### ISSUE TITLE
[Discovery] Evaluate ability to programmatically retrieve realtime analytics data from Prometheus

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#100]
## Description
From early discussions with Edu stakeholders we've heard that they want to easily understand if the tools they own are up (uptime)

## User Story
As a Product Owner, I need to have automatic, regular, and easy to consume updates of up/downtime in order to use data regularly as a part of my workflow.

## Discovery Question
Can we pull real-time data that shows whether a tool is online and display it somewhere for edu stakeholder to access.

## Constraints/Assumptions
- We can pull the data programmatically
- Prometheus is the right tool for the job

## AC 
- [ ] Discovery has been conducted
- [ ] A readout of findings is documented
- [ ] If we can pull the data from prometheus, realtime or otherwise, update the Google Sheets MVP so that the fields populate automatically.

**Comment by jholton** [comment]
A lot of this discovery was done during discovery for a `backed_statuses` endpoint creation.
You can find that discovery document [here](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16830).

The potential issues with querying Prometheus directly as explained in that issue by @wyattwalter:
> We definitely should be caching this data somewhere in the API, I’d be very concerned about a publicly exposed endpoint where a client could trigger a query back to the Prometheus node

> Prometheus is also a single node in each environment, not really built to be high-traffic. I say that assuming that the loading of this status page would inevitably result in many API calls to Prometheus

Ultimately, it was decided to use the Pager Duty API to obtain the current status for upstream backend services.

Prometheus talks to Pager Duty via an [integration](https://www.pagerduty.com/docs/guides/prometheus-integration-guide/)

The `backend_statuses` endpoint in `vets-api` is finished and in production, but is currently not consumed by any client.  
This is probably our best current resource for determining the current up/down status of stakeholder product services.

**Comment by batemapf** [comment]
Slightly off topic, but any chance `backend_statuses` includes the statuses of our identity providers, namely DS Logon?

**Comment by jholton** [comment]
Yes, I see DS Logon, MyHealtheVet, and ID.me.
If you have a PagerDuty account, you can browse the monitored services here: https://dsva.pagerduty.com/services/

**Comment by wyattwalter** [comment]
The decision here is to cache this data still, correct? PagerDuty has API limits that we'd hit pretty quickly (plus it'd be slow).

**Comment by jholton** [comment]
Yes, there is currently a Sidekiq job that hits the PagerDuty API once per minute and stores the data in Redis.

**Comment by joanneesteban** [comment]
@jholton Is it possible to output the current uptime/downtime data into a sheet (such as this: https://docs.google.com/spreadsheets/d/1go-gIeGXb_W-XdJzW3xLT__UUspXX5hwfY2K0ovqkTo/edit#gid=1289815191)

**Comment by jholton** [comment]
I have not looked deeply into this, but off the top of my head, I believe the answer is 'yes'.
Google provides an API for Sheets.  As mentioned above, we already have a job in place that gets the current status of services from Pager Duty every minute.  We could create another job that then posts that data to the relevant Google Sheets.

To clarify what this service status data is communicating: 
The status can be one of the following: `active`, `warning`, `critical`, `maintenance` or `disabled`
From the Pager Duty docs:
```
The current state of the Service. 
Valid statuses are:
- `active`: The service is enabled and has no open incidents.
- `warning`: The service is enabled and has one or more acknowledged incidents.
- `critical`: The service is enabled and has one or more triggered incidents.
- `maintenance`: The service is under maintenance, no new incidents will be triggered during maintenance mode.
- `disabled`: The service is disabled and will not have any new triggered incidents. 
```

**Comment by rroueche** [comment]
@jholton and @joanneesteban heads up that I updated the last acceptance criteria a little to: ```If we can pull the data from prometheus, realtime or otherwise, update the Google Sheets MVP so that the fields populate automatically.```

**Comment by joanneesteban** [comment]
Discovery has been completed and the build for automation is high effort. Created a new issue to address the automated Prometheus pull, which will need an engineer assigned, and closing this discovery ticket.
