### ISSUE TITLE
Left Nav "In this Section" Mobile Duplicated

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#10002]
## What happened?
"In this Section left nav block is duplicated, one is non-functional"

![Left Nav in this section.jpg](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/43ef26a8-c105-486a-a4c2-cd48a541abf8)

## Specs:
- Device: iPhone Xs
- Browser: Safari
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL: https://www.va.gov/pittsburgh-health-care/
- Test User _(if applicable)_: N/A

## Desired behavior
Only one "In this section should be there (the one with the hamburger)

## Acceptance Criteria
- [ ] More in this section > removed
- [ ] In this section hamburger works

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
This was reverted because the implementation caused other problems. Re-opening.

**Comment by mpelzsherman** [comment]
Bumping estimate from 2 to 5 due to need to isolate this change to VAMC pages only.

**Comment by mmiddaugh** [comment]
![image](https://user-images.githubusercontent.com/55411834/93826608-d6bdb300-fc24-11ea-9965-a600551dafe2.png)
