### ISSUE TITLE
Access for Michael Chelen

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#10004]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > N/A
- Please provide your name.
   > Michael Chelen
- Please Provide your email.
   > michael.chelen@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA Digital Services, Healthcare Products, Engineer
- What is the **public** SSH key?
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDH6kL+d6EWErv4TjAeBoncaqmrQyqyJ17jfMVeWXFjklaOg6XlbqFMUkIWH/M8wn7fYBUYfcon41BhNwNbIj4Vquar4tiHkg7YlSiDXhdecuCnGB3Ti30O7G4mTV4Odm2BqS+HRWIvHEAafJk5Jl4DJGVhDTNGga4KCiW0xDovXrzCuMmBeL0ETHGVWflyFY7mkNnOCwVZgfeGT3yVV+j96WyrhoAuU0opRfLuvXL0D4ZxoqyqvUBGQPO+VYDwLngg5q2rhbqQ0jOSZS+V6G8g58IM7qiaDlj0KL8gYT44TvufXV6CUl1qPTYEN34uVoM0d8VNkrDdbEL8q+idnZT54g9lRrqlYNph6ySGLyrvAZnEereQ08y32ip8QLu5MtkdstnJH1Vf4oSPtB2Y5Y/8F68SbLhSUVqJd3PQrBUPJl2wR5CZJn7w9EMY2wIRnkHZFk94tA1YPVbRjRila3RK49NjxxfDvLtlCjfc0r87eG2ffDT6EAJVV459YponWmuTHh9iBU0Bb6NKUhtgfPMk0x0hhr76SSrecUNxsh/GK9uSRQwpTOhjbi5TV4UNNwzNKpffUYTKzfzshtKr0opwi9W9DaIc9vczb+QMyhvPRNoipYC37PXNa7kDb3K7vBIivEjolKxrf5X7EBiVk+i+qS9FnIbpZLiIfwJfkW1Vuw== michael.chelen@va.gov
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by mchelen-gov** [comment]
Hey just realized I need AWS Console access, for debugging BE applications in AWS env. Can someone set that up?

**Comment by tskinn** [comment]
@Jeff-Hayter

**Comment by jbritt1** [comment]
Sorry, was out on PTO so trying to catch up. Yes, it is correct that you already have a provisioned admin level account (Mike.Chelen). Would you like me to reset the password?

**Comment by jbritt1** [comment]
@mchelen-gov, what can I do to assist you on this? Do you need a password reset? Or is this resolved at this time?

**Comment by mchelen-gov** [comment]
@jbritt1 Oh that's alright, I wasn't sure if I had console access or not. Looks good, thanks for following up!
