### ISSUE TITLE
Contact Center Review for Medical Device Reordering Tool 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10007]
**Product Description:** the Medical Device Reordering Tool allows eh Veteran to order hearing aid batteries and accessories online. It replaces a legacy eBenefits ordering system and adds functionality to order accessories the legacy system does not support. Prosthetic socks ordering will remain with legacy system and is slated to be migrated to va.gov at a later date

All fulfillment and  contact center support is handled by the Denver Logistics Center (DLC) - Their telephone number is provided to the veteran. 

Here is the Product Guide: [https://app.zenhub.com/files/133843125/fc3d5d9c-2ec4-4143-b228-cf4d7f67b0a1/download](https://app.zenhub.com/files/133843125/fc3d5d9c-2ec4-4143-b228-cf4d7f67b0a1/download)

Here is the Happy Path Video:

https://slack-files.com/THYGV9KQU-F016Q4F5533-3386967443

Here is the Happy Path Video Transcript: 
[https://app.zenhub.com/files/133843125/abe3befc-ea64-4a9b-8f9d-086f16cd094d/download](https://app.zenhub.com/files/133843125/abe3befc-ea64-4a9b-8f9d-086f16cd094d/download)

Here is the Common Errors Video:

https://slack-files.com/THYGV9KQU-F015WP1SRAT-f1bff60969

Here is the Common Errors Transcript:
[https://app.zenhub.com/files/133843125/f7cda366-bf26-4125-a453-b1ea97a3dbee/download](https://app.zenhub.com/files/133843125/f7cda366-bf26-4125-a453-b1ea97a3dbee/download)

Planned Launch date - 7/08/2020 [Release Plan here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/Release%20Plan.md)

**Comment by Kimberley2019** [comment]
@leahkeeler after review it appears to have all the required information, however, I am unsure if the external contact center has access to Slack (in which the videos were recorded).  I am in the process of determining with @clantosswett if this is going to be an issue.

As long as there have been no edits to the content that has been provided and they are able to view the videos in Slack, I will pass along to the contact center to ensure that they do not have any feedback.

Can you advise that no additional content has been added or updated?

**Comment by leahkeeler** [comment]
Hi Kimberly, The video is viewable in a browser - can you please confirm? The content is complete 

Thanks!!! Leah

**Comment by Kimberley2019** [comment]
After speaking with Chante, the videos should not be an issue.
I will pass along to the appropriate contact center and obtain feedback.

**Comment by Kimberley2019** [comment]
@leahkeeler I have passed the information along to the Contact Center for review and they have until COB on 7/1/2020 to advise if there are any questions or feedback to provide.  If not, then the information is fine as is.

One suggestion that I have is to include a table of contents as mentioned in the self service product guide documentation.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md

**Comment by leahkeeler** [comment]
@Kimberley2019 We found a small issue and have updated the documents and videos. Can you pull the current ones back and I will have the new uploaded later tonight. Sorry for the inconvenience but we had a late development design change that was not captured in the originals. I appreciate your help - Leah

**Comment by Kimberley2019** [comment]
@leahkeeler I will advise that there has been a slight update and the new documents and videos will be sent over later this week.  
Thank you for getting back to me so quickly.  I will be on the lookout for the updated information.

**Comment by leahkeeler** [comment]
@Kimberley2019 The links above have been updated. Please let me know if you have any issues downloading the video as it exceeds the github size limits and we linked it to slack

**Comment by Kimberley2019** [comment]
@leahkeeler Thank you for the update.  I will review and send out if there are no issues.

**Comment by Kimberley2019** [comment]
@leahkeeler I receive an error message when attempting to view the Product Guide (first link).  Can this be fixed or is it just an error that I am receiving?

Please see below.



[image.png](https://images.zenhubusercontent.com/5d3b2f7176f8655a8ad39ace/3235268e-28a2-43fa-a1bf-ee26095d9abf)

**Comment by leahkeeler** [comment]
@Kimberley2019 The link is a download - it does work. Check to see that your browser settings allow downloads, otherwise I can just email or slack it to you (if you have slack) Let me know what is best.

**Comment by Kimberley2019** [comment]
@leahkeeler Thanks!  I have sent it over to the Contact Center for review and feedback.  I asked if they could get that back to us today if at all possible.

**Comment by leahkeeler** [comment]
Thank-you @Kimberley2019 and have a great long weekend!

**Comment by Kimberley2019** [comment]
You are very welcome @leahkeeler thank you so much for your patience.  I hope that you have a great long weekend as well.

**Comment by Kimberley2019** [comment]
@leahkeeler Please see response from Contact Center below and advise if the errors can be incorporated into  the product guide.

_Hi Kimberly,

Have we not been getting the errors added to the product guides?  The videos are great for training, but we link the product guides to the KM and agents need to know what types of errors they will receive that way.  They won’t have time to watch a video on a call._


_Thanks,
Lana_

**Comment by leahkeeler** [comment]
@Kimberley2019 Sure we can add the common errors into the product guide - I will let you know when it's uploaded  Thanks!

**Comment by Kimberley2019** [comment]
@leahkeeler You're the best!  Thank you so much!  I will await your update.

**Comment by leahkeeler** [comment]
Hi @Kimberley2019 - the errors are there, what happened to me is the doc doesn't load until you scroll down - make sure all 12 pages are loaded. I can. .pdf it as well if that will help just LMK

**Comment by Kimberley2019** [comment]
Hi @leahkeeler I have sent them the information that you have provided and advised that if they are referring to other errors, to please advise me.

**Comment by leahkeeler** [comment]
@Kimberley2019 Just a heads up , the release slipped by a week to 7/15. Please let us know if there are any additional questions.

**Comment by Kimberley2019** [comment]
@leahkeeler that you for the update.  I have reached out to the Contact Center again and have advised that all feedback needs to be received by 5 PM ET today in order to resolve this matter.
If I do not receive any additional feedback from them today, then the information that was provided to them will be what they use for training their agents on this tool.

**Comment by leahkeeler** [comment]
Yes, we will update shortly- Thanks for letting me know - Leah

**Comment by Kimberley2019** [comment]
Much appreciated Leah!

**Comment by leahkeeler** [comment]
The table of content has been added to the product guide. Please let me know if anything else is required. Thanks for all your help and have a wonderful weekend! -Leah

**Comment by Kimberley2019** [comment]
This updated information has been shared with the Contact Center and advised that agents utilize the tools that they have been provided to assist end users on this topic.
If any concerns or issues arise they have been informed to notify us as quickly as possible so that we can relay any important details back to the team for review.
