### ISSUE TITLE
[Analytics] Add Personalization Failures to Product Health MVP V1

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1001]
## User Story
As a Personalization decision maker, I need Google Analytics for my forms on the Product Health MVP so I can see my product's health at a glance.

## Goal
Add personalization failures Google Analytics data to V1 of the product health MVP.

## Acceptance Criteria
- [ ] Add Google Analytics personalization failure data to the product health MVP
- [ ] _Stretch_: Automate Personalization Failure data to product health MVP

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

CC: @amycesal for design verification.

**Comment by joanneesteban** [comment]
#1165

**Comment by nedierecel** [comment]
Going to close this issue that has been in backlog since we are pivoting the Product Success Tool to focus on Education.
