### ISSUE TITLE
update setup documentation 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#10018]

**Comment by laineymajor** [comment]
@ndsprinkle can you review and let me know if this is a duplicate or can be merged with your new work?

**Comment by ndsprinkle** [comment]
@laineymajor Yes, I'll see if we have any similar tickets. This may not be relevant anymore given how long ago it was created and the fact that this documentation lives in another location now.

https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html
https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html

**Comment by laineymajor** [comment]
Closing as this documentation lives in another location currently. 

https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html
https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html
