### ISSUE TITLE
Update VVC appointments to show VVC instructions

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10016]
As a Veteran with a VVC appointment, I want to be able to see any instructions for how to prepare for my upcoming VVC appointment. 

## Acceptance Criteria:
- [ ] Display the following copy when "instructionsTitle" is "video visit instructions"
**Before your appointment:**
- If you’re using an iPad or iPhone for your appointment, you’ll need to download the VA Video Connect iOS app beforehand. If you’re using any other device, you don’t need to download any software or app before your appointment.
- You’ll need to have access to a web camera and microphone. You can use an external camera and microphone if your device doesn’t have one.

To connect to your Virtual Meeting Room at the appointment time, click the "Join session" button on this page or the link that's in your confirmation email.

**To have the best possible video experience, we recommend you:**
- Connect to your video appointment from a quiet, private, and well-lighted location
- Check to ensure you have a strong Internet connection before your appointment
- Connect to your appointment using a Wi-Fi network if using your mobile phone, rather than your cellular data network

- [ ] Display the following copy when "instructionsTitle" is "medication review instructions"
During your video appointment, your provider will want to review all the medications, vitamins, herbs, and supplements you’re taking—no matter if you got them from another provider, VA clinic, or local store.
Please be ready to talk about your medications during your video visit to ensure you're getting the best and safest care possible.

- [ ] Instructions should be available to Veteran at all times (not just when the 'join' link is active)

- [ ] Include test case for this addition in our test cases

## Mock-up -- see this ticket (#7951) for background on the mockup
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/54d1eaee-89fa-42a1-b643-44fa88da3a4d)

**Comment by jbalboni** [comment]
Also note, we may need to abandon the AdditionalInfo component for this, since we want to put all the actions next to each other horizontally and we want to get rid of the blue bar on the left side.
