### ISSUE TITLE
Redirect Request - Remove an inactive (but still in our code) redirect for add dependents legacy page

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10026]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

Based on the the findings related to #9966
There is a redirect that was set up in a PR a couple months ago that is not active (the legacy page is missing the injection script to make it active). We need to remove the redirect code so that, in the event the legacy page is updated to include the injection code, the redirect does not start working without a new discussion with stakeholders. 

This ticket is based out of our findings at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/post-mortems/redirect-06-09-20.md

The removal of this redirect will not have a noticeable impact on users as it (currently) does not work. But we need to make this happen to avoid another future surprise with a redirect suddenly becoming active.

### Requestor team info
Public Websites - Stephanie Orkand

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed to be removed

https://benefits.va.gov/compensation/add-dependents.asp -> https://www.va.gov/disability/add-remove-dependent/

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@stephorkandatx We had the same issue on the C&P exam legacy page.   https://www.benefits.va.gov/compensation/claimexam.asp 

Do we also need to remove the redirect from that page or was it never implemented?

**Comment by stephorkandatx** [comment]
@mnorthuis the redirect in question was removed in #9966 . 
That was one of the tickets that was made without the redirect request template (my apologies) and did not have you as an assignee. I just added you to it so you should see an alert.
