### ISSUE TITLE
[Release date 07/15] Redirect Request: Hearing aids and prosthetic socks page

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#10027]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
The existing static page for ordering hearing aids and prosthetic socks will be split into 2 separate pages.  Once the new pages are up, we need to redirect the old URL to retire it and ensure no users receive a 404 when clicking on links, bookmarks or search results. 

### Requestor team info
BAM2 - @leahkeeler 

### Implementation date
Date new URL(s) will be live: **Launch date scheduled for 07/15**

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [x] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
https://www.va.gov/health-care/order-hearing-aid-batteries-prosthetic-socks/ | https://www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@lunascoop This is the redirect required to change the URL for the existing hearing aid/prosthetic sock page to the new URL.   This is vetted and can be implemented once the new hearing aid static page is live.

**Comment by kelsonic** [comment]
Is this ready for me to send up a PR yet? 🙂 CC @lunascoop @mnorthuis

**Comment by mnorthuis** [comment]
Timing is driven by the BAM2 team, @leahkeeler can you provide an update on launch plan for the new content pages?

**Comment by leahkeeler** [comment]
@kelsonic - Our business partner has slipped their date to move the API to a service - I am going to have a new date after meeting with them this afternoon. Thanks for your patience

**Comment by leahkeeler** [comment]
@kelsonic New Launch date is 7/8/2020 I will let you know if anything changes. Thanks! Leah

**Comment by MickinSahni** [comment]
Confirming this is scheduled to go out with the daily deploy this Wed (7/8)
cc @leahkeeler @mnorthuis

**Comment by leahkeeler** [comment]
We have a go/no-go meeting at 2pm et - I will let you know right after. Issues--> They found that queries are causing time-out resulting in  500's. My bet is this is getting pushed, but keep your fingers crossed.

**Comment by MickinSahni** [comment]
Pulling out of Sprint 25 to coincide with new launch date
@lunascoop can you add the blocker bug in front of this one?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop @kelsonic. The new pages will be going live in tomorrow's (7/15) deploy. Can you please coordinate redirect for tomorrow? Thank you!

FYSA @MickinSahni @RLHecht

**Comment by kelsonic** [comment]
Sounds good! PR is already up, I will be sure to merge it tomorrow morning 🙂

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @kelsonic!

**Comment by kelsonic** [comment]
After discussing with @bradl3yC it sounds like the URL should be redirected to https://www.dev.va.gov/health-care/order-hearing-aid-batteries-and-accessories/order-form-2346 instead. Is that correct? If so, we should update this ticket and I'll send up another PR for the new destination 🙂 

CC @DanielleThierryUSDSVA @mnorthuis @leahkeeler

**Comment by mnorthuis** [comment]
@kelsonic per our slack conversation, the redirect documented here is accurate, we do not want the static page redirecting the form, we want it redirecting to the new static page per the original description.

**Comment by kelsonic** [comment]
Perfect, thanks! 🙂

**Comment by lunascoop** [comment]
Redirect has been validated and confirmed as working. Closing ticket.
