### ISSUE TITLE
Fix location prop issue ProfileWrapper

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#10037]
We need to come up with a way to use `location` in ProfileWrapper so that we can render the BreadCrumbs properly. 

We need to either pass it via the `Route`, or use the `getLocation()` hook.

**Comment by erikphansen** [comment]
@mshea0606 you can confirm this by checking that the breadcrumbs work correctly on Profile 2.0. Previously the last crumb was not showing up at all.
