### ISSUE TITLE
Home breadcrumbs for Pittsburgh health care website

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10038]
## Issue Description
Currently, the breadcrumbs across https://www.va.gov/pittsburgh-health-care/ all begin with 
`Home  >`, taking the Veteran back to https://www.va.gov/. 

![image](https://user-images.githubusercontent.com/55411834/84298254-0d573e00-ab0c-11ea-949e-dd8385573a8d.png)

Veteran feedback indicates that Veterans using the Pittsburgh health care website view https://www.va.gov/pittsburgh-health-care/ as "Home" and expect to be taken back to that as the home page. 

## Tasks
Remove `Home  >` across https://www.va.gov/pittsburgh-health-care/ for VAMC products **only**

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
merged and working on prod

**Comment by mmiddaugh** [comment]
@mpelzsherman @brangi the following liquid layout templates are **not** part of VAMC sites and **should not** be impacted by our Breadcrumb changes:

As listed in layouts
- page.drupal
- landing page.drupal
- home.drupal
- office.drupal

**Comment by brangi** [comment]
Merged
