### ISSUE TITLE
VFS Support: Analytics Request for DIC Entry Points

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#1004]
A stakeholder within VBA has requested a review of our current placement for the DIC page (link below).  We currently have this page within the Burials and Memorials section of the site but we want to evaluate where this content best fits - Disability, Pension or Family hub. 

DIC page: https://www.va.gov/burials-memorials/dependency-indemnity-compensation/

Back in July after the initial request, I looked through GA to the best of my knowledge to try and understand how users were finding the DIC page.  I used the navigation summary view for a 6 week timeframe.  A screenshot if what I looked at is attached.   Based on this, I concluded that about 32% of visitors were coming from a page in Disability, 28% from Burials, 15% from Family and 2.5% from search. 

Questions I have:
1) Is this the best GA view to see how users are ultimately arriving at the DIC page?
2) Is the 6 week timeframe enough time for confidence in the data?  (It's a low trafficked page)

In addition, I need to look at the following data:
1) How many users are clicking on the DIC link in the Disability top nav versus the Burials top nav
2) How quickly are users finding the DIC page in their session (i.e. are they looking all over the site before landing there?)
3) Are we able to see the internal search terms users are entering to get to this page?

![2019-07-18_9-19-52](https://user-images.githubusercontent.com/20994159/63111715-e49a0280-bf53-11e9-8784-ab50050c7e4f.png)

**Comment by mnorthuis** [comment]
@nedierecel @joanneesteban  Not sure of the turnaround time for this request, but hoping we can answer the above questions within a week.  Can you let me know?

**Comment by nedierecel** [comment]
@mnorthuis Thanks for looping me in. A week should be a good amount of time to provide you with answers. 

1. Great work on looking at the behavior flow. This is the first report I would look at as well.
2. I would probably extend to the past 90 days to look across the season. 

Feedback on your questions before I go hunt:
1. This should be possible.
2. I'll look at a few ways to slice this.
3. This report provides the top terms users looked for that landed them on the DIC page: https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-search-terms/a50123418w177519031p184624291/explorer-table.secSegmentId=analytics.searchAfterDestinationPage&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.searchAfterDestinationPage%22,%22PT%22,%22~2Fburials-memorials~2Fdependency-indemnity-compensation~2F%22,0%5D%5D/

**Comment by mnorthuis** [comment]
Hi @nedierecel, just wanted to check in on this.  Were you able to find any additional data?

**Comment by nedierecel** [comment]
Hi @mnorthuis - I have progress on #2 and created a custom report you can [view here](https://analytics.google.com/analytics/web/?authuser=0#/analysis/a50123418w177519031p184624291/edit/0OeFDpyUTlepXhtu0N983w)

In short, more users open the Disability nav and access DIC from there.

For request #3, I don't have an average or range but can share a deeper report that mirrors the behavior report you linked to. It goes deeper into [common paths](https://analytics.google.com/analytics/web/?authuser=0#/report/content-engagement-flow/a50123418w177519031p184624291/_u.date00=20190520&_u.date01=20190820&_.useg=&_r.navigationNode=%25257B%252522entityCondition%252522%25253A%25257B%252522leaf%252522%25253A%25257B%252522keyFilter%252522%25253A%25257B%252522key%252522%25253A%252522request_uri%252522%25252C%252522matchType%252522%25253A%252522PARTIAL%252522%25252C%252522expression%252522%25253A%252522~2Fburials-memorials~2Fdependency-indemnity-compensation~2Findex.html%252522%25257D%25257D%25257D%25252C%252522label%252522%25253A%25257B%252522customValue%252522%25253A%252522~2Fburials-memorials~2Fdependency-indemnity-compensation~2Findex.html%252522%25257D%25252C%252522type%252522%25253A%252522CUSTOM%252522%25257D&_r.inspectStep=1&_r.stepsLeft=8&_r.stepsRight=1&_r.hlNode=10-0-265644698/)

When you review, you can look at Step 0 and then work backwards to see what paths lead them there:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/1b232c41-e349-4597-8ce5-89bbc1528d3f)

Observations:
1. Like the report you found, most are coming in from the Disability hub (which is mostly driven by direct entrances to the site or by visits from the homepage)
2. The Burials and Memorials hub is the second-ranked preceding page. Users reach that hub most often from direct entrances to the site or from the homepage.

**Comment by joanneesteban** [comment]
@nedierecel Is this ready to close, or are there still data points that we need to add?

**Comment by mnorthuis** [comment]
Its on me to document this within my files and then I will close.  I will take Nedie off so it comes off your board.

**Comment by joanneesteban** [comment]
Sounds good! Thanks, Mikki!

**Comment by mnorthuis** [comment]
Summary of results copied here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/dic/ia-placement.md

closing issue
