### ISSUE TITLE
Explore ways for writing better front end integration tests

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10056]
Front end integration tests would be tests that cover multiple components and/or Redux logic in the same test. We do some of this inadvertently, but mostly we write unit tests and e2e tests.

Ideally, I would like to have a set of tests that cover most or all of the business logic on the front end that closely reflect how a user actually uses the page or functionality being tested. For example, that would mean testing an appointment card within the context of the appointment list, with the mock data we use run through all of our Redux logic. 

A non-technical user should be able to read through these test names and understand the behavior being tested (even if they don't understand the test code).

There are a few options for where to write these tests:

1. Write more Cypress/Nightwatch tests. These are browser tests, so we can only mock at the api level, which forces them to be integration tests. But these are typically slower and don't give us code coverage numbers.
2. Write more Enzyme tests using `mount`. We can mount higher level components and test that way by mocking fetch. However, it's hard to wait for async code in Enzyme without access to the promises called. And Enzyme encourages tests that dig into the implementation details of React components.
3. Use a library like react-testing-library. Another team is advocating for adding RTL and this library would make writing integration tests with JSDOM much easier for us.

**Comment by jbalboni** [comment]
Based on the couple PRs I've written and @narin's comments about Cypress, I think option 3 is the better option. Cypress isn't wildly more efficient to write tests in than Nightwatch, so while it's hopefully more stable and readable, it's not clear that widely expanding our usage is a good idea.

Enzyme tests using `mount` are very likely to keep us in a position where most of our tests break after refactors.

RTL so far, while not world-changing, seems to be pretty easy to use and keeps us away from writing lots of brittle selector based tests.

I wrote up some testing guidance here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/testing/fe_testing_guidance.md
