### ISSUE TITLE
Evaluate consumer driven contract testing 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1005]
## Problem 
- scripting and managing integration tests that run `vets-api` + `vets-website` are complex, brittle, and difficult to maintain 
  - some state management is difficult to coordinate 
  - there are several approaches to testing in `vets-website` that have various tradeoffs 
- lack of tests that test integration with `vets-api` reduce confidence of api changes that don't involve FE engineers 

## Tasks 
- Evaluate pact as a means to testing `vets-api` integration: https://docs.pact.io/

## Notes
- ideally consumer driven contract tests cover all important serialization / deserialization logic (e.g. prefill transformers, pre-submit transformers)
- maybe evaluate the way data is used in `vets-website` in general. in some of our apps we spread data transformation logic throughout components which can make regression tests that represent all of the ways data is transformed difficult to write.

**Comment by meganhkelley** [comment]
Evaluation is complete, implementation is tracked in #7353
