### ISSUE TITLE
Write test scenarios for Appointment List

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10050]
Helpful to follow the BDD format of:

**[Header] Scenario - Task**
- GIVEN ...
- WHEN ...
- THEN ...
- AND... (when more context needed)

...Need to add the scenarios for...
- list out scenario types

### Reference test scenarios for Appt List -- https://gist.github.com/jbalboni/66edd517c06e6e4d821f874435915951

**Comment by jbalboni** [comment]
These scenarios are all entered into TestRail
