### ISSUE TITLE
What is covered by AppDynamics alerts?

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#10063]

**Comment by LeakyBucket** [comment]
A bit of foundational information on AppDynamics.  It tries to be "intelligent" and determine severity on its own.  Most of the built-in tooling is intended to be driven by that internal logic.  For most of its health

Current alerts in AppDynamics:

National Portal:
  * Calls per minute low
  * Database count high
  * High CPU usage
  * Resource pool limits reached
  * Response time is high
  * Server restarts 

_Resource pool limits reached_, and _Server restarts_ look to be set on "custom" activities.  The pool limit alert is configured to fire any and every time the condition is met and sends to: eric.robertson@va.gov, tuong.ngo@va.gov, jessica.robertson2@va.gov, an.tran@va.gov, emmanuel.tudeme@va.gov and jason.heap2@va.gov.  The _Server restarts_ alert also fires on any server restart event and sends to: eric.robertson@va.gov and raquel.robertson@va.gov.

The remaining alerts are configured to fire based on AppDynamics "baseline" measurements.  They are all set to alert only when the _Health Rule_ is determined to be critical.

**Comment by batemapf** [comment]
Very helpful info. Triggering an alert on `Server restarts` seems incongruous with the idea of an alert — the team should already know that a server was restarted because they are being manually restarted. Maybe this is in anticipation of some kind of self-healing behavior so the can be aware if things are going down and restarting at a too high frequency. Or maybe it is just another way to keep track of how often the team is restarting servers.

I assume AppDynamics keeps a log of all alerts that have been triggered — any interesting patterns in there? E.g., alerts that never get triggered or alerts that get triggered all the time?

Interesting on the ServiceNow integration. I'd be interested if those tickets are then picked up and assigned by Tom, probably back to the operations team. If so, this feels like a pretty circuitous route to addressing slow response times.

Finally, I'm interpreting this to mean that the employee facing application(s) (pretty much Secure Messaging...?) and the administrative application(s) don't have triggers set up?

> None of the other applications have alerting policies setup in AppDynamics.
