### ISSUE TITLE
CTO view access to stuff monitoring team is looking at

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#10062]

**Comment by LeakyBucket** [comment]
I currently have access to all the monitoring tools except for Spotlight:

  * [Grafana](http://vac10monmhv200.va.gov)
  * [Kibana](https://vac10logmhv200.va.gov) - only works in Edge 😢 
  * AppDynamics
  * CloudWatch

I also have access to [Rational](https://clm.rational.oit.va.gov/ccm/web/projects/MHV%20%28CM%29).

I believe Jira access is in the works.

**Comment by LeakyBucket** [comment]
Oh, I almost forgot about Google Analytics.  I do not have access to that at all, although it sounds like that is somewhat external to MHV.  Or is it just "outside" the domain of the Operations team?

@batemapf do you know?

**Comment by batemapf** [comment]
See this thread in [#vfs-analytics](https://dsva.slack.com/archives/C1Q4294JJ/p1591724269155800). TL;DR, we have access to at least some https://www.myhealth.va.gov/* data in this GA [view](https://analytics.google.com/analytics/web/#/realtime/rt-content/a50123418w177519031p176188361/_.useg=&filter.list=10==www.myhealth.va.gov~2Fmhv-portal-web~2Fhome~2F;/). Haven't messed around with it to see if there are custom tags/events or if it is just an off the shelf GA implementation. Will create a ticket to do just that!

**Comment by batemapf** [comment]
@batemapf submitted his Jira request (email + PIV exp.) on 6/12.
