### ISSUE TITLE
Gatsby Client side documentation links and images are broken

### ISSUE THREAD

**Issue by accbjt** [department-of-veterans-affairs/va.gov-team#1006]
Links on the gatsby site are broken. We need to look into why this is happening and what we can do to fix it. Images on pages also look very weird.

![Screen Shot 2019-08-15 at 10.32.25 AM.png](https://images.zenhubusercontent.com/5ac3be554b5806bc2bcd7ea1/968d5fbd-c81c-4d8d-b26a-7aa7af05b415)

**Comment by accbjt** [comment]
@rianfowler @andreahewitt-odd Not sure who's responsibility for this is but we should fix this.

**Comment by andreahewitt-odd** [comment]
@brandonrapp Any idea which team is responsible for working on this?

**Comment by rianfowler** [comment]
@accbjt can you elaborate on the issue? what links are broken? how do i recreate this issue?

**Comment by meganhkelley** [comment]
I changed this back to an issue, which now rolls into epic: MVP of Gatsby as documentation site portal #2131 which rolls into super epic: Determine documentation site approach #2130

Please reach out with any questions/comments!

**Comment by meganhkelley** [comment]
As far as I know this is fixed; if we encounter this issue again it will be tracked as a separate bug report.
