### ISSUE TITLE
Review grouping / fingerprinting that Sentry does (Prod Error Handling)

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#10086]
Sentry groups by finger print of the exception class. We need to get better at more granular breakdowns wherever possible because VAOS::Appointments#index 500 errors for example could have resulted from 5 different types of issues on the VAMF side for all we know. 

it's not enough to just run through a handful and look them up in Kibana and write up a ticket. We need to mindful of this deficiency in the grouping or verify what the underlying issue might have been more regularly even for endpoints for which we've previously opened up tickets.

UPDATE:

Our vaos errors middleware is part of the problem here. I think we want our VAOS specific application errors to return more of the payload of the we get from VAMF. In certain cases we will override these errors with exception.en.yml, but we should look at parsing their error payloads and including things like source id and other bits of information in the payload we ultimately send to the FE. We can provide this additional detail in the "source" field of the JSON payload we send up. This will make it easier to triage directly from FE to VAMF as opposed to having to first find the corresponding BE issue with the VAMF payload. Furthermore, I am hoping that this will also provide us some improved fingerprinting of exceptions. Please try to see what the latest Sentry 10 does in the way of fingerprinting and document what you find as part of this ticket.

**Comment by lenaecb** [comment]
@saneshark - i want to try and knock out some of these high priority prod error handling tasks in this sprint. Given what was discussed with the VAOS team, is this something we want to tackle sooner than later?

**Comment by saneshark** [comment]
This one is going change dramatically once the VAR Resources changes go into affect so it doesn't make sense to look at it now. We might find that no further action is necessary if the error payloads we receive are more informative.

**Comment by saneshark** [comment]
This is actively being reviewed by VSP right now. Unrelated to the original reason this issue was created, the upgrade to Sentry 10 has introduced an entirely different way that platform-api Sentry behaves in its grouping.

For example, when I identify an exception related to specific controller and I drill down into that exception, previously I used to be able to click on events and view other instances of that same error. This worked as expected. Instead, now we're seeing exceptions that are completely different than the original all getting grouped together. We don't have any way of fixing this, but will continue to see what VSP comes up with as a solution so that we can close out this ticket. Not much we can do until they make the more macro changes needed to get to a similar grouping to that which we had under Sentry 9.
