### ISSUE TITLE
Getting local backend stack setup (Prod Error Handling)

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#10085]
We want to be in a position to more meaningfully contribute to BE Team in addressing bugs. I think one of us from the Rails middleware side should try to get their local stack setup for now, but ideally we would all be in a position to scrub in and help where possible.

**Comment by ajmagdub** [comment]
got the code repositories for VAR and VAMF projects on my local computer. Some of the repositories no longer are used, especially true for the mock repos. But the major repos such as var-resources are at a point where i can use them to assist in issue resolution.
