### ISSUE TITLE
Identify triage process improvements

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#10088]
I think an RFC is going to be one of the most transparent, least adversarial ways of instituting some much needed change in the triage process.

**Comment by lenaecb** [comment]
@saneshark - this is currently being discussed throughout the VAOS suite team (not just VAOSR on VA.gov). 

Are you taking lead on this? I want to make sure we scope this appropriately so it doesn't hang around as a 'to do.'

**Comment by saneshark** [comment]
In discussion yes, was waiting for conversation on 6/26 with Barrs, Case, and others before and writing something up to share after that discussion.

**Comment by lenaecb** [comment]
@saneshark - what's your plan for this? Did you plan to get a RFC documented, or was that going to be a team effort with Barrs and Brad?

**Comment by lenaecb** [comment]
@saneshark @laurenernest - bringing this back based on recent conversations of the need to solidify our process even further. 

Here is where we landed previously from a triage process that highlights when an issue is 'veteran reported.' What we need to clarify further is when help desk items are triggered from Veteran HCD input, how are we working through/managing with the VAOS prod team?

The other area that still needs work is for items discovered more proactively through our performance analytics and logging. 

Additionally, we need to sync with the VSP BE team to see how we can provide some of our more granular production monitoring analytics to their SLO report. Per request of Chris Johnston. 

Let's make some working tickets for these items if we need to.

**Comment by lenaecb** [comment]
Here is the doc I reference - https://docs.google.com/document/d/1hy-OVjp79AyKKbJXFuiCc6Fh8TLnXph7ebsU7gQYJXc/edit

**Comment by laurenernest** [comment]
@grossb1 assigning to you for next steps

**Comment by grossb1** [comment]
Next action item -
Schedule meeting with the team to review that above mentioned issues.

**Comment by ldelacosta** [comment]
We might want to revisit this item once V2 is almost done. 
@JRRoof @simiadebowale

**Comment by JRRoof** [comment]
Old issue, no longer needed.
