### ISSUE TITLE
App Dynamics dashboard (Prod Error Handling)

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#10082]
This is more a matter of finding what exists currently and how it might be deficient in elucidating the types of problems we're seeing. 

I think we can hand this one off to Larry Norcross on his team to do discovery on though. It would still be good for us to be more familiar with this however.

**Comment by lenaecb** [comment]
@saneshark - I think this one can wait for now. We should add this to our recommendation for a shared process as an action item, but it doesn't seem like an action item for our team.

**Comment by saneshark** [comment]
Sitting in on a conversation regarding this for 6/26

**Comment by lenaecb** [comment]
@saneshark - cleaning up our backlog a bit. we haven't touched this and I don't know if it's in our cards to touch it soon or ever. close out?

**Comment by saneshark** [comment]
Yeah, this can be closed.
