### ISSUE TITLE
How do we determine the number of users that will be impacted by a server restart?

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#10080]

**Comment by batemapf** [comment]
This could maybe get us a rough number...

- Identify all authenticated pages/paths in MHV;
- Track active session numbers for GA across those routes for a given period (e.g. one hour);
- Find out how many servers are running during the same period;
- Divide

Assumes that load is somewhat symmetrically balanced across all servers. Also assumes that there is no impact to anonymous users if their session is lost. Both of these assumptions should definitely be validated.

**Comment by LeakyBucket** [comment]
Shortly before Craig left on vacation I did a bit of poking around on the site and noticed a couple of potentially interesting cookies attached to my requests.  I relayed this to Craig and he was going to poke around a bit in a lower env.  I'm not sure if he was able to get around to this or what the results may have been.

Long story short I think there are a couple of promising options.  There is a `VSERVER` cookie which looks like it identifies the actual machine your session is tied to.  There appear to be a couple of potential options for identifying users.  There is an `ajs_user_name` which was always `null` for me.  It needs to be investigated whether that is populated by the application on login.  The other possible option would be the ga_client_id cookie which won't necessarily tell us how many users on a server were logged in but it would give an upper bound.

**Comment by batemapf** [comment]
All three possibilities sound promising and would be an improvement on what we've got now (not much). If you wanted to take test out the usefulness of each approach, what would you need? When cookies are set on the client side, is there a record of that event recorded on the server side?
