### ISSUE TITLE
Update Drupal instance of DIC page post-CMS migration QA

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#1008]
@peggygannon 
Parent ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/986 (Add link - and info - on DIC page about Blue Water Navy/Agent Orange law change) 

When this DIC page comes out of CMS migration content freeze - https://www.va.gov/burials-memorials/dependency-indemnity-compensation/ 

Manually update the Drupal instance with the updates in the parent Github ticket above. 

For awareness @Karak888

**Comment by aeltarhoni** [comment]
Waiting on Drupal to come out of code freeze. ETA - Now and next week.

**Comment by Karak888** [comment]
@peggygannon can this be closed now or are we still waiting on DIC Page?

**Comment by Karak888** [comment]
when burials hub goes live through Drupal, 2 version exist:  GH page is live, Drupal page is being held back for public information.  when we update all sme feedback from burials copy deck @RLHecht does final review and @RLHecht will get this from gH to drupal

**Comment by RLHecht** [comment]
@Karak888 Update: I added the alert in Drupal but need help putting in jump links in alert box. Slacked Jen Lee and will ask her or Howie tomorrow to walk me through it again.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - I @'d you in the cms-general channel on a thread that has some guidance. Unfortunately, the cms team is saying wait until content is live, which doesn't help us. 

Here's what I would do - per how Nick helped me fix an anchor link bug in Disability. 

- Manually create the anchor link in the wysiwyg like this: #how-we-determine-combined-va-d  [i.e., use the H2 or H3 text; replace all the spaces with dashes; and stop at 30 characters including spaces, after the # symbol] 

This is how Nick fixed the anchor link problem we had on a Disability page, so I think it will work for this alert text. 

We can look at this with the team at sync, too, if you want to try it as a demo.

**Comment by RLHecht** [comment]
Anchor links have been added to the the alert and alert has been added to page. @peggygannon please review and publish when you do the other Burials pages.

**Comment by Karak888** [comment]
needs to be validated by @peggygannon - please confirm when this goes live in drupal so we can close this out ?  Thanks

**Comment by peggygannon** [comment]
@Karak888 @RLHecht I reviewed and validated this update. Page has been set to "publish" and will go live on 10/10

**Comment by Karak888** [comment]
Thank you both!  closing out this ticket.
