### ISSUE TITLE
[Bug] Manage Dependents - Copy/styling mismatches

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#10096]
## What happened?
On Staging **** form, some copy/styling items did not match corresponding design prototypes.

## Specs:
- Browser-/device-agnostic
- `vets.gov.user+271@gmail.com` \[do not sign-in until after checking unauthenticated Intro page]

## Steps to Reproduce
1. Go to https://staging.va.gov/view-change-dependents/add-remove-form-686c/introduction -- do not sign-in yet.
1. On unauthenticated **Introduction** page, observe copy mismatches. \[see screenshot below]
1. Sign-in as **`vets.gov.user+271@gmail.com`** (Jerry).  IF application-in-progress alert is displayed, Start a new application.
1. On **What do you want to do?** page, observe label-annotation mismatch. [See screenshot below]
1. Select **Claim benefits for your child under 18 and unmarried** option, then click **Continue**.
1. Advance through **Veteran's Information** pages, and 1st **Information needed to add your child** page, completing required fields and clicking **Continue**.
1. On 2nd **Information needed to add your child** page, under **Your child's status**, select **Adopted**.
1. Under **Additional evidence needed** section, expand evidence examples detail-section.
1. Observe copy/styling mismatches. \[See screenshot below].
1. On 3rd **Information needed to add your child** page, select **Yes**, then click **Continue**.
1. On 4th **Information needed to add your child** page, under **Additional evidence needed** section, expand evidence examples detail-section.
1. Observe same copy/styling mismatches as on 2nd **Information needed to add your child** page.
1. Click **Continue**.
1. On **Review Application** page, observe copy mismatch. This occurs with all form-flow Options, not just Add-Child. \[See screenshot below]

**Unauth'd Intro** page copy mismatches
![image](https://user-images.githubusercontent.com/587583/84334844-40b7be00-ab48-11ea-8017-4db4b8c27696.png)

**What do you want to do?** page copy mismatch
![image](https://user-images.githubusercontent.com/587583/84335486-cc7e1a00-ab49-11ea-9da8-deaa6cca2698.png)

**Information needed to add your child** 2nd-/4th-page copy/styling mismatches
![image](https://user-images.githubusercontent.com/587583/84336579-6a72e400-ab4c-11ea-9b82-319eba5ee43b.png)

**Review Application** page copy mismatch ][occurs with all form-flow Options]
![image](https://user-images.githubusercontent.com/587583/84337550-ae66e880-ab4e-11ea-94a8-1ed83d143708.png)

## Desired copy/styling
**[Unauthed Intro page](https://xd.adobe.com/view/057055ba-4c2b-4367-667b-7d7034cb43b4-7341/)** prototype
![md-design-intro-unauth](https://user-images.githubusercontent.com/587583/84334688-d30b9200-ab47-11ea-98ab-678c98fa97d2.png)
    \[Step 1 singular-/plural-form mismatches also exist in prototype]

**[What do you want to do? page](https://xd.adobe.com/view/ca825c11-2268-458f-4fec-6aaecfec5b2d-bcb3/)** prototype
![md-design-options](https://user-images.githubusercontent.com/587583/84335739-634ad680-ab4a-11ea-95d7-49803cced3ec.png)

[**Information needed to add your child** 2nd-](https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/7177f4d5-995e-4906-ad80-1d7fe4e9e08e/)/[4th-page](https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/13cb64c5-dc7a-4f6f-be78-38a08a1bb1cb/) prototypes
![md-design-add-child-p2](https://user-images.githubusercontent.com/587583/84336821-f258ee00-ab4c-11ea-88fa-dbac097f888d.png)

[**Review Application** page](https://xd.adobe.com/view/88794e80-ae26-4f3e-509e-94d09eb571f7-fe48/?fullscreen) prototype
![md-design-review](https://user-images.githubusercontent.com/587583/84337807-5c729280-ab4f-11ea-8669-fb1798b728b3.png)

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jason-gcio** [comment]
@tlei123 - Thanks! We will triage this and get into our queue.  I'll ping you if we have any questions.  Some of these were recent changes, so they might be simply resolved with sharing the latest designs but let me check to be sure.
