### ISSUE TITLE
Asyncronous API calls for all CDW dependent endpoits

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#10092]
Basically clinics and anything that touches appointment index actions, MAS, past appointments

**Comment by lenaecb** [comment]
At this point, based on our conversations, it sounds like we need to move this back to 'backlog' at a minimum. 

can you confirm @saneshark ?

**Comment by saneshark** [comment]
Yeah, this was never going to improve latency issues but rather to help avoid stability to the platform. Based on recent conversations the probability of that seems somewhat nebulous, but I'll write something up about that decision for posterity and we can re-evaluate later if it's worth doing this.

Icebox might be more fitting.
