### ISSUE TITLE
[Research] Create a Research Plan to test Usability of the Analytics MVP

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#101]
## Description
We want to usability test out Analytics MVP to determine if it helps Edu POs/Stakeholders quickly assess the health of their tools and where there might be gaps to further investigate

## User Story
As a product owner, I need to be able to understand how the tools I own are performing so I can make informed product decisions.

## AC 
- [x] A research plan has been written
- [x] A conversation guide has been written
- [x] Usability sessions have been scheduled for testing

**Comment by smoonpeyes** [comment]
@emilywaggoner Started the research plan here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Analytics/Research/Education-Analytics-Research-Plan.md

Feel free to edit!

**Comment by joanneesteban** [comment]
For documentation, adding:
(Insights) Legend to understand how to turn color indicators into actions
(Access) link things up to their source

**Comment by joanneesteban** [comment]
New research plan folder location: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/Education-Analytics-Research-Plan.md

**Comment by joanneesteban** [comment]
Research plan and Conversation guide have been written. Usability sessions have been scheduled. Thank you to all of the designers for your work on this! Closing this issue.
