### ISSUE TITLE
Analytics Reporting Request - Contact Information Dashboard [Profile 2.0]

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#10105]
# Google Analytics Dashboard 

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Create Profile 2.0 dashboard around [Contact Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/analytics/Analytics%20needs%20for%20profile%202.0.md#contact-information-dashboard) update events

- Who is this request for?

    - [Samara Strauss]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - [Authenticated Experience]
    
- Provide the Domain where Google Analytics needs to be implemented
    i.e. www.staging.va.gov/profile/

## Acceptance Criteria
- [ ] Create contact information dashboard for events requested
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bmcgrady-ep** [comment]
@jonwehausen - I finished the first iteration of the dashboard. Please review and let me know what I can iterate on.

Here is the link for the dashboard: https://analytics.google.com/analytics/web/template?uid=s_7fdUqgS0SmH1iCMP_WvA

**Comment by bmcgrady-ep** [comment]
I updated the RegEx for both Non-Prod and Production All VA View to include the new event label naming structure and the old event label naming structure.
