### ISSUE TITLE
VSP ATO Controls - Address ATO Control requirements for the Platform 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#10119]
migrating to: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team-sensitive/170

### High Level User Story/ies

As a  member of DEPO, I want VSP to maintenance and follow the guidelines laid out by the VA's ATO, so that VSP can continue to serve their users and Veterans. 

### Problem Statement
We need to address 18 different controls laid out by the VA in order to remain compliant.

### Hypothesis or Bet:

Getting this work in place will allow VSP to better understand the requirements that the VA expects us to follow. 

Having documented and done this process will make it easier in the future.

We will be able to decomplexify and demystify ATO

###  OKR
O4: Stability and resiliency of VSP's systems and teams continue to improve.

## Success metrics
- [VSP KR] Increase in customer NPS
- VA extends our ATO 
- The team has a better understanding of VA controls going forward.

## We will know we're done when
All controls are address, any work that needs to be done is in place, and evidence is provided for all sub controls. 

## Details and Notes 
We need  to address all the controls by November 2020

### Communication
- Team that owns this super epic: VSP Operations
- Teams contributing to this super epic: VSP Operations and TBD

**Comment by jhouse-solvd** [comment]
migrating to https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team-sensitive/110

**Comment by jhouse-solvd** [comment]
moved to https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13740
