### ISSUE TITLE
Upgrade redux / react-redux dependency 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#10118]

**Comment by jhonnyoddball** [comment]
[Redux Update to the latest](https://github.com/department-of-veterans-affairs/vets-website/pull/13081#event-3431591771)

**Comment by jhonnyoddball** [comment]
## `react-redux` upgrade

The upgrade of `react-redux` from "5.1.1" to "^7.2.0" causes a lot of unit tests errors with `connect()` and with `setState()`

This [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13103) is attempt to perform this upgrade

### Additional info

- [Release notes](https://github.com/reduxjs/react-redux/releases)

**Comment by jbalboni** [comment]
I saw the [recent comment](https://dsva.slack.com/archives/CBU0KDSB1/p1614276786296400) about this from @U-DON in Slack.

I understand the reasoning around wanting to wait to update certain dependencies, but this is something that has been holding back improvements we want to make on VAOS for nearly 9 months. The fact that we're on a version of react-redux that doesn't support hooks forces VFS teams into particular patterns (namely higher order components) that aren't generally necessary in modern React apps. We're several versions behind, with one of the react-redux maintainers noting that there's so [little traffic to the docs](https://twitter.com/acemarke/status/1363703668164468736) for our version that he wants to drop them.

It's not necessarily clear to me that this upgrade gets easier with app isolation, as this is a core dependency that is used across both platform and app code.

cc @Mottie

**Comment by timwright12** [comment]
@jbalboni this was merged right? Do you want to close the ticket?

**Comment by jbalboni** [comment]
@timwright12 Yep, this is merged and can be closed.
