### ISSUE TITLE
Refactor forms library review page 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#10114]
## Overview 

- review page and its child components have stamp coupling / prop drilling 
- review page component composition is overly complex and difficult to change 
- some recent changes to the review page suggest that it will be a target for future enhancements- refactoring now will make those changes easier later 

## Notes 

- This ticket represents a one sprint time box. Insights or conclusions about future forms library work will be recorded here.

**Comment by Clark-W-Griswold** [comment]
Some thoughts. 
Starting to iterate towards composition heavy approach. This includes reducing the prop noise a component will receive. 

Lot's of passing of things around and not everything is in the redux store. Gathering my thoughts around what should and should not live in our redux store.

**Comment by Clark-W-Griswold** [comment]
I've got the RoutedSavableReviewPage copy pasta'd into a new folder in forms. Started to refactor things down from there. In forms, we now have a container folder with a review subfolder. I've started to break out the components under the ErrorMessage && SubmitController . From there, I've started to break out the sub components. Moving props around as needed.

Going to introduce container components where needed once that is done to clean up props being passed around. This will help define some boundary's as we refactor. 

There is some passing around of props and functions that I have had to untangle.

Also, all the linting rules are run against new files. So I've been doing a lot of cleanup on the migrated files to align with our current linting strategy. 

More updates to follow.

**Comment by sshein** [comment]
wondering how much input you want on this - there's some oddness with the way this page works that my design team on VSA has input on. How extensive is this work? Would it be worth talking through and perhaps working with a designer on edits? Very rough list of brainstorming issues the team had at one point is attached:
<img width="586" alt="Screen Shot 2020-06-17 at 5 39 47 PM" src="https://user-images.githubusercontent.com/3856611/84964683-96004c00-b0c1-11ea-8786-861baebed328.png">

**Comment by rianfowler** [comment]
@sshein 
- Review page section titles can be customized like [this](https://github.com/department-of-veterans-affairs/vets-website/blob/841a350d07b90315ce725c9c2cfdf9a964918095/src/applications/disability-benefits/526EZ/config/form.js#L158). We're working on documenting all of these APIs right now but this example should suffice. 
- the rest of this will need to be triaged into a ticket in the [design system repo](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues)- the work this ticket references is strictly related to making the review page easier to maintain rather than making any UX improvements. cc @emilywaggoner

**Comment by Clark-W-Griswold** [comment]
Updates to component structure:
 - new components have grouped imports which leverage aliases (makes for easy refactoring and shuffling of logic).
 - where possible, components are now functional components.
 - removed depreciated lifecycle methods on refactored components and upgraded to hooks.
 - added selectors to help with selecting data from store.

Component specific updates:
RoutedSavableReviewPage:
 - moved to `forms/containers/review` folder.
 - cleaned up imorts
 - removed `renderErrorMessage` and implemented it as it's own, reusable component.
 - updated `mapStateToProps` to support needed props and use new selectors. 
 - some component cleanup of unused props/imports
 - updated to match current linting rules. 

SubmitController:
 - moved to `forms/containers/review` folder.
 - reduced old `SubmitController` and old `SubmitButtons` components logic into this controller.
 - cleaned up imorts
 - removed depreciated `UNSAFE_componentWillReceiveProps` component lifecycle method.
 - moved logic of handling render of status to this controller. 
 - moved `RenderPreSubmitSection` into its own component.
 - moved `getPreSubmit` into a selector. 
 - converted to functional component.
 - updated `mapStateToProps` to support needed props and use new selectors. 
 - updated to match current linting rules. 

New components from old `SubmitButtons` components:
 - ApplicationSubmitted
 - ClientError
 - GenericError
 - SubmitButtons
 - SubmitPending
 - ThrottledError
 - ValidationError

New reusable components from refactor based on common patters:
 - `ErrorMessage`: functional component from common error message patter in `SubmitButtons`.
 - ``Column`: functional component that uses the common `columns` style .
 - `Row`: functional component that uses the common `row` style.

**Comment by Clark-W-Griswold** [comment]
adding PR here for visibility:
https://github.com/department-of-veterans-affairs/vets-website/pull/13355

**Comment by meganhkelley** [comment]
Converted this to an epic, working on grouping and creating related tickets

**Comment by Clark-W-Griswold** [comment]
Adding here for visibility:
https://dsva.slack.com/archives/CQH357ZTP/p1598361284101000

**Comment by Clark-W-Griswold** [comment]
[Linking spreadsheet to the epic](https://docs.google.com/spreadsheets/d/1WCEJgarh9sJKVys_xbtpWqBxLHQfX1eWSItBHUZSvos/edit#gid=0)
