### ISSUE TITLE
Find or create a plugin for validating React props

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#10127]
## Issue Description
Ideally, I think the plugin would catch two cases:
1. Props passed to the component without an associated prop type
    - This would throw a lot of warnings or errors
    - It would also, however, require engineers to more clearly document the API for their components
      - Even though `PropTypes.object` isn't especially useful, it's better than nothing
2. Prop type definitions for unused props

**Comment by jhonnyoddball** [comment]
We will need to turn on `react/no-unused-prop-types` inside `.eslintrc`
