### ISSUE TITLE
Access for Ben McGrady

### ISSUE THREAD

**Issue by bmcgrady-ep** [department-of-veterans-affairs/va.gov-team#10122]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Ben McGrady
- Please Provide your email.
   > ben.mcgrady@empiricalpath.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Analytics & Insights Team, Reporting Specialist, Empirical Path
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDr48T6lNg2/hz1+mq902f4RlEtWGqZ6t9tGXoYtaIxVd0NIgVhXcKO1ct3BZJjZ8VI2CDC2y2sETxD/Z8X57HpNt7aK45E/FSHBjj7vI8cvxvKiRl4m0PhoBs6GHwrYzq4LJ/texTVomdvc2AFDb0spWGlM516VzScUkZkCBp0HZNQhbYXYeFOCqFu9Y1PvxXQKlhvp3CXB9gk1T369eKPe9JYZBYpoBW+ctOELK9MdS7mhueiB/c+aRDJoasSrgwmLu2RRn6K/g/jfm9ArcCvQN5A7ary85Gu2qmc9bKbdIUI0ZLdH2LTKo32LCX3X/gWFMdaGVtOIdWA0+rOYCMrbULF0nviCO5R176cnMF4afElZSZ1sxKxeE3SuzmVpdq+B5JTBKLyoTIDaCnN0WJx3OouBenqVNW7Xp2oLnf6caWmNO4t6EwmWRFpcNkT+urw0V+YH1z1cD0MSChG9GuLpKFTs0Xeb5JZr38MX1/+wS4V2ujMOg8dgKgt/DSCbRk= b_mcgrady@DESKTOP-9O3OKFJ

```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
