### ISSUE TITLE
Analytics Implementation for [Facility Locator]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10124]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA? `Google Analytics implementation`

- Who is this request for? `Michelle Middaugh`

    
- What team/project is this work for? `Facilities Team, Facilities Locator`
     
- Provide the Domain where Google Analytics needs to be implemented: `https://www.va.gov/find-locations/ `
   
- Please provide any upcoming deadlines or important milestones: `no particular deadline`

## Typical Website Interactions to Track 
**Conversions - Understanding the User Flow**
- Veterans who click on the "Can’t find what you’re looking for?Try using our other tools to search." link above the map on the Facility Locator search page will be routed to the [legacy locator](https://www.va.gov/directory/guide/home.asp) 
- It would be valuable to know what type of search has been done prior to this "exit", if that is possible. 

**Certain conditions/responses that need to be reviewed**
- This "exit hatch" is available for all Facility Locator searches, regardless of Facility type. 

**Additional Comments**
- Our assumption here is that Veterans use this "exit hatch" when they are frustrated by the search process or dissatisfied with the search results provided. We want to use this as additional Veteran satisfaction data input. 
- This information may already be available in GA but I have been unable to find a way to view it. 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@mmiddaugh Thank you for your patience on this request! We are going to work this guy along with 10126 - stayed tuned.

**Comment by jonwehausen** [comment]
Thank you again for your time today @mmiddaugh !

[Here is a template](https://analytics.google.com/analytics/web/template?uid=I2_z3YZnQr2JsDtcAq3Ugg) you can use to surface data around volume of visitors who went to the legacy map experience.

**Comment by jonwehausen** [comment]
@mmiddaugh closing this ticket per creation of new implementation ticket #10987. 

We will follow-up with you on any DL requirements we may need.
