### ISSUE TITLE
Remove link to legacy VAOS & update feedback copy from footer

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10130]
As part of our prep for sunsetting legacy VAOS, we want to remove link at bottom of footer that allows user to go back to legacy VAOS. 

![Screen Shot 2020-06-12 at 9.03.19 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/e1b0854f-73ce-4728-b77d-0d941e6d94f7)

### Acceptance Criteria: 
- [ ] Remove link and copy in footer that allows user to navigate to old VAOS tool
- [ ] Update feedback copy in footer to say -  [Leave feedback about this application] _(not for this application)_

**Comment by jbalboni** [comment]
@lenaecb Can we do this any time?

**Comment by lenaecb** [comment]
@jbalboni - yes, we can implement now. 

does this happen to be behind a toggle? wondering if we should keep it around but toggled off until, at least, everything is firmly redirecting to new VAOS without issue.

**Comment by jbalboni** [comment]
@lenaecb No, it's not behind a toggle. We could create one for the various copy changes we are making in anticipation of full launch. Up to you if you think it's worth the effort.

**Comment by lenaecb** [comment]
No, let's just go ahead and remove @jbalboni
