### ISSUE TITLE
Redirect Request

### ISSUE THREAD

**Issue by ArmavelAlysse** [department-of-veterans-affairs/va.gov-team#10131]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
There are two redirects that need to be completed relating to the recent launch of the new VA Open Data Site:

1) There is a GSA requirement that the site be accessible at "https://www.va.gov/data", even if this is a redirect to another site.  So we would like to redirect "https://www.va.gov/data" to "https://data.va.gov"

2) There is another GSA Requirement that the VA's data.json file (a catalog of their data) be accessible at "https://www.va.gov/data.json", again also if it's a redirect.  We would like to redirect "https://www.va.gov/data.json" to "https://data.va.gov/data.json"

### Requestor team info
​Tracy Pham - Business Requestor (out of office from 6/16-19)
Deepak Paudyal – Tracy Pham’s Backup
Alysse Ketner - Digital Transformation Center SaaS PM

### Implementation date
Date new URL(s) will be live: 6/10/2020 

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : The other URLs are live now so as quickly as possible would be great. We understand your timeline above states 2 weeks.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
www.va.gov/data| https://data.va.gov
www.va.gov/data.json | https://data.va.gov/data.json

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@ArmavelAlysse Hi!   It appears there is already a redirect in place on va.gov/data that redirects to here: https://www.ea.oit.va.gov/eaoit/va_ea/opendata.asp.  Do you know who implemented that redirect?

Unfortunately we cannot insert a redirect on the OIT page since that does not live within our tech stack, and I am not sure if we can access the original va.gov/data page since I cannot get to it.

**Comment by ArmavelAlysse** [comment]
@mnorthuis Hello, happy Friday! I will look into the current redirect and who implemented that.

If that is identified then would your team be able to move forward with the redirect? If not, do you know which team has access/is able to help facilitate this? 

Thanks so much for your time!

**Comment by ArmavelAlysse** [comment]
@mnorthuis We were able to find the correct team to help with this request. Thank you for your quick response and help. There is no additional action needed on this ticket at this time.

**Comment by mnorthuis** [comment]
Closing issue.
