### ISSUE TITLE
Check shortened Burial H1s post-CMS migration Q/A

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#1014]
We need to make sure the following Burial H1s have been shortened in drupal, post CMS migration. 

Shortened H1s: 
https://www.va.gov/burials-memorials/dependency-indemnity-compensation/:
Benefits for spouses and dependents (VA DIC) 

https://www.va.gov/burials-memorials/memorial-items/:
Honor a Veteran or Reservist with memorial items

https://www.va.gov/burials-memorials/plan-a-burial/
Schedule a burial for a Veteran or family member

https://www.va.gov/burials-memorials/pre-need-eligibility/: 
Pre-need eligibility for burial in a VA cemetery

https://www.va.gov/burials-memorials/pre-need-eligibility/after-you-apply/:
After you apply for an eligibility determination

**Comment by peggygannon** [comment]
@Karak888 @jenniferlee-dsva

The shortened burial H1s listed above have been checked and validated on Drupal.

**Comment by Karak888** [comment]
wow @peggygannon great news!  does this mean that all of the burials above are complete in Drupal?

**Comment by peggygannon** [comment]
yes, @Karak888 Burial pages are in drupal. The have gone through the first pass of UAT and we are now in the process of incorporating SME parity feedback into the pages.

**Comment by peggygannon** [comment]
@Karak888 @jenniferlee-dsva Since I've validated these H1s in Drupal, I'd like to close this issue. That OK with both of you?
