### ISSUE TITLE
[Design] - Create "Contact info unavailable" copy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10157]
## Background
VA Profile will be down in prod 6/13 between 7:00 pm ET and 9:00 pm ET. Can we get an alert put up in the profile before the end of the day that communicates that contact information will be down in that time? Direct deposit and everything else should be fine since the other info doesn't currently go through VA Profile.

## Tasks 
- [ ] Create copy for the alert

**Comment by peggygannon** [comment]
Hi, @mshea0606 @tressaellen 

Here's suggested message for alert. Please let me know if this will work for the use case: 


**Profile is down for maintenance**
We’re making some updates to VA Profile. The maintenance will last 2 hours. During that time, you  won't be able to access your contact information. 
**Date:** June 13, 2020
**Start/End time:** 7:00 p.m. to 9:00 p.m. ET.

**Comment by tressaellen** [comment]
Thank you @peggygannon !

<img width="971" alt="Screen Shot 2020-06-12 at 3 28 11 PM" src="https://user-images.githubusercontent.com/58752772/84551076-f6a21a00-acb8-11ea-8b1b-a41ed5ebc1af.png">

Just talked with @erikphansen and he said this was no longer needed - but at least we'll have something for future use cases.
