### ISSUE TITLE
CT:  Update TYY to be TTY in Application Process section

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10169]
On the Profile Page within the Comparison Tool, under the Application process accordion TTY is TYY. Let's do global fix/replace to correct this and make it **TTY**. 

This bug originated from https://github.com/department-of-veterans-affairs/va.gov-team/issues/9989#issuecomment-643311667

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13136

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now live. Closing this issue
