### ISSUE TITLE
[SCREENREADER]: GIBCT EYB - iOS VoiceOver MUST read the correct amount when I update my benefits

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#10167]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

**UPDATE: Bumping this down to a `508-defect-2` after identifying it has been an issue in production.**

While testing the college and OTJ flows, I noticed that iOS VoiceOver was reading the wrong data points back after I made filter changes and pressed the "Update your benefits" button. Screenshot and steps to recreate below.

* https://dsvavsp.testrail.io/index.php?/cases/view/671&group_by=cases:section_id&group_order=asc&group_id=46
* https://dsvavsp.testrail.io/index.php?/cases/view/672&group_by=cases:section_id&group_order=asc&group_id=46

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] iOS VoiceOver reads the correct data before and after I have updated my benefits

## Environment

* iOS 13.5.1 - iPhone 8
* Safari
* VoiceOver
* https://staging.va.gov/gi-bill-comparison-tool/profile/11806124
* https://staging.va.gov/gi-bill-comparison-tool/profile/11806124

## Steps to Recreate

1. Start iOS VoiceOver from Settings > Accessibility > VoiceOver
1. Open one of the two URLs above
1. Swipe through until you get to the Estimate Your Benefits panel. Verify the numbers read aloud are what appear on the screen.
1. Now swipe left to change one or more filters. Make it a big change, like wildly different tuition numbers or say you are an out of state student and add a large tuition number.
1. Press `Update your benefits`
1. Swipe right to the Estimate your benefits panel. Read out each numeric value. The values embedded in headings will read incorrectly.

## WCAG or Vendor Guidance (optional)

* [Error Prevention (Legal, Financial, Data): Understanding SC 3.3.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-reversible.html)

## Screenshots or Trace Logs

![Image from iOS](https://user-images.githubusercontent.com/934879/84527728-09f6ba80-aca4-11ea-9e62-29276f9330a5.png)

**Comment by shawkey-daniel** [comment]
@1Copenut This issue appears to be a bug in iOS voiceover. If we change the header tags to div or p, the voiceover works correctly. This would be working around an implementation issue. Do you have another recommendation for how to get this to work with the existing header tags?

**Comment by 1Copenut** [comment]
@dneel-bah I'm going to bump this down to a level 2 defect, non launch-blocking. @shawkey-daniel and I determined this is an issue in production, so it's not a new item. We should definitely look to close this out as quickly as possible post-launch, but for now, testers can verify the issue using any prod url like https://www.va.gov/gi-bill-comparison-tool/profile/11806124

I'll add my troubleshooting notes here after a meeting, to help engineering and QA find the right solution.

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13143

**Comment by sonntag-adam** [comment]
@1Copenut in staging.

**Comment by 1Copenut** [comment]
@sonntag-adam && @desireeturner I reviewed this again in staging and the issue appears to be resolved. Updated values are being read as expected, so I'll move this one closed.
