### ISSUE TITLE
[Development] BDD: Separation Location Auto Suggest

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10174]
## Issue Description
We realized that having a list of 250 separation locations to scroll through is not ideal.

This ticket is to either modify the auto suggest but not allow free input or perhaps we can just validate after auto complete.  If we follow the second path, we need to add wording that explains why their free input is not allowing them to proceed.

## Acceptance Criteria
- [ ] Make sure whatever we choose is accessible.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
Link to PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13116

**Comment by luke-gcio** [comment]
Closing - done as part of PR (see linked PR).
