### ISSUE TITLE
[Development] BDD: Service Treatment Record (STR) Submission

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10172]
## Issue Description
With the addition of STRs for the BDD flow, it may require changes to allow for submitting under the right document type.  Options include coming up with a new document type (which may create downstream work and issues) or figuring out a way to use an existing document type but adding some wording on the front-end.  This ticket here for the back end work, to make sure we are passing the data appropriately to the downstream endpoint.  There is also a front end ticket that makes a decision on the former options.

## Acceptance Criteria
- [ ] STRs are being submitted to (wherever they need to go) their endpoint
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Service treatment record designs for BDD can be found here: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/421404546_BDD_-_Supporting_Evidence_-_STR_Upload_Question

**Comment by annaswims** [comment]
I started looking at STR uploads a bit, and it looks like the code to upload STR's has been around for years. 
So, no BE work will be needed.

![Screen Shot 2020-06-16 at 12.16.32 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/93308777-4f33-4bcb-b6fe-9ecd1121351f)(url)

**Comment by ndsprinkle** [comment]
@annaswims Wow, great find, wish we had caught this sooner. I'll have to see what makes the most sense for the FE going forward. I have already done all the work to give STRs their own workflow, so the "easiest" approach going forward may be some data transformation on submission to use the already existing schema.
