### ISSUE TITLE
Rename MVI to Master Person Index

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#10178]
## Issue Description

MVI is used throughout the app as an acronym.  There's no acronym set up in in the inflections file.  There's also a conflict in a model with the same name as the module name for MVI lib stuff.  Also, the MVI acronym is outmoded because the service is called MPI now.  This work is to use the introduction of the acronym as the opportunity to begin renaming things as MPI.

### notes
This PR was closed because it tried to do this all at once and was too big https://github.com/department-of-veterans-affairs/vets-api/pull/4521

**Comment by erluti** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/4521
This PR is tied to https://github.com/department-of-veterans-affairs/va.gov-team/issues/10472 which accomplishes this story's goals.

**Comment by alexpappasoddball** [comment]
@erluti @LindseySaari Can this be closed?

**Comment by LindseySaari** [comment]
@erluti I think we can close this in favor of #10472 ?
