### ISSUE TITLE
Enable Zeitwerk mode

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#10183]
## Issue Description
Remove the line `config.autoloader = :classic` in `config/application.rb` and use the modern Rails autoloading engine.

---
## Tasks
- [x] Enable zeitwerk

## Acceptance Criteria
- [x] All tests pass
- [x] app runs using zeitwerk

**Comment by LindseySaari** [comment]
Note: review rakelib/pension_burial.rake

**Comment by erluti** [comment]
Was incorporated into this change https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10641
