### ISSUE TITLE
Analytics Reporting Request for Direct Deposit [Profile 2.0]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10198]
## Description
Is this request for Google Analytics implementation or QA?
- GA implementation

Who is this request for?
- Matt Shea, Samara Strauss

    
##### What team/project is this work for?
 - Authenticated Experience team, Direct Deposit product

##### Provide the Domain where Google Analytics needs to be implemented
- www.staging.va.gov
    
##### Identify if PII is passed in URL or title tag_
- No PII is passed through the data

##### Please provide any upcoming deadlines or important milestones
- This product launched a long time ago, we are just looking to add some additional 
   metrics to the dashboard and/or a new dashboard if needed
    
##### Additional Comments
- [Link to current Direct Deposit dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p176188361/)

- [Staging usernames-pws doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/QA)

Metrics Requested:
- Total number of VA.gov users
- Total number of users enrolled in Direct Deposit  
- Week over Week changes %(WoW)  (Total number of users enrolled in Direct Deposit)
- WoW % change (Successful Retrievals of Direct Deposit)
- WoW % change (Direct Deposit Form Submits)
- WoW % change (Total Direct Deposit Errors)

This is probably too much information to include on the current Direct Deposit Dashboard, it's ok if this is on a separate dashboard or report. Let me know if you need any clarification on any of the metrics or have any questions!

Thanks for your help! 
- Matt Shea

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bmcgrady-ep** [comment]
@mshea0606 Confirming receipt. Thank you. Will take a look and get back to you.

**Comment by bmcgrady-ep** [comment]
@jonwehausen - Finished initial build of a dashboard for this request. Can you please take a look and let me know what I can iterate on?

Here is the link: https://analytics.google.com/analytics/web/template?uid=Mtkcf4Y_TgmpnYl_S4MjKQ

**Comment by bmcgrady-ep** [comment]
I updated the RegEx for both Non-Prod and Production All VA View to include the new event label naming structure and the old event label naming structure.
