### ISSUE TITLE
[Design] Write a Key for Analytics MVP that outlines thresholds and translations

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#102]
## Description
Currently, the analytics MVP has colors that indicate product health and headings that describe different data points. Now we need to establish a key that explains the color coding and headings to ensure edu POs/stakeholders understand how to read the Analytics MVP.

## User Story
As a product owner, I need to be able to understand and interpret the data myself in order to effectively make data-driven decisions and be empowered to make these decisions without data literacy dependencies on others.

## AC
- [x] A key has been created. The key should include the following criteria: 
    * Glossary of terms
    * Explanation of data origins
    * Explanation of data interpretations/definitions
    * Legend to explain how to turn the color indicators into action
- [x] The key should be accessible in the working MVP prototype.

## Definition of Done
- [x] All AC met

**Comment by nedierecel** [comment]
@joanneesteban As we build threshholds for the Google Sheet MVP, one thing to keep in mind when pulling Form Conversion rate is the `View` it is pulled from. 

For example, for the WBC View, this is the conversion rate for Form 1990:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/4ce0797f-45df-4879-9e23-b38d01d13a92)

This same goal in the Education Modernized View (which only filters on the Education subdirectory) yields a higher conversion rate:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/224c446d-5cea-4912-86bb-d81845b5e62c)

Thinking about our product owners, it might be more useful to see the latter Education view; the user has arrived at Education content and now we need to determine if they are converting by completing that form.

**Comment by rroueche** [comment]
@rtluu and @joanneesteban I think this should include collaboration with @smoonpeyes as well, bc the way that contextual content is incorporated into the MVP could use some design advice. I know that we provide contextual help w/very intentional design throughout VA.gov, we should take the same approach here.

**Comment by joanneesteban** [comment]
#134

**Comment by nedierecel** [comment]
@joanneesteban Within the Product Health MVP, I have added information for the Google Analytics definitions and their calculations. I also included suggestions within "Definition" to indicate success or red flags to look for.

**Comment by joanneesteban** [comment]
Glossary has been added to the MVP. Will iterate as needed after usability testing. Version 1 is completed. Closing this issue.
