### ISSUE TITLE
[CONTENT]: GIBCT EYB - CONSIDER reviewing Pell under scholarship labels

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#10203]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

For colleges, one of the options under scholarships lists Pell as an option. Is this a reference to Pell Grants? It might be worth reviewing this language with a content specialist. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] VSP content and/or BAH design team makes a call for the right language

## Environment
* https://staging.va.gov/gi-bill-comparison-tool/profile/11806124

## WCAG or Vendor Guidance (optional)

* [Unusual Words: Understanding SC 3.1.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-idioms.html)

## Screenshots or Trace Logs

![Screen Shot 2020-06-12 at 4 39 20 PM](https://user-images.githubusercontent.com/934879/84548678-d3cd3100-accb-11ea-8c92-644053936409.png)

**Comment by amyknox** [comment]
It seems like this would be "Federal Pell Grants." Let's confirm this with EDU before we make that update.

**Comment by desireeturner** [comment]
From @amyknox: We confirmed with EDU on Monday that it is Pell Grants. I think we can go ahead and just add the word "Grants" onto the end of that label (see below) and make the same adjustment to the heading of its Learn more modal.
**Scholarships (excluding Pell Grants)**

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13363
Branch: bah-10203

**Comment by sonntag-adam** [comment]
@1Copenut this is in staging.

**Comment by 1Copenut** [comment]
LGTM. Moving to close.
