### ISSUE TITLE
Discovery-Project Brief and Planning

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#10212]
[Project Brief ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/project_brief_planning.md)

Once reviewed by our team we need to send to:

- [ ] Send the Discovery Project Brief and Planning Document link to Kelly to approve the final list of stakeholders you will be reaching out to. Once OK’d, update the planning doc.
- [ ] Send completed Discovery Project Brief and Planning Document link to Clare for approval to start the sprint.

**Comment by abuckley3385** [comment]
@LEHigley will you please review the document and we will mark complete after your feedback and send to "Kelly" and "Clare"

**Comment by LEHigley** [comment]
Done! @batemapf who is Kelly?

**Comment by batemapf** [comment]
i dunno, maybe @abuckley3385 does?
