### ISSUE TITLE
CT - GA: Accordion expand and collapse events are reversed

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#10228]
When a user collapses or expands an accordion on a school profile page, that action is tracked as either `nav-accordion-collapse` or `nav-accordion-expand`. Currently, Expanding an accordion triggers the `nav-accordion-collapse` event, and collapsing an accordion triggers the `nav-accordion-expand` event. These should be reversed.

1. Access https://staging.va.gov/gi-bill-comparison-tool/profile/35356632
2. Click and section header (Estimate your benefits, Veteran programs, etc) to collapse
3. Open console and use the `window.dataLayer` command
4. Expand the collapsed section by clicking the header
5. Open console and use the `window.dataLayer` command

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13142

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now live. Closing this issue
