### ISSUE TITLE
[Call Center] Call Center Escalation for Analytics & Insights

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1022]
## User Story
As a Call Center Lead, I need understand what information is needed from Call Center so we can provide that information effectively and in a timely manner.

## Goal
_What outcome(s) do we want to see?  
-Effective collaboration and information sharing between A/I and CC.
    -This can be done through the Call Center Cadence that has been created.

## Acceptance Criteria
- [x] _What needs to happen or be created?
_Meeting with Chante and/or Joanne to get a better understanding of what details are needed.
_If there is documentation that lives on GitHub and link should be provided.
_If no documentation exists, create that document.

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
The escalation process for A/I will mirror the escalation process that has been developed for the Triage team.
ETA EOD 8/20/2019.

**Comment by joanneesteban** [comment]
@Kimberley2019 We can close this out. We'll wait on you to confirm.
