### ISSUE TITLE
Research API's Available from EMR's 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#10223]
- [x] API from Vista

- [ ] API from Cerner

- [ ] [Tech API's  for Clinical Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/feature-documentation/clinical_forms_data.md)

- [x] API Prototype

- [ ] Patient generated data PGD service FHIR API. (example - VA mobile)

**Comment by abuckley3385** [comment]
developer.va.gov
code.cerner.com

**Comment by abuckley3385** [comment]
@mdewey #10223 issue looks like the same as #10486 should we close this on and copy contents into #10486?

**Comment by mdewey** [comment]
Looks like a duplicate. Bringing over the considerations from the #10486 

Discovery research and prototype API integrations.

Considerations:

- [ ]  Security precautions needed to take
- [ ]  Performance of the API and if we need to cache or store requests
- [ ] Source of Truthiness of the API
- [ ] Where in the flow of information do they go

**Comment by mdewey** [comment]
Task: 
Find if API from Vista and API from Cerner has Family History and SHx. 

Acceptance criteria: 
- Can we pull in data from the APIs? 
- Does that data exist?

**Comment by mdewey** [comment]
**Acceptance Criteria**

-[ ] Add findings to the [tech doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/engineering)
