### ISSUE TITLE
Create a Product Guide for the Online 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#10220]
Using the guidelines provided [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) I want to create a Product Guide for the online 10-10CG so that users who call the Help Desk can get the support they need

**Comment by psanders86** [comment]
This is finished, but will be updated when PW team is able to give me a screenshot and URL of the updated drupal page that has the application button activated.

[https://app.zenhub.com/files/133843125/0c9bd244-98cf-4e16-a1c6-cda60d0cf2ff/download](https://app.zenhub.com/files/133843125/0c9bd244-98cf-4e16-a1c6-cda60d0cf2ff/download)

**Comment by psanders86** [comment]
Here is the final product guide, including a screenshot to the landing page when the application button is activated.

[https://app.zenhub.com/files/133843125/0f027b26-f455-4dea-8c60-8f605a28c784/download](https://app.zenhub.com/files/133843125/0f027b26-f455-4dea-8c60-8f605a28c784/download)

**Comment by psanders86** [comment]
This guide needs to be updated to include guidance from the help desk for navigating users past the new error message
