### ISSUE TITLE
Integrate maintenance banner with pager duty

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#10234]
# Description

While it's really nice having a single config file to update the maintenance banner, we can simplify it even further by having the config originate from Pager Duty.

View [Rian's comment here](https://github.com/department-of-veterans-affairs/vets-website/pull/12959#discussion_r435993206):

> We should fetch this information from pager duty using something like getCurrentGlobalDowntime in src/platform/monitoring/DowntimeNotification/util/helpers.js. The parent component for this could transform that data into the view props (e.g. I think you only get the downtime window but you'd need to turn that into stuff like warnStartsAt).

> If we use that helper then we don't need to do a site deploy to turn this on- we can set a maintenance window for the global downtime in PagerDuty.

https://api.va.gov/v0/maintenance_windows has scheduled maintenance windows in PD
https://api.va.gov/v0/backend_statuses and has the current status of services (including unscheduled downtime)

## Acceptance Criteria

- [ ] Use Pager Duty to derive maintenance banner's config.

**Comment by kelsonic** [comment]
CC @stephorkandatx follow-up ticket to https://github.com/department-of-veterans-affairs/va.gov-team/issues/9223

**Comment by kelsonic** [comment]
Hmm, is this risky to implement? I get the feeling that it might be since we'd control of the maintenance banner would then go to pager duty CC @ncksllvn @MickinSahni

**Comment by ncksllvn** [comment]
In the past, we've only shown the maintenance banner during site-wide outages, where the API is completely down. VSP created a tool to determine site-wide downtime from the FE without an API request. The idea here is that we could use that tool to power the maintenance banner so that we no longer need to edit our own JSON config to set up site-wide downtime.

**Comment by brianalloyd** [comment]
Completed,  based on innovation of maintenance banner component.
