### ISSUE TITLE
Frontend support: Change VR&E name throughout benefits section

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10232]
**Issue Description**

The program name is changing on June 22, and stakeholders would like to update our pages as close to that date as possible. 

Laura has been able to modify most of the impacted pages but we have found two that require frontend support.
We will need to modify these two pages (React apps) for the new name, but may also find that additional changes are needed. 

Please work with Laura while doing these changes so she can review the content within the apps and determine if additional updates are needed besides updating the name.

Note: these are possibly old pages, that may not actually be on the site. These may be ghost pages

Content work at #9899

**New name of program: Veteran Readiness and Employment**

**Acceptance Criteria**
- [ ] Confirm that these pages are not ghost pages. If they are, disregard & alert Laura, Beth

If these are NOT ghost pages:
- [ ]  Frontend update employment/vocational-rehab-and-employment/application/chapter36/index.html (React app) for the new name of the program - Basically any reference of Vocational Rehabilitation and Employment is being changed to Veteran Readiness and Employment
- [ ] Frontend update employment/vocational-rehab-and-employment/application/chapter31/index.html (React app) for the new name of the program - Basically any reference of Vocational Rehabilitation and Employment is being changed to Veteran Readiness and Employment
- [ ] Content writer review of the content within the react apps, making recommendations on other updates as needed (Laura)

**Comment by ncksllvn** [comment]
I did a search for VR&E throughout the FE code - 

1. `/find-locations/` has a sentence - `Vocational Rehabilitation and Employment (VR&E) help`
1. The GIBCT has two instances of the sentence - `To apply for VR&E benefits, please`
1. The My VA has a sentence - `Find out if you're eligible for Vocational Rehabilitation and
            Employment (VR&E) services`

The forms Chapter 31 and Chapter 36 have both not launched so I think that makes them ghost pages. There is also an upcoming app, View Payments, which has a sentence - `This will update your information across disability compensation, pension benefits, claims and appeals, Vocational Rehabilitation & Employment (VR&E), and VA health care.`

**Comment by ncksllvn** [comment]
Should I just directly change those instances of VR&E to Veteran Readiness and Employment? CC: @lwalsh617 @bethpotts

**Comment by bethpottsVADEPO** [comment]
@ncksllvn and I are getting on a call about this 6/23. FYI @stephorkandatx this ticket should be able to close tomorrow.

**Comment by ncksllvn** [comment]
### Facility Locator
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/f31d6aa8-bf49-4d3c-9221-e1a9091cd1da)

### GIBCT
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/608ebd0a-bd8a-44be-bc11-8f2b7febe8be)

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/52f7ad34-2544-4665-95eb-d7708eb161c7)

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/4db8fccd-42f6-46b3-b663-8cb0cd90ee7d)

**Comment by ncksllvn** [comment]
### /My-VA

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/51e3bef6-4e3f-40cf-9c1a-a0d85b38fc15)

**Comment by ncksllvn** [comment]
### View Payment History

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/d4933e34-810b-466b-81dc-16c655e3b079)

**Comment by ncksllvn** [comment]
### Claims
I can't find a user to use for `/track-claims` but this screenshot is what we're looking at -

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Global/Claim%20Status/Screenshots/Claims%20List%20-%20Has%20Claims.png

I'm semi-guessing, but I think the title of one of those cards could contain `vocational rehabilitation and employment`, like `Claim for vocational rehabilitation and employment`

**Comment by bethpottsVADEPO** [comment]
@ncksllvn Thanks for ushering through these edits!

**Comment by bethpottsVADEPO** [comment]
@ncksllvn I need to change the first guidance I gave, above, in the main drop-down in facility locator. That one actually needs to be a general reference rather than a branded one to match the other entries here, so: Vocational rehabilitation and employment help. Can you change the request to that team?

**Comment by ncksllvn** [comment]
@bethpotts I actually haven't opened the PR yet, but will make sure to update that when I do!

**Comment by ncksllvn** [comment]
@bethpotts just confirming that this is still on hold? My PR isn't merged yet.

**Comment by bethpottsVADEPO** [comment]
@ncksllvn You can move forward with this! Thank you!

**Comment by MickinSahni** [comment]
Carryover to sprint 25

**Comment by MickinSahni** [comment]
@bethpottsVADEPO can you validate this ticket for nick?

**Comment by bethpottsVADEPO** [comment]
I validated the PR and it got merged! Closing.
