### ISSUE TITLE
Tech investigation for Rails - API integration

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#10236]
Vets-API uses faraday to wrap external requests
our design pattern is to have a Client class that pulls in Configuration from a Config class and a Response class to handle any data conversion before handing the data back to rails

[Common::Client::Base](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/client/base.rb)

[Common::Client::Configuration::REST](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/client/configuration/rest.rb)
[Common::Client::Configuration::SOAP](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/client/configuration/soap.rb)

[Common::Base](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/common/models/base.rb)

Examples can be found in the lib directory, [Lighthouse Client Example](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/lighthouse/facilities)

After getting the data from the API we need to use a model to represent the data inside rails
Using the Lighthouse Facilities Client as an example we can see an example of a model [Lighthouse::Facilities::Facility](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/lighthouse/facilities/facility.rb)

To present the data to the frontend it needs to be serialized. We currently have two serializers available unfortunately they are not cross-compatible.
[Lighthouse::Facilities::FacilitySerializer](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/serializers/lighthouse/facilities/facility_serializer.rb) uses the newer and faster FastJsonApi serializer
[MessagesSerializer](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/serializers/messages_serializer.rb) uses the older and slower ActiveModel serializer

**Comment by annaswims** [comment]
Feel free to use FastJsonApi serializer for new code. VSP has/had a ticket to convert to FastJsonApi but the risk/reward didn't seem to justify the effort.

 https://github.com/department-of-veterans-affairs/va.gov-team/issues/465

**Comment by short000** [comment]
@annaswims pointed me to this Endpoint Punch List video whcih could be helpful for Laurence: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/tutorials/endpoint-punch-list-presentation.md

**Comment by annaswims** [comment]
[video tutorial for new external services](https://www.youtube.com/watch?v=V_i8JLXk5rg)
[slides from video](https://hackmd.io/@z9SepQsSSlu0NKymVGnXTA/r1ZdSNJmr#/)
[code example linked from video](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering/backend/tutorials/endpoint-punch-list-presentation/supporting_code)
