### ISSUE TITLE
Add ErrorMessage Override

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#10233]
As a user I would like to see more than a hard coded error for every form in the FormBuilder, please make an enhancement so we can override the default hard coded ErrorMessage with our own Custom ErrrorMessage alert.

Add a ternary so this default error can be replaced by a custom [DSVA Error alert](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/) component

https://github.com/department-of-veterans-affairs/vets-website/blob/280aff39b72c301eef37bf6a1e1a1dc73e79d9fa/src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx#L98

**Comment by LinnJS** [comment]
Discussions: 

https://dsva.slack.com/archives/C5HP4GN3F/p1592233974059800


https://dsva.slack.com/archives/CBU0KDSB1/p1592233036426000

**Comment by LinnJS** [comment]
Unit test error discussions: https://dsva.slack.com/archives/C5HP4GN3F/p1593467730105500

**Comment by LinnJS** [comment]
I am not sure how to continue with these test due to pre-existing errors with this component. I cannot do a full mount to implement a very simple test and not sure how to solve this problem, and current do not have time to invest in a solution.

**Comment by drorva** [comment]
From VSP's perspective, feel free on testing in this case, since we're the ones blocking you.

**Comment by LinnJS** [comment]
Another discussion that lead to this ticket being re-blocked due to concerns over consistency on the platform despite this functionality being needed on more than one team. They currently have a hardcoded error message that assumed an authenticated experience.

We need this sorted out so applications have flexibility over error handling and a better user experience. This block feels moot since the VSP "Collaboration Process" should be reviewing each implementation for consistency rather than blocking this engineering feature.

Link to discussion:
https://dsva.slack.com/archives/CBU0KDSB1/p1594737235181100

**Comment by meganhkelley** [comment]
Update from VSP: 

- @Clark-W-Griswold will review and approve the ability to implement custom error messages in the forms library 
- In the future, these instances will need explicit approval from VSP — please note that in your documentation as applicable @LinnJS (Ticket #10528) 
- In the future, VSP will flag these instances for explicit approval by using a review bot #11358

Note that this approach pertains to the ability to implement custom error messages and does not speak to whether this particular custom error message has been approved — for more on Caregiver review/approval status please see comments on #4996
