### ISSUE TITLE
Health insurance page should not require an answer of yes

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#10238]
Per the conversation in Slack [here](https://dsva.slack.com/archives/CMJ2V70UV/p1591994994238000) - the health insurance page wasn't allowing users to move forward without selecting "yes" for one of the options. This is not the desired behavior - the user should be allowed to continue if they select no for all of the answers.

**Comment by LinnJS** [comment]
The issue is the input is required, and needs to be conditionally required.
