### ISSUE TITLE
[FE] - Update "We can't access your military information" message in the profile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10246]
## Background
Reference ticket: [Copy] Improve copy for "We can't access your military information" message in the profile #7553

![image.png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/27f949bf-409c-444f-8f75-15754fd223fa)

## Tasks 
- [ ] build updated message in Military info section

**Comment by erikphansen** [comment]
I'm closing this. The [original issue that spawned this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7553) was handling the "empty array from `GET service_history`" situation correctly. And we already handle the temporary server issue with appropriate messaging.
