### ISSUE TITLE
[Improvement] - Update no results found message for Find Yellow Ribbon Participating Schools tool

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#10244]
Please update `no results found` message as follows. [Wireframe here](https://vsateams.invisionapp.com/share/Z6XPA1BE4AB#/421619606_Screen_Shot_2020-06-15_At_1-08-08_PM).

Acceptance Criteria:

`h2` reads **No schools found for your search criteria**
`<p>` reads `To find participating schools:`
`<ul>` reads 
  - Double-check your spelling. 
  - Try fewer search terms .
  - Try more general search terms.

**Comment by kelsonic** [comment]
@andaleliz is this ready for implementation? 🙂

**Comment by andaleliz** [comment]
Sure is!
