### ISSUE TITLE
Authenticated Users Updates: Medical Records page alert box updates for Cerner+MHV patients

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10248]
**User Story**
When a Veteran who is a patient at a Cerner facility but who is also a patient at non-Cerner facilities is logged in on VA.gov and is on the Medical Records page (https://www.va.gov/health-care/get-medical-records/), the alert box should explain to users that they will be directed to the appropriate page on both My VA Health and MHV.

Mock-Up at https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405228559

**Acceptance Criteria**

 - [ ] Alert box lets authenticated users know that they have records in both MHV and Cerner, and provides correct link to both medical records pages
- [ ] Alert box content updates match the mock-up (if there are issues with the specific content, loop in Danielle and Peggy)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by MickinSahni** [comment]
Validated internally on local
