### ISSUE TITLE
Authenticated Users Updates: Prescription page alert box updates for Cerner+MHV patients

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10253]
**User Story**
When a Veteran who is a patient at a Cerner facility but who is also a patient at non-Cerner facilities is logged in on VA.gov and is on the Prescription Refill and Tracking page (https://www.va.gov/health-care/refill-track-prescriptions/), the alert box should explain to users that they will be directed to the appropriate page on both My VA Health and MHV.

Mock-Up and content at https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404897044

**Acceptance Criteria**

- [ ] Alert box UX lets authenticated users know that they have records in both MHV and Cerner, and provides links to Cerner to MHV *note that if the prescription information in Cerner is incorrect, we will not link to it, and will continue to send users to MHV only.
- [ ] Alert box content updates match the mock-up (if there are issues with the specific content, loop in Danielle and Peggy)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by MickinSahni** [comment]
Validated internally on local
