### ISSUE TITLE
Authenticated Users Updates: Messaging page alert box updates for Cerner+MHV patients

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10252]
**User Story**
When a Veteran who is a patient at a Cerner facility but who is also a patient at non-Cerner facilities is logged in on VA.gov and is on the Messaging page (https://www.va.gov/health-care/secure-messaging/), the alert box should explain to users that they will be directed to the appropriate page on both My VA Health and MHV.

Mock-up and content at https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404880626

**Acceptance Criteria**

- [ ]  Alert box UX lets authenticated users know that they have records in both MHV and Cerner, and provides correct link to both messaging pages
- [ ] Alert box content updates match the mock-up (if there are issues with the specific content, loop in Danielle and Peggy)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by MickinSahni** [comment]
Validated internally on local
