### ISSUE TITLE
Authenticated Users Updates: Scheduling page alert box updates for Cerner+MHV patients

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10251]
**User Story**
When a Veteran who is a patient at a Cerner facility but who is also a patient at non-Cerner facilities is logged in on VA.gov and is on the Scheduling page (https://www.va.gov/health-care/schedule-view-va-appointments/), the alert box should explain to users that they will be directed to the appropriate page on both My VA Health and MHV (or, once launched, VAOS).

Note that this should include, to start, users who are patients at Spokane Mann Grandstaff, as well as users who are patients at Columbus.

Note that once VAOS can consume the Cerner API (eta TBD), this may change.

Mock-up and content at https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881778

**Acceptance Criteria**

- [ ]  Alert box UX lets authenticated users know that can schedule with both VAOS or Cerner, depending on the facility, and provides correct link to the correct scheduling pages (Cerner for Spokane and Columbus facilities, VAOS for everything else)
- [ ] Alert box content updates match the mock-up (if there are issues with the specific content, loop in Danielle and Peggy)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by kelsonic** [comment]
@DanielleThierryUSDSVA @andaleliz Do we know if this design is still up-to-date with the recent content changes for the authenticated CTA widget on this page?

![image](https://user-images.githubusercontent.com/12773166/85603244-6a271e00-b60d-11ea-9052-935b4dfc4069.png)

Also it'd be super helpful if I could know what to show based on:

1. Authenticated + belongs to 0 Cerner facilities
2. Authenticated + belongs to 1 Cerner facility
3. Authenticated + belongs to 2+ Cerner facilities

**Comment by DanielleThierryUSDSVA** [comment]
@kelsonic I'm going to recommend similar changes to the alert content across all alerts. Will post final content for each as soon as I can. Will also confirm the approach to showing each state.

**Comment by MickinSahni** [comment]
Validated internally locally
