### ISSUE TITLE
Authenticated Users Updates: Scheduling page - Authenticated users main content updates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10254]
**User Story**
As a user who is a patient at a Cerner facility and who is browsing the Scheduling page on VA.gov after authenticating (logging in), I want the content on the page (above ad below the alert box) to give me the correct information about Cerner and/or MHV so that I am not confused about where my patient portal information is housed.

Note that authenticated users who are not patients at Cerner facilities should see the same content/UX as unauthenticated users (see #5745)

Mock-Up and content at https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881778

**Acceptance Criteria**

- [ ] Content on Scheduling page (above and below alert box) for authenticated Cerner patients displays the necessary Cerner-specific information
- [ ] Content on Scheduling page (above and below the alert box) for authenticated users who are not Cerner patients is the same as for unauthenticated users
- [ ] Alert box content updates match the mock-up (if there are issues with the specific content, loop in Danielle and Peggy)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by kelsonic** [comment]
@DanielleThierryUSDSVA 

![image](https://user-images.githubusercontent.com/12773166/85598595-f8e56c00-b608-11ea-952c-68f4e957d201.png)

Just want to confirm, should we remove **What types of medical appointments can I schedule online?** section when a user is authenticated despite if they belong to a Cerner facility?

**Comment by kelsonic** [comment]
Also, need to confirm that we want to show the **More information about your benefits** links when a user is authenticated despite if they belong to a Cerner facility:

![image](https://user-images.githubusercontent.com/12773166/85602700-dc4b3300-b60c-11ea-8541-6e366f94cdb9.png)

**Comment by kelsonic** [comment]
![image](https://user-images.githubusercontent.com/12773166/85602794-f422b700-b60c-11ea-8e03-3bc316c4e090.png)

Sorry, last thing, but where should `[contact us online]` link to? Should that just be the normal link design, too?

**Comment by DanielleThierryUSDSVA** [comment]
@kelsonic I'll look at these questions today. Also, just want to give you the heads up that I will have content changes coming to you in the next few days. All changes will be tracked/highlighted so they should be easy to see. But just want to make sure you know!

**Comment by kelsonic** [comment]
@DanielleThierryUSDSVA Sounds great! Thanks for keeping me updated! 🎉

**Comment by DanielleThierryUSDSVA** [comment]
@kelsonic 

**Posting update that I just slacked you as well:**

Unauthenticated users + authenticated users who are not Cerner facility patients = unauthenticated content

Cerner facility patients = authenticated content
