### ISSUE TITLE
Customer Support - Pilot new BE Rotation Model

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#1026]
## High Level User Story

As a member of the Backend tools team, I need to be able to focus on my work during a sprint and not be interrupted by support requests, searching for PRs to review and occasionally browsing sentry to identify issues.

## Hypothesis/(es)

If we define a rotation model for the backend tools team, we will be able to dedicate one team member to be responsible for fielding customer requests for assistance who can than pass along the request, assign out PRs to be reviewed so the load is better distributed, and monitor sentry alerts so that the remaining team members are not disturbed while they work on other sprint objectives.  This will make us more efficient as a team and reduce duplicate efforts on solving issues.

## VSP Objectives
Q3 - Stability and Resiliency

**Comment by rroueche** [comment]
@alexpappasoddball please add KPIs to the description. what data do you plan to measure to understand whether this work is improving what you hypothesize it will improve?
