### ISSUE TITLE
Authenticated Users Updates: Prescription page - Authenticated users main content updates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10261]
User Story
As a user who is a patient at a Cerner facility and who is browsing the Prescription page on VA.gov after authenticating (logging in), I want the content on the page (above adn below the alert box) to give me the correct information about Cerner and/or MHV so that I am not confused about where my patient portal information is housed.

Note that authenticated users who are not patients at Cerner facilities should see the same content/UX as unauthenticated users (see #5741)

Mock-ups and content at https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404897044

Acceptance Criteria
- [ ] Content on Prescriptions page (above and below alert box) for authenticated Cerner patients displays the necessary Cerner-specific information
- [ ] Content on Prescriptions page (above and below the alert box) for authenticated users who are not Cerner patients is the same as for unauthenticated users
- [ ] Content updates match the mock-up (if there are issues with the specific content, loop in Danielle and Peggy)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by MickinSahni** [comment]
Validated internally on local
