### ISSUE TITLE
Unauthenticated User Updates: Test Results page - Unauthenticated users main content updates

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10263]
**User Story**
As a user who is browsing the Test Results page on VA.gov without authenticating (logging in), I want the content on the page (above and below the alert box) to be neutral between MHV and Cerner so that I am not confused about where my patient portal information is housed.

Mock-up and content at https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405217796

**Acceptance Criteria**
- [ ] Content on Test Results page (above and below the alert box) for unauthenticated users does not contain any references to MHV or Cerner
- [ ] Content updates match the mock-up (if there are issues with the specific content, loop in Danielle and Peggy)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by kelsonic** [comment]
PR is open https://github.com/department-of-veterans-affairs/vets-website/pull/13198
