### ISSUE TITLE
Redirect Request for The Program of Comprehensive Assistance for Family Caregivers

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10277]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
Redirect request from #9376 

We need to change the url for The Program of Comprehensive Assistance for Family Caregivers
current url | redirect to (new url)
--- | ---
www.va.gov/health-care/family-caregiver-benefits/comprehensive-assistance/ | www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/

### Requestor team info
Public Websites Team

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

from:
/health-care/family-caregiver-benefits/comprehensive-assistance/
to:
/family-member-benefits/comprehensive-assistance-for-family-caregivers/

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by DanielleThierryUSDSVA** [comment]
**Note:** Please coordinate with Drupal URL update captured in this issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10284.

**Comment by mnorthuis** [comment]
This redirect is vetted and ready to go when your team is ready. 

Please note: there is an older vets.gov URL that is currently pointing at the current URL, this redirect does not need to be updated at this time.  (www.vets.gov/health-care/family-caregiver-health-benefits/comprehensive-assistance-family-caregivers/)

**Comment by stephorkandatx** [comment]
need this by the beginning of July - Danielle has asked that we do this as soon as we can

**Comment by lunascoop** [comment]
@ncksllvn this can be implemented now as no stakeholder notification is needed.

**Comment by lunascoop** [comment]
Actually this page is not live: www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/. Shouldn't we hold off on this redirect until the page is live? ...And, when will this page go live? @DanielleThierryUSDSVA

**Comment by ncksllvn** [comment]
PR is open - https://github.com/department-of-veterans-affairs/devops/pull/7135

I think the redirect and the page-move will have to go together if I understand correctly. Can we plan on moving the page via Drupal and publishing the redirect on Monday?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Yes, definitely hold off until page is live. See note above re: coordinating with Drupal URL update captured in this issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10284.

@ncksllvn Monday would be fantastic. @RLHecht and I will make sure to publish Drupal page on Monday. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ncksllvn @RLHecht. Looks like new URL is working. But https://www.va.gov/health-care/family-caregiver-benefits/comprehensive-assistance/ is throwing an error message. So just wanted to check in to make sure we have redirect in place. Thanks!

**Comment by ncksllvn** [comment]
Working with DevOps on this, https://dsva.slack.com/archives/CBU0KDSB1/p1592839630199700

**Comment by ncksllvn** [comment]
@DanielleThierryUSDSVA fixed!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much, @ncksllvn!
