### ISSUE TITLE
[Development] BDD: Cache servicelocation (Post Launch)

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#10275]
## Issue Description
the data for /v0/disability_compensation_form/separation_locations does not change often and should be cached. 

@annaswims started a branch aec/9735_intake_sites_cached but it was going to delay the original so it is a new ticket.

There was a discussion around whether this needs to happen and Anna indicated that caching for a day will prevent this being an issue if the end service is down.  The other suggestion was to hard code but since there is a service that will provide the latest service location information we should likely use it to avoid having to make manual changes.

Questions: How do we test this?  Can we simulate the service location endpoint being down?  Do we use the cached version for the entire 24 hours or do we only use it if the service is down?

## Acceptance Criteria
- [ ] Service location will cache for 24 hours.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Post launch, one of the first items to work so we do not rely on EVSS.

**Comment by lihanli** [comment]
@annaswims is the `separation_locations` data the same for every user?

**Comment by annaswims** [comment]
The data is the same for every user, but for some reason the API still requires the same auth headers that have user's info.  So, caching feels a bit weird to me but is probably fine.

**Comment by annaswims** [comment]
the data is different on different environments though.
