### ISSUE TITLE
[Development] BDD: Create mock data for EVSS separation_locations

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#10276]
## Issue Description
create mock data for /v0/disability_compensation_form/separation_locations.

Related to testing and caching separation location work

## Acceptance Criteria
- [ ] Mock data for testing separation location created

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Post launch work as well for BDD.

**Comment by annaswims** [comment]
@luke-gcio I'm adding this to the next sprint.  Now that the endpoint is being called this is necessary for local development.
