### ISSUE TITLE
[Development] Claims Status: Update Wording for Timing of Processed Claim Evidence Documentation

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10287]
## Issue Description
Provide a time frame of how long it takes for faxed/mailed/uploaded evidence to processed by VBA before claim status changes.  Have talked to Paul Shute and have sent an email on this.  Sounds like we will need to use a range.

**Response from Paul Shute:**
Not all evidence will result in a claim status change that the Veteran will see. Often times evidence is submitted, the adjudicator reviews the evidence, however additional evidence gathering or administrative actions are needed before the claim moves to the next status.

With that being said, we’ll probably want to assure Veterans that when they submit evidence to VA, we receive it within days and associate with their record, however, the evidence will then be reviewed and considered in relation to the Veterans claim before a claim status change will be made.

**My Notes**
How soon after I submit evidence does the status of my claim change?  It really depends.  Some evidence does not change the status of the claim, some do. It is not easy to describe this scenario and it may only be possible to say "We have received your evidence and associated it with your claim. If it impacts the status of your claim you will see that change within 30 days". 

## Acceptance Criteria
- [ ] We do enough research to make sure we are not making false claims on the timing.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
>If it impacts the status of your claim you will see that change within 30 days

@luke-gcio is this 30 days from submission or 30 days from VA personnel reviewing the submitted evidence?

**Comment by kevinstachura** [comment]
I have generated this copy, contingent upon the above answer:

>**We have your evidence**

>Thank you for sending us additional evidence. We will associate it with your record in a matter of days. If the submitted evidence impacts the status of your claim, then you will see that change within 30 days of review.

>Note: It may take a few minutes for your uploaded file to show here. If you don’t see your file, please try refreshing the page.

@Mottie you know that confirmation success alert box that shows when a user uploads evidence? We want the exact copy above to go in there. The alert we currently show looks like this:

<img width="1159" alt="Screen Shot 2020-06-29 at 10 12 24 AM" src="https://user-images.githubusercontent.com/54544300/86017346-f19bd500-b9f1-11ea-842f-e7b8ae00bc38.png">

**Comment by luke-gcio** [comment]
30 days from submission confirmed!
