### ISSUE TITLE
Missing Community Care facility type

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10286]
## What happened?
The user does not have the ability to find a specialty type when Community Care is chosen from the Facility type dropdown on Facility Locator.  The team was able to reproduce this on a variety of browsers and devices this morning during planning. 

This may be related to the feature flag for Facilities V1 which was flipped on right before we noticed this bug. 

## Acceptance Criteria
1. Facility type drop down should include 

- VA health
- Urgent care
- Community providers (in VA's network)
- VA benefits
- VA cemeteries 
- Vet Centers 

2. When Facility type = Community providers (in VA's network) and the user begins to enter a service type into the typeahead, matches appear as dropdown for selection. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brangi** [comment]
merged and live
