### ISSUE TITLE
v2 Express Care Prototype for VA.gov/VAOS

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10283]
**Recommendations to consider based on research:** ([Full research here)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/express-care-research/2020-may-research/express-care-research-report.md)
1. Incorporate "Express Care" and/or Telehealth resources immediately accessible for Veterans when scheduling appointments.
2. If "Express Care" is going to be offered, the experience must clear and consistent across the entire VA medical ecosystem.
3. If "Express Care" is going to be offered, responses must be from medical professionals, not schedulers.
4. Timeliness is critical, especially for same-day and urgent types of care. Responses to "Express Care" requests must be within the time promised.

**Prototype used during research:** https://projects.invisionapp.com/share/3PWYUFVAVQU#/screens/414573920

**Current EC implementation in legacy VAOS:** (see walk-through here -- [https://app.zenhub.com/files/133843125/44889afd-4fac-4a62-be01-30cecc0ec5f2/download](https://app.zenhub.com/files/133843125/44889afd-4fac-4a62-be01-30cecc0ec5f2/download)
1. Veteran is informed of EC option via site-specific website (ex. SF VAMC) or in MHV
2. Veteran logs on to VAOS and reads Express Care criteria
3. Veteran either selects EC or is dropped into Express Care flow based on how they accessed the EC option
4. Fills in all required fields and hits submit

**Comment by rtwell** [comment]
@peggygannon @lenaecb @lalexanderson-dsva here's the quick critical path—side note: click anywhere on the header to start over

https://vsateams.invisionapp.com/share/U9XQMY2GS5V

**Comment by peggygannon** [comment]
@rtwell, please see below for content recommendations for the Express Care prototype. Please let me know if you have any questions about my feedback. 

cc@lenaecb        


First screen content edit: 

**If you need to talk to someone today about your symptoms, you can request an Express Care screening**
If you have a non-life threatening symptom and want to talk to someone before going to a clinic, urgent care facility, or emergency room, you can request an Express Care phone screening with a health care provider.  Contacting us first helps protect you, medical staff, and other patients. 

Don’t use Express Care if you're having an emergency or need to talk to someone right away.

{CTA button} Request an Express Care screening

------

Screen 2
{head} Request an Express Care screening 

{Alert}
**If you need to talk to someone right now or need emergency care: 
	- Call 911, **or** 

-	Call the Veterans Crisis hotline at  800-273-8255 and select 1, **or**

-	Go to the nearest emergency room. For emergencies, you don’t need a referral or approval from VA to go to a non-VA ER in your community
{end alert}

**Can I use Express Care?**

You can use Express Care if you need same-day medical advice for a non-life threatening symptom. You don’t need a PACT assigned to you to use Express Care. 

**How it works**

{begin Subway map}

1. **Express Care is available only during certain hours**

This option is available between 9:00 a.m. to noon at your local VA medical center. You can’t request an Express Care phone screening before or after these hours.

2. **After you make a request, a health care provider will call you** 

The health care professional who will call you may be a registered nurse (RN) or a licensed independent practitioner (LIP). Your doctor won’t call you. 

Please have your phone nearby after you make your request so you can receive their call. They'll try to contact you up to 3 times. 

3. **During the call, they'll assess your condition and recommend next steps**

They might recommend a follow-up call or video visit with your doctor or a specialist. They may give you a prescription. You might not have an in-person visit with your doctor after the Express Care call.  

{CTA button}
Request an Express Care screening

Screen 3

**Select a reason for your Express Care call**

{radio buttons}
Cough without shortness of breath

	{text box} Please provide additional details about your symptoms

Gastrointestinal symptoms without abdominal pain, such as diarrhea, constipation, nausea, vomiting, upset stomach, or acid reflux

Headache that isn’t severe

Musculoskeletal pain that isn’t from trauma

Red or weeping eye without pain or vision loss

Skin lesion or rash

Upper respiratory symptoms, such as earache, runny nose, nasal or sinus congestion, sore throat, or hoarse voice

Urinary symptoms, such as painful urination, frequent urination, difficulty urinating

**Your contact information**

A health care worker will use the below information to contact you

Phone number (we don’t usually have a field for the 1+.. are we doing that for international numbers? 

Email address 

------

Screen 5

**Your Express Care request has been submitted**

Please change Appointment detail TO Your symptom detail

**Comment by rtwell** [comment]
prototype updated @lenaecb @peggygannon 

https://vsateams.invisionapp.com/share/U9XQMY2GS5V

**Comment by peggygannon** [comment]
Thanks, @rtwell . I'm going to make some additional tweaks based on my sync with Lenae and Lauren yesterday. I'll list them here and put in the mockup.

**Comment by peggygannon** [comment]
@rtwell some additional content updates to the EC prototype. I also added these to the mockup. 

also, I am still PL the conditions list. will drop that into the mockup on Monday. 

Screen 1
Update to this alert to more clearly define Express Care

**If you need to talk to someone today about your symptoms, you can request an Express Care screening**
With Express Care you can get a same-day telehealth appointment with a health professional. Express Care is for non-life threatening conditions or symptoms. Don’t use it for emergency care or if you need to talk to someone right away. 
Contacting us before going to a clinic, urgent care facility or emergency room first helps protect you, medical staff, and other patients. 
{CTA button} Request an Express Care screening

-----

Screen 2

1. Update to this content to add some condition examples: 

**Can I use Express Care?**
You can use Express Care if you need same-day medical advice for certain conditions or symptoms, such as cough, sore throat, headache, skin rash, and nasal or sinus congestion. See the full list of the conditions you can schedule for an Express Care appointment on the next screen.

You don’t need to have a PACT assigned to you to use Express Care. 

2. Update to 1st bullet on subway map
**Submit your Express Care request between 9:00 a.m.-noon**
We accept requests only in the morning to make sure we can talk to everyone the same day. You can’t make an Express Care request before or after these hours. 

-------

Screen 3
I'm recommending we  change "call" to screening to match the button that take users into this screen. 
Also, I've added 1 line of content to set up the radio buttons

**Select a reason for your Express Care screening**

You can request an Express Care appointment for the conditions or symptoms listed below.

**Comment by rtwell** [comment]
prototype updated!

**Comment by lenaecb** [comment]
Latest version of EC prototype: https://vsateams.invisionapp.com/share/U9XQMY2GS5V#/screens/422011176

**Comment by lenaecb** [comment]
Latest version as of 7/20 - https://vsateams.invisionapp.com/share/BVY4QCOJM4U#/screens/425790746
