### ISSUE TITLE
[Development] Claims Status: Provide information about how to get a copy of your Comp/Pen Exam

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10288]
## Issue Description
Provide information about how to get a copy of your Comp/Pen Exam.  Need to figure out where this information should be displayed. 

We have this information on this page: https://www.va.gov/disability/va-claim-exam/

Not sure if this is still the best information we can provide at this point.

![image.png](https://images.zenhubusercontent.com/5d54025346ffca000148e7f7/a4bc133b-52b9-4b48-bc52-fc1177b818e6)

**Response from Paul:**
_The current web content directing the Veteran to their local regional office is the best guidance to include. They can also submit a Freedom of Information Act Request, however, I’m not sure that we want to encourage additional FOIA requests being submitted._

**My Notes**
_Guidance to coordinate with regional office.  They can also submit a FOIA act request.  Do not request a copy from the regional exam vendor._

## Acceptance Criteria
- [ ] Make sure the info posted on the VA.gov site linked above is the most current.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Thinking we can simply add this content section beneath the 'need help?' section on the file upload tab's sidebar as it has FAQ-type information on it already:

<img width="1266" alt="Screen Shot 2020-06-29 at 3 57 35 PM" src="https://user-images.githubusercontent.com/54544300/86050088-4440b580-ba21-11ea-8125-f86394f8c566.png">

>Want a copy of your Claim Exam?

>You can obtain a copy of your claim exam (also known as a compensation and pension, or C&P, exam) by contacting your nearest regional office.


Further, the pattern has been established that more of the detailed information seems to show up consistently on the sidebar for the CST.

**Comment by luke-gcio** [comment]
I'm ok with adding it under the "need help" although it may be very specific in the sense that only when they have an exam recorded somewhere.  Is that possible?

**Comment by kevinstachura** [comment]
Hmm. I would respond with this thought - do you think it would be helpful to know what the process _will_ be for obtaining your exam result, even before you have completed a C&P exam?

**Comment by kevinstachura** [comment]
Created a visual for this ticket as well:

<img width="1012" alt="Screen Shot 2020-07-01 at 10 38 49 AM" src="https://user-images.githubusercontent.com/54544300/86257731-f2ff0600-bb87-11ea-8291-5a7d0007b365.png">

However **noting that this should show up on the 'files' tab, principally, and not necessarily on the status tab as shown** (the only claim detail screenshot I had of CST - tool is down at the moment).
