### ISSUE TITLE
[Development] Claims Status: Provide Information on Communication Post Claim Closure

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10292]
## Issue Description
Provide information about how long it takes from the time a claim decision is made until decision is communicated and the first payment is sent/deposited.  This is also tricky, per Paul, but we are working it.  Long email sent with some info, I will post here when results are obtained.

**Response from Paul Shute:**
Once the claim decision is made, the decision notice will be mailed to the Veteran and the time it takes to reach them is dependent on mail routing timeframes specific to the US Postal Service. Typically, decision notices are received within 10 days.

The payment piece gets a little more tricky. If the Veteran is entitled to retroactive benefits, that payment is made within days of the decision. All regular recurring monthly payments occur on the first of the month, so the overall timeframe is dependent on when the decision is made in relation to the monthly payment distribution (which usually occurs on the 1st of the month).  

**My Notes**
Part 1: If I am getting a retroactive payment (based on effective date) will get paid within 5-7 days within days of the decision. Some sort of HCD around how to explain this process because the letter does not use the word "retroactive" in the letter (not official HCD obviously but these were Paul's words).
Part 2: When it is not a retroactive benefit, you will receive your payment within 1 month depending on when the decision was reached.  Payments go out on the first.

## Acceptance Criteria
- [ ] Make sure the timing range is realistic.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
I'm thinking of this copy for the above explainer:

>Once a claim decision is made, a decision noticed will be mailed to you. Typically, decision notices are received within 10 days, but this is dependent upon U.S Postal Service timeframes.

>**Payments**

>If you are entitled to retroactive payments (based on an effective date), you can expect to receive payment in 5-7 business days. If your payment is not retroactive, you can expect to receive payment within 1 month of a decision date. 

Unfortunately the CST in staging is not actually showing claim detail screens (just spins infinitely). But from memory and from @Mottie 's assistance I was able to determine where this should probably go, contextually, in the CST. I would expect it would show under the 'complete' portion under the details tab of a claim detail screen.

![Screen Shot 2020-06-30 at 9 59 43 AM](https://user-images.githubusercontent.com/54544300/86143426-68080800-bac2-11ea-9f57-0ca52411a67f.png)

The above screenshot is from a local environment but shows what a complete (closed) claim should look like in the CST.

**Comment by luke-gcio** [comment]
Only thing with this one is Paul mentioned that not everyone knows what a "retroactive payment" looks like. Do you have any thoughts on this?

**Comment by kevinstachura** [comment]
Yeah @luke-gcio I hear ya on that...I just would like to confirm the same. If we had the time frame to confirm the definition of what a retroactive payment is (in the eyes of the VA) then I would be happy to dig into this to clarify language, but my #1 worry is giving incorrect information. My assumption is that this is 'back-pay'. Is that how you understood this? And could we confirm this (and be certain of the VA's definition of what 'retroactive payment' is) within the next 24 hours? Otherwise I have to err on the side of caution without assumptions at this point.

**Comment by luke-gcio** [comment]
"If you are expecting back payments through your intent to file date"?

**Comment by kevinstachura** [comment]
Alright, I have changed a bit of the content to fit the given context in the page and to use the terminology of back payments, which may be easier to understand for the user:

>A decision packet is being mailed to you. Typically, decision notices are received within 10 days, but this is dependent upon U.S Postal Service timeframes.

> Payments

>If you are entitled to back payment (based on an effective date), you can expect to receive payment in 5-7 business days. If your payment is not retroactive, you can expect to receive payment within 1 month of your claim’s decision date.


It will be dropped in here:

![CST-decision-notice](https://user-images.githubusercontent.com/54544300/86289044-f78fe280-bbb8-11ea-9202-34f44e4f9ff9.jpg)


@luke-gcio what do you think?

**Comment by kevinstachura** [comment]
And a version for a closed claim status - so the user can still refer back to the information:

<img width="722" alt="Screen Shot 2020-07-01 at 4 44 03 PM" src="https://user-images.githubusercontent.com/54544300/86289728-307c8700-bbba-11ea-9fb4-c793d310e1fc.png">
