### ISSUE TITLE
Fix vets-api rubocop linting exemptions

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#1029]
## The Problem
We have many exemptions in our [vets-api rubocop yml file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.rubocop.yml). Comments from within the file itself indicate that we should be revisiting these excemptions. A few examples:

- [# IMPORTANT: this needs to be changed or handled differently. NoMethodError is not acceptable.
Skipping it for now as I dont have time to address.](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.rubocop.yml#L163-L164)
- [# Skipping for now, should revisit](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.rubocop.yml#L171)

## Acceptance Criteria / Work to be Done
- [x] Identify the exemptions that have the biggest impact and are the easiest to fix
- [x] For small issues: remove exemptions from .rubocop.yml and fix the relevant lint issue(s) in the ruby code
- [x] For big issues: a ticket is created in Github to track the work

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/3236

**Comment by LindseySaari** [comment]
Through my development and identification, I was able to refactor syntax related rubocop exemptions. There were no larger issues that needed to be tracked in GitHub. Detailed changes and finding are listed in the GitHub PR description.
