### ISSUE TITLE
[Development] Claim Status: Information on Time Estimate to Complete (for Appeals)

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10293]
## Issue Description
NCC recommendation was to mask estimates longer than one year; upon further investigation, the data feed needs improvement, so initially going to remove estimate messaging until the data can be resolved.

Looks like the call to this is dynamic and we should comment out the call and possibly remove the whole section of content. Assigned to design since maybe we can come up with some wording that is better.  During a meeting with talked about "on average it takes BLAH but in some complex cases it can take multiple years" or something like that.

Convo about where this is located in the code: https://dsva.slack.com/archives/CDHBKAL9W/p1589344568495100?thread_ts=1589299198.475700&cid=CDHBKAL9W

## Acceptance Criteria
- [ ] Remove the information without doing HCD.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
@luke-gcio just seeing what I might be able to do from a design/copywriting perspective - is there any guidance on the accurate timeframes here? We have two sections that would need updating:

![Screen Shot 2020-07-01 at 3 55 50 PM](https://user-images.githubusercontent.com/54544300/86291806-90c0f800-bbbd-11ea-803c-0cd9ddbe40f8.png)

The '2-12 months' (when it's sent to the board) and the '7-20 months' (when Veteran can expect SSOC). Would there be time frame we could change within these gray boxes (even something like '2 months - 5 years', for example) or would we just look at potentially crafting the text copy beneath the headings (and just totally remove the gray boxes for now)? 

For further reference, here's where the above screenshot appears in the overall page:

![localhost_3001_track-claims_](https://user-images.githubusercontent.com/54544300/86292031-fd3bf700-bbbd-11ea-95bf-558964e2334d.png)

Whatever extra guidance we have at this time would be much appreciated - thanks!

**Comment by Mottie** [comment]
The code to hide these duration cards has been merged, but I'll leave this ticket open until we figure out if it was the right way to go.

**Comment by sshein** [comment]
this is a tricky one. Is it worth getting Peggy's input on this?

**Comment by Mottie** [comment]
> this is a tricky one. Is it worth getting Peggy's input on this?

I'm not sure. The NCC wants to remove times > 12 months (see the Slack discussion); I was going to wait on merging these changes, but they wanted it done yesterday.

**Comment by sshein** [comment]
can you link the slack discussion here for visibility? I'm obviously way out of the loop here so have no insight into required timelines, etc :(

**Comment by Mottie** [comment]
It's was in the top comment - https://dsva.slack.com/archives/CDHBKAL9W/p1589344568495100?thread_ts=1589299198.475700&cid=CDHBKAL9W

**Comment by sshein** [comment]
ok well I won't get in the way of whatever plan the team has if there have been promises made
