### ISSUE TITLE
[CONSIDER] In creation of VAMC-Page Hardening - Determine if Regional Content is required

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10296]
## Story
_In CMS page hardening there are content pages that have Regional information, that would sit between National and System content,  Perhaps at the VISN level so that all Systems in the VISN can update the content across all pages with one edit, (for example: Regional DAV-VAN numbers, schedules, etc).

**Comment by davidmpickett** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12583
