### ISSUE TITLE
[Documentation] Update disability_compensation_form swagger docs

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#10300]
## Issue Description
Update [disability_compensation_form swagger docs](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/swagger/requests/disability_compensation_form.rb) to reflect that all actions will return a HTTP 403 if EVSS attributes aren't present.

## Acceptance Criteria
- [ ] Swagger/documentation updated so it reflects the correct error codes.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vhenry07** [comment]
Closed complete.
