### ISSUE TITLE
[Development] BDD: Update vets JSON-schema for separation location and STR

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10309]
## Issue Description
During grooming, we identified we need to make some final schema updates for sep location and STR.

## Acceptance Criteria
- [ ] Schema updated and back end is aware
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
PR here done by back end:

https://github.com/department-of-veterans-affairs/vets-json-schema/pull/442
