### ISSUE TITLE
[FE] -  Build state in Direct Deposit where user hasn't set up but is eligible

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10312]
## Background 
[related design ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8757)
Add state in DD where user hasn't set up but is eligible #8757

![image.png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/1a186288-240d-4538-9862-d989762f0e07)

## Tasks
- [ ] Build new state in Direct Deposit

**Comment by erikphansen** [comment]
Changed this from a 1 to a 2. The change was more involved than I initially thought it was going to be.

**Comment by erikphansen** [comment]
@tressaellen @mshea0606 you should be able to validate this on staging with user 201. List of Direct Deposit test users is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/test-users.md).

**Comment by tressaellen** [comment]
Hey @erikphansen - everything looks good. There has been a change to the content from Peggy - the "What's my bank routing number?" FAQ will be removed from the page.  Do you want me to create a separate ticket for that, or do you want that tracked here?
<img width="515" alt="Screen Shot 2020-06-22 at 9 18 54 AM" src="https://user-images.githubusercontent.com/58752772/85304810-a6654d80-b458-11ea-8ba5-411f65f3d8a3.png">

**Comment by erikphansen** [comment]
@tressaellen is that always removed or only when DD is not set up? I'm guessing the former.

**Comment by tressaellen** [comment]
It will always be removed

**Comment by erikphansen** [comment]
k I'll just update this PR with that change.

**Comment by erikphansen** [comment]
Actually I'm making a ticket for this. I had already merged the PR and @mshea0606 wants us to track little things like this.
