### ISSUE TITLE
[Ongoing Service] Maintain & improve Analytics tools

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#10325]
### High Level User Story/ies
As a VFS team member, I need to be able to trust the quality of my data so I can make accurate decisions about my product.

As a VFS team member, I need my data to be consistent with other VA.gov products so that I can accurately compare my data with other like data across the website.

As a Platform Analytics & Insights team member, I need standard metrics already tracked so that I can focus my time on edge case tracking.

### Problem Statement 
As VSP Analytics & Insights has implemented Google Tag Manager for VFS teams, we've noticed areas of improvement for data quality in Google Tag Manager as well as some bugs that need to be fixed.

How might we improve the data quality for analytics on VA.gov so that accurate data is used for reporting and making decisions on VFSs?

How might we increase scalability on our analytics tools so that we can support more VFS teams?

### Hypothesis or Bet
If we take some steps back to not only support teams in implementing GTM, but also fixing bugs and improving the dataLayer as well as other types of analytics tools improvements and data standardization, then we expect higher data quality with more accurate reporting, more trust around our metrics, and the ability to scale our support.

### OKR
O4: Stability and resiliency of VSP's systems and teams continue to improve.

### Success metrics 
- Customer satisfaction
- Number of VFS reports shared

### Communication
- Team that owns this super epic: Analytics & Insights
- Teams contributing to this super epic: might occasionally need some support from the FE & BE Tools teams, and the Design System team

**Comment by johnny-jesensky-adhoc** [comment]
Closed as part of backlog review on Feb 23, 2024.
