### ISSUE TITLE
Create email content for 526EZ (Disability comp) successful submission

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#10328]
## User story
As a Veteran applying for disability benefits, I want to know that my claim was successfully submitted.
VA will begin sending emails to let applicants when their claim was submitted. 

## Acceptance criteria
- [x] Peggy to craft email message  letting users know their 526EZ claim was successfully submitted.  
- [x]  Email message should "reusable" so we can use this template for other benefit categories/forms in the future. 
- [ ]  Once VA email notifications have been rolled out to 100% of users, we'll need to also provide content within the form (introduction or confirmation page?) letting users know that they will receive an email notification after successfully submitting a 526EZ claim.

**Comment by peggygannon** [comment]
connecting my issue to the notifications-api [issue 81](https://app.zenhub.com/workspaces/notifications-5ea0ae59b51ccc3c83a8b65b/issues/department-of-veterans-affairs/notification-api/81)

**Comment by toddstanich** [comment]
@peggygannon a couple of additional content notes came out of our design intent meeting with the VSP team. Adding them here for your reference.

- Ensure that subject line is clear and concise for what it is and provides trust
- Consider adding text to check status CTA that indicates they will need to log in

**Comment by peggygannon** [comment]
@toddstanich ok, thank you. I'm going to be working on this today.

**Comment by peggygannon** [comment]
Hello, @toddstanich Please see below recommended content for: 
-- Successful 526 submission email
-- Suggested content for email template to be used across benefit applications. 

One thing to note about the 526 email.
--For disability comp applications, we use "file" vs. "apply", per user research done a few years ago. So I've adjusted the first line of the 526 email to accommodates that. (Other benefits use "apply" so the Email 
Template below has that). 

Please let me know your thoughts and if you'd like to meet to discuss in a call. 

-----

1. 526 successful submission


Subject line: We’ve received your application

Dear {first name} {last name},
Thank you for filing a claim for disability compensation. 

We process applications in the order we receive them. If we have questions or need more information, we may contact you. We’ll notify you by mail once we’ve processed your claim.

To check the status of your claim, you can [sign in to our claim status tool]( https://www.va.gov/claim-or-appeal-status/). Please allow 24 hours for your disability claim to show up there. 

You claim details are below:  
{Benefit name}
Confirmation number: {tk}
Date submitted: {Month, day, year}

Thank you for your service, 
VA.gov

-------

2. Email template

Subject line: We’ve received your application

Dear {first name} {last name},

Thank you for applying for {name of benefit}. 

We process applications in {time frame for that benefit}. If we have questions or need more information, we may contact you. We’ll notify you by mail once we’ve processed your claim.

To check the status of your claim, you can [sign in to our claim status tool]( https://www.va.gov/claim-or-appeal-status/). Please allow 24 hours for your {name of benefit} claim to show up there. 

You claim details are below:  
{Benefit name}
Confirmation number: {tk}
Date submitted: {Month, day, year}

Thank you for your service, 
VA.gov

**Comment by toddstanich** [comment]
Hi @peggygannon thank you for sending this over. I dropped the content in the email template design here - https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/design/email-template/email-html-alt.jpg

A couple questions for you:
• We plan to display full URLs instead of linking text so users see can see what they are clicking on or copy and paste the link if they are not comfortable clicking on it. Because of this, I made a change to the "...you can sign in to our claim status tool at www.va.gov/claim-or-appeal-status" line. I'd like your feedback on if that is the best way to phrase a sentence with a full URL.
• We would like to include a headline at the top of the email so users have a quick understanding of the contents of the email after opening. I used the subject line for this. Thoughts on if this should be the same as the subject line or different?

**Comment by peggygannon** [comment]
Hello, @toddstanich! answers to your questions below, and I have one question for you: 

1. *re: We plan to display full URLs instead of linking text so users see can see what they are clicking on or copy and paste the link if they are not comfortable clicking on it.*
I've updated email (below) to account for this

 2.* re: We would like to include a headline at the top of the email so users have a quick understanding of the contents of the email after opening. I used the subject line for this. Thoughts on if this should be the same as the subject line or different?*
I think it's fine to be the same. I would like to keep the headline succinct and relatively short, so I think it's OK for it to be the same as the email subject line. 


3. I made the signature "Thank you for your service".. this works for disability comp, but won't work if these emails  eventually go out to a Veteran's dependents or spouses for other benefits (education, for example). 
do you know if a Veteran's dependent might also receive emails in the future? If so, I might tweak that template. 


------

Updated disability comp email 

Subject line: We’ve received your application

**We've received your application**

Dear {first name} {last name},

Thank you for filing a claim for disability compensation.

We process applications in the order we receive them.  If we have questions or need more information, we may contact you. We’ll notify you by mail once we’ve processed your claim.

To check your claim’s status, go to https://www.va.gov/claim-or-appeal-status/ to sign in to our claim status tool. Please allow 24 hours for your disability claim to show up there.

You claim details are below:
{Benefit name}
Confirmation number: {tk}
Date submitted: {Month, day, year}

Thank you for your service,
VA.gov

**Comment by toddstanich** [comment]
@peggygannon Thank you!

Re: For point #2 about the "thank you for your service" signature, I imagine we will run into scenarios where the emails go to people other than the Veterans. We may need to follow up with the business unless @QaysarA, you know.

**Comment by peggygannon** [comment]
Ok, thank you @toddstanich  I just want to make sure if we do have the the use case of sending emails to dependents or family member, then we'll need to revisit the email template signature.

**Comment by QaysarA** [comment]
Yes, the template will also be used for beneficiaries who may not be Veterans

**Comment by peggygannon** [comment]
OK, thank you @toddstanich @QaysarA In that case, I've updated the signature for the overal email template above. 

I still recommend using Thank you for your service for the 526EZ email, as I think it's important to acknowledge the Veteran's service.
