### ISSUE TITLE
Track VFS product launches

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1033]
## User Story
As VSP, I need to know whether we are meeting our north star of empowering VFS teams to launch great products, so I can prioritize iteration to VSP features/docs/process etc as needed.

## Goal
O3. Agility: incentivize VFS Teams to build performant applications in an agile way.
KR: 
`>` 4 new major pieces of functionality have been launched on VSP

O5. Self-service: ensure VSP scalability through increased self-service tooling and documentation.
KR: All new VFS applications are built using example app / SDK

But the overall goal of this particular issue is to have a way to track what launches, and whether the things launching are objectively good products. I.e. are meeting SLOs, used the Sample App, met Prod Dev Requirements.

## Acceptance Criteria
- [ ] Some document exists and is shared w/the Product Dev Support Team, VSP Leadership, and Leah and Patrick that enables the Prod Support team to leanly capture the minimum necessary info, and allows leadership to understand and see whether we're hitting our KRs.

**Comment by shiragoodman** [comment]
@andreahewitt-odd do you think this is something we can close? I don't think this falls under the scope of Product Support.

**Comment by andreahewitt-odd** [comment]
@shiragoodman yeah close it. We kind of do it with the collab cycle tracker
