### ISSUE TITLE
[FE] Update connected apps 

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#10330]
## Background

The lighthouse team has made some changes to connected apps, so we need to update the profile to reflect these.  They will have copy changes to us by the end of the week. 

## Specs

Invision: https://vsateams.invisionapp.com/share/BHXQ39SKGYZ

[Design and Copy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/connected-apps-2.md)

## Tasks

-[ ] Update connected apps with new layout and copy

## Acceptance criteria

-[ ] Connected apps is updated
-[ ] Connected apps has been reviewed by Tressa/Matt

**Comment by mshea0606** [comment]
Hey @tressaellen ! Could you drop the content updates in here once you get them? Thanks!

**Comment by sanlouise** [comment]
@mshea0606 This one is ready for validation 😄
