### ISSUE TITLE
Schedule "Load testing, Privacy, and Security" Intro Session

### ISSUE THREAD

**Issue by peterhill-oddball** [department-of-veterans-affairs/va.gov-team#1034]
Justin Pickett is inquiring about scheduling the introduction session for "Load testing, Privacy, and Security".  Coordinate a time between relevant VSA team members and VSP team members.

**Comment by peterhill-oddball** [comment]
Justin indicated the following team members will attend the session -- 

Justin Pickett: jpickett@governmentcio.com
Amen Ra: ara@governmentcio.com
Erik Hansen: erik@adhocteam.us
Lihan Li: lihan@adhocteam.us

**Comment by peterhill-oddball** [comment]
In support of VSP's presence, the following team members will attend --
Peter Hill: peter.hill@oddball.io
Anna Carey: anna@adhoc.team
Bill John Tran: bill@oddball.io

**Comment by annaswims** [comment]
our current load testing docs https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest

**Comment by peterhill-oddball** [comment]
Load testing presentation is complete.  Privacy and Security presentation should be complete by today 9/11 or tomorrow 9/12.  Justin would prefer an integrated onboarding session late this week or early next week.

**Comment by peterhill-oddball** [comment]
This has been scheduled for 9/20 at 1:30PM.
