### ISSUE TITLE
EYB: Add GA to Estimate Your Benefits Profile Section

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10353]
As a developer, I need to add google analytics to the comparison tool for the estimate your benefits enhancements so we can have a better understanding about how users are interacting with the tool.

## Assumptions:
1. This work is a result of #9991.
2. This story is limited to the "Estimate Your Benefits" section of the profile pages (VETTEC & Non VETTEC)

## Acceptance Criteria
1. The following event is captured on mini-accordion opening:
```
{
  'event': 'nav-accordion-expand',
  'accordion-size': 'small' 
}
```
2. The following event is captured on mini-accordion closing:
```
{
  'event': 'nav-accordion-collapse',
  'accordion-size': 'small'
}
```
3. The following event is captured when the "Update benefits" button is clicked:
    a. For non VETTEC profiles:
    ```
    {
      'event': 'cta-default-button-click',
      'gibct-parent-accordion-section': 'Estimate your benefits'
      'gibct-child-accordion-section': 'Your military details' 
    }
    ```
    b. For VETTEC profiles:
    ```
    {
      'event': 'cta-default-button-click',
      'gibct-parent-accordion-section': 'Estimate your benefits',
      'gibct-child-accordion-section': undefined
    }
    ```

4. The following event is captured on radio button change:
```
{
  'event': 'gibct-form-change',
  'gibct-form-field': 'FORM FIELD NAME OR ID',
  'gibct-form-value': 'FORM FIELD VALUE' 
}
```
5. The following event is captured on drop-down list change:
```
{
  'event': 'gibct-form-change',
  'gibct-form-field': 'FORM FIELD NAME OR ID',
  'gibct-form-value': 'FORM FIELD VALUE' 
}
```

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13225

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-23 at 12.30.14 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f2653182-1049-4d31-94b5-3bf3c780a550)
##
![Screen Shot 2020-06-23 at 12.30.33 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b5b847e8-7774-4554-bd3d-30aae398635e)
##
![Screen Shot 2020-06-23 at 12.30.43 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/92fa4f4a-ccdb-4118-b121-6b7745a27650)
##
![Screen Shot 2020-06-23 at 12.32.53 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/365f1a0b-f1f8-4a83-9727-08f65dc29b81)

**Comment by desireeturner** [comment]
Waiting on feedback via #9991 in order to close this issue.

**Comment by sonntag-adam** [comment]
Testing passes in #9991. Closing out current story.
