### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by LeakyBucket** [department-of-veterans-affairs/va.gov-team#10357]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
Lawrence.Holcomb@va.gov

I have created a new Google Account for my VA email address.

## Access Requirements

I really just need access to the MyHealtheVet analytics

## Date Required

As always, sooner rather than later.  We are trying to get better visibility around the MyHealtheVet user experience and currently GA looks to be the only real client side tool for metrics and performance on the platform.

## Product Team / External Team / VA Office
I'm currently working with DEPO/CTO's Office on an engagement with MyHealtheVet with @batemapf 

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @LeakyBucket ,

Thank you for setting up your Google account with your VA email. Lawrence.Holcomb@va.gov has been provisioned Google Analytics. 

While we don't track a great-deal of MyHealthEVet interactions, basic page-level metrics can be found within the "All VA.gov Website Data" view. 

We will close when we've heard from you that you're successfully able to access GA 😄

**Comment by LeakyBucket** [comment]
@jonwehausen Awesome thanks!  Looks like I'm in.
