### ISSUE TITLE
GIDS: Add 'POO Status' data to version export

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10358]
As an education team member, I need the 'POO status' data column from the WEAMS data to be included in the version export so I can better analyze the data within the dashboard tool.

## Acceptance Criteria
1. The 'POO status' column from the weams.csv is included as the last column in the generated version in GIDS.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
database PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/675

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/676

**Comment by sonntag-adam** [comment]
Last column in the data to version export

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/518&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
in staging
