### ISSUE TITLE
[Development] Increase testing for BDD forms submission (Pre-Launch)

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#10368]
## Issue Description
Test form submission and translation for new BDD form.

Some places to look (not complete list):
[spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb:29](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/lib/evss/disability_compensation_form/data_translation_all_claim_spec.rb#L29)
[spec/request/disability_compensation_form_request_spec.rb:120 ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/request/disability_compensation_form_request_spec.rb#L120)

## Acceptance Criteria
- [x] Increased confidence in BDD - very measurable
- [x] Fast path to submission (least amount of variables)
- [x] Long path let's make it a little more complicated
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Pushed into sprint 25, this was one of the lower priority items.

**Comment by luke-gcio** [comment]
Now that we have merged 526/BDD, we will likely just need to rerun and replace the saved script.
