### ISSUE TITLE
Build instrumentation for measuring success of production code deployments

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1036]
## User Story
As VSP, I need to know if we're meeting our goal of helping VFS teams be Agile.

## Goal
Measure the percentage of scheduled daily deploy jobs for vets-website and vets-api that do not need manual intervention (i.e. do not post a failure notification in #vetsgov-engineers Slack channel)

The goal for this specific issue is to create instrumentation that allows us to measure.

## Acceptance Criteria
- [ ] We have instrumentation capturing that data
- [ ] It updates automatically

**Comment by ricetj** [comment]
Adding a comment from Wyatt a few weeks ago here, because we had a ticket looking to track a few different metrics (#547): 
"This is one we probably want to track on a per-repo basis as each repo can be different. Other metrics that may be useful here are things like amount of time waiting before a worker was available. The plugin that we have installed in Jenkins is emitting some pretty limited metrics. I don't know yet how much work it could be to modify this. Jenkins also has some built-in metrics in the UI.. might be able to just export those somehow."

**Comment by ricetj** [comment]
@wyattwalter to help on giving more clarity

**Comment by benniemosher** [comment]
What instrumentation is being used for this? Where is this data collected from? Is this all happening in Jenkins and we need to do something in Prometheus to calculate this? This ticket needs more acceptance criteria and more direction.

**Comment by wyattwalter** [comment]
Hey @benniemosher. I'm not sure what you're asking about as far as "what instrumentation is being used". 

The ticket here has a high level goal of tracking the percentage of the daily deploys that go out without manual intervention. At this point we can safely assume that no manual intervention is needed if the central controlling job (http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-vets-api/ and http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-vets-website/) succeeds. So really, we care about what percentage of these jobs are successful over a quarter. The data source would ultimately be Jenkins for pass/fail per job, but I don't think we've decided whether the data gets stored in Prometheus or elsewhere. I think that we need to evaluate and make a proposal on where that should be calculated and/or stored.

**Comment by wyattwalter** [comment]
A highly manual version of this, written out in English/yaml:

For vets-api and vets-website, go to the "vets-gov-autodeploy-<app>/buildTimeTrend" page:

- http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-vets-api/buildTimeTrend
- http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-vets-website/buildTimeTrend

Get total number of jobs total number of failures

example:
  vets-website:
    jobs: 26
    failures: 3
  vets-api:
    jobs: 18
    failures: 0

Add values for vets-website and vets-api together

example:
  jobs: 44
  failures: 3

Calculate percentage of jobs that were successful

(1 - failures/jobs) * 100

example:
  (1 - (3/44) ) * 100
