### ISSUE TITLE
Build instrumentation for capturing build time

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1037]
## User Story
As VSP, I need to know if we're meeting our goal of helping VFS teams be Agile.

## Goal
Measure the percentage of CI builds against vets-website and vets.api branches (PR + master branch) that complete and give feedback to developers within 30 minutes.

The goal for this specific issue is to create instrumentation that allows us to measure.

## Acceptance Criteria
- [ ] We have instrumentation capturing that data
- [ ] We have a recommended goal for the KR
- [ ] It updates automatically

**Comment by ricetj** [comment]
Adding a comment from Wyatt a few weeks ago here, because we had a ticket looking to track a few different metrics (#547):
"This is one we probably want to track on a per-repo basis as each repo can be different. Other metrics that may be useful here are things like amount of time waiting before a worker was available. The plugin that we have installed in Jenkins is emitting some pretty limited metrics. I don't know yet how much work it could be to modify this. Jenkins also has some built-in metrics in the UI.. might be able to just export those somehow."

**Comment by ricetj** [comment]
@ricetj to update

**Comment by benniemosher** [comment]
What is the instrumentation to capture this data? Where does the data live? What does that instrumentation look like and where does it live? How do we come up with a recommended goal for KR? Do we pull something out of the clouds? What is it and how does it update automatically?

**Comment by wyattwalter** [comment]
In English(ish):

```
For vets-api and vets-website:

Query Jenkins API for build times on all branches of <app>

example: http://jenkins.vfs.va.gov/job/testing/job/vets-website/api/json?pretty=true&depth=2&tree=jobs[name,builds[number,timestamp,duration,result]]

Filter out result of "FAILURE" builds (or only return result of "SUCCESS")

Filter out timestamp values older than 3 months

Record total (with filters applied)
  total_jobs: total at this step

Filter out jobs with duration larger than 30 minutes (duration/1000/60 > 30)
  satisfactory: total at this step

Calculate percentage of jobs under 30 minutes

OKR = satisfactory / total_jobs * 100


(Average build duration is a nice-to-have)
```

**Comment by benniemosher** [comment]
Total Jobs can be found with this curl and jq command:

```
curl --proxy socks5h://localhost:2001 -g "http://jenkins.vfs.va.gov/job/testing/job/vets-website/api/json?pretty=true&tree=jobs[name,builds[number,timestamp,duration,result]]" | jq -c '.jobs | .[].builds | .[] | select(.result == "SUCCESS") | .timestamp |= (. / 1000 | strftime("%Y-%m-%d")) | select(.timestamp > (now - (90*24*3600) | strftime("%Y-%m-%d")))' | wc -l
```

Satisfactory jobs can be found with this curl and jq command:
```
curl --proxy socks5h://localhost:2001 -g "http://jenkins.vfs.va.gov/job/testing/job/vets-website/api/json?pretty=true&tree=jobs[name,builds[number,timestamp,duration,result]]" | jq -c '.jobs | .[].builds | .[] | select(.result == "SUCCESS") | .timestamp |= (. / 1000 | strftime("%Y-%m-%d")) | select(.timestamp > (now - (90*24*3600) | strftime("%Y-%m-%d"))) | select(.duration < (30 * 60 * 1000) )' | wc -l
```
