### ISSUE TITLE
Create process to help VFS teams document their Critical User Journeys

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1038]
## User Story
As the VSP team, I need to encourage VFS teams to document their critical user journeys, so that we can understand whether there's good e2e test coverage across VA.gov testing for these paths.

## Goal
O5. Self-service: ensure VSP scalability through increased self-service tooling and documentation.
KR: Test coverage: all new VFS apps have e2e tests exercising critical user journeys

The goal for this specific issue, is just to have an approach for helping VFS Teams define and document their critical user journeys. Perhaps that's templates / guides / a check-in we have with them after they've done a good amount of "define" and "discovery" work. But having that guidance in place will then enable us to track the KR referenced above.

## Acceptance Criteria
- [ ] Process, collateral, and supporting documentation exists in GH and is incorporated into the VFS Team user journey to help them document their critical user journeys.

**Comment by shiragoodman** [comment]
@andreahewitt-odd again, can we close out? not sure this falls under scope of Product Support.

**Comment by andreahewitt-odd** [comment]
@shiragoodman Yeah I would close this.
