### ISSUE TITLE
Access for Michael Pelz-Sherman

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#10384]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Michael Pelz-Sherman
- Please Provide your email.
   > mpelzsherman@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Facilities, Front-end Software Engineer, GovernmentCIO

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdqyKLao5uEv5nrjL4LCy+k/6E6XKrcwz9/9Mej2jvCIn4Gm78ZR82wrDA+Epo6kq8sNj1SrWPXoC1SYSbgU7eKBpWHfhSM61aGs9NzqKcxATqvOPVNTtrL97nPcsxVo9HLusmIBDuGlF8fLyQqyYrJj2lEvpllTjqM4N18YKbXcVKXsDWTun0KaHooFbzEzRMRufEVGlWiT1DLgjIubggKR910ndL5F4leaCFJmX4iatO+1Fk4rqKK/Rc/PNCqS+eApWQfqDWQaa2QtF06mdsPXe6lKfViDj3bEd2DPeI8brf6HSD/Cnk5wNvS0yXB7qY+h4zOrHLCYzPvS5sJviXLfaMZyxapnMfyDuhirtKvvTBDWtiAiZdQsLtMX2ohSpBmYzUusy2eTMH+iClxwys6POeGDr/fI1jgSp/XgQpONBSeRYpnZ/pHvqRN3jZ9mAf4b0Rp+FFHR59uHwXmEeES7NjaX7ymNtxWISGqqXNZxJMGTmSNf6Rcsy5TbQN7fs= michaelpelz-sherman@MichaelelzMBP13.attlocal.net
```

- Grant AWS Console access?
  > Yes
  - Please give a brief description for why you are requesting AWS access.
So that I can help troubleshoot back-end issues.

**Comment by mpelzsherman** [comment]
Pinging @department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
Name: Michael Pelz-Sherman

**Comment by tskinn** [comment]
@mpelzsherman you should have access to socks. Reach out in slack if you have issues connecting.
