### ISSUE TITLE
Design feedback for Design intent Collaboration [VANotify Email Confirmation]

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#10381]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**
- No “do” feedback at this moment

**Try:**

- Idea from Kevin: For usability testing, have a mock up flow for the disability form and have the testing participant receive the email

**Consider:**
- Consider speaking to Tressa Furner (she’s the designer on the VA profile)  about email notification preferences
- Consider testing with people who use assistive technology.
- Assistive tech guidelines and troubleshooting for using zoom for research: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/during-research/zoom-instructions.md
- Example conversation guide for people using assistive tech: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/Research/508_Usability_Study/conversation_guide.md

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by toddstanich** [comment]
Thanks @CrystabelReiter. We've captured these notes and added a card to our board for user research.

**Comment by CrystabelReiter** [comment]
Thanks @toddstanich I'll close the ticket
