### ISSUE TITLE
[Discovery] - Create prototype to be tested for Learning Center MVP usability study

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#10393]
Create interactive prototype for usability study

Acceptance criteria
- [ ] Interactive prototype created
- [ ] Prototype reviewed with stakeholders and team
- [ ] Prototype link added to research plan

**Comment by andaleliz** [comment]
Prototype created, waiting until convo guide is buttoned up before closing this 

https://vsateams.invisionapp.com/share/YJXZTKC6CN4

**Comment by MickinSahni** [comment]
hey @andaleliz can you estimate?

**Comment by andaleliz** [comment]
Closing this as no further changes are needed on the prototype
