### ISSUE TITLE
[Discovery] Environment management/isolated deployment

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#104]
## Description
Currently, whatever gets merged into staging gets deployed into production. Now we want to explore the potential path of adding ____@rianfowler___

## AC
- [ ] We've explored different options for controlling merging, review instances and deployment
- [ ] Research/discovery has been documented and shared with the Tools & Improvement teams.

**Comment by rianfowler** [comment]
Epic addressing "management" part of discovery: [Improve app telemetry](https://github.com/department-of-veterans-affairs/va.gov-team/issues/243)

**Comment by rianfowler** [comment]
Epic addressing "isolation" part of discovery: [Improve vets-website code isolation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/257)
