### ISSUE TITLE
[Tech Debt] 526: How Are Veterans Able to Enter Future Dates for Military History (non-BDD)

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10405]
## Issue Description
Somehow we are getting submissions for 526 that are actually BDD claims - should not be possible.

## Acceptance Criteria
- [ ] Find out how we allow for a date in the future - story fix if necessary but may be OBE by BDD
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
After digging into this, I believe the core issue is simply that we aren't validating the date entered at all. We show plenty of messages and warnings, but the user isn't blocked from continuing in any way. I will post some screenshots to illustrate the situation.

**Comment by ndsprinkle** [comment]
![image](https://user-images.githubusercontent.com/53942725/85877679-88c01d00-b7a5-11ea-9da8-8d9c276261ce.png)

Entering a date in the future (any amount of days in the future) shows no messaging of any kind. Hitting continue does not cause info to appear, it simply goes the next page. However, if you hit continue and then go back, you will see an appropriate message:

![image](https://user-images.githubusercontent.com/53942725/85877830-c2912380-b7a5-11ea-916b-68a118bb2f6b.png)

Despite this message, you are still able to continue the form without any validation preventing you from doing so. The only other way to make this message appear is to hit "add another service period". As stated previously, this message appears even if the date entered is 90 to 180 days from now. This is correct for now, but once BDD is live we will need to link users to the BDD form.

Hitting continue takes the user to this page:
![image](https://user-images.githubusercontent.com/53942725/85878107-34696d00-b7a6-11ea-8847-19e9f9312831.png)

Here, we do say something about BDD, but offer no link to the form, which again should be added once the form is live in production. Just like before, even though we tell the user that their date looks funky, we still let them continue through the form. This question isn't even required, users can skip answering yes or no and just go on with the form with a future date.

Answering yes and hitting continue or just hitting continue takes the user to this page:
![image](https://user-images.githubusercontent.com/53942725/85878468-bce80d80-b7a6-11ea-815f-3ef279148d42.png)

Here we do finally say "You can't file" but still let the user continue through the form. This spot should definitely be preventing the user from continuing. This is the message we show if the date entered is 90 to 180 days in the future:
![image](https://user-images.githubusercontent.com/53942725/85878594-f4ef5080-b7a6-11ea-93c1-8551450ce034.png)

As with the previous image, we still let the user continue through the form even though we directly say they can't file the 526 form. In the future, this message should be updated to direct users to the BDD form.

**Comment by ndsprinkle** [comment]
I think that this messaging:
![image](https://user-images.githubusercontent.com/53942725/85880164-8f509380-b7a9-11ea-87ee-7b7d268a4c04.png)

should just be removed as the main reason it isn't showing up is because the military date is still in "edit" mode and there probably isn't an easy way to get that to show up. Plus, the messaging on the next page should be more than enough to deal with the situation of a future date. The "Filing a claim before discharge" page should be the only one and should **require** the user to enter yes or no. Entering no takes the user back to the military history page, as it does now, and answering yes displays an alert box explaining the situation and does not allow the user to continue. This alert box could display multiple messages depending on the end date entered.

**Comment by ndsprinkle** [comment]
Ticket created #10703
