### ISSUE TITLE
Fix wrong application info on spina bifida page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#1040]
## What happened?
On this page https://www.va.gov/disability/eligibility/special-claims/birth-defects/ 
Under “How do I get these benefits for my child” - we link ppl to the 526EZ how to file page. That's not how ppl should apply for a spina bifida claim, which has a totally separate -- and not online -- app process currently. 

See screenshot. 

## Action
@AnneHurley 
Replace the text link "Find out how to file a claim for disability compensation" [https://www.va.gov/disability/how-to-file-claim/] with the below content - verified by SME, Misty Sweet: 

**By mail**

File your spina bifida claim by mail using an Application for Benefits for Certain Children with Disabilities Born of Vietnam and Certain Korea Service Veterans (VA Form 21-0304). 

Download VA Form 21-0304 (PDF) [https://www.vba.va.gov/pubs/forms/vba-21-0304-are.pdf]
 
Print the form, fill it out, and send it to this address:
 
VA Regional Office Veterans Service Center (339/21) 
Box 25126 
Denver, CO 80225 
 
**In person** 
Bring your application to a VA regional benefit office near you.
 
Find a VA regional benefit office near you [ https://www.va.gov/find-locations/?facilityType=benefits ]

**With the help of a trained professional** 
You can work with a trained professional called an accredited representative to get help filing a claim for disability compensation. 

Get help filing your claim [ https://www.va.gov/disability/get-help-filing-claim/ ]

If you have a power of attorney and need to update their information, please call Veterans Benefits Assistance at 800-827-1000, Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. 
 
![image](https://user-images.githubusercontent.com/43381063/63181089-7c175800-c01d-11e9-9371-662a871a58eb.png)

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** ( https://github.com/department-of-veterans-affairs/va.gov-team/issues/1020 `)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

P;lease have @peggygannon review once it's ready for deployment, preferably today or Monday latest.

**Comment by AnneHurley** [comment]
[Spina Bifida application info update]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/3510410/Spina.Bifida.application.update.-.v1.0.docx)

@peggygannon @jenniferlee-dsva Ready for your review - there was just one small thing at the bottom I found confusing... talking about "if you have power of attorney and 'their' information has changed..." it wasn't immediately clear if the 'they' is the disabled person or the Veteran. I assumed the former so suggested a small edit to clarify. But because this came from Misty and it's a rush, if leaving it as-is works for you both, I'm fine with that.

**Comment by jenniferlee-dsva** [comment]
@AnneHurley - your edit makes sense. @peggygannon I wonder if we can come up with something that means the same as Anne's edit but not "disabled person's..." -- Not sure why, it's not hitting me right.  Or 'the person you're filing the claim for' or ...?   Not as important as updating this today though.

**Comment by peggygannon** [comment]
this is live. Closing. Will check that this update is migrated into drupal during Disability UAT.
