### ISSUE TITLE
[Orientation] Refactor Orientation to be More Product-Driven

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#10406]
Focus on how teams will be successful in every practice area.

### High Level User Story/ies
As a VFS team, I want Orientation to teach me everything I need to be successful developing on VA.gov so that I can get to development quickly and get through the collaboration cycle easily. 

As VSP, I want orientation to have more of a focus on success and what teams need to do to be successful in my practice area so that I don't have to do much hand holding and support throughout the development process. 

### Problem Statement 
Right now, we give a lot of good information in Orientation. We talk about the different practice areas in break out meetings. We give a general overview in our inital meeting. But we still answer a lot of questions about our practice areas throughout the development cycle. We think if our content is more focused on how teams will be successful and the processes they need to follow, they will be able to get through the development cycle without relying on us so heavily. 

### Hypothesis or Bet
**We think** that if we shift the focus of orientation to the team's first project and how to be successful in all our practice areas, **then** we will spend less time doing support. 

**We think** that if we shift the focus of orientation to the team's first project and how to be successful in all our practice areas, **then** VFS teams won't be surprised by anything throughout the development cycle and the will be able to get their products launched faster. 

### OKR
O1: Teams have efficient experiences using the platform to build impactful products for Veterans, where their expectations are exceeded.

### Success metrics 
Increase in positive feedback from teams on the value of the platform quarter over quarter				
Net reduction in time it takes to perform VSP review (collaboration cycle) across 5 practice areas				

### We will know we're done when...
The general onboarding is very focues on collaboration cyce
Every breakout meeting is focused on guidelines and process for that practice area
There is a new suite of ppt templates to use. 

### Artifacts
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))

### Communication
Product support
Will work with other teams that do breakout meetings during orientation

**Comment by shiragoodman** [comment]
closing this as it is similar to #13709 (which is in progress).
