### ISSUE TITLE
[Call Center] Missing Gender Turns out Not to be Missing

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10400]
## Issue Description
Even when ID.me does contain the gender, some veterans are still not able to submit.  This ticket is to figure out if there is anything else we can do to allow them to submit.  Some ideas include giving them a direct link to the SSOe beta that is out there.

## Acceptance Criteria
- [ ] Our veteran can submit his claim

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
This is the issue they're facing. http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/116861/events/e03b48e06b74481d800f42663229dee7/

**Comment by annaswims** [comment]
same issue as https://github.com/department-of-veterans-affairs/va.gov-team/issues/8908

**Comment by annaswims** [comment]
It seems to be resolved.  I haven't seen any errors since our last deploy
If we wait a few more hours and don't see any here we should email our veteran.
 http://sentry.vfs.va.gov/vets-gov/platform-api-production/?query=UnprocessableEntity.
