### ISSUE TITLE
Consider a content refresh

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#10408]
from 6/16 stand up discussion on whether we should move forward with some changes to question content:

- Hold off until we get more research
- When we do, include the following items in our discussion:
    - Timing (e.g. 3 days vs. 24 hours vs. 14 days)
    - Travel (outside the US?)
    - Repetition (sore throat multiple times?)
    - Solve for chronic conditions or prefer wide net that might unnecessarily catch folks with chronic conditions?

**Comment by DanielleThierryUSDSVA** [comment]
Noting that we've addressed these 2 items from the list above:

- Travel (outside the US?)
- Repetition (sore throat multiple times?)
