### ISSUE TITLE
Find Return Payment Endpoint for Future FE Use

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10404]
## Goals
The payment history calls did not have return payments in our first examination and we need to establish them.

## Tasks
- [x] Collaborate with Linda Ciston via VA.gov email to establish those endpoints

## Acceptance Criteria
- [x] Share those endpoints with team

### Next Steps
- update BGS gem
- create an endpoint in rails API

**Comment by digitaldrk** [comment]
UPDATE: In an email thread, it was brought up that evss was using a different service than we're trying to use. BGS webservice doc indicates that the service being used by evss is/was deprecated. (being cryptic for security reasons)

**Comment by digitaldrk** [comment]
UPDATE: BGS responded with a service that EVSS uses that was marked deprecated in documentation. We have ran the call and were able to get both payments and return payments. 

HOWEVER

The header we use for auth is not working for the call. We have encountered this issue before, @kathleencrawford has requested the header we're using to be added for that service.

**Comment by digitaldrk** [comment]
There seems to be some sort of layering of services on BGS's side that needs unraveling.

*My understanding* is that a deprecated service(s) are mapping to their middleware framework and they're un aware of what middleware element is involved. They are digging around to find out that information. Once they have it, they will 'whitelist' va.gov and we will make calls to the deprecated service.

**Comment by jason-gcio** [comment]
Are we able to share what content is in this call for Jim to spec out what the data will be displayed as?  Or does the whitelist need to happen first?
