### ISSUE TITLE
[Discovery] Use Drupal Spec Tool info to perform transformation automatically

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#10417]
## High Level Overview
The current transformer process  involves quite a bit of manual definition of schemas and transformation files. Look at automating the process by generating some of these files automatically.

## Description
The CMS team uses the [Drupal Spec Tool](https://github.com/acquia/drupal-spec-tool). This tool provides information about the different bundles and the fields in each bundle in the "fields" tab of [a google sheet](https://docs.google.com/spreadsheets/d/1vL8rqLqcEVfESnJJK_GWQ7nf3BPe4SSevYYblisBTOI/edit#gid=943298572).

## Steps
To simplify the process focus on a single node file and a single bundle and run the process end-to-end.
1. Manually export the "fields" tab into a CSV file.
 Compared to the current schemas this file misses information about references. Create a reference file for the specific bundle you are testing with
1. Read the CSV into memory and the new file  you created in the previous step and fetch the referenced data. This is similar to the validation step in the current transformer.
1. Transform the file based on field types. For each type you need to create a transformation function. Note that you **don't need** to create functions for all data types. Just do those needed for the specific bundle.
1. Use the existing approach and feed the output of the transformation to the liquid template and generate the HTML file.

**Comment by drorva** [comment]
cc: @rianfowler @gunsch

**Comment by drorva** [comment]
So based on the data from the Drupal Spec Tool sheets it looks like there are 25 different data types that we will need to support:
```
'Entity reference',
'Entity reference revisions',
'Boolean',
'Text (plain)',
'Meta tags',
'Text (formatted, long)',
'Text (plain, long)',
'Date',
'List (text)',
'Link',
'Entity label',
'Address',
'Date range',
'List (integer)',
'File',
'Email',
'Telephone number',
'Number (integer)',
'Table Field',
'Computed (text, long)',
'Markup',
'Image',
'Video Embed',
'Text (formatted)',
'Social Media Links Field ' 
```

**Comment by cvalarida** [comment]
This is great! Like we discussed in Slack an on our call, I think the next step for this discovery is mapping each of these to a schema that matches the data found in the CMS export. It might look like:

**Entity reference**
```js
{
  type: 'array',
  items: {
    type: ['object', 'null'],
    properties: {
      target_type: { type: 'string' },
      target_uuid: { type: 'string' },
    },
  },
  minItems: 1
}
```
(I use JSON schema just because I'm familiar with it.)

**Comment by drorva** [comment]
@cvalarida
I generated the following schema from the export of the [a google sheet](https://docs.google.com/spreadsheets/d/1vL8rqLqcEVfESnJJK_GWQ7nf3BPe4SSevYYblisBTOI/edit#gid=943298572).

* Both bundles and fields have a bunch of info that we don't need. I figured it won't hurt for now, but we can later clean that up.
* I didn't test this too much, so while I think it's correct, I won't guarantee it.

The structure is for easy access:
* All bundles object
  * bundle_machine_name: bundle_content
    * Array of fields (inside each bundle)

This should be a temporary schema while we wait for the graphQL one.

[bundles.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4823592/bundles.zip)

**Comment by drorva** [comment]
[transform.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4844258/transform.zip)

Focusing on the page https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

The transform.zip has 4 files in it:
1. coronafaq.json -- has the node info for the above page from the generated graphQL at vets-website/.cache/localhost/drupal/pages.json. This is a sample of the output we need to generate for a specific node.
2. node.fda9b503-6548-46b5-985b-22aef50f063a.json -- this is the node info from the tar file that we need to convert into
3. pageScheman.json -- (yes typo) this is the schema for the "page" bundle generated from the google sheets. 
4. index.js -- loads the node, loads the schema and generates a stub of the desired output.

This is very rough, hand crafted, and needs to be generalized by using the field transformers. Specifically, the references need to handles.

But once we do the above,  it looks like we can drop and replace the graphQL output and just use that pipeline as is.

**Comment by drorva** [comment]
We're not doing this.
