### ISSUE TITLE
Some VBA Facilities Missing Service Listings

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#10416]
## What happened?
Service Listing information is missing from some VBA Facilities (e.g. https://www.va.gov/find-locations/facility/vba_313f)

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/539083c2-6bd5-490c-8cce-54634e2635db)

## Specs:
- Device: ALL
- Browser: ALL
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
If a facility has services associated with them, they should show up on the front end
Need to validate for all sub-types
![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/fe1d433f-f407-4806-8681-ea35d595517c)

## Acceptance Criteria
- [ ] Unit tests pass
- [ ] When a veteran views a VA health facility detail page, services are displayed. 
- [ ] When a veteran views a VA benefit facility detail page, services are displayed. 
- [ ] When a veteran views a VA Vet Center detail page, services are displayed. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Not parsing the services info from v1 transition
