### ISSUE TITLE
Form Details - Decide front-end approach for Form Detail pages

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#10414]
The Form Details work on the backend is now underway - form data is being pulled into Drupal, which means that soon we'll need to begin steps for implementing the frontend of the form detail pages. 

We have two options for this -

## Lighthouse API (dynamic approach)
Once the Lighthouse API has the complete form data via Drupal, we could leverage the Lighthouse API for form detail pages.  This means that the form detail pages would be built as a single React app, and when a user lands on `/FormDetail/:formNumber` (not the actual URL), the frontend would just get that data directly out of the Lighthouse API.

Pros
- May be easier to build as a standard React app
- "Feels right" to keep form data centralized to Lighthouse when accessed from the browser

Cons
- In Drupal, when you update a form's data, the updates would only be visible on the website once a Lighthouse migration runs instead of the usual content deployment.
    - This is an assumption dependent on Lighthouse's strategy for integrating in Drupal. They may instead _not_ use a local database and use a Redis cache with an expiry instead. In the case of the latter, updates may automatically come through to the browser without a content deployment after X time has passed. We should talk about this during our next cross-sync.
- Blocked until Lighthouse has the Drupal data integrated
- _Could_ run into the issue with Lighthouse rate-limiting API calls. We'd have to make sure we never reach that limit.
- _Could_ run into API downtime

## Front-end templates (static approach)
This would be to follow the standard approach we use when pulling data out of Drupal and into the frontend. It means that for the +400 forms in Drupal (originating from the Forms DB), we would generate a static HTML page for each one.

Pros
- Follows the standard content deployment for getting updated form details out the door
- Static HTML doesn't have any concern of downtime
- Actionable as soon as the form detail pages are set up in Drupal

Cons
- The data flow is a little hard to understand - we'd be using Lighthouse to query forms, but static HTML pages for the form detail pages
- Some unknowns involving GraphQL/transformers/templates

**Comment by kevwalsh** [comment]
The "Front-end templates (static approach)", with 400+ published VA Forms nodes, would probably push the graphql query some current limitations. It sounds like some additional RAM (or CPU?) might temporarily rectify that problem, but there is risk there. It's the same barrier being faced by other product teams, such as VAMC upgrade who want to soft-launch new VAMC sites. @swirtSJW can speak to this limit more intelligently than i.

**Comment by ncksllvn** [comment]
Ah okay @kevwalsh - so we're blocked until transformers are implemented?

Just curious, but it wouldn't make any difference if we just chunked out the single GraphQL query into separate requests, would it?

**Comment by kevwalsh** [comment]
@ncksllvn i've been wondering about that for months... I'm not sure about how that fits into the content release architecture, but if you see an approach, there are others who might be interested! Especially if the transformers looks like it's months away.

**Comment by jenniferlee-dsva** [comment]
RE ^ 

> The "Front-end templates (static approach)", with 400+ published VA Forms nodes, would probably push the graphql query some current limitations. It sounds like some additional RAM (or CPU?) might temporarily rectify that problem, but there is risk there.

We can (possibly?) mitigate some of this by first launching with the 30-40 top forms/detail landing pages. @kevwalsh @kelsonic @ncksllvn (fysa @stephorkandatx @swirtSJW )

**Comment by kevwalsh** [comment]
@jenniferlee-dsva interesting idea!

@swirtSJW would be the best judge of risk in that approach.

**Comment by jenniferlee-dsva** [comment]
I'd like to understand the tech pros/cons of these 2 options better to be able to weigh in. Let's find a time to discuss this on a call. @ncksllvn @kevwalsh @stephorkandatx @swirtSJW @ Andrew Ficht (Andrew doesn't seem to come up as attable). 

I like the Pros of the static FE approach, and have real concerns about the Cons outlined for the Lighthouse FE approach above.

**Comment by jenniferlee-dsva** [comment]
Hey all - as promised, a decision. Let's go with the static CMS approach. 

After additional consultations, I think the pros of the Lighthouse approach ultimately doesn't outweigh the cons, and doesn't give us that much more value for publishing the form detail pages. Rendering static html via Lighthouse also sounds like there could be performance issues especially if the user has slow service or is on a phone, which wouldn't be an issue with the static approach. 

@ncksllvn @kelsonic @kevwalsh @swirtSJW @stephorkandatx

**Comment by jenniferlee-dsva** [comment]
I'm closing this ticket, as the FE approach has been determined. Will create another ticket for the actual FE work. Per biweekly sync with Lighthouse and Drupal, we'll start this work after CMS preview work (PW) and completing forms search mvp 1.0 (Lighthouse API data call + PW FE ).
