### ISSUE TITLE
Hide Military History section for non-Vets

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#10422]
With Profile v1, if a user is not a Vet (if their `user.profile.veteranStatus.servedInMilitary` is falsey), we totally hide the Military Info section and do not call `GET service_history`

We should do the same with Profile 2.0. Instead we call `GET service_history`, get a 403, and show the user a `We can’t access your military information` alert.

![Screen Shot 2020-06-18 at 7.11.10 AM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/d416f8f8-eefc-4942-b8dd-c8cf662b11da)
> non-Vets should not see this screen

Instead we should:

- remove the Military Info item from the sidenav
- redirect users from the `profile/military-information` route to `profile/personal-information`
- not call ``GET service_history` at all

**Comment by mshea0606** [comment]
great job @sanlouise !
