### ISSUE TITLE
Come up with content for Load testing/Privacy and security intro

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1042]
Just come up with content for load testing in this ticket

**Comment by peterhill-oddball** [comment]
Current load testing documentation: https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest

**Comment by peterhill-oddball** [comment]
I've checked out the Devops repo, and I'm working on executing the load test against staging as they currently are.

**Comment by peterhill-oddball** [comment]
Working with some FE engineers to resolve my issues with getting the load tests up and running.

Created a Load Testing / Privacy / Security presentation here -- https://docs.google.com/presentation/d/11GWnu5r2qg8P12uglVY6q3P5t3rzGWoC170n0irTNl0/edit?usp=sharing

**Comment by brandonrapp** [comment]
We can help with this for sure. Do you have specifics of what you want to
cover here? Or is it more high level? I assume this is for onboarding?

**Comment by brandonrapp** [comment]
What is our timeline for this? I just want to make sure that we can align
this work with our other priorities.

**Comment by peterhill-oddball** [comment]
A first pass at Load Testing slides is up here -- https://docs.google.com/presentation/d/11GWnu5r2qg8P12uglVY6q3P5t3rzGWoC170n0irTNl0/edit?usp=sharing

**Comment by brandonrapp** [comment]
Thanks @peterhill-oddball - We are already starting on this work, but the work will definitely bleed into Sprint 8.

**Comment by peterhill-oddball** [comment]
@kfrz I'm not sure if you're the appropriate person to review this, but you know quite a bit about load testing as it is implemented.  If you're not the appropriate person then perhaps you could point me to the right person.  At any rate, is there any chance that you have a few minutes to review the slides on load testing that I've created in the presentation here -- https://docs.google.com/presentation/d/11GWnu5r2qg8P12uglVY6q3P5t3rzGWoC170n0irTNl0/edit?usp=sharing

Note that the intended audience is devs or QA personnel being onboarded to the platform.  This introduction session is intended to point them to existing resources and encourage them to incorporate load testing into their SDLC.

**Comment by brandonrapp** [comment]
The Privacy and Security slides have been added! We wanted to keep these fairly high level as there is A LOT of detail documentation already in place to help answer more granular questions. We wanted to create some talking points so that we can better understand what each new team's security and privacy needs are going to be based on their type of work. Depending if they are using PII or other factors will greatly determine where the security\privacy discussion should go.
