### ISSUE TITLE
[BUG] Add "incomplete" COVID screener result for debugging

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#10420]
In order to diagnose the blank Event Action we are getting for some COVID screener results:

![image](https://user-images.githubusercontent.com/62304138/85029910-d48e1900-b14a-11ea-84c2-71247dc428b4.png)

...please add "incomplete" to our event action lookup table in GTM.

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventAction:COVID%20Screening%20Tool%20-%20Result%20Displayed%20-/

**Comment by jonwehausen** [comment]
@bsmartin-ep 

### **Screenshot of last 30 minutes of covid screener events**
![image](https://user-images.githubusercontent.com/48527022/85036490-330ac580-b152-11ea-816e-c548db4fad94.png)

### **Observation**
- No incomplete events
- Seeing DL values flow through

### Suggestions / Options
- Let's try to convert back to a regex table with .* logic
- Write a small JS to scrape for the display text as a secondary logic to DL check
- Use what's displayed as last resort send logic

**Comment by jonwehausen** [comment]
### QA 

### Test Notes 
- Simulated the receiving of a `undefined` `screening-tool-result` variable and as a secondary attempt to clean the event taxonomy, look at the result text on the page

Description of Interaction | DL Screenshot | Tag Screenshot | Test Status
------------ | ------------- | ------------- | -------------
Intentionally executed a fake undefined dataLayer push | ![image](https://user-images.githubusercontent.com/48527022/85333564-cd973b80-b4a7-11ea-85a5-1ab00750d747.png) | ![image](https://user-images.githubusercontent.com/48527022/85333782-2ff03c00-b4a8-11ea-9eda-40d636d50a79.png) | ✔️ **PASS**
Full "Pass" path | http://c2n.me/484oqZK | ![image](https://user-images.githubusercontent.com/48527022/85334043-9d9c6800-b4a8-11ea-99d7-832b64d16bf7.png) | ✔️ **PASS**
Full "More screening needed" | https://clip2net.com/s/484ozO8 | ![image](https://user-images.githubusercontent.com/48527022/85333836-48605680-b4a8-11ea-9900-d9721f32fee8.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
Closing per [post mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2020-06-30-mobile-user-site-caching-ga-events.md).
