### ISSUE TITLE
Define & create plan for handling errors returned from CCE API

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10424]
We need to understand the errors that are returned from CCE API as part of the CC eligibility check. 

VAOS need to handle these errors in a user-friendly way. 

### Acceptance Criteria:
- [ ] Get a comprehensive set of these errors (or determination explanations) and what they look like in JSON

Note from Kam: There are certain cases where we might want UI to reflect. For example, with respect to the timestamps: If a veteran has updated their VA Profile recently but E&E does not reflect the change yet, this might be an opportunity to show the user a message telling them to try again in X hours when E&E has been updated. That's only one example. Based on this list of errors there might be other things to consider and other questions that might come up.

Additionally, a decision tree / flow diagram of sorts might be helpful in understanding various edge cases. This isn't too complicated, but a flow diagram could help to visualize any gaps in our understanding. Perhaps it's something Lighthouse already has available that they can share.

**Comment by saneshark** [comment]
I found this [here](https://github.com/department-of-veterans-affairs/health-apis-community-care-eligibility/blob/master/README.md) while researching: 

> For this MVP, access standards are based only on drive-times, without appointment wait times. The last two criteria, best medical interest and quality standards, are subjective criteria outside the scope of this API. Because the subjective criteria are not included, this API's eligibility decisions are not final. A user-facing message based on the result of this API should stress that the patient is probably eligible or probably not eligible, and that no decision is final until they have consulted VA staff and scheduled their appointment.

> The response includes the overall eligibility decision and the individual details (patient address, eligibility codes, nearby facilities, etc.) that were used to compute it.

**Comment by saneshark** [comment]
The README goes on to show an example where an API response is received and there is no supplementary explanation as to why the user is not eligible. 

The expectation might in fact be that we will not receive such an explanation and we're expected to provide a more generic response that "You are PROBABLY not eligible."

**Comment by lenaecb** [comment]
Closing ticket.

Regardless of error returned, we will redirect Veteran to VA request (as we do now). 

If errors do return, we'll catch them in our sentry report and can follow up with Lighthouse.
