### ISSUE TITLE
[COGNITION]: Disability Calculator - Remove error message on valid input blur

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1043]
## Description

Our quick test flagged the error message as not being removed when users enter valid data into the Disability Rating field. This is more of an accessibility experience than compliance issue, but will be worth doing for user consistency. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a user, I want the error message to be removed when I have entered a valid number in the Disability Rating field.

## Environment

* MacOS
* Chrome

## WCAG or Vendor Guidance (optional)

* [Labels or Instructions: Understanding SC 3.3.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html)

## Screenshots or Trace Logs

![Screen Shot 2019-08-16 at 11 10 41 AM](https://user-images.githubusercontent.com/934879/63181835-b16c7780-c016-11e9-96fc-e56e24e4f6db.png)

**Comment by Karak888** [comment]
These have been captured moving to close
