### ISSUE TITLE
Add analytics to homepage banner content

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#10436]
# Description

Ticket created in reference to [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9223#issuecomment-646147420):

> Today Analytics and Insights noticed as part of this work the event previously in place for tracking the coronavirus banner clicks has been removed.
> 
> The event push previously in place for each of the embedded links was
> 
> 'event': 'nav-warning-alert-box-content-link-click', 
> 'alertBoxHeading': 'Coronavirus'
> Is it possible we could request this event be reinstated? Thank you all very much for your time.

## Acceptance Criteria

- [ ] Add event tracking for covid banner links.

**Comment by kelsonic** [comment]
Upon further review it looks like this may be a CMS task since the `content` is coming from Drupal?

![image](https://user-images.githubusercontent.com/12773166/85047837-9e9f6380-b14f-11ea-9d5c-39fe565a650e.png)

CC @ncksllvn @stephorkandatx

**Comment by kelsonic** [comment]
Sorry dumb question lol homepage banner content comes from https://github.com/department-of-veterans-affairs/vagov-content/blob/master/fragments/home/banner.yml#L27 so it will need to be updated there

**Comment by jenniferlee-dsva** [comment]
Can answer @kelsonic's Q above: 
The homepage coronavirus banner is not published from Drupal. 

However the coronavirus banners that appear appear on Drupal nodes (benefit pages) are published via Drupal. (The homepage isn't a node, and Drupal banner component can only be place on nodes.)
