### ISSUE TITLE
Create cloned 2018 and 2019 rates pages for all benefit rates pages

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#10435]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/f01947174c4ad0b19acd9c05969a866075551f90/products/public-websites/legacy-rates)

## High Level User Story/ies
As a user, I need the ability to view 2018 and 2019 rates for all the benefit pages so I can have reference to historical information.

Create by cloning in Drupal and filling in info for 2018 historic rates tables pages. 
Each page will be its own separate ticket.
Pages will be batched, rolled out together by benefit section.
Legacy pages need to be redirected. 

## Definition of done
Cloned 2018 rates pages exist for all benefit rates pages

## Sections to be filled in as they are completed
Section | Completed? | Scheduled Release to Production (coordinated with stakeholders)
-- | -- | --
Careers and Employment - 1 | no | xx/xx/2020
Disability - 6 | yes | August 2020
Education and Training | no | xx/xx/2020
Health Care | no | xx/xx/2020
Housing | no | xx/xx/2020
Life Insurance | no | xx/xx/2020
Pension | no | xx/xx/2020

The pages are:

Benefit | Rates | URL
-- | -- | --
Careers  and Employment | Subsistence   Allowance Rates | https://www.benefits.va.gov/vocrehab/subsistence_allowance_rates.asp
Disability | 2020   Veterans disability compensation rates | https://www.va.gov/disability/compensation-rates/veteran-rates/
Disability | 2020   VA special monthly compensation rates | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
Disability | 2020   special benefit allowances rates | https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
Disability | 2020   birth defect compensation rates | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
Disability | 2020   VA DIC rates for spouses and dependents | https://www.va.gov/disability/survivor-dic-rates/
Disability | 2020   VA DIC rates for parents | https://www.va.gov/disability/parent-dic-rates/
Education and training | Survivors’   and Dependents’ Educational Assistance | https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/
Education and training | Post-9/11   GI Bill and other VA education benefit rates | https://www.va.gov/education/benefit-rates/
Health Care | VA   health care copay rates | https://www.va.gov/health-care/copay-rates/
Housing | VA   funding fee and loan closing costs | https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/
Housing | VA   home loan limits | https://www.va.gov/housing-assistance/home-loans/loan-limits/
Life Insurance | Servicemembers’   Group Life Insurance (SGLI) | https://www.va.gov/life-insurance/options-eligibility/sgli/
Life Insurance | Family   Servicemembers’ Group Life Insurance (FSGLI) | https://www.va.gov/life-insurance/options-eligibility/fsgli/
Life Insurance | Veterans’   Group Life Insurance (VGLI) | https://www.va.gov/life-insurance/options-eligibility/vgli/
Pension | VA   pension rates for Veterans | https://www.va.gov/pension/veterans-pension-rates/
Pension | VA   Survivors Pension benefit rates | https://www.va.gov/pension/survivors-pension-rates/

Top section - 2018 rates
1. Careers: Legacy page needs content strategy & rewriting to publish on VA.gov first. Danielle and Beth
2. Disability main rates, 2018 spreadsheet request of Elana as dry run. Request sent 6/15 by Anne; followup by Beth 7/3 #10893 - Spreadsheet received from SME Elana and CVS process executed by Selina. GTG
3. Special Monthly Compensation 2018 historic rates: #10450 - Validated
4. Birth Defect Compensation 2018 historic rates: #10544 - Validated
5. Special Allowances rates: #10635 - Beth verified with stakeholders the correct effective dates. GTG
6. DIC - surviving spouse and dependents: #10717 NOTE: Also need 2019 rates Status: Blocked until Beth can find out the post-1993 surviving child rate, and where it lives on legacy pages. *NOTE* We're changing "All rates in $US dollars" to a parenthetical (in U.S. $) that sits in the actual table header above the dollar figures.
7. DIC - surviving parents #10718 NOTE: Also need 2019 rates
8. Education - Survivors and dependents: Danielle and Beth. Part of Education rewrite.
9. Education - Post 9/11 GI Bill and other rates.  Danielle and Beth;
---Post-9/11 GI Bill (Chapter 33) and the Fry Scholarship
---Montgomery GI Bill - Active Duty (MGIB-AD/Chapter 30)
---Montgomery GI Bill - Selected Reserve (MGIB-SR/Chapter 1606)
---Reserve Educational Assistance Program (REAP/Chapter 1607) [HOLD ON REAP per Danielle]
---Survivors' and Dependents' Educational Assistance Program (DEA/Chapter 35)
10. Health care - copay rates. Beth.
11. Housing - Funding Fee and Loan Closing Costs. Beth.
12. Housing - Home loan guaranty limits. Beth
13. Life Insurance - SGLI Beth
14. Life insurance - FSGLI Beth
15. Life insurance - VGLI Beth
16. Pension - Veterans: #10779 
17. Pension - Survivors: #10785 

2019 rates
18. 2019 historic rates DIC - spouses and dependents - Anne to create new ticket
19. 2019 historic rates DIC - parents - Anne to create new ticket 
---
Note: Redirects handled by @mnorthuis @lunascoop FYSA @jenniferlee-dsva

**Comment by DanielleThierryUSDSVA** [comment]
Re: subsistence allowance rates page: Intention was to rewrite/redirect this, but we had open questions for SMEs first. These questions were communicated to SMEs not long before contract transition, so likely got paused/lost in transition period.

@bethpotts Let's sync on this with @mnorthuis before bringing back to SMEs.

[Careers - voc rehab - legacy content rewriting](https://app.zenhub.com/files/133843125/3af65739-3565-4c6a-8121-dc9ce000833e/download)

**Comment by AnneHurley** [comment]
@bethpottsVADEPO  - Let's chat about this. There are historic VGLI rates, but they are all before 2014. Since the rest of this ticket focuses just on the 2nd to last year of historic rates -- 2019 and 2018 only -- I wonder if we need to capture these older rates.

**Comment by MickinSahni** [comment]
@RLHecht @lunascoop to review tickets within and groom

**Comment by FranECross** [comment]
All tickets in this old epic are completed; closing
