### ISSUE TITLE
Design feedback for Staging Review [Facility Locator] 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#10442]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**
- The circles of the pins are not consistent depending on the letter. The I is vertically narrow oval and the M is horizontally narrow. Can we have a standard circle size so the pins are consistently shaped? 
![Screen Shot 2020-06-18 at 1.47.08 PM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/a2b32d01-1309-4b60-9764-706eea3e2b34)
- When selecting a pin from the map, it highlights the corresponding item in the list in the left sidebar, and looks like this: 
![Screen Shot 2020-06-18 at 1.35.49 PM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/96e319f7-7425-486d-841b-8bbb5a772d09)

The blue inset box shadow isn’t a style I’ve seen elsewhere on VA.gov. Is it possible to switch that active state’s inset box shadow to the 2px yellow border that we use to indicate focus states? Something like this instead:
![Screen Shot 2020-06-18 at 1.36.28 PM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/ce511b25-b451-47e7-89fb-a32b88bebd38)

**Try:**

-  It looks like the font-weight of the letters in the pins doesn't match the original design spec. If possible, increase the font-weight to match the design spec to increase readability

**Consider:**
- No "consider" feedback at this time

**Definition of Done:**
- [ ] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by mmiddaugh** [comment]
Thank you @CrystabelReiter. I have documented your findings in the following issues, which will be groomed and prioritized as appropriate during our next grooming. 

- Inconsistent pin design [#10525](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10525) 
- Hover state design [#10526](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10526)
- Font size [#10527](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10527)

**Comment by CrystabelReiter** [comment]
Thank you! @mmiddaugh I'll close now
