### ISSUE TITLE
[COGNITION]: Telephone - 911 SHOULD NOT have an extra "One" in the aria-label

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#10446]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Our [Telephone component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/telephone/) has several examples of correct formatting with `aria-labels that read out numbers individually. This is a **great** thing.

The `911` aria-label will read out "One. Nine. One. One." This is potentially confusing, because 911 does not require users to dial "1" first. The accessibility specialists are in agreement we should update this aria-label. Code snippet below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] 911 link reads out as "Nine. One. One" for screen readers

## Environment

* https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/telephone/

## Possible Fixes (optional)

```diff
# Telephone.jsx#L32
const LABELS = {
- 911: '1. 9 1 1.',
+ 911: '9 1 1.',
};
```

## WCAG or Vendor Guidance (optional)

* [Language of Parts: Understanding SC 3.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-other-lang-id.html)

**Comment by jenniferlee-dsva** [comment]
@1Copenut - Hello - just wanted to ask a qq:  The content team was advised before the design system launched that when phone numbers are hyperlinked, that the linkref should include the +1. I don't remember if that was due to accessibility or due to enabling mobile phones to dial the number by clicking the link. 

Does the above global aria label guidance wrt the 1- prefix mean that all hyperlinked phone numbers on content pages should now omit the 1 prefix in the linkref? 

@RLHecht @DanielleThierryUSDSVA fysa ^

**Comment by 1Copenut** [comment]
@jenniferlee-dsva The guidance above is only for the `aria-label` that is read out to screen readers when users focus or swipe to the `911` link on the page. This should not affect or change how the `href` is structured.

**Comment by jenniferlee-dsva** [comment]
Thank you so much for the explanation @1Copenut!

**Comment by 1Copenut** [comment]
Issue moved to [department-of-veterans-affairs/vets-design-system-documentation #218](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/218) via [**ZenHub**](https://www.zenhub.com/)
