### ISSUE TITLE
Access for Thomas Dugan

### ISSUE THREAD

**Issue by duganth-va** [department-of-veterans-affairs/va.gov-team#10451]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia LeeCecilia
- Please provide your name.
   > Tom Dugan
- Please Provide your email.
   > thomas.dugan@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I work on Leeroy Jenkles with the Lighthouse project. I work for Ad Hoc.

- Requesting SSH key authorization?
   > YES 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2uC/0wKXPweku1Yj81mGWbH8odZ/JXrwmHus3IPj3ALKhwmN4veIdh8T2CKzIuns45VwKtG8V2JsFLr2ryVnNne5qMdmqJBHo7q+TCS7Fd49AfPbJ5z5dZFxpeO8B3OahMh/0DNLZTQLcrvVGTjBU+hbyqRTTLgWGqnXti9bp9RLsdKwLus6CrG0SJB7Ld1NK5TUrJCIsHidjm8F8WpfdDjv9bSum5AIR1YtDBZIdBn+FqKRbfGib+0sgM3R66MiiBWmzizERht8r5n17mG4mX0sfLM0TUxaX969jSZYyst0fMjSfXk9QR1UWRNYYeMnyf7mREC7AO1Hu2bR2vu9EXFR6yvju8BC1xcS3H5ua/LS7skHRBCH+X7MmBCm9XaxvEmZnHx3TGxLipG/0iWEEkjw51Ijq65xuzKlrb0v8n1EMFvhyLs0LKjTNF+Z/hB+eMnq3UunK1rl4VpkchNn81P+w2WJZcFlk3ektxxCAHQMAcauLwm6KegPG2u8L9vfE7dMLEptw3I4c6gpJ5MMUhCwf+PGH6S6t6ZVWiH7HY/ecjND3eL9JSqvzv3WoAlQqkFpnx4PLau2ZaUjb6gMiYrGxkHM0THJWX57g4Q8OzJiANRSPme12ADJurAVcP1bjsYKBubLkX+2cMS24cJzalh2r5IRQV5D5bvDkgDwjmw== thomas.dugan@adhocteam.us
```

- Grant AWS Console access?
  >  Yes
  - I am on the DevOps team and will need console access for managing Lighthouse components that still reside in DSVA

**Comment by duganth-va** [comment]
@department-of-veterans-affairs/vsp-operations please review.

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Cecilia LeeCecilia
Name: Tom Dugan

**Comment by tskinn** [comment]
@duganth-va you should have socks access now. Reach out in slack if you have any issues connecting.

**Comment by golavarr-va** [comment]
Hello, I just wanted to follow up on this request. Tom is a member of the Lighthouse DevOps team, and he's awaiting AWS Console access to be granted. Is there any update regarding this request? Is there something missing that perhaps we can help facilitate? Thank you!

**Comment by golavarr-va** [comment]
Following up on this thread. Any updates on the request to obtain AWS access? @tskinn @Jeff-Hayter ? Thank you for your help!

**Comment by Jeff-Hayter** [comment]
@tskinn @jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
Requesting additional approval in group message with leadership for the level of permissions this user will need.

**Comment by drorva** [comment]
Approved.

**Comment by jbritt1** [comment]
User created and first-time login credentials provided. Closing.
