### ISSUE TITLE
Sign out of inbound SSOe session is broken

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#10452]
After a user has auto logged in using an existing inbound SSOe session, the VA.gov sign out button no longer works because SSOe appears to deny the signout request.

**Comment by marriej** [comment]
![Screen Shot 2020-06-18 at 3.46.15 PM.png](https://images.zenhubusercontent.com/5e5d21ccbf668393ce8d133e/e8331078-f44f-4d99-92d0-3fc3e906f980)
