### ISSUE TITLE
VAMC Situation Updates: Editorial Experience & Front End experience

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#10455]
## Issue Description
The formatting for the Situation Update on the VAMC is wonky. This might be an Epic?
We should think through how these are used and re-align the design for a (arguably) better experience.
Right now there are no headers, all an editor can do is bold
The front end spacing is wonky.

 ![pittsburgh-health-care_operating-status_.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/e0dc2dfd-c9cd-4dfe-aeab-38a2c16abf5d)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This issue is resolved. Headings are available in situation updates. 

![situation-update](https://user-images.githubusercontent.com/55411834/105222909-59457900-5b18-11eb-9b68-57f8d0a7e27c.png)
