### ISSUE TITLE
External Service Integration Improvements

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#10458]
### High Level User Story/ies
*What is the pathway you’re creating for VFS or VSP teams through this initiative?*

### Problem Statement 
The service design team identified that one of the big pain points when developing on the platform was "external service integration".  The purpose of this epic is to track work that comes out of the user research initiative completed in Q2 of 2020 that can be actionable for the BE Tools team.

How might we improve the biggest pain point of VFS engineers when it comes to integrating with external services through documentation and other tools.

### Hypothesis or Bet
Identifying where the major gaps are and documenting a path forward to improve the experience for VFS engineers.

### OKR
O1: Teams have efficient experiences using the platform to build impactful products for Veterans, where their expectations are exceeded.
KR: Increase in positive feedback from teams on the value of the platform quarter over quarter

### Success metrics 
TBD - will know more when the research is done.

### We will know we're done when...
TBD - will know more when the research is done.

### Artifacts
[Research Materials](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/tools/backend/Product/external-services-research)

### Communication
- Team that owns this super epic: BE Tools
- Teams contributing to this super epic: NA

**Comment by holdenhinkle** [comment]
Review the [Research Materials](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/tools/backend/Product/external-services-research).

Is this still the biggest pain point of VFS engineers when it comes to integrating with external services through documentation and other tools? This research was done almost 2.5 years ago.

If so, research what external service integration improvements could be made.
