### ISSUE TITLE
Coronavirus FAQs & Alerts: Week of 6.15.20

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10473]
# User story

As a Veteran, I want to get my top questions about the coronavirus and VA answered as quickly as possible, and have easy access to other questions if I need them.

# Details

## Known updates that need to be made this week:
- New question on VGLI application period extension

**Process steps to completion:**
- [x] Write content for FAQs and alert (Danielle)
- [x] Add in Drupal (Danielle)
- [x] Coordinate SME review/approval (Danielle
- [x] Submit FAQ to JTF for approval (Lauren)
- [x] JTF approval received
- [x] Validate in preview and set to publish (Randi)
- [x] Validate on live site (Randi, Danielle)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. We received JTF approval on the new VGLI extension FAQ today. No changes. 

Could you validate one more time in preview and publish ahead of today's deploy?

We can also publish those pages with the related alert:
- node 764 (Life insurance options and eligibility)
- node 767 (SGLI)
- node 769 (VGLI)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA The FAQs page is now published along with those three pages with the alert. I also republished the site-wide alert with those three nodes removed.

**Comment by RLHecht** [comment]
These changes have been validated on the live site. Closing ticket. FYSA @stephorkandatx @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA The FAQ page is now published and those three nodes were removed from the related alert. Closing ticket. FYSA @stephorkandatx
