### ISSUE TITLE
CONSIDER: Hardening of System Health Services

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#10475]
## Issue Description
the system health services offering bullets seem to be somewhat standardized (or possibly standardized) by the VAMC-Upgrade team.
Consider whether or not to make these managed at the national level, some form of "default" or what have you.

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/3add8762-0e6b-4de6-990e-c14d5f1a167c)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
This work is complete
