### ISSUE TITLE
[SCREENREADER]: 526 v2 - Need aria-labels for some edit / remove buttons

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1047]
## Issue
Some of the UI controls for editing and removing sections of content don't have aria-labels. This leaves screen reader users to find headings or other related text when determining what action they are taking. Screenshots attached below.

Adding content editor because these will probably need reviewed for plain language.

## Acceptance Criteria
As a screen reader user, I'd like to understanding what I am editing or removing by hearing a descriptive `aria-label` like "Edit Air Force service period" or "Remove buddy/lay statement".

## Affected Pages
* https://staging.va.gov/disability-benefits/apply/form-526-all-claims/review-veteran-details/military-service-history
* https://staging.va.gov/disability-benefits/apply/form-526-all-claims/supporting-evidence/private-medical-records
* https://staging.va.gov/disability-benefits/apply/form-526-all-claims/supporting-evidence/additional-evidence
* https://staging.va.gov/disability-benefits/apply/form-526-all-claims/review-and-submit
* https://staging.va.gov/disability-benefits/apply/form-526-all-claims/contact-information

## Environment
* MacOS Mojave
* Chrome latest
* https://staging.va.gov/disability-benefits/apply/form-526-all-claims/contact-information
* Test user account

---
![screen shot 2019-02-06 at 12 12 29 pm](https://user-images.githubusercontent.com/934879/52364193-3f352d80-2a0a-11e9-9229-fb45fcdea0de.png)

---
![screen shot 2019-02-06 at 12 19 45 pm](https://user-images.githubusercontent.com/934879/52364205-44927800-2a0a-11e9-816b-8d564a3b75b2.png)

---
![screen shot 2019-02-06 at 12 22 17 pm](https://user-images.githubusercontent.com/934879/52364209-4825ff00-2a0a-11e9-93bc-d100dff72c83.png)

---
![screen shot 2019-02-06 at 12 23 40 pm](https://user-images.githubusercontent.com/934879/52364211-4b20ef80-2a0a-11e9-861f-292a759330bb.png)

**Comment by alexpappasoddball** [comment]
@YanaRoy & @AZSchneider I believe this one is for your team.  If you agree move to your backlog and remove "triage" and "triage-incident"
