### ISSUE TITLE
CF: Update FTC settlement caution flag plain language mappings

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10474]
As a developer, I need to update the Caution Flag content for any issues found post launch so that the user has a good experience when using the Comparison Tool

## Assumptions:
1. This story will remain open until the work is delivered to production, due to the nature of the mapping updates.

## Acceptance Criteria:
1. The Caution Flag “The Federal Trade Commission (FTC) has reached a settlement with this school.” received in the settlement.csv file uploaded to GIDS is displayed in the following way on the Comparison Tool:
    - CT Caution Flag Title – VA style: Settlement reached with Federal Trade Commission (FTC)
    - CT Caution Flag description – VA style: The FTC has reached a settlement with this school. 
2. The Caution Flag “The Federal Trade Commission (FTC) has reached a settlement with this school” received in the settlement.csv file uploaded to GIDS is displayed in the following way on the Comparison Tool:
    - CT Caution Flag Title – VA style: Settlement reached with Federal Trade Commission (FTC)
    - CT Caution Flag description – VA style: The FTC has reached a settlement with this school. 

## Supporting Artifacts:
1. [Settlement_06042020.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/4736108/Settlement_06042020.txt) - CSV renamed to text to upload into github.
2. Schools with flag as reported by EDU:
    - American Intercontinental University =  “School engaged in misleading, deceptive, or erroneous practices” // Should be: “The Federal Trade Commission (FTC) has reached a settlement with this school.”
    - Colorado Technical University = School engaged in misleading, deceptive, or erroneous practices. School has settled its case with the state Attorney General // Should be: “The Federal Trade Commission (FTC) has reached a settlement with this school”.
    - University of Phoenix = “School engaged in misleading, deceptive, or erroneous practices” // Should be: “The Federal Trade Commission (FTC) has reached a settlement with this school.”

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/673

**Comment by delli-gatti-michael** [comment]
Tested by the following testrail test case
https://dsvavsp.testrail.io/index.php?/cases/view/736

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

#### Test (Fake) Data
- SOUTHERN UTAH UNIVERSITY
  - https://staging.va.gov/gi-bill-comparison-tool/profile/11000144
- BIG BEND COMMUNITY COLLEGE
  - https://staging.va.gov/gi-bill-comparison-tool/profile/14802147

#### Real Data
- AMERICAN INTERCONTINENTAL UNIVERSITY-ATLANTA
  - https://staging.va.gov/gi-bill-comparison-tool/profile/21801111
- COLORADO TECHNICAL UNIVERSITY-AURORA
  - https://staging.va.gov/gi-bill-comparison-tool/profile/21809206
- UNIVERSITY OF PHOENIX-ARLINGTON
  - https://staging.va.gov/gi-bill-comparison-tool/profile/21923146

**Comment by ccruzgra** [comment]
@delli-gatti-michael UX reviewed and the only discrepancy is the missing period at the end of the warning description. This should be: The FTC has reached a settlement with this school.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/674

**Comment by JenLJ** [comment]
@delli-gatti-michael UX has reviewed and this looks good!

**Comment by zurbergram** [comment]
@dneel-bah This is production environment
