### ISSUE TITLE
[Development] BDD: Work Through All EVSS Issues for XSD and Back-End Business Logic

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10479]
## Issue Description
During testing with EVSS, even if the XSD is validating, there are conditional situations that are captured further downstream.  An example of this has been documented by @annaswims. 

In terms of another explanation of the above, Anna captured it well when she said:

> The XSD isn’t a full picture.  Attributes that are required in some scenarios are marked as “optional” when they really mean “not required all the time”.

The goal of this story is to continue to work this until we no longer have edge cases that error for us when submitting BDD (or maybe 526 in general).

```
----------------------------------------
Jobs:
SubmitForm526AllClaim
  status: non_retryable_error
  error: EVSS::ErrorMiddleware::EVSSError
    message: [{"key"=>"form526.standardClaim.NotNull", "severity"=>"ERROR", "text"=>"may not be null"}, {"key"=>"form526.veteran.currentlyVAEmployee.NotNull", "severity"=>"ERROR", "text"=>"may not be null"}]
  updated at: 2020-06-18 23:15:02 UTC
----------------------------------------
Form JSON:
{
  "serviceInformation": {
    "servicePeriods": [
      {
        "serviceBranch": "Air Force",
        "dateRange": {
          "from": "1999-01-01",
          "to": "2020-11-01"
        }
      }
    ],
    "separationLocation": {
      "separationLocationCode": "98283",
      "separationLocationName": "AF Academy"
    }
  },
  "phoneAndEmail": {
    "primaryPhone": "2342342345",
    "emailAddress": "test@test.com"
  },
  "mailingAddress": {
    "country": "USA",
    "addressLine1": "1",
    "addressLine2": "2",
    "addressLine3": "3",
    "city": "indianapolis",
    "state": "IN",
    "zipCode": "46240"
  },
  "privacyAgreementAccepted": true,
  "newPrimaryDisabilities": [
    {
      "cause": "NEW",
      "primaryDescription": "asdf",
      "condition": "hair loss",
      "classificationCode": "3070"
    }
  ],
  "attachments": [
    {
      "name": "Screen Shot 2020-06-10 at 2.50.14 PM.png",
      "confirmationCode": "7b3a7eff-a701-4ff3-9ebf-b5afa72583d5",
      "attachmentId": "L451"
    }
  ],
  "veteran": "FILTERED"
}
```

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
once we've added `currentlyVAEmployee` and `standardClaim` we can submit the claim to evss and get  `[{"key"=>"form526.submit.establishClaim.serviceError", "severity"=>"FATAL", "text"=>"Error calling external service to establish the claim during Submit"}]` 
That sounds to me like we've plausibly submitted enough data to EVSS but that they're having issues.

**Comment by annaswims** [comment]
note to self for later:

This is the code used to get around CSRF for postman
```JavaScript
console.log('Pre-request Script from Request start');

// We don't need to do anything if it's GET or X-CSRF-Token header is explicitly presented
if (pm.request.method !== 'GET' && !(pm.request.headers.has('X-CSRF-Token'))) {

  var csrfRequest = pm.request.clone();
  csrfRequest.method = 'GET';
  if (pm.request.method === 'POST') {
     // just need a get url
    csrfRequest.url = 'https://staging-api.va.gov/v0/user';
  }

  csrfRequest.upsertHeader({
    key: 'X-CSRF-Token',
    value: 'fetch'
  });

  pm.sendRequest(csrfRequest, function(err, res) {
    console.log('pm.sendRequest start');
    if (err) {
      console.log(err);
    } else {
      var csrfToken = res.headers.get('X-CSRF-Token');
      if (csrfToken) {
        console.log('csrfToken fetched:' + csrfToken);
        pm.request.headers.upsert({
          key: 'X-CSRF-Token',
          value: csrfToken
        });
      } else {
        console.log('No csrf token fetched');
      }
    }
    console.log('pm.sendRequest end');
  });
}

console.log('Pre-request Script from Request end');
```

**Comment by annaswims** [comment]
[this conversation](https://dsva.slack.com/archives/C8R3JS8BU/p1586795125022600) makes me think that the error "Error calling external service to establish the claim during Submit" is not BDD -related.

**Comment by SarahJaine** [comment]
- `Error calling external service to establish the claim during Submit` per old conversation with Slack, it sounds like we can't have multiple open BDD claims 
- Per Luke, users should be able to est mult bdd claims
- Per, Anna maybe this is simply a problem with test users 228, 229 and 226

**Comment by SarahJaine** [comment]
Wrote two news tickets to capture work discovered in course of this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/10876 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/10861. Closing work on this ticket on @annaswims 's behalf. Thanks for all your work on this Anna!  🎉
