### ISSUE TITLE
Staging Review - Altoona-health-care - VAMC-Upgrade website

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10484]
## Story
Review Altoona-health-care website in Devshop environment.  

## Links and resources
[Altoona Devshop Site](http://altoonahealthcare.web.demo.ci.cms.va.gov/altoona-health-care/)
[Altoona Initial Review Docs](https://drive.google.com/drive/folders/1Juw7qXdDtzXHm-yPPwaJNUaYZkCFD9B-)

## Artifacts
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)
[Release Plan-TBD](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers)
* Site Access in Devshop - http://altoonahealthcare.web.demo.ci.cms.va.gov/altoona-health-care/
* VSA-QA results - \[[see Comment below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10484#issuecomment-654363792)]

**Comment by peggygannon** [comment]
@SgardnerPMP Content feedback for Altoona is here: 
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10539

Please note, in the interested of time, i didn't do a content review on the individual clinic pages under Altoona. I focused my review on the higher-level pages.  I'm not sure if I captured all these high-level pages, so please let me know if there is a page you want to review/take a look that I didn't cover in my review.  Thx!

**Comment by SgardnerPMP** [comment]
Thank you Peggy,

I will review ASAP.
[image: GovernmentCIO] <http://www.governmentcio.com/>

Stan Gardner | PMP, SSGB
Sr. Product Manager
| *mobile* (775) 772-1409
| *office* (775) 772-1409
| *e.* sgardner@governmentcio.com
*Government*CIO
website <https://www.governmentcio.com/> | media
<https://governmentciomedia.com/> | services
<https://www.governmentcio.com/services> | jobs
<https://careers-governmentcio.icims.com/> | map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>
[image: Twitter] <https://twitter.com/GovernmentCIO> [image: Facebook]
<https://www.facebook.com/GovernmentCIOMedia> [image: LinkedIn]
<https://www.linkedin.com/company/governmentcio> [image: YouTube]
<https://www.youtube.com/user/GovernmentCIO/videos> [image: Instagram]
<https://www.instagram.com/gciotalent>
*Confidentiality Note: *This email may contain confidential and/or private
information.
If you received this email in error please delete and notify sender.

**Comment by mnorthuis** [comment]
@SgardnerPMP  I have been unable to get into the Altoona site to review. Let me know if there's another way to get to it or when I should retry.

**Comment by SgardnerPMP** [comment]
http://altoonahealthcare.web.demo.ci.cms.va.gov/altoona-health-care/     has been rebuilt in DevShop.  Thank you.

**Comment by mnorthuis** [comment]
IA feedback

1. There are a number of breadcrumb issues and left nav issues in regards to interactions that I did not capture.  They both seem to be working rather inconsistently across the site.  

2. All of the child pages that should be under "Health services" have the incorrect URLs and breadcrumbs. They are all up one level too high and should be nested under /health-services and the left nav and breadcrumb should also indicate that placement.  There are 9 pages that should be nested under health services as documented here: https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9

3. Johnstown clinic is shown as a main location and other nearby locations. If its a main location, it should be listed 2nd in the left nav and not listed under other.

4. The "Work with us" option under "About VA Altoona" section in the left nav is not linking correctly, it seems to be linking to whatever page you are currently on.  Could not access the work with us page or section to validate. 

5. The 4 child pages under " About us" - leadership, mission, history and performance - have incorrect URLs and breadcrumbs

6. When on a News release or story detail page, the breadcrumb is inaccurate - it does not let you click on one level up and is missing the current page.

7. For leadership detail pages, the URL is incorrect.  They should be `/altoona-health-care/about-us/leadership/[name]

8. The campus map under James E. Van Zandt VAMC is labeled as "Altoona" campus map. This is confusing as the entire site is "Altoona" but the map is specific to the one VAMC in Altoona.  Labeling should be more distinct.

9. "Jobs and careers" and "Volunteer or donate" pages have incorrect URLs, they should be children of the Work with us section - i.e. /work-with-us/volunteer-or-donate/

**Comment by tlei123** [comment]
@pjhill , no Test Plan/Cases or Reports needed for VAMC's content.  As we've already discussed, there's no separate copy or design documentation against which to QA against, nor do I see any need for such docs -- the Team already has their own internal content-review process.

As far as Left-Nav (LN) QA goes...

Through Jennifer Strickland's screenshare this morning, I'm confirming here that LNs are successfully propagated into the level-1 & -2 pages that we spot-checked, and:
- spot-checked links are working;
- spot-checked parent-links \[those top-level items that have children] have their respective sections expanded & highlighted after navigation.

No React widgets were found in spot-checked pages' content.

Going forward, I agree with Jennifer that we'd probably provide better value to the Product Team by focusing our validations on the underlying CMS-template(s), as it's not feasible for us to thoroughly validate every single content page for every facility.
