### ISSUE TITLE
CMS / Drupal Intregation 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#10487]
Research, document, and decide if/where /how to integrate with a CMS or the current Drupal instance.

**Comment by mdewey** [comment]
Key questions: 

- [ ] How does this work
- [ ] How static is the information? 
- [ ] who owns and manages the data?

**Comment by mdewey** [comment]
**User Stories** 
- As a team, we might need to have static content for our users
- Content should be editable by a non-developer

**Questions to Answer**
 - [ ] How does this work in regards to the build system?
 - [ ] How static is the information?
 - [ ] who owns and manages the data?
 - [ ] How often does the CMS data get rebuilt 
 
**Definition of Done**
- [ ] All the questions answered

**Prototype**
- [ ] None for this ticket

**Comment by abuckley3385** [comment]
@mdewey  Option is to finish what research you are currently doing and then put on hold so its documented in the tech feasibility. We can move your acceptance criteria /questions to a new issue that is form builder/or a service strategy to host our own questions outside code. (lets discuss so I can clarify.) 

Lacey was able to meet with the Drupal PO and their static content is not meant for forms builders.

**Comment by mdewey** [comment]
**Acceptance Criteria**:

Added to the [tech doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/engineering#cms-integration)
