### ISSUE TITLE
Staging Review - 'Coatesville-health-care' VAMC-upgrade website

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10483]
## Story
Review Coatesville-health-care website in Devshop environment.  

## Links and resources
[Coatesville Devshop Site](http://coatesvillehealthcare.web.demo.ci.cms.va.gov/coatesville-health-care/)
[Coatesville Initial Review Docs](https://drive.google.com/drive/folders/1Juw7qXdDtzXHm-yPPwaJNUaYZkCFD9B-)

## Artifacts
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)
[Release Plan-TBD](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers)
* Site Access in Devshop -http://coatesvillehealthcare.web.demo.ci.cms.va.gov/coatesville-health-care/
* VSA-QA results - \[[see Comment below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10483#issuecomment-654365897)]

**Comment by mnorthuis** [comment]
IA feedback

1. There are a number of breadcrumb issues similar to what is documented in #10482

2. There are 2 "Health services" options in the left nav, one links to the main Coatesville health system page

3. All of the child pages that should be under "Health services" have the incorrect URLs and breadcrumbs. They are all up one level too high and should be nested under /health-services and the left nav and breadcrumb should also indicated that placement.  There are 9 pages that should be nested under health services as documented here: https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9

4. The left nav is not showing all of the locations - the main location of Coatseville VAMC is not showing as well as other locations.  The VAMC is also listed under "other nearby va locations" (so its listed twice). 

5. All of the options in the "About VA Coatesville" section in the left nav are not linking correctly, they seem to be linking to whatever page you are currently on. 

6. Missing the 4 required child pages under " About us" - leadership, mission, history and performance - as documented here: https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9 

5. Both the /jobs-careers and /volunteer-or-donate pages have the wrong URLs, breadcrumbs and are not properly showing in the left nav.  That pages should be children of "Work with us"

6. There is a "programs" option in the left nav but I was unable to get to the page

7. There is a "research" option in the left nav but I was unable to get to the page

8. There are 2 "Contact us" options in the left nav

9. The left nav seems to have a number of issues in incorrectly linking, not showing your current spot, and not showing children.

**Comment by peggygannon** [comment]
@SgardnerPMP Content feedback for Coastesville is captured here: 
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10538

**Comment by tlei123** [comment]
**QA feedback**

@pjhill , no Test Plan/Cases or Reports needed for VAMC's content.  As we've already discussed, there's no separate copy or design documentation against which to QA against, nor do I see any need for such docs -- the Team already has their own internal content-review process.

As far as Left-Nav (LN) QA goes...

Through Jennifer Strickland's screenshare this morning, I'm confirming here that LNs are successfully propagated into the level-1 & -2 pages that we spot-checked, and:
- spot-checked links are working;
- spot-checked parent-links \[those top-level items that have children] have their respective sections expanded & highlighted after navigation.

No React widgets were found in spot-checked pages' content.

Going forward, I agree with Jennifer that we'd probably provide better value to the Product Team by focusing our validations on the underlying CMS-template(s), as it's not feasible for us to thoroughly validate every single content page for every facility.
