### ISSUE TITLE
[Bug] 526: Explore What we Can Do About Multiple EDIPI Issues

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10481]
## Issue Description
Looks like there are cases, such as marriage, where there is a new EDIPI created and this is creating issues for a lot of veterans.  I met with Paul Shute and will add his notes to this issue.  Perhaps we can do something about it but we are being asked to at least investigate root cause (as much as possible).

Sounds like DOD does not want to reuse the existing EDIPI, but not sure this is always the case.  Could also happen when they change branch of service or retire.  Does not seem like we will have the possibility to fix this on the DOD side, but we may be able to work with MVI.

Email from Paul:

> So for your reference over a decade ago the govt made a decision that a DoD EDIPI would be the best person identity to replace SSN for VA and DoD.  PROBLEM:
> 
> 1. DoD only cares about a person as long as they are paying them or paying on behalf of them
> If you are a retiree they care about you for life – your EDIPI is fixed
> If you are a not a retiree they only carry your EDIPI for your period of service
> If you change branches or become a spouse you are issued a new EDIPI
> DoD sends the most recent EDIPI to MVI not necessarily the military EDIPI
> 2. VA used to have a 7-8 digit VA Identity under BIRLS – this was a record identity not a person identity it was a Lifetime evidentiary record identity based on all claims filed on behalf of a veteran’s military service– which then was changed to SSN based on a Govt decision in the mid 70’s.
> Since it is not a person identifier it cannot be used to identify a specific person for lifetime VA records purposes – which means VA should look at not using the SSN – instead transitioning to creating the person identity UUID upon inception to DoD from the VA side not using the DoD temporary EDIPI .
> VBA has a corporate identifier for internal use that is used to identify person relationships within VBA business systems – but is not a UUID so would not be efficient to use for a person identifier outside VBA.

Wondering if a lot of these MVI errors "record not found" are side effects of having multiple EDIPI.

![screen_shot_2020-06-20_at_12 24 38_pm](https://user-images.githubusercontent.com/53824125/85207867-1f459780-b2e9-11ea-9ddf-1b037714d1d3.png)

## Acceptance Criteria
- [ ] We understand why this EDIPI issue is causing errors (root cause established)
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
This may be fixed by some of the SSOe work.  Need some more details about whether this is creating errors/error messages on VA.gov.  Luke to contact Paul.

**Comment by annaswims** [comment]
0.5% of people who logged into VA.gov in the last two weeks were not found in MVI.  
I'd think that the most common reason that they are not found in MVI is that they're not a veteran or have not had a recent interaction with the VA.  


Since https://github.com/department-of-veterans-affairs/vets-api/pull/4628 was deployed on August 6, we've seen that the vast majority of "not found" errors in MVI are users that are looked up in MVI using attributes, which means that they're logged in with id.me.   ![Screen Shot 2020-08-17 at 11.01.24 AM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/85cac73d-98e3-4b69-adb2-0eee37e92af3)

only 13% of the "not found in MVI" errors are users looked up by edipi.

**Comment by annaswims** [comment]
SSOe is rolled out at 5% of all users, still.  [SSOe/Access VA](https://access.va.gov/) is implemented by the IAM team who also works on MVI. As users log in with SSOe, they should all have a record in MVI or get an error message telling them what to do.    I don't know if it's something we should spend our time on, if SSOe will gate users sooner.

**Comment by luke-gcio** [comment]
Anna made great progress during investigation phase but we may be tabling this as fixed by SSOe.

**Comment by edmangimelli** [comment]
@annaswims 
1) i think maybe we need to see if this is still a problem
2) maybe this should be part of a bigger conversation with the team in charge of login stuff.

maybe, in the meantime, we should be validating that our logged-in user has all of their ids present, but that seems like it's just a bandaid --still would like to get to the heart of this problem (or maybe just commit to keeping the login team up-to-date with these errors as we see them)

**Comment by annaswims** [comment]
I don't think that it should be the responsibility of our team to ensure that a user can log in and identity-verify and get a record from MVI. The VSP identity team should own that work.  Ideally, the'd own the work about getting a BIRLS/Participant id in MPI as well. 

BUT I do think that our team could probably use google analytics to see how many people would like to begin the form but can't, due to identity issues.

**Comment by edmangimelli** [comment]
is the action item:
>use google analytics to see how many people would like to begin the form but can't, due to identity issues.

and send that info to the VSP identity team?

**Comment by vhenry07** [comment]
Closing as this is an issue with the identify team.
