### ISSUE TITLE
Staging Review - 'Erie-health-care'  VAMC-upgrade website

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#10482]
## Story
Review Erie-health-care website in Devshop environment.  

## Links and resources
[Erie Devshop Site](http://eriehealthcare.web.demo.ci.cms.va.gov/erie-health-care/)
[Erie Initial Review Docs](https://drive.google.com/drive/folders/1Juw7qXdDtzXHm-yPPwaJNUaYZkCFD9B-)

## Artifacts
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/Project_Plan_Outline_2019.md)
[Release Plan-TBD](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers)
* Site Access in Devshop -http://eriehealthcare.web.demo.ci.cms.va.gov/erie-health-care/
* VSA-QA results - \[[see Comment below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10482#issuecomment-654367219)]

**Comment by peggygannon** [comment]
@SgardnerPMP hello, content feedback for Erie can be found here: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10537

Please note, in the interested of time, i didn't do a content review on the individual clinic pages under Erie. I focused my review on the higher-level pages. I'm not sure if I captured all these high-level pages, so please let me know if there is a page you want to review/take a look that I didn't cover in my review. Thx!

**Comment by mnorthuis** [comment]
IA feedback:

**The breadcrumb** 
In general, it seems the breadcrumb is not functioning right at all, but I don't know what requirements your team defined for the breadcrumb so I can't speak to what is correct or what is wrong, but here are a few examples...
- On the main page, the breadcrumb says "Home" but doesn't link anywhere
- On several pages, the "VA Erie health care" option is not clickable and should be; examples: 
  - http://eriehealthcare.web.demo.ci.cms.va.gov/erie-health-care/make-an-appointment
  - http://eriehealthcare.web.demo.ci.cms.va.gov/erie-health-care/about-us
- On the individual location pages, the "Location" option in the breadcrumb should take you back to the main locations page, but it is not clickable **and** the current page is not in the breadcrumb

**Additional feedback**
1. There are no child pages under About Us - It is my understanding that Mission, Leadership, History and Performance are required content pages
2. Under "Work with us" the child page for /jobs-careers is not in the left nav, and the required page for /volunteer-or-donate is not there
3. All of the pages under /health-services have the incorrect URLs and breadcrumbs.  They should all up one level too high and should be nested under /health-services
 - example: `/erie-health-care/mental-health-care` should be `/erie-health-care/health-services/mental-health-care`
  - the breadcrumb and left nav should then indicate the correct position/you are here based on this
4. Required page `/erie-health-care/billing-insurance` is missing

**Comment by tlei123** [comment]
**VSA-QA results**

@pjhill , no Test Plan/Cases or Reports needed for VAMC's content.  As we've already discussed, there's no separate copy or design documentation against which to QA against, nor do I see any need for such docs -- the Team already has their own internal content-review process.

As far as Left-Nav (LN) QA goes...

Through Jennifer Strickland's screenshare this morning, I'm confirming here that LNs are successfully propagated into the level-1 & -2 pages that we spot-checked, and:
- spot-checked links are working;
- spot-checked parent-links \[those top-level items that have children] have their respective sections expanded & highlighted after navigation.

No React widgets were found in spot-checked pages' content.

Going forward, I agree with Jennifer that we'd probably provide better value to the Product Team by focusing our validations on the underlying CMS-template(s), as it's not feasible for us to thoroughly validate every single content page for every facility.
