### ISSUE TITLE
School Ratings: Discovery Interviews - Findings & Recommendations

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10494]
Prioritize findings & Recommendations that emerged during synthesis

**Comment by ccruzgra** [comment]
https://boozallen.sharepoint.com/teams/benefitsintegrationplatform/education/_layouts/15/doc2.aspx?sourcedoc=%7B2B8CD172-E3E3-46FF-B75B-2B4B261D51EE%7D&file=UX-Backlog-Tracker.xlsx&action=default&mobileredirect=true

**Comment by ccruzgra** [comment]
@amyknox Recommendations are now in our backlog.
