### ISSUE TITLE
School Ratings: Interviews - Synthesize Interview Findings

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10493]
Review observations and identify themes.  
Determine findings & recommendations 
Consolidate relevant findings from other parties Identify 
Recommendations & Enhancements

**Comment by ccruzgra** [comment]
Synthesis mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1592854683402/d460598d3b5ebe141b777b52af0eee19477046a5v
