### ISSUE TITLE
[QA] Research online version of QA Manual Testing Matrix

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#1051]
## User Story
As a Design & Development team member, I want to easily view and update the QA Manual Testing Matrix online. 

## Goal
Create an online version of the Matrix to replace the [current Excel-spreadsheet version](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/QA/QA_Testing_Matrix_Template.xlsx) \[which must be downloaded, edited offline, and re-uploaded to GitHub\].

### Must-haves
- [x] Online-editable -- no downloading/uploading.
- [x] Online-usable by QA Engineer -- expandable to full-screen-width when conducting QA.
### Nice-to-haves
- [ ] Scalable -- has a template version for easy reuse.
- [ ] VA ownership & administration of any required account(s)
- [ ] Any required account(s) sharable with contractors

## Definition of Done
- [x] **Labeled with Team** - VSA Support
- [x] **Labeled with Practice Area** \[need a “qa” label in this repo\]
- [x] **Labeled with Type** - Discovery
- [ ] Research documented here.
- [ ] Enhancement issue created for actual implementation.

**Comment by tlei123** [comment]
Testing personal Microsoft OneDrive spreadsheet link here:
[QA Manual Testing Matrix (on OneDrive)](https://1drv.ms/x/s!AtFPwFnvF2TMaSlntY7hEl5OwPw)

**Comment by tlei123** [comment]
@lkoenigsberg @Samara-Strauss @Justin-Pickett @mojaray2k  @ncksllvn @erikphansen ,
Please try entering your **Last Name** \[next to your pre-filled First Name] into the [**OneDrive Test spreadsheet**](https://1drv.ms/x/s!AtFPwFnvF2TMbep0FLMLuHIwXwE) on my Microsoft OneDrive \[click the green **Edit in Browser** button in the toolbar once you’re there].

You should **not** have to either sign into your Microsoft account or even create one, but I want to make sure with this edit-test.

Thanks much in advance!

**Comment by Samara-Strauss** [comment]
Done! Worked for me. I had to be off of the VA network but otherwise it was fine.

**Comment by Justin-Pickett** [comment]
Done! Worked for me as well.

**Comment by tlei123** [comment]
### Research findings
[WIP -- I’d like to get more test results before finalizing this]

Microsoft OneDrive should meet both requirements of online-version Matrix:

- Excel spreadsheets are **online editable**\* by both VA & contractor agencies:
  - Does not require OneDrive account.
  - Does not require local MS Office software.
- Excel spreadsheets are expandable to full-screen and thus **usable by QA Engineer**.

\*@Samara-Strauss had to log out of VA network to access my shared sheet.  Would like more VA-user testing to discover further implementational issues.

### Implementational considerations
- Documents ownership/hosting should ideally be on VA-side.  Not a strict requirement -- contractors can online-host* just temporarily (only during testing).

*Contractors would, however, need to create a free MS OneDrive account.

**Comment by lkoenigsberg** [comment]
Tried from a non-VA mobile phone and can open the sheet but not able to edit (or more likely some sort of user error, not knowing how to edit).

**Comment by tlei123** [comment]
@lkoenigsberg @Samara-Strauss , considering the apparent VA-network technical barriers, I thinking we should just go with temporary contractor-side hosting of the online Matrices, attaching the actual Excel spreadsheets to the QA tickets once QA testing's complete.  I.e., the Matrices would only be online-editable during development & testing.

Although I think VA-side MS OneDrive hosting of these Matrices would be a good long-term solution, you'd know much better whether this is worth involving your IT resources to implement the necessary organizational- and team-accounts infrastructure for everyone.

Let me know what you think please!  Thanks much!

cc @Justin-Pickett

**Comment by lkoenigsberg** [comment]
I'm pretty sure that Office 365 is a system approved by the VA and it might include OneDrive but would probably then require dramatics around being on a VA network, with VA email, etc.

Sooo...for now I think it's smart to continue as we were.

**Comment by tlei123** [comment]
> I'm pretty sure that Office 365 is a system approved by the VA and it might include OneDrive but would probably then require dramatics around being on a VA network, with VA email, etc.
> 
> Sooo...for now I think it's smart to continue as we were.

Understood & thx, @lkoenigsberg !  Closing ticket.
