### ISSUE TITLE
[MDOT Bug]- Can't progress through form without a temporary address

### ISSUE THREAD

**Issue by mr0sari0** [department-of-veterans-affairs/va.gov-team#10514]
##BLOCKER

## What happened?
Expected to be able to go through the order process without a temporary address.  There is a schema error thrown if there is no temporary address. The error is `temporaryAddress: is not exactly one from [subschema 0],[subschema 1],[subschema 2],[subschema 3]`.

## Screenshots

![screenshot-localhost_3001-2020 06 22-11_25_48](https://user-images.githubusercontent.com/12755283/85305570-3b793e00-b47b-11ea-9c2a-c2437b1b49d7.png)

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction
- Test user 228 (Mark) or remove temporary address info from user 1 (Mark)

To see the error:

Go to `vets-website` and navigate to `SchemaForm.jsx`

Path: `/src/platform/forms-system/src/js/components/SchemaForm.jsx`

Find the following code block:

```
<Form
        safeRenderCompletion={safeRenderCompletion}
        FieldTemplate={useReviewMode ? ReviewFieldTemplate : FieldTemplate}
        formContext={this.state.formContext}
        liveValidate
        noHtml5Validate
        onError={this.onError}
        onBlur={this.onBlur}
        onChange={({ formData }) => onChange(formData)}
        onSubmit={onSubmit}
        schema={schema}
        uiSchema={uiSchema}
        validate={_.once(this.validate)}
        showErrorList={false}
        formData={data}
        widgets={useReviewMode ? reviewWidgets : widgets}
        fields={useReviewMode ? this.reviewFields : this.fields}
        transformErrors={this.transformErrors}
        name={addNameAttribute ? name : null}
      >
```
Change `showErrorList={false}` to `showErrorList`

## Desired behavior
You should be able to go through the order process if you don't have a temporary address

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mr0sari0** [comment]
Starting a slack conversation [here](https://dsva.slack.com/archives/CBU0KDSB1/p1592839987201000) to get more insight into this error.

**Comment by mr0sari0** [comment]
[This PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/441) should fix this issue.

**Comment by mr0sari0** [comment]
> [This PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/441) should fix this issue.

Making a new PR to update something that was missing from this PR.

**Comment by mr0sari0** [comment]
The solution implemented in the above PR did not work. Will regroup on what to try next.

**Comment by camerontesterman** [comment]
The user in staging that was formally Mark Webb seems to have had their name changed to "Colder Polarbear" so now we are getting a 404 in staging for this user.

**Comment by mr0sari0** [comment]
> The user in staging that was formally Mark Webb seems to have had their name changed to "Colder Polarbear" so now we are getting a 404 in staging for this user.

The error also happens on Greg, if you remove his temporary address and try to go to the next page.

**Comment by mr0sari0** [comment]
The PR [here](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/449) seemed to resolve this bug.
