### ISSUE TITLE
Original Claims: Deeper Analysis of MVI Add-Proxy Errors

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10524]
## Background info 
In order for a veteran to submit a form 526 to EVSS they need to be LOA3. VA.gov needs to have their EDIPI, SSN, participant_id (corp id) and  BIRLS ID. 

* VA.gov uses a call to action to prompt a user to log in and idienty-verify if they have not already
* If a user has an EDIPI and SSN but is missing a BIRLS or Participant id VA.gov makes a call to `V0::MPIUsersController#submit`
  * If a user has a participant_id  but no birls_id `V0::MPIUsersController#submit` raises ~~([apparently this should never happen](https://github.com/department-of-veterans-affairs/vets-api/pull/4010/files#r390738992), [but it does ](http://sentry.vfs.va.gov/organizations/vsp/issues/6165) )~~
  * If a user is missing both, or just a participant_id VA.gov makes a call to MPI add_proxy, which [often but not reliably succeeds](http://grafana.vfs.va.gov/d/000000062/mvi?viewPanel=16&orgId=1). 

in mid-2020 the VA.gov team opened up form526 for veterans who were filing for disability for the first time.  Prior to that, the va.gov form was only available to veterans who were filing for increase (and therefore had records in the other systems).
Staring in late 2020 the VA.gov team opened the form up to people who are active duty and 90-180 days from discharge.  It's much more likely that this is their first digital interaction with the VA. 
## Open questions
* What should va.gov or the user do when they have a participant_id  but no birls_id?  We're currently [linking them ](https://github.com/department-of-veterans-affairs/vets-website/pull/12839)to the VBA call center but they don't know how to handle the issue. 
* Why are [requests to MPI add_person failing](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&groupStatsPeriod=14d&project=3&query=transaction%3AV0%3A%3AMPIUsersController%23submit&statsPeriod=14d) and what can va.gov of the veteran to to get the necessary attributes to  allow completion of the form?
[Additional info](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10524#issuecomment-783722632)
* Is it up the the individual veteran to call and ask for their data to be fixed or might we be able to fix it in bulk (1-off or routinely)?
* How does the C&P team (Claims and Pension) team hande creating these identifiers and are there any significant issues with active duty service members who are pre-discharge?

## Why does it matter?
Without these identifiers a veteran can not begin/complete the form.
Everyone who fills out this form has a disability, many of which make completing the form more difficult. Successful completion/processing  of the form can have a major financial impact on the veteran.

**Comment by annaswims** [comment]
Sentry issue: http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/31727/
success rate: http://grafana.vfs.va.gov/d/000000062/mvi?orgId=1&from=now-24h&to=now

**Comment by luke-gcio** [comment]
Looking at this again for this sprint.

**Comment by annaswims** [comment]
Success rate seems to be improving...
![Screen Shot 2020-08-06 at 3.41.02 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/1875757f-999c-49f8-a019-c35e656f80ec)

**Comment by annaswims** [comment]
our code refers to it as `invalid request` but the status code actually means  "AE – failed to process the message due to data or service business rules"

**Comment by annaswims** [comment]
ok, here's what I think is happening.  A veteran logs in and we can find them in MVI with either their EDIPI or ICN.  But, they don't have a BIRLS id or Participant id.  So we call `mvi_add_person` but the data from the identity provider doesn't match the data in MVI, so  MVI responds with the status `AE`, (which we're calling `invalid_request`.

We're only calling `mvi_add_person` for veterans with an EDIPI and for users who log in with id.me the only place we can get EDIPI is MVI... so that means that these users are found in MVI.  But the `add_person` call could still fail if the attributes we got from the identity provider (given_names, last_name, birth_date, ssn gender) don't match what's in MVI. Since we likely have that data from MVI, would it be appropriate to use that data rather than the data from the identity provider???

🤔

**Comment by annaswims** [comment]
Ok, now we have the additional information
In the last week there were 111 events affecting 74 users.
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/197033/events/7576154/

we see this 53 times:
{:other=>[{:codeSystem=>"2.16.840.1.113883.5.1100", :code=>"INTERR", :displayName=>"Internal System Error"}]}
`2.16.840.1.113883.5.1100` is the HL7 code for  AcknowledgementDetailCode. Still don't know what that means. 


we see this 38 times:
{:other=>[{:codeSystem=>"2.16.840.1.113883.3.2017.11.6.1", :code=>"PNADD000001", :displayName=>"Inconsistent person ID specified"}]}

If we search for `2.16.840.1.113883.3.2017` on https://www.hl7.org/oid/ we see that `This is the root OID for the DoD Defense Manpower Data Center (DMDC). DMDC will be creating OIDs to represent person identifier, organization and system identifier, coding systems, and other entities. If information is needed regarding the DMDC OIDs, contact Daniel Vidosic at Daniel.Vidosic@osd.pentagon.mil`

There is an email thread with the subject `[EXTERNAL] Dev Test Records` starting on 4/23/2020 that is relevant to this issue.  Our team failed to respond to MVI on 5/11 .

2
 {:other=>[{:codeSystem=>"2.16.840.1.113883.5.4", :code=>"Key205",
1

{:other=>[{:codeSystem=>"2.16.840.1.113883.1.11.19639", :code=>"SY

**Comment by annaswims** [comment]
We were able to get some useful info, but logging more will be helpful https://github.com/department-of-veterans-affairs/vets-api/pull/4860/files

**Comment by annaswims** [comment]
Here are the relevant bits of the responses we see over 2 days and counts

14 ` "code"=>"INTERR",      "codeSystem"=>"2.16.840.1.113883.5.1100",        "displayName"=>"Internal System Error"}}, {"nodes"=>["ICN/VPID Does Not Exist"], "value"=>"text"}], "value"=>"acknowledgementDetail"}, {"nodes"=>[{"nodes"=>["ICN/VPID Does Not Exist"],`

14 `"code"=>"INTERR",      "codeSystem"=>"2.16.840.1.113883.5.1100",        "displayName"=>"Internal System Error"}}, {"nodes"=>["Internal System Error"], "value"=>"text"}], "value"=>"acknowledgementDetail"}, {"nodes"=>[{"nodes"=>["Internal System Error"],`

40 - "code"=>"PNADD000001", "codeSystem"=>"2.16.840.1.113883.3.2017.11.6.1", "displayName"=>"Inconsistent person ID specified"}}, {"nodes"=>["Unable to associate Id"], "value"=>"text"}], "value"=>"acknowledgementDetail"}, {"nodes"=>[{"nodes"=>["Unable to associate Id"],

**Comment by annaswims** [comment]
there's an email chain with the subject `EXTERNAL] Dev Test Records` that references `PNADD000001` but it sounds like it was also discussed in other channels that I was not a part of.  @luke-gcio do you know what the end result was?

**Comment by annaswims** [comment]
Additional issue - What about people who have a CORP id but not a BILRS id?
[Silvio said](https://github.com/department-of-veterans-affairs/vets-api/pull/4010/files#r390738992)
>  This is an extreme edge case (as it technically should never be possible to have a corp id but not a birls id) and we may want to log some user information so we can investigate these cases with upstream services.

 but we see it's affected 500 unique users in [sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/6165/?environment=staging&project=3&statsPeriod=14d)
https://dsva.slack.com/archives/C1VBAHWQL/p1557953628067900

**Comment by annaswims** [comment]
I revived an old email chain that was forwarded to me. Daniel Lopez answered some of Silvio's questions so we'll see if he might be able to help again.

**Comment by annaswims** [comment]
No response. Trying to find the correct people

**Comment by annaswims** [comment]
The error responses we've seen from MPI in the past two weeks are (with counts)
````
171 - {"code"=>"PNADD000001", "codeSystem"=>"2.16.840.1.113883.3.2017.11.6.1", "displayName"=>"Inconsistent person ID specified"}}, {"nodes"=>["Unable to associate Id"], "value"=>"text"}], "value"=>"acknowledgementDetail"}, {"nodes"=>[{"nodes"=>["Unable to associate Id"], "value"=>"text"}], "value"=>"acknowledgementDetail"}]
127 - {"code"=>"INTERR", "codeSystem"=>"2.16.840.1.113883.5.1100", "displayName"=>"Internal System Error"}}, {"nodes"=>["Internal System Error"], "value"=>"text"}], "value"=>"acknowledgementDetail"}, {"nodes"=>[{"nodes"=>["Internal System Error"], "value"=>"text"}], "value"=>"acknowledgementDetail"}], 
86 -  {"code"=>"INTERR", "codeSystem"=>"2.16.840.1.113883.5.1100", "displayName"=>"Internal System Error"}}, {"nodes"=>["ICN/VPID Does Not Exist"], "value"=>"text"}], "value"=>"acknowledgementDetail"}, {"nodes"=>[{"nodes"=>["ICN/VPID Does Not Exist"], "value"=>"text"}], "value"=>"acknowledgementDetail"}], 
 3- {"code"=>"INTERR", "codeSystem"=>"2.16.840.1.113883.5.1100", "displayName"=>"Internal System Error"}}, {"nodes"=>["MVI[S]:INVALID REQUEST"], "value"=>"text"}], "value"=>"acknowledgementDetail"}, {"nodes"=>[{"nodes"=>["MVI[S]:INVALID REQUEST"], "value"=>"text"}], "value"=>"acknowledgementDetail"}], 

````
