### ISSUE TITLE
Documentation for error override enhancement

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#10528]
Given that we created a custom, platform-wide enhancement to override the error component,
I want to document the functionality so that other teams can take advantage of it.

See: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10233

**Comment by LinnJS** [comment]
Appending here as it pertains to this work

![image.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/98871a2b-774a-46ac-be07-f3c316ff4386)

**Comment by LinnJS** [comment]
Conversation around details for error message:

https://dsva.slack.com/archives/C862Q82UQ/p1596556013086600
