### ISSUE TITLE
Access for Sandra Hallie

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#10522]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Sandra Hallie
- Please Provide your email.
   > shallie@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Authenticated Experience, frontend engineer, GovernmentCIO

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA76NMwCHZHw/zJu/9o7pR/mLn6Q/iFcozc1oFpBqyV/3HnjRYwOlkGjTFL2jLwn0ybHQh0GI7K3Uf7lIdrs0NuHV4qeR7e23vNmZSUpPk05Y/WPveW2e7/EoQemF1g6yG9kV4wVtEa/XZMXOFSTXK0jMIoAs7zn0XMFFFwB/F4qmx/aKPb7Ck4ScS1kUnwBBV9fuB1Jm1/1FQTiTjuqa2eHz1Wb28sCtlgx228NnXZx4T+a7qWXBKkqURDnwgG6NCQu6mWGmJlN/rLnS/q4Fbwk7uh9wMPFuyHPe5U/IwLUgprK2IbTRzO/Tv7tGzD9/qgBdILjYdMqc3ltXV+xTL sandra@sandras-mbp.lan
```

- Grant AWS Console access?
  > NO
  - Please give a brief description for why you are requesting AWS access.

**Comment by sanlouise** [comment]
@department-of-veterans-affairs/vsp-operations Created ticket to request SOCKS access, let me know if you need anything, thank you! 🙂

**Comment by tskinn** [comment]
@sanlouise you should be able to connect to the proxy. Reach out in slack if you have any issues.
