### ISSUE TITLE
Infra Recommit - Implementing new Logging Solution 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#10529]
### High Level User Story/ies
As a developer working on VA.gov, I want to easily access logs, so that I can see what is happening with my application.

### Problem Statement 
Right now logging is not a  great experience on VA.gov.  All the logs are within cloud watch logs in AWS which requires AWS consul access to view. That process can take months and even after getting access it is not a full logging experience. Another method that is being used is Sentry, which is not meant to be a logging tool. This leads to confusion and having logging all over the place and hard to access. It also has been identified as a top pain point for both VSP and VFS teams.

How might we create a  better logging experience on  VA.gov that can make logging easy, accessible, and scalable? 

### Hypothesis or Bet
Having better logging will improve the quality and velocity of all teams working on VA.gov. 

Having logging with Loki in Grafana will be an easy familiar place for developers. 

### OKR
O1: Teams have efficient experiences using the platform to build impactful products for Veterans, where their expectations are exceeded.

### Success metrics 
- Decrease in the amount of time it takes for a developer to access logs
- Number of users using Loki vs cloudwatch 
- Increase in positive sentiment around logging 
- Reduction in volume of “non-human-needed” support requests month over month
- Decrease in logging support related tasks

### We will know we're done when...
- All services are sending their logs to fluentD and Loki
- Developers have clear documentation on how to access and export their logs 

### Artifacts
- Link to ([Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/logging/product_outline.md))
- Link to Log by Service doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/logging/logsByService.md

### Communication
- Team that owns this super epic: VSP Operations
- Teams contributing to this super epic: Ops

**Comment by jhouse-solvd** [comment]
This ticket is now defunct. Migrated to: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13744
