### ISSUE TITLE
VSP content review: VAMC Erie (staging)

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#10537]
## User story

This ticket captures VSP content feedback on VAMC Erie 

Staging link:   Site Access in Devshop -http://eriehealthcare.web.demo.ci.cms.va.gov/erie-health-care/

## Acceptance criteria

- [x]  Peggy provides content feedback for page/form/tool and any associated static pages
- [ ]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [ ] Teams leaves comments about any feedback they decide not to take
- [ ] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
VAMC Erie content feedback

Please note, I didn't review the individual clinic pages. I focused my content review on the higher-level pages.

Chaplain services
- Suggest using contractions: 
you will to you’ll 
They will to They’ll
They are to They’re

----

Performance page
- Suggested rewrite quality of health care to health care quality 

---

Volunteer or donate page
- Insert space btw. Community living center (CLC) and Here’s your chance.

---

Policies page
- “Not” is bolded in this sentence, "However, you’re not allowed to do general visitation by going from bed to bed….”  but not in other VAMC policy page. I recommend unbolding this to match style of other VAMC pages. 

----- 

About us
- There is TK under Research and development header

---


Jobs page
- Apply for job through Veteran Recruitment
Please rewrite to: 
Veteran Recruitment Appointment (VRA) lets us hire eligible Veterans without competition to positions at any pay level through GS-11. The GS-11 pay grade is typically for mid-level positions held by civilian government employees. 

---

History
No changes

---

Mission
No changes

---

Contact us page
- We used TTY throughout VA.gov… but TDD here. Recommend changing it to TTY to align with VA.gov 

----

Operation status
- For Veterans Crisis line: also consider add in the VCL text, chat and TTY numbers? 
- Please use sentence case for our labels if they are not proper nouns


Clinic pages
-Please format clinical hours in our style 7:30 a.m.-4:30 p.m.
Under Health services offered here accordions
-Please use serial comma
Suicide Prevention accordion is listed 2x


-----

Billing page
No changes 

-----

Register for care
- Also please update style of TRICARE to all caps to match how it’s treated throughout VA.gov

------

Make an appointment page

- Tricare style Should be all caps, per VA.gov
- Under this accordion, How do I cancel or reschedule my appointment? 
The link [reschedule of cancel some appointments online]. please remove “reschedule” from this link, as you can’t reschedule online. Veterans can only cancel.. so link should read You can also [cancel some appointments online]

----
Suicide prevention page
- Style for phone number,  remove the 1- before numbers
- Consider adding VCL chat, text and TTY numbers here

-----

Caregiver support
No changes

Homeless
No changes

Pharmacy care
No changes

Woman Veteran care
No changes

Minority Veteran care
none

**Comment by peggygannon** [comment]
Hi, @SgardnerPMP do you have any questions about my feedback above? I not will close out this issue. thank you!

**Comment by SgardnerPMP** [comment]
Hello Peggy, 

Sorry for the delay.   All recommendations have been updated with the exception of:

Clinic pages
-Please format clinical hours in our style 7:30 a.m.-4:30 p.m.

This is a API format issue that CMS will have to resolve.  It is pulled in from Lighthouse API, so we will have to request the front end team to see if they can change the format.  Once they implement the change it should retroactively change all facility hours.

Erie will be in final reviews in Dual State and we can make all final changes there. 

Thank you,
