### ISSUE TITLE
Request Contact Center Review for Cerner Support - Health Pages (In Progress)

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10530]
**This ticket is not complete**

When this work is on staging and ready for review with the Contact Center, assign this issue to: Chante Lantos-Swett and Kimberley Daniels
+
remove "(In Progress)" from ticket title

**Issue Details:**
The Public Websites team is implementing changes to the Health pages, for support for the upcoming Cerner launch. There are changes to the unauthenticated content, and changes to the alert boxes' experience for authenticated users + additional content changes.

Functionality will change the display of the alert box so that if a user is tagged for a Cerner facility, they will have a link that is easily accessible for that login experience. 

**Launch Date and Details:**
Launch Date of Cerner is currently TBD. In coordination with SSOe teams.

URL: link to your project on staging

Product Guide/Video:
In speaking with Chante, we would schedule a time with Chante and Kimberley to demo the changes (via Zoom). That demo would be recorded and then shared as the video content. This replaces the need for generating a video through other means.

**Comment by MickinSahni** [comment]
@DanielleThierryUSDSVA to check-in with Chante on the minimal artifacts necessary for the Contact Center

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. I connected with Chante, and we're going to meet on Thursday or Friday of this week to talk more about what might be needed in this case. Will update here when I have more info. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jenniferlee-dsva @MickinSahni. Here are my notes from call with @clantosswett. 

**Questions that will be good for contact centers to know (and next steps to get answers):**

- How many people will be affected by the first rollout (August, Chalmers, schedule appts)? How many affected by then 2nd rollout (Fall, Mann-Grandstaff, all health tools)? Danielle to ask SSO team.
- Does Cerner have a dedicated group within their contact center to help with support, and what's their plan? Danielle to email Cerner contact, cc'ing Chante. 

**Materials needed for VA.gov contact center:**

- We don't need full product guide with demo video. This isn't a VA.gov product, we're just sending people to My VA Health, so we don't want to do full training (takes time, can be overwhelming) and this shouldn't be the responsibility of the VA.gov contact center beyond handing off to My VA Health support.
- We just need a write-up with:
  - Brief description of what this is
  - New terms the contact center should know (ie, My VA Health)
  - URL(s) of affected page(s) and screenshots of the sign in modals with My VA Health messaging/buttons
  - Any VA.gov-related error states 
  - Handoff # for My VA Health

I'm happy to put this write-up together.

**Comment by jenniferlee-dsva** [comment]
- How many people will be affected by the first rollout (August, Chalmers, schedule appts)?  Appx 100 per my notes from @lalexanderson-dsva but please correct if wrong or has changed.

- How many affected by then 2nd rollout (Fall, Mann-Grandstaff, all health tools)? Danielle to ask SSO team.  @lalexanderson-dsva may know as well. 

Does Cerner have a dedicated group within their contact center to help with support, and what's their plan? Danielle to email Cerner contact, cc'ing Chante.  [ Perhaps @lalexanderson-dsva  may also know?]

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni FYI for sprint planning - I attended a Cerner meeting and asked about contact center on Cerner side. Confirmed # and will add to info write up for contact center when I return from being OOO (8/10-8/12). Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. Keeping you in the loop. I've written up the attached and shared with Chante, who confirmed this is good to go and she'll share with contact center. I'm just waiting for a final sign-in modal update to the scheduling page to capture and insert the final screenshot and then will send Chante final version. 

This document covers the 8/21 launch. So I'll create another one for the next launch as we get closer to that. Thanks!

[VA.gov appointments tools change_Information for contact center_8.18.20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5090230/VA.gov.appointments.tools.change_Information.for.contact.center_8.18.20.docx)

**Comment by MickinSahni** [comment]
Closing out
