### ISSUE TITLE
Staging Review Cerner Support - Health Pages

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10532]
When this ticket is ready, add back Andrea Hewitt and Megan Kelley as Assignees. Add back the labels 'collaboration-cycle', 'content-ia-team'. and 'product-support'

## Steps to complete Staging Review: 

- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [ ] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
- Link to your accessibility test cases:
  - **TestRail** [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc) **OR**
  - **Markdown** [Github accessibility test cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/accessibility-test-cases-template.md)
- List of known issues (with links to tickets when applicable)

## Meeting attendees from **requesting team**
- Product Manager (required): **name**
- DEPO product lead (required): **name**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **names**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by MickinSahni** [comment]
Should happen once we’ve gotten the final content

**Comment by MickinSahni** [comment]
@DanielleThierryUSDSVA to check-in with Lauren A. re: whether Cerner's end-to-end testing/Staging Review

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. @jenniferlee-dsva included this Q in her questions for Lauren so just updating below based on slack.

![image](https://user-images.githubusercontent.com/62957278/87070132-59b69c00-c1e6-11ea-8f09-054e57fe02e7.png)

**Comment by MickinSahni** [comment]
> Hi @MickinSahni. @jenniferlee-dsva included this Q in her questions for Lauren so just updating below based on slack.

Awesome. Thanks, Danielle. I gave Tze a heads up that this is still in our court, which means #10638 will need to be prioritized. 

The primary input for #10638 is a list of user-scenarios and Staging test-accounts. 

Based on your and Kelson's work so far, do you think we're in a good place to populate those?

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @MickinSahni. I connected with @kelsonic and we recommend waiting until we've finalized content. Kelson can add more details. Thanks!

**Comment by kelsonic** [comment]
Hey! So we can definitely add e2e tests at the moment, but I do recommend waiting until the content is further finalized to avoid the redundancy of updating the e2e tests. But ya just lmk when and I'll start building them! 🙂
