### ISSUE TITLE
VSP content review: VAMC Altoona (staging)

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#10539]
## User story

This ticket captures VSP content feedback on VAMC Altoona

Staging link:   Site Access in Devshop - http://altoonahealthcare.web.demo.ci.cms.va.gov/altoona-health-care/

## Acceptance criteria

- [x]  Peggy provides content feedback for page/form/tool and any associated static pages
- [ ]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [ ] Teams leaves comments about any feedback they decide not to take
- [ ] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
VAMC Altoona content feedback

Please note, I didn't review the individual clinic pages. I focused my content review on the higher-level pages. 


Performance page
- Suggested rewrite: change quality of health care to  health care quality 

----

Volunteer or donate page
- Please update time/day format to 8:00 a.m. to 4:00 p.m. ET, Monday through Friday
To put the time zone immediately after the time. 

---

Policies page
- Fix the odd spacing under “Visitation” header
- Fix some contractions: 
	you are should be you’re
	they are should be they’re
- There is an extra period in sentence under “bringing children to visit” header


-----

Jobs page
- Under "Apply for job through Veteran Recruitment" header
Please rewrite paragraph to the below. I recommend removing "white-collar" from the sentence

Veteran Recruitment Appointment (VRA) lets us hire eligible Veterans without competition for positions through pay level GS-11. The GS-11 pay grade is typically for mid-level positions held by civilian government employees. 

---

History and Mission pages
no changes

---

State college clinics page (this is the only one I reviewed). So please be sure the other clinic pages match the style here.  

- Please format clinical hours in our style 7:30 a.m.-4:30 p.m.

Under the "Health services offered here" accordions
- Please use serial commas
- Suicide Prevention accordion is listed 2x

----

Operation status page
- Emergency phone numbers: per our style, we don’t use 1- for our numbers
- For Veterans Crisis line: 
- Please change "press" to "select" her our styleguide. 
- Also consider adding to the VCL the text, chat and TTY numbers here 

----

Contact us page
- We used TTY throughout VA.gov… but TDD here. I recommend updating to TTY to align with VA.gov

---

Billing page
- Please fix this heading to match the CTA button: Pay online, by phone, or by mail

- Under "pay in person" header please remove the periods in the address for the Agent cashier window

------

Register for Care

- Please make H1 sentence cased

- Please update style of TRICARE to all caps to match how it’s treated throughout VA.gov 

---

Make an Appointment

- Please make H1 sentence cased
- please update TRICARE to all caps. to match how it's treated throughout VA.gov  
- Under this accordion, "How do I cancel or reschedule my appointment?":
The link [reschedule of cancel some appointments online]. please remove “reschedule” from this link, as you can’t "reschedule" online. Veterans can only cancel.. So the link should read: 
You can also [cancel some appointments online]

-----

Suicide prevention
- Please fix style for phone number: remove the 1- before
- Consider adding the VCL chat, text and TTY numbers here
- Use "select" in the VCL number (not press)

**Comment by peggygannon** [comment]
Hi, @SgardnerPMP do you have any questions about my feedback above? I not will close out this issue. thank you!

**Comment by SgardnerPMP** [comment]
I will post updated ASAP.  Actions are underway, just have to update the issues with info.  Thank you.
