### ISSUE TITLE
Add Debt Letter History Endpoint

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#10548]
## Issue Description
A new endpoint has been provided by the DMC team to return the debt letter history. A method to access this will need to be added to the debts service, a method within the debts controller will also need to be added.

## Tasks
- [ ] 

## Acceptance Criteria
- [ ] A new route will be added allowing veterans to view their debt history for a particular debt.

**Comment by leahkeeler** [comment]
Per our request the API endpoints are combined into one API call - there is no need for this work

**Comment by leahkeeler** [comment]
Closing ticket
