### ISSUE TITLE
STEM: Pre-fill 10203 chapter fields

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10549]
As an authenticated user, I need the 10203 form to pre-fill application information that I have previously provided to VA.gov so that I have to spend less time completing the form.

## Assumptions:
1. This work is done behind feature flag #7271.
2. The applicant is authenticated and pre-fill data is that available on authenticated users profile.
3. The Chapter 3 pre-fill data is retrieved using the EVSS service documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/statement-of-benefits/gibs-2017-07-06.yaml)

## Acceptance Criteria
1. The following Chapter 1 questions are pre-filled (note: similar to 22-1995):
    a. Your first name
    b. Your middle name
    c. Your last name
    d. Suffix
    e. Social Security Number
2. The following Chapter 3 questions are pre-filled with the most recent enrollment information available:
    a. What's the name of the school where you plan on using the Rogers STEM Scholarship
    b. City
    c. State
3. The Chapter 3 Summary (https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040787) page displays an entitlement remaining alert:
    a. When the service is available and the user has 181 days or more of remaining entitlement
    b. With the following background color is #fff.
    c. The amount of time left (**[X] months, [Y] days**) displays the data returned by the EVSS service.
    d. With the following content:

> **Your remaining education benefits**
> 
> Our entitlement system shows that you have more than 6 months of education benefits remaining. You should apply when you have less than 6 months of entitlement left.
> 
> Months you have left to use: MM months, DD days

4. The following Chapter 5 questions are pre-filled (note: similar to 22-1995):
    a. Country
    b. Street address
    c. Line 2
    d. City
    e. State
    f. Postal code
    g. Email Address
    h. Home Phone number
    i. Mobile phone number

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040835) as of 07/01.
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ac00ddfc52dd101577639d5bdcf25a720a029fbf/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md#form-title-apply-for-the-rogers-stem-scholarship-11) as of 07/01.
3. [10203-Fields.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4805097/10203-Fields.xlsx)

**Comment by dmccurdybah** [comment]
PRs:

- vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/13411
- vets-api: https://github.com/department-of-veterans-affairs/vets-api/pull/4494
- vets-api-mockdata: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/144

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-10 at 10.13.28 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7576e78a-a089-4762-9f09-ab997d250cad)
##
![Screen Shot 2020-07-10 at 10.13.47 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c19d77c0-75ce-4ef4-a337-d392282914dd)
##
![Screen Shot 2020-07-10 at 10.14.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ea99bf38-e23c-408c-9fba-eec2d81e6bc5)
##
![Screen Shot 2020-07-10 at 10.14.34 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8c593b2d-9d64-496d-ae90-33c63a0197ed)
##
![Screen Shot 2020-07-10 at 10.16.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/25f1e8a4-6488-4fe8-80ee-c8e486674da5)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-10 at 11.13.55 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4e16f149-cb6a-423c-83e8-e7b9d3853687)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9334&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-10 at 1.19.21 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/fb2b0a55-3453-45de-a606-3c92a72c5961)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by sonntag-adam** [comment]
Blocked as we don't have staging users for recent enrollment information and entitlement remaining alert.

**Comment by dneel-bah** [comment]
EDU has agreed to launch with an MVP without pulling entitlement / enrollment data from EVSS.  The re-validation of AC3 in staging will be handled in #12734 once the test data is available in the staging environment.  Closing this story because all other AC have been signed off on.
