### ISSUE TITLE
Form step: Review biographical information

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#1054]
## Stories (Definition of Done)

- [ ] I can review my name, DOB, and gender, or understand that they are not available
- [ ] I can understand what to do to correct my info if it is wrong
- [ ] I can understand that if any of these things are wrong I won't be able to continue with the pilot
- [ ] I can save my application and finish it later
- [ ] I can continue with the app
- [ ] I can move to the previous step in the app

## Implementation notes

- This is a direct copy of the same screen in the 526 app, and should use the same bio info.

## Design screenshot

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/386172038

**Comment by aeltarhoni** [comment]
@YanaRoy will follow up.

**Comment by aeltarhoni** [comment]
@smoonpeyes will sync with Carola
