### ISSUE TITLE
Change entry URL of MDOT

### ISSUE THREAD

**Issue by bradl3yC** [department-of-veterans-affairs/va.gov-team#10543]
During staging review, one of the blocking points was to adjust the URL to access this tooling.

**Structure:** <br>
![image](https://user-images.githubusercontent.com/20994159/81016380-eb401100-8e25-11ea-8170-60bf5269d0c9.png)

Page | URL | Breadcrumb | Notes
--- | --- | --- | ---
Order prosthetic socks static content page  |  www.va.gov/health-care/order-prosthetic-socks/  | Home > Health care > Order prosthetic socks | - Static content page that includes link to eBenefits to order 
Order hearing aid accessories static content page | www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/ |  Home > Health care > Order hearing aid batteries and accessories | - Static content page that includes link to online form for ordering
Order form for hearing aid accessories | www.va.gov/health-care/order-hearing-aid-batteries-and-accessories/order-form-2346  |  Home > Health care > Order hearing aid batteries and accessories > Order form 2346 | - This is the online order form

**Notes**
- Please connect with your writer/editor on the proper verbiage and capitalization of the breadcrumb

**Comment by leahkeeler** [comment]
@brad here is the ticket that has all the links that need to be changed https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-med-device-order.md
