### ISSUE TITLE
Change the Drupal GraphQL to provide metadata to the CMS Transfomer

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#10556]
# Overview

The CMS transformer transformer pipeline transforms the Drupal content into static HTML files. To be able to automate the process, we need metadata about the structure of the different bundles: content types, paragraph types, etc.

# Details
We need to have GraphQL queries that provide the following:
* List of bundles to export
* For each bundle provide the meta data of the bundle
* For each bundle provide the list of fields in the bundle
* For each field provide the meta data of the field
* Be able to run a query that provides all the above info:
  * fetch all the bundles
  * with the meta data
  * and the fields in each bundle
  * and the metadata for the field

# References
The handling of references from one node to another probably need special attention. The CMS team should collaborate with the transformer implementation team to add details in here about implementing references.

# GraphQL and tar file versions
When creating the tar file, write to file the graphQL output to a schema file. This way, we know that the content and the schema match. There's still a bit of a race condition, but we can worry about this level of consistency at a later date.
The transformer pipeline will use the version from the tar file.

**Comment by swirtSJW** [comment]
I think this looks good.    We anticipate handling this with GraphQl to deliver the data, and then write that toto a file that would be included in the tar of the content export.   By doing it this way we make the data available for real time things like Lighthouse and and front end content builds via the content export.

**Comment by drorva** [comment]
The openAPI supplied with the export works for us now.
