### ISSUE TITLE
Dev Task: Complete Questions from Developer Experience Team at VA

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10550]
We had a meeting on June 12, to answer a series of questions from the Developer Experience Team at the VA. 

There were some questions that we did not answer, as we ran out of time.

They have asked that we answer these questions and send the answers back.

**Tasks**
- [ ] Fill out the questions below
- [ ] Send to Tim Akampa, either by Slack or by email (akampati@thoughtworks.com)

- Where do you see friction points in getting software built on your team?
- What things has your team has done in the past that have greatly improved your software development process?
- Mention any three areas that you think could greatly improve developer experience across the VA? 
- Are there any stages in which manual testing needs to be done before or after deploying?
- How are incidents managed and reported back to the team? 
- How are the applications (vet-websites and vets-api) monitored in production? 
- How are cross functional requirements(e.g performance, security) tested?
- Do you have any system architecture documentation that you could share with us?

**Comment by MickinSahni** [comment]
Pulling into backlog until we're able to work on this
