### ISSUE TITLE
[Launch] Original Claims: Prep for Security Review

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10555]
## Issue Description
One of the collab cycle items is to do a full security review.  We will likely be able to use all of the same things for BDD but we were asked/recommended we go ahead and do Original Claims now.  The following items are required for the security review.

- [x] An architecture diagram, showing involved systems + data flows
I am getting information on the necessary fidelity.  Sounds like we will likely need a basic diagram showing hitting EVSS, MVI, and the S3 bucket for our file uploads.  Not sure anything more complex is required but will add info when I hear back from Andrew Gunsch.
  - Completed; see comment below for architecture diagram
- [x] Description of any new publicly-exposed endpoints (vets-api or otherwise)
The MVI one is the big one but not sure what else was created.
  - There are no new publicly exposed endpoints.  The new `/v0/mvi_users/{id}` endpoint requires an authorized token. See the [swagger docs](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/postMviUser) for a description of this endpoint.
- [x] Description of any new interactions with dependent services (i.e. vets-api --> ???)
MVI again and I don't know if anything changed with EVSS.
  - Again, see summary of `/v0/mvi_users/{id}` in the [swagger docs](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/postMviUser) for a description of interaction with dependent services.  No changes were made with the interaction with EVSS.

- Description of any other security hotspots you're concerned about / want extra attention on
MVI endpoint is public?

Additional Info from Andrew.

> here's a couple examples of arch diagrams I've found helpful for other security reviews:
> * https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/92
> * https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsa/teams/caregiver/architecture-diagram-as-of-june-15-2020.pdf
> I'm mostly interested in understanding things around the boundaries of vets-api --- nontrivial flows to/from vets-api, including services that vets-api depends on (as they relate to your team's application)

## Acceptance Criteria
- [x] Ready for security review and updated info attached here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/128
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SarahJaine** [comment]
Requested architecture diagram
![Original Claims Architecture Diagram-Page-1](https://user-images.githubusercontent.com/9893700/86062709-ef0ba080-ba2e-11ea-8bf2-4814eb6846f1.png)
