### ISSUE TITLE
Add www. to SMS response URL w/o increasing number of message segments

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#10554]
As a user connected to the VA network, I need to be able to access the screener but cannot because of VA's unconventional use of the `va.gov` internal DNS entry, so I can quickly complete an entry screening.

**Comment by DanielleThierryUSDSVA** [comment]
Hi. @batemapf. We need to stay <160, right? We may be OK just adding the www.

Would be:

Welcome. To help us protect you and others, please use our COVID-19 screening tool and share your results when you arrive: https://www.va.gov/covid19screen

Total of 155 characters with spaces.

If we do need to shorten further, here's a version that's 149 characters with spaces:

Welcome. Please help us protect you and others. Use our COVID-19 screening tool. Share your results when you arrive: https://www.va.gov/covid19screen

**Comment by DanielleThierryUSDSVA** [comment]
Hi @sstrass. We think we're okay with adding the www to the link for the first text without needing to cut any character. Updated text below. Just let me know if it needs to be shortened. Thanks!

Welcome. To help us protect you and others, please use our COVID-19 screening tool and share your results when you arrive: https://www.va.gov/covid19screen

**Comment by batemapf** [comment]
Just tested this — looks like change still needs to be implemented by VEText team. @DanielleThierryUSDSVA would you please follow up with them (or tell me I said I would do that and clearly failed to)?

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf Just followed up in slack and tagged you. Thanks!
