### ISSUE TITLE
Not top forms: Add custom form content fields into Drupal for form detail landing pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10561]
## Not top forms: Add custom form content fields into Drupal for form detail landing pages

This ticket is related to VA form detail landing pages, per this [epic #5590 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5590)

**Acceptance critera:**

- [x] Add the custom "Related to" and "Online tool" field values (if any specified) for the 400+ forms that are not "top" forms for MVP. 
- [x] Spot copy check/validate selected form detail pages. 

---------------

**Content source docs:**

See this folder for the final docs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs/README.md

---------------
**Product repo:**
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages

**Comment by jenniferlee-dsva** [comment]
Added this FYSA to the other form detail custom content ticket. Adding here for parity. 

> @RLHecht @lunascoop - Wanted to make you aware of a couple of updates that happened after the copydecks were finalized. I don't think this affects the custom content addition that you're working on, but thought you should know about this change, so you don't treat it as a bug. 
> 
> The copydeck shows the H1 and meta title patterned like this:  `VA Form xxxxx` and `VA Form xxxxx | Veterans Affairs`
> The CMS update will now use `About VA Form xxxx` as the H1 -- adding the "About." 
> 
> This affects the: 
> 
> - H1
> - Breadcrumb
> - Meta title

**Comment by RLHecht** [comment]
Update 7/23: Selina completed her pass through all these but I'm going back in to fix issues related to the CMS nightly migration, which lost a lot of the work done (updating the form name to match the PDF and selecting the category for the related to field). I'm doing a first pass on 200 and above in the spreadsheet and for the ones I had already reviewed, I will revert to the version in Drupal from before the nightly migration. FYSA @MickinSahni

**Comment by RLHecht** [comment]
This ticket is now complete. I've moved all of the forms in the spreadsheet into Review. I reverted the first 200 back to my last revision before the most recent nightly migration where we lost some work in the H2. @jenniferlee-dsva There were a few forms that weren't showing up in Drupal or not opening, which I've put into the top of the ticket so we can keep track of them. Moving to validate but let me know if I should close.

**Comment by jenniferlee-dsva** [comment]
Hi @RLHecht - thank you! yes, since this ticket is just for the adding, we can close this, There's a separate ticket here:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11014

just for validating. Please add your validation using the ^ ticket AC, but could you wait until the preview bugs have been fixed? I also want to spot check (after your validation) but want to make sure the final updated FE preview is being used for visual check.
