### ISSUE TITLE
Document the public assets S3 bucketand the regular deployment bucket

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#10568]
## Issue Description

For each environment in `vets-website`, we deploy to two S3 buckets.  One is designated an "assets" bucket, and the other just seems to be a catch-all bucket which currently contains the output of both the content and the application builds.

In addition to the S3 bucket that holds the build outputs of the content and the webpack builds, we also have another bucket which holds just the app assets (no content).

- prod-va-gov-assets
- staging-va-gov-assets
- dev-va-gov-assets

The purpose of the different buckets isn't very clear.

---
## Tasks
- [ ] Investigate & document the existence of each S3 bucket

## Acceptance Criteria
- [ ] A document exists describing why the buckets exist and how each one fits in with the website

**Comment by timwright12** [comment]
Noting that these buckets have updated since the content build separation

**Comment by timwright12** [comment]
Content prod: http://content.www.va.gov.s3-website-us-gov-west-1.amazonaws.com/
Content staging: http://content.staging.va.gov.s3-website-us-gov-west-1.amazonaws.com/
Content dev: http://content.dev.va.gov.s3-website-us-gov-west-1.amazonaws.com/

Apps prod: http://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com
Apps staging: http://staging-va-gov-assets.s3-us-gov-west-1.amazonaws.com
Apps dev:  http://dev-va-gov-assets.s3-us-gov-west-1.amazonaws.com

Uploads: https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/

Unused Apps prod: http://apps.www.va.gov.s3-website-us-gov-west-1.amazonaws.com/
Unused Apps staging: http://apps.staging.va.gov.s3-website-us-gov-west-1.amazonaws.com/
Unused Apps dev: http://apps.dev.va.gov.s3-website-us-gov-west-1.amazonaws.com/

**Comment by jhouse-solvd** [comment]
Removing "operations" label per Tim Wright.

**Comment by timwright12** [comment]
This is complete and will be live the next time platform website is published https://vfs.atlassian.net/wiki/spaces/pilot/pages/2226388993/S3+bucket+locations
