### ISSUE TITLE
Adding VA API Team Members to DSVA Slack

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#10567]
Please add the following new API team members to DSVA Slack. We are expecting a number of new additions over the next few weeks and will try to batch requests where we can.

Brent Schneider - UX Designer  brent.schneider@adhocteam.us
Darcy Duda - UX Writer darcy.duda@adhocteam.us 
Andrew Suprenant - PM  andrew.suprenant@adhocteam.us

Thank you!

**Comment by KevinMHoffmanUSDS** [comment]
All three have been added to Slack. In the future, feel free to use the Slack channel #vfs-platform-support if you need to follow up on anything like this. Cheers!
