### ISSUE TITLE
EDU: Create Feature Flag for RPO Routing Update

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10578]
As a developer, I need to create a feature flag that can be used to turn on and off routing files to the St. Louis RPO so that it can be delivered to production in a timely manner.

## Assumptions:
1. Feature flag for St. Louis RPO routing will need be available in the vets-api repo.
1. The Feature Flag is configured per environment.
2. When the feature flag is:
     a. Off: Submissions are routed to both St. Louis and Buffalo
     b. On: Submissions that would be routed to St. Louis are routed to Buffalo.
3. The feature flag `routeStLouisRPOtoBuffaloRPO` is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. The Feature Flag `routeStLouisRPOtoBuffaloRPO` is available to be used for altering submission routing.
2. The Feature Flag description is: "All submission data that was previously routed to St Louis RPO is routed to the Buffalo RPO"
3. The Feature Flag is defaulted to the OFF state.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by elder-joseph** [comment]
Associated Pull Requests:

Front End: https://github.com/department-of-veterans-affairs/vets-website/pull/13255
Back End:  https://github.com/department-of-veterans-affairs/vets-api/pull/4442

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-06-26 at 11.56.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/50e9bb44-025d-442c-8931-aa2bf8fb9971)
##
![Screen Shot 2020-06-26 at 11.57.08 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/61e19ae9-be60-4d44-8c6a-4890d6bff901)
##
![Screen Shot 2020-06-26 at 11.57.17 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/240ad9e3-9565-4407-9f13-f4830a599d9e)

**Comment by desireeturner** [comment]
This is blocked by https://github.com/department-of-veterans-affairs/vets-api/pull/4460

**Comment by desireeturner** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4460 is merged. Moving back to in progress

**Comment by sonntag-adam** [comment]
This is now showing in both https://staging-api.va.gov/flipper/features and https://api.va.gov/flipper/features
