### ISSUE TITLE
[Bug] Facility Locator - "Sticky" error message after correcting search input

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#10577]
## What happened?
On Staging [**Find VA Locations**](https://staging.va.gov/find-locations/) page, after an invalid search, the error-message persisted even for a subsequently valid search, and required a page-refresh to return location results on the results-list.

## Specs:
- Browser-/device-agnostic
- Unauthenticated-experience

## Steps to Reproduce
1. Go to https://staging.va.gov/find-locations
1. In **Search by...** text-field, input an invalid location or zip-code (e.g., **uiop, in** / **qwerty, pa** / **00000** / **99999**), then click **Search** button to intentionally trigger an error-message.
1. In **Search by...** text-field, input a valid location or zip-code (e.g., **reading, pa** / **90210**), then click **Search** button.
1. Observe that despite valid location/zip input, the same error-message is triggered. \[See GIF-capture below.]
1. Refresh the page, observe that the unchanged, valid input now generates search results on the left-panel results-list.

**GIF-capture**
![fl-sticky-error-msg](https://user-images.githubusercontent.com/587583/85907190-81a90700-b7c5-11ea-8e49-db16d6483cbf.gif)

## Desired behavior

- The user should be able to continue searching after an error state without requiring a page refresh.
- An appropriate error message is displayed. (TBD)
- A valid search should immediately remove any error message from a previously-invalid search, and load search results into results-list 
- A new search should clear the error message and initiate the query again. 

Added 8/7/2020:
The design system has the following error messages which could be applicable to this situation:

| Scenario | Message title | Message content | Actions | Component | State | Location |
| ---- | ----| ---- | ---- | ----| ---- | ---- |
| Form general error | We need you to start over with this application | Something’s not working quite right. We’re sorry to make extra work for you, but please try applying again in a few minutes. | Start over | Alert box | Error alert | Replace content below page title |
| Unable to complete a user-initiated task, can’t proceed | We’ve run into a problem | We’re sorry. Something went wrong on our end. Please try again. | N/A | Alert box | Error alert | Above page title |
| Component is not accessible (general message; specific iterations to be added later) | [COMPONENT NAME] isn’t working right now | We’re sorry. Something went wrong on our end. Please refresh this page or try again later. | Go back to previous page | Alert box | Warning alert | Replace affected component |

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tlei123** [comment]
I just checked your functional bug-fix on http://917c43b0c5ac86b06420538fc781b5f1.review.vetsgov-internal/find-locations/ , and the fix worked

FYI, "uoip, pa" and "qwerty, pa" no longer replicates the error-message.  Only "00000" and "99999" bring the error-message up.  Not sure if this warrants a new Defect, but it's worth another look.

After triggering the eneral error message with "00000"/"99999", correcting to "reading, pa"/"90210", then clicking **Submit**, the error-message was successfully replaced with valid results \[page-refresh no longer needed].

**Comment by brangi** [comment]
merged
