### ISSUE TITLE
EDU: Route St. Louis RPO Submissions to Buffalo RPO

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10581]
As a Buffalo RPO Team Member, I need submissions that were previously being sent to the St. Louis RPO to be routed to my RPO so that the submissions can be processed in a timely manner and there is no impact to the veterans.

## Assumptions:
1. This work is completed behind feature flag #10578 .

## Acceptance Criteria
1. Submissions from the following states are routed to the Buffalo RPO:
    - Colorado
    - Illinois
    - Indiana
    - Iowa
    - Kansas
    - Kentucky
    - Michigan
    - Minnesota
    - Missouri
    - Montana
    - Nebraska
    - North Dakota
    - Ohio
    - South Dakota
    - Tennessee
    - Wisconsin
    - West Virginia
    - Wyoming
2. Submissions are no longer routed to the St. Louis RPO.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4452

**Comment by delli-gatti-michael** [comment]
Testing by submitting forms from all of the following states, generating a spool file, and ensuring that none of the submissions are routed to St. Louis (\#331) and that they are instead routed to Buffalo (\#307)
- [ ] Colorado
- [ ] Illinois
- [ ] Indiana
- [ ] Iowa
- [ ] Kansas
- [ ] Kentucky
- [ ] Michigan
- [ ] Minnesota
- [ ] Missouri
- [ ] Montana
- [ ] Nebraska
- [ ] North Dakota
- [ ] Ohio
- [ ] South Dakota
- [ ] Tennessee
- [ ] Wisconsin
- [ ] West Virginia
- [ ] Wyoming

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Confirmed in Staging. Closing this issue
