### ISSUE TITLE
Background application processing for 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#10586]
How might we update the processing of the application so that the user doesn't see as long of a response time?

Possible alternative Workflow
```rb
### On Request
# 
# -> get vet icn from MPI
# -> create claim
# -> create "pending" submission:
# 
#       Submission.create!(
#         saved_claim_id: claim.id,
#         metadata: metadata,
#         status: 'pending'
#       )
# 
# -> start background job
# 
### In Background Job
# 
# -> get veteran status
# -> get icn of caregivers
# 
#         submission.update!(
#           metadata: { version: 'v1', data: new_metadata }
#         )
# 
# -> auth to CARMA
# -> submit to CARMA
# 
#         submission.update!(
#           carma_case_id: 'CARMA_ID',
#           submitted_at: 'DATETIME'
#         )
# 
# -> send pdf version as attachment
# 
#         submission.update!(
#           attachments: (submission.attachments << attachment),
#           status: 'completed'
#         )
```

**Comment by kevinmirc** [comment]
For reference, the last staging submission was 15 seconds.

<img width="682" alt="Screen Shot 2020-06-24 at 2 24 02 PM" src="https://user-images.githubusercontent.com/7391284/85612040-7ff50d00-b626-11ea-97bf-2ae06c3b1d39.png">

**Comment by ala-yna** [comment]
Note from 6/25 - We're going to move forward with sending the entire submission at once, and work with DEPO and CARMA to figure out the best way to break that process up to make the user experience more seamless.

cc @kevinmirc

**Comment by kevinmirc** [comment]
Closing since the description is "How might we update the processing of the application so that the user doesn't see as long of a response time?" and the comments outline a solution.

Linking the implementation epic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/16952
