### ISSUE TITLE
Design - allow user to print their application

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#10588]

**Comment by jenstrickland** [comment]
For the "Download your online application" button, this should use the [Download PDF pattern](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340). This will render a link with a download icon and indicate that this is a PDF and what the file size is, and includes attributes that enhance the experience for UX and those using assistive tech.

**Comment by jonathanjnelson** [comment]
@jenstrickland Thank you! I updated the [designs](https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/426759908_Error-Desktop-V-06). Utilizing this pattern, do we typically leave the content as **Download PDF** or is it customizable?

**Comment by jenstrickland** [comment]
@jonathanjnelson we should be explicit in our pdf download links, indicate what is being downloaded, following the pattern.
