### ISSUE TITLE
Create a landing page for IRIS redirects and implement redirects

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10592]
### Problem Statement
tbd Beth, Danielle

--- 

~~1/ Implement redirects for IRIS URLs - **[iris.custhelp.va.gov](iris.custhelp.va.gov)** AND **https://gibill.custhelp.va.gov**  @ncksllvn / @kelsonic / @lunascoop~~ (Update 6/24: these redirects cannot be set up client-side because the legacy pages do not have the injection script. Chante is reaching out to the team that oversees IRIS to confirm they can and will manage redirects on their side, once they have the URL)

2/ Create a landing page for redirected users - @bethpottsVADEPO / @DanielleThierryUSDSVA 

Stakeholder SME: @clantosswett 

ETA: Go live when the IRIS links are removed: Unconfirmed 6/26 Friday; please wait for Chante's "go." 

**Content requirements:**

- Must include CTA to call VA311
- Must include CTA to search for information on VA.gov
- Must inform user that IRIS (Information Routing & Inquiry Service)  is no longer available
- `Nice to have: `Our site search bar [Is it possible to use a custom version of our normal 404 page that's just our search page with a 404 message? But instead of a default 404, show the customize IRIS redirect message.]

**Copy draft:**

**We're sorry, but IRIS is no longer available**
For questions and benefits help, you can:

- Call VA311  
- Search `VA.gov `
- Or use one of our frequently used online tools

`[list of link teasers  drupal component]`

**Check your VA claim or appeal status**
Check the status of a VA claim or appeal for benefits, including disability compensation, pension, VA health care, and more.

** Sign in FAQs [https://www.va.gov/sign-in-faq/]**
[some kind of blurb] 

**Change your address on file with VA**
Update your address and other contact information for VA benefits and services.

**Change your VA direct deposit information**
Find out how to change your direct deposit information online

**Reschedule, cancel, or view your VA appointment**
Request, reschedule, or cancel your VA health care appointments online.

## Tasks
- [ ] Define problem statement
- [ ] tbd

## Acceptance criteria
- tbd on our solution recommendation 

## Considerations
- CMS bandwidth
---------------------

[This issue is related to ticket #10125](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10125)

**Comment by ncksllvn** [comment]
The redirect piece will be easy but just fysa that they'll be client-side redirects through the inject script, like we do on benefits.va.gov

**Comment by jenniferlee-dsva** [comment]
I figured that as well, thx @ncksllvn for confirming. 

- Does that mean that any IRIS links that live on legacy pages without our modern header won't get redirected here? 
- What about people who have bookmarked  `iris.custhelp.va.gov` or `https://gibill.custhelp.va.gov` - those folks _would_ be redirected, correct?

**Comment by clantosswett** [comment]
Because IRIS will still be usable internally to respond to inquiries until July 1, we might want to add a disclaimer notifying users they will receive a response to their previously submitted inquiry by July 1. Once we reach July 1, we can probably remove that information. Here's a suggestion for that language:

**Comment by mnorthuis** [comment]
@clantosswett Do teams use the web interface of IRIS, or do they have an internal interface for responses?  Want to make sure that redirecting doesn't impact internal teams' ability to access inquiries and respond. 

@DanielleThierryUSDSVA @bethpottsVADEPO when you are ready, let's discuss where this new landing page will live.

@stephorkandatx can you please submit a redirect request for the appropriate IRIS URLs?

**Comment by clantosswett** [comment]
@mnorthuis internal users access IRIS using this URL: https://va-osvchelpdesk.custhelp.va.gov/app/answers/detail/a_id/42/

And just to clarify, the target date to have the redirect page set up and IRIS links removed is **Friday, 6/26, TBC by me**. Internal IRIS helpdesk users will have access to the system to answer submitted inquiries through June 30th. But we want to stop veteran/user submissions from being made so helpdesk agents can clear out their queues before it officially goes away.

**Comment by ncksllvn** [comment]
Update per Slack thread - neither of these IRIS pages include the inject script and they are not on www.va.gov, so we don't have the ability to redirect them. The team that manages IRIS will have to set up the redirect

**Comment by clantosswett** [comment]
That all makes sense. Maybe a silly question, but can we still create the redirect page that the IRIS team will redirect to?

**Comment by jenniferlee-dsva** [comment]
Replying to @clantosswett 
...can we still create the redirect page that the IRIS team will redirect to?

Yes. Could you confirm with the IRIS team that they will/can implement the server side redirect? If they cannot do that for whatever reason, creating a redirect landing page won't be useful. 

Once they confirm, we can give them the new URL of the redirect page and work on publishing the page. 

@clantosswett Can you help us coordinate go live date with that team? We don't want them to make the redirect live until the landing page was ready.

**Comment by clantosswett** [comment]
@jenniferlee-dsva thank you for the summary. I will confirm with the team that hosts IRIS that they can implement a server side redirect and notify the group once I have that information. I will make sure to coordinate the go live date and time with that team. My assumption is that the new page will go live during the daily deploy on Friday. If you imagine it happening at a different time, let me know so I can be aware of that during my conversations with that team.

**Comment by clantosswett** [comment]
@jenniferlee-dsva @stephorkandatx I wanted to confirm here that the redirect page is a go and we have identified who will implement the redirect to this page. I am working today to finalize the content for this page, with the relevant stakeholders. Given this needs to go live tomorrow, it would be helpful to know what is needed by when. Here is the list I am tracking but please let me know if I'm missing anything: 

- Finalized content delivered to PW team: tracking for this to be done ~12pm today

- Provide new page URL to team implementing redirect: not sure when this is needed but I will follow up with the team on this.

- Preview of the landing page to be reviewed and approved by key stakeholders: Completed by COB today or early tomorrow morning

- New landing page published to production with daily deploy: Friday ~3pm

**Comment by jenniferlee-dsva** [comment]
@clantosswett - should the 'remove IRIS links on pages' task go live at the same time as this redirect page or can they be staggered?

**Comment by clantosswett** [comment]
@jenniferlee-dsva I think they can be staggered. What were you thinking in terms of the timing? I'm thinking the links would be removed prior to the landing page going live. If that is the case, would that happen during today's daily deploy?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jenniferlee-dsva @clantosswett Content for landing page v1 with a few notes in comments. Let me know your thoughts and I can finalize for Nick to flow into page. Thanks![IRIS landing page v1 6.25.20](https://app.zenhub.com/files/133843125/35806ee0-9333-4d31-85bb-43f303220cf7/download)

**Comment by jenniferlee-dsva** [comment]
@DanielleThierryUSDSVA - LGTM - the warm empathetic tone. You're so masterful.

**Comment by jenniferlee-dsva** [comment]
@clantosswett - re https://github.com/department-of-veterans-affairs/va.gov-team/issues/10592#issuecomment-649583475

I was really wondering if the links could be removed AFTER the redirect went live. But that's fine, it sounds like the team should be targeting removing the links and launching the redirect landing page together on Friday?

**Comment by clantosswett** [comment]
@DanielleThierryUSDSVA agree with, Jen, this looks fantastic. Two quick questions. I don't have data around the top uses for IRIS but I know some people used it to find information about facilities. I'm wondering if we might want to have a link to the facility locator as part of the helpful online tools? 

My second and more difficult question has to do with stakeholder requests. I am hearing from VBA and VHA that they don't want all users to be directed to VA 311 because it will take longer for a user to speak to an agent going through that IVR. VBA specifically wants their benefits hotline number listed and VHA wants the My HealtheVet helpline listed. Any thoughts on how to navigate these requests? I fear if we give in to adding a few additional numbers then everyone will want their number included on the page. But I'm also worried they won't back down from it.

**Comment by mnorthuis** [comment]
Proposed URL for landing page after discussion with @DanielleThierryUSDSVA and @bethpottsVADEPO 

www.va.gov/iris-no-longer-available

**Comment by DanielleThierryUSDSVA** [comment]
@jenniferlee-dsva @clantosswett @ncksllvn 

Final content. Nick - I may have an update to the aria coding for phone numbers. Will post if needed asap. Thanks!

[IRIS landing page v3_6.25.20](https://app.zenhub.com/files/133843125/ba762c12-a3f0-4be7-91f7-c8689834311f/download)

**Comment by ncksllvn** [comment]
@DanielleThierryUSDSVA PR is open! https://github.com/department-of-veterans-affairs/vagov-content/pull/698

**Comment by ncksllvn** [comment]
![image](https://user-images.githubusercontent.com/1915775/85800370-d63d7b00-b70e-11ea-85ae-c47371bdc0e7.png)

**Comment by DanielleThierryUSDSVA** [comment]
This looks great, @ncksllvn, thank you! @clantosswett Let us know when we have approval or any additional stakeholder feedback on content. Thank!

**Comment by bethpottsVADEPO** [comment]
@stephorkandatx @ncksllvn @DanielleThierryUSDSVA @jenniferlee-dsva @RLHecht @clantosswett Confirming here that this work is moving forward for implementation Friday 6/26.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks. @bethpottsVADEPO.

2 caveats for @ncksllvn 

- Please wait for final go-ahead before merging.
- Please set this to no-index so it doesn't appear in search.

Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn just fyi that it is looking like this may be held off (no definitive change in direction at the moment, but definitely a reason to hold off on merging until we are 100% sure).

**Comment by clantosswett** [comment]
@ncksllvn @DanielleThierryUSDSVA There is a meeting happening at 2pm where we should learn new information. I've reached out directly to see if they can update me prior to this on how to proceed with the redirect page. I'll make sure to update here when when I hear something. Thank you all for your patience and apologies for how all over the place this work has been.

**Comment by clantosswett** [comment]
@DanielleThierryUSDSVA @jenniferlee-dsva @ncksllvn the group is NOT moving forward with the transition plan from IRIS. Funding has not be definitively secured but will likely be available starting today or tomorrow. We do not need to move forward with publishing the redirect page.

**Comment by MickinSahni** [comment]
Removing from sprint 24

**Comment by jenniferlee-dsva** [comment]
@DanielleThierryUSDSVA  @clantosswett CC @mnorthuis  - Now that we have a reprieve of sorts with IRIS and can think through this more proactively, could we consider refactoring this 'not-available-redirect-landing-page' idea? Perhaps more in line with creating a more permanent 'Contact us for help' landing page? 

- One idea is to create a global Contact US landing page that would replace the [IRIS "Ask a question"](https://iris.custhelp.va.gov/app/ask) link in the global Contact Us header dropdown and other hub "Ask a question" links. `<-- I think Chante's DEPO card has to do with this email us form??`

- Or to create a learning center page that can act as a contact us page (that includes a directory of VA toll free numbers, commonly used VA.gov tools, and a new email form).  

- Or somehow a combo of these if both of these are needed?

**Comment by mnorthuis** [comment]
I do like the idea of a global contact us page that is easily accessible from global nav and footer, and linked to from other applicable places in the experience.

**Comment by MickinSahni** [comment]
@bethpottsVADEPO @DanielleThierryUSDSVA to define the problem statement and potentially convert to an epic to house any tasks we might need.

**Comment by jenniferlee-dsva** [comment]
Overlapping/duplicate/related? DEPO card: https://github.com/department-of-veterans-affairs/digital-experience-products/issues/212

FYSA @DanielleThierryUSDSVA @mnorthuis

**Comment by mnorthuis** [comment]
This issue feels like it was going a different direction than we are now with the proposed contact us landing page.  Wondering if we should close this one and start fresh with a focus on welcoming user to a new support option rather than a nod to IRIS?

**Comment by bethpottsVADEPO** [comment]
Yes, that's what Danielle and I were thinking too. And whoever we decide should drive this can create that ticket??

**Comment by brianalloyd** [comment]
Team, reviewed this ticket as part of our grooming strategy and was wondering if this is still in scope or if we can close this ticket.  Thoughts?

**Comment by bethpottsVADEPO** [comment]
We can indeed close this dinosaur, @brianalloyd. Doin' it! Sitewide content will create a new ticket for when IRIS does get retired in the fall for tasks that will need to take place then. @RLHecht would you create that ticket? Include a screen shot of the language Danielle mocked up and Nick dropped into this ticket above as we'll be able to reuse some of that content that's still relevant. We'll start with these tasks:

- Add to contact us page: "IRIS no longer available" messaging in an informational alert
- Coordinate with Chante about redirect strategy
