### ISSUE TITLE
Discovery - Review filtering logic for Facilities

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10595]
We know that we have a high % of dropoff in the user funnel on the Facilities page.

We have also received some feedback from users indicating they are not seeing "their facilities/clinics" or that their "facilities/clinics are incorrect." We know that when they say 'clinic' they are not talking about direct schedule clinics because that feature is not currently available. 

There is UX testing to be done here as well based on current design. We'll be testing existing design again with user in an upcoming round of user testing. 

### What we want to confirm:
- [ ] re-verify that what filtering logic (MHV identifiers) va.gov does for the sites is correct and not excluding sites we think are valid

### For reference, the main known differences between VAOSR and legacy VAOS are:
- [ ] legacy you can 'select city/state' and then it populates clinics
- [ ] VAOSR hides facilities that are not available
- [ ] Both use MVI to get the registered sites

**Comment by jbalboni** [comment]
I did a check of all the cdw facilities, to make sure their site ids were within our ranges. They all were within our range. 

I'm going to check against the facilities api list of facilities if I can get that data, too.

**Comment by jbalboni** [comment]
Same result for the VA facilities api list. All VHA facilities are within the range we've set.

**Comment by lenaecb** [comment]
@saneshark - where are we with this?

Just checking numbers and see that in the past month the the dropout rate on the facilities page as gone up to 37%. We can attribute some of that to folks seeing the 'your facility does not support online scheduling' but really that's only about 10%.

I am realizing from our user feedback sessions that this page is definitely not working for users. Almost every test someone gets tripped up on this page. 

So, we can pull this out of sprint and couple it with future design changes that I know need to be made. But I just really also want to make sure we're showing Veterans all the data they should be seeing.
