### ISSUE TITLE
[Discovery] Document best engineering practices/standards

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#106]
## Description
Our engineering team operates under cultural best practices within the team, but now that we are looking to work with VFS teams outside the platform, we need to clearly document our engineering best practices and come up with processes to enforce them.

## Questions
- Does a team need to create an API contract (OpenAPI doc) and have sign-off before starting work?
- How does a VFS team get started writing code? e.g. tutorials, example app, generators
- How to enforce process? Epic templates, admin app to generate branch/review instances
- How to allow for longer testing sessions without reinventing the VA's current 3 week to 3 month deploy cycles?
- Can we make Docker dev nicer or should we move to Vagrant or NixOS for reproducible dev envs?

## Use cases
-  What is an example of a bad actor?
   - Facility Locator 20s latency?
   - 526 auxiliary forms copy pasta'ed and later had to be refactored
   - Following our examples too closely (everything looks like a nail...)

## AC
- [ ] Generate tickets that breaks this documentation work into specific sets of engineering practices

**Comment by rianfowler** [comment]
# Visual Regression Testing

## Overview 

Visual regression testing captures and compares screenshots. Failure occurs when the test image deviates significantly from the baseline image. 

Good for detecting 
- CSS regression  
- SPA loading errors 

## Short term

Use VRT to monitor critical pages on the site - testing at least once a day or testing after every deploy to production 

Tasks: 
- Run the current set of VRT everyday: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16518
  - validates production 
  - only validates on page load (no interactions to code)
  - only validates on Chrome 
- Notify slack channel when there are failures 
- Expand test coverage to highest traffic pages of the website 

## Medium / Long term: 
Improve detection and make easier to use

- drive test coverage with a config or the sitemap (ideally no developer intervention to test new pages)
- easily update baseline images 
- track historical baseline images 
- VRT on other browsers (specifically IE 11) 
- Improve reporting 
  - notifying through slack doesn't scale 
  - include information about failures e.g. base image vs failure image, link to page that failed 


Other tickets: 

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1248
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1249
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1251

**Comment by rianfowler** [comment]
Front end tickets:
- [Enzyme best practices](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15720)
- [Create guidelines for redux usage (epic)](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11015)
- [Document fetch patterns and helpers](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15549)

**Comment by rianfowler** [comment]
FE epic: #193
