### ISSUE TITLE
Implement Feedback from Design on Wizard Mockup

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10602]
## Goal 
We want to take feedback from the design community on how best to present the wizard for eligibility.

## Tasks
- [x] Implement feedback obtained into mockups before prototypes.

## Acceptance Criteria
- [x] Feedback implemented
- [x] Mockups shared for additional feedback

**Comment by sporeboy** [comment]
Initial feedback implemented per conversation with PW designer, Liz Lantz. Three wizard start screen variations created. Link: https://xd.adobe.com/view/17b9e3b9-abb2-4c17-6619-adcc54353687-6188/

**Comment by sporeboy** [comment]
Revised mockups shared and reviewed by Wizards team: https://dsva.slack.com/archives/C0113MPTGH5/p1593034304002500

**Comment by sporeboy** [comment]
Feedback implemented and variants created--Options 2 and 3 here: https://xd.adobe.com/view/17b9e3b9-abb2-4c17-6619-adcc54353687-6188/
