### ISSUE TITLE
Create FE CMS preview: form detail landing pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10606]
### Create FE CMS preview: form detail landing pages 

**aka Enables writers to be able to preview the form detail pages**

As a content author, I want to preview a form detail node, so I can validate that the content is rendering correctly as a page. 

-----------
**Frontend content mapping specs:** 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs/Form-detail-page-content-fields-FE-mapping-062520.docx

**Sample FE design/layout :**
_Note: Some of the text details in this wireframe is slightly outdated. For what exact text to use, you should refer to the FE content mapping spec above._

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/Generic-form-page-with-May-2020-updates.pdf

Happy to provide a brief walkthrough of the CMS fields as well - lmk. @ncksllvn @kelsonic 

Added 6/25: Steve Wirt just completed in-body alert capability to CMS form page, so the FE should account for that as well above the **When to use this form** section. I'm sorry the above documentation doesn't include this in the mockup bc it was a later addition. I can just walk you through it quickly, lmk.   [9189](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9189) for details. 

## Remaining tasks
- [ ] complete design iteration - https://github.com/department-of-veterans-affairs/va.gov-team/issues/10606#issuecomment-657660113 (Nick)

## Acceptance criteria
- We will be able to preview the form detail page in Drupal

**Comment by jenniferlee-dsva** [comment]
Related tickets:

Change Revision Date logic and label to "Form last updated" [8633 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8633)

FE display of in-body alert [9189 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9189)

**Comment by jenniferlee-dsva** [comment]
@ncksllvn / @kelsonic  - When the preview functionality is ready for form detail landing pages, can you please let @RLHecht and @lunascoop know?  They'll use preview to validate the form custom content work that they're working on this sprint.

**Comment by MickinSahni** [comment]
@ncksllvn does this ticket also accomplish this task:
> [Drupal] Create a "node -type" for Form Detail pages

**Comment by ncksllvn** [comment]
@MickinSahni I think that was already done when the pages were being set up in Drupal, whereas this work is to create the FE template for that node-type (the node-type being `va_form`).

**Comment by ncksllvn** [comment]
![image](https://user-images.githubusercontent.com/1915775/87324539-39e0ea00-c4fe-11ea-82cf-aff0fd0f992b.png)

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - Per Slack thread, providing feedback here from me and form detail page designer @artsymartha68. 

1/ line break between `Related to `and `Form last updated `- needs para break or more line space

2/ `Related to` field values - See content doc here for [FE copy mapping - page 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs/Form-detail-page-content-fields-FE-mapping-062520.docx) shows the copy that should be used to display for each data value. 

3/ All Download links on the form detail page - make them initiate download, same as with download links on forms search

4/ Under the R`elated forms and instructions` section: Can you add vertical/para break space after the form number and the form name? (Or _(prefer)_  take the form name out of the H4 and make it strong text. If that's not 508-compliant, then 2nd preference, make the form number and form title each individual H4s?)

5/ Note - Martha and I verified the `online tool `and tool CTA `button` with this other form page for the 526ez. They look good - no changes. https://us02web.zoom.us/j/2746446208?pwd=QmpPUWpvMFphL3B1NXh0ZCtKOHlPQT09 

FYSA @jenstrickland or @1Copenut - We'd like to make sure that the FE template is being built with good 508 semantic markups. Would you mind specifically commenting on #4 above?

**Comment by ncksllvn** [comment]
@jenniferlee-dsva question on number 2 -

Definitely a lot more logic than I expected there! So `/preview?nodeId=5776` for example has -

```
Related to: VA health care; VA benefits for service members
```

Should that be mapped over to `Related to: Health care; Service members`? I'm confused on why the text isn't written that way to begin with

**Comment by ncksllvn** [comment]
Edit - also, I separated the benefit list using semicolons because some of the options contain commas. See `/preview?nodeId=5820` -

![image](https://user-images.githubusercontent.com/1915775/87332492-a3b2c100-c509-11ea-9849-8d6999406f6c.png)

**Comment by ncksllvn** [comment]
> 3/ All Download links on the form detail page - make them initiate download, same as with download links on forms search

We're gonna run into the same problem here as `/find-forms/` where the super easy way of just adding `download` into the `<a>` element doesn't work in IE or across different subdomains. There's nothing we can do on the latter case - it's a browser security thing. On the former, we can do the same thing as `/find forms/` by using JS to download the PDF to the tray, although I personally prefer to just accept the limitation in IE and let it open the PDF in the browser 🙂

**Comment by jenniferlee-dsva** [comment]
[Replying to ^ comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10606#issuecomment-657692179):

>We're gonna run into the same problem here as /find-forms/ where the super easy way of just adding download into the <a> element doesn't work in IE or across different subdomains. There's nothing we can do on the latter case - it's a browser security thing. 

That's fine. FWIW, the main need for instigating a download instead of a browser open has to do with errors that happen in Chrome and Firefox mostly. 

>On the former, we can do the same thing as /find forms/ by using JS to download the PDF to the tray, although I personally prefer to just accept the limitation in IE and let it open the PDF in the browser

What do we do today in forms search with IE? If we initiate the JS download there, we should do so in IE instances of form detail pages, too.  It seems like currently in IE form search, the behavior is that the download link does both - it opens in a new tab AND it generates a download dialog on the current tab. Is that right?

**Comment by ncksllvn** [comment]
> What do we do today in forms search with IE? If we initiate the JS download there, we should do so in IE instances of form detail pages, too. It seems like currently in IE form search, the behavior is that the download link does both - it opens in a new tab AND it generates a download dialog on the current tab. Is that right?

I'm not sure exactly what the full UX looks like when downloading in IE, just that it's using JavaScript to initiate the download instead of the native browser functionality because IE doesn't have it natively.  We can do this on the form detail pages too - it's just more work than Find Forms because right now form detail pages are just static HTML where as Find Forms is a React app.

**Comment by jenniferlee-dsva** [comment]
[And replying to this comment ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10606#issuecomment-657670229):

>I'm confused on why the text isn't written that way to begin with

Good question. ~Part of it is because there are forms in the VA Forms DB today which are not veteran benefit forms. For instance, there are some internal VA and external non-VA job/employment forms, so we need to distinguish for instance stuff that's in the `Careers and employment` benefits category and stuff that VA stakeholders think of as careers and employment but they're not benefits related at all - so we call those "Jobs or employment at VA."~

@ncksllvn - It looks like the benefit categories and labels have recently gotten updated and the text that's there is actually okay to use. (Before, the checkbox text was different and not actually matching exactly the hub category labels.) 

As of today - in Drupal: 
![image](https://user-images.githubusercontent.com/43381063/87342435-3f97f900-c519-11ea-9686-599f688036bd.png)

So...

>So /preview?nodeId=5776 for example has -
> Related to: VA health care; VA benefits for service members
> Should that be mapped over to Related to: Health care; Service members? 

Correct, but with a comma` , `instead of a` ; `semicolon. And since the Drupal benefit data field text got updated to match the benefit hubs, I actually don't think we need to create a FE mapping. 

We'll just have to make sure to let @kevwalsh and @swirtSJW to  not continue to change the text  of those fields.

**Comment by jenniferlee-dsva** [comment]
[RE semicolon comment:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10606#issuecomment-657679611)

I think this is moot now with the updated CMS benefit checkboxes aligning with benefit hub category labels. LMK if this is still a problem though @ncksllvn

**Comment by ncksllvn** [comment]
> Under the Related forms and instructions section: Can you add vertical/para break space after the form number and the form name? (Or (prefer) take the form name out of the H4 and make it strong text. If that's not 508-compliant, then 2nd preference, make the form number and form title each individual H4s?)

@jenniferlee-dsva What do you think of using an H4 followed by an H5 so that the font of the form name is slightly smaller?

![image](https://user-images.githubusercontent.com/1915775/87347409-2f841780-c521-11ea-883e-77a392590cc7.png)

**Comment by jenniferlee-dsva** [comment]
Hmm. I like it better than when they were both H4s. 

I'm going to defer to the design eyes of @artsymartha68 and @rtwell  though because...

1/ I don't know if it's okay to use H5s on our pages - don't recall them in the design system, and
2/ I can't tell if the H5 is actually smaller in font size than the para text font. It _appears_ that way to my eyes, but I'm not sure. And if it is, is that ok from design POV?

Martha and Ryan - note that some form names are short enough to fit within/on 1 line; but some form names, like the examples above, are long and wrap. Something to consider when reviewing the use of H5 above and with mobile, so on.

**Comment by artsymartha68** [comment]
I like the H5 better. If there is a styling available then I guess it means H5 exists....?

I'd still like review/approval of this semantically from @1Copenut and/or @jenstrickland

**Comment by jenstrickland** [comment]
Agreed, @artsymartha68. For this VSA Public Websites CMS template work, the VSA accessibility specialist needs to review the design, including HTML design, of the template before the template is provided for others to use. Going forward, it would be helpful to provide the design for the accessibility specialist to mark up accessibility specifications before development of CMS templates. Does that sound right, @1Copenut ?

@ncksllvn @jenniferlee-dsva Is there a pilot project or placeholder content available to test the templates with?

**Comment by jenstrickland** [comment]
From the screenshot, it looks like the heading styling is different from what's in the [VA design system](https://design.va.gov/design/typography).

The preference would be to use an H5 after an H4. Will there always be H1, H2, and H3 preceding the H4 on the page?

**Comment by ncksllvn** [comment]
> Is there a pilot project or placeholder content available to test the templates with?

There is, in the form of a CMS preview page, but you need SOCKS proxy set up to see it. Do you have that set up? This link should give you a preview if so, http://preview-prod.vfs.va.gov/preview?nodeId=5820. I'd maybe hold off a bit though because I'm still making these [changes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10606#issuecomment-657660113) above.

> From the screenshot, it looks like the heading styling is different from what's in the VA design system.

Shouldn't be. No special style applied besides reducing margin-top on the H5.

> The preference would be to use an H5 after an H4. Will there always be H1, H2, and H3 preceding the H4 on the page?

Yep!

**Comment by jenstrickland** [comment]
Re SOCKS proxy, still need to see if I can get that set up. I have my PIV, but was told I needed some additional permissions set up. That link looks like something I could look at it in the VA environment. Would that be possible?

I wonder if the design system is out-of-sync. The design system shows H2, H3, H4, and H6 as Source Sans Pro, while H1 and H5 are Bitter. The H3s and H4s in the screenshot above look like they're Bitter.

![Screen Shot 2020-07-14 at 10 32 13 AM](https://user-images.githubusercontent.com/57469/87438251-4d9f5580-c5bd-11ea-9321-bd61f7f706f6.png)

**Comment by ncksllvn** [comment]
> Re SOCKS proxy, still need to see if I can get that set up. I have my PIV, but was told I needed some additional permissions set up. That link looks like something I could look at it in the VA environment. Would that be possible?

Yeah, our writers look at the previews via the VA environment regularly, so 100% possible and preferred as well.

> I wonder if the design system is out-of-sync. The design system shows H2, H3, H4, and H6 as Source Sans Pro, while H1 and H5 are Bitter. The H3s and H4s in the screenshot above look like they're Bitter.

I have no idea what is correct. Looks like a bug in the design system though. 

The formation CSS clear sets all headings to Bitter - 

![image](https://user-images.githubusercontent.com/1915775/87439104-5e040000-c5be-11ea-8bc1-eacd77d03ce2.png)


For some reason design.va.gov has site-specific CSS that overrides it -

![image](https://user-images.githubusercontent.com/1915775/87439173-7542ed80-c5be-11ea-8dd0-ab6c8d473d55.png)

No clue why it is doing that.

**Comment by jenstrickland** [comment]
@1Copenut @rianfowler @emilywaggoner — do you know whether Formation CSS or the VA design system documentation is the right styling for headings, based on the difference noted above?

**Comment by ncksllvn** [comment]
Hm I don't enjoy saying the whole "that's a site-wide issue" thing but this page isn't exceptional in how it styles headings

**Comment by jenniferlee-dsva** [comment]
@rtwell may be able to answer your questions re headers - Source Sans Pro vs Bitter: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10606#issuecomment-658220237

**Comment by jenniferlee-dsva** [comment]
But yes, @jenstrickland  - that would be a sitewide design system issue.

**Comment by rtwell** [comment]
The Formation CSS is the correct styling…almost. The only disparity I see is the h6, which should be Source Sans Bold. I don’t know where that decision came from…if I had to wager a guess, it’s because the smaller headers get more and more difficult to differentiate as their sizes are relatively similar. I’d love to update our typography site-wide, but that’s an issue for another time. For now, @ncksllvn can we fix/purge .site-showcase so it’s rendering properly on design.va.gov? Do you need anything from me regarding specifics?

**Comment by ncksllvn** [comment]
@rtwell Can we do that in its own issue, since this issue is written for the form detail pages?

**Comment by rtwell** [comment]
whatever is best for you!

**Comment by jenstrickland** [comment]
@rtwell In general, the serif fonts may be more difficult for readers to comprehend. If the design system council has the opportunity to revisit the history of the difference in the VA design system documentation and the Formation CSS, that would be helpful. The sans-serifs will be easier, quicker to read for the most people.

**Comment by rtwell** [comment]
@jenstrickland noted! In the spirit of keeping this ticket focused on the VA forms detail page, please open site-wide issues/recommendations like this in their own ticket, and link this convo so we don't lose the thread. Thank you for the observation and the initiative to note this topic!

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - per convo, I've uploaded the updated heading hierarchy in the repo here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-heading-hierarchy-071620.pdf 

This helps us solve for the sticky header situation, so we don't have to go all the way down to H5 and helps us resolve for gianormously long form names. 

Thanks @rtwell and @artsymartha68 for your expert design eyes on this. Sorry our form names are so intense - we don't control the form names {shrug}.

**Comment by MickinSahni** [comment]
Standup 2020-07-16
- some heading updates to make (e.g. h4 --> h3s)

**Comment by jenniferlee-dsva** [comment]
I think this can be closed. I saw the merged updates, and they look great!

**Comment by jenniferlee-dsva** [comment]
Sorry - spoke too soon. There appears to be one FE mapping thing that isn't showing up right now. I don't know if it is a an api bug or if it is due to just an omission during the preview creation. 

FE preview and FE mapping bugs: 
1/ “Non-VA” Related to value should display at the frontend: “A non-VA form. For other government agency forms, go to the GSA forms library.”   <https://www.gsa.gov/reference/forms>

2/ When the “When to use” custom content field is empty, the When to use this form H2 should be suppressed/not display.

Example – form SF 144 http://preview-prod.vfs.va.gov/preview?nodeId=6133
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/c8be6be2-cb14-469b-bdea-1d37849fdedf)
 

[https://app.zenhub.com/files/133843125/28494eef-308d-49ff-bdd4-9bb1cae2be02/download](https://app.zenhub.com/files/133843125/28494eef-308d-49ff-bdd4-9bb1cae2be02/download)

**Comment by kelsonic** [comment]
Hey @jenniferlee-dsva if we can make those 2 items a separate ticket happy to knock them out asap! 🙂

**Comment by jenniferlee-dsva** [comment]
That would be great if you could - thank you!

**Comment by kelsonic** [comment]
Ticket created! ⬆️
