### ISSUE TITLE
remove vet360 reference_data code from vets-api

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#10607]
the va profile team is deprecating their `/referencedata/contact-information/va/zipcode5` endpoint. after talking with a frontend engineer, we realized that none of the vets-api `reference_data` endpoints are being called by the frontend. therefore i think we should remove all the old `reference_data` code from vets-api.

## Acceptance Criteria
vets360 `reference_data` code has been removed from vets-api

**Comment by johnpaulashenfelter** [comment]
@lihanli we just figured out the same thing in paralell with @kfrz
