### ISSUE TITLE
Develop a Few User Types to be Created for 686 Testing

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10605]
## Goal
To create new users (3) to test with, we need to establish the parameters for the personas we want to test with.  This avoids collisions with other systems.

## Considerations
- Rated Disabilities (0-10%) and (50+%)
- VA file number (yes) and (no)
- Born 1960 (before) and (after)
- Template? How do we add other important aspects to the user profile?
- Develop use cases/ presonas

| first_name | middle_name | last_name | gender | birth_date | ssn | phone |email | password | who_is_using |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| JAIME | Dep | BROOKS | M | 1975-11-26T00:00:00-08:00 | 796186272 | 800-827-1000 | vets.gov.user+EBN1@gmail.com | Zm9*** | EBN |
| JOHN | Dep | BROOKS | M | 1955-11-26T00:00:00-08:00 | 796186272 | 800-827-1000 | vets.gov.user+EBN2@gmail.com | Zm9*** | EBN |
| JIM | Dep | BROOKS | M | 1989-11-26T00:00:00-08:00 | 796186272 | 800-827-1000 | vets.gov.user+EBN3@gmail.com | Zm9*** | EBN |

## Tasks
- [x] Generate personas
- [x] Get in touch ID.me and establish contact, request that three separate users be created for us

## Acceptance Criteria
- [x] 3 users have been created and shared with BGS folks

**Comment by sporeboy** [comment]
Created sets of data for six users to support testing user access to 686... MD doc here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-test-users.md

**Comment by sporeboy** [comment]
Users created using ID.me. Info logged at link above.

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/dependency-claims/research-design/686-test-users.md
