### ISSUE TITLE
CT-Search: Create Feature Flag for Search Enhancements.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10615]
As a developer, I need to create a feature flag that can be used to turn on and off the search enhancement changes so that they can be delivered to production in a timely manner.

## Assumptions:
1. Feature flag for search enhancement routing will need be available in the vets-api & vets-website repos.
1. The Feature Flag is configured per environment.
2. When the feature flag is:
     a. Off: Search functionality works as it is in production currently.
     b. On: Search functionality uses the new logic in future stories.
3. The feature flag `gibct_search_enhancements` is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. The Feature Flag `gibct_search_enhancements` is available to be used for the search enhancements.
2. The Feature Flag description is: "Comparison Tool Search Enhancements to improve usability"
3. The Feature Flag is defaulted to the OFF state.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by delli-gatti-michael** [comment]
This is in Staging. Closing this issue

![Screen Shot 2020-06-29 at 10.51.15 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/dd855f40-f6b8-4a42-a460-e023112024da)
