### ISSUE TITLE
CT-Search: Add additional search criteria to free text search field.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10617]
As a Comparison Tool user, I would like to be able to search for schools by nickname and/or ZIP code so that I can better find schools that I am looking for.

## Assumptions:
1. This work is completed behind the feature flag #10615 .
2. These data elements are not subject to the fuzzy search.

## Acceptance Criteria
1. The 'ialias' from the IPEDSHD is searchable within the Comparison Tool.
2. The 'physical institution zip code' from the WEAMS data is searchable within the Comparison Tool.

## Supporting Artifact:
1. N/A

**Comment by hughes-dustin** [comment]
Waiting on changes from [10613](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10613). The PRs for this story have the prod flags that I need to put my changes behind.

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/678

Branch: bah-10617

**Comment by sonntag-adam** [comment]
blocked by https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/10613

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-02 at 2.28.42 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/47065ac9-3420-46f1-9fce-54bb70c70f3a)
##
![Screen Shot 2020-07-02 at 2.34.19 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/de2a440d-fc3f-4194-a573-0e0dab86407b)

**Comment by sonntag-adam** [comment]
Testing passes QA.
