### ISSUE TITLE
Bad Address Indicator

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1061]
**Bad Address Indicator**
Each address stored in Vet360 comes with an optional Bad Address Indicator (BAI). When BAI is true that means that the VA has had mail returned to it from that address, which means not only have the taxpayers paid for a bad government interaction, but also that the Veteran in question did not receive her benefit.

We should consume the BAI and surface a UI notification to the user that the address in question needs attention.

This feature is expected to be available from Vet360, as a boolean, in November.

## High Level User Story
As a _____, I need _____ so I can _____.

## Hypothesis/(es)
**If** _we make this change_ **then** _we expect this to happen_.

## Goals
_What outcome(s) do we want to see?_ 

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`, `Automation + Instrumentation`, `Support`, `Capacity-building`)

## Definition of Done
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Epic`**

**Comment by lkoenigsberg** [comment]
Might be duplicate of #1797, which is an epic?

**Comment by Justin-Pickett** [comment]
yeah it is but no worries. I'll  keep the other one (#1797) as the Epic and close this one out.
