### ISSUE TITLE
CT-Search: Update Search to find close matching schools

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10613]
As a Comparison Tool user, I need the search functionality to be smarter so that results are found when I have small typos.

## Assumptions:
1. This story is completed behind the feature flag #10615 
2. The fuzzy match should leverage database capabilities.
3. This fuzzy match capability will not affect the autocomplete end point.
4. The search label currently calls out "City, School, or Employer Name"; AC1b assumes that School and Employer name leverage the same field.

## Acceptance Criteria
1. Institution search results return partial matches based the following search criteria:
    a. City
    b. Institution Name
2. The institution search results are sorted in the following order:
    a. % Match
    b. Institution Name

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
gibct-data-service PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/677
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13309

**Comment by dmccurdybah** [comment]
SQL query to display the calculated match percentages for a facility

```
SELECT
	institutions.institution,
	facility_code,
	SIMILARITY(institution, 'college of harleston') name_match,
	SIMILARITY(city, 'college of harleston') city_match,
	(SIMILARITY(institution, 'college of harleston') + SIMILARITY(city, 'college of harleston')) / 2 match_average
FROM "institutions"
	INNER JOIN versions on version_id = versions.id
WHERE 
	facility_code = '11929140'
	and production = true
```

**Comment by dmccurdybah** [comment]
GIDS PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/679

**Comment by dmccurdybah** [comment]
The "fuzzy-search" uses the `pg_trgm` extension to search the institution name and city using a [trigram search](https://en.wikipedia.org/wiki/Trigram_search) by breaking it into smaller 3-character pieces which are compared instead of the entire value.

This finds partial matches and helps users find good results even when the search term includes misspellings.

The results are ordered by a match percentage

**Comment by sonntag-adam** [comment]
Testing passes QA.
