### ISSUE TITLE
[QA] Test Plan - SSO Cerner

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#10638]
## Product/Feature summary

We are introducing a new alert box design to the health pages to highlight easy access to Cerner log-in, for patients who are Cerner patients. While there are content updates happening to the pages as well (both for unauthenticated and authenticated) those do not impact functionality.

There is a team at Cerner testing functionality. They have created test scenarios, including one that begins with our health page entry point.

Product/Feature Outline: \[https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/sso]
Product/Feature Epic: [https://github.com/department-of-veterans-affairs/va.gov-team/issues/9672]
Product/Feature Pre-Launch Checklist: \[provide link]
Product/Feature Design artifacts: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9693 (scroll down to "Documentation"
## Product-team SMEs

\[List points-of-contact (just full names) for all involved Subject-Matter domains.  Most often, these would be the relevant development-team members (Product Manager, UX Designer, Front-End Developer, & Full-Stack or Back-End Developer]
Product Management: 
Design/Research: 
Content/IA: 
Front-end: 
Back-end: 
QA: Tze-chiu Lei

## Proposed user-scenarios and Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs (ideally, use [this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md) from VSA Design Lead).  IMPORTANT for authenticated-experiences: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

1. <scenario-1> - <test-account-1>
2. <scenario-2> - <test-account-2> ...

## How to configure this issue

- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Test Plan reviewed by Product Team.
- [ ] Test Plan finalized per review feedback.
- [ ] Actual Test Run(s) completed on Staging \[or [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by tlei123** [comment]
@stephorkandatx , please start building your use-case above in the ticket Description or add a link to any separate docs you my have.

Feel free to ping me on Slack as needed.  Either I or @pjhill will help as needed.

**Comment by stephorkandatx** [comment]
From the handoff document at https://docs.google.com/document/d/11OGKfLk0fKd08pqCKT0Wvrt9ze2vZW_PSEn2kJdK714/edit#heading=h.yeejgddqil0p

**Testing**
We have a limited number of cases in TestRails pertaining to the release of scheduling functionality for patients at the Columbus (Chalmers P. Wylie Ambulatory Care Center in MVI). https://dsvavsp.testrail.io/index.php?/runs/view/241&group_by=cases:section_id&group_order=asc&group_id=66

NOTE: As soon as we know which facilities are launching you’ll need to ask for a test credential for a user that is attached to that facility in the MVI.
(There's not a good process for locating/establishing test users at a given facility. There are some VHA folks (Lynne Case, Mike Ramirez) in the #health-care-products channel in DSVA slack who can sometimes provide one. Otherwise some of our contacts in the IAM team (Damien DeAntonio, Ashley Piasecki) can try to query MVI and find a candidate record.

**Comment by pjhill** [comment]
Initial draft of test plan with new test case stubs created here -- https://dsvavsp.testrail.io/index.php?/plans/view/554

**Comment by pjhill** [comment]
[Invision mockup](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405228622) for #5743 appears to be missing callouts for the added / changed text. I'm assuming that the text being changed is similar to the other pages that were mocked up. Confirmation of the changes to the "Medical Records" health page would be appreciated.

**Comment by MickinSahni** [comment]
hey @tzelei @pjhill removing this ticket from our upcoming pw sprint (26) since there are content updates pending as well as figuring out test data availability.

**Comment by pjhill** [comment]
> hey @tzelei @pjhill removing this ticket from our upcoming pw sprint (26) since there are content updates pending as well as figuring out test data availability.
@MickinSahni -- Alright, the primary potential blocker regarding test data is defining at least on test user at each facility that will be launching the text / alert changes, right? Do these users also need to be associated with some kind of Cerner login as well?

Also, to check that I've synthesized the information available correctly, it seems like there are two main flows to the changes:

1. Unauthenticated users browsing the text changes/alerts on health care product pages
1. Authenticated users browsing the health care product pages

**Comment by MickinSahni** [comment]
Hey @kelsonic @DanielleThierryUSDSVA can you take a look at/help answer @pjhill's questions above?

**Comment by kelsonic** [comment]
>Alright, the primary potential blocker regarding test data is defining at least on test user at each facility that will be launching the text / alert changes, right?

>Do these users also need to be associated with some kind of Cerner login as well?

@pjhill We have test (fake) users that belong to at least 1 Cerner facility on staging that you can use for testing purposes, ping me and I'm happy to share the creds with you! 🙂 

>Also, to check that I've synthesized the information available correctly, it seems like there are two main flows to the changes:
>
>Unauthenticated users browsing the text changes/alerts on health care product pages
>Authenticated users browsing the health care product pages

So there are currently 3 states:

1. On production environments, we show the legacy content.
2. On non-prod envs and when a user is authenticated AND belongs to at least 1 Cerner facility, we show the authenticated content.
3. On non-prod envs and when a user is NOT authenticated OR does not belong to at least 1 Cerner facility, we show the unauthenticated content.

Hope this helps! 🙂

**Comment by pjhill** [comment]
@kelsonic Perfectly clear explanation -- thanks very much for that! Presumably, at some point the behavior on production will reflect the scenarios that you've described in 2 and 3, right?

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @kelsonic! Was just pulling together the explanation of 2 and 3, but this is perfect.

**Comment by kelsonic** [comment]
>Presumably, at some point the behavior on production will reflect the scenarios that you've described in 2 and 3, right?

@pjhill Exactly! 💯

**Comment by MickinSahni** [comment]
Hey @pjhill @tlei123 we're targeted 8/21 for our initial Cerner go-live. Do we have test cases wrapped up in TR? Is there anything you need from Public Websites?

**Comment by tlei123** [comment]
> Hey @pjhill @tlei123 we're targeted 8/21 for our initial Cerner go-live. Do we have test cases wrapped up in TR? Is there anything you need from Public Websites?

@pjhill , I'm assuming you got this, but do let me know if you need me to jump back in.

**Comment by tlei123** [comment]
> @pjhill , I'm assuming you got this, but do let me know if you need me to jump back in.

I'm jumping back in.  @pjhill is on parental leave, returning on/after 8/26.  VSP will have QA-review covered.

**Comment by tlei123** [comment]
@MickinSahni @kelsonic , would one of you mind checking @pjhill 's [stubbed-out TestRail test-cases](url) please?

- let me know if any steps need updating;
- provide missing info:
  - Entry-point URL(s);
  - Staging test-account(s) for the Authenticated cases.

I'm planning to start test runs this afternoon if everything's in place.

Feel free to ping me for a quick Zoom mtg if you prefer.  Thx much!  :)

**Comment by tlei123** [comment]
From [Slack conversation w/ Product Team](https://dsva.slack.com/archives/C52CL1PKQ/p1597770773104500), entry-point URLs and latest copy/layout updates have been provided.

I'm updating the test-cases, and running the unauthenticated ones today.

Will need to run VSA BaM1's BDD test-cases tomorrow (Wed), but will circle back here afterward to follow-up (probably Thu 20) on test-account(s).

**Comment by tlei123** [comment]
> I'm updating the test-cases, and running the unauthenticated ones today.

@MickinSahni @DanielleThierryUSDSVA , turns out @kelsonic 's [content updates PR](https://github.com/department-of-veterans-affairs/vets-website/pulls/kelsonic) for #12446 is still open right now.  I've updated all my test-cases for those updates -- was hoping that PR would've been approved & merged today so I could get started on runs.

I'll circle back to this tmrw (Wed) afternoon -- after BaM1's BDD test-case updates and test-runs.

**Comment by MickinSahni** [comment]
👋 Tze, how do we feel about closing this out?

**Comment by tlei123** [comment]
@MickinSahni , i'm finishing test-runs today, and will close this once all are done.

**Comment by tlei123** [comment]
@MickinSahni , all test runs done.

TestRail links
- Test Plan
- Coverage for References report
- Summary (Defects) report

NOTE: It seems the provided Staging test-acct ```ssoissoetesting+mhvcss4@gmail.com``` may have brought up Unauthenticated content (for Users signed-in but not belong to a Cerner facility) while running many of the Authenticated test-cases.  That would explain the numerous copy mismatches in the "Auth'd" bugs.  It'd be advisable for @kelsonic to take a first look at the bugs, as chances of false-positives are high.

I'm actually gonna keep this ticket Open for any further test-runs if the above test-account anomaly turns out to be true, and we can find some more Cerner-user test-accounts.  I'm not sure if the provided test-account actually enabled QA'ing the Authenticated content.

Feel free to reply here, or ping me on Slack, for further discussion.

cc @pjhill

**Comment by tlei123** [comment]
@MickinSahni @pjhill , [NEW Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/135) generated.

Turns out Staging feature-flag(s) disabled Authenticated-content for Messaging, Prescriptions, Records, and Results pages, so I've just Closed the 4 relevant Bugs as invalid, and added Retest statuses to the 4 now-outstanding test-runs in TestRail.

I'm expecting a new ticket to track when those 4 Auth'd pages will be flipped on, so that I can re-run the outstanding cases.

Feel free to reply here, or ping me on Slack, for any clarifications needed.

**Comment by MickinSahni** [comment]
Thanks, @tlei123. Gaining more clarity and hope to have an update on the path ahead soon.

**Comment by brianalloyd** [comment]
Closing per Grooming session.
