### ISSUE TITLE
Ensure we do not show 'Identity Verified' when user is not MVI

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#10636]
We need to make sure that we only show the Identity Verification section in the table when the user is both LOA3 and in MVI, otherwise this can happen (is LOA3, but not MVI):

![image.png](https://images.zenhubusercontent.com/5e9d15aab51cccb259a8a6c7/3439153c-cb24-4e33-ac41-8f28698253a4)

This is confusing for the user.

**Comment by sanlouise** [comment]
@mshea0606 This one is ready for validation when you have a moment 😄  We can test it by checking a non-MVI user, the 'Identity Verification' section should not appear in the table

**Comment by mshea0606** [comment]
@sanlouise do you know a non-MVI staging user? or is there a way to recreate it locally?

**Comment by sanlouise** [comment]
@mshea0606 How are staging test users normally created? Is there a specific team responsible for this? We surely should have a document that lists non-MVI, LOA1 etc. users for staging?  I don't normally test in staging but make sure things work properly locally. In this case, I logged in with a user that was in MVI but tweaked the code so I could test in my local environment. 🙂
