### ISSUE TITLE
Include a Cypress test template in the app generator

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#10631]
Once teams have gotten settled into using Cypress, the app generator should include a skeleton Cypress test.

**Comment by mchelen-gov** [comment]
This would definitely be appreciated, there are new apps spinning up that should probably be using Cypress.

**Comment by U-DON** [comment]
We're now on the latest version of the app generator (`generator-vets-website@3.4.0`), which generates Cypress tests.

**Comment by mchelen-gov** [comment]
awesome, ty!!
