### ISSUE TITLE
[FE] -Update Direct Deposit links to the profile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10644]
## Background
[Slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1593098872233100)
We need to update links from Direct Deposit that occur as a result of an error that redirect the user to correct their profile/contact information.

## Tasks
- [ ] Make updates

**Comment by erikphansen** [comment]
Looks like we can just set up redirects in Profile 2.0's router.

**Comment by sanlouise** [comment]
@mshea0606 This one is ready for validation 😄
