### ISSUE TITLE
Setup Dependabot in FE repos

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#10654]
`dependabot` needs to be configured for the following repos:

- [x] [Vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/13001)
- [x] [VFS tools](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/286)
- [x] [App Generator](https://github.com/department-of-veterans-affairs/generator-vets-website/pull/33)
- [ ] Design system

**Comment by timwright12** [comment]
@jhonnyoddball @meganhkelley Any reason we never did this? It's just a button in `settings/security_analysis`

**Comment by jhonnyoddball** [comment]
I did it on those repos but Rian removed it because it was generating too many PRs, it was too crowded when reviewing PRs in GitHub and some of those PRs that got merged on a "safe" mode were causing a lot of problems on other VSP apps. Therefore, he decided to remove it and put it on hold.

**Comment by laineymajor** [comment]
@jhonnyoddball how does this relate to your dependency management work? Let's discuss.

**Comment by jhonnyoddball** [comment]
Expired. Closing
