### ISSUE TITLE
Discovery research synthesis 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#10663]
## User research
Veteran sessions were conducted during the week of June 22 and June 26, with the goals of learning about the current Veteran health journey and how our solution might improve the pre-appointment process of filling out forms/questionnaires. 

[Link to Discovery research planning issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10226#issue-638921582)

## Acceptance Criteria
- [x] Create topline summary
- [x] Team recap meeting
- [x] Create synthesis doc (Github)
- [x] Create readout presentation

**Comment by arickalewis1** [comment]
Here's a link to the research findings document
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/user-research/research-findings.md
