### ISSUE TITLE
STEM: Update Schema

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10668]
## Assumptions
1. This story will be behind a feature flag #7721
2. This story is a blocker for submission of the 22-10203 STEM form

## Acceptance Criteria
1. The following schema fields are not required:
    a. isPursuingTeachingCert
    b. bankAccount
    c. mobilePhone

**Comment by dneel-bah** [comment]
Based on grooming; this work has been incorporated into #7857 .  Closing as OBE.
