### ISSUE TITLE
CT-Search: Update labels

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10669]
As a Comparison Tool user, I need the search functionality to be smarter so that results are found when I have small typos.

## Assumptions
1. This story is completed behind the feature flag #10615

## Acceptance Criteria: 
1. The Comparison Tool Landing Page displays the following content: 
   a. Text Search field Label "Enter a city, school or employer name" is replaced with "Enter a school, location, or employer name"
   b. Search button label "Search Schools" is replaced with "Search"

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13309

**Comment by delli-gatti-michael** [comment]
TestRail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/745

**Comment by delli-gatti-michael** [comment]
Local testing complete



![Screen Shot 2020-07-01 at 10.57.47 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d8771c8b-cb0d-4178-90cd-5068836eae38)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
@sonntag-adam UX has reviewed and this looks good!

**Comment by sonntag-adam** [comment]
Closing story
