### ISSUE TITLE
Offboarding of [Jon Pugh]

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#10667]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Jon Pugh
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VFS-CMS team; DevOps engineer; 6/19/20; Agile 6
- Please provide any type of access they may have. 
  > I believe most of Jon's access has been taken away (SOCKS, AWS, Slack), the only thing remaining is GitHub membership/team access to department-of-veterans-affairs/cms-infrastructure and department-of-veterans-affairs/all-va. GitHub ID = jonpugh
  
 
## AC
 - [x] Remove global/config.yml
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] SOCKS Access removed (if applicable) 
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Or
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jbritt1** [comment]
global/config.yml, SOCKS, and AWS removed in https://github.com/department-of-veterans-affairs/devops/pull/7136

confirmed user is not in Pagerduty at this time

request for GitHub org removal submitted: https://github.com/department-of-veterans-affairs/github-user-requests/issues/3156

**Comment by joanneesteban** [comment]
Confirming that the user did not have Google Analytics or Domo accounts.

**Comment by cmaeng** [comment]
I believe he's in these private Slack channels as well: `#a6-private`; `#a6-strategy`; `#devshop`

Can each of these channels be archived?
 
![slack image](https://user-images.githubusercontent.com/60702623/86044440-17d46b80-ba18-11ea-9d65-9547137df21c.png)

**Comment by ricetj** [comment]
Confirmed that DSVA account was deactivated
