### ISSUE TITLE
VANITY URL Redirect Request

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#10672]
**Selena, nothing for you to do on this one. Stakeholder communication is already taken care of.**
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*VR&E business line would like the option to use a short URL for print materials. Would like to create va.gov/vre*

### Requestor team info
*Beth Potts, PW (for Bettye Hodge, VR&E)*

### Implementation date
Date new URL(s) will be live: *Friday, 6/26*

Please indicate when the change/redirect(s) needs to be implemented"
- [x] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Vanity URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/vre | https://www.va.gov/careers-employment/vocational-rehabilitation/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [x] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
This is ready for implementation.

**Comment by bethpottsVADEPO** [comment]
Validated that it's live.
