### ISSUE TITLE
[Design] Connected apps error states

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#10684]
## Background

We realized we don't have any of the error states for connected apps.

FE Ticket: #10687

[Slack Conversation](https://dsva.slack.com/archives/C0136FJV5R9/p1593190549001000)

## Tasks

- [ ] Tressa and Sandra work together to get the correct copy
- [ ] Tressa design error states

**Comment by sanlouise** [comment]
Error fetching connected applications (first string):

![image](https://user-images.githubusercontent.com/14869324/86942843-e556fc80-c102-11ea-8abc-f4f082791f27.png)

**Comment by tressaellen** [comment]
We need two different error states for connected apps. @kristinagore could you take a look at this copy and let me know if you have any suggested changes?

1. If we cannot fetch current connected apps.

We are unable to retrieve your connected apps
We’re sorry.  Something went wrong on our end and we couldn’t access your connected apps.  Please try again later.

![Screen Shot 2020-07-09 at 9.05.34 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/6ee2442d-408c-4bd5-93a0-f0a4de21a56d)

2. If we cannot disconnect an app.

We are unable to disconnect [app name] 
We’re sorry.  Something went wrong on our end and we couldn’t disconnect [app name].  Please try again later.

![Screen Shot 2020-07-09 at 9.05.41 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/595d9d6a-5d93-4f64-8c3c-1def53737986)

**Comment by tressaellen** [comment]
@sanlouise copy has been approved - so these are good to be built. :)

**Comment by sshein** [comment]
curious about the orange alert versus red for the "unable to disconnect the app" case. If something goes wrong and we can't perform the task, should it be red?

**Comment by tressaellen** [comment]
@sshein - great question, I remember having a conversation with platform long ago about this... and I ended up changing most of the alerts to orange, but I can't remember _why_.  I'll reach out again for a reminder and drop their response here.

**Comment by tressaellen** [comment]
Okay we've got the answer! @sshein - you are correct! The disconnect error should be red. @sanlouise could you be sure to update this in the build?

<img width="823" alt="Screen Shot 2020-07-10 at 9 10 14 AM" src="https://user-images.githubusercontent.com/58752772/87169510-92a15000-c27c-11ea-84bf-9799561808e0.png">

**Comment by kristinagore** [comment]
@tressaellen Looks good! The only thing we'd suggest would be changing the headers of those alerts to:
"We couldn't access your connected apps"
and
"We couldn't disconnect [app name]"
So just "couldn't" instead of "are unable to" for simplicity

**Comment by tressaellen** [comment]
Sounds good - thanks @kristinagore. @sanlouise the updated copy for the alerts should be:

**1. If we cannot fetch current connected apps.**

We can't retrieve your connected apps
We’re sorry. Something went wrong on our end and we couldn’t access your connected apps. Please try again later.

![Screen Shot 2020-07-10 at 11.43.47 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f85c37e9-0e3b-4034-ba37-911e69f55cbe)

**2. If we cannot disconnect an app.**

We can't disconnect [app name]
We’re sorry. Something went wrong on our end and we couldn’t disconnect [app name]. Please try again later.

![Screen Shot 2020-07-10 at 11.44.00 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f15e00d3-da91-4237-a759-65a710c98e92)
