### ISSUE TITLE
Offboarding of Nathan Hruby :(

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#10682]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   >Nathan Hruby .
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VSP Operations, last day is June 26, 2020 please wait till end of day. :( :(, Ad Hoc
- Please provide any type of access they may have. 
  > ex: Nathan will have access to everything. 
  
 
## AC
 - [x] Remove global/config.yml
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] SOCKS Access removed (if applicable) 
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Or
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by wyattwalter** [comment]
Created ticket for Nathan's offboarding from the org: https://github.com/department-of-veterans-affairs/github-user-requests/issues/3162

**Comment by joanneesteban** [comment]
He's been removed from Google Analytics and Domo. I reassigned his Domo datasets to myself and can reassign those to another Ops rep.

**Comment by wyattwalter** [comment]
I think the only thing that's left is DSVA Slack. @KevinMHoffmanUSDS / @drorva is that supposed to go through one of you?

**Comment by drorva** [comment]
Not me :-)

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1593533200024700

**Comment by jbritt1** [comment]
Slack account deactivated by Ric Miller. Marking as complete.

**Comment by ricetj** [comment]
ok looks like this can be closed then.
