### ISSUE TITLE
Standardize onboarding and access for new VSP apps team members

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#107]
## Description

Right now the onboarding process for new developers is different on a per-tool basis and is cumbersome. Credentials are even shared in both directions which makes it difficult. For example: we provide a developer with temporary AWS credentials for them to reset on their own, but we also require them to give us an SSH public key to gain access to some other tools. This back-and-forth makes it difficult to streamline the onboarding, and creates a lot of toil for folks.

This epic should be used to track efforts surrounding onboarding for the initial phases of the VSP project.

## Old stuff

@wyattwalter commented on [Wed Apr 03 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17756)

Need to. update documented procedures to include info we need rather than making people bug us in Slack:

- first/last name
- email
- team membership
- ssh pub key

---

@omgitsbillryan commented on [Tue May 14 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17756#issuecomment-492326458)

Which documented procedures are you referring to? There's a slew of them in `vets.gov-team`:

![image.png](https://images.zenhubusercontent.com/59c291c1b0222d5de4787932/d3efede6-e83c-4523-b76f-7924d7ff0219)

I'm a bit confused about what problem this issue is trying to solve - why do people need to bug us in slack?

---

@wyattwalter commented on [Tue May 14 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17756#issuecomment-492387958)

When I originally wrote it there were some links on the wiki: https://github.com/department-of-veterans-affairs/vets.gov-team/wiki/VA.gov-Onboarding

Will need some more digging to find out where these procedures ended up.

**Comment by gunsch** [comment]
deleted

**Comment by b00klegger** [comment]
Merged this PR:
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/24
with directions for external teams.
