### ISSUE TITLE
Find Forms - Capture an error to Sentry when there are no results for an empty query

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#10708]
When a search is executed on `/find-forms/` without a query (just hitting "search" without typing), there should _always_ be results. If not, this could be an indication of a server problem, so we should capture the error into our monitoring service, [Sentry](http://sentry.vfs.va.gov/), so that we can easily spot the problem.

## Tasks
- [ ] 

## Acceptance criteria
- Error shows up in our logs when a user without a query and doesn't receive results
- Error shows up in our log when 10-10ez is queried with no results

**Comment by MickinSahni** [comment]
Closing this out as we won't be able to validate until an error occurs.
