### ISSUE TITLE
[FE] Add grey title on personal information section

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#10721]
## Background

From an accessibility stand point we need to be consistent with the titles of the 'blocks' on the profile. We need to add a title to the 'personal information' section.

## Specs

Add 'Personal information' title to the personal information block.

![Screen Shot 2020-06-29 at 11.13.32 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/282b8970-a2fc-429b-be8f-eb0375b16615)

## Tasks

- [ ] Update title

**Comment by erikphansen** [comment]
knocking out this little task with this existing PR https://github.com/department-of-veterans-affairs/vets-website/pull/13295

**Comment by erikphansen** [comment]
@tressaellen this can be validated
