### ISSUE TITLE
STEM: Update Introduction page for 10203 form

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10730]
As an applicant, I need information provided regarding what is necessary to complete the application process so that I can be prepared to complete the application in one sitting.

## Assumptions:
1. This work is done behind feature flag #7271.
2. The entitlement alert is not a part of this story.

## Acceptance Criteria
1. The [introduction page](https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction) content and layout matches that as specified in supporting artifact # 2.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040757) as of 07/01.
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ac00ddfc52dd101577639d5bdcf25a720a029fbf/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md#form-title-apply-for-the-rogers-stem-scholarship) as of 07/01.

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13392

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-09 at 11.06.10 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7ff2b88d-3f8e-4f73-8c10-969632860707)
##
![Screen Shot 2020-07-09 at 11.06.17 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bf905431-caf2-4e38-b941-6a0e91b20ae2)
##
[Uploading... Screen Shot 2020-07-09 at 11.06.23 AM.png ]

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9326&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam @JenLJ and I took a look, and this work checks out on our end.

**Comment by sonntag-adam** [comment]
Closing story
