### ISSUE TITLE
Pension Rewriting: SME feedback edits, publish

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#10737]
# User story

As a Veteran or survivor with a pension under the older laws, I want to be able to easily find my current pension rate.
This is follow-up to #8362 . This ticket will be actionable with SME feedback is received. The goal is to incorporate changes, and make ready for publish

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**
- [x] Draft page and build in GitHub
- [x] Strategy/voice/organization review
- [x] Managed editor review
- [x] Packaged with rewriting review instructions and sent to SMEs
- [x] SME feedback received

**Steps needed to complete this work now:**
- [x] Incorporate any additional SME feedback, and capture SME approval in documentation (Beth, Randi)
- [x] Publish in drupal and update left nav link
- [x] Re-start redirect process in [issue #2212](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2212) at this time (when rewritten page is ready & approved) (Selina)

## Information and files for reference

- **SME as of July 2019:** Alfreda Smith (Angie)

- **SME feedback:** Angie is concerned that users will miss reading the conditions information around income limits if it's not directly in the tables, as it appears on the legacy page.

- **Issue #18514 capturing this work originally:** https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18514

- **PR:** https://github.com/department-of-veterans-affairs/vagov-content/pull/448

- **Page in Github:**  https://github.com/department-of-veterans-affairs/vagov-content/blob/content-WIP-rewriting-pension/pages/pension/protected-pension-rates.md

- **Heroku link:** https://github.com/department-of-veterans-affairs/vagov-content/pull/448

- **PDF sent to SMEs:** [Brand Consolidation Content Rewriting_Protected Pension Rates_6.24.19](https://app.zenhub.com/files/31788863/22caeffe-0a48-45ea-b6f5-5b17058c1a2d/download)
- **Drupal preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=5090

## Acceptance criteria

- [x] Assigned to milestone
- [x] Assigned to epic
- [x] "Content" and "vsa-public-websites" labels added

### Definition of done

- [x] Page approved by appropriate SMEs and published in Drupal

**Comment by MickinSahni** [comment]
Pulling into Ready until ready to complete

**Comment by bethpottsVADEPO** [comment]
Talked to SME, Angie Smith. She has one change she wants us to make to the language in the charts. And there's one correction to make on the page as well. 

Angie's response:
I have one concern with the sentence “Your yearly income must be $13,696 or less to receive this benefit”.  I know you felt making this a sentence was better, but here is my concern; I don’t’ think we need the part “to receive this benefit”. But if we keep this part I think it should be, “Your yearly income must be $13,696 or less to continue receiving this benefit”. 

And she said yes to this question:
Should the year 2014 actually be 2019? I’m wondering if this is a typo and we should use the year 2019 on the new modern page. 

I'll make these updates today or tomorrow so we can get this wrapped up this sprint.

**Comment by bethpottsVADEPO** [comment]
@RLHecht I forgot to make a drupal note when I updated the above with the wording, "to continue receiving" but you'll see that wording in each chart. Have you ever done a full proofread on this rewritten page? I think you have, but if not, that's next. Then this page is ready to publish!

I added to the task list above (before the redirect process starts): Publish in drupal and update left nav link.

After you publish, let me know and I'll open the redirect ticket.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis  We're going to put this modern protected pension rates page live tomorrow. I see this url on your legacy redirects spreadsheet: pension/protected-pension-rates/

Randi will change the left nav link currently linking to the legacy page to our new page with the above url. All sound good? Are we missing any steps?

**Comment by mnorthuis** [comment]
That is the correct URL so it can go live whenever you are ready.  The link will need to be changed on the hub page and the left nav.  

There is a redirect issue for the legacy page here:https://github.com/department-of-veterans-affairs/va.gov-team/issues/2212.  so the redirect can be pushed through once the new page is live.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis I'm not seeing a link to Protected pension rates on the hub. Where is that?

**Comment by RLHecht** [comment]
@bethpottsVADEPO It's under the More Information and Resources section: 
<img width="762" alt="Screen Shot 2020-07-17 at 12 10 29 PM" src="https://user-images.githubusercontent.com/48728214/87807653-83934280-c826-11ea-90c3-03eecd3c7275.png">

**Comment by bethpottsVADEPO** [comment]
@RLHecht Thanks! I was, stupidly, looking in the disability hub.

**Comment by RLHecht** [comment]
Page is live on site. Closing ticket! FYSA @MickinSahni
