### ISSUE TITLE
Request accessibility/508 review for Direct Deposit

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1073]
## Team Name

Authenticated Experience

## Product Description

Port eBenefits Direct Deposit Functionality into VA.gov

## Staging URL and Credentials

https://staging.va.gov/my-va/
LOA3 with 2FA: Sign in with any staging user and navigate to the profile.
LOA3 without 2FA: Will be promted to setup 2FA before accessing.
LOA1: Create an account on staging and navigate to the profile. You will see a prompt to verify your identity since the profile is only available to users who have verified their identities.

## Known Issues

[508 Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=508%2FAccessibility&template=508-issue.md&title=)

- **Related Issue URL:** _Delete if no known issues._

**Comment by 1Copenut** [comment]
@Samara-Strauss @Justin-Pickett I've completed this audit, and logged issues under the [Direct Deposit 508 Epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1329)

6 issues logged, and I have 1 for the design system that will be an improvement for this app as well. Thank you!

**Comment by Samara-Strauss** [comment]
Great! Thank you so much, @1Copenut!
