### ISSUE TITLE
Add question for Hawaii

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#10734]
AC:
- [x] "SCREEN459" returns message that includes www.va.gov/covid19screen/459
- [x] `www.va.gov/covid19screen/459*` loads question text from [hi-custom-question.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4859787/hi-custom-question.xlsx)
- [x] `covid19screen/459GH` shows custom 459GH facility question
- [x] `covid19screen/459gh` shows custom 459GH facility question
- [x] answer options are "Yes" and "No"
- [x] user selection of "Yes" results in "more screening" result

**Comment by batemapf** [comment]
Updated above w/ content from HI. Definitely want @DanielleThierryUSDSVA to take a look at it. Also updated facility ID in url. Also added SMS AC, which is already complete :-).

**Comment by batemapf** [comment]
content and facility ids are here: [hi-custom-question.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4859787/hi-custom-question.xlsx)

**Comment by mchelen-gov** [comment]
PR merged

**Comment by batemapf** [comment]
@mchelen-gov looks like this is capitalization sensitive. To recreate:

- Navigate to staging.va.gov/covid19screen/459GH
- Click through to last question
- Observe custom question for facility 459GH
- Navigate to staging.va.gov/covid19screen/459gh
- Click through to last question
- Custom question for facility 459GH is missing

This doesn't have an impact if folks are using the QR or SMS short code. However, if users are typing the URL in directly, this could definitely trip them up.

**Comment by mchelen-gov** [comment]
WIP PR for case insensitive route: https://github.com/department-of-veterans-affairs/vets-website/pull/13403
