### ISSUE TITLE
Facility Locator Mobile experience

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10749]
## What happened?
The search box and content on the main Facility Locator page is partially cut off in Staging. 

![Screenshot_6_29_20__4_15_PM](https://user-images.githubusercontent.com/55411834/86058804-afd55380-ba1e-11ea-8d4e-bfcc89d183a5.png)

Was determined to be introduced VSP's dependabot version change. Our dependency was bumped from 0.4.1 to 1.1.1 without us knowing. 
<img width="930" alt="Screen Shot 2020-06-29 at 3 43 25 PM" src="https://user-images.githubusercontent.com/55411834/86058428-1dcd4b00-ba1e-11ea-9446-b04ee1d39cd7.png">

Reverting to original version, fixed the issue

<img width="1015" alt="Screen Shot 2020-06-29 at 3 41 40 PM" src="https://user-images.githubusercontent.com/55411834/86058312-eced1600-ba1d-11ea-92da-6b96340da931.png">

## Acceptance Criteria
- [ ] All content is visible when viewed in mobile or zoomed. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brangi** [comment]
@mmiddaugh We should not revert back the version but will be fixed with PR https://github.com/department-of-veterans-affairs/vets-website/pull/13319
