### ISSUE TITLE
STEM form: Typo and out-of-order checkboxes in Chapter 2

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#10744]
The second chapter of the 10203 STEM form is a single page with a single question. The possible answers to this question are in the form of a series of checkboxes.

The question should read as "Which benefits have you used or are you currently using?", but currently reads as "Which benefit have you used or are currently using?". There are two errors:
1. The word "benefit" should the plural "benefits"
2. The word "you" is missing between "are" and "currently"

The answers are all correct, however, the last two are in the incorrect order. The expected order is as follows:
- Post 9/11 GI Bill (Chapter 33) Learn more
- Fry Scholarship (Chapter 33) Learn more
- Montgomery GI Bill (MGIB-AD, Chapter 30) Learn more
- Montgomery GI Bill Selected Reserve (MGIB-SR, Chapter 1606) Learn more
- Transfer of Entitlement program (TOE) Learn more
- Post-Vietnam Era Veterans' Educational Assistance Program (VEAP, Chapter 32) Learn more

![Screen Shot 2020-06-29 at 4.07.37 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/71b409e1-8311-4b9e-a096-7a6219d4dbde)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13325

**Comment by delli-gatti-michael** [comment]
local testing complete - LGTM
![Screen Shot 2020-06-30 at 11.50.01 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4898e4fd-9fb2-44c4-928a-8a3e8f4c9e0c)

**Comment by delli-gatti-michael** [comment]
This is now on Staging. Closing this issue
