### ISSUE TITLE
Find a VA Form: Apply result weighting and rank based on relevance to search term

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10754]
### Feature enhancement: display forms search results by relevance based on form number or form title/name

**User story:** 
When I search for a form by number (e.g., 526ez) or by form title or part of the form title (e.g., "hearing aid batteries"), I want to see the most closely matching results on the first page and preferably at the top of the first page of results. 

**Problem statement:**
Today, the forms in the search results appear in random order, so that it's hard to locate the ones that most closely match your search query. The form that has the closest matching query term in its name or number might appear on page 2+, making it unlikely that the user will find the form they may be looking for even though the search results included it. 

Per this [comment](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8054#issuecomment-620642822): 
>We do have control over the sort order, but there isn't a "weight" or indicator of how popular a form is. We can sort by form number or form title, ascending or descending.

FYSA @mnorthuis  @MickinSahni 

### **Questions to answer before prioritizing this:**
* How are we measuring "closely matching results" right now? 
  - potential metrics: Average number of refinements, average pagination (i.e. how far do people need to page before finding their search result), download conversion rate
* What other attributes do we want to include to improve relevance when someone searches e.g. "Related to"?
  * Mental model is aligned with very specific form numbers or titles so how much value would we even get?

### Other background info: 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/19012#issuecomment-774155887

Research & Support search logic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/16916

**Comment by ncksllvn** [comment]
This is a tricky one, technically speaking. What would be the ideal way for us to weight the results? In Drupal, we could possibly add a "weight" field, where a weight of 1 would indicate that this result should be at the top of search results; 2 being just under that; and so on. We would need the Lighthouse API to be integrated with Drupal though for that data to carry over to the search app.

**Comment by ncksllvn** [comment]
Adding "blocked" to indicate that this is not actionable on the FE until we've determined a strategy for weighing results that is then reflected in the forms data.

**Comment by jenniferlee-dsva** [comment]
Thanks for flagging @ncksllvn . I think the overarching search strategy will come in 2021, led by @johnhashva . 

I'll note a few tactical things here for consideration as part of improving forms search relevance: 
- **Account for variable hyphens and spaces in queries:** Currently when someone searches on a specific form number, they have to get everything exactly right - if the hyphen is in the wrong place, the search will bring up NULL results. This is one way that we could help improve search - to enable relevant form to be brought back - e.g., the 10-10EZ - whether the user enters "1010ez" / "1010-ez" / "1010E-Z" OR for the 21-526ez, whether someone enters "21526" / "21-526" / "21526ez" / "21-526-ez" / "526-ez" / "526EZ" / so on. 

- Another tactical way that forms search could be improved is by including word pairs that are used inside the forms themselves - the form name, form instructions. This would need to be a little bit smart and not bring up any form with the word "application" like the legacy Microsoft SQL based search did. 

My immediate 2 cents for you and @johnhashva to consider.

**Comment by MarciMcGuireGCIO** [comment]
Assigned to new Decision Tools team; removed Public Websites and PW engineers as assignees

**Comment by MarciMcGuireGCIO** [comment]
Moving this to a separate "Enhance Search Results" Epic that will be released after the search results page is joined to the form detail pages.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO this does not look like it is blocked anymore?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel - Nick added this https://github.com/department-of-veterans-affairs/va.gov-team/issues/10754#issuecomment-696186906 -- do you know if that condition has been resolved?

**Comment by zacharymorel** [comment]
Oh no, it does not look like it has been resolved. I assume we need to have a discussion about this.

**Comment by ncksllvn** [comment]
It's hard to say. I read this ticket like if someone searches "health" then 10-10EZ should always pull up first because it's most likely what the user is looking for. I think we would need a "weight" field for each form so that an editor can express to the front-end how the form should be ranked.

On the other hand, if we're saying a user searches for "hearing aid batteries" then we have more to work with - maybe if a form title matches all three words, then we can rank that form more highly, followed by forms w/two matches, followed by those w/only one.  I think this is something that can be done as a front-end sort so this is actionable. I'm just not sure if this would give us everything we want.

**Comment by zacharymorel** [comment]
So in the following case I can see as an easy win. 
Granted, whatever search "10-10EZ" returns for, it will be weighted towards the top I suspect? 
 
> It's hard to say. I read this ticket like if someone searches "health" then 10-10EZ should always pull up first because it's most likely what the user is looking for. I think we would need a "weight" field for each form so that an editor can express to the front-end how the form should be ranked.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I will come up with some logic that we may be able to start from (I was a Business Analyst for 7 years).   Looking at the API documentation https://developer.va.gov/explore/vaForms/docs/vaForms?version=current, I have some ideas that we can try out in a Discovery sprint.

**Comment by MarciMcGuireGCIO** [comment]
Closing; this is being done in this Epic - > https://github.com/department-of-veterans-affairs/va.gov-team/issues/21639
