### ISSUE TITLE
Access for Jose Costa

### ISSUE THREAD

**Issue by jcosta-gcio** [department-of-veterans-affairs/va.gov-team#1076]
@department-of-veterans-affairs/vsp-operations 

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Jose Costa (JOE)
- VSA Team, Lead Engineer, Government CIO - GCIO.
-What is the **public** SSH key? 
>[id_rsa_vagov.pub.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/3541926/id_rsa_vagov.pub.zip)

>ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGqKk2sxKOsPhLTxrGJdLQH1vDi5oDeLDr9jF9hv89gpeLdy3iM/EWruvnYrNgYYrdNHS2zFiDEu0/LWY/YLNMfxy5scfBDycn4EHoStHNVG2jkJDnODOId6NkSqHgxVwxEHeAcPAavsS7dqNPfaXPh0laUcaEv/TfXmYbSZEkfC/oR27Ynyih9LvmwQzyp40WlmsVdL6t9eZdsNp22esoauMUJCKyC6hDytTFXwkz1ppPK3Jxr7f1mKNeapWP+DL8ygE872xg3KfQKz6ezn6fVrCXFGPgh3gwYbdWPBzDOdKpFzh3tgvm6V4FwMffINKDC4tcXkzp+1fCYi4PdAJD josecosta@jcosta-gcio.local
- [Grant AWS Console access?]
  > YES

**Comment by jcosta-gcio** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by b00klegger** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Jose Costa

**Comment by Jeff-Hayter** [comment]
@b00klegger Mary tells me Jose's paperwork is still with his previous VA contract.  He needs to have that COR transfer all of that documentation to Mary.

**Comment by jcosta-gcio** [comment]
@Jeff-Hayter Do you know who I have to contact to get that paperwork transferred ?

**Comment by jcosta-gcio** [comment]
@b00klegger @Jeff-Hayter  The paperwork should have been transfer already

**Comment by Jeff-Hayter** [comment]
@b00klegger Confirmed.  Please grant access.

**Comment by tskinn** [comment]
This should be done with 
- [x] https://github.com/department-of-veterans-affairs/devops/pull/5457
- [x] https://github.com/department-of-veterans-affairs/devops/pull/5458
