### ISSUE TITLE
[09/30] Redirect Request: Agent Orange consolidation

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10768]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description

Based on content strategy and IA recommendations from Mikki and Danielle, the PW websites team is working to consolidate and streamline the Agent Orange section within the Disability benefits hub. The information below reflects the associated redirects that we'll need in coordination with this work.

### Requestor team info
**Team:** Public websites
**Primary contacts:** Danielle Thierry, Beth Potts, Selina Cooper

### Implementation date
**Date new URL(s) will be live:** We're hoping for end of PW sprint 25 (July 14) or early in PW sprint 26. But date not confirmed: This will happen in coordinate with issue [#10765](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10765)

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [x] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

These URLs should redirect to https://www.publichealth.va.gov/exposures/agentorange/benefits/registry-exam.asp

www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/registry-health-exam/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/registry-health-exam/

The following URLs should all redirect to www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/

www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/related-diseases/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/diseases/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/non-hodgkins/
www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/c-123-aircraft/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/c-123/
www.benefits.va.gov/compensation/agentorange-c123.asp
www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/navy-coast-guard/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/water-vietnam/
www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/service-in-vietnam-korea/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/service-inside/
www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/testing-storage-areas/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/test-storage/
www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/thailand-military-bases/
www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/thailand-military-bases/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by DanielleThierryUSDSVA** [comment]
@lunascoop @bethpotts Added you both to this issue for awareness. No action needed at this time. Thank you!

**Comment by mnorthuis** [comment]
I updated the list above to also include URLs that are currently redirected to the pages we are eliminating - there about 8 legacy vets.gov URLs and 1 legacy benefits.va.gov url. 

Eventually I hope to retire these older redirects, but not ready to quite yet, so we need to eliminate the double jump. 

This list is vetted and ready to be implemented when your team is ready.

**Comment by MickinSahni** [comment]
@DanielleThierryUSDSVA is this ready for a dev to implement?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. No. This won't be ready for a little while. I'll make sure to coordinate with content being ready/approved. Thanks!

**Comment by MickinSahni** [comment]
> Hi @MickinSahni. No. This won't be ready for a little while. I'll make sure to coordinate with content being ready/approved. Thanks!

Oh gotcha. I'm removing it from this sprint's commitments until we're ready to go. Thanks, Danielle

**Comment by lunascoop** [comment]
Hi @bethpottsVADEPO these pages are ready for redirect implementation. Could you find out the appropriate stakeholders the the legacy URLs listed above? Thanks

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop @bethpottsVADEPO . The SMEs we worked with for this are Paul Shute, Shawn Graham, and Sandy Tadeo.

**Comment by lunascoop** [comment]
Thanks @DanielleThierryUSDSVA I'll send out the stakeholder communications today regarding the legacy redirects. It will be scheduled for **09/30**. cc: @bethpottsVADEPO @kelsonic @ncksllvn

**Comment by kelsonic** [comment]
Just confirming, are the redirects in the ticket description ready for implementation? 🙂

**Comment by kelsonic** [comment]
Confirmed that it's ready to be worked on by @lunascoop, will send up a PR for this shortly but won't merge until 9/30!

**Comment by kelsonic** [comment]
There are 2 redirects I'm concerned with:

https://github.com/department-of-veterans-affairs/devops/pull/7672#discussion_r496168526

https://github.com/department-of-veterans-affairs/devops/pull/7672#discussion_r496168608

Not sure if we can implement those but getting confirmation from devops 🤔

**Comment by lunascoop** [comment]
@kelsonic I checked w/ @ncksllvn via Slack (https://dsva.slack.com/archives/C52CL1PKQ/p1600717229062400) and it seems that we can. Don't know if this helps.

**Comment by kelsonic** [comment]
Oh nice! Hopefully my implementation works then! 🤞

**Comment by kelsonic** [comment]
PR is merged, will be deployed with the daily deploy today + devops manual deploy

**Comment by lunascoop** [comment]
Confirmed that these redirects have been implemented. Closing ticket and updating stakeholders.
