### ISSUE TITLE
STEM: Add Entitlement Remaining alert to 10203 introduction page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10774]
As an applicant, I need to view my remaining entitlement while completing the 10203 so that I can determine if I should complete the application based on my eligibility.

## Assumptions:
1. This work is done behind feature flag #7271.
2. The alert requires for the user to be authenticated.
3. The remaining entitlement data is retrieved using the EVSS service documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/statement-of-benefits/gibs-2017-07-06.yaml)

## Acceptance Criteria
1. The alert contains the following content:

> **You may not be eligible**
> Our entitlement system shows that you have more than 6 months of education benefits remaining.
> 
> To be eligible for the Rogers STEM Scholarship, you must have less than 6 months of Post-9/11 GI Bill benefits left when you submit your application.
> 
> Months you have left to use: **[X] months, [Y] days**

2. The amount of time left (**[X] months, [Y] days**) displays the data returned by the EVSS service.

3. The alert is: 
    a. Displayed when the service is available and the user has 181 days or more of remaining entitlement
    b. Displayed on the Introduction page (https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040759)
    c. Background color is #f1f1f1.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040757) as of 07/01
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ac00ddfc52dd101577639d5bdcf25a720a029fbf/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md) as of 07/01

**Comment by elder-joseph** [comment]
Associated Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/13453

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-15 at 12.57.10 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d9053015-8ec0-4419-a89d-1d772dae4de8)
##
![Screen Shot 2020-07-15 at 12.57.21 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9bcd1acb-7d80-404d-9e4e-6e84269ce4d0)

**Comment by sonntag-adam** [comment]
Blocked as we don't have staging users for recent enrollment information and entitlement remaining alert.

**Comment by dneel-bah** [comment]
EDU has agreed to launch with an MVP without pulling entitlement / enrollment data from EVSS.  The re-validation of AC3 in staging will be handled in #12734 once the test data is available in the staging environment.  Closing this story
