### ISSUE TITLE
Writing ticket for prototype: Burials learning center articles

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10778]
### Writing ticket for prototype: Burials learning center articles

**AC:**
- [ ] Draft content ready for Liz to use for her prototype
- [ ] Content is in  formats using new LC templates, a mix of formats

**Burials and memorials learning center articles**
_The following burials LC articles are already mocked up in Ryan's wireframe. @jenniferlee-dsva just needs to provide the draft copy in the LC template copydeck format, if @andaleliz can't grab copy from the Sketch files._ 

1. Veterans Legacy Program
2. How much does VA pay for funderal expenses?
3. How we assign SMC levels
4. Emblems of belief
5. Burials benefit FAQs
6. What do I do if the headstone inscription is incorrect?
7. Checklist for scheduling a burial at a national cemetery

**Not mocked up:**
NCA video list template -- this one is not already mocked up. @jenniferlee-dsva  will provide

-------
**References:**

[Copydeck template for LC prototype content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy/template-copydeck-learning-center-draft.docx)

[Complete list of mvp prototype content](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy#list-of-content-articles-for-the-first-mvp-prototype-user-research-session)

[LC template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md)

This work is needed to implement [ticket 10393 Create prototype for testing](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10393).

**Comment by jenniferlee-dsva** [comment]
@andaleliz - [Ryan's LC wireframes ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b) currently already have all but one of these burial LC articles as example content. 

Do you need me to provide the copy for those as a copydeck, or can you grab them from the original Sketch files?

**Comment by andaleliz** [comment]
I can grab everything from the Sketch files, no need to put them in a copy deck if the content is already there.

**Comment by jenniferlee-dsva** [comment]
Given our latest discussion about what we need for the actual prototype tasks, we might not need anything in this ticket except the Burials tagged list of LC search results page -- which is available in Ryan's sketch files here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-Learning-center-template.sketch

TBC sync with Liz on Tuesday. 

@andaleliz

**Comment by andaleliz** [comment]
I put a list of the pages we need so far in our status/decisions document. It's in the Decisions section from the notes on our 6/30 meeting.  Maybe this will be helpful to clarify what does/doesn't need to be written?

I'll update the list once we meet tomorrow and discuss any additional pages we need.

**Comment by andaleliz** [comment]
Based on our meeting today, I believe we don't to do the work outlined in this ticket.

**Comment by MickinSahni** [comment]
Closing as won't do
