### ISSUE TITLE
Writing ticket for prototype: VA.gov account and profile learning center articles

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10775]
### Writing ticket for prototype: VA.gov account and profile learning center articles

**AC:**
- [x] Draft content ready for Liz to use for her prototype
- [x] Content is in  formats using new LC templates, a mix of formats

**VA.gov account and profile articles needed for user test**

1. Sign in FAQs [already exists - just putting it into LC template]
2. Change your address on file with VA - FAQs or About? 
3. How to change your address online - step-by-step with screenshots [this is already in a subway map, but just need screenshots - this is basically pulling out the online process component as its own LC article] 

-------
**References:**

[Copydeck template for LC prototype content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy/template-copydeck-learning-center-draft.docx)

[Complete list of mvp prototype content](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy#list-of-content-articles-for-the-first-mvp-prototype-user-research-session)

[LC template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md)

This work is needed to implement [ticket 10393 Create prototype for testing](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10393).

**Comment by jenniferlee-dsva** [comment]
@DanielleThierryUSDSVA - I'm unassigning you for now; I'll provide draft of these to Liz, as I'd like to get moving on part of the protoptype.

**Comment by jenniferlee-dsva** [comment]
I'm uploading draft va.gov account/profile copydeck for Liz's prototype. There's one article that I need help with - the 'how do I change my VA address online' article which has placeholders for screenshots. 

@bethpottsVADEPO  - could you assign out as a subtask to add screenshots for that one? Also if the 'verify your identity' step is actually multiple steps, would be good to break those out more granularly. 

[Account-profile-copydeck-learning-center-070620.doc](https://app.zenhub.com/files/133843125/43de3eba-b11b-426a-bf46-6004f3202318/download)

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva Will do. Checking the team's capacity and will assign it out here.

**Comment by andaleliz** [comment]
Is this the [sign in FAQ page](https://www.va.gov/sign-in-faq/) you referenced that already exists? If so, just as an FYI I can use the existing page to capture the headings + accordion titles for the prototype, so you don't need to include those in the documents you create for me. Would need the following from the content team:
- topic and audience tag
- what, if any, CTAs, you'd want to put on the page (the [LC template example](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b?wid=0-1588252280345) has 2 CTAs on the multiple FAQ page)
- confirm that the accordions would be closed by default per the current accordion component, and not all open as shown on the LC template
-  Need help + related articles content

**Comment by jenniferlee-dsva** [comment]
>If so, just as an FYI I can use the existing page to capture the headings + accordion titles for the prototype

Great. 

>from the content team:
topic and audience tag
what, if any, CTAs, you'd want to put on the page (the LC template example has 2 CTAs on the multiple FAQ page)
confirm that the accordions would be closed by default per the current accordion component, and not all open as shown on the
LC template
Need help + related articles content

I will provide those in a  copydeck. (Beth is assigning out for a different LC task - screenshots for the step-by-step.) I'm assuming you prefer it all together in one deck? I'm also fine Slacking you content in chunks as you're working. Just LMK.

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva I just uploaded a Word doc with all the screen shots to this issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11022

**Comment by jenniferlee-dsva** [comment]
This is complete and content uploaded to GH and incorporated into Liz's prototype for user test.
