### ISSUE TITLE
FE BUG: "you have unsaved edits" sometimes shown when it shouldn't be

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#10776]
- Edit a phone number
- Save the change
- Try to leave the Profile
- Boom: you are told you have unsaved edits

This seems to only affect phone numbers, not addresses or email address

![warning.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/13577cf7-6ad4-47a3-9ffd-07b5b604b3fd)

**Comment by sanlouise** [comment]
After successfully saving an edited phone number, a bunch of actions are fired that should be fired. `hasUnsavedEdits` is set to true when UPDATE_PROFILE_FIELD is called, causing this bug.

![image.png](https://images.zenhubusercontent.com/5e9d15aab51cccb259a8a6c7/0f567c8c-299e-449c-8f2e-567bf235dfcd)

**Comment by sanlouise** [comment]
@mshea0606 Could you validate in staging that this is good to be closed? This bug should have been resolved with [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13459). Thank you

**Comment by mshea0606** [comment]
@sanlouise @erikphansen this has been fixed. Looks good. Closing it out.
