### ISSUE TITLE
Writing ticket for prototype: Disability learning center articles

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10777]
### Writing ticket for prototype: Disability learning center articles

**AC:**
- [x] Draft content ready for Liz to use for her prototype
~- [ ] Content is in  formats using new LC templates, a mix of formats~
- [x] LC page has 2 CTAs: File a claim + How to file a claim 

**Disability learning center**
Agent Orange page (either as individual LC pages or as one consolidated LC page)

Source:
/disability/eligibility/hazardous-materials-exposure/agent-orange/
/disability/eligibility/hazardous-materials-exposure/agent-orange/registry-health-exam/
/disability/eligibility/hazardous-materials-exposure/agent-orange/related-diseases/
/disability/eligibility/hazardous-materials-exposure/agent-orange/service-in-vietnam-korea/
/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/
/disability/eligibility/hazardous-materials-exposure/agent-orange/thailand-military-bases/
/disability/eligibility/hazardous-materials-exposure/agent-orange/c-123-aircraft/
/disability/eligibility/hazardous-materials-exposure/agent-orange/testing-storage-areas/

-------
**References:**

[Copydeck template for LC prototype content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy/template-copydeck-learning-center-draft.docx)

[Complete list of mvp prototype content](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy#list-of-content-articles-for-the-first-mvp-prototype-user-research-session)

[LC template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md)

This work is needed to implement [ticket 10393 Create prototype for testing](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10393).

**Comment by jenniferlee-dsva** [comment]
@DanielleThierryUSDSVA  @bethpottsVADEPO - updated list with just the disability topic pages we will test with. Since you're already working on the draft consolidated AO page, we can use that draft to put in a LC template format.  (If the consolidated draft isn't ready now, feel free to just pick one of the source pages into the format.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz Here's a copy deck with the content for this page. Just let me know if you have any questions! 
[LC content_multiplefaqstemplate_agent orange_7.13.20](https://app.zenhub.com/files/133843125/649339c7-53f4-4702-9130-0407cfeca8b7/download)

FYSA @jenniferlee-dsva

**Comment by andaleliz** [comment]
Thanks Danielle! I'd like to confirm the alert box style you refer to in the beginning of the doc - is it the [informational alert](https://design.va.gov/components/alertboxes#informational-alert)?

**Comment by DanielleThierryUSDSVA** [comment]
Yes, informational alert. Thanks, @andaleliz!

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA [here's the page in InVision](https://vsateams.invisionapp.com/share/92Y27YZQCAR).  Would you please give it a look when you have a moment and let me know if the content translated as you expected?

I wasn't sure how the `on this page` and first set of CTA buttons fit in with the information alert, so I placed the alert between them.  Thinking here is that: 
- the CTAs would always be consistently placed with the intro text so they don't lose context
- The information in the alert is important enough that we don't want to encourage people to skip it via the `on this page` links right away.

Also, section 3 has 2 Q&A's, but the doc has them labeled as `1 of 5` and `2 of 5`. Are 3-5 intentionally missing?

**Comment by DanielleThierryUSDSVA** [comment]
This looks great, @andaleliz!

1. I think your thinking on this makes sense, yes.
2. Yes, just an error. Thanks!
3. I agree with you on just linking the phone numbers. I thought I'd seen that in the template designs.

**Comment by jenniferlee-dsva** [comment]
this is complete, so closing
