### ISSUE TITLE
508-defect-1 ❗ Launchblocker [ZOOM, MOBILE]: Content MUST not be cut off when magnified

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#10783]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

When zoomed to 200–400%, the form doesn't wrap, is cut off. "Can't find what you're looking for…" sentence is cut off, as well is the attribution text.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a mobile phone user, I want to view all of the content within the viewport so that I may make informed decisions.

## Environment

* Operating System: all
* Browser: all
* Server destination: production

## Steps to Recreate

1. Enter https://www.va.gov/find-locations in browser
2. Enter a valid Zip code in the first form input
3. Verify that the form is cut off as shown in the screenshots

## WCAG or Vendor Guidance (optional)

* [W3C Understanding Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)

## Screenshots or Trace Logs

**Zoom to 200%:** 
    ![Screen Shot 2020-06-29 at 5 40 40 PM](https://user-images.githubusercontent.com/57469/86059237-583fe380-ba30-11ea-87a8-8212017f8579.png)
    ![Screen Shot 2020-06-29 at 5 46 13 PM](https://user-images.githubusercontent.com/57469/86059310-7c9bc000-ba30-11ea-8b44-58bb172fc132.png)
    - Zoom to 300%: 
    ![zoom-to-300-a](https://user-images.githubusercontent.com/57469/86060717-56c3ea80-ba33-11ea-860f-1b79167c7cbc.png)
    ![zoom-to-300-b](https://user-images.githubusercontent.com/57469/86060727-59bedb00-ba33-11ea-9b2f-a26fa0cf76c6.png)

**Zoom to 400%:** 
    ![zoom-to-400-a](https://user-images.githubusercontent.com/57469/86060793-807d1180-ba33-11ea-897e-13c4f68372f1.png)
    ![zoom-to-400-b](https://user-images.githubusercontent.com/57469/86060805-84109880-ba33-11ea-89b2-c0d399f7fafc.png)
    ![zoom-to-400-c](https://user-images.githubusercontent.com/57469/86060810-87a41f80-ba33-11ea-93e6-1e8b5e8da3a0.png)

**Comment by 1Copenut** [comment]
Same comment on this issue as my comment on #10782 regarding [differences in behavior on mobile devices and zoomed browsers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10782#issuecomment-653069795).

**Comment by mmiddaugh** [comment]
We are preparing to move the "Can't find…" in the next iteration (in design now). Adding this as acceptance criteria for that implementation [#11460](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11460)

**Comment by mmiddaugh** [comment]
Can't find.... was recently moved to below the map and is now fully visible in mobile. 

@jenstrickland this is ready for your validation, please.

**Comment by jenstrickland** [comment]
This is still an issue in the new location.

![Screen Shot 2020-07-30 at 7 56 38 PM](https://user-images.githubusercontent.com/57469/88985639-ccbfa980-d29e-11ea-8b22-d2dd08263c3a.png)

**Comment by mmiddaugh** [comment]
@jenstrickland this one is ready for your review when you are available.

**Comment by jenstrickland** [comment]
Apart from the issue commented on https://github.com/department-of-veterans-affairs/va.gov-team/issues/8414, this is good. I'll close this Launchblocker item since this is more about the search button cut off.
