### ISSUE TITLE
508-defect-1 ❗ Launchblocker [MOBILE]: In mobile view, content MUST not be cut off 

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#10782]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

On mobile, the search form, "Can't find…", and pagination are all cut off at 100% (see screenshots). Content **must** not be cut off, especially in the 100% default state.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a mobile phone user, I want to view all of the content within the viewport so that I may make informed decisions.

## Environment

* Operating System: iOS
* Browser: Safari
* Server destination: production

## Steps to Recreate

1. Enter https://www.va.gov/find-locations in browser
2. Enter a valid Zip code in the first form input
3. Verify that the form is cut off as shown in the screenshots

## WCAG or Vendor Guidance (optional)

* [W3C Understanding Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)

## Screenshots or Trace Logs

![100-a](https://user-images.githubusercontent.com/57469/86163329-166d7680-bade-11ea-8519-c8fb02afabe1.PNG)

![100-b](https://user-images.githubusercontent.com/57469/86163343-1a00fd80-bade-11ea-9f0a-76bdd1c597de.PNG)

![100-c](https://user-images.githubusercontent.com/57469/86163359-1e2d1b00-bade-11ea-8e27-8ce5d03326e1.PNG)

**Comment by 1Copenut** [comment]
I agree with @jenstrickland about this item. The interface seems to respond correctly with a tabbed approach when I'm checking on a mobile device, but doesn't respond properly when I zoom layouts using my browser zoom.

**Comment by mmiddaugh** [comment]
We are preparing to move the "Can't find…" in the next iteration (in design now). Adding this as acceptance criteria for that implementation [#11460](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11460)

**Comment by mmiddaugh** [comment]
@1Copenut if you are available to validate this one, I think our responsive design changes will have resolved the issue.

**Comment by 1Copenut** [comment]
@mmiddaugh I confirmed this in Chrome using the mobile emulator and an iPhone 8. Both behaved correctly. Moving this issue to close.
