### ISSUE TITLE
Full Accessibility & 508 Office Audit for Comparison Tool Estimate Your Benefits updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10786]
## Steps to complete the Full Accessibility & 508 Audit: 
- [x] Product Manager: create issue and fill in feature name in the title and other bolded information appropriately
- [x] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts when you request a full review_
- Access information for the tool or feature in staging
   1. Navigate to the [Comparison Tool on staging](https://staging.va.gov/gi-bill-comparison-tool)
   2. Search for a Schools or VET TEC institutions 
   3. Select a school or institution
   4. On the school or institution "profile page" the first accordion is "Estimate your benefits"
- Link to accessibility test cases:
   - https://dsvavsp.testrail.io/index.php?/cases/view/671&group_by=cases:section_id&group_order=asc&group_id=46
   - https://dsvavsp.testrail.io/index.php?/cases/view/672&group_by=cases:section_id&group_order=asc&group_id=46
   - https://dsvavsp.testrail.io/index.php?/cases/view/670&group_by=cases:section_id&group_order=asc&group_id=46

## Additional Notes
As part of this review, VSP will send your product to VA's 508 office for approval (as applicable)

**Comment by dneel-bah** [comment]
@1Copenut Checking in on this issue; should it still be open or can it be closed out?

**Comment by 1Copenut** [comment]
@desireeturner I need to keep this one open. It slipped under my radar, so I'll get an audit taken care of promptly and sent to the VA 508 office. We have 5 known issues, with work being done on 2  per comments this morning, and 1 more that I might be able to close in testing: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-product-review-list.md#gi-bill-estimate-your-benefits

**Comment by dneel-bah** [comment]
@1Copenut Can this issue be closed out?

**Comment by 1Copenut** [comment]
@dneel-bah Yes, this one appears complete. I'll move it to closed.
