### ISSUE TITLE
[FE] - Create documentation regarding how to setup/use feature flags

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#10791]
## Background
Matt/Tressa need to be able to use feature flag functionality during UAT so Erik/Sandra won't have to attend all UAT sessions.

## Tasks
- [ ] Create documentation

Matt/Tressa to create an identity verified IDme account on VA.gov (production)

**Comment by erikphansen** [comment]
@mshea0606 @tressaellen @Samara-Strauss I added documentation here https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/flipper-feature-flags. Any feedback is welcome, especially as you go through the steps and find holes in the intructions.

**Comment by Samara-Strauss** [comment]
Thanks for this! I gave it a go with my email address (samara.strauss@va.gov) and got this message after clicking **Enable User**:

<img width="689" alt="Screen Shot 2020-07-20 at 2 33 13 PM" src="https://user-images.githubusercontent.com/34068740/87973136-0ec63f80-ca96-11ea-940e-1e8263e0dd72.png">

Any idea what went wrong?

**Comment by erikphansen** [comment]
@Samara-Strauss you are likely missing this step:

> The email address you use for your LOA3 ID.me account is added to the list of admin_user_emails in the vets-api config/settings.yml file: https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L458

I'll open a PR to get you added to that list.

**Comment by erikphansen** [comment]
@Samara-Strauss PR open https://github.com/department-of-veterans-affairs/vets-api/pull/4555

**Comment by Samara-Strauss** [comment]
Totally missed that step. Thanks!!
