### ISSUE TITLE
STEM: Email SCO on form Submission

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10790]
As an Education Team Services member, I need the SCO for the school where the applicant is planning to use the STEM Scholarship emailed so that they can confirm the information necessary to complete the application.

## Assumptions:
1. This work is done behind feature flag #7271.
2. The facility code is retrieved using the EVSS service documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/statement-of-benefits/gibs-2017-07-06.yaml)
3. On staging, the email should go to a list of recipients that is [TBD]. 
4. Testing of this story is dependent on test EVSS accounts (2). 

## Acceptance Criteria
1. Upon submission, if the Chapter 3 pre-filled school data has not been changed by the applicant and the applicant has less than or equal to 180 days of entitlement and Chapter 33 benefit:
    a. a single primary SCO of the school is emailed the populated template in SA#1.
    b. a single secondary SCO of the school is emailed the populated template in SA#1 if a secondary SCO exists
    c. the applicant is cc'ed on the email sent to the SCOs.
2. The following lines of the email are pre-populated:
    a. Name of Student: [First Initial. Last Name]
    b. Email address of student: [Chapter 3, Page 3: Your school email address]
    c. Student ID number: [Chapter 3, Page 3: Your school student ID number]
3. The spool file has been updated to reflect whether or not an email was successfully sent to the SCO ("Auto Email Sent to SCO") as represented in SA3. 
   a. If SCO email is found, applicant has <= 180 days of entitlement, and has chapter 33 benefit then the spool file should display "Yes"
   b. If SCO email is not found, or if applicant has more than 180 days of entitlement + chapter 33 benefit  then the spool file should display "No"
4. The email subject is "Applicant for VA Rogers STEM Scholarship"

## Supporting Artifacts:
1.  [STEM-SCOEmail-20200715.docx](https://app.zenhub.com/files/133843125/60d17068-eac1-404c-9a47-b1ef3b1333b5/download)
2. [Prototype](https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040796)
3. [10203_Spool_20200709_story_version.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4899135/10203_Spool_20200709_story_version.docx)

**Comment by desireeturner** [comment]
@zurbergram The email template (SA1) has been updated with the latest content.

**Comment by zurbergram** [comment]
To check email locally go to http://localhost:3000/rails/mailers/school_certifying_officials_mailer/build

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4538

**Comment by zurbergram** [comment]
Testing email format
- Submit a form
- go to http://localhost:3000/rails/mailers/school_certifying_officials_mailer/build to view what the email will look like
( this uses the last submitted 10203 form to populate the email and doesn't include sco emails)

Testing the sending of emails will require this to be on staging and for a GIDS institution to have SCOs with QA emails to ensure receipt of emails via SCOs. 

The mailer adds QA emails as `bcc` in staging and below

**Comment by zurbergram** [comment]
In the spool file it will display

- "N/A": this indicates that either user does not have EVSS data or sending of emails is disabled in the backend
- "No": this indicates that user does have EVSS data and sending of emails is enabled but meet necessary criteria to send an email
- "Yes": this indicates that user has less than six months of entitlement, the institution has at least one Primary or Secondary SCO with an email address and the email process successfully attempted to send the email

**Comment by zurbergram** [comment]
AC#1.a, AC#1.b, and AC#3.a are only testable in staging with a user with EVSS data and less than six months of entitlement

**Comment by zurbergram** [comment]
http://localhost:3000/rails/mailers/school_certifying_officials_mailer/build?facility_code=11000139

now accepts a facility_code as a param so logic for pulling first Primary and Secondary with an email address can be tested

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-31 at 7.35.00 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/169daf5d-5f06-4a6f-b831-e6cc5981ca89)
##
![Screen Shot 2020-07-31 at 7.36.06 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/21ac8e79-35ee-4d22-802f-14ed166a07e2)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-31 at 7.07.22 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/12c8fa2e-537c-4228-a41c-bc3b0ff7f98b)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/10070&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
In staging, but need evss user to test.

**Comment by dneel-bah** [comment]
EDU has agreed to launch with an MVP without pulling entitlement / enrollment data from EVSS.  The re-validation of AC3 in staging will be handled in #12734 once the test data is available in the staging environment.  Closing this story because it has been validated in the local/dev environment.
