### ISSUE TITLE
[Discovery] Investigate options for access to internal tools

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#108]
# Description

Currently, granting access to internal tools requires manually requesting access in Slack, with a lot of ops-team toil per-person per-service. We should investigate ways to simplify this process to reduce toil on ops-team members.

# AC
- [x] Enumerating all services that should be encompassed in onboarding, with criteria for which new members need access to which systems
- [x] Get buy-in from DSVA + VSP leadership in terms of what systems can be self-service, which can be exposed publicly, and which must be VA-private

**Comment by wyattwalter** [comment]
Notes from previous ticket in vets.gov-team:

> After discussion with platform team after onboarding new devs during prototype phase [for compass project], we see the following improvements as warranted:
> - Make a public Jenkins instance for continuous integration (i.e. testing of branches), that doesn't require socks proxy access. There's no risk to doing this because our repos are already open source.
> - Make review instances accessible without requiring the socks proxy by proxying through paths under dev.vets.gov
> - Enable GitHub OAuth access for Sentry and Grafana - reducing the number of accounts that need to be set up and that a user needs to keep track of - they will have one-click log in based on their membership in the department-of-veterans-affairs Github org.

**Comment by wyattwalter** [comment]
Submitted PR with an RFC for decision here. I'm leaning towards getting requests in for the tools at {tool}.vfs.va.gov internally so keep things cleanly separated, and using dev.va.gov/_vfs/review/{hash} for review instances.

**Comment by wyattwalter** [comment]
re: the first requirement here:

Systems we need are:

- Jenkins
- Grafana
- Sentry

All of them would be required for VFS developers.
