### ISSUE TITLE
STEM: Update YTD Report Format and Distribution

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10808]
As an Education Services Team member, I need the 10203 submissions included in the daily YTD report so I can perform my duties with accurate and up to date information once the 10203 has launched.

## Assumptions:
1. N/A

## Acceptance Criteria
1. 3 New columns are included in the YTD reports:
     a. Fiscal Year Submissions (Ex. Header: 2018-10-01..2019-08-08 23:59:59 UTC)
     b. Submitted (Ex. Header: Submitted)
     c. Daily Submissions Sent to Spool File (Ex. Header: 2019-08-08 00:00:00 UTC..2019-08-08 23:59:59 UTC | Sent to Spool File)
2. The 3 new columns in AC #1 are grouped under the "22-10203" header
4. The 22-10203 submissions counts:
    a. are NOT included in the number of 22-1995 STEM submissions.
    b. are ALL included in the chapter33 row under the 22-10203 header
    c. are calculated based on the header listed in AC1.
5. All other RPOs have zero counts for 22-10203.
6. The last row has a "22-10203" footer
7. The following email addresses are included in the staging distribution for the report:
    a. Adam Sonntag - Sonntag_Adam@bah.com
    b. Desiree Turner - Turner_Desiree@bah.com
    c. Darrell Neel - Neel_Darrell@bah.com

## Supporting Artifacts:
1. [Sample_YTD_Report_w10203_20200701.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4904489/Sample_YTD_Report_w10203_20200701.1.xlsx)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-api/pull/4505

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9437&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
Submissions and reports show in staging and received emails confirmed.
