### ISSUE TITLE
STEM: Include 10203 submissions in the Daily Spool Report

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10805]
As an Education Services Team member, I need the 10203 submissions included in the daily spool report so I can perform my duties with accurate and up to date information once the 10203 has launched.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The following data is added to the daily spool report for each 10203 submission:
    a. Claimant Name
    b. Veteran Name
    c. Confirmation #
    d. Time Submitted
    e. RPO
2. The following email addresses are included in the staging distribution for the report:
    a. Adam Sonntag - Sonntag_Adam@bah.com
    b. Desiree Turner - Turner_Desiree@bah.com
    c. Darrell Neel - Neel_Darrell@bah.com

## Supporting Artifact:
1. [Sample_Daily_Spool_Reportw10203_20200701.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4858088/Sample_Daily_Spool_Reportw10203_20200701.xlsx)

**Comment by hughes-dustin** [comment]
branch: bah-19805
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4512

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-13 at 1.46.25 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a1d55a8f-a620-487b-b5e7-4071c49c51ea)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9342&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
Submissions and reports show in staging and received emails confirmed.
