### ISSUE TITLE
CT-Search: Remove 'gibct_search_enhancements' feature flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10810]
As a developer, I need to remove the feature flag for the free text search enhancements because it will not be disabled going forward.

## Assumptions:
1. The feature flag was configured as part of story #10615.
3. This functionality has gone through UAT with EDU and been signed off on as of 09/03.
4. This functionality has been turned on as of 09/10 and no issues have been encountered.

## Acceptance Criteria:
1. The feature flag 'gibct_search_enhancements' is not displayed here: https://[environment]-api.va.gov/flipper/features.
2. The search functionality is still available per stories:
     a. #10613  
     b. #10617 
     c. #10669  

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/743
- https://github.com/department-of-veterans-affairs/vets-website/pull/14653
- https://github.com/department-of-veterans-affairs/vets-api/pull/5126

Merging the vets-website PR will cause the site to stop sending the `fuzzy_search` flag to GIDS, so the GIDS code will need to be merged in first. The "enhanced" search functionality will be live at that point, and the vets-website and vets-api PRs are just cleanup to remove unnecessary code.

**Comment by sonntag-adam** [comment]
Testing passes in staging.

**Comment by delli-gatti-michael** [comment]
This is live in production. Closing this issue
