### ISSUE TITLE
Make the FE form detail landing pages using static approach

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10819]
### Make the FE form detail landing pages using static approach

**aka Form detail pages can be published to all environments**
The current state of the detail page is it can be previewed, but not published. This accomplishes the publishing step

---
**User story:** 
As a Veteran, if I do a search for a form on Google, I want to see a form page that gives me contextual information including if there's an easier online alternative to filling out the paper form. 

**Summary:**
This follows the standard approach we use when pulling data out of Drupal and into the frontend. It means that for the +400 forms in Drupal (originating from the Forms DB), we would generate a static HTML page for each one.

**Acceptance Criteria - ~we will publish in batches:~**

- [ ]  Custom form detail page can be previewed with the correct data fields.
- [ ] Non-custom form detail page can be previewed with the correct data fields.
- [ ] ~Form detail pages can be published to all environments~
- [ ] ~Batch 1: Top 30-40 identified MVP form pages.~
- [ ] ~Batch 2: Remaining form pages.~ 

~**Dependency:**~
~Because of transformer and processing memory dependency, we will have the pages ready in Draft CMS state and check memory/transformer situation before publishing.~

**Comment by jenniferlee-dsva** [comment]
@MickinSahni - I crossed out the publish AC above, per my comment in #11155, and added more specific AC for this task. @ncksllvn - Can you add more specific FE engineering validation that should happen with this task?

**Comment by ncksllvn** [comment]
@jenniferlee-dsva There is a lot of overlap between this issue and https://github.com/department-of-veterans-affairs/va.gov-team/issues/10606. I added to the AC for this issue what I think is the key distinction - `Form detail pages can be published to all environments`. 

#10606 enables writers to be able to preview the form detail pages, whereas this enables us to publish them.

**Comment by jenniferlee-dsva** [comment]
Got it - thanks for that distinction @ncksllvn
