### ISSUE TITLE
Initial Audit of Developer Focused Documentation

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#10813]
## Description

This will be the first task in focusing on developer documentation as a collection for VFS teams.  This task will be to go through our exisiting documentation and make note/organize what we have in the different locations and understand how it could be leveraged as a VFS facing docs.

## Questions to ask around the docs
Are they VFS facing?
Are they VSP facing?
Are they VFS and VSP facing?
What teams owns them?
Where are they located (what repo)?
etc.

## Definition of Done

- We have gone through all known existing docs and categorized them with the questions listed above
- A draft outline is ready to be shared with other teams on structure
- Gaps in documentation have been identified and a plan is created to fill them.

**Comment by thilton-oddball** [comment]
https://docs.google.com/spreadsheets/d/1CHhM0LSrOzecRg70lAivM5f8wA4Kwhv4e8wy7QOKXWI/edit?usp=sharing

**Comment by alexpappasoddball** [comment]
@thilton-oddball I believe we can close this.
