### ISSUE TITLE
[SCREENREADER]: Alert message for bad submit is not read out to assistive devices like JAWS or VoiceOver

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#1081]
Migrated from vets.gov issue [15627](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15627)

## Issue
The Education feedback tool has an alert message that fires on Step 5 to alert assistive device users that their submission did not complete. This alert is not being read out to assistive devices, so this user group is at a disadvantage. Screenshot attached below.

## Acceptance Criteria
As a screen reader user, I want to hear the full alert message read aloud when there's a pause in the natural page narration.

## Environment
* MacOS Mojave
* Safari latest
* VoiceOver SR
* https://staging.va.gov/education/submit-school-feedback/review-and-submit

## Possible Fixes (optional)
Adding an `aria-live="polite" to the containing div fixed the issue in VoiceOver and should do the same for NVDA and JAWS. I will re-test in all assistive devices when a PR is issued.

## WCAG or Vendor Guidance (optional)
* [Error Identification: Understanding SC 3.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-identified.html)

---
![screen shot 2018-12-11 at 9 04 39 am](https://user-images.githubusercontent.com/934879/49809613-fd974780-fd24-11e8-94be-f3c21d707539.png)

**Comment by CourtneyChambers77** [comment]
@pjhill I tested this error again and I do not get that error anymore I am confirming

**Comment by caw310** [comment]
@pjhill , we were going through some old a11y tickets to see if they're still a problem. If this is no longer an issue we can close it.

**Comment by pjhill** [comment]
Awesome -- let's close it!
