### ISSUE TITLE
[BE] fix debts api staging connection

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#10827]
/v0/debts is returning 503 errors in staging but works in dev

**Comment by lihanli** [comment]
@bradl3yC i emailed the debts api team about this, the api hasn't been deployed yet to the server that our staging environment is connected to. "We are still changing the API contract and there are more fields that needs to be added to the API. Once we finalize and freeze the API contract we can deploy this to pre-prod."

**Comment by leahkeeler** [comment]
this is done

**Comment by leahkeeler** [comment]
this is done and no further action needs to be taken
