### ISSUE TITLE
Access for Michael Fleet

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#10824]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Nancy Smith
- Please provide your name.
   > Michael Fleet
- Please Provide your email.
   > michael.fleet@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I need for SOCKS access to Jenkins, for debugging production deployment errors.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNVbvqaBaju2qaaUyptDnWF0V8Vm1fdFIgzMIX8jYNEreTDtpdIaEMdc951Npjn4FpWO4QLJhfKYXp8IZj+Y+mAb7ShOBDlBG6MfJ/Mv0WroyyYJCCT1W05zEdAMS3/3G6BGnTHE304dYvgE+a7LravqUmJsguTXVpUg01fP2bCBd0t2pE/e+lpd+ztXS6te0p9gKj1KXf4lJOuPXqi3NgsuKW1OSOGUcUnKHMdx92PYZHWBryoRl7c15WojKFuzsCJmPq1M/RZkw+H9npy3zN4M3KCNp4VirNSYjSfN3eQuiF+VlA/b5brY1NN3JRrTTVa5tPgPPm87bszXVerTJ5ue/QPlxmkujny0oKiFuYDbhnZ6qG9bewN0SCKXWnp4q+br+rYC7XTpeejyZ3c7c+mqdiX7cwvK7CNERNoGVd3Ore95C4ou5YmOZju9MeBOau96gzM/74lRkwej3aWfcpQJVrMpnVTiINfrd5pi5j4bY3vMeWMDD2v5OWaMXVkWnLgQSKUAvoPAc1U9VVaHib5VNl0UQWodrMTkZsNqb4NMvDOVkM6U1CvZ2oFyQ+nWgNhWIujicQbW7PzIh4BhvaQMUlmESbmEUx/H1H/usM2KjWsnm5Z97WeyY+Z/x0q6x9lWWylCMaSfN50hVImsfhruTtLCg8vEsI2CtK+gozpQ== f1337@f1337.us
```

- Grant AWS Console access?
  > NO
  - Please give a brief description for why you are requesting AWS access.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by f1337** [comment]
Thank you @jbritt1 !
