### ISSUE TITLE
Produce Flowchart for CH31 Wizard

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#10823]
## Goal
Per the stakeholders input from Steve, develop a flowchart that describes what is intended.

## Considerations
[Convo with screens](https://dsva.slack.com/archives/CLY6Q69RV/p1593469644404100)

## Tasks
- [x] Develop a flowchart of the CH31 wizard

## Acceptance Criteria
- [x] A flowchart has been shared for feedback from stakeholders/ Steve

`Next steps`
- mockups
- prototype as approved

**Comment by sporeboy** [comment]
VR&E (CH31) wizard flowchart created along with user-flow thumbnails: https://xd.adobe.com/view/879cf230-f3ce-4204-79ba-c3453b0bcc09-f1ad/screen/cda5f810-18aa-4b95-b441-a63050f91bda/CH31-Wizard-Flowchart-1

**Comment by sporeboy** [comment]
Sources include stakeholder-supplied questionnaire (screen-caps), VA.gov and [revised VA factsheet (June 2020)](https://www.benefits.va.gov/BENEFITS/factsheets/serviceconnected/Ch31FactSheet.pdf). This last document was used as the source-of-truth for requirements and eligibility.
