### ISSUE TITLE
Express care requests disappear from list once cancelled

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#10844]
Express care requests disappear almost immediately once cancelled, because they don't have date options associated with the request, so we can't do our normal logic about waiting until the latest preferred date is past.

When should cancelled express care requests disappear from the list?

**Comment by lenaecb** [comment]
@jbalboni - this is one of the stories that I have for the upcoming EC work. 

For EC requests, the preferred day is always today (the day of the request). So, for this use case, we'd want to change that logic to show cancelled appointment for today. The current logic (as you know) if "Cancelled requests are shown if there is a requested date later than today"

@lalexanderson-dsva - it may be worth changing the cancellation logic universally and having all appointments the a cancellation day of today or later than today" show in the list. 

That's what I would recommend. @jbalboni thoughts?

**Comment by jbalboni** [comment]
Showing cancelled EC requests just on the day they're cancelled is fine. We could also show them for a specified amount of time after created or cancelled (like 24 hours).

Might be worth keeping in mind that it looks like FHIR doesn't support this kind of activity data. I just see a `created` date on the current version of the spec (nothing in DSTU2, that we're aiming toward). So we might lose some flexibility here in the future.

**Comment by lenaecb** [comment]
I am going to repurpose this ticket as I have created a ticket to address all EC request statuses (#10993). 

Given that, we can close this ticket or repurpose it for another cancellation bug which is that user shouldn't be able to cancel an EC request if the status is 'escalated' in SM.

**Comment by lenaecb** [comment]
Closing - bug being addresses in EC statuses ticket
