### ISSUE TITLE
Log enough info to check one-timeness of "missing UUID" condition.

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#10841]
We have a caveat on inbound SSO that if a user arrives and doesn't have an ID.me UUID, we will force them to re-authenticate through ID.me one time, in order to get their ID.me UUID mapped. 

Business owners are aware of this caveat, but will likely want assurance that it's only happening one time per user. We don't currently have a good way of tracking that. 

Acceptance Criteria:
- We can provide assurance that users are only experiencing the 'one time reauthentication' one time.

Options:
1) We could, when we detect this condition, log a specific message that includes the user's secID. Then we could use that to pull these specific log entries and parse them to ensure that we don't see the same sec IDs multiple times. 
We might see some duplicate secIDs if a user abandons the one-time reauthentication, but the numbers should be low, and we can spot check them to make sure we're not seeing them complete the one-time reauthentication but then getting prompted to do it again later. 

2) ???

**Comment by christine-dillman** [comment]
This work was completed with the VAOS launch for Inbound.
