### ISSUE TITLE
Public websites support for Profile 2.0 launch

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#10852]
## Purpose of this epic

To capture PW work related to supporting the launch of Profile 2.0

## Details

We want to have content ready to go by August, but we won't publish until we get the go-ahead from @Samara-Strauss @tressaellen.

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 for awareness that we need to make sure content updates are coordinated with our phased launch. We can wait to launch these updates until we have launched to 100% of users.

**Comment by mshea0606** [comment]
Thanks @Samara-Strauss

**Comment by DanielleThierryUSDSVA** [comment]
@Samara-Strauss @mshea0606 If anything else comes up beyond connected apps and change address, just let me know and i'll add to this epic. thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss @mshea0606. I'm going to be out part of next week (Monday - Wednesday) so just checking in in preparation. Do you anticipate needing this content coordination next week? I think it's further out than that, but just checking to make sure so I can prep team if needed. Thanks!

**Comment by Samara-Strauss** [comment]
I don't *think* so, but we'll get back to you on that. We have some feedback in from our staging review, and I have yet to go through it to see if there is anything content related. If there isn't anything content related, we'll be good to go and shouldn't need any support.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ricetj. Just looping you into this epic as well based on our slack conversation re: connected apps FAQs. We're also ready to publish the changes to the Change address page when you all are ready for them to be live. I believe we're waiting until Profile 2.0 is available for 100% of users, but feel free to let me know if you need it published sooner (slack is best). Thanks!

**Comment by ricetj** [comment]
> Hi @ricetj. Just looping you into this epic as well based on our slack conversation re: connected apps FAQs. We're also ready to publish the changes to the Change address page when you all are ready for them to be live. I believe we're waiting until Profile 2.0 is available for 100% of users, but feel free to let me know if you need it published sooner (slack is best). Thanks!

Hello @DanielleThierryUSDSVA ok great info here and thank you for bringing me into the loop on this. This all makes sense to me.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss @ricetj. Just checking in now that profile 2.0 has launched to 100% of users. Would you like us to publish the updates to the change address page? Thanks!

**Comment by Samara-Strauss** [comment]
@DanielleThierryUSDSVA were there additional changes to that page beyond changing the subway map to a dynamic widget? That change is already live (it was programmed in a way that worked for both profile 1.0 and 2.0), but yes, if there are additional changes, we're ready for them to go out.

**Comment by jilladams** [comment]
Surfing open epics tagged for Public Websites. @DanielleThierryUSDSVA could this close?

**Comment by DanielleThierryUSDSVA** [comment]
Yes, okay to close. Thanks, @jilladams!

**Comment by Samara-Strauss** [comment]
Oh yeah, this is super old. Closing.
