### ISSUE TITLE
[Copy] Profile: Copy needed for appointment reminder check box

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#1085]
Hi @peggygannon — we could use your eyes on a small copy task.

### Background

@claricechan is working with the Bylight team to implement a notification setting in the user profile that will allow health care recipients to opt in/out of appointment reminders.

### Copy needed

We need copy approval/suggestions for the suggested check box copy:

"Receive text messages (SMS) for VA health care appointment reminders."

We also need copy approval/suggestions for the in-line saved notification:

"Your preference has been saved."

![image003](https://user-images.githubusercontent.com/34068740/63296301-d3772b80-c29c-11e9-8fe0-dd3b06f1f5f6.png)

**Comment by peggygannon** [comment]
Hi, @Samara-Strauss Here's my recommended content update to more closely align with VA voice/tone (conversational and using 1st person),

-- please tweak checkbox language to: 
{checkbox} Send me text message (SMS) reminders for my VA health care appointments. 

--in-line notification to: 
We've saved your preference.

Also, for the checkbox copy, another option the team might want to consider is making it a yes/no opt-in or opt-out. For example: 

{question} Would you like to receive text message (SMS) reminders for your VA health care appointments? 
{checkbox} Yes
{checkbox} No

**Comment by Samara-Strauss** [comment]
Thanks for this, @peggygannon!!

**Comment by Samara-Strauss** [comment]
@rtwell — Peggy has greenlit the following copy for the health care appointment reminder check box. Can you please make the following updates in the mockups/prototype so they're updated for Byight? Once you've done that, feel free to close this ticket:

- Checkbox: Send me text message (SMS) reminders for my VA health care appointments. 
- In-line saved notification: We've saved your preference.

![image003](https://user-images.githubusercontent.com/34068740/63440929-b0648d00-c3fe-11e9-8173-c7190b516a1e.png)

**Comment by rtwell** [comment]
[done and done](https://adhoc.invisionapp.com/project/18216300).

**Comment by Samara-Strauss** [comment]
@rtwell can you share the public link? I don't have access to the one above.

**Comment by rtwell** [comment]
oops! my mistake! [here's the public link.](https://adhoc.invisionapp.com/share/FSTDOO0WUHC)

**Comment by Samara-Strauss** [comment]
Looks good to me!
