### ISSUE TITLE
VSP content feedback - Usability prep - Debt letters mockup

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#10851]
## User story

This ticket captures VSP content feedback on Debt Letters

Protype link:  https://preview.uxpin.com/4355a6c97a71ddaf1069ec43e5dfc0ae46b79869#/pages/130133439/simulate/no-panels?mode=i   

## Acceptance criteria

- [x]  VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x] Teams leaves comments about any feedback they decide not to take
- [x] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
@kristinagore @meganhkelley I was able to complete my VSP content review for the Debt Letters mockup. A couple of things for next week's meeting: 

-- I have requested to see copies of the "debt letters" to more accurately provide content recommendations. I've provided some feedback below, but would like to see the letters to ensure I've accurately captured the content. 
-- I have a few questions for the BAM team. Listed below as "QUESTION" . If you can address this during the collab meeting that would be great. 


--I'm cc'ing @DanielleThierryUSDSVA  I'm awaiting feedback from the PW team on what FAQs they are adding to the Debt Letters static page.. We need to discuss if any make sense to also add to the tool.  

-------

Feedback for the BAM team:
General question. 
1. for the debt letters, can I see the content of these debt letters (First demand, Second demand, etc,) to more accurately provide content recommendations? 


Landing page
I updated introduction to make it clear what types of VA debt are covered in this tool.

**Your VA debt**
Check the details of debt you might have from VA education, disability compensation, pension, or home loan programs. Find out how to pay your debt and what to do if you need financial assistance. 

Debt cards
I suggest removing the date from the header and putting it the card copy to shorten the length of the subheads
So header will be: 
Chapter 33 (Housing) debt

QUESTION: What does this date refer to? 
is it the debt due date or the date that VA sent the letter?

Please update content  under **Next step**: TO: 

Pay your bill now or call the Debt Management Center before July 1, 2020, to avoid this debt going to credit reporting agencies. This may cause your credit score to decrease. 

Please update content under **What if I don’t see a debt?** TO: 
If you’ve received a letter about a VA debt, but don’t see it listed here call the Debt Management Center at 800-827-0648. 
For medical copay debt, please go to [pay your VA copay bill] to learn about your payment options. 

-----

Right rail content
Per VA.gov styleguide
- please format phone numbers as  xxx-xxx-xxxx
- please format time a.m. p.m. 

Under **Request financial assistance** please update content TO:
If you need financial help, you can request an extended monthly payment plan, a compromise (ask us to accept a lower amount of money as full payment of the debt), or a waiver (ask us to stop collection on the debt). Call the DMC to discuss your options and next steps. 

Under **Dispute a debt** please update TO:
If you think a debt was created in error, you can dispute it. Get information online about [how to dispute a debt] or call the DMC.

QUESTION: Where does the how to dispute link take users? 

------

Screen 2 
Please update alert to: 

**You don’t have any VA debt**
If you think you have debt for a VA education, disability compensation, pension, or home loan program, or would like to get information about a resolved debt, please call the Debt Management Center at 800-827-0648. We’re Monday-Friday, hours, ? 

For medical copay debt, please go to [pay your VA copay bill] to learn about your payment options. 

Under **Why do I have this debt?** Helper link, please update content TO: 

We sent a letter explaining the debt details to the mailing address we have on file for you. Some reasons you might have this debt are: 
- The school you’re attending reported that you reduced your hours or are no longer enrolled. 
- Your eligibility for this benefit has changed.

If you want more details about this debt, please call the education benefit department at 555-555-5555

Update content under **Next step** TO:
Pay your bill now or call the Debt Management Center before [month, day, year], to avoid this debt going to credit reporting agencies. This may cause your credit score to decrease. 

----
Debt letters 
You can view the status or download the letter we sent about this debt. 

QUESTION: What does "status" refer to? the status of the letters or the status of the debt?  

Update content for **Note** TO: 
Note: The content of the debt letters below may not include the most recent update to your debt. If you have any questions about your debt history, please call the Debt Management Center at 800-827-0648.


I recommend bumping down the font of the date, as it's the same weight of the Debt letter header.  

July 12, 2020
First demand letter
This letter notified you of your debt and let you know if it wasn’t paid within 30 days, it would be reported to credit reporting agencies. This may cause your credit score to decrease. 
 . 

Please update **This debt is on hold** alert TO: 
Collection of this debt is on hold because it’s going through a waiver review. You don’t need to do anything right now. 
Please check back here for updates or call the Debt Management Center at 800-827-0648. 

Please update **Letter returned – bad address** TO: 
We couldn’t deliver a letter to the address we have on file for you. Please call the Debt Management Center at 800-827-0648 to update the address we have for you. 


------

QUESTION: Can I see the content of these letters to better recommend content? I've offered some recommendations below, but would like to see the letters to ensure I've capture the letter content correctly. 

Debt history
Below is updated recommended content for the letter accordions: 

**Your waiver request is being evaluated** TO: **We’re reviewing your waiver request**
We've received your waiver request and the Committee for Waivers and Compromises will make a decision in about [#] days. We’ve put collection action on hold until a decision is made.

Financial Status Report requested
You've asked us to send you a Financial Status Report so you can submit a waiver or compromise. Fill out this form by [next diary date] and send it to us with the attached 

We’ve sent this debt to credit reporting agencies
This debt is [TK] days overdue, so we’re required by law to notify the credit reporting agencies. This may cause your credit score to decrease.

Second demand letter sent
This letter notified you that if your debt wasn’t paid within 60 days, it would be transferred to the U.S. Treasury.

**Comment by rileyorr** [comment]
Good morning @peggygannon! The content updates you left on the UXPin prototype have been incorporated. Would you like to review the prototype again in case there are additional edits or are we good to close this ticket?

**Comment by peggygannon** [comment]
thannks, @rileyorr I'm looking at the Debt letters alerts today (tickets below), so I might need to take a look a the prototype again as I review these alerts.  I'll close this ticket once I'm done. thank you for checking! 


https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/11935
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/11902

**Comment by rileyorr** [comment]
@peggygannon Awesome, thanks! We're rolling this project out in multiple phases:
- [The MVP release](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130705115/simulate/no-panels?mode=i) (the prototype relating to the tickets you're reviewing today)
- [The first iteration release](https://preview.uxpin.com/4355a6c97a71ddaf1069ec43e5dfc0ae46b79869#/pages//simulate/sitemap?mode=i) (the prototype you added comments for content changes on)  

I've tried to match your feedback on the first iteration with the MVP, but I've provided links to both just in case you want to review either one!
