### ISSUE TITLE
[Cerner widgets] Implement feature flag to test in dev/staging without impacting production

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#10869]
We have widgets across various health care pages for rendering unauthenticated and authenticated content directing users to Cerner or MHV. These widgets are almost ready to be hooked up into Drupal as React widgets. However, we would like to test these widgets in lower environments before going into production. This means we need to incorporate a third state into each widget in order to power a feature flag. Altogether, these states are -

1. "Legacy" content - the content shown currently on va.gov without any Cerner references
1. Unauthenticated content containing Cerner
1. Authenticated content containing Cerner

Once each widget has incorporated the legacy content, we can hook the widgets up into each Drupal page. Then, after being published via Drupal and being deployed, we should see Cerner content in dev/staging and legacy content (Cerner-free content) in production

**Comment by ncksllvn** [comment]
This is hand-in-hand with https://github.com/department-of-veterans-affairs/va.gov-team/issues/10859

**Comment by MickinSahni** [comment]
Created these dummy pages so Cerner can test the functionality pre-prod:
https://staging.va.gov/cerner-staging/messaging
