### ISSUE TITLE
Update messaging on View or change dependents React Widget

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#10860]
### Background
React widgets were created in ticket [#8115](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8115)  for the static landing page for Form 21-686c/674 (view or change dependents). The messaging on the react widget needs to be updated to match the messaging in the screenshot below.
<img width="681" alt="Screen Shot 2020-07-01 at 5 14 07 PM" src="https://user-images.githubusercontent.com/42546515/86348250-67d84b80-bc2d-11ea-8c2c-4997855b480f.png">

**[From Jason] Closer to launch we will request the addition of some HTML around the first and second login widget, that we will provide below, that will allow Flipper to adjust traffic redirects for a graduated, controlled rollout.**

## Here are the react widgets
- HTML to replace first login widget/section:
```diff
<div data-widget-type="view-dependents-CTA" id="view-dependents-CTA"></div>
```
- HTML to replace second CTA widget/section:
```diff
<div data-widget-type="686UnauthContentBlock" id="686ContentBlock"></div>
```
[Image: Code to replace second widget](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/images/VA_View_Dependents_Screens_W3_html.jpg)

---
## Tasks

- [ ] _Update messaging on react widgets_

## Acceptance Criteria
- [ ] _**Implementation of REACT sign in widgets**_

**Comment by MickinSahni** [comment]
Expected behavior: Drupal preview that uses this widget should start working

**Comment by MickinSahni** [comment]
Expected behavior:
if feature flag is off, should direct users to eBenefits

Currently it's off, so shouldn't be seeing VA.gov CTA directing them to eBenefits

(btw feature flags: https://api.va.gov/flipper/features)
