### ISSUE TITLE
[FE] Update copy on LOA1 alert button

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#10868]
## Background

Currently on the LOA1 alert in account security the green CTA button says "Verify **my** identity", we need to update it to say "Verify **your** identity" to keep things consistent across va.gov. 

![Screen Shot 2020-07-02 at 9.45.33 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/ebd33ebf-0c4f-4685-8d88-a7aa857ba676)

## Tasks

- [ ] Update copy

**Comment by sanlouise** [comment]
@tressaellen @mshea0606 This copy change is already covered in https://github.com/department-of-veterans-affairs/va.gov-team/issues/10596, so this ticket can be closed.
