### ISSUE TITLE
[Development] Investigate/Resolve BDD "external service" error

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#10876]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

Per Anna, when we submit the claim to evss and get  `[{"key"=>"form526.submit.establishClaim.serviceError", "severity"=>"FATAL", "text"=>"Error calling external service to establish the claim during Submit"}]` 
That sounds to me like we've plausibly submitted enough data to EVSS but that they're having issues.

- `Error calling external service to establish the claim during Submit` per old conversation with Slack, it sounds like we can't have multiple open BDD claims 
- Per Luke, users should be able to est mult bdd claims
- Per, Anna maybe this is simply a problem with test users 228, 229 and 226

Issue discovered during https://github.com/department-of-veterans-affairs/va.gov-team/issues/10479

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
todo: answer michael https://dsva.slack.com/archives/C8R3JS8BU/p1593624408336100?thread_ts=1593191206.321400&cid=C8R3JS8BU

**Comment by luke-gcio** [comment]
Part of the retryable errors work @annaswims did during Sprint 26.
