### ISSUE TITLE
Access for Ling Tran

### ISSUE THREAD

**Issue by lingtran** [department-of-veterans-affairs/va.gov-team#10877]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea @CourtneyBethea
- Please provide your name.
   > Ling Tran
- Please Provide your email.
   > ltran@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @department-of-veterans-affairs/thoughtworks 
   > Role: Developer
   > Company: ThoughtWorks
   > I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana / Sentry so we can
   >   - Modify / update Jenkins job configs
   >   - Kick off Jenkins jobs
   >   - Review Prometheus data, some of which is imported into the scorecard
   >   - Review Grafana data for the scorecard
   >   - Review logs in different environments to facilitate testing along the path to production

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGE6dBaYvVF5hNf4FswRPoOkH9gIkmJ09BM58DD3qpI8H5X5OyijjzhBDS8O2BllnVpxCcrVfDdH/AcKDJeHmicCrBISd55/IF4bAAc0pThzFRuRoHVhGoIL1RHGfqA+69U/lOQI/ir+avng7lKb7DJ89fru6Ma388W5lE3w5+k2av8mHvxrqoi0KyW4sBCSYuYm3x6+iu//gGD7SfGA2ozW3AEkp/SnRcu0gNox3AmtYxL8H05N8Eq1tV66TCImNtDJo+JznaTxvqy99hL48prFt2IqC0iyGJtOmSoN5CIuADF1cEeCbCfT5foId0yyTrHPB9nkJwRiX8KMTdemAl ltran@thoughtworks.com
```

- Grant AWS Console access?
  > YES

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jbritt1** [comment]
#### For AWS Access

User: Ling Tran
COR: Courtney Bethea
Approval needed: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
