### ISSUE TITLE
CF: Update GIDS to accept consolidated caution flag file format

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10883]
**As** an EDU team member, I need the ability to upload a single file of caution flag data to GIDS so the number of steps to maintain the comparison tool is reduced.

## Assumptions:
1. Updating version generation is outside of the scope of this story.
2. This will replace the following files: Settlement, School Closing, Section 702. 
3. This does not affect the MOU, Accreditation Action and HCM caution flags (these flags will continue to work as is).

## Acceptance Criteria
1. The CSV Type is: "VA Caution Flags"
2. The header for the CSV has the columns in the following order:
    a. id (facility code)
    b. instnm
    c. school_system_name
    d. settlement_title
    e. settlement_description
    f. settlement_date
    g. settlement_link
    h. School_Closing_Date
    i. Sec_702
3. The "Id" column:
    a. Is required
    b. Accepts alphanumeric strings
4. The "instnm" column:
    a. Is not required
    b. Accepts alphanumeric strings
5. The "school_system_name" column:
    a. Is not required
    b. Accepts alphanumeric strings
6. The "settlement_title" column:
    a. Is not required
    b. Accepts alphanumeric strings
7. The "settlement_description" column:
    a. Is not required
    b. Accepts alphanumeric strings
8. The "settlement_date" column:
    a. Is not required
    b. Accepts dates
9. The "settlement_link" column:
    a. Is not required
    b. Accepts alphanumeric strings
10. The "School_Closing_Date" column:
    a. Is not required 
    b. Accepts dates
11. The "Sec_702" column:
    a. Is not required
    b. Accepts True / False / Blank 
    c. All bad data is accepted as "False" like current functionality for other booleans in csv uploads.

## Supporting Artifacts:
1. Sample file: [https://app.zenhub.com/files/133843125/4b5aafb6-67a3-4bed-80d3-72978afa59c7/download](https://app.zenhub.com/files/133843125/4b5aafb6-67a3-4bed-80d3-72978afa59c7/download)

**Comment by hughes-dustin** [comment]
DB Changes 
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/687
Branch: bah-10883

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/689
branch: bah-10883-b

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-27 at 10.09.17 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/76a5a41a-e24e-451f-95aa-a667bec7b2ec)
##
![Screen Shot 2020-07-27 at 10.11.08 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0138990f-59b8-4d51-a764-776b2d41fb3a)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-30 at 11.13.27 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/03a89600-b272-4855-bb93-36bd79507288)

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
