### ISSUE TITLE
[PM] Profile: Refine OKRs and KPIs

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#10887]
## Background

We did a hand-wavey job of establishing OKRs and KPIs for the profile 2.0 project and the other profile-related products. I'm going back and refining those OKRs and KPIs so we actually have a sense of what we need to be measuring and how we can measure success.

## Tasks

Establish/document OKRs and KPIs for the following:

- [x] Profile 2.0 project
- [x] Contact information (includes address validation)
- [x] Direct deposit
- [x] Account settings

## Acceptance criteria

- [x] OKRs and KPIs have been reviewed and agreed upon by Matt/Samara.

**Comment by Samara-Strauss** [comment]
@mshea0606 I am documenting the OKR and KPI work I am doing around the profile in this ticket.

At this point, I am looking for your feedback on where I am at with OKRs for the profile. There are four things I'm working on — OKRs for the profile 2.0 project, as well as documenting OKRs or just establishing baseline metrics for contact information (includes address validation), direct deposit, and account settings (this latter stuff is not urgent now, but it does need to be properly documented). Post, July 4, can you give this stuff a look and let me know what you think? [Here is a link to the spreadsheet](https://docs.google.com/spreadsheets/d/1B6c1rY-1l64cWhHO7D8WjA328zwfdAhSgKkPatIKmts/edit#gid=666840712). Each section is in a different tab. can you review it and let me know if you have feedback at your earliest convenience? 

Once we have a chance to go over your feedback, Iet's schedule another chat with Jon/Brian to review.

Thanks!!

**Comment by mshea0606** [comment]
@Samara-Strauss Will do. I'll take a look today
