### ISSUE TITLE
[Bug] Facility Locator - CA State search initial results fewer than after zoom-in

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#10894]
## What happened?
On Staging **Find VA Locations** page, when searching by State, initial results loaded were fewer than after zooming map in.

## Specs:
- Browser-/device-agnostic
- Unauthenticated experience

## Steps to Reproduce
1. Go to https://staging.va.gov/find-locations/ \[this issue occurs regardless of whether geolocation is allowed or blocked]
1. In **Search by...** text-field, input **CA**\*, the click **Search** button. 
1. Observe that only 2 results are loaded.
1. In **map-panel**, click **+** (zoom-in) button.
1. Observe that more results are loaded.
1. Click **-** (zoom-out) button.
1. Observe that additional results now remain displayed at initial zoom-level, unlike on initial search.

\*Bug also occurs with **AZ**, **AR**, **CO**, **DE**, **GA**, **HI**, **IL**, **IA**, **KS**, **KY**, **LA**, **ME**, **MI**, **MN**, **MS**, **MO**, **NH**, **NM**, **ND**, **PA**, **RI**, **SC**, **SD**, **TN**, **TX**, **VT**, **VA**, **WV**, **WI**, **WY** \[with varying numbers of initial results before zoom-in].

**GIF capture \[CA example]**
![fl-bug-state-zoom](https://user-images.githubusercontent.com/587583/86420556-dd730480-bc8b-11ea-8ee8-9d24085f3fc7.gif)

## Desired behavior
Initial results are same number as or more than after zoom-in.

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tlei123** [comment]
Not sure which Practice Area label \[frontend/backend] to add.

**Comment by mmiddaugh** [comment]
This should be addressed during upcoming map interaction enhancements

**Comment by mmiddaugh** [comment]
This issue has been resolved by disabling the auto-zoom behavior and adding the "Search this area of the map" feature.
