### ISSUE TITLE
[UAT] Direct Deposit: Create research plan

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#1089]
Epic #1088 

- [x] [Create research plan](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/Profile/Direct%20Deposit/Discovery%20&%20Research/UAT/Research%20Plan.md)
- [x] Kickoff recruiting

**Comment by lalexanderson-dsva** [comment]
Submitted!
