### ISSUE TITLE
[CONSIDER] Consistent logic for organizing lists

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10892]
This is a placeholder issue based on feedback from Pittsburgh PAO

## Issue Description
Listings are all categorized differently, which causes confusion. For example; when adding a staff member to a WYSIWYG the list is alphabetized by first name (confusing in and of itself) while other lists are populated by date. There should be a common thread with these.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
Lists no longer use an alpha list, but instead and Add more / Autocomplete field, so not relevant for all lists. 

The guidance around how to manage adding items to a list in the CMS is maybe a bigger picture design component question for the CMS team. But: we can specify those asks as they come in from editors. Closing.
