### ISSUE TITLE
[Documentation] Add documentation for onboarding access to production tools

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#109]
# Description

Currently, documentation is scattered for new team members discovering what systems they need access to and how to get that access.

We should have a central document on the va.gov-team repo that describes the process for getting access to these systems (audience: new apps developers) and another document that describes the ops-team process for quickly adding members to those systems.

# AC
- [x] Document for describing production systems + process for requesting access
- [x] Document (manual) for ops team to grant access

**Comment by ricetj** [comment]
Update: issue template titled "Environment Access Request Template", has been added to repo for onboarding

**Comment by b00klegger** [comment]
Document explaining process for external team access merged here:
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/28

Document explaining the process from the operations side here:
https://github.com/department-of-veterans-affairs/devops/blob/master/docs/operations/Internal_Onboarding_Instructions.md

Issue template here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/Environment-Access-Request-Template.md

**Comment by ricetj** [comment]
Great stuff here. LGTM thanks for all the great documentation.

**Comment by ricetj** [comment]
Reopening because further changes may need to be made for AWS access.

**Comment by ricetj** [comment]
Done
