### ISSUE TITLE
Design - Appointment page with EC prompt to start EC flow

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10900]
To support EC flow, need a mock for what a Veteran sees if they are registered at a VAMC that is offering EC and that EC is available right now (in the defined window from VATS). 

## AC:
- Visible on homepage of VAOS
- This is the 'active' state prompt meaning EC is available right now (Veteran is using VAOS in window when EC is being offered)

EC Prototype: https://vsateams.invisionapp.com/share/U9XQMY2GS5V#/screens/422011176

**Comment by rtwell** [comment]
another option for the VAOS landing page w/express care visible:

![image](https://user-images.githubusercontent.com/12564977/86622204-82902480-bf8d-11ea-8eda-f697eb71e13d.png)

**Comment by lenaecb** [comment]
@rtwell - I would love to A/B test this. Is there a preferred tool that you know of on the VSP side? 

My initial reaction is to stick with the previous iteration because EC is still considered in "Pilot" mode and it seems there is a desire to encourage folks to more 'telehealth' like options. But, I also like that this doesn't draw the users eyes away from the typical flow (which they most likely want). 

Thinking the 'inactive' state with this version would be easier to comprehend as well. 

@lalexanderson-dsva - thoughts? 

@rtwell - to answer your question in the prototype re: need data and time here, yes. That way it's clear that this is something that's only offered at a set time. Also, I am wondering if we need to call out the facility name as well since it's tied to the date/time window config.

**Comment by lenaecb** [comment]
Update: We're going with this design, but still reviewing copy.

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/86850975-2954ed80-c080-11ea-888b-9c458852d8f0.png)
