### ISSUE TITLE
Understand the current forms library

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#10908]
**Idea:** 
Even though we as a team are still going through discovery, we know we are going to be at least using some sort of form or forms. Research creating a form using the current forms system is needed.

**Acceptance Criteria**
- We should be able to submit a simple form
- Should be able to understand and be able to discuss solutions using the existing forms system.

**Comment by mdewey** [comment]
I am able to:

-  create a simple form, that includes drops, radios, and text fields (and others).
-  Handle required fields and other validation; both hardcoded and dynamic logic
- Create custom Widgets 
![captured (1)](https://user-images.githubusercontent.com/1793923/86625609-57103880-bf93-11ea-830a-477e91c1ac8f.gif)

Current outstanding questions : 
- Can we use the authenticated user's data in a form
- Can we force authentication on a form
- Can we load external data into a form via an API?

These questions will be answered on #10714

**Comment by abuckley3385** [comment]
@mdewey this is fantastic thank you!
