### ISSUE TITLE
VOAS background jobs don't run in staging/prod

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#10905]
VAOS sidekiq jobs don't run in staging and production because of a NameError. http://sentry.vfs.va.gov/vets-gov/platform-api-staging/issues/139982/?query=is%3Aunresolved

Steps to reproduce:

1. log in
2. make an API call to VAOS backend (e.g. appointments)
3. wait 1 minute
4. make another call
5. Sentry will display a new NameError as above. Also in a staging console you can verify that the session token in Redis was not updated.

**Comment by saneshark** [comment]
This issue has now been resolved. JP noticed that there was an instance running old code in the load balancer list for staging. Shouldn't happen anymore.
