### ISSUE TITLE
Design - Inactive state of EC prompt on VAOS appts homepage

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10901]
Veteran who is eligible for EC at a VAMC who has EC enabled, but it is not currently available for the Veteran at this time because it's out of the window for EC set by VATs. 

AC:
- Veterans see EC prompt on VAOS appt homepage but the prompt is not actionable
- Need to include language about the Facility and the window in which EC requests are available

**Comment by rtwell** [comment]
![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/70d88267-615d-4f28-8f35-97cfc483c5a1)

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/86847832-fbb97580-c07a-11ea-8bdb-cea03b6a8490.png)
