### ISSUE TITLE
Access for Eric Oliver

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-team#10929]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Eric Oliver
- Please Provide your email.
   > eric.oliver@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > CMS, Software Engineer, Agile6

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtwqO4IZxL5hxGLukQ6UPtlCvqjcVluyvIzjvSgExv/vOJIibaB50sBGuT6eSqoNYwfGkjRjQvdTWhNafgcKggsygPlGUh3Ug4uxbMI1NzZzukGdGUYew+43VsgWxtr22XTNkg/PJBT7HjIPARzwgHWqLfVw2rYH5pldWruEZIYn6NBokIIZwlaccxj3MfCsJC90GlI/WC8HOjlYdrgmJYzHYGhAWskNKNpWF/YdgBQBShy8sQfE6tDhJVLSskFbZOlhpllOx5ri8jo0wgtC5+T+hMXJ/Ujoh/cYqvgJOa1S6R2NRsluP2stKzLrwDuTtUGwSi2vZtrDqQSlqMGSURAR8yNH04/l8S6+ber05fJl+eRNnhI8nVS5hW97p8zuuTwHPN5ul1vqdLZmU1QNejp9Q1chLYJ3fxzTF79HzOL4tQm7JN6P+sotudRbqW2c9LSoLgSR8iUzvuP/BUncQW1GSQYfT/UcGmYGP0AsJOVpPuJa7gGOe7LPUl5HHGY88= eric.oliver@agile6.com
```

- Grant AWS Console access?
  > YES
  - Please give a brief description for why you are requesting AWS access.

**Comment by olivereri** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by oksana-c** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by olivereri** [comment]
Changed AWS Console access to yes, based on new information.

**Comment by ElijahLynn** [comment]
Also need Eric added to @department-of-veterans-affairs/cms-infrastructure, which I think I can do, but if you are at it that would be great.

**Comment by ElijahLynn** [comment]
@Jeff-Hayter Eric already completed the eQIP and background check from his previous role on COMMS. So we should be good here, right?

**Comment by jsev-io** [comment]
@olivereri You should have access to SOCKS now. Please confirm when you have a moment.
Thanks!

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by jbritt1** [comment]
@Jeff-Hayter I believe @ElijahLynn needs this user to be given administrator level AWS permissions. I think when we did this for @indytechcook we laid that out and had you "double approve" for absolute transparency.

@ElijahLynn, correct me if I have made this assumption in error.

If not, @Jeff-Hayter please let us know if you approve of that level of permissions for this user before we approve department-of-veterans-affairs/devops#7231.

**Comment by Jeff-Hayter** [comment]
Yep, I think Dror now has final approval on these but I'll start a thread in slack.

**Comment by drorva** [comment]
Approved.

**Comment by jsev-io** [comment]
@olivereri Has been provided with AWS credentials and login instructions  - has also confirmed SOCKS proxy access.
Closing ticket.

**Comment by ElijahLynn** [comment]
Crosslinking the GitHub access ticket for my own convenience > https://github.com/department-of-veterans-affairs/github-user-requests/issues/3280
