### ISSUE TITLE
Forms library developer documentation update

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#10925]
## User Story 

As a VFS developer, I need to be able to find accurate information on the forms library, so that I can build forms on VA.gov efficiently and in an agile way. 

## Problem Statement 

Forms library developer documentation currently is stored primarily on ["the Gatsby site"](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms). However, there is additional information scattered in other sources, and much of it is out of date. 

How might we overhaul forms library developer documentation to better meet the needs of VFS developers?

**Comment by meganhkelley** [comment]
Forms library developer documentation user research: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/documentation-site/research/forms-library-docs-research-2020

**Comment by vbellissimo** [comment]
Cancelling/old task.
