### ISSUE TITLE
STEM - Printer Friendly Confirmation 

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#10939]
Create Print Preview prototype/content doc specific to 10203

Request that it be similar to https://vsateams.invisionapp.com/share/ATW7AI7QXCV#/screens or https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens/413780135_Caregiver_Confirmation_-_Desktop_-_V-02

**Comment by ccruzgra** [comment]
I have two print pages. One incorporates the link under "What happens after I apply?" as we have it currently on staging, and the other borrows content from the "After you apply" page that the link leads to. I'm going to recommend that we go with the version with the additional content.
![STEM-confirmation-print-out.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/a713d49e-0230-4606-b2cf-767515b31f4a)![STEM-confirmation-print-out2.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/70f385c4-24e0-425a-a627-c1732729bed9)

If this looks good, I will close the story and let Matt know this is what we're going with, @amyknox.
