### ISSUE TITLE
Analytics Reporting Request for BAM2 - Medical Device Ordering

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10937]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Medical Device Reordering Tool, BAM2 Leah Keeler

- [Leah Keeler] 

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._

    

## Timeframe for Analytics Requested
_We are looking for metrics at launch going forward 

## Analytics to Track Down
> Examples
> 
> - [ ] Total Traffic 
> - [ ] Orders completed 
> - [ ] Orders abandoned, which page 

## Which Product Questions are you trying to answer?

How may

## Other Helpful Questions to think through
- Who is your audience? Veterans who wear hearing aids 
- Why do you need this data? KPIs post launch 
- What are you hoping to find? baseline KPIs to improve post launch 
- What is your hypothesis that you're hoping the data will support? Increase online orders, decrease abandon from current eBenefits site 
- What area of the VA are you hoping to assess? medical Device Reordering
- How frequently do you need this data? daily for launch roll-out period, weekly after is fine 

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thank you @leahkeeler , confirming receipt! We'll be in touch soon.

**Comment by jonwehausen** [comment]
@bradl3yC @bsmartin-ep @leahkeeler 

We have verified the `--submission-failed` event is firing properly now! ✔️ 

![image](https://user-images.githubusercontent.com/48527022/87720754-6d807600-c783-11ea-8a7d-a94535fac668.png)


@bsmartin-ep Our tag drops the quantity ordered in as a custom metric and the product-ids-failed as CD 88. 

![image](https://user-images.githubusercontent.com/48527022/87720864-96087000-c783-11ea-84dd-8eab612d49b2.png)

----------------------
Without having appropriate test users for the partial scenario, we staged a DL push of what will happen for the partial scenario with: 
```
dataLayer.push({
'event': 'bam-2346a--submission-successful', 
'partial-failed': true,
'product-ids-successful': '14444 55555 66666',
'product-ids-failed': '11111'
});
```
![image](https://user-images.githubusercontent.com/48527022/87721321-40809300-c784-11ea-8ad3-497745560599.png)

@bsmartin-ep Our tag populated correctly for CDs 87-89


![image](https://user-images.githubusercontent.com/48527022/87721261-2941a580-c784-11ea-8890-54e579a6fbad.png)

**Comment by jonwehausen** [comment]
Closing per post launch
