### ISSUE TITLE
Access for Amen Ra

### ISSUE THREAD

**Issue by mojaray2k** [department-of-veterans-affairs/va.gov-team#1093]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Amen Ra
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > vsa-authenticated-experience, Front End Developer, GovernmentCIO
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGYtkfnFIvCjLysjO7fmAQRR+tcxwGjM06BJXdU/7HijmRIhwFskkhc8fX7TtcCCHopd+3huQE8uPmNM+XDOF1+GRcsMZi5eRA5ziM26dtbNGdRb5H/VUjWEK/S1FwIiDDYha55fGL/gmLlRlMeLQItRWwgbiryDmQNaVWvpORuisLpN45guojs729wATYkmQXl9bTRMg8AqHw/nRzKQ/T2HtFhlDeoGTcSGY8pPv6VADcU1mkmB9kCnrwwyBIRlyAZAzxwX0cXu4NmY6opgUaFyXH4DSh3vlyLEsq+Rh0RrKGedcs5iS8/a6vHVIXcsha2Upg/ugrfXWU1D8GCzI/ amenra@USRMonitors-MacBook-Pro.local

- [Grant AWS Console access?]
  >  NO
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by b00klegger** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Amen Ra

**Comment by Jeff-Hayter** [comment]
@ricetj Confirmed, please grant SOCKS access.

**Comment by ricetj** [comment]
Please follow the remaining instructions for configuring your SOCKS proxy.
