### ISSUE TITLE
Findings for accessibility staging review for VAMC Coatesville

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#10932]
**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This epic will contain the accessibility staging review findings issue tickets.

Site Access in Devshop -http://coatesvillehealthcare.web.demo.ci.cms.va.gov/coatesville-health-care/

## Point of Contact

**VFS Point of Contact:** Jennifer

**Comment by jenstrickland** [comment]
@SgardnerPMP 

With limited testing possible in the VA environment, the single issue ticket is all I have at this time. Once this is in Production, and I may properly test, I will add additional issues found to this epic.

There was a design issue found, which may be documented elsewhere:

* 2020-07-06-Coatesville-01 - Duplicated items in the sidenav: Health services and Contact us

![2020-07-06-Coatesville-01](https://user-images.githubusercontent.com/57469/87310596-2c226900-c4ec-11ea-9026-cb73ff8e8c9a.png)

**Comment by jenstrickland** [comment]
@SgardnerPMP Once Coatesville is in the production environment, please let me know and I will finish the staging review.

**Comment by jenstrickland** [comment]
@1Copenut For your visibility, the VAMC Coatesville staging review is paused until the work is in the non-public facing production instance.

**Comment by laflannery** [comment]
Closing because the issues are also covered in this epic #10931
