### ISSUE TITLE
ForeSee Survey Request for BAM2 Medical Device Reordering 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#10943]
# Request the ForeSee Survey

## What this form is for
Use this template to request adding the ForeSee Survey to your product.

ForeSee FAQ [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/foresee-readme.md)

## Description
*Medical Device Reordering Tool - Allows Veterans to reorder hearing aid batteries and accessories 

### Launch Date
7/8/2020 - tentative at this time due to backend issue with fulfillment system

### Staging URLs
https://staging.va.gov/health-care/order-hearing-aid-batteries-and-accessories/introduction

### Production URLs
https://va.gov/health-care/order-hearing-aid-batteries-and-accessories/introduction

Is there any way to add additional question to foresee splash screen? Thanks!

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the ForeSee Comment Card

**Comment by joanneesteban** [comment]
@leahkeeler the feedback survey is on Staging, but I'm receiving this page error. Let me know if this is works for you, and I can add it to Prod!

Unfortunately, we're currently limited to the feedback button (on the right hand side of the page) and the 5 star comment card on ForeSee. We're switching over to another survey tool in the next few months and can certainly update your survey then!

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/2a55990f-5ac1-48c0-9ec4-7290da7d7e76)

**Comment by leahkeeler** [comment]
@joanneesteban my bad - here is the URL https://staging.va.gov/health-care/order-hearing-aid-batteries-and-accessories/introduction

**Comment by joanneesteban** [comment]
@leahkeeler fysa this is in Prod:

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/e34a375e-954e-4eb8-9dc0-ca1b45ab2df0)

**Comment by leahkeeler** [comment]
Thank-you! Do you provide reports on how many stars the veterans give the app?

**Comment by joanneesteban** [comment]
@leahkeeler - we can add it to your KPI dashboard if you think that's one of your product's KPIs, or we can send it to you separately with [this request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/metrics-reporting-request-template.md)! Just note that it's currently getting pulled manually which is why we can't update more often, but when we switch over to Medallia in the next couple months it should be automated.

**Comment by leahkeeler** [comment]
Thank-you! If it's easy to add to dashboard that would be awesome. If it's hard, I'll just fill out the form - LMK I dont' want to add to your busy schedule - it is not a part of our KPIs

**Comment by joanneesteban** [comment]
Thanks! We'll add it to Domo, and let you know when that's ready.

**Comment by leahkeeler** [comment]
Hi @joanneesteban - checking in on this. No rush  :)

**Comment by joanneesteban** [comment]
Thanks, @leahkeeler ! We're adding it to Domo. 

Currently, there is:
- 1 survey response from 7/27/20: 5 stars.

**Comment by leahkeeler** [comment]
Hahaha one big one big one :)

**Comment by leahkeeler** [comment]
HI @joanneesteban - Can you let me know when this is  added to domo so I an close this ticket. THanks!
