### ISSUE TITLE
STEM: Add EDU team members to staging report distributions for UAT

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10942]
As an Education Services Team Member, I need to receive the daily spool and YTD reports out of the staging environment during UAT so that I can confirm that everything is working correctly with the 10203 prior to launch.

## Assumptions:
1. This work is completed behind a prod flag.

## Acceptance Criteria
1. The following email addresses are included in the staging distribution for the daily spool report:
    a. Luke Tickner - Lucas.Tickner@va.gov
    b. Brian.Grubb - Brian.Grubb@va.gov
    c. Tammy Hurley - tammy.hurley1@va.gov
    d. Joe Preisser - Joseph.Preisser@va.gov
    e. Joseph Welton - Joseph.Welton@va.gov
    
2. The following email addresses are included in the staging distribution for the YTD report:
    a. Luke Tickner - Lucas.Tickner@va.gov
    b. Tammy Hurley - tammy.hurley1@va.gov

3. The following email addresses are included in the Production distribution for the daily spool report:
    a. Luke Tickner - Lucas.Tickner@va.gov
    b. Brian.Grubb - Brian.Grubb@va.gov
    c. Tammy Hurley - tammy.hurley1@va.gov
    d. Joe Preisser - Joseph.Preisser@va.gov
    e. Joseph Welton - Joseph.Welton@va.gov
    
4. The following email addresses are included in the Production distribution for the YTD report:
    a. Brian.Grubb - Brian.Grubb@va.gov
    b. Tammy Hurley - tammy.hurley1@va.gov
    c. Joe Preisser - Joseph.Preisser@va.gov

5. The following recipients are to be removed from the Production distribution of the YTD report:
    a. Anne Kainic
    b. Brandy Terrell
    c. Carolyn McCollam
    d. Christopher Marion
    e. Christopher Sutherland
    f. Ian@adhoc
    g. Peter Chou
    h. Peter Nastasi
    i. Robert Shinners

## Supporting Artifacts:
1. N/A

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4539

**Comment by sonntag-adam** [comment]
Closing out story.
