### ISSUE TITLE
STEM: Update 10203 Intro based on user testing updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10958]
As a developer, I need to update the 10203 workflow due to changes recommended from user testing interviews so that the applicant's have the best experience when completing the application.

## Assumptions:
1. This work is completed behind the feature flag #7271.
2. Updating breadcrumbs is not included in this issue and will be completed in a subsequent issue. 

## Acceptance Criteria
1. On the STEM Intro page: 
   a. When a user is logged in but has more than 180 days of entitlement, the following text in the yellow warning alert has been updated:

    > You may not be eligible

    is replaced with: 

    > It appears you're not eligible

   b. When a user is logged in but has more than 180 days of entitlement, the following text in the yellow warning alert has been updated:

    > Our entitlement system shows that you have more than 6 months of education benefits remaining

    is replaced with: 

    > Our entitlement system shows that you have the following benefits remaining: **NN months, NN days**
If you apply and you’re not eligible, your application will be denied. 

   c. The “Determine Eligibility” text has been updated as follows: 
    > **Education benefit:** You’re using or recently used Post-9/11 GI Bill or Fry Scholarship benefits. 
    > **STEM degree:** You’re enrolled in a bachelor’s degree program for science, technology, engineering, or math (STEM), or have already earned a STEM bachelor’s degree and are pursuing a teaching certification. [See eligible programs ](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf)
    > **Remaining entitlement:** You’ve used all of your education benefits or are within 6 months of doing so when you submit your application. [Check your remaining benefits](https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/)

   d. The following text has been updated: 
    > **What if I need help filling out my application?** A School Certifying Official (SCO) or an accredited representative, like a Veterans Service Officer (VSO), can help you fill out your claim.

    is replaced with: 

    > **What if I need help filling out my application?** An accredited individual, like a Veterans Service Officer (VSO) or a Veteran representative at your school, can help you fill out your application. [Get help filing your claim](https://staging.va.gov/disability/get-help-filing-claim/)

   e. Respondent burden, located at the bottom of the page, is updated from 5 minutes to 15 minutes. 

## Supporting Artifacts:
1. [Final Version of the Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md) 
   a. The following word document tracks changes between  7/7 content doc & current version of the content doc that is linked above: 
[22-10203-ContentReconciliation-20200720 v2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4953780/22-10203-ContentReconciliation-20200720.v2.docx)
2. [Final Prototype](https://bahdigital.invisionapp.com/share/YFIAEHK8U2W#/screens)

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13560

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-22 at 11.23.11 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/87c9448b-40b4-4fae-8072-485e2d15926e)

**Comment by sonntag-adam** [comment]
[Uploading... Screen Shot 2020-07-22 at 12.09.38 PM.png ]

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-22 at 12.18.12 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6a194321-f3d2-4521-996d-b9e988b4bca3)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-22 at 12.19.13 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a053d4a8-1793-4836-9bba-4bb794eeb6a5)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-22 at 12.43.05 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/15f70da9-c574-4e79-b8e2-5480a620640c)
##
![Screen Shot 2020-07-22 at 12.43.17 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1d7ab212-f9de-4442-8d0f-3468fce05486)
##
![Screen Shot 2020-07-22 at 12.43.22 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8161cc1f-a2ea-443c-b4d6-12f95fe406ce)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9857&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
Need Staging user with entitlement to properly test.

**Comment by sonntag-adam** [comment]
Extra "You:" needs to be removed
![Screen Shot 2020-07-29 at 5.14.42 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/fe2bb225-a752-48fb-90c9-a74f197abcb4)

**Comment by ksantiagomorgan6** [comment]
typo fix: https://github.com/department-of-veterans-affairs/vets-website/pull/13657

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-30 at 8.16.41 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/341839ab-82c1-4446-a515-5a84663145c3)

**Comment by dneel-bah** [comment]
EDU has agreed to launch with an MVP without pulling entitlement / enrollment data from EVSS.  The re-validation of AC3 in staging will be handled in #12734 once the test data is available in the staging environment.  Closing this story because it has been validated in the local/dev environment.
