### ISSUE TITLE
Design intent Collaboration [MVP learning center templates]

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10955]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> **requesting team** design intent collaboration meeting completed
- [x] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources
- [x] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)
- [Template content requirements - FE and CMS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md)
- [Mural mockups](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)
- [Epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10111)

## Meeting attendees from **Public Website team**
- Designer(s) (required): **@rtwell  **
- Product Manager (optional): ** @MickinSahni (interim) **
- DEPO design lead (required as applicable): ** @jenniferlee-dsva  @rtwell  **

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET) 
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Crystabel will reach out as needed_

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by CrystabelReiter** [comment]
Hi @jenniferlee-dsva ! for scheduling we have these time blocks available:

ET:
Friday, 7/10 - 2-2:30 PM 
Monday, 7/13 - 3:30-4 PM
Tuesday, 7/14 - 11:00 AM- 12:00 PM
Wednesday, 7/15 - 11:30 AM- 12:00 PM
Thursday, 7/16 - 1:30-2:30 PM
Friday, 7/17 - 2-2:30 PM

**Comment by jenniferlee-dsva** [comment]
@CrystabelReiter @emilywaggoner - Hello, I can't access Google cal on VA network; can you please provide some other means of scheduling? 

@rtwell and I are available  Friday 7/10 at 2pm ET.

**Comment by andaleliz** [comment]
@CrystabelReiter @emilywaggoner, can you please include me as optional?  I'm on PTO Friday, but I'll join if I'm able to at that time. I think it'll be useful to sit in since I'm running the research study.  Thanks!

**Comment by MickinSahni** [comment]
Friday 7/10 at 2pm ET works for me

**Comment by meganhkelley** [comment]
Just scheduled this for Friday @ 2 pm ET — my first invite sent via my VA email! Let me know if there are any issues with that invite; I won't be attending the meeting.

**Comment by jenstrickland** [comment]
From @sshein 
> I have to go but have a few small questions for consideration from platform: 
> 1) What are our thoughts about having two blue buttons right next to each other? Should there only be one “primary”?  
> 2) should the “File for disability” buttons be green? I forget the guidance regarding green buttons. 
> 3) For that new little “back to top” feature, if we componatize it it would be nice to get thoughts on when we suggest putting it on a page and where .

**Comment by rtwell** [comment]
thanks for the Qs and recording them here @jenstrickland and @sshein . Answers are…

> 1. What are our thoughts about having two blue buttons right next to each other? Should there only be one “primary”?

I have no issue with this. They are both primary actions (one is not more important than the other). we implemented 3 primary buttons [on Pittsburgh](https://www.va.gov/pittsburgh-health-care/) and have not has any usability issues as far as I am aware.

> 2. should the “File for disability” buttons be green? I forget the guidance regarding green buttons.

no, I don't believe so. Green primary buttons are for actionable items/entry into the tool on the tool page itself. these just point to the tool landing page. 

> 3. For that new little “back to top” feature, if we componatize it it would be nice to get thoughts on when we suggest putting it on a page and where .

Yes! Once we flesh out the guidance for all of these templates, _On this page jump links_ and _Back to top_ will both need logic and guidance to make sure they are used appropriately. I believe the discussion @jenniferlee-dsva  and I had regarding it's use was logically connecting it to the number of `h2`s a page had (i think we landed on a minimum of 3). This one gets a little tough to govern because there would be nothing stopping an author from creating a page w/ 3 very short sections and thus getting _Back to top_ on that short page. BUT, like Pittsburgh, we've seen some non-ideal choices made with authoring some of its CMS pages, and while they aren't perfect, they still work. examples include: the [policies page](https://www.va.gov/pittsburgh-health-care/policies/) (the first 2 `h2`s only have a single link) and [programs](https://www.va.gov/pittsburgh-health-care/programs/) (do we need jump links here? probably not).

**Comment by jenniferlee-dsva** [comment]
Confirming @rtwell regarding the back to top links. I've asked for this to be built with some logic/governance within Drupal, per [template requirements here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md).  The desired outcome is that if the author can check the TOC checkbox only when there are at least 3 H2 headers on the page; and enabling the TOC links will force the back to top links. 

> - Optional: On this page TOC links – When enabled, at least 3 H2 sections are required; TOC link text generated by the H2 text.
> - Back to top links - required if TOC links are enabled: displays at the end of each H2 section

**Comment by jenniferlee-dsva** [comment]
Is this collaboration review okay to close as completed? @meganhkelley

**Comment by jenstrickland** [comment]
Please hold this open until end of day 7/15. Accessibility still needs to provide guidance.

**Comment by andaleliz** [comment]
@rtwell question about the pagination in these templates. Small details, but I noticed the design system uses `Prev` vs the LC `Previous`. Also, the LC templates have a `...` showing the final page number after the `...` where the pagination I see on production shows 5 pages at a time with no ellipses.  Are we testing a new pagination format with the templates? Thanks!

**Comment by rtwell** [comment]
This is probably a disparity between our Sketch library and production. I would default to the production version, and if you're feeling up to it, you can [fill out an issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new/choose) to alert VSP folks and they can update the Sketch library.

**Comment by andaleliz** [comment]
Yep, you're totally right. Thanks for pointing that out.  Looks like VSP is [already on it](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/253)!

**Comment by andaleliz** [comment]
Yep, there is a disparity. I had a hard time even finding it in the sketch library since it doesn't have the blue circles/numbers to start.   Looks like VSP is [already working on getting this synced up](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/253)!

**Comment by jenniferlee-dsva** [comment]
Is this okay to close @meganhkelley ?
