### ISSUE TITLE
Design feedback - Staging Review - 'Erie-health-care' VAMC-upgrade website

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#10950]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**
- Add padding-left to the “last updated” thing at the bottom of the pages
- Make sure all the pages are properly displayed in the left navigation. Some pages are not showing up (History, Jobs and Careers, Internship and Fellowships, Volunteer or Donate). 
- For jobs and careers page, breadcrumbs don’t match the page (Home > VA Erie). Please match the breadcrumbs to the current page
- On the “Work with us” page, “Visit our internships and fellowships page” text is not linked, make sure to link it up if the surrounding copy sets the expectation of having a link

**Try:**
- “On this page” component for all pages: Try capping the width of the “on this page” section so that the hover state is the same length of the text, instead of the full width of the container. Same with the focus state - make sure whatever width gets applied, the focus state follows that too.

**Consider:**
- Consider for short pages with only 1 item in “on this page”, hiding the “on this page” component instead.
- Consider pages with multiple items in the “on this page” component to have a “back to top” link after each section.

**Questions:**
- Should all pages have a “Last updated X date” line at the bottom? Not all of them do.

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by SgardnerPMP** [comment]
Items completed for this Review:
DO: 
* Last updated is a Devshop instance only and will not appear in production (update suggested to CMS)
* Left Nav has been updated and all pages selected for Menu now appear properly
* Breadcrumbs have been updated for all pages.
* All links to other pages have been updated.

TRY: 
* Design changes are not within VAMC's purview,  Suggestion provided to CMS and VHA for design approval and changes.

Consider:
* Agreed, items with only one item on Short pages have table of contents removed
* "Back to Top" link item has been requested in CMS design backlog.
