### ISSUE TITLE
STEM: UI & Content Updates - remediation during testing 

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#10963]
As a prototype developer, I need to incorporate key updates to the prototype and content document based on early test sessions so that the team can validate the solutions during subsequent testing sessions.  

Tasks
- update STEM eligibility alert
- update benefit-only eligibility alert 
- update content doc

**Comment by ccruzgra** [comment]
@amyknox Could we please remove the step for updating the content doc and do that with our post-test updates? I don't want there to be a mix up if DN is linking to our current doc in his stories.

**Comment by ccruzgra** [comment]
If we don't foresee other updates needed for testing, this can be closed, @amyknox.
