### ISSUE TITLE
Access for Nick Bloom

### ISSUE THREAD

**Issue by nickbloom** [department-of-veterans-affairs/va.gov-team#10969]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Nick (Nicholas) Bloom
- Please Provide your email.
   > nick.bloom@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > CMS Team, UX Designer, Agile Six

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDo1Xx9ZtbOZDWW/ooqlMnt572HWd7m7qvt6z/nIrfPasT5G2384eDtNxdU9EwC9t7NBNlXd8TkDI11x6l7t5Ep94WCBJtl5Gn17snOvFELL5nPsVnHsXNKTEwF4ktt8LmHKOt9sZs7$nick.bloom@Agile6-A29.local
```

- Grant AWS Console access?
  > NO
  - Please give a brief description for why you are requesting AWS access.

**Comment by oksana-c** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@nickbloom 

Did you edit the end of your key here manually --> "$nick.bloom@Agile6-A29.local" I'm curious about it's lack of a space between the key and the comment

**Comment by jsev-io** [comment]
@nickbloom Please confirm you can connect to the SOCKS Proxy.
Thanks!

**Comment by ricetj** [comment]
If you need help please reach out in the support channel

**Comment by nickbloom** [comment]
> @nickbloom
> 
> Did you edit the end of your key here manually --> "$[nick.bloom@Agile6-A29.local](mailto:nick.bloom@Agile6-A29.local)" I'm curious about it's lack of a space between the key and the comment

Sorry was out on PTO. I think I might have...is that a problem?

**Comment by jsev-io** [comment]
@nickbloom Does your key work? Do you have access to SOCKS?
