### ISSUE TITLE
STEM: Create QA documentation in advance of STEM Staging Review	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10968]
As a member of the BAH QA team, I need to ensure that all STEM testing documentation is completed so that the team is prepared in advance of the STEM Staging review with VSP. 

## Assumptions
1. In alignment with [staging review prep guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation), the following items have been completed in advance of the staging review: 
    a. Axe scans in daily development
    b. Axe scans in end-to-end tests
    c. Color tests
    d. Content resize check
    e. Keyboard navigation check
    f. Screen reader tests

## Acceptance Criteria
1. Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
2. Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
3. Link to verification that accessibility checks are complete using ONE of the following:
   a. (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc). 
   b. Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
4. List of known issues (with links to tickets when applicable)

## Supporting artifacts
1. Checks that must be completed prior to staging review included here: [Accessibility staging review preparation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#accessibility-staging-review-preparation)

**Comment by sonntag-adam** [comment]
AC 1 and 3: https://dsvavsp.testrail.io/index.php?/plans/view/495

AC 2: 
Coverage for References: https://dsvavsp.testrail.io/index.php?/reports/view/125
Summary(Defects): https://dsvavsp.testrail.io/index.php?/reports/view/126

**Comment by sonntag-adam** [comment]
Closing story.
