### ISSUE TITLE
EDU: Add EDU users to staging YTD report distribution

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10970]
As an Education Services team member, I need to receive the YTD report from the staging environment so that I can confirm the routing updates have been successful.

## Assumptions:
1.

## Acceptance Criteria
1. The following people are added to the YTD Report distribution in the staging environment:
    a. Da Silva, Ricardo, VBAVACO <Ricardo.DaSilva@va.gov>
    b. Ziolkowski, Matthew VBABUF <matthew.ziolkowski@va.gov>
    c. Welton, Joseph VBAVACO <Joseph.Welton@va.gov>
    d. Preisser, Joseph, VBAVACO <Joseph.Preisser@va.gov>
    e. Grubb, Brian D., VBAVACO <Brian.Grubb@va.gov>
    f. Johnson, Michael <Michael.Johnson19@va.gov>
    g. Pietrosanto, Kyle T. <kyle.pietrosanto@va.gov>

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4489

**Comment by sonntag-adam** [comment]
Closing out story.
