### ISSUE TITLE
Determine Scope of Issue

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#10974]
## Description
In order to fully understand the effects of this, we need to understand if this was a one off occurrence or if this is a systemic problem throughout the code base.

## Definition of Done
- Identify & Document the specific failure point
- Document additional failure points that are uncovered

**Comment by johnpaulashenfelter** [comment]
Summarizing from multiple conversations, code reading, etc:

* The majority of vets-api JSON endpoints return snake_case results, as documented in our swagger docs
* The `olive_branch` Rack middleware provides case conversion (eg to camelCase) if a custom HTTP header is included in the request.
* There is *very* little code coverage in vets-api for the request specs _with the camelCase inflection_

A quick search of vets-api, verified by more detailed code reading, shows six request specs that include an inflection: https://github.com/search?q=org%3Adepartment-of-veterans-affairs+HTTP_X_KEY_INFLECTION&type=Code

A quick search of the frontend, vets-website, shows 31 instances (though some are load test configurations) where the client *requests* camelCase with the inflection http header: https://github.com/search?q=org%3Adepartment-of-veterans-affairs+X-Key-Inflection&type=Code

Effectively, returning camelCase inflections from our well-tested/well-covered codebase is mostly missing specs, which means that unless the client handles snake_case (or the API endpoint diverges from the norm of vets-api and directly serves camelCase attributes) there is a clear potential for backend inflections to change the *output of the JSON for the client*. This is what happened in this case.

**Comment by johnpaulashenfelter** [comment]
Added the specific request spec that would have caught the error in the `validPdf` vs `validPDF` inflection issue, code is in https://github.com/department-of-veterans-affairs/vets-api/pull/4544
