### ISSUE TITLE
Review automation (if any) between swagger, jsonapi RSpecs/mocks, and serializers

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#10979]

**Comment by erluti** [comment]
I had opened this ticket when looking at gem upgrades related to Rails 6.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7572

Looks like we do test some of the endpoints against the swagger, but the way we do it isn't supported anymore

**Comment by erluti** [comment]
Considering this work https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/11585 and upcoming Pact work, we've got much better coverage of this
