### ISSUE TITLE
CT-Search: Update VETTEC search functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10985]
As a Comparison Tool user, I need the search functionality to be smarter so that results are found when I have small typos.

## Assumptions:
1. This story is completed behind the feature flag #10615 
2. The fuzzy match should leverage database capabilities.
3. This fuzzy match capability will not affect the autocomplete end point.
4. The alias search is not applicable to VETTEC.

## Acceptance Criteria
1. The free text search on the VETTEC search results page label 

    > "City, VET TEC program or provider" 

    is replaced with 

    > "Program, provider, or location"

2. The 'physical institution zip code' from the WEAMS data is searchable within the Comparison Tool for VETTEC providers.
3. VETTEC search results return matches that partially match the following search criteria:
    a. City
    b. Institution Name
4. The institution search results are sorted in the following order:
    a. % Match
    b. Provider Name

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
`vets-website` PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13545
`gibct-data-service` PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/686

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-21 at 1.28.01 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3da1fabe-facc-41fe-86b5-b6f48735a89f)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-22 at 8.34.24 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d891411d-9ad9-40c6-8121-e31b56563273)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-22 at 8.53.04 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ae1308ac-1465-4dcc-b5ca-8398088bb967)
##
![Screen Shot 2020-07-22 at 9.26.23 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/85d9659a-f50e-4ebe-947e-9cccf9c83a1a)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/561&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
@sonntag-adam UX has reviewed and this looks good!

**Comment by sonntag-adam** [comment]
Closing story.
