### ISSUE TITLE
CT-Search: Add Scorecard alias data element to version data

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10983]
As a developer, I need to add the Scorecard alias data element to the API pull request in GIDS so that the data can be included in version generation for search.

## Assumptions:
1. This alias replaces IPEDS HD alias. 

## Acceptance Criteria
1. The alias data element is retrieved and stored by the API Fetch request within GIDS.
2. The alias data element is included in the version generation. 
3. The comparison tool search functionality includes the scorecard data element when a search is executed.

## Supporting Artifacts:
1. [College Scorecard Documentation](https://collegescorecard.ed.gov/data/documentation/)

**Comment by elder-joseph** [comment]
Associated PRs:
Full PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/695
Database Specific PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/696

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testrail test case:
https://dsvavsp.testrail.io/index.php?/tests/view/11113&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by delli-gatti-michael** [comment]
This is now live on Staging. Closing this issue
