### ISSUE TITLE
[Discovery] - Set up card sorts for Learning Center MVP audience and top tags

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#10982]
Set up card sort in Optimal Sort for Learning Center MVP.
Acceptance criteria

- [x] Write instructions
- [x] Set up cards
- [x] Set up categories based audience, topic, and articles list in ticket #12329

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA can you please leave a comment on this issue when you have reviewed and finalized the list of audience tags? I'm assuming any changes you make will be updated [on the list ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#audience-tags) of all tags.

**Comment by jenniferlee-dsva** [comment]
Hi @andaleliz CC @DanielleThierryUSDSVA - can you please reference the other card sort ticket you created? I uploaded my comments for you there along with the list of audience tags. (In a Word doc)

@DanielleThierryUSDSVA - please refer to the list of audiences on that Word doc. You can also use this list here - which is the same list but in the context of actual wip article titles for the card sort: ticket #12329

**Comment by andaleliz** [comment]
@jenniferlee-dsva I listed the other card sort ticket as a dependency to this one. #11012, @DanielleThierryUSDSVA
