### ISSUE TITLE
Running prod build doesn't recognize existing drupal cache

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#10981]
## Issue Description
1. Run `yarn install`
1. Run `yarn fetch-drupal-cache`
1. Run `NODE_ENV=production yarn build --buildtype vagovprod`

Drupal content then gets pulled from `https://prod.cms.va.gov` despite it already having been downloaded.

 
Not sure if this should be resolved by changing how these commands operate, or by clarifying docs?

See also: https://dsva.slack.com/archives/CBU0KDSB1/p1594149355379300

P.S. Same issue if step 3 is `yarn build-analyze`

**Comment by meganhkelley** [comment]
Docs should be clarified accordingly

**Comment by rmessina1010** [comment]
Expired. Closing.
