### ISSUE TITLE
Consider an acronym style guide

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#10986]

**Comment by erluti** [comment]
I think it would be good to explicitly define when we expect acronyms to be inflected or if they should be spelled out.  This documentation should go with other onboarding information for platform users so our code can consistently deal with these as we go forward.  I think it would also give us something to point to when our output doesn't match front-end expectactions.

**Comment by erluti** [comment]
Some existing acronyms were worked through on this ticket https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10976.  `ICN`, `PCIU`, and `PDF` were all called out to be considered here

**Comment by alexpappasoddball** [comment]
This has been considered and discussed, however no action item is needed at this time.  Closing issue
