### ISSUE TITLE
Express Care requests statuses in Upcoming appts list

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10993]
As a Veteran who can use the Express Care feature, I want to know the different statuses of my Express Care appointment that show in my Upcoming Appointments list. 

## Acceptance Criteria:
- [ ] For EC status "Submitted" we will show "Submitted" in UI
- [ ] For EC status "Cancelled", "Cancelled - Other" we will show "Canceled" in UI
- [ ] For EC status "Cancelled - Unable to reach Veteran" we will show "Canceled - Unable to reach Veteran" in UI
- [ ] For statuses that show "Escalated to Tele/Urgent Care - Phone" or "Escalated to Tele/Urgent Care - Video" we will show "In progress" in UI
- [ ] For EC requests - cancellations should not drop from the Appt list
- [ ] Remove directions and phone number from EC card

## Testing considerations:
- Need to have SM/Marcy test all of these scenarios once implemented

**Comment by lenaecb** [comment]
@rtwell - how do we want to handle the color coding for these statuses?
- Submitted - green
- In progress - gold
- Complete - no color
- Canceled - red

Thoughts?

**Comment by rtwell** [comment]
i think the complete could also be green? maybe we swap an icon or something. i will noodle on this.

**Comment by lenaecb** [comment]
Made a slight tweak to the status (updated in the issue body above) based on some user feedback from yesterday.

**Comment by jbalboni** [comment]
@rtwell @lenaecb Do we have card mockups for each of these statuses? There's explanatory text usually under the main status text that isn't defined for all the statuses.

**Comment by lenaecb** [comment]
Issue updated to focus on key statuses for interim EC requests showing in upcoming appts
