### ISSUE TITLE
[Epic] [Engineering/Drupal] Learning Center MVP

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#10992]
## Product Outline
[learning-center-mvp/product-outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)

### What must be true in order for you to consider this epic complete? 
Engineering re: learning center mvp is complete along with any necessary artifacts 

## Resources

- [WIP wireframes](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)

## Breakdown of engineering tasks and tickets
- [x] Dev discovery (Sprint 27) (~to be~ created) (assignees: nick, kelson, steve w.) - #11435
- [ ] ..

**Comment by FranECross** [comment]
All tickets are completed/closed; closing
