### ISSUE TITLE
Design intent Collaboration: CT Filters

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#10996]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> **requesting team** design intent collaboration meeting completed
- [x] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources
- [x] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/college-scorecard/product-outline.md)
- Lo-fi mockups: https://bahdigital.invisionapp.com/share/2PIAEGICD48
  - Search Results with new filters (Gender, Specialized mission, Religious affiliation) in sidebar. Tags on School cards https://bahdigital.invisionapp.com/share/2PIAEGICD48#/screens/296044397
  - Search Results with filters in sidebar. Incorporating "More info" pattern in lower part of sidebar https://bahdigital.invisionapp.com/share/2PIAEGICD48#/screens/296044406
  - Search Results with new sidebar filters. "More info" elements open https://bahdigital.invisionapp.com/share/2PIAEGICD48#/screens/296044407
  - School profile with tags for filter/data display
https://bahdigital.invisionapp.com/share/2PIAEGICD48#/screens/296044411
  - School profile with tags & icons for filter/data display https://bahdigital.invisionapp.com/share/2PIAEGICD48#/screens/296044412

## Meeting attendees from **requesting team**
- Designer(s) (required): **Amy Knox, Cindy Cruz, Jen Jones**
- Product Manager (optional): **Darrell Neel (in absentia)**
- DEPO design lead (required as applicable): **Matt Self**

## Scheduling
- Would it be possible to hold this design intent on Thursday, July 16 at 1pm (ahead of the CT Ratings discussion)? We have a conflict 2-2:30 so can't do the later block. 
If not, 2pm on July 17 would be our 2nd choice. 

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by rtwell** [comment]
Please include me in this meeting (Matt Self is the DEPO lead for this project, while I am the DEPO design lead)—thank you!

**Comment by CrystabelReiter** [comment]
Scheduled July 16 at 1pm, if not enough reviewers can make it, we can talk about rescheduling for Friday

**Comment by ccruzgra** [comment]
Hi @emilywaggoner and @CrystabelReiter We've put together some initial mockups for this project: 
https://bahdigital.invisionapp.com/share/2PIAEGICD48  

We have our standard Search Results Page, and then a version using the Additional Information component, plus two profile pages.

**Comment by amyknox** [comment]
IA Input from Mikki #11361
