### ISSUE TITLE
[Epic] [Research-Design] Learning Center MVP

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#10991]
## Product Outline
[learning-center-mvp/product-outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)

### What must be true in order for you to consider this epic complete? 
Research and design re: learning center mvp is complete along with any artifacts 

## Breakdown of research/design tasks and tickets
- tickets we need so far are below!

**Comment by jenniferlee-dsva** [comment]
this was completed for 1.0-1.1, so closing.
