### ISSUE TITLE
[Decisions] Decide on structure for managing access by VSA team

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#110]
# Description

Currently, access is largely managed per app developer, but often application team permissions/settings should be similar across that application team. We don't have much process for this.

# AC

- [x] Decide whether or not VSA developers should be treated as a single group for access permissions, or managed per application team
- [x] Determine process for deciding which application teams get access to which production systems
- [x] Determine structure for managing application teams and tracking developer membership in those teams

**Comment by b00klegger** [comment]
> Decide whether or not VSA developers should be treated as a single group for access permissions, or managed per application team

Thinking about this a little, I have had some contact with `bah-vfs-developers` recently. They are not running their own infrastructure; an application team I suppose. Contrast with `dvp` (whatever that is) they run their own instances, VPCs etc. 

I propose we use this (run your own stuff) as a condition for being in our 'group' versus another group. Currently we would have three groupings in our account, matching project tags placed onto some resources: appeals, dvp, vagov. We would follow the current naming convention <group>-<project>-theme. Examples include `dsva-vagov-devops`, `dsva-appeals-developers`. Could include `psf-dvp-devops` if proposal accepted.

For application teams on OUR project that we group them all under the umbrella `dsva-vagov-developers` or whatever you want to call it.

**Comment by b00klegger** [comment]
Group ideas and some sample policies to attach.

`<group>-<project>-devops`
- AdministratorAccess
- ExplictDenyAccessToAppealsBucketsToEveryoneInTheGroup

`<group>-<project>-powerops`
- PowerUserAccess
- ExplictDenyAccessToAppealsBucketsToEveryoneInTheGroup

`<group>-<project>-developers`
- ReadOnlyAccess
- ExplictDenyAccessToAppealsBucketsToEveryoneInTheGroup
- SSMApplicationLowerEnvironmentAccess

`<group>-<project>-powerdevs`
- ReadOnlyAccess
- ExplictDenyAccessToAppealsBucketsToEveryoneInTheGroup
- SSMApplicationLowerEnvironmentAccess
- SSMApplicationProdEnvironmentAccess

**Comment by wyattwalter** [comment]
That's a really good point about there being a big difference between folks who are contributing to vets-api/vets-website and those that are managing infra within the AWS account. I don't think we have a sense yet about how many would fall into the latter category.

I'm imagining that most folks who run infrastructure would be on an explicit contract with some expectation that they fully operate the service. Those would most likely have separate Terraform environments as well.

**Comment by b00klegger** [comment]
Maybe a terraform group? Granted we are frequently adding new services managed by the tech but .... what if we had a group that allowed access to the DynamoDB table and could also run the apply? This seems like it is the principal reason (lately) we've been ping'd for lack of permissions. 

The apply is a bit tricky ... Seems like a lot of EC2, CloudWatch, Lambda, VPC. RDS is a little weird but sure people try to provision databases with TF. No IAM management for this group, just PowerDevs type stuff. 

This might be a better approach for the Ops-type engineer we're going to be encountering more often on the project.

**Comment by ricetj** [comment]
Will be sending proposal tomorrow morning.

**Comment by ricetj** [comment]
Proposal sent, waiting for approval and feedback.

**Comment by ricetj** [comment]
Approval from DSVA on the proposal, planning/ mapping session conducted on 7/15/2019.

**Comment by ricetj** [comment]
closing ticket  and work will continue in this epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/683
