### ISSUE TITLE
Create Express Care tab to hold all Express Care appointments regardless of status

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11002]
As a Veteran using Express Care option, I want a quick and easy way to see all my Express Care requests in one spot since their statuses change so often. 

## Acceptance Criteria:
- [ ] User sees Express Care tab if their site has Express Care enabled
- [ ] When user logins out and back in, load 'upcoming appointments' list
- [ ] User can see all their Express Care requests in one location
- [ ] If user does not have any Express Care requests display - "You don’t have any Express Care screenings
You can request a screening now, or you can call your [VA medical center](https://www.va.gov/find-locations) to schedule an appointment.
Request Express Care screening" 
- [ ] All Express Care statuses are shown in this list (SM Status = Status show in UI)
     - Submitted = shows "Next step: A VA health care provider will contact you today about your request."
     - Cancelled = Canceled
     - Resolved	= Completed
     - Escalated to Tele/Urgent Care - Phone = "Next step: A VA health care provider will follow up with you today."
     - Escalated to Tele/Urgent Care - Video = "Next step: A VA health care provider will follow up with you today."
     - Cancelled - Unable to reach Veteran = Canceled - Unable to reach Veteran
     - Cancelled - Other = Canceled
     - Resolved by MSA - Scheduled with LIP = Completed
     - Resolved by LIP = Completed
     - Resolved by LIP - Schedule Follow Up = Completed
     - Resolved - Referred to ER = Completed
     - Cancelled = Canceled
- [ ] The tab design takes into account a11y standards
- [ ] The tab design doesn't wrap in mobile

## Open questions:
- [ ] what a11y considerations do we need to account for
- [ ] how will this function/show in mobile
- [x] confirm statuses and supporting status text (need @peggygannon eyes)
- [x] confirm mock up (@ryan)

## Design mock up:
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/fba9ff06-1800-4c96-bc6f-05c2655ebf4d)

**Comment by lenaecb** [comment]
Open items we need to address for this ticket:
- confirm statuses for this iteration and helper text that goes along with them (in-progress)
- confirm final mocks for EC status/cards

cc: @rtwell @peggygannon

**Comment by peggygannon** [comment]
@lenaecb @rtwell here is document with EC statuses (vetted by me and Danielle)

[https://app.zenhub.com/files/133843125/76b8ccdd-6ba1-4301-ad7f-167c88af3b7e/download](https://app.zenhub.com/files/133843125/76b8ccdd-6ba1-4301-ad7f-167c88af3b7e/download)

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/87543227-5aca4c00-c672-11ea-8764-75932b0c36cf.png)

**Comment by rtwell** [comment]
updated cards @jbalboni 

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/ab1de685-9951-456c-962a-deeaac34abdf)

**Comment by lenaecb** [comment]
@jbalboni - @narin and I chatted, and due to the limitation of the current endpoint, we probably need to decouple the Express Care tab (when it does/does not show) from the facilities call. This will ensure that if you have any EC appts whatsoever, they will still show even if the window for EC is closed. 

Can we set the logic for the EC tab to be based on whether you have _any_ EC requests (regardless of status) to show the EC tab and said EC requests?

**Comment by jbalboni** [comment]
@lenaecb Yeah, it's going to be somewhat painful, but yes, we can do that.

**Comment by narin** [comment]
Sorry @jbalboni.  When checking the `direct_scheduling_facilities` response, I wrongly assumed that the `expressTimes` returned would apply to all weekdays.  Assuming you haven't started, I can work on adjusting the tabs to display based on the existence of EC requests tomorrow (Tuesday).

**Comment by jbalboni** [comment]
@narin Nope, no worries I assumed we'd have more info, too. I started on updating the tabs this evening, should be able to finish it up in the morning.
