### ISSUE TITLE
Analytics Reporting Request for Charles

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#11003]
# Metrics Reporting Request

## Description
- Leslie Byford reached out over Slack to request VA.gov metrics for an upcoming TP briefing next week

## Metrics Requested
- Overall traffic over the last month
- VA.gov top pages of interest over the last month
- How many profile updates over the last month
- How many disability compensation claims have been filed over the last month
- How many pension submissions over the last month
- How many burial submissions over the last month

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

### Due Date
- End of week (7/10)

## Description
Who is this request for?

- Charles Worthington

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
[Domo Dashboard](https://va-gov.domo.com/page/694925990)

**Comment by jonwehausen** [comment]
[Congressional Briefing_VA.gov Metrics_June1-July9.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4904701/Congressional.Briefing_VA.gov.Metrics_June1-July9.pdf)

**Comment by jonwehausen** [comment]
Have delivered a PPT and PDF copy to Leslie Byford over slack (cannot upload ppt version here)

**Comment by joanneesteban** [comment]
Thanks, @jonwehausen ! Moving to QA & we can close when we hear back from Leslie.

**Comment by jonwehausen** [comment]
Leslie requested to update with the latest data from the weekend...Delivered her the copy of this morning. 

[Congressional Briefing - VA.gov Metrics - June 1 - July 12 2020.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4912837/Congressional.Briefing.-.VA.gov.Metrics.-.June.1.-.July.12.2020.pdf)

**Comment by jonwehausen** [comment]
Also delivered a powerpoint copy over Slack to Leslie.

**Comment by jonwehausen** [comment]
Following our conversation yesterday, will need to replace data with COVID FAQ metrics Month over Month

**Comment by jonwehausen** [comment]
Confirmed with Leslie the latest iteration with month-over-month and week-over-week data for the COVID FAQ page will meet the needs for the briefing.
