### ISSUE TITLE
[Discovery] - Recruit content authors for Learning Center MVP card sort

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#11006]
This is a ticket to capture the work related to recruiting content authors for our card sort exercise.

**Comment by andaleliz** [comment]
@jenniferlee-dsva [Here's a start](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort-recruit-email-sme.md) on the email we'll send out to SMEs on Monday. Links will come once we have cards/categories set up. Pasting here as well in case that's easier for you to review:

----

Hello,

The VA.gov Public Websites team is looking for your participation in a brief research session. The research is for a new web experience designed to help Veterans find answers to questions about their VA benefits, services, and other common customer service questions.

We are looking for subject matter experts or people who create/manage content for Veterans to provide feedback through a card sorting exercise to help us understand how to organize information.

**What will I be doing in this session?** You will be sorting article titles into categories in two different card sorts. If the pre-defined categories don't feel right, you will have the opportunity to create your own categories. There are no wrong answers. We just want to know how you would categorize things.

**How long is a session?** The session is self guided and should take you 10-20 minutes to complete both card sorts. You can do this at any time of day that's convenient for you.

**Is there a deadline?** We would like to gather all responses by September 11, 2020.

**How do I participate?** Click on the links below and follow the provided instructions. 

Card Sort A 

Card Sort B 

Thank you in advance for your participation! Your input is appreciated, and will contribute to improving the Veteran experience on VA.gov.

**Comment by jenniferlee-dsva** [comment]
Closing this because we've completed the card sort exercise.
