### ISSUE TITLE
EYB: Update GA for Profile Page full size accordions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#11001]
As a developer, I need to add google analytics to the comparison tool for the estimate your benefits enhancements so we can have a better understanding about how users are interacting with the tool.

## Assumptions:
1. This work is a result of #9991.
2. This story is limited to the CT profile pages (VETTEC & Non VETTEC)
3. Full size accordions examples are (Estimate Your Benefits, Veteran Programs, Cautionary Information, etc)

## Acceptance Criteria
1. The following event is captured on full size accordion opening:
```
{
  'event': 'nav-accordion-expand',
  'accordion-size': 'full-content-width'
}
```
2. The following event is captured on full size accordion closing:
```
{
  'event': 'nav-accordion-collapse',
  'accordion-size': 'full-content-width'
}
```

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13886

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-19 at 1.55.56 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b65c18c7-ed2c-4a49-b676-c5c0d304a30e)
##
![Screen Shot 2020-08-19 at 1.56.03 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1e4f2e16-abcb-4ec9-b2be-aa898d9326ef)
##
![Screen Shot 2020-08-19 at 1.58.03 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f1aef8f7-fc0a-4bae-b396-bd47ffa1be38)
##
![Screen Shot 2020-08-19 at 1.58.10 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2a1ed2fa-0eca-4d61-9d22-eea63c5edfd2)

**Comment by sonntag-adam** [comment]
This is in staging. Closing story.
