### ISSUE TITLE
Validate non-top forms custom content - form detail landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11014]
## Validate non-top forms custom content - form detail landing page

This ticket is to validate the work being completed in ticket #10561 - for about 400 forms. We will randomly select ~10% to validate.

**Dependency:** Preview functionality - currently in progress here - ticket #10606.

AC:

 - [x] Preview 50 randomly selected form detail pages from the not top forms spreadsheet. (Please document in this ticket the 50 you select.)
 - [x] The 50 selected preview pages are displaying the forms db and custom content fields correctly, ~[per FE content mapping doc.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs/Form-detail-page-content-fields-FE-mapping-062520.docx)~ [per updated visual mockups](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs#visual-mockups)   <--updated 7/17
 - [x] All custom updated form pages are changed to "in review" state.
- [x] Uncheck the autogenerate URL checkbox on all "in review" forms.  < -- Added 7/15 JL
- [x] Please provide a list of the 50 pages that were used to validate.   <--Added 7/17 jl

 (Note: we're still using the autogenerated URL; we're just unchecking the box so that after publishing, the URL is hard set and doesn't change even if the form data changes.)

Adding visual references from the CMS preview ticket: 

**Version user sees when a page has all custom content fields:**

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-heading-hierarchy-071620.pdf

**Version user sees when a page has no custom content fields:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-minimum-content-072820.pdf [edited 7/29 JL]

~https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-minimum-content-071620.pdf~

**50 forms previewed:**
1. 10-0455 (There is no "Form last updated" date showing but there is none in the DB)
2. 10-0388-6
3. 10-1245c
4. 21-4170
5. VA0904 
6. VA0730a
7. 10-1313-2
8. 20-0998
9. 21P-0513-1
10. 21P-4185
11. 10-10072a
12. 26-0592
13. 26-6808
14. 10-0491K
15. 10-1394
16. 21P-0847
17. 21-0819
18. 22-0997
19. 26-0971
20. 26-8599
21. 10-6001a
22. 40-0895-7
23. 10-9054
24. 22-0803
25. 21P-10199
26. 22-8691
27. 26-421
28. 22-5281
29. 26-1817
30. OF-306
31. VA40-1330M
32. 29-586
33. 26-0551
34. 26-8644
35. VA2793
36. 10-2850D
37. 29-353
38. 10-3203
39. VA40-1330
40. VA40-0895-11
41. 4676a
42. 10-7959e
43. VA9
44. 26-8736b
45. 26-8812
46. 1902w
47. 10-2553
48. 10-2478
49. 26-1820
50. 10-2409 (There is no "Form last updated" date showing but there is none in the DB)

**Comment by jenniferlee-dsva** [comment]
@lunascoop - I updated ticket ^ with a link to the updated mockups. This  shows Ryan's latest headings hierarchy. Most of the 400ish forms will display as the minimal version. 

Content data fields are the same as before, no changes there. 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs#visual-mockups

**Comment by jenniferlee-dsva** [comment]
@lunascoop @RLHecht - The FE preview template is now showing those PR updates, and these can now be validated formally with the ACs. 

Note: I added a link to an example with the updated FE visual above.

**Comment by RLHecht** [comment]
I've previewed 50 pages and all look good. I made a note on two of them that the last updated info wasn't in the preview but that info also wasn't showing in the forms DB. Let me know if I can close this ticket. FYSA @jenniferlee-dsva @MickinSahni
