### ISSUE TITLE
[Decision] - Confirm initial set of screens needed for learning center MVP prototype

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#11018]
- [x] Come to consensus on initial screens needed for prototype 
- [x] create additional writing tickets if necessary

[Here's a prototype ](https://vsateams.invisionapp.com/share/YJXZTKC6CN4) with the pages we have from Ryan's Sketch file.  Reviewing these will help us understand the gaps for additional content needed.

**Task 1**
- Learning center homepage

**Task 2**

- View all VA account and profile articles page
  - Should include 10 search results
  - Page should include some results that have similar titles so we can see if the template labels are effective in helping users choose a relevant search result

**Task 3** (these are already captured in #10775 
- Sign in FAQs
- Change your address on file with VA
- How to change your address online

**Task 4**
- Exposure to hazardous materials page from benefit hub
- Agent Orange LC page w/ CTAs leading back to hub, with Vietnam War Veterans (to tee up next task)
- Disability hub:  How to file or eligibility page from benefit hub. Not sure we need both

**Task 5** 
- Vietnam War Veterans search results page

**Comment by andaleliz** [comment]
@jenniferlee-dsva what are your thoughts on this?

**Comment by jenniferlee-dsva** [comment]
This matches what we discussed re the tasks in the protoype user session. Thanks Liz. I think we can close this now, since this ticket is to just confirm the final list of content needed for prototype. 
fysa @MickinSahni
