### ISSUE TITLE
Validate top forms custom content - form detail landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11010]
## Validate top forms custom content - form detail landing page

This ticket is to validate the work being completed in ticket #7491 - for about 40 forms. 

**Dependency:** Preview functionality - currently in progress here - ticket #10606.

AC:
- [x] Preview all of the form detail pages in the top forms copydeck and spreadsheet. 
- [x] All preview pages are displaying the forms db and custom content fields correctly, per [FE content mapping doc.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs/Form-detail-page-content-fields-FE-mapping-062520.docx)
- [x] Validated form pages are changed to "in review" state. 
- [x] Uncheck the autogenerate URL checkbox on all "in review" forms.  < -- Added 7/15 JL

 (Note: we're still using the autogenerated URL; we're just unchecking the box so that after publishing, the URL is hard set and doesn't change even if the form data changes.)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I've reviewed all of the Top 40 forms using Preview. There were issues on two pages that we can't change within Drupal:

- https://prod.cms.va.gov/find-forms/about-form-10-10ez-pdf We need to eliminate "(pdf)" from the H1, Download link and Helpful Links header
- https://prod.cms.va.gov/find-forms/about-form-va40-10007 We need to remove "va" from in front of the form name in the H1, Download link and Helpful Links header

**Comment by swirtSJW** [comment]
Those will be have to be edited in the forms DB and then they will update in drupal the following night.

**Comment by jenniferlee-dsva** [comment]
I will let the form owners know and ask them to change that in the source VA forms DB.

**Comment by jenniferlee-dsva** [comment]
fysa @MickinSahni - I will spot check this after FE template PR has gone through, and then close after I've had a chance to view the previews with [PR updates here](https://github.com/department-of-veterans-affairs/vets-website/pull/13527).

**Comment by jenniferlee-dsva** [comment]
I just spot checked using the updated FE preview with Nick's PR updates. It looks great! Closing.
