### ISSUE TITLE
Complete Discovery Tech Feasibility Documentation

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11027]
Update doc in Github that answers all the technical research done to date including the following areas: 

[Discovery technical feasibility  ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/technical-feasibility.md)

During the research phase of the questionnaires product we need to answer a few key questions from a engineering tech feasibility perspective -

- [ ] How do we get health data from multiple EHR source systems?
- [x] How do we authenticate the Veteran so we can show personalized health data?
- [x] What is the scope involved with creating a form on va.gov?
- [x] What is our Mobile and va.gov platform development strategy
- [ ] How do we show va.gov profile information by pre- a form or leverage a re-usable component?
- [ ] Others as needed

**Comment by mdewey** [comment]
**Acceptance Criteria**

- [ ] review doc with team

**Comment by abuckley3385** [comment]
Not sure why zenhub won't allow .rft attachments so Im adding my google drive link to the [questions I had on the tech doc.  ](https://drive.google.com/file/d/14Ydo48f4YzKJW-pbpYFsdU4qRGGhvEA_/view?usp=sharing)
