### ISSUE TITLE
Project Kickoff: Comparison Tool Search and Filter Enhancements

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11028]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt @ Mandi Lipka
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline
   -  [Search](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/search/search-enhancements_product-outline.md)
   - [Filter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/search/filter-enhancements_product-outline.md)
- Explanation of the problem space
   - Search: The current search in the Comparison Tool poses challenges for users as they search for institutions since it requires that they enter an exact match in order to provide them with results. The current search feature limits the ability to search on school type to just on the job training (OJT) and schools, which means people are not able to search exclusively for associates programs, VET TEC programs, and more. When users search for schools based on state alone then branches of schools that are not in the same state are returned. If users search for content in the Comparison Tool right now and accidentally include a misspelling or abbreviations or nicknames (such as UCLA or Cal State, state abbreviations) then the results they are searching for will not be returned.   
   - Filter: The GI Bill Beneficiaries using the Comparison Tool are lacking additional nuanced data points that would help them find schools and training institutions that are the best fit for their education needs and make better education decisions.

- Other artifacts we have so far
   - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/research/EducationJourney-Phase1-KevinMhoffman-Draft-V003.pdf
   - Attributes to consider displaying/incorporating into search in the Comparison Tool: https://collegescorecard.ed.gov/assets/FullDataDocumentation.pdf

## Meeting attendees from **requesting team**
- Product Manager (required): Darrell Neel (Darrell is on leave through 07/31 so Desiree Turner & Will McCormack are covering for him for the time being)
- DEPO Product Lead (required): Matt Self
- Entire VFS team (recommended): Amy Knox, Cindy Cruz, Jen Jones, Dan Shawkey, Adam Sonntag

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** No

## Scheduling
Preferred time slot: 11:30-12:30 on Wednesday 7/15 (anticipate needing more than the usual 30 minutes because we are potentially combining two efforts - search and filter - into one checkpoint.

**Comment by dneel-bah** [comment]
Meeting completed 07/15
