### ISSUE TITLE
How express care works

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11034]
As a Veteran who has access to Express Care, I want to know exactly how I can use Express Care and if it's right for my needs because this is a new offering from the VA. 

## Acceptance Criteria:
- [ ] Veteran provided brief explanation of how to use Express Care / what it's for
- [ ] Veteran sees the availability window in Step 1
- [ ] Veteran sees Emergency care not Express Care and includes 911 and hotline numbers/direct dial
- [ ] Veteran sees confirmation about moving forward with EC means they do not have any emergency symptoms
- [ ] Veteran can choose to 'cancel' their EC request flow which takes them back to appointments homepage
- [ ] Veteran can choose to 'Continue with Express Care request'

## Mock up: [(prototype here)](https://vsateams.invisionapp.com/share/BVY4QCOJM4U#/screens/425790746)
![Screen Shot 2020-07-22 at 10.34.42 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/344aeb22-28a4-428f-bdd6-fa9416aa6e59)

**Comment by lenaecb** [comment]
@rtwell @peggygannon - we need to review the 1,2,3 points for this copy. 
- For 1 - we need to update it as to not include 'we only accept request in the morning' this is not true for all sites. We could pull in the today's time for EC like we do on the homepage prompt. 
- For 2 - is confusing because we are saying you don't need a PACT/won't get a call back from your PACT, but then we say you will get a call back from your VA provider - which most Veterans associate with their PACT. I would recommend we use - " " - this is also what is used by the EC comms team. 

cc: @melissajschaff

**Comment by peggygannon** [comment]
@lenaecb @rtwell @melissajschaff Please see update content recommendations below. 

I've included: 
-Active and Inactive state for the landing page
-Updated content for subway map. I've also tweaked this content to be more clear and active about what steps the *Veteran* needs to take, what they need to do. 

Please let me know your thoughts/feedback on the below content. thank you!!

-----



ACTIVE STATE:
**Create an Express Care request**
Talk to a VA health care member today about a condition or symptom that’s not urgent and doesn’t need emergency care. This new Express Care option is available from [hours] to [hours] [a.m. or p.m.] [time zone]. 
{button} Create an Express Care request

INACTIVE STATE:
**Express Care isn’t available right now**
Express Care lets you request a same-day call with VA health care member to discuss a condition or symptom that’s not urgent and doesn’t need emergency care.  
Express Care is only available certain hours. If you want to use this option, you can submit a request tomorrow OR check back later… 
**need guidance on if we can tell Veterans when to return to use Express Care** 

If you need to talk to a VA health care member today, please contact your call your VA medical center(https://www.va.gov/find-locations/) before going to a clinic.

-------


**How Express Care works**
[begin subway map}
**Submit an Express Care request online**
You can request Express Care between [hour] and [hour] [a.m./p.m.] [time zone].  You don’t need to have an assigned Patient Aligned Care Team (PACT) to use Express Care. 

**Wait for a call from a VA health care member**
A VA health care member will call you soon after you submit your request. This call won’t be from your primary care provider or someone on your PACT team. 

**Talk to the VA health care member about your health concern**
The VA health care member will assess your condition and recommend next steps. Depending on your needs, they might recommend you have a follow-up phone or video call with your primary care provider or a specialist. They might recommend a prescription.  Not all Express Care calls will result in a follow-up appointment. 

{emergency alert}
No changes

**By choosing to continue with Express Care, you agree that you don’t have any of the symptoms listed above**

{button} Continue

**Comment by lenaecb** [comment]
@lenaecb - copy/paste latest copy in ticket.

**Comment by rtwell** [comment]
@peggygannon my only edit to the copy is changing VA health care member —> VA health care staff. It feels more "health care-y" to me, and I know Kathy preferred that language as well. 

![image](https://user-images.githubusercontent.com/12564977/88297841-6bac3a80-ccce-11ea-9649-4c0571a20341.png)

**Comment by peggygannon** [comment]
Hi, @rtwell Ok, sounds good. thank you for that information. 

Some additional word tweaks to accommodate this wording change: 

subway bullet 2: please update to: **Wait for a call from VA health care staff** (removing "a")

change the first sentence to: Someone from VA health care staff will call you soon after you submit your request. 

Subway bullet 3: **Talk to the VA health care staff member about your health concern**

**Comment by peggygannon** [comment]
**How Express Care works**
[begin subway map}
**Submit an Express Care request online**
You can request Express Care between [hour] and [hour][a.m./p.m.] [time zone]. You don’t need to have an assigned Patient Aligned Care Team (PACT) to use Express Care.

**Wait for a call from VA health care staff**
Someone from VA health care staff will call you soon after you submit your request. This call won’t be from your primary care provider or someone on your PACT team.

**Talk to the VA health care staff member about your health concern**
The VA health care staff will assess your condition and recommend next steps. Depending on your needs, they might recommend you have a follow-up phone or video call with your primary care provider or a specialist. They might recommend a prescription. Not all Express Care calls will result in a follow-up appointment.

{emergency alert}
{begin emergency alert}
**Express Care can’t provide emergency help**
Call [911] or go to the nearest emergency room now if you have any of these symptoms:
• Major bleeding or trauma
• Chest pain with shortness of breath
• Sudden inability to speak or walk
• Vaginal bleeding or abdominal pain during pregnancy
• Sudden, severe headache
• Sudden vision loss
Note: For emergencies, you don’t need a VA referral or approval to go a non-VA ER in your community.

If you need to talk to someone right now:
Call our Veterans Crisis Line at 800-273-8255 and select 1.
{end emergency alert}

**By choosing to continue with Express Care, you agree that you don’t have any of the symptoms listed above.**
{button} Cancel
{button} Continue


[Uploading... How Express Care works doc.docx ]
