### ISSUE TITLE
Analytics for Express Care in VAOSR

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11033]
As a product manager, I want to understand how this feature is being used, and when it is, and isn't, resulting in successful request submission.

**We want to track the following areas from the new Express Care request flow:**
- Event for button "Create an Express Care request" - _the start of Express Care request flow_
- Event on 'Cancel' button on 'How Express Care works' page - tracks users who drop out of flow on this page
- Event on 'Continue with Express Care request' - tracks users who commit to moving forward with EC request
- On the symptoms page track the following:
    -- Track clicks on links to 'Facility Locator' and 'Schedule an appointment' on the EC 'symptoms page'
    -- Symptom selected _(ex. Cough without shortness of breath, Gastrointestinal symptoms, such as diarrhea, constipation, nausea, vomiting, upset stomach, or acid reflux (heartburn), etc)_
- Event on 'Submit Express Care request' button on 'request details' page - track final completion of Express Care flow

**Express care tab/Express Care cards:**
- Event on 'Cancel' button on Express Care cards - tracks cancelations of Express Care
   - As additional data: cancel succeeded
   - As additional data: cancel failed
- Track average number of Express Care cards showing per user in Express Care tab

**Comment by jbalboni** [comment]
Events:

vaos-express-care-request-button-clicked
vaos-express-care-request-cancel-flow
vaos-express-care-request-continue-flow
vaos-express-care-submission
vaos-express-care-submission-successful
vaos-express-care-submission-failure

Additional data on submission: `health-expressCareReason` (contains the symptom)

Cancel events are the same:

vaos-cancel-appointment-submission
vaos-cancel-appointment-submission-successful
vaos-cancel-appointment-submission-failure

Additional data:

isExpressCare (true or false)
appointmentType (pending or request)
facilityType (va or cc)

I think I need some guidance on tracking the number of requests for a user. I assume that would be a custom page level variable, but I can't find any examples of that in vets-website. I'm not sure who on the analytics team to tag to ask about that.

**Comment by jbalboni** [comment]
@bsmartin-ep Can you help with the above? I have a question above about how I should track additional data about a particular page. I'd also like to verify that the additional data listed for our cancel appointment events is actually set up correctly.

**Comment by jbalboni** [comment]
As far as I know, the development for this ticket is complete and in production.

**Comment by bmcgrady-ep** [comment]
### QA Testing of 11033
Description of Test Scenario | DL Screenshot | Test Status
-- | -- | --
Event for button "Create an Express Care request" - the start of Express Care request flow | (https://user-images.githubusercontent.com/66263904/91233901-08eff980-e6e7-11ea-9391-dc9801d1a8a1.png) | ✔️ PASS
Event on 'Cancel' button on 'How Express Care works' page - tracks users who drop out of flow on this page | ![image](https://user-images.githubusercontent.com/66263904/91234134-7ef46080-e6e7-11ea-96b9-0f0c9d8c7749.png) | ✔️ PASS
Event on 'Cancel' button on Express Care cards - tracks cancelations of Express Care | ![image](https://user-images.githubusercontent.com/66263904/91236967-37250780-e6ee-11ea-8bb5-06359d02cd97.png)![image](https://user-images.githubusercontent.com/66263904/91234718-b7486e80-e6e8-11ea-83ea-6a935dc466ac.png) | ✔️ PASS
Track average number of Express Care cards showing per user in Express Care tab | ![image](https://user-images.githubusercontent.com/66263904/91235209-ec08f580-e6e9-11ea-8a76-1aaf94c13b8b.png)![image](https://user-images.githubusercontent.com/66263904/91237121-a6026080-e6ee-11ea-9942-6da60849da6a.png) | ✔️ PASS
Track final completion of Express Care flow | ![image](https://user-images.githubusercontent.com/66263904/91236653-62f3bd80-e6ed-11ea-875e-63f110dc61dd.png)![image](https://user-images.githubusercontent.com/66263904/91236668-6b4bf880-e6ed-11ea-9b96-85c74d9d4799.png) | ✔️ PASS

**Comment by bsmartin-ep** [comment]
Ah @bmcgrady-ep - the address alert stuff is on a slightly different flow.  Click the blue _Schedule an appointment_ button on the main VAOS page.

Not seeing those events firing on staging yet.

![image](https://user-images.githubusercontent.com/62304138/91248538-e24fb400-e722-11ea-8406-7615aa26e102.png)

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep - I updated the QA Document with screenshots of the GTM tags. I went through the "schedule an appointment" and still don't get an "updated address" prompt, so I couldn't QA the Data Layer for those events.

**Comment by bsmartin-ep** [comment]
@lenaecb / @jbalboni / @narin -

Our GTM workspace has been published.  Event label data has been recording since day 1, but this will include the extra custom dimensions for _# of cards_ and _express care health reason_.  And some slightly more detailed Event Actions.

Let me know if you need a hand coaxing this data out of GA.

**Comment by lenaecb** [comment]
@bsmartin-ep - I am going to close this ticket, but I will need help coaxing it out of GA :)
