### ISSUE TITLE
Stakeholder Interviews

### ISSUE THREAD

**Issue by LEHigley** [department-of-veterans-affairs/va.gov-team#11037]
- [ ] VetLink Kiosk: Shawn Adams
- [ ] Lighthouse APIs: Dave Mazik 
- [ ] My HealtheVet: Kathy Frisbee, Dr. Evans
- [ ] Kellie Condon 
- [ ] VEO: Denise Kitts 
- [x] Internal Medicine and Informatics physician: Dr. Byrne
- [x] eScreening: James Pittman 

Stakeholders to identify: 
- [ ] Clinical Informatics Lead for Nursing Intake forms: This stakeholder can assist in updated patient intake forms documentation being done with both Vista and Cerner to ensure we are leveraging the modernization of the EHR project for consolidated and consistent documentation across facilities and specialties.
- [ ] Connected Care- clinical tool VCM 
- [ ] Clinical/Admin/Intake staff who can speak to current state processes & documents

**Comment by mlighdc** [comment]
@abuckley3385 can you provide some context? I am thinking this is the list of clinicians and/or people you would like me to reach out to? Thanks.

**Comment by abuckley3385** [comment]
@mlighdc this is just the ticket we have had on our board for months and in the blocked column.  You are already working on it and I just changed the owner from Lacey to yourself.
