### ISSUE TITLE
Write supporting tests for forms library review page refactor of SubmitController

### ISSUE THREAD

**Issue by Clark-W-Griswold** [department-of-veterans-affairs/va.gov-team#11040]
### **Overview**

From the work originating in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10114), write supporting tests for the new version of the SubmitController.

**Comment by meganhkelley** [comment]
@Clark-W-Griswold what is the status of this work? If it's unstarted let's move to backlog; if it's complete let's close as applicable. Thanks!

**Comment by meganhkelley** [comment]
@Clark-W-Griswold nudging the above Q and moving to backlog for now
