### ISSUE TITLE
[Copy] Copy is confusing in 'Learn more about military base addresses' FAQ (P&C section)

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#11043]
Under the mailing address section in the FAQ dropdown ' Learn more about military base addresses', the copy is confusing - we should update it to have a better explanation as to _why_ we can only put the US as the country.

![Screen Shot 2020-07-07 at 12.02.11 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/31ec542a-793f-49df-963c-74f6397eac1b)

**Comment by peggygannon** [comment]
hi, @tressaellen taking a look at this. 

Do we have an answer or explanation yet on why we can only put US as the country? Is this a dev question?

**Comment by tressaellen** [comment]
@erikphansen @sanlouise or @Samara-Strauss do you have any knowledge about why we can only put US as the country in a military base address?

**Comment by Samara-Strauss** [comment]
Yes — because military bases are considered to be in the United States even if they are overseas.

**Comment by erikphansen** [comment]
Addresses are weird, yo. It's crazy to me that some place in the middle of Europe will have an American zip code but that's the way it works!

**Comment by peggygannon** [comment]
Hi, @tressaellen Let me know your thoughts on this... Please let me know if you think this is clearer? 
this question predates me, so I am also recommending changing the question to eliminate repetitive words: 

{checkbox} I live on a U.S. military base outside of the country. 


The United States is chosen as your country if you live on an overseas military base. U.S. military bases are considered a domestic address and a part of the United States.

**Comment by tressaellen** [comment]
@peggygannon I definitely think this is much clearer. So are you suggesting removing the additional info dropdown all together?

**Comment by Samara-Strauss** [comment]
Agreed that the copy is better. This is great!

>  So are you suggesting removing the additional info dropdown all together?

We originally had this in the FAQ format to save space so the form wasn't pushed down super far, and also because that use case applies to a small minority of users who are updating addresses on VA.gov. If we decide to keep it, I think that rationale is still fair.

However, one other idea — how hard would it be to show the explanation about military bases being in the US conditionally if the box is checked? Ideally, we'd show it under the country dropdown so that information was in context. Good idea/Bad idea? What do you think?

**Comment by tressaellen** [comment]
I think that is a good idea, depending on how difficult the implementation would be. 

<img width="706" alt="Screen Shot 2020-07-21 at 8 53 06 AM" src="https://user-images.githubusercontent.com/58752772/88070632-5cd35580-cb1f-11ea-9f06-6c6b02f56152.png">


If we decide to go that route, I think we need to shorten the messaging even more if possible. I actually think we could just use the second sentence of Peggy's suggestion:

U.S. military bases are considered a domestic address and a part of the United States.

If we want to include the full messaging, I think the FAQ is the right route - otherwise it does push the form down too much. Is it possible for that to appear conditionally as well?

<img width="715" alt="Screen Shot 2020-07-21 at 8 53 12 AM" src="https://user-images.githubusercontent.com/58752772/88070876-a754d200-cb1f-11ea-87f4-81268aeb69b2.png">

**Comment by Samara-Strauss** [comment]
Both of these options look good to me. Final call is up to you as the designer, @tressaellen! What is your top recommendation?

**Comment by tressaellen** [comment]
I'd recommend option #2 - a shortened conditional message that only appears if the box is checked. @peggygannon do you have any other recommendations for messaging with this change? I think it works with just that one sentence - but let me know if you have any other feedback.

U.S. military bases are considered a domestic address and a part of the United States.

**Comment by peggygannon** [comment]
Hi, everyone. I like option 2 too, especially taking into account mobile users. 

And I think this shortened sentence works: 
U.S. military bases are considered a domestic address and a part of the United States.

@tressaellen this military address pattern appears across other forms.  So I would like to update the other designers on this new approach and content. Let's sync via slack on how best we can do that!

**Comment by tressaellen** [comment]
@peggygannon sounds good! And for visibility - @sanlouise is taking a look at how to implement this and will update us.

**Comment by peggygannon** [comment]
Hi, @tressaellen checking in about this. Is there an updated screenshot?

 I want to be sure all the other designers know about the changes we're suggesting to this military address pattern in forms.

**Comment by tressaellen** [comment]
@peggygannon here is an updated screenshot!

<img width="743" alt="Screen Shot 2020-07-30 at 2 04 36 PM" src="https://user-images.githubusercontent.com/58752772/88969156-e17b4d80-d25c-11ea-8c13-b415252eebb4.png">

**Comment by jenstrickland** [comment]
This new design — removing the additional info toggle — is great! What might we do to ensure this pattern is incorporated sitewide? Other projects are using the toggle 😢  and this would be great to have implemented everywhere.

Thank you so much for doing this!

**Comment by Samara-Strauss** [comment]
We have tickets created to update the benefits forms with this if they choose to do so. Those tickets have been hanging around since December/January and haven't been implemented, so I posted a link to the latest designs in each of those tickets.

**Comment by peggygannon** [comment]
thank you @Samara-Strauss and @tressaellen !!

**Comment by Samara-Strauss** [comment]
This ticket looks done to me — yes? If so, @mshea0606 or @tressaellen can you create a ticket for FE implementation if one does not already exist?

**Comment by mshea0606** [comment]
@Samara-Strauss @sanlouise @tressaellen [FE] Update "learn more about military base addresses' section #12217 has been created for this.

**Comment by tressaellen** [comment]
@peggygannon I know this is closed - but just for documentations sake I wanted to drop these screenshots in here. There was some development constraints, so we ended up having to put the text above the 'Country' box. Screenshots below. 

![image (1)](https://user-images.githubusercontent.com/58752772/90449496-0f9dc180-e094-11ea-8f7d-2be61ee50aad.png)
![image](https://user-images.githubusercontent.com/58752772/90449500-10ceee80-e094-11ea-8ebc-27c96736b6b9.png)
