### ISSUE TITLE
[Design] Profile: Add info on the DD214 in the Military information section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#11053]
## Background

["DD214" is the second most searched term from the profile](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-pages/a50123418w177519031p176188361/_u.date00=20200101&_u.date01=20200707&_.useg=builtin1&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.searchStartPage:www.va.gov~2Fprofile~2F/). It's reasonable to assume that users expect to see information about their DD214 in the profile under "Military information." While we can't add the DD214 itself because we don't have access to it, we can at least link to information that helps guide users on how to get it.

## Tasks

- [x] Determine approach.
- [x] Design mockups.

## Acceptance criteria

- [x] Mockups completed with DD214 info in the Military information section.

**Comment by cgednalske** [comment]
Hi @Samara-Strauss and @SKasimow. Below is my suggestion for a link going to the Records page for info on requesting a DD214 / other military records. 

This follows the pattern used in [Account Security](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/3OYm1ew) and [Connected Apps](https://www.sketch.com/s/479aa6d6-a7a7-4d82-acf1-c06a6699655e/a/ELvK4q2) for highlighted info/link. I had done a little discovery for this a while back to see if other approaches might work better, but in this case the blue featured content component is definitely the best option in the design system 👍. I'd imagine it also has more research behind it as we're already using it throughout Profile. A link on its own might present challenges for users to pick out when located under the FAQ. 

I've used content found on the [records page](https://www.va.gov/records/get-military-service-records/), but I plan to take this to Danielle's office hours on Thursday to confirm the wording and see if the heading should be in question form instead (though I believe the content team is moving away from questions as headings). 

Let me know your thoughts! If you're good with this approach I will add it to the official mockups.

<img width="772" alt="Screen Shot 2022-08-30 at 9 25 28 AM" src="https://user-images.githubusercontent.com/79372956/187489946-7be95135-f9ce-4b83-afad-4f0221f4bb1e.png">

**Comment by SKasimow** [comment]
@cgednalske - I think it looks good! No changes from me.

**Comment by Samara-Strauss** [comment]
This looks good to me! Where does the link go to?

**Comment by cgednalske** [comment]
Great! Thank you both 👍 The link goes to the [records page](https://www.va.gov/records/get-military-service-records/), which appears to be the only place to get this info and where everything else leads that is related to DD214/other records.

**Comment by cgednalske** [comment]
Here are the updated mockups after reviewing the content with Danielle ([Desktop](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/g0YO03a) & [Mobile](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/DPDA8Wk)) - just some changes to the wording in the link. 

She also noticed some sighted language that we're using for the FAQ and expanded info that will need to be updated. She'll get back to me on that once she's able to review it. @SKasimow not sure how long that will take, so I might need a ticket to update that once she does.

**Comment by SKasimow** [comment]
@cgednalske - sounds good, thanks.

On a related note, we'll need to replace the DD mocks in the sketch files, use cases, and Contact Center guides (anything else?). Should I add those as tasks to this ticket? Or, open a new ticket to make the changes once we have this in staging?

Also, do we keep the links to the sketch files the same so that any time a page is updated the use cases links to mocks don't need to be changed? I know we touched on that before but wasn't sure if it was just for a specific project or if we are set up to do that across the board for all our pages?

**Comment by cgednalske** [comment]
@SKasimow this ticket is for Military info not DD (confusing, I know, since we're referring to DD214), so I'm not sure what DD work you mean?

For Sketch file links in general, yes that's correct 👍  We've moved away from including screenshots and copy in our documentation and are instead always linking to the same Sketch files so we don't need to constantly remember to update those items in documentation.

**Comment by SKasimow** [comment]
@cgednalske d'oh! sorry I think the "dd214" got me - lol!

Sounds like the sketch files and use cases are taken care of; should I just add a task to replace the CC mock?

**Comment by Samara-Strauss** [comment]
@cgednalske your updated mocks look good to me! And noted re: needing to update the FAQ language. That can definitely be a separate ticket.

**Comment by cgednalske** [comment]
Closing this ticket. And @SKasimow that sounds great for a ticket to update the CC image(s) once this is in staging. If not, I'm afraid it would be too easy to forget 🤓
