### ISSUE TITLE
ForeSee Survey Request for Authenticated experience — Profile 2.0

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#11054]
# Request the ForeSee Survey

## What this form is for
Use this template to request adding the ForeSee Survey to your product.

ForeSee FAQ [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/foresee-readme.md)

## Description

We already have a ForeSee survey in the profile (thank you!). However, as we work towards the profile 2.0 launch, we are going to be changing URLs in the profile. I want to make sure we are prepared for that and have the ForeSee survey available on each page of the profile.

Right now, the profile has one URL — www.va.gov/profile.

For Profile 2.0, we will be dividing different sections of the profile into different pages. The new URLs will be:

|Page| URL |
|-----|-----|
|Personal and contact information section (landing page)| /profile |
|Military information | /profile/military-information  |
|Direct deposit information | /profile/direct-deposit-information |
|Account security | /profile/account-security |
|Connected apps | /profile/connected-apps |

### Launch Date
*Please provide the launch or rollout date.*

We are targeting early September but don't have a definite date yet.

### Staging URLs
*Please provide staging URLs*

Profile 2.0 will be live in staging by 7/15/20. You can get to the profile by going to staging.va.gov/profile.

### Production URLs
*Please provide Production URLs*

See above

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the ForeSee Comment Card

**Comment by Samara-Strauss** [comment]
CC/ @mshea0606 for awareness

**Comment by joanneesteban** [comment]
Apologies for the delay - the feedback button is on Staging. Once this is verified, we can add this to Prod.

**Comment by Samara-Strauss** [comment]
Things are working on the military information, direct deposit, and account settings pages. It looks like I got you incorrect URLs for personal and contact information and connected apps.

- The URL for the personal and contact information page is /profile/personal-information.
- The URL for connected apps is /profile/connected-applications.

Once those are fixed, we should be good to go. Sorry for not having the right information in the first place!

**Comment by joanneesteban** [comment]
Hi @Samara-Strauss ! Thanks for the updated info - this has been updated in Staging. If this looks fine to you, I can push to Prod!

Thanks!

**Comment by Samara-Strauss** [comment]
Looks great! 

The new profile isn't live yet, so no need to push to prod at this moment. Should we just circle back with you when the profile is live on VA.gov?

**Comment by joanneesteban** [comment]
@Samara-Strauss Great! Yes, please - once this is live, I can push to prod. Thanks!

**Comment by joanneesteban** [comment]
The survey's been added to the URLs above in production. Please note that the first iteration of this ForeSee included va.gov/profile and has collected some feedback since Q1 of this year.

**Comment by Samara-Strauss** [comment]
I'm gonna close this out. Everything looks great. Thank you so much!
