### ISSUE TITLE
Discovery - Returning child facility with Express Care when user logs in

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11067]
Need to do some testing/tech discovery on making call for child facility data when user first loads VAOS app homepage. 

Desired behavior:
- User will see Express Care option on homepage is registered at site

Considerations:
- performance based on number of calls
- as part of this ticket lets collect some thoughts/idea on how we'd handle the scenario where Veteran may have more than one registration site and/or has more than one site with EC enabled

**Comment by narin** [comment]
In an email exchange with Brad Crosby and Steve Monson, we found that there might be an endpoint in the mobile facility service that can return express care times in a single call.  Will touch base with Monson to confirm if the response contains the times we need.  If it does, we'll need to create a new backend ticket to create the endpoint to interact with this ticket in `vets-api`.  

Potential endpoint we'd use is documented in a swagger doc here: https://coderepo.mobilehealth.va.gov/projects/VDMS/repos/mobile-facility-service/browse/src/main/resources/swagger.json#689

**Comment by narin** [comment]
As it turns out, that endpoint requires facility IDs to be passed to it, which we wouldn't have without making the multiple calls anyway.  We'll use our existing method of making a call with each site ID to get a list of facilities and their express care info.
