### ISSUE TITLE
Duplicate suicide prevention accordions in Altoona demo

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11074]
## What happened?
Several locations within the Altoona system (demo) have duplicate suicide prevention accordions. Only one has content. 
One example: Huntingdon County. 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/9b3854f9-8588-464f-b488-52e65e5c4859)

![image (40).png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/720eeae6-83f1-4819-8c01-4c127d989ba6)

## Desired behavior

- Accordions should be present only if they hold content. 
- Only one accordion should be present per facility health service. 

## Acceptance Criteria
- [ ] Duplicates are removed from Altoona Facility Health Services

**Comment by SgardnerPMP** [comment]
Duplicates found for Altoona and deleted.  Opening research to find out why and how this happened.  Consideration for CMS to not allow duplicate health services per facility.  One and done.
