### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#11071]
# Request Google Analytics access

We'd like the whole CMS team to be able to access the "VA.gov CMS Backend" property

## User Email Address

These are all google-enabled accounts:

nick.bloom@agile6.com (may already have an account)
jordana.mello@agile6.com
oksana.cyrwus@agile6.com
clarence.maeng@agile6.com
howard.brande@agile6.com
daniel.milller@agile6.com
jeff.brauer@agile6.com
neil.hastings@agile6.com
kaise.lefrai@civicactions.com
steve.wirt@civicactions.com
rachel.kauff@civicactions.com

## Access Requirements

* "VA.gov CMS Backend" Property

## Date Required
No hard deadline, but in the next week would be great. 

## Product Team / External Team / VA Office

`#CMS-team`

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Thank you @kevwalsh! We'll follow-up when we've got everyone here added.

**Comment by jonwehausen** [comment]
@kevwalsh team members have been added! 

For reference, here's the list of accounts provisioned access: 

**Agile6 accounts:**
brian.derfer@agile6.com
alex.seelig@agile6.com
nick.bloom@agile6.com
jquag@agile6.com
jeff.brauer@agile6.com
elijah.lynn@agile6.com

**Civicactions accounts:**
ethan.teague@civicactions.com
kevin.walsh@civicactions.com

**Comment by oksana-c** [comment]
@jonwehausen , please review accounts with provisioned access. The following users still do not have access to "VA.gov CMS Backend" Property. If all looks good at your end, we may need to connect via call to review. Thank you.

* jordana.mello@agile6.com
* oksana.cyrwus@agile6.com
* clarence.maeng@agile6.com
* howard.brande@agile6.com
* daniel.milller@agile6.com
* neil.hastings@agile6.com
* kaise.lefrai@civicactions.com
* steve.wirt@civicactions.com
* rachel.kauff@civicactions.com

**Comment by jonwehausen** [comment]
Hi @oksana-c , 

Thanks for your request here! **All but these two individuals should have access to all GA properties and views at this time:** 

- Daniel Miller: daniel.milller@agile6.com
- Kaise Lefrai: kaise.lefrai@civicactions.com

We'll finish getting these folks setup when their Google Accounts have been configured. [Here](https://accounts.google.com/signup/v2/webcreateaccount?flowName=GlifWebSignIn&flowEntry=SignUp)is where that process can be done.

**Comment by oksana-c** [comment]
@jonwehausen , it appears that both these users had typos in their email.
Correct emails:

* daniel.miller@agile6.com
* kaise.lafrai@civicactions.com

Apologies for any inconvenience this may have caused.

**Comment by jonwehausen** [comment]
@oksana-c No problem! These two should have received an email indicating their access as well. 

If we can verify all necessary folks have visibility to CMS Backend we can close at your discretion. Thank you!

**Comment by oksana-c** [comment]
Confirmed access for all. Thank you @jonwehausen!
