### ISSUE TITLE
[Discovery] - Synthesize data and provide recommendations from Learning Center MVP card sort

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#11072]
Produce synthesis report for Learning Center MVP card sort

Tasks

- [x]  Synthesis draft
- [x]  Report shared with team and stakeholders, gather recommendations
- [x]  Synthesis feedback incorporated
- [x]  Study added to research history markdown page

**Comment by andaleliz** [comment]
Draft started, pinged @jenniferlee-dsva on Slack and moving convo here for visibility:

I've got a draft of the card sort synthesis for the [Veteran audience card sort](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort/card-sort-research-summary.md#audience-labels), and I'd like to get your eyes on it before I move forward with the rest. I don't want to continue on this path if there is anything about this that isn't helpful.

 I haven't fine tuned all the wording/grammar yet, so no need to provide feedback on that. Also, no need for you to spend time reading anything above the heading that link takes you to (Audience labels) unless you'd really like to review that now.

Specific questions:
- How do the findings and data presented align with what you hoped for?
- I'd like to break up the report into 2 sections: audience and topic. Within each section, I will detail the findings from each participant group, with a section at the end that pulls together findings from both. Does that format work for you?

Any other feedback is welcome too. Thanks!

**Comment by jenniferlee-dsva** [comment]
Super interesting, @andaleliz . No feedback other than I look forward to learning the rest of your synthesis.

**Comment by jenniferlee-dsva** [comment]
RE your question:
>I'd like to break up the report into 2 sections: audience and topic. Within each section, I will detail the findings from each participant group, with a section at the end that pulls together findings from both. Does that format work for you?

Yes.

**Comment by andaleliz** [comment]
@jenniferlee-dsva The [card sort final draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort/card-sort-research-summary.md) is complete.  

I updated the format from my initial proposal so that [the combined findings for all sorts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort/card-sort-research-summary.md#key-findings-across-both-participant-groups) are at the top of the doc, so someone can understand what we learned in the study without having to read the whole doc.   It definitely gets into the details by participant group and by audience/topic.

I welcome your feedback in whatever way it is easiest for you to provide.  Thanks in advance for your time.

**Comment by jenniferlee-dsva** [comment]
@andaleliz - pls see comments/questions here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort/card-sort-research-summary.md

**Comment by andaleliz** [comment]
@jenniferlee-dsva thanks for this feedback! It's super helpful to see your edits, and know which details you're interested in. 

I've updated the summary with new info and specifics.  Answering some specific questions here so you don't have dig, and to offer some more context around the updates.  There is one comment I haven't addressed yet, which I'm working on and will update tomorrow.

---

>Still, we should consider making `Records` more specific to records and documents,  { @LIZ <-- is that right? it wasn't clear what you mean by "speciic" - specific to what? }

There were a lot of surprising (at least to me) things Veterans put in this category. It's like they thought of anything that could be "on the record" or recorded somewhere would there.  I understand that category/topic to be more about official documents and personal records about a Veteran, so suggesting that perhaps we add some more specificity to the label to eliminate some guesswork on the Veteran's part.

---
RE: audience labels
>Many of these instances seemed to be related to the a word in the article title being repeated in the audience label {@LIZ - is this true or just a sense?

It was a sense (which is why I chose the word `seemed`)- the data does support this for the articles we had with the word "family" in it.  Many of the one-off instances for other articles seem to be related to people considering their own personal situation, e.g. putting 'How do I verify my school enrollment?' into 'Women Veterans'. Updated the finding for this. 

---

>Consider adding a label with the word "contact." <-- this seems like an extremely subjective recommendation, given that only 2 of 39 users created this category. Also, did they BOTH create the same category "points of contact"? If "most people will look for contact information under 'other topics and articles,' shouldn't we consider making sure that all contact info type of articles definitely get added to that category (in addition to where ever else we put it).

It is subjective, but because 2 people did create the same exact label with the same exact cards, I thought it was worth considering (not saying it **must** be done, just something to think about).   I added more details to the finding to give more context about `most` that I think will also help see my rationale. I do think we should make sure all contact info type of articles have that category, but try to use my recommendations to provide guidance to content authors sparingly since that doesn't seem to be something we can count on.    All that being said, if this isn't compelling enough for a 'consider' recommendation, I'm totally fine leaving it out.

--- 

>Any consideration here on the potential for SMEs to mix beneficiary and non-beneficary audiences if allowed? Is this a risk per our hypothesis or no longer valid based on this finding?

Yes, I think there is potential to for them to get mixed, or confused - but it would probably depend on the article's context. For example, the "fiduciary for my family member" going under `family members and caregivers` doesn't seem wrong to me.  4 people put `How do I verify my school enrollment` under the career counselor audience. We had mapped that to `all veterans` probably based on the context of the article - I think SMEs were just not sure who the "my" was in that article.  [Added more details to that finding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort/card-sort-research-summary.md#sme-participants-generally-understood-how-to-apply-the-non-beneficiary-audience-labels).

---

>did MORE ppl add the Where can I view my VA payments online? article to the 'account/profile' bucket than 'records'? }

Yes, 22 Veterans put it in account/profile, vs 8 put it into records.  5 put it into disability, and there were 4 one-off categorizations.

---

> <-- @LIZ: Do you mean - even if the article is about say, your pension claims stuff, the article should also be put into the Disability category? 

No, I was referring to articles like the one about challenging a claims agent fee. I don't _think_ that article would live in the disability hub, but I think a lot of ppl w/ disability benefits would be interested in something like that. And reading the article, I think it applies to more than just disability benefits. Added that as an example to the finding.

---

>One SME created a category called `My VA Claims` for all claim articles. <-- this is SMEs correct? It's under the SME participant section, so just confirming we're not mixing Veteran data into this section.

Yes, that's correct

--- 

>SME participants created topic categories in the audience card sort. 2 of 3 of the self-created categories align with what we saw in the topic card sort: {Not grokking what this sentence means - lost the meaning at "align with what we saw in the topic card sort." }

We didn't tell people one card sort was for audiences, and one was for topics.  In the audience card sort, people created categories that were actually topics (from our learning center perspective).  There was alignment between the new categories people created in both sorts. They weren't identical (e.g. in the audience card sort someone created `claim related resources` and in the topic sort someone cre

**Comment by andaleliz** [comment]
@jenniferlee-dsva you had asked for numbers on the first finding in the SME topic card sort. [Check out this update](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort/card-sort-research-summary.md#sme-participants-mapped-articles-to-topic-labels-the-way-we-expected-the-majority-of-the-time) and see if that's more helpful than what I had previously. I can also split out the SME/Veteran data from the topic table and bring that SME data down into that section.

**Comment by jenniferlee-dsva** [comment]
@andaleliz  - thx for making those clarifications in your updates. They look great. There's one part where I wonder if we can clarify our hypothesis. In this part: 

>Takeaways
>SMEs are thinking about claims and payments in a different, but not necessarily incorrect, ways.
>This validates that our plan to apply multiple topic categories to articles will help surface content for Veterans with a variety of mental >models.
 [RE last bullet point: this also affirms our hypothesis that additional labels, in the form of tags could be helpful to users. For example: an article about education tuition overpayment could be in the Education **category**, but ALSO be tagged with a content tag like 'payments and debts.'  That is, that it could be helpful to users to have more flexible or thematic ways of finding content, than just our official benefit categories. Not sure how to summarize that, but wanted to point that out because throughout, the report references categories - or conflates categories with tags - and I have from the start been proposing that tags and categories be different and complimentary rather than echoes of each other.]

**Comment by andaleliz** [comment]
@jenniferlee-dsva, when I reference `multiple topic categories`, I'm talking about what is [described here in the template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#learning-center-categories), which I _think_ is what you also mean by
>an article about education tuition overpayment could be in the Education category, but ALSO be tagged with a content tag like 'payments and debts.'

When you say 
>this also affirms our hypothesis that additional labels, in the form of tags could be helpful to users.
I think the `tags` refers to what is [described here,](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#frontend-content-tags) but I only see audience tags listed, so I didn't think **topics** applied to tags anymore (in the sense of clickable elements on the page that take users to a group of similarly tagged articles)

Happy to discuss on a call if that's easier. 

Also, wrt to
>or conflates categories with tags
I wasn't aware of the change from tags > categories until 1/2 way through this doc, so it's possible I missed some references that should now say categories instead of tags...

**Comment by jenniferlee-dsva** [comment]
>I think the tags refers to what is described here, but I only see audience tags listed, so I didn't think topics applied to tags anymore (in the sense of clickable elements on the page that take users to a group of similarly tagged articles)

We flattened audience and topics, so they are both just FE tags now. We divorced LC menu categories from tags, so the category labels will only be used to organize articles in the lc ia, rather than appearing as tags. 

No need to update - it's too hard to explain. Thx @andaleliz  - we can move forward as finalized now.
