### ISSUE TITLE
[Ongoing Service] Global Customer Support (IA design)

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#11076]
### High Level User Story/ies
As a Veteran or other VA.gov user, I need to be able to find tools that help me complete key tasks on VA.gov, so that I can apply for/manage/track my benefits etc.

As a VFS team, I need to know the ideal IA of the content/tool I am building within the VA.gov ecosystem, so that I can best meet the needs of Veterans and other users.

### Hypothesis or Bet
If we provide customized IA design support for teams building on VA.gov, then end users of VA.gov will be able to find and use relevant tools with ease.

### OKR
O1: Teams have efficient experiences using the platform to build impactful products for Veterans, where their expectations are exceeded.

### Success metrics 
- Increase in positive feedback from teams on the value of the platform quarter over quarter
- IA health of VA.gov

### Additional Details/Notes (optional)
~IA design support for teams building on VA.gov is tracked in three separate buckets, which are linked as epics to this super epic. The definition for each is:~

~**Basic IA design support for VFS teams** #11077~
~**Heavier lift IA design support for VFS teams** #11078~
~**IA design support for DEPO** #11079~

The approach for tracking within this super epic has changed — we will use story points and team labels for the time being, in order to help us identify patterns (before we consider creating separate epics for separate types of projects).

**Sizing:**
1 = Trivial
3 = Small
5 = Medium
8 = Large
13 = XL

### Communication
- Team that owns this super epic: Content & IA

**Comment by mnorthuis** [comment]
@shiragoodman This is my old epic for tracking VFS team IA support.  Do you want me to move/reassign these issues to the global service issue and close this one?

**Comment by shiragoodman** [comment]
thanks @mnorthuis ! yes, that would be great. Only the open issues should be reassigned. The closed ones are fine as is.

**Comment by mnorthuis** [comment]
Moved all remaining open issues to Global Support epic #3675 under Product Support team. Closing this epic.
