### ISSUE TITLE
"Home" breadcrumb present on Philadelphia VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11088]
## What happened?
The Home breadcrumb was hidden purposefully for the VAMC pages. It appears to have been applied to most systems, but not all. The "Home" breadcrumb still appears on recently cloned http://philadelphiahealthcare.web.demo.ci.cms.va.gov/philadelphia-health-care/ DevShop environments 
And also that http://philadelphiahealthcare.web.demo.ci.cms.va.gov/philadelphia-health-care/about-us/ Home isn't there by VA Philadelphia health care is not hyperlinked.

Note: Investigation with Ethan found a root cause: "dehandlized" code for hard coding the name push. This was likely implemented at launch to address nickname/short name logic that was originally planned. 

## Desired behavior
All VAMC healthcare pages should have consistent Veteran experience. The "Home" breadcrumb should be hidden for all. 

## Acceptance Criteria
- [ ] VAMC healthcare pages do not have a "Home" breadcrumb. 
- [ ] Non-VAMC pages must retain the "Home" breadcrumb". 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brangi** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11288
