### ISSUE TITLE
CT-Filter: Pull additional filter data via GIDS Scorecard Fetch API [DRAFT]

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#11086]
As a developer, I need GIDS to pull additional data elements from the Scorecard API so that they can be leveraged in version generation to create additional filters within the comparison tool.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The following data elements are retrieved via the Scorecard API and saved in GIDS:
    a. HBCU
    b. Men Only (menonly)
    c. Women Only (womenonly)
    d. Religious Affiliation (RELAFFIL)
    e. HCM2
    f. PCTFLOAN
2. Documentation is created that outlines valid data elements for the values in AC1.

## Supporting Artifacts:
1. [College Scorecard Documentation](https://collegescorecard.ed.gov/data/documentation/)
2. [College Scorecard Technical Documentation](https://collegescorecard.ed.gov/assets/FullDataDocumentation.pdf)
3. [CollegeScorecardDataDictionary.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4904787/CollegeScorecardDataDictionary.xlsx)

**Comment by zurbergram** [comment]
For AC#2 see Supporting Artifact#3 and search for requested data name under the VARIABLE NAME column

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/681

Database query below to quickly check if data was pulled, fetching without the PR won't return any results, fetching with the PR will return results.

```
select "cross", hbcu, menonly, womenonly, relaffil, pctfloan
	from scorecards
	where hbcu is not null 
	or menonly is not null
	or womenonly is not null
	or relaffil is not null
	or pctfloan is not null
```

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-13 at 12.40.32 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/243d3ae8-22c5-4dc7-8e3b-95ec10da75a2)

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA
