### ISSUE TITLE
[Ongoing Service] IA support for DEPO platform teams

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#11081]
### High Level User Story/ies
As a member of VSP or another team that contributes to the DEPO Platform, I need support from an information architecture expert, so that I can better support VFS teams and VA.gov.

### Additional Details/Notes (optional)
This super epic is used to track VSP's IA support for non-VFS teams. This may include such tasks as: 
- Documentation IA
- Global IA maintenance/governance in CMS
- "Customer support" for teams re: non-VFS topics (ex. fielding questions from Lighthouse or VANotify)

### Communication
- Team that owns this super epic: Content & IA

**Comment by mnorthuis** [comment]
Closing old epic for tracking IA work.
