### ISSUE TITLE
Discovery on testing tools for the forms library 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#11098]
## Overview 

[This](https://github.com/department-of-veterans-affairs/vets-website/pull/12669) change adds a debugging tool to the forms library in the test environment to help change and share form state.

Some forms like 526 are very long and filling them out to test a specific page state is time consuming and error prone. It's difficult to report steps to reproduce bugs and test UI / accessibility fixes. 

Some form flows require the user to have certain state. 

## Tasks 

- Review the tool mentioned in the PR above
- Document state management issues related to testing, QA, design review

**Comment by rianfowler** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10471

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
