### ISSUE TITLE
[Frontend] MDOT- Update Address Schema For DLC Military Addresses

### ISSUE THREAD

**Issue by mr0sari0** [department-of-veterans-affairs/va.gov-team#11093]
## Description

The address schema for MDOT needs logic added in to handle how the DLC is sending military base addresses.

**Comment by mr0sari0** [comment]
Waiting on the DLC to confirm what their production data looks like for military base addresses.

**Comment by mr0sari0** [comment]
Placing in backlog as agreed upon in 07/14/2020 standup. The reason is because DLC has not provided us an example of a military base address in their production data.

**Comment by leahkeeler** [comment]
there is no action to take on this
