### ISSUE TITLE
Analytics Implementation or QA Support for Debt Letters MVP

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11091]
# Google Analytics Implementation or QA Request

**PLEASE NOTE:** The MVP Release will only be one page listing out the debt summary and debt letters. The second iteration will provide a detail page with debt details and status. 

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA? **Implementation** 

- Who is this request for? BAM2 - Debt Letters MVP-Leah Keeler @leahkeeler @bradl3yC 

    - [Insert Name(s)]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
   BAM2, Debt Letters 
    
 
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - [va.gov]

- Please provide any upcoming deadlines or important milestones
    _no launch date set yet
    

- Typical Website Interactions to Track

  
    -  https://staging.va.gov/debt-letters - total visits, bounce rate 
    - Number of debt letters viewed/downloaded 
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

• vets.gov.user+1@gmail.com (Greg)
• vets.gov.user+228@gmail.com (Mark)
• vets.gov.user+38@gmail.com (Pauline)
• vets.gov.user+14@gmail.com (Jerry)
• vets.gov.user+17@gmail.com (Eddie)

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    -The debt letters download page has not been created yet

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thank you @leahkeeler , confirming receipt! Will be in touch here soon.

**Comment by leahkeeler** [comment]
Hi @jonwehausen - wondering when y'll have this slated for? We are planning to release MVP as soon as next sprint @bradl3yC -fyi

**Comment by jonwehausen** [comment]
Okay @leahkeeler , thanks for letting us know! We will bump up on our priorities to get you all the DL necessary for this.

**Comment by jonwehausen** [comment]
### Datalayer Specification

### Developer Notes
- Dynamically populate `letter-type` and `letter-received-date` according to the row of the table 


Description of Interaction | Screenshot | DataLayer Spec
------------ | ------------- | -------------
Click to download the letter | ![image](https://user-images.githubusercontent.com/48527022/87978649-c8291300-ca9e-11ea-8a95-277587c2dd2f.png) | `'event': 'bam-debt-letter-download',` <br> `'letter-type': '<letter_type>',` <br> `'letter-received-date': '<date_of_receipt>'`

**Comment by jonwehausen** [comment]
@bradl3yC Comment above represents our DL spec for tracking the downloads, thank you sir!

**Comment by jonwehausen** [comment]
### QA Testing

Description & Screenshot of Interaction | DL Screenshot | GTM Tag Screenshot | Test Status
------------ | ------------- | ------------- | -------------
Click on "Download letter PDF" for second demand letter within letter grid ![image](https://user-images.githubusercontent.com/48527022/89320034-f5ed8a80-d64e-11ea-8786-34c10e343d7e.png) | ![image](https://user-images.githubusercontent.com/48527022/89320130-13baef80-d64f-11ea-97be-ee110fd94c53.png) | ![image](https://user-images.githubusercontent.com/48527022/89320348-5ed50280-d64f-11ea-8a25-7fe550c25fe7.png) | ✔️ **PASS**
Click on "Download letter PDF" for first demand letter within letter grid ![image](https://user-images.githubusercontent.com/48527022/89320531-95128200-d64f-11ea-9d84-4a667038ae3f.png) | ![image](https://user-images.githubusercontent.com/48527022/89320687-c7bc7a80-d64f-11ea-923e-045dd59eab65.png) | ![image](https://user-images.githubusercontent.com/48527022/89320591-ab204280-d64f-11ea-8323-115eb0c2ed0e.png) | ✔️ **PASS**


## Validation of Custom Dimension for Date ✔️ 
![image](https://user-images.githubusercontent.com/48527022/89321564-21717480-d651-11ea-868e-5199100720f9.png)

@bradl3yC @leahkeeler this looks great! QA has passed and the events can move to production according to your release schedule.
