### ISSUE TITLE
[Development] HLR: Schema Changes

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#11094]
@edmangimelli says:

# Tiny Little Changes That Aren’t Inconvenient in the Slightest:
`ratingIssueId`, in the HLR Create payload, is now `ratingIssueReferenceId` [1]

`ratingDecisionIssueId`, in the HLR Create payload, is now `ratingDecisionReferenceId` [1]

all JSON:API datatypes (type field) are now lowercase camelCase: [2]
  `appeals_api_higher_level_review_validation` -> `higherLevelReviewValidation`
  `appeals_api_higher_level_review` -> `higherLevelReview`
  `HigherLevelReview` -> `higherLevelReview`
  `ContestableIssue` -> `contestableIssue`

the show endpoint fields are now camelCase: [3]
  `form_data` -> formData
  `updated_at` ->` updatedAt`
  `created_at` -> `createdAt`

The contestableIssues endpoint is now nested under the specific decisionReview type: [4]
  was:
    `services/appeals/v1/decision_reviews/contestable_issues/`
  is now:
    `services/appeals/v1/decision_reviews/higher_level_reviews/contestable_issues/{benefit_type}`
note: the benefit type is no longer hardcoded to compensation --it must be specified.
The headers are still the same (X-VA-SSN and X-VA-Receipt-Date)

### Why?
[1] changing these fields to match the response from the contestable_issues endpoint. Caseflow uses reference in ID field names to indicate that an ID is for an outside system.
[2] consistency. this is what Fast JSON API gem defaults to
[3] consistency.
[4] is more RESTful and gives us some wiggle room for NOD without jumping a major version

**Comment by luke-gcio** [comment]
Updated to 5 points - more than we thought and new team member on this ticket.

**Comment by edmangimelli** [comment]
gonna give Anna my draft PR this afternoon so we can start discussing it (and before I invest too much in testing).
also have a PR in vets-json-schema that needs review, and will need a handful more reviewed before this PR (in vets-api) gets closed out.

**Comment by edmangimelli** [comment]
ran out of time to go over the draft PR.
asking for a review on another vets-json-schema PR
https://dsva.slack.com/archives/CBU0KDSB1/p1598529641385300

**Comment by edmangimelli** [comment]
got the last of the updates to vets-json-schema pushed up for review.
this will enable me to finish the vets-api PR

**Comment by edmangimelli** [comment]
This is blocked.
Needing review (and merge) of vets-json-schema PR to continue with vets-api PR

**Comment by edmangimelli** [comment]
Still blocked.

The vets-json-schema PR is being ignored/blocked. Spent a good chunk of time yesterday trying to unblock it.
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/496

**Comment by edmangimelli** [comment]
This was blocked for a week but has finally unblocked (<- the blocking is now part of a larger conversation).

Fixed a couple things for Robin yesterday. Tests are passing this morning --just need one more thumbs up from Anna

**Comment by edmangimelli** [comment]
Anna approved. Waiting for VSP to approve

**Comment by edmangimelli** [comment]
VSP approved!  MERGED!!!
