### ISSUE TITLE
GIDS: Research and document feasibility of uploading excel file to GIDS

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#11095]
As a developer, I need to research the feasibility of uploading an excel file to GIDS so that it can be determined if the Accreditation file upload process can be streamlined.

## Assumptions:
1. N/A

## Acceptance Criteria
1. Documentation outlining the steps needed to upload SA2 to GIDS and an LOE OR documentation outlining why uploading excel to GIDS is not feasible is attached to this story.

## Supporting Artifacts:
1. Data file source: https://ope.ed.gov/dapip/#/download-data-files
2. [AccreditationData.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4899258/AccreditationData.xlsx)

**Comment by dmccurdybah** [comment]
# GIDS Excel File Import Support

## Suggested Solution

It should be possible to allow uploading of 'xls' and 'xlsx' files into GIDS using the following Ruby gems.

- roo https://github.com/roo-rb/roo
- roo-xls https://github.com/roo-rb/roo-xls

The Roo documentation says that it supports
- "Excel 2007 - 2013 formats" for xlsx files. 
- .xls files

## LOE

The work should be possible for one developer to complete in one sprint.

## Implementation Notes

Most of the upload functionality is handled in `lib/csv_helper/loader.rb` but there will also have to be changes made to `app/views/uploads/_form.html.erb` to allow the upload of XLS and XLSX files.

All column value converters (`NumberConverter`, `InstitutionConverter`, etc.) will need to be supported.

Tests should be written to verify that data imported from a CSV and Excel file with the same contents are identical.

## Assumptions

- All uploadable types should support CSV and XLS, XLSX uploads
- Excel files will have all relevant data in the first sheet.
- Excel files will use the same column names and data structure as the CSV files.
- It's possible that Microsoft Excel will make changes that are not supported by Roo.
- Exports will still be CSV files
