### ISSUE TITLE
Create transformer for node-full_width_banner_alert

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11101]
## Description
Create the following for the `node-full_width_banner_alert` bundle:
- Input schema
- Transformer
- Output schema

**Comment by jhonnyoddball** [comment]
Having an issues with this transformer. See comment on [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13553#issuecomment-663043153)

![Screen Shot 2020-07-22 at 4.03.32 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/8ffde72e-3207-42bb-9035-db53292aabc9)

**Comment by jhonnyoddball** [comment]
Done!
