### ISSUE TITLE
Create transformer for node-nca_facility

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11105]
## Description
Create the following for the `node-nca_facility` bundle:
- Input schema
- Transformer
- Output schema

**Comment by theodur** [comment]
Merged in https://github.com/department-of-veterans-affairs/vets-website/pull/13594.

This transformer won't be used until 6-12 months from now. 
https://dsva.slack.com/archives/C01512KN35G/p1596135220347100
