### ISSUE TITLE
Create transformer for node-vba_facility

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11110]
## Description
Create the following for the `node-vba_facility` bundle:
- Input schema
- Transformer
- Output schema

**Comment by theodur** [comment]
Merged in https://github.com/department-of-veterans-affairs/vets-website/pull/13599. This transformer won't be used for the next 6-12 months. It can be updated as needed when it's in use. 

Context: https://dsva.slack.com/archives/C01512KN35G/p1596135220347100
