### ISSUE TITLE
CF: Remove "VA may suspend benefits to this school." from caution flags

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#11116]
As an Education Services team member, I need the caution flag language updated so that it effectively communicates to the users of the comparison tool the state of the caution flags for an institution.

## Assumptions:
1. This story will remain open until this work is delivered to production.
2. The changes have been reviewed by EDU in staging and approved as of [TBD]

## Acceptance Criteria
1. The description for caution flag "Federal Trade Commission (FTC) filed suit for deceptive action" is: "The FTC filed a suit against this school for deceptive action."
2. The description for caution flag "States Attorney General Filed Suit for Deceptive Action" is:  "The state's Attorney General filed suit against this school for deceptive action."
3. A document is created that lists the institutions that have these caution flags so that it can be provided to EDU.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
For AC3:

Using `Settlement_06242020.csv` and `WEAMS_School_Data_07082020.csv` from prod the database query below returned the results in [11116_AC3.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/4913328/11116_AC3.txt)

```
select i.institution, i.facility_code, i.cross, s.cross as settlement_cross, s.settlement_description 
	from institutions i join settlements s on i.cross = s.cross
        OR i.facility_code = s.cross
	where s.settlement_description in ('Federal Trade Commission (FTC) filed suit for deceptive action', 'States Attorney General Filed Suit for Deceptive Action')
	and i.version_id = 5
```

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/682

**Comment by sonntag-adam** [comment]
AC 2 The description for caution flag "States Attorney General Filed Suit for Deceptive Action" is on the front end suppose to be "State's Attorney General filed suit for deceptive action"

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-14 at 10.58.08 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/64dfe044-f1c0-4668-91f7-2fca686ee293)
##
![Screen Shot 2020-07-14 at 10.58.17 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a9508788-0fce-4a1f-a8f6-813c45e22056)
##
![Screen Shot 2020-07-14 at 10.58.23 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cf14d021-e0d5-486b-948c-d24ffb1e62c0)
##
![Screen Shot 2020-07-14 at 10.58.31 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e74b5086-1a8b-4cf2-a199-65fe9be83e03)
##
![Screen Shot 2020-07-14 at 10.58.37 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8e87645f-acdb-4840-802a-83ad653b3ea1)
##
![Screen Shot 2020-07-14 at 10.58.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7a27aa56-171e-4d33-b7e4-2e810e4d3723)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-14 at 11.04.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4431c1dd-d37b-4eaf-8257-9e0c07d1ade7)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9504&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam This checks out for UX!

**Comment by sonntag-adam** [comment]
Closing story.
