### ISSUE TITLE
Redirect: Request for input

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11133]
**NOTE: This issue is to request input on the need for redirects.**

### Description
When a Veteran performs a search on Facility Locator, the search results list includes links to detail pages about the location. 

For a variety of reasons, the Facilities team will be hiding Facility Detail pages for Community Care locations. [#10324](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10324) Note: this change will not impact VA locations. 

URLs for these pages follow this format `/find-locations/provider/ccp_1053359729/`

To evaluate the need to implement redirects on the soon-to-be-suppressed Community Care facility detail pages, here is data pertaining to views of those pages and their source over the last three months. 
Total sessions = number of Community care facility detail pages visited
Direct sessions = number of sessions initiated directly  

![image (41).png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/1cfad09c-a9be-4b12-852e-fff4233a5c55)

**Given this information, we would like input on whether or not a redirect for the suppressed Community care detail pages will be necessary.** 

### Requestor team info

Facilities team

- Michelle Middaugh, Product Manager (Ad Hoc)
- Dave Conlon, Product Owner, DEPO

I will populate the remaining information if a redirect is recommended

----

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
*enter current URL* | *enter new URL*

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@mmiddaugh Is the intent to hide these pages temporarily or permanently?

**Comment by mmiddaugh** [comment]
They've been suppressed for some time already and will likely be hidden long term.

**Comment by mmiddaugh** [comment]
@davidconlon do we need to continue this request?
