### ISSUE TITLE
CT: /mo missing from estimated housing

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#11141]
The /mo is missing from estimated housing. Navigate to https://www.va.gov/gi-bill-comparison-tool/profile/11806124. Observe.

![Screen Shot 2020-07-10 at 3.10.44 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e834acb3-f5f6-4326-a637-814f599fd860)
##
What it should look like
![Screen Shot 2020-07-10 at 3.08.35 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b46679aa-4bfc-4cc5-8b2f-c07f6167aa40)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13463

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-13 at 8.07.17 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/aa80efff-f41e-4c9e-beb5-1804ff5f3806)
##
![Screen Shot 2020-07-13 at 8.07.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/fb5d03b2-4aae-4ef8-aea2-aab671e5ffab)

**Comment by sonntag-adam** [comment]
Fixed in production. Closing bug.
