### ISSUE TITLE
Design feedback - Design intent Collaboration [MVP learning center templates] 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#11143]
**Questions:**
- Would you ever consider having a “top tasks” section -- or similar -- in the learning center, similar to the home page?
- On the checklist page type: Do you imagine the checklist to be interactive? (was that the purpose of the blue outline, instead of the gray?)
- Do you imagine if someone selects “Search VA.gov” that would return the global search UX?
- Would you ever consider using the benefit hub icons on the learning center home page?
- Where would the “Was this page helpful” data go? (exciting!)
- If the tags test well, would you add these to the design system? 

**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**
- No "do" feedback at this time

**Try:**
- No "try" feedback at this time

**Consider:**
- Consider the different states for tags (hover, click, etc…)
- Consider using the additional info component for any “learn more” information
- Consider using the secondary button (outline) when there are 2 main calls to action

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (No do feedback for this ticket, so I checked it off)

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by jilladams** [comment]
Cleaning up Public Websites tickets. THis is only open item from #10953 and Learning Centers launched. Closing. Feel free to reopen if this is valuable for follow up.
