### ISSUE TITLE
Express Care Availability Check

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#11145]
## Issue Description
In order to determine whether to display the Express Care tab and messaging up top, we need to first check if any of the facilities in the user's systems supports Express care. We'll do this by either calling the `getFacilitiesBySystemAndTypeOfCare()` for each system, or if we find a different method in our discovery.

## Acceptance Criteria
- [ ] Make appropriate API calls
- [ ] Store necessary data in state
- [ ] Update homepage prompt to use check and show correct hours (if homepage ticket already done)
- [ ] Update tab to show if any EC hours found (regardless of if current time is window, if tab ticket is already complete)

**Comment by lenaecb** [comment]
Watching [VAOSR 927](https://issues.mobilehealth.va.gov/browse/VAOSR-927)
