### ISSUE TITLE
FE BUG: GET enrollment_status called on every change to contact info data

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#11152]
Sometimes, when you change a value of a Profile 2.0 contact info field, a call to `GET enrollment_status` is made.

![get-esr-on-change.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/27b7c7eb-943c-45e3-8b48-46bb2414c4ac)

This was introduced with [this PR](https://github.com/department-of-veterans-affairs/vets-website/issues/13148) and looks to be due to the `hasUnsavedEdits` prop that was added to the `PersonalInformation` component (https://github.com/department-of-veterans-affairs/vets-website/blob/d001f47feb3d0432d068bff78a315a9b6848746e/src/applications/personalization/profile-2/components/personal-information/PersonalInformation.jsx#L51). When that value changes, it triggers a re-render of the entire profile. The `getEnrollmentStatus` action creator is called by the `ReceiveTextMessages` component rendered by the `VAPPhoneField`.

**Comment by sanlouise** [comment]
@mshea0606 I don't think there is anything to validate on your end, I will verify in staging that this PR prevents those calls from being made.
