### ISSUE TITLE
CT: School names expand over the center line of the cards.

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#11159]
Navigate to https://www.va.gov/gi-bill-comparison-tool/search?category=employer&name=California. Zoom in to around 150% you can see the school names going over center. Around 175% you can see them push past well over the center
![SRPat120Percent-20200710.jpg](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bc69c7ed-900c-4665-bda2-1643578b243d)
##

![Screen Shot 2020-07-13 at 10.12.25 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/21d1dafb-65b5-44c0-93ed-7ce1792459a3)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13470

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-13 at 12.47.06 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/988335fb-39b0-45b1-a2cf-b835e9db7097)

**Comment by sonntag-adam** [comment]
In staging, testing passes QA
