### ISSUE TITLE
CT: /mo added to Estimated benefits per term

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#11158]
/mo is added to all values under Estimated benefits per term.

Navigate to https://www.va.gov/gi-bill-comparison-tool/profile/11806124. Observe.

![Screen Shot 2020-07-13 at 9.47.30 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/81cf22ec-418e-4a85-bac6-dc5369ba057b)
##
What it should look like. There should not be /mo after the numeric values
![Screen Shot 2020-07-13 at 9.49.38 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/09ab882c-db80-451b-a690-229bb2bc2aef)

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13466

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-13 at 10.46.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9348c5a0-a30a-4a31-80b9-94f27ceb4a5f)

**Comment by sonntag-adam** [comment]
Fixed in production. Closing bug.
