### ISSUE TITLE
Create a Conversation Guide for Stakeholder Interviews

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11160]
As we prepare for clinician (physician and nurse) and Admin Staff interviews we want to have a consistent interview doc to walk through questions with each participant.  The below docs will be used by our team and do not need to go through the formal user research approval process. These docs will be a collaboration with PO/PM/Researcher

- [x] [Create Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/clinician-interviews/research-plan.md)
- [x] Create [Questions List](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/clinician-interviews/clinician-questions.md)

**Comment by abuckley3385** [comment]
@arickalewis1 can you please update this issue with links to the docs you created in github

**Comment by arickalewis1** [comment]
@abuckley3385 absolutely. @LEHigley mentioned in Slack that there isn't a need for a conversation guide. I hadn't started one but can remove it from the criteria if we are just going off of the questions list.

**Comment by arickalewis1** [comment]
This one is done. Closing now that we have kicked off these interviews
