### ISSUE TITLE
[Bug] CMS Drupal Events

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#11163]
# Google Analytics Bug

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Google Analytics events have stopped firing for Drupal CMS property, investigate root cause

## Acceptance Criteria
- [ ] Debug & identify root cause - determine how we can prevent from happening again in the future
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@kevwalsh / @ethanteague 

Thank you both for bringing this issue to our attention.

**I believe we have found the root cause of this issue.** 

For context -- during implementation, we setup two different GTM environments to segment lower CMS environments from Production. This was to aid in testing on our part and not impact production data when we wanted to test things in lower environments specifically.

It looks like currently in prod.cms.va.gov the GTM preview mode that is being loaded is pointed to our dev/staging snippet with an id of 5(see screenshot below)...`gtm_preview=env-5`. 

This caused issues because our gtm staging environment for `env-5` was still running an older version of our event tracking. We have since updated `env-5` to have the latest GTM version so events are now firing within production, that said we will want to get the environment prefix updated on the FE of the site to `env-2` to correct for future deployments. We also want to ensure this is not something can be risked 

![image](https://user-images.githubusercontent.com/48527022/87331534-1fac0980-c508-11ea-9e50-071cf1daa84e.png)


###  **Events currently firing**
![image](https://user-images.githubusercontent.com/48527022/87332332-64847000-c509-11ea-974c-1611f6cf5b2a.png)

**Comment by jonwehausen** [comment]
Expecting to merge in to production at some point today. 

Will close when the `env` variable has been verified. 

Events have successfully reached the property for the last 3 days.

**Comment by jonwehausen** [comment]
Good afternoon @ethanteague ,

Wanted to loop you in -- we are still seeing `env-2` populated in prod.cms.va.gov. 

Should we expect this to merge-in today? 

![image](https://user-images.githubusercontent.com/48527022/87970095-4088d780-ca91-11ea-851a-96562a6191d2.png)

**Comment by ethanteague** [comment]
Yep, @jonathanjnelson - should be later this afternoon.

**Comment by jonwehausen** [comment]
In light of conversation here: https://dsva.slack.com/archives/CT4GZBM8F/p1595270475041100

Looks like just updated the `env` param caused an issue with auth. 

Please see the full snippet we will need implemented on prod.cms.va.gov @ethanteague 

Paste this code in as high in the `<head>` of the page as possible
```javascript
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=hHvHnY1eIx1IOSJMAnOBLA&gtm_preview=env-2&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WQ3DLLB');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening `<body>` tag: 
```javascript
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WQ3DLLB&gtm_auth=hHvHnY1eIx1IOSJMAnOBLA&gtm_preview=env-2&gtm_cookies_win=x"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by bsmartin-ep** [comment]
@jonwehausen / @kevwalsh / @ethanteague

#### Prod CMS looks good...

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/e94b1751-170f-4eef-b78f-f09c1708bcdc)

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/9352f8c2-f8e7-429a-b8dc-1c8a96bac0b8)

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/b957d154-3009-4a6a-8a7b-e8ac722cca4c)

------------------
#### ...but it appears dev CMS is also pointing to the prod GTM environment.

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/222e6b2b-4bf4-4014-84df-10cae2a4106a)

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/d7202a5a-e7c3-46c2-a195-eecb771db9ab)

https://dev.cms.va.gov/modules/custom/va_gov_backend/js/gtm_tag_push.js

--------------------------
@jonwehausen - should dev.cms.va.gov point to `env-5`?

**Comment by jonwehausen** [comment]
Hi @ethanteague , 

Per Brian's post above, this isn't causing any issues today, but we will want to update dev.cms.va.gov to have the following snippet: 

**Paste this code as high in the <head> of the page as possible:**
```javascript
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=GDc7Zfyf8G-0S5j8FC1WXQ&gtm_preview=env-5&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WQ3DLLB');</script>
<!-- End Google Tag Manager -->
```

**Additionally, paste this code immediately after the opening <body> tag:**
```javascript
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WQ3DLLB&gtm_auth=GDc7Zfyf8G-0S5j8FC1WXQ&gtm_preview=env-5&gtm_cookies_win=x"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

**Comment by jonwehausen** [comment]
Hey @ethanteague, 

Just wanted to bump this to help get closed out. 

@bsmartin-ep identified we need to make the update on dev CMS as well. This isn't currently affecting anything as our GTM environments dev<>prod are all aligned, just want to make sure we get this solidified in dev as well. 

Once we've got the two snippets in and validated, we can close. Thanks again for your assistance!

**Comment by bsmartin-ep** [comment]
Is this ready to test on CMS dev @ethanteague?

FYI - I am seeing an error in the console that appears related to your PR:

<table><tbody><tr><td>
<img src="https://user-images.githubusercontent.com/62304138/90527275-5c8aa200-e13f-11ea-8055-5c26a85f170d.png" /> </td><td> <img src="https://user-images.githubusercontent.com/62304138/90527336-6e6c4500-e13f-11ea-9181-6a50d245619a.png" /></td></tr></tbody></table>

**Comment by ethanteague** [comment]
Yep, it's ready, @bsmartin-ep - I'll look into that err.

**Comment by bsmartin-ep** [comment]
Looks like the error has been addressed @jonwehausen.  I still get a 403 on the actual GTM snippet (on all environments), but I believe that is related to my usage of the SOCKS proxy and not the code.

```
if (drupalSettings.environmentIndicator) {
     env = drupalSettings.environmentIndicator.name === "Production" ? "2" : "5";
}
```
Closing.
