### ISSUE TITLE
Access for Laurence Guild

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#11168]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Laurence Guild
- Please Provide your email.
   > lguild@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > developer for Health Care Experience Team for GovernmentCIO 

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTUrseGkg8rI0Y7NaSfYyZ92QU1mMgcIHiISnkPB8MNE/7fYw03Kzgu8fQyxFOvMxJAKQRFznlW0VvJESzRhxFEziPtUlRFC/lYMWurKIlFViGSiQAYtK0iroaasp6E0U3VAv4tJaTv2rQK11sY+774GvENA/z2PHQD3Zf2p7mSiBwJ8HntepFPWdP8oQVCyqwS1KHKw8Vp59v2zVO4hZWBWO+hHecuitLBm85pJTjsFzhFGxk+WT5uK7713cOsC/zK+dGNt7SWmFTdZcS/aXHksAlWfo1LZhKkJC5nWZCu9LvnJnCiylt88hpDQkh85qNtAZXORO5E8RZXlAP4U48Hs+gBNKWX5K03H5bC3kFrv02KAaK5HTOuRWF/45S8wCg6d4hMI+0EnfW2ObV14SG21t97aP+jvOoVdDhnyPUEOXbKLSuf5SUQTRDvWvj63VH/AwvHaIx0wsN/KT0gzni0KY7CkoZudWzzhVpl6VaTr+2OXsYE1d03hZpLUQDGYE= lguild@lguild-VirtualBox
```

- Grant AWS Console access?
  > YES
  @department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@massrb 
Laurence, please confirm you have socks proxy access now.

Thanks,

**Comment by massrb** [comment]
This URL gives me a 404, not sure why: 
https://github.com/department-of-veterans-affairs/devops/raw/master/ssh/config

**Comment by jsev-io** [comment]
Seems you don't have access to that repo, can you give me a name of someone you report to on your team?

**Comment by massrb** [comment]
Yana Roy

**Comment by jsev-io** [comment]
@massrb has confirmed connectivity to proxy. Closing ticket.

**Comment by massrb** [comment]
I need AWS access so I can access keys to test the MAP sandbox. Taylor Skinner said to reopen this issue

**Comment by jsev-io** [comment]
**Requesting AWS **Approval
cc @Jeff-Hayter 
User: Laurence Guild
COR: Mary O'Toole

**Comment by jbritt1** [comment]
First time login credentials provided to user.
