### ISSUE TITLE
Need more SOCKS documentation for dummies like myself

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#11172]
## What happened?

I had the whole SOCKS proxy working a few weeks ago (my personal Mac outside the network). I had to reboot my machine and the thing wouldn't start up due to the "permission denied (publickey)" error. Because I am a dummy who barely knows how to spell "ls -l", I started over from scratch. Then I realized I probably shouldn't have done the step where I generate a key. I wish I hadn't done that, I think I have to start all over by notifying the team what my new key is. And I will do that but I don't have the time to spare and mess with it right now. These things usually take hours for me, again, admittedly, I am a dummy when it comes to anything in Terminal.  

I browsed various threads on Slack and most of them go something like:
1. I'm having publickey problems
2. Helpful folks chime in on Slack
3. Offer to help via zoom or a Slack call
4. Thank you note from original poster that their zoom call fixed everything with no resolution posted for folks like me to learn from later

Is it possible to provide some doc for the use case where you had it working at one point then you rebooted and now it's broken?

Thanks for your consideration. cc @mchelen who asked me to open this issue to improve the SOCKS docs.

## Specs:
- Device: Macbook Pro, outside VA network

**Comment by mchelen-gov** [comment]
Probably what needed to happen was to run https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/pages/getting-started/internal-tools.mdx#for-internal-developers step 4 again.

The optional following part about OSX should have done this for you, did you add this to the top of your `~/.ssh/config` file?
```
  Host *
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile ~/.ssh/id_rsa_vagov
```

**Comment by artsymartha68** [comment]
I'm not kidding when I say I'm a dummy. I have no idea how to open and edit a file in terminal. I know I need to research that and learn how to do it.

**Comment by mchelen-gov** [comment]
@artsymartha68 that's ok! that file can be opened in any plain text editor. you can probably do "file -> open" and copy + paste in `~/.ssh/config`. this is probably something else the docs could explain better.

**Comment by artsymartha68** [comment]
Google is my friend! It would be nice to add these instructions to the documentation.

Run the open ~/.ssh/config command to open the file. 
Copy and paste the following into the top.
Save the file.

Or something like this.

**Comment by jsev-io** [comment]
@artsymartha68 We use the "curl" command listed in the documentation in place of "open this file and copy and paste" because it takes out a step that can potentially result in user error. It does the copying and pasting for you :).

It basically says:
1. Download ("curl") this page ("http://www.path.to/page") 
2. Put the contents of that file (">")
3. into my config file ("~/.ssh/config")

Hope this helps!

**Comment by jsev-io** [comment]
@artsymartha68 

> I had the whole SOCKS proxy working a few weeks ago (my personal Mac outside the network). I had to reboot my machine and the thing wouldn't start up due to the "permission denied (publickey)" error. Because I am a dummy who barely knows how to spell "ls -l", I started over from scratch. Then I realized I probably shouldn't have done the step where I generate a key. I wish I hadn't done that, I think I have to start all over by notifying the team what my new key is. And I will do that but I don't have the time to spare and mess with it right now. These things usually take hours for me, again, admittedly, I am a dummy when it comes to anything in Terminal.
> 
> Is it possible to provide some doc for the use case where you had it working at one point then you rebooted and now it's broken?

That initial permission denied error could have been because you didn't re-run the `ssh-add ~/.ssh/id_rsa_keyname` command after restarting.

Also, when you say rebooted, can you clarify? Are you saying you actually rebooted the computer? Or than you reinstalled your operation system and your system is starting from scratch?

If the former is the case, then yes, you probably didn't need to generate a new key, overwriting your previous key if you saved it as the same name. Not a huge problem, we just need to update your public key here to correspond to the new private/public keys on your machine.

**Comment by artsymartha68** [comment]
Restarted the mac. Have not reinstalled the OS.

**Comment by mchelen-gov** [comment]
@jsev-io agree about curl usage for config download. what about the osx "add this to your ssh config" part though?

**Comment by artsymartha68** [comment]
+1 with @mchelen but after I did the curl step, the resulting config file **did not** have the section I was told to add:

  Host *
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile ~/.ssh/id_rsa_vagov

**Comment by jsev-io** [comment]
> @jsev-io agree about curl usage for config download. what about the osx "add this to your ssh config" part though?

@mchelen-gov Alas, I'm but a lowly windows WSL user. 😂

> +1 with @mchelen but after I did the curl step, the resulting config file did not have the section I was told to add:

@artsymartha68 I believe that's for you to add separately only in the case that you are an OSX user.

**Comment by artsymartha68** [comment]
OK my publickey is back in working order via the attached ticket. HURRAY! THANK YOU!!!

Is there a consolidated set of instructions for me to follow after I have to restart my machine one day?

**Comment by mchelen-gov** [comment]
@jsev-io haha no worries, any idea who can help get the osx docs fixed?

**Comment by jbritt1** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/11950 adds explicit notes about restarted terminals and includes some optional/additional notes from the web about automating the process.

**Comment by jbritt1** [comment]
Added suggestions from this ticket in @11950. Closing this one now to consolidate. Please use #11443 for any added feedback / suggestions.
