### ISSUE TITLE
Analytics Reporting Request for Beth Potts

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#11177]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Beth Potts and Paul Shute (in Compensation Service)

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - Public Websites
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
I'm not sure what would be helpful here. What timeframe would you recommend for getting a snapshot of the path to/state of authentication when filing a claim for disability compensation?

## Analytics to Track Down
> Examples
> 
> - [ ] Compare metrics on Veterans who are signed in (authenticated) vs unauthenticated who start on this page (https://www.va.gov/disability/how-to-file-claim/) to get the 526-EZ application. 

I'd like to know how many unauthenticated users start clicking through the wizard on this page and pause to sign in when prompted, then proceed to the application **vs** number of authenticated users who file a claim starting from this page.

## Which Product Questions are you trying to answer?
The business line has created assets (a one-pager guide and a video series) that feature screen shots of our How to file a claim page. I noticed that the path they were stepping users through said they should start by signing in. That's not the best guidance if most users are unauthenticated when they start clicking through the wizard to get to the 526-EZ application. I want to find out which path is more common, so they can update their assets accordingly.

## Other Helpful Questions to think through
- Who is your audience? Veterans.
- Why do you need this data? I'm collaborating with the business line about how users interact with our site to reach the 526-EZ, so they can provide the best possible experience to Veterans who might see their materials. 
- What are you hoping to find? How Veterans enter the 526-EZ--are they authenticated when they start clicking through the wizard on the How to file page to reach the application or unauthenticated?
- What is your hypothesis that you're hoping the data will support? I think most Veterans are unauthenticated when they start interacting with the wizard. 
- What area of the VA are you hoping to assess? The path Veterans take when going to the application.
- How frequently do you need this data? Just once. 

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thank you @bethpotts ! We will take a look and get back with you

**Comment by jonwehausen** [comment]
### Things to note / limitations
Here are some of the limitations with the data we have that limits our accuracy + precision: 
- We don't yet have direct tracking on the /disability/how-to-file-claim wizard components, we are working on this sprint standardize that tracking across all "How To" wizards
- This essentially means we can't build a funnel that says the user **precisely** engaged with the wizard directly before or after login, so we must work with what we have from a page-level perspective

### Sample Reports for Review
- [Custom report template](https://analytics.google.com/analytics/web/template?uid=gROH8cJHRt63rQiTF2FXbQ) for users, sessions, pageviews where previous page from `/disability/how-to-file-claim/index.html` was one of the `/auth` pages -- indicating user logged in from 
- [Custom report template](https://analytics.google.com/analytics/web/template?uid=MffA3oPdRQCx62X1ZdDd3Q) for users, sessions, pagesviews where previous page was **NOT** an authentication page but user had an LOA level (indicating they must have already been logged in) 
 
We want to look at how we can segment this data to now determine how this correlate with 526, whether people are logged in already when getting to 526

**Comment by bethpottsVADEPO** [comment]
Thanks, @jonwehausen ! It sounds like you need a little more time to drill down more into this? I'm working with stakeholders on a project for which this info will inform direction of work, so if you could give me a sense of timeframe for your being able to get the data we need, that would be really helpful. Thank you!

**Comment by jonwehausen** [comment]
Hi @bethpotts, 

Yes we need a bit more time to dig in, thank you very much for your patience up to this point -- We're close but need to a bit more fine-tuning to surface as accurately as we can. 

Would it be alright if we got you final results by end of week?

**Comment by bethpottsVADEPO** [comment]
End of week would be amazing. Thanks so much!

**Comment by jonwehausen** [comment]
@bmcgrady-ep / @bsmartin-ep 

Sometime before end of week -- Could I have you peer review my results here? Use WBC Modernized View and Jan 1 -- June 22 date range for each. 

Both of these items we're obviously working to correct, however, given our current limitations of:
 (1) Not having direct wizard tracking in terms of if someone started clicking on the wizard or not, we are forced to utilize page paths as a source of truth
 (2) Limited authentication tracking given our outstanding post authentication parameter issue, again forcing us to use specific auth page paths as source of truth

### Be Sure to Check 
- [ ] Ensure logic of Include / Exclude filters on each custom report is correct
- [ ] Ensure logic of RegEx on each custom report is correct

Report Template Link | Interpretation | Users
------------ | ------------- | -------------
[How To Page - Previous Page WAS an Auth Page](https://analytics.google.com/analytics/web/template?uid=mrVF3J_4Q0ut6yuH1mbWwQ) | Those users who authenticated just before reaching `/how-to-file-claim` | **40,907**
[How to Page - No Auth Previous Page and had LOA Level](https://analytics.google.com/analytics/web/template?uid=lu8XM6CVQ_KQlmarSRTFfQ) | Those users who were already authenticated when they reached `/how-to-file-claim`  | **365,143**
[526 Intro Page - Previous Auth Page](https://analytics.google.com/analytics/web/template?uid=FVgscL03SGCwYSSIJLhsQg) | Those users who authenticated just before reaching `/disability/file-disability-claim-form-21-526ez/introduction/` | **88,864**
[526 Intro Page - No Auth Previous Page and Had LOA Level](https://analytics.google.com/analytics/web/template?uid=JEiqLtq_QIaAm_SqPiiA3Q) | Those users who were already authenticated when they reached `/disability/file-disability-claim-form-21-526ez/introduction/` | **179,700**

### Insights
- Working with what we have today, my interpretation of this data would suggest **most veterans <ins>are</ins> authenticated by the time they reach the `/how-to-file-claim` wizard.**
- Taking one step further, the amount of users who appear to be already logged in by the time they reach  `/disability/file-disability-claim-form-21-526ez/introduction/` far exceeds those who log in just before  `/disability/file-disability-claim-form-21-526ez/introduction/` -- 179,700 vs 88,864

@bsmartin-ep / @bmcgrady-ep Let me know if this aligns with your assessment of if you have a better way to segment and support / reject my findings here. Thank you.

**Comment by bmcgrady-ep** [comment]
@jonwehausen - I checked the Filters and the RegEx on each of the reports. Everything looks correct to me and I believe this is the best way to approach the different reports.

**Comment by jonwehausen** [comment]
Hi @bethpotts ,

Thank you very much for your patience on this request! I had my two of my colleagues review my analysis for accuracy and here's our conclusion (the date range for this analysis was Jan 1 2020 - July 23 2020): 

## Please note
As I mentioned, unfortunately due to our current tracking limitations of the wizards and authentication, we were forced to surface these numbers in a more round-about way than we ideally would like... We have existing tickets open we are actively working through to correct these issues to surface this insight with greater accuracy and ease in the future. 

## Insights Drawn
The data we have to work with suggests that the overwhelming majority of users (**365,143 vs 40,907**) **are in fact authenticated by the time they reach the wizard than those who immediately attempted to login before landing on the wizard `/how-to-file-claim` page**. This conclusion is also supported by the overwhelming majority already authenticated when reaching the 526 form intro page. 

## Future 
In the future as we work through our outstanding tracking limitations we will be able to more concretely draw the distinction and segment for users who absolutely interacted with the wizard before logging in. 

Please let us know any further questions you may have! We would be happy to revisit this in the future as well when our tracking more accurately captures this user journey. Appreciate you coming to us for this insight!
