### ISSUE TITLE
[FE] Align checkmark icons in Account Security

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#11196]
## Background

Related to #11169

For accessibility reasons we need to have all of the green checkmarks aligned in their own 'column' in account security.

## Specs

![Screen Shot 2020-07-13 at 11.46.02 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/cfd3c983-0916-48d0-b65f-cd93ae1dfb18)

## Tasks

- [ ] Update checkmark alignment

## Acceptance criteria 

- [ ] Matt/Tressa has reviewed and approved

**Comment by erikphansen** [comment]
How should we handle this on mobile? This is how it looks now:

![image](https://user-images.githubusercontent.com/20728956/87460867-65c5a380-c5c2-11ea-82e0-536a9fe9ad39.png)

**Comment by tressaellen** [comment]
I actually think that works for mobile. Especially once T&C and the sign in email are swapped. I think Sandra was working on that. 

<img width="329" alt="Screen Shot 2020-07-14 at 12 22 16 PM" src="https://user-images.githubusercontent.com/58752772/87462157-f6e54c00-c5bb-11ea-8de6-9d891b6c1343.png">


<img width="328" alt="Screen Shot 2020-07-14 at 12 14 44 PM" src="https://user-images.githubusercontent.com/58752772/87461942-a2da6780-c5bb-11ea-9083-c2f179e9139d.png">
