### ISSUE TITLE
CT-Search: Modify search queries to enhance search results

### ISSUE THREAD

**Issue by shawkey-daniel** [department-of-veterans-affairs/va.gov-team#11197]
As a Comparison Tool user, I need the search function to be enhanced so that I can find desired schools more easily.

---
## Assumptions
1. This story is completed behind the feature flag #10615

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
1. Institution search results return results sorted by number of GI Bill students descending then similarity on institution name.
---

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/680

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-15 at 2.20.50 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e5021579-a78c-4f25-a665-04c0b1610fc3)
##
![Screen Shot 2020-07-15 at 2.36.05 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/90c3f387-fcbc-4e51-bc29-2edd1c0cb5d9)

**Comment by sonntag-adam** [comment]
In staging. Closing story.
