### ISSUE TITLE
Mask Account Numbers Shown in "View Payments"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11206]
## Goal
Given that account numbers are sensitive and would only need a routing number before becoming actionable from a bad actor, we want to mask those numbers up until the last four digits, similar to how SSN's are sometimes handled, so that we can ensure that the Veterans funds are less vulnerable to theft.

## Considerations
- Confirm that the direct deposit process involves a penny test
  - A penny test with a positive outcome removes any concern for needing to show the account number to the Veteran for correction, making masking a viable solution to sharing which account is in use but not allowing unauthorized access to it.
  - Conversation held [here](https://dsva.slack.com/archives/C909ZG2BB/p1594750093431200) on this topic; result is we will continue to mask
- What about nils? (what do we do when it's a mailed check?) (FE?)
  - What about empty payments? (FE?)
  - What about empty return payments? (FE?)
- Figure out return payments (keep API/interface the same)

## Tasks
- [x] Mask all but the last four digits of the account number as it comes in from the backend.

## Acceptance Criteria
- [x] Account numbers are masked and only display the last four digits e.g., `*********1234`

**Comment by digitaldrk** [comment]
BGS view payments call is not working.

**Comment by digitaldrk** [comment]
We are still sort of blocked here.

We're not certain the call we were given to obtain payment history reliably associates payment information with the vet's account information.

We have shipped an endpoint for now that returns: payments and return payments.

**Comment by jason-gcio** [comment]
Based on the email from Harlow on Tuesday, these endpoints have to be shifted around to accommodate the service call that has all the info.
