### ISSUE TITLE
Improve dependency upgrade management -  Core vs Apps

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#11224]
### Problem

When upgrading dependencies in the `package.json` file for `vets-website`, even though there are no breaking changes, it's causing some apps to break.

A research of a new way to organize the dependencies between core vs apps is needed.

### Possible solution

- Create an alternative dependency type like `peerDependencies` to mark app dependencies and only upgrade core dependencies
- Use monorepo tools like:
  - [Nx](https://nx.dev/react)
  - [Lerna](https://lerna.js.org/)
  - [Yarn Workspace](https://classic.yarnpkg.com/en/docs/workspaces/)

### Resources
- [Why you should switch from Lerna to Nx](https://blog.nrwl.io/why-you-should-switch-from-lerna-to-nx-463bcaf6821)
- [React Microfrontends and Monorepos](https://blog.nrwl.io/monorepos-and-react-microfrontends-a-perfect-match-d49dca64489a)

**Comment by timwright12** [comment]
Closing in favor of the new initiative work
