### ISSUE TITLE
[Placeholder] Update Cerner content after content review

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11239]
## Issue Description
Given we have content we're implementing for the Cerner work and have submitted them for review
I want to make any necessary updates 
so that we incorporate feedback in our implementation.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- Necessary updates for the Cerner implementation is complete

**Comment by kelsonic** [comment]
Might be dup of #10756 CC @MickinSahni
