### ISSUE TITLE
[Documentation] Provide documentation for Navigation, Forms, and Funnels

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#1124]
## User Story
As a VSA/VFS team, I need to access documentation to understand how current naming conventions, tagging structure, and traits (custom dimensions) are passed. I also want to understand how I can build my own Google Analytics funnels and goals.

## Goal
Improve self-service among VSA/VFS teams to research, build, and validate Google Analytics, so we can provide a framework for future development.  

## Acceptance Criteria
- [ ] Jon - Global navigation documentation
- [ ] Nedie - Forms documentation 
- [ ] Nedie - Create funnels and goals in non-Production environment and understand how to validate

## Resources
- See this older issue in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12464 for screenshots of navigation items

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Linking #1541

**Comment by nedierecel** [comment]
The objectives of this issue are replicated in #849, so I will close this task.
