### ISSUE TITLE
[FE] - Update Profile 2.0 Documentation

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#11243]
## Background

We would like to have all Profile 2.0 documentation updated prior to launch.

## Tasks

- [ ] Pre-launch - Update relevant parts of the [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/README.md)
- [ ] If you were a developer onboarding to this product, what documentation would you want?

[general documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account)

**Comment by erikphansen** [comment]
@mshea0606 Do you have links to the existing documentation for Profile v1?

**Comment by mshea0606** [comment]
@erikphansen [Profile 1.0 links](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile)
