### ISSUE TITLE
Access for Martha Wilkes (reset publickey?)

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#11253]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > USDS
- Please provide your name.
   > Martha Wilkes
- Please Provide your email.
   > martha.wilkes@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > UDSD/DEPO

- Requesting SSH key authorization?
   > YES 
- What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDcEGqejij7mMthiP6ppFwBYcsH/6hFhWu/66e3+oQBupLL+RB1ziXhRJf3rG0NrU/0d2MEvzuPvH8gN9aXM8qgeAPm1f9sljkUMrFzofjJmTKXWjmD0dhD4ZBUcIicGd7ARi4s1JUzyK03tKyUm8zFigla2VWjrUjYV9zqvwQJb8iAa2uM4bxlrZG0CsaoPIb5Gepp/lQtL1SwqBubM4M3FwfC2z9bYSQezcJVQSRgS0uSeriIU8aQEgz/RBSzYJ1UHg0j4T6m64jBfPeVJ5RU63dtwNSeAGTr/QFJBZMeSX4ZBdoUVkf4sWhdll50a6azYMsgRAWRyt87Mhkb/dGsnyU0GSsbF+DXY+7AExnDj/g8nVZHQVBhsmcJM50cCrlgZHBxXZ83x9zPhdBTL5598+LuyAQU2ExjoWhronajor+1N4X83OO5s6YW0f32yZLoSB/Nw7IbwhXIHsHxfuJD7nwGbBNs+p6EW0BsjBZC89Dv5WO0Sn67xhQEDkO6TbE= marthawilkes@Marthas-MacBook-Pro.local`

Note that I'm a bit confused about the email address above. I guess this process fixes it? I'm using my personal machine over the Internet to try and run SOCKS proxy. It was working once, then it wasn't. I'm a total DUMMY at this terminal stuff and I have requested additional documentation for other dummies like myself here: #11172 

- Grant AWS Console access?
NO

- Please give a brief description for why you are requesting AWS access.
I don't think I need this...?

**Comment by jsev-io** [comment]
> Note that I'm a bit confused about the email address above. I guess this process fixes it? I'm using my personal machine over the Internet to try and run SOCKS proxy.

I totally thought that was an email address before too! However, it's what is known as an ssh key comment. It is automatically generated by your system when you create a new key. In this case it is a combination of your personal computer username, your computer name, and your computer name / hostname.

Here is an [article](https://coolaj86.com/articles/the-ssh-public-key-format/) with further information on SSH keys.

**Comment by jsev-io** [comment]
*Note *** Edited original user issue

**Comment by jsev-io** [comment]
@artsymartha68 Were you able to successfully connect to the proxy?

**Comment by artsymartha68** [comment]
HUZZAH!!!! That did it!!! Thank you so much!
