### ISSUE TITLE
[Discovery] Investigate Implementation of Global UX Elements for Expedited Analytics Implementation

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#1125]
## User Story
As an engineer on the VSA/VFS teams, we want to standardize naming convention and deployment of common UX elements. 

## Goal
-  Begin discovery to streamline turnaround time to implement common elements and establish a framework moving forward for Drupal and Forms library elements

## Acceptance Criteria
- [x] Analytics-Insights: Investigate components contained [here](https://design.va.gov/components) and identify gaps between what is currently within GTM and what is not
- [x] Analytics-Insights: Propose dataLayer framework for one element not currently implemented within analytics
- [ ] Engineering: Implement dataLayer framework for 1 design and 1 form library element

## Resources
- Most commonly used elements in Drupal provided by @cvalarida 
>448 wysiwyg
    384 q_a
    106 video
     97 q_a_section
     85 page
     63 collapsible_panel_item
     47 table
     39 document
     31 image
     26 process
     19 support_service
     16 alert
     13 collapsible_panel
     12 react_widget
     12 expandable_text
     11 list_of_link_teasers
      4 landing_page
      4 administration
      2 spanish_translation_summary
      2 number_callout
      1 publication_listing
      1 office
      1 event_listing
- Commonly asked Forms Library components:

  -  Sending of custom dimensions with form submission
  -  Clicks on helper text
  -  Bank or Personal info saved
  -  Accordion on Review & Submit step

- Related tickets on former vets.gov-team repo:

  -  [Baking Form Components](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16681)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@ncksllvn @tlei123 Thanks for conversation earlier this week. Regarding the forms library, we've identified that forms that save personal or bank account information could be a common component to track across products.

#### Context 
- These requirements were originally made to the BAH team in [#16872](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16872) for VET TEC 22-0994 as a one-off request.
- Requirements we provided for 22-0994 were:
  - Bank Account: `dataLayer.push({'event': 'edu-0994-bank-account-saved'});`
  - Personal Information Saved: `dataLayer.push({'event': 'edu-0994-personal-information-saved'});`

### Suggested Implementation
- At point of bank or personal information saves in the form or upon the Review & Submit step, can these events be disabled-by-default and then enabled by a VSA/VFS engineer? 

(![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/bf777f98-6b47-417a-b4d9-8813d7b37a88)

- Using 22-0994 as precedent, can the convention be used like so:

  - Bank Account Saved: `dataLayer.push({'event': '<product-goes-here>-bank-account-saved'});`
  - Stop Direct Deposit: `dataLayer.push({'event': '<product-goes-here>-bank-account-removed'});` 
  - Personal Information Saved: `dataLayer.push({'event': '<product-goes-here>-personal-information-saved'});`

**Comment by aeltarhoni** [comment]
@Karak888 will look into this

**Comment by nedierecel** [comment]
@joanneesteban @jonwehausen For visibility, I rewrote the acceptance criteria to set the expectation that we wanted to identify 1 component for unauthenticated and 1 component within tools to streamline.

**Comment by nedierecel** [comment]
@Karak888 Hello! Bumping this request to see if someone can help look into the Profile Direct Deposit forms that are embedded within tools (not at the Profile level, which the VSA Auth team is already implementing)?

**Comment by joanneesteban** [comment]
Deprioritizing for Sprint 10. Bumping to Ready.

**Comment by jonwehausen** [comment]
Closing per standardization effort
