### ISSUE TITLE
[BUG] 686c - Frontend Route Gating

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#11266]
## Description
Currently if a user is logged in, they are able to navigate to the 686 options selection by typing it directly into the URL. This circumnavigates the VA File Number check mechanism designed to prevent invalid users from filling out the form. 

## Consideration
- Depending on findings, we may want to move the VA File number check higher one level from the intro page to that app container.

## Steps to reproduce
1. Login with a test user on staging.
1. Navigate to https://staging.va.gov/view-change-dependents/add-remove-form-686c/686-options-selection

## Expected behaviour
1. A user who has not gone through VA File Number check should be redirected to the introduction page. 

## Possible solutions/Tasks
- [ ] Add additional gating logic that prevents direct URL navigation to the options selection page. 

## Acceptance Criteria
- [x] Route gating has been added (bypass is no longer possible)
- [x] PR has been submitted and merged

**Comment by micahchiang** [comment]
Have a pr out for this, but leaving this ticket open until we can verify on staging that the fix works.

**Comment by jason-gcio** [comment]
I could not get around the VA file check with user 5 - ok to close?
