### ISSUE TITLE
Project Kickoff [Vet Center] (WIP)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11268]
## Steps to complete Project Kickoff
- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Link to this issue once created in #vfs-platform-support in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [ ] Mandi will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough [draft of product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/feature-brief.md)
- [Andy's initial design sketch](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/design/VA-Vet-Center-template.pdf)
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Michelle Middaugh**
- DEPO Product Lead (required): **Dave Conlon**
- Entire VFS team (recommended): **Gibran Rodriguez, Michael Pelz-Sherman, Lance Sanchez, Leyda Hughes**

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** not immediately

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

**Scheduling preference: Thursday, July 30 at 1:30 ET**

**Comment by mandifrances** [comment]
Hi. Did you mean August 30th (it's a Sunday)?

**Comment by mmiddaugh** [comment]
Deferring this until after taxonomy. 
Sending back to Icebox

**Comment by mmiddaugh** [comment]
This issue was replaced by https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/12988
