### ISSUE TITLE
HAProxy metrics should provide reliable request timing information

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#11271]
## Background

@darkbushido and his team are having troubles effectively debugging intermittent request latency spikes in requests to the `/v1.0/ProviderLocator` PPMS endpoint. The challenge is determining where the bottleneck occurs. 

### Tasks

2020-07-15 @kfrz and @darkbushido met to discuss potential issues. Here are some things we can investigate:

- Define technical requirements for updating HAProxy => Prometheus exporter integration, which may have updated features including detailed request timing
- Further expand the parsing on this [Insights query](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logs-insights:queryDetail=~(end~0~start~-43200~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40message*0a*7c*20parse*20*40message*20*22*5b*2a*5d*20*2a*7e*20*2a*20*2a*20*5c*22*2a*20*2a*20*22*20as*20haproxyTimestamp*2c*20front*2c*20back*2c*20reqTiming*2c*20verb*2c*20path*0a*7c*20filter*20path*20*3d*7e*20*22*22*23*20filter*20misc.*20haproxy*20messages*20w*2fo*20requests*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20display*20back*2c*20verb*2c*20substr*28path*2c*200*2c*2064*29*20as*20pathName*2c*20reqTiming*20*23*20shorten*20for*20PII*0a*7c*20filter*20back*20*3d*7e*20*2fppms*2f*0a~isLiveTail~false~queryId~'0f70550c-6781-4b8c-8f75-cda874c3fd94~source~(~'dsva-vagov-prod*2fvar*2flog*2fhaproxy.log))) to filter request timing, so we can further pinpoint log lines/individual requests that take an above-average time to complete

### Notes

- NewRelic has historically provided the insights needed to debug this, however, NR is no longer available in the VSP stack. Datadog *may* help solve this, however, we should have a solid understanding of our internal infrastructure and request timing. 

- It maybe the HAProxy gets backed up when many requests happen in serial, which causes an upstream timeout somewhere in our infrastructure.

- The main problem here is that the VSP user (facilities team) cannot unequivocally show which segment of the request path is causing issue. 

- This presents an opportunity for our team to improve the monitoring experience on VSP. 

- Below screenshot shows some random spikes on existing request timing data. How can we determine why this is happening?

![image.png](https://images.zenhubusercontent.com/5951581361b4ca3b0a725a57/6870bdff-e2ac-49d8-929a-155027b5831e)

### Acceptance Criteria

- [ ] Facilities team has access to HAProxy metrics required for debugging PPMS calls

**Comment by drorva** [comment]
Can we please raise the priority on this, since it is blocking the Facilities team from trouble shooting their latency issue? @kfrz @johnpaulashenfelter

**Comment by kfrz** [comment]
- `fwdproxy` task for building & running the main instance and additional exporter found [here](https://github.com/department-of-veterans-affairs/devops/blob/14689445f4246e0cbc5f33cbe14763191aad84c7/ansible/build/roles/fwdproxy/tasks/main.yml)

- `haproxy` build tasks found [here](https://github.com/department-of-veterans-affairs/devops/blob/6b32b1de927cfdb6e6d6efcc55f167f8989e7ba6/ansible/build/roles/_haproxy/tasks/main.yml)

I believe we need to upgrade the infrastructure so that we're using at least version `2.0.7` of `haproxy`, which includes a bugfix for the internal `contrib/prometheus-exporter`:

[`- BUG/MINOR: contrib/prometheus-exporter: Return the time averages in seconds`](http://git.haproxy.org/?p=haproxy-2.0.git;a=blob_plain;f=CHANGELOG)

We also could eliminate (I think) the code for the `quay.io/prometheus/haproxy-exporter:v0.10.0` container, as it's since been brought into the `haproxy` repo. 

Would love some backup from @tskinn or other VSP ops engineers.

**Comment by kfrz** [comment]
Support request is made to VSP Operations team in [Slack](https://dsva.slack.com/archives/CJYRZK2HH/p1595967375369400)

**Comment by dginther** [comment]
Seems like we should just move to 2.0.16 so we are at the latest 2.0 release. Once we have compiled it with the exporter, we can easily move the scrape to that endpoint rather than scrape the exporter.

**Comment by dginther** [comment]
I think this PR covers turning in the endpoint in haproxy, and adding the proper ingress. Once we verify that the endpoint is good, and works as expected, we can switch prometheus scraping to the new endpoint and then remove the exporter.

**Comment by kfrz** [comment]
**08/03/2020** 

This issue (extended HAProxy export metrics) is resolved. Separate PR opened for removing the extra exporter container [here](https://github.com/department-of-veterans-affairs/devops/pull/7355)

**Updates on the macro issue:**

- @darkbushido and I met to examine & update the [Facilities Locator Grafana board](http://grafana.vfs.va.gov/d/000000048/facility-locator-ppms?orgId=1)
- Now shows breakdown of each segment of the HAProxy logs, indicating a slowdown in `Tr` - total response seconds.
- @darkbushido: PPMS has apparently been a problem for over a year. 
- @boris-ning-usds assisted with understanding of the greater VA network considerations and helpful tips
- Boris suggests isolating or re-creating the behavior at a known point of origin in order to have a precise traversal point for the PPMS team to debug.
- This may need a ticket opened w/ BPE Support, but no priority because... it's been a problem for a year, clearly doesn't need fixing tonight. 
- According to @darkbushido the PPMS team at Microsoft is difficult to work with. 
- @darkbushido will write a load test to re-create behavior using Apache Bench
