### ISSUE TITLE
Access for Sarah Hutchins

### ISSUE THREAD

**Issue by sarahproof** [department-of-veterans-affairs/va.gov-team#11285]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea @CourtneyBethea
- Please provide your name.
   > Sarah Hutchins
- Please Provide your email.
   > shutchin@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @department-of-veterans-affairs/thoughtworks
   > Role: Developer
   > Company: ThoughtWorks
   > I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana / Sentry so we can
   > 
   > - Modify / update Jenkins job configs
   > - Kick off Jenkins jobs
   > - Review Prometheus data, some of which is imported into the scorecard
   > - Review Grafana data for the scorecard
   > - Review logs in different environments to facilitate testing along the path to production

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzNqWqaFUR4FWe/Rx9KaIBMFmyfMyeAVMY3rrISabqHFFIG3YszJilfZeOaT7Ii2GOC29Q93mxs2TNPnQJ/3J40LxIU/fZeiLWS5XIUG9jLEjAXXySlsMuHCbwVeKTeYUydg4OzpJlphqDFpIjxapl0BMMAF0YL4QTM3cJoe2RCs7a1IHn9m71tEHLT+4OrlpWMekK+jPGT7sJGfBT7oAOZvDHbV/lEMykw6xKdQSoYixHSXEp5JMgc99kNt84EljlxmwGrOCbFHTv8empcYNcZ3XnsHsmcrYtOYSs56Nc1tYAmmaHFkZ+OWIxAfRKfLMX7DrQKU+tmjfzXw1GvMzSkexYu0XrL0w2/Wr3BHZtS0sfCK+weY9EewdyI3j23Mo03oGsXqpYgvwAj1++DHj16NxtQVTlFfob64OsDnn4UpGqZifri0fk/kbPfhDJhe6q7+dxhQmxovsXayLV8HjrU3K7zafkA5MKkwlRYII8DWllbW5u/zAIyaOXiJ/LC0k= shutchin@thoughtworks.com
```

- Grant AWS Console access?
  > YES

**Comment by ricetj** [comment]
For AWS Access
User: Sarah Hutchins
COR: Courtney Bethea
Approval needed: @Jeff-Hayter

**Comment by jbritt1** [comment]
Closing due to https://github.com/department-of-veterans-affairs/va.gov-team/issues/13489
