### ISSUE TITLE
Find a VA Form: CMS: Create auto-unchecking functionality upon publishing a form detail page node

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11283]
## CMS: Create auto-unchecking functionality upon publishing a form detail page node 

**User story 1:** As a Veteran, if I've bookmarked a form detail page, I want the URL to stay evergreen (like a permalink). 

**User story 2:** As a PW content editor, I want to be assured that when I publish a form detail page, the autogenerate URL checkbox is automatically unchecked upon publishing without additional manual action from me.

This ticket is to capture the the [decisions that came out of the 7/15 forms call. ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/status-and-decisions.md#071520) 

It is lower priority than Learning Center and Vet center facilities CMS work for Q3. 

AC:
- [ ] When a form detail page gets published, we can go back to the CMS and see that the autogenerate URL checkbox is unselected, and has not changed the original autogenerated URL.

**Comment by MarciMcGuireGCIO** [comment]
Priority note:  We need to better understand the ask here

**Comment by jenniferlee-dsva** [comment]
This feature has already been implemented by the CMS team, so it can be closed. :-)
