### ISSUE TITLE
IA Request: Apply for the Rogers STEM Scholarship, 22-10203

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#11284]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/10203_product_outline.md)
- Link to or attach prototype or mockups
  - [Prototype showing ineligibility due too much remaining entitlement](https://bahdigital.invisionapp.com/share/DTIAECACEWF#/screens/296042333)
  - [Prototype showing ineligibility due to no Ch33 benefit](https://bahdigital.invisionapp.com/share/GUIAECBJB5C#/screens/296043462)
  - [Prototype showing ineligibility due to non-STEM program](https://bahdigital.invisionapp.com/share/ZQIAECCSG5D#/screens)

- Link to research readout/results 
  - [Round 1 Testing: Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/research/22-10203-RogersSTEMScholarship-TestingReadout-20200611.pdf)
  - Round 2 Testing: (Readout in progress)

- Link to [research history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable

- [Link to content doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** (if more than one page)
- Provide link or image of proposed page structure

**Suggested URL(s)**
- Provide suggested URLs and any background or rationale

**Suggested entry points**
- What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [x] Requesting team closes issue upon implementation
- [x] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
Draft IA write-up is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bah-stem-app.md

Reviewing with various individuals to finalize, will let you know when it is final.  Happy to talk through this as well.

**Comment by amyknox** [comment]
Thanks @mnorthuis - this will get us started.  A couple Q's for you
* on the application breadcrumb, is using the full name of the application a new style? I believe it was just "Apply" on previous applications we've done. 
* For mobile, we're thinking the breadcrumb would be [Home]() > [Education and training]()

Caught 2 typos in the 
Product/**Featue**: STEM **Scholoarship** Application
Product/Feature: STEM Scholarship Application

**Comment by mnorthuis** [comment]
Thank you for catching the typos, that's why it still needs another look! :-)  I'm going to review this again with fresh eyes yet. 

For the application breadcrumb, yes, the full name would be the breadcrumb.  None of the education applications have been updated with breadcrumbs and URLs since the WBC effort.  If you look at Disability, you'll see it in action: https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction

For mobile, the breadcrumb only shows the previous page so users can click back up the hierarchy - this should be standard functionality.  So while on the application the breadcrumb would show "< Edith Nourse STEM Scholarship".   Clicking back one by one would walk the user back up, so the progression would be:
< Edith Nourse STEM Scholarship
< Other VA education benefits
< Education and training 
< Home

**Comment by amyknox** [comment]
Gotcha. Thanks!

**Comment by amyknox** [comment]
@mnorthuis - How "firm" is the the new STEM scholarship URL (wwww.va.gov/education/other-va-education-benefits/stem-scholarship)?  If you're solid with that, we can get the breadcrumbs set up.

**Comment by mnorthuis** [comment]
@amyknox URLs and breadcrumbs should be pretty solid, just want to review them with writers next week, but I think you are pretty safe to move forward.

**Comment by amyknox** [comment]
@mnorthuis - Question... our "limited production roll-out" is scheduled for Aug 19.  Since the content page will still be in the works at that time, we were thinking about how we'd approach implementing the breadcrumb for that page. 

Couple ideas... 
a) use the new breadcrumbs but not link the content page 
b) use the "real" breadcrumbs that show the content page on benefits.va.gov for soft-launch and then go back and switch it when the content page is ready
c) don't implement any breadcrumbs until the content page is ready, then use the new ones. 

cc: @dneel-bah

**Comment by mnorthuis** [comment]
@amyknox What will be the primary way that users will get to the application?  Just through the wizard on the How to apply page or through other communication/direct link efforts?

**Comment by amyknox** [comment]
@mnorthuis - you know, I'm not sure.  Analytics indicate users are getting to the current form via search engine (google, bing, yahoo), direct navigation, search.usa.gov.  A lot of the users are getting to the form via the "change benefits" page which will be irrelevant to STEM applicants. I'm not sure the promotion VA is doing on benefits.va.gov is driving a lot of traffic but we're still primarily dealing with toooooo many applicants so it's hard (for me) to know.  Once the stand-alone form is in place and we don't have a lot of opportunistic applicants, there may need to be a more centralized, strategic communications plan. 

If we go with "mismatched" breadcrumbs, we're talking about a week or 2 until the content page is deployed & they match up again.  However, our PoP goes all the way through 9/19 so we have some time in case the content page needs an extra day or 2.

**Comment by mnorthuis** [comment]
I would prefer not to have a breadcrumb that goes between the 2 experiences.  I'm thinking we could mimic the breadcrumb that is on the current 1995 application so users can get back to the How to apply page - my guess is that that they will either direct link to the new application or they will come from the wizard on the How to apply page, so this provides them a way to get back.   

**Home >  Education and training >   How to apply  >  Apply for the Edith Nourse STEM Scholarship**

The content on the introduction page of the application can provide a link to the legacy content page if needed. And the legacy content page should for sure have a link directly to the application.  

Once the static content page launches, the breadcrumb should be updated to reflect the correct path.

**Comment by amyknox** [comment]
Thanks @mnorthuis.  I think we can do this.  I'll let you know tomorrow if we have any questions.  I srsly hope not. :)

I believe the content on the intro page is more helpful than the legacy page and the legacy page actually does have a link to the application... it's just not that easy to find.

**Comment by mnorthuis** [comment]
Sounds good.  
If its not possible or difficult to customize the breadcrumb, then I would opt to either hide it or hide a portion of it: 

Option 1: Home > Education and training > How to apply > Apply for the Edith Nourse STEM Scholarship
Option 2: Home > Education and training 
Option 3: No breadcrumb

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - You may already be aware but just making sure... 
RE:
> ... or they will come from the wizard on the How to apply page, 

The Education wizards are actually being moved from the "How to" pages to the actual application tool landing page. I don't know the ETA of when that will go live, so depending on timing, this might be relevant or not (yet!).  For ETA, Matt Self or John Hashimoto would have info..

**Comment by mnorthuis** [comment]
@jenniferlee-dsva Yes, I am aware and we have discussed.  Not sure it will be implemented in time for the initial launch of the STEM application, but we will adjust if it does happen.

**Comment by dneel-bah** [comment]
@mnorthuis Just to confirm, until the new static content page is ready, we want to do this:

Option 1: 
Home (https://staging.va.gov/)
> Education and training (https://staging.va.gov/education/)
> How to apply (https://staging.va.gov/education/how-to-apply/)
> Apply for the Edith Nourse STEM Scholarship (read-only on page: https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction)

**Comment by mnorthuis** [comment]
Yes, that is interim breadcrumb until the static page is complete.  
However, that is not the accurate URL for the application.  Draft URL is documented in the IA write-up.  I am meeting with Danielle tomorrow to finalize content strategy and will finalize URLs with that.

**Comment by dneel-bah** [comment]
@mnorthuis Thanks for the clarification.  For the URL, I assume you mean this (https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction) is still being finalized.

I also just noticed that the last part of the breadcrumb lost the word "Rogers" along the way, so it should actually be "Apply for the Edith Nourse Rogers STEM Scholarship".  Unless that's too long

**Comment by mnorthuis** [comment]
@amyknox Reviewed the IA along with the content strategy work with Danielle today and finalized info in the IA write-up.  

FYI, I did tweak the URL for the form a bit - removed "stem" from the the final slug to shorten it a bit.  It breaks convention for form/application URLs, but this one is lengthy and structure slightly different.  

The write-up does not reference the interim breadcrumb discussed above.  Please let me know if you have any questions on any of the information. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bah-stem-app.md

**Comment by amyknox** [comment]
@mnorthuis - thanks for sharing this.  Looks mostly good. As @dneel-bah mentioned, "Rogers" is missing from the scholarship name in the breadcrumbs for both the content page and the application.  

- Content: Home > Education and training > Other VA education benefits > Edith Nourse **Rogers** STEM Scholarship
- 
- Application: Home > Education and training > Other VA education benefits > Edith Nourse **Rogers** STEM Scholarship > Apply for the Edith Nourse STEM Scholarship.    

If you need to shorten those, when we've used a shortened version of the scholarship name, we've gone with "Rogers STEM Scholarship" per the Education Service team.

**Comment by mnorthuis** [comment]
@amyknox @dneel-bah I'm so sorry, I totally missed that feedback!  I updated the breadcrumbs to include "Rogers" in the static page segment, but used the shortened name on the Apply page (just Rogers) to reduce the repetition.   Please let me know if there are any requirements to include the name in the URL, I know that can be an issue in some cases, but hoping we can leave the URL brief for this.   I updated the IA page with the breadcrumbs below. 

- Content: Home > Education and training > Other VA education benefits > Edith Nourse Rogers STEM Scholarship
- Application: Home > Education and training > Other VA education benefits > Edith Nourse Rogers STEM Scholarship > Apply for the Rogers STEM Scholarship

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bah-stem-app.md

**Comment by amyknox** [comment]
@mnorthuis 

I think we're just about there!  We're solid with the plan that we will implement the interim breadcrumbs now and the final breadcrumbs when the content page launches.  

Curious about who's handling the balance of updates specified in the bah-stem-app.md.  Is that work you're anticipating we'll do or is that assigned out to another team?

**Comment by mnorthuis** [comment]
@amyknox very valid and good question, its a combo of BAH and Public Websites.  BAH is directly responsible for all the the URLs and breadcrumbs on the application that you are building .  Public Websites would be responsible for implementing the static content page and corresponding redirect, and the entry points/links recommended.   That said, BAH is responsible for the overall experience of the launch of this new application, so would be the ones taking the lead on communication and ensuring all pieces are coordinated/completed at launch.     

Happy to have a regroup with you and Public Websites to talk through the different items, or any follow up discussions needed.

**Comment by amyknox** [comment]
@mnorthuis - do you know where the PDF of approved STEM programs will end up living when the new page is launched? It's currently here:  https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf

**Comment by mnorthuis** [comment]
It depends on how the Public Websites team decides to handle the PDF.  Some PDFs are converted to web pages and migrated over, other PDFs remain and continue to be  hosted by the business line.  I'll make sure this is on the PW team radar when they work on that page.

**Comment by mnorthuis** [comment]
@amyknox Looks like that PDF is not planned to move, should remain exactly where it is for now.  Let me know if you have any concerns about that.

**Comment by mnorthuis** [comment]
@amyknox Just a gentle reminder now that that static page has been launched, the breadcrumb on the actual STEM form will need to be updated to reflect the correct IA per the conversations above.  Thank you!

**Comment by dneel-bah** [comment]
@mnorthuis We will begin working on that update as soon as tomorrow, but no later than Monday.

**Comment by dneel-bah** [comment]
@mnorthuis We are currently working this update, and noticed the links are slightly different than discussed.  We are implementing as shown below.  Let me know if anything is incorrect.

Thanks,

The breadcrumb for the 10203 form is: **Home > Education and training > Other VA education benefits > Edith Nourse Rogers STEM Scholarship > Apply for the Rogers STEM Scholarship**
    a. Home link: [https://[environment].va.gov/](https://staging.va.gov/)
    b. Education and training link: [https://[environment].va.gov/education/](https://staging.va.gov/education/)
    c. Other VA education benefits link: [https://[environment].va.gov/education/other-va-education-benefits/](https://staging.va.gov/education/other-va-education-benefits/)
    d. Edith Nourse STEM Scholarship link: [https://[environment].va.gov/education/other-va-education-benefits/stem-scholarship/](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/)
    e. Apply for the Rogers STEM Scholarship: Read only and displayed when the user is on this page: [https://[environment].va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction)

**Comment by mnorthuis** [comment]
Hi @dneel-bah, those labels and links look correct to me, which one is different than previously discussed?

**Comment by mnorthuis** [comment]
Ah, yeah those are not quite correct.  Correct ones are listed up above in this issue and in the linked IA documentation.   Thank you for checking!

**Comment by mnorthuis** [comment]
Work is launched.  Closing issue.
