### ISSUE TITLE
entityUrl differences

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11288]
## Issue Description
The GraphQL query and the CMS export produce different `entityUrl`s for some entities. We need to figure out what the cause of this is.

## Example entity
**UUID:** 00f8a6a5-37a6-478c-b5d0-4eaa87b5bdd1
**Entity ID:** 221

### CMS export
**Breadcrumbs:**
```json
[
  {
    "url": {
      "path": "/",
      "routed": true
    },
    "text": "Home"
  }
]
```
<details>
<summary>Screenshots of the data to show it's the same entity as below</summary>

![image](https://user-images.githubusercontent.com/12970166/87594687-2ff7ec00-c6a2-11ea-8dec-afbb9fb1ebd5.png)
...lots of stuff in between...
![image](https://user-images.githubusercontent.com/12970166/87594739-4605ac80-c6a2-11ea-8dac-705b0e59391f.png)
</details>

### GraphQL result
**Breadcrumbs:**
```json
[
  {
    "url": {
      "path": "/",
      "routed": true
    },
    "text": "Home"
  },
  {
    "url": {
      "path": "/pittsburgh-health-care",
      "routed": true
    },
    "text": "VA Pittsburgh health care"
  }
]

```
<details>
<summary>Screenshot of the data to show it's the same as above</summary>

![image](https://user-images.githubusercontent.com/12970166/87594537-f6bf7c00-c6a1-11ea-9ae8-ebfd605f90ff.png)
</details>

**Comment by swirtSJW** [comment]
I think this may be related to another configuration issue that Kev discovered department-of-veterans-affairs/va.gov-cms#2336

**Comment by swirtSJW** [comment]
Unfortunately the misconfiguration issue in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2336 .

Still digging.

**Comment by swirtSJW** [comment]
Interesting.   I just saved node/221   and then looked at the export file

node.00f8a6a5-37a6-478c-b5d0-4eaa87b5bdd1.json

and I see 
```
"entityUrl": {
        "breadcrumb": [
            {
                "url": {
                    "path": "\/",
                    "routed": true
                },
                "text": "Home"
            },
            {
                "url": {
                    "path": "\/node",
                    "routed": true
                },
                "text": "Node"
            },
            {
                "url": {
                    "path": "\/pittsburgh-health-care\/medical-records-office",
                    "routed": true
                },
                "text": "Medical records office BOOGA"
            }
        ],
        "path": "\/pittsburgh-health-care\/medical-records-office"
    }
```
Note: 'BOOGA' was my change as part of the save.


The saving is working.  I suspect that something about running the bulk export for some reason did not update it.   Checking on that theory next.

**Comment by swirtSJW** [comment]
I confirmed that the file does not have it on prod.
![image](https://user-images.githubusercontent.com/5752113/87835038-084b8400-c85a-11ea-8450-17ef3eec7f53.png)

So it seems like actual node save is working and the batch process is failing.
@indytechcook  To debug this, it might be helpful to know the date of that this file was updated on prod node.00f8a6a5-37a6-478c-b5d0-4eaa87b5bdd1.json

That might tell us whether it was not updated when you ruan the bullk export, or that it was updated but the update makes it not get the breadcrumb

**Comment by indytechcook** [comment]
PR to fix the breadcrumbs:  https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2358

**Comment by indytechcook** [comment]
Follow up PR to address more issues with breadcrumbs: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2373

**Comment by cvalarida** [comment]
Confirmed that the node I listed in the example has the right breadcrumbs now. I'm gonna assume they all do unless we run into something that tells me otherwise.

Thanks for tackling this, @swirtSJW @indytechcook ! :raised_hands:
