### ISSUE TITLE
[Bug] Profile 2.0: LOA1 profile showing "Personal and contact information" and "Connected apps" in side nav

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#11291]
## To replicate

1. Sign into staging with a LOA1 user.
2. Go to the profile.
3. You will see that **Personal and contact information** and **Connected apps** show up in the side nav. However, they are not clickable and don't go anywhere.

![Screen Shot 2020-07-15 at 5.39.28 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/2932cc12-db22-4318-b20c-5a6bc58f618f)

## Bug fix acceptance criteria

- [ ] **Personal and contact information** and **Connected apps** should not show up in the side nav for LOA1 users.

**Comment by erikphansen** [comment]
@Samara-Strauss this should be fixed on staging.
