### ISSUE TITLE
Sign-in page should enforce LOA3 before redirecting users to Cerner

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#11292]
Issue reported:
> Patrick/Alexis – it looks like if someone starts at MyVA Health (Cerner Patient Portal) and selects to create a new ID.me account VA.gov/sign-in sends the SAML AuthN request with AuthNClassContextRef=http://idmanagement.gov/ns/assurance/loa/1/vets.

> For this reason the user only creates an ID.me LOA1 account and then is returned back to VA.gov via IAM SSOe.  VA.gov/sign-in then redirects the user to Cerner to trigger the AuthN request to SSOe, SSOe before sending SAML response to Cerner has to redirect the user to sign-up service.  This throws an error as the /MAP junction

We typically test with LOA3 accounts but there's nothing enforcing that in the sign-in page application. Sign-in page need check if the user profile is `verified` and if not, trigger a `verify` request before redirecting back to Cerner.

In principle, we might want it configurable whether we do that for specific applications or not - if some applications might accept LOA1 users. In practice, I think most other sites at VA are requiring LOA3 so we can probably implement that later if needed.

**Comment by patrickvinograd** [comment]
The way we've implemented redirects is not super conducive here, because we set the RETURN_URL and then count on the AuthApp to send the user back to the originating application. So control doesn't go back through the sign-in page application in order to do this per-application validation there. 

We could make it so control does go back through the sign-in page (e.g. to a sub-route that checks validation or we could somehow pass a parameter to AuthApp that enforces the LOA3 requirement before redirecting. 

I guess one UX question is whether we are going to tell the user that we are sending them through identity proofing and why, or if we are just dumping them straight into the verification flow.

**Comment by hinzed1127** [comment]
>I guess one UX question is whether we are going to tell the user that we are sending them through identity proofing and why, or if we are just dumping them straight into the verification flow.

Yeah, I've got it preliminarily just routing to the site-wide verify page, which is very bare-bones. Alternatively, we could do something like the health benefits app, which has more specific language for unverified users on its intro page, and then the "Verify your Identity" button simply leads to the site-wide page. E.g.:

![Screen Shot 2020-07-30 at 11.59.45 AM.png](https://images.zenhubusercontent.com/5ca254d7e268082e7bd49749/74e902bd-987a-47f9-9ddc-df9ea186d97e)

_Click button and you get routed to:_

![Screen Shot 2020-07-30 at 12.01.22 PM.png](https://images.zenhubusercontent.com/5ca254d7e268082e7bd49749/7319459a-2602-4871-8f07-6947b2e798d5)
