### ISSUE TITLE
[Support] GTM Implementation on oprm.va.gov

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#113]
@rroueche commented on [Tue Apr 30 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18300)

## Story or Description
As a content producer, I need Google Analytics visibility into the performance of the new Privacy Policy page and performance on the OPRM subdomain https://www.oprm.va.gov/privacy/

a) The subdomain https://www.oprm.va.gov/privacy/ does not utilize the main VA.gov Google Analytics account.

b) Currently, the Privacy Policy page generates extra pageviews for each link interaction on the "On this Page". The scope of this issue will be covered in a separate task. 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/76923066-210c-4198-942a-115719035766) 

## Def of Done
- [ ] Concrete task that needs to be completed (e.g., Updated error message for error code 001)
- [ ] Testing complete if needed (local, staging, prod)
- [ ] Important info documented in GitHub

---

@rroueche commented on [Tue Apr 30 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18300#issuecomment-488099302)

@bethpotts could you please coordinate w/the team to fill out the issue details above? thank you!

---

@bethpotts commented on [Tue Apr 30 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18300#issuecomment-488125985)

@rroueche Mikki thinks Nedie may already have this covered. Are you checking with Nedie? If Mikki is correct, we can close this issue.

From slack:

Mikki Northuis   [1 hour ago]
I believe what needs to be done is already tracked here: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18158

Rachael Roueche   [1 hour ago]
wait the superfooter analytics ask and the privacy policy analytics ask are really the same ask? (edited)

Mikki Northuis   [44 minutes ago]
I believe so, because there's no tracking events in the footer at all, but you can clarify with Nedie (edited)

Rachael Roueche   [44 minutes ago]
aha. ok thanks!

---

@nedierecel commented on [Tue May 28 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18300#issuecomment-496597904)

Reassigning this task to me. The Superfooter task in #18158 has been completed, but I am adding 2 other items here:

1. Placing Google Tag Manager on oprm.va.gov. On 4/24, this email was sent to Josh Tuscher to request Google Tag Manager on the subdomain. I do not see it has been added yet:

>Hello Josh:

>Thanks for your help today. 

>Option A (Preferred) - I am attaching two text files, with one set for production and another for dev/staging environments. This allows analytics to publish changes to each environment as we validate changes. You’ll find a snippet for the <head> and <body> within each file. 

>Option B - If it’s not possible for the lower environments to have distinct code, you can use the Production code. We have mechanisms in place to filter test vs. production data, but Option A allows us to deploy analytics changes more methodically.  

>Best,
>Nedie

2. Each interaction with the links in the "On this page" is generating an extra pageview for each click on the hashed link. 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/92880e1e-5eba-4b3b-9a07-afe7ee429a45)

I will help evaluate if we should count these as interactions as distinct pageviews or as navigation events.

**Comment by nedierecel** [comment]
GTM has been implemented, but it is a different container ID that does not belong to our GA/GTM 360 account.

**Comment by nedierecel** [comment]
Follow-up on 7/10/2019 - Requested more information on the creation of the GTM container that is used on the subdomain.
