### ISSUE TITLE
CT-Filter: Update Search Results page with new filters

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11306]
## Value Statement
As someone using the Comparison Tool, I want to be able to filter search results on more specific criteria so that I can more quickly find the institution I am looking for. 

## Assumptions
1. This work should be behind a feature flag: #11344

## Acceptance Criteria
1. On the Search Results page, the left panel has been updated as follows:  
   a. The "Keywords" heading is changed to "Refine Search"
   b. The "City, School, Employer" label is changed to "Enter a school, location, or employer name"
   c. "Country" and "State" dropdowns have been moved below the "Enter a school, location, or employer name" text search field
   d. The "Warnings and school closings" control (label and checkbox) remains unchanged
   e. The "Institution Details" section has been moved below the "Warnings and school closings" control 
   f. The "Type of institution" label (for radio button elements) is changed to "Select an institution type"
   g. The "Institution type" dropdown label is changed to "Institution categories" and the control (label and dropdown element) has been moved below the newly named "Select an institution type" control and above the "Programs" control (label and checkboxes)
   h. The "Programs" control is unchanged
   i. "Gender" control (label and radio buttons) have been added below Programs and the values include any, women only, men only. 
   j. "Specialized Mission" label with corresponding Historically Black Colleges and Universities (HBCU) label and checkbox have been added
   k. "Religious affiliation" label and corresponding dropdown have been added and the dropdown values are available in SA1. 
   l. "Your benefits" section heading has been changed to "Your military details" and the section can be collapsed or expanded
   m. "Your housing allowance" section heading has been added above "How do you want to take classes" and the section can be collapsed or expanded

2. The search results cards for institutions have been updated to include tags that represent the following categories when applicable: 
   a. Gender: Women Only, Men Only
   a. Specialized Mission: HBCU
   a. Religious Affiliation: See SA1 for values

3. Tags are for display purposes only and are not interactive

4. Tags are displayed in the following order: 
   a. Gender
   b. Religious Affiliation
   c. HBCU

6. The following colors are utilized for the tags:
   a. Text: 323A45
   b. Background: FFFFFF

5. In the left navigation, all "Learn more" elements move with their respective controls

## Supporting Artifacts 
1. Religious Affiliation list of labels/dropdown: [ReligiousAffiliations_CollegeScorecard.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4939562/ReligiousAffiliations_CollegeScorecard.docx)
   a. For values of "-1 Not reported" and "-2 Not applicable" no tags will be displayed
   b. For values of "99 Other (none of the above)", display the tag "Other religious affiliation"
   c. For values of 77 & 79 (Protestant, Not specified) and (Other Protestant), display the tag "Protestant"
2. Prototype: https://bahdigital.invisionapp.com/share/QNIAEHO8BH2
3. Content doc: [TBD on 06/20]

**Comment by sonntag-adam** [comment]
vets-website PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/13629

GIDS PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/gibct-data-service/692

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-31 at 11.52.29 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9e6cf1ad-c19a-4dcb-866b-919282ee22bc)
##
![Screen Shot 2020-07-31 at 12.03.51 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2a802e0c-13a8-4ad0-b64a-3b699f9ab425)
##
![Screen Shot 2020-07-31 at 12.04.16 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/13e1d2f8-bcd9-40c9-b774-ac1377e5ee1b)
##
![Screen Shot 2020-07-31 at 12.06.31 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/40035492-a8b1-46d9-94d4-26cdaaa4fd59)
##
![Screen Shot 2020-07-31 at 12.08.33 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bea3a38b-71fb-4762-9055-1165ae13b250)
##
![Screen Shot 2020-07-31 at 12.09.10 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6cee79b1-041e-46b1-9e32-1dac9bacfc0b)
##
![Screen Shot 2020-07-31 at 12.15.18 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/69f0c016-3586-42d4-8fa5-aa62c618a99f)
##
![Screen Shot 2020-07-31 at 12.18.21 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e31fafd2-9e30-4d02-8a14-1f778bdcb3bb)
##
![Screen Shot 2020-07-31 at 12.22.41 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cebca4cb-1924-4e0f-ad91-fa05ff2e964e)
##
![Screen Shot 2020-07-31 at 12.47.53 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a2af71aa-dca2-48e6-9e13-ead345fb6d57)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-31 at 12.55.42 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2b21dab0-27f5-4e94-97e0-41f34e781a19)
##
![Screen Shot 2020-07-31 at 12.56.00 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/09fcd83a-78c3-41e8-bc34-10c74143b665)
##
![Screen Shot 2020-07-31 at 12.56.05 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/81d6a8f2-f108-48d1-8331-8204c3b273b1)
##
![Screen Shot 2020-07-31 at 12.56.11 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/19e10130-4c1b-4fa5-8639-8822ad460752)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/10176&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by JenLJ** [comment]
@sonntag-adam UX has taken a look and this looks good!

**Comment by sonntag-adam** [comment]
Closing story.
