### ISSUE TITLE
reverseField* queries missing from CMS export

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11312]
## Background
In the GraphQL query, there are 18 `reverseField*` queries to create new properties on entities.
![image](https://user-images.githubusercontent.com/12970166/87694386-ff1bc380-c742-11ea-802c-a3b15c385499.png)
These queries are necessary when the parent entity doesn't know what child entities it has. For example, the `event_listing` doesn't know what `event`s are associated with it, but each individual `event` knows what `event_listing` it belongs to. The `reverseFieldListingNode` in that case queries for all the `event`s that belong to the `event_listing` and create a new `pastEvents` field on the entity.

## Problem
We don't have any indication in the CMS export when an entity should have these added fields.

### Add the fields to the CMS export
The CMS export could contain the necessary fields. Using our above example, it would add the `pastEvents` field into the `event_listing`'s export data. This would make transformation trivial.

I personally prefer this approach since when a child entity is added or removed, it already has a "link" to the parent entity that needs changed. Once the system is in place, the time complexity of this solution is very small. O(1), maybe. (I don't really know how to measure that for DB lookups.)

### Determine relationships during transformation
We have all the data available in the CMS export, even if it's not clear. We could set up a system whereby we establish relationships between entities that weren't immediately clear.

I personally would shy away from this approach because of both the time and cognitive complexity it introduces.
- How do we specify whether an entity should have these "extra" fields?
- How do we determine which entities should be associated with it?
- How do we find those entities?
  - I expect this is ~O(n^2) for establishing entity relationships (though Big O is pretty pessimistic in this case, admittedly)
  - Alternatively, we modify the transformation system to store entities in a hash map, keyed by the UUID for fast lookup, but while this reduces time complexity significantly, it adds a lot of cognitive complexity (and potentially increased memory consumption) to the system

---
## Tasks
- [ ] Determine how we're going to establish these entity relationships on the parent entities in the CMS export where we are currently using `reverseField*` queries in the GraphQL

**Comment by swirtSJW** [comment]
I think this may be related to another configuration issue that Kev discovered  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2336

**Comment by swirtSJW** [comment]
Possible solutions:
1.  On tar event, we export Drupal View list data to files in the content export that could be used to assemble the pages that have lists.
   - Pro:  Data could be managed by Drupal Views.  
   - Pro: This would be timely at the time of request.
   - Pro:  This is similar to the queries that GraphQL queries that are referenced in the screenshot
   - Con:  This would slow down the export as it has a lot of data to collect and save.

2.  Output the list data directly into the node for the listing items. to be output on the page as a json object in the html
     - Pro Data would be read from the page by react so it could be smarter about what is future and past
     - Con:  This would slow down the export as it has a lot of data to collect and save.

3. Output list of nodes objects and key them by the relationship so the file could be used to lookup the list items for generating the list.
    - Pro:  faster on the tar operation
    - Con potentially slower on the FE build operation.

4.  Provide all list items to lighthouse OR a json endpoint/file content file that would  and turn all  lists into react widgets so that they can be smarter about timely issues and provide enhancements for sorting and such.
   - pro : Our data for press releases, events ... ought to be available via a public API
   - pro:   Future and past events would not look all goofy when it shows an event that happened last night as not being in the past, until a content release happens.  (less of an issue if we get to content releases every X minutes).
   - pro:  This is the right way to do it for the end user.
   - con:  Means a large shift in all related front end templates. 

5.   Reverse process them and keep state during the FE build.
       - pro:  No changes need to export
       - con:  Lots of processing needed during Transform

**Comment by drorva** [comment]
#3 sounds like the best solution.
* doesn't slow down the export
* Slow down should be minimal as long as we have the **nid** of the nodes

Issues with other solutions:
1, 2 would slow export.
4 violates our rules that static pages don't use the API
5.6 are not scalable. As the number of nodes increase, this could slow the build to levels that are unacceptable.

**Comment by swirtSJW** [comment]
@drorva I'll have no objection to #3 however, it is very Transformer centric, while $4 is more useful and more adaptable.

> 4 violates our rules that static pages don't use the API

To clarify, #4 A page that uses lists events, should probably not be static, as those are changing.   Opening events up to an API actually aligns with the broader mission of providing open data for others to consume.  

The JSON does not have to be pushed to lighthouse api.  It could be pushed to a JSON file that exists publicly as a "static" page.   
During the content release, just build a page at  /data/events.json   or /data/press_releases.json.   
The advantages are:
  * Others could consume it (open data)
  * FE content builds could consume it for static page generation
  * FE react widgets could consume it for more user friendly displays like current and past events.

CC: @ElijahLynn @jefflbrauer  @cmaeng @indytechcook @ethanteague @kevwalsh

**Comment by drorva** [comment]
I see how this is a borderline case.
I guess the two questions that come to mind:
* Do these events reside in Drupal? If so, I'm not quite clear how they're fundamentally different from other content, other than that they change more often.
* Do they contain any HTML?

**Comment by swirtSJW** [comment]
They do reside in drupal and they do  contain html   They are different largely only in that they are date sensitive.  (think event calendar)

**Comment by drorva** [comment]
In that case, I'd really not go this route. We should handle them as we do other nodes.

**Comment by swirtSJW** [comment]
I have the following output being added to any of the list content types.   These are the nodes for any node that should appear on that list.   In this case events for the pittsburgh event list.

Node ID : UUI 
```
"reverse_field_list": {
        "369": "e700d2e9-bb8f-4098-b5ca-90485ba11c78",
        "370": "7bb3b8f2-0641-4a63-a96c-93df7ac5874f",
        "371": "7984d817-8e43-4a51-9de2-a45a929f77cd",
        "372": "05056017-e2b7-4254-942a-f26e04ad64d8",
        "373": "5fad5405-4a8f-473b-aac4-232f5494821b",
        "374": "fd6c00cf-3943-4574-a12c-db362a2d199f",
    }
```

**Comment by swirtSJW** [comment]
The PR for this is in QA  right now https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2418   Will likely go out with tomorrows CMS deployment and will need a full export to be run.

**Comment by swirtSJW** [comment]
The end result of this is that any node that serves as a list of other nodes will have a pseudo field in the content export  that looks like this
```
"reverse_field_list": {
        "369": "e700d2e9-bb8f-4098-b5ca-90485ba11c78",
        "370": "7bb3b8f2-0641-4a63-a96c-93df7ac5874f",
        "371": "7984d817-8e43-4a51-9de2-a45a929f77cd",
        "372": "05056017-e2b7-4254-942a-f26e04ad64d8",
        "373": "5fad5405-4a8f-473b-aac4-232f5494821b",
        "374": "fd6c00cf-3943-4574-a12c-db362a2d199f",
    }

```

Files of these list items can then be loaded by the UUID and their data extracted.

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2418 has been merged and will go out with today's cms deployment.

**Comment by cvalarida** [comment]
@swirtSJW wrote up a couple more tickets to capture most of the remaining work:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2528
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2529

From there, we'll need to determine whether it makes more sense to create the individual fields unique to the bundles that use these on the Drupal side or the transformer side. (For example, the `allPressReleaseTeasers` field on the `node-health_care_region_page` bundle is created in GraphQL by the `reverseFieldOfficeNode()` sub-query. Should this field be added to the CMS export for all those entities, or should the `node-health_care_region_page` transformer iterate through the `reverse_field_office` and create that field at that point?)

I'm leaving this ticket open to track the remaining work on our ZenHub board since those tickets Steve wrote up are in the CMS repo.
