### ISSUE TITLE
Add language about trying to accommodate preferred CC provider

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11316]
We need to indicate to Veteran that we will make every effort to schedule with your preferred provider, if not we will try and find another provider close to your home address to schedule your appointment (or something to that effect) 

Consider adding this on the following pages:
- Community Care preferences page
![Screen Shot 2020-07-16 at 1.15.46 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/5defc936-97ec-410a-aa7a-fdc253673430)

- Review your appointment details page and/or actual CC request card
![Screen Shot 2020-07-16 at 1.16.25 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/03c2aacb-2ec1-4cf5-a5ef-9af5f3034e2f)

**Comment by lenaecb** [comment]
@rtwell @peggygannon - need your assistance on:
- where you think this point needs to get made (see my suggested pages in the issue)
- what we want the final copy to be (see intent of message in issue)

**Comment by rtwell** [comment]
here's my recommendation:
![image](https://user-images.githubusercontent.com/12564977/87714173-62284d00-c779-11ea-8f52-2c175d470a8b.png)

**Comment by lenaecb** [comment]
@peggygannon @rtwell - for consistency, we should probably add 'community' to the copy. So the message reads: "VA will make every effort to schedule with your preferred _community_ provider, if not we will try and find another _community_ provider close to your home address to schedule your appointment"

CC team made a fair point that just saying 'provider' can lead the Veteran to think it's their VA provider.

**Comment by peggygannon** [comment]
hello,  @lenaecb @rtwell here are my content recommendations for this page. I've provided edits for whole screen, not just the new alert. 

Content updates: 
{header} Share your community care provider preferences


What’s the closest city and state to your location? 

Do you prefer your community provider to speak a certain language?

Do you have a preferred VA-approved community care provider for this {type of} appointment? 
-Yes
-No/I don’t know

Use the [VA facility locator] to find an approved community care provider. 

Labels should be sentence cased
Mailing address 1
Mailing address 2
Zip code should be Postal code

{alert}
**We’ll try to schedule your appointment with your preferred community provider**
If we aren’t able to schedule this appointment with your preferred provider, we’ll make every effort to schedule your appointment with another community provider closest to your home.
{end alert}

**Comment by lenaecb** [comment]
thanks @peggygannon 

@rtwell - just checking in on the location selection. that is not currently part of the existing page on VAOS. I think I remember this being a hold over from previous version of the page, but want to confirm that's not changed.

**Comment by rtwell** [comment]
@lenaecb i believe location selection is there when there is the rare occasion a user is registered at multiple VAMCs and we're trying to detect which VAMC CC scheduling office to route them. IIRC, most users with not see this interaction.

**Comment by jbalboni** [comment]
@lenaecb What @rtwell said is correct, that question shows up when you are registered at multiple sites that support CC. Only one of the test sites is supported for CC on staging, so test users don't see it.

**Comment by rtwell** [comment]
@peggygannon I noticed you changed "**What is the closest city & state for your appointment?**" to "**What’s the closest city and state to your location?**" — I think we're losing something here with this change. The reason we ask for appointment location is b/c the rare occasion a user is registered at multiple VAMCs and we're trying to detect which VAMC CC scheduling office to route them so that a Scheduler in New York can effectively schedule that person around that area. A user, who might physically be in Florida for the winter, may want to schedule something in advance, in New York for example, so it really is about _appointment_ location / area, not where the user's location. does that make sense?

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/88186117-c9735080-cc02-11ea-8e4f-0a8a20fd9c12.png)

**Comment by jenniemc** [comment]
Hi @rtwell , the new titles, "Mailing address 1" and "Mailing address 2" can get misinterpreted as two separate mailing addresses. Can I use "Mailing address line 1" and "Mailing address line 2" to help clarify? Thanks.

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/88389828-3d3d6680-cd85-11ea-9012-f050adf3f0ca.png)

**Comment by lenaecb** [comment]
good catch @jenniemc!

**Comment by jbalboni** [comment]
@jenniemc @rtwell @lenaecb Are the changes here just for the new alert? The labels/layout of the address fields aren't in line with the way we have the address now (which follows other forms), but I don't think the intent here is to update those?

**Comment by jbalboni** [comment]
@rtwell Question about this comment:

> so it really is about appointment location / area, not where the user's location.

I agree with that, but we also made a decision early on to hide the "Preferred city and state" field that exists in legacy and populate it with the user's residential address city or nearest VA site city. Is that still the behavior we want?

**Comment by rtwell** [comment]
I do not recall the preferred city and state. is that a data we store in VAOS or pull it from their profile?

**Comment by jbalboni** [comment]
It's a free text field that was on the legacy form, which is saved with the request in Scheduling Manager. Before we submit a request, we try to fill that field in behind the scenes with the residential city/state from VA Profile, and if we don't have that, then we use the city/state for the VistA site (which we always have).

**Comment by rtwell** [comment]
ah, yes this is jump starting my memory—didn't legacy vaos have a "preferences" section that had your phone number, email addy and this "preferred city/state"? or am i conflating it all? I remember my reason for eliminating that preference page was b/c it is my belief a user has no reason for every app to have a different set of preferences, and the overhead that comes with maintaining them (both for us and them).

**Comment by jenniemc** [comment]
Hi @rtwell , I kept the uiSchema title in normal text as oppose to bolded text in order to maintain the visual continuity of the VAOS appointment request flow.
