### ISSUE TITLE
Remove radio button selection from "Reason for appointment" for Community Care

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11317]
Remove selection from "Reason for appointment" - rationale is that those radio buttons do not make sense or map to CC requests needs. 

## Acceptance criteria:
- remove radio button
- keep additional info text box
- make this page and the additional info box optional

Screen as is now:
![Screen Shot 2020-07-16 at 12.36.50 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/184c17b0-a716-45d3-8f00-e4be0477fc96)

**Comment by rtwell** [comment]
i think we'd just simplify this page like so ( @peggygannon this needs your eyes)

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/d12e2f6d-83f8-445d-81c9-dc1919056ab0)

**Comment by narin** [comment]
@jbalboni @kreek For CC appointment request submissions, I see in `vets-api` that `purposeOfVisit` is optional, but do either of you know if the downstream service accepts a `null` value here? Or should I set this to `other` behind the scenes before submission to be safe?

**Comment by peggygannon** [comment]
Hi, @lenaecb @rtwell is the reason for this screen to help schedulers better schedule the CC request? 
Why are we asking users for this information?

**Comment by jbalboni** [comment]
@narin Yeah, I think we should set purposeOfVisit to whatever value it would be set to if you choose the "Other" option from the old radio buttons.

**Comment by rtwell** [comment]
the reason for this screen is
1. we need to provide Veterans a means to add any details about their symptoms that may be helpful for the health provider to know beforehand. 
2. We know Veterans like the ability to add details from our testing
3. we need a home for the 911 info. 

we could consider moving this content and condensing it onto the "How can the VA contact you?" screen, but then the details seem out of place, as does the 911 message. it's a tough one—very awkward in it's current form.

**Comment by lenaecb** [comment]
For this version, I think we keep as is. However, in the future, I think actually moving it up in the flow to be closer to the 'care type' selection would be helpful. 

From our recent round of research we have learned that the reason for appt and choose appt type (F2F, phone, video) feel very late in the process.

So, for now, let's move forward with this iteration and come back to this flow as part of our overall feedback from research.

**Comment by peggygannon** [comment]
@rtwell @lenaecb ok, thank you! Here's my recommendation for the updated language

**Tell us the reason for this appointment**

Please let us know any additional details about your symptoms that may be helpful for the community health provider to know. (Optional)

{Text box}

**Comment by lenaecb** [comment]
@rtwell - can you update the mock to reflect Peggy's latest?

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/88304998-f6913300-ccd6-11ea-9bb7-2a41f7c5ee9e.png)

**Comment by peggygannon** [comment]
looks good!
