### ISSUE TITLE
Community Care - Update cancel modal for CC

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11313]
Update copy for CC cancel modal to:

"Community Care appointments can’t be canceled online. Please call the below community provider to cancel your appointment."

Cancel modal now:
![Screen Shot 2020-07-16 at 1.06.30 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/7d46540c-89d8-4f05-b9c4-f6b977212fee)

**Comment by lenaecb** [comment]
@peggygannon - can you give us a quick thumbs up on the suggested phrasing here?

**Comment by peggygannon** [comment]
@lenaecb Yes, this modal content looks good

**Comment by jbalboni** [comment]
@lenaecb @peggygannon I thought the issue in the call was that the header said "your provider," rather than what the copy in the body of the modal said?

**Comment by lenaecb** [comment]
sorry, yes, I just went back to my scribbled notes and also checked with notes Judy sent me. It should be the header... so - "You need to call your community care provider to cancel this appointment" - @peggygannon thoughts on this header update?

I think we should also keep it consistent and also update the helper text as well. 

@jbalboni @peggygannon

**Comment by peggygannon** [comment]
Ok, thanks, @jbalboni  Yes, this below header is fine: 

**You need to call your community care provider to cancel this appointment**

Community care appointments can't be canceled online. Please call the below provider to cancel your appointment.
