### ISSUE TITLE
Use cache for non-node content

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11322]
## Issue Description
Currently, when doing a content build using the CMS export data, it'll use the cache for the `cms-export-content/`, but not for the non-node query. This is a reasonably fast query, but we should still be caching it and using the cache whenever we use the `cms-export-content/` cache.

Potentially, this may mean using `pages.json` whenever it exists, whether or not it came from a GraphQL build. (We're going to replace the `nodeQuery.data` anyhow. :man_shrugging:)

## Acceptance Criteria
- [ ] When the CMS export content cache is used, also use the non-node content cache if available

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
