### ISSUE TITLE
CT-Filter: Update Profile Page with new labels

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11324]
## Value Statement
As someone using the Comparison Tool, I want to be able to filter search results on more specific criteria so that I can more quickly find the institution I am looking for. 

## Assumptions
1. This work is completed behind a feature flag: #11344

## Acceptance Criteria
The institution summary section at the top of the CT Profile page for a school includes a label for any of the following categories: 

1. Gender: Women Only, Men Only
2. Specialized Mission: HBCU
3. Religious Affiliation: See supporting artifact 1
   a. For values of "-1 Not reported" and "-2 Not applicable" no tags will be displayed
   b. For values of "99 Other (none of the above)", display the tag "Other religious affiliation"
   c. For values of 77 & 79 (Protestant, Not specified) and (Other Protestant), display the tag "Protestant"
4. Tags are displayed in the following order:
   a. Gender
   b. Religious Affiliation
   c. HBCU
5. The following colors are utilized for the tags: 
   a. Text: 323A45
   b. Background: D6D7D9

## Supporting Artifacts
1. Religious Affiliation list of labels/dropdown: [ReligiousAffiliations_CollegeScorecard.docx](https://app.zenhub.com/files/133843125/c3c71389-ca8b-4ffd-9160-a5bd0508a88e/download)
2. Profile Page Prototype: https://bahdigital.invisionapp.com/share/QNIAEHO8BH2#/screens/296044997

**Comment by ksantiagomorgan6** [comment]
Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/13688

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-11 at 1.33.21 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0a5a199f-b45d-46a2-a6ca-498227a1b281)
##
![Screen Shot 2020-08-11 at 1.34.24 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/244989df-9c2c-476c-bef4-50e8db1c6ece)
##
![Screen Shot 2020-08-11 at 1.35.33 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/501faf06-dfe4-4916-9faa-79ce99877a3f)
##
![Screen Shot 2020-08-11 at 1.32.57 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/08d85828-c655-468d-b6e5-204bbaadf743)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/10687&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by ccruzgra** [comment]
This checks out for UX, @sonntag-adam.

**Comment by sonntag-adam** [comment]
Closing story.
