### ISSUE TITLE
Remove unused dependencies in vets-website

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#11323]
Generate a report using [depcheck](https://github.com/depcheck/depcheck)

**Comment by jhonnyoddball** [comment]
### This is the `depcheck` report:

Using `$ depcheck --ignores='eslint'`
```
Unused dependencies
* leaflet-control-geocoder
* react-dropzone
Unused devDependencies
* @department-of-veterans-affairs/generator-vets-website
* cypress-multi-reporters
* enhanced-resolve
* eslint-import-resolver-babel-module
* extract-text-webpack-plugin
* json2csv
* mocha-junit-reporter
* nyc
* polyfill-function-prototype-bind
* quick_check
* react-test-renderer
* recursive-uncache
* start-server-and-test
* uglify-js
* webpack-cli
* webpack-dev-server
```

**Comment by billfienberg** [comment]
The following `vets-website` dependencies are only used in `package.json`:

- `react-dropzone`: https://github.com/department-of-veterans-affairs/vets-website/search?q=react-dropzone&unscoped_q=react-dropzone
- `leaflet-control-geocoder`: https://github.com/department-of-veterans-affairs/vets-website/search?q=leaflet-control-geocoder&unscoped_q=leaflet-control-geocoder
- `enhanced-resolve`: https://github.com/department-of-veterans-affairs/vets-website/search?q=enhanced-resolve&unscoped_q=enhanced-resolve
- `extract-text-webpack-plugin`: https://github.com/department-of-veterans-affairs/vets-website/search?q=extract-text-webpack-plugin&unscoped_q=extract-text-webpack-plugin
- `json2csv`: https://github.com/department-of-veterans-affairs/vets-website/search?q=json2csv&unscoped_q=json2csv
- `polyfill-function-prototype-bind`: https://github.com/department-of-veterans-affairs/vets-website/search?q=polyfill-function-prototype-bind&unscoped_q=polyfill-function-prototype-bind
- `quick_check`: https://github.com/department-of-veterans-affairs/vets-website/search?q=quick_check&unscoped_q=quick_check
- `react-test-renderer`: https://github.com/department-of-veterans-affairs/vets-website/search?q=react-test-renderer&unscoped_q=react-test-renderer
- `recursive-uncache`: https://github.com/department-of-veterans-affairs/vets-website/search?q=recursive-uncache&unscoped_q=recursive-uncache
- `uglify-js`: https://github.com/department-of-veterans-affairs/vets-website/search?q=uglify-js&unscoped_q=uglify-js
- `webpack-cli`: https://github.com/department-of-veterans-affairs/vets-website/search?q=webpack-cli&unscoped_q=webpack-cli

**Comment by meganhkelley** [comment]
@timwright12 should we close this in favor of #27348?
