### ISSUE TITLE
Design feedback - Design intent collaboration: CT Filters 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#11325]
**Do:**
- If you choose to use the additional info component for the filters (military details and housing allowance), separate the blue bar instead of letting it expand on both sections. Let the blue bar expand on the appropriate section showing information belonging to the specific section

**Try:**

- No "try" feedback at this time

**Consider:**

- Consider sentence case for tags. We like the color choice since these tags are informational. Follow up with Ryan T. about interactive tags. He’s creating a design where the outline and text are blue. 

**Definition of Done:**
- [ ] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by ccruzgra** [comment]
@CrystabelReiter Thanks for the feedback! We'll let you know if we have any questions.
