### ISSUE TITLE
Find VA Form - Detail Pages Use Cases

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11335]
## Issue Description
Track and compile the various use cases that exist for your product

## Acceptance Criteria
- [x] Make a copy of the [Product Use Cases Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md) and add to your product folder if one does not already exist
- [x] Add/update the various [use cases for your product](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md)
- [ ] (Optional) Submit along with your QA test plan request

**Comment by MickinSahni** [comment]
@jenniferlee-dsva to drop specs for me to use in documenting the use cases

**Comment by jenniferlee-dsva** [comment]
@MickinSahni I added a link ^ to the use cases. The uses cases link to visual mockups, but right now the FE Preview template has a couple of errors, so the preview pages won't match the designs. They will be aligned after Kelson finishes the preview bug fix in ticket #11444.

**Comment by MickinSahni** [comment]
Hey @jenniferlee-dsva , took a look and noticed one thing—

The _minimum custom form data_ use-case mentions 'the standard set of "helpful links."' But, that section on the associated mock-up looks to be the same as the _maximum custom form data_ use-case associated mock-up.

Could you confirm what the standard set looks like?

Version user sees when a page has all custom content fields: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-heading-hierarchy-071620.pdf

Version user sees when a page has no custom content fields: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-minimum-content-071620.pdf

**Comment by jenniferlee-dsva** [comment]
@MickinSahni Great catch! The screenshots above are both showing the custom helpful links. OMG. There are so many details - I am really sorry. The example I grabbed from the CMS happens to be a form that has custom helpful links but no tool link and now 'when to use this form' content.

Here is a screenshot of what the NOT custom -- standard helpful links section looks like - fysa @ncksllvn and @kelsonic for awareness: 

![image](https://user-images.githubusercontent.com/43381063/88739320-48d3b900-d108-11ea-9426-d5e5bd9f0564.png)

**Comment by jenniferlee-dsva** [comment]
Hey - I just checked in the CMS and the FE template preview PRs came through and everything looks correct and great. 

http://preview-prod.vfs.va.gov/preview?nodeId=6133  
and 
http://preview-prod.vfs.va.gov/preview?nodeId=6140

![image](https://user-images.githubusercontent.com/43381063/88739796-72411480-d109-11ea-8e6f-8d12e296eb49.png)


I'll update the bad version PDF in the product repo with this ^ correct FE version.

**Comment by MickinSahni** [comment]
💯 thanks, jen! 

👋 @tzelei @pjhill getting this on your radar (added the `vsa-qa` label). these use cases should be in a good spot for starting TestRail entry. let us know if anything can be clarified! 🙇

**Comment by pjhill** [comment]
@MickinSahni Thanks for the heads up! It looks like Tze already has a good suite of test cases created. A separate QA environment sounds great!

@tzelei , do you want me to go through the use cases and make sure there's a relevant test case for each?

**Comment by tlei123** [comment]
> @tzelei , do you want me to go through the use cases and make sure there's a relevant test case for each?

hi, @pjhill !  Yeah, that'd be great if you got the time right now.  :)  This week I'm finishing up Authd-Exp's Profile 2.0 test-runs, and starting BaM2's Debt Ltrs test-plan.

**Comment by jenniferlee-dsva** [comment]
@MickinSahni @tzelei - I've updated the [product use cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md) with a list of the top 40 form pages that we can QA with.

**Comment by MickinSahni** [comment]
potential new scenarios:
- 404ing pdf download link - ticket/implementation pending

**Comment by MickinSahni** [comment]
@tlei123 @pjhill i updated use cases doc with two newer scenarios re: deleted forms and invalid PDFs
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md

**Comment by jenniferlee-dsva** [comment]
@tzelei and @MickinSahni 
RE new scenario - the bad pdf download link error [per Mickin's message:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11335#issuecomment-669325402)

See ticket #12181 which describes this use case and will address it with a new error/info message.

**Comment by MickinSahni** [comment]
@tlei123 @pjhill hey team, we have one scenario we're working on re: error message for form detail pages (#12181). we're working on that this coming sprint (8/12). 

you mentioned having stubbed out cases in TestRail. how long will it take to flesh those out completely?

**Comment by tlei123** [comment]
@MickinSahni @jenniferlee-dsva , I've just started stubbing-out [TestRail test-cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&group_id=187).

There're a few questions though before I'd know when\* they can all be fully fleshed-out:

1. Re. [Use-Case C](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md#use-case-c) (Invalid PDF URLs):
  a. will a page path (either a preview-node-URL or actual-page-URL) be available for this case?
  b. will a design prototype be available for this case?
2. Re. [Use-Case D](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md#use-case-d) (Deleted Forms), how can/will this be QA'ed?  I'm reading that the Detail page would be "unpublished" in this case.  E.g., will we be QA'ing just the error-message in the Form-Search results page, searching by specific keyword(s)?
3. Re. the [top-40 forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md#batch-1---top-40-forms-for-qa):
  a. which detail-pages are for which Use Case?
  b. are corresponding preview-node paths (/preview?nodeid=????) be available for these forms?  I'm still waiting for VA-network access\*\* to get re-enabled, so currently I can only access the preview-nodes (e.g., /preview?nodeid=5891) via my socksProxy.

Please let me know.  Thx much!


\*Assuming quick answers/resolutions to my questions, I'm shooting for test-cases completion by end of this week.
\*\* @pjhill , did you mention you have VA-network access?  If yes, can you check if you can access the top-40 forms? \[link is in my question #3 above]

**Comment by jenniferlee-dsva** [comment]
Will try to answer ^ in-line.

**Comment by jenniferlee-dsva** [comment]
I couldn't finish answering ^, but will get back to finishing replies in a bit @tlei123

**Comment by jenniferlee-dsva** [comment]
@tzelei - in line answers above

**Comment by tlei123** [comment]
thx, @jenniferlee-dsva !  Never mind about mapping the top-40 forms to use-cases from your end.

I can now log into prod.cms.va.gov, so i'll sort them out.

@MickinSahni , expect an update on TR test-cases some time tmrw (Thu).  We're looking good for having those finalized by end of week.  :)

@pjhill , nvm about access the top-40 forms; i got that figured out now.

**Comment by pjhill** [comment]
@MickinSahni, @tzelei -- I'm so sorry! Various VSP responsibilities kept popping up, and I haven't been able to contribute to the authoring of these test cases. I'm out on (unexpectedly early) parental leave starting 8/11 and returning 8/26.

If this effort is ongoing upon my return, I will prioritize time to spend contributing.

**Comment by tlei123** [comment]
@MickinSahni , would you consider those forms with only **When to use this form** section Use Case A?

The design screen for Use Case A doesn't have this section, BUT that screen's described as "no custom content", while your Use Case A is described as "minimum custom form data".

I added preview-node URLs and preliminary Use-Case mappings to the [top-40 forms](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md#batch-1---top-40-forms-for-qa).  Maybe you can click a few that's marked "(in-between)", and let me know if they're good for Use Case A?

None of those forms have NO custom data; they all have at least **When to use this form**.  I'm guessing the "(in-between)" ones are Use Case A, but just wanna double-check w/ you.

Pls. let me know.  Thx much!

cc @jenniferlee-dsva 

P.S. No sweat, @pjhill !  I'll manage.

**Comment by MickinSahni** [comment]
> @MickinSahni , would you consider those forms with only **When to use this form** section Use Case A?

👋 Hey @tlei123, great question. **When to use this form** is a custom field. Not all forms will have that so it falls into the minimal bucket.

**Comment by tlei123** [comment]
@MickinSahni , [TestRail test-cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&group_id=187) now updated, based on today's discussions and your Use-Cases updates.  TR links also added to the [Test Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md):

- For new Use Case C (No custom form data) which we've determine to be edge-case, I have a new [TR test-case C909](https://dsvavsp.testrail.io/index.php?/cases/view/909) in case we do find some examples to QA.
- For update Use Case D (invalid PDF link), also awaiting QA examples, I've added links to the new Design prototypes provided via #12181 (to which I'm Subscribed).

Pls keep me posted on QA example pages for these two Cases.  No big deal if none are found for edge-case C.

Thx much!

**Comment by jenniferlee-dsva** [comment]
Hi - I'd love to check in on the ETA for QA of form detail pages. Would like to keep the VA forms stakeholder working group know an estimate of where we are. @tzelei @MickinSahni 

Let me know if there's any action item on my part here!

**Comment by MickinSahni** [comment]
> @MickinSahni , [TestRail test-cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&group_id=187) now updated, based on today's discussions and your Use-Cases updates. TR links also added to the [Test Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md), along with updated Use-Case mappings.
> 
>     * For new [Use Case C](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md#use-case-c) (No custom form data) which we've determine to be edge-case, I have a new [TR test-case C909](https://dsvavsp.testrail.io/index.php?/cases/view/909) in case we do find some examples to QA.
> 
>     * For renamed [Use Case D](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md#use-case-d) (Invalid PDF URLs) [[TR test-case C860](https://dsvavsp.testrail.io/index.php?/cases/view/860), also awaiting QA examples], I've added links to the new Design prototypes provided via #12181 (to which I'm Subscribed).
> 
> 
> Pls keep me posted on QA example pages for these two Cases. No big deal if none are found for edge-case C.
> 
> Thx much!

Hey @tlei123, would you need examples for Use Case D available in perpetuity? This is a negative case we're testing for and we'd hope we would *never* have an invalid PDF url. BUT, we can introduce a temporary example that we'd need to revert. Is that ok?

**Comment by tlei123** [comment]
@jenniferlee-dsva @MickinSahni , i'm shooting for starting test-runs this Thu 20th afternoon and finishing late Fri / early Mon \[got your SSO-Cerner and BaM1's BDD test-runs to do right now].

Re. Use Case D (invalid PDF link), no we won't need to perpetuate this edge-case.  I'm fine with validating that just once. 
 I'm figuring any re-test would only be needed IF the alert trigger condition(s) get updated in the future for some reason.

IF I can't get a testable example for D, then yes a screenshot would be good.

**Comment by jenniferlee-dsva** [comment]
@tlei123 - hello! I'm checking in to see if we're on track for completing QA early this week?  [Per this eta, ](https://dsva.slack.com/archives/CUB5X5MGF/p1597853280234800), we'd like to work on fixing any QA bugs this week.

**Comment by tlei123** [comment]
@jenniferlee-dsva , Use Cases A & B (and the top-40 form's Detail pages) are almost done; I'm wrapping 'em up this evening...

@MickinSahni , @ncksllvn , do we have:
- Any QA-examples of edge Use-Case C (No custom form-data)?
- Screenshot for Use-Case D (invalid PDF link)?
- Any QA-examples of Use-Case E (deleted forms)?  \[I vaguely recall this Case may have been deemed out-of-scope for Detail-Pages QA, but I'm not positive.]

**Comment by jenniferlee-dsva** [comment]
RE use case E - Slack: https://dsva.slack.com/archives/CUB5X5MGF/p1598308983009400?thread_ts=1598299668.007800&cid=CUB5X5MGF

**Comment by MickinSahni** [comment]
Hey, Tze. Use-Case D (invalid PDF link) is in progress with #12181 and #11380 in code review at the moment. 
Nick will supply a screenshot/recording when it's wrapped up. 

Wrt to Use Case C (No custom form data), closing the loop here that Jen provided a sample in slack with http://forms.demo.ci.cms.va.gov/find-forms/about-form-10-2649b 👍

**Comment by tlei123** [comment]
Thx, @jenniferlee-dsva @MickinSahni !  Use Case C test-runs done and Passed.

For Use Case D (invalid PDF link), I'm now Subscribed to both #12181 & #11380.

**Comment by tlei123** [comment]
@MickinSahni @jenniferlee-dsva , Use Case D (invalid PDF link) QA'ed.

So, all Test Cases except for Use Case E\* has been tested: 
- Mac Chrome test-cases & results
- Mac Firefox test-cases & results

\* @MickinSahni @pjhill , for Use Case E (deleted forms), see our Slack convo cited by Jennifer.  Due to testability challenges [cited by Jennifer on Slack](https://dsva.slack.com/archives/CUB5X5MGF/p1598308983009400?thread_ts=1598299668.007800&cid=CUB5X5MGF), and the fact that there wouldn't really be a Detail-page per se to be tested, maybe this "outstanding" Case should be out-of-scope for Detail-pages QA?  I'm thinking it's probably more appropriate for a future Find VA Forms - Search QA \[possibly when that feature gets updated?]  Let us know your thoughts please.  Thx much!

**Comment by jenniferlee-dsva** [comment]
@tzelei - Was the staging demo of the invalid pdf use case okay? Can we close QA ticket? 

Invalid PDF staging demo thread: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12181#issuecomment-683923844

**Comment by tlei123** [comment]
> @tzelei - Was the staging demo of the invalid pdf use case okay? Can we close QA ticket?
> 
> Invalid PDF staging demo thread: [#12181 (comment)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12181#issuecomment-683923844)

@jenniferlee-dsva , yes, the invalid-PDF use case is okay and QA'ed.  This Use Cases ticket is what I'm actually using as the QA ticket.

@MickinSahni , I think we can Close this UNLESS you think we still need to figure out how to QA Use Case E (deleted forms) -- see my previous Comment (^^).  cc @pjhill

**Comment by MickinSahni** [comment]
Thanks, Tze, for the Use Case E call out. Created a post-launch discovery ticket for us to explore this scenario (perhaps around testing in CMS in general): https://github.com/department-of-veterans-affairs/va.gov-team/issues/13331
