### ISSUE TITLE
[KEYBOARD]: GIBCT Learn more modals scroll down the page, change focus, when I press TAB

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1133]
## Issue
The GI Bill® Comparison Tool modal windows do not remain stationary when I press `TAB` one or more times inside the modal. They seem to be firing a `window.scrollTo` event or some other item that's scrolling my browser window. This could be confusing to keyboard and screen reader users. Animated GIF attached below.

## Related Issue and PR
* **Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/1132
* https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/209
* **Pull Request:** https://github.com/department-of-veterans-affairs/vets-website/pull/9403

## Acceptance Criteria
* As a keyboard user, I want to be able to press `TAB` inside the modal window and not having it scroll
* As a keyboard user, I want to be able to press `SHIFT + TAB` inside the modal window and have my focus move backwards, but not escape the modal window. The window also should not scroll.
* As a screen reader user, I want the same things as the keyboard user, and I want focus restored to the `Learn More` button that opened the modal window when I close the modal window.

## Environment
* MacOS Mojave
* Chrome latest

---
![gibct-modal-window-scroll](https://user-images.githubusercontent.com/934879/51401557-abf68f80-1b10-11e9-9483-b0df0f015d98.gif)

**Comment by desireeturner** [comment]
The https://github.com/department-of-veterans-affairs/veteran-facing-services-tools repo deployments are currently broken, so we're going to make this update in the vets-website repo. We will enter a follow-on defect with instructions on how to resolve this issue in the veteran-facing-services-tools repo to be resolved once deployments are restored. cc @shawkey-daniel @ksantiagomorgan6

**Comment by ksantiagomorgan6** [comment]
Bug as been created in the veterans-facing-service-tools-repo, https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/issues/209

**Comment by ksantiagomorgan6** [comment]
Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/12303

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
@1Copenut This fix is on Staging and ready for your review

**Comment by 1Copenut** [comment]
@delli-gatti-michael I retested this on Staging, and think we're good to close. There's still a small movement when I press `Shift + TAB` with the modal open, but that could be a lot of things and feels out of scope. I'll go ahead and close this one.
