### ISSUE TITLE
Access for [Michelle Middaugh]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11331]
# Description
Request: Please provide SOCKS proxy access as this is required to complete support work on Facilities portfolio of products.  Access needed for: dev, staging, prod,  CI environments and Jenkins.

- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Michelle Middaugh
- Please Provide your email.
   > michelle.middaugh@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Facilities team, Product Manager, Ad Hoc, LLC

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
$ cat id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDA7m1Zlr1frO2z0tToTT/FPZPnNkFSTrQQxpSgFebzGgog9bhbw8+15LMTm7hdW2SF9bdWa7fTmddjhIDE/0ugOnlASV2365QNXwTCYlaCN8ymSETExHsiJT3wDmNEzhw4XysRrHEi1s79mMZIyaJm7PXXEgNtwp1KgW5ym9ydscY/C5/BwwrIKBSKr2dATLMtyAY7/KM3sXa4oT3TMD3hgwIR5HolT/5DHCCNDCiRbuNn7n4OldLU5bMf2OQk290i39F9HjHCp0mlKP1ZRVt2ZLAQwvKZeJPjqe5Rhh8MZiejHyvVPE9WmFEh0K4qwh+9boxoIckAkVWAscb8Q15QNS/V40HejkNo+s4G1JxWRAnFryV3pcUmUlbQDsC79lK5RZQcEStdHbY9LjvQ77dvRJ6To8ZMi/usQk7GLUR2SQuyzGiWn9nGNszGSuAvY+X2FZf6qEw2rFaAg4NuDRLHM02+J4XiV46Qx8eylJB1UEwjSKxX8/Hcfu3+R7ANlL0= Michelle Middaugh@DESKTOP-PM3JNMO
```

- Grant AWS Console access?
  > NO

**Comment by jsev-io** [comment]
@mmiddaugh Please verify you have access to the SOCKS proxy now.
Thanks!

**Comment by mmiddaugh** [comment]
Hi - I recently sent my laptop back for repair and since getting it back - I cannot access SOCKS and Gitbash doesn't recognize the file or directory

**Comment by mmiddaugh** [comment]
@jsev-io do I need to start this process all over?

**Comment by jbritt1** [comment]
@mmiddaugh, Julian (jsev-io) is no longer on this project. I would recommend going back through the process as there is no easy way to tell what was altered during the repairs made to the system.
