### ISSUE TITLE
686 Silent Failures: Establish Email Procedures

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11339]
## Description
We have learned recently that there is a Gov Delivery service that could be used for for email service.

## Goal
We need to wire up to this email service to expose to the Veteran the status of their application submission.

## Considerations
- Are we allowed to do this? What permissions do we need?
- Kevin Mircovich and Lihan might know, or maybe 1010EZ is using it
- Ask Paul Short what he might know
- There are folders with ruby templates in ` vets-website/app/mailers`

## Tasks
- [x] Establish how to connect to this service and utilize its SMTP functionality

## Acceptance Criteria
- [x] A plan for integrating with Gov Delivery service has been explored

**Comment by jason-gcio** [comment]
WIP draft doc with notes so far: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/potential-email-solution.md

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4576

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/potential-email-solution.md
