### ISSUE TITLE
Add modern form detail URLs to redirect spreadsheet

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11336]
## Add modern form detail URLs to redirect spreadsheet

__This ticket is related to the [redirect ticket #5549](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5549).__

Currently we have a spreadsheet of all the legacy form detail pages that we want to do 1:1 redirects for. There are about 70 form pages that need 1:1 redirects. 

The legacy URLs are captured. Mikki needs the specific modern form page URLs individually listed out.

AC:
- [x] Add the modern form detail page URLs to the spreadsheet located here: 
https://drive.google.com/file/d/1hIVyafXDMQGJZZWQliQ0yQdboP7Uu7Mz/view?usp=sharing
- [ ] Update redirect request with url mapping and close out this ticket

**Target ETA:** This can be completed this or next sprint. 

Background:
- redirect a portion of the form detail pages 1 for 1 from the legacy based on analytics, etc.
- redirect all other form detail pages to Find VA Forms - Search

**Comment by MickinSahni** [comment]
Tentatively scheduled for sprint 27 but might be able to pick up for 26.

**Comment by lunascoop** [comment]
Completed initial pass and updated Google sheet. Am having trouble finding some of the forms on the site, so I will reach out for assistance. I also found a bug, ticket #11813.

**Comment by lunascoop** [comment]
@RLHecht the spreadsheet is ready again for review.

**Comment by RLHecht** [comment]
This has been reviewed. I changed the one 10-10EZ that we discussed on slack. Everything else looked good, @jenniferlee-dsva FYSA @MickinSahni
