### ISSUE TITLE
IA Feedback from Design Intent - Comparison Tool Ratings

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#11347]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Must
- Include the numeric rating and scale along with the stars to reduce cognitive load and ensure users can understand and read the rating - i.e. "4.6 out of 5"
- Do not use stars for both the VETTEC preferred provider and the ratings, use different icons or eliminate the icon for one of them - if they are both the same they will appear to be related
- Be consistent in the use of the word "rating" versus "feedback".  The word "feedback" can infer that there are comments, and in this case it is purely a rating. Strongly suggest keeping "rating" as the label. 

## Should
- Review placement of the rating within the search results and detail page and ensure its level of importance is aligned with its placement.  For example, it is currently placed at the very top of the card along with the name, I would only place the rating here if it was the most important criteria in evaluating a school, which would assume that we have a solid volume and perspectives of ratings.  Consider potentially placing along with other data points on the card - such as the number of attendees or the feedback. 
- Include labeling the ratings to indicate that they are from Veterans - i.e. "Veteran rating".  If/when more users are allowed to provide ratings, this can evolve to be "Student rating" or "Attendee rating", etc. 
- On the school detail page, add a heading over the the overall ratings section to label the "distribution of ratings" similar to how it is handled in the detail. 

## Consider
- Include controls to ensure ratings cannot be spammed - i.e. only allow a user to rate a school once, ask the user when they attended as a deterrent to rating a school they didn't attend, etc
- Adding a filter for rating, such as "5 stars and up", "4 stars and up", "3 stars and up", etc. 

## General Questions:
- Can they leave any of the ratings categories blank?
- When the user clicks on the link showing the number of ratings "(122 ratings)", where do they go
- How will you ensure only Veterans rate a school?
- What will drive users to provide a rating and will they have to search for their school in order to do it or can we link them to it?

## Definition of Done
* Team acknowledges and responds to feedback in ticket 
* Team schedules follow up conversations with IA as needed

**Comment by amyknox** [comment]
Thanks for the input @mnorthuis ! We'll review and let you know if we have any questions.
