### ISSUE TITLE
STEM: Update preferred contact method to radio buttons

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11346]
## Assumptions
1. This work is completed behind the form's prod flag

## Acceptance Criteria
1. The options have been updated so that they are now are single-select radio buttons instead of multi-select checkboxes: 
   a. Mail
   b. Email
   c. Home phone
   d. Mobile phone

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13525

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-17 at 10.30.24 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/238e9a14-e5f8-4ab6-83c9-a701987f4b97)
##
![Screen Shot 2020-07-17 at 10.30.29 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a9a5d73c-c873-4934-b4b9-c9d289cfa2dd)
##
![Screen Shot 2020-07-17 at 10.30.33 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/39459d68-6931-4904-ba47-921daaa70dfd)
##
![Screen Shot 2020-07-17 at 10.30.38 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e1731018-e48d-49b8-9a33-7fc490c9f391)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9715&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam This checks out for UXers.

**Comment by sonntag-adam** [comment]
Closing story.
