### ISSUE TITLE
STEM: Load Testing

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11345]
## Value Statement
As a member of the development team, I need to ensure that the new standalone STEM form 22-10203 is performant so that when we go live Veterans are able to utilize and submit the application without issue. 

## Assumptions: 
1. None

## Acceptance Critera: 
1. Load testing has been completed against the standalone STEM form on staging. 
2. Load testing results have been captured on GitHub and linked in the comments of this story

## Supporting Artifacts: 
1. Example for load testing: https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest/education_benefits_claim_1995_stem
2. https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest#load-testing

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/7340/
