### ISSUE TITLE
CT Filter: Make additional College Scorecard data available in the Comparison Tool

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11343]
## Value Statement
As someone using the Comparison Tool, I want to be able to filter search results on more specific criteria so that I can more quickly find the institution I am looking for. 

## Assumptions
1. No feature flag is needed for this issue

## Acceptance Critieria
1. The following College Scorecard data elements are available for utilization in Comparison Tool filtering and display: 
   a. Women Only (womenonly)
   b. Men Only (menonly)
   c. HBCU
   d. Religious Affiliation (relaffil)
   e. HCM2 (heightened cash monitoring, severe)
   f. PCTFLOAN (Percent of Full-time, Firsttime Undergraduates Receiving Federal Loans)
2. This data is returned on institution searches and profile endpoints. 

## Supporting Artifacts

**Comment by ksantiagomorgan6** [comment]
Pull request db migration: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/684

Pull request: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/683

**Comment by sonntag-adam** [comment]
[Uploading... Screen Shot 2020-07-20 at 12.40.34 PM.png ]

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-20 at 1.36.56 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/45997a95-4037-47fd-90fa-f8a73a5458f2)

**Comment by sonntag-adam** [comment]
pctfloan not being pulled in.

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-21 at 10.04.49 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a1fa6d5b-9a12-4d35-bafb-4b4a5a913f7c)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-21 at 10.05.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4d9e39f8-24b1-4ae3-9ef6-990b3d96f821)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-21 at 10.06.36 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a8a4f927-6171-47e3-9e42-19942877542f)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-21 at 10.07.32 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e7b4f674-14f5-432e-94f8-95d96320fa1c)

**Comment by sonntag-adam** [comment]
In staging. closing story.
