### ISSUE TITLE
Debt Letters MVP  VSA-QA Test Plan

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11342]
## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- [Product/Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/new%20product_outline.md)
- Product/Feature Epics:
    - Landing page (**Manage your VA debt**): #7527
    - Debt list page (**Your VA debt**): #9931
- Product/Feature Pre-Launch Checklist: \[provide link]
- Product/Feature Design artifacts:
    - [Wire Flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/design/wireframes.md)
    - [UXPin MVP prototypes](https://preview.uxpin.com/305eb36ed6ec2e5f2bc1dd91659b70ef961ab269#/pages/129917808/simulate/sitemap?mode=i)

## Product-team SMEs

Product Management: @leahkeeler @mattpointzxer0 
Design/Research: @rebeccawalsh @rileyorr 
Content/IA: @DanielleThierryUSDSVA 
Front-end: @bradl3yC 
Back-end: @camerontesterman 
QA: Tze-chiu Lei

## Proposed user-scenarios and Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs (ideally, use [this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md) from VSA Design Lead).  IMPORTANT for authenticated-experiences: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

1. Landing page (**Manage your VA debt**) - unauthenticated - \[design-prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e)
2. Debt list (**Your VA debt**):
    - Default - ```vets.gov.user+1@gmail.com``` (Greg) - [design-prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/simulate/sitemap?mode=i)
    - Empty states:
        - General - \[test-acct TBD] - [design-prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130748284/simulate/sitemap?mode=i)
        - Resolved debts - \[test-acct TBD] - [design-prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174953/simulate/sitemap)
        - COVID debt suspension - \[test-acct TBD] - [design-prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174235/simulate/sitemap?mode=i)
    - Error states:
        - 404 - VBMS (Debts present, no letters) - ```vets.gov.user+14@gmail.com``` (Jerry) - [design-prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130821989/simulate/sitemap)
        - 404 - DMC (No debts, letters present) - ```vets.gov.user+229@gmail.com``` (Mark) - [design-prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130822746/simulate/sitemap)
        - 404 - Both (No debts, no letters) - ```vets.gov.user+21@gmail.com``` (Chad) - [design-prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130823985/simulate/sitemap)

### Moderated UATs on Prod

Due to SPI/PII restrictions that preclude data-integrity validation on Staging, moderate UATs will be conducted on Prod, recruiting real Veteran users to validate their debt letters via remote sessions.

See Moderated UAT spreadsheet attached below for details on what questions will be asked, and eventually how each UAT participant responds:
[Debt Letters UAT Checklist Aug 2020.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5065777/Debt.Letters.UAT.Checklist.Aug.2020.xlsx)

## How to configure this issue

- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Test Plan reviewed by Product Team.
- [ ] Test Plan finalized per review feedback.
- [ ] Actual Test Run(s) completed on Staging \[or [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by leahkeeler** [comment]
@tzelei This is all god except the debt details page is not part of MVP, it will be released in iteration 1

**Comment by tlei123** [comment]
@bradl3yC @camerontesterman , do you have Staging test-accounts for all the user-scenarios listed above (in the main Description)?

Also, the Staging Debt-List page that was accessible last week is now throwing up our Not-Found error-page: https://staging.va.gov/manage-va-debt/your-debt  I'm using test-acct 1 & 21 (for the 2 user-scenarios that have test-accts provided.

I didn't think Flipper feature-flag would limit access on Staging, but I might be wrong.  Do you think the test-acct emails need to be added for Staging access?

cc @pjhill

**Comment by tlei123** [comment]
@pjhill , i just attached @rileyorr 's Prod Moderated UAT spreadsheet up in the main Description above \[see **Moderated UATs on Prod** section].  On first scan, it looks plenty thorough to me.

Do feel free to take a look if you like.  Your input is very welcome.  Thx much!  :)

**Comment by tlei123** [comment]
@leahkeeler , while waiting for test-accounts for the remaining Empty-state cases, I've logged a couple of defects from those cases I've been able to run: 

#12398 - A couple of copy anomalies
#12438 - pay.gov link

Once test-accounts for the Empty-state user-scenarios are determined, I'll run those test-cases, and generate the TestRail reports.

cc @bradl3yC

**Comment by tlei123** [comment]
Sorry, @leahkeeler !  I fat-fingered the 1st ticket# above.  Just corrected it -- should be #12389 .

**Comment by tlei123** [comment]
@bradl3yC , once you can add local screenshots of the mocked 404 - VBMS & - DMC cases, I'll remove those cases from the Test Plan.

Thx much!

**Comment by bradl3yC** [comment]
@tlei123 for your review:

### DMC 404
![DMC404](https://user-images.githubusercontent.com/6165421/90176176-8fffb200-dd76-11ea-813d-b025c59fc1db.png)

### VBMS 404
![VBMS404](https://user-images.githubusercontent.com/6165421/90176188-97bf5680-dd76-11ea-9a18-e847f0da7dc9.png)

### Both VBMS DMC 404
![BOTH404](https://user-images.githubusercontent.com/6165421/90176294-b9204280-dd76-11ea-9efc-2d73cae2b616.png)


### DMC Empty Response
![DMCEMPTY](https://user-images.githubusercontent.com/6165421/90176318-c0475080-dd76-11ea-96e8-f80c3bba77f5.png)


### VBMS Empty Response
![VBMSEMPTY](https://user-images.githubusercontent.com/6165421/90176331-c50c0480-dd76-11ea-9841-53625b5c8d69.png)

### Both DMC and VBMS Empty Response
![BOTH EMPTY](https://user-images.githubusercontent.com/6165421/90176401-d9e89800-dd76-11ea-99c6-3e655cb48818.png)

**Comment by leahkeeler** [comment]
@tlei123 - Can we close this? or still in progress?

**Comment by tlei123** [comment]
Yep, closing.
