### ISSUE TITLE
CF: Include new VA Caution Flags CSV in version generation

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11354]
**As** an EDU team member, I need the ability to upload a single file of caution flag data to GIDS so the number of steps to maintain the comparison tool is reduced.

## Assumptions:
1. This does not affect the MOU, Accreditation Action and HCM caution flags
1. This does not remove the current caution flag mapping that is triggered via post deploy actions
1. Current `caution_flags` table will continue to be used to reduce impact on vets-website

## Acceptance Criteria
1. When generating a new version, `caution_flags` for Settlement, School Closing and Section 702 are created using the data from VA Caution Flags CSV
1. Mapping rules for Settlement and Section 702 are no longer generated on post deploy actions
1. The following CSVs rows do not show in the **Latest Uploads** table in the GIDS dashboard
    - Settlement
    - SchoolClosure
    - Sec702School

### Main
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/694
### Supplemental
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/698
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/702
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/703
- https://github.com/department-of-veterans-affairs/devops/pull/7385

**Comment by zurbergram** [comment]
There is a `sec702` field on institutions that is returned the profile data

**Comment by zurbergram** [comment]
So the [Download Data on All Schools (Excel)](https://www.benefits.va.gov/GIBILL/docs/job_aids/ComparisonToolData.xlsx) in the CT

has a sheet called “Caution Flags” which checks the `caution_flag` (BK) and `caution_flag_reason` (BL) columns in the “Comparison_Tool_Data_Full” sheet

It does a count of `caution_flag` and does contain checks for various `caution_flag_reason`

Meaning the `institution.caution_flag` boolean and `institution.caution_flag_reason` CSV string need to keep being populated

![image](https://user-images.githubusercontent.com/1094999/89335073-820aac80-d665-11ea-8294-0cd89d22f0f7.png)

**Comment by zurbergram** [comment]
@dneel-bah 
Questions:
1. If an institution is not sec702 should the caution flag be the current values
    - title: ’School isn\‘t approved for Post-9/11 GI Bill or Montgomery GI Bill-Active Duty benefits’,	
    - description: ’This school isn\’t approved for Post-9/11 GI Bill or Montgomery GI Bill-Active Duty benefits because it doesn\‘t comply with Section 702. This law requires public universities to offer recent Veterans and other covered individuals in-state tuition, regardless of their state residency.’,	
    - link_text: ‘Learn more about Section 702 requirements’,	
    - link_url: ‘https://www.benefits.va.gov/gibill/docs/factsheets/section_702_factsheet.pdf’
1. If the row is missing a "settlement title" but has a "settlement description" should:
    a. The row have been import from the CSV originally?
    b. A caution flag be created without a title?
    c. A caution flag be created with a default title?
1. For Caution Flags in general there is `link_text` and `link_url`, currently the frontend will not show a `link_url` if there is not `link_text`, should:
    a. The frontend be changed to display urls if there is not `link_text` present?
    b. The VA Caution Flag CSV be updated to have a `settlement link text` column?

**Comment by shawkey-daniel** [comment]
1. 702 caution flags should continue to work the same. The only difference is 702 flag is now in the new consolidated file.
	2. If the row contains a settlement description but no settlement title, the row should not be imported during the upload. The row should be reported in the error message for upload.
	3. B
	4. Make available
	5. Ignore

**Comment by zurbergram** [comment]
Looks like only 2 institutions that are in VA Caution Flags CSV that could have a sec702 flag are

- "11900238"	"TEMPLE UNIVERSITY"
- "12000238"	"TEMPLE UNIVERSITY HEALTH SYSTEM"

as these 2 are PUBLIC institutions that are approved

**Comment by zurbergram** [comment]
resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/12238

**Comment by zurbergram** [comment]
When testing if using CSVs that were uploaded in https://github.com/department-of-veterans-affairs/gibct-data-service/pull/703

After uploads, generate, and publish in SQL do
```
select *
	from caution_flags
	where source in ('Settlement', 'Sec702')
```
And there should be 21 rows, 1 Sec702 and 20 Settlement rows.  

For the Settlements rows:
- `description` should match `settlement_description` from `va_caution_flags`
- `link_text` should match requested value in https://github.com/department-of-veterans-affairs/va.gov-team/issues/12238
- `link_url` should match `settlement_url` from `va_caution_flags`

Use below to find facility codes
```
select facility_code, version_id from institutions where id = <<institution id from caution_flag row>> 
```

**Comment by zurbergram** [comment]
@delli-gatti-michael @sonntag-adam When testing you cannot use frontend to test Settlement caution flags as these do not have title's at this time

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-13 at 10.42.49 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c8abd723-e045-482c-8e95-a3fa23e31286)
##
![Screen Shot 2020-08-13 at 10.45.00 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5dbb0d95-a120-4080-b615-e6ad1fc9093b)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-13 at 11.12.51 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/35c1e8d9-87c9-4e70-b60f-66435a818d98)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-13 at 11.15.24 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5d602303-eb23-4bed-83bf-71fd73476b8b)
##
![Screen Shot 2020-08-13 at 11.15.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8a695e68-e44e-487b-a880-1864e619da1c)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-13 at 11.18.27 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4be18edb-17ae-4c0e-ab31-5c7e2e188c26)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-13 at 11.19.46 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a4e1a1ca-9735-44b9-a885-5b330f2e6cbd)

**Comment by sonntag-adam** [comment]
in staging, testing passes QA.
