### ISSUE TITLE
Write e2e tests for Cerner content pages - Scheduling

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11355]
## Issue Description
We need to ensure that the following page has e2e tests for the below 2 states.

https://www.va.gov/health-care/schedule-view-va-appointments

User states:

1. In non-prod environments when user does not belong to a Cerner facility, show new unauthenticated content.
2. In non-prod environments when user DOES belong to a Cerner facility, show authenticated content.

---
## Tasks
- [ ] https://www.va.gov/health-care/schedule-view-va-appointments e2e test with axe checks

## Acceptance Criteria
Using Cypress: 
- [ ] https://www.va.gov/health-care/schedule-view-va-appointments e2e test passes with axe checks

**Comment by kelsonic** [comment]
This ticket is blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/11154 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/11239

**Comment by MickinSahni** [comment]
Might end up being substantial work given lack of how much we're able to cover tests with the scripts we write.

**Comment by MickinSahni** [comment]
axe checks already executing for all pages from Drupal automatically 
i.e. unauth content in this issue will be tested as part of that. 
auth content will _not_ be tested by axe checks. but they're similar to unauth. 

moving to sprint 29 until we're in prod and can actually run e2e tests.

**Comment by kelsonic** [comment]
This passed CI in production during yesterday's release, moving to closed 👍 CC @MickinSahni
