### ISSUE TITLE
Flag instances of custom error messages in forms as needing additional review

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#11358]
## User Story

As a VSP team member, I need to know when a VFS team is overriding the default forms error messaging, so that I can ensure the new messaging adheres to VA.gov best practices. 

## Definition of Done
- [ ] Document how to add things to review bot @bkjohnson 
- [ ] Configure review bot to flag custom error messages in forms library as requiring explicit review and approval from VSP @Clark-W-Griswold

**Comment by meganhkelley** [comment]
From Dan:

 OVERALL_REVIEW_COMMENT: >
        # Custom error message found
        Please note that this error message would override the default forms library error message for this page.
        ## What you can do
        Custom error messages will require explicit approval from VSP content & design. This can be flagged during a regular collaboration cycle review or brought to #vfs-platform-support.
      LINE_COMMENT: review page custom error message found

**Comment by rianfowler** [comment]
Does this flag need to be a blocking approval? I don't think the flag for manual review feature supports this yet.

**Comment by meganhkelley** [comment]
Per decision documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/automated_code_quality/08-31-20-manual-review-trigger-decision.md

We are not going to add a manual review trigger ("review bot") for custom form submission error messages.

**Comment by meganhkelley** [comment]
@peggygannon please note the above link & context. tl/dr: we were going to add a "review bot" (a flag when someone submitted a PR) to highlight instances where an app team was using a custom form submission error message in the form, instead of the hard coded error messages. We are *not* adding that review bot for the time being. Our expectation is that custom form submission error messages will be reviewed as part of typical content review in the Collaboration Cycle. 

Let me know if you have Qs, and please tag other folks who need to know about this decision as needed! Thanks

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
