### ISSUE TITLE
[Tech Debt] 526 Claims: BDN Team PIF Errors

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#11351]
## Issue Description
retry the error 
`form526.submit.save.draftForm.PIFInUse: Claim could not be established. Contact the BDN team and have them run the WIPP process to delete Cancelled/Cleared PIFs`

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
we now retry PIF errors and they seem to resolve after multiple retries

![Screen Shot 2020-07-30 at 1 59 33 PM](https://user-images.githubusercontent.com/19188/88957530-f8c23700-d26c-11ea-9bb9-d49404cad1d1.png)
