### ISSUE TITLE
[DISCOVERY] Facility Locator: Pagination 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11364]
## What happened?
Pagination is behaving strangely in Facility Locator (all environments)

## Observations from Prod: 
<details>
<summary>
1.  Pagination is not displayed correctly. It should be left justified under the list of results.</summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bc7c9e4d-0330-4392-9900-9cd6674095a7)
</details>

<details>
<summary>
2. When a user asks for the next page of results, the pagination display does not advance. Page 1 remains highlighted or in the following case, both are highlighted. Sometimes the page does not advance at all, leaving the same list of results. </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/35a1b9ce-5ad6-470f-895a-6bed493f00a2)

</details>

## Specs:
- Browser: Chrome (also observed in other browsers)

## Desired behavior
Pagination should be visually consistent with design systems. 
Page indicators should reflect the actual page of results being displayed.
Page indicator should reflect only one page at a time. 
Page indicator should update when "Next" is clicked. 
Results list should advance with page. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
We are timeboxing this discovery effort to today since this was prioritized mid-sprint. @brangi to share findings on Monday.

**Comment by brangi** [comment]
investigated, closing
