### ISSUE TITLE
[Analytics]  Review and if required update syntax for VISN-19 playbook health service titles [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#11365]
## Story
As a Drupal engineer, data provided on the playbook must be an exact match to data listed in Drupal, so that migration of the playbooks will succeed without a mis-match error.

## Resources
[Analytics VISN-19 Playbooks](https://drive.google.com/drive/folders/1mXSsjBi8ts0pTWRUSfffSV0CmTgY2F0z)

## Tasks
- [x] Review all VISN-19 Playbooks for accurate Health service titles that support both System and Facility health services.

## Acceptance Criteria
* All Systems in VISN-19 have been updated with exact match to Source of truth in Drupal Health Services drop down.

**Comment by ltrombley** [comment]
Cheyenne, Western Colorado, Oklahoma City and Montana are completed.

**Comment by EdwardBoehme05** [comment]
Eastern Oklahoma and Sheridan are completed.

**Comment by lealester** [comment]
Eastern Colorado & Salt Lake City
