### ISSUE TITLE
IA Feedback from Design Intent: CT Filters

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#11361]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Must
- Individual and group labels for filters/controls should be consistent. Individual labels must be consistent and succinct.  If filters/controls are grouped and labeled together on the search results page, they should be grouped and labeled the same on the results page
- The initial search page has a CTA to execute on the search (although if you select something from type ahead it executes automatically) and the search results page does not have CTA  to change results based on selections.  Watch performance on the refresh of the search results page to ensure that auto-refreshes don't cause issues with users who are quickly making selections in filters.  

## Should
- Review/gather feedback on labels on "institution type" and "institution category" - the labels are very synonymous. 

## Consider
- Limiting what data is shown on the search results in the "card".  Not all information can/should be shown on the search results, as the details becomes more cluttered, the harder it will be for users to decipher differences. 
- "Filters" that change/reduce the list of results shown, and "data controls" that change the data on the results shown are intermingled - consider separating these controls so users can clearly filter/narrow their results and then use the data controls to do their comparison 
- Utilize similar input controls where possible - i.e. can radio button filters be be changed to drop lists in order to simplify the interface?

## General Questions:
- If they type in a state in the open text box of the initial page, how does that work with the state drop list in the filter list?

## Definition of Done
* Team acknowledges and responds to feedback in ticket 
* Team schedules follow up conversations with IA as needed

**Comment by amyknox** [comment]
Thanks for the input, @mnorthuis - we'll review and get back to you with any questions.
