### ISSUE TITLE
Content for error message

### ISSUE THREAD

**Issue by psanders86** [department-of-veterans-affairs/va.gov-team#11367]
## Issue Description
When Veterans attempt to submit the 10-10CG form, I want them to receive a nonspecific error message if their form cannot be processed that does not include references to matching Veteran data.

---
## Tasks
- [x] Consult with DEPO and Platform.
- [x] Draft language.
- [x] Consult with security to ensure acceptance.
- [ ] Update design.

**Comment by psanders86** [comment]
Modifying the language on this error message now that we've decided that applicants won't be able to resubmit the form after receiving the error message.

**Comment by psanders86** [comment]
## Can’t process application message ##
#### We didn't receive your online application ####
We’re sorry. Something went wrong when you tried to submit your application. Please review your application to make sure you entered your information correctly. If you think your information is correct, please call the VA.gov help desk at 855-574-7286 (TTY: 711). We’re here Monday through Friday, 8:00 a.m.–8:00 p.m. ET.

Or, you can download and print out your completed online form and mail it to:

__Program of Comprehensive Assistance for Family Caregivers__
Health Eligibility Center
2957 Clairmont Road NE, Suite 200
Atlanta, GA 30329-1647

{end of error message} 


{CTA button} Download your online application
{CTA button} Go back to VA.gov

**Comment by ala-yna** [comment]
Does it make sense to include the help desk/ask if information was entered correctly, given that at this point the user wouldn't be able to go back and change it?

**Comment by psanders86** [comment]
I think it does. We want to encourage them to make sure they're being accurate. I think they can correct the PDF before downloading it.

**Comment by sshein** [comment]
After thinking about it, my 2 cents is that allowing users to go back and telling them to double check spelling is useful because then it will catch the people that may have spelled things wrong. They can just open all the accordions on the review page and double check things. Then they can try submitting again and if there is still an issue, they can download the prefilled PDF.  That said, if the team has already decided they are not allowing the user to go back, we can work with that.  

The language here "We’re sorry. Something went wrong when you tried to submit your application. Please review your application to make sure you entered your information correctly. If you think your information is correct, please call the VA.gov help desk at 855-574-7286 (TTY: 711). We’re here Monday through Friday, 8:00 a.m.–8:00 p.m. ET.

Or, you can download and print out your completed online form and mail it to:"

Makes it seem like there should be 2 actions - "review your application" and "download your application" but then the two CTAs are "download" and "go back to VA.gov" which seems confusing to me.

**Comment by psanders86** [comment]
I don't think we need a button to review the application since the user is already on the review page and can go over everything submitted right there. But I agree with you that the CTAs need to be a simple as possible so we're not confusing the user.

I do like the solution that Jonathan showed me earlier, with a CTA button to download the PDF and a hyperlink to go back to VA.gov.

**Comment by sshein** [comment]
ohhh I didn't realize this error was showing ON the review page. I thought it was a separate page. so sorry. My comments don't apply then.

**Comment by psanders86** [comment]
Hi @gunsch ... In reference to our recent security review https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/117 and the issue you flagged on the error message, please have a look at this proposed language and advise if you have any concerns. Thanks!

### Can’t process application message ###

#### We didn't receive your online application #####
We’re sorry. Something went wrong when you tried to submit your application. Please review your application to make sure you entered your information correctly. If you think your information is correct, please call the VA.gov help desk at 855-574-7286 (TTY: 711). We’re here Monday through Friday, 8:00 a.m.–8:00 p.m. ET.

Or, you can download, print, and sign your completed form and mail it to:

__Program of Comprehensive Assistance for Family Caregivers__
Health Eligibility Center
2957 Clairmont Road NE, Suite 200
Atlanta, GA 30329-1647

{end of error message}

{CTA button} Download your online application

**Comment by psanders86** [comment]
Adding @jonathanjnelson @LinnJS @kevinmirc

**Comment by gunsch** [comment]
My questions / comments are:

(1) Is this still the same error message we show when Salesforce is unable to receive submission? I don't think that to do with "making sure your information was entered correctly.", at which point we're sending Veterans down an unrecoverable path.

(2) If a Veteran calls the VA.gov help desk, what kinds of actions will happen? Can the help desk help that Veteran finish submitting it successfully online? Can they process the submission over the phone? If not, should we just direct them more immediately to print+mail?

(3) "Please review your application to make sure you entered your information correctly. If you think your information is correct" -- this sounds like hinting at the kind of information we're looking to avoid revealing.

**Comment by jonathanjnelson** [comment]
@sshein Originally, I had the error message designed on a separate page. However, Justin informed me that the form builder does't handle errors this way - By default it puts errors on review page and has been hard coded. Therefore, would be large platform effort to change that. 

Made the decision to have the error message on the review page for this release.

**Comment by sshein** [comment]
got it, that makes sense. Thanks for the explanation :)

**Comment by psanders86** [comment]
@gunsch Yes, this is the message that would be used for any failure. If the Veteran gets the error message and identifies an error, they can call the help desk who can do 2 things:

1. Verify that they have filed a 10-10EZ and are in MPI, and 
2. Counsel them to restart the form from the beginning, this time ensuring that their information is correct when they submit it.

If the help desk cannot verify they are in MPI or if the Veteran cannot verify they made an error, then the Help desk can walk them through the process of saving their completed PDF and sending it in.

Either way, we think that the error message is giving the user an avenue to proceed and be successful at submitting the form, either online or via a completed PDF.

**Comment by gunsch** [comment]
Got it. That sounds good to me.

I worry that the first thing we do is to say "go fix your data and try again", if we're also showing this same message for backend failures. But assuming those are rare, and VA / product owners are OK showing this text for those error states, then I'm OK with this.

**Comment by psanders86** [comment]
Thank you!
