### ISSUE TITLE
Update FE template to enable in-body alert component to display on form detail pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11380]
## Update FE template to enable in-body alert component to display on form detail pages

aka trigger and show form detail page alert/banner when data populates a specific field in Drupal `fieldAlert`

**User story:** 
As a Veteran, if there's a form related alert that I need to be aware of, I want to be able to see that on the form detail page. 

**Example:** 
I'm on a health care form, and there's an alert that tells me that I can get free mental health care even if I'm not enrolled in VA health care. Or that a form is going to be retired, so they should use the online tool instead, etc. 

**AC:** 
- [ ] UX design makes recommendation of where in-body alerts should display in the form detail page FE template. (Ryan, Liz)
- [ ] FE engineer updates the FE template based on design recommendation. 
- [ ] If the in-body alert component is enabled on a form detail page/node, the user sees the alert on the preview page in the right location.

**Visual example of a form detail page:**
Note: there are 2 possible page designs, depending on whether a form page has/doesn't have custom data. The in-body alert component should appear in the same location in the FE template for both views if enabled. The common location for an alert needs to look appropriate for both states. 

- With and without all custom content fields: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs#visual-mockups [edited 8/6: consolidated]

**Example of an in-body alert:**
Note: these are the components already available in the CMS. These alerts can be reusable or with unique content. 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/df905ee2-df6d-4fdc-8e01-562680655384)

**Comment by MickinSahni** [comment]
Might've run into this before where the boxes rendered incompletely.
@jenniferlee-dsva  to post an example (with a node id) as well as check with design folks re their recs

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - here's an example node: http://preview-prod.vfs.va.gov/preview?nodeId=5820

/about-form-21p-534ez - Added a DIC Blue Water Navy Vietnam Veteran info alert in Drupal

@andaleliz - Could you take a look at the og ticket info ^ and recommend placement of alert in the FE? 

Note: This can be done post-soft launch, so not urgent.

**Comment by andaleliz** [comment]
Acknowledging receipt! What milestone is this associated with? I see it's not urgent.

**Comment by ncksllvn** [comment]
@swirtSJW would these alert boxes be added under `fieldVaFormUsage`?

**Comment by jenniferlee-dsva** [comment]
@andaleliz - because this is 'scope creep' - FE functionality I forgot to include in the preview tickets, this is put into the form detail pages post-soft launch epic. We don't have a date or specific sprint for the soft launch yet. Lighthouse team is working on updating the forms API to cutover to grabbing data from Drupal. And then our team will need to validate....  And staging review. So probably not before sprint 28, 29.

**Comment by ncksllvn** [comment]
Link to the page in staging - https://staging.cms.va.gov/find-forms/about-form-21p-534ez

It looks like we need to add a new field, `fieldAlert`, into the GraphQL query and then the FE template as well. (Tech detail - we can look at `page.graphql.js` for an example implementation of pulling in `FIELD_ALERT`). Example query response -

![image](https://user-images.githubusercontent.com/1915775/89437972-3a902900-d716-11ea-8aa4-e5a93e94bf60.png)


This should be pretty straightforward. I'll add an estimate to it.

**Comment by jenniferlee-dsva** [comment]
@MickinSahni @ncksllvn @andaleliz - per grooming yesterday, I think this FE work is needed prior to QA, so we can also use this alert UX as a way to display 'invalid' form link use case message. 

So the priority for this is no longer post-soft-launch but pre-QA review.

**Comment by ncksllvn** [comment]
The tech requirements here are met for us to add this into the template. It seems like we only need to decide on position. It seems like just under the name of the form could be a good spot?

**Comment by andaleliz** [comment]
Is there a use case where the invalid PDF and an information alert would be needed?  Or does it just need to be one alert?

I focused on #12181 as it seemed more urgent. Came here, read the description, and failed to read the comments before thinking through the scenario of needed both. 

The solution I provided in #12181 has the alert **replacing** the PDF link. I think having an alert saying "the link is invalid" and still showing the link is bad UX.

But, that is not an appropriate place to just put a general info alert on the page.

My thinking is that info alerts should go immediately under the h1, intro + metadata (those things should stay together), but alerts about invalid PDFS should replace the link.

[This prototype](https://vsateams.invisionapp.com/share/G2YF5AJC845) has all of the possible combinations of all alerts on a page outlined.  Thoughts?

**Comment by ncksllvn** [comment]
I was thinking that too @andaleliz, sounds good. I'll implement it that way but we can change it if necessary.

**Comment by andaleliz** [comment]
@ncksllvn this ticket is really intertwined with #12181 - go by Jen's comments there please, to resolve this issue.

**Comment by ncksllvn** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/1915775/91080223-39666380-e613-11ea-8b46-afd7c7d3da99.png)

**Comment by andaleliz** [comment]
(Not the `you are viewing a draft` right?)

Looks to me like this lines up with Jen's guidance to place the info alert under the main CTA on the page. Thumbs up.

**Comment by jenniferlee-dsva** [comment]
LGTM @ncksllvn

**Comment by ncksllvn** [comment]
This is merged and will be on staging soon

**Comment by ncksllvn** [comment]
Actually I guess staging doesn't matter in this case (CMS preview pages), but this will go out during today's deployment
