### ISSUE TITLE
Create infrastructure for CMS CI Pipeline

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#1138]
CMS team has a separate application that handles the creation of testing environments for each PR in the CMS repo.

We need to create the infrastructure to run this application. They have started a PR to add configuration here https://github.com/department-of-veterans-affairs/devops/pull/5161

More details will need to gathered for the requirements from Elijah but they will include changes to terraform to update security groups and create a load balancer at a minimum.

**Comment by ricetj** [comment]
Done, work will be continued in https://github.com/department-of-veterans-affairs/va.gov-team/issues/1468
