### ISSUE TITLE
Offboarding of Beth Jacobson

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#11387]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Beth Jacobson
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VFS-CMS, Drupal Engineer, last day = 7/17/20, CivicActions
- Please provide any type of access they may have. 
  > SOCKS, DSVA Slack, GitHub
  
 
## AC
 - [x] Remove global/config.yml
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] SOCKS Access removed (if applicable) 
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Or
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by joanneesteban** [comment]
Confirming that Beth didn't have a Google Analytics or Domo account.

**Comment by jbritt1** [comment]
User removal from VA GitHub org submitted: https://github.com/department-of-veterans-affairs/github-user-requests/issues/3366

**Comment by jbritt1** [comment]
PagerDuty access removal not applicable to this user.

**Comment by jbritt1** [comment]
Request for removal from dsva slack workspace: https://dsva.slack.com/archives/C03FECE9K/p1595264956202500
