### ISSUE TITLE
ETL Github labels on Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#11383]
## Issue Description
How might we ETL the labels column from the Github connector so that we can more easily view and our workflows on Domo and ultimately improve our work processes?

---
## Examples
**Label Column in [Domo Dataset](https://va-gov.domo.com/datasources/b9bb9eeb-35c5-458e-951b-2989261ba45d/details/data/table)**

Github Label:
`[{"id":1342519411,"node_id":"MDU6TGFiZWwxMzQyNTE5NDEx","url":"https://api.github.com/repos/department-of-veterans-affairs/va.gov-team/labels/analytics-insights","name":"analytics-insights","color":"E8BCE4","default":false,"description":""},{"id":1342519342,"node_id":"MDU6TGFiZWwxMzQyNTE5MzQy","url":"https://api.github.com/repos/department-of-veterans-affairs/va.gov-team/labels/contact-center","name":"contact-center","color":"ffc9e6","default":false,"description":""}],`

Expected Output:
`analytics-insights` `contact-center`

---

Github Label:
`[{"id":1342519411,"node_id":"MDU6TGFiZWwxMzQyNTE5NDEx","url":"https://api.github.com/repos/department-of-veterans-affairs/va.gov-team/labels/analytics-insights","name":"analytics-insights","color":"E8BCE4","default":false,"description":""},{"id":1360053794,"node_id":"MDU6TGFiZWwxMzYwMDUzNzk0","url":"https://api.github.com/repos/department-of-veterans-affairs/va.gov-team/labels/analytics-request","name":"analytics-request","color":"e99695","default":false,"description":null},{"id":2172231488,"node_id":"MDU6TGFiZWwyMTcyMjMxNDg4","url":"https://api.github.com/repos/department-of-veterans-affairs/va.gov-team/labels/gtm","name":"gtm","color":"e9bfff","default":false,"description":"Google Tag Manager implementation"}],`

Expected Output:
`analytics-insights` `analytics-request` `gtm`

## Acceptance Criteria
- [ ] Documented process on how to ETL Github issues by label

**Comment by bsmartin-ep** [comment]
@joanneesteban -

Looks like we can parse this out in the connector settings.  Under _Parsing_, select the `labels` column and choose "Expand as Array".  We should then have a column called `labels_name`.

This will create several rows for each issue, so we will probably need to do some GROUPing.

![image](https://user-images.githubusercontent.com/62304138/87837738-8f045f00-c862-11ea-989f-745db85238a3.png)

**Comment by joanneesteban** [comment]
@bsmartin-ep this is perfect! And we can group by [issue] number.

**Comment by joanneesteban** [comment]
Thank you for the help on this! Added this fix to [internal Domo FAQ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-internal-faq.md)
