### ISSUE TITLE
[EXPLORATION]: Turn on jsx-a11y ESLint rules

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1139]
Per @jbalboni on the [original issue ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4509) in vets.gov-team repo:

> We have a couple of the rules in the jsx-a11y config turned off that would probably be helpful:

```
jsx-a11y/href-no-hash
jsx-a11y/no-static-element-interactions
```

No hash has 7 errors, the other has 48.

**Comment by 1Copenut** [comment]
@jholton && @rianfowler Has this been implemented? I thought I remembered it being added, but not for sure. If it has, please feel free to close and ping me.

**Comment by rianfowler** [comment]
tagging @jhonnyoddball - @jholton is on the BE team.

**Comment by jhonnyoddball** [comment]
`jsx-a11y/href-no-hash` is disabled as of right now on '.eslintrc' .

`jsx-a11y/no-static-element-interactions` is turned on (inside airbnb linting) but disabled (overridden) on '.eslintrc' 

@1Copenut I'll get to these rules soon

**Comment by jhonnyoddball** [comment]
Something I found out: `href-no-hash` replaced with `anchor-is-valid` in the recommended and strict configs for airbnb. [Change log](https://github.com/evcohen/eslint-plugin-jsx-a11y/commit/a14617528cda23c6c88902ace1d083e4e13ac271)

**Comment by 1Copenut** [comment]
@jhonnyoddball Has there been discussion about turning on the entire `jsx-a11y` plugin? It might be a big effort, with lots of things to fix initially, but is effort worth doing. We'd catch a number of inaccessible code practices during daily work that currently depends on manual review.

Or if it's too large a lift to turn on at once, can we turn on rules one or two applications at a time, using local overrides to our  `eslintrc` file?

**Comment by jhonnyoddball** [comment]
@1Copenut There are some rules from `jsx-a11y` that are already enabled in [airbnb plugin](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js). I'll do an audit for this soon and activate what's needed. I did look into the 2 rules you suggested and they have a lot of errors that we might need to fix before the rule is enabled. That's where you can help me a lot with.

**Comment by 1Copenut** [comment]
@meganhkelley It looks like JSX-a11y is enabled as a plugin for ESLint:
* https://github.com/department-of-veterans-affairs/vets-website/blob/d0a726afbcc256ffbeed3db34f1bb56671d6fd2b/package.json#L194
* https://github.com/department-of-veterans-affairs/vets-website/blob/master/.eslintrc

Seems like we could close this issue ticket unless I'm completely mis-reading the .eslintrc file.

**Comment by 1Copenut** [comment]
Closing this issue based on prior research into ESLint-JSX-a11y already being in our linting process.
