### ISSUE TITLE
CT Filters: VSP Follow-up	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11397]
UI Updates based on VSP Input - Points & Stories
TBD
VSP Design Intent Story: #10996
VSP Design Intent Epic (with Design, IA & Accessibility) https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10996

**Comment by amyknox** [comment]
Handy guide to mobile-first design: https://www.uxpin.com/studio/blog/a-hands-on-guide-to-mobile-first-design/
