### ISSUE TITLE
CT: Staging search functionality issues

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#11408]
When searching in the comparison tool, it is not accurately finding search criteria

Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool
2. Enter a school, location, or employer name: Ohio or Yale
3. Select Search
4. Observe that for Ohio no results show, for Yale it does not find the school.

##
![Screen Shot 2020-07-20 at 10.17.03 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/751fe7d3-7299-4ebd-97f3-87a28a7184ce)
##
![Screen Shot 2020-07-20 at 10.17.22 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0cf5ee0d-7952-4f47-90e1-47caddb077eb)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/685

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-20 at 2.27.19 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4e2b4460-555f-472d-bb05-0d4088f85016)
##
![Screen Shot 2020-07-20 at 2.27.54 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b21d9a7a-8c8b-44d1-bede-b16b3ca3ef68)

**Comment by sonntag-adam** [comment]
In staging. Closing bug.
