### ISSUE TITLE
Offboarding of [Stephanie Orkand]

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11403]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Stephanie Orkand
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Public Website 
- Please provide any type of access they may have. 
  > ex: [ SOCKS, Pagerduty -??]  Google analytics, Slack, GitHub, DOMO, VA email, ect.
  
 
## AC
 - [x] Remove global/config.yml
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] SOCKS Access removed (if applicable) 
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Or
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jenniferlee-dsva** [comment]
@YanaRoy - ^ placeholder for GOV CIO to fill out/complete request. Please make sure Anne Hurley is also officially offboarded. Thank you.

**Comment by joanneesteban** [comment]
Confirming that Stephanie didn't have Google Analytics or Domo access.

**Comment by dginther** [comment]
Confirming that there is no SOCKS or AWS account.

**Comment by dginther** [comment]
Confirming that there is no Pagerduty account

**Comment by YanaRoy** [comment]
submitted issue https://github.com/department-of-veterans-affairs/github-user-requests/issues/3387 to remove Steph off VA GH Organization and removed her from the DSVA Slack

**Comment by ricetj** [comment]
Complete
