### ISSUE TITLE
Update EC prompt on VAOS appt homepage

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11405]
After some research sessions and digging in on specific EC clinical processing flow, we need to update the prompt to the following:

- Update header to: Create a new Express Care request
- Update sub-text to (with bullet list):
"_Do you have a health concern that you need help with today, but it isn't an emergency? Submit a request for a same-day Express Care screening with a VA health care provider._
   _- You can submit your request [Day] through [Day], [Hours] to [Hours] a.m. [time zone]._
   _- A VA health care provider will call you today._
   _- After your screening, we may schedule a follow-up phone, video, or in-person visit or other care if needed.._
- Update button text to: "Request Express Care"

**Comment by jbalboni** [comment]
@lenaecb @rtwell FYI, the hours we get from VATS could be different for every day, so we might need some guidance about how we want to present more complicated cases.

**Comment by lenaecb** [comment]
@jbalboni - yea, I am checking on what is being advised for EC because I do think it's in the best interest of the user to offer different times on different days. That's pretty confusing.

Nonetheless, we'll want to account for this use case. I'll create a issue for that.

Also - we may have one small tweak to the copy here. Getting verification. It's on the last bullet.

**Comment by lenaecb** [comment]
@jbalboni @rtwell @peggygannon 

It looks like part of the existing service we get for our call on whether a facility has express care enabled does not include all dates/times. It only includes times for _today._

We are going to have a new end point that will return all dates/times, but that may take a few weeks for BE to release. 

**So in the meantime, I think we need to how the following for the facility time bullet:**
- Submit your express care request today between [Hours]and [Hours] [a.m] [time zone].

Thoughts on the above?

**Comment by lenaecb** [comment]
@rtwell @jbalboni @peggygannon 

Also, based on the inability to pull future days/times right now for eligible Express Care facilities (we will be able to do this in a few weeks after a new endpoint is released) we need to change the 'inactive' state copy. 

I suggest something like the following, @peggygannon please help make this better:
_VA offers same-day Express Care screening for non-urgent issues. If you are seeing this message, you are outside of the hours for submitting express care requests. If you need to talk to a provider urgently, please contact your clinical contact center or your facility before going in._ 


Current mock for inactive state:
![Screen Shot 2020-07-20 at 5.26.13 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/7b0d53a1-5cf3-4103-88cd-2e422d797018)

**Comment by peggygannon** [comment]
@lenae Where  will user see the in EC inactive state? will this message appear on the appoinments landing page or will it appear  in a modal or pop up?

**Comment by lenaecb** [comment]
@peggygannon - The inactive state shows in the same place as the active state on the appointments landing page. 

We are showing the inactive state to help users understand that the EC offering is only available during certain times. Due to current limitations (which we're fixing with a new endpoint) we can not display future day/times with inactive state.

**Comment by peggygannon** [comment]
@lenaecb @jbalboni @rtwell Recommendations for inactive state is below. (I've also included the 
Express Care inactive state, so we can see the content in context.)  

Question: Are we able to give users a time frame on when to return back to submit an EC request? I think it's important to give user some guidance on when to return... 

Here are some content recommendations. Would either of these sentences be accurate? 

If you want to use Express Care, you can submit a request tomorrow. 
OR
If you want to use Express Care, please check back later. 

INACTIVE STATE

**Express Care isn’t available right now**

Express Care is only available certain hours. With Express Care you can request a same-day screening with a VA health provider for health conditions that aren’t an emergency. *If you want to use Express Care, you can submit a request tomorrow.*
OR
*If you want to use Express Care, please check back later.*

If you need to talk to a provider today, contact your call your VA medical centerhttps://www.va.gov/find-locations/) before going to a clinic.

----------


ACTIVE 
**Create a new Express Care request**
Do you have a health concern that you need help with today, but it isn't an emergency? Submit a request for a same-day Express Care screening with a VA health care provider. 
- You can submit your request today from 1:00 to 5:00 p.m. ET. 
- A VA health care provider will call you today. 
- After your screening, we may schedule a follow-up phone, video, or in-person visit or other care if needed.
{button} Create an Express Care request

------

**Comment by lenaecb** [comment]
@peggygannon @rtwell - we have a request out to the BE team to provide a new endpoint to us for EC that includes dates into the future. But, right now, the only data we have is time for _today_

So, we need to make a slight tweak now to the inactive info to accommodate this current data constraint. I will make a new issue to allow for us to iterate on this prompt that takes into account this new endpoint. 

We do not have a time/day when this new endpoint will be released/available to us for production use.
