### ISSUE TITLE
Update `<Telephone />` with TTY numbers

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#11417]
# Description

The reusable `<Telephone />` component in the [design system](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/telephone/) needs to include the following TTY numbers:

```
800-877-3399
800-877-8339
800-799-4889
866-363-2883
711
```

For each of these numbers, we need a brief description. For example, these are some of the current `<Telephone />` standardized numbers with descriptions:

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/4809db4f-60fe-4563-92bd-6b5fc1ff6afb)

## Acceptance Criteria

- [ ] Comment on this ticket with a brief description for the above TTY numbers.
- [ ] Add the TTY numbers to the `<Telephone />` component's `CONTACTS` module.

## Related
Update `<Telephone />` with TTY numbers #11418

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic Here's what I've got so far:

800-877-3399 - nothing coming up for this one. I am thinking it may be one of the numbers that's been switched out with 711. @RLHecht can you also search to make sure?

800-877-8339 - Federal Relay Service @RLHecht Can you look into this one as well as a double check? It's also showing search results for HUD and other mortgage services specifically.

800-799-4889 - Suicide Prevention Lifeline 

866-363-2883 - Defense Manpower Data Center (DMDC)/Defense Enrollment Eligibility Reporting System (DEERS) Support Office

711 - Telecommunications Relay Service

**Comment by kelsonic** [comment]
Thank you @DanielleThierryUSDSVA! I wonder if `800-877-3399` is actually a typo where they meant `800-877-8339`... Hmm

**Comment by RLHecht** [comment]
@kelsonic @DanielleThierryUSDSVA Yes, that second number 800-877-8339 is Federal Relay Service. Just tried calling it and it took me there.

**Comment by kelsonic** [comment]
Oh that's a good idea, I'm going to try calling 800-877-3399

**Comment by kelsonic** [comment]
Wow I just called 800-877-3399 and it just asked me if I were over 50 years old, I responded "no", then it said "thanks for being part of our survey" and hung up lol

**Comment by kelsonic** [comment]
Can't imagine that number being useful to veterans 🤔

**Comment by DanielleThierryUSDSVA** [comment]
@kelsonic @RLHecht Yeah, it's entirely possible 800-877-3399 is actually just a typo. And yes, let's ditch this one for sure! @kelsonic can you tell us where it currently appears so we can remove from site?

**Comment by kelsonic** [comment]
![image](https://user-images.githubusercontent.com/12773166/88071900-a462dd00-cb31-11ea-9690-7e9996b83817.png)

**Comment by kelsonic** [comment]
Any idea what we should change these 800-877-3399 to? 🙂

**Comment by DanielleThierryUSDSVA** [comment]
Hmm...is there a way to see what the non-TTY number it's associated with? I think that would be the best way to help us solve it.

**Comment by kelsonic** [comment]
So it looks like all of them are the TTY number for My HealtheVet:

```jsx
        <AdditionalInfo triggerText="Call the My HealtheVet help desk">
          <p>
            Call us at <a href="tel:877-327-0022">877-327-0022</a>. We're here
            Monday through Friday, 8:00 a.m. to 8:00 p.m. ET. If you have
            hearing loss, call TTY: 800-877-3399.
          </p>
          <p>
            Tell the representative that you tried to sign in to use the online
            health tools on VA.gov, but received an error messaging telling you
            that we couldn't create an account for you.
          </p>
        </AdditionalInfo>
```

**Comment by peggygannon** [comment]
Hello! @kelsonic I love your table above listing the recurring 800 numbers we use across the site. @DanielleThierryUSDSVA @RLHecht I'm wondering if you all think it would be helpful to have that that 800 number list live somewhere on github?

**Comment by kelsonic** [comment]
Hey @peggygannon, that's actually what this ticket is intended for -- to create a consolidated list of the TTY numbers so that they can never be misspelled across `vets-website` 🙂

**Comment by DanielleThierryUSDSVA** [comment]
Ah, ha! @kelsonic it's definitely a typo. looked up the mhv # and got this in search:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/6330cee0-671a-4372-bd74-6f3580ec0bb4)

We should replace with 800-877-8339

**Comment by RLHecht** [comment]
Great detective work, @DanielleThierryUSDSVA !

**Comment by kelsonic** [comment]
Amazing! Nice work @DanielleThierryUSDSVA! 🕺

**Comment by DanielleThierryUSDSVA** [comment]
Great detective work all around, @kelsonic @RLHecht. We are regular TTY sleuths :)

**Comment by kelsonic** [comment]
PR is up! 🙂 https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/341
