### ISSUE TITLE
[Discovery] A veteran is registered at one or more VAMC facilities/sites, but only one site has EC enabled

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11411]
Use case (account for in current v1.0):  A veteran is registered at one or more VAMC facilities, but only one facility has EC enabled and availability today. 

Example - Veteran is registered at both San Fransisco and Sacramento, but only EC is only offered at San Fransisco which is not the site that the Veteran goes to for care. 

**Not accounted for/needs discussion:**
- Do not indicate to Veterans which Facility (parent or child) they have EC access to - should we?
- Should we ask Veteran to confirm that they want to request EC at that site even though it's at a site they don't normally go to? 
    - Consider asking user to confirm via question - "Express care is a pilot feature currently available for Veterans [name child facility]. Is [name child facility] where you primarily receive your VA care? [Y/N]
        - If yes - continue user to EC flow
        - If no - ask Veteran to confirm they would still like to submit express care request with facility (or something to the effect)

## Acceptance criteria:
- Decision on if we want to indicate to Veteran which site they are getting EC care from
- Decision on if we should allow them to exit out of flow if not desired site (therefore not allowing them to get EC request/care)

**Comment by peggygannon** [comment]
@lenaecb is this for Express Care V2?

**Comment by lenaecb** [comment]
@peggygannon - this will be part of v1.1. 

We are considering v2 to be more of a 'greenfield' approach that we'll move towards in the future. Whereas our current iteration is focused on enabling this feature based on existing services/data.

**Comment by lenaecb** [comment]
Per conversation with @lalexanderson-dsva Lauren, current iteration (which accounts for this use case) is sufficient. 

However, we should discuss this with stakeholders. We are not actively making it aware to Veterans what site they will be getting an EC call back from. This could be confusing for Veterans because they may assume their EC request is going to their preferred VAMC/site, even if it's not going to their actual provider/doctor. 

There is also concern about patient dating getting updated/being up to date if patient is seen at site they do not regularly go to. 

**Recommendation:** Ask about this in the stakeholder demo (if it happens next week, week of Aug 3rd).

**Comment by lenaecb** [comment]
As of today, going to stick with current iteration where we are defaulting to first Facility that has EC enabled. If there are multi-sites with EC enabled at same time, we'll pick based on closest proximity to home address. 

Right now it's our assumption based on stakeholder feedback and business process, that facility name and contact information are unnecessary.

May revisit after EC has been released/being used. 

Closing.
