### ISSUE TITLE
[CONSIDER] Display of address/directions in Facility Locator 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11413]
## Issue Description
There a a few small improvements which should be considered in the display of address and directions in the Facility Locator search results card and on detail pages. The changes to search result cards may be able to be incorporated into the design for the urgent care mashup. (Changes to detail pages for consistency will be included in separate issue)

## Current result behavior
 
![search results.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/281afcda-9d3c-4c17-a269-f93c2e6d3f8f)

## Recommended behavior

1. To support understanding, use spacing to group `Directions` with the address, rather than the phone number
2. Use consistent padding: 24px space above/below phone links
3. Add a label to urgent care phone numbers (such as `**Main number**`) 
4. Improve semantic markup on address/directions
    - Each line should be a <li>
5. Replace the word `Directions` with `Get directions` 
    - this will required approval from the content team

## Design tasks
- As appropriate, incorporate the recommendations above into the new urgent care mashup design. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Adding this as acceptance criteria for that implementation #11460

**Comment by lildziner** [comment]
Reference [UXPin prototype ](https://preview.uxpin.com/f373333a8a59902cbf120c3f00e6d0e13d52fb75#/pages/131031425/simulate/sitemap?mode=i)
![image.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/cd05a020-bddb-4b53-9f47-0e87a0f56caa)

**Comment by davidmpickett** [comment]
@thejordanwood review if still relevant?

**Comment by thejordanwood** [comment]
@davidmpickett Looks like the spacing issue was fixed. Going to close this one too.
