### ISSUE TITLE
CT: Issue when selecting an autocomplete suggestion

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#11436]
## What happened?

In the CT if the user selects an autocomplete suggestion it returns a large amount of results and the selected suggestion does not appear on the first page

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool/
- Go to [CT Landing Page](https://staging.va.gov/gi-bill-comparison-tool/) > type in search box > select a suggested institution
  - notice large number of search results and selected suggestion is not on first page

## Desired behavior
When a user selects an autocomplete suggestion the selected institution appears on the first page of the search results

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13546

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/688

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
