### ISSUE TITLE
IN-PROGRESS - Accessibility Feedback for PW [Campaign Landing Page CMS Template]

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#11432]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Point of Contact

**VFS Point of Contact:** Jennifer (VSA) & Trevor (VSP)

## Description

This ticket will house accessibility feedback for the Campaign Landing Page CMS Template.

## Definition of done

1. Review and acknowledge feedback.
1. Document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions.

**Comment by jilladams** [comment]
CLP is launched, Collab cycle tracked in https://github.com/department-of-veterans-affairs/va.gov-team/issues/11004
