### ISSUE TITLE
S-DVI benefits detail page quick fix: remove apostrophe in intro

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#11447]
Per our style guide, "Service Disabled Veterans Life Insurance (S-DVI)" has no apostrophe after "Veterans." 
Need to remove apostrophe in intro copy and check rest of page. 

- [x] Laura to make change and alert Randi
- [x] Randi to proof and publish

**Comment by lwalsh617** [comment]
On hold until Beth hears back from SME. We want to get confirmation that our style guide is correct as the application has an apostrophe.

**Comment by MickinSahni** [comment]
Moving out of sprint 26 until we hear back from SMEs

**Comment by lwalsh617** [comment]
@RLHecht - Beth got confirmation that there is no apostrophe. Screenshot from email with SME attached. 
![Screen Shot 2020-07-28 at 5 37 40 PM](https://user-images.githubusercontent.com/53535663/88724946-50d82c80-d0f9-11ea-85c8-4a825618aba1.png)
I made the edits: http://preview-prod.vfs.va.gov/preview?nodeId=766

**Comment by RLHecht** [comment]
This page has been published. Note that Laura will ask whether the official name has Life in it (we have it in style guide without). Will revisit when the SMEs review all life insurance pages. Moving to validate. FYSA @MickinSahni

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. FYSA @MickinSahni
