### ISSUE TITLE
Fix copy issues with form detail pages

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#11444]
# Context

https://github.com/department-of-veterans-affairs/va.gov-team/issues/10606#issuecomment-661274194

> There appears to be one FE mapping thing that isn't showing up right now. I don't know if it is a an api bug or if it is due to just an omission during the preview creation. 
> 
> FE preview and FE mapping bugs: 
> 1/ “Non-VA” Related to value should display at the frontend: “A non-VA form. For other government agency forms, go to the GSA forms library.”   <https://www.gsa.gov/reference/forms>
> 
> 2/ When the “When to use” custom content field is empty, the When to use this form H2 should be suppressed/not display.
> 
> Example – form SF 144 http://preview-prod.vfs.va.gov/preview?nodeId=6133
> ![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/c8be6be2-cb14-469b-bdea-1d37849fdedf)
>  
> 
> [https://app.zenhub.com/files/133843125/28494eef-308d-49ff-bdd4-9bb1cae2be02/download](https://app.zenhub.com/files/133843125/28494eef-308d-49ff-bdd4-9bb1cae2be02/download)

# Description

On the form detail pages, there are 2 issues that need to be resolved. Update `non-VA` values to `A non-VA form. For other government agency forms, go to the GSA forms library.” https://www.gsa.gov/reference/forms`. When fields are empty, make sure its respective header is also conditionally rendered.

## Acceptance Criteria

- [ ] “Non-VA” Related to value should display at the frontend: “A non-VA form. For other government agency forms, go to the GSA forms library.” https://www.gsa.gov/reference/forms
- [ ] When the “When to use” custom content field is empty, the When to use this form H2 should be suppressed/not display.
- [ ] When the "When to use" custom content field is empty, the "Downloadable PDF" header is also suppressed. (I.e., just the form link is displayed)  <-- clarification per comment below

**Comment by jenniferlee-dsva** [comment]
@kelsonic - I'm adding the original visual mock up from the other ticket: 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-design-files/form-detail-FE-minimum-content-071620.pdf

A form without custom content fields should look like ^. 

So actually, I should have crossed out the "Downloadable PDF" header as well. Take a look at the mockup for what a page with no custom content should look like. Sorry for the additional clarification.

**Comment by kelsonic** [comment]
Ah interesting, so I guess this condition is already coded in vets-website, it's just likely that `fieldVAFormType` isn't actually `'Non-VA'` but maybe `'non-va'` or something different than we were expecting:

![image](https://user-images.githubusercontent.com/12773166/88340853-c60ec080-ccf9-11ea-8621-44f17f540f53.png)

**Comment by jenniferlee-dsva** [comment]
So here is how that field appears in the CMS interface: 
![image](https://user-images.githubusercontent.com/43381063/88341431-94065a00-cd0b-11ea-976c-85b49c7f2344.png)


If you go to this node preview, you can see the current (buggy) FE: http://preview-prod.vfs.va.gov/preview?nodeId=6133

**Comment by jenniferlee-dsva** [comment]
@kelsonic - There's a Slack thread about this ^ - where the Related to selection is "Non-VA" but the preview is still showing the form administration value (Veterans Affairs, in this instance). 

https://dsva.slack.com/archives/CUB5X5MGF/p1595514227061800?thread_ts=1595428936.051600&cid=CUB5X5MGF

**Comment by MickinSahni** [comment]
Nick to send over an example

**Comment by ncksllvn** [comment]
Here we go!

http://preview-staging.vfs.va.gov/preview?nodeId=6133

```
fieldVaFormName": "Statement of Prior Federal Service",
    "fieldVaFormTitle": "Statement of Prior Federal Service",
    "fieldVaFormType": "non-va",
    "fieldVaFormUrl": {
        "uri": "http://www.opm.gov/forms/pdf_fill/sf144.pdf",
        "title": null,
        "options": []
    },
```

I think we just need to adjust the template to check `fieldVaFormType` against `non-va-` whereas right now it's checking for `Non-VA`.

**Comment by kelsonic** [comment]
@ncksllvn Thank you so much!! Adding that to the PR 🔥

**Comment by kelsonic** [comment]
PR is merged! Following deployment today we can validate + close! 🙂

**Comment by MickinSahni** [comment]
Validated!
