### ISSUE TITLE
[KEYBOARD]: main nav accessibility -- tabbing in small screens

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1144]
## Description

From migrated issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/8421

Not sure how much of a problem this will be, but it's a thing: When we're in a second-level menu (VA benefits and health care > Disability, for instance), tabbing after the end of the menu is reached will go "up" a level and focus on the next item in the first-level menu (Explore benefits). On large screens in which both levels are shown, this may make sense, but on small screens, it's a bit awkward since we're still only showing the second level.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a keyboard user who has the screen zoomed in, I want focus to remain in the expanded menu so I understand where I am on the page at all times.

## WCAG or Vendor Guidance (optional)
* [Focus Visible: Understanding SC 2.4.7](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html)
* [Focus Order: Understanding SC 2.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html)

## Screenshots or Trace Logs

![Screen Shot 2019-08-20 at 1 44 19 PM](https://user-images.githubusercontent.com/934879/63375120-c6b40f80-c350-11e9-957f-a9ffaa20dde8.png)

**Comment by rianfowler** [comment]
steps to reproduce: 
1. load mobile view of mega menu
2. navigate with keyboard to 2nd level menu

expect behavior: opening the 2nd level menu should focus the first item

**Comment by jhonnyoddball** [comment]
Testing `activeElement` in [devtools instructions](https://developers.google.com/web/tools/chrome-devtools/accessibility/focus)
