### ISSUE TITLE
IA Feedback - Design Intent - VRE/Chapt 31

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#11441]
## Description

This issue describes IA feedback

Feedback framework
- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

**MUST**
- Review the purpose/intent of the wizard.  In other uses, the wizard's purpose is to route users to the correct version of a form - i.e. in Education there are 6 different education benefit forms - the user has indicated that they want to apply, so the wizard sends them to the right form.  In the Ch31 and Ch36 forms, the wizard appears to be validating eligibility and asking if they are "interested in applying".  Using the wizard to vet eligibility isn't necessarily incorrect, but its a different type of use, and wondering if this is the right placement if that is the focus. Would love to walk through these flows with you in detail. 

**SHOULD**

**CONSIDER**

## Definition of Done
- [x] Feedback is reviewed and acknowledged by team 
- [x] Decisions and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by jason-gcio** [comment]
@mnorthuis - Thanks for the note, much appreciated and yes, we would love to chat more on the wizard content.  It came directly from stakeholders so they might be interested in streamlining as well.

**Comment by mnorthuis** [comment]
@jason-gcio @sporeboy One other "consider" would be potentially eliminating or rephrasing the last question in the wizard flow.  Given they have landed on the application, their interest could be inferred.

**Comment by jason-gcio** [comment]
@mnorthuis - can we put the explicit urls in this ticket?

**Comment by sporeboy** [comment]
Wizard placement was reviewed; the location will be the intro screen of the 28-1900 form.

The text of the wizard is under review. Text suggestions will be made with an understanding of its location on the initial tool screen, and the ongoing confusion between the 28-8832 and 28-1900 forms. Content revisions could include links to other resources.

The team discussed the final wizard question ("do you want VRE counseling"), and the decision was to leave it until testing.
