### ISSUE TITLE
Repeating related links component on schedule appointments page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#11465]
## What happened?
The related components link on the schedule appointments page repeats twice.

https://www.va.gov/health-care/schedule-view-va-appointments/

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/35fe5eda-e824-405d-9d61-a80f2a1bb333)

## Desired behavior
Component should appear once.

## Acceptance Criteria
- [ ] Component appears once on live site

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. I happened upon this bug. Could you assign out/work with content team to fix? Thanks!

**Comment by RLHecht** [comment]
This is now fixed. The related links were in the react widget, so I deleted the second set of related links that were in Drupal. Moving to validate and will close after tomorrow's deployment.

**Comment by RLHecht** [comment]
This is now fixed on the site. Closing ticket. FYSA @MickinSahni
