### ISSUE TITLE
[Discovery] Explore using Dependabot for automated dependency PR's

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#1146]
https://dependabot.com/ 

Dependabot automatically creates pull requests to keep our dependencies secure and up-to-date and we should consider using it in at least `vets-api` `vets-website` as a way to keep our dependencies secure and up to date.

This is a free tool that would automate the process of updating our dependencies (Rails, Testing Framework, Job Processing, All of the open source libraries) and provides a better description of what it is.  PR suggestions would be presented to us and we would be able to decide if we wanted to merge that or not.

## Acceptance Criteria
- [x] Decide and document if we want to do this at all, if so proceed to next step.  If not, document reason not to in this issue
- [x] Sign off on the documentation from other tech leads
- [x] Implement the change

**Comment by annaswims** [comment]
example Dependabot PR (currently enabled for "automated security updates" by gihtub, but we could use it for more than security)

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/514

**Comment by annaswims** [comment]
@LindseySaari I added you to the list of vets-api admins so that you can work on this but the dependabot app has already been added to vets-api

![Screen Shot 2019-12-12 at 9.45.47 AM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/1d5fb8ed-ce35-4bb0-89a1-3e5661280557)

**Comment by LindseySaari** [comment]
**Dependabot Pros:**
Nicely formats Changelog / Fixes in a PR
Automatically keeps track of updates (This can be tedious if not nearly impossible manually) 
A great reminder if anything, we can always deny the PR 
Security/Up to Dateness 
Free tool
https://seankilleen.com/2019/07/automagically-update-your-package-dependencies-with-dependabot-for-free/

**Dependabot Cons:**
Gem hijacking - https://withatwist.dev/strong-password-rubygem-hijacked.html
Lots of upfront PR approvals

**Comment by LindseySaari** [comment]
Currently there's a issue with passing the sidekiq key to dependabot. First solution was to set up a GH secret with the sidekiq enterprise key value pair, but this solution was unsuccessful:  https://app.dependabot.com/accounts/department-of-veterans-affairs/update-logs/17717531

**Comment by kfrz** [comment]
Closing this because you rockstars @LindseySaari and @annaswims have pushed this over the goal line! :party:

**Comment by YesThatAllen** [comment]
This issue comes up as the first result on google for setting up dependabot & sidekiq pro/enterprise. 

Dropping a clue as to how dependabot was taught to work with the key-value pair would be pretty awesome, if possible.

**Comment by annaswims** [comment]
we added a config variable at https://app.dependabot.com/accounts/department-of-veterans-affairs/config-variables
<img width="789" alt="Screen Shot 2020-06-30 at 12 23 22 PM" src="https://user-images.githubusercontent.com/19188/86151432-b3bfaf00-bacc-11ea-941e-011d0ba14c69.png">

Another thing to note is that github runs a dependot for security issues and we were running an additional dependabot fo the rest.  The screenshot was for the second dependabot but you might be able to add something to github secrets for the security bot.
