### ISSUE TITLE
CT: Update Post-9/11 GI Bill benefit rates in advance of 8/1 rate change

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11472]
As someone who wants to utilize my GI Bill benefits, I need to know the most accurate benefit rate so that I can make an informed decision about how best to utilize my benefits.

## Assumptions
1. These changes should be completed behind a feature flag #11534
2. These updates need to be live on production on 7/31/2020
3. These rates only apply to post-9/11 GI Bill benefits (CH33)

## Acceptance Criteria
1. The benefit rates included in the Cumulative Post-9/11 active-duty service dropdown on the Comparison Tool landing page have been updated to reflect the new rates that go into effect on 08/01/2020 (see SA1)
1. The benefit rates included in the Cumulative Post-9/11 active-duty service dropdown on the Comparison Tool search results page have been updated to reflect the new rates that go into effect on 08/01/2020 (see SA1)
3. When the benefit rate on the Search Results page is changed, the values displayed for "You may be eligible for up to" change in accordance with the new values. 
1. The benefit rates included in the Cumulative Post-9/11 active-duty service dropdown on the Comparison Tool institution profile page have been updated to reflect the new rates that go into effect on 08/01/2020 (see SA1)
5. When the benefit rate on the institution profile page is changed and the "update benefits" button is clicked, the values displayed for "Your estimated benefits" change in accordance with the new values. 
6. The learn more content for the dropdown on the landing, search results, and institution profile pages has been updated to reflect the content captured in SA2. 

## Supporting Artifacts
1. The dropdown old>new values for the benefit levels to be displayed in the CT can be found in this document: [NewBenefitLevelValues_08012020_dropdownValues.docx](https://app.zenhub.com/files/133843125/8293adde-9daa-4bfd-9932-327d0bd2039a/download)
2. Learn more content: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/design/content-doc.md#cumulative-post-911-service
3. The benefit levels should reflect the numbers found on page two of this document: 
https://benefits.va.gov/gibill/docs/fgib/Post9-11_benefit_levels_postcard.pdf
4. New benefit rates as provided by EDU on 7/21/20: ![Screen Shot 2020-07-21 at 4.27.36 PM.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/a85c9845-23a5-4cc8-8f4e-39a849f2f15f)

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13578

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-24 at 11.50.08 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cb6d9267-a1e4-45a9-bbee-e16a12f47149)
##
![Screen Shot 2020-07-24 at 11.51.10 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9e0bb468-7853-4b4e-a3a1-e3bd1d79e766)
##
![Screen Shot 2020-07-24 at 11.58.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2ac1bebd-5536-4526-85ab-8a9dcf6bf380)
##
![Screen Shot 2020-07-24 at 11.51.41 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1e0e6426-154d-4f55-a243-a017311e183d)
##
![Screen Shot 2020-07-24 at 12.01.24 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3fac76c6-9cdc-4123-a274-a6c927ed4dab)
##
![Screen Shot 2020-07-24 at 12.01.47 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/fe3a348d-8880-49a9-a703-374c59fb811b)
##
![Screen Shot 2020-07-24 at 12.01.58 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/680c6808-5d8a-458b-a68b-3bdce599a96c)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/573&group_by=cases:section_id&group_order=asc

**Comment by amyknox** [comment]
LGTM

**Comment by sonntag-adam** [comment]
Closing story.
