### ISSUE TITLE
Ramp up Traffic to 100% for Medical Device Reordering Tool 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#11475]
Hi Wonderful PW Team - We er close to 100 orders on MDOT - can you please ramp up the traffic to 100% -we are going to hold here for a week and then redirect from eBenefits

**Comment by kelsonic** [comment]
Hmm, I don't have access to Flipper (assuming that's how this is done) so think we'll have to wait for Nick tomorrow 🙂

**Comment by kelsonic** [comment]
So it sounds like MDOT is already at 100% traffic since it wasn't implemented with flipper, so this ticket is already completed! 🎉 lol

**Comment by leahkeeler** [comment]
the best kind :) yikes... well it all ended well so... closing
