### ISSUE TITLE
Create new redirects template for www.va.gov

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#1147]
Right now www.va.gov redirects are stored in `react-routes.yml` and are used in this template `base-redirects.conf.j2` to generate `base-redirects.conf` which is included in the revproxy nginx config. Probably the easiest way forward is to replace that base-redirects.conf file with a file that was generated with redirects from drupal.

So when "switching on" the use 'drupal as a source' we must be sure that the drupal request is being made by including the `deployment_cms_redirects_graphql_url` variable in the deployment config and changing the source of the template that generates the base-redirects.conf file to point to the new template.

We also need to add a filter to transform domains to lower environments. I don't know if this is strictly necessary for www.va.gov but will be in the future for sure. Since the same data is coppied down from higher envs in drupal we can't have separate data for each environment. So we will just have the same redirects for all environments and we will take upon ourselves to update the domain to match the environment. So for example with www.va.gov, the function will take as parameters the production domain and the environment and return the corresponding domain for the given environment. (www.va.gov, dev) -> dev.va.gov or (www.pittsburgh.va.gov, dev) -> dev.pittsburgh.va.gov This filter filter probably wouldn't be used for www.va.gov but it is a fairly small change that will used for other domains.

- [ ] create new template config file
- [ ] create new filter to handle domain changes per environment

**Comment by ricetj** [comment]
Done
