### ISSUE TITLE
[COGNITION]: VAOS Appointment Tabs - CONSIDER adding SR-only text to the visual tab labels

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#11470]
## [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The tabs for upcoming, past, and Express Care appointments have had their visual labels shortened for better fit on mobile. In testing this afternoon, I found myself wanting to hear "Upcoming appointments" even though we have the full heading spelled out in an H2 above. I'd like to consider adding SR-only text to the tabs.

cc @rtwell for situational awareness

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] As a screen reader user, I would like to hear "Upcoming appointments" or "Past appointments" read aloud when a tab took focus.

## Steps to Recreate

1. Start a screen reader of your choosing
1. Log into staging.va.gov and navigate to https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
1. Tab or arrow down until you settle on the "Upcoming" tab, and listen to the announcement
1. Did you understand or remember what Upcoming was related to?

## Possible Fixes (optional)

Adding a single line span to the `<a>` tags should do the trick:

```diff
<li role="presentation" class="vads-u-margin--0">
  <a
    id="tabupcoming"
    aria-selected="true"
    role="tab"
    class="vaos-appts__tab vads-u-text-align--center vads-u-color--gray-dark vaos-appts__tab--current"
    href="/health-care/schedule-view-va-appointments/appointments/"
    aria-controls="tabpanelupcoming"
-   >Upcoming
+   >Upcoming <span class="vads-u-visibility--screen-reader">appointments</span>
  </a>
</li>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2020-07-21 at 2 49 24 PM](https://user-images.githubusercontent.com/934879/88101997-7b0f7480-cb64-11ea-8c4b-ff33ee45767f.png)

**Comment by jbalboni** [comment]
I think we must have done this work as part of another ticket. We currently set an aria-label in our tabs with the "appointments" suffix. Closing.
