### ISSUE TITLE
Public Websites [MVP learning center templates]: About

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#11494]
This is a subtask of Accessibility feedback - Design intent collaboration - Public Websites [MVP learning center templates]
#11386

![image](https://user-images.githubusercontent.com/12564977/88177992-b018d700-cbf7-11ea-833b-d9e85ac73d6a.png)

1. Consider a See more/less component to expand long text areas for all viewports, and especially mobile

**Comment by andaleliz** [comment]
This is something to consider, specially for mobile.  It could kick in after a certain character amount and if there are multiple h2s on the page.

Will content authors have the ability to use accordions on the About template? That's another, sort of similar option...but then it's kind of an FAQ page..

**Comment by andaleliz** [comment]
talked w/ Ryan, we are not doing this. It's an interesting idea but these are like wikipedia pages and they're just going to be long. With the back to top, we'll be okay.
