### ISSUE TITLE
[Design] MVP learning center - Explore solutions for tags on mobile

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#11491]
## Design exploration 

- how will these tags look on mobile when they get long (likely wrap on two lines)?
- how can we make sure the tags communicate interactivity?
-  how might topics/audience collapse, depending on the limit of topic tags that can be applied?

Acceptance criteria

- [x] Create mock-ups for mobile showing how tags will look for MVP
- [x] @rtwell, @jenniferlee-dsva, @andaleliz to review
- [x] Review w/ @jenstrickland 

## Background
This is a subtask of Accessibility feedback - Design intent collaboration - Public Websites [MVP learning center templates]: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11386

![image](https://user-images.githubusercontent.com/12564977/88174695-b22c6700-cbf2-11ea-9e3d-2c05c4da7a38.png)

### Original feedback from Design Intent epic #10955 
1. Provide guidance for what these tags do, how to use? At a minimum for non-sighted users.
2. What does the tag result design look like in smaller viewports, 600 pixels and less?
      - Consider if some items could collapse, such as how Google provides in their mobile web app.
      - For longer tag items, they may not fit within a 320px wide viewport. Is it okay if they are cut off by the viewport?

**Comment by andaleliz** [comment]
>Consider if some items could collapse, such as how Google provides in their mobile web app.

@jenstrickland, I'm not familiar with this example. [Is this the app](https://apps.apple.com/us/app/google/id284815942) you're talking about? If so, I'll download and check it out.

**Comment by andaleliz** [comment]
>What does the tag result design look like in smaller viewports, 600 pixels and less?

@rtwell do you have any existing mobile variations for these designs? Meg Peters asked about our plans for testing mobile previously. Wasn't sure how to answer that...

**Comment by jenstrickland** [comment]
> > Consider if some items could collapse, such as how Google provides in their mobile web app.
> 
> @jenstrickland, I'm not familiar with this example. [Is this the app](https://apps.apple.com/us/app/google/id284815942) you're talking about? If so, I'll download and check it out.

@andaleliz I'm referring to the Google web application, as it works on mobile. Here's a screenshot of the collapsed areas. 

![IMG_8509](https://user-images.githubusercontent.com/57469/88308872-9224a280-ccdb-11ea-82e5-7099ccec39b8.PNG)

**Comment by andaleliz** [comment]
Thank you! That's how Google looks in a web browser, so I must not need to download any applications.  

So you are suggesting to collapse the tags for each search result? Using the above an example, where it says `Cost`, ours would say `Topics` and then the arrow would expand to reveal the lozenges?

Just want to be sure I fully understand your suggestion.

**Comment by jenstrickland** [comment]
Yes, there would be two collapsed areas on smaller viewports. 

[**Topics -------------- V**]  <-- expand to reveal the lozenge items in a container as shown in the Google screenshot
[**Audience ----------- ^**] <-- expanded to reveal items
[ [item a](url)   |  [item b](url) |  [item c](url) ]
[ [item d is longer](url)   |  [item b](url)]

**Comment by andaleliz** [comment]
Character limit will be enforced in Drupal
@andaleliz to explore how will these tags look on mobile when they get long (wrap on two lines), and explore how topics/audience collapse, depending on the limit of topic tags that can be applied

**Comment by andaleliz** [comment]
No need for an additional info component on mobile for V1 yet (from convo w Ryan)

**Comment by andaleliz** [comment]
talked to @rtwell today; he has this underway and will take care of this.

**Comment by brianalloyd** [comment]
Old ticket in backlog, closing this out in support.
