### ISSUE TITLE
Import redirects to Drupal

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#1149]
In order to properly test the new config changes from start to end we need proper redirects in the lower environment of the CMS. There are already some in there but they will need to be removed because we will be following a new format. Also, since data is moved from the prod down to staging and dev, data in the lower environments will be overwritten occasionally. Surely the need will arise to import redirects to drupal on more than one occasion.

The script to import, ideally, will take as input a list of redirects and use a graphql query to put the redirects into drupal.

The format needs to be as follows (pending update):

| Item          | Format                            | Example                 |
|---------------|-----------------------------------|-------------------------  |
| src           | full domain with path             | www.va.gov/source       |
| dest          | protocol and full domain and path | https://www.va.gov/dest |
| matching type | one of ...                        | prefix                  |

UPDATE:
The Drupal redirects plugin provides some mass import functionality via csv file. So we can create a small python script to convert from yaml to csv.

**Comment by ricetj** [comment]
@tskinn to update.
