### ISSUE TITLE
MVP learning center: videos template for desktop and mobile

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#11497]
Create desktop and mobile versions of the learning center `media list - videos` template.

**Acceptance Criteria**
- [x] Update design of video template page (desktop + mobile)
- [ ] @jenniferlee-dsva @rtwell and @ncksllvn to review
- [ ] refine based on meeting of the minds ^ 

**Background:**

This is a subtask of Accessibility feedback - Design intent collaboration - Public Websites [MVP learning center templates]
#11386

![image](https://user-images.githubusercontent.com/12564977/88179754-5a91f980-cbfa-11ea-9f14-b93795831ab2.png)

### [Progressive enhancement](https://alistapart.com/article/understandingprogressiveenhancement/) specifications recommendations — would like to review with Ryan

1. Base experience: Link the title of the video as a view video link with the play icon — See design system work-in-progress: department-of-veterans-affairs/vets-design-system-documentation#152

2. Enhancement step 2: Link title and image thumbnail

    - image file size max of 50 kb
    - set height & width size.
    - title link would include styling as noted in #1, to indicate that it is going to Youtube.
    - Page weight should not exceed 1.5 MB.

3. Enhancement step 3: Under certain parameters, load an embedded video <= need to investigate further.

    - Deliver embedded video only if user is connected to wifi
    - Video only plays on user action
    - Video must be able to be paused (Youtube embedded player does have these settings; ensure auto-play is not selected)
    - Are there any constraints on the code that YouTube automates for embedded video? If not, we can provide semantic structure.

**Comment by andaleliz** [comment]
I _think_ what you are saying, @jenstrickland,  is that the video title, and image, should be a link to YouTube **unless** the user is connected to Wi-fi (or other non-cell data internet source), in which case then it could be an embedded video.  Do I have that right?

**Comment by jenstrickland** [comment]
**base experience**
The first deliverable would be the linked video title text, as follows, perhaps inside a shaded box created with HTML.

```html
<a 
  title="Go to video about VA disability compensation" 
  class="video-link" 
  href="https://www.youtube.com/watch?time_continue=3&amp;v=xE0LzeRgdAk" 
  target="_blank" 
  rel="noopener ">
    <i aria-hidden="true" role="img" class="fas fa-play-circle vads-u-padding-right--1"></i>
      View video about VA disability compensation <dfn>on Youtube</dfn>
</a> 
```

**enhancement** 
Next, enhance the experience with a video thumbnail image.
Trevor suggested using a [responsive image technique](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images). This would require art direction of images, that is outside the capabilities of content creators. They will not be able to art direct an image for small viewports, another for middle, and another for desktop. Instead, we could add in an image, after the page loads to fill in a shaded box that is the dimensions of the image. 

Another treatment might be to only load the image at a certain width. Visit [Floodsmart.gov](https://www.floodsmart.gov/) and resize your browser. Watch the image of the people be replaced by a textured svg graphic. This uses a tiny vector graphic repeated in the background, and then replaces it with an image at a dimension that we can expect the user has sufficient connectivity.

```html
<a 
  title="Go to video about VA disability compensation" 
  class="video-link" 
  href="https://www.youtube.com/watch?time_continue=3&amp;v=xE0LzeRgdAk" 
  target="_blank" 
  rel="noopener ">
    <i aria-hidden="true" role="img" class="fas fa-play-circle vads-u-padding-right--1"></i>
      View video about VA disability compensation <dfn>on Youtube</dfn>
  <img 
            srcset="va-disability-compensation-480w.jpg 480w,
             va-disability-compensation-800w.jpg 800w"
            sizes="(max-width: 600px) 480px, 800px"
            src="va-disability-compensation-800w.jpg"
            alt="Director Wilkie speaking about disability compensation"
  />
</a> 
```

**next enhancement, embedded video(s)**
The third option of including an embedded video requires additional technical discovery. Ryan documented notes from our discussion, and we can discuss further.

**Comment by andaleliz** [comment]
Thanks, that information is super helpful @jenstrickland.

**Comment by andaleliz** [comment]
Ryan has a mock-up w/ Jennifer's suggestions - free to explore the designs.  We are not sure if the MVP will include this template; need to figure that out to prioritize this issue.

Not sure about styling for `show more`. Look into it. prob follow pattern on landing page.

In phase 3, f/u w/ @jenstrickland if that's when the link becomes the plain h3 and the image becomes the clickable thing, or does that happen in phase 4.  Also, is it a problem for the h3 to NOT be clickable in phase 4?

**Comment by rtwell** [comment]
## progressive enhancement phases 1 -> 4 (left to right):

![image](https://user-images.githubusercontent.com/12564977/88421049-d6847100-cdb5-11ea-9e7a-7de52b1dd9b1.png)

**Comment by jenstrickland** [comment]
1. For phase 1 and 2, we need to communicate the difference in the View Video links. There is [documentation available for that](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340) — also noted above. Having the icon conveys that this link is different. 
1. If an image is going to be lazy loaded, the recommendation is to use the shaded box as shown above, in order to not have movement on the page once an image appears. This is similar to the shadow pattern used when Facebook is loading content. It provides a hint that something is coming, while deferring impact until the rest of the content is available since the image is decorative / marketing pizzazz.

**Comment by rtwell** [comment]
oh shoot @jenstrickland i did not see those comps! I will update. have a great weekend!

**Comment by jenniferlee-dsva** [comment]
Carried this over to 1.1 epic for FE work

**Comment by jenniferlee-dsva** [comment]
full set of CMS meta data functionality will not be ready in 1.1, so we can implement the FE of Videos article template after Dec. 

(In 1.1, they will work on brining over the youtube video data + title. Post 1.1, they will add the other meta data we need for this template: video duration + video youtube description + video youtube publication date)

**Comment by andaleliz** [comment]
@jenniferlee-dsva and/or @rtwell is more design work needed for this? I see the `update designs for mobile + desktop` box checked but afaik this hasn't been completed and I don't see the mock-ups on the Mural board.

**Comment by jenniferlee-dsva** [comment]
Hi @andaleliz and @rtwell - FE is blocked on video template until the CMS team has bandwidth to host YouTube meta data that the FE needs to pull. So we do not need the mobile designs in 1.1 after all. 

I've put this ticket into the icebox in Zenhub.

**Comment by andaleliz** [comment]
Removing myself since I'm no longer on the team; pinging @brianalloyd for visibility so this work is tracked if needed.

**Comment by brianalloyd** [comment]
Thanks @andaleliz appreciate the the pass.  @callen2563 let's review and discuss during next grooming session.

**Comment by brianalloyd** [comment]
Adding in comments that clarify the authoring intent for the video component:  Slack Thread Convo [HERE](https://dsva.slack.com/archives/C52CL1PKQ/p1615399853364300)

**Comment by FranECross** [comment]
Closing as a no op
