### ISSUE TITLE
Public Websites [MVP learning center templates]: Media list - images

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#11496]
This is a subtask of Accessibility feedback - Design intent collaboration - Public Websites [MVP learning center templates]
#11386

![image](https://user-images.githubusercontent.com/12564977/88178484-785e5f00-cbf8-11ea-8e77-cb36fbe6982f.png)

1. The inline keyword search on the Media List view could be challenging. Do users know this is a subset search? Where do the search results go? Does this shorten up the list to match keywords only? How do I clear it? How do we distinguish it from the "full" learning center search?
2. Similar improvements/affordances for search could be gleaned from the Search interaction work, summarized at the top of the Learning center home page #11490

**Comment by andaleliz** [comment]
I share Jennifer's concerns about the inline keyword search.  Was a filter considered, instead of a search? I think the idea of it is that it would act as a filter, so maybe it's just a matter of relabeling, or offering set refinements instead of a keyword.

**Comment by andaleliz** [comment]
Nothing to do for this now, because we're not launching this with MVP. 

Will tackle in future versions, when we can dig into this page more.
