### ISSUE TITLE
Finalize Iteration - EC prompt on homepage

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11507]
### We need to do another iteration on the EC prompt on the homepage to factor in the following:
- varying Express Care times per facility (they do not offer consistent times across days due to staffing)
   - Need to account for VATS configuration being different every day for a given facility. Right now our current prompt on the homepage assumes facilities are offering a consistent time window each day.
- when a Veteran has more than one facility with EC enabled today
- the fact that Veteran's may be eligible for EC with a site they are registered at but no long go to
- Kathy wants use to put out there that we will be returning your call within an hour - this is a requirement for VAMC's who choose to use EC
- Need to update EC button on homepage

Need to consider these things for both the 'active' and 'inactive' states of EC

**Comment by lenaecb** [comment]
@peggygannon - adding your latest for the active and inactive states for the EC prompt on the homepage to this ticket. 

-----
**ACTIVE STATE:**
Create an Express Care request
Talk to a VA health care member today about a condition or symptom that’s not urgent and doesn’t need emergency care. This new Express Care option is available from [hours] to [hours][a.m. or p.m.] [time zone].
{button} Create an Express Care request

**INACTIVE STATE:**
Express Care isn’t available right now
Express Care lets you request a same-day call with VA health care member to discuss a condition or symptom that’s not urgent and doesn’t need emergency care.
Express Care is only available certain hours. If you want to use this option, you can submit a request tomorrow OR check back later…
need guidance on if we can tell Veterans when to return to use Express Care

If you need to talk to a VA health care member today, please contact your call your VA medical center(https://www.va.gov/find-locations/) before going to a clinic.

@rtwell fyi for those mock updates

**Comment by rtwell** [comment]
I think we could include the time during the inactive state, that way we'd be able to tell folks why it's not available. My second grader attempt would be something like:

**Express Care isn’t available right now**
Express Care lets you talk to a VA health care staff the same day to discuss a symptom that’s not urgent and doesn’t need emergency care. **Express Care is only available 1:00 to 5:00 p.m. ET today**. Check back tomorrow for availability.

**Comment by rtwell** [comment]
actually, I wonder if the availability time should be listed first (and not bold)

**Comment by rtwell** [comment]
## Active

![image](https://user-images.githubusercontent.com/12564977/88298614-600d4380-cccf-11ea-9e23-8366e34ff40e.png)

## Inactive

![image](https://user-images.githubusercontent.com/12564977/88298645-6b606f00-cccf-11ea-9b53-516dcaab325f.png)

**Comment by peggygannon** [comment]
Hello: trying to catch instances of when we say a VA health care member. 

We're changing it to **VA health care staff** (removing the "a" )

**Comment by rtwell** [comment]
i think i caught them all on the prototype: https://vsateams.invisionapp.com/share/BVY4QCOJM4U

**Comment by peggygannon** [comment]
Yes, thank you! looks good

**Comment by lenaecb** [comment]
@peggygannon @rtwell - for the inactive state - a user may log into VAOS and get the inactive state before the window is live. So, may login at 9am and see that the window isn't open till 1pm. 

To account for this, should we change the last sentence to something more generic like - "Check back later during the times specified." or something

But even that feels like it doesn't work because they could come back the next day and the times are different.

Thoughts?

**Comment by peggygannon** [comment]
@lenaecb @rtwell Yes, agree. 

I recommend this: 
To use Express Care, check back during the time shown above.

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/88420657-39c1d380-cdb5-11ea-9c55-2d44da69756f.png)

**Comment by lenaecb** [comment]
Great! I like these iterations! I am going to go ahead and create the dev tickets to update both the active and inactive states for this prompt now. 

Closing out this ticket.
