### ISSUE TITLE
Document issue tracking location in devops repo README

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#11506]
The [devops repo](https://github.com/department-of-veterans-affairs/devops) README has a bunch of great information about who to contact regarding problems or requests.

A user outside the @department-of-veterans-affairs/vsp-operations team who looks at the README might reasonable expect to create issues in the repo's [issue tracker](https://github.com/department-of-veterans-affairs/devops/issues).

However it seems like the correct place for the operations team to track & respond to issues would be: https://github.com/department-of-veterans-affairs/va.gov-team/issues#workspaces/vsp-5cedc9cce6e3335dc5a49fc4/board?labels=operations&repos=133843125

Is this correct, and if so can it be added to the README?

**Comment by gmaciolek** [comment]
@ricetj is this an update your team could make to the devops repo README?

**Comment by ricetj** [comment]
We turned off the ability for folks to make issues in the DevOps repo. Will also update the readme

**Comment by mchelen-gov** [comment]
hello, it looks like the readme PR is still in progress: https://github.com/department-of-veterans-affairs/devops/pull/7309
