### ISSUE TITLE
Adjust View Payments URL 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11509]
## Goal
Per IA recommendation's the url for View Payments so that Veterans can find and use it easier.

## Considerations
- https://staging.va.gov/va-payment-history/ is the landing page that will have its button link changed to VA.gov away from EBN

## Tasks
- [ ] Change the url from `/disability-benefits/view-payments` to `/va-payment-history/payments`
- [ ] Update breadcrumbs

## Acceptance Criteria
- [ ] The url has been updated to `/va-payment-history/payments`

**Comment by micahchiang** [comment]
pr - https://github.com/department-of-veterans-affairs/vets-website/pull/13565
