### ISSUE TITLE
STEM: Update Education Benefits on the application Summary page

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11504]
As a developer, I need to update the 10203 workflow due to changes recommended from user testing interviews so that the applicant's have the best experience when completing the application.

## Assumptions:
1. This work is completed behind the feature flag #7271.
2. Updating breadcrumbs is not included in this issue and will be completed in a subsequent issue. 

## Acceptance Criteria
1. The display of the Education Benefits accordion has been to display the "Selected" instead of "True" for all of the benefits selected on Chapter 2, page 1 of the STEM form. 

## Supporting Artifacts:
1. [Final Version of the Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md) 
   a. The following word document tracks changes between  7/7 content doc & current version of the content doc that is linked above: 
[22-10203-ContentReconciliation-20200720 v2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4953780/22-10203-ContentReconciliation-20200720.v2.docx)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13563

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-23 at 10.12.38 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/04ed9649-c8ac-4d0d-867d-547b32187697)
##
![Screen Shot 2020-07-23 at 10.15.12 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6457204a-d8ad-45a4-83dc-690ba38aec4c)
##
![Screen Shot 2020-07-23 at 10.15.20 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/acf539b9-8815-4793-8691-0b23f7b6e285)
##
![Screen Shot 2020-07-23 at 10.15.31 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4d204536-5649-4aaa-a86f-ec4eabd21220)
##
![Screen Shot 2020-07-23 at 10.15.39 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/419fb282-023e-4322-bbda-b30742ab939a)
##
![Screen Shot 2020-07-23 at 10.15.47 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c58e8c57-f9c1-4685-bfc0-e408ada5f6ce)
##
![Screen Shot 2020-07-23 at 10.15.56 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a72cb6a5-ff23-4807-ae44-db84b7519687)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/9950&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
@sonntag-adam UX has reviewed and this looks good!

**Comment by sonntag-adam** [comment]
Closing story.
