### ISSUE TITLE
Transform feature toggle documentation

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#11508]
Requested in this Slack thread from Nick Sullivan:
https://dsva.slack.com/archives/CBU0KDSB1/p1595427141481200

Megan pointed out that the release plan template explains staged rollout:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md

Questions to consider:

- The release plan template presents this info when PMs are working through the collaboration cycle, but is it discoverable otherwise? 
- Might a separate document that explains staged rollout process independent of the template be useful? Would that be redundant?
- Is the release plan actually a template or is it a guide? Does is matter? Does it impact findability?

**Comment by lianilychee** [comment]
Don't forget to investigate release plan guidance as part of this transformation.  Info about "staged rollouts" is only available in the release plans.  Current guidance is dev-centered; no info for PMs.

**Comment by vbellissimo** [comment]
Cancelling/old task.
