### ISSUE TITLE
STEM: 508 Review of STEM Program List PDF

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11511]
In advance of our launch of STEM form 22-10203 in late August/early September, we'd like to have a review of the following document from an accessibility perspective so that if updates are required we can get an head start on them: 
- https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf

**Comment by 1Copenut** [comment]
@desireeturner I've done the preliminary check in Adobe Acrobat Pro, using the accessibility tools. The PDF passed automated scanning with no issues. I'll go ahead and check it in Acrobat Reader using NVDA on my Windows machine too.

If you like, it can be submitted to the VA's document remediation group through the VA Network IT portal. Their timeline is variable, but they have document experts on staff. Let me know if this is a step you'd like to take and we can follow up.

**Comment by desireeturner** [comment]
@1Copenut Great, thank you! Sounds like getting another review from VA's document remediation group couldn't hurt, so let's go ahead with that if you don't mind submitting that.

**Comment by 1Copenut** [comment]
Can do. I'll send it tomorrow morning when I log in.

**Comment by 1Copenut** [comment]
@desireeturner Good news. I checked on the request ticket for your STEM PDF this morning, and the audit has been completed and request approved. There's no additional notes or follow up items I can see, so this document looks to be good to go. I'll unassign myself and please feel free to close as it's convenient.

**Comment by desireeturner** [comment]
Thank you @1Copenut; closing now.
