### ISSUE TITLE
[Pre-release] Document the frontend revproxy config

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#11519]
## Description

In anticipation of making changes to the reverse proxy config for the frontend website, we need to first document what each existing piece does so that we are aware of what may need to be changed.

## Background/context/resources
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/11023

---
## Tasks
- [ ] Write a document that captures all of the things that the reverse proxy is doing for the va.gov frontend

## Definition of Done
- [ ] We have a document covering the revproxy responsibilities on the frontend

**Comment by jhonnyoddball** [comment]
# Reverse Proxy

## What it is?

The vagov-revproxy service is a reverse proxy designed to accept traffic coming from the Trusted Internet Connection (TIC) and direct that traffic towards private S3 resources (static content, ie. css, images, etc.).

Static site content is housed within a bucket or multiple buckets (AWS S3) for the respective environment of the traffic (sandbox, dev, staging, or prod).

Our reverse proxy nodes use OpenResty®, an enhanced version of Nginx core.

![image](https://user-images.githubusercontent.com/55560129/109044121-08d5b400-76a0-11eb-83d9-910700ec12de.png)

## Configuration

The deployment of the reverse proxy configuration:

- [sandbox](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov-sandbox.yml#L77-L81)
- [dev](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov-dev.yml#L85-L89)
- [staging](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov-staging.yml#L77-L81)
- [prod](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov-prod.yml#L78-L82)

Each deployment calls the `Nginx` file [nginx_website_server](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_website_server.conf.j2#L17) which passes the corresponding properties depending on each environment. It also calls [nginx_revproxy_redirects](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_revproxy_redirects.conf.j2) to handle the port 80/443 requests

Nginx conf files containing the properties for each environment:

- [sandbox](url)
- [dev](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-dev.yml)
- [staging](url)
- [prod](url)

## Next steps

- Write code to update reverse proxy to use separate S3 buckets
- Have DevOps review reverse proxy updates
- Merge and deploy reverse proxy updates to staging
- Monitor change in staging
- Update prod

## Links

- [Reverse proxy initial clean up](https://github.com/department-of-veterans-affairs/devops/pull/7262)
- [Reverse Proxy Documentation](https://vfs.atlassian.net/wiki/spaces/VI/pages/744980492/Reverse+Proxy)
- [Files, templates, and variables leveraged by all environments](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/revproxy-vagov)

**Comment by timwright12** [comment]
@jhonnyoddball this looks good to me, can we move this document over to a subdirectory (of your choosing) here https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform ? Then we can make sure that gets linked in all the other revproxy tickets. It sound like we'll need to do this to release to dev

cc @meganhkelley

**Comment by jhonnyoddball** [comment]
> @jhonnyoddball this looks good to me, can we move this document over to a subdirectory (of your choosing) here https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform ? Then we can make sure that gets linked in all the other revproxy tickets. It sound like we'll need to do this to release to dev
> 
> cc @meganhkelley

Reverse proxy doc created in https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/infrastructure/reverse_proxy.md
