### ISSUE TITLE
CT: Feature flag for Post-9/11 GI Bill benefit rate update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11534]
As a developer, I need to create a feature flag that can be used to turn on and off CT post-9/11 gi bill benefit rate updates so that it can be delivered to production in a timely manner.

## Assumptions:
1. Feature flag for post-9/11 GI Bill (CH 33) benefits will need be available in the following repo: vets-website

## Tasks
1. Follow feature flags documentation to create front-end CT CH33 rate feature flag.

## Acceptance Criteria
1. The "gibctCh33BenefitRateUpdate" feature flag is created and available in all environments.
2. The description is "Update to Chapter 33/Post-9/11 GI Bill benefit rates set to go live 8/1"

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by ksantiagomorgan6** [comment]
Frontend PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13569
Backend PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4570

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-23 at 7.51.14 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c012a026-3879-464e-87af-8e82969dc2b2)
##
![Screen Shot 2020-07-23 at 7.52.33 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2783a4bd-0218-4227-8485-5caddd26bba0)

**Comment by sonntag-adam** [comment]
In both https://staging-api.va.gov/flipper/features and https://api.va.gov/flipper/features now
