### ISSUE TITLE
Research CDW- Clinical data Warehouse

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11533]
Need to know all about how to work with CDW and performance

**Comment by abuckley3385** [comment]
@massrb thanks for creating this ticket, much appreciated. Can you please put a description of why our project needs the CDW to be researched as a data source. A hypothesis is fine! Also put acceptance criteria for based on your research what are you going to create/document to show this story is complete.  Ie. have a section in the Tech Feasibility doc?

**Comment by mchelen-gov** [comment]
Is issue about how to access patient data that would be used to prepopulate forms?

**Comment by massrb** [comment]
It turns out that we do not need to research CDW.  it is a far downstream dependency, if at all.  we would not write to CDW, and any data we might read from CDW would be possibly 24 hours old.

**Comment by mchelen-gov** [comment]
@massrb ah ok interesting. does that mean this issue is resolved?
