### ISSUE TITLE
Add dotenv to vets-website

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1153]
It's useful to use an external config for environment related information like hostnames for the build process. Evaluate using a dotenv file similar to the approach on `vets-api`

See: https://www.npmjs.com/package/dotenv

**Comment by timwright12** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17368

**Comment by timwright12** [comment]
content-build PR https://github.com/department-of-veterans-affairs/content-build/pull/192
