### ISSUE TITLE
STEM: Research "Exit application" button 

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11530]
As someone who processes education benefits applications, I want to ensure that individuals have a way to exit applications for benefits that they are no eligible for as soon as they know they are not so that we reject fewer ineligible applications. 

## Assumptions
1. This update is not expected to be part of the MVP launch for the 22-10203 STEM application. 
2. There will be a follow-on story for implementation based on the research outcomes

## Acceptance Criteria
1. The feasibility of adding an "Exit application" button to the 22-10203 on Chapter 2, page 2 and Chapter 3, page 2 has been evaluated and findings have been captured on this story. 
2. Follow on stories have been updated in accordance with the research findings. 

## Supporting Artifacts
1. Prototype of chapter 2, page 2: https://bahdigital.invisionapp.com/share/YFIAEHK8U2W#/screens/296045020
2. Prototype of Chapter 3, page 2: https://bahdigital.invisionapp.com/share/YFIAEHK8U2W#/screens/296045070

**Comment by dneel-bah** [comment]
Closing as OBE
