### ISSUE TITLE
Does Profile need to call the `GET full_name/` or `GET personal_information` endpoints?

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#11538]
Investigate if the Profile needs to call `GET full_name/` or `GET personal_information/`. It seems that `GET user/` gives us that same data.

Example response from `GET full_name/`:
```json
{
  "data": {
    "id": "",
    "type": "hashes",
    "attributes": {
      "first": "Wesley",
      "middle": "Watson",
      "last": "Ford",
      "suffix": null
    }
  }
}
```

Example response from `GET personal_information/`:
```json
{
  "data": {
    "id": "",
    "type": "mvi_models_mvi_profiles",
    "attributes": { "gender": "M", "birthDate": "1986-05-06" }
  }
}
```

`GET user/` gives us similar info. The only potential gap is the name suffix which I'm not seeing as part of the `GET user/` response, but I need to find an example of a user that has a suffix to confirm:

```json
{
  "data": {
    "id": "",
    "type": "users_scaffolds",
    "attributes": {
	  ...
      "profile": {
        ...
        "birthDate": "1986-05-06",
        "gender": "M",
		...
      },
      "vaProfile": {
		...
        "birthDate": "19860506",
        "familyName": "Ford",
        "gender": "M",
        "givenNames": ["Wesley", "Watson"],
        ...
      },
    }
  },
  "meta": { "errors": null }
}
```

If there is no reason to call these endpoints our code should be cleaned up to use the data from the `GET user/` instead.

**Comment by erikphansen** [comment]
Interesting that on staging user 32 has a gender of `null` from the `personal_information` endpoint or `user.vaProfile` but it is set correctly on `user.profile`

**Comment by erikphansen** [comment]
It appears that we do need to call the `full_name` endpoint. User 11 has a suffix of `Jr.` but there is no name suffix to be found on the `user` object.

Response from `GET full_name`:
```json
{
  "data": {
    "id": "",
    "type": "hashes",
    "attributes": {
      "first": "Eric",
      "middle": "Victor",
      "last": "Bishop",
      "suffix": "Sr."
    }
  }
}
```

Response from `GET user`:
```json
{
  "data": {
    "id": "",
    "type": "users_scaffolds",
    "attributes": {
      ...
      "profile": {
        "email": "vets.gov.user+11@gmail.com",
        "firstName": "ERIC",
        "middleName": "VICTOR",
        "lastName": "BISHOP",
        "birthDate": "1963-07-05",
        "gender": "M",
        "zip": "20171",
        "lastSignedIn": "2020-07-23T01:01:20.416Z",
        "loa": { "current": 3, "highest": 3 },
        "multifactor": true,
        "verified": true,
        "signIn": { "serviceName": "idme", "accountType": "N/A", "ssoe": true },
        "authnContext": "http://idmanagement.gov/ns/assurance/loa/3"
      },
      "vaProfile": {
        "status": "OK",
        "birthDate": "19630705",
        "familyName": "Bishop",
        "gender": "M",
        "givenNames": ["Eric", "Victor"],
        "isCernerPatient": false,
        "facilities": [],
        "vaPatient": false,
        "mhvAccountState": "NONE"
      }
      ...
    }
  },
  "meta": { "errors": null }
}
```

**Comment by erikphansen** [comment]
We can likely stop calling `personal_information` but we should confirm that endpoint doesn't sometimes provide additional information.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel can work on if it's easily handed off by @erikphansen .

**Comment by erikphansen** [comment]
Right now my recommendation is to not make any changes to which APIs we call and how we populate the Redux store with the data we show on the Profile.

- we DO need to call the `GET full_name` API because that's the only way to get the name with proper capitalization and the suffix (if there is one)
- we _might_ need to keep calling the `GET personal_information` API since future work will be expanding what the personal info that we show. That API might be responsible for retrieving that data.
