### ISSUE TITLE
Forms Content Management Investigation

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11531]
Identify the correct strategy for form question management solutions that exist today if CMS is not the source. 
- We do not want to have to have the questions to each form in code. 

- [ ] Product Strategy documentarians
- [ ] Technical capabilities documentation

**Comment by abuckley3385** [comment]
We are putting this issue on hold until we have an identified need.  @LEHigley spoke with the Drupal PO and the current strategy for VA CMS is only for static content pages- no form templates.

**Comment by julieadair1** [comment]
@jparker0425 is this something we need to prioritize?
cc: @dillo @batemapf

**Comment by jparker0425** [comment]
@julieadair1 closing this out. I believe there have been a lot of changes to the form system since this was initially opened. Will create new epic in future if needed for specific work around forms.
cc: @dillo
