### ISSUE TITLE
Redirect users from bookmarked 'How EC works' if inactive

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11548]
For Veterans who bookmark the Express Care page or Veterans who use the direct Express care url from a VAMC specific site, if EC is inactive when they navigate to the EC flow from a VAMC website or bookmark redirect them to VAOS app homepage. 

## Acceptance Criteria:
- [ ] If user navigates directly to EC page "How Express Care works" and EC window is not active redirect user to VAOS app homepage

This maps to the following GH issue: #11034

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/88305627-b8484380-ccd7-11ea-84d5-eb08d8bf5c5f.png)

**Comment by peggygannon** [comment]
@rtwell looks good. My only followup is to tweak this line and remov the "a" before VA health care staff for sense: 

Express Care lets you talk to VA health care staff the same day to discuss a symptom that's  not urgent and doesn't need emergency care.

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/88338070-cc0a9e80-cd05-11ea-9006-01e0c5319926.png)

**Comment by lenaecb** [comment]
@rtwell @peggygannon - this ticket is to create an 'inactive' state for the 'How Express Care works' page. 

We need to also have inactive state on this page for users that using a direct URL into VAOS from specific VAMC sites, but they are outside of the active EC window.

I made a suggestion in the actual ticket for how we can handle this.

**Comment by peggygannon** [comment]
@lenaecb just to make sure I understand, we need another inactive state for the How Express Care works screen? 

--Does this message need to be different than the one on the VAOS landing page? Or can we use the same message that we're using for the VAOS landing page?

--Would this message appear as an alert? 

**Express Care isn't available right now**
Express Care is only available [Hour] to [Hour][pm] [timezone] today. Express Care lets you talk to VA health care staff the same day to discuss a symptom that's not urgent and doesn't need emergency care. To use Express Care, check back during the time shown above.

If you need to talk to VA health care staff now, please contact your VA medical center(https://www.va.gov/find-locations/) before going to a clinic.

**Comment by rtwell** [comment]
hmmmmm this is a tough one. it _seems_ like an alert at the top of the page (pulling the language from the inactive home page) would be the appropriate UX, but that means we've got 2 alerts on this page (although the second 911 alert is kinda meaningless in this scenario b/c the user cannot move forward anyway. 

question: can we hide the 911 alert in this scenario? i'm guessing the answer is no b/c we still want to direct Veterans to the appropriate place if they are indeed in need of urgent care

**Comment by peggygannon** [comment]
@rtwell Maybe we can use this pattern for the 911 message (in screenshot below) where the user clicks on link to get full message? 

**Express Care isn't for emergency care**
{dropdown link} **Call 911 or go to emergency room if you have any of the following symptoms**
user clicks on link to see rest of alert

![2020-07-28.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/03e90363-1e97-4109-99e9-8ff66231d685)

**Comment by lenaecb** [comment]
@peggygannon I am late to answer you, but yes. We need an additional inactive state for times where users have bookmarked a page directly, login directly using that link, but the window for EC is actually unavailable. I had recommended repurposing the message from the homepage here - as you have indicated too. 

As for the 911 question - @rtwell I think if we can make it work here, we keep it. But we don't indicate that on the inactive state on the homepage, so also don't want to mislead. Whatever is the most appropriate path to get them their care - either calling the doctor/facility, or visiting the ER if an emergency.

**Comment by rtwell** [comment]
Question for @jbalboni (i think)— if a user bookmarks this page and EC is closed, can we redirect to the vaos homepage?

**Comment by jbalboni** [comment]
@rtwell Yes, we can do that.

**Comment by rtwell** [comment]
woo perfect! this is also what @lalexanderson-dsva would prefer as well. another benefit for this approach is it allows users to request a reg appt on new vaos.

**Comment by lenaecb** [comment]
Based on this I will update the ticket to account for this change.

**Comment by lenaecb** [comment]
@jbalboni - can you confirm that isn't only for EC is _closed_? We will want to use this url for direct access from VAMC sites to the EC flow, and if EC is active when they arrive they should be able to continue with flow.

**Comment by jbalboni** [comment]
@lenaecb Right, if I'm understanding this correctly, when a user lands on the "how express care works" page:

1. If there's no active EC window, they will get redirected to the VAOS homepage
2. If there is an active EC window, they will be shown the "how express care works" page and can start the EC flow

**Comment by lenaecb** [comment]
@jbalboni - yes, that is what I would expect as well based on the request from Lauren/Ryan.

**Comment by jbalboni** [comment]
The redirect part of this is done, but I can't tell if there's other that needs to happen here @rtwell @peggygannon.

**Comment by rtwell** [comment]
the redirect _should be_ all we need.
