### ISSUE TITLE
Add error handling for creating pages in documentation site

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#11543]
## Issue Description
A [fix](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11173) for the documentation site build was made for handling invalid HTML pulled from the [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team) repo.

The fix above only handles invalid HTML pulled from `va.gov-team` , but the build still breaks if there is invalid HTML in markdown files inside of the documentation repo itself.

The same approach that was taken in this [PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/318) needs to be applied to the `gatsby-plugin-mdx(forked)/gatsby/on-create-page.js` plugin. Error handling needs to be added for the `onCreatePage` [lifecycle](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/f58cba0c387de013426e5eeb1aae597355554f57/packages/documentation/plugins/gatsby-plugin-mdx(forked)/gatsby/on-create-page.js#L26) as well.

This problem was discovered in this [commit](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commit/b1e60b63028aa4d4e2e08fba99c79b72060f506d).

## Acceptance Criteria
- [ ]  Invalid HTML in the documentation repo itself doesn't break the documentation site build.

**Comment by mchelen-gov** [comment]
how about enforcing markdown validity in PR checks instead of trying to handle errors in build process?

**Comment by meganhkelley** [comment]
Megan/Eugene convo 8/28: 
* The fix Theo used for invalid html in `va.gov-team` does not exactly apply here
* We are not going to prioritize troubleshooting this in the short term, pending a documentation site strategy decision from Content & IA Team

**Comment by timwright12** [comment]
@meganhkelley  Do we need this ticket since we're migrating into confluence?
