### ISSUE TITLE
Discovery: Direct deposit paper forms retired - content update + redirects?

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11551]
## Direct Deposit VA Forms **24-0296** and  **24-0296a** are being retired/discontinued starting Aug 1, 2020. 

•	24-0296  Direct Deposit Enrollment: https://www.vba.va.gov/pubs/forms/VBA-24-0296-ARE.pdf
•	24-0296a  International Direct Deposit Enrollment https://www.vba.va.gov/pubs/forms/VBA-24-0296a-ARE.pdf

1/ We need to ensure that our benefit hub pages are no longer referencing or linking to these forms. 
2/ Consider: Are these 2 forms highly accessed according to analytics? If so, should we redirect them to an appropriate place if one exists? ( [Our Direct Deposit page](https://www.va.gov/change-direct-deposit/)? <-- to be safe would verify with Samara who, I believe, is PO of our DD tool. )

**Business stakeholder's email:**

> From: Kinder, Adam, VBASLCY <Adam.Kinder@va.gov> 
> Sent: Wednesday, July 22, 2020 10:06 AM
> To: Lee, Jennifer Y. <Jennifer.Lee27@va.gov>
> Cc: Kessinger, Nancy, VBAVACO <nancy.kessinger@va.gov>; VAVBAWAS/CO/PCO <PCO.VBACO@va.gov>; Shawler, Joseph E., VBAMUSK <Joseph.Shawler@va.gov>; Haas, Philip J., VBAMUSK <Philip.Haas@va.gov>
> Subject: RE: 24-0296 and 24-0296a forms
> 
> Good morning Ms. Lee, 
> 
> As an outcome of a risk-based decision,  we wanted to inform you that a decision has been made to discontinue the use of paper-based Direct Deposit Forms (VA Form 24-0296 and VA Form 24-0296a) effective August 1, 2020 (grace period Jan 1, 2021).  Our goal is to encourage Veterans to use the VA.gov self-service capability to update/change their direct deposit information and use the National Call Centers as a secondary option.  As a result, we need to take steps to discontinue these forms effective August 1, 2020.  Eliminating the use of mail and fax to process paper-based forms is consistent with operations at the Social Security Administration and will enhance the security of Veterans’ benefits delivery.  
>

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva Thanks for raising the question of redirecting. The only place we have a link to that first pdf form is *from* our direct deposit page, so we can't redirect there... the user is already there. Since the point of retiring this form, according to the stakeholder, is to encourage users to enroll for direct deposit through their VA.gov profile and make changes/update using our tool, I don't think there's a need to redirect. 

@RLHecht thank you for removing the broken link to the one pdf. And for auditing to see if there were any other broken links to those forms.

**Comment by FranECross** [comment]
@bethpotts @RLHecht Is it okay to close this old ticket, or do you know if something still needs to be done?  Thanks in advance!

**Comment by RLHecht** [comment]
@FranECross you can close this ticket. Thank you!

**Comment by FranECross** [comment]
Closing per Randi Hecht.
