### ISSUE TITLE
Contact Center Review for [Profile 2.0]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#11572]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high level description of your product.*

Name: Profile 2.0
Description: This is a change to the existing VA.gov profile. We are combining the "Profile" and "Account" pages as well as making the UI more effective and easier to scan. We also have included a side navigation menu to make the Profile easier to navigate.

### Launch Date
*[Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)*

### Product Guide
*to be added by 7/29*

### Product Video
*to be added by 7/29*

### Product Video Transcript
*to be added by 7/29*

## Acceptance Criteria
- [ ] VSP Analytics & Insights QA has been completed 
- [ ] VSP Analytics & Insights sends artifacts to appropriate contact centers
- [ ] VFS team completes brief VSP Collaboration Cycle Feedback survey [link](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before)

**Comment by Samara-Strauss** [comment]
I'm not sure why this ticket is open/in the icebox, since I know we submitted the contact center help guide for profile 2.0 and got sign off from Chante. Closing.
