### ISSUE TITLE
Add the camelCase schema tests

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#11585]
`spec/support/schemas` includes json schemas for various request specs.  There is now a rake task (`rake camelize_file:schema`) that can take a file from that schema directory and apply camel-inflection on it and save it in `spec/support/schemas_camelized`.  Then anywhere the `match_response_schema` matcher is used in a request spec, another test can be added that is the same except uses a new `match_camelized_response_schema` matcher to validate against the camel-inflected version.  This task is to add in those additional tests to the specs so that camelCase can be supported in test.

**Comment by erluti** [comment]
All schemas converted to camelCase and have tests added.
