### ISSUE TITLE
Initial Draft of BE Documentation Navigation

### ISSUE THREAD

**Issue by thilton-oddball** [department-of-veterans-affairs/va.gov-team#11589]
Come up with an initial draft of how we think the navigation for the BE Developer Focused Documentation should be laid out.

**Comment by alexpappasoddball** [comment]
@thilton-oddball can you link your WIP spreadsheet here and we can close this ticket as we have enough to get started on the prototype which I created a ticket for already!

**Comment by thilton-oddball** [comment]
https://docs.google.com/spreadsheets/d/1-IDYDMnms1rO8ZIlR3xROzeKb7TONzV8pQDp_xzewlE/edit#gid=0
