### ISSUE TITLE
Design feedback - Usability Testing Prep [learning center MVP template]

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#11586]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**

Finicky hot spots:
- [On this page](https://vsateams.invisionapp.com/share/YJXZTKC6CN4#/screens/425180625), hotspot for “contact the specific program” seems to be floating and not on the link itself
- “Sign in FAQs page, hotspot is in to related info section at bottom of page”- There is no hotspot in the related info section of the [FAQs page](https://vsateams.invisionapp.com/share/YJXZTKC6CN4#/screens/425192997)
- [On Agent orange page](https://vsateams.invisionapp.com/share/YJXZTKC6CN4#/screens/425126481), the first button “Learn how to file a disability claim” hotspot is in the alert instead of on the button

**Try:**

- Try adding a hover state to the tag “Vietnam War Veterans” to infer that it’s interactive, and test the hover state
- [On this page](https://vsateams.invisionapp.com/share/YJXZTKC6CN4#/screens/423655543), consider changing the blue outlined boxes around the “Find articles by audience section” to gray because blue is generally reserved for interactive components

**Consider:**

-  For the on this page hotspots on the Agent Orange page, consider when clicking on the section of the component to bring you right above the section title. When I click through the page jumps to the title half hidden
- Consider using higher res screenshots in the “Step-by-Step” sections - some of them are a little grainy.

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

**Comment by andaleliz** [comment]
Thanks @CrystabelReiter for this feedback! The `do` items are corrected, as well as the first bullet in the **Consider** section.

I'll defer to @rtwell for your suggestions in the Try section, since he's the designer on this. Not sure if he has already planned for interactive states or not.

Since we are not testing the content in the screenshots, I'm going to leave those as-is for now.

**Comment by CrystabelReiter** [comment]
Thanks Liz! I'll close the ticket :)
