### ISSUE TITLE
Sentry 10 configuration is extracted from UI into code

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#11584]
## Background

With Sentry 10 launch, we're doing configuration within the UI. This makes re-deploying a fresh instance of Sentry difficult, as we would need to re-configure everything.

This work effort tracks the work needed to extract configuration into code. 

## Tasks

- [ ] Projects are defined in configuration
- [ ] [Discovery] - Can we use a Terraform provider to configure Sentry, so that we can store our Senntry config as code?

**Comment by omgitsbillryan** [comment]
I've created a separate ticket that kind of overlaps with this one: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12118

It covers only the `dev` portion of Sentry 10 configuration.
