### ISSUE TITLE
SAML Post binding does not work in some versions of IE11

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#11596]
For users using IE11, specifically on Windows SP2010 (ie IE11 on CAG), the SAML Request Post is never sent to eauth.  Instead the user is left on an empty page after initiating the call to authenticate because of a JS error when rendering the SAML Post form.

It appears that versions of IE11 in the Windows SP2010 don't support the `addEventListener` function, so a JS workaround is needed.

https://stackoverflow.com/questions/18829292/object-doesnt-support-this-property-or-method-error-in-ie11

**Comment by patrickvinograd** [comment]
For context, IE on VA GFE machines is set to run in compatibility mode for "intranet sites" which includes va.gov. That's why addEventListener is not supported.
