### ISSUE TITLE
Show generic message when a Profile-related endpoint fails

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#11602]
Profile 2.0 calls a handful of endpoints in order to collect all the data it needs to display. Sometimes a call to one or more endpoints will fail. While we continue to show what data we can in these situations, we don't always indicate to the user that not all of their data will be shown. So we should show a generic "things may not look right, please refresh the page or try again later" error at the top of each profile page if any of the following calls fail:

- `GET full_name`
- `GET payment_information`
- `GET personal_information`
- `GET military_information`

This error alert should live above each section's headline.

Alert text to be determined by @tressaellen

**Comment by tressaellen** [comment]
@peggygannon could you take a look at this? A bit of background - if we can't connect to an endpoint we need to have a generic message letting users know that things might now look right and they need to try again.  This will be used for a handful of endpoints so we won't be able to let them know what specific things aren't working. Here's a first pass for a generic message.

We couldn't load this page properly

We’re sorry. Something went wrong on our end and we couldn’t load everything we need to display this page correctly. Please refresh or try again later.

![Screen Shot 2020-07-31 at 1.54.10 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/ff9f6031-afbc-4f69-9213-1e54f6efbd1e)

**Comment by peggygannon** [comment]
@tressaellen Here's a recommendation. 

**We can’t load your information**
We're sorry. Something went wrong on our end. We can’t display all the information on this page. Please refresh the page or try again later.

**Comment by erikphansen** [comment]
Could I suggest we change the headline from `We can’t load your information` to `We can’t load all of your information`?

**Comment by peggygannon** [comment]
@erikphansen Yes, that works. So message would be 

**We can't load all of your information**
We're sorry. Something went wrong on our end. We can’t display all the information on this page. Please refresh the page or try again later.

**Comment by erikphansen** [comment]
Gonna remove @tressaellen and @peggygannon from this ticket now. Thanks!

**Comment by erikphansen** [comment]
@tressaellen this is done. But sadly there isn't a great way to just make an endpoint fail in staging so you can see it so it'll be hard to validate.

**Comment by tressaellen** [comment]
Okay sounds good! I guess I'll just have to take your word for it. Are we good to close this then?

**Comment by erikphansen** [comment]
Yep!
