### ISSUE TITLE
Tell user they are blocked from accessing their Direct Deposit info

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#11606]
If a user is flagged as incompetent, deceased, or having a fiduciary we need to tell them that they are blocked from accessing their Direct Deposit section. We do this on Profile v1 (https://github.com/department-of-veterans-affairs/vets-website/blob/218ffcf826877dfdf2a7785468d1061d26ea739c/src/applications/personalization/profile360/components/ProfileView.jsx#L117) but are not doing it with Profile 2.0 yet.

- [x] show the PaymentInformationBlocked component at the top of the Personal and Contact Info section
- [x] add tests that check that the alert is shown when it should be and not shown otherwise

**Comment by erikphansen** [comment]
@mshea0606 can you check this in staging with the users who are flagged as incompetent or having a fiduciary?

**Comment by mshea0606** [comment]
@erikphansen no problem!

**Comment by mshea0606** [comment]
@erikphansen looks good!
