### ISSUE TITLE
Investigate plan for how to support CMS in our ATO

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#1161]
Brandon and Faith to Investigate what we will need to do to support CMS in our ATO.

**To support the CMS in our ATO we will need to have 3 pieces complete:**
1. Access Control Policy
2. System Response Plan
3. System Contingency Plan

**Next Steps:**
- [ ] Gather any ATO compliance information that currently exists for the CMS
- [ ] Identify ATO compliance gaps
- [ ] Create a plan to bridge gaps
  - [ ] Identify people who can help answer ATO questions

What are the potential risks?

What are the dependencies?

What are potential blockers?
- Faith requires PIV access to get into the ATO systems (RiskVision or eMASS).

People who can help answer ATO questions
- Elijah Lynn (Agile6)
- Jeff Barnes (DSVA)
- Taylor Skinner (VSP)

CMS ATO docs
- The docs need to be updated, but there are some at https://github.com/department-of-veterans-affairs/va.gov-cms-devops/ for now
- They are moving to https://github.com/department-of-veterans-affairs/devops soon and we have some already moved to  https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/cms (not sure that is the longterm location, they may be moved)
- 

Previous contact: Brian Gryth

Next Steps:
1.  Get access into EMS - Brandon
2.  Share docs with Faith - including new PIA template
3.  Submit a PTA for VFSP (leverage vets.gov and change name and project owner)
4.  Enter in a remediation task around CMS - This should handle our CMS integration. We can make this to be completed in the future.
5.  Start working on PIA
6.  Review docs in system with Faith and Brian

**Comment by rroueche** [comment]
Note: CMS ATO needs to be merged into VSP ATO by 9/25/19, so this sprint we need to start figuring out how to do this, so that we can actually do it in future sprints.

**Comment by brandonrapp** [comment]
@fowusu2 - I added the CMS ATO documents that Elijah had mentioned to us in the ticket.

**Comment by brandonrapp** [comment]
Plan has been finalized! Moving on to more granular tickets for ATO work upcoming.

1. Get access into EMS (Patrick is providing assistance)
2. Share docs with Faith - including new PIA template
3. Submit a PTA for VFSP (leverage vets.gov and change name and project owner)
4. Enter in a remediation task around CMS - This should handle our CMS integration. We can make this to be completed in the future.
5. Start working on PIA
6. Review docs in system with Faith and Brian
