### ISSUE TITLE
New info message for deleted forms: Find a VA form search

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11625]
## New form-specific info message for deleted forms: Find a VA form search

As a Veteran, if I search for a form that has been deleted, I want to know that it's not a search error or because I'm not using the right search query. 

**Condition:**  User searches for a form that has been deleted in the VA forms database - it has a deleted flag and deleted date meta data.

**Message:** The form you're looking for has been retired or is no longer valid, and has been removed from the VA forms database. 

Acceptance Criteria: 
- [ ] Instead of showing the generic error message as it does today, show the above form-specific error message for deleted forms.

**Deleted forms we can validate with:** 
3 forms in the CMS that are showing the ‘deleted’ meta data:  24-0296, 24-0296a,  and 22-8873

## open question
* is lighthouse consuming the deleted/archived form flag and returning this? Per t[his Slack thread](https://dsva.slack.com/archives/CUB5X5MGF/p1600370964118600?thread_ts=1598555957.028300&cid=CUB5X5MGF), this is now being done

**Comment by jenniferlee-dsva** [comment]
Per Slack message: 
This isn't a bug but an enhancement with a new error message for the deleted form use case.
So please prioritize accordingly. The FE CMS work and validating API cutover (when that's ready) are definitely the higher priorities.

**Comment by ncksllvn** [comment]
I'm checking out the Lighthouse API implementation to learn how to do this and hoping to distinguish between these two fields.

`valid_pdf` - set to `false` if the form PDF fails to open during the Lighthouse migration
`deleted_at` - an unsurfaced field equal to the GraphQL field `fieldVaFormDeletedDate`.

My inclination is that `valid_pdf` is what we're interested here. Currently, Find Forms just ignores any form that has `valid_pdf` of false. I think the work here is calling for us to show the form but represent it as invalid. I'm not sure how that differs from `deleted_at though.

**Comment by jenniferlee-dsva** [comment]
Replying to 
>I think the work here is calling for us to show the form but represent it as invalid. I'm not sure how that differs from `deleted_at though.

In the CMS there is a difference between `invalid` form and a `deleted` form. @swirtSJW would be able to shed light on this.

**The `deleted` meta data comes directly from the VA forms DB.** 

- It tells us that form X was deliberately removed from the DB and what date. This let's us know that the form detail page for X form should be automatically put into an unpublished archive state. 
- Right now, the search treats a deleted form, just as if it was an invalid form, and suppresses the form from search results. The user sees the generic no search result form message: "No results were found for "22-8873." Try using fewer words or broadening your search. If you're looking for non-VA forms, go to the GSA Forms Library."

**Invalid PDFs - these forms are still in the forms DB.** 

- They haven't been removed (the unique form rowID is still there). Because the forms db generates the PDF url from the PDF filename, the PDF url could become invalid through human error (misnaming the file etc). But the form is still in the DB as a form in active use. 
- The valid_pdf meta data -- I think that is fully FE. Didn't we implement that when the API was still on web scrape, @ncksllvn ? And we did that because we were seeing so many instances of invalid pdf links coming up in search? I believe that's when either we or LH api added logic to suppress invalid PDFs from coming up in search.  

So as you say, maybe in the FE logic, there's no need to treat them differently. Though I think bc we can know definitively that form X is deleted, we can provide a clearer message that the form has been removed. So users don't keep searching for the form via search refinements and/or report that search is broken, which is both what has happened.) Otherwise we wouldn't be able to tell them the form was deleted. 

I think where the API does need to consume the deleted meta data is to provide that [autonotification to form managers per this slack with LH engineers](https://dsva.slack.com/archives/CUB5X5MGF/p1596125866103900?thread_ts=1596123199.101700&cid=CUB5X5MGF) -- to include both deleted forms and invalid PDF links.

Sorry for the mega reply.

**Comment by MickinSahni** [comment]
**Discussion - JL, NS, KA, MS**

* Forms can be deleted for valid reasons but we couldn't tell if it was a bug or a deliberate deletion by Form Managers
  *

**Comment by ncksllvn** [comment]
Summary from call 8/06 -

Currently this is blocked until Lighthouse API supports returning "deleted" metadata for each form in search results. If a user performs a search and ALL results are "deleted: true" (there will likely only ever be one for an exact search by form number), then we should show the error message "The form you're searching for has been deleted." If ANY of the results are not deleted (maybe a search returns 10 results, 9 of 10 which are deleted, but 1 is still active) we should just ignore the deleted forms by filtering them out, then rendering the remaining search results as normal

**Comment by ncksllvn** [comment]
Removing the blocked label per https://dsva.slack.com/archives/CUB5X5MGF/p1600370964118600?thread_ts=1598555957.028300&cid=CUB5X5MGF

**Comment by jenniferlee-dsva** [comment]
**Adding IRL example:** 

- This form **5655blank** was deleted in the DB on 9/23. 
- On 9/24 (2:07 pm), it still appears in the search. 
- When you click on the form link (of the deleted form, nothing happens.

Since the API now includes the ‘form deleted’ meta data, I think we should be able to:
1/ Suppress the deleted form from search (per above og ticket description) and provide a custom error message saying the form they searched for was deleted and no longer available. 

The one thing I'd like help thinking about is this in-between/purgatory time when a form has been deleted in the DB, but still shows in form search until the next deployment. (If I understood right - this form is still appearing because the site and api haven't gotten updated yet with the newly deleted meta data??) 

![image](https://user-images.githubusercontent.com/43381063/94184417-dd8d3580-fe71-11ea-944a-d27f0e7b2f15.png)

**Comment by MickinSahni** [comment]
> Suppress the deleted form from search (per above og ticket description) and provide a custom error message saying the form they searched for was deleted and no longer available.

In this scenario where there's more than 1 result originally returned, my understand is we'd only return the valid result and **not** return an error message too. 

I'm basing this on the summary above: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11625#issuecomment-670099929

**Comment by jenniferlee-dsva** [comment]
>In this scenario where there's more than 1 result originally returned, my understand is we'd only return the valid result and not return an error message too.

Yep! We should suppress the deleted form though.

**Comment by jenniferlee-dsva** [comment]
^ I mean from search results.

**Comment by MickinSahni** [comment]
Right. So to confirm, for the scenario with more than one form returned in results AND where one of the forms has the `form deleted` flag, there's *no* error message returned. Just the not-deleted forms will be returned in results. cc @brianalloyd

**Comment by jenniferlee-dsva** [comment]
Yep - confirming [what you said ^](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11625#issuecomment-701125917) @MickinSahni 
cc @brianalloyd

**Comment by MarciMcGuireGCIO** [comment]
Grooming note - reiterating that forms that can be used for testing are 
24-0296, 24-0296a, and 22-8873

**Comment by MarciMcGuireGCIO** [comment]
Updated title since this is not an error message per se, but rather a message to inform the user that a form no longer exists in our database.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO this is ready for validation on staging: 
https://staging.va.gov/find-forms/?q=22-8873

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel this looks great to me!  @johnhashva please have a look at the updated message for deleted forms when you have a moment.

**Comment by zacharymorel** [comment]
Was the showing off in Standup good enough for validation?

**Comment by MarciMcGuireGCIO** [comment]
I believe so.  @johnhashva are you good with us closing this issue?

**Comment by MarciMcGuireGCIO** [comment]
Closing!
