### ISSUE TITLE
Direct Schedule Flow - 'Earliest date we can schedule' alert showing when it shouldn't

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11631]
## What happened?
User is seeing 'earliest date we can schedule' alert showing when it shouldn't be. 

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- Test User: Judy Morrison
- Select:  Schedule an appt, Primary Care, VA Medical Center, CHYSHR, Cheyenne VAMC
- Select CHY PC Cassidy. Enter 9/4 as desired date.  (Verified clinic has availability on 9/4/2020)
- Expected Response: System displays:  Tell us the data and time you’d like your appointment and the clinic calendar displays
- Actual Response:  System displays:  Tell us the data and time you’d like your appointment and then a grey box with message (This is the earliest date we can schedule your appointment and more detail)  and then the calendar.

## Desired behavior
- Alert should only show if clinic doesn't have availability and user needs to select new time/date

What test saw:
![image.jpg](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/344c47be-0339-4917-ac9c-ae9a522ee8cd)

**Comment by marcynadeau** [comment]
attaching another screen shot.  Judy M.  Primary Care.  

![EarliestDate.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/e497d852-2cdb-4eab-aa1c-d9c3ca2f9e96)

**Comment by laurenernest** [comment]
@lenaecb What's blocking this ticket?

**Comment by marcynadeau** [comment]
Adding another scenario:   Login as ola.edgecombe.  1)  Select Eye 2) Select Optometry 3) Select Cheyenne 4) Select CHY OPT VAR1 as the clinic 5) Select current date as appointment date.  6) Actual Response:  VAOS displays a modal above the calendar that says "The earliest we can schedule your appointment is January 22, 2021 at 9:10 a.m. Mountain time (MT)" and then the date 1/22/2021 is not even selectable in the scheduling calendar.  6) Expected response:  The verbiage in the modal needs to be consistent with what the app will allow

![image](https://user-images.githubusercontent.com/62026291/105513772-f24ad000-5c8f-11eb-8a8f-b97ce22bf5fe.png)

**Comment by outerpress** [comment]
@laurenernest - I'm wondering why we need that first date entry here. Don't we get that data if they request an earlier appointment?

A better flow might be:
* Send them to the schedule an appointment page
* Add an add'l info dropdown like "Need an earlier appointment?"
* Include the alert info and option to request an earlier appointment there

That would save them from entering a date twice in two different ways, and still provide data on how many people are not able to direct schedule because they need an earlier date.

**Comment by laurenernest** [comment]
@outerpress For direct scheduling, this first date entry is a business requirement tied to reporting. 

Adding this to the list for grooming to talk through with the team.

**Comment by laurenernest** [comment]
Handled in #25745
