### ISSUE TITLE
Use Danger Bot to Fail Large PR's

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#11630]
### The Problem
Large PR's make their way to the utility dev for review that cannot be reviewed in a reasonable timeframe and often result in delayed feature releases, bug fixes, & deploys. 

### Extra Context
There are mismatching expectations, where the PR author still expects their PR to be reviewed inside 1 business day([as outlined in our docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ca2514e624dcf5b245cf662f17839c6c5cee69f0/platform/engineering/code_review_guidelines.md#the-pull-request-review-lifecycle-in-brief)), but due to it's size, it takes longer. If we fail the PR immediately, it may help set expectations sooner.

Currently, the dangerbot will warn for PR's larger than `250` LoC
![image](https://user-images.githubusercontent.com/3077884/88418524-ac30b480-cdb1-11ea-8047-5aa86620ddb5.png)

However, this is only a warning and does not "Fail" the `danger/danger` status check:
![image](https://user-images.githubusercontent.com/3077884/88418479-991de480-cdb1-11ea-9d6e-0ed379e78984.png)

...Even if it did fail, `vets-api` does not require for this status check to pass in order to merge
![image](https://user-images.githubusercontent.com/3077884/88418610-d08c9100-cdb1-11ea-9cb9-8e154dbe18d7.png)

#### Even More Context
There may be scenarios in which a PR cannot be broken down to be smaller - in which case, we should have a process (maybe a form?) explaining why an override is necessary.

### Work to be Done
- [ ] Update the Dangerfile to fail PR's large PR's (exact number TBD)
- [ ] Update relevant platform facing docs with any new PR restrictions

**Optional Steps**
- [ ] Optionally create "override" process to force the review of large PR's
- [ ] Optional change how LoC are counted in PR's to exclude specs

**Comment by digitaldrk** [comment]
Thank you for getting this out in the open.

My only concern is that there are some occasions where a concept or feature doesn't work with this requirement. That there would be a lot of rework breaking up PR's for the sake of breaking them up to meet the LOC guideline.

I like the idea of having this as a hard requirement but also having an SOP in place between platform and teams where we could meet and discuss moving complex/large features through as sort of a partnership, a mutually agreed upon plan. I think this would reduce a lot of confusion.

**Comment by omgitsbillryan** [comment]
@erluti had a similar comment that LOC is an arbitrary guideline. I chose `LoC`  because it is:

- easy to understand
- easy to measure
- it's _pretty good_ at indicating that a PR can be broken up into smaller pieces

If not `LoC` we might be able to use codeclimate's code-complexity rating 🤷 ?  It just needs to be something tangible that a bot can measure against.

...Also our [list of file exclusions from `LoC`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Dangerfile#L3) count can/will be an ever changing list.

**Comment by alexpappasoddball** [comment]
@omgitsbillryan moving this to in progress since you are actively working on it.

**Comment by alexpappasoddball** [comment]
@omgitsbillryan Just a reminder that we need to include this new policy in the guidelines doc [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/code_review_guidelines.md)

**Comment by annaswims** [comment]
I think fairly often Lines of code is a fairly poor substitute for cognitive complexity.  I also don't think that deletions should count as much as additions. For example, this "delete unused code" PR isn't that complex though it approaches 1000 lines. https://github.com/department-of-veterans-affairs/vets-api/pull/4514
