### ISSUE TITLE
Community Care - VistA CC appts not showing in FE but should be

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11632]
Community Care clinics are identified by either using the prefix:
- COM CARE-<specialty> (example: COM CARE-AUDIOLOGY)

Or match one of these two clinic names:
- NON VA CARE HCPS HEMODIALYSIS
- NON VA CARE HCPS PERITONEAL DIALYSIS

From Marcy:
A clinic that I expected to display in staging in new UI is not displaying.   The clinic matches the regex and so should show  in new UI as VA appointment.   

I went into VistA and made an appointment for Cecil Morgan in this clinic on 8/7/2020  COM CARE-PRIMARY CARE CHYSHR.  I expected it to display in new UI. It did not. 

https://veteran.apps-staging.va.gov/cdw/v3/facilities/983/clinics/452

{"etag":"b807872d8805f255daf0871b26cdf90e04870b74839cea3a24753835e5436e27","locationSID":1400078821,"locationIEN":"452","facilityId":"983","locationType":"CLINIC","locationName":*"COM CARE-PRIMARY CARE"*,"primaryStopCode":669,"primaryStopCodeName":"COMMUNITY CARE CONSULT","institutionSID":1400039290,"institutionIEN":"442","institutionName":"CHYSHR-CHEYENNE VAMC","institutionCode":"983","patientFriendlyLocationName":"NONE","medicalService":"MEDICINE","appointmentLength":20,"directSchedulingPatient":false,*"displayAppointment":true,*"sta6aid":"983","vaStationName":"CHYSHR-Cheyenne VA Medical Center"}

This was the URL called in the app.
https://staging-api.va.gov/vaos/v0/appointments?start_date=2020-07-16T06:00:00.000Z&end_date=2021-08-16T06:00:00.000Z&type=va

Here are the rest of the clinics. I was expecting all the appointments in clinics with display flag = yes would display in new UI as VA.  

APPOINTMENTS FOR: MORGAN,C
- Aug 06, 2020 8:00 AM (15 MINUTES) NON VA CARE HCPS PERITONEAL DI CHYSHR ien 1065 display flag = yes
- Aug 07, 2020 8:00 AM (20 MINUTES) COM CARE-PRIMARY CARE CHYSHR ien 452 display flag= yes
- Aug 07, 2020 12:00 PM (30 MINUTES) COM CARE- PODIATRY CHYSHR ien 733 display flag = yes
- Aug 10, 2020 10:00 AM (30 MINUTES) COMCARE-NUTRITION CHYSHR ien 923 display flag = yes
- Aug 10, 2020 2:00 PM (15 MINUTES) NON VA CARE HCPS HEMODIALYSIS DENTAL CLINIC CHYSHR ien 1054 display flag = yes

**Comment by jbalboni** [comment]
I checked, these aren't coming through from vets-api, so I don't believe we're getting them from MAS.

**Comment by jbalboni** [comment]
According to @marcynadeau, these are now coming through for claudia.c.lapomarda@id.me:

![image (3).png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/0db9917f-b692-451a-97c8-fad09f30ad31)

**Comment by lenaecb** [comment]
@jbalboni - interesting... wonder why the provider information is showing?

Ok, so we're now seeing these in staging. Are there duplicates? Hard to tell probably currently. 

To dos to address this:
- For these appt types, we need to display 'Community Care Appointment' for the appt type (instead of VA Appointment)
- Show date/time
- Show confirmed
- do we know if we get any data from the booking notes field from VistA?

In legacy, when they were working through this, they were supposed to prompt the user with the following:
"This appointment is scheduled with a community provider. Please do not report to your local VA facility. If you have questions, please contact your facility community care staff at your local VA."

We should consider displaying this as well if we cannot get any additional data from the booking notes.

**Comment by jbalboni** [comment]
@lenaecb There won't be duplicates in this case, since Marcy created them in VistA for testing. Provider info is showing because that's the facility info for the appt and we're just treating it as a VA appt. We'd probably just hide that, I would think.

Those to-dos sound good. I believe someone said there's generally CC provider info in the booking notes, but it's going to be messy looking.

**Comment by lenaecb** [comment]
Closing and handling this issue in #9844
