### ISSUE TITLE
Access for Kaise Lafrai

### ISSUE THREAD

**Issue by kaise-lafrai** [department-of-veterans-affairs/va.gov-team#11650]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Kaise Lafrai
- Please Provide your email.
   > kaise.lafrai@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VACMS, Engineer, CivicActions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBL1j/33L9R+iHPwuWfSxShqHndLuffGHSuLjYpyI0XC4vqnqR6PcOAEQ6l3AA0MjQU89UfYBBqTPSIGxWPPwozKRKd7jauF5FZ+WOxYfW7AnGPzRo4D+e2+62Am1rUti/ZJ0Z/vWk1DmgGVzeHLjfKM+AG2oRGBstwtPpl5U2TdivhNaqKHTqp3gAlfPDZs92EecsJXhFKXfTdH/uf1sB9ZYMP4IIXi4xA00CDUDS/nU+yz3Dht8aNGEmF1I27njXyEGVn8kisEaDFXsY4ApSnVyAbHXvishMGVlgVEYXGEz4zGU597T5n07jGpgQAA905U1ivhZX52E+xF6uTCjxrQt49A+bRvpDd3GanpAfal2pFK+l78YgoMPKG1VRp/Wb/NQPrxACfgScmLjZUOSD5mFFqxRnW/egGtmj53VYcihvmW78AQG1+W/YfwdUgEGo9l2mOThMGOc6uHkvYtPJ+BjqONNq3W/zsi4VfiHyUVR/lWKkzwPCzB6MVm9PfVk= kaiselafrai@Kaises-MBP.fios-router.home
```

- Grant AWS Console access?
  > NO
  - Please give a brief description for why you are requesting AWS access.

**Comment by kaise-lafrai** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
