### ISSUE TITLE
[Analytics] Outline remaining potential products on product health MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1165]
## User Story
As DSVA and VSP Leadership, I need to know what products will be measured by Google Analytics on the product health mvp (version 1) so I can use those metrics in leadership and planning meetings.

## Goal
Add an outline of the products that are currently tracked on Google Analytics and that can be added to the Google Sheets product health MVP

## Acceptance Criteria
- [ ] Joanne: Add a template for potential products to current Sheet
- [x] Jon or Nedie: Verify that these products can be added
- [ ] @amycesal: Verify design
- [ ] _Stretch_ Joanne & Nedie: Meet with Unauthenticated Experience to verify forms that should be tracked
- [x] _Stretch or future issue_ Nedie or Jon: Add actual data
- [x] _Stretch or future issue_ Jon: Automate data

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Resources:
[Leah's list of products](https://docs.google.com/spreadsheets/d/1cbIvHce7AatnG4tDL_KGKDVLykTMSqSZDw6-5wrMJYk/edit#gid=0)
[Triage product list](https://docs.google.com/spreadsheets/d/1hzz6whEGoQJQbiNvIggirhydYYdv57nfOZfLvFqZ1pQ/edit?ts=5d41f8ed#gid=1535759874)

**Comment by nedierecel** [comment]
@joanneesteban Several new goals have been added to the Product Health MVP V1

@jonwehausen I noted a few of the pageview-driven Goals that have Events tied to them. In some cases, we will not have funnel completion rate; so we should note as N/A. Please let @amycesal know the next steps.

**Comment by joanneesteban** [comment]
First Column: number of submissions, number of page views, etc. Note the difference between forms and other 'products'. The non-forms aren't going to have event failures.

**Comment by joanneesteban** [comment]
@amycesal Can you add the "Missing Goals" on [this sheet](https://docs.google.com/spreadsheets/d/1ul4Dl98BdjdnGSmgF-0dWg_O3-rCukDOy8qghZXoJTo/edit#gid=0) to the MVP as 'nice to haves' at the bottom of the sheet?
