### ISSUE TITLE
[Backend] VA.gov and Lighhouse oAuth Strategies

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11669]
## Issue Description
Can we use VA.gov as our platform if there are Oauth gaps that will prevent our forms from showing health care data via lighthouse api's

Form speaking with Michael Bastos and Andy Parcel from the lighthouse team, they said that
Oauth strategies va.gov and lighthouse differ. The tokens on va.gov are not likely to have the correct scopes. This implies that vets-api logins are not compatible with the lighthouse health API. Lance said he is going to get more details and that it has to do with different SAML login strategies between V0 and V1 of vets api. We need a strategy to get a direction for how we are going to have an interface to the lighthouse health API. 

 The lighthouse team is aware of what they need to do but has not provided a specific timeline. They are aware that we are asking for timelines and we have to keep asking them about it. 

[Technical feasibility](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/README.md#lighthouse-health-api-compatability-with-vagov)

---
## Tasks
- [x] Document OAuth and Lighthouse authentication capabilities and gaps 

## Acceptance Criteria
- [x] Document lighthouse team's approach and solution

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/README.md#lighthouse-team-is-working-on-a-solution

**Comment by abuckley3385** [comment]
@massrb and @mdewey I feel like we have done quite a bit on this ticket but I don't see any comments or acceptance for this las sprint. Please update.

**Comment by massrb** [comment]
The lighthouse team has been having meetings on this but hasn't said anything definitive for us. I have been trying to make sure that the slack discussion continues with informational updates

https://lighthouseva.slack.com/archives/CB0DV4HC5/p1597094739210100

The last comment was: We have a sprint planning meeting tomorrow. We'll make sure this usecase is included in the discussion of priorities among the Lighthouse product owners. @Shawnee Petrosky - for your awareness.

**Comment by massrb** [comment]
Recent Conversation:
 
Laurence Guild  [9:53 AM]
Hi Dave, do you know anything about the meeting regarding the authorization issue for vets-api to connect to lighthouse health api ? There was supposed to have been a meeting on Friday. I have to keep asking for updates as that responsibility to try to keep tabs on it seems to have fallen on me.

Dave Mazik  [9:56 AM]
Hi Laurence.  I met with Patrick V. and Beau and others.  It seems we're on the path towards a solution with SSOe/IAM, but not clear on the timeline yet.

**Comment by massrb** [comment]
Beau Grantham, Dave Mazik, Shawnee Petrosky have been the primary people we have been speaking with on this in the last couple of weeks. 

August 24th update from Dave Mazik: 

Hi Dave,
Are there any updates on the lighthouse health api authorization for vets-api ? Do you have a ticket for that in zenhub or similar ?
New

Dave Mazik  8:49 AM
We are submitting  a service-request ticket with the IAM/SSOe team.   Their timeline will probably be the major factor of when this gets done.  We'll know more after our first intake meeting with them.

**Comment by abuckley3385** [comment]
@massrb @mdewey can we link to the Tech feasibility section where the research for this gap is documented and what exactly we are needing /wanting from Lighthouse to enhance to work with the va.gov auth. In addition, I believe the current description is a bit out of date so it might be nice just to have a couple sentences outlining the issue for a quick read.  Otherwise it really only has the updated requests for update.

**Comment by massrb** [comment]
Added documentation and acceptance criteria

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/README.md#lighthouse-team-is-working-on-a-solution
