### ISSUE TITLE
CMS export build should provide equivalent result to graphQL

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#11675]
## Overview
Make the CMS export build provide equivalent output to the one provided by the graphQL build

## Hypothesis or Bet
**If** _the CMS build provides equivalent output to the graphQL_ **then** _we can use it to replace graphQL_.

## OKR
_Make the build fast and scalable_

##### The html files generated by the CMS export build are equivalent to the ones provided by the graphQL build
Note that we say equivalent, not identical. There might be cases where we can decide to change or enhance the output.

### HTML and text files
1. Run the graphql build 
2. Rename the output dir
   1. mv build/localhost build/localhost.graphQL
4. Run the CMS export build
5. Do a diff on the two builds,  something like 
```
cd build
diff -r -wb localhost localhostGraphQL
```
6. Create tickets based on the differences
7. Repeat steps 4-6
### Other
* In the diff generated above check out files that only show in one build and not the other
* Do a du on both dirs. The results should be close

**Comment by drorva** [comment]
Check out the following[ pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/13620/files) thatprovides  a way to get the build to finish while we're resolving a bunch of issues.

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
