### ISSUE TITLE
Google Indexing Issue - Submitted URL Returns Unauthorized Request

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#11673]
## What happened?
As a Google Search Console Admin, I received a priority email from Google about an indexing issue: Submitted URL returns unauthorized request.  The page in question is: https://www.va.gov/disability-benefits/apply/dependents/

This means VA.gov submitted this page for indexing, but Google got a 401 (not authorized) response. Resolution step: Either remove authorization requirements for this page, or else allow Googlebot to access your pages by verifying its identity.

<img width="1136" alt="Screen Shot 2020-07-27 at 1 40 29 PM" src="https://user-images.githubusercontent.com/63107147/88573643-08dcdb00-d00f-11ea-94a1-56a8f56a5756.png">

## Specs:
- Device: Desktop and Mobile
- Browser: All
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: Once the issue is resolved, we can validate the fix via Google Search Console 
- Test User _(if applicable)_:

## Desired behavior
- Google Search Console validates the page/URL is fixed.

## Acceptance Criteria
- [ ] - Google Search Console validates the page/URL is fixed.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ncksllvn** [comment]
I think this page is listed in the sitemap.xml (so Google is attempting to index the page) but it's intentionally behind credentials. It looks like this page is an old form 686 that was never launched.

I think the fix here is to get that page out of the sitemap either by marking it as private or by just _not_ building it to production.

**Comment by johnhashva** [comment]
Gotcha -- a job for the Platform team or you/Kelson?

**Comment by ncksllvn** [comment]
I think the eBenefits team would do it because they're launching a revamped version of the form here soon. We could probably ask them to remove this old version that was never launched.

**Comment by johnhashva** [comment]
K, will add Matt Self to the ticket with a note.

**Comment by johnhashva** [comment]
@mattpointzxer0 making you and your team aware of this issue related to Site Map XML.
