### ISSUE TITLE
Analytics Implementation or QA Support for Find VA Forms - Search

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#11677]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
  - GA implementation > update to existing dashboard ([Find Forms Dashboard 1.0](https://analytics.google.com/analytics/web/?authuser=1#/dashboard/MHSfv0WxQySyKRB5IYyw1Q/a50123418w177519031p176188361/_u.date00=20190101&_u.date01=20191231&_.useg=builtin1/))

- Who is this request for?

    - Mickin Sahni
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    - Public Websites > Find VA Forms Search
    
- Provide the Domain where Google Analytics needs to be implemented
    - www.va.gov/find-forms
    
- Please provide any upcoming deadlines or important milestones
    - Update to existing product, no upcoming launches for Find VA Forms Search

## Requests
- Typical Website Interactions to Track

    - Add page views on `/find-forms` in order to calculate how many views convert to searches and PDF downloads
      - Existing GA dashboard: https://analytics.google.com/analytics/web/?authuser=1#/dashboard/MHSfv0WxQySyKRB5IYyw1Q/a50123418w177519031p176188361/_u.date00=20190101&_u.date01=20191231&_.useg=builtin1/

- Provide clarity on existing dashboard components (This might be a good conversation topic)
  - Are the Top 10 PDF numbers counting downloads from Find VA Forms Search or from all potential places **across** VA.gov a user might download a particular form?
  - Same question for the [GSA Outbound Clicks](https://www.va.gov/find-forms/?q=djfklasdjfldsjafl) — are those clicks across VA.gov or just Find VA Forms?

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @MickinSahni ! Acknowledging receipt here. We'll be in touch soon.

**Comment by MickinSahni** [comment]
Thanks! I added an additional request around some questions we had re: existing components on the dashboard.

**Comment by jonwehausen** [comment]
@bmcgrady-ep to start on dashboard adjustments

**Comment by bmcgrady-ep** [comment]
@MickinSahni - I have updated the Find Forms Dashboard 1.0 with your requests above. Let me know if that's what you are looking for.

**Comment by bmcgrady-ep** [comment]
Hi @MickinSahni - Following up from last week. The Find Forms Dashboard 1.0 has been updated with your requests above. Let me know if anything else needs to change. Thanks!

**Comment by MickinSahni** [comment]
> Hi @MickinSahni - Following up from last week. The Find Forms Dashboard 1.0 has been updated with your requests above. Let me know if anything else needs to change. Thanks!

Thanks so much, Ben.

The ultimate goal is to understand two relationships:
1. the relationship between people who come to the Find VA Forms experience (pageviews) and the % of people who complete a search (queries)
1. the people who complete a search and the % of people who download a PDF 

For the first one, is it possible to provide a page views chart similar to *Total Unique Searches*? Or perhaps, is it possible to overlay the two on each other? 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/13204473/90464388-329f9400-e0db-11ea-889b-2714858a91e7.png">


The second one is a new request so understand if it might take more time. I'm not sure if a table or a line diagram is best for this. One row in a table would be something like:

Query | Query volume | PDF download volume
|---|---|---|
forms | 1,251 | 512
jobs | 912 | 391

Is there a way to depict one and two on the dashboard?

**Comment by bmcgrady-ep** [comment]
@MickinSahni Here is a link to a custom funnel report for the second request: https://analytics.google.com/analytics/web/template?uid=XXOelA-rT4KjlCBLWHcFUA

Also, I have updated the pageviews chart to be the same format as the Find Forms Search chart. Let me know what you think.

**Comment by MickinSahni** [comment]
Thanks, Ben! Do we know why the report search volume (Search to PDF Downloads) is lower than the dashboard search volume (Total Unique Searches - Find Forms)? |

(Both are for Aug 17, 2020-Aug 23, 2020)

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/13204473/91082309-83047d80-e616-11ea-86b2-0f449a92de92.png">

**Comment by bmcgrady-ep** [comment]
@MickinSahni - The Custom Funnel is using a different metric (Sessions) than the Total Unique Searches - Find Forms graph (Total Unique Searches). Unfortunately, Total Unique Searches is not available to be used in the custom funnel report, but I am working on a solution that will get these numbers closer. Meanwhile, I updated the custom funnel and it is now a little closer to the Total Unique Searches - Find Forms graph.

**Comment by MickinSahni** [comment]
> @MickinSahni - The Custom Funnel is using a different metric (Sessions) than the Total Unique Searches - Find Forms graph (Total Unique Searches). Unfortunately, Total Unique Searches is not available to be used in the custom funnel report, but I am working on a solution that will get these numbers closer. Meanwhile, I updated the custom funnel and it is now a little closer to the Total Unique Searches - Find Forms graph.

Thanks for your work, Ben. 
Could you clarify the impact/implications of using sessions instead? Is it that the searches on the custom report aren't considered unique? 

I checked it out this morning and the Unique Searches are at ~42k whereas the custom report searches are at ~29k. 

Is the PDF download count on the custom report *also* not unique? 
My thinking is that we might be able to rely on teh Unique Searches count as the denominator and the PDF Download rate on the Report as the numerator, but that would require the PDF Download rate is also based on unique downloads.

**Comment by bmcgrady-ep** [comment]
@MickinSahni - Yes, the custom report is based on session, which basically means that it is only counting one search per session. The Total Unique Searches is unique only for the **same keyword during the same session**. This means that if a user is searching for **1995** and **10203**, 2 unique searches are counted. In the goal funnel, I believe it would only count as one, since it is session-based.

Unfortunately due to GA's limitations, we can't replicate the report that you are asking for in the goal funnel. However, this would probably be a possibility in BigQuery.

**Comment by MickinSahni** [comment]
Morning, Ben. To confirm—the PDF download rate on the funnel is also session-based, right?

**Comment by bmcgrady-ep** [comment]
Good morning, @MickinSahni - yes, the PDF download rate on the funnel is also session-based.

**Comment by bmcgrady-ep** [comment]
Hi @MickinSahni - I updated the Custom Goal Funnel. It still doesn't match the dashboard, due to the session limitation, but it should be accurate within each session. Let me know if you have any questions.

**Comment by joanneesteban** [comment]
@MickinSahni @brianalloyd - Checking in on this. Is it okay to close this ticket, or do y'all need anything further?

**Comment by MickinSahni** [comment]
Thanks, team. Nothing at this point so feel free to close. 

For context, we're working the form detail pages. 
After that, we'll connect results in this search experience to those individual form detail pages. 

That means we have at least one more analytics request (to determine conversion rate) for this search experience to look forward to. 

Appreciate the help as always :)
