### ISSUE TITLE
Specialty wait times

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11676]
## What happened?
During v1 migration, data format changed, impacting our wait times/satisfaction scores displays on Facility Detail pages. A similar issue [#8009](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8009) has been resolved in this sprint. 

**Current behavior:**
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/4d19cc10-fb2d-41fb-a412-2b5c28edbabf)

**Expected behavior:** 
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/f61ee336-b4a5-4193-8410-1b52cd8cd853)

## Desired behavior
Wait times under specialty care should be expressed by `name of specialty: # of days`

Related issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10094

## Acceptance Criteria

- [ ] When Veteran views the Facility Detail page for a VA health location, the satisfaction/wait time data should be expressed by name of specialty: # of days
- [ ] wait time for new and existing patients should be accurate and valid

 
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Confirming that sentence case should be used consistently for all parts of the facility detail page (Services list AND Appointments). The services listed in the Appointment were overlooked in the original acceptance criteria. 

Relevant exceptions: Proper nouns and the word "Veterans"
(From the [style guide](https://design.va.gov/content-style-guide/capitalization))

**Comment by brangi** [comment]
Merged
