### ISSUE TITLE
Update GA for connected apps

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#11684]
In terms of GA, we need to mirror the Direct Deposit call in connected apps, like so:

```
{
  'event': 'profile-get-connected-apps-retrieved',
  'user-has-connected-apps': true|false
}
```

And we also need to record connected apps API failures, like so:

`'event': 'profile-get-connected-apps-failure'`

**Comment by bsmartin-ep** [comment]
Hi @sanlouise -

To mirror the Direct Deposit events in Profile, I think we'll need 3 events:

```
{
  'event': 'profile-get-connected-apps-started'
}
```
```
{
  'event': 'profile-get-connected-apps-failure'
}
```
```
{
  'event': 'profile-get-connected-apps-retrieved',
  'user-has-connected-apps': true|false
}
```

Let me know if you have any questions.
