### ISSUE TITLE
Analytics Implementation or QA Support for View Payment History

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11687]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics Implementation

- Who is this request for?
    - Jason Wolf: @jason-gcio or @Jason (slack)
    - Micah Chiang: @micahchiang or @Micah Chiang (slack) and/or Jesse Cohn: @cohnjesse or @Jesse Cohn (slack)
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - eBenefits Team, View Payment History
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_

    _Identify if PII is passed in URL or title tag_
    No
    - https://staging.va.gov/va-payment-history/payments/
- Please provide any upcoming deadlines or important milestones
    _ex: launch_

    - Aug/Sept Launch
     
- Typical Website Interactions to Track
    
    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
      - https://www.va.gov/va-payment-history/payments/
      - https://www.va.gov/profile
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
      - Pagination

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Any, currently hardcoded

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Any, currently hardcoded

- Certain conditions/responses that need to be reviewed

    - Test payment data

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
### Datalayer Specification

@jason-gcio @cohnjesse @micahchiang 

Description of Interaction | DL / event specification 
------------ | -------------
Triggered on each initial start of the API call to return payment history | `'event': 'view-payment-history-started'`
Triggered on each successful return of payment history data from API | `'event': 'view-payment-history-successful'`
Triggered on each failed return of payment history data from API | `'event': 'view-payment-history-failed,'`<br>`'error-key': 'XXX_description_of_error'` 

**Dev Notes**
- The `error-key` is a concatenation of the error code (400 or 500) with a relevant description of the error separated by underscores.

**Comment by micahchiang** [comment]
@jonwehausen - for `'error-key': 'XXX_description_of_error'` - Can you clarify: are we inserting the actual string `_description_of_error` Or are you asking for something that describes the error i.e. `503_internal_server_error`?

**Comment by jonwehausen** [comment]
Hi @micahchiang ,

Good question, that's your discretion, whatever you all feel like is descriptive enough to understand what happened in the event of an error...`503_internal_server_error` is totally fine.

**Comment by jonwehausen** [comment]
@bsmartin-ep When you have capacity if you could stage the GTM implementation here that would be great.

**Comment by bsmartin-ep** [comment]
Thinking something like this for the Event structure @jonwehausen ?

eventCategory: "API Calls", 
eventAction: "View Payment History - Started", 
eventLabel: "view-payment-history-started"

![image](https://user-images.githubusercontent.com/62304138/90796481-60542b00-e2dd-11ea-824d-2760678a6ad7.png)

[GTM workspace WIP](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000357)

**Comment by jonwehausen** [comment]
### QA Testing

Description of Interaction | Tag Screenshot | Test Status
------------ | ------------- | -------------
Started API Call for Payment History | ![image](https://user-images.githubusercontent.com/48527022/92415994-5c236c80-f129-11ea-8486-a1c4a41cfb55.png)<br><br>![image](https://user-images.githubusercontent.com/48527022/92415985-50d04100-f129-11ea-861c-3360029d90b3.png) | ✔️ **PASS**
Successful API Call for View Payment History | ![image](https://user-images.githubusercontent.com/48527022/92416104-e23fb300-f129-11ea-86e7-59c63a3dc0f8.png)<br><br>![image](https://user-images.githubusercontent.com/48527022/92416096-d653f100-f129-11ea-87c4-328f613b01e0.png) | ✔️ **PASS**

@jason-gcio @micahchiang @bsmartin-ep this tracking has been published and is ready to move to production at your earliest convenience
