### ISSUE TITLE
Accessibility Feedback for Usability Testing Prep - BAM2 [Debt Letters MVP]

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#11692]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Point of Contact

**VFS Point of Contact:** Jennifer (VSA) & Trevor (VSP)

## Description

This ticket houses accessibility feedback for the Usability Testing Prep Debt Letters MVP.

### Must

1. Please provide Jennifer with the url for where the debt letter PDFs are stored. These **must** be provided to the VA 508 Office who will contact the owner of those to ensure they are 508-compliant.

1. Since UXPin may not be usable for those using IE and various assistive technology, Perigean **must** be provided the constraints. See the [guidelines for Inclusive research](
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/resources/inclusive-research-recommendations.md#guidelines-for-inclusive-research-recruiting).

### Should

1. In the prototype, suggestions that **should** be incorporated are noted to include jump links to the right rail info, so that people know how to pay debt, get help. One of the reviewers didn't notice the option to dispute a debt, as it was at the bottom of the right rail. The info in the right rail is unlikely to be seen by mobile users. Since debt may be a trigger, this info **should** have higher visibility.

### Consider

1. **Consider** providing the participant recruiting requirements in the pattern documented in the [guidelines for Inclusive research](
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/resources/inclusive-research-recommendations.md#guidelines-for-inclusive-research-recruiting). This way Perigean will receive requirements in a consistent pattern. 
1. For the participants, **consider** including at least one user with an identified cognitive disability, especially anxiety or depression, as noted in the guidelines for inclusive research.. 
1. **Consider** asking research participants if they're more interested in hearing what type of debt, or how much is owed for this particular debt. To me, it's more valuable to understand how large the debt is, than who it's owed to. Debt is debt, and all creditors are roughly equal, no? 

**Question from @1Copenut** - Is there any way to know how much I owe in total? Previous challenges for anxiety, depression, et al. not withstanding, I feel it would be beneficial to know how much one owes in sum, somewhere.

## Definition of done

1. Review and acknowledge feedback.
1. Document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions.

Reading for review, @1Copenut .

**Comment by rileyorr** [comment]
Thank you for the feedback, @jenstrickland! 

> Please provide Jennifer with the url for where the debt letter PDFs are stored. These must be provided to the VA 508 Office who will contact the owner of those to ensure they are 508-compliant.
@leahkeeler is there a point of contact within VBMS that Jen can forward to the 508 Office? 

> Since UXPin may not be usable for those using IE and various assistive technology, Perigean must be provided the constraints. See the guidelines for Inclusive research.
I've added all your feedback pertaining to the research guide. I didn't see any verbiage around UXPin not being accessible with IE; should we add that to the inclusive research doc? 

> Consider asking research participants if they're more interested in hearing what type of debt, or how much is owed for this particular debt. To me, it's more valuable to understand how large the debt is, than who it's owed to. Debt is debt, and all creditors are roughly equal, no?
What portion of the design are you referring to for this question? Some contact center representatives specialize in certain types of debt, so it's important to know what the debt type is so the Veteran can contact the correct department. 

> Question from @1Copenut - Is there any way to know how much I owe in total? Previous challenges for anxiety, depression, et al. not withstanding, I feel it would be beneficial to know how much one owes in sum, somewhere.
Our team did chat about adding this data a few weeks ago! @camerontesterman wasn't there a technical constraint that prevented us from being able to show how much a Veteran owes in total? Or perhaps I'm misremembering...

**Comment by 1Copenut** [comment]
@jenstrickland Looks great. VSP has no additional comments.

**Comment by jenstrickland** [comment]
@rileyorr Ah, sorry! I got the VA work mixed with resources for my talk. 

For UXPin we want to be sure to let Perigean know we won't be able to support IE users — until we hear otherwise from UXPin. I did contact Marcin Treder about it. For now, yes, we should add it to the guidelines. Thank you!

Regarding the PDF, can you provide a sample url? That's enough for me to provide the 508 office.

> What portion of the design are you referring to for this question? Some contact center representatives specialize in certain types of debt, so it's important to know what the debt type is so the Veteran can contact the correct department.

> Consider asking research participants if they're more interested in hearing what type of debt, or how much is owed for this particular debt. To me, it's more valuable to understand how large the debt is, than who it's owed to. Debt is debt, and all creditors are roughly equal, no?

The above was a consider from Trevor. I recognize there are a lot of moving parts — and this is the MVP. I know this has to launch quickly, and will be iterated on. I think to Trevor's question, it would be possible to ask research participants if they'd want to know the total of their debt(s) at certain points. 


At the end of the day, this is the MVP, and it will be iterated on. :)

**Comment by rileyorr** [comment]
> Regarding the PDF, can you provide a sample url? That's enough for me to provide the 508 office.

Of course! We have a [GitHub folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/debt-letters-mvp/letter-samples) containing sample letters. Let me know if works for you!

**Comment by jenstrickland** [comment]
Would the PDF link to one in the repo, or one on a VBMS site?

**Comment by rileyorr** [comment]
Sorry for misunderstanding what you're looking for! Those all link to the repo. I don't have a sample PDF that links directly from VBMS. 
@camerontesterman or @bradl3yC, are we able to provide that info for Jen?

**Comment by bradl3yC** [comment]
@jenstrickland @rileyorr I don't believe so - the download links require user authentication.  @camerontesterman would you agree?

**Comment by jenstrickland** [comment]
I don't need an actual PDF, rather the path. What we're looking to uncover is who owns those PDFs, so we can send the VA 508 Office to work with them and make them compliant.

**Comment by bradl3yC** [comment]
@jenstrickland the path wont help you as it goes directly to vets-api.  From there, it gets forwarded on to the VBMS system.  VBMS owns the PDFs.

**Comment by jenstrickland** [comment]
Thank you, @bradl3yC ! 

@leahkeeler — can we connect to document this accurately, so I can bring to the VA 508 Office? They'll work with VBMS to have them remediate their PDFs.

**Comment by leahkeeler** [comment]
Yes absolutely @jenstrickland - i will try to get a name today to start the conversations.

**Comment by jenstrickland** [comment]
@leahkeeler Do we have a name for the people in VBMS who own the PDFs? That way I can provide it to the VA 508 Office for them to reach out and ensure all PDFs are 508 compliant or have a plan to remediate (ahead of the October congressional report).

**Comment by leahkeeler** [comment]
HI Jen, Here are the VBMS contacts for you : 

VBMS PM – Clyde Miller – clyde.miller@va.gov

VBMS Intake Manager – Michael Pohlman – Michael.pohlman@va.gov

**Comment by jenstrickland** [comment]
Thank you, @leahkeeler . I just added the info to the staging review, and will carry over to the Full A11y & 508 Office Audit, so I provide the VA 508 Office with that info. I know my contact is going to be OOO for the coming three weeks, so I'll hold the info for then. 

If you have a relationship with Mr. Miller and Mr. Pohlman, please consider having them reach out to the VA 508 Office for assistance ensuring their PDFs are all 508 compliant. The sooner they reach out the better, and they'll be able to work with someone other than my contact. Congress requested a large 508 compliance report from the VA, and they have to deliver it in October. It would be great if all of their PDFs were compliant, or there was a plan documented for ensuring they are. 

Otherwise, my contact will follow up during the full audit.
