### ISSUE TITLE
Stevan Onboarding to VSP Ops

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11699]
# Ops Onboarding
## Overview 
Welcome to the platform and more particularly the VSP Operations team.  This ticket is a checklist and guide to try and improve the onboarding process and get you up to speed. 

If you have any questions/need access please reach out to TJ. 

### Access to what you need
- [ ] [Getting setup](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md#request-access-to-tools)
- [ ] Share your calendar with VSP; vsp-team.group@adhocteam.us

### Understanding VSP and where we sit
- [ ] [Overview of VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Welcome%20to%20VSP.md#welcome-to-the-veteran-facing-services-platform)
- [ ] [Getting to know VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/vsp-team-member-onboarding.md)
- [ ] [Overview Presentation of VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/VSP%20Mission%2C%20Objectives%2C%20Roadmap%2C%20and%20OKRs%20-%207-23-19.pdf)

### VSP Operations
High level:
- [ ] [High level info of the team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/operations#operations)
- [ ] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/operations-team-charter.md#operations-team-charter)
- Meet the members of the team
  - [ ] Demian
  - [ ] Taylor
  - [ ] Jeremy
  - [ ] Julian
  - [ ] Bill
  - [ ] Faith 
  - [ ] TJ

More details on our work: 
- [ ] [Infra recommit work](https://docs.google.com/document/d/1cVFlFXuwjg_dbapwiCZ-iT01mywcZdHBhfzPjAq-7TI/edit)
- [ ] [VSP Onboarding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/onboarding.md)
- [ ] [Oncall role](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/daytime-oncall-support-role.md)
 - [ ] Talk with TJ about Sprint Objects 
- When creating an issue in GH, make sure to use the “ops issue template”

### Overviews 
- [ ] [VA Network Overview](https://dsva.slack.com/archives/CJYRZK2HH/p1568982910041200)
- [ ] [Our current BRD overview](https://zoom.us/rec/play/usUrd-6s_z83HdHGuQSDBaUrW47ue6ysg3Udr_NYyku2VHJXMwegb7BBardDXyrOvVEQ0Rn8j_5pt9Op?autoplay=true&startTime=1570553770000)
- [ ] [Ansible Overview](https://zoom.us/rec/play/uMB7druurjI3S9GWsASDC_d7W9S0Jvms0Ccd8vMJzEqwBXRRO1D3ZrQRM-brWsd8PNfawPVTesdwLrG7?autoplay=true&startTime=1571860777000)
- [ ] [Grafana overview](https://zoom.us/rec/play/uZR_I--o_zo3GdDH4gSDBqd7W426J_qs2ylL-_ZeyEy8BnRVZwKkZ7MWZOAtXA9N7YhPyRvLuov228GF?autoplay=true&startTime=1573063037000)
- [ ] [Overview of Service Now](https://zoom.us/rec/play/vJModuGupm43HdeW5QSDVqArW9W6L_6s1nAb-aUNnknhWnEBOlGnNeERMeLqy001uOwCdfqvWAk6x2e-?autoplay=true&startTime=1584040023000) 
- [ ] [ Review instance](https://dsva.slack.com/archives/CTYQL39FE/p1594849624096000)
- [ ] [ESECC](https://zoom.us/rec/share/xpB7Mr3V23pOeaeW73rhd7caP7b5eaa80yJP-vdcxUiJ5VTJjk44QQ74tP0AZFMX?startTime=1595520188000)
- [ ] [Rev/Fwd Proxy deep dive](https://zoom.us/rec/share/3ItcHryrz0RIYbfxy1n_cYcAHYfqX6a8hyUe8_oIzk9qo1FhjHypmapEa7VsGxWd?startTime=1589400199000)
- [ ] [ATO Overview](https://zoom.us/rec/share/19ZPDKut-k9JSKPx1nrFZIoNOMO1X6a8hikZ-qZYnhqgN8T_naYWLWli2Jcy50wm?startTime=1586362492000)

**Comment by jbritt1** [comment]
I would change `Daytime oncall role` to just `Oncall role` since we did away with day/night shifts

**Comment by pnwstevan** [comment]
@ricetj THANK YOU for gathering all this for me; super helpful and appreciated.  Feel free to assign to me as I have access to Zenhub now.

**Comment by ricetj** [comment]
> @ricetj THANK YOU for gathering all this for me; super helpful and appreciated. Feel free to assign to me as I have access to Zenhub now.

hmm looks like you are not in the org yet. This is a public repo, so I guess that is why you can comment on stuff hmmm.

**Comment by jbritt1** [comment]
> > @ricetj THANK YOU for gathering all this for me; super helpful and appreciated. Feel free to assign to me as I have access to Zenhub now.
> 
> hmm looks like you are not in the org yet. This is a public repo, so I guess that is why you can comment on stuff hmmm.

Nancy [submitted one for him yesterday](https://github.com/department-of-veterans-affairs/github-user-requests/issues/3601), just hasn't been pick up yet

**Comment by ricetj** [comment]
> > > @ricetj THANK YOU for gathering all this for me; super helpful and appreciated. Feel free to assign to me as I have access to Zenhub now.
> > 
> > 
> > hmm looks like you are not in the org yet. This is a public repo, so I guess that is why you can comment on stuff hmmm.
> 
> @ricetj, Nancy [submitted one for him yesterday](https://github.com/department-of-veterans-affairs/github-user-requests/issues/3601), just hasn't been pick up yet

Looks like @pnwstevan is now in the GH Org 🎉

**Comment by ricetj** [comment]
ok nevermind, we can assign him now, but still not in the Org 😞

**Comment by pnwstevan** [comment]
Ok, NOW I'm in the Org! 🎉

Looks like there may still be a few access/permissions issues though.  

For example, I can now see this page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/daytime-oncall-support-role.md

But can't see:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/OnCall

or anything under https://github.com/department-of-veterans-affairs/devops/

Progress though! ;)

**Comment by ricetj** [comment]
> Ok, NOW I'm in the Org! 🎉
> 
> Looks like there may still be a few access/permissions issues though.
> 
> For example, I can now see this page: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/daytime-oncall-support-role.md
> 
> But can't see:
> https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/OnCall
> 
> or anything under https://github.com/department-of-veterans-affairs/devops/
> 
> Progress though! ;)

Hey @pnwstevan you should be good to go for those repos now. If It a try and let me know.
