### ISSUE TITLE
[FE] at some medium-width screen sizes, contact info editing is cramped

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#11695]
We'd likely need to move away from the [float-grid](https://design.va.gov/layout/float-grid) we're currently using now and switch to using a [flex box grid](https://design.va.gov/layout/flexbox-grid) with responsive prefixes to make the right hand column wider at tablet sizes before shrinking back to 2/3s width at wider screens.

![edit address narrow screen 2.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/1071e53f-501d-479c-b5b0-53fcab5fc39b)
![edit address narrow screen.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/0b5c2642-f146-4262-bd1f-70cdd60155d0)

**Comment by erikphansen** [comment]
tagging @tressaellen for awareness

**Comment by erikphansen** [comment]
@tressaellen should confirm this looks decent when she gets back.

**Comment by erikphansen** [comment]
@tressaellen PING!

**Comment by tressaellen** [comment]
@erikphansen this looks more than decent - it looks great!
