### ISSUE TITLE
Triage & address Cypress implementation feedback from VSA Auth Exp

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#11693]
## User Story 

As a VFS engineer, I need to easily understand and learn Cypress, so that I can quickly take advantage of its features.

## Definition of Done 
- [ ] Triage feedback to determine what needs to be fixed before Cypress rollout
- [ ] Make tickets for additional items to be addressed in future, label with `tools-fe` and place in `backlog`

## Feedback from VFS engineer

I found a link to this documentation https://github.com/department-of-veterans-affairs/va.gov-team/blob/6dccdd3ac61d7fbfa8b30e317230cc9212a7c9f8/teams/vsp/teams/tools/frontend/cypress-migration-guide.md from https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test, which is where I started. I also referred to the official Cypress docs as well as the Cypress Testing Library docs (because I somehow knew we were using that) (edited) 

4:22
I also looked at the one non-form test I could find, which was written by the VAOS team, to get an idea of how to write tests with Cypress.

4:23
Our docs mention how to run an axe check (https://github.com/department-of-veterans-affairs/va.gov-team/blob/6dccdd3ac61d7fbfa8b30e317230cc9212a7c9f8/teams/vsp/teams/tools/frontend/cypress-migration-guide.md#cypress) but fail to mention that you might need to call cy.injectAxe() first. A note about that should probably be added. (edited) 

4:27
In my opinion our docs should be opinionated about best practices. Specifically I think it should strong encourage people to use Testing Library queries, especially findByRole() to query the DOM while using findByTestId() as a fallback. It should discourage using cy.get(<css selector>) to query the DOM.

4:28
That's about it. While Cypress was totally new to me, I probably did more of my own learning about Cypress than a typical user would so I'm probably not the best one to comment on how well the docs work to get someone started from ground zero.

4:28
I did a talk about my experience writing my first test at the VSA FE meeting on Friday. I'll see if I can find a video of it.

4:31
Hopefully a link to the video will be shared here eventually https://dsva.slack.com/archives/C5HP4GN3F/p1595611087224600

from our docs:
With the test runner, you are able to use Cypress's "Open Selector Playground". This allows you to click on elements in the DOM and copy that element's selector to use in your test. This means there's usually no need to manually inspect an element and copy the selector.

This is, IMO, exactly what we should not be doing to find elements in the DOM, unless that targeted element has a data-testid assigned. Otherwise it's going against even Cypress's best practices https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements

this section should probably mention our cy:open and cy:run commands https://github.com/department-of-veterans-affairs/va.gov-team/blob/6dccdd3ac61d7fbfa8b30e317230cc9212a7c9f8/teams/vsp/teams/tools/frontend/cypress-migration-guide.md#running-tests- (edited) 

4:50
Which reminds me that yarn cy:run didn't work locally for me. It just seemed to hang.

**Comment by meganhkelley** [comment]
@U-DON you mentioned that you already addressed this feedback, correct? If so please confirm & close this ticket. Thanks!

**Comment by U-DON** [comment]
Migration doc has been updated to address the feedback.
