### ISSUE TITLE
Re-Enable ESLlint rules

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#11691]
To be able to upgrade ESLint to v. 7, some rules needed to be diasbled to complete the upgrade.

These rules need to be enabled again:

```
/* ----- TODO: evaluate and potentially turn these rules back on ----- */

    /* TODO | DISABLED TEMPORARILY */
    "max-classes-per-file": 0, //1
    "no-buffer-constructor": 0, //13
    "prefer-promise-reject-errors": 0, //14
    "func-names": 0, //14
    "no-restricted-globals": 0, //28
    "no-else-return": 0, //41 (fixable)
    "no-unused-vars": 0, //61
    "prefer-object-spread": 0, //78 (fixable)
    "lines-between-class-members": 0, //103 (fixable)
    "prefer-destructuring": 0, //261 (fixable)

    "react/jsx-fragments": 0, //2 (fixable)
    "react/jsx-closing-tag-location": 0, //3 (fixable)
    "react/no-typos": 0, //5
    "react/state-in-constructor": 0, //7
    "react/no-unused-state": 0, //15
    "react/sort-comp": 0, //23
    "react/default-props-match-prop-types": 0, //44
    "react/static-property-placement": 0, //50
    "react/jsx-wrap-multilines": 0, //60 (fixable)
    "react/jsx-curly-brace-presence": 0, //71 (fixable)
    "react/no-access-state-in-setstate": 0, //79
    "react/jsx-curly-newline": 0, //95 (fixable)
    "react/button-has-type": 0, //196
    "react/jsx-props-no-spreading": 0, //767
    "react/jsx-one-expression-per-line": 0, //2188 (fixable)
    "react/destructuring-assignment": 0, //3010

    "jsx-a11y/control-has-associated-label": 0, //7
    "jsx-a11y/click-events-have-key-events": 0, //10
    "jsx-a11y/anchor-is-valid": 0, //19
    "jsx-a11y/label-has-associated-control": 0, //35
    "jsx-a11y/label-has-for": 0, //66

    "import/named": 0, //2
    "import/no-useless-path-segments": 0, //59  (fixable)
    "import/no-cycle": 0, //105
    "import/order": 0, //544 (fixable)
```

**Comment by mchelen-gov** [comment]
:heavy_plus_sign: for enabling `no-unused-vars`
i'm guessing the number after the `//` is the number of errors from that rule?

**Comment by jhonnyoddball** [comment]
> ➕ 1️⃣ for enabling `no-unused-vars`
> i'm guessing the number after the `//` is the number of errors from that rule?

That is correct!

**Comment by mpelzsherman** [comment]
Is it necessary for ALL of these rules to be re-enabled in one go? Or can we break this up into smaller chunks?

I'm happy to lend a hand if you need help with this. I'm particularly missing `no-unused-vars`.

**Comment by jhonnyoddball** [comment]
> Is it necessary for ALL of these rules to be re-enabled in one go? Or can we break this up into smaller chunks?

Well, I usually take 1 at the time. In addition, I have to group the errors by code owners and create multiple PRs for each code owner per rule.

> I'm happy to lend a hand if you need help with this. I'm particularly missing `no-unused-vars`.

Yeah, absolutely!

cc: @meganhkelley

**Comment by bkjohnson** [comment]
As an update, I'm working on fixing the issues around `no-unused-vars` right now.

**Comment by timwright12** [comment]
I'm going to start chipping away at this one

**Comment by timwright12** [comment]
Working on the jsx/a11y linting rules first. Initial run turned up 231 errors. I'm fixing small ones and reaching out to teams for big issues that require more context to fix. Will likely turn these on as warnings until they're cleared out.

**Comment by bkjohnson** [comment]
I don't know if the issues are distributed conveniently enough for this to work without a lot of tedious effort, but we could [use overrides](https://eslint.org/docs/user-guide/configuring/configuration-files#how-do-overrides-work) to selectively turn those warnings into errors for certain directories. This could make sure that they don't appear anywhere where they didn't already exist.

**Comment by timwright12** [comment]
Opened up a PR that should only turn on jsx-a11y linting error on changed files, so if someone is in there making changes they'll have to also fix the issues:

https://github.com/department-of-veterans-affairs/vets-website/pull/20034

We can use this as a mechanism for the rest as well moving forward
