### ISSUE TITLE
Update coronavirus language on Facility Locator search home page. 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11690]
## Description
The coronavirus banner on the Facility Locator home search page needs to be updated
- It's been 6 months and Veterans understand the routine information
- Veteran research indicates the size of the banner might cause confusion about the search functionality

**Current behavior**
**Coronavirus update:** For questions about how COVID-19 may affect your health appointments, benefits, and services, use our [coronavirus chatbot](url). Many locations have changing hours and services. For your safety, please call before visiting to ask about getting help by phone or video. We require everyone entering a VA facility to wear a cloth face covering. [Learn more about this requirement.](url)

Expected nehavior: (TBD)

**Comment by davidconlon** [comment]
[Revised COVID Update Facility Locator Text.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5007285/Revised.COVID.Update.Facility.Locator.Text.docx)
