### ISSUE TITLE
STEM: Update Google Analytics for the 22-10203

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11706]
## Assumptions
1. This work is completed behind the feature flag #7271.
2. The following standard form tracking has been added to the 22-10203
   a. All of the following steps in the form process include the corresponding dataLayer event described in the table: 

   Step in Form Process | Interaction | dataLayer Event
-- | -- | --
Form Starts | Form Start - Starting application without logging in | `no-login-start-form`
Form Starts | Form Start - Call-to-action to Sign In to start form | `login-link-clicked-cta-form`
Form Starts | Form Start - Begin form button after successful sign in | `login-successful-start-form`
Form Saves and Submissions | Form Saves - Event is triggered for auto form saves | `edu-10203-sip-form-saved`
Form Saves and Submissions | Form Prefill Failures - Tracks when form prefill cannot be retrieved | <product>`edu-10203-sip-form-prefill-failed`
Form Saves and Submissions | Form Submission - Measure the form submission; Success and failures are measured distinctly | `edu-10203--submission`
Form Saves and Submissions | Form Submission Successful - Triggered when the form has been successfully submitted | `edu-10203--submission-successful`
Form Saves and Submissions | Form Failures - Triggered when the form has failed client or server-side | `edu-10203--submission-failed`
   
## Acceptance Criteria
1. The following submission tracking has been added to the 22-10203
   a. The following standard additional context dataLayer variables are added to the `--submission-successful` and `--submission-failure` events:  

   dataLayer Variable | Description of Form Submission Variable | Screenshot 
-- | -- | -- 
`'edu-benefits-currently-used'` | Populates with a **concatenated string** seperated by a space for each of the checkboxes checked from `/eligibility` page | ![image](https://user-images.githubusercontent.com/48527022/88176055-bd809200-cbf4-11ea-95ed-462c2cfb72ec.png) 
`'edu-currently-enrolled'` | Populates with 'Yes' or 'No' based on answer to "Are you enrolled in a science, technology, engineering, or math (STEM) undergraduate degree?" | ![image](https://user-images.githubusercontent.com/48527022/88176336-19e3b180-cbf5-11ea-9735-2c238dea0c75.png)
`'edu-benefits-remaining'` | Populates with answer to "About how much of your education benefit do you have left?" | ![image](https://user-images.githubusercontent.com/48527022/88176616-8d85be80-cbf5-11ea-9486-507a09d3d3e4.png)
`'edu-name-of-degree'` | Populates with answer to "Whats the name of your stem degree" |![image](https://user-images.githubusercontent.com/48527022/88176683-a3937f00-cbf5-11ea-8608-2b12dce43e71.png)
`'edu-stem-scholarship-school'` | Populates with answer to "Whats the name of the school where you plan on using the Rogers STEM Scholarship?" | ![image](https://user-images.githubusercontent.com/48527022/88176748-be65f380-cbf5-11ea-82fb-0604995d47d1.png)
`'edu-school-city'` | Populates with answer to school city | ![image](https://user-images.githubusercontent.com/48527022/88176966-143a9b80-cbf6-11ea-9dc7-e38fd9f50a14.png)
`'edu-school-state'` | Populates with answer to school state | ![image](https://user-images.githubusercontent.com/48527022/88177019-2b798900-cbf6-11ea-846a-b7e205580910.png)
`'active-duty'` | Populates with answer to "Are you currently on active duty or will you be going on active duty while receiving the Rogers STEM Scholarship?" | ![image](https://user-images.githubusercontent.com/48527022/88177069-421fe000-cbf6-11ea-8c2c-3bf8bd0ee28a.png)
`'contact-method-preference'` | Populates with answer to "How should we contact you if we have questions about your application?" | ![image](https://user-images.githubusercontent.com/48527022/88177146-611e7200-cbf6-11ea-8b40-60c7e638722d.png)
`'direct-deposit-account-type'` | Populates with answer to "Account type" | ![image](https://user-images.githubusercontent.com/48527022/88177226-81e6c780-cbf6-11ea-9a5e-ecc5f5eff063.png)
`'edu-pursuing-teaching-certifcation'` | Value for "Are you pursuing a teaching certification" | ![image](https://user-images.githubusercontent.com/48527022/88730194-8c77f400-d103-11ea-8b35-f34e6a064a84.png) | `'Yes'\|'No'`
   
3. Tracking for radio buttons, multi-select check box components is implemented in the 22-10203. 

Example of tracking: 

   Description of Form Interaction | Screenshot | dataLayer Event
-- | -- | --
Click to check multi-select checkbox | ![image](https://user-images.githubusercontent.com/48527022/88171019-a3db4c80-cbec-11ea-9b15-826c161b1803.png) | `'event': 'edu-form-change',`<br>`'edu-form-field': <question_text>',`<br>`'edu-form-value': <question_response_label>`<br>`edu-form-action: 'checked'\|'unchecked'\|'clicked'`

4. The  ineligibility alert and the button click of "exit application" are tracked as separate events
5. "Exit Application" clicks are tracked as a primary button according to the design system
   a. Each time the ineligibility alert displays, `'event': 'edu-stem-scholarship-ineligibility-alert'` is pushed along with `true|false` for each criteria met/unmet
   b. Each variable of the `edu-stem-scholarship-ineligibility-alert` event should populate `true` or `false` according to the green checks (`true`) and gray x's (`false`)

   `event` | Description of Interaction | Screenshot
-- | -- | -- 
`'event': 'edu-stem-scholarship-ineligibility-alert',`<br>`'edu-eligibility-criteria-post911-met': true\|false,`<br>`'edu-eligibility-criteria-stem-or-teaching-met': true\|false,`<br>`'edu-eligibility-criteria-used-all-benefits-met': ':true\|false,`<br>`'edu-eligibilty-criteria-months-remaining-for-use':` | Display of the ineligibility alert | ![image](https://user-images.githubusercontent.com/48527022/88921566-c1d42d00-d23c-11ea-9576-057c4c16f992.png)
`'event': 'cta-primary-button-click` | Click on "Exit Application" button | ![image](https://user-images.githubusercontent.com/48527022/88730477-1b850c00-d104-11ea-99d7-57f2d03e8d04.png)

## Supporting Artifacts
1. Feedback from the analytics team that informed these changes: 
   a. https://github.com/department-of-veterans-affairs/va.gov-team/issues/10780#issuecomment-662429290
   b. https://github.com/department-of-veterans-affairs/va.gov-team/issues/10780#issuecomment-665338349

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13764
Branch: bah-11706

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-10 at 12.33.15 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/aa33eb0d-646d-4543-a3be-f96c3488f57e)
##
![Screen Shot 2020-08-10 at 12.33.23 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bc3a95e8-a8c9-4ebc-b525-593a6fd046a5)
##
![Screen Shot 2020-08-10 at 12.37.55 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a568033b-5d46-4f51-848b-697121b8d9ae)
##
![Screen Shot 2020-08-10 at 12.38.01 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/616037af-e6d3-4512-86b6-72bdd0da5b16)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-10 at 1.01.18 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/710a2335-247f-4504-90ab-e2b3766f488a)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-10 at 1.19.39 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4acf8178-e126-4fdd-9e6e-47918b58c559)

**Comment by sonntag-adam** [comment]
In staging. Closing story.
