### ISSUE TITLE
Analytics Reporting Request for Mobile App

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#11704]
# Metrics Reporting Request

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

-  Sophie Myers 

What team/project is this work for?

- VA-mobile-app
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after)?
 
2019

## Analytics to Track Down

- [ ] Metric 1: Track whether users who visit claims pages on VA.gov subsequently visit healthcare-related pages

## Which Product Questions are you trying to answer?
Would users use a mobile app that included both health and claims features or are those totally separate user groups?

## Other Helpful Questions to think through
- Who is your audience?
Internal VA audience
- Why do you need this data?
To help shape our product strategy and determine the types of users to target
- What are you hoping to find?
Either overlap between health and claims users or an obvious distinction
- What is your hypothesis that you're hoping the data will support?
Our hypothesis is that in a given year, there will be users who access both claims and health features
- What area of the VA are you hoping to assess?
Claims and health
- How frequently do you need this data?
As of now, we think this is a one-time request

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @srmyers17 , 

Thank you so much for your request! We'll take a look and get back with you shortly. 

May we know when were you hoping to have this answer by? 

Thanks in advance!

**Comment by srmyers17** [comment]
It isn't urgent but we're hoping to firm up our strategy in the next couple of weeks so it would be great to have some answers by next Friday (8/7), if possible.

**Comment by jonwehausen** [comment]
Okay thank you for this timeline! We'll be sure to have something for you all by then.

**Comment by bmcgrady-ep** [comment]
@srmyers17 - Here is the report from Google Analytics that we have for the latest 90 day period.
[healthcare_claims_segment_data.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5043599/healthcare_claims_segment_data.pdf)

**Comment by bsmartin-ep** [comment]
@srmyers17 -

Here are User numbers for `2019-06-18 `(start of data in BigQuery) - `2020-06-18`:

Segment Overlap|Users who visit _Health Care_ Pages|Users who visit _Claims_ pages
----|----|------
1,171,281|5,479,354      |  4,401,957
