### ISSUE TITLE
Move Cypress docs & update links

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#11702]
## User Story 

As a VFS team, I need to be able to find Cypress documentation, so that I can learn how to use the tool (to comply with platform standards and take advantage of its feature set). 

## Details

The steps below outline final documentation updates that should happen with Cypress docs in order to ensure that the location of the docs makes sense in the greater information architecture of documentation. 

This needs to be done after/in addition to completion of updates to documentation content based on feedback from VAOS (#) and VSA Auth EXP (#11693)

## Definition of Done 
- [x] [Cypress Migration Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/tools/frontend/cypress-migration-guide.md) is a resource about using the platform and therefore should be moved to the `/platform` folder, specifically here is good for now: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering/frontend
- [x] Current crosslinks in `va.gov-team` and in the `veteran-facing-services-tools` repo that link to current/previous location of Migration Guide should be updated 
   - [x] Links on the [writing an end to end test](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test/) page
   - [x] Any other locations that link to the Cypress Migration Guide
- [ ] Current docs and resources that mention Nightwatch should be updated to reflect new policy (use Cypress moving forward as of August 1, 2020). The following are docs I've found that mention Nightwatch based on a quick repo search — please update as appropriate or let me know which ones shouldn't be updated, etc
   - [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/eslint/axe-check-required.md
   - [x] https://github.com/department-of-veterans-affairs/va.gov-team/blob/983d84608cc0ca24350bdf8d9f1282e25a9d3cac/platform/engineering/frontend-testing-guidelines.md
- [x] Cypress Migration Guide should specifically crosslink to [the form tester docs that are in vets-website](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/platform/testing/e2e/cypress/support/form-tester)
- [x] `vets-website` readme should be updated (as noted by Eugene) 

Is there anywhere else we need to update? Anywhere else we should link to the Migration Guide or form tester docs?

**Comment by meganhkelley** [comment]
@pjhill I found a couple QA docs that mention Nightwatch. We are requiring teams to use Cypress moving forward, but are not (in the short term) requiring teams to migrate old tests out of Nightwatch. Do any of these docs need to be updated accordingly? 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/cross-platform-testing-plan.md
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/e2e-testing/README.md
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/technologies.md

Please note that we still need to finalize and move the Cypress docs; I can ping you here when that's completed assuming you want to wait before updating your docs. 

@1Copenut same Q to you — these docs mention Nightwatch, do they need to be updated to reflect our use of Cypress for tests moving forward? Do other things (tests, etc) need to be updated before docs are updated? Or are we not planning to move Nightwatch axe checks to Cypress?

- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/testing/508-automated-testing.md
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md

**Comment by pjhill** [comment]
@meganhkelley -- Agreed, that those documents need to be updated. I was waiting for the official switchover from Nightwatch to Cypress. Additionally, most if not all of the QA documentation could use some rewrites, so I was gathering all of those todos as a backlog of sorts.

I'm psyched about Cypress, and I'm happy to do some documentation reogranizing / rewriting. Please ping me when your Cypress documentation is settled, and I will start tweaking QA documentation to point to that.

**Comment by U-DON** [comment]
@meganhkelley: While I'm editing it, should `frontend-testing-guidelines.md` be moved into the `frontend` folder?

**Comment by U-DON** [comment]
I've left the `axe-check-required.md` doc alone for now. The ESLint rule hasn't been updated to handle Cypress files, and doing so would present some challenges that need to be discussed.

**Comment by meganhkelley** [comment]
@U-DON you mean this one? https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend-testing-guidelines.md

Let's just leave it for now — it's in the right _general area_ (we just don't want to send folks to /teams), and we need to overhaul the IA of this at some point anyway. Moving it will break all existing links to it so let's leave. 

And yes sounds good for `axe-check-required.md`! Trevor and I are meeting on 7/30 to discuss further

**Comment by meganhkelley** [comment]
@pjhill Eugene has been updating docs over the past day or two, you should be good to go on updating your QA docs to reflect the new policy 👍 

Let us know if you have any Qs

**Comment by meganhkelley** [comment]
@1Copenut could you please take a look at the links in my comment above and let me know if (a) you are able to update those docs or if (b) something else that's in our Cypress backlog #12206 needs to happen first?

**Comment by meganhkelley** [comment]
Hi @pjhill (no rush — I know you're just getting back from leave) and @1Copenut could you please take a look at the links in my above comment and let me know if (a) you are able to update those docs or if (b) something else that's in our Cypress backlog #12206 needs to happen first?

**Comment by pjhill** [comment]
@meganhkelley -- I think I have what I need to make the updates to these docs. If I run into any questions then I will use this ticket to pose questions.

**Comment by 1Copenut** [comment]
@meganhkelley I haven't forgotten about this one, just haven't had a moment to sit down and parse it. Will make it a priority item tomorrow or Monday.

**Comment by pjhill** [comment]
So, it's not a straight swap of Nightwatch for Cypress in SauceLabs like I assumed it would be (never assume). I'm trying to go through this page from SauceLabs to figure out how to guide users  -- https://saucelabs.com/blog/test-all-the-things-with-cypress-and-testcafe

**Comment by 1Copenut** [comment]
@meganhkelley I've updated my three documents to point to new Cypress helpers, and noted the Nightwatch automated test suite has been deprecated.

**Comment by pjhill** [comment]
> @meganhkelley I've updated my three documents to point to new Cypress helpers, and noted the Nightwatch automated test suite has been deprecated.

^ Ditto
