### ISSUE TITLE
PACT Tag verification results with branch name

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#11701]
## Issue Description
Add branch info to pact_helper so that the branch is tagged w/ the published results

[Example Search Matrix on heroku broker](https://vagov-pact-broker.herokuapp.com/matrix/provider/VA.gov%20API/consumer/Search)

---
## Tasks
- [x] add git_branch tagging in pact_helper when publishing verification results

## Acceptance Criteria
- [x] Verify that the provider version is tagged with git_branch
---

**Comment by alexpappasoddball** [comment]
@LindseySaari can you confirm or deny this is now working?

**Comment by LindseySaari** [comment]
@alexpappasoddball @f1337 Tagging looks to be working: https://vagov-pact-broker.herokuapp.com/matrix/provider/VA.gov%20API/consumer/Search

**Comment by f1337** [comment]
OK, closing because it's done. Thank you @LindseySaari for confirming!
