### ISSUE TITLE
[Call Centers] Direct Deposit Rollout

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1170]
## User Story
As a call center agent, I need information and training materials on the new direct deposit feature, so I can give users the most accurate guidance when they call in for help. 

## Goal
_Provide call center leadership and agents the necessary material and information on the direct deposit feature and migration so that they are able to provide excellent service for any questions or issues that arise as part of the release._

## Acceptance Criteria
- [x] Create product guide, demo video, FAQs
- [x] Share and have reviewed by NCC leadership
- [x] Schedule direct deposit training

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Work on this issue can be reviewed here: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18824
