### ISSUE TITLE
Cypress rollout metrics gathering

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#11703]
## User Story 

As a VSP team member, I need to know whether VFS teams are adopting Cypress, so that I can understand whether we need to iterate on functional test offerings to best support VFS teams. 

## Details 
We want to document the following metrics throughout our Cypress rollout: 

- Number of total tests in Cypress
- Number of total tests in Nightwatch
- ~Number of unique contributors who have created tests in Cypress~ will not capture bc we would need to build implementation for this and we can get what we need from the above two metrics  

We need to pull these numbers manually AFAIK, so it would be great to do so on the following dates: 
- Week of July 27 (ASAP)
- Week of August 10
- Week of August 24
- Week of September 7
- Week of September 21

**Comment by U-DON** [comment]
## Methodology for tracking metrics
- Cypress tests can have multiple test cases per file (as in the case of form tests), so I'll be providing number of test cases as well as files.
    - Number of test cases are coming from the output at the end of the Cypress tests job in CI.
    - Number of files are pulled from running: `find src -name "*.cypress.spec.js" | wc -l` on `vets-website`.
- Nightwatch tests are counted by file since each file covers one test, so I will only be counting files.
    - Number of files are pulled from running: `find src -name "*.e2e.spec.js" | wc -l` on `vets-website`.

**Comment by U-DON** [comment]
## Week of July 27

### Cypress
38 test cases across 11 files

### Nightwatch
92 tests

**Comment by meganhkelley** [comment]
Thank you @U-DON ! Can you explain what the difference is between test cases and files? Is a "file" a single "product"? 

Also, which of these numbers (Cypress test cases or files) corresponds more closely to the Nightwatch "tests"?

**Comment by U-DON** [comment]
Tests are written in files (as in the folders and files on your file system). A Cypress file can contain multiple tests (test cases). Since Nightwatch files each only represent one test, I think it's more appropriate to compare the number of Cypress test cases to the number of Nightwatch tests.

**Comment by U-DON** [comment]
## Week of August 10

### Cypress
39 test cases across 12 files

### Nightwatch
92 tests

**Comment by meganhkelley** [comment]
@U-DON friendly reminder to grab Cypress/Nightwatch numbers this week when you have a moment. Thanks in advance!

**Comment by U-DON** [comment]
## Week of August 24

### Cypress
62 test cases across 23 files

### Nightwatch
88 tests

**Comment by meganhkelley** [comment]
Compiling these numbers here: https://docs.google.com/spreadsheets/d/16gxaUQdsdVjtxyOp30cTuzpKWuz02xdH6w7lZAg0xz8/edit#gid=0

**Comment by meganhkelley** [comment]
@JoeTice @pjhill I am handing this ticket off to y'all — you can keep it open or close, whatever makes sense to you. We can discuss more when we all meet on 11/17

**Comment by pjhill** [comment]
Closing this ticket because the team is tracking adoption in other similar ways and in other tickets.
