### ISSUE TITLE
STEM: Update GA for the 22-1995

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11700]
## Assumptions
1. This work is completed behind the feature flag #7271.
2. Values in the table in AC 1 separated by `|` indicate 1 of possible values
3. The Yes or No question variables in the table in AC 1 should populate with `Yes` or `No`
4. This replaced the existing google analytics on submit tracking. 
5. If a value listed below already exists, note that it is being updated to adjust the variable taxonomy / convention to be all lowercase separated by '-' consistently across.

## Acceptance Criteria
1. The following data layer variables fire on `edu-1995--submission-successful` or `edu-1995--submission-failed`:

dataLayer Variable | Description of Form Submission Variable | Screenshot | Example Value
-- | -- | -- | --  
`'benefits-used-recently'` | Value for "Which benefit are you currently using or have you used most recently?" | ![image](https://user-images.githubusercontent.com/48527022/88547735-1df44280-cfec-11ea-868f-433534e182f2.png) | `Post-9/11 GI Bill (Chapter 33)`
`'new-service-periods-to-record'` | Value for "Do you have any new periods of service to record since you last applied for education benefits?" | ![image](https://user-images.githubusercontent.com/48527022/88547918-5eec5700-cfec-11ea-8521-95a6cb6cc3b6.png) | `'Yes'` OR `'No'`
`'service-details'` | Array containing the details of service containing each branch name and pair of service start dates, and end dates given | ![image](https://user-images.githubusercontent.com/48527022/88549773-b8558580-cfee-11ea-84e7-e0996fcec7ce.png) | `'service-details': [`<br>`{'service-branch': 'Air Force', 'service-start-date': '02/02/2020', 'service-end-date': '07/03/2020'},`<br>`{'service-branch': 'Navy', 'service-start-date': '05/14/1999', 'service-end-date': '05/14/2001'}]`
`'service-before-1978'` | Value for "Do you have any periods of service that began before 1978? | ![image](https://user-images.githubusercontent.com/48527022/88548015-8511f700-cfec-11ea-87b8-a915139b304f.png) | `'Yes'` OR `'No'`
`'edu-desired-facility-name'` | Value for "Name of school, university, or training facility" | ![image](https://user-images.githubusercontent.com/48527022/88550780-120a7f80-cff0-11ea-9144-72d31b08f10f.png) | `'harvard'`
`'edu-desired-type-of-education'` | Value selected from dropdown for "Type of education or training" | ![image](https://user-images.githubusercontent.com/48527022/88550915-3a927980-cff0-11ea-8579-fbcc11c0022e.png) | `'Correspondence'`
`'edu-desired-facility-state'` | Value selected from dropdown for state | ![image](https://user-images.githubusercontent.com/48527022/88551102-74fc1680-cff0-11ea-879e-251334c4c836.png) | `'Massachusetts'`
`'edu-desired-facility-city'` | Value inputted for desired school city | ![image](https://user-images.githubusercontent.com/48527022/88551193-9230e500-cff0-11ea-8411-2617892992a4.png) | `'Cambridge'`
`'edu-prior-facility-name'` | Value inputted on `/old-school` for "Name of school, university, or training facility" | ![image](https://user-images.githubusercontent.com/48527022/88551297-b4c2fe00-cff0-11ea-87dd-ce5649ef79cb.png) | `'Yale'`
`'edu-prior-facility-state'` | Value selected from dropdown for old school state | ![image](https://user-images.githubusercontent.com/48527022/88551442-de7c2500-cff0-11ea-8755-a16be2e6f5ae.png) | `'Connecticut'` 
`'edu-prior-facility-city'` | Value inputted for old school city | ![image](https://user-images.githubusercontent.com/48527022/88551582-03709800-cff1-11ea-96be-13b31602b381.png) | `'New Haven'`
`'edu-prior-facility-end-date'` | Value inputted for date stopped taking classes | ![image](https://user-images.githubusercontent.com/48527022/88551660-1be0b280-cff1-11ea-9e00-9749c393bb6b.png) | `'04/09/2020'`
`'preferred-contact-method'` | Value for "how would you like to be contacted..." | ![image](https://user-images.githubusercontent.com/48527022/88551790-46327000-cff1-11ea-9be0-a182bf955f86.png) | `'email'`
`'married'` | Value for "Are you currently married" | ![image](https://user-images.githubusercontent.com/48527022/88551878-606c4e00-cff1-11ea-814d-defe90397578.png) | `Yes` OR `No`
`'dependent-children'` | Value for "Do you have children in the following categories...." | ![image](https://user-images.githubusercontent.com/48527022/88551946-7548e180-cff1-11ea-9afb-9b338df51061.png) | `Yes` OR `No`
`'dependent-parent'` | Value for "Do you have a parent who is dependent for financial support?" | ![image](https://user-images.githubusercontent.com/48527022/88552052-9b6e8180-cff1-11ea-86b8-e2ff7980540e.png) | `Yes` OR `No`
`'direct-deposit-method'` | Value for "Benefit payment method" | ![image](https://user-images.githubusercontent.com/48527022/88552155-bf31c780-cff1-11ea-8c37-16d3fa5a33cd.png) | `Unchanged` OR `Updated` OR `Stopped` 
`'direct-deposit-account-type'` | Value for "Checking or Savings" | ![image](https://user-images.githubusercontent.com/48527022/88552480-251e4f00-cff2-11ea-9b1b-4784186ca775.png) | `'Checking'` OR `'Savings'` OR `undefined` <br><br> **Please use undefined if user chose not to update**

2. When a value is not provided by the user, pass in **`undefined`** for the given variable.

## Supporting Artifacts
1. Feedback from the analytics team that informed these changes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10780#issuecomment-664424693

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13642

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-08-04 at 9.17.51 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d8ae6662-ae45-48f7-ac93-b3deb66f99b0)

**Comment by delli-gatti-michael** [comment]
Changes are in Staging. Closing this issue

**Comment by desireeturner** [comment]
Notified the analytics team that this is available for review on Staging: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10780#issuecomment-670651032
