### ISSUE TITLE
STEM: Update SCO email content to reflect the final version received from EDU on 07/24

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11713]
As an Education Team Services member, I need the SCO for the school where the applicant is planning to use the STEM Scholarship emailed so that they can confirm the information necessary to complete the application.

## Assumptions:
1. This work is done behind feature flag #7271.
2. On staging, the email should go to a list of recipients that will be covered in a different story. 
3. Testing of this story is not dependent on test EVSS accounts - preview of content is available locally at http://localhost:3000/rails/mailers/school_certifying_officials_mailer/build?facility_code=11000139 where the facility code value can be replaced with any facility code and preview will render

## Acceptance Criteria
1. The content of the STEM email established in #10790 has been updated to reflect the content included in SA1.

## Supporting Artifacts
1. [STEM-SCOEmail-(CLAP final).docx](https://app.zenhub.com/files/133843125/4c58fbbc-55ca-4d1f-8a40-117b648cdba7/download)

**Comment by zurbergram** [comment]
```
A student enrolled at your school has applied for the Edith Nourse Rogers STEM Scholarship.  They will also receive a copy of this letter. We aren’t able to make a formal determination on this student’s eligibility for the STEM Scholarship until we receive the following information from you.
```
has been changed to
```
      A student enrolled at your school has applied for the Edith Nourse Rogers STEM Scholarship.  The student will also receive a copy of this letter. We can't make a formal determination on the student's eligibility for the STEM Scholarship until we receive the following information from you.
```

**Comment by zurbergram** [comment]
`Name of Student:` has been changed to `Student's name:`

**Comment by zurbergram** [comment]
```
If we don’t receive a response within that time, we won’t be able to process the student’s application for the Rogers STEM Scholarship.
```
has been changed to 
```
Please submit your response to <a href="mailto:STEM.VBABUF@va.gov">STEM.VBABUF@va.gov</a>. If we don't receive a response within that time, we won't be able to process the student's application for the Rogers STEM Scholarship, and we may follow up for the required information.
```

**Comment by zurbergram** [comment]
`Please account for the 14-day time limit when submitting these questions.` has been changed to `Please account for the 14-day time limit when submitting questions.`

**Comment by zurbergram** [comment]
```
      VA Form Number: 10203
      OMB Control Number: 2900-0878
      OMB Expiration Date: 6/30/2023
      Respondent Burden: 15 minutes
      cc: <%= @applicant.email %>
```
has been changed to 
```
      VA Form Number: 10203
      Respondent Burden: 25 minutes
      OMB Control Number: 2900-0878
      OMB Expiration Date: 6/30/2023
      <a href="https://www.va.gov/education/apply-for-education-benefits/application/10203/introduction">Privacy Act Statement (available online)</a>
      cc: <%= @applicant.email %>
```

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4629

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13685

Test by going to http://localhost:3001/education/apply-for-education-benefits/application/10203/introduction#omb-info-container and noticing that page scrolls to OMB section with Privacy Act

**Comment by zurbergram** [comment]
SA Document was changed after PR was created and story moved into validate

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/10250&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
Blocked

**Comment by dneel-bah** [comment]
EDU has agreed to launch with an MVP without pulling entitlement / enrollment data from EVSS.  The re-validation in staging will be handled in #12734 once the test data is available in the staging environment.  Closing this story because it has been validated in the local/dev environment.
