### ISSUE TITLE
Design feedback - Usability Testing Prep Debt Letters MVP

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#11711]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**
- On the Content page (authenticated and unauthenticated) fill the info icon in the info alert black instead of blue 
- On the Content page, the last two headings both read “Frequently Asked Questions about VA Debt” - The second one looks like it should be changed to better describe the content below it (defer to content feedback for further guidance)
- On the debt list page, on the main “View debt details” call to action button, swap out the text character “›” for the right chevron icon in Font Awesome as seen below (recommended for legibility)
![Screen Shot 2020-07-28 at 12.07.49 PM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/b2944828-54dc-46a4-aab3-f870d3189d6b)

**Try:**

- No “try” feedback at this time

**Consider:**
- No "consider" feedback at this time (all consider questions were about debt letters being connected to the debts which we found out is a constraint)

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by rileyorr** [comment]
Hey, @CrystabelReiter! Thank you for the feedback! The proposed changes in the **Do** category have been incorporated into [the prototype](https://preview.uxpin.com/4355a6c97a71ddaf1069ec43e5dfc0ae46b79869#/pages/130133417?mode=i) :)

**Comment by CrystabelReiter** [comment]
Thanks @rileyorr I'll close now :)!
