### ISSUE TITLE
Offboarding of Ben Shyong

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#11724]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Ben Shyong
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   >Ad Hoc, Github user is bshyong
- Please provide any type of access they may have. 
  > ex: SOCKS, Pagerduty, Google analytics, ect.
  
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Or
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jbritt1** [comment]
PagerDuty access not applicable to this user.

**Comment by jbritt1** [comment]
DSVA Slack removal requested: https://dsva.slack.com/archives/C03FECE9K/p1595959309216500

**Comment by jbritt1** [comment]
AWS / SOCKS access revoked.

**Comment by jbritt1** [comment]
All Operations actions have been taken for this user, just waiting for Slack admins to remove from DSVA Slack workspace.

**Comment by jbritt1** [comment]
Removed from DSVA Slack

**Comment by joanneesteban** [comment]
Removed from GA 360. Confirmed did not have a Domo account.

**Comment by jbritt1** [comment]
All line items for this user complete.
