### ISSUE TITLE
Uploads: malformed PDFs return generic server error

### ISSUE THREAD

**Issue by SMLuthi** [department-of-veterans-affairs/va.gov-team#1172]
@markgreenburg commented on [Fri Jun 28 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19102)

## Story
As a veteran, it's frustrating to have my PDF uploads fail for no specific reason. I want to receive a better error message so that I can take action to correct problems in my uploaded doc / pdf.

## Context
'Malformed PDF' errors [Sentry Link](http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/61647/?query=is%3Aunresolved%20malformed) return a `500` to the front end. However, since we know that there's an issue with the PDF itself, we should return a more helpful error message to the front end so that the front end can show more helpful messaging to the veteran.

## AC:
- [ ] Return something more helpful than a `500` to the front end for PDF data errors.

**Comment by camerontesterman** [comment]
Is there any specific endpoint where this is occurring, or does this happen with every PDF upload? Could I get an example endpoint @markgreenburg ?

**Comment by camerontesterman** [comment]
This has been resolved.
