### ISSUE TITLE
STEM: Add SCO test participants to the staging distro

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11723]
As a member of the 22-10203 form development team, I want to ensure that SCO's are receiving emails we're sending upon submission of 22-10203 applications in staging so that we can be confident that it will also work in production. 

## Assumptions
1. SCOs listed in AC 1 will be associated with an institution in the mock data. 
2. The following emails are added as bcc if an email is sent on staging: 
   a. Delli-Gatti_Michael@bah.com
   b. roth_matthew@bah.com
   c. shawkey_daniel@bah.com
   d. sonntag_adam@bah.com

## Acceptance Criteria: 
1. The following SCOs are able to receive the SCO email if the mock institution they are associated with is selected by a 22-10203 applicant on staging: 
   a. david.threatt@umgc.edu 
   b. sfallah@scitech.edu
   c. va@wgu.edu
   d. Additional email addresses expected from EDU 

## Supporting Artifacts

**Comment by dneel-bah** [comment]
This story is OBE and now covered by #12734
