### ISSUE TITLE
Create upload validator for encrypted PDFs

### ISSUE THREAD

**Issue by SMLuthi** [department-of-veterans-affairs/va.gov-team#1173]
@kreek commented on [Tue Nov 13 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15113)

**User Story**: As a developer I want to block users from uploading encrypted PDF files as the `EVSS::DocumentsService` can't process them.

---

@YanaRoy commented on [Wed Aug 21 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15113#issuecomment-523563950)

Research required for viable solution.

**Comment by camerontesterman** [comment]
This has been merged and resolved.
