### ISSUE TITLE
CT-Search: Update VET TEC program length tags to match the new style

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11730]
As a team member supporting the Comparison Tool, I want the look and feel of tags on the institution "cards" to be consistent in order to increase intuitiveness and ease of use by individuals searching for and viewing institutions. 

## Assumptions
1. This work should be behind a feature flag: #11344

## Acceptance Criteria
1. The program length label on the institution "cards" on the VET TEC search results page have been updated to reflect the style defined in SA1. 
2. The following colors are utilized for the tags:
   a. Text: 323A45
   b. Background: FFFFFF

## Supporting Artifacts
1. [Prototype](https://bahdigital.invisionapp.com/share/QNIAEHO8BH2#/screens/296045002)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13704

**Comment by sonntag-adam** [comment]
Tags are blocking housing, moving back to in progress for fix happening between 482 - 640 px

![Screen Shot 2020-08-11 at 3.00.21 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b9d89a89-6d4f-4ddc-96de-c34b6ab78055)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-12 at 9.14.32 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e2ffa8c1-3373-4980-9d3a-aa9a8b14c54f)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/11013&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by ksantiagomorgan6** [comment]
ADDITIONAL PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13849

**Comment by delli-gatti-michael** [comment]
No more overlap with "Housing"

![Screen Shot 2020-08-14 at 2.47.43 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/628ae86a-53f6-4db7-be9b-f1bb48c62b04)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah The latest is now live on Staging

**Comment by amyknox** [comment]
The vertical spacing between housing & the length label on my iphone looks larger than What Ricky's showing in his screenshot.  

![image](https://user-images.githubusercontent.com/41081945/90289824-b1ca6900-de4a-11ea-98ad-830d2bfe1937.png)

**Comment by amyknox** [comment]
On desktop, the top of the label used to align with the bottom of the housing line (Image 1) but now, on staging, it's placed lower than that (image 2).

Image 1
![image](https://user-images.githubusercontent.com/41081945/90290320-a88dcc00-de4b-11ea-9be7-693473854a51.png)

Image 2
![image](https://user-images.githubusercontent.com/41081945/90290440-e1c63c00-de4b-11ea-96f1-95a1c8e1dae0.png)

**Comment by JenLJ** [comment]
@delli-gatti-michael @sonntag-adam @ksantiagomorgan6 UX has taken a look and this checks out!

**Comment by sonntag-adam** [comment]
Closing story.
