### ISSUE TITLE
Deprecate @babel/polyfill in favor of core-js and regenerator-runtime.

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#11743]
[@babel/polyfill has been deprecated as of 7.4.0](https://babeljs.io/docs/en/usage#polyfill).

Polyfills should be covered by directly importing core-js/stable (v3) and regenerator-runtime/runtime.

> 🚨 As of Babel 7.4.0, this package has been deprecated in favor of directly including core-js/stable (to polyfill ECMAScript features) and regenerator-runtime/runtime (needed to use transpiled generator functions):

[ECMAScript features we get from core-js/stable v3](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#stable-ecmascript-features)

[Web standards included from core-js/stable v3](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#web-standards)

Notable additions:
- `URL`, giving us a standard way to handle URLs, removing the need for the `append-query` dependency
- `URLSearchParams`, so we can remove `url-search-params` and `url-search-params-polyfill` (recently added because the former was deprecated)
- `forEach` on DOM collections

**Comment by timwright12** [comment]
@meganhkelley I can probably take a run at this one if we're looking for something for me to work on. Let me know!

**Comment by Clark-W-Griswold** [comment]
Chris update:
Working on manually testing IE 11 with babel upgrade. 
Investigating missing polyfill relating to [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17305)
