### ISSUE TITLE
[Bug] Letters errors related to malformed or empty address data

### ISSUE THREAD

**Issue by SMLuthi** [department-of-veterans-affairs/va.gov-team#1175]
@hinzed1127 commented on [Thu Jun 20 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19017)

[Sentry Link](http://sentry.vetsgov-internal/vets-gov/website-production/issues/64761/?query=is%3Aunresolved%20lastSeen%3A-30d%20timesSeen%3A%3E%3D100%20source%3Aletters%20event.timestamp%3A%3E2019-05-17T00%3A00%3A00)

Throwing `422`s when we fetch the letters list. This could be related to an empty address, some other validation issue, or something else

---

@markgreenburg commented on [Wed Jun 26 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19017#issuecomment-505946142)

@SMLuthi to check if we can get more details on cases where vets-api throws a 422.

---

@SMLuthi commented on [Wed Aug 21 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19017#issuecomment-523578119)

This is currently blocked by EVSS Sustainment. They are scheduling an implementation to allow for a transaction id in the request header so that we can sync our calls and hopefully debug the calls that are currently raising errors.

**Comment by luke-gcio** [comment]
Looks like the transaction ID fix came through on the EVSS side and now we have to determine if we are still getting errors (and hopefully be able to actually associate them with a user).

**Comment by luke-gcio** [comment]
Overall to see if we can pull error rates for chapter 33 errors (with the LTS system which is through EVSS).

**Comment by SMLuthi** [comment]
The EVSS Sustainment team has been notified with a sample set of transaction ids from transactions that have encountered this issue in production. They are now working to expose the issue that the veterans are running into. As of right now, they are still in the process of crawling through their logging at their end... Apparently, this is a significantly difficult task regardless of having obtained those unique identifiers.

**Comment by SMLuthi** [comment]
Update:

After investigating with the EVSS Sustainment team the conclusion is that the veterans who are encountering this issue are lacking the address line 1 field in the CORP database. EVSS validates the existence of the address since it has to be filled in for any of the letters that can be requested by the veteran.

I investigated further by asking the VA Profile team whether their profile information syncs up with CORP. This seems to be the case (as long as the veteran already has an entry in the CORP database... VA Profile cannot create this entry for them but they can update the information). This lead to further investigation since we currently are already, supposedly, gating on whether the veteran has an address set in their profile and if they dont we ask them to update that information before they can continue.

It turns out, though, that our gating isnt working correctly. We tested the letters service by signing in with a veteran who did not have a mailing address set. When we went to request the letters the application would make a call to the `get_letters` endpoint but then stall out and not display anything. Whether this is the primary reason we are seeing these errors in production remains to be seen but as a next step this issue needs to be fixed. @ndsprinkle and @Mottie have already been informed about this issue and, I believe, are creating ticket(s) to reflect this work.

Once this has been resolved we will need to revisit this and verify that the fix has corrected the error rates we are seeing or restart the investigation and attempt to find the culprit.

**Comment by AZSchneider** [comment]
I'm excited to see if the gating change improves the error rates. Thanks for digging in to this @SMLuthi !

**Comment by SMLuthi** [comment]
Ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/6543 has been created to attempt to address this problem. We will close this ticket and mark the discovery work completed. Once this issue has been corrected and, for some reason, it has _not_ curtailed the errors we are seeing we will need to revisit this.
