### ISSUE TITLE
Zenhub template for research activities

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1176]
As a UX designer, I want a research activities zenhub template so that I don't have to recreate the same ticket every time.

**Comment by smoonpeyes** [comment]
Templates have been created:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/1176-discovery-epic-template/.github/ISSUE_TEMPLATE/discovery-research-epic.md

https://github.com/department-of-veterans-affairs/va.gov-team/blob/1176-discovery-epic-template/.github/ISSUE_TEMPLATE/research-epic.md
