### ISSUE TITLE
GIDS: Combine P911Tf & P911Yr files	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11766]
As a member of the Education Services team, I want to streamline the process for updating GIDS so that the likelihood of user errors due to manual data manipulation is decreased. 

## Assumptions
1. N/A

## Acceptance Criteria
1. The P911Tf and P911Yr files have been combined to match file format of SA1. 
   a. The "number of trainees" column in the P911Tf file maps to "Distinct count of Tuition and Fees". 
   b. The "tuition and fees cost" column in the P911Tf file maps to "Tuition and Fee Total Amount". 
   c. The "number of trainees" column in the P911Yr file maps to "Distinct count of Yellow Ribbon".
   d. The "total cost" column in the P911Yr file maps to "Yellow Ribbon Total Amount".
2. New combined file:
    a. can be uploaded to GIDS
    b. can be exported from GIDS
3. New file is utilized in version generation and populates attributes in institution.
4. The P911Tf and P911Yr files:
    a. are no longer used in version generation.
    b. are not available to be uploaded.
    c. are not available to be exported.
5. The latest uploads doesn't include the P911Tf and P911Yr files and instead includes the new file. 
## Supporting Artifacts
1. Consolidate sample file: [P911Tf_Yr_FY19_new.xlsx](https://app.zenhub.com/files/133843125/348dfb04-1700-4038-912e-df3e62ea7214/download)

**Comment by dmccurdybah** [comment]
[https://app.zenhub.com/files/133843125/c272e35a-0c83-4152-9b30-b87f5c38f0e6/download](https://app.zenhub.com/files/133843125/c272e35a-0c83-4152-9b30-b87f5c38f0e6/download)[https://app.zenhub.com/files/133843125/0d603940-22d7-4227-9377-695ba72909a4/download](https://app.zenhub.com/files/133843125/0d603940-22d7-4227-9377-695ba72909a4/download)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/699
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/700
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/701

**Comment by dmccurdybah** [comment]
This is 3 PRs because of the way we're required to break this up, but the final PR branch `post911-csv-cleanup` is the one that should be tested.

PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/699
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/700
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/701

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-08-13 at 8.40.43 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c3a428c1-b5c3-492c-b856-e4797469147d)

**Comment by sonntag-adam** [comment]
In staging. Closing story.
