### ISSUE TITLE
IA Feedback - Usability Prep - Debt Letters

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#11762]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This issue describes IA feedback

**MUST**
- Update breadcrumbs as below - discussed these changes with Peggy and are aligned, they may not match H1s exactly but help the flow of the breadcrumb: <br>
Static page :   Home > Manage your VA debt <br>  
Tool-Debt list:    Home > Manage your VA debt > Current debt  <br>
Tool-Debt detail:   Home > Manage your VA debt > Current debt > Details <br>
Tool-Download letters:    Home > Manage your VA debt > Current debt > Download debt letters 

**SHOULD**
- none at this time

**CONSIDER**
-  Getting at where users will look for tools that are not part of benefit hubs/directly related to specific benefits is a challenge. 
 One thought, is to start a user on an authenticated home page, so that it includes additional potential areas that a user may look - namely "My VA" and "Profile".  This is not necessarily a natural start, but may provide more insight into how/where users associate this tool - particularly if they think it would be more associated with elements available in a logged in experience.  Very open to thoughts on this, or open to trying this as an experiment to open conversation.  

## Definition of Done
- [x] Feedback is reviewed and acknowledged by team 
- [x] Decisions and question responses documented in issue
- [x] Issue is closed by VFS team once complete

**Comment by rileyorr** [comment]
Thank you for the feedback, @mnorthuis! I've updated the breadcrumbs in our prototype. 

> One thought, is to start a user on an authenticated home page, so that it includes additional potential areas that a user may look - namely "My VA" and "Profile".

I think this is a great idea! I know that we can recruit participants through Perigean for UAT, but I'm unsure if there's any constraints for tasking users to sign in to VA.gov during usability testing. I posted a question about this in Slack, so hopefully I'll have some more info soon!

**Comment by mnorthuis** [comment]
I am also unsure of that, given it can require PII...the other option is to use a mocked up page in your prototype, but also don't want to interject a bunch more work for you at this point in the process.

**Comment by rileyorr** [comment]
Good morning! I reached out to the Authenticated Experience team and they told me that they've had folks sign in during sessions and it should be fine for our study since passwords are hidden. I'm going to update our research plan and conversation guide to reflect that we'll ask participants to sign in if they're comfortable doing so :)

**Comment by rileyorr** [comment]
Good morning @mnorthuis! I wanted to follow up in case you had any other questions. Otherwise, are we good to close this ticket?

**Comment by mnorthuis** [comment]
Good to close as long as you have what you need.  Thanks!
