### ISSUE TITLE
Update language in our 2 maintenance modals for upcoming maintenance from VAMF - Scheduled 8/3

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11767]
**For modal that shows 1hr before maintenance takes place:**
_VA Online Scheduling will be down for maintenance on August 3rd between 9:00 p.m. EST and 10:00 p.m. EST. If you need to verify an appointment during this time, please call your local VA medical center. You can find contact information using the [Facility Locator](https://www.va.gov/find-locations/) online tool._ 

![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/4d6bf0dc-ebcd-47bf-8004-5d014a892007)

**For modal that shows during maintenance period:**
_**VA online scheduling is down for maintenance**
We're making some updates to this tool on August 3rd between 9:00 p.m. EST and 10:00 p.m. EST. We're sorry it's not working for you now. If you need to verify an appointment during this time, please call your local VA medical center. You can find contact information using the [Facility Locator](https://www.va.gov/find-locations/) online tool._ 

![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/8e7062bd-698d-4aa1-85da-5044850293ca)

## Acceptance Criteria:
- [ ] update copy for two modals
- [ ] hook up FE to BE pagerduty service
- [ ] release this by Monday, Aug 3rd prior the maintenance occurring

**Comment by lenaecb** [comment]
@peggygannon - We just found out that there were will be maintenance on the VAMF BE services Mon Aug 3rd at 9pm EST.

We need to prep some language to use in our standard modals. I have providing some content suggestions based on the dates/times we know from the VAMF team, but I'd like your final review/input.

**Comment by peggygannon** [comment]
@lenaecb Here are my content recommendations for these messages:

Advance message for Modal
**VA online scheduling will be unavailable soon**
We’re doing work on the VA appointments tool on August 3, 2020, between 9:00 p.m. and 10:00 p.m. ET. If you need to request or confirm an appointment during this time, please call your local VA medical center. Use the [VA facility locator] to find contact information for your medical center 

During downtime window

**The VA appointments tool is down for maintenance**
We’re making updates to the tool on August 3, 2020, between 9:00 p.m. and 10:00 p.m. ET. We're sorry it's not working right now. If you need to request or confirm an appointment during this time, please call your local VA medical center. Use the [VA facility locator] to find contact information for your medical center.

**Comment by lenaecb** [comment]
@peggygannon - Can we alter the first alert header from "VA online scheduling will be unavailable soon" to "VA online scheduling will be down for maintenance" or something similar?

The way the header reads right now, it some what implies the tool is going away.

**Comment by peggygannon** [comment]
@lenaecb Yes, good point! thank you for that feedback  So the modal message would be: 

**VA online scheduling will be down for maintenance**
We’re doing work on the VA appointments tool on August 3, 2020, between 9:00 p.m. and 10:00 p.m. ET. If you need to request or confirm an appointment during this time, please call your local VA medical center. Use the [VA facility locator] to find contact information for your medical center
