### ISSUE TITLE
Redirect Request: Vanity URL for Home Loans Ad Campaign

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#11775]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
This URL is being requested by VBA stakeholders for the purposes of an ad campaign that is launching on 7/29/2020.  The URL must not be placed in the XML sitemap and should be noindex.

### Requestor team info
Public Websites/IA

### Implementation date
7/29/2020

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X ] Other - Please indicate timing : **Needs to launch 7/29/2020**

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
http://va.gov/homeloans | https://www.va.gov/housing-assistance/home-loans/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by kelsonic** [comment]
PR is merged + deployed to prod! Thanks @ncksllvn for grabbing this! 🎉  Ready for validation + closing

**Comment by MickinSahni** [comment]
Validated!
