### ISSUE TITLE
[Development] BDD: Install Flipper UI Around BDD Capability

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#11778]
## Issue Description
In order to roll out BDD soon, we will need to make sure that we can control the flipper.  Also, as part of discussions with stakeholders, they let us know that the option to go to eBenefits should still exist until eBenefits is off.  I am not sure what the best way to implement this and perhaps it needs a discussion but it sounds like currently we have:

1. Ineligible to file BDD
2. File BDD on eBenefits (for production)

It looks like we are being asked to:

1. Ineligible to file BDD
2. File BDD on VA.gov (for production behind flipper)
2a. File for BDD on eBenefits (still have a note saying you could do it on eBenefits).

The truth is - this is not a demand from the stakeholders so if the above does not make sense in regards to design and best practices for other apps, let's not do it.

## Acceptance Criteria
- [ ] Flipper is there.
- [ ] We consider whether we need to also remind them it's _possible_ to do this on eBenefits.
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
Created a devops PR: https://github.com/department-of-veterans-affairs/devops/pull/7359
Created a vets-api PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4646

These are for access to controlling the flipper in production (devops) and for adding the actual feature flipper (vets-api).
