### ISSUE TITLE
Confirm PPMS update

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11776]
## Description
PPMS will be updating the systems on Friday, July 31. No impact is expected on the data but we need to confirm. 

## Task
Take snapshots of providers across specialties and geography from Staging in advance of upgrade to use in validation on Monday

**Comment by mpelzsherman** [comment]
![Find_VA_Locations___Veterans_Affairs](https://user-images.githubusercontent.com/80267/88825889-1a042400-d196-11ea-8e8f-2eacc655182a.png)

**Comment by mmiddaugh** [comment]
<details>

 <staging> Screenshots </staging>

![abq mental health ppms](https://user-images.githubusercontent.com/55411834/88851504-14b0d480-d1aa-11ea-829e-11ec67ccdb6e.png)

---

![urgent care PPMS Boise](https://user-images.githubusercontent.com/55411834/88851574-298d6800-d1aa-11ea-82bb-2d431254d2a6.png)

---


![urgent care PPMS Nashvillepng](https://user-images.githubusercontent.com/55411834/88851588-2db98580-d1aa-11ea-8af8-241954ccbbbf.png)

---

![urgent care PPMS Denver](https://user-images.githubusercontent.com/55411834/88851525-1c707900-d1aa-11ea-93dc-e7fe92bf992f.png)

---

![indianapolis oncology ppms](https://user-images.githubusercontent.com/55411834/88851532-1ed2d300-d1aa-11ea-9a47-3e92ebde86bc.png)

---

![cody wy optometrist ppms](https://user-images.githubusercontent.com/55411834/88851534-20040000-d1aa-11ea-8f33-f20c78fd58b2.png)

---

![obgyn nashville ppms](https://user-images.githubusercontent.com/55411834/88851546-21cdc380-d1aa-11ea-873b-4a79b48e53bd.png)

---

![urgent care PPMS Portland](https://user-images.githubusercontent.com/55411834/88851553-24301d80-d1aa-11ea-82f0-6b1ad1999d29.png)

---

![tampa gi ppms](https://user-images.githubusercontent.com/55411834/88853182-90138580-d1ac-11ea-8e46-417bec4b56ac.png)


</details>

**Comment by mpelzsherman** [comment]
I did a quick check in prod, and the PPMS searches seem to be working the same as before AFAICT - with the usual slowness and pagination issues.

**Comment by mmiddaugh** [comment]
@mpelzsherman Snapshots were taken from staging for baseline so this needs to be validated in that environment. I've confirmed all of the scenarios except Indianapolis + oncology since that one repeatedly timed out for me. 

## Validated

<details>

 <summary> Psychologist - Rehab in Raleigh, N.C. search </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bb6561dd-589a-425e-823d-2b453c1d956c)

</details>

---

<details>

 <summary> Counselor: Mental Health in ABQ search </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/e02280b6-4bfd-47eb-bbce-043a08865acd)!

</details>

---

<details>

 <summary> Urgent care in Boise search </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bc9b8681-3d61-48fb-afbe-4d93945639da)!

</details>

---

<details>

 <summary> Urgent care in Nashville search </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/c0af3adb-2ce3-44dd-bffc-8def3cc5cd0d)

</details>

---

<details>

 <summary> Urgent care in Denver search </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/9ab685b4-7e02-4961-9630-27d50057be73)

</details>

---

<details>

 <summary> Optometry in Cody, WY search </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b7ce3296-302d-46c9-a091-f79fcbbecb51)

</details>

---

<details>

 <summary> OB/GYN in Nashville, TN search </summary>


![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/844f839b-ed18-4f18-9cd4-707d535b0824)

</details>

---

<details>

 <summary> Urgent care in Portland, Oregon search </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/4817de2f-faae-4807-897a-431e20dbe99b)

</details>
---

<details>

 <summary> Gastroenterology in Tampa, FL search </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/17a6ef9a-9bfc-4c4c-94a1-790f854e1c84)

</details>

## Not Validated

I was unable to validate Oncology in Indianapolis as the search repeatedly timed out. 

## Other observations

I have concerns about the duplication observed in a few locations but the results are consistent before/after the update so I will record them elsewhere.

**Comment by mmiddaugh** [comment]
Duplication is occurring in Swagger as well. Sent observations to OCC.
