### ISSUE TITLE
[Development] 526: Redacted form526 banking data

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#11773]
it it looks like if we prefill a person's banking information in form 526 and then submit the form we're actually submitting redacted account numbers like '*****1234' rather than '123451234'.

 [translate_banking_info](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L93) should get banking data from PPIU if the submitted banking info has stars in it.

Edit: I verified that this is happening.  We see this response from EVSS `"key"=>"form526.directDeposit.routingNumber.Pattern", "severity"=>"ERROR", "text"=>"must match \"\\d{9}\""`

**Comment by luke-gcio** [comment]
Very low hanging fruit and good to get Lihan's feet wet.

**Comment by annaswims** [comment]
You can run the rake task `rake form526:errors` to find instances of this error. `form526.directDeposit.routingNumber.Pattern: must match...`

Once you have the submission_id from that list you can run `rake form526:submission[383534]` to see form submission data, though in this case we need the redacted veteran data that we could get from the console (`Form526Submission.find(383534).form.dig("form526","form526","directDeposit")`).
