### ISSUE TITLE
Add `python3` to ALL Jumpboxes

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#11783]
I use a tool to connect to instances called `sshuttle` and it recently broke because it only supports Python 3 now and the DEV Jumpbox doesn't have Python 3. I can specify the remote interpreter like `sshuttle --python=/usr/local/bin/python3` and want to see if we can install Python 3 side by side with the binary name of `python3` (so it shouldn't break anything) on the DEV Jumpbox. Thoughts?
`sshuttle` is useful because it routes entire system CIDR blocks to the proxy/jumpbox. Which means I can use a browser (not switchyomega) with local /etc/hosts entries and have it run through the jumpbox.
See https://github.com/sshuttle/sshuttle/issues/481#issuecomment-662228546 for context. 

Previous discussion with @dginther about adding this (internal) https://dsva.slack.com/archives/CBU0KDSB1/p1596035062255100.

**Comment by ElijahLynn** [comment]
Hi there, wondering if I can maybe just get a little guidance and take this on. A quick pointer on what files to look at would be good enough for me to make a PR. cc @jbritt1

**Comment by ElijahLynn** [comment]
Maybe this would actually just go in the base AMI for all apps? I also want to add boto3 to our app so we can use the https://docs.ansible.com/ansible/latest/modules/aws_s3_module.html module (must be on the target to use), which we add with pip install in our current images, so wondering if that should all be in the base image so other Ansible engineers/apps can use that module too.

**Comment by jbritt1** [comment]
Hey @ElijahLynn, I personally would not see anything wrong with installing it in the build for common AMIs. I would just ask that it be alias'd called in such a way that does not disrupt current automation / configurations. For example, python 3 being called with python3 (which I think is the default upon installation anyway) vs python -> python3.

**Comment by ElijahLynn** [comment]
Agreed, name should be `python3`.
