### ISSUE TITLE
Conduct Content Review with Peggy (Dependency Claims)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11795]
## Goal
We want to ensure that every piece of content we put in front of a Veteran is at the highest standard, so we need to get Peggy to take a look and verify what we have in place or provide suggestions.

## Tasks
- [x] Provide Peggy with a link to the latest staging, prototype or mockup

## Acceptance Criteria
- [x] Feedback has been requested

### Next steps
- Implement changes before or after launch as needed.

**Comment by sporeboy** [comment]
Will meet with Peggy today (7/31).

**Comment by sporeboy** [comment]
Met with Peggy regarding 686 changes. Mandatory stuff before launch includes: 

- Updating the H1 and style tweak
- Capping V in Veteran
- Removing "Note" from the beginning of sentence on the Add Student screen

She will organize the other feedback for a post-launch content update, but I have her initial revisions in the XD screens.
