### ISSUE TITLE
Turn off Direct Deposit on eBenefits with an update banner message with new location/instructions

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1179]
On a specified, agreed upon, date, the eBenefits Sustainment Team should turn off access to Direct Deposit on eBenefits and update a banner/msg.
- Should the banner start earlier and indicate this _will_ be happening?
- Who is the best person to approach on the sustainment team?

### Definition of Done
~~- [ ] Get confirmation that this will be satisfactorily completed from the sustainment team.~~
~~- [ ] Communicate those details to Auth-Exp.~~
- [ ] Lisa will move and resolve this issue

**Comment by lkoenigsberg** [comment]
See [screenshot examples](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17099) that help identify the places we'll need to update/edit on eBenefits.

(1) Dashboard, popular items
(2) Manage top nav menu
(3) Personal Information & update information page(s)
(4) Maybe more...

**Comment by lkoenigsberg** [comment]
Created https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19546 to replace this.  Closing.
