### ISSUE TITLE
Track school name searched in GI Bill Comparison Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#118]
@nedierecel commented on [Thu Apr 25 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18200)

As an analytics user, I want to track the schools searched on the GI Bill Comparison Tool, categories within the Institution details that have been used, and percentage of sessions where search has been utilized. This data is not currently tracked within the Education Modernized View.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/aeb42761-0236-42bf-8416-ef835222159d)

Interactions with "Your Eligibility" are tracked as Event Actions.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/16e700bf-3f29-4cb0-bc63-82b5341fba66)

Link here: https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184334251/explorer-table.plotKeys=%5B%5D&explorer-table.filter=GIBCT%20form%20change&_r.drilldown=analytics.eventCategory:Interactions

Acceptance criteria:
- [ ] Apply to non-production property
- [ ] Validate that no PII appears and that values are populating

---

@nedierecel commented on [Thu May 23 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18200#issuecomment-495238779)

Within the Google Analytics Non-Production Property (`UA-50123418-17
`), Google Analytics was updated to capture school name and Institution Filters, including: 
- category (e.g. school or employer)
- country
- state
- Program Filters (studentVeteranGroup, yellowRibbonScholarship, principlesOfExcellence, eightKeysToVeteranSuccess, stemOffered, priorityEnrollment, independentStudy, onlineOnly, distanceLearning)

@joanneesteban @tonyadhoc - For your visibility, I've enabled search reports to capture data on the institutions searched within the GI Bill Comparison tool. This is only on the dev/staging property within the "Education Modernized View" for now. 

We should consider if we want to enable this same data in the "All" and "WBC Views", which already include search results on https://www.va.gov/search/ and within the Facility Locator. 

---

@nedierecel commented on [Tue May 28 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18200#issuecomment-496586442)

Adding a setting to lowercase the search terms and validating to see why search categories are not appearing

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/39ec40a9-bb97-499b-9608-b30ec57c6f52)

**Comment by nedierecel** [comment]
@joanneesteban For visibility, I had to make a few changes in staging:

1. Lowercasing all of the search category values
2. I removed tracking of the "Programs" filters. Unfortunately, in GA the values that are captured only list `true` but don't associate what values are used; I removed this from search tracking.

I should be able to close this on Monday after I validate more of the test data.

**Comment by joanneesteban** [comment]
@mattpointzxer0 Hi Matt, pulling you in on this - would it make sense to pull all the data (above) into the WBC view? It will exist in the education view regardless.

**Comment by nedierecel** [comment]
@joanneesteban - Edit to my above comment, as I ran into an issue where my test searches this week aren't appearing in the Staging property. I am working on a new solution and will close when I see my latest tests. Thanks!

**Comment by nedierecel** [comment]
@joanneesteban From our standup, I am going to spin off the category tracking as a separate task.

@mattpointzxer0 - We will be tracking the name of school, city, or employer as search results within the education view. This *can* also be added to the WBC and "All Production" Views.

The WBC and "All Production" views also include search results from search.gov and Facility Locator, so Google Analytics users would see all results from various VA.gov search results in one view.

**Comment by nedierecel** [comment]
@joanneesteban I added the `name` parameter to track the values of searches on the school/city/employer field in the GI Bill Comparison tool in the Education Modernized View. If we choose to track these values in another view (e.g. Modernized or All Production), I can open a new issue.
