### ISSUE TITLE
STEM: Send confirmation email to applicant

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11809]
## Assumptions
1. This work is done behind feature flag #7271.
2. When testing this on staging, the tester will need to add their email to the "email address" field on chapter 5 - personal information so that the email is sent to them upon submission. 

## Acceptance Criteria
1. Upon submission of a STEM Scholarship Application on VA.gov, the confirmation email included in SA1 is sent to the email associated with the applicant. 
2. The email subject is VA Rogers STEM Scholarship, Application Confirmation
2. The following lines of the email are pre-populated:
   a. Name of Student: [First Name Last Name]
   b. Date of email, format: Mon. DD, YYYY (Nov. 14, 2019)
   c. Confirmation number (number provided after submission on the confirmation page; format V-ABC-1234)

## Supporting Artifacts
1. [STEM-ApplicationConfirmationEmail-20200727.docx](https://app.zenhub.com/files/133843125/c7248ded-e017-44c0-8de5-072ec2e66442/download)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4641

**Comment by dmccurdybah** [comment]
Email can be previewed locally by hitting this url:

`http://localhost:3000/rails/mailers/stem_applicant_confirmation_mailer/build?claim_id=1`

The `claim_id` is the confirmation number without the leading `V-EBC-`

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-08-06 at 10.54.50 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a7c5293e-56f7-46a7-8edb-781763a2f826)

**Comment by delli-gatti-michael** [comment]
Letter generated locally with language updates from #11876

![Screen Shot 2020-08-06 at 12.12.59 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ab5a79ee-d0c9-4ef3-bf35-3e3351715aeb)

**Comment by delli-gatti-michael** [comment]
Some of the content in SA1 is being overwritten by #11876

**Comment by delli-gatti-michael** [comment]
Changes are live on staging. Closing this issue

**Comment by delli-gatti-michael** [comment]
Tested by TestRail test Case:
https://dsvavsp.testrail.io/index.php?/tests/view/10240&group_by=cases:section_id&group_order=asc&group_id=51
