### ISSUE TITLE
[Design/Tech] Claims Status: Work With Engineering Team to Begin Creating Tech Discovery Activities

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#11803]
## Issue Description
As part of our work to move CST forward, we need to understand what are the highest priority technical discovery activities.  We also need to at least find a few initial POCs to start these conversations with. We have Fred and Paul as the first level stakeholders but will want to ask them for both business and tech stakeholders.  

## Acceptance Criteria
- [x] Determine prioritized list of technical debt activities (likely hold a meeting)

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
We have begun some technical discovery around the CST. We have a ticket to see claim types/average number of claims per user within the tool that was assigned to the BE developers.

**Comment by luke-gcio** [comment]
There have been some adjustments to the priorities.  This ticket will move forward to sprint 28 as we continue to evolve CST initial work.

**Comment by luke-gcio** [comment]
This is practically OBE given all of the priorities we are getting to make updates to the current tool.  Moving out of the next few sprints worth of work so we can focus on the existing tool fixes.

**Comment by chrvalla** [comment]
This is being pushed due to focus on BDD UAT testing and BDD launch.

**Comment by kevinstachura** [comment]
The claims data comes from EVSS and the appeals data comes from Caseflow (however it's glacially slow). We have data from REDIS(sp?) and that will give us an indicator of what comes back. Mobile app team might have some insights as to what data comes in.

**Comment by kevinstachura** [comment]
I've uploaded a product discover outline file in GitHub for this ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/product-discovery-outline.md

Once I have a better understanding of how to approach doc sharing on Sharepoint, I will just upload the Word doc there. We can build upon this document and further hone in on tech discovery activities as well as prioritizing 'smaller wins' in such a large product undertaking (while planning the larger, more time-intensive activities).

**Comment by kevinstachura** [comment]
Also worth mentioning that we discussed some of this on Friday's quarterly planning meeting and planned on looking into a few areas where we could make short term changes. These included:

- Reassessing timelines in the CST and updating accordingly (and determining stakeholders)
- Chatting with the mobile app team to understand the gaps they encountered
- Small content areas of change, including error messages and expectations of when items would actually end up in the CST
