### ISSUE TITLE
[Launch] Original Claims: Review Metrics After Differentiation Between OG Claims and All Claims

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#11814]
## Issue Description
Make sure OG Claims works.

## Acceptance Criteria
- [x] Create additional failure logging for MVI add person
- [ ] Review logging between OG Claims and All Claims
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
In the last 14 days:

Total requests to v0/mvi_users # submit

 | Status | Count | text |
 ---------|-------|----|
 | 200 |  86 | Success! |
 |  502 | 53 | Error |
 | 422 | 49 |   Scenario indicates serious problems with user data - user.birls_id.nil? && user.participant_id.present?|

Add person to MVI calls:
* Total Requests  284
* Failures  56

The MVI failures are logged in setry here:
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/39378/events/?query=url%3A%22https%3A%2F%2Fapi.va.gov%2Fv0%2Fmvi_users%2F21-0966%22

Something doesn't add up in the MVI failures though.  Everyone who makes it far enough to call v0/mvi_users # submit so I'm not sure why the calls to find_profile in MVI are failing. So, I made a pr to log additional info https://github.com/department-of-veterans-affairs/vets-api/pull/4628

**Comment by luke-gcio** [comment]
We are no longer going to spend time differentiating between All and Original Claims.
