### ISSUE TITLE
File for increased disability compensation page does not seem to exist

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#11813]
## What happened?
_When searching for VA form "21-526ez" the results show a "File for increased disability compensation" page, which results in a "Sorry -we  can't find that page."_
<img width="1089" alt="Screen Shot 2020-07-29 at 1 15 52 PM" src="https://user-images.githubusercontent.com/42546515/88831688-b1b94080-d19d-11ea-8893-043bdcae2b07.png">

## Specs:
- Device: Macbook Pro
- Browser: Firefox

## Steps to Reproduce
- Type "21-526ez" in Search field
- Click on the "File for increased disability compensation" search results

## Desired behavior
_I imagine the link should take the user to a "File for increased disability compensation" page. But, based upon additional findings, I'm not sure this page should even exist. In viewing the ["When to file"](https://www.va.gov/disability/how-to-file-claim/when-to-file/) in the disability hub, there's an accordion discussing increased claims (screenshot below). The link at the bottom of the accordion takes the user to the ["How to file a disability claim"](https://www.va.gov/disability/how-to-file-claim/) page. _
<img width="1094" alt="Screen Shot 2020-07-29 at 1 26 16 PM" src="https://user-images.githubusercontent.com/42546515/88832669-26d94580-d19f-11ea-9d2b-cf9b59e38a3c.png">

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by MickinSahni** [comment]
when you click on file for increase from left nav, it goes to regular file disability claim

**Comment by MickinSahni** [comment]
Any Top Recommendation keywords pointing to `https://www.va.gov/disability-benefits/apply/form-526-disability-claim/introduction` should instead point to `https://www.va.gov/disability/how-to-file-claim/`

Goal is to remove any links to 404s

**Comment by johnhashva** [comment]
Update:  I've "fixed" the File for increased disability compensation to link to https://www.va.gov/disability/how-to-file-claim/ -- and that change is live.

Do note: Search.gov Best Bets/Top Recommendations only allows ONE use of a referring URL.   You heard that right: You can't set-up the same destination URL for multiple Best Bets.

**Comment by MickinSahni** [comment]
@lunascoop can you do a quick independent check to make sure we got it all? 
moving to validate

**Comment by lunascoop** [comment]
I've validated that the File for increased disability compensation page links to https://www.va.gov/disability/how-to-file-claim/ -- and that change is live.
