### ISSUE TITLE
Create transformer for media-image

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#11819]
Create the following for the `media-image` bundle:

- Input schema
- Transformer
- Output schema

**Comment by drorva** [comment]
So this is a high priority now.

**Comment by cvalarida** [comment]
Yup. @theodur's got a connected PR at https://github.com/department-of-veterans-affairs/vets-website/pull/13645.

**Comment by theodur** [comment]
Merged in https://github.com/department-of-veterans-affairs/vets-website/pull/13645.
