### ISSUE TITLE
Update BGS Gem to Allow View Payments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#11827]
## Goal
In order to see their payments, we need to go into the BGS gem and update it so that the payment data are available.

## Tasks
- [ ] Update BGS gem to allow the View Payment data to be utilized

## Acceptance Criteria
- [ ] BGS gem code is submitted and a PR is requested for merging

**Comment by digitaldrk** [comment]
BGS call is not working
