### ISSUE TITLE
Conduct Veteran User Research/Testing on Prioritizing Features 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#11839]
To complete tasks and acceptance criteria.

**Comment by abuckley3385** [comment]
@arickalewis1 given you stated we are done with Veteran sessions I will close this issue.  Unless you have a reason for it to carry over to sprint 28 since its still in progress status. ??

**Comment by arickalewis1** [comment]
This one is finished @abuckley3385
