### ISSUE TITLE
STEM: "Rogers STEM Scholarship" missing from alert

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#11844]
"Rogers STEM Scholarship" is missing from "Your is in progress." It should say "Your Rogers STEM Scholarship is in progress."

Steps to reproduce:
1. Log in with user
2. Start filling out form 10203 https://staging.va.gov/education/apply-for-education-benefits/application/10203/
3. Navigate back to https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction
4. Observe
![Screen Shot 2020-07-30 at 9.14.06 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/42ad3ae8-9b9a-4681-9d29-06da7fafc07d)

**Comment by ccruzgra** [comment]
Hey @sonntag-adam This should be “Your Rogers STEM Scholarship application is in progress.” like we had discussed!

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13715

**Comment by ccruzgra** [comment]
Kenny pointed out that the form number was being put in by the code, and checking the 526ez reveals that's the right behavior, so we are moving forward with "Your Rogers STEM Scholarship application (22-10203) is in progress."

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-08-06 at 3 29 43 PM](https://user-images.githubusercontent.com/45575003/89574277-e52d4800-d7f9-11ea-92d0-9e47492f6486.png)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by ccruzgra** [comment]
@delli-gatti-michael This checks out for UX!

**Comment by sonntag-adam** [comment]
Closing bug.
