### ISSUE TITLE
STEM: 10203 form not showing under "Your Applications"

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#11843]
Steps to reproduce.

1. Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction
2. Log in with a user
3. Start filling out 10203 form
4. Select "My VA" near the top right of the page
5. Scroll down to "Your applications"
6. Observe 10203 form does not show

![Screen Shot 2020-07-30 at 7.00.32 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/30298fb2-d104-4a36-ab73-4bb320d7fc53)

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/13768

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-10 at 11.33.04 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bc0c6be5-50f1-432b-b116-fe89d7485471)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by ccruzgra** [comment]
@sonntag-adam This checks out for UX. Awesome to see the form there now!

**Comment by sonntag-adam** [comment]
Closing bug
