### ISSUE TITLE
Full Accessibility & 508 Office Audit Original Claims

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#11851]
## Overview
Benefits and Memorials have combined the BDD flow into the Original/All Claims flow.  This has been a complication is separating out the audits and some of the accessibility reviews.  However, after speaking to Jennifer, as long as it is possible to recreate what is happening on production in staging (using the appropriate users, in this case non-BDD users), we can work to do a full audit in staging.

I am creating this ticket as the placeholder and will continue to fill out the areas below before making an official request.  Expected by end of the week but there is a number of BAM deliverables ahead of this at the moment.

## Steps to complete the Full Accessibility & 508 Audit: 
- [X] Product Manager: create issue and fill in feature name in the title and other bolded information appropriately
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts when you request a full review_
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
- Link to your accessibility test plan:
  - **TestRail** [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc) **OR**
  - Complete/check-off the required items here:
    - [ ] [Axe scans in daily development](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-daily-development)
    - [ ] [Axe scans in end-to-end tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#axe-scans-in-end-to-end-tests)
    - [ ] [Color tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#color-tests)  
    - [ ] [Content resize check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#content-resize-check)
    - [ ] [Keyboard navigation check](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#keyboard-navigation-check)
    - [ ] [Screen reader tests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md#screen-reader-tests)

## Additional Notes
As part of this review, VSP will send your product to VA's 508 office for approval (as applicable)

**Comment by jenstrickland** [comment]
Once all the required artifacts above are complete, please tag me in a comment to let me know it's ready to start the audit.

**Comment by luke-gcio** [comment]
Closing against #9081 since we combined BDD into 526.
