### ISSUE TITLE
[Development] BDD: Additional Fields/Screens Required for BDD

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#11858]
## Issue Description
Based on the JSON (will attach example) looks like we need reservedNationalGuard and post-911 served in combat zone.  Nick will look to double check to make sure that is all.

## Acceptance Criteria
- [ ] We submit/ask all the questions EVSS submits down to EVSS
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
OBE, looks like there is not a lot of required data after talking to EVSS.

**Comment by ndsprinkle** [comment]
It seems that all required fields were covered in the one PR I linked to this ticket, so I am closing this.
