### ISSUE TITLE
page.fieldLeadership is not iterable

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11862]
## Issue Description
When performing a `vagovprod` build using the CMS export, I'm running into the
following error:

```
TypeError: page.fieldLeadership is not iterable
    at createHealthCareRegionListPages (/home/christopher/adhoc/vets-website/src/site/stages/build/drupal/health-care-region.js:224:24)
    at pipeDrupalPagesIntoMetalsmith (/home/christopher/adhoc/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:126:7)
    at Ware.<anonymous> (/home/christopher/adhoc/vets-website/src/site/stages/build/drupal/metalsmith-drupal.js:264:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It's not immediately clear why this is happening, but my hunch is that it's due
to the `health_care_region_page` transformer not matching the GraphQL output.

## Tasks
- [ ] Discover why this is happening
- [ ] Fix it

**Comment by cvalarida** [comment]
This might have something to do with these reverse fields we've been running into. @swirtSJW 's change to add all the reverse fields should get deployed tomorrow, so if it _is_ that, we should get unblocked then.

**Comment by theodur** [comment]
After adding the `field_leadership` field to the `health_care_region_page` transformer, the error above seems to have went away. One thing I noticed is that `fieldLeadership` is of the type `node-person_profile`, and `node-person_profile` has the field `fieldOffice`, which can be of the type `node-health_care_region_page`. So it looks like we have a circular reference problem.

**Comment by theodur** [comment]
Is it safe to assume that every `node-person_profile` in the `fieldLeadership` field will have the `fieldOffice` of `node-health_care_region_page`, specifically the `node-health_care_region_page` entity that we are transforming at that moment? That's the only way I can see us getting around this 🤔. Sorry if this doesn't make sense 😅.

**Comment by theodur** [comment]
Merged in https://github.com/department-of-veterans-affairs/vets-website/pull/13813.
