### ISSUE TITLE
STEM: Update applicant confirmation email content

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11876]
## Assumptions
1. This email was originally implemented as part of story #11809

## Acceptance Criteria
1. The following content in the STEM applicant email is updated from: 
   > You’ll get a Certificate of Eligibility (COE), or decision letter, in the mail. If we’ve approved your application, you can bring this to the VA certifying official at your school.
  
   to 

   > You’ll get a Certificate of Eligibility (COE) or decision letter in the mail. If we’ve approved your application, you can bring the COE to the VA certifying official at your school.

2. The link "More about what happens after you apply" is: https://www.va.gov/education/after-you-apply/?utm_source=confirmation_email&utm_medium=email&utm_campaign=what_happens_after_you_apply

## Supporting Artifacts
1. [STEM-ApplicationConfirmationEmail-20200805.docx](https://app.zenhub.com/files/133843125/428e5d9e-32fb-4619-8434-cdfb0e1a20b6/download)

**Comment by desireeturner** [comment]
This language was implemented in the origninal story #11809

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4641

**Comment by delli-gatti-michael** [comment]
Local testing complete. See:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11809#issuecomment-670026899

**Comment by delli-gatti-michael** [comment]
Changes are live on staging. Closing this issue

**Comment by delli-gatti-michael** [comment]
Tested by Testrail test case:
https://dsvavsp.testrail.io/index.php?/tests/view/10260
