### ISSUE TITLE
Time the CMS export download and untarring separately

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11871]
## Problem Statement
There's only one timer for downloading and untarring the CMS export, so we don't
know how long each operation takes.

## Acceptance Criteria
- [ ] The time for downloading the CMS export is logged separately
- [ ] The time for untarring the CMS export is logged separately

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
