### ISSUE TITLE
Time the non-node query

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11870]
## Issue Description
Currently, the query for getting non-node conted isn't timed, so we have no way
of knowing how long it takes.

## Acceptance Criteria
- [ ] The non-node query is timed and the result is logged

**Comment by drorva** [comment]
Part of the reverse field work.

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
