### ISSUE TITLE
Bottom padding for VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#11873]
## Issue Description

VAMC page has 0 padding along bottom bar

**Seen on pages with a small amount of content.** 

![image (43).png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/5141c234-904d-4adb-8a45-073ba206e764)

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure unit tests are available and updated 

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] All VAMC pages have the same padding above the footer, regardless of the amount of content displayed on the page. 
- [ ] Unit tests pass

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
merged, deploying tomorrow.
