### ISSUE TITLE
Fix nested anchor tags in crisis hotline modal 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#11875]
>Warning: validateDOMNesting(...): &lt;a&gt; cannot appear as a descendant of &lt;a&gt;.![Screen Shot 2020-07-30 at 4.19.08 PM.png](https://images.zenhubusercontent.com/5a5d4c174b5806bc2bc2db50/65590362-3875-4f8c-b8a3-a587e7737192)

maybe use `<Telephone />` component

**Comment by ncksllvn** [comment]
I _think_ this is related to https://github.com/department-of-veterans-affairs/vets-website/pull/13607/files#r465970894. This should be an easy fix and the error it's producing is ugly even though it has no effect on the user. I'm gonna pull it into our Ready column.
