### ISSUE TITLE
Access for: Leyda Hughes - VAMC-Upgrade team - GovernmentCIO

### ISSUE THREAD

**Issue by lildziner** [department-of-veterans-affairs/va.gov-team#11879]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product.  Access needed for: dev, staging, prod,  CI environments and Jenkins.
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Leyda Hughes
- Please Provide your email.
   > leyda.hughes@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSA / Facilities
   > Role: UX Designer
   > Company: Ad Hoc

- Requesting SSH key authorization?
   > YES 

- What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUUyKyRrr/hb0jCuFcOWPrRU4dWGGMtd3fQ6FyTNHkI8s7qDxAcUwSEoPqYG8dNqA0DA1AdGDOy+e0mr8rckFiR0Ew7tDr/CQ6NxqdDYgNEQsO1xJrB6ntNSHmLn+a1JXYsu4LtRtRWoHWuCw16E+t7zhe05MfTT5fy15o7dtUesfJ+TSxK4q9UtC5MhbCyaOUUGObn4AZq0OwaefyfBmLR/Zbi3o71vXHAu7k8cC7Ye+AsXpV2ue4uFd9qSfzjGWi+cS0RpZKTApJ6D72RUDcQM9CrX3Jfat5GQjGjZPzj9+uoGPwqrmtoVRaWmyEpPaGDJe13S+2dA8NEUqhAQ4log1LpVG6QcHoMSrxE8WEWEWXYJSlTAKwuTthQsZrNKNt24p8lA+11G8kCgvHQzdUZC+ORNA60aY1qce+PWKWVSobF5Hdh8jzmm4QCSjh+bVErrkEq8CzcxOVM03wCnOe0xlhMPueUKEh76BelV5d9d+ahhgOLobeA/UL8JEn8CM= leydahughes@Leyda-MacBook.local
```

- Grant AWS Console access?
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
