### ISSUE TITLE
Accessibility feedback for staging review - Authenticated Experience [Profile 2.0]

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#11880]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Point of Contact

**VFS Point of Contact:** Jennifer (VSA) & Trevor (VSP)

## Description

This ticket houses accessibility issues for the staging review of Authenticated Experience - Profile 2.0.

## Test cases

* [Profile 2.0 staging users + use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/QA/Staging%20Users%20-%20Test%20Cases.md)

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

@1Copenut ready for VSP review 🤘

**Comment by jenstrickland** [comment]
In IE11 I noticed this bug, and adding a note here for @tlei123 and QA review.

![image (4)](https://user-images.githubusercontent.com/57469/89192080-d92f5500-d571-11ea-9396-289c6cc9e8d0.png)

**Comment by 1Copenut** [comment]
@jenstrickland I added the one issue we discussed earlier about focus management. Have mapped it to the VSP ticket for the forms library element.

No further feedback from VSP. We are 💯

**Comment by tlei123** [comment]
> In IE11 I noticed this bug, and adding a note here for @tlei123 @pjhill in QA review.

#11971 styling defect opened, assigned to @mshea0606

**Comment by Samara-Strauss** [comment]
Does this still need to be open?

**Comment by jenstrickland** [comment]
We usually leave the epic open until all issues are remediated. However, the responsibility for the remaining issue is not on your team, so I say close it. Thanks for the nudge!
