### ISSUE TITLE
Benefit Hubs and Benefit Hub Detail Pivoted against Mobile OS (iOs and Android)

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/va.gov-team#11883]
Goal: create a way to view iOs and Android columns for the overall benefit hub content groupings, as well as the top pages within each grouping, so that we can see if there are differences in

* Behaviors across hubs comparing mobile operating systems to the aggregate
* Behaviors within hubs (e.g. most used resources/apps) comparing mobile operating systems to the aggregate

If we could take General Benefit Hub activity: 

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.pageGroup1&explorer-table.plotKeys=%5B%5D/

and each hub (disability as an example)

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pageGroup1:Disability

and look at iOs numbers AND Android numbers specifically for
* Page views
* Unique views
* Avg time on page
* Entrances
* Exits

This could be delivered in any number of ways, e.g as additional colums in the same chart, separate charts, etc. 

An alternative approach would be being able to apply Benefit Hub content groupings as we do now in Behavior > Site Content > All Pages for benefit hubs as a filter within this report: 

https://analytics.google.com/analytics/web/#/report/visitors-browser/a50123418w177519031p184624291/explorer-table.plotKeys=%5B%5D&explorer-segmentExplorer.segmentId=analytics.operatingSystem

**Comment by bsmartin-ep** [comment]
@KevinMHoffmanUSDS -

Here is a custom report to get us started.  You will need to import this into a view (like _WBC - VA.gov Modernized_) that has the Content Groups set up...

https://analytics.google.com/analytics/web/template?uid=ReLzvhqpRGaQ7AdzjCVV8g

Once imported, you can add dimensions or metrics or adjust the filters by clicking EDIT in the report.

Let me know if you have any questions.

**Comment by KevinMHoffmanUSDS** [comment]
@bsmartin-ep Thank you! I'll take a look right now.

**Comment by KevinMHoffmanUSDS** [comment]
Thanks for this! We can consider this one closed.
