### ISSUE TITLE
VAOS UX meeting

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1189]

**Comment by smoonpeyes** [comment]
@emilywaggoner You presented the UX overview to Carolyn. Are there any other designers on VAOS that need this overview, or can we close this ticket?

**Comment by emilywaggoner** [comment]
Let's leave it open for now actually because Carolyn had to reschedule our meeting until after she gets back from vacation. We are scheduled to meet on Wednesday, Sept. 11.

**Comment by andreahewitt-odd** [comment]
@emilywaggoner  There's one other designer on that team also: https://docs.google.com/spreadsheets/d/1O-ESPJIJghOLv_7qnglOkxvBntxxKzUnY9TBb5ZNZF8/edit?usp=drive_web&ouid=115401213582977368894

**Comment by andreahewitt-odd** [comment]
@emilywaggoner Are you guys still meeting today?

**Comment by emilywaggoner** [comment]
Yes, we are meeting from 2:30-3:30pm ET today.
