### ISSUE TITLE
508-defect-4 [MOBILE DESIGN] Consider abutting mobile subnav to the top of viewport

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#11890]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The mobile navigation is absolutely positioned and other content scrolls beneath it. There is a bit of space on the top where content is visible. This may be cognitively confusing, and interfere when layered over interactive elements. The recommendation is to **consider** removing the space above by removing the .8rem top margin.

## Point of Contact

**VFS Point of Contact:**  Jennifer

## Acceptance Criteria

As a mobile user with cognitive impairment, I want to confidently understand the interface so that I may interact with the mobile navigation.

## Steps to Recreate

1. Enter https://staging.va.gov in browser
2. Log in as user 36
3. Navigate to Profile
4. Resize browser to mobile width
5. Scroll down the page
6. Verify the subnav remains in view at the top, with space between the top of the nav and the viewport
7. Continue to scroll and evaluate the content that scrolls beneath the subnav

## Possible Fixes (optional)

**Current styling**

![Screen Shot 2020-07-31 at 11 48 17 AM](https://user-images.githubusercontent.com/57469/89052534-d6d7bb80-d323-11ea-8479-c49d28e44faa.png)

```diff
.mobile-nav .menu-wrapper {
    position: absolute;
    background-color: #fff;
    left: 0;
    right: 0;
!    margin: .8rem .8rem 1.6rem;
    color: #0071bb;
    border: 1px solid #0071bb;
    border-radius: 4px;
}
```

**Suggested styling**

![Screen Shot 2020-07-31 at 11 48 34 AM](https://user-images.githubusercontent.com/57469/89052552-df2ff680-d323-11ea-834b-e93e8d200110.png)

```diff
.mobile-nav .menu-wrapper {
    position: absolute;
    background-color: #fff;
    left: 0;
    right: 0;
+    margin: 0 .8rem 1.6rem;
    color: #0071bb;
    border: 1px solid #0071bb;
    border-radius: 4px;
}
```

**Comment by mshea0606** [comment]
@tressaellen to add designs

**Comment by tressaellen** [comment]
I suggest making the top an opaque white and adding a drop shadow to help differentiate between the content and button even more.

![mobile sticky nav.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/e4e4dd5f-2626-4486-bfec-0d434d02088f)

**Comment by tressaellen** [comment]
FE will be tracked in #12873

**Comment by jenstrickland** [comment]
I need to be able to validate the fix to close this issue.

**Comment by tressaellen** [comment]
Oh, sorry Jen!

**Comment by tressaellen** [comment]
@jenstrickland - this is ready to be validated

**Comment by jenstrickland** [comment]
Validated
