### ISSUE TITLE
The Platform Newsletter: August 

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#11897]
### What is your documentation request, question, comment, or issue?

Requesting content review of the August newsletter - copy and linked documents.
Target release date for newsletter: 8/10

**Comment by gmaciolek** [comment]
@jchasia-adhoc  Should I sign in to MailChimp to see the draft of the newsletter? Is it ready for review yet? I'm thinking about working on this with the new writer on the Content and IA team, so just let me know when it's ready and we'll take a look.

**Comment by jchasia-adhoc** [comment]
@gmaciolek The draft is ready for review. [https://us19.admin.mailchimp.com/campaigns/wizard/neapolitan?id=4512268#](https://us19.admin.mailchimp.com/campaigns/wizard/neapolitan?id=4512268#)
Open Newsletter: August 2020 and click on “Edit Design” to see the draft newsletter.

PM for each topic:
- Google Analytics Content Grouping for Benefit Hubs: Joanne Esteban
- External Service Performance Monitoring: Alex Pappas
- Cypress Testing: Megan Kelley
- Mobile Month: Kevin Hoffman
