### ISSUE TITLE
Only run output schema validation on root entities

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11898]
### Circular reference validation trouble
When a parent entity has a child entity which has a field pointing back to the parent entity, the output schema for the child's field expects a transformed entity. The trouble is, when that child's field points to an entity in its ancestry tree, it hasn't been transformed yet.

**Example**
![image](https://user-images.githubusercontent.com/12970166/89067513-48b00500-d324-11ea-877a-d489a1594f37.png)

### Double-validation
After a child entity is transformed, it's validated. After its parent is transformed, all of _its_ fields are validated, including all fields with children entities. This means the children are run through JSON schema validation twice.

It's not a big deal, but it slows down the process somewhat.

## Proposed Solution
Only run the output schema validation on the root entities.

**Benefits**
- All entities are still validated
- All entities are only validated once
- When a parent uses only a subset of fields of a a child entity, only that subset of fields is validated
  - Assuming, of course, the parent's output schema only specifies that subset

**Drawbacks**
- Debugging validation errors in deeply-nested entities may be tricky
  - I feel like this is a solvable problem, but I don't have a solution to it on the top of my head

**Comment by jhonnyoddball** [comment]
Done!
