### ISSUE TITLE
Add contact information update clarification to EC reason for appointment page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11899]
As a Veteran using Express Care, it needs to be clear to me that if I update my phone and/or email information in my EC request that this information is not reflected in my VA Profile. 

## Acceptance Criteria:
- [ ] On EC reason for request page provide a promote that clarifies my contact information use
- [ ] Veteran should be able to update their VA Profile if they want 

-------
### _We should follow the same pattern we have in other request flow for this need._ 
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/2ab8b6ac-45c5-4ac1-97a0-6e82d01cc7f0)

Area in red potential candidate for adding content. 
![ec request.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/2796ee0a-5bc2-45c1-984f-15220bb19f83)

**Comment by lenaecb** [comment]
Talked this over with @lalexanderson-dsva and she agrees.

**Comment by peggygannon** [comment]
Hi, @lenaecb this is what is currently in the EC prototype (in italics). I tweaked this content slightly to make it more applicable to EC. We can add the sentence about profile next iteration of updates. 

**Your contact information**
*Please provide your phone number and email address where VA health care staff can contact you. This contact information will be used just for Express Care and won’t be updated in your VA profile.* 


We can add this line: 
If you want to update your contact information for all your accounts, please [go to your profile page].

**Comment by lenaecb** [comment]
Thanks, @peggygannon we are moving to implement the new 'reason for request' page now so we would like to go ahead and get this added to the mock. See current iteration of that [page here](https://vsateams.invisionapp.com/share/FEYB1YQM7ZW#/screens/427456322)

@rtwell can you add in @peggygannon suggestion to include the following line with our 'contact information' section - "_If you want to update your contact information for all your accounts, please [go to your profile page]."_ 

I'll make sure this gets implemented as part of the eng team creating the 'reason for request' page.

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/89590614-524ed680-d816-11ea-9d9b-8ab02a6750cc.png)

**Comment by peggygannon** [comment]
@rtwell thank you.. looks good
