### ISSUE TITLE
Letter Downloads show several success events when a failure occurs

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#119]
@nedierecel commented on [Fri Nov 23 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15282)

@rtluu Placing you on this first for review and to reassign as needed to FE team.

- Expected Behavior: Since the button is grayed out, I expected the events `letter-list-success` and `letter-get-bsl-success` to not fire.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/3cba9d75-206d-4ee8-b9e4-5bf61133f5a0)

---

@nedierecel commented on [Thu May 09 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15282#issuecomment-490945698)

Shifting this to Ready to review and then Q/A

---

@nedierecel commented on [Fri May 17 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15282#issuecomment-493497748)

Hello @hinzed1127 - I have this backlog issue to research these two events that are triggered:

`letter-list-success` and `letter-get-bsl-success` - These events appeared when I logged in with a user that had the "View Letters" button grayed out. Is this expected behavior, or is this a bug?

---

@hinzed1127 commented on [Fri May 17 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15282#issuecomment-493571250)

@nedierecel right now like those both fire after successful API requests. Included in the the return of the address request is a `canUpdate` flag for if the user has permissions to update their address. In this case, this seems to be the flow happening:

1. Letters request is successful (GA event fires)
2. Address request is successful
   - However, the address is empty and the response also communicates that the user does **not** have permission to update it
3. Button is disabled because the address is empty

From here they are stuck, and it seems the reason isn't effectively communicated to user for this situation. If that's the case, we should verify this is intended behavior and update how that info is displayed.

Is there a user in staging that I can use to reproduce this issue? I couldn't find the "Jamie Wood" user in the [MVI staging users](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/MVI%20Integration/reference_documents/mvi_stagingUsers_fullList.csv).

---

@nedierecel commented on [Mon May 20 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15282#issuecomment-494000380)

Thanks for the feedback @hinzed1127 

---

@nedierecel commented on [Tue May 28 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15282#issuecomment-496583792)

@hinzed1127 Were you able to recreate the issue with this user? Thanks!

**Comment by joanneesteban** [comment]
@YanaRoy Do you know if we can have an engineer confirm the expected behavior above for Benefits?

**Comment by joanneesteban** [comment]
@bsmartin-ep 

Assigning you to this for now, but we'll discuss later as this is staying in the backlog for now. No need to start work on this just yet.

**Comment by jonwehausen** [comment]
Not sure if this is still an issue. so adding bug label and adding to tracking board.
