### ISSUE TITLE
[Bug] CST: Claim Status Tool Content Update - Direct to VA.gov Not eBenefits

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#11906]
## What happened?
When I go to https://staging.va.gov/track-claims/your-claims I see 

"This page shows only completed claim applications. If you started a claim but haven’t finished it yet, go to eBenefits to work on it." but we should be directing people to do their claims on va.gov. 
![Screen Shot 2020-07-31 at 5 04 50 PM](https://user-images.githubusercontent.com/19188/89077555-701cc700-d350-11ea-86da-3f18d7f948ce.png)

## Steps to Reproduce
- URL: https://staging.va.gov/track-claims/your-claims
- Test User _(if applicable)_: vets.gov.user+206@gmail.com

**Comment by ndsprinkle** [comment]
Going to begin work on this while waiting to meet with Kevin for 15897, though I'll probably need design help on this as well.

**Comment by ndsprinkle** [comment]
PR created: https://github.com/department-of-veterans-affairs/vets-website/pull/15357

After meeting with Kevin, for now we are just going to remove the text directing the user to eBenefits. In the future, if we feel it would be more helpful, we may look into checking the user's in progress forms and directing them to those form as the purpose behind this messaging is to convey to the user that they don't have any completed claims. The users may have claims/forms in progress, but those won't appear.
