### ISSUE TITLE
Content review of Debt Letters MVP empty states

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11902]
## Issue Description
I'm looking for a content review on some empty states I'm working on for the Debt Letters tool. There are 3 potential empty states that can occur:
- [A veteran accesses the tool and has never had a VA debt](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130748284/simulate/no-panels?mode=i)
   - The veteran would not have any debts nor any debt letters. This is the base empty state for the tool.
- [A veteran has no current VA debts, but they have resolved debts in their record](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174953/simulate/no-panels?mode=i)
   - We have a constraint where we will be unable to display resolved debts, so we need an empty state for the debt summary section while we still provide access to the veteran's resolved letters
- [If a veteran has received a debt after debts were put on hold in March 2020 due to COVID-19](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174235/simulate/no-panels?mode=i)
   - DMC put debt collection on hold in March. A veteran can still actively receive debt(s), but they won't receive any letters. Therefore, we want to provide them information about why they have a debt but don't have any letters. 
   - I'm unsure about this content because it seems a little long and I bet there's a more eloquent way to phrase why the veteran isn't receiving debt collection letters. I'm debating if we want to include the DMC's contact info in this empty state since there's no action on the veteran's part. 

**Note:** The designs linked use the right rail component. We're going to be releasing a second iteration that replaces the right rail content with the 'on this page' anchor links. Just wanted to give ya a heads up in case you were wondering while reviewing the content :) 

Please feel free to edit this ticket to fit whatever format works best for you!

**Comment by peggygannon** [comment]
Hi, @rileyorr I have a question, in the mockup, the second alert (resolved debt) is the same as the first one (no debt). Is this correct?

**Comment by rileyorr** [comment]
Good morning @peggygannon! You're right, I did make a mistake! Before my team found out that we couldn't provide additional info about resolved debts but could still provide the letters, that verbiage "to get information about resolved debts" was part of the original empty state. My apologies; I've updated the 'resolved debt' alert!

**Comment by peggygannon** [comment]
Hi, @rileyorr here are recommendation for empty state alerts for Debt Management tool. I'm still working on the COVID-19 related alerts. 

Use case 1: Veteran doesn't have any debt.
 
**You don't have any VA debt**
Our records show you don’t have any debt related to VA benefits. If you think this is an error, please contact the Debt Management Center at 800-827-0648. 
If you have VA health care copay debt, go to our [pay your copy bill] page to learn about your payment options. 


Use case 2:  No current debt, but has resolved debt in history

**You don't have any current VA debt**
Our records show you don’t have any debt related to VA benefits. If you think this is an error or you have questions about your past debt, please contact the Debt Management Center at 800-827-0648. 
If you have VA health care copay debt, go to our [pay your copy bill] page to learn about your payment options.

**Comment by rileyorr** [comment]
Thanks, @peggygannon! I've updated the prototype to reflect those changes :)

**Comment by peggygannon** [comment]
@rileyorr ok, thank you. the alerts look good. 

I left you a note in this [ticket](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/11935) about the COVID-19 related alert for debt collection.

**Comment by rileyorr** [comment]
@peggygannon I wanted to follow up about the [COVID-related empty state](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174235/simulate/sitemap?mode=i) in this ticket since it's slightly different from the alert you recently approved. Are there any content changes I should make? I've attached a screenshot for reference. 

<img width="698" alt="Screen Shot 2020-08-18 at 10 29 26 AM" src="https://user-images.githubusercontent.com/46329147/90525848-b2f6e100-e13d-11ea-8eba-569404934654.png">

**Comment by peggygannon** [comment]
Hi, @rileyorr , sorry I missed this last week. I recommend that we use this alert for this page as well. 

**VA debt collection is on hold due to the coronavirus**
We’ve taken action to stop collection on newly established Veteran debt and make it easier for Veterans to request extended repayment plans and address other financial needs during this time.

You won’t receive any debt collection letters in the mail until after December 31, 2020.
For the latest information about managing VA debt, visit our [coronavirus FAQs].

**Comment by rileyorr** [comment]
Hey, @peggygannon! No worries - I know you've got a lot on your plate :) I updated the COVID empty state with your suggested content, so we should be good to close this ticket!

**Comment by peggygannon** [comment]
ok, sounds good. thank you!
