### ISSUE TITLE
VAOS Frontend meeting

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1191]
These developers have been working on the platform for a long time so gear this meeting toward how we can assist them through their process. 

VAOS team: 
FE Engineers Jeff Balboni and Narin Ratana
Architect: Kam Karshenas

**Comment by accbjt** [comment]
Jeff Balboni and Narin know the system very well, so I won't be needing to go over this with them.
