### ISSUE TITLE
[Pre-release] Update revproxy for dev environment

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#11914]
Before we test out the new content bucket and new application bucket in the **staging** environment, we should test them in the **dev** environment. 

Tasks

- [x] Update dev revproxy config to point to new app bucket
- [ ] Monitor applications in dev environment
- [x] Update dev revproxy config to point to new content bucket
- [ ] Monitor static pages in dev environment

**Comment by jhonnyoddball** [comment]
I'm creating a PR that will update `default_proxy_url` in the [nginx webserver config file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_website_server.conf.j2#L17) to work with all buckets for every environment

**Comment by jhonnyoddball** [comment]
Successfully deployed content from [`http://content.dev.va.gov.s3-website-us-gov-west-1.amazonaws.com`](http://content.dev.va.gov.s3-website-us-gov-west-1.amazonaws.com) into [`https://dev.va.gov/`](https://dev.va.gov/) using reserve proxy.

Pull requests related:
- Update reverse proxy for dev environment #[8666](https://github.com/department-of-veterans-affairs/devops/pull/8666)
- Update reverse proxy conditionals #[8679](https://github.com/department-of-veterans-affairs/devops/pull/8679)
- don't override hostname in s3 proxy requests #[8681](https://github.com/department-of-veterans-affairs/devops/pull/8681)

**Comment by jhonnyoddball** [comment]
This [PR](https://github.com/department-of-veterans-affairs/devops/pull/8707) was merged deploying the apps bucket using the reverse proxy
