### ISSUE TITLE
[Pre-release] Create rollback documentation

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#11912]
Before we start trying to use the new content bucket and new application bucket, we should create documentation for how we intend to rollback our changes if something goes wrong.

**Comment by jhonnyoddball** [comment]
Rollback documentation has been added in this [PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/21566) to the [full proxy documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/infrastructure/reverse_proxy.md)
