### ISSUE TITLE
[Pre-release] Notify teams about upcoming revproxy changes

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#11913]
Before we start using the new application bucket and new content bucket, we should let teams know so they're not caught off guard if something goes wrong.

**Comment by meganhkelley** [comment]
First step: Megan, Tim, Bill, Dan connect about messaging needed

**Comment by meganhkelley** [comment]
Current step is to change dev, messaged potential dev instability to teams week of 3/1/21
