### ISSUE TITLE
Improve the contrast of the  "OK to proceed" page

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#11922]
Patrick has heard some feedback that the final OK screen needs to have more contrast. We can't lighten the white text any more. But we can darken the background. 

Per the VA design system, we have a couple darker blues to try.

https://design.va.gov/design/color-palette

#003e73 is $color-primary-darker
#112e51 is $color-primary-darkest

Also we could try increasing the size of the checkmark and the "OK to proceed" text.

**Comment by batemapf** [comment]
OK background to be updated here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/coronavirus-screener/sass/coronavirus-screener.scss#L23

OK to proceed text and check to be updated (maybe) here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/coronavirus-screener/sass/coronavirus-screener.scss#L22 or https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/coronavirus-screener/components/FormResult.jsx#L30

**Comment by mchelen-gov** [comment]
closed by https://github.com/department-of-veterans-affairs/vets-website/pull/13787
