### ISSUE TITLE
CMS sprint 11 PO comments/answers to LC questions

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#11921]
## CMS sprint 11 PO comments/answers to LC questions

[Demo video](https://zoom.us/rec/play/uJMtJOmh_Wg3G9WQ4gSDUP5_W47rKaqsgyBI_fQPzky1UXhVNlTwZLEWauUKNnTMgC-z7yVljdd_eMpp?continueMode=true) / Password: vW!Kh5WN

**Meta title field - all LC templates**

-  Similar to this field in the benefit details pages, please make meta title auto generated within the CMS by the H1. [Per requirements here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md), the only difference is the expanded char count for LC. 
-  Make meta title not-editable by authors (i.e., it's totally based on the 70 character H1). No casing logic needed. 

**CTA buttons - all templates**

- Currently we don't set a character max limit for buttons in the design system. The CMS demo looked like it was setting this to 30 characters in the LC, Please make the max character with spaces 40. Please make this rigid. 
- Confirming yes - we want ability to link to non-drupal links. 

**TOC links - all templates**

- We didn't see this demoed but it was on one of the templates demoed. I just want to confirm that this is optional yes/no and that when it is checked, a minimum of two H2 sections are needed on the page. 
- TOC link text should be autogenerated by the H2 text and not manually editable. 

**Multiple FAQs**

- Display in AX - instead of side by side/horizontal display of order, please make these stacking to reflect the order in which they would display
- Question about min and max - Great Q! For LC: make the minimum required in LC 2, in or out of accordions; maximum not in accordions 20; maximum inside accordions 60. 
- FAQ 'metadata,' per @JeffBarnesUSDS comment at around 11:05 min: each FAQ should have a unique ID (same as node?), per COPE epic; FAQs should also be findable in the CMS AX by topic, audience, owner, in addition to the text of the question. 

**Step-by-step template**

- Images - We didn't see the AX for actually uploading the images, but currently it doesn't appear to allow cropping. This is just a question: do we have cropping ability in the VAMC? If so, can we use the same component capability here? 

**About template**

- Not sure what the 'big picture' or governance issues are for the About template (and why that wouldn't be a blocker for the other templates but would be for the About). 
- Per Jeff Barnes - if the About template needs to be for LC only, we should do that. The About template in LC is much much more limited and rigid than in the Benefit Detail pages, so the LC About would actually not be used by authors in the Benefit hubs.

**Comment by oksana-c** [comment]
@jenniferlee-dsva thank you for the summary. 

**Meta titles**
we'll follow up on auto generated meta titles within this issue https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2547 

We may need a separate conversation around search needs and the use of meta description field to obtain a teaser.

**CTA char limit**

we took a wild guess on char limit here per original reqs
> Required: CTA buttons – at least 1 required; up to 2; must restrict button text length (to prevent wrapping button labels in mobile)

thanks for clarifying the number. Do you mind me updating the [spec page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md) as we know more about rigidity of LC components?

updated char limit requirement is captured here - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2548 

**TOC links - all templates**

> We didn't see this demoed but it was on one of the templates demoed. I just want to confirm that this is optional yes/no and that when it is checked, a minimum of two H2 sections are needed on the page.

TOC is currently present only on "FAQ - multiple Q&As" template. The assumption is that Process list and Single Q&A will never have enough headings to generate a ToC. Correct?

> TOC link text should be autogenerated by the H2 text and not manually editable.

ToC is not manually editable in the CMS. ToC is generated by FE logic.
ToC is always optional. Our assumption is that ToC will be processed/generated by FE logic only if the checkbox is checked in Drupal. We may need to confirm w/ @kelsonic or @ncksllvn 

**Multiple FAQs**

great feedback. Noted.

**Step-by-step template**

Cropping is available. Cropping options are similar to existing "embedded image" component. I can demo on our call later today.

**About template**

The "About" template is very similar to existing "Detail page" content type. Our hope is to create an Authoring Experience around existing Details page that will support LC content rigidity requirements + offer LC-specific components. 
Same AX will also be used for templates like Q&A (single), Media list templates.
The FE team will be able to reuse the majority of the work they've done for Detail page components.
I can expand on our plan/thinking on the call today/tomorrow.

**Comment by FranECross** [comment]
Closing old, obsolete ticket.
