### ISSUE TITLE
Prod error: facility name is null

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#11923]
We have a few instances of the facility name being null unexpectedly:

http://sentry.vfs.va.gov/vets-gov/website-production/issues/164536/?query=is%3Aunresolved%20source%3Avaos%20TypeError
http://sentry.vfs.va.gov/vets-gov/website-production/issues/145951/?query=is%3Aunresolved%20source%3Avaos%20TypeError

Possibly this one: http://sentry.vfs.va.gov/vets-gov/website-production/issues/156142/?query=is%3Aunresolved%20source%3Avaos%20TypeError

**Comment by narin** [comment]
Haven't had any luck reproducing this one and it has affected less than 10 users.  Moving back to Ready column for now.

**Comment by jbalboni** [comment]
I think this is a duplicate of #12644, closing
