### ISSUE TITLE
VSP QA feedback for Profile 2.0 [Staging Review]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#11938]
## VSP QA feedback on SSO-login [Staging Review]

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

### Links
**Test Plan / Execution logs:**
https://dsvavsp.testrail.io/index.php?/plans/view/196
**Coverage for References Report**
https://dsvavsp.testrail.io/index.php?/reports/view/122
**Summary (Defects) Report**
https://dsvavsp.testrail.io/index.php?/reports/view/123

### Feedback
**Test Execution Logs**
1. **⚠️Should**: It appears as though three or four test cases may be currently blocked. The team should work to resolve all issues blocking the verification of test cases prior to releasing to production.
1. **Comment**: Great cross-browser coverage is demonstrated in this test plan -- awesome!

**Coverage for References Report**
1. **⚠️Should**: Four test cases do not contain references. The team should clarify which user story(ies) these test cases verify 

**Summary (Defects) Report**
1. **❗️ Must**: [Defect 11489](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11489) appears to potentially be an accessibility issue. Accessibility issue potential combined with the ease with which this can resolved leads me to believe that his defect is a must resolve prior to release to production.

## Definition of Done
- [ ] Acknowledge each item of feedback with a decision
- [ ] VSP QA will close ticket after reviewing feedback decisions

**Comment by tlei123** [comment]
I'll open a styling defect for the [IE11 anomaly](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11880#issuecomment-668047656) that Jennifer caught during A11y review.  Will link here when tic's created.

Thx for catching that, @jenstrickland !

**Comment by tlei123** [comment]
> I'll open a styling defect for the [IE11 anomaly](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11880#issuecomment-668047656) that Jennifer caught during A11y review. Will link here when tic's created.

#11971 styling defect opened.

**Comment by mshea0606** [comment]
@mshea0606 tickets have been created for these issues

**Comment by Samara-Strauss** [comment]
> It appears as though three or four test cases may be currently blocked. The team should work to resolve all issues blocking the verification of test cases prior to releasing to production.

Assuming this refers to the three test cases highlighted in yellow [in this spreadsheet](https://docs.google.com/spreadsheets/d/1XQiqBSol6BhQxnRpjuohblsNBLQx4SLDYbr9NJflCtM/edit?ts=5f2987eb#gid=1599074391).

I left these comments in the spreadsheet, but also posting here for visibility/documentation purposes.

- Military info: "We cant access your military information" — We probably don't have a user who will show this messaging since we can't force this backend error.
- Direct deposit: "This user should see the direct deposit functionality but they should see a gate to add 2FA first" — This use case is always a pain for us, as almost, if not all ID.me staging users have 2FA set up. I guess 299 had worked when we created this original list but doesn't now. I am trying to track down whether we can access this test case with the old DS Logon credentials we used to use to test it, but having some trouble signing in with DS Logon right now. I'll get back to you if I can get this figured out.
- Direct deposit: "This user should not see the direct deposit feature" — Try user 360 instead.

**Comment by pjhill** [comment]
Thanks for the update regarding the blocked test cases. It looks like at least two of them may have the blocks cleared in short order.

Regarding the military info error messaging, were you able to create the conditions necessary to cause the error message locally?

**Comment by Samara-Strauss** [comment]
> Regarding the military info error messaging, were you able to create the conditions necessary to cause the error message locally?

@sanlouise or @erikphansen could probably help out with this.

**Comment by tlei123** [comment]
@pjhill , DD-ineligible test-case ([C773](https://dsvavsp.testrail.io/index.php?/cases/view/773)) has Passed ([T9732](https://dsvavsp.testrail.io/index.php?/tests/view/9732)), using provide test-acct 360.

Re. those test-cases without references, there're no specific tickets that explicitly mentioned their respective use-case conditions -- only the [test-case spreadsheet](https://docs.google.com/spreadsheets/d/1XQiqBSol6BhQxnRpjuohblsNBLQx4SLDYbr9NJflCtM/edit?ts=5f2987eb#gid=1599074391) has them listed.  Considering there've never been any GH tickets strictly dedicated to use-/test-cases, I'm gonna start adding non-GH-ticket links to the Refs report Description.  The next Refs report will have a link to the test-cases spreadsheet.  Lemme know if you have better ideas.

I'll run that last remaining DD - no 2FA test-case ([C772](https://dsvavsp.testrail.io/index.php?/cases/view/772))(multiple cross-browser/-device tests) once a test-acct's been found for it, then I'll generate final reports.

Feel free to Comment further if you have more questions/concerns, or ping me directly on Slack.

**Comment by pjhill** [comment]
@tzelei --

> Re. those test-cases without References, there're no specific GH tickets that explicitly mention their respective use-case conditions -- only the [test-case spreadsheet](https://docs.google.com/spreadsheets/d/1XQiqBSol6BhQxnRpjuohblsNBLQx4SLDYbr9NJflCtM/edit?ts=5f2987eb#gid=1599074391) has them listed. Considering there've never been any GH tickets strictly dedicated to use-/test-cases, I'm gonna start adding non-GH-ticket links to the Refs report Description. The next Refs report will have a link to the test-cases spreadsheet. Lemme know if you have better ideas.
> 
Hrmm, that's an interesting conundrum there. I'm assuming that although these unreferenced scenarios are not explicitly detailed in any user story, their details are somehow derived from one or more user stories. Perhaps it would be prudent to reference the user story from which the derived scenarios originated?

> I'll run that last remaining DD - no 2FA test-case ([C772](https://dsvavsp.testrail.io/index.php?/cases/view/772))(multiple cross-browser/-device tests) once a test-acct's been found for it, then I'll generate final reports.
> 
Excellent! I'm aware that discovering appropriate test accounts can be very challenging at the moment.

**Comment by Samara-Strauss** [comment]
> I'll run that last remaining DD - no 2FA test-case (C772)(multiple cross-browser/-device tests) once a test-acct's been found for it, then I'll generate final reports.

Sounds good. If the SSO team can get DS Logon to work again on staging, we *should* be able to get a user for you, but if not, then we will not be able to provide a test user for this case.

**Comment by mshea0606** [comment]
@pjhill Here are the tickets/references related to the test cases you mentioned above. 

C776 | P2 - LOA3 - Dir. Dep. - Visibility - Incompetent w/o Fiduciary
C794 | P2 - LOA3 - Dir. Dep. - Visibility - Incompetent w/ Fiduciary
= Design - Hide Direct Deposit information if the user is incompetent or has a fiduciary #6094

C795 | P2 - LOA3 - Dir. Dep. - Visibility - Deceased
= [FE] Add direct deposit error for people who have fiduciary/are deceased #6090

C773 | P2 - LOA3 - Dir. Dep. - Visibility - DD-Ineligible
= [FE] Remove Direct Deposit on the Profile 2.0 if users are not eligible #8571

**Comment by tlei123** [comment]
> Here are the tickets/references related to the test cases you mentioned above.

Thx, @mshea0606 !

@pjhill , new Coverage for References report generated: https://dsvavsp.testrail.io/index.php?/reports/view/128

**Comment by pjhill** [comment]
> > Here are the tickets/references related to the test cases you mentioned above.
> 
> Thx, @mshea0606 !
> 
> @pjhill , new Coverage for References report generated: https://dsvavsp.testrail.io/index.php?/reports/view/128

Nice -- thanks everyone!
