### ISSUE TITLE
Content review of Debt Letters MVP COVID-19 alert 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#11935]
## Issue Description
I'm looking for a content review on an alert informing Veterans that VA debt collection has been put on hold for the rest of the year due to COVID-19 that is doing to be displayed in the Debt Letters tool. I've attached a screenshot of the alert, but you can also reference [the design in UXPin](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997?mode=i) to see how it looks within the tool's UI. [I referenced this VA blog post while writing the content.](https://www.blogs.va.gov/VAntage/77109/va-offers-debt-relief-veterans-years-end/) 

![Screen Shot 2020-08-03 at 2.09.31 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/ee9ed867-5f01-4faa-8ead-98a02ff5a328)

**Note:** The designs linked use the right rail component. We're going to be releasing a second iteration that replaces the right rail content with the 'on this page' anchor links. Just wanted to give ya a heads up in case you were wondering while reviewing the content :) 

Please feel free to edit this ticket to fit whatever format works best for you!

**Comment by peggygannon** [comment]
Hi, @rileyorr Where in the tool will this alert go?  there is a general COVID alert that will appear on the Debt Letters static landing page, so I'm trying to figure out how these two alerts will differ and if both are needed?

**Comment by rileyorr** [comment]
Hi @peggygannon! The alert will be at the top of the tool's page. You can see the alert's placement in [the UXPin prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/simulate/no-panels?mode=i). The general COVID alert that appears on the static landing page links to a FAQ containing questions relating to a lot of VA services like benefits, claims, debts, etc. whereas this alert is meant to notify the user that collection action has been put on hold due to COVID. Some users may come into the tool wondering why they haven't received any letters, so I think it's important to provide that context. 

I did find this verbiage in the FAQ, "As of April 3, 2020, we’ve taken action to stop collection on newly established Veteran debt and make it easier for Veterans to request extended repayment plans and address other needs during this time.". We could incorporate that into the alert and then link to the general FAQ if the user would like to learn more or they can call the DMC. What do you think?

**Comment by peggygannon** [comment]
Hi, @rileyorr Can we put a TBD on the COVID-related alerts for the Deb Management tool? These COVID alerts need to go through the Joint Task Force for approval. 

I'm working with Danielle Thierry to get JTF-approved language. Will keep you posted. 

cc @rebeccawalsh @leahkeeler @mattpointzxer0

**Comment by peggygannon** [comment]
hello,  @rileyorr I wanted to let you know that the JTF has not approved the Copay/collection alerts. So please do not use them in the Debt Management Tool. 

In my staging review feedback, I'll be suggesting we use the below debt-related general COVID alert in the tool:

![image.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/564e6dea-7da5-472e-bc5d-41ca395e44b6)

cc @mattpointzxer0 @leahkeeler @rebeccawalsh

**Comment by leahkeeler** [comment]
Thanks @peggygannon cc: @bradl3yC

**Comment by rileyorr** [comment]
Hi @peggygannon! Thank you for proving that feedback. Did the JTF provide a reason about why they'd like us to display a general COVID alert instead of telling Veterans that debt collection has been suspended due to the pandemic and linking to the coronavirus FAQs for more information?

**Comment by leahkeeler** [comment]
Hi @peggygannon We received substantial pushback from our stakeholders at the DMC over the proposed covid alert. Their position is it will confuse the veteran more than explain and will generate more calls to the contact center. What do we need to do to revisit the original alert?  Happy to jump on a quick call with @mattpointzxer0

**Comment by rileyorr** [comment]
Hey @peggygannon, I was looking at [the content review ticket for empty states](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11902) and I want to verify: is the JTF also saying we're not allowed to use [the COVID-related empty state](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/131174235/simulate/sitemap?mode=i)? We need to provide context for when Veteran receives a new debt after April 2020 and don't have any letters to download because the DMC isn't currently sending out any letters. Thanks in advance for your help!

**Comment by peggygannon** [comment]
hello! @leahkeeler @mattpointzxer0 @rileyorr I'm happy to get on a call to talk through. I realize an alert about the debt letters not being mailed out, but showing up on tool is needed. We can try to make this one more general and not tie it to "debt collection being suspended or on hold"

**Comment by rileyorr** [comment]
Hey, @peggygannon! I've received the revised COVID alert content and want to confirm that [this updated alert in the prototype](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/simulate/sitemap?mode=i) aligns with your feedback (also attached a screenshot below). 

<img width="678" alt="Screen Shot 2020-08-17 at 2 26 27 PM" src="https://user-images.githubusercontent.com/46329147/90430561-ac149380-e095-11ea-928a-d56f785108a6.png">

**The updated content**
This is a screenshot of the content I received for this alert; I was a little confused how the bottom 'Coronavirus FAQs: What Veterans need to know' portion fits in to the alert, or if it was just indicating where that link redirects to. LMK if anything I updated looks off. Thanks! 

<img width="647" alt="Screen Shot 2020-08-17 at 2 10 44 PM" src="https://user-images.githubusercontent.com/46329147/90430408-60fa8080-e095-11ea-9b8b-9821d74f08f1.png">

**Comment by peggygannon** [comment]
Hi, @rileyorr the alert looks good.  The bottom part should NOT be part of the alert "'Coronavirus FAQs: What Veterans need to know"  It just indicates where that link goes. 

This is the content for the alert: 

**VA debt collection is on hold due to the coronavirus**
We’ve taken action to stop collection on newly established Veteran debt and make it easier for Veterans to request extended repayment plans and address other financial needs during this time. 

You won’t receive any debt collection letters in the mail until after December 31, 2020.
For the latest information about managing VA debt, visit our [coronavirus FAQs].

**Comment by leahkeeler** [comment]
Hey y'll - can we close this ticket?

**Comment by rileyorr** [comment]
Yup!
