### ISSUE TITLE
STEM: Wizard content updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#11940]
Update STEM requirements content on Apply for Benefits wizard

**Comment by amyknox** [comment]
Replace STEM eligibility content on the How to apply page (1st image below) with the eligibility criteria in "Determine eligibility" on the STEM intro page (2nd image below)


[How to apply](https://staging.va.gov/education/how-to-apply/)
"![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/5ed39c66-6b54-441e-bc8c-59305d40044e)

[STEM Intro page](https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction) 
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/6d8ddde7-c1dd-4d15-8929-8577d34f7a2d)

**Comment by amyknox** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/apply-for-benefits-wizard-content-update.md
