### ISSUE TITLE
Design feedback - Staging Review [Profile 2.0]

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#11945]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**
- Please match the visual design of the  additional info components in the connected apps section to the others ones on the VA profile (the color of the font and the chevron need to be changed to the standard component: https://design.va.gov/components/additional-info) 

- [X] [Design] Update the visual design of the additional info components in the "connected apps" section to match others in the Profile #12044

**Try:**

- No “try” feedback at this time

**Consider:**

- No “consider” feedback at this time

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by tressaellen** [comment]
@emilywaggoner and @CrystabelReiter here is the updated mock for the additional info component. :)

<img width="849" alt="Screen Shot 2020-08-06 at 1 00 01 PM" src="https://user-images.githubusercontent.com/58752772/89571351-00855c80-d7d4-11ea-8051-d367c554fd50.png">

**Comment by mshea0606** [comment]
Thanks @tressaellen  cc @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Looks good to me! What is the priority level for this update? 

When we have that, @mshea0606 can you get a FE ticket created for this that also indicates priority level? I want to make sure we triage accordingly based on other tickets.

**Comment by tressaellen** [comment]
@Samara-Strauss this was already done on the FE (thanks to @sanlouise ). It was marked high priority and was tracked in [this ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12044)

**Comment by CrystabelReiter** [comment]
@tressaellen Awesome! thanks for the update. We'll close now :)!

**Comment by Samara-Strauss** [comment]
Ah, thanks, @tressaellen! Sorry I didn't make the connection on my own. Thanks for elevating this.
