### ISSUE TITLE
Review resource - Content practice area 

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1195]
Please review all resources in the [content practice area](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/Practice%20Areas/Content).

### Sections
- [README](#README)
- [ ] [Content ROE feedback and questions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Practice%20Areas/Content/content-ROE-insights.md)
- [ ] [Content writing and plain language best practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Practice%20Areas/Content/content-review-process.md)

<span id="readme"/>

#### README
- Onboarding/training
    - [ ] [Onboarding](https://github.com/department-of-veterans-affairs/vets.gov-team/wiki/VA.gov-Onboarding)
- Content processes
    - [ ] [Content Review process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Practice%20Areas/Content/content-review-process.md)
    - [ ] [VA content owner requests](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/guides/content-update-form-process.md)
    - [ ] [URL creation and process](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Information%20Architecture/URL%20Creation%20Process%20and%20Guidelines.md)
    - [ ] [Web content templates](https://github.com/department-of-veterans-affairs/vets.gov-content/tree/master/templates-and-guides/web-content-templates)
    - [ ] [Content process for modernizing VA forms](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/guides/content-VA-form-process.md)
- VA.gov content styleguide and strategy guides 
    - [ ] [VA.gov content styleguide](https://design.va.gov/content-style-guide/)
    - [ ] [WIP VA.gov consolidated styleguide](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/tree/master/src/_content-style-guide)
    - [ ] [Terms to lowercase (these aren't proper nouns)](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/list-of-terms-to-lowercase.md)
    - [ ] [Content strategy guide](https://github.com/department-of-veterans-affairs/vets.gov-content-style-guide/blob/master/Content-Strategy-Document/Table%20of%20Contents.md)
    - [ ] [Error messaging dictionary styleguide](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Design%20System/Guidelines/Error%20handling/Dictionary.md)
    - [ ] [Error message standardization styleguide](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Design%20System/Guidelines/Error%20handling/Content%20Style%20Guide.md)
    - [ ] [Form label masterlist](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/site-wide-issues/Form%20label%20masterlist.xlsx) 
- Content team checklists    
    - [ ] [Content launch checklist](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/checklists/new-content-launch.md)
    - [ ] [Writing/editing short UX text](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/checklists/rewrite-or-edit-short-UX-text.md)
    - [ ] [Copy edit checklist](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/checklists/copyedit-checklist.md)
    - [ ] [Proofreading/QA checklist](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/checklists/proofreading-QA-checklist.md)
    - [ ] [UAT process for content migration](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/checklists/UAT-process-for-content-migration.md)
- SEO resources
    - [ ] [Writing for SEO](https://design.va.gov/content-style-guide/seo)
    - [ ] [Meta and title tag guidelines](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/SEO-work/metas-and-title-tags-guidelines.md)
- GitHub resources
    - [ ] [Content process in Github](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/guides/GitHub_content_process.pdf)
    - [ ] [Mastering markdown](https://guides.github.com/features/mastering-markdown/)
    - [ ] [Github Markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- Drupal (CMS) resources

### Acceptance Criteria 
- [ ] Confidence with material covered in resource(s)
- [ ] Comment (on this ticket) with any questions or concerns

**Comment by ncksllvn** [comment]
@peggygannon I think some of these resources need to be updated before assigning to other content editors for reviewing. Do you know if these have been updated?

**Comment by peggygannon** [comment]
@ncksllvn Yes, thank you. I'm in the process of updating, based on a meeting with Jen last week. I should have updated list today.

**Comment by jenniferlee-dsva** [comment]
@peggygannon - I shared one more content onboarding doc with Nick - on content tiers. Sorry for the late addition.

**Comment by peggygannon** [comment]
@ncksllvn @jenniferlee-dsva OK, thank you. I've updated the content resources that are listed under the platform folder. They should be in parity with the content resources for the Global-UX team. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/README.md

![2019-09-05](https://user-images.githubusercontent.com/17554224/64370630-b4360900-cfd3-11e9-8f19-f26ccd31b188.png)
