### ISSUE TITLE
508-defect-2 [MOBILE DESIGN]: Relevant content provided on desktop MUST also be available on mobile

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#11969]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Relevant content **must** be available for all devices. The Helpful Links section is shown for viewports 768px and wider, but not available for smaller viewports. This is useful content regardless of the device used. 

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a mobile user, I want to to access the same resources and information available for laptop and desktop users.

## Environment

* Operating System: all
* Browser: all
* Server destination: production

## Steps to Recreate

1. Enter https://www.va.gov/education/yellow-ribbon-participating-schools/?state=AL in browser
2. Resize the browser to less than 768 pixels wide
3. Verify that the Helpful link content is not available

## Screenshots or Trace Logs

![Screen Shot 2020-08-03 at 4 59 51 PM](https://user-images.githubusercontent.com/57469/89226972-e0268980-d5aa-11ea-9988-27563c967fef.png)

**Comment by MarciMcGuireGCIO** [comment]
Moving to a consolidated 508 epic for Yellow Ribbon to clean up our backlog.

**Comment by zacharymorel** [comment]
Mobile:
![Screen Shot 2021-08-13 at 10 40 21 AM](https://user-images.githubusercontent.com/26075258/129387997-96da584c-0b6a-463d-99b7-fd7b82a2be46.png)

IPad: 
![Screen Shot 2021-08-13 at 10 40 06 AM](https://user-images.githubusercontent.com/26075258/129388000-a086488c-d9ce-4aad-84bd-4ad290fc93a2.png)

**Comment by joshkimux** [comment]
<img width="871" alt="Screen Shot 2021-08-13 at 1 21 11 PM" src="https://user-images.githubusercontent.com/14154792/129396441-01d7d94d-fb19-45b6-91eb-96c8365da566.png">

Great job as always @zacharymorel , you're a superstar 🥳 
Sidenote-- is there a reason the "Search Criteria" heading is repeated twice 👀

**Comment by zacharymorel** [comment]
Nope, that's a bug. We got a user story slated for this sprint to fix that duplicate listing.
