### ISSUE TITLE
Update wrong Korean DMZ date on spina bifida page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#1197]
The Korean DMZ date needs to be updated on this spina bifida page: https://www.va.gov/disability/eligibility/special-claims/birth-defects/   

This is factually incorrect and should be made now. It will then need to be made manually in Drupal as part of the post-CMS UAT epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1020#event-2562405819 

**Currently it shows:** 
"A unit in or near the Korean Demilitarized Zone for any length of time between April 1, 1968, and August 31, 1971”

**Change to:** 
"... between September 1, 1967, and August 31, 1971."

![image](https://user-images.githubusercontent.com/43381063/63527006-5501d000-c4ce-11e9-96aa-ac10685cb625.png)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?) https://github.com/department-of-veterans-affairs/va.gov-team/issues/1020#event-2562405819

- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
^ please let me know when it goes live, so I can inform stakeholders and ask them to retire their duplicate legacy content.

**Comment by AnneHurley** [comment]
Here's the updated sentence - but I'm not in Drupal yet alas, so Peggy, is this something you'd be able to change?

Correct:

* A unit in or near the Korean Demilitarized Zone for any length of time between September 1, 1967, and August 31, 1971

**Comment by AnneHurley** [comment]
@peggygannon @mnorthuis  @Karak888 @jenniferlee-dsva 
I wasn't able to tag you all earlier - the copy change in a complete sentence is above - I am happy to take a stab at making this update in GH so it goes live asap - but someone else should review it. Are any of you available? lmk and thanks.

**Comment by peggygannon** [comment]
@AnneHurley Yes, I can review it. Can you add me as reviewer on the Pull request? 

also, @jenniferlee-dsva @Karak888 I added this issue to the "post-content freeze drupal updates " epic.

**Comment by AnneHurley** [comment]
@peggygannon  

This is updated now in this branch: pages/disability/eligibility/special-claims/birth-defects.md

I named the branch dmz-date-update

**Comment by peggygannon** [comment]
@AnneHurley ok, thanks. did you create a Pull Request for this change or does that step still need to happen?

**Comment by AnneHurley** [comment]
OK thank you so much. Sorry for my confusion and thanks for doing this.
I'll move the issue along in its path, then.
[image: GovernmentCIO] <http://www.governmentcio.com/>
Anne Hurley
Content Writer
| *mobile* (503) 298-7203
| *e.* ahurley@governmentcio.com
*Government*CIO
website <https://www.governmentcio.com/> | media
<https://governmentciomedia.com/> | services
<https://www.governmentcio.com/services> | jobs
<https://careers-governmentcio.icims.com/> | map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>
[image: Twitter] <https://twitter.com/GovernmentCIO> [image: Facebook]
<https://www.facebook.com/GovernmentCIOMedia> [image: LinkedIn]
<https://www.linkedin.com/company/governmentcio> [image: YouTube]
<https://www.youtube.com/user/GovernmentCIO/videos> [image: Instagram]
<https://www.instagram.com/gciotalent>
*Confidentiality Note: * This email may contain confidential and/or private
information.
If you received this email in error please delete and notify sender.
