### ISSUE TITLE
VSP content feedback - Staging review - Profile 2.0 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#11972]
## User story

This ticket captures VSP content feedback on Profile 2.0 in staging 

Staging link:  
https://staging.va.gov/profile/

## Acceptance criteria

- [x]  VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [ ] Teams leaves comments about any feedback they decide not to take
- [ ] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
Profile 2.0 staging review



--------
Personal and contact information screens

1. Phone numbers: should be formatted xxx-xxx-xxxx, per VA.gov style. Not with parens

2. Sign-in email . this should have a hyphen in the below content: 
To view or update your **sign in** email, go to the website where you manage your account information.
Update **sign in** email address on ID.me

3. Please remove the 1- in DMDC phone number, per style guide
To reach the DMDC, call ~1-~800-538-9552,.

--------

Military information screens

The below military info message is missing information on how users can file a request. do they need to call or can they do this online?  Can we add this information to the message:

**We can’t access your military information**
We’re sorry. We can’t access your military service records. If you think you should be able to view your service information here, please file a request to change or correct your DD214 or other military records.

------

Direct deposit screens
1. This note below is missing the TTY before 711.  
Note: If you think you’ve been the victim of bank fraud, please call us at 800-827-1000 (711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. 


-----

Account security
1. Sign-in email  This should have a hyphen in the below content: 
To view or update your **sign in** email, go to the website where you manage your account information.
Update **sign in** email address on ID.me

2. We should be consistent in FAQ link. 
-On this page it says: [Go to VA.gov FAQs]
I recommend we change it TO: [link] Go to FAQs about signing in to VA.gov 
-On this page https://staging.va.gov/verify/
it says [Get answers to Frequently Asked Questions]
I recommend we change it TO: [Go to FAQs about signing in to VA.gov]

------

Connected apps
1. Make FAQ link language consistent: 
Under “Have more questions about connected apps?”
Change link: Visit our frequently asked questions.
TO: [link] [Go to FAQs about signing in to VA.gov] 

2. Under  “How do I connect a third-party app to my profile?”
Bold the names of the accounts: **DS Logon, My HealtheVet,** or **ID.me**.

3. Under this link: “What should I do if my records are wrong or out of date in a connected app?”
This sentence is missing content: If your information isn’t accurate: Call VA311 at 844-698-2311. If you have hearing 711. Or visit a VA health facility near you and ask a staff member for help.

Please update sentence to: If you have hearing loss, call 711

3. Under “If you’re getting an “unreadable data” message” : 
Please fix typo here: his means the This means the connected app has access to your information, but isn’t using it in its interface. It’s nothing to worry about. If you have questions about this, send feedback directly to the app.

Remove “his means the” as the beginning of the sentence.

**Comment by mshea0606** [comment]
need to confirm phone number format

**Comment by tressaellen** [comment]
Hi @peggygannon - here's some questions and feedback.

Military information

We ended up going away from including the DD214 messaging in the military information section in favor of a more generic message.  This is documented here:

- [Design ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7553)

- [Front end ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10246)  

<br />

Direct Deposit

I took this screenshot from staging - it seems like this copy is already correct. Am I missing something? Also Tze brought up that this might not be the correct number in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11489), could you verify that this is the correct number?
<img width="719" alt="Screen Shot 2020-08-06 at 9 42 25 AM" src="https://user-images.githubusercontent.com/58752772/89553289-c9a24d00-d7b9-11ea-8f53-5d917fda4114.png">

<br />

Connected Apps

>Could we make this an anchor link to take users directly to the connected app section of the sign-in FAQs?

@sanlouise could you answer this question?

>Also, are you working with Danielle and PW team on having the connect apps content updated on the FAQ page in time for Profile 2.0 launch date?

I will follow up with the connected apps team to see where we are on this. 

I also had a question about [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12037) - Mikki mentioned working with you on the FAQ language - but I believe you've already covered this in this content ticket. Is this correct?

**Comment by sanlouise** [comment]
@tressaellen

> Could we make this an anchor link to take users directly to the connected app section of the sign-in FAQs?
Yes, we can! I will add the anchor link as part of [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12037)

Per a conversation in `vsa-public-websites`, Danielle mentioned
> Connected apps FAQs are ready to go in draft (with one late-breaking update I'm going to make, but it's small). We're just waiting for the go-ahead to push to production when profile 2.0 launches.

**Comment by sanlouise** [comment]
@peggygannon For [this ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11489), are we just missing the `TTY:`, so the only content update would be `(TTY: 771)`? The rest of the phone numbers stay the same?

**Comment by peggygannon** [comment]
hello @tressaellen and @sanlouise here are some answers for you. Please let me know if I missed anything! 

1. thank you for the update about the military address message. Just want to confirm that staging will also be updated with this message: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7553

2. bank fraud note. are you asking the the 800 number or the TTY number? I left a comment in this ticket about the TTY number... (https://github.com/department-of-veterans-affairs/va.gov-team/issues/11489)

the PW dev did a sweep of TTY numbers recently and updated them all to 711. 

Also, did this Note come from somewhere else on VA.gov? I  know this note has been on the pages, but I don't recall writing it, so please let me know where this info originally came from.

3. and yes, we're missing the TTY ahead of 711, so it should be TTY: 711





3.
