### ISSUE TITLE
[Bug] Profile 2.0 - Account Security - T&C text not wrapping in IE11

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#11971]
## What happened?
In Internet Explorer 11, on Staging Profile page  > Account Security section, the Term & conditions right-column text ran beyond column-border without wrapping.

## Specs:
- Device: Windows PC
- Browser: IE11
- Test User: ```vets.gov.user+36@gmail.com``` (Wesley)

## Steps to Reproduce
1. In IE11, go to https://staging.va.gov/profile/account-security \[sign-in as ```vets.gov.user+36@gmail.com``` (Wesley)]
1. In main-content, **Terms & conditions** row, in righthand-side column, observe that the text runs off beyond the column-border, without wrapping.

**IE11 screenshot**
![p2-bug-acct-sec-t c-text-run-on-ie11](https://user-images.githubusercontent.com/587583/89232313-085abc00-d59c-11ea-8b2b-8a2ceb363b26.png)

## Desired behavior
Text wraps to new line, remaining with the column.

## Acceptance Criteria
\[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mshea0606** [comment]
@sanlouise looks good!
