### ISSUE TITLE
x-csrf-token shouldn't be sent in GET requests

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#11976]
Issue in title. Using non-standard HTTP headers causes the browser to send an `OPTIONS` round-trip first.

With `x-csrf-token` included, `GET api.va.gov/v0/feature_toggles` now takes _two_ requests, because we have to do an `OPTIONS` round-trip before we can initiate a `GET`. This adds some avoidable user latency.

I noticed it on the `feature_toggles` requests, but we should check to see if we're doing this elsewhere we shouldn't be.

CSRF Token shouldn't be enforced on `GET` requests anyways, and `csrf_request_spec.rb` seems to confirm this.

For further reference, see MDN's docs on ["simple requests"](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests) for guidance on when `OPTIONS` are skipped.

**Comment by gunsch** [comment]
On a little more looking, we're definitely doing this on a lot more than `/v0/feature_toggles`.

![image](https://user-images.githubusercontent.com/769353/89262077-fbfa5180-d5e3-11ea-9d11-4201fcce7f21.png)

**Comment by jholton** [comment]
Interesting.
It's not just the CSRF token header though.

![image](https://user-images.githubusercontent.com/733873/89302542-f5e29000-d638-11ea-9741-9f687ff81bfb.png)

The CSRF token header can definitely be excluded from `GET` requests.
I haven't worked with the others though, so I'm not sure of their importance in `GET` requests.

**Comment by patrickvinograd** [comment]
Ref https://github.com/department-of-veterans-affairs/va.gov-team/issues/2715
and https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9358

**Comment by jholton** [comment]
Relevant Slack convo about the use of the `x-key-inflection` header: [link](https://dsva.slack.com/archives/CQHBJ5U06/p1596555621450600)

**Comment by gunsch** [comment]
Ooh, thanks for calling out other headers. When I first noticed this on `/v0/feature_toggles`, that one _only_ has `x-csrf-token`, so that case should be easily fixable.

`x-key-inflection` seems like we're already trying to eliminate it.

If we wanted to get serious about removing OPTIONS across the site, one option could be to move those things into query parameters. i.e. change `source-app-name` header to a "srcApp" query parameter.

I see Rian said in Slack he doesn't see this as a high priority to fix performance-wise. I'm fine with his judgment on this. But I do think we should fix the `x-csrf-token` case at least and leave a ticket open to revisit the OPTIONS requests across the board at some point in the future.

**Comment by holdenhinkle** [comment]
Look into whether we're requiring x-csrf-token on GET requests.
