### ISSUE TITLE
user is auto logged out if immediately redirected after login

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#11973]
If the user needs to be immediately redirected to another page after login, they could be auto logged out after doing so.

The call to `/keepalive` will return an empty response if a network error occurs, this is possible if the user is redirected to a new page before the XHR response is returned http://sentry.vfs.va.gov/vets-gov/website-staging/issues/108541

In this case the `transactionid` will be undefined and [won't match the value the user logged in with](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/sso/index.js#L47).

**Comment by ericbuckley** [comment]
I just ran a test on production and the fix worked as expected.

```
- as an unauthenticated user I opened up https://www.va.gov/track-claims/
- I was redirected to https://www.va.gov/?next=%2Ftrack-claims
- I clicked on the "Sign in with ID.me" button and completed the authentication process
- after successfully authenticating, I was redirected back to https://www.va.gov/track-claims/your-claims and stayed logged in
```

**Comment by patrickvinograd** [comment]
I validated that this is fixed in production after today's deploy went out. I went to https://www.va.gov/track-claims,  sign-in modal popped up, I authenticated through SSOe,and landed back at the claims app and was not subsequently logged out.
