### ISSUE TITLE
Set upper limit of 395 days for preferred date

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#11985]
We only allow 395 days out for direct scheduling, but we allow the preferred date to be any future date. Which should put an upper limit on this date.

From Marcy:

```
This is an inconsistency I found in the app.   

VAOS only allows user to direct schedule T+395 days.

This calendar allows the user to enter any date when it should restrict entries to T+395 days. 

If you can’t schedule out past 395 days then you shouldn’t be able to enter any date you want. I can enter any M/D/Y combination I want. 
```

**Comment by jenniemc** [comment]
Hi @rtwell , could use your help providing the language/flow to inform users they are limited from making a direct appointment beyond 395 days (or 13 months) into the future. Currently, if they enter a date say 14 months from now, it would send the them to a calendar with no available date to select. 
<img width="568" alt="Screen Shot 2020-08-12 at 8 12 02 AM" src="https://user-images.githubusercontent.com/54327023/90013703-ca345b00-dc73-11ea-8346-2cfe061727be.png">

**Comment by jbalboni** [comment]
@jenniemc Typically we do this as a validation error message that says something like "You must choose a date less 395 days in the future." @rtwell and @peggygannon can come up with the exact wording and maybe if there should be extra explanatory text on the page, but the validation error is the main thing.

**Comment by lenaecb** [comment]
@jenniemc - Chatted with @peggygannon about this. She'll add some language for us to use with this fix. Thanks!

**Comment by peggygannon** [comment]
@jbalboni @jenniemc Hello on our content sync today, we discussed this option below:  

What is the earliest date you'd like to be seen? (*Required)
Please pick a date within the next 13 months.

Month Date Year

{Validation error} Please enter a date less than 395 days in the future
