### ISSUE TITLE
Create transformer for node-office

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#11996]
## Issue Description
Create the following for the `node-office` bundle:

- Input schema
- Transformer
- Output schema

**Comment by cvalarida** [comment]
**Note:** The schemas and transformer already exist for this one, but they're incomplete. I believe we stubbed them out to bypass a circular reference issue a while back.

**Comment by jhonnyoddball** [comment]
Done!
