### ISSUE TITLE
Audit vets.gov-team repo to identify content that must remain private

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#120]
## Description
As we look to move the content from `vets.gov-team` (a private repo) to `va.gov-team` (a public repo) we need to identify which content needs to remain private.

#### Items to consider
- keys and credentials
- contact information
- veteran information (research)
- internal policies
- more...

## AC 
- [x] A list of directories/files of items that needs to remain private has been compiled
- [ ] The list has been reviewed by DSVA leadership 
- [ ] A plan is established and documented for how we'll maintain private information in the long term.

## Def of Done
- [ ] Connected to an Epic
- [ ] AC is complete

**Comment by smoonpeyes** [comment]
@emilywaggoner The work of [identifying the types of content that should be private](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive) appears to be complete.

I'm auditing the vets.gov-team repo to identify which items need to be moved or removed before migrating to va.gov-team. Does that sound like the right direction for this ticket?

**Comment by smoonpeyes** [comment]
The audit is ongoing here: https://docs.google.com/spreadsheets/d/1xhsyME4caITSbJiAxHFjSDVn7HlfzkHuVu3mvch-Ox4/edit?usp=sharing

**Comment by andreahewitt-odd** [comment]
https://docs.google.com/spreadsheets/d/1waFEAra9aeXK4UFp-ODMbCcKC4MHDZCFel8Oahb2X1E/edit?usp=sharing
