### ISSUE TITLE
Better handling of entering bad email addresses

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12004]
When entering an email address with an invalid TLD, the server handles it correctly and provides proper errors, but we only show a generic error message to the user. We could either improve the form field validation to prevent submitting this in the first place. Or we could show a more specific error message to the user.

Response from `POST profile/email_addresses`:
```
{
  "errors": [
    {
      "title": "Check Email Address",
      "detail": "Email address cannot have 2 @ symbols, must have at least one period '.' after the @ character, and cannot have '.%' or '%.' or '%..%' or \" ( ) , : ; < > @ [ ] or space unless in a quoted string in the local part.",
      "code": "VET360_EMAIL305",
      "source": "Vet360::ContactInformation::Service",
      "status": "400"
    }
  ]
}
```

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/d06c5f71-4bc0-4175-9d69-cc050989bce8)

**Comment by sanlouise** [comment]
@peggygannon After talking with @tressaellen , we decided to go with the AlertBox route with helpful text for the user. The current copy does not make clear that the request could not be processed due to an invalid email address. Could you provide us with copy that makes it clear that their email address is invalid so we could not submit the request?

**Comment by peggygannon** [comment]
Hi, @sanlouise would this error message work for this scenario? 

**We couldn't update your email address** 
It looks like the email you entered isn’t valid. Please enter your email address again.

**Comment by sanlouise** [comment]
@peggygannon That works! Thank you so much! 😄

**Comment by mshea0606** [comment]
looks good @sanlouise !
