### ISSUE TITLE
Profile delete confirmation alert bug

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12002]
When confirming the deletion of a profile contact info field, the Confirm button should remain a spinner while the polling of the transaction status is still happening. Instead the Confirm button is re-enabled after the initial transaction is created. This allows you to hit the button again leading to weird behavior.

The "cancel" button should also be removed when the Confirm button is showing a spinner.

![delete-confirm-button.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/afce3f79-8740-43a0-912b-506587b9ac46)

**Comment by erikphansen** [comment]
@mshea0606 can you confirm that this bug does not happen anymore?

**Comment by mshea0606** [comment]
@erikphansen that issue no longer occurs, good catch!
