### ISSUE TITLE
Delete confirmation alert should scroll into view

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12013]
We should use the `scrollOnShow` with `scrollPosition="end"` props on the 'are you sure?' Alert that shows up when starting to delete some contact info. On small screens the Alert will show up but have a lot of its content fall below the fold.

https://github.com/department-of-veterans-affairs/vets-website/blob/deec9141649736b09b6fa833f85004c10a6a6e5a/src/platform/user/profile/vet360/components/base/Vet360EditModalActionButtons.jsx#L109-L118

In this GIF I have to manually scroll to show the entire Alert that appears.
![delete confirm.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/8625daa4-54c7-41c0-8781-a2e1cf3bb043)

**Comment by sanlouise** [comment]
@erikphansen 

In your example, the Alert is already partially in the viewport so adding `scrollOnShow` will not trigger a scroll.

```
const isInView = window.scrollY <= this._ref.offsetTop;

    if (this._ref && !isInView) {
      this._ref.scrollIntoView({
        block: this.props.scrollPosition,
        behavior: 'smooth',
      });
    }
```

Do you suggest we should update the Alert component to instead check for a certain percentage visibility in the viewport to trigger scroll (i.e. 20%), versus none at all? I am not sure what the best way would be to go about doing this, but that might work.

**Comment by erikphansen** [comment]
Oh that totally makes sense. I like your approach. Alternatively there could be another prop that overrides that check thats happening that's preventing the scrolling.
