### ISSUE TITLE
[Bug] Profile 2.0: After saving direct deposit info, the page doesn't scroll back up to the top to show the newly saved info

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12019]
## Overview

- Device: iPhone Xs
- iOS version: 13.5.1
- Brower: Safari

**Issue**

On mobile, when I saved direct deposit, the screen did not scroll back up to the top to show the save confirmation/newly saved direct deposit info. When I clicked save, this was the screen I saw after saving had completed and the form had closed:

![IMG_1286.PNG](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/9fa373d8-e09c-4d7c-aa58-8f917098ae7c)

This is **medium** priority. Desired functionality — we should scroll back up to the direct deposit heading so people can see the saved confirmation and newly saved info.

## Tasks

- [ ] Fix scrolling issue with direct deposit: Once the new info is saved, we should scroll back up to the direct deposit heading so people can see the saved confirmation and newly saved info.

**Comment by erikphansen** [comment]
I think the fix we implement for this might be worth adding to all Profile fields. Scroll the just-edited field to the top of the viewport. I suspect exiting address edit view in particular might not be great on mobile.

**Comment by erikphansen** [comment]
It is safe to ignore my comment above. I confirmed that when you exit edit mode the field you were editing is always in the viewport. This is because we manage the focus when leaving edit mode, placing focus back on the `Edit` button. The act of programmatically focusing on the `Edit` button will move the `Edit` button to the center of the viewport if it is not already in the viewport. At least in Chrome.

**Comment by Samara-Strauss** [comment]
Confirmed the fix! Looks great now on iPhone in Safari.

**Comment by mshea0606** [comment]
@erikphansen can you please add an estimate to this? Thanks!

**Comment by erikphansen** [comment]
@sanlouise is the one who did it. And did it quickly so I'm putting a 1 on it.
