### ISSUE TITLE
[FE] Profile 2.0: Inconsistent "cancel" button styling

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12010]
In the Profile we usually use a text-link style for the Cancel button. But on the address validation screen we use a button that actually looks like a button. We should settle on one style. 

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/23707cfc-71ee-48d1-b69a-9968f50a919a)
![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/37f52fa6-b019-4203-b8c5-f2ae77070165)

**Comment by mshea0606** [comment]
Hey @tressaellen  can you add an estimate to this? Thanks!

**Comment by Samara-Strauss** [comment]
@mshea0606 is this on the schedule for this sprint? Looks like Sandra needs some design help before she can work on #12014

**Comment by tressaellen** [comment]
We should update all of the links to buttons for 'Cancel'. It's much more user friendly from a mobile perspective especially. 

![Screen Shot 2020-08-17 at 12.16.58 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/63be7c81-ee15-451f-b6a3-3e3277c31104)

**Comment by tressaellen** [comment]
And here's a screenshot with the delete button as well. 

![Screen Shot 2020-08-17 at 12.54.10 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/6ac2dec2-ed90-40c7-900e-28d86ec07f7a)
