### ISSUE TITLE
[FE] In mobile account security, Terms and Conditions and Sign-in Email overlap

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#12018]
![IMG_5350.PNG](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/95e15252-3e5c-4026-b0d8-b35346823d95)

**Comment by erikphansen** [comment]
@sanlouise Any chance this is a side effect of the IE11 flexbox fix you made? This reminds me of flexbox issues I had four years ago.

**Comment by sanlouise** [comment]
After looking into this, it's definitely related. I'll assign the ticket to myself to get it fixed 👍
