### ISSUE TITLE
[Bug] Profile 2.0: Weird alignment of Delete button in Phone number field on mobile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12014]
## Overview

- Device: iPhone Xs
- iOS version: 13.5.1
- Brower: Safari

**Issue**

The Delete link is not aligned with the Cancel link. These should be on the same line.

This is **low** priority.

![IMG_1284.PNG](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/0ea2e73e-bca9-4195-80f2-7e1f5c323f02)

## Task

- [ ] Fix alignment of the Delete link.

**Comment by sanlouise** [comment]
I will hold off on working on this ticket till [this ticket from design](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12010) is resolved, then I'll know whether to change the Close link to a button or update the Close link styles.

**Comment by tressaellen** [comment]
Hi @sanlouise - here's an updated screenshot for you. We'll change all of the links for 'Cancel' to buttons. 

<img width="657" alt="Screen Shot 2020-08-17 at 12 54 10 PM" src="https://user-images.githubusercontent.com/58752772/90433413-41089400-e078-11ea-9b2b-2b61b35fd93e.png">

**Comment by sanlouise** [comment]
Create [this FE ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12565)

**Comment by sanlouise** [comment]
@mshea0606 Since we'll be changing the links to buttons, we should close this ticket. The styling will be resolved in [this ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12565)

**Comment by sshein** [comment]
testing something
