### ISSUE TITLE
Add field into search results indicating  whether a form has a detail page

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#12027]
Find Forms search has launched and we're now looking at launching the form detail pages. As part of integrating the search with the detail pages, we need search results to dynamically link to each form's detail page. However, not every form will have a detail page, and to start, very few will. For example, if we publish only one form detail page, then when that form is shown in search results, we should link to the detail page, but the other forms should continue to not link anywhere (except the PDF download).

This means that we need a new field in the form search results to indicate that a form has a published form detail page so that the frontend knows whether to link to it or not. We will need to do this by -

## Tasks
1. Write the new field in a GraphQL query
1. Pass this query over to the Lighthouse team to implement
1. Once implemented in the Lighthouse layer and promoted, we're ready for https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453. 

## Acceptance Criteria
* At the end of ALL of this, the API will indicate form detail metadata/url for each VA form
* the FE search results will not be updated yet (that's in #11453)

**Comment by ncksllvn** [comment]
Hm, so, this ended up being way easier than I thought. I don't know what I was expecting lol. 

Example query -

```graphql
{
  nodeQuery(limit: 10, offset: 0, filter: {conditions: [{field: "type", value: ["va_form"]}]}) {
    entities {
      ... on NodePage {
        fieldRelatedLinks {
          entity {
            parentFieldName
          }
        }
      }
      ...vaForm
    }
  }
}

fragment vaForm on NodeVaForm {
  entityBundle
  entityId
  entityPublished
  title
  entityUrl {
    ... on EntityCanonicalUrl {
      breadcrumb {
        url {
          path
          routed
        }
        text
      }
      path
    }
  }
}
```

I think what we could do here is add a new field to the form model called `form_detail_url` or something like that. The logic would that if `entityPublished` is true, then `form_detail_url` is set to `entityUrl.breadcrumb.path`. Otherwise, it is `null`.

This way when a search is performed on `/find-forms/`, we'll be able to show links to the form detail pages for each form in search results that has a published form detail page.

**Comment by MickinSahni** [comment]
> Hm, so, this ended up being way easier than I thought. I don't know what I was expecting lol.

Think we should add to this sprint, @ncksllvn?

**Comment by ncksllvn** [comment]
I think we can add it @MickinSahni 

If we want to, we can broaden this ticket to be "Implement links to form detail pages from form search results (for forms with published detail pages)". Then we can do the other items listed on https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453

**Comment by MickinSahni** [comment]
> I think we can add it @MickinSahni
> 
> If we want to, we can broaden this ticket to be "Implement links to form detail pages from form search results (for forms with published detail pages)". Then we can do the other items listed on #11453

I'd rather not broaden. But, would it be behind a flag since we need to get detail pages out first? Also, there's going to be lag-time in order for Lighthouse to make the necessary changes. 

Another reason is #11453 is a well-packaged release of new features/functions we can ship together. Not to mention, we have to string up analytics on new CTAs. @ncksllvn

**Comment by MickinSahni** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/13204473/90658202-451be980-e211-11ea-8f65-23ac0ef8c133.png">
