### ISSUE TITLE
[FE] FAQ dropdown spacing in Personal and Contact Information is cramped

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#12022]
Super minor issue - There should be more spacing between each line of the ‘How do I update my personal information’ dropdown. It all feels very cramped.

![IMG_5353.PNG](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/9777fe28-5b60-489c-9a8d-786d46affd20)

**Comment by mshea0606** [comment]
looks good @sanlouise !
