### ISSUE TITLE
[FE] Checked/unchecked U.S. Military base address bug

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#12021]
In mobile if a user is editing the mailing address in Personal and Contact information there is a small bug when checking/unchecking the US military base box. 

To recreate:

- Check 'I live on a United States military base outside of the country.'
- Start editing form
- Uncheck 'I live on a United States military base outside of the country.'
- Entries from the previous form stay in the form, but in the wrong boxes (i.e. APO/FPO/DPO shows up in the city box - city box should be clear) 

![IMG_5351.PNG](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b59c3e02-601f-40fc-bb8d-6e35b9b48450)

**Comment by erikphansen** [comment]
Hmm I think this may be done on purpose. Technically APO is a city. And AE is a state. As far as USPS is concerned. But we could add logic to wipe out the city and state when clicking that checkbox.

**Comment by tressaellen** [comment]
@erikphansen oooh interesting, I did not know that. In that case it's probably fine, it's not really a hassle to change from a user perspective if you end up unchecking the box. I'll go ahead and close this and we can re-address this if there is any confusion in the future.

**Comment by erikphansen** [comment]
I it works the opposite way, too, which is nice. If you enter FPO as the city and then click the checkbox, FPO is selected in the drop down.

**Comment by mshea0606** [comment]
@erikphansen  can you add an estimate to this? Thanks!

**Comment by erikphansen** [comment]
@mshea0606 it's closed/it works as intended.
