### ISSUE TITLE
[IA] [FE] - Update FAQ link labeling

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12037]
## Background 
See Ticket: [Design] - Update FAQ link labeling #12035 

---> From Ticket: IA feedback - Staging review - Profile 2.0 #11968
There is a link to /sign-in-faqs on the account security and connected apps pages, but the links are labeled very differently and sort of seem to refer to very broad "va.gov faqs". I recommend working with Peggy on this to label these faqs consistently, potentially link to an anchor on the page for specific faqs, and ensure they they are represented as faqs specific to authentication and not just general faqs

## Tasks
- [ ] Update FAQ links

**Comment by sanlouise** [comment]
@DanielleThierryUSDSVA Could you please provide the anchor link to the connected apps section in the FAQs whenever you have a moment? Thank you!
