### ISSUE TITLE
v1/v2 migration documentation

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1204]
@djmunoz1 commented on [Fri Mar 29 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17675)

##
We need to document our learnings from v1/v2 so that when this is  encountered again, we or other teams can leverage our knowledge.

## Acceptance Criteria
- [ ] v1/v2 Process is documented and stored in GH

## Def of Done
- [ ] issue is connected to Epic
- [ ] All AC met

**Comment by luke-gcio** [comment]
Not even sure what this is, closing.
