### ISSUE TITLE
[Frontend]- Apply Wizards- 5490

### ISSUE THREAD

**Issue by mr0sari0** [department-of-veterans-affairs/va.gov-team#12052]
## User story

As a Veteran applying for education benefits, I want to have an education benefits wizard on the 5490 introduction page so that my experience of starting an online application is more seamless.

## Unknowns

Platform's involvement may cause delays or extra work.

## Tasks

- Transfer code from the education benefit wizard to the 5490 form introduction page 
- Create and setup logic for `sessionStorage`
- Create unit test for the user story
- Sync up with @johnhashva and @andaleliz for approval

##  Definition of done
Taken from #9665 

The how to apply wizard is live in production across the identified page, resulting in reduced Wizard bounce rates.

## Acceptance criteria

A user with no session cookie should see the wizard when arriving at the 5490 introduction page and the introduction page content should be hidden.

If the appropriate questions are answered, the wizard should be hidden and the introduction page content should be displayed.

If the appropriate questions are answered, an apply button should be displayed at the bottom of the page, with a link to the most appropriate education benefit form

**Comment by leahkeeler** [comment]
Can this be closed out

**Comment by johnhashva** [comment]
I have actually not had an opportunity (nor has @andaleliz I think) to review this build on staging for approval.  Should we do that now, or wait until any final changes are implemented as a result of the Platform reviews?

**Comment by leahkeeler** [comment]
@johnhashva Hang on until analytics and content reviews :)

**Comment by leahkeeler** [comment]
closing per new requirements
