### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by zachgoldfine44** [department-of-veterans-affairs/va.gov-team#12065]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

- Thanks. I have a google account attached to VA email account, so I believe I'm good to go!

## Access Requirements
n/a

## Date Required
As soon as is convenient - no rush!

## Product Team / External Team / VA Office
CTO Office - Benefits team

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @zachgoldfine44 , 

Thank you for your patience on this request. You should have received an email notification indicating you now have been provisioned Google Analytics access through your va.gov email. 

Let us know any further questions you may have!
