### ISSUE TITLE
Enter sample LC content in CMS, so FE engineers have something to test FE template work

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#12066]
### Acceptance criteria
- We need to enter sample learning center content into 3 learning center CMS templates that are currently in progress. 
- The sample text is needed so the FE engineers can start building the FE template and connecting to the CMS LC content fields and test that the FE mapping is working. 

**Sample WIP learning center content:** 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-copy/for-prototype-test

**The 3 CMS templates are:**

- Single Q/A 
- Multiple Q/A
- Step-by-step

`Note: The CMS templates currently don't include the sandwich bread layers:`
```
- Tags taxonomy
- Need more help
- Was this useful
- Related info/articles
```

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva I think this could be a content team member task this sprint. Where are the templates/who on the CMS team should Randi work with on how to get this done?

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO -   We will be adding content in prod.cms. I don't see a way to filter Learning Center content but you will be able to find the specific LC templates in the massive dropdown list located on the content dashboard.   @oksana-c / @swirtSJW in the LC slack channel will be able to provide more details.

Screenshot:
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/f75d745b-edd7-40b9-a726-48747718fd52)

Here is the CMS team's related ticket to create the dev environment: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2561

**Comment by jenniferlee-dsva** [comment]
@oksana-c - will there be a COPE FAQs library for the content team to add the individual Q/A's (end state) or should they just be adding the WIP test content for now directly into the FAQs template page?

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva Thanks for the screen shots and explanation.

@RLHecht Let's talk about this work.

**Comment by oksana-c** [comment]
@jenniferlee-dsva , dedicated COPE FAQ UI is not a part of a LC MVP.

in the meantime, the content team can add single "Q&A" and "FAQ - multiple Q&As" pages straight from the available Content Types list - https://prod.cms.va.gov/node/add 

The process of entering Q&A content should begin with creating single Q&A pages. Then, if you need to compose a page with a collection of Q&As as shown on the LC mockup, simply create a "FAQ - multiple Q&As" page, which will allow you to connect existing single Q&A pages into a cohesive list. 

also, here's quick links to Q&A forms for your convenience:
* https://prod.cms.va.gov/node/add/q_a -  add single "Q&A"
* https://prod.cms.va.gov/node/add/faq_multiple_q_a - add "FAQ - multiple Q&As"

**Comment by oksana-c** [comment]
Checklist content type is available for test data entry - https://prod.cms.va.gov/node/add/checklist

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO @RLHecht cc @MickinSahni - let's focus on the content types in the og ticket. I'll create another ticket for tacking Checklist (and other content types that the CMS team complete) for the next sprint. 

Thx so much for the ^ info @oksana-c

**Comment by RLHecht** [comment]
I've entered the content for the step by step, multiple Q&A, and single Q&A. I couldn't put in the in-page alert, which I already mentioned to Oksana. 

Step-by-step: prod.cms.va.gov/node/6899
Multiple Q&A: prod.cms.va.gov/node/6898 
Single Q&A (there are a lot but, here's one): prod.cms.va.gov/node/6897

FYSA @jenniferlee-dsva @bethpottsVADEPO @oksana-c

**Comment by RLHecht** [comment]
This work has been completed. Closing ticket.

**Comment by RLHecht** [comment]
@jenniferlee-dsva @oksana-c I've added a reusable alert to the three nodes listed above as well. Closing this ticket again. FYSA @MickinSahni
