### ISSUE TITLE
Access for Braden Shipley

### ISSUE THREAD

**Issue by bradenshipley** [department-of-veterans-affairs/va.gov-team#12073]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Braden Shipley
- Please Provide your email.
   > braden.shipley@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > End User XP, Node Engineer, Oddball

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0d+pyXxHuE8ef8Xf2LB9+TdX3W5GP388urH0CsaPR8qNIZsuHy1U2MompaH0zDoJ8CTiYkT1wlvjuPUJvDtu2nv/uL//TSn+fEI11hB6Mmdr4/td239VweLF+HtS/cj50vus88hfxf9JV0WGE97rY9pCBOesig6HZoplyFL4EN9nxiy+y3QWPl0PFsFoCwsqeu38NsD4PSV01yRUqh+xSTQjaol2hGJpZP/U0/T9Yb0Bvx9lQnuWywg4arL+5Jt6V5sEk0s1S5+Yvf+f22zALkic8Z2djPP6mcmUyrPYtmgkEhSaOfbyGHWLz5X7vghmxz7C2r+Iv7XEMDZtEHQ21bsKtw+QMjRp1Hh6OoSf1Xfd77ECZxx+lCD09DG6Qblf7GtAugY1kSIzN6m1Y4gwQIIr8aMj078yts9TU0fpXD3foJxRAQNEDlHtVZmvTeuH2qs1VBrtqBuX3c9uExXbwdtlKWWEV5X/BLY3VmNVLYUpXCj0hZvznz/L9aDmvDwx0oKYzhxjGH88O53uFeFM4PkJU4ciNnIPUDp66GWfD3NfrU0Tha3YCh38u1gGVO3iDIq0AAb+jj3/9oAC7fRo6mdBLOnRYPqmmpYI0I8wm1PaqlFgxcjNaygm9gReae5eOMDzeEpDwEDZhJFWHEBzPDT/kyUbsyqqK3swl82TWNQ== bradenrshipley@gmail.com

```

- Grant AWS Console access?
  > YES 
  - Please give a brief description for why you are requesting AWS access.
Will be working with a variety of teams and am expecting to need AWS access regularly.

**Comment by bradenshipley** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
Name: Braden Shipley
COR: Crystal Moultrie

**Comment by tskinn** [comment]
@bradenshipley you should be able to connect to the socks proxy. Reach out if you have any issues.

**Comment by jsev-io** [comment]
AWS Access granted as part of recent lighthouse onboarding.
