### ISSUE TITLE
Add reverseFieldListingNode to node-story_listing

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#12072]
## Issue Description
The `node-story_listing` bundle needs `reverseFieldListingNode`. The GraphQL sub-query can be found [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/storyListingPage.graphql.js#L11).

---
## Tasks
- [ ] Add the `reverseFieldListingNode` to the `node-story_listing`

**Comment by theodur** [comment]
Merged in https://github.com/department-of-veterans-affairs/vets-website/pull/13772.
