### ISSUE TITLE
Create a Google Analytics event to track backend failures

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#12089]
**Description**
We have GA events for Form 10-10cg `attempt`, `success`, and `failed`. We want to add an event that specifies a failure because of qualification: when we block an application from being submitted because the veteran applying was not qualified.

For security reasons we don't notify the front-end for the reason the application failed. Qualification errors look like Backend Service Outage errors to the front end

So we'll need to fire the `*_failed_qualifications` event from the API.

**Summary**
In `CaregiversAssistanceController` you can see where the qualification error is being `rescued_from` and being converted to a Backend Service Outage. That is where we want to fire the event to GA.

This will require making a GA HTTP Client Service. This will also require parameters from the end-user / request headers: their google client ID (a.k.a. "cid" - the uniuqe identifier for this GA user).

There are many parameters that need to be defined on the event you fire (which is just an ga endpoint with query parameters). Contact me (@kevinmirc) or @jonwehausen for these parameters.

**User Story**
Given that we want to be able to track the root cause of submission failures in Google Analytics, I want to add a GA event on the backend, so that we can use the dashboard to understand why submissions are failing.

**Comment by lihanli** [comment]
@kevinmirc how is the frontend going to send the google client id?

**Comment by kevinmirc** [comment]
We have not planned or scoped that out.

In my opinion, we should just look for an additional header (i.e. `X-Google-Client-ID`). Does that work for you guys @LinnJS @lihanli ?

**Comment by lihanli** [comment]
that works for me

**Comment by lihanli** [comment]
based on [this conversation](https://dsva.slack.com/archives/CBU0KDSB1/p1600796719217400), we need to add two more issues to complete this issue
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13856
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13855
