### ISSUE TITLE
Add additional PR checks with dangerbot

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#12081]
## Overview

Danger bot is a module that can be run in CI to check for things that linters can't check such as PR size and documentation updates.

Dangerbot [documentation](https://danger.systems/js/)

**Comment by timwright12** [comment]
Looked into the docs for this. It looks nice, but people also already complain about the noise in their PRs. This seems like a "maybe if we can figure out real value"

**Comment by oseasmoran73** [comment]
With Github Actions being transitioned we already have linting notification being displayed directly on the PR. Much like Tim mentioned above, unless there is value, seems like bit more noise
