### ISSUE TITLE
Access for Steve Novosel

### ISSUE THREAD

**Issue by stephennovosel** [department-of-veterans-affairs/va.gov-team#12087]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Steve Novosel
- Please Provide your email.
   > steve.novosel@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse API team

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCu2G7cryUl/WeLMkYF8XDdDEOVrnX+ffWu55p4Y2fMPvm7WEDMrm2M8qWL4Ti8Z1Vpxx+6GDZk+62Eulb0e5bK3/NPWvupI7B9YLwuXoL3WHEPL2bPhe6Ua2Idapp7kFPB3Qa9BZxuAJXicB4kfCOXdPuGJLD/uaxj5CtWlD6u5+Iov6vEiLd4N2XxIaj2zGck753aZXYAZB40bCShIhrDKy/BvKF0A5zZPR4RUmtAz6NHhMLUr2GBJqkwjJuo6Wztgn9s0ZbNEqY06wJAIZrb4E7wAtoTSrKj4dXNJeGcGx55B6EMWIOQpoWi04j08RAz93tYkV5pIJ3wIJpsZ6+JASKGJlm4XVUgsaFyr1HkLarOEv1dkeXNYcp46zK2MIW2siiL85tjMSEkTPQ7K4AjH+caz3dy9Sp4iA15T9M8ng1Txi5gG9YEShPzwI5obX3NvTsgEUsE0XWygSltmCae/Ov169KOGUJ1hyj7VPkTly8f8w1dzb6NZCs17TipSc= snovosel@Steves-MBP
```

- Grant AWS Console access?
  > NO
  - Please give a brief description for why you are requesting AWS access.

@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@stephennovosel you should be able to connect to the socks proxy. Reach out in slack if you have issues.
