### ISSUE TITLE
508-defect-2 [SEMANTIC MARKUP, SCREENREADER]: Search form SHOULD use semantic markup

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#12108]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

On the initial landing screen with the search form, the JAWS experience is confusing because there is no indication of entering a form so "School name" moves to "State or territory" without an indication that information could be entered. The form **should** use semantic structure so that screen reader users have the context afforded to sighted users.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user I want to know when there is a form that I can enter data in to accomplish a search for what I need.

## Environment

* Operating System: all
* Browser: all
* Screenreading device: all
* Server destination: production

## Steps to Recreate

1. Enter https://www.va.gov/education/yellow-ribbon-participating-schools/ in browser
2. Start screenreading device listed in Environment
3. Read through the page
4. Verify that it isn't clear there is a search form until the combobox for State or territory is announced

### Current code

```diff
- <p>Search for schools participating in the current academic year, August 2019 through July 2020.</p>
<!-- etcetera -->

<form name="yellow-ribbon-form" data-e2e-id="search-form">
  <label for="yr-search-name">School name</label>
  <div><input name="yr-search-name" type="text" value="" aria-label="Name of institution" /></div>
  <label for="yr-search-state">State or territory</label>
-  <div><select name="yr-search-state" aria-label="State of institution">
    <option value="">- Select -</option>
    <option value="AL">Alabama</option>
    <option value="AK">Alaska</option>
    <option value="AS">American Samoa</option>
    <!-- etcetera -->
    <option value="WI">Wisconsin</option>
    <option value="WY">Wyoming</option>
  </select></div>
  <label for="yr-search-city">City</label>
-  <div><input name="yr-search-city" type="text" value="" aria-label="City of institution" /></div>
  <div>
-    <div><input type="checkbox" /><label for="errorable-checkbox-3">Only show schools that provide maximum funding (tuition that's left after your Post-9/11 GI Bill)</label></div>
-    <div><input type="checkbox" /><label for="errorable-checkbox-4">Only show schools that provide funding to all eligible students</label></div>
  </div>
<button type="submit">Search</button>
</form>
```

### Potential code

```diff
+ <p>You may search for schools participating in the current academic year, August 2019 through July 2020.</p>
<!-- etcetera -->

<form name="yellow-ribbon-form" data-e2e-id="search-form">
+  <fieldset>
+    <legend>Search criteria</legend>
      <label for="yr-search-name">School name</label>
+      <div><input name="yr-search-name" type="text" value="" /></div>
      <label for="yr-search-state">State or territory</label>
      <div><select name="yr-search-state" aria-label="State of institution">
        <option value="">- Select -</option>
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>
        <option value="AS">American Samoa</option>
        <!-- etcetera -->
        <option value="WI">Wisconsin</option>
        <option value="WY">Wyoming</option>
      </select></div>
    <label for="yr-search-city">City</label>
+    <div><input name="yr-search-city" type="text" value="" /></div>
    <div>
+        <div><input type="checkbox" id="errorable-checkbox-3" name="only_show" /><label for="errorable-checkbox-3">Only show schools that provide maximum funding (tuition that's left after your Post-9/11 GI Bill)</label></div>
+        <div><input type="checkbox" id="errorable-checkbox-4"  name="only_show" /><label for="errorable-checkbox-4">Only show schools that provide funding to all eligible students</label></div>
    </div>
    <button type="submit">Search</button>
+  <fieldset>
</form>
```

## WCAG or Vendor Guidance (optional)

* [WEBAIM checkboxes](https://webaim.org/techniques/forms/controls)

* [A11yMatters - Accessible checkbox](https://www.a11ymatters.com/pattern/checkbox/#:~:text=As%20per%20MDN%2C%20a%20checkbox,single%20values%20in%20a%20form.)

## Screenshots or Trace Logs

![Screen Shot 2020-08-05 at 1 21 58 PM](https://user-images.githubusercontent.com/57469/89443710-a8d8e980-d71e-11ea-8090-9a54447a5a2d.png)

**Comment by MarciMcGuireGCIO** [comment]
Moving to a consolidated 508 epic for Yellow Ribbon to clean up our backlog.

**Comment by zacharymorel** [comment]
@joshkimux Looks like the new web component that will be released today will help with this in regards to Check Box's! 
https://github.com/department-of-veterans-affairs/component-library/blob/web-components/src/components/va-checkbox/va-checkbox.tsx#L122

**Comment by zacharymorel** [comment]
I am going to convert the old checkbox to the new checkbox once the code is on prod. It looks like that will help this ticket!

**Comment by joshkimux** [comment]
Fantastic, thanks for looking into this! 🥳

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel should I put a blocker on this since there's dependency on the checkbox?

**Comment by zacharymorel** [comment]
You don't have to, moving on without it.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @zacharymorel !

**Comment by zacharymorel** [comment]
@joshkimux This is ready fro review on Staging.

**Comment by joshkimux** [comment]
<img width="895" alt="Screen Shot 2021-07-06 at 8 41 30 AM" src="https://user-images.githubusercontent.com/14154792/124601565-fc275080-de35-11eb-92cb-d922d8599910.png">

Brilliantly done! Thank you!
