### ISSUE TITLE
[IA] [FE] Update "change address" link to go directly to personal information section of the profile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12100]
## Background
**See IA staging review feedback ticket:** IA feedback - Staging review - Profile 2.0 #11968

Once signed in, the link from the [change address page[(https://staging.va.gov/change-address/) should link directly to the personal information page, not just the top level /profile page. Currently this is not required since the /profile page is essentially a pass-through to the /personal-information page, but as profile evolves, the landing page may evolve and be a separate page.

## Tasks
- [ ] Update link from change address link to go directly to https://www.va.gov/profile/personal-information.

**Comment by sanlouise** [comment]
@mshea0606 

You should be OK to close this ticket. 

The desired change was implemented in [this ticket ](https://github.com/department-of-veterans-affairs/vets-website/pull/13804) - see [this convo](https://dsva.slack.com/archives/C52CL1PKQ/p1597328956032900) for context.
