### ISSUE TITLE
Documentation: Define Vanity URL guidelines and request process

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#12122]
Identify and document guidelines and process for vanity/shortened URLs.

**Comment by mnorthuis** [comment]
Initial draft

[vanity-urls.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5031641/vanity-urls.docx)

**Comment by mnorthuis** [comment]
Vanity URL guidelines documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/vanity-url-guidelines.md

Process for requesting is TBD, but guidelines is complete.

**Comment by mnorthuis** [comment]
Items to do before communicating out:
- Document the process to request and confirm with PW team
- Review with documentation team 
- Look at adding info on vanity URLs versus shortened URLs with https://go.usa.gov/

**Comment by mnorthuis** [comment]
@jenniferlee-dsva @bethpottsVADEPO @DanielleThierryUSDSVA @mpeterz 

Here is the full draft of the Vanity URL guidelines and request process. Can you please take a look and let me know if there are any questions or feedback?   
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/vanity-url-guidelines.md

**Comment by mnorthuis** [comment]
@jenniferlee-dsva @bethpottsVADEPO @DanielleThierryUSDSVA @mpeterz

One last call for a review and feedback on this.  If no feedback is received at end of this week, I will close this and communicate out the guidelines.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mnorthuis. This looks great to me. One thing: I know there's been talk about URL shorteners in the health product space. So we should just check in with health side. I can do that via slack or would you like to?

> Note: We don't use URL shortening services.

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA the "we" in that means VSP...I will clarify the above statement to be clear that we (VSP) do not do the set up, maintenance or review for shortened URLs or provide URL shortening services.

**Comment by mnorthuis** [comment]
File updated and guidelines published.  Closing issue.
