### ISSUE TITLE
Dan offboarding knowledge transfer

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#12120]
@hinzed1127 to do a brain dump of knowledge before rolling off SSOe.

Any and all information is helpful, but to get started:

1. What have been the challenges with race conditions and other undesirable behavior and what seems to bet the best implementation strategy to avoid those?

2. Any insight around writing unit/e2e tests within vets-website, how to structure them and areas where more test coverage would be helpful.

3. Based on feedback accumulated from VSP, what's been the best way to structure utility code related to login (I've seen reducers vs. helper functions at various times, what are the tradeoffs?)

4. Any info about the /keepalive endpoint - how it's supposed to work, challenges we've seen with it. 

5. Any other areas for refactor/improvement

6. Please write up an overview of the smoke test work, where all the bits live, how that needs to be carried forward, and any challenges getting the tests to work reliably.

**Comment by patrickvinograd** [comment]
7. Who have been helpful contacts on other teams (esp IAM) for specific issues?

**Comment by ericbuckley** [comment]
8. I'm still unclear as to the separation between vets-website and what the content team is still responsible for.  Are there any GH tickets that the content team still needs to complete for the SSO project?  If so would we expect any more work to come our way for UI/UX changes?

**Comment by hinzed1127** [comment]
@ericbuckley I tried to write the document I have as something that can sit inside the product description, so I'll answer your question here and we can add it in there if it makes sense.

>I'm still unclear as to the separation between vets-website and what the content team is still responsible for. Are there any GH tickets that the content team still needs to complete for the SSO project? If so would we expect any more work to come our way for UI/UX changes?

I'm having trouble tracking down the _original_ ticket where the Health Pages work was handed off to VSA, but it looks like #10756 and #12446 cover the remaining work around that. To my knowledge, that work should be completely out of our hands by this point.
