### ISSUE TITLE
[Pre-release] Add automation to check the standalone content build against the existing vets-website one

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#12129]
## Issue Description
We are trying to move the content build code out of `vets-website` and into the [content-build](https://github.com/department-of-veterans-affairs/content-build) repo. We have a script that a developer can run locally to compare the two builds to see if they match up, but we want this step to be automated on a schedule.

---
## Tasks
- [ ] Write a script that can be run on a schedule in CircleCI that will run validation script that exists in the `content-build` repo which compares the content build in that repo against the content build in `vets-website`

## Acceptance Criteria
- [ ] The standalone content build is validated against the vets-website one automatically

**Comment by bkjohnson** [comment]
The `content-build` repo has far fewer folders and files than what is in `vets-website`, but anytime a file gets updated in `vets-website` that is in the `content-build` repo we should make sure that the repos don't get out of sync.

### Steps to update the `content-build` repo

1. Look at the history for the same folder in both repos, i.e. `src/site`
1. If `vets-website` is ahead by a few commits, run `git format-patch -1 [YOUR_COMMIT_HASH]` to create a patch file
1. Make sure that the patch doesn't make changes to files which aren't in the `content-build` repo, i.e. `src/applications/vaos/...`
1. From a terminal in the `content-build` directory, run `git am --signoff < ../vets-website/YOUR_PATCH_FILE.patch`
1. Delete the patch file to make repeated steps easier using autocompletion

**Comment by billfienberg** [comment]
Draft PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14264

**Comment by meganhkelley** [comment]
@billfienberg is this ticket complete? Anything else we need to do before closing?

**Comment by meganhkelley** [comment]
This is on hold as we work to release to dev environment. 

#13604 will come first.
