### ISSUE TITLE
[FE] Update Direct Deposit fraud phone number

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12125]
## Background
See ticket: [Design] Profile 2.0 - Direct Deposit - Fraud Note copy does not match design prototype #11489

## Tasks
- [ ] Updated phone number

**Comment by tressaellen** [comment]
Dropping a screenshot for the correct number in here as well. 

<img width="833" alt="Screen Shot 2020-08-05 at 12 21 03 PM" src="https://user-images.githubusercontent.com/58752772/89449342-6525b600-d705-11ea-93d3-c62854dcc70e.png">
