### ISSUE TITLE
Standardize error page behavior 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#12135]
## Overview

- All error pages should but do not show any Va.gov branding 
- 404 is the only status code handled currently and it is not using a standard static page generated by the CMS and it doesn't get the same headers as the rest of the static pages on the site 
- Examples of current error pages:
<img width="873" alt="Screen Shot 2020-10-02 at 2 53 36 PM" src="https://user-images.githubusercontent.com/4998130/94969597-072d0900-04d1-11eb-9278-d9b4bfd2bfec.png">

![image (2)](https://user-images.githubusercontent.com/4998130/94969599-085e3600-04d1-11eb-8fd7-314d83c4fb72.png)

![Screen Shot 2020-10-02 at 17 02 40](https://user-images.githubusercontent.com/4998130/94969635-190eac00-04d1-11eb-9570-6cd73a5f1713.png)

## Tasks 
- evaluate current 404 page to determine if we can / should use a page managed or generated by the CMS build process
- evaluate if we can and should handle additional status codes 
- implement handling for all error codes 
- some login views are returned by vets-api (i.e. not by the html server) and should follow the same display standard as other error pages

**Comment by timwright12** [comment]
This is the config area that holds the 404, we would add the rest of the errors in the same file: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_website_server.conf.j2#L406-L423

Slack conversation: https://dsva.slack.com/archives/CBU0KDSB1/p1628271562236400

**Comment by caw310** [comment]
@GnatalieH , assigning this to you for now. We can review as a team in next planning or refinement meeting.

**Comment by ytsaoca** [comment]
Hi @rianfowler and @caw310 ,

This is Ya-ching. I'm the Product Designer of the check-in experience project. I'm new to the design system and tried to find if there is any component or guile for a 404 mobile website. I only found this ticket and I was still confused. Do we have a 404 mobile website template? Thanks!

CC. @kristenmcconnell @niradatta1

**Comment by caw310** [comment]
@GnatalieH , can you respond to @ytsaoca ?

**Comment by GnatalieH** [comment]
> @GnatalieH , can you respond to @ytsaoca ?

There is not a mobile 404 error template that I can find. I can work on this for the next sprint, however.

**Comment by ytsaoca** [comment]
@GnatalieH  @caw310 
That will be really great! Thanks!

**Comment by GnatalieH** [comment]
Hi @ytsaoca! After doing more investigation on this issue, I realized it isn't something the Design System Team would normally handle (I'm fairly new, too). We typically don't produce new patterns or components, rather we document best practices in examples we see other teams on the platform producing, or point out where a pattern could improve. We encourage folks to contribute to the Design System, so if you have a template to propose for branded error page standardization (desktop and mobile), you can follow these steps for [submitting an Experimental Design pattern](https://design.va.gov/documentation/contributing-to-the-design-system) for the Design System Council to review. Please feel free to ping me if you have any questions.

However, if you are satisfied with using the existing 404 error page pattern (shown here in mobile view), that's fine too:

![image](https://user-images.githubusercontent.com/88347129/137179112-9622f090-1741-4df2-bc81-123f6242aca1.png)

**Comment by k80bowman** [comment]
Closing as this issue seems to be resolved.
