### ISSUE TITLE
Decommission the Puppeteer form tests from Jenkins

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#12139]
Now that Cypress has offically rolled out, we no longer need the Puppeteer form tests to run in CI. Furthermore, the tests that Puppeteer runs have aready been converted to Cypress.

The Puppeteer tests currently run in their own step in Jenkins.

**Comment by U-DON** [comment]
To speed up the pipeline, it would also be worth splitting Cypress E2E tests into their own step so they can run parallel with the Nightwatch tests.

**Comment by meganhkelley** [comment]
@U-DON is this work that our team would complete or should we pass to testing team? (cc @JoeTice @pjhill)

**Comment by U-DON** [comment]
@meganhkelley: I think this would be on us. Mainly to just remove them from our CI pipeline.

Also for the record, the following has been done:
> To speed up the pipeline, it would also be worth splitting Cypress E2E tests into their own step so they can run parallel with the Nightwatch tests.

**Comment by timwright12** [comment]
Chatted with @U-DON about this in [Slack](https://dsva.slack.com/archives/GLDNCMRSP/p1621256986350100)

Opened PR to remove `test:puppeteer*` scripts from `package.json`: https://github.com/department-of-veterans-affairs/vets-website/pull/17256

**Comment by timwright12** [comment]
This has been merged, closing out.
