### ISSUE TITLE
FL Map data layer

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12137]
## Issue Description
Based on Analytics issue #10987 and Epic

The Analytics team has proposed the addition of the following dataLayer variables with that search event to be included to unveil and enhance our insight. We need to groom these items to determine which will be most valuable and how we can prioritize the work. If needed, we can work with the Analytics team to add/remove variables that are unneccessary or don't feel like they provide additional value and help reduce scope / testing etc. They are open to our priorities and scheduling for the timeline and suggested doing the search results returned spec and the search result clicks during 1 sprint and the map movements and zoom interactions during another. Could also be broken into separate issues.

Questions should be directed to @jonwehausen @bsmartin-ep @bmcgrady-ep

### Clicks on Map Pin Clicks & Letter 
Event / DataLayer Variable | Example Value | Description
------------ | ------------- | -------------
`'event'` | `'fl-map-pin-click'` | Event push with each map pin-specific click
`'fl-facility-type'` | `'VA Health'` | Facility type of the facility clicked
`'fl-facility-classification'` | `'VAMC'` | Classification of facility clicked on
`'fl-facility-id'` | `'vha_688'` | Facility ID of facility clicked on
`'fl-facility-facility-name'` | `'Charlotte Hall VA Clinic'` | Facility name of facility clicked on
`'fl-facility-distance-from-search'` | `32.4` | Distance of facility clicked on from search params

### Clicks to Zoom In/Out on Map
Event / DataLayer Variable | Example Value | Description
------------ | ------------- | -------------
`'event'` | `'fl-map-zoom-in' //or 'fl-map-zoom-out'` consistently this value for each interaction type | Event push with zoom ins and zoom outs

### On Tracking Map (Double Click or Hand Click-and-Drag) Movements 
- It looks like the map does indeed render a new search with even the smallest of mouse movement or double click, so in order to normalize this data and increase data quality & meaning -- **We could try to set a threshold value the map must be moved from point A to point B (i.e previous coordinate or searched location to newly moved coordinate) before we write the code to record the dataLayer `'event'`. @mmiddaugh we would of course leave it up to you for what that threshold should be and priority for writing the logic to do so.** Perhaps a miles threshold? 
- It may be helpful to capture at time of map move search completion the user's zoom depth at this point as well to understand proximity, view and overall scale of what the user is actually seeing on the map as well -- that could give us a better sense at time of insight of it perhaps made sense for that user to use the map based on how much they were zoomed in. This also gives us a better way to understand mobile users who naturally have smaller real estate to work with and zoom more often. Interested to hear @brangi and @mpelzsherman your feedback on this, open to your suggestion. 
- For each map movement of significant threshold, **we can push the event `fl-map-movement-search`, along with the following variables:** 

DataLayer Variable |  Example Value
------------ | ------------- 
`'fl-map-miles-moved'` | `'300 miles` `//output of point A to point B calculation`  <br> _open for discussion based on what's available, whether qualitative or quantitative_ 
`'fl-map-zoom-depth'`  | `'<current_zoom_depth>'`<br> _also open for discussion based on what's available, whether qualitative or quantitative_ 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
Our map code currently does not distinguish between a map zoom vs. pan. Here's a [stackoverflow post](https://stackoverflow.com/questions/18609091/leaflet-js-detecting-when-map-finishes-zooming) showing how to set up a zoom listener in Leaflet.js.

**Comment by mpelzsherman** [comment]
@jonwehausen @bsmartin-ep @bmcgrady-ep @mmiddaugh I would suggest capturing the current and new bounding box and current and new zoom level. This may generate a lot of data; any concerns about this?

**Comment by brangi** [comment]
Merged, @mmiddaugh @jonwehausen ,after the next release, these events should start recording on staging and production.

**Comment by jonwehausen** [comment]
Hi @brangi and @mpelzsherman , 

Thank you both for your efforts here. 

@mpelzsherman Apologies for the delay here -- I agree it's best to simply capture the current zoom level rather than track each zoom in/out to conserve hit volume.

Can we discuss how we can bset tweak our solution here?

**Comment by brangi** [comment]
@jonwehausen, we can, however,  I was able to implement all the events as described above with no problem but ^ once in production, maybe you can test the event and give us some feedback?

**Comment by jonwehausen** [comment]
Hi @brangi , 

Certainly. For awareness, we won't enable any of our GTM tracking components to send events to GA until we're able to test out your teams changes within staging. 

In other words, this is fine to go to staging/prod but we're going to want to go through and test to verify everything looks good  and there's no changes we need to make before we turn events on for tracking.

**Comment by bmcgrady-ep** [comment]
Hi @mmiddaugh @brangi @mpelzsherman ,

We are noticing that the dataLayer variables are being pushed individually. The dataLayer variables should be along with the event `fl-map-pin-click`.
![image](https://user-images.githubusercontent.com/66263904/93538087-183b1f00-f902-11ea-982a-1fa15d832399.png)


Also, we aren't seeing any dataLayer variables coming in with `fl-search-results`. 
![image](https://user-images.githubusercontent.com/66263904/93537972-c8f4ee80-f901-11ea-91ee-4fd78d2c71d3.png)

**Comment by brangi** [comment]
> Hi @mmiddaugh @brangi @mpelzsherman ,
> 
> We are noticing that the dataLayer variables are being pushed individually. The dataLayer variables should be along with the event `fl-map-pin-click`.
> ![image](https://user-images.githubusercontent.com/66263904/93538087-183b1f00-f902-11ea-982a-1fa15d832399.png)


I don't see this specified anywhere in the Issue Description^ though? but it's an easy fix.


> Also, we aren't seeing any dataLayer variables coming in with `fl-search-results`.
> ![image](https://user-images.githubusercontent.com/66263904/93537972-c8f4ee80-f901-11ea-91ee-4fd78d2c71d3.png)

`fl-search-results `is an old event, new events with variables have not been merged yet, do they need to be pushed together as well?

**Comment by jonwehausen** [comment]
Thank you for that infomation @brangi !

Yes, per our slack conversation, we will wait for the items from #12136 to merge in.
