### ISSUE TITLE
Responsive design at breakpoint 1008

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12131]
## Issue Description
As a Veteran, I need the Facility Locator search page to adjust to my viewpoint so that all content is rendered on screen and available to me. 

## Current behavior
We currently have two layouts: desktop and mobile. 

There are several Defect-1 issues documenting the behavior of search buttons and content wrapping in screen sizes between standard desktop and mobile. 
- [508-defect-1 [ZOOM, MOBILE]: Content MUST not be cut off when magnified](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10783)
- [Search button overlaps content in smaller viewports](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11121)
- [508-defect-1 [MOBILE]: In mobile view, content MUST not be cut off ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10782)

<details>
<summary>
The search button leaves the box right around 1000 </summary>

 ![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/163ae4bc-8fed-4332-8ec0-97db2787d359) 
</details>

## Front end tasks
- Set 1008 breakpoint to display full width search fields and search button, consistent with UX Pin specs
- Center pagination below the search results list and map. 
- Center _Can’t find what you’re looking for?  Try using our other tools to search._ below the pagination. 
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
When the Facility Locator search page is viewed at 1008 or below:
- [ ] The search fields and button are displayed full width 
- [ ] Pagination is centered below the search results list and map. 
- [ ] _Can’t find what you’re looking for?  Try using our other tools to search._ is centered below the pagination. 
- [ ] All content is visible, especially in default 100% state 

Usual acceptance criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
### Here is the UXPin prototype at:

[1008 in spec mode](https://preview.uxpin.com/f373333a8a59902cbf120c3f00e6d0e13d52fb75#/pages/131154260/specification/sitemap?mode=i)
[1008 in simulate mode](https://preview.uxpin.com/f373333a8a59902cbf120c3f00e6d0e13d52fb75#/pages/131154260/simulate/sitemap?mode=i)

**Static preview:**
![2-FacLoc-1008](https://user-images.githubusercontent.com/4960080/89677014-a14e4780-d8ba-11ea-96dd-d0270896fea4.png)

**Comment by mmiddaugh** [comment]
Should be pulled into the same sprint as 
[Dynamic resizing #12223](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12223)
[Breakpoint 768#12225](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12225)
