### ISSUE TITLE
FL Search data layer

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12136]
Based on Analytics issue #10987 and [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11597)

The Analytics team has proposed the addition of the following dataLayer variables with that search event to be included to unveil and enhance our insight. We need to groom these items to determine which will be most valuable and how we can prioritize the work. If needed, we can work with the Analytics team to add/remove variables that are unneccessary or don't feel like they provide additional value and help reduce scope / testing etc. They are open to our priorities and scheduling for the timeline and suggested doing the search results returned spec and the search result clicks during 1 sprint and the map movements and zoom interactions during another. Could also be broken into separate issues.

Questions should be directed to @jonwehausen @bsmartin-ep @bmcgrady-ep

## On Search
- We currently have an existing event `fl-search-results` being pushed to the dataLayer with each search. 
- Understanding this is going to take a few different iterations of dataLayer work, and trying to cut-down on parse-out code necessary -- we can begin with the approach of taking and utilizing (_what we can_) of what the API gives us directly in its raw unstructured nature. We can cleanse the data on our side in accordance with PII best practices for Google Analytics. 
- Leveraging [this documentation](https://docs.mapbox.com/api/search/#geocoding-response-object), the fields we can use to start with are `query`, `place_type`, and `place_name` for the response returned that is most relevant according to Mapbox (**_top result with a `relevance` of closest to 1_**). 

DataLayer Variable | Example Value | Description
------------ | ------------- | ------------- 
`'fl-facility-type-filter'` | `'VA health'` | The facility type the user used to filter on search, `undefined` if not used
`'fl-service-type-filter'` | `'Primary Care'` | The service type the user used to filter on search, `undefined` if not used
`'fl-allowed-location'` | `true` `//false` | if the user used the allow location functionality to auto-search, `true` if so, `false` if not
`'fl-results-returned'` | `true` `//false` | `true` if the search returned ANY results, `false` if no results returned
`'fl-total-number-of-results'` | `101` | Contains the full number of results returned ,
`'fl-total-number-of-result-pages'` | `5` | Stores the total number of result pages returned for the search
`'fl-searched-query'` | `"query"` | ![image](https://user-images.githubusercontent.com/48527022/88317091-c8b3ea80-cce6-11ea-84e5-c08153f0295d.png)
`'fl-mapbox-returned-place-type'` | `"place_type"` | ![image](https://user-images.githubusercontent.com/48527022/88317176-e7b27c80-cce6-11ea-8444-a03fb4f1e368.png)
`'fl-mapbox-returned-place-name'` | `"place_name"` | ![image](https://user-images.githubusercontent.com/48527022/88317273-0b75c280-cce7-11ea-9344-c26e4a8889c9.png)
`'fl-closest-result-distance-miles'` | `32.4` | Stores the top result's distance
`'fl-time-to-return-results'` | `4023 //in milliseconds` | Stores the total time taken to return the search results <br> We do currently have a GTM-only solution for this, however, if a relatively low lift to get within the DL, we would like to repurpose to push with this event  

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
`'fl-allowed-location', is the one, I was have not been able to implement so far. @jonwehausen @mmiddaugh  , is this something we really need ?

**Comment by mmiddaugh** [comment]
It would be great to have but I think the other elements will provide a wealth of useful information. 
@brangi, if @jonwehausen has ideas on implementing 'fl-allowed-location', we can put it in its own issue so that you are able to close this one.
