### ISSUE TITLE
Express Care reason for appointment page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12149]
In an effort to improve the usability and provide additional guidance to Veterans on what to add to their EC requests, we are going to have the reason for appointment details on their own page. 

## Acceptance Criteria:
- After user selects symptom from symptoms page, user take to 'reason for request' page
- user can add additional details about their appointment in a open text box up to 256 characters
- for user's contact information, pull phone # and email listed in the VA Profile
- user is provided with prompt where their contact information was pulled and how if they update it will only be reflected in this request 
- ignore the 911 prompt from the mock up below for this page for now

## Mockup:
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/fe12e6a9-c214-4f76-8a7c-3558bfb90436)

**Comment by narin** [comment]
@rtwell The "Tell us about your..." header can get a bit long depending on the reason they select.  Are we okay with this, or do we want to some up with some sort of "short name" for each that we can display here instead? See screenshot below:

![image](https://user-images.githubusercontent.com/786704/89721364-8dc1e000-d991-11ea-9765-4ce760a02523.png)
