### ISSUE TITLE
STEM: Update the URL and breadcrumbs for the 10203 application

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12156]
As a developer, I need to update the breadcrumb of the new 10203 form so that it is fully functional for launch.

## Assumptions:
1. This work will need to be completed behind a production flag (not a feature flag).
2. The "staging.va.gov" portion of the URL is based on the environment where the form is being viewed.
3. This story is a result of: #12307 and #11284

## Acceptance Criteria:
1. Both the "mobile" and "desktop" breadcrumb for the 10203 form are: **Home > Education and training  > How to apply > Apply for the Rogers STEM Scholarship**
2. The breadcrumb pieces are links (when applicable) / displayed on the following pages:
    a. Home page: https://staging.va.gov/
    b. Education and training page: https://staging.va.gov/education/
    c. How to apply page: https://staging.va.gov/education/how-to-apply/
    d. Apply for the Rogers STEM Scholarship page: https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203
3. The form url is: https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203
4. On the [How to apply page](https://staging.va.gov/education/how-to-apply/), when the user selects "
Applying to extend my Post-9/11 or Fry Scholarship benefits using the Edith Nourse Rogers STEM Scholarship" and continues to apply, they are redirected to: https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203

## Supporting Artifacts:
1. https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/registry.json#L517

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13814
Branch: bah-12156

Note: 
 You will need to run `yarn build` in order to see the changes

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-13 at 12.25.09 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e36f0fcd-947b-40f3-a80d-5bb62631a0de)
##
![Screen Shot 2020-08-13 at 12.25.02 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4d65b229-0a32-45cc-8083-4e9d3531c5d2)
##
![Screen Shot 2020-08-13 at 12.24.53 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3993f568-8348-49d2-8c5d-ab6e9fac60c9)
##
![Screen Shot 2020-08-13 at 12.24.45 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7dad0a43-df95-4fcd-9ad7-b2d5d789112c)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/11239&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/11239&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah is now on Staging

**Comment by hughes-dustin** [comment]
Devops PR: https://github.com/department-of-veterans-affairs/devops/pull/7413

vets-api PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4739

**Comment by hughes-dustin** [comment]
second vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13893

**Comment by JenLJ** [comment]
@sonntag-adam UX has reviewed and this checks out!

**Comment by sonntag-adam** [comment]
Closing story.
