### ISSUE TITLE
Same-day mental health alert on EC symptoms page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12153]
Per VA's Office of Mental Health and Suicide Prevention guidance we want to direct Veterans to use the already existing same-day mental health appointments option. Any Veteran can use the VA facility locator to find a VAMC of their choice, call the facility, and say “I need a same day mental health appointment” and they will get a Veteran connected to services. 

To our knowledge, Express Care is not necessarily being monitored by mental health providers, so we wanted to make sure Veterans needing same-day mental health care were directed to the right place.

## Acceptance criteria:
- add alert specific to same-day Mental health appointments to EC symptoms page
- prompt links out to facility locator with 'facility type: va health' and 'service type: mental health care' pre-populated
- user can also navigate to the 'type of care' page to start traditional appointment request flow if applicable
- prompt "don't see you're symptoms list" now also lives with this mental health content in same alert

### Mock up
Need to update copy too... 
{begin alert}
If you need a mental health appointment today
Please call your nearest VA medical center or Vet center, and ask for a "same-day mental health appointment."
Find a VA location

If your health concern isn't listed here
Please use our appointments tool to schedule an appointment.
{end alert)

![Screen Shot 2020-08-06 at 10.17.20 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/74cfda1d-f476-44da-ad97-fcec06d7b03c)

**Comment by peggygannon** [comment]
Hi, @rtwell and @lenaecb here's the latest content for the EC mental health alert.. this was posted in Slack, but got lost in a flurry of messages! 

{begin alert}
**If you need a mental health appointment today**
Please call your nearest VA medical center or Vet center, and ask for a "same-day mental health appointment." 
[Find a VA location](/find-locations)

**If your health concern isn't listed here**
Please use our [appointments tool](/schedule-view-va-appointments/) to schedule an appointment. 
{end alert)

**Comment by narin** [comment]
@rtwell Do we want to use a different font for the bolded headers, or does this look okay?

![image](https://user-images.githubusercontent.com/786704/89932639-cdbbd980-dbc2-11ea-89e7-09e7b3c48224.png)

**Comment by rtwell** [comment]
yes @narin it should look like what's posted above.
