### ISSUE TITLE
Access for Lawrence (Glen) Holcomb

### ISSUE THREAD

**Issue by LeakyBucket** [department-of-veterans-affairs/va.gov-team#12161]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Lawrence Glen Holcomb
- Please Provide your email.
   > glen@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > COVID Vacccine Trial Team, I am a backend engineer, I work for Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtC0CWhJq3XzAFOz9bD04f81Ttf7AxvcYjb8GKV2dqMJc46YlmxSMuwkMTwJvpBVYQ0VgEvGaWGvFPogfI5ONl0cIv2C0gA4BwuuGWnKX3DtfX/vuRjE7bDmvxcvHBGIPEmDkmFSKsRINFR2MCi+g102hcHpe9QzOtZrkzep4c2ERIhcE6tzc5+mAmR/d7E+fkfETJXef4hkc7LjbD5UQEY0pSXpxtZOBx1HM3tleQ3WU9graXE3KHo/LK+Cu6Xiyiztup5uni/VTjosot0PFzJiLz7GGH1wY+AH6rq3pKkXMbYSm+UYcbPer0vk9WAt30I0Sx8yrt1/XnO0jpLK3f lawrenceholcomb@Lawrence-Holcombs-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES
  - Being able to view CloudWatch logs would be 👍

**Comment by LeakyBucket** [comment]
ping @department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter

**Comment by tskinn** [comment]
@LeakyBucket you should be able to connect to socks now.

**Comment by LeakyBucket** [comment]
Thanks @tskinn I can confirm that socks is working and I can get to Jenkins.

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS access.
