### ISSUE TITLE
STEM - 10203 Submission fails when not signed in

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#12163]
When submitting the 10203 form without logging in, the user receives the following error message:

![Screen Shot 2020-08-06 at 11.24.47 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2d743731-6a7f-46f3-be0f-4b9359eafb9b)

#### Expected behavior
The user should be able to submit without being logged in

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4659

**Comment by delli-gatti-michael** [comment]
Locat testing complete

**Comment by delli-gatti-michael** [comment]
Fix is now in staging. Closing this issue
