### ISSUE TITLE
Access for Helen Shin

### ISSUE THREAD

**Issue by helenshin-va** [department-of-veterans-affairs/va.gov-team#12162]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Chante Lantos-Swett
- Please provide your name.
   > Helen Shin
- Please Provide your email.
   > hshin@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > IRIS/Team Orchid - Tech Lead [ThoughtWorks]

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCv3xuwI7F4Xcp8cgBE4SetTgPZBOVsmUgstyyWfU4e/lIO/b3DLExlZPbmAGpSjdf13JKG1HPD3NM9CRCgvLP2sAHa6K9TicMMCrQei5s/Fl8V6ckQpmlu3PIDUU91vnARksbfjENS44uQTWcRCNeiNVn/enRZ29bPVwZeaZOQFfY8Joi/xldv+/E7Ta87g1/ljE3M+Fy86BO+Mby2HR44UktD6trRmPSzH84XfdachHXUPC/9iCBsDFw/2y4psIE58yB/wuA+tsoISNwE/aN0xZnyZzJRaY0Uo90LM0NqBb/QaspUG1ZbnE7HqmA3wwuxfErju7QJ/xMBpRK7BnsipRjpG1tbfJOcxTKqqdLWwQAT6So3xzfMxFdIXp7LhaYwWoZ3uPhpleSGjuQjqZSFj+6bR4R7iin3Lr8a3/fUw9tcnCUAkiCiDNp3sNdC4/HvWjlBqI7UFy41OKTsd3zEuZXSVferlvKAooUaCNAHfgXqyAV1Z4aFpWctHyRv0H8= hshin@Helens-MBP
```

- Grant AWS Console access?
  > NO

**Comment by helenshin-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@helenshin-va you should be able to connect to the socks proxy now. Reach out in slack if you have any issues.
