### ISSUE TITLE
[Post Launch] Profile 2.0 Post Launch content/URL Updates

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12175]
## Background
This EPIC will be used to record and track post launch content URL updates that need to be made.

See Ticket: #8395  

## Tasks
- [ ] Direct deposit 
- [ ] Change address content page, update 3 separate URLS
- [ ] TBD
- [ ] TBD 
- [ ] TBD

**Comment by Samara-Strauss** [comment]
Closing this. I don't think there are any post-launch URL updates. We've already updated the content pages, and the public websites team is handling the redirect from account --> profile.
