### ISSUE TITLE
VSP content feedback - Health questionnaires MVP (usability prep)

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12178]
## User story

This ticket captures VSP content feedback on Health questionnaires MVP. 

## Acceptance criteria

- [x]  VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x] Teams leaves comments about any feedback they decide not to take
- [ ] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
Content feedback is below for 

H1? Title of questionnaire 

Question: Should this H1 title be specific about type of appointment you have? Or should this H1 be more general that could apply to many different appointments? 

*Consider*

Screenshot 1 Veteran information 

- Recommend updating first line to: 
You have an appointment at [name of facility] with [provider name] on [date] at [time]. 

Below is the personal and contact  information we have on file for you. 


- Need help? footer
I recommend updating the footer to the below to align with other health tools on the site: 

If you have questions or need help filling out this form, please call VA Benefits and Services at 800-827-1000{make phone number a link}. If you have hearing loss, call TTY: 711. 

If you have questions about COVID-19 and how it affects VA health care, please [go to our coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/). 

----

Screenshot 2
Reason for visit screen
- I recommend updating head TO:  **Please tell us the reason for your visit**

- Please remove double question (it’s currently in header and again right above text box)

- I recommend updating the questions/label to the below to be more conversational 

**What’s the main health concern or goal you’d like to discuss with your provider?** 
To help your provider prepare to best meet your needs, please tell us the main reason for your visit. 
{text box}

Please provide any added  details you’d like to share with your provider  about how this concern or goal affects you. 
{text box}

- Question: is this 2nd question optional? If so, I recommend adding (Optional)


- Can we make Additional questions a header like the “What concerns…” question header above? See recommendation below.

- Also, for the sentence that currently reads, “Do you have other concerns or goals that you want to discuss with your care team” please update “your care team” to “your provider” for consistency with the first question…unless there’s the potential for the appointment to be with multiple members of the team? 


-------

Screenshot 3

3. Additional questions
- I recommend updating this subhead to: **Do you have any other health concerns or goals you’d like to discuss with your provider? ** 

- Question: is this question optional? If so, please add (Optional) 

- I recommend updating sentence TO: 
 Please share any additional concerns or goals. Please list them from most to least important. 


Recommendation for label: 
Concern or goal 1
Concern or goal 2
Concern or goal 3

**Comment by arickalewis1** [comment]
Thanks for your feedback! I have incorporated most of what you stated -- I will update once more after the study. 

![reason for visit](https://user-images.githubusercontent.com/54509359/89787570-49def000-dae3-11ea-9375-1d327a4d2980.png)

**Comment by peggygannon** [comment]
thank you @arickalewis1 Please keep me posted on the research and if the content needs further tweaking based on users feedback.

**Comment by abuckley3385** [comment]
@peggygannon can you close this ticket per your review and end of sprint 27
