### ISSUE TITLE
Analytics Reporting Request for Healthcare Application

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#12182]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
- Who is this request for?
     - Alayna, @ala-yna 

    
- What team/project is this work for?
     -  Looking into work on the 10-10EZ/Healthcare application
    

## Timeframe for Analytics Requested
- What timeframes are you looking to analyze (e.g. before vs. after)?
     - As old as possible

## Analytics to Track Down
> Examples
> 
> - [ ] What issues do users face related to filling out the healthcare application?
> - [ ] What behaviors have we seen related to the healthcare application?

## Which Product Questions are you trying to answer?
- What issues do users face related to filling out the healthcare application?
- What behaviors have we seen related to the healthcare application?

## Other Helpful Questions to think through
- Who is your audience? Product managers
- Why do you need this data? To define and scope out how we might best support veterans applying for healthcare benefits
- What are you hoping to find? More details on the pain points that veterans face when applying for health care
- What is your hypothesis that you're hoping the data will support? None yet!

## Additional Comments
- Appreciate your help!

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @ala-yna , confirming receipt. We will get back with you as soon as we can here.

**Comment by jonwehausen** [comment]
@bmcgrady-ep to fulfill reporting request at earliest convenience.

**Comment by bmcgrady-ep** [comment]
@ala-yna Currently we have the capability to see the funnel of the Healthcare Application. Here is the report for that: https://analytics.google.com/analytics/web/#/report/conversions-goal-funnel/a50123418w177519031p184624291/_.goalOption=13

However, we do not currently have existing event tracking happening within the application. We only have event tracking for the start of the forms and the form submissions. If you want more behavioral tracking it will involve an implementation.

**Comment by joanneesteban** [comment]
@ala-yna - let us know if you want the behavioral tracking for 1010ez?

**Comment by jonwehausen** [comment]
@ala-yna We will close this per @bmcgrady-ep report delivery. 

If hoping to see more granular data as it relates to the health care application, we can work with you on a separate request to propose a data layer specification tracking those areas of the form where users may face complications. 

cc: @bmcgrady-ep @joanneesteban
