### ISSUE TITLE
Access for David Addison

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-team#12187]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > David Addison
- Please Provide your email.
   > david.addison@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS-CMS, Delivery Manager, Agile Six / CivicActions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeFChafeOwvQRJ3q5HN4RehX3WrVBmvVF36MUMxbiNeNCIOv7Q0jtDKCL++n2l88y/GVAeNJkJils76GzbsIbYHbFM84nE1n4wrTvYAvnpPOin5EIGn8oXm4hVWZwao+86NO/FzZdpAvViJ0nhiL0SDo0A6/5knvxVVfQq/rJq1nljisisgtenKeGiJmAP0bzZzjapWLgx3Gck3qC+gygKdqagSButqQ16WL+uwxN+GH+pqQmcrosJnRn+CDcYL7Ru8qg0tnJqriMUuOuB8H5Ea/IbXvEzkqAoGYCFg+Co/SWYM9AfdMI6mjeOmP1vP875fGQMZ6dCzQOQFY8X8iWWwkYlXuKpKQtT1WBXiD0J7Mu5O5MBvTsFSF4ENotm3wu+bVx1/OZ6bUXNbHKRvO0y8pI/8+MWyb9Q480VDIPTKYX/SoyF6EKhIDFGGMOKqB4bpQv/ZH4E/wVAs9KQXvHVTCG6GdzCjvSECx2xBYIKob3OPlbbhfb69lVzFdWG14U= okied@LAPTOP-LGL5TLEH

```

- Grant AWS Console access?
  > NO
  - Please give a brief description for why you are requesting AWS access.

**Comment by daddison48** [comment]
@department-of-veterans-affairs/vsp-operations I submitted a request for my SSH key authorization

**Comment by tskinn** [comment]
@daddison48 you should be able to connect to socks proxy now. Reach out in slack if you have issues.
