### ISSUE TITLE
CT-Filter: Update Search Results - "Refine search"

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12186]
## Value Statement
As someone using the Comparison Tool, I want to be able to filter search results on more specific criteria so that I can more quickly find the institution I am looking for. 

## Assumptions
1. This work should be behind a feature flag: #11344

## Acceptance Criteria
1. On the Search Results page, the left panel has been updated as follows:  
   a. The "Refine Search" heading is changed to "Refine search"

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/13770

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-11 at 12.56.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e5252092-3170-4d58-ba1f-50b2214483f6)
##
![Screen Shot 2020-08-11 at 12.56.35 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/103ea339-6c94-4a21-9572-1041ca382f96)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/10617&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by ccruzgra** [comment]
@sonntag-adam This work checks out.

**Comment by sonntag-adam** [comment]
Closing story.
