### ISSUE TITLE
STEM: Chapter 3 change "See eligible Programs" to "See eligible programs"

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12203]
Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/benefits/stem-eligibility. On chapter 3 needs to update "See eligible Programs" to "See eligible programs"
##

![Screen Shot 2020-08-07 at 8.22.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6ecdc224-e93a-41f2-881e-8a7bce5a894f)

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13777

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-08-10 at 12.27.47 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b4402c05-fd15-44c3-8ec4-00dae6e612e5)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is now on Staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael This checks out for UX!
