### ISSUE TITLE
Rewrite Nightwatch helper functions in Cypress for keyboard e2e tests

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#12208]
## User Story 

@1Copenut can you help fill in the details here? (This issue will be in our backlog)

## Details 

Per discussion between Megan/Rian/Eugene/Trevor on 7/30/20: 
- Note that if/when we deprecate Nightwatch entirely, we’ll need to rewrite some helper functions for keyboard e2e tests, specifically for Education Feedback Tool and GI Bill Comparison Tool (maybe Facility Locator?) 

## Definition of Done 
- [ ] Helper functions for keyboard e2e tests have been written as needed in Cypress 
- [ ] Teams who work on the apps that had these helper tests in Nightwatch have been informed of the move to Cypress as needed
- [ ] Documentation has been updated as needed

**Comment by pjhill** [comment]
Duplicates the initiative to rewrite the helpers here -- https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15784
