### ISSUE TITLE
STEM: Update 'Auto Email Sent to SCO:' in Spool File

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12205]
As an STEM Scholarship processor, I need the 'Auto Email Sent to SCO:' field to be populated so that I can determine the next steps that are necessary so that the application can be processed in a timely and efficient manner.

## Assumptions:
1. This work is done behind feature flag #7271.
2. When this work is completed, the generated spool file should be sent to the following individuals so that they can do a test run in TIMS to ensure that it loads properly.
   a. shay.norton-leonard@va.gov
   b. pierre.brown@va.gov
3. The field 'Auto Email Sent to SCO:' continues to be populated with 'Yes' when an email has been sent to the SCO.

## Acceptance Criteria
1.  The field 'Auto Email Sent to SCO:' is populated with 'No' when an email has not been sent to the SCO.

## Technical Notes:
1. Some Possible reasons for an email not being sent:
    a. feature flag edu_benefits_stem_scholarship is disabled
    b. no token for usage with email delivery server
    c. user is not authorized to access EVSS, most likely cause they don’t have a EVSS account an email has not been sent to 

## Supporting Artifacts:
1. [10203_Spool_20200709_story_version.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5041429/10203_Spool_20200709_story_version.docx)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4669

This does not require a EVSS user in staging.

When testing you are just verifying that instead of `N/A` occurring you get a 'No' locally when either
 - In vets-api’s `settings.local.yml`  remove the property `govdelivery.token`
- Disable feature flag `edu_benefits_stem_scholarship`

**Comment by delli-gatti-michael** [comment]
Tested by the following test case
https://dsvavsp.testrail.io/index.php?/tests/view/10545&group_by=cases:section_id&group_order=asc&group_id=51&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
Testing passes locally.

a 10203 form was submitted on 8/11/2020 under confirmation number `V-EBC-4656`. That submission will show in the spool file generated on the morning of 8/12. It will contain the following line:

`Auto Email Sent to SCO: NO`

**Comment by delli-gatti-michael** [comment]
[307_08122020_070002_vetsgov.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/5064183/307_08122020_070002_vetsgov.txt)

Spool file entry is as expected. Closing this issue
