### ISSUE TITLE
STEM: Duplicate sentences on print confirmation screen

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12202]
Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/confirmation

Select "Print this page"

There are two of the sentence under "What happens after I apply?".  "You’ll get a Certificate of Eligibility (COE), or award letter, in the mail if we’ve approved your application. Bring this to the VA certifying official at your school." There should only be one.
##
![Screen Shot 2020-08-07 at 7.52.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9252a39d-e257-4be6-9525-5da3b6da9d8c)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-10 at 12.02.59 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/195f6d98-c726-437b-86dd-dcad876e83ab)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by ccruzgra** [comment]
@sonntag-adam Checks out for UX!

**Comment by sonntag-adam** [comment]
Closing bug.
