### ISSUE TITLE
STEM: Signed in - Intro page - Duplicate informational alert and green start application button at top. 

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12201]
Signed in - Intro page - Duplicate informational alert and green start application button at top. They should only exist at bottom of page as per prototype and content doc.

Steps to reproduce:

1. Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction
2. Sign in 
3. Observe

Expected behavior:
Remove informational alert and green start application button from top of intro page.
##

![Screen Shot 2020-08-07 at 7.17.21 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/78a8aa1c-1fe9-4009-b0b2-b47d9d52e7d2)
##
![Screen Shot 2020-08-07 at 7.17.28 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/36095b80-7c3a-418e-8dd1-4d4899699037)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13766

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-10 at 11.14.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/56fb4a71-0e1a-4bed-a5c2-61c3804d5f06)
##
![Screen Shot 2020-08-10 at 11.15.05 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/03b8acee-ac19-4d99-803a-5e19ebc96899)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by amyknox** [comment]
Checks out for me.

**Comment by ccruzgra** [comment]
This checks out here, too @sonntag-adam.

**Comment by sonntag-adam** [comment]
Closing bug
