### ISSUE TITLE
STEM: Exit application buttons have down chevron on both benefit eligibility summary pages

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12200]
Exit application buttons have down chevron on both benefit eligibility summary page (Ch2) and STEM scholarship summary page (Ch3). See the screenshots below.

Steps to reproduce:
1. Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/ 
2. Fill out the form to chapter 2 and 3
3. Observe
##
![Screen Shot 2020-08-07 at 6.35.10 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2b89eef0-8a10-4763-b4f4-9537dbffbfa4)
##
![Screen Shot 2020-08-07 at 6.49.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/968d3a22-c1d2-4b4d-810a-262f97ae4989)

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13776

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-08-10 at 11.11.08 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e77a6dab-2f8e-4b99-bdbc-fb34ff6c27a9)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is now on Staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael This checks out for UX!
