### ISSUE TITLE
Cypress improvements post-release

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#12206]
## User Story 

As a VFS developer, I want to be able to effectively and efficiently set up frontend e2e tests for the products I'm building on VA.gov, so that I can provide a defect-free experience for Veterans.

## Details 

Cypress was officially released to VFS teams on 8/1/20. The tickets in this epic represent remaining items in the Cypress backlog.

**Comment by pjhill** [comment]
All stories have been completed for this epic.
