### ISSUE TITLE
STEM: Missing period on sentence "Equal to VA Form 22-10203 (Application for Edith Nourse Rogers STEM Scholarship)"

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12204]
Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction

There is a missing period on the sentence "Equal to VA Form 22-10203 (Application for Edith Nourse Rogers STEM Scholarship)". It should be "Equal to VA Form 22-10203 (Application for Edith Nourse Rogers STEM Scholarship)."
##

What it looks like

![Screen Shot 2020-08-07 at 8.31.40 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8a09044b-d2f6-4b4f-ab31-aa4737ee942e)
##
What is should be
![Screen Shot 2020-08-07 at 8.31.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9be1ffb7-bc25-4f68-b75d-2c248f49d6ea)

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13777

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-08-10 at 12.25.28 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2fa426c3-0a89-42d6-a253-96c6edcb5671)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is now on Staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael This checks out for UX!
