### ISSUE TITLE
Create ESLint rule for axe checks in Cypress

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#12207]
## Description 

As decided by Megan/Rian/Eugene/Trevor in meeting on 7/30
- we need to add an ESLint rule that applies to axe checks in Cypress (there is an existing ESLint rule that applies to axe checks in Nightwatch)
- warning message should link to documentation that instructs people to disregard the rule if they've used the Cypress form tester, which automatically includes axe checks
- that documentation should also explain that if they want to disregard the warning permanently (if they are working on a form), they can do so with Trevor's approval (docs explain HOW to do this) 

## Acceptance Criteria
- [ ] VFS teams are warned if their app is missing axe checks
- [ ] ESLint axe check warnings account for the fact that VSP's recommended e2e tester is now Cypress 
- [ ] We need to announce this change in ToT -- 11/2
- [ ] Craft a notice for Slack
- [ ] Alter the warning to link to documentation in Platform website with details specific to Cypress instead of NW

**Comment by pjhill** [comment]
* Notify VFS teams that an ESLint rule enforcing axe checks in all Cypress tests is coming
* Consider having a long warning period (~1 month)?
* Notification can contain reference to justification coming from ATO

**Comment by pjhill** [comment]
Throwing this into the Icebox until the previously mentioned issue is resolved and this is prioritized for Noah again.
