### ISSUE TITLE
Determine timeline and strategy for deprecation of Nightwatch

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#12209]
## User Story

As a VSP developer, I only want to support one frontend end-to-end testing tool (Cypress), so that I can support VFS teams more efficiently and effectively. 

## Details 

This is a placeholder ticket for beginning to determine timeline and strategy for deprecating Nightwatch. Upon rolling out Cypress 8/1/20, we told VFS teams that they were encouraged but not required to migrate existing test from Nightwatch, and that if we were ever to deprecate Nightwatch we would give plenty of warning before doing so. 

We should give teams a good few months to ramp up on Cypress and monitor the Cypress and Nightwatch usage metrics recorded in #11703 before picking up this ticket, perhaps in Q1 2021 or later.

**Comment by pjhill** [comment]
Do we need Nightwatch to provide IE11 smoke tests in production?
Can we end of life Nightwatch if IE11 support remains essential on the platform?
Would the existing Nightwatch test specs actually run in IE11 without any changes?

**Comment by pjhill** [comment]
IE11 EOL pontification: https://vfs.atlassian.net/wiki/spaces/VI/pages/708116498/IE11+End+of+life

**Comment by pjhill** [comment]
[Spreadsheet of Nightwatch tests](https://docs.google.com/spreadsheets/d/1DXj0GzObcfxBn6LKhOD9QO7kF8iZEWciAjHFfBkrFfs/edit?usp=sharing)

**Comment by ddzz** [comment]
# Nightwatch deprecation documentation

Nightwatch is being deprecated in favor of Cypress for automated end-to-end testing. Our existing test suite consists of a mix of Cypress tests and Nightwatch tests. We have half as many Nightwatch tests (50) as Cypress tests (~100 and growing), and Cypress test execution takes significantly longer: on Jenkins, Cypress takes over 25 minutes while Nightwatch tests take five minutes. Additionally, a separate suite for accessibility testing is run using Nightwatch. The accessibility test suite runs an aXe check against the entire VA.gov sitemap, taking over 20 minutes to run.

## Notes on existing tests
- There is no obvious duplication of tests between Nightwatch and Cypress for testing functionality.
- There is duplication of accessibility testing: aXe tests are being run with both Nightwatch and Cypress.
  - Cypress aXe checks tend to be more thorough than the Nightwatch accessibility suite. Some Cypress tests run aXe checks multiple times on the same pages to check for aXe failures on page state changes, whereas the Nightwatch checks run only against the initial, unmodified page.
- Some Nightwatch tests test keyboard navigation.
- Nightwatch is integrated with SauceLabs for cross-platform testing.
- Nightwatch supports testing in IE whereas Cypress does not.

## Deprecation strategy
Deprecation of Nightwatch will likely have to be rolled out in three separate steps:
- Migrating the Nightwatch accessibility suite to Cypress.
- Having VFS teams re-write their existing Nightwatch tests in Cypress.
- Rewriting Nightwatch keyboard navigation tests using the Cypress E2E Keyboard Helper

## Intenet Explorer 11 testing
There is an open question about how testing of IE11 should be handled. Cypress supports some Microsoft browsers, but it does not support IE11, which is still commonly used by VA.gov users. Nightwatch does support testing with IE11, so the deprecation strategy may have to be modified if testing with IE11 is required. At the very least, a smoke test suite using Nightwatch and IE11 could be developed and maintained while all other tests will be converted to Cypress. This would minimize our need for Nightwatch while still meeting requirements for IE11 testing.

**Comment by pjhill** [comment]
Initial findings and recommendations are in place. We can work the recommended strategy in new tickets.
