### ISSUE TITLE
STEM: Confirmation page language doesn't match content doc.

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12216]
Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/confirmation

Confirmation page language doesn't match content doc. Says, "We may contact you for more information or documents."

Should say:
"We may contact you if we need more information or documents."
![Screen Shot 2020-08-07 at 10.59.03 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ff197274-96ce-43ff-9a94-9fd5d1e5f658)

**Comment by delli-gatti-michael** [comment]
PR:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/13797

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-08-11 at 10.35.43 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/af326dd3-1d3b-4557-b7d0-7dccd0baf15f)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on Staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael This update checks out for UX!

**Comment by sonntag-adam** [comment]
Closing bug
