### ISSUE TITLE
STEM: Changing from ch33 to non-ch33 the bottom of that summary accordion expands & contracts

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12214]
Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/review-and-submit

Observe below
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48804582/89658606-c03de100-d89c-11ea-8237-b376a3bfb0e8.gif)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13798

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by ccruzgra** [comment]
@sonntag-adam This work checks out.

**Comment by sonntag-adam** [comment]
Closing bug.
