### ISSUE TITLE
Investigate eMIS search failures when searching by ICN

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#12212]
*Not a breaking change*

Goal: understand why we're unable to get a successful response from eMIS, come up with a mitigation plan if needed. That way we can use ICN to look up Veteran status/designation in eMIS and send that information to CARMA. Currently, use MVI to look up ICNs and then send that information to CARMA, and CARMA has functionality to search eMIS. Right now, we send all Veterans as "unverified." After this work, we'd be able to send Veterans as verified. 

See: https://dsva.slack.com/archives/CMJ2V70UV/p1596770887353200

**Comment by kevinmirc** [comment]
All veteran status searches with an ICN fail with the error:
```
MIS-ERR-003 INVALID_IDENTIFIER Invalid Parameter Identifier
```

I've tested this by going though our staging user and querying emis with their icn and their edipi. icn based searched will fail even when the edipi based search was successful, for the same user.

**Comment by hdjustice** [comment]
Closing - This ticket has not been addressed in over a year, and there are no initiatives linked.  Any new work will have new tickets created.
