### ISSUE TITLE
Access for Anita DeWitt (IRIS/Orchid)

### ISSUE THREAD

**Issue by anitadewitt-va** [department-of-veterans-affairs/va.gov-team#12218]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Brian Broome
- Please provide your name.
   > Anita DeWitt
- Please Provide your email.
   > adewitt@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I am a developer on the IRIS/Orchid Team from ThoughtWorks.

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDO0E8c0DDRbJr5CWdniNy5AlxZB+RB9lbFptRmFtqYqTajwhLvu2l9LU/cRlk5LmYt41GjGF4xCFyIspA0O0Up7p25OANBNDw67NlfuCJUofJHXczmrL/csS7W06UPVGCA55KFv9Zcz10BAdkaz8vLrsdxufE/Ve1whm0wRADlw9qF/zn5HYmi8ZIN/u8K/SlKsJcztyjBnCTcClPZvqPNyDSy9uHPEsd/+RpkMaKT/F8jE+hx+8fLToxECGdBvbQJyFg46XZvCnysbjGLX6HvD0rVH52IuVmzNLb0Krc2t5iOkggItSnUDxQjuKT8BtIEeqyM9wvnM1OpeZuCQHsv adewitt@Anitas-Computer.local
```

- Grant AWS Console access?
  > YES
  - I am requesting access for tools such as Jenkins, Grafana, Sentry, and SOCKS Proxy

**Comment by anitadewitt-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by anitadewitt-va** [comment]
updated public SSH key for request:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEEX4CqOUYO//VtNnHwZPyCMHR2p8SgyheOY0qN6A3AcNZxn0SpQMlI4/poVvh+2jdyy82PK7KIkZnVu6Lw0uldAnB0PIDUn1sww45vTh3dN7GZhTlaLoNsJapMd+08AGA4swETBk8lwaqc+YCl3uY6ndCtU/OSc2YMhLHiqXdGEednipZ2dFTdVN8tA5ybcF0COOiN8C3ondQAkN1SifiAPoZYYUNX/DRaeC7+vcwFm3GgrV83p5iov7pDvmnK4DY43iMUlnWXKfd0wdIpIk/nECKOfV56BuglePf5sxI1ytrZ1fbxZpeg0GxAqY330fT1Rktk+4eipWlWCK373Qz adewitt@Anitas-Computer.local
```

**Comment by tskinn** [comment]
Thanks @anitadewitt-va Are you sure you need  AWS console access. You should be able to reach the tools you mentioned without AWS access.

You should be able to connect to socks proxy now. Reach out in slack if you have any issues.

**Comment by anitadewitt-va** [comment]
> Thanks @anitadewitt-va Are you sure you need AWS console access. You should be able to reach the tools you mentioned without AWS access.
> 
> You should be able to connect to socks proxy now. Reach out in slack if you have any issues.

I don't think that I will need AWS console access. Thanks!

**Comment by anitadewitt-va** [comment]
I am having issues connecting to the socks proxy, is there anyway you can let me know which of the above ssh keys is being used by the platform?

**Comment by anitadewitt-va** [comment]
I am having issues connecting to the socks proxy, is there anyway you can let me know which of the above ssh keys is being used by the platform?

**Comment by jsev-io** [comment]
@anitadewitt-va  The second key - the one starting with AAAAB3NzaC1yc2EAAAADAQABAAABAQDEEX4CqOUYO

**Comment by anitadewitt-va** [comment]
got it. I am all connected now.

**Comment by anitadewitt-va** [comment]
I am requesting AWS Console access in order to file a ticket for setting up an s3 bucket for file attachments as a part of the IRIS replacement form.

**Comment by jsev-io** [comment]
@Jeff-Hayter 
**Requesting AWS Access**
User: @anitadewitt-va 
COR: Brian Broome

**Comment by jsev-io** [comment]
@anitadewitt-va I've cc'ed Jeff regarding your AWS access. However, are you actually trying to create / apply the bucket changes yourself? If that's not the case, then you don't need AWS access to create a ticket.

**Comment by jsev-io** [comment]
@anitadewitt-va we'll leave this ticket open until @Jeff-Hayter provides confirmation for that access.
Then you'll be provided credentials.

**Comment by tskinn** [comment]
Julian I think Anita already confirmed she only needs to access these tools through the socks proxy: Jenkins, Grafana, Sentry, and doesn't actually need an AWS account.

I'm going to close this ticket and if I am wrong, @anitadewitt-va feel free to reopen. If you have any issues connecting to socks reach out in slack for support. Thanks
