### ISSUE TITLE
STEM: Feedback button appears on confirmation page

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12215]
Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/10203/confirmation

Observe
![Screen Shot 2020-08-07 at 10.59.03 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/de9dd550-fa91-47a4-ba2f-3f6a77599982)

**Comment by desireeturner** [comment]
@WillMcCormack can you coordinate w Analytics to get this updated? Thanks!

**Comment by WillMcCormack** [comment]
@joanneesteban can you take a look at this when you get back in the office next week? The only page that these surveys should appear is: https://staging.va.gov/gi-bill-comparison-tool

**Comment by joanneesteban** [comment]
@WillMcCormack this should be fixed in Staging. Let me know if this works, and I can push it to Prod.

**Comment by desireeturner** [comment]
@sonntag-adam @delli-gatti-michael  this is ready for QA on staging.

**Comment by delli-gatti-michael** [comment]
This one is a bit odd. The button is there, disappears for a second, and then comes back. If I'm understanding correctly, it shouldn't be there at all. Recording below:

![feedback_button.gif](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/55541f92-78d8-4416-9bea-a2c3640f3262)

**Comment by WillMcCormack** [comment]
Correct, it should only be on the Comparison Tool landing page. @joanneesteban looks like the survey is still there.

**Comment by joanneesteban** [comment]
That is odd. I made another edit. Can you QA again? If it reappears, I'm going to need to a submit a ticket to ForeSee for the engineers to work on it on their end.

**Comment by joanneesteban** [comment]
Can you also try clearing your cache?

**Comment by delli-gatti-michael** [comment]
@joanneesteban I retested this morning after clearing my cookies, cache, etc and I'm still getting the behavior shown in the gif above.

**Comment by joanneesteban** [comment]
@delli-gatti-michael thank you for retesting. I've opened a ticket with ForeSee, and will get back to you when I hear back.

**Comment by desireeturner** [comment]
Moving to Blocked while we wait to hear back from the Foresee team.

**Comment by joanneesteban** [comment]
Hi there. Thanks for your patience. I was able to hear back from the ForeSee team about fixing this. @delli-gatti-michael would you be able to test on Staging again?

**Comment by sonntag-adam** [comment]
@joanneesteban It is still occurring on staging.

![Screen Shot 2020-09-08 at 1.52.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/82300b09-6611-4088-b0e8-a9a2b8470854)

**Comment by joanneesteban** [comment]
Actually, @sonntag-adam would you mind checking again? I think I found the error. Thanks!

**Comment by joanneesteban** [comment]
@sonntag-adam - scratch that. I'll need to regroup with ForeSee again. Thanks for checking.

**Comment by joanneesteban** [comment]
@sonntag-adam or @delli-gatti-michael The ForeSee team made additional updates. I don't see the button on my end; would you mind checking as well?

**Comment by sonntag-adam** [comment]
@joanneesteban I'm still seeing the button on my end

**Comment by delli-gatti-michael** [comment]
I'm also seeing it. It's still displaying the same behavior from the recording I posted above.

**Comment by joanneesteban** [comment]
Thanks for checking! Is this only happening on https://staging.va.gov/education/apply-for-education-benefits/application/10203/confirmation, or is it on all of the education pages?

**Comment by sonntag-adam** [comment]
I'm seeing it on all the education pages

**Comment by joanneesteban** [comment]
Checking back in here - haven't forgotten about this. ForeSee's still working on this, and I'll provide an update when they get back to us with a fix.

**Comment by joanneesteban** [comment]
Checking in again. ForeSee's been adding fixes, but I'm still seeing the button on my end. The logic that we're asking for is for the button to ONLY appear on the following education pages:

staging.va.gov/education
staging.va.gov/gi-bill-comparison-tool

We're asking that _everything_ after the `/` at the end of these URLs be excluded. Will update when we see better results.

**Comment by joanneesteban** [comment]
@sonntag-adam @delli-gatti-michael ForeSee checked in to say they've fixed the issue. I'm not seeing the feedback button on the other education pages now. Can you confirm on your end?

**Comment by sonntag-adam** [comment]
Hey @joanneesteban, confirmed I no longer see the feedback button. Closing bug testing passes QA.
![Screen Shot 2020-10-07 at 7.26.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ff962427-8839-4489-968d-e44fed2fdf14)
