### ISSUE TITLE
Accessibility feedback — Project Kickoff — PW, BAM1, BAM2 [Move How To Apply Wizards]

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#12211]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Point of Contact

**VFS Point of Contact:** Jennifer (VSA) & Trevor (VSP)

## Description

This ticket houses accessibility feedback for the Project Kickoff for PW, BAM1, BAM2 Move How to Apply Wizards.

### Must

1. **Must** use semantic markup. 
    **Why:** This ensures the screen reader user clearly understands the questions and available answers. 
    **Sample markup:**

    ```diff
    <fieldset>
      <legend>For what type of claim are you requesting a Higher-Level Review?</legend>
      <label for="radioA"><input type="radio" id="radioA" name="claim_type" /> Disability compensation claim</label>
      <label for="radioB"><input type="radio" id="radioB" name="claim_type" /> A benefit claim other than disability compensation</label>
    </fieldset>

    ```

### Should

1. Accessibility **should** review any content updates.

### Consider

1. **Consider** using a mobile-first design approach. 
    **Why:** This allows the solution to meet those with in the greatest need and ensure we deliver a streamlined hierarchy and maximize touch experience. We often treat mobile as a fluid delivery of the desktop experience, but the mobile experience has small font sizes, desktop contrast, and small interaction touch points.
1. If there is time and appetite, **consider** how the mobile experience might be improved. 
    **Why:** Same as for mobile-first approach
    **For example:** font-size could be increased on mobile for the questions and input labels, the radio inputs could use radio input buttons. The Benefits and Memorials 2 team has a radio input that enhances the clickable area affordance with what looks more like a button. There is a case to be made for this "toggle" type of UI element to be added to the VA design system, yet it would require clear guidance for usage.

   **Unselected**
![Screen Shot 2020-08-07 at 11 06 12 AM](https://user-images.githubusercontent.com/57469/89659571-0e071900-d89e-11ea-97bf-f8e07520a387.png)

   **Selected**
![Screen Shot 2020-08-07 at 11 06 04 AM](https://user-images.githubusercontent.com/57469/89659628-1eb78f00-d89e-11ea-9511-bd450671a235.png)

## Definition of done

1. Review and acknowledge feedback.
1. Document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions.

cc @1Copenut — ready for your review!

**Comment by 1Copenut** [comment]
@jenstrickland I agree with the feedback listed here. 

The must feedback about using proper `fieldset` and `legend` structures will be a good context improvement for screen reader users. If that work needs to happen as a next iteration post-launch, that's fine.

VSP has no additional feedback. We are 💯

**Comment by leahkeeler** [comment]
@craigwheeler - assigning this to you for EDU

@Mottie - FYI, not sure this applies to the work you are doing, if it does feel free to add your labels or however you keep track
