### ISSUE TITLE
STEM: Display validation message on Chapter 2 / Chapter 2 Summary

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12224]
As an applicant, I need a validation message to display if I do not complete the required information so that I know what needs to be done in order to proceed.

## Assumptions:
1. This work is completed behind the feature flag #7271.

## Acceptance Criteria
1. On Chapter 2 Page 1, the following message is displayed if the user tries to continue without selecting a benefit: "Please select at least one benefit"
2. On Chapter 6 Page 1, the following message is displayed if the user tries to continue without selecting a benefit: "Please select at least one benefit"

## Supporting Artifacts:
1. Chapter 2 example ([prototype page](https://bahdigital.invisionapp.com/share/YFIAEHK8U2W#/screens/296045010)):
<img width="505" alt="chapter-2-validation-example" src="https://user-images.githubusercontent.com/48260534/89670744-b1145e80-d8af-11ea-9c8d-dfdb44468921.png">

2. Chapter 2 summary example ([prototype page](https://bahdigital.invisionapp.com/share/YFIAEHK8U2W#/screens/296045141)):
<img width="618" alt="1990-benefits-required" src="https://user-images.githubusercontent.com/48260534/89670756-b671a900-d8af-11ea-9815-4ff0c8b9879f.png">

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/13788

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah The fix for this is now on Staging

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/10535&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/12587

**Comment by ccruzgra** [comment]
Based on the AC, this checks out for UX.

**Comment by sonntag-adam** [comment]
closing story.
