### ISSUE TITLE
Access for Jacob Gacek

### ISSUE THREAD

**Issue by jgacek** [department-of-veterans-affairs/va.gov-team#12220]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Bryan Broome
- Please provide your name.
   > Jacob Gacek
- Please Provide your email.
   > jacob.gacek@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > IRIS/Team Orchid - Developer [ThoughtWorks]

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM5goinqaTOvG16NztUCgZdq66x2/ceQ+bk9psXdpcWUcVGbyirBEGVtBh31clQpqRIUE2SVMKViNPJyrF5bCgCz5+iXTAwL4gk0wx/96qBOmkxXT4Nh7pawdw48oSbx7agLdaq8mXuQEk8y/6pW4U+Kik1HlCa8Rkh1frQ9zChKGXlyHy9SN8XhIFHQqCgv8yjc+mzxWeMCjI47/c2YE/T07m80Ny5igz4xr4DoEHZo9GEI6fXnhBeYwszKuGmpv1zpl4AiEn4ZDvTUn3rsAb21JGuzeeW6vAPgLzvGlTpu3VvJat144MdPHBgQ+HtbiG5DLus7Zj99ecIQS5ZLiz jacobgacek@JacobGacek-Mac.local
```

- Grant AWS Console access?
  > NO

**Comment by jgacek** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@jgacek you should be able to connect to the socks proxy. Reach out in slack if you have any issues.

**Comment by jgacek** [comment]
I would like to reopen the issue in order to request AWS Console Access

- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee

- Grant AWS Console access?
  > YES
  
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
#### For AWS Access
User: Jacob Gacek
COR: Cecilia Lee
Approval Needed: @drorva, @mchelen, or @thepipster

**Comment by drorva** [comment]
approved

**Comment by jbritt1** [comment]
Temporary credentials provided to user at this time.
