### ISSUE TITLE
staging.va.gov - Canceled Future and Past VVC Appts Not Displaying

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12221]
## What happened?  
Cancelled VVC appointments that are >=current date are not displaying in new UI
Past VVC appointment do not display

## Specs:
- Device: (e.g. iPhone 8, Macbook)  PC
- Browser: (e.g. Firefox, IE 11): Chrome
- Test User _(if applicable)_:  HDRPSIMPATIENTA,JOANN A (9121)

## Steps to Reproduce
- Test User _(if applicable)_:  HDRPSIMPATIENTA,JOANN A (9121)   
- In Virtual Care Manager (VCM) create future video appointment for a patient
- Log into VAOS and verify appointment is displayed
- Back to VCM and cancel video appointment   
- Expected Response:  VAOS displays future cancelled video appointment 
- Actual Response:   Future video appt is NOT displayed

On past Appointments tab, past VVC appts do not display.  

In VCM I could not find a way to display cancelled Appointments so this may be a limitation of VCM and not the app.  I have reached out to Pam Barbour VCM PM to ask if there is a way to view cancelled appointments in VCM. 

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by marcynadeau** [comment]
@lenaecb I checked with Pam Barbor on VCM team about cancelled VVC appointments.   I asked Pam:   Is there any way in VCM to view cancelled Video Appts? Her response:  No - In VCM the requirement was that cancelled appointments not display.

So this might be the reason that VAOS can't pull them in.

**Comment by lenaecb** [comment]
test @beth-wodzinski @aarathi-poldass can you see this?

**Comment by aarathi-poldass** [comment]
@lenaecb Yes, I can see it. Testing. Thank you!

**Comment by marcynadeau** [comment]
Lenae
This is Marcy and yes I can see this.

**Comment by marcynadeau** [comment]
@lenaecb Was this ticket closed b/c data is not available from VVC?  When I look at the comments, it appears you all were testing emails from Github and so when Aarathi said yes she can see this, she was referring to the email from GitHub not past VVC appointments.  cc @aarathi-poldass
