### ISSUE TITLE
VA.gov landing page

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#12236]
**To do**
- [x] Content is reviewed by ORD
- [x] Content is tested for usability
- [x] Content is reviewed by SMEs on recruiting underrepresented populations (e.g. Kosj and/or Georgetta)
- [x] Content is approved by JTF
- [x] Page is built and published in Drupal
- [ ] `vagov-content` prototype page is retired

**Acceptance criteria:**
- [ ] Not-logged-in user can navigate to a VA.gov page, learn about how to participate in VA COVID-19 research, and take action

**Comment by DanielleThierryUSDSVA** [comment]
Page is https://github.com/department-of-veterans-affairs/vagov-content/blob/master/pages/coronavirus-research.md. Need to delete.
