### ISSUE TITLE
CF: Add data validation to GIDS on VACautionFlag.csv file upload

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12230]
As an EDU team member, I need validation to made aware of potential data issues when uploading the CSV file so that I will know if there are any issues with the data in the file that need to be corrected before publishing a new version.

## Assumptions:
1. This does not affect the MOU, Accreditation Action and HCM caution flags
2. Current "caution_flags" table will continue to be used to reduce impact on vets-website

## Acceptance Criteria
1. The following validation message is displayed on upload of the VACautionFlag.csv file: "Row X: Both settlement title and settlement description are required for the settlement caution flag to be displayed." when one of the following is blank:
    a. "settlement_title"
    b. "settlement_description"
2. The following validation message is displayed on upload of the VACautionFlag.csv file: "Row X: The row has settlement data, but does not have a Title and Description." when the following occurs:
    a. The file contains "settlement_date" OR "settlement_link" data
    b. The file does not contain the "settlement_title" AND "settlement_description" data
3. If there are no settlement values (settlement_title, settlement_description, settlement_date, settlement_link)  in a row, and the row has "School_Closing_Date" OR "Sec_702" data, no validation message is displayed.

## Supporting Artifacts:
1. [va-caution-flags-template.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5042849/va-caution-flags-template-20200805.xlsx)

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/gibct-data-service/709

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/709

**Comment by sonntag-adam** [comment]
Validation messages are backwards and showing "The row has record.settlement data, but does not have a Title and Description." and "Both record.settlement title and record.settlement description are required fo the record.settlement caution flag to be displayed."   "record" needs to be removed.![Screen Shot 2020-08-24 at 3.03.06 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7f5416fd-6f11-4bb0-8915-9e3fe401dbb6)

Moving back to in progress.

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-25 at 11.27.46 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b587ed14-425a-46be-a075-e55a52cd9a00)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/671&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA
