### ISSUE TITLE
CF: Add default text for settlement flags that have links.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12238]
As a comparison tool user, I need to see relevant links provided by the Education Services team for caution flags so that I can make informed decisions about whether to further pursue education at an institution with caution flags.

## Assumptions:
1. Link text for non-settlement caution flags remains unchanged.

## Acceptance Criteria
1. All settlement_links uploaded to GIDS via the VACautionFlag.csv are displayed with the following text on the caution flag card: "Learn more about this cautionary warning"

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
resolved by https://github.com/department-of-veterans-affairs/va.gov-team/issues/11354

**Comment by delli-gatti-michael** [comment]
Looks like the work for this was already done as part of #11354 

@department-of-veterans-affairs/uxbah if you want to review again, the functionality is in staging

The following schools have caution flags that come from the VA Caution Flag file:

https://staging.va.gov/gi-bill-comparison-tool/profile/21801111#viewWarnings
https://staging.va.gov/gi-bill-comparison-tool/profile/21376032#viewWarnings
https://staging.va.gov/gi-bill-comparison-tool/profile/21822411#viewWarnings

**Comment by delli-gatti-michael** [comment]
Tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/936

**Comment by amyknox** [comment]
Looks good to UX.  Close at will.

**Comment by delli-gatti-michael** [comment]
Closing this out
