### ISSUE TITLE
VSP content feedback - How to apply wizards (Edu) 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12243]
## User story

This ticket captures VSP content feedback on How to apply wizards

Links:
EDU: https://staging.va.gov/education/apply-for-education-benefits/application/1990/introduction

## Acceptance criteria

- [x]  VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [ ]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [ ] Teams leaves comments about any feedback they decide not to take
- [ ] Peggy checks form/tool after content feedback has been incorporated

**Comment by leahkeeler** [comment]
Hi @peggygannon - Do you have a high level estimate of when you will have bandwidth for this? I know we have been keeping you busy with debt letters :( 

Thanks! cc @johnhashva

**Comment by peggygannon** [comment]
hi, @leahkeeler Yes, I will be uploading my feedback today. I'm syncing with Danielle and the PW content today about this. want to be sure we're aligned on our feedback.

**Comment by leahkeeler** [comment]
Thank-you so much! You are awesome as always :)

**Comment by peggygannon** [comment]
HI, @leahkeeler Please see below for content feedback on the EDU wizard. I recommend we meet to discuss the users flows that @mnorthuis has mapped out so we can have a better understanding of the content needs. 


**Static pages**( How to Apply page  https://staging.va.gov/education/how-to-apply/ and Education Eligibility page https://staging.va.gov/education/eligibility/)

1. Need to work with the Public Website team on updates to the static EDU How to Apply and Eligibility pages. What content will go on those pages to take users to the wizard? 

2. Need to discuss with the Public Website team if this green CTA wizard button will be replaced by a link of if the the design is for it to still be a button. And if so, is that a lot of  “clicks” for a user to get to the actual form.

3. Need to do an audit of the content on the How to Apply page to ensure it maps to the edu subway map pages. This is account for users who may skip the How to Apply static page and go directly to the wizard. 

4. Discuss with PW team how we are going to update other entry points. There are currently links and buttons throughout VA.gov static pages and tools to the EDU How to Apply and Eligibility static pages.  Should these links now point to the wizard?  

-----

**Wizard page**
1.  There needs to be messaging and content to account for the various flows a user can take from the wizard. (see Mikki’s map of these flows). I recommend we discuss and review these together before I provide content. 
For example, 
--What if a user already knows they DON’T need the 1990 form and they need another EDU form? It might be confusing to them to have to go to the 1990 intro page to start wizard.
--What if a user is routed to a EDU form, but they realize it’s the wrong form and want to go back to wizard? 

2. I also recommend having messaging to inform user about **what** edu form they are being routed to and why.  The flow right now is confusing b/c the wizard starts on the 1990 and depending how the user answers the wizard questions, it could take the users to a different form with a different header. 

3. Suggest green CTA button says “Find your education benefits form”

4. I recommend we add content about eligibility to this page for those users who might bypass the static Eligibility page. For example (not final copy), “Not sure you’re eligible for VA education benefits?” [Learn more about education benefits eligibility](link to https://www.va.gov/education/eligibility/)

6.  Style edit: Apply for VA Education Benefits should be sentence-case

cc @DanielleThierryUSDSVA and @bethpotts

**Comment by peggygannon** [comment]
Closing, as EDU wizard content work is now being tracked in this issue: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13889
