### ISSUE TITLE
Pre-Staging Review Education Form Wizard

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#12249]
## Description
* Several teams are coordinating on benefits wizards, with the first one being related to the education benefits form: https://staging.va.gov/education/apply-for-education-benefits/application/1990/introduction

This spike ticket is to conduct a light touch 508 review ahead of a full staging review.

/cc @leahkeeler @mattpointzxer0 and @johnhashva for awareness. Please feel free to tag others in comments as you see appropriate.

## Related Issues
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/12211

## Additional Notes
This pre-staging review accessibility check will be done quickly, looking for basic automated issues, keyboard navigation, screen reader usability, and will reference @jenstrickland findings from the kickoff meeting.

**Comment by 1Copenut** [comment]
@andreahewitt-odd I'm not sure where we landed on this one. It's probably worth revisiting with the teams working on wizards to see if they're ready for a light-touch review of accessibility.

**Comment by johnhashva** [comment]
@1Copenut and @andreahewitt-odd (with @leahkeeler FYSA)  --  a few of us (Mikki, Peggy, Liz and I) met on Thursday to review IA/Content feedback for Education Wizard (and some of this will apply to other Wizards, including Disability (https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction) and we want to take time to refine some things, so this will slow our launch plan.   Details at the top of this status report > https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/status_reports/status.md

**Comment by 1Copenut** [comment]
@shiragoodman && @johnhashva Circling back on this issue ticket. Are any of the wizards ready for the light-touch 508 review, or are there any related tickets we can relate to this ticket?

**Comment by johnhashva** [comment]
@1Copenut None of the wizards are quite ready -- we have completed work on a UX p[rototype](https://preview.uxpin.com/ca08f3dbf63475b2b62f3e8c00050ad1b19c4cb5#/pages//simulate/no-panels?mode=i) which reflects a series of IA/Content and UX changes we needed to make per IA/Content platform review.   The prototype was shared with the Education and Disability dev teams last week and we are awaiting word back from the PMs as to when that work will be scheduled/completed for staging review.

**Comment by 1Copenut** [comment]
Thank you for the update @johnhashva !

**Comment by jilladams** [comment]
Wizards were launched long ago. Closing.
