### ISSUE TITLE
Remove noindex and basic auth

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#12242]
## Issue Description
Given we've published form detail pages
we want to list the pages under the website's [sitemap](https://www.va.gov/sitemap.xml) and remove basic authentication
so that form pages are available to external indexers.

---
## Tasks

- [ ] Revert https://github.com/department-of-veterans-affairs/devops/pull/7535
    - Implemented basic auth
- [ ] Revert https://github.com/department-of-veterans-affairs/vets-website/pull/14111
    - Excludes form detail pages from the sitemap

## Acceptance Criteria
- All form detail pages are listed under www.va.gov/sitemap.xml
- Form detail pages do **not** require basic authentication to visit

## Questions
- How does Platform rec we handle noindex on Drupal pages? 
    - Answer - they recommend excluding the Drupal page from the sitemap.xml file via a JavaScript line during the website build.

## Considerations
- https://searchengineland.com/google-to-stop-supporting-noindex-directive-in-robots-txt-319003
- check to see how we did this on find va forms - search

**Comment by ncksllvn** [comment]
I think the plan was for us to do this via robots.txt, although we might be able to do it this way instead.

**Comment by MickinSahni** [comment]
just here to start the convo :)

**Comment by ncksllvn** [comment]
Echoing https://github.com/department-of-veterans-affairs/va.gov-team/issues/13125 -

These two PRs will need to be reverted to make form detail pages fully public -

1. https://github.com/department-of-veterans-affairs/vets-website/pull/14111
    - Excludes form detail pages from the sitemap
1. https://github.com/department-of-veterans-affairs/devops/pull/7535
    - Implemented basic auth

**Comment by MickinSahni** [comment]
@jenniferlee-dsva to give the thumbs up when we can do this

**Comment by ncksllvn** [comment]
PRs are open -

- Include in sitemap - https://github.com/department-of-veterans-affairs/vets-website/pull/14466
- Remove basic auth - https://github.com/department-of-veterans-affairs/devops/pull/7709

**Comment by johnhashva** [comment]
@ncksllvn can you confirm we can close this one?

**Comment by ncksllvn** [comment]
Definitely in the sitemap!

![image](https://user-images.githubusercontent.com/1915775/98956836-81887a00-24ce-11eb-801b-ac32e3ad3698.png)

**Comment by johnhashva** [comment]
Thanks @ncksllvn -- will close this ticket.
