### ISSUE TITLE
staging.va.gov:  Past Appointments On the Current Date Not Displaying

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#12260]
@marcynadeau commented on [Fri Aug 07 2020](https://github.com/department-of-veterans-affairs/vets-json-schema/issues/474)

Steps to recreate
1. In VistA create two appointments (in a clinic configured for VAOS)  on the current date for a patients.  One appt for a time that has passed and one for a time in the future.  
2.  Log in to New UI
3.  Expected Response: In Upcoming Appointments tab the future appt displays.  In Past Appointment tab the past appointment displays.  
4.  Actual Response:  In Upcoming Appointments tab the future appt displays.  In Past Appointment tab the past appointment does **NOT** display.  

This is the patient and these are the appointments current time is as indicated below

APPOINTMENTS FOR: HDRPSIMPATIENTA,JOANN   ***-**-9121 PRINTED: 8/7/2020@14:44

Aug 07, 2020 11:20 AM (60 MINUTES) CHY PC CASSIDY       DOES NOT DISPLAY in Past Appts tab.    In VistA the status of this appointment is   Chy Pc Cassidy            08/07/2020@11:20      No Action Taken/Today and this is an appointment that should display with no status shown.  

Aug 07, 2020  2:20 PM (60 MINUTES) CHY PC CASSIDY        DOES DISPLAY IN Upcoming appts tab.  

---

@marcynadeau commented on [Fri Aug 07 2020](https://github.com/department-of-veterans-affairs/vets-json-schema/issues/474#issuecomment-670664158)

@lenaecb I don't know what I might be doing wrong but I could not add labels or select the template or assign to you.

**Comment by lenaecb** [comment]
@jbalboni - looks like this has already been addressed?

**Comment by jbalboni** [comment]
@lenaecb I don't think we did anything to address this, I think there's possibly a gap of 12-24 hours where an appointment disappears from both lists. We need to investigate it.

**Comment by jbalboni** [comment]
@grossb1 We could go over this together in a screen share, but I'm not sure I understand how the code snippet there would address this. It looks like call moment with and without a Date object results in essentially the same time:

![Screen Shot 2020-08-24 at 2.57.31 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/89f795b4-a187-477c-811b-436d7d4fe384)

That code is a little misleading in that `today` and `startOfToday` are the same value, because Moment objects are mutable.

You're definitely in the right spot though, it's something to do with the end date there compared with the start date for future appointments.

**Comment by jbalboni** [comment]
@marcynadeau Do you want to retest this?
