### ISSUE TITLE
[Discovery] Enable Labs to be direct scheduled

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12269]
# Stakeholder input:
## High Level User Story / Problem / Opportunity
As a Veteran who has labs to scheduled at the VA, I want to be able to do this directly in VAOS and get a confirm lab appointment at the end of my VAOS submission. 

With social distancing and limiting the number of Veterans that come into the facility at a time, we are hoping to institute direct scheduling for lab for our Veterans

Stop Code 108 (Labs) set up in VA Online Scheduling for Direct Scheduling

### Business process for Labs (specific to Nevada VA (who is requesting)):
- walk-in process for all labs with the exception of our rural clinics so no one is checking for lab orders until the patient presents now.  This process shouldn’t have an impact on that but will hopefully allow for us to control patient flow with all of the social distancing requirements
- From Chief of Pathology & Laboratory Medicine - "Most place don’t do appointments, so you would need to have the option to turn it on/off or allow for a general appointment with a certain number of patient slots.  As long as you have the option not to use it for particular sites, I am fine with it." 

## Requested from:
- West Haven VAMC (requests)
- Nevada VAMC (direct schedule only)

### Open Questions
- Confirm - is this for requests and direct schedule?
- Do we want to follow existing appt design (provider info, care type, etc)?
- Does anything additional need to supplement a lab such as paper work that should be available in VAOS?
    - Do language for things such as 'none fasting' - instructions to patient
    - check in - using kiosks = "checked in"; "completed in VAOS past appts"  
- Do all VA labs use same stop codes - Y: they should all have the same primary stop code. For LV, just the one primary
   - Standard stop code that all VAMCs use - 108 (specific for lab)
      - For LV - just the appt for the draw
      - these are non-count clinic - just space holder - just 108 is primary
          - confirm secondary code
- send email reminder for 'labs' 
- want to allow for both self-schedule and also request labs appt
   - need to look at resolved statuses
- can cancel lab
- need to vet to have consistency across labs and VAMCs
- do we need a separate work flow for labs?
   - requests: 'reason for appt' probably doesn't apply; or would be 'blood draw' or... for lab

## Goals / Outcomes
- what does success look like - 

## Hypothesis:
- ability to schedule/cancel appts - 10 less veterans                    
- 1 less thing to do after the appt - trying to get veterans more involved and vested in their own care; hand holding
- decrease staff overhead - more tech savvy veterans using this that's one less veteran that's on hold; scheduling piece so much more manageable                  

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## (Optional) Supporting Documentation
_Link to Additional Implementation artifacts- requirements based on policy, data, system-related needs_

**Comment by ldelacosta** [comment]
This ticket is old. We will need to partner with the services team to implement this feature. A new ticket will be created once we decide if we will pick up this work. cc: @JRRoof
