### ISSUE TITLE
Life insurance rewriting batch 3: Content Review

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#12267]
**Issue Description**
Review of batch 3 pages that have been built in Drupal. 
1. PW initial copy editing in Drupal (Randi)
2. DEPO review (Beth)

**[Update your insurance beneficiary](<http://preview-prod.vfs.va.gov/preview?nodeId=5583>)**
- [x] PW copy edit
- [ ] DEPO review

**[VGLI autopay](<http://preview-prod.vfs.va.gov/preview?nodeId=5584>)**
- [x] PW copy edit
- [ ] DEPO review

**[SGLI online enrollment system](<http://preview-prod.vfs.va.gov/preview?nodeId=5585>)**
- [x] PW copy edit
- [ ] DEPO review
 
**[Dividend payment options](<http://preview-prod.vfs.va.gov/preview?nodeId=5587>)**
- [x] PW copy edit
- [x] DEPO review

**[Closed programs](<http://preview-prod.vfs.va.gov/preview?nodeId=5588>)**
- [x] PW copy edit
- [ ] DEPO review

**[SGLI Contact Info for National Guard and Reserve](http://preview-prod.vfs.va.gov/preview?nodeId=6920)**
- [ ] PW copy edit
- [ ] DEPO review

**S-DVI premium rates**
- [ ] PW copy edit
- [ ] DEPO review

**Comment by RLHecht** [comment]
@lwalsh617 I've done a copy edit on all of these and have a few questions:

**Update your insurance beneficiary:** Do we need to define what we mean by a competent Veteran?

**VGLI Auto Pay:** Should the numbered list in the "How do I enroll in VGLI auto pay" be turned into a process list?

**SGLI Online Enrollment System:** Should the numbered list be turned into a process list?

**Dividend payment options:** 
- In Option 2, the and/or is confusing. Do we need to further explain with it's all and when it's one one of the ones listed?

- Do we have a more recent year with interest examples than 2007?

**S-DVI rates:** page not ready for me yet so holding off copyediting

Moving this to validate. Not sure if you want to address these before we icebox it or after.

**Comment by bethpottsVADEPO** [comment]
@RLHecht @lwalsh617 Can you do an assessment of this work and what's left? We got up some of these articles, but what's remaining? And what related tickets are out there? Tag me once you're ready to summarize where everything stands and we can prioritize editing or reworking the remaining articles in upcoming sprints.

**Comment by lwalsh617** [comment]
@bethpottsVADEPO -- Please see attached document for the assessment you requested ^ 
[life-Insurance-restart-v2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7528917/life-Insurance-restart-v2.docx)

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Would like to go through these articles with you to assess whether there are any that we still want to keep in tier 1. When the content team initially worked on this, there was no R&S section. See Laura's doc attached above. Maybe we'll have time in our check-in today.

**Comment by laurwill** [comment]
Closing and continuing this work in new epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49916
