### ISSUE TITLE
Offboarding of Kim Mueller

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#12273]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Kim Mueller
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VSA, Content Writer, Last day 8/10/2020, GovernmentCIO
- Please provide any type of access they may have. 
  > ex: SOCKS, Pagerduty, Google analytics, ect.
  
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Or
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jsev-io** [comment]
Kim Mueller has no AWS accounts in dsvagovcloud, or in dsvasupport.

**Comment by jonwehausen** [comment]
Kim Mueller has no GA or DOMO accounts.

**Comment by jsev-io** [comment]
All Tasks Completed
