### ISSUE TITLE
Review forms library documentation updates

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#12277]
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/349/files

**Comment by meganhkelley** [comment]
Context: https://dsva.slack.com/archives/C862Q82UQ/p1597873675006800

**Comment by taylorkaren** [comment]
The Forms Library Team reviewed this PR on tickets https://github.com/department-of-veterans-affairs/formulate/issues/116 and [https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/formulate/140](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/formulate/140.) and incorporated relevant information into documentation tickets being worked in Q1 2022.
