### ISSUE TITLE
Document title is the same for all Profile sections

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12278]
The `document.title` is identical for all Profile sections. Which makes is hard to make sense of the browser history.

In this screenshot, each item in the list is actually a different section but it's impossible to know which page any entry maps to:
![profile pages in history menu.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/17949278-31e2-4562-9f15-93f83fc7415e)

Perhaps we should have each section update the title with something appropriate?

## AC
Titles should be as follows:
- Personal And Contact Information | Veterans Affairs
- Military Information | Veterans Affairs
- Direct Deposit | Veterans Affairs
- Account Security | Veterans Affairs
- Connected Apps | Veterans Affairs

**Comment by erikphansen** [comment]
@mnorthuis I'm assigning you since I think this might be in your wheelhouse. Feel free to remove yourself.

**Comment by mnorthuis** [comment]
@erikphansen Hi!  Guidelines are title tags are documented here: https://design.va.gov/content-style-guide/seo .  They are typically pulled from the H1, but doesn't look like you have an H1 on the pages?

Title tags for the individual pages of profile should be as below.  
cc: @peggygannon

Personal and Contact Information | Veterans Affairs
Military Information | Veterans Affairs
Direct Deposit | Veterans Affairs
Account Security | Veterans Affairs
Connected Apps | Veterans Affairs

**Comment by erikphansen** [comment]
Should we use Title Case as you called out or sentence case like they appear on the page?

**Comment by erikphansen** [comment]
The `h1` is there (currently not on mobile but we'll fix that) and reads `Your profile`.

**Comment by mnorthuis** [comment]
Title tags should be title case.  I can't visibly see the H1 on desktop either - are they actually displayed on the page?
The H1s should be the actual page title, so they should be updated to reflect these same titles, although H1s are sentence casing.

**Comment by peggygannon** [comment]
@erikphansen I love that you asked that question!
title tags= title case
H1: sentence case

**Comment by jenniferlee-dsva** [comment]
Quick correction - per style guide: https://design.va.gov/content-style-guide/seo#title-tags

Meta title tags - Initial Caps (slightly different - much simpler - than title case)
H1 - sentence case

**Comment by jenniferlee-dsva** [comment]
P.S. The guidance ^ and the character limit is geared toward public -- unauthenticated - pages that come up in organic searches. 

For signed in authenticated pages, I think the character limit of meta titles don't matter -- bc these pages do not come up in searches at all.

**Comment by erikphansen** [comment]
@mnorthuis The H1 should be showing up on Desktop (see screenshot). Making the H1 the subnav heading while the H2 is the section heading was by Jen Strickland's direction. 
<img width="980" alt="Screen Shot 2020-08-10 at 11 29 36 AM" src="https://user-images.githubusercontent.com/20728956/89817538-29239400-dafd-11ea-8283-766c8eccf345.png">

**Comment by mnorthuis** [comment]
Thank you @jenniferlee-dsva for catching that (title versus init caps).  Based on that, I believe there's just one change to the above  - the "And" in the first title should be capitalized.

Personal And Contact Information | Veterans Affairs

Will follow up with @peggygannon and @jenniferlee-dsva  on whether the style guides need any reference to nuanced guidelines for authenticated pages.  We can take that convo offline.

**Comment by mnorthuis** [comment]
@erikphansen do you have what you need for this issue?

**Comment by erikphansen** [comment]
@mnorthuis I believe so. Thanks!

**Comment by erikphansen** [comment]
Gonna remove @mnorthuis from this since all the required info is in this ticket now.

**Comment by erikphansen** [comment]
@mshea0606 can you validate that the page titles for all five sections of Profile 2.0 meet the AC described in this ticket?

**Comment by mshea0606** [comment]
@erikphansen the page titles look good
