### ISSUE TITLE
VSP Content feedback -  Staging review - STEM Scholarship form 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12288]
## User story

This ticket captures VSP content feedback on STEM form 

Staging link: https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction

## Acceptance criteria

- [x]  VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [ ]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [ ] Teams leaves comments about any feedback they decide not to take
- [ ] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
Hello, @amyknox @desireeturner Please see below for VSP content feedback to the STEM form. 

*Feedback key

Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement

------



VSP content review
Breadcrumb: confirming that breadcrumb is correct? doesn't match what is in the I/A ticket

*Consider* the below suggestions to make content more clear: 

1. Add "your" to this:  Determine your eligibility

2. for 2nd bullet point, break it up into two sub-bullets (or two different lines) to make it more clear, readable. 
3. add "degree" to the link at the end of the line


	STEM degree: 	
You're enrolled in a bachelor’s degree program for science, technology, engineering, or math (STEM), 

**or** you have already earned a STEM bachelor’s degree and are pursuing a teaching certification. See eligible [degree] programs

4. add "using all your benefits" to the bullet below

	Remaining entitlement: You've used all of your education benefits or are within 6 months of [using all your benefits] when you submit your application. Check your remaining benefits


------

https://staging.va.gov/education/apply-for-education-benefits/application/10203/benefits/stem-eligibility
1. add a period to end of this sentence: 
None. I’ve used all of my benefit 


--------

*Consider* slight tweaks to language to make this alert more clear. In addition to the icons, maybe add content to make eligibility *really* clear:

**Based on your responses, you may not be eligible**
You responded:
{checkmark} Yes to: Are using or recently used Post-9/11 GI Bill or Fry Scholarship benefits

{no checkmark] No to: Are enrolled in a bachelor’s degree program for science, technology, engineering, or math (STEM), **or** have already earned a STEM bachelor’s degree and are pursuing a teaching certification

{checkmark} Yes to: Have used all of your education benefits or are within 6 months of using all your benefits when you submit your application. 

--------

https://staging.va.gov/education/apply-for-education-benefits/application/10203/personal-information/direct-deposit

1. in this sentence, please change VA to We,
We make payments only through direct deposit, also called electronic funds transfer (EFT). If you’re approved for the Rogers STEM Scholarship, we’ll need to know where to deposit the funds.


global change, please remove 1- before phone numbers (it's OK for the 1- to be in the code, though) 


------

https://staging.va.gov/education/apply-for-education-benefits/application/10203/confirmation

please update this link: More about what happens after you apply update TO: “Learn more about what happens after you apply

**Comment by amyknox** [comment]
Thanks for the great input, @peggygannon. We'll review and let you know if we have any questions.
