### ISSUE TITLE
Audit request flows for design/content consistency for VA, Community Care, & EC requests

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12298]
With changes in feature enablement (turning on/off Community Care and Direct Schedule) and the addition of Express Care request flow, we should do a request flow walk-through for design and content consistency. 

## Acceptance Criteria:
- [x] Review request flows and identify language/content consistency through flows - VA Request, Community Care Request, Express Care Request
- [ ] Identify variations/collect issues for updates needed based on design/content consistency

**Comment by peggygannon** [comment]
@lenaecb @jbalboni Is there a suggested test user I should use to see the CC and direct schedule flow on staging? I'm not able to see those screens and wondering if I should be using a certain sign in to see them.

**Comment by lenaecb** [comment]
@peggygannon - See below for the users/scenarios to test the various flows. 

VA appointment requests - Judy.Morrison should work for any care type and potentially any facility if a request isn't currently open for that on staging

CC appointment requests - Judy.Morrison 
- Care type to select 'Primary Care' then you'll be asked to select VA or CC for appt, select CC and continue request

VA direct schedule - Judy.Morrison
- care type select 'nutrition and food' 
- select VA center
- select DAYTSHR-Dayton VA Medical and then select first selection 'DAYTSHR-Dayton VA Medical Center (Dayton, OH)
- select 'yes' for clinic system selected
- continue with direct schedule flow to completion

Express Care - Judy.Morrison
- Should be able to make a request with limit easily if window is open

**Comment by peggygannon** [comment]
You’ll want to use DS Logon, judy.morrison
7:41
aaAA123!@#

**Comment by peggygannon** [comment]
@lenaecb @rtwell Please see below for content recommendations to CC, Direct, and EC flows, based on my audit. Let me know if you have any questions. We can discuss on our sync on Monday. 

**Community Care flow**

Global change: per recent style decision, community care should no longer be intial caps. 

1. Under Need help footer
Lowercase community care in this sentence: "For help scheduling a VA or community care appointment," 

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/choose-facility-type
2. lowercase community care in these sentences: 
- You’re eligible to see either a VA provider or community care provider for this type of care.
- Go to a Community care facility near your home
- Community care facility

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/community-care-preferences
3. lowercase community care in header. It should be: Tell us your community care preferences
4. lowercase community care in this question: Do you prefer that your community care provider speak a certain language?

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review
5. lowercase Community Care in this header: You’re requesting a community care appointment


-------

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
On main landing page, I recommend  removing "View" from this header, as it implies sightedness "View your upcoming, past, and Express Care appointments" and updating TO:  "Your upcoming, past, and Express Care appointments"

------

**Direct schedule flow**

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/preferred-date
1. Update the content under the helper link TO: 

Tell us the earliest day you’re available and we'll try find the date closest to your request. Please note that we might not be able to find an appointment for that particular day.


https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/select-date
2. update alert on this page to the below to avoid having repeated header and first sentence of alert: 

**Your earliest appointment time**
The earliest we can schedule your appointment is {date} at {time} {a.m./p.m.} {time zone}. 
If this date doesn’t work you can: 
- Submit a request for an earlier appointment, or
- Pick another date from the calendar below, or 
- Call your local VA medical center

2. Please update the sentence on this screen TO: Please choose your preferred date and time for your appointment. Appointment times are displayed in 

3. Also, I'm not sure if this is a potential bug, but from this screen, if my preferred time is OK, I’m unable to hit Continue to move forward. It’s making me click a date again on the calendar below the alert. 


https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review

Please update the message on this screen TO: 

**We’re sorry. Your request didn’t go through**
Something went wrong when we tried to submit your request and you’ll need to start over. Please wait a day to try again, or you can call your medical center to help with your request. 

-------

**Express Care flow**
Express care window times are showing as odd times. Here's the window of time it was showing me: 
This new Express Care option is available today from 1:03 a.m. to 11:10 p.m. MT.

-----

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/audiology

Please fix misspelling in this content. It should be "includes" 
Routine hearing exam
This **incudes** an office visit for a hearing exam and an evaluation using non-invasive tests to check your hearing and inner ear health. A routine exam is not meant for any new or sudden changes with your hearing or ears.

----

https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/choose-eye-care

Please update the content for Optometry and  Ophthalmology to more closely align with our health care taxonomy: 

UPDATE Optometry TO: 
This includes routine eye exams, preventive vision testing and treatment for conditions like glaucoma. Optometrists also can provide prescriptions for eyeglasses and other assistive devices.

 UPDATE Ophthalmology TO: 
You can schedule an appointment with an ophthalmology specialist to diagnose and provide medical and surgical care for conditions that affect your eyes—like cataracts, glaucoma, macular degeneration, and diabetic retinopathy.

**Comment by lenaecb** [comment]
Need to break Peggy's recommendations into separate tickets based on flow (meaning for all CC request changes put in one ticket)
