### ISSUE TITLE
Audit and iterate on current error messages 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12305]
## User story 
Review and update current VA.gov [error messages](https://design.va.gov/patterns/messaging-dictionary) and [error message styleguide](https://design.va.gov/patterns/messaging-error-messages), taking into account mobile standards and best practices. 

Acceptance criteria
- [x]  Peggy and Danielle review current messaging in dictionary and error message styleguide: https://design.va.gov/patterns/messaging-dictionary
https://design.va.gov/patterns/messaging-error-messages
- [x] Identify messages that need updating 
- [ ] Update error message dictionary and styleguide
- [ ]  Share updated resources with product teams building on VA.gov

**Comment by peggygannon** [comment]
Uploading Word docs of the VA.gov Error messages and the Error message styleguide: 

[https://app.zenhub.com/files/133843125/94b59c05-4380-43d8-ba69-d2ba038a7569/download](https://app.zenhub.com/files/133843125/94b59c05-4380-43d8-ba69-d2ba038a7569/download)[https://app.zenhub.com/files/133843125/ffbf7c24-1de2-4e9b-9f41-8a992974f0e8/download](https://app.zenhub.com/files/133843125/ffbf7c24-1de2-4e9b-9f41-8a992974f0e8/download)

**Comment by peggygannon** [comment]
@DanielleThierryUSDSVA Hello, here is the updated error message dictionary with suggested edits. Please let me know if you have any questions. 

[https://app.zenhub.com/files/133843125/2643341a-b915-4e4e-ab52-a74fb724b08e/download](https://app.zenhub.com/files/133843125/2643341a-b915-4e4e-ab52-a74fb724b08e/download)

**Comment by DanielleThierryUSDSVA** [comment]
Restarting effort in separate epic. Closing.
