### ISSUE TITLE
STEM: Address Application Summary UI/Content Issues

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12304]
As a developer, I need to update the form summary page so that it matches DEPO content and design best practices and patterns so that the user has a positive and consistent experience with all forms.

## Assumptions:
1. This work is done behind feature flag #7271.

## Acceptance Criteria
1. The content "These details will help us review your application faster, but aren’t required." in the program details section is not displayed.
2. The padding above the following titles is reduced to 16px.
    a. STEM degree and school details
    b. Direct deposit

## Supporting Artifacts:
1. AC1
<img width="837" alt="school-details-content" src="https://user-images.githubusercontent.com/48260534/89814067-9260d280-db10-11ea-8cd4-bd2708cafbbe.png">
3. AC2
<img width="639" alt="title_excess_padding" src="https://user-images.githubusercontent.com/48260534/89814480-30549d00-db11-11ea-90bb-13db29493d23.png">
4. [Prototype](https://bahdigital.invisionapp.com/share/YFIAEHK8U2W) as of 08/10

**Comment by hughes-dustin** [comment]
branch: bah-12304
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13888

**Comment by delli-gatti-michael** [comment]
AC1
![Screen Shot 2020-08-18 at 12.46.37 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/56f33190-f80a-4b0a-9bc0-23b9d8c85829)

AC2a
![Screen Shot 2020-08-18 at 12.44.54 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2d552063-e126-4670-b1ae-2ab9eab7587d)

AC2b
![Screen Shot 2020-08-18 at 12.05.08 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/96d97c38-313b-4be3-9b76-b11b53272aad)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah this is ready for review on Staging

**Comment by JenLJ** [comment]
@delli-gatti-michael UX has reviewed and this checks out!

**Comment by delli-gatti-michael** [comment]
Closing this issue

**Comment by delli-gatti-michael** [comment]
Tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/929&group_by=cases:section_id&group_order=asc&group_id=51
