### ISSUE TITLE
IA Feedback - Staging Review - STEM Scholarship

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#12307]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description

**Notes**:  This issue describes IA feedback for **the STEM scholarship application only**.  At the time of this review, the static landing page was not implemented, which requires the use of an interim breadcrumb and navigation flow.  Once the static page is launched, changes will be required to update the navigation flow and breadcrumbs.  The implementation of the updated apply wizard will also result in flow and content changes in the near future. 

**MUST**
- Application URL should be:  staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203

**SHOULD**
- Interim breadcrumb (until static STEM page is launched) should be:  `Home > Education and training > How to apply > Apply for the Edith Nourse Rogers STEM Scholarship`. This was decided on in issue #11284.

**CONSIDER**
- Link to "Learn about career counseling options" currently goes to "How to use your benefits page". Is this accurate?

**QUESTIONS** 
- If I want to start over, the only option I have is "Finish application later" and then I have an option to "start over", but that brings me back to /applicant/information not /introduction. Should the user be able to easily get back to /introduction?  This is where the wizard will be eventually...in addition, is there any information on the intro page that a user might need to get back to?

## Definition of Done
- [x] *Must* feedback is implemented on staging
- [x] Decisions on  *Should* and *Consider* feedback and question responses documented in issue
- [x] Issue is closed by VFS team once complete

**Comment by mnorthuis** [comment]
Follow up to the above "Consider" feedback - the link is used across all the education applications, so we will review this separately outside of this work effort and create an issue to address any changes across the forms needed.   

Follow up to the question on the "Finish application later" link - I am deferring this question to the team that is working on the application wizards - as the need may change based on that work,  and it may be a global user flow scenario that we will need to consider.

**Comment by dneel-bah** [comment]
Must and should are covered in: #12156.  Assigning to @amyknox for Consider / Questions.

**Comment by amyknox** [comment]
@dneel-bah - Consider / Questions were resolved by Mikki in her follow-up after the meeting (see below).  This can be closed. 

> Follow up to the above "Consider" feedback - the link is used across all the education applications, so we will review this separately outside of this work effort and create an issue to address any changes across the forms needed.
> 
> Follow up to the question on the "Finish application later" link - I am deferring this question to the team that is working on the application wizards - as the need may change based on that work, and it may be a global user flow scenario that we will need to consider.

**Comment by dneel-bah** [comment]
Must and should have been addressed.
Consider and Questions have been addressed as mentioned in this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12307#issuecomment-672260785
