### ISSUE TITLE
Clone historic 2019 rates page for Pension - Survivors benefits

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#12308]
Current Rates URL: https://www.va.gov/pension/survivors-pension-rates/

Tasks:
- [x] Clone current Pension - Survivors rates page in Drupal. Selina
- [x] Copy over rates from legacy historic page, https://www.benefits.va.gov/PENSION/rates_survivor_pen18.asp
- [x] Copy edit and doublecheck rates and new math examples. Randi

Epic: #10544

## Acceptance Criteria
- [x] Page created in Drupal for 2018 historic rates for Pension and ready for stakeholders

**Comment by lunascoop** [comment]
HI @RLHecht this page is ready for review. http://preview-prod.vfs.va.gov/preview?nodeId=6861

**Comment by RLHecht** [comment]
This page is reviewed and checked. Just waiting on the one outstanding question which @lunascoop and I slacked @bethpottsVADEPO about regarding the year in the Notes section.

**Comment by lunascoop** [comment]
@RLHecht the pages 2018, 2019 and current page have been updated to removed the year from the third bullet point. They are ready for review.

**Comment by RLHecht** [comment]
Thanks, @lunascoop This looks good. Closing this ticket and will continue work with SME approval and publishing in #12403 FYSA @bethpottsVADEPO @MickinSahni
