### ISSUE TITLE
[Development] HLR: Update to HLR Schema Based on Ed's Changes

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12319]
`ratingIssueId`, in the HLR Create payload, is now `ratingIssueReferenceId` [1]

`ratingDecisionIssueId`, in the HLR Create payload, is now `ratingDecisionReferenceId` [1]

all JSON:API datatypes (type field) are now lowercase camelCase: [2]
  `appeals_api_higher_level_review_validation` -> `higherLevelReviewValidation`
  `appeals_api_higher_level_review` -> `higherLevelReview`
  `HigherLevelReview` -> `higherLevelReview`
  `ContestableIssue` -> `contestableIssue`

the show endpoint fields are now camelCase: [3]
  `form_data` -> formData
  `updated_at` ->` updatedAt`
  `created_at` -> `createdAt`

The contestableIssues endpoint is now nested under the specific decisionReview type: [4]
  was:
    `services/appeals/v1/decision_reviews/contestable_issues/`
  is now:
    `services/appeals/v1/decision_reviews/higher_level_reviews/contestable_issues/{benefit_type}`
note: the benefit type is no longer hardcoded to compensation --it must be specified.
The headers are still the same (X-VA-SSN and X-VA-Receipt-Date)

### Why?
[1] changing these fields to match the response from the contestable_issues endpoint. Caseflow uses reference in ID field names to indicate that an ID is for an outside system.
[2] consistency. this is what Fast JSON API gem defaults to
[3] consistency.
[4] is more RESTful and gives us some wiggle room for NOD without jumping a major version

**Comment by luke-gcio** [comment]
Moved to sprint 29.  We had a lot of stuff come from BDD staging review that we added to the sprint in the middle.

**Comment by Mottie** [comment]
Starting work on this today.

**Comment by Mottie** [comment]
Work has been delayed as the updates to be made to the vets-json-schema are still pending. I thought about working from the branch, but since the changes have been blocked, I didn't want to repeat work that would need to be done on the frontend.

**Comment by Mottie** [comment]
In progress, but there isn't much I can do when I have to run everything on branches of vets-api, vets-json-schema & vets-website all at the same time.

**Comment by Mottie** [comment]
FE code has been merged. It won't be usable on staging until the API changes are available.
