### ISSUE TITLE
[Analytics] Direct deposit dashboard: Change the name of the successful submission field 

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12313]
## Background

[Direct deposit dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p176188361/)

We just learned that the "Form Submits for Direct Deposit Information [Total Events]" event field on the direct deposit dashboard reflects forms that were submitted and successfully saved, not just attempted submissions. 

![Screen Shot 2020-08-10 at 3.49.38 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/24d14eac-efa7-458b-82db-b1c248226d73)

Up until this point, I assumed that "Form Submits for Direct Deposit Information [Total Events]" reflected the attempted submissions, but not necessarily the transactions that actually saved. I had thought that in order for us to calculate successful saves, we had to subtract the failed submission number from the submitted number. But, since this isn't the case, we should change the name of the "Form Submits for Direct Deposit Information [Total Events]" heading to something like "Successes in Saving Direct Deposit Information [Total Events]" so it is clearer what that number represents.

## Tasks

- [ ] Confirm that "Form Submits for Direct Deposit Information [Total Events]" is, in fact, successful saves and not just total submissions overall regardless of whether they are successful or not.
- [ ] Change "Form Submits for Direct Deposit Information [Total Events]" to "Successes in Saving Direct Deposit Information [Total Events]"

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 for awareness

**Comment by bsmartin-ep** [comment]
@Samara-Strauss -

Based on what I'm seeing in the code, the `profile-transaction` / ` Profile - Form Submit - Direct Deposit Information` event is firing when the update of Direct Deposit info is **successful** and not on the submission itself.

https://github.com/department-of-veterans-affairs/vets-website/blob/dd54734f805dff6387ca5c0a19f014ecf057efdb/src/applications/personalization/profile360/actions/paymentInformation.js#L124

Dashboard widget title has been updated:
https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p176188361/

**Comment by Samara-Strauss** [comment]
This is perfect. Thank you!
