### ISSUE TITLE
Clarify onboarding docs and va.gov-team access

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#12316]
### What is your documentation request, question, comment, or issue?
When a new user is starting work on VSP, they can follow these onboarding docs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Welcome%20to%20VSP.md

There is another document that explains how to get access to the tools needed: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md

However, the "request access to tools" doc does not seem to be linked from the "Welcome to VSP" doc?

Additionally, [step 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md#github) in the Github section of "request access to tools" is unclear about how to check current permissions.

**Comment by gmaciolek** [comment]
I'll try to take this one on within the next couple weeks. I think that there might even be more docs that discuss getting access to tools than the ones you listed and I'm pretty sure the Working with VSP doc is a little outdated as well. Would be good to do an audit of the various "access tools" docs and clean things up.

**Comment by mchelen-gov** [comment]
@gmaciolek yeah that would be great, thanks! there are quite a lot of tool/system access docs, anything you can do to deduplicate or consolidate them would be really helpful. i'm not sure what all these processes *should* be but maybe we can start by describing how they currently work.

**Comment by gmaciolek** [comment]
@mchelen Update: I looked into this a bit more and I think it's part of a broader problem of orientation docs, slide decks etc. being out of date and out-of-synch. If I start updating this doc, it will turn into a bit of a rabbit hole. It's a rabbit hole I want to explore, but since it will take a bit of time, I need to make sure it aligns with our team's current priorities. I should know more by next week!

**Comment by mchelen-gov** [comment]
@gmaciolek very true, it's quite a lot of interconnected pieces. would it be helpful to either 1) limit scope to one of these docs, updating it as best as possible without touching anything else 2) try to describe & plan the pieces that need to be updated, without trying to modify anything yet
i'll look forward to hearing what you discover, it's definitely a big knot to untangle so any progress or planning around this would be wonderful!

**Comment by gmaciolek** [comment]
@mchelen Update on this one: We have a new PM for our product support team who will be doing research this quarter on the orientation process. I expect them to identify some documentation projects to work on as part of their discovery. I'll put this on our backlog and circle back with them in the latter half of the quarter.

**Comment by mchelen-gov** [comment]
@gmaciolek Great, thanks! Do you know where that team's planning board is?

**Comment by lianilychee** [comment]
Closing this ticket, since the Platform website is the new source of truth for [onboarding information](https://depo-platform-documentation.scrollhelp.site/getting-started/index.html).  Please open another ticket for further onboarding questions!
