### ISSUE TITLE
Analytics Implementation and  QA Support for EDU how to apply wizards 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12317]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA? Potentially both, The how to apply for educational benefits wizard is being migrated from drupal to react. all the current tags have been copied over to teh new pages but I think it needs a fresh review. 

- Who is this request for?

    - [Insert Name(s)] Leah K @leahkeeler John H @johnhashva 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - Bam2 is working with public webites in collaboration 
    
- Provide the Domain where Google Analytics needs to be implemented
    _https://staging.va.gov/education/how-to-apply/ and https://staging.va.gov/education/eligibility/
    
    _Identify if PII is passed in URL or title tag_ no
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here] this is unauthenticated and a client side cookie will keep information for partial searches. 

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - Please note that the tagging currently in place was migrated over from the drupal implementation and needs validation

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @leahkeeler , confirming receipt!

**Comment by leahkeeler** [comment]
Thank-you @jonwehausen - This is kind of a strange one LMK if you have any questions, I can clear them up in a 5 minute convo if needed 👍

**Comment by leahkeeler** [comment]
HI Jon, Can you give me an indication of what sprint y'll can groom this into?

**Comment by joanneesteban** [comment]
@leahkeeler we'll be pulling this into our next sprint, which starts on Thursday.

**Comment by leahkeeler** [comment]
Awesome! Thank-you so much @joanneesteban cc: @johnhashva

**Comment by jonwehausen** [comment]
Sharing preliminary datalayer specification for How To Wizards. This is currently a work in progress.

https://docs.google.com/document/d/1LiJ_C9jGnHdezyGl0yxFtSE1u9MuoJV6H7O2t4gGRpI/edit?usp=sharing

### Goal
- With the expectation that How To wizards will begin to be introduced across modernized VA.gov for several benefit hub How To pages over the coming months, we want to have a dataLayer taxonomy generic enough to be reused across How To Wizards
- Ideally, we can have this code setup as a library (_similar to the forms system_) where this DL code becomes baked-in for future deployments for FE's to take advantage of -- helping to cut down on coordination and completion time for future analytics around these wizards
- Would like to setup meeting with @johnhashva @leahkeeler and other wizard stakeholders to discuss our current taxonomy and how this aligns with future objectives / goals for this initiative
- Also would like to globalize this issue GH ticket to include edu, disability, and the standardization of How To wizards moving forward

cc: @bsmartin-ep @joanneesteban @bmcgrady-ep for visibility

**Comment by leahkeeler** [comment]
CC @craigwheeler

**Comment by jonwehausen** [comment]
Hi @craigwheeler, 

Noticed this was still opened -- could you provide an update on the status here? 

For reference, you can find our full Wizard data layer specification here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md

Thanks in advance

**Comment by leahkeeler** [comment]
@jonwehausen - apologies, we had to put this on hold and focus on finishing and releasing the FSR form - we will pick this up in February likely.

**Comment by jonwehausen** [comment]
Thanks for the notice here @leahkeeler

**Comment by jonwehausen** [comment]
@leahkeeler I know this one has been on hold for a while -- is there still a plan to migrate this how to wizard to be similar to the others? Thanks so much.

**Comment by laurensimpson14** [comment]
@leahkeeler We've pulled this into our current sprint objectives, so we're looking to get this resolved in the next week. Do you have an update or should we move this ticket back to the backlog?

**Comment by joanneesteban** [comment]
@leahkeeler Hi! Any update on this?

**Comment by leahkeeler** [comment]
Good question - not by the debt team, let me check if this was taken over by a different team

**Comment by joanneesteban** [comment]
Thanks, @leahkeeler! Any luck with who owns this now?

**Comment by leahkeeler** [comment]
sorry must have missed - checking with John H. - he will know where it landed

**Comment by johnhashva** [comment]
@leahkeeler + @joanneesteban I actually don't know where this landed.   In effect -- we (Public Web, with Liz Lantz and Mikki and Peggy most heavily involved) -- handed off implementation (including Analytics) to the various teams who manage benefits applications that include How to Apply Wizards.  This, per agreement with @mattpointzxer0 .   Our hand-off included fairly well documented guidance here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/status_reports/implentation_tracker.md

**Comment by joanneesteban** [comment]
Thank you for the quick responses & info, @leahkeeler & @johnhashva ! We might end up backlogging or iceboxing this until this has an owner then.

**Comment by johnhashva** [comment]
@leahkeeler  who is the new PM who works with the team that owns the [22-1990 application](https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction)?

**Comment by joanneesteban** [comment]
@leahkeeler following up on the 22-1990 work. Thanks!

**Comment by joanneesteban** [comment]
@leahkeeler - hi! Double checking: is the new team for 22-1990 led by Gina?

**Comment by laurensimpson14** [comment]
Hi @ERRonat0609 I'm closing this ticket from 2020, but if there is any work you need completed or if you have a question, please feel free to re-open the ticket!
