### ISSUE TITLE
[COGNITION]: STEM Standalone - Information MUST NOT interrupt the normal reading flow unless it is critical or time sensitive

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#12328]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

On Step 5: Personal Information, there is a `div[role="alert"]` that is announcing itself immediately. This caused me a lot of confusion because the information was being read out of context. It wasn't time-sensitive or critical, so I feel it would be better to remove the `role="alert"` and add a `tabIndex="0"` to the container. Screenshot and code snippet below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] The note about bank account information is not read aloud when Step 5 is first announced by screen readers
- [ ] The note about bank account information can receive keyboard focus (has a tabIndex="0" attribute)
- [ ] The note has a yellow focus halo. This is a bit of a departure, but feels right in this case because focus will be driven by the user, not by programmatic focus change.

## Environment
* https://staging.va.gov/education/apply-for-education-benefits/application/10203/personal-information/direct-deposit
* Test user 226

## Possible Fixes (optional)

```diff
<div
  class="vads-u-padding-top--1p5"
- role="alert"
+ tabindex="0"
>
  ...
</div>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

<img width="1116" alt="Screen Shot 2020-08-10 at 4 47 04 PM" src="https://user-images.githubusercontent.com/934879/89835841-23dd3e00-db2b-11ea-8c61-cec794c6fb91.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13812

**Comment by delli-gatti-michael** [comment]
Looks good locally

**Comment by delli-gatti-michael** [comment]
@1Copenut This is in staging and ready for your review

**Comment by 1Copenut** [comment]
I spot-checked this in Staging with Chrome + VO. I'll check it briefly with NVDA and JAWS in a bit.

**Comment by 1Copenut** [comment]
Tested with NVDA and JAWS. No extra information being read aloud. Moving to close.
