### ISSUE TITLE
[Discovery] - Create DRAFT conversation guide for VA.gov sitewide search usability study

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12333]
## Description

Complete the conversation guide for our research study
[Link to Conversation Guide draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/conversation-guide.md)

## Background/Context/Resources

- [Conversation guide ideas doc](https://docs.google.com/document/d/1pbeYiiMViLBTm79Aw7pi9kDDoduM9sF6Tc07iCw_KIQ/edit?usp=sharing)
- [Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

## Tasks
- [x]  Create conversation guide

## Acceptance Criteria
 - [x]  Draft of conversation guide created and uploaded to GH

**Comment by denisecoveyduc** [comment]
@mgleo will add a link to document to collect potential conversation guide questions the team thinks of during conversations.

**Comment by denisecoveyduc** [comment]
@mgleo as discussed I renamed this one to establish a draft of the conversation guide. I also created a ticket for the approvals needed (#16886). Could you please review - edit as needed and check the sizing estimates to ensure they are aligned to the work in each?

**Comment by denisecoveyduc** [comment]
As per discussion with @mgleo changing the estimate to a 5 from 8 since we extracted the PO approval piece.

**Comment by denisecoveyduc** [comment]
@mgleo has created initial draft of conversation guide and is moving to finalizations and gaining approvals. That effort is captured in #16886.
