### ISSUE TITLE
[Discovery] - Create research plan for VA.gov sitewide search usability study

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12331]
As a UX Designer, I need to create a research plan so I can document the research's purpose, goals, hypothesis, and usability testing recruitment needs.

[Research plan folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/search/research)

[Usability study research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/search/research/user-research/research-plan.md)

Our usability study should answer the following questions:
- What are people searching for on VA.gov?
- How effective is VA.gov's search tool at providing the information people are seeking?
- At what point in their visit do Veterans use site search?
- How can search results be improved to improve scanning behavior?
- How do Veterans scan search results?
- Is there a cognitive disconnect and/or issues for folks that the search results use such a tiny font compared to the rest of the site?
- Do people understand the difference between “top recommendations” and the rest of the results and what are their thoughts on that?
- Do people utilize or see “More VA search tools”? (get some data on the right rail)
- How is the search experience different for Veterans across benefit hubs?
- How do Veterans perceive of the search experience on VA.gov?
- What, if any, pain points do Veterans experience when using search?
- How do those painpoints differ from mobile to desktop?
- What, if any, advanced search features do Veterans expect? (refinements, type ahead, etc)
- Where do Veterans look for information if they don't find it via VA.gov search?
- How do you see VA.gov search separate from google?

Tasks
- [x] Create research plan

**Comment by andaleliz** [comment]
Plan in progress https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/search/research/site-search-research-plan.md

**Comment by denisecoveyduc** [comment]
@mgleo completed the creation of research plan for SD team and will proceed to get required approvals( #16822)  before implementing and moving forward with conversation guide (#12333).
