### ISSUE TITLE
508-defect-2 [COGNITION]: STEM Standalone - Heading levels SHOULD only increase by one

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#12339]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The introduction and confirmation pages skip from the H1 to an H4 and H3 respectively. Headings must increase by just one level (H1 to H2 in this case) to ensure maximum usability for screen reader users and better understanding of information importance. Screenshots attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Axe-core best practice warnings for the page headings do not appear any more. Axe may show warnings for the footer H4s, but these are outside the scope of this issue ticket.

## Environment

* https://staging.va.gov/education/apply-for-education-benefits/application/10203/introduction
* https://staging.va.gov/education/apply-for-education-benefits/application/10203/confirmation

## Screenshots or Trace Logs

<img width="1075" alt="Screen Shot 2020-08-10 at 10 01 23 PM" src="https://user-images.githubusercontent.com/934879/89853075-02de1280-db56-11ea-8b6b-c08156a11ebd.png">

---
<img width="1067" alt="Screen Shot 2020-08-10 at 10 02 05 PM" src="https://user-images.githubusercontent.com/934879/89853079-05406c80-db56-11ea-8331-8ba7a678265f.png">

**Comment by desireeturner** [comment]
@amyknox @ccruzgra @JenLJ This looks like a defect that might need some UX input since it is specific to headers. Can you all take a look?

**Comment by ccruzgra** [comment]
@1Copenut I think these are inherited headings. Taking a look at other VA.gov forms, they have the same issue going on. Would that also need to be fixed in the forms system?

**Comment by 1Copenut** [comment]
@ccruzgra Yes, if they're appearing on other forms, these are quite possibly forms system items. I'll reassign to to the right team. Thank you for following up.

**Comment by af-manish** [comment]
@noahgelman  
The links are now: 

https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction
https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/confirmation
