### ISSUE TITLE
Duplicate Feedback button

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#12345]
There are currently 2 feedback buttons on va.gov. need to determine why this is happening and fix it if necessary.

![Screen Shot 2020-08-04 at 3.41.30 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/89d59c41-18c0-4c9d-8668-ad86669d8384)

**Comment by WillMcCormack** [comment]
Can you include the staging URL @delli-gatti-michael ?

**Comment by WillMcCormack** [comment]
@joanneesteban can you take a look at this when you get back in the office next week? The only page that these surveys should appear is: https://staging.va.gov/gi-bill-comparison-tool

**Comment by joanneesteban** [comment]
@WillMcCormack is that Yellow feedback button occurring in Prod and Staging? Or just Staging? We're currently working on adding Medallia surveys in Staging, where this additional Feedback button may incorrectly appear.

**Comment by WillMcCormack** [comment]
@joanneesteban only in staging, this form (STEM: 22-10203) isn't in Production yet.

**Comment by joanneesteban** [comment]
@WillMcCormack - this additional yellow button is a bug that we're working on with Medallia. It shouldn't be appearing in Staging. I haven't been able to recreate this on my end, so let me know if you're experiencing this button after clearing your cache and cookies.

**Comment by WillMcCormack** [comment]
@joanneesteban looks like it is no longer appearing for me either, I will move forward with closing this out.

**Comment by mchelen-gov** [comment]
This is totally irrelevant but congrats on `va.gov-team` issue #12345 :tada:
