### ISSUE TITLE
[COGNTION]: STEM Standalone - CONSIDER removing the opt-out direct deposit message when users have opted in

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#12342]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

When users opt in to direct deposit, there is an empty row for opting out on the form review page. I'd like to consider removing that empty row to remove a potential source of confusion. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] The direct deposit opt-out line "I don't want to use direct deposit" is removed when user has opted in and filled out a checking/savings account number and routing number.

## Environment

* https://staging.va.gov/education/apply-for-education-benefits/application/10203/review-and-submit

## Screenshots or Trace Logs
![Screen Shot 2020-08-10 at 10 18 28 PM](https://user-images.githubusercontent.com/934879/89854373-61f15680-db59-11ea-897b-ae4b8a60c04f.png)

**Comment by desireeturner** [comment]
@amyknox @ccruzgra @JenLJ This bug needs some UX input on implementation. Can you take a look? Thanks!

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13833

**Comment by amyknox** [comment]
Appears to be resolved via https://github.com/department-of-veterans-affairs/vets-website/pull/13833

@desireeturner - can this be closed?

**Comment by delli-gatti-michael** [comment]
Local testing complete


### Test Bank Data Entered
![Screen Shot 2020-08-17 at 3.38.09 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/189ea8aa-b331-4c9c-8e71-c6914962d4fb)

### Opted out
![Screen Shot 2020-08-17 at 3.39.03 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ec5eac26-d22e-4a7b-89fc-c809418c6aa5)

**Comment by delli-gatti-michael** [comment]
@1Copenut the fix for this is on staging and ready for review

**Comment by 1Copenut** [comment]
@delli-gatti-michael Looks 💯 to me. Moving to close.
