### ISSUE TITLE
[COGNITION]: STEM Standalone - CONSIDER revising the optional / required pattern for contacting a user in step 5

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#12341]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Users can select which way they'd like to be contacted regarding their educational benefits. Sometimes this can lead to a situation where a previously optional field becomes required. I'd like to consider revising this pattern. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Users have a clear understanding of the required fields, and the relationship between values added for home and mobile phone, and the contact you radio group.

## Environment

* https://staging.va.gov/education/apply-for-education-benefits/application/10203/personal-information/contact-information

## WCAG Guidance (optional)
* [Labels and Instructions](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html)

## Screenshots or Trace Logs

![Screen Shot 2020-08-10 at 4 34 56 PM](https://user-images.githubusercontent.com/934879/89854074-8dc00c80-db58-11ea-9dea-d34b692adffa.png)

**Comment by desireeturner** [comment]
@amyknox @ccruzgra @JenLJ This bug needs some UX input on implementation. Can you take a look? Thanks!

**Comment by desireeturner** [comment]
@1Copenut We've looked into this issue and have determined that this functionality is also part of the forms system (this is how the form system works for `ui:required` fields). Is this another one you can pass along for the platform team to review?

**Comment by 1Copenut** [comment]
@meganhkelley && @rianfowler The BAH team asked me to have y'all take a look at this one. There's an interesting situation where non-required fields could become required based on how users answer questions about contact preference. LMK if you want to discuss further and we can sync up.

**Comment by af-manish** [comment]
@naomimarcussen Can you let us know how we want to handle this scenario? It just gives a suggestion, but we need to know exact requirements.

**Comment by nbarthelemy** [comment]
After reviewing the ticket with @dan-brooking, he and II believe the this form functions exactly as described in option 1 of @GnatalieH 's comment above. I would suggest that this ticket be validated, but at this point it seems to function as desired.

**Comment by hallihocine** [comment]
Ticket has been validated in staging and prod: it works as expected (as described in option 1 by @GnatalieH ): Display a (*Required) label displayed next to whatever communication preference is selected. If the user changes their selection from Home phone to Mobile phone, display the (*Required) label next to the Mobile phone number field and hide it on the Home phone number field.
See below: 

https://user-images.githubusercontent.com/86266024/149410950-fccf5779-a078-408c-925e-5efb9445cfbb.mov

**Comment by hallihocine** [comment]
### **Screenshots**
1. 
<img width="851" alt="Screen Shot 2022-01-13 at 3 08 52 PM" src="https://user-images.githubusercontent.com/86266024/149411077-f9382c87-0dd7-458d-9bd9-77d1f4d80b85.png">

2.
<img width="772" alt="Screen Shot 2022-01-13 at 3 09 11 PM" src="https://user-images.githubusercontent.com/86266024/149411130-df9b4135-e231-48c2-8922-900cee5ecc27.png">

**Comment by mrblanco1** [comment]
Conducted UAT Demo to EDU on 1/20/2022 - Passed and approved by Joe P.
