### ISSUE TITLE
Profile mobile sub nav sits above main site nav

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12346]
On mobile, the Profile sub nav sits on a layer about the site's main nav. It should be on an z-index below the main nav.

![menu-layers.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/18187ee5-2633-4bf9-a239-9393c2b0cf2c)

I don't know off the top of my head how the z-indexes are managed.

**Comment by erikphansen** [comment]
The PR is still pending.

**Comment by erikphansen** [comment]
@mshea0606 can you validate that the Profile 2.0 subnav no longer appears _above_ the site's main nav as shown in this ticket's GIF?

**Comment by mshea0606** [comment]
@erikphansen sure, checking this now

**Comment by mshea0606** [comment]
looks good!
