### ISSUE TITLE
Connected apps GA Dashboard for Profile 2.0

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#12351]
# Google Analytics Implementation or QA Request

As discussed @bmcgrady-ep , we need to build some additional GA Dashboards for Profile 2.0

From [Analytics needs for Profile 2.0
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/analytics/Analytics%20needs%20for%20profile%202.0.md)

### Connected apps dashboard

- How many users have apps connected
- How many users disconnect apps from here
- Clicks of "Go to connected accounts FAQ"
- Clicks of "Full list of possible applications"

Don't forget about or [Profile 2.0 Gap Analysis](https://docs.google.com/document/d/1Op-v4h7nGOo7Jb4uU7B8O6D4y5GN0Qkar3u5K4ZZlqw/edit).

------------

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Closing per GA dashboard completion + auth experience KPI dashboard
