### ISSUE TITLE
STEM: Add GA tracking to SCO email links

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12359]
As a developer, I need to update the URLS contained within the SCO email to contain GA trackers so that we understand if recipients are using the links.

## Assumptions:
1. This work is currently behind the feature flag implemented in #12467 (`stem_sco_email`)

## Acceptance Criteria
1. The "Programs approved for STEM Scholarship" link is: https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf?utm_source=confirmation_email&utm_medium=email&utm_campaign=stem_approved_programs
2. The "Privacy Policy" link is: http://va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction#privacy_policy/?utm_source=confirmation_email&utm_medium=email&utm_campaign=privacy_policy

## Supporting Artifacts:
1. [SCO Email with GA Updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5203284/SCO.Email.with.GA.Updates.docx)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4904

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-16 at 8.12.40 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/331cca84-217b-45cc-84e7-a8e34528c15c)
##
![Screen Shot 2020-09-16 at 8.13.00 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/312c2ac1-7910-43cf-b00f-e369b45d564d)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/12561&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
In staging. Closing story.
