### ISSUE TITLE
Account Security GA Dashboard for Profile 2.0

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#12350]
# Google Analytics Implementation or QA Request

As discussed @bmcgrady-ep , we need to build some additional GA Dashboard for Profile 2.0

From [Analytics needs for Profile 2.0
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/analytics/Analytics%20needs%20for%20profile%202.0.md)

### Account security dashboard

- Clicks of Verify your identity
- Clicks of Set up 2-factor authentication
- Clicks of Go to the terms and conditions for health tools
- Clicks of "Go to VA.gov FAQ"

Don't forget about or [Profile 2.0 Gap Analysis](https://docs.google.com/document/d/1Op-v4h7nGOo7Jb4uU7B8O6D4y5GN0Qkar3u5K4ZZlqw/edit).

------------

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bmcgrady-ep** [comment]
This is now staged in Non-Prod. Here is the [link](https://analytics.google.com/analytics/web/#/dashboard/fybwEuuTRCmaQjsUVDBGJA/a50123418w178298118p176884211/) to the dashboard.

**Comment by jonwehausen** [comment]
@bmcgrady-ep verified dashboard is publicly shared in the production property. Closing
