### ISSUE TITLE
[Design] Create first draft of "Grey Sky" Product Health Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1236]
## User Story
As an Insights team member and stakeholder, I need to understand what the Product Health Tool will look like so I can prioritize the data that will be needed and run through platforms that the tool can live on.

## Goal
Create first draft of the "Grey Sky" Product Health Tool.

## Acceptance Criteria
- [x] Document data criteria for "Grey Sky" tool
- [x] Design first 'paper' draft of Grey Sky tool
- [x] _Stretch_ Add real data to draft

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amycesal** [comment]
![Grey Sky](https://user-images.githubusercontent.com/1656046/65987308-2ec73c80-e44b-11e9-8ba0-d4f961a032b7.png)

**Comment by joanneesteban** [comment]
All AC met for this. Thank you @amycesal for your work with this!

**Comment by amycesal** [comment]
![Grey Sky](https://user-images.githubusercontent.com/1656046/66149858-957a6080-e5d9-11e9-9d84-0e6cabfa5db8.png)

**Comment by amycesal** [comment]
A couple of label updates after a test run with Emily
![Grey Sky](https://user-images.githubusercontent.com/1656046/66323109-e85d5c00-e8e8-11e9-9980-931c255df849.png)

**Comment by amycesal** [comment]
![Grey Sky](https://user-images.githubusercontent.com/1656046/66419852-68a7be00-e9ca-11e9-9b87-cee86407fa84.png)

**Comment by amycesal** [comment]
![Grey Sky](https://user-images.githubusercontent.com/1656046/66585429-6bcab780-eb4c-11e9-9e1b-218c0413bbaa.png)

**Comment by amycesal** [comment]
![Grey Sky copy](https://user-images.githubusercontent.com/1656046/66852474-aa90b100-ef42-11e9-9174-8b3bd02a2de2.png)
