### ISSUE TITLE
[Spike] authenticated and whitelisted experience

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#12360]
Research what "I appears they have a list of approved users." from Sprint Demo - Micah Chiang 

## Acceptance Critieria
- [ ] Findings in the [Tech Feas Doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/engineering)

**Comment by mdewey** [comment]
Added comments here after a quick meeting with Micah 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/engineering#user-whitelist
