### ISSUE TITLE
School Ratings: Research and Design CSV to support school ratings details

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12362]
As a developer, I need to research and design the CSV that will support the loading of school ratings information that is displayed within the comparison tool.

## Assumptions:
1. A veteran will be prompted by an automated process to provide a rating for an institution.
2. A veteran may be prompted to rate an institution multiple times, if so, only the most recent rating is counted.
3. A veteran may rate multiple institutions

## Acceptance Criteria
1. Documentation is created that outlines the fields in the CSV, their data types, and whether they are required or not.
2. If there is functionality in the prototype that cannot be supported, it is documented.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/9TIAEOA3AJ7#/screens/296045901) as of 08/11

**Comment by dmccurdybah** [comment]
## Institution Ranking CSV Import

### Columns
- `ranker_id` (`string`)
  - The format of this isn't known, so `string` gives us the most flexibility.
- `facility_code` (`string`)
- `overall_experience` (`int`)
  - The rating columns can be a value of 1 to 5 stars with `null` or `0` being treated as a "N/A" rating.  Anything over a 5 will be treated as a 5.
- `quality_of_classes` (`int`)
- `online_instruction` (`int`)
- `job_preparation` (`int`)
- `gi_bill_support` (`int`)
- `veteran_community` (`int`)
- `marketing_practices` (`int`)
- `ranked_on` (`datetime`)
  - rankers can rank institutions more than once, and this will be used to make sure we're only counting their most recent ranking.
