### ISSUE TITLE
Update the formation-react publishing documentation

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#12363]
## Background
I recently published a new version of `formation-react`. When I got to the "Create a release" step of [the documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/updating-formation/), the `yarn release` script threw a syntax error.

After talking with some folks, it sounds like this may have never worked.

I ended up skipping that step and it seemed to work fine.

## Task
- [ ] Update [the documentation](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/documentation/src/pages/getting-started/common-tasks/updating-formation.mdx) to remove the "Create a release" step

**Comment by k80bowman** [comment]
Closing, as formation-react is no longer in use.
