### ISSUE TITLE
Iteration 1: Build the FE template for Step-by-step, Multiple FAQs, and single QA learning center content types

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#12365]
## Iteration 1: Build the FE template for Step-by-step, Multiple FAQs, and single QA learning center content types

The FE build for iteration 1 is to start mapping the middle layer of the templates, based on Ryan's designs and the template requirements. 

**The 3 CMS templates for this ticket are:**

- Single Q/A
- Multiple Q/A
- Step-by-step

_Note: The CMS templates currently **don't** include the sandwich bread layers:_

- Tags taxonomy
- Need more help
- Was this useful
- Related info/articles

**There are some global template elements that will eventually need to be built for all or most of the templates:**
- breadcrumb
- in-body alerts
- TOC links logic
- Back to top page height driven logic
- _There may be other global FE template elements that I'm not including here, and that you may want to triage to include with this work or to break out later as separate work._ 

**Design mocks:**
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files

**Global template requirements:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md

**Content type template requirements:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#specific-lc-content-template-types

---
## Tasks
- [ ] breakdown components in this ticket

## Acceptance criteria
- Frontend templates built for Step-by-step, Multiple FAQs, and single QA learning center content types
- Can be validated by previewing in CMS
  - don't include the sandwich bread layers from above (until these are ready - we can create a separate ticket when they are)

--------------

**Related tickets:**
[Enter sample LC content in CMS, so FE engineers have something to test FE template work](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12066)

[Learning Center CMS devshop environment for FE engineers](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2561)

--- 

Open question
- [x] should we breakdown this ticket further?
  - Yes

**Comment by MickinSahni** [comment]
@ncksllvn @kelsonic to groom this sprint (28)

**Comment by jenniferlee-dsva** [comment]
Hi @MickinSahni - I clarified AC in the original ticket description ^.

**Comment by MickinSahni** [comment]
@ncksllvn @kelsonic they are 3 separate templates mentioned here. Let's consider breaking this out into 3 separate tickets within this epic.

**Comment by ncksllvn** [comment]
Should [About](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-About.png) be included here as well? I see it included in this comment, https://github.com/department-of-veterans-affairs/va.gov-team/issues/11435#issuecomment-683972811

**Comment by jenniferlee-dsva** [comment]
The About template is not yet ready in the CMS.

**Comment by MickinSahni** [comment]
hey @brianalloyd unassigned myself but think this can be closed?

**Comment by brianalloyd** [comment]
Thanks Mickin, concur closing now.
