### ISSUE TITLE
[Front End] Update for Covid alert 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12370]
Per Peggy, the COVID alert was not approved, it needs to be updated to suggested alert box found here https://github.com/department-of-veterans-affairs/va.gov-team/issues/11935 

Please ping @rileyorr @rebeccawalsh one complete so they can review

**Comment by leahkeeler** [comment]
This is still under review -- please wait on this tix until a final decision is made

**Comment by rileyorr** [comment]
Peggy's approved [the alert's final design](https://preview.uxpin.com/8019d7c491dc05231e456a666928bd6a5ca40e6e#/pages/130777997/simulate/sitemap?mode=i). I've sent it over to Brad & he's already working on it :)
