### ISSUE TITLE
[Development] 526: MVI Errors Logged to PII Friendly Table

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12376]
## Issue Description
We need more info on why MVI Add Person is occasionally failing.  it may be part of the "orchestrated" lookup (deeper search beyond the local MPI database).  Since we cannot log the body of the response (contains PII) we need to use something other than Sentry to log.  The PII table in our Postgres database.

## Acceptance Criteria
- [ ] Production-level logging to the PII friendly table so we can see the MPI error response body
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
progress in https://github.com/department-of-veterans-affairs/vets-api/compare/aec/mvi_logs?expand=1 bug putting this down for a while to look at BDD stuff

**Comment by annaswims** [comment]
this PR is ready for review https://github.com/department-of-veterans-affairs/vets-api/pull/4804.  I realized that we may not actually need to log PII if we log the exception details. 🤞 We'll see if this is enough.
