### ISSUE TITLE
Access for Nathan Wright

### ISSUE THREAD

**Issue by nathanbwright** [department-of-veterans-affairs/va.gov-team#12379]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Nathan Wright
- Please Provide your email.
   > nathan.wright@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Interro!
   > Role: Backend Engineer
   > Company: Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDxosfPjOMJZDJC4n9tjGMw7HzzK7BVxdUY8a8PZYdVIYR+O/waA7J4yL/2xrd81FyBr6pJfHlc0sfOZLD62YKaTrtKzkWhwfTJoW/8wjyu/uZAGKdho5L4/TQCjNxjl61u3w0G8Mf+lPJUcyDU+4//ytklMuarIKCemOUdEVi8oKgXbMpbuzQDtyMdipAUtsQJLB/RFRdTOWe7pBjrRXYlsnSJGTWsZG85HFLbgKF3lMpkiHubL7uOcl5J2NNoGVChhUB1FET0H42JWkjyxMK9L1uuOCs3gLf/uToYp1gFBosidkud9NJ/zLd8kDc0YAiRuz93kpEB5S642DwN94PV nathan.wright@oddball.io
```

- Grant AWS Console access?
  > YES
  - Need AWS Console access for developing and maintaining the Lighthouse dev portal.

**Comment by nathanbwright** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@nathanbwright Please verify you've got access to the socks proxy

**Comment by jsev-io** [comment]
cc: @Jeff-Hayter requesting approval for AWS access

**Comment by nathanbwright** [comment]
@jsev-io - I now have access to the socks proxy. Thank you!

**Comment by jsev-io** [comment]
AWS Access has been granted.
