### ISSUE TITLE
[FE] Add 'I live on a United States military base outside of the country.' checkbox to the Home address

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#12374]
## Background

We noticed an inconsistency between addresses. We need to add the 'I live on a United States military base outside of the country.' checkbox to the Home address section of the Personal and contact information section.

## Specs

![Screen Shot 2020-08-11 at 2.11.52 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b1a20534-4c47-4be0-b2bb-75562aaa7aef)

## Tasks

- [ ] Checkbox has been added

**Comment by mshea0606** [comment]
@sanlouise looks good!
