### ISSUE TITLE
Review Content ROE with VAOS Team

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1237]
### User story
As the new VAOS (VA Online Scheduling) VFS Team, I need to know what's expected of my team in terms of the content that wee create for our tool, and what we can expect from VSP, so that we can move fwd efficiently and so that Veterans can easily find and interact with our tool.

### Goal
Collaborate with the Product Support team, and do whatever's necessary to proactively incorporate "content" into VAOS's onboarding experience effectively, so they come away achieving the user story above.

### Definition of done

- [x] Meet with appropriate VAOS team members to go over content best practices
- [x] Meet with VAOS PM(s) to go over Content Review ROE (Rules of Engagement)
- [x] Document findings and feedback from that meeting to recommend for doc iteration

**Comment by rroueche** [comment]
@peggygannon note I added another checkbox item to the Definition of Done for this one - let Megan or I know if there's any concern!

**Comment by peggygannon** [comment]
**9/3/19 update** Meeting with Mark Greenburg scheduled for 9/4

**Comment by peggygannon** [comment]
Closing. This is complete. Meeting with Mark and Ryan happened on 9/4/19.
