### ISSUE TITLE
Create Authenication diagram

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#12372]
As per our conversion with Paul Short, create a current state diagram for the Vets API authentication schema.  This diagram should also include the plans and strategy to add a new authentication schema; specifically the Lighthouse API authentication (OpenId Connect) 

## Acceptance Criteria
- [x] Diagram of the current state
- [x] Diagram with new authentication strategy added

**Comment by mdewey** [comment]
Initial RequestL

**Comment by mdewey** [comment]
Initial Request from Paul : 
```
Paul Short  6:57 PM
Hi... during last week's customer-facing VSA Leadership Sync (where Andre, Luke, Yana, Mickin, Shawna, and I brief our VA Product Line Manager, Chris Johnston), Chris showed quite a bit of interest in the status for the HealthCare team's integration efforts with Lighthouse. He gave us a quick oral history which indicates that this would be va.gov's 4th type of authentication to external services (Lighthouse "on octa," ID.me, a one-off for myHealth-eVet, and now this) so he put me (us) in touch with Corey Trimm, the USDS (gov't side) engineer who knows about these integrations. That is why he'll be involved, which I believe is a great thing. (edited) 






Paul Short  7:02 PM
ALSO, Chris Johnston specially asked for and suggested a diagram for this--since it was a great suggestion from the customer, I committed to doing that. I will work with this team on getting it done. I'm open to delegation, collaboration, or even hands-on depending on y'all's comfort level with this request. I did go through some SSOe and auth diagrams prepared by the platform team last month, so I'd like to dig those up, see what you think (but not get too sidetracked since some of those complex details may not matter in our situation.)
```

**Comment by mdewey** [comment]
After days of researching, I found the following interesting documentations: 

- [existing VA auth diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login/reference-documents/auth/authentication-and-authorization.md)
- [Login Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/login)
- [understanding identity](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login/gettingstartedidentity.md)

I created a doc aimed to help guide discovery here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/auth-diagrams-notes/READMDE.md#L10

Not sure what the next steps are. 

Tagging @abuckley3385  and @short000 for next steps

**Comment by abuckley3385** [comment]
@short000 I'd like to mark this complete for the sprint - have you had a chance to review Mark's diagram.  Im good with the doc.
