### ISSUE TITLE
Access for Edwin Otero 

### ISSUE THREAD

**Issue by ediiotero** [department-of-veterans-affairs/va.gov-team#12377]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Edwin Otero
- Please Provide your email.
   > eddie.otero@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >Interro, Back-end engineer, Oddball

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuKAgn1Nrvx0INgePCmIRRN8EQkkzCaP7Iqx0c2O9afZzUm4v2A22SOxRK9P8MckU0GAhMncDM8pFuZyUPu+ViDK2mlRS97Q4ipnhQCHtOW+00UbHd4U3L2F1NyLB7y86Ne0OCtXAUb69GXIf3njJSi6Eiu+0hJSbfW0uT4m2pnV4h6lytuSP3iTztknK2Vd/0bpYN1Vfz+f71I6a+wxtkPaU/vfmafpuXS7kPZB1frhDYcZaGAnEMhMm2AoOaGbm7t7PoPYPV9xmNuFU88LpM0YY39AtuEkiF3zYHpntp7+8TDSqtojP8V4lyqE2JRRVUsTXZG872J5xF8VeEAwZh eoter@DESKTOP-NEB8O84
```

- Grant AWS Console access?
  > YES
  - for development purposes and need access to Jenkins, Grafana, and Sentry

**Comment by jsev-io** [comment]
@ediiotero Please verify you've got access to the socks proxy

**Comment by jsev-io** [comment]
cc: @Jeff-Hayter requesting approval for AWS access

**Comment by jsev-io** [comment]
AWS Access has been granted.
