### ISSUE TITLE
Access for Michael Kimball

### ISSUE THREAD

**Issue by michaelkimball** [department-of-veterans-affairs/va.gov-team#12371]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Michael Kimball
- Please Provide your email.
   > michael.kimball@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Interro! | Role: Backend Engineer | Company: Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4lCAH186g/cVU+6PRndllsM7uVtHmCWbhoDxL7pLujz6Kha0NYSr4PiPt+7voQfUYyGSjjWt8gA25NsoG38eHwIca0LoJzHUcVsq7Jdwyp95Kg8vHN6kGscqzcYumu7JK8fhmViokmifAZfb9lRxzf9Ov28yw3ayRdOpntC6Mle9fIDeWpuQd5277xEQldOX54y6D79L7sUVYH1ecPVAgC5G8pTXne3LEbXnhk70Fb2yVArzKPXcOgVpPeFYPJIYD3wuUPVXJSdGe5bVNHNvfAcPwSm0N16IpwBTdA96iyb+Mc1Zv6tLdzHiW9aEulGVBtXN9hRwRhVFMMIEMp77tGkeSaFQxTU+a+KoC9Ppcv0qMRvvkedCgPBT8xUBdyhdobxUZMTZReHbeQXtkBwui2fDBAtNwtn9noqq4TO7cGAsgyNlYkHhslvajiMl+3ag2Cpv7hkQGVGBLTkQwhWXnQi9sXBMcYo7juKIb6l3/8TqQEjct7Ukekjik8sWp5JKidrhcUiZ9uWj8v96Y+qpgEiEMfESHWfyhxF4C4w64IaWvvPhMPhvnyIQZ0CsrBpqkFw/8/ZuwSo33n6FkT4QB7bLYye0xQboOX1FAUuyUHeCLOceGmUk5c9SBM/FhcqLWV9id3T6WTHtDjXckvI5CoieNxBvp+vXnnXMkAxJpdw== michael.kimball@oddball.io
```

- Grant AWS Console access?
  > YES
  - As a backend engineer I need to be able to view the results of PR builds as well as make Kong configuration changes and a number of other DevOps focused investigatory tasks.

**Comment by jsev-io** [comment]
@michaelkimball Please verify you've got access to the socks proxy

**Comment by jsev-io** [comment]
cc: @Jeff-Hayter requesting approval for AWS access

**Comment by michaelkimball** [comment]
I have SOCKS proxy access

**Comment by michaelkimball** [comment]
Still need AWS Access. If it's possible, I also need access to the Parameter Store

**Comment by jsev-io** [comment]
AWS Access has been granted.
