### ISSUE TITLE
VSP content feedback - Staging review - Debt Letters MVP

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12378]
## User story

This ticket captures VSP content feedback on Debt Letters tool 

Staging link: https://staging.va.gov/manage-va-debt/your-debt/
Team: BAM 2

Product/Tool/Form: Debt Letters MVP

Collaboration stage: Staging review

Is there a static landing page that supports this product/tool/form? Y

## Acceptance criteria

- [x]  VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x] Teams leaves comments about any feedback they decide not to take
- [x] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
Team: BAM 2

Product/Tool/Form: Debt Letters MVP

Collaboration stage: Staging review

Is there a static landing page that supports this product/tool/form? Y

------

Content feedback
*Feedback key

Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement

**Comment by leahkeeler** [comment]
Thank-you @peggygannon. We were awaiting feedback from SMEs at DMC on the "Why might.. " they have until eod tomorrow to come back with feedback. The content is below: 

'Why might I have this debt?' content
30 - Compensation & pension debt
A letter was sent from the Compensation & Pension office to your address on file explaining the reason for this debt.  Some common reasons for this type of debt are:
A change in dependency was not submitted or processed before a payment was made to you
An adjustment for drill pay
A change in eligibility for the benefit
A duplicate or erroneous payment
If you want more information about the reason for this debt, please call the DMC at 800-827-0648.

41, 44 - Chapter 34 education debt, Chapter 35 education debt
A letter was sent from the Education office to your address on file explaining the reason for this debt.  Some common reasons for this type of debt are:
A change in course enrollment
Withdrawal from a higher education institution
A change in eligibility for the benefit
A duplicate or erroneous payment
If you want more information about the reason for this debt, please call the Education office at 888-442-4551. 

71, 72, 74, 75 - Post-9/11 GI Bill debt for books and supplies, Post-9/11 GI Bill debt for housing, Post-9/11 GI Bill debt for tuition, Post-9/11 GI Bill for tuition (school liable)
A letter was sent from the Education office to your address on file explaining the reason for this debt.  Some common reasons for this type of debt are:
A change in course enrollment
Withdrawal from the higher education institution
A change in eligibility for the benefit
A duplicate or erroneous payment
Note: For Post-9/11 GI Bill debts, three separate payments are made for tuition, housing, and books and supplies. When there is a change in this benefit’s use, the VA will collect the three debts separately.

If you want more information about the reason for this debt, please call the Education office at 888-442-4551. 

If there are any edits from SMEs we will update and then do we need to open up a separate ticket to have reviewed? 
Thanks! Leah

**Comment by rebeccawalsh** [comment]
@peggygannon here is the updated content with SME feedback -- tear it apart!

### 'Why might I have this debt?' content

**30 - Compensation & pension debt**
A letter was sent from the Compensation & Pension office to your address on file explaining the reason for this debt.  Some common reasons for this type of debt are:
- A change in spouse or dependents was not submitted or processed before a payment was made to you, **or**
- An adjustment for drill pay, **or**
- A change in eligibility for the benefit, **or**
- A duplicate or erroneous payment

If you want more information about the reason for this debt or the decision resulting in this debt, please call 800-827-1000 for disability compensation or 877-294-6380 for pension.

If you want more information about the debt overpayment and available options, please call the DMC at 800-827-0648.

---
**41, 44 - Chapter 34 education debt, Chapter 35 education debt**
A letter was sent from the Education office to your address on file explaining the reason for this debt.  Some common reasons for this type of debt are:

- A change in course enrollment, **or**
- Withdrawal from a higher education institution, **or**
- A change in eligibility for the benefit, **or**
- A duplicate or erroneous payment

 If you want more information about the reason for this debt or the decision resulting in this debt, please call the Education office at 888-442-4551. 

If you want more information about the debt overpayment and available options, please call the DMC at 800-827-0648.

---

**71, 72, 74, 75 - Post-9/11 GI Bill debt for books and supplies, Post-9/11 GI Bill debt for housing, Post-9/11 GI Bill debt for tuition, Post-9/11 GI Bill debt for tuition (school liable)**
A letter was sent from the Education office to your address on file explaining the reason for this debt.  Some common reasons for this type of debt are:

- A change in course enrollment, **or**
- Withdrawal from the higher education institution, **or**
- A change in eligibility for the benefit, **or**
- A duplicate or erroneous payment

Note: For Post-9/11 GI Bill debts, three separate payments are made for tuition, housing, and books and supplies. When there is a change in this benefit’s use, the VA will collect the three debts separately.

If you want more information about the reason for this debt or the decision resulting in this debt, please call the Education office at 888-442-4551. 

If you want more information about the debt overpayment and available options, please call the DMC at 800-827-0648.

**Comment by peggygannon** [comment]
@rebeccawalsh Here you go. My edits to the "why might I have this debt" content
Please let me know if you have any questions. The document shows track changes in case you need to share with SME? 


cc @leahkeeler 

[https://app.zenhub.com/files/133843125/f56c66a7-a715-4bfa-adf7-68a695621a93/download](https://app.zenhub.com/files/133843125/f56c66a7-a715-4bfa-adf7-68a695621a93/download)

**Comment by rileyorr** [comment]
Hi @peggygannon! Thank you for providing these content updates :) 

I have a question about some content in the "Why might I have this debt?" Word doc:

> Note:  For Post-9/11 GI Bill debts, please make separate payments for tuition, housing, and books and supplies. When there is a change in this benefit’s use, we’ll collect the three debts separately.

Do the asterisks indicate that 'Note:' should be bolded? Just wanna double-check because other words in the document are bolded, but this one has asterisks around it.

**Comment by peggygannon** [comment]
Hi, @rileyorr Hello! Yes, the **Note:** should be bolded.  thank you for checking!

**Comment by bradl3yC** [comment]
This is ready to be validated in staging

**Comment by peggygannon** [comment]
thank you @bradl3yC I will take a look.

**Comment by peggygannon** [comment]
@bradl3yC @rebeccawalsh @rileyorr I noticed on staging two places where we're missing a period at the end of sentences. 

Two examples below: 
1. We're missing a period after the phone number: 

*If you want more information about the reason for this debt or the decision resulting in this debt, please call the Education office at 888-442-4551 We're here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET.*

2. Missing a period after the phone number here too: 

*If you’ve received a letter about a VA debt, but don’t see the letter listed here call the VA Debt Management Center at 800-827-0648 You can also call the DMC to get information about your resolved debts For VA health care copay debt, please go to our pay your VA copay bill page to learn about your payment options.*

**Comment by bradl3yC** [comment]
@peggygannon I fixed a few of them in a previous PR and I have a PR to fix the remaining ones that I could find.

**Comment by peggygannon** [comment]
ok, thanks!

**Comment by bradl3yC** [comment]
@peggygannon this should have trickled down to staging now and is ready to be reviewed

**Comment by leahkeeler** [comment]
HI, Can we close this?

**Comment by peggygannon** [comment]
@leahkeeler Yes, I will close this one. thx!
