### ISSUE TITLE
Project Kickoff: Team Orchid (IRIS)

### ISSUE THREAD

**Issue by katieho-va** [department-of-veterans-affairs/va.gov-team#12382]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ AndreaHewitt @ Mandi Lipka
- [x] Mandi will schedule meeting with VSP reviewers and Team Orchid attendees (as listed below)
- [ ] VSP <> Team Orchid kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from Team Orchid
- Product Manager (required): Ramya Ramesh ramyar@thoughtworks.com
- DEPO Product Lead (required): Chante Lantos-Swett chante.lantosswett@va.gov
- Entire VFS team (recommended): 
  - Katie Ho kho@thoughtworks.com
  - Helen Shin hshin@thoughtworks.com
  - Rachel Murray rachel.murray@thoughtworks.com
  - Shefali Nayak shefali.nayak@thoughtworks.com
  - Anita DeWitt adewitt@thoughtworks.com
  - Jacob Gacek jacob.gacek@thoughtworks.com

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Megan/Andrea will reach out as needed_

Timeslot: **Wednesday, August 12th at 11:30am ET**

**Comment by mandifrances** [comment]
Scheduled for 8/12 @ 11:30am ET @katieho-va
