### ISSUE TITLE
Adding Bradley Gross to DSVA Slack

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#12384]
The following individual `bradley.gross@b3groupinc.com` needs be added as a full member to #vaos-team

I'm requesting full member because I will ultimately need to invite him to several more channels that we use across the VFS platform. He will be a core contributor / software engineer as part of VAOS.

**Comment by LizCallaghan** [comment]
done!

**Comment by saneshark** [comment]
@LizCallaghan could you please make him a full member -- he'll need to be invited to at least 4 other channels.
