### ISSUE TITLE
[Bug] - Debt Letters MVP - Your VA Debt - Copy anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12389]
## What happened?
On Staging Your VA Debt page, the following copy anomalies were found:
1. Under Need Help? \[right-rail on desktop], time-range copy did not follow VA Design System > Content guidelines.
2. Under same section, 1st subheading has typo.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: ```vets.gov.user+1@gmail.com``` (Greg)

## Steps to Reproduce
1. Go to https://staging.va.gov/manage-va-debt/your-debt/ -- sign-in as ```vets.gov.user+1@gmail.com``` (Greg).
1. In **Need Help?** section \[scroll down on mobile; in right-rail on desktop]:
  a. Observe that in 1st paragraph **6:30am**, **6:00pm**, and **CST** do not follow VA Design System Content guidelines.
  b. Observe that in 1st subheading's last word **assitance** is misspelled.

**Screenshot**
![dl-bug-copy-debt-ltrs](https://user-images.githubusercontent.com/587583/90082620-18257f00-dcc5-11ea-9061-4b2e29c15e6d.png)

## Desired copy
Time-range copy should be **6:30 a.m.**, **6:00 p.m.**, and **CT**, following VA Design System Content [guidelines](https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones):
![va-design-sys-content-spec-times](https://user-images.githubusercontent.com/587583/90082707-5a4ec080-dcc5-11ea-9654-46fbace2bfb3.png)

"assitance" should be spelled **assistance**.

## Acceptance Criteria
- [ ] \[see **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by leahkeeler** [comment]
Can you please pull this into current sprint as unplanned to fix. @bradl3yC @rileyorr or @rebeccawalsh

**Comment by rileyorr** [comment]
@leahkeeler I'm not sure why I'm assigned to this ticket. This seems like content change on the frontend, so pulling it into the current sprint depends on @bradl3yC's bandwidth. Thank you for finding these content bugs, @tlei123! You're awesome!!

**Comment by leahkeeler** [comment]
Hey @rileyorr - just fyi in case you need to change in prototype, if not, nothing to do

**Comment by rileyorr** [comment]
@leahkeeler awesome, no worries! I usually don't make content changes in prototypes if the tool's already in staging/prod. I am always available to review updates to the frontend, though! :)

**Comment by bradl3yC** [comment]
@tlei123 this has been merged and should be in staging to validate in the next 30-40 minutes

**Comment by rileyorr** [comment]
@tlei123 does everything look good on your end regarding the content changes @bradl3yC made?
