### ISSUE TITLE
VSP Release Plan Template

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#12388]
## Release Plan Template [Draft]
This Release Plan Template is intended to be used to help ensure your new VSP product or feature is ready for launch and will deliver the desired user outcomes. In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necesssary prior to going live. In Phase 2, you will define the launch communications plan and post-launch KPIs. 

You do not need to complete a release plan for a product or feature update that does not:

- Add substantial new functionality to the Platform.
- Impact user flows through tasks.

For your product or feature, make a copy of this template and check it into products/platform/<product-name>.

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- Desired date range or test duration: 
- Desired number of users: 
- The group(s) from which you'll recruit test users:
  - [ ] VFS
  - [ ] VSP
  - [ ] DEPO
- How you'll recuit test users:
- How you'll give test users access to the product: 
- What metrics-based "success criteria" will you look at before launch? [use your KPIs to help guide this.]
- How you'll measure your "success criteria": 

### Results:

- Number of users: 	

- Results for your "success criteria":

- Number of bugs identified / fixed: x/x

- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no

  - If yes, what:   

### Launch communications:

- [ ] Product documentation
  - Product brief
  - User Guide (if applicable)
- [ ] Release announcements
  - Newsletter article - collaborate with the Service Design team
  - Team of Teams and other VFS/VSP meetings

### Planning:

- Desired launch date: 
- Post-launch KPI 1:
- Post-launch KPI 2:
- Post-launch KPI 3: 

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by gunsch** [comment]
Hey --- I'm not sure what to do with this. Did you mean to put this in an [issue template](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/.github/ISSUE_TEMPLATE)?

**Comment by jchasia-adhoc** [comment]
Hi - yes, I wanted to create an issue template but it looks like I don't have permissions to do so. Could you create a vsp-release-plan issue template file that I can put this into?

**Comment by gunsch** [comment]
this was checked in as an issue template -- closing
