### ISSUE TITLE
IA Feedback - Staging Review - Debt Letters

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#12386]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This issue describes IA feedback for the Manage Debt/Debt Letters tool experience

*Note: Given this is an MVP and not full implementation of the solution, only a small portion of the IA can be reviewed.  Will need to do an additional review once the full product is available on staging.*

**MUST**
1. Static page breadcrumb should be:   [Home](www.va.gov) > **Manage your VA debt**
2. Your VA debt page breadcrumb - the "Manage your VA debt" component should link to  staging.va.gov/manage-va-debt

**SHOULD**

**CONSIDER**

## Definition of Done
- [ ] Must feedback is implemented on staging
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by leahkeeler** [comment]
Thank-you @mnorthuis, iteration 2,3 is a few sprint out but will for sure go through a separate staging review. 

@bradl3yC - can you run by Mikki please once complete
