### ISSUE TITLE
STEM - Post-VSP Staging Review Content Doc updates

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#12398]
Update content per VSP staging review, as relevant
- content
- accessibility
- ia 

Create new content doc for ease of use

**Comment by leahkeeler** [comment]
Hi @tzelei I think this may be in the wrong ticket? or I am really missing something :)

**Comment by tlei123** [comment]
> Hi @tzelei I think this may be in the wrong ticket? or I am really missing something :)

Sorry, @leahkeeler !  I fat-fingered that 1st ticket# in my Test Plan ticket.  Just corrected it there -- should be #12389 .

**Comment by ccruzgra** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-post-staging-review-v0.5.md
