### ISSUE TITLE
CT-Filter: Gender radio button switching on refresh

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12394]
Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=
2. Select "Women only" under gender
3. Refresh the page 
4. Observe the "Any" radio button is selected and it still shows the "Women only" results
5. Can do the same steps for "Men only" and on refresh, the "Any" gets selected

Expected behavior: On refresh, the radio button selection should hold its value of "Women only" or "Men only" or "Any" and not just default to "Any" on every refresh.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13837/

**Comment by sonntag-adam** [comment]
Retains value locally on refresh.

**Comment by sonntag-adam** [comment]
In staging. closing bug.
