### ISSUE TITLE
STEM: Post-VSP Staging Review Prototype Updates

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#12396]
Update prototype per VSP staging review, as relevant
- content
- accessibility
- ia 

Create new prototype for ease of use

**Comment by ccruzgra** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-post-staging-review-v0.5.md

**Comment by ccruzgra** [comment]
STEM 10203 Prototype V0.5: https://bahdigital.invisionapp.com/share/DGIAEP75WKA
