### ISSUE TITLE
Update GA for connected apps

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#12399]
See conversation [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9488)

We need to make small updates to the events we're tracking.

here is a dataLayer spec for Connected Apps disconnect:

```
{
  'event': 'profile-disconnect-connected-app-started'
}

{
  'event': 'profile-disconnect-connected-app-failed',
  'error-key': '00_error message'
}

{
  'event': 'profile-disconnect-connected-app-successful',
  'user-has-connected-apps': true|false
}
```

```
profile-get-connected-apps-failure would need to become profile-get-connected-apps-failed
profile-get-direct-deposit-failure would need to become profile-get-direct-deposit-failed
```

**Comment by sanlouise** [comment]
@bsmartin-ep For the 'error-key' when disconnecting has failed, what is the `error message` we want to record? Do we want to use the error `code` or `status`? I am seeing both being used in different parts of the application.
 
![image](https://user-images.githubusercontent.com/14869324/90028389-db329b80-dc76-11ea-9c46-c450c8eaba1d.png)

**Comment by bsmartin-ep** [comment]
@sanlouise -

If possible, both the code and the status/description:

`'error-key': '204_the connected application's grant have been deleted'`

...and...

`'error-key': '401_Not Authorized'`

Thanks!
