### ISSUE TITLE
Define checklist of requirements for application launches, with details solicited from stakeholder VSP teams

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#124]

**Comment by gunsch** [comment]
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Launch%20Process/overview.md

review from DSVA still TBD, but initial launch checklist is created and checked in

**Comment by gunsch** [comment]
DSVA gave initial review yesterday. Said the checklist looked good, they just want to change emphasis away from "checklist for launch" and focus on integrating those requirements more throughout the product development lifecycle.
