### ISSUE TITLE
GIBCT Profiles Text Field Changes firing multiple events

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#12401]
### GIBCT Form Change for Text Fields
- The dataLayer push seems to be happening on every keystroke, for example inputting 100 is pushing on `1`, `0`, `0`. **We will want to adjust this event listener to be on click away from the text field -- indicating the user has finished inputting their adjusted numbers**. See the example screenshot below firing 3 separate `gibct-form-change` events
![image](https://user-images.githubusercontent.com/48527022/87788595-99473e80-c80b-11ea-814f-2040a59c3a58.png)

## Steps to Reproduce
- Go to a profile at `/gi-bill-comparison-tool/profile`
- Change the dollar amount of Scholarships field for example

## Desired behavior
_`gibct-form-change` should only be firing one event for each time the user has finished inputting their dollar amount and clicks away
![image.png](https://images.zenhubusercontent.com/5d234c844828605fd8bf8ede/c807cc6b-a9c2-4e2f-b1bc-d53b8800fe74)

## Acceptance Criteria
- [ ] Fire **one** event on click away for the text field
- [ ] QA has been completed

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13864

**Comment by bsmartin-ep** [comment]
### QA

Interaction|Screenshot|Pass/Fail
---|---|---
Typing in _Tuition and fees per year textbox|![image](https://user-images.githubusercontent.com/62304138/90524367-fbad9a80-e13b-11ea-9380-5e05489f3bdf.png) ![image](https://user-images.githubusercontent.com/62304138/90524560-3adbeb80-e13c-11ea-9117-6f46eb2600d8.png) | **PASS :heavy_check_mark: **
Typing in _Scholarships (excluding Pell Grants)_ textbox| ![image](https://user-images.githubusercontent.com/62304138/90524702-64951280-e13c-11ea-9392-a739b9168957.png) ![image](https://user-images.githubusercontent.com/62304138/90524738-6d85e400-e13c-11ea-8476-b6d78a377a8c.png) | **PASS :heavy_check_mark: **

One thing I see @jonwehausen is that it fires the `gibct-form-change `event every time you blur a textbox.  Not just when the value changes.

**Comment by jonwehausen** [comment]
Thanks @bsmartin-ep that is fine -- we can exclude those out in our eventual queries here. 

@dmccurdybah and @desireeturner we were able to test this change within the deployment PR instance and confirmed this is now functioning as expected and can move to production at your earliest convenience.
