### ISSUE TITLE
[Discovery] JSON Schema: Front End Seems to Use Three Different Schemas

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12416]
## Issue Description
We have three sources of schema's (vets-api, vets-json, lighthouse). 

## Acceptance Criteria
- [ ] Determine why we have so many and whether there are consolidation/deletion/combination options
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by edmangimelli** [comment]
My findings:

vets-website and vets-api are using completely different schemas. Typically, vweb and vapi would share a schema via the vets-json-schema repo. vets-json-schema has a 20-0996 schema but it's not being used by vets-api, and, according to Robin, it's not being used by vets-website either.

Action Being Taken:

1) Put a snapshot of Lighthouse's JSON Schema into vets-json-schema (DONE)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7197

2) Use vets-json-schema in vets-api (BEING WORKED ON)
incorporated into this ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11094

3) Use vets-json-schema in front-end?? This might not be entirely possible (having talked to Robin about it) (the front-end needs a very transformed version of the schema to play nice with the libraries they use).
This needs to be spun into a ticket
