### ISSUE TITLE
[Post-release] Update old Drupal content deploy trigger (CMS Team to execute)

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#12423]
After the revproxy config in prod has been updated to use the content bucket instead of the original bucket, we should should remove the old drupal content deploy trigger so stop deploying content to the original bucket.

**Comment by indytechcook** [comment]
@billfienberg are you referring to the manual content build which is triggered from the cms to jenknis?  We won't be removing the functionally.  It will be updated to call the new jenkins job.

**Comment by timwright12** [comment]
@indytechcook thanks! I'll update the title of this ticket to reflect that
