### ISSUE TITLE
FL search result header shows code instead of name for VA benefits service type

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#12428]
## What happened?
When searching for VA benefits, the service type code is shown instead of the human-readable name.

Bug:
![Find_VA_Locations___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/96a0a434-67f2-47b9-a5b0-8264c28c737b)

Fix:
![Find_VA_Locations___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/659a44c2-4751-4ac4-a1f8-b3111ff3aefe)

**Comment by mmiddaugh** [comment]
Looks great!
