### ISSUE TITLE
508-defect-2 [HEADING, COGNITION]: Heading levels SHOULD only increase by one 

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#12430]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

At the top of the CMS authoring system, there is a blue area that communicates accessibility issues. The heading level issue is with the Option 1: Pay online, Option 2: Pay by phone, and Option 3: Pay by mail. Each of these are h4, but there isn't a preceding h3. These **should** be h3s.

See [Common A11y Issues - Headings documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/common-issues/headings-should-increase-by-one.md)

## Point of Contact

**VFS Point of Contact:** Jennifer

## Screenshots or Trace Logs

**Blue accessibility issues area**

![Screen Shot 2020-08-12 at 1 19 21 PM](https://user-images.githubusercontent.com/57469/90046445-7b4feb00-dc9e-11ea-8895-ef6f481c1c7f.png)

<hr>

**Area where the heading level issue exists**

![Screen Shot 2020-08-12 at 1 21 05 PM](https://user-images.githubusercontent.com/57469/90046729-dc77be80-dc9e-11ea-8397-582cd1d4bb29.png)

**Comment by bradl3yC** [comment]
@jenstrickland this is the static website created in the CMS by whomever does that.  Its not on the actual frontend code.  I am un-assigning myself

**Comment by jenstrickland** [comment]
@leahkeeler Who is your contact for this work? My suspicion is Public Websites, but I'm not sure who y'all worked with there.

**Comment by leahkeeler** [comment]
Hi Jen - Danielle did all the HP work

**Comment by jenstrickland** [comment]
Hi @DanielleThierryUSDSVA — would you be the person to connect with regarding this heading level issue?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jenstrickland - yes! I can help resolve this.

**Comment by DanielleThierryUSDSVA** [comment]
I was counting the accordion as the h3 here...but sounds like that's not correct, yes?

**Comment by leahkeeler** [comment]
@brianalloyd I am going to remove our tag from this tix - lmk if there is anything u need form our team on this

**Comment by brianalloyd** [comment]
@leahkeeler thanks for the notice, sure thing as it looks like @DanielleThierryUSDSVA commented above.  Thanks for the update.

**Comment by brianalloyd** [comment]
closing per grooming.  We can open up if this becomes an issue forward.
