### ISSUE TITLE
[Bug] Debt Letters MVP - pay.gov link goes to www.pay.va.gov

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12438]
## What happened?
On Staging Your VA Debt page, in **How do I pay my VA debt?** > **Online** section, **pay.gov** link went to **www.pay.va.gov**.

**NOTE**: While the link worked fine \[i.e., navigated successfully to some destination], this Defect calls out the **need to fix either the link text or link destination**.  It'd be prudent to verify, through independent documentation, whether the link should really navigate to https://pay.gov \[which does also exist], or https://www.pay.va.gov/ \[where it actually navigated].  Because financial transactions are involved, Veteran users should not have to just assume we sent them to the correct place to pay.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: ```vets.gov.user+1@gmail.com``` (Greg)

## Steps to Reproduce
1. Go to **https://staging.va.gov/manage-va-debt/your-debt/** -- sign-in as **```vets.gov.user+1@gmail.com``` (Greg)**.
2. In **How do I pay my VA debt?** > **Online** section \[scroll down on mobile; right-rail on desktop], click **pay.gov** link.
3. Observe that the destination hostname is **www.pay.va.gov**.

## Desired behavior
See **NOTE** in **What happend?** section above -- either the link text or link destination should be fixed.

## Acceptance Criteria
- [ ] \[see **NOTE** in **What happend?** section above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by leahkeeler** [comment]
@rebeccawalsh @rileyorr Can you please make a call on what this should be changed to? 

This is referring to this link 
![image](https://user-images.githubusercontent.com/60892917/90134102-44c5af00-dd36-11ea-8edf-a9e9ffcc3a89.png)

Currently on the debtman site it spells out "Pay online" 

![image](https://user-images.githubusercontent.com/60892917/90134228-763e7a80-dd36-11ea-9c87-48083e7ef28c.png)

The link is correct - can you please advise @bradl3yC what to change to

**Comment by rebeccawalsh** [comment]
This text came Debtman, iirc. It should go to https://www.pay.va.gov/ <https://www.pay.va.gov/>.

**Comment by leahkeeler** [comment]
Thanks @rebeccawalsh should the text be " Pay Online" to be consistent w/debtman or spelling out the actual link

**Comment by rebeccawalsh** [comment]
I don't think we have to be consistent with Debtman? Keep the text as-is, it's already been reviewed by Peggy.

**Comment by rileyorr** [comment]
Hm, I see what Tze's saying about this bug. [Pay.gov](https://www.pay.gov/public/form/start/25987221) takes you to a site to pay medical copayment bills, whereas [pay.va.gov](https://www.pay.va.gov/) takes you to a site to pay your debt. It does seem incorrect to write "pay.gov" and then redirect to "pay.va.gov" since they're different sites. 

@peggygannon what do you think about us updating the text to, "Pay directly from your bank account or by debit or credit card on the secure pay.va.gov website."?

**Comment by leahkeeler** [comment]
@peggygannon Do you have any input on how to best handle the nuance between the tow payment methods. Thanks!!!

**Comment by peggygannon** [comment]
hello, @leahkeeler and @rileyorr sorry, I didn't see this come through!! I agree the content should be as this below: 

Pay directly from your bank account or by debit or credit card on the secure [pay.va.gov] website.

**Comment by bradl3yC** [comment]
This was just merged and will be in staging in about 30 minutes for validation
