### ISSUE TITLE
Fix content updates to Cerner pages

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#12446]
# Description

While implementing [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10756), a lot of the content had to be written into code manually (instead of copy-paste) so there are some content issues that didn't get implemented correctly. We should correct these as soon as possible.

#### Not Cerner User: https://staging.va.gov/cerner-staging/appointments/

- [x] Need to update the alert at the top to reflect recent changes to that alert in legacy content. Copy in alert should read:

**Due to COVID-19, we'll need to contact you to confirm your appointment**

You can still use our online appointments tool to request an appointment. We'll then contact you to confirm the date, time, and location.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/b73ce9f2-65ab-4b43-b47a-bde41af56aec)
- [x] Need to add colon after the "You're" in the eligibility lead-in to read "**You're:**" 
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/6e0b8aa2-7230-47bd-a945-4c12a88425cf)
- [x] Need line space after "Find out how to apply for VA health care" and bold **DS Logon** and **ID.me** in second and third bullet![Screen Shot 2020-08-13 at 11.51.36 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/15b83783-91ad-4e6d-99d2-0081510b6241)
- [x] Need to change "these tools" to "this tool" in 2 places in the below question:
  - Can I use this tool to schedule community (non-VA) appointments?
  - If you're eligible to receive care from a community provider outside of VA, you can use this tool to submit appointment requests.
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/9d80008d-11a9-4b41-89e0-7af22dcab075)
- [x] Link for "Find a community provider in the VA network" is not working.![Screen Shot 2020-08-13 at 11.59.49 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/da8205f9-46d7-4e46-b7b0-fbf53c526a13)
- [x] Need line space before the "Please note" line![Screen Shot 2020-08-13 at 12.06.58 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/a3bab0b1-2ebb-4d4c-9c47-8334265ef8fa)
- [x] For the two TTY numbers the text should read: (TTY: 711). Everything in the parentheses should be linked.![Screen Shot 2020-08-13 at 12.09.21 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c1cb1bbb-6932-4dcf-9adf-a7ee33385434)

#### Cerner User: https://staging.va.gov/cerner-staging/appointments/

- [x] Need to update the alert at the top to reflect recent changes to that alert in legacy content. Copy in alert should read:

**Due to COVID-19, we'll need to contact you to confirm your appointment**

You can still use our online appointments tool to request an appointment. We'll then contact you to confirm the date, time, and location.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/b73ce9f2-65ab-4b43-b47a-bde41af56aec)
- [x] Add line space after COVID alert![Screen Shot 2020-08-13 at 1.17.57 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/85a9a5f5-a0e8-42a8-95d2-c9cd48dfd0af)
- [ ] Per recent confirmation, update button 1 to read: **Go to My VA Health** and button 2 to read: **Go to the VA appointments tool**![Screen Shot 2020-08-13 at 1.23.33 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/4eda46a3-42c5-4a4f-991c-bea03fd261d4)
- [x] Add line space after "Find out how to apply for VA health care". Also the link in the third bullet for ID.me isn't working right. ![Screen Shot 2020-08-13 at 1.27.04 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d6ce57a6-5bd9-4b0c-9f77-51f623992191)
- [x] Add line space above the "Please note"![Screen Shot 2020-08-13 at 1.29.04 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/cbbfb46b-077d-45a1-81fd-203c5569d56b)
- [x] Fix coding for the TTY numbers. It should show as (TTY: 711) with everything within the parentheses linked. ![Screen Shot 2020-08-13 at 1.30.24 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/59b69775-a050-42cd-99e6-aae6a1775da5)
#### Not Cerner User: https://staging.va.gov/cerner-staging/messaging/

- [x] Add line space after "Find out how to apply for VA health care"![Screen Shot 2020-08-13 at 1.35.35 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/b66f2d7a-9fde-4a84-8489-2a5605a02c9d)
- [x] Add a space after the bolded comma in the third paragraph![Screen Shot 2020-08-13 at 1.36.54 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d8b57aa9-8ca0-41a2-b819-1c1dd4ee2169)
- [x] Take out the line space before "Find your nearest VA health facility" and put one in after it so there is space between that and the paragraph below it. Also the link for "Find your nearest VA health facility" isn't right.![Screen Shot 2020-08-13 at 1.38.36 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/5e18e8b4-ace0-4893-bd03-48d535002dc4)
- [x] The sentence "Get tips for protecting your personal health information" needs to be a link. ![Screen Shot 2020-08-13 at 1.39.52 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ead9630c-0cf8-4454-9831-5ed2cf1b57fb)

#### Cerner User: https://staging.va.gov/cerner-staging/messaging/

- [x] Should the buttons in alert say "Use My VA Health secure messaging" and "Use My HealtheVet secure messaging"?![Screen Shot 2020-08-13 at 2.30.44 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/2dcf23cd-87ff-4fa4-8dec-ddbaead14e48)
- [x] Delete the last line "Learn about the 3 different MyHealtheVet account types"![Screen Shot 2020-08-13 at 2.33.39 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/941cb7f5-6edf-4777-8c8d-fbd0746fa399)

#### Not Cerner User: https://staging.va.gov/cerner-staging/prescriptions/

- [x] Add line space after "Find out how to apply for VA health care" and bold DS Logon and ID.me in the bullets![Screen Shot 2020-08-13 at 1.48.03 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/7f404ede-e0ae-41b3-a814-0842c52a7bbe)
- [x] Remove line space above "Get tips for protecting your personal health information"![Screen Shot 2020-08-13 at 1.50.18 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/f0840c08-1746-4d21-8e40-dd954f9f53a0)

#### Cerner User: https://staging.va.gov/cerner-staging/prescriptions/

- [x] Should buttons on alert say "Refill prescriptions on My VA Health " and "Refill prescriptions on My HealtheVet"?![Screen Shot 2020-08-13 at 1.57.54 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/aa353862-c836-4d57-bdbe-f36e70dd3ea3)
- [x] Add a space before the bolded "Pharmacy" ![Screen Shot 2020-08-13 at 2.06.02 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/8501f485-6d10-4127-ab10-4a408d4ce127)
- [x] Add space before bolded "Pharmacy" and add ", and" at the end of the first bullet ![Screen Shot 2020-08-13 at 2.07.55 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/315018be-9bb0-4528-a8db-721ab7a6bca4)
- [x] The sentence under the H2 should be moved to the very bottom of that section with a bold "Note:" in front of it.![Screen Shot 2020-08-13 at 2.10.11 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/3d79a0fe-6fea-4cad-9e7e-e7b4446f1e80)
- [x] Add a colon after TTY ![Screen Shot 2020-08-13 at 2.12.52 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/aecf4be7-7362-4a54-94c5-f2c763d4c022)

#### Not Cerner User: https://staging.va.gov/cerner-staging/records/

- [x] Bold the "and" at the end of the first bullet![Screen Shot 2020-08-13 at 2.54.28 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/73fe1124-4b1a-483e-a99c-1590c6a5269e)
- [x] Add line space after "Find out how to apply for VA health care" and bold "DS Logon" and "ID.me"![Screen Shot 2020-08-13 at 2.54.57 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/4e086138-502d-44c3-9fe3-8d8d08386b64)
- [x] Delete line space before "Get tips for protecting your personal health information"![Screen Shot 2020-08-13 at 2.58.27 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/cccb550b-f48b-4cc4-88c8-39bb0c3524cb)
#### Cerner User: https://staging.va.gov/cerner-staging/records/

- [x] Should alert buttons say "Get records on My VA Health" and "Get records on My HealtheVet"?![Screen Shot 2020-08-13 at 2.18.01 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/b1dc6c52-de86-4974-863d-8bb29f1f47f9)
- [x] Add a line space after "Find out how to apply for VA health care"![Screen Shot 2020-08-13 at 2.22.20 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d8957932-a7a6-41d2-a687-35a220b8cecb)
- [x] Bold the "or" at the end of the second bullet![Screen Shot 2020-08-13 at 2.23.21 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/e7a0590d-dd63-4ba6-8db6-46fcb412c55d)
- [x] Remove line space before "Get tips for protecting your personal health information"![Screen Shot 2020-08-13 at 2.25.50 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/1359eac5-05c7-4493-8208-6f082bedf74e)
- [x] Remove line spaces within the first bullet![Screen Shot 2020-08-13 at 3.02.36 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/0d8529ef-a6cd-43b7-adef-1d2e0fc35285)

#### Not Cerner User: https://staging.va.gov/cerner-staging/results/

- [x] Add line space after "Find out how to apply for VA health care" and bold "DS Logon" and "ID.me"![Screen Shot 2020-08-13 at 2.48.53 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d74e41ae-5688-4564-907c-6db8af503f20)
- [x] Delete line space before "Learn about the 3 different My HealtheVet account types" ![Screen Shot 2020-08-13 at 2.51.04 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/0821588c-e795-443b-bd6e-50f5b9b0f775)
- [x] Delete line space before "Get tips for protecting your personal health information"![Screen Shot 2020-08-13 at 2.51.42 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/4ef77cbc-836c-4b5a-98fb-903ccaf5d8aa)

#### Cerner User: https://staging.va.gov/cerner-staging/results/

- [x] Should alert buttons say "View results on My VA Health" and "View results on My HealtheVet"?![Screen Shot 2020-08-13 at 2.37.24 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/8a9f1b7a-85ce-44ef-b545-ccb5985ec6b3)
- [x] Bold "My VA Health's Labs and Vitals"![Screen Shot 2020-08-13 at 2.38.29 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/3e415a77-d28a-4290-ae70-68d39d046b15)
- [x] Bold "My HealtheVet's Labs + Tests"![Screen Shot 2020-08-13 at 2.39.50 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/b2616f31-10bb-402a-9ba3-1b7a3da3115b)
- [x] Delete the last four lines starting with bolded "If you receive care..."![Screen Shot 2020-08-13 at 2.41.27 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/bc0bf250-6fa4-49f3-8cff-fc2c06bc654c)
- [x] Add space before both instances of bold copy here ![Screen Shot 2020-08-13 at 2.42.57 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/bf117921-6729-4eeb-86ae-a79a4c49f5af)
- [x] In the parentheses add "TTY:"![Screen Shot 2020-08-13 at 2.44.58 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/73ccde8e-4fa5-4962-b95a-625964ef3aaf)
## Acceptance Criteria

- [ ] Fixed the content implementation for the above issues.

**Comment by RLHecht** [comment]
@kelsonic Here you go! Please let me know if you have questions about any of this. @DanielleThierryUSDSVA I know you wanted to do a read through this all too. If it's easier you can check to see if I've already caught what you caught so we don't have to double the work. Or if you'd rather wait till this is updated and then do a second check afterward.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht! I think it does make sense for me to do a second check after for most of the pages, yes (see below for exception). That way, I can be a fresh pair of eyes on the updated content. @kelsonic, just let me know when these updates are made and I'll do a final check.

@kelsonic 2 other things:

1. We need to replace the legacy content with the new unauthenticated content for the **Schedule and view appointments** page for Monday 8/17 because the new content also has some community care-related updates that need to go live just a little ahead of the Cerner launch of that page on 8/21. So that will be the one exception to the plan above - I'll look at that page today and send over any needed updates so we can get that launched.

2. I've confirmed that we are good to go with generic buttons across all alerts. But would like to go with "Go to" instead of "Use" (so "Go to My VA Health" and "Go to My HealtheVet"/"Go to the VA appointments tool"). Could you update this? Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht and @kelsonic. I edited my comment above to avoid confusion. I've reviewed the schedule and view appointments page and added notes to Randi's list above (caught a couple of things that we also need to update in content doc, and I'll do that).

Also, @kelsonic, we separately need to update the legacy content for this schedule and view appointments page for the Monday 8.17 deploy. The VA appointments tool is adding community care appointments that day, but we won't be quite ready to just switch to the unauthenticated Cerner content. I'm attaching the needed changes to the legacy page. Can you update these or show me how to update Monday morning? Thank you!

[appointments page_legacy content updates](https://app.zenhub.com/files/133843125/d578f88a-ddc5-4bc3-a2b7-92fd648685ff/download)

**Comment by kelsonic** [comment]
Hey @DanielleThierryUSDSVA! Sorry I was out Friday on PTO so I didn't get this until now, I'll try to send up a PR this evening for the schedule + view appts page legacy content! 🙂 Following that, first thing tomorrow I'll work on implementing the content updates on all the other pages!

**Comment by kelsonic** [comment]
PR is up for updating the legacy content! Will definitely be merged before deploy tomorrow 🤞 CC @DanielleThierryUSDSVA @ncksllvn

**Comment by DanielleThierryUSDSVA** [comment]
Thank you so much, @kelsonic!!

**Comment by kelsonic** [comment]
This should be ready for review here once the deploy to staging occurs! @RLHecht @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
@kelsonic Here are the changes that still need to be made. Let me know if you have any questions:
**Non user https://staging.va.gov/cerner-staging/appointments/**
- [ ] Add a space between the lines "Find out how to apply..." and "And you must have one of these accounts..."
<img width="675" alt="Screen Shot 2020-08-20 at 9 09 10 AM" src="https://user-images.githubusercontent.com/48728214/90774027-d1d3af80-e2c4-11ea-80f3-e795edee13c2.png">

- [ ] Looks like there's now too big of a space before the line "Please note:..."
<img width="802" alt="Screen Shot 2020-08-20 at 9 44 17 AM" src="https://user-images.githubusercontent.com/48728214/90777659-b9b25f00-e2c9-11ea-9e6d-4ca77595324d.png">

**User https://staging.va.gov/cerner-staging/appointments/**
- [ ] Add a line space between "Find out how to apply..." and "And, you must have one of these free accounts"
<img width="749" alt="Screen Shot 2020-08-20 at 9 48 06 AM" src="https://user-images.githubusercontent.com/48728214/90778119-41986900-e2ca-11ea-87ec-1f352103dda9.png">


- [ ] Add a line space between "Learn more about secure messaging' and "Please note"
<img width="787" alt="Screen Shot 2020-08-20 at 9 48 51 AM" src="https://user-images.githubusercontent.com/48728214/90778215-5d037400-e2ca-11ea-8d66-6a8e3a36c920.png">

**Non user https://staging.va.gov/cerner-staging/messaging/**
- [ ] Add line space between "Find out how to apply for VA health care" and "And you must have one of these free accounts"
<img width="743" alt="Screen Shot 2020-08-20 at 9 21 50 AM" src="https://user-images.githubusercontent.com/48728214/90775218-9639e500-e2c6-11ea-8f53-5078a38a7fb6.png">

- [ ] Delete the line space before "Find your nearest VA facility" and add a line space before "If you need to talk to someone right away..."
<img width="607" alt="Screen Shot 2020-08-20 at 9 20 50 AM" src="https://user-images.githubusercontent.com/48728214/90775125-74406280-e2c6-11ea-9c59-0dd89e004c2c.png">

**Non user https://staging.va.gov/cerner-staging/records/**
- [ ] Add line space after "Find out how to apply for VA health care"
<img width="784" alt="Screen Shot 2020-08-20 at 9 32 34 AM" src="https://user-images.githubusercontent.com/48728214/90776435-16147f00-e2c8-11ea-8988-e1a5089e3ed1.png">

**User https://staging.va.gov/cerner-staging/records/**
- [ ] Add line space between "Find out how to apply" and "And you must have one of these..."
<img width="704" alt="Screen Shot 2020-08-20 at 9 34 59 AM" src="https://user-images.githubusercontent.com/48728214/90776688-6c81bd80-e2c8-11ea-8f28-35e925ef7fce.png">

- [ ] The first bullet point is now missing the line spaces. 
<img width="821" alt="Screen Shot 2020-08-20 at 9 36 57 AM" src="https://user-images.githubusercontent.com/48728214/90776905-b2d71c80-e2c8-11ea-9b7e-7a9c19eb2a52.png">

**Non user: https://staging.va.gov/cerner-staging/results/**
- [ ] Add line space between "Find out how to apply" and "And you mus thave one of these..."
<img width="735" alt="Screen Shot 2020-08-20 at 9 38 49 AM" src="https://user-images.githubusercontent.com/48728214/90777089-f5005e00-e2c8-11ea-87cc-7eda541296fd.png">

- [ ] Delete line space between "Note" and "Learn about the 3 different types..."
<img width="736" alt="Screen Shot 2020-08-20 at 9 39 40 AM" src="https://user-images.githubusercontent.com/48728214/90777198-14978680-e2c9-11ea-8c2a-6ccb22578110.png">

**Comment by kelsonic** [comment]
Validated and moving to close as it's now live on prod
