### ISSUE TITLE
VSP content - Usability prep - VRE Chapt 36 prototype

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12440]
## User story

This ticket captures VSP content feedback on VRE Chapt 36 form and wizard

Prototype link: https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/130194084/comment/sitemap

## Acceptance criteria

- [x]  VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x] Teams leaves comments about any feedback they decide not to take
- [x] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
Hi, @sporeboy Please see below content recommendations for Chapter 36 prototype. Let me know if you have any question or need to discuss.  thx. 

Feedback key

Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement

----

*Should*

Wizard page 

1. Change current “Find out if this is the right form” header to: 

**Is this the form I need?**
UPDATED content: This application is for Veterans, service members, or their dependents to apply for career counseling and support to help them find a training program or job. 
To see if this is the right form for you, please answer a few questions.

2. Change: Already know this is the right form? TO
**I know this is the form I need. How do I apply?**
Click on the link below to go to our online application without answering the questions above.
{link} Apply online with VA Form 28-8832

------

Subway map page

1. Under Decision
Rewrite to: 
If you’re eligible for career planning and guidance benefits, we’ll invite you to an orientation session at your nearest VA regional office. 

-----

Screen 1
Please add hyphen between active and duty. Should be active-duty service member

------

Screen 3
Military address treatment? Use updated treatment/language below:
{checkbox} I live on a U.S. military base outside of the country.
U.S. military bases are considered a domestic address and a part of the United States.


-------

Screen 4 Veteran or service member information 

Rewrite intro TO: 

**The below information is optional.** You don’t have to answer these questions now, but we may ask for this information again when we process your application.

Recommend putting (Optional) after each label 

Have you ever applied for Vocational Rehabilitation Benefits (Chapter 31)? 
Please rewrite to the below with new rebranded program name: 

Have you ever applied for Veteran Readiness and Employment benefits (Chapter 31)? 
{box}

add "for" in this question:

Have you ever applied for Veterans’ education assistance based on your own service?

-----

Military service screen

Rewrite intro TO: 

**The below information is optional.** You don’t have to answer these questions now, but we may ask for this information again when we process your application.

Recommend putting (Optional) after each label 

------

QUESTION about the flow 
In the mockup, the Review and submit screen shows up before the dependent screens. Is this intentional flow? 

----- 

Dependent information

Rewrite intro TO: 

**The below information is optional.** You don’t have to answer these questions now, but we may ask for this information again when we process your application.

Do you have a disability and need special restorative training?

I recommend adding  some explanation what “special restorative training" is. 
What are your thoughts design-wise on how that could look? I can provide some explainer content.. maybe just 1-2 lines. 


Do you have a disability and need special vocational training?
I recommend adding  some explanation what “special vocational training" is. 
What are your thoughts design-wise on how that could look? I can provide some explainer content.. maybe just 1-2 lines. 


--------

Sponsor info screens

Is the sponsor someone other than the Veteran or service member? I'm wondering why we need a "sponsor" section if we already have a Veteran and service member information section.  


-----

Confirmation page
Please move this header our of the blue box: 

1.	Please move this header out of the blue box: Thank you for submitting your application

2.	Print button… has it been determined yet if where this button will appear on confirmation pages? I’ve seen it placed in various spots on the confirmation page. I think we should have a consistent location across all forms.

3.	Can we confirm with SMEs that they process applications in 1 week? I’m not sure this is true.

4.	I don’t think the subway map work for VRE since the next step in process would be a communication from a counselor. Can we check to see if VRE claims are posted in claim status tool? If not, I would recommend this:

**What happens after I apply?**
If you're eligible for career counseling benefits, we’ll invite you to an orientation session at your nearest VA regional office.


5.	I don’t think the “What if I have more question" phone number is correct. Do the VRE SME have a number they want applicants to call?

**Comment by sporeboy** [comment]
@peggygannon Thanks so much for all of your help. Answers to your questions below:

- The optional info screens were removed by the LOB. I made the text changes, but we're leaving them "on the side" for now. We can add explainer text if the LOB pulls them back in.
- The out-of-order screens are rigged to work as a prototype, so running through as a slideshow may result in screens out of place.
- Is the sponsor someone other than the Veteran or service member? There are two separate workflows; the sponsor screen only shows for dependents. In one flow, the claimant is a Veteran or service member, in the dependent is the claimant in the spouse or child flow.

**Comment by peggygannon** [comment]
**10/2/2020 update** Below is user feedback from user test sessions. I will be taking this user feedback into account in my content review.

from Jim Adams:
*Here’s my super-quick take: Generally the content of the wizards was well-understood, but some things stood out:
Participants often stopped on anything with time. One example: they wanted more specificity for “in the last year…” They asked if it meant any time last year, within the last 12 months, etc.
The other really big content related-issue was the last-minute addition regarding the 21-1900. That section work well on the confirmation page, but just created confusion on the intro.
A few participants mentioned they wanted “alternatives” when one or another of the wizard questions stopped them. One particular example is the, “Are you within 12 years of separation…” question. It has no link.
“…Better than dishonorable” discharge was another sticking point in the CH31 wizard.
The big grey sign-in box on the intro threw many participants. It obscured their view of the subway map; a couple participants said to make users scroll down and read before getting them to sign in. This is more a design problem, but cutting the content in the box could “lighten” it a bit.
Three or four participants said eliminate the paragraphs and replace them with “bullet points.” They wanted small verb-driven sentences with an action indicated.
Another generalization: the younger participants went straight to clicking, the older participants spent more time reading.*

**Comment by peggygannon** [comment]
Hi, @sporeboy Content recommendations for Chapt 36 wizard screen and prototype are below. This feedback doesn't include Chapt 31 wizard feedback. 

Wizard screen
*Should*
Update intro to the below to more closely align with content/structure of other online wizards. 
**Is this the form I need?**
If you’re a Veteran, service member, or dependent,  use this form to apply for personalized career counseling and support to help you find a training program or job. 
Answer a few questions to get started.
If you already know this is the correct form, you can go directly to the online application without answering questions. [Apply online with VA Form 28-8832](va.gov/URL TK)



*Should* 
REMOVE this part, as I've incorporated it into the intro above (and this matches style of other wizards)
I know this is the form I need. How do 
I apply?
Click on the link below to go straignt to the application without answering the questions above.
Apply online with VA Form 28-8832

I suggest removing the “Do you have a service-connected disability rating?  paragraph from the wizard page as it confusing to the use. I recommend we move this info to the subway map page (see edit below)  

Update the following alerts in the Chapter 36 wizard flow: 
1. To be eligible for career planning and guidance, you or your sponsor must have been discharged from active duty in the last year, or have less than 6 months until discharge.
[Learn more about VA career planning and guidance eligibility] (https://www.va.gov/careers-employment/education-and-career-counseling/)

2. When you’re ready to apply for career planning and guidance, just come back to this page to begin your application. 

3. Please cap Vocational Rehabilitation Counselor in the alerts to align with how we treat this on the static pages. 

4. Please update link language to: [Learn more about VA career planning and guidance]


------

Introduction/subway map page

ADD Introduction page (maybe in blue box?)
**If you’re a Veteran or service member with a service-connected disability or a pre-discharge disability rating,** you may also be eligible for Chapter 31 Veteran Readiness and Employment (VR&E) benefits. This program allows you to get employment support and services to help you live as independently as possible.  
[Learn more about Chapter 31 eligibility]( https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/)

On introduction sign-in page
Please make sure the green CTA button matches what we have for the wizard CTA button:
Apply for career planning and guidance

Form screen 1
I recommend using “applicant” vs. “claimant” as claimant sounds like the user is making a "claim"
Applicant information

Claimant signed in page
Please tweak the below sentence TO:
If you need If you need to update your personal information, please call Veterans Benefits Assistance at 800-827-1000, Monday through Friday, between 8:00 a.m. and 9:00 p.m. ET.

Screen 3
Military address treatment? I suggest we use the update treatment/language below:
{checkbox} I live on a U.S. military base outside of the country.
U.S. military bases are considered a domestic address and a part of the United States.

Veteran or service member information screens
Suggest using standard labels of 
Your first name
Your last name


-----


Confirmation page


1.	Please move this header out of the blue box: Thank you for submitting your application
2.	Print button… has it been determined yet if where this button will appear on confirmation pages? I’ve seen it placed in various spots on the confirmation page. I think we should have a consistent location across all forms.
3.	Name of the VRE program needs to be updated in the blue box content
4.	Can we confirm with SMEs that they process applications in 1 week? I’m not sure this is true.
5.	I don’t think the “What if I have more question" phone number is correct. Do the VRE SME have a number they want applicants to call?
6.	Print button. I recommend shortening this to "Print this page"
7.	I don’t think the subway map work for VRE since the next step in process would be a communication from a counselor. Can we check to see if VRE claims are posted in claim status tool? If not, I would recommend this:

**What happens after I apply?**
If you're eligible for career counseling benefits, we’ll invite you to an orientation session at your nearest VA regional office.

**Do you have a service-connected disability?**
If you have a service-connected disability or a pre-discharge disability rating, you may also be eligible for Chapter 31 Veteran Readiness and Employment (VR&E) benefits. This program allows you to get employment support and services to help you live as independently as possible.  
[Learn more about VR&E eligibility]( https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/)
Or you can apply online for VR&E benefits right now. [Apply online with VA Form 28-1900](goes to Chapt 31 wizard page)

**Comment by peggygannon** [comment]
Hello @sporeboy, I'm checking in to see if you have any questions about the feedback above?

**Comment by jason-gcio** [comment]
I think we might have some questions about some of these but they are pretty minor.  I will talk with Jim and get a short list so we can go over them with you.  Thanks!

**Comment by peggygannon** [comment]
@jason-gcio OK, thank you for the followup. Please let me know if I can clarify any of the feedback.

**Comment by peggygannon** [comment]
also, I've updated the wizard outline for Chapt 36 (per my work with the "wizard team"). I had share this earlier, but also dropping in the outline link to this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/chapter%2036-form-wizard.md

**Comment by peggygannon** [comment]
this product is now going through staging review. closing.
