### ISSUE TITLE
STEM: Update program details summary page section

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12459]
As a developer, I need to remove the eligibility summary panel so that it reduces the risk of confusion when interacting with the update process.

## Assumption:
1. This work is completed behind the feature flag #7271.

## Acceptance Criteria
1. The "Rogers STEM Scholarship eligibility summary" panel is not displayed in the "Program details" accordion on the summary page (Chapter 6).

## Supporting Artifacts:
1. 
<img width="611" alt="stem_eligibility_summary" src="https://user-images.githubusercontent.com/48260534/90164809-d8fb3a80-dd65-11ea-97c3-d0620eab5f8f.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13875

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-08-17 at 11.23.35 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b29393af-2ba8-47ff-97fd-a8cab9c39d1f)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on Staging and ready for review

**Comment by ccruzgra** [comment]
This checks out for UX.

**Comment by delli-gatti-michael** [comment]
Closing this out

**Comment by delli-gatti-michael** [comment]
Tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/918&group_by=cases:section_id&group_order=asc&group_id=51
