### ISSUE TITLE
Create post mortem for website sidebar not accessible across benefit pages from mobile devices

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#12451]
## Acceptance Criteria
Completed post-mortem added to Github

**Comment by ncksllvn** [comment]
Added here, https://github.com/department-of-veterans-affairs/va.gov-team/pull/12448

@brangi @ethanteague @kelsonic please make changes as you see necessary. I plan on sharing on our Slack thread this afternoon or tomorrow.

**Comment by ncksllvn** [comment]
Postmortem added here, https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/post-mortem/missing-sidebar-mobile.md, will share later
