### ISSUE TITLE
Create folders in GH for VAOS, Caregiver, and Get Care onboarding

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1245]
### User Story
As a new VFS Team, I need to have a space (and know how to use it!) in GitHub to store my team-specific information, so that I can self-organize and move forward effectively.

### Goal
Have folders with preliminary README.mds or whatever other "skeleton docs" we recommend for a nice UX for these new teams as they come on and start using these folders.

### Definition of Done
- [x] Folder and any docs/templates we want to include exist for each team in /teams
- [x] The new VFS Teams and their VA PM are aware that those folders exist and they know how to use them
- [x] The new VFS Teams and their VA PM are aware that their product documentation should NOT go in their team folder

**Comment by mnorthuis** [comment]
Worked through all of this with Lauren A.  

 All needed folders created under `products`

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/111935a2-be37-4b22-8774-5cda122647bd)

Folders created in `teams` area for all health products teams. 

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/4d090a5f-0ff4-4b5b-9eec-5021d4653a24)
