### ISSUE TITLE
Access for Bradley Gross

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#12457]
- Please provide your Contracting Officer's Representative (COR) name.
Herbert Ackermann
- Please provide your name.
Bradley Gross
- Please Provide your email.
bradley.gross@b3groupinc.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
Software Developer, VAOS Team, B3 Group

- Requesting SSH key authorization?
 YES 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVjnIflneh0Tt6YoiAz9ntb52h1ze9rK1Fw29F/++qiPh7YniD+zPzld5oibJ+nMvSAp+eCxQxsT3OoMTQW90ZFr+K9DjcWtPmb/51RQD/mZXSPdqhUqLjgm5s3iaRN07xDh21LJnrYuX2Lc+VUvk3CwNJsLVXuNp9quxZa5WFneMtT9QqNtsI2dYwx62CxxTlHF/ENkXlni/tceQb4ZxNM1dSGrDT3Ee9i6DoLe0TfX1bL2MTJyhK/y115TiYcUhAdLJLFrh+HrSUZumMIN8KPdzHc3lnV6/IO5DRfYFVxtLg2847gJADdepvEfsCLYk7pj8OLsW340Y8j71m0cuoD3PFs8ed3Ejo6GyqDqxrEFOyF7OMqfGZaqqGE0ubzfSdtuswlTv6x5LktLFoytqK+3yA0ifQswnCCzNjM/y5Z9hlUW+p/MkGoLSHDJOuFyJ30WsVtz5tLbpLcQkgSSWS+W2Ia+MQ3XyIWFcC3d7A/7UGhBXHdo19ZE8WhdYLuJk= grossb1@Uukrul
```

- Grant AWS Console access?
YES, need access to Cloudwatch

**Comment by grossb1** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by pnwstevan** [comment]
Not sure your @mention worked for some reason.

Pinging @department-of-veterans-affairs/vsp-operations for visibility.

**Comment by grossb1** [comment]
I was wondering what the status of this request is.  Do I need to provide any more information?

**Comment by jsev-io** [comment]
@Jeff-Hayter Requesting access for AWS Approval
COR: Herbert Ackermann
User: Bradley Gross

**Comment by jsev-io** [comment]
> I was wondering what the status of this request is. Do I need to provide any more information?

Bradley, your AWS access is subject to the above approval.

However, apologies can you verify your access to SOCKS proxy? That was active as of the merge.

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS access.

**Comment by jbritt1** [comment]
First time login credentials provided.
