### ISSUE TITLE
STEM: Add "use EVSS" Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12467]
As a developer, I need a way to toggle when the SCO email is sent from the staging environment so that SCOs are not being sent test data unnecessarily.

## Assumptions:
1. Feature flag for SCO email will need to be available in both vets-api and vets-website repos.

##Tasks
1. Follow feature flags documentation to create front-endback-end STEM SCO email feature flag.
2. Follow feature flags documentation to create back-end STEM SCO email feature flag.

## Acceptance Criteria
1. The STEM SCO Email feature flag is created and available in all environments.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by ksantiagomorgan6** [comment]
Frontend PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13883
Backend PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4733

**Comment by delli-gatti-michael** [comment]
Feature flag is present

![Screen Shot 2020-08-17 at 2.52.05 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/9a85845c-9934-4a2e-be8b-707f20c8f9f8)

**Comment by delli-gatti-michael** [comment]
This flag is now merged in. Closing this issue
