### ISSUE TITLE
VR&E Left Nav nesting is incorrect/missing

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#12466]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

The left nav in the Veteran Readiness and Employment section of va.gov is not correctly reflecting the intended hierarchy, and one page is missing from the left nav. 

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/bca4dd94-653a-4fea-8e9c-c7016d73fc8d)

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/careers-employment/vocational-rehabilitation/
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

Here is the correct order and hierarchy of the left nav - links provided for the nav items that are incorrect currently. 

- [Veteran Readiness and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/)
  - [Support-and-services tracks](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/)
    - [Reemployment services](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/reemployment)
    - [Rapid Access to Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/rapid-access-to-employment)
    - [Self-Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment)
    - [Long-Term Services](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/long-term-services)
    - [Independent Living](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/independent-living)
  - Eligibility
  - How to apply
  - Accessing VR&E through IDES

The "Support-and-services tracks" page is missing from the left nav. It should be the first page listed in the left nav, and the 5 tracks pages should be children to that page.  

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mnorthuis** [comment]
@bethpottsVADEPO Can you review the left nav labels and make sure I have them accurate?

**Comment by bethpottsVADEPO** [comment]
@mnorthuis You got it right. Thanks for noticing this. 

@RLHecht Can you make these changes?

**Comment by RLHecht** [comment]
@mnorthuis This is fixed. Should be live after today's deployment. FYSA @bethpottsVADEPO  Here's the new nav: 
<img width="297" alt="Screen Shot 2020-08-14 at 12 02 53 PM" src="https://user-images.githubusercontent.com/48728214/90269114-17f0c500-de26-11ea-93b9-5b311b53f814.png">

**Comment by RLHecht** [comment]
This is now validated on live site. Closing ticket. FYSA @mnorthuis @MickinSahni @bethpottsVADEPO
