### ISSUE TITLE
Create best practices and guidelines for using va.gov-team repo

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1246]
Document information and best practices for how to use the va.gov-teams repo.

**Comment by mnorthuis** [comment]
Draft document started: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/repo-usage-best-practices-DRAFT.md

**Comment by mnorthuis** [comment]
Document finalized and placed in repo for use:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/repo-guidelines.md

**Comment by meganhkelley** [comment]
Reopened to add to applicable epic, closing now.
