### ISSUE TITLE
Health Care application data - Campaign Dashboard

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#12460]
# COVID Dashboard Additions

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?
    _Lauren Alexanderson_
    

## Timeframe for Analytics Requested
 - TBD

## Analytics to Track Down
- entrance/clickthrough/bounce page stats for:
- https://www.va.gov/health-care/apply/application/introduction
- https://www.va.gov/health-care/how-to-apply/
- Funnel data on the application itself
- submissions

## Acceptance Criteria
- [ ] Chart for inbound data to application
- [ ] Chart displaying total number of submissions
- [ ] Funnel data on a page-level 

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@clantosswett Please find the temporary [Health Care application campaign dashboard](https://va-gov.domo.com/page/290380612) here. Any and all feedback you have is very much appreciated. 

@amycesal these charts are also ready for visualization tweaks.

**Comment by joanneesteban** [comment]
## Dashboard Release Checklist

**GA Reporting Specialist:**
  - [ ] For user/session based metrics, create shared GA segment
  - [ ] Stable automated connection to data source, BigQuery where possible
  - [ ] Data is structured in a convenient way to meet the metric with little manual effort
  - [ ] QA data sources to ensure data accuracy & cleanliness
  - [ ] Non line graphs have date ranges (dynamic text boxes)
  - [ ] Cross-team: work with designer to ensure the data is explained
  - [ ] Cross-team: work with designer to ensure each "card" has a data source that is clearly linked & that the link works

**Designer:**

  - [ ] Content is not "too long" so that export is possible
  - [ ] All graphs are logically grouped in layouts so exporting works and feels logical
  - [ ] Each graph and table has appropriate titles & labels
  - [ ] Each graph has appropriate date ranges
  - [ ] Set goal lines
  - [ ] Cross-team: work with GA Reporting Specialist to ensure that data is explained
  - [ ] Cross-team: work with GA Reporting Specialist to ensure each "card" has a data source that is clearly linked & that the link works

**Contact Center Lead:**

  - [ ] Ensure accuracy of contact center data
  - [ ] Contact center data has appropriate dimensions, descriptions, and sources

**Product Manager:**

  - [ ] Groom descriptions for grammar, date ranges, & accuracy
  - [ ] Groom titles for grammar, date ranges, & accuracy
  - [ ] Groom notes for grammar, date ranges, & accuracy
  - [ ] Groom dashboard and charts for flow & usability
  - [ ] Schedule onboarding with VFS PM/PO/Stakeholder

**Comment by joanneesteban** [comment]
### Feedback Notes
(Most is for visualization)
- [ ] Add data source links (to GA)
- [ ] Edit titles (remove BQ, "by date" and "by x" is inconsistent right now; "Intro" and "Introduction" is inconsistent)
- [ ] Add descriptions for "sessions" & why this matters
- [ ] Add descriptions for bounce rates (something around comparing bounce rates and sums to eligible users)
- [ ] Add dashboard description/objective. Something around "Increase online Veteran enrollment to ensure that Veterans are applying for the benefits that they are eligible for and deserve and are doing so safely." (@clantosswett if you have any feedback on the dashboard objective)
- [ ] Is there funnel information? Can we get this through BigQuery?

**Comment by clantosswett** [comment]
@jonwehausen This looks great. I have a few questions/comments on it but overall, this is super helpful to see this data and I think will be very helpful moving forward for many teams at the VA. 

- This might be ignorance but what does BQ stand for?

- The dates seem off on the second chart. It jumps from 2019 to 2020 back to 2019. 

- It would be awesome to get a funnel chart in there to show abandonment rate throughout the entire application. I know Brian is working on that so it might not be ready but when it is that would be great. 

- Is there any way for us to get demographic information? This came up a bit yesterday during a call and it might be interesting to see if there are certain demographics that are more likely to abandon the application vs. not. There might be underlying reasons for this (certain groups of veterans are more likely to be eligible than other groups) but it could be interesting to at least see what the data shows and go from there to try and validate anything we are seeing.

**Comment by jonwehausen** [comment]
Hi @clantosswett , 

Great questions! 

- BQ stands for BigQuery here, just put that there temporarily as a reminder this data is now coming from BigQuery, can certainly be removed. 
- Thanks for calling out! This should now be corrected for all charts. 
- Yes @bsmartin-ep has been working on this and has a working query to produce closed-funnel results. You can see a mock-up (not all data just yet) of the results of his query at the bottom of the dashboard. 

![image](https://user-images.githubusercontent.com/48527022/90635919-d4b49e80-e1f7-11ea-88f0-1f51a3c03e3c.png)

- Please note this is accounting for those users who hit every single step of the application process. We are working on a more sophisticated query that can pivot on various segments and not be as strict as to hitting every step. 
- Yes, we can get basic demographic information like age and gender for entrances and completions easily -- getting this information from a funnel perspective will also come out of our exploration with the more advanced queries.

**Comment by joanneesteban** [comment]
### Additional to do

- [ ] Opening a Content request for the content

- [ ] Adding overall dashboard description: `How might we improve the Screening Tool completions by metro area`

**Comment by joanneesteban** [comment]
Still need to address funnel issues on this dashboard. The funnel hasn't updated in a month, and the title says "July."

Other issues: the first 3 charts haven't updated for September.

**Comment by jonwehausen** [comment]
Datasets and charts have been updated here -- set to standard scheduling of daily.

Will revisit checklist items as next steps

**Comment by jonwehausen** [comment]
@amycesal @joanneesteban 

As a way to reconcile our percentage of total issue that came up with the caregivers dashboard -- I have adjusted the goal funnel datasets to include a "Percentage_Of_Total" column. 

From a visualization perspective, I'm having difficulty determining if there is a way to use the number we calculated through BigQuery as our source of truth to show up in the funnel legend. 

For the time being, I included in the "Percentage_Of_Total" as an additional column within the table below , this may be what we need to do for funnels for the time being where we want to show an accurate percentage of total of each step. 

This percentage of total is the percentage of sessions that reached the given step compared to the total number of sessions from the first step. 

![image](https://user-images.githubusercontent.com/48527022/95791442-5fbd8c80-0caf-11eb-8b4d-f59aed03f504.png)

**Comment by amycesal** [comment]
Redid the colors on this one again to reflect the sections. 
<img width="641" alt="Screen Shot 2020-10-27 at 10 42 32 AM" src="https://user-images.githubusercontent.com/1656046/97325661-3836fa00-1841-11eb-8606-83ee2697d94a.png">

**Comment by bsmartin-ep** [comment]
I refactored the funnel's dataset and cards to have a date column (and calculate `% of total` and `step completion %` dynamically).  You should be able to filter on date now.

https://va-gov.domo.com/page/290380612

**Comment by joanneesteban** [comment]
Awesome, thanks for your work here, @bsmartin-ep ! When we filter by date, it does look like the charts change. The title, however, continues to state "April 1, 2020 - Present." Is there a way to make the title dynamic?

**Comment by bsmartin-ep** [comment]
@joanneesteban - don't think we can do dynamic fields in the actual title, so added to the summary:

![image](https://user-images.githubusercontent.com/62304138/99293007-072e6180-2810-11eb-9b2d-c7427ec52242.png)

**Comment by joanneesteban** [comment]
Iterations for this dashboard is being tracked on #14883. Closing this ticket.
