### ISSUE TITLE
STEM: EVSS dependent functionality is behind a feature flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12469]
As a developer, I need a way to toggle when the SCO email is sent from the staging environment so that SCOs are not being sent test data unnecessarily.

## Assumptions:
1. This leverages the feature flag in #12467.

## Acceptance Criteria
1. The STEM SCO email behavior is based on the feature flag status:
    a. When off, no email is sent to the SCO.
    b. When on, email is sent to the SCO
2. When on, the EVSS service requests the following information: 
   a. Remaining entitlement
   b. Enrollment details (Institution name, Institution city, Institution state)
3. When off, the EVSS service does not request the following information
   a. Remaining entitlement
   b. Enrollment details (Institution name, Institution city, Institution state)

## Supporting Artifacts: 
1. Entitlement alert locations:
    a. https://bahdigital.invisionapp.com/share/YFIAEHK8U2W#/screens/296045008
    b. https://bahdigital.invisionapp.com/share/YFIAEHK8U2W#/screens/296045059

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/13903
- https://github.com/department-of-veterans-affairs/vets-api/pull/4744

**Comment by sonntag-adam** [comment]
On
![Screen Shot 2020-08-19 at 2.58.10 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c96757c8-c633-4de3-a558-4c7bf6f223cc)
##
Off
![Screen Shot 2020-08-19 at 2.59.20 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2be23222-81d4-4fa4-9104-609b52fc6788)
##
On
![Screen Shot 2020-08-19 at 2.58.39 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2c603e14-7425-4e8a-a242-5b73d439e98c)
##
Off
![Screen Shot 2020-08-19 at 2.59.44 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1f0eaec8-99aa-4d00-86ce-7c2abcbaa808)
##
On
![Screen Shot 2020-08-19 at 3.06.30 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1a421f80-df4a-4ac9-8a3f-4f95ed186abb)
##
Off
![Screen Shot 2020-08-19 at 3.03.24 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d93945eb-f821-4709-b867-b5f19166d809)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/11630&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
Merged. Evss blocked.

**Comment by dneel-bah** [comment]
EDU has agreed to launch with an MVP without pulling entitlement / enrollment data from EVSS.  The re-validation in staging will be handled in #12734 once the test data is available in the staging environment.  Closing this story because it has been validated in the local/dev environment.
