### ISSUE TITLE
STEM: Create End-to-End tests for form 10203

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12464]
As a developer, I need to create end to end tests for form 10203, so that there is test coverage to use to test form functionality when there are form changes.

## Assumptions
1. DEPO is moving to Cypress instead of NightWatch, so we should write these tests in Cypress.

## Acceptance Criteria
1. An end to end test is created for each branch of the 10203 to submission.
   a. Axe checks are included in the end to end tests [ see feedback on staging review for STEM ]

## Supporting Artifacts:
1. N/A

**Comment by hughes-dustin** [comment]
For running the Cypress e2e tests:
Go to `vets-website` in terminal and run: 
`yarn cy:run --spec "src/applications/edu-benefits/10203/tests/edu-10203.cypress.spec.js"`. 

Cypress will generate a mp4 for the test located at: `vets-website/cypress/videos`.

**Comment by hughes-dustin** [comment]
Axe checks are automatic so there is no need to create a manual check. See [documentation](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/testing/e2e/cypress/support/form-tester/README.md#accessibility) for more info.

**Comment by hughes-dustin** [comment]
branch: bah-12464
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14007

**Comment by delli-gatti-michael** [comment]
[Cypress_10203_test.mp4.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/5125116/Cypress_10203_test.mp4.zip)

Test passes locally. Captured video atatched
