### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/va.gov-team#12477]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
shawna@adhocteam.us

If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
I want to be able to see click rates on breadcrumbs on desktop and mobile

## Date Required
ASAP

## Product Team / External Team / VA Office
VSA Design Lead

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bmcgrady-ep** [comment]
@sshein - You should now have access to GA. Let me know if you need anything else!
