### ISSUE TITLE
Clean up and update content documentation in parity with Global UX Team

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1247]
and copy over from vets.gov-team (marking the old files as obsolete w/links to the new in va.gov-team)

**Comment by rroueche** [comment]
and copy over from vets.gov-team (marking the old files as obsolete w/links to the new in va.gov-team)

**Comment by peggygannon** [comment]
This is complete. I've been working with Nick and Jen Lee on resource parity (via https://github.com/department-of-veterans-affairs/va.gov-team/issues/1195)
