### ISSUE TITLE
HTML Adjustment for 686 "On this page" from eBenefits

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12470]
## Why you're here
- Content support for static public website pages
- Content support for authenticated application or tools
- For specific copy editing tasks
- Support for redirects that have **first been vetted by the VSP IA team**
- Engineering support for implementation of REACT sign in widgets 

## Steps to complete intake request
- [ ] Submit this request when VSA Public Website team intervention is required
- [ ] Provide detailed information of your request to help us understand our role in completing your request 
- [ ] Link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Selina Cooper 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

## Background
*Provide a background of your tool/functionality.*

* **Is the request related to a VA.gov tool? Provide a brief description of the tool or functionality:**  
   * On the Dependency Claims tool in staging, the links in the "On this page" section seem to be in a section of code that causes them to look not as intended.
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
<details>
       <summary>Click to expand - Current "On this page" section text decoration: underlines and no down-arrows on unordered list</summary>

![Capture](https://user-images.githubusercontent.com/53826255/90182796-80856680-dd80-11ea-9924-c915750c084f.JPG)
</details>
<details>
       <summary>Click to expand - Intended"On this page" section text decoration</summary>

![Screen Shot 2020-08-11 at 10 32 56 AM](https://user-images.githubusercontent.com/53826255/90182896-a4e14300-dd80-11ea-8f62-417506062277.png)
</details>
<details>
       <summary>Click to expand - Possible Solution, per Nick Sullivan: The issue appears to be that the content is inside of an intro text. The actual HTML looks ok.</summary>

![image](https://user-images.githubusercontent.com/53826255/90182978-c6dac580-dd80-11ea-96c0-36483f9c5355.png)
</details>

---

## Request Type
*Select all applicable and provide details behind your request* 

### Content
- [ ] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * **Word document with draft if available, or link to the URL where the draft content appears:** 
     - < link > 
   * **Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?):** 
     - < design context >
   * **Scope: How many screens? (Or messages, etc.):** 
     - < scope > 
      
      
- [x] **Content support for a static public website page**
   * **Is this to update existing static content?** 
     - Yes
   * **Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.):**  
     - No
   * **Provide a list of URL/s that need to be reviewed or updated.** 
      * https://staging.va.gov/view-change-dependents/
   * **If it's a small copy section, list what the new info should be and what it is replacing.**
      * Text decoration for links in the "On this page" section need some tweaking to look as intended

### Frontend  
- [ ] **New URL or Redirect Requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA Redirect Request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*

* August 24, 2020

---

### Requestor info
*Indicate what team and who the primary contacts are on your team* 

- Team name: *eBenefits*
- DEPO product owner: *Steve Kovacs*
- Product manager: *Jason Wolf*
- Designer: *Jim Adams*
- FE engineer: *Micah Chiang & Jesse Cohn*
- Product/team Slack channel: *#vsa-ebenefits*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by sshein** [comment]
Slack discussion about this can be found here: https://dsva.slack.com/archives/CLY6Q69RV/p1597167248200000

**Comment by jason-gcio** [comment]
Tagging @sshein here in case she would like to add any other context for this.   Link to previous conversation: https://dsva.slack.com/archives/CLY6Q69RV/p1597167248200000

**Comment by lunascoop** [comment]
Looping you in @DanielleThierryUSDSVA

**Comment by sshein** [comment]
this is an particular use case of potentially a much broader question - how do we make sure the "On this page" table of contents component is an actual "component" both in Drupal and in our design system, designed in a single consistent way (e.g. the way it's designed on the Pittsburg pages https://www.va.gov/pittsburgh-health-care/health-services/

**Comment by sshein** [comment]
ideally we would solve for the smaller use case (Jason's page) but also document and start solving for the larger use case

**Comment by MickinSahni** [comment]
@RLHecht to evaluate next steps in this sprint

**Comment by RLHecht** [comment]
I've changed this so that the "On this page" is out of the intro. I checked the "Include table of contents?" so it's now showing as that. Just note it goes below the featured content blue box so not directly below the intro text like it was previously in the bigger font. See screenshot: 
<img width="871" alt="Screen Shot 2020-08-26 at 4 13 42 PM" src="https://user-images.githubusercontent.com/48728214/91351961-1e345900-e7b7-11ea-9a4d-0739576fb7bd.png">

This is currently set as draft in Drupal. Please let me know if it's good and I can set to publish. FYSA @DanielleThierryUSDSVA 
 
Preview node ID: preview-prod.vfs.va.gov/preview?nodeId=6663

**Comment by lunascoop** [comment]
@jason-gcio the HTML adjustment is ready for review via this Drupal preview link: preview-prod.vfs.va.gov/preview?nodeId=6663. The change has been made in "Draft" mode in Drupal and has not been published. Once you "ok" the change, @RLHecht can re-publish the page so that you can see the update in staging.

**Comment by MickinSahni** [comment]
Hey @jason-gcio can you take a look so we can wrap up publishing?

**Comment by sshein** [comment]
@sporeboy might want to take a look as well since placement changed a little

**Comment by jason-gcio** [comment]
@lunascoop / @MickinSahni / @sshein 
Will do - sorry for the delay.  
Chatting with Jim on this now

**Comment by sporeboy** [comment]
Apologies for being late to this discussion.

It seems the "On this page" element needs to be above the fold on screen load so the user can access the jump links right away. So it should sit immediately below the intro paragraph below the H1, and above the blue box. That has the added benefit of creating a more natural flow between the blue box content about dependents/eligibility, and the accordions that answer questions about dependents.

There are differences in the leading (vertical spacing is tighter in the original) of the lines, and the arrows themselves (they seem be different icon fonts) between the original design example and the execution. Likely I'm the only one who sees them... :-) 

I suggest moving the "On this page" element to ahead of the blue box. This will position the jump links so they can be seen on page load; and this will alleviate the interruption of related content regarding dependent eligibility and the QA accordions.

**Comment by RLHecht** [comment]
There was a bug affecting the placement of the TOC on pages. This has now been fixed and it's showing above the featured content box.
<img width="909" alt="Screen Shot 2020-09-04 at 9 38 55 AM" src="https://user-images.githubusercontent.com/48728214/92245497-74c62500-ee92-11ea-9192-734c855ca813.png">

Let me know if this is now ready to set to publish.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @RLHecht!

**Comment by sporeboy** [comment]
Works for me... Thank you! :-)

**Comment by jason-gcio** [comment]
Agreed, thank you @RLHecht - we are good to go for this to published.

**Comment by RLHecht** [comment]
Just published the page. This should be live later this afternoon.

**Comment by RLHecht** [comment]
This page is now live and correct on staging. Closing ticket. FYSA @MickinSahni
