### ISSUE TITLE
add SSOe application logging to new_stats and login_stats

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#12487]
Our statsd (grafana) success rate is determined by looking at the quotient of the `login_stats` call over the `new_stats` call.  We should add application logging values to these methods, so we can calculate that same value when looking at the application logs.

**Comment by benniemosher** [comment]
Added logging statements to provide more data. See PR to see what was done. https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets-api/issues/4761
