### ISSUE TITLE
SPIKE: review login stats for v0 and v1 authentication

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#12489]
Review the v0 and v1 sessions controller `new_stats` and `login_stats` methods to make sure they are being evaluated in identical ways.  If they are not then we can't compare the login success rates on the grafana dashboard.

**Comment by christine-dillman** [comment]
@patrickvinograd Found no discrepencies and therefore this issue is closed.  ncd
