### ISSUE TITLE
Enhance smoke tests with CodeBuild report feature

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#12490]
"As an SSO product owner or developer, I want more granularity about which SSO smoke tests are passing or failing without having to read through the raw logfile."

Optional enhancement: once the smoketest job in #6177 is working reliably, it would be great to have it spit out a report that can be surfaced in the codebuild console. Per this blog post, you can add a definition of a report file to the buildspec, and it understands the Cucumber JSON test result format:

https://aws.amazon.com/blogs/devops/test-reports-with-aws-codebuild/

I don't know what the effort would be to make the current testing framework output in this format, so this task definitely requires some triage/investigation.

**Comment by AGarcia-Clarity** [comment]
Did some research into adding the CodeBuild reports feature and it looks like there isn't a huge lift as far as integration is concerned.  It does look like it needs permissions via AWS's IAM to run it though and would have to look more into it.

**Comment by AGarcia-Clarity** [comment]
@nsoutouras We can probably close this as we've decided to go in a different route with creating the Inbound/Outbound tests & Unit testing in the FE.
