### ISSUE TITLE
STEM: 22-1995 UXBA Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12499]
Review new, non-STEM 22-1995 prototype @ UXBA Sync 
Incorporate input

**Comment by amyknox** [comment]
[https://app.zenhub.com/files/133843125/50ca5e6f-7d8f-47f2-b00f-a8e610bbe171/download](https://app.zenhub.com/files/133843125/50ca5e6f-7d8f-47f2-b00f-a8e610bbe171/download)

**Comment by amyknox** [comment]
Discussed at UXBA sync, no significant issues. Agreed to share with EDU at regular Monday mtg, 9/14

**Comment by amyknox** [comment]
[Updated recommendations doc](https://app.zenhub.com/files/133843125/8704cc5a-645c-44f7-8e67-9ab8046926c5/download)

**Comment by ccruzgra** [comment]
@amyknox Would you like to close this or keep it open in case we need to go over the 1978 issue for the next UXBA Sync?

**Comment by amyknox** [comment]
Closing this. Any updates to routing / logic for Chapter 30 & periods of service before 1978.
