### ISSUE TITLE
STEM: 10203 Content Updates -  VSP / UAT

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12496]
Update content doc per VSP / EDU input

**Comment by amyknox** [comment]
As of 8/28, includes
- Twilio update
- Personal info / Best way to contact you update

Additional updates may result from UAT (scheduled for 8/31, 9/1)

**Comment by ccruzgra** [comment]
These enhancements address 2 updates from UAT and VSP, both on the Personal information page:
* Including sentence & checkbox about Twilio
* Reformatting the page to address Best way to contact you & required fields

Content doc v0.6 updates can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md

Anchor link to specific Personal Information updates: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md#chapter-title--5-of-6--personal-information

Accompanying prototype updates can be found here (v0.6): https://bahdigital.invisionapp.com/share/FAIAEVUYVKN

**Comment by amyknox** [comment]
@amyknox - update twilio note in content doc
