### ISSUE TITLE
STEM: 22-1995 Prototype Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12498]
Create new, non-STEM  22-1995 prototype

**Comment by ccruzgra** [comment]
Prototype link where updates will exist for post-STEM 1995 application: https://bahdigital.invisionapp.com/share/VUIAEXFPHBC

**Comment by ccruzgra** [comment]
All the prototype updates are now in. UXers will take a look, and Amy will update the content doc based on some feedback I shared with her.

**Comment by ccruzgra** [comment]
Amy provided some feedback, which I incorporated this morning into the prototype. She'll be taking a final look.

**Comment by amyknox** [comment]
@ccruzgra - prototype looks great. I dropped in a couple comment that, if actionable, are minor tweaks

**Comment by ccruzgra** [comment]
@amyknox Those were taken care of.
