### ISSUE TITLE
STEM: 10203 Prototype Updates - VSP / UAT

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12497]
Update prototype per VSP / EDU input

**Comment by ccruzgra** [comment]
These enhancements address 2 updates from UAT and VSP, both on the Personal information page:
*Including sentence & checkbox about Twilio
*Reformatting the page to address Best way to contact you & required fields

Prototype updates can be found here (v0.6): https://bahdigital.invisionapp.com/share/FAIAEVUYVKN

Accompanying v0.6 content updates can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md

Anchor link to specific Personal Information updates: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md#chapter-title--5-of-6--personal-information

**Comment by amyknox** [comment]
Connect with Trevor quickly to consider accessibility implications here.

**Comment by ccruzgra** [comment]
Scheduled a meeting with Trevor and sent UI mockups for him to preview.

**Comment by ccruzgra** [comment]
Met with Trevor and he had a couple of suggestions for how we could address accessibility concerns with the integration of the Twilio checkbox. His preference was for having a checkbox option beneath the mobile field, but with an additional warning alert if the user hadn't yet included a mobile phone number, and also displaying an error message for the mobile phone number field if the user chose to continue anyways. His second preference was for the conditional display of the checkbox if the user starts typing in a mobile phone number into the text field.

**Comment by amyknox** [comment]
@amyknox - check out Review application & Summary page for Twilio integration asap.

**Comment by ccruzgra** [comment]
As Amy mentioned, she'll give the prototype a final look-see since all updates are in, including updates to the Review Application page for the Personal Information accordion.

**Comment by amyknox** [comment]
The updates look great. Anything else required before closing the story?

**Comment by ccruzgra** [comment]
@amyknox That's it for me!
