### ISSUE TITLE
Left Nav doesn't build in DevShop

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12491]
## What happened?

Devshop instances for VISN-19 build without Left Navigation, including: 

- Cheyenne health care
- Eastern Colorado healthcare
- Western Colorado healthcare

<details>
<summary> Example screenshot </summary> 

![image (45).png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/16aff37d-1e79-49c9-8db7-e4d24b7823a1)

</details>

## Acceptance Criteria
- [ ] _All content should publish to lower environment, including navigation components

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
`FACILITY_MENU_NAMES` in `src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js` is hard-coded. Need to add the missing VAMC's to fix.

**Comment by mmiddaugh** [comment]
Will need help from @ethanteague for testing in Dev Shop

**Comment by SgardnerPMP** [comment]
@mpelzsherman Please be advised.  Left Navigation did not appear for Eastern Colorado or Oklahoma City.   Rebuild systems in Devshop and those are the only two that did not come up correctly.  Rebuilt them twice to confirm.  Reviewing if there are any issues in Production now, have confirmed no issues in Prod for East. Colorado, reviewing Oklahoma City now.  Please assist with fixing these two issues.  Respectfully. 
![EasternColorado_No_LeftNav](https://user-images.githubusercontent.com/56848714/93234118-c2634d00-f730-11ea-8489-d6e1a32f197e.jpg)

**Comment by brangi** [comment]
I debugged this locally last night and I can tell it's not a left nav issue but content or some sort of transformation issue. So what the left nav is missing is some items (links) with parentId after it's data normalized. This is needed to build the left nav - 

https://github.com/department-of-veterans-affairs/vets-website/blob/311f26c9382a0aa2ba8cd732ed4b0a3c282e31e9/src/platform/site-wide/side-nav/components/SideNav.js#L51


I also checked the differences being outputted by pages showing nav vs the one that does not and I can see in the one that is not showing it is missing a root level. Hopefully these photos can highlight what I am referring too.  


<img width="1374" alt="Screen Shot 2020-09-16 at 9 53 47 AM" src="https://user-images.githubusercontent.com/100468/93357204-a9789b80-f805-11ea-90b8-4d0df70dabe6.png">

<img width="1422" alt="Screen Shot 2020-09-16 at 9 53 39 AM" src="https://user-images.githubusercontent.com/100468/93357257-b72e2100-f805-11ea-88ac-f4b9dfc47cf7.png">

<img width="1418" alt="Screen Shot 2020-09-16 at 9 53 31 AM" src="https://user-images.githubusercontent.com/100468/93357292-bdbc9880-f805-11ea-8eae-308590566593.png">

**Comment by kevwalsh** [comment]
As mentioned on Slack: i fixed the Eastern Colorado menu, to make those three all caps menu items nested under the parent. 

That one is a data problem. 

Is there another left nav that's not working?

**Comment by mpelzsherman** [comment]
@SgardnerPMP - can you please try again and let us know if there are any further issues?

**Comment by SgardnerPMP** [comment]
Eastern Colorado has been rebuilt, published and Left Nav is up and running.  Going on to test Oklahoma City Left NAV.  Thank you!

**Comment by SgardnerPMP** [comment]
@mmiddaugh @kevwalsh , Are we still working on Oklahoma City in production?  The Devshop environment will not reload and continues to fail.  I wanted to check with you both before I submit a support case.  I'm also thinking of deleting and rebuilding the Oklahoma instance if you think that will help resync it with Production.  Thank you.
