### ISSUE TITLE
School Ratings: Content Review  - EDU

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12503]
Gather input on design & content 
Refine / update content as necessary

**Comment by amyknox** [comment]
Was going to add Luke's comment about "the content looks great" from EDU meeting earlier this sprint but can't track it down in mtg notes.  Will send over content doc (attached) for their review with 8/27 mtg agenda.

[https://app.zenhub.com/files/133843125/0037f234-34b9-485e-bba9-02a89595485d/download](https://app.zenhub.com/files/133843125/0037f234-34b9-485e-bba9-02a89595485d/download)
