### ISSUE TITLE
STEM: 22-1995 EDU Review	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12500]
Review new, non-STEM  22-1995 prototype w EDU

**Comment by ccruzgra** [comment]
Reviewed the initial 1995 prototype with EDU today. Overall, the response was very positive. They did have mention that we may need to update the form's flow to only direct Chapter 30 applicants to the 1978 question, and subsequently, to the dependents page.

**Comment by amyknox** [comment]
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/ef12eed4-3de4-458f-b3d6-63d23810ebc3)
