### ISSUE TITLE
CT Site Search:UI Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12517]
Design UIs for prioritized solutions 
Review with UX  
Incorporate input

**Comment by ccruzgra** [comment]
Prototype for CT Search and Filter updates (v0.3): https://bahdigital.invisionapp.com/share/PVIAEVAXHK7

**Comment by ccruzgra** [comment]
Accompanying content doc (v0.3): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/search/design/content-doc-v0.3.md

**Comment by ccruzgra** [comment]
Waiting on UX review before closing this story.
