### ISSUE TITLE
CT Site Search: Solution identification

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12516]
Create draft solutions for key updates

**Comment by amyknox** [comment]
Mobile UI solution - Confirm whether we could display counts for "See Results" button. (roundtable)

Heading style cascade... allow for correct flow but also support accessibility.

**Comment by amyknox** [comment]
Mobile UI solution - We CAN display counts for "See Results" button. (roundtable)

Heading style cascade... we CAN work with CSS to support correct flow of headings and also support accessibility.
