### ISSUE TITLE
[SCREENREADER]: GIBCT® VETTEC - Can we move the Learn more buttons out of the label tags?

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1251]
## Description

The first page of GIBCT® has several `Learn more` buttons that open modals to help users learn more about the benefit in question. These buttons are wrapped inside the `<label>` tag, which is causing some issue with screen readers like NVDA. Users normally can press `ENTER` when the label has virtual cursor focus and move into the related input in forms mode, but the way these are coded, the modals are opening instead. Screenshot attached.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screen reader (NVDA) user, I want to be able to press `ENTER` on the label and have focus set on the related input.
* As this user, I want to be able to focus the `Learn more` button as a separate element, and press `ENTER` or `SPACE` to open the modal window.

## Environment

* Windows 10
* Firefox latest
* NVDA
* https://staging.va.gov/gi-bill-comparison-tool/

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## PR
https://github.com/department-of-veterans-affairs/vets-website/pull/10626

## Screenshots or Trace Logs

![Screen Shot 2019-08-22 at 4.21.54 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/b8ae043f-bd5a-4798-80ed-83dc264e7d67)

**Comment by delli-gatti-michael** [comment]
Passes local testing

**Comment by 1Copenut** [comment]
@delli-gatti-michael Can you send me a PR number or feature branch? I can re-test it ahead of the staging environment and close the issue ticket. Otherwise LMK when it's in Staging and I'll retest at that time. Thank you.

**Comment by desireeturner** [comment]
@1Copenut Here's the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/10626

**Comment by 1Copenut** [comment]
@desireeturner I need to keep working with this item. Please do not merge it yet. I'm still having trouble with screen readers handling the Learn More button when it sits between the label and the input. Will work on a solution tomorrow and see if there's a way to improve, or if the current implementation is better than the proposed adjustment.

**Comment by desireeturner** [comment]
@hughes-dustin see @1Copenut message above. Please hold on merging department-of-veterans-affairs/vets-website#10626 in anticipation of more information.

**Comment by 1Copenut** [comment]
@desireeturner && @hughes-dustin 
I'm going to follow up with the DSVA design lead on this one. My preliminary suggestion to move the `<button>` out of the `<label>` didn't behave as expected with screen readers. Please hold on merging, and I will follow up when we have guidance on a good fix.

**Comment by desireeturner** [comment]
@1Copenut Sounds good. I moved this to the Icebox until we receive a path forward on implementation.

**Comment by desireeturner** [comment]
@1Copenut any update on this issue and path forward?

**Comment by 1Copenut** [comment]
@desireeturner Not yet. I'm assembling findings and taking them to the right personnel today to see what we can come up with.

**Comment by 1Copenut** [comment]
@desireeturner I met with @KevinMHoffmanUSDS && @jenstrickland yesterday to discuss the related issue #1817. We came up with some proposed improvements, and I'll follow up here when those are approved and ready to move forward.

**Comment by jenstrickland** [comment]
@peggygannon Here's the original ticket, and here's the Codepen with @1Copenut proposed improvement: https://codepen.io/tpierce_402/pen/PoYVKKa

**Comment by desireeturner** [comment]
@1Copenut Any updates on this issue and path forward?

**Comment by 1Copenut** [comment]
@desireeturner We're in use testing of a new design way this week and next. After that we'll collect the data and make recommendations for keeping existing or making a new component.

**Comment by desireeturner** [comment]
@1Copenut Is this something we should keep open?

**Comment by 1Copenut** [comment]
@desireeturner I took a look at this in Staging briefly. The Learn More buttons have been moved out of the `<label>` elements and so default behavior has been restored. I'll move this to close.
