### ISSUE TITLE
IA Request VA.gov COVID-19 Research Landing Page & Registry

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#12524]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/covid-vaccine-trials/product-outline.md
- Link to or attach prototype or mockups: https://staging.va.gov/covid-research-volunteer/
- Link to research readout/results: Ask for Mural link in Slack for raw notes; synthesis will be here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/covid-vaccine-trials/research
- Link to [reserach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach final content including H1s (if separate from prototype/mockup): https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/covid-vaccine-trials/content

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords** - COVID-19 COVID vaccine clinical trials research registry medical trials medical research

**Proposed site map/page structure** - Landing page >>> Registry form >>> confirmation page

**Suggested URL(s)** - https://dsva.slack.com/archives/C01706RQ5MZ/p1597344830153000

**Suggested entry points** - Either crosslinked from other COVID content, directly from a communication (e.g. email, text, sign, flyer, etc...), or organic search

**Crosslinking opportunities** - Coronavirus FAQ; Coronavirus chatbot; maybe facilities

**Redirects/canonical tags** - Nope!

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
Draft URLs:
static page: www.va.gov/coronavirus-research/
sign-up form: www.va.gov/coronavirus-research/volunteer/

Additional draft IA information found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/cto-covid-trials.md

Remaining open items:
- Confirm URLs and entry points with Danielle

Will post when the info is finalized.

**Comment by mnorthuis** [comment]
IA was finalized and product was launched.
