### ISSUE TITLE
[Documentation] Add `editModeOnReviewPage` to forms library

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#12528]
### What is your documentation request, question, comment, or issue?

The `editModeOnReviewPage` form config page option is not documented on this page - https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/config-options - or any others.

**Comment by taylorkaren** [comment]
Potential need to add to docs FLT is updating in Q1 2022.
