### ISSUE TITLE
[Tech Debt] 526: Discovery Around "Submission is Taking Longer than Expected"

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12539]
## Issue Description
It looks like when we fail with a bad zip code, it "times" out for the user instead of displaying a real failure message.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Robin placed a fix (actually just added a delay) before it checks the submission endpoint for errors so it may have solved this issue.

**Comment by vhenry07** [comment]
Closed per grooming session 2/4. Front end issue fixed.
