### ISSUE TITLE
[SCREENREADER]: GIBCT® VETTEC - We should set focus on the H1 when users click Search Schools and school detail links

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1253]
## Description

We are not managing focus when users click on the `Search Schools` button or click on a school detail link like "GALVANIZE INC". This focus management is important for screen reader users to understand something has changed on the page. Screenshots attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screen reader user, I want to hear "16 search results, heading level one" when I am routed to the search results page.
* I also want to hear "Galvanize Inc, heading level one" when I am routed to a VETTEC school detail view.
* As a tester, I want to be able to verify the H1 is focused by entering `document.activeElement` on the Dev Tools console.

## Environment
* MacOS Mojave
* Chrome latest

## Possible Fixes (optional)
We should use the existing focus helper and look at the `componentDidMount()` lifecycle method for setting focus. Will need to add a `tabIndex` to the H1:

```javascript
<div class="vads-l-col--10">
  <h1 tabIndex={-1}>16 Search Results</h1>
</div>
```

## WCAG or Vendor Guidance (optional)
* [Focus Order: Understanding SC 2.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html)

## PR
https://github.com/department-of-veterans-affairs/vets-website/pull/10638

## Screenshots or Trace Logs

![Screen Shot 2019-08-22 at 4.57.52 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/4fa0d386-9790-4273-876f-3f34da2830d0)

---
![Screen Shot 2019-08-22 at 4.57.59 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/1415a886-4285-4336-bd7c-dd675d6d1cd7)

**Comment by dmccurdybah** [comment]
@1Copenut Sounds good. I made the requested changes and also unlinked this from the PR because we need these to be in different pipelines.

**Comment by dmccurdybah** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/10638

**Comment by sonntag-adam** [comment]
![Screen Shot 2019-09-06 at 9.49.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e09a5a82-92e8-4086-a4e0-e2b75c810a9f)
##
![Screen Shot 2019-09-06 at 9.52.23 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f6dc8a3a-aea3-4eaf-a599-66e4cc27121b)
##
![Screen Shot 2019-09-06 at 9.50.14 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/618db52b-fa6b-443a-b689-21afb2e1fc39)
##
![Screen Shot 2019-09-06 at 9.50.34 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0e8c104f-0ff7-431e-9927-555d9fb66e6d)

**Comment by sonntag-adam** [comment]
@1Copenut this is now in staging for review.

**Comment by 1Copenut** [comment]
@sonntag-adam Tested in the following screen reader pairings:
* Win10 + JAWS + IE11
* Win10 + JAWS + Chrome
* Win10 + JAWS + Firefox
* Win10 + NVDA + Chrome
* Win10 + NVDA + Firefox
* MacOS + VoiceOver + Safari

All behaved as expected. Works great and improves understanding of route change. Moving to close.
