### ISSUE TITLE
[Tech Debt] BDD: Ensure We Check for Real Zip Codes

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12538]
## Issue Description
We failed a BDD (so 526) submission that failed in staging when a fake (11111) zip code was entered. We should check against real zip codes, this already happens in vets360 and possibly other places.

We should be able to talk to facilities team about an API. Luke to reach out to one of their devs.

## Acceptance Criteria
- [ ] Do not allow submission of fake zip code

**Comment by ndsprinkle** [comment]
After some digging into this, I am going to close this ticket. There is currently no implementation in forms (or elsewhere) to check that the zip code is real. Every location, even platform's default address definition, uses a regex expression to verify a 5 or 9 digit zip code. This is the same functionality currently implemented in all address parts of 526/BDD. If at some point this changes and there is a client side list that we can validate against, we can revisit.
