### ISSUE TITLE
Update feature toggle documentation to include unauthenticated testing

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#12548]
## Issue Description
There's evidently a way to enable feature toggles for unauthenticated users by using a `FLIPPER_ID` cookie, but we don't have it documented in our [feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles).

Source: @patrickvinograd [in Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1597686184088200?thread_ts=1597680499.074300&cid=CBU0KDSB1).

---
## Tasks
- [ ] Discover how this works
- [ ] Document it

**Comment by laineymajor** [comment]
@ndsprinkle merge with current documentation epic, please

**Comment by ndsprinkle** [comment]
New feature toggle documentation location: https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Using+feature+toggles+to+progressively+release+changes

Still doesn't look like it references `FLIPPER_ID` anywhere, so I guess it's still worth investigating.

**Comment by laineymajor** [comment]
@npeterson54 Is this ticket relevant to your team? I would like to remove fe-tools, but don't want this to get lost. Let me know your thoughts. Thanks!

**Comment by ndsprinkle** [comment]
@laineymajor Upon further review, this information is already covered here: https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Feature+toggles+guide#2.-Configure-Flipper-UI-settings

In the "Use case" column for "Percentage of Logged in Users", there is information on how to use the `cookie_id` for unauthenticated users. This is referring to the same thing as `FLIPPER_ID`, so nothing needs to be updated. (`FLIPPER_ID` is what we call the variable in the front end, but `cookie_id` is the actual param we pass to the back end, so it would be the more appropriate term) 

I also double checked the slack thread linked above as well to make sure there was no information in there worth adding. The only thing of note was some info on how you would force an unauthenticated user to have the `cookie_id` you created. It essentially involves walking the user through the developer tools in their browser. I think this a very uncommon scenario and isn't relevant enough to add to this section of documentation, so I'm going to close this ticket.
