### ISSUE TITLE
Iteration 1: Build the FE template for Checklist, Video, Images learning center content types

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#12541]
## Iteration 1: Build the FE template for Checklist learning center content types

The FE build for iteration 1 is to start mapping the middle layer of the templates, based on Ryan's designs and the template requirements. 

**The CMS templates for this ticket are:**

- Checklist (Related [CMS ticket #2315](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2315 )
- Videos (Related [CMS ticket #2454](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2453undefined) )
- Images (Related [CMS ticket #2453](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2453undefined) )

_Note: The CMS templates currently **don't** include the sandwich bread layers:_

- Tags taxonomy
- Need more help
- Was this useful
- Related info/articles

**There are some global template elements that will eventually need to be built for all or most of the templates:**
- breadcrumb
- in-body alerts
- TOC links logic
- Back to top page height driven logic
- _There may be other global FE template elements that I'm not including here, and that you may want to triage to include with this work or to break out later as separate work._ 

**Design mocks:**
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files

**Global template requirements:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md

**Content type template requirements:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#specific-lc-content-template-types

---
## Tasks
- [ ] breakdown components in this ticket

## Acceptance criteria
- Frontend template built for Checklist learning center content types
- Can be validated by previewing in CMS
  - don't include the sandwich bread layers from above

--------------

**Related tickets:**
[#12537 - Enter sample LC checklist content in CMS, so FE engineers have something to test FE template work](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12537)

[Learning Center CMS devshop environment for FE engineers](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2561)

--- 

Open question
- [ ] should we breakdown this ticket further?

**Comment by MickinSahni** [comment]
3 separate tickets for the 3 new types (checklist, video, images) just like #13133 etc.

**Comment by MickinSahni** [comment]
@brianalloyd to create 3 separate tickets for the 3 new content types: checklist, video, images. 
Those tickets will live under this epic (#12541)
You can use #13134 as a good model for what to include, etc.
Assign it to Kelson for him to groom/review/estimate and we'll add it to this sprint (sprint 30)!

**Comment by jenniferlee-dsva** [comment]
closing and separately ticketing for 1.1 finalizing work. these look almost done if not totally done. just needs design, mobile, and accessibilty validation.
