### ISSUE TITLE
STEM Form 22-10203: Enable basic authentication for STEM form URL

### ISSUE THREAD

**Issue by shawkey-daniel** [department-of-veterans-affairs/va.gov-team#12542]
## Description
The STEM Form 22-10203 is set to go live in preparation for UAT no later than August 24, 2020. Form is behind feature flag, but password may be needed to mitigate possible direct access to form URL.

The STEM Form 22-10203 can be found here: [STEM Form 22-10203](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203)

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by desireeturner** [comment]
We're going to test this in staging before we deploy to production. Production deploy planned for sometime before noon on Friday 08/20.

**Comment by desireeturner** [comment]
This is now enabled on Production.
