### ISSUE TITLE
Analytics Reporting Request for VA.gov Search (On-site + Off-site)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#12543]
## Description

To better understand the effectiveness of (WBC) VA.gov's on-site and off-site search as a primary discovery tool, we conducted a quick scan analytics review -- via Google Analytics, Google Search Console and SEMRush (a licensed third party tool) to find answers for key questions, including:

- **On-Site**
   - How important is on-site search as a discoverability tool for VA.gov users? In other words, How often is search used by site visitors?
   - How effective is VA.gov's search tool at providing the information users/veterans are seeking?
   - What are users searching for on VA.gov?

- **Off-Site**
   - What are the top referrals of off-site/organic Search traffic for VA.gov?
   - In percentage terms, how much has organic search traffic grown since the launch of modernized VA.gov in November 2018

We were able to find data for some questions, but not all.  And the numbers and conclusions drawn require vetting from the Analytics team.

A note: While the relatively recent implementation of  Google Search Console & Bing Web Developer Tools has provided new insight about organic search behavior, on-site search analysis is hindered as a result of a gap: click tracking for on-site search queries, powered by Search.gov.   A solution is in development and may be available by September.

The "ask" is for the Analytics team to:

- Vet/validate the [Top Questions data assembled](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/search/research/top_questions.md) -- and correct, refine as needed.   
- Determine if custom tracking and/or reports are needed to capture missing insight
- Determine if a GA or DOMO dashboard for on-site (and possibly off-site) would help drive efforts for on-going monitoring, measuring and enhancement of VA.gov's "discoverability factor" for users.

- What team/project is this work for?
    -  Public Website
    
## Timeframe for Analytics Requested

- [Phase I of the VA.gov Search initiative is well underway](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/search/phase_one.md), with a variety of tactical projects in progress, including implementation of on-site [Type Ahead](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8896).   
- Optimally, the process of vetting and refining the Top Questions would be completed by early September.
- If custom tracking, reporting and dashboarding is needed, this ideally would be in place by end of September.

## Analytics to Track Down

The specific analytics -- as [outlined in this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/search/research/top_questions.md) -- include:

- the average number of VA.gov (modern) searches conducted monthly
- what topics/content/tasks are being searched the most?
- how many pages of results does a user view after executing a search?
- the number/percentage of exits from VA.gov site that occurred following a result from an internal search?

## Which Product Questions are you trying to answer?

- How important is search, as a tool/utility, for VA.gov site users?
- How relevant are results provided by VA.gov search?
- How effective are VA.gov "landing pages" in answering users' questions?

## Other Helpful Questions to think through
- **Who is your audience?** VA.gov site users, in particular Veterans.

- **Why do you need this data?** To understand the "problem space" -- e.g. to determine if VA.gov search is in need of enhancement, or "fine as is."

- **What are you hoping to find?** The data the validates the effectiveness or ineffectiveness of VA.gov search (both on- and off-site)

- **What is your hypothesis that you're hoping the data will support?**

- What area of the VA are you hoping to assess?

  - On-site Search (global)
  - Off-site Search 

- How frequently do you need this data?

  - On-demand, daily

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._

> Please leave the following blank

## Acceptance Criteria
- [x] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [x] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@johnhashva We will be taking a look at this and getting back with you -- stay tuned for some follow-up questions that may arise following our review

**Comment by bmcgrady-ep** [comment]
@johnhashva - I went through each of the specific analytics and documented in this [document](https://docs.google.com/document/d/1yg1ja8CRJqzk42dqNqiRUvdcR11D26JZL-OuTdeeSrc/edit?usp=sharing). @jonwehausen will be reviewing it and following up with next steps.

**Comment by denisecoveyduc** [comment]
@denisecoveyduc  to schedule meeting with the analytics team - Nov 5/6 if available. 

Meeting Prep: S&D team to review Analytics document link above.

**Comment by jonwehausen** [comment]
Updated sheet as of 11/9: https://docs.google.com/document/d/1yg1ja8CRJqzk42dqNqiRUvdcR11D26JZL-OuTdeeSrc/edit#

**Comment by jonwehausen** [comment]
@denisecoveyduc @johnhashva 

[Here](https://docs.google.com/presentation/d/1Qlwon8_2iaOb_q1SGkskG0TuYgTdnjQnydf4RR2y9A4/edit?usp=sharing) is the slide deck we walked thru today. 

We are very much looking forward to working with you! 

cc: @joanneesteban for visibility.

**Comment by jonwehausen** [comment]
@denisecoveyduc We will keep this ticket open per any follow-up questions you may have. 

We will move to our Review VFS column as we await to hear from you and your team again.
