### ISSUE TITLE
[Discovery] Distinguish between appointment types - in person, phone, video

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12551]
Feedback that it's confusing which appointments are which - in person, phone, or video. Only video has some clarity because different appointment type altogether. 

## To include in discovery:
- which appointment formats (visit, phone, video) are available for each care type, and if this is something that's configurable at the facility or system level
- Currently, the VAOS legacy tool offers all three appointment formats for all types of care, even when some formats may not be available at a given facility.
- Discovery on whether there are any services that provide appointment format data for care types, facilities, appointment reasons, or any other primary category is documented in this ticket or GH.
- Documentation exists in GH for a table that definitively shows which appointment formats should be available for each care type (or by any other metric that differentiates availability for appointment formats)

**Comment by laurenernest** [comment]
Addressed in homepage refresh #19237
