### ISSUE TITLE
STEM: Add country to school address information (Chapter 3)

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12553]
As a student I need to be able to specify foreign schools for the STEM scholarship application so that I can complete the application with accurate information.

## Assumptions:
1. This work is done behind feature flag #7271.

## Acceptance Criteria
1. The user can specify the country of the school.
2. The country field:
    a. is required.
    b. is pre-populated with "United States" if the user is not authenticated
    c. is pre-populated with "United States" if the user is authenticated and does not have enrollment information available via EVSS.
    d. is pre-populated with the most recent enrollment country if the user is authenticated and has enrollment information available via EVSS.
3. If the selected value for country is not "United States":
    a. the "State" field is not required
    b. the "State" field allows free text
4. The country field is included in the spool file (SA3).

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/DGIAEP75WKA#/screens/296046743) as of 08/17
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/514c73ab362e53c01952459bb8d27ebbf297c95c/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-post-staging-review-v0.5.md#form-title-apply-for-the-rogers-stem-scholarship-6) as of 08/17
3. [10203_Spool_20200817_story_version.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5090532/10203_Spool_20200817_story_version.docx)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/13937
- https://github.com/department-of-veterans-affairs/vets-api/pull/4758

**Comment by dmccurdybah** [comment]
There will be two additional PRs to update vets-json-schema for vets-website and vets-api, but this can be tested as-is

**Comment by dmccurdybah** [comment]
vets-json-schema PR (not required for testing): https://github.com/department-of-veterans-affairs/vets-json-schema/pull/483

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-20 at 12.37.20 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d4d7d3ac-17c7-494a-92aa-295e6e4bde7f)
##
![Screen Shot 2020-08-20 at 12.37.40 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/519a99d7-876f-4cf9-a358-bab5aee7c857)
##
![Screen Shot 2020-08-20 at 12.37.48 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2264904b-9dbc-4a03-a7fd-e7af5af94e19)
##
![Screen Shot 2020-08-20 at 12.38.43 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bd9980f8-aef6-41eb-b244-d3e25decdc23)
##
![Screen Shot 2020-08-20 at 12.38.55 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c92edf36-6a39-4b4f-97cb-dddc9dbf5c07)
##
![Screen Shot 2020-08-20 at 12.53.46 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0b6778cc-02cf-4fe2-9598-66e453b957cd)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-20 at 1.00.09 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3f50ba91-0695-43c0-9e2b-797f2c7cff3f)
##
![Screen Shot 2020-08-20 at 1.13.47 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/560cd264-4d37-4c76-845f-17471ba699c9)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/11640&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by dmccurdybah** [comment]
Field order PR: https://github.com/department-of-veterans-affairs/vets-website/pull/13984

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-08-24 at 12.10.22 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2323ff81-92b6-44ef-b075-7263ed5ddc17)

**Comment by sonntag-adam** [comment]
Fixed in staging. AC 2 c/d blocked due to EVSS and all other ac checks out.

**Comment by dneel-bah** [comment]
EDU has agreed to launch with an MVP without pulling entitlement / enrollment data from EVSS. The re-validation of AC2c/d in staging will be handled in #12734 once the test data is available in the staging environment. Closing this story because all other AC have been signed off on.
