### ISSUE TITLE
Disable search form and show spinner while geolocating the user

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#12564]
Currently, when a user visits the Facility Locator page, we try to geocode their location using MapBox.

There is no indication to the user that this is happening. The call to MapBox can take several seconds to complete, and during this time, the user may start typing into the location field or selecting facility/service types, only to have their entries wiped out when the geolocation request returns.

We should disable the form and show the user some indicator that we are auto-locating them.

Design details TBD.

**Comment by mmiddaugh** [comment]
This issue has been resolved
