### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#12562]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address

liani@adhocteam.us

Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

## Access Requirements
_Please list any requirements, if any._

No particular requirements; new PM -- ramping up and absorbing as much as I can.

## Date Required

ASAP

## Product Team / External Team / VA Office

VSP Content + IA

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by joanneesteban** [comment]
Access has been granted with read & write permissions. Closing this ticket.
