### ISSUE TITLE
CT: Search showing "name" when searching on enter

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12570]
Steps to reproduce:
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool
2. Type in a school name
3. Hit enter without selecting a school from the dropdown
4. Search results show “name” in the search text field with results that aren’t close to what was searched for

Expected results:
Should show the word that was typed out in the search box not "name"

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13904

**Comment by sonntag-adam** [comment]
This is fixed in staging. closing bug.
