### ISSUE TITLE
Staging and Dev URLs appearing in Google search results

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#1258]
### Status

UNRESOLVED

### Severity Analysis

- `sev 3` 
    - Can go out in a regular deploy but still needs fixed ASAP
    - Can be put into the owning team's backlog and scheduled by PM

### User Impact 

- *Who is the user impacted by this problem?*

A user that uses broken / incorrect / prerelease functionality on staging.va.gov.

- *How does this problem affect the user?*

Search for `staging va gov` in Google, see results that include `staging.va.gov` URLs:

<img width="896" alt="Screen Shot 2019-08-23 at 10 30 12 AM" src="https://user-images.githubusercontent.com/7645362/63600461-9effba00-c591-11e9-8721-5c936ba7e3d0.png">

### Description

See above.

### Steps to Reproduce

See above.

#### Expected Results

The user does not see `staging.va.gov` URLs in Google search.

#### Actual Results

See above.

### Proposed Solution

Maybe the VSA global UX / website team pushes an update to the [robots.txt](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/robots.txt) file?

**Comment by ElijahLynn** [comment]
Thanks for opening this. This is on DEV too > https://www.google.com/search?q=site%3Adev.va.gov

![image](https://user-images.githubusercontent.com/1504756/63608160-21d04700-c589-11e9-932b-0dc8bb01e0a4.png)

**Comment by alexpappasoddball** [comment]
@ricetj & @ncksllvn This one came through the triage incident and assigning to nick after conversation with Kara.  TJ, do you have any insight into this one you can add?

**Comment by ricetj** [comment]
> @ricetj & @ncksllvn This one came through the triage incident and assigning to nick after conversation with Kara. TJ, do you have any insight into this one you can add?

@alexpappasoddball I do not.

**Comment by ncksllvn** [comment]
I believe this comes down to just updating our `robots.txt` to block everything on dev/staging, only allowing crawlers on production. So, sounds like a good candidate for a build plugin.

**Comment by ncksllvn** [comment]
Moved to backlog, so it'll be groomed for next sprint.

**Comment by kelsonic** [comment]
As @ncksllvn mentioned, one solution is to update the robots.txt conditionally depending on the environment. On environment's that are not production, the `robots.txt` file should look like:
```
User-agent: * 
Disallow: /
```

Another solution is to use the meta tag `<meta name="robots" content="noindex">`, but it's important to note that [this will **only** block Google from indexing the site](https://support.google.com/webmasters/answer/93710?hl=en).

For now my plan is to go with @ncksllvn's solution for our users discovering va.gov via Bing, etc.

**Comment by kelsonic** [comment]
I'm actually wondering why we should allow random users from the internet use environments other than production anyways 🤔Despite not wanting to create more process, perhaps the best solution is to limit non-production environments access to only specific IP addresses (or alternatively/additionally a login). There's some pros and cons to doing this:

**Pros:**
1. We don't have to worry about a `robots.txt` file that disallows all web crawlers accidentally getting into production. 😱 
2. We would know exactly which IP addresses are allowed on non-production environments.
3. Crawlers would not be able to crawl non-production environments **AND** if we did come upon a use-case where they should be crawled we can create a static IP address for them to use.

**Cons:**
1. How do we still allow open-source developers to contribute when they can't access non-production environments?
2. As many of our engineers are remote, what if they switch IP addresses a lot?

I'm sure I missed some but would love your thoughts @ncksllvn @Karak888

**Comment by ElijahLynn** [comment]
> Actually, now I'm wondering why we should allow random users from the internet to use non-production environments in the first place Despite not wanting to create more process, **perhaps the best solution is to limit non-production environments access to only specific IP addresses (or alternatively/additionally a login)**. There's some pros and cons to doing this:
> 
> **Pros:**
> 
> 1. We don't have to worry about a `robots.txt` file that disallows all web crawlers accidentally getting into production. scream
> 2. We would know exactly which IP addresses are allowed on non-production environments.
> 3. Crawlers would not be able to crawl non-production environments **AND**, if we did come upon a use-case where they should be crawled, we can always create a static IP address for them to use.
> 
> **Cons:**
> 
> 1. How do we still allow and encourage open-source developers to contribute when they can't access non-production environments?
> 2. As many of our engineers are remote, what if they switch IP addresses a lot?
> 
> I'm sure I missed some pros/cons but would love your thoughts on this idea! @ncksllvn @Karak888

In the spirit of open source and also developer onboarding and testing, I think these should stay public. As an open source software engineer, I was really happy to see these non-prod environments be public, it gave me a boost working on this project, it showed me that this really is opensource in not only practice, but spirit as well.

**Comment by ElijahLynn** [comment]
> As @ncksllvn mentioned, one solution is to update the robots.txt conditionally depending on the environment. On environment's that are not production, the `robots.txt` file would look like:
> 
> ```
> User-agent: * 
> Disallow: /
> ```
> 
> Another solution is to use the meta tag `<meta name="robots" content="noindex">`, but it's important to note that [this will **only** block Google from indexing the site](https://support.google.com/webmasters/answer/93710?hl=en). On top of that, we would have to add it to the `<head>` tag of each HTML file we serve.
> 
> For now, my plan is to go with @ncksllvn's solution for our users discovering va.gov via Bing, etc.

Yeah, just this in non-prod environments and it is done.
> User-agent: * 
> Disallow: /

**Comment by kelsonic** [comment]
After discussing with @ncksllvn, it seemed much less complicated to go the meta tag route over modifying the `robots.txt` during the build process. After doing some research, we found that the robots meta tag is definitely respected by Google and is *very likely* to be [respected by Bing](https://www.bing.com/webmaster/help/which-robots-metatags-does-bing-support-5198d240) and [by Yahoo](https://en.wikipedia.org/wiki/Noindex).

**Comment by ElijahLynn** [comment]
> After discussing with @ncksllvn, it seemed much less complicated to go the meta tag route over modifying the `robots.txt` during the build process. After doing some research, we found that the robots meta tag is definitely respected by Google and is _very likely_ to be [respected by Bing](https://www.bing.com/webmaster/help/which-robots-metatags-does-bing-support-5198d240) and [by Yahoo](https://en.wikipedia.org/wiki/Noindex).

That will cause confusion when others engineers look at `/robots.txt. If it works though then that is a good start!

**Comment by ncksllvn** [comment]
@ElijahLynn would you suggest modifying the robots.txt based on environment as opposed to the meta tag?

**Comment by ElijahLynn** [comment]
> @ElijahLynn would you suggest modifying the robots.txt based on environment as opposed to the meta tag?

Yes, this is what I suggest long term. It is easier to see what is going on that way.

**Comment by ncksllvn** [comment]
Okay, @kelsonic, I'll defer to @ElijahLynn's judgement here and go with a build step for generating the robots.txt. 

Here's an [example](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/create-drupal-debug.js#L37) for creating a [Drupal debug page](https://staging.va.gov/drupal/debug/). I think we can follow a similar model for this.

**Comment by Karak888** [comment]
@kelsonic can you ensure that this gets validated by someone so we can close this out from sprint?  Thanks!

**Comment by ncksllvn** [comment]
![image](https://user-images.githubusercontent.com/1915775/66346868-178fbf80-e921-11e9-8b7e-398a073851ad.png)

![image](https://user-images.githubusercontent.com/1915775/66346877-1fe7fa80-e921-11e9-883e-4bac3680ebc7.png)

Validated!

**Comment by ElijahLynn** [comment]
Thanks everyone!
