### ISSUE TITLE
[Bug] 526: Schema Issues in Production After August 3

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12582]
## Issue Description
Looks like we are having some schema validation issues.

![image](https://user-images.githubusercontent.com/53824125/90535097-c1da9500-e137-11ea-9306-d1d1ed552ebf.png)

## Acceptance Criteria
- [ ] Root cause found and fixed
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
🤦 never mind. This is a ligthouse url.  ours is `v0/disability_compensation_forms` # submit_all_claim. It makes sense that lighthouse might recieve unvalidated schemas.
