### ISSUE TITLE
Support SLA Reminder Bot

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#12580]
Per a recent 1:1 I had w/ @nsmith1982, introduce a Slack reminder/bot to reiterate the support SLA/terms.

Reasoning: During my ( @f1337 ) recent utility dev rotation, I received several requests (including public @s and private messages) which made it clear that our clients do not understand the 24-hour SLA. I suggested perhaps a daily reminder might help, and Nancy suggested more frequency and/or a smart bot to reply on keywords.

More details to come.

Possible approaches (not exhaustive):
- daily reminder
- 2-Nx-times per day reminder
- bot that reminds on keyword usage (pull requests linked, pinging the support devs in channel, etc)

**Comment by alexpappasoddball** [comment]
@f1337 Is this is the right column?  Anything to add to this?

**Comment by f1337** [comment]
`/remind`er created in slack, weekdays at 11a ET for now:

> Reminder: VSP’s goal is to answer your questions as soon as possible, but if you aren’t getting traction with your request, we have the following escalation path:
• If you don’t get a response within a few business hours (or 1 business day for pull requests), @-mention one of the support engineers in the channel to look at your question. They can then contact the correct person to answer your question if it isn’t them.
• If you don’t get a response within 1 business day, contact your DSVA Product Manager, who will make sure the right people address your question.
We understand the desire to DM someone you’ve worked with previously about a question, but VSP has weekly and biweekly support rotation to limit interruptions for everyone on the platform.

![Screen Shot 2020-09-09 at 11.31.46 AM.png](https://images.zenhubusercontent.com/5ee13191b9a71c2fcbb3012a/5b81c81a-68dd-425d-bf87-c34c2941ef56)

**Comment by f1337** [comment]
I will move the "keyword monitoring" into my list of nice-to-haves for the other support bot ticket. Closing this as done (as of yesterday).
