### ISSUE TITLE
[Tech Debt] 526: Still Seeing Front-End Validation Issues

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12583]
## Issue Description
1. Duplicate disabilities
2. Age before 13 when joining service

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by edmangimelli** [comment]
this also seems like it might be multiple tickets (and overlaps with https://github.com/department-of-veterans-affairs/va.gov-team/issues/12584 )

**Comment by annaswims** [comment]
Closing in
