### ISSUE TITLE
[COGNITION]: GIBCT® - Consider adding full state names to States filter menu for better context

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1259]
## Description

Our states menu has just two-letter abbreviations. Screen readers do not read these out as proper abbreviations because they are just text strings. It would be a good enhancement to add the full state name, such as "CA - California" to that menu. Screenshot attached below.

/cc @peggygannon for content review and guidance.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screen reader user, I would like to hear the full state name read out when I have the States filter expanded.

## WCAG or Vendor Guidance (optional)

* [Abbreviations: Understanding SC 3.1.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-located.html)
* [G97: Providing the first use of an abbreviation immediately before or after the expanded form](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G97)

## Screenshots or Trace Logs

![Screen Shot 2019-08-23 at 9.48.26 AM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/e9c40dcc-fc8f-4360-ab50-677f8061c165)

## PR
https://github.com/department-of-veterans-affairs/vets-website/pull/11417

**Comment by 1Copenut** [comment]
@danziober I've got two or three more issue tickets to write for GIBCT®. Would you mind adding the right team label to them so we can track in Github/Zenhub accurately? Thank you.

**Comment by ksantiagomorgan6** [comment]
PR:

https://github.com/department-of-veterans-affairs/vets-website/pull/11417

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-01-08 at 10.46.32 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/20d733a4-45a7-4a62-8bfc-dcd1abad8cf5)

**Comment by 1Copenut** [comment]
@ksantiagomorgan6 This looks good to me. Much clearer to have the full name. Pinging @peggygannon and @CrystabelReiter for awareness.

**Comment by delli-gatti-michael** [comment]
These changes are now live in Staging

**Comment by ccruzgra** [comment]
@delli-gatti-michael Do you know where the state list is coming from? Curious because some states are not in alphabetical order, like the first two, for example. You would expect Alabama to come before Alaska. Are they being converted from their abbreviation to the full name? Thanks.

**Comment by 1Copenut** [comment]
Great catch @ccruzgra ! Ideally yes, these are in alphabetical order. Keyboard and screen reader users can type into the select and bring up their wanted state, but there's an expectation the list will be ordered by some logic that we don't want to lose.

**Comment by 1Copenut** [comment]
@desireeturner Verified this on staging. Moving this issue to close.
