### ISSUE TITLE
Analytics Implementation for Documentation Site

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#12598]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics

- Who is this request for?

    - [Alex Pappas & the BE/FE Tools team]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - BE/FE Tools Team.  We are working through validating updating the FE Tools documentation site (using gatsby) to include BE and Ops related docs.  We want to implement GA now so that we can compare usage on the current site with a new version that is being worked on.
    
- Provide the Domain where Google Analytics needs to be implemented

    https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/
    
    _Identify if PII is passed in URL or title tag_

None
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thank you @alexpappasoddball , acknowledging receipt here! Would like to setup some brief time with you to learn more about this request.

**Comment by joanneesteban** [comment]
@jonwehausen @bmcgrady-ep instead of a separate property, would we be able to pull this under the current github property and add a separate view so all of the VSP documentation lives in one place?

**Comment by jonwehausen** [comment]
Hi @joanneesteban , 

Yes for sure! Now seeing in the description this new page looks to be an additional page to our Github IO where we have the existing GA property supporting `https://department-of-veterans-affairs.github.io/va.gov-team/` -- certainly agree makes sense to create another view off of the existing property with `/veteran-facing-services-tools/getting-started/` as it's own GA view.

**Comment by jonwehausen** [comment]
### Dev Notes - WIP 


Meeting on calendar to discuss 1:30 EST. 

First look at the tracking on the page looks like we'll want to first add our GTM snippet. 

### Developer Notes

```javascript

**Paste this code as high in the <head> of the page as possible:**
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T2ZTDXZ');</script>
<!-- End Google Tag Manager -->
```


**Additionally, paste this code immediately after the opening <body> tag:**
```javascript
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T2ZTDXZ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by jonwehausen** [comment]
### Follow-up Notes
- Met with Megan, Alex, Bill, Brian, Ben 8/20
- Reviewed team goals for this initiative, will start with generic GA tracking and iterate from there on event tracking if needed


### Next Steps
- @bmcgrady-ep to do the following: 
   - [ ] Validate pageview tracking when GTM snippet is put in
   - [ ] Create new view for all pages following the directory `/veteran-facing-services-tools` 
   - [ ] Rename current documentation landing page view from "All Website Data" 

cc: @bsmartin-ep and @joanneesteban for visibility

**Comment by alexpappasoddball** [comment]
@bsmartin-ep the tracking pixel is live on the site now.  Let me know how else we can help to setup the property.  Take a peek at my previous comment as well, might be some small extra step we need to do for the plugin we used.

**Comment by bsmartin-ep** [comment]
@alexpappasoddball -

We're able to observe your `gatsby-route-change` event, so we can use that to fire pageviews.

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/bb9c0c35-8004-47b9-a68f-ff82badd8a6e)

We'll need to maintain _Window Loaded_ triggers for any pages not generating this event.

Can you think of any pages in our docs **besides** the ToC page that wouldn't have the `gatsby-route-change` event?

-------

@bmcgrady-ep - Once we get this trigger stuff worked out, here's a GTM workspace for you to QA:

https://tagmanager.google.com/#/container/accounts/144676348/containers/30787921/workspaces/4

**Comment by bsmartin-ep** [comment]
## QA

Description|GTM tagging
---|---
Direct visit to _VSP Documentation Landing Page_|![image](https://user-images.githubusercontent.com/62304138/91722394-2ea65400-eb68-11ea-8992-526b77b97203.png)
Direct visit to _Client application documentation_ page|![image](https://user-images.githubusercontent.com/62304138/91722154-de2ef680-eb67-11ea-92b8-b581a154fd9a.png) ![image](https://user-images.githubusercontent.com/62304138/91722182-e850f500-eb67-11ea-861c-50797886ca3c.png)
Click _Overview_ link|![image](https://user-images.githubusercontent.com/62304138/91722254-fd2d8880-eb67-11ea-9261-cbaa3c8fd12f.png)
Direct visit to _Overview_ page|![image](https://user-images.githubusercontent.com/62304138/91722475-4ed61300-eb68-11ea-83fc-8527c3d315ec.png)

LGTM @alexpappasoddball and @bmcgrady-ep.  Publishing our GTM workspace to start collecting data.

**Comment by bsmartin-ep** [comment]
@alexpappasoddball -

I also created a dedicated view for "Veteran Facing Service Tools":

https://analytics.google.com/analytics/web/#/report-home/a50123418w224573768p227831524

**Comment by alexpappasoddball** [comment]
@bsmartin-ep Looks good to me!  Anything else we need to do or is this task completed?!

**Comment by bsmartin-ep** [comment]
I think we are done for now @alexpappasoddball.  I'll keep an eye on the real-time data, but feel free to close this issue if it looks good to you.

**Comment by alexpappasoddball** [comment]
Just did a spot check and it looks good to me.  I'll close this out and if there are issues that pop up we can create a new issue to address that.  Thanks everyone!
