### ISSUE TITLE
10203 STEM form - longer email addresses are cut off on the review page

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#12617]
On the review page of the 10203 form, the user is given the opportunity to review the responses to all questions in the form. On two separate pages, the user is asked for an email address. If either of those email addresses is too long, it will be cut off on the review page.

### Expected behavior
Full email address is shown

### Actual behavior
Email addresses are cut off

### Screenshots
![Screen Shot 2020-08-19 at 10.35.47 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ce0963ab-a3a9-4dc9-bed2-30a142152f45)

---

![Screen Shot 2020-08-19 at 10.33.19 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c98c3cd1-2646-4858-a5a6-c957b038dc1e)

**Comment by dbarnes-VA** [comment]
Test Run: https://dsvavsp.testrail.io/index.php?/runs/view/2507

**Comment by AdamFreemer** [comment]
@nbarthelemy -- dug in here a bit for you. The core of the fix will most likely be here:

`vets-website/src/applications/edu-benefits/10203/sass/10203_stem.scss`

And this code seems to fix the problem (with a caveat):
```
dd > span {
  overflow-wrap: break-word;
}
```
I'm not the best with css, and this is adding  wrap to all the form fields, but I think that might be preferred behavior anyway. Adding specificity to the email field can probably be figured out, but perhaps I'd ask if having wrap on all the fields is ok, and preferred as I mentioned. 


![Screen Shot 2021-11-18 at 11.23.15 AM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/b8f9ec0f-b747-454a-923c-7bb56a284ccd)

**Comment by nbarthelemy** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/19494

**Comment by dbarnes-VA** [comment]
Validated in Review Environment
Awaiting push to Staging for final validation per QA.
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/612faf5311d1aa63424e2351/bcb3a6c4-d209-4a25-9640-f061a0d24b76)

**Comment by noahgelman** [comment]
@dbarnes-VA Approved for accessibility

**Comment by mrblanco1** [comment]
@af-manish to demo this change to Joe on Monday 11/29/2021.

**Comment by mrblanco1** [comment]
Ready for QA once it makes it to Staging.

**Comment by dbarnes-VA** [comment]
Test Run: https://dsvavsp.testrail.io/index.php?/runs/view/2507
Test Script: [10203 STEM form - longer email addresses are cut off on the review page.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7628337/10203.STEM.form.-.longer.email.addresses.are.cut.off.on.the.review.page.xlsx)

**Comment by dbarnes-VA** [comment]
Tested and validated in https://staging.va.gov/

Note: Address lines 1 and 2 original form fields have character limits of "50" therefore only the first 50 characters have been tested. However, these 50 characters word wrap as expected. In addition, the email address will also word wrap instead of being cut off.

<img width="525" alt="12617" src="https://user-images.githubusercontent.com/88742213/144116042-3ae11e14-cad7-4ac4-9443-fd92c97da175.png">
