### ISSUE TITLE
Product Guide for Find VA Forms - Detail Pages

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#12616]
# Request the Contact Center Review 

## Description
Provide Veterans and other users information on the forms they need to apply for VA benefits and services. 

### Launch Date
Mid-Sept

### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/contact-center/Find%20VA%20Forms_Search%2BDetailPages_Product%20Guide.pdf

## Tasks
- [x] Update existing guide
- [ ] Share with Contact Center liaison team

## Acceptance Criteria
- Updated product guide for Find VA Form Detail Pages

**Comment by jenniferlee-dsva** [comment]
LMK what screenshots you need @MickinSahni

**Comment by MickinSahni** [comment]
Ok, @jenniferlee-dsva. I have a GSlides version of the product guide ready. 

And I think I can pull screenshots from the prod-preview links here: [Find VA Forms - Detail Pages: Product Use Cases/Batch 1 - top 40 forms for QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/form-detail-product-use-cases.md#batch-1---top-40-forms-for-qa)

It's not the QA environment, but they should be consistent. Is that right?

**Comment by MickinSahni** [comment]
👋 @chant

**Comment by MickinSahni** [comment]
👋 @clantosswett @joanneesteban @Kimberley2019 this is available in github for review. happy to close out if we're ready.

**Comment by Kimberley2019** [comment]
@MickinSahni Good Morning.  My apologies, I'm a little out of the loop, but let me sync with @clantosswett to see where we are with this.  We will get back to you today with next steps and/or an update.

**Comment by MickinSahni** [comment]
Thanks so much! Hopefully this doesn't need to much bandwidth on both of our parts as this effort involved updating an existing VA.gov experience.

**Comment by Kimberley2019** [comment]
Good Morning @MickinSahni I have been able to review the product guide and do not have any questions.  The only suggestion/request that I have is a table of contents.
Is there going to be a product video and transcript?
I have passed this product guide along to the Contact Center for their review with a requested response date of 10/1/2020.  Can you advise if this product has launched already?

**Comment by MickinSahni** [comment]
Hi @Kimberley2019, thanks for the review. There's not going to be an associated video/transcript. This hasn't launched yet. Anticipating launch within the next two weeks. cc @brianalloyd

**Comment by MickinSahni** [comment]
HI @Kimberley2019 updated the product guide with a contents page. Link is updated!: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12616#issue-681890877

Closing this out!

**Comment by Kimberley2019** [comment]
@MickinSahni Thank you.  I was going to close this out to day since we have not received any feedback from the Contact Center.
