### ISSUE TITLE
[FE] Profile 2.0 bug: The profile does not properly handle a contact field update without any changes

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12632]
![no-change-edit.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/5c95bb2f-be0c-4ac5-99ef-0e61232916a2)

If you attempt to update a contact field, such as a phone number, without making any actual changes to the field, a transaction is never actually created and the field exits edit mode after 5s but does not give the user any feedback as to what is happening.

I don't know the best approach to fixing this. A few options:
1. Simply disable the auto-exit edit mode feature in this situation
2. Do 1 _and_ also show an alert of some kind telling the user they need to actually make a change.
3. Just quickly exit edit mode in this case
4. Disable the UPDATE button unless there is an actual change made to prevent this from happening. We should already have the logic to do this; it's the same logic as what we use to show the warning modal when a user has unsaved changes.

Note: The call to `PUT v0/profile/telephones` returns this:
```
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_telephone_transactions",
    "attributes": {
      "transactionId": "321768b4-819e-40a9-b698-b80c0baee6e5",
      "transactionStatus": "COMPLETED_NO_CHANGES_DETECTED",
      "type": "AsyncTransaction::Vet360::TelephoneTransaction",
      "metadata": []
    }
  }
}
```

@tressaellen do you have any thoughts on the UX approach you'd like to take for this? I'm happy to chat about options and the work involved with any of them.

**Comment by erikphansen** [comment]
@mshea I don't remember this being added to the sprint during sprint planning. Tressa and I are both assigned to it. Was it added to the sprint with the idea that she would be figuring out the UX for this particular case? The desired UX needs to be decided on before we can implement the fix. I'm removing myself from this ticket for now until the desired UX has been determined.

**Comment by mshea0606** [comment]
@erikphansen that makes sense. I'll move this to next sprint and leave it assigned to Tressa until the UX is figured out, then create the needed FE ticket. Thanks!

**Comment by erikphansen** [comment]
@tressaellen I'm leaning toward option 4; it would likely be the most straightforward to code. And we have precedence for disabling a SUBMIT button if the user didn't actually make any changes to their data. We do that on the Find Benefits page which you can see by signing in and going to https://staging.va.gov/my-va/find-benefits

![find-benefits.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/3b90c79a-69d5-40e8-bb59-860484a6a2ec)

**Comment by tressaellen** [comment]
@erikphansen  - I like option 4 as well - let's move forward with that.

**Comment by erikphansen** [comment]
@tressaellen feel free to validate this on staging. The Update button should be disabled if you haven't actually changed your data.

**Comment by tressaellen** [comment]
@erikphansen - this looks great!
