### ISSUE TITLE
[Discovery] Comparative UX analysis: Search limited to 250 miles 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12635]
## Issue Description
This issue to explore options to address the scenario in which a search is limited by the data source. 

**Current behavior** 
When a Veteran initiates a search, the map continues to zoom out until results are found. If no results are found, we display a general error message. 

**Problems** 
- PPMS will be limiting the response to include results within 250 miles. This could be misleading/confusing to Veterans if they think the full list of results has been returned when the list actually has been limited. 
- The user is not given information to understand why the search failed or how to be more successful. 

## Task
Considering the forced data limitation, discover how other modern websites are handling this situation and what the ideal user experience should be:
- How do we communicate the 250 mile limitation to users?
- How does the Veteran search after specifying new/refined parameters? (Search this area? New search?)
- How can we enable Veterans to search a larger radius than the default?  
- How should the UI change based on interactions with the map? 
  - Should the original parameters be updated? 
  - What happens to the subhead? 
  - How does this change the distance/directions displayed in the search results?
  - What error messages will support users in these scenarios? 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
Analysis in Google Sheets
https://docs.google.com/spreadsheets/d/1sIqiSYLL6JXqaQJ3iGUnBYYjOxFLTmn0TRWeN0HcDbM/edit?usp=sharing

Recommendations with supporting visual examples
https://docs.google.com/presentation/d/1FNvhu7peex3EfufXeNWZYIA4F2cZs2RuArdaBOwT9zg/edit?usp=sharing

Working with Jennifer Strickland for next steps.
