### ISSUE TITLE
New document about how VSP will handle edge cases in our design system governance process

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#12641]
### What is your documentation request, question, comment, or issue?
I already drafted a document and got feedback on the contents within it - so conceptually it's pretty close to ready to go, but I know the tone, language, flow, format, etc is not where it should be in order to fit nicely into our ecosystem of docs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/design-system/governance-process/edge-cases.md

I'd like advice, feedback, or direct help both on the IA of this (where it should live in the gh repo), as well as the content itself so that I can publish it and our team can start using it in their guidance of VFS teams.

**Comment by gmaciolek** [comment]
@rroueche 👋  I made edits and left a comment in a PR on your doc for your consideration.
