### ISSUE TITLE
 Monitoring Tool -  Migrate from Prometheus to DataDog

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#12647]
### High Level User Story/ies
As a developer, I want to have a clear monitoring solution that allows me to gain insight into my application and as an Operations member is better to maintenance so that Va.gov can easily access their application and infra data to make better data-driven decisions.

### Problem Statement 
RIght now we use Prometheus for our monitoring and over the years we have not invested the time to make it as effective as we need on Va.gov. This has resulted in it being outdated, not clean alerting, very difficult to use due to its query language, Prothemus's limited data retention, and does not provide an APM solution. This creates pain point for VSP and applications teams trying to see their metrics.

How might we have a better monitoring experience for Va.gov.

### Hypothesis or Bet
Have a modern and more user-friendly monitoring solution will not only allow gathering of data to be easier but will ensure more developers to use the monitoring tool. 

### OKR
*Which Objective / Key Result does this epic push forward?*

### Success metrics 
- Percentage of users using DataDog (Baseline will be users accessing Grafana to see Prometheus data)
- TBD

### We will know we're done when...
When we completed the migration from Protheus to DataDog and our users know how to use the new monitoring tool.

### Additional Details/Notes (optional)
*Any other relevent information about this project not already listed above*

### Artifacts
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))

### Communication
- Team that owns this super epic: (e.g. Product Support)
- Teams contributing to this super epic: (e.g. FE Tools, BE tools, Ops)

**Comment by jhouse-solvd** [comment]
Migrated to: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13748
