### ISSUE TITLE
STEM: Remove 10203 Prod Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12658]
As a developer, I need to remove the prod flag from the 10203 so that it is available in production for the limited rollout.

## Assumptions:
1. This flag is the default flag "vagovprod".
2. This story does not include the changing of the `showSTEMScholarship` feature flag status.
3. This story is to enable direct access, and does not include changing the wizard or any other entry points to the form.

## Acceptance Criteria
1. Form 10203 is available in production

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13940

**Comment by delli-gatti-michael** [comment]
10203 form is accessible in production using the following link:
https://www.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction

Closing this issue
