### ISSUE TITLE
[Bug] Benefits Delivery at Discharge - POW period Edit button misaligned

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12656]
## What happened?
On Staging Benefits Delivery at Discharge form, Disabilities, Prisoner of War (POW) page, after entering 1st POW period and clicking Add Another Period button, 1st period's Edit button is not aligned properly with the display box.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: ```vets.gov.user+250@gmail.com``` (Clifford)

## Steps to Reproduce
1. Go to https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
1. Click **Sign in to start your application** -- sign-in as ```vets.gov.user+250@gmail.com``` (Clifford).
1. Click **Start...**, then keep clicking **Continue**, inputting required field-inputs, until you reach **Disabilities, Prisoner of War (POW)** form-page.
1. Click **Yes**, input a valid POW period, then click **Add Another Period**.
1. Observe that the 1st period's **Edit** button is not aligned properly within the display-box, with bottom of button showing beyond the bottom of display-box.

**Mac Chrome screenshot**
![BDD-bug-pow-period-edit-btn-alignment-200119](https://user-images.githubusercontent.com/587583/90717788-3eb75d00-e265-11ea-822a-ba7c6fa633c4.png)

## Desired styling
**Edit** button should be aligned properly within display-box, with padding between bottom of button and bottom of display-box.

## Acceptance Criteria
- [ ] \[See **Desired styling]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
Fixed in https://github.com/department-of-veterans-affairs/vets-website/pull/13978
