### ISSUE TITLE
[Bug] Benefits Delivery at Discharge - last Service History period cannot be Updated

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12654]
## What happened?
On Staging Benefits Delivery at Discharge form, Veteran Details, Service History page, the last existing service period's Edit form is missing Update button.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: ```vets.gov.user+250@gmail.com``` (Clifford)

## Steps to Reproduce
1. Go to https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
1. Click **Sign in to start your application** -- sign-in as ```vets.gov.user+250@gmail.com``` (Clifford).
1. Click **Start...**, then keep clicking **Continue** until you reach **Veteran Details, Military service history** form-page.
1. Scroll down to the last existing service-period **Marine Corps**, then click **Edit**.
1. Observe that there's no **Update** button, and only **Remove** button is displayed in the edit-form -- changes cannot be saved.

**Mac Chrome screenshot**
![BDD-bug-svc-hist-no-update-btn-200819](https://user-images.githubusercontent.com/587583/90708960-fa6d9200-e24f-11ea-9473-c444e45ce757.png)

## Desired behavior
For Editing an existing service-period, both **Update** and **Remove** buttons should be displayed in the edit-form, and changes should be saved upon clicking **Update**.

## Acceptance Criteria
- [ ] \[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
This already has a PR awaiting review - https://github.com/department-of-veterans-affairs/vets-website/pull/13585
