### ISSUE TITLE
VSP content feedback - Staging - BDD 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12653]
## User story
This ticket captures VSP content feedback on BDD part of 526EZ  disability compensation form

Staging link: 
https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction

## Acceptance criteria
 - [x] VSP/Peggy provides content feedback and recommendations for the form/tool.
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x]  Product team leaves any comments about feedback they decide not to take
- [ ] Peggy checks form after content feedback has been incorporated

**Comment by peggygannon** [comment]
VSP content for BDD

Feedback key:
Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement

----------

**Comment by Mottie** [comment]
Hi @peggygannon, this is a current work-in-progress. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/11188

**Comment by Mottie** [comment]
Hi @peggygannon, these changes have just been merged into the code base and should be available in staging soon.

**Comment by peggygannon** [comment]
HI, @Mottie OK, thank you! I will take a look

**Comment by peggygannon** [comment]
Hi, @Mottie I was FINALLY able to access the BDD screens within the form and have added some additional content feedback above. please let me know if you have any questions about my recommendations. Thank you!

**Comment by peggygannon** [comment]
Hi, @Mottie I don't see the content updates on staging yet, so I wanted to check in if you had any questions about my changes?

**Comment by Mottie** [comment]
@peggygannon The content is on staging. Here are the steps to follow:

1. Start from https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
2. In the wizard, choose "Yes" for active duty
3. Enter a date at least 90 days in the future, e.g. `Feb 1 2021` (works now)
4. Use the "File a Benefits Delivery at Discharge claim" button
5. The BDD intro page content will now show. Note that the document title (browser tab), breadcrumbs and page title have all updated.

**Comment by peggygannon** [comment]
Thanks, @mottie. I've followed the steps above and still don't see the following content recommendations in staging (screenshots below of what I see) 

- I recommend we update the H1 TO: **File a Benefits Delivery at Discharge claim**

- I recommend tweaking this message to be more clear and succinct:
TO:
Please be aware that you’ll need to be available for 45 days after you file a BDD claim to complete a VA exam.

- Please update bullets under “Apply” TO follow VA.gov style:
-Provide your service member information
-Provide your military history
-Describe the conditions you’re submitting a claim for

VA Review should be sentence cased> VA review


![2020-10-20.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/fcbe9054-1b5a-4bd6-84f2-f67b3c07630e)

![2020-10-20 (1).png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/7569b158-0584-4ad0-8512-8a60410dee9a)
