### ISSUE TITLE
[Bug] Benefits Delivery at Discharge - Review page extraneous Mil. Svc. History edit section

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12657]
## What happened?
On Staging Benefits Delivery at Discharge form, Review page, Review Veteran Details section displayed an extraneous Military service history heading and Edit button.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: ```vets.gov.user+250@gmail.com``` (Clifford)

## Steps to Reproduce
1. Go to https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
1. Click **Sign in to start your application** -- sign-in as ```vets.gov.user+250@gmail.com``` (Clifford).
1. Click **Start...**, then keep clicking **Continue**, entering required field-inputs, until you reach **Review Application** form-page.
1. Click to expand **Review Veteran Details** section.
1. Immediately below **Review Veteran Details** heading, observe that there's a smaller, extraneous **Military service history** heading and **Edit** button above the actual, larger **Military service history** heading.
1. Click the extraneous heading's **Edit** button.
1. Observe that an extraneous **Update** button is displayed, with no fields above to edit.

**Mac Chrome screenshots**
Extraneous heading & edit button
![jBDD-bug-rvw-pg-svc-history-extra-hdg-edit-200819](https://user-images.githubusercontent.com/587583/90722708-3284cd00-e270-11ea-8083-16e7a8a7da68.png)

After clicking edit button, extraneous update button with no edit fields
![jBDD-bug-rvw-pg-svc-history-extra-hdg-update-200819](https://user-images.githubusercontent.com/587583/90722782-547e4f80-e270-11ea-9721-7e931a5d4aa8.png)

## Desired behavior
There should be no extraneous Military service history heading displayed between Review Veteran Details and actual Military service history heading.

## Acceptance Criteria
- [ ] \[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ndsprinkle** [comment]
The reason this empty edit field is appearing is because of separation location. In this case, nothing shows because separation location is set to hide if it's not a BDD claim. I am able to force the field to hide all the time, but haven't been able to get the parent Edit button and matching title to hide without completely removing separation location. I still have a few more things to try and also may consult with Kevin to determine where separation location should live on the review page or if it is okay to hide it.

**Comment by ndsprinkle** [comment]
Robin and I believe using `hideHeaderRow` will fix this issue. However, this also seems to hide the edit button which technically does need to be there if want the user to be able to edit separation location on the review page. I will consult with Kevin on this to see what he thinks. I have also consulted with Kevin about moving separation location to its own page which would theoretically fix all issues, but we would only do that as a last resort.

**Comment by ndsprinkle** [comment]
Agreed on solution with design to move separation location to its own page. A PR has been created and linked to this ticket.
