### ISSUE TITLE
sitewide 508-defect-2 [AXECORE]: Page MUST contain a level-one heading

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#12666]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

```diff
! Team impacted: VSA BAM1; Project: BDD
```

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Even when a page renders an error, there **should** be an h1.

Screen reader users can use keyboard shortcuts to navigate directly to the first h1, which, in principle, should allow them to jump directly to the main content of the web page. If there is no h1, or if the h1 appears somewhere other than at the start of the main content, screen reader users must listen to more of the web page to understand its structure, wasting valuable time.

Keep in mind that blind users can't just look at a web page and immediately understand its layout the way that a visual user can. Visual users can take in much information about the page layout without having to read all of the content. Blind users don't have that luxury. Screen readers read linearly, which means listening to the entire web page unless there is some other convenient way to get a "glimpse" of the page's layout and structure. It turns out that headings are a way to do that. Screen reader users can use keyboard shortcuts to navigate through the heading structure of a document.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to navigate the structure of the document to know what the content is.

## Environment

* Operating System: all
* Browser: all
* Screenreading device: any
* Server destination: staging, production

## Steps to Recreate

1. Logged in as user 261, enter https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction in browser
2. Start application
3. After a long processing time, verify the error shown in the enclosed screenshot appears
4. Run an axe scan, and verify the "Page must contain a level-one heading" issue appears

## Possible Fixes (optional)

Ensure that an h1 renders first on a page, while the remainder of the content is generated. For example, the h1 on these pages could be:

```
 <h1>Application for  Disability Compensation</h1>
```

## WCAG or Vendor Guidance (optional)

* [Deque University - Page must contain a level-one heading](https://dequeuniversity.com/rules/axe/3.5/page-has-heading-one?application=AxeChrome)

## Screenshots or Trace Logs

![Screen Shot 2020-08-20 at 12 08 14 PM](https://user-images.githubusercontent.com/57469/90798131-8975bb00-e2df-11ea-8349-d956a3467fdd.png)

![Screen Shot 2020-08-20 at 12 26 45 PM](https://user-images.githubusercontent.com/57469/90798836-73b4c580-e2e0-11ea-9e19-8edf3dee20ed.png)

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by Mottie** [comment]
Please note: that the merged in changes do not include showing an `H1` while the loading indicator of the save-in-progress (`RoutedSavableApp`) component is visible. That will require code changes in the platform folder.

**Comment by jenstrickland** [comment]
@Mottie If we need platform changes, we should tag in the appropriate folks and assign this ticket. Can you provide a few more details so I understand? My hunch is that this is a `frontend` label, now…

**Comment by Mottie** [comment]
Here are some example screenshots

<details><summary>Retrieving your profile information</summary>


![Screen Shot 2020-09-10 at 5 39 42 PM](https://user-images.githubusercontent.com/136959/92818394-47471300-f38d-11ea-9b65-292c4d5e9ce6.png)</details>

<details><summary>Saving your application</summary>


![Screen Shot 2020-09-10 at 5 41 40 PM](https://user-images.githubusercontent.com/136959/92818387-4615e600-f38d-11ea-8d55-5600a7edee10.png)</details>

<details><summary>Retrieving your saved application</summary>


![Screen Shot 2020-09-10 at 5 41 57 PM](https://user-images.githubusercontent.com/136959/92818392-46ae7c80-f38d-11ea-815c-8a47c42bf202.png)</details>

**Comment by jenstrickland** [comment]
@Mottie is there a particular component that we need to let @meganhkelley know the `frontend` team should look into? 

My hunch is the H1 is populated by a particular component. The issue I see happening is that the H1 is rendered with all of the content of the page, but it **should** be populated before the rest of the page content is rendered. Does that describe it?

**Comment by Mottie** [comment]
> is there a particular component

I mentioned it already: `RoutedSavableApp`

**Comment by jenstrickland** [comment]
Thanks, @Mottie! @meganhkelley, I hope this is enough info for the frontend team to explore. Of course, let us know if any more details would be helpful.
