### ISSUE TITLE
IA feedback - Staging review - Caregiver application 

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#12667]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This issue describes IA feedback for the Caregiver application. 
IA solution is documented here for reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/caregiver-10-10cg.md

**Must**
- The breadcrumb labels are not accurate - please update to 
Home > Family member benefits > Apply for the Program of Comprehensive Assistance for Family Caregivers

**Consider**
- On the /introduction page of the form there is a link to "Learn more about the Program of Comprehensive Assistance for Family Caregivers (PCAFC)" that takes the user to the caregivers subdomain.  Consider having this link take them to our moderinzed page first, and allow that content page to link back to the subdomain.  This will ensure users that enter directly on the application stay within the same experience and have quick access via the primary CTA to go back to the application. The legacy/subdomain does not provide an easy or quick option to get back to the application.  It also does not link them to a page about the PCAFC, just to the subdomain main page. 

## Definition of Done
- [x] Must feedback is implemented on staging
- [x] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by LinnJS** [comment]
PR for Breadcrumbs `must` feedback https://github.com/department-of-veterans-affairs/vets-website/pull/13985

**Comment by ala-yna** [comment]
Hi @mnorthuis  - I think we can close this out - can you confirm? The must feedback has been addressed and I created a backlog ticket to look into changing the link (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13116). Thank you!

**Comment by mnorthuis** [comment]
Thanks!
