### ISSUE TITLE
[Bug] Form526: Submission Status Not Available and Affecting Submission Message

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#12668]
## What happened?
This happened locally, but metrics show it happened in prod 243 times in the past 14 days.  

When I submit a form 526 a form526 `submit_all_claim` returns a job_id.  The FE then immediately queries the BE for the submission_status.  However, the submission_status isn't immediately available. On the back end the job is enqueued, but the job status isn't available until the job starts running, which was about a half second later when I looked at it locally. 

<img width="1216" alt="Screen Shot 2020-08-20 at 10 22 57 AM" src="https://user-images.githubusercontent.com/19188/90791352-15371980-e2d7-11ea-98b3-0aafebdd3723.png">

I think the simplest fix would be to retry the `submission_status` endpoint a few seconds later if `submission_status` returns a 404.  Unless the queue system is really backed up (which happens on rare occasions) this will help veterans see their status.

<img width="1644" alt="Screen Shot 2020-08-20 at 10 36 42 AM" src="https://user-images.githubusercontent.com/19188/90786030-15341b00-e2d1-11ea-9bc5-c4aa89ed4fae.png">

**Comment by annaswims** [comment]
I'll verify here tomorrow http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?viewPanel=12&orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v0%2Fdisability_compensation_forms&var-frontend_app=All

**Comment by Mottie** [comment]
Make it Friday, or later... this was just merged, but won't be available in production until 3pm ET tomorrow.
