### ISSUE TITLE
Design feedback - Staging Review Benefits Delivery at Discharge

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#12678]
- **Must** Feedback must be applied
- **Should** Feedback is best practice
- **Consider** For suggestions/enhancements

**Must:**
- For all secondary buttons “Add another…” make sure the labels are in sentence case and not in camel case
- On the review and submit page, please unbold the heading text of the additional info components (image below)
![Screen Shot 2020-08-20 at 1.26.01 PM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/ed1da3f3-df9c-45de-8a4c-d441c8cefbab)
- On the review and submit page, these secondary button labels are off centered vertically, please center them (image below)
![Screen Shot 2020-08-20 at 10.38.54 AM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/9ae88f33-8c5a-4145-bf9e-b63e380eaff5)
![Screen Shot 2020-08-20 at 10.37.51 AM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/7f9d57a8-f225-442d-8c78-7ee9784ea773)

**Should** 
- For Chapter 2 of 5, in the question “What caused this service-connected disability?”, instead of a link that opens up a modal, try using an additional info component for “What does service-connected disability mean? Or “Learn more about service-connected disabilities”. We’ve done studies with assistive tech users that has proven that it’s difficult for users to learn more information through a link + modal
- Should we move the edit box into this gray box for consistency sake? (image below)
![Screen Shot 2020-08-20 at 10.37.51 AM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/4edbf05a-2a0e-4993-bddf-17324dae64eb)

**Consider**
- Consider adding more space in between the additional info component and the date input (image below)
![Screen Shot 2020-08-20 at 10.20.25 AM.png](https://images.zenhubusercontent.com/5d8b8d43bb171300016bf17a/cb3f841b-6488-4726-a1e4-e7c9e8e234c6)

- [ ] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by Mottie** [comment]
| Done | Status | Description |
|------|-----|-----|
|  | [14061](https://github.com/department-of-veterans-affairs/vets-website/pull/14061) | Change "Add another..." buttons to sentence case |
|  | [14062](https://github.com/department-of-veterans-affairs/vets-website/pull/14062) | Remove bold from AdditionalInfo link on the review page |
|  | [14062](https://github.com/department-of-veterans-affairs/vets-website/pull/14062) | Fix vertical text alignment in secondary buttons |
|  | Researching | Change service connected modal to AdditionalInfo |
|  | Researching | Move edit button into gray box |
|  | [14062](https://github.com/department-of-veterans-affairs/vets-website/pull/14062) | Add space above the AdditionalInfo box on the Individual Unemployability page |
