### ISSUE TITLE
508-Defect-2 [AXE-CORE]: Heading levels SHOULD only increase by one

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#12675]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

### Note

This is a common issue, and we have documented the Acceptance Criteria, Environment, Steps to Recreate, Possible Fixes, and WCAG Guidance in a [Github document on Heading levels SHOULD only increase by one](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/common-issues/headings-should-increase-by-one.md).

## Point of Contact

**VFS Point of Contact:** Jennifer

## Possible Fixes (optional)

```
Element location
#table_servicePeriods_0 > .va-growable-expanded.small-12.columns > h5

Element source
<h5 class="schemaform-array-row-title" tabindex="0">New Service Period</h5>
```

```diff
<div class="form-review-array">
  <div>
    <div class="form-review-panel-page-header-row">
      <h3 class="form-review-panel-page-header">Military service history</h3>
    </div>
    <div class="va-growable va-growable-review">
      <div></div>
      <div class="va-growable-background">
        <div></div>
        <div class="row small-collapse schemaform-array-row" id="table_servicePeriods_0" tabindex="-1">
          <div class="small-12 columns va-growable-expanded">
!            <h5 class="schemaform-array-row-title" tabindex="0">New Service Period</h5>
+            <h4 class="schemaform-array-row-title" tabindex="0">New Service Period</h4>
```

## Screenshots or Trace Logs

![Screen Shot 2020-08-20 at 1 52 32 PM](https://user-images.githubusercontent.com/57469/90807485-89c88300-e2ec-11ea-9220-2e9d7680aa56.png)

**Comment by Mottie** [comment]
This code has been merged and is ready to be reviewed on staging.
