### ISSUE TITLE
Join Telehealth appointments in VAOSR

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12684]
Given the rise and use of VVC/video appointments for various health appointments, we want to improve the ease of access and use of video appts from within VAOSR.

**Comment by laurenernest** [comment]
Documented for future reference here https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/appointments/va-online-scheduling/product/future-work-requests-ideas.md
