### ISSUE TITLE
[Bug] 526: Users are allowed to fill out  or submit form526 after it has expired

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#12690]
## What happened?
We let a veteran complete and submit a form526 even though their application has expired, but then va.gov sends it to EVSS who rejects it, due to the applicationExpirationDate.  I would consider this a bug that happened infrequently in the past, but will need additional consideration as we release BDD.

## Business-level questions:

- When should a form expire and why?
## EVSS Question:
- applicationExpirationDate is a field we send to EVSS, but what are they expecting?  

This is the only EVSS documentation I know of.
![Screen Shot 2020-09-18 at 5 20 19 PM](https://user-images.githubusercontent.com/19188/93646026-5fddab80-f9d3-11ea-8e77-3bed6bc628e6.png)

## What does the vets-api code currently say?
[code](https://github.com/department-of-veterans-affairs/vets-api/blob/169018e9bc884c7c1bdda30d485776f599726ce7/lib/evss/disability_compensation_form/data_translation_all_claim.rb#L607)

* if `rad_date` > `application_create_date` the application expires one year and a day after the RAD date
*  if `intent to file creation date is blank`, or` intent to file expiration_date is blank`, or  `intent to file creation_date > application_create_date`the application expires one year after the application was created
* otherwise the application expires on the intent to file expiration_date

### Definitions
`application_create_date is` the date the save in progress form is created on VA.gov, it's possible to restart the form and get a new `application_create_date`

`rad_date` is currently the last date of a service episode from EMIS.  BUT it _maybe_ should only consider active duty and should be based upon the veteran-submitted data, as EMIS will not have service episodes with future end dates.

# Error frequency

We see this error roughly once a day and we see the message `form526.ApplicationExpirationDate: The submitted application has already expired` from EVSS

**Comment by annaswims** [comment]
@annaswims will provide some examples.

**Comment by annaswims** [comment]
rad_date is Release from Active duty, which probably does not count time in the reserves, which is a related question/conversation.  I'm thinking it's the date on DD214

**Comment by annaswims** [comment]
somewhat related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/13721

**Comment by annaswims** [comment]
@luke-gcio will you hunt down the answers to the question "when should a form expire?"

**Comment by luke-gcio** [comment]
Paul will meet with us to discuss the business logic when we are ready.  His initial look at the above seems to indicate there _is_ something wrong with our logic.

**Comment by luke-gcio** [comment]
From Paul:

> Let me take a shot at addressing this from a work flow perspective: Application A1 is started on 9/22/2019. One year following the ITF, application A1 is expired. On 9/23/2020, the applicant logs and tried to complete the application. Since A1 has expired, application B1 is created. When the applicant submits application B1, EVSS should not reject it.
> I'm wondering if the issues resulted from us deciding the persist the initiate application. We viewed this as a change that improve the user experience because they wouldn't need to start over, but I wonder if it introduced a defect. Same fact pattern as above, but with new rules: Application A1 is started on 9/22/2019. One year following the ITF, application A1 is expired. On 9/23/2020, the applicant logs and tried to complete the application. Rather than creating a new application (B1) the system persists the prior A1 application information and ID, which will be rejected by EVSS because it's flagged as expired. My hypothesis is that the back-end "expired" designation is not in alignment with our front-end user experience changes, which is resulting in EVSS rejecting the application.

**Comment by luke-gcio** [comment]
Paul has been on vacation - trying to schedule some time with him for the next discussion.

**Comment by luke-gcio** [comment]
History: Business decision was made to use form expiration as an ITF.  This was replaced by the ITF concept so some of this expired application business logic is not necessarily still needed.  

Active ITF is critical to making sure expiration dates are not necessary.  @Anna believes that the ITF automatically would be refreshed even if the form is longer than a year and a new one is necessary. Our system currently checks for a valid ITF and creates one if one does not exist.  Therefore, simply sending "form expiration" down to EVSS can simply be a date in the future.

Looks like we have to:
1. Send a future date to EVSS (and/or talk to EVSS about removing this data point.  Assumption is VBMS has this requirement so it may not be possible so our workaround is to send a future date).

Note on BDD: ITF is not really coming into play, it's really all about their separation date (even if it moves).  They have one year from the date of separation to file a claim (to be back paid to the separation date).
