### ISSUE TITLE
Outbound link to eBenefits results in 404 on VA.gov

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#12704]
## What happened?
1. https://www.va.gov/disability/how-to-file-claim/
2. Click Let's Get Started
3. Select No
4. Click the green Go to eBenefits button
5. See a 404 page on VA.gov

## Specs:
- Device: Macbook
- Browser: Chrome

## Desired behavior
Current link goes to https://www.va.gov/disability/how-to-file-claim/ebenefits/about/feature?feature=disability-compensation but the link should go instead to: https://www.ebenefits.va.gov/ebenefits/about/feature?feature=disability-compensation

Looks like it's just a relative link that needs a "https://www.ebenefits.va.gov/" prepended.

## Acceptance Criteria
- [ ] Link takes user to eBenefits so they can file a claim

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

![Screen Shot 2020-08-21 at 7.42.18 AM.png](https://images.zenhubusercontent.com/59c92d2eb0222d5de47906f6/a88f4e7e-c182-4e6a-9efa-b23fe2aee2db)

**Comment by kelsonic** [comment]
PR merged and ready for validation + closing 🙂
