### ISSUE TITLE
10203 STEM form review page - double lines on the review page

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#12703]
On the review page of the 10203 form, the user is given the opportunity to review their responses to all questions. One of the sections is titled "Program Details" and within this section, there is some hidden content. The content is hidden intentionally, but the horizontal lines intended as dividers are still displayed under certain conditions. 

### Steps to reproduce
1. Complete a 10203 STEM form ensuring the following selections are made:
- Education benefit selection: **Post-9/11 GI Bill (Chapter 33)**
- Are you enrolled in a science, technology, engineering, or math (STEM) degree program?: **Yes**
- About how much of your education benefit do you have left?: **Less than 6 months**
2. On the Review page, expand the "program details" section
3. Click edit
4. Change the response for "About how much of your education benefit do you have left?" to "More than 6 months"
5. Click "Update Page"
6. Collapse and then expand the Program Details section

### Expected behavior
The page looks the same with "More than 6 months" selected as it does with "Less than 6 months" selected
![Screen Shot 2020-08-21 at 10.33.53 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6e892012-767e-4657-9f31-17813fddac24)

### Actual behavior
Additional break between "About how much of your education benefit do you have left?" and "STEM degree and school details"
![Screen Shot 2020-08-21 at 10.34.06 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/82476b41-cb23-416a-99b7-9c8840558cc8)

**Comment by dmccurdybah** [comment]
Platform team is working on a fix

**Comment by dmccurdybah** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14681

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-26 at 10.28.02 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b3edb550-1792-43d8-9c2b-3b94454cf872)

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
