### ISSUE TITLE
Debt Letters - Bug - Right rail is stacking on medium screens

### ISSUE THREAD

**Issue by bradl3yC** [department-of-veterans-affairs/va.gov-team#12714]
Styles need to be modified to only stack the right rail content if the user is on a small screen

![Screen Shot 2020-08-21 at 1.26.08 PM.png](https://images.zenhubusercontent.com/5450f83c7c6ccc6277a5c4b7/2ba7ed63-5d9d-4373-b8ad-3f1bfa7a9b55)

**Comment by leahkeeler** [comment]
done
