### ISSUE TITLE
[DISCOVERY] Test coverage for Liquid templates

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12724]
## Issue Description
The Facilities team is prioritizing test coverage for our suite of products and plan to make test coverage for VAMC pages a 4Q2020 priority. 

Before we can scope and groom the work, we need to understand the following:
- What type of testing is possible and/or preferred for Liquid templates?
  - Our understanding is that only automated tests are possible. Are there alternatives to unit tests? 
- What tests currently exist for templates used on VAMC pages?
- What are the considerations for Liquid templates which impact cross-product pages?

## Acceptance Criteria
- [ ] The Facilities team understands the current status of test coverage for Liquid templates and knows what tests are needed to expand VAMC test coverage. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brangi** [comment]
Response from VSP - https://dsva.slack.com/archives/CBU0KDSB1/p1598998280125800?thread_ts=1598997047.120100&cid=CBU0KDSB1

**Comment by mmiddaugh** [comment]
Pulling out some details from the Slack thread referenced above 

VSP is looking to add support for testing content and application builds together [#13118](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13118)
-  separate from the content build because of the strict performance constraints
- separate from the application build because it does not have access to the content build

**Background**
1) Content is created in Drupal
2) The content build requests that content
3) Much data manipulation and massaging happens
4) Data is fed into the Liquid templates
  - Templates include other templates based on the content itself
5) More manipulation of resulting DOM
6) HTML files are written
**Unfortunately, most of this process has zero tests and poor error handling.**

The challenge with testing content is that a content editor can makes changes at any time, and if we're testing against it, they can inadvertently break our CI, preventing branches from being merged and applications from being deployed.

**Comment by mpelzsherman** [comment]
Just to document this: there is an automated test that runs as part of the website build/compilation - in Jenkins, that would be during the vagov(dev|staging|prod) builds.

`src/site/stages/build/plugins/check-broken-links`
