### ISSUE TITLE
Under certain conditions, a user can be shown Profile sections in the sub-nav but be blocked from accessing them

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12727]
I just ran into a situation on staging where user 36 was blocked from anything but Account Security, but they are shown Personal Info and Connected apps in the subnav. Trying to go to either of those other two sections results in them being redirected to `account-security`.

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/d99c9d44-d813-4cc9-8a6f-f1a0755be85d)

Full response from `GET user` is below. Note the `MVI` error. This is almost certainly the cause of this weird behavior. The user is coming back as LOA3 with 2FA turned on, so they are shown the sub nav options, but they are blocked from going to those pages.

The expected behavior in this situation is to:
- hide those non-Account security subnav items
- ideally also hide the `We can't load all your info...` alert at the top of the page. This is being shown because we are still making a call to `GET personal_information` and it's failing due to an MVI/MPI-related error.

`GET user/`:
```
{
  "data": {
    "id": "",
    "type": "users_scaffolds",
    "attributes": {
      "services": [
        "facilities",
        "hca",
        "edu-benefits",
        "form-save-in-progress",
        "form-prefill",
        "user-profile",
        "appeals-status",
        "identity-proofed",
        "evss_common_client",
        "claim_increase"
      ],
      "account": { "accountUuid": "c049d895-ecdf-40a4-ac0f-7947a06ea0c2" },
      "profile": {
        "email": "vets.gov.user+36@gmail.com",
        "firstName": "WESLEY",
        "middleName": "Watson",
        "lastName": "FORD",
        "birthDate": "1986-05-06",
        "gender": "M",
        "zip": "22182",
        "lastSignedIn": "2020-08-21T22:13:08.801Z",
        "loa": { "current": 3, "highest": 3 },
        "multifactor": true,
        "verified": true,
        "signIn": { "serviceName": "idme", "accountType": "N/A" },
        "authnContext": "http://idmanagement.gov/ns/assurance/loa/3/vets"
      },
      "vaProfile": null,
      "veteranStatus": null,
      "inProgressForms": [
        {
          "form": "22-10203",
          "metadata": {
            "version": 1,
            "returnUrl": "/benefits/stem-eligibility",
            "savedAt": 1597089200404,
            "expiresAt": 1602273198,
            "lastUpdated": 1597089198
          },
          "lastUpdated": 1597089198
        }
      ],
      "prefillsAvailable": [
        "21-686C",
        "40-10007",
        "22-1990",
        "22-1990N",
        "22-1990E",
        "22-1995",
        "22-1995S",
        "22-5490",
        "22-5495",
        "22-0993",
        "22-0994",
        "FEEDBACK-TOOL",
        "22-10203",
        "21-526EZ",
        "21-526EZ-BDD",
        "1010ez",
        "21P-530",
        "21P-527EZ",
        "686C-674",
        "20-0996",
        "MDOT"
      ],
      "vet360ContactInformation": {}
    }
  },
  "meta": {
    "errors": [
      {
        "externalService": "MVI",
        "startTime": "2020-08-21T22:17:28Z",
        "endTime": null,
        "description": "MVI_504, 504, Gateway timeout, Did not receive a timely response from an upstream server",
        "status": 504
      },
      {
        "externalService": "EMIS",
        "startTime": "2020-08-21T22:17:28Z",
        "endTime": null,
        "description": "EMISRedis::VeteranStatus::NotAuthorized, NOT_AUTHORIZED",
        "status": 401
      }
    ]
  }
}

```

Also, the call to `GET personal_information` errored, but that likely has nothing to do with this behavior:
```
{
  "errors": [
    {
      "title": "Unexpected response body",
      "detail": "MVI service responded without a birthday or a gender.",
      "code": "MVI_BD502",
      "source": "V0::Profile::PersonalInformationsController",
      "status": "502"
    }
  ]
}
```

**Comment by sanlouise** [comment]
Oh, glad you caught this before Profile 2.0 is live.

Also, I think we might need to ask for a copy update for the `notInMVI` [error alert ](src/applications/personalization/profile-2/components/NotInMVI.jsx). When MVI returns `null`, we'll still want the user to see `/account-security`, and they will be shown a message that indicates they should `contact your nearest VA medical center to verify and update your records`, which is not necessarily needed.

**Comment by erikphansen** [comment]
This is still happening on staging, so I checked out how we handle it with Profile v1:

<img width="1070" alt="Screen Shot 2020-08-24 at 7 38 03 AM" src="https://user-images.githubusercontent.com/20728956/91058141-f8ebf300-e5dc-11ea-8b34-19dc8d7c8530.png">

So I think the correct approach to take with Profile 2.0 in this situation is:
- hide all the subnav routes that aren't for `Account security`
- and ideally also hide the `We can't load all your info...` alert at the top of the page (this is being shown because we are still making a call to `GET personal_information` and it's failing)

I will update the ticket to reflect this.

**Comment by peggygannon** [comment]
@sanlouise thanks. Just checking to see if the "We can't load all of your information" error would work in this scenario? 

cc @erikphansen

**Comment by erikphansen** [comment]
I think that right now we are showing the correct error alert on the Account Security page for this scenario. It's basically in line with the error we're showing on Profile v1 in this case.

Maybe the real question is: should we show a different error on the Account Security page when there is an error connecting to MPI/MVI?

Right now we simply check to see if the user is in MPI/MVI based on the data we got from the `GET user/` call. The actual check in the code is simply: `export const isInMVI = state => selectProfile(state).status === 'OK';` (https://github.com/department-of-veterans-affairs/vets-website/blob/c546f329a82405ad0455348df4681a724779ee2e/src/platform/user/selectors.js#L8). But it's possible that the value of `status !== 'OK'` because there was an error with MPI and not because they really aren't in MPI. We'd need to dig into figuring out if we do anything with the MPI error we get from `GET user/` as part of `meta.errors`:
```
{
  "title": "Unexpected response body",
  "detail": "MVI service responded without a birthday or a gender.",
  "code": "MVI_BD502",
  "source": "V0::Profile::PersonalInformationsController",
  "status": "502"
}
```

So for now we just need to remove those subnav items when the user is not appearing in MPI. I'll make another ticket to investigate if we do anything with the MPI error I pasted above.

**Comment by erikphansen** [comment]
A little more info. I failed to note the Redux state when I encountered this error last week. So I used Proxyman to mock the `GET user/` response to be exactly what it was last week and this is the Redux state (with some irrelevant data removed for brevity). You can see that when there is an upstream MPI/MVI error, we set the `user.profile.status` to `'SERVER_ERROR'`:
```
{
  vaProfile: {
    hero: {
      userFullName: {
        first: 'Wesley',
        middle: 'Watson',
        last: 'Ford',
        suffix: null
      }
    },
    personalInformation: {
      gender: 'M',
      birthDate: '1986-05-06'
    },
    militaryInformation: null,
    paymentInformation: null,
    paymentInformationUiState: {
      isEditing: false,
      isSaving: false,
      responseError: null
    }
  },
  vet360: {
    hasUnsavedEdits: false,
    initialFormFields: {},
    modal: null,
    modalData: null,
    formFields: {},
    transactions: [],
    fieldTransactionMap: {},
    transactionsAwaitingUpdate: [],
    metadata: {
      mostRecentErroredTransactionId: ''
    },
    addressValidation: {
      addressValidationType: '',
      suggestedAddresses: [],
      confirmedSuggestions: [],
      addressFromUser: {
        addressLine1: '',
        addressLine2: '',
        addressLine3: '',
        city: '',
        stateCode: '',
        zipCode: '',
        countryCodeIso3: ''
      },
      addressValidationError: false,
      validationKey: null,
      selectedAddress: {},
      selectedAddressId: null
    },
    transactionStatus: ''
  },
  hcaEnrollmentStatus: {
    ...
  },
  profileUi: {
    isSideNavOpen: false,
    isMenuTriggerPinned: false,
    focusTriggerButton: false
  },
  connectedApps: {
    apps: [],
    errors: [],
    loading: false
  },
  announcements: {
    isInitialized: true,
    dismissed: [
      'single-sign-on-intro',
      'pittsburgh-vamc',
      'find-benefits-intro',
      'personalization',
      'welcome-to-new-vaos'
    ]
  },
  externalServiceStatuses: {
    loading: false,
    statuses: null
  },
  featureToggles: {
    ...
  },
  navigation: {
    showFormSignInModal: false,
    showLoginModal: false,
    utilitiesMenuIsOpen: {
      search: false,
      help: false,
      account: false
    }
  },
  scheduledDowntime: {
    globalDowntime: null,
    isReady: true,
    isPending: false,
    serviceMap: {},
    dismissedDowntimeWarnings: []
  },
  user: {
    login: {
      currentlyLoggedIn: true,
      hasCheckedKeepAlive: true
    },
    profile: {
      userFullName: {
        first: 'WESLEY',
        middle: 'Watson',
        last: 'FORD'
      },
      email: 'vets.gov.user+36@gmail.com',
      dob: '1986-05-06',
      gender: 'M',
      accountType: 3,
      loa: {
        current: 3,
        highest: 3
      },
      verified: true,
      mhvAccount: {
        accountLevel: null,
        accountState: 'no_account',
        errors: null,
        loading: false,
        termsAndConditionsAccepted: true
      },
      vet360: {},
      savedForms: [
        {
          form: '22-10203',
          metadata: {
            version: 1,
            returnUrl: '/benefits/stem-eligibility',
            savedAt: 1597089200404,
            expiresAt: 1602273198,
            lastUpdated: 1597089198
          },
          lastUpdated: 1597089198
        }
      ],
      prefillsAvailable: [
        ...
      ],
      loading: false,
      services: [
        'facilities',
        'hca',
        'edu-benefits',
        'form-save-in-progress',
        'form-prefill',
        'user-profile',
        'appeals-status',
        'identity-proofed',
        'evss_common_client',
        'claim_increase'
      ],
      multifactor: true,
      signIn: {
        serviceName: 'idme',
        accountType: 'N/A'
      },
      veteranStatus: 'NOT_AUTHORIZED',
      status: 'SERVER_ERROR'
    }
  },
  megaMenu: {
    currentDropdown: '',
    currentSection: '',
    display: {}
  }
}
```
The code that does this is at https://github.com/department-of-veterans-affairs/vets-website/blob/bc8913736fe039ae5d092e568ed1e41c28ca8bba/src/platform/user/profile/utilities/index.js#L105-L109

So it would be pretty easy to show a different error message if we cannot connect to MPI. I think that would a nice enhancement so it doesn't look like we are telling Vets that we can't find them in MPI when in reality we just cannot connect to MPI at this time.

**Comment by erikphansen** [comment]
@mshea0606 heads up that this bug came up late last week and I pulled it into the sprint and have a PR open for it.

**Comment by erikphansen** [comment]
Handled by https://github.com/department-of-veterans-affairs/vets-website/pull/14002. It's been merged. There is no good way to validate this so I'm closing it.

**Comment by mshea0606** [comment]
@erikphansen thanks for the heads up!

**Comment by erikphansen** [comment]
I created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12817) to discuss showing a different error message in this case, when we cannot connect to MPI.
