### ISSUE TITLE
STEM: Add additional GA tracking to 10203

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12733]
As a developer, I need to add additional Google Analytics tracking to the STEM 10203 so that adjustments can be made to the form based on user behavior.

## Assumptions:
1. This work _Originally posted by @jonwehausen in https://github.com/department-of-veterans-affairs/va.gov-team/issues/10780#issuecomment-678442138_
2. This work does not need to be behind a feature or prod flag.

## Acceptance Criteria:
1. The `edu-eligibilty-criteria-months-remaining-for-use` event is replaced with `edu-eligibility-criteria-months-remaining-for-use`. (**Note:** Typo (missing second **_"i"_** in eligibility)

2. The event `cta-primary-button-click` is triggered on each "Exit Application" button:
    a. `/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/benefits/initial-confirm-eligibility`
    b. `/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/benefits/confirm-eligibility`

3. The unnecessary firing of event `cta-primary-button-click` is removed.  (**Note:** There looks to be a one-off `cta-primary-button-click` event firing occasionally upon continuing from `benefits/stem-eligibility` to `/benefits/confirm-eligibility` and `/benefits/eligibility` to `/benefits/initial-confirm-eligibility` we will want to remove. The `edu-stem-scholarship-ineligibility-alert` and `edu-form-change` events are perfect here and we will be able to determine those who continue / move back using page URLs.)

4. The ineligibility alert is tracked on `/benefits/initial-confirm-eligibility` using the following event:
```javascript
   'event': edu-stem-scholarship-ineligibility-alert
```

## Supporting Artifacts:
1. For AC1:
![image](https://user-images.githubusercontent.com/48527022/90923933-8ac8e580-e3bc-11ea-9541-c65a68a9a036.png)

2. For AC2:
![image](https://user-images.githubusercontent.com/48527022/90924120-daa7ac80-e3bc-11ea-8c4e-ec5aa41ed541.png)

3. For AC3:
Screenshot 1 | Screenshot 2
------------ | -------------
![image](https://user-images.githubusercontent.com/48527022/90924269-25292900-e3bd-11ea-836d-33fcb4a66b84.png) | ![image](https://user-images.githubusercontent.com/48527022/90924768-0c6d4300-e3be-11ea-8138-c65bef92d0cd.png)

## Notes:
cc: @bsmartin-ep and @bmcgrady-ep for visibility

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14081

**Comment by zurbergram** [comment]
Testing instructions for AC#2 in Chrome
1. Navigate to either page for A or B
1. Open Dev Tools
1. Go to Sources tab
1. In the Page section, navigate to `top/"webpack://"/./src/applications/edu-benefits/10203/` and click on `analytics-functions.js` 
1. Put a breakpoint on line 39, this should be last line of `exitApplication` function
![Screen Shot 2020-09-02 at 9 34 53 AM](https://user-images.githubusercontent.com/1094999/91990300-904cf680-ecff-11ea-8016-8e9ba47dde2d.png)

1. Click "Exit Application", breakpoint should be hit
1. In console type `window.dataLayer` and hit enter
1. Observe event is present

Note: after leaving a form, `window.dataLayer` is cleared so this is how to check event is added

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-02 at 11.20.29 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4783f5af-7e56-4561-8f2a-54f365c87ab0)
##
![Screen Shot 2020-09-02 at 11.33.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f5773026-e629-4e0f-80c4-9b7424f8c9b2)
##
![Screen Shot 2020-09-02 at 11.34.19 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3a4127f7-33e2-4028-aa62-6f09e7d08697)
##
![Screen Shot 2020-09-02 at 11.38.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e0000165-22da-4c0e-bba6-e2b97d79de4d)
##
![Screen Shot 2020-09-02 at 11.40.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/69ef284d-7343-452c-ad02-0c2df937a96a)
##
![Screen Shot 2020-09-02 at 12.08.11 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/592bb137-f84e-4453-a90f-d5260214fc70)

**Comment by sonntag-adam** [comment]
In staging. Closing story.
