### ISSUE TITLE
Refactor Submit Button States

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#12743]
## Work Planned

- [x] Extract default SubmitButtons state as it's own component
- [x] Extract ApplicationSubmitted as it's own component
- [x] Extract ClientError as it's own component
- [x] Extract FormSubmitPending as it's own component
- [x] Extract FormSubmitThrottledError as it's own component
- [x] Extract FormValidationError as it's own component
- [x] Extract GenericError as it's own component
- [x] Update SubmitButtons to use new components.
- [x] Add tests for all new things

## Success Criteria

"We didn't break anything":
- [x] Improved automated test(s): thoroughness (of use/edge-cases) is more important than line coverage
- [x] PR created
- [x] PR reviewed (tag @cvalarida as a PR reviewer)
- [x] PR merged 
- [x] Smoke-tested on staging ([verification steps](url))
- [x] Review staging analytics (verify previous weeks to analyze trends)
- [x] Pre-flight check: If issue, triage and assert roll forward/roll back. 
- [x] Prod deployment   
- [x] Smoke-tested on prod ([verification steps](url)) 
- [x] Review production analytics (verify daily over next few days)

## Risk Estimate

> _Scale: 1 (low) – 3 (high)_

Risk: **2**

Risks associated with this change are as follows:
- SubmitButtons will be reduced to a HOC that essentially controls which state is being shown. There is potential that a bug can be introduced here. Test coverage helps to mitigate that. 
- Potential for visual structure change or mis-alignment.

**Comment by Clark-W-Griswold** [comment]
Submission states rendered in staging:
Default state:
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/bd450ad9-f9d7-4bc6-9457-dc3bc07b405b)

Submit Pending:
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/eaefa83a-a844-4af5-a985-ffd8048fd98c)

Client Error:
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/e11a2e1e-dfb2-439e-86e6-3ad50f1b47b3)

Throttled Error:
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/01518569-d8f3-4664-a3eb-82473511a21b)

Validation Error:
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/4834aae7-7be0-4d52-9d9d-fd9406e4baea)

Generic Error:
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/14124e0d-5a94-494c-9c0f-47aef81b4664)

**Comment by meganhkelley** [comment]
@Clark-W-Griswold my understanding is that this is complete, I'm closing the ticket. Please reopen if needed.
