### ISSUE TITLE
Refactor SubmitController

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#12746]
## Work Planned

Refactor into a [fully controlled component](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-controlled-component).

Should fix UNSAFE_componentWillReceiveProps?

## Success Criteria

"We didn't break anything":
- [ ] Improved automated test(s): thoroughness (of use/edge-cases) is more important than line coverage
- [ ] PR created
- [ ] PR reviewed (tag @cvalarida as a PR reviewer)
- [ ] PR merged 
- [ ] Smoke-tested on staging ([verification steps](url))
- [ ] Review staging analytics (verify previous weeks to analyze trends)
- [ ] Pre-flight check: If issue, triage and assert roll forward/roll back. 
- [ ] Prod deployment   
- [ ] Smoke-tested on prod ([verification steps](url)) 
- [ ] Review production analytics (verify daily over next few days)

## Risk Estimate

> _Scale: 1 (low) – 3 (high)_

Risk: **1**

<provide an explanation for @meganhkelley to share with broader team>

**Comment by meganhkelley** [comment]
@f1337 @Clark-W-Griswold this work has been completed, correct? Can you please confirm & close as applicable?

**Comment by k80bowman** [comment]
The [UNSAFE_componentWillReceiveProps](https://github.com/department-of-veterans-affairs/vets-website/blob/63e0fc1e6e6e5028a92a619c73d36ffe732d57c8/src/platform/forms-system/src/js/review/SubmitController.jsx#L23) is still present

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
