### ISSUE TITLE
Refactor Common Error Components

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#12740]
## Work Planned

- [x] Add snapshot testing.
- [x] Add new component to error cases in SubmitButtons

## Success Criteria

"We didn't break anything":
- [x] Improved automated test(s): thoroughness (of use/edge-cases) is more important than line coverage
- [x] PR created
- [x] PR reviewed (tag @cvalarida as a PR reviewer)
- [x] PR merged 
- [x] Smoke-tested on staging ([verification steps](https://docs.google.com/spreadsheets/d/1WCEJgarh9sJKVys_xbtpWqBxLHQfX1eWSItBHUZSvos/edit?ts=5f3efa1a#gid=753663668))
- [x] Review staging analytics (verify previous weeks to analyze trends)
- [x] Pre-flight check: If issue, triage and assert roll forward/roll back. 
- [ ] Prod deployment   
- [ ] Smoke-tested on prod ([verification steps](https://docs.google.com/spreadsheets/d/1WCEJgarh9sJKVys_xbtpWqBxLHQfX1eWSItBHUZSvos/edit?ts=5f3efa1a#gid=753663668)) 
- [ ] Review production analytics (verify daily over next few days)

## Risk Estimate

> _Scale: 1 (low) – 3 (high)_

Risk: **1**

Risks associated with this change are as follows:

- Potential for visual structure change or mis-alignment

**Comment by Clark-W-Griswold** [comment]
PR opened: [13989](https://github.com/department-of-veterans-affairs/vets-website/pull/13989)
