### ISSUE TITLE
Refactor PreSubmit Section

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#12744]
## Work Planned

- [x] Extract PreSubmitSection as it's own component.
- [x] Update SubmitButtons to render PreSubmitSection

## Success Criteria

"We didn't break anything":
- [x] Improved automated test(s): thoroughness (of use/edge-cases) is more important than line coverage
- [x] PR created
- [x] PR reviewed (tag @cvalarida as a PR reviewer)
- [x] PR merged 
- [x] Smoke-tested on staging ([verification steps](url))
- [x] Review staging analytics (verify previous weeks to analyze trends)
- [x] Pre-flight check: If issue, triage and assert roll forward/roll back. 
- [x] Prod deployment   
- [x] Smoke-tested on prod ([verification steps](url)) 
- [x] Review production analytics (verify daily over next few days)

## Risk Estimate

> _Scale: 1 (low) – 3 (high)_

Risk: **2**

Risks associated with this change are as follows:
- Since we are moving the Presubmit section into it's own component and where it gets called, there is potential that a bug can be introduced here. Test coverage helps to mitigate that. 
- Potential for visual structure change or mis-alignment.

**Comment by f1337** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14025

**Comment by Clark-W-Griswold** [comment]
All tests are passing. Plan is to merge this afternoon post deployment and test with release to production on pending successful testing.

**Comment by Clark-W-Griswold** [comment]
Tested on staging:
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/c7ed3653-f334-4ef9-971c-cc062dc21fbc)
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/2877d2ce-48fa-4f1b-ba9d-2b80334628a6)![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/90295ee7-7f9e-4a7f-b0ce-52d9f9452c8e)

**Comment by Clark-W-Griswold** [comment]
This has been released to production.
