### ISSUE TITLE
Contact Center Review for Caregivers

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#12748]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description

The [family caregiver application](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/) allows pairs of Veterans and Caregivers to apply as a pair for the Program of Comprehensive Assistance for Family Caregivers (PCAFC).

### Launch Date

The form is currently in moderated production testing (beta-launch) with an estimated go-live of September 2020. We are expecting an influx of applications around October 2020.

### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/issues/12091#issuecomment-677686161

### Product Video

Product video will be coming soon.

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] VSP Analytics & Insights QA has been completed 
- [ ] VSP Analytics & Insights sends artifacts to appropriate contact centers
- [ ] VFS team completes brief VSP Collaboration Cycle Feedback survey [link](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before)

**Comment by Kimberley2019** [comment]
@ala-yna Thank you, we will review and send to the contact center for review and feedback.

**Comment by ala-yna** [comment]
Hi @Kimberley2019  - we're still refining some of the questions on the for, so I wasn't sure if it made sense to go through the steps to create a full video - since some of the fields be changing soon. What do you think?

**Comment by Kimberley2019** [comment]
@ala-yna It makes sense to hold off on the video and transcript if there are still changes to be made, it's better to send them the most up to date version.  These changes will not effect the current product guide that needs to be sent over for review correct?

**Comment by ala-yna** [comment]
@Kimberley2019  - The changes will not effect the product guide substantially. There are some questions that are currently marked as required that are going to be changed to not required in the future, for example. But the big issues (who fills out the form, the form experience, and what happens upon submission) are all the same.

**Comment by Kimberley2019** [comment]
@ala-yna I can send over the current product guide to the Contact Center for review, however, if there are changes made, they will need the updated product guide highlighting those changes.  I would personally wait until the product guide is 100% complete, because it can seem like double work, but that final decision is up to you and your team.  Please advise on how you would like to proceed.

**Comment by joanneesteban** [comment]
@Kimberley2019 Here's their product guide for review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12091#issuecomment-677686161

**Comment by Kimberley2019** [comment]
@joanneesteban Thanks for passing this along.  If it is the same link as the one listed under product guide, I have already reviewed and passed along to the VEO Contact Center.

I advised the Contact Center to provide any feedback and/or questions they had no later than 9/2/2020 and I have not received anything from them.  With that being said, the Contact Center Review is complete.

**Comment by Kimberley2019** [comment]
@ala-yna I advised the Contact Center to provide any feedback and/or questions they had no later than 9/2/2020 and I have not received anything from them. With that being said, the Contact Center Review is complete.

If there have been any modifications, please provide updated documents so that the Contact Center will have the most up to date information to provide to veterans.
