### ISSUE TITLE
Refactor RenderErrorMessage section

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#12745]
## Work Planned

- [x] Extract RenderErrorMessage as it's own component
- [x] Update SubmitButtons to accept a prop to render RenderErrorMessage component

## Success Criteria

"We didn't break anything":
- [x] Improved automated test(s): thoroughness (of use/edge-cases) is more important than line coverage
- [x] PR created
- [x] PR reviewed (tag @cvalarida as a PR reviewer)
- [x] PR merged 
- [x] Smoke-tested on staging ([verification steps](url))
- [x] Review staging analytics (verify previous weeks to analyze trends)
- [x] Pre-flight check: If issue, triage and assert roll forward/roll back. 
- [x] Prod deployment   
- [x] Smoke-tested on prod ([verification steps](url)) 
- [ ] Review production analytics (verify daily over next few days)

## Risk Estimate

> _Scale: 1 (low) – 3 (high)_

Risk: **1**

Risks associated with this change are as follows:
- Moving `renderErrorMessage` function into its own component has potential to introduce bugs. Test coverage helps to mitigate that.
- Potential for visual structure change or mis-alignment.

**Comment by meganhkelley** [comment]
@Clark-W-Griswold is this complete? If so, please close this ticket

**Comment by Clark-W-Griswold** [comment]
![image.png](https://images.zenhubusercontent.com/5db31b5573e8f70001d9e0c8/145d8e76-65e8-4ae2-8625-8a98c1f0bbdb)

**Comment by meganhkelley** [comment]
@Clark-W-Griswold this work has been completed, correct? Can you please confirm & close as applicable?
