### ISSUE TITLE
[Design] Claims Status: Estimated Claim Completion Date Status Statement

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12753]
## Issue Description
Temporarily replace the estimated claim completion date with a general statement.  This will need to be reviewed and reconsidered after the COVID-19 situation has resolved.

There has been a request to change the estimated completion date for claims to a message.  This is the suggested message:

_The estimated claim completion date feature has been temporarily removed. Due to the impact COVID-19 has had on the availability and scheduling of required in-person medical disability exams, the estimated completion date is not accurate at this time.  VA is coordinating efforts to ensure all exams are scheduled and conducted as soon as it is safe in each area.  You can review the status of exams in your area here._ 

This story is to design this message into the CST page.  However, it may be worth reaching back out to the stakeholders to see if the middle ground of including the estimate _with_ the message may be more accurate and therefore what we suggest.

## Acceptance Criteria
- [ ] Decide whether we remove the date completely
- [ ] Design with/without date and the message
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
What are your thoughts about taking the simple solution for this round and adding the date calculation into the second round of updates?  I feel like we would want to really spend the time to do this right and right now we don't have that.

**Comment by luke-gcio** [comment]
Spoke to Matt Self.  He is going to reach out to Chris J about going in the total removal direction and whether DEPO is ok with this.

**Comment by kevinstachura** [comment]
I have a design on standby already (for the removal). I can't imagine we can change the algorithm to meet the desired turnaround timeline requested by VBA...makes sense that would be a second round if possible.

**Comment by kevinstachura** [comment]
I will push up the aforementioned design to Invision today (for the estimated completion date removal / alert box with text) and post here.

**Comment by kevinstachura** [comment]
https://vsateams.invisionapp.com/share/VUYLT5C9KEZ#/430229164_Claim_Appeal_Status_-_Claim_Detail

**Comment by kevinstachura** [comment]
No change has been made on this since the preceding comment / Invision link.
