### ISSUE TITLE
[Design] - MVP learning center - iterate on image list page template

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12759]
Create version of image list template 
- without search by keyword
- make the `ol` less misleading

**Note:** Content authors can add an image file and enter the title of the image. They'll have optional descriptive text. 

## Acceptance criteria

- [ ] create mobile version of image list template  (depending on audit)
- [ ] create desktop version of image list template
- [ ] @andaleliz, @rtwell, and @jenniferlee-dsva to review

**Comment by andaleliz** [comment]
moving this to the icebox since this template is part of MVP 1.1, not 1.0

**Comment by andaleliz** [comment]
I need some more information in order propose a design that supports the way data comes in from the CMS for this template.  

@kelsonic, @oksana-c  and/or @ncksllvn, can you share any information about how data is structured for this template? Is it all one big WYSIWYG dump?  Drupal screenshots might be helpful so we can see it from the author perspective.

**Comment by ncksllvn** [comment]
Not a _WYSIWYG dump_ 😄 We get nice structured data. This page's data is a list of "media images", each one containing an image location (src), description, label, etc. Easy to work with.

**Comment by andaleliz** [comment]
Awesome, thank you for confirming!

**Comment by brianalloyd** [comment]
Closing as 'Not Required' based on review in grooming.
