### ISSUE TITLE
STEM: Post-launch content updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12752]
As a developer, I need to update content in the 10203 so that it matches DEPO patterns and practices so that the applicant is provided with a consistent experience.

## Assumptions:
1. This work was originally intended to be completed behind a prod flag, but it was not (went live on 09/16).
2. This was reviewed and signed off in staging as of 09/16/20.

## Acceptance Criteria
1. On the 10203 form [introduction page](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction):
    a. The step 1 content matches supporting artifact 1.
    b. The step 4 content matches supporting artifact 1. 
    c. The "Privacy Act Statement" link has an anchor, `#privacy_policy`, that can be used to bring the user to when linked to from external sources.
2. In the 10203 form, Chapter 3 Page 1, the question "About how much of your education benefit do you have left?" answer options are:
    - More than 6 months
    - 6 months or less
    - None. I've used all of my education benefit.
3. In the 10203 form, Chapter 3 eligibility alert, the content `Have used all of your education benefits or are within 6 months of doing so when you submit your application` is replaced with `Have used all of your education benefits or are within 6 months of using all your benefits when you submit your application`
4. In the 10203 form, Chapter 5 page 2, the content `VA makes payments only through direct deposit, also called electronic funds transfer (EFT). If you’re approved for the Rogers STEM Scholarship, we’ll need to know where to deposit the funds` is replaced with `We make payments only through direct deposit, also called electronic funds transfer (EFT). If you’re approved for the Rogers STEM Scholarship, we’ll need to know where to deposit the funds.`
5. In the 10203 form, Chapter 5 page 2, the phone number `1-800-333-1795` is replaced with `800-333-1795`
6. In the 10203 form, Chapter 5 page 2, the phone number `1-888-224-2950` is replaced with `888-224-2950`
7. In the 10203 form, on the confirmation page, the content after **What happens after I apply?** is:

> We usually decide on applications within 30 days.  
> 
> You’ll get a Certificate of Eligibility (COE) or decision letter in the mail. If we’ve approved your application, you can bring the COE to the VA certifying official at your school.
> 
> [Learn more about what happens after you apply](https://www.va.gov/education/after-you-apply/)

## Supporting Artifacts:
1. [Version 5 of the Content doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/514c73ab362e53c01952459bb8d27ebbf297c95c/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-post-staging-review-v0.5.md) as of 08/27
2. [Version 5 of the Prototype](https://bahdigital.invisionapp.com/share/DGIAEP75WKA#/screens) as of 08/27

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14199

**Comment by delli-gatti-michael** [comment]
Local testing complete

Tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/971

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by ccruzgra** [comment]
@delli-gatti-michael UXers had a look and this checks out.

**Comment by sonntag-adam** [comment]
Closing story.

**Comment by desireeturner** [comment]
Reopened this issue to be tested on Prod since it did not have a prod flag.

**Comment by delli-gatti-michael** [comment]
Validated in Production. Closing this issue
