### ISSUE TITLE
[Design] - MVP learning center - audit of page template designs to determine if any do not need a mobile version

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12760]
Audit templates to determine if any page templates do not need a mobile version.

Acceptance Criteria
- [x] review all pages templates for Learning Center
- [x] run findings by another designer
- [ ] create GH issues for creating page templates that require a specific mobile version, that do not already have one.

**Comment by andaleliz** [comment]
Audit completed, would love to get another designers input before I consider this "final" though. @rtwell can you please take a look and see if you agree w/ what I've outlined below?

**TL;DR** 
I think we would benefit from a mobile mock-up for all templates except the text-only step-by-step template, and a single FAQ template.

Template | Release Version | Mobile Design
--- | --- | ---
Home | 1.0 | @rtwell working on it
Checklist | 1.0 | needed, new pattern
Step-by-step w/out screenshots | 1.0 | needed, since uses existing ds component
Step-by-step w/ Screenshots | 1.0 | needed, to explore possible need for progressive enhancement. 
FAQ Multiple | 1.0 | needed, to explore use case of many questions (also, define `many`)
FAQ Single (question and answer) | 1.0 | not needed - just text 
About - text only | 1.1 |  not needed - just text
About - text w/ on this page, loooong content | 1.1 | needed, to explore use case of very long text (also, define `very long`)
About - tables | ? | needed, new pattern. Check w/ VFS team exploring responsive tables
Keyword results | 1.0 | needed, new pattern
Tag results | 1.0 | needed, new pattern
Media list - video | 1.1 | needed, see #11497
Media list - images | 1.1 | needed, see #12759
Media list - filtered list | 1.1 | needed, see #12759

**Comment by rtwell** [comment]
thank you for this comprehensive list @andaleliz !

I agree with everything except FAQ multiple. While I agree, we should consider how we define `many`, I do not think we need a mobile design—it'll be a train of accordions and the design system covers that use case. Unless we anticipate the need for accordions with more robust labels ([pittsburgh](https://www.va.gov/pittsburgh-health-care/health-services/) has accordions like this), we're OK for now.

**Comment by rtwell** [comment]
Oh, sorry, it just occurred to me—the 3 "results" pages (search results, articles tagged, and view all topics) are identical in their layout, so i think we can get away with a single design for all 3.

**Comment by andaleliz** [comment]
@rtwell sounds good - I'll transfer this table to our status/decisions doc.  Your reasoning behind the FAQ multiple makes sense.

I think you're right for mobile about the search results pages too, but we may need two designs for desktop so that QA/devs can clearly understand any differences between the two layouts. A couple differences immediately come to mind:
-  the `h2` or `h3` (whatever heading it ends up being) from a keyword search results vs an article tagged list page will probably have different verbiage. 
- sort order will probably be different for the two: `keyword search` by relevancy, and `articles tagged` by alpha order (probably).

**Comment by rtwell** [comment]
right—we have the desktop comps for all of those to clarify the differences
