### ISSUE TITLE
[Design] -  MVP learning center - iterate on search pattern

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12761]
Our usability study revealed some ambiguity about the search radio options in our design. Explore a solution where users get the suggestion to search VA.gov only after LC search has returned no results.

Acceptance Criteria
- [ ] create mock-up matching ^ for mobile + desktop
- [ ] review with @jenniferlee-dsva and @rtwell

**Comment by andaleliz** [comment]
@rtwell and I synced today and he mocked this up in the call. Assigning over to him to wrap up/close out.

**Comment by rtwell** [comment]
After speaking with @jenniferlee-dsva , we will not be utilizing this approach for MVP.
