### ISSUE TITLE
10-10CG Program Content Changes

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#12766]
Draft content changed/recommendations based off the following feedback received from the program team on 8/21:

**Note: the following items were pulled directly from the feedback, and do not reflect the final decision/guidance.**

1. Everywhere the “Need Help” phone number of 877-222-8387, we need to have it changed to 855-488-8440.  This is the same office, but a number specific to PCAFC questions. 
2. Step 2 Apply (on application intro page)- Please add language in red: You will need to complete all form questions which are marked as required before submitting the form  
3. Remove Sex as a required field for Veteran, Primary and Secondary Family Caregivers, and remove 'unknown' option.
4. Please remove requirement for “Please enter the name of the medical facility where the Veteran last received medical treatment” and “Was this a hospital or clinic?”  ** Not a space to show distinct transition. Reading quickly caused confusion.**
5. Remove reference to VSO support 
6.  For the purpose of PCAFC, we use the following language but can adjust it based on the context of where this blurb sits.: If you disagree with this decision, you have the right to appeal.  Please contact the Patient Advocate at your local VA medical center to discuss the appeal process.  Your Caregiver Support Coordinator is also available if you have additional questions.

**Comment by psanders86** [comment]
# Content changes #

The following changes to the 10-10CG form are in response to the program's team's feedback from Aug. 21, 2020.

## Issue 1: Change phone number ##

*Everywhere the “Need Help” phone number of 877-222-8387, we need to have it changed to 855-488-8440.  This is the same office, but a number specific to PCAFC questions.*

The phone number 877-222-8387 (877-222-VETS) is a well-publicized number promoted by VA for Veterans to receive assistance on a variety of issues. The number 855-488-8440 is for the Health Eligibility Center Enrollment and Eligibility Division. @ala-yna is reaching out to the program team to confirm that this is their intention. 

![md-1.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/7dd6d4d1-22f6-4de1-a593-56020d2b3c73)

**Revised language:** Replace the highlighted phone number with 855-488-8440. 

<p> <br>

The phone number also appears on the subway map on the introduction page.

![md-2.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/de2a04cf-953d-4e5a-ab1e-ed45dfcd1952)

**Revised language:** Replace the highlighted phone number with 855-488-8440. 

## Issue 2: Clarify instructions on subway map ##

*Step 2 Apply (on application intro page)- Please add language in red: You will need to complete all form questions which are marked as required before submitting the form*

We can modify the language as requested, but VA.gov style guides do not allow us to put text in a different color as a way for emphasis.

![md3.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/2479d681-15f8-4dfb-b981-96e3139095ee)

**Revised language:** Please remember, whether you’re the Veteran or a family caregiver, you’ll need to complete all form questions that are marked as required before submitting the form. After submitting the form, you'll receive a confirmation screen that you can print for your records.

## Issue 3: Gender question ##

*Remove Sex as a required field for Veteran, Primary and Secondary Family Caregivers, and remove 'unknown' option.*

This appears a maximum of four times in the form – for the Veteran, the Primary Family Caregiver, the Secondary Family Caregiver, and the Secondary Family Caregiver (2).

![md-4.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/667dc29a-28d4-4bfe-ba21-fd28c5d3986b)

**Revised language:** N/A. This is entirely a design function to remove the “Required” label as well as the third radio button.

## Issue 4: Veteran medical information ##

*Please remove requirement for “Please enter the name of the medical facility where the Veteran last received medical treatment” and “Was this a hospital or clinic?” Not a space to show distinct transition. Reading quickly caused confusion.*

This appears on the Veteran health information page.

![md-5.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/0e9f76c1-4d5e-439b-b43a-1327a188b2ea)

**Revised language:** N/A. This is entirely a design function to remove the “Required” label and increase the spacing.

## Issue 5: VSO support ##

*Remove reference to VSO support*

This appears on the introduction page subway map. The language for the Veterans Service Organization appears on the paper form without a hyperlink. The online version takes applicants to a page about VSOs, but the program team expressed that the link was not relevant to 10-10CG applicants.

![md-6.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/10ce2dea-e948-4eda-80da-3f577c98dbae)

**Revised language:** Delete the highlighted hyperlink.

## Issue 6: PCAFC appeal process ##

*For the purpose of PCAFC, we use the following language but can adjust it based on the context of where this blurb sits.: If you disagree with this decision, you have the right to appeal.  Please contact the Patient Advocate at your local VA medical center to discuss the appeal process.  Your Caregiver Support Coordinator is also available if you have additional questions.*

This can be added to the “next steps” portion of the subway map on the introduction page.

![md-7.png](https://images.zenhubusercontent.com/5e0643332dae1ddd8a211288/2a92fc03-7686-4c75-98fc-b8661fee33ec)

**Revised language:** If you aren’t eligible for PCAFC, you have the right to appeal. You can contact the patient advocate at your local VA medical center to discuss the appeal process. Your Caregiver Support Coordinator is also available if you have additional questions.
You may also be eligible for the Program of General Caregiver Support Services (PGCSS). To find out more, contact VA’s Caregiver Support Line at 855-260-3274<hyperlink>, visit www.caregiver.va.gov<hyperlink> or discuss these options with your local Caregiver Support Coordinator.

**Comment by psanders86** [comment]
Added @jonathanjnelson to this so he can get notifications.

**Comment by jonathanjnelson** [comment]
Design to do list: 

- [ ] Issue 1 **Phone number**
- [X] Issue 2 **Content in _Apply_ section**
- [X] Issue 3 **Remove _required_ and _unknown_ for Gender question**
- [X] Issue 4 **Remove _required_  and possible redesign for Medical facility** 
- [X] Issue 5 **Remove reference to VSO support**
- [X] Issue 6 **PCAFC appeal process**

**Comment by LinnJS** [comment]
Frontend to do list: 

- [ ] Issue 1 **Phone number**
- [ ] Issue 2 **Content in _Apply_ section**
- [ ] Issue 3 **Remove _required_ and _unknown_ for Gender question**
- [ ] Issue 4 **Remove _required_  and possible redesign for Medical facility** 
- [ ] Issue 5 **Remove reference to VSO support**
- [ ] Issue 6 **PCAFC appeal process**
