### ISSUE TITLE
GET appointment data from staging

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#12776]
## User Story
**In order** to use the appointment questionnaire feature on the va.gov site in the nearby future
**As a** Veteran
**I want** I want the website engineers to have the ability to pull appointment data from the staging environment.
## Related Documentation
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13834
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
Provide the ability for the Health Quest module to query for appointment data from the staging endpoints.

## Acceptance Criteria
- [ ] Health Quest module must be able to query for appointment data from staging
- [ ] The format and structure of the data returned must match the requirements of invested parties(FE/Swagger docs etc)

**Comment by massrb** [comment]
Once access to VAMF staging is obtained we want to be able to connect and display an appointment

Acceptance Criteria
- [ ] Able to connect to VAMF appointments through vets-api in staging

**Comment by abuckley3385** [comment]
@massrb  can you please describe what the difference in this ticket is compared to what is being delivered for #12285 & #12404?

**Comment by massrb** [comment]
this is a much smaller subset of what is in #12404. Quite a bit of #12404 is complete based on that ticket, other things for PGD will have to be added at some point to the service.

 I didn't have to create this ticket but I thought perhaps I needed a new ticket for the next sprint

**Comment by abuckley3385** [comment]
1. How does PGD relate to retrieving appointment details and displaying in our workflow? 
2. When I read the #12404 acceptance ( not complete yet) is that we have retrieved appt. details and are able to show in the screen.  The comments state we are waiting for staging environment and blocked until we have access. This is the same as what the above tasks/description does?  So either we need to update #12404 and remove the acceptance and state the correct scope for that ticket or remove this one.

**Comment by massrb** [comment]
This is blocked until we have access to MAP (was VAMF but renamed to MAP)

**Comment by abuckley3385** [comment]
code is done and data available in Health quest API - just need to configure the environments (staging, prod, etc) and point to the code

**Comment by dillo** [comment]
Clarifying title further to "GET appointment by ID in staging(Live)"

**Comment by abuckley3385** [comment]
@dillo  do we need this ticket anymore now that we are connecting to staging with real map data not mock?

**Comment by dillo** [comment]
@abuckley3385 we still need to integrate the vets-api with staging MAP and pull down the appointment data from it. I can either create a new ticket to do that or I can edit this ticket to accomplish the work.

**Comment by abuckley3385** [comment]
@dillo  understood- is Mock data correct then? maybe its just rewording this ticket
