### ISSUE TITLE
[Bug] Find VA Forms - Detail Pages - 10-10CG - Possibly missing Online-tool section

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12774]
## What happened?
On CMS QA-environment, **[About VA Form 10-10CG](http://forms.demo.ci.cms.va.gov/find-forms/about-form-10-10cg?_format=static_html)** detail-page, **might**\* be missing **Online tool** section, per correponding spec on [copy-doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-content-docs/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx) pg. 45.

\*Check with VSA-Caregiver team PM @ala-yna re. 10-10CG launch; it may currently be a "dark" or "phased" launch, which should determine whether **Online tool** section should really be added right now to our Detail-page.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: \[CMS QA-environment requires Drupal login credentials]

## Steps to Reproduce
1. Go to http://forms.demo.ci.cms.va.gov/find-forms/about-form-10-10cg?_format=static_html \[requires Drupal login].
1. Observe that, between **When to use this form** and **Related forms and instructions** sections, there's no **Online tool** section.

**CMS QA-environment screenshot**:

<img width="732" alt="FFD-copy-bug-10-10cg" src="https://user-images.githubusercontent.com/587583/91115530-45681a80-e63f-11ea-9a8f-f986960c7252.png">

## Desired copy
**[Copy-doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-content-docs/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx) pg. 45 screenshot**:

![FFD-copy-spec-10-10cg](https://user-images.githubusercontent.com/587583/91115665-8b24e300-e63f-11ea-858e-743c1b171f25.png)

## Acceptance Criteria
- [ ] \[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ala-yna** [comment]
Hi @tlei123 - thanks for flagging this! This is actually expected behavior while we're still in beta-testing mode. We'll be updating the feature toggle on the Drupal page once we get the go-ahead from our business owners. The feature toggle will indicate that the online application tool is available for all. Thanks!

**Comment by tlei123** [comment]
Thx, @ala-yna !

@jenniferlee-dsva @MickinSahni , feel free to Close this ticket unless you'd like to keep this as a reminder for later.

**Comment by MickinSahni** [comment]
Thanks for the find! We're launching form detail pages before caregiver's launch anticipated in september so will be good to go. closing this out for now. 🙇
