### ISSUE TITLE
[Bug] Find VA Forms - Detail Pages - 21P-0969 - copy mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12773]
## What happened?
On CMS QA-environment, **[About VA Form 21P-0969](http://forms.demo.ci.cms.va.gov/find-forms/about-form-21p-0969?_format=static_html)** detail-page, in **Related forms and instructions** section, **VA Form 21P-527EZ**'s description didn't match\* the corresponding spec on the [copy-doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-content-docs/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx) pg. 27.

\***However**, this shorter related-form description _did_ match [About VA Form 21P-527EZ Detail-page](http://forms.demo.ci.cms.va.gov/find-forms/about-form-21p-527ez?_format=static_html)'s "When to use this form" section description, as well as [About VA Form 21P-527 Detail-page](http://forms.demo.ci.cms.va.gov/find-forms/about-form-21p-527?_format=static_html)'s related-form 21P-527EZ description.  Also, [copy-doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-content-docs/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx) pg. 43 for 21P-527EZ also showed this shorter description.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: \[CMS QA-environment requires Drupal login credentials]

## Steps to Reproduce
1. Go to http://forms.demo.ci.cms.va.gov/find-forms/about-form-21p-0969?_format=static_html \[requires Drupal login].
1. Scroll down to **Related forms and instructions**, **VA Form 21P-527EZ**, and observe that the text description does not match the [copy-doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-content-docs/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx) pg. 27.

**CMS QA-env. screenshot**:

<img width="603" alt="FFD-copy-bug-21p-0969" src="https://user-images.githubusercontent.com/587583/91113660-f3bd9100-e63a-11ea-80d9-70a940c8539c.png">

## Desired copy
**[Copy-doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-content-docs/form-detail-lp-coydeck-consolidated-RH-DT-JL-060220.docx) pg. 27 screenshot**:

![FFD-copy-spec-21p-0969](https://user-images.githubusercontent.com/587583/91113684-ffa95300-e63a-11ea-8d0e-4973d604d376.png)

## Acceptance Criteria
- [ ] \[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by MickinSahni** [comment]
@RLHecht @lunascoop can you validate / update if needed?

**Comment by RLHecht** [comment]
The text attached to the related forms is auto-populated and pulls from the When to use copy. It looks like this may be an error in the Word doc for that instance and is currently showing correctly. CC @jenniferlee-dsva

**Comment by MickinSahni** [comment]
What's in the QA env is consistent with other forms so likely an issue with the copy in the doc. 
@jenniferlee-dsva to confirm offline and then close or comment.

**Comment by jenniferlee-dsva** [comment]
Randi is correct - what you see in Drupal is correct - prepopulated text - so this isn't a real bug.
