### ISSUE TITLE
Re-Consider providing end-user confirmation code for trouble shooting with CAMRA/CSC

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#12782]
**Beta-Test Action Item**:
Paul mentioned that it would be good to provide end-user with some confirmation code for troubleshooting successful submissions.

**Comment by hdjustice** [comment]
Closing - This ticket has not been addressed in over a year, and there are no initiatives linked.  Any new work will have new tickets created.
