### ISSUE TITLE
[DESIGN]: GIBCT® - Consider revising See Results button placement at mobile size

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1278]
## Description

The active (focused) element is sometimes hidden by the See Results button when I am zoomed in to 400% using the browser's built-in zoom feature. This could also be an issue on mobile devices depending on how users navigate through forms. I considered it worth raising as an exploratory ticket. Screenshot attached below.

/cc @rtwell for design guidance.

## Screenshots or Trace Logs

![Screen Shot 2019-08-23 at 12 56 05 PM (3)](https://user-images.githubusercontent.com/934879/63613240-eb54f500-c5a5-11e9-8845-4096fb8ab0c4.png)

**Comment by hughes-dustin** [comment]
branch: bah-1278
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11588

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging

**Comment by desireeturner** [comment]
@1Copenut This issue is ready to be reviewed on staging.

**Comment by 1Copenut** [comment]
@desireeturner This looks good. Moving to close.
