### ISSUE TITLE
[Tier 3] User Profile

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#12786]
**Issue Description:** User is having multiple issues with his profile.

**Total Number of Issues:**1

**Issue Number and User Description:**

Issue #1: My Profile Information in the VA.gov website is not displaying
my personal information. This means the information is empty and I can not
view this information. This issue is critical and should be addressed
first. Please see PDF attached: VA Complaint Issue 1.
Issue #1 items missing: Mailing Address, Home Address, Home Phone Number,
Mobile Phone Number, Work Phone Number, Fax Number, and Email Address.

Issue #2: VA.gov will not allow me to update any of this information.
Please see PDF attached: VA Complaint Issue 2.
Issue #2 Error Message A: We are unable to update your information.
Issue #2 Error Message B: We couldn't save your recent mailing address
update. Please try again later.

Issue #3: Since my personal information is missing, VA.gov will not
populate my VA Letters or Documents. Please see PDF attached: VA
Complaint Issue 3.
Issue #3 Error status: VA.gov displaying a thinking / spooling icon and
NEVER displays my VA Letter or Documents.

*Computer Information:* I used FOUR different computers that have the
latest updates installed: 1 Desktop and 3 Laptops.

*Browser Information: * I have used FOUR different browsers that have the
latest updates installed: IE, Chrome, Safari on MacBook Pro, and Mozilla.

*Logon types:* I have used THREE Login methods: DS Logon, MyHealthEVet,
and ID.me. ALL these logins are up to date and work on all other websites
when used.

*Closing remarks:* This issue can not be computer or browser related after
reviewing the above information. My Profile information in the VA.gov
website is not displaying (e.g., missing). This has been going on for
months with no resolve.

An Unsatisfied Veteran,

**Comment by Samara-Strauss** [comment]
I am 99% sure this is the issue where the user has multiple identities at the VA so the backend system isn't able to verify him. I am basing this on his profile not loading coupled with the Letters tool not working. This is exactly what was reported to us back in May. 

Unfortunately, there is nothing we can do about this because we don't manage identity at the VA. Even our identity team can't do anything — this is an issue with either the health care side of the house or maybe even DoD. He is going to have to get that resolved before the website will work. This is what I sent to the last veteran with this issue:

> In terms of getting this resolved, I only have semi-helpful advice. We don’t know exactly where the duplicate ID is coming from, but it may be coming from one of these two places:
> 
> **This may be related to your MyHealtheVet information**
> 
> You can call 877-327-0022 Monday - Friday, 8:00 a.m.- 8:00 p.m. ET. Tell the representative that you tried to sign in to VA.gov, but you’re having trouble because we have more than one ID for you, but you don’t know which kind. Ask if they can look into whether you have more than one MyHealtheVet account or more than one ICN (that’s a fancy abbreviation for an ID that the VA health system uses for you).
> 
> **This may be related to Department of Defense (DoD) information**
> 
> If the MyHealtheVet folks don’t see any duplicate IDs for you, this might be a problem with the VA having more than one DoD ID for you. You can fill out this form and tell them you think you have multiple IDs associated with your identity.
> 
> I am hoping this will move us closer to getting this resolved! I am so sorry this process has been so complicated. I know the VA can be a really tough place sometimes. I am hoping we can get this resolved so you can get into VA.gov and manage your account.
> 
>

**Comment by Kimberley2019** [comment]
@Samara-Strauss I have passed this information along to the user.  Hopefully this will be helpful to him.  This ticket will now be closed out.
