### ISSUE TITLE
STEM: Update spool file benefit and document types

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12797]
As an EDU team member, I need the spool file to have a valid benefit and document type so that the TIMS system can appropriately process the data entry.

## Assumptions:
1. This work is done behind feature flag #7271.

## Acceptance Criteria:
1. The 7th line of the spool file header is: "STEM1995"
2. The 10th line of the spool file header is: "CH33"

## Supporting Artifact:
1. [10203_Spool_20200825_with_call_notes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5125385/10203_Spool_20200825_with_call_notes.docx)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4781

**Comment by delli-gatti-michael** [comment]
Confirmed in Staging
[Spool File](https://app.zenhub.com/files/133843125/414804f7-00af-4694-b3fa-baacd75692b4/download)

**Comment by delli-gatti-michael** [comment]
Tested by TestRail test case
https://dsvavsp.testrail.io/index.php?/tests/view/11964&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
Awaiting confirmation by EDU before closing

**Comment by delli-gatti-michael** [comment]
Changes confirmed by EDU. Closing this issue
