### ISSUE TITLE
Access for Joseph Elder

### ISSUE THREAD

**Issue by elder-joseph** [department-of-veterans-affairs/va.gov-team#12791]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Doris Lin
- Please provide your name.
   > Joseph Elder
- Please Provide your email.
   > joseph.elder@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA.gov Booz Allen Hamilton team

- Requesting SSH key authorization?
   > NO 
   - I already have SSH Key authorization.

- Grant AWS Console access?
  > YES
  -  I am requesting AWS Console Access in order to access spool file data related to the areas of the va.gov site in which our team works.

@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
### For AWS access:
User: Joseph Elder
COR: Doris Lin
Approval needed: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by jsev-io** [comment]
AWS Access Provided and confirmed
