### ISSUE TITLE
STEM: Exit application button going to wrong link

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#12795]
Steps to reproduce:
Navigate to Chapter 3 of https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/benefits/confirm-eligibility. Select the "Exit application" button. It navigates to https://staging.va.gov/education/about-gi-bill-benefits/ and opens in a new tab

##
Expected behavior:

The link should go to https://staging.va.gov/education/ and open in the same tab.

##
![Screen Shot 2020-08-25 at 12.48.36 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/327d173c-e3d5-4e84-b638-99905ef42484)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/14008

**Comment by amyknox** [comment]
@sonntag-adam - Checks out for UX.

**Comment by sonntag-adam** [comment]
closing bug.
