### ISSUE TITLE
STEM: Update Spool File Header Document Type

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12799]
As an EDU team member, I need the spool file to use the new V10203 document type so that the TIMS system can appropriately process the data entry.

## Assumptions:
1. TIMS is configured to receive the new document type as of 2020-09-02.
2. The Feature Flag is configured per environment.
    a. Feature flag for spool header is available in both vets-api repo.
3. When the feature flag is:
     a. Off: The spool header is `STEM1995`
     b. On: The spool header document type is `V10203` as specified in this story.
4. The feature flag is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria:
1. The Feature Flag `stem_document_type` is available to be used for the document type enhancements.
2. The Feature Flag description is: "Set 10203 spool file document type"
3. The 7th line of the spool file header is: "V10203"

## Tasks
1. Follow feature flags documentation to create front-end school ratings feature flag.
2. Follow feature flags documentation to create back-end school ratings feature flag.

## Supporting Artifact:
1. [10203_Spool_20200825_with_TIMS_update.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5125460/10203_Spool_20200825_with_TIMS_update.docx)
2. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/4880
- https://github.com/department-of-veterans-affairs/vets-api/pull/4884

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-14 at 1.29.30 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/98915ad5-c13a-4cb1-99be-6edb47d4668d)
##
On
![Screen Shot 2020-09-14 at 1.29.52 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/74a47eec-70a8-494c-9a1a-dff1a9f20284)
##
Off
![Screen Shot 2020-09-14 at 1.30.09 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2a7242c9-146a-410d-ae1f-ccf402e2119a)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/12531&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
Verified with EDU that the Spool file header is correct. Closing this issue
