### ISSUE TITLE
Better support for read-only data

### ISSUE THREAD

**Issue by short000** [department-of-veterans-affairs/va.gov-team#12798]
### User story
 As a VFS developer, I need to the forms library to direct support read-only data, so that I can avoid inconsistent workarounds involving empty schemas and empty objects.

### Additional details/notes/links
Read-only data is only pseudo supported, with a variety of ways that teams have gotten around this, (empty schemas, empty objects) but a consistent way to deal with this would be good. A good example is read-only demographic information. The current "View-only data" support is view only in the sense that it only appears client side, but still editable. 

Ideally, we should be able to have a read-only data field. The data should be able to be loaded from a data source (API  call), a calculation based on another field, or a static value (I do not that that is as useful).

Currently, teams have used a combo 'view:fieldName', a custom component that is tied to redux, empty schemas and/or hiding the header row on the review page. 

It might look something like 
```
    properties: {
              'claimInfo': {
                type: 'object',
                properties: {
                  claimId: {
                    type: 'string',
                    data:async (formData) => {
                      // load data for text field here
                    }
                  },
                },
              },
            },
```
### Acceptance criteria
TBD

### Point(s) of contact
@mdewey 

### What type of issue is this? 
- [ ] Bug
- [x] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

### How to configure this issue
- [ ] When a ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by Mottie** [comment]
Related to #12769

**Comment by cvalarida** [comment]
What would the form config look like for this read-only data? I agree that the current support is kind of hacky, but I don't have any ideas for alternatives.

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
