### ISSUE TITLE
Better internal component documentation

### ISSUE THREAD

**Issue by short000** [department-of-veterans-affairs/va.gov-team#12801]
### User story
As a VFS developer, I need documentation for internal forms components so that I understand why they exist and how to leverage them.

### Additional details/notes/links
A better insight into the components under the hood. There is good enough docs around the basic big building blocks, but in the code there are several form components that are not documented anywhere, such as "SchemaForm" or "RoutableSavedApp". Understanding why these exist and how they can be leveraged would better communicate the power of the forms system.

Value: quicker turnaround time, less mistakes when trying to reuse and customize the form system. If developers do not know what is available, they have to rely on hearsay, working knowledge, and trial-and-error to figure what can or can't be reused.

Suggestion: Look into automated documentation generation tools for React. Enforce documentation updates when either new Form components are added or used.

### Acceptance criteria
[ ] Identify the set of key undocumented internal forms components that should be documented ???
[ ] Document SchemaForm
[ ] Document RoutableSavedApp
[ ] Document ... TBD ???

### Point(s) of contact
@mdewey

### What type of issue is this? 
- [ ] Bug
- [ ] Request new feature
- [ ] Request update to existing feature
- [x] Documentation change
- [ ] Other (please describe)

### How to configure this issue
- [ ] When ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by meganhkelley** [comment]
@caw310 @cvalarida for awareness

**Comment by taylorkaren** [comment]
[ ] Identify the set of key undocumented internal forms components that should be documented ???: Working on a full list of forms widgets and fields via this ticket: https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/formulate/127
[ ] Document SchemaForm - [current help page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/bypassing-schemaform/); to be updated and moved to new Platform documentation site via ticket https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/formulate/160
[ ] Document RoutableSavedApp
[ ] Document ... TBD ???

**Comment by micahchiang** [comment]
I'm closing this. Documentation for `RoutedSavableApp` isn't essential imo, as user interaction with it is pretty limited to providing a formConfig and currentLocation, both of which are spun up as boilerplate when running `yarn new:app`
