### ISSUE TITLE
Create error messages for clinic configuration issues

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#12809]
We have two scenarios where a user will submit an appointment and an error occurs due to clinic configuration problems that we can't know about in advance (the data is not exposed by the underlying VistA services used by the VAMF services). Currently, we show a generic error message:

![ProhibitAccessUI.PNG](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/2aca0c6c-f59a-41d1-8af3-2aed351bcc63)

This is misleading to users because waiting a day won't help them, they would need to contact the facility and schedule the appointment over the phone. Or in theory they could go back to the clinic page and choose a different clinic.

The two scenarios are:

- The date chosen for the user is past the max allowed days in the future set by the clinic. We don't know any information about the actual days in the future that are allowed, just that user exceeded them
- The clinic chosen by the user doesn't have a proxy user associated with it and no patient scheduling can be done. We also see this for canceling appointments. There's not really any meaningful info to tell the user about why this is a problem.

**Comment by peggygannon** [comment]
Hello, @lenaecb and @jbalboni I have a few questions about this: 

-- is this for a direct schedule appt or an appt "request"? 
-- Is the goal of this message to cover both of the scenarios listed above? or do we need 2 separate messages?

**Comment by jbalboni** [comment]
@peggygannon This is for direct schedule only.

I'll let @lenaecb answer the other question, but we do have the ability to show two different messages if that's desired.

**Comment by peggygannon** [comment]
Ok, thank you. @jbalboni Here are some recommendations for scenario 1 and 2

cc @lenaecb Let me know what you think!

Scenario 1: request is too far out in future: 

**We couldn't schedule this appointment**
We’re sorry. Something went wrong when we tried to submit your appointment. Please start over and choose an earlier date or call your local VA medical center to schedule this appointment.  

{medical center name}
{medical center address}
{medical center phone}

-------


Scenario 2: no way for patient to schedule

**We couldn't schedule this appointment** 
We’re sorry. Something went wrong when we tried to submit your appointment. You’ll need to call your local VA medical center to schedule this appointment. 
 
{medical center name}
{medical center address}
{medical center phone}

**Comment by lenaecb** [comment]
Thanks @peggygannon 

@jbalboni - for #1 - there is no way for us to get a general idea, on avg, about how far in the future patients can typically book even if we can't get that specific information back form the system? I think that if we can't give them something more specific than 'choose an earlier date' then they could be going back and forth multiple times to try and find a date in the unknown range. 

If that's the case, I would just direct both #1 and #2 to call their facility.

**Comment by jbalboni** [comment]
@lenaecb Not that I know of. When that error happens, the site has chosen to arbitrarily set the max scheduling date to something less than 395 days and I don't think we have any insight as to why.
