### ISSUE TITLE
Form Content Management

### ISSUE THREAD

**Issue by short000** [department-of-veterans-affairs/va.gov-team#12804]
### User story
As a non-technical person, I want to be able to change content on the form (content limited to wording of the question) so that I can quickly make updates to the content without involving development resources.

### Additional details/notes/links
A way to config forms content that does not require a developer. The idea is that it shouldn't take a developer to update the content that is on a form. 

Value: it reduces time and resources for changes to happen in the form. As well let developers work on more, non-trivial problems.

Impact if not done: developers are heavily involved with minor updates to the form and non-technical folks have to wait till a developer gets to it.

Stretch goal: make the entire form loadable from a JSON object so it can stored, modified and managed by some other system. 

Suggestion: give the option to load the form data from either a headless CMS or some sort of API. the biggest hurdle here would be the functionality that is baked into the form.js as functions. These would need to be abstracted in a more declarative based approached. 

### Acceptance criteria
TBD

### Point(s) of contact
@mdewey 

### What type of issue is this? 
- [ ] Bug
- [x] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

### How to configure this issue
- [ ] When ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by meganhkelley** [comment]
@cvalarida @caw310 I believe this is something y'all discussed a couple months ago; feel free to consolidate this if you have another relvant ticket.

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
