### ISSUE TITLE
Spool File Routing: Files being routed to St. Louis on 08/24

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#12818]
## What happened?
Shay Norton-Leonard from the Buffalo EDU team sent @WillMcCormack the following information regarding spool file routing for routing that took place on 08/24/20:
   12:08 PM] Norton-Leonard, Shay, VBAVACO
   Will - I also was looking to see if the spool file has been processed and see that yesterday 8/24 there was a spool file created for RPO 
331 (St. Louis). There has no been one for a while... since July. 
   [12:09 PM] Norton-Leonard, Shay, VBAVACO
   The TIMS team is running all 331 files in 307, but I found it a little odd that one was created at all. Not sure if it is related to testing or not.
   [12:18 PM] Norton-Leonard, Shay, VBAVACO
   And... it did not just have one or 2 claims, but 303.

Shay also checked the file and did not see any duplicate submissions

After some investigation, @shawkey-daniel found that this happened: 
   For the spool file... We had moved all of the central states to eastern. Somehow those ended up back in central. The routing should still work, because we removed central from a possibility, but I think we need a defect to move those central states to the eastern array.

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
Logic for routing is in https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/education_form/education_facility.rb

Only Buffalo and Muskogee should be getting spool files
- If the state is in values below then it is routed to Muskogee otherwise it is routed to Buffalo: AK AL AR AZ CA FL GA HI ID LA MS NM NV OK OR SC TX UT WA  GU PR AP
- Except for these special cases: 
  - Muskogee if 0993 or country is PHL
  - Buffalo if 0994, 1995s, or 10203

## Acceptance Criteria
- [ ] The source of the routing to St. Louis has been identified and confirmed that it no longer occurs.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4786

**Comment by delli-gatti-michael** [comment]
Submitting using a user in Colorado (previously a Central state) routes to Buffalo

![Screen Shot 2020-08-27 at 11.29.19 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/51d8bc69-3397-4eca-a36f-42b0889fff75)

**Comment by delli-gatti-michael** [comment]
Confirmed with EDU that this is no longer an issue. Closing this defect.
