### ISSUE TITLE
anyOf should trigger custom error message

### ISSUE THREAD

**Issue by short000** [department-of-veterans-affairs/va.gov-team#12812]
### User story
As a VSF developer, I need errors on _anyOf_ to trigger the custom error message (similar to other validation definitions), so that I can directly handle _anyOf_ errors.

### Additional details/notes/links

Workaround: combine patterns using "or" in our regex; however, it's less straightforward to do that. More importantly, that worked for our specific case for that situation, but it may not in other cases.
https://dsva.slack.com/archives/C5HP4GN3F/p1594644702163400

### Acceptance criteria
- [ ] An error causes _anyOf_ to trigger a custom error message

### Point(s) of contact
@LinnJS 

### What type of issue is this? 
- [x] Bug
- [ ] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

### How to configure this issue
- [ ] When ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by meganhkelley** [comment]
@caw310 @cvalarida for awareness

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new request.
