### ISSUE TITLE
CT Site Search: Update Free Text Search of City Data Behavior

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12810]
As a developer, I need to update the free text search functionality to include cities with a better match algorithm so that the search results return better behavior.

## Assumptions:
1. This work is completed behind the feature flag #10615.
2. An auto-complete match bypasses fuzzy search.

## Acceptance Criteria
1. When comparing the search value against the city data, only exact city matches are returned in the search results.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/710/

Changes made in this PR will make it so that exact matches to alias, city, and institution are correctly sorted to the top

When testing use cases that should work as one would think
1. exact matches to alias
1. exact matches to institution name
1. exact matches to city
1. exact matches to facility code
1. partial matches to institution name

**Comment by zurbergram** [comment]
Sorting was changed to create a 0.0 to 1.0 value for relevant columns to allow for a "weighted value" to be created by adding all criteria together and having those with largest "weighted value" be sorted to the top

The sum of the following determines a rows weight
- `CASE WHEN UPPER(ialias) LIKE :upper_contains_term THEN 1 ELSE 0 END`
- `CASE WHEN UPPER(ialias) = :upper_search_term THEN 1 ELSE 0 END`
- `SIMILARITY(city, :search_term)`
- `SIMILARITY(institution, :search_term)` 
- `(COALESCE(gibill, 0)/CAST(:max_gibill as FLOAT))`

Variables/functions
- `:search_term` is a user provided value
- `:upper_contains_term` is `:search_term` wrapped in LIKE operators
- `:upper_search_term` is `:search_term` in all upper case
- `:max_gibill` is the max gibill value from all non VET TEC approved institutions
- `SIMILARITY` returns a value between 0.0 and 1.0 based on how close the `:search_term` is too the column's value
- `COALESCE` uses gibill value or 0 if none

After sorting by the "weighted value" results are ordered by institution name

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/712

**Comment by delli-gatti-michael** [comment]
Test Case:
https://dsvavsp.testrail.io/index.php?/tests/view/12038&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by delli-gatti-michael** [comment]
Closing this issue
