### ISSUE TITLE
[Design] Show different error alert text when we cannot connect to MPI

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#12817]
Currently if we are unable to connect to MPI/MVI, when we show the Profile we treat the user as though they aren't even in MPI, when the reality is we can't even tell if they are or not.

If we cannot even connect to MPI, I think we should:
- still block users from most Profile sections, as though they are not in MPI
- show an error alert, like we do if they aren't in MPI, but modify the text to make it clear that the issue is we couldn't connect to MPI, _not_ that we couldn't find them in MPI

For reference, this is the error we are showing in either case:

![image](https://user-images.githubusercontent.com/20728956/91222904-b1e12900-e6d4-11ea-9f84-89340769e138.png)

More background in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12727)

## Tasks
- [ ] Change error alert content to be more accurate

**Comment by tressaellen** [comment]
Hey @peggygannon, I took a stab at this, BUT... 

![Screen Shot 2020-09-17 at 3.27.43 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/b399008a-29bc-4b6c-a4ff-a7dd978b0b7b)

...I'm wondering if it's worth it try to adapt the original message, or should we just use the original 'we can't load this page, please refresh' messaging. @erikphansen what are your thoughts?

![Screen Shot 2020-09-17 at 3.26.51 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/d0dea72a-d088-47aa-9cff-0ccdfc84e12f)

**Comment by erikphansen** [comment]
Hmm I think the most important part is the "something went wrong on our end" to make it clear there was an error. But that's my only opinion as far as this goes.

**Comment by tressaellen** [comment]
Okay sounds good. Well then in that case, let's plan on something like this messaging, with whatever recommendations from @peggygannon 

We can’t connect to your Veteran records

We’re sorry. Something went wrong on our end and we can’t give you access to health and benefit tools until we can connect to your Veteran records.
Please refresh this page to try again.

![Screen Shot 2020-09-17 at 3.27.43 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/81e76757-7c17-40d7-9da3-62091ecf67d3)

**Comment by peggygannon** [comment]
hello, @tressaellen @erikphansen a couple of questions for ya:

1. is the Veteran trying to get access to health tools (as message says in the screenshot? ) or are they trying to access their military info? 

2. Will having the user refresh fix this issue of *not connecting to MPI* 

3. Is the current message for *couldn't find them in MPI* the one in the very first screenshot at top of this issue?

**Comment by erikphansen** [comment]
1. In this case they aren't trying to access health tools, just their Profile and account, which doesn't have health tools.
2. Yes, a refresh could fix the issue.
3. Yes, that screenshot in the original message is what we show people if they aren't in MPI/MVI

To reword the ask:
- We correctly handle the situation where we CAN connect to MPI but the user does not exist in MPI.
- We should have clearer messaging when we CAN'T even connect to MPI.

**Comment by peggygannon** [comment]
Hello, OK, thank you @erikphansen 

@tressaellen Here are recommendations for these messages. I've updated the one for "can't find them in MPI" slightly b/c  the one above talks about health tools. Please use the one below for Profile. 

Let me know what you both think. 

User not in MPI:
**We can’t match your information to our Veteran records**
We’re sorry. We can’t give you access to your profile or account information until we can match your information and verify your identity. 
If you’d like to access these tools, please contact the VA.gov help desk at 844-698-2311 (TTY: 711) to verify and update your records. 

------

Can't connect to MPI
**We can’t access your Veteran records**
We’re sorry. Something went wrong when we tried to connect to your Veteran records. Please refresh this page to try again.

**Comment by tressaellen** [comment]
@peggygannon thanks so much!
