### ISSUE TITLE
Vet Center Synthesis

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#12819]
## Issue description
The Facilities team conducted interviews with representative Vet Center Outreach specialists during Sprint 28 with the following goals: 

- To understand the role of a Vet Center's outreach coordinator
- To understand the typical "clients" (Veterans, active service members/loved ones) served at Vet Centers and the services those clients typically receive
- To develop the personas we will use going forward

## Tasks
Synthesize findings from interviews with outreach specialists and Vet Centers Brand Analysis Report_03272020

## Acceptance Criteria

- [x] Documentation of findings
- [x] Recommendation for next steps

**Comment by lildziner** [comment]
[Link to findings and recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/discovery/outreach-specialist-interviews/research-findings.md)
