### ISSUE TITLE
[Development] BDD: Update Separation Location Hardcoded Values to Production API Values

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12813]
## Issue Description
As a short term fix for BDD testing, we are going to update the hardcoded values to match those in the prod API call.

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/content/separationLocations.js

The final fix is #12792. This will break staging BDD submissions since now staging won't match prod.

## Acceptance Criteria
- [ ] BDD is working!
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
will validate after deploy today
