### ISSUE TITLE
Further Unauthenicated Research 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#12820]
After review of [this doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/auth-vs-unauthed.md) for #12291, more research is needed once more use cases for unauthenticated experience is needed 

## Notes for unauthenticated experience
- How can we trust that who is filling out the form is the patient
- What systems can we write to if the user is not verified  ( PGD, etc)

**Comment by julieadair1** [comment]
@mdewey - is this something we still need? 
cc: @jparker0425

**Comment by julieadair1** [comment]
Per @mdewey  this can be closed.
