### ISSUE TITLE
Redirect Request: Disability & BDD related pages

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#12825]
**Instructions**
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

These redirects are related to the launch of the capability to file a BDD claim on va.gov rather than eBenefits.  There are 2 groups of changes happening to content within disability with this launch 
1) we are bringing pre-discharge/BDD content up in the IA for more visibility, new labeling to coincide with SEO, and prepare for future content strategy work within this area  
2) we are retiring 2 legacy pages that include old information on filing claims on eBenefits. 

### Requestor team info
*Indicate what team and who the primary contact on that team is*
Benefits & Memorials 1 team - @luke-gcio 

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : These redirects can happen independent of the BDD launch and at any time the content is ready to go.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
/disability/how-to-file-claim/when-to-file/pre-discharge-claim/	|  /disability/how-to-file-claim/benefits-delivery-at-discharge/
/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/  |  /disability/how-to-file-claim/benefits-delivery-at-discharge/file-while-overseas
https://www.benefits.va.gov/FDC/walkthrough.asp  |  /disability/how-to-file-claim/evidence-needed/fully-developed-claims/
https://www.benefits.va.gov/FDC/checklist.asp  |  /disability/how-to-file-claim/evidence-needed/fully-developed-claims/

Update the following redirects
Legacy URL  |  Updated redirect to
---  |  ---
www.vets.gov/disability-benefits/apply/claim-types/predischarge-claim/ |  /disability/how-to-file-claim/benefits-delivery-at-discharge/
www.benefits.va.gov/predischarge/claims-pre-discharge-benefits-delivery-at-discharge.asp |  /disability/how-to-file-claim/benefits-delivery-at-discharge/
www.benefits.va.gov/predischarge/index.asp |  /disability/how-to-file-claim/benefits-delivery-at-discharge/
www.vets.gov/disability-benefits/apply/claim-types/predischarge-claim/overseas/ |  /disability/how-to-file-claim/benefits-delivery-at-discharge/file-while-overseas
www.benefits.va.gov/predischarge/claims-pre-discharge-overseas-intake-sites.asp |  /disability/how-to-file-claim/benefits-delivery-at-discharge/file-while-overseas

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
These redirects can be implemented independently from the launch of the BDD capability in the 526.  

The 2 legacy pages are no longer relevant now that minimal to no disability claims will be filed from eBenefits, but stakeholders should be notified that we are retiring and redirecting them. 

The 2 Drupal pages can be redirected once we have the ok on the H1 change to reference the BDD program and we know the URL is aligned. 

FYSA: @kevinstachura @chrvalla @DanielleThierryUSDSVA @bethpotts

**Comment by mnorthuis** [comment]
@bethpottsVADEPO We should revisit this one, it might have gotten lost in the shuffle...the links are still up in the left nav, so maybe some work was put on hold?
https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/

**Comment by bethpottsVADEPO** [comment]
@lunascoop Did you initiate any stakeholder notification about these redirects? I'm not sure why this would have paused. Do you?

**Comment by lunascoop** [comment]
@bethpottsVADEPO I didn't send out any stakeholder notification for these redirects. And I can't recall everything exactly involving the BDD and 526 launch because it's been a long time since I was a part of the discussion. But I think I was told to hold off on everything since some things weren't quite finalized. 

@mnorthuis Is it just the pages below that should be redirected and removed from the left nav because the redirect destinations for the other pages aren't live yet?

- https://www.benefits.va.gov/FDC/walkthrough.asp
- https://www.benefits.va.gov/FDC/checklist.asp

**Comment by mnorthuis** [comment]
Maybe @DanielleThierryUSDSVA has some insight on this?  I don't know why the work was stopped.

**Comment by DanielleThierryUSDSVA** [comment]
@mnorthuis I'm going to throw some time on our calendars to sync back up on this.

**Comment by mnorthuis** [comment]
These redirects were part of 2 efforts the launch of BDD within the 526 and some rewriting and reorganizing of content within disability. I believe this work is still relevant - the BDD has launched, and I don't believe the FDC is relevant any longer.  

@DanielleThierryUSDSVA thoughts?

- Here is the IA/content strategy ticket: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/gh/department-of-veterans-affairs/va.gov-team/10896
- IA design: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-benefits-at-discharge.md
- Separate issue created for redirect of two FDC pages: https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/28377

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA @mnorthuis Just checking to determine if I can close this ticket. Thanks in advance!

**Comment by mnorthuis** [comment]
The work described above will be affected by the content placement criteria and the streamlining the benefit hub work, so it is no longer valid.  

The 2 legacy FDC pages can still be redirected, but those are handled in a [separate issue](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/28377) that we will follow up on. 

Closing this ticket.
