### ISSUE TITLE
VAOSR - Scaling Communications & product static site

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#12836]
**Problem:** We have a large stakeholder group for VAOS. We also need a way to scale communication to that group without overburdening our day to day. 

**Idea:** Improve broadcast communication of VAOSR efforts while also maintaining a running documentation for that information that is easily accessible to users not familiar with Github. 

**Solution options:**
- Github page + Jekyll
- Emails and Sharepoint page
- Github wiki

**Comment by mchelen-gov** [comment]
Option details:

1. Markdown files in va.gov-team project dir
    - Location: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling
    - Note: could create subdir such as `/docs` for user-facing documentation

1. Github pages: va.gov-team repo
   - Location: https://department-of-veterans-affairs.github.io/va.gov-team/
   - Source: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/docs

1. Github pages: new repo
    - Location: https://department-of-veterans-affairs.github.io/example-name/
    - Source: https://github.com/department-of-veterans-affairs/example-name/

1. Github wiki: va.gov-team repo
   - https://github.com/department-of-veterans-affairs/va.gov-team/wiki

**Comment by mchelen-gov** [comment]
From email:

> The intended audience is: various stakeholders within the offices of - Community Care, Connected Care, Telehealth, Veteran Access to Care, etc. 

@lenaecb does any of the documentation needed by these stakeholders need restricted access, or is ok to be public?

**Comment by mchelen-gov** [comment]
As a first step, how about creating markdown files in a `/docs` dir like https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/docs ?

It would be straightforward to move them later if any of those other approaches get confirmed.
