### ISSUE TITLE
[Bug] SSO-Cerner Health Page Updates - Unauthd - Appointments - Copy mismatches

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12848]
## What happened?
On Staging, **[Cerner Health, Appointments](https://staging.va.gov/cerner-staging/appointments/)** page \[unauthenticated], **How can the VA appointments tool help me manage my care?** section, copy did not match provided copy-spec.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]

## Steps to Reproduce
1. Go to https://staging.va.gov/cerner-staging/appointments/ -- do not sign in.
1. Under **How can the VA appointments tool help me manage my care?**, observe that there are mentions of community care that are not in the provided copy-spec screenshot.

**Staging screenshot**:

![SSoC-copy-bug-unauthd-appts](https://user-images.githubusercontent.com/587583/91258927-55a4f600-e722-11ea-942c-6a4610c0ffdf.png)

## Desired copy

**copy-spec screenshot** from [TestRail Test Case](https://dsvavsp.testrail.io/index.php?/cases/view/784&group_by=cases:section_id&group_order=asc&group_id=162):

Also, in 1st bullet-item, if Product Team deems there's a significant difference between "health appointments" and "medical appointments", change to "medical appointments" as spec'ed below.
![SSoC-copy-spec-unauthd-appts](https://user-images.githubusercontent.com/587583/91258606-9b14f380-e721-11ea-868c-89a48b59925c.png)

## Acceptance Criteria
- [ ] \[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Hi @tlei123. Confirming that this is okay as is. We've added community care recently. We're good to close this. Thank you!

FYSA @MickinSahni @brianalloyd
