### ISSUE TITLE
[Design] Conduct UAT

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12859]
## Background
We are conducting UAT for Profile 2.0

[UAT Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)

## Tasks
- [x] Conduct UAT
- [x] Document any issues that come out of UAT

**Comment by tressaellen** [comment]
All issues have been documented in [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/UAT/Profile%202.0%20Research%20Findings.md).

None of these are launch blockers.
