### ISSUE TITLE
[Bug] SSO-Cerner Health Page Updates - Unauth'd - Messaging - Copy mismatches

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12852]
## What happened?
On Staging **[Cerner Health, Messaging](https://staging.va.gov/cerner-staging/messaging/)** page \[unathenticated], copy did not match provided copy-specs.

## Specs:
- Device: \[device-agonstic]
- Browser: \[browser-agnostic]

## Steps to Reproduce
1. Go to https://staging.va.gov/cerner-staging/messaging/ -- do not sign in.
1. Observe the following copy mismatches
    - Immediately below **page-title**, spec'ed 1st paragraph is missing.
    - **How does Secure Message work...** section-title & 1st paragraph do not match provided copy-spec.

### Staging screenshots

**Missing paragraph under page-title**:
![SsoC-copy-bug-unauthd-msg](https://user-images.githubusercontent.com/587583/91268488-49bd3200-e72a-11ea-9c85-9b0d0d185191.png)

**How does Secure Messaging work...**:
![SsoC-copy-bug-unauthd-msg-2](https://user-images.githubusercontent.com/587583/91269678-5d699800-e72c-11ea-9e82-e40ef04bd3aa.png)

### Copy-spec screenshots from [TestRail Test Case](https://dsvavsp.testrail.io/index.php?/cases/view/781&group_by=cases:section_id&group_id=162&group_order=asc)

**Paragraph under page-title - \[copy-spec]**:

(https://dsvavsp.testrail.io/index.php?/cases/view/781&group_by=cases:section_id&group_id=162&group_order=asc):
There should be a paragraph between page-title and sign-in alert, as spec'ed.
![ScoC-copy-spec-unauthd-msg](https://user-images.githubusercontent.com/587583/91268508-52ae0380-e72a-11ea-8f78-960dbfc347d0.png)

**How does Secure Messaging work... - \[copy-spec]**:

![SsoC-copy-spec-unauthd-msg-2](https://user-images.githubusercontent.com/587583/91269736-72462b80-e72c-11ea-8a4c-f5ac28073160.png)

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Confirming that question in staging is now correct and matches final copy:

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/573d034c-ce5b-4f20-8238-570831259a72)

First paragraph is missing because it's housed in Drupal.
