### ISSUE TITLE
Fix tab GA events

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#12853]
## Description
Created this ticket based on @bsmartin-ep's comment on a different ticket.

> 1. I noticed the `tab-click` event (for the first tab) is automatically firing on page load.  Any way to restrict that to just user tab clicks?

> 2.  I'm feeling a little queasy about attaching _number of cards_ to a navigation event.  Is this a dimension more associated with an API call rather than a navigation / tab event in your opinion?

_Originally posted by @bsmartin-ep in https://github.com/department-of-veterans-affairs/va.gov-team/issues/10662#issuecomment-680229012_

**Comment by narin** [comment]
@bsmartin-ep This code was merged to master late last week and I've verified that the API events (`vaos-get-future-appointments-started` etc.) are firing.  Could you please verify that the number of cards dimensions are also being passed?  I'm not sure the best way to get to these in GA.

**Comment by bmcgrady-ep** [comment]
### DL Change QA
Description of Test Scenario | DL Screenshot | GTM Tag Screenshot | Test Status
-- | -- | -- | --
`vaos-get-pending-appointments-retrieved` | ![image](https://user-images.githubusercontent.com/66263904/92527217-87669400-f1db-11ea-9c9b-1195bb11350b.png) | ![image](https://user-images.githubusercontent.com/66263904/92527319-aa914380-f1db-11ea-9551-66e1a095af14.png) | ✔️ PASS
`vaos-get-future-appointments-retrieved` | ![image](https://user-images.githubusercontent.com/66263904/92527435-d90f1e80-f1db-11ea-9325-1bd8ee0bb8dd.png) | ![image](https://user-images.githubusercontent.com/66263904/92527480-edebb200-f1db-11ea-848f-fbea0163e68a.png) | ✔️ PASS

**Comment by bmcgrady-ep** [comment]
Published latest GTM changes to production.
