### ISSUE TITLE
[Design] Discuss a plan for design iterations/explorations

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12861]
## Background
Now that we have done the initial discovery work and put together the uses cases, we can start to work on some initial design iterations/explorations.

## Tasks
- [x] Create plan for design exploration and iteration
- [x] Review with Samara/Matt

**Comment by Samara-Strauss** [comment]
Let's get a meeting on the calendar to start discussing this for either this Friday, 8/28, or Monday, 8/31.

**Comment by mshea0606** [comment]
@Samara-Strauss Just put some time on for Monday, 8/31 at 2:30-3pm ET.

**Comment by Samara-Strauss** [comment]
Closing this. I changed the goal of this ticket to just creating the plan for the homepage iterations. We can start the actual explorations next sprint.

Plan is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md
