### ISSUE TITLE
[Design] Track the documentation from the LOA3/LOA1 use case/data point exercise in Github

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12862]
## Background
It would be very helpful to have the documentation from the LOA1/LOA3 use cases exercise in Github. This would make it easier to find and accessible to a larger number of people. 

## Tasks
 - [ ] Track documentation from LOA1/LOA3 use cases exercise in Git Hub

**Comment by tressaellen** [comment]
All LIH assets will be kept in [this folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/lih-assets)
