### ISSUE TITLE
Prevent DD fraud phone numbers from wrapping across lines

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#1286]
It should be possible to prevent phone numbers from having line breaks inserted in the middle if they are wrapped in this helper class (or if that class isn't available in this app, make a similar class) https://github.com/department-of-veterans-affairs/vets-website/blob/8d80af4a05efc4cf89c3f41785cf17be687f97a3/src/platform/forms/sass/_m-schemaform.scss#L292-L297

![Screen Shot 2019-08-23 at 9.54.46 AM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/eee5daf1-7951-4def-8376-d83e21ed3640)
![Screen Shot 2019-08-23 at 1.34.29 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/14ed3f6b-0976-464f-a2c9-f1af9fa282b1)

**Comment by Justin-Pickett** [comment]
@erikphansen currently working through item. Will follow up.
