### ISSUE TITLE
Create a Research Plan for CH36/CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12871]
## Goal
We want to put the feature we have worked on in front of real users to ensure that we have provided an improvement over the legacy digital experience.

## Considerations 
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)
- There are several workflows that need to be looked at as well as a few hypotheses that need to be validated.

## Task
- Document a research plan to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/discovery-research-plan.md)):
  - Research method (moderated user interviews)
  - Participants & Recruitment
  - Timeframe
  - Team Availability
  - Roles (include emails)
  - Seek review before implementation
  
## Acceptance Criteria
- [x] Research Plan is ready for review by [Lauren Alexanderson in Recruiting](https://dsva.slack.com/team/U772MC9BQ) ([email](mailto:lauren.alexanderson@va.gov)) and Shawna

**Comment by sporeboy** [comment]
Initial draft of research plan is done pending dates...

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-research-plan.md

**Comment by sporeboy** [comment]
Will need to coordinate dates with UAT schedule.
