### ISSUE TITLE
Setup Central Mail Submission for CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#12877]
## Goal
CH36 uses Central Mail as its submission process, so we need to get that in place for CH36 to operate properly.

## Tasks
- [x] Implement submission process for CH36

## Acceptance Criteria
- [x] CH36 is ready to test its submit process via Central Mail

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4939

**Comment by jason-gcio** [comment]
@steve-gov is going to connect @digitaldrk with some folks to help validate this
