### ISSUE TITLE
[Design] Claims Status: Allow the Notification Letter to be accessed once the package has been sent via US Mail

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12874]
## Issue Description
This is coming from NCC and we had an idea that this would be an update to the existing tool.

It looks like once we get confirmation that the letter has been sent, we would like to allow them to download it or view it (as PDF) within the tool.

This ticket is to figure out where to place the letter in the design of the existing tool.

Some goals:
1. Determine where in the UX and overall CST flow this letter should appear (in the decision details page, assumingly)
2. Determine whether it's just a download link or whether we display it.

## Acceptance Criteria
- [x] Design showing the letter
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
This is a start to this design. A user could click the link below each item to view the decision letter:

https://vsateams.invisionapp.com/share/SWYMSCCJ3ZD#/430475271_Claim_Appeal_Status_-_Claim_Detail

**Comment by kevinstachura** [comment]
Spoke with @luke-gcio and we're still trying to ascertain if we can actually get this data (i.e. if anyone in the process actually uploads the letter digitally). The design is set for now but technical feasibility still remains unanswered.

**Comment by kevinstachura** [comment]
Closing this as the design for this feature has been created. If there are changes needed based upon technical discovery, we can create a new ticket for the design changes.
