### ISSUE TITLE
[FE] [MOBILE DESIGN][508] - Consider abutting mobile subnav to the top of viewport

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#12873]
## Background
See: 508-defect-4 [MOBILE DESIGN] Consider abutting mobile subnav to the top of viewport#11890
Proposed updated design in bottom of the ticket in Tressa's comment
- low priority 508 review ticket

##Specs

Make the top an opaque white so the content isn't visible behind the menu bar. 

![mobile sticky nav copy](https://user-images.githubusercontent.com/58752772/91350839-bcaec300-e793-11ea-842c-07d42d80ef4d.jpg)

## Tasks
- [ ] Make updates to design

**Comment by erikphansen** [comment]
@tressaellen feel free to validate and close this.

**Comment by tressaellen** [comment]
@erikphansen looks good to me! Closing this ticket.
