### ISSUE TITLE
eFolders - MyDocuments Page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#12885]
## High Level User Story/ies
As a Veteran I would like the ability to see the documents that are available to me to view/download in a tabel format with the ability to filter/sort/search 

## Hypothesis or Bet
**Allow veterans to download needed documents 

### As a veteran I am able to see a full list of the documents available to me and be abel to sort, filter, search for specific documents. 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by denisecoveyduc** [comment]
Additional work will be completed as part of #36682
