### ISSUE TITLE
Move VHIE info alert down to VHIE section on page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#1288]
On this page https://www.va.gov/health-care/get-medical-records/ 

@RLHecht - Please fix this content bug in Drupal, and loop in myself or Peggy for review before publishing. @Karak888 for awareness. Thank you! 

## What happened?
This is an old bug hold over from when it migrated into the CMS. There is a blue VHIE/ebenefits info alert at the top of the pg. This is the wrong location for the alert. (When this page migrated, the CMS moved all alerts to the top and couldn't be moved. This CMS bug is fixed now, so we should move this alert.) 

Move the VHIE ebenefits info alert down to the VHIE content section. See screenshots. 

**Move this alert on the page:**
![image](https://user-images.githubusercontent.com/43381063/63660388-27de4780-c784-11e9-821c-e0d686f86526.png)

**To here:**
![image](https://user-images.githubusercontent.com/43381063/63660256-a1296a80-c783-11e9-8bf3-147a0f845323.png)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by RLHecht** [comment]
@jenniferlee-dsva Let me know if you want this to wait until I have my PIV card access and can get into Drupal or if I should pass this to someone else to take care of. Wasn't sure how urgent this was.

**Comment by RLHecht** [comment]
Kevin Walsh moved the alert on the page and I asked Peggy to preview and publish it.

**Comment by RLHecht** [comment]
@peggygannon Now that Drupal preview is working, could you please review this page and set it to publish?

**Comment by Karak888** [comment]
@RLHecht  will follow-up with @peggygannon to see if this can be closed now that Preview is working.

**Comment by Karak888** [comment]
@RLHecht  I am moving this to validate since the work is essentially done.  I'll let you follow up with Peggy and you can let me know status after that.  Thanks!!

**Comment by RLHecht** [comment]
@peggygannon Could you please review this in Drupal and set it to publish if the alert has been moved down to the right spot on the page? Thanks!

**Comment by peggygannon** [comment]
@RLHecht @Karak888 I've reviewed and published. We should wait until after the deploy tomorrow (9/17) to validate on the live site before closing out this issue.

**Comment by RLHecht** [comment]
Validated and closing issue.
