### ISSUE TITLE
CT Filters: Remove scorecard filters from search results

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12884]
As a developer, I need to remove the scorecard filters from the Comparison Tool search results page because they were not found to be useful by the users during usability testing.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The following filters are not available on the Comparison Tool Search Results page:
    a. Gender
    b. Specialized mission
    c. Religious affiliation

## Supporting Artifacts:
1. 
<img width="258" alt="filters" src="https://user-images.githubusercontent.com/48260534/91578713-923a4280-e918-11ea-9286-42d129bef1ea.png">

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14055

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-01 at 10.44.54 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/974f9667-84e4-40c1-8a77-d62f665dd0e5)
##
![Screen Shot 2020-09-01 at 10.45.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/64641037-1069-4a52-a595-b278513d4244)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/12112&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is on Staging and ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam Checks out for UX!

**Comment by sonntag-adam** [comment]
Closing story.
