### ISSUE TITLE
Adding Kristen McConnell to DSVA Slack

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#12882]
Hello! We have a new person starting with the VSA Project. Can you please add her as a full member to the DSVA Slack. Thanks!
Email: kristen.mcconnell@adhocteam.us

**Comment by LizCallaghan** [comment]
it looks like she already has access?

**Comment by YanaRoy** [comment]
Yes, I had not realized that she had it from her previous project. I will close the ticket.
