### ISSUE TITLE
[Design] HLR: Design and Content Wizard Updates

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12891]
## Issue Description
Moving the wizard to the intro page. Same deal as we did for 526.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
The new wizard has been designed and can be found here:

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/430329537_HLR_-_Info_Page_-_New_Wizard

Although it brings up questions about some content items. Such as the different headings throughout (info page says 'higher-level reviews', wizard pages say 'apply for a higher-level review' and the intro page says 'request a higher-level review). I think a chat with Laura and Mikki would help clear this issue up.
