### ISSUE TITLE
Update React doc code samples to use function components

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#12909]
Some of the React docs include [code samples with class components](https://github.com/search?q=%22extends+React.Component%22+repo%3Adepartment-of-veterans-affairs%2Fveteran-facing-services-tools+path%3A%2Fpackages%2Fdocumentation%2Fsrc%2Fpages%2F&type=Code)

These should be updated to use function components instead, in accordance with React best practices.

**Comment by jhonnyoddball** [comment]
Expired. Closing
