### ISSUE TITLE
VSP Content review: IRIS form content-design outline

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#12906]
## User story
Provide content feedback the content/design outline for IRIS form. 

Link to the spec doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/iris/IRIS%20Design%20%2B%20Content%20Specifications.md

**Comment by peggygannon** [comment]
@murrayra Hello, please see attached my content recommendations for the IRIS outline. Let me know if you have any questions about my suggestions or if you want to meet to discuss. thx! 

I put these in Word so you can review, before we update the Github outline. 


[https://app.zenhub.com/files/133843125/77b8e92e-d38c-49a1-84c5-5b70e269b0ba/download](https://app.zenhub.com/files/133843125/77b8e92e-d38c-49a1-84c5-5b70e269b0ba/download)

**Comment by peggygannon** [comment]
@murrayra Do you have any questions about my feedback above? Let me know if you do. If not, I will close this ticket.. thx!

**Comment by murrayra** [comment]
Hi Peggy - no questions, feedback was clear! I'm incorporating your feedback and hope to touch base with you at some point soon on progress we're making on the form.

**Comment by peggygannon** [comment]
ok, thank you for the update.  I will close this ticket then.
