### ISSUE TITLE
[Launch] BDD Post-Launch: Adjusting Flipper

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#12907]
Adjusting flipper (whitelist, 0%+)

This story is to capture the decisions about when/how much to increase the flipper.  This should also include a decision on initial flipper value based on eBennies traffic.

**Comment by luke-gcio** [comment]
Likely to go to 20% sprint 35.

**Comment by luke-gcio** [comment]
We are already doing this, no more need to track this.
