### ISSUE TITLE
BDD Post-Launch: Verify Successful Submission with VBMS

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#12904]
Get with VBMS to verify that the data we submitted is showing up correctly in their systems.

1. During UAT, it should be taken care of live essentially (but just in case we can track it here).
2. During X%-100% rollout phase, make sure we are regularly letting Barry/Paul know and track some submissions to make sure things are looking good (EP codes, establishment of claims, STR uploads).
3. Make sure things are looking good in CST.

**Comment by luke-gcio** [comment]
We have verified a number of these submissions through Barry.  However, we have not yet had a 100% (no manually submitted documents essentially) UAT session yet.  Will close this once we are through one or two full submissions.

**Comment by luke-gcio** [comment]
We may have two UAT candidates!  Will hold open.

**Comment by luke-gcio** [comment]
Reached out to Nancy - she is going to let us know!

**Comment by luke-gcio** [comment]
We are good. We will continue to work this but there is a large email chain with the information about submissions and responses from Barry.
