### ISSUE TITLE
[FE] Logged-in homepage: Investigate what data we have access to for prescriptions on the My VA dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12902]
## Background

Now that we have a staging user (user 377) so we can see prescriptions live in staging, we are realizing that there is a big difference between the original mockup that was done of the "Refill prescriptions" section and what we are actually showing there.

This is the old design mockup:

![Prescription refills on My VA dashboard.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/e701a86c-962e-4c32-b536-dfab532509ef)

And this is a screenshot of what we actually see in staging. 

![Screen Shot 2020-08-18 at 1.33.14 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/60c297c1-9ff2-4c20-8ec4-33059c81188f)

All of the medications have a "filled" date, but we only show the date the meds were submitted. Here is the screenshot to show what this looks like in MHV:

![image004.jpg](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/9039f14e-a41c-4beb-bf24-d951fc7c0572)

What we need — we need to confirm what data we have access to for prescriptions. Specifically, I want to know:

- Are we supposed to be linking to individual prescriptions, and is that functionality broken? Or is it just something that was in a mockup that never got built? Do you see this in the code?
- If we wanted to link to individual prescriptions, could we do that easily?
- Do we have access to the "Fill" date (see MHV screenshot for clarification)? Right now, it looks like we are just surfacing the "submitted" date.
- Is there any "track package" functionality in the code that links out to MHV, and is that broken? Or is this just something that was in a mockup and never got built?
- If there is no "track package" functionality, is there anything we have access to via the API that would allow us to surface something like that?
- Is there other data you see in the code or API that we have access to that we are not surfacing? 

## Tasks

- [ ] Review "Refill prescriptions" My VA code to answer the questions above

**Comment by sanlouise** [comment]
1. **Are we supposed to be linking to individual prescriptions, and is that functionality broken? Or is it just something that was in a mockup that never got built? Do you see this in the code?**
This was never built.

2. **If we wanted to link to individual prescriptions, could we do that easily?**
We are getting a lot of data for each individual prescription. What would we link to exactly? Would this go to an external page/internal page/stay on the same page but we'll surface the information in a modal form or otherwise?

3. **Do we have access to the "Fill" date (see MHV screenshot for clarification)? Right now, it looks like we are just surfacing the "submitted" date.**
Yes, we have access to that date. For a dev reference, this is the 'refill_date' property.

4. **Is there any "track package" functionality in the code that links out to MHV, and is that broken? Or is this just something that was in a mockup and never got built?**
This did not get built yet.

5. **If there is no "track package" functionality, is there anything we have access to via the API that would allow us to surface something like that?**
Yes, we have an API endpoint `/v0/prescriptions/{prescription_id}/trackings` that should provide all needed data.

6. **Is there other data you see in the code or API that we have access to that we are not surfacing?**
You can see all available data here: 

![image](https://user-images.githubusercontent.com/14869324/92153841-1c374f00-ede2-11ea-895c-cedf364f78a1.png)

At first glance, it appears we do not display the Facility Name, Quantity and Station Number per prescription.

**Comment by sanlouise** [comment]
This is a quote from Jeff that might be helpful for context:

My memory of the history of prescriptions on vets/va.gov is that a long time ago we built a full rx refill app and that was eventually removed in favor of having a simplified view on the profile and sending folks to MHV for actually doing anything. I believe Eugene Doan and Kam Karshenas worked on that old rx app (which included building out the apis), but I don’t think they did any work on the profile part.

**Comment by Samara-Strauss** [comment]
> We are getting a lot of data for each individual prescription. What would we link to exactly? Would this go to an external page/internal page/stay on the same page but we'll surface the information in a modal form or otherwise?

So each individual prescription has a page of its own on My HealtheVet, and in theory, we could link each prescription we show on VA.gov to the individual page on MHV. [Here is an example on their staging environment](https://mhv-syst.myhealth.va.gov/mhv-portal-web/refill-prescriptions?p_auth=X49q4lvj&p_p_id=mhvRefillPrescriptionsSummary_WAR_mhvrxrefillportalportlet&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=3&p_p_col_pos=2&_mhvRefillPrescriptionsSummary_WAR_mhvrxrefillportalportlet__facesViewIdRender=%2Fviews%2Frx-refill%2FrefillPrescriptionsSummary.xhtml).

<img width="1280" alt="Screen Shot 2020-09-03 at 5 32 46 PM" src="https://user-images.githubusercontent.com/34068740/92176071-c11a5200-ee0b-11ea-9ffd-346ed72c43a4.png">

You can view this page on My HealtheVet with test user Kristie ([password is here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/reference_documents/MHV/mhv-lower-env-test-accounts.md)). If you try to sign in, do so through the following button on the sign in page:

<img width="631" alt="Screen Shot 2020-09-03 at 5 32 55 PM" src="https://user-images.githubusercontent.com/34068740/92176097-cb3c5080-ee0b-11ea-8c16-6d0aaa62d11e.png">

I guess the question is: do we get this link to the individual prescription page on MHV through our API?

> Yes, we have access to that date. For a dev reference, this is the 'refill_date' property.

Thank you! And to confirm, we are *not* showing that now on the frontend...? All I saw was the "submit" date, not the fill date, so I want to confirm we are indeed not conflating the two in the code and showing the "fill" date but labeling it as the "submit" date.

> Yes, we have an API endpoint /v0/prescriptions/{prescription_id}/trackings that should provide all needed data.

Thank you!

> You can see all available data here:

Got it. Thanks for this!

**Comment by sanlouise** [comment]
Thank you for the background!

> do we get this link to the individual prescription page on MHV through our API?
We do not currently get this link through our API.

> Thank you! And to confirm, we are not showing that now on the frontend...? All I saw was the "submit" date, not the fill date, so I want to confirm we are indeed not conflating the two in the code and showing the "fill" date but labeling it as the "submit" date.

We are conditionally showing that refillDate now. This is how we determine which date to show next to 'You submitted your refill order on':

`const submittedDate = moment(refillSubmitDate || refillDate).startOf('day');`

If we have access to the refillSubmitDate, we show that. If we don't, we currently show the refillDate. I am not sure why the decision was made to make the refillDate the fallback.

**Comment by Samara-Strauss** [comment]
> If we have access to the refillSubmitDate, we show that. If we don't, we currently show the refillDate. I am not sure why the decision was made to make the refillDate the fallback.

This sounds really bad and confusing, because I think it looks like we are showing the refill date sometimes as the submit date. No wonder people are confused.

Going forward, please do not do this. If we have the submit date, we should show it only as the submit date. If we have the refill date, we should only show that as the refill date. Can you make a note of this somewhere?

Otherwise, I think we have the information we need from this. I'm going to close, but please reopen if you feel there's anything that still needs to be done. Thanks for your help @sanlouise!
