### ISSUE TITLE
[Launch] BDD Post-Launch: Review metrics

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#12903]
Review metrics (number of successful entries etc)

1. Make sure our charts are working and we have data coming into Sentry.
2. Run the rake task and look at 526/BDD and make sure nothing (new) weird is happening.
3. Look every day during launch (as we ramp up from X% to 100%)

**Comment by annaswims** [comment]
I'm thinking that most of this will happen in a future sprint, when we're launched. Though a bit will happen with UAT.  I didn't see any BDD grafana metrics for Robin's or my submissions, but I think that's because we had a couple servers running old code as VSP rolled out the new version of redis.

**Comment by luke-gcio** [comment]
https://files.slack.com/files-pri/T03FECE8V-F01J88MUPHQ/bdd_submissions_per_day_2020-12-01_to_2021-01-06.png

[BDD Submissions Log.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5798047/BDD.Submissions.Log.xlsx)
