### ISSUE TITLE
SRE Pager Duty for Warnings (Backend)

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#12912]
*As a user, I should be notified when there might be latency or high number of errors.* 

Currently there is only a mechanism to put up a maintenance window. What we'd like to do is to put up a warning without maintenance. There is a way to pass messages between pager duty and vets-api. We should investigate how to make this happen. We'd still need to get the copy approved though.

1. Do discovery around this pager duty mechanism and how it was used in the past.
2. Either use existing mechanism if possible or create new service to handle it in pager duty.
3. Do any appropriate vets-api related changes to surface these warnings to the FE.
4. Get pre-approval on copy for variety of possible warning messages but could just be one generic one (this could be a separate ticket).
5. Figure out if there is a way to automate these using prometheus data into Pager Duty.

There should be a corresponding FE ticket to check for these possible warning messages and to surface them as needed.

**Comment by ajmagdub** [comment]
From the VA OIT Devops Slack Channel [VA Devops Pagerduty Presentation](https://vaoitdevops.slack.com/files/UP6MYPVC5/F0192HS8C94/dots_training_-_pagerduty__1_.mp4)

**Comment by lenaecb** [comment]
@saneshark - to add AJ and Brad licenses for VA.gov/VSP pagerduty

**Comment by ajmagdub** [comment]
error processing was modified to provide more BE (VAMF) error information to the Back End. Pager Duty hooks are already in the Rails AP. Next step is to come up with a DevOps call response / rotation that can be triggered by Pager Duty.
