### ISSUE TITLE
Access for [individual]

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#12917]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Alexander Garcia
- Please Provide your email.
   > agarcia@clarityinnovates.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Identity Team, Front-end Developer, Oddball

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCgf2YXUMrRabDNCJuvwBu33XgnHD7qPR+2TWqlhS2EM9EH4x8EuBPVi/3d90opOV6/IhiBpy0+Tl2TY9Zl03vHLcY18r7eMw4f3sAZfTvphsaLrShEBfZkzwWC3/MpOHpVUp3lPpEm/adWcn5xVU0gwa9Jz2p8wB8xRx2BfFofASCRgBSpgajC8hTKwIHRcfIjBueI0qLCf0nTLUR2zB4fEDQd2DwtWN5tnLAJS3fTBukfmbApeEKFi87krhVs8bPaeoDcBgcH+sf3K+P08W20YCZYrCltFzVYHketl5mhzOsU0WYG0udhg4uGHgfANbKOna5zivtgOU7aEXsGSsQw7nLoO/wVQIjBUcjXirr+VpGNJzuGKqlqynu32vLmrGHe1oJ8vxMpxBT8u7cajAsPsEEOZqbsswuKSWRrJ9NvY8R281IucfJ2VsAnxTaKPcBqFjpu199lmpCllIGE1V1M49PtVOPr7wPWsRgtrRZzhxpquHKpYonI0DtCmFQ4jME= alexandergarcia@agarcia01.fios-router.home
```

- Grant AWS Console access?
  > NO (I'm going with no for now unless I know otherwise)

**Comment by AGarcia-Clarity** [comment]
@department-of-veterans-affairs/vsp-operations Thank you!

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by AGarcia-Clarity** [comment]
@jbritt1 - I am getting a 404 on Step 1's 'Click this link'.  I don't think I have access to the `devops` repo.

**Comment by jbritt1** [comment]
> @jbritt1 - I am getting a 404 on Step 1's 'Click this link'. I don't think I have access to the `devops` repo.

Roger. Does the identity team have an official GitHub team yet? Have you been added there?

**Comment by jbritt1** [comment]
@ricetj, can you add this user to vets.gov-write in the meantime while he waits for official identity team membership so he can view the devops repository please sir?

**Comment by AGarcia-Clarity** [comment]
> > @jbritt1 - I am getting a 404 on Step 1's 'Click this link'. I don't think I have access to the `devops` repo.
> 
> Roger. Does the identity team have an official GitHub team yet? Have you been added there?

I will ask my team lead but none exist to my knowledge.  Thank you again!

**Comment by jbritt1** [comment]
Roger that, 

> > > @jbritt1 - I am getting a 404 on Step 1's 'Click this link'. I don't think I have access to the `devops` repo.
> > 
> > 
> > Roger. Does the identity team have an official GitHub team yet? Have you been added there?
> 
> I will ask my team lead but none exist to my knowledge. Thank you again!

Roger that, in the meantime I have asked TJ if we can get you on a team that I believe will at least work in interim.
