### ISSUE TITLE
[Support] Create Report to track users of Claims/Benefits tools

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#1291]
## User Story
As a Claims/Appeals stakeholder, I need to track trends of claims users. This is a follow up to story #519. 

## Goal
- Self-service report that pulls users of modernized claims

## Acceptance Criteria
- [ ] Create Google Analytics dashboard or custom report allowing stakeholders to track claims users

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@jenniferlee-dsva Please see two self-service dashboards that teams can access directly within Google Analytics.

The following two reports track users accessing their claims on the Modernized tools over time. To change the dates, please select the upper right corner.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/79a3172b-0595-4992-af2b-55b2326dbc41)

*Reports with Links*
- [Vets.gov Historical Data](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/NXn4uh_FR1qQY-f5m03RvQ/a50123418w107014820p111433053/) - Please note that by default, the report may choose the past 30 days; report users will need to change the timeframe to view pre-web brand consolidation data before November 2018. 
- [VA.gov Modernized Data](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/tWmn_1b5Rb6jdBaHfjCLKQ/a50123418w177519031p184624291/_u.date00=20181101&_u.date01=20190908/)

When logged into Google Analytics under the `WBC - VA.gov Modernized View`, these links can also be accessed from selecting the Dashboards option on the left navigation menu.

**Comment by nedierecel** [comment]
@jenniferlee-dsva Hello! I wanted to check in and see if you had an opportunity to review. Thanks!

**Comment by jenniferlee-dsva** [comment]
Hi Nedie - thank you for following up. I will slack you with a couple questions.
