### ISSUE TITLE
Clarify code linting docs

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#12924]
### What is your documentation request, question, comment, or issue?
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/front-end-standards/manual-reviews

The "ESLint" section of this page is helpful because it covers the basic linting config, mainly as used in the CI server.

However, ESLint is used in at least 3 slightly different places:
1. IDE (`.eslintrc`)
1. Git commit hook
1. CI (Circle + Jenkins)

It would be helpful to include these different cases, and how the lint rules in each case are similar or different.

**Comment by mchelen-gov** [comment]
.cc @chrvalla @jhonnyoddball

**Comment by gmaciolek** [comment]
@mchelen-gov I agree that the docs regarding ESLint are a little confusing. I'm going to put this on our backlog for now as we are focused on BE tools docs this quarter. If @jhonnyoddball has time to look into this in the meantime, he can take over on this ticket.

**Comment by lianilychee** [comment]
Closed; Platform website has info about ESLint.
