### ISSUE TITLE
[Bug] - SSO-Cerner Health Page Updates - Unauth'd - Prescriptions - Copy mismatches

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12928]
## What happened?
On, Staging **[Cerner Health, Prescriptions](https://staging.va.gov/cerner-staging/prescriptions/)** page \[unauthenticated], copy did not match copy-specs.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]

## Steps to Reproduce
1. Go to https://staging.va.gov/cerner-staging/prescriptions/ -- do not sign in.
1. Observe the following copy mismatches:
    A. Immediate below **page-title**, spec'ed 1st paragraph is missing.
    B. Under **How can the VA Prescription Refill and Tracking tool help me with my health care?**, 1st paragraph copy does not match copy-spec.

### Staging screenshots

**A. Below page-title, missing spec'ed 1st paragraph**:
![SsoC-copy-bug-unauthd-prsrptn](https://user-images.githubusercontent.com/587583/91355145-9e03f880-e7a2-11ea-93c8-71a4ab17493a.png)

**B. Under "How can the... tool help me...", 1st paragraph copy mismatch**:
![SsoC-copy-bug-unauthd-prscrptn-2](https://user-images.githubusercontent.com/587583/91354633-de16ab80-e7a1-11ea-99f2-9b66868fda21.png)

## Desired copy - specs from [TestRail Test Case](https://dsvavsp.testrail.io/index.php?/cases/view/782&group_by=cases:section_id&group_order=asc&group_id=162)

**A. Below page-title, spec'ed 1st paragraph**:
![SsoC-copy-spec-unauthd-prscrptn](https://user-images.githubusercontent.com/587583/91353308-eff74f00-e79f-11ea-8860-67a2e5bc556e.png)

**B. Under "How can the... tool help me...", spec'ed 1st paragraph**:
![SsoC-copy-spec-unauthd-prscrptn-2](https://user-images.githubusercontent.com/587583/91354975-58dfc680-e7a2-11ea-9ef6-cc11aba33038.png)

## Acceptance Criteria
- [ ] \[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Confirming unauth content is okay in staging. It makes final copy per below, and first paragraph is missing because it's housed in Drupal.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/9cb122d9-c151-4fa6-a185-7f2be98ea2fe)
