### ISSUE TITLE
[Development] HLR: Wizard Implementation

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12925]
## Issue Description
Once we have the design and content for the new wizard, we will implement it in time for UAT testing.

## Acceptance Criteria
- [ ] Wizard built and approved by designers, etc
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Robin, is Liz working a final design of this?  I am curious where/how the accessibility review would be conducted.

**Comment by Mottie** [comment]
Yes, they are still working on the flow. I'm working on implementing it now, and copying the same pattern as form 526. So once the new flow/design is ready. It'll (hopefully) only need minor updates to match the changes.
