### ISSUE TITLE
Staging review - Dependents claim - IA feedback

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#12920]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This issue describes IA feedback for 2 items: View dependents tool and Add/remove dependents form

**MUST** <br>
Add/remove dependents 686
- Update URL for the 686 from to include the "21" in the form number.  URL should be: `https://staging.va.gov/view-change-dependents/add-remove-form-21-686c` .  This was incorrectly documented in the IA recommendations and noticed by the designer, my apologies for missing this. 
- In the breadcrumb, add a dash between the 21 and 686 in "Add or remove dependents form 21-686c"
- In the breadcrumb, the "View or change your dependents" component should link to 'https://staging.va.gov/view-change-dependents/'.  

View dependents tool
- Both the 2nd and 3rd sections of the breadcrumb are incorrect.  Breadcrumb should be: Home > View or change your dependents > View your dependents
- The "Learn more about adding or removing a dependent from your VA benefits"  is currently linking to a page that will be retired. 

**SHOULD** <br>
~View dependents tool~
~Unauthenticated users that attempt to access the "View dependents" tool directly should be sent to the static landing page - http://www.va.gov/view-change-dependents.  The user can then click to sign in and proceed. Currently the sign in is served over top of the home page and that could be confusing for some users who are not sure what or why they are being prompted to sign in.  This is the recommended flow.~
^^^Removing this for larger discussion on standard flow change

**CONSIDER**
- none

## Definition of Done
- [ ] Must feedback is implemented on staging
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by jason-gcio** [comment]
This was all completed save for the very first item, which has been ticketized here: #27514
