### ISSUE TITLE
[Development] 526: disabilities array must be between 1 and 100

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#12938]
Some submissions are failing with this error:
`form526.disabilities.Size: size must be between 1 and 100`

Add validation to the UI that will catch this error before the form is submitted.

Looking at occurrences of this error, largely the problem is that 0 disabilities are handed to the BE.

this ticket comes from https://github.com/department-of-veterans-affairs/va.gov-team/issues/9903#issuecomment-681291763

## Acceptance Criteria
- [ ] disability arrays handed to the BE cannot be < 1 or > 100

**Comment by edmangimelli** [comment]
not sure what epic this should be in

**Comment by ndsprinkle** [comment]
Going to try to knock this out quickly today.

**Comment by luke-gcio** [comment]
Nick is going to implement this when they try to add more than 100 (message "you've reached a maximum number of disabilities we can submit on this form. When you speak to an adjudicator after claim submission you can discuss your claim and add additional disabilities").
