### ISSUE TITLE
[Bug] SSO-Cerner Health Page Updates - Auth'd - Prescriptions - Copy/styling mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12937]
## What happened?
On Staging **[Cerner Health, Prescriptions](https://staging.va.gov/cerner-staging/prescriptions/)** page \[authenticated], copy/styling did not match specs.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: ```ssoissoetesting+mhvcss4@gmail.com``` (Adolph) -- this was provided as a Cerner user.

## Steps to Reproduce
1. Go to https://staging.va.gov/cerner-staging/prescriptions/ -- sign in as ```ssoissoetesting+mhvcss4@gmail.com``` (Adolph).
1. Observe the following copy/styling mismatches:
    A. Immediately below **page-title**, alert copy/styling do not match spec.
    B. **How can the VA Prescription and Refill...** section-title, 1st paragraph, and subhead copy do not match spec.
    C. **Am I eligible...** section-title and 1st paragraph copy do not match spec.
    D. **Can I use...** section-title copy does not match spec, and spec'ed 1st-sentence deleted instead of moved.
    E. **Where will...** section **Important note** copy does not match spec.
    F. **How long...** section 1st paragraph copy does not match spec.

#### A. Below page-title, alert copy/styling mismatches:

![SsoC-copy-bug-authd-prscrptn](https://user-images.githubusercontent.com/587583/91383479-14bfe680-e7e1-11ea-8fe9-ff947693cc70.png)

#### B. "How can..." copy mismatches:

![SsoC-copy-bug-authd-prscrptn-2](https://user-images.githubusercontent.com/587583/91383444-01ad1680-e7e1-11ea-8d1e-60c24b136411.png)

#### C. "Am I eligible..." copy mismatches:

![SsoC-copy-bug-authd-prscrptn-3](https://user-images.githubusercontent.com/587583/91372452-87709800-e7c8-11ea-804a-3bdafb990610.png)

#### D. "Can I use..." copy mismatches:

![SsoC-copy-bug-authd-prscrptn-4](https://user-images.githubusercontent.com/587583/91374439-0e277400-e7cd-11ea-8e0e-6fb837fa7928.png)

#### E. "Where will..." copy mistmatch:

![SsoC-copy-bug-authd-prscrptn-5](https://user-images.githubusercontent.com/587583/91375607-00bfb900-e7d0-11ea-9eec-8c24a239a39b.png)

#### F. "How long..." copy mismatch

![SsoC-copy-bug-authd-prscrptn-6](https://user-images.githubusercontent.com/587583/91384085-a419c980-e7e2-11ea-8b53-4ce794c4f8f9.png)

#### A. Below page-title, alert spec:

![SsoC-copy-spec-authd-prscrptn](https://user-images.githubusercontent.com/587583/91371707-95bdb480-e7c6-11ea-98b2-5ced8f5e3dba.png)

#### B. "How can..." copy-spec:

![SsoC-copy-spec-authd-prscrptn-2](https://user-images.githubusercontent.com/587583/91383512-299c7a00-e7e1-11ea-8c49-11ed521c995c.png)

#### C. "Am I eligible..." copy spec:

![SsoC-copy-spec-authd-prscrptn-3](https://user-images.githubusercontent.com/587583/91372481-99523b00-e7c8-11ea-85b7-c0c2e626db22.png)

#### D.  "Can I use..." copy-spec \[from #12446]:

![SsoC-copy-spec-authd-prscrptn-4](https://user-images.githubusercontent.com/587583/91374450-17184580-e7cd-11ea-9cc7-efefe39f30f4.png)

#### E. "Where will..." copy-spec:

![SsoC-copy-spec-authd-prscrptn-5](https://user-images.githubusercontent.com/587583/91375659-2351d200-e7d0-11ea-8c6f-5c1abf330b4e.png)

#### F. "How long..." copy-spec:

![SsoC-copy-spec-authd-prscrptn-6](https://user-images.githubusercontent.com/587583/91384118-b267e580-e7e2-11ea-9c79-8266288a3b29.png)

## Acceptance Criteria
- [ ] \[See **Desired copy/styling above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tlei123** [comment]
Closing this as invalid for the underlying Authenticated-content test-run.

Unauthenticated content actually came up instead, which generated this Bug.  There was feature-flagging on Staging that disabled the Authenticated-content.

**Comment by DanielleThierryUSDSVA** [comment]
@tlei123 Looks like this should be closed, so I'm closing now. Thanks!
