### ISSUE TITLE
[Bug] SSO-Cerner Health Page Updates - Auth'd - Appointments - Copy mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12935]
## What happened?
On Staging **[Cerner Health, Appointments](https://staging.va.gov/cerner-staging/appointments/)** page \[authenticated], copy did not match copy-spec.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]
- Test User _(if applicable)_: ```ssoissoetesting+mhvcss4@gmail.com``` (Adolph)

## Steps to Reproduce
1. Go to https://staging.va.gov/cerner-staging/appointments/ -- sign in as ```ssoissoetesting+mhvcss4@gmail.com``` (Adolph).
1. Under **What if I have more quesitons?**, observe that copy does not match copy-spec.

**Staging screenshot**:

![SsoC-copy-bug-authd-appts](https://user-images.githubusercontent.com/587583/91363840-62712a80-e7b2-11ea-93ce-83e9574a2d80.png)

## Desired copy

**Copy-spec screenshot** from [TestRail Test Case](https://dsvavsp.testrail.io/index.php?/cases/view/788&group_by=cases:section_id&group_order=asc&group_id=162):

![SsoC-copy-spec-authd-appts](https://user-images.githubusercontent.com/587583/91363887-7ae14500-e7b2-11ea-9773-961295d7a6c6.png)

## Acceptance Criteria
- [ ] \[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tlei123** [comment]
@DanielleThierryUSDSVA , FYI, this is now the ONLY valid Bug for Authenticated-content.  I've Closed the other Authenticated-content Bugs as invalid.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @tlei123. I've checked this and we're good. This was a change we made due to the appointments tool changing from My HealtheVet to the VA appointments tool on VA.gov.  Thanks very much for flagging!
