### ISSUE TITLE
[Support] Onboard By Light

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1293]
## User Story
As a VFS team, I need to know what the VSP Analytics and Insights team does so I can use efficiently use their analytics support for my products and processes.

## Goal
Onboard By Light onto VSP Analytics and Insights.

## Acceptance Criteria
- [x] Schedule Meeting with Team
- [x] Meet with Team
- [ ] Add Team Members to Google Analytics
- [x] Iterate Onboarding Documentation based on debrief

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
Attempted to add users on 8/28 to GA but emails do not match a Google account. I will reach out to Dorothy as a follow-up

**Comment by nedierecel** [comment]
- 8/29/2019: Reached out to Dorothy; Team will create Google Accounts associated with By Light emails

@joanneesteban Recommendations for future trainings:
- Clarify difference between GMail vs. Google Accounts so access process is more efficient (Include screenshots of Signup Without Gmail form)

**Comment by joanneesteban** [comment]
Send out full instructions to teams for adding GA access:

Instructions
1. Make sure every team member has a Google account tied to their corporate or va.gov email.
 Email addresses ending in gmail.com may not be used.
 If the user has a VA.gov or work email address that is not linked to a Google account, they will need to create one by visiting this link.
 VA.gov users and external users with email accounts that are not Google based should select the option “Use my current email address instead”.
 If the user already has a Google account that is not yet linked to their VA.gov email, they can link it using these instructions.
2. Create a list of the email addresses.
3. Send a Slack message to #vsp-analytics with the email addresses that need to be invited.

**Comment by nedierecel** [comment]
Brittany was added on Monday, 9/16; Sent Slack on 9/17 that Dorothy and Dan's emails need an associated Google account.

**Comment by nedierecel** [comment]
Via Slack - Dorothy expressed she and Dan do not need access at the moment. We will add a subsequent team member in a new ticket.
