### ISSUE TITLE
[Bug] SSO-Cerner Health Page Updates - Unauth'd - Results - Copy mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#12931]
## What happened?
On Staging **[Cerner Health, Results](https://staging.va.gov/cerner-staging/results/)** page \[unauthenticated], copy did not match copy-spec.

## Specs:
- Device: \[device-agnostic]
- Browser: \[browser-agnostic]

## Steps to Reproduce
1. Go to https://staging.va.gov/cerner-staging/results/ -- do not sign in.
1. Immediately below **page-title**, observe that spec'ed 1st paragraph is missing.

**Staging screenshots**

![SsoC-copy-bug-unauthd-rslts](https://user-images.githubusercontent.com/587583/91358403-a01c8600-e7a7-11ea-8d5a-0b16db1a810c.png)

## Desired copy

**Copy-spec screenshot** from [TestRail Test Case](https://dsvavsp.testrail.io/index.php?/tests/view/9597&group_by=cases:section_id&group_order=asc&group_id=162):

![SsoC-copy-spec-unauthd-rslts](https://user-images.githubusercontent.com/587583/91358327-7bc0a980-e7a7-11ea-850d-1bff08b1805b.png)

## Acceptance Criteria
- [ ] \[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Just going through anything Cerner related ahead of 10/24. I think this is okay, as the intro paragraph won't appear here since it's housed in Drupal. @kelsonic would you mind confirming when you have a moment before I close this? Thanks!

**Comment by kelsonic** [comment]
@DanielleThierryUSDSVA that's correct! Ok to close imo 🙂

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @kelsonic!

FYSA @MickinSahni  @brianalloyd @tlei123 I'm going to go ahead and close this.
