### ISSUE TITLE
[FE] - Update form button styling

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#12943]
### Description
In some rare scenarios, the 'Remove' action did not wrap to the next line. Also, the padding between the Cancel and Confirm buttons is too wide.

![image.png](https://images.zenhubusercontent.com/5e9d15aab51cccb259a8a6c7/905cd394-2c3b-4757-9847-b965293940c3)
![image.png](https://images.zenhubusercontent.com/5e9d15aab51cccb259a8a6c7/08b3ab32-46c1-4a39-b038-6483f45d597d)

### Tasks
- [ ] Ensure the Remove action wraps to the next line
- [ ] Make the padding between the action buttons 1 unit instead of 2

**Comment by mshea0606** [comment]
@sanlouise looks good!
