### ISSUE TITLE
EDU: Update feature flag implementations.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12944]
As a developer, I need to modify feature flags to verify user has authorization to access the feature flag.

## Assumptions:
1. This work is related to feature flags in vets-api repository.
2. The following feature flags are to be reviewed to determine changes necessary for this story:
    a. edu_benefits_stem_scholarship
    b. stem_sco_email
    c. gibct_filter_enhancement
    d. gibct_search_enhancements
    e. gibct_eyb_bottom_sheet

## Acceptance Criteria:
1. The following feature flags are accessible to authorized users:
    a. stem_sco_email

## Supporting Artifacts:
1. [Backend example](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

**Comment by ksantiagomorgan6** [comment]
Looks like the  stem_sco_email feature flag was the only one that needed updating to test EVSS data in prod

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-api/pull/4807

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-02 at 7.59.16 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e269f000-1972-4d76-a861-f4d7875a5ce6)
##
![Screen Shot 2020-09-02 at 7.59.23 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/44252ce6-cc6a-4b03-a23f-2f4d5415404f)
##
![Screen Shot 2020-09-02 at 7.59.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2382f8ba-2116-4bb1-b29d-5a507cc12c09)
##
![Screen Shot 2020-09-02 at 8.00.36 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/68f84c1b-d669-49d8-9dbe-29df1b4f0dfd)
