### ISSUE TITLE
Review Pact docs for FE & BE Tools teams

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#12945]
### What is your documentation request, question, comment, or issue?

VSP FE & BE Tools teams are currently working on setting up Pact. Pact is an integration testing tool that will allow VFS teams to run automated tests on their apps, specifically to test the frontend of the app (the UI on VA.gov)'s integration with the backend. 

Lindsey and Eugene have drafted VFS-facing documentation about how to set up Pact. That can be seen in the `be-tools/pact-readme` branch: https://github.com/department-of-veterans-affairs/va.gov-team/blob/be-tools/pact-readme/platform/testing/integration-testing/how-to-use-pact-for-integration-testing.md

I reviewed and left some comments on the PR, many of which have now been addressed: https://github.com/department-of-veterans-affairs/va.gov-team/pull/11833

As I see it, there are 3 primary sections to this doc: introduction & details about Pact, how to set up the frontend, and how to set up the backend. We've talked about maybe splitting these out into separate docs, but I'm not sure whether that is necessary and am curious for y'alls documentation advice. 

We hope to begin testing Pact with VFS teams mid-next week — this will include getting feedback from engineers on the documentation (in other words, it doesn't need to be 100% perfect right now). I'm hoping to have another round of edits completed (from y'all) before we begin that testing.

@U-DON @LindseySaari @alexpappasoddball @rianfowler please add any details here as needed! Thanks all. 👍

**Comment by gmaciolek** [comment]
@meganhkelley I'm going to take a look at this with @amygoldman tomorrow morning and between the two of us, we'll get back to you with recommendations by end of day Tuesday. Does that timing work for you?

**Comment by meganhkelley** [comment]
Yep, Tuesday will work! 💯

**Comment by gmaciolek** [comment]
@meganhkelley I guess by end of day I meant, in the wee hours of Wednesday AM 😄  I think the doc is pretty solid! 

I edited the doc and left comments in PR #13106  (Apologies if that decision causes confusion--I see you already have a neatly organized conversation going on PR #11833) Feel free to challenge any of my changes. My goal was to smooth out the formatting for better scannability/readability and to make the sections a little more consistent with one another. The FE and BE sections read like they were written by different authors--neither were necessarily bad! Just not consistent with each other.

As for whether or not to split up the docs, my gut says leave it as one doc for now. I don't feel too strongly about it, though. Our cross-linking and IA health are generally not awesome right now. In the current state of VSP docs, if the BE and FE content is all on one page, information is less likely to be missed or become the victim of yet another broken link.
