### ISSUE TITLE
[Development] 526: error: "disability being claimed for increase was not found"

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#12941]
Some submissions are failing with this error:
`form526.disabilities.ratedDisability.isInvalid: The rated disability being claimed for increase was not found for Disability`

Look up occurrences of this error one-by-one and see if we're maybe formatting the request incorrectly.
Spin up a ticket as necessary (if you want this to be a discovery ticket and you think there should be a separate implementation/ bug fix ticket)

this ticket comes from https://github.com/department-of-veterans-affairs/va.gov-team/issues/9903#issuecomment-681291763

## Acceptance Criteria
- [ ] this error stops showing up in our reporting/monitoring

**Comment by annaswims** [comment]
Data example in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/163

It seems to suggest that the veteran's rated disabilities were updated in the time that the veteran started filling out the form and when it was submitted.

**Comment by annaswims** [comment]
if we see the error it means that the 4th and 6th `ratedDisabilities` with a `"disabilityActionType": "INCREASE"` are invalid.  

````ruby
{"{"key"=>"form526.disabilities[3].ratedDisability.isInvalid", "text"=>"The rated disability being claimed for increase was not found for Disability", "severity"=>"ERROR"}",
"{"key"=>"form526.disabilities[5].ratedDisability.isInvalid", "text"=>"The rated disability being claimed for increase was not found for Disability", "severity"=>"ERROR"}"}
````

I think the correct course of action would be to retrieve the `/v0/disability_compensation_form/rated_disabilities` data each time a user returns to the form and check that the form's `ratedDisabilities` are included in the data from the endpoint.

**Comment by annaswims** [comment]
What's happening is that we get the veteran's rated disabilities when they first start the form (as a prefill)  then, their rated disability info is updated by the VA.  Then, when the veteran submits the form the submission fails and we provide no useful information to the veteran. At this point, the veteran doesn't  have any way of getting the updated rated disability information in their form, other than deleting their form and starting again. 

This error affected 53 veterans this month who tried their submission an average of 5 times each.

**Comment by annaswims** [comment]
In conclusion: I think we should address this in the front end in a new ticket. We'll need to hammer out the details but I think  the correct course of action would be to retrieve the /v0/disability_compensation_form/rated_disabilities data each time a user returns to the form and check that the form's ratedDisabilities are included in the data from the endpoint.

**Comment by annaswims** [comment]
Closing. Created https://github.com/department-of-veterans-affairs/va.gov-team/issues/13128 as the next step
