### ISSUE TITLE
STEM: Remove 'gibct_ch33_benefit_rate_update' feature flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12946]
As a developer, I need to remove the feature flag for benefit level percentages because they will not be reverted going forward.

## Assumptions:
1. The feature flag was configured as part of story #11534.
2. This functionality has been turned on as of 07/31/2020 and no issues have been encountered.

## Acceptance Criteria:
1. The feature flag 'gibct_ch33_benefit_rate_update' is not displayed here: https://[environment]-api.va.gov/flipper/features.
2. The functionality delivered in #11472 is still available.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PRs:

Front End: https://github.com/department-of-veterans-affairs/vets-website/pull/14077
Back End: https://github.com/department-of-veterans-affairs/vets-api/pull/4813

**Comment by sonntag-adam** [comment]
Removed from staging and production. Testing passes QA
