### ISSUE TITLE
Increase font size for date on final screen

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#12942]
## What happened?

Per feedback from users in Puget Sound, the font size for the date on the final screen to be larger since they are required to verify the date. 

I'll work on an updated design.

**Comment by artsymartha68** [comment]
OK this is what it looks like on my iPhone 8. We definitely have some vertical room to play with.

The only thing I'm changing here:

1. Day name font size: 54 px in Sketch (can we insure no line breaks in day name somehow?)
2. Add a line return/paragraph for Date
3. Increase font size for date: 74 px in Sketch
4. Remove comma, add line return/paragraph for time
5. Time font is 24 px in Sketch

<img width="856" alt="Screen Shot 2020-08-27 at 10 01 28 AM" src="https://user-images.githubusercontent.com/47792423/91452216-56d24200-e84c-11ea-99bc-8228ac8893d7.png">

**Comment by mchelen-gov** [comment]
@artsymartha68 it seems like we are supposed to use these classes & font sizes from the design system:
- https://design.va.gov/design/typography
- https://design.va.gov/utilities/font-size

however they do not go large enough for this use case. 

i ended up creating custom classes with `font-size: 500%` and such. this is probably no the best approach, but i'm not sure how we are supposed to do this?

**Comment by artsymartha68** [comment]
For SURE the design system does not handle supersized fonts like we want for screener. CC @rianfowler for advice on the best way to do this...?

**Comment by mchelen-gov** [comment]
@artsymartha68 is this a question for design council board? .cc @KevinMHoffmanUSDS

**Comment by artsymartha68** [comment]
Luckily @rianfowler is on the council too! The entire mobile optimized supersized UI is a variation we have talked about contributing back to the design system. Screener is a bit of a special case, admittedly. Very few Veteran-facing UIs we create have the "viewable from 6 ft away" requirement.

**Comment by mchelen-gov** [comment]
@artsymartha68 [PR is here](https://github.com/department-of-veterans-affairs/vets-website/pull/14100) for review if it ever successfully deploys to review environment...

**Comment by mchelen-gov** [comment]
@artsymartha68 can you take a look at [review instance](http://4100fa77e296595a45de09d7f341d26f.review.vetsgov-internal/) and approve https://github.com/department-of-veterans-affairs/vets-website/pull/14100 if it looks good?

**Comment by artsymartha68** [comment]
@mchelen - approved! Oh wait let me actually approve. :)

**Comment by mchelen-gov** [comment]
resolved by https://github.com/department-of-veterans-affairs/vets-website/pull/14100
