### ISSUE TITLE
Add sass:changed yarn task

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#12950]
Currently our `lint:changed` task, which runs as a pre-commit hook, calls `lint:sass`, which examines ALL of our scss files, not just the ones we touched.

Can we please add a `sass:changed ` task so we only see warnings and errors related to the files we actually touched?

**Comment by oseasmoran73** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/18254) created

**Comment by oseasmoran73** [comment]
Closing ticket as PR has been merged and is in `vets-website`
