### ISSUE TITLE
Load testing - Create a load testing review model for VFS teams

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#1295]
## User Story
As a VA.gov team member, I want to have clear alerting and monitoring, so that I can see true problems and not have issues lost in the noise. 

## Measuring Success
- [ ] Increase in customer NPS
- [ ] Reduction in volume of "non-human-needed" support requests month over month

## VSP OKRs 
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

**Comment by ricetj** [comment]
@ricetj to close these

**Comment by jhouse-solvd** [comment]
Closing per TJ above
