### ISSUE TITLE
Screenreader support for invalid PDF message

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#12958]
## Issue Description
Given a PDF url may be invalid
I want to make sure the alert that appears is accessible by screenreaders
so people of differing abilities can note when a PDF form isn't available.

---
## Tasks
- [ ] tbd

## Acceptance Criteria
- Alert is made accessible by screenreaders

Note:
- TBD if this is already handled elsewhere

**Comment by kelsonic** [comment]
Can this ticket be closed? Is it still relevant? CC @brianalloyd

**Comment by brianalloyd** [comment]
Think we can close this based on work that has already been done with screen reader.
