### ISSUE TITLE
vets-json-schema: "additionalProperties" should default to False

### ISSUE THREAD

**Issue by short000** [department-of-veterans-affairs/va.gov-team#12959]
### User story
As a VFS developer, I want "additionalProperties" in vets-json-schema to default as false, so that undefined data does not accidentally make it past validation and possibly enter our database.

### Additional details/notes/links
The property “additionalProperties” should be “false” on every schema property of type “object” - to avoid unsolicited data entering our database. (additionalProperties -false; otherwise, undefined). Impact if not fixed: data that is not defined in the schema could make it past validation and possibly into our database. 

Kevin has a possible solution in mind. He may be able to make the fix himself and request a PR.
https://dsva.slack.com/archives/CBU0KDSB1/p1576622962082800?thread_ts=1576620898.079800&cid=CBU0KDSB1

### Acceptance criteria
TBD

### Point(s) of contact
@kevinmirc 

### What type of issue is this? 
- [x] Bug
- [ ] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

### How to configure this issue
- [ ] When ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by kevinmirc** [comment]
To resolve this I'd suggest adding a test to `vets-json-schema/test/common/all-schemas.spec.js` that would assert that any property with `"type": "object"` has an adjacent key of `additionalProperties` set to `false`.

Future versions of json-schema may default "additionalProperties" to false, so this may be something to consider if we have a version update planned.

**Comment by cvalarida** [comment]
Would setting `additionalProperties` to `false` by default break the validation on existing forms? How can we tell without introducing a bug in production and watching Sentry?

**Comment by laineymajor** [comment]
@micahchiang It looks like this ticket is related to a forms library epic. Should this be reassigned to y'all?

**Comment by micahchiang** [comment]
@laineymajor - The forms library team won't be prioritizing this work. You can close this. Thanks!

**Comment by laineymajor** [comment]
Closing per Micah's comment
