### ISSUE TITLE
IA Request for Higher Level Review Entry Points

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12957]
As we are beginning to roll out different decision review and appeals capabilities it is clear that the decision and appeal review information is not very easy to find.  We are wondering how it would be best to update the IA and public websites to advertise the fact that we have the new capability available.

Currently, we have the following flow.

![image](https://user-images.githubusercontent.com/53824125/91477619-d74c6f00-e85b-11ea-849f-5567ec6d34aa.png)
User lands on VA.gov and then clicks "file a claim for compensation".  Notice this does not indicate that there is an option to question a decision.

![image](https://user-images.githubusercontent.com/53824125/91477719-ff3bd280-e85b-11ea-9b6c-963d82bbc145.png)
Next, the veteran has to enter in YES to separated and "I'm disagreeing" to see an info box with the decision review info.

![image](https://user-images.githubusercontent.com/53824125/91477825-2db9ad80-e85c-11ea-8723-f273c9aee339.png)
They then land on this page and have to click "request a decision review".

![image](https://user-images.githubusercontent.com/53824125/91477882-3e6a2380-e85c-11ea-86e8-cb0668d2fb9a.png)
Then they have to know to click on Higher Level Review - no where does it indicate at this time that this capability is available on VA.gov or whether they are even eligible.

![image](https://user-images.githubusercontent.com/53824125/91477971-6063a600-e85c-11ea-9960-303f093ba841.png)
Finally they make it to the HLR page and will see the new wizard for HLR.

As you can see, the HLR capability will remain very hidden without some IA changes.  There is a much larger effort to create a decision review wizard (for all decision and appeal types) to determine eligibility. This is not the intent of this request.  We are asking for advice/recommendations on how to best advertise the existence of HLR within the confines of some of the existing flow and content on the public websites side of the house.

## Required Inputs:
- Link to product outline ([HLR](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/README.md))
- Link to or attach prototype or mockups (https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/404075470_HLR_-_Info_Page)
- Link to research readout/results (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/research/HLR%20usability%20testing%20-%20Research%20Readout.pdf)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords** - Higher Level Review, Decision, ???

**Proposed site map/page structure** - N/A, just wanting some advice on the above.

**Suggested URL(s)** - N/A for this particular question.

**Suggested entry points** - Somewhere higher up - perhaps find a way to provide a temporary note or something that advertises that HLR is available.

**Crosslinking opportunities** - N/A

**Redirects/canonical tags** - Not sure at this time.

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by luke-gcio** [comment]
Added @lwalsh617 since she was heavily involved in some of the content around decision reviews.

**Comment by bethpottsVADEPO** [comment]
Hi @luke-gcio... I appreciate your looping in @lwalsh617, but I'm going to unassign her for now since this is (at least initially) purely IA and Laura is heads down on a big project. @mnorthuis will bring her into the fold when there are content needs. Thanks!

**Comment by luke-gcio** [comment]
No worries - thanks for taking the time to explain it!

**Comment by mnorthuis** [comment]
@luke-gcio have you pulled any analytics or search data for insights on how users are looking for this content?  As part of the last round of AMA updates, we did add entry points to decision reviews from each of the benefit hubs, would be good to know if any of those links are seeing any traffic, or where users are coming from to get to decision reviews.

**Comment by luke-gcio** [comment]
@mnorthuis Getting back to this - I have not pulled those metrics and would love some help pointing me in the right direction.  I have played around in GA a few times but I definitely don't know where I'm looking for this data.

**Comment by mnorthuis** [comment]
@luke-gcio Following up on this older issue.  Have you worked with the analytics team to pull data on current traffic and referring pages?  Are you considering any research around the findability of this content?   User data/feedback would be needed to review findability of this content.

**Comment by mnorthuis** [comment]
This issue is a bit aged, and we had done some entry point work after this was opened.  Closing this issue, and a new issue can be opened if data shows that there are any concerns around traffic or findability.
