### ISSUE TITLE
DEV: Get local builds working on iPhone / iOS

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12964]
As a developer, I need local builds working on the iPhone so that I can test and validate iOS specific fixes.

## Assumptions:
1. This story will unblock https://github.com/department-of-veterans-affairs/va.gov-team/issues/10201

## Acceptance Criteria
1. A local build is accessible on an iPhone.
2. Documentation is attached to this story that outlines the steps necessary for future reference.

## Technical Notes:
1. Steps mentioned by DEPO: yarn watch --env.host 0.0.0.0 --env.public 192.168.x.x:3001

## Supporting Artifacts
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4811

**Comment by delli-gatti-michael** [comment]
This is working on master. Closing this issue
