### ISSUE TITLE
School Ratings: Upload school ratings data CSV to GIDS

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#12962]
As an EDU Team Member, I need the ability to upload a data file containing school ratings information to GIDS so that the information can then be displayed within the comparison tool

## Assumptions:
1. The rating columns can be a value of 1 to 5 stars with `null` or `0` being treated as a "N/A" rating.  Anything over a 5 will be treated as a 5.
2. Rankers can rate an institution multiple times
3. Rankers can rate multiple institutions
4. This file is not required to generate and publish a new version
5. Including this data in the version will be done in a future story.

## Acceptance Criteria
1. A "school_ratings.csv" with the following data elements can be uploaded to GIDS:
    a. `rater_id` (REQUIRED string), Note: The format of this isn't known, so `string` gives us the most flexibility.
    b. `facility_code` (REQUIRED string)
    c. `overall_experience` (int)
    d. `quality_of_classes` (int)
    e. `online_instruction` (int)
    f. `job_preparation` (int)
    g. `gi_bill_support` (int)
    h. `veteran_community` (int)
    i. `marketing_practices` (int)
    j. `rated_date` (REQUIRED datetime), Note: rankers can rank institutions more than once, and this will be used to make sure we're only counting their most recent ranking.
2. Data rows are validated against the specifications in AC1:
    a. If there is a data type mismatch the following message is displayed: "Row [Number]: [column name] : is not a number"
    b. If there is a data type mismatch the following message is displayed: "Row [Number]: [column name] : can't be blank"
    c. If the data does not meet the specifications, the row is not imported.
    d. If a row contains multiple validation errors, they are all displayed on a single line.

## Supporting Tasks:
- [ ] Create and add to `repo` a mock data CSV to be used in testing this story.

## Supporting Artifacts:
1. [Prototype 1](https://bahdigital.invisionapp.com/share/KYIAERSZNVP#/screens)
2. [Prototype 2](https://bahdigital.invisionapp.com/share/PGIAEQXWMQ7#/screens)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/713
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/714

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are in Staging. Closing this story

**Comment by delli-gatti-michael** [comment]
Tested by the following test case

https://dsvavsp.testrail.io/index.php?/tests/view/12393&group_by=cases:section_id&group_order=asc&group_id=46
