### ISSUE TITLE
vets-json-schema: semantic versioning

### ISSUE THREAD

**Issue by short000** [department-of-veterans-affairs/va.gov-team#12963]
### User story
As a VFS developer, I want library references to use semantic versioning rather than individual hash codes, so that our builds leverage the benefits of a standard release versioning scheme rather than the current the tedious and brittle process of manually updating references across several repos manually.

### Additional details/notes/links
Enforce semantic versioning and require references to the UI and API updates to support the changes (when breaking). Since we just use hash codes rather release versioning, we have to manually update references across three different repos manually (three separate PRs, etc.) The process is something like this: build vets website, PR, then schema from vets-website, move into vets-json schema repo, PR vets-json schema. Vets-api, work, PR in vets-api. In practice, many developers do not go through the process of updating website and api, which can cause complex code block days later, when someone else makes a change and imports it into website/api.

Impact if not done: continued tedious process for existing developers; trial-and-error for new developers. Continued configuration management risks.

Question: do we publish to npm or use a patch script?

### Acceptance criteria
TBD

### Point(s) of contact
@kevinmirc 
@cohnjesse 

### What type of issue is this? 
- [ ] Bug
- [x] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

### How to configure this issue
- [ ] When ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by cvalarida** [comment]
I can't speak for how the API manages dependencies, but I think even if we were to use semantic versioning, we would still need to create another PR for `vets-website` to update the pinned `vets-json-schema` version in the `yarn.lock` file.

This would solve the problem of using hashes on branches, though.

**Comment by cvalarida** [comment]
Ooh, we maybe could automate the creation of a version-bump PR in vets-website and vets-api, though. I think if we were going to do semantic versioning, we'd need to publish `vets-json-schema` as an NPM module, which means either manual publishing (nope) or automated publishing to NPM from CI (that's the way we'd go). Since we'd have to add something to CI _anyhow_, we could potentially just update the GitHub hash. That could work.

:thinking: Does `vets-json-schema` _have_ a CI pipeline? :confused:

**Comment by laineymajor** [comment]
@micahchiang It looks like this ticket is related to a forms library epic. Should this be reassigned to y'all?

**Comment by micahchiang** [comment]
@laineymajor - The forms library team won't be prioritizing this work. You can close this. Thanks!

**Comment by laineymajor** [comment]
Closing per Micah's comment
