### ISSUE TITLE
[BE] Profile 2.0 bug: Direct deposit isn't working

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12977]
## Background

The direct deposit feature on Profile 2.0 isn't working. [Sandra looked into the issue](https://dsva.slack.com/archives/C909ZG2BB/p1598624841098400?thread_ts=1598623926.098000&cid=C909ZG2BB), and reported that this is an issue with the API retrieving direct deposit info.

This needs to be fixed ASAP, as we are starting UAT on 9.1.20.

## Tasks

- [ ] Get direct deposit up and running again in staging for profile 2.0.

**Comment by mshea0606** [comment]
https://dsva.slack.com/archives/C909ZG2BB/p1598907215017400
