### ISSUE TITLE
508-defect-4 [COGNITION]: CONSIDER updating the label Hours for 18-23 year old students who are enrolled part time

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#13018]
## [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

While adding an 18-23 year old child in college in my benefits, I noticed a field that asked for hours they were enrolled in part-time when I answered "No" to the enrolled full time question. I'd like to clarify what "hours" means, if it's hours per week, credit hours, or something else. Screen shot attached below.

## Point of Contact

**VFS Point of Contact:**  _Trevor_

## Acceptance Criteria
- [ ] As a user, I want to make sure I'm understanding the question of my child's hours correctly

## Screenshots or Trace Logs

![Screen Shot 2020-08-28 at 4 54 30 PM](https://user-images.githubusercontent.com/934879/91618299-a0f01c00-e94f-11ea-9f14-1728f6614145.png)

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by jason-gcio** [comment]
On the form 21-674, this is termed as "10D. HOURS PER WEEK" which is safe to assume they mean credit hours.  We are going to change this to read:

**Credit hours per week**
Instead of **Hours a week**

**Comment by steve-gov** [comment]
@1Copenut What distinction are you drawing between "hours a week" and "credit hours a week" in this context? Where do you think the confusion would arise?

**Comment by 1Copenut** [comment]
@steve-gov I must have been moving too fast when I wrote that original ticket. I'm looking for an explicit explanation of what hours represents. It sounds like it's Credit Hours. If we know that for sure, I think should go with @jason-gcio comment to make the label **"Credit hours per week"**.

**Comment by steve-gov** [comment]
We don't know for a fact whether it means credit hours per week or total time burden or something else, so I'll ask the business for input. Please stand by.

**Comment by micahchiang** [comment]
@steve-gov - was business able to verify what the definition of `hours per week` here is?

**Comment by steve-gov** [comment]
The question is still out. I just asked again.

**Comment by steve-gov** [comment]
In the absence of evidence to the contrary or feedback from the business I suggest we mark this wontfix and stick with the form label as given. Will revisit if we get feedback from users or Comp Services.

**Comment by 1Copenut** [comment]
@steve-gov I'll move to close with a label identifying it as a won't fix item. Thank you.
