### ISSUE TITLE
508-defect-4 [COGNITION]: CONSIDER removing duplicated content for child's additional evidence needed accordion

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#13017]
## [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

While adding a child to my benefits, I noticed the Additional Evidence Needed accordion duplicates the first line of text "What are some examples of additional information?" I'd like to consider removing that second line because it's repetitive. Screen shot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor _

## Acceptance Criteria
- [ ] As a user, I don't want to read content twice, or have it read back twice if I'm using a screen reader

## Screenshots or Trace Logs

![Screen Shot 2020-08-28 at 9 51 52 AM](https://user-images.githubusercontent.com/934879/91617754-4e623000-e94e-11ea-93d3-b8f6b15c652c.png)

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by jason-gcio** [comment]
Super easy, doin' it.
