### ISSUE TITLE
508-defect-4 [DESIGN, COGNITION, MOBILE DESIGN]: CONSIDER re-ordering the confirmation page to support assistive tech better

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#13019]
## [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

When looking at the confirmation page and listening to it with screen readers, I thought it might be worth looking again at where focus is set, and where we place the print receipt call to action. I found myself wanting to hear the confirmation heading that my form was submitted, then print my receipt. Screen shot attached below.

/cc @emilywaggoner && @CrystabelReiter for awareness

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Screenshots or Trace Logs

![Screen Shot 2020-08-28 at 10 26 16 AM](https://user-images.githubusercontent.com/934879/91618591-6470f000-e950-11ea-85bd-5fb635738098.png)

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by jason-gcio** [comment]
Do along side: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17004
