### ISSUE TITLE
Access for Srikanth Valluru

### ISSUE THREAD

**Issue by mydesignrocks** [department-of-veterans-affairs/va.gov-team#13023]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Srikanth Valluru
- Please Provide your email.
   > Srikanth.Valluru@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP/Ops Tools - Staff Software Engineer [Ad Hoc]

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQ91KCwJ3E6KbgUshcextzC5LlVMhI66SAXMVhp70qjIvz31eou43feGfOrCVOMECC+sVA20UqpMuxDaHHHl+gNFn83Gc5KPMk29JyM5ZWl6bMHhTyk4AuRHqWeXrW4eyf/cvWCJbKP9o1k4f+HktLVFhAsvOjGufFDq4Y74qvg9DW59KsE+AUsHK4cUkrtacjLbPNVkUgOFPvn2Vevv0EOjsCW5qtg/Si8MCnXyWfOvEHN4kBMhmKgI1/CJphhYRPS93SR+h17WgoyHSQjCO69BWRwWV8FPzEOwBsG6g0Gwd1vPSWHQaMsNB4rUYdhZl6tNGNzWgISjr1/8bbD/lj/3rBaFIxiHI9p4h4Qw+UxhRMayhFa/mACnZ7HT1SPnV6yCk21CnMYpZYT5ftRaPYdRKJvC1O3bJWo1XViNpZj0Ysj95oIWxBRi0qWoq/X6rWjA/K5bhjuD0tmtpzOA9+GfJatRjbccYZ3VgItqkwH90o/mtihHg0pQL/wLz2/jk= Srikanth Valluru@SrikanthV-Spectre
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
Need access to AWS GovCloud. Require access to AWS for troubleshooting, log file review, and to apply changes to the running instances and services. @department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
Seeking Approval for AWS Access
cc @Jeff-Hayter 
User: Srikanth Valluru

**Comment by jsev-io** [comment]
@mydesignrocks Srikanth you should now have SOCKS Proxy access

**Comment by jbritt1** [comment]
@Jeff-Hayter, this user is an Operations team member. Can we get him fast-tracked like we did for Julian and Stevan if at all possible?

**Comment by drorva** [comment]
approved. Welcome to the team Srikanth

**Comment by jsev-io** [comment]
AWS Access Granted
