### ISSUE TITLE
Mobile API module setup

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#13021]
## User Story
As an api developer I want a module, or rails engine, within vets-api so that the mobile endpoints are isolated from the core api.

### Definition of Done
- [x] The module skeleton for the mobile api is initialized in vets-api's modules directory
- [x] The base endpoint returns a welcome message
- [x] A feature flag is set to turn off all mobile endpoints in production

**Comment by srmyers17** [comment]
In review with VSP. Requires VSP review b/c this is the container we will work in and then we will be in our container and can be left alone!
