### ISSUE TITLE
issue statsd metric when SSOe post form is rendered

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#13022]
We've had issues in the past where the SAML post form didn't load in some user's browsers.  If we could issue some tracking call after the form has loaded, but before it is submitted, we could get some information on whether we still have problems with browsers loading the SSOe SAML Post form.

**Comment by erluti** [comment]
I commented on the PR, but just wanted to say here it'd be good to have a ticket lined up to roll this back once the problem is identified/corrected.
