### ISSUE TITLE
Mobile Discovery Endpoint

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#13020]
## User Story
As a mobile app developer I want a discovery endpoint so that I can load the correct feature endpoints for the version of the app.

## Tasks
- [ ] Hard code the versions 
- [ ] Return a JSON API formatted map of services 

### Definition of Done
The `/mobile` endpoint returns a map of features to endpoints similar to how [Github's discovery endpoint](https://api.github.com/) works.

**Comment by bridgethapner** [comment]
More for when we have different versions of the API

**Comment by kreek** [comment]
Design doc https://docs.google.com/document/d/1nNTJ77GJvxShzBLcvh0iNUEMjzc3eBkRIbqch2AhrWE/edit
