### ISSUE TITLE
9/16 - Redirect Request: Disability legacy rates pages

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#13024]
**Date: 9/16**

### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*The Public Websites team has created 2018 and 2019 historical rates pages for Special monthly compensation rates, Veterans compensation rates, Special benefit allowances rates and Birth defect rates. These specific legacy pages need to be redirected to the modern versions on our site.*

### Requestor team info
*Public Websites*

### Implementation date
Date new URL(s) will be live: **These pages are alreadylive**

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing :  Seven business days after stakeholder notification

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.benefits.va.gov/COMPENSATION/resources_comp0217.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/past-rates-2018/
https://www.benefits.va.gov/COMPENSATION/resources_comp0218.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/past-rates-2019/
https://www.benefits.va.gov/COMPENSATION/resources_comp0117.asp | https://www.va.gov/disability/compensation-rates/veteran-rates/past-rates-2018/
https://www.benefits.va.gov/COMPENSATION/resources_comp0118.asp | https://www.va.gov/disability/compensation-rates/veteran-rates/past-rates-2019/
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2017.asp | https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/past-rates-2018/
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2018.asp | https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/past-rates-2019/
https://www.benefits.va.gov/COMPENSATION/sb2017.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/past-rates-2018/
https://www.benefits.va.gov/COMPENSATION/sb2018.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/past-rates-2019/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@lunascoop @bethpottsVADEPO These 2 pages were launched at the incorrect URLs - the last component should use "historical" versus "historic".  Given these were just launched, we don't need to implement redirects once we move them, we just need to get them moved/corrected before we do these redirects.

https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/historic-rates-2018/
https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/historic-rates-2019/

**Comment by mnorthuis** [comment]
Please hold on the changing these URLs, will discuss with @bethpottsVADEPO regards some different direction on all of these URLs.  Only want to have to change them once! :-)

**Comment by mnorthuis** [comment]
This work is blocked by #13189 - once the urls are updated in that workstream, we can update them here and move forward with the redirects.

**Comment by MickinSahni** [comment]
Question from Kelson - what do we do about casing? @lunascoop to find out.

**Comment by lunascoop** [comment]
@mnorthuis the URL changes have been published and the table above has been updated. Also, per Mickin's comment, will casing for "/compensation" be an issue?

**Comment by kelsonic** [comment]
PR is up 🙂 https://github.com/department-of-veterans-affairs/vets-website/pull/14170 won't merge until the morning of 9/16, which means the redirects will be deployed on that date with the normal daily deploy

**Comment by mnorthuis** [comment]
Please account for casing issues - the legacy site often has multiple URL instances with different casing.

**Comment by lunascoop** [comment]
These redirects are live and have been validated. Closing ticket and notifying stakeholders.
