### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#13032]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
megan.kelley@adhocteam.us
liani@adhocteam.us
rian.fowler@adhocteam.us
gretchen.maciolek@adhocteam.us

## Access Requirements
I'm hoping to get access for myself and the above folks for the new view in GA that corresponds to the Gatsby site. Property is “VSP - VA.gov GitHub Table of Contents”
View is “Veteran Facing Services Tools”

It would be great if everyone who has access to that property is able to access both the docs homepage view and the Gatsby site view. Thanks!

## Date Required
No strict deadline, I'll say 9/7.

## Product Team / External Team / VA Office
VSP FE Tools

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @meganhkelley, 

We will make sure we get this access over to you folks today! Thank you for your patience here.

**Comment by jonwehausen** [comment]
Hi @meganhkelley , 

Folks here should now have access! Thank you and we will close when we've received confirmation from you all.

**Comment by joanneesteban** [comment]
Hi there! Closing this ticket - let us know if you have trouble accessing this.
