### ISSUE TITLE
CT-Search: Exclude list of common words from fuzzy search functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13039]
As a developer, I need to exclude common words from the fuzzy search functionality so that the search results provide a set of results with less extraneous matches.

## Assumptions
1. The feature flag was configured as part of story #10615.

## Acceptance Criteria
1. The top 20 terms in supporting artifact 1 are exclude from the fuzzy search algorithm.
    a. They are not excluded from the result sorting.
    b. If the search terms entered only contains excluded words then fuzzy search will use the excluded words
2. The similarity threshold for institution name is 25%.

## Supporting Artifacts:
1. [common_words_count.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5152406/common_words_count.docx)
2. Search results comparison prior to this story: [CT-Top 100SearchResultComparison.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5152422/CT-Top.100SearchResultComparison.xlsx)

## Notes:
Some terms to search to compare against prod:
- George Washington University
- University of North Carolina
- College of Charlston

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/715

when testing locally view the console logs and notice that the output that looks like below is missing top 20 common words listed in SA#1 in the `SIMILARITY(institution, 'george washington')` functions


>   Institution Load (245.0ms)  SELECT  "institutions".* FROM "institutions" INNER JOIN "versions" ON "versions"."id" = "institutions"."version_id" WHERE (campus_type != 'E' OR campus_type IS NULL) AND "institutions"."approved" = $1 AND "institutions"."version_id" = $2 AND "institutions"."vet_tec_provider" = $3 AND (facility_code = 'GEORGE WASHINGTON UNIVERSITY' OR SIMILARITY(institution, 'george washington') > 0.1 OR UPPER(city) = 'GEORGE WASHINGTON UNIVERSITY' OR UPPER(ialias) LIKE '%GEORGE WASHINGTON UNIVERSITY%' OR zip = 'george washington university') AND "institutions"."institution_type_name" != $4 ORDER BY COALESCE(SIMILARITY(ialias, 'george washington'), 0) + CASE WHEN UPPER(ialias) = 'GEORGE WASHINGTON UNIVERSITY' THEN 1 ELSE 0 END + CASE WHEN UPPER(city) = 'GEORGE WASHINGTON UNIVERSITY' THEN 1 ELSE 0 END + CASE WHEN UPPER(institution) = 'GEORGE WASHINGTON UNIVERSITY' THEN 1 ELSE 0 END + (COALESCE(SIMILARITY(institution, 'george washington'), 0)) + ((COALESCE(gibill, 0)/CAST(17635 as FLOAT))/3) DESC NULLS LAST, institution LIMIT $5 OFFSET $6  [["approved", true], ["version_id", 4], ["vet_tec_provider", false], ["institution_type_name", "OJT"], ["LIMIT", 10], ["OFFSET", 0]]

**Comment by sonntag-adam** [comment]
This is in staging. Closing story.
