### ISSUE TITLE
[Design] - MVP Learning Center - Mobile template for Step-by-step with screenshots

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13036]
Create mobile version of a step-by-step page with images in each step.  Might we need progressive enhancement for this if people are uploading large images into Drupal? Need to better understand how images are handled.

## Acceptance criteria

- [x] create mobile version of Step-by-step template with images for MVP 1.0
- [ ] review w @jenstrickland  
- [ ] @andaleliz, @rtwell, and @jenniferlee-dsva to review

**Comment by andaleliz** [comment]
@ncksllvn and @kelsonic I have some thoughts I want to bounce around with you about this:

I looked at the [template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#step-by-step), but didn't see answers to a couple of questions I had. Do you know if these have been defined anywhere?
- Is there a limit to how many steps a person can add?
- Is there a limit to how many screenshots a person can add for each step?


A few other thoughts, if Drupal gives us mobile-friendly image sizes ([Oksana is getting back to me in Slack on what Drupal does with images](https://dsva.slack.com/archives/C0173CAJ7A6/p1599164184088800))
- it'd be good to use the `picture` element if we have a choice, because I believe that allows us to use different image files (not just sizes). Down the road, if people are uploading screenshots of web UIs, it'd be cool if we could load a desktop screenshot on desktop devices, and a mobile screenshot on a mobile device.  
  - That assumes people would be willing to do both (a girl can dream) but I think if we use `picture` we'll be set up for it already.  
  - I think that use of `srcset` will automatically set images at viewport width to prevent panning/horiztonal scrolling on images, so those desktop screenshots will probably not be helpful on mobile.
- ^ given that scenario in the last bullet: I know people can enlarge on their phone, but if the image size is so small that it starts to get pixelated and people can't see details...thats not good. Any idea if that could be the case with the mobile images we get? If so, do we need to give some kind of special "zoom" or "enlarge" option (e.g. how you zoom in to details on an e-commerce product image)?

- lastly, can we do use lazy loading to optimize mobile performance, especially if people upload a bunch of images on a page?

We're still not totally sure how content authors are going to use this template or what images they'll upload for step-by-step. I'm thinking we do what we can to optimize data consumption for mobile users for now, and once we know more how these look in the wild, we can explore more advanced techniques/design iterations to optimize for mobile, if needed.

**Comment by andaleliz** [comment]
On hold. Waiting for image deets from Oksana and response on ^ before moving forward.

**Comment by andaleliz** [comment]
Moving some info from Slack into GH so we have this all in one place. I asked:

>I'm thinking through the step-by-step template with screenshots in each step. I try to consider a worst-case scenario, and I'm imagining a page where a content author has 15 steps and uploaded a giant file image for each step.  What's the mobile UX for that? 
I brought this up to the team yesterday and Nick said he was pretty sure that Drupal created different image sizes from an uploaded image. 
I'm interested to know more about how this works. Does it use the img or picture tag? Does it resize the images to a specific kb size, or dimensions, or both? Could you estimate the what the first 1-2 file weights would be on page load?

Oksana replied:
>let me do some digging into this question, Liz.
The CMS (in theory) provides various image sizes for each uploaded image. It’s then up to FE templates/logic to construct these images into appropriate tags <img> or <picture> .
I’ll follow up here once I confirm this is indeed a reality.

**Comment by andaleliz** [comment]
Also asked @oksana-c the question below.  She'll reply here instead of Slack.
>I looked at the template requirements, but didn't see answers to a couple of other questions I had:
- Is there a limit to how many steps a person can add?
- Is there a limit to how many screenshots a person can add for each step?

**Comment by oksana-c** [comment]
@andaleliz , there's currently no limit on steps. Screenshots are limited to 1 per step.
I'll get back re: images sizes next week.

**Comment by andaleliz** [comment]
Thanks Oksana! Submitted a PR to Jen to propose adding these details about the step-by-step template in the requirements to make sure that is clear to all.

**Comment by ncksllvn** [comment]
If it helps answer any questions, the veteran banner on the homepage is in a picture element -

![image](https://user-images.githubusercontent.com/1915775/92284082-4adf2380-eecf-11ea-8476-66b57693963f.png)

> given that scenario in the last bullet: I know people can enlarge on their phone, but if the image size is so small that it starts to get pixelated and people can't see details...thats not good. Any idea if that could be the case with the mobile images we get? If so, do we need to give some kind of special "zoom" or "enlarge" option (e.g. how you zoom in to details on an e-commerce product image)?

I think that is a valid scenario, and that would be part of the balance between image size and image quality. We'll probably have to do this case by case, determining when it's important a picture not pixelate when zoomed in on.

> lastly, can we do use lazy loading to optimize mobile performance, especially if people upload a bunch of images on a page?

We are set up to lazy load. We actually do this on the homepage as well. The stories on the homepage contain images that aren't loaded until they are scrolled into view. You can see the image download on the fly when you scroll, or if you're watching your network panel in devtools.

![image](https://user-images.githubusercontent.com/1915775/92284300-b4f7c880-eecf-11ea-9acd-d4e9654a93ac.png)

**Comment by oksana-c** [comment]
@andaleliz @kelsonic @ncksllvn 

Every image that is uploaded in the CMS is stored in a variety of sizes listed in the table below for easy reference.

style name | size
-- | -- 
original | original
 1:1 square medium thumbnail | 240×240
 2:1 medium thumbnail | 480×240
 2:3 medium thumbnail | 320×480
 3:2 medium thumbnail | 480×320
 7:2 medium thumbnail | 1050×300
Large (480×480) | 480×480

**Comment by andaleliz** [comment]
[Mock-ups in a mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1599749914789/b6142b86cf53c35d5dd632a0a4b406aed6fe0f11). Scheduled review w/ Jennifer Strickland + Ryan Thurlwell

**Comment by andaleliz** [comment]
@jenstrickland  and @rtwell I put the [latest version of the step-by-step mobile design in UXPin](https://preview.uxpin.com/192f5be770c74272f782765a19a196aed0a4a588#/pages/132512748/documentation/no-panels?mode=i) for you to check out.  This has the same `show all` treatment/behavior as the table design.

@jenstrickland similar to the table designs, interested to know if there are other a11y considerations that need to be called out in the documentation.

@kelsonic is all of this FE work, or do I need to pull in the CMS folks to get their eyes on this too?

I'm planning on dropping into the VSP office hours tomorrow to discuss my modified accordion component. Not sure if that needs an official collab cycle meeting or how that fits into the review process.

**Comment by jenstrickland** [comment]
@andaleliz — for the `show/hide all` I recommend including the link to the gov.uk implementation we are using in the documentation, so the devs have an example: https://www.gov.uk/apply-online-for-student-finance 

It uses the same `aria-expanded` pattern we use for accordions, so it should be fine.

Using the step number ahead of 'details' is an excellent way of being specific.  I wonder if the link would benefit from the addition of an `aria-labelledby` attribute that pairs with the `id` of the step heading. 

I'd like to have a design review with VSP — particularly design, content, and accessibility — before this is built as a component in the CMS. I wonder if it should be reviewed by the design system council, as well (wondering what Ryan thinks here).

**Comment by andaleliz** [comment]
Excellent, I'll update the docs. Thank you @jenstrickland !

>I'd like to have a design review with VSP — particularly design, content, and accessibility — before this is built as a component in the CMS. I wonder if it should be reviewed by the design system council, as well (wondering what Ryan thinks here).

Yeah, that's what I wasn't sure about and was just going to pop into the VSP office hours to see what the review process would be. I can just go head and request a meeting - would this be a design intent review? I can use that GH template to request.

**Comment by jenstrickland** [comment]
@andaleliz My hunch is you are correct and the design intent would be logical. I think @andreahewitt-odd may be better positioned to indicate which, since VSP oversees the selection of checkpoints.

**Comment by andaleliz** [comment]
@jenstrickland I reached out to on #vfs-platform-support so we'll go from there!

I'm going to close this out since the only change is the addition of the `show all` and Ryan was on board with everything else.  Ryan, I'll re-open if there is anything else you want to see addressed.
