### ISSUE TITLE
[Design] - MVP Learning Center 1.1 - Mobile template for checklist 

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13037]
Create mobile version of a checklist page.  This will be for MVP 1.1

The checklist page can include h1, intro text, alert info box after the intro text (optional), section heading (optional), section blurb text (optional); and then the checkbox labels (which are plain text up to 300 chars with spaces).

No limit to # of checkboxes. Authors can also break up the checklist into chunks, organized under section headings 

[Example 1](http://preview-prod.vfs.va.gov/preview?nodeId=9544) 
[Example 2](http://preview-staging.vfs.va.gov/preview?nodeId=6924)

## Acceptance criteria

- [ ] create mobile version of check template MVP 1.1
- [ ] review w @jenstrickland  
- [ ] @andaleliz, @rtwell, and @jenniferlee-dsva to review

**Comment by jenniferlee-dsva** [comment]
Does this one need a special mobile template?? I thought you did an audit previously of which template seemed like it needed a special mobile design, and this one was not one of them. (I could be wrong though and I can't find that table you created.) 

Liz - to answer your questions above: 

can content authors put anything other than an intro, list of checkboxes and section headings in this template?
- they can include h1, intro text, alert info box after the intro text (optional), section heading (optional), section blurb text (optional); and then the checkbox labels (which are plain text up to 300 chars with spaces). 

is there a limit to how long the checklist can be?
- no. they can also break up the checklist into chunks, orgainzed under section headings [(like this)](http://preview-prod.vfs.va.gov/preview?nodeId=9544)

**Comment by jenniferlee-dsva** [comment]
I see the audit you did refereneced above. Thx for keeping track - nevermind!

**Comment by andaleliz** [comment]
Thanks Jen, updated the description w/ that info.

**Comment by andaleliz** [comment]
I need some more information in order propose a design that supports the way data comes in from the CMS for this template.  

@kelsonic, @oksana-c  and/or @ncksllvn, can you share any information about how data is structured for this checklist template? Is it all one big WYSIWYG dump?  Drupal screenshots might be helpful so we can see it from the author perspective.

**Comment by ncksllvn** [comment]
_WYSIWYG dump_ is a term I'm gonna start using now 😁 I don't see any design limitations we would run into based on the data behind this layout. The gist of the data is that we get a list of "checklist sections", each containing a heading and a list of "checklist items". I don't think it gets any more ideal than that.

**Comment by jenstrickland** [comment]
Will the checklist always be preceded by the same content structures, or could it be the first item under a h1? 

I ask so that the semantic markup will be flexible enough to work regardless of where it is placed (thinking that a description list structure may be useful, for example).

**Comment by andaleliz** [comment]
@jenstrickland based on [Jen's comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13037#issuecomment-723277186), I think the `h1` will be followed by an intro section (pretty sure it's a `<p>`), and then a checklist could be the first item under the intro.  

It is also possible that the checklist will be preceded by an optional section heading (I'm thinking this should be an `h2`) and/or an optional section blurb text (thinking this should be a `<p>`) element.

@ncksllvn you said:
>The gist of the data is that we get a list of "checklist sections", each containing a heading and a list of "checklist items".
Do you know if the heading, optional blurb and checklist items come through as separate values, so we can split them out (and wrap the heading in an `h2`, and the optional blurb in a `p`)?

**Comment by jenstrickland** [comment]
@andaleliz Thanks! That clarifies why I'm suggesting that a description list is likely to be a good semantic structure so that if there is a preceding h2 or not, the content will still be useful. The alternative is that the checklist heading would be an h2 and a list would be applied to the checklist items, then aria used to associate them. The description list does all of that without any aria spackle and allows you to style it as you want.

**Comment by ncksllvn** [comment]
> Will the checklist always be preceded by the same content structures, or could it be the first item under a h1?

The checklist could/will be preceded by the page title (h1), alert banner, and links styled as buttons. Right now, in our (very rough) template, we also have an H2 that is hardcoded to always say "Checklist" but that is being removed. After all that, we get into the checklist(s).

We can probably check for the existence of optional values in order to render a certain heading tag if that's what you're asking? We do that on Multiple FAQ pages where the section headers are optional - when a section header is present, questions are presented in H3s; when not present, questions are presented as H2s.

Does this answer your question?

> Do you know if the heading, optional blurb and checklist items come through as separate values, so we can split them out (and wrap the heading in an h2, and the optional blurb in a p)?

If I am following correctly, they do come through separately.

---

<details>
<summary>
Here's an example data structure representing a page of type `checklist` - its id, entity bundle (type of page), and its checklist.
</summary>


```json
{
          "entityId": "6924",
          "entityBundle": "checklist",
          "fieldChecklist": {
            "entity": {
              "fieldChecklistSections": [
                {
                  "entity": {
                    "fieldSectionIntro": "This is where the intro text will go for this section",
                    "fieldSectionHeader": "Checklist header section here",
                    "fieldChecklistItems": [
                      "Name of national cemetery you’re requesting"
                    ]
                  }
                },
                {
                  "entity": {
                    "fieldSectionIntro": null,
                    "fieldSectionHeader": "Deceased Veteran’s details:",
                    "fieldChecklistItems": [
                      "Deceased Veteran’s full name",
                      "Deceased Veteran’s home address",
                      "Deceased Veteran’s Social Security number",
                      "Deceased Veteran’s date of birth",
                      "Deceased Veteran’s date of death",
                      "Deceased Veteran’s branch of service",
                      "Deceased Veteran’s military rank",
                      "Deceased Veteran’s marital status at time of death"
                    ]
                  }
                },
                {
                  "entity": {
                    "fieldSectionIntro": null,
                    "fieldSectionHeader": "Funeral home details:",
                    "fieldChecklistItems": [
                      "Funeral home name and ID number",
                      "Funeral home’s address and phone number",
                      "Funeral home contact person’s name and email"
                    ]
                  }
                },
                {
                  "entity": {
                    "fieldSectionIntro": null,
                    "fieldSectionHeader": "Surviving spouse or family details: ",
                    "fieldChecklistItems": [
                      "Surviving spouse’s full name (or next of kin’s)",
                      "If next of kin, relationship to deceased Veteran",
                      "Spouse/next of kin’s Social Security number",
                      "Spouse/next of kin’s date of birth",
                      "Spouse’s Veteran status",
                      "Spouse’s request for a set-aside grave",
                      "Did the deceased Veteran have adult dependent children who are mentally or physically disabled?",
                      "If yes, their full name, Social Security number, and date of birth"
                    ]
                  }
                },
                {
                  "entity": {
                    "fieldSectionIntro": null,
                    "fieldSectionHeader": "Interment (burial) details:",
                    "fieldChecklistItems": [
                      "Type of interment (cask or urn)",
                      "For cask, liner type (standard government or private vault)",
                      "For case, liner size (small 60 X 20 X 18; regular 86 X 30 X 28; extra-large 86 X 38 X 28; oversize 88 X 34 X 27; jumbo 98 X 44 X 30) "
                    ]
                  }
                },
                {
                  "entity": {
                    "fieldSectionIntro": "You will be asked to respond to the following federally required questions.",
                    "fieldSectionHeader": "Legally required details:",
                    "fieldChecklistItems": [
                      "\"To the best of your knowledge, has the decedent ever committed a capital crime?\"",
                      "\"To the best of your knowledge, has the decedent ever been convicted of a sexual offense of which he or she was sentenced to a minimum of life in prison?”"
                    ]
                  }
                },
                {
                  "entity": {
                    "fieldSectionIntro": null,
                    "fieldSectionHeader": "Military honors and emblem of belief details: ",
                    "fieldChecklistItems": [
                      "Request for military honors (yes/no)",
                      "Branch of service ",
                      "Request for committal service (yes/no)",
                      "Request for a religious emblem of belief for the marker (yes/no/not at this time)",
                      "Selection of the emblem of belief"
                    ]
                  }
                },
                {
                  "entity": {
                    "fieldSectionIntro": null,
                    "fieldSectionHeader": "Scheduling details:",
                    "fieldChecklistItems": [
                      "Method of delivery to the cemetery",
                      "Name of individual who is scheduling military honors",
                      "Preferred date and time of the scheduled service"
                    ]
                  }
                }
              ]
            }
          }
        }
```
</details>

**Comment by jenniferlee-dsva** [comment]
@andaleliz - here is an example of the CMS edit fields that appear below the H1, intro text. The content fields above the global bottom layers are:

H1
Intro text limited rich wisywig up to 1,000 chars
(Optional) Alert
CTA button(s)
(Optional) Checklist section header
(Optional) Checklist section blurb text
Checklist item label (can have as many items as needed)
(Optional - Can include additional checklist sections.)


![image](https://user-images.githubusercontent.com/43381063/98979828-d685b980-24e9-11eb-8920-93eb6b39a4fa.png)

**Comment by jenniferlee-dsva** [comment]
@andaleliz - there is currently a CMS content field FE bug that you should be aware of: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15915 

It doesn't affect the design per se, but it's important to know that the "Checklist" H2 that currently appears in the preview examples above will not always say "Checklist." 
1/ It would be the optional checklist section header that will appear in that field. If used, the FE should dynamically display it as an H2. 
2/ If a checklist section heading is not used, the FE will just show the list of checklist items. These are just normal body text font.

**Comment by rtwell** [comment]
Mobile:

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/d8e8cc41-b13e-4fdc-9cf5-606cd1fdb9b4)

**Comment by jenniferlee-dsva** [comment]
@rtwell - per above comment to Liz re the CMS bug rn - all of the headings will be optional and when used, they will all be H2s. Sorry about one more round - could you make one more v. showing the correct header class, so FE don't get confused? 

![image](https://user-images.githubusercontent.com/43381063/99541813-4929e580-297f-11eb-8d0f-d2a5abd77da9.png)

**Comment by jenstrickland** [comment]
@rtwell What happens when a user selects "Learn how to schedule a burial"?  If it goes to another page, it would be better if it was a link instead of a button.

For the download worksheet PDF link, that should probably use the download file pattern, for consistency as well as the functional features in the link pattern (download and type attributes) and include the file size if possible.

**Comment by jenstrickland** [comment]
Those H2s should be `<legend>` elements for semantic markup grouping the checkboxes beneath them.

**Comment by jenniferlee-dsva** [comment]
@jenstrickland - I don't know what legend elements mean. Whatever it needs to be is fine. I'm just pointing out that there is no H2 section header and another type of checkbox section header. That was a bug in the CMS, which they are fixing. The correct FE content fields are per this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13037#issuecomment-726253361

**Comment by andaleliz** [comment]
Removing myself from assignees since @rtwell is tackling this now.

**Comment by rtwell** [comment]
fixed the comp above 👆  FYSA I labeled them as h2s so folks know how they should be styled, not how it should be codified. 

to answer your question about the CTA @jenstrickland — these CTAs can point to any page on va.gov, but we will provide guidance for their usage. We _do_ use CTAs to link to pages on VA.gov—we cannot link users directly into a tool, we send them to a tool landing page, or a page where they can determine if they need to take an action. or maybe we have to route folks to something like myHealtheVet. That said, I think its ok for CTAs link to pages, and the drupal guidance will recommend reserving CTAs for directing users to actionable pages/tool/etc

**Comment by jenniferlee-dsva** [comment]
This design ticket is complete with Ryan's mobile mockup above. Closing and linking mockup to the FE ticket #15617 .
