### ISSUE TITLE
Update 508 docs to reflect move from Nightwatch to Cypress

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#13030]
From Megan:  these docs mention Nightwatch, do they need to be updated to reflect our use of Cypress for tests moving forward? Do other things (tests, etc) need to be updated before docs are updated? Or are we not planning to move Nightwatch axe checks to Cypress?

- [x]  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/testing/508-automated-testing.md
- [x]  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md
- [x]  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md

**Comment by 1Copenut** [comment]
@andreahewitt-odd I had a chance to review these all last week and updated docs with Cypress current practices. We should be good to close this issue.

**Comment by 1Copenut** [comment]
@shiragoodman This has been completed. Moving to close.
