### ISSUE TITLE
Is `GET connected_applications` handling non-Vets correctly?

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#13044]
When a user who _is_ in MPI/MVI, but who is _not_ a Veteran, calls the `GET connected_applications` endpoint, the response is a 404:

```
{
  "errors": [
    {
      "title": "Record not found",
      "detail": "The record identified by 084ea86d33eb4db5a84d57fe6a03a844 could not be found",
      "code": "404",
      "status": "404"
    }
  ]
}
```

This has been replicated with two non-Veteran users in the production environment. We also confirmed that a user who is a Veteran does _not_ get this error. 

## Next steps

Answer these questions:
- Is this the expected behavior? Is so, should the Swagger docs be updated to reflect this?
- Should we be blocking non-Veterans from accessing the Connected Apps feature even if they are in MPI/MVI?

**Comment by sanlouise** [comment]
We can close out this ticket. After discussions with the team responsible for connected apps, we now treat this error as an empty array on line 46 in `src/applications/personalization/profile/components/connected-apps/ConnectedApps.jsx`.

[This ticket](https://github.com/department-of-veterans-affairs/vets-website/pull/14272) closed the issue.
