### ISSUE TITLE
CT Filter: Create Benefit Question Enhancements Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13041]
As a developer, I need to create a feature flag that can be used to turn on and off CT benefit filter question enhancements so that it can be delivered to production in a timely manner.

## Assumptions:
1. Feature flag for CT Filtering will need to be available in the following repos: vets-api, vets-website

## Tasks
1. Follow feature flags documentation to create front-end CT filter feature flag.
2. Follow feature flags documentation to create back-end CT filter feature flag.

## Acceptance Criteria
1. The "gibctBenefitFilterEnhancement" feature flag is created and available in all environments.
2. The description is "Comparison Tool Search Results Benefit UI Enhancements to improve usability"
3. The styling changes for the following questions on the CT Search Results page are behind this new feature flag instead of the filter feature flag:
    a. What's your military status?
    b. Which GI Bill benefit do you want to use?
    c. Cumulative Post-9/11 active-duty service
    d. How do you want to take classes?

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

2. Current staging styling - when flag is on
<img width="268" alt="staging_sr_style_update" src="https://user-images.githubusercontent.com/48260534/91765358-d8a4d100-eba6-11ea-90b5-20fd7ed8c177.png">

3. Current prod styling - when flag is off
<img width="313" alt="ct_prod_sr_benefits" src="https://user-images.githubusercontent.com/48260534/91765357-d80c3a80-eba6-11ea-8c4a-2fe0870fe934.png">

**Comment by hughes-dustin** [comment]
**Vets-api**
 branch: bah-13041
 PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4824

**vets-website**
 branch: bah-13041
 PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14090

**Comment by delli-gatti-michael** [comment]
## Feature Flag Off
![Screen Shot 2020-09-02 at 1.59.39 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/055a103c-7c07-4eb7-a340-eb157680f1d9)

---

![Screen Shot 2020-09-02 at 2.40.35 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6dc6503a-a2e9-4bd3-aa58-ab3fa1500d2e)

---

![Screen Shot 2020-09-02 at 2.40.45 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/47c65c07-a1cf-40ae-91b8-9fde25776f74)

## Feature Flag On
![Screen Shot 2020-09-02 at 2.12.38 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2d134d01-f312-4fbb-9928-611a6ccec0a9)

---

![Screen Shot 2020-09-02 at 2.13.16 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/7fa4e783-db56-4d66-b27d-3a80237603b5)

---

![Screen Shot 2020-09-02 at 2.16.06 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/811fbcd5-f1bf-41de-95cc-df6706c69063)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
The flag is working correctly Staging. Closing this issue
