### ISSUE TITLE
Access for Liani Lye

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#13040]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Liani Lye
- Please Provide your email.
   > liani@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Content/IA - Product Manager [Ad Hoc]

- Requesting SSH key authorization?
   > YES

- What is your **public** SSH key?
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+bk9V0rmJlk8HhoNpEQA5NpA/qCbk+jOx1mlW9tO/fn6Vgxq7fD31j7QNnOyWbVLcjpteEfPqIX1fOKlTHVeEj8Ph0kSsVDvRwSZyWM/OwtHiqRsEyjKJW260ZqNS1rLjMy/c6mj88nR0g363WL7/5BGf5/wyUM+maOESuKF/7TJDUUPBuVbu6zDcScciwGFCbQ43XPXirARDU72hcLll9W0pBxQtCAEO1s/vtEipq61W4gyqQvb5+yofRjvOz1dyY8RKoFGkjI9mWXcwUrSzpo0rJImbWe/fov4ypBWvwlUxJfLI9ioFrnWIXZkv2XEWRWa1sps2Xip7DhpQ33iIhD7mAHCYMfgn+S1iNL1jU/XI7STM9DIb89Qa/M9doycUzYnuFJkDWaxT6B9+6j+WycSHbS0u6GzWzW4hkASswsSaYv3JhDuJiSZNd8Y11tM4m8o45pUEaGsnlK4/VW+7qFbWchtY6RWAmHoI6ZEyY361gxcoOkZRX9bLn2Mfr2qhLuMB+kP6Ry+TOCvKGW28T2NTEq2P/72/SjQTbIGrWSwCWYVJsHcP6UPkee2furJac9akJcYKX1hw/H0sLPkv7pKiLtf3EiYmMc8MdCOe1EfvVgMtM8uNpyXDxKNR47Xve0RBmkZ768tUegUSrmdfbIn+XtS2P/JmhmppgXs7tQ== lye.liani@gmail.com
```

- Grant AWS Console access?
  > YES
- What AWS services do you need access to and why? 
  > Not sure which services, just want to dogfood developer docs (particularly feature toggles vs review instances, per Andrew Gunsch's recommendation)

**Comment by jsev-io** [comment]
Hey @lianilychee, from this request, it doesn't appear you'll need AWS access... No documentation lives there.

**Comment by jsev-io** [comment]
@lianilychee SOCKS access granted - please test that you have access to the proxy. Will confirm with you in Slack

**Comment by jbritt1** [comment]
### For AWS Access:

User: Liani Lye
COR: Jeff Hayter
Approval needed: @Jeff-Hayter

**Comment by lianilychee** [comment]
in process of configuring SOCKS proxy in order to confirm that I have access.  Will post back here to close the loop once confirmed.  Currently troubleshooting with Julian via Slack.

**Comment by jsev-io** [comment]
SOCKS Access confirmed.

**Comment by jhouse-solvd** [comment]
@lianilychee Do you now have all of the access that you need? If not, can you let me know what remains? Thank you!

**Comment by lianilychee** [comment]
@jhouse-solvd I am good on SOCKS, so from my perspective, this can be closed.  But wasn't sure if Jeff needed to grant approval.

**Comment by jbritt1** [comment]
Yep, for AWS we will have to await approval from Jeff. Have you submitted an e-QIP yet Liani?

**Comment by jbritt1** [comment]
So if you are still requesting AWS access the ticket will remain open until approval is granted.

If no longer requesting AWS access, we can close.

**Comment by lianilychee** [comment]
Got it.  My eQIP was approved last week.  I would still like AWS access!

**Comment by jbritt1** [comment]
Perfect, once @Jeff-Hayter confirms / approves we will be happy to get you squared away!

**Comment by Jeff-Hayter** [comment]
@jbritt1 I approve, thanks.

**Comment by jbritt1** [comment]
Account created and temporary credentials passed to user at this time.
