### ISSUE TITLE
Design feedback - Design intent Collaboration [Address Project Form 10-10EZ] 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#13048]
- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

**Must**
- No must feedback at this moment

**Should**
- No should feedback at this time 

**Consider**
- Consider on [this page](https://vsateams.invisionapp.com/share/RPYKB0VNA68#/screens/429934942) you can add a light blue background alert around the info “Note: We are using information we have on your…” 

**Definition of Done:**
- [x] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by jonathanjnelson** [comment]
Thank you for the feedback. You can see updated designs [here](https://vsateams.invisionapp.com/share/NJYZ5YSYF8Q#/433719998_Unathenticated-Blank_-v-2-1)

**Comment by CrystabelReiter** [comment]
Thanks Jonathan! Closing now
