### ISSUE TITLE
Iteration on VVC Appointments

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13046]
### User need:
Not all VVC appointments are the same. Veterans may need to go into a Facility or to an ATLAS location in order to have their VVC appointment because they do not have a digital device or the internet where they are. 

Right now, we treat all the following VVC appts (kinds) the same except for the last kind (GFE):
`"ADHOC",
  "NO_VA_ID",
 "CLINIC_BASED",
 "MOBILE_ANY",
 "STORE_FORWARD"`
https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/9632623c-2d69-45b3-aded-d8c3d9785856

Specific GFE
` "MOBILE_GFE"`
https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/7c4964ae-13c9-453b-bf4a-f30a1f189ccd

### What we need to do:
- Properly handle all of the following VVC appt kinds: (ignore the yellow areas)
![Screen Shot 2020-09-09 at 1.49.06 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/68a57be0-8730-4542-944f-3e10d42863ec)
- Iteration on "How to join" language to something similar to "To Join your appointment click”. Per stakeholders - How to join really belongs down with "How to prepare for your appointment" instructions. Currently layout is misleading/not actionable enough.
- Apply appropriate instructional content based on VVC appt kind (ex. - need to provide some reference to "A room with a computer will be available at the location at the time of your appointment." for ATLAS associated VVC appts) Need to do this for all appt kinds:
      - Ad Hoc
      - Ad Hoc - ATLAS Associated
      - Clinic-Based
      - Group Video
      - Mobile Any
      - Mobile Any - ATLAS Associated
      - Mobile GFE
- For Store Forward appts - these should display like a regular booked VA appointment
- For all appointments we need to consider adding 'provider information' where helpful - right now all VVC appts are had to tell apart 

### Open questions:
- ~Do we need to handle/show "Group Video" in VAOSR? Notes say it's 'email only'~ as of 9/1 - "yes, group video should be shown to Veteran."
    - As a note, Currently Kind Group does not have a link to VistA scheduled appointments.
    - When the Veteran views appointment details the VMR link will be available as for other “video to home” workflows.
- ~Do we need to handle/show "Store Forward"? Ron M. mentions they treat this "like in person really is just direction to go to the facility."~ - As of 9/1 - Yes, these need to be shown, however these are not like traditional VVC appts. From Ron M.:
     - Since the Veteran has to physically go to the VA facility. The Veteran display as I recall from past discussion was simply to show the VistA scheduled appointment information just like a traditional in person clinic appointment.
     - There is no link for the Veteran to join or other information. From the Veteran perspective it is an appointment they attend in person.

 

### Outcome/measurement
- By addressing and properly displaying all video appts - we'll accurately direct Veterans to where they need to go for their VVC appt (either in home, in facility, or at ATLAS location)

### Definition of Done:
- All VVC appt types are accounted for appropriately
- All necessary VVC appt data is displaying as should (instructions, facility/ATLAS location)

### Assumptions:
- We will continue to use the VVC request design as is
- We will repurpose existing VVC booked appt design with slight iteration to meet new VVC appt needs

**Comment by jbalboni** [comment]
General video appointment information:

- Provider first/last
- Provider email
- Provider phone
- Provider timezone
- Provider location
   - VA or NonVA
   - VA site code
   - timezone

ATLAS appointment information:
- Location address 
- Confirmation code
- Site contact
   - Name
   - Phone
   - Email
- Site code

Group video information:

We don't appear to get any information indicating it's a group appointment

**Comment by lenaecb** [comment]
@jbalboni - to confirm for 'group video' we do get that type, just not associated data with it? I think that's ok since it should be held 'in home.' 

And yea on getting provider first/last name! That would be really helpful in distinguishing these visits based on 'who they are with.'

**Comment by jbalboni** [comment]
@lenaecb Correct, I created a group visit and I see the appt in the list, but nothing says it's a group visit as far as I can tell.

**Comment by rtwell** [comment]
ok gang this is my first stab at delineating these appointments. 

- as you can see, adding some type to the header isn't enough
- these don't have to be taken at home, right? i assume a Veteran could take a video appointment that is private and has stable connection
- im leaning toward the card style with the alert, as it seems clearest to me, but my good these "cards" are getting HUGE and clunky. i know that rethinking the appt list is in the near future, so I'll have to deal with it for now 😄 
- these obviously need some content love from @peggygannon 

![image](https://user-images.githubusercontent.com/12564977/92237375-43932800-ee85-11ea-8580-760ebe92aff3.png)

**Comment by lenaecb** [comment]
A few comments/feedback:
- For confirmed VVC appts - we do not display any additional 'reason for appt' 'booking notes' so that won't show on cards as you have outlined here 
- For video from home appts - I would keep it simple and only have the line about joining via secure connection
- Also for video from home - we need a way to distinguish these for Veterans - this has been ongoing feedback from Veterans that they can't tell the VVC appts apart 
     - My suggestion on improving this is/was: use is 'provider' information; so we could say something like 'Your VVC appointment will be with [Provider]'
- I believe we need consistency in labeling all appts - we have VA Video Connect at Facility or at " " at ATLAS - I would advocate for  _VA Video Connect from Home_ or _VA Video Connect from Home/Mobile_ (this latter option is also consistent with recent MHV deploy of VVC appts) for VVC appts from home
- I do not think we need to have an option for iPhone because instructions on downloading the iOS app is already a part of the 'prepare for video visit' instructions
- Also, I think we need rearrange content location and the 'join session' button because:
   - 'How to join your virtual appointment' directs user to 'join session' button not to the content above it (the new bullet you have added) or our the instructions below it
   - instead we could consider lumping all preparation content (ie, instructions) into a shared section, but still hide the full 'prepare for video visit' instructions
   - Then could provide 'join session' button underneath
   - I think this helps flow a bit...
- we should all-caps ATLAS as it's an acronym of a VA program (keep consistency with that branding)


cc: @rtwell @peggygannon

**Comment by rtwell** [comment]
hmmm instead of calling them "at home" appointments, I wonder if we should call them "online appointments" or something. The more I dig into this, the more our choice of language is going to be the biggest factor.

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/92488108-1cf22b80-f1bc-11ea-9805-9dbd9d289a96.png)

**Comment by lenaecb** [comment]
@rtwell nice! I loving this latest iteration. 

@peggygannon - content thoughts/input here?

**Comment by rtwell** [comment]
i'm still leery of "at home" because it really not about taking the appointment at home per se, but i have no idea how else we might talk about it.

**Comment by peggygannon** [comment]
@rtwell and @lenaecb the layout looks great. 

I have a couple of questions: 
1. will users know what "ATLAS" is/stands for? wondering if would be the first time they see this term and if we should define/spell out? 
2. I don't recall discussing the video visits with VA device on our kickoff call. Do users typically have a VA device at home? or do they need to be **at** a VA facility to use a VA device? 
3. I also recall discussing that we *may* need to tweak the content under "Prepare for video visit" link.  Is that true? 

And a couple of notes: 
- I used VA Video Connect when referring to the appointments to make this consistent with how we talk about video appointments across all of VA.gov
- You'll see I added this line to all of of the video appts content: You can join the meeting up to 30 minutes before the start time,"  in an effort to keep the language consistent across all of type of video appts. 

-----

At home:

**Video appointment at home**

How to join your VA Video Connect appointment
You can join this video meeting from your home or anywhere you have a secure Internet connection.  You can join the meeting up to 30 minutes before the start time. 

You'll be meeting with
{provider name}


-------

At VA facility

**Video appointment at a VA location**

How to join your VA Video Connect appointment
You must join this video meeting from the VA location listed below. You can join the meeting up to 30 minutes before the start time.

You'll be meeting with
{provider name}

-------
With VA device

**Video appointment using a VA device**

How to join your VA Video Connect appointment
You can join this video meeting using a device provided by VA. You can join the meeting up to 30 minutes before the start time.

You'll be meeting with
{provider name}

----
At ATLAS location


**Video appointment at an ATLAS location**

How to join your VA Video Connect appointment
You must join this video meeting from the ATLAS location listed below. You can join the meeting up to 30 minutes before the start time.

You'll be meeting with
{provider name}

**Comment by rtwell** [comment]
hi @peggygannon i think i can clarify a couple of these:

for 2: there are 2 types of "***VA*** video appointments". The VA may have provided equipment for a Veteran to use, OR they may have to physically go to a VA facility and use equipment the facility has on hand. If you look at my first comps, i labeled them "GFE" (government furnished equipment) and "VA facility", if that helps.

> You'll see I added this line to all of of the video appts content: You can join the meeting up to 30 minutes before the start time," in an effort to keep the language consistent across all of type of video appts.

The 30 minute rule isn't necessarily true across _all_ VA Video appointments, particularly if you have to go to a physical place. I believe the 30 minute rule is based off of the fact that the join link becomes active 30 minutes before the meeting. 

I see what you're driving at regarding "How to join your VA Video Connect appointment", but I would also like to keep these as short as possible (on mobile these appointment cards get pretty tall. HMmmmmm 🤔

**Comment by lenaecb** [comment]
@peggygannon - see notes below to your Qs:
1. will users know what "ATLAS" is/stands for? wondering if would be the first time they see this term and if we should define/spell out?
- The email that is sent to Veterans says _"This video appointment is at an ATLAS (non-VA care site) location. A room with a computer will be available at the location at the time of your appointment."_
- I would assume that yes, they do know what it is? Spelling out "Advancing Telehealth through Local Area Stations" feels just as confusing. 
- ATLAS appts are scheduled with VCM which means that a Scheduler should be talking with the Veteran about the VVC appt being at an ATLAS location when booking. 
2. I don't recall discussing the video visits with VA device on our kickoff call. Do users typically have a VA device at home? or do they need to be at a VA facility to use a VA device?
- This was already accounted for in the UI which is why we didn't talk about it specifically in our meeting (or ran out of time)
- the VA device is va registered device to Veterans that they will use in their home (or somewhere outside of VA facility) - ex. ipads distributed to Veterans with launchpad app (which include VVC app) or VA staff who use VA services (so have VA issued GFE or mobile phones)
3. I also recall discussing that we may need to tweak the content under "Prepare for video visit" link. Is that true?
 - I think was about the change that Ryan already made where currently we have "how to join your appt" is right above the 'join session' button and that is/was misleading. 
- Instead any brief instruction we give about these appts should go together. Ryan's latest mock accounts for that. 
- the 'Prepare for video visit' do not need to change/are part of the larger virtual video ecosystem

**Comment by peggygannon** [comment]
hello,  @lenaecb and @rtwell thanks for your clarifications! 

Regarding, ATLAS, I don't think we need spell out.. I just wanted to make sure the Veteran had some earlier context about what an ATLAS location is. Here are updates based on your answers above. 


At home:

**Video appointment at home**

How to join your video appointment
You can join this video meeting from your home or anywhere you have a secure Internet connection. You can join the meeting up to 30 minutes before the start time.

You'll be meeting with
{provider name}

-------

At VA facility

**Video appointment at a VA location**

How to join your video appointment
You must join this video meeting from the VA location listed below. 

You'll be meeting with
{provider name}

------

With VA device

**Video appointment using a VA device**

How to join your video appointment
You can join this video meeting using a device provided by VA. 

You'll be meeting with
{provider name}

------

At ATLAS location

**Video appointment at an ATLAS location**

How to join your video appointment
You must join this video meeting from the ATLAS (non-VA) location listed below. 

You'll be meeting with
{provider name}

**Comment by rtwell** [comment]
@peggygannon love it!

![image](https://user-images.githubusercontent.com/12564977/92630323-ac234000-f29d-11ea-8d7a-f6758369290f.png)

**Comment by lenaecb** [comment]
For the GFE should we consider "Video appointment using _your_ VA _registered_ device" ? @peggygannon @rtwell

**Comment by peggygannon** [comment]
@lenaecb I think the head should still be short, but how about we can add that into the body of the message, so like this: 

With VA device

**Video appointment using a VA device**

How to join your video appointment
You can join this video meeting using your VA-registered device.

**Comment by lenaecb** [comment]
Love it @peggygannon!

Also, @rtwell - for ATLAS appts a Veteran gets a appointment code. I think we should supply this code as part of the appt in case they use their phone to look up the appt details/don't have their email handy. 

For reference here's what is sent via email about ATLAS appts:
_"This video appointment is at an ATLAS (non-VA care site) location. A room with a computer will be available at the location at the time of your appointment.
 
Location: Springfield American Legion
6520 Amherst Ave
Springfield VA 22150
**Appointment Code: NMCQR6**
You will use this code to find your appointment using the computer provided at the site.
Please either save the attached invite to your personal calendar or print this email to take to the appointment."_

Lastly, for all non-home appts, I am dropping the 'prepare for visit' instructions because they are tailored to in home visits?

**Comment by rtwell** [comment]
i think we need some standardized language for each type of appointment that requires unique instructions. if 2 or more utilize the same instructions, great, but if they are unique, the instructions should match, i would think

**Comment by lenaecb** [comment]
I am not sure I follow @rtwell 

The instructions we show now are dependent on if they come from VCM booking or TMP (another system used for booking). VCM has a 2 sets of instructions and they are tailored to VVC appts that the Veteran is logging into on their own. 

I am recommending that we do not show these instructions for @ {location name} appts because the process for getting online is different than described in the VCM instructions for 'in home.'

Also - can you add in the 'confirmation code' for ATLAS appt? Don't want that to get lost.

**Comment by rtwell** [comment]
yeah I'm suggesting that whichever VVC appts have the same instructions, they should use the same instructions across the relevant appts, and if there is a need for a different set of instructions (like the facility example) we provide the appropriate language. I like the idea of instruction/appointment info always living in the same location on our cards.

**Comment by rtwell** [comment]
Ok updated comp with all 4 VVC appointment types:

![image](https://user-images.githubusercontent.com/12564977/92786854-9a619b80-f376-11ea-8ee8-7de122561387.png)

**Comment by peggygannon** [comment]
@rtwell  @lenaecb  hello, for the VA device appt, I think we wanted to go with this latest content (calling out that the device is *VA-registered*

**Video appointment using a VA device**

How to join your video appointment
You can join this video meeting using your VA-registered device.

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/92919468-8c575d80-f3fe-11ea-84ff-f4ae17a41acb.png)

**Comment by lenaecb** [comment]
Remaining VVC kinds to account for:
- Group VVC appointments - we believe come in as individual VVC appointments - confirm no way to show 'group'
- Store_Forward - these are actually in VA facilities - how should we show these appointments?

Specific issues remain below:
- #13062
- #15294

**Comment by ldelacosta** [comment]
We will create a new epic if this is a priority for the Appointments team. Closing out the ticket. cc: @JRRoof @outerpress
