### ISSUE TITLE
"In Home" VVC Appt (Ad Hoc - Single & Mobile_Any)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13051]
Right now we are treating all VVC appts the same. They are not the same.

### Acceptance Criteria: 
- **all Ad Hoc - Single and Mobile_Any VVC appointments should display "Video appointment at home"** under the VA Video Connect card label (where date/time used to show)
   - Any `appointmentKind` other than `CLINIC_BASED` and `MOBILE_GFE` and that don't have a `tasInfo` object
 - we've re-arranged the content for better flow and direction (see mock)
- provider name should be populated (based on VCM designation) with "You'll be meeting with"
- if no provider name, do not display provider section
- all other logic existing for VVC cards (when button displays, 'prepare for video visit,' 'veteran not able to cancel in VAOS') still applies

### Latest mock here: ([Full mock here)](https://user-images.githubusercontent.com/12564977/92630323-ac234000-f29d-11ea-8d7a-f6758369290f.png)
![Screen Shot 2020-09-09 at 1.18.50 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/bdcdf792-8cf4-4459-84a2-9ce390b596fc)

Supporting email sent for ADHOC and Mobile Any VVC appts - [https://app.zenhub.com/files/133843125/8f7289b2-047f-47aa-b5e0-2bd14a268696/download](https://app.zenhub.com/files/133843125/8f7289b2-047f-47aa-b5e0-2bd14a268696/download)

**Comment by lenaecb** [comment]
@jbalboni - can we get type of care and provider information associated with these VVC appts?

**Comment by jbalboni** [comment]
@lenaecb It looks like have provider info (name, phone, and email), but nothing related to type of care.

**Comment by lenaecb** [comment]
@jbalboni - Has this been merged to staging? I see ATLAS update but not this update. But also I can't find the PR so couldn't tell if this was merged yet or not.

**Comment by jbalboni** [comment]
@lenaecb It should be on staging in 15-20 minutes, I just merged it. I did this ticket and the clinic based one in the same PR, so this one didn't have a direct link: https://github.com/department-of-veterans-affairs/vets-website/pull/14349

**Comment by lenaecb** [comment]
My b, @jbalboni - I got too excited hahaha
