### ISSUE TITLE
Access for David Addison (redo)

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-team#13063]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > David Addison
- Please Provide your email.
   > david.addison@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS-CMS, Delivery Manager, Agile Six 

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjwkRSOxl5irYv1TFPfrulEpjUNVE3XkwAdOsyPWjMGyzQUJqGhRYJ49D7IpUWSSffnjqjo7nMH8gMOWAJIW8XtYs9YkaycPg/ddWLK4c8kYDbzaa8Cy/0uVfH3RrZwwo4ERxz90Z5Ss8gHrVco6X+ejCFpwjQ9DB8I/iu8UP+TcM8EAudtmPORfh+lcRiK3Ugfp9tr7cv/I7fplVHcvzmbglHpPlFAjmhqMVNjS9/wWS0DGGWNDpoLjFM2964ZuFBfdFs8PifYgSjbZBhI+T8dzkuS5lbeCWgsqSWmf24dp89vln4MHhLXDhFtLxVEeH9PoDXyitcZvUZ4N5nmAq0/nGVFpZ5E5q8JfhmjKem9iNrJPSo3NftbKyqEKitu8Mt/36Dyewr8KIFcMLsaJEL5HO5RkJwc7AqCmnkKzE3y0nm00o3th/LgqQ4UZ8z02C3Coy/fl+6UoZMO+4mj0ffKhd3V0Kln3/pQN3TWqZwlWRdfYUDJUEVRR4tJhMF+y0= okied@LAPTOP-LGL5TLEH

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by daddison48** [comment]
@department-of-veterans-affairs/vsp-operations I submitting a new request for my SSH key authorization. I previously requested one under #12187 but for the life of me forgot my phase phrase, so regenerated new key and promise to remember phrase this time...

**Comment by jbritt1** [comment]
Key updated in #7522. Please allow up to ten minutes for the new configuration to be deployed.
