### ISSUE TITLE
Design - Account for VVC Group video appts

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13062]
Right now, we are not accounting for Group VVC appts in VAOSR. 

Group VVC appts should be treated very similarly to VVC appts for Ad Hoc and Mobile any - which use existing design layout. 

We will need to call out/label Group appts as such. 

Supporting email sent for Group VVC appts: [https://app.zenhub.com/files/133843125/93533e6b-4ee3-4eb8-b124-16ad9a08127b/download](https://app.zenhub.com/files/133843125/93533e6b-4ee3-4eb8-b124-16ad9a08127b/download)

**Comment by jbalboni** [comment]
Looks like we need a groupAppointment flag from VVS that MAS isn't currently passing through: https://issues.mobilehealth.va.gov/browse/VAOSR-1274

**Comment by ldelacosta** [comment]
We will create a new ticket if this is a priority for the Appointments team. Closing out the ticket. cc: @JRRoof @outerpress
