### ISSUE TITLE
Analytics Implementation for How To Wizards

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#13060]
# Google Analytics Implementation

## Purpose
- Establish a standardized dataLayer and reporting structure for all "How To" Wizards on VA.gov that can be baked-in to FE code of future wizards (similar to forms library) 
- The end goal is for all and future "How To" Wizards to be tracked consistently -- this will allow for:
   - Increased turn-to-market speed on FE components (dataLayer) and Analytics components (GTM) of tracking
   - Consistency in reporting within Google Analytics 

### Stakeholders
    - John Hashimoto + Teams (BAM1, BAM2, Education, eBenefits)
    
### Helpful Resources
- [Implementation Tracker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/status_reports/implentation_tracker.md)
- [Epic for Moving Wizards to Application Pages](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9665)
- [PDF of Education Wizard Paths](https://app.zenhub.com/files/133843125/e42e1b7a-5a5c-45f0-a208-7c4a17a79442/download)

## Acceptance Criteria
- [ ] Standardized datalayer specification has been drafted and finalized
- [ ] DataLayer specification has been implemented on all current How To Wizards
- [ ] FE dataLayer analytics code has been packaged along with the How To Wizard code as a template for future use 
- [ ] QA has been completed of both the dataLayer and Google Analytics tagging

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Other Product Specific How To Wizard Issues: 
- #9510
- #12317

**Comment by jonwehausen** [comment]
### Developer Notes
cc: @craigwheeler 
- To reiterate, the goal is to make this code generic / flexible enough to scale to each of the product wizards effectively
- From our readings, it looks like the wizard will be dynamically visible within the session based on whether the user has already engaged with the wizard, for this reason, -- we'll want to have a generic event that says yes the wizard was visible
- Anywhere you see `<>` this is intended to represent dynamic population of the relevant form details
- For the `form-field-type` -- this should dynamically identify the type of form field generically, noticed the form radio buttons have the generic `form-radio-buttons`, this should do just fine
- For manual input fields, _e.g the year field of the date selections_, we will want to wait to push to the dataLayer until the user has clicked away from the field, rather than with each keystroke change
- To track the instructional embedded links for example, we can consistently use `<BENEFIT_PREFIX>-howToWizard-navigation` for all of the link clicks contained within the wizard, if possible, we will also want to dynamically populate `true` or `false` based on if all questions have been answered at the time the user clicks on a link (in other words, if all form fields are completed / answered)
- Where you see **<BENEFIT_PREFIX>** in the specification below, this will correspond with the benefit hub directory according to the following taxonomy: 

  | Benefit Hub Pages Where Wizard Will Live | BENEFIT_PREFIX | 
  | -- | -- |
  | Education How To Apply & Education - 1990,1995,1990e,5490, 10203, 1990n, 0994 | `edu`| 
  | Disability How To File, Disability 526, & Higher Level Review | `disability`| 
---------------------------
### Edge Cases Still Needing Clarification 
- We noticed on [21-526EZ](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction) that there doesn't seem to be an initial CTA expand/collapse dropdown - the wizard seems to automatically load. This is certainly fine, and from an analytics perspective we can leave the `expand` and/or `collapse` events out for these types of wizards, just want to make sure we will still be able to build around this organically and with ability to scale on the FE. @johnhashva @craigwheeler your insight here would be very much appreciated
---------------------------
### Proposed DataLayer Specification


| Description of Event / Interaction | Screenshot of Event / Interaction |Data Layer                                                                                                                                                                                                         
|--|--|--|
| Wizard visible (loaded or not) | N/A | ```'event': '<BENEFIT_PREFIX>-howToWizard-load'``` | 
|Click to expand of first CTA button | ![image](https://user-images.githubusercontent.com/48527022/91852248-8f985f80-ec2e-11ea-96ba-70d370e377ff.png) |``` 'event': '<BENEFIT_PREFIX>-howToWizard-cta-expand' ``` |
| Collapse of first cta button | ![image](https://user-images.githubusercontent.com/48527022/91852416-d1290a80-ec2e-11ea-95bf-7dddf3f7d096.png) |``` 'event': '<BENEFIT_PREFIX>-howToWizard-cta-collapse'``` |
| **All** Form Field Types (radio buttons, date dropdowns, text input fields) & Interactions (clicks, checks/unchecks, dropdown selections)| **form-radio-buttons** ![image](https://user-images.githubusercontent.com/48527022/91853117-be630580-ec2f-11ea-9362-4c0e58cf3551.png) <br><br> **errorable-select** ![image](https://user-images.githubusercontent.com/48527022/91853367-1437ad80-ec30-11ea-954a-8792055baca6.png) |`'event': '<BENEFIT_PREFIX>-howToWizard-formChange',`<br>`'form-field-type': '<form_component_type>',`<br>`'form-field-label': '<question_text>',`<br>`'form-field-value': '<question_answer_or_form_value>'` |
| Receiving ineligibility alert | ![image](https://user-images.githubusercontent.com/48527022/91853808-be173a00-ec30-11ea-8d1f-89d003677472.png)  | `'event': '<BENEFIT_PREFIX>-howToWizard-ineligibility-alert',`<br>`'ineligibility-alert-heading': '<INELIGIBILITY_ALERT_HEADING_TEXT>',`<br>`'ineligibility-alert-reason': '<INELIGIBILITY_REASON>'`                      |
| Wizard cta (green primary button) completion  | ![image](https://user-images.githubusercontent.com/48527022/91853862-d424fa80-ec30-11ea-871e-b511cacc3836.png) |```'event': '<BENEFIT_PREFIX>-howToWizard-completion-cta'```|
| All Embedded static links within wizard | ![image](https://user-images.githubusercontent.com/48527022/91854198-5ca39b00-ec31-11ea-8c53-862ad920ac62.png)  |`'event': '<BENEFIT_PREFIX>-howToWizard-navigation',`<br>`'howToWizard-all-form-fields-answered': false //true` |
|"_I know this is the form I need scenario_" -- Skip wizard link (skip-wizard-link) | ![image](https://user-images.githubusercontent.com/48527022/91854451-bf953200-ec31-11ea-9881-26b503f7043f.png) |```'event': '<BENEFIT_PREFIX>-skip-wizard-link-click'```                                     
-----------------------------
### Next Steps
- @johnhashva, @craigwheeler, @leahkeeler + others if you could give this a review and clarify the edge case identified above and let us know any other questions you may have
- Once we've got that clarified, we can then begin implementing the dataLayer spec above for education (refactoring the existing tracking to comply with this new convention) verify and QA before scaling to the other wizards and QA the remaining wizards
- We can then think about how we might scope a KPI dashboard in the future leveraging this data and looking at these wizards holistically

ccing @joanneesteban @bsmartin-ep and @bmcgrady-ep for visibility

**Comment by jonwehausen** [comment]
@johnhashva 

Thanks again for your follow-up on the green button removal. Documenting here for further visibility purposes. 
slack thread: https://dsva.slack.com/archives/C0113MPTGH5/p1599059026104600

-------
#### ❕ **Green button will be getting removed, original spec including the `expand|collapse` should be ignored**
------

### Here are a few remaining design / functional implications we should get pinned down before finalizing our spec: 
- **What is the status of session storage utilization for wizard visibility?** There are outstanding discussions of whether session storage will be leveraged as a utility for dynamically displaying the wizards. If session storage is used or the wizard is conditionally shown for any reason, we will certainly want to have our `howToWizard-load` event to indicate volume of those seeing the wizard at all. If session storage is not done, and the wizard loads for every page load, there may not need to be an event here. 
- **Are there any conditions for the wizard failing to load functionally?** If there is are other dependencies or a reasonable potential for the wizard not to load, we maybe want to look at capturing a failure `event` of the tool. 
- **Any other UX adjustments?** Understanding there is ongoing tweaks and feedback of the wizard UX -- we will want to make sure we have seen the a fairly-close final UX upon sign-off of our spec.

**Comment by johnhashva** [comment]
@jonwehausen Liz has created a[ full flow Interactive Prototype](https://preview.uxpin.com/ca08f3dbf63475b2b62f3e8c00050ad1b19c4cb5#/pages//simulate/no-panels?mode=i) for the Education Wizard which outlines the UX refinements the team has determined were needed.

**Comment by jonwehausen** [comment]
## REVISED Datalayer Specification for How To Wizards As of 10/20/200
- This version is intended to serve as the data layer tracking specification all How To wizards should adopt
- This version is intended to be flexible enough so that it can be re-used where small design customizations do not impact the functional components of the form 
- To highlight some of the changes from the first specification to this one: 
   - No need to include a product prefix in the data layer -- reason here is we are already capturing product groupings via GTM and the URL will be specific enough for product identification
   - No need for an expand/collapse event in the data layer as that portion of the UX will not be re-used moving forward
   - Introduce events for when the wizard is hidden, the user starts over, and/or skips the wizard
   - A few event/variable name changes allow for greater flexibility and consistency

@johnhashva Please find our latest version of the full data layer specification for How To Wizards below (**please ignore prior comment from prior design**). Please let us know your thoughts and let's setup a time where we can review together and with developers from the various teams to level-set on what we have here, answer any questions, and determine next steps. 

Description/Screenshot of Interaction | DataLayer | Dev Notes
------------ | ------------- | -------------
Wizard does not load due to business logic around prior engagement with forms | `'event': 'howToWizard-hidden',`<br>`'reason-for-hidden-wizard'` | For the circumstances where the wizard is hidden, perhaps we add a small reason for the hidden wizard as `reason-for-hidden-wizard` -- should be descriptive enough to provide insight into why from a system perspective the wizard was hidden
User chose to start over the wizard | `'event': 'howToWizard-start-over'` | Pushed along with the user function to start the form over [(manually clears the session data)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/use_cases/business_logic.md)
Form field changes (clicks on radio button answers) | `'event': 'howToWizard-formChange'`,<br>`'form-field-type': '<form_component_type>',`<br>`'form-field-label': <question_text>',`<br>`'form-field-value': '<question_answer_or_form_value>',` | • `'form-field-type'` should populate with the class name, in this case `'form-radio-buttons'` ![image](https://user-images.githubusercontent.com/48527022/93485736-61bf4600-f8d1-11ea-9650-8c2f6f381b95.png) •`'form-field-label'` should populate with the full question label<br>•`'form-field-value'` should populate with the value selected, in most cases here `'Yes'` or `'No'`
Received alert notice following a question answer <br> ![image](https://user-images.githubusercontent.com/48527022/93490255-40ad2400-f8d6-11ea-85bf-f2d7b88e2d3c.png) <br> ![image](https://user-images.githubusercontent.com/48527022/93491401-a3eb8600-f8d7-11ea-9086-00218c7eb200.png) <br> ![image](https://user-images.githubusercontent.com/48527022/96585154-2d162400-12ad-11eb-9856-dc04ba7b5bca.png) | `'event': 'howToWizard-alert-displayed',` <br>`'reason-for-alert': '<description>'` | <br>`'reason-for-notice'` can populate with whatever free text level of specificity you all feel is necessary to understand why the user received the notice, for reasons that are ineligibility related, we can prefix with `ineligibility - `...(**e.g** `'ineligibility - not a service member or veteran'`, `'ineligibility - eligible for chapter 31'`, `'ineligibility - outside time period from active duty discharge`', `'chose not to apply now'`)
Click on link within blue box notice <br> ![image](https://user-images.githubusercontent.com/48527022/93496079-cb911d00-f8dc-11ea-92ec-14109038beda.png) ![image](https://user-images.githubusercontent.com/48527022/96589333-aebc8080-12b2-11eb-9b2a-bb7315e08a29.png) | `'event': 'howToWizard-alert-link-click'`, <br> `'howToWizard-alert-link-click-label'`| Populate with the full link click label
How to wizard primary CTA is surfaced / visible | `'event': 'howToWizard-cta-displayed'` | When the user has reached the end of the series of questions to reach the apply now button 
User clicks button to apply now <br> ![image](https://user-images.githubusercontent.com/48527022/93489961-e44a0480-f8d5-11ea-83ba-d94edee335f9.png) | `'event': 'cta-primary-button-click'`<br>`'primary-button-click-label'` | Populate with the full primary button click label
User clicks link to skip how to wizard <br> ![image](https://user-images.githubusercontent.com/48527022/93489251-49512a80-f8d5-11ea-83e5-e2ab93892d28.png) | `'event': 'howToWizard-skip'` | From reading [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/use_cases/business_logic.md#for-all-wizards), sounds like there will be customization around the display properties (link vs h2) <br><br> Keeping this event name generic to account for the customizations of some teams having links vs buttons

**Comment by jonwehausen** [comment]
@cohnjesse Thanks again for your time today and volunteering here, we greatly appreciate it! 

Per our conversation, our goal is to standardize our specification into the platform wizard code for fast-tracked deployments of analytics for how to wizards moving forward (similar to our forms library events today). 

Please reference [this specification](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md) as part of this effort. Again, please feel free to incorporate as part of your normal prioritization / sprint planning. 

In addition, if possible, we would like to make the adjustment to allow the full capture of the radio button question **AND** radio button option text, please let us know if this becomes overly complicated. 

cc: @johnhashva @joanneesteban @bsmartin-ep @jason-gcio

**Comment by bsmartin-ep** [comment]
GTM workspace for this:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000387

**Comment by jonwehausen** [comment]
Hi @cohnjesse , 

Hope you had a great holiday!

Wanted to touch-base here if there was any other information you needed from us and ballpark of when you think you'll fit within your sprint cadence / priorities. 

Thanks again for your help here!

**Comment by jonwehausen** [comment]
### Update
- Leaving open until we can coordinate with Jesse on when we can update all active wizards

**Comment by jonwehausen** [comment]
### Refactor Education Wizard to Latest Specification

Hi @johnhashva , 

The education wizard on `www.va.gov/education/how-to-apply/` is currently being tracked according to a data layer spec that preceded our effort to standardize our spec across all wizards. 

It would be a good idea for us here to adjust the tracking on the wizard according to our new data layer spec to keep up with our goal of standardizing our wizard tracking. If possible in an upcoming sprint, it would be great to adjust the data layer according to this most recent up-to-date spec: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md

cc: @mattpointzxer0 @leahkeeler @amyknox

**Comment by johnhashva** [comment]
@jonwehausen Fully agree!

**Comment by jonwehausen** [comment]
Closing -- was open primarily as a parent ticket for tracking how to wizard deployments over time
