### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13079]
# User Story
As a user, when I open Settings from the Profile menu, I see the following items:
- Manage your account
- Touch ID on/off
- Share the app
- Privacy Policy
- Sign out

# Tasks
- [x] High fidelity prototype of screens in iOS
- [x] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

# Prototype
[Prototype screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636883)

**Comment by srmyers17** [comment]
Other things to consider:

- Horizontal/vertical
- Language
- Dark vs light mode

**Comment by artsymartha68** [comment]
I sign off, looks good!
