### ISSUE TITLE
Access for Giles Wells

### ISSUE THREAD

**Issue by gileswells** [department-of-veterans-affairs/va.gov-team#13087]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Giles Wells
- Please Provide your email.
   > giles.wells@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: okAPI | Role: Frontend Engineer | Company: Oddball

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBbqotEgbj6Sbrch5h08gc08KTzDUnM3RK2EQe6NhGyuqLTdAQO64M7HgP1aFfRTpXTJPbS/jAP6UnuLk5f0+Hg+OW1Z8lSndoJ89nPc2i5unRPGrmVmrJlO5zHAPNLuPnwJxBUMcjK4ir4xbytTYl3xHmGHxulLIjDr0MEW8DxGhbi1dZPu1wIngkoJbhOH7WlSJF641OhO1eS+0xoNfrPXZWCpYPg4t+zdpSSTZokKDTJEBzc63wx9584SaKRPPHTD4JHfcREgcl3eW5+ebRtkQncyeZaJlynaUzRYa+4nNX/nIScmMZvL47jeXs5MgjAHlKkNmDTZ647nX4jKj+oEav1bKvbwgvTUXCvyES5pA3YxtggWrjsr9paKCgme0mxXGfcN7LHADMUxKs5gnFqZghM+BNkCQImoOHfxFhEXhrFGjPyLOoVBNl/+t7vfhztE7MesMWOasS1haOnroAjSX31XTGLyCtEwyzOzTkO4aJb9SXAqdVRyy/8WrU3IE= giles.wells@oddball.io
```

- Grant AWS Console access?
  > YES
  - Need AWS Console access for developing and maintaining the Lighthouse dev portal.

**Comment by gileswells** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
Will get SOCKS access configured shortly.

**Comment by jbritt1** [comment]
### For AWS Access:

User: Giles Wells
COR: Crystal Moultrie
Approval needed: @Jeff-Hayter

**Comment by jbritt1** [comment]
Accidental close, apologies.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by gileswells** [comment]
I'm able to connect to SOCKS

**Comment by gileswells** [comment]
@jbritt1 am I needing to do anything else for AWS?

**Comment by jbritt1** [comment]
Just awaiting approval. Have you submitted an eQIP?

**Comment by gileswells** [comment]
I've submitted it and also just picked up my physical PIV this morning. Haven't heard back on the status of the eQIP.

**Comment by jbritt1** [comment]
Alright, all we need is for @Jeff-Hayter to confirm/approve.

**Comment by Jeff-Hayter** [comment]
@gileswells I usually reach out to your COR, but if you have a copy of the email saying your eQIP was successfully submitted and is processing I can use that to expedite.

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by jsev-io** [comment]
Thanks @Jeff-Hayter , @gileswells I'll get you access shortly.

**Comment by gileswells** [comment]
Able to login to AWS and setup MFA and Access Keys. Thank you all.
