### ISSUE TITLE
Staging; Audiology set to Yes Any Veteran System displays appt needed in last 12 mos

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#13081]
For Audiology in VATS configure the following:
Cheyenne Direct Schedule and Request = NO.
All Child Sites (Fort Collins, Loveland, Sidney) Direct Schedule and Request = YES Any Veteran.  

ola.e.edgecombe@id.me. As  of the time this script was written ola did not have any audiology appts

Type of Care =Audiology Care. 
1.  System displays Choose where you want to receive your care  VA medical center or clinic AND Community Care facility.  Select VA. System displays Choose a VA location for your appointment: Fort Collins, Loveland and Sidney.  
2.  Select Fort Collins.
3.  Expected Response:  System displays Choose a day and time for your appointment (request flow).   
4. Actual Response:  We couldn’t find a recent appointment at this location.  You need to have visited this facility within the past 12 months to request an appointment online for the type of care you selected.
Also happens on 
1.  In VATS Sleep in Cheyenne: Direct Schedule = No.  Requests = Yes
2.    Jacqueline.morgan@id.me.   Select Sleep Home Medicine Expected Response:  Request Flow Displays.  Actual response:  We couldn't find a recent appointment at this location.  
4. Actual Response:  We couldn’t find a recent appointment at this location.  You need to have visited this facility within the past 12 months to request an appointment online for the type of care you selected.

![FTC_Audilogy_Can'tRequest.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/4d2ca243-426c-4de1-b2b1-01f17c17eb19)

**Comment by jbalboni** [comment]
This appears to be a backend issue. Created a ticket: https://issues.mobilehealth.va.gov/browse/VAOSR-1081

**Comment by marcynadeau** [comment]
Tested and passed SQA testing in Staging with VAR-Resources 4.23.1
