### ISSUE TITLE
[development] InProgressFormCleaner -  delete associated uploads

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13086]
When we [delete expired In progress](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/in_progress_form_cleaner.rb#L7) forms, we should also delete their associated document uploads.

**Comment by edmangimelli** [comment]
@annaswims 
are we currently deleting expired in-progress forms? I thought we weren’t and we were reluctant to settle on an expiration date (as long-lived bugs keep cropping up)

**Comment by annaswims** [comment]
yeah, they get deleted a year after they were last updated. But on second thought this might not always be a good idea so I'm closing the issue.  If someone makes a submission attempt and then later their form expires it would be nice to still have the files around I think.  Or, at the very least, this doesn't benefit the veteran.

**Comment by edmangimelli** [comment]
>yeah, they get deleted a year after they were last updated. But on second thought this might not always be a good idea so I'm closing the issue.

do want to consider lengthening this?
