### ISSUE TITLE
Codeclimate metrics broken

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#13088]
## What happened?
Something seems to have broken with Codeclimate's maintainability & tech debt metrics between April and June of 2019:
https://codeclimate.com/github/department-of-veterans-affairs/vets-website/trends/technical_debt

![image](https://user-images.githubusercontent.com/63597655/91899007-8e852380-ec6a-11ea-8c1f-e2fb78fe767b.png)

It's currently showing 0 code smells, 0 duplication, and 0 issues of any kind:
![image](https://user-images.githubusercontent.com/63597655/91899411-1e2ad200-ec6b-11ea-99ae-dd591db3957b.png)

## Steps to Reproduce
URLs:
- https://codeclimate.com/github/department-of-veterans-affairs/vets-website
- https://codeclimate.com/github/department-of-veterans-affairs/vets-website/trends/technical_debt
- https://codeclimate.com/github/department-of-veterans-affairs/vets-website/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication
- https://codeclimate.com/github/department-of-veterans-affairs/vets-website/issues?category=duplication&engine_name%5B%5D=structure&engine_name%5B%5D=duplication
- https://codeclimate.com/github/department-of-veterans-affairs/vets-website/issues

## Desired behavior
Codeclimate metrics should accurately reflect `vets-website` codebase.

## Acceptance Criteria
- [ ] Accurate Codeclimate "technical debt" metric
- [ ] Accurate Codeclimate "code smells" + "duplication" + other issues metric

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by timwright12** [comment]
@mchelen-gov I can see that the codeclimate file was removed in Nov. 2018 (but the data kept reporting), then it was added back in Oct. 2019 (this is when the data dropped off)

https://github.com/department-of-veterans-affairs/vets-website/commits/master/.codeclimate.yml

I can look into this one

**Comment by timwright12** [comment]
It looks like a bunch of the metrics were turned off to incrementally bring them back in, but it never happened https://github.com/department-of-veterans-affairs/vets-website/commit/a25e443991f1d5ea901501fdc5fa3b5115596039#diff-e97904d8a0443f46ad2c8ceb5fbe5355e52f6be540378ab8ea1e98870395d7de

**Comment by timwright12** [comment]
Opened PR to turn on the metrics again https://github.com/department-of-veterans-affairs/vets-website/pull/17861

**Comment by timwright12** [comment]
@mchelen Closing out, this should be all set: https://codeclimate.com/github/department-of-veterans-affairs/vets-website - you'll see the updated metrics in the dashboard and the trends information should be filled in https://codeclimate.com/github/department-of-veterans-affairs/vets-website/trends/technical_debt
