### ISSUE TITLE
Homescreen links

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13089]
# User Story

As a user, from within the homescreen, I can navigate to: 
- Veteran Crisis Line
- Claims & Appeals
- Appointments
- Find a VA location
- Coronavirus FAQs
- Contact VA

# Tasks
- [x] High fidelity prototype of screens in iOS
- [x] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting, Android-specific design as needed

# Prototype
- [Screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636866)

**Comment by srmyers17** [comment]
Removed cards from homescreen testing for round 1.

**Comment by srmyers17** [comment]
Usability feedback will be incorporated into the prototype.

**Comment by bridgethapner** [comment]
# Relevant wireframe
- [Home screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636866)

**Comment by artsymartha68** [comment]
Looks good, I sign off!

1. "Appeals" should not be capitalized, I don't think
2. "Location" should not be capitalized, I don't think
3. On the back burner: add a link for covid screener?

**Comment by bridgethapner** [comment]
Thanks @artsymartha68! 

I made changes 1 & 2 and created a ticket for #13679 for the COVID screener.
