### ISSUE TITLE
VAOS backend discovery questions

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#1308]
These are the backend-related questions I've come up when researching the front end data requirements for the WIP designs. Some of them should be broken into separate tickets, probably, but we also may want to talk through which ones to prioritize.

1. The new design has a flow where you schedule by provider, how could that work in the current system? (#1424)
   - This doesn't exist in the current application, what does it actually mean for us to do this?
   - This is the flow that Cerner would use, but digital services would like to see if it's possible here
2. How can we make the type of care page more efficient?
   - We need the systems where someone is registered along with what types of care are available for facilities in that system
   - Each type of care for each facility is an individual request. We'd like to get a list of types of care supported for each facility with ideally just one call.
3. How do facility ids map to the ids used in the va.gov facility locator? (#1324)
   -  They appear to be different
4. New appointment (not request) details page is showing some info that isn't in the existing service, is it possible to add this extra data?
   - Appt type, reason, doctor, specialization, and contact info
5. Why is there a separate endpoint for booked CC appts, but they're mixed into the requests endpoint?
   - Could we combine these?
6. Can we make the Appointment/Request list and details services more efficient?
   - All the data is pulled down in the main list request, rather than having a separate detail request for each appt/request
7. What is going on with datetimes and timezones?
   - Why are dates returned in a non-ISO format? What timezone are they in? What is the current timezone related code doing?
   - If all times are relative to the facility local time, what timezone logic do we even need?
8. Ryan wants messaging and notifications moved to Secure Messaging. How can we make this work?
   - What does this mean for launching an MVP? Can we launch something that doesn't show the existing messaging?
9. Can you currently opt out of email notifications from the email itself?
   - Ryan wants this functionality in the email, not asked in the new appointment flow.
   -  If not, how do we implement this?

**Comment by markgreenburg** [comment]
Moved provider flow question (#1) to #1424

**Comment by markgreenburg** [comment]
@saneshark do you have any input on question 8 above?

> Ryan wants messaging and notifications moved to Secure Messaging. How can we make this work?
What does this mean for launching an MVP? Can we launch something that doesn't show the existing messaging?

**Comment by markgreenburg** [comment]
Swaggers for existing services are available in the code repos of each per chat with Kam. This requires access to VA network IIRC.

**Comment by markgreenburg** [comment]
@kreek think we're ok to close this ticket?

**Comment by kreek** [comment]
@markgreenburg yes, I'll close it
