### ISSUE TITLE
Content Feedback on Medallia intro & thank you pages

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#13084]
## Issue Description
We need to use Medallia to release new user feedback surveys on VA.gov so that we continue to receive website feedback. How might we ensure that our content on intro and thank you pages are plain language and user friendly?

---
## Tasks
- [ ] Receive feedback on the intro and thank you pages. Images below (can comment on this issue with feedback).

## Acceptance Criteria
- [ ] VSP Analytics & Insights receives content feedback on the new survey pages.
---
## Medallia Screenshots
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/184386df-06cf-4b2a-a265-5a733c048336)

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/4a16446c-9bf1-45ec-a58a-c2bf4975ed81)

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/87d5eda2-9a74-49fb-9296-29e6e487140b)

**Comment by amygoldman** [comment]
Hi @joanneesteban, here are my copy revision suggestions: 

Slide 1:
Let us know what you think.
Thank you for visiting our website. You’ve been randomly selected to participate in a brief customer satisfaction survey. Let us know how we can improve your experience. 

Not right now		Provide feedback


Side 2:
Thank you for taking our survey—and for helping us serve you better.

We appreciate your input.


Slide 3:
Thank you for providing feedback.

**Comment by joanneesteban** [comment]
Hi @amygoldman . Thank you for the feedback! Here are the final copy edits based of your feedback:
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/36f38283-12ae-4999-a72a-2adfb6562c62)

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/bfd9d063-0607-4734-b2c6-016b6c70854a)

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/ae9d9fcf-8fbd-48bd-9585-6e26418b1edd)

**Comment by joanneesteban** [comment]
Hi @amygoldman ! Closing this ticket, but can reopen if you find that the above text doesn't work.
