### ISSUE TITLE
Consider data retention policies for Form 526

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13085]
The team should discuss and set a policy for how long we intend to save  Form 526 submissions and their associated uploads.  I don't see any reason to keep the files after a successful EVSS submission. Or at the very least, don't keep them long. 

currently we have around 500k files that are 800gb in s3.  
https://console.amazonaws-us-gov.com/s3/buckets/dsva-vetsgov-prod-evss/?region=us-gov-west-1&tab=management

**Comment by edmangimelli** [comment]
talked about this in back-end backlog grooming today.
summary: We have a form 526 cleanup job, we just need to start deleting uploaded files for successful submissions.

something we did on Lighthouse was cleanup files ***a week after*** they hit successful status, to give us time for debugging (if needed).

**Comment by vhenry07** [comment]
We've decided to keep the data as there is no negative impact to doing so.

**Comment by vhenry07** [comment]
Closed with decision to retain data.
