### ISSUE TITLE
Access for Bradley Gross

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#13095]
@department-of-veterans-affairs/vsp-operations
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Herbert Ackermann
- Please provide your name.
   > Bradley Gross
- Please Provide your email.
   > bradley.gross@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VAOS

- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVjnIflneh0Tt6YoiAz9ntb52h1ze9rK1Fw29F/++qiPh7YniD+zPzld5oibJ+nMvSAp+eCxQxsT3OoMTQW90ZFr+K9DjcWtPmb/51RQD/mZXSPdqhUqLjgm5s3iaRN07xDh21LJnrYuX2Lc+VUvk3CwNJsLVXuNp9quxZa5WFneMtT9QqNtsI2dYwx62CxxTlHF/ENkXlni/tceQb4ZxNM1dSGrDT3Ee9i6DoLe0TfX1bL2MTJyhK/y115TiYcUhAdLJLFrh+HrSUZumMIN8KPdzHc3lnV6/IO5DRfYFVxtLg2847gJADdepvEfsCLYk7pj8OLsW340Y8j71m0cuoD3PFs8ed3Ejo6GyqDqxrEFOyF7OMqfGZaqqGE0ubzfSdtuswlTv6x5LktLFoytqK+3yA0ifQswnCCzNjM/y5Z9hlUW+p/MkGoLSHDJOuFyJ30WsVtz5tLbpLcQkgSSWS+W2Ia+MQ3XyIWFcC3d7A/7UGhBXHdo19ZE8WhdYLuJk= grossb1@Uukrul
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
Monitoring via Cloudwatch

**Comment by grossb1** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
Working on SOCKS access now.

**Comment by jbritt1** [comment]
### For AWS Access:

User: Bradley Gross
COR: Herbert Ackermann
Approval needed: @Jeff-Hayter

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.
