### ISSUE TITLE
Fix the bad labels on Caregiver's Facilities List

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#13096]
**Description**:
The Form 10-10cg has a list of facilities that the user can choose to receive care ("Planned Facility"). This list is a subset of all VA Medical Facilities found in `vets-json-schema`.

We used the labels in the `vets-json-schema`'s [vaMedicalFacilities.js](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/vaMedicalFacilities.json). Some of these labels are not user-friendly.

**Summary**
- [ ] Ensure there is no technical purpose for these labels being defined how they are, and that we can update them without issues.
- [ ] Update [vaMedicalFacilities](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/vaMedicalFacilities.json) list in `vets-json-schema` to use the labels found on [VA Facility Locator](https://www.va.gov/find-locations/?zoomLevel=4&page=1&address=St.%20Louis%2C%20MO&facilityType=health&serviceType&location=38.63%2C-90.19&context=Saint%20Louis%2C%20Missouri%2C%20United%20States)
- [ ] Update the [Caregiver Program Facility List](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/caregiverProgramFacilities.json) to have consistent labels to the new `vaMedicalFacilities` list lables.
- [ ] Pull the `vets-json-schema` changes into `vets-api` and `vets-website`

**Investigation**:
- See: https://dsva.slack.com/archives/CMJ2V70UV/p1598925031015600

**Attachments**
Form 10-10CG
- ![image](https://user-images.githubusercontent.com/7391284/91914260-9c946d80-ec85-11ea-845d-531fdb5793f0.png)

Form 10-10EZ
- <img width="944" alt="Screen Shot 2020-09-01 at 10 24 59 AM" src="https://user-images.githubusercontent.com/7391284/91914261-9c946d80-ec85-11ea-8211-db55bd193cd3.png">

Facility Locator
- ![image (1)](https://user-images.githubusercontent.com/7391284/91914259-9bfbd700-ec85-11ea-9201-c2e7d9bbfe1c.png)

**Comment by ala-yna** [comment]
Hi @lihanli ! Let me know if you have any questions want to set up some time to talk through this ticket with Kevin and I. Thank you so much for your help!

(cc @mshea0606)

**Comment by lihanli** [comment]
@ala-yna thanks, i'll take a look at the code and let you guys know if i have any questions

**Comment by lihanli** [comment]
not all facilities in the `vaMedicalFacilities` list are in the facility locator database, should i leave those labels unchanged?

**Comment by kevinmirc** [comment]
@lihanli do you have a list of the facilities not found in Facility Locator?

**Comment by lihanli** [comment]
@kevinmirc yeah, these ones:

```JSON
[
  {
    "state": "VT",
    "value": "405HK",
    "label": "WHITE RIVER JUNCTION MORC"
  },
  {
    "state": "VT",
    "value": "405HB",
    "label": "MONTPELIER OUTREACH CLINIC"
  },
  {
    "state": "MT",
    "value": "436GJ",
    "label": "MILES CITY VA CLINIC"
  },
  {
    "state": "SD",
    "value": "568HG",
    "label": "SIOUX SAN"
  },
  {
    "state": "NE",
    "value": "636GV",
    "label": "O'NEILL VA CBOC"
  },
  {
    "state": "NM",
    "value": "504HA",
    "label": "CLAYTON OUTPATIENT CLINIC"
  },
  {
    "state": "PA",
    "value": "693GE",
    "label": "SCHUYLKILL COUNTY CBOC"
  },
  {
    "state": "PA",
    "value": "693GD",
    "label": "WILKES-BARRE (CBOC)"
  },
  {
    "state": "TX",
    "value": "549GI",
    "label": "NORTH TEXAS HEALTH CARE SYSTEM - CLEBURNE CBOC"
  },
  {
    "state": "TX",
    "value": "519HD",
    "label": "STAMFORD CBOC"
  },
  {
    "state": "TX",
    "value": "549GA",
    "label": "TYLER VA CLINIC"
  },
  {
    "state": "TX",
    "value": "549GB",
    "label": "NORTH TEXAS HEALTH CARE SYSTEM - DALLAS CBOC"
  },
  {
    "state": "TX",
    "value": "549GC",
    "label": "BONHAM VA CLINIC"
  },
  {
    "state": "TX",
    "value": "580GA",
    "label": "HOUSTON CBOC"
  },
  {
    "state": "TX",
    "value": "671B0",
    "label": "SOUTH TEXAS HEALTH CARE SYSTEM - MC ALLEN OUTPATIENT CLINIC"
  },
  {
    "state": "TX",
    "value": "671BZ",
    "label": "SOUTH TEXAS HEALTH CARE SYSTEM - CORPUS CHRISTI OUTPATIENT CLINIC"
  },
  {
    "state": "TX",
    "value": "671GA",
    "label": "VA HARLINGEN OUTPATIENT CLINIC"
  },
  {
    "state": "TX",
    "value": "671GC",
    "label": "DEL RIO VA CLINIC"
  },
  {
    "state": "TX",
    "value": "671GD",
    "label": "UNITED MEDICAL CENTERS"
  },
  {
    "state": "TX",
    "value": "671GE",
    "label": "SOUTH TEXAS HEALTH CARE SYSTEM - LAREDO OUTPATIENT CLINIC"
  },
  {
    "state": "TX",
    "value": "671GG",
    "label": "CHRISTUS SPOHN SAN DIEGO FAMILY HEALTH CLINIC"
  },
  {
    "state": "TX",
    "value": "671GI",
    "label": "CHRISTUS SPOHN BISHOP FAMILY HEALTH CLINIC"
  },
  {
    "state": "TX",
    "value": "671GJ",
    "label": "UVALDE VA CLINIC"
  },
  {
    "state": "TX",
    "value": "740GE",
    "label": "EAGLE PASS CBOC"
  },
  {
    "state": "OH",
    "value": "541GN",
    "label": "STATE STREET VA CLINIC"
  },
  {
    "state": "MD",
    "value": "460HM",
    "label": "MILLINTON MORC"
  },
  {
    "state": "KY",
    "value": "596HA",
    "label": "LEXINGTON MOBILE OUTREACH CLINIC"
  },
  {
    "state": "WV",
    "value": "613HK",
    "label": "MOBILE VAN CLINIC MORC"
  },
  {
    "state": "FL",
    "value": "546B0",
    "label": "MIAMI (OCS)"
  },
  {
    "state": "FL",
    "value": "573GB",
    "label": "JACKSONVILLE CBOC"
  },
  {
    "state": "FL",
    "value": "573GG",
    "label": "LECANTO VA CLINIC (NFL)"
  },
  {
    "state": "NY",
    "value": "630GC",
    "label": "CHAPEL STREET OPC"
  },
  {
    "state": "WI",
    "value": "676GB",
    "label": "LEAVENWORTH, WI CBOC"
  },
  {
    "state": "WI",
    "value": "695HK",
    "label": "CLEMENT J ZABLOCKI"
  },
  {
    "state": "NC",
    "value": "659GB",
    "label": "HICKORY CBOC"
  },
  {
    "state": "NC",
    "value": "659GC",
    "label": "PETERS CREEK VA CLINIC"
  },
  {
    "state": "NC",
    "value": "565GI",
    "label": "VILLAGE GREEN VA CLINIC"
  },
  {
    "state": "NC",
    "value": "565GK",
    "label": "FAYETTEVILLE VA CLINIC"
  },
  {
    "state": "NJ",
    "value": "561GB",
    "label": "ELIZABETH CBOC"
  },
  {
    "state": "NJ",
    "value": "460HO",
    "label": "SALEM CITY MORC"
  },
  {
    "state": "DE",
    "value": "460HL",
    "label": "SMYRNA MORC"
  },
  {
    "state": "MS",
    "value": "520A0",
    "label": "GULFPORT VAMC"
  },
  {
    "state": "MS",
    "value": "520BY",
    "label": "BILOXI OPC"
  },
  {
    "state": "MS",
    "value": "586UMC",
    "label": "UMC"
  },
  {
    "state": "MS",
    "value": "586QC",
    "label": "LAKELAND DRIVE VA CLINIC"
  },
  {
    "state": "CA",
    "value": "654GA",
    "label": "SIERRA FOOTHILLS VA CLINIC"
  },
  {
    "state": "CA",
    "value": "662GB",
    "label": "VALLEJO CBOC"
  },
  {
    "state": "CA",
    "value": "691GN",
    "label": "LYNWOOD CBOC"
  },
  {
    "state": "CA",
    "value": "691GO",
    "label": "PASADENA CBOC"
  },
  {
    "state": "CA",
    "value": "612",
    "label": "NORTHERN CALIFORNIA HCS"
  },
  {
    "state": "WY",
    "value": "442MB",
    "label": "IDES SHERIDAN VAMC"
  },
  {
    "state": "MA",
    "value": "518GG",
    "label": "FITCHBURG CBOC"
  },
  {
    "state": "MA",
    "value": "523GB",
    "label": "VA BOSTON HEALTHCARE SYSTEM - WORCESTER DIVISION"
  },
  {
    "state": "TN",
    "value": "614GH",
    "label": "BOLIVAR CBOC"
  },
  {
    "state": "AL",
    "value": "521GB",
    "label": "DECATUR CBOC"
  },
  {
    "state": "NV",
    "value": "660GC",
    "label": "ELY VA CLINIC"
  },
  {
    "state": "KS",
    "value": "589G9",
    "label": "FORT RILEY CBOC"
  },
  {
    "state": "AZ",
    "value": "649HK",
    "label": "PRESCOTT MORC"
  },
  {
    "state": "CT",
    "value": "689HK",
    "label": "WEST HAVEN MORC"
  }
]
```

**Comment by mlighdc** [comment]
@davidconlon - per our conversation today,  ^^^ is the list of facilities that Lihan was unable to find in the Facility Locator database. Let us know if you have any questions.
cc-ing - @kevinmirc @ala-yna

**Comment by ala-yna** [comment]
Here is a list of some of the facility name changes that our business stakeholders recommended:

![Screen Shot 2020-09-14 at 10.18.16 AM.png](https://images.zenhubusercontent.com/5ddc08a57dcda00001c763e1/1c78d5a3-eb13-4736-927d-a32434b17359)

**Comment by davidconlon** [comment]
@lihanli I'm trying to wrap my head around where the list from 10-10EZ and 10-10CG comes from.
The PDF for 10-10EZ, updated in Jan 2020 (https://www.va.gov/vaforms/medical/pdf/10-10EZ-fillable.pdf), directs veterans to select from the legacy facility locator as opposed to VA.gov's (so that should be fixed on the PDF).

I'm a little skeptical of the data quality from this system as it's a shadow system from VAST - in fact I _think_ this information comes from the old Facilities Locator & Leadership Directory system that VHA is looking to to turn off.

**Comment by lihanli** [comment]
@davidconlon the 1010ez facilities list was given to me by josh faulkner (Joshua.Faulkner@va.gov), who is in charge of the 1010ez submission API. he should have more information about where the list came from.
