### ISSUE TITLE
Platform Code Base - Maintain stable versions - Q2

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#131]
## Problem

Without proper attention, we can easily become behind the accepted versions in the platform code base.  We want to ensure that we do not fall so far behind that the version we are on isn't supported, and ensure that we are on a current stable version according to VA's specifications.

## VSP Q1 + Q2 2020 OKRs 

O3: Stability and resiliency of the Platform's systems and teams continue to improve.

## Details
Shipping features rather than a focus on performance drove our design in the first years of api.va.gov.
  - Both the client and its middleware have some tech debt and can be refactored to be more performant and easier/more clear to use. e.g. function calls are expensive in Ruby, and send is more expensive, the client runs through multiple methods and sends before calling Faraday HTTP methods. A lot of middleware was born out of specific use cases and we've later tacked on conditional logic to make their use more broad. The base case should be the default and specific uses should extend or mixin the base case.
  - Some of our gems are no longer maintained, e.g. [virtus](https://github.com/solnic/virtus) for models (replace with [dry-types](https://dry-rb.org/gems/dry-types/))
  - Can we gain performance with things like [fast_jsonapi](https://github.com/Netflix/fast_jsonapi)

**Comment by jholton** [comment]
[Pertinent article](https://www.mskog.com/posts/42-performance-tips-for-ruby-on-rails/#use-rack-mini-profiler)

**Comment by annaswims** [comment]
@annaswims will split into distinct issues

**Comment by annaswims** [comment]
j/k changed it to discovery

**Comment by jholton** [comment]
Do we have any existing application APM metrics/data?

**Comment by annaswims** [comment]
we collect metrics in https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/statsd_middleware.rb but as far as I can tell they're not used in grafana.  We can make our own dashboards like this though

http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.range_input=6h&g0.step_input=60&g0.expr=sum(rate(api_rack_request_duration%7Bquantile%3D%270.5%27%7D%5B1m%5D))by%20(controller%2C%20action)%20%2Fcount(rate(api_rack_request_duration%7Bquantile%3D%270.5%27%7D%5B1m%5D))%20by%20(controller%2Caction)&g0.tab=0

**Comment by annaswims** [comment]
we could get something close to this
https://docs.newrelic.com/sites/default/files/thumbnails/image/ruby-apm-app_0.png
by adding view and db runtime from rails
https://edgeguides.rubyonrails.org/active_support_instrumentation.html#process-action-action-controller

**Comment by rroueche** [comment]
@alexpappasoddball please add KPIs to the description. What data will you be measuring to understand whether you have improved what you hypothesized this work would improve?

**Comment by rroueche** [comment]
Also which Objective does this work drive? Please add that to the description as well. @alexpappasoddball

**Comment by alexpappasoddball** [comment]
Changing this super epic to quarterly and will add additional super epics for the next quarters and organize them into the next and future columns.

**Comment by alexpappasoddball** [comment]
Closing this super epic in favor of the new Q3 one.
