### ISSUE TITLE
STEM: Case sensitive validation on email

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#13127]
Steps to reproduce:

1. Navigate to https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/personal-information/contact-information
2. In Email address(*Required) enter in test@gmail.com
3. In the Re-enter email address(*Required) enter in TEST@gmaill.com 

Expected behavior: 
1. not be case sensitive (by adding a parameter to ignore case)
2. This is applied to all EDU forms where this issue is present (10203, 1995, 0993, 0994, 1990, 1990e, 1990n, 5490, 5495)

![Screen Shot 2020-09-02 at 12.46.46 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1dd9ec76-0122-4076-91af-6632d581c025)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14269

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-17 at 1.28.40 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c262be64-728c-4836-a42b-c113d39bce45)

**Comment by sonntag-adam** [comment]
In staging. Closing bug.
