### ISSUE TITLE
Batch 1 form detail page UAT 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13126]
## Batch 1 form detail page UAT 

We will provide DEPO, form managers, and SMEs the list of batch 1 form pages behind basic auth gate for UAT review. [See release plan. ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/release-plan.md)

This issue is blocked until breadcrumb issue has been resolved with [CMS ticket #1238](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1238) - ETA 9/11 Friday. 

AC: 
- [x] Breadcrumb issue is fixed. 
- [x] UAT stakeholder email sent. (Jen)
- [ ] Bug reports collected, if any - will do this [via SharePoint doc](https://dvagov.sharepoint.com/:w:/s/VA-forms-managers-and-SMEs/Ef-ae7VAeGtMl8kE3iNpJw0BY4anvfMftXOAnOgShXKDkQ?e=TaDryq). 
- [ ] Close UAT review phase after 5 business days from email sent. 

Related hidden launch ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11155

**Comment by jenniferlee-dsva** [comment]
FYSA @MickinSahni

**Comment by jenniferlee-dsva** [comment]
UAT review of VBA top forms are complete. We received 1 UAT feedback from Luke Tickner and that update has been completed here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13491#issuecomment-692178822

Pending: UAT for VHA top forms.

**Comment by jenniferlee-dsva** [comment]
UAT bug ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13565

**Comment by MickinSahni** [comment]
the uat ticket (Add 'Last updated' date on form detail page templates #13565) is closed. can this be closed as well, @jenniferlee-dsva?
