### ISSUE TITLE
EDU Wizard  VSA-QA Test Plan

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13124]
## Product/Feature summary

All\* the information is [here ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9665)

\*See also #13367 for upcoming IA/Content changes.

## Product-team SMEs

\[List points-of-contact (just full names) for all involved Subject-Matter domains.  Most often, these would be the relevant development-team members (Product Manager, UX Designer, Front-End Developer, & Full-Stack or Back-End Developer]
Product Management: @johnhashva - John H. @mattpointzxer0 -Matt S. @leahkeeler Leah K
Design/Research: @andaleliz LIz L. 
Content/IA: @mnorthuis Mikki N. @peggygannon Peggy G
Front-end: @craigwheeler Craig W. 
Back-end: No BE work required 
QA: @tlei123 Tze L.

## Proposed user-scenarios and Staging test-accounts

- Widget does not require sign-in.
- Mural form-flows \[link in Epic #9665]
- [Wizard to Correct Form Visual Guide](https://github.com/department-of-veterans-affairs/va.gov-team/files/5169364/Education_Disability_Wizards_Questions_for_Forms_3.pdf) \[updated 2020-09-03]
- [TestRail Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_order=asc&group_id=202) (WIP)

## How to configure this issue

- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Test Plan reviewed by Product Team.
- [ ] Test Plan finalized per review feedback.
- [ ] Actual Test Run(s) completed on Staging \[or [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by tlei123** [comment]
@johnhashva @leahkeeler , [WIP TestRail Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_order=asc&group_id=202) are in place now for all destination forms except 1990->5495.

Test-Case updates/completions pending further clarifications requested in [our Slack thread](https://dsva.slack.com/archives/C0113MPTGH5/p1599068509117900):
- [Education Wizards Questions for Forms diagram](https://zh-file.s3.amazonaws.com/133843125/195a43c0-4a84-4611-a44e-4f9472e09135)'s Wizard for 1990e spec
- [Mural flow](https://app.mural.co/t/vsa8243/m/vsa8243/1585244567898/2167d6cafb30ce4a81e2ea8a082a6a832293e11c)'s destination 5495 -- this is missing from our [Education Wizards Questions for Forms diagram](https://zh-file.s3.amazonaws.com/133843125/195a43c0-4a84-4611-a44e-4f9472e09135)

**Comment by tlei123** [comment]
> Test-Case updates/completions pending further clarifications requested in [our Slack thread](https://dsva.slack.com/archives/C0113MPTGH5/p1599068509117900):
> 
> * [Education Wizards Questions for Forms diagram](https://zh-file.s3.amazonaws.com/133843125/195a43c0-4a84-4611-a44e-4f9472e09135)'s Wizard for 1990e spec

Question about 1990e questions-flow resolved, thx to [Mikki Northuis's Slack response](https://dsva.slack.com/archives/C0113MPTGH5/p1599073787120500?thread_ts=1599065817.113900&cid=C0113MPTGH5).  [TestRail Test Case](https://dsvavsp.testrail.io/index.php?/cases/view/942) now updated to refer to Wizard for Form 5490 instead, except for selecting No for the last question re. sponsor-status.

Now just waiting for clarification \[specifically the missing questions-flow] for:
* [Mural flow](https://app.mural.co/t/vsa8243/m/vsa8243/1585244567898/2167d6cafb30ce4a81e2ea8a082a6a832293e11c)'s destination 5495 -- this is missing from our [Education Wizards Questions for Forms diagram](https://zh-file.s3.amazonaws.com/133843125/195a43c0-4a84-4611-a44e-4f9472e09135)

**Comment by johnhashva** [comment]
@tlei123 Attached here is the updated (and corrected) Questions for Forms diagram (PDF) -- and this version includes:

- the Wizard question flow for the 5495
- screen flows for  Disability wizard

Note that this PDF includes a few slides where I document some open questions that will guide conversation next week with Mikki, Peg, Liz and Danielle as we button-up/refine UX and content.

[Education_Disability_Wizards_Questions_for_Forms_3.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5169364/Education_Disability_Wizards_Questions_for_Forms_3.pdf)

**Comment by tlei123** [comment]
> here is the updated (and corrected) Questions for Forms diagram (PDF)

@johnhashva , thx for the updated diagram!  I'll check w/ Luke re. his BDD form-launch vis-a-vis his Disability Widget's eBenefits use-case \[I heard he's launching the Widget & Form together, but pls. correct me if you know I'm wrong].

@leahkeeler , the [Edu. Wizard Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_order=asc&group_id=202) have been updated accordingly -- Update via Fry/DEA (1990->5495) case now also added.

**Comment by tlei123** [comment]
Will update my TestRail Test Cases for upcoming IA/Content changes (#13367).

**Comment by leahkeeler** [comment]
closing per new requirements
