### ISSUE TITLE
Staging:  Fort Collins Nutrition Direct Sched= Yes Any Veteran.  Vet has Past Appt. Not able to schedule

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#13123]
![FTC_Nutrition_Can'tSchedule.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/6ccd5e4a-fa82-4c71-813e-3f3b438e3698)Note in Legacy UI, I am able to direct schedule.  
In VATS for Food/Nutrition has Direct Schedule = Yes any veteran.  
nacier.y.stowe@id.me has past appointment in Nutrition:   Zzftc Nutrition  08/24/2020@10:00  Inpatient/No Act Taken.  

Select Nutrition and Food
Select Fort Collins. 
Expected Response: System displays Choose your VA clinic for your nutrition appointment:  Would you like to make an appointment at Zzftc Nutrition?  
Actual Response:  System displays Choose a day and time for your appointment (request flow).

From the mock cdw:  {"etag":"dedc713c702d6149b431fbca9575375082f8f9603e2340cf3171c5914646145b","locationSID":1400079043,"locationIEN":"674","facilityId":"983","locationType":"CLINIC","locationName":**"ZZFTC NUTRITION",**"primaryStopCode":123,"primaryStopCodeName":"NUTRITION/DIETETICS-INDIVIDUAL","secondaryStopCodeName":"*Missing*","physicalLocation":"FORT COLLINS, CO","institutionSID":1400039292,"institutionIEN":"421","institutionName":"CHYSHR-FORT COLLINS","institutionCode":"983GC","patientFriendlyLocationName":"FORT COLLINS NUTRITION","medicalService":"NONE","appointmentLength":60,"**directSchedulingPatient":true,**"displayAppointment":true,"sta6aid":"983GC","vaStationName":"CHYSHR-Fort Collins

**Comment by marcynadeau** [comment]
this clinic does displays (albeit it has a friendly name):  {"etag":"1dd7e97165f631d2b0a813b75cbf1f4c06ec46e8e3500803269a85bf24194f5a","locationSID":1400079313,"locationIEN":"945","facilityId":"983","locationType":"CLINIC","locationName":**"ZZFTC C&P AUDIO BEV",**"primaryStopCode":203,"primaryStopCodeName":"AUDIOLOGY","secondaryStopCode":450,"secondaryStopCodeName":"COMP & PENS (C&P) EXAMS","physicalLocation":"FORT COLLINS AUDIO","institutionSID":1400039292,"institutionIEN":"421","institutionName":"CHYSHR-FORT COLLINS","institutionCode":"983GC","patientFriendlyLocationName":"**C&P BEV AUDIO FTC",**"medicalService":"MEDICINE","appointmentLength":60,"directSchedulingPatient":true,"displayAppointment":true,"sta6aid":"983GC","vaStationName":"CHYSHR-Fort Collins VA Clinic"}
![ZZClinicDisplays.PNG](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/46fd2622-e819-4c7e-8cd7-85eacc777c18)

**Comment by jbalboni** [comment]
When I check this, the 674 clinic does not show up on any appointments we pull from MAS. So I think either MAS should be returning appointments with this clinic or the clinic should not be returned to us for scheduling.

**Comment by jbalboni** [comment]
Closing based on conversations with @marcynadeau, seems like this issue is stop code exclusion related.
