### ISSUE TITLE
Form Detail Page - Basic Auth

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13125]
## Issue Description
Given we're going live with form detail pages 
and want to control the roll-out 
I want to implement basic auth so we can test functionality in a live environment.

---
## Tasks
- [ ] Implement basic auth for this path `www.va.gov/find-forms/about-form-` TBD if this works
  - otherwise manual for the ~top 40

## Acceptance Criteria
- Basic auth prevents access to all form detail pages 
- Pages that go out with Batch 2 will automatically be behind basic auth
- Pages are not on the sitemap

**Comment by ncksllvn** [comment]
When we decide to go public, these two PRs will need to be reverted -

1. https://github.com/department-of-veterans-affairs/vets-website/pull/14111
    - Excludes form detail pages from the sitemap
1. https://github.com/department-of-veterans-affairs/devops/pull/7535
    - Implemented basic auth

**Comment by ncksllvn** [comment]
This will be ready after today's deployment. It did two things -

1. Basic auth implemented for all pages that start with `/find-forms/about-form-`
    - See https://www.va.gov/find-forms/about-form-10-10ez
1. All form detail pages are excluded from sitemap
