### ISSUE TITLE
Empty facilitySidebar in node-person_profile

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#13137]
## Issue Description
In output files related to the `node-person_profile` transformer, the `facilitySidebar` field is blank when it should be populated.

 An example of this can be seen when comparing the GraphQL and CMS export builds in the `pittsburgh-health-care/staff-profiles/adam-fischer/index.html` file.

## Tasks
- [ ] Figure out why the `facilitySidebar` field is blank.
- [ ] Resolve issue, and verify the output matches the GraphQL content build.

**Comment by jhonnyoddball** [comment]
merged into [13113](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13113)
