### ISSUE TITLE
[CONSIDER] VAMC detail page should open in a new tab/window from FL

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13139]
## Issue
Currently, when a Veteran clicks on a location in the search results to view the detail page, he/she is able to navigate back to the search results.  However, for VAMC pages, the navigational flow is different and the Veteran is unable to easily return to the search results list in the event he/she wasnts to view information on another facility. 

## Consider
How might we make it easy to return to the search results/Facility Locator after viewing a detail page?
Should the detail page open in a new window or tab?

**Comment by davidmpickett** [comment]
@ryguyk review if this is still relevant for links on Facility Locator. Might also be a question for @laflannery

**Comment by ryguyk** [comment]
@davidmpickett I'm not clear on what problem this ticket is highlighting. Specifically, I don't understand the distinction between VAMC pages and other pages. I don't know what is different about the "navigational flow". In either case, the user should be taken to a different page, and from that different page they should be able to click the browser's back button to return to the facility locator.

That said, my hunch is that we don't want this. In recent work, we actually made the inverse change to [prevent clicks from opening a new tab](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11814). One AC on that ticket was to ensure that the back button would take the user back to the facility locator with the results from the previous search.

**Comment by laflannery** [comment]
This is not relevant - links should not open in a new tab. The ticket Ryan linked to above is the correct behavior and we should not be changing that back to what it was previously. My recommendation is to close this ticket.
