### ISSUE TITLE
Build FE template for Single Q/A

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13133]
## Issue Description
Given CMS templates have been built for the "Single Q/A" component
I want to begin building the FE template
so that this component is successfully used on VA.gov

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- This layer of the FE template (meat layer) is complete for this content type

## Screenshot of latest design 
![image](https://user-images.githubusercontent.com/55992116/92020590-622edd00-ed26-11ea-9554-4e72564c9d32.png)

**Comment by kelsonic** [comment]
Validated at http://preview-staging.vfs.va.gov/preview?nodeId=6889 🎉 

Closing this as the AC were completed + validated 🔥
