### ISSUE TITLE
Build FE template for Multiple Q/A

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13134]
## Issue Description
Given CMS templates have been built for the "Multiple Q/A" component
I want to begin building the FE template
so that this component is successfully used on VA.gov

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- This layer of the FE template (meat layer) is complete for this content type

- Example
  - https://vsateams.invisionapp.com/share/YJXZTKC6CN4#/screens/425192997

**Comment by ncksllvn** [comment]
Designs for multiple, https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-FAQ-Multiple.png

**Comment by jenniferlee-dsva** [comment]
http://preview-staging.vfs.va.gov/preview?nodeId=6898

I'm seeing a couple of missing /bugs in the FE. Noting here:

The CTA buttons should appear above the TOC links. 
In the CMS for this article, the CTA buttons are 'off' / not enabled  to repeat at the bottom of the page. 

The FE design and template logic are:
At least 1 CTA button is required. The buttons will by default appear at the top of the page in this order: 

- required H1
- required intro text block
- optional alert
- required at least 1 CTA button
- optional TOC links
- [etc...]

And then, _IF enabled inside the CMS,_ the buttons should display also at the bottom of the article content. In this article example here, the 'Repeat CTA buttons' checkbox is not selected, so shouldn't appear again at the bottom.

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/68d21ac2-95f6-4f52-99e1-2cc981c33106)

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/b227dbb7-e634-4712-a879-fc583074eb40)
