### ISSUE TITLE
Outreach & Events: Outreach Materials not being sorted into multiple pages on IE11

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1313]
## What happened?
The [Outreach Materials page](https://staging.va.gov/outreach-and-events/outreach-materials/) is using JavaScript to "chunk" a single page of events and materials into upwards of 18 unique views that can be navigated to using the pagination links at the bottom.

IE11 is not honoring this because of a console error: `Object doesn't support property or method 'forEach'`

Screenshot attached below.

## Specs:
- Device: HP laptop, Windows 10
- Browser: IE11

## Acceptance Criteria
* IE11 should hot throw a console error
* Page should be chunked into smaller groups
* Pagination links should work

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

---
![Screenshot (11)](https://user-images.githubusercontent.com/934879/63725932-6d048700-c821-11e9-9cb7-423e4e8b7904.png)

**Comment by jefflbrauer** [comment]
@1Copenut pls review again :) 
cc @ethanteague

**Comment by 1Copenut** [comment]
@jefflbrauer I verified this on Staging in my local IE11 box. Am not seeing the error any more and IE11 is sorting pages as expected. Moving this one to close.
