### ISSUE TITLE
[FE] "Invalid date" on Military History period of service

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13130]
## Background
"invalid date" was displayed in the on the period of service date section of Military information. 
This could be due to the fact that Veteran was still currently active in the military.

https://dsva.slack.com/archives/C909ZG2BB/p1599062697061300
![image.png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/3f67744b-5613-466a-83d9-7c30be1d3912)

## Tasks
- [ ] Update the "invalid date" bug

**Comment by erikphansen** [comment]
We do not know what API data caused this error so it's hard to know what the correct fix is. It's entirely possible that there was no end date provided in this case. I think that the safest fix for this is to simply render an empty string if the date data cannot be parsed. @tressaellen do you have any thoughts?

**Comment by erikphansen** [comment]
@tressaellen ping!

**Comment by erikphansen** [comment]
Added `needs grooming` since the AC for this is not clear.

**Comment by tressaellen** [comment]
@erikphansen I'm sorry I missed these notifications somehow! If there is an error, are you saying that we simply remove the entire date for that section? Or the error date? I'm nervous if it's just empty that might be confusing to users.

**Comment by erikphansen** [comment]
We would not show the date we can’t parse. I’m saying that in this case we would show `September 26, 2013 - `.

Adding some kind of error message would be a different chunk of work, I think. Without knowing why the date could not be parsed I don’t think we should change much

**Comment by tressaellen** [comment]
Is it possible to change the wording for 'invalid date'? Or is that some sort of system thing?

It makes sense to have it be blank if a user is still actively in that phase of the military, but if it's an issue and there's completely blank dates I think it might be confusing.

**Comment by erikphansen** [comment]
~Yeah we can change that text to anything we want.~ Well we can do anything, but right now that `Invalid date` is coming directly from MomentJS, the date library that we use. So changing the text from `Invalid date` to something else will be a little more involved.

The problem with this whole ticket is that we have no idea what data from the backend resulted in this user seeing `Invalid date`. So if a user is still active in the military, we don't know what data we'll get from the backend. That `endDate` might just be missing entirely. Or that `endDate` could be something like `'active'`. ¯\_(ツ)_/¯

So this is my proposal: if a date is just missing entirely, we don't try to parse the date. We'll just show a blank/empty string.  But if we get _anything_ from the server for a date, we'll still continue to try to parse it and if it fails we'll still report `Invalid date`. That might fix the problem with this particular user.

**Comment by tressaellen** [comment]
Oh, okay got it. Well then in that case, that sounds good to me. Let's move forward with that. Thanks Erik!

**Comment by erikphansen** [comment]
closing this since it can't be easily validated on staging.
