### ISSUE TITLE
Build FE template for Step-by-step

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13135]
## Issue Description
Given CMS templates have been built for the "step-by-step" component
I want to begin building the FE template
so that this component is successfully used on VA.gov

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- This layer of the FE template (meat layer) is complete for this content type

---

## Considerations
- Mobile impact on this template
  - #13036

- includes h1 down to end of step by step (right before page footer with was this helpful etc. also doesn't include tags up top)
  - <img width="400" alt="image" src="https://user-images.githubusercontent.com/13204473/92017221-702e2f00-ed21-11ea-8221-22644197c2ff.png">

**Comment by ncksllvn** [comment]
Designs for Step-by-step, https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-LCT-Step-by-step-screen-shots.png

**Comment by MickinSahni** [comment]
Node = 6899

**Comment by andaleliz** [comment]
@kelsonic is this ticket just to build the "meat" of the sandwich (no tags, or need help, etc)? 

The design linked above doesn't reflect Ryan's latest placement of the tags and the redesign of the page "footer" (which contains related articles, need help, etc), but everything between the thin gray borders is still accurate.

**Comment by andaleliz** [comment]
nvm I just re-read the AC and I see it specifically references the meat. Or, seitan if that's your jam :)

**Comment by andaleliz** [comment]
@kelsonic, [here are the mobile versions](https://preview.uxpin.com/192f5be770c74272f782765a19a196aed0a4a588#/pages/132512748/documentation/no-panels?mode=i) of this step-by-step template (2 screens in total)

I think the next step is for you to evaluate and determine whether or not any changes in the CMS are required to implement something like this. 

Do you want to set up time to go through it, or review/discuss async? I included documentation in hopes that it'd make everything easy to understand.

**Comment by andaleliz** [comment]
Also, I reviewed this with @ncksllvn Friday and he didn't see any major red flags with the design. 

This includes a modification/variant of the `additional info` component in the design system, and I'll review those changes with VSP. I think since this is a CMS template and won't use react, that's kind of a moot point, but wanted to let you know.

**Comment by ncksllvn** [comment]
@kelsonic for reference we have some design system JavaScript that is framework-free, https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/formation/js

**Comment by kelsonic** [comment]
Oh nice! I was about to just write some custom JavaScript for it 😂 thanks for sharing!

**Comment by kelsonic** [comment]
Would it be ok to close this ticket for now and we can open up a follow-up ticket for the mobile designs when they get approved by VSP? 🙂 
CC @MickinSahni @brianalloyd

**Comment by andaleliz** [comment]
@kelsonic question for you - did you see #2 in my documentation?
![image](https://user-images.githubusercontent.com/55992116/93370083-4c3d1400-f81e-11ea-8858-af25521d9b36.png)

I'm pretty sure that you said you didn't see anything that required the CMS team to be involved, but just want to double check that you can add this kind of guidance on the front end.  Thanks

**Comment by kelsonic** [comment]
That's a wysiwyg field so adding links should be no problem with current cms functionality! 🙂

**Comment by andaleliz** [comment]
Sorry I wasn't more clear - I'm referring to this guidance that I'd like to see added to the field people see when they enter the step heading:

>When content authors are filling out this template, put guidance that encourages them to succinctly call out the most important detail about that step.  Idea is that someone could get the gist of the step-by-step if they didn't open the details. Maybe this is something that is also called out in training?

**Comment by kelsonic** [comment]
So our team doesn't manage any of the frontend for the CMS content editor interface, so you would have to ask the CMS team to add that guidance (tooltip, label, etc.) in Drupal for that field 🙂

**Comment by jenniferlee-dsva** [comment]
@andaleliz - confirming what @kelsonic stated ^. Also FWIW, people do not really read the CMS instructional text that carefully. And -- philosophical for a mo -- we will never really be able to teach ppl how to write for digital if they don't already know how to do that. (We've already seen this with Pittsburgh.) What we can do within our control is to provide technical guardrails. Such as... 

For the field that creates each step heading - there will be a 70 character max limit. This doesn't guarantee that the text will be great, but it does ensure that the author will have to make tough choices about how much information to include in that header -- which indirectly (hopefully) steers them to summarizing succinctly the main point of the step. 

One Q - so the 'additional info' text expand UX: This is something that only shows via FE on only when the connection for loading is bad, correct? (Similar to the progressivve enhancement video loading behavior?)

**Comment by jenniferlee-dsva** [comment]
@andaleliz - if that 'additional info' expander component is something that has to be driven from w/in the CMS template, this won't work. The step-by-step template doesn't have that functionality in the CMS. 

If the expander ux behavior happens via FE - e.g., based on bad connection, we can implement it entirely on the FE. LMK if this isn't clear and we can sync. (you, ryan...kelson?)

**Comment by andaleliz** [comment]
>For the field that creates each step heading - there will be a 70 character max limit. This doesn't guarantee that the text will be great, but it does ensure that the author will have to make tough choices about how much information to include in that header -- which indirectly (hopefully) steers them to summarizing succinctly the main point of the step.

That makes sense, and will hopefully work. I will remove that suggestion from the documentation.

The expander behavior is in the template on mobile, regardless of the connection. This does help with possible download issues on mobile but also reduces the amount of scrolling and processing someone has to do to get an overview of what is needed.

@kelsonic reviewed this and didn't see anything that couldn't be implemented on the FE.

**Comment by andaleliz** [comment]
[VSP collab cycle review complete](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13626); no changes!

**Comment by andaleliz** [comment]
Passing along some feedback from @1Copenut in case our devs have questions:
> The expand/collapse accordions nested inside the subway map LIs should be tested for semantic HTML and axe validation as early as possible. There should be no issue, but sometimes certain elements upset the axe algorithm when nested.

**Comment by 1Copenut** [comment]
@andaleliz Thank you for passing this along!

**Comment by jenniferlee-dsva** [comment]
@kelsonic (fysa @RLHecht ) The step by step allows in-body alert component. I think the CMS team just enabled that with a release? Heads up - the FE preview doesn't currently show the added alert content (I just added). Just want to make sure we don't forget to enable that in the FE template when a user has added an alert. (Placement would be like in the screenshot: below the intro text block.)

**Comment by kelsonic** [comment]
Oh good catch! I'll make sure we get a ticket created to add that! That's probably in a lot of the FE templates for LC, so I'll make sure we add it in all of the ones that have that functionality 🔥

**Comment by jenniferlee-dsva** [comment]
Mucho appreciate mr. @kelsonic .  Should we create a separate ticket to include Last updated date at the bottom of each page too? I had assumed that was a 'global' part of all pages.

**Comment by kelsonic** [comment]
Definitely! I'll create one now 👍 

Alert content ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14008
Last updated date ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14009

**Comment by kelsonic** [comment]
Noticing images aren't loading because the images are cross-domain, but we can fix that in a subsequent ticket! 🙂 

You can see an example step-by-step node here now: http://preview-staging.vfs.va.gov/preview?nodeId=6899

Closing this ticket for now as the AC is validated! 🎉

**Comment by jenniferlee-dsva** [comment]
Thx @kelsonic - I just wanted to make sure you, @ncksllvn and @RLHecht are coordinating, so you are using the demo environment: http://learningcenter.demo.ci.cms.va.gov/ 

When Randi (and upcoming, also @lunascoop ) add new content for the learning center fields that the CMS team has added, Randi will make sure the prod content gets copied over to the demo enviro for you guys. 

I don't know if staging enviro reflects all the ongoing fields that the CMS team is continuing to add (and sometimes they have to fix bugs/omissions). Just want to make sure that we're able to easily preview in demo environment a close-to-live state as we get close to 1.0 release.

**Comment by kelsonic** [comment]
Awesome! We haven't made use of the demo environment yet but it will likely come in handy here soon as we continue to experiment + build out the boilerplate data for these new content types! 🙂

**Comment by jenniferlee-dsva** [comment]
So I checked this node in both prod and staging just to make sure I was looking at the latest. 

A couple things: 

When I added an optional info alert below the intro text, the preview did not display it.
Step 2 - Verify your identity - has a coronavirus alert enabled but the preview does not display it. 

Info alerts are optional components that can be enabled in the CMS. They can appear in a few places: 
1/ Right below the intro text wisywig block
2/  and below/within each step's  wisiwyg text block. 

Example - field schema:

required H1
required intro text block
`optional alert`
required CTA buttons (min 1 required)
optional TOC links
optional H2
required template body: 
step 1 text

- step 1 wisywig block
- `optional alert`
- optional screenshot

step 2 text

- step 2 wisywig block
- `optional alert`
- optional screenshot
Etc. 
optional repeat of CTA buttons

**Comment by kelsonic** [comment]
The `optional alert` (called `fieldAlertSingle` from drupal) after the intro block is present in the `step-by-step` template, you can see that in the code [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/layouts/step_by_step.drupal.liquid#L28). If it's not working, it's likely that the CMS isn't sending it over to the FE.

The alerts within the steps are indeed missing, sending up a PR now to fix that! Thanks for catching this! 🙂

**Comment by kelsonic** [comment]
I've added support for `fieldAlert` for each step in the `step_by_step` template in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14441), but unfortunately they are coming as `null` or an empty object from Drupal, so we won't be able to visually confirm the implementation until this is fixed on Drupal's side

**Comment by kelsonic** [comment]
Validated + closing:

![image](https://user-images.githubusercontent.com/12773166/95483819-ef300c00-094c-11eb-9c72-8450dfe1825e.png)

The step by steps are not showing up currently due to their cardinality likely having been changed, which is being addressed in another ticket
