### ISSUE TITLE
GA Analytics - CC eligibility

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13163]
How many Veterans are getting a 'yes' when their eligibility is checked?

**Comment by lenaecb** [comment]
Is there a PR linked to this ticket? I was going to go in and see what we're seeing for this new event but didn't see the PR so thought maybe it's still in progress @grossb1 @jbalboni

**Comment by jbalboni** [comment]
I just linked it: https://github.com/department-of-veterans-affairs/vets-website/pull/14326

I think the PR just needs to be merged, unless I'm missing something @grossb1?

**Comment by lenaecb** [comment]
Gothca, yea, looks like it needs a merge. Can you do the honors if there's nothing else to do here @grossb1 ?

**Comment by grossb1** [comment]
Just merged it!

**Comment by lenaecb** [comment]
Awesome, thanks @grossb1!

**Comment by lenaecb** [comment]
@bsmartin-ep - you're seeing this come in too right?

**Comment by bsmartin-ep** [comment]
@lenaecb -

I see these events in production:
https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=cc-eligible-yes/

...and these events in non-production:
https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p184600834/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=cc-eligible-yes/
