### ISSUE TITLE
Access for Jasmin Smith

### ISSUE THREAD

**Issue by jsmithVA** [department-of-veterans-affairs/va.gov-team#13166]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea @CourtneyBethea
- Please provide your name.
   > Jasmin Smith
- Please Provide your email.
   > jasmin.smith@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @department-of-veterans-affairs/thoughtworks
   > Role: QA
   > Company: ThoughtWorks
   > I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana / Sentry so we can
Modify / update Jenkins job configs
Kick off Jenkins jobs
Review Prometheus data, some of which is imported into the scorecard
Review Grafana data for the scorecard
Review logs in different environments to facilitate testing along the path to production

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCn/XRdHN71WmTwemH3IMmRdmqkfsGxrTpiZX4HsUL0+cZTQ2bdeXhn8mM5JGKeC27e4tiD9/ewYO0aKoHuIH7ExgvdmUqDIRtMT8IKPsa3A5pPH7byS77QjALJD9qp6j59SKP/ERc4zSTN0bodReaAJ7YGeTcsz81RRkXEv7ii+uv3MH5+A0OY/W2/T8Gd95LogVYR7GfK9w8cOtcr2CFWdvG6D0yVGBerLJA8yIT5mujSATYJ2xJzQ6EF/3aabp9G4zjN+KoFlgOD9xPn6n14fNU50tjFLfpG9nUtkdi18E760dIRJipnccPLqblU99qWIRNwRabiwIuwfOHMr1Mb jasminsmith@Jasmins-MBP.home
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
