### ISSUE TITLE
Analytics Implementation or QA Support for PCPG (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13167]
## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics implementation

- Who is this request for?

    - Jason Wolf (@Jason  (Slack) & @jason-gcio (GH))
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - eBenefits Team
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_  
    _Identify if PII is passed in URL or title tag_  
    
    - Domain: https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction
    - No PII
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - Launching ASAP (By end of Sept)

- Typical Website Interactions to Track

    - **Conversions - Understanding the User Flow:** _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._  
     ⬇️ **CHANGED - USE LINK HERE:** https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/
    - (Landing Page) https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/
    - (Intro with Wizard) https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction
    - (Basic Info) https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/basic-information
    - (Claimant Info) https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/claimant-address
    - (Status Selection) https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/status-selection
    - (Veteran Info) https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/veteran-information
    - (Review and submit) https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/review-and-submit
    
    - **Other User Interactions**: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - Review application has some accordion expansions but I don't think those need to be checked
    - There is some explanation text around what living on a military base means for the purposes of filling out the form (on [claimant address](https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/claimant-address) for example) but that might already be tracked in the Form System

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Auth not needed

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Auth not needed

- Certain conditions/responses that need to be reviewed

    - None

- Additional Comments

    - None

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Confirming receipt @jason-gcio ! Will review and be in touch shortly

**Comment by jonwehausen** [comment]
### Datalayer Specification

### Developer Notes
- This implementation can follow the standard set of events baked-in to the [forms library code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms-system/src/js/actions.js)
- The tracking prefix as [implemented here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/helpers.jsx#L148) for this form will [be](url) `edu-8832`

When implemented correctly, the following events will be available per our documentation: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md

cc: @jason-gcio Let us know if you and your team have any further questions with this

**Comment by jason-gcio** [comment]
When the wizard events are ready to go, will you just give us those or will we need another ticket set up for that?  you could just let us know and we could request them depending on how specific they are to our wizard...that way we have a specific convo about each question OR if ya'll have a way to simply cover all wizard questions?

**Comment by jonwehausen** [comment]
Good question and thanks for asking this! We're still finalizing the spec / next steps of deployment for the global wizard tracking... got a few questions I'm waiting for answers there. That said, I should have more information for you over the coming days on how we'll approach the deployment of that, what role if any your devs need to play... To your point, we're going to have one spec that dynamically can capture all of the questions and answers for all wizards under the same specification.

**Comment by jonwehausen** [comment]
### How To Wizard DataLayer Specification

Description/Screenshot of Interaction | DataLayer | Dev Notes
------------ | ------------- | -------------
Wizard does not load due to business logic around prior engagement with forms | `'event': 'howToWizard-hidden'` | N/A
User chose to start over the wizard | `'event': 'howToWizard-start-over'` | Pushed along with the user function to start the form over [(manually clears the session data)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/use_cases/business_logic.md)
Form field changes (clicks on radio button answers) | `'event': 'howToWizard-formChange'`,<br>`'form-field-type': '<form_component_type>',`<br>`'form-field-label': <question_text>',`<br>`'form-field-value': '<question_answer_or_form_value>',` | • `'form-field-type'` should populate with the class name, in this case `'form-radio-buttons'` ![image](https://user-images.githubusercontent.com/48527022/93485736-61bf4600-f8d1-11ea-9650-8c2f6f381b95.png) <br> •`'form-field-label'` should populate with the full question label<br>•`'form-field-value'` should populate with the value selected, in most cases here `'Yes'` or `'No'`
Received blue notice following a question answer <br> ![image](https://user-images.githubusercontent.com/48527022/93488746-b1534100-f8d4-11ea-8d54-68dc73afcdc4.png) <br> ![image](https://user-images.githubusercontent.com/48527022/93490255-40ad2400-f8d6-11ea-85bf-f2d7b88e2d3c.png) <br> ![image](https://user-images.githubusercontent.com/48527022/93491401-a3eb8600-f8d7-11ea-9086-00218c7eb200.png) <br> ![image](https://user-images.githubusercontent.com/48527022/93494152-b5825d00-f8da-11ea-9220-34b0916a6e25.png) | `'event': 'howToWizard-notice-displayed',` <br>`'reason-for-notice': '<description>'` | <br>`'reason-for-notice'` can populate with whatever free text level of specificity you all feel is necessary to understand why the user received the notice, for reasons that are ineligibility related, we can prefix with `ineligibility - `...(**e.g** `'ineligibility - not a service member or veteran'`, `'ineligibility - eligible for chapter 31'`, `'ineligibility - outside time period from active duty discharge`', `'chose not to apply now'`)
Click on link within blue box notice <br> ![image](https://user-images.githubusercontent.com/48527022/93496079-cb911d00-f8dc-11ea-92ec-14109038beda.png) | `'event': 'howToWizard-notice-link-click'` | 
User clicks button to apply now <br> ![image](https://user-images.githubusercontent.com/48527022/93489961-e44a0480-f8d5-11ea-83ba-d94edee335f9.png) | `'event': 'cta-primary-button-click'` | N/A
User clicks link to skip how to wizard <br> ![image](https://user-images.githubusercontent.com/48527022/93489251-49512a80-f8d5-11ea-83e5-e2ab93892d28.png) | `'event': 'howToWizard-skip-wizard-link-click'` | N/A

**Comment by jonwehausen** [comment]
@jason-gcio comments above cover the form and wizard dataLayer specification. 

Let us know any other questions you may have.

**Comment by jason-gcio** [comment]
Thanks @jonwehausen - just to confirm, two question:
1. are these being added at the platform level for all these components or should we enter these into our feature?  
2. Also, for links ('event': 'howToWizard-notice-link-click'), this is for wizard-specific links, correct?
cc-ing @cohnjesse & our slack convo

**Comment by jonwehausen** [comment]
Hey Jason, great questions:
1. Since there are still some decisions that are being sorted out across all of the wizards as far as design, this can be entered specifically into your feature. We will revisit how these are instituted at a platform level when design has been finalized universally.
2. Correct, those are for the links that are within the blue box notices

**Comment by jonwehausen** [comment]
@jason-gcio,

### Read Me
- For reference, please refer to the latest revised [data layer specification for how to wizards](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13060#issuecomment-712852345)
- As it relates to our overall goal to standardize VA.gov How To Wizard tracking -- to understand the correlations / pattern differences between the CH36 wizard and succeeding wizards, used this [UX Preview as a reference](https://preview.uxpin.com/ca08f3dbf63475b2b62f3e8c00050ad1b19c4cb5#/pages/132986955/simulate/sitemap?mode=i)
- There are few differences that call for data layer adjustments here -- some of the items below are either to more broadly align with future wizards or tweaks for GA data collection purposes

### QA Results
Description/Screenshot of Interaction | DataLayer | Test Status 
------------ | ------------- | ------------- 
Clicks on form controls within wizard (radio buttons) | ![image](https://user-images.githubusercontent.com/48527022/96578379-1965c000-12a3-11eb-878e-58500453781f.png) | ❌ **DOES NOT PASS** - Functional firing of this event is correct, however please populate `'form-field-value'` with the full question answer text 
Clicks on links contained within alerts ![image](https://user-images.githubusercontent.com/48527022/96583490-cc85e780-12aa-11eb-872b-b5e8cd66dcc1.png) | `no event fired` | ❌ **DOES NOT PASS** - should fire a `'howToWizard-alert-link-click'` event on click
Clicks on primary button CTA to apply now at end of wizard ![image](https://user-images.githubusercontent.com/48527022/96583885-68175800-12ab-11eb-8eb3-52f98927ace1.png) | `no event fired`  | ❌ **DOES NOT PASS** - should fire `cta-primary-button-click` event
Skip wizard link ![image](https://user-images.githubusercontent.com/48527022/96584739-a7927400-12ac-11eb-96ec-e9437981b100.png) | `no event fired` | ❌ **DOES NOT PASS** - should fire `howToWizard-skip` on click
Visibility of wizard alerts | ![image](https://user-images.githubusercontent.com/48527022/96586005-584d4300-12ae-11eb-91ae-8e18830036aa.png) | ✔️ **PASS** -- Functional firing of this event is correct, however would like to request the `notice` be changed to `alert` though


### Summary of Adjustments to make
- [ ] Populate `form-field-value` with the full form value text as presented to the user within the form control
- [ ] Change where the word `notice` is used in spec and replace with `alert` to align with product verbiage -- `howToWizard-**notice**-displayed` and `reason-for-**notice**` should be changed to `howToWizard-alert-displayed` and `reason-for-alert`

- Events to be newly added: 
   - [ ] `'howToWizard-cta-displayed'` 
   - [ ] `'howToWizard-skip'`
   - [ ] `'howToWizard-alert-link-click'` 
   - [ ] `'howToWizard-hidden'`
    

cc: @johnhashva @bsmartin-ep @joanneesteban for visibility

**Comment by jonwehausen** [comment]
Hi @jason-gcio, 

Just wanted to touch base here, summary of adjustments & QA can be found above for when a dev resource is available to make these updates. 

Thanks in advance, 
Jon Wehausen

**Comment by jonwehausen** [comment]
### QA Testing
- @cohnjesse Here is the latest round of QA, for your awareness - and apologies in advance many of these updates refer to recent updates from our standardized wizard specification as we aim to standardize across all wizards. Please find the full data layer specification [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md): 

Description of Interaction | Data Layer Screenshot | Test Status
------------ | ------------- | -------------
Click on radio button option toggles | ![image](https://user-images.githubusercontent.com/48527022/99457559-2e149280-28f9-11eb-9bd9-9f384d8b6c8a.png) | ✔️ **PASS**
Receiving of notice within the wizard | ![image](https://user-images.githubusercontent.com/48527022/99457807-91062980-28f9-11eb-818d-0d6692080f29.png) | ⚠️ **DOES NOT PASS** -- event is **functionally firing correctly**, could we replace the word `notice` with `alert` here ?
When the primary button call to action is visible | N/A - **not currently firing an event** | ⚠️ **DOES NOT PASS**
Clicking of primary button ![image](https://user-images.githubusercontent.com/48527022/99458092-fa863800-28f9-11eb-8d02-e76993448cad.png) | N/A - **not currently firing an event** | ⚠️ **DOES NOT PASS**
Skipping the wizard ![image](https://user-images.githubusercontent.com/48527022/99459176-aa0fda00-28fb-11eb-8a2b-3f377b44d6e8.png) | N/A - **not currently firing an event** | ⚠️ **DOES NOT PASS**
Starting the wizard over ![image](https://user-images.githubusercontent.com/48527022/99459509-391cf200-28fc-11eb-97ba-0ed8a9a5259c.png) | N/A -- **not currently firing an event** | ⚠️ **DOES NOT PASS**

I have put a meeting on the calendar for us tomorrow 11/18 at 3pm EST to review these changes. Thanks again for your help here. 

cc: @jason-gcio @bmcgrady-ep @bsmartin-ep

**Comment by jonwehausen** [comment]
Prefix for CH36: `-careers-28-8832-`

**Comment by bsmartin-ep** [comment]
GTM workspace for this:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000387

**Comment by jonwehausen** [comment]
### Summary of Data Layer Changes To Make

@cohnjesse here is a brief list of the remaining data layer changes: 
- [ ] Pushed along with the the `'howToWizard-alert-displayed'` event, can we update `'reason-for-notice'` to be `'reason-for-alert'` ? (to align with business verbiage of "alert") 
- [ ] Pushed along with the `'howToWizard-alert-link-click'` event, can we also push a generic `'howToWizard-alert-link-click-label'` along with this event with the click text of the link? 
- [ ] When the "Apply" primary button becomes visible, push a `'howToWizard-cta-displayed'` event
- [ ] Push the `'howToWizard-start-over'` event when the "go back and answer the questions again" link is clicked: 
![image](https://user-images.githubusercontent.com/48527022/100138283-ceb80480-2e5b-11eb-9f39-4c8c18e27aa8.png)
- [ ] Could you also confirm for me if the `'howToWizard-hidden'' has been implemented? 

Thanks again for your assistance and let me know any further questions you may have here. 

cc: @joanneesteban

**Comment by joanneesteban** [comment]
@jason-gcio let us know if you have an update on this! We can get started on QA when you're ready.

**Comment by joanneesteban** [comment]
@jason-gcio circling back on this ticket. We're ready to review.

**Comment by jason-gcio** [comment]
For sure - let me double check with Jesse, I know he was working on this.

**Comment by cohnjesse** [comment]
@jonwehausen Updates have been made

**Comment by jonwehausen** [comment]
Connected with @cohnjesse 12/17/2020 on further DL updates for wizards and provided latest spec to be used universally https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md 

cc: @joanneesteban

**Comment by jason-gcio** [comment]
Remaining items are to be resolved in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17693

**Comment by jonwehausen** [comment]
### QA Testing of How To Wizard


| Description / Screenshot of Interaction | Data Layer | GTM Screenshot | Test Status
| -- | -- | -- | -- |
Skip the form and go to start application page | ![image](https://user-images.githubusercontent.com/48527022/103426025-60fea700-4b84-11eb-935c-2b50e0ff05e5.png) | ![image](https://user-images.githubusercontent.com/48527022/103426029-6c51d280-4b84-11eb-9c7f-ea57bea8adab.png) | ✔️ **PASS** 
Click on radio button toggle | ![image](https://user-images.githubusercontent.com/48527022/103425852-29dbc600-4b83-11eb-82b6-d18602f46adf.png) | ![image](https://user-images.githubusercontent.com/48527022/103425861-38c27880-4b83-11eb-9e99-11e29a69e55d.png) | ✔️ **PASS**
Alert displayed following radio button toggle | ![image](https://user-images.githubusercontent.com/48527022/103425968-0f561c80-4b84-11eb-8054-90636d585f86.png) | ![image](https://user-images.githubusercontent.com/48527022/103425985-20069280-4b84-11eb-8517-f2b4ebc15a7a.png) | ✔️ **PASS**
Click on link inside of alert | ![image](https://user-images.githubusercontent.com/48527022/103426008-37de1680-4b84-11eb-8d78-a0ced796c3fc.png) | ![image](https://user-images.githubusercontent.com/48527022/103426013-46c4c900-4b84-11eb-8bfe-25210dfe0c4e.png) | ✔️ **PASS**
CTA Displays to start form | ![image](https://user-images.githubusercontent.com/48527022/103425877-5859a100-4b83-11eb-9be4-419ec26ab719.png) | ![image](https://user-images.githubusercontent.com/48527022/103425897-73c4ac00-4b83-11eb-96c2-5a255a82abd5.png) | ✔️ **PASS**
Click on CTA to begin form | ![image](https://user-images.githubusercontent.com/48527022/103425922-a8386800-4b83-11eb-826e-f6441b4f8402.png) | ![image](https://user-images.githubusercontent.com/48527022/103425930-c2724600-4b83-11eb-90d4-4437b7072867.png) | ⚠️ **DOES NOT PASS** - _ @cohnjesse if we could adjust this to be according to this spec ![image](https://user-images.githubusercontent.com/48527022/103425948-e5045f00-4b83-11eb-92b9-aaf71592d661.png) 
Click on go back and answer questions again | ![image](https://user-images.githubusercontent.com/48527022/103426051-9905ea00-4b84-11eb-819c-b7225be891d1.png) | ![image](https://user-images.githubusercontent.com/48527022/103426059-a4f1ac00-4b84-11eb-8259-bfe726e1a977.png) | ✔️ **PASS**

----------------------------------

## QA Testing 
| Description / Screenshot of Interaction | Data Layer | GTM Screenshot | Test Status
| -- | -- | -- | -- |
Testing of _Submission_ event | ![image](https://user-images.githubusercontent.com/48527022/103426135-48db5780-4b85-11eb-9684-6ef83fc5aa30.png) | ![image](https://user-images.githubusercontent.com/48527022/103426142-58f33700-4b85-11eb-9dfd-56e9081de7a8.png) | ⚠️ **DOES NOT PASS** <br><br> _It appears there is an extra `-` prior to the submission, believe an extra `-` may need to be taken off the prefix to be consistent with our two `--` before submission_
Testing of _Successful_ submission event  | ![image](https://user-images.githubusercontent.com/48527022/103426187-a7a0d100-4b85-11eb-8470-f8679be5d400.png) | ![image](https://user-images.githubusercontent.com/48527022/103426198-b25b6600-4b85-11eb-8e58-573d9d6c3587.png) | ⚠️ **DOES NOT PASS** <br><br> _same thing here_ 

--------------------------------------

## Remaining Steps to Closure
- @cohnjesse please find the test results for the chapter 36 wizard here. Only adjustments here are: 
   - Correct the button event with our new taxonomy, as comparable to the one [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15757#issuecomment-752782990) - thanks in advance for your continued patience & efforts here. 
   - Correct the additional `-` populating before `submission` in each event
- @jason-gcio For your awareness, this is not effecting the collection of this data today, we are still actively collecting, these remaining changes are just for data consistency purposes. Once these are addressed, we can close out this implementation ticket.

**Comment by johnhashva** [comment]
@jason-gcio Howdy, since you will be first out (unless HLR beats you) with the Wizard on the intro/apply page, do you plan to create a Domo dashboard to track Wizard performance? @jonwehausen this is a question for Matt Self and his PMs as well (for Education and Disability Wizards).  Let me post a message on the How to Apply Wizards Slack channel to see how teams plan to approach this.

**Comment by jonwehausen** [comment]
Hi @johnhashva, great question! Let me discuss with @joanneesteban and get back with you -- Certainly agree it would make sense for us to create a generic how to wizard dashboard with these expected to roll out more frequently. 

@johnhashva 
- Would you consider [these ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites/how-to-apply-wizards#kpis) as your most up-to-date KPIs around how to wizards as a whole? 
- Secondary, please see comment here https://github.com/department-of-veterans-affairs/va.gov-team/issues/13060#issuecomment-754010917 for request to update the data layer for the education how to wizard. This would be great if we could get a developer to update in coming sprints. Thanks in advance

**Comment by johnhashva** [comment]
@jonwehausen 

- Would you consider these as your most up-to-date KPIs around how to wizards as a whole? **Yes**.

- Secondary, please see comment here #13060 (comment) for request to update the data layer for the education how to wizard. This would be great if we could get a developer to update in coming sprints. Thanks in advance  **Agree**

**Comment by jonwehausen** [comment]
Hi @cohnjesse, 

Just a reminder [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13167#issuecomment-753197641), if we could correct the following it would be very much appreciated: 
- Extra `-` before `submission`...End result should have 2 hypens before submission `--submission` and 1 hypen following with successful or failed `-failed` or `-successful` (this part is currently correct) 

Thanks so much @cohnjesse, this is the last piece and then we can close out!

**Comment by jonwehausen** [comment]
2/4 Reached out to ebenefits team on these remaining corrections -- fysa these are not affecting any data collection, but would be great to clean up for data consistency & cleanliness purposes.

**Comment by jonwehausen** [comment]
Testing results on 15757

Thanks again @cohnjesse
