### ISSUE TITLE
CT Site Search: Content Doc Updates

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#13170]
Update content document to support recent prototype revisions

**Comment by amyknox** [comment]
Content doc lives here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/search/design/content-doc.md

**Comment by ccruzgra** [comment]
Updated content doc to coincide with v0.3 of the prototype: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/search/design/content-doc-v0.3.md

Link to prototype: https://bahdigital.invisionapp.com/share/PVIAEVAXHK7

**Comment by amyknox** [comment]
Looks good.  I dropped a couple notes in the prototypes.  Just one other thing on the content doc: we talked about needing updates to the 107 learn more copy for the new question. A quick starter draft is below, 

> **Where you take classes determines your housing allowance**
> 
> Under the GI Bill you’re eligible to receive a monthly housing allowance whether you take classes in-person or online.  We calculate the monthly housing allowance based on where you take those classes. 
>
>If you're using Post-9/11 GI Bill benefits to take at least 1 in-person class, your housing allowance will be based on where you do most of your coursework. If you're taking distance-learning courses only, we’ll pay you a housing allowance based on 50% of the national average.
> 
> Through Dec. 21, 2020, current and new students can receive in-person rates if the school converted their approved program from in-person to online training due to COVID-19.
> 
> [View the current housing allowance payment rates.](https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp?_ga=2.144591223.39405460.1542131207-1582256389.1508352376)

**Comment by ccruzgra** [comment]
The content doc has been updated to reflect the mobile search UI enhancements.

@amyknox Would you like this to be added to the current prototype and content doc for CT Search and Filters?

**Comment by amyknox** [comment]
@ccruzgra - sure - if you have bandwidth to get that in, great. If not, we can work on it in Sp56.

**Comment by ccruzgra** [comment]
After discussing in UX Sync this morning, we will work on the above modal copy and integration into the prototype in Sp56.

**Comment by amyknox** [comment]
Will check with Devs during round table 9/11 to see if they need the Learn more modal content in the content doc.

**Comment by amyknox** [comment]
Yes, yes they do want all the Learn more modal content in the content doc.  WIP

**Comment by amyknox** [comment]
@ccruzgra - learn more modal content elements are now in the v3 content doc.
