### ISSUE TITLE
[Development] BDD & CST - Increase file upload size

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13178]
The Service Treatment Record (STR) a veteran gets from the DOD can be larger than 25 mb. Increase the file upload size to 50 mb for Evss claim documents.

Do not merge until after the limit has been increased in VBA and EVSS (anticipated date Sept 16, we've been emailing)

>Work item 1297928 has been created in the EVSS backlog for this.

**Comment by annaswims** [comment]
Note to self: do the same for CST

**Comment by luke-gcio** [comment]
Blocked until Sept 30 release from EVSS. Moved to Sprint 31.
