### ISSUE TITLE
[Development] BDD and CST - Increase file upload size

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13187]
## Issue Description
on http://localhost:3001/disability/file-disability-claim-form-21-526ez/supporting-evidence/additional-evidence (and possibly other pages within the form) we show a 25 MB upload limit. In coordination with EVSS/VBA and Vets-api, we will raise the limit to 50 mb. We anticipate them to be ready Sept. 16.

This change should be deployed on the same day or after the vets-api PR.
Back end issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13178

## Acceptance Criteria
- [ ] Unit tests pass
- [x] Messages have been updated for all BDD uploads
- [ ] Messages have been updated for CST uploads

**Comment by ndsprinkle** [comment]
Similar to #13209 where we may need to create a new custom component for 526/BDD to handle specific upload requirements for our form, so I will size this a little high.

**Comment by ndsprinkle** [comment]
Going to begin work on this today. May also pull in #13209 to work on simultaneously.

**Comment by ndsprinkle** [comment]
Will dig into this more today after dealing with the UAT submission errors from yesterday. There are actually a couple different upload components used for 526, BDD, and CST. At their core, they all share the platform file upload component, which supports customizing the min and max file sizes and file types, so it should be fairly straightforward to complete these tickets. The main struggle will be making sure I hit all the places that use file uploads, as there are many, and making sure I don't mess up our own ancillary form upload UI thing that is using the platform upload component.

**Comment by ndsprinkle** [comment]
Working on this more today after spending most of Friday diagnosing the PTSD issue we had with the veteran for BDD UAT.

**Comment by annaswims** [comment]
Limit was raised and now we see fewer files rejected.
<img width="1257" alt="Screen Shot 2020-10-14 at 4 36 19 PM" src="https://user-images.githubusercontent.com/19188/96045368-db4e4380-0e3f-11eb-97ea-9b28a772645a.png">

**Comment by annaswims** [comment]
My bad, this is the FE ticket and I think we might still need to update CST text.

**Comment by Mottie** [comment]
Text is updated in https://github.com/department-of-veterans-affairs/vets-website/pull/14720
