### ISSUE TITLE
Analytics Implementation or QA Support for Research Volunteer Portal

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#13198]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
 - Google Analytics implementation

- Who is this request for?
    - Patrick Bateman
    - [#va-cto-vaccine-trial](https://dsva.slack.com/archives/C01706RQ5MZ)

- What team/project is this work for?
  - Standing up the COVID-19 research volunteer portal on VA.gov. Work being done by the CTO health care team. More details: [product repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/covid-vaccine-trials).
    
- Provide the Domain where Google Analytics needs to be implemented:
  - All environments (dev, staging, prod)
  - No PII passed in tags.

- Please provide any upcoming deadlines or important milestones
  - Target soft launch is 9/9.

- Typical Website Interactions to Track
    - Landing page: /coronavirus-research
    - Form: /coronavirus-research/volunteer
    
- *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - Interested in how users are arriving at the landing page. Expect traffic from cross links on other VA.gov coronavirus content, email click throughs, social media click throughs, organic search, and direct entry.

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
  - No authentication required.
  - No test users needed.

- Certain conditions/responses that need to be reviewed
  - Not sure if this is relevant, but here is the [form schema](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/COVID-VACCINE-TRIAL-schema.json) 

- Additional Comments
  - Implemented the form using the VA.gov Form System and used GA prefix `coronavirus-research-`

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Confirming receipt @batemapf ! Thanks again, we will be in touch shortly

**Comment by jonwehausen** [comment]
## Update
- Did a run thru of the form in staging this AM, initial findings include: 
   - There is already a **`covid-research-volunteer--submission`**, **`covid-research-volunteer--submission-successful`**, and **`covid-research-volunteer--submission-failed`** event on form submission 👍

### Developer Notes
- Use the specification below to track prior to and on submission question respones
- As new questions are introduced or verbiage is changed, we will want to adjust our dataLayer values to capture those accordingly
- For the `form-change` event fires -- for most form components they should be tracked on click, however for text inputs those should be tracked on click away in order to avoid sending hits for each keystroke


### On Successful/Failed Submission Example

```javascript
   'event': 'covid-research-volunteer--submission-successful',
   'previously-diagnosed-with-covid19': 'Yes'|'No',
   'close-contact-with-positive-test': 'Yes'|'No',
   'recent-overnight-stay': 'Yes'|'No',
   'smoke-or-smoking-history': 'Yes'|'No', 
   'historical-health-issues': {"Allergy to any vaccines", "Autoimmune disease"},
   'work-situation': {"Employed (working from home)", "Student"},
   'work-transportation': {"Car", "Public transportation (bus, train, subway)"},
   'people-living-at-home': '1 to 2',
   'close-contact-outside-of-home': '0', 
```

### On Form Changes (prior to submission)
```javascript
{
   'event': 'covid-research-volunteer-form-change,
   'form-field-type': '<form_component_type>', //i.e 'form-radio-buttons', 'form-checkbox', 'form-datefield-day'
   'form-field-label': '<form_question_text>', //i.e 'Have you ever been diagnosed with COVID-19?'
   'form-field-value': '<question_answer_or_form_value>', //i.e 'Yes' or 'No', 
   'form-field-action': '<action_description>' //'clicked', 'checked', 'unchecked', 'changed'
}
```

### Next Steps 
- Ask any questions on this specification and begin implementation of dataLayer
- @bsmartin-ep to stage the GTM configuration leveraging this structure

**Comment by batemapf** [comment]
@jonwehausen OK if we edit a few of these fields you listed above? e.g. `recent-overnight-stay` --> `hospitalized-w-in-six-months` or something like that.

```
   'event': 'covid-research-volunteer--submission-successful',
   'previously-diagnosed-with-covid19': 'Yes'|'No',
   'close-contact-with-positive-test': 'Yes'|'No',
   'recent-overnight-stay': 'Yes'|'No',
   'smoke-or-smoking-history': 'Yes'|'No', 
   'historical-health-issues': {"Allergy to any vaccines", "Autoimmune disease"},
   'work-situation': {"Employed (working from home)", "Student"},
   'work-transportation': {"Car", "Public transportation (bus, train, subway)"},
   'people-living-at-home': '1 to 2',
   'close-contact-outside-of-home': '0', 
```

**Comment by jonwehausen** [comment]
Hi @batemapf , 

Yes sir, sure thing, certainly okay here to tweak according to the question context here. 

Thanks!

**Comment by stephenBarrs** [comment]
@jonwehausen we deployed the `covid-research-volunteer--submission-successful` event with the additional data to prod yesterday.  Is there work on the analytics side to surface that data (or work we need to do in GA)?  If not, can you show me how to see that data in GA?

**Comment by bsmartin-ep** [comment]
@stephenBarrs -

I am getting up the tagging for the additional data.  A few things...

- `recent-overnight-stay` seems to be missing from submission-successful.  Has that been removed?
- I renamed `smoke-or-smoking-history` to `smoke-or-vape-history` the dataLayer
- I see a few things in the dataLayer we aren't adding to the event action.  `zip-code, gender, race-ethnicity-origin, hospitalized-w-in-six-months, relationship-to-va`

cc @jonwehausen

**Comment by bsmartin-ep** [comment]
Ready for your QA @bmcgrady-ep:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000375

Warning - very beefy event action:

![image](https://user-images.githubusercontent.com/62304138/97609358-e2518600-19e9-11eb-8fa5-09cdf75b83d2.png)

cc @jonwehausen

**Comment by bmcgrady-ep** [comment]
### QA Testing 
cc: @bsmartin-ep @jonwehausen 

Interaction | dataLayer Screenshot | Test Status
-- | -- | --
Covid Research Volunteer Form Submission | ![image](https://user-images.githubusercontent.com/66263904/97746718-0ecbd780-1aa8-11eb-8d73-9885a4d9d9d0.png) | ✔️ **PASS**
Covid Research Volunteer Events tag | ![image](https://user-images.githubusercontent.com/66263904/97747458-3d967d80-1aa9-11eb-872b-177d0d250f76.png) ![image](https://user-images.githubusercontent.com/66263904/97747496-4dae5d00-1aa9-11eb-9473-7faa9633ea7b.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
### Update @bmcgrady-ep @bsmartin-ep zip code has been removed per PII compliance

**Comment by jonwehausen** [comment]
@stephenBarrs Thank you so much again for your work here! Official word as of 4:35PM EST 10/30 GTM changes have been published out to begin collecting the metadata of the submissions. :rocket:

One point we wanted to resurface here -- We are looking forward to surfacing this data within our COVID-19 DOMO dashboard, we know there has been discussion about wanting to see funnel data in order to analyze where users may be getting delayed within the form... since this is only a two-page form, in order to surface that data we would want to move forward with implementing the data layer events for form control changes. Please see slack notice here as well: https://dsva.slack.com/archives/C010AJ1L2EN/p1603727464001000?thread_ts=1603562554.000400&cid=C010AJ1L2EN

Let us know your thoughts and thanks again. 

cc: @joanneesteban @batemapf

**Comment by jonwehausen** [comment]
@joanneesteban Just wanted to re-surface this as we can now bring in submission data for the research sign-up into DOMO if we wish, however if we want to surface funnel data here, we will want to proceed with the component-level tracking.

If not of interest, implementation work has been completed here and this can be closed.

**Comment by joanneesteban** [comment]
@batemapf 

Let us know if you'll be able to track at the component level - this will allow us to surface funnel information for the Covid dashboard.

Otherwise, we can close out this ticket.

**Comment by joanneesteban** [comment]
Hi @batemapf @lalexanderson-dsva - we're in grooming & closing this ticket out. If you want funnels tracked here, please let us know. We can reopen this ticket, or have a new implementation ticket opened.
