### ISSUE TITLE
Claim file information

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13203]
## User Story

As a user, I can see the following file information for any claim:
- File requests from VA
- Descriptions of files being requested from VA

## Tasks
- [ ] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Android
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting

## Prototype
[Screen link](https://adhoc.invisionapp.com/share/JPYCWHEQ56N#/screens/427924948)

**Comment by bridgethapner** [comment]
Per usability testing, we are moving the file upload CTA to the status screen. Closing in favor of #13202.
