### ISSUE TITLE
GIBCT: Institution tags missing from search results

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#13208]
The search result "cards" for institutions should have labels as implemented in #11306. The tags are currently not displaying for search results.

### Steps to reproduce
1. Search for "divine word college" on in the comparison tool

### Expected Behavior:
Tags present on search result card

![dwc.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a94f5f09-6e24-4386-bd36-16bcac0b8def)

### Actual Behavior:
Tags missing from search result card

![Screen Shot 2020-09-03 at 1.14.53 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/adda1237-3dc4-4797-89f0-5b78bc7c6ad6)

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/14114

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-09-03 at 1.38.02 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/abb07629-24ff-4a15-b51b-055b83747f54)
![Screen Shot 2020-09-03 at 1.38.15 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2989a090-5eba-4ba4-b719-904d85a01e2e)
![Screen Shot 2020-09-03 at 1.38.33 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/70d7a63a-56dc-4458-876e-fc72ec2e2af6)

**Comment by delli-gatti-michael** [comment]
Tags are showing again. Closing this issue

**Comment by delli-gatti-michael** [comment]
Reopening this issue. The tags have gone missing again

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14134

Branch: bah-feature-flag-fix

**Comment by delli-gatti-michael** [comment]
Tags are showing again (again). Re-closing this issue
