### ISSUE TITLE
Upgrade Mocha

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#13211]
Mocha is currently on v5, while the latest release is v8. We should upgrade to the latest version.

The latest version supports running tests in parallel, which is worth exploring as it might eliminate flaky tests.

## Definition of Done 
- [ ] Upgrade Mocha to v8

**Comment by meganhkelley** [comment]
@U-DON is this actively in progress? what would be the approximate remaining level of effort to finish this?

**Comment by U-DON** [comment]
It's essentially complete and sitting in a branch. Just haven't focused on pushing it past the finish line.

There was also the question of whether the parallelization would resolve the flaky tests; it seems like there's a bit more work in exploring that, but we can do the upgrade independently of trying this parallelization feature.

**Comment by timwright12** [comment]
Adding the PR for good measure https://github.com/department-of-veterans-affairs/vets-website/pull/13982/
