### ISSUE TITLE
[Design] Create error message for when a user's Military Branch does not appear in Military Information section

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13220]
## Background
We discovered a bug where a Veteran's Military branch did not populate in the Military Info section. This occurs when we receive a "null" value.

![image](https://user-images.githubusercontent.com/60523453/93620516-1d52a980-f9a8-11ea-8209-40fc0344258d.png)

**https://www.va.gov/records/get-military-service-records/reconstruct-records**

## Tasks
- [ ] Create error message

## Acceptance Criteria
- [ ] The user is shown an error message notifying them that their military information could not load and the appropriate action to take to resolve the issue

**Comment by callen2563** [comment]
<img width="391" alt="Screen Shot 2020-09-17 at 11 31 28 AM" src="https://user-images.githubusercontent.com/68560244/93525871-7b6d8700-f8eb-11ea-88ec-fe9586e9ccce.png">
![image](https://user-images.githubusercontent.com/68560244/93525887-7f99a480-f8eb-11ea-845f-cae50af83901.png)

**Comment by peggygannon** [comment]
Hi, @callen2563 I recall working on a similar message for this ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11602

The final message we landed for that ticket is below. Would this message below cover the scenario you list above? 

**We can't load all of your information**
We're sorry. Something went wrong on our end. We can’t display all the information on this page. Please refresh the page or try again later.

**Comment by callen2563** [comment]
@sanlouise Hey Sandra, does Peggy's copy above work for this error state? Just wanted to also double check, is this the kind of thing where refreshing the page could fix the problem?

**Comment by callen2563** [comment]
@erikphansen see above

**Comment by erikphansen** [comment]
@peggygannon I think that my previous message ☝️  should be more or less ignored. I'm apparently blind and have been totally overlooking the "what if my service info doesn't look right?" blurb. I think that that is sufficient in this case. One suggestion: maybe if the service branch doesn't appear/is not available, we make that clearer and put `Unknown` instead of an empty string. If the Vet only has one stint of service it would be very easy for them to not even know their branch of service wasn't on record if we show an empty string.

**Comment by sanlouise** [comment]
@erikphansen Are you suggesting that we do not need a new Alert at all? The user will in any case be shown the "what if my service info doesn't look right" _blurb_,  which gives enough information for the user to figure out the next steps. I think adding 'Unknown' would be nice, but if that's what you meant, I agree that a new Alert would be redundant in this case and we may just need to close out this design ticket and I can update the FE ticket to reflect the 'Unknown' addition. @callen2563 Thoughts?

**Comment by erikphansen** [comment]
Correct. I don't think we need a special alert for this case.

**Comment by mshea0606** [comment]
@erikphansen @sanlouise  @callen2563  I agree that would be too repetitive. Closing this ticket.
