### ISSUE TITLE
[Design] Error alert for when Veterans are not showing up as Veterans with military information in the system

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13224]
## Background
See Slack convo:: https://dsva.slack.com/archives/C909ZG2BB/p1599156467141700

During UAT a Veteran did not show up in the system as being a Veteran with Military Information.  We should tell users when they aren't reported as being a veteran. We should let users know so they can fix it if they want to.

## Tasks
- [ ] Create updated error messaging

**Comment by callen2563** [comment]
@tressaellen @mshea0606 
I'm putting an estimate of 2 but let me know if you think we should change this. 
"2 - One should be able to deliver one 2 comfortably in a day"

**Comment by tressaellen** [comment]
Hi @peggygannon, could you look at this one as well? I reached out to patrick for the exact link, so we can fill that in when he gets back with us. I figure we can work on the rest of the messaging until we hear back.

We can’t verify that you are a Veteran
Our records indicate that you may not be a Veteran. If this is incorrect, please contact us at...
[How to correct military service history]

![Screen Shot 2020-09-17 at 3.55.25 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/380eafeb-0672-4dc8-b825-17dad8018dde)

**Comment by sshein** [comment]
I would caution against the line "Our records indicate that you may not be a veteran." Instead maybe "We cannot locate your veteran records" or something like that since as we discussed maybe their records just got burnt in that big fire. I'm sure Peggy has ideas :)

**Comment by peggygannon** [comment]
Hi, @tressaellen Can you tell me where the link "How to correct military service history" will take users?

**Comment by tressaellen** [comment]
Hi @peggygannon - I'm in the process of tracking that down. It'll most likely be this link:

https://iris.custhelp.va.gov/app/answers/detail/a_id/478/~/amend-or-change-dd-214-or-other-military-records

But it sounds like there's some other possible places that a veteran has to go. Here's a link to the [slack conversation](https://dsva.slack.com/archives/CBU0KDSB1/p1599156299323900). Also if you have any idea where this might need to go, that would be helpful as well!

**Comment by peggygannon** [comment]
Hello, @tressaellen Here is recommended message for this scenario. 

A question, will this link *"What is my military service information doesn't look right?"* show up on the page with this alert? 
 Or will this alert be the only thing shown on this page? The message under the link instructs the user to call DEERS, so I'm looking into if the new alert should also say that... am still checking on that. 

Also, I recommend we provide this link in the error alert:  https://www.archives.gov/veterans/military-service-records/correct-service-records.html

**We don't seem to have your military records** 

We're sorry. We can't match your information to our records. If you think this is an error, please call the VA.gov help desk at 844-698-2311 (TTY: 711). We’re here Monday–Friday, 8:00 a.m.–8:00 p.m. ET.

Or you can learn how to [update or correct your military service history]( https://www.archives.gov/veterans/military-service-records/correct-service-records.html).

**Comment by Samara-Strauss** [comment]
Moving to Sprint 31.

**Comment by tressaellen** [comment]
@peggygannon there will not be any other content on the page, it will just be the alert. But otherwise, I think this content will work great.

**Comment by tressaellen** [comment]
This copy has been merged.
