### ISSUE TITLE
Tech debt: Modify SASS files to remove linter warning messages

### ISSUE THREAD

**Issue by shawkey-daniel** [department-of-veterans-affairs/va.gov-team#13234]
As a developer, I need to modify SASS files to eliminate build warning messages

## Acceptance Criteria
- [ ] The sass linting warnings are removed from the following files

src/applications/edu-benefits/10203/sass/10203_stem.scss
src/applications/edu-benefits/sass/edu-benefits.scss
src/applications/gi/sass/gi.scss
src/applications/gi/sass/partials/_gi-profile-page.scss
src/applications/gi/sass/partials/_gi-search-page.scss

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-04 at 1.58.11 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a2a5dbaa-de1f-4fe4-9b74-dbe2baa61086)

**Comment by sonntag-adam** [comment]
Merged. Closing out story.
