### ISSUE TITLE
Rework table on Education Benefits page due to CMS bug

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#1323]
Table on Education benefits for survivors and dependents needs to be changed to two columns from three due to a CMS bug preventing the third column from showing up correctly on mobile apps. 

## Purpose

Table comparing DEA and Fry Scholarship benefits on [Education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) page needs to be changed to two columns from three due to a CMS bug preventing the third column from showing up on mobile apps. 

## What we need to do
Wording for the column headings needs to be changed so that the table can be condensed to two columns from three. 

### Screenshot (if applicable)
![Screen Shot 2019-08-27 at 1.49.49 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/0dcc4a62-c626-4aa5-8dbb-c6abfd735500)
## Def of Done
- [x] Table changed to two columns from three with all relevant info still incorporated
- [ ] Layout and text reviewed (Peggy Gannon/Jen Lee)

**Comment by jenniferlee-dsva** [comment]
@RLHecht - This looks so much better and more scannable! Few things: 

1/ Can you make the bolded subheaders on its own line, for all cells. (Like you have for "Programs covered:" subheader.) 
2/ Payment row should have same apples to apples label, so comparison is clear. Suggest adding "How payments are made" bolded header above what's there now - for both cells. 
3/ Break out "duration" info as separate rows for spouse and for children. 
4/ "Spouse gets both..." label seems to need 'can' - ?- "Spouse can get DIC and education...: Yes"

**Comment by RLHecht** [comment]
@jenniferlee-dsva I made all the changes you suggested. There is now a line space between all the heads and the body copy like in the last section but I can't tell if it looks like too much open space this way. Let me know what you think.

**Comment by jenniferlee-dsva** [comment]
@RLHecht  This looks good to go! Thank you so much for tweaking. (Yes, I agree the spacing looks a little more than ideal, but it's good enough to merge for this CMS bug problem.)

**Comment by RLHecht** [comment]
These fixes were made and branch was merged into master. Confirmed it's good on the live site.
