### ISSUE TITLE
Discovery: Map facility IDs

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1324]
As a developer, I want to map facility IDs from VAMF to the Facility Locator so that I can use facility locator data to show veterans the best facility information possible.

## AC:
- [ ] Documentation created in GH for whether it's possible to match Facility Locator facilities to facility IDs coming from VAMF
- [ ] If possible to match, documentation created in GH for how to match facilities in the two data sources

**Comment by kreek** [comment]
Based on the limited locations we can see with user `mhvvisn05` the facility ids are the same but are prepended with the type in the va.gov facility locator.

| Name                          | VAMF    | va.gov   |
|-------------------------------|---------|----------|
| WASHINGTON VA MEDICAL CENTER  | 688     | vha_688  |
| CHARLOTTE HALL VA CLINIC      | 688GD   | vha_688GD|
| FORT BELVOIR VA CLINIC        | 688GA   | vha_688GA|

**Comment by jbalboni** [comment]
Ah, looks like the data in staging for facilities doesn't use real ids, that's what threw me off. The Cheyanne VA is 442 in prod, but 983 on staging.
