### ISSUE TITLE
Access for Steven Templeman

### ISSUE THREAD

**Issue by templeman15** [department-of-veterans-affairs/va.gov-team#13241]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia LeeCecilia
- Please provide your name.
   > Steven Templeman
- Please Provide your email.
   > steven.templeman@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: DASH | Role: Backend Engineer | Company: Oddball

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+eaFlUQhAt/3nSAbZ7tPgAFAJE+WkCagRgZ/a9frZUT3HyaPb/dOETsk3t7LFjMwCPIxFEB+risnf7vAe/csTAPIh+l6TqQtSjMCefSrFZpeC/sq34SqyTo8efGYp1lB/AnkVOpVqrvMBqfTKZUfqoV309biu0KBZImsiU4Iq6ZN6ksSC31ayGMcSwONaE9XQ4AWFMz91zY6ODkpPY9WsCsmb3KCKowDvRtC9r+rTfaN/eeGE3ykBTgs1jS72O6QWa+1LgqRPbweTmlUay1910J7f+i+yJVWy5dw9W0OrTx5i7IztZdMYiCWHLjcWCIgKSiMsrNTm5mRnFVEAap/l steventempleman@Stevens-MBP.home
```

- Grant AWS Console access?
  > YES
  - Need AWS Console access for developing and maintaining the Lighthouse dev portal.

**Comment by templeman15** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
### For AWS Access:

User: Steven Templeman
COR: Cecilia Lee
Approval needed: @Jeff-Hayter

**Comment by jsev-io** [comment]
@templeman15 You should now have SOCKS proxy access, please verify when possible.

**Comment by templeman15** [comment]
@jsev-io I have SOCKS proxy access, thanks!

**Comment by emilygoodrich5623** [comment]
@Jeff-Hayter - re-pinging for attention - thank you

**Comment by drorva** [comment]
approved

**Comment by jsev-io** [comment]
![image](https://user-images.githubusercontent.com/63133731/94809044-06588200-03c0-11eb-833a-4feb07d32e5a.png)

Confirmed that eQIPs submitted
cc: @drorva @Jeff-Hayter @department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
User Provided AWS Access Credentials
