### ISSUE TITLE
Set up front end repo

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13247]
## Tasks

- [x] Add relevant documentation

- [x] Add standards for accessibility, testing, security

**Comment by jjulian** [comment]
https://github.com/department-of-veterans-affairs/va-mobile-app
https://github.com/department-of-veterans-affairs/va-mobile-app/blob/master/TESTING.md
https://github.com/department-of-veterans-affairs/va-mobile-app/tree/master/docs
https://github.com/department-of-veterans-affairs/va-mobile-app/blob/master/docs/Significant-Decisions.md
