### ISSUE TITLE
[Design] LIH Design Intent checkpoint

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13255]
## Background
[Collaboration cycle documentation visual](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)

[Design/Intent checkpoint requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#design-intent-collaboration)

[Design intent checkpoint ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13415)

You bring:
- Whiteboard sketch or other lo-fi prototypes or mockups
- A general idea of the toolset you intend to use in your designs

## Tasks
- [ ] Conduct Design/Intent VSP collaboration cycle meeting

**Comment by tressaellen** [comment]
The logged-in homepage design intent will be tracked in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13415).

Hopefully will be scheduled for September 22 at 11 EST (pending approval from platform)

**Comment by Samara-Strauss** [comment]
We are moving this out of Sprint 30 at my request. Removing that milestone. Should be Sprint 31 now.

**Comment by mshea0606** [comment]
@Samara-Strauss sounds good

**Comment by tressaellen** [comment]
Scheduled for September 24, 2020 at 1:30 ET
