### ISSUE TITLE
Protect Against Deploying the master Branch when master is not "Deployable"

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#13256]
### The Problem
Sometimes the `master` branch is not "deployable". We want an automated check during deployment that will fail out of the deployment in this event. 

### More Context
One example of `master` not being "deployable":
1. Daily auto-deploy occurs with severe bug
2. A new manual deployment is run using the previous release

`master` is now in a state "non-deployable" state. This can be a problem if another off-cycle deployment occurs where the engineers who perform the 2nd deployment are not aware of this state. (this actually happened 😄  - [link](https://dsva.slack.com/archives/CBU0KDSB1/p1599234036422700?thread_ts=1599170312.358000&cid=CBU0KDSB1))

### Work to be Done
- [ ] Discover best solution
- [ ] Implement said solution

**Comment by omgitsbillryan** [comment]
### Proposal 1
On the deploy job we could add 2 new job params:

```groovy
stringParam('block_future_deploys', '', 'When not blank, future deploys will fail with this message.')
booleanParam('override_deploy_block', false, 'Overrides a previous deploy block')
```

When a deploy happens where `block_future_deploys` is non-null, ansible will create a `.deploy_blocker` file in the `/app` directory with the contents of the file being the `block_future_deploys` job string param.

When a future deploy runs, we can add a jenkins or ansible step that checks for the existence of this `.deploy_blocker`, and fail the build so long as `override_deploy_block` == false.

**Comment by omgitsbillryan** [comment]
I had another thought to create a new "Rollback Deploy" job... but I'm hesitant to create new jobs. It would require the engineer to be aware of this new job, and nothing would stop them from going to the original deploy job they already know.

**Comment by jhouse-solvd** [comment]
@omgitsbillryan - was this in reference to the master branch of "vets-website" specifically? or all repos in general? curious to see if this is still relevant given much of the work that has transpired over recent months

**Comment by jhouse-solvd** [comment]
We wouldn't want to modify existing Jenkins jobs. But, we will want some sort of similar protection in the new deployment framework on the new infra. Moving to the icebox for now, and will consider at a later date.

**Comment by rmtolmach** [comment]
EKS has features to protect against this. For that reason, we're not prioritizing this in Jenkins.
