### ISSUE TITLE
Investigate plan to integrate Beta Enrollment feature into the Feature Toggles

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#1325]
Teams would like a way to do Beta/UAT testing with users that involves them clicking on a vanity url that navigates them to the Beta/UAT pages. This would occur for a set amount of time (2 weeks) before it turns off.  This will involve taking functionality from the existing beta enrollment feature and integrating it with the feature toggles work.

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/beta-enrollment/README.md 

- [ ] Investigate the integration efforts required
- [ ] Outline an detailed integration plan

**Comment by meganhkelley** [comment]
Closing ticket due to age, work will be tracked in new tickets if/when it is picked up.
