### ISSUE TITLE
New Facility selection page - Sort child facilities based on distance 

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13267]
As a Veteran who is making a VA appointment, I want VAOS to only show me the facilities that I care about and want to receive care from using my home address as a starting point. 

### Acceptance criteria:
- user is only displayed child facilities that: user is registered to, support the type of care selected
- if we have home/residential address for user, facilities are sorted based on distance from home/residential address
- if we don't have home/residential address for Veteran, we will default to showing facilities in alphabetical order
- facility information should include:
    - Facility name
    - City, State of facility
    - distance (in miles) from Veteran's home/residential address
- facility list should only display top 5 facilities at time - if more than 5 facilities returned for Veteran collapse those facilities into according that expands
- Content: page header & instructions should now include {type of care}

### Latest mock up: https://user-images.githubusercontent.com/12564977/92120405-023c4300-edc7-11ea-83fd-3729320a4816.png
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/8171b074-d6a7-47fb-bce3-758ca188ebdd)

**Comment by narin** [comment]
@lenaecb Do we want to fall back to mailing address if they don't have a residential address (or it is a PO box)? Or go straight from residential -> alphabetical.

**Comment by lenaecb** [comment]
I would fall back to the alphabetical for now @narin

**Comment by lenaecb** [comment]
@narin - can we make more small tweak and add 'home' to the address h2? This will maintain consistency with the VA profile settings and let the user know where that address is coming from. 

So update to: "Your _home_ address on file"

![Screen Shot 2020-10-08 at 10.23.02 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/1c21017e-138b-4cc7-b3d5-70d702694ce0)
