### ISSUE TITLE
New facility selection page - Use geolocation to sort child facilities

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13269]
As a Veteran who is making a VA appointment request, I want to use my current location instead of my home/residential address to sort the facilities I can go to for my care needs. 

### Acceptance Criteria:
- User can use their current location (based on their browser) to sort facility list
- Facility list should only include facilities: the user is registered to and that supports type of care previously selected
- List will display first 5 facilities; if more than 5 facilities returned collapse other facilities into accordion that can be expanded
- if we cannot establish current location for Veteran, default to showing facilities based on home address on file
- test scenario where user accepted/declined user location

### Latest mock up: https://user-images.githubusercontent.com/12564977/92120405-023c4300-edc7-11ea-83fd-3729320a4816.png
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/8171b074-d6a7-47fb-bce3-758ca188ebdd)

**Comment by lenaecb** [comment]
@rtwell - how do we want to account for after (state-wise) a user selects 'use your current location?'

**Comment by rtwell** [comment]
im thinking it is basically a toggle between residential addy and current location:

![image](https://user-images.githubusercontent.com/12564977/94151220-23350880-fe48-11ea-93ec-85428fa79458.png)

**Comment by narin** [comment]
@peggygannon @rtwell @lenaecb 

When you get a chance, I could use some guidance on a couple scenarios which I don't think are covered by the mocks:

**1. What should the top copy/section look like once a user has chosen and accepted the use of their current location? For now, I've come up with the copy below:**
![Screen Shot 2020-10-09 at 9 17 56 AM](https://user-images.githubusercontent.com/786704/95607339-72fefc80-0a10-11eb-9af9-34969dd48b6a.png)
**2. When the user hits "use your current location", they should be asked by their whether they would allow or block location.  We need to account for the scenario where the user hits "block".  I've come up with the following copy, but it definitely needs work or potentially some sort of alert/warning icon?**
![image](https://user-images.githubusercontent.com/786704/95607789-17813e80-0a11-11eb-9767-0f2c9a3d381c.png)
**3. Getting the user's location is asynchronous so I'm thinking we should display some sort of loading state.  What do you think of using the loading indicator along with this message?**
![Screen Shot 2020-10-09 at 8 38 44 AM](https://user-images.githubusercontent.com/786704/95608019-6e871380-0a11-11eb-89c3-a33ef099ca4f.png)

**Comment by lenaecb** [comment]
@narin gotcha, let's see what we can come up with here. 

@peggygannon let me know what you think based on the below + Narin's suggestions:
1. What you've mocked here locks pretty good Narin. Slight tweak I would make is the last sentence: "We have based this one the current location you have provided us." -- I used past tense here because the user did something to make the address up versus us doing it by default. Thoughts? 
    - Also separate question: @narin @rtwell - if a Veteran _does_ use the geolocation options, should we consider allowing them to change that back to their home address? (this would be an additional iteration and new ticket, but worth considering). 

2. @narin - Hmm, I am not sure a user will know how to change their browser location settings without guidance. @peggygannon - thoughts? I do think we should follow other alert patterns...

3. @narin - I love this suggestion and repurpose. Approve!

**Comment by peggygannon** [comment]
Hello, @narin and @lenaecb Let me know what you think of the recommendations below: I've tweaked the intro paragraph a bit. Let me know if the sentence about browser/location  works? Users get a pop up where they can "allow" or "block" their location, so I want to use same language, so they understand. Let me know if you think this'll work? 


{intro} Below is a list of VA locations where you’re registered that offer Primary care appointments. Locations closest to you are at the top of the list. We base these locations on the address you’ve given us. 

We can't find your location. Please make sure to choose "allow" if you get a browser pop-up asking for your location. 


Spinner language: 
Finding your location….

**Comment by lenaecb** [comment]
@peggygannon - should we also still include "try again" for the 'can't find your location' prompt?

Also, side note, our new designer had a good question/comment regarding the intro paragraph. He mentioned:

> My first instinct is to remove the line “Locations closest to you are at the top of the list” to reduce the cognitive load a bit. (It’s pretty clear in the UI that this is true.)
> If it is needed, I think that info would be most useful when a veteran starts scanning through the list of results, maybe next to the mileage on (only) the first result.

_I would tag him on this thread but he hasn't been added to the va.gov-team yet because they are still scheduling his orientation._ 

Anyway, thoughts on his comment and my question?
