### ISSUE TITLE
Full Accessibility & 508 Office Audit [Express Care]

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13272]
Requesting 508 audit for our latest feature - Express Care in the VAOS tool on VA.gov. 

## Artifacts - _please provide the following artifacts when you request a full review_
- Typical test user used for VAOS - Judy
- [You can find our completed accessibility checklist ticket here. ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12625)

## Additional Notes about feature
- [project brief for this feature here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/express-care-initiative.md)
- this feature is based on 'windows' of availability, so if you are not getting an 'active' state when you go in to test, let us (#vaos-team) know so we can change the backend system to active for you to complete your testing

**Comment by lenaecb** [comment]
hi @1Copenut - I wanted to check back in on this audit for the Express Care feature. It's only available at 1 VAMC right now, but I want to make sure we're getting eyes on it regardless. Thanks!

**Comment by 1Copenut** [comment]
@lenaecb Thank you for following up. I've been in a big hole lately, and haven't had a chance to review yet. I'm prioritizing this and a few other full audits as much as I can.

**Comment by lenaecb** [comment]
Sounds good @1Copenut 

We will have another 508 for an iteration on one of our pages we'll want you to look at soon. So you'll have another VAOS accessibility ticket soon for that too.

**Comment by 1Copenut** [comment]
@lenaecb I've completed the sweep through the Express Care feature for accessibility. I've logged the two most serious issues. Have five issues that are lower priority (four defect severity 3, one defect severity 4) and a handful of design/enhancement checks that I'll get entered tomorrow.

**Comment by 1Copenut** [comment]
@lenaecb This audit is complete so I've assigned it to you. LMK if you have any questions. I'll plan to send it to the VA 508 office for review later this week or early next.

**Comment by lenaecb** [comment]
Status - currently ticking away at some of these items.

**Comment by 1Copenut** [comment]
Quick test sent to the VA 508 office on November 4, 2020

**Comment by 1Copenut** [comment]
@laurenernest I followed up with the VA 508 office and CC'ed you on the email about the two small items they flagged on Express Care scheduling.

**Comment by laurenernest** [comment]
@1Copenut Thanks for following up! The last email I have is the one saying the issues were resolved. Can you send me the issue numbers for the new items reported so I can link them to this epic?

**Comment by 1Copenut** [comment]
@laurenernest Sure thing, I actually added them to this epic:
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/16293
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/16301

**Comment by laurenernest** [comment]
@1Copenut Thanks! Both are closed. Let me know if any other dev action is needed.

Keeping this epic open while we get decisions for the open design questions.
cc @outerpress

**Comment by laurenernest** [comment]
14 of 15 issues are complete. Remaining issue has been moved to the Design System team to review and is not specific to Express Care.
