### ISSUE TITLE
STEM: phone number field validation

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#13276]
Both "Home phone number" and "Mobile phone number" take all special characters instead of just dashes and digits.

Steps to reproduce:

1. Navigate to contact information https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/personal-information/contact-information
2. Observe screenshot below
##
Expected results: Do not allow special characters, only digits and dashes
##
![Screen Shot 2020-09-08 at 8.21.47 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5ee31633-0d30-4c95-87b8-71ebc30f3b1e)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14140
