### ISSUE TITLE
COVID-19 facts sheets

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13288]
## What's needed

Create 1 overall fact sheet for VSOs + 3 audience-specific tips fact sheets.

### Tasks

- [x] Research & write fact sheets (Danielle)
- [x] Copy edit fact sheets (Randi)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. First 2 fact sheets: 

[Health equity_VSO fact sheet_for copyediting_9.8.20](https://app.zenhub.com/files/133843125/ed90121a-df05-4556-9a1c-40dfc85d9fb2/download)

[Health equity_fact sheet for pregnant Veterans_for copyediting_9.8.20](https://app.zenhub.com/files/133843125/67b881b3-22a3-4726-b537-562805fa8d09/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here are the fact sheets with my edits. Let me know if you have any questions!
[Health equity_fact sheet for pregnant Veterans_for copyediting_9.8.20-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5190703/Health.equity_fact.sheet.for.pregnant.Veterans_for.copyediting_9.8.20-RH-edit.docx)
[Health equity_VSO fact sheet_for copyediting_9.8.20-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5190717/Health.equity_VSO.fact.sheet_for.copyediting_9.8.20-RH-edit.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht! I hope to have the final 2 ready for you this afternoon.

**Comment by DanielleThierryUSDSVA** [comment]
Fact sheet 3 of 4 for you, @RLHecht. Thank you!
[Health equity_VSO one-pager_Black-Hispanic-Indigenous Veterans 09.02.20](https://app.zenhub.com/files/133843125/abdf1f7c-deb0-4d0d-972c-7d5bbcad883b/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here's the third fact sheet with my changes.
[Health equity_VSO one-pager_Black-Hispanic-Indigenous Veterans 09.02.20-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5210316/Health.equity_VSO.one-pager_Black-Hispanic-Indigenous.Veterans.09.02.20-RH-edit.docx)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here's the fourth fact sheet with my edits.
[Health equity_VSO one-pager_Veterans over age 65_9.7.20.-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5218926/Health.equity_VSO.one-pager_Veterans.over.age.65_9.7.20.-RH-edit.docx)

**Comment by RLHecht** [comment]
Tasks are completed on this. Closing ticket. @DanielleThierryUSDSVA Let me know if these needs to be reopened for any reason. FYSA @MickinSahni @brianalloyd
