### ISSUE TITLE
Design Intent Collaboration – Facilities [Vet Centers]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13284]
## Instructions

1. Click or press the gear icon next to the "Labels" heading on the right. Search for your team in the labels list. If your team is not listed in the Labels menu, please leave a comment after you have created this issue. The Product Support team will create a new label for your team. -->
2. Text inside `<-- comment -->` blocks will not appear in your issue ticket. These comments offer guidance on what information you should provide for each section.

### For reference

* **VSP** - [VSP Design Rules of Engagement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/working-with-platform-design-team.md)

* **VSA** - [VSA Design Review Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#design-reviews)

* **Accessibility** - [Accessibility Best Practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md) | [VSA A11y Review Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md)

* **Content** - [VSP Content Rules of Engagement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/content-review-process.md)

* **IA** - [VSP IA Rules of Engagement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/working-with-ia.md)

* **Research** - [VSP Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-process.md)

## Product Name

Vet Centers

## Checkpoint Stage

- [x] **Design Intent** (for early discussions about needs, priorities, concepts, research planning, and direction)

### Where in the process is this? 

- [x] Initial concept

- [ ] Initial mockup

## Design links or mockups

[Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1599673587082/4caed61844c4e3665e9592e2b9467d0eaec8dc6d?wid=0-1600125104061&outline=open)
![VetCenter-Wireframe-Draft-V1](https://user-images.githubusercontent.com/4960080/93337697-79c29700-f7f7-11ea-8b2d-5c11da96fe71.png)

## Point of contact

Michelle Middaugh, Product Manager (Ad Hoc)
Leyda Hughes, Designer (Ad Hoc)

## Preferred times

Thursday, September 10 at 1:30 PM ET
Friday, September 11 at 2 PM ET
Tues, Sept 15, 1-5PM ET

## Next steps

This issue *automagically* creates a Zenhub ticket (assigned to Emily, Crystabel, Megan Kelley, Peggy Gannon, Shawna, Trevor and Jennifer), then VSP will convert this issue into an epic and schedule a design review. Feedback from the design review will be collected in the issue ticket. Be prepared to frame your design in the first ten minutes. Reviewers will have an opportunity to ask questions for five minutes each, and provide feedback in individual issues collected in this epic.

**Comment by jenstrickland** [comment]
@mmiddaugh Hi there, this ticket template is sidelined and replaced by the VSP Collab Cycle: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md

**Comment by CrystabelReiter** [comment]
Hi @mmiddaugh if you'd like to schedule a design intent please use this template: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+meganhkelley%2C+crystabelreiter%2C+emilywaggoner&labels=product+support&template=design-intent-collaboration.md&title=Design+intent+Collaboration%5BFeature-Name%5D

Please make sure to add the artifacts to the ticket at least 2 days before the desired meeting date.

**Comment by CrystabelReiter** [comment]
@mmiddaugh @lildziner When artifacts are attached, please also update the preferred meeting date times. We have a 2 business day turnaround for reviewing the ticket once all artifacts are attached. We have open meeting times all next week. Looking forward to it!

**Comment by lildziner** [comment]
Hi @CrystabelReiter I'm attaching a link to our [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1599673587082/4caed61844c4e3665e9592e2b9467d0eaec8dc6d) where @mpeterz and I have been iterating on a rough wireframe. This is the link to the [wireframe roughs within the Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1599673587082/4caed61844c4e3665e9592e2b9467d0eaec8dc6d)
Would Tues, Sept 14, 1-5 EST be possible?

**Comment by CrystabelReiter** [comment]
Hi @lildziner - once artifacts are attached to a ticket the review group needs at least 2 days to review. Tomorrow is not available, but we have Thursday (1:30-2:30pm ET) and Friday (2-2:30 ET) open 

You can reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and you can let me know and I'll schedule.

**Comment by lildziner** [comment]
Thanks @CrystabelReiter Still learning the process. Friday 2-2:30 ET seems to be the best time for all calendars. Artifact/links updated above. cc: @mmiddaugh

**Comment by CrystabelReiter** [comment]
No problem at all! I’ll schedule it first thing in the morning. Thanks!

**Comment by lildziner** [comment]
The artifact/link has been updated to include more notes and direction on content needs.
