### ISSUE TITLE
Access to ActionMailer Previews in staging environment

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#13289]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
For https://guides.rubyonrails.org/action_mailer_basics.html#previewing-emails can http://staging-api.va.gov/rails/mailers/ be made accessible?

In local environment the URL is http://localhost:3000/rails/mailers/

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

Enabling this for staging and dev environment would allow for easy previewing of the content of emails for review.  The content would not include any database information unless the previewer is setup to pull database information.  This is not needed in production as this in something to support development and QAs when designing and creating emails.

[Additional information about mailers](https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/mailer.md)

BAH team has recently done 10203 submission confirmation emails along with submission notification emails.
From slack messages in platform support it appears other teams are also adding more Mailers into vets-api so this would benefit any team working on Mailers who take advantage of ActionMailer Previews

Currently http://localhost:3000/rails/mailers/ looks like below so would expect to see same at http://staging-api.va.gov/rails/mailers/ 
![Screen Shot 2020-09-08 at 1 55 12 PM](https://user-images.githubusercontent.com/1094999/92511164-f2fc3180-f1da-11ea-9aa5-c88a87c306ca.png)

## Technical notes
_Notes around work that is happening, if applicable_
---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by amyknox** [comment]
If not completed in a previous effort, UX needs to test the privacy policy anchor link on the SCO email that this story would enable.

**Comment by jhouse-solvd** [comment]
@alexpappasoddball - let me know if this is something that is on your team's radar. ops can help from the url configuration / authentication perspective

**Comment by ericboehs** [comment]
I believe this is done.

**Comment by zurbergram** [comment]
https://staging-api.va.gov/rails/mailers/ is accessible
