### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#13280]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

No Channel in DSVA slack, we are the Bilby team (end-user experience) on VA API. And we will be using GA for a few things we have on VA.gov. The following folks need access: 
- braden.shipley@oddball.io
- Kevin.Lee@adhocteam.us
- bill.wanamaker@oddball.io

If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
_Please list any requirements, if any._

## Date Required
ASAP 😄 

## Product Team / External Team / VA Office
VA API, Biliy (End-user Experience) 
*Please leave the following blank*

---

### Definition of Done
- [x] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Thanks @ricetj , confirming receipt and have added folks listed to GA. They should have received an email indicating their access. 

We will close when we have validated GA can now be accessed.

**Comment by ricetj** [comment]
> Thanks @ricetj, confirming receipt and have added folks listed to GA. They should have received an email indicating their access.
> 
> We will close when we have validated GA can now be accessed.

Hey @jonwehausen looks like braden.shipley@oddball.io never got an email. Still checking with the others.

**Comment by jonwehausen** [comment]
Hi @ricetj 

Oops -- folks should have received an email. If not, can we confirm whether or not they're able to access GA directly? 

Thanks again

**Comment by jonwehausen** [comment]
Confirming @bradenshipley does in fact have GA access despite not receiving the email. Waiting to hear confirmation from other folks before closing out.

**Comment by jonwehausen** [comment]
Per slack conversation, confirmed with Braden Shipley appropriate folks now have access. Closing issue
