### ISSUE TITLE
On-Site Search:  Recommendations for Improvements 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1328]
**Discovery Goal:**
Goal of this discovery exercise is to evaluate how the on-site search works today (including any data points, historical information, analytics), what we can do to test making improvements to what we have today, and make recommendations on how we may improve this functionality.

**Background**:  
The on-site search has not been touched since the rebranding launch and transition to VA.gov.  We are at a point where we need to revisit search functionality and make recommendations for areas of improvements.  Many pages on the site have since been updated on VA.gov or added since the launch. 

**What we know about the on-site search today:** 
- Site search is integrated with search.gov. and they own the index. For any given search term, 
  we send it to them and receive a response back via their API. 
- Search.gov as a service is highly programmable with an admin account with our “search property”. (As in, you can log into search.gov and tweak various parts of the va.gov search experience.)
- We also have google analytics access and are connected to Site Search (Behavioir > Site Search).

**Comment by Karak888** [comment]
@Karak888 to send Info from @steve-gov to @jenniferlee-dsva to pick this up again and get specifics created.

**Comment by Karak888** [comment]
@Karak888 to add outline from Steve. K - Hasn't been touched in awhile but add document!!

**Comment by Karak888** [comment]
@jenniferlee-dsva as follow up I am including the outline that steve K. worked on with Chris (you already have just attaching to keep things succinct)!  Also including contact information for search.gov team so I keep it together!

(https://app.zenhub.com/files/133843125/8f036e07-0c74-4198-9a28-eb39b7d97fb4/download)

**Search.gov contacts:**
Dawn McCleskey (program manager) - QXD <dawn.mccleskey@gsa.gov>
Arantxa Piperova - QXD <arantxa.recio@gsa.gov>

**Comment by Karak888** [comment]
@ncksllvn since this is part of the discovery work which will be happening in this sprint, I am going to leave it in the Backlog until we have our grooming session on Wednesday.  At that point I will hopefully have our search.gov meeting scheduled and we can make some progress on recommendations, etc.  
:cc @jenniferlee-dsva

**Comment by ncksllvn** [comment]
You rock @Karak888!

**Comment by jenniferlee-dsva** [comment]
Also, per convo with Chris today: Mikkn at Ad Hoc used to be onsite search PM for last year's merger launch. He may be a resource for history and background info.

**Comment by chrisj-usds** [comment]
@jenniferlee-dsva To clarify my comment from our earlier conversation... Mickin did not work on VA.gov on-site search (or any other aspect of VA.gov). Rather, he was (as I understand it) PM for Search.gov itself, under a different contract between GSA (where search.gov resides) and AdHoc. Hence, my suggestion that he might have broad general knowledge about how search.gov works, who to talk to for issues or questions, etc.

**Comment by MickinSahni** [comment]
Yep, that's right; i'm new to VA and was the PM for search.gov. 

@Karak888 already reached out and I provided some quick suggestions re what might addressed: 
* Any problems we're currently seeing and/or outcomes we seek to enable [where updates to on-site search may be our Bet]
* Type of content being/to be indexed
* Anticipated changes to query volume
* Mitigating stability issues - driving this home (assuming it's one of our key problems) is going to be important. Though, they may not be able to respond/resolve as quickly as we'd like.

**Comment by chrisj-usds** [comment]
Thanks @MickinSahni 

I've not looked at the suggestions made by Steve (or any of the current discovery work going on) but I know there are a few things we can / should look at, including (in no order, and not limited to): 

- Capturing click events and sending them back to search.gov (bc I believe they use clicks as a prioritization mechanism?) 
- Providing better / complete sitemap so search results are more accurate
(Currently, our best search results are only hand-programmed Best Bets.) 
- Allowing for searching within a subdomain (requires UI work as well) so that I can search on just research.va.gov or washington.va.gov 
- Some others I don't recall since I started writing this response a week ago

**Comment by Karak888** [comment]
Discovery work is completed.  sitemaps for teamsites may not be included in sitemaps.  @Karak888 will add notes - preditice type-ahead can be explored.  Another item is configuring our search feature when subdomains- searches - long term potential have VA forms switch sql search with search.gov-

**Comment by jenniferlee-dsva** [comment]
@Karak888 @ncksllvn  - referencing past site search decisions and history here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/global/search

Perhaps we can start adding discovery, decisions, and plans for the next iteration (v.3)  of search work in this folder.

**Comment by ncksllvn** [comment]
@Karak888 Our current sprint might be pretty busy with dev work between the sidebar and Find a VA Form, but before our next sprint, we should definitely have a kickoff-ish meeting to help us organize our thoughts on search.gov and get some of these on our plate.

**Comment by aeltarhoni** [comment]
@Karak888 we are closing this one but please break down to a list of recommendations and actionable items.
