### ISSUE TITLE
[COGNITION]: STEM Standalone - CONSIDER reviewing the school email address for data safety

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#13298]
## [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The STEM standalone form has a question about the applicant's school email address. It's not required, so there's no validation (re-entry) field to confirm the address. I'd like the team to consider reviewing the purpose of this email address. Will the VA ever contact the veteran at this school email address, or ask the veteran to validate that the email is active? If the answer is yes, then this needs to have a re-enter the school email address field that becomes required if the veteran enters an address. Screenshot attached below.

/cc @CrystabelReiter && @KevinMHoffmanUSDS for visibility into a potential new pattern. We have seen some cases lately where data is being asked for that wasn't required, but becomes required when users enter a value. I think the use case of not requiring a field until we need to is valid, but want to confirm.

## Related Issue
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/12982

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] As a veteran, I want to be sure I enter my school email address correctly, and that the VA is validating fields match

## Environment

* https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/benefits/program-details

## WCAG or Vendor Guidance (optional)

Note: WUHCAG links provided additionally because they are generally more plain language, easier to understand.

* [W3C WCAG - Success Criterion 3.3.4 Error Prevention (Legal, Financial, Data) (Level AA):](https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-legal-financial-data.html)
* [W3C WCAG - Error Prevention (Legal, Financial, Data): Understanding SC 3.3.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-reversible.html)
* [WUHCAG - 3.3.4 – Error Prevention (Legal, Financial, Data) (Level AA)](https://www.wuhcag.com/error-prevention-legal-financial-data/)
* [W3C WCAG - 3.3.6 Error Prevention (All) (Level AAA)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-reversible-all.html)
* [WUHCAG - 3.3.6 – Error Prevention (All) (Level AAA)](https://www.wuhcag.com/error-prevention-all/)

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Screenshots or Trace Logs
![Screen Shot 2020-09-08 at 4 30 30 PM](https://user-images.githubusercontent.com/934879/92530639-6198b980-f1f2-11ea-8446-8421dc051ed3.png)

**Comment by desireeturner** [comment]
@1Copenut The intent of this email is to provide School Certifying Officials (SCOs) with user information that can be utilized to verify the applicant's identity upon receipt of the email notifying SCOs that a student has applied to for the scholarship with intent to use it at their institution. This functionality is not yet live so the information is not being utilized in this way yet, unless it is being done manually by the Buffalo RPO. This is always intended to be an optional field because not all students will have this information at the time they apply. 

To answer your specific questions:
- Will the VA ever contact the veteran at this school email address? No
- Will the VA ask the veteran to validate that the email is active? No

Let me know if you still believe this is an issue. Thanks!

**Comment by 1Copenut** [comment]
@desireeturner It doesn't sound like this rises to the threshold of needing a verify school email input at this time. If SCOs identity it as something they'll be using to contact veterans in the future, then we will need a second input to verify the email and the two fields must have matching values. Even if the field is optional, we want to ensure data correctness if it has bearing on the benefit award.

Please feel free to close this issue for now, or put it in the icebox to revisit later.

**Comment by desireeturner** [comment]
Sounds good. I will closed this out. And just to be clear, all contact with the applicant via email will occur via the email associated with their account, which is verified within the application.
