### ISSUE TITLE
[Bug] ClaimStatusTool and 526 Sending empty files to EVSS

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13293]
## What happened?
It appears that we occasionally have empty files uploaded.  They're 0Bytes by the time they reach s3 and we attempt to send them on to EVSS we should find out what method users are using to upload empty files and provide them with a useful error message, as we do on form 526

It looks like they're coming from the /v0/evss_claims/:evss_claim_id/documents endpoint, which I assume is the CST.  
[old sentry](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/120661/events/?query=Invalid+file+size) [new sentry](http://sentry10.vfs.va.gov/organizations/vsp/issues/452/events/?statsPeriod=14d)

CST and form 526 ultimately submit to the same endpoint on EVSS and we  should check that we're doing the same validation on the FE.  We see far more errors for files submitted through `/v0/evss_claims/:evss_claim_id/documents `

More details on the kind of errors we're seeing. https://github.com/department-of-veterans-affairs/va.gov-team/issues/10427#issuecomment-685936135

## Steps to Reproduce
Unknown, just kinda happens.

## Acceptance Criteria
- [ ] Figure out what goes on that S3 gets empty files

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ndsprinkle** [comment]
I feel like we've tackled a ticket on this issue before, but I'll have to dig and see if I can find it. We don't allow users to upload 0 byte files, so my guess is the file is being dropped somewhere along the submission line. I suppose it could also be something like the file fails to upload but we are still treating it like a successful upload? Not sure, I'll size this with some extra points since I don't have an obvious lead.

**Comment by annaswims** [comment]
Log in as user 229, and go to https://staging.va.gov/track-claims/your-claims/600202895/files

when I try to upload an empty text file `empty.txt` I see this screen.  It never goes away and there is no network traffic [
<img width="1613" alt="Screen Shot 2020-09-10 at 8 54 07 AM" src="https://user-images.githubusercontent.com/19188/92731822-91a3a200-f343-11ea-8617-d6748e3a1140.png">
](url)

**Comment by annaswims** [comment]
So, not exactly the problem I described, but also a problem with empty files.

**Comment by ndsprinkle** [comment]
Going to be working on this more today, haven't made too much progress.

**Comment by annaswims** [comment]
We are still seeing empty files.  I suspect there is more to this issue http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/120661/

**Comment by annaswims** [comment]
check out https://github.com/department-of-veterans-affairs/va.gov-team/issues/9970

**Comment by ndsprinkle** [comment]
And it is 100% the front end sending empty files to the back end? And not some issue where the back end is dropping them? I see the network request failed ticket you linked. I guess that could potentially be causing issues, but I'd have to find some way to test that and see if it still lets users continue with the form even when failing.

**Comment by annaswims** [comment]
I'll re-check. When I last looked at files (sept 2) https://github.com/department-of-veterans-affairs/va.gov-team/issues/10427#issuecomment-685936135. The back end had stored an empty file in S3 that later got passed to EVSS.

**Comment by annaswims** [comment]
[This sentry issue](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/120661/events/7746307/) connects to [this 0B file in s3](https://console.amazonaws-us-gov.com/s3/buckets/dsva-vetsgov-prod-evss/evss_claim_documents/f29abfad01e147bdbf747846bdac665d/6045aa0f-6979-449a-9e7f-b3848530a495/?region=us-gov-west-1&tab=overview) which is from [this api request](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log;filter=%257B%2524.named_tags.request_id%253D%2522fe4bf71c-45ae-4f21-a3f6-520ced361e02%2522%257D;start=2020-09-27T15:58:00Z;end=2020-09-27T16:00:00Z) to upload a file.  
looks like the `qqtotalfilesize` parameter would be helpful here and is not PII, so I'll see what I can do to get it logged properly. 
````json
 "params": {
            "tracked_item_id": "FILTERED",
            "document_type": "FILTERED",
            "qquuid": "FILTERED",
            "qqfilename": "FILTERED",
            "qqtotalfilesize": "FILTERED",
            "file": "#<ActionDispatch::Http::UploadedFile:0x00007f0dc86d9980 @tempfile=#<Tempfile:/tmp/RackMultipart20200927-25-16p2mzm.jpeg>, @original_filename=\"JPEG image 38.jpeg\", @content_type=\"image/jpeg\", @headers=\"Content-Disposition: form-data; name=\\\"file\\\"; filename=\\\"JPEG image 38.jpeg\\\"\\r\\nContent-Type: image/jpeg\\r\\n\">",
            "evss_claim_id": "FILTERED"
        },
````

**Comment by annaswims** [comment]
I added a PR to log [qqtotalfilesize](https://docs.fineuploader.com/tag/3.8.2/features/request-parameters.html)  unfiltered, which should definitively answer at what point the files have 0bytes. https://github.com/department-of-veterans-affairs/vets-api/pull/4985

**Comment by ndsprinkle** [comment]
Awesome :)

**Comment by annaswims** [comment]
[This sentry issue](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/120661/events/3369d6bcb2404df3b51b97b18fd9f4b3/) connects to [this 0B file in s3](https://console.amazonaws-us-gov.com/s3/buckets/dsva-vetsgov-prod-evss/evss_claim_documents/53ddcb8279c940801432285/fa1a7c2b-e31d-4fdd-9650-1fea7a9e3f79/?region=us-gov-west-1&tab=overview) which is from [this api request](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log;filter=%257B%2524.named_tags.request_id%2520%253D%2522337ed004-d60f-43c7-9df5-617d52aa2d9d%2522%257D;start=2020-10-01T01:45:00Z;end=2020-10-01T01:50:59Z) to upload a file.  
looks like the `qqtotalfilesize` parameter would be helpful here and is not PII, so I'll see what I can do to get it logged properly. 
````json
"name": "V0::DocumentsController",
    "message": "Completed #create",
    "payload": {
        "controller": "V0::DocumentsController",
        "action": "create",
        "params": {
            "tracked_item_id": "FILTERED",
            "document_type": "FILTERED",
            "qquuid": "FILTERED",
            "qqfilename": "FILTERED",
            "qqtotalfilesize": "1900175",
            "file": "#<ActionDispatch::Http::UploadedFile:0x00005602c7242bb8 @tempfile=#<Tempfile:/tmp/RackMultipart20201001-105-3vs6y9.jpeg>, @original_filename=\"IMG_4311.jpeg\", @content_type=\"image/jpeg\", @headers=\"Content-Disposition: form-data; name=\\\"file\\\"; filename=\\\"IMG_4311.jpeg\\\"\\r\\nContent-Type: image/jpeg\\r\\n\">",
            "evss_claim_id": "FILTERED"
        },
````

**Comment by annaswims** [comment]
Somewhere between when the browser sends a file and when it arrives in s3, we’re dropping the body of the file.  I know that the file was not empty to start, because the FE sends a param with file size, but the file is 0bytes in s3.

Ops - is there something that might periodically clear tmp files? The file gets written to a path like `/tmp/RackMultipart20201001-105-3vs6y9.jpeg` before it gets uploaded to S3.

VSP-Tools-BE -  The gems we depend on are really out of date - could you upgrade them and see if it helps?
* we’re using carrierwave 0.11.2 released May 06, 2016. The recent version is 2.1.0 released February 16, 2020
* we’re using aws-sdk-s3  1.9.0 released April 04, 2018. The recent version is 1.82.0 - September 30, 2020

**Comment by annaswims** [comment]
I was able to reproduce in prod.  

Interesting bits: it says 0bytes and 1.8 minutes and did not send anything to sentry from the FE
<img width="1343" alt="Screen Shot 2020-10-02 at 4 29 32 PM" src="https://user-images.githubusercontent.com/19188/94967192-9ab00b00-04cc-11eb-8463-f392a3cb8806.png">

<img width="272" alt="Screen Shot 2020-10-02 at 4 13 51 PM" src="https://user-images.githubusercontent.com/19188/94966815-e57d5300-04cb-11eb-9573-5b053f804047.png">

I tried to upload  [this 27mb file](https://github.com/department-of-veterans-affairs/vagov-content/blob/master/assets/playbook/downloads/VHA_Style_Guide_508.pdf) to https://www.va.gov/track-claims/your-claims/80390321/files

**Comment by annaswims** [comment]
uploading [this](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability/Disability%20526EZ/discovery/VBMSCoreUserGuide-Release_14_1.pdf) 23.8 MB file worked.

**Comment by annaswims** [comment]
I'm thinking there are two problems instead of one, so I wrote up this https://github.com/department-of-veterans-affairs/va.gov-team/issues/14425

**Comment by annaswims** [comment]
As of https://github.com/department-of-veterans-affairs/vets-api/pull/5059 we'll tell the user their file can't be empty and log the error to sentry.

**Comment by annaswims** [comment]
So... as of  https://github.com/department-of-veterans-affairs/vets-api/pull/5059 carrierwave should validate that the file is at least 1 byte.  

aws https://github.com/department-of-veterans-affairs/vets-api/pull/5031 and carrierwave gems were updated.

**Comment by annaswims** [comment]
related validation errors - I'd expect to see something like this http://sentry10.vfs.va.gov/organizations/vsp/issues/439/?project=3&query=+transaction%3AV0%3A%3ADocumentsController%23create+&statsPeriod=14d

**Comment by annaswims** [comment]
the problem exists in form526, but [we check if the body is empty](https://github.com/department-of-veterans-affairs/vets-api/blob/27e8132dfd1e125bcfe80661446229baa4743a8f/app/workers/evss/disability_compensation_form/submit_uploads.rb#L23) before sending to EVSS 

[new sentry](http://sentry10.vfs.va.gov/organizations/vsp/issues/1701/events/?statsPeriod=14d)

**Comment by annaswims** [comment]
new message http://sentry10.vfs.va.gov/organizations/vsp/issues/2757/

**Comment by annaswims** [comment]
I think we're no longer sending files with no body to EVSS (though some of the older jobs are retrying). I've made a PR to normalize the file retry to 1day https://github.com/department-of-veterans-affairs/vets-api/pull/5128

Now, we're telling people immediately when they've uploaded a file that appears to have no body.  It appears to be more of a mobile safari problem.... So maybe there's some digging to do on the FE?
http://sentry10.vfs.va.gov/organizations/vsp/issues/2757/tags/?statsPeriod=14d

**Comment by annaswims** [comment]
[this user](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log;filter=%257B%2520%2524.payload.path%2520%253D%2522%252Fv0%252Fevss_claims%252F81151357%252Fdocuments%2522%257D;start=2020-10-21T10:20:00Z;end=2020-10-21T10:30:00Z) uploaded a file - text.txt that is not empty according to the FE uploader `"qqtotalfilesize": "646"`but the BE says is empty and got an error response.  Then they successfully uploaded a .gif and then retried thes same text file `text.txt` and got the same error.  [new sentry](http://sentry10.vfs.va.gov/organizations/vsp/issues/2757/events/3b2e515a6ded4929a2764d8557d10b7e/?project=3&query=device.family%3A%22iPhone%22&statsPeriod=14d)

**Comment by annaswims** [comment]
I'm unable to reproduce this on mobile safari because I get stuck sooner. 
when I try to upload [this empty file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/fixtures/files/empty_file.txt)
the uploader tells me it's 
![IMG_1480.PNG](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/b0e4c875-f554-49ac-8832-6d4bfa41a3aa)![IMG_1481 2.PNG](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/abff6221-d4c9-4e80-8e56-eaa87f160425)

**Comment by annaswims** [comment]
The behavior has been updated so now the user will see a message "File size should be greater than 1 Byte".  we can update the text in va.gov-team/14752

**Comment by annaswims** [comment]
Closing as complete if the BE recieves and empty file it responds with an appropriate error message. Issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/14889 will address the FE issue
