### ISSUE TITLE
Rollback SAML Post Tracker

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#13297]
The [SAML Post Tracker](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13022) is only needed for debugging the SSOe integration project.  After diagnosing and resolving the drop in login success rates, this additional tracker (both the API endpoint issuing it and the JS code invoking it), can be [removed/reverted](https://github.com/department-of-veterans-affairs/vets-api/pull/4806).

**Comment by joeniquette** [comment]
this will be done before putting down login.gov blockers resolved
