### ISSUE TITLE
New Facility selection page - Create flat list of facilities

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#13306]
Fetch parent and child facilities for each and display as a flat list

### Acceptance criteria:
- user is only displayed child facilities that: user is registered to support the type of care selected
- implement feature flag to switch between new and old versions
- default to showing facilities in alphabetical order
- facility information should include:
    - Facility name
    - City, State of facility
    - distance (in miles) from Veteran's home/residential address
- Content: page header & instructions should now include {type of care}

### Mockup
https://user-images.githubusercontent.com/12564977/92120948-afaf5680-edc7-11ea-99cd-9e855f6292f2.png
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/fb5b7d2c-1e49-469a-a4c9-4d849e5712aa)

**Comment by narin** [comment]
Hey @rtwell, I'm working on the alphabetical list first and I have 2 quick questions for you:

1. For the alphabetical scenario, do we still want to limit the list to 5 items, and display the "+X more locations" expander link?  I think the expander definitely makes sense for the distance based sorting, but just want to confirm for the alphabetical.

2. In our current design (see below), we display any sort of request limit or error alert boxes below the list of radio buttons.  Since this list can get pretty long, I'm wondering if we want to continue displaying these at the bottom (and auto scrolling to them), or if we should instead display them in line, right below the selected radio button?

![image](https://user-images.githubusercontent.com/786704/93251444-0b270000-f749-11ea-8413-d53eec785183.png)

**Comment by rtwell** [comment]
for now:
1. let's keep the "+X more locations" for both list types (alpha or distance)
2. i like your suggestion of showing this inline. it's a clunky interaction that should probably be a modal at some point, but for now i think this makes sense.

**Comment by narin** [comment]
@rtwell Displaying in a modal should be the same LOE as inline, so I can go ahead and do that instead if you don't think it requires any additional design.

**Comment by rtwell** [comment]
I would make sure we're not inciting any 508 issues using a modal, but if we're ok there, I don't see why not

**Comment by lenaecb** [comment]
Prod release of this blocked by BE - https://issues.mobilehealth.va.gov/browse/VAOSR-994
