### ISSUE TITLE
POSTMORTEM - Autoloading rollback

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#13300]
## Linked Artifacts

[Autoloading BE Tools Rollback](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/postmortem-for-2020-09-03-rollback/Postmortems/2020-09-03-unscheduled-prod-deploys.md)
[StatsD Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/164)

**Comment by gunsch** [comment]
Policy updates:
- https://github.com/department-of-veterans-affairs/va.gov-team/pull/13301
- https://github.com/department-of-veterans-affairs/devops/pull/7566

**Comment by alexpappasoddball** [comment]
The work to resolve this has been complete and the autoloading PR has merged into production without issue.  Closing this postmortem.
