### ISSUE TITLE
[KEYBOARD]: Direct Deposit - Direct deposit form needs to allow keyboard users to traverse backward as well as forward

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1332]
## Description

The form to enter direct deposit data does a good job capture keyboard focus when moving forward through the DOM using `TAB`. It needs to allow users to traverse backward through the form using `SHIFT + TAB`, capturing the keyboard focus in the same way. Screenshot attached.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a keyboard user, I want to be able to traverse forward and backward through the direct deposit data form, without losing my focus outside the form.

## WCAG or Vendor Guidance (optional)

* [Keyboard: Understanding SC 2.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html)

## Screenshots or Trace Logs

![Screen Shot 2019-08-27 at 4.09.24 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/493bc0f9-3b04-476b-b3cb-1ab6a637dc1c)

**Comment by Justin-Pickett** [comment]
This will need some more technical discussions to resolve this issue. @erikphansen @mojaray2k .

**Comment by erikphansen** [comment]
This appears to be an issue with any and all instances of the Formation Modal component. We have the same issue with any of the modals you can pop open on the Profile page. Will continue to see if there's a fix but I suspect that component has some custom logic to handle tabbing (to override the browser's default tabbing behavior) so that it prevents tabbing to move focus to elements _outside of_ the modal.

**Comment by erikphansen** [comment]
yup, this function gets called if the browser tries to focus on an element outside of the modal. So we'll need to add some logic to determine if the user hit `tab` or `shift-tab` and handle things differently.

https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/f0259ddbf75207d40ecdf765b4dc08f17576cae4/packages/formation-react/src/components/modal/Modal.jsx#L77-L85

**Comment by erikphansen** [comment]
This PR fixed the Modal in Formation React: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/170
This PR will pull in the update to the website: https://github.com/department-of-veterans-affairs/vets-website/pull/10796

**Comment by erikphansen** [comment]
@Justin-Pickett since Trevor is out, can you validate that tabbing and shift-tabbing works as expected in the Direct Deposit modal (or any modal on the site)? Will have to test on staging as it won't be on prod until after our daily deploy in an hour.

**Comment by Justin-Pickett** [comment]
@erikphansen this has been validated by myself and @artistgreen.

Closing this ticket!
