### ISSUE TITLE
[Discovery] - IRIS Contact Center Research, Initial Outreach to teams

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13332]
Chante has provided us with contacts at 5 call centers that can help us understand the content authoring process.  We need to reach out to these contacts to figure out who we need to talk to and observe for our study.  It'll be helpful to answer the following questions to help us determine what and who we want to observe for further research sessions:

- What are the roles on these teams?
- How many people are in each role?
- High-level overview of content authoring/management process? 

We'll be reaching out to people at the following centers, per Chante:
- Health Resource Center (HRC)
- Veterans Experience Office Tier 1 Contact Center
- National Cemetery Administration (NCA)
- Office of Care Coordination (OCC)
- Debt Management Center (DMC)
- National Call Center (NCC)

Acceptance Criteria
- [x] Sessions scheduled with call center contacts
- [x] Questions above have been answered by call center contacts

**Comment by andaleliz** [comment]
Have scheduled sessions with all except NCC (waiting to hear back). Sessions will run from 9/29 - 10/9.

**Comment by MickinSahni** [comment]
May have a direct line to the VACO NCC coordinator

**Comment by andaleliz** [comment]
All sessions have been scheduled!

**Comment by andaleliz** [comment]
10/9 session rescheduled to 10/16

**Comment by andaleliz** [comment]
All sessions completed.
