### ISSUE TITLE
[Design] Phase 1: Create 2-3 high-level concepts for LIH

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13330]
## Background
[Logged-in homepage design plan](Phase 1: Create 2-3 high-level concepts for logged-in homepage)

## Tasks
- [x] Create 2-3 high level concepts for LIH
- [x] Review with Matt/Samara

**Comment by callen2563** [comment]
@tressaellen @mshea0606 
I gave this ticket an estimate of a 5 based on the agile estimation guide: "5 - On the order of about a week or more to deliver"

**Comment by tressaellen** [comment]
![v1 desktop.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/3b423791-6cfb-45cf-bfb6-cfceaa9b9224)![v2 desktop 1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/848878d0-fd68-4794-92ed-61f217c8dff7)![v2 desktop 2.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/e5bc9398-59ac-446e-8731-54dc6904c6bc)![v3 desktop.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/d9d36623-c66f-45c6-a5aa-658dab77b2b7)![v3 mobile 2.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/3c991102-75b3-40c2-bade-a640df62dea6)![v3 mobile 3.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/7b3d8fde-dc56-429f-a46c-a04a2d5027ed)
