### ISSUE TITLE
CT: Fuzzy Search performance is hitting timeout threshold for searches

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#13335]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

Fuzzy search is not performant
![image](https://user-images.githubusercontent.com/1094999/92620578-c86cb000-f290-11ea-8511-2acae2fe8c47.png)

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_
Fuzzy search continues to work as expected but faster

## Acceptance Criteria
- [ ] _Describe the desired working behavior_
Fuzzy search continues to work as expected

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/716

**Comment by zurbergram** [comment]
```
  Institution Load (126.7ms)  SELECT  "institutions".* FROM "institutions" INNER JOIN "versions" ON "versions"."id" = "institutions"."version_id" WHERE (campus_type != 'E' OR campus_type IS NULL) AND "institutions"."approved" = $1 AND "institutions"."version_id" = $2 AND "institutions"."vet_tec_provider" = $3 AND (facility_code = 'CHARLESOTN' OR institution % '%charlesotn%' OR UPPER(city) = 'CHARLESOTN' OR UPPER(ialias) LIKE '%CHARLESOTN%' OR zip = 'charlesotn') AND "institutions"."institution_type_name" != $4 ORDER BY (COALESCE(SIMILARITY(ialias, 'charlesotn'), 0) * 1) + CASE WHEN UPPER(ialias) = 'CHARLESOTN' THEN 1 ELSE 0 END + CASE WHEN UPPER(city) = 'CHARLESOTN' THEN 1 ELSE 0 END + CASE WHEN UPPER(institution) = 'CHARLESOTN' THEN 1 ELSE 0 END + (COALESCE(SIMILARITY(institution, 'charlesotn'), 0)) + ((COALESCE(gibill, 0)/CAST(17635 as FLOAT)) * 0.33) DESC NULLS LAST, institution LIMIT $5 OFFSET $6  [["approved", true], ["version_id", 4], ["vet_tec_provider", false], ["institution_type_name", "OJT"], ["LIMIT", 10], ["OFFSET", 0]]


```


vs old
```
  Institution Load (243.3ms)  SELECT  "institutions".* FROM "institutions" INNER JOIN "versions" ON "versions"."id" = "institutions"."version_id" WHERE (campus_type != 'E' OR campus_type IS NULL) AND "institutions"."approved" = $1 AND "institutions"."version_id" = $2 AND "institutions"."vet_tec_provider" = $3 AND (facility_code = 'CHARLESOTN' OR SIMILARITY(institution, 'charlesotn') > 0.25 OR UPPER(city) = 'CHARLESOTN' OR UPPER(ialias) LIKE '%CHARLESOTN%' OR zip = 'charlesotn') AND "institutions"."institution_type_name" != $4 ORDER BY (COALESCE(SIMILARITY(ialias, 'charlesotn'), 0) * 1) + CASE WHEN UPPER(ialias) = 'CHARLESOTN' THEN 1 ELSE 0 END + CASE WHEN UPPER(city) = 'CHARLESOTN' THEN 1 ELSE 0 END + CASE WHEN UPPER(institution) = 'CHARLESOTN' THEN 1 ELSE 0 END + (COALESCE(SIMILARITY(institution, 'charlesotn'), 0)) + ((COALESCE(gibill, 0)/CAST(17635 as FLOAT)) * 0.33) DESC NULLS LAST, institution LIMIT $5 OFFSET $6  [["approved", true], ["version_id", 4], ["vet_tec_provider", false], ["institution_type_name", "OJT"], ["LIMIT", 10], ["OFFSET", 0]]
```

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by sonntag-adam** [comment]
In staging. Closing bug.
