### ISSUE TITLE
Everyone: Attend general Onboarding meeting

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1334]
## User Story

As a part of the VSP Onboarding process, I need participate in a general Onboarding intro session so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal

 Attend general on-boarding intro session for Benefits and Memorials  team.  

## Acceptance Criteria

General on-boarding session has completed with VSP team.   

## Definition of Done  

- [x] *Has been scheduled and completed * 

- [ ] *To be completed in Sprint 3 * 

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by smoonpeyes** [comment]
Done.

**Comment by ndsprinkle** [comment]
Done.

**Comment by YanaRoy** [comment]
Done.

**Comment by SMLuthi** [comment]
Done.

**Comment by YanaRoy** [comment]
All who were active members of the Benefits and Memorials team attended this session when it occurred.
