### ISSUE TITLE
[Discovery] How might we handle VA.gov auth/unauth states

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13348]
## High Level User Story/ies
As a VFS product team, I need determine how best to build on VA.gov in a way that accounts for auth and unauth states and the content, design, and technical implications of those decisions.

## How does this relate?
- Cerner where we have both states and questions about how we should handle that. But, that now means content is managed in code and not Drupal (see manual entry by Kelson for chalmers)
- Other teams (B&M2) struggled with launching products 
  - the drupal page goes live even though the post-sign-in flow is toggled via feature flags

## Questions
- How is auth content vs. unauth content handled?
- What should be in Drupal vs. not?
- How should content be written (if at all) to be generic enough for Drupal?
- What use-cases does this enable? A/B testing?

## Decision we're hoping to make
- The degree of content specification that is OK for unauth (rather than making it too detailed)

**Comment by MickinSahni** [comment]
Liz, Beth, Danielle, Kelson, Jen Lee to review and triage for prioritizing CMS bandwidth, etc. cc @brianalloyd

**Comment by jilladams** [comment]
Cerner effort has been underway with auth/unauth handling in place. No tickets tracking here, closing epic.
