### ISSUE TITLE
[Discovery] - IRIS Call Center Author Research, follow-up

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13340]
Follow-up with contact center teams to answer remaining questions.

**AC**
- [x] Sessions scheduled with HRC, Michelle HQ (IRIS admin), and NCC
- [x] Questions sent to: NCA, DMC, OCC, and VEO (this may end up taking place over phone calls)

**Comment by andaleliz** [comment]
@brianalloyd FYI moving this into the next sprint - I want to complete synthesis and have a comprehensive list of all my follow-up questions before I start reaching out to people for the next round of sessions.

**Comment by brianalloyd** [comment]
@andaleliz sounds like a good plan, thanks for the update.

**Comment by andaleliz** [comment]
Created a [google sheet](https://docs.google.com/spreadsheets/d/1zbiYwh-7jH2a88_wp3wMB9F2weGYCl9AvBsK9S2Hiiw/edit?usp=sharing) to track all the follow-up work needed.

**Comment by andaleliz** [comment]
Waiting to hear back from NCC and HRC regarding observation sessions and follow-up meetings. Also awaiting response from NCA for follow up questions

**Comment by andaleliz** [comment]
Completed follow-up today. Was not able to get responses from NCA scheduling and NCC content teams, but I think we're good with what we have.

**Comment by andaleliz** [comment]
Updating complexity on this issue due to LOE to track people down and the volume of follow up interviews that resulted.
