### ISSUE TITLE
IRIS Q&As Content Review: Batch 1 

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#13354]
First-draft copy of batch 1 to be reviewed  and copy-edited in preparation for presentation to SMEs and eventual Drupal build: 

[valc-non-benefit-faqs-copy-v0.2-091420.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5220127/valc-non-benefit-faqs-copy-v0.2-091420.docx)

- [x] PW to do first review and copy edit  (Randi)

- [x] DEPO to review copy (Beth)

- [x] PW to create new GH ticket for Drupal build of pages (Laura)

 ###Acceptance Criteria

- [ ] Copy deck ready for SME review

**Comment by lwalsh617** [comment]
@RLHecht -- I just attached the latest copy deck to the top of this ticket. LMK if you have questions. Thanks!

**Comment by RLHecht** [comment]
@lwalsh617 Here is the Word doc with my edits. I put some comments in there for both you and Beth as well. 
[valc-non-benefit-faqs-copy-v0.2-091420.-RH-edit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5225496/valc-non-benefit-faqs-copy-v0.2-091420.-RH-edit.docx)

**Comment by lwalsh617** [comment]
Thanks, Randi!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lwalsh617** [comment]
Thanks for the edit, @RLHecht!
@bethpottsVADEPO -- I accepted Randi's tracked changes except for where there are open questions. Here's the latest document for you to review. 
[valc-non-benefit-faqs-copy-v0.3-091520.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5227020/valc-non-benefit-faqs-copy-v0.3-091520.docx)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Thanks! Taking a look today.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Here are my edits on the first half of your batch 1. I uploaded this doc to Selina's ticket for implementation too. 

[https://app.zenhub.com/files/133843125/9a92d795-e34a-40af-a416-6aa0dd900132/download](https://app.zenhub.com/files/133843125/9a92d795-e34a-40af-a416-6aa0dd900132/download)

**Comment by bethpottsVADEPO** [comment]
I'm closing this ticket. The next phase of work (drupal implementation) is now captured in other tickets.
