### ISSUE TITLE
Mobile API Design: Letters and Documentation

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#13350]
## User Story
As a developer I want documentation for the API endpoint that will populate the letters and documentation screens so that I have schema to build against.

#### Definition of Done
- [ ] [Mobile API docs](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/mobile/docs) in the vets-api module include requests, responses, and schemas including an example of expected data.

#### Notes
- [Invision prototype screen](https://adhoc.invisionapp.com/share/JPYCWHEQ56N#/screens/427927553)
- [Figma service blueprint](https://www.figma.com/proto/RqG1G4ClpWbd7a09ZtLoxU/Mobile-App-Service-Blueprint?node-id=4%3A225&scaling=min-zoom)
- [Figma data tagging](https://www.figma.com/file/0SGZH6YNbMAPsdaHC4xIjl/API-Data-Tagging?node-id=0%3A1)

**Comment by srmyers17** [comment]
Outstanding Q: Where does the content come from?
- List is in the API
- Brief description of letter, where does that come from?
- Do we need to take into account internationalization for Letters? (How do we handle translating backend content?)

**Comment by srmyers17** [comment]
- Created documentation for initial letters call (list of letters)
- Need to decide how to deal with the content 
- Need to create doc for download calls
