### ISSUE TITLE
School Ratings: Create Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13359]
As a developer, I need to create a feature flag for the school ratings UI functionality so that it is not displayed in production as development is completed.

## Assumptions:
1. The Feature Flag is configured per environment.
    a. Feature flag for school ratings is available in both vets-api and vets-website repos.
2. When the feature flag is:
     a. Off: The school ratings section is not displayed.
     b. On: All of the UI work completed as part of epic #6234 is available in the given environment.
3. The feature flag is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. The Feature Flag `gibct_school_ratings` is available to be used for the ratings enhancements.
2. The Feature Flag description is: "Show/Hide the school ratings section of the Comparison Tool School Profile Page"

## Tasks
1. Follow feature flags documentation to create front-end school ratings feature flag.
2. Follow feature flags documentation to create back-end school ratings feature flag.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by ksantiagomorgan6** [comment]
Frontend PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14233

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-15 at 12.02.57 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f9d1c026-4ee3-4d0a-bb5a-e2c6a760730f)
##
![Screen Shot 2020-09-15 at 12.03.36 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1ec62dad-7ca9-4f2f-b733-4da59ac503cb)

**Comment by sonntag-adam** [comment]
In staging and production.
