### ISSUE TITLE
Mobile API Design: Appointments

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#13352]
## User Story
As a developer I want documentation for the API endpoint that will populate the appointments screens so that I have schema to build against.

#### Definition of Done
- [ ] [Mobile API docs](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/mobile/docs) in the vets-api module include requests, responses, and schemas including an example of expected data.

#### Notes
- [Invision prototype screen](https://adhoc.invisionapp.com/share/JPYCWHEQ56N#/screens/427924939)
- [Figma service blueprint](https://www.figma.com/proto/RqG1G4ClpWbd7a09ZtLoxU/Mobile-App-Service-Blueprint?node-id=4%3A225&scaling=min-zoom)
- [Figma data tagging](https://www.figma.com/file/0SGZH6YNbMAPsdaHC4xIjl/API-Data-Tagging?node-id=0%3A1)

**Comment by srmyers17** [comment]
@kreek for when we get to this, how much more effort is it to add in Cancellations? Asking b/c we learned that Facilities benefit from knowing about cancellations so that other Veterans can take those slots - so we may want to prioritize this higher than we originally thought.

**Comment by kreek** [comment]
@srmyers17 there's a few calls to gather the info that makes up a cancelation, but canceling itself on the backend it's pretty straight forward. I'd say it would take about half to a full sprint's worth of time for one backend developer.

**Comment by srmyers17** [comment]
Okay, good to know. We can see where we are come Sprint 4 and decide whether we have the time.
