### ISSUE TITLE
VSP content review: health care form emergency messaging

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#13355]
## User story
We need to add wording to remind Veterans  to not use this form for emergencies or urgent needs.

wireframe link with messaging is here: 
https://zpl.io/VOOek8j.

**Comment by peggygannon** [comment]
@kristenmcconnell Hello, please see my recommendation for the emergency message alert. Please let me know if you have any questions! 

1. I recommend this emergency message is placed earlier in the flow, to let them know as early as possible to not use form for emergencies. 

2. Below is content recommendations for emergency care alert. these content edits align with messaging we have on our static pages and other tools:

--also, please note that the phone numbers should be hyperlinked


{alert header} **Please don’t use this form if you need emergency care**

**If you have an emergency or urgent medical need,** call [911] or go to the nearest emergency room.

**If you need to talk to someone right away,** 
-	Call the Veterans Crisis hotline at [800-273-8255] and press 1, **or**
-	Start a [confidential Veterans chat]( https://www.veteranscrisisline.net/get-help/chat), **or**
-	Text [838255]

**Comment by kristenmcconnell** [comment]
@peggygannon Thank you. I agree and we do plan to have this information on the introduction page of the form (earlier in the workflow).
