### ISSUE TITLE
"at an ATLAS location" VVC Appt (Ad Hoc - ATLAS Associated & Mobile Any  ATLAS Associated)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13358]
### Acceptance Criteria: 
- **all Ad Hoc - Ad Hoc - ATLAS Associated & Mobile Any  ATLAS Associated appointments should display "Video appointment at an ATLAS location"** under the VA Video Connect card label (where date/time used to show)
   - ATLAS appointments are indicated by the presence of `tasInfo` in the data in the `vvsAppointment` array
- we've re-arranged the content for better flow and direction (see mock)
- "How to join your video appointment" directions for this appointment are "You must join this video meeting from the ATLAS (non-VA) location listed below
- Display appointment code to Veteran under "how to join"
- Display location address and directions for ATLAS location
- provider name should be populated (based on VCM designation) with "You'll be meeting with"
- if no provider name, do not display provider section
- all other logic existing for VVC cards (when button displays, 'prepare for video visit,' 'veteran not able to cancel in VAOS') still applies

### Latest mock here: ([Full mock here)](https://user-images.githubusercontent.com/12564977/92630323-ac234000-f29d-11ea-8d7a-f6758369290f.png)
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/5b35f1c4-05be-4917-ac50-5c7c7b06398c)

**Comment by lenaecb** [comment]
During implementation need to verify how the city/state information comes in. Current mock has it twice.

**Comment by rtwell** [comment]
> During implementation need to verify how the city/state information comes in. Current mock has it twice.

oops, that was my error from a copy/paste from [connected care's site](https://connectedcare.va.gov/partners/atlas).

![image](https://user-images.githubusercontent.com/12564977/92784794-e3185500-f374-11ea-891b-a2f414ee6ad9.png)
