### ISSUE TITLE
Mobile API Design: Claims

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#13351]
## User Story
As a developer I want documentation for the API endpoint that will populate the claims screens so that I have schema to build against.

#### Definition of Done
- [ ] [Mobile API docs](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/mobile/docs) in the vets-api module include requests, responses, and schemas including an example of expected data.

#### Notes
- [Invision prototype screen](https://adhoc.invisionapp.com/share/JPYCWHEQ56N#/screens/427924938)
- [Figma service blueprint](https://www.figma.com/proto/RqG1G4ClpWbd7a09ZtLoxU/Mobile-App-Service-Blueprint?node-id=4%3A225&scaling=min-zoom)
- [Figma data tagging](https://www.figma.com/file/0SGZH6YNbMAPsdaHC4xIjl/API-Data-Tagging?node-id=0%3A1)

**Comment by srmyers17** [comment]
- Jayson finished draft on Friday, in PR now and working with Patrick to finalize
- Jayson can still start implementation though

**Comment by srmyers17** [comment]
- continuously will be worked on as make decisions about what data we want back

**Comment by srmyers17** [comment]
- Overview doc design is merged
- Detail doc will be merged after the serialization
- Doc upload will be merged when it is complete
