### ISSUE TITLE
CT Filter: Remove 'gibctBenefitFilterEnhancement' Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13364]
As a developer, I need to remove the 'gibctBenefitFilterEnhancement' feature flag toggle and related functionality so that dead code is no longer in the codebase.

## Assumptions:
1. Feature flag creation story: #13041 

## Acceptance Criteria
1. The feature flag 'gibctBenefitFilterEnhancement' is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.
3. The functionality shown in SA1 is removed from staging and matches current production functionality.

## Supporting Artifacts:
1. 
<img width="1112" alt="staging_filter_functionality" src="https://user-images.githubusercontent.com/48260534/108525855-85325680-729e-11eb-9c97-ecfbc923eae2.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14593

**Comment by ksantiagomorgan6** [comment]
FE PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16112
BE PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5975

**Comment by sonntag-adam** [comment]
Testing passes QA
