### ISSUE TITLE
Zooming map stuck after unsuccessful search 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13368]
## What happened?
When a Veteran performs a serach to which no results are returned, the Facility Locator displays the appropriate error message but the user is able to enter new parameters and trigger a new search. However, the state is not cleared and the search never completes. The user is then stuck, unless the page is refreshed.  

For example: 
The following video begins by showing that `Community Providers (in VA's network)` + `Counselor - Mental Health` in `Polson, MT` is a valid search which returns at least two provider results. When a search for `Community Providers (in VA's network)` + `Poetry Therapist` in `Polson, MT` is initiated, the map zooms out looking for a match before failing to find one and displaying the appropriate error. When the user enters a new service type of Counselor - Mental Health, the search gets stuck (although this has been shown to be a valid search with results). 

https://www.loom.com/share/9d1a064729f2438fa7c8921bf645080f

A previous issue resolved a scenario in which the state was not cleared following a failed search due to invalid geographic search parameters. 

## Desired behavior
If the user refines the search parameters following a failed search, the Facility Locator should complete the search and return results when one or more provider matches is found. 
If the user refines the search parameters following a failed search, the Facility Locator should complete the search and display an appropriate error message if no matching results are available. 

## Acceptance Criteria
- [ ] Unit test has been added
- [ ] The state is cleared following a failed search resulting from any of the following scenarios:
      - [ ] Invalid geographic search parameters
      - [ ] Search which has timed out
      - [ ] No matching provider found for any facility type
      - [ ] Other reason (??)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brangi** [comment]
merged
