### ISSUE TITLE
IRIS Q&As:  Batch 2 Workplan

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#13365]
Create GH tickets for each of the 12 benefits categories, assigning to upcoming sprints. Tickets need to reflect a work plan that ensures the following tasks are completed for each benefit category:

- Draft copy 
- PW copyediting
- DEPO review
- Revisions per DEPO review
- SME review
- Revisions per SME review
- Drupal build
- PW QA of Drupal pages
- Depo review of Drupal pages
- Final revisions of Drupal pages
- Publishing

### Tasks

- [ ] PW to create GH tickets (Laura)

### Acceptance Criteria

- [ ] Tickets are on GH

**Comment by MickinSahni** [comment]
Open question - is it helpful to create a separate epic for the 12 benefits or should these 12 tickets go under #11516 @bethpottsVADEPO

**Comment by bethpottsVADEPO** [comment]
@MickinSahni Please attach the 12 tickets to #11516.

**Comment by lwalsh617** [comment]
Created 12 tickets and closing this one.
