### ISSUE TITLE
Move How to Apply Wizards - IA + Content Changes

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#13367]
### Status
**[2024-04-24]** Commented with question to Mikki... can this ticket be closed?

### Description

The move of the How to Apply Wizards from the How To content pages to the actual Apply Now pages introduces more complexity than anticipated based on the variety of use cases (example: authenticate, start application, go back to Wizard because as a user I am confused).

Additionally, with multiple product teams implementing the Wizards at the same time (also not anticipated), the need to establish design pattern guidance (along with a fresh look at the Wizards as common react component) is needed.
As a result, the team has outlined the following steps to ensure successful, steamlined implementation AND to ensure we deliver improved outcomes for service-members who are applying for benefits at VA.gov:

- More time/effort will be needed to articulate and illustrate "design system" level changes (including IA/UX, Content and Functional) to the Wizards that takes into account the new complexity and use cases introduced by moving Wizards to the applicaton pages.

- Changes outlined so far (some of which will require additional definition and illustration):

1. Include messaging to indicate the form the user will be taken to - this is already being done in some wizards.  Need to make messaging display consistent.   This will communicate to the user what form they should be completing based on their  wizard responses so they can more easily navigate/find a form in future sessions.  

2. 'Skip wizard' capability should be configurable for display/hide for each wizard - some wizards should not have it, while others should not.  Also need to consider scenarios where the wizard indicates that user is not eligible based on their responses but the skip option is still presented. 

3. Add content/link to "start over" and repeat wizard on introduction page. Option resets their current page with the wizard displayed as though they had not completed it yet.  If they had been taken to a different form from the initial wizard, they will stay on their current form introduction page with the wizard reset/displayed. 

4. Wizard is only bypassed when user is sent to a new form immediately after completing it on another.  Once the user navigates away from the application, or navigates to a new application, the user will need to repeat the wizard. 

5.  Allow ability to customize title of wizard.  This will allow the title to match the purpose/context of the wizard - find the right form, determine eligibility, etc. 

6.  Allow customization of skip wizard language/display properties on its context and importance.  Some wizards only need a small text link, others may need H2, etc. 

7.  POSSIBLE (via Tze): Save in Progress for the Wizard -- or if there are informational links, open those in another Tab (because right now, when you reload the browser, you lose your place on the wizard)

- Determine with Matt Self if the Education Wizard is needed on all application pages. For example, does the Wizard need to be on highly specific scholarship pages, including:
  - 0994 - Apply for VET Tech
  - 1990n - Apply for Education Benefits under the National call to service program
  - Form 22-10203 - Apply for Rogers STEM Scholarship

### Reference URLs

- Disability ([on Staging](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction))
- HLR (application almost ready, but Wizard dev has not yet started.)
  - [Prototype](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/430329538)
  - Wizard dev ticket is https://github.com/department-of-veterans-affairs/va.gov-team/issues/12925
- Education ([on Staging](https://staging.va.gov/education/apply-for-education-benefits/application/1990/introduction))
  - Rogers STEM ([application page on Staging](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction))
- Personalized Care & Planning Guidance ([new Wizard on staging](https://staging.va.gov/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction))

- Platform Review/Feedback
  - [IA Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12244)
  - Content Feedback
    - [Education Wizard](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12243)
    - [Disability Wizard](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12248)
    - [Chapter 31 and 36 Wizard](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12642)
    - [Updated messaging for wizard alerts](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13889)
    - Public Websites [Content Intake Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13028)
  - [Analytics Instrumentation Plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13060)
  - [Accessibility Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12211)
  - [Q-A Test Cases](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13124)

### Next Steps

- [X] Mikki will translate her [IA recommendations ](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31)into a format that allows for wider communication -- and use by Liz/Peggy/Danielle

- [x] Liz will create more specific design comps detailing important guidance/requirements

- [x] Peggy will work with Danielle to provide more specific content guidance for the teams

- [ ] John will provide this update to the all product leads (Education, Disability, eBenefits) as it may impact expectations and timelines -- and they can provide SME guidance on key questions -- e.g. should the Education Wizard go on all or select benefits pages?

- [x] We may conduct usability testing with veterans to ensure we can validate key changes outlined above before going back to the product implementation teams to finalize development for staging review. This will likely result in delayed implementation for the Education and Disability teams.

We will provide more details to all the involved product teams (BAM 1/2, Booz-Allen and eBenefits) at a meeting set for Thursday 9/10 at 10am EST.

**Comment by andaleliz** [comment]
I've created the issues related to my work on this.  It feels like a lot, but I believe there is a need to be very thorough and detailed in these deliverables since we've had a lot of confusion and churn with this effort so far.

#13374 
#13375 
#13378
#13379
#13381
#13382

**Comment by johnhashva** [comment]
Added me to to assignees.

**Comment by mnorthuis** [comment]
IA recommendations will be tracked in this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14193

**Comment by peggygannon** [comment]
Wizard content outlines are complete in Github. Tracked in [this ticket](//app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/13375) and linked below: 

- [x] Content outlines of wizard flows are completed in Github
    - [Education wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/education-forms-wizard.md)
     - [Disability wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/disability-form.md)
     - [Chapter 31 wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/chapter%2031-form-wizard.md)
     - [Chapter 36 wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/chapter%2036-form-wizard.md)
     - [Higher Level Review wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/higher-level-review-form-wizard.md)

**Comment by FranECross** [comment]
@mnorthuis Do you know if this old ticket can be closed? TIA!

**Comment by mnorthuis** [comment]
The wizard pattern has been deprecated and teams that are currently using it are working through how to move it to a sub-task pattern per their form requirements. There shouldn't be anything that PW needs to do in these efforts at this time.

**Comment by FranECross** [comment]
Closing per Mikki's note above.
