### ISSUE TITLE
Sample Content - 1.0 LC About Template

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13360]
## Tasks
- [x] Add sample content for the scenarios we want to test on the FE
  - Mobile responsiveness
  - Tables/Sample rates
    - e.g. SMC 

Node with sample text: prod.cms.va.gov/node/7910

## Acceptance Criteria
- [x] Sample content available for FE to build templates

**Comment by ncksllvn** [comment]
I think this is done, as we have been testing against CMS data while working on LC templates

**Comment by jenniferlee-dsva** [comment]
This is just the 'add sample About content' ticket placeholder for @RLHecht (so that FE work can happen). I don't think Randi is able to add the sample content yet because - AFAIK - the CMS template for this template isn't ready yet. 
@oksana-c @JeffBarnesUSDS @cmaeng can confirm ^ /provide eta.

**Comment by ncksllvn** [comment]
Oh I see, thank you. I don't see "About" mentioned though - should we edit the title to include that?

**Comment by oksana-c** [comment]
@jenniferlee-dsva @ncksllvn @RLHecht 
The "About" template will use "Learning Center Detail page" content type as mentioned on today's check-in.
Here's a link to create new content https://prod.cms.va.gov/node/add/support_resources_detail_page 

The CMS deployment on Sep 23 will introduce LC category fields `field_primary_category` and `field_other_categories`, so you may want to enter "About" type pages later in the afternoon.

**Comment by MickinSahni** [comment]
@andaleliz to drop in relevant tables e.g. DIC, SMC

**Comment by andaleliz** [comment]
- Check out the [SMC-L through SMC-N rates] table (https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/)
- See the Added amounts for surviving spouses table on the [2020 VA DIC rates for spouses and dependents page](https://www.va.gov/disability/survivor-dic-rates/)

**Comment by RLHecht** [comment]
Sample text has now been added. Link to node is at top of this ticket. Will let @kelsonic know as well. There was not an option for optional H2s underneath the button yet but I did add one in the WYSIWYG field.

**Comment by RLHecht** [comment]
Sample content has been added for FE to work on. Closing ticket.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - is this sample content available in the demo envir? 

(Just want to make sure we're always copying the latest content to demo, so FE can always do final validation there. It is also where I'll validate to make sure all the content fields are included in the FE template.)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I didn't do a bulk publish in the demo environment but when I look at the node there it has all the elements I added (learningcenter.demo.ci.cms.va.gov/node/7910). I am still a little confused on when I should be doing it. Does it happen automatically each day (like prod) so I only do it if I add more that wouldn't have made it? Or always the last step of me adding content to prod should be doing a content release in the demo environment? Sorry for the confusion!
