### ISSUE TITLE
[Design] Content & IA Review of HLR Wizard

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#13366]
## Issue Description
As a designer, I need to ensure that the designs for the HLR wizard are appropriate for VA.gov content guidelines and that the flow of the wizard is correct per IA requirements.

## Acceptance Criteria
- [ ] Content team has reviewed the HLR wizard and approved/updated content
- [ ] IA team has reviewed the HLR wizard and approved the flow/IA
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Design for the HLR wizard can be found here:  https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/430329537

Will be tagging up with @peggygannon to discuss/improve content and @mnorthuis to ensure the flow is correct per IA requirements.

**Comment by kevinstachura** [comment]
Spoke with Liz Lantz about the HLR wizard - there are some general changes coming down the pipeline for the wizard pattern as outlined in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13367), which will have implications on the FE design/visuals. Liz plans on addressing these changes via a design. Will be in contact with her this week to understand visual changes for the HLR wizard.

**Comment by kevinstachura** [comment]
Liz has created a ticket for the HLR changes needed: #13382

**Comment by kevinstachura** [comment]
@luke-gcio not sure if we want to close this ticket and just roll it into a new, larger one, as I will be working on the HLR wizard design this upcoming sprint. Rather than just confirming some IA and content items.

**Comment by luke-gcio** [comment]
Cloooosing out, new HLR design/ticket for wizard will be a separate effort.
