### ISSUE TITLE
CT Filter: Remove 'gibct_filter_enhancement' Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13363]
As a developer, I need to remove the 'gibct_filter_enhancement' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of 09/11/2020.
2. The new functionality is live in production with no need remaining need for the toggle.
3. Feature flag creation story: #11344

## Acceptance Criteria
1. The feature flag 'gibct_filter_enhancement' is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by sonntag-adam** [comment]
Flag is removed from all environments, closing story.
