### ISSUE TITLE
STEM: Remove "use EVSS" Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13361]
As a developer, I need to remove the 'stem_sco_email' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. This feature flag was created in #12467.
2. UAT has been completed for this effort as of 11/09.
3. The new functionality is live in production with no need remaining need for the toggle.
4. The limited production rollout is completed as of 12/01.

## Acceptance Criteria
1. The feature flag `stem_sco_email` is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5551

**Comment by sonntag-adam** [comment]
Closing story, in staging and prod
