### ISSUE TITLE
 Analytics Reporting Request for Leslie Byford 

### ISSUE THREAD

**Issue by Bester1987** [department-of-veterans-affairs/va.gov-team#13376]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Leslie 

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - I am developing a PPT deck  for Charles to present at the upcoming GITEC Emerging Award event. 
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
I am sending Charles his presentation for review and concurrence tomorrow, so if possible I would like the graphs by 9/10. 

## Analytics to Track Down
> - I am looking for visual representation, graph(s), which show positive usage/growth of VA.gov since the website redesign launch. The briefing I am pulling together focuses primarily on the VA.gov re-design as that is the award Charles has been nominated. 

## Other Helpful Questions to think through
- Who is your audience?
       General Public 
- Why do you need this data?
        A briefing deck for a short presentation. 
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
         I am hoping that providing visual(s) drives home to the audience that the re-designed website is more user friendly and 
         thus more Veterans are easily able to access the information that they need. 
- What area of the VA are you hoping to assess?
- How frequently do you need this data?
        This is a 1 time request. 

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
## VA.gov Migration Visuals
@Bester1987 here are 3 basic visuals that can help tell the growth story of the migration. Please let us know if you have any further questions here

### Total Pageviews
- This chart represents the total pageviews for VA.gov and for 2018 vets.gov
- Months January - July of 2018 represent months where only vets.gov was still live
- Months August - December 2018 represent when vets.gov was still live (and in the process of being decommissioned) and va.gov was being stood up -- leading to higher pageview totals from both sites. 
- **Key item to note is 2019 & 2020 VA.gov numbers are well above where we were with vets.gov alone at this point through the year in 2018**
![image](https://user-images.githubusercontent.com/48527022/92724443-9f9ff580-f338-11ea-8c7b-4a43132c9c55.png)

-----------------------------
### Total Users
- This chart represents total users of vets.gov (2018) & va.gov (2019 & 2020)
- 2019 and 2020 numbers represent only users of **modernized** content
- **Key item to note here is users have nearly doubled for the same month of the prior year dating back to 2018.**

![image](https://user-images.githubusercontent.com/48527022/92726049-058d7c80-f33b-11ea-8c36-0cf567477516.png)
-----------------------
### Customer Satisfaction Scores
- This chart represents customer satisfaction scores from our customer feedback survey software Foresee where veterans can anonymously submit their feedback  
- **Key item to note here of course is custom satisfaction averages are well above 2018&2019 averages**


| 2018 Avg CSAT | 2019 Avg CSAT | 2020 Avg CSAT
| ----------------- |  ----------------- | ----------------- |
54.18 | 58.09 | 64.03


![image](https://user-images.githubusercontent.com/48527022/92727885-d3c9e500-f33d-11ea-9068-43be71d76e77.png)

**Comment by jonwehausen** [comment]
### CSAT Scores v2
- Per slack conversation, Leslie requested to have a single-line chart for the entire range of CSAT scores dating back to January 2018
- @Bester1987 Please let us know if this chart services your request or if you would like adjustments

![image](https://user-images.githubusercontent.com/48527022/93116154-e3716280-f68a-11ea-87b7-0d38533ccd8a.png)

**Comment by jonwehausen** [comment]
@Bester1987 Closing per your sign-off, thanks again!
