### ISSUE TITLE
Write documentation for teams implementing wizard migration effort

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13375]
**Acceptance Criteria:**
Write documentation for teams implementing wizards, and possible updates to design system documentation for this pattern:
- [x] Behavior of wizard
    - wizard is skipped only when sent to new form after completing it.  Once you navigate away, you will need to repeat the wizard. 
   - wizard is no longer behind a button by default
   - Do we need to go into more detail about this? SIP, new tab, etc
- [x] interaction going from view to view, to address bug on staging where the scroll position is maintained when you go from the wizard to 
- [x] Content outlines of wizard flows are completed in Github
    - [Education wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/education-forms-wizard.md)
     - [Disability wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/disability-form.md)
     - [Chapter 31 wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/chapter%2031-form-wizard.md)
     - [Chapter 36 wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/chapter%2036-form-wizard.md)
     - [Higher Level Review wizard content outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/higher-level-review-form-wizard.md)
   

the into page w/ subway map. 
- [ ] behavior of `start over` link
- [ ] a11y considerations?

**Comment by andaleliz** [comment]
@mnorthuis, @peggygannon and @johnhashva 

I revisited Mikki's [IA documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md), and I think it will meet the need for dev teams especially when combined w/ the Edu prototype, and Peggy's content docs. @mnorthuis can we upgrade this from draft status now that research has been complete? I submitted a small edit via a branch/PR based on what we learned.

How are you all feeling? Is there any further UX documentation needed from me before I go on leave?

**Comment by johnhashva** [comment]
Good point, @andaleliz -- one more meeting with the dev teams before you leave is ideal.  I will work to schedule by posting a message in the How to Apply Wizards Slack channel today.

**Comment by brianalloyd** [comment]
@johnhashva we discussed this yesterday during planning, are we at a point where we can close out this ticket based on the finalization of the work @andaleliz has done?  Thanks.

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO I know that you and I were each recently refining some of the wizard language in our work with product teams (you for Chapter 36 I believe and me for Request help with VA debt). Let's sync to determine how we may need to update this documentation to reflect that.

cc @johnhashva @brianalloyd @peggy

**Comment by mnorthuis** [comment]
I think this can be closed?  I am refining IA documentation as we learn and modify, and other teams are handling the implementation of this.  Is there specific documentation that we wanted to put together?  It is scattered at the moment...

**Comment by johnhashva** [comment]
Yes, let's close.  For documentation overall, I've [captured everything here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/status_reports/implentation_tracker.md).  The 526 and HLR -- I believe -- are very close to launching (click staging links); Education/1990 has been on hold as focus shifted to Debt and other priorities.
