### ISSUE TITLE
Request access to tools

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1337]
Read and follow the instructions in [Github request access to tools document](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Onboarding/request-access-to-tools.md)

Comment "done" when completed. 

## User Story  

As a part of the VSP on-boarding process, I need to read and follow the instructions in [Github request access to tools document](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Onboarding/request-access-to-tools.md) so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  

Read and follow the instructions in [Github request access to tools document](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Onboarding/request-access-to-tools.md)  

## Acceptance Criteria  

I have read and follow the instructions in [Github request access to tools document](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Onboarding/request-access-to-tools.md)   

## Definition of Done  

- [ ] *Has been scheduled and completed * 

- [ ] *To be completed in Sprint 3 * 

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by ndsprinkle** [comment]
Done.

**Comment by smoonpeyes** [comment]
Done.

**Comment by kevinstachura** [comment]
Done.

**Comment by SMLuthi** [comment]
Done.
