### ISSUE TITLE
CT: Write "keyboard.e2e.spec.js" using Cypress

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13371]
As a developer, I need to rewrite the comparison tool end to end tests using Cypress so that they meet DEPO coding patterns and practices.

## Assumptions:
1. Tests are currently written using Nightwatch
2. Helper functions are added to or put into cypress versions of:
    a. gibct-helpers.js
3. If part of the test is OBE, it would be excluded, or if there is functionality that isn’t covered by the test but should be it would be added.

## Acceptance Criteria
1. The "keyboard.e2e.spec.js" test is replaced with a test using cypress.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14332/files

**Comment by sonntag-adam** [comment]
Merged. Closing story.
