### ISSUE TITLE
Request QA review of test suite

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13384]
## Issue description
One of the Facilities 3Q2020 priorities is expansion of test coverage for Facility Locator. This issue is to request a review of the Cypress and unit test suites to identify any gaps. 

Reference [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10677)

## VA facility search user stories 

<details>
  <summary> When a Veteran arrives on https://www.va.gov/find-locations, (expand) </summary>

- The Facility type field displays the default "Choose a facility type" 
- The Faciity type drop down contains
  - Choose a facility type
  - VA health
  - Urgent care
  - Community providers in VA's network
  - Community pharmacies (in VA's network)
  - VA benefits
  - VA cemeteries
  - Vet Centers
- Location information must be entered or enabled through browser before search can be initiated
- Facility type must be selected before search can be initiated 

</details>

---

<details>
  <summary> When `VA health` is selected as the facility type, (expand)</summary>

- The "Choose a service type" default is `All VA health services`
- The following options are shown in the "Choose a service type" drop-down

> Primary care
> Mental health care
> Dental services
> Urgent care
> Emergency care
> Audiology
> Cardiology
> Dermatology
> Gastroenterology
> Gynecology
> Ophthalmology
> Optometry
> Orthopedics
> Podiatry
> Urology

</details>

---

<details>
  <summary> When `VA benefits` is selected as the facility type, (expand)</summary>

- The "Choose a service type" default is `All VA benefit services`
- The following options are shown in the "Choose a service type" drop-down
 
![image](https://user-images.githubusercontent.com/55411834/85793587-76d17200-b6f2-11ea-97bd-307901b08115.png)

</details>

---

When `Vet centers` or `VA cemeteries` is selected as the facility type, the "Choose a service type" is unavailable.

---

<details>
  <summary> When `VA health` is selected as the facility type, (expand) </summary>

- No alert displays below search box
- Results will be relevant to the geographic location and facility type specified
- Search result cards contain required standard information
   - Alpha icon correlating to map pin
   - Distance
   - Hyperlinked name of VA Facility 
   - Address
   - Functional directions hyperlink
   - Main number
   - Mental health phone number
   - Facility operating status information  (if normal, no status is displayed)

</details>

---

<details>
  <summary> When `VA benefits` `Vet centers` or `VA cemeteries` (with any service type, when applicable) is selected as the facility type, (expand) </summary>

- No alert displays below search box
- Results will be relevant to the geographic location and facility type specified
- Search result cards contain required standard information
   - Alpha icon correlating to map pin
   - Distance
   - Hyperlinked name of VA Facility 
   - Address
   - Functional directions hyperlink
   - Main number
   - Facility operating status information  (if normal, no status is displayed)

</details>

## VA facility detail page user stories 

<details>
  <summary>Given Facility type = `VA benefits` or `Vet centers` (with any service type, when applicable), when the Veteran clicks the hyperlinked facility name, a facility detail page for that facility is displayed (expand)</summary>

The Facility Detail page contains the following information about the selected facility

- Name of Facility 
- Alert box with operating status information  (if normal, no alert is displayed)
- Address
- Main Number
- Mental Health Number (if available)
- Functional Hyperlink to Website
- Functional Hyperlink to Directions
- Static map
- Hours of Operation displayed by day
- List of services

</details>

---

<details>
  <summary>Given Facility type = `VA cemeteries`,  when the Veteran clicks the hyperlinked facility name, a facility detail page for that facility is displayed (expand)</summary>

The Facility Detail page contains the following information about the selected facility

- Name of Facility 
- Alert box with operating status information  (if normal, no alert is displayed)
- Address
- Main Number
- Mental Health Number (if available)
- Functional Hyperlink to Website
- Functional Hyperlink to Directions
- Static map
- Hours of Operation displayed by day

</details>

---

<details>
  <summary>Given Facility type = `VA health` (with any service type, when applicable), when the Veteran clicks the hyperlinked facility name, a facility detail page for that facility is displayed (expand)</summary>

The Facility Detail page contains the following information about the selected facility

- Name of Facility 
- Alert box with operating status information  (if normal, no alert is displayed)
- Address
- Main Number
- Functional Hyperlink to Directions
- Static map
- Hours of Operation displayed by day
- List of services
- Appointment times for new patients in primary care, expressed in days
- Appointment times for new patients in specialty care, listed by specialty, expressed in days
- Appointment times for existing patients in primary care, expressed in days
- Appointment times for existing patients in specialty care, listed by specialty, expressed in days
- Satisfaction scores for urgent-primary care appointments, listed as percentage of Veterans 
- Satisfaction scores for urgent-specialty care appointments, listed as percentage of Veterans 
- Satisfaction scores for routine care appointments, listed as percentage of Veterans 

</details>

## Community care user stories

<details>

<summary>When Facility type = `Community providers (in VA's network)` and Service type is specified (such as Dentist or Podiatrist, etc) (expand)</summary>

- The user can select a service from the list which generates from typeahead
- Results will be relevant to the geographic location and facility type specified
- Search result cards contain required standard information
   - Alpha icon correlating to map pin
   - Distance
   - Provider/group name 
   - Address
   - Functional directions hyperlink
   - Main number
   - Referral text 
 - NO alert displays below search box.  
- There is no link to a facility detail page 
</details>

### Pharmacy user stories

<details>

<summary> When Facility type = `Community pharmacies (in VA's network)`, then </summary>

- Results will be relevant to the location and service type specified
Search result cards contain the following:
> Alpha icon correlating to map pin
> Distance
> Facility type
> Services
> Name of group/provider
> Address
> Functional Directions hyperlink
> Phone number
> Text to call to confirm hours and service
- There is no link to a facility detail page
</details>

---

<details>

<summary> When Facility type = `Community providers (in VA's network)` and Service type = `Pharmacy - Community/Retail`, then </summary>

- Results will be relevant to the location and service type specified
Search result cards contain the following:
> Alpha icon correlating to map pin
> Distance
> Facility type
> Services
> Name of group/provider
> Address
> Functional Directions hyperlink
> Phone number
> Text to call to confirm hours and service
- There is no link to a facility detail page
 </details>

### Urgent care user stories

- When Facility type = `Urgent care`, the Service type drop down defaults to `All urgent care`.
- When Facility type = `Urgent care`, the Service type drop down contains
  - All urgent care
  - VA urgent care
  - Community urgent care providers (in VA's network)

---

<details>

<summary>When Facility type = `Urgent care` and Service type = `All urgent care`, then </summary>

- Results will be relevant to the location and service type specified
- Search results will contain a mix of VA health locations and Community care locations

- Search result cards for `VA health` locations will contain the following:
> Alpha icon correlating to map pin
>  Distance
>  Hyperlinked name of VA Facility 
>  Address
>  Functional directions hyperlink
>  Main number
>  Mental health phone number
>  Facility operating status information  (if normal, no status is displayed)

- Search result cards for `Community urgent care` locations will contain the following:
> Alpha icon correlating to map pin
> Distance
> Facility type
> Services
> Name of group/provider
> Address
> Functional Directions hyperlink
> Phone number
> Link to urgent care benefit page
> Text to call to confirm hours and services
- There is no link to a facility detail page

</details>

---

<details>

<summary>When Facility type = `Urgent care `and Service type = `Community urgent care providers (in VA's network`), then </summary>

- Results will be relevant to the location and service type specified
- Search result cards contain the following:
> Alpha icon correlating to map pin
> Distance
> Facility type
> Services
> Name of group/provider
> Address
> Functional Directions hyperlink
> Phone number
> Link to urgent care benefit page
> Text to call to confirm hours and services
- There is no link to a facility detail page

</details>

---

<details>
<summary> When Facility type = `Community providers (in VA's network)` and Service type = `Clinic/Center- Urgent care`, then
</summary>

Search result cards for all scenarios above contain the following:

> Alpha icon correlating to map pin
> Distance
> Facility type
> Services
> Name of group/provider
> Address
> Functional Directions hyperlink
> Phone number
- Results will be relevant to the location and service type specified
- There is no link to a facility detail page
</details>

---

## Mobile design user stories
<details>
  <summary>When a Veteran uses a mobile device to visit https://www.va.gov/find-locations (expand) </summary>

All search fields and associated drop-down lists are visible.
All buttons are visible.  
All content, including the map, is visible. 
No content gets focused off screen or is hidden from view.

</details>

<details>
  <summary>When a Veteran views the detail page of a selected VA facility with a mobile device (expand) </summary>

All search fields are visible.
All buttons are visible.  
All content, including the map, is visible. 
No content gets focused off screen or is hidden from view.

</details>

## Tasks
- [ ] Review [available test suite](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/facility-locator/tests)
- [ ] Identify and document gaps in test coverage

**Comment by tlei123** [comment]
@brangi @mpelzsherman , re. unit-tests review, can one of you put something in here about PR code-reviews and code-coverages pls?

Though I'd love to review unit-tests here too, I just don't have the capacity right now -- something documented here would suffice for me.  I'll be focusing on e2e-tests for this tic.  

Thx much!  :)

cc @mmiddaugh @pjhill

**Comment by brangi** [comment]
@tlei123 I will cover the above scenarios with cucumber BDD tests 

Look for example

src/applications/facility-locator/tests/cucumber/steps/search.cucumber.js

You can follow this PR https://github.com/department-of-veterans-affairs/vets-website/pull/14221/

I will let you know when ready.

**Comment by mpelzsherman** [comment]
Hi @tlei123. I'm not sure what you are looking for exactly. Let's discuss with @mmiddaugh .

**Comment by brangi** [comment]
I agree with @mmiddaugh @mpelzsherman, let's discuss about how to assess the code coverage because although I do really want to integrate cucumber tests, it will maybe need a lengthy process approval from VSP

**Comment by mmiddaugh** [comment]
Closing this issue as our request is being captured in #13779

**Comment by tlei123** [comment]
@mmiddaugh @brangi @mpelzsherman , thanks so much for your proactive efforts in improving test-coverage!

My feedback is ready for you in #13779 .  Feel free to schedule a Zoom meeting with me to discuss further.

Since this was the 1st QA e2e-test review, the feedback is comprehensive, but I've stratified it to facilitate easier scoping/prioritization.  Please don't be discouraged, it's given in the interest of continuous improvement.

Thanks, and KUDOS!  👍
