### ISSUE TITLE
Everyone read the Guidelines for Working Safely in an Open Source Repo

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1338]
## User Story 

As a part of the VSP on-boarding process, I need to read [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/README.md) so I can properly be on-boarded to the Benefits and Memorials team. 

## Goal 

Read and understand the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/README.md) documentation.

## Acceptance Criteria 

Read the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/README.md)

 
## Definition of Done 

- [ ] *Has been scheduled and completed *

- [ ] *To be completed in Sprint 3 *

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by ndsprinkle** [comment]
Done.

**Comment by kevinstachura** [comment]
Done

**Comment by smoonpeyes** [comment]
Done.

**Comment by YanaRoy** [comment]
Done.

**Comment by SMLuthi** [comment]
Done.
