### ISSUE TITLE
What should the "learning center" be called in real life? 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13385]
## What should the "learning center" be called in real life? 

@bethpottsVADEPO and @DanielleThierryUSDSVA - we've currently been referring internally to this new section of the site "learning center." Please propose a recommendation for how we should solidify this descriptive name going forward for customers. 

We don't need this imminently, but we will need solidify the name as we get closer to October, in order to move forward with Mikki's URL strategy (and potentially with search.gov directory if we go search.gov route). 

**Reference:** 
Please see name section of LC ppt deck for reference re other sites: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/pw-learning-center-takeaways-mvp-roadmap-082820.pptx 

**Background:** 
Other names we whiteboarded during design session - definitely NOT necessarily good! 
Benefit guide
Support center / Help center / Help / Support
Benefit education center
How-to center
Resource center/ Resource library
Benefit resources
Benefit help center / Benefits help
Benefits support center / Benefits support
Reference library
Benefit learning center / Learning center
Benefit knowledge center / Knowledge center

**Comment by bethpottsVADEPO** [comment]
Resources and support!
