### ISSUE TITLE
Wizard migration - UX deliverables for HLR form

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13382]
Create hi-fi mock-ups and documentation based on [HLR flow](https://app.mural.co/t/vsa8243/m/vsa8243/1585244567898/2167d6cafb30ce4a81e2ea8a082a6a832293e11c?wid=49-1585323547816)

**Documentation**
[Edu mock-ups](https://preview.uxpin.com/ca08f3dbf63475b2b62f3e8c00050ad1b19c4cb5#/pages/132986657/simulate/no-panels?mode=i)
[IA User flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md)

**Tasks**
- [x] Create hi-fi for `/introduction` page 
   - this form should NOT include skip link per Robin
   - include examples w/ alert indicating the outcome
- [x] Create hi-fi for subsequent view when user is on the form, showing subway map
   - Add content/link to "start over"
   - Provide guidance/visuals for interaction going between views

**Comment by andaleliz** [comment]
From Robin, via Slack:
> Now that I think about this more, if the user "knows this is the correct form" and chooses the link to bypass the wizard, we won't be able to gather the essential information the user enters into the wizard. If the information is missing, we would then need to dynamically add a first page to the form asking the essential question.

HLR should **not** have the skip link.

**Comment by andaleliz** [comment]
@johnhashva FYSA Kevin is going to work on these mock-ups, so taking them out of the public websites backlog.

**Comment by kevinstachura** [comment]
This design has been completed and implemented in code within the Higher-Level Review product.
