### ISSUE TITLE
OBE - STEM: Remove #12752 Prod Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13397]
As a developer, I need to remove a prod flag so the updated content is available in the production environment.

## Assumptions:
1. The work completed in #12752 has been reviewed and signed off in staging as of 09/16/20

## Acceptance Criteria
1. The work completed in #12752 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by desireeturner** [comment]
This issue is OBE because no prod flag was used for #12752. It is now in production

**Comment by dneel-bah** [comment]
Closed as OBE
