### ISSUE TITLE
Review Code of Conduct

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1339]
## User Story  

As a part of the VSP on-boarding process, I need to read the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/code-of-conduct.md) document so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  

Read the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/code-of-conduct.md) document.

## Acceptance Criteria  

I have read the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/code-of-conduct.md) document.  

## Definition of Done  

- [x] *I have read this document * 

- [ ] *To be completed in Sprint 3 * 

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by ndsprinkle** [comment]
Done.

**Comment by kevinstachura** [comment]
Done.

**Comment by YanaRoy** [comment]
Done.

**Comment by SMLuthi** [comment]
Done.
