### ISSUE TITLE
Maintenance: Update code owners file

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13399]
As a developer, I need to update the code owners file so that unnecessary extra required reviews for EDU benefits changes are prevented.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The following line of code is removed from the code owners file:

`src/applications/edu-benefits @department-of-veterans-affairs/vsa-bam-2-frontend @department-of-veterans-affairs/vsa-bam-1-frontend @department-of-veterans-affairs/vsa-caregiver-frontend @department-of-veterans-affairs/vsa-ebenefits-frontend`

Currently line 24.

## Supporting Artifacts:
1. https://dsva.slack.com/archives/CBU0KDSB1/p1599662233065300

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14168

**Comment by sonntag-adam** [comment]
Merged closing story.
