### ISSUE TITLE
Transformers for Public Website Content Types

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13395]
## Product Outline
[CMS Transformer Resource Document](https://vfs.atlassian.net/wiki/spaces/VP/pages/637567205/Transformers+Development+Guide)

## High Level User Story/ies
PW team will need to create transformers in support of product initiatives based on VSP requirements.

## What's in here
- Discovery around learning transformers
- Actual transformer implementation for the LC content types

## Planning Considerations 
<details> 

 <summary>Priority Node Build (expand)</summary>

- Plan is to build iteratively with the below 'Nodes' being the priority;

- [ ] NodeQA, 
- [ ] NodeFaqMultipleQA
- [ ] NodeStepByStep
- [ ] NodeSupportResourcesDetailPage
- [ ] NodeBasicLandingPage
- [ ] NodeChecklist
- [ ] NodeMediaListImages
- [ ] NodeMediaListVideos 

- These tickets will make up this epic in support of transformers build. 

<details> 

 <summary>Other Node Build (expand)</summary>

- Need to assess other node builds post priority node build out;

- [ ] ParagraphStepByStep
- [ ] ParagraphStep
- [ ] ParagraphAlertSingle
- [ ] ParagraphButton
- [ ] ParagraphQAGroup
- [ ] ParagraphQ
- [ ] NodeBasicLanding
- [ ]  nodeSupportService
- [ ] ParagraphListsOfLinks
- [ ] TaxonomyTermAudienceBeneficiaries
- [ ] TaxonomyTermLcCategories
- [ ] TaxonomyTermTopics
- [ ] ParagraphRichTextCharLimit1000

**Comment by MickinSahni** [comment]
Hey @brianalloyd this is the epic around Transformers for LC. The initial ticket/question is a discovery around the question: 
`Should we building LC transformers iteratively for each content type or globally for all LC content types?`

**Comment by ncksllvn** [comment]
It looks like we will need transformers for any paragraphs and nodes, including -

```
NodeQA
NodeFaqMultipleQA
NodeStepByStep
ParagraphStepByStep
ParagraphStep
ParagraphAlertSingle
ParagraphButton
ParagraphQAGroup
ParagraphQA
```

**Comment by brianalloyd** [comment]
@ncksllvn and @kelsonic I'm going to use the original Epic to align with our future transformer tickets.  I'll be building those out shortly and placing NodeQA (Nick) and NodeStepByStep (Kelson) into this sprint for action as discussed in planning.  Thanks.

**Comment by kelsonic** [comment]
Final list of entities for PW:

```
block_content-promo
node-basic_landing_page
node-checklist
node-faq_multiple_q_a
node-full_width_banner_alert
node-landing_page
node-media_list_images
node-media_list_videos
node-q_a
node-step_by_step
node-support_resources_detail_page
node-support_service
paragraph-alert_single
paragraph-audience_topics
paragraph-button
paragraph-checklist
paragraph-checklist_item
paragraph-contact_information
paragraph-email_contact
paragraph-link_teaser
paragraph-list_of_link_teasers
paragraph-lists_of_links
paragraph-media_list_images
paragraph-media_list_videos
paragraph-process
paragraph-q_a
paragraph-q_a_group
paragraph-react_widget
paragraph-rich_text_char_limit_1000
paragraph-step
paragraph-step_by_step
paragraph-table
paragraph-wysiwyg
taxonomy_term-administration
taxonomy_term-audience_beneficiaries
taxonomy_term-lc_categories
taxonomy_term-products
taxonomy_term-topics
```

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165

@brianalloyd do y'all want to go ahead and close this out?

**Comment by brianalloyd** [comment]
Absolutely @meganhkelley, this must have escaped us as we closed out all other transformer relevant tickets.  Closing now, thanks.
