### ISSUE TITLE
VSP content feedback- How to apply wizard (HLR)

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#13398]
## User story

This ticket captures VSP content feedback on How to apply wizards

Higher-Level Review links:
  - HLR (application almost ready, but Wizard dev has not yet started.)
  - [Prototype](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/430329538)
  - Wizard dev ticket is https://github.com/department-of-veterans-affairs/va.gov-team/issues/12925

## Acceptance criteria

- [x]  VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x] Teams leaves comments about any feedback they decide not to take
- [x] Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
Wizard page
feedback is still a WIP... just posting what I have so far: 



---------


Wizard page
1.	The header “Find out if this is the right form” doesn’t work for HLR, as (unlike EDU) it’s just 1 form
Please change header TO
**Is this the form I need?**
Update intro content below it TO: 
Use this form if you disagree with VA’s decision on your claim and want to request that a senior reviewer take a new look at your case and the evidence you provided. You can’t submit any new evidence for this Higher-Level Review. 

Answer a few questions to get started.

{green wizard button} language TBD

**Comment by Mottie** [comment]
Hi Peggy! HLR is now available on staging 🎉 

There is still some work being done on the wizard flow, which will be implemented once that has been finalized, but almost everything else is in place. The only thing missing is the mock "Contact Information" details.

A list of users is available here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.docx

**Comment by peggygannon** [comment]
thank you @Mottie ! I will take a look.

**Comment by kevinstachura** [comment]
Hi @peggygannon! Thanks so much for all the feedback on this. The changes should be fully incorporated and are viewable here: 

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/430329538_HLR_-_Info_Page_-_New_Wizard_-_First_Question

The relevant wizards screens are 2-8 on the prototype.

_Note: We have decided to accept all of the suggested feedback, but we will still want to confirm with AMO about the date selection for legacy appeals. Since we agree that having the date selection is the optimal experience and makes sense message-wise, we have decided to do the design effort around it and then show our SMEs. We just would like to confirm with them once more that it indeed still parallels the business logic._

Please let me know if there's anything I missed or if you have further feedback. Thanks again!

- Kevin

**Comment by peggygannon** [comment]
HI, @kevinstachura Thank you! Please keep me posted on any additional feedback from SMEs. I don't see user flow 3 (below) in the mockup (adding a "I don't know" option). Let me know if that is an oversight, or if you don't want to implement until you discuss with SMEs? 

also, due to accessibility feedback we're recommending an update the H1 on the form intro page and form screens to make it clear to users with assisted tech that the content on the screen is different from the wizard screen. I will add the new H1 to the mockup, but also want to share it with you here: 

H1 for form intro page (subway map) and screens in the form flow: 
**Request a Higher-Level Review with VA Form 20-0996**


--






User flow 3
For what type of claim are you requesting a Higher-Level Review?
Disability compensation claim
Is this claim going through the legacy appeals process?
Recommend ADDING radio button option:
I don’t know
Recommend ADDING: What’s the date of VA’s decision
Month, date, year

{if after Feb. 19, 2019}
{alert} You can request a Higher-Level Review online using VA Form 20-0996.
{CTA} Request a Higher-Level review online
Learn about other ways you can request a Higher-Level Review
{end alert}

{if before Feb. 19, 2019}
{alert} Since your claim has a decision date before February 19,2019, you’ll need to opt in to the new decision review process. To opt in, fill out and submit VA Form 20-0996 by mail, fax, or in person. On the form, you’ll need to check Box 15 to “opt in from SOC/SSOC.”
Download VA Form 20-0996 (PDF)
If you haven’t filed a legacy appeal for this claim, you’ll need to file a Supplemental Claim
{end alert}

**Comment by kevinstachura** [comment]
Ah, that is indeed an oversight...Thanks @peggygannon - I will fix that!

I will absolutely keep you apprised to SME feedback. Really, all we're looking to have the SMEs answer is: "is the decision date really the only parameter that would indicate whether or not it's a legacy appeal?" Given the messaging one would assume so, but we want to ensure there are no rare, extenuating circumstances in which date is feb 19, 2019 or after, and still might be considered a legacy appeal. Just want to make sure we're catching any potential edge cases.

I will make further edits and let you know when they're complete!

**Comment by kevinstachura** [comment]
@peggygannon updated Invision link:

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/430329541_HLR_-_Info_Page_-_New_Wizard_-_Disability_Selected_-_Legacy

Also updated H1 for intro page: 

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/404076958_Signed_Out_-_File_An_HLR_-_Intro_Page

**Comment by peggygannon** [comment]
ok, thanks, @kevinstachura the updates look good.

**Comment by peggygannon** [comment]
**11/2/2020 update**

Based on SME feedback to the wizard questions, I"ve updated the content outline and uploaded it here: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13889

Feedback on the HRL form is captured here: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/15096
