### ISSUE TITLE
[Design] Prepare Analytics MVP prototype for usability testing

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#134]
## User Story
As a product owner, I need to easily access and understand data about my product to leverage data for product decisions and understand if there are problem areas I may need to dig more deeply into.

## Description
Prepare the Analytics MVP prototype to align with scenarios/tasks outlined in the usability conversation guide.

## AC
- [x] Iterate to ensure 508 accessibility
- [x] Iterate so it's adhering to design best practices
- [x] Prototype matches other scenarios/tasks in the conversation guide.
- [x] Add Weekly view to the Google Sheets MVP (can have mock data)
- [x] Update the "realtime" section of the Google Sheets MVP to be more usable (can have mock data)
- [x] Iterate to incorporate user feedback

**Comment by joanneesteban** [comment]
Adding @nedierecel for to align for metrics accuracy.

**Comment by rroueche** [comment]
@smoonpeyes as a heads up - I added one more AC: ```Iterate so it's adhering o design best practices```

**Comment by rroueche** [comment]
@rtluu and @joanneesteban the thresholds for coding IMO is a product task, not sure if you want to break that into a separate issue, or collaborate here w/Layla on it.

**Comment by joanneesteban** [comment]
@rroueche Opening a new issue for thresholds.

**Comment by nedierecel** [comment]
For visibility, I also relabeled "Goal Conversion" to "Funnel Conversion" within the Prototype.
