### ISSUE TITLE
GIBCT Search: University of Maryland institutions dont show in search results when searching "University of Maryland"

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#13408]
All universities with "University of Maryland" in the name should show in search results for the comparison tool when searching "University of Maryland"

### Expected
University of Maryland institutions display when searching for "University of Maryland"

### Actual
![Screen Shot 2020-09-10 at 2.34.37 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/525ad08a-2520-48c6-ace3-0f8bd677e097)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/730

**Comment by delli-gatti-michael** [comment]
local testing complete

<img width="1045" alt="Screen Shot 2020-09-11 at 12 13 51 PM" src="https://user-images.githubusercontent.com/45575003/92948975-47e0b780-f428-11ea-8c37-deec8b752275.png">

**Comment by delli-gatti-michael** [comment]
Fix is now in Staging. Closing this issue
