### ISSUE TITLE
SPIKE: investigate slow DB queries from SSOe saml_callback controller

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#13403]
A database query, or queries, are [averaging over 1.6s on production](http://grafana.vfs.va.gov/d/000000017/vets-api?viewPanel=23&orgId=1&from=now-12h&to=now) when a response comes back to `/v1/sessions/saml_callback`.  Its possible that this is realted to the `icn` [lookup on the Accounts table](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/user_session_form.rb#L61-L66), but more work should be done to analyze the flow of the `saml_callback` controller and determine what query needs to be optimized.

https://dsva.slack.com/archives/CHPA76VV5/p1599741340002300

**Comment by jholton** [comment]
#13442 : Added index to `accounts` table `icn` column
