### ISSUE TITLE
[Analytics] HLR: Ensure Grafana Dashboard is Working

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#13400]
**Once HLR is live in Prod**, ensure that stats are being recorded in the [HLR Grafana dashboard](http://grafana.vfs.va.gov/d/qCRjZjDMk/hlr-higher-level-review?orgId=1).

## Issue Description
Follow up to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10712

## Acceptance Criteria
- [ ] **Once HLR is live in Prod**, ensure that stats are being recorded in the [HLR Grafana dashboard](http://grafana.vfs.va.gov/d/qCRjZjDMk/hlr-higher-level-review?orgId=1). (Do a dummy request and make sure you see the failure in the charts)

**Comment by annaswims** [comment]
![Screen Shot 2020-11-13 at 4.16.29 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/1e08ac41-004b-41c0-a2de-235b1501b7e9)

looks good in staging
