### ISSUE TITLE
[Development] Claims Status: Display or Provide Link to Decision Letter

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#13405]
## User Story
As a veteran, I expect to be able to find my decision letter easily from the claims status tool.

## Expected Behavior
When looking at my decision summaries on the main CST page, a link to the decision letter would be excellent.

Prelim design for this ticket: https://vsateams.invisionapp.com/share/SWYMSCCJ3ZD#/430475271_Claim_Appeal_Status_-_Claim_Detail

## Tasks
- [ ] Implement the prelim design above

**Comment by kevinstachura** [comment]
There's a prelim design for this ticket: https://vsateams.invisionapp.com/share/SWYMSCCJ3ZD#/430475271_Claim_Appeal_Status_-_Claim_Detail

**Comment by Mottie** [comment]
More discovery work needs to be done before this work can commence. I don't see individual decisions listed on the decision letters page. It appears to include an overall summary only

<details><summary>Screenshot from test user 238</summary>


<img width="587" alt="Screen Shot 2021-02-08 at 9 51 42 AM" src="https://user-images.githubusercontent.com/136959/107244633-d9624e80-69f3-11eb-84ff-ee05d54324eb.png"></details>

Related links:
- https://staging.va.gov/records/download-va-letters/letters/letter-list
- https://staging.va.gov/disability/view-disability-rating/rating

**Comment by vhenry07** [comment]
Closing pending further discovery / issue validation.
