### ISSUE TITLE
Review Platform Principles

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1340]
Everyone read [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/platform-principles.md) and comment "done" when completed. 

## User Story  

As a part of the VSP on boarding process, I need to read [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/platform-principles.md) so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  

Read [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/platform-principles.md).  

## Acceptance Criteria  

I have read [Platform Principles](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/platform-principles.md).   

## Definition of Done  

- [x] *Has been  completed * 

- [ ] *To be completed in Sprint 3 * 

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by ndsprinkle** [comment]
Done.

**Comment by smoonpeyes** [comment]
Done.

**Comment by kevinstachura** [comment]
Done.

**Comment by YanaRoy** [comment]
Done

**Comment by SMLuthi** [comment]
Done.
