### ISSUE TITLE
Review the Norms for Communication

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1341]
Everyone read the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-communication.md) and comment "done" when completed. 

## User Story  

As a part of the VSP on boarding process, I need to read the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-communication.md)so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  

Read the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-communication.md).  

## Acceptance Criteria  

I have read the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Norms/norms-communication.md).   

## Definition of Done  

- [x] *Has been  completed * 

- [ ] *To be completed in Sprint 3 * 

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by ndsprinkle** [comment]
Done.

**Comment by smoonpeyes** [comment]
Done.

**Comment by kevinstachura** [comment]
Done

**Comment by YanaRoy** [comment]
Done.

**Comment by SMLuthi** [comment]
Done.
