### ISSUE TITLE
STEM: Remove prod flag and content related to STEM Scholarship question from 22-1995 workflow

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13414]
As a veteran looking to update my benefits, I should not have to answer unnecessary questions about the STEM scholarship application in order to update my benefits.

## Assumptions:
1. The STEM Scholarship question in the 22-1995 was placed behind a prod flag in #7272.
2. This content is removed from the 22-1995 + submissions in Production when the new 22-12030 is live on Production (09/10/2020).

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
1. STEM Scholarship Application questions are not included in the 22-1995 workflow.
   - The STEM questions
   - The read-only view on the "Review Application page"
2. The Prod Flag created in #7272 has been removed completely from all environments.

## Supporting Artifacts:
1. [22-1995 Workflow with STEM](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/VA%20Form%2022-1995%20with%20STEM%20Process%20Flow%20122419%20v0.3.pdf)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14184

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4886

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/7580

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/507

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14207

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4895

**Comment by delli-gatti-michael** [comment]
Local testing complete.

Tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/tests/view/12541&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by zurbergram** [comment]
Closing as remaining cleanup has been merged in
