### ISSUE TITLE
[DUE ON 09/28] Redirect Request: STEM Legacy Content Page

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#13411]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
The legacy STEM content page has been rewritten and migrated into Drupal.  The URL of the legacy page should now be redirected to the new page. 

### Requestor team info
BAH, Public Websites

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : ASAP

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://benefits.va.gov/gibill/fgib/stem.asp	| www.va.gov/education/other-va-education-benefits/stem-scholarship

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
This redirect is ready for implementation when your team is ready.   Please ensure redirect is not case sensitive.

**Comment by lunascoop** [comment]
@bethpotts can you find out who are the appropriate stakeholders for redirect notification?

**Comment by lunascoop** [comment]
This redirect has been implemented. Closing ticket and updating stakeholders.
