### ISSUE TITLE
Backend validation for unique social security numbers

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#13427]
Given that we're adding a new constraint, requiring all 10-10CG applicants to have unique SSNs
I want to update the backend
To enforce the front end validation.

**Comment by mlighdc** [comment]
@ala-yna and @kevinmirc - Trying to help prioritize. It sounds like this has become a stretch target based on discussion in Monday's huddle (9/14)? And we believe Frontend should catch most of these.

**Comment by kevinmirc** [comment]
Yes, that's right.

**Comment by hdjustice** [comment]
Closing - This ticket has not been addressed in over a year, and there are no initiatives linked.  Any new work will have new tickets created.
