### ISSUE TITLE
Review GitHub Markdown Cheatsheet

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1342]
## User Story  

As a part of the VSP on boarding process, I need to read the [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and comment "done" when completed so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  

Everyone read the [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).   

## Acceptance Criteria  

I have read the [GitHub Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and comment "done" when completed.  

## Definition of Done  

- [ ] *Has been  completed * 

- [ ] *To be completed in Sprint 3 * 

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by ndsprinkle** [comment]
Done.

**Comment by smoonpeyes** [comment]
Done.

**Comment by kevinstachura** [comment]
Done.

**Comment by YanaRoy** [comment]
Done.

**Comment by SMLuthi** [comment]
Done.
