### ISSUE TITLE
Update product guide for 10/1

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#13422]
Given that we're updating the 10-10CG to meet 10/1 program requirements
And have made a few other small changes based on business & Veteran feedback
I want to update the product guide to reflect the revisions
So that the contact center can assist Veterans who call in with questions.

**Comment by psanders86** [comment]
Blocked until we get the form into staging so I can get updated screen grabs.

**Comment by mlighdc** [comment]
@psanders86 I know you are OOO on Monday (9/28). The screens should be ready to go. Can you let me know when the Product Guide will be available? I am sorry if I missed it if you sent it on Friday (9/25). Thanks.

**Comment by ala-yna** [comment]
[Uploading... Online-10-10CG-Product-Guide-Updated-9.30.2020.docx ]
