### ISSUE TITLE
Deprecate buildtype and node_env

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#13425]
## Overview 

- vets-website has two similar concepts for gating behavior: buildtype and environment 
  - buildtype is generally used as a node environment variable (production, localhost, test) 
  - [environment](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/constants/environments.js) is generally used as in the website code (vagovprod, vagovstaging, localhost) 
- The two concepts don't have distinct meanings but they use separate sets of enums that are often conflated. This causes difficult to track down [bugs](https://dsva.slack.com/archives/CBU0KDSB1/p1599687029106700?thread_ts=1599578888.015000&cid=CBU0KDSB1) (e.g. when someone uses `production` when `vagovprod` should be used). 
- `node_env` is sometimes used as an environment variable for buildtype

## Tasks 
- where possible, eliminate the `__BUILDTYPE__` and `NODE_ENV` concepts  
- Consolidate everything under [ENVIRONMENT](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/constants/environments.js) flags 
- Update the environment flag enum to `production`, `staging`, `dev`, `test`, and `localhost`
- Update environments documentation [page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/site-structure/environments/)

**Comment by timwright12** [comment]
closing this out, as I believe we need both these options
