### ISSUE TITLE
Review Design & Research Onboarding Documentation

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1343]
## User Story  

As a part of the VSP on boarding process, I need to read and review the [Review Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers) and comment "done" when completed. so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  

Read and review [Review Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers).

## Acceptance Criteria  

I have read the [Review Design & Research Onboarding Documentation](https://design.va.gov/documentation/designers)and comment "done" when completed.  

## Definition of Done  

- [ ] *Has been  completed * 

- [ ] *To be completed in Sprint 3 * 

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by smoonpeyes** [comment]
Done.

**Comment by kevinstachura** [comment]
Done.
