### ISSUE TITLE
STEM: Remove 'stem_document_type' feature flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13439]
As a developer, I need to remove the feature flag for 10203 form document type because it will not be disabled going forward.

## Assumptions:
1. The feature flag was configured as part of story #12799 .
2. This functionality has gone through UAT with EDU and been signed off on as of 09/22.
3. This functionality has been turned on as of 09/24 and no issues have been encountered.

## Acceptance Criteria:
1. The feature flag 'stem_document_type' is not displayed here: https://[environment]-api.va.gov/flipper/features.
2. The spool file continues to be generated with the V10203 document type for 10203 application submissions.

## Supporting Artifacts:
1. N/A

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5124
branch: bah-13439

**Comment by sonntag-adam** [comment]
in all environments, closing story.
