### ISSUE TITLE
Analytics for new Facility selection page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13438]
We are redesigning this page in VAOS - https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/va-facility

This new design will have a new URL as we are going to do a phased release of the new redesign to see if it improves user dropoff on this page/overall funnel. This is us somewhat hacking together an A/B type testing scenario.

### We need to track the following:
- Continue to track a user through VA request process using this new page + the existing page (would like to have a [funnel view similar to my existing funnel for VAOS requests](https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p184318975/edit/5pTuYti2SICJcXOmDUObBA))
- We need to make sure we are collecting same data currently tracked on the /va-facility page -- system id & care type with eligibility events ([see past implementation ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8366)
- **Track # of users who click 'use my current location'**
      **- # that select allow & # that select 'block'**
- **Collect # of child facilities that return in Veteran's location list** (want to understand - on avg - how many Veterans are seeing/getting)

**Flat list design: (v1)**
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/a193f2c3-cd2e-4411-9790-6c80aa9a221a)

**Distance + geolocation design: (v2)**
![Screen Shot 2020-09-11 at 8.53.41 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/2a9534a5-07d1-42c2-a90c-5619e8fbf8de)

**Comment by lenaecb** [comment]
@joanneesteban - it might be helpful if we connect with Brian (or whomever will be working on this with us) for a sync so we can talk through more what we're trying to do and VSP Analytics ideas on our approach.

**Comment by jonwehausen** [comment]
@bsmartin-ep Let's discuss any knowledge you have at this point regarding this request.

**Comment by lenaecb** [comment]
@jonwehausen - I chatted with @bsmartin-ep about this yesterday.

I have the following action items:
1. Get new url for this page
2. Let you all know when page is up on staging so we can see if anything is being tracked based on new design (as is)

Hopefully will have something for you all later today.

**Comment by jonwehausen** [comment]
Hi @lenaecb , 

Wanted to touch base here if we had an updated URL in staging? Thanks in advance

**Comment by lenaecb** [comment]
@jonwehausen @joanneesteban - ok, we finally got our page up on staging! 

Here's the updated url: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/va-facility-2

So a few things I want to understand are:
- do the current eligibility events that are currently tracking (and typically fire on this page) still firing with this new page?
- how do can we have two simultaneous flows (current prod version + this phased version) happening at once so we can see the change and dropoff (hopefully)? 

To add the some complexity here, we decided to break the release of this page up a bit further to get this 1/3 of this design out the door to combat some major user feedback that we're getting with the existing page. So, the releases are:
1. Flat list of facilities (no gelocation sorting)
2. Distance and geolocation sorting (as the primary view for most veterans with the flat list being default if we don't have a veterans address/location)

We want to get #1 out early next week.

**Comment by bsmartin-ep** [comment]
@lenaecb -

We should be able to differentiate between versions of the facility selection page by URL.  If production will match staging, we can build two different funnel visualizations in DOMO for sessions that hit one version of the page or the other.

- https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/va-facility
- https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/va-facility-2

----------------
> do the current eligibility events that are currently tracking (and typically fire on this page) still firing with this new page?

Here are all the `vaos-eligibility-*` events I see on the new page.  Is there one I should trigger with a specific flow / selection / user?  

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p184600834/_u.date00=20200901&_u.date01=20201006&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%22vaos-elig%22,0%5D,%5B0,%22analytics.pagePath%22,%22EQ%22,%22staging.va.gov~2Fhealth-care~2Fschedule-view-va-appointments~2Fappointments~2Fnew-appointment~2Fva-facility-2~2F%22,0%5D%5D/

----------------
I did see some null dataLayer params...

![image](https://user-images.githubusercontent.com/62304138/95237365-1b754c80-07d6-11eb-9831-15fcfe73a9e4.png)

----------------
And lastly, not sure if we want to do it now (or in the big design system ticket we are working on), but this component in your list isn't firing an event...

https://design.va.gov/components/additional-info

**Comment by jonwehausen** [comment]
@lenaecb Per our conversation here: https://dsva.slack.com/archives/CMNQT72LX/p1602166726087700...

With confirmation that the roll-out structure will be to a percentage of users...we would like to request a small data layer push be executed on page load for those veterans receiving v1 vs v2. This will allow us to segment the data for those users who have v2 enabled. 

```javascript
'event': 'phased-roll-out-enabled', 
'product-description': 'VAOS - Facility Selection v2'
```

We can also leverage the page URL of `/va-facility-2` **(if following thru to production)** to draw this distinction for funneling purposes, however pushing to the data layer as well will also allow us to give context to people who received `v2` at a session-level.

@narin & @jbalboni We would recommend this push execute as early in browser session as possible (as soon as the system knows user has v2 facility selection enabled)

**Comment by jonwehausen** [comment]
Hi Team, 

Wanted to follow-up from last Slack comment....

Per Brian's comment, we would like to request `health-TypeOfCare` and `health-FacilityID` be populated on receiving of eligibility alerts. From the looks of it -- `health-FacilityID` doesn't look to be known in the form at this point, so if that's the case, we can leave `null`. 

Populating `health-TypeOfCare` here will then allow us to correlate eligibility events with care types. 

cc: @lenaecb @bsmartin-ep @narin

**Comment by jbalboni** [comment]
@jonwehausen @bsmartin-ep What do you all want the event name to be for this item?

> Collect # of child facilities that return in Veteran's location list (want to understand - on avg - how many Veterans are seeing/getting)

Following the pattern of the appointment list pages, maybe this?

```
'event': 'vaos-get-available-facilities', 
'vaos-number-of-facilities': 5
```

**Comment by jonwehausen** [comment]
@bsmartin-ep will let you make the call here as I know you have mentioned interest in adjusting taxonomy here...

**Comment by bsmartin-ep** [comment]
@jbalboni -

My apologies for missing this metric in your request.

I know it's not apples to apples, but thoughts on using the taxonomy I suggested in #14331?

```javascript
'event': 'vaos-number-of-cards-retrieved',
'vaos-card-type': 'available_facilities',
'vaos-number-of-cards': 5
```

cc @jonwehausen

**Comment by jonwehausen** [comment]
@narin Pending Jeff's return (realize he is out), Could you take a look at the proposed structure above and let us know your thoughts?

**Comment by narin** [comment]
@jonwehausen @bsmartin-ep I think that is along the lines of what @jbalboni was suggesting in his comment above.  This page isn't on the appointments list though, so we probably wouldn't need an equivalent on `vaos-card-type`.  Does Jeff's suggestion work?

```
'event': 'vaos-get-available-facilities', 
'vaos-number-of-facilities': 5
```

**Comment by jbalboni** [comment]
@narin I'm going to update this to follow the pattern from the other ticket, using `vaos-number-of-items-retrieved`. https://github.com/department-of-veterans-affairs/va.gov-team/issues/14331#issuecomment-706218729

**Comment by jonwehausen** [comment]
Thank again guys, very much appreciate your work here @jbalboni @narin

**Comment by jbalboni** [comment]
@bsmartin-ep For this requirement: 

> Track # of users who click 'use my current location'
- # that select allow & # that select 'block'

Do these events work?

`vaos-request-current-location-clicked`
`vaos-request-current-location-allowed`
`vaos-request-current-location-blocked`

**Comment by bsmartin-ep** [comment]
@jbalboni -

Those work for me.  They aren't exactly navigation, so I think they should be in the `vaos-` product prefix like you suggested.

**Comment by jbalboni** [comment]
@bsmartin-ep Great, they should be up on staging soon.

**Comment by jonwehausen** [comment]
### QA Documentation

### Number of Items

Description of Interaction or API Call | DL Screenshot | GTM/GA Screenshot | Test Status 
------------ | ------------- | ------------- | -------------
API call returning number of card details on upcoming appointments tab (with 0 items) | ![image](https://user-images.githubusercontent.com/48527022/97740466-ba305880-1ab7-11eb-81ba-4a493445073c.png) | **NONE FIRED** | ✔️ Tag will not fire when data layer variable `vaos-number-of-items` = 0 
API call returning number of card details on upcoming appointments tab (with more than 0 items) | ![image](https://user-images.githubusercontent.com/48527022/97740775-23b06700-1ab8-11eb-8236-ea19e6005147.png) | ![image](https://user-images.githubusercontent.com/48527022/97740824-3034bf80-1ab8-11eb-93bc-ce67b73cee8e.png) ![image](https://user-images.githubusercontent.com/48527022/97740937-59ede680-1ab8-11eb-8df7-b4a8a5e8a9e7.png) | ✔️ **PASS** - custom dimension for returned item type is mapped correctly 

### Facility v2 Location Allow/Block
Description of Interaction or API Call | DL Screenshot | GTM/GA Screenshot | Test Status 
------------ | ------------- | ------------- | -------------
Click on "use my location" ![image](https://user-images.githubusercontent.com/48527022/97741751-9cfc8980-1ab9-11eb-9087-a5fed475d1a3.png) | ![image](https://user-images.githubusercontent.com/48527022/97741791-ad146900-1ab9-11eb-891b-79595ce2316c.png) | ![image](https://user-images.githubusercontent.com/48527022/97741819-ba315800-1ab9-11eb-94f8-5566df135be7.png) | ✔️ **PASS**
When location is allowed | ![image](https://user-images.githubusercontent.com/48527022/97742145-42aff880-1aba-11eb-8ce4-e336f65c8e22.png) | ![image](https://user-images.githubusercontent.com/48527022/97742170-4e032400-1aba-11eb-9b5a-18bd0bd34e20.png) | ✔️ **PASS**
When location is blocked | ![image](https://user-images.githubusercontent.com/48527022/97742404-9d495480-1aba-11eb-94e6-3cd4743bfdb8.png) | ![image](https://user-images.githubusercontent.com/48527022/97742450-ae926100-1aba-11eb-887d-7c05f1ba0df1.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
## Closing this per impl. and keeping #14192 open for dashboard iterations
