### ISSUE TITLE
VA Profile connected applications should show immediately in a veteran's profile regardless of cache timeout

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#13444]
## What happened?
Reported issue in DSVA Slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1599842802258400

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce

- Log in with vets.gov.user+1@gmail.com / a production va.gov account that has an app connected
- Navigate to the profile, navigate to 'Connected applications`
- Delete connected app
- In another tab, connect the same application by going to http://va-claims-staging.herokuapp.com/ or in prod http://va-claims-production.herokuapp.com/
- The added app does not appear till much later (20 mins to an hour, unconfirmed caching time)

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ericboehs** [comment]
@thilton-oddball and I reviewed this and was also not able to reproduce the issue. We will wait until the meeting with Sandra tomorrow at 3p ET.

**Comment by thilton-oddball** [comment]
Walked through steps with Sandra in staging. Was able to connect app and see it reflected immediately. Then disconnected app and saw it reflected immediately. However, when re-connecting app a second time, it was not reflected in the profile immediately.

**Comment by ricetj** [comment]
@thilton-oddball wanted to see if you needed any other information from my end on running this bug down.

**Comment by ricetj** [comment]
Just connecting this: https://dsva.slack.com/archives/CQHBJ5U06/p1603830600259000

**Comment by erluti** [comment]
We have no hooks to clear the cache on `add`s, so the cache needs to timeout to see newly added apps.
Our app is "properly" clearing the cache on deletes, but if we verify there are no connected apps before connecting one, we'll cache 0 connected apps and the newly added one won't be seen until the cache times out.

I think this section of code doesn't need to use the redis cache, it should be storing the okta response in memory until the end of the request cycle.  I don't think getting the okta information is a heavy request and I don't think connected apps is heavily used enough to require caching.

**Comment by erluti** [comment]
Caching is no longer used for grants and they stay up to date with okta now
