### ISSUE TITLE
Staging:  Direct Scheduling Should be Allowed for Patient in Optometry and Food when VATS is Yes 12 or Yes 24/Optometry Request Should be Allowed

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#13443]
@marcynadeau commented on [Fri Sep 11 2020](https://github.com/department-of-veterans-affairs/vets-json-schema/issues/504)

Scenarios
Scenario #1 Timeframe 12 mos and #2 TimeFrame 24 mos
1. In VATS direct scheduling settings for Cheyenne Audiology, Cheyenne Food/Nutrition, Cheyenne Optometry, Sidney Ophthalmology and Cheyenne Move are set to YES, Based on Timeframe 12 mos (same thing happens in Timeframe 24 mos). In VATS requests settings for Cheyenne Audiology, Cheyenne Food/Nutrition, Cheyenne Optometry, Sidney Opthalmology and Cheyenne Move are set to YES, Any Veteran.  
2.  Jacqueline.morgan@id.me has past checked out appts in Optometry and Nutrition in clinics that are not filtered by MAS:  

-  Chy Optometry (IEN 999) 09/07/2020@08:00  Act Req/Checked Out and 

- Chy Nutrition/Satp (IEN 707)       09/07/2020@11:00      Act Req/Checked Out

3.  Select Optometry, VA, Cheyenne.  **Expected Response:**  Direct Scheduling Flow Displays.  **Actual response:**  We couldn't find a recent appointment at this location.  
4.  Change type of care to Food/nutrition, VA, Cheyenne.  **Expected Response:**  Direct Scheduling Flow Displays.  **Actual Response:** Request flow displays.  

**Scenario#3.**  
1.  In VATS Optometry in Cheyenne: Direct Schedule = No.  Requests = Yes
2.    Jacqueline.morgan@id.me.   Select Optometry, VA, Cheyenne.  **Expected Response:**  Request Flow Displays.  **Actual response:**  We couldn't find a recent appointment at this location.

**Comment by marcynadeau** [comment]
[https://app.zenhub.com/files/133843125/47ff3d68-d465-4ad8-b77f-66377113005c/download](https://app.zenhub.com/files/133843125/47ff3d68-d465-4ad8-b77f-66377113005c/download)![MorganAppt.PNG](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/b17cd27f-a6c0-47f8-8a84-d0bb099ba3ec)

**Comment by marcynadeau** [comment]
[https://app.zenhub.com/files/133843125/331f51e4-12f8-49d4-bf01-7509cd9908fe/download](https://app.zenhub.com/files/133843125/331f51e4-12f8-49d4-bf01-7509cd9908fe/download)

**Comment by jbalboni** [comment]
I'm not sure if this one is still an issue, seems like a VATS or var-resources issue if it is still a problem.

**Comment by laurenernest** [comment]
@marcynadeau Can you confirm if this is still an issue?

**Comment by aarathi-poldass** [comment]
Completed QA Validation on Staging. Works as expected.

**Comment by laurenernest** [comment]
Closing per latest validation comment.
