### ISSUE TITLE
Engineers: Set Up Local Dev Environment

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1344]
## Silvio/Nick: please review and complete [Set Up Local Dev Environment](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/getting-started.md) with the following links below:

[Set Up Front End](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
[Set Up Back End](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
[Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Administrative/Onboarding/request-access-to-tools.md)
[Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)

## User Story  

As a part of the VSP on boarding process, I need to set up my local dev environment and comment "done" when completed, so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  
I need to set up my local dev environment with the following links below:

[Set Up Front End](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)
[Set Up Back End](https://github.com/department-of-veterans-affairs/vets-api#vets-api-)
[Set up internal tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Administrative/Onboarding/request-access-to-tools.md)
[Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)

## Acceptance Criteria  

I have set up my local dev environment with the links provided.

## Definition of Done  

- [ ] *Has been completed * 

- [ ] *To be completed in Sprint 3 * 

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by ndsprinkle** [comment]
Done.

**Comment by SMLuthi** [comment]
Done.
