### ISSUE TITLE
Access for Wyatt Walter

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#13453]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   >  Cecilia Lee
- Please provide your name.
   > Wyatt Walter
- Please Provide your email.
   > wyatt@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse -> Platypus, tech lead, Ad Hoc

- Requesting SSH key authorization?
   > NO — already have SOCKS access

- Grant AWS Console access?
  > YES
  - Already have an AWS user, but need to be added to the lighthouse-developers group

**Comment by jsev-io** [comment]
@wyattwalter This is complete.

**Comment by wyattwalter** [comment]
Thanks Julian!
