### ISSUE TITLE
Personal & contact information

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13458]
## User Story

As a user, I can view and edit the following information from my VA.gov profile:
- Date of birth (view only) 
- Gender (view only) 
- All addresses in /v0/user endpoint
- All phone numbers in /v0/user endpoint
- Fax number
- Email address

## Tasks
- [ ] Any necessary optimizations to endpoints are determined and discussed with team
- [ ] Any necesssary optimizations are made in vets-api 
- [ ] Endpoints are tested
- [ ] Endpoints are documented 
- [ ] Hand off to frontend

## Prototype
[Screen link](https://adhoc.invisionapp.com/share/JPYCWHEQ56N#/screens/427924942)

## API Tagging
[Profile tagging](https://www.figma.com/proto/0SGZH6YNbMAPsdaHC4xIjl/API-Data-Tagging?node-id=1%3A2&scaling=min-zoom)

**Comment by kreek** [comment]
PR for `/mobile/v0/users` https://github.com/department-of-veterans-affairs/vets-api/pull/5015
