### ISSUE TITLE
Clear local storage after every browser test 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#13450]
## Overview 

- Using `localStorage.clear();` after each mocha test reduces cross test state pollution 
- Currently this is added as part of each test suite. 

## Tasks

- Clear the local storage as part of the global `afterEach` hook in mocha tests

**Comment by k80bowman** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17739)
