### ISSUE TITLE
Forms library bug: itemFilter removes data for validation, but not schema

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#13452]
## Issue Description
In [`validation.js`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms-system/src/js/validation.js#L255-L266), the `itemFilter` removes the data from the array that needs to be filtered out, but it doesn't remove the corresponding item schemas. This leads to a mismatch between the `formData` and `schema` being sent to the [`v.validate` function](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms-system/src/js/validation.js#L268).

## Impact
The 526 form currently has a bug affecting the following scenario:
- Claim for new PTSD condition
- Claim for any secondary conditions _after_ the PTSD condition

The trouble is that the `itemSchema`s require different information, so when there's a mismatch between data and schema, unexpected validation errors are raised.

## Acceptance Criteria
- [ ] The array item schemas and array item data match up when an `itemFilter` is specified
- [ ] A unit test is written to validate :point_up:

**Comment by annaswims** [comment]
Is [this](http://sentry.vfs.va.gov/vets-gov/website-production/issues/12188/events/d6327093514b4d508b32429cb10c17ae/) or [this](http://sentry.vfs.va.gov/vets-gov/website-production/issues/12188/events/686c28acac304f72811fb3b05bbcc172/) an instance of the issue, or another problem?

**Comment by annaswims** [comment]
I made an issue to follow up with veterans and let them know that the issue they encountered has been fixed https://github.com/department-of-veterans-affairs/va.gov-team/issues/13657

**Comment by meganhkelley** [comment]
@caw310 handing this off to design system team

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
