### ISSUE TITLE
Access for Alex Wilson

### ISSUE THREAD

**Issue by FonzMP** [department-of-veterans-affairs/va.gov-team#13451]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Alex Wilson
- Please Provide your email.
   > alex.wilson@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Platypus, Node Engineer, Oddball

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDluoeQLlQRml5UTZhyX4ulPGm7HFNh5xk8YGlzJUow96Pj+QPzgePxAtoCNDCNI7tYlGxqiXoKpz7/oiz6hA6bAf1KV72uDfOCK50GzQX0fqY/Wt3/W+RQjq0rfu1YFiSSKWHVMV92n0trO95s1M72scoEbo391ARuwSsujFl6cNfxRLvV5eIiDyu7VGAhU2fZ6bhxJRYZBswJppZTsWguAO9jdOYwe+W5y1YqOr0hYT18Nmzc8UZY10ZUaUhxvu0AAzKmhGpT0dSXE3NneR9kCOOFeRbUNet7OZGEsyhvo+UaUu6eGadH+YgUgzwqt4/8JMCxDjJgiJuuaC9O7X+euykCeJd3LKwdRbMYGIJqJgCDlYqDy6GqVhd6zPcPTHeUDeR9rVzyWPlH5nLTGze7S5Mo8hn1cSy/Ljmf2Irq6SEoTuKcqcPIwmYqzDcJfUrmJw7vPiFV6hF7Y2yoynU1KVIsIBBI9k9ZBhb22v2Fn9wo8duEXEs4kzkdvx89QL0= alexwilson@Alexanders-iMac.home
```

- Grant AWS Console access?
  > YES
 
- What AWS services do you need access to and why? 
Cloudwatch and other developer-centric services

**Comment by FonzMP** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jsev-io** [comment]
Repopening to simplify Access tracking

In place of the following:
(https://github.com/department-of-veterans-affairs/va.gov-team/issues/13542)

**Comment by jsev-io** [comment]
Requesting AWS Access
cc: @Jeff-Hayter 
User: Alex Wilson
COR: Cecilia Lee

**Comment by drorva** [comment]
AWS logs access aproved.

**Comment by jsev-io** [comment]
Thank you for the approval @drorva !

**Comment by jsev-io** [comment]
AWS Access Granted.
