### ISSUE TITLE
Designers: Attend breakout session

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1345]
Layla/Kevin please complete the item below and and comment done when completed. 

## User Story
As a designer, I need participate in a breakout session with VSP so I can properly be on-boarded to the Benefits and Memorials team.

## Goal
Attend breakout session for designers with VSP team. 

## Acceptance Criteria
Breakout session needs to be completed with VSP team. 

## Definition of Done
- [ ] To be completed in Sprint 3
- [ ] This relates to epic ticket #879

**Comment by smoonpeyes** [comment]
Done.

**Comment by YanaRoy** [comment]
Layla was on VSP team at the time and ran these sessions. She met with Kevin and reviewed presentation with him when he joined the team.
