### ISSUE TITLE
Call facility CTA

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13469]
## User Story
For any confirmed or past appointment of any type, I can see a button to call the facility that will open my phone app.

## Tasks
- [ ] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Android
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting

**Comment by bridgethapner** [comment]
This story is part of #13463, closing in favor of #13463.
