### ISSUE TITLE
Engineers: Attend breakout session

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1346]
## User Story 

As a part of the VSP on boarding process, I need participate in a breakout session so I can properly be on-boarded to the Benefits and Memorials team. 

## Goal 

Attend breakout session for engineers. 

## Acceptance Criteria 

Breakout session scheduled and completed with VSP team.  

 
## Definition of Done 

- [x] *Has been scheduled and completed *

- [ ] *To be completed in Sprint 3 *

- [ ] *This relates to epic ticket #879 *

**Comment by SMLuthi** [comment]
Done.
