### ISSUE TITLE
Directions to facility CTA

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13468]
## User Story
For any confirmed or past VA, Express Care, or Community Care appointment, I can see a button for Directions to the facility that will open my default maps app. 

## Tasks
- [ ] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Android
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting

**Comment by bridgethapner** [comment]
This story is part of #13463, closing in favor of #13463.
