### ISSUE TITLE
Cancel appointment CTA

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13467]
## User Story
For any confirmed appointment of any type, I see a button leading to VA.gov where I can cancel the appointment.

## Tasks
- [ ] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Android
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting

**Comment by bridgethapner** [comment]
This story is part of #13463, closing in favor of #13463.
