### ISSUE TITLE
Google Analytics/Tag Manager Training

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1347]
## High Level User Story
As a VFS engineer, I need to understand how to use Google Analytics and Google Tag Manager so I can implement analytics in a self-sufficient manner.

## Hypothesis/(es)
**If** _we train selected engineers and analytics leads_ **then** _we expect teams to be more self-sufficient in implementing analytics_.

## Goals
Train selected engineers and analytics leads on Google Analytics and Google Tag Manager in order to increase self-sufficiency and free up Insights for more QA and support work

## Objectives
`Intake & Onboarding`, `Support`, `Capacity-building`)

## How to configure this issue
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area**

**Comment by jonwehausen** [comment]
Closing as a historical ticket...will revisit at some point.
