### ISSUE TITLE
Appointments overview - empty

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13470]
## User Story
If I am enrolled in VA health care but have no upcoming appointments, I will see a message indicating that on the Appointments overview screen.
## Tasks
- [ ] High fidelity prototype of screens in iOS
- [ ] High fidelity prototype of screens in Android
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for range of devices we are supporting

## Notes
- If Veterans believe this is an error, does a phone # exist to offer?

**Comment by bridgethapner** [comment]
Closing in favor of #13463
