### ISSUE TITLE
Add veteran status question to coronavirus research form

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#13476]
**Story** 
As a study team looking to enroll participants in a particular research study, it is helpful for me to know if a participant I am considering contacting and enrolling has a relationship with VA and, if so, what that relationship might be, so I am able to select the most qualified participant 

**Proposed content**
> **What is your relationship to the VA  (select all that apply)?**
I am a Veteran 
I am a non-Veteran 
I am a VA employee
I am related to a Veteran
I receive some or all of my care at VHA facility
I have no relationship to a Veteran or the VA

**To do**
- [ ] Question above is reviewed for content (particularly last option — would "none of above" be better?)
- [ ] JSON schema implementation
- [ ] FE implementation
- [ ] BE serialization (if needed)
- [ ] Update contact center schema and tool

**AC**
- [ ] User sees question above (or updated version)
- [ ] User is able to select one or more options
- [ ] If user selects "none of above" type response, all other selections are cleared
- [ ] User can view selection on review screen
- [ ] User's selections can be viewed by contact center representative prior to making confirmation call

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf @stephenBarrs What do you think of this for the question?

**Which of these best describe you (Please select all that apply)?**
Veteran
Active-duty service member
Member of the National Guard or Reserve 
VA employee
Family member or caregiver of a Veteran or service member
Enrolled in VA health care or CHAMPVA
None of the above

**Comment by batemapf** [comment]
Looks good @DanielleThierryUSDSVA, let's go with the single question option. If we learn that lots of people who are enrolled in VHA care are not selecting that option, then we can consider splitting them out.
