### ISSUE TITLE
Everyone: Attend the Discovery and Logistics Workshop

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1348]
## User Story 

As a part of the VSP on boarding process, I need participate in a Discovery and Logistics Workshop intro session so I can properly be on-boarded to the Benefits and Memorials team. 

## Goal 

Attend Discovery and Logistics intro session for Everyone. 

## Acceptance Criteria 

Discovery and Logistics workshop has been scheduled and completed with VSP team.  

 
## Definition of Done 

- [ ] *Has been scheduled and completed *

- [ ] *To be completed in Sprint 3 *

- [ ] *This relates to epic ticket #879 

*Check the box below when this has been completed and comment "done".

**Comment by smoonpeyes** [comment]
Done.

**Comment by SMLuthi** [comment]
Done.

**Comment by YanaRoy** [comment]
@SMLuthi @ndsprinkle @kevinstachura @Mottie Please review the findings from the workshop here. I will close the ticket by EOD 9/10.
https://dsva.slack.com/files/UL39HR399/FMT63UU90/benefits__-_discovery_and_logistics_workshop.pptx

**Comment by SMLuthi** [comment]
this link does not work for me, @YanaRoy

**Comment by YanaRoy** [comment]
@SMLuthi  try this: [Benefits  - Discovery and Logistics Workshop.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3592058/Benefits.-.Discovery.and.Logistics.Workshop.pptx)

**Comment by ndsprinkle** [comment]
Done.

**Comment by Mottie** [comment]
Done.
