### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13483]
## User Story
As a user, I want an onboarding flow when I enter the app so that I understand how to navigate the app. 

**This onboarding flow will be progressive and include the following steps:** 
- The first time I open the app, I will see a dismissable message explaining the scope of the app.
- The first time I visit the Appointments screen, I will see a dismissable message explaining the scope of the app's appointment features. 
- The first time I visit the Claims screen, I will see a dismissable message explaining the scope of the app's Claims features. 
- The first time I visit the Profile screen, I will see a dismissable message explaining the scope of the app's Profile features and clarifying that edits on the app are reflected on VA.gov.

## Invision Link
https://adhoc.invisionapp.com/d/main#/console/20546460/439611290/preview

## Tasks
- [x] High fidelity prototype of screens
- [ ] Start process of VSP content review

**Comment by srmyers17** [comment]
New component for onboarding (cc: @lexicalninja)

**Comment by msmanak** [comment]
![onboarding of app.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/c7407a7a-af8b-4fc6-82a0-fef1077d76e5)

**Comment by bridgethapner** [comment]
I like the lighter direction visually. This is a hypothesis, but I think the interaction design of that direction is a good fit for the app (e.g. explaining a feature's scope a bit right before the user interacts with that feature). This seems more useful to me than an onboarding that would happen upfront all at once -- what do you think?

I like the 'Continue to X' button but wonder if we should maybe make this dismissable module that sits above the screen content under the navbar, or a dismissable modal that sits in front of screen content?
