### ISSUE TITLE
WEAMS Institution Search left nav link does not work

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#13480]
## What happened?
_In the VA Education hub, when clicking on the WEAMS Institution Search link on the left nav, the page refreshes itself and does not go to an appropriate page._

## Specs:
- Device: Macbook
- Browser: Firefox

## Steps to Reproduce
1. Go to https://www.va.gov/education/choosing-a-school/
2. Click on the WEAMS Institution Search left nav link 

## Desired behavior
_ I assume that since there is a left nav link, the link should go to a WEAMS Institution Search page, which seems to be this URL: https://inquiry.vba.va.gov/weamspub/buildSearchInstitutionCriteria.do_

## Acceptance Criteria
- [x] _The left nav link should either be deleted or go to a WEAMS Institution Search page._

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by MickinSahni** [comment]
Should the left nav link be removed or updated? @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
@bethpottsVADEPO @mnorthuis This ticket resurfaced while we were doing the work on the header hierarchy ticket. This will be an easy one for our team to fix, but we just need to know whether the link should be removed in the left nav or point to where Selina had suggested. FYSA @SgardnerPMP

**Comment by mnorthuis** [comment]
It technically should not be in the left nav, since the content doesn't actually live in this area of the site.  It is referenced on the page (lthough not sure if that link or text needs to mention WEAMS) so it is fine to remove it from the nav.

**Comment by RLHecht** [comment]
@bethpottsVADEPO Should we update the link on the page to [Use our WEAMS Institute Search tool]? So that WEAMS is mentioned? And we'll delete the link in the left nav.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Yes, but use "Institution" rather than "Institute." Thanks!

**Comment by RLHecht** [comment]
Whoops! That's what I meant! I updated and published the link and removed the WEAMS link from the left nav. Moving to validate.
