### ISSUE TITLE
Proof read and publish UAT copy updates for the 22-1995 form detail page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13491]
Please review the copy updates on the 22-1995 form page and publish after making any needed copy edits. 

**This page:** 
http://preview-prod.vfs.va.gov/preview?nodeId=5977 

**Luke Tickner provided UAT review of form page 22-1995:**

- The 1995 is no longer used to apply for the STEM scholarship - remove last bullet point in WHEN TO USE THIS FORM text. 
- Update HELPFUL LINKS section - point STEM link to the new online STEM application page and update text accordingly. 
- https://www.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction

Note: There does not appear to be a paper/PDF version of 22-10203 form, only the online tool.

**Comment by RLHecht** [comment]
@jenniferlee-dsva This looks good. I've reviewed and published.

**Comment by jenniferlee-dsva** [comment]
Thank you!
