### ISSUE TITLE
Static map icons are missing on VAMC and VC pages

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#13490]
![image.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/1d9507ee-aacb-4790-a935-84891e4b1544)

Map pin images were accidentally deleted in https://github.com/department-of-veterans-affairs/vets-website/pull/14154/files

**Comment by mmiddaugh** [comment]
@mpelzsherman this page is still missing the map
![image](https://user-images.githubusercontent.com/55411834/93827304-3c5e6f00-fc26-11ea-9a7b-af3b95c255a7.png)

**Comment by mmiddaugh** [comment]
Also, I created a separate issue for Facility Locator detail pages https://github.com/department-of-veterans-affairs/va.gov-team/issues/13811 which will likely be added to the new sprint, FYI

**Comment by mmiddaugh** [comment]
Looks good!
