### ISSUE TITLE
Access for Anthony Kopczyk

### ISSUE THREAD

**Issue by anthony-kopczyk** [department-of-veterans-affairs/va.gov-team#13493]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Anthony Kopczyk
- Please Provide your email.
   > anthony.kopczyk@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: okAPI | Role: Node.js Engineer | Company: Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDA0VhvCT8msJLG5lVVxfe+xPbSjq8zx/bHMrC8F8hy22RpxaTiMamAntqNcu9oOEjnvMx8xFoj7R8jIB8eLDiGkfDBnG8jX4tnagJP/L4mHLzaEOwaEVGy/nL3UyCY7/aVPCULBqnrNJIWf1gANNMDc0GdbFoR0R9YybMzB9rK7PCcytP2RKTS0PkgBv4OWhj8S8cQaheEkCGtnoLRjoBmeQQ4K9+hHPapl0WlsMXEpT7NO/JX9Bnma2Zv5hTfAUtB75ballFQYFD+DS5iDGsZOT2sl24HLnYZHJ+GhAV4E+CPbHcshko4J8qMiKOe3CJW+yanpqko9mbpmdQkRK27Lk+0sdIhFw5U/bFICeKK2M0qpqiLoBTz/PCPw4ZxEKFYI+UItwbZGCdBwDPkwNvM34+JtffUXrDvBVL00aB9MEfSCKVKu07aaBlsQ39YouupCmV9j5EpivSfwOfGTqyDPHcb91ub76Ef9Rv+peQMa/7aDK2YPc00Rz1Tbik9Z78= anthony.kopczyk@oddball.io
```

- Grant AWS Console access?
  > YES
  - Need AWS Console access for developing and maintaining the Lighthouse dev portal.

**Comment by anthony-kopczyk** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
### For AWS Access:

User: Anthony Kopczyk
COR: Cecilia Lee
Approval needed: @Jeff-Hayter

**Comment by pnwstevan** [comment]
Hi @anthony-kopczyk!

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

**Comment by Jeff-Hayter** [comment]
@pnwstevan Approved for AWS access.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
