### ISSUE TITLE
Access for Alexander Valencia

### ISSUE THREAD

**Issue by alexandervalencia** [department-of-veterans-affairs/va.gov-team#13495]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecellia Lam
- Please provide your name.
   > Alexander Valencia
- Please Provide your email.
   > alex.valencia@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse (Quokka) - Frontend Engineer - AdHoc LLC

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC37IbHGSJ4Ye1bEfHGg/9zcVnbrFLPyGmOPa+N/PKr4z6WZOadU8X3i3Kq6yowS5cXtmxWXY9hYlHaGqNR0Y7SDc8AH25VyqSTShspFSij/hthOTCoiPm5Kv8FROqYRsP/rZERq4ZP1BtDO+p55GOSF5SIkuhR1GVn390wk2DVVjgM3WLhWZvbNVGejw+7fJWTJ7z27qmw2lmIALMDonb0+40IOawv6OieCcyYDBxYnnD8Dq16qjDxjNfItljci2Z8RUgUI4C5/KShPhCr2cxzI0tGchULMBeOvwMAssaT26vbS2TTx7SK5w9wNfTc/rpC8UIX3nGQi6kyE/3gK/TDl4mItqcFCrfQ7tkl56+wA4VUOkm+qvIWn+bObcoA6UTZq9HQ2vB5xF8PqNjI1rXmUEWP7t111wD5dBWeM1l1UMvoTzbbFuFCuES6gKoqfXxxuKboXk1KJH2w0Wp0Kpw2xwacnFlXS0yl0bqLh4uaa9t5A7fvzVKq0FBGPjGxymk= alex.valencia@adhocteam.us
```

- Grant AWS Console access?
  > YES
  - AWS Console access for developing and maintaining the Lighthouse dev portal

**Comment by alexandervalencia** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by pnwstevan** [comment]
**For AWS Access:**
User: Alexander Valencia
COR: Crystal Moultrie
Approval needed: @Jeff-Hayter

**Comment by pnwstevan** [comment]
Hi @alexandervalencia!  

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

**Comment by Jeff-Hayter** [comment]
@alexandervalencia I have not heard back from your COR regarding eQIP status.  If you have a copy of your eQIP acceptance email that can speed things along.

**Comment by Jeff-Hayter** [comment]
@alexandervalencia Can you please confirm the COR and team listed above is correct?  Crystal is not seeing your name in her roster.

**Comment by alexandervalencia** [comment]
Hi @Jeff-Hayter I've learned my COR is actually Cecellia Lam. Please let me know where I can send my eQIP acceptance email.

**Comment by jsev-io** [comment]
@alexandervalencia Please update the ticket to reflect your COR.

**Comment by alexandervalencia** [comment]
@jsev-io I've updated the ticket. Please let me know if there's anything else you need from me. Thanks!

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by jbritt1** [comment]
Temporary credentials provided to user.
