### ISSUE TITLE
Rewrite `va.gov-team` repo root README.md

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#135]
## Description
Currently, the `va.gov-team` README is focused on WBC. Now we need to move that README into a different appropriate place, and write a new README.md file for the root of the va.gov-team repo.

## Considerations
Link to the readme: https://github.com/department-of-veterans-affairs/va.gov-team

The README.md file needs to make sense as the summary of what's in the va.gov-team repo. We could probably jsut take the content from Mikki's repo IA presentation, and restructure to make sense as an .md file. A lot of that content was geared toward the goal of helping ppl understand the purpose of this repo, which is exactly what the README.md needs to convey as well.

## Acceptance Criteria 
- [ ] A draft has been written for the new README.md with a structure that fits in with the work of VSP
- [ ] Reviewed by DSVA
- [x] va.gov-team repo README.md has been updated in master

**Comment by smoonpeyes** [comment]
@rtluu @emilywaggoner 

Created a draft version here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/README-draft.md
* Added Document History section
* Added separate paths for people building for Veterans vs. people building tools and resources for teams that build products for Veterans
* Removed point of contact info (not sure if this info should be public)

**Comment by rtluu** [comment]
This is great @smoonpeyes! I just turned your Draft into the main readme, we can continue to flesh things out there like the `Onboarding` section

**Comment by rtluu** [comment]
This work has started but it appears that it will take some additional thought and content migration before this can be fully fleshed. I'm pulling it back to Ready to be reevaluated for future sprints

**Comment by mnorthuis** [comment]
Moving this issue under the new va.gov-repo IA epic.  This will need to be done as part of the repo build out.

**Comment by rroueche** [comment]
I updated the description to reflect what we need today, now that we have a good strategy for the purpose and IA of the repo.

**Comment by mnorthuis** [comment]
@rroueche I think this should be worked on with the VSP leadership team to determine how we want to frame up that initial README.md file.   If the info that is out there today is good, I can update it per our structural changes, but could you review with Patrick, Leah and others to determine if the content is what we want?

**Comment by mnorthuis** [comment]
I have updated the current README.md so the description and links are correct.  Work to further refine how we want the "introduction" to VSP to be represented on the file can be done in future sprint in collaboration with VSP leadership team. 

Closing this issue.
