### ISSUE TITLE
STEM: 10203 Post-launch updates: Email content

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13505]
## Acceptance Criteria: 
- [x] Update SCO Email (content doc) to include updated privacy policy anchor link 
- [ ] Ensure link functions as anticipated

**Comment by amyknox** [comment]
2 Content docs for SCO email exist. Both have been updated with new 10203 link w/ privacy policy anchor.

**Comment by amyknox** [comment]
@dneel-bah or @desireeturner - any possibility that the SCO Email with the #privacy_policy anchor will be updated and testable this sprint?

**Comment by desireeturner** [comment]
@amyknox That is not planned for this sprint. cc @dneel-bah

**Comment by dneel-bah** [comment]
@amyknox 

The anchor link was completed as part of: #12752 which has already been delivered to production.
The SCO email was updated as part of: #12359 which has been delivered to staging / production behind the EVSS feature flag.

cc @desireeturner

**Comment by amyknox** [comment]
@desireeturner - thanks for the info. closing this story then!

**Comment by amyknox** [comment]
@dneel-bah UX has a task to test the email link.  I don't believe we were able to test #12359 so we'll want to confirm that functions as anticipated

cc @desireeturner

**Comment by amyknox** [comment]
Task 2 is OBE. 

Per Adam: We can only create a local preview of that story, that one isn't able to be tested in staging.

Once the email can be generated, UX will jump on the testing bandwagon to ensure the anchor link works as anticipated.
