### ISSUE TITLE
STEM: 10203 - Twilio update: UXBA Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13507]
## Tasks
1. Review Twilio update in UXBA Sync 
2. Confirm functionality works per dev 
3. Updates to prototype/content doc, if needed

**Comment by amyknox** [comment]
Reviewed in UXBA Sync. 
BA/TL suggested mobile phone field may need "(* Required) notation but not error / validation message once user selects text message checkbox. 
UX team is working with VSP accessibility to verify & will report back, update as necessary.

**Comment by ccruzgra** [comment]
BA also suggested potentially adding in the warning alert that the number is required if we don't have a required label for the mobile field.

**Comment by ccruzgra** [comment]
After deliberating on the issue of whether to have the mobile field required or not, Trevor Pierce recommended the path forward is to have the mobile field required as soon as users selected the checkbox. 

@amyknox Closing this story.
