### ISSUE TITLE
Front-end Engineers: Attend deep-dive session

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1350]
## User Story  

As a part of the VSP on boarding process, I need participate in a front-end engineering deep dive session so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  

 Attend deep dive intro session for front-end engineers.  

## Acceptance Criteria  

Deep dive intro session has been scheduled and completed with VSP team.   

## Definition of Done  

- [x] Has been scheduled and completed * 

- [ ] To be completed in Sprint 3 * 

- [ ] This relates to epic ticket #879 *

Check the box below when this has been completed and comment "done".

**Comment by YanaRoy** [comment]
@Mottie @ndsprinkle please reach out to @accbjt to coordinate a day/time to complete this session.

**Comment by Mottie** [comment]
Huh, we had our deep dive session with Bill Tran on 9/17.

**Comment by ndsprinkle** [comment]
@YanaRoy @Mottie That's true, we did already do this. I think we were supposed to comment Done, but I forgot to do that.

**Comment by YanaRoy** [comment]
Ok, then I'm closing! Thanks @Mottie @ndsprinkle !!
