### ISSUE TITLE
STEM: 10203 Establish KPI Dashboard

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13519]
## Tasks
1. Support DEPO on 10203 KPI Dashboards 
2. Align priority widgets / KPIs with EDU - 9/17 
3. Share status with EDU - 9/26"

**Comment by amyknox** [comment]
VSP Analytics story: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13103
