### ISSUE TITLE
Back-end Engineers: Attend deep-dive session

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1351]
## User Story 

As a part of the VSP on boarding process, I need participate in a back-end breakout session so I can properly be on-boarded to the Benefits and Memorials team. 

## Goal 

Attend breakout session for back-end engineers. 

## Acceptance Criteria 

Breakout session scheduled and completed with VSP team.  

 
## Definition of Done 

- [ ] *Has been scheduled and completed *

- [ ] *To be completed in Sprint 3 *

- [ ] *This relates to epic ticket #879 *Check the box below when completed and comment "done".

**Comment by SMLuthi** [comment]
Done.
