### ISSUE TITLE
STEM: 10203 Track daily submissions

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13518]
## Tasks
1. Review STEM Submission analytics (Goal Funnel) each morning
   a. download funnel PDF and report findings to team
2. Incorporate these findings into EDU agenda to verify #s from Buffalo are tracking

**Comment by amyknox** [comment]
Tracking submissions from Sept 2 to current date. 
URL for 9/2-13
https://analytics.google.com/analytics/web/#/report/conversions-goal-funnel/a50123418w177519031p184334251/_u.date00=20200902&_u.date01=20200913&_.goalOption=14

**Comment by amyknox** [comment]
[Report for 9/2-13](https://app.zenhub.com/files/133843125/2ded3d83-9483-4674-bd1b-ea09148e6051/download)

[Report for 9/2-14](https://app.zenhub.com/files/133843125/5ede485c-2f87-43e1-b01d-c6be746e9de4/download)

**Comment by amyknox** [comment]
[Report launch thru 9/16](https://app.zenhub.com/files/133843125/3ff70789-5e3e-4e0d-a53f-a8ad39be333f/download)

**Comment by amyknox** [comment]
[Report launch through 9/17](https://app.zenhub.com/files/133843125/1c9d113c-16ca-4085-ac95-d18fd7603a59/download)

**Comment by amyknox** [comment]
[Report launch through 9/20](https://app.zenhub.com/files/133843125/09595e91-36ca-4ccb-b69b-14d8e63cfd4c/download)

**Comment by amyknox** [comment]
[Report launch, 9/2, through 9/24](https://app.zenhub.com/files/133843125/a376025e-da7e-4378-8647-bcdda0ea7c05/download)

**Comment by amyknox** [comment]
[Report: Launch 9/2 - through 9/24](https://app.zenhub.com/files/133843125/5c6eadfc-da15-4b23-932f-401a920191a9/download)
