### ISSUE TITLE
Access for [individual]

### ISSUE THREAD

**Issue by RoStokes** [department-of-veterans-affairs/va.gov-team#13516]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Rothesia Stokes
- Please Provide your email.
   > ro.stokes@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >VFS-CMS Project, Help Desk Support, CivicActions

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPra+PPb4Rd6BOcpdfNljgT3HieixdM9MdFzpas5YfeV4aIOoygemJevGkmovt5SemGjLDAmJRksL1R98Lgi7P2HZ7lrx5J82amw9GYDYSBwc/0Q+DnvK1ukMFtmoNHHePX6Uor0k9z1iI/z+RlWtSbx5/DQ2o1164OqRh2ExGlRyKd8aDfOIZYLUi33/yjQ3UHxMgHSPrKKhRhaJ0xld886BOSHSq6I8ZPxPKPHWefkDtPupSYcpZWKs2qSCpvD9+BtMI+LpVcdUh+R4+ALVhLYeQzK5j/uPIWggoVz1AZeiFCIdo8xCXIT6s1Ja463T9Gx3f2/1T7uEaAaxYRwddqUOFtPLz+DUz1yYonkO0q4zIn7ez4HaaWpBPeb+b2sL71ByAfTKPI2yPO8Q8ru0i1syb2VFOxLOGdrCm9ISnRAKbPjSMHAJCwKN4ur5Qw+WEYQcCRBt/pOtSluLJ4vQQAxNEGpP/xqTXbnZrWKGyX4oUUVvTtJSjRH/RHHKIfzc= Lilbit@RDS-PC
```

- Grant AWS Console access?
  > NO

@department-of-veterans-affairs/vsp-operations

**Comment by pnwstevan** [comment]
Hi @RoStokes! 

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.
