### ISSUE TITLE
STEM: 22-1995 Establish KPI Dashboard

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13521]
## Tasks
1. Support DEPO on 1995 KPI Dashboards 
2. Align priority widgets / KPIs with EDU 
3. Share status with EDU

**Comment by amyknox** [comment]
Submitted KPI Dashboard request, [#18316](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18316)

Story may take DEPO up to 3 sprints to complete.

**Comment by amyknox** [comment]
Great news - looks like the 22-1995 Dashboard may get some DEPO love in the near future: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23221#issuecomment-820571968
