### ISSUE TITLE
STEM: 22-1995: Enhancements - Prototype Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13524]
## Tasks
1. Update prototype, as necessary, with items sanctioned by EDU (align version # with corresponding GH content doc)

**Comment by ccruzgra** [comment]
@amyknox @JenLJ If you all took a look at the prototype updates, and everything looks good on your end, then this can be closed.

**Comment by ccruzgra** [comment]
Got feedback from UXers for some minor tweaks to the UI, and those were completed this morning.
