### ISSUE TITLE
STEM: 22-1995: Enhancements - Content Doc Updates 

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13525]
## Tasks
1. Incorporate updates sanctioned by EDU into new version of GH content doc (align version # with prototype)

**Comment by ccruzgra** [comment]
The 1995 content doc has been created here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/1995/content/1995-content-doc-v3.0.md

**Comment by ccruzgra** [comment]
@amyknox Once this looks good to you, feel free to close the story.

**Comment by ccruzgra** [comment]
UXers provided some additional feedback for the content vs. prototype updates, and I finished those updates in the content doc.
