### ISSUE TITLE
School Ratings: Content Doc

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13529]
## Assumptions: 
1. Keep general content as-is until a path forward on ratings collection & information sharing is identified, or at least drafted. 

## Tasks: 
1. Update Ratings Content Doc to reflect new approach to NA, Marketing practices, Adjust "About ratings" content for scannability.

**Comment by amyknox** [comment]
@ccruzgra per current status of [content doc v5](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/design/content-doc-v0.5.md),  this story looks complete.
