### ISSUE TITLE
STEM: 22-1995 KPIs

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13520]
## Tasks
1. Draft 3-5 KPIs for form 
2. Review KPIs with EDU 
3. Revise, if necessary, & document in GH

**Comment by amyknox** [comment]
Resources to help with this effort: 

[Initial 1995 charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/1995/vets-gov-charter-for-1995-feb-2017-signed.pdf) - Check out Sec4 MVP Scope of Work; Sec6 Ongoing maintenance; Sec7 Assumptions
[22-1995 Funnel for Summer 2020](https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goal-funnel/a50123418w177519031p184334251/_u.date00=20200601&_u.date01=20200831&_.goalOption=4&funnel_goaloption_4-graphOptions.selected=analytics.nthWeek)
[Analytics Playbook](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/AnalyticsPlaybook.md)
[KPI Pre-workshop Planning](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-setting-pre-workshop-template.md)
[KPI Mural](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1591285060838/5b950dfe08c860feb2b26d049665f8a043ee278d)

[22-10203 KPIs in DOMO](https://va-gov.domo.com/page/558555603)
