### ISSUE TITLE
STEM: 22-1995 Enhancement Recs - EDU Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13523]
## Tasks
1. Review list of enhancements with EDU 
2. Discuss priorities & feasibility

**Comment by amyknox** [comment]
List shared with EDU 9/14. Input anticipated 9/17.

**Comment by amyknox** [comment]
EDU's good with the full list of recommended enhancements

From Luke Tickner - 

On the 22-1995 updates: All are good and I have no issues with those changes except for the following:
 
8 b: update telephone labels.  If we change it to mobile and home which one would then be required?  I’d like to think most folks would just put in whatever number they have.  But if we make mobile mandatory for example, someone without a mobile phone might be confused.  Would it be possible to let them select the phone type if we want that (assuming it would be good to know if it is mobile in case we are going to send text messages).  Just want to make sure we think through this one. 

> From DARRELL 
> Currently:
> The 1995 has the question “How would you like to be contacted if we have questions about your application?” with a single “Phone” option.  When the user selects “Phone”, the “Primary telephone number” field is marked required.
> 
> Update:
> 1.	The question “How would you like to be contacted if we have questions about your application?” will have 2 phone options “Home Phone Number” and “Mobile Phone Number”.  
> 2.	The “Primary telephone number” and “Secondary telephone number” fields will be updated to match the answer options “Home Phone Number” and “Mobile Phone Number”
> 3.	If the user does not select home/mobile as an answer to: “How would you like to be contacted if we have questions about your application?”, the fields will not be required.
> a.	If they do, the corresponding field is marked required.
> 

 
8 c: do we have a list of countries without postal codes?  Is that something that would have to be reviewed and updated regularly or are we pulling that from a recognized source?


> The “postal code” field validation behaves differently for us vs foreign countries.  In this instance, the required / 5 digit validation will be removed if the user selects a non-US country.  There is no “approved list” of zip codes that needs to be managed.
