### ISSUE TITLE
School Ratings: About Ratings content tweaks

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13528]
## Tasks
1. Update About Ratings WIP content so it's not alarming to potential raters.    
   a. Alternative: incorporate the final decision making into UI updates

**Comment by ccruzgra** [comment]
I put together content updates and Amy and Jen provided feedback. Amy mentioned she'll be dropping the updates into the ratings content doc.

**Comment by amyknox** [comment]
Content doc is updated. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/design/content-doc-v0.5.md
