### ISSUE TITLE
CT Site Search: 107 Prototype Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13538]
## Tasks
- [x] Update prototype with 107 content

**Comment by ccruzgra** [comment]
These updates are included as part of the CT Search/Filters v0.3 Prototype - Desktop: https://bahdigital.invisionapp.com/share/PVIAEVAXHK7

The landing page includes a modal for the housing question that shows the updated copy.

**Comment by ccruzgra** [comment]
Added to landing page yesterday. Will be incorporating into search and profile page today/Monday since they also contain the housing question.

**Comment by ccruzgra** [comment]
All housing question learn more modal views have been incorporated into the above prototype since the housing question is found on the landing page, search results page, and within the Estimate Your Benefits accordion of institution profile pages.
