### ISSUE TITLE
School Ratings: EDU Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13532]
## Tasks
1. Review Ratings with EDU Confirm design & functionality are incorporated as anticipated 
2. Updates to prototype/content doc, if needed

**Comment by amyknox** [comment]
Reviewed w EDU to review 9/14

Joe P really liked it. Reminds him of Amazon. Well organized, easy to read. You know what every category means. 

Provided input on top 3 "Marketing practices" alternatives

- Cost and admissions
- True to expectations
- Expectations vs reality
