### ISSUE TITLE
School Ratings: UXBA Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13531]
## Tasks
1. Review Ratings updates with UXBA Sync 
2. Respond to questions 
3. Updates to prototype/content doc, if needed

**Comment by ccruzgra** [comment]
@amyknox We completed this yesterday, and the only feedback item was to consider adding some copy to the "About Ratings" section regarding N/A and how it does not affect the overall category calculations.

**Comment by ccruzgra** [comment]
Sent over copy updates for "About Ratings" to other UXers for feedback.
