### ISSUE TITLE
School Ratings: UI Updates	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13530]
## Tasks
1. Align with UX team on approach to NA, Marketing practices, About Ratings content 
2. Update prototype to reflect approach Review w UX team

**Comment by ccruzgra** [comment]
UXers agreed on using "True to expectations" as the alternative for "Marketing practices", so I updated that in the prototype. Will be including the updated "About Ratings" content since we just finalized it.

**Comment by ccruzgra** [comment]
@amyknox @JenLJ If you all took a look at the prototypes that were updated and had no feedback items, then this can be closed.
