### ISSUE TITLE
508-defect-2 [HEADINGS, COGNITION]: Heading levels SHOULD only increase by one 

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#13545]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The alert box heading is an `H3` but there isn't a preceding `H2` (see screenshot enclosed). When teams use the [AlertBox component in React apps they must use the level property](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/) to ensure the alert box heading suits the semantic structure of the page. 

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to navigate the page by headings without worrying there is skipped content.

## Environment

* Operating System: all
* Browser: all
* Screenreading device: any
* Server destination: staging

## Steps to Recreate

1. Enter https://staging.va.gov/manage-va-debt/your-debt/ and please use Greg Anderson (user 1). This tests a user with a number of debts and debt letters.
2. Select "Go to debt details >"
3. Run an axe browser scan
4. Verify "Heading levels should only increase by one" is listed, associated with `<h3 class="usa-alert-heading">Hidden alert</h3>` 

## Possible Fixes (optional)

Set the level prop on the AlertBox component to `2`.

## WCAG or Vendor Guidance (optional)

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/common-issues/headings-should-increase-by-one.md

## Screenshots or Trace Logs

![Screen Shot 2020-09-14 at 5 15 40 PM](https://user-images.githubusercontent.com/57469/93139209-4a544300-f6ae-11ea-991b-05eec6ca0a4f.png)

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by bradl3yC** [comment]
@jenstrickland please validate

**Comment by jenstrickland** [comment]
@bradl3yC Is there a different url I should use? `https://staging.va.gov/manage-va-debt/your-debt/` returns a 404.

**Comment by jenstrickland** [comment]
Validated! 🎉
