### ISSUE TITLE
Update the 10-10CG form detail page with button to online tool when it goes live

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13548]
User story: As a Veteran, if I'm trying to find the paper 10-10CG form, I want to know if there's an easier online alternative, so I can apply online instead of mailing in a form. 

On this page in the CMS: https://www.va.gov/find-forms/about-form-10-10cg/ - add an online tool button to the new online 10-10CG app when it goes live. (Approx eta October.)

**Comment by jenniferlee-dsva** [comment]
Related ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11592

**Comment by lunascoop** [comment]
It seems that this tool is now live. I will pull this ticket into this sprint to update the form detail page. CC: @MickinSahni @brianalloyd @DanielleThierryUSDSVA

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @lunascoop! Yes, launched this morning. Let me know what you need from me to support.

**Comment by lunascoop** [comment]
Online tool has been added and published. Closing ticket.
