### ISSUE TITLE
PM and Front-End Engineers: Request analytics intro

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1355]
## User Story  
As a part of the VSP on boarding process, I need participate in a Analytics intro session so I can properly be on-boarded to the Benefits and Memorials team.  

## Goal  
Attend analytics intro session for PM and Front-End Engineers. 

## Acceptance Criteria  
Analytics intro has been scheduled and completed with VSP team.   

## Definition of Done  
- [x] *Has been scheduled and completed *
- [x] *To be completed in Sprint 3 * 
- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by ndsprinkle** [comment]
Done.

**Comment by YanaRoy** [comment]
Done.
