### ISSUE TITLE
UAT bug: Add 'Last updated' date on form detail page templates

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13565]
## Add 'Last updated' date on form detail page templates

I'm not sure if this is FE template or CMS backend. 

The "Last updated: Month Day, YYYY" that appears by default on all of our modern VA.gov pages is missing on the form detail pages. (FWIW, the Find a VA form search page DOES have this date.) 

**AC:**
- [ ] On a form detail page, at the bottom of the page (right before the global footer), there should appear a "Last updated:" date field. 
- [ ] And it should show the correct last updated page date. (This date is DIFFERENT - not the same thing - as the "Form last updated" date. 

Example form detail page: https://www.va.gov/find-forms/about-form-22-1995/   `<-- this form page should be showing a page updated info of: September 14, 2020 `

**Comment by kelsonic** [comment]
I think the last updated field is appearing: ![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/5f09f64b-b975-4d1c-8960-a4d169c7625b) Are we expecting different behavior? :)

**Comment by kelsonic** [comment]
PR merged, should be live today following the daily deploy 🎉

**Comment by MickinSahni** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/13204473/93956699-c8ed5800-fd20-11ea-8616-85fd656c94ed.png">
