### ISSUE TITLE
[Discovery] Comparative analysis for map interaction

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13568]
## Issue description

**Current behavior:** the Facility Locator actively searches and re-searches as the user interacts with the map. The user does not have a way to stop this process or indicate that the map is set for a search.

To inform our enhancements to the map interaction on Facility Locator, we should review examples of modern websites which are handling this well. 

## Related issues
[#13229](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13229) for map display when zooming
[#9498](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9498) for supporting users when no results are found
[#5201](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5201) for proposed 250 mile limitation
[#13299](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13299) for optimizing map view

## Tasks
- Conduct a comparative analysis to collect examples of map interaction to reference related to visual design and user experience, considering the following:

- What should the default map zoom level be?
   - Urban vs rural? See [#13299](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13299)
- Which map interactions should trigger a new search?
- Are there any map interactions which should **not** trigger a new search?
- Does the search experience differ when users interacting with the map compared to when the user changes parameters in the search fields? 
   - Is the experience different for panning vs zooming?
- How should the Veteran initiate a new search after interacting with the map or specifying new/refined parameters? 
   - for example: Search this area? New search?
- What does the map display when the user has panned/zoomed? 
  - such as: new result set or all results?
- Is there a limit to the distance which can be panned?
- How can a user stop a search already in progress?
- How should the UI change based on interactions with the map?
   - Should the original parameters be updated?
   - What happens to the subhead?
   - How does this change the distance/directions displayed in the search results?
- What error messages are needed to support users in these scenarios?
- What considerations are needed for accessibility?

## Acceptance Criteria
- Documentation of predictive search examples and recommendations for UX
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
Link to [competitive analysis in a Google Sheet](https://docs.google.com/spreadsheets/d/1sIqiSYLL6JXqaQJ3iGUnBYYjOxFLTmn0TRWeN0HcDbM/edit?usp=sharing).
