### ISSUE TITLE
[Zeitwerk] - Handle initialization Deprecation Warning

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#13562]
With lib directory loading changes, this DEPRECATION WARNING has started to appear when running `vets-api` natively.  The message seems to indicate switching to zeitwerk will clear it up.  Want to be sure this deprecation is handled after the changes have been made.

```
DEPRECATION WARNING: Initialization autoloaded the constants VAOS::Middleware, VAOS::Configuration, UserSessionForm, V1, AuthenticationAndSSOConcerns, ApplicationController, V1::SessionsController, V0, IgnoreNotFound, V0::Post911GIBillStatusesController, EVSS::DisabilityCompensationForm::JobStatus, EVSS::DisabilityCompensationForm::Job, EVSS::DisabilityCompensationForm::SubmitForm526, SentryJob, Form1010cg, Form1010cg::Service, EVSS::DisabilityCompensationForm::SubmitUploads, CentralMail::SubmitForm4142Job, EVSS::DisabilityCompensationForm::SubmitForm0781, EVSS::DisabilityCompensationForm::SubmitForm8940, and EVSS::DisabilityCompensationForm::SubmitForm526Cleanup.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload VAOS::Middleware, for example,
the expected changes won't be reflected in that stale Module object.

`config.autoloader` is set to `classic`. These autoloaded constants would have been unloaded if `config.autoloader` had been set to `:zeitwerk`.
```

### definition of done
If the deprecation warning is gone, close this ticket.  If there is still a deprecation warning after zeitwerk is enabled, triage and create a new ticket.

**Comment by erluti** [comment]
running rails zeitwerk:check can give more information about other things that need to change to support future versions of autoloading. More details here:
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#autoloading

**Comment by erluti** [comment]
Appears to still be an issue with zeitwerk enabled

```
Rails -- DEPRECATION WARNING: Initialization autoloaded the constants CovidVaccine::SubmissionJob, CovidVaccine::V0, CovidVaccine::V0::RegistrationService, ExceptionHandling, Headers, Instrumentation, SentryControllerLogging, Mobile::ApplicationController, VAOS::Middleware, VAOS::Configuration, CovidVaccine::V0::VetextConfiguration, ApplicationRecord, FeatureToggleEvent, UserSessionForm, V1, AuthenticationAndSSOConcerns, ApplicationController, V1::SessionsController, V0, IgnoreNotFound, V0::Post911GIBillStatusesController, EVSS::DisabilityCompensationForm::JobStatus, EVSS::DisabilityCompensationForm::Job, EVSS::DisabilityCompensationForm::SubmitForm526, SentryJob, Form1010cg, Form1010cg::Auditor, EVSS::DisabilityCompensationForm::SubmitUploads, CentralMail::SubmitForm4142Job, EVSS::DisabilityCompensationForm::SubmitForm0781, EVSS::DisabilityCompensationForm::SubmitForm8940, EVSS::DisabilityCompensationForm::SubmitForm526Cleanup, and Form526ConfirmationEmailJob.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload CovidVaccine::SubmissionJob, for example,
the expected changes won't be reflected in that stale Class object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /Users/philip/oddball/vets-api/config/environment.rb:7)
```
possibly related to https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14689

**Comment by erluti** [comment]
The issue is the listed classes are referenced in `/initializers`.
Each one of those classes will have to be addressed individually most likely.
The rails guides discusses some strategies that might help https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#reloading

**Comment by LindseySaari** [comment]
@thilton-oddball I checked out [this article](https://guides.rubyonrails.org/autoloading_and_reloading_constants_classic_mode.html), which suggests using the `Rails.configuration.to_prepare `API or to possibly explicitly require dependencies in initializers (see the second answer [here](https://stackoverflow.com/questions/56402093/how-can-i-preload-concerns-in-a-rails-initializer-using-rails-6-zeitwerk). The above deprecation error seems to be mostly coming from the statsd.rb initalizers.

**Comment by LindseySaari** [comment]
Reloading does not reboot the application, and therefore code executed during initialization does not run again. So, if you reload, changes to classes in the initializer won't be reflected in that stale Class object because the initializer only runs on reboot. Therefore, code that references a reloadable class or module, but that is not executed again on reload, becomes stale. 

The [rails guide](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#reloading-and-stale-objects) has some great examples

Also see:
https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots
