### ISSUE TITLE
Investigate the slowdown that was caused

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#13566]
After the initial rollback, Michael Pelz-Sherman said
```
could be coincidental, but the api calls seem MUCH faster now than they were a few hrs ago.
```
Following up he said the issue was with facilities endpoints.

We need to investigate facilties endpoints response times during the initial deploy and see if we can reproduce any slowness of those endpoints.

**Comment by alexpappasoddball** [comment]
@erluti can you provide the details for this ticket?

**Comment by erluti** [comment]
> @erluti can you provide the details for this ticket?

updated the description

**Comment by erluti** [comment]
After reviewing latency metrics from the time of deploy, this is a non-issue.

Here are grafana graphs for when the lib-loading changes were deployed and rolled back (the two marker lines).  The times used are EDT.
In this first graph you can see the mean latency for the whole system is relatively flat during the time the lib-loading changes were deployed compared to for the hours leading up to and after the time it was in production.
![Screen Shot 2020-09-15 at 1 04 21 PM](https://user-images.githubusercontent.com/103328/93253606-1b4cd880-f765-11ea-883b-de93d089557c.png)
In this graph you can see the latency on the facilities endpoints (which Michael said was where he specifically felt there was a slowdown) and the latency for the 24 hours leading up to the deploy and the 4 hours after the rollback were similar to latency for facilities at other times.
![Screen Shot 2020-09-15 at 1 10 52 PM](https://user-images.githubusercontent.com/103328/93253604-1ab44200-f765-11ea-9bfe-81aa5c5734de.png)
This final graph shows most of the day of the deploy, and latency during the time lib-loading is deployed is in-line with latency throughout the day broken down by endpoints.
![Screen Shot 2020-09-15 at 1 11 52 PM](https://user-images.githubusercontent.com/103328/93253596-18ea7e80-f765-11ea-983a-a3edb30ce753.png)
