### ISSUE TITLE
Access for Giles Wells (AWS Parameter Store permissions)

### ISSUE THREAD

**Issue by gileswells** [department-of-veterans-affairs/va.gov-team#13563]
I already have SOCKS proxy access and AWS console access. I am looking to add AWS permissions to be able to read Parameter Store values, at least (don't believe I need write access at this time, will open a new request if that's the case).

- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Giles Wells
- Please Provide your email.
   > giles.wells@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse/VA APIs program
   > Team OkAPI (developer portal)
   > Software engineer
   > Company: Oddball

- Requesting SSH key authorization?
   > NO (already have it)

- Grant AWS Console access?
   > YES - additional permissions for Parameter Store

- Please give a brief description for why you are requesting AWS access.
   > Our team uses Parameter Store to manage secrets and other environment variables for the Lighthouse developer portal backend (https://github.com/department-of-veterans-affairs/developer-portal-backend). I would like to be able to view these values in the AWS console.

**Comment by gileswells** [comment]
Requesting additional AWS permissions @department-of-veterans-affairs/vsp-operations

**Comment by pnwstevan** [comment]
Hi @gileswells!

You are already a member of the `lighthouse-developers` group which includes a policy called `dvp-parameter-store-admin` that gives full read/write access to anything in Parameter Store under `/dvp`. I believe everything you should need is within that ParamStore directory?

Are you having issues or do you need something beyond ^^ ?

**Comment by gileswells** [comment]
@pnwstevan I have someone looking into it on my end as I might have asked for the wrong thing or be looking in the wrong spot in AWS. Will update back if more assistance is needed.
\

**Comment by gileswells** [comment]
Sorry for the delay. This was resolved.
