### ISSUE TITLE
UX flow for US Postal Service doesn't recognize address

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#13570]
## Background
On 9/15 I met with the VSA Authenticated Experience team & they are sending over the UX for the scenario where the US Postal Service doesn't understand the address the user inputs. 

#### 10/12 update -- from Profile 2.0 Product Guide
When people update and save their addresses, the VA.gov profile checks the likelihood that the U.S. Postal Service will be able to deliver mail to them. This is called address validation. If someone tries to save an address that our system flags as problematic, they will see one of the following scenarios:
1. A prompt to confirm the address, with potential address suggestions
2. A prompt to confirm the address, with no suggestions
3. A prompt to add a unit number
4. A prompt to edit a unit number

In all of the above cases, a person can edit the address they originally entered or choose to override the warning and save the address they entered as-is. If there is an address suggestion, they can choose that. When they eventually save an address, we will close the form and show the new address in their profile.

Link to the Profile 2.0 Product Guide with documentation: https://docs.google.com/document/d/1XNHpYOP73so_bnnEjplx_zG_ybGarGenG2V0E6-N-CA/edit?ts=5ef38253#

## User Story
As a user, I can verify my address with the US Postal Service if they don't recognize what I input either when I enter my address to my profile OR change my address as part of the letters/documentation flow. 

- [x] High fidelity prototype of screens in iOS
- [ ] Usability test as needed, refine as needed
- [ ] (Ongoing) UI for a range of devices we are supporting

**Comment by bridgethapner** [comment]
Waiting for documentation on this from VSA Auth Experience team

**Comment by bridgethapner** [comment]
I can start UX per the Profile 2.0 Product Guide, but I don't know the backend of how VA.gov checks against USPS. @kreek is it safe to say we can use the same service VA.gov is using to check addresses against USPS and therefore should follow the same UX? I want to make sure our mobile app can access what it needs to on the backend to check addresses against USPS.

**Comment by kreek** [comment]
Good timing I was just looking at this myself 😄 Yes it will be the same service so it can follow the same UX.

**Comment by bridgethapner** [comment]
Thank you Alastair! 

I'm attaching my UX progress here rather than adding it into the prototype. We are tackling this work in frontend and backend in a later sprint and I don't want to add this into the click-thru flow until we get to the point where this work is happening.

![Edit Mailing Address (Not-Recognized-1).png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/d20cbf84-6b84-4e9c-af6b-5a504d9eb41e)

![Edit Mailing Address (Not-Recognized-2).png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/2a5ed56f-fa14-4589-8b69-41c0a510a958)

![Edit Mailing Address (Not-Recognized-3).png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/b45761cb-23e0-4305-ba3d-4ccb69aba014)

![Edit Mailing Address (Not-Recognized-4).png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/5557c48f-a4e3-49e1-97f4-e03de53da84c)

**Comment by bridgethapner** [comment]
@jmarchi @bessgreen Here is the UX/UI for the USPS Address Recognition Flow. What I see in the Product Guide (linked above) is that there are 4 potential suggestion patterns to validate an address. 

Screens in Invision here: 
1. [A prompt to confirm the address, with potential address suggestions](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/437865412)
2. [A prompt to confirm the address, with no suggestions](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/437865413)
3. [A prompt to add a unit number](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/437865415)
4. [A prompt to edit a unit number](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/437865414)
