### ISSUE TITLE
PM and Engineers: Request load testing, privacy, and security intro

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1357]
## User Story 

As a part of the VSP on boarding process, I need participate in a load testing, privacy and security intro session so I can properly be on-boarded to the Benefits and Memorials team. 

## Goal 

Attend load testing, privacy and security intro session for PM and Engineers. 

## Acceptance Criteria 

Load testing, privacy and security intro has been scheduled and completed with VSP team.  

 
## Definition of Done 

- [x] *Has been scheduled and completed *

- [ ] *To be completed in Sprint 3 *

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by SMLuthi** [comment]
Done.

**Comment by YanaRoy** [comment]
Load testing is ready to go but security and privacy aren't yet (should be in the next couple days). Then Peter will schedule with the team.

**Comment by YanaRoy** [comment]
@peterhill-oddball is this something we can work on setting up for the benefits and memorials team? I know there was something we were waiting on, per andrea hewitt, but don't recall what that was and want to get this task completed. Thank you!
