### ISSUE TITLE
[Archived] 10-10 Updates

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#13580]
# Archived - see: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13430 instead

**Comment by ala-yna** [comment]
Leaving the original content here though: ## Issue Description
_Revisions  based on program feedback and 10/1 expansion_

## Intro Page - Front end tasks 

- [ ] **Remove link**
- [ ] **Sentence case:** Social Security number or tax identification number
- [ ] **Update content** from "You will" to "You'll"
- [ ] **Change phone number** to 855-488-8440
- [ ] **Remove** VSO link 
- [ ] **Add content:** "that are marked as required"
- [ ] **Add content:** "If you aren’t eligible for PCAFC you have the right to appeal. You can contact the patient advocate at your local VA medical center to discuss the appeal process. Your Caregiver Support Coordinator is also available if you have additional questions."
- [ ] **Update footer with** phone number 855-488-8440 and content 

![Intro - Addtional info-Annoted](https://user-images.githubusercontent.com/58444931/93257127-0753a780-f762-11ea-9299-f10d89f1d667.png)

## Veteran Personal - Front end tasks 

- [ ] **Remove** "service member" 
- [ ] **Sentence case:** Social Security number or tax identification number
- [ ] **Sex:** No longer required and remove "unknown" 

![Vet Personal - annotated ](https://user-images.githubusercontent.com/58444931/93262044-33265b80-f769-11ea-9ce7-1ea7e9a828e5.png)

## Veteran Medical Center  - Front end tasks 

- [ ] **Update heading** "Recent medical care" 
- [ ] **Bold:** " last received medical treatment"   
- [ ] **Add label** "Name of medical facility"
- [ ]  **Name of medical facility and and hospital/clinic** no longer required
- [ ] **Update heading** "VA health care services" 
- [ ] **Bold:** "receives or plans to receive health care services" 

![Vet Medical Center -annoted ](https://user-images.githubusercontent.com/58444931/93264041-31aa6280-f76c-11ea-9cf7-e130b840a0d3.png)

## Caregiver Personal - Front end tasks 

- [ ] **Update chapter title** "Primary Family Caregiver applicant information" 
- [ ] **Update content** "Family caregivers are approved and designated by VA as Primary Family Caregivers and Secondary Family Caregivers to provide personal care services. A Primary Family Caregiver is the main caregiver for the eligible Veteran."   
- [ ] **Sentence case:** Social Security number or tax identification number - No longer required
- [ ] **Sex:** No longer required and remove "unknown" 

![Caregiver Personal - annoted](https://user-images.githubusercontent.com/58444931/93268475-d891fd00-f772-11ea-8128-75f1d0d4c83b.png)

## Caregiver health coverage - Front end tasks 

- [ ] **Update content** to "Does the Primary Family Caregiver applicant have health care coverage, such as Medicaid, Medicare, CHAMPVA, Tricare, or private insurance?"

![Caregiver health coverage-annoted ](https://user-images.githubusercontent.com/58444931/93269032-d9775e80-f773-11ea-862d-4cd59910bb8e.png)

## Secondary caregiver - Front end tasks 

- [ ] **Update chapter title** "Secondary Family Caregiver applicant information" 
- [ ] Remove intro sentence 
- [ ] **Update content** "Family caregivers are approved and designated by VA as Primary Family Caregivers and Secondary Family Caregivers to provide personal care services. A Secondary Family Caregiver generally serves as a backup to the Primary Family Caregiver."   

![Secondary-annotated](https://user-images.githubusercontent.com/58444931/93271206-5278b500-f778-11ea-9b70-bd9d713edcc7.png)



## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>



---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
