### ISSUE TITLE
Update Sentry 10 Prometheus Scrape Targets

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#13586]
## The Problem
Prometheus does not scrape any metrics for Sentry 10. The current scrape targets are for Sentry 9 and need to be updated.

![image](https://user-images.githubusercontent.com/3077884/93280093-cde95f00-f796-11ea-9dbc-84b841f1787a.png)

## Extra Context
We're currently running Sentry 10 (`sentry10.vfs.va.gov`) in parallel with Sentry 9 (`sentry.vfs.va.gov`) as part of a migration effort from 9 to 10 (https://github.com/department-of-veterans-affairs/va.gov-team/issues/7064). Prometheus has not yet been updated to scrape sentry 10 metrics.

## Work to be Done
- [x] validate Sentry 10 supports the `/metrics` endpoint to serve up prometheus metrics
- [x] validate that the metrics [we currently use in grafana](http://grafana.vfs.va.gov/d/000000092/sentry?orgId=1&from=now-3h&to=now&var-datasource=Prometheus%20(Production)), are still supported in sentry 10 (e.g. `sentry_events_processed_ruby`)
- [x] Update prometheus configs to point to scrape the sentry 10 metrics

**Comment by kfrz** [comment]
Further metrics & logging may be explored, when [migrating to Datadog](https://develop.sentry.dev/services/metrics/)
