### ISSUE TITLE
PM and Engineers: Request ATO intro

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1358]
## User Story 

As a part of the VSP on boarding process, I need participate in an ATO intro session so I can properly be on-boarded to the Benefits and Memorials team. 

## Goal 

Attend ATO intro session for PM and Engineers. 

## Acceptance Criteria 

ATO intro has been scheduled and completed with VSP team.  

 
## Definition of Done 

- [ ] *Has been scheduled and completed *

- [ ] *To be completed in Sprint 3 *

- [ ] *This relates to epic ticket #879 *Check the box below when this has been completed and comment "done".

**Comment by SMLuthi** [comment]
Done.

**Comment by YanaRoy** [comment]
No ATO person currently on VSP team to provide the intro. Closing ticket.
