### ISSUE TITLE
Access for Laura Trager

### ISSUE THREAD

**Issue by ElleeB** [department-of-veterans-affairs/va.gov-team#13581]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Laura Trager
- Please Provide your email.
   > laura.trager@adhocteams.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team DASH/Banana Peels | Backend Engineer | Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABgQCv1b6JArpCY0JYX+zz6jX3QYxa0LRzuJ28bLAPMmnJyLS0xyDqlfU3VumISEQ573jSOPHRYZnU/+Dwz46lHKj+q2XRbuAOqYLsHyF9EoK3XqclecXkEy2sSfIjuqwa8lNL9lrvGcy6xsx1paZXqWmO1fvGVKZfCmSVVOzqi0cXWgaSxN6I9P/jsR/zkqNwOT2e7tAGpMu248qOvpqEUGA+GcFZ+F0oh/ZRVgx7ImW8xEH6VIPiuJ9/qcSD0RCOlEnL4TGqpBr0U2of27Zf9ZYXTbS6PA32FDkN+HXTisCKSPGCSYcXFEnwUspjo/oMTbNRBFdo+X4oqpREJVzPHp1Nw8L/4xDEkAuUIwEnq/bVTFlXN+TF9ZkqM4SOZQL172LoeogcScDefDPR/1lM/6j6T0v1CAQkU/Zrhpg4XpV4vmuSq4olfIROJIkvl4FdjrTyUKjBP6wmvWmCnwRYAvXbZb4EfPKW4FDV8JnDoX6ivyNc8vx/L64Fsj0hUBQQs2k= lauratrager@Laura-Trager-Macbook.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
Developing and maintaining the Lighthouse APIs/Dev Portal

**Comment by pnwstevan** [comment]
Hi @ElleeB! 

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

**Comment by pnwstevan** [comment]
**For AWS Access:**
User: Laura Trager
COR: Cecilia Lee
Approval needed: @Jeff-Hayter

**Comment by emilygoodrich5623** [comment]
@Jeff-Hayter  - pinging for attention. Laura is blocked until she has aws access. Let me know if I can provide any additional information. Thank you. Emily

**Comment by drorva** [comment]
approved

**Comment by jsev-io** [comment]
![image](https://user-images.githubusercontent.com/63133731/94810674-51739480-03c2-11eb-885d-5ecd1ad38b62.png)

Confirmed that eQIPs submitted
cc: @drorva @Jeff-Hayter @department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
User Provided AWS Access Credentials
