### ISSUE TITLE
Facility wait time spinner spins forever

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#13585]
The wait times on this URL never load:
https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

![image (1).png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/9a72341b-ce7d-4f36-b1ee-2e98b8fd753b)

This is because the API calls in production are returning strings for some of the times, and our code expects a Number:

![https___api_va_gov_v0_facilities_va_vha_646.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/4dea3f75-b1b9-4292-ad50-34c427731ff5)

These calls are currently using the v0 facilities API. We should be using v1 instead. The v1 API does not have this issue.

We should also guard against this in the code just to be safe.

**Comment by mmiddaugh** [comment]
@mpelzsherman now I don't see any wait time information: 
![image](https://user-images.githubusercontent.com/55411834/93827558-ba227a80-fc26-11ea-9aee-4985ceb1fb40.png)

**Comment by brangi** [comment]
merged
