### ISSUE TITLE
Add basic PGD endpoints for QuestionnaireResponses and Questionnaires 

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/va.gov-team#13599]
## User Story
**In order** to save time by using the appointment questionnaire feature on the va.gov site in the nearby future
**As a** Veteran
**I want** I want features to be built for me in an incremental manner so that they will be available on the va.gov site sooner than later

## Description
Add basic patient-generated-database(PGD) endpoints for questionnaire and questionnaire responses and have them return a successful status. Establishing the endpoints and have them only return the status will be the initial step in fleshing out this epic.

## Acceptance Criteria
- [x] Create basic and separate endpoints for getting questionnaires and QuestionnaireResponses in the Health Quest module
- [x] The basic endpoints must only return a status of 200

**Comment by massrb** [comment]
I have an initial PR out there but the VSP people have still not approved it for merging into the main branch

**Comment by abuckley3385** [comment]
@massrb  given this is day 1 of the new sprint - I see all the tasks and acceptance are checked does this mean this is already done?  Was thinking this was this way in sprint planning and you were going to update as it was not correct?

**Comment by massrb** [comment]
It was in the backlog and I had moved it out of the backlog. I coded the endpoints and had pull requests but they haven't let me merge it yet so I will uncheck the merged to main part

**Comment by massrb** [comment]
VSP has found many problems with having endpoints that return dummy data so I just pushed up another PR for them to look at that is more typical

**Comment by dillo** [comment]
Removing ambiguity and restructuring AC to reflect what needs to be coded and nothing more.

**Comment by abuckley3385** [comment]
@dillo  can you  please add s user story to this ticket so its clear why we need PGD endpoints for the responses - ie what functionally does that get us.

**Comment by dillo** [comment]
The first PR has been created with a basic endpoint for questionnaires data: https://github.com/department-of-veterans-affairs/vets-api/pull/5047
