### ISSUE TITLE
Understand and develop initial integration against Caseflow Intake API

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1359]
## User Story
As a Veteran, I want to complete my Higher Level Review request online so that I can avoid reiterating information the VA already knows about me on a paper form.  

## Goal
Understand and develop initial integration against Caseflow Intake API

## Acceptance Criteria
  - [x] Figure out if any technical or authentication docs require modification (e.g., ATO)
  - [x] Figure out if any special network connections need to be made

## Definition of Done
- [x] **Technical and/or authentication docs that require modification identified** 
- [x] **Special/additional network connections identified **

**Comment by SMLuthi** [comment]
The lighthouse team responsible for the building and maintaining of the Decision Review API has been in contact with us regarding their work.

Notes for backend work:

- The integration will require a service to be built out in vets-api
- Currently the authentication with their API will be through an api key
    * You can get a development key at https://developer.va.gov/apply
    * We will need to determine whether we can use a preexisting key for this integration or if we will need to generate a new production key for vets-api that it will use.
    * This is a link to their swagger docs: https://raw.githubusercontent.com/department-of-veterans-affairs/caseflow/master/app/controllers/api/docs/v3/decision_reviews.yaml which can be viewed via http://editor.swagger.io/
    * This is a link to their schema file which provides more information on the payload and the variables that are required: https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/schema.rb
    * The current caseflow intake process has a demo website we can use to see the current intake flow and how it works: http://www.caseflowdemo.com/ (user BVAGBLUE works well)
        - Heres a list of dummy file numbers that can be used: https://github.com/department-of-veterans-affairs/caseflow/blob/master/local/vacols/bgs_setup.csv (`872958715` seems to be the most useful as it has a lot of issues)
- The integration will need to be able to make calls to all three of the endpoints they have exposed
- Vets-Api will need new endpoints for these three calls (as it will act as a passthrough from the front end). This means it will need an appeals POST higher review submission endpoint, a GET higher level reviews status intake endpoint (to poll against until we get a processes response), and a GET higher level review endpoint (which retrieves the actual results).

**Comment by tlei123** [comment]
Hi, @SMLuthi !

Re. @Mottie’s  HLR Form Step 1 (#1924), will I be able to QA that form-page on Staging once his PR has been merged?

He has been using test-user 226 on his local, but I need to know if this test-user (or any other) will actually have contact-data prefilled on Staging (where local mocked-data aren't being used).

Please let me know.  Thanks much!

cc @Mottie
