### ISSUE TITLE
Iteration - Cerner/Spokane off-boarding to account for CC flow

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13607]
Current implementation doesn't account for Veterans who are CC eligible and are Cerner-enabled. We need to account for this so users can get CC check + directed to the Cerner portal (My VA Health) within VAOS. Scoped to existing location selection page (not new/latest design). 

### Acceptance criteria:
- Cerner-only patients can start scheduling flow
- If Cerner-only patient is community care eligible
     - patient can selects cc as provider and continue with CC flow
     - If patient selects VA provider, patient taken to location page where Cerner-only site displays but cannot be selected. Instead they must select link or click button 'Go to My VA Health' 
- If Cerner-only patient not CC eligible, they are taken to location selection page where Cerner-only site displays but cannot be selected. Instead they must select link or click button 'Go to My VA Health' 

---
#### **All patients (even cerner-only) see the following option to start scheduling flow:**
![Screen Shot 2020-09-22 at 11.00.51 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/fe922134-3f34-44bb-87b3-2f46302afbd5)

#### **Choose a VA location - for both CC and not CC eligible, cerner-only patients**
![Screen Shot 2020-09-22 at 10.58.22 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/80b3187e-04c6-4674-bd55-1d190e15bed0)

#### **Choose a VA location - for Cerner+other sites, Veterans have same flow as above, but the follow Location screen**
![Screen Shot 2020-09-23 at 10.29.23 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/f55dc762-db55-4235-b79f-2ac541288ec8)

### Cerner-only experience flow:
![566620bb-93a6-4a91-8c07-f527165eb5fa.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/f75ef451-0585-4362-b80d-57edf9e15fdf)

**Comment by peggygannon** [comment]
Hi, @lenaecb 
Question about the first screenshot:

--what is the UX for a Cerner-only patient who wants to make a community care appt? 
Do we need to include messaging on the VA appointment landing page? 

--when would a Cerner-only patient see this screen? wouldn't they be directed to My VA Health right away from the static Schedule page?

Are there other screens in this flow not shown above? 

cc @rtwell

**Comment by lenaecb** [comment]
@peggygannon - Not sure if you saw my slack on this or not, but you can see both of the current experiences via screen recordings [here.](https://dsva.slack.com/archives/CMNQT72LX/p1597687060058100)

Right now there _is not_ a way for a Cerner-only patient to get into the community care flow because we present them with this if they get into VAOS. 
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/bc48dc66-ad6a-40c3-93b2-b68c852714ea)

For VA appt landing page - do you mean in app (screenshot above), or the static appointments page?

The widget on the static page looks like this: (test user is Columbus-only)
![Screen Shot 2020-09-18 at 4.04.08 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/4d5790da-19f1-40f4-ab0f-3eec3f96e798)
-  We should consider whether or not we can to call out 'other VA facility or community care' on the second, inactive button

This is a funky way to handle enabling community care for cerner-only (and also cerner+other sites) experience, but Cerner has no way right now to enable the community care capability which is why we need to iterate on our current experience to allow for cerner-only patients to get enough into the flow to know whether or not they are CC eligible. 

I am going to be adding tracking to this as well so we are getting an idea of how many people are getting into this state so we can understand potential impact.

**Comment by peggygannon** [comment]
@lenaecb ok, thank you clarifying. I just recommend one minor tweak to put VA in the header part. 

**Need to schedule a VA appointment?**
You can schedule an appointment through My VA Health. 

{cta button} Go to My VA Health

**Comment by peggygannon** [comment]
Hi, @lenaecb based on our content sync today, it sounds like we aren't making CC any content/UI updates to the VA appointments tool landing page for Cerner-only users. 

Is this issue no longer needed, then?

**Comment by lenaecb** [comment]
@peggygannon - we are going to break this up into a few tickets for implementation. At the moment we think there will be only one ticket that needs content/design input, but I need to understand how that use case happens more before I can create that ticket. So more to come.
