### ISSUE TITLE
[Pre-release] Make validate-content-builds.js script pass

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#13604]
After recently updating the `content-build` repo with the latest changes from `vets-website`, the [`validate-content-builds.js` script](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/validate-content-builds.js) was still failing. We need to figure out why the builds don't match, and fix it.

**Comment by meganhkelley** [comment]
Note 11/12 — content build repo has not been updated in a while; this needs to happen before this ticket can be completed.

**Comment by timwright12** [comment]
PR to get this into the pipeline https://github.com/department-of-veterans-affairs/content-build/pull/50

**Comment by timwright12** [comment]
The command to validate the content build repo against the vets-website build is complete and passing.

The command to run this is: `yarn build:validate`

A failure on the script does not mean the build is incorrect, it likely means that vets-website has made updates that have not been moved into content-build yet.

PR: https://github.com/department-of-veterans-affairs/content-build/pull/50
