### ISSUE TITLE
Measure the baseline for how many VFS teams have started E2E testing suites for their products

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#13608]
As a QA specialist on VSP, I want a way to measure what VFS teams are utilizing E2E tests so that I can know what teams are meeting VA.gov standards. 

AC:
- [x] We have a baseline metric for what teams are creating E2E tests
- [x] We have a process for continuing to measure 
- [x] We have shared the process with leadership so they can check the metrics whenevery they want

**Comment by pjhill** [comment]
- FE Tools does not currently track coverage / use of Cypress by VFS teams.
- FE Tools / Michael Fleet generally agree that mapping Cypress tests to test cases in TestRail is a worthwhile effort.
- FE Tools has no plans to track "coverage" or any similar concept

**Comment by pjhill** [comment]
I've compiled a [spreadsheet ](https://docs.google.com/spreadsheets/d/1mq9of8Yi_8tfDObui4vi16Zi7oV7h95x2Bg2HLyRwbY/edit?usp=sharing)of "products" based on folder structure within vets-website. I've included a subjective assessment of the test depth for the automation that is available.

**Comment by pjhill** [comment]
Without the creation of a custom tool to scan the repository for the presence of Cypress or Selenium files it will be difficult to automate this process. I'm not aware of any tools that can perform this function out of the box.  That said, VFS teams need to follow a specific folder structure and naming convention. Currently, we locate relevant Cypress files with the following regex -- 
`**/tests/**/*.cypress.spec.js?(x)`
