### ISSUE TITLE
DECISION- Edit demographics workfow or leave read only for MVP

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#13623]
[See workflow diagram ](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780/screen/5f60eb5d5c8d82a8df727cbd)for determining if bounce tabs, modal, or navigate in line is acceptable or no ability to have an edit of demographics once in the questionnaire workflow.

**Comment by abuckley3385** [comment]
moving to icebox as editing for MVP is not needed.

**Comment by kristenmcconnell** [comment]
Demographic information and its editing capabilities are being addressed as part of the check-in experience (particularly the pre-check in workflow). The new experience can be view at: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/ZOdgYzp/play
