### ISSUE TITLE
Prioritize design features for Higher-Level Review Pilot MVP

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1362]
## User Story
As a Veteran, I want to be able to submit a request for a Higher Level Review as soon as possible so that I can cut down on my time waiting for a decision. 

## Goal
Walk through existing designs with Carola and team to determine which features are pilot-necessary and which could wait until a second version

## Acceptance Criteria
  - [x] Review existing designs
  - [x] Participate in Veteran focus groups to collect design feedback
  - [x] Prioritize design features 
  - [x] Create list of design features for a successful MVP release

## Definition of Done
- [x] **List of MVP design features identified and prioritized**

**Comment by smoonpeyes** [comment]
Adding this to GH (and then will post a link and close):

## High-Level Review MVP Design and Research Priorities

- Claim Status Tool Research (#1754, #1755): This research will include findings that determine the information architecture for the Higher-Level Review pages.

- Identify points of entry to access Decision Review pages (#1913)

- [design] Regional Office selection (#1915)

- [design] HLR (Step 1) Review Contact Information pattern (#1917)

- [design + content] Define signed-in/out states of the `File a Higher Level Review` page (#2011)

- [research + design] Optional Notes Character Limit (#1919)

- [design] Time period rules (#1920)

- [design] Design `Eligibility` page for the HLR application (#2026)

- [design] Design `How to Apply` page for the HLR application (#2027)

- [design] Design `After You Apply` page for the HLR application (#2028)

- [research] Conduct research sessions on HLR MVP application with Veterans to determine usability issues before launching MVP **(no ticket)**


## Additional design work **not required** for MVP

- [design] Scale display of larger number of disabilities (#1918)

**Comment by smoonpeyes** [comment]
@kevinstachura feel free to update the list as you see fit, and then close this ticket. Moving to `Validate`.

**Comment by YanaRoy** [comment]
@kevinstachura is this ticket ready to close?

**Comment by kevinstachura** [comment]
I think we can close this, yes!
