### ISSUE TITLE
DECISION - Review Page - What to bring and Who to contact 

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#13624]
Determine strategy for Q4 MVP if we want to show Review page what to bring and who to contact sections being static or dynamic based on the appt. type/questionnaire. 

An example of a what to bring list: https://www.veteranshealthlibrary.va.gov/142,40992_VA.

Task
- [x] Talk to Ryan Thurwell on VAOS about new appointment details designs
- [x] Add in link to secure messaging, so a patient can send an image to their provider if they want. Say something like "we will work on this feature, but go here for now."

**Comment by kristenmcconnell** [comment]
@abuckley Based upon research findings, I'm proposing that we add contact information (phone numbers), but link to VAOS for additional appointment details. I propose that we do not add a "What to bring" section.

**Comment by kristenmcconnell** [comment]
Moving to closed, since I already reviewed the wireframes with you, @abuckley3385.
