### ISSUE TITLE
[Bug] Redirect logout issue 

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#13625]
## Steps to reproduce

Browser: Chrome
User: Samara.Strauss@va.gov
Environment: Production

1. Turn on Profile 2.0 for your prod account via https://api.va.gov/flipper/features/profile_show_profile_2.0.
2. Log in to VA.gov in prod.
3. In the URL bar, go to /account. This link no longer exists with the new profile turned on, but it should redirect to /profile/account-security. Instead, it logs you out, and you have to log in before it redirects you.

What should happen: When I go to /account, it should redirect me to /profile/account-security without logging me out in the process.

Also of note: I tested to make sure this isn't happening with all redirects. It's not. When I tested redirect links for other features that were currently live and not activated by Flipper, I was not logged out as part of the redirect.

Other links I tried (these all redirect to VA.gov even though they are not VA.gov links themselves):

www.benefits.va.gov/compensation/types-disability.asp
https://www.vets.gov/signin/  (should just go to home page)
www.benefits.va.gov/gibill/comparison_tool.asp
www.vets.gov/dashboard/
www.vets.gov/download-va-letters/letters/

## Tasks

- [ ] Investigate why logout is happening when using a redirect link for a feature that is activated via Flipper.
- [ ] If possible, fix this so redirects for Flipper features don't cause someone to be logged out.

**Comment by erikphansen** [comment]
@Samara-Strauss which browser were you using?

**Comment by Samara-Strauss** [comment]
I was in Chrome Version 85.0.4183.102

**Comment by Samara-Strauss** [comment]
[Update from Eric Buckley in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1600288388360600?thread_ts=1600268451.328300&cid=C909ZG2BB): 

> I ran a few tests and from what I can see it doesn’t appear to be related to SSOe.  I believe there might be an issue with rendering the RequiredLoginComponent and redirecting to the /profile/account-security/ page at the same time, but I haven’t been able to conclusively show that

**Comment by erikphansen** [comment]
@Samara-Strauss a fix for this has been merged. Please validate it when you have some time.

I created [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13720) to fix the _real_ problem that you uncovered.

**Comment by Samara-Strauss** [comment]
Looks good to me! No longer getting logged out on this redirect.
