### ISSUE TITLE
School Ratings: Add composite rating to institution

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13620]
As a comparison tool user, I need to see how other veterans have rated institutions while searching for an institution that I am interested in attending so that I can make an informed decision about which institutions to investigate further when deciding where to use my benefits.

## Assumptions
1. This work is completed behind feature flag `gibct_school_ratings` created in #13359.

## Acceptance Criteria
1. On the institution card on the search results page:
    a. If an institution does not have any ratings the following is displayed:

       > School rating:
       > Not yet rated

    b. If an institution has ratings:

       > Rated by: NN Veterans 
       >  ***** (4.8 of 5) { star rating visual with numerical display }

3. The star rating visual fills in the number of stars based on the composite average rating.
    a. The composite average rating is the sum of the ratings for the institution divided by the (number of ratings - N/A ratings) rounded to a single decimal place.
    b. The number of stars filled is the whole number of the average
    c. If the decimal of the average is < .3, the next star is empty
    d. If the decimal of the average is >= .3 & <= .7, the next star is half full.
    e. If the decimal of the average is > .7, the next star is full

5. The following rating information is displayed in the profile header: `***** | 5.0 of 5 (See XX ratings by Veterans)`
    a. If there are no caution flags, the information is displayed below the school name and before the number of GI Bill students.
    b. If there are caution flags, the information is displayed below the caution flags and before the number of GI Bill students.
    c. If an institution does not have ratings, no rating information is shown in the header.

6. The card matches the layout and structure as specified:
    a. In Supporting Artifact # 1 when viewed on a desktop device
    b. In Supporting Artifact # 2 when viewed on a mobile device
    c. The “You may be eligible for up to” card label IS NOT replaced with "Estimated benefits:" as seen in the prototype.
    d. The institution name continues to link to the profile page (unlike as seen in the prototype)

### Technical Notes
institution search result response fields:
  rating_count - int
  rating_average - float

institution profile response fields:
  rating_count - int
  rating_average - float

  rated_categories - array of:
    category_name - string
    average_rating - float
    rated5_count - int 
    rated4_count - int 
    rated3_count - int 
    rated2_count - int 
    rated1_count - int
    na_count - int

## Supporting Artifacts:
As of 09/16:
1. [Prototype - GIBCT School Ratings v0.5 - Desktop](https://bahdigital.invisionapp.com/share/HQIAEWSBGFU#/screens/296049136)
2. [Prototype - GIBCT School Ratings v0.5 - Mobile](https://bahdigital.invisionapp.com/share/NCIAEWUAYDS#/screens/296049161)
3. [Content-doc-v0.5.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/eea8b38d5d9fd91ee5ab70399e7f9b6281b29231/products/education-careers/school-comparison-tool/school-ratings/design/content-doc-v0.5.md)

**Comment by dmccurdybah** [comment]
PR to add the `gibct_school_ratings` feature flag back in: https://github.com/department-of-veterans-affairs/vets-api/pull/4990

**Comment by dmccurdybah** [comment]
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14436
gibct-data-service PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/734

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-02 at 1.15.32 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/55858bfd-145d-4c20-9628-5aef3f882d3a)
##
![Screen Shot 2020-10-02 at 1.15.58 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/528cc75a-d823-4913-9397-5b7d1d5bb9cb)
##
![Screen Shot 2020-10-02 at 1.18.15 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d86bf4f3-ca3d-495d-8fe0-49b51b2aa442)
##
![Screen Shot 2020-10-02 at 1.18.26 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/becd1b3b-3a64-4885-8730-02b2d601a7ff)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-02 at 2.08.01 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b3ad69b9-16de-4342-860f-f9cbf99b6fa5)

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-10-02 at 3.21.38 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/7df22de0-2ff3-4b09-a556-9b93627545f7)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/12770&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by dmccurdybah** [comment]
Mobile styling PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14505

**Comment by JenLJ** [comment]
@sonntag-adam UX has reviewed and this checks out!

**Comment by sonntag-adam** [comment]
Closing story
