### ISSUE TITLE
School Ratings: Add school ratings accordion to school profile

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13635]
As a comparison tool user, I need to see how other veterans have rated a school while viewing a school profile that I am interested in attending so that I can make an informed decision about where to pursue my education and use my benefits.

## Assumptions
1. This work is completed behind feature flag `gibct_school_ratings` created in #13359.

## Acceptance Criteria
1. The "School ratings" accordion:
    a. Is not displayed when the school has no ratings.
    b. Is displayed between the "Cautionary information" and "Contact details" accordions when the school has ratings.

2. The header of the content contained within the accordion is: `XX Veterans rated this institution:`

3. The following composite average rating content is displayed following the header:

    > N.N 
    > out of a possible 5 stars 
    > { star rating visual }

4. The collected ratings are separated into the following groups:
    a. Education ratings
    b. Veteran friendliness

5. The following rating categories are a part of the "Education ratings" group in the following order:
    a. Overall experience
    b. Quality of classes
    c. Online instruction
    d. Job preparation

6. The following rating categories are a part of the "Veteran friendliness" group in the following order:
    a. GI Bill support
    b. Veteran community
    c. True to expectations

7. Each rating category:
    a. Is expandable / collapsible.
    b. Only one rating category per group (Education ratings, Veteran friendliness) can be expanded at a time _(note that this is not reflected in the prototype)_.
    c. If there are ratings, displays: `{ star rating visual } X.X`
    d. If there are not ratings, displays: `Not yet rated`

8. Each rating category displays the following information when expanded:
    a. Distribution of ratings
    b. 5 star { bar visual } NN% (NN users)
    c. 4 star { bar visual } NN% (NN users)
    d. 3 star { bar visual } NN% (NN users)
    e. 2 star { bar visual } NN% (NN users)
    f. 1 star { bar visual } NN% (NN users)
    g. NN users didn’t rate this category {If all users provided a rating, don't display this}
    h. Description of category (as outlined in SA3)

9. Each star rating visual fills in the number of stars based on the composite average rating.
    a. The composite average rating is the sum of the ratings for the institution divided by the (number of ratings - number of 
 N/A ratings).
    b. The number of stars filled is the whole number of the average
    c. If the decimal of the average is < .3, the next star is empty
    d. If the decimal of the average is >= .3 & <= .7, the next star is half full.
    e. If the decimal of the average is > .7, the next star is full

10. The following content is displayed in the "School ratings" accordion:

    > ### About ratings 
    > 
    > We ask Veterans who have used their education benefits to rate schools they’ve attended on a scale of 1 to 5 stars, with 5 stars being the best rating. 
    > 
    > #### How ratings are collected
    > 
    > VA works independently to collect ratings from Veterans. We reach out to Veterans to provide a rating who have:
    > - Received a Certificate of Eligibility (COE) for benefits
    > - Transferred into or out of a school 
    > - Made a change to their program of study, **or**
    > - Completed their degree program 
    > 
    > Veterans rate schools on a number of categories. Those ratings are averaged to calculate the overall school rating. If a Veteran doesn’t rate a category, it has no effect on the category’s overall score. 
    > 
    > #### Veteran privacy
    > 
    > A school may ask us for a list of Veterans who rated their school, but we do not share individual ratings with schools. If an institution asks us for information on who rated their school, no information beyond what is publicly available on the Comparison Tool is shared with them that would tie an individual to their ratings.

11. "(See XX ratings by Veterans)" in the header is a link to the "School ratings" accordion further down the profile page

12. The page matches the layout and structure as specified:
    a. In Supporting Artifact # 1 when viewed on a desktop device
    b. In Supporting Artifact # 2 when viewed on a mobile device

## Supporting Artifacts:
As of 09/16:
1. [Prototype - GIBCT School Ratings v0.5 - Desktop](https://bahdigital.invisionapp.com/share/HQIAEWSBGFU#/screens/296049140)
2. [Prototype - GIBCT School Ratings v0.5 - Mobile](https://bahdigital.invisionapp.com/share/NCIAEWUAYDS)
3. [Content-doc-v0.5.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/eea8b38d5d9fd91ee5ab70399e7f9b6281b29231/products/education-careers/school-comparison-tool/school-ratings/design/content-doc-v0.5.md)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/14530
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/736

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-14 at 8.33.11 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/59d3ede4-dd01-46b0-aa4e-a1504b080eba)
##
![Screen Shot 2020-10-14 at 8.33.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cbb5726d-a628-4719-b2a1-076141e432f2)
##
![Screen Shot 2020-10-14 at 8.33.25 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c123ece9-0750-40e5-85ff-648bcea04f5e)
##
![Screen Shot 2020-10-14 at 8.33.37 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/92272983-9790-4215-aff8-9e46d761b0e5)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging ready for review

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/12971&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me

**Comment by amyknox** [comment]
UX Review 2/2: 

AC 7b needs a recheck.  On my PC and iphone, I can only open 1 single accordion at a time - not 1 from each group as the AC specifies.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14638

**Comment by sonntag-adam** [comment]
@amyknox @JenLJ updates are in

**Comment by amyknox** [comment]
Looks great - very exciting!

**Comment by sonntag-adam** [comment]
Closing story.
