### ISSUE TITLE
Logo and Name of App

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13633]
- [ ] How do we want to approach this?

- [ ] Who needs sign off?

**Comment by steve-gov** [comment]
One thought: This should tie in with the "branding" of the logged-in experience at VA.gov which is currently "My VA".

**Comment by rtwell** [comment]
+1! the content is almost identical: both surface claims, disabilty, and appointments. My VA on va.gov (at least, at first) will be view only and direct folks to the page where they are able to take action. They are quite similar. I would think we don't want them to be clones of each other, but they could certainly echo each other, e.g. If a user sees an appointment card on the app, then again on My VA, and again on VAOS, I would expect to see very similar content, from both a data perspective and visual design perspective.

**Comment by srmyers17** [comment]
- @bridgethapner made new miro board and started to bucket the 3 different design exploration options
- Sophie and Bridget to discuss next steps today

**Comment by srmyers17** [comment]
- Outcome from first workshop: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1602620677692/7f0746f14fc64c5b236be8815f3330fbba7892b4
- Second workshop scheduled for 11/13

**Comment by bridgethapner** [comment]
**Next steps here per Friday 11/13 work session:** 

- [ ] For now, we will use the name 'VA Mobile App'
- [ ] Bridget to design Android and iOS icons for simple VA mark on darker-primary background (timeline: will have something share early December)
- [ ] Think about some kind of 'concept testing' for usability testing (e.g. asking participants what they think of the mark, what they think the app should be called, etc).

**Comment by bridgethapner** [comment]
- Bridget & Patrick to work together to see how it fits on devices
- Name - VA Mobile?  VA Mobile app? 
- Final sign off from DEPO

**Comment by bridgethapner** [comment]
- Branding as internal release?

**Comment by bridgethapner** [comment]
@lexicalninja To test out what the icon looks like in the app builds, I've exported a PNG of a basic square icon w no radius. Will this work as a placeholder to test the design? Let me know if need different sizes. 

![placeholder-mobile-app-icon.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/643a7adf-6f14-4ff7-b042-d4acada5b896)

**Comment by bridgethapner** [comment]
Hi there @lexicalninja -- Attached is an svg for Android!

![logo-svg.svg](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/2a85bd11-7397-4c1b-a7e1-d7024bd7db64)

Here is the copy we want for the App Center distribution as our title for the time being: "VA Mobile"

**Comment by bridgethapner** [comment]
@lexicalninja & I are working together on a naming convention for our App Center releases that clarify the release date & purpose so we can keep track of each release. I'm going to move this ticket (which we created for app store publishing) to post-MVP Backlog so we can revisit it & access all the comments above when we're ready to finalize the app store release. For now, we'll work on specifics for App Center distribution in other tickets. cc @ayushchak

**Comment by lexicalninja** [comment]
@bridgethapner Can you send a different svg over?

For some reason this svg is just an xml file with an embedded png and not an actual svg drawing of the logo

**Comment by ayushchak** [comment]
Discussion with Steve:
- Short answer, branding etc. is okay
- Will have to create more collateral and metadata to support the launch, but inherent name and description are okay.

**Comment by bridgethapner** [comment]
Closing this since we have decided on name/branding for MVP launch (see above comment). If we need to do anything for launch we can open a new ticket in the Launch Activities epic.

**Comment by ambikaroos** [comment]
Branding discussion Mural - https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1603483458583/8946ac65f0a17a4f150e4b351369a12224192981
