### ISSUE TITLE
Description of Letter

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13630]
## User Story

As a user, once I have selected a letter to view, I go to a new screen where I can see:
- A description of the letter or document
- An alert from VA informing me about changes to how this letter and document can be used, if one exists

**Comment by srmyers17** [comment]
- Need to determine where the letter descriptions come from

**Comment by jperk51** [comment]
For MVP, we decided to follow .gov and hard code this info in the app so I believe this could be pulled out as something we would do post-MVP

**Comment by bridgethapner** [comment]
@bessgreen For MVP, we'll hardcode letter titles & descriptions. 

I've pulled titles & descriptions from a couple of places in vets-api and put it here: 
https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit#gid=2126117638

@srmyers17 A couple of notes FYSA: 
- For MVP we'll display letter descriptions for everything besides the 1 letter that requires user selections (Benefit Summary and Service Verification Letter). There are 2 other letters that have help phones/websites associated with them that we can add in post-MVP. I'll make a ticket for that. 
- I can't find any documentation on 'certificate_of_eligibility' in vets-api & we can't get reliable access to letters in staging so not sure we'd be able to tack any answers quickly. I think we should exclude this letter for MVP (noted this in the content spreadsheet).
