### ISSUE TITLE
The Platform Newsletter: September

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#13648]
### What is your documentation request, question, comment, or issue?
Requesting content review of the September newsletter.

Link to draft newsletter: [https://us19.admin.mailchimp.com/campaigns/wizard/neapolitan?id=4524892](https://us19.admin.mailchimp.com/campaigns/wizard/neapolitan?id=4524892)

Target release date for newsletter: week of 9/21

**Comment by gmaciolek** [comment]
Thanks, @jchasia-adhoc! @amygoldman I'll take a look at this tomorrow morning to double-check the linking URLs and flag anything to pay special attention to. Can you give it a final editorial review by the end of the day on Monday?

**Comment by amygoldman** [comment]
@gmaciolek no problem!
