### ISSUE TITLE
Access for Nicole Houston

### ISSUE THREAD

**Issue by nwalker-va** [department-of-veterans-affairs/va.gov-team#13645]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Nicole Houston
- Please Provide your email.
   > nicole.houston@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Quokka | Role: Fullstack Engineer | Company: Oddball

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFfQ83w5oKJzmbiErt7fh899IZbXuPPhLcgUsVottLvYB1aR6TnO6OUfdP+2M8wibB1v37eU2SAlMRR2kGhe3Lk4N5jrkq1zfD2oUF+X6c+lP2Z5VlnpvtEBU6WQHv6Q+5P3erkdUA72PJfuCoZwtZdSXN2IaBBS9CWDD8rrP/xfIsKJhM0OQzC3Qk2QNxOO6RZQ3oL1xQUOxi0nGNtEmzDEKtVBqHnVV+ypCi/EZKWN1hfdHcDMCJxGDpnsTU1dGjhnApG7ERCoyKSGHWqNPjx+df5Hd5GEa4ACd4pXpxLVFYJFYtq6OhXor/eKQDADUow7TYLkK2RYkX/vRhojMlQgABdaFrOFdvovFbCQ2sBosqgNUd8Its6qlaugN4qTpgplb0gYTjQdg5FzJDzp5+ttWaPdQ6BfhFeePxOGz+7nRRXpHiblujpJQrTJo4vlgOBtH0NyASaLCX14ozeicCoGkMjvcuJrnhB+by485su4inLwV0McD0zhp/q2rW138= nicole.houston@oddball.io
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
Need AWS Console access for developing and maintaining the Lighthouse dev portal.

**Comment by nwalker-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by pnwstevan** [comment]
Hi @nwalker-va! 

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

**Comment by pnwstevan** [comment]
**For AWS Access:**
User: Nicole Houston / @nwalker-va 
COR: Cecilia Lee
Approval needed: @Jeff-Hayter

**Comment by nwalker-va** [comment]
@pnwstevan Thanks so much!

**Comment by nwalker-va** [comment]
@pnwstevan @Jeff-Hayter Just curious if I have been granted AWS access or not. Is there anything I need to do? Thanks for the help!

**Comment by Jeff-Hayter** [comment]
@pnwstevan Approved for AWS access.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
