### ISSUE TITLE
CT: School locations showing incorrectly on mobile view

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#13653]
### Steps to reproduce:
1. Navigate to https://www.va.gov/gi-bill-comparison-tool/profile/11802405
2. Scroll down to school locations
3. Switch to mobile view

Observe how it looks in the mobile view, this occurs for iPhone, galaxy, pixel, etc. Multiple formats.
##
![Screen Shot 2020-09-16 at 3.32.59 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a6bea2ea-0df0-4293-8f9e-31b28531b297)
##
### Expected results:
This is how the mobile should look
![Screen Shot 2020-09-16 at 3.37.58 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9bdcc4fe-719a-445c-b998-5d24366f5e37)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14288

**Comment by zurbergram** [comment]
Should resolve https://github.com/department-of-veterans-affairs/va.gov-team/issues/11055#issuecomment-693546987

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-18 at 8.55.38 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e7aa591a-0c5d-4330-8693-b2a54e877473)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by amyknox** [comment]
Mission accomplished.

**Comment by sonntag-adam** [comment]
Closing story
