### ISSUE TITLE
[Metrics] 526: follow-up on form526 secondary issue validation discovered in UAT

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13657]
## Issue Description
We found an issue with PTSD that was fixed as part of #13849. This ticket is intended to keep track of the logs to make sure we are no longer seeing the issue.

## Acceptance Criteria
- [x] validate that issue was fixed - Is [this](http://sentry.vfs.va.gov/vets-gov/website-production/issues/12188/events/d6327093514b4d508b32429cb10c17ae/) or [this](http://sentry.vfs.va.gov/vets-gov/website-production/issues/12188/events/686c28acac304f72811fb3b05bbcc172/) an instance of the issue? 

Follow up is in this issue: #13852

https://github.com/department-of-veterans-affairs/vets-website/pull/14189 was merged/deployed on 9/16

**Comment by annaswims** [comment]
![Screen Shot 2020-09-24 at 5.34.39 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/9760058b-62e2-4814-a19e-b6d6be2c730b)

The errors dropped significantly after the fix went in, but it looks like we still have some other validation errors that are in the same region. I've sent some examples to @mottie on keybase.

**Comment by luke-gcio** [comment]
Luke will review and close out.

**Comment by annaswims** [comment]
I think a FE engineer should review http://sentry10.vfs.va.gov/organizations/vsp/issues/241/events/?query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdisability%2Ffile-disability-claim-form-21-526ez%2Freview-and-submit&statsPeriod=14d

**Comment by annaswims** [comment]
I created https://github.com/department-of-veterans-affairs/va.gov-team/issues/19860 to follow up on additiona validation errors, but we no longer see the PTSD validation error
