### ISSUE TITLE
[Bug] Claim status tool - error when file extension doesn't match contents

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13664]
Sometimes a veteran uploads a file that has an incorrect file extension, like a .tiff called `image.jpg` or a jpg called `whatever.png`.

When this happens we accept the file and EVSS rejects it. 

We already have code that converts tiff's to jpg and we could likely use that same code to convert any file that has mismatched file type and contents.  
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/uploaders/evss_claim_document_uploader.rb#L11

specific file examples are in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10427

## Expected Behavior
Let the user know _before_  they get to the submission that their file type/extension does not match.  By let them know, don't let them proceed past without an error message.

## Acceptance Criteria
- [x] the CST file uploading endpoint, and the regular form 526 file upload endpoint, ensures that file extension matches mime type (determined by analyzing the binary), and attempts to fix the file extension (and returns an error if it can't or if the new fixed extension is an unallowed one).

**Comment by luke-gcio** [comment]
Do we think we should talk to EVSS about this first to see if they can open up more file types?  Perhaps it is a limitation of the downstream system but I imagine any image type that opens in a web browser _should_ work.

**Comment by annaswims** [comment]
This problem is that the file type doesn't match the file extension, not that the file type isn't allowed. Which now makes it clear that it'd be easier for us to just make the file extension match.

**Comment by edmangimelli** [comment]
digging into this one

**Comment by edmangimelli** [comment]
Worked with Anna to nail down an acceptance criteria for this one. Working on PR

**Comment by edmangimelli** [comment]
> ... down quite the rabbit hole yesterday into today. I have a fix but I have a small refactor PR that will have to go through first (we’re currently doing some somewhat funky things with our uploader gem). going to test both PRs this evening.

https://dsva.slack.com/archives/C5AGLBNRK/p1613516073133400

**Comment by edmangimelli** [comment]
PR 1/2
https://github.com/department-of-veterans-affairs/vets-api/pull/5958

**Comment by annaswims** [comment]
If you'd like to see examples for validation take a confirmationCode 
 from here http://sentry.vfs.va.gov/organizations/vsp/issues/441/events/97f4764633314c758840d0c917beb4ad/?project=3&query=transaction%3ASidekiq%2FEVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitUploads&statsPeriod=14d 
and search for it in s3
https://console.amazonaws-us-gov.com/s3/buckets/dsva-vetsgov-prod-evss?region=us-gov-west-1&prefix=disability_compensation_supporting_form/&showversions=false

**Comment by edmangimelli** [comment]
still waiting on a VSP review of https://github.com/department-of-veterans-affairs/vets-api/pull/5991

**Comment by annaswims** [comment]
An example of a TIFF named jpg

http://sentry.vfs.va.gov/organizations/vsp/issues/452/events/c1aa0b45c41340e399fc3df91ae24526/?environment=production&project=3&statsPeriod=14d

https://console.amazonaws-us-gov.com/s3/object/dsva-vetsgov-prod-evss?region=us-gov-west-1&prefix=evss_claim_documents/132948bbf8fa423398e0e6419c09a4cc/157508120/34dbcd56-5410-4b9f-a7a9-0df98ec2ad8a/Alvarado_dd_214_1.jpeg
