### ISSUE TITLE
526 All Claims - design updates from stakeholder feedback

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1366]
@djmunoz1 commented on [Tue Oct 30 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14706)

### Homelessness Questions
Flash questions for homelessness -- consider moving to the beginning of the flow

### Add a new contention
use list of 125 and allow them to append

### Headers
Header is oversize, steps are more important
![Screen Shot 2018-10-30 at 10.24.21 AM.png](https://images.zenhubusercontent.com/5a008bb78a75884b90863d96/3403baf2-a7b4-4f30-b821-539fdea2efc0)

**Comment by smoonpeyes** [comment]
@YanaRoy Here's some background information that I learned from Dawn:

* This ticket was used to capture stakeholder requests. The idea was to just capture the feedback and hold it for later prioritization. We should discuss with @AZSchneider to determine if any of the items called out in this ticket are current priorities. 

* Each item in this ticket should probably be a separate ticket with its own user story and acceptance criteria.

* The homelessness questions are now included the 526 application in step 4, so this item may have been previously addressed.

**Comment by AZSchneider** [comment]
@smoonpeyes I agree that we can close this ticket but we need a separate ticket to be opened for the **Add a New Contention** list. We need to revisit which list of contentions we should be using and if we should switch to the list of 125. @YanaRoy can you open a new ticket for this?

**Comment by YanaRoy** [comment]
Closing. See ticket #1638 for Add a new contention
