### ISSUE TITLE
RTL tests fail with imported `screen`

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#13678]
React Testing Library unit test is failing when run through unit test script.

PR with failing test: https://github.com/department-of-veterans-affairs/vets-website/pull/13395
https://app.circleci.com/pipelines/github/department-of-veterans-affairs/vets-website/13499/workflows/a218c8aa-74f3-4290-9f3a-ce251cb35df8/jobs/100921

Fails with test script: 
`yarn run test:unit --path src/applications/coronavirus-screener/components/FormResult.unit.spec.jsx`

Passes with manual command:
`BABEL_ENV=test ./node_modules/.bin/mocha --opts src/platform/testing/unit/mocha.opts --recursive 'src/applications/**/FormResult.unit.spec.js?(x)'`

Error seems to be related by something in `src/platform/testing/unit/helper.js` which is included in `script/run-unit-test.js` mocha opts?

Slack thread: https://dsva.slack.com/archives/CQH357ZTP/p1600112131477600
Debugging PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14215

.cc @Clark-W-Griswold @billfienberg @U-DON

**Comment by mchelen-gov** [comment]
nonworking code:
```js
    import { render, screen } from '@testing-library/react';
    render(<App />);
    screen.getByText('Hello React');
```

workaround:
```js
    import { render } from '@testing-library/react';
    const screen = render(<App />);
    screen.getByText('Hello React');
```

**Comment by laineymajor** [comment]
@timwright12 please review

**Comment by timwright12** [comment]
Going to close this out, as it's pretty old and the branch was archived. However, looking into it if seems to be rooting in us not using Jest with RTL (which the doc assume), but instead using Mocha. So with that, the test syntax would change a little:

**Error from the console reading:**
> TypeError: For queries bound to document.body a global document has to be available... Learn more: https://testing-library.com/s/screen-global-error

When using Jest, JSdom will be packaged by default, but we use Mocha. Mocha is configured to use JSDom, but it isn't being imported into the example listed here. With bringing Mocha in we would write this test something like:

```
describe('App', () => {
  it('should render component', () => {
    expect( render( <App /> ).findByText( 'Hello React' ) ).to.exist;
  });
});
```
