### ISSUE TITLE
"Related links" area not rendering on Pittsburgh detail pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13688]
## What happened?
`Related links` area is missing from required health services detail pages on https://www.va.gov/pittsburgh-health-care/, such as [suicide prevention](https://www.va.gov/pittsburgh-health-care/suicide-prevention/) and [LGBT](https://www.va.gov/pittsburgh-health-care/lgbt-veteran-care/) 

<details> 
<summary> Suicide prevention example </summary>

![image](https://user-images.githubusercontent.com/55411834/93512342-6b50aa00-f8e1-11ea-994f-97f3d4685dd6.png)

</details> 

<details> 
<summary> The content is present in Drupal prod but does not render on the front end. </summary>

![image (54)](https://user-images.githubusercontent.com/55411834/93526627-f2f3e400-f8f4-11ea-8649-fa1c2a71e142.png)

</details> 

## Acceptance Criteria
- [ ] When Drupal/CMS prod instance contains `Related links` area for a given detail page, the area should render in the UI on the appropriate page. 
- [ ] The `Related links` area contains the appropriate/relevant resources for a given page . 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by kevwalsh** [comment]
This is a CMS defect, marked critical, hopefully fixing in today's deploy https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2945

**Comment by mmiddaugh** [comment]
Resolved by cms team in [department-of-veterans-affairs/va.gov-cms#2945](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2945)
