### ISSUE TITLE
Settings: Share the app

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#13696]
## User Story
- [x] As a user, I can select "Share the app", and it will open my messaging app with a link to download the app and preloaded text. 

## Documentation
- This is accessible within **Profile > Settings**. 
- When a user hits 'Share the app' it should open their default messaging app to pre-populated tex:
 
"Download the VA mobile app on the App Store: [link to app store] or on Google Play: [link to Google Play]". 

- For MVP, we'll offer both iOS & Android links in the default message. In the future, we can add in OS detection.

**Comment by bridgethapner** [comment]
Will we need to include links to both the Play Store & App Store? Seems like it since we won't know what device the recipient has.

**Comment by bridgethapner** [comment]
Per 12/7 stand up, we want to use the phone's share sheet instead of the SMS app since those are a similar level of effort / the share sheet is recommended by Patrick. @lexicalninja @bessgreen Do we need more definition of the requirement past deciding to use the share sheet?

**Comment by bessgreen** [comment]
@bridgethapner we should be good to go!
