### ISSUE TITLE
Meet with Matt Self and Andrea Schneider about past form implementations on VA.gov

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#1369]
@cohnjesse commented on [Mon Aug 26 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19566)

In order to better assess the possibilities/ pitfalls/ opportunities with the caregiver project we should meet with Matt Self and Andrea Schneider. They are the PMs that have overseen past form implementations on the VA.gov website and will be able to clue us in on what currently exists, what may be able to be reused, and what we may need to build from scratch.

Who will meet: 
- Jesse Cohn
- Brett Kippes
- Matt Self
- Andrea Schneider

Agenda
1. Discuss what recent forms have been implemented on VA.gov
2. Discuss what issues came up during the development of the recent forms on VA.gov
3. Discuss the technical environment for the recent forms on QA.gov

Action Items
1. Jesse and Brett to further investigate the forms pointed out by Matt and Andrea

**Comment by yarogit** [comment]
Hi Peter,

I intend to include you on all engineering invites and you can accept or
decline.
Is this good for you?

Many thanks,
Scott


[image: GovernmentCIO] <http://www.governmentcio.com/>
Michael "Scott" Yaroschuk | PMP
Director Digital Center DC
| *mobile* (703) 298-1400
| *e.* syaroschuk@governmentcio.com
*Government*CIO
website <https://www.governmentcio.com/> | media
<https://governmentciomedia.com/> | services
<https://www.governmentcio.com/services> | jobs
<https://careers-governmentcio.icims.com/> | map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>
[image: Twitter] <https://twitter.com/GovernmentCIO> [image: Facebook]
<https://www.facebook.com/GovernmentCIOMedia> [image: LinkedIn]
<https://www.linkedin.com/company/governmentcio> [image: YouTube]
<https://www.youtube.com/user/GovernmentCIO/videos> [image: Instagram]
<https://www.instagram.com/gciotalent>
*Confidentiality Note: *This email may contain confidential and/or private
information.
If you received this email in error please delete and notify sender.

**Comment by pkinch** [comment]
Yeah I just didn’t see my name listed in the body

**Comment by yarogit** [comment]
Ahhh,  I think Jesse made that one before he knew about you...

Many thanks,
Scott


[image: GovernmentCIO] <http://www.governmentcio.com/>
Michael "Scott" Yaroschuk | PMP
Director Digital Center DC
| *mobile* (703) 298-1400
| *e.* syaroschuk@governmentcio.com
*Government*CIO
website <https://www.governmentcio.com/> | media
<https://governmentciomedia.com/> | services
<https://www.governmentcio.com/services> | jobs
<https://careers-governmentcio.icims.com/> | map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>
[image: Twitter] <https://twitter.com/GovernmentCIO> [image: Facebook]
<https://www.facebook.com/GovernmentCIOMedia> [image: LinkedIn]
<https://www.linkedin.com/company/governmentcio> [image: YouTube]
<https://www.youtube.com/user/GovernmentCIO/videos> [image: Instagram]
<https://www.instagram.com/gciotalent>
*Confidentiality Note: *This email may contain confidential and/or private
information.
If you received this email in error please delete and notify sender.
