### ISSUE TITLE
Settings: Manage notifications

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#13697]
- [ ] As a user, I can turn all my app notifications on or off.

**Comment by bridgethapner** [comment]
@jjulian I think we can consider this unblocked & start the UI work, does that sound right to you?

**Comment by jjulian** [comment]
Not yet - #16026 needs to be complete to provide the API for managing push settings.

But yes, I'm ready to work with FE devs on the mobile app parts of #16026.

**Comment by bridgethapner** [comment]
Ok, thank you! Will slate for next sprint.

**Comment by jjulian** [comment]
The API is not yet functional, but the [API docs](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/mobile/docs/index.html) should be complete - @jperk51 can confirm

**Comment by msmanak** [comment]
## Notifications Turned on after system prompts
- User clicks yes for push notification, push will turn on for all notification until user turns off in settings.
- Toolbar bubble will indicate how much messages per tab
- in app notification will show banner. (time:-----)

1. User goes to settings to change app category settings
2. toggle


## Design Decisions

- Use list and toggle

![Slice-SETTINGS.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/32a78bb9-f42f-43ea-9d67-a40221911242)
