### ISSUE TITLE
Investigate and understand the set up of the e2e for the 1990/preneed

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#137]
## Description
Currently we have e2e running for the 1990 and preneed. Now, we want to better understand the work that's been done there and leverage it as we work to set up an e2e for prefill.

## AC
- [ ] The two existing e2e test have been reviewed
- [ ] A plan is put in place to extend the 1990 e2e test to include login #138 

## Def of Done
- [ ] AC is complete
- [ ] Connected to an epic

**Comment by brandonrapp** [comment]
This work has been included in #644 and thus this ticket will be closed.
