### ISSUE TITLE
Analytics Reporting Request for API - Connected Apps

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#13708]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
Hello all, we are looking for a way to see all the info around connected applications in the new Profile 2.0. auth EX just rolled out to 25% users, but it seems the data in GA is a bit mixed up with connected accounts. 

For example here are the two areas I found GA data: 
- Most of the interactions: 
https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20200916&_u.date01=20200917&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:~2Fprofile~2Fconnected-applications~2F,analytics.eventCategory:Interactions/
- A dashboard: https://analytics.google.com/analytics/web/#/dashboard/-7uuXRP8QJOLgqwi7s5OOg/a50123418w177519031p176188361/

It seems like all the interactions are not displayed for example the disconnect info that is found in the dashboard (profile-disconnect-connected-apps-successful) is not showing up anywhere else.
It would be great if we could have a dashboard to have all the information in one place so it isn't so scattered or if the info was just in the interaction sections. 

Also if there are things that are not being tracked on the /profile/connected-applications/ page it would be great to know (we are a newer team and don't have the history info around this). 

- [ ] Timeframe for Analytics Requested
ASAP because Profile 2.0 is being rolled out now and it would be great to have this data from the start. 
- [ ] Analytics to Track Down
All interactions connected to /profile/connected-applications/ and special attention to if we can tell when people have a connected app, disconnect an app successfully (and any errors that happen), and if possible when they connect a new app. 
- [ ] Which Product Questions are you trying to answer?
How are the users interacting with connected apps, what problems are they having or what successes, 
- [ ] Additional Comments
It would also be really nice to see if possible when folks click the FAQs "how do I connect a 3rd party app" and it would also be really nice to see am event flow so we know where users are going after the page better.
## Description
Who is this request for?
End User experience team 
- [Insert Name(s)]
TJ Rice 👋 
    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?
VA Lighthouse API 
    _this adds context for the data_
    - [Insert team and project)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after)?

## Analytics to Track Down
> Examples
> 
> - [ ] Metric 1
> - [ ] Metric 2
> - [ ] Metric 3

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @ricetj , confirming receipt, we will take a look and get back with you

**Comment by bmcgrady-ep** [comment]
@ricetj - Thanks for pointing out that not all of the interactions are tracked on the Connected Apps Dashboard. I changed the dashboard to reflect the interactions with connected apps. Here is a [link](https://analytics.google.com/analytics/web/#/dashboard/-7uuXRP8QJOLgqwi7s5OOg/a50123418w177519031p176188361/) to the updated dashboard. Let me know if you want me to change anything.

**Comment by ricetj** [comment]
> @ricetj - Thanks for pointing out that not all of the interactions are tracked on the Connected Apps Dashboard. I changed the dashboard to reflect the interactions with connected apps. Here is a [link](https://analytics.google.com/analytics/web/#/dashboard/-7uuXRP8QJOLgqwi7s5OOg/a50123418w177519031p176188361/) to the updated dashboard. Let me know if you want me to change anything.

Thanks for the update. I do have another question though. Why on this list of interactions: https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20200916&_u.date01=20200917&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=500&_r.drilldown=analytics.pagePath:~2Fprofile~2Fconnected-applications~2F,analytics.eventCategory:Interactions/ does disconnect not show up?

**Comment by bmcgrady-ep** [comment]
The disconnected apps interaction does not show up because it has not happened yet. I reached out to the connected apps team and they said while the `disconnect` events are live in production, they are probably a rare event and haven't happened yet. The report you sent over with the list of interactions only shows interactions that have been completed by users.

**Comment by ricetj** [comment]
> The disconnected apps interaction does not show up because it has not happened yet. I reached out to the connected apps team and they said while the `disconnect` events are live in production, they are probably a rare event and haven't happened yet. The report you sent over with the list of interactions only shows interactions that have been completed by users.

Ooo ok thanks for the clarification and all the help!

**Comment by bmcgrady-ep** [comment]
You're welcome. Let me know if you have any more questions.

I'm closing out the ticket, but once again feel free to reopen if anything else comes up.

**Comment by ricetj** [comment]
@bmcgrady-ep not sure if this is how I should do this, but I repoed because I need some help on the connected app's dashboard: https://analytics.google.com/analytics/web/#/dashboard/-7uuXRP8QJOLgqwi7s5OOg/a50123418w177519031p176188361/_u.date00=20200917&_u.date01=20201008/

I am trying to improve my query for the # of users interacting with the Connected Apps FAQ. 
I am trying to capture all the interactions with the Connecting third-party (non-VA) apps to your VA.gov profile section of the sign-in FAQs page (https://www.va.gov/sign-in-faq/), but for the life of me I can't figure out how to query all the different areas of the section that can be expanded. I would ideally like to track all the interactions there so I know how many people are interacting with that section of the FAQs.

**Comment by bmcgrady-ep** [comment]
@ricetj - Here is an [updated report](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20200917&_u.date01=20201008&_r.drilldown=analytics.pagePath:~2Fsign-in-faq~2Findex.html&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22What%20are%20connected%20apps,%20and%20why%20might%20I%20want%20to%20use%20them%3F%7CHow%20are%20connected%20apps%20different%20from%20My%20HealtheVet%20or%20VA%20mobile%20apps%3F%7CWhat%20third-party%20apps%20can%20I%20connect%20to%20my%20profile%3F%7CHow%20do%20I%20connect%20an%20app%20to%20my%20VA.gov%20profile%3F%7CI%20don%5Cu2019t%20have%20a%20smartphone.%20Do%20I%20need%20one%3F%7CWhat%20should%20I%20do%20if%20my%20records%20in%20an%20app%20are%20wrong%20or%20out%20of%20date%3F%7CCan%20I%20stop%20sharing%20my%20VA%20information%20with%20an%20app%3F%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=25/) of the FAQ page data with only interactions for the Connected Apps section of the FAQ page.

**Comment by ricetj** [comment]
> The disconnected apps interaction does not show up because it has not happened yet. I reached out to the connected apps team and they said while the `disconnect` events are live in production, they are probably a rare event and haven't happened yet. The report you sent over with the list of interactions only shows interactions that have been completed by users.

@bmcgrady-ep another question on this. It looks like we still haven't seen any disconnects. I did see this page, but not sure if this is correct  https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/_u.date00=20201102&_u.date01=20201102&_r.drilldown=analytics.pagePath:www.va.gov~2Fprofile~2Fconnected-applications~2F,analytics.eventCategory:API%20Calls&explorer-table.plotKeys=%5B%5D/

The connected apps page has nothing to do with direct deposit. Is that a mistake?

**Comment by bmcgrady-ep** [comment]
@ricetj - Correct, the connected apps page has nothing to do with direct deposit. I do see the `Profile - Direct Deposit Retrieval Started` and `Profile - Direct Deposit Retrieval Successful` events happening on each of the profile pages. I believe this is due to the events being an API call.

**Comment by ricetj** [comment]
> @ricetj - Correct, the connected apps page has nothing to do with direct deposit. I do see the `Profile - Direct Deposit Retrieval Started` and `Profile - Direct Deposit Retrieval Successful` events happening on each of the profile pages. I believe this is due to the events being an API call.

@bmcgrady-ep we had one of our veteran team members test the disconnection in Prod today and it looks like we still are not receiving any data from GA.

**Comment by bmcgrady-ep** [comment]
@ricetj - Okay, thanks for letting me know. Would you be able to provide me with a test user that I can go test disconnecting an app?

**Comment by ricetj** [comment]
@bmcgrady-ep  Sure, test user 1 has an app connected in staging, so you can disconnect the app via the profile and then go to https://va-claims-staging.herokuapp.com then click login to get started to reconnect the application to the test user's profile (you will need to login as test user 1 and consent to have the app appear in the profile). If you have problem I'm happy to jump on a call.

**Comment by bmcgrady-ep** [comment]
Hi @ricetj - I tested disconnecting an app via the profile and we currently have the event coming in the data layer. However, I am not seeing any events coming in GA, so I am thinking that we still need to implement using GTM.

Here is a screenshot of the event coming through:
![image](https://user-images.githubusercontent.com/66263904/98401713-5d86ed80-2023-11eb-934f-72a830584a64.png)

cc @jonwehausen @bsmartin-ep

**Comment by ricetj** [comment]
> Hi @ricetj - I tested disconnecting an app via the profile and we currently have the event coming in the data layer. However, I am not seeing any events coming in GA, so I am thinking that we still need to implement using GTM.
> 
> Here is a screenshot of the event coming through:
> ![image](https://user-images.githubusercontent.com/66263904/98401713-5d86ed80-2023-11eb-934f-72a830584a64.png)
> 
> cc @jonwehausen @bsmartin-ep

hello @bmcgrady-ep please let me know next steps and happy to work with you all on this.

**Comment by bmcgrady-ep** [comment]
@ricetj - thanks! We will be following-up with the next steps shortly.

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

Ready for your QA:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000383

Please also test - as discussed - the other API call that magically disappeared from GTM.


```js
{
     event: 'profile-get-connected-apps-retrieved',
     'user-has-connected-apps': hasConnectedApps,
}
````

Would you also mind doing a pass on all the profile triggers in GTM to make sure [this trigger won't cause problems](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000383/triggers/1002)?

`^profile-(.+)-connected-app.*$`

I don't think it will, but would appreciate an extra set of eyes.

**Comment by bmcgrady-ep** [comment]
### QA for Disconnected App Events

Interaction | dataLayer Screenshot | Test Status
-- | -- | --
Disconnect App | ![image](https://user-images.githubusercontent.com/66263904/98567950-c792d300-226d-11eb-8ae6-a262115c5dfb.png) | ✔️ **PASS**
Connected App Retrieved | ![image](https://user-images.githubusercontent.com/66263904/98568041-e4c7a180-226d-11eb-894e-78e4efa463a9.png) | ✔️ **PASS**

**Comment by bsmartin-ep** [comment]
@ricetj / @bmcgrady-ep -

GTM workspace has been published.  Closing.

**Comment by bsmartin-ep** [comment]
Post-close update:

Lookup table was updated and published.

![image](https://user-images.githubusercontent.com/62304138/98707946-9807c780-234e-11eb-8e56-4b59767d6830.png)

**Comment by bmcgrady-ep** [comment]
> @bmcgrady-ep Sure, test user 1 has an app connected in staging, so you can disconnect the app via the profile and then go to https://va-claims-staging.herokuapp.com then click login to get started to reconnect the application to the test user's profile (you will need to login as test user 1 and consent to have the app appear in the profile). If you have problems I'm happy to jump on a call.

@ricetj - I disconnected the app from User 1 and have reconnected a few times for QA purposes. For some reason, this last time I am unable to reconnect the app to User 1's profile. Let me know on next steps.

**Comment by ricetj** [comment]
> > @bmcgrady-ep Sure, test user 1 has an app connected in staging, so you can disconnect the app via the profile and then go to https://va-claims-staging.herokuapp.com then click login to get started to reconnect the application to the test user's profile (you will need to login as test user 1 and consent to have the app appear in the profile). If you have problems I'm happy to jump on a call.
> 
> @ricetj - I disconnected the app from User 1 and have reconnected a few times for QA purposes. For some reason, this last time I am unable to reconnect the app to User 1's profile. Let me know on next steps.

Hey @bmcgrady-ep sorry to took my awhile to find this ticket. Can we setup sometime today so I can show you the flow to connect and disconnect an app?

**Comment by bmcgrady-ep** [comment]
Hi @ricetj - Sure, I am available anytime after 12PM EST today.

**Comment by joanneesteban** [comment]
@bmcgrady-ep what was the outcome of this meeting?

**Comment by bmcgrady-ep** [comment]
@joanneesteban - @ricetj and I met to discuss the flow of connecting and disconnecting an app. This ticket should be able to be closed as it is now complete.
