### ISSUE TITLE
[Documentation] AlertBox missing `level` property docs

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#13716]
### What is your documentation request, question, comment, or issue?

The `<AlertBox>` documentation does not include a `level` property. 

https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/

This property is essential in maintaining our accessibility heading levels in sequence.

## Related Code

https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation-react/src/components/AlertBox/AlertBox.jsx#L58

## Example

```jsx
<AlertBox
  headline='Informational alert'
  content="Lorem ipsum dolor sit amet."
  status="info"
  level={2}
  isVisible
/>
```

Results in

```html
<div class="usa-alert usa-alert-info">
  <div class="usa-alert-body">
    <h2 class="usa-alert-heading">Informational alert</h2>
    <div class="usa-alert-text">Lorem ipsum dolor sit amet.</div>
  </div>
</div>
```

**Comment by taylorkaren** [comment]
Going to https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/  is now returning a "NOT FOUND You just hit a route that doesn't exist... the sadness." message.

Maybe this is the correct URL now: https://design.va.gov/components/alertboxes?

**Comment by Mottie** [comment]
We can close this issue.... `AlertBox` has been replaced by the `va-alert` web component.
