### ISSUE TITLE
Feature: Add Ability to Skip Rspec Testing in CI

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#13715]
## The Problem
In the event of an off-cycle deployment, we don't always want to wait for the the rspecs to run before deploying new code - such as in the event of an emergency deployment.

## Extra Context
- On a PR, the the required jenkins check may be undone by a `vets-api` GH repo admin
- The `Run Tests` stage of the `vets-api` CI (which runs rspecs), takes ~12-15 minutes.
![image](https://user-images.githubusercontent.com/3077884/93616744-1d03df80-f9a3-11ea-8fae-5b6fc6d1872f.png)

## Work to be Done
- [ ] Add parameter(s) to the jenkins CI job that would allow for rspecs to be skipped
- [ ] Modify jenkinsfile to skip rsepc jenkinsfile stage if said parameters are selected

**Comment by jhouse-solvd** [comment]
We should add some wording to the flag for the job that indicates the sensitivity of skipping unit tests for the code to be deployed.

**Comment by omgitsbillryan** [comment]
It would also be a good idea to update the ["Resolving Critical Issues"](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/resolving-critical-issues.md) doc when this ticket is complete.

We could even link to this doc directly from some wording on the jenkins job page. Something like,

> [ ] Skip Rsepc Testing (You may use this option when performing a time-sensitive off-cycle deploy - See doc for more details)

**Comment by jhouse-solvd** [comment]
This has been mitigated by the fact that the RSPEC stage takes only 4-5 minutes due to some parallelization work that was done by @bosawt. 

Not a super high priority at this moment, and will consult w/ other teams for prioritization/ownership of this work.

**Comment by jhouse-solvd** [comment]
@ericboehs - flagging you for awareness on something that was previously proposed. this is likely low priority, and may not be immediately necessary, but wanted to share for visibility.

**Comment by ericboehs** [comment]
We'll be moving away from Jenkins for testing in a sprint or two. I'm not sure if that solves any issues here but it will change the way we solve this problem.

I'm also curious how much work we want to put into something that will only work for a short while. Once we are on EKS, we'll have to devise a different strategy for skipping tests or perhaps this will be a non-issue as we could just push a commit to the argo repo.

**Comment by jhouse-solvd** [comment]
@ericboehs - yeah, I think you're spot on. we'll leave this ticket as a reminder but move to the icebox.

**Comment by jbritt1** [comment]
Is this one closable?

**Comment by ericboehs** [comment]
@jbritt1 We can skip for BRD but how do we do this in EKS? I haven't thought through a solution to that. Would we just force a deploy in argo?

**Comment by jbritt1** [comment]
I honestly can't imagine a "turn off testing to push to prod" scenario being a good thing. Even last week when you, Matt, Oseas, and I were on that call fixing prod after 5pm ET on a Friday we didn't skip testing. I get that there could be an argument for it in the event of an emergency, but it doesn't give me the warm and fuzzies.

**Comment by ericboehs** [comment]
Then there should be a way to rollback without making a code change. Imagine a scenario where api.va.gov was completely down and we needed to roll out code. Having to wait for CI and a new AMI to build is insane.

I'm fine with closing this if we have a way to rollback deployments in EKS.

**Comment by jbritt1** [comment]
ArgoCD has the rollback functionality built-in:

![image](https://user-images.githubusercontent.com/56260532/174816063-6844dca6-1f07-4a1e-8af0-8bbedd7f8edf.png)

![image](https://user-images.githubusercontent.com/56260532/174815988-676cdc6a-77c3-42d5-a50e-f8ce3a317d29.png)

With that, can this be closed at this time?

**Comment by jbritt1** [comment]
Closed, feel free to reopen if needed.
