### ISSUE TITLE
Access for Kevin Lee

### ISSUE THREAD

**Issue by LeKeve** [department-of-veterans-affairs/va.gov-team#13710]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   Cecilia Lee
- Please provide your name.
  Kevin Lee
- Please Provide your email.
   kevin.lee@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
  Lighthouse End User Experience, Software Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcNdPEBjby1NM6sXvDPcqE9MHOxzM18RrKMzUP7KOXj6IYkjE5A6KRJJaXff4nUIpecn2R8xkKzmhTj/2E8SVqk7yRbYXiqn78BT7kNqV5zjSX+v9UeIyK2uxhxJpheP9qb4e7ottXsyExnRVGaBhqcpt5AhiWZScMTRzSWREdqNae04R+f98Z+OpqE4RE9UfZgwaoolK0RFyLFFP3r2ajrpGYLxjVm8cgBAKVIvkX4Yv8lpKS5Ghck0plm9bgag/ghKmvDSgk7ecZmGWawku5x9oknsO9ztim3Ka6jKizzi/zs0X1b9QzJ8xRfO0k57Va2mNB5VwvUlv2U1JUxCw/a8FUWVe+iwiVott4pVXUNE8byJCH3cfAulv7zOhigwEfFcnkg0S6jnFGIq7jteyCyd6mFWP+epVsB/zsVQRhlWRASHFgWQWUm7aqMaJL3kwObt/quBitWRrw7CvUlJQBHlmXaP5fOV8FzMOq+c1z3M0rN2dgcfJTQXP3h0VNbC13xXgpJOZiAht47Duz2DaI8lCsxyfZ/0V1Ws5HCVwYsXrbZtwZ4DjlDe/gu7GIhcFglT41n/FPlXMSrqiYELkIFK8APJoirr2GOszmN5uKgUx2WJlxzR4xB2oxRBQE2PyXHf8s+rdeojefPcEyaj8EPux1I/emeMssvtqiRahbPw== kevin.lee@adhocteam.us

```

- Grant AWS Console access?
  > NO

**Comment by pnwstevan** [comment]
Hi @LeKeve!

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.
