### ISSUE TITLE
Additional information about Veteran SSN

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#13712]
Given that Veteran SSN is required on the online form but not the paper form
I want to create some additional context on the online form
To explain to Veterans why there's a difference.

Content is in the comments, screenshots from the prototype are below:

## 1 Subway Map
![Screen Shot 2020-09-18 at 1.45.51 PM.png](https://images.zenhubusercontent.com/5ddc08a57dcda00001c763e1/42cb8099-9f23-461d-8ee8-95e21d8425dd)

## 2 Veteran information (additional info component collapsed)
![Screen Shot 2020-09-18 at 1.46.39 PM.png](https://images.zenhubusercontent.com/5ddc08a57dcda00001c763e1/d59e4bd9-4c2d-44ea-9ed6-9d241f85b73b)

## 3 Veteran information (additional info component open)
![Screen Shot 2020-09-18 at 1.46.23 PM.png](https://images.zenhubusercontent.com/5ddc08a57dcda00001c763e1/fe4b68fb-6918-48d1-bde5-1f93f002cd65)

**Comment by ala-yna** [comment]
Here is the content. 

# 1. Subway map:

1. Prepare
To fill out this application, the Veteran and each family caregiver applicant will need to provide specific information. You’ll need:
●	The address, telephone number, and date of birth for the Veteran and each family caregiver applicant
●	The VA medical center where the Veteran will receive care
●	Health insurance information for the Primary Family Caregiver
     
Note: You’ll need to have the Veteran’s Social Security number or tax identification number to complete the online application, but it’s not required to apply for the program. If you would like to apply without providing the Veteran’s Social Security number or tax identification number, [download the form](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/).



# 2. Form section

[Text input] Veteran’s Social Security number or tax identification number (required) 

[Expanded learn more] Why is this required?
We need the Veteran’s Social Security number or tax identification number to process the application when it’s submitted online, but it’s not a requirement to apply for the program.

**Comment by ala-yna** [comment]
@peggygannon, if this is something you could take a look at when you get a chance, would be much appreciated! Let me know if you have any questions.

**Comment by ala-yna** [comment]
Tagging a couple of other folks who we would appreciate some :eyes: from: @emilywaggoner, @sshein, @jenstrickland, @1Copenut. Thanks!

**Comment by sshein** [comment]
I think the content in the form itself seems fine. I think the content on the intro page is a bit heavy handed (having it as a "note" separate from the bullets), I would definitely get @peggygannon's thoughts on that if possible.

**Comment by jenstrickland** [comment]
1. Agree with Shawna that it would be more empathetic to remove "Note:".

1. For the "Why is this required?" additional info this should be a link instead of the button usually used to code an additionalInfo component. At this time, the design system component still uses the `<button>` for the additional info activator. @1Copenut — do you know if there's a plan to add the link option?
    * [VA developer documentation for additionalinfo](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/additionalinfo/)

    * [VA design system documentation for additionalinfo](https://design.va.gov/components/additional-info)

    * [View CodePen example](https://codepen.io/tpierce_402/pen/PoYVKKa)

```
<label>Veteran’s Social Security number or tax identification number (* Required)</label>
<a aria-expanded="true" class="vsp-button--expandable vsp-button--expandable-link" role="button" href="#">Why is this required?</a>
<div>
  <p>We need the Veteran’s Social Security number or tax identification number to process the application when it’s submitted online, but it’s not a requirement to apply for the program.</p>
</div>
```

**Comment by peggygannon** [comment]
Hello, @ala-yna I recommend we keep the SSN and TIN as part of the bullets and not separate out as a note.  This treatment also aligns with how we've handled this scenario in other tools/forms. 

Let me know if you have any questions. 


**Prepare**
To fill out this application, the Veteran and each family caregiver applicant will need to provide specific information. You’ll need:

- The address, telephone number, and date of birth for the Veteran and each family caregiver applicant
- The VA medical center where the Veteran will receive care
 - Health insurance information for the Primary Family Caregiver
- Social Security number or tax identification number (This is required for the online application only. If you’d like to apply without providing this information, you can [download the paper form (PDF)]. 

-----

On the form: 
Question: is the reason that this is required is b/c of simply how it's processed--online vs. paper?  will online forms not get processed without this info? I'm wondering if we can a little more specific in the drop-down message?


[Text input] Veteran’s Social Security number or tax identification number (Required)
{ if null, then validation error} **Please provide a Social Security or tax identification number**

-	[Expanded learn more] Why is this required?
The Veteran’s Social Security or tax identification number is needed to process the online application only. This information isn’t required to apply to the program.

**Comment by ala-yna** [comment]
Hi @peggygannon - thank you for your help! The wording in the "Prepare" section is still a little off, I think; SSN or TIN is required for the Veteran on the online form, but not required for any of the family caregiver applicants. Does this sound ok?

Social Security number or tax identification number of the Veteran (This is required for the online application only. If you’d like to apply without providing this information, you can [download the paper form (PDF)].

**Comment by peggygannon** [comment]
Hi, @ala-yna I would recommend this to tighten up that line a bit: 

- Veteran's Social Security number or tax identification number (This is required for the online application only. If you’d like to apply without providing this information, you can [download the paper form (PDF)]

**Comment by ala-yna** [comment]
Perfect, thank you @peggygannon ! I'll make sure @jonathanjnelson gets this incorporated into the designs for our 10/1 release. Thank you again!

**Comment by jonathanjnelson** [comment]
Updating this ticket for awareness: 

Designs are updated to address 508 request and align with our download PDF pattern on VA.gov

<img width="801" alt="Screen Shot 2020-09-23 at 8 22 13 AM" src="https://user-images.githubusercontent.com/58444931/94044569-f0313d00-fd93-11ea-84a6-248e57900d3b.png">
