### ISSUE TITLE
Update form526 wizard wording

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13721]
The wizard wording should be updated to reflect that a veteran could be released from active duty but still part of the reserves

![Screen Shot 2020-09-18 at 12.48.47 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/6e404898-41b3-45ee-aa86-720c350dce9f)

**Comment by kevinstachura** [comment]
A couple options that were discussed in the meeting:

>"Are you on active duty?"

>"Are you currently on active duty?"

However, we may need to massage this to make it more apparent to reservists that it's the RAD date and not a term of service end date.

**Comment by kevinstachura** [comment]
I did include the latter content option ("Are you currently on active duty?") in the design - which can be viewed here:

https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/421391041_BDD_Gating_-_Have_You_Separated

I will need to mock this up in the 'new wizard' flow - but keeping the content as the focal point here - this is what it would look like with the new language.

**Comment by Mottie** [comment]
Fixed in https://github.com/department-of-veterans-affairs/vets-website/pull/14489
