### ISSUE TITLE
Analytics Implementation for COVID FAQ Accordion Embedded Links

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#13727]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- With our goal of improving our COVID-19 VA response dashboard, we would like to ensure we are capturing and ingesting as much data as we can around the common questions veterans are concerned with during this time
- As part of that goal, we would like to add tracking to embedded links within accordions to understand which questions are being engaged with the most/least

## Datalayer Specification
- The structure below is our existing taxonomy that lives on COVID FAQ to record link clicks, along with the FAQ and FAQ section of each link. 
- The variable `faqText` should populate with the question contained on the accordion itself and the `faqSection` should still populate with the top level section header. Here is an example: 

Description & Screenshot | Data Layer Example
------------ | -------------
Click on the link 'CDC website' <br><br> ![image](https://user-images.githubusercontent.com/48527022/93599594-5d0b9800-f98c-11ea-8210-4283560bd364.png)  | `'event': 'nav-covid-link-click',`<br>`'faqText': 'Do I need to wear a mask when I go to a VA hospital or other location?'`<br>`'faqSection': 'Health care, appointments, and more'`

## Acceptance Criteria
- [ ] Data Layer has been implemented and QAed
- [ ] GTM has been configured and QAed
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@ncksllvn here is the new issue for the accordion embedded links. Thank you again for your time and please let us know any questions you may have.

**Comment by ncksllvn** [comment]
@MickinSahni @brianalloyd Can we add this one to our next sprint?

**Comment by jonwehausen** [comment]
Hi @ncksllvn / @MickinSahni 

Was curious if we had a status update here? Thanks again 👍

**Comment by MickinSahni** [comment]
Hey @jonwehausen, not yet. This item is lower priority for us vs. learning center and upcoming form detail and cerner launches.

**Comment by jonwehausen** [comment]
Hi @MickinSahni , 

Thanks for the update here.

**Comment by joanneesteban** [comment]
@brianalloyd any updates here? We're looking to see if we can add this data to our Covid-related datasets.

**Comment by brianalloyd** [comment]
@joanneesteban thanks for circling back, This item remains lower priority for us vs. Resources and Support MVP 1.1 launch and the huge undertaking on Transformers.  I'm going to bring this up in planning today and see if we have the bandwidth but more realistically will not be able to get to this until Sprint 37.  I'll follow up post planning.

**Comment by joanneesteban** [comment]
@brianalloyd let us know when you have an update on this, and we can QA on our side.

**Comment by brianalloyd** [comment]
Sounds good @joanneesteban we're going to do our best to fit this into this sprint, I'll keep you updated in support.

**Comment by brianalloyd** [comment]
@kelsonic can you take a look and provide an estimate.  Would also like to fit this into this Sprints workflow.  Thanks.

**Comment by brianalloyd** [comment]
@kelsonic @RLHecht could you both take a look at this and advise on estimate. Would like to clear this out in Sprint 38.  Thanks.

**Comment by RLHecht** [comment]
@brianalloyd I don't think this is a content thing so I am going to defer to @kelsonic on this one.

**Comment by ncksllvn** [comment]
The current estimate of 3 (or possibly bumped to a 5) is what seems accurate to me

**Comment by brianalloyd** [comment]
Thanks @RLHecht and @ncksllvn for the feedback and estimate.  This has been floating around for some time and would like to work it into our flow this sprint or next if possible.  We can discuss in planning.  Thanks.

**Comment by brianalloyd** [comment]
@ncksllvn if you have bandwidth post MVH work, please pick up this ticket for review and action.

**Comment by ncksllvn** [comment]
I merged a PR just now that should start passing in the `faqText` in the GA event. Here's an example where I clicked `Learn more about volunteering`

![image](https://user-images.githubusercontent.com/1915775/104742690-be642d80-5718-11eb-8cf9-eb1fb7f44903.png)

  `faqSection` won't be included in the event object due to a technical limitation. The heading `More coronavirus-specific questions` is just typed into a WYSIWYG and has no relationship to the accordion below it, so the analytics-handler can't reliably capture it. Thread on that here, https://dsva.slack.com/archives/CDHBKAL9W/p1610492404381400.

**Comment by brianalloyd** [comment]
FYSA @joanneesteban @jonwehausen

**Comment by jonwehausen** [comment]
Hi @ianMcCullough-ob , I have handed this item off to you for QA testing. 

### Steps to QA: 
- Expand an click on embedded links within [accordions with questions](https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/#more-benefit-and-claim-questions) 
- Check that the data layer populates according to this taxonomy (found above): 
![image](https://user-images.githubusercontent.com/48527022/105735612-e7977180-5f01-11eb-9912-88fb71d7bc00.png)
- Ensure existing GTM tagging is populating with the correct tagging and [custom dimensions 77 and 78](https://analytics.google.com/analytics/web/#/a50123418w177519031p176188361/admin/custom-dimensions/)


cc: @joanneesteban & @JasonTheBearded for visibility

**Comment by jonwehausen** [comment]
@JasonTheBearded @bsmartin-ep @joanneesteban Following @ianMcCullough-ob 's testing, we will want to determine if and how we want to include this data within the COVID dashboard. 
- If we want to include, we'll want to make sure the questions getting added and categorized correctly and our engagement metrics are recalculated

**Comment by ncksllvn** [comment]
Keep in mind that `faqSection` will not be present in the event object. The page's content model does not have a relationship between the heading that precedes the accordion and the accordion itself, so there isn't a clear way to grab the heading's text to capture in the event object.

**Comment by jonwehausen** [comment]
Okay, thanks for that context @ncksllvn

**Comment by ianMcCullough-ob** [comment]
For this test, I clicked on in-text "CDC website" link under the "How else will VA protect me from exposure to COVID-19?" FAQ on the [Coronavirus FAQs page](https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/#more-benefit-and-claim-questions) (*screenshot below*)

<img width="707" alt="Screen Shot 2021-01-25 at 3 36 08 PM" src="https://user-images.githubusercontent.com/73119703/105762959-1ffb7780-5f23-11eb-964a-002fc5931fe1.png">

***


| Item Tested                    | Screenshot | Test Status                                                  |
| :----------------------------------------------------------- | :--------- | :----------------------------------------------------------- |
| **event: nav-covid-link-click / Data Layer** | <img width="527" alt="Screen Shot 2021-01-25 at 3 00 26 PM" src="https://user-images.githubusercontent.com/73119703/105762289-348b4000-5f22-11eb-940f-ff056cdde243.png">| ✔️ **PASS**<br />Note: `faqSection` populates with `undefined` per @ncksllvn's comment earlier |
| **Tag: EV - COVID FAQ / Custom Dimensions**|<img width="557" alt="Screen Shot 2021-01-25 at 3 19 43 PM" src="https://user-images.githubusercontent.com/73119703/105762309-39e88a80-5f22-11eb-983c-82c67be2f502.png"> | ✔️ **PASS**                                                   |

@jonwehausen please review the above table and let me know if you need anything test tested. Not sure if `nav-covid-link-click / Data Layer` should for sure get a pass or if there needs to be more testing/development around that.

**Comment by brianalloyd** [comment]
@joanneesteban and @jonwehausen it looks like the Public Website teams work here has been validated, are we at a point that we can remove our labels in support of this ticket?  Thanks.

**Comment by jonwehausen** [comment]
Thanks for your QA here @ianMcCullough-ob , this looks great!

One question I had here - @ncksllvn , I see on the spanish page `https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/` the `faqText` and `faqSection` (where available) populate in spanish, would it be possible for these variables to be pushed to the data layer consistently in english? 

Thanks so much here

**Comment by jonwehausen** [comment]
cc: @bmcgrady-ep & @JasonTheBearded for visibility

**Comment by jonwehausen** [comment]
@ncksllvn We were able to get word from and @SKasimow + @youngfreezyVA that it would be a larger lift to return the english versions, so we will manipulate the data on our end for now. 

Closing this ticket.
