### ISSUE TITLE
Access for Johanna Del Pino

### ISSUE THREAD

**Issue by johanna-adhoc** [department-of-veterans-affairs/va.gov-team#13723]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Johanna Del Pino
- Please Provide your email.
   >johanna@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VA API - developer portal account management
   > Role: Staff Software Engineer
   > Company: AdHoc

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxSC8zXR1izUR8RVfXnTYLT5IDX316J/0GtLvhozBE/CQSFeM33FrWJdf6FYpS1zkpGZdKx1Ssg5b2aGSfdfTlQpunCtu9BgKAOW3wO0ffFEdkatmHfvTjiGv6HLcLsMsMvGwy8OGIWTO0PWv5ydAmS8nEXaVFhqlZcCxAoZcjDdJtRSgENGl5PdizsWJhzmmopau/oA91ZL1GgN3K31/Ff22JOvif2aNS79EU7nSSjNZQUnhSvkKxhgMWSPGEJIwXgsVbDjShSUIG1fHedVYen7NWuwwTG47m9Yn5Tc6WJ/AOlnP/LQXhDLDHZG99n/U6xxcyB+YCi2MlKBX5vd3R6fERhVDrs7FIkHwQic14Mcu7sn5uKQHE6v/8uPscyXSWgy7MhexrYxAoe9plQshLE0l2q3LIPgFqTPKHfmO0jlaFIf8yC5Q/OnEHrNUkIUjT88LF3i6gecEaETyfL8eM05md0hDoqCBt9RK4/JOxPCcSi/flLtuSCj105j2F8wM= johannadelpino@Johanna-Del-Pinos-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES
  -  Need AWS Console access for developing and maintaining the Lighthouse dev portal.

**Comment by johanna-adhoc** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by pnwstevan** [comment]
Hi @johanna-adhoc!

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

**Comment by pnwstevan** [comment]
**For AWS Access:**
User: Johanna Del Pino / @johanna-adhoc 
COR: Cecilia Lee
Approval needed: @Jeff-Hayter

**Comment by johanna-adhoc** [comment]
The socks access is working thanks!

**Comment by Jeff-Hayter** [comment]
@pnwstevan Approved for AWS access.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
