### ISSUE TITLE
Accessibility feedback/guidance for Design Intent Collaboration – Facilities [Vet Centers] 

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#13729]
**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This ticket contains the accessibility feedback/guidance for the Facilities [Vet Centers] Design Intent Collaboration.

### Must

1. Explore mobile design, which should clarify hierarchy and the starting point for progressive enhancement.

### Should

1. Include mobile users in research, and especially non-WiFi. In order to test cellular data connectivity, it may be necessary to use team members, since we don't want to impact anyone with limited data plans.

1. Define a performance budget for these pages, if possible; this would limit the number of images and scripts, thereby delivering an empathetic, useful page load time.

1. Use progressive enhancement to deliver an experience that is useful regardless of device or connectivity, and enhance as appropriate. Defer loading and use responsive image techniques.

1. Collaborate frequently with your VSA accessibility specialist as design and research plans evolve.

### Consider

1. Event listings - Providing events as a .ics attachment.  I love this as an experience design bonus, clicking on a link and having it offer to add to my calendar.

1. Content length -- Page may be very long. Consider using the "On this page" navigation component to "skip" and move asynchronously.

1. Visual transitional cues will be important. When I zoom way out and squint at the screen, the page has white/gray banding that may just be wireframe artifacts, or may be cues for background colors. I'd encourage the team to keep these visual divides and offer 1-2 different mechanisms for dividing the page. This can create visual interest and create cognitive distinctions. Color blocks could be used for "big" idea changes, for instance, and horizontal rules or the decorative star + line treatment for "small" idea changes or supporting idea sections.
    - One note about the full-width color bleeds: the current design system prevents implementing these full-width background colors; in order to do this, it would require revisiting the margin and padding styles associated with the `<main>` element, and then adjusting  the margin/padding for child elements.
    - There is interest in modifying the styling as indicated above, specifically for mobile in order to maximize space available and expand design options.

1. Logistical information is super important. I'd recommend this be coded in such a way to maximize SEO. Bonus points for microdata or JSON-LD that enables the smart Google search results for Vet Centers.

1. Interested in seeing how the "Areas we serve", "Map", and "Parking" buckets develop as these wireframes become full designs. I agree these will be very beneficial and necessary information.
    - What does "Areas we serve" represent? Is this things like neighborhood, city, county, state?
    - Are there techniques or UI that could be used to bucket services besides accordions? This creates a challenge for screen readers, those who search by keywords, and possibly SEO for finding service descriptions or more detailed information. It might be as simple as adding a second line that offers the keywords for each service, or exploring other means like two-column short paragraph blurbs about each service and a learn more > link or a responsive table.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by jenstrickland** [comment]
@1Copenut — ready for your review

cc @mmiddaugh @lildziner  FYSA

**Comment by lildziner** [comment]
Thanks so much for taking the time to review and for the input. Will investigate these ideas and check back in again when we have a more refined round.

**Comment by mmiddaugh** [comment]
"Must" feedback has been added as Acceptance Criteria for next iteration (which will follow Veteran research sessions)
All other suggestions have been added to the description of that issue for reference and consideration during

**Comment by 1Copenut** [comment]
@jenstrickland Late to the discussion. Thank you for collating good points about perf budgeting and mobile-first designs. I agree with these feedback and have no additional items.
