### ISSUE TITLE
Access for team digital-foundry-mobile

### ISSUE THREAD

**Issue by jjulian** [department-of-veterans-affairs/va.gov-team#13728]
# Description
Requesting that existing team `digital-foundry-mobile` be granted Write access to repo va.gov-team, to be able to manage issues and add documentation.

# Team
Request from the va-mobile-app team. For more info contact @patrickvinograd @cgreim @srmyers17 

cc @department-of-veterans-affairs/vsp-operations @erikbreedlove

**Comment by srmyers17** [comment]
CC: @steve-gov - we're having trouble with this one. Should this be going somewhere else?

**Comment by drorva** [comment]
approved

**Comment by jbritt1** [comment]
Verified access, closing

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/ef02f2ca-a803-44ed-83e8-94edba55e15f)
