### ISSUE TITLE
cached `/v0/user` response

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#13726]
It appears that in some cases the https://api.va.gov/v0/user endpoint returns a cached JSON payload when it shouldn't be.  The following steps show that when one user logs in with the same credentials in two different browsers, after the second login the subsequent call to `/v0/user` returns the response generated from the first login.

### steps to reproduce bug
1. in Firefox type in the url, https://staging-api.va.gov/v1/sessions/idme/new
1. complete the login process
1. verify that the call to `/v0/user`, after login completes, has `ssoe: true` in the `profile.sign_in` object of the JSON payload
1. in Chrome or Safari type in the url, https://staging-api.va.gov/sessions/idme/new
1. complete the login process WITH THE SAME USER USED IN STEP 2
1. after signing in, you are immediately logged out via https://staging-api.va.gov/v1/sessions/slo/new

### steps to fix
- [x] in vets-api; add `ssoe` and `transactionid` to the Session object, and serialize those values into the `UserProfile` when `/v0/user` is invoked
- [x] in vets-website; read the ssoe transaction id from the new `session` attribute rather than the `profile.sign_in` object
- [ ] in vets-api; remove the `ssoe` and `transactionid` values from the `profile.sign_in` object

**Comment by ericbuckley** [comment]
After reviewing the code, @jholton pointed out that the entire `UserIdentity` payload is cached in redis and keyed on the user's ID.me UUID.  Thus, a subsequent login in a different browser could change the `sign_in` object and cause issues in the first browser the user logged into.

Because the `UserIdentity` object was only meant to store user level data, and not transaction level data (which can change from session to session), the best solution would be to move the `ssoe` and `transactionid` attributes over to the Session object, so the two browser sessions don't conflict with one another.

**Comment by patrickvinograd** [comment]
You _could_ just serialize the txnid and ssoe attributes from the session model into the user object without moving them out of the sign_in object. I.e. change it at API response rendering time, and thus not have to coordinate 3 PRs. But if that will lead to longer term confusion I'm okay with what is proposed.

**Comment by ericbuckley** [comment]
> You _could_ just serialize the txnid and ssoe attributes from the session model into the user object without moving them out of the sign_in object. I.e. change it at API response rendering time, and thus not have to coordinate 3 PRs. But if that will lead to longer term confusion I'm okay with what is proposed.

This is true, however I thought it would read better to the end user if the "session" data was separated from the "profile" data.  I know the FE is unaware of where the data is being stored, but just knowing that the session information can change from browser to browser and the profile information would not, I think could be helpful.
