### ISSUE TITLE
Medallia implementation on VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13724]
## Issue Description

- As the Facilities team, we want to get specific Veteran feedback on the navigation, content and usability of the new VAMC pages. 
- As a PAO at a health care system, I want to know that the Veterans we serve are able to navigate our pages and find the content they need. 

We may be able to implement Medallia for this purpose but need to define the strategy with the following considerations - 
- when should this be implemented?
- what type of feedback will be solicited?
   - and who decides? 
- who will receive the analytic data?
- what are the expectations for acting on the data? 
   - and who has the responsibility?
- dual mode only?
   - can we differentiate feedback from beta sites vrs fully in prod?

The timeline for this implementation is based on
- number of VISNs rolled out
- availability of instant publishing

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@joanneesteban @jwoodman5 - want to make sure this one is on the radar

**Comment by jwoodman5** [comment]
Hey @mmiddaugh - this was not on my radar, so thanks for calling it out. Do you have any idea on when we will hit the number of VISNs rolled out? Or are we there already? And for instant publishing as well...? Thanks.
