### ISSUE TITLE
Python Upgrade (2.7 End of Life) [Pipelines, VMs] 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#13725]
**Need to upgrade python from legacy version to ensure stability and inter-operability of major infrastructure software components** 

- This epic needs careful consideration and planning because of the potential impact to essentially all of the core infrastructure. 
- Need to develop strategy for breaking this in to several chunks of work
- Understand how to mitigate impact by having multiple versions of python running in parallel 

**Next Steps:** 

1. Need to perform inventory of exactly which components this will affect (Demian to help kick start this work) 
2. Operations team to set up meeting to flesh out this epic with tickets and details for areas of concern and granular tasks 

Notes: 
Amazon Linux 1 EOL December 31, 2020 - can't use YUM on Amazon Linux 2 if you're using Python 3

**Comment by jhouse-solvd** [comment]
Jesse to create first ticket: 

Need to perform inventory of exactly which components this will affect (Demian to help kick start this work)

**Comment by jbritt1** [comment]
Closing at this time. Please see [ADR-0003](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/adr/0003-continue-leveraging-python-2.md).
