### ISSUE TITLE
Page reloads/navigation events can lead to a user getting logged out of VA.gov

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#13720]
## What happened?
It's possible to get signed out of VA.gov by simply reloading the page at the wrong time.

In this GIF I'm just hitting ⌘R a few times to reload the page quickly. This eventually leads to me getting signed out.

![logout-on-reload](https://user-images.githubusercontent.com/20728956/93623287-59c7da80-f993-11ea-8982-5bf6f1b539c0.gif)

The reason for this seems to be the `initializeProfile` action creator (https://github.com/department-of-veterans-affairs/vets-website/blob/ba8ab7006bd1d5c870cc6be041e97fbb85d26421/src/platform/user/profile/actions/index.js#L43-L53) that's fired by the `Main.jsx` component (https://github.com/department-of-veterans-affairs/vets-website/blob/59227d4c3013ecfb49d49a91bc54674b062539c6/src/platform/site-wide/user-nav/containers/Main.jsx#L75).

High level summary of what's happening:
- A page loads, which in turn triggers a call to `GET user/`
- If a browser navigation event or reload happens before the `GET user/` call resolves, that call is cancelled by the browser
- A cancelled `GET user/` call is treated is an error which results in the user getting logged out.

A potential solution to this _might_ be to make the `initializeProfile`'s `catch` handler a little smarter skip the logout process if the caught error is from the request being cancelled by the browser.

[This issue was originally discovered due to a FE redirect](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13625) that is being used while Profile 2.0 is being rolled out to some users. We thought it might have to do with the redirect itself and [implemented a hacky fix](https://github.com/department-of-veterans-affairs/vets-website/pull/14291) that essentially slows down the redirect so it doesn't happen while the `GET user/` call is in flight.

## Specs:
- Device: MacBook
- Browser: Chrome, but it happens in any browser
- Test User: Any user in any environment

## Steps to Reproduce
1. Sign into VA.gov with any user in any environment
2. On any page, hit the `reload` keyboard shortcut (⌘R on Mac) quickly

## Desired behavior
You should not get signed out simply because you reloaded the page quickly

## Acceptance Criteria
- [ ] Don't get logged out just because a `GET user/` call was cancelled by the browser
- [ ] Other `GET user/` call failures should still result in the user getting logged out

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by erikphansen** [comment]
@jholton Rian tells me you are leading a team that might be responsible for handling this bug so I assigned it to you. Let me know if you need any more info!

**Comment by jholton** [comment]
In my experimentation I've found that if you logged in with the legacy (`v0`) flow, this bug occurs as described.  You get logged out.
If you logged in with the new SSO flow (`v1`), you get logged out, but then the frontend immediately auto-logs you back in.  
I'm not saying this is fine behavior; just noting a difference depending on which login flow the user used.

**Comment by erikphansen** [comment]
hmm that might explain why I've also gotten stuck in an endless logout/login/logout loop

**Comment by erikphansen** [comment]
I just replicated the auto-login after logout behavior like you described. And I think it was the FE redirect I had in place that caused the endless logout/login/logout loop I was seeing in staging.

**Comment by jholton** [comment]
> And I think it was the FE redirect I had in place that caused the endless logout/login/logout loop I was seeing in staging.

You say "was" instead of "is".  Does that mean the FE redirect you mention has been removed?  
Do you have a link in code to the redirect in question?

**Comment by erikphansen** [comment]
I implemented a fix that essentially delays the FE redirect that prevents the logout from happening. I'm also guessing that that's what caused the endless loop. Eric Buckley saw it as well. Honestly I saw a lot of inconsistent behavior that was really confusing until I was able to figure out what was really going on. So I don't have a lot of details about the endless loop since it was hard to replicate or diagnose.

**Comment by AGarcia-Clarity** [comment]
#### Findings
Initially I started going the rabbit hole refactoring the `apiRequest` method to include an AbortController and binding the results to the response object. In the end it got super complicated and a lot of breakpoints were not stopping so I decided to scrap it. Instead I took what Erik mentioned about making the catch statement a little smarter.

Currently, what I have is a conditional to check if the error is a TypeError and has a `Failed to fetch` message else we teardown the profile.  Inside the conditional, I essentially use another try/catch to call it one more time to ensure we have the profile data otherwise we teardown the profile.

I'll push up what I have as I'm sure there are better/more efficient ways.
