### ISSUE TITLE
Exclude Mobile Vet Centers from Facility Locator search results

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13730]
## Issue descriptions
Mobile Vet Centers are currently included in Facility Locator search results and have detail pages. This is undesirable because
- They are more an extension of a brick and mortar Vet Center than a location in themselves
- Vet Center staff are not updating the facility operating status for mobile units.
- Due to their mobile nature, the location and hours of operation change so the detail page information is likely to be incorrect or out of date. 

The relevant data element within the Facilities API properties is `mobile`
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/272548f8-1f89-439f-bbea-5b712f2d885a)

## Tasks
- Exclude mobile vet centers from Facility Locator search results. 

## Acceptance 
- If **Facility type = Vet Center** and `mobile = true`, the location should be excluded from Facility Locator search results.

**Comment by mmiddaugh** [comment]
FO needs to pass parameter to display mobile = false 
BO needs to filter Vet Centers based on mobile parameter

**Comment by mmiddaugh** [comment]
change parameter language to say "hide" (or similar)

**Comment by brangi** [comment]
@darkbushido The request will look like  

`https://dev-api.va.gov/v1/facilities/va?bbox[]=-98.45&bbox[]=29.59&bbox[]=-96.95&bbox[]=31.09&type=vet_center&page=1&per_page=20&exclude_mobile=true`

**Comment by brangi** [comment]
Frontend change merged

**Comment by mmiddaugh** [comment]
Mobile Vet Centers are no longer included in the search results.
