### ISSUE TITLE
VSA Onboarding - Dillo Raju

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#13739]
## Welcome to the VSA Program

Welcome! This issue will be used to track your onboarding to the VSA Program.

---

## Pre-Onboarding

**Operation Lead Tasks**

- [x] Send Welcome email to New Hire (request GitHub Username)

*Send Notifications with New Hire details (name, position, start date) to:*

- [x] Admin Analyst
- [x] VA Leadership
- [x] VA PO
- [x] Practice Lead
- [x] VSP Onboarding

**Access, Paperwork and Program File Updates**

- [x] Access to [Shared Google Drive](https://drive.google.com/drive/u/1/folders/0ACZ1e6Rs_6sDUk9PVA)
- [x] Access to VSA PTO Calendar
- [x] Access to VA Organization in GitHub [#4323](https://github.com/department-of-veterans-affairs/github-user-requests/issues/4323)
- [x] Access to VSA GitHub Repositories
- [x] Access to GCIO/AdHoc Slack Workspace
- [x] Access to DSVA Slack Workspace #13743
- [x] Request Hardware/Software (remove if non-GCIO)
- [x] Request New Hire to Complete VA Onboarding Paperwork (GCIO Admin Analyst)
- [x] Schedule Program Overview Meeting

---

## Onboarding

**New Hire Tasks**

*Day 1*
- [x] [Watch Chris Johnston va.gov Backgrounder recording](https://drive.google.com/file/d/1BTYPaR0p9hYD4qd-OCCduyIRTRr77S1O/view?usp=sharing)
- [x] Attend VSA Program Overview Meeting
- [x] Make Calendar Public (Free/Busy)
- [x] Complete VA Onboarding paperwork (sent by Admin Analyst - Victoria Akitobi)

*Month 1*
- [ ] Complete Skill Matrix (GCIO only, sent by @yanaroy)
- [ ] Request SOCKS Access, after SAC Adjudication
- [ ] Complete VSP Orientation (Andrea Hewitt)

**Operation Lead Tasks**

- [x] Inform Practice Lead, Product Manager to trigger communication
- [x] Conduct VSA Program Overview Meeting
- [x] Update Org Chart and Share with New Hire
- [x] Add New Hire to #va-vsa
- [x] Send out org announcement on #va-vsa
- [x] Request New Hire to Complete Skills Matrix (GCIO only)
- [x] Add New Hire to Program-wide Meetings
- [ ] Add New Hire to The Platform Newsletter (James Chaisa)

**Practice Lead Tasks**

- [x] Send Intro Comms to New Hire
- [ ] Conduct Practice-specific Onboarding Meeting with New Hire
- [x] Add New Hire to Practice-specific meetings

**Product Manager Tasks**

- [x] Send Intro Comms to New Hire
- [x] Conduct Intro Meeting with New Hire
- [x] Add New Hire to Product team meetings

**Program Manager Task**

- [x] Check in with New Hire

**Comment by azwilling** [comment]
Welcome, Dillo!
