### ISSUE TITLE
IA feedback - Design intent - Vet Centers facility pages

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#13745]
**Feedback framework**
- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This ticket contains the IA feedback/guidance for the Facilities [Vet Centers] Design Intent Collaboration.

**QUESTIONS**
- Will these facilities require an operating status page similar to the health facilities?
- Are any of the "highlight" blocks on the page clickable?  If so, will they go to existing content pages or would they be additional content for this specific facility?

**MUST**
- Show breadcrumb within design (it may be accounted for in the mast head, but it is an element that will need to be figured out as part of this work)

**SHOULD**
- Start to think about how users will arrive at and navigate out of these pages - should they be part of the facility locator tool or do they live as independent pages that FL just links to (like vamcs).  This will help formulate entry points, URLs and breadcrumbs. 
- Work through a mobile version of the wireframe to create a content hierarchy and structure - this is another way of exploring whether content needs to be broken up into supporting pages or can be fully contained in a single landing page. 
 
**CONSIDER**
- As you work through content needs and determine if there may/should be more than 1 page, please reach out so we can work through what a core "site template" might look like, which will help define what a potential left nav component and breadcrumb implementation. 

## Definition of Done
- [ ] Review and acknowledge feedback
- [ ] "Must" feedback is incorporated into designs/work
- [ ] Decisions on Should and Consider feedback and any question responses documented in issue
- [ ] Issue is closed by VFS team once complete

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by mmiddaugh** [comment]
"Must" feedback has been added as Acceptance Criteria for next iteration (which will follow Veteran research sessions)
All other suggestions have been added to the description of that issue for reference and consideration during
