### ISSUE TITLE
UAT: form detail page for 22-1995 - copy update

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13753]
## UAT: form detail page for 22-1995 - copy update

**On the form detail page for VA Form 22-1995**
https://www.va.gov/find-forms/about-form-22-1995/

UAT feedback Cindi Quattrini:

Please remove this bullet: ` ‘Reentering a program that you previously left due to issues with attendance, progress, or conduct.’  `The form is no longer required for this purpose(CQ)'

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/fec17f16-18a4-4acd-9823-217e51771f45)

ETA:  This should be completed any time before we remove basic auth.

**Comment by lunascoop** [comment]
This change will be published and validated later today.

**Comment by lunascoop** [comment]
Validated
