### ISSUE TITLE
UAT: form detail copy update for 22-1990E

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13754]
## UAT: form detail copy update for 22-1990E  

_~Currently awaiting clarification from Cinda Quattrini wrt her UAT comments.~ Confirmed._

On this form detail page https://www.va.gov/find-forms/about-form-22-1990e/ 

1/ 
**Current text:** 
Use VA Form 22-1990E if you want to transfer your unused Post-9/11 GI Bill benefits to your spouse or dependent children.

**Change to:**
Use VA Form 22-1990E if your spouse or parent has transferred Post-9/11 GI Bill benefits to you, and you need to apply for a Transfer of Entitlement (TOE).

**2/ In the Helpful links section**

Replace the current GI BIll benefit links with these 4 family member benefit links:

**Survivors’ and Dependents’ Educational Assistance** 
https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/ 
Learn about the Survivors’ and Dependents’ Educational Assistance (DEA) program. If you’re eligible, you may be able to get help paying for school or job training through the DEA program (also called Chapter 35). 

**Fry Scholarship** 
https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship 
Learn about the Marine Gunnery Sergeant John David Fry Scholarship for children and dependents of Veterans.

**Reallocating Post-9/11 GI Bill benefits if a family member dies**
https://www.benefits.va.gov/GIBILL/FGIB/Reallocation.asp#:~:text=The%20Harry%20W.,who%20had%20unused%20transferred%20benefits.
 Learn how to transfer unused Post-9/11 GI Bill benefits if the Veteran, service member, or dependent beneficiary has died.  

**VA benefits for spouses, dependents, survivors, and family caregivers** 
https://www.va.gov/family-member-benefits 
Learn about benefits for spouses, dependents, and survivors. If you’re caring for a Veteran in your family or shared home, you may also be eligible to receive certain benefits.

**Comment by jenniferlee-dsva** [comment]
^ has been confirmed with EDU stakeholders. 

When this is live, please let the following stakeholders know with auth info:
U: veterans + P: am3rica

- Tammy Hurley
- Lucas Tickner
- Joseph Welton
- Cinda Quattrini

**Comment by lunascoop** [comment]
This change will be published and validated later today.

**Comment by RLHecht** [comment]
@lunascoop I just reviewed this. I lowercased the "e" at the end of the form name to be consistent with the H1 and the forms database. I set it to publish.

**Comment by lunascoop** [comment]
Changes are live and validated. Closing ticket.
