### ISSUE TITLE
UAT: form detail page update for About VA Form 40-10007 pg

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13751]
## UAT: form detail page update for About VA Form 40-10007 pg

Current URL is set to:  https://va.gov/find-forms/about-form-va40-10007/

Update URL to: VA.gov URL: https://va.gov/find-forms/about-form-40-10007/   <-- Remove the "va"

This is NOT a form that impacts @mnorthuis 's redirects (bc it's not one of the 1:1 redirect forms), but we should make this URL update before basic auth is removed for full launch. (I.e., can be completed after batch 2 hidden launch.)

**Comment by jenniferlee-dsva** [comment]
In CMS: http://preview-prod.vfs.va.gov/preview?nodeId=6053

**Comment by lunascoop** [comment]
This change will be published and validated later today.

**Comment by lunascoop** [comment]
URL updated and validated
