### ISSUE TITLE
Debt Letters I2 Create Content for diary codes, debt status 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13765]
As a Veteran who has debt I would like to know the status of my debt and what my actions should be . The status is recorded in DNC database in diary code field, multiple diary codes can be the same status category. 

Attached spreadsheet has diary codes with explanation and roll up categories [https://app.zenhub.com/files/133843125/7d829149-fc88-4db7-8801-89e89e198828/download](https://app.zenhub.com/files/133843125/7d829149-fc88-4db7-8801-89e89e198828/download)

**Comment by leahkeeler** [comment]
HI Peggy, I was wondering if you had a projected completion timeframe for this, I know it's a lot, but it would help me coordinate requesting QA and stating review for this iteration.

**Comment by leahkeeler** [comment]
[https://app.zenhub.com/files/133843125/8585040e-7bdd-4f67-9584-d0d10a67b719/download](https://app.zenhub.com/files/133843125/8585040e-7bdd-4f67-9584-d0d10a67b719/download)

**Comment by peggygannon** [comment]
Hi, @leahkeeler I'll be taking a look at this with Danielle. I should be able to provide you an eta after that, sometime tomorrow.

**Comment by leahkeeler** [comment]
Thanks-you so much!!!!!! really appreciate all the help and support on this

**Comment by peggygannon** [comment]
Hi, @leahkeeler, an update and two questions

Update: Danielle and I sync'd this morning and we are aiming to get our feedback back to you by Monday. 

Questions:

--what will be the design patterns for these status messages? 

--in the spreadsheet,  are the current headers listed under the Status column also part of the external-facing message? or is that an internal message/status?  (for example, for this message below  should "Pending Veteran deployment verification" be part of the external-facing message? )

![image.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/725e043b-d235-4113-86be-bb3003a21a9e)
![image.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/4348a465-bff7-4d86-9b46-2f44b5a8e989)

**Comment by rebeccawalsh** [comment]
@peggygannon 

Here are how they display in the designs, with the initial ideas for content:
**- Debt card on the list page, when there is a next step for the Vet:** ([UXPin link](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263526/specification/sitemap?mode=i))
![image](https://user-images.githubusercontent.com/6361930/94056876-d8b27e00-fdac-11ea-9be4-6bad9191fceb.png)

**- Debt card on the list page, when there is no next step for the Vet:** ([UXPin link](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263526/specification/sitemap?mode=i))
![image](https://user-images.githubusercontent.com/6361930/94057034-0dbed080-fdad-11ea-8f3e-e1faf679f2cb.png)

**- On the detail page, when there is a next step for the Vet:** ([UXPin link](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263534/specification/sitemap?mode=i))
![image](https://user-images.githubusercontent.com/6361930/94057078-2333fa80-fdad-11ea-8fe6-296d21d9b1eb.png)

**- On the detail page, when there is no next step for the Vet:** ([UXPin link](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263539/specification/sitemap?mode=i))
![image](https://user-images.githubusercontent.com/6361930/94057141-36df6100-fdad-11ea-8364-8df355cccedf.png)

We are open to guidance on whether or not a separate status and next step/alert is necessary. We've gone back and forth and will do whatever makes sense with the final content.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. I'm reviewing and editing Peggy's draft today and aiming to send you a final version (likely with a few open questions) by EOD. Thanks!

**Comment by leahkeeler** [comment]
Thank-you @DanielleThierryUSDSVA - appreciate all the help on this :)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. Here's the edited document (edited content for status in column C and edited content for next step in column E). 
From the designs, it looks like there may be cases where we may need some more content for a detail page. This isn't entirely clear, so just let us know as design progresses. Thanks!

[Debt letter statuses.content edits 9.29.20](https://app.zenhub.com/files/133843125/47912cdf-9836-46e7-897a-6fda05bcb230/download)

**Comment by leahkeeler** [comment]
Thank-you @DanielleThierryUSDSVA! @bradl3yC - assigning the ticket to you for status ocntent.

**Comment by leahkeeler** [comment]
Hi @peggygannon - here are the edits from DMC - nothing major - they really want that email address instead of phone number lol. Can you please review? cc: @craigwheeler - Once @peggygannon reviews this will be the final version to add. [https://app.zenhub.com/files/133843125/20f21d8a-2b36-48da-8724-782c5957f7ce/download](https://app.zenhub.com/files/133843125/20f21d8a-2b36-48da-8724-782c5957f7ce/download)

**Comment by peggygannon** [comment]
hi, @leahkeeler this is on my list to review today!

**Comment by peggygannon** [comment]
Hi, @leahkeeler Let me know if you have any questions. I reverted back some of the DMC edits to follow our VA.gov styling. 
[Debt letter status.final.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5387569/Debt.letter.status.final.xlsx)

**Comment by leahkeeler** [comment]
Thank-you so much @peggygannon 🥇 @craigwheeler - This is ready to go for iteration2 :)

**Comment by craigwheeler** [comment]
Hey @leahkeeler  ... maybe im missing it but after looking at the latest revision I only see content for `Next step` and would just like to confirm what should be used for `Status`?

**Comment by craigwheeler** [comment]
The status shown on the card is coming from [mockResponses.js](https://github.com/department-of-veterans-affairs/vets-website/blob/dd14d78c992070dea49488c14407bba2cc67e99c/src/applications/debt-letters/utils/mockResponses.js#L43) but that file only appears to show mock data?

**Comment by bradl3yC** [comment]
It comes from the API

**Comment by peggygannon** [comment]
hi, @craigwheeler here's updated spreadsheet. Let me know if anything is unclear.

[https://app.zenhub.com/files/133843125/8dc4fe31-6726-4aa8-b5c2-59860f7aaefa/download](https://app.zenhub.com/files/133843125/8dc4fe31-6726-4aa8-b5c2-59860f7aaefa/download)

**Comment by 3obryandogs** [comment]
@peggygannon We need a generic status/next step in case an unknown diary code is received for debt letters. It hopefully won't be needed, but just in case ... Would the following be acceptable?

**Status:** We are here to help. **Next step:** Please [contact us through IRIS](https://iris.custhelp.va.gov/app/ask) or call us at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET.

**Comment by peggygannon** [comment]
HI, @3obryandogs do you have any more context on what would trigger an unknown diary code? It is a case where the API doesn't have any information about the user or the debt to show? I think we could provide a status that gives the user more info

Can you ask the developer is the below recommendations would be accurate for this use case?  

**Status** We don't have any debt information to show
**Next step:** If you have questions, please contact us through IRIS or call us at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET

Also, I had provided the team feedback earlier this week that the **Status** need to be plain language/user friendly. I saw a few statuses earlier this week that didn't include earlier edits and that seemed to be coming from an API.

**Comment by bradl3yC** [comment]
@peggygannon I would be happy to chime in on this.  Currently, the API just passes us diary codes and letter codes and we (you and team) have written content surrounding what those mean.  Currently if the API passes us a code that we have NOT accounted for, literally nothing gets displayed.  We just want a default case to avoid the possibility of blanks. 

Thanks for all of your work on this

**Comment by 3obryandogs** [comment]
This is how it was put to me - can we come up with default statuses / next steps in the event the DMC passes us back a diary code that we're not expecting "?”

I asked if the statement below would cover it. He responded that the page doesn’t ask for any information. But rather “this is just in the event they send us a diary code that we do not already have documented content for.”

Status: We need more information to help you. Next step: Please [contact us through IRIS](https://iris.custhelp.va.gov/app/ask) or call us at 800-827-0648<tel:8008270648> (or 1-612-713-6415<tel:16127136415> from overseas) to provide the needed information. We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET.

**Comment by peggygannon** [comment]
thanks, @bradl3yC would this status recommendation work for an unknown code?

**Status** We don't have any debt information to show
**Next step:** If you have questions, please contact us through IRIS or call us at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET

**Comment by bradl3yC** [comment]
@peggygannon works for me!

**Comment by rebeccawalsh** [comment]
@peggygannon I'm not sure if that fits the issue 100%. They will still see all debt information like amount, dates, history... we just won't know exactly what the diary code is. The DMC doesn't believe some of the excluded diary codes should ever come up, but we know that probably isn't true! They're thinking that the mistaken diary codes will be very temporary if they do come up, and the issue will resolve itself quickly. 

That's why we initially suggested that we tell them things are being updated and to check back in a week.

Do you still want to say "We don't have any debt information to show"?

**Comment by peggygannon** [comment]
hello, ok, so sounds like we **do** have a status in the spreadsheet that could apply to this? In the debt status spreadsheet (linked above), there is this content below. Can we use this? 

**Status** We're updating your account
**Next step** Please check back in 1 week for updates. If your account shows the same information then, call us at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET.

**Comment by rebeccawalsh** [comment]
@peggygannon Yep! That's what I included in this [ticket for FE here](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/16757). Thanks!
