### ISSUE TITLE
DebtRes FSR - Create research plan - Veterans

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13767]
Create research plan to to understand how to design online FSR form that veterans can fill out on-line. 

Story - As a veteran I want the ability to fill out the FSR form on-line to start my debt resolution process. I want to understand: 

- Which resolution path is the right one for me (waiver, compromise, monthly off-sets) 
- I want to be able to fill out the form correctly so the process is not help up.

**Comment by rileyorr** [comment]
I added [the research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/dec-2020/research-plan.md) to GH
