### ISSUE TITLE
9.21.20 COVID-19 updates for Coronavirus research landing page, FAQs, and chatbot

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#13768]
## Issue Description
We need to update COVID-19 communications to support the coronavirus research volunteer list form launch, the change to the chatbot CDC exist messages, and some minor maintenance content tweaks.

---
### Coronavirus research landing page

*Note: This page is currently behind password authentication. So we can save all edits as published, and don't need to use drafts for now.*

- [x] Update landing page to match JTF submission doc (Danielle)
- [x] Change link to form from staging.va.gov/coronavirus-research/volunteer/ to /coronavirus-research/volunteer/. (Danielle)
- [x] Final proof - for errors and omissions + link check only (Randi)
- [x] Incorporate any JTF changes (Danielle) - Approved with no changes
- [x] Final proof - for errors and omissions of JTF changes - Approved with no changes
- [x] IRB approval - Approved with no changes
- [x] Add buttons back and set to publish (Danielle)
- [x] Validate on live site (Danielle)

### Coronavirus FAQs page

- [x] Add FAQ update + new FAQ to match JTF submission doc (Danielle)
- [x] Incorporate minor content maintenance tweaks (Danielle)
- [x] Final proof - for errors and omissions only (Randi)
- [x] Incorporate any JTF changes (Danielle) - Approved with no changes
- [x] Final proof - for errors and omissions 
- [x] Set to publish (Randi) 
- [x] Fix link (Randi)
- [x] Validate on live site (Danielle/Randi) 

### Coronavirus chatbot

- [x] Add FAQ update + new FAQ to match JTF submission doc (Danielle)
- [x] Update all CDC exit messages to new generic message (Danielle)
- [x] Incorporate minor content maintenance tweaks (Danielle)
- [X] Final proof - for errors and omissions only (Randi)
- [x] Incorporate any JTF or IRB changes (Danielle) - Approved with no changes
- [x] Final proof 
- [x] Hand off to Thoughtworks team (Danielle)
- [x] Validate on staging (Danielle)
- [x] Validate on live site (Danielle) 

### Coronavirus research volunteer list landing page

**Drupal node** = 6785

### Coronavirus FAQs

**Drupal node** = 3014

### Coronavirus chatbot

**Branch and content folder:** https://github.com/department-of-veterans-affairs/covid19-chatbot/tree/9.21.20-updates-covid-research-and-cdc-exit-msg/content

**PR:** https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/327

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht This is the work we talked about for first thing Monday morning. We haven't gotten the final approval from JTF yet. So, if they come back with additional changes, I'll add those and we'll need one final E&O check of those changes. Thank you, as always, for your help!

@batemapf CC'ing you here so you can track progress as well. We're all set for Monday's launch (pending we get JTF approval, of course). Randi will do a final proof, and we'll coordinate publishing/hand-off to chatbot team. Thanks!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA I reviewed this and made a few copy edits throughout. let me know if you have any questions.

**Comment by DanielleThierryUSDSVA** [comment]
Update: We just received JTF/OPIA approval on separate updates for the coronavirus FAQs page. So I need to revert to the latest published version and input the other updates...and then will need to re-input the research updates. @RLHecht I will let you know when this is ready for your eyes again :)

FYSA @batemapf

**Comment by DanielleThierryUSDSVA** [comment]
**9/30/20 update:**

- Landing page: Received IRB approval with no changes and published on 9.30.20.
- FAQs page: Received IRB approval with no changes and published on 9.30.20. Link pointing to form rather than landing page. Fixed and need to validate 10.01.20.
- Chatbot: Created new, clean branch/PR with approved updates. @RLHecht Could you give this a quick look in the morning? And then I'll let the ThoughtWorks team know it's ready. Thanks!

FYSA @batemapf @MickinSahni @brianalloyd

**Comment by RLHecht** [comment]
@DanielleSoCompany These changes all look good to me.

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @RLHecht @brianalloyd @MickinSahni Work complete. Closing ticket.
