### ISSUE TITLE
Develop a test for comparing CMS build outputs in Jenkins

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#13762]
**This ticket was originally intended to determine whether content validation script for build separation can be reused for transformers.**

The content build separation work requires content validation, which @billfienberg wrote up a full design doc for: https://github.com/department-of-veterans-affairs/va.gov-team/pull/9658

The CMS Export Build release also requires content validation. Can we reuse the same solution, or otherwise tailor the solution from content build separation work to cms export build work? 

Please connect on this Q and record your findings here. 

--- 

Notes from Eugene: 

Test script will probably work similarly to the diffs used during development.
Could potentially make it more sophisticated by checking DOM equality rather than just comparing content hashes.

Secondary comparison plan documented in separate ticket.

### Open Questions 
- [ ] What will trigger the comparison? 
- [ ] 

### Definition of Done 
- [ ] Open questions are answered
- [ ] Primary solution for comparing build outputs is determined, and is documented as part of CMS Export Build release plan
- [ ] All necessary artifacts (such as comparison scripts) are created

**Comment by joanneesteban** [comment]
@U-DON - Checking in to see if any progress has been made on this transformers ticket.

**Comment by U-DON** [comment]
Draft PR is available here:
https://github.com/department-of-veterans-affairs/vets-website/pull/15236

Will continue to iterate on it a bit more before opening it up for review.

**Comment by mpelzsherman** [comment]
We need to handle the following patterns of diffs that generate "false positives" when comparing the cms-export and graphql builds:

- entity id's are added to some elements in the cms-export builds only. (We could also address this on the graphql side, or remove the entity id's from the templates where they aren't needed.)

- There are several cases of whitespace-only diffs. These should be ignored.

- The CMS build adds an unnecessary meta tag. I've created a [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17065) to remove this.

- Some pages are created only by the cms-export build. These need to be investigated to see if they are really needed.

**Comment by mpelzsherman** [comment]
It would be great if we could add some way of filtering the output so we can see just the facilities-related diffs, for example.

**Comment by meganhkelley** [comment]
@theodur working on this now

Re: what will trigger this, likely part of CI and will be triggered by commits that change content

**Comment by meganhkelley** [comment]
@theodur could you please update the estimate based on the new approach of comparing JSON?

**Comment by meganhkelley** [comment]
Consider using tiered approach: html comparison script, and then running json comparison script on discrepancies that are found

**Comment by meganhkelley** [comment]
Theo updates

1/14: Worked in modifying the output of the script
Did some refactoring of the script

1/15: Work on adding functionality for running sequentially on all parent nodes

**Comment by meganhkelley** [comment]
Comparison tool complete and documented, further iterations will be tracked in separate tickets
