### ISSUE TITLE
Verify hyperlinks in Product Development Checklist are functional

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#13770]
## Issue Description
The [Product Development Checklist ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md)may be out of date with broken hyperlinks to supporting documentation. The links need to be verified to ensure they are still linked to the correct supporting documentation.

---
## Tasks
Verify all hyperlinks in document link to the correct documentation.

## Acceptance Criteria
VFS teams will have an accurate checklist to use to ensure that all necessary steps have been taken with each feature release.

---

**Comment by allison0034** [comment]
Made changes to plain language, unit testing and google analytics.
https://github.com/department-of-veterans-affairs/va.gov-team/pull/16173
