### ISSUE TITLE
[Development] BDD: Disability compensation, active duty, then reserves

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#13773]
Have we properly taken into account veterans who are BDD for active duty but then enter the reserves?

<img width="1260" alt="Screen Shot 2020-09-21 at 11 18 43 AM" src="https://user-images.githubusercontent.com/19188/93785715-669b3700-fbfc-11ea-9c26-2162b53f4197.png">

then later....
<img width="581" alt="Screen Shot 2020-09-21 at 11 25 43 AM" src="https://user-images.githubusercontent.com/19188/93786369-3c964480-fbfd-11ea-9238-dcf2e398e6cf.png">

and after that...
<img width="581" alt="Screen Shot 2020-09-21 at 11 28 01 AM" src="https://user-images.githubusercontent.com/19188/93786682-9a2a9100-fbfd-11ea-9c01-4119f78ec9a0.png">

**Comment by luke-gcio** [comment]
Intent is to do some discovery during sprint 31 but this is NOT a launch blocker.

**Comment by annaswims** [comment]
From form 526:
<img width="745" alt="Screen Shot 2020-09-22 at 10 19 17 AM" src="https://user-images.githubusercontent.com/19188/93908125-4175f980-fccc-11ea-8bae-f61c42d8dd38.png">

**Comment by luke-gcio** [comment]
Still have questions on FULL TIME ACTIVE DUTY RESERVES or whether that is possible.
