### ISSUE TITLE
Iteration on VAOS content, flows, & experience (based on recent feedback)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13777]
### Learnings
Recent testing showed us that:
- our current content/instructional information in the flows can be overwhelming or too ambiguous - need to focus on being more direct and simplifying
- observed areas for improvement in the flows (type of care page, facilities page, calling our request)

### While we look at making bigger changes to the Appointments homepage/dashboard, we can make some slight tweaks to the in flow experience:
1. Update "schedule an appt" to "Request an appt" especially right now since self-schedule isn't enabled
2. Type of care page - add supporting text to type of care labels & add way to 'call directly your VA' if not seeing care type
3. Review all alerts - make sure they are directing user to most appropriate path
4. Calendar updates:
     - On calendar selection page, add "next" button at bottom of calendar. Consider dynamic content for "next" button, replacing "next" with the following month name, for additional context.
    -  On calendar section page, provide content defining "AM" and "PM" to inform the decision a Veteran makes. For example, if an AM appointment is anything prior to noon, the calendar page should clarify.
5. Should we move 'reason for appt' up in the flow?

Supporting research documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/july-2020-user-research/2020-july-VAOSR-EC-research-report.md

**Comment by laurenernest** [comment]
Issues in this epic are complete. Closing ticket.
