### ISSUE TITLE
Facility-Locator - E2E tests QA feedback

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#13779]
**Feedback framework**

- [ ] **❗️ [Must](#%E2%9D%97%EF%B8%8F-must----user-story-test-gaps)** for if the feedback must be applied
- [ ] **⚠️ [Should](#%E2%9A%A0%EF%B8%8F-should----overall-feedback)** if the feedback is best practice
- [ ] **✔️ [Consider](#%E2%9C%94%EF%B8%8F-consider----suggested-negative-tests)** for suggestions/enhancements

# Facility-Locator E2E-Tests QA Feedback

Requesting ticket: #13384 

KUDOS to VSA Facilities team for improving E2E test coverage! It's great to see efforts made towards this end. The feedback given below is in the spirit of continuous improvement, and any issues mentioned are not meant to convey any negative assessment.

There are no launch blockers here, and the remediations under **Must...** are time-sensitive only with respect to the next VSP Usability Testing Prep \[see No. 2 in [VSP Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle-visual.pdf)].

## ❗️ Must -- User-story coverage-gaps

Remediate before next Platform Usability Test Prep for this product.

### VA facility search & results

[I'm combing search & results feedback here for the separate Use Case provided above]

Test spec-file: [search.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/tests/e2e/search.cypress.spec.js)

[See also **[⚠️ Should -- Overall feedback](#%E2%9A%A0%EF%B8%8F-should----overall-feedback)** below]

#### Vet arrives... [initial load]

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Facility-type default-option
- [ ] Facility-type options-list
- [ ] Search not initiated unless:
  - [ ] Location info entered [geolocation disabled/denied]; and
  - [ ] Facility-type selected

</details>

#### VA health facility-type selected

\[This feedback combines the 2 separate search Use Cases provided above (with the same title)]

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Service-type default-option
- [ ] Service-type options
- [ ] Alert below search-box
- [ ] Result cards:
  - [ ] Relevance? [not sure how we'll check this]
  - [ ] Distance
  - [ ] Address
  - [ ] Operating status? [cover IF you're mocking (and thus have control over) the data response]

</details>

#### VA benefits facility-type selected

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Facility-type default-option
- [ ] Facility-type options-list

</details>

#### VA benefits / Vet centers / VA cemeteries facility-type selected

<details>
<summary>Specific coverage gaps: [expand]</summary>

- [ ] Alert below search-box
- [ ] Results: \[see results-related gaps listed in **VA health facility-type selected** above, EXCEPT no need to cover Mental health number here]

</details>

#### Community providers facility-type, Dentist/Podiatrist service-type selected

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Alert hidden below search-box
- [ ] Result cards:
  - [ ] Relevance? [not sure how we'll check this]
  - [ ] Distance
  - [ ] Address
  - [ ] Directions
  - [ ] Main number
  - [ ] Referral text
- [ ] No Detail-page link

</details>

#### Community pharmacies facility-type selected

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Result cards:
  - [ ] Relevance? [not sure how we'll check this]
  - [ ] Distance
  - [ ] Facility-type
  - [ ] Services
  - [ ] Address
  - [ ] Directions
  - [ ] Phone number
  - [ ] Test to call to confirm hours and service
- [ ] No Detail-page link

</details>

#### Community care facility-type, Pharmacy - Community/Retail service-type selected

Entire Use Case not covered.

#### Urgent Care facility-type, All urgent care service-type selected

Entire Use Case not covered

#### Urgent Care facility-type, Community urgent care service-type selected

<details>
  <summary>Specific coverage gaps: [expand]</summary>

- [ ] Service-type default
- [ ] Service-type options
- [ ] Result cards:
  - [ ] Relevance? [not sure how we'll check this]
  - [ ] Facility-type
  - [ ] Services
  - [ ] Name of group/provider
  - [ ] Distance
  - [ ] Address
  - [ ] Directions
  - [ ] Phone number
- [ ] No Detail-page link

</details>

#### Community providers facility-type, Clinic/Center - Urgent Care service-type selected

Entire Use Case not covered

### Mobile

Test spec-file: [mobile.cypress.spec.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/tests/e2e/mobile.cypress.spec.js)

Detail-page Use Case not covered

### Overall feedback

**Context**: Unlike unit-test code-reviews in pull-requests, E2E-test coverage/results review audiences will likely expand to include non-technical & higher-level reviewers/stakeholders.

While much of the feedback below revolves around improvements to enable easy reviews by non-technical personnel, it should hopefully also facilitate test-code maitainability.

<details>
  <summary>Test suite and test structures/descriptions [expand]</summary>

- [ ] Test-Suites & Tests should be closely related to Use Cases and expected results, in terms of structure and descriptions:
  - [ ] Managers should easily determine which use cases passed/failed when checking test results
  - [ ] Engineers should easily determine which suites/tests to update when use cases change
  - [ ] Where separate Use Cases actually belong to a common User-flow, they're corresponding tests can be combined into a single suite/sub-suite. See suggested code-block below.

```javascript
describe('Facility search', () => {
  ...
  describe('Initied load', () => {
    it('should not auto-initiate search', () => {
      // assert empty location-input [geolocation disabled]
      // assert facility-type non-selection
    })

    it('should have expected facility-type dropdown default/options', () => {
      // assert default
      // assert options
    })
  })

  describe('VA health facility-type selected', () => {
    it('should have expected svc-type dropdown status/default/options'), () => {
      // assert enable/disabled status
      // assert default option
      // assert options list
    })

    it('should have/not have alert below search-box', () => {...})

    it('should have expected result-cards info', () => {
      // assert alert show/hide
      // assert map-icon
      // assert facility-name link
      ...
    })

    it('should have expected Detail-page contents', () => {...})
  })

  describe('VA benefits facility-type selected', () => {...})

  ...
})
```

</details>

<details>
  <summary>Selectors [expand]</summary>

- [ ] Selectors should target **data-testid** attributes wherever possible \[see [Cypress Best Practice](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements)]. Semantic values should be used for these attributes, to relate closely with expected-results (e.g., `data-testid="facility-link"`, etc.).
- [ ] With semantic `data-testid` attributes added:
  - [ ] These specific elements (currently targeting `.facility-result a`) should be asserted separately:
  - [ ] Facility-name link
  - [ ] Directions link
  - [ ] Main number link
  - [ ] Mental health number link
  - [ ] Other already-covered elements (currently targetting non-semantic selectors) should also target semantic `data-testid` attributes instead.

</details>

## ✔️ Consider -- Suggested negative tests

- [ ] Invalid location inputs:
  - [ ] Invalid zip
  - [ ] Spaces only
  - [ ] Garbage? (e.g., '@&#\*%')

**Comment by mmiddaugh** [comment]
Thank you, @tlei123! I'll put this feedback in an issue for the team to use in expanding our coverage even further.
