### ISSUE TITLE
STEM: Remove prod flag for form selection wizard STEM content update

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13781]
As a developer, I need to remove a prod flag so the updated content is available in the production environment.

## Assumptions:
1. The work completed in #12366 has been reviewed and signed off in staging as of 09/10/20

## Acceptance Criteria
1. The work completed in #12366 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14330

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
This is now in production. closing this issue
