### ISSUE TITLE
STEM: Update Personal Information Chapter Layout and questions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13784]
As an applicant, I need the completion and review of my Personal Information to be seamless and flow from start to finish so I do not have to review previously answered questions based on questions that follow.

## Assumptions:
1. This work is completed behind ~feature flag `stem_text_message_question` (#13826)~ a production flag

## Acceptance Criteria
1. The questions in Chapter 5, Page 1 are displayed in the following order:
    a. What's the best way for us to contact you?
    b. Country
    c. Street address
    d. Line 2
    e. City
    f. State
    g. Postal code
    h. Email address
    i. Re-enter email address
    j. Home phone number
    k. Mobile phone number
    l. I would like to receive text messages from VA about my GI Bill benefits
2. The following content is displayed after the last question:

    > **Note:** Text messages may include status updates or requests to verify school attendance or other GI Bill benefit information. Message and data rates may apply.

3. When the user answers the `I would like to receive text message from VA about my GI Bill benefits` question:
    a. The "Mobile phone number" question is marked required and the following message is displayed when triggered "Please enter a phone number".
    b. The following alert content is displayed below the question if the user did not enter a phone number prior to checking the box: `Since you've opted to receive text message updates, you need to enter your mobile phone number so we can send updates to your device.`
    c. The alert is no longer displayed once the user enters a valid "Mobile phone number"
4. The page matches the layout and structure as specified in Support Artifact #1

## Supporting Artifacts:
1. [Prototype v6](https://bahdigital.invisionapp.com/share/FAIAEVUYVKN#/screens/296049093) as of 09/21
2. [Content v6](https://github.com/department-of-veterans-affairs/va.gov-team/blob/e7b88bd6c48f5d61adfee110f63ef924058a25d7/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md#chapter-title--5-of-6--personal-information) as of 09/21
3. Mock Spool File Format: [10203_Spool_with_Twilio_20200921_story_version.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5257151/10203_Spool_with_Twilio_20200921_story_version.docx)

**Comment by elder-joseph** [comment]
The original assumption for this story was to be completed behind the `stem_text_message_question` feature flag. It has been determined that this would not be possible without wiring up a custom redux container for the form. A production flag will be used instead.

**Comment by elder-joseph** [comment]
Front End PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14405
Back End PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5003

**Comment by sonntag-adam** [comment]
Needs more space
![Screen Shot 2020-10-01 at 6.21.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8b405322-9fb2-4c9d-a1f7-d586fb0005ca)
##
Validation needs to say "Please enter a mobile phone number".
![Screen Shot 2020-10-01 at 6.31.44 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/dae4c6bd-0ac7-47b8-ad4f-1458a16fcc72)

**Comment by sonntag-adam** [comment]
moving back to in progress

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-01 at 11.58.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ab0236f3-a88a-4fa7-8a2b-9fd685414493)
##
![Screen Shot 2020-10-01 at 11.59.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c7323ff9-11ac-4331-8cd1-eff556d693ef)
##
![Screen Shot 2020-10-01 at 11.58.46 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0e5a2788-8076-478c-9a90-16112fd36a9a)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/12680&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
@@department-of-veterans-affairs/uxbah This is in staging and ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam This checks out for UXers!

**Comment by sonntag-adam** [comment]
Closing story, testing passes QA
