### ISSUE TITLE
Protecting and Sharing Health Information Verbiage on the Introduction Forms Page

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#13786]
**Description**

Current draft verbiage (a version shown in the screenshot below):

How will my personal health information be protected and shared if I use this clipboard?
The information that you enter will be shared with your provider’s office and added to your medical record. After it becomes part of your medical record, all VA providers will be able to view this information. You’ll have until [time period] before your upcoming appointment to submit this clipboard. This is a secure website. We follow strict security policies and practices to protect your personal health information.

Do we need the Veteran to acknowledge that this information will be protected and shared? Do we need to require that they check a check box? Would wording close to the "Start this form button" stating that "By starting this form, you are accepting that this information be sent to..." meet the VA's requirement? Is the above FAQ style information enough to meet the VA's requirement?

**Tasks**
- [ ] Craft verbiage
- [ ] Get appropriate approval for verbiage

**Acceptance Criteria**
- [ ] Finalized verbiage sent to Kristen McConnell to incorporate into wireframes

![Introduction - Reason for Visit - SignedIn EmergencyOption 2- Desktop.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/61af16cb-fded-4830-ac95-04d135e51774)

**Comment by LEHigley** [comment]
@lalexanderson-dsva is this something we would need to run past privacy?

**Comment by abuckley3385** [comment]
@LEHigley did you find out any more about this one?

**Comment by LEHigley** [comment]
yes sorry! just getting to this now. patrick said we should have the platform team do a privacy threshold assessment. the folks in the privacy office would ask about that assessment first.

**Comment by abuckley3385** [comment]
ok will get time set up with the privacy team

**Comment by abuckley3385** [comment]
thread in platform - https://dsva.slack.com/archives/C01CJV0L9PS/p1605634685052900

**Comment by leahkeeler** [comment]
Hi @mlighdc - do we have any path forward on this ?

**Comment by mlighdc** [comment]
Hi @leahkeeler and @kristenmcconnell, yes. Just got some feedback for some tweaks on the language. Once the tweaks are made, I will officially submit it to OGC for final review.

**Comment by jparker0425** [comment]
This is an older ticket that was handled per @kristenmcconnell. Closing out.

**Comment by mlighdc** [comment]
@jparker0425 This is done and language was provided to Kristen and Mark to update. The only thing I was not totally clear on was did we update for the whole platform or just Clipboard. I also think this was tracked with another ticket. @kristenmcconnell may you can link to we have a little bit of a trail if not already done. Thanks!

**Comment by kristenmcconnell** [comment]
Here are links to the finalized wording as shown in wireframes:
https://www.sketch.com/s/fd688be2-76eb-484b-a306-9c1b522f4f09/a/eKpo5gW
https://www.sketch.com/s/fd688be2-76eb-484b-a306-9c1b522f4f09/a/OmOnpym
