### ISSUE TITLE
Create FSR Prefill Form - VA Benefits Prefill Discovery [Backend]

### ISSUE THREAD

**Issue by camerontesterman** [department-of-veterans-affairs/va.gov-team#13789]

**Comment by camerontesterman** [comment]
@leahkeeler I am blocked on this right now as I don't know which business units offer which forms of compensation to the veteran which is necessary to complete this work.

**Comment by leahkeeler** [comment]
Let me see what I can find out. I am not sure we will be able to prefill this since the form cannot be changed and currently the fields are combined - but I do think it is worth having a conversation.
