### ISSUE TITLE
Meet with Platform team to discuss Pact work

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13790]
## Background
See ticket # VSA Auth Experience - Pact setup for [product name] #13336
We would like additional information regarding what is needed fort his work as well as breaking it out into multiple tickets.

## Tasks
- [ ] break out work into multiple tickets
- [x] Meet with platform team

**Comment by Samara-Strauss** [comment]
Adding sprint 31 milestone since this is happening on Monday.

**Comment by Samara-Strauss** [comment]
Has this work been broken into the tickets you need? If so, we can close this ticket.

**Comment by mshea0606** [comment]
yes, closing ticket

**Comment by mshea0606** [comment]
[FE] - Write Pact test #14233
 [BE] - Setup Pact test #14234
 Meet with Platform team to discuss Pact work #13790

**Comment by Samara-Strauss** [comment]
Great, thanks!
