### ISSUE TITLE
STEM: Remove 22-10203s from in progress applications that were purposefully exited 

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13794]
As a va.gov user, I need the 10203 to not show up in my in-progress applications if I have purposefully exited the application because I did not meet the eligibility criteria, so that my in-progress application list is accurate.

## Assumptions
1. This work is done behind a prod flag.
2. The in-progress applications are found here: https://staging.va.gov/my-va/

## Acceptance Criteria
1. The 10203 is not marked as an in-progress form when the applicant clicks the Chapter 2 `Exit application` button.
2. The 10203 is not marked as an in-progress form when the applicant clicks the Chapter 3 `Exit application` button.

## Tech Notes
1. There is likely an existing custom component that would support the work we want to do here. 

## Supporting Artifacts:
1. [Prototype v6 - Exit Application 1](https://bahdigital.invisionapp.com/share/FAIAEVUYVKN#/screens/296048644) as of 09/21
2. [Prototype v6 - Exit Application 2](https://bahdigital.invisionapp.com/share/FAIAEVUYVKN#/screens/296048679) as of 09/21
3. Screenshot of In-progress application card:
<img width="693" alt="Screen Shot 2020-09-24 at 8 33 21 AM" src="https://user-images.githubusercontent.com/48260534/94145529-afdbc880-fe40-11ea-99c1-bada389f788d.png">

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14418

**Comment by delli-gatti-michael** [comment]
Testrail test case:
https://dsvavsp.testrail.io/index.php?/tests/view/12690&group_by=cases:section_id&group_order=asc&group_id=51

local testing complete

**Comment by delli-gatti-michael** [comment]
Verified in Staging. Closing this issue
