### ISSUE TITLE
Extend the e2e for the 1990 to include login

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#138]
## Description
Before we build out a completely new e2e test for prefill, we want to extend the 1990 e2e to include login. This work is contingent on the discovery in #137 

## AC
- [ ] E2E test for login has been tested and merged

## Def of Done
- [ ] AC is complete
- [ ] connected to an epic

**Comment by annaswims** [comment]
it's worth  noting that the E2E testing @lihanli  is working on in vets-api includes login 
https://github.com/department-of-veterans-affairs/vets-api/pull/3102

**Comment by brandonrapp** [comment]
This work has been completed as part of #644 and thus we will be closing this issue out.
