### ISSUE TITLE
Accessibility feedback - Staging Review - Public Websites [Find VA Forms: Detail Pages]

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#13805]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This ticket contains the accessibility feedback/guidance for the Public Websites Find VA Forms: Details Pages Staging Review

Here's a list of prod urls for "top forms":

1. https://www.va.gov/find-forms/about-form-21-4138/
1. https://www.va.gov/find-forms/about-form-22-1995/
1. https://www.va.gov/find-forms/about-form-21-526ez/
1. https://www.va.gov/find-forms/about-form-21-2680/
1. https://www.va.gov/find-forms/about-form-10-7959c/
1. https://www.va.gov/find-forms/about-form-10-10d/
1. https://www.va.gov/find-forms/about-form-21-22/
1. https://www.va.gov/find-forms/about-form-10-5345/
1. https://www.va.gov/find-forms/about-form-20-0995/
1. https://www.va.gov/find-forms/about-form-21-686c/
1. https://www.va.gov/find-forms/about-form-10-0137/
1. https://www.va.gov/find-forms/about-form-21-0781/
1. https://www.va.gov/find-forms/about-form-21-0966/
1. https://www.va.gov/find-forms/about-form-21-0845/
1. https://www.va.gov/find-forms/about-form-22-5490/
1. https://www.va.gov/find-forms/about-form-26-1880/
1. https://www.va.gov/find-forms/about-form-10-2850c/
1. https://www.va.gov/find-forms/about-form-21-4142/
1. https://www.va.gov/find-forms/about-form-21p-0969/
1. https://www.va.gov/find-forms/about-form-21p-534ez/
1. https://www.va.gov/find-forms/about-form-10-10ez-espanol/
1. https://www.va.gov/find-forms/about-form-10-3542/
1. https://www.va.gov/find-forms/about-form-22-1990e/
1. https://www.va.gov/find-forms/about-form-22-1990n/
1. https://www.va.gov/find-forms/about-form-22-1990/
1. https://www.va.gov/find-forms/about-form-22-5495/
1. https://www.va.gov/find-forms/about-form-va40-10007/
1. https://www.va.gov/find-forms/about-form-21p-530/
1. https://www.va.gov/find-forms/about-form-21p-527ez/
1. https://www.va.gov/find-forms/about-form-10-10cg/
1. https://www.va.gov/find-forms/about-form-21-22a/
1. https://www.va.gov/find-forms/about-form-21-674/
1. https://www.va.gov/find-forms/about-form-21p-509/
1. https://www.va.gov/find-forms/about-form-10-0137-espanol/
1. https://www.va.gov/find-forms/about-form-10-0137a/
1. https://www.va.gov/find-forms/about-form-21-0781a/
1. https://www.va.gov/find-forms/about-form-21p-527/
1. https://www.va.gov/find-forms/about-form-21p-534/
1. https://www.va.gov/find-forms/about-form-10-10ez/
1. https://www.va.gov/find-forms/about-form-10-10ezr/
1. https://www.va.gov/find-forms/about-form-21-0779/

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by jenstrickland** [comment]
**Previously documented issues found** 

(Will add to this list as I work through the pages)

- CMS, components, design system — 508-defect-2 [KEYBOARD]: Landmarks MUST have a unique role or role/label/title (i.e. accessible name) combination; main nav and sidebar nav conflict - https://github.com/department-of-veterans-affairs/va.gov-team/issues/7723

**Comment by jenstrickland** [comment]
On https://www.va.gov/find-forms/about-form-21-2680/, it would be preferable if the download PDF links used the pattern that the VA design system is about to add: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340 

Download PDF Link Example
(size only if available, or an easy add to generate)

```
<a 
  href="https://www.va.gov/playbook/downloads/Voices_Of_Veterans.pdf" 
  download="Voices_Of_Veterans.pdf" 
  type="application/pdf">
    <i aria-hidden="true" class="fas fa-download vads-u-padding-right--1" role="img"></i>
      Download the Voices of Veterans <dfn><abbr title="Portable Document Format">PDF</abbr> (4.9<abbr title="Megabytes">MB</abbr>)</dfn>
</a>
```

**Comment by jenstrickland** [comment]
@brianalloyd — I'd like to consider the accessibility staging review complete at this time, if that's okay. A thorough audit will be conducted for the Full A11y & 508 Office Audit. Is that okay with you? I think the team is launching officially.

**Comment by brianalloyd** [comment]
@jenstrickland that works, team has officially launched.  Appreciate all the work and support on this initiative.

**Comment by jenstrickland** [comment]
I normally keep these open until all the issues within are closed. Does that sound 🍌 🍌 ? 😂
