### ISSUE TITLE
Predictive search (Facility Locator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13803]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Veteran, I need to receive meaningful search results relevant to the parameters I enter so that I can understand the results and choose from the facilities closest to me. 

## Current behavior
The input entered by the user can be misunderstood when they are passed to mapbox as geographic parameters. This results in the potential for a result list which is technically accurate but not as intended.

How can we ensure the parameters used for searching match the Veteran's intended input?

## Hypothesis or Bet
**If** _we implement geographic predictive search_ **then** _we TBD.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jilladams** [comment]
Now being tracked in a SPIKE around address auto-suggest, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19201, within the FL usability / a11y improvements epic.
