### ISSUE TITLE
Service-centric search (Facility Locator)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#13801]
##  Overview
It has long been recognized that the Facility Locator's facility-centric search is not consistent with the Veteran task-based mental model. 

## High Level User Story/ies
_As a Veteran, I want to be able to search by service so that I can find a location that can meet my need._

## Resources
**Related/Associated product(s)**
- [Facility Locator product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/product/facility-locator-product-outline.md)
- [Link to Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/service-centric-search/initiative-brief.md)

Ideas from Hackathon, November 2020
- [Leyda Hughes](https://preview.uxpin.com/c300973e45a11d90a87d54bc788f6461da080480#/pages/134295035/simulate/sitemap?mode=i)
- [Michelle Middaugh](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/images/ba3ed474-79a2-4bad-bb21-a5f04cf89402-original.pdf) 

### What is the problem and who is affected? And, what evidence do we have of the problem?

The Facility Locator currently forces Veterans to choose the type of facility they wish to search for. This assumes the following
    * Veterans understand the organizational structure at the VA
    * Services are offered at only one type of facility
    * Or that Veterans understand that they should perform more than one type of search to get a full list of options
    
Services are not fully or accurately mapped for all facility types. 
- The VA health service list has a small subset of the health service taxonomy and is not mapped for all facilities. For example, searching for VA health facilities offering emergency services will not return a list of all facilities known to offer this type of care and may include facilities which do not. 
- Benefit services are not listed in plain language and may not be complete. 
- Community care searches rely on a typeahead functionality powered by a clinical/billing taxonomy which is not at all Veteran facing and does not map to VA health services.

### How does this initiative help further OCTO-DE's mission and goals?
- OCTO-DE objective: Provide accurate health service information for local facilities 
- OCTO-DE objective: Help Veterans manage their health services online

## Hypotheses
* By implementing a service-centric search experience in the Facility Locator, we can return an accurate, complete and facility-type agnostic set of facilities offering the service a Veteran seeks

**Comment by jilladams** [comment]
Closing. New work in new epics.
