### ISSUE TITLE
DebtRes FSR Submission - Discovery

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13818]
Currently the paper form is scanned into .pdf, goes into a queue and is attached to case in caseflow Pega tool. Once the form is online, the data needs to integrate with a backend system. 

Discovery needs to be completed on what BE system the form data will flow to 
How to integrate with BE system chosem.

**Comment by camerontesterman** [comment]
Met with Pavan and Satish yesterday to further discuss the implementation of a submission endpoint. Agreement and understanding has been reached by both sides and we have a path forward -closing this ticket.
