### ISSUE TITLE
DebtRes Tech spike - eSignatures, authorizations

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13817]
Story: As a veteran who filled out the FSR on-line, I need the ability to e-sign or authorize the form before it is submitted. If I have a spouse I need to have the ability for my spouse to e-sign or authorize the FSR data as well. 

Tech Spike to investigate options for both logged in user and spouses to sign/authorize FSR before it is submitted.

**Comment by bradl3yC** [comment]
@leahkeeler currently there aren't any signatures in vets-website that I can see.. there is just a check box acceptance.  What level of validation do we need on the signature? Are there any standards that need to be met?  Do we know what format we need the signature in?

**Comment by leahkeeler** [comment]
All good questions. I think the potential blocker here is the spouse signature - we will need to work through this ...

**Comment by bradl3yC** [comment]
@leahkeeler We can add a signature component.  However, we're currently sending over a JSON payload to the DMC.  We can include a PNG image as a part of the payload by base64 encoding it to a string.  

I know caregivers stakeholders had some issues with allowing a 2nd signature - they currently do not have a drawn signature, they have a check box with an input field where they have to string match the name of the veteran and spouse.  I hope this helps.
