### ISSUE TITLE
va.gov cookie for sharing SAML Request metadata

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#13813]
The current workflow between vets-api and eauth.va.gov does not allow us to forward metadata attributes (eg transaction id, user action, client id, etc) in the SAML Request.  As an alternative we'd like to explore the option of setting that data in a shared `.va.gov` domain cookie that would give the eauth.va.gov service access when a new SAML Request is sent.

In the `V1::SessionsController` we should update the `render_login` method to set a `.va.gov` cookie.  The name of this cookie should include the environment name (eg `vagov_saml_request_dev`) so they don't conflict with one another across environments.  We will NOT be encrypting the cookie value, so nothing sensitive should be set.  For a test run the payload can just be an MD5 encoded JSON string with the following attributes.
- iso 8601 timestamp
- transaction id for user authentication (should generate a new value for this, unless we are upleveling in which case the previous transaction id should be used)
- saml request id
- saml request query params

**Comment by jholton** [comment]
@ericbuckley Can you help me out with a couple of definitions?
"saml request id" - Is this the `RelayState`'s `originating_request_id`?
"saml request query params" - What are these?

**Comment by ericbuckley** [comment]
@jholton the "saml request id" is just the `ID` attribute in the root node of the SAML XML payload.  We [store that in redis after creation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/saml/url_service.rb#L168) and [can be accessed from the controller using the redis tracker](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v1/sessions_controller.rb#L188).

"query params" are values like `op` and `clientID` that we want to pass through to ID.me.  They can be [accessed from url_service](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/saml/url_service.rb#L104)

**Comment by joeniquette** [comment]
-IAM and ID.me working on figuring this out. Waiting on Craig from the IAM team to respond to Tanels (ID.me) question about putting query params and IDs into the relay state (such as ops=signin)

**Comment by joeniquette** [comment]
Cookie attributes are being accepted and sent along to ID.me in dev as of 3/24. I am now working on queries for cloudwatch which will produce a 24 hour report of all transaction IDs. This report will then be transformed to isolate all missing responses (will include the authn to track which service is missing the response). The list of missing response `transaction_id`s for the 24 hour period will be then run against the ISAM logs in splunk, isolating the request being passed in, with an attempt to identify any missing requests from va.gov, missing responses from downstream services.

Once we have the list of missing `transaction_id`s we will then send this to id.me to help us understand if they have a corresponding saml request, then ask for logs of anything they have regarding the missing response transactions at the ISAM level.

Next, all responses which are sent by ID.me, but then not seen in ISAM splunk logs will be investigated. 

Finally, response logs which are shown by id.me and isam but then not in va.gov will be investigated (this will likely be a va.gov issue or networking between va.gov and ISAM.

**Comment by joeniquette** [comment]
Cookie data collection capability was confirmed as of 4/26/21.
