### ISSUE TITLE
DebtRes Integrate FSR with Vets API for contact data 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13815]
Story: As a Veteran who is authenticated on va.gov filling out the FST form I would like my contact data to be pre-filled. If the contact record is incorrect I would like to see links to update my contact record.

Acceptance criteria: For a test user logged into VA.gov, teh contact record fo rthe test user is prefilled.

**Comment by camerontesterman** [comment]
@leahkeeler is this any different from https://github.com/department-of-veterans-affairs/va.gov-team/issues/13769?

Looks the same. Can I close?

**Comment by leahkeeler** [comment]
ur right - close it
