### ISSUE TITLE
STEM: Create automated decision feature flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13829]
As a developer, I need a way to toggle the automated decision functionality, so that it can be turned on/off in environments as needed.

## Assumptions:
1. Feature flag for automated decision is needed the vets-api and vets-website repos.
2. The Feature Flag is configured per environment.
3. When the feature flag is:
     a. Off: The 10203 is completed entirely by the applicant.
     b. On: The 10203 automated decision functionality is enabled, and the application will exit at defined points.
4. The feature flag is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. The Feature Flag `stem_automated_decision` is available to be used for the submission enhancements.
2. The Feature Flag `stem_automated_decision` description is: "Add automated decision to 10203 application workflow"
3. The Feature Flag is created and available in all environments.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by ksantiagomorgan6** [comment]
FE PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15459
BE PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5561

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-12-22 at 8.21.24 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/82dd1566-c56e-4958-8c73-3231c3be4ca1)
##
![Screen Shot 2020-12-22 at 8.21.29 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a88b3bf4-fea1-4ca9-803d-86ae36728d72)

**Comment by sonntag-adam** [comment]
In staging and prod. Closing story.
