### ISSUE TITLE
STEM: Remove Text Message Question Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13827]
As a developer, I need to remove the feature flag for 10203 text message question because it will not be disabled going forward.

## Assumptions:
1. The feature flag was configured as part of story #13826.
2. This functionality has gone through UAT with EDU and been signed off on as of 10/15.
3. This functionality has been turned on as of 10/19 and no issues have been encountered.

## Acceptance Criteria:
1. The feature flag 'stem_text_message_question' is removed.
2. The feature flag 'stem_text_message_question' is not displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
`vets-website` PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14941
`vets-api` PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5278

**Comment by sonntag-adam** [comment]
Testing passes QA
