### ISSUE TITLE
Review of new short VSP policy (documenting our desire that VFS not use password protection)

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#13820]
### What is your documentation request, question, comment, or issue?

I wrote up some new policy, about how we'd prefer VFS teams not use password protection for VA.gov features, and I'd like to communicate this stance to DEPO, VSP, and VFS teams. The other DEPO leads are reviewing the content to see what suggestions they have to adjust the message, but I thought I'd go ahead and get it queued up with the Content & IA team as well in case a simultaneous tone and IA check can be done.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/pw-protection-usage/platform/working-with-vsp/policies-work-norms/usage-of-password-protection.md

Thank you!

**Comment by gmaciolek** [comment]
Updates proposed here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/914684114424e0d409749df19917ad7f8b8562f8/platform/working-with-vsp/policies-work-norms/usage-of-password-protection.md

https://dsva.slack.com/archives/CL181NRJQ/p1600722274008500
