### ISSUE TITLE
STEM: Add Text Message Question Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13826]
As a developer, I need a way to toggle when the new text message option question is displayed within the 10203 form, so that it can be delivered when EDU is ready to accept the data.

## Assumptions:
1. Feature flag for text message will need to be available in both vets-api and vets-website repos.
2. The Feature Flag is configured per environment.
3. When the feature flag is:
     a. Off: The 10203 "Personal Information" chapter has no changes.
     b. On: The 10203 "Personal Information" chapter includes the text message and layout changes.
4. The feature flag is displayed here: https://[environment]-api.va.gov/flipper/features.

## Tasks
1. Follow feature flags documentation to create front-endback-end text message feature flag.
2. Follow feature flags documentation to create back-end text message feature flag.

## Acceptance Criteria
1. The Feature Flag `stem_text_message_question` is available to be used for the text message enhancements.
2. The Feature Flag description is: "Add text message opt-in question to 10203 Personal Information chapter and layout changes"
3. The text message feature flag is created and available in all environments.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by ksantiagomorgan6** [comment]
Front end pr: https://github.com/department-of-veterans-affairs/vets-website/pull/14380
backend pr: https://github.com/department-of-veterans-affairs/vets-api/pull/4981

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-09-28 at 10.25.58 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a912031e-d4e2-4465-aee4-fe4c3564b4d5)

**Comment by sonntag-adam** [comment]
In staging and production. Closing story
