### ISSUE TITLE
FHIR Mapping for PGD

### ISSUE THREAD

**Issue by stephenBarrs** [department-of-veterans-affairs/va.gov-team#13833]
As an administrator of the MAP PGD, I need to understand what data fields will be captured by the Clipboard application, and how those data fields will be mapped to FHIR Questionnaire/Questionnaire Response Resources so I can confirm compliance with FHIR and PGD specifications.  Additionally, I need to know if any discreet data being captured should also be stored in other relevant FHIR Resources in PGD.

**Comment by stephenBarrs** [comment]
From the [MAP PGD wiki](https://wiki.mobilehealth.va.gov/display/PGDG/FAQ+-+answers+to+common+questions):

Question:   If my app is in the form of a Questionnaire, am I still responsible for creating resources?

- Answer:    There is considerable overlap between the information covered by Questionnaires and other Resources (especially FamilyMemberHistory, MedicationStatement, Observation, Procedure, etc.). It is possible to do both, fill out a (standard) questionnaire and create resources. If a resource can be created from the answers to a questionnaire, then the resource should be created as well. Information stored as resources provides rich data. Resource information stored only in questionnaires would not be found if a user queries a resource. Don't misuse questionnaire as a convenient data structure and miss the opportunity to enrich the patient's record.  

Question:   Do I need to include the complete Questionnaire structure in my PGD FHIR Mapping spreadsheet?

- Answer:    Definitely yes. Make sure to follow the Questionnaire structure. A Questionnaire has at least one Group - the root group. Information in the root group is specific to the questionnaire. For example, the title of the "root" group is the title for the questionnaire. The root group can have subgroups. A group may contain either questions or groups but not both.  

Question:   Do I need to create a separate row in the PGD FHIR Mapping spreadsheet for QuestionnaireResponse?

- Answer:    No. The QuestionnaireResponse mimics the Questionnaire data structure (graph). To simplify PGD FHIR mappings, pair the question/response in a single row of the mapping spreadsheet using a semi-colon as a separator, e.g., Questionnaire.group.question; QuestionnaireResponse.group.question.answer.

**Comment by stephenBarrs** [comment]
FHIR Mapping Template:

[VA_Mapping_Template_v3_0.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5262429/VA_Mapping_Template_v3_0.xlsx)

**Comment by mlighdc** [comment]
@stephenBarrs or @abuckley3385 is there a visual or architectural diagram of the systems involved? Just point me to where I can find it. I am not familiar with PGD but assume this is going into VistA or related?

**Comment by abuckley3385** [comment]
@mlighdc this is what we have todate - still WIP https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/architecture-diagram.md

**Comment by mlighdc** [comment]
Thanks @abuckley3385. The diagram is super helpful. I am still not sure how the responses from the questionnaire are getting into the appropriate EHRs (VistA or Cerner) after it has been completed. Or do we expect the providers to get the responses from somewhere else (such as printing them out). The arrows are going in one direction via Lighthouse API and I do see the arrow that is marked future work. I would assume for the initial release there would be an arrow from PDG to the EHRs or from VistA Scheduling. I am sure once someone walks me through this, it will all be clear :-)

**Comment by abuckley3385** [comment]
@mlighdc to our knowledge there is no direct interface of PGD to the EHR.  Clinicians use an app called Virtual Care Manager to view PGD data and from that UI experience they have an ability to "move" the patient generated data ie. our questionnaire fields into their documentation/the patient EHR chart.  @LEHigley has been working with the VCM team to get us a demo and I believe late last week they agreed so we will know more on how that workflow is enabled.  I will say out of all our stakeholders to-date none of them have ever used VCM so we see that as a potential workflow barrier to adoption but have some additional ideas on how the clinics could make it work in more of a manual way. Not ideal.   If you have other ideas we are all open!

**Comment by mlighdc** [comment]
That's right. Lacey did mentioned the Virtual Care Manager. I forgot about that. It was not in the diagram so it slipped my mind. Thanks Amanda.

**Comment by stephenBarrs** [comment]
Initial FHIR Mapping spreadsheet: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/data

I am not sure if we will need to include all elements on this spreadsheet. If VCM is expecting that all of these fields have been populated with data then we might have to.  Get Care FHIR mapping UI requires these fields, but FHIR does not.  

@abuckley3385 @mlighdc  @LEHigley

**Comment by stephenBarrs** [comment]
Design Doc for MAP integration: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md

**Comment by abuckley3385** [comment]
@stephenBarrs @LEHigley @mlighdc  Not an exact match to GetCare wording but I think it works for our MVP - please have a look and see if you agree.  I do have a question for Stephen on the last question as we will have multiple and if that will work with the mapping - I bolded the question for reference in the doc.  
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/pgd.md

**Comment by stephenBarrs** [comment]
@abuckley3385 for the last question I think we can still collect that data as multiples, but concatenate it into a single data field for storage in PGD.  It would need to be a logical separator that could be displayed to the Provider, but also something that can be parsed back into multiple entries so that if we need to rebuild the form with existing data we can populate the multiples on the form.

**Comment by stephenBarrs** [comment]
FHIR Mapping has been submitted for review. [Jira Ticket ](https://issues.mobilehealth.va.gov/browse/PGDG-75)(note: MAP credentials required)
