### ISSUE TITLE
[Development] HLR: Does HLR Work

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#13835]
## Issue Description
Initial integration testing has shown some possible issues with the API key, feature flag.  There was also a possible issue with prefill data.  This story is to capture the FE and BE work to get HLR working in staging.

## Acceptance Criteria
- [x] Staging user(s) are able to submit an HLR claim

**Comment by luke-gcio** [comment]
Looks like it was just the API key.

**Comment by edmangimelli** [comment]
This is blocked by:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/14003
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13952

**Comment by edmangimelli** [comment]
removing acceptance criteria:
- [ ] Confirm with LH everything worked on their end.

this ticket is mostly about ensuring HLR works in Staging/Sandbox, and those environments are completely mocked (and, therefore, aren't really hitting Lighthouse)

**Comment by edmangimelli** [comment]
All the individual tasks for this ticket have been spun into other tickets:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/13952
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14518

consequently, setting story points for _this_ ticket to 0
