### ISSUE TITLE
STEM: Remove in-progress application prod flag.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13830]
As a developer, I need to remove a prod flag so the updated content is available in the production environment.

## Assumptions:
1. The work completed in #13794 has been reviewed and signed off in staging as of 10/01.

## Acceptance Criteria:
1. The work completed #13794 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Confirmed in production. Closing this issue
