### ISSUE TITLE
Analytics Implementation for Debt Letters Iteration 2 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13846]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA? **Implementation for Iteration 2** 

- Who is this request for?

    - [BAM2]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _BAM2/ Debt Letters Iteration 2 
    

- Provide the Domain where Google Analytics needs to be implemented
    _https://staging.va.gov/manage-va-debt/your-debt/ - Please reach out to Brad to turn feature flag on for I2
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _This will be launched on 1/1/2020
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

   We would like to track page views, bounce rates, and letter downloads. 

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

- Additional Comments

    - This is specific to Iteration 2, the work on Iteration 1 has already been completed and reviewed. Please ping Brad to flip feature flag to I2 and list of test users for I2. 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @leahkeeler , thank you for your request! Confirming receipt

**Comment by bradl3yC** [comment]
@jonwehausen any update on this?

**Comment by leahkeeler** [comment]
Hi @jonwehausen - Do we have ETA for this? we were hoping to complete this sprint to get to staging review in next - Thanks!!

**Comment by jonwehausen** [comment]
Hi @leahkeeler & @bradl3yC , 

Thank you for your patience here, sure thing -- may we know does your team have documentation around your KPI's for debt letters? If not, that is certainly fine, if so we would like to take a look and make sure we've given those a review. Thank you!

**Comment by leahkeeler** [comment]
Hi Jon, the KPIs really have not changed from Iteration 1 - except an additional page was added for debt history and letter downloads is in a different place - does that help?

**Comment by jonwehausen** [comment]
HI @leahkeeler , 

Yes, thank you for that, we just like to ask to make sure we have done our due diligence in taking a look at your KPIs as context for ensuring we are tracking those pieces most significant for you all. 

The items you mentioned of **pageviews, bounce rate, and letter downloads** (_we have PDF downloads globally tracked_) are items that will have with not require any configuration changes from your team or ours to measure 😄 

If there are other items you had in mind you were interested in for roll-out please let us know -- happy to meet and/or discuss if there were other parts of I2 you and your team were interested in as well.

**Comment by leahkeeler** [comment]
Hi Joanne - good question. we do not have any KPIs  per se as this is a brand new product and since debt collection has been on hold for covid-19 and will resume in 2020 the behavior, visitors will be very skewed and not representative of typical visitors. We are hoping to just capture baseline numbers and develop KPIs in conjunction with online FSR in CY Q2 - lmk if this makes sense or if you have additional questions.

**Comment by leahkeeler** [comment]
@jonwehausen Checking on the stauts of this? it is one additional page to Iteration 1 -- @bradl3yC Can show you the pages in staging, if needed Thanks!

**Comment by jonwehausen** [comment]
### Data Layer Specification 
Per discussion with @bradl3yC , here are the items we will track (_some of these items have limited availability of context towards errors and/or downloads_) 

@leahkeeler Would you like to take a look and let us know if there is anything else that would be of interest to you? 

Description of Interaction | Data Layer Specification
------------ | -------------
Downloads of letters - **_already done from iteration 1_** | `'event': 'bam-debt-letter-download'`, <br> `'letter-type:', //First Demand Letter, Second Demand Letter`<br> `'letter-received-date:' //Date of letter`
API Successes / Failures (DMC data) | `'event': 'bam-get-veteran-dmc-info-successful'` `// or 'bam-get-veteran-dmc-info-failed',`<br> `'veteran-has-dependent-debt': true` `//or false`
Number of current cards returned | `'event': 'bam-number-of-cards-retrieved',` <br>`number-of-current-debt-cards': //integer of # of cards` - @bradl3yC let's only fire this event when number of cards > 0 

@bradl3yC Confirmed we also have a history change pageview currently firing when changing to `/your-debt/` to `/your-debt/debt-detail`

**Comment by leahkeeler** [comment]
Looks great to me = Thank-you @jonwehausen @bradl3yC :)

**Comment by jonwehausen** [comment]
Hi @bradl3yC, 

Just wanted to touch base with you for an update on the implementation, thanks in advance

**Comment by bradl3yC** [comment]
@jonwehausen I have not started yet - this sprint is focusing on the FSR form

**Comment by bradl3yC** [comment]
@jonwehausen this was just merged - should be in staging in 30 minutes

**Comment by jonwehausen** [comment]
### WIP - QA Testing
cc: @bradl3yC @leahkeeler 

Description of Interaction \ API Call | Data Layer Screenshot | GTM Screenshot | Test Status
| -- | -- | -- | -- |
**Tested with user+1** - DMC API call | ![image](https://user-images.githubusercontent.com/48527022/97745501-5873ec80-1abf-11eb-9b2a-55c062c94f9c.png) | ![image](https://user-images.githubusercontent.com/48527022/97745535-645fae80-1abf-11eb-95b2-562150cab7b3.png) | ⚠️ **NEEDS FURTHER REVIEW** - _have not seen the `veteran-has-dependent-debt` variable fire along with the event_
**Tested with user+1** - VBMS API call | ![image](https://user-images.githubusercontent.com/48527022/97745753-be607400-1abf-11eb-9e20-a6c8429d4211.png) | ![image](https://user-images.githubusercontent.com/48527022/97745782-c91b0900-1abf-11eb-95f8-a3e74a236138.png) | ✔️ **PASS**
**Tested with user+1** - **was unable to get `/manage-va-debt/your-debt/` to load completely and/or see debt cards** | _will update when testable_ | _will update when testable_ | ⚠️ **NEEDS FURTHER REVIEW** - need to reconnect on a usable test user to validate this event
**Tested with user+38** Clicked letter to download ![image](https://user-images.githubusercontent.com/48527022/97746530-d684c300-1ac0-11eb-8ead-271059ad02d1.png) | ![image](https://user-images.githubusercontent.com/48527022/97746653-177cd780-1ac1-11eb-909a-8cfb315a7ca1.png) | ![image](https://user-images.githubusercontent.com/48527022/97746709-30858880-1ac1-11eb-9872-c8d383e8fdfa.png) ![image](https://user-images.githubusercontent.com/48527022/97746743-3c714a80-1ac1-11eb-903f-0093e5ba7897.png) | ✔️ **PASS**

**Comment by bradl3yC** [comment]
@jonwehausen I think the has-dependent-debt was in its own call 

User 1 should have debt cards in staging

**Comment by jonwehausen** [comment]
@bradl3yC [Retested ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13846#issuecomment-719746804)the `'bam-get-veteran-dmc-info-successful'` event and looks good. 

Would be able to provide a user that fires the `'bam-number-of-cards-retrieved'` event? Did we implement this? 

Thanks again for your assistance here.

**Comment by jonwehausen** [comment]
@bradl3yC Thanks for calling out the `number-of-current-debt-cards` variable, am now seeing fired within GTM preview...

That said, could we update to be pushed along with a `bam-cards-retrieved` event? Resembling...

```javascript
   'event': 'bam-cards-retrieved', 
   'number-of-current-debt-cards': //dynamically populate with card count
```

If there are other card types that may surface here that we would like to capture, we can tact-on additional data layer variables as necessary. 

Thanks again -- this should be the final QA item for us to reach closure.

**Comment by bradl3yC** [comment]
@jonwehausen @bsmartin-ep can we verify this and close?

**Comment by jonwehausen** [comment]
Hi @bradl3yC , 

Verifying this today in effort to close, thanks

**Comment by jonwehausen** [comment]
@bradl3yC thank you very much for your work here -- the events have been validated and our QA [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13846#issuecomment-719746804) has been updated to reflect the `'bam-cards-retrieved'` event. 

We will close this ticket per implementation completion. 

cc: @leahkeeler @joanneesteban
