### ISSUE TITLE
[Investigation] 526: Look at Production SIP Data for PTSD

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#13852]
## Issue Description
When we worked with VSP to fix the itemFilter function, we realized there could be hundreds if not thousands of SIP applications that are impacted.  We want to look in to the data on production to determine if we can send an email to everyone that has selected PTSD somewhere in their disability flow.

## Acceptance Criteria
- [x] Collect all email addresses of veterans that have PTSD in their SIP
- [ ] Write and send email to all impacted veterans
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14189 would've gone out on the 9/16 deploy at 3pm ET

**Comment by annaswims** [comment]
I think this will get the email of all affected users.
````ruby
sips = InProgressForm.where("updated_at < ?", '2020-09-16'.to_date).where(form_id: "21-526EZ")

@veterans_to_notify = []
sips.each do |sip|
  form_data = JSON.parse(sip.form_data)
  @ptsd_present = false
  next unless form_data["new_disabilities"].present?
  form_data["new_disabilities"].each do |disability|

    if disability["condition"].include? "PTSD"
      @ptsd_present = true
    end
    if @ptsd_present && disability["cause"] == "SECONDARY" #
      @veterans_to_notify << form_data["phone_and_email"]["email_address"]
      next
    end
  end
end

````

**Comment by annaswims** [comment]
10,364 people affected in the past year by this bug. 

I have the emails, just let me know who to send them to.

**Comment by annaswims** [comment]
I sent an email with ~3k email addresses to Paul

**Comment by annaswims** [comment]
@luke-gcio Every day we wait to send this email means that some veterans will have their intent to file timeout

**Comment by luke-gcio** [comment]
@annaswims The call center team is working on a possible solution.  I understand the timeline here but unless we want to send an email from our VA.gov email and hope it takes 1000+ emails we are somewhat stuck.

**Comment by luke-gcio** [comment]
We found a method for sending the emails.  We should have them sent out within a few days.

**Comment by annaswims** [comment]
Updated email list was sent to Matt and John this morning on VA email.

**Comment by luke-gcio** [comment]
Met with NCC Friday and they are ready to go.  Email going out today/tomorrow.

**Comment by annaswims** [comment]
@luke-gcio What's the status on this?

**Comment by vhenry07** [comment]
Closing as bug fix applied
