### ISSUE TITLE
Reports: Remove deprecated items from the YTD Report

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13859]
As an Education Team member, I need the St. Louis RPO entries removed from the YTD reports after the start of the new fiscal year because applications are no longer being routed to the RPO.

## Assumptions:
1. This work is done behind ~a prod flag~ the `education_reports_cleanup` feature flag.

## Acceptance Criteria
1. The set of rows related to the St. Louis RPO are not included in the YTD report.
2. The set of columns related to the `22-1995 STEM` application are not included in the YTD report.
3. The `ALL RPOS TOTAL` calculations do not include the St. Louis RPO.

## Supporting Artifact
1. [YTD_Report_Updates_20200922.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5263425/YTD_Report_Updates_20200922.xlsx)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/5096
- https://github.com/department-of-veterans-affairs/vets-api/pull/5097

**Comment by dmccurdybah** [comment]
Implemented behind the `education_reports_cleanup` feature flag

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
TestRail test run here:
https://dsvavsp.testrail.io/index.php?/tests/view/13378&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
Updated Staging YTD report received 10/23/2020. Closing this issue
