### ISSUE TITLE
STEM: Remove 'edu_benefits_stem_scholarship' feature flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13850]
As a developer, I need to remove the 'edu_benefits_stem_scholarship' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. The feature flag was configured as part of story #7271.
2. This functionality has gone through UAT with EDU and been signed off on as of 08/17.
3. This functionality has been turned on as of 09/10 and no issues have been encountered.

## Acceptance Criteria:
1. The feature flag 'edu_benefits_stem_scholarship' is removed and all 10203 functionality is still available as outlined in supporting artifacts 1 and 2.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/JHIAE4UVKA4#/screens/296040907) as of 07/01
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ac00ddfc52dd101577639d5bdcf25a720a029fbf/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md#form-title-apply-for-the-rogers-stem-scholarship-10) as of 07/01

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/14619
- https://github.com/department-of-veterans-affairs/vets-api/pull/5116

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/5116
- https://github.com/department-of-veterans-affairs/vets-website/pull/14619

**Comment by delli-gatti-michael** [comment]
The feature flag is gone. Closing this issue
