### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13864]
### User story
As a Veteran, I want the ability to navigate back to the previous page anytime I leave the home page. 

### Acceptance Criteria

1. When the user is on any page in the app except the 4 landing pages (Home, Claims, Appointments, Profile), a Back button appears in the top left corner
     - Each of the 4 tabs has its own navigation stack
2. Selecting the Back button returns user to the previous page

### Designs

https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432345659

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
@bridgethapner Does the Back button need to exist when the user switches between any of the 4 buttons on the nav bar? Or, does the Back button only need to appear when the user has navigated away from any of those 4 landing pages (Home/Claims/Appts/Profile) and deeper into the IA (this is similar to how it's handled on Instagram, FB, Spotify, etc.)?

The designs indicate that the answer to the first question is 'yes', but since this will impact how we implement navigation throughout the app, I want to make sure we're on the same page as you!

**Comment by jjulian** [comment]
I feel like the standard implementation is for each bottom bar "tab" to have its own navigation stack. Once you hit back all the way to the main view, you can no longer go back any further.

(Android Back button may provide _more_ "back" capability such as going back to a previously seen tab)

**Comment by bridgethapner** [comment]
Good question, thank you! -- I agree with @jjulian, it seems confusing to me to hit back on, say, the Claims homepage and to go back to somewhere in Profile. So let's remove the "Back" button the 4 main landing pages and homepage and keep it deeper into the IA. Looking forward to talking more later - would appreciate hearing your POV too.

**Comment by digitalken** [comment]
See issue logged:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14605

**Comment by digitalken** [comment]
Testing:

1. Verify that a back button appears in the upper left corner when on any page in the app other than the four landing pages:  Home, Claims, Appointments, Profile.
2. Verify that the back button takes user back to the previous page.
3. Verify screen reader reads back button.
4. Use auxiliary keyboard and verify user is able to tab to the back button and the focus is clear.

**Comment by digitalken** [comment]
PASS 10/29/2020 - Tested in Android simulator and on iOS device. Back button is operates as expected and is read by screen readers correctly.
