### ISSUE TITLE
Reports: Remove YTD update feature flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13860]
As a developer, I need to remove the 'education_reports_cleanup' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. This feature flag was created in #13859 
2. UAT has been completed for this effort and EDU signed off as of 10/30.
3. The new functionality is live in production with no need remaining need for the toggle.

## Acceptance Criteria
1. The feature flag 'education_reports_cleanup' is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5287

**Comment by sonntag-adam** [comment]
Testing passes QA
