### ISSUE TITLE
GIDS: Add the ability to upload the accreditation excel file

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13863]
As an EDU team member, I need the ability to upload the accreditation excel file so that I can minimize the number of manual steps involved with maintaining the comparison tool

## Assumptions:
1. This is the implementation story of the work done in #11095.
2. This work is completed behind a prod flag.
3. The current accreditation file uploads are to remain available until this feature has been completed and tested by the customer.

## Acceptance Criteria
1. The "AccreditationData.xlsx" file that can be downloaded from the Office of Postsecondary Education can be uploaded to GIDS.
    a. The "InstituteCampuses" tab populates the tables/fields that are currently populated by the "AccreditationInstituteCampus" upload.
    b. The "AccreditationRecords" tab populates the tables/fields that are currently populated by the "AccreditationRecord" upload.
    c. The "AccreditationActions" tab populates the tables/fields that are currently populated by the "AccreditationAction" upload.

## Supporting Artifacts:
1. Data file source: https://ope.ed.gov/dapip/#/download-data-files

## Implementation 
- `RooHelper::Loader.load_with_roo` is inherited by all ImportableRecord classes, this is the upload method
- For the SA #1 use the `:parse_as_xml` option

**Comment by zurbergram** [comment]
Refactor PR - https://github.com/department-of-veterans-affairs/gibct-data-service/pull/753

**Comment by zurbergram** [comment]
Main PR - https://github.com/department-of-veterans-affairs/gibct-data-service/pull/751

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-28 at 1.50.40 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4dc7e0ca-eee4-45e9-9dd6-bfbd7798549c)
##
![Screen Shot 2020-10-28 at 2.06.47 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ef661e37-05f7-44c7-be68-64a19a5f273f)

**Comment by zurbergram** [comment]
unit tests https://github.com/department-of-veterans-affairs/gibct-data-service/pull/757
