### ISSUE TITLE
GIDS: Remove prod flag for accreditation excel upload functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13866]
As a developer, I need to remove a prod flag so the accreditation upload functionality is available in the production environment.

## Assumptions:
1. The work completed in #13863 has been reviewed and signed off in staging as of 11/03

## Acceptance Criteria:
1. The work completed #13863 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/761

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Now showing in Production. Closing this issue

![Screen Shot 2020-11-04 at 9.45.28 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4bd4a4cf-46ef-4018-a1c6-977e59590052)
