### ISSUE TITLE
Navigation bar & 4 landing pages

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13862]
### User story

As a Veteran, I want a persisting navigation bar at the bottom of my device so I can easily route to the main pages of the app. 

### Acceptance Criteria

1. Horizontal navigation bar at the bottom of the screen with 4 page options. Include icon + label for:  
     - Home
     - Claims 
     - Appointments
     - Profile
2. Hook up routing to 4 skeleton landing pages (no UI on these pages needed)
3. Selected and non-selected states for each icon/label: 
     - Selected state (darker blue icon/label) matches design
     - Non-selected state (lighter blue icon/label) matches design
4. The bottom nav bar appears on all pages in the app, except in the keyboard edit state

### Designs

https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636866

### Accessibility Acceptance Criteria

1. Everything should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each touch target must be at minimum 44px by 44px
3. All elements should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
 Note: The nav bar does not have to scale up if a user has increased their text size on a page.

### Accessibility Implementation Guidelines 
- The nav bar should be specified as accessibilityRole= toolbar
- All page options should be specified as accessibilityRole= imagebutton, accessibilityLabel= Page Name (i.e. Home, Claims, Appointments, Profile)
- When a user navigates to a page, the selected state should be marked as accessibilityState= selected

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bridgethapner** [comment]
@bessgreen @komaly15 Regarding AC 4 - 

Looking at the UX, I think we should also not display the bottom navigation on the following pages:
- **[Veterans Crisis Line](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432348084) and [Contact VA](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432493860).** Since these screens are only accessible via in-page CTAs, it seems odd to me to include the bottom bar nav as these items aren't really part of that nav structure. Additionally, since the Veterans Crisis Line is accessible from the unauthenticated home screen, we won't want unauth users to ever see the nav until they sign in. 
- **Any informational states [like this one](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636872).** Since these are niche informational states that only relate to the screen the user just came from, it feels ok to me for the only option on screens like this to be "Back". 

These are just thoughts that came up for me when working through the unauth home screen this morning, happy to hop on a Zoom to discuss more & value any input y'all have too as mobile experts!

**Comment by bessgreen** [comment]
@bridgethapner there may be an a11y issue with omitting the nav bar from certain pages. Having the nav bar on some pages and not others breaks with WCAG's [Consistent Navigation](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-consistent-locations.html) standards, but it IS a grey area for the following reasons:

- The pages that you specified are informational 
- 508 says nav consistency isn't required
- 508 says non-web software is exempt

Since we're in a bit of a murky area here, this would be a good candidate to run by the 508 office / discuss with Martha. 

In the meantime though, in case we get approval to hide the nav bar on select pages, @komaly15 is building it out in a way that will make it easy to turn it on/off when we want to.

I also made a list of all the pages in the app that I assumed would fall into the "no nav bar" category. Let me know if this is the right list of pages / if we missed any! 

- [How do I update my personal info? ](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636872)
- [How will you use my contact info? ](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636871
)
- [What if my military service info doesn’t look right? ](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636874)
- [Manage your account ](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432001518)
- Privacy Policy
- [Why we combine claims ](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432462453)
- [Disagree with your decision on my VA disability claim ](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432462454)
- Learn about your decision review options
- How we come up with your estimated decision date

**Comment by digitalken** [comment]
See issues logged:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14562
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14607

**Comment by bridgethapner** [comment]
Hi @bessgreen - Thank you very much for making this list of pages that might fall into this category! Given that this is a gray area, I think the quickest solution for MVP is to just keep the bottom nav on all pages, including informational pages, for now.

**Comment by digitalken** [comment]
Testing:

1. Verify four buttons in nav bar at bottom of page ordered left to right as follows:
    a. Home
    b. Claims
    c. Appointments
    d. Profile
2. Buttons are white outline in unselected state and filled in blue when selected. (matches design)
3. Verify tapping on nav bar buttons takes users to the specified pages.
4. Verify that the nav bar on all pages in the app except in keyboard edit state.
5. Ensure screen reader reads all buttons correctly including name (title), role and value.
6. Verify touch point for each button is at least 44px by 44px.
7.  Use an auxiliary keyboard to tab through the page and verify nav bar is accessed and focus for each button is clear.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Moving to Design QA. Have one outstanding bug to be fixed https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14562

**Comment by bessgreen** [comment]
@msmanak here is a ticket with an example of a11y requirements
