### ISSUE TITLE
Set up styling patterns

### ISSUE THREAD

**Issue by erikbreedlove** [department-of-veterans-affairs/va.gov-team#13873]

**Comment by bridgethapner** [comment]
Hi there @keli13 --

## Fonts
The fonts we are using are Source Sans and Bitter, both can be downloaded [here] (https://design.va.gov/design/typography#fonts).

## Sketch file
Here is the sketch file, SVG icons in here: https://drive.google.com/file/d/1SEIM5vmcaVIi8Th6PeIAavVORl3HS-h-/view?usp=sharing

Will keep y'all posted on anything we're able to work out with Invision for using Inspect Elements down the line.

**Comment by srmyers17** [comment]
- core styling but not the details, that will require Inspect
- not able to get into google drive - Sophie to f/u
