### ISSUE TITLE
Profile screen (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13885]
### User story
As a Veteran, I can view and manage my Profile information, including:
     - Personal and contact information
     - Military information
     - Direct deposit 
     - VA letters and documents
     - Settings

### Acceptance Criteria

1. Styling and UI matches the design. 
2. A header appears that includes the user's bolded first name and last name on top, and the military branch they served in on the bottom. The military branch's seal should be displayed to the left.
     - assumption for this story: user is only associated with 1 branch of the military and thus only has 1 icon displayed. The icon displayed will reflect the user's _most recent branch of service._ most recent branch of service (there may be a future task for us to update this when users are a member of 2+ branches - investigation work is in prog by the AH team)
     - driven by the profile-api 
     - Icons for the 5 service branches are listed below 
3. Below the header, include a list of 5 pages to choose from (UI only. Routing is handled in separate stories)
 
### Designs

https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636867

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

### Assets
![vic-air-force-coat-of-arms.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/1fb73250-85e4-44a7-ad01-f26a39fd4913)

![vic-army-symbol.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c8351c2b-558b-4177-b75f-1b070490f5ae)

![vic-cg-emblem.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/37271009-d292-40f9-bce9-4ea1bbf5c04b)

![vic-navy-emblem.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d1730943-84ef-4a97-bef6-8e9d83b65556)

![vic-usmc-emblem.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/43ca9aca-68aa-416e-99bf-40a4751de57e)

**Comment by bessgreen** [comment]
Questions: 

1. Veterans may have served in multiple forces - if we get ex: Air Force and Army returned form API - how do we determine which we display? View for displaying both? user select? most recent? - We should get a test user form va.gov to see how they handle this

**Comment by bessgreen** [comment]
@bridgethapner when you have a chance, are you able to provide the icons for each of the service branches (in addition to Air Force)?

**Comment by bridgethapner** [comment]
Hi there @bessgreen -- Seal assets are here: https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/site/assets/img and are the following files:

- vic-air-force-coat-of-arms.png
- vic-army-symbol.png
- vic-cg-emblem.png
- vic-navy-emblem.png
- vic-usmc-emblem.png

Re your question on if a user has multiple branches of service, let's display the seal for their most recent branch of service.

**Comment by bessgreen** [comment]
Military branch seal display (if the user has multiple): most recent branch of service

**Comment by digitalken** [comment]
Issue(s):
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14719

**Comment by digitalken** [comment]
Testing:

1. Verify that profile page matches the design.
  a. Header includes the user's first and last name in bold text.
  b. Service logo to the left.
  c. Branch of service in regular text below user's name.
2. Test with user that has served in multiple military branches:
  a. Verify user is only associated with one branch and and only one icon displays.
  b. Displayed branch will be the most recent.
3. Verify a list of five page links appear (currently only place holders.)
  a. Personal and contact information
  b. Military information
  c. Direct deposit
  d. VA letters and documents
  e. Settings

Accessibility testing:
1. Very page displays correctly using largest font setting.
2. Page reader reads correctly.
3. Tap to navigate steps through buttons in a logical manner.
4. Focus on each button is well defined.
5. Page passes with Deque or similar a11y testing tool.

**Comment by digitalken** [comment]
Bug 14932 is blocking some testing of this story.
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14932

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 11/11/2020 on TestRail run. Sending to Design QA.
