### ISSUE TITLE
[Discovery] Review Transformers docs

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#13884]
## Issue Description
Given the Transformers team is generating documentation for teams to consume and the VAMC team is doing a pass,
I want to provide an FE perspective on the product/dev docs so we can close any templates. 

---
## Tasks
- [x] Review Transformer evaluation from VAMC team
- [ ] Document any gaps from a FE perspective

## Acceptance Criteria
- Provided feedback to Transformers team on documentation
- Identify Transformers required for LC
---

**Comment by ncksllvn** [comment]
[Per this message](https://dsva.slack.com/archives/C01512KN35G/p1604946928149800), I think this is the key resource - https://vfs.atlassian.net/wiki/spaces/VP/pages/637567205/Transformers+Development+Guide. We were also assigned this ticket as an intro ticket, https://github.com/department-of-veterans-affairs/va.gov-team/issues/15969.
