### ISSUE TITLE
Access for Joseph Niquette

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#13880]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Joseph Niquette
- Please Provide your email.
   > joe.niquette@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Identity team within VSP. I am a Sr. Security Engineer at Oddball.

- Requesting SSH key authorization?
   > YES 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5UR8xyEp3uGFK6MQe5/TABrfYKc/ZI874C+bQXxypdYiQNm4gCychHcVTtGz1nzg4E5dw0dbkbK0JYHJxDVOQT8AnLf4kvKwPEAqcJzEaHjy4UJXHlioV+XU6hmDLeGI/ulx5U4K9M3WAAHLqd1xdLulNyLWX5mCXXV1khQEIQqA72e2/rw1lE7wNKtnUvVeqvXgPWJdRZxWnb+nEV+Awub5zBnwyF6hMejvPvbtnDVR6X/GKu55aj9vWrfi3VPGcOLXzzUk7GBa4wu0aAEOYYeDYXdPx4qstVRha5Ozg8XuCOxcqcML96nnEc2HhBRf16yPqfL06LjMOGxUteeapkuGMk9VTNiu4tEhhyQ1LIQv8CxXihesUyaf8+H+btsHwI9VVpNS1Q+88mVz0Uv0ZRNZnEjRvSA411FAq2GeBqBVtBJ2nR/H5OQ76C+VJyMhCqfgP+o/5fwvnCFSAHPqcs4qCm2lRQcsagiFEgmF+cJT8GXHZzc+130W6jpvE9BE= niquette@niquette-macs-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES
  - Viewing cloudwatch logs and other log sources. As a security engineer on the VSP contract I would like to be able to review logs within AWS which concern the VSP.

**Comment by joeniquette** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
**Requesting AWS Access**
User: Joe Niquette @joeniquette 
cc: @Jeff-Hayter

**Comment by drorva** [comment]
Approved

**Comment by tskinn** [comment]
I've given Joe his access credentials for AWS
