### ISSUE TITLE
View military information

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13896]
### User story
As a user, I can view my military information and periods of service.

### Acceptance Criteria

1. Styling and UI matches the design. 
2. Each service period description should include the branch of the Military the user served in at the top, and the time period at the bottom, in the following format: Month X, XXXX - Month X, XXXX
3. Include a link at the bottom: "What if my military service information doesn't look right?" (UI only. Routing is in a separate story)

### Designs
[https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636873](url)

### Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 

- Mark “Military Information” as Header 1.

**Banner** 
- Veteran Name
     - Title= “Veteran First Name, Middle Initial, Last Name” e.g. Jerry M Brooks
     - accessibilityRole= “text”
- Military Branch 
     - Title= “Military Branch Name” e.g. United States Air Force
     - accessibilityRole= “text”
- Military Branch Image 
     - Title= “Military Branch Seal” e.g. United States Air Force Seal
     - accessibilityRole= “image”

**Period(s) of Service**
- Heading= “Period(s) of Service
- accessiblityLabel= List of Periods of Service, including Branch Name and Dates
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list.

**Link**
- accessibilityRole= Link

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions

1. Is the order for listing the service periods API driven? Or do we need to build out any logic for how these are displayed (i.e. by least recent start date, most recent end date, etc.)

**Comment by bessgreen** [comment]
Need: icons for all military branches

**Comment by kreek** [comment]
@bessgreen pretty sure the underlying service returns it in the right order, but we can make sure that the API orders it if it doesn't cc @jperk51

**Comment by digitalken** [comment]
Testing:

1. Verify page (styling and UI) matches designs.
2. Verify each service period includes:
  a. Branch of the military served in at the top.
  b. The time period served at the bottom.
  c. Time period in the format: Month x, xxxx - Month x, xxxx.
3. Verify a link at the bottom:  "What if my military service information doesn't look right?" (UI only, not linked yet.)
4. Verify everything on page is correctly read by screen reader.
5. Verify page functions without loss of content, overlap or horizontal scroll with maximum font size device supports.
6. Verify minimum touch point sizes (44px by 44px).
7.  Verify user is able to navigate by tap or voice control only.
8.  Verify auxiliary keyboard is able to traverse page and the focus for each element is clear.

**Comment by digitalken** [comment]
Linked issue(s):

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15592

**Comment by esther-k** [comment]
UI and functionality pass. Accessibility does not pass with two persisting bugs and a multi-issue bug entered. Moving this to Design QA for review

[Multi-issue accessibility bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15592)

[Service record bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15592)

[Service record dates bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15316)
