### ISSUE TITLE
Incorrect service info page + click-to-call 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13897]
### User story:
As a user, I want to know how I can report misinformation about my military service. 

### Acceptance Criteria:

1. Selecting the "What if my military service information doesn't look right?" hyperlink routes to a new page
2. Styling and UI matches the design
3. Two phone numbers at the bottom of the screen, styled as hyperlinks
     - Click-to-call capability on both hyperlinks. Upon selection, the selected number dials via the user's phone app

### Designs
[https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636874](url)

### Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 
- Back button in top left
     - accessibilityRole = “button”
     - accessibilityLabel = “Go back to military information”
- Programmatically set page title as "What if my military service information doesn't look right? page" and mark as Header 1
- Mark "What if my military service information doesn't look right?" as Header 2

**Links**
- Icons
     - Title= “Phone Icon”
     - accessibilityRole= “image”
- Contact Resource
     - Title= Name of link (e.g. 800-538-9552)
     - accessibilityRole= “link”
     - accessibilityHint= “Dials this number via your device’s call function"

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions:

1. Validate AC # 3 - click-to-call capability

@bridgethapner

**Comment by bridgethapner** [comment]
@bessgreen Yes, click to call is correct.

**Comment by esther-k** [comment]
@bridgethapner 

Questions:

1. Validate - Programmatically set page title as "What if my military service information doesn't look right? page"

**Comment by bridgethapner** [comment]
@esther-k Yes!

**Comment by digitalken** [comment]
Testing:

1. Verify that selecting the "What if my military service information doesn't look right?" hyperlink takes user to a new page.
2. Verify styling and UI matches designs.
3. Verify two phone numbers at the bottom of the screen - click to call hyperlinks. (NOTE: designs only show one number currently!)
4. Verify everything on screen is read by screen reader.
5. Set font to largest in device settings and verify that font scales without loss of content, overlap or horizontal scrolling.
6. Verify all touch point targets are at least 44px by 44px.
7. Verify page may be navigated and and operated by tap or voice control only.  Any gestures needed will be available through the OS built-in capabilities.
8. Verify external auxiliary keyboard may be used to traverse the page and focus on elements is clear.
9. Verify screen reader reads "back" button role as "button" and label as "Go back to military information."
10. Verify page title is read as "What if my military service information doesn't look right? page".
11. Verify phone icons are read "Phone icon", "image".
12. Verify link is read "800-538-9552" (or the actual number), "link", "dials this number via your device's call function".

**Comment by keli13** [comment]
Covers the ui and unit test. Note here to add in integration in another pr

**Comment by keli13** [comment]
Integration test are in now

**Comment by digitalken** [comment]
Added to TestRail

**Comment by esther-k** [comment]
UI and functionality pass. Accessibility does not pass with a multi-issue bug entered. Moving this to Design QA for review

[Accessibility Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16249)
