### ISSUE TITLE
How will you use my contact info page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13892]
### User story
As a user, I want to understand how the VA will use my contact information.

### Acceptance Criteria

1. The "How will you use my contact information" hyperlink routes to a new page 
2. Styling and UI matches the design.

### Designs
Launch page: [https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636868](url)
How will you use my contact info? page: [https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636871](url)

### Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.

### Accessibility Implementation Guidelines 
- Programmatically set page title as "How will you use my contact information? page" and mark as Header 1
- Back button in top left
     - accessibilityLabel = "back"
     - accessibilityHint= “Go back to Personal Information”
     - accessibilityRole = “button”
- Mark “How will you use my contact information?” as Header 2 
- Mark summary text as “text” 
     - Do not include question so that it’s not repeated

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by keli13** [comment]
UI and unit test has been merged. Reminder here to add integration test

**Comment by digitalken** [comment]
Testing:

1. Verify that hyperlink, "How will you use my contact information", routes to a new page.
2. Verify styling and UI matches the design.
3. Verify everything on page is read by the screen reader.
4. Verify user may use largest font device supports and have no loss of content, overlap or horizontal scrolling.
5. Verify each touch point target is a minimum of 44px by 44px.
6. Verify that tapping or voice control is all that is necessary to view the page.
7. Verify that all elements of page are able to be traversed by an auxiliary keyboard.
8. Verify page title is read as "How will you use my contact information? page" as header 1.
9. Verify back button (top left) is read as:
  a. accessibilityLabel = "back"
  b. accessibilityHint = "Go back to Personal Information"
  c. accessibilityRole = "button"
10. Verify "How will you use my contact information?" is Header 2.
11. Verify summary text as "text".

**Comment by digitalken** [comment]
Added to TestRail

**Comment by esther-k** [comment]
**11/17**

PASS - UI, functionally, and accessibility pass on iOS and Android
