### ISSUE TITLE
Edit email address

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13895]
### User story
As a user, I want the ability to edit my email address directly from the app. 

### Acceptance Criteria

1. Tapping on the editable button for email address will take the user to a new page where they can edit that field
2. The edit page for the Email address only has one "Email address" field
     - When a user taps into/ selects this field, the QWERTY keyboard should appear. (i.e. the default keyboard with the addition of the @ symbol)
3. Ellipses when a field is too long to fit on one line
4. There should be a "Save" CTA button in the top-right corner that only be becomes actionable (and turn white) when either of the following are true:
     - The Email field is blank
     - The Email field contains the @ symbol in the middle of two characters (format: "X@X" - see comments below for more info)

### Designs
TBD

### Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 

- Mark page title as Header 1 
- Cancel button in top left
     - accessibilityLabel = "cancel"
     - accessibilityHint= “Go back to Profile options”
     - accessibilityRole = “button”
- Save button in top right
     - accessibilityLabel= “Save”
     - accessibilityHint= “Saves changes”
     - accessibilityRole= “button”
     - accessibilityState= Denote when disabled vs. enabled
- Mark all fields as text input
     - Include necessary props 
     - Denote if filled vs. unfilled
     - If unfilled, denote placeholder text
     - Denote requiredness 

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions:

1. Handling for long fields? (break to a new line, ellipses, etc.)

@bridgethapner

**Comment by bridgethapner** [comment]
@bessgreen Ellipses works! Thank you.

**Comment by bessgreen** [comment]
@bridgethapner are there rules for when the Save button should be actionable on the email address edit screen? Can this field be left blank?

**Comment by bridgethapner** [comment]
@bessgreen This field can be left blank, so let's follow the same rule as phone numbers where the Save button activates if:
- The field is empty, or
- The field is full and meets the criteria of "X@X". The only requirement per the VA.gov Profile product guide is that the field includes an "@" symbol.

**Comment by digitalken** [comment]
Testing:

1. Verify tapping on edit button for email address takes user to a new page for editing.
2. Verify the edit page for the email address only has one "Email address" field.
  a. Verify when user taps into or selects this field, the "email address" keyboard should appear. (Keyboard with a @ symbole.)
3. Verify that ellipses will appear when a field is too long to fit on one line.
4. Verify that a "Save" call to action button in the top-right corner that only enables when the field is blank or the field contains the @ symbol between two characters. (Minimal validation.)
5. Verify everything on the page is read by the screen reader.
6. Verify each page supports the largest font on the device without loss of content, content overlap or horizontal scroll.
7. Verify all touch point targets are a minimum of 44px by 44px.
8. Verify the page supports operability by tap or voice control only.
9. Verify user can traverse the page(s) by an auxiliary keyboard reader and focus on elements is clear.
10. Verify when a page opens, the first section or element should automatically be placed in focus.
11. Verify that when a page opens, the title page should be announced.

**Comment by digitalken** [comment]
@bessgreen, the design link for this story doesn't seem to be correct.
From above:  https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432057841https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432057841

**Comment by bessgreen** [comment]
@digitalken there aren't designs for the edit email screen - I'll remove the link to avoid confusion.

**Comment by digitalken** [comment]
Add to TestRail

**Comment by digitalken** [comment]
UI Test passes with a minor bug entered.  Accessibility does not pass. Entered a bug with multiple issues.  Moving this along to Design QA for review.

UI bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15865

Accessibility bug: 
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16170
