### ISSUE TITLE
Edit phone number

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13894]
### User story
As a user, I want the ability to edit my phone number(s) directly through the app,

### Acceptance Criteria

1. Tapping on the editable button for phone number will take the user to a new page where they can edit that field. Header bar includes:
     - "Cancel" (in place of Back button)
     - "Save" (see AC #5)
2. The page title reflects the selection from the previous page. Page titles display as: 
     - Home phone
     - Work phone
     - Cell phone
     - Fax number
2. The edit page for all 4 types of numbers should format the user's string after the user taps out of the field (format: (000)-000-000) and extension field (0000), along with explanatory content under the number field. Editing any of these fields should introduce a numerical keyboard.
3. The Number field cannot exceed 10 digits
4. There should be a "Save" CTA button in the top-right corner that only be becomes actionable (and turn white) when either of the following are true:
     - The Number field contains 10 digits
     - The Number field is blank

### Designs
[https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636868](url)

### Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 

- Mark page title as Header 1 
- Cancel button in top left
     - accessibilityLabel = "cancel"
     - accessibilityHint= “Go back to Profile options”
     - accessibilityRole = “button”
- Save button in top right
     - accessibilityLabel= “Save”
     - accessibilityHint= “Saves changes”
     - accessibilityRole= “button”
     - accessibilityState= Denote when disabled vs. enabled
- Mark all fields as text input
     - Include necessary props 
     - Denote if filled vs. unfilled
     - If unfilled, denote placeholder text
     - Denote requiredness 
- If an error occurs, announce error and provide suggestion

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
Questions:
- AC # 2: Are these the correct page names? (The designs gave an example for Home phone - just need to validate the other 3)

@bridgethapner

**Comment by bridgethapner** [comment]
@bessgreen Yes, these are the correct page names!

**Comment by bessgreen** [comment]
@bridgethapner 
1. Is there validation for the phone number? Or could a user input 000-000-0000 and it would be "accepted"? 
2. Will the Save button only become active when a user has input a 10-digit number?

**Comment by bridgethapner** [comment]
@bessgreen 
There is validation on VA.gov today. I get rejected when I enter something other than 10 digits, so let's limit the # of characters to 10. @kreek Is it safe to assume the API only accepts 10 character entries?

Re the Save button - This one is tricky, let's connect in a quick Zoom Bess. Users should be able to remove their phone numbers and save no phone number. Maybe the best way to handle this is to require the field to either have 10 characters or be blank, and the Save button only activates in those two states. This feels confusing to me but I'm not sure how else to handle it.

**Comment by bessgreen** [comment]
@bridgethapner if a user can save no phone number, then should we omit the suggestion text that says "Number (Required)"?

**Comment by digitalken** [comment]
Testing:

1. Verify that tapping on the edit button for phone number will take the user to a new page where they can edit that field.
  a. Header for edit page should include:
    i. Cancel in place of back button.
    ii. Save button.
2. Verify the page title reflects the selection from the previous page:
  a. Home Phone or
  b. Work phone or
  c. Cell phone or
  d. Fax number
3. Verify formatting for all 4 types of numbers are of the format (000)-000-0000 with explanatory information.
  a. Verify editing uses a numerical keyboard.
4. Verify formatting for the extension field is (0000) with explanatory information.
  a. Verify editing uses a numerical keyboard.
5. Verify the number field can't exceed 10 digits.
6. Verify Save button enables for the following:
  a. The number field contains 10 digits.
  b. The number field is blank.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
UI and functionality pass. Accessibility does not pass with a multi-issue bug entered. Moving this to Design QA for review

[Accessibility Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16310)
