### ISSUE TITLE
Edit US address (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13893]
## User story

As a user, I want the ability to edit my US addresses directly through the app.

Note for dev: there are separate stories for Military Base & International addresses. The Military Base checkbox is also handled in a separate story.

## Acceptance Criteria

1. From the Personal Information page, tapping on any of the Address buttons will take the user to a new page where they can edit that specific field. 
2. Styling and UI matches the design
3. The page title reflects "Mailing address" or "Residential address" depending on the user's selection from the Personal Info page
4. The edit page for Addresses should allow a user to edit its "parts" in separate fields: 
     - Country
     - Street Address Line 1, Line 2, Line 3
     - City
     - State
     - Zip code
5. Country field:
     - Indicate field as "Required" 
     - Selecting Country will open a native picklist. Countries JSON: https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/constants.json#L777
     - When the user selects the United States from this picklist, the address fields above should persist (Note: when the user selects any country except the U.S. from this list, this will change the address fields. This is handled in a separate story.)
6. Street address fields:
     - Address Line 1 is indicated as "Required". Lines 2 & 3 are not required.
     - Selecting Address lines will open the default QWERTY keyboard when a user taps into the field
     - Maximum of 35 characters for each field
7. City field:
     - Indicate field as "Required" 
     - Selecting field will open the default QWERTY keyboard
8. State field:
     - Indicate field as "Required"
     - Selecting field will open a native picklist. States JSON: https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/constants.json#L2537
9. Zip code field:
     - Indicate field as "Required"
     - Selecting field will open the numerical keyboard
10. When a user is moving through multiple text input fields, keep the keyboard open to avoid flickering. (blurOnSubmit prop) 
11. There should be a "Save" CTA button in the top-right corner (validation is handled in a separate story)

Future story for the following requirements:
- "Save" button is actionable when any of the following are true:
     - All required fields have a valid entry in the edit screen
     - A valid change is made in any required field
- Address validation through the US Post Office _(designs in progress - see comments below)_

## Designs:
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432053040
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431899953

## Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark page title as Header 1 (e.g. “Mailing Address”)
- Cancel button in top left
     - accessibilityLabel = "cancel"
     - accessibilityHint= “Go back to Profile options”
     - accessibilityRole = “button”
- Save button in top right
     - accessibilityLabel= “Save”
     - accessibilityHint= “Saves changes”
     - accessibilityRole= “button”
     - accessibilityState= Denote when disabled vs. enabled
- Mark all fields as text input
     - Include necessary props 
     - Denote if filled vs. unfilled
     - If unfilled, denote placeholder text
     - Denote requiredness 
- If an error occurs, announce error and provide suggestion

## Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
Questions:
1. When the 'military base' box is checked, will this designation appear on the confirmed address in the previous screen? 
2. Are APO/FPO/DPO 3 separate items that appear in a picklist? How does a user make this selection (e.g. native dropdown, radio buttons, etc.)?
3. How is the "delete" vs. "edit" function for addresses communicated to the user? (AC # 6)
4.  Is there validation for any of these fields?

**Comment by bessgreen** [comment]
Questions:

1. When the 'military base' box is checked, will this designation appear on the confirmed address in the previous screen? 
2. Are APO/FPO/DPO 3 separate items that appear in a picklist? How does a user make this selection (e.g. native dropdown, radio buttons, etc.)?
3. How is the "delete" vs. "edit" function for addresses communicated to the user? (AC # 6)
4. Is there validation for any of these fields?

@bridgethapner

**Comment by bridgethapner** [comment]
@bessgreen These are such good questions, thank you!

1. No, when 'military base' is checked, this designation does not appear on the confirmed address screen. 

2. Yes, APO/FPO/DPO are 3 separate items & should come up through native dropdown. 

I also just realized that when 'military base' is checked, 'State' also should become a native drop down with the following options: 
- Armed Forces Americas (AA)
- Armed Forces Europe (AE)
- Armed Forces Pacific (AP) 

3. A user will need to have a valid address in their edit screen for Mailing Address before the 'save' button becomes activated. So if they delete their address and don't replace it, the save button will become inactive. Open to other mobile-friendly ideas you have about how to handle this.  

4. Yes - there is validation for these fields via the US Post Office. I haven't started this work yet but have a ticket for it [here](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13570).

**Comment by bessgreen** [comment]
@kreek will the address service give us the list of Countries & States that a user can choose from? (i.e. @bridgethapner - will these 2 fields open a native picker?)

**Comment by kreek** [comment]
@bessgreen on va.gov these are currently hard coded e.g. countries are [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/user/profile/vet360/constants/countries.json). It's not immediately clear where the states come from. There's also this [vets json schema library](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/constants.json) which gets loaded in.

We could move that into the mobile API. The data doesn't change very much, so it should at least be cached by the app. @jjulian this is part of the broader discussion of how to handle essentially static date (letter descriptions etc) that the app needs to load.

**Comment by jjulian** [comment]
I think it's reasonable to bundle the countries json file with the app, and do an app update if any global information changes. 

Your thoughts on bundling a master list of country names/codes in the app? @lexicalninja

**Comment by bessgreen** [comment]
@bridgethapner 
- Depending on which country the user selects from the picklist, will that alter the Address field options below? (Not all countries have a zip code, for example)
- Looking at the [US Post Office ticket](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13893) that you referenced earlier - if the integration with the USPS API / corresponding UX work is still in the backlog, we can make a separate ticket for this level of validation for a later sprint. Perhaps for this sprint, we can handle validation at the most basic level: ensuring that a user has entered some information for the 'Required' fields - and as long as this is true, the Save button is active. Thoughts? cc: @srmyers17

**Comment by lexicalninja** [comment]
> I think it's reasonable to bundle the countries json file with the app, and do an app update if any global information changes.
> 
> Your thoughts on bundling a master list of country names/codes in the app? @lexicalninja

This should be fine. There are only 195 countries so the size of this is way cheaper than api calls anytime we need it.

**Comment by lexicalninja** [comment]
> @bridgethapner
> 
> * Depending on which country the user selects from the picklist, will that alter the Address field options below? (Not all countries have a zip code, for example)
>

I just checked in VBMS and they have 3 options: US, International, and Military Base
International has Address 1, Address 2, Address 3, City, and Country. 

I also would be interested to know how the va.gov site handles this part of the addresses. I had to take a stab at this for an app and it can require some wild trade-offs. Each country has its own address style so you have to break the address parts all the way down to government areas and house number, then have a lookup for each country about what address fields they use and what order to display them in. Otherwise you just have like 1 or two and then bail out on the others. Or start with the top 4 and add as needed. 

And in the end it probably matters how the database is expecting the address more than anything. 

If time zones are the worst things, international addresses are finishing in the medals somewhere.

**Comment by srmyers17** [comment]
@bessgreen - I recommend proceeding with the basic validation for this sprint and adding a more sophisticated address validation later on.

**Comment by bridgethapner** [comment]
@bessgreen 
- Yes, the country list should use a native picker
- @lexicalninja thank you for looking into this! For internal addresses, let's include the following fields (screenshot below of how VA.gov handles international address, [quick mobile mock here](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/434404975_Edit_Mailing_Address_-International-)). 
1. Country (Required)
2. Street address 1 (Required) 
3. Street address 2
4. Street address 3
5. City (Required)
6. State (VA.gov uses "State/Province/Region" but that breaks the limits of characters our UI can accommodate, so let's stick with State for MVP) 
7. International postal code (Required)

- I like the idea of including address validation in a separate ticket. I'm starting that UX work today.


![Screen Shot 2020-10-12 at 1.17.53 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/e3cd2aec-fcd4-4e59-aade-92eca69a2020)

**Comment by digitalken** [comment]
Testing:

1. Tapping on an address field on the personal information page will take user to an edit page.
2. Verify styling and UI matches designs.
3. Verify page title indicates "Mailing address" or "Residential address", depending on user selection.
4. Verify edit page for addresses allows editing in "parts", i.e.::
  a. Country
  b. Street Address Line 1, Line 2, Line 3
  c. City
  d. State
  e. Zip code
5. Verify Country field is required and selecting it reveals a picklist.
  a. Verify that if user picks US from the list, the address fields above persist.
  b. Verify that choosing a country other than US changes the address fields (separate story)
6. Verify Street address fields:
  a. Verify address line 1 is required, with lines 2 and 3 optional.
  b. Selecting address lines will open the default QWERTY keyboard when user taps into the field.
  c. Verify a maximum of 35 characters for each field.
7. Verify City field:
  a. Is required.
  b. Selecting field will open the default QWERTY keyboard.
8. Verify State field:
  a. Is required.
  b. Verify selecting opens a picklist.
9. Verify zip code field:
  a. Is required.
  b. Verify selecting opens a number keyboard.
10. Verify that when user is going through similar fields, they keyboard remains open to avoid flickering.
11. Verify there is a Save CTA button in the top right corner. (Validation handled in another story.)
12. Verify page is read by screen reader.
13. Verify component types are announced by screen reader (name (title), role, value).
14. Verify OS can be scaled to maximum font without losing content, overlapping or horizontal scrolling.
15. Verify each touch target is minimum 44 px by 44 px.
16. Verify app can be traversed by tap or voice only.
17. Verify all elements on page may be traversed with auxiliary keyboard and focus on elements is clear.
18. Verify that when page opens, the first section or element is automatically placed in focus.
19. Verify when page opens, the title is announced.

**Comment by digitalken** [comment]
Added to TestRail

**Comment by esther-k** [comment]
UI and functionality pass. Accessibility does not pass with multi-issue accessibility bug entered. Moving this to Design QA for review

[Accessibility Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16395)
