### ISSUE TITLE
Flipper Insertion Request from eBenefits into CH36 Feature

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13905]
### Content support for:
- Unauthenticated (static) VA.gov pages
- Apps or tools
- Other writing or editing requests

### Engineering support for:
- Redirects that have **first been vetted by the VSP IA team**  
- ✔ REACT sign-in widgets or feature flags (flipper)  
- Other engineering support  

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [x] Post a link to this issue in [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites) in Slack, tag @Danielle Thierry and @Brian Lloyd. If your request includes engineering support, also tag @nick and @Kelson Adams.
- [ ] If noted in the guidance below, please schedule any relevant meetings. *(already met)*

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * We would like to have our feature toggle (flipper code) inserted into [the unauthenticated landing page for the CH36 feature](https://staging.va.gov/careers-employment/education-and-career-counseling/)
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   *  [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling) (full folder)
---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ ] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)  

- [ ] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * < URL list >
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * < list of new info >
   * **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * < list of new info >

- [ ] **Writing support for new app/tool** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @Danielle Thierry and @Brian Lloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs. [View Danielle's calendar](https://outlook.office365.com/calendar/published/b2a32b65cdbd4a218f7c0461ab4e41c1@va.gov/82b0e0b178934e80b2190b37e41a14668122172627511760876/calendar.html)   

- [ ] **Editing support for app/tool** <br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - < scope >            

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [x] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - [eBenefits CH36 Flipper creation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13129)
     - [Merged PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4901)
   * **Flipper unique id:** 
     - unique id: `chapter-36-cta`
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* ?We would like to start UAT by the end of the month

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: *eBenefits*
- DEPO product owner: *Steve Kovacs*
- Product manager: *Jason Wolf*
- Designer: *Jim Adams*
- FE engineer: *Micah Chiang / Jesse Cohn*
- Product/team Slack channel: *#vsa-ebenefits*

--- 
#### Acceptance Criteria
- ~Convert this request into a Zenhub epic~
- [x] Follow-up with requestor to address any lingering questions/concerns
- ~Create epic/tickets as needed for the Public Websites team to implement~
- [ ] CTA is inserted onto https://staging.va.gov/careers-employment/education-and-career-counseling/

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by MickinSahni** [comment]
Hey @jason-gcio @micahchiang have you created the CTA? If so, can you point us to it?

**Comment by jason-gcio** [comment]
@MickinSahni - Per Micah: The unique ID for this widget is `chapter-36-cta`. So the full attribute needed will be `data-widget-type="chapter-36-cta"`

**Comment by MickinSahni** [comment]
> @MickinSahni - Per Micah: The unique ID for this widget is `chapter-36-cta`. So the full attribute needed will be `data-widget-type="chapter-36-cta"`

@kelsonic need any more info?

**Comment by kelsonic** [comment]
Awesome! I see that it's implemented in `vets-website` now 👍 So next step would be to coordinate with @RLHecht on inserting their CTA widget (`chapter-36-cta`) into your content page(s)! 🙂

**Comment by jason-gcio** [comment]
🤘

**Comment by MickinSahni** [comment]
Great. We talked about this in our planning—we're scheduling it for sprint 32. But it's available for pickup this sprint if there's bandwidth. @RLHecht, please let the group know here if you need any other info! Thanks, team.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Can you, @bethpottsVADEPO, and I sync on this early next week? I want to make sure that Beth is up to speed since she works with the Ch 36 SMEs. Thanks!

**Comment by RLHecht** [comment]
@jason-gcio are we able to see what the content looks like for when the flipper is turned on vs. off? I'm able to see the subway map and the button when I put in the widget but we wanted to see what the other state is as well.

**Comment by jason-gcio** [comment]
@RLHecht - Yep!  Here is our original ticket that shows both path ways: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13129

**Comment by RLHecht** [comment]
@jason-gcio Confirming here that the PW team would like to hold off on putting in the widget until the rest of the work is being done in January. We don't want this to be accidentally published before the date if we have to make other changes to the page in the interim. Drupal doesn't allow for multiple versions so we would either need to revert to an earlier version or undo edits. FYSA @bethpottsVADEPO @DanielleThierryUSDSVA

**Comment by brianalloyd** [comment]
@jason-gcio wanted to validate that you've seen @RLHecht comment and recommendation?  Also wanted to explore next steps on this to ensure we're not losing the bubble on the requested support.

**Comment by jason-gcio** [comment]
@brianalloyd - Yep, thanks for following up.  Given @RLHecht's note, we are going to pause moving forward until end of Nov/early Dec to start up again.  The work to put in the flipper component shouldn't be changing on our end but we wanted to leave time to test and get the feature situated before launch.  End of the year is hectic with holiday freezes so we want to avoid those conflicts as well.

**Comment by jason-gcio** [comment]
@brianalloyd @RLHecht @bethpottsVADEPO @DanielleThierryUSDSVA -

I wanted to circle back to this real quick and make sure our timelines were laid out a little better, apologies for the lack of detail on my part.  

- The CH36 folks that are looking for this feature are expecting a go live date of January 4 (the first Monday of 2021).  
- I requested our staging review to be December 3, 2020 to allow time for final deployments and UAT ahead of, and around, the holidays.
- I think that having the flipper component installed a week, or maybe even a sprint, ahead of that would be a good idea so we can test it and make any last minute updates.  

Would it be possible to schedule this installation for the middle of November?  Sprint 35 starts on November 18, 2020 (week after this has a freeze IIRC).  I don't think we have any other changes on our end for this landing page.

Thank and please let me know if there is another day that works better.
cc: @steve-gov

**Comment by brianalloyd** [comment]
@jason-gcio thanks for circling back with an update, Sprint 35 should work unless @RLHecht @bethpottsVADEPO @DanielleThierryUSDSVA have any objections or perhaps more time is needed to complete the required work flows.

**Comment by RLHecht** [comment]
This page is now published with the widget. Here's the preview link: preview-prod.vfs.va.gov/preview?nodeId=720 FYSA @jason-gcio @cohnjesse 

Moving ticket to validate.

**Comment by RLHecht** [comment]
These changes are live on the site. Closing ticket.

**Comment by brianalloyd** [comment]
Thanks @RLHecht @jason-gcio let us know if any questions remain.  Thnks.
