### ISSUE TITLE
View direct deposit info

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13902]
### User story

As a veteran, I can view and manage my direct deposit information for disability compensation and pension benefits.

### Acceptance Criteria
1. Styling and UI matches the design
2. A header appears that includes the user's bolded first name and last name on top, and the military branch they served in on the bottom. The military branch's seal should be displayed to the left. 
3. Current direct deposit account information is displayed: 
     - bank name
     - last 4 digits of account number
     - account type
4. Null state for this account banner: "Please add your bank account information"
5. Include subtext at the bottom of the page:
     - Time zone is hard-coded to E.T. (there is a future story for converting timezones based on user location)
6. Two phone numbers on the screen, styled as hyperlinks
     - Click-to-call capability on both hyperlinks. Upon selection, the selected number appears in the native call banner (e.g. in iOS, these are 2 stacked banners at the bottom of the screen: the top banner displays the phone number, and the bottom banner displays Cancel)
     - Selecting the number from the call banner will dial the number via the user's phone app

### Designs
null state (no account added): https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636875
account added: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636875

### Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.

### Accessibility Implementation Guidelines 
- Specify "Direct Deposit" as Header 1

Banner
- Veteran Name
   - Title= “Veteran First Name, Middle Initial, Last Name” e.g. Jerry M Brooks
   - accessibilityRole= “text”
- Military Branch 
   - Title= “Military Branch Name” e.g. United States Air Force
   - accessibilityRole= “text”
- Military Branch Image 
   - Title= “Military Branch Seal” e.g. United States Air Force Seal
   - Role= “image” 

Direct Deposit Info Section
- Specify "Direct deposit information" as Heading Level 2
- Text/ numbers in Account Field should simply be marked as text
- Right caret should be marked as accessibilityRole= button
     - accessibilityLabel= "Edit this information" 
     - accessibilityHint= "Navigates to a new page where you can edit your direct deposit information" 

Phone Number Hyperlinks
- Phone icons - accessibilityRole= “image”
- Number - accessibilityRole= “link”, accessibilityHint= “Dials this number via your device’s call function”

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
Questions :

1. UI when the account info is null?

@bridgethapner

**Comment by bridgethapner** [comment]
Hi there @bessgreen -- Per a UX Review Meeting I had with VA this morning, there are a couple of minor changes to this design: 

- Adding click to call (documented in #13073)

**Comment by bessgreen** [comment]
Thanks @bridgethapner - from a design standpoint, does adding click-to-call on the Direct Deposit screen just mean that we're stylizing the two numbers as hyperlinks? Or will the UI change so that the two numbers are stacked vertically with a blue phone icon, similar to some of the [other](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432493860) click-to-call pages?

**Comment by bessgreen** [comment]
@bridgethapner saw you added new screens for null states with the updated UI for the phone numbers - thank you!! :)

One other question regarding AC # 5 and any case where we're displaying timezones: can you confirm whether or not this time zone should update to reflect the user's local time (including international timezones)? If so, is this based off the user's phone location?

**Comment by jjulian** [comment]
Wherever we are showing time to the user, lets coordinate with @kreek to be sure we want to display in local TZ (vs facility TZ, for instance)

**Comment by bridgethapner** [comment]
@bessgreen 

- The [wireframes](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432050367) show the updated design for click-to-call, it will be stacked with icons + text buttons like other pages.
- Regarding the question about time zones, displaying times in the time zone that's local to the user's phone location seems like a bonus, but not a requirement. If it's relatively low effort, let's do it. We can chat more later today. 
- And yes, if we do it, let's use the user's location data -- I do not want to use any registration at VA facilities information because Vets can be registered at facilities all around the country and we may not know their primary one.

**Comment by digitalken** [comment]
Linked issue:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14908

**Comment by digitalken** [comment]
(Design of no account added:  https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432050367 )

Testing:

1. Very styling and UI matches designs.
  a. Need account info with and without bank account added.
2. Verify Head contains bold first and last name on top with military branch they served in under the name, along with service icon.
3. Verify current banking information is displayed:
  a. Bank name
  b. last 4 digits of account number
  c. account type
4. Using account with no bank account added, verify the banner "Please add your bank account information" is displayed.
5. Verify text at bottom of the page indicates that times are in eastern time.
6. Verify two phone number tap to call links are included.
  a. Verify number will dial from link.
7. Verify screen reader will read screen in a logical order.
  a. Any buttons will be read with name (title), role, value.
8. Verify back button takes user to previous page.
9. Set device to largest font and verify page still functions correctly and is readable.
10. Verify app operates by tap only with no needed gestures.
11. Buttons and links need to have a minimum 44px by 44px size.
12. Test page using auxiliary keyboard for navigation, focus, logical traversal.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Pass 11/11/2020 - Accessibility failed for Android with keyboard, bug logged. Moving this story to Design QA.
