### ISSUE TITLE
Edit direct deposit info (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13907]
### User story
As a user, I can edit my saved direct deposit banking information

### Acceptance Criteria

1. Selecting the Account summary banner routes user to a new page where they can enter/edit bank information
2. Styling and UI matches the design
3. The first section is expandable so users can learn where to find their bank routing and account numbers. Tapping the downward caret expands this section and converts the down-caret to an up-caret. Tapping the up-caret collapses this section.
     - Expanded section reveals an embedded image (.png attached below)
4. 3 separate text input boxes where users can enter their routing number, account number and account type
     - These fields are always unfilled, even if the account already has bank information saved
     - Tapping the Routing number and Account number fields will display a numerical keyboard. The keyboard should stay open when a user is tapping from field to field.
     - Tapping the Account type field displays a native dropdown with two options: "Checking" and "Savings"
5. Character limits and requirements:
     - All 3 fields are required
     - The Routing number can be no more than 9 digits
     - The Account number can be no more than 17 digits
7. At the top-left, users can exit this page and return to the main Direct Deposit page by tapping Cancel.

Note: Disregard the confirmation checkbox at the bottom of the screen AND the Save button. This is covered in a separate [story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14714). 

### Designs
[https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636876](url)

### Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 

- Mark page title as Header 1 (e.g. “Mailing Address”)
- Save button in top right
     - accessibilityRole = “button”
     - accessibilityLabel = “Save changes” 
     - Denote when button becomes disabled vs. enabled
- Ensure the dropdown area is marked appropriately (additional investigation will be needed to determine appropriate properties)
    - Check image guide: accessibilityRole= image.
          - Alt text: "You can find your 9-digit routing number on the bottom left side of a check. You can find your account number in the bottom center of a check."
    - Ensure this area does not "trap" the keyboard focus
- Mark all fields as text input
     - Include necessary props 
     - Denote if filled vs. unfilled. If unfilled, denote placeholder text
     - Denote requiredness 
     - If an error occurs, announce error and provide suggestion

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

![direct-deposit-check-guide.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/924cf190-b1f5-4fe3-b02f-12513dbfecb2)

**Comment by bessgreen** [comment]
Questions: 

1. Currently, Account Type is a text input field, but if the field has a limited set of acceptable answers, i.e. Checking or Savings. his should be a drop-down menu or radio button selection, to reduce user errors]

**Comment by bessgreen** [comment]
Questions: 

1. Currently, Account Type is a text input field, but the field has a limited set of acceptable answers (Checking or Savings). Should this be a native drop-down menu or radio button selection to reduce user errors? 
     - If so, are Checking and Savings the only 2 options we need to account for? 

@bridgethapner

**Comment by bridgethapner** [comment]
@bessgreen Yes - Account Type should be a native drop-down and the two types are "Checking" and "Savings"

**Comment by bridgethapner** [comment]
Hi there @bessgreen -- Per a UX Review Meeting I had with VA this morning, there are a couple of minor changes to this design:

- I removed any error states here and edited the field labels to reflect the character limits (documented in #13073). 
- We'd like to use an aria-label to read the check image (e.g. your account number can be found...) to ensure it's accessible.

**Comment by bessgreen** [comment]
@bridgethapner Thanks! Regarding the character limits - will this be communicated to the user, or will we just prevent them from entering a character once they've reached the limit?

**Comment by b-rocha** [comment]
Hi @bridgethapner - what should the alt text for the check image say/ how should we describe this?

**Comment by bridgethapner** [comment]
@b-rocha @bessgreen For alt text let's say: **You can find your 9-digit routing number on the bottom left side of a check. You can find your account number in the bottom center of a check.**

**Comment by bridgethapner** [comment]
@bessgreen Re character limits - I think we've covered in communicating to the user thru [the field labels](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636876). Per the UX documentation [here](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13073), let's also: 
- Set a character limit of 9-digits on the Routing number field
- Set a character limit of 17-digits on the Account number field

**Comment by bridgethapner** [comment]
@bessgreen @jmarchi here is a link to the png of the check guide asset on vets-website: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/assets/img/direct-deposit-check-guide.png

**Comment by digitalken** [comment]
Testing:

1. Verify selecting Direct Deposit Information banner from Direct Deposit page opens the direct deposit account summary screen where user may enter/edit bank information.
2. Verify styling and UI matches designs.
3. Verify the expandable box opens and closes and that it displays information as to where to find account numbers on a check.
  a. Verify caret mark is down when box is collapsed and up when box is expanded.
4. Verify three separate text input boxes where users can enter routing number, account number and account type.
  a. Verify fields never have existing information (always unfilled when opened.)
  b. Verify tapping routing and account number fields will display a numerical keyboard.
  c. Verify tapping the account type field displays a native dropdown with top options:  Checking and Savings.
5. All three fields are required.
  a. Routing number can be a maximum of 9 digits.
  b. Account number can be a maximum of 17 digits.
6. Verify user can exit page by tapping Cancel button at top left.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
UI passes with a minor bug entered. Accessibility does not pass with a multi-issue bug entered. Moving this to Design QA for review

[UI Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16134)

[Accessibility Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16174)
