### ISSUE TITLE
Release "beta" version of Profile with Direct Deposit feature enabled

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#1391]
To prepare for UAT which begins the week of Sept 1, we need to release a version of the Profile app that has the Direct Deposit un-gated. This "beta" version of the Profile will live alongside the standard Profile, it will not replace it. The "beta" version of the Profile should live at `va.gov/profile-beta`

**Comment by Justin-Pickett** [comment]
this feature has been released. Currently in UAT. Closing this ticket.
