### ISSUE TITLE
[Design] Healthcare: View your lab and test results 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13922]
## Background
See [Design plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/product/LIH-outline-and-timeline.md)
Note: link shown conditionally if someone has health care in general

## Tasks
- [ ] Appropriate stakeholder reviews and approvals have been completed

**Comment by Samara-Strauss** [comment]
Reminder: "View your lab and test results" Is just a link, and there is no "section" to design in the same way we are designing the prescriptions or messages section. I think we can either leave this ticket to remind ourselves that we need to include this link, **or** we can roll this into the Healthcare Overview section (#13918) ticket and just make sure that including the "View your lab and test results" link is a requirement.

**Comment by tressaellen** [comment]
@Samara-Strauss @callen2563 I'd like to keep this ticket as a separate task because I'd like to put a little thought into how we're displaying things that are just links. I don't expect it to be time consuming at all, I just want to make sure we have the time allotted. Once we figure out how we're displaying links then we won't need a separate ticket for each one.

**Comment by Samara-Strauss** [comment]
Sounds good to me! Thanks for letting me know, @tressaellen.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen We will be reviewing these designs on Wednesday but wanted to post progress so far. 
![Uploading LIH - Desktop - Healthcare - Multi Card.jpg…]()

**Comment by callen2563** [comment]
Great! This is so good to hear that we are on the right track so far! 👍🏼 I have made the edits you mentioned in the feedback document and will work on adding some iconography next and a treatment for the new number of messages, appointments etc
![LIH - Desktop - Healthcare - Multi Card](https://user-images.githubusercontent.com/68560244/95266212-998e1f00-07e7-11eb-9012-4b3d003ad4e8.jpg)
![LIH - Desktop - Healthcare - Unahppy Path :(](https://user-images.githubusercontent.com/68560244/95266227-9eeb6980-07e7-11eb-9f42-21a038626d68.jpg)

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen Hey ladies, here are the latest mocks. I've added a table header on desktop and went though and cleaned up some areas and incorporated the latest feedback. Let me know if I missed any thing. Thanks!
https://cassandraallen738782.invisionapp.com/overview/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/screens
https://cassandraallen738782.invisionapp.com/overview/HP-mobile-logged-in-ckeyhydog01kz01xd3tao5pcj/screens

**Comment by Samara-Strauss** [comment]
All of my feedback is in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13920#issuecomment-708414228) of the secure message ticket. Not going to repost here, so you can go there or [check the feedback doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/design-ia/samara-design-feedback.md#feedback-101420).

**Comment by Samara-Strauss** [comment]
Closing. We've done a lot of exploration of this section, so I am considering this ticket done. [Here's where the design stands as of now](https://cassandraallen738782.invisionapp.com/console/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/ckgb2sajy019u01as9gd12s97/play#project_console). We'll open new tickets as needed for any updates or copy work.
