### ISSUE TITLE
CT: Update Comparison Tool question content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13929]
As a comparison tool user, I need the questions and content on the landing page of the tool to clearly communicate the information that is trying to be gathered, so I can accurately answer the questions to get the best results.

## Assumptions:
1. This work is behind a prod flag. 
2. This story does not affect VET TEC search results page. 

## Acceptance Criteria
1. The "Type of institution" label is replaced with "Select an institution"  on the Landing Page

1. The "Select an institution type" label is replaced with "Select an institution" on the Search Results Page

2. The "Enter a school, location, or employer name" question label is replaced with "Enter a school, employer name, city, or zip code"
    a. On the Landing Page
    b. On the Search Results Page

3. The "How do you want to take classes?" question label is replaced with "Will you be taking any classes in person?"
    a. On the Landing Page
    b. On the Search Results Page
    c. On the Profile Page

4. The available answers to "Will you be taking any classes in person?" are: Yes (default selection on page load), No
    a. On the Landing Page
    b. On the Search Results Page
    c. On the Profile Page
    d. Answering "Yes" to "Will you be taking any classes in person?" is equivalent to selecting "In person only" or "In person and online" in the old question
    e. Answering "No" to "Will you be taking any classes in person?" is equivalent to selecting "Online only"

5. Will you be taking any classes in person?" has a "(Learn more)" link with the following content:
    a. On the Landing Page
    b. On the Search Results Page
    c. On the Profile Page

    > **Your housing allowance is determined by where you take classes**
    >
    > Under the GI Bill you’re eligible to receive a monthly housing allowance. We calculate this monthly housing allowance based on where you take classes.
    >
    > If you use Post-9/11 GI Bill benefits to take at least 1 in-person class, your housing allowance is based on where you do most of your coursework. If you take online courses only, your housing allowance is based on 50% of the national average.
    >
    > Through Dec. 21, 2020, current and new students can receive in-person allowance rates if their school’s approved program changed from in-person to online learning due to COVID-19.
    >
    > [View the current housing allowance payment rates](https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp?_ga=2.144591223.39405460.1542131207-1582256389.1508352376).

6. The page matches the layout and structure as specified:
    a. In Supporting Artifact # 1 when viewed on a desktop device
    b. In Supporting Artifact # 2 when viewed on a mobile device

### Note
- Applicable e2e tests should be updated.

## Supporting Artifacts:
1. [Desktop Prototype v3](https://bahdigital.invisionapp.com/share/PVIAEVAXHK7#/screens) as of 09/23
2. [Mobile Prototype v3](https://bahdigital.invisionapp.com/share/86IAEWNCF27#/screens) as of 09/23
3. [Content Document v3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/1d2a2c1135bd5b00d16d48e227a756df8e21494b/products/education-careers/school-comparison-tool/search/design/content-doc-v0.3.md) as of 09/23

**Comment by hughes-dustin** [comment]
branch: bah-13929
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14444

**Comment by hughes-dustin** [comment]
Prod flags in files: 

1. src/applications/gi/components/search/InstitutionFilterForm.jsx
2. src/applications/gi/components/search/InstitutionSearchForm.jsx 
3. src/applications/gi/components/search/LandingPageTypeOfInstitutionFilter.jsx
4. src/applications/gi/components/search/OnlineClassesFilter.jsx
5. src/applications/gi/components/search/SearchResultTypeOfInstitutionFilter.jsx
6. src/applications/gi/containers/Modals.jsx
7. src/applications/gi/containers/LandingPage.jsx

**Comment by desireeturner** [comment]
We are going to wait to move forward with this work until #13364 (removal of feature flag that some of this functionality is behind) is complete. It has been added as a blocker.

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-15 at 5.39.00 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/80951a83-ceca-4fd1-80ab-81cc8108a4d7)
##
![Screen Shot 2020-10-15 at 5.39.39 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7e47def2-97af-42a8-b005-a3473ea77d40)
##
![Screen Shot 2020-10-15 at 5.40.21 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/718b7fa6-b55e-4a29-ba95-9e8367cdcf67)
##
![Screen Shot 2020-10-15 at 5.40.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7f2f3843-16fd-4dd3-9ad2-4830ce27e702)
##
![Screen Shot 2020-10-15 at 5.52.09 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f5013f0f-b2cc-4948-8c4d-d281eb0aff46)
##
![Screen Shot 2020-10-15 at 5.52.51 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bd765edb-59f2-4722-bdea-b27cdc27c1a7)
##
![Screen Shot 2020-10-15 at 5.53.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2c589613-8b0e-401c-9825-d7d00c7307b6)
##
![Screen Shot 2020-10-15 at 5.54.06 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bcfbeec6-eb3a-47fe-8872-6c0819c18592)
##
![Screen Shot 2020-10-15 at 5.54.26 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/71bd3432-a211-46c0-8302-52c2ca9592f6)
##
![Screen Shot 2020-10-15 at 5.54.38 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7a70ecb8-560f-4e0a-8afd-72e2cbf5f2f9)
##
![Screen Shot 2020-10-15 at 5.54.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ae2b2d89-ef40-4750-a53f-446fe567eaf9)

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14612

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-16 at 10.07.10 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6508fbb3-4a1d-4a7b-8a6e-ee2ef4d0ced7)
##
![Screen Shot 2020-10-16 at 10.07.27 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5d199a54-1166-453d-aa5d-541f1784eca8)
##
![Screen Shot 2020-10-16 at 10.08.20 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8e66c4b1-d6f1-4198-be71-5a1e08c6617f)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah is ready for review

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/13124&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by amyknox** [comment]
Housing allowance modal heading is too tight to the top of the modal window and crowds the (X) 

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/656f421d-9309-437a-b8e7-7c10c57b784c)

**Comment by watersemma** [comment]
Looking good. I agree with Amys comment above. Otherwise the findings I commented in [13938](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13938) should persist here as well.

**Comment by hughes-dustin** [comment]
> Housing allowance modal heading is too tight to the top of the modal window and crowds the (X)
> PC / Chrome
> 
> ![image.png](https://camo.githubusercontent.com/51598fb49f9a708c111fd7b5c678bbe2788c9bf1/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562353165613339386331613736323864393231386134322f36353666343231642d393330392d343337612d623865372d376331306335376237383463)

The issue looks like the scrollbars that appear in Chrome on Windows. The scrollbars are pushing the "X" out of its position. I'll see if we can get rid of the scrollbars but expect that not being possible without resizing something on the modal.

**Comment by desireeturner** [comment]
@amyknox mentioned she is also seeing the above issue in Firefox.

**Comment by sonntag-adam** [comment]
Bug for scroll bar fix https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15111

**Comment by sonntag-adam** [comment]
Closing out story.
