### ISSUE TITLE
CT: Update Search Results Page Content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13938]
As a comparison tool user, I need the questions and content on the landing page of the tool to clearly communicate the information that is trying to be gathered, so I can accurately answer the questions to get the best results.

## Assumptions:
1. This work is behind a prod flag. 
2. This work is specific to non VETTEC search results.

## Acceptance Criteria
1. The "Refine search" header label is replaced with: "Search by keyword"
2. Selecting an auto-complete value from the "Enter a school, employer name, city, or zip code" does not cause the search to automatically happen.
3. A "Search" button is added after the "Enter a school, employer name, city, or zip code" input.
    a. Clicking the search button will refresh the search results using the filter criteria and free text search.

4. The following content is added after the "Search" button and before the "Country" input:
    > **Refine search**
    > 
    > Make changes below to update your results:
6. The question "Select an institution [type]" answer "Employers only (OJT, apprenticeships)" is replaced with: "Employers (On-the-job training [OJT], apprenticeships)"
    - Note: This will now match the landing page answer value

7. On mobile:
    a. Clicking the "Search" button collapses the filters panel and displays the search results.
    b. The "See Results" button label is replaced with "See Results (NN)" where NN is the current number of results based on the search and filter selections.

8. The "Institution categories" question label is replace with: "Type of school or employer"

9. The page matches the layout and structure as specified:
    a. In Supporting Artifact # 1 when viewed on a desktop device
    b. In Supporting Artifact # 2 when viewed on a mobile device

### Note
- Applicable e2e tests should be updated.

## Supporting Artifacts:
1. [Desktop Prototype v3](https://bahdigital.invisionapp.com/share/PVIAEVAXHK7#/screens) as of 09/23
2. [Mobile Prototype v3](https://bahdigital.invisionapp.com/share/86IAEWNCF27#/screens) as of 09/23
3. [Content Document v3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/1d2a2c1135bd5b00d16d48e227a756df8e21494b/products/education-careers/school-comparison-tool/search/design/content-doc-v0.3.md) as of 09/23

**Comment by desireeturner** [comment]
We are going to wait to move forward with this work until #13364 (removal of feature flag that some of this functionality is behind) is complete. It has been added as a blocker.

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14580

**Comment by delli-gatti-michael** [comment]
Testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/1025

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by watersemma** [comment]
Hey, looking good. Here are a few things I spotted: 

1. Search by Keyword should be updated to <H3> 
![1.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/7e40d1b5-c98a-45c7-9f50-83a37657a691)
2. College search box margin should be updated from 3.2 px to 6px to match
![2.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/1d40ca96-44ce-4792-a56e-f148ddb604f4)
3. Adjust alignment of 'Exclude results with warnings or closings' checkbox 
![3.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/31b5ba25-d7cc-4a71-93cf-e5fc4d78bbe7)
4. Update 'programs' margin  from 16 px to 24 px to match
![4.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/c08eaad8-f166-43e0-a8a7-b699155764ff)
5. Military details and housing allowance should each have a 12px margin to give more space after independent study.
![5.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/8d203235-dbc2-4f31-b31d-09ad53128f94)

**Comment by ksantiagomorgan6** [comment]
Styling updates PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14631

**Comment by delli-gatti-michael** [comment]
1 and 2 from the UX feedback are fixed in the PR above. 3-5 should be covered by a separate story

### 1
![Screen Shot 2020-10-20 at 9.26.16 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/533898fb-3be1-4d79-8c70-ad1ce14d4816)

---

### 2
![Screen Shot 2020-10-20 at 9.27.01 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/5468a8ed-c572-4f27-b398-6720773a0eb2)

**Comment by dneel-bah** [comment]
3&4 are covered in story: #15054.
5 will be left alone until that functionality has gone through another round of usability testing.

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah the updates for 1 and 2 are now in staging

**Comment by ksantiagomorgan6** [comment]
additional PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14655

**Comment by delli-gatti-michael** [comment]
Local testing complete on PR \#3

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah The most recent changes are now live on Staging and ready for review

**Comment by JenLJ** [comment]
UX Review 1/2:  This looks good!

**Comment by amyknox** [comment]
UX Review - 1/2 Looks great!

**Comment by delli-gatti-michael** [comment]
Closing this out
