### ISSUE TITLE
On-Site Search: Generate a sitemap XML file via Facilities API

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#13939]
## Issue Description
In order to improve search discovery for veterans seeking local facility information on VA.gov, a sitemap XML file should be generated via the Facilities API

## Front end tasks
@ncksllvn to add details here:
- [ ] TBD
- [ ] TBD

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@ncksllvn Would you be able to add some information about the tasks and discuss with @srsuddath

**Comment by denisecoveyduc** [comment]
Jan 13 - This is a low priority and will require discussions with Dave Conlon to proceed

**Comment by ncksllvn** [comment]
The gist of this work is to boost the search rankings of the facility detail pages by providing an XML sitemap or including them in the existing `va.gov/sitemap.xml` somehow. A facility detail page looks like this -> `https://staging.va.gov/find-locations/facility/{{ facility ID }}`. For example, here is my local Florence facility's facility detail page, `https://staging.va.gov/find-locations/facility/vha_539GD`. Right now there is no index (sitemap) for them.

I am not really sure the best way to do this but my idea was to add a new API method into the existing Facilities API that would return an XML sitemap. Because this is XML, work can't be done from the FE code.

```xml
<!-- 
   https://staging-api.va.gov/v1/facilities/va/sitemap.xml 
   Retrieves all facilities from the DB then iterates across them to generate an XML file.
-->
<urlset>
    <url>
        <loc>https://staging.va.gov/find-locations/facility/vha_539GD</loc>
    </url>
     <url>
        <loc>https://staging.va.gov/find-locations/facility/vha_123</loc>
    </url>
    <url>
        <loc>https://staging.va.gov/find-locations/facility/vha_456</loc>
    </url>
</urlset>
```

Then we just need to let Google and other search crawlers know that this sitemap exists. I think we would do this by linking to it from a metatag in the website `<head>`. Here's an article here about it, https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps.

**Comment by kelsonic** [comment]
Is this still relevant work to groom? CC @brianalloyd
