### ISSUE TITLE
Add Sentry Events for CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13936]
## Background
Sentry is a tool that allows us to view and be notified of errors that might appear in our feature.  We want to add CH36 to Sentry so that we can see if there is an issue and hopefully resolve it before any one is negatively impacted.

## Tasks
- [x] Add CH36 feature events to Sentry

## Acceptance Criteria
- [x] CH36 is wired up to Sentry

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4939

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4939
