### ISSUE TITLE
[PM] Review Direct Deposit feature on eBenefits

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13937]
## Background
As we work on moving over Direct Deposit for Education benefits it would be beneficial to gain a deeper understanding of this feature and eBenefits. 

## Tasks
- [x] Connect to VA network and log into ebenefits
- [x] Review the direct deposit feature on eBenefits

**Comment by mshea0606** [comment]
![image](https://user-images.githubusercontent.com/60523453/95247497-ee2f9b00-07e3-11eb-8c0c-c691346b15eb.png)

Staging user: vets.gov.user+3@gmail.com

**Comment by mshea0606** [comment]
@Samara-Strauss , I just reviewed the edu Direct Deposit feature on ebenefits with Jason Wolf and Jim Adams. Let me know if/when you would like to meet to discuss it. Thanks!

**Comment by Samara-Strauss** [comment]
I actually don't think we need to meet to review. I removed that requirement from the task list. Closing, and thanks!
