### ISSUE TITLE
View / edit address before opening letters & docs

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13940]
### User story
As a user visiting the Letters and Documents page, I want to see a page displaying my current mailing address, so that I can confirm that this address is valid or edit the address if it's incorrect.

### Acceptance Criteria

1. Tapping on/ selecting the Mailing address from the Letters overview page takes the user to the mailing address edit page
     - In this case, hitting "Cancel" or "Save" on the Mailing address edit page should route the user to the Letters landing page

### Designs
Letters landing page: [https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636878](url)
Mailing address edit page: [https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432053040](url)

### Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 
- Mark page title as Header 1 (e.g. “Mailing Address”)
- Cancel button in top left
     - accessibilityLabel = "cancel"
     - accessibilityHint= “Go back to the letters landing page”
     - accessibilityRole = “button”
- Save button in top right
     - accessibilityLabel= “Save”
     - accessibilityHint= “Saves changes and takes you back to the letters landing page”
     - accessibilityRole= “button”
     - accessibilityState= Denote when disabled vs. enabled
- Checkbox
     - accessibilityLabel= “I live on a United States military base outside of the United States”
     - accessibilityHint= "Confirms you live on a base outside of the United States"
     - accessibilityRole= “checkbox”
     - accessibilityState= Denote when checked vs. unchecked
- Mark all fields as text input
     - Include necessary props
     - Denote if filled vs. unfilled
     - If unfilled, denote placeholder text
     - Denote requiredness
- If an error occurs, announce error and provide suggestion
### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions:

1. Verify AC # 2: Do we want the user to go to the mailing address edit page? If so, should we create a copy of that page that's organized under "Letters and Documents"? Otherwise, if we drive the user to the main mailing address edit page under Personal Contact Info, they'll have to navigate back to Letters & documents
2. Do users always see this page to remind them of their address on file? Or do they only see it upon first visit? 

@bridgethapner

**Comment by bridgethapner** [comment]
@bessgreen 

1. Yes, we want users to go to the Mailing Address page. Creating a copy that lets them stay in Letters shoulds great.

2. They see this page every time.

**Comment by digitalken** [comment]
Added to TestRails.

**Comment by esther-k** [comment]
**11/20**
UI and functionality pass. Accessibility fails with a [bug entered](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16491). Moving to Design QA for review
