### ISSUE TITLE
[Discovery] CST: Look at Exam Scheduling Info

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#13948]
## Issue Description
One of the top priorities from NCC is the ability to integrate with the exam scheduling capability.  This story is to find the right people and begin to understand how the exam scheduling stuff looks and how it would look if integrated into CST.  This is not expected to produce high fidelity designs.

> Allow the Veteran to easily view exam information (scheduled date, contact information, etc.) and to submit a request to reschedule an exam if necessary.

## Acceptance Criteria
- [x] Low fidelity design concepts
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Initial concepts/wireframing has been completed for this effort. Note: It's important to understand where this falls in regards to CST enhancement efforts.
