### ISSUE TITLE
Service Verification letter

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13942]
## User story

As a user, I want to see a description of my  **Service Verification** letter with the option to view it on my device. 

## Acceptance Criteria
1. Styling and UI matches the design 
2. Letter description below the title
     - This is static content
3. Pull in Mobile Alert common component
     - This is static content
     - Note: This 'alert' is specific to the SV letter. We don't expect to have this alert for the other letter types
4. View letter button 
     - Pull in Large Button common component (downloading/viewing the letter is covered in a separate story)

## Designs:
Service Verification letter summary: [https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636880](url)
Letter: [https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636881](url)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - accessibilityLabel = "back"
     - accessibilityHint = “Go back to letter list"
     - accessibilityRole = “button” 
- Mark "Letters" as Header 1
- Mark "Service Verification Letter" as Header 2
- For info box:
     - Treat as static text 
- View Letters Button
     - Title= “View Letter”
     - accessibilityHint= “View your letter so you can save it to your mobile device."
     - accessibilityRole= “button”

## Dev checklist

- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions:

1. AC # 3 : when does this appear? Do all users see this? Is this always the same message or can the letter names be switched out?

**Comment by bridgethapner** [comment]
1. This is an alert that is triggered by the Alerts API and only displays when there is a relevant alert for that letter. 

2. & 3. I believe all letters aside from Benefit Summary and Service Verification are download only. I'm not 100% sure -- @kreek can you confirm this via the API?

**Comment by kreek** [comment]
Benefit Summary is only one that has options when generating a download: https://github.com/department-of-veterans-affairs/vets-website/blob/7e40a773626d8f0f58742fed6c90f9586707db6c/src/applications/letters/actions/letters.js#L95-L105

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/20**
UI and functionality pass (need to verify bug fixes on iOS when new build is available). Accessibility fails with a [bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16512) entered. Keeping in QA for iOS verification
