### ISSUE TITLE
Benefit Summary & Service Verification letter

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13947]
### User story
As a user, I want to customize my **Benefit Summary and Service Verification** letter so that I can use it for multiple purposes (such as housing assistance, tax relief, etc.).

### Acceptance Criteria
1. Styling and UI matches the design 
2. Top section includes title and letter description 
3. Second section displays the user's military service information: discharge type, active duty start, separation date.
4. "Include military service information" toggle. Toggling this on will include the 3 items above (Discharge type, Active duty start, Separation date) in the rendered letter.
5. The last section, "VA benefit and disability information" has 4 configuration options that can be toggled on and off.
     - Toggling this on will include this verbiage in the rendered letter. 
6. Content in each option is service-driven (e.g. '$XXXX' in the designs)
7. "View letter" UI (download/view letter is handled in a separate story)
8. Create "Send a message" UX/UI (this is specific to the Benefit Summary letter)
     - Update common component w/ arrow button
     - Include static copy above the hyperlink
     - Selecting the hyperlink opens in browser out-of-app to the following page: https://iris.custhelp.va.gov/app/ask

### Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636882

### Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guideline
- Back button in top left
     - accessibilityLabel = "back"
     - accessibilityHint= “Go back to letter list”
     - accessibilityRole= “button”
- Mark "Letters" as Header 1 
- Mark "Benefit Summary and Service Verification Letter" as Header 2
- Mark "Please choose what information you want to include in your letter" as Header 2

**Military Service Information** 
- Mark “military service information" as Header 3
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list
- For each item:
     - accessibilityLabel= field title (e.g. Discharge type)
     - accessibilityValue= contents of field
- Military service information toggle
     - accessibilityLabel= "include military service information"
     - accessibilityHint= "select whether to include military service information"
     - accessibilityRole= "switch"
     - accessibilityState= Denote when selected or not selected (on vs. off)

**VA Benefit and Disability Information** 
- Mark “VA benefit and disability information" as Header 3
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list
- For each item:
     - accessibilityLabel= field name (e.g. You have one or more service-connected disabilities)
     - accessibilityHint= "select whether to include ___ in your letter" (e.g. You have one or more service-connected disabilities)
     - accessibilityRole= "switch"
     - accessibilityState= Denote when selected or not selected (on vs. off)

**Send A Message**
- Icon
     - Title= “Send Icon”
     - accessibilityRole= “image”
- Link
     - Title= “Send a message”
     - accessibilityHint= “Takes you to the Inquiry Routing & Information System (IRIS) page” 
     - accessibilityRole= “link”

**Button**
- Title= “View Letter”
- accessibilityHint= “View your letter so you can save it to your mobile device."
- accessibilityRole= “button”

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
Questions: 

1. Alert text at the bottom of the screen: "If your service period or disability information is incorrect..." where should this go? 
2. Do we anticipate other letters becoming customizable in the future?

**Comment by bridgethapner** [comment]
@bessgreen Great question - I started this work then have not been able to successfully access the Letters screens in staging since getting halfway through due to API failing to load ... I made #14000 to complete this UX work. Can this be something that I follow up with later? (Will try to get to it soon).

**Comment by bessgreen** [comment]
@bridgethapner Definitely! We can revisit down the line.

**Comment by bessgreen** [comment]
@bridgethapner what does the **Send a message** hyperlink do on this screen?

**Comment by bessgreen** [comment]
@msmanak here is a ticket with an example of a11y requirements

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/20**
UI and functionality pass (need to verify bug fixes on iOS when new build is available). Accessibility fails with a [multi-issue bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16510) entered. Keeping in QA for iOS verification
