### ISSUE TITLE
View list of letters

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13941]
### User story

As a user, I want to view a list of the letters available to me, so that I can decide which letter or document fits my need. 

### Acceptance Criteria
1. Selecting the "View letters" button from the Letters landing page routes to a new page (also called Letters)
2. Styling and UI matches the design
3. The list of letters encompasses the letters available to the user from the letters endpoint. Of the 8 possible letters, a user may not have each one available to them. List of 8 possible letters for MVP: 
     - Commissary Letter
     - Service Verification Letter
     - Civil Service Preference Letter
     - Benefit Verification Letter
     - Proof of Service Letter
     - Proof of Creditable Prescription Drug Coverage Letter
     - Proof of Minimum Essential Coverage Letter
     - Benefit Summary and Service Verification Letter
4. If the letter title is long, the text should go to the next row (as seen in design)
5. Tapping/ selecting any of these letters routes to the letter-specific overview page (only the routing is needed for this story - no detailed UI for these pages)

### Designs
[https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636879](url)

### Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guideline
- Back button in top left
     - accessibilityLabel = "back"
     - accessibilityHint= “Go back to the letters landing page”
     - accessibilityRole = “button”
- Mark “Letters” as Header 1

**Letters List**
- accessibilityRole= "menu"
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list
- For each letter:
     - accessibilityLabel= field name
     - accessibilityHint= "Go to an overview of your ____ " (e.g. Service Verification Letter)
     - accessibilityRole= "menuitem"

**Comment by bessgreen** [comment]
Questions / Notes:

1. Up to how many letters can a user have access to? Should we paginate this or allow the user to scroll through a list? 
2. Depending on the # of letters in the list, scrolling could get messy from a user interaction standpoint if the touch target for the letter is the whole bar.

**Comment by bessgreen** [comment]
@bridgethapner other than **Service Verification Letter** and **Benefit Summary and Service Verification Letter**, what are the other types of letters that a user can have? I saw a list referenced in one of the backend [tasks](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13461), but how will these appear in the UI?

**Comment by bessgreen** [comment]
@bridgethapner assuming a user has access to all of the letter types, what determines the order in which these are listed? (alphabetically, by some pre-designated order, etc.)

**Comment by digitalken** [comment]
Testing:

1. Verify selecting the "View letters" button from the Letters landing page will route user to a new page that is also called Letters.
2. Verify styling and UI matches the design.
3. Verify user has up to 8 letters available to them:
  a. Commissary Letter
  b. Service Verification Letter
  c. Civil Service Preference Letter
  d. Benefit Verification Letter
  e. Proof of Service Letter
  f. Proof of Creditable Prescription Drug Coverage Letter
  g. Proof of Minimum Essential Coverage Letter
  h. Benefit Summary and Service Verification Letter
4. Verify title text wraps to the next row if it is long.
5. Verify that tapping or selecting any of these letters routes to the letter-specific overview page (only routing for this story.)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Tested on TestRail.  Functionality and UI are passing but accessibility is a fail.  Only able to test on Android due to availability of iOS build.  Will retest with iOS when it is available. Moving story to Design QA.

Accessibility bug logged:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16252

**Comment by esther-k** [comment]
**11/23**

Retested on iOS. Functionality and UI pass. Accessibility fails (see comment above for link). Moving to Design QA
