### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va.gov-team#13950]
### User story
As a Veteran, I want a single page that outlines the most important functions/ navigation paths that I can take within the app, so that I can easily execute tasks.

### Acceptance Criteria

1. Styling and UI matches the design
2. UI for Veterans Crisis Line banner (routing is a separate story)
     - The banner should be sticky and remain anchored to the top of the page.
3. The "Claims and Appeals" and "Appointments" buttons follow a different style (according to design specifications) and include short descriptions.
     - Tapping on "Claims and Appeals" takes the user to the Claims landing page
     - Tapping on "Appointments" takes the user to the Appointments landing page.
4. UI for 4 additional pages (UI only. Routing is handled in separate stories)
     - Find a VA Location
     - Coronavirus FAQs
     - Contact VA
     - Covid-19 screening tool 

### Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636866

### Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.

### Accessibility Implementation Guidelines 

- Home is heading level 1 and should be programmatically announced as such 
- Introductory page - Include “Summary” which describes general page layout and options.
- Talk to the veterans Crisis Line now CTA
     - Title = “Talk to the Veterans Crisis Line now”
     - accessibilityRole = “button”
     - AccessibilityHint = “Go to Veterans Crisis Line”
- For list of nav options, Role= “menu”
- Claims and appeals Check your claim or appeal status
     - accessibilityRole = “menuitem”
     - accessibilityHint=”go to claims and appeals”
- Appointments View your medical appointments
     - accessibilityRole = “menuitem”
     - accessibilityHint = “go to appointments” 
- Find a VA Location
     - accessibilityRole = “menuitem”
     - accessibilityHint= “go to VA Facility Locator”
- Coronavirus FAQs 
     - accessibilityRole = “Menuitem”
     - accessibilityHint= “go to Coronavirus FAQs” 
- Contact VA 
     - accessibilityRole = “menuitem”
     - accessibilityHint= “go to VA Contact Information page”

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by b-rocha** [comment]
-Should the "Veterans Crisis Lie" banner be sticky? It doesn't matter on this view but in the event that a user significantly increases text size and the page starts to scroll, should this stay at the top?
- Confirm: Is the "Facility Locator" page going to be a page on the app or will this go to the mobile web view? It sounds like it will live on a web page, but our team discussion on 9/22 seemed to leave this open ended. 
- Contact VA page/ screen? (I believe this was in the old design/ prototype link, will this still be the same?)

**Comment by bridgethapner** [comment]
@b-rocha

- Yes, the banner should be sticky. 
- Facility Locator will be [a web view](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432493111). 
- [This is what I have now for Contact VA](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432493860) - some short text and a phone number. Might change a little, but will be something like this.

**Comment by b-rocha** [comment]
@bridgethapner Thanks!

**Comment by digitalken** [comment]
Linked issue(s):
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14722

**Comment by digitalken** [comment]
Testing:

1. Verify styling and UI matches design.
2. Verify that the Veterans Crisis Line banner is sticky and remains toward top of page.
3. Verify "Claims and Appeals" and "Appointments" pages match design and include short descriptions.
4. Confirm tapping on "Claims and Appeals" button takes user to the Claims landing page.
5. Confirm tapping on "Appointments" button takes user to the Appointments landing page.
6. Confirm the following buttons appear below the Claims and Appeals and Appointments buttons and that they match design:
  a. Find a VA Location
  b. Contact VA
  c. Coronavirus FAQs
  d. COVID-19 screening tool

Accessibiltiy testing:

1. Verify that everything on page is read by screen reader.
2. Verify that anything non-text (buttons, menu items, list tables, images, headings, forms, etc) is bing read by the screenreader to includ: Name (title), role, value.
3. Verify that all touch points are at least 44px by 44px.
4. Verify app supports tap operability (no gestures required) or voice control only.
5. Verify that where gestures occur, like scrolling, that these are operable through the OS' built-in capbilities.

**Comment by digitalken** [comment]
Moving to Design QA.
