### ISSUE TITLE
Settings landing page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13957]
### User story

As a user, I want to adjust my app settings to suit my needs and preferences. 

### Acceptance Criteria

1. Selecting the Settings button from the Profile page routes to a new page called "Settings"
2. Styling and UI matches the design
3. The top/ main section of the page includes a list of possible options for user input including, "Manage your account", "Touch ID" (see AC #5), "Share the app" and "Privacy policy"
     - No routing needed for any of these pages (addressed in separate stories)
5. If the device supports biometrics, display UX/UI for a biometric toggle. This toggle has a dynamic label that is driven by the device's capabilities:
     - "TouchID" for certain iOS devices
     - "FaceID" for certain iOS devices
     - "Use fingerprint" for certain Android devices
     - "Use face recognition" for certain Android devices
6. UI to "Sign out"

### Designs
[https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636883](url)

### Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 
- Back button in top left
     - accessibilityLabel= “back”
     - accessibilityHint= "Go back to profile"
     - accessibilityRole= “button”
- Mark "Settings" as Header 1

**Settings**
- accessibilityLabel= "settings"
- accessibilityRole= "menu"
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list
- For manage your account, share the app, and privacy policy:
     - accessibilityLabel= field title (e.g. manage your account)
     - accessibilityHint= “Go to manage your account" **OR** "Opens your device's share sheet with a link to download the app" **OR** "Takes you to the privacy policy page"
     - accessibilityRole= "menu item"
- Touch ID
     - accessibilityLabel= field title (e.g. touch id)
     - accessibilityHint= “select whether to use___ to log in to the app” (e.g. touch id)
     - accessibilityRole= “switch”
     - accessibilityState= Denote when selected vs. unselected (on vs. off)

**Sign Out**
- Title= "sign out" 
- accessibilityHint= “sign out of the app"
- accessibilityRole= "button"

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Linked issue (for future verification):
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14946

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Minor bugs logged for UI and accessibility, otherwise passes.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18085
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18089

Sending to Design QA.
