### ISSUE TITLE
Manage your account page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13958]
### User story
As a user, I want the ability to manage my mobile app account settings so it is configured to my preferences.

### Acceptance Criteria:

1. Selecting the "Manage your account" button from the Settings page routes to a new page
2. Styling and UI matches the design

### Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432001518/preview

### Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 
- Back button in top left
     - accessibilityLabel= “back”
     - accessibilityHint= "Go back to settings"
     - accessibilityRole= “button”
- Programmatically set page title as "Manage your account page" and mark as Header 1
- Mark "manage your account" as Header 2

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions: 

1. What does this page look like? Is this the right one? https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432001518

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
