### ISSUE TITLE
Access for Adrian Rollett

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#13956]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Adrian Rollett
- Please Provide your email.
   > adrian.rollett@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS-CMS team, Drupal developer, Agile Six Applications Inc.

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzVssswrFlF+g4X1i3kLsxF5ssEsCAh6UGI1qfxyqe9UHGZBAczWucNlK7wzI900cqmrHNz1h4w2kPh6pgSqG3jOPRB//+EH2aBrrQShUnh67/YYyHFpP4GHHB+NqairL475QxXDMs+6s+sesPYNr+gtd3akkFqhLPzlB53Xhy2RyXtNCzJnfdBOb4IAFq1MMD89omcEMOH3644szZFygNlylyZHfeD5iweX6WdIteHgbLn5L7u50lWDaXwP/JQ4oE/N8fMfvaD2LmAMfsZ2lEaHVqSz3rqXH3EHa9PoAj+xNnDuIwRWI5H5ZtvDf1zk72bnA04WgHLVn+1SzmSf9ZVAYxOWk1YlCTnFGzWmN4Nu5YRXJQdJupG1ItDSD34RL3uU4dqdRBV+27uEi6lj7BJlwViwCi8MR1s3e8lulJ9ffotaMJy+aJSX6Gg2guLsnjxRYzUUF+7qffMXbaB76inMPOjaeQJb1mu3V+z25d2m5Ty/aZOHM2RUIWMi2/uMs= Adrian.Rollett@Agile6-A45.local
```

- Grant AWS Console access?
  > NO

**Comment by acrollet** [comment]
@department-of-veterans-affairs/vsp-operations thanks for your help!

**Comment by tskinn** [comment]
@acrollet you should be able to access the socks proxy now. Reach out in slack if you have any issues.
