### ISSUE TITLE
Save letter to files

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13951]
### User story

As a user, I want to download my letter to my device's storage so that I can have a copy of my letter.

### Acceptance Criteria
1. Tapping on the top right download button should allow a user to download the .pdf to their mobile device's files
    - Selecting this button triggers the native action sheet with the option to "Save to files" or "Cancel"

### Designs
[https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636881](url)

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions: 

1. How do we want to handle failures? Do we need a ticketing experience? If service is too busy how do we message?

**Comment by bessgreen** [comment]
@bridgethapner I updated the AC here based on what we talked about for MVP. Are you able to review that this is the intended behavior? (Specifically that this button will trigger the native action sheet, with the 2 options of "Save to files" and "Cancel").

**Comment by bridgethapner** [comment]
@bessgreen Yes, this is right. The button triggering the native action sheet with the 2 options sounds good for MVP. 

Do we need to add accessibility AC here about voice over of the PDF letter or write voice-over descriptions at this point?

**Comment by bessgreen** [comment]
@bridgethapner we've added that type of accessibility AC to the [Download & view letter](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14707) story. Would be great to get your eyes on this one too just to make sure we're checking the boxes! :)
