### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13967]
### User story
As a user, I want to view the app's privacy policy. 

### Acceptance Criteria:

1. Selecting the "Privacy policy" button from the Settings page opens the following page, out-of-app in browser: https://staging.va.gov/privacy-policy/

### Designs
N/A

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Ticket to update URL to the non-staging site: https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17263

**Comment by esther-k** [comment]
**12/09**

UI and functionality pass on iOS and Android. URL will be updated in a [separate ticket](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17263). Moving to Design QA
