### ISSUE TITLE
EDU Benefits Impact List

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13960]
## Background
We need to better understand what education benefits get updated when there is a specific and separate direct deposit path for the Veteran.  Knowing this will better inform us as to what messaging to take and if other stakeholders need to be notified.

## Considerations
- We may need to talk to stakeholders or check in with Steve/ Samara to see who might be a good person to research this with.

## Tasks
- [x] List the education benefits that get updated when direct deposit for edu is in place.

## Acceptance Criteria
- [x] A list of education benefits has been drafted and saved as a markdown file in GitHub (in eBenefits initially, we can transfer/ link to it later)

**Comment by sporeboy** [comment]
Tables with Comp & Pen and EDU benefits and payees added to the discovery doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/edu-dd-discovery.md#payment-compensation-use-cases
