### ISSUE TITLE
1995: Update 1995 content to match DEPO styles

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#13965]
As a developer, I need to update the 1995 so that it is up to date with the current DEPO patterns and practices.

## Assumptions:
1. Introduction page changes are completed behind the feature flag `form_1995_edu_updates ` #14064.
2. Form chapter changes are completed behind a prod flag.

## Acceptance Criteria
1. The "Sign in to start your application" button text is replaced with "Sign in or create an account"
2. The introduction page "Prepare" section content is:

    > #### Prepare ###
    > 
    > To fill out this application, you’ll need your:
    > * Social Security number (required)
    > * Basic information about the school or training facility you want to attend (required)
    > * Bank account direct deposit information (if adding or changing an account)
    > * Military history
    > * Education history
    > 
    > What if I need help filling out my application? An accredited individual, like a Veterans Service Officer (VSO), or a     Veteran representative at your school, can help you fill out your claim. [Get help filing your claim](/disability/get-help-filing-claim/)
    > 
    > #### Learn about educational programs ### 
    > See what benefits you’ll get at the school you want to attend. [Use the GI Bill Comparison Tool](gi-bill-comparison-tool/)

3. The introduction page "Decision" section content is:

    > #### Decision ### 
    > If we approve your application, you’ll get a Certificate of Eligibility (COE), or award letter, in the mail. Bring this COE to the VA certifying official at your school. This person is usually in the Registrar or Financial Aid office at the school.  
    > 
    > If your application isn’t approved, you’ll get a denial letter in the mail.  

4. In Chapter 1, page1, the following label text is updated:
    a. "First name" is replaced with "Your first name"
    b. "Middle name" is replaced with "Your middle name"
    c. "Last name" is replaced with "Your last name"

5. In Chapter 2, page 1, the "Which benefit are you currently using or have you used most recently?" question text is replaced with "Which benefit are you currently using?"

6. In Chapter 4, page 1, the "Name of school, university, or training facility" question text is replaced with "Name of school, university, program, or training facility"

7. In Chapter 4, page 2, the "Name of school, university, or training facility" question text is replaced with "Name of school, university, program, or training facility"

8. In Chapter 5, page 1, the "How would you like to be contacted if we have questions about your application?" question text is replaced with “How should we contact you if we have questions about your application?”.
    a. The "Phone" answer text is replaced with "Home phone number"
    b. "Mobile phone number" is an available answer option

9. In Chapter 5, page 1, the “Primary telephone number” question label is replaced with “Home phone number”
    a. If the user selected "Home phone number" as preferred contact method, the question is marked required.

10. In Chapter 5, page 1, the “Secondary telephone number” is replaced with “Mobile phone number”
    a. If the user selected "Mobile phone number" as preferred contact method, the question is marked required.

11. In Chapter 5, page 2 (answered yes to service before 1978), the "Do you have any children who fall into these categories?" question label is replaced with "Do you have any children who are:"
    a. The answer value "Under age 18" is replaced with "Under age 18, **or**"
    b. The answer value "Between the ages of 18 and 22, not married, and attending school" is replaced with "Between the ages of 18 and 22, not married, and attending school, **or**"
    c. The answer value "Any age who are permanently disabled for mental or physical reasons" is replaced with "Permanently physically or mentally disabled"

12. In Chapter 5, page 3, the "Account number" question text is replaced with "Bank account number"

13. In Chapter 5, page 3, the "Routing number" question text is replaced with "Bank routing number"

14. In Chapter 5, page 3, if the user selects "Stop direct deposit" the following content is displayed:

    > The Department of the Treasury requires all federal benefit payments be made by electronic funds transfer (EFT), also called direct deposit.
    > 
    > If you don’t have a bank account, or don’t wish to provide your bank account information, you must receive your payment through Direct Express Debit MasterCard. To request a Direct Express Debit MasterCard:
    > 
    > - Apply at [www.usdirectexpress.com](www.usdirectexpress.com) **or**
    > - Call [800-333-1795](800-333-1795)
    > 
    > If you choose not to enroll, you’ll need to call the Department of the Treasury at [888-224-2950](888-224-2950) and speak to a representative handling waiver requests. They’ll encourage you to participate in EFT and address any questions or concerns you have.

15. The page matches the layout and structure as specified in Supporting Artifact # 1.

## Supporting Artifacts: 
1. [Mobile Prototype v3](https://bahdigital.invisionapp.com/share/VUIAEXFPHBC#/screens) as of 09/23
2. [Content Doc v3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ad9acc27708637115a20e2bb502026faf1112604/products/education-careers/application/1995/content/1995-content-doc-v3.0.md) as of 09/23

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14463
https://github.com/department-of-veterans-affairs/vets-website/pull/14470

https://github.com/department-of-veterans-affairs/vets-website/pull/14447

**Comment by delli-gatti-michael** [comment]
Tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/998

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by delli-gatti-michael** [comment]
I heard you like screenshots

![Screen Shot 2020-10-08 at 1.25.54 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f11a43d6-caa2-4c61-be09-83d64ca9d7aa)

---

![Screen Shot 2020-10-08 at 1.26.18 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/bab7f631-2b60-4c0e-bf83-826446dc2f88)

---

![Screen Shot 2020-10-08 at 1.26.24 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e521c7a5-b90d-483a-99c2-9e922b1565c0)

---

![Screen Shot 2020-10-08 at 1.26.36 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/061d2418-4854-4b35-b644-aa2f970415a4)

---

![Screen Shot 2020-10-08 at 1.26.56 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/8b1f0c09-1f6e-4e0d-b3ae-3abb6ebb4d72)

---

![Screen Shot 2020-10-08 at 1.31.26 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/8c0b0c1e-6591-48bf-84dd-cfb6254ac416)

---

![Screen Shot 2020-10-08 at 1.27.06 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/04390a57-f2cc-4265-aedd-33b76e973d5f)

---

![Screen Shot 2020-10-08 at 1.27.24 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/060e51c1-84d4-465c-91e1-2cf5505a7972)

---

![Screen Shot 2020-10-08 at 1.27.34 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/bc919249-3b51-4d4b-a512-134dfb9fc76f)

---

![Screen Shot 2020-10-08 at 1.27.40 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a9782642-d251-42c9-a004-fd903aa6ee21)

---

![Screen Shot 2020-10-08 at 1.27.46 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/9b1bd4a0-be6d-4793-a8ec-2525603553d9)

**Comment by ccruzgra** [comment]
@delli-gatti-michael UXers found two content items that need adjustments, and @dneel-bah will follow up with a story to make those tweaks. Otherwise, this work checks out!

**Comment by delli-gatti-michael** [comment]
closing this out
