### ISSUE TITLE
Share app

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#13966]
## User Story
As a user, I want the ability to share the app with others so they can open it on their native app store to download. 

## Acceptance Criteria:

1. Selecting Share app opens the device's share sheet
     - User can choose where they want to send the message
2. Message contains text with two links to the App Store & Google Play store (use placeholders until links are provided):
      - Text: "Download the VA mobile app on the App Store: [link to App store] or on Google Play: [link to Google Play]"

## Accessibility Acceptance Criteria
NOTE: Accessibility should be handled by the device. In case it's not:

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Dev Checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions/considerations: 
-What will app be called in the app store?

**Comment by bessgreen** [comment]
Share sheet example: 
![image (8).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b28732b0-8608-4f2a-a99d-d0f9dd956973)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Follow up ticket to add in the app store links: https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17136

**Comment by digitalken** [comment]
Testing...
