### ISSUE TITLE
Topline Summary of CH36/31 Usability Test Findings

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13969]
### Story
As a Veteran, I need a simple, clear way to determine if I'm eligible under CH36/CH31, so I can apply for benefits. **And...** As a Veteran, I need a simple, easy form, so I can apply for CH36/CH31 benefits.

Usability testing of the CH36 and CH31 wizards and form was conducted between 9/24 and 10/1. There were seven sessions. 

### Goals
Create a high-level summary of usability testing findings so that:

- Everyone who observed the study is in alignment with the perceived findings
- Insight is captured from team/stakeholder/designers to determine specific directions to pursue as we analyze the data

### Considerations
- [CH36/CH31 Usability Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-research-plan.md)
- [CH36/CH31 Usability Convo Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-convo-guide.md)

### Tasks
- [ ] Create MD document that details initial high-level findings from usability testing

### Acceptance criteria
- [ ] Topline summary available in GH

**Comment by sporeboy** [comment]
Topline summary complete here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/usability-testing/ch36-ch31-usability-topline-summary.md
