### ISSUE TITLE
Determine what font/icon licensing info needs to be in the app

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#13961]
## User Story
As a VA mobile app team member, I know what font and icon licensing information needs to be included in the MVP app.

- [ ] Determine what font and icon licensing information needs to be included in the MVP mobile app.
- [ ] Determine where we will display this information (likely in Settings) and design the screens.

**Comment by ayushchak** [comment]
Need Steve's opinion on this - where do we put this? Any access to legal resources to help us with this?

**Comment by bridgethapner** [comment]
Just following up on this to share the context I have - here is a screenshot of the guidance from Font Awesome (below). I think we could put the license information in 'Settings' as the last item. Or we could get a paid plan and avoid this altogether. 
![Screen Shot 2021-02-08 at 4.39.05 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/048439ea-1052-4bb3-8c07-d16f9cb207c6)

I read the Open Type Font License to see if we need to credit our fonts, but I don't think we do? Here's the link to the license if someone else wants to take a look: https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL
