### ISSUE TITLE
Appointments Overview Nav

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va.gov-team#13962]
## User story
As a user, I want to quickly navigate through my list of upcoming and past appointments. 

Note: This story is only for the navigation capability for the appointments list. Upcoming and past appointments can be found in separate stories.

## Acceptance Criteria
1. Appointments landing page has two views: Upcoming or Past
     - No back button on either of these options
2. "Upcoming" and "Past" are two different segmented controls/ tabs at the top that each display a unique list of appointments. 
     - Pull in the common component: Segmented Selector
2.  A user can tap "Upcoming" or "Past" to navigate to that list of appointments 

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432442341 

## Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by b-rocha** [comment]
Note: The current design uses segmented controls which are unique to iOS. We'll need a separate design/ story for Android.

**Comment by digitalken** [comment]
Added test cases for acceptance and accessibility on TestRails.

**Comment by esther-k** [comment]
**11/19**

UI and functionality pass. Accessibility does not pass with a [multi-issue bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16459) entered. Moving this to Design QA for review.
