### ISSUE TITLE
DebtRes SME Interviews 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13976]

**Comment by rileyorr** [comment]
I've uploaded [the transcript from today's workshop](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/oct-2020/09292020-sme-workshop.md) to GH :)

**Comment by rebeccawalsh** [comment]
Github repo for this work can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Financial-Status-Report/research/oct-2020
