### ISSUE TITLE
DebtRes Conversation Guide 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#13975]
## Issue Description
_Once concluding preliminary research on the FSR (VA form 5655), the design team needs to write conversation guide(s) for the SME interviews._

---
## Tasks
- [x] _Write at least one conversation guide to be used for DMC SME interviews. Additional conversation guides may be needed depending on interviewees' roles_

## Acceptance Criteria
- [x] _Conversation guide(s) is uploaded to GH and linked in this ticket_

**Comment by rileyorr** [comment]
Added [the SME conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/oct-2020/SME-conversation-guide.md) to GH. We may make adjustments after our first workshop :)

**Comment by rebeccawalsh** [comment]
SME Conversation guide can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/oct-2020/SME-conversation-guide.md)
