### ISSUE TITLE
[Design] - update documentation for learning center About template responsive tables

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#13972]
Per[ feedback from the design intent review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13825#issuecomment-697014817), create documentation for:
- document at what viewport width we plan to collapse columns 2–12, so that we have all the info and are in agreement.
- document focus management for when the collapsed row is expanded/collapsed. It is expected it would behave the way the additionalinfo component does (where focus remains on the button that expands/collapses).

**acceptance criteria**

- [ ] documentation created and shared with PW FE developers

**Comment by andaleliz** [comment]
@kelsonic @ncksllvn FYI this will be coming at you. If you get the green light to start building before I provide this, lmk and I'll prioritize this

**Comment by andaleliz** [comment]
@jenstrickland, I've looked into the [breakpoints defined for VA.gov](https://design.va.gov/design/breakpoints), and guidance around exceptions to that.  Since we're designing for templates, we don't know what the tables will contain or how many columns a table might have.

To keep things simple, I'm inclined to design for the "worst case scenario" and imagine a table with 12 columns that has everything (bulleted lists, paragraphs, numbers, etc), and recommend the collapsed state kicks in at our medium breakpoint (768px per guidance, 767 per production).

For some smaller tables, that would be overkill, but I don't think I want to go down the path of recommending logic for different column numbers collapsing down at different breakpoints (e.g. if it has 1-3 columns, collapse cols 2-3 at 481px, if it has 1-5, collapse cols 2-5 at 600px, if it has 1-12 cols, collapse at 768px, etc).

Interested to hear your thoughts on this, as I'm kind of at a loss beyond my "worse case scenario" approach. You mentioned 600px in Slack and I'm curious how you arrived at that number.

cc @mpeterz since you +1 this feedback from Jennifer

**Comment by jenstrickland** [comment]
@andaleliz 👏  I agree with your thinking. We need an MVP not an acrobatic workhorse.

**Comment by andaleliz** [comment]
Updated documentation in mock-ups, and added guidance via comment to #13963
