### ISSUE TITLE
Clarify load testing documentation

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1398]
As a new user to the system, I want the load testing documentation to be up to date so that I can easily follow the steps to get it working. 

https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest

AC:
- [x] Documentation is updated based on Peter's findings last sprint
- [x] Changes have been reviewed by devops before merged to master

**Comment by peterhill-oddball** [comment]
@tlei123 Please have a look at the load tests that require authenticated sessions.  One example is the appealsv2 test.
