### ISSUE TITLE
Update design files to show other sandwich layers: learning center

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13989]
## Update design files to show other sandwich layers: learning center

As a PW team member, I want to be able to visualize the latest design iterations for article templates. 

1/ Please update the following 1.0 LC pages with the latest iterations on the sandwich layers: 

- [x] Step-by-step
- [x] Multiple FAQs
- [x] Question and answer
- [x] About

**Sandwich layers:** 

- Need more help - contact info component
- How do you rate your experience on this page? component (PRA change from "Was this page helpful?") - Answer ux pending Joanne confirmation ([Slack thread](https://dsva.slack.com/archives/C1Q4294JJ/p1600892236000600?thread_ts=1600106082.033700&cid=C1Q4294JJ))
- Related information component
- VA benefits component
- Back to top UX

**2/ Remove content type labels for these pages:**
_**We will not display content type labels in 1.0. We will show them in 1.1.**_

- [x] Search results listing 
- [x] Static list page for 'all articles in Xcategory'
- [x] Static list page for 'all articles tagged: Y'

**3/ Please add updated design files to:**

- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)
- Repo wip design folder https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/updated-sept-16

**Comment by rtwell** [comment]
# Step by step

![image](https://user-images.githubusercontent.com/12564977/94302123-b601a000-ff39-11ea-8c5a-79e83cbbf818.png)

# FAQ

![image](https://user-images.githubusercontent.com/12564977/94302007-86529800-ff39-11ea-9968-4e19c0cfb13b.png)

# Q+A

![image](https://user-images.githubusercontent.com/12564977/94302139-bdc14480-ff39-11ea-84d9-b998cc02b058.png)

# About

![image](https://user-images.githubusercontent.com/12564977/94302154-c3b72580-ff39-11ea-83d5-d461cce7c28e.png)

**Comment by rtwell** [comment]
# Search results listing

![image](https://user-images.githubusercontent.com/12564977/94302473-4213c780-ff3a-11ea-8c1e-c611933dffe7.png)

# Static list page for 'all articles in Xcategory'

![image](https://user-images.githubusercontent.com/12564977/94302505-4d66f300-ff3a-11ea-9206-a13f61c5a5af.png)

# Static list page for 'all articles tagged: Y'

![image](https://user-images.githubusercontent.com/12564977/94302513-51931080-ff3a-11ea-9de0-6c2fe641a970.png)

**Comment by jenniferlee-dsva** [comment]
The only thing missing here is the back to top design @rtwell . I know you've shown one of the designs previously. Would you mind adding it to the Mrual and linking it here? TYVM!

**Comment by rtwell** [comment]
Added to the mural.

[Desktop](https://murally.blob.core.windows.net/uploads/departmentofveteransaffairs9999/1602688965794.png?se=2020-10-14T16%3A00%3A00Z&sp=r&sv=2018-03-28&sr=b&rscc=public%2C%20max-age%3D600&sig=UXcTBj3j7jE7PNVq17CiKYsO9cM2XL30YV7auhOqvGo%3D)

[Mobile](https://murally.blob.core.windows.net/uploads/departmentofveteransaffairs9999/1602688981453.png?se=2020-10-14T16%3A00%3A00Z&sp=r&sv=2018-03-28&sr=b&rscc=public%2C%20max-age%3D600&sig=elmP87%2BPpgdWNry0xftarJjGkRhWxTsJID7vmju3uuc%3D)

**Comment by jenniferlee-dsva** [comment]
I'm getting a strange error message. Is it just my gfe / VA network? 

![image](https://user-images.githubusercontent.com/43381063/96175687-3b54f080-0ef9-11eb-972b-009e3a322b32.png)

**Comment by jenniferlee-dsva** [comment]
Updated mockups are now on Mural, so we can close this ticket. 

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b
