### ISSUE TITLE
Error state directing user to call center

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13991]
## User Story

As a user, I am not able to access a service because I don't have the requisite ID and therefore need to be directed to the call center.

**Comment by patrickvinograd** [comment]
I think there's two sub-cases here:

1) I don't have the requisite ID but that's correct because I'm not enrolled in whatever program would have issued that ID. I.e. I've never enrolled in VA healthcare, or never claimed any VBA benefit, so I don't have the relevant identifier. This is to be expected.

2) I don't have the requisite ID in MPI (the central index for such things) and it's a mistake/data error that needs resolving. 

Just want to avoid over-routing people to the call center.

**Comment by bridgethapner** [comment]
Thanks @patrickvinograd! 

It sounds like for scenario 1 screens like [this](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432581200) and [this](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432463354) will suffice, and scenario 2 is what we need a design for. 

@srmyers17 + Patrick, Do we know where this might present in the app? If a user doesn't have a requisite ID in MPI, will that blanket affect their experience with all app features, or could such a scenario only affect Appointments, for example?

**Comment by srmyers17** [comment]
I think it will impact Claims but not Appointments or Appeals but we should confirm with @kreek

**Comment by kreek** [comment]
appointments only check is that the user is LOA3, appeals is LOA3 and SSN, claims requires EVSS policy which is EDIPI, SSN, and Participant ID (also referred to as Corp ID)

**Comment by srmyers17** [comment]
- Appointments doesn't need an error state
- Appeals and Claims needs an error state if user doesn't have SSN
- Claims needs an error state if user doesn't have EDIPI, Participant ID

**Comment by srmyers17** [comment]
What stakeholder should review error states / may have input? 
Perhaps content team.

**Comment by srmyers17** [comment]
Since the same error states apply across Profile, Address and Military Information, I think we can create generic error messages for each type:

![Screen Shot 2020-10-08 at 1.22.46 PM.png](https://images.zenhubusercontent.com/5de7efc226120baf54e97f2e/287765b0-b5b6-40c8-9297-91fd0d398075)

Next step is to meet with Alastair/Jayson to understand the errors a bit more and determine language for each type.

**Comment by bridgethapner** [comment]
Blocked for now by more general error state conversation. Once we touch base across backend and UX to understand the error states we'll get from the API we can write content for this error state.

**Comment by bridgethapner** [comment]
It seems like we still need a state to cover the second scenario Patrick mentioned above (I don't have the requisite ID in MPI (the central index for such things) and it's a mistake/data error that needs resolving) just for Claims. It seems like this error from the Error Message style guide will work:

### We don’t seem to have your records
We’re sorry. We can’t find your records in our system. If you think they should be here, please try again later or call the VA.gov help desk at 844-698-2311 (TTY: 711). We’re here Monday–Friday, 8:00 a.m.–8:00 p.m. ET.

![Missing ID Error State.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/f8766319-b23f-4ddf-92b4-31cda3028b0d)

**Comment by bridgethapner** [comment]
This is a 401 error / authorization error

**Comment by bridgethapner** [comment]
This design work is done, the content may change based on VSP feedback. I will create a new ticket for updating content if we need to.
