### ISSUE TITLE
[FE] Built 'Can't connect to MPI' error alert 

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#13996]
## Background

[Design Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12817#issuecomment-697027527)

We need to build an alert for when we can't connect to MPI. Here is the content for it. 

**We can’t access your Veteran records**
We’re sorry. Something went wrong when we tried to connect to your Veteran records. Please refresh this page to try again.

**Comment by erikphansen** [comment]
@mshea0606 heads up that I brought this ticket into this sprint since I have bandwidth and was just working on something similar to this.

**Comment by mshea0606** [comment]
@erikphansen sounds good, thanks for the heads up!
