### ISSUE TITLE
10/1 Front end QA updates 

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#13993]
**Intro**
- [x] "Download the VA form 10-10CG(PDF)" (Remove `the` and is there anyway to make sure the color doesn't change?)![Screen Shot 2020-09-23 at 4.58.15 PM.png](https://images.zenhubusercontent.com/5ddc08a57dcda00001c763e1/cf160469-2239-4689-80b0-58eb7a42973d)

- [x] Update OMB control number (should be: 2900-0768)
<img width="218" alt="Screen Shot 2020-09-23 at 5 47 23 PM" src="https://user-images.githubusercontent.com/15709424/94073077-d9efa500-fdc4-11ea-8970-01c64b6aa67e.png">

**Primary Family Caregiver** 

- [x] Primary Family Caregiver component (remove the first sentence of the 2nd paragraph) 
- [x] Remove "\u2019s"
![image (2)](https://user-images.githubusercontent.com/15709424/94073035-cba18900-fdc4-11ea-96d0-a810b298131f.png)

**Secondary Family Caregiver**
- [ ] Can we look at the padding after "Additional info" component on the Secondary Caregiver question 
![image (1)](https://user-images.githubusercontent.com/15709424/94073004-bdec0380-fdc4-11ea-9fab-ec363ef3593a.png)

**Review and submit**
- [x] A service member snuck in on the signature page 
![image](https://user-images.githubusercontent.com/15709424/94072962-aad93380-fdc4-11ea-8a3b-f17788f93fac.png)

**Throughout**
- [ ] It might be a form builder thing - But can we look at the padding between the steps, chapter title, intro sentence (seems inconsistent) 

**Late add ons**
- [x] On the subway map, add the word "The" to the beginning of the last bullet. It should read: "The Veteran's Social Security number or ...."
![image (3)](https://user-images.githubusercontent.com/15709424/94160381-8f1c6e80-fe52-11ea-8448-227330ac6b73.png)

- [ ] Scrolling numbers in birth field [See here](https://dsva.slack.com/archives/CMJ2V70UV/p1600953125004200)

**Comment by jonathanjnelson** [comment]
I think the Secondary Caregiver radios look good. I think with more spacing we risk the radios getting lost and floating out there without a label

**Comment by ala-yna** [comment]
@LinnJS - Added two more under "Late add ons" in the issue description.

**Comment by LinnJS** [comment]
@ala-yna we cant just change behavior of global components need to talk to platform about that number input scroll thing.

**Comment by jonathanjnelson** [comment]
@ala-yna Are we sure we want to add "The" - Peggy's suggesting can be seen here:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/13712#issuecomment-696322074
