### ISSUE TITLE
Past Appointments List (UI)

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va.gov-team#13994]
## User story
As a user, I want to see a list of my past appointments so that I can reference my appointment record when needed.

## Acceptance Criteria
1. Selecting "Past" in the segmented selector or swiping right to left navigates to the past list of appointments
2. Styling and UI matches the design
3.  Placeholder for Date range picker (UI / functionality covered in a [separate story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15763))
4. Past Appointments should list any past appointments associated with the user, organized by recency
     - Appointments should be grouped by filter range
     - Canceled appointments should also show in the list (UI covered in a [separate story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15739))
5. Each appointment in the list should include the date in [Day], [Month XX, XXXX] at [00:00] [am/ pm] [Timezone] format
     - The timezone should match the timezone the clinic is in (6 timezones)
6. The location or appointment type (if virtual) should be listed below the day/time
     - For VA Appointments and Community Care appointments, the VA Medical Center name or Community Care facility name should be shown
     - For virtual appointments the specific appointment type should be listed:
          - VA Video Connect at home
          - VA Video Connect at an ATLAS location
          - VA Video Connect at a VA location
          - VA Video Connect using a VA device

Covered in a separate story: Selecting a past appointment takes the user to the details page for that appointment

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432457679

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark "Appointments" as Header 1

**Segmented Selector**
- accessibilityLabel="upcoming"
- accessibilityHint="view your past appointments"
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector

**Date Range Picker**
- accessibilityLabel= contents of field (e.g. Past 3 months)
- accessibilityHint="select a date range"
- accessibilityRole="spinbutton"
- accessibilityState="collapsed"

**List of Past Appointments**
- accessibilityLabel= "past appointments list"
- accessibilityRole= "menu"
- Mark section title (e.g. Past 3 months) as Header 2
- For each field:
     - accessibilityLabel= field title (e.g. Tuesday, September 22, 2020 10:00 a.m. E.T.)
     - accessibilityHint= "view details of this appointment"
     - accessibilityRole= "menuitem"
     - accessibilityValue= contents of field
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by b-rocha** [comment]
Questions: 
- What are the possible time ranges I can filter for? 
- Confirm: Cancelled appointments will not be included in the "Past Appointments" list.

@bridgethapner

**Comment by bridgethapner** [comment]
@b-rocha

 - The way that VA Online Scheduling tool on VA.gov handles Appointment filtering today is filtering in 3-month chunks that are set based on the current date ([documented here](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13463)). Is this filtering easy or high LOE to replicate? If it's easy, I'd like to keep it for consistency across web/app. If it's high LOE let's come up with something simpler -- not a big deal at all to change. Let me know what you think! 

- Canceled appointments **should** be included in the "Past Appointments" list.

**Comment by b-rocha** [comment]
@bridgethapner Thanks for sharing that documentation! Super helpful :) 

- I'll share this with the team and we can discuss during estimation/ sprint planning! Let me know if you'd like us to discuss sooner.
- Gotcha! Glad I asked :) Adding that to the requirements.

**Comment by esther-k** [comment]
@bridgethapner 

- Confirm: If the appointment was virtual, the address field should say "Virtual Session"

**Comment by bridgethapner** [comment]
@esther-k Thank you for raising this Q! I think I wrote this documentation before I knew about the 4 types of virtual sessions. For virtual appointment types, the specific appointment type should be listed below the day/time, so one of these 4:

- VA Video Connect at home
- VA Video Connect at an ATLAS location
- VA Video Connect at a VA location
- VA Video Connect using a VA device

For VA Appointments and Community Care appointments, the VA Medical Center name of Community Care facility name should be shown.

**Comment by esther-k** [comment]
@bridgethapner 

gotcha, thanks for clarifying!

**Comment by esther-k** [comment]
@bridgethapner 

Will the appointment grouping be by date range, month, or year?

**Comment by bridgethapner** [comment]
@esther-k For the past appointment filters? If I'm understanding your question I think the answer is the ranges will be by months for 3 of the filters and by year for two of the filters. Let me know if this isn't what you're looking for.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Test run is set for retest on iOS.  Passes on Android for UI.  Fails on accessibility. Moving to Design QA.
