### ISSUE TITLE
Upcoming Appointment Details: VA Appointment

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va.gov-team#13995]
## User story
As a user, I want to see details for my upcoming, VA appointment and: add the appointment to my calendar, call the clinic, and get directions directly from the app

## Acceptance Criteria
Note: Canceled UI covered with story #15739

1. Selecting a VA Appointment from the Appointments list routes to a new page with more detail about that appointment
     - Display Back button
2. Styling and UI matches the design
3. The date should be in [Day], [Month XX, XXXX] at [00:00][am/ pm] [Timezone] format
     - The timezone should match the timezone the clinic is in (6 timezones)
4. Pull in "Add to calendar" CC [(separate story)](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16046)
     - Calendar app opens with a new event that corresponds to the date/time of the appointment, with the appointment title (VA Appointment) pre-filled as the event name
5. Clinic address is displayed in standard address format:
     - The 1st line displays 'healthcareService' from the API
     - The 2nd line should be the location name
     - The 3rd line should be the street address
     - The 4th line should be the city, state, and zip code
6. Pull in "Get directions" CC [(separate story)](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15609)
     - Navigation app opens to the coordinates of the clinic
7. The clinic's phone number hyperlink with a phone icon displayed to its left
     - Tapping on this should launch the phone's "call" app
     - Call app opens with the clinic's number pre-filled
8. "Visit VA.gov" hyperlink with a right arrow icon displayed to its left
     - Opens the following link out-of-app in the user's browser: https://www.va.gov/health-care/schedule-view-va-appointments/ 
9. The clinic's phone number is a hyperlink with a phone icon displayed to its left
     - This is the same clinic phone number that is displayed on the card above
     - Tapping on this should launch the phone's "call" app
     - Call app opens with the clinic's number pre-filled

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432457680

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Back button in top left
     - accessibilityLabel= “Back”
     - accessibilityHint= “Go back to the upcoming appointments list”
     - accessibilityRole= “button”
- Mark "Appointment" as Header 1
- Mark date/time (e.g. Friday, September 25 2020 11:15 a.m. ET) as Header 2
- Mark the "friendly clinic name" (e.g. CHY PC CASSIDY) as Header 3
- Mark "Need to cancel?" as Header 3

**Links**
- Icons
     - Title= “___Icon” (e.g. Calendar, Street, Phone, Right Arrow )
     - accessibilityRole= “image”
 - Link
     - Title= Name of link (e.g. Add to calendar )
     - accessibilityHint= “Adds this appointment to your device's calendar" **OR** "Opens your device's navigation app" **OR** “Dials this number via your device’s call function”
          - No hint for "visit va.gov" link
     - accessibilityRole= “link” 

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by esther-k** [comment]
@bridgethapner 

Do you have the VAOS link and will the link open in app or out of app?

**Comment by bridgethapner** [comment]
@esther-k hi! 
- The VAOS link is: https://www.va.gov/health-care/schedule-view-va-appointments/
- It should open out of the app

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/30**

UI and functionality pass on Android. Accessibility fails with a [multi-issue bug](zenhub) entered. Keeping in QA until UI and functionality can be tested on iOS.
