### ISSUE TITLE
[Discovery] Run e2e outside of the normal CI testing, on its own schedule (i.e. once a day at xyz)

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#140]
## Description
The development team will need to run the e2e outside of the normal CI schedule which will require devops changes and research around how to trigger these tests to run

## AC
- [ ] Research has been done to determine the devops changes needed to run these tests outside of the CI Schedule
- [ ] Research into how to create a manual trigger
- [ ] Establish a schedule for when the e2e tests will run
- [ ] Research into what it would take to establish a dashboard/portal that enables non-engineers to be able to run these e2e tests

## Def of Done
- [ ] Connected to Epic
- [ ] AC is complete

**Comment by annaswims** [comment]
a lot of this sounds like defining what we'd like a Jenkins job to be fore the Devops team.

**Comment by brandonrapp** [comment]
This work has been rolled into the issue #644 and thus this ticket will be closed.
