### ISSUE TITLE
Complete Alert Text Design on Benefit Summary & Service Verification letter

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14000]
## User Story
This story is to figure out the Alert Text and related actions for the Benefit Summary & Service Verification letter. This is blocked by not being able to access staging.

## Alert text 
"If your service period or disability status information is incorrect, please send us a message through VA's Inquiry Routing & Information System (IRIS). VA will respond within 5 business days."

Link: https://iris.custhelp.va.gov/app/ask

## [Wireframe](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636882)

**Comment by srmyers17** [comment]
To get unblocked 
- have tried logging in on different days, no luck
- next step is to post in VSP support channel
