### ISSUE TITLE
[Development] 526: Decrypt Password Protected PDFs for the Veteran

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#14002]
## Issue Description
Note: Technically this is an issue for all 526, but this was a blocker in 2 of 3 UAT sessions

During a UAT session, a veteran tried to upload a password-protected PDF and saw a response like this one 
![Screen Shot 2019-09-27 at 3 22 44 PM](https://user-images.githubusercontent.com/11036339/65799944-eb16bf00-e13a-11e9-844b-df6234527232.png)

[related sentry error](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/146117/events/)

Apparently, that was expected behavior as created in:
https://github.com/department-of-veterans-affairs/vets-api/pull/3346

I did some research last night and it is possible for us to remove the password protection from the PDF if we are given the password.

The veteran indicated that it was typical to receive password-protected PDF's for DOD medical records.  

This story is to handle the decryption once the FE gives them the password.

## Acceptance Criteria
- [x] Send decrypted PDF down to EVSS
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
We could do something like this to  remove the password from the PDF. 
```ruby
 pdftk = PdfForms.new(Settings.binaries.pdftk)
 tmpf = Tempfile.new(['decrypted', '.pdf'])
 error_messages = pdftk.call_pdftk(file.tempfile.path, 'input_pw', 'test', 'output', tmpf.path)
```

My main concern is - how do we validate that contents of the PDF were uncorrupted by the conversion?  Can we get 5 or so "typical" documents?  Also, how 

I'd imagine that most people don't know how to remove password protection from a PDF and that it's rather difficult to do on a mobile device.

**Comment by luke-gcio** [comment]
This looks like there would be some design elements to add a field to the file upload.  Do we have the source of the file upload component or would we have to override the component from the library with a custom copy?

**Comment by annaswims** [comment]
PR to make the error messages have useful words in a standard format. https://github.com/department-of-veterans-affairs/vets-api/pull/5059. This will affect error responses for uploads for  HCA, Preneeds, 526, CST and VIC.  I _think_ VIC (veteran id card) never launched.  

@luke-gcio could you find out for me which teams are responsible for HCA and Preneeds?
