### ISSUE TITLE
Ensure FE templates show `fieldAlertSingle`

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#14008]
## Summary

This conversation began [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13135#issuecomment-698382195) where it was noticed that alert content does not appear on the newly added FE templates for LC:

http://preview-prod.vfs.va.gov/preview?nodeId=6899 vs. design spec (in image below)

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/bff1dfc7-b4b5-46c7-a893-91a4a8728476)

## Acceptance Criteria

- [ ] Ensure QA, multi QA, step-by-step, images, videos, and checklist all show alert content if provided

**Comment by kelsonic** [comment]
Hey @RLHecht would you mind confirming that http://preview-staging.vfs.va.gov/preview?nodeId=6899 has its `fieldAlertSingle` filled out on Drupal? The code is actually all there to support this in the template so trying to figure out why it's not rendering 🤔

**Comment by kelsonic** [comment]
PR open to add `fieldRelatedLinks` to the `q_a` content type, `step_by_step` should already have it but it's not showing up (maybe it's not added in Drupal for 6899?): https://github.com/department-of-veterans-affairs/vets-website/pull/14370/files#diff-7d210cc49d1c10fd1d197bded641fd7fR32

**Comment by ncksllvn** [comment]
@kelsonic Looks like your PR is merged - can we move this to validate?

Also, on that link you posted, dev tools does show the JSON structure used for the page and yeah that `fieldAlertSingle` is null

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/aa7e36e0-9cb3-43b0-aab3-c5e3bdda6bd0)

**Comment by kelsonic** [comment]
Yupp! Just merged the PR this morning 🙂 Moving to validate!

**Comment by jenniferlee-dsva** [comment]
Hey - maybe the body step by step template FE is captured in another ticket? But on prod.preview, this node 1/ shows the alert that was added (yay!), but 2/ the step by step component has disappeared (rut roh!) 

http://preview-prod.vfs.va.gov/preview?nodeId=6899

![image](https://user-images.githubusercontent.com/43381063/95488619-c404e700-0963-11eb-83f0-97adda5f7738.png)

Perhaps @RLHecht has info - did that content get deleted in the cms?

**Comment by kelsonic** [comment]
Yupp, that will be addressed in the cardinality change ticket for step by step! 🙂
