### ISSUE TITLE
[Development] 526: Provide Field for Password to Password Protected PDFs

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14011]
## Issue Description
During a UAT session, a veteran tried to upload a password-protected PDF and saw a response like this one 
![Screen Shot 2019-09-27 at 3 22 44 PM](https://user-images.githubusercontent.com/11036339/65799944-eb16bf00-e13a-11e9-844b-df6234527232.png)

[related sentry error](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/146117/events/)

Apparently, that was expected behavior as created in:
https://github.com/department-of-veterans-affairs/vets-api/pull/3346

This story is related to #14002 except this is the front end changes required to provide a place for someone to enter a password.

Also, we will need some content updates to appropriately ask for the password.  Something along the lines of "If you are submitting a password protected PDF, please enter it here and we will decrypt it for you upon submission."

## Acceptance Criteria
- [ ] Be able to pass a password down to the backend
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
This is possible! But given the demo code as-is, [it won't work in IE11](https://developer.mozilla.org/en-US/docs/Web/API/FileReader#Browser_compatibility)

Demo: http://plnkr.co/edit/4oFwXZ5K5vF82ZjD

<details><summary>HTML</summary>


```html
<input type="file" id="fileElem" multiple accept="*" style="display:none">
<a href="#" id="fileSelect">Select some files</a> 
<div id="fileList">
  <p>No files selected!</p>
</div>
```
</details>

<details><summary>JS</summary>


```js
window.addEventListener('load', () => {
  const fileElem = document.querySelector('#fileElem');
  const fileList = document.querySelector('#fileList');

  document.querySelector('#fileSelect').addEventListener('click', event => {
      if (fileElem) {
        fileElem.click();
      }
      event.preventDefault();
    },
    false
  );

  fileElem.addEventListener('change', handleFiles, false);

  function handleFiles() {
    if (!this.files.length) {
      fileList.innerHTML = '<p>No files selected!</p>';
    } else {
      fileList.innerHTML = '';
      const list = document.createElement('ul');
      fileList.appendChild(list);
      for (let i = 0; i < this.files.length; i++) {
        const li = document.createElement('li');
        list.appendChild(li);

        const reader = new FileReader();
        reader.onloadend = event => {
          if (event.target.readyState === FileReader.DONE) {
            const isEncrypted = event.target.result.includes('/Encrypt')
              ? 'Encrypted!'
              : 'Not encrypted';
            const info = document.createElement('span');
            info.textContent = `${this.files[i].name}: ${this.files[i].size}bytes - ${isEncrypted}`;
            li.appendChild(info);
          }
        };

        const blob = this.files[i].slice(0, 200);
        reader.readAsBinaryString(blob);
      }
    }
  }
});
```
</details>

Example PDF files:

- [TestPDF-no-password.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5331073/TestPDF-no-password.pdf)
- [TestPDF-edit-password1234.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5331076/TestPDF-edit-password1234.pdf) (password = `password1234` to allow editing only; still viewable without entering a password)
- [TestPDF-password123.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5331074/TestPDF-password123.pdf) (password = `password123`)
- [TestPDF-encrypted-password123.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5331075/TestPDF-encrypted-password123.pdf) (Encrypted using a certificate; password = `password123`)

**Comment by Mottie** [comment]
The Claim status tools does not share the code used by the form system for file uploads. It is completely separate, so I opened a ticket for implementation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14723

**Comment by kevinstachura** [comment]
Design recommendation on this is as follows:

When user attempts to upload evidence that the system detects as a password-protected PDF, this is what they will see:

<img width="768" alt="Screen Shot 2020-10-14 at 9 16 29 AM" src="https://user-images.githubusercontent.com/54544300/96131490-3ecf8400-0ec7-11eb-99f0-1071313ef48f.png">

After entering the password on the screen and clicking 'add password', the system checks to determine if the password unlocks the PDF/is correct. If it is correct, the user will see this:

<img width="760" alt="Screen Shot 2020-10-14 at 9 16 36 AM" src="https://user-images.githubusercontent.com/54544300/96131766-9968e000-0ec7-11eb-94e8-dc9663e81227.png">

If it is incorrect, the user will see this: 

![Screen Shot 2020-10-15 at 8 24 53 AM](https://user-images.githubusercontent.com/54544300/96132705-b7831000-0ec8-11eb-8f19-8e55416473be.png)

It's worth noting that the error message of 'unprocessable entity' is going to be made clearer - it's just what we're getting from the backend currently.

Please let me know if you have any further questions. Thanks!

**Comment by Mottie** [comment]
I need to rewrite part of the code to split out the Redux dependent code. As it is now, it's causing 12 sets of unit tests (48 tests in all) to fail because of the Redux-connected `FileField`.

**Comment by Mottie** [comment]
PR in review - completed first round of recommended changes.

**Comment by Mottie** [comment]
Merged for _all_ forms that upload PDFs; but we still need the claim status tool code to get updated - https://github.com/department-of-veterans-affairs/va.gov-team/issues/14723
