### ISSUE TITLE
Veteran Crisis Line page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14016]
### User story
As a user, I want the ability to connect with a qualified responder in the event that I need urgent help. 

### Acceptance Criteria
1. Selecting the Veteran Crisis Line banner on the Home page routes to a new page called Veteran Crisis Line
2. Styling and UI matches design
3. Two phone numbers on the screen, styled as hyperlinks
     - Click-to-call capability on both hyperlinks. Upon selection, the selected number appears in the native call banner (e.g. in iOS, these are 2 stacked banners at the bottom of the screen: the top banner displays the phone number, and the bottom banner displays Cancel)
     - Selecting the number from the call banner will dial the number via the user's phone app
          - For the first phone number listed on the page, only "800-273-8255" will dial. The "1" menu option will not dial as part of the number
4. Text number styled as a hyperlink
     - Click-to-text capability. Upon selection, the native messaging app opens with the indicated number pre-filled as the message recipient 
5. Start a confidential chat, styled as a hyperlink. Upon selection, the following page opens in browser, out-of-app: https://www.veteranscrisisline.net/get-help/chat
6. Get more resources hyperlink to VeteransCrisisLine.net. Upon selection, this page opens in browser, out-of-app: https://www.veteranscrisisline.net/
7. Pull in the Veteran Crisis Line banner so it also displays on the [Contact VA](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432493860) page _(this should already be done)_

### Designs
[https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432348084](url)

### Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.

### Accessibility Implementation Guidelines 
- Mark “Veterans Crisis Line” as Header 1
- Back button in top left
     - accessibilityLabel= "back"
     - accessibilityHint =“Go back to home”
     - accessibilityRole = “button”
- Mark “We’re here anytime, day or night - 24/7” as Header 2

**Contact links**
- Icons
     - Title= “___Icon” (e.g. Phone, Chat)
     - accessibilityRole= “image”
 - Contact Resource
     - Title= Name of link (e.g. Call 800-273-8255 and press 1 )
     - accessibilityHint= “Dials this number via your device’s call function" **OR** "Opens a new text message with this number via your device’s text messaging function" **OR** “Takes you to a crisis chat web page”
     - accessibilityRole= “link” 

**Get more resources**
- Mark “Get more resources” as Header 2 
- Link
     - Title= “VeteransCrisisLine.net”
     - accessibilityHint= “Takes you to a resource page” 
     - accessibilityRole= “link”

### Assets:
![button chat.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/53f786c7-d854-4f3a-abc3-549f06412668)
![text button.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/2a4832e5-8b0f-457a-b056-f30aa0489f90)
![button phone.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/98fa9dd3-83f9-4cba-a9b6-a9b214043055)

**Comment by bessgreen** [comment]
Hi @bridgethapner, do you mind double-checking the AC for this story? Thanks!

**Comment by bridgethapner** [comment]
Hi there @bessgreen --

This AC looks right to me. I have 2 questions: 

AC #3 -- The Crisis Line instructions are "Call 800-273-8255 and press 1". Does click-to-call dial the number **and** press 1?
AC #5 -- I agree we want to keep the view of the Veterans Crisis Line site in-app. We discussed on #14164 hardcoding "VA.gov" as the in-app web view title. For this web view, we'd need the title to read "veteranscrisisline.net" instead.

**Comment by bessgreen** [comment]
@bridgethapner: 

- AC #3: Click-to-call would only dial 800-273-8255. The "1" is a menu option, not an extension, so we won't be able to roll that into the click-to-call. 
- AC #5: Good to know - we can make the title dynamic and update it on this page so it reads  "veteranscrisisline.net"

**Comment by bessgreen** [comment]
@bridgethapner will the hyperlink at the bottom for VeteransCrisisLine.net open in-app, or will this open in a browser outside of the mobile app?

**Comment by bridgethapner** [comment]
@bessgreen -- 

- Good to know re AC 3, thank you! 
- Great! Let's plan for this to be an in-app web view then.

**Comment by digitalken** [comment]
@bessgreen - For the acceptance criteria #2, I see "Remove bottom nav bar on this page" yet the design shows a bottom nav bar. I'm confused.

**Comment by digitalken** [comment]
Testing:

1. Verify tapping Veteran Crisis Line banner on home page takes user to a new page called "Veteran Crisis Line."
2. Verify styling and UI match design in Invision.
3. There are two phone numbers on the screen that are hyperlinked:
  a. Verify Click to call works on each.
  b. For the 800-273-8255 number, user will have to manually dial the '1' as it is not included in the hyperlink.
  c. Use Deque / Axe to verify touch point height on linked numbers.
4. Verify the Click-to-text hyperlink pops open the native messaging app with the indicated number pre-filled as recipient.
  a. Use Deque / Axe to verify touch point height on click-to-text link.
5. Verify the "Start a confidential chat" link brings up a browser outside of app to https://www.veteranscrisisline.net/get-help/chat
  a. Use Deque / Axe to verify touch point height on chat link.
6. Verify the more resources link to VeteransCrisisLine.net opens up new page in browser to https://www.veteranscrisisline.net/
  a. Use Deque / Axe to verify touch point height on chat link.
7. Verify screen reader can read everything on screen.
  a. Verify announcements by screen reader are of the following form:  Name (title), role, value.
8. Set device to largest font size and verify page scales correctly without losing content, causing content overlap or horizontal scroll.
9. Verify all touch targets are 44px x 44px or larger.
10. Verify page can be navigated and operated by tap, no need to slide any controls.
11. Verify page can be operated with voice control.
12. Verify an auxiliary keyboard can be used to traverse the page.

**Comment by esther-k** [comment]
Issue(s):
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15067

Via Ken Harrison:

"10/20 @ 12:12 PM: Noticed that phone icons aren't the right color compared to designs. Checked with Ken Li and he says they are in flux right now and to come back to it. Designs show blue phone icons should be "primary" which is #0071bc. They are currently the same color as the header, which is "primary-darker" #003e73. Veterans Crisis Line page is the same thing. Go back to check on these after final decisions have been made"

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
UI and functionality pass. Accessibility does not pass with a multi-issue bug entered. Moving this to Design QA for review

[Accessibility Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16238)
