### ISSUE TITLE
move google_analytics_tracking_id to google_analytics.tracking_id in settings.yml

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#14017]
move `google_analytics_tracking_id` to `google_analytics.tracking_id` in the settings.yml file and update the vets-api references

**Comment by erluti** [comment]
Didn't want to lost track of this tech-debt, so I made a parallel ticket for be-tools, https://github.com/department-of-veterans-affairs/va.gov-team/issues/14053.

Went ahead and did the work:
Corresponding PRs:
https://github.com/department-of-veterans-affairs/vets-api/pull/4978
https://github.com/department-of-veterans-affairs/devops/pull/7657

**Comment by lihanli** [comment]
great, thanks for the help!
