### ISSUE TITLE
[Development] 526: Provide Better Error Message when Veteran Uploads Password Protected PDF

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14010]
## Issue Description
During a UAT session, a veteran tried to upload a password-protected PDF and saw a response like this one 
![Screen Shot 2019-09-27 at 3 22 44 PM](https://user-images.githubusercontent.com/11036339/65799944-eb16bf00-e13a-11e9-844b-df6234527232.png)

[related sentry error](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/146117/events/)

Apparently, that was expected behavior as created in:
https://github.com/department-of-veterans-affairs/vets-api/pull/3346

This story is related to #14002 except here we are just trying to add a better error message instead of "Internal Server Error".

## Acceptance Criteria
- [ ] Have a message that explicitly says "please save a copy of your PDF without a password" or something along  those lines
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
I added the backend tag as well.  For reasons that don't make sense to me the BE is intentionally returning a 500 error when an encrypted file is uploaded

**Comment by Mottie** [comment]
For future reference: https://stackoverflow.com/q/52081345

```js
if (contents.indexOf('/Encrypt') !== -1) {
  console.log("Is encrypted");
}
```

**Comment by luke-gcio** [comment]
Closing as being replaced by #14416
