### ISSUE TITLE
Contact VA page + click-to-call

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14015]
### User story
As a Veteran, I want guidance for how I can contact the VA via phone in case I need additional assistance beyond what the app offers. 

### Acceptance Criteria
1. Selecting the Contact VA button from the Home page routes to a new page called Contact VA
2. Styling and UI matches the design
3. Two phone numbers on the screen, styled as hyperlinks
     - Click-to-call capability on both hyperlinks. Upon selection, the selected number appears in the native call banner (e.g. in iOS, these are 2 stacked banners at the bottom of the screen: the top banner displays the phone number, and the bottom banner displays Cancel)
     - Selecting the number from the call banner will dial the number via the user's phone app
4. Pull in the sticky Veteran Crisis Line banner so it also displays on the top of the page (UI only - routing is handled in a separate story)

### Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432493860

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bridgethapner** [comment]
Hi there @bessgreen -- Per a UX Review Meeting I had with VA this morning, we have added the Veterans Crisis Line sticky banner to this page. Documented in #13916.

**Comment by bessgreen** [comment]
Sounds good @bridgethapner - I've added that to the VCL story (AC # 6) in [#14016](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14016)

**Comment by digitalken** [comment]
Testing:

1. Verify that selecting the Contact VA button on the home page routes user to a new page called Contact VA.
2. Verify that styling and UI matches designs in Invision.
3. Verify two numbers are on the new page styled as hyperlinks with "click to call" functionality.
  a. When selected, verify the native call banner pops up with two stacked banners at bottom of the screen.
  b. The top banner will contain the hone number.
  c. The bottom banner will cancel.
  d. Verify selecting the number will initiate the dialing of the number on user's phone.
4. Verify sticky Veteran Crisis Line banner appears at top of page.

**Comment by digitalken** [comment]
Issue(s):
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15063

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Ran tests in TestRail. Failed accessibility with Android. Wrote bug. Moving this to Design QA.
