### ISSUE TITLE
[Design] Health care: Cerner/MHV split use case for My VA dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14025]
## Background

Like with My VA (#13831), we need the new logged-in homepage to account for the split between some veterans being on the Cerner platform and some veterans being on the My HealtheVet platform for their health care information.

I don't know that we necessarily need to handle things the exact same way that we are handling them (or are going to handle them) on My VA for this use case, so I would like us to consider this after the health care section has been mocked up for the primary use case of a user's health care information coming from MHV. Then we can figure out how we can best direct people to the appropriate platform based on the design we have.

## Tasks

- [ ] Design for the Cerner/MHV split for health care users on the new logged-in homepage

**Comment by Samara-Strauss** [comment]
I think we can tackle this in sprint 39. My recommendation would be a single notification that shows within the health care section if someone is detected to be going to any of the facilities using Cerner. I think we should drastically simplify the message from what it is now — they're huge and cumbersome and are probably about as long as the new dashboard. Let's talk about this when you're ready to tackle it.

Also, if this is just a single alert message, we can probably reduce the estimate on this from a 4 to maybe a 1 or 2, but I'll let @tressaellen or @callen2563 handle that.

**Comment by tressaellen** [comment]
Here's a very simple mock for this - we're going to be tracking all the copy changes in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19002). So I think we're good to close.

![MHV.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/c7ac42aa-5f9f-4243-a731-1dbf01ef9a66)

**Comment by Samara-Strauss** [comment]
I think the general design approach is fine, but I would provide better copy guidance to Peggy. This mock copy doesn't make sense (I am assuming it's from the original/existing copy) given the proposed design changes. While we obviously don't need to write actual copy ourselves, mock copy is an opportunity to communicate to Peggy what she needs to include in real copy. Without that, we're putting a lot of the responsibility on her to understand the nuances of a  feature or alert, which she can't do efficiently or effectively without our guidance.

**Comment by tressaellen** [comment]
Sounds good - I'll take a swing at it this afternoon.

**Comment by tressaellen** [comment]
I posted an update in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19002)
