### ISSUE TITLE
Offboarding of howardbrande

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#14021]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Howard Brande
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VFS-CMS, Helpdesk and Support, 9/24/20, Agile 6
- Please provide any type of access they may have and their GitHub username. 
  > SOCKS
  
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jsev-io** [comment]
1. Removed SOCKS Access

2. No AWS Access

3.Removed from the DSVA Slack
![image](https://user-images.githubusercontent.com/63133731/94283342-e12ac600-ff1e-11ea-8793-c9764b16eee7.png)

4. Removed from GitHub Org

5. PagerDuty Access Removed
https://dsva.slack.com/archives/CTYQL39FE/p1601046628025300

**Comment by joanneesteban** [comment]
Removed from GA 360. 

Confirmed no Domo access.

**Comment by jbritt1** [comment]
All line items complete for this user, closing.
