### ISSUE TITLE
[Development] Update 526 suggested facilities endpoint

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#14028]
## Description

A new `v1` endpoint has been added, and `v0` will be deprecated soon (https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/facilities/suggestedFacilities).

We use this endpoint on form 526's VA medical records page

We'll need to coordinate with the facility locator team to determine what changes need to be made, and review the new swagger docs, then update the endpoint call & response processing as needed

Related: https://dsva.slack.com/archives/C5AGLBNRK/p1600968597012000

## Acceptance Criteria

- [ ] Facility location endpoint has been updated

**Comment by Mottie** [comment]
Update: `v1` of the endpoint does not provide `suggestedFacilities` anymore. We need to either find a new API endpoint or completely remove the code using this endpoint.

Related:
- https://dsva.slack.com/archives/CQHBJ5U06/p1605910509496200
- https://dsva.slack.com/archives/C5AGLBNRK/p1606169108464200

**Comment by annaswims** [comment]
@Mottie is it a big deal if we just stop using the API? looks like it's just used for autocomplete and fails gracefully. 

With functioning api:
![Screen Shot 2021-01-20 at 4 13 08 PM](https://user-images.githubusercontent.com/19188/105238310-8f93f000-5b3a-11eb-8c12-0c7bdec504e3.png)
after api is removed:
![Screen Shot 2021-01-20 at 4 15 06 PM](https://user-images.githubusercontent.com/19188/105238882-b2260900-5b3a-11eb-8529-a02d1605b6ad.png)

**Comment by Mottie** [comment]
> is it a big deal if we just stop using the API

It's not a big deal if EVSS doesn't require exact matching facilities names on submission

**Comment by annaswims** [comment]
[swagger docs](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/index.html?url=https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/products/disability/526ez/engineering/evss-docs/wss-form526-services-web-v2.yaml#/form526/submit) say that it just needs to be a string without special characters.

**Comment by annaswims** [comment]
ooh, also EVSS has a [/referencedata/v1/treatmentcenter](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/index.html?url=https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/products/evss-integration/reference-documents/api-docs/wss-referencedata-services-web.yml#/) endpoint that might be exactly what we're looking for.  Though, it wants state as a param.

**Comment by vhenry07** [comment]
Closing ticket as API call removed.
