### ISSUE TITLE
VAEC Utility VPC Running Out of IP space

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#1402]
While creating CMS-CI infrastructure I ran into the problem of the dsva-vagov-utility vpc not having enough free IPs. In an attempt to create an ALB I found that less than 8 IPs were available in subnet-1a and an ALB requires at least two subnets with more than 8 IPs available.

So we need to increase IP space in that VPC. One possibility is to request a secondary VPC cidr.

Another thing to do is to update/recreate the cms-ci-utility elb (or change it to alb) to use at least two subnets since I had to settle for one subnet during creation.

Need to look for 18 or so. 

## AC 
- [ ] check if Unitilty has 3 AZs
- [ ] Do a clean up pass

**Comment by dginther** [comment]
Options available:
1. Request new VPCs
 - Pros: 
    - fresh canvas
    - separation from existing infrastructure
 - Cons: 
    - Permissions / Network routing requests
    - Timeline
2. Request New CIDRs and add them to existing VPCs
 - Pros:
    - No rebuilding of anything we currently have
 - Cons:
    - ESECC redo
    - CIDR confusions, perhaps
    - Timeline
3. Steal IP space from other VPCs we have
 - Pros:
    - We can do this work ourselves
    - Timeline
 - Cons:
    - may have to rebuild multiple environments

**Comment by dginther** [comment]
The decision appears to be to add extra CIDRs to the existing subnets.

I do not have a VA account yet to request these from COMS, so I will need to collaborate on this or hand this to someone who can make the request.

**Comment by tskinn** [comment]
@dginther what does the request look like? Who do we make the request to?

**Comment by ricetj** [comment]
@tskinn we can close this out, right?
