### ISSUE TITLE
Update overall VSP docs to reflect new Pact policy

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#14020]
### User Story 

As a VFS team member, I need VSP docs to account for/explain/direct me to VSP's contract testing information and requirements, so that I can ensure my app meets required quality standards and is production ready. 

### Definition of Done 
- [x] Pact documentation is finalized
- [x] Relevant VSP docs that should reference Pact are identified and updated

**Comment by mchelen-gov** [comment]
some places that might be relevant (not sure if all apply):
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/ (running/debugging/writing sections)
- https://department-of-veterans-affairs.github.io/va.gov-team/
- https://github.com/department-of-veterans-affairs/vets-website/blob/master/README.md
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/README.md

**Comment by mchelen-gov** [comment]
for reference it looks like the WIP docs are: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/contract-testing/how-to-use-pact-for-contract-testing.md

**Comment by alexpappasoddball** [comment]
@meganhkelley is there anything that BE Tools needs to be aware of for this one?

**Comment by holdenhinkle** [comment]
PR to add link to Pact documentation from https://department-of-veterans-affairs.github.io/va.gov-team/ - https://github.com/department-of-veterans-affairs/va.gov-team/pull/22046

**Comment by holdenhinkle** [comment]
PR for updating `vets-website` `README.md` with how to run consumer contract tests - https://github.com/department-of-veterans-affairs/vets-website/pull/16498

**Comment by holdenhinkle** [comment]
We are not adding documentation to this page because it's old - https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/test/

**Comment by holdenhinkle** [comment]
This ticket can be closed.
