### ISSUE TITLE
Investigate the local documentation site build

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14038]
## Issue Description
@Mottie [mentioned in Slack](https://dsva.slack.com/archives/C5HP4GN3F/p1600984131012400?thread_ts=1600975930.006400&cid=C5HP4GN3F) not being able to get the MDX files in the `formation-react` library to render in the documentation site locally using [the instructions](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools#build). We should investigate to see if there are any errors or if the documentation is out-of-date.

It's [possibly a misunderstanding](https://dsva.slack.com/archives/C5HP4GN3F/p1600984728014900?thread_ts=1600975930.006400&cid=C5HP4GN3F), but warrants a brief discovery spike.

**Comment by timwright12** [comment]
closing out in favor of new docs initiative
