### ISSUE TITLE
Keep track of areas where we want content help

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14031]
## User Story
As the UX designer on the VA mobile app team, I want to list out where we most feel we need content help from VSP and list out where in the app there is any content that was not pulled directly, verbatim from VA.gov. 

#### 1. LOA1 gating
We'd like help with the screens where we are explaining to users that will need to identity verify if they are LOA1.

[Screen](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/433563910)
#### Body
To give you access to your personal and health-related information so you can quickly check your claim or appeal status and medical appointments, we need to make sure you’re you. When you sign in, you may be prompted to verify your identity. If your account is not yet verified, you can verify now on your mobile device.

#### Accordion label
Here's what you'll need

#### Accordion text
If you are not yet verified, we can help you verify your identity using ID.me—a trusted partner that provides the strongest identity verification system available to prevent fraud and identity theft.

**To go through the ID.me identity-proofing process on your smartphone, you’ll need:**

1. Your Social Security number
2. Proof of your identity, either:
Your driver’s license or passport, or 
The ability to answer questions based on private and public data (like your credit report) to prove you’re you

#### CTA
Continue to sign in

### 2. Error States
We'd like content help on our error states. We referenced the Error State Style guide but would like to ensure some tweaks we made are in alignment with the guide.

- [Error State to call the call center](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/435506798)
- [Error State to refresh, then call the call center](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/435095150)
- [Error State that ID is missing](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/435506787)

### 3. Direct deposit overview screen
We'd like content help on the explainer text on [the direct deposit overview screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636875): 

**Body:** View and edit your direct deposit information for disability compensation and pension benefits. When you make updates on the VA mobile app, those changes will be reflected on VA.gov.

### 4. Personal & contact Information overview screen
We'd like content help on the explainer text on [the personal information overview screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636868): 

**Body:** When you edit information on the VA mobile app, those changes will be reflected on VA.gov.

### 5. Appointments overview screen
We'd like content help on the explainer test on [the appointments overview screen](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432442341):

**Body:** Your confirmed appointments are displayed below. Appointments that have been requested but not yet confirmed are not shown.

### 6. Claims file upload flow
We'd like content help on this whole flow, which begins [here](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432623517). 

### 7. Contact VA screen
We'd like content help on [this whole screen](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432493860). 

**Title:** Call VA311
**Body:** VA311 is a national toll-free number through which Veterans can access all VA has to offer. 

### 8. Manage account screen
We'd like help on [this whole screen](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432001518). 

**Title:** Manage your account
**Body:** To view or update your sign-in email, go to the website where you manage your account information.

**Comment by srmyers17** [comment]
Error state language

**Comment by srmyers17** [comment]
- F/u on content team's availability to support and potentially set up cadence to meet with them.

**Comment by srmyers17** [comment]
Sign in screens

**Comment by bridgethapner** [comment]
I went through the prototype & documented all the places where it felt like we _really_ need content help for MVP and ordered them in priority order in the ticket. @artsymartha68 when you're back tomorrow, please feel add other places you think we need content eyes if anything feels like it's missing to you. Hopefully, we can get a KO convo with Peggy later this week or early next! cc @srmyers17

**Comment by bridgethapner** [comment]
Hi there @peggygannon and @DanielleThierryUSDSVA Just wanted to give a heads up that I added one more place we would like your guidance, if possible, to this ticket (#2 - Error States). Please let me know if you have any questions about anything listed in the ticket body! Thank you again for your help!

**Comment by bridgethapner** [comment]
@peggygannon @DanielleThierryUSDSVA Apologies for the multiple messages -- just wanted to let you know we are revisiting the UX of **High Priority Item 1 - LOA 1 Gating** right now. Just wanted to let you know to hold on reviewing content there, don't want to create repeat work for y'all. cc @artsymartha68

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @bridgethapner!

**Comment by srmyers17** [comment]
- Bridget and Martha had a sync with content team
- Asked content team to hold off on reviewing while Auth is in progress
- Next steps: regroup with content team later this week

**Comment by bridgethapner** [comment]
Hi there @DanielleThierryUSDSVA and @peggygannon! Just wanted to circle back and say we have solidified our MVP UX/UI for our highest priority item and we are ready for your help on the content front whenever you have the bandwidth.

If it would be helpful to do another Zoom sync to overview again (since we first met awhile ago), I can set up a Zoom at a time that's good for you both.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @bridgethapner! Peggy and I were just chatting about this ticket in our office hours today. We'll have some thoughts on the error messaging (priority 2) to post soon. And we'll start back up on the highest priority item next week. I'll sync w/ Peggy and we can take a look and let you know if we think we need another call to chat before diving in. Thanks again!

**Comment by srmyers17** [comment]
- VSP reviewing now

**Comment by bridgethapner** [comment]
Hi there @DanielleThierryUSDSVA & @peggygannon! :wave: Just wanted to let you know that I will be PTO starting tomorrow until 11/30. If you have any questions about mobile app in the next week, please reach out to @artsymartha68.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @bridgethapner, and hope you enjoy your time away!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @bridgethapner @artsymartha68 @peggygannon. I know Peggy and I both have a large volume of content work right now, and I'm going to be even more focused on covid vaccine communications in the coming weeks. So I'm going to upload my edits/thoughts on these as I go to get this moving along. Happy to talk through and/or iterate further on these as needed. And Peggy, feel free to download my versions and combine our edits/comments if you've been working on these as well. Thanks!

[Mobile app_LOA1 gating_content recommendations_11.29.20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5612983/Mobile.app_LOA1.gating_content.recommendations_11.29.20.docx)

**Comment by DanielleThierryUSDSVA** [comment]
@bridgethapner @artsymartha68 @peggygannon. Error states (Peggy and I both looked at these): 
[mobile app error messages pg & dt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5613036/mobile.app.error.messages.pg.dt.docx)

**Comment by DanielleThierryUSDSVA** [comment]
# Edits for 3, 4, and 5

## 3. Direct deposit overview screen

Add, review, or change your direct deposit information for disability compensation and pension benefits. Any updates you make here will also update on VA.gov.

**or**

Add, review, or change your direct deposit information for disability compensation and pension benefits. Any updates you make here will also update in your VA.gov profile.


## 4. Personal & contact Information overview screen

Any updates you make here will also update on VA.gov.

**or**

Any updates you make here will also update in your VA.gov profile.

## 5. Appointments overview screen

Here are your confirmed appointments. This list doesn't include appointments you've requested but not yet confirmed.

**or**

Your confirmed appointments are listed below. This list doesn't include appointments you've requested but not yet confirmed.

**Comment by bridgethapner** [comment]
Thank you so much @DanielleThierryUSDSVA & @peggygannon! We appreciate your help on these highest priority items! I am going to close this ticket for now. We would love to ask for more of your help in early 2021 (perhaps ~February-March) if you have the bandwidth then (I can reach back out). For now, we feel we have everything we need to go into our next round of testing. 

@bessgreen @jmarchi All content changes are listed in this Google doc: https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit?usp=sharing
