### ISSUE TITLE
Update BGS Gem for View Payments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14035]
## Background
Harlow sent two services that EVSS is using for View Payments: `retrievePaymentSummaryFilterResponse` and `retrievePaymentSummaryWithBDNResponse`.  

## Tasks
~~[ ] Update BGS gem to allow the `retrievePaymentSummaryFilterResponse` data to be utilized~~
- [x] Update BGS gem to allow the `retrievePaymentSummaryWithBDNResponse` data to be utilized

## Acceptance Criteria
- [x] BGS gem code is submitted and a PR is requested for merging

**Comment by kathleencrawford** [comment]
Update: Still waiting on confirmation from BGS that this will return all the information we need.  According to BGS we should only have to call `retrievePaymentSummaryWithBDNResponse` and not `retrievePaymentSummaryFilterResponse`.  We are waiting for access to the `retrievePaymentSummaryWithBDNResponse` API.

**Comment by kathleencrawford** [comment]
Access has now been granted to the BDN call.  According to BGS we only need to use that call and not both calls.

PR has been submitted here: https://github.com/department-of-veterans-affairs/bgs-ext/pull/37
