### ISSUE TITLE
Authenticated login (styling)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14033]
Closing this ticket, as it's been replaced by other tickets related to the login flow.

### User story
As a Veteran, I can log in to the app using my ID.me, MHV, or DS Logon credentials on the va.gov site.

### Acceptance Criteria

1. Login-flow is an in-app web view
2. Selecting the "Sign in" button redirects the user to the mobile Access VA site
3. Center the loading spinner to the center of the page

Should already be done by [14133](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14133):
- Once a user has been authenticated, it will check to see whether they're on mobile, and once it verifies mobile, it will redirect the user back to the app and pass back an auth token.

### Designs

- Splash screen while id.me is loading? 
- header positioning 

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Designs required for loading states / general styling

**Comment by bridgethapner** [comment]
@bessgreen There are not designs for splash screens or loading states yet. I created #14198 for splash screen design for when the app is loading before the user hits the unauthenticated hone screen. I'm not sure I understand when the splash screen, while the sign-in web view is loading, would display -- I figured we'd show the Access VA page loading. Can we touch base about this?
