### ISSUE TITLE
Shore up /sidekiq endpoints

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#14045]
The sidekiq admin app has been made available in vets-api in our non-production environments.  These urls are not behind socks and would allow someone to manipulate sidekiq jobs and disable scheduled ones.  Since it's non-production, there's no PII risk.

This discovery is discussed here https://dsva.slack.com/archives/CQHBJ5U06/p1600807838028400

There were some notes provided for how sidekiq admin could be accessed locally.  We should test that process and if it works, shutdown the urls.  Otherwise we should consider some security for the endpoints.

**Comment by erluti** [comment]
@alexpappasoddball this is the sidekiq stuff we talked about the other day that might need some devops/security opinions

**Comment by erluti** [comment]
related
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17806

**Comment by erluti** [comment]
related https://github.com/department-of-veterans-affairs/va.gov-team/issues/18240

**Comment by jeff2d2** [comment]
Closing as #22354 is a replacement.
