### ISSUE TITLE
Create mobile version for step_by_step MVP 1.1

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#14047]
## Summary

The main boilerplate for step-by-step was created (you can see that tracked [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13135#issuecomment-692227343)), but we still need to implement the mobile design for step-by-step.

You can see the current step-by-step implementation at http://preview-staging.vfs.va.gov/preview?nodeId=6899 (don't forget your 🧦s!)

**The additional info field should only be used for the optional alert and/or screenshot(s).**

## Suggested implementation

Feel free to use `formation-js` to toggle the additional info fields: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/formation/js

## Design spec

Design: https://preview.uxpin.com/192f5be770c74272f782765a19a196aed0a4a588#/pages/132512748/documentation/no-panels?mode=i

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/469deb9d-397f-478f-aa98-c918725f8d56)

## Acceptance Criteria

- [ ] step-by-step matches the design spec on mobile

**Comment by kelsonic** [comment]
CC @andaleliz

**Comment by kelsonic** [comment]
CC @MickinSahni created this ticket as follow-up work for the `step-by-step` template: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13135#issuecomment-692227343

**Comment by brianalloyd** [comment]
@kelsonic what's the status for this ticket?  Will it be ready by end of Sprint 32?

**Comment by kelsonic** [comment]
I haven't picked this ticket up yet 🙂 my guess is no, but it will definitely be knocked out next sprint!

**Comment by brianalloyd** [comment]
Thanks @kelsonic I'm going to update with next sprint milestone, would need this completed prior to OCT 23 in order to remain on pace for internal staging review.  Thanks.

**Comment by kelsonic** [comment]
This very likely won't be completed before Oct 23 due to our prioritization of Cerner work, which is also launching on Oct 23.

**Comment by brianalloyd** [comment]
@kelsonic I'm reworking this ticket and will place in R&S MVP 1.1 Epic for action and tracking purposes.

**Comment by andaleliz** [comment]
There's a bug I noticed during the design phase of this work, captured in [this Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1599749914789/b6142b86cf53c35d5dd632a0a4b406aed6fe0f11?wid=0-1599788381472). Let's make sure we don't re-create that w/ our implementation of this step by step template.

**Comment by jenniferlee-dsva** [comment]
Per this super long thread https://dsva.slack.com/archives/C52CL1PKQ/p1604942685057600, the expander text in mobile will say "Show details" and show/hide the optional screenshot + optional alert. 

1) Step header text 
Step description text, both of these are in 1 wysiwig field. 
Show details...   `<-- expander component`
{expands to show screenshot and alert if any; don't include the expander component if there's no screenshot/alert to show/hide}

**Comment by brianalloyd** [comment]
Fareez please take this on, work with @kelsonic on specific elements for build background.

**Comment by jenniferlee-dsva** [comment]
Hmm. I am still seeing the capitalization @youngfreezyVA . Wondering if the daily deployment didn't go through today? 

I will try again Monday. Just wanted to let you know why I haven't closed this ticket in validation yet.

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/06b85f69-4277-4e2c-892f-d3265174e517)

**Comment by youngfreezyVA** [comment]
yup, the pr for capitalization was merged in earlier today.

**Comment by jenniferlee-dsva** [comment]
validated and closing! Thank you @youngfreezyVA .
