### ISSUE TITLE
Facility Locator map unavailable in mobile

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14046]
## What happened?
<details>
<summary> Map is not visible in mobile tab view </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b6960735-fb8c-4e85-ac3b-8e933db0c908)

</details>

---

<details>
<summary> Returns at breakpoint 482 </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/6ff9db6c-07c6-4e02-878e-767d03f77cdd)

</details>

## Desired behavior
Mobile map experience is equivalent to desktop

## Acceptance Criteria
- [ ] Map appears in tab
- [ ] Map displays results of search and user location (based on parameters) 
- [ ] Map is active (user can pan/zoom)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
This issue identified as showstopper: bring into sprint

**Comment by brangi** [comment]
issue has been fixed - https://dsva.slack.com/archives/C0FQSS30V/p1601069679102300
