### ISSUE TITLE
Analytics Reporting Request for Qaysar

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/va.gov-team#14044]
# Metrics Reporting Request

## What this form is for

I wanted some guidance on how/what your recommendations are for VANotify to track the number of users who get to the claims status page from a notification email we are building (successful submission of the 526EZ disability claim on VA.gov)

We have a link in our notification email content that navigates the user to the claims status page ‘https://www.va.gov/claim-or-appeal-status/’ Do you recommend we add ‘?utm_source=526EZ’ or how do we set this up? 

Also are there norms/best practices we should follow for emails? example - ‘?utm_source=VANotify&utm_medium=email&utm_campaign=526EZ’. 

If there is a different approach or better way for us to track the number of users who get directed to the claims status page from the notification email on VA.gov please let me know

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Qaysar Ahmad

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    VANotify (Notifications for internal VA teams), notification email for 526EZ disability compensation claim
    

## Timeframe for Analytics Requested
Not a high priority - asking for direction and best practices + guidance

## Analytics to Track Down

The number of Veterans who get to the claims status page from a the 526EZ disability claim notification email VANotify is building (The email is sent after the successful submission of the 526EZ disability claim on VA.gov)

## Other Helpful Questions to think through
- Who is your audience?
Internal team and stakeholders 

- Why do you need this data?
Understand the number of Veterans who access the claims status page to view the status of their claim after they receive the notifications email   

- What are you hoping to find?
Veterans are navigating to check the status of their claim from the notifications email  

- What is your hypothesis that you're hoping the data will support?
The notifications email help guide the Veteran to check the status of their claim on VA.gov 

- What area of the VA are you hoping to assess?
Notifications emails and claims status on VA.gov

- How frequently do you need this data?
Weekly and monthly

## Additional Comments
We have a link in our notification email content that navigates the user to the claims status page ‘https://www.va.gov/claim-or-appeal-status/’ Do you recommend we add ‘?utm_source=526EZ’ or how do we set this up? 

Also are there norms/best practices we should follow for emails? example - ‘?utm_source=VANotify&utm_medium=email&utm_campaign=526EZ’. 

If there is a different approach or better way for us to track the number of users who get directed to the claims status page from the notification email on VA.gov please let me know. Jon Wehausen advised to enter a issue for this request 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bmcgrady-ep** [comment]
@QaysarA - I would recommend a link like this: https://www.va.gov/claim-or-appeal-status/?utm_source=VANotify&utm_medium=email&utm_campaign=526EZ to fully build out the UTM parameters. The main UTM parameter that I am questioning a little bit is source. If the link is included in a newsletter email, then the source should be newsletter.

**Comment by QaysarA** [comment]
Hey @bmcgrady-ep , the source is a notification email for the 526EZ form/application and not a newsletter email. 1. Would this be a better way to reflect the source of the email - https://www.va.gov/claim-or-appeal-status/?utm_source=526EZ ?? We would prefer not to include medium or campaign since the source is a notification email for the 526EZ form/application and we can conclude it is from an email and in addition there is no campaign/marketing effort. Please let me know your thoughts    

2. Since this link displays on the email as content, we want to try to make the link short if possible. Is there a way to shorten/hide the long link that you can recommend without losing the tracking? https://www.va.gov/claim-or-appeal-status/?utm_source=VANotify&utm_medium=email&utm_campaign=526EZ

**Comment by bmcgrady-ep** [comment]
Hi @QaysarA - Here is a [link](https://ga-dev-tools.appspot.com/campaign-url-builder/) to Google's URL builder for UTM parameters. It looks like you are required to have source, medium, and campaign.

Also, the URL builder allows you to connect to bit.ly to shorten the link to something like: https://bit.ly/3488z2V

**Comment by QaysarA** [comment]
Thanks for your inputs @bmcgrady-ep on the UTM parameters and also the shortner. Please let me know if there is anything else we need to do if we plan to start using the link. Thanks !!

**Comment by bmcgrady-ep** [comment]
My pleasure to help @QaysarA. I think you should be good to start using the link. Feel free to reach out with any more questions!
