### ISSUE TITLE
Expand VAMC test suite to include basic smoke tests for facility pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14049]
## Issue Description
This issue expands VAMC test suite coverage of facility and system page components 

## Add unit/automated tests to check for the presence of the following basic required components on facility pages:

- Left Nav is present (except for individual event, news release and story pages)

[Facility example home page](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/) has
- Intro text
- Calls to action (buttons are stacked in mobile experience) 
- "On this page" jump links
- Location and Contact Info
  - Address
  - Phone number(s)
  - Clinical hours
  - Photo
  - Map
- Prepare for your visit (with accordions)
- "In the spotlight at VA Pittsburgh health care" (single blue box)
- Accordions within "Health services offered here"
  - "Average days to get an appointment" found within Dermatology, Gastrology, Gynecology, Ophthalmology, Optometry, Orthopedics, Primary Care and Urology
- Veteran satisfaction with appointment wait times at this location
- Get updates from VA Pittsburgh health care  (grey box)

## Acceptance Criteria
- [x] Tests check for the presence of all required components and responsive design. To the extent possible, testing should include checks to be done on mobile devices

**Comment by mpelzsherman** [comment]
Should this be an epic?

**Comment by mmiddaugh** [comment]
Epic is [Expand VAMC test coverage](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13238)

**Comment by mmiddaugh** [comment]
Event tests captured in#13238

**Comment by mpelzsherman** [comment]
> buttons are stacked in mobile experience

We can't test for this using the tools we currently have available.
