### ISSUE TITLE
Debt Letters Iteration 2  VSA-QA Test Plan

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#14059]
**_Please reach out to Brad to turn on feature flag for I2_[https://app.zenhub.com/files/133843125/e26dd1fd-f18b-4b1b-8d9d-7a87094c7449/download](https://app.zenhub.com/files/133843125/e26dd1fd-f18b-4b1b-8d9d-7a87094c7449/download)**

## Product/Feature summary

Debt Letters Iteration 2 builds on iteration 1 in providing the veterans the status of their va debt. 

[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/new%20product_outline.md)

[Designs I2](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263526/simulate/no-panels?mode=i)

[Epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9932)

The attached spreadsheet has all the debt statuses that could be encountered 

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: 
Content/IA: Mikki/Peggy
Front-end: Brad
Back-end: Cameron
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs (ideally, use [this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md) from VSA Design Lead).  IMPORTANT for authenticated-experiences: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

1. <Use Case 1> - <test-account-1>
2. <Use Case 2> - <test-account-2> ...

## How to configure this issue

- [x] Product Manager added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Actual Test Runs completed on Staging \[or optional [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by leahkeeler** [comment]
[https://app.zenhub.com/files/133843125/e40a6ced-776f-4cc8-8786-dc678cfeb5e1/download](https://app.zenhub.com/files/133843125/e40a6ced-776f-4cc8-8786-dc678cfeb5e1/download)

**Comment by tlei123** [comment]
@leahkeeler @pjhill @bradl3yC , should we meet to discuss our coverage/scope strategy?  

The Diary-Codes spreadsheet (https://app.zenhub.com/files/133843125/e40a6ced-776f-4cc8-8786-dc678cfeb5e1/download) lists about 90-100 codes triggering about 30-40 combos of Status & Next-Steps content.  I don't think either I or Brad would have the capacity to cover all the codes, but we should decide on a good compromise, covering (ideally) all the Status/Next-Step combos (rows) if feasible [or as many combos as we can].

Let me know what you think please.  Thx much!

**Comment by tlei123** [comment]
> https://app.zenhub.com/files/133843125/e40a6ced-776f-4cc8-8786-dc678cfeb5e1/download

@camerontesterman , above is the download link for the diary-codes/status/next-steps spreadsheet, which @leahkeeler may have an update for also.

**Comment by tlei123** [comment]
@bradl3yC , IF the latest e2e test files are not on master branch, please let me know the feature branch.  I'd like to take a look at them before my next convo w/ @pjhill .

IF they're work-in-progress, that's fine, just be sure to let me know.

Thx much!

**Comment by leahkeeler** [comment]
Here is the final edits for content 
[Debt.letter.status.final (1).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5418353/Debt.letter.status.final.1.xlsx) @tzelei

**Comment by tlei123** [comment]
^ @bradl3yC @camerontesterman , fyi, Leah just added download-link above for statuses spreadsheet.

**Comment by tlei123** [comment]
@craigwheeler , which of these 2 vets-website branches should I watch for new/updated automated tests for the diary-codes/next-steps?  Or, should I be watching a different branch from these 3?
- 13764-diary-codes-content
- 13765-diary-codes
- 13765-diary-codes-content

Please let me know.  Thanks much!

**Comment by craigwheeler** [comment]
hey @tlei123 :wave: ... the PRs you listed above have already been merged and are now closed, however I should be finishing up diary codes shortly so if it helps i'll post a branch containing the new tests here

**Comment by leahkeeler** [comment]
@tzelei Did you get a chance to connect with Peter to see in e2e tests will suffice in lieu of manual ?

**Comment by craigwheeler** [comment]
@tlei123 I created e2e tests to cover use cases for when there is a `next step` and when there is `no next step`... lemme know if this works or if I should add/change anything? The PR is [14059: cypress tests for diary codes #14836
](https://github.com/department-of-veterans-affairs/vets-website/pull/14836)

cc @leahkeeler

**Comment by tlei123** [comment]
> @tzelei Did you get a chance to connect with Peter to see in e2e tests will suffice in lieu of manual ?

@leahkeeler , yes I did.  @pjhill agrees we should rely on automated-testing to validate the data-scenarios.  QA will focus on functionality & content/styling.


> @tlei123 I created e2e tests to cover use cases for when there is a `next step` and when there is `no next step`... lemme know if this works or if I should add/change anything? The PR is [14059: cypress tests for diary codes #14836 ](https://github.com/department-of-veterans-affairs/vets-website/pull/14836)

Thx, @craigwheeler !  I'll check the test changes today and add my feedback to the PR [if it's still Open] or here [if that's Closed].

**Comment by tlei123** [comment]
@craigwheeler @pjhill , I added my feedback to the [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14836#issuecomment-722704639).  Basically: we need add'l tests to validate specific expected content for specific codes.

**Comment by tlei123** [comment]
@leahkeeler , Test Cases are up on TR:
- Debt-details-with-Next-Step - [C824](https://dsvavsp.testrail.io/index.php?/cases/view/824)
- Debt-details-with-Alert (WIP) - [C820](https://dsvavsp.testrail.io/index.php?/cases/view/820)

@craigwheeler @camerontesterman , for Debt-details-with-Alert data-scenario, lets touch bases A.S.A.P.* to determine test-account 38 (Pauline) readiness.  I checked Staging today (Wed 11/11) and her Debt-list is empty.  Thanks much!

*I'd like to start test-runs no later than early afternoon (MST) tomorrow (Thu 11/12) if at all possible.

**Comment by bradl3yC** [comment]
Her debt list is empty - user 1 has debt cards.  User 38 has debt download links

**Comment by bradl3yC** [comment]
@tlei123 here is a screenshot of the alert being triggered by diaryCode 608

![Screen Shot 2020-11-12 at 12.23.15 PM.png](https://images.zenhubusercontent.com/5450f83c7c6ccc6277a5c4b7/f7a0a612-0606-4484-9fea-ea805a0e8af7)

**Comment by tlei123** [comment]
@leahkeeler , all test-runs now completed.  QA-artifact links:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/682)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/151)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/150)

Defects logged: #16307, #16309
