### ISSUE TITLE
[Frontend] Caregiver QA feedback 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#14054]
## Issue Description
_This ticket contains UI feedback on 10-10CG as it appears in staging. Categorize by page. Please let me know if you have questions_

### General (footer)
- [x] Shift "Use our online Caregiver Support Coordinator search tool" link 4px to left align with other content

<img width="392" alt="Screen Shot 2020-09-25 at 11 01 22 AM" src="https://user-images.githubusercontent.com/58444931/94289542-78dbe480-ff1e-11ea-87ee-0d2a263a5857.png">

- [ ] Adjust spacing

![Spacing ](https://user-images.githubusercontent.com/58444931/94477165-222d0f80-0197-11eb-9828-7af602538db4.png)
 
- [x] Design issues - Gender is no longer required on form (radios) 

<img width="523" alt="Screen Shot 2020-09-28 at 2 29 35 PM" src="https://user-images.githubusercontent.com/58444931/94477524-a41d3880-0197-11eb-8d87-c2d772c103ba.png">

### Intro page 

- [x] PDF download link: Remove "the" - Should read "Download VA Form 10-10CG (PDF)" to be consistent with Drupal page 

<img width="597" alt="Screen Shot 2020-09-25 at 9 50 56 AM" src="https://user-images.githubusercontent.com/58444931/94282644-ad976e00-ff15-11ea-8c55-313cd8015e45.png">

### Medical Center page

- Not a task - Do you know why some facilities are in all caps and some are not?  

<img width="594" alt="Screen Shot 2020-09-25 at 11 52 59 AM" src="https://user-images.githubusercontent.com/58444931/94295782-61552980-ff27-11ea-823e-38e403d9881f.png">

### Review Page
- [x] Update wording on signature page: 
`I understand that participation in the PCAFC does not create an employment relationship between me and the Department of Veterans Affairs.
`is provided for each signature box for caregivers but the primary caregiver statment is missing “the” in “the PCAFC”
`I understand that participation in PCAFC does not create an employment relationship between me and the Department of Veterans Affairs.`
- [ ] Not a task - I thought we were not going to show Secondary Caregiver on the review page (if user did not select Secondary Caregiver) BUT we might have had a constraint because the "Do you want to add a secondary caregiver" question is it's own chapter - Can you remind me again?
<img width="768" alt="Screen Shot 2020-09-25 at 1 57 36 PM" src="https://user-images.githubusercontent.com/58444931/94306206-24ddf980-ff38-11ea-8ed9-9f8fa826c75e.png">

### Error
- [x] Please add spacing after "...completed application" and "Mail your application to..." 

![Screen Shot 2020-09-30 at 12 05 08 PM](https://user-images.githubusercontent.com/58444931/94716938-3b5bca80-0315-11eb-81b0-9a12e867fbe0.png)

- [ ] VA.gov button (to home page)

**Comment by LinnJS** [comment]
Just noting that `Gender is no longer required on form (radios)` was done in a earlier PR

**Comment by LinnJS** [comment]
Responding to `Not a task - Do you know why some facilities are in all caps and some are not?` this has something to do with how the backend is handling this need to look on the API side.

**Comment by LinnJS** [comment]
@jonathanjnelson I am going to follow up with `Adjust spacing` in another PR since that will take considerably more time and finagling. Want to get all these other changes in sooner than later.
