### ISSUE TITLE
UAT bug: Form page preview not showing any form last updated date

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14058]
## UAT bug: Form page preview not showing any form last updated date

This may be related bug to ticket #14024. 

On this form page preview for the 10-250: http://preview-prod.vfs.va.gov/preview?nodeId=6489

The `Form last updated` field is missing in the preview. 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/82a18df3-3bc3-4cd1-ba44-28f4ef5d7808)

However, when you look at the CMS forms meta data, it has an Issue date (no Revision date). Since the most recent date is from the Issue Date field, the FE should be displaying the `Form last updated` field with that date. (Again - the logic is not to pull from a specific date field but to show whatever is the most recent date of either the Issue or Revision dates. )

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/5cd43ae8-db67-4b8a-a85c-1cb03cc47e50)

**Comment by MickinSahni** [comment]
Waiting for https://github.com/department-of-veterans-affairs/va.gov-team/issues/14024 to validate before we can check to see if this issue is resolved

**Comment by ncksllvn** [comment]
I think that will happen if both the "issue date" and "revision date" is empty

**Comment by jenniferlee-dsva** [comment]
But as you can see in the screenshot above, the Issue date had a value. Hmm. @ncksllvn

**Comment by jenniferlee-dsva** [comment]
The missing form date is now appearing on this form and with the right 'latest' date. So maybe the PR for the other date bug fixed this one? 

![image](https://user-images.githubusercontent.com/43381063/94733806-52f77b00-0336-11eb-8ec7-2f591272e3ac.png)

**Comment by jenniferlee-dsva** [comment]
![image](https://user-images.githubusercontent.com/43381063/94733886-6f93b300-0336-11eb-8e74-493f136b6a95.png)

**Comment by ncksllvn** [comment]
> But as you can see in the screenshot above, the Issue date had a value. Hmm. @ncksllvn

Ah so prior to https://github.com/department-of-veterans-affairs/va.gov-team/issues/14024 only the revision date was being taken into account for the "last updated" field. The form in the screenshot only has an issue date, so "last updated" was just being hidden.

I think https://github.com/department-of-veterans-affairs/va.gov-team/issues/14024  fixed this issue as a side effect. Thanks for flagging this @jenniferlee-dsva

**Comment by ncksllvn** [comment]
I'll move this to validate so we can triple check before close

**Comment by MickinSahni** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/13204473/95103465-9ff69b00-0702-11eb-8ea2-4e0fb1347b1f.png">
