### ISSUE TITLE
CT: Remove prod flag for search results content updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14068]
As a developer, I need to remove a prod flag so the updated content is available in the production environment.

## Assumptions:
1. The work completed in #13938 has been reviewed and signed off in staging as of 10/20/2020.

## Acceptance Criteria
1. The work completed in #13938 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14656

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now in Production. Closing this issue
