### ISSUE TITLE
CT: Remove prod flag for shared content updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14066]
As a developer, I need to remove a prod flag so the updated content is available in the production environment.

## Assumptions:
1. The work completed in #13929 has been reviewed and signed off in staging as of 10/21.

## Acceptance Criteria
1. The work completed in #13929 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14657
Branch: bah-14066

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
These changes are now in prod. Closing this issue
