### ISSUE TITLE
Create new slack channel for security alerts 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14069]
Related to #8954

**Comment by jhouse-solvd** [comment]
connect with Julian on whether or not this has been done

**Comment by jhouse-solvd** [comment]
@jjulian Did you get the channel set up that you need?

**Comment by jjulian** [comment]
> @jjulian Did you get the channel set up that you need?

I don't think this is mine. Another "julian" out there?

**Comment by jhouse-solvd** [comment]
@jjulian - Yep, that was gaffe. Sorry for the unnecessary ping. Cheers!

**Comment by jhouse-solvd** [comment]
@jsev-io - Did you get the channel created that you needed?

**Comment by jsev-io** [comment]
@jhouse-solvd yup! I did. thanks. we can close this.
