### ISSUE TITLE
Ensure Sentry 10 has appropriate data backups

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#14062]
## Description

As part of the rollout of Sentry 10, we need to ensure that it has the proper data backups.

## Definition of Done
- [x] Investigation to if the backups exists is complete and this ticket is closed with comments confirming they exists
OR 
- [ ] a new ticket is created to create those backups and assigned to the Sentry 10 upgrade epic and prioritized

**Comment by omgitsbillryan** [comment]
Didn't take much digging, we get this for free for being part of BRD (see the ["Create backup snapshots" ansible task](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-instances/tasks/instances-inner.yml#L6-L13))

![image](https://user-images.githubusercontent.com/3077884/94296836-7cc53200-ff31-11ea-86f1-519d7c9e8f43.png)
