### ISSUE TITLE
EDU: Create feature flag for education form updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14064]
As a developer, I need to create a feature flag for the 1995 updates so that it is not displayed in production as development is completed.

## Assumptions:
1. Feature flag for 1995 updates is needed the vets-api and vets-website repos.
2. The Feature Flag is configured per environment.
3. When the feature flag is:
     a. Off: The 1995 content updates are not displayed.
     b. On: All of the 1995 content updates are available.
4. The feature flag is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. The Feature Flag `form_1995_edu_updates ` is available to be used for the search enhancements.
2. The Feature Flag description is: "Form updates to bring EDU forms in compliance with latest DEPO patterns and practices"
3. The feature flag is created and available in all environments.

## Tasks
1. Follow feature flags documentation to create front-end school ratings feature flag.
2. Follow feature flags documentation to create back-end school ratings feature flag.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5013
https://github.com/department-of-veterans-affairs/vets-website/pull/14437

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-10-01 at 12.06.37 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3b24d0d0-4be4-48e3-a6da-91fc6757050b)

**Comment by delli-gatti-michael** [comment]
The flag is now on Staging. Closing this issue
