### ISSUE TITLE
Prepare to Migrate extra VSP projects for Sentry

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#14060]
## Description

There are additional projects that live in Sentry 9 that are outside of `vets-website` (frontend) & `vets-api` (backend).  We need to reach out to the teams responsible for the sections listed below to ensure they are still needed and the plan to move them to the new Sentry.

- If they want to use Sentry 10 we'll need to migrate their projects
- This could include code changes in their repo, might not be 1:1 w/ `vets-api` 
- Will require configuration of `environment` setting as well `SENTRY_ENVIRONMENT=$environment`
- Where $environment is one of `'development', 'staging', 'sandbox', 'production'`

### VSP

- [x] [Content Preview Portal](http://sentry.vfs.va.gov/vets-gov/content-preview-production/) @thilton-oddball @ericboehs 
- [x] [GI Bill Data Service](http://sentry.vfs.va.gov/vets-gov/gi-bill-data-service-production/) --- [#7655](https://github.com/department-of-veterans-affairs/devops/pull/7655/files)

**Comment by alexpappasoddball** [comment]
@kfrz @ericboehs @thilton-oddball For this task (ie. ticket) the idea isn't to actually migrate it, but to create a draft PR to migrate it once we get confirmation that is needed in the new sentry instance right?  I'm guessing Staging/Prod (for vets-website & vets-api) and these projects listed above will all migrate on a predefined date (October 6th).  Is that a correct assumption?

**Comment by kfrz** [comment]
Yes - this is to align understanding and communications

**Comment by kfrz** [comment]
Projects are all created in Sentry 10.

**Comment by kfrz** [comment]
- OAuth is not present in the `devops` repo, discover where this configuration lives cc @patrickvinograd @wyattwalter

**Comment by wyattwalter** [comment]
@duganth can you help with finding the config here?
