### ISSUE TITLE
Access for Edison Velez

### ISSUE THREAD

**Issue by evelez-va** [department-of-veterans-affairs/va.gov-team#14076]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Edison Velez
- Please Provide your email.
   > edison.velez@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I am on the LeeroyJenkles team as part of the Lighthouse project. I am a DevOps engineer at Liberty IT Solutions.

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdF3yzJhX1EvR+ZDmWnLoOL1Xdgq7v/xCae8UzQRv9ucI0uR0wQYMoIty8sADmpf6sOzrD/AK6MMzi/Mkj+dFbteP/ta7Wp/e/Lz1C1YtgF1R2FQ6GNfqROHtCk4gfU/rKor0wqXoXGmQ8Wuw8EVZv0TqG0BDFDkrvb0bJ8tzLeahrCZDchGG4gNaLAZEztcchMaL+WAXI2r9tF479nE1lSpc6hzjcTohm9zPEnsSKEUqdEEuOmFh/gKqxi2/cH1aHq1k0Ql4P/HvzFVhYAT+2XyYHtxHrVPBMEQ4HOWcGvNLeRwToSz/GZ0FLfW4yAYAEtdjgEgmEOJsu5BEEtL7ePinZ7Pg/vu5LZNiLgmyCC2kJn8tS2LkADSvkV1+iLZTrXv7tsSHk84z0OXefvIpozpPS8jTsiK0r+ZpdvQohf31+P8AaoDVa4cEVhh0aRoXFi7uC2IuigooY8WIcz8RZvPcu9ozrMQVPog3oqF9/pVvvpoal5g5IvzSG6bicch0= edison.velez@libertyits.com
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
I am on the DevOps team and will need console access for managing Lighthouse components that still reside in DSVA

**Comment by evelez-va** [comment]
@department-of-veterans-affairs/vsp-operations please review.

**Comment by tskinn** [comment]
@Jeff-Hayter

**Comment by tskinn** [comment]
@evelez-va you should be able to access the socks proxy now. Reach out in slack if you have any issues.

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS access.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
