### ISSUE TITLE
Project Intake Request: Dynamic Statement of Benefits

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#14075]
## Request
The Office of Transition and Economic Development (OTED) wants to know the feasibility of create a personalized Statement of Benefits (SOB) for transitioning Service members (TSM) and newly-separated veterans (NSV) via VA.gov.

The vision is: the transitioning Veteran answers a "few" questions and will receive a personalized SOB in return.  The full requirements are TBD in consultation with VA.gov.

OTED needs to know the feasibility of including this functionality into eBenefits as part of its transition to va.gov.  OTED is interested in the following:
 
- Funding required
- Internal stakeholders required
- Timeline
- OTED resources needed

## Background
The Office of Transition and Economic Development (OTED) is leading the VA’s joint collaboration with the Department of Defense, Department of Labor, and other agencies to implement a strategy to assist Service members in their transition from the military to civilian life. The effort is called Military-to-Civilian Readiness Pathway and it is Congressionally-mandated (via the John S. McCain National Defense Authorization Act for Fiscal Year 2019).

This addition requires the military services to provide a summary of all benefits available to members of the armed forces and Reserve Components on current benefits administered by the Department of Defense and Department of Veterans Affairs. The assessment of benefits and entitlements must be provided no later than 30 days before a member retires or separates from active duty.

Per Chris Johnston: 
This sounds remarkably similar to the Benefits Navigator project, which was not ultimately successful.  Sounds like explore.va.gov.

Per Steve Kovacs:
This may be linked to Authenticated experience as well.  Could be connected to the idea of an eligibility rules engine.

## Business Stakeholders
 - Lawrencia Pierce, Deputy Director, OTED at Lawrencia.Pierce@va.gov
 - Christopher Maclin, Senior Program Analyst, Office of Business Integration at VA

**Comment by johnhashva** [comment]
Notes from 9/30 meeting with @steve-gov & @Samara-Strauss:   Some key questions to get answers for are:

- What is actually mandated?  What does this mean -- and what does it require?  This is a tall order to say the least.  This will take a big team, algo development, etc.

- Do we actually have access to all the data sources to make this accurate, valuable to do a high quality "one fits all" eligibility rules engine. (We did some thinking around this -- and came to the same conclusion)

- Keep in mind individual benefits are managed/governed by different lines of business -- compensation, education, etc.  -- feudal lines of business that are not centralized.   Just maintaining data quality will be really hard.

- IF there are 200 benefits, as an example, that a veteran may be entitled to -- each of those benefits has an eligibility matrix that has 15-20 elements.  

- **Explore VA history (benefits navigator)**: questionnaire where at end "benefits you are likely eligible for."  Decent user experience; prior to VA.gov redesign, it was silo'ed; there were questions about the quality of the eliribility criteria (wasn't necessarily up to date); utility was questionable and its "decision engine" was questionable as well.

- Would this be an authenticated product?  ExploreVA was not -- more of a wizard.   

- You can't really tell someone they are eligible (in a simple way) -- some of these processes require confirmation/proof, adjudication (by someone else, it's subjective).  Most of these programs are means-tested.

**Comment by Samara-Strauss** [comment]
I did a quick Google search for Military-to-Civilian Readiness Pathway and the John S. McCain National Defense Authorization Act for Fiscal Year 2019 and here's what I found:

- Military-to-Civilian Readiness Pathway is a VA term and nothing I could find in legislation (though I understand the general idea of helping service members transition is congressionally mandated). [There's more about on it on benefits.va.gov](https://benefits.va.gov/transition/transition-home.asp#:~:text=The%20Military%20to%20Civilian%20Readiness,help%20you%20achieve%20civilian%20success.).
- As for [the John S. McCain National Defense Authorization Act for Fiscal Year 2019](https://www.congress.gov/bill/115th-congress/house-bill/5515/text), I did Ctrl F for "benefits" and found this:

> SEC. 522. STATEMENT OF BENEFITS.
> 
>     (a) In General.--Chapter 58 of title 10, United States Code, is 
> amended by adding at the end the following new section:
> 
>
> [[Page 132 STAT. 1756]]
> 
> ``Sec. 1155 <<NOTE: 10 USC 1155.>> . Statement of benefits
> 
>     ``(a) Before Separation.--Not later than 30 days before a member 
> retires, is released, is discharged, or otherwise separates from the 
> armed forces (or as soon as is practicable in the case of an 
> unanticipated separation), the Secretary concerned shall provide that 
> member with a current assessment of all benefits to which that member 
> may be entitled under laws administered by--
>             ``(1) the Secretary of Defense; and
>             ``(2) the Secretary of Veterans Affairs.
> 
>     ``(b) Statement for Reserves.--The Secretary concerned shall provide 
> a member of a reserve component with a current assessment of benefits 
> described in subsection (a) upon release of that member from active 
> duty.''.

So, it sounds like the summary is exactly what this team said – there is a mandate to provide a statement of benefits to folks for "benefits to which that member may be entitled." But, there is nothing prescriptive about how anyone does this or what exactly that means.

I still think another call with this team to find out more is still a good idea. After having read this part of the legislation, I agree with Steve that the best move forward after talking to this team would be to get a high quality discovery team to learn more, investigate, and propose a solution. However, let's not mention any possibility of that on a call since we can't promise people to do that.

**Comment by Samara-Strauss** [comment]
## Notes from 10.8.20 regroup

### Overview

- **Most importantly, it sounds like the VA is already meeting the congressional mandate of providing a statement of benefits to the separating service member through DoD via TAP**. So, while the statement of benefits is congressionally mandated, this project is not.
- What exists now: For TAP, VA puts together a list of benefits people might be eligible for based on their character of service.
  e.g a list of benefits for people who have an honorable discharge, less than honorable, etc.

### What they want to do

- Basically they want to create an explore.va.gov type questionnaire on VA.gov.
- Want this to be executable by the end of next year for when eBenefits fully sunsets.

### Questions

**Denise: Has there been research with separating service members?**

- Dr. Pierce: We haven’t been able to do human centered design research. But, if we came up with a plan and said that was a milestone, I could go back to DoD to see if we could make that happen.

**How do you see VA.gov being involved?**
 
- Dr Pierce anticipates a contractor or supporting team would help make the questionnaire and VA.gov would build it on the website.

**Do you have a contractor to work on the questionnaire yet?**

- Have nothing yet. 

**Is there room for MVP and further growth?**
 
- Dr. Pierce seem open to this. Wants the group of people on the meeting to come up with a project plan and then she can go back to leadership to figure out how to get funding and resources.

**What about maintenance over time?**

- They haven't thought about it. I think thinking through some of this is new to the team, but they seem amenable to figuring out how to do this the right way.

**Who would we be working with?**
 
- Chris Matlin, Bill Brimley, or Mike Caldwell.

**When should we regroup?**

- Chris to come up with a list of what we want to accomplish in/by the next meeting (identity stakeholders, how we get to a project plan, where would this be a good fit in terms of who can do the work). Let’s start with a once a week cadence and then likely move to biweekly.

**Comment by Samara-Strauss** [comment]
**My thoughts**

- I think this is worthwhile work, and it's stuff our team has talked about before. 
- This would really benefit from involvement from DEPO or USDS to help guide this work in the right direction. The team seemed super amenable to guidance and is aware that they have blind spots in who this would be executed. 
- However, that being said, this is huge work that would need to be sustained over time. How well are we set up to do that?

**Comment by johnhashva** [comment]
The CTO benefits team (led by. Zach Goldfine and Chief Data Officer Denise Kitts) -- who have been working to _shape and launch impactful, lean experiences to further the mission of improving service member data and speeding benefits delivery_ -- are engaged on this initiative as well.  They provided the following relevant discovery documentation for background.

[2020-09-01_Helping service members  and veterans access their service data.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5355120/2020-09-01_Helping.service.members.and.veterans.access.their.service.data.pdf)

[2020September_Understanding the value of service members and Veterans viewing and editing their service data_General Discovery Research.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5355130/2020September_Understanding.the.value.of.service.members.and.Veterans.viewing.and.editing.their.service.data_General.Discovery.Research.pdf)

[2020September_Understanding the value of service members and Veterans viewing and editing their service data _Post-awardReturnToActiveDuty (2).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5355131/2020September_Understanding.the.value.of.service.members.and.Veterans.viewing.and.editing.their.service.data._Post-awardReturnToActiveDuty.2.pdf)

**Comment by johnhashva** [comment]
10/15 Update: (FYSA @Samara-Strauss + @steve-gov 

- Weekly update meeting held with Christopher Maclin, William Brimley of OTED and Denise Kitts (OCTO) and members of her team.  Dr. Pierce was OOO and unavailable.
- No specific agenda items were provided -- so Brimley wanted a level set, with following questions:
  - Are we moving Benefits Explorer over to VA.gov from eBenefits as part of the migration? (Needs to be validated by Steve Kovacs)
  - Do we want to modify Benefits explorer when we bring it over and that will meet the goals of this project?  Could be easier to do than building a new thing?
        - Hashimoto: Maybe next step is a Gap Analysis of the Explorer vs. what is desired.  And we should determine through analytics and user testing how effective Explorer is in meeting Veteran expectations/needs. 
        - Maclin: Let me make sure Pierce is aware of Explorer so she can determine if a gap analysis is a good starting point. 
- Next Steps:
        - Hashimoto: Ask Kovacs (a) if there are plans to bring Benefits Explorer to VA.gov — and if that is on roadmap for 2021 with the sunset of eBenefits expected by end of year (true?)
        - Next week’s meeting will happen, with expectation that we will all have updates to share.

**Comment by johnhashva** [comment]
Background on explore.va.gov (per Steve and Samara):
- Was a website where veteran answered some questions and then it showed you benefits that s/he may be eligible for, and linked off to the benefit "homepages (in Teamsite)" under the old VA site system.
- The site did have the wizard/quiz, but it was also largely a content site. Most of the content was duplicative of content on VA.gov, so anything that was duplicative was retired and anything unique was moved over to the public websites portion of our site (integrated in, no separate section for this stuff).
-  The quiz wasn't bad but it also wasn't great. You couldn't save the results, it wasn't in context of benefits you already have, and there was always a question mark about how accurate/up-to-date the benefits information it served up was (not for lack of effort on that team's part, but because eligibility is near impossible to capture/keep updated in entirety).

**Comment by johnhashva** [comment]
10/15 meeting notes via Christopher Maclin:

**Purpose:**
The purpose of the call was to discuss the feasibility of developing an individualized statement of benefits in va.gov.  We know there is an effort to sunset eBenefits and transition its data into va.gov.  The Office of Transition and Economic Development (OTED) is interested in adding functionality in va.gov that will allow a Veteran to answer a series of questions, and based on the responses to those questions, receive an individualized statement of benefits.

Discussion:

Ms. Kitts –

- Mentioned Benefits Explorer.
   - Benefits Explorer access is authenticated (the user logs into the system) and non-authenticated (the user does not log into the system).
  - The courses of action are 1) leverage the current Benefits Explorer as a foundation for the future  functionality OTED envisions; 2) develop new functionality.
 
Mr. Hashimoto –
- Benefits Explorer is not in the current version of va.gov.  There are questions as to whether or not Benefits Explorer has not been successful.
- Will reach out to Matt Self and Steve Kovacs about the va.gov roadmap and functionality.
 
Mr. Brinley –
- Will get Dr. Pierce’s understanding of Benefits Explorer.
- Will get vision for the way she wants to proceed with the effort.
- Will work with OTED to schedule the next meeting.

**Comment by Samara-Strauss** [comment]
Closing. Bill Brinley's team is still working on this, but OCTO is not involved.
