### ISSUE TITLE
[Development] BDD: Military Separation Question Update

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14070]
## Issue Description
Update military separation question to read "Are you currently on active duty?" and switch yes/no logic for BDD qualified.

## Acceptance Criteria
- [ ] Switch the question out and make sure the yes/no is switched (since before they said NO to indicate BDD versus YES now)
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
The design for this is located here: https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/421391041_BDD_Gating_-_Have_You_Separated
