### ISSUE TITLE
[Development] 526: Military Branch BGS API Integration 

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14073]
## Issue Description
We want to see if we can leverage the pattern we are working on for separation location for military branch drop down in the military history area.  We are seeing preloaded data from EMIS not match our dropdown and creating issues.  It seems like if BGS has an endpoint for this we can leverage it once Nick figures out how to add non-prefill data to the forms.

## Acceptance Criteria
- [ ] We confirm BGS has an API
- [ ] We write a backend service hitting the API
- [ ] We write the front end story for this work
- [ ] We write a caching story for this work
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by edmangimelli** [comment]
>We are seeing preloaded data from EMIS not match our dropdown and creating issues

Do you have an example of the issues that are being created? (sentry?)

**Comment by edmangimelli** [comment]
is this the issue of prefill data not matching what's in the dropdown on the front end?
@Mottie

**Comment by Mottie** [comment]
I don't know the details. Nick has a PR open that pulls the separation location list from the `/disability_compensation_form/separation_locations` API endpoint - https://github.com/department-of-veterans-affairs/vets-website/pull/14416

**Comment by luke-gcio** [comment]
After talking to Anna, she made the point that this would add complexity and not really add a lot of value.  We were converting Air Force Reserves to a code wrong in one case, but with that corrected we don't have a need to make a more complex change.
