### ISSUE TITLE
Review and correct invalid education URL appearing in search

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#14071]
The following URL is showing up as a best bet when you search for "licensing and certification"

URL showing: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/licensing-certification-fees/
Search results: https://www.va.gov/search/?page=1&query=licensing+and+certification

The correct URL for this page is: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/

- [ ] Review history of these URLs to understand what is correct and what happened
- [ ] Update best bets to correct URL
- [ ] Validate that incorrect URL is not getting traffic or search engine traffic
- [ ] Implement redirect on incorrect URL if necessary

Reported by @bethpottsVADEPO

**Comment by mnorthuis** [comment]
@johnhashva This is a best bet change, are you able to make this update?

**Comment by johnhashva** [comment]
@mnorthuis  -- Already made (on Friday) via this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14074

**Comment by mnorthuis** [comment]
Funny, didn't realize Beth had created the same ticket...closing as duplicate!  Thank you!
