### ISSUE TITLE
[FE] Contribute not scrolling to Multiple Questions

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#14084]
## Description
The built-in forms system does a jarring scroll when a user enters an answer to a list of questions. We have determined that to not quite fit our design and flow. We are proposing a configuration value to toggle the scroll on and off. 

## Tasks
- Make the scrolling optional
- Create tests
- Add documentation 
- Submit a PR to the platform
- have platform access the changes

## Acceptance criteria
- Form doesn't scroll when a user adds a new question
- Fix is in vets-website master and deployed to staging

**Comment by mdewey** [comment]
Accessibility does not want this change. They have found that users want to see the new input and be focused on what they are wanting to 

Link to conversation: https://dsva.slack.com/archives/C8E985R32/p1604423197114800?thread_ts=1604421009.111800&cid=C8E985R32

Looking for next steps @abuckley3385 @kristenmcconnell

**Comment by mdewey** [comment]
Status update: 

Accessibility and design are now onboard after a meeting.  Accessibility is testing the change and the engineering team will work with the platform team to get the change in and help document it.

**Comment by mdewey** [comment]
Blocked due to waiting for testing .

**Comment by mdewey** [comment]
Current status: 

- merged in master and in staging 

Received [this comment](https://github.com/department-of-veterans-affairs/vets-website/pull/14802#issuecomment-728103905). TL;DR; Platform team is not changing the list loop for the time being. 

@kristenmcconnell  and @abuckley3385, can you verify that is does not scoll in staging?

**Comment by kristenmcconnell** [comment]
It does not scroll from what I'm seeing.

**Comment by abuckley3385** [comment]
looks fantastic!
