### ISSUE TITLE
Create content for onboarding discussion around security and privacy

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#1408]
Create some content to go over our security and privacy tools during onboarding. Someone from Tools team will go over this in the onboarding meeting.

**Comment by rianfowler** [comment]
## CORS 
  - CORS flow (headers, OPTIONS) required on all relevant services, assets 
  - document how to add hosts to allowed-origins
## CSP 
  - content security policy must not be circumvented / modified 
  - document current content security policy 
## HTTPS only 
## CORB
  - may not need to document anything here (requires discovery)
  - `content-type` must be defined?

**Comment by rianfowler** [comment]
Adding a document to the client documentation site that we can use as a source for the onboarding stuff: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/164

**Comment by brandonrapp** [comment]
Updated presentation is here - https://docs.google.com/presentation/d/11GWnu5r2qg8P12uglVY6q3P5t3rzGWoC170n0irTNl0/edit?usp=sharing
