### ISSUE TITLE
VSA dev intent: Learning center, MVP 1.1 - media_list_videos

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#14086]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This issue contains the VSA accessibility feedback for the Learning center, MVP 1.1 - media_list_videos

### Designs to consider

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11497

#### Desktop

![Screen Shot 2020-09-25 at 3 54 16 PM](https://user-images.githubusercontent.com/57469/94310294-69bd5c80-ff47-11ea-8d17-ae92dce54fef.png)

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by laflannery** [comment]
No feedback provided, closing
