### ISSUE TITLE
VSA dev intent: Learning center, MVP 1.1 - process_list

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#14087]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This issue contains the VSA accessibility feedback for the Learning center, MVP 1.1 - process_list

#### Desktop

![Screen Shot 2020-09-25 at 3 57 47 PM](https://user-images.githubusercontent.com/57469/94310604-e51f0e00-ff47-11ea-9581-7379b4e426d9.png)

![Screen Shot 2020-09-28 at 6 37 57 PM](https://user-images.githubusercontent.com/57469/94493106-cd4ec080-01b9-11eb-876a-0e1a4209bac9.png)

#### Mobile

_Not provided_

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by laflannery** [comment]
No feedback provided, closing
