### ISSUE TITLE
Discovery - Integrated sites & VAOS (FE app + SM)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14099]
We continue to get reports that integrated sites are getting requests to the 'wrong' facility.

FE app previously worked on a bug that fixed missing integrated facilities, but we have reports from Buffalo and Miami that those 'parent' sites are still incorrectly receiving requests that should be going to 5 digit VistA sites (as part of integrated sites). 

This needs full workflow investigation to make sure the requests moving from the FE to SM are properly mapping and displaying data. 

### Expected behavior:
- Veteran is CC eligible
- Veteran chooses from city/state list if eligible for more than 1 site
- Based on city/state selection, site id map to location and passed to SM
- SM display appropriate facility with request

### Actual behavior:
- SM is only identifying CC requests at the 'parent' level - is this because it's only recognizing 3 digit sites?
- SM not properly routing Veteran CC request

**Comment by jbalboni** [comment]
I checked the parent sites call for these two sites (528 and 546). Buffalo looks fine, so users should have the option of choosing between Buffalo, Syracuse, Albany, and Bath. 

Miami does not appear to be set up in CDW as an integrated site, so searching for 546 only returns the Miami VAMC.
