### ISSUE TITLE
Staging:  You need to have visited within the last 12 months message is incorrect

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#14096]
## What's happening
This message populates several times in the UI and is incorrect.  I have found veterans with past appointments getting this message.
![Nacier_DSYes_ReqYes12m_modal.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/f4b11f0d-1fe3-4246-a5f8-f3fc3164c850)

## Feedback
The message displays should really indicate that last visit is specific type of care.  

## Steps to Recreate:
1.  In VATS set Request to  "Yes Any Veteran."
2.  Select a veteran that has past appointments in a differing stop code than the one selected in new UI for type of care.  Another way to say this veteran will not have any past appointments in the stop code selected in type of care AND does have past appointments in other stops codes at that facility.    
3.  Select a type of care, select Facility.
4.  VAOS displays, "We couldn't find a recent appointment appointment at this location.  You need to have visited this facility in the last 12 months".    The veteran HAS visited the facility and has had past appointments.  So this is incorrect.  

Steps to Recreate: nacier.y.stowe![Nacier_DSYes_ReqYes12m_modal.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/bc3fa69d-23aa-49ed-ba2c-8296e6d9d67e)@id.me
1.  VATS =  Audiology Cheyenne Direct Scheduling = YES and Request = Yes 12 if seen in last 12 months. 
2.  Veteran has past cancelled appointment in audiology (Friendly Name Audiology clinic) but NO checked in/checked out audiology appts (which means they do not meet the criteria for Request). 
3.   Direct Schedule criteria met because VATS is set to Yes Any. 
4. In VAOS select Audiology, Select Cheyenne VAMC.  
5.  VAOS displays, "We couldn't find a recent appointment appointment at this location.  You need to have visited this facility in the last 12 months".     The veteran HAS visited the facility and has had past appointments.  So this is incorrect.  

## Actual Results
Copy in alert is "You need to have visited this facility within the last {time frame} to request an appointment online for the type of care you selected.

## Expected Results
- Copy in alert is:

> You need to have visited this facility within the past {time frame} for {type of care selected} to request an appointment for this type of care.

## Definition of Done

- [ ] Steps return expected results
- [ ] Alerts documentation is updated https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md

**Comment by lenaecb** [comment]
@jbalboni - trying to understand what's needed here. Since you marked this for 'content' I assume that we've validated that we're properly passing the recency check. It seems like we need an additional alert that we don't have? 

Is the content change actually that we need to say 'You need to have visited this facility within the past 12 months for {type of care selected} to request an appointment for {type of care selected}.

**Comment by jbalboni** [comment]
@lenaecb Yes, that content change is the issue. It's not any appt in the past 12 months, it's an appt for that type of care in that time frame.

**Comment by peggygannon** [comment]
HI, @laurenernest Here's slight update to the message proposed above: 

 You need to have visited this facility within the past 12 months for {type of care selected} to request an appointment for this type of care.

**Comment by jbalboni** [comment]
@laurenernest Are we ready to make this change on the FE?

**Comment by laurenernest** [comment]
@jbalboni Yep! The description is updated with expected results and definition of done.
