### ISSUE TITLE
[Discovery] Upgrade vets-api to Rails 6.0

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#1409]
Research what it takes to upgrade to upgrade to rails 6 as well as any blockers 
## Acceptance criteria
- [ ] list of potential blockers such as gems that have not been updated and are no longer maintained
- [ ] issues created detailing steps that can be completed prior to an upgrade to rails 6
- [ ] issues created detailing steps to upgrade to rails 6
- [ ] overview of new features va.gov could benefit from
- [ ] Review and create documentation that outlines the process that VSA would follow if we upgrade a code base in the future.

**Comment by johnpaulashenfelter** [comment]
Woohooo! Glad to see this on the docket.

I'd love to see activestorage replacing shrine and carrierwave as part of this, though that isn't Rails6 directly.

**Comment by erluti** [comment]
Betamocks is locked to rails < 6, so it needs updating before vets-api can use it with rails 6.

**Comment by erluti** [comment]
Upgraded betamocks with this PR https://github.com/department-of-veterans-affairs/betamocks/pull/19

**Comment by erluti** [comment]
`apivore` is a gem used for testing that is marked incompatible with Rails 6.0.2.
`active_model_serializers` is locked for our project at 0.10.4 because later versions remove nil id keys, and our specs expect those to return "null".  However, 0.10.4 doesn't support Rails versions greater than 6.0.0.

**Comment by erluti** [comment]
Forking `apivore` and `active_model_serializers` and releasing the version lock allows the Rails 6.0 upgrade to continue, so with that approach the upgrade can continue.
