### ISSUE TITLE
Offboarding of [Glen Holcomb]

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#14098]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Glen Holcomb
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Software Engineer, AdHoc
- Please provide any type of access they may have and their GitHub username. 
  > ex: SOCKS, Pagerduty, Google analytics, ect.
  
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jbritt1** [comment]
https://dsva.slack.com/archives/C03FECE9K/p1601301913008300

**Comment by jbritt1** [comment]
PagerDuty not applicable for this user

**Comment by joanneesteban** [comment]
Confirmed no GA 360 or Domo accounts.

**Comment by bsmartin-ep** [comment]
GA 360 account for Glen Holcomb was just removed.

**Comment by jbritt1** [comment]
Seems to already be removed from GitHub org:

![image](https://user-images.githubusercontent.com/56260532/94444866-c5206200-0174-11eb-90f3-bec1819a87bd.png)

**Comment by jbritt1** [comment]
All access revoked, just awaiting confirmation for Slack from the Slack administrators team.

**Comment by jbritt1** [comment]
All line items complete for this user.
