### ISSUE TITLE
[Discovery] Automatically Create "VA" tickets when errors are detected from 3rd party services

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#141]
## Story
As a VA Platform Engineer, it takes a lot of time and effort to manually triage Service Now tickets.

## Goal
Create an automated process for creating tickets in Service now when errors are detected form a 3rd party backend.

## Risk
- Tickets will get diluted if too many are created and tickets could get stale if they don't get addressed quickly.
- When a human create a ticket, whoever picks up the work can reach out to the ticket creator. When it is automatically generated, the engineer picking up the ticket might not know where to go to address questions or get more context.

## Breakdown of work
- Medium effort part: Make an api call to UIT (already on VA Network)
- Hard part: reach service now outside of VA network (might not be possible)

**Comment by annaswims** [comment]
This issue seems like it's outside the scope of this epic.

**Comment by annaswims** [comment]
I'm not convinced that this is worth doing.  I don't think we create enough servicenow tickets to justify the effort or that the tickets we do create are repetitive enough to be automatable.

**Comment by kfrz** [comment]
@annaswims agreed. Let's close this and clean up the board a bit.
