### ISSUE TITLE
Add supporting descriptions to 'type of care' labels + direct user to 'call facility' if not seeing type of care

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14108]
As a veteran starting the scheduling flow, I want to clearly understand what is involved/covered by each type of care label so I can make an informed decision. 

![14108-type-of-care-labels-v2-pr.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/bb499627-f741-4362-b461-d4dde0b43ea3)

## Acceptance criteria:
- Add helper/support text to care type labels so Veterans are clearer on what all that label covers (from a care perspective)
- Add alert/direction for users who do not see the type of care they need in the list
   - User should contact their VAMC to request care via phone

**Comment by peggygannon** [comment]
@lenaecb @rtwell Here are types of care descriptions/labels. Please let me know if you have any questions. 

[https://app.zenhub.com/files/133843125/4cadd57a-33a5-46b6-b9ce-9b4fa6695017/download](https://app.zenhub.com/files/133843125/4cadd57a-33a5-46b6-b9ce-9b4fa6695017/download)

**Comment by outerpress** [comment]
@peggygannon @lenaecb @rtwell here's the mockup. I used the informational box for the alert. Feedback welcome, as always.

![14108-type-of-care-labels-pr.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/211e9e99-6aeb-4cf7-be4e-c73e79c636f9)

**Comment by peggygannon** [comment]
Hi, @outerpress This looks good. the only additional edit I suggest is to update the parenthentical content for Podiatry TO: 

Podiatry (community care appointments only)
Treatment for feet and ankle injuries or disorders

**Comment by outerpress** [comment]
Sounds great @peggygannon, I updated the mock and dropped it into the story description.

**Comment by peggygannon** [comment]
thank you @outerpress !

@rtwell @lenaecb how do you think this looks on mobile? do you recommend any more trimming?

**Comment by lalexanderson-dsva** [comment]
I'm sorry to be a pain, but I'm not sold on the solution of adding more words to this page to describe these types of care at this time. We have other parts of the application where we describe some of these type of care services. (i.e. the breakdown between audiology and hearing aid battery, the description of optometry and ophthalmology). 

As I think about the outcomes of that research study that prompted this modification, i'm less convinced that veterans do not know what these types of care are but rather are confused about what type  of _appointments_ they can get at VA using online scheduling app for this type of care. For example, "Should i select primary care to get a COVID-19 test or a flu shot?" or the bit that comm care flagged 4 us - you can get a basic eye exam, but NOT see a doc for glaucoma. 

I do not want to add a lot of words to this page without that understanding. Maybe @outerpress can work this into his convo guide somehow on this or a future user rsch study. I also am very keen to dig more into the clinics to see what kind of data we can get about them.

**Comment by lenaecb** [comment]
@lalexanderson-dsva - yep, we have this current design mock with the added supporting text in the testing prototype so will have more data/research on what a veteran is seeking on this page and/or if this addition is even helpful.

**Comment by lenaecb** [comment]
At a minimum, I think we break this ticket a part. We need to get the alert added in for folks that aren't seeing the type of care they want. @laurenernest - can you create a ticket just for implementing the following addition?
![Screen Shot 2020-11-04 at 11.14.18 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/b8bd36ed-e980-4e5a-a22d-251453535266)

**Comment by laurenernest** [comment]
@lenaecb Alert-specific work can now being tracked here https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15794

**Comment by peggygannon** [comment]
hello @lenaecb @laurenernest Is there anything more needed for this ticket?

**Comment by laurenernest** [comment]
@peggygannon No additional content work needed for this ticket right now.
