### ISSUE TITLE
School Ratings - Test Data Identification

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14102]
- [x] Define schools, ratings for testing efforts 
- [x] Work with Devs to create data

**Comment by JenLJ** [comment]
UX touched base with devs on what is needed for test data creation.  Request is that UX convey what cases will be tested.

Preliminary testing scenarios:
1) Compare 2-3 campuses within a single school (e.g. University of California or University of Maryland [backup])
2) Compare 2+ schools users will have to search for separately (e.g. options are schools with same program, top 5 US Rankings schools, etc.)

**Comment by amyknox** [comment]
Dev story: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13620

**Comment by amyknox** [comment]
Create general rules for ratings across the board, refine specifics for the 4-5 schools we want to target with testing.

**Comment by JenLJ** [comment]
School ratings data files:
“School Ratings for Test Data” shows the easy-to-digest summarized version of the ratings
“school_rating_ux” is the actual CSV devs will be uploading

File location:
https://boozallen.sharepoint.com/:f:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/UX%20Assets/Research/School%20Ratings?csf=1&web=1&e=uicu3M

**Comment by amyknox** [comment]
@JenLJ - looks like this may be complete.  True story?

**Comment by JenLJ** [comment]
@amyknox True story!  Closing
