### ISSUE TITLE
Provide clearer direction + context for homepage scheduling button

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14105]
As a Veteran who wants to schedule an appointment at the VA, I want to clearly understand that when I start the scheduling flow it is for an appointment "request" for either VA or CC. 

**In Research:** We received scores of feedback that it is not clear that a Veteran is making a 'request' when they are going through the scheduling flow. 

## Acceptance criteria:
- Update button from "Schedule an appointment" to "Request an appointment"
- Consider adding clearer support text with the "Request an appointment" button update
- only display when direct schedule feature flag is off
- also update Express Care H2 to follow similar content pattern
- header, inter text, and button should change to following:

H2: **Request an appointment**
You can submit a request for an appointment at a VA medical center, clinic, or approved community care facility.
{button} Request an appointment

Please update ExpressCare header too to more closely match this style:
H2: **Request Express Care**

### Current prod implementation
![Screen Shot 2020-09-28 at 1.55.55 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/592765e3-e089-4be5-9c03-e268191f3339)

*NOTE:* When direct schedule is turned back on, we'll need to update this again to be more inclusive of the varied paths. But while we only have requests, let's be very direct in letting users know that clicking that button will only create _an appointment request._

**Comment by peggygannon** [comment]
@lenaecb @rtwell  Here's my recommendation for this landing page (until Direct scheduling is turned back on). 

would love your thoughts on ""Make an appointment" "Request an appointment" vs **Create an appointment**  I don't recall if any research was done into this heading?. The static landing page leading into the tool says "view, schedule, or cancel". But we cant use "schedule" at this time.  I was wanting to take opportunity to look at this header again. 

option 1 **Make an appointment**
option 2 **Request an appointment**

You can submit a request for an appointment at a VA medical center, clinic, or approved community care facility.

{button} Request an appointment


If we update the above H2, then here's is my recommendation for Express Care header (options below)  

**Make an Express Care request**
**Request Express Care**

**Comment by rtwell** [comment]
I think we should be as direct as possible, throughout the user flows in vaos, that they are making a **_request_** for an appointment. In theory (assuming direct scheduling is enabled), when a user is going through vaos, they are skipping along not knowing if they are making a request or direct sched. this is great b/c the veteran shouldnt have to know or care, we do all of that for them. what we **_don't_** do, is tell veterans explicitly what's actually happening _when they need to know_ they are making a request and not direct scheduling. That said, this ticket isnt about rewriting the entirety if the flows, but it's something we should use to guide our language across the board. 

that said, I like the idea of calling these what they are: requests. if it helps, something we've been thinking about is separating Requests from Appointments on the aggregate page.

**Comment by peggygannon** [comment]
@lenaecb Based on today's VAOS sync, here is updated content for that screen: 

H2: **Request an appointment**

You can submit a request for an appointment at a VA medical center, clinic, or approved community care facility.

{button} Request an appointment

Please update ExpressCare header too to more closely match this style: 

H2: **Request Express Care**

**Comment by lenaecb** [comment]
@grossb1 - I checked and it looks like your PR is merged, but I just went in to test and didn't see these updates. Do you have another PR open for this work?
