### ISSUE TITLE
Audit all in flow alerts (eligibility, error, recency) & make sure accurate/actionable

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14109]
Given the various logic a user has to pass through to make an appointment - either request or self-schedule) - every alert needs to appropriately account for the proper context and always offer a 'next step' for the veteran that is getting them closer to getting the appointment they are trying to book. 

## Acceptance criteria:
- audit existing alerts throughout the flow
- identify areas for improvement/iteration
- all alerts should appropriately direct the user towards action of 'getting an appointment scheduled' 

*NOTE:* You may need to pair with a FE engineer to properly get all the alerts to display. They can force those alerts via their local environments.

**Comment by lenaecb** [comment]
@peggygannon - I am prepping for our next sprint (starts Wed, 10/14) - I wanted to make sure to keep space in the sprint for a eng or two to assist you with this. Do you think this will be something you'll be pulling in next week or the following week (10/19)?

**Comment by peggygannon** [comment]
Hi, @lenaecb Yes I can pull this into my next sprint. (starting 10/14).. I would need screenshots of all the alerts/messages so I can do the audit. Let me know the best way to do that!

**Comment by peggygannon** [comment]
@lenaecb @narin Please let me know the best way I can review all the alerts and messaging in VAOS.

**Comment by narin** [comment]
Hey @lenaecb.  @peggygannon and I chatted and determined that because there are so many conditional alerts and not all of them can be triggered easily on staging, the best way to do this would be for me to search through the codebase, trigger them on my local machine and take screenshots of each page.

There are close to about 50 different alerts so this would likely take me about half a day.  Just wanted to update you on the LOE so we can prioritize this audit in the upcoming sprints.

**Comment by lenaecb** [comment]
Cool, thanks for the note @narin 

I mentioned to Peggy that we made need her to pair with a FE in order to get these alerts triggered. We'll bring this work into our upcoming sprint (starts tomorrow after planning).

**Comment by narin** [comment]
Hi @peggygannon, I've taken documented and screenshotted all alerts that can appear during the New Appointment flow here: 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md

Please let me know if you have any questions.

**Comment by peggygannon** [comment]
thanks, @narin  would you prefer that I update the markdown file with my edits? or drop in my edits into this issue?

**Comment by narin** [comment]
@peggygannon Hmm. I'm thinking we might want to track any edits within this ticket, and once they've been deployed, I can update the markdown file with new screenshots and we can try to keep it updated as documentation of our alerts. How does that sound?

**Comment by peggygannon** [comment]
@narin OK, sounds good!

**Comment by peggygannon** [comment]
Hi, @narin @laurenernest  Uploaded below are my content edits/recommendations for the in-flow VAOS alerts. Please let me know if you have any questions. Thx!

[https://app.zenhub.com/files/133843125/cc067c54-0f9b-4be8-bff0-5669b0da8c0f/download](https://app.zenhub.com/files/133843125/cc067c54-0f9b-4be8-bff0-5669b0da8c0f/download)

**Comment by laurenernest** [comment]
@peggygannon Added questions for you in your doc. [https://app.zenhub.com/files/133843125/10162ad1-a833-4ad3-80c9-52311ce0f0b0/download](https://app.zenhub.com/files/133843125/10162ad1-a833-4ad3-80c9-52311ce0f0b0/download)

@narin For _Calendar Page: Direct Schedule > Slot Loading Error_, what are the steps to repro this error? If there are issues loading the direct schedule calendar, do they see the request calendar instead? (since we're saying you can submit a request)

**Comment by narin** [comment]
> @narin For _Calendar Page: Direct Schedule > Slot Loading Error_, what are the steps to repro this error? If there are issues loading the direct schedule calendar, do they see the request calendar instead? (since we're saying you can submit a request)

@laurenernest We make an API call to fetch the slots on load, and then each time they press "prev" or "next" month.  The error message would display if this API call fails.  We don't fallback to the request calendar, but I think this would be a good idea.

**Comment by narin** [comment]
@peggygannon I've converted the doc with your suggestions to a Google Doc that I've shared with you so we can collaborate more easily.  

https://docs.google.com/document/d/1Yuhjc6EiavYJi7vcY5SibOrQHKiClKf_6NusHu5OucA/edit?usp=sharing

Can we address @laurenernest's comments there, as I make the copy updates?

**Comment by peggygannon** [comment]
@narin and @laurenernest I've responded to your questions in the google doc. Provided recommendations on updated messaging as needed. Please let me know if you have any questions. thx

**Comment by narin** [comment]
Changes have been merged and verified on staging.  Closing this ticket out.
