### ISSUE TITLE
Form 10-10CG: A signature shows up for a Secondary Caregiver that I removed

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#14106]
## What happened?
On the online 10-10CG, a signature shows up for a Secondary Caregiver that I removed while filling in the form.

## Specs:
- Device: Macbook
- Browser: Chrome
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL: https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg
- Test User _(if applicable)_: N/A

## Desired behavior
If I remove a secondary caregiver from my application, I should not see a signature field on the review page for that caregiver.

## Acceptance Criteria
- [ ] Can add a secondary caregiver, fill in the required fields, remove them from the application, and submit the form without requiring the signature of the removed caregiver.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by LinnJS** [comment]
This was addressed and fixed in this [PR](https://github.com/department-of-veterans-affairs/vets-website/issues/14385)
