### ISSUE TITLE
[Discovery] Add a 'sort by form last updated' function on modern forms search

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14112]
## Add a 'sort by form last updated' function on modern forms search

**User story:** As an external user of VA forms - such as a state Veterans benefit agency or a Veterans claims agent service - I need to access the full list of VA forms by the most recent form updated date. 

Today, by doing a null search, users are able to get the full list of forms. However, users are not able to view the forms in the order of the most recent **Form last updated** date. This is a frequent request by organizations using VA forms (e.g., state veteran agencies).

Acceptance Criteria:
- [ ] Create design for 'Sort by Form last updated' date feature following established pattern if one exists.
- [ ] Estimate effort required to test and implement the solution
- [ ] Go/No go decision on implementing 
- [ ] If implemented, issues to capture each task required to complete

**Comment by MarciMcGuireGCIO** [comment]
Grooming note: John to meet with Laurel Lawrence and get this teed up

**Comment by MarciMcGuireGCIO** [comment]
Adding fix to last updated date as a dependency.

**Comment by johnhashva** [comment]
Adding @laurellawrence who is scrubbing in for a few months as Public Websites UX designer and can help us tackle this one.

**Comment by MarciMcGuireGCIO** [comment]
Unblocking this.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/15241 and this issue can be worked in parallel.

**Comment by MarciMcGuireGCIO** [comment]
Adding a new related task to separate design from the engineering work.

**Comment by MarciMcGuireGCIO** [comment]
Making note of Laurel's discovery that no pattern for this feature currently exists in the design system.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva given the above ^^ any objection to my converting this issue to a discovery item so that we can properly size the effort, and weight that against ROI before proceeding further?

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO no objection.

**Comment by MarciMcGuireGCIO** [comment]
Changing AC for this issue to capture discovery criteria only.  Other AC related to the actual solution has been captured in https://github.com/department-of-veterans-affairs/va.gov-team/issues/17732.

**Comment by MarciMcGuireGCIO** [comment]
We discussed this feature and currently don't believe that user testing is needed since this is for a secondary audience

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO can this be closed now that https://github.com/department-of-veterans-affairs/va.gov-team/issues/17901 is ready?

**Comment by MarciMcGuireGCIO** [comment]
Yup! Closing now. Thx!
