### ISSUE TITLE
Learning Center Articles List - MVP 1.0

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#14114]
## High Level User Story/ies
As a Veteran, I need to view LC articles so I can find more information about a benefit or service I'm interested in.

**In scope**
- **Ranking**: alphabetical
  - [Reference section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/view-all-articles-in-X-category-landing-pg-requirements.md#all-articles-in-x-lc-category-landing-page)
- **Description snippet**: 200 char max followed by ellipsis `...` if more than 200 char is returned in the field
  - [Reference section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/view-all-articles-in-X-category-landing-pg-requirements.md#all-articles-in-x-lc-category-landing-page)

**Not in scope**
- Ranking:
- Description snippet: 

**Outstanding Questions**
- Description in search result - how truncated?
- Ranking/ordering - what is "default?"

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by jenniferlee-dsva** [comment]
completed, closing
