### ISSUE TITLE
Slight tweak to VAOS footer

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14111]
We have received feedback from the help desk that Veterans are calling them to get help with their VA appointment. The help desk is only available to triage issues with the app itself, not specific appointment issues. 

### Acceptance Criteria:
- all phone numbers should be hyperlinked.
- update footer to following:

> **Need help?**
> If you have questions about using the VA appointments tool, or if the tool isn’t working right, please call 877-470-5947 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.
>
> If you need help scheduling a VA or community care appointment, please call your VA or community care facility. [Find your health facility’s phone number.](https://www.va.gov/find-locations/)
> 
> For questions about joining a VA Video Connect appointment, please call 866-651-3180 (TTY: 711). We’re here Monday through Saturday, 7:00 a.m. to 11:00 p.m. ET.

-----
### Context
We made an update to the static scheduling page that we should consider for the VAOS footer:
![Screen Shot 2020-09-28 at 11.59.46 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/bb33b4dc-ad67-400d-95a3-99635aa663d4)

For reference, current footer:
![Screen Shot 2020-09-28 at 1.54.09 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/06bf3bf5-8502-4bca-b872-c4aaef67854c)

**Comment by peggygannon** [comment]
@lenaecb Updates to the Need help footer are below. Let me know if you need anything more on this. 


**Need help?**
If you have questions about using the VA appointments tool, or if the tool isn’t working right, please call  [877-470-5947] (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.

If you need help scheduling a VA or community care appointment, please call your VA or community care facility. [Find your health facility’s phone number](va.gov/find-locations/)

For questions about joining a VA Video Connect appointment, please call [866-651-3180] (TTY: 711). We’re here Monday through Saturday, 7:00 a.m. to 11:00 p.m. ET.

**Comment by lenaecb** [comment]
Awesome, thanks @peggygannon

**Comment by lenaecb** [comment]
Hi @LanceGundersen - I just noticed while testing on staging that the content for this is incorrect.

Currently the footer on staging reads:
![Screen Shot 2020-10-21 at 9.18.31 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/7170ce5d-b999-444a-a7d7-8eed95919944)

**We need to update the first line to say:**
If you need help scheduling a VA or community care appointment _tool_,...

**Comment by lenaecb** [comment]
The footer should read the following:

> Need help?
> If you have questions about using the VA appointments tool, or if the tool isn’t working right, please call 877-470-5947 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.
> 
> If you need help scheduling a VA or community care appointment, please call your VA or community care facility. Find your health facility’s phone number
> 
> For questions about joining a VA Video Connect appointment, please call 866-651-3180 (TTY: 711). We’re here Monday through Saturday, 7:00 a.m. to 11:00 p.m. ET.

@LanceGundersen @jbalboni

**Comment by jbalboni** [comment]
This should be on staging now

**Comment by lenaecb** [comment]
Awesome, thanks @jbalboni and thanks @LanceGundersen for getting this updated. 

I've verified and all looks good. I'll check again on prod after this afternoon's deploy.
