### ISSUE TITLE
Analytics Support for VA.gov efforts

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#14118]
# Google Analytics Implementation or QA Request

## What this form is for

<summary>Adding VA.gov functionality launch dates to the GA annotation tray</summary>

## Description
- Is this request for Google Analytics implementation or QA? 
    - **Implementation / Annotation**

- Who is this request for?
    - **Booz Allen team.  Contact Amy Knox: knox_amy@bah.com**
    
- What team/project is this work for?
    - **Booz Allen team / Education Service VA.gov GI Bill Comparison Tool and STEM Scholarship**
   
- Provide the Domain where Google Analytics needs to be implemented
    - **www.va.gov**
        
 - Relevant dates to include in annotations: 
    - July 14 - CT Fuzzy search updates 
    - July 31 - CT Benefit level update, Colmery 105
    - Sep 10 - 22-10203 STEM Scholarship Production Launch
    - Sep 10 - CT Text search improvements 
    - Sep 14 - CT Filter enhancements

- Additional Comments

    - Would like these added to help with tracking future efforts.  Let me know if you have any questions! 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @amyknox , acknowledging receipt!

**Comment by jonwehausen** [comment]
@bmcgrady-ep Find out what annotations and where we need to include

**Comment by amyknox** [comment]
@jonwehausen - I included dates and details in the original story under "Relevant dates to include in annotations".  Definitely LMK if you need more info!

**Comment by bmcgrady-ep** [comment]
@amyknox - I added the annotations to Google Analytics. Let me know if there are any more that need to be added.

**Comment by bmcgrady-ep** [comment]
@amyknox - closing out this issue as the annotations have been added.
