### ISSUE TITLE
Calendar iteration/updates

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14110]
We noticed during testing that Veterans got tripped up a few times on the following design items relating to calendar selection:
- Veterans who were looking to schedule an appointment beyond the 2 months shown almost _never_ noticed the 'Next' button to show more months
- Veterans were not clear as to what constituted as 'AM' hours - is that 8am-12pm? 9am-12pm? Other hours?

## Acceptance criteria:
- we remove "Previous" and "Next" and replace with icons on mobile
- show one month at a time (instead of two)
- abbreviate days of the week on mobile
- update AM/PM to include descriptors - AM - before noon, and PM - after noon (see mock below)

## Specs
https://adhoc.invisionapp.com/share/FSZEGAUBP3E#/screens/437745940

**Comment by rtwell** [comment]
I'm thinking we do something like this:

1. we show one month at a time (instead of two)
2. we remove "Previous" and "Next" and replace with icons on mobile
3. abbreviate days of the week on mobile

![image](https://user-images.githubusercontent.com/12564977/94973084-ca651000-04d8-11eb-9ae4-a4ace3dcbb8d.png)

![image](https://user-images.githubusercontent.com/12564977/94973328-65f68080-04d9-11eb-932f-8a482ac2c408.png)

**Comment by peggygannon** [comment]
@lenaecb @rtwell I'm confused on the above screenshots, as they are showing two different headers and intro content. 

Also, I'm looking on staging (below) and I see the calendar is showing actual time slots (not just AM and PM). Which screen is correct? 

![Screenshot (7).png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/e3d045ba-7068-417d-98e7-7c0449ae078d)

**Comment by lenaecb** [comment]
Hey @peggygannon - the screenshot you have is for the self-schedule flow (which is still enabled for staging) and does allow for selecting direct times slots. 

For your first question, it looks like Ryan accidentally intermixed the VA request calendar content and the VA self schedule content. 

Current header for VA requests (on staging and prod) is:
 ![Screen Shot 2020-10-09 at 2.36.17 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/2c56a030-eeaa-4803-acb7-9e800073de4f)

**Comment by peggygannon** [comment]
@lenaecb here's what I recommend for the AM/PM explanation in the calendar

AM: before noon
PM: noon or later

**Comment by laurenernest** [comment]
@jbalboni Not yet. I'll pulled it until we have the final specs.

**Comment by outerpress** [comment]
VA Request calendar, only change @rtwell 's designs is the addition of the AM/PM descriptions. We could also add a footnote to the page but I thought it'd be most helpful at the point they need to make the decision. Thoughts @peggygannon and Ryan?

![VAOS-cal-desktop.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/f0fa3454-986c-474e-80eb-79f69c64c404)
![VAOS-cal-mobile.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/d161c666-0031-47da-b674-565ac7b862a2)

**Comment by peggygannon** [comment]
Hi, @outerpress this looks good to me. agree it works well having these within the calendar box.

**Comment by outerpress** [comment]
@laurenernest - [Specs (currently in progress) live here](https://adhoc.invisionapp.com/share/FSZEGAUBP3E)

A couple of questions:
* Are we updating the direct scheduling calendar as part of this work?
* If so, how do I access that? :)

**Comment by laurenernest** [comment]
@outerpress Let's keep this ticket just for the request calendar. I'll create a separate ticket to align the other calendar(s) if needed.

@jbalboni Are any of the calendar components shared? So if we make changes to the month header and next icon, it'll persist on all the calendars (like direct scheduling)?

**Comment by jbalboni** [comment]
@outerpress Yeah, it's basically the same calendar components for request and direct schedule, just different options when you expand a day.

**Comment by outerpress** [comment]
Thanks @jbalboni and @laurenernest - I added the specs to the body of the ticket.

**Comment by jbalboni** [comment]
@laurenernest These changes should be up on staging now

**Comment by laurenernest** [comment]
@jbalboni Looks good!
