### ISSUE TITLE
Front end applications fail to deploy when Drupal is in maintenance mode

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14116]
## Issue Description
When deploying (or building?) front end applications, if the CMS is in maintenance mode, the application deploy (/build) will fail. The CMS enters maintenance mode once every weekday when it's deployed. I believe this lasts for 10 - 15 minutes. (My memory is very fuzzy on that, though.)

This tight coupling between the two deployments means that application teams cannot deploy during the CMS maintenance window every day (or potentially multiple times a day if the CMS needs to deploy that often).

We briefly discussed this deploy failure in [this Slack thread](https://dsva.slack.com/archives/C0MQ281DJ/p1601062881008700?thread_ts=1601062774.007700&cid=C0MQ281DJ).

**Comment by timwright12** [comment]
This is no longer a problem for application teams, but still within the content-build

**Comment by timwright12** [comment]
This was fixed on another ticket
