### ISSUE TITLE
	CT Redesign: Analytics Investigation	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14127]
- [x] Review current CT stats 
- [x] Document findings 
- [x] Review w UX team; UXBA

**Comment by amyknox** [comment]
CT Dashboard: https://analytics.google.com/analytics/web/#/dashboard/PPUZ37Q0SOi_CiRCBb-HBg/a50123418w177519031p184334251/

VET TEC in CT
https://analytics.google.com/analytics/web/#/dashboard/TT52avPURam05B0aRxyz5g/a50123418w177519031p184334251/_u.date00=20200901&_u.date01=20200930/


![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/eae9a7d1-b290-4713-ac86-42c1e217589c)

Qs 
- When is CT busiest? (time of year, time of day)
- Locations of users - anything worth noting compared to the rest of VA.gov? 
- Top search terms? 
- Highest use of "learn more" elements
- what can we tell about SRP (time on page? 
- Can data for users who select child, national guard/reserves, spouse be separated out to from Veterans (default selection) to compare engagement? 
- Does data show Caution Flags are a deterrent to page views?  For VA are Caution Flags impacting benefits paid to schools?

**Comment by amyknox** [comment]
Bounce rates are generally lower on CT than on other Education pages

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/66537bf5-4c01-4ed9-9f1d-fa2578c85b87)

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/49152def-988c-47e3-8935-7b0c92e013ee)

**Comment by amyknox** [comment]
Busiest months appear to be January, June, July & August

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/1f6344a2-7bfa-4daa-aa1a-be51afb478d5)

**Comment by amyknox** [comment]
[https://app.zenhub.com/files/133843125/7bd32348-ae43-4593-8970-e8760ea5cecd/download](https://app.zenhub.com/files/133843125/7bd32348-ae43-4593-8970-e8760ea5cecd/download)
