### ISSUE TITLE
Verify connectivity between environments and components within VPC

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#14125]
## Background

As part of preparing the Sentry 10 rollout, we should test and verify that all environments and components that need to connect to each other are able to do so.

## Tasks

Verify that traffic is flowing between the following components and Sentry 10 in `vetsgov-utility`

- `vagov-prod` `revproxy`
- `vagov-staging` `revproxy`
- `vagov-dev` `revproxy`

**Comment by jbritt1** [comment]
Why is sentry10 being deployed to vetsgov-utility?

**Comment by omgitsbillryan** [comment]
The original design used a load balancer but the `vagov-utility` VPC did not have enough available IP addresses, so as a compromise (at that time), the sentry 10 EC2 instances and the LB would reside in `vetsgov-utility` instead. A short time after that, we did away with the LB altogether. At that time, we should have realized we no longer needed to be in `vetsgov-utility` but we didn't 🤦 .

[More reading on the design history here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2020-06-02-Sentry10.md#alternatives).

**Comment by omgitsbillryan** [comment]
Seems fair to close this since connectivity is good from:

- `vagov-prod` ---> `vetsgov-utility`
- `vagov-staging` ---> `vetsgov-utility`
- `vagov-dev` ---> `vetsgov-utility`
