### ISSUE TITLE
School Ratings: VET TEC UI Review - B.A./Dev

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14121]
- [x] Review with BA/Dev Lead
- [x] Update prototype as necessary

**Comment by ccruzgra** [comment]
During UXBA sync, we received two items for feedback:

- For the appended provider names, it may not be clear what they are.

- They are neutral about the new display of the preferred provider label with the Yes/No. 

We'll evaluate based on the feedback and many any necessary adjustments.

**Comment by ccruzgra** [comment]
Updated the desktop and mobile UI options. The preferred desktop UI is here: https://bahdigital.invisionapp.com/share/TJIAF1Q8X5K#/screens/296049763

Mobile prototype: https://bahdigital.invisionapp.com/share/WJIAF4LVHEN

@amyknox @JenLJ If the mobile UI also checks out for you, this story can be closed.

**Comment by amyknox** [comment]
@ccruzgra - this is a solid option and definitely makes sense given the desktop layout. 

I'm reflecting on earlier conversations with the Buffalo team about the need to emphasize Preferred Provider status.  Curious to get your thoughts about that info appearing closer to the Provider name & location and wondering about the technical feasibility of implementing that. 

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/66ed9d85-8b46-4211-9cb5-2a2f26a4dbe9)

**Comment by ccruzgra** [comment]
@amyknox This can be closed.
