### ISSUE TITLE
Convert timezones based on device location

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14129]
### User story
As a Veteran, I want any times that are referenced in the 'Need help?' sections to reflect the time zone that I'm currently in. 

### Acceptance Criteria

1. Convert times and timezones so they reflect the location of the user's mobile device. This occurs in the following pages:
     - [Direct deposit](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432050367)
     - [Military service help](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636874)
     - [Claim help](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432345660)

**Comment by bridgethapner** [comment]
Closing - we can keep this simple and use ET for now. If we want to change this later we can open a new ticket.
