### ISSUE TITLE
CT Redesign: VSP Analytics Support

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14128]
- [x] Collect analytics questions from UXBA team  
- [x] Consolidate & share with VSP  
- [ ] Schedule mtg w VSP Analytics team to explore

**Comment by amyknox** [comment]
Submitted analytics request to VSP  https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14646
