### ISSUE TITLE
CT Redesign: Stakeholder Research plan

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14132]
- [x] Draft initial research plan 
- [x] Review w UX Team 
- [x] Update based on feedback

**Comment by ccruzgra** [comment]
PDF of 1995 confirmation print out: [https://app.zenhub.com/files/133843125/04bb1cde-6e7b-4c48-a4d3-b750dbe9246c/download](https://app.zenhub.com/files/133843125/04bb1cde-6e7b-4c48-a4d3-b750dbe9246c/download)

Adding a note to 1995 content doc for accordion to indicate that it should be hidden when printing out: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/1995/content/1995-content-doc-v3.0.md#form-title-update-your-education-benefits-11

**Comment by JenLJ** [comment]
@amyknox Feedback from UXers has been incorporated - closing story
