### ISSUE TITLE
Access for Mike Lumetta

### ISSUE THREAD

**Issue by mjlumetta** [department-of-veterans-affairs/va.gov-team#14139]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Mike Lumetta
- Please Provide your email.
   > mike.lumetta@adhoc.team
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse/VA APIs - Consumer Experience (Okapi)
   > software engineer
   > Ad Hoc

- Requesting SSH key authorization?
   > NO - **already have access**
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

- Grant AWS Console access?
  > YES - **need additional permissions**
  - What AWS services do you need access to and why? 
    - ECR. we have some containers in there, both Codebuild containers and for the developer portal backend. error: "User: arn:aws-us-gov:iam::008577686731:user/Mike.Lumetta is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws-us-gov:ecr:us-gov-west-1:008577686731:repository/*." should probably be okay with read access for now.
    - not sure of the appropriateness of this one, but i get the following error when i try to kick off a failed build with Retry Build in Codebuild: "User: arn:aws-us-gov:iam::008577686731:user/Mike.Lumetta is not authorized to perform: iam:PassRole on resource: arn:aws-us-gov:iam::008577686731:role/service-role/codebuild-service-role." i would like to be able to perform that action, and i can manually kick off new Codebuild jobs. would like to be able to do this if possible.

thank you!

**Comment by mjlumetta** [comment]
requesting additional AWS permissions from @department-of-veterans-affairs/vsp-operations. thank you!!

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Cecilia Lee
Name: Mike Lumetta

**Comment by Jeff-Hayter** [comment]
@tskinn Approve for AWS access.

**Comment by jbritt1** [comment]
Just for transparency / awareness, we are currently working with Mike and the Lighthouse infrastructure team to nail down some improved permissions for the developers and/or privileged users they have. Leaving this one open until we get Mike what he needs here to be unblocked / able to do the tasks he mentioned.

**Comment by jhouse-solvd** [comment]
@jbritt1 - do you know if Mike got the access that he needed. I can no longer find @mjlumetta on this project.

**Comment by jbritt1** [comment]
I think this was attached to some work @jsev-io was working on at the time. I see Mike's activity in AWS as recent as 13 days ago, but he may perhaps be on holiday / PTO currently.

**Comment by jbritt1** [comment]
It does appear it was confirmed though: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14736#issuecomment-729947003

**Comment by jbritt1** [comment]
Spoke with @mjlumetta this morning, he is still seeing:

```
arn:aws-us-gov:iam::008577686731:user/Mike.Lumetta is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws-us-gov:ecr:us-gov-west-1:008577686731:repository/*
```

**Comment by jsev-io** [comment]
@mjlumetta @jbritt1 Taking a look at this, thanks for letting me know.

**Comment by jbritt1** [comment]
This should be resolved at this time.

**Comment by jbritt1** [comment]
Think this one is good to go @jhouse-solvd

**Comment by jhouse-solvd** [comment]
Closing.
