### ISSUE TITLE
Update forms and publications link in the va.gov search page right rail

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14138]
## Update forms and publications link in the va.gov search page right rail

Currently the right rail on site search result pages point to this legacy forms search: 
https://www.index.va.gov/search/va/va_adv_search.jsp?SQ=www.va.gov/vaforms,www.va.gov/vapubs,www.va.gov/vhapublications,www.vba.va.gov/pubs/forms

Point the link to the modern search with updated link text - breaking out to 2 diff links: 
Find a VA form https://www.va.gov/find-forms/ 
VA handbooks and other publications https://www.va.gov/vapubs/

Screenshot: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/da41845c-9c49-425e-b8a6-2196568344c0)

This page is not in Drupal, so will need FE engineering to update. 

FYSA @johnhashva @mnorthuis and for content review @DanielleThierryUSDSVA

**Comment by brianalloyd** [comment]
@kelsonic @ncksllvn can you review and provide an estimate, something we can discuss and factor into Sprint planning during today's grooming session.  cc @MickinSahni

**Comment by ncksllvn** [comment]
Yeah this is easy

**Comment by brianalloyd** [comment]
@ncksllvn @kelsonic I'm going to add this to current sprint as a stretch, worse case scenario we can push to next sprint if time doesn't permit.

**Comment by ncksllvn** [comment]
This one was low-hanging fruit so I grabbed it

**Comment by brianalloyd** [comment]
Perfect.  Thanks @ncksllvn

**Comment by ncksllvn** [comment]
Ah sorry, I have a PR open but it's not merged yet - waiting on review. Should be ready to be closed by EOD though!

**Comment by MarciMcGuireGCIO** [comment]
@ncksllvn , @brianalloyd can you confirm that this issue can be closed?  Thanks!
