### ISSUE TITLE
Validate SLO report using GA

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#14146]
## Issue Description
The VSP backend tools team has been sharing an SLO report weekly. How might we validate that the availability of these systems are accurately portraying when the system is up or down?

---
## Tasks
- [ ] Cross-reference GA data (i.e. Medical Devices/MDT submissions & other VFSs) with down time

## Acceptance Criteria
- [ ] VSP understands whether or not GA data corresponds to the SLO report data

---
@drorva

**Comment by drorva** [comment]
@kfrz for the analytics team to validate the data we're getting in the SLO report it'll be helpful to see when the systems are actually down.
Is there a way to include in the SLO report a graph that shows when the downtime occurs, the way we have graphs for the latency?

**Comment by jonwehausen** [comment]
Thanks team! We will review upon receiving the SLO report. Thanks in advance

**Comment by kfrz** [comment]
![image](https://user-images.githubusercontent.com/11085141/94627461-3b12ef00-0283-11eb-9963-3092658c08db.png)

This is the best I can come up with in an hour, this additional graph indicates at a (4hr) resolution the general availability of the service, it aligns with the dips in the above panel, which doesn't allow for adding time-ranges. 

I'd be interested to know how the data correlates with the Google Analytics data, too - to see how the backend downtime affects the MDT submission project. Going to generate the report with this additional panel, happy to revisit it and tweak it if you have feedback.

**Comment by kfrz** [comment]
[External SLO report here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/external-service-monitoring/historical-reports/2020-09-29-vsp-external-slo-report.pdf) - happy to iterate on this a bit more. 

We may be able to investigate getting data from Google Analytics directly into Grafana to make the correlation easier.

**Comment by joanneesteban** [comment]
@jonwehausen @bmcgrady-ep 

As Keifer noted, we'll need to see if backend downtime correlates with lack of submissions. So, are MDT submissions generally lower during the downtime hours? One of the things we'll need to take into account is if submissions during these times is lower in general. 

Please prioritize any dashboarding or GTM work that needs to go out this sprint. We can pull this into next sprint.

@kfrz thanks for the quick turnaround. So to clarify the 4 hour intervals for each day:
- 00:00 - 03:59
- 04:00 - 07:59
- 08:00 - 11:59
- 12:00 - 13:59
- 14:00 - 17:59
- 16:00 - 19:59
- 20:00 - 23:99
?

From the report, it's a bit unclear which time ranges are missing. But also, let us know if we can just see that more easily on Grafana!

**Comment by bmcgrady-ep** [comment]
@joanneesteban - I'm not seeing any evidence in Google Analytics that the backend downtime is correlating with a lack of submissions. I used this [hourly GA report](https://analytics.google.com/analytics/web/?authuser=0#/my-reports/FyjIisQKQYe4zvpWXZCkUg/a50123418w177519031p176188361/_u.date00=20200916&_u.date01=20200916/) and looked at each day.

**Comment by joanneesteban** [comment]
### Example:

GA - 9/17
![image](https://user-images.githubusercontent.com/48964695/95358765-660acd80-0897-11eb-8ed8-27002dada84d.png)


SLO report shows that there was downtime between 8pm-12am on the 17th, but there were forms submitted during that time.

@drorva

**Comment by drorva** [comment]
@kfrz can we dig into this and see why the discrepancy?

**Comment by drorva** [comment]
@alexpappasoddball can we schedule an investigation of this? 
We'll need @kfrz to collaborate with @bmcgrady-ep or someone else on the Analytics team.

**Comment by alexpappasoddball** [comment]
@drorva Yes, we will get this into the pipeline to look at after we wrap up the sentry work we are currently trying to get across the finish line.

**Comment by joanneesteban** [comment]
@alexpappasoddball any updates with this? We're looking to close out this ticket (I'm assuming the work will be continued with Datadog).

**Comment by drorva** [comment]
I'd like to dig a bit more into this since it looks like it'll take longer to get datadog. @alexpappasoddball can we do a quick single day look at this in sprint 40 and see if we can at least figure out the discrepancy. If it's a simple fix, let's do it, but anything involved can wait.

**Comment by joanneesteban** [comment]
Thanks! We'll put this in our backlog until we hear back.

**Comment by alexpappasoddball** [comment]
Here is the [task](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16613) for BE Tools for sprint 40.  We will update this ticket with findings once completed!

**Comment by kfrz** [comment]
The [breakers board](http://grafana.vfs.va.gov/d/000000022/breakers?orgId=1&from=now-14d&to=now) in Grafana shows general "uptime" of an external service, which may correlate to the Google Analytics data. This metric is calculated over 5m interval, i.e. if the service is down for 5m or more it will show as unavailable. 

![image](https://user-images.githubusercontent.com/11085141/100910951-355ca400-3494-11eb-9be1-bd6e2afaa832.png)


Beyond something like the above-linked board, there's not a great way to correlate this data *directly* - only so far as we already have, leveraging Grafana to visualize outage trends.
