### ISSUE TITLE
Access for Alexander Garcia

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#14147]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Alexander Garcia
- Please Provide your email.
   > agarcia@clarityinnovates.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Identity Team, Front-end Developer, Oddbal

- Requesting SSH key authorization?
   > NO 

- Grant AWS Console access?
  > YES
  Access to debugging information via AWS logs and ability to run adhoc database queries via Rails console, in staging (and/or production on as needed basis).

**Comment by AGarcia-Clarity** [comment]
ping @department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
Name: Alexander Garcia

**Comment by AGarcia-Clarity** [comment]
Any updates @tskinn?

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS.

**Comment by jbritt1** [comment]
Frist time login credentials provided to user.

**Comment by AGarcia-Clarity** [comment]
Requesting updated permissions
Description
I am writing smoke-tests for SSO and need the ability to view, update, run, and write on the CodeBuild tests to ensure MHV smoke-tests are working correctly. Furthermore, I will be integrating reporting features that will be generated each time the smoke-tests are run in CodeBuild.

Repository Link (or Name):
https://github.com/department-of-veterans-affairs/va.gov-sso-smoke-tests

User and/or Team requested:
@AGarcia-Clarity

Special Instructions:
Please ensure that the Alexander Garcia is given Read, Write, Update access so that he can incorporate sso-smoke-tests into CodeBuild to ensure proper functionality and create reporting features for the vsp-identity-team

**Comment by joeniquette** [comment]
@jsev-io or @jbritt1 is there anything else you need from us to get Alex the access he requires?

**Comment by jsev-io** [comment]
> @jsev-io or @jbritt1 is there anything else you need from us to get Alex the access he requires?

Hey Joe, no, I think we have everything we need. I've created a PR with the proposed code changes to allow his access. There was another issue with applying Terraform yesterday so I will apply the changes after we have resolved that.

**Comment by jsev-io** [comment]
Update: 
@jbritt1 @joeniquette 
I've manually created a temporary group with the following policies for @AGarcia-Clarity and Mike Lumetta while we figure out the terraform issues.
![image](https://user-images.githubusercontent.com/63133731/99399292-74470300-28b3-11eb-9ca0-3b397b685af2.png)

**Comment by AGarcia-Clarity** [comment]
> Update:
> @jbritt1 @joeniquette
> I've manually created a temporary group with the following policies for @AGarcia-Clarity and Mike Lumetta while we figure out the terraform issues.
> ![image](https://user-images.githubusercontent.com/63133731/99399292-74470300-28b3-11eb-9ca0-3b397b685af2.png)

Thank you @jsev-io

**Comment by jsev-io** [comment]
Updated policy to include the necessary permissions . Alex reported he could access as expected. Closing this issue
