### ISSUE TITLE
GIDS: "Show GIBCT" button under Latest Preview Version not working 

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#14145]
Steps to reproduce:

1. Navigate to https://staging.va.gov/gids/dashboards
2. Under Latest Preview Version select "Show GIBCT"
3. Page doesn't load 

Expected results: https://staging.va.gov/gi-bill-comparison-tool should load

![Screen Shot 2020-09-28 at 2.45.34 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/60fd6d5a-f876-4140-89a0-06176f30c5e1)
##
![Screen Shot 2020-09-28 at 2.45.44 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/838fb659-c6e4-4a85-8fa1-a1bc91aa0b0f)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14392

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Waiting for verification that this is fixed in Production

**Comment by delli-gatti-michael** [comment]
per @dneel-bah 
"Per Brian Grubb, issue is resolved as of 10/01."

Closing this as resolved
