### ISSUE TITLE
✅   VSA dev intent: Learning center, MVP 1.0 - step_by_step

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#14158]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This issue contains the VSA accessibility feedback for the Learning center, MVP 1.0 - step_by_step.

#### Desktop

![Screen Shot 2020-09-28 at 6 35 02 PM](https://user-images.githubusercontent.com/57469/94492907-574a5980-01b9-11eb-8ec3-260171e6fc08.png)

#### Mobile

**mobile views of step by step template**

![VA-LCT-Step-by-Step-Images-mobile expanded](https://user-images.githubusercontent.com/55992116/94591454-1bb19d00-0256-11eb-8346-957d9a9f1c75.png)
![Uploading VA-LCT-Step-by-Step-Images-mobile.png…]()

![Screen Shot 2020-09-29 at 9 39 41 AM](https://user-images.githubusercontent.com/57469/94565873-bc449480-0237-11eb-8d49-186d4804c93f.png)

https://preview.uxpin.com/192f5be770c74272f782765a19a196aed0a4a588#/pages/132512748/documentation/no-panels?mode=i

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by andaleliz** [comment]
![VA-LCT-Step-by-Step-Images-mobile expanded](https://user-images.githubusercontent.com/55992116/94591454-1bb19d00-0256-11eb-8346-957d9a9f1c75.png)
![Uploading VA-LCT-Step-by-Step-Images-mobile.png…]()
mobile views of step by step template

**Comment by jenstrickland** [comment]
For the expand/collapse, I believe it would use the AdditionalInfo component, which communicates the expanded and collapsed states to assistive tech. The Gov.UK pattern this originated from may be helpful if there are any questions during implementation: https://www.gov.uk/apply-online-for-student-finance

Accessibility feedback for this complete. Let me know, of course 😄 if anything isn't clear or overlooked, and feel free to tag me on the PR as a reviewer.

**Comment by laflannery** [comment]
Only specific feedback is indicating which component to use, any updates to the component would not be PW.  Closing
