### ISSUE TITLE
Account for Cerner-only offboarding on new facility selection page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14150]
With the latest updates to the facility selection page, we need to account for Cerner-only patients that have access to new facility selection experience.

## Acceptance criteria: 
- Cerner-only patients can start scheduling flow
- If Cerner-only patient is community care eligible patient can select cc option and continue with CC flow
- If patient selects VA provider, patient taken to _**flat list**_ location page where Cerner-only site displays but cannot be selected. 
    - Instead they must select link provided with site (see below) or click button 'Go to My VA Health'
- If Cerner-only patient not CC eligible, they are taken to location selection page where Cerner-only site displays but cannot be selected. Instead they must select link or click button 'Go to My VA Health'
    - Copy beside site name/location should say - "To schedule a VA appointment at this location, go to My VA Health"
- 'Continue' button needs to be updated to 'Go to My VA Health'

**Comment by lenaecb** [comment]
Questions:
- for the Cerner site - what's happening in MAS for Cerner sites?

**Comment by lenaecb** [comment]
De-prioritizing - based on PI planning and Q4 objectives, we are going to continue to use existing v1 of VA facility selection page for Cerner offboarding. Will reevaluate for next PI 2021.

**Comment by laurenernest** [comment]
covered in #25482
