### ISSUE TITLE
✅   VSA dev intent: Learning center, MVP 1.0 - Q & A

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#14159]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This issue contains the VSA accessibility feedback for the Learning center, MVP 1.0 - Q & A.

#### Desktop

![Screen Shot 2020-09-28 at 6 35 29 PM](https://user-images.githubusercontent.com/57469/94492944-6d581a00-01b9-11eb-82e9-d906925f02d7.png)

#### Mobile

_Not provided_

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by jenstrickland** [comment]
This page is straightforward, and I don't think anything special needs to be documented.

Accessibility feedback for this complete. Let me know, of course 😄 if anything isn't clear or overlooked, and feel free to tag me on the PR as a reviewer.

**Comment by laflannery** [comment]
There is no feedback in this issue, closing
