### ISSUE TITLE
Profile service integration

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va.gov-team#14155]
### User Story/ Task

Integrating with the profile endpoint. This is a backend task  - the associated UI is included in different stories. Incorporates all services that exist within Profile, including Military information

### Acceptance Criteria

1. Profile data loads in pages that display profile information (most stories within the Profile epic)

### Dev checklist

- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
- Can mock out until BE service work is complete (if we're confident what the API contract looks like)

**Comment by bessgreen** [comment]
update: First API call that's been made is for User name/mailing address/DOB. need to ID gaps.

**Comment by digitalken** [comment]
Testing: 

1. Verify profile information is loaded into pages under the Profile group.

**Comment by digitalken** [comment]
Added to TestRails.

**Comment by bessgreen** [comment]
11/19 update: ticket is blocked - Profile service is down. Moving this ticket to the backlog.

**Comment by esther-k** [comment]
**11/24**

Pass on iOS and Android. Moving to Design QA
