### ISSUE TITLE
Alert when no facility available in new facility selection list

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14152]
When Veteran does not get a list of facilities returned on new facility selection page, we need to display an alert directing the Veteran to use the facility locator to contact their Facility or to pick a different type of care. 

Given changes to this page, if the user is registered to more than one site, we will not know which site they intend to schedule at, so we cannot populate the contact details. In that case we should redirect them to facility locator. (This error relates to [this epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12951))

## Acceptance criteria:
- Veteran is informed a VA supported facility was not found for the care type they have selected
- Veteran can:
    1. Go back to type of care page and select a different type of care
    2. Or contact their VA facility (using the Facility Locator) and call to schedule their appointment. 
- we cannot display the facility address or phone number to veteran in this use case
- alert should display on page
 

### Current alert:
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/a7c7578b-414a-4655-8d77-d95be85bd194)

**Comment by peggygannon** [comment]
@lenaecb quick followup: is the message that there is no VA facility that offers this type of care or no VA facility that offers *online scheduling* for this type of care?

**Comment by lenaecb** [comment]
@peggygannon - Of the facilities that the veteran is registered at, none of them support of them have online scheduling turned on for the type of care supported. 

I wouldn't say there are 'no' VA facilities, just no VA facilities that this Veteran is registered at? Maybe doesn't make a difference. I think the key things we want to convey are:
- you can't book online for this care type because none of your facilities support online booking for that care type
- you should call your facility (but we can't show you anymore the data to support calling your intended facility like we once could)

Does that help?

**Comment by peggygannon** [comment]
Hi @lenaecb yes, thank you for the additional clarification. Here's the recommended message: 

**We can't find a registered VA facility for this {type of care} appointment**
We're sorry. None of the VA facilities where you’re registered offers online appointments for this type of care. Please call your local VA medical center to schedule this appointment. Find a VA location(https://www.va.gov/find-locations/)
To request another online appointment, please go back and choose a different type of care.

**Comment by lenaecb** [comment]
hey @peggygannon - I think the header may still be a bit misleading. Right now it can kinda seem like no facility is offering appointments for that type of care. Where really, it's that no facility that the user is registered to is offering online booking for that type of care (and maybe others). I also don't think veterans have a clear sense of what 'registered' means in this sense. 

So, perhaps something like "**We can't find a VA facility where you receive care that allows online appointments for this {type of care}**"

We just really want them to know that:
- online appt not supported for their facilities where they receive care
- but they can still make an appt for that care type, they just have to call

**Comment by peggygannon** [comment]
OK, thanks, I'm am trying to keep that header relatively short. will drop in another option shortly.

**Comment by lenaecb** [comment]
Thanks @peggygannon - I agree it seems long, but also it does clearly state what happens? I think we roll with it.

**Comment by peggygannon** [comment]
yes, i agree.
