### ISSUE TITLE
✅  VSA dev intent: Learning center, MVP 1.0 - About page

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#14157]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This issue contains the VSA accessibility feedback for the Learning center, MVP 1.0 - About page

#### Desktop

![Screen Shot 2020-09-28 at 6 24 30 PM](https://user-images.githubusercontent.com/57469/94492356-20277880-01b8-11eb-8352-6940bf0c1f51.png)

#### Mobile

For details, see https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/status-and-decisions.md#090120

* About - text only: not needed - just text 

* About - text w/ on this page, loooong content: needed, to explore use case of very long content (also, define very long). See [#13038](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13038)

* About - tables: needed, see [#11499](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11499). Check w/ eBenefits team's responsive table for View Payments

**mobile view of this template w/ a table, first cell in open state**

![table-complex 1, open](https://user-images.githubusercontent.com/55992116/94591387-06d50980-0256-11eb-9450-026db684b182.png)

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by andaleliz** [comment]
![table-complex 1, open](https://user-images.githubusercontent.com/55992116/94591387-06d50980-0256-11eb-9450-026db684b182.png)
mobile view of this template w/ a table, first cell in open state

**Comment by jenstrickland** [comment]
For the search form, please use a form element with the legend as the heading; **why** since this search is placed above the h1 this will not interfere with the heading order.

**Comment by jenstrickland** [comment]
Semantic markup for table: https://codepen.io/jenstrickland/pen/MWyPmRW

```
        <table data-template="paragraphs/table" data-entity-id="7237" class="va-table rwd" role="table">

            <caption>
              <h3>SMC&nbsp;rate payment variations</h3>
                <button aria-expanded="false" class="gem-c-step-nav__button gem-c-step-nav__button--controls js-step-controls-button" aria-controls="step-panel-check-if-you-re-eligible-1">Show all</button>
            </caption>
    
                <thead>
                    <tr role="row">
                        <th scope="col" role="columnheader">SMC letter designation</th>
                        <th scope="col" role="columnheader">Monthly payment (in&nbsp;U.S.&nbsp;$)</th>
                        <th scope="col" role="columnheader">How this payment variation works</th>
                    </tr>
                </thead>
                <tbody>
                    <tr role="row">
                        <td role="cell">
                          <dfn>SMC letter designation</dfn>
                          <span>SMC-K</span>
                          <button>Hide all</button>
                          </td>
                        <td hidden role="cell"><dfn>Monthly payment (in&nbsp;U.S.&nbsp;$)</dfn><span>110.31</span></td>
                        <td hidden role="cell"><dfn>How this payment variation works</dfn><span>If you qualify for SMC-K, we add this rate to your basic disability compensation rate for any disability rating from 0% to 100%. We also add this rate to all SMC basic rates except SMC-O, SMC-Q, and SMC-R. You may receive 1 to 3 SMC-K awards in addition to basic and SMC rates.</span></td>
                    </tr>
                    <tr role="row">
                        <td role="cell"><dfn>SMC letter designation</dfn><span>SMC-Q</span></td>
                        <td role="cell"><dfn>Monthly payment (in&nbsp;U.S.&nbsp;$)</dfn><span>67.00</span></td>
                        <td role="cell"><dfn>How this payment variation works</dfn><span>This is a protected rate that we haven’t awarded since August 19, 1968. If we awarded you an SMC-Q designation, we pay this rate in place of your basic disability compensation rate.</span></td>
                    </tr>
                </tbody>
                <tfoot>
                  <tr role="row">
                    <td colspan="<!-- number of columns -->" role="cell">If there is content that pairs with the table such as a footnote or a paragraph, it could be included here, so that screen reader users navigating via the table rotor will have access to all of the information of the table in one mode. </td>
                  </tr>
                </tfoot>                   
            </table>
```

**Comment by jenstrickland** [comment]
For the expand/collapse, I believe it would use the AdditionalInfo component, and the Gov.UK pattern this originated from may be helpful if there are any questions during implementation: https://www.gov.uk/apply-online-for-student-finance

**Comment by jenstrickland** [comment]
Accessibility feedback for this complete. Let me know, of course 😄  if anything isn't clear or overlooked, and feel free to tag me on the PR as a reviewer.

**Comment by laflannery** [comment]
Closing, the feedback has been covered separately in more recent issues
