### ISSUE TITLE
In-app web view: Find a VA location, Coronavirus FAQs

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14163]
### User story
As a user, I want a VA facility finder that's accessible from the mobile app, as well as a Coronavirus FAQ page. 

### Acceptance Criteria

1. Selecting Find a VA location from the home page routes to an in-app web view of the [VA location/facility locator](https://www.va.gov/find-locations/) page
2. Selecting Coronavirus FAQs from the home page routes to an in-app web view of the [Coronavirus FAQs](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) page

### Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432493111
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432493468

### Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Testing:

- [ ] 1. Verify that selecting the "Find a VA Location" button from the home page opens https://www.va.gov/find-locations/ in a web view within the app.
- [ ] 2. Verify screen reader reads the page without issues.
- [ ] 3. Verify Deque or similar tool finds no issues on the displayed page.
- [ ] 4. Verify user is able to use form to find a VA facility through the app.
- [ ] 5. Verify assistive functionality operates on Find VA Locations page through app.
- [ ] 6. Verify that selecting the "Coronavirus FAQs" button from the home page opens https://www.va.gov/coronavirus-veteran-frequently-asked-questions/
- [ ] 7. Verify screen reader reads the page without issues.
- [ ] 8. Verify Deque or similar tool finds no issues on the displayed page.
- [ ] 9. Verify user is able to navigate the page within web view on the app.

**Comment by digitalken** [comment]
Issue(s):
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14997

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Pass 11/11/2020 in TestRail on both iOS and Android.  Moving to Design QA.
