### ISSUE TITLE
✅   VSA dev intent: Learning center, MVP 1.0 - faq_multiple_q_a

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#14160]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

This issue contains the VSA accessibility feedback for the Learning center, MVP 1.0 - faq_multiple_q_a.

#### Desktop

![Screen Shot 2020-09-28 at 6 36 24 PM](https://user-images.githubusercontent.com/57469/94492993-88c32500-01b9-11eb-88b3-1f846b601dfa.png)

#### Mobile

_Not provided_

## Point of Contact

**VFS Point of Contact:** Jennifer

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by jenstrickland** [comment]
The alertbox heading **should** be an H2 with the utility class styling for an H3. This is a CMS issue, previously documented: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6375

This is due to the CMS implementing the [VA design system alertbox component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/) as-is. For React apps, there is a `level` prop that takes numeric values. For the alertbox to be implemented in the CMS, it needs to be a static implementation that will work no matter where the alertbox is placed on a page. The heading **should** be coded as:

```
  <h2 class="vads-u-font-size--h3">Alertbox heading</h2>
```


![Screen Shot 2020-10-01 at 7 14 52 PM](https://user-images.githubusercontent.com/57469/94872529-d5596b00-041a-11eb-8ed0-cb6cc18ffb50.png)

**Comment by jenstrickland** [comment]
For this multiple Q & A design, **consider** associating the H2 question with the related list of answers.

```
  <h2 id="agent-orange-presumptive-disea">Agent Orange presumptive diseases</h2>
  <div class="usa-accordion-bordered">
    <ul class="usa-unstyled-list" aria-labelledby="agent-orange-presumptive-disea">
      <li>First answer</li>
      <!-- etcetera --
    </ul>
  </div>
```

![Screen Shot 2020-10-01 at 7 16 25 PM](https://user-images.githubusercontent.com/57469/94873082-3afa2700-041c-11eb-84d4-7da92c1ef3da.png)


**Guidance**

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

**Comment by jenstrickland** [comment]
Accessibility feedback for this complete. Let me know, of course 😄 if anything isn't clear or overlooked, and feel free to tag me on the PR as a reviewer.

**Comment by laflannery** [comment]
Closing - the alerts and accordions have been discussed in more recent issues
