### ISSUE TITLE
Direct Deposit service integration

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va.gov-team#14161]
### User Story/ Task

Integrating with bank account service to retrieve and send up direct deposit account information 

Note: Need to investigate further. Is there any additional protocol here since it's financial information? Is there any validation on the backend? What does a "failed state" look like if there's an error? 

### Acceptance Criteria
1. Direct Deposit view page should display account details if they exist
     - Currently: pulling mock data. Update the endpoint to hit the Direct Deposit service.
2. If a user edits their direct deposit information, the changes should be saved and sent back up

### Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Hi @kreek, are you able to share any insights of how the account validation works on the backend? This might be easier to discuss over a call, but wanted to give you a heads up in the meantime! 

cc: @bridgethapner

**Comment by kreek** [comment]
@bessgreen PPIU is the service that updates the bank account information, its validation rules are here: https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/ppiu/payment_account.rb#L32-L37

Happy to go over it in a meeting as well if that need clarification :)

**Comment by jjulian** [comment]
(translation from ruby code to English)
Account type must be "checking" or "savings"
Routing number must be present and match the proper format.
Account number must be present and match the proper format.

**Comment by kreek** [comment]
Also should note that we use the [olive branch gem](https://github.com/vigetlabs/olive_branch) so when working in react native/JSON you can continue to use camelCase variables and not snake_case like ruby. So the app will send `financialInstitutionRoutingNumber` rather than `financial_institution_routing_number` to the API.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
12/17/2020 - I'm not seeing direct deposit saved right now so I'm thinking that something isn't quite ready.  I also understand that something else is in the works. Need to test this later.

**Comment by digitalken** [comment]
PASS 1/13/2021 - Both Android and iOS saved.  Moving to Design QA.
