### ISSUE TITLE
Catalogue known table authoring experience issues

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-team#14171]
## Status
**[2024-04-24]** Asked Laura to review for viability.

The goal is to document all known issues with table editing in the CMS.

## CMS Acceptance Criteria

- [x] known issues with table creation/editing are documented
- [x] documented issues are triaged and moved to backlog w/ detailed descriptions
- [x] most critical issues/bugs are prioritized

## PW Acceptance Criteria - tbd
- lorem

### PW Tasks - tbd
- [ ] lorem

**Comment by MickinSahni** [comment]
I guess that worked. It's now in `va.gov-team` for us to consider.

**Comment by FranECross** [comment]
@laflannery Will you please (no rush) review this to see if the changes are still needed? Thanks!

**Comment by laflannery** [comment]
Tables are all using DS components now so none of these issues are applicable

**Comment by FranECross** [comment]
Closing as not needed per Laura's note above.
