### ISSUE TITLE
Tier 2 Content Audit for Legacy Pages 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1418]
## Goal
Audit of Tier 2 benefit-related content on the legacy (old TeamSite design) pages.

## Examples
heath conditions, wellness content, other knowledge/support/learning/resources content
Could be for beneficiaries or non-beneficiaries like VSOs, school administrators,counselors.
URL, page name, brief page summary, primary audience, secondary/other audiences 

## Acceptance Criteria
Audit Documentation Includes:
- [ ]  URL 
- [ ] page name
- [ ] brief page summary
- [ ] primary audience, secondary / other audiences
- [ ] related benefit

## How to configure this issue
- [x] **Attached to a Milestone** 
- [x] **Attached to an Epic** 
- [x] **Labeled with Practice Area** `research`, `ia`, `research`, `content`
- [x] **Labeled with Type** `discovery`, `documentation`

**Comment by jenniferlee-dsva** [comment]
@Karak888 and @lwalsh617 - added one more info audit should include:  "related benefit" (please use the benefit categories of our hubs - they're all listed on the second panel of our homepage or the flyout mega menu nav)

**Comment by Karak888** [comment]
@laura if you need any guidance on finding anything just let me know and happy to help. Thanks @jenniferlee-dsva !

**Comment by lwalsh617** [comment]
Super! Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lwalsh617** [comment]
Adding some notes per today's content call. Priority areas are as follows:
- Disability
- Education
- Voc Rehab, aka Careers & Employment
After these three area are done, we'll move on to:
- Housing
- Pension
- Life Insurance

**Comment by Karak888** [comment]
@Karak888  can we create a checklist on this ticket so that it stays together, @lwalsh617 will work with Kara on tickets.

**Comment by lwalsh617** [comment]
Here is the tier 2 content audit for Disability, VR&E, Housing, Pension, & Life Insurance. All that's missing is education which is coming from Lunascoop (Thanks for that!)

[va.gov-tier2contentaudit-v1-092519.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3653232/va.gov-tier2contentaudit-v1-092519.xlsx)

**Comment by lunascoop** [comment]
Here is an updated version with education included.

[va.gov-tier2contentaudit-v1-092519.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3654108/va.gov-tier2contentaudit-v1-092519.xlsx)

**Comment by lwalsh617** [comment]
Quick note: I included content like factsheets in videos in tier 2, though, strictly speaking they address tier 1 issues around accessing/managing benefits. My rationale is that much of the same info is available on tier 1 pages. So, for example, while I don't think we'd want a factsheet to compete with the tier 1 content on a webpage, it's valuable for the user who prefers to download a "factsheet" rather than bookmark a web page. Make sense?

**Comment by jenniferlee-dsva** [comment]
@lwalsh617  and @lunascoop Thank you! Looking...
