### ISSUE TITLE
Logging sources inventory documentation to inform implementation plan 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#14186]
## Issue Description
Create inventory spreadsheet which identifies all logging data sources that are currently implemented, supported, or maintained by the operations team on VSP 
---
## Tasks
Create a living document which informs the operations team and can be used to assist in implementing Loki logging solution in production

## Acceptance Criteria
All core services should be identified along basic info: 
- services
- apps
- log group name 
- amazon resource name 
- environments 
- priority 
- tags 
- status

WIP: https://docs.google.com/spreadsheets/d/1LMmK6hV0uTqApgh-rMGRMzf0QJ5XjA5FZVAMUVgNlsE/edit#gid=82168139

**Comment by pnwstevan** [comment]
I think this is pretty much complete.  Here are a few notes/comments:

- Please add 'status' to the AC, since that's an important element I added.
- The basic inventory and status is complete, along with what's currently logged in CloudWatch
- Updating this will be an ongoing effort/chore

**Comment by jhouse-solvd** [comment]
@pnwstevan thanks for the update! status added to AC. let me know if you need any other changes. Looking forward to discussing early next week. 

Great work!
