### ISSUE TITLE
Analytics Implementation or QA Support for View Payments

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14181]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytic event names

- Who is this request for?
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    - Jason Wolf - #vsa-ebenefits

    
- What team/project is this work for?
    _this adds context for the data_
    - eBenefits Team - View my VA payment history ([product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-payment-history))
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    - No PII
    - https://staging.va.gov/va-payment-history/payments/

- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    - October 2020

- Typical Website Interactions to Track
    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    - There is only the one url: https://staging.va.gov/va-payment-history/payments/
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    - Pagination, (help links and breadcrumbs probably don't need anything)

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - User +271 shows both payments and returned payments

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - User +271 shows both payments and returned payments

- Certain conditions/responses that need to be reviewed
    - None

- Additional Comments
    - This is a single page, simple View task that is pulling data from BGS into tables

<details>  

<summary>Screenshot</summary>  

![View my VA Payment history](https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/teams/vsa/teams/ebenefits/features/view-payment-history/images/View-Payments-Veterans-Affairs-cropped.png)

</details>  

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @jason-gcio ! Confirming receipt.

**Comment by jonwehausen** [comment]
@jason-gcio 

Thank you for your patience on this request -- started off taking a read thru your product outline to review your KPIs (_understanding some are still TBD it looks like, and that's certainly fine_): 

# KPI Read-thru
----------------
> **% of View Payment History traffic (EBN / VA.gov)**
> **Time to view My Payment History**

## KPI 1: % of View Payment History traffic (EBN / VA.gov) 
We will certainly of course be able to report on this from GA relatively easily at a high level...A consideration to think about here is if our goals are mostly tailored towards overall volume of traffic or if there are other traffic segmentation points that may be of interest in assessing the old page vs this one (i.e mobile vs desktop, where traffic is coming from, etc etc). 

## KPI 2: Time to view my payment history - Reduce to under 30 seconds
This one we are now capable of reporting on much more precisely and with minimal custom development work through BigQuery. Per our last view payments work, we have an existing event that fires when view payments has successfully completed load.

![image](https://user-images.githubusercontent.com/48527022/95335029-dfe18d80-087c-11eb-8e67-66a3379f8e6c.png)
 
Leveraging that event, we can now construct a query to determine the difference in seconds between page load and view payment history load completion to determine an average time to view payments. 

_Another small influence to think about here is - Is there any reasonable potential point where the volume of payments loaded back to the user can heavily impact the time to view payments? Would that information be helpful as context in identifying potential outliers? If so, we would want to surface a variable for this information and would require a small config change_

-----------
# Behavioral Interactions

## Pagination
- You also mentioned in the issue template pagination behavior may also be of interest -- we now have that tracked at a global level across the site 😄 , so no further changes necessary there and we have that data currently available . 

## Breadcrumb
- As we work towards global standardization of the datalayer for design system components -- breadcrumb interactions should be tracked and while it does looks like the the page is currently missing tracking on breadcrumbs, as one of our efforts for this quarter we are going to be working with the new design system team to implement holistically so we don't want to have your developers spend time here if not overly important for your insights. 

## Help links
- Yes you're correct in that these don't need dedicated tracking, we can ultimately leverage previous page paths and telephone link click events to report on those if interested. 

Other than the few items to consider here -- there aren't any additional configuration changes needed to fulfill those KPIs for October launch TBD and we could certainly work to surface them within a dashboard if interested, at which point we would ask to submit a KPI dashboard request. 

cc: @bsmartin-ep @bmcgrady-ep @joanneesteban for visibility

**Comment by jonwehausen** [comment]
Per Jason and I's slack conversation -- confirming no other changes necessary at this time awaiting confirmation from Steve following return from PTO.

**Comment by joanneesteban** [comment]
Taking @bsmartin-ep @bmcgrady-ep off this ticket.

**Comment by jonwehausen** [comment]
Closing this ticket. Implementation complete, remaining work on KPI dashboard ticket #14537
