### ISSUE TITLE
Iteration (v2) of VAOS KPI Dashboard(s)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14192]
# Request a KPI Dashboard ITERATION

# Requesting an iteration on existing dashboard:
- [see full list of data review needs + changes for the dashboard here](https://docs.google.com/document/d/1Q4MGw5QpNotuCyq4zZOp5kigsnomMCbs5L7F_PV-DwA/edit#)
- overview of ask:
    - need to update the objectives to 3 main objectives we are tracking
    - requesting we add a 'product performance' section to track other data points important for product evaluation
    - provide some feedback on current data discrepancies
    - provided some additional 'common questions' I need to answer for VAOS
    - provided future version of dashboard that would hold 'sub dashboard' specific to individual flows and/or a monthly report that could hold those views

### I provided a lot of thoughts in that doc so recommendation on prioritization of feedback/changes:
- Take each objective and iterate/update & sync with VAOS PM for feedback/alignment

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team

**Comment by bsmartin-ep** [comment]
Thanks @lenaecb.  I will look at this ASAP.

**Comment by lenaecb** [comment]
Cool, let me know if you'd like to meet and chat about my recommendations/feedback in that doc. I am still noticing in the BQ version of the Domo dashboard that we're still not getting same # for conversion % specifically.

**Comment by lenaecb** [comment]
@jonwehausen @bsmartin-ep - would it be worth setting up sometime to talk through current, in progress v2 of the Domo dashboard? I have a few questions/suggestions, but I think it may take some conversation.

My goal soon is to use DOMO as our source of truth for most high level app analytics we need, but right now there are a few things that we could clarify to make that possible.

**Comment by amycesal** [comment]
better funnel viz 
<img width="707" alt="Screen Shot 2020-11-18 at 5 05 17 PM" src="https://user-images.githubusercontent.com/1656046/99599108-4a2f3700-29c0-11eb-9b01-8bebe7c28565.png">

**Comment by joanneesteban** [comment]
@amycesal would you be able to help visualize this before you leave? Let us know!

**Comment by bsmartin-ep** [comment]
Hi @laurenernest  -

Thanks again for meeting about these dashboards on Monday.

If you are taking the lead on this from Lenae, I'll need you to review the updated dashboards.

Lenae's changes:  https://docs.google.com/document/d/1Q4MGw5QpNotuCyq4zZOp5kigsnomMCbs5L7F_PV-DwA/edit#

### **DOMO dashboards:**

> Main - https://va-gov.domo.com/page/1769944412
> Performance - https://va-gov.domo.com/page/1315231862
> Funnels - https://va-gov.domo.com/page/443732151
> Funnels (AB test) - https://va-gov.domo.com/page/1087403783

### **Things to consider (some we already discussed):**

- Do all card titles include the metric type and date grouping when applicable?
- Are our headers / subheaders still accurate with the new changes?  Anything we need to add to titles / KPI descriptions?
- Is each card summary helpful or should it be removed?  Any labeling that would help?
- How do want to handle weekly line graphs that show a precipitous drop in incomplete weeks?  Do we only show complete weeks?  What do you think about enabling projection?

Now|With Projection
---|---
![image](https://user-images.githubusercontent.com/62304138/101029154-f76c8800-3546-11eb-9025-665965be35bd.png)|![image](https://user-images.githubusercontent.com/62304138/101029730-21be4580-3547-11eb-84f3-6ec1af9e7f7a.png)

- Most of our cards are just SUMs or AVG of metrics.  If something is more complex, let me know if you want a quick description of the calculation below the card.  Example:

![image](https://user-images.githubusercontent.com/62304138/101032079-c9d40e80-3547-11eb-814c-b6580e05c7bd.png)

###  **Funnels**

- I re-added the VA Request funnel (with a date column) to the [Funnels all](https://va-gov.domo.com/page/443732151) page at Lenae's request.
- :point_right::point_right::point_right: We still need events and page URLs for the steps for CC, Direct, and any other VAOS types / flows.  Update [those in this spreadsheet](https://docs.google.com/spreadsheets/d/1ohLOujFHOqHhBZww57Qj06qIAcJOiDjK9KnjXRvZnf4/edit?usp=sharing).


(cc @JasonTheBearded)

**Comment by laurenernest** [comment]
I added a section called "Lauren's Notes" in the original GDoc.

-----
> Do all card titles include the metric type and date grouping when applicable?

Looks good

-----
> Are our headers / subheaders still accurate with the new changes? Anything we need to add to titles / KPI descriptions?

Notes are in the doc. I still want to look more into the KPI descriptions, but good for now.

-----
> Is each card summary helpful or should it be removed? Any labeling that would help?

Helpful for me! Please keep.

> How do want to handle weekly line graphs that show a precipitous drop in incomplete weeks? Do we only show complete weeks? 

I like the update to complete weeks 👍

-----
> What do you think about enabling projection?

Let's enable where it can be. I'll see how often I refer to it.

-----
> Most of our cards are just SUMs or AVG of metrics. If something is more complex, let me know if you want a quick description of the calculation below the card.

Including the calculations would be helpful for me.

**Comment by bsmartin-ep** [comment]
Looks good @laurenernest.  I'll get started on these updates today.

**Comment by bsmartin-ep** [comment]
@laurenernest -

These dashboards should be ready for your review (and a :30 Zoom if you want to run through them).

> Completion rate - Change default graph views to weekly, and keep the delta from the last 7 days widget
> Completion rate - Add monthly view with monthly delta
> For scheduling completion, is it possible to also show the totals in addition to the percentages? It doesn’t have to be in the default view.

Now we have 4 charts:

1. Completion rate **by event** by day grouped by month (overlay total successful submission events).
2. Completion rate **by event** by day grouped by week (overlay total successful submission events).
3. Completion rate **by user** by day grouped by month (overlay total users with successful submission events).
4. Completion rate **by user** by day grouped by week (overlay total users with successful submission events).

We have a lot of [available chart types in DOMO](https://knowledge.domo.com/Welcome/Available_Chart_Types) if this looked different in your head.

> Add last 7 days delta to the other graphs 

I added a few of these.  Any other cards would think have a _last n days_ delta?

> Since the weeks are captured Sunday-Saturday, weekly data marked as Dec 20 would be representative of the total from 12/13-12/19?

For week (and month) grouping, DOMO displays the day at the START OF the period. So the period in this case would be 12/20 - 12/26.

> Change Objective 4 header to a theme like User Retention or something
> ...etc...

Took at shot at these!  Let me know what you think.

> Funnels - https://va-gov.domo.com/page/443732151
> Good to set up the Community Care funnel with the steps here  https://docs.google.com/spreadsheets/d/1ohLOujFHOqHhBZww57Qj06qIAcJOiDjK9KnjXRvZnf4/edit#gid=894312614

I ran into an issue when I set up the Community Care funnel.  With these closed funnels, we need to start the funnel at the **first step unique to the VAOS flow**.  Because CC and Request share the initial `-button-clicked` event - and most of them apply to Request - it was showing an extremely inaccurate step conversion rate for CC.

To fix this, I chopped off the first 2 event on each funnel.  Does this make sense? 

We can keep the initial `-button-clicked` event in the conversion rate line graphs though since we look for ANY VAOS flow successful completion rate as that denominator.  But if we want to focus on individual flows, we need to start with the first **unique** step.

> Funnels (AB test) - https://va-gov.domo.com/page/1087403783
> Can we archive this AB test and create a new funnel comparison for V1 and V2, starting from January 

I'm not sure I'm familiar with the MVT that started in January.  Is this the flattened facility selector or something else?

**Comment by laurenernest** [comment]
@bsmartin-ep The updates look great! Thanks for running through those with me. Only a couple of header items (marked under my google doc notes in red/yellow) then we should be good to go!

**Comment by bsmartin-ep** [comment]
Changes have been made @laurenernest.  OK to close this?

**Comment by laurenernest** [comment]
Thanks! Closing ticket.
