### ISSUE TITLE
Image src mismatch inside header liquid template

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#14191]
## Issue Description
The image's `src` doesn't match the GraphQL build HTML. This is the same in all transformers.

The [header.htm](  <script type="text/javascript">)l template file populates `headerFooterData` which contains the information displayed
```
  <script type="text/javascript">
    window.VetsGov = window.VetsGov || {};
    window.VetsGov.headerFooter = {{ headerFooterData }};
  </script>
```

## Example:
![Screen Shot 2020-09-29 at 3.57.03 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/dcd03493-54c2-4f69-888a-5b4486092af4)

## Example File
`/pittsburgh-health-care/events/index.html`

## Tasks
- [ ] Figure out why the `src` field is wrong.
- [ ] Resolve issue, and verify the output matches the GraphQL content build.

**Comment by swirtSJW** [comment]
Similar data is coming from 
`file.e638fd17-9090-442b-a724-5113133b4d0f.json`

![image](https://user-images.githubusercontent.com/5752113/94620250-51697c80-027c-11eb-8cf2-deab78519b99.png)


I think the transformer is incorrectly referencing `uri -> value` rather than `uri -> url`

**Comment by jhonnyoddball** [comment]
## Tracing:
- `headerFooterData` is expected in the 'header.html' template
- This is populated in the `createHeaderFooterData` function [here](https://github.com/department-of-veterans-affairs/vets-website/blob/69cb9387b87f1141368f1768f5993f44e16722b1/src/site/stages/build/plugins/create-header-footer.js#L42)
- The incorrect image link is generated [here](https://github.com/department-of-veterans-affairs/vets-website/blob/69cb9387b87f1141368f1768f5993f44e16722b1/src/site/stages/build/drupal/menus.js#L152)

## Solution
Fix the url using the correct path and image style based on the GraphQL query

**Comment by jhonnyoddball** [comment]
Fixed!
