### ISSUE TITLE
IA Request: Move application wizards

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#14193]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

Requesting team: Public websites @johnhashva, @andaleliz 

## Required Inputs:
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/README.md)
- [Mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31)
- Link to or attach final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.
**SEO Keywords** - Provide a list of keywords used by your target audience when they talk about or search for your content
**Proposed site map/page structure** - Provide link or image of proposed page structure (if more than one page)
**Suggested URL(s)** - Provide suggested URLs and any background or rationale
**Suggested entry points** - What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.
**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [ ] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
List of current entry points to applications across Disability, Education, Careers and Employment and Decision Reviews:
https://docs.google.com/spreadsheets/d/1HvjCZ86EX4truevyUUbk-WdN-0A_5fcamRZV3GnmLq4/edit?usp=sharing

**Comment by mnorthuis** [comment]
@johnhashva @andaleliz @peggygannon 
Draft IA for review is posted here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md

Will need to work through individual entry points for each effort.

**Comment by andaleliz** [comment]
@mnorthuis first, you are amazing. This is great work, thank you for being so thorough.

Everything looks good and lines up with what we've discussed, from my perspective. I have a questions about this step of the flow, the `start over` option
![Screen Shot 2020-10-02 at 1 29 50 PM](https://user-images.githubusercontent.com/55992116/94953749-0dfa5280-04b6-11eb-8e7d-2fcf8a174705.png)
I understand this step to be the stage where the user is seeing the wizard outcome, but _hasn't_ clicked on it yet. If that's the case, I see the `start over` option as reanswering the wizard questions since they're still out and available for interactivity, rather than literally resetting the wizard with a click/tap. Is that how you see it too, or were you thinking there'd be an explicit "clear responses and start again" option here?

Also, the flow doesn't address (from what I can tell) what happens if a user has an unexpired, SIP application, but chooses the `start a new application` button.  Currently the user doesn't ever go back to the intro/subway map in that flow:
User clicks `start a new application` > presented with confirmation modal > User confirms > directed to first "page" of form questions.
 
I'm guessing since it's not addressed here, your recommendation is not to make any changes to that flow, but wanted to double check because we briefly touched on this a few meetings back.

**Comment by mnorthuis** [comment]
@andaleliz Excellent catches!   

I removed the start over from the "correct form?" step, you are right, that should not have that option at that point because they haven't proceeded.  Although we could think about a future "reset wizard" option if its not clear to users they can simply just change their answers if they feel they need to. 

I also expanded on the save in progress flow to show that users have a choice to either continue with their saved form or to start over. Based on our discussion Friday, we determined that if they want to start over, it would basically reset everything and send them back to the top - the /introduction page of the form with the wizard reset and open. 

IA updated: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md

**Comment by andaleliz** [comment]
@mnorthuis thought of 2 more things while working through the Edu screens.  Let's consider this flow as an example:
1990 Intro Wizard Open > User completes wizard > Routed to 1990N 

Based on the flow below, it looks like you're saying the wizard should be open on the 1990N, but in this scenario, that would mean the user would be completing the same wizard twice. So, we'd want to send them to the 1990N subway map, correct?

![Screen Shot 2020-10-05 at 7 41 32 PM](https://user-images.githubusercontent.com/55992116/95142927-d94efb00-0742-11eb-93e5-f8c8d9a8fda1.png)

Second question, same scenario:
Would the `go back / start over` link send the user back to the 1990 page (or whatever form they came from), or the wizard on the 1990N form?  I think this will be important logic to clarify for the developers (and maybe add to the flow from the circled Application B intro step), whether this link should function essentially as a back button like the browser, or send the user back to the beginning of the form they are on.  IMO, it should function like the back button on a browser (to application A), but want to be sure we're on the same page.

**Comment by mnorthuis** [comment]
Modified flow and added call-outs to describe the technical requirements.  Let me know if this is flow is getting too complex or if you find anything else missing/incorrect.

![image](https://user-images.githubusercontent.com/20994159/95248216-99d4ed00-07dc-11eb-848c-be0a43112598.png)

Wizard functionality
1. Skip/ignore wizard - This is an optional feature of the wizard pattern.  On the /introduction page while the wizard is displayed, an option may be provided that allows the user to skip the wizard or ignore's its recommendation if they want to continue forward on the current application.
2. Shared wizards - The same wizard may be shared across multiple related applications - i.e. the wizard on each of the education applications will be the same wizard, however the wizards on the chapter 31 and 36 wizards are different.  
    - If a wizard routes a user to a different application that shares the same wizard, the user will not need to complete the wizard again. 
    - If a wizard routes a user to a different application with a different wizard, the user will need to complete that application's wizard. 
3. Start over - Once the user has either completed or skipped/ignored the wizard, the /introduction page of the application is refreshed with content about that application along with an option for the user to "start over".  When the user clicks this option, it should function like the browser 'Back' button - they should be returned to the original /introduction page with the wizard completely reset (i.e. their previous answers are cleared). This option only appears on the /introduction page.
    - If the user did the wizard on application A, continued to application A, clicking "start over" would return them to the default state of application A
    - If the user did the wizard on application A, was routed to application B, clicking "start over" would return them to the default state of application A
4. Abandon application - If a user abandons their application by either navigating away from an unsaved form, choosing to start a new application, or their saved application has expired,  their wizard status should be reset.  When starting the application again, they would need to complete the wizard again. 
5. Resume saved application - If a user resumes a saved application, they would not need to complete the wizard again.  The saved in progress application will return them to the appropriate place within the application form flow.

**Comment by andaleliz** [comment]
It **is** complex, but I think it has to be, since we're dealing with complex flows.  IMO this serves as really thorough and clear documentation for teams.  Thank you @mnorthuis !

**Comment by mnorthuis** [comment]
Discussed entry point pattern and language with PW team.  Education entry points are updated here for review, others are in progress.  
https://docs.google.com/spreadsheets/d/1HvjCZ86EX4truevyUUbk-WdN-0A_5fcamRZV3GnmLq4/edit?usp=sharing

**Comment by mnorthuis** [comment]
IA for the general pattern and flow was finalized as of 11/20/2020.  Entry point work will be done with each team. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md
