### ISSUE TITLE
IA Feedback - Usability Prep - Chapt 36/PCPG

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#14205]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description

**MUST**
- Update breadcrumb of landing page and application per IA recommendations
- Show "Apply now" option in left nav as child of "Personalized Career Planning and Guidance" per IA recommendations

IA documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt36.md

**SHOULD**
none

**CONSIDER**
none

## Definition of Done
- [x] Must feedback is implemented on staging
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [x] Issue is closed by VFS team once complete

**Comment by jason-gcio** [comment]
@mnorthuis - thank you 👍

**Comment by jason-gcio** [comment]
We can certainly adjust the breadcrumb but Public Websites will need to adjust the static page.  Should I make that request?

**Comment by mnorthuis** [comment]
Yes, always good to coordinate with them.  Thank you!
