### ISSUE TITLE
❗️Support Mann Grandstaff to go live on Cerner pages on October 24, 2020

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#14203]
# Description

For 10/24, Mann-Grandstaff will be transitioning to My VA Health (Cerner) across the following pages:

- Refill prescriptions
- Secure messaging
- Schedule appointments
- View lab and test results
- Get your VA medical records online

We should assume that future facilities will also transition to My VA Health across all tools at the same time (like Mann-Grandstaff and not like Chalmers).

After Mann-Grandstaff, the anticipated date for the next facility is January 2021. At this time, Chalmers will likely also transition to My VA Health across all health tools. Lauren will share the latest roll out schedule as soon as she has it.

Therefore, we need to ensure that the implementation supports an ongoing staged release for Chalmers but each facility from here on out will go live to all pages listed above.

## Acceptance criteria

- [ ] There's support for Chalmers continuing to only have gone live on the Schedule appointments page.
- [ ] There's support for Mann Grandstaff to go live on all pages at once on October 24, 2020.

**Comment by ncksllvn** [comment]
Thank you for gathering this @kelsonic ! 

Per the thread [here](https://dsva.slack.com/archives/C0190MTGNUE/p1601490200002600), it looks like we can operate under the assumption that the Columbus VAMC is an exception in how it only offer the Schedule Appts product of the Cerner suite. With that, we should assume that all other VAMCs will offer the entire Cerner suite, and therefore they should include an `isCerner: true` flag that we can rely on (which was not the case for Columbus).

So what I'm thinking is that each portal (va.gov health-care page) to a Cerner product will first feature a Flipper feature flag as the top-level gateway. Then, when we render the authenticated content, we can check each facility for the `isCerner` flag (should be true for all VAMCs that are included in a Cerner launch going forward). To account for VAMCs that have only specific Cerner products enabled and not the whole suite (therefore making `isCerner` false for that VAMC), each portal should also have its own list of VAMC IDs to manually enable that portal for the VAMC of that ID.

@kelsonic what do you think?

**Comment by kelsonic** [comment]
That sounds good! So for each Cerner page we would have a feature toggle and then we would just rely on MPI's `isCerner` flag? Would love to discuss this further with you when you have time! 🙂

**Comment by ncksllvn** [comment]
> That sounds good! So for each Cerner page we would have a feature toggle and then we would just rely on MPI's isCerner flag?

That's correct - each Cerner page would have a feature toggle. Facilities have to have "isCerner: true" _or_ be listed in a hardcoded FE lookup list. So pseudocode would be -

```
# /health-care/appointments (authenticated user)

1. Is the Flipper feature flag `show_new_schedule_view_appointments_page` set to true?
    -> Yes
        -> Do any facilities have `isCerner=true`?
            -> Yes - Show the Cerner portal
            -> No 
                -> Do any facilities have an ID listed in the lookup table, `facilitiesEnabledForCernerScheduleViewApptsOnly`
                    -> Yes - Show the Cerner portal (this will be the case for Columbus facility)
                    -> No - Don't show the Cerner portal 
    -> No - Show the legacy content of this health care page
```

**Comment by kelsonic** [comment]
Let's do it! Great plan 👍

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn @kelsonic  

If you don't have this already, facility ID for Mann-Grandstaff (Spokane) = 668

**Comment by kelsonic** [comment]
Thanks you! 🙂

**Comment by CoryTrimmUSDS** [comment]
Just for ease of finding, I believe [we'll have to update this file](https://github.com/department-of-veterans-affairs/vets-website/pull/13836/files) that @kelsonic updated previously for Columbus.

**Comment by kelsonic** [comment]
Following yesterday's conversation, the next step for PW is to modify the `vets-api` `/user` endpoint response of `facilities` to derive the `isCerner` flag from 2 feature toggles (1 for whether Chalmers is live and 1 for whether Mann Grandstaff is live).

**Comment by kelsonic** [comment]
PRs up on both [vets-api](https://github.com/department-of-veterans-affairs/vets-api/pull/5107) and [devops](https://github.com/department-of-veterans-affairs/devops/pull/7811), awaiting reviews/feedback and then we'll need to update vets-website code to support the new `isCerner` flag behavior.

**Comment by kelsonic** [comment]
PRs merged! 🎉

**Comment by kelsonic** [comment]
Closing since launch went well, need a follow-up ticket with all facility IDs of Cerner facilities that will be launching in the future. That way I can create a PR to add their feature toggles

**Comment by jenniferlee-dsva** [comment]
@kelsonic - I've already captured request in a ticket for lauren. Here:  https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15309

**Comment by kelsonic** [comment]
Perfect, thank you! 🙂
