### ISSUE TITLE
Orientation for VAOS - new Designer and Product Manager

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#14204]
## Onboarding User Story
New Designer Peter Russo and new Product Manager Lauren Ernest from the VA Online Scheduling (VAOS) going through orientation to work on VSP, they need support to get up and running. This epic contains the tasks our team will perform to support them through their orientation stage.

## Goal
Get new Designer Peter Russo and new Product Manager Lauren Ernest from the VA Online Scheduling (VAOS) team up and running in their workflow as quickly as possible._ 

## Issues to create within this Epic

```
Send welcome email
Create a place to store all relevant documents for the team we are supporting
Have intake forms filled out
Set up team members as multichannel slack users
Give access to GitHub repo va.gov-team
Setup ZenHub for team
Complete orientation meetings and present engineering and UX slide decks
Meeting to make sure the team is setup and ready for development
Schedule times to meet with team
```

## How to configure this issue
- [x] **Labeled with `Product Support` Team**
- [x] **Orientation is complete and new VFS team is operating in their development workflow**

**Comment by shiragoodman** [comment]
@lenaecb

**Comment by anerbovig** [comment]
Hi @shiragoodman, Peter and Lauren have both started, listing their info below:

Name: Peter Russo
Role: Designer
Github profile: https://github.com/laurenernest
Email: lauren.ernest@adhocteam.us

Name: Lauren Ernest
Role: Product Manager
Github profile: https://github.com/outerpress/
Email: peter.russo@adhocteam.us

Lauren and Peter have both been invited to the VA.gov organization on Github, Peter has DSVA Slack access and Lauren is still getting set up with Slack access. Please let me know if you need any other information and I'd be happy to provide. Thank you!

**Comment by shiragoodman** [comment]
Thanks @anerbovig! We usually reach out through Slack DM's to schedule. Do you know when Lauren will get access?

**Comment by anerbovig** [comment]
I hope to have her up and running tomorrow, thanks @shiragoodman !

**Comment by shiragoodman** [comment]
sounds good @anerbovig . I just checked and don't see her yet. I'll reach out to schedule once she get's her access. thank you!

**Comment by anerbovig** [comment]
Hi @shiragoodman , Lauren is still not set up with Slack. She's also going to be out of the office next week, and may not be able to acknowledge the invite to Slack while she's out, so I'll check in on her status when she's back on Monday, Oct. 19. If there's a time that would work next week for the VSP team & Peter, we could do their orientations separately.

Apologies for any added confusion, and thanks for all your help while we wait for permissioning!

**Comment by shiragoodman** [comment]
Hi @anerbovig. Peter has gone through the VSP orientation, however because he is not yet in GitHub, I haven't been able to assign him an issue for ensuring all orientation items are complete. Can you let me know when he's in GitHub, and share his GitHub name here? Thanks!

**Comment by anerbovig** [comment]
Great, thank you Shira! He's been added to the VA organization, but doesn't have read/write access in the va.gov-team repo, maybe you could assist here? I created a ticket and to request the extra permissions: https://github.com/department-of-veterans-affairs/github-user-requests/issues/4792

Do you know if this is the right way to go about this step?

**Comment by andreahewitt-odd** [comment]
@anerbovig I added him to the team for him to have access so he should be good now! And you can close the user request -- that's not how you request write access to the repo. @shiragoodman I'll show you how to add folks to the correct github team.

**Comment by anerbovig** [comment]
Confirming here that I can tag @outerpress with no issues! Thanks @andreahewitt-odd, appreciate the direction. The other ticket has been closed.

**Comment by anerbovig** [comment]
Hi @shiragoodman, Lauren Ernest is back online and set up on the DSVA Slack if you want to reach out to her about VSP orientation. As part of that orientation step, would it be possible to set her up with read/write access to the va.gov-team repo? Thank you!

**Comment by shiragoodman** [comment]
Thanks @anerbovig . I reached out to Lauren via Slack and hopefully we'll get something scheduled soon. I can add her to the va-gov.team repo but she will need to have access to the VA organization, just like Peter. We can do that at her orientation (or sooner if you'd like to share her github name). Thanks!

**Comment by anerbovig** [comment]
Sure thing, and thanks again! Her github name is laurenernest: https://github.com/laurenernest

**Comment by shiragoodman** [comment]
@anerbovig we are good to go. @laurenernest has been added.
