### ISSUE TITLE
Define where we're using in app web views vs. sending users to browser

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14200]
This ticket is to define where we are sending users to their browser vs. sending them to an in-app web view. 

## Tasks
- [x] Create a list of all places we're linking out of the app
- [x] Define what's in-app web view vs. browser 

#### Homescreen
- Find a VA Location - **In-app webview**
- Coronavirus FAQs - **In-app webview**
- COVID-19 screening tool - **Open browser**

#### Veterans Crisis Line
- Start a confidential chat - **Open browser**
- More resources - **Open browser**

#### Personal & contact information
- How do I update my personal information? > Find your nearest VA location - **Open browser**

#### Letters & documents
- Benefit Summary and Service Verification Letter > Send a message - **Open browser**

#### Settings 
- Privacy Policy - **Open browser**

#### Appointments
- "Need to cancel? Visit VA.gov" - **Open browser**

#### Claims & Appeals
- "To view more details about your appeal, visit VA.gov: Visit VA.gov" - **Open browser**
- "What should I do if I disagree with your decision on my VA disability claim? > Learn about your decision review options" - **Open browser**

**Comment by srmyers17** [comment]
- Help states
- COVID FAQ
- Facility locator
- Privacy Policy
- What else?

**Comment by bridgethapner** [comment]
@bessgreen Just wanted to make you aware of this ticket in case it's helpful in writing front-end stories going forward. The TLDR is let's use the in-app webview for the **Coronavirus FAQs** and **Find a VA Location**, and send users out to their browser for everything else.
