### ISSUE TITLE
Display a veteran's 'pending disabilities' on the frontend

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1420]
```diff
- WIP - Is your list of pending items the same as in the Claim Status Tool, this might be redundant
```
## Story
As a veteran, I want the ability to view any pending disabilities I may have, as well as the date they were submitted, and the type they are. I want to be able to click on one of them to view more information.  

## Considerations  
Similar to Rated Disabilities, this should render to front end and be displayed with the same level of functionality currently.   

## Tasks
Before relevant endpoints arrive, display scaffold a table for Pending items, including headers mentioned in the existing table

## Definition of Done
- [ ] Display EVSS data to front end

**Comment by micahchiang** [comment]
### User Story
As a veteran, I want the ability to view any pending disabilities I may have, as well as the date they were submitted, and the type they are. I want to be able to click on one of them to view more information.

**Comment by micahchiang** [comment]
### Current view of pending disabilities:
![Screen Shot 2019-09-11 at 11 09 58 AM](https://user-images.githubusercontent.com/15097156/65447361-39e6f080-ddeb-11e9-8410-3a9666902ca7.png)

### Proposed view:
https://xd.adobe.com/view/ebfa6df6-c0aa-4ea9-413e-98793ba7a5a3-9dcb/
