### ISSUE TITLE
VANotify - Set expectation of confirmation email during 526EZ application

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/va.gov-team#14228]
When the confirmation email for the 526EZ application goes live, we would also like to update the text on va.gov to set the Veteran's expectation that a confirmation email will be sent to them.

We believe the confirmation page should contain this content and are open to any additional places in the application process you think should be updated.

**Comment by peggygannon** [comment]
Hi, @toddstanich Here is my recommendation of where we can add information about the confirmation email to the 526 application: 

1. On Contact information (see updated content and screenshot below)

UPDATE content TO: 
This is the contact information we have on file for you. Please review it to make sure the information below is correct. 
We’ll send any important information about your disability claim to your mailing address. After you submit your claim, we’ll send you a confirmation email to your email address. 

![2020-10-02 (5).png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/6cab1a08-496f-477b-8980-f8ddcc192979)



MOVE THIS content to bottom of screen. 
Any updates you make here to your contact information will only apply to this application. If you want to update your contact information for all of your VA accounts, please [go to your profile page]( va.gov/va.gov/profile/).

----------



2. On the Confirmation screen

Please update the first line on the successful confirmation page TO: 

**We'll send you an email to confirm that we received your claim. You can also print this page for your records.**

**Comment by toddstanich** [comment]
Thanks @peggygannon this looks good to us. I'll add these details to our implementation story.

**Comment by peggygannon** [comment]
Hi, @toddstanich  do you need anything else from me on this? If not, can this issue be closed?

**Comment by toddstanich** [comment]
Hi, @peggygannon we do not need anything more. Closing the issue. Thanks!
