### ISSUE TITLE
Staging: VistA Community Care Appointments Clinic Name = None

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#14226]
Steps to recreate:
Schedule future appointments into Community Care clinics in VistA
View appointments in VAOS
Expected Response: clinic name displays or no name displays.  
Actual response: Clinic name displays as NONE.  

![CommunityCare_ClinicNameNone.PNG](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/c4bbb5dd-1e58-4ba3-9dc0-a457439b77ef)

**Comment by jbalboni** [comment]
This looks like a MAS issue. We use the `communityCare` flag to determine if these appointments are Community Care or not, but that flag is false in the data in those screenshots.

**Comment by jbalboni** [comment]
VAOSR issue: https://issues.mobilehealth.va.gov/browse/VAOSR-1197

**Comment by laurenernest** [comment]
The JIRA ticket was Closed as working as expected. 

@saneshark @jbalboni Are we able to track how many times we get these? Seems like an edge case.
