### ISSUE TITLE
School Ratings: VET TEC Content Doc

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#14223]
Create stand-alone, ratings specific content document for VET TEC Search / profile page 

Will live here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/design/

**Comment by ccruzgra** [comment]
An additional section was added to the School Ratings v0.5 content doc to include the VET TEC UI: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/school-ratings/design/content-doc-v0.5.md#vet-tec---search-results-page

**Comment by ccruzgra** [comment]
@amyknox If no further adjustments are needed, this can be closed.
