### ISSUE TITLE
Access for Natalie Dunbar

### ISSUE THREAD

**Issue by nataliedunbarCS** [department-of-veterans-affairs/va.gov-team#14224]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Natalie Dunbar
- Please Provide your email.
   > natalie.dunbar@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA.gov CMS Team, Senior Content Strategist, Agile Six

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDU8wZzmJv/3rWtod/jwwL6NjbEV0tH5kw9y55LI5qFN0H4HcCzgQPGcyEmger/gQ+YcIKiMzI//ERpzocmFyEasPommgjowJ6O944tI+qzya2yNIx2psYVOAnbh89ziU2LRN9IzUcHqRIOHw/woKxROKyNDGECYtr+NJWYmG/z0JCAUctV4oZ08V5jgIQEpPEJhBjrdRdlsQfp0udFB5RI5PrHeU8N4Qjm6syKSjUlT7s/NMX8JCf4Acky9jkjy/PFh82L5//qp3Ce6SWXVRQU4e7fFzETNGCBWtWAtHENLPsdaxZQWH+NDgnaotxtVnhpxQO0uP5KGV6yPh+Xnh8NZZ44oWP5ORqGLzXvzr1x7N+NeF8/iIZp2BAU6EkLf2n6BuP7eWUJZJWGLaOV+DhBT+ByxtWEf/VdTm4l1hG8BGuIkzatVLQGvsslTx6kupptStFvOtMks3t26YK7XFEyYT4sE+CUWkulKib9+MSBeTI9SvSgPNAbkyExLqOl+Ts= natalie.dunbar@Agile6-A44-Pro.attlocal.net

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDU8wZzmJv/3rWtod/jwwL6NjbEV0tH5kw9y55LI5qFN0H4HcCzgQPGcyEmger/gQ+YcIKiMzI//ERpzocmFyEasPommgjowJ6O944tI+qzya2yNIx2psYVOAnbh89ziU2LRN9IzUcHqRIOHw/woKxROKyNDGECYtr+NJWYmG/z0JCAUctV4oZ08V5jgIQEpPEJhBjrdRdlsQfp0udFB5RI5PrHeU8N4Qjm6syKSjUlT7s/NMX8JCf4Acky9jkjy/PFh82L5//qp3Ce6SWXVRQU4e7fFzETNGCBWtWAtHENLPsdaxZQWH+NDgnaotxtVnhpxQO0uP5KGV6yPh+Xnh8NZZ44oWP5ORqGLzXvzr1x7N+NeF8/iIZp2BAU6EkLf2n6BuP7eWUJZJWGLaOV+DhBT+ByxtWEf/VdTm4l1hG8BGuIkzatVLQGvsslTx6kupptStFvOtMks3t26YK7XFEyYT4sE+CUWkulKib9+MSBeTI9SvSgPNAbkyExLqOl+Ts= natalie.dunbar@Agile6-A44-Pro.attlocal.net
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by nataliedunbarCS** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@nataliedunbarCS 
Please verify that you can access resources via SOCKS proxy. You should now have access.

**Comment by nataliedunbarCS** [comment]
I am not able to access resources via SOCKS proxy. Will reach out to the VMS platform support on slack for assistance. Thank you.

**Comment by jbritt1** [comment]
User's key updated and verified with user that SOCKS connection is good at this time. Closing.
