### ISSUE TITLE
VANotify - Content for auto response to unmonitored email address

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/va.gov-team#14229]
Our service provider for emails will send an auto response when a user replies to an email sent from our service. The content should inform the Veteran that the email is not monitored and direct them to an appropriate way of getting help.

I've attached a document of a standard auto response used by another VA service.

[https://app.zenhub.com/files/133843125/048c1323-1a4b-4757-9c7d-f19d6314c6d2/download](https://app.zenhub.com/files/133843125/048c1323-1a4b-4757-9c7d-f19d6314c6d2/download)

**Comment by QaysarA** [comment]
Hey @peggygannon I provided a draft of the 'do not reply' auto response email content to our vendor so that they would not stop the setup. I have that attached to this comment and once we complete/finalize content, I will send any changes that need to be made to the vendor
 [https://app.zenhub.com/files/133843125/f927c9af-a5cb-4856-92ee-72f65b22ae64/download](https://app.zenhub.com/files/133843125/f927c9af-a5cb-4856-92ee-72f65b22ae64/download)

**Comment by peggygannon** [comment]
thanks, @QaysarA I'm working on this today, so will take a look at the draft ^^ thank you

**Comment by peggygannon** [comment]
Hi, @toddstanich and @QaysarA recommendation for NO-reply email below. 

@toddstanich I can't recall if the current 526EZ confirmation email has a line that let's users know to not response to the message (for example, Please don’t reply to this email. Messages sent to this mailbox can’t be answered.) Can you let me know? I don't have this in my notes for the 526 email. 


-----

No reply email: 

Subject line: This message has been sent to a mailbox that isn’t monitored 

This mailbox isn’t checked by anyone. Messages sent to this address won’t get a reply. If you need to reach someone, please use the contact information below. 

If you’re a Veteran in crisis and need immediate help, please call 800-273-8255 and press 1. Or visit www.veteranscrisisline.net.

If you have questions or need more information about your benefits, please visit VA.gov or call Veterans Benefits Assistance at 800-827-1000 (TTY:711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by toddstanich** [comment]
Thanks @peggygannon! We had added this to the footer of the email, "You are receiving this email because you filed a claim on VA.gov. Please do not reply to this email. If you need to contact us please visit https://va.gov."

**Comment by QaysarA** [comment]
Hey @peggygannon I had one comment regarding '... or call Veterans Benefits Assistance at 800-827-1000 (TTY:711)...' this auto reply email will be for all email notifications that VANotify will send. The 526EZ confirmation email is our MVP and that is under the VBA, in the future any group at the VA could use VANotify - and the Veteran may be inquiring/responding to an email notification about healthcare or the cemetery.

**Comment by peggygannon** [comment]
@QaysarA  ok, thank you for clarifying. I was wanting to add a phone number as another option for the user. How about using this for that last paragraph.  I've swapped out the benefits number for the general VA.gov number. 


If you have questions or need more information about your benefits, please visit VA.gov or call us at 844-698-2311 (TTY:711).

**Comment by QaysarA** [comment]
@peggygannon yes, the updates to the last paragraph look great - that would allow the Veteran to get routed to the right group/team at the VA. Thanks for expediting this request for us and I appreciate your help. I will send the updated content over to the vendor for setup.

**Comment by peggygannon** [comment]
Hi, @toddstanich and @QaysarA do you need anything more from me for this issue?

**Comment by toddstanich** [comment]
Hi, @peggygannon we do not need anything more. Closing the issue. Thanks!
