### ISSUE TITLE
Staging:  My Reason Isn't Listed Here Auto Populates SM field "Other reason for appointment" with "See message"

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#14230]
1.  VAOS Reason for Appt = "My reason isn't listed here" corresponds to "Other"  
2.  VAOS "Please give us more detail about why you’re making this appointment" maps to Additional Information is SM. 

#1 and #2 make sense.  No issue there.

But in SM when My reason is not listed here, SM is add this field "Other reason for appointment" and auto populates with "See message". This extra bit of info is confusing and makes no sense as there no message to see.  

![OtherReasonforAppt.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/a3e56824-c4c0-4192-bb8b-5dedcd92bd49)

**Comment by jbalboni** [comment]
It seems like this should say "See additional information." 

And also, SM should probably just hide this field, it will never have useful information. Created an SM issue: https://issues.mobilehealth.va.gov/browse/SCV-5810
