### ISSUE TITLE
Staging:  Request Limit Not Observed if Any Existing Submitting Request is Older than ?? Date

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#14235]
Select a veteran that has existing requests that are old. Not sure how old.  But old.  
Judy Morrison has existing Primary Care request from 5/22/2020 from Loveland
Set VATS to Yes Any Veteran with Limit = 1 for Loveland 
In VAOS select Primary Care, Loveland
Expected Response:  user informed that limit has been reached.
Actual Response:  user can submit request and exceed VATS limit.  

Another example Nacier Stowe.  Existing Optometry Request from 4/10/2020 from Fort Collins.  
Set VATS to Yes Any Veteran with Limit = 1 for Fort Collins.  
In VAOS select Optometry and Fort Collins
Expected Response:  user informed that limit has been reached.
Actual Response:  user can submit request and exceed VATS limit.  

Though we might decide this is desired behavior since you can't cancel these old request since new UI only displays request submitted within the last 30 days.  I am going to check the VSSC reports to see how many request are older than 30 days. This might prove useful information in determining where to go with this.  

![Morrison_PrimaryCare.PNG](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/3ac90917-bcde-49ce-ba98-c63b29e289a3)

![Stowe_Optometry.PNG](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/83734094-3ab4-4723-a4d1-a76989dfcfca)

**Comment by jbalboni** [comment]
It looks like var-resources is getting the last 120 days for requests for this count. This does create a gap where a request falls off the user's list after 30 days, but isn't excluded from the request limit check until 120 days. 

I agree that we should see how many submitted requests are older than 30 days. We should probably change the max days for the check to be in sync between the FE and BE, and we could do that in either direction, potentially.
