### ISSUE TITLE
[Discovery] Competitive Analysis of Resource content and IA on other sites

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1423]
**Goal:** 
- Document knowledge/support/learning/resources from content on other sites (government and corporate brands)

**Competitor Research Questions / Answers to Include:**
- How do they organize their IA? separate subdomain, incorporated within main site, on/off their product pages
- Background how do their users access this type of content, is it effective/not? What doesn’t 
work well? What does?
- Specific Site Examples:  Gov.uk, Social Security Administration, Small Business Administration, 
Zappos, Canadian government site, 23me. Please include others you find useful as illustrations.

**Focus for this Category of Content:**
- landing pages
- What types of detail pages exist:  templatized (How do I’s/ FAQs/Abouts) or unstructured?

**Acceptance Criteria:**
- [ ] Screenshots of IA access paths (from homepage, from a product page, from global nav?)
- [ ] Screenshots of content landing page + detail page types, if applicable

This task is related to tier 2 content audit task: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1418

**Comment by Karak888** [comment]
@lwalsh617 do you think this is in acceptable state for completion to close for this sprint so that you can pick up in audit in sprint starting today? Thanks

**Comment by Karak888** [comment]
@lwalsh617 closing this out for Sprint 3 even if you had minor tweak you can begin work on Audit of Tier 2 content. Thanks!

**Comment by jenniferlee-dsva** [comment]
@lwalsh617  - LOVE what you've put together. Great food for thoughts and a lot of interesting ideas. There were some content types that I would def put into our tier 3 bucket ( a lot of those 'about us'/ 'working with us'/ legal OIG stuff).
