### ISSUE TITLE
22-1995 Printer Friendly Confirmation Page

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#14249]
- [x] Mock up 22-1995 printer-friendly confirmation page
- [ ] Share with BA/Devs
- [ ] Refine / updates as necessary

**Comment by ccruzgra** [comment]
PDF of 1995 confirmation print out: [https://app.zenhub.com/files/133843125/bbfa319c-cbe0-4879-a395-399aeb46c481/download](https://app.zenhub.com/files/133843125/bbfa319c-cbe0-4879-a395-399aeb46c481/download)

Also indicated in 1995 content doc that the accordion should be suppressed from the print out after verifying this is possible with devs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/1995/content/1995-content-doc-v3.0.md#form-title-update-your-education-benefits-11

@dneel-bah This is good to go. Let me know if you have any questions or concerns.
