### ISSUE TITLE
STEM: Add text message field to spool file

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14247]
As a developer, I need to include the text message question and answer in the spool file so that it can be used by the RPO.

## Assumptions:
1. This work is completed behind feature flag `stem_text_message_question` (#13826)

## Acceptance Criteria
1. The following content is included in the spool file after "Preferred method of contact" and before "Direct Deposit":

> I would like to receive text message from VA about my GI Bill benefits:

2. When the feature flag is off; the answer to the question is "N/A"
3. When the feature flag is on; the answer to the question reflects the user selection in the form.
    a. No, if the corresponding question is unchecked.
    b. Yes, if the corresponding question is checked.

## Supporting Artifacts:
1. [Prototype v6](https://bahdigital.invisionapp.com/share/FAIAEVUYVKN#/screens/296049093) as of 09/21
2. [Content v6](https://github.com/department-of-veterans-affairs/va.gov-team/blob/e7b88bd6c48f5d61adfee110f63ef924058a25d7/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md#chapter-title--5-of-6--personal-information) as of 09/21
3. Mock Spool File Format: [10203_Spool_with_Twilio_20200921_story_version.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5257151/10203_Spool_with_Twilio_20200921_story_version.docx)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5036

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-07 at 12.49.24 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/76e29268-e8b4-43b1-a843-334fa28d66ce)
##
![Screen Shot 2020-10-07 at 12.49.39 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/59e4132d-ac69-44dc-9cb9-dc47b5d44988)
##
![Screen Shot 2020-10-07 at 12.49.51 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6ad1e960-e434-4aeb-b2e5-623e47607ee8)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/12788&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
Testing passes QA
