### ISSUE TITLE
1995: Remove 'form_1995_edu_updates' feature flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14243]
As a developer, I need to remove the 'form_1995_edu_updates' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. This feature flag was created in #14064 
2. The updates have been signed off on in staging as of 10/22.
3. The new functionality is live in production with no need remaining need for the toggle.

## Acceptance Criteria
1. The feature flag 'form_1995_edu_updates' is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.
3. The functionality previously behind the feature flag is available in production:
    a. #13965 
    b. #14358 

## Supporting Artifacts:
1. https://github.com/department-of-veterans-affairs/vets-website/pull/14447

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/15227
- https://github.com/department-of-veterans-affairs/vets-api/pull/5445

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
The `form_1995_edu_updates` feature flag is now removed from all environments. Closing this issue
