### ISSUE TITLE
1995: Remove prod flag for updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14244]
As a developer, I need to remove a prod flag so the updated content is available in the production environment.

## Assumptions:
1. The work completed in #13965 has been reviewed and signed off in staging as of 10/15
2. The work completed in #14358 has been reviewed and signed off in staging as of 10/22

## Acceptance Criteria
1. The work completed in #13965 is available in the production environment.
1. The work completed in #14358 is available in the production environment.

## Supporting Artifacts:
1. https://github.com/department-of-veterans-affairs/vets-website/pull/14447

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14794

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
This is in production. Closing this out
