### ISSUE TITLE
[Discovery] Schedule by VA / CC provider flow

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1424]
## Story
As a veteran, I want to be able to schedule healthcare appointments with doctors that I've seen before so that I can get care from a doctor I trust.

## Context
While Cerner will eventually provide a more robust provider-centric solution on the backend, we should do some technical discovery in an attempt to enable a provider-centric scheduling flow for veterans using the existing backends.

Currently, it should be possible to allow veterans to choose a doctor from among all the doctors with which they've had history. However, we should validate this and attempt to find where this data would come from and how we'd be able to submit an appointment / request against a specific provider.

## Acceptance Criteria
- [ ] Documentation exists in GH for service that would allow us to surface a list of providers that a veteran has a history with (or document that this isn't available)
- [ ] Documentation exists in GH for how vets-api would be able to do a POST for appointments / requests with specific providers
- [ ] Decision is documented on whether it's technically feasible to provide a provider-based scheduling flow without updates to backend services (i.e., pre-Cerner)

**Comment by ldelacosta** [comment]
We will need to check with the Product Owners to see if this is still needed. 

cc: @JRRoof

**Comment by ldelacosta** [comment]
Closing out this ticket. We will need to create a new ticket after we have fully integrated with Oracle Health and Well Hive. cc: @JRRoof
