### ISSUE TITLE
User testing approach

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14257]
## Notes
- Peregian testing?
- VHA beta testing?
- Recruiting from AH + VA?

**Comment by bridgethapner** [comment]
Bridget next steps: 

- Write POV about prioritizing the backlog
- Write POV about usability testing the "MVP"

**Comment by bridgethapner** [comment]
My first draft of user research approach for usability testing + post-MVP planning: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-research/usability-testing/readme.md

**Comment by srmyers17** [comment]
Added a couple of things in a PR for you to review, @bridgethapner!

**Comment by bridgethapner** [comment]
Thanks @srmyers17! All looks good to me. Will move to Design review to remember to share w martha tomorrow & we can share w Steve next week.

**Comment by bridgethapner** [comment]
Reviewed w Martha 10/8. Bridget to make update to add 508 office support to usability plan, share in Slack next week.
