### ISSUE TITLE
STEM: Remove prod flag used in #13784

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14250]
As a developer, I need to remove a prod flag so the updated content is available in the production environment.

## Assumptions:
1. The work completed in #13784 has been reviewed and signed off in staging as of 10/15
## Acceptance Criteria:
1. The work completed #13784 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14614

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by sonntag-adam** [comment]
In production. Closing story.
