### ISSUE TITLE
Discovery on feasibility of micro frontends

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1425]
## Overview

- [Micro frontends](https://martinfowler.com/articles/micro-frontends.html) are an approach to managing multiple front end apps in an ecosystem that prioritizes team autonomy
  - covers patterns that allow every team to have their own build / deployment pipeline 
  - addresses concerns with bundle size, css, etc 
- Problems this could address: 
  - reduce the overhead with managing `vets-website` front end platform by separating the front end apps from the platform (e.g. not using a monorepo)
  - allow apps teams to modify or introduce additional tooling, modules, or development flows without impacting the platform
  - remove the need for the platform team to review application specific code 

## Goal

- determine feasibility of micro frontend approach for `vets-website`

## Potential tasks 

- focus on process for accommodating design system- this specific challenge is not addressed in the micro frontends article
- determine how the platform group would manage critical metrics like performance, bundle size, user experience, test coverage

**Comment by rianfowler** [comment]
@cvalarida Can you link to your design document here? I think this is the next step after separating the cms build.

**Comment by timwright12** [comment]
closing since we're doing this as part of the app isolation discovery
