### ISSUE TITLE
Execute Confluence Pilot: Release Plan

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#14251]
Execute Confluence Pilot: Release Plan #14251
## Guidance

_This Release Plan Template is intended to help ensure your new VSP product or feature is ready for launch and will deliver the desired user outcomes._
* _In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necessary prior to going live._
* _In Phase 2, you will define the launch communications plan and post-launch KPIs. **You can close this ticket once you have completed Phase 2**._
* _Phase 3 is optional - you may use it to document post-launch results._

_Fill out the **Planning** sections to start, then the **Results** sections as you complete each phase of testing._

---

## PHASE I: USER ACCEPTANCE TESTING
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- Desired date range or test duration: _Beginning of Sprint 39 (11/12) - midway through Sprint 41 (12/16), ~5wks_
- Desired number of users: _Five (5)_
- The group(s) from which you'll recruit test users: _VFS teams (both VSA and non-VSA application teams)_
- How you'll recruit test users: _Combination of channel asks, DMs, and ToT.  [Detailed recruitment strategy.](https://docs.google.com/document/d/1YWrLai3qheKYsMgtkuaN0S0-_tsvKVb-pUSzj1fr-GM/edit#bookmark=id.fvu1657tj0x7)_
- How you'll give test users access to the product: _Optimal Workshop study.  [Non-live link here.](https://adhoc.optimalworkshop.com/treejack/6v04p01o/tasks)_
- What "Success" criteria will you look at before launch? 
  - _VFS sentiment around current platform BE developer documentation: [BE-specific section](https://murally.blob.core.windows.net/uploads/adhocvetsgov9623/1609890426890.svg?se=2021-01-15T05%3A30%3A00Z&sp=r&sv=2018-03-28&sr=b&rscc=public%2C%20max-age%3D600&sig=MlCBNlI1CKfTP8GFNE98C2s3VJtDEHIaX1SF4pHv4hs%3D) of the [User Journeys MURAL board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1587506427611/4fb63eb007eadec05ce8634499699ff610706a7d) - according to this 2020 Q1 research, sentiment ranges on average from neutral to dissatisfied_ 

- How you'll measure your "Success" criteria? 
  - Sentiment of proposed Confluence BE documentation IA will be measured via interviews with research participants

### Results:

- Number of users: 
  - _5 individuals:_
    - _1 OCTO, 2 VSA, 2 non-VSA_
    - _2 women, 3 men_

- Results per your "Success" criteria: 
  - Participants had generally positive sentiment around the proposed IA, along with specific critiques.

- Number of bugs identified / fixed: _n/a_

- Any UX changes necessary based on the logs, user feedback, or VA challenges?
  - _Yes: Participants indicated that Testing is more appropriate housed under Developing on VA.gov, instead of a standalone section_
- _Takeaways comprehensively detailed in the full research readout deck: [Slides](https://docs.google.com/presentation/d/1lVLH2vcF3xm-dI-4MqTn1aESoYHsocK5Lm6EfWPoexg/edit#slide=id.ga793902612_0_99), [PDF](https://drive.google.com/file/d/13t9ULmge2tW3pd67nNEAd0kHs3QFjwej/view?usp=sharing)_

### Planning:

Our goal is to socialize the VFS-facing documentation to VFS teams.  There are multiple parts to this goal: 
1. By the end of January, socialize VFS-facing BE documentation.
2. At the end of Q1 or start of Q2, inform VFS teams that we have made progress on moving the priority set of documentation to Confluence, and will be taking Q2 to move the rest of it.
3. At the end of Q2, socialize the link to the entirety of VFS-facing-VSP-owned documentation.

Socialization for all three above parts above will occur over three mediums: #vfs-all-teams, the Newsletter, and Team of Teams.  

This is the language we currently have drafted for the VFS-facing-BE-owned socialization: 

> VSP is moving our documentation. Use the new documentation website to learn about building, deploying, and maintaining backend code on VA.gov.  

End of 2021 Jan:
- Success of the VFS-facing-BE-owned docs socialization will look like:
  - Increased adoption of VFS-facing-BE-owned documents (# of new users / total number of users)
  - Reduced volume of BE-specific support requests

End of 2020 Q2: 
- Success of the VFS-facing-VSP-owned docs socialization will look like: 
  - Increased adoption of VFS-facing-VSP-owned docs (# of new users / total number of users)
  - Increase in volume of support requests being linked to documentation
  - Reduced volume of non-PR-review support requests

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by vbellissimo** [comment]
Cancelling/old task.
