### ISSUE TITLE
Onboard VSP developers to work on transformers

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#14252]
### User Story 

As a VSP developer, I need to learn about transformers: what they are, how to create them, how to troubleshoot them, so that I can help improve our tooling and documentation and work towards parity between GraphQL and CMS Export Build.

### Details

Dan and Eugene began onboarding to transformers work around 9/21. This ticket is to track that work as needed.

### Definition of Done

- [x] Dan and Eugene have created a new transformer
- [x] Documentation feedback has been captured as they have onboarded

**Comment by U-DON** [comment]
Recreated transformer as part of onboarding. department-of-veterans-affairs/vets-website#14378
