### ISSUE TITLE
Document the pre-fill pattern

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14269]
## Issue Description
We have documentation about the Save in Progress functionality of the forms library, but it makes no mention of pre-fill. I searched through our documentation and found no mention of it.

Pre-fill needs to be added to our documentation as a pattern that forms can use to populate user data when a user first starts a form.

---
## Acceptance Criteria
- [ ] The pre-fill pattern is documented

**Comment by caw310** [comment]
Closing as forms library is being rebuilt.
