### ISSUE TITLE
[Tech Debt] Letters: Remove Reference to "Adobe" for the PDF Reader

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14263]
## Issue Description
We should say something like "for instance, Adobe Reader" but really we should tell folks to just use a PDF reader.

## Acceptance Criteria
- [ ] No more Adobe
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
Adobe Reader includes a link. Should the generic PDF reader link point to [wikipedia](https://en.wikipedia.org/wiki/List_of_PDF_software), or something?

**Comment by kevinstachura** [comment]
Anyone got a link to where this issue exists?

**Comment by annaswims** [comment]
I was curious why it said that in the first place and found this - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2732

https://www.va.gov/records/download-va-letters/letters/letter-list
<img width="758" alt="Screen Shot 2020-10-02 at 9 29 40 AM" src="https://user-images.githubusercontent.com/19188/94928546-daa5cc80-0491-11eb-875a-e1d8120dc38e.png">

**Comment by luke-gcio** [comment]
I was about to send this to platform to ask if there is a reason why we say Adobe.  Perhaps this is still not ideal but it may be the wrong hill to begin dying on.

**Comment by Mottie** [comment]
@peggygannon Do you have any recommendations about this change? We don't need to tell the user that Adobe Reader is necessary just to download a file.

**Comment by Mottie** [comment]
Related conversation: https://dsva.slack.com/archives/C52CL1PKQ/p1603067415374700

Essentially, we could point the user to the following page instead of recommending a specific program: https://www.va.gov/viewer.htm

**Comment by peggygannon** [comment]
Hi, @Mottie sorry, I completely missed this last week.  Do you still need some guidance on wording?

**Comment by Mottie** [comment]
Yes, please. I think it might be better to redirect the user to the viewer page I shared above. Ultimately, it seems that we do recommend Adobe, but the letter app is the only application in vets-website repo that explicitly states this fact.

**Comment by peggygannon** [comment]
OK, I'm going to look into this a little bit @Mottie I've reached out to Beth Potts about this very page you linked to above,  and to check if the Public Website team has created any standard language around PDFs. will keep you posted.

**Comment by peggygannon** [comment]
Hi,  @Mottie Here's my recommendation below. I want to avoid sending users to a legacy page, so I recommend we update the content here to below. This aligns with Q&A content that will appear in the soon-to-be launched Resources and Support on VA.gov. (Once that launches we can add a link to there)


To see an explanation about each letter, click on the (+) to expand the box. After you expand the box, you'll be given the option to download the letter. 

To download a letter, you'll need to have Adobe Acrobat Reader installed on your computer. You can then download or save the letter to your device. Open Acrobat Reader, and from the File menu, choose Open. Select the PDF. 

If you're still having trouble opening the letter, you may have an older version of Adobe Acrobat Reader. You'll need to [download the latest version]. It's free.

**Comment by Mottie** [comment]
Thank you!
