### ISSUE TITLE
Testing Ticket - flat list location selection page

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#14268]
1.  Login as Veteran only registered at one site (CJHYSHR)  noahjames.j.staknis@id.me
2. Select Primary Care
3. Select VA Care.  System shows the 4 CHYSHR Sites and indicates that there is an +-1 more locations.
4.  Select +-1 more locations.  Expected response:  System show other sites
5.  Actual response:  There are no additional sites. 

![AdditionalSites.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/76aecff3-ee34-4ce0-91d8-4b66991ba41b)

1.  Login as Veteran only registered at one site (DAYTSHR)  marcy.nadeau@va.gov
2. Select Primary Care
3. Select VA Care.  System shows the 5 DAYTSHR sites and indicates that there is an +0 more locations.
4.  Expected response no message to indicate additional sites as DAYTSHR only has 5 sites.  
5.  Actual response:  System shows +0 more locations.

![ZeroLocations.PNG](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/bc4848d8-7fe0-4cb2-96a9-63d605bf8267)

**Comment by lenaecb** [comment]
This is the testing ticket for testing the 'flat list alphabetical' version of the Facility Selection page. Maps to this implementation ticket-[]( https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13306)

**Comment by beth-wodzinski** [comment]
This looks good. The list of locations matches what's show in VATS. If the veteran has an address on file, the locations are sorted by distance; if the veteran does not, the locations are sorted alphabetically. Works properly for one site (CHYSHR, DAYTSHR) or both. Pass.
