### ISSUE TITLE
Form app code imports all forms code.

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14278]
## Issue Description
I discovered this when I ran into an error on the 1990 edu benefits form. The error was happening on the 526 all-claims form. After a little digging, I discovered forms library code is importing `applications/personalization/dashboard/helpers.jsx`, which imports _all_ form configurations...which in turn import all their pages, etc. etc. See the stack trace for more details.

![image](https://user-images.githubusercontent.com/12970166/94853072-ad004b00-03df-11eb-8200-222285d89c88.png)

Turns out there are more forms library modules that are importing this file. The forms library code cannot import this file if it imports all the configuration files.

---
## Acceptance Criteria
- [ ] The following files no longer import `applications/personalization/dashboard/helpers.jsx`
  - [ ] `save-in-progress/FormSaved`
  - [ ] `save-in-progress/SaveInprogressIntro`
  - [ ] `save-in-progress/ApplicationStatus`
- [ ] `FormSaved` still shows the form title

## Note
Don't forget to measure the size of the application bundles before and after the change so we can measure the impact.

**Comment by billfienberg** [comment]
It looks like [the `formTitles` named import is only used in one place inside the `FormSaved` component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/save-in-progress/FormSaved.jsx#L61).

Since the `formId` is already passed to the `FormSaved` component via `props`, would it be feasible to update the `FormSaved` component to accept a `formTitle` string prop, and move the `formTitles[formId]` code from inside the `FormSaved` component to the component that renders the `FormSaved` component?

**Comment by cvalarida** [comment]
Yeah, I also discovered a couple other utilities used in the `SaveInProgressIntro`, so we'll need to do a little more thinking about how we can go about removing the import to this file while maintaining the functionality we need.

**Comment by cvalarida** [comment]
I commented out the imports to the dashboard helpers in those two files and compared the result. It's definitely worth spending the time on! Looks like it shaves off ~8-9 MB from the bundles (localhost build).
![image](https://user-images.githubusercontent.com/12970166/94867133-759c9900-03f5-11eb-8987-c0ff0a4b5aab.png)

**Comment by cvalarida** [comment]
Comparing the prod builds yields less impressive results (~1.3 - 1.5 MB average), but that still cuts the prod bundle sizes for form applications in half.
![image](https://user-images.githubusercontent.com/12970166/94869957-40934500-03fb-11eb-9aca-995c553925f2.png)

**Comment by cvalarida** [comment]
## Notes to myself
Running out of time for the day, but before I forget...
### Removing `formTitles` from `FormSaved`
- Each form will need to describe itself
  - I think we can call this `benefitDescription: 'education benefits'` or something
  - We may want like a `benefitDescription: { type: 'health care benefits', subText: '(10-10EZ)` }` option as well
- The `formTitles` helper will work the same as `formLinks`; just use the `formConfig` property
- We can then use `this.props.route.formConfig?.benefitDescription` (:nauseated_face:) in `FormSaved` to replace `formTitles`
