### ISSUE TITLE
An error was raised when trying to read a PDF on user 10-10CG PDF Generation

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#14274]
**Description**:
On 10-01-2020, there were multiple attempts to generate a pre-filled 10-10CG, but it failed because 
```
No such file or directory @ rb_sysopen - /srv/vets-api/src/tmp/pdfs/10-10CG_uuid.pdf
```

**Sentry Error**:
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/221153/?query=is%3Aunresolved%20controller_name%3Acaregivers_assistance_claims

**Comment by ala-yna** [comment]
Closed - issue was investigated and should be addressed by the current background processing work.
