### ISSUE TITLE
Access for Elwood Gary

### ISSUE THREAD

**Issue by elwoodva** [department-of-veterans-affairs/va.gov-team#1427]
#Description

I have actually filled out this form for the new key on my new Mac before but it's not working so I wasn't sure how to get someone to look into it with me again.  So I have re-generated my key and added it to GitHub.  I deleted the one that wasn't working before.

- Please provide your Contracting Officer's Representative (COR) name.
   > Matt Bain
- Please provide your name.
   > (Kenneth) Elwood Gary
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > By Light
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a 

 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDafD8e477g2fkUQ8Ibt1ETuz4lUvcF5LU78e4td+Mq3ypp887b+FzuqxTVu209+Wx0WFBSzXfjhvXeXCXX5J47AILzFWvTFNB7B7K0mwCdATvUbAnY3HfNy2NggbH/QlOMkWV21RD2Czh40645cf+PJoHVmi5ezpavGINim+Plen2HByY0+UD0CWAKqCp5JtnDHwsdsnCHtpkhyFpXcMjfcDm9ybpbyN8oEs3Lezv9FtHAeYOUxf0irbxGCDTKtLSvQ3tt2C0OLkvbuZYG/q073V+0xNIyZXzIVloWjZW5h+qPK8T3sLwGfzDTX7HV6GQrb0OTkNJBwl/NHOrpxgNV elwoodgary@elwoods-mbp.lanq

- [Grant AWS Console access?]
  > YES

**Comment by elwoodva** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by b00klegger** [comment]
@elwoodva 
Explain the issue you're having and please feel free to attach pictures and pasted output from the terminal

**Comment by elwoodva** [comment]
Ok, I will, but first, I did delete the old ones and re-did the procedure so the new one that's there now will have to be added. But let me get you a screen shot.

**Comment by elwoodva** [comment]
![Screenshot 2019-08-30 at 7 33 46 AM](https://user-images.githubusercontent.com/46933023/64017955-e7baf400-caf8-11e9-98b8-97148b0f92ff.png)

**Comment by elwoodva** [comment]
I added the regular GitHub keys to my machine and I can do the normal git procedures with the source code.  But when I try to use the keys I generated for id_rsa_vetsgov with the socks proxy I get the errors you see in the screen shot above.

**Comment by elwoodva** [comment]
![Screenshot 2019-08-30 at 8 28 33 AM](https://user-images.githubusercontent.com/46933023/64020726-4768cd80-cb00-11e9-96c0-dcdd607ef238.png)

**Comment by elwoodva** [comment]
![Screenshot 2019-08-30 at 8 34 53 AM](https://user-images.githubusercontent.com/46933023/64021042-1341dc80-cb01-11e9-9cae-dee87fe4672f.png)

**Comment by elwoodva** [comment]
I am double checking the key and I seem to have accidentally pasted the wrong thing above.  Here is the current key of mine: 

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvbjQ+PxrByrEsaAb4snhTOpXjCrXBXJoKjm+49npyJ5OLveoRGk65YMp5otzcu+gp17Rde3ckQ91hj6k2JdcEDtGDYW5axdrydQliC43O3TQImyU39+ahdwTj2sQnJXu6RLI+wuZVXnsQNosMGz3k0DIQeNFiS5PetfKaBNPW7k4JlMZt/IYlSQZLY7SENgE0yTGPLJBW6xae5uKqD1cpYtWkdU+2W5nLOMIzuPwDCG3mg0p6VerLoYpgkf6CE6RAuIDWBVjudhAY0bSLoWB01pzQU40Ib0pJwTeDzzCfimL3X8ksLF16z6ydsR6s1kbei/M/gRuQPhl9gAPFQ0OZ elwoodgary@Elwoods-MacBook-Pro.local

**Comment by b00klegger** [comment]
confirmed with engineer that is now working
