### ISSUE TITLE
[Design] - Update resources and support mockups to replace instances of learning center

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#14280]
Update mock-ups to reflect the updated product name:

- breadcrumbs- TBD
- homepage h1 should read: "Resources and support for your VA benefits and services"
- heading above search should read: "Search resources and support articles or all of VA.gov."
- radio buttons should read: "Resources and support" and "All VA.gov"
- h1 on list pages should read: "All articles tagged: [tag label]" or "All articles in: [category] "
- h1 on search query page should read "Search results"

**Acceptance Criteria**
- [x] Mural board updated with new mock-ups reflecting these changes
- [x] new sketch file uploaded to GH so @rtwell can pull down the latest

**Comment by mnorthuis** [comment]
@andaleliz FYI I will work through breadcrumbs and urls with the IA work.  If you need placeholder info sooner, let me know and we can discuss.

**Comment by andaleliz** [comment]
@kelsonic and @ncksllvn can you please help me with prioritization/timing on this? When are these updated screens needed/most helpful?

**Comment by ncksllvn** [comment]
@andaleliz Is this specifically applying to the homepage of the LC?

**Comment by andaleliz** [comment]
@ncksllvn.  All pages will be impacted as far as mock-ups go since the search and breadcrumbs are on each page. The homepage h1 is impacted too

**Comment by ncksllvn** [comment]
Ah I see! I suspect many of these will be roles for a CMS user to do, but many of these will be for FE devs...I don't want to create a whole bunch of work for you though to update the mockups. I wonder if we can get away with just updating the issue/Epic names on ZenHub lol

**Comment by andaleliz** [comment]
@ncksllvn hmmm, unless I'm missing something, I don't think there are any actions for CMS users to do. this would all be FE work/changes to the templates you guys are building.  Actually, mostly to the bread layers. 

this issue is to update the mockups to remove the word "learning center" from them, since the product is called "resources and support"

**Comment by jenniferlee-dsva** [comment]
LC ("support and resources") homepage intro and H1 will be entered by @RLHecht or @lunascoop /PW content team. So I think it would be helpful to them to have updated mockups before they start on that. 

I don't think there's a ticket yet for that task, I'll get that on our board now, for @brianalloyd to triage when to pull into a sprint. 

@brianalloyd we still haven't had our meeting regarding 1.0 release plan and timeline. Could we get that on our calendar soon, so we can figure out when all the steps need to happen by (for end of October - 29/30) beta launch?

**Comment by andaleliz** [comment]
The mural board has been updated to reflect the new product name.  The only thing I had to change that wasn't accounted for is the label on the collapsed version of search on mobile.  I changed the `Search the learning center`  to `Search resources and support` which butted up right against the icons on either side of the text.  

After adjusting the padding on the elements, and trying different phrases to keep vertical space to a minimum, I settled on `Search articles` for the label. I _think_ this is just as clear as `Search resources and support`.  Thoughts, @jenniferlee-dsva ?

**Comment by andaleliz** [comment]
@rtwell I added the [new Sketch file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/wip-files/VA-Learning-center-template-v3.sketch) to the wip folder too.

**Comment by jenniferlee-dsva** [comment]
Are we talking about inside the search bar, on mobile? Assuming that we are: `Search resources and support` would be clearer.

It is an unfortunate consequence that the new recommended name is longer, but we have to work with it. What if the text inside the search bar was not bold? Does that buy us some padding? 

Also, if the user toggles to the other option, I'm assuming that in mobile the text inside the search bar would need to change to reflect the radio button change -- "Search all VA.gov" correct?  If the text inside the search bar is supposed to be static for both states, that we should not reference either articles, support, or whatever, and just keep it `Search`. 

Also the radio button option should be `Search all VA.gov` - no "of." We do say that in the sentence above, but I prefer we be succinct in interface labels and not narrative-form. 

![image](https://user-images.githubusercontent.com/43381063/95460608-2d283280-0943-11eb-8c9d-89ed976bdad3.png)

**Comment by andaleliz** [comment]
@jenniferlee-dsva  I'm not sure what you're referring to here:
>Also, if the user toggles to the other option, I'm assuming that in mobile the text inside the search bar would need to change to reflect the radio button change -- "Search all VA.gov" correct? If the text inside the search bar is supposed to be static for both states, that we should not reference either articles, support, or whatever, and just keep it Search.

The text really shouldn't change between desktop or mobile, or if someone selects a different a radio button.

Here's the non-bold text. It looks odd to me, but possibly I've been staring at this too long:
<img src="https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/0e24bae6-2b21-4655-86da-3e14c03a473e" width="40%"  />

---

Here's an option with adjusted padding, 10px on each side. It technically breaks with our "increments of 8px"  that we have with a lot of our spacing, BUT we do have a lot of elements that have 20px of padding. I'll leave it to @rtwell to make the final call, as a member of the design system council and original designer of this pattern.

<img src="https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/366007c4-5d2d-427d-991b-d2156efca029" width="40%"  />

**Comment by ncksllvn** [comment]
Sorry I missed this and left you hanging @andaleliz . As far as updating designs based solely on the name change, if it's a lot of work to re-upload fresh designs/mockups based on the name change, I'm perfectly fine with the textual changed just being mentioned in the issue description or an MD file that outlines the template specs.

**Comment by andaleliz** [comment]
No prob @ncksllvn  - Jen asked me to go ahead with updates for the team.  It's faster to update mock-ups through UXPin or InVision, but still not a huge deal to manually update the Mural board :) Glad to do whatever is needed to help things go smoothly.

**Comment by rtwell** [comment]
i'm leaning towards dropping the left icon, mostly because when the search box is open, the close icon gets so close to the type and it blends in with its surroundings. Thoughts?

![image](https://user-images.githubusercontent.com/12564977/95911662-c5714d80-0d6f-11eb-8c02-fd3ae0241844.png)

**Comment by andaleliz** [comment]
There's part of me that is _a little_ concerned that without the magnifying icon this reads like less of a button, and people won't know it's clickable - but for the most part, I think this will work.  Definitely something we can evaluate in our next round of testing. I say we go with this!

@rtwell are you able to update the mural board with the final decision, or do you need me to?

**Comment by rtwell** [comment]
'tis already updated, i believe!

**Comment by andaleliz** [comment]
I only saw the `About` mobile screen updated - went ahead and copy pasted the update to the other screens. We should update the Sketch file too though in case those are needed in the future. 

Closing this out.
