### ISSUE TITLE
[Carryover] Remove data validation for user-requested 10-10CG PDF download

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#14287]
**Description**
At this moment we need a perfectly valid data payload to generate a PDF as an end-user. But if their data is invalid, or missing, we should consider giving them back a PDF no matter what. We should do a best-effort pre-fill of the PDF so that the user can get a PDF back even if one field is invalid.

Even returning a blank PDF is a better user experience than not being able to download a PDF because some field is invalid.

**Comment by tchrisdyer** [comment]
Added to Sprint 48 Epic
