### ISSUE TITLE
Remove Profile 2.0 feature flag mentions

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#14289]
## Description
Since we have rolled out Profile 2.0 to 100% of all users, we can now remove all logic related the feature flag/localStorage value.

This is ticket 1 of the steps to remove Profile 1.

Ticket 1 - Remove profile 2 feature flag
Ticket 2 - Identify dead code related to profile 1 and remove it
Ticket 3 - Reused code of profile 1 in profile 2 needs to be moved to the profile 2 folder && renaming of components/logic where needed

## Tasks
- [ ] Remove all gating from Profile 2.0
- [ ] Remove `cy.route('GET', '/v0/feature_toggles*', mockFeatureToggles);` from cypress test files

**Comment by sanlouise** [comment]
This was a technical cleanup, so there is nothing to validate on your end @mshea0606

**Comment by mshea0606** [comment]
ok thanks @sanlouise
