### ISSUE TITLE
Access for Tyler Snell

### ISSUE THREAD

**Issue by TS000** [department-of-veterans-affairs/va.gov-team#14281]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecelia Lee
- Please provide your name.
   > Tyler Snell
- Please Provide your email.
   > tyler.snell@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VA API - developer portal account management
Role: Senior Software Engineer
Company: AdHoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLdU5tErzHlbt9CB3JE0oUniQxfhAs7oK/OFbYzlzDY1xyT7YRUO++gnoIn28eVAMi7KVlPMMDHpk8TrUd8B+hDIW6mMnvFVfWzccMqgaCoGr1SaV4GuN9hIjCDKQPX+uPq6U8O2P20zBI7KKPr0BSpoKoN7QyAeCy5GLPAaHo3UrNtvH5xZgc1u1fmoZAHLJ26JCPBUyhFutXQXhuPLTkzCQD/frExu0KtO4i2TvYmOSpUckmeDctfZDyE+0Qfshkp3JPx9gzSNHfsyVEwwG3DTwE1D9XgH5JeuasNgeNEAPUar0FRs3S2lqje9amQmroWP3MS1bJrZc4/+tusXwRHcLyC13ZIOFQsip6bRQ3jaZxZetodShLkSHznXMYCfAtehBcWgYXJ2YPAe2g9kBl8ZByPBNlZCd6ruYjxt4iVmBKsTDEPsZH2fkikP8YYyh1jqNzuEMoxSMtNtG6NlcdTmNxP529HMBizzeS2uXchRCktvwwvh1FHcsWgp3hyoc= tylersnell@TylerSnlMacbook
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
> Need AWS Console access for developing and maintaining the Lighthouse dev portal.

**Comment by TS000** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
**Requesting approval for AWS Access**
User: Tyler Snell
COR: Cecilia Lee
cc: @Jeff-Hayter

**Comment by jsev-io** [comment]
Hello, @TS000 

SOCKS access granted. Please see this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) for getting configured.
Once you've confirmed access, please close this issue. Reach out for any help needed!

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by jsev-io** [comment]
Credentials provided to user.
