### ISSUE TITLE
Design feedback - Usability Testing Prep - eBenefits [CH36]

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#14283]
- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

**Must:**
- For chapter step section of forms, please use updated version in sketch library, we removed the circled numbers and replace it with a spelled out word, “Step 1 of 2 Claimant Information” (this was a recent change and it was changed for accessibility purposes)
- The font-weights of the headings are too light - increase the font-weight to match as shown on the [design system site here](https://design.va.gov/design/typography#headings)

**Should:**

- Make the entire expand/collapse on the Review & Submit page clickable, rather than just the + icon

**Consider:**

- No “consider” feedback at this time

**Definition of Done:**
- [x] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by jason-gcio** [comment]
These are addressed and/or completed.
