### ISSUE TITLE
[Engineering] - build LC Index and generate sitemap

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14291]
## Issue Description
_Build LC Index and generate sitemap as outlined_

## Front end tasks
TBD

## Acceptance Criteria
TBD

## Planning Considerations 
- Even if we build it, we still have to make it publicly consumable by search.gov _(Needs discussion)_
- Possible solution is for PW to send search.gov our sitemap that they can manually consume for us _(Solution Ideation)_

**Comment by kelsonic** [comment]
@ncksllvn do you know if this has been done already? No, right? 🙂

**Comment by ncksllvn** [comment]
Bc we have a client-side search instead of one powered by search.gov, we don't need to worry about this anymore.
