### ISSUE TITLE
[Discovery] - Steps for populating LC index for testing and prod? 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14290]
## Discovery 
Learning Center - How will we populated our index for Testing and Production environments? 

## Findings/Recommended Solution
_Action/Trigger_ #15153

**Comment by brianalloyd** [comment]
Decision - Can't have search.gov in staging or demo, needs to be live.  @johnhashva what does the search team need exactly to ensure indexing (sitemap and XML file).  Plan to submit files day prior to launch to support crawl functionality.

**Comment by johnhashva** [comment]
Per Carter Baxter, indexing lead at Search.gov:There is no way for Search.gov to index the content until it's available that wouldn't result in a ton of unwanted 404 errors in the index. We will have to have the site map and content available/accessible to the Search.gov indexer.  Their recommendation -- a soft launch approach (e.g. live in production, but no prominent links to the LC section) -- a few days prior to public launch.

**Comment by brianalloyd** [comment]
@johnhashva Thanks for the update, makes complete sense.  @jenniferlee-dsva want to link you in as well, this will be the planning considerations going forward as we work search/index items for LC.

**Comment by brianalloyd** [comment]
Closing this ticket as discovery and path have been defined.  `Action/Trigger` ticket is here #15153
