### ISSUE TITLE
Create Conversation Guides

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#1429]
## User Story
As a researcher, I need to create Conversation Guides to be used during User Research Interviews.  

## Goal
Create separate Conversation Guides for interviewing Veterans and Caregivers. 

## Acceptance Criteria
- [x] _What needs to happen or be created?_

Team needs to develop two separate documents containing questions posed during User Research Interviews. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)

Sprint 1

- [ ] **Attached to an Epic** (what body of work is this a part of?)

Conduct User Interviews

- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)

VSA Caregiver

- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

Research

- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

Discovery, Documentation

**Comment by jenstrickland** [comment]
Veteran and Caregiver Conversation Guides complete: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/research/discovery-aug-2019
