### ISSUE TITLE
Do not raise errors of MPI Search on caregivers for 10-10CG

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#14309]
**Description**:
No need to prevent a submission because of an error searching for the caregiver's ICN. It's non-required information for submitting to CARMA.

**Considerations**
- Add to logs the result or error for the MPI search vs logging "not found in MPI" which is misleading.

Relates to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14307

**Comment by hdjustice** [comment]
Closing this ticket - has not been addressed in over a year.  If work is needed, a new ticket will be created under an initiative
