### ISSUE TITLE
Update in-app web view: text resizing & share

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14304]
### Acceptance Criteria

1. Add text resizing to the top nav of the in-app web view 
     - appears before the Refresh button
2. Add a share button to the bottom nav of the in-app web view
     - appears before the Open in Browser button
     - Requirements needed: what should this do? (ex: messaging, airdrop, email, etc.?)

**Comment by bridgethapner** [comment]
Closing this in favor of a future ticket to rethink the web view component more holistically  -- this Common Component is on the list for refinements.
