### ISSUE TITLE
[Epic] LC Template Top and Bottom Layers - MVP 1.0

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14300]
## High Level User Story/ies
As a Veteran, I need a visual way to view a step-by-step process quick navigation to Tier 1 benefits tools and content.

## Scope
_This Epic will account for both top and bottom template layers. The layers should apply to all pages regardless of LC template e.g. step-by-step is the assumption_

## OKR
_TBD_

**Comment by jenniferlee-dsva** [comment]
Do we have a ticket for the` On this page` (aka TOC) links component? Sorry if I missed this one. It is listed in the product repo templates doc, but I don't always have 100% off the top of head recall. :-/ The reason I ask is that these links are enabled in the CMS, but the rest of the logic is all FE and I want to make sure to capture that. 

If not I can create one - I just don't want to create more dupes.

**Comment by jenniferlee-dsva** [comment]
1.0 completed. We iceboxed the rating layer till Medallia is ready, so we can tackle that as part of 2021 when Medallia pilot finishes.
