### ISSUE TITLE
Biometric login

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14305]
## Acceptance criteria
1. Add the option to use biometric app unlock after initial login
2. Include the ability to opt into it, if it's available

**Comment by bessgreen** [comment]
### Acceptance criteria

1. Add the option to use biometric app unlock after initial login
2. Include the ability to opt into it, if it's available

**Comment by bessgreen** [comment]
ready for AH review

**Comment by digitalken** [comment]
Tests:
1. Set up biometric data (finger print).
2. Verify option to use biometrics.
3. Verify app accepts biometric data and unlocks for use.

**Comment by digitalken** [comment]
(Question in to Brandon regarding flow and usage of biometric data in place of username / password login.)

**Comment by jjulian** [comment]
Does this ticket reflect all the decisions documented [here](https://docs.google.com/document/d/1FHtT1A0qbuteMV_sfSm2tzp4nGgZW_0cSaISt72WXRo/edit)? I'd like to document our biometric capabilities for stakeholders.

**Comment by digitalken** [comment]
Added to TestRail

**Comment by digitalken** [comment]
PASS 11/11/2020 - Android and iOS.  Moving to closed, no design to verify.  I understand there is going to be some new designs coming down the pipe soon as this current placeholder UI doesn't pass accessibility.

**Comment by digitalken** [comment]
Pass 1/20/2021 - Any issues in the future are issues with modifications. Original passes.  Closing.
