### ISSUE TITLE
[Content] BDD: Public Websites Update to BDD Information

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14322]
## Issue Description
On this page, there are a couple of minor changes needed as part of the BDD rollout.

https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/

1. Currently the 45 day exam requirement is way at the bottom and our stakeholders would like to move it up to the top.  Suggested wording and screen shot will be attached.

2. Need to have a VA exam done in a foreign country (except if the exam can be requested by the overseas BDD office in either Landstuhl, Germany, or Yongsan, Korea), or -> Changed to Camp Humphreys, Korea.

![image](https://user-images.githubusercontent.com/53824125/94957470-0a150300-04ab-11eb-82ec-8d8bc8fc9c2f.png)

## Acceptance Criteria
- [ ] Changes made on public BDD page

**Comment by jilladams** [comment]
Scrubbing old PW issues, and both these changes seem to have been made: 
<img width="842" alt="Screen Shot 2022-08-22 at 3 59 04 PM" src="https://user-images.githubusercontent.com/85581471/186033453-44a94bf4-8346-4633-bc67-fbcfa59ce3ad.png">
<img width="750" alt="Screen Shot 2022-08-22 at 3 59 41 PM" src="https://user-images.githubusercontent.com/85581471/186033457-5c2615c5-6a0c-4103-af42-87ecde7b45c1.png">

Closing.
