### ISSUE TITLE
Alter Rules to Align with New Rubric for Alerts on VSP 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#1432]
## User Story
As an Oncall engineer, I need to have clear rules that help conform and adjust to meet the new alerting rubric alerting.

## Goal
Have a clear list of rules so that all are on the same page when creating new alerts or changing old ones.

new Rubric: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/Monitoring%20Norms.md

## AC
- [ ] rules updated to adhere to new criteria

**Comment by wyattwalter** [comment]
I started an OnCall directory in the sensitive repo and migrated this list here. The list itself isn't sensitive, but my intent is to migrate all of the related documentation here. A lot of this info (like contacts) can't be shared publicly.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/OnCall

**Comment by wyattwalter** [comment]
Oops, I thought this was the other ticket linked. The rules are written, need to audit the existing list to make sure they all conform. I made a pass initially at some of the worst offenders, but we should be defensive by auditing the whole list.

**Comment by ricetj** [comment]
We will do this when we get to alerting in the Infra overhaul
