### ISSUE TITLE
[ZOOM]: Direct Deposit - Buttons for Update and Cancel scale unexpectedly at more than 250% zoom

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1433]
The `Update` and `Cancel` buttons scale unexpectedly at zoom rates above 250%. I'd expect them to retain the side-by-side relationship, but the Cancel button becomes full width. Screenshot attached at 400% zoom.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a user who zooms their browser in to 300-400%, I'd like the button controls on the direct deposit form to retain their existing layout *or* both be full-width.

## Screenshots or Trace Logs

<img width="1251" alt="Screen Shot 2019-08-29 at 12 27 45 PM" src="https://user-images.githubusercontent.com/934879/63962647-d4584c00-ca58-11e9-83cc-9b8d736c4f49.png">

**Comment by Justin-Pickett** [comment]
@tlei123 can you validate this has been fixed?

**Comment by tlei123** [comment]
@1Copenut  , feel free to just Close* this bug if you're satisfied with my new findings...

The **button-widths are now consistent on Staging** \[after styling bugfix [#19550](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19550)].

They're either both auto-width side-by-side, or both full-width vertically-stacked, depending on OS/browser \[see screenshot below]: 

<img width="1226" alt="staging-dd-update-btns" src="https://user-images.githubusercontent.com/587583/64302684-40472280-cf39-11e9-8564-d1d45507d4e8.png">
Note: Chrome's button-widths differ between Windows and Mac.

Let us know please whether you still need a fix.  I'm not sure whether you're thinking the buttons just should not change widths at all when zoomed-in.

Also attaching the actual screenshots here: 
[staging-dd-update-btn.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/3576926/staging-dd-update-btn.zip)

*If you still need a fix, then just keep ticket Open, add a Comment and Assign to @erikphansen 

Thanks much!

**Comment by 1Copenut** [comment]
I spot-checked a few browsers and all looks good. Moving to close.
