### ISSUE TITLE
Analytics Implementation or QA Support for VAOS

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#14331]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
QA

- Who is this request for?

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._

   - Tony Williams

- What team/project is this work for?
    _this adds context for the data_
    
    - VAOS
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
   No
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]
   None

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

   These are the GA tags needed:
  - vaos-video-home-number-of-cards
  - vaos-video-atlas-number-of-cards
  - vaos-video-va-facility-number-of-cards
  - vaos-video-gfe-number-of-cards
  - vaos-video-store-forward-number-of-cards   

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
Acknowledging receipt, @vbahinwillit.

I will message you Monday Oct 5 to schedule a quick meeting about this.

**Comment by bsmartin-ep** [comment]
@vbahinwillit / @jbalboni / @jonwehausen  -

I think our best bet is to move these `number-of-cards` values into their own event and use two generic dataLayer params / custom dimensions.  This should allow us to expand to any number of card types without needing to map out more custom dimensions.

How does this look to everyone?

```javascript
'event': 'vaos-number-of-cards-retrieved',
'vaos-card-type': 'video_whatever',
'vaos-number-of-cards': 2
```
You would want to...

1.  Remove the existing `-number-of-cards` stuff out of the `vaos-get-*-retrieved` events
2.  Clear out these values after the event:

```javascript
'vaos-card-type': undefined
'vaos-number-of-cards': undefined
```

And a general FYI, you will need a flat table Custom Report to report on these CDs in pairs.  Which we can build for you if you would like.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

QA this [GTM workspace](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000374)

Interaction|Data Layer|GA Tag
----|----|----
_VAOS items returned_|![image](https://user-images.githubusercontent.com/62304138/96462431-8de12600-11f3-11eb-99c9-63db85cdb7d0.png)|![image](https://user-images.githubusercontent.com/62304138/96462505-a3565000-11f3-11eb-97c0-f15e929b0248.png)

Publish this to staging in GTM, Jon?

**Comment by bsmartin-ep** [comment]
@jbalboni -

How annoying would it be to only fire those `vaos-number-of-items-retrieved` event if the count > 0?

We are trying to cognizant of our hit count in the long term.

Thanks!

(cc @jonwehausen)

**Comment by bsmartin-ep** [comment]
@jbalboni / @lenaecb -

As discussed, please disregard this request....
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14331#issuecomment-712237775

**Comment by bsmartin-ep** [comment]
@jonwehausen / @bmcgrady-ep -

Can I get a QA on this GTM workspace?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000374

**Comment by bmcgrady-ep** [comment]
## QA Testing

Description of Interaction | DL Screenshot | Test Status
------------ | ------------- | -------------
VAOS Number of Items > 0 | ![image](https://user-images.githubusercontent.com/66263904/96775607-9a54b280-139c-11eb-8515-c2d4a7ffa9dc.png) | ✔️ **PASS**
VAOS Number of Items = 0 | ![image](https://user-images.githubusercontent.com/66263904/96775676-b8baae00-139c-11eb-9233-2ecbba19449c.png) | ✔️ **PASS**

**Comment by bsmartin-ep** [comment]
Thank you @bmcgrady-ep .

This GTM workspace has been published @lenaecb , @vbahinwillit , @jbalboni .

I should be able to run some sample queries tomorrow.

**Comment by jonwehausen** [comment]
Closing for implementation - refer to #14192 for dashboard-related updates
