### ISSUE TITLE
[Epic] LC Template Top and Bottom Layers - MVP 1.1

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14337]
## High Level User Story/ies
As a Veteran, I need a visual way to view a step-by-step process quick navigation to Tier 1 benefits tools and content.

## Scope
_This Epic will account for both top and bottom template layers for MVP 1.1. The layers should apply to all pages regardless of LC template e.g. step-by-step is the assumption_

## Bet
_The design of the learning center pages should make it easy to navigate and find information for primary users and caregivers. Visuals add to the UX and ease the process for visual learners._

## OKR
_TBD_

### What must be true in order for you to consider this epic complete?

**Comment by jenniferlee-dsva** [comment]
Hello - I am not sure which ticket/s to comment on, as this is more global and pertains to the order in which these layers should be displayed in the FE.  The order that the bottom layers should be displayed is - screenshot:

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/0f83456d-077f-4f55-a29f-58a6ae462367)

1. Tags
2. Rating
3. Related information
4. VA benefits
5. Need more help

On this preview, the `Related information` section is appearing below the `Need more help`: 
http://preview-prod.vfs.va.gov/preview?nodeId=8417

**Comment by jenniferlee-dsva** [comment]
^ @ncksllvn @kelsonic

**Comment by jilladams** [comment]
All tickets complete, feedback from 10/19/20 is outdated in live site. Closing.
