### ISSUE TITLE
[FE] Build 'Benefit Hubs' LC page component

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14330]
## Issue Description
_LC 1.0 build for "benefit hubs page component_

User story: As a Veteran, I always want an easy way to go to the relevant benefit hub from any article. 

## Front end tasks
TBD

## Acceptance Criteria
- [ ] Section is showing in the correct layer order
- [ ] Section header is styled as an H3, using H2 element
- [ ] Can be validated against this test node: http://preview-prod.vfs.va.gov/preview?nodeId=7910

## Planning Considerations 
- FE Bottom Layer component build. 

## Requirements - VA benefits component
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#va-benefits-section

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/b4e56cb6-fe5f-4c3f-895e-6f064c0b21a0)

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/14711

**Comment by jenniferlee-dsva** [comment]
Validated and closing
