### ISSUE TITLE
Sample content for 'Benefit Hub' LC Component 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14335]
## Issue Description
_Need sample content for 'Benefit Hub' LC 1.0 Component_

## Planning Considerations
- ~Need content for all hub~s [We don't need to input this - it is auto generated in the CMS]
- ~Blocked by being available in CMS~ (Need to validate timeline with CMS) <-- I believe this component is now available in the CMS/JL.

## Requirements/description about this component in LC
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#va-benefits-section

**Comment by jenniferlee-dsva** [comment]
Adding @RLHecht so she can coordinate timing with Kelson/Nick so this sample content is ready for them to test FE. This component is already ready in the CMS.

**Comment by jenniferlee-dsva** [comment]
This work is blocking FE work for ticket #14330

**Comment by RLHecht** [comment]
@kelsonic @ncksllvn Here is a node with Benefit Hub info: prod.cms.va.gov/node/6898 Let me know if you need anything else.

**Comment by kelsonic** [comment]
Awesome, thank you! 🙂

**Comment by RLHecht** [comment]
I think this ticket can be closed but want to confirm with @kelsonic

**Comment by kelsonic** [comment]
Yupp! Good to close! Thanks! 🙂

**Comment by brianalloyd** [comment]
Thanks @kelsonic and @RLHecht.
