### ISSUE TITLE
[FE] Build 'Tags' LC bottom page component

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14332]
## Issue Description
_Build 'Tags' LC bottom page component_

## Design

![image (1)](https://user-images.githubusercontent.com/12773166/96480346-5c6a5980-11f7-11eb-9441-aaa5aaaaa528.png)

## Front end tasks
1.0 tags will be:
- Sign in
- Claims and appeals status
- Payments and debt
- All Veterans

## Acceptance Criteria
TBD

## Planning Considerations 
- Build should factor in Audience + content themes as discussed in grooming/planning

**Comment by brianalloyd** [comment]
@ncksllvn and @kelsonic please provide an estimate.  If we have bandwidth we could add to this sprint, otherwise slated for next sprint.

**Comment by jenniferlee-dsva** [comment]
Per Ryan's slack comment: https://dsva.slack.com/archives/C0173CAJ7A6/p1603309729419200?thread_ts=1603306717.408100&cid=C0173CAJ7A6

>additionally, Tags are plain ol’ Source Sans @ default size, no bold, no nuthin’

**Comment by jenniferlee-dsva** [comment]
Reporting possible bug - please see slack. It might be a CMS bug, but it could be FE - hard to tell: 
https://dsva.slack.com/archives/C0173CAJ7A6/p1603374439437800

**Comment by kelsonic** [comment]
PR is open to add beneficiary tags as well 🙂 https://github.com/department-of-veterans-affairs/vets-website/pull/14670

**Comment by kelsonic** [comment]
PR merged: https://github.com/department-of-veterans-affairs/vets-website/pull/14670

**Comment by jenniferlee-dsva** [comment]
Validated and closing

**Comment by jenniferlee-dsva** [comment]
opening a separate ticket re mobile bug
