### ISSUE TITLE
[Design] 'Back to Top' link LC 1.1

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14340]
## Issue Description
_Design considerations for 'Back to Top' link for LC 1.1 roll out_

## Planning Considerations 
- Refer to style guide and latest version of Mural mock ups.

**Comment by jenniferlee-dsva** [comment]
The design has already been completed by @rtwell . We only need to build the FE logic. I created a ticket combo design+ FE effort but can't find it anymore. Did you by any chance close it? @brianalloyd

**Comment by jenniferlee-dsva** [comment]
My bad - I found my original ticket:
 https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13646

Nice to have for 1.0; required for 1.1.  - It would be great going forward to not lose the og ticket Brian, so we don't lose og AC requirements and comments. (As you see - even I forget!)

**Comment by brianalloyd** [comment]
Thanks Jen, agree, lessons learned for sure. Closing this out as I combined work flow with #14347 and ensured notes we're matched in support.
