### ISSUE TITLE
Unexpected error: Network error

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14351]
## User Story

As a user, when there is a network error, I want to see an error message that clarifies what is happening.

**Comment by bridgethapner** [comment]
Generic error screen - can't connect to network, API returns 500, etc

**Comment by bridgethapner** [comment]
- Determine language here - can the user do anything? 
- Define the scenarios this specific error story is covering

**Comment by bridgethapner** [comment]
Design: https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/437850383_Generic_App_Error

My understanding is that we need a blanket generic error for things like no connection scenarios, but I don't understand 100% exactly **all the scenarios** of when this error would appear. @lexicalninja Wondering if you can take a look at [what I've designed](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/437850383_Generic_App_Error) & provide any insight: 
- Based on what you know about when this error may render, would you recommend changing anything?

**Comment by bridgethapner** [comment]
Bridget / Patrick sync on 11/16: 

- This will capture the use case of no network connection
- Patrick to do some research to figure out how to best do this in React Native

**Comment by lexicalninja** [comment]
This can be done by updating the api to catch errors around the fetch call.

api errors are caught within the response block, but network/connectivity errors show up in the catch block of a fetch request. 

the api wrapper in the app will need to be wrapped in a try catch and the system will need to track that state and display something appropriately

**Comment by bridgethapner** [comment]
Thanks for this context @lexicalninja. UI is done & this is ready for front-end work in a future sprint.
