### ISSUE TITLE
Small typo in alert on How to Apply EDU page

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#14359]
## What happened?
Noticed a small typo in an alert on the how to apply EDU page, when logged in. There is a missing space between `your` and `application` in the third sentence.

![image](https://user-images.githubusercontent.com/55992116/94959167-b90f0a00-04be-11eb-9b2c-68866120e6db.png)

Might be worth a quick search for instances of yourapplication in the code,  just in case it was copied and pasted from elsewhere?   I assume the eligibility page would have the same react widget, and thus the same error (and get fixed when this is addressed)

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://staging.va.gov/education/how-to-apply/, I assume this is in production too but don't have a production login to validated

## Desired behavior
there should be a space between words.

## Acceptance Criteria
- [ ] _the alert reads `your application` instead of `yourapplication`_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by andaleliz** [comment]
Per @Mottie :
>The ApplicationStatus component is where the "yourapplication" problem exists, here is the problem - https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/save-in-progress/ApplicationStatus.jsx#L135-L136 - these two lines need to be combined into one line:
src/platform/forms/save-in-progress/ApplicationStatus.jsx:135-136

**Comment by ncksllvn** [comment]
Thanks Liz, opened a PR, https://github.com/department-of-veterans-affairs/vets-website/pull/14508

**Comment by ncksllvn** [comment]
Should be live now
