### ISSUE TITLE
Parity check on vets.gov word list with VA style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#1435]
## Status
**[2024-05-16]** Messaged Randi H in [Slack](https://dsva.slack.com/archives/C01K37HRUAH/p1715883557289299) asking if we can close this ticket 
**[2024-04-24]** Comment added with tag to R Hecht to see if this ticket can be closed or is still viable.

## User Story
Platforms documentation points readers to both a [Vets.gov word list](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/list-of-terms-to-lowercase.md) and the [VA.gov style guide word list](https://design.va.gov/content-style-guide/word-list) to call out certain terms and words that should not be capitalized on VA.gov. There should be only one source of truth for VA.gov style, so the Vets.gov list should be retired and relevant terms incorporated into the style guide.
 
## Goal
Review the Vets.gov word list and determine if information is accurate. If there are words and terms that are on the Vets.gov list that are not listed in the style guide and continue to be relevant, they should be added. The Vets.gov word list should be retired from Platforms documentation.

## Acceptance Criteria
- [x]  Update style guide with relevant words/terms from Vets.gov list
- [ ]  Retire Vets.gov word list from Platforms documentation

**Comment by RLHecht** [comment]
@jenniferlee-dsva Here is a Word doc with all the words/terms from Vets.gov that are not currently in the style guide. I put comments next to each of whether we should add it and some other questions. Let me know when we can go over it. Then I can start adding them into the Style Guide so we can get rid of the other list. [https://app.zenhub.com/files/133843125/06a5af67-d45e-4c21-9802-8a8764ca719b/download](https://app.zenhub.com/files/133843125/06a5af67-d45e-4c21-9802-8a8764ca719b/download)

**Comment by jenniferlee-dsva** [comment]
@RLHecht - thanks Randi. I'll take a look and reach out to you, so we can go over questions.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I've added all the entries we discussed from Vets.gov to the VA.gov style guide. Here is the PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/141

I know we are discussing a few of these terms at the content weekly and there are still a few you are checking on (Disability Benefits Questionnaires, Fully Developed Claim).

**Comment by Karak888** [comment]
@Karak888 to look into whether or not this is included in an already existing epic.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I've updated this to put in the terms we discussed on the content weekly call yesterday. Please let me know when you've found out about Disability Benefits Questionnaires and Fully Developed Claim).

**Comment by Karak888** [comment]
waiting for @jenniferlee-dsva  review and following up on a few terms to see if we should be adding them.  ^^^

**Comment by Karak888** [comment]
@jenniferlee-dsva will follow-up to validate.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - Sorry this has been on me to follow up on. Is it possible for us to go forward with what we know, and leave out/omit the terms that I still need to get SME feedback on?  (I believe Aid and Attendance was one; I don't remember if there were others...)

**Comment by RLHecht** [comment]
Thanks, @jenniferlee-dsva I took out the A&A entry for now. The other two to follow up on are Disability Benefits Questionnaires and Fully Developed Claims. 

Do you want to review the rest of the PR and we can merge if all are good? Here's the new one after Kevin restored it for us: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/144

**Comment by RLHecht** [comment]
All terms except for three have been added to style guide. New ticket [#3748](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3748) created to continue work. Closing this issue. @Karak888

**Comment by RLHecht** [comment]
@jenniferlee-dsva I just discovered that the PR for this was never merged with a lot of the edits to the word list. Here's the PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/144

These were all words that we discussed from the vets.gov list and whether they should be incorporated into the style guide. This is separate from the appeals list we were working on.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - this was the PR that kevin h. accidentally merged when it was still being worked on. is it okay to merge as is?  i.e., are we sure it won't overwrite the more recent changes we merged?

**Comment by RLHecht** [comment]
@jenniferlee-dsva I went through the PR again and updated some entries and made a few more corrections. This can obviously wait till the new year but just commenting so I don't lose track of it.

**Comment by RLHecht** [comment]
You can close this, @FranECross. Thanks!
