### ISSUE TITLE
Expected error - Generic default message

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14352]
## User Story

As a user, I want to see an error message if one of the features in the app is not performing as expected.

**Comment by bridgethapner** [comment]
Next steps: 
- What area of the app could this apply to and what language should we use to communicate the error?
- Work sessions

**Comment by bridgethapner** [comment]
All app errors would only be unexpected / all APIs errors ARE expected (we can plan for them) and are covered in other tickets
