### ISSUE TITLE
[Build] “Need more help” / IRIS replacement web intake form LC 1.1 FE Only

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14350]
## Issue Description
_Build “Need more help” / IRIS replacement web intake form LC 1.1 ***FRONT END ONLY**_

## Front end tasks
TBD

## Acceptance Criteria
TBD

## Planning Considerations 
- Not sure when this will be available (might be post 1.0)
- This is a FE only work

**Comment by brianalloyd** [comment]
Bot Team not ready for this implementation.

**Comment by kelsonic** [comment]
Update on this ticket? Can we close or still relevant? CC @brianalloyd

**Comment by brianalloyd** [comment]
Closing in support.
