### ISSUE TITLE
Access for Eric Boehs

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#14361]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Eric Boehs
- Please Provide your email.
   > eric.boehs@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > - VSP
   > - I'm a Senior Software Engineer on the VSP/BE Tools team
   > - I work for Oddball.

- Requesting SSH key authorization?
> Yes
   - What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLQVhVaSc1pMHuPdLOmiDITD920VB2YR7AMr1kGEBkpSPBzce2z6JJYPYnzeURZ+MyLaLLP6WP7RR+6GdTF65BGdW5ehq+SDryAzCJLE6rOarR7PnheWOUDY+AuzQ9EF0PHPcQybVf+samaj56o3rjushmaCL2Pv8KNLJwI33AyNnbIoUdGCGotQtwY3k1W1hCDO6YGBLcwjhn/ALLfzU8AnCHuqOCYMXUkOVelJ0IOZNfTj5vFBZlccvVi72rRIux2FrPOHxFfQC5C5Y9qpGPQ7s8mSOsvuWlbJSCaMjk5zbNxzTQjgCrMPrCABVGYsP3NW6bw/W+QvD8KDAEWheBHyd4gCNAu5brBiqTwNDrmXUxW4hW4GVFkAJlvj2As5eTTxiiaKpBRXaELPkifQAqzPLlRJCgZNeC8gymyRCSD96gxv6/bcS6RhWOXxlVBywUGdHnvmrYb/E4tNSx8mI1blpuf7mFtSfB9+ghVoOzuTh0Yj090ehwbkB0Ev13gbE= ericboehs@Erics-13.local
```

- Grant AWS Console access?
> Yes
  - What AWS services do you need access to and why? 

> I will be working on backend tools and collaborating with devops. For example, I'm currently helping with upgrading to Sentry 10 and we're debugging container-to-host port mappings which are not properly configured in our ansible/tf templates.

**Comment by ericboehs** [comment]
Hello @department-of-veterans-affairs/vsp-operations, I'm looking to get SOCKS/AWS access, please kindly. 🙂 My e-QIP adjudication is under way.

**Comment by jsev-io** [comment]
@ericboehs Please verify that you have access to the SOCKS proxy when you have a moment.

**Comment by jsev-io** [comment]
**Requesting AWS Access**
User: Eric Boehs
cc: @Jeff-Hayter

**Comment by ericboehs** [comment]
@jsev-io I do have SOCKS access now, thank you!

When will I receive the AWS login url/temp password? cc: @Jeff-Hayter

**Comment by jbritt1** [comment]
Looks like your user was made, but you weren't yet given first time login credentials. Sorry about that. Will get that to you momentarily.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
