### ISSUE TITLE
Content for Direct Deposit Landing Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14367]
## Background
The existing direct deposit page (https://www.va.gov/change-direct-deposit/) needs an EDU DD version

## Considerations
- Do instructions for use need to change?
- Work with public websites to figure out if we need only one CTA to the profile now. We probably don't need two sections and two dynamic widgets.
- If we only need one dynamic widget, we should make sure the copy in the existing one is benefit neutral. I *think* it is, which would make our lives easy. Just for reference, there are four states of this widget:
  - A prompt to sign in if you are logged out
  - A prompt to verify your identity if you are LOA1
  - A prompt to add 2FA if you don't have it already
  - A prompt to go to your profile if you are signed in, LOA3, and have direct deposit set up
- Given that we probably don't need to have two sections for comp & pen and edu benefits, there will need to be some copy updating to clean things up and make sure the content we have makes sense.

## Tasks
- [x] Using existing landing page content, create a dedicated, initial landing page mockup for EDU DD

## Acceptance Criteria
- [x] Mockups is created and shared with Auth Exp

**Comment by jason-gcio** [comment]
Hold for feedback that may come from Design Intent Collab scheduled for Friday, October 16, 2020 at 2 pm ET

**Comment by Samara-Strauss** [comment]
This got mentioned in the design intent collab session today, so I wanted to add more notes here on what we'll need to do:

- Work with public websites to figure out if we need only one CTA to the profile now. We probably don't need two sections and two dynamic widgets.
- If we only need one dynamic widget, we should make sure the copy in the existing one is benefit neutral. I *think* it is, which would make our lives easy. Just for reference, there are four states of this widget:
  - A prompt to sign in if you are logged out
  - A prompt to verify your identity if you are LOA1
  - A prompt to add 2FA if you don't have it already
  - A prompt to go to your profile if you are signed in, LOA3, and have direct deposit set up
- Given that we probably don't need to have two sections for comp & pen and edu benefits, there will need to be some copy updating to clean things up and make sure the content we have makes sense.

**Comment by sporeboy** [comment]
Initial pass at landing page content revision here: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/72860e86-bed9-4e10-8794-223ebb03794f

- Only one CTA
- EDU payments language consolidated with Comp & Pen; just one section
- Sign-in widget is standard; no revisions needed
- Remaining copy left as is

**Comment by Samara-Strauss** [comment]
This looks good to me! No additional suggestions before reviewing with someone on the content team.
