### ISSUE TITLE
1995: Update form breadcrumbs and title

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14365]
As a developer, I need to update the 1995 title and breadcrumbs so that it matches DEPO patterns and practices to provide the veteran with a consistent user experience.

## Assumptions:
1. This work will go directly to production due to breadcrumb update.

## Acceptance Criteria
1. On the introduction page the "Manage your education benefits" header is replaced with "Change your education benefits".
2. On the form pages the "Update your education benefits" header is replaced with "Change your education benefits".
3. The breadcrumb of the 1995 is: `Home > Education and training > Change your GI Bill school or program > Change your benefits VA Form 22-1995`
    a. "Home" url: https://www.va.gov/
    b. "Education and training" url: https://www.va.gov/education/
    c. "Change your GI Bill school or program" url: https://www.va.gov/education/change-gi-bill-benefits/
    d. "Change your benefits VA Form 22-1995" url: https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction

## Supporting Artifacts:
1. Originating story: #14089

**Comment by ccruzgra** [comment]
@dneel-bah Do you know what the mobile breadcrumb should be? "< Change your benefits VA Form 22-1995"?

**Comment by dneel-bah** [comment]
@ccruzgra I do not; it was not mentioned in the originating story #14089 as being different than what was provided / how the platform handles mobile breadcrumbs by default.

**Comment by amyknox** [comment]
22-1995 mobile breadcrumb: < Change your benefits VA Form 22-1995

**Comment by elder-joseph** [comment]
Related PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14579

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-10-15 at 10.15.38 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4709160f-2a4b-4f38-aee9-a156889a0e4a)

---

![Screen Shot 2020-10-15 at 10.15.51 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e1bf419d-b492-4d9d-a094-3ddba182d01b)

---

![Screen Shot 2020-10-15 at 10.16.04 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/5f092bd1-6106-4ff0-87e1-15faf078609a)

---

![Screen Shot 2020-10-15 at 10.16.15 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a1e8fb5e-d98c-474b-a2b7-43dfc51f7575)

**Comment by delli-gatti-michael** [comment]
Testrail test case
https://dsvavsp.testrail.io/index.php?/cases/view/1023

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
For the breadcrumbs, is the dash ( - ) supposed to be included between the 22 and 1995?  

![Screen Shot 2020-10-19 at 11 39 23 AM](https://user-images.githubusercontent.com/36964225/96473643-e61e2500-11ff-11eb-91d3-6acf335fcc5e.png)

**Comment by elder-joseph** [comment]
Hey @JenLJ for this change I actually supplied:

```
        {
          "name": "Change your benefits VA Form 22-1995",
          "path": "education/apply-for-education-benefits/application/1995/introduction"
        }
```
which included the dash, to override that breadcrumb. 
We supply values to `breadcrumbs_override` which gets rendered. It appears that on dash is getting stripped out as its rendered.

**Comment by JenLJ** [comment]
@elder-joseph Thanks for providing!  For the non-dev, any idea why the dash isn't getting stripped out of the breadcrumb on this page?  https://www.va.gov/find-forms/about-form-22-1990/

**Comment by JenLJ** [comment]
UX Review 1/2:  Given the conversation above, this checks out for me

**Comment by amyknox** [comment]
UX Review 2/2: Checks out for me. 
Although I'm also curious why it's not getting stripped on https://www.va.gov/find-forms/about-form-22-1990/

**Comment by delli-gatti-michael** [comment]
Closing this out
