### ISSUE TITLE
School Ratings: Only display school ratings if a school has a minimum number of school ratings.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14370]
As a comparison tool user, I want to see institution ratings that have been rated by multiple users, so that I can get a better understanding of other student's experience at that institution.

## Assumptions:
1. This work is completed behind feature flag `gibct_school_ratings` created in #13359.
2. A valid rating is a rating that has at least one category rated by the rater.

## Acceptance Criteria
1. The minimum number of valid ratings for display of ratings information is 5.
    a. This number is configurable so that it can be changed as necessary.

2. On the search results page:
    a. If the institution has the minimum number of valid ratings, the composite average is displayed on the card.
    b. If the institution does not have the minimum number of valid ratings, "Not yet rated" is displayed

3. On the profile page:
    a. If the institution has the minimum number of valid ratings, the composite average is displayed in the header.
    b. If the institution does not have the minimum number of valid ratings, no ratings information is displayed in the header.
    c. If the institution has the minimum number of valid ratings, the school ratings accordion is displayed.
    d. If the institution does not have the minimum number of valid ratings, the school ratings accordion is not displayed.

4. The page matches the layout and structure as specified:
    a. In Supporting Artifact # 1 when viewed on a desktop device
    b. In Supporting Artifact # 2 when viewed on a mobile device

## Supporting Artifacts:
1. [Prototype - GIBCT School Ratings v0.5 - Desktop](https://bahdigital.invisionapp.com/share/HQIAEWSBGFU#/screens/296049140) as of 10/05
2. [Prototype - GIBCT School Ratings v0.5 - Mobile](https://bahdigital.invisionapp.com/share/NCIAEWUAYDS) as of 10/05
3. [Content-doc-v0.5.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/eea8b38d5d9fd91ee5ab70399e7f9b6281b29231/products/education-careers/school-comparison-tool/school-ratings/design/content-doc-v0.5.md)  as of 10/05

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14564

**Comment by delli-gatti-michael** [comment]
Added the following test data to the existing rating file:

[COLLEGE OF CHARLESTON
](http://staging.va.gov/gi-bill-comparison-tool/profile/11929140)- 5 ratings by the same user

[OHIO STATE UNIVERSITY-MAIN CAMPUS
](http://staging.va.gov/gi-bill-comparison-tool/profile/11513535)- 4 ratings from different users

[LOUISIANA STATE UNIVERSITY-BATON ROUGE
](http://staging.va.gov/gi-bill-comparison-tool/profile/11800118)- 5 ratings from different users

**Comment by delli-gatti-michael** [comment]
Tested by the following TestRail test case
https://dsvavsp.testrail.io/index.php?/cases/view/1018

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by amyknox** [comment]
Approved 1/2

**Comment by JenLJ** [comment]
UX Review 2/2 - This looks good!

**Comment by delli-gatti-michael** [comment]
Closing this out
