### ISSUE TITLE
Create automated regression test of the 10-10CG form

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#14377]
**Description**
Doing regression tests on staging takes a lot of time and we often miss scenarios that have failed in the past. Since QA can't be multi-tasked, we have one or more people on our team either (1) doing QA and pushing other priorities to the side, or (2) skipping QA to tackle more urgent issues.

**Proposal**
We should write a script to walk through the form, step by step, using different scenarios, in order to identify issues when they come up.

**Comment by tchrisdyer** [comment]
Closing, can be accomplished with QA and manual regression testing.
