### ISSUE TITLE
Enter content for 1.0 LC homepage 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14376]
## Enter content for 1.0 LC homepage 

**User story:** As a Veteran, if I land on the LC homepage, I want to be able to orient myself and know high level what I can find or do with the LC. 

**User story:** As a FE engineer, I want to know what content fields and data I need to pull from the CMS to create the FE template for the 1.0 LC homepage.

[LC homepage requirements in product repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/LC-homepage-requirements.md)

See [ticket #14280](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14280)  to coordinate with Liz on when you need updated mockups for entering content. (That ticket also has a list of what the text updates are, but might be hard to track what's changing and what's not.) 

**Page with sample content: prod.cms.va.gov/node/8296/**

Content ACs: 
- [x] Latest H1 and intro text are entered into the CMS LC "landing page" template. (Check with Liz - she will be updating latest text changes on the Mural mockups.) 
- [x] Latest LC categories are showing. 
         -VA account and profile
         - Other topics and questions
- [x] Curated 5 articles for each category are displaying. ( @bethpottsVADEPO to determine final 5 each for 1.0 )

ETA needed by: 
Defer to @brianalloyd on timing. However we'll need this done in order to work on the FE template.

**Comment by jenniferlee-dsva** [comment]
Confirming here that this is ready in the CMS. @RLHecht - the template to use for the LC homepage is the "landing page" template; and the 'list of links' component is where the top 5 list of articles for each category + go to all articles link are entered. (We don't currently have the go to all articles landing page URL, but the placeholder text can be added already.)

This 1.0 mvp Epic has a description, and you can check in with @andaleliz regarding the final design showing updated LC name. 

I don't think @bethpottsVADEPO is ready to finalize the final/real list of what articles should be used to display on the homepage, but we can use the test articles for now, so Nick/Kelson can start building the FE template. 

LMK, happy to hop on a quick call.

**Comment by brianalloyd** [comment]
@RLHecht can you estimate once reviewed.

**Comment by RLHecht** [comment]
I added sample content to the LC landing page based off the design for the page in Mural. The link is at the top of the ticket. A few things:

1. The template let me enter more than five articles (I put in six). It isn't giving me a way to remove any without deleting the whole content block.

2. I'm unclear what the "final link" is. Should I be entering the five articles in the regular link section or four and then the last one in that final link component? <img width="755" alt="Screen Shot 2020-10-09 at 4 32 50 PM" src="https://user-images.githubusercontent.com/48728214/95628986-153cd580-0a4d-11eb-8a85-3cba5eaa6b02.png">

2. Is the "Go to more articles" link automatically created at the end of the list? 

3. Drupal wasn't letting me search for any of the sample content nodes I created when looking for URLs. Is this because the nodes haven't been published yet? Because of that I just entered random nodes from the tier 1 content. Will this be an issue when we want to build the page with real contentl if we haven't published the other nodes yet? 

FYSA @oksana-c @jenniferlee-dsva @bethpottsVADEPO

**Comment by jenniferlee-dsva** [comment]
@RLHecht  - RE your Q #4 - Oksana confirmed that that Linkit functionality is missing in the lc homepage template. They will add it via this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3176

Could you please stay in close touch with her, so you can add node links as soon as it's enabled in the CMS?

**Comment by RLHecht** [comment]
I've updated the list of links so they are now five and the final link is for more articles.

**Comment by jenniferlee-dsva** [comment]
The CMS ax is missing a requirement (ability to add an optional info alert) - have flagged this for Oksana here: https://dsva.slack.com/archives/C0173CAJ7A6/p1602868726350800

**Comment by jenniferlee-dsva** [comment]
@brianalloyd - this is no longer blocked by cms linkit functionality/bug which has been resolved. The FE build can move forward. I didn't see a ticket or epic for that so will make one for the board.

**Comment by jenniferlee-dsva** [comment]
Related FE ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14996

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva, here are 8 out of 10 topics to be featured on the home page. Below this I’ve listed the other articles for you to look at SEO for to determine the remaining 2 articles.

 **Other topics and questions**
1/ How to check your VA claim or appeal status online
http://preview-prod.vfs.va.gov/preview?nodeId=8520

2/ What your claim status means
http://preview-prod.vfs.va.gov/preview?nodeId=8548

3/ What you can learn from the claim status tool
http://preview-prod.vfs.va.gov/preview?nodeId=8528

4/ TKTKTK


5/ TKTKTK


**Account and profile**
1/ Signing in to VA.gov 
preview-prod.vfs.va.gov/preview?nodeId=8222

2/ Change your address on file with VA 
preview-prod.vfs.va.gov/preview?nodeId=8473

3/ Use direct deposit to receive your VA benefit payments 
preview-prod.vfs.va.gov/preview?nodeId=8423

4/ How to change your direct deposit information for VA education benefits
preview-prod.vfs.va.gov/preview?nodeId=8474

5/ How to change your direct deposit information for disability or pension 
preview-prod.vfs.va.gov/preview?nodeId=8434


**Need SEO on these:**
Toll-free phone numbers for help with your benefits
Commissary and exchange privileges
How can I find a VA facility?
Veteran Identification Card (VIC)
How do I get my discharge upgraded or changed?
What’s VA's policy regarding service dogs?
What if I’m having trouble opening a PDF on VA.gov?

**Comment by jenniferlee-dsva** [comment]
@bethpotts - your list of acct/profile articles lgtm. 

RE the articles you wanted SEO data on, the `commissary `topic had the highest MSV, but you would need to add "VA" to not dilute competetiveness with commissary queries for military and branch-specific results. Next strongest MSV topic is `service dogs`. The PDF trouble topic had no relevant organic searches. Find a facility had none as well.  Since facility locator is well surfaced all over our site, I recommend not including the 'find facility' article in the homepage 5 list. 

**Toll-free phone numbers for help with your benefits** 

> Recommend adding “VA” – like “VA phone numbers” for SEO, omit “toll free” as that dilutes the strength of the phrase “VA phone numbers”; “va benefits phone number” 2,400 MSV; “va education benefits phone number” 1,900 MSV; “va education phone number” 1,900 MSV; “va gi bill phone number” “1,600 MSV; “va disability phone number” 1,300 MSV; “va claim status phone number” 720 MSV; “va claims phone number” 480 MSV


**Commissary and exchange privileges**  

> Recommend adding “for Veterans” for SEO; and to help distinguish this in organic searches from queries for military commissary and PX. “Commissary” 135,000 MSV; “px exchange” 27,100 MSV; interestingly, “vhic card” and variation come up as a related search term with ~4,000 MSV

**How can I find a VA facility?**

> Tried several variations, none of them brought up any related organic search terms being searched on. ("how can i find a va facility" 0 msv; "how find a va facility" 0 msv; "find a va facility" 0 msv. Did not check internal site searches. "va facility" brought up several related organic search terms but nigh high MSV (in the hundreds and lower); ex: "is the va open today" 390 MSV; "when does urgent care open" 590 msv; "who can use the va hospital" 320 msv. A lot of queries had to do with Virginia. 


**Veteran Identification Card (VIC)**

> How do I get my discharge upgraded or changed? 

> “honorable discharge” 6,600 MSV; “types of military discharge” 2,900 MSV; “military discharge” 1,900 MSV; “how to upgrade” 1,000 MSV

**What’s VA's policy regarding service dogs?**

> Recommend using “service dogs for Veterans”; researching related phrases for VA + service dogs: “how to get a service dog” 8,100 MSV; “ptsd service dog” 3,600 MSV; “service dogs for veterans” 2,900 MSV; “dogs for veterans” 1,000 MSV; “service dog for depression” 1,300 MSV; “service dog application” 880 MSV;  “service dogs for veterans with ptsd” 590 MSV


**What if I’m having trouble opening a PDF on VA.gov?** 

> no relevant search terms. All the phrases that came up as ‘related’ were queries for specific forms (e.g., “va aid and attendance application pdf”) - Did not check internal site searches.

**Comment by jenniferlee-dsva** [comment]
**SEMRush export report:** 
[VA_consolidated-phrase_related-us-1.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5423917/VA_consolidated-phrase_related-us-1.xlsx)

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva thanks! We'll go with the commissary article for sure. Haven't yet heard back with a SME thumbs up from Jeff and Jenny re: service dogs, so I'm going to pull in the VIC one instead. If we can swap it out for service dogs Friday or Monday, we will. Would be really fun to have an article about dogs on our home page!!

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva After our convo today, here are the titles... giving you one more look-see before @RLHecht loads the nodes.

 **Other topics and questions**
1/ How to check your VA claim or appeal status online
http://preview-prod.vfs.va.gov/preview?nodeId=8520

2/ Commissary and exchange privileges
http://preview-prod.vfs.va.gov/preview?nodeId=8490

3/ Veteran Identification Card (VIC)
http://preview-prod.vfs.va.gov/preview?nodeId=8498

4/ Helpful VA phone numbers
preview-prod.vfs.va.gov/preview?nodeId=8427

5/ How do I open a PDF on VA.gov?
TKTKTK -- @lunascoop Can you place the preview link here for that new step by step you created?

**Account and profile**
1/ Signing in to VA.gov
preview-prod.vfs.va.gov/preview?nodeId=8222

2/ Change your address on file with VA
preview-prod.vfs.va.gov/preview?nodeId=8473

3/ Direct deposit for your VA benefit payments
preview-prod.vfs.va.gov/preview?nodeId=8423

4/ How to change your direct deposit information for VA education benefits
preview-prod.vfs.va.gov/preview?nodeId=8474

5/ How to change your direct deposit information for disability or pension
preview-prod.vfs.va.gov/preview?nodeId=8434

**Comment by RLHecht** [comment]
I've put in these real links instead of the sample ones we had. For the final link that's "Go to more articles" I am not sure what I am supposed to be linking to so that is still a random link for the time being.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - the Go to more articles link should point to the  Account/profile category landing page and the Other topics landing page - when the FE is built for those. The FE for those were supposed to be ready last Friday, so please check with Nick and Kelson. 

The URLs for those are going to be:  URL pattern: `www.va.gov/resources/[category-name]/`. Those landing pages are not going to be nodes, so I believe you'll need to manually enter the URL, but would you mind confirming that with Oksana in the lc channel? 

va.gov/resources/va-account-and-profile/ 
va.gov/resources/other-topics-and-questions/

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO - please be sure to review the sample beta info alert on this page and provide your feedback. 

LC homepage: https://prod.cms.va.gov/resources

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva 
ALERT HEADING
Test: This is a beta launch
ALERT CONTENT
Beta launch text - Welcome to resources and support, a new part of VA.gov. We're currently in beta testing. We'll be adding more articles and topics in the coming weeks and months, so please check back often.

**Comment by jenniferlee-dsva** [comment]
ALERT HEADING
We're currently in beta testing. 

ALERT CONTENT
Welcome to resources and support, a new part of VA.gov.  We'll be adding more articles and topics in the coming weeks and months, so please check back often.

**Comment by jenniferlee-dsva** [comment]
Updated in the CMS, will close this ticket
