### ISSUE TITLE
VSA Onboarding - Denise Coveyduc

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#14371]
## Welcome to the VSA Program

Welcome, Denise! This issue will be used to track your onboarding to the VSA Program.

---

## Pre-Onboarding

**Operation Lead Tasks**

- [x] Send Welcome email to New Hire (request GitHub Username)

*Send Notifications with New Hire details (name, position, start date) to:*

- [x] Admin Analyst
- [x] VA Leadership
- [x] VA PO
- [x] Practice Lead
- [x] VSP Onboarding

**Access, Paperwork and Program File Updates**

- [x] Access to [Shared Google Drive](https://drive.google.com/drive/u/1/folders/0ACZ1e6Rs_6sDUk9PVA)
- [x] Access to VSA PTO Calendar
- [x] Access to VA Organization in GitHub
- [x] Access to VSA GitHub Repositories
- [x] Access to GCIO/AdHoc Slack Workspace
- [x] Access to DSVA Slack Workspace
- [x] Request Hardware/Software (remove if non-GCIO)
- [x] Request New Hire to Complete VA Onboarding Paperwork (GCIO Admin Analyst)
- [x] Schedule Program Overview Meeting

---

## Onboarding

**New Hire Tasks**

*Day 1*
- [x] [Watch Chris Johnston va.gov Backgrounder recording](https://drive.google.com/file/d/1BTYPaR0p9hYD4qd-OCCduyIRTRr77S1O/view?usp=sharing)
- [x] Attend VSA Program Overview Meeting
- [x] Make Calendar Public (Free/Busy)
- [x] Complete VA Onboarding paperwork (sent by Admin Analyst - Victoria Akitobi)

*Month 1*
- [x] Complete Skill Matrix (GCIO only, sent by @yanaroy)
- [x] Request SOCKS Access, after SAC Adjudication
- [x] Complete VSP Orientation (Andrea Hewitt)

**Operation Lead Tasks**

- [x] Inform Practice Lead, Product Manager to trigger communication
- [x] Conduct VSA Program Overview Meeting
- [x] Update Org Chart and Share with New Hire
- [x] Add New Hire to #va-vsa
- [x] Send out org announcement on #va-vsa
- [x] Request New Hire to Complete Skills Matrix (GCIO only)
- [x] Add New Hire to Program-wide Meetings
- [ ] Add New Hire to The Platform Newsletter (James Chaisa)

**Practice Lead Tasks**

- [x] Send Intro Comms to New Hire
- [x] Conduct Practice-specific Onboarding Meeting with New Hire
- [x] Add New Hire to Practice-specific meetings

**Product Manager Tasks**

- [x] Send Intro Comms to New Hire
- [x] Conduct Intro Meeting with New Hire
- [x] Add New Hire to Product team meetings

**Program Manager Task**

- [x] Check in with New Hire

**Comment by shiragoodman** [comment]
@YanaRoy Denies has already gone through VSP orientation, so I'll be unassigning myself from this ticket

**Comment by denisecoveyduc** [comment]
@YanaRoy Can you remind me where I can find the skills matrix? I believe that is the final task outstanding for my onboarding ticket.

**Comment by YanaRoy** [comment]
Here's the link to the folder where the Skills Matrix lives:
https://drive.google.com/drive/u/1/folders/1egguUa68Mzr6QPxMU8xwMckNjYW3vQFi

[image: GovernmentCIO] <http://www.governmentcio.com/>
Yana M. Roy | CSM
Operations Lead
| *mobile* (732) 822-1200
| *e.* yroy@governmentcio.com
*Government*CIO
website <http://www.governmentcio.com/> | magazine
<http://governmentciomagazine.com/> | consulting
<http://www.governmentcio.com/consulting> | training
<http://www.governmentcio.com/training> | jobs
<http://www.governmentcio.com/careers> | map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>
[image: Twitter] <https://twitter.com/GovernmentCIO> [image: Facebook]
<https://www.facebook.com/GovernmentCIOMagazine> [image: LinkedIn]
<https://www.linkedin.com/company/governmentcio> [image: YouTube]
<https://www.youtube.com/user/GovernmentCIO/videos>
*Confidentiality Note: *This email may contain confidential and/or private
information.
If you received this email in error please delete and notify sender.
