### ISSUE TITLE
Identify transformers owned by VSA Facilities & triage discrepancy issues to team

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#14380]
## Overview 

The purpose of this ticket is to identify which open issues should be worked on by VSA Facilities developer (Michael). To do that, we need to first identify which transformers are relevant to VSA Facilities team. 

## To Do

- Identify [which transformers](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/site/stages/build/process-cms-exports/transformers) should be owned by VSA Facilities (used to generate facility locator and VAMC pages)
   - Generate a list & review with VSP
   - Get various teams (VSP, Facilities, CMS) to sign off on this list (Megan to help with approval wrangling)
- Review the list of open issues that VSP identified to address discrepancy between CMS Export Build <> Graph QL — [view ZenHub board with `cms-transformer` label and review `Ready` column](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/board?labels=cms-transformer&repos=133843125&showPipelineDescriptions=false)
   - Each issue is titled "for `bundle_name`"
- Assign issues that relate to transformers owned by VSA Facilities to Michael and add team label

## Acceptance Criteria (WIP)

- [x] Transformers "owned" by VSA Facilities team are identified and documented (ownership list is captured) 
   - [ ] VSP, VSA Facilities, CMS have signed off on this list
- [x] Discrepancy tickets between Graph QL <> CMS Export Build (that were generated by VSP ~ 8/28/20) that apply to transformers that VSA Facilities team owns are identified and assigned to Michael

_What happens next? Once this ticket is complete, the next step will be to complete all of the issues that Michael assigns to himself as part of this ticket (all discrepancies related to VSA Facilities team). Then, Michael will re-run the diff between GraphQL and CMS Export Build to identify new issues that have come up since 8/28._

**Comment by mpelzsherman** [comment]
Please add acceptance criteria so we can estimate, thanks.
