### ISSUE TITLE
[Epic] LC Search + 'view all articles' landing page

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14389]
## High Level User Story/ies
As a Veteran or beneficiary, I need to search for LC articles so I can find answers to questions I have about the site or about VA services or benefits. As a non-beneficiary who works with Veterans (like VSOs, fiduciaries), I want to find answers to questions I have about what I need to do in order to do my job (e.g., how to apply to become a fiduciary)

## Hypothesis or Bet
**If** _LC article search feature is created_ **then** _veterans and non-beneficiary can find answers to questions_.

## OKR
_WTBD_

## Planning Considerations
_Task Tbd_

**Comment by MickinSahni** [comment]
hey @brianalloyd i think this can be closed
it looks like a dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/13983

**Comment by brianalloyd** [comment]
Thanks @MickinSahni closing now.
