### ISSUE TITLE
COVID-19 screening tool

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14384]
### User Story
As a user, I want to easily access a COVID-19 screening survey so I can complete it before my appointment. 

### Acceptance Criteria

1. Selecting the Covid-19 screening tool option from the home page opens the following page out-of-app in the browser: https://www.va.gov/covid19screen/

### Designs:
Launch page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636866

**Comment by digitalken** [comment]
Testing:

1. Verify Covid-19 screening tool button opens web view of https://www.va.gov/covid19screen/
2. Designs don't show expected navigation but probably look for "Done", "Reload" buttons on top of web view and left, right, open in browser buttons on bottom of screen.
3. Verify above buttons work as expected.
4. Verify web view buttons are read by screen reader.
5. Verify user can tab their way through navigation.
NOTE: Web page content is external to app.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Tested in TestRail. Passed. Opens web browser and covid screen page.
Sending over to Design QA.
