### ISSUE TITLE
Recommend final text of 1.0 LC tags

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14394]
## Recommend final text of 1.0 LC tags

Per MVP phases (documented here) we will launch 1.0 mvp with a limited set of FE content tags, based on content categories, articles available, and card sort synthesis. 

**Content tag labels we need to finalize:** 
- claims/appeals status theme
- payments/debts theme
- sign in/account sign in theme

AC:
- [ ]  Agreed upon final nomenclature of the above 3 tag labels. 
- [ ]  Final labels are shared with Oksana on the CMS team.

**Comment by jenniferlee-dsva** [comment]
For awareness @brianalloyd

**Comment by bethpottsVADEPO** [comment]
This is a dup. We decided this in #14399. Closing.
