### ISSUE TITLE
[Epic] LC Step-by-Step MVP 1.0

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14391]
## High Level User Story/ies
As a Veteran, I need a visual way to view a step-by-step process quick navigation to Tier 1 benefits tools and content.

## Hypothesis or Bet
**If** _build a step-by-step visual experience in LC_ **then** _veterans will be able to quickly navigate to Tier 1 benefits_.

## OKR
_TBD_

**Comment by jenniferlee-dsva** [comment]
closing as this was completed with the last mobile ticket by Fareed.
