### ISSUE TITLE
[Build] Alerts for LC Global Templates (All)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14395]
## Issue Description
- Ability to display "alert" block for article templates. (Sample alert copy in CMS)
- To specify: which templates this applies to - See template requirements for this list
All allow alerts to intro text and some within body content
- Applies to MVP 1.0 and 1.1
- In body Alert.

## Tasks
TBD

## Acceptance Criteria
- Validate FE logic with all templates. 

## Planning Considerations
WIP - All allow alters to intro text and some within body content.

**Comment by ncksllvn** [comment]
We have been adding the top-level `fieldAlertSingle` into each LC template as we've worked on them, and have also added the standard block alerts as well. I _think_ we have already done this, but I would like someone to be able to verify what pieces we are missing if not.

**Comment by kelsonic** [comment]
Moving to validate as related PRs have been merged

**Comment by jenniferlee-dsva** [comment]
Validated with 1.0 templates and all is well with them except on the Step-by-Step. 

So, the alert field after the intro text block works okay! 

It's the alert fields within the body content (when enabled within a step after the step blurb) that do not display. I believe they once did appear correctly. And then they turned into weird ghost alerts. 

Now the ghost alert problem appears to have been resolved, but now the real alerts also seem to be suppressed. 

Here is an example node: http://preview-prod.vfs.va.gov/preview?nodeId=6899
https://dsva.slack.com/files/UCV8RHP8R/F01DFEZBB6F/image.png

And in the CMS, there are test alerts enabled in several steps: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/19051cbe-e854-44bc-af40-91e626d0a497)

**Comment by jenniferlee-dsva** [comment]
Hey all - let's push resolving this bug for post-Nov 4 launch. 

The handful of step by step articles that we currently have for go live do not need  alerts within the body content. This is a capability that exists in the CMS which we need to reflect in the FE, but I would say this is not a critical blocker bug. 

@ncksllvn @kelsonic @brianalloyd

**Comment by jenniferlee-dsva** [comment]
Validated with http://preview-prod.vfs.va.gov/preview?nodeId=6899 . Closing!
