### ISSUE TITLE
enable oauth for grafana

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#144]
## Description

Currently our internally hosted Grafana requires SOCKS access and a user to self-register by giving an email and password. We can reduce the number of passwords folks need by enabling OAuth. Not going to tackle the SOCKS access issue in this ticket (but that'll come soon as well).

## AC

- [x] a user within the VA GitHub organization can sign up for Grafana via GitHub OAuth without supplying a username and password

**Comment by batemapf** [comment]
FYI, redirect from the GH auth screen is to `grafana.vetsgov-internal` which results in `Server side error :(` if you begin the auth process from `grafana.vfs.va.gov`.

**Comment by tskinn** [comment]
Thanks @batemapf . It has been updated and should be working now.

**Comment by ricetj** [comment]
@tskinn is this good to close now?
