### ISSUE TITLE
Analytics Implementation or QA Support for Learning Center

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#14408]
## Analytics Request - Resources and Support (Learning Center)
---
Raw KPIs:
- Findability/Navigation: how easily are users finding LC content and navigating between LC content?
- Navigation/Traffic: Increase traffic to benefit hubs via LC content?
- Customer Satisfaction: Majority of Veteran/user feedback responses are positive (3/5+ or primarily ‘good’)

---

<details>

<summary>Google Analytics Implementation or QA Request</summary>

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
- Google Analytics implementation

- Who is this request for?

    - @jenniferlee-dsva , PO; @brianalloyd , PM
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    - Team: Public Websites team

    - Learning center (official name: __Resources and support__)
    
- Provide the Domain where Google Analytics needs to be implemented
    - www.staging.va.gov and va.gov (but we might need clarification on Drupal urls)
    
    _No PII is passed in URL or title tag_ 
    
    - [URL and Title Tag Chart] 
![Screen Shot 2020-10-20 at 11 00 48 AM](https://user-images.githubusercontent.com/70410912/96620595-e2080b00-12c4-11eb-981d-b7eeaa9efbc4.png)

- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - MVP 1.0 Production beta launch: ~October 29 - Nov 5
    - MVP 1.1 Production full launch: ~ December

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._

- Category: Account and profile
    - URL: www.va.gov/resources/account-and-profile/
    - BC: Home > Resources and support > All articles in: Account and profile
    - Article page UPDATE 10/16/2020

- Example H1: Frequently asked questions (FAQs) about signing in to VA.gov
    - URL: www.va.gov/resources/frequently-asked-questions-faq-about-signing-in-to-va-gov/
    - BC: Home > Resources and support > Frequently asked questions (FAQs) about signing in to VA.gov
    - URL: www.va.gov/resources/account-and-profile/frequently-asked-questions-faq-about-signing-in-to-va-gov/
    - BC: Home > Resources and support > Account and profile > Frequently asked questions (FAQs) about signing in to 
     VA.gov
    - Tag landing page

- Tag: Claims and appeals status
   - Example H1: All articles tagged: Claims and appeals status
   - URL: www.va.gov/resources/tag/claims-and-appeals-status/
   - BC: Home > Resources and support > All articles tagged: Claims and appeals status
      Search results page

- Example search: claim status
   - Example H1: Search results for: "claim status"
   - URL: www.va.gov/resources/search/?query=claim+status
   - BC: Home > Resources and support > Search results for: "claim status"
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._

## Website Interactions to Track
**Note: the url structure of the Resources and Support pages is **

## Search Engagement 
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Origin/Acquisition     | Search refinements after initial search (What terms are bringing users to Resources and Support components?)  | Table                   |
|2| Baselining             | Organic Search - want to measure out-preform from previous to post launch                                                                       | Table and/or Line graph |
|3| Conversions/Engagement | How often users switch to search "All VA.gov" after searching resources and support articles.                                                                                 | Table                   |
|4| Conversions/Engagement | Resource & Support (LC) search - How often is R&S search component is engaged                                                       |       Table                  |
|5| Conversions/Engagement | Scroll depth - What are the users behaviors in finding related content                                                                                     | Table                   |
|6| Conversions/Engagement | Search Terms (what are users searching for on LC)              | Table                   |

## Exits/Navigation from an Article
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Navigation/Engagement    | global search in the utility nav  | Table            |
|2| Navigation/Engagement         | Breadcrumb                  | Table and/or Line graph |
|3| Navigation/Engagement  | Global menu (fat nav)                                                                                | Table and/or Line graph (However best to view)     |

## Engagement Metrics
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Navigation/Engagement    | Tags (Which tags are being clicked? Frequency?            | Table   |
|2| Navigation/Engagement         | Related information link clicks/engagement                 | Table  |
|3| Navigation/Engagement  | VA benefits link clicks/engagement               | Table and/or Line graph (However best to view)     |
|4| Navigation/Engagement  | CTA button(s) how many clicks on each page/article, bounce rate post click to determine user behavior              | Table and/or Line graph (However best to view)     |

## Customer Satisfaction via: GA Dashboard or Medalia (DOMO)
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Satisfaction/Engagement    | `How do you rate your experience on this page` track response with comparable between good and bad         | Chart/Graph   |
|2| Navigation/Engagement         | Calls via phone number links in the `Need more help` component                | Table  |

Screenshots:

Please reference the [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b) board in support of requested items tabled above. 

Customer Satisfaction Elements:

How do you rate: 
![Screen Shot 2020-10-20 at 10 54 15 AM](https://user-images.githubusercontent.com/70410912/96618927-c865c400-12c2-11eb-92fe-52169e5f5483.png)

Tags:
![Screen Shot 2020-10-20 at 10 54 08 AM](https://user-images.githubusercontent.com/70410912/96619005-df0c1b00-12c2-11eb-86da-a99c9a156e2e.png)

Need More Help:
![Screen Shot 2020-10-20 at 10 54 36 AM](https://user-images.githubusercontent.com/70410912/96619053-edf2cd80-12c2-11eb-9b79-84f6e199cef0.png)

Search Component: Resources and Support Vs. All of VA.gov
![Screen Shot 2020-10-20 at 10 55 00 AM](https://user-images.githubusercontent.com/70410912/96619124-04008e00-12c3-11eb-8c4d-e82105ef4b20.png)

<details>
<summary>More Information</summary>

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

</details>

**Comment by jenniferlee-dsva** [comment]
@brianalloyd - have you started this already? if not, i can start this today and we can asynchronously co-create - and TB to submit. Want to make sure we're getting things into other team's queue timely but avoid duplicating.

**Comment by brianalloyd** [comment]
@jenniferlee-dsva I have not, but agree it would be good to get this rolling.  If you would like to start the process today and we can asynchronously co-create - and TB to submit.  Thanks.

**Comment by MickinSahni** [comment]
Question: what domain/urls can we share?
  - Check out what we did for Form Detail Pages: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4552#issuecomment-685014359

Question: how useful are screenshots?
  - Can be used to connect GA data layer reqs to the real-life LC components. Check out this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4552#issuecomment-676525777

Question: Anything related to test users?
  - Nope. Not necessary since this is entirely unauthenticated.

Question: How will the analytics team scope/aggregate metrics?
  - We need the root/path for all LC pages so that the analytics team knows the pages to pull metrics.

**Comment by brianalloyd** [comment]
@joanneesteban submitting the analytics request in support of Resources and Support (Learning Center) MVP 1.0, this is my first request since I came on board I was to see if it would be beneficial to do a 15 min sync to clear up any questions?  LMK, thanks.  CC @jenniferlee-dsva

**Comment by jonwehausen** [comment]
@brianalloyd going to close this as I believe we've got what we're looking for here covered in #15196

**Comment by brianalloyd** [comment]
@jonwehausen sounds good, thanks.
