### ISSUE TITLE
Coordinate IA and Content Onboarding with Care Giver Team

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1440]
### User story
As the new Care Giver VFS Team, I need to know what's expected of my team in terms of the content and IA that we create for our tool, and what we can expect from VSP, so that we can move fwd efficiently and so that Veterans can easily find and interact with our tool.

### Goal
Collaborate with the Product Support team, and do whatever's necessary to proactively incorporate "content" and "IA" into Care Giver onboarding experience effectively, so they come away achieving the user story above.

### Definition of done

- [x] Meet with appropriate Care Giver team members to go over content and IA best practices
- [x] Meet with Care Giver PM(s) to go over Content Review ROE (Rules of Engagement)
- [ ] Document findings and feedback from that meeting to recommend for doc iteration

**Comment by mnorthuis** [comment]
Onboarding for content and IA completed on 1/7/2020.
