### ISSUE TITLE
[Content] 526: Some of the 526 Language is Unclear - Explore Other Options

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14403]
## Issue Description
Edit: We determined this requires usability.  This story needs some more updates to reflect that, but it is no longer an implementation story.  Suggestion is we find a way to do some very basic usability around the wording changes to determine if our suggestions clarify the wording for most veterans/sms.

There are two situations where the language the SM or veteran sees is a little unclear and has consistently come up as a possible issue during UAT.

- Exposure during military service.  The first bullet below.  Suggested some other language such as "My disability was caused by an injury, exposure, or first occurred during military service."  This language may not be allowed and we have to check with stakeholders on whether we can make updates to this language.
![image](https://user-images.githubusercontent.com/53824125/95114702-91f44a80-0701-11eb-9aa5-989a91c213ca.png)

- New conditions
When filing for a disability claim, the "new condition" language seems to throw people.  Consider optimizing this language.

## Acceptance Criteria
- [ ] Exposure during military service decision on possible new language
- [ ] New condition decision on possible new language
- [ ] New language implemented if we decide to change it

**Comment by kevinstachura** [comment]
Yes, this is something we should circle back on and wrap it into 526 enhancements. Should this be part of the research initiative that Christian will be putting together for 526?

**Comment by vhenry07** [comment]
Closing as this work will be captured in our new usability testing tasks.
