### ISSUE TITLE
Create a release plan for for learning center MVP 1.0

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14415]
Acceptance Criteria
- [x] A completed release plan for learning center MVP 1.0

WIP release plan for learning center: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/release-plan-1-0-beta.md

**Comment by jenniferlee-dsva** [comment]
Hi @brianalloyd - I started a draft for you ^. Please reach out to complete it so we have launch plan ready. Would love for you to own the launch plan as PM.

**Comment by brianalloyd** [comment]
Thanks @Jen, I'll work this today and reach out if any gaps exist. Thanks, Brian.

**Comment by brianalloyd** [comment]
Release plan is complete, closing out this ticket. Final plan is [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/release-plan-1-0-beta.md)
