### ISSUE TITLE
Project Kickoff [App Directory, VA Lighthouse API, Bilby team (End User Experience)]

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#14418]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all relevent artifacts to the ticket
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] Shira will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed and [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline (All out product outlines live in confluence so I don't have it in GH) (product outline is attached in comments below)
- Explanation of the problem space
    - We are creating a list of Oauth Applications that Veterans can connect to in order to improve discoverability for Veterans, as well as give them information on the different applications. 
- Any other artifacts you have so far
  - There are a few, but I will link to relevant info: 
     - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/connected-apps-data
     - Original design ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/9238
     - New ticket to incorporate within the Learning Center: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14279
     - Draft PR for App Directory: https://github.com/department-of-veterans-affairs/vets-website/pull/14149
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **@ricetj** 
- DEPO Product Lead (required): **Andrew Fichter**
- Entire VFS team (recommended): **@LeKeve, @bradenshipley, ** 

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** NO

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

the preferred time slot is for Thursday at 1:30-2:30 pm est

**Comment by shiragoodman** [comment]
@ricetj  - we need to see the Product Outline to schedule the kickoff. Would you be able to download it and attach here as a comment ?

**Comment by ricetj** [comment]
> @ricetj - we need to see the Product Outline to schedule the kickoff. Would you be able to download it and attach here as a comment ?

sure 
[VAExternal-2152183501-051020-1701-14.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5330063/VAExternal-2152183501-051020-1701-14.pdf)

**Comment by shiragoodman** [comment]
@ricetj could you also add more info to the title about your team? I don't think "App Directory" is enough information for our review team.

**Comment by ricetj** [comment]
> @ricetj could you also add more info to the title about your team? I don't think "App Directory" is enough information for our review team.

Hello @shiragoodman, what kind of information are you looking for in the title? Happy to provide whatever is needed.

**Comment by ricetj** [comment]
How is that?

**Comment by shiragoodman** [comment]
Perfect. Thank you!
