### ISSUE TITLE
Additional AWSAccess for Joseph Niquette

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#14412]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Joseph Niquette
- Please Provide your email.
   > joe.niquette@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Identity team, Sr. Security Engineer, Oddball

- Requesting SSH key authorization?
   > NO 
   - Already have this setup

- Grant AWS Console access?
  > YES
  - I would like to request additional READ ONLY access into EC2, Load Balancers, AMIs, security groups, S3, API Gateway, direct connect, VPC, Route 53, S2S VPN, VPGs, (essentially all the networking components such as route tables, IGs, etc), and cloudtrail. Their may be more later, but this is a good start. The reason I am requesting this is because I am trying to perform a security review of the entire implementation of SSOe. I also am currently troubleshooting logging for the SSOe solution which requires me to be able to see load balancers and other instance data associated with the cloudwatch logs. Each of the permission requests above are strictly associated with reviewing each of the components that are involved with the SSOe solution and determining where we have security gaps and troubleshooting gaps in SSOe return logs.

**Comment by joeniquette** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
User should now have read on all requested services.
