### ISSUE TITLE
CT Redesign: Research options for searching for schools near me

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14413]
As a developer, I need to research and document options for identifying institutions near the user.

## Assumptions:
1. If a demo is needed to evaluate these options, then that will be a follow on story.
2. We will reach out to the teams on VA.gov who are using geolocation and include those tools for evaluation here (facility locator team). 

## Acceptance Criteria
1. Research and document available APIs/geolocation providers with a priority recommendation on which one to use in the Comparison Tool as part of the redesign effort.  Documentation includes but is not limited to:
    a. Cost
    b. Licensing information (open source, # users, etc)
    c. Pros & Cons 
    d. Feature inventory 

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
Possible story add longitude and latitude data from Scorecard into institution data

https://collegescorecard.ed.gov/data/documentation/ has latitude and longitude data

Latitude | root | location.lat | float | LATITUDE |   |   | IPEDS
-- | -- | -- | -- | -- | -- | -- | --
Longitude | root | location.lon | float | LONGITUDE |   |   | IPEDS

**Comment by zurbergram** [comment]
https://www.npmjs.com/package/react-map-gl-geocoder

**Comment by zurbergram** [comment]
https://github.com/perliedman/leaflet-control-geocoder

**Comment by zurbergram** [comment]
https://react-leaflet.js.org/docs/en/components#marker

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/containers/VAMap.jsx#L358

**Comment by zurbergram** [comment]
## “Near Me” filter option

Add a "Near Me" button to Landing Page and both Search Results that ask user's browser for their location and populates the search box with the browser's zip code.

See https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/containers/VAMap.jsx#L265 for sample implementation already present within va.gov

The frontend search query to backend would be provided zip code, latitude, and longitude, ex. `name=29424&latitude=32.776474&longitude=-79.931053`

On the backend https://www.postgresql.org/docs/11/earthdistance.html or similar can be used to determine distance from passed down latitude and longitude coordinates in the search query (if latitude and longitude are present ignore the zip code search term to prevent converting back to latitude and longitude).  
The distance threshold could either be a part of the search query or a configuration option within the backend.

### T-shirt size
Medium

**Comment by zurbergram** [comment]
## Improve usage of zip code as a search term

On the backend https://www.postgresql.org/docs/11/earthdistance.html or similar can be used to determine distance from the zip code's latitude and longitude.

https://github.com/alexreisner/geocoder#basic-search could be used to find latitude and longitude of the zip code.

The distance threshold could either be a part of the search query or a configuration option within the backend.

### T-shirt size
Medium

**Comment by zurbergram** [comment]
## Map

For frontend see https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/facility-locator/containers/VAMap.jsx#L358 for https://staging.va.gov/find-locations

On the backend https://www.postgresql.org/docs/11/earthdistance.html or similar can be used to determine distance from the a provided zip code's latitude and longitude.

A distance threshold to reduce results size could either be a part of the search query or a configuration option within the backend.


### T-shirt size
XXL

**Comment by zurbergram** [comment]
Sample code using https://github.com/alexreisner/geocoder#basic-search

```
irb(main):009:0> Geocoder.search("29424").filter{|r| r.country_code == 'us'}
=> [#<Geocoder::Result::Nominatim:0x00007ff1f4b5b420 @data={"place_id"=>237762361, "licence"=>"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright", "boundingbox"=>["32.624167064935", "32.944167064935", "-80.097383779221", "-79.777383779221"], "lat"=>"32.78416706493507", "lon"=>"-79.93738377922081", "display_name"=>"Charleston, Charleston County, South Carolina, 29424, United States of America", "class"=>"place", "type"=>"postcode", "importance"=>0.33499999999999996, "address"=>{"city"=>"Charleston", "county"=>"Charleston County", "state"=>"South Carolina", "postcode"=>"29424", "country"=>"United States of America", "country_code"=>"us"}}, @cache_hit=nil>]
```

**Comment by zurbergram** [comment]
### Vets-website
https://react-leaflet.js.org/ and https://github.com/mapbox/mapbox-sdk-js which are currently used by https://staging.va.gov/find-locations currently

### Gibct-data-service
https://github.com/alexreisner/geocoder uses by default https://github.com/osm-search/Nominatim
but has access to other APIs if nominatim is not sufficient or presents issues

https://www.postgresql.org/docs/11/earthdistance.html

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/schools-near-me/research.md
