### ISSUE TITLE
Research: A 10-10CG submission was sent without an attachment

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#14429]
**Description**
Investigate the reason for why these submissions' attachments did not reach CARMA.

Attempt to reproduce on local env.

The logs for these submissions have the "attachments" key set to an empty object `{}`. These could be failing on upload and there is not an error case for logging it.

```csv
request_id,carma_case_id,timestamp
50a402ca-62f0-4ad0-865f-0a4542f4145e,aB9t0000000H8YNCA0,2020-10-02T21:09:59.632Z
c040ad75-9f46-453b-93e1-e472a02ea2a1,aB9t0000000HAJrCAO,2020-10-05T16:23:59.909Z
```

**Comment by mlighdc** [comment]
@kevinmirc in our weekly update with the Caregiver team, there was a 3rd instance of where a submission was missing the PDF. Here is the information from Caitlin. This looks like a new one from a quick scan of above ^^. I can look the case up in CARMA if you need me to.

[12:40 PM] Reyna, Caitlin M. (TISTA Science and Technology Corporation)
    
aB9t0000000H8YNCA0, aB9t0000000HAJrCAO
CD-0717259
Created Date: 10/2/2020 5:09 PM

**Comment by kevinmirc** [comment]
Background processing will alleviate the issues of PDF generation (specifically the file referencing error).
