### ISSUE TITLE
[DESIGN]: GIBCT EYB - CONSIDER shortening margin between benefit headers on college, OTJ profiles

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#14424]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a user, I want to skim the benefit headings quickly. 
## Details

The college and OTJ profile benefit headings feel like they have smaller margins for easier scanning. Screenshot attached below.

/cc @CrystabelReiter && @emilywaggoner for VSP design awareness 

## Acceptance Criteria

- [ ] Heading margins are shortened, or design agrees this is not an issue

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Environment

* https://staging.va.gov/gi-bill-comparison-tool/profile/11006124 (college profile)
* https://staging.va.gov/gi-bill-comparison-tool/profile/10000008 (OTJ profile)

## Screenshots or Trace Logs

![Screen Shot 2020-10-05 at 4 13 19 PM](https://user-images.githubusercontent.com/934879/95133108-646dc800-0726-11eb-9249-088e4a67c2af.png)

---
![Screen Shot 2020-10-05 at 4 13 10 PM](https://user-images.githubusercontent.com/934879/95133113-6a63a900-0726-11eb-9b03-e99d11ca62ee.png)

**Comment by desireeturner** [comment]
@JenLJ @watersemma @amyknox Looking for your input on this issue. Thank you!

**Comment by amyknox** [comment]
@watersemma - do you have time this sprint to take a look at this and propose new vertical spacing for schools and OJT?   

It'd be good if we could tighten up the vertical spacing... but not too much... want the numbers to still have room to breathe.

**Comment by watersemma** [comment]
@amyknox yes, I can take a look at this today.

**Comment by watersemma** [comment]
Lets tighten the margin in-between to 16 px. See examples in invision here: https://bahdigital.invisionapp.com/share/UZIAFSK5BVP
https://bahdigital.invisionapp.com/share/R9IAFSLJGC5

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15410

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me

**Comment by watersemma** [comment]
UX Review 2/2: looks good to me!

**Comment by delli-gatti-michael** [comment]
@1Copenut This is on Staging and ready for your review

**Comment by 1Copenut** [comment]
@delli-gatti-michael LGTM. Moving to close.
