### ISSUE TITLE
IA Request [Resources and support (formerly learning center)]

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14445]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to[ product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)
- Link to or attach prototype or[ mockups](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)
- Link to research readout/results - [usability prototype research ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/learning-center-mvp-findings-summary.md)+ [card sort](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort/card-sort-research-summary.md)

**SEO Keywords** - Provide a list of keywords used by your target audience when they talk about or search for your content

- resources
- support
- faqs
- help

**Proposed site map/page structure** - Provide link or image of proposed page structure (if more than one page)

**Suggested URL(s)** - Provide suggested URLs and any background or rationale

**Suggested entry points** - What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
Utility nav
Global footer
From the "More resources" spoke

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?

Yes, but not until 1.1 (December). 
https://iris.custhelp.va.gov/app/answers/list

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [x] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
Draft IA is documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-learning-center.md

I need to do the following yet:
- Review complex user flows with team and discuss potential pain points
- Review H1s, breadcrumbs and URLs with @bethpotts, @peggygannon and @andaleliz 
- Finalize entry points with @mpeterz 
- Review content templates to ensure all flows are captured
- Review approach with CMS team

**Comment by jenniferlee-dsva** [comment]
Hi @mnorthuis - I commented on several things via gh branch. Could we tb on a call to discuss? There are a few important things that I feel strongly about. 

1/ Article landing pages - H1s - should be super dummy clear to the user and not be awkward no matter what the category or tag label is in the future. Prefer: All articles in: {X-category-name}  and All articles tagged: {Y-tag-name}.  

- Don't think we need to keep repeating 'resources and support in the H1, especially as it makes the landing page titles super long, and possibly even longer depending on the tag and category names. 

2/ Article landing pages - breadcrumbs should match the text of the H1s, so using the above, the breadcrumb would be   
`Home > Resources and support > All articles in: {X-category-name}` .   We've been slowly cleaning up the issue of breadcrumbs not matching H1s and nav labels in the benefit hubs, and I'd like to avoid recreating that issue here. 

- Also want to simplify H1s-to-breadcrumb relationship by automating as much as possible and not relying on manual text creation. This is something we can do easily in the CMS, as we did for forms product. 

3/ LC article H1s are already set to a max of 70 chars max including spaces. This follows the character count max for our section headers globally, and would prefer to be on the slightly generous side here bc titles in the form of questions -- especially when using wordier plain language - tend to go a bit long.

**Comment by mnorthuis** [comment]
Some responses, but yes we can chat

1 - I removed the H1s from my IA, since I don't determine those. I had originally copied them from the mural, but they may not have been updated when I looked. 

2 - Updated IA to show that for category and tag landing pages, the breadcrumb pulls the H1, not just the category/tag label

3- I can change it to 70. I used 60 since that is what is recommended for a title tag and they should be similar.  With the category added to the url and breadcrumb, they are going to get relatively long.

**Comment by jenniferlee-dsva** [comment]
Thx @mnorthuis for the reply. 

RE #3 - I updated the 60 to 70. When you had asked about tags character count before, I thought we were talking about frontend content tags, not meta title tags. But FWIW, we don't have a hard set character limit for frontend content tags. They can be pretty long (`Lenders, appraisers, and other real estate professionals`) but only the PW team  can create these.

**Comment by mnorthuis** [comment]
FWIW, not capping the titles in the VAMC pages has caused some issues and they are now looking at modifying those to cap the H1s because the titles have become incredibly long and poorly written.  Kind of like this sentence lol!

**Comment by jenniferlee-dsva** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-learning-center.md#urls-and-breadcrumbs

So to confirm - we're aligned on this final pattern for URL and breadcrumb. And wrt meta title - we're using `H1 | Veterans Affairs` with no character limit in LC and no initial capping, similar to news releases and comm stories.

![image](https://user-images.githubusercontent.com/43381063/95916366-82ff3f00-0d76-11eb-8acd-4e01a7232cb5.png)

**Comment by mnorthuis** [comment]
If the URL and breadcrumb are going to pull from the H1 of the content, then I still strongly recommend that you cap the H1.  I updated it to reflect the 70 characters you mentioned above, but originally recommended 60 characters to match the cap recommended by Moz for title tags.

I do not recommend leaving the H1 as an uncapped field that allows anything.

**Comment by jenniferlee-dsva** [comment]
Yes, we always capitalize the H1 using sentence casing.  I only meant usually we INITIAL cap the META TITLES, and for LC, we're NOT initial capping. (We use sentence case capitalization.)

EX: Article H1 is "How to get a service dog through VA"

The meta title would be: `How to get a service dog through VA | Veterans Affairs `

And the breadcrumb - because it will just pull from the H1 - would go: 

Home > Resources and support > Category > `How to get a service dog through VA`

**Comment by jenniferlee-dsva** [comment]
The URL would be different, per the global URL pattern you recommend for VA.gov to make everything lower case.

**Comment by jenniferlee-dsva** [comment]
The H1 field in the CMS can't enforce capitalization rules. Remember - sentence capitalization still allows for words to be capped if it's a proper noun, and there's no way for the CMS (or for FE logic fwiw) to recognize if a word/s is a proper noun vs. a common noun, especially since VA has some weird exceptions like capitalizing "Veterans" all the time. This is the same case for other CMS products. 

The H1 field is simply a text field, that we've set to 70 char max in the CMS.

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - sorry, I am just noticing the URL pattern for tag landing pages. Made a comment on your md file here: https://github.com/department-of-veterans-affairs/va.gov-team/commit/d72c6118f87f36a5518618c5c2625ed5a7c812a5#diff-ac4066be1f4a214f04c03013e718659ebfd7dd1fc563593191e57b48b022cbfe

**Comment by mnorthuis** [comment]
Some things above are getting a bit confused so we may need to chat.   When I say I recommend capping the H1, I mean enforcing a limit on the characters of the H1 to 60 characters. I leave capitalization decisions totally up to you.

**Comment by jenniferlee-dsva** [comment]
Ah, sure. Let's talk. 

The H1 of articles were set to 70 from the beginning - see requirements doc I linked to above. 70 hasn't changed at all from the beginning. As I mentioned, this is the character limit for section headers and because so many articles will be in the form of a question, I think 60 is going to be too limited. When there's not enough room, authors will create lots of funny abbreviations and workarounds. I do think we need to be a little more generous than 60 with article titles.

**Comment by mnorthuis** [comment]
Ok, sorry, it was this comment that threw me in regards to no character limit.  I used the word "cap" which probably caused more confusion, sorry.  
> 
> So to confirm - we're aligned on this final pattern for URL and breadcrumb. And wrt meta title - we're using `H1 | Veterans Affairs` with no character limit in LC and no initial capping, similar to news releases and comm stories.
>

**Comment by mnorthuis** [comment]
Updated IA including urls/breadcrumbs for the category and tag landing pages, as well as primary entry point recommendations. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-learning-center.md

**Comment by brianalloyd** [comment]
Closing per discussion.
