### ISSUE TITLE
[Spike] Write QuestionnaireResponse data to PGD sandbox

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#14443]
## Acceptance Criteria
- [x] Code written for this spike must be testable from a topical branch.
- [x] Health Quest must implement the JSON Web Tokens(JWT) internet standard to safely transmit data to the PDG sandbox.
- [x] Must be able to write Questionnaire and QuestionnaireResponse data to the PGD sandbox from an interface(Command line).
- [x] Written data(from a command line) must be verifiable for accuracy and integrity on the PGD sandbox.

**Comment by abuckley3385** [comment]
@dillo In order to pull this into this sprint I need this pointed-please.  I know you and Stephen were not able to get together but can you discuss with @mdewey and get an estimate please.

**Comment by dillo** [comment]
We can read questionnaire data and write questionnaire responses to the PGD via curl in the command line. Implementation details for the vets-api are coming up in stories further upstream. This is safe to be closed.
