### ISSUE TITLE
Coronavirus faqs& chatbot updates: Week of 10.5.20

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14446]
## Issue Description

We need to update the coronavirus FAQs and chatbot with the latest information.

This week's updates include:
- Revising Q on visiting patients to reflect visitation policy updates
- Revising Q on masks to reflect people with concerns about wearing them
- Potentially adding new Q on testing results
- Maintenance updates 

---
### Coronavirus research landing page

*Note: This page is currently behind password authentication. So we can save all edits as published, and don't need to use drafts for now.*

### Coronavirus FAQs page

- [x] Revise questions for JTF review (Danielle)
- [x] Receive JTF approval
- [x] Update Drupal page with revised questions and maintenance updates (Danielle)
- [x] Review for errors and omissions, set to publish (Randi)
- [x] Validate on live site (Danielle/Randi) 

### Coronavirus chatbot

- [x] Update chatbot content/messages in GH to match latest FAQs (Danielle)
- [x] Review for errors and omissions, approve PR (Peggy)
- [x] Hand off to Thoughtworks team (Danielle)
- [x] Validate on staging (Danielle, Randi)
- [x] Validate on live site (Danielle, Randi) 

### Coronavirus FAQs

**Drupal node** = 3014

### Coronavirus chatbot

**Branch and content folder:** TBD

**PR:** TBD

## Acceptance Criteria
- [x] Updated content on live FAQs page
- [x] Updated content live in chatbot
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. FAQ updates ready for you:

1. Added new testing section 
2. Moved the existing testing question into that new section
3. Moved the flu shot question from health care up into covid-specific questions section
4. Moved prescription renewals out of accordion and up into regular Qs in health care now that there's room w/ the flu shot Q going away
5. Updated mask question per attached
6. Updated visitation question per attached

[Coronavirus FAQ updates week of 10.05.20_revised](https://app.zenhub.com/files/133843125/9aa0f014-a18d-4bbb-adaf-51be5ca32965/download)

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA COVID FAQs updates are live on the site.
