### ISSUE TITLE
Evaluate guidance for VFS teams to configure their downtime notifications

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#14447]
## Issue Description
VFS teams need to have appropriate guidance on how to configure their downtime notifications. This should be part of the [Product Development Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/c86d27504cfcfb4024d4663afeb11be8e28acb05/platform/working-with-vsp/orientation/Product%20Development%20Checklist.md) and the [Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle). 
[Slack discussion ](https://dsva.slack.com/archives/CJRQ85PQB/p1601583387133400)

---
## Tasks
Evaluate when/how VSP instructs VFS teams to configure their downtime notifications.

## Acceptance Criteria
VFS teams will have appropriate guidance for configuring their downtime notifications.

---

**Comment by lianilychee** [comment]
hello @rroueche !  Shira gave me the context of this ticket.  I submitted a PR #15397 and requested your review.  (Shira, I've tagged you in said PR so you remain in the loop.)

**Comment by lianilychee** [comment]
hey @shiragoodman - PR #15397 has been merged.  Can this issue be closed?

**Comment by shiragoodman** [comment]
thanks @lianilychee ! yes, it can be closed.
