### ISSUE TITLE
HLR Launch: What are the Key Metrics?

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#14448]
What does success look like for HLR? How are we going to measure/monitor it?

AC:
- [ ] Decide what the key metrics are (involve Design, FE, BE) (meeting?)
- [ ] Document key metrics in va.gov-team repo (link in comments)
- [ ] Make ticket to gather metrics

**Comment by edmangimelli** [comment]
Related Ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/3825

**Comment by luke-gcio** [comment]
Meeting with team on Friday 11/20 to wrap up, notes will be here or link to KPI/OKR spreadsheet.

**Comment by luke-gcio** [comment]
Met with the team, looks like we have a good place to start.  Will link to spreadsheet.
