### ISSUE TITLE
Figure out how session cookies work with load testing

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1445]
As a user load testing a new feature, I need to know how to configure my set up so session cookies are on so that the load testing can run. 

AC:
- [ ] Discover what the approach is for using session cookies in load testing

**Comment by peterhill-oddball** [comment]
@tlei123 Please have a look at the load tests that require authenticated sessions. One example is the appealsv2 test.

**Comment by tlei123** [comment]
I should hopefully have AWS-access granted in the next couple of days.

In the meantime, I'm continuing my Python & Locust learning.

**Comment by tlei123** [comment]
@peterhill-oddball , AWS-access request process is getting held up until my VA onboarding (PIV) paperwork gets transferred to the new VSA contract.

I'll update here when access is granted, and continue with independent learning/research in the meantime.

Ping me on Slack as need, especially if this becomes time-sensitive.

**Comment by peterhill-oddball** [comment]
@tlei123 , Understood, this is a fairly low priority item, so just keep it on your radar when you can.

**Comment by peterhill-oddball** [comment]
https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest/education_benefits_claim_1995_stem

This load test that requires authenticated user sessions has a great README explaining how to generate the session cookies, copy them from Jenkins output, and paste them into a sessions.json file in whatever load test directory you need them.

**Comment by peterhill-oddball** [comment]
I created a quick tutorial for incorporating authenticated session cookies into your load test as part of the QA platform documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/peter-qa/platform/quality-assurance/auth-session-loadtest.md).

**Comment by peterhill-oddball** [comment]
@tlei123 Explored this on his own, and discussed the Jenkins output with the owner.  They've agreed to make some tweaks which should make grabbing the cookies from the Jenkins console much easier.  Tze will update the documentation accordingly once the new console output has been settled on.

[Authenticated Sessions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/auth-session-loadtest.md)
