### ISSUE TITLE
Design feedback - Design intent Collaboration [MVP VA Mobile App]

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#14456]
- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

Thoughts/questions:

Is it possible to change the font of the header?

**Must:**
- No “must” feedback at this time

**Should:**

- For the current status (dynamic process list), make the current step blue instead of green to match the standard in the sketch library 

**Consider:**

- Check out the work Liz is doing on alerts in the context of the education wizard - she’s exploring some versions with no icons, which could potentially be an option: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14104

**Definition of Done:**
- [x] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by bridgethapner** [comment]
Thank you for the feedback Emily & Crystabel! 

I have incorporated all the feedback (and also the feedback from VSP Design Office hours) so I will close this ticket.
