### ISSUE TITLE
[Development] HLR: Final Wizard Work for Higher Level Review

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14460]
## Issue Description
Wizard work for new HLR Wizard

## Acceptance Criteria
- [ ] New wizard replacing the old wizard (implementation)
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Wizard design is almost finalized, Robin's or Nick's implementation likely in mid to late sprint 33.

**Comment by Mottie** [comment]
Almost done... still need to include the restart wizard update.
