### ISSUE TITLE
[Development] 526: Move the 9/11 Question Immediately After the Service History

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14469]
## Issue Description
During UAT, it seemed like a usability item was related to when we were asking about the their 9/11 service.  This story is to explore two things:

1. Can we avoid the question entirely if their service history does not match any dates post 9/11 date in the question - quick answer: removing this does not make sense since the chances of someone filing a claim where their service history ended by the 9/11 combat date is very unlikely.
2. Move the question right after service history so it makes more sense.

## Acceptance Criteria
- [ ] New site flow
- [ ] Front end implementation
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
Beginning work on this today.

**Comment by ndsprinkle** [comment]
We actually already are conditionally not showing this page. We use the function `servedAfter911` which checks to see if there is any service period entered that is post 9/11. In the PR that I am about to link to this ticket, the only change will be moving this page to be immediately after the separation location page.
