### ISSUE TITLE
Create 508 guidance/best practice documentation

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1446]
As a developer, I want information about 508 that I can go to while developing so that I know what the best practices are when coding with assessibility in mind. 

AC:
- [x] Documentation is created
- [x] Documentation is reviewed by front end group
- [x] Documentation is live for devs to use

Check with Mikki/Matt Johnson on best place to store this

**Comment by 1Copenut** [comment]
I'm working on a React boilerplate right now that will capture a number of accessibility best practices. The intent is to have this available as a one-off meeting with engineering teams and a self-contained "app" for teams to download, run locally, and learn from.
