### ISSUE TITLE
1995: Update spool file phone number labels

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14467]
As a developer, I need to update the phone number labels in the spool file so that it matches the information collected in the application.

## Assumptions:
1. This work will go directly to production because the spool file template cannot leverage prod / feature flags.

## Acceptance Criteria
1. The Telephone Numbers Data has the following labels:
    a. Home
    b. Mobile

## Supporting Artifacts:
1. [1995_sample_spool.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5336152/1995_sample_spool.docx)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5040

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-07 at 9.54.55 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cea0af6c-59ab-4553-9491-99620f410bb2)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-07 at 9.58.06 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a95da1da-a34b-4693-ba26-8c76cdd4eaa9)

**Comment by sonntag-adam** [comment]
In production closing story.

**Comment by delli-gatti-michael** [comment]
Tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/1038
