### ISSUE TITLE
Common style sheet tracking for MVP

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14461]
- [x] Bridget to define styles

- [ ] Patrick to implement common style sheet

**Comment by bridgethapner** [comment]
I added @lexicalninja here b/c I think this is what he was talking about working on in the engineering touch base right? Patrick and I chatted about the next steps & he's taking the first pass at the style sheet then we'll review together.

**Comment by lexicalninja** [comment]
Implemented base text types, added VA Colors and started on a a theme class to explicitly control colors in discretely locations for easy refactoring in the future. 

DF will need to do a PR to start moving common design components into the styles library. 

I think we kind of need to go with a readme of all the things that we put together in that shared doc on fonts and colors and add use examples for components or something to start. Fairly low tech but good enough to make it understandable. 

I have also started making some buttons and will need to work with @bridgethapner to get some dimension things worked out.

**Comment by bridgethapner** [comment]
Thank you for the update @lexicalninja! I'll grab some time tomorrow for the two of us to connect.

I have: 
- Outlined font styles & color styles for MVP in Google doc (ty Patrick for adding these things in)

I am working on: 
- Adding some general design documentation to the running Google file

I can (if useful):  
- Upload all svgs we are using in MVP to GitHub in a central folder

**Comment by srmyers17** [comment]
- Documenting common component tickets
- Using google doc to document  components to it

**Comment by srmyers17** [comment]
- Moving more things into common component tickets
