### ISSUE TITLE
Add address form field validation to prevent users from entering web URLs

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#14471]
We should update the Profile 2.0 address form schema to mark fields as invalid if they contain parts of web URLs.

If address lines contain the following, mark them as invalid and prevent users from making an update:
- `http`
- `www.`
- `.co`
- `.net`
- `.org`
- `.gov`
- `.edu`

A rough idea for a pattern is: `pattern: '^((?!https?:?/?/?|www\\.|\\.co|\\.net|\\.gov|\\.org).)*$',`

I'm sure there are plenty of ways a user could get around this if they wanted to. But this is better than nothing and shouldn't have any unintended side effects, ie blocking users from entering legit addresses.

**Comment by erikphansen** [comment]
@mshea0606 can you validate that it's no longer possible to enter web URLs as part of your address on staging and close this ticket if things look good?

**Comment by mshea0606** [comment]
@erikphansen looks good!
