### ISSUE TITLE
STEM: Update link in how to apply wizard content.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14472]
As a user of the form wizard, I need the how to apply wizard to provide me with a direct link to the STEM information page so that I do not have to go through an unnecessary redirect.

## Assumptions:
1. This will go directly to production (no prod flag).

## Acceptance Criteria:
1. The "Edith Nourse Rogers STEM Scholarship" links to: https://www.va.gov/education/other-va-education-benefits/stem-scholarship/

## Supporting Artifacts:
1. 
<img width="648" alt="Screen Shot 2020-10-06 at 3 32 46 PM" src="https://user-images.githubusercontent.com/48260534/95251234-41581c80-07e9-11eb-85cf-69d9271d2611.png">

**Comment by elder-joseph** [comment]
Associate PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/14548

**Comment by delli-gatti-michael** [comment]
Tested by the following testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/1000

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by amyknox** [comment]
Checks out for me.

**Comment by JenLJ** [comment]
@delli-gatti-michael This checks out for UX!

**Comment by delli-gatti-michael** [comment]
Closing this out
