### ISSUE TITLE
Active Claims & Appeals (UI)

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#14477]
## User Story
As a user, I want to quickly navigate through my list of active and closed claims/appeals.

## Acceptance Criteria
1. Claims landing page has two views: Active or Closed
     - Pull in the Segmented Selector common component
     - A user can tap "Active" or "Closed" to navigate to that respective list
2. UI when a user has active claims/appeals: 
     - Header: "Your active claims and appeals"
     - Single list of active claims/appeals, sorted by the most recent updated date
3. Each item in the list should include a header (either for a Claim or an Appeal), and a submitted date below the header:
     - Header for a Claim: Claim for [type] updated on [Month XX, XXXX]
     - Header for an Appeal: [Type] appeal updated on [Month XX, XXXX]
     - Below the header: Submitted [Month XX, XXXX]

**Note:** The following are covered in separate stories:
- Closed Claims & Appeals UI
- Detail views for active claims/appeals 

## Designs
Active view: https://adhoc.invisionapp.com/d/main#/console/20546460/432345659/preview#project_console
Closed view: https://adhoc.invisionapp.com/d/main#/console/20546460/432345982/preview#project_console

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines
- Mark "Claims and Appeals" as Header 1

**Segmented Selector**
- accessibilityLabel="active"
- accessibilityHint="view your active claims and appeals"
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 1 of 2)

**List of Active Claims and Appeals**
- accessibilityLabel= "active claims and appeals list"
- accessibilityRole= "menu"
- Mark "Your active claims and appeals" as Header 2
- For each menu item:
     - accessibilityLabel= field title (e.g. Claim for disability updated on January 20, 2020)
     - accessibilityHint= "view details of this active___" (e.g. Claim or Appeal)
     - accessibilityRole= "menuitem"
     - accessibilityValue= contents of field

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
