### ISSUE TITLE
Implement homepage banner into vets-website

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1448]
The configuration for the homepage banner (used for things like hurricane alerts) currently lives in vagov-content as a "fragment". However, the homepage will be migrated to Drupal in the immediate future, making this fragment no longer usable.

As a temporary solution, we should hardcode the homepage banner in vets-website so that we can publish the rest of the homepage from Drupal. Then, once Drupal has the ability to publish homepage banners, we can remove the one hardcoded in vets-website.

**Comment by jefflbrauer** [comment]
@ncksllvn shall we close this out?

**Comment by ncksllvn** [comment]
@jefflbrauer sounds good to me! Want to do the honors?
