### ISSUE TITLE
Standardized Design System Components - Accordions

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#14487]
# Google Analytics Implementation 

## Description 
- Standardize data layer events and variables to track [accordions ](https://design.va.gov/components/accordions) across va.gov

## Data Layer Specification 

```javascript
'event': 'int-accordion-expand', //OR 'int-accordion-collapse'
'accordion-parent-label' //accordion parent label (if there is two labels, if only one label on accordion, populate this value and make child-label undefined)
'accordion-child-label': //dynamically populate with secondary label of the accordion
'accordion-section-label': //populate with the label of the section where the accordion is present`
```

## Acceptance Criteria
- [ ] Data layer for accordions as been deployed universally
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14489)

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14490)

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14492)

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14494)

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14496)

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14497)

**Comment by jonwehausen** [comment]
## Jon to update with most recent specification

**Comment by jonwehausen** [comment]
@bsmartin-ep This has been updated with the correct taxonomy.

**Comment by jonwehausen** [comment]
### QA Testing on Local Storybook

| Description of Interaction | Event Structure | Test Status 
| -- | -- | -- | 
Click to expand accordion with only 1 header | ![image](https://user-images.githubusercontent.com/48527022/116415484-75d40a00-a807-11eb-8fb4-ea6da3521e13.png) | ✔️ **PASS**
Click to collapse accordion with only 1 header | ![image](https://user-images.githubusercontent.com/48527022/116415572-8c7a6100-a807-11eb-98eb-a6bdd45078c7.png) | ✔️ **PASS**
Click to expand accordion with subheader | ![image](https://user-images.githubusercontent.com/48527022/116416013-fabf2380-a807-11eb-816e-0684e981cbc4.png) | ⚠️ **DOES NOT PASS** - @bsmartin-ep `subheader` did not populate here
Click to collapse accordion with subheader | ![image](https://user-images.githubusercontent.com/48527022/116416329-3eb22880-a808-11eb-9d91-54ea0cf576fc.png) | ⚠️ **DOES NOT PASS**

**Comment by jonwehausen** [comment]
@bsmartin-ep After your `subheader` typo fix looks like we still do not have the `subheading` populate

**Comment by jonwehausen** [comment]
### QA Retest

@bsmartin-ep Retest for accordions including `level` parameter look good. Approval to move forward. 

| Description of Interaction | Event Structure | Test Status 
| -- | -- | -- | 
Click to _expand_ two label accordion (adjusted level to be 3) | ![image](https://user-images.githubusercontent.com/48527022/116900664-fed3b280-ac06-11eb-83c0-0b92d0032777.png) | ✔️ **PASS**
Click to _collapse_ two label accordion | ![image](https://user-images.githubusercontent.com/48527022/116900770-1e6adb00-ac07-11eb-941c-b39274e5807e.png) | ✔️ **PASS**
Click to _expand_ single label accordion (level 2) | ![image](https://user-images.githubusercontent.com/48527022/116900918-4d814c80-ac07-11eb-9a7e-e1691a65c69c.png) | ✔️ **PASS**
Click to _collapse_ single label accordion (level 2) | ![image](https://user-images.githubusercontent.com/48527022/116901043-730e5600-ac07-11eb-83e3-fb3855ec90cf.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
@bsmartin-ep to close following production merge

**Comment by bsmartin-ep** [comment]
Merged on May 17.

https://github.com/department-of-veterans-affairs/vets-website/pull/17157
