### ISSUE TITLE
Standardized Design System Components- Alert Boxes

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#14489]
## Description 

*   Standardize data layer events and variables to track [alert box components](https://design.va.gov/components/alertboxes) across [www.va.gov](http://www.va.gov)

## Data Layer Specification - Link click

```javascript
'event': 'nav-alert-box-link-click' //consistent for all links within an alert box
'alert-box-status': //dynamically populate according to the type of alert box, 'warning', 'error', 'informational'
'alert-box-headline': //dynamically populate according to the top level heading of the alert box
'alert-box-headline-level': //dynamically populate with headline level of the component
'alert-box-click-label': //dynamically populate according to the click label of the link
'alert-box-background-only: //dynamically populate with boolean true|false if alert box background only prop was used
'alert-box-closeable': //dynamically populate with boolean true|false if alert box is capable of being closed
```

## Acceptance Criteria

- [ ] Data layer for alert box components as been deployed universally

- [ ] QA has been completed

## Definition of Done

- [ ] All appropriate issue tagging is completed

- [ ] All AC completed

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14491)

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14495)

**Comment by jonwehausen** [comment]
@bsmartin-ep this has been updated with the most up-to-date data layer specification

**Comment by jonwehausen** [comment]
### QA Testing 

Description of Test Case | Data Layer Screenshot | GTM Tagging | Test Status | Dev Notes 
| -- | -- | -- | -- | -- |
Click on link "Find VA locations tool" within the homepage warning alert box | ![image](https://user-images.githubusercontent.com/48527022/112203284-c2b13900-8be8-11eb-86e3-04bcf2b96591.png) <br><br> ![image](https://user-images.githubusercontent.com/48527022/112204967-aadab480-8bea-11eb-9890-1e9401c9e088.png) | ![image](https://user-images.githubusercontent.com/48527022/112205014-bb8b2a80-8bea-11eb-849a-14b02b707840.png) | ✔️ **PASS** | - Alert box link click fired with all of the relevant metadata


@bsmartin-ep All I tweaked was the order of `{{JS - Alert Box Link Click Action}}` to have `alert-box-clickLabel` be last in the event action 

|

**Comment by jonwehausen** [comment]
## QA Testing Round 2
Description of Test Case | Data Layer Screenshot | GTM Tagging | Test Status | Dev Notes 
| -- | -- | -- | -- | -- |
Click on link within view dependents "Info" alert box | ![image](https://user-images.githubusercontent.com/48527022/112499485-e5189300-8d5d-11eb-8b52-6176ee11e850.png) | ![image](https://user-images.githubusercontent.com/48527022/112505375-19db1900-8d63-11eb-8a8f-8c5defddd516.png) | ✔️ **PASS** | • Example where although this alert box has a headline, the prop isn't being used directly so the title reaches our `(not set)`, chatted with Brian on this

**Comment by jonwehausen** [comment]
@bsmartin-ep 

Here is an example of where there is comparable "alert box" events within VAOS: https://github.com/department-of-veterans-affairs/vets-website/blob/45150dd0dfdeb4b2e427416c3026213913405826/src/applications/vaos/tests/new-appointment/components/TypeOfCarePage.unit.spec.jsx#L69. Doesn't look this is an alert box leveraging the component. 

## GTM Tag 
![image](https://user-images.githubusercontent.com/48527022/112510732-17c78900-8d68-11eb-9bc5-864aab0eceef.png)

**Comment by bsmartin-ep** [comment]
@jonwehausen -

If you trace the component back a few levels, you get an AlertBox component at:

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/new-appointment/components/TypeOfCarePage/UpdateAddressAlert.jsx

**Comment by jonwehausen** [comment]
Thanks @bsmartin-ep! Seeing now on that guy the `disableAnalytics` flag was turned on 👍 

![image](https://user-images.githubusercontent.com/48527022/112541039-486bea80-8d89-11eb-97f4-e0010aac68ff.png)
