### ISSUE TITLE
Standardized Design System Components - Side Nav

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#14496]
# Google Analytics Implementation 

## Description 
- Standardize data layer events and variables to track [side navigation](https://design.va.gov/components/accordions) across www.va.gov

## Data Layer Specification - Work in Progress
<table>
  <tr>
  <td><strong>Side Nav - Parent or standalone side nav click with no children</strong></td>  
  <td><strong><code>'event': 'nav-sidenav',</code></strong>
<strong><code>'sidenav-click-label':</code></strong>
   </td>
  </tr>
  <tr>
 <td><strong>Side Nav - Children click</strong></td>  
 <td><strong><code>'event': 'nav-sidenav-child',</code></strong>
<strong><code>'sidenav-dropdown-header'</code></strong>
<strong><code>'sidenav-child-click-label':</code></strong>
   </td>
  </tr>
</table>

## Acceptance Criteria
- [ ] Data layer for side navigation as been deployed universally
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
This component has been retired.
