### ISSUE TITLE
Standardized Design System Components - Buttons

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#14491]
## Description
*   Standardize data layer events and variables to track [button components](https://design.va.gov/components/buttons) across [www.va.gov](http://www.va.gov)

## Full Code Sample
```javascript
'event': 'cta-button-click',
'button-type': 'primary', 
'button-click-label': 'Make an appointment',
'button-background-color': '#0071bb',
```

## Data Layer Specification
<table>
  <tr>
   <td><strong>Event / Variable Name</strong></td>
   <td><strong>Description of Event/Variable </strong></td>
   <td><strong>Example Value </strong></td>
  </tr>
  <tr>
   <td><code>'event': 'cta-button-click'</code></td>
   <td>Triggered when the user clicks on the button</code></td>
   <td><strong>will consistently be <code>'cta-button-click</code> for all buttons</strong></td>
  </tr>
  <tr>
    <td><code>'button-type'</code></td>
    <td>Primary, Secondary, Default button type</td>
    <td><code>'primary' //'secondary', 'default'</code></td>
  </tr>
  <tr>
    <td><code>'button-click-label'</code></td>
    <td>Text of button clicked on</td>
    <td><code>'Make an appointment' //dynamic according to click text label</code></td>
  </tr>
  <tr>
    <td><code>'button-background-color'</code></td>
    <td>RGB color code for button</td>
    <td><code>'#92a8d1' //dynamic according to button button-background-color/code></td>
  </tr>
  <tr>
    <td><code>'button-is-disabled'</code></td>
    <td>Boolean <code>true|false</code> when button is clicked on in a disabled state</td>
    <td><code>true</code></td>
  </tr>
  <tr>
    <td><code>'button-is-progress'</code></td>
    <td>Boolean <code>true|false</code> when button is of progress button</td>
    <td><br /><code>true</code></td>
  </tr>
  <tr>
    <td><code>'button-is-progress-icon-position'</code></td>
    <td>Captures the icon progress position</td>
    <td>Default populate with <code>undefined</code> if button is not a progress button, <br /><br /> otherwise when is a progress button populate with <code>'before-text'</code> or <code>'after-text'</code></td>
  </tr>
  <tr>
    <td><code>'button-is-within-logical-group'</code></td>
    <td>Boolean <code>true|false</code> engineers / designers can set when logically grouping buttons for design purposes</td>
    <td>Default: Populate with <code>undefined</code>, <br /> Designer will have the option to set true/false at points in future<code>true|false</code></td>
  </tr>
  <tr>
    <td><code>'button-type-index-number'</code></td>
    <td>Starting with 1, index number in HTML sequence of button on page of same type (primary, secondary) as button clicked on</td>
    <td><code>2</code></td>
  </tr>
  <tr>
    <td><code>'button-type-markup-on-page'</code></td>
    <td>Array of button breakdown on current page, returning number of buttons of same types</td>
    <td><code> {
      "primary-button-page-count": 3,
      "secondary-button-page-count": 2,
      "default-button-page-count"1
      }
    </code></td>
  </tr>
</table>  

### _Stretch_
 - This is a stretch to bake-in as a "prop" analytics data layer variables that can be used with ANY design system component
 - Many of these align with "utilities" for each component 
 - Would like to discuss next steps with you to programmatically paramaterize these so they may be used with any component 
<table>
  <tr>
   <td><strong>Variable Name</strong></td>
   <td><strong>Description of Variable </strong></td>
   <td><strong>Example Value </strong></td>
  </tr>
  <tr>
    <td><code>'icon-name'</code></td>
    <td>Icon used with component</td>
    <td><code>'warning' //friendly name to describe icon</code></td>
  </tr>
  <tr>
    <td><code>'text-decoration'</code></td>
    <td>Text decoration used, css styling</td>
    <td><code>'.vads-u-text-decoration--underline'</code></td> 
  </tr>
  <tr>
    <td><code>'font-weight'</code></td>
    <td>font weight used, css styling</td>
    <td><code>'.vads-u-font-weight--bold'</code></td> 
  </tr>
  <tr>
    <td><code>'background-color'</code></td>
    <td>RGP code of background color used, css styling</td>
    <td><code>'#ffffff'</code></td> 
  </tr>
  <tr>
    <td><code>'breakpoint-sass-variable'</code></td>
    <td>When a breakpoint sass variable is used, populate the value</td>
    <td><code>'$xsmall-screen'</code></td> 
  </tr>
  <tr>
    <td><code>'font-style'</code></td>
    <td>front style used, css styling</td>
    <td><code>'.vads-u-font-style--italic'</code></td> 
  </tr>
  <tr>
    <td><code>'font-size'</code></td>
    <td>font size used, css styling</td>
    <td><code>'40px .vads-u-font-size--2xl'</code></td> 
  </tr>
</table> 

## Acceptance Criteria
- [ ] Data layer for button component as been deployed universally
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Kamino cloned this issue to [department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14493)

**Comment by jonwehausen** [comment]
@caw310 @joanneesteban 

### Update
- The specification has been updated to include some additional variables based on the feedback you all provided yesterday following our discussion yesterday

**Comment by jonwehausen** [comment]
@bsmartin-ep Please find the latest specification here.

**Comment by bsmartin-ep** [comment]
@jonwehausen / @bmcgrady-ep -

Thoughts on this GTM workspace to consolidate the CTA button tagging?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000438

Essentially I wanted to remove the individual tags for default and primary, but still allow the old events (`cta-default-button-click` and `cta-primary-button-click`) to function.  I did this by adding a default value to the `button-type` dataLayer variable that runs the triggering event through a lookup on the `event`:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000438/variables/1252


...so it should be able to run through one tag in the end.

Thoughts?  Want me to map out all the triggering events (or the pages they are on)?

**Comment by jonwehausen** [comment]
### QA Testing

- Testing was performed here by doing manual data layer pushes to simulate each type of button click

Description of Test Case | Data Layer Screenshot | GTM Tagging | Test Status
--------- | -------------- | --------------- | ---------------
Primary button (new taxonomy)  | ![image](https://user-images.githubusercontent.com/48527022/104049419-f2889d00-51b2-11eb-9dcb-3780c94b8dd3.png) | ![image](https://user-images.githubusercontent.com/48527022/104049448-fc120500-51b2-11eb-81c8-c3e525a84653.png) | ✔️ ✔️ **PASS**
Primary button (new taxonomy) - _no `button-click-label`_ | ![image](https://user-images.githubusercontent.com/48527022/104049601-3da2b000-51b3-11eb-8809-f3230ac4a44b.png) | ![image](https://user-images.githubusercontent.com/48527022/104049646-4bf0cc00-51b3-11eb-99a4-5126ca45d4c5.png) | ⚠️ **Question** - _Should we change the default value from `(not-set)` with hypen `-` to `(not set)` no hypen_ <br><br> _Should we also have this fall back on trying to look for the "{{Click Text}}" secondary, and if no click text found either, than use `(not set)`_
Primary button (old taxonomy), with metadata  | ![image](https://user-images.githubusercontent.com/48527022/104050409-9757aa00-51b4-11eb-8d33-26be7e675245.png) | ![image](https://user-images.githubusercontent.com/48527022/104050422-9d4d8b00-51b4-11eb-8955-4ce3a419b1f1.png) | ✔️ **PASS** <br><br>_although same question here_
Default button (new taxonomy) - with metadata | ![image](https://user-images.githubusercontent.com/48527022/104051049-82c7e180-51b5-11eb-94fa-a26ef4270291.png) | ![image](https://user-images.githubusercontent.com/48527022/104050701-03d2a900-51b5-11eb-8a70-1bd22e4a78ba.png) | ✔️ **PASS** 
Default button (new taxonomy) - with metadata, missing `button-click-label` | ![image](https://user-images.githubusercontent.com/48527022/104050949-63c94f80-51b5-11eb-91fc-fc89646e9d4d.png) | ![image](https://user-images.githubusercontent.com/48527022/104050879-4a280800-51b5-11eb-957a-62b8a7f0a6ba.png) | ✔️ **PASS**
Default button (old taxonomy) - with metadata, missing `button-click-label` | ![image](https://user-images.githubusercontent.com/48527022/104051163-b276e980-51b5-11eb-9ed7-3d5b321d9ddd.png) | ![image](https://user-images.githubusercontent.com/48527022/104051247-d9352000-51b5-11eb-85a0-8121865fcedd.png) | ✔️ **PASS**
Default button (old taxonomy) - with metadata, includes `button-click-label` | ![image](https://user-images.githubusercontent.com/48527022/104051335-f9fd7580-51b5-11eb-84b0-f1da866b1e0b.png) | ![image](https://user-images.githubusercontent.com/48527022/104051369-071a6480-51b6-11eb-958a-0a68e0a85780.png) | ✔️ **PASS**
Secondary button (**only** new taxonomy) - with metadata | ![image](https://user-images.githubusercontent.com/48527022/104051590-5cef0c80-51b6-11eb-8740-3f91641cdba1.png) | ![image](https://user-images.githubusercontent.com/48527022/104051638-6f694600-51b6-11eb-9bb3-eb02bf7960a4.png) | ✔️ **PASS**
Secondary button - no `button-click-label` | ![image](https://user-images.githubusercontent.com/48527022/104051729-99226d00-51b6-11eb-80a3-d40fdf6b1d0a.png) | ![image](https://user-images.githubusercontent.com/48527022/104051741-9fb0e480-51b6-11eb-9d48-dd98ed502077.png) | ✔️ **PASS**
Secondary button - no `'button-click-label'`  or `'button-background-color'` | ![image](https://user-images.githubusercontent.com/48527022/104051835-c838de80-51b6-11eb-8c2f-bb2d11018910.png) | ![image](https://user-images.githubusercontent.com/48527022/104051867-d424a080-51b6-11eb-987e-212417cb10fb.png) | ✔️ **PASS** <br><br> _Same question here regarding omitted `button-background-color` and `(not set)` default value 
Button event with no metadata | ![image](https://user-images.githubusercontent.com/48527022/104052006-0afab680-51b7-11eb-901f-f0bebe26fef6.png) | ![image](https://user-images.githubusercontent.com/48527022/104052040-1817a580-51b7-11eb-92b1-773c8c229d19.png) | ⚠️ _Obviously unlikely with the way we will ultimately build this to fire these events, but perhaps throwing in a generic "Button CTA" default value as well_


### Next Steps
- Finalize and update values for `(not set)` structure
- `{{Click Text}}` Default value if `button-click-label` is unavailable for any reason
- Default value when `button-type` is unavailable for any reason

@bsmartin-ep Awesome job here! Please see the few next steps above and this should be good to update and publish

**Comment by jonwehausen** [comment]
### Latest Design System Conversation
https://dsva.slack.com/archives/C01DBGX4P45/p1610046831011700

**Comment by jonwehausen** [comment]
### Next Steps
- @bsmartin-ep to begin drafting the global event listener code to be included with the footer

**Comment by bsmartin-ep** [comment]
Changes in [your comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14491#issuecomment-756931694) have been made, Jon.  I'll publish Monday since it is in fact 6:00 PM on a Friday.

Looking into the footer JS setup shortly....

**Comment by bsmartin-ep** [comment]
GTM workspace has been published to dev, staging, and live.  We should know have collection on "secondary" buttons.

**Comment by jonwehausen** [comment]
Thanks here @bsmartin-ep. 

Can you provide an update on the progress of the footer JS global event listener code? Thanks in advance

**Comment by jonwehausen** [comment]
## QA Testing on Local - Static Content

cc: @bsmartin-ep 

Description of Interaction | Data Layer Screenshot | GTM Tag Screenshot | Test Status
------------ | ------------- | ------------- | -------------
Click on blue default button on `/coronavirus-research` page | ![image](https://user-images.githubusercontent.com/48527022/106512355-7aef1a80-649f-11eb-9d6c-5e635cfd54d5.png) | ![image](https://user-images.githubusercontent.com/48527022/106512404-8c382700-649f-11eb-829e-c814fbf8759f.png) | ✔️ **PASS**
Click on **continue forward** and **back buttons** on `/coronavirus-research/volunteer/sign-up` page | _no data layer fire_ | none | ✔️ **PASS** - _this button type is a progress button and thus will not fire a standard `cta-button-click` event_
Click on "Go to Chatbot" default button on `/coronavirus-veteran-frequently-asked-questions/` | ![image](https://user-images.githubusercontent.com/48527022/106513099-7c6d1280-64a0-11eb-8b47-1011d42b1cf0.png) | ![image](https://user-images.githubusercontent.com/48527022/106513153-8db61f00-64a0-11eb-9b7b-4cdaba820a69.png) | ✔️ **PASS**
Click on 'Go to resources and support" button from `/contact-us/` page | ![image](https://user-images.githubusercontent.com/48527022/106513419-f9988780-64a0-11eb-8f6a-bed9fa0a36fd.png) | ![image](https://user-images.githubusercontent.com/48527022/106513475-0ae19400-64a1-11eb-879d-c7fb06dc0ff0.png) | ✔️ **PASS**
Click on "Check your status" button on `resources/what-your-decision-review-or-appeal-status-means/` | ![image](https://user-images.githubusercontent.com/48527022/106513862-80e5fb00-64a1-11eb-9dae-0c33dbb9ef83.png) | N\/A | ⚠️ **DOES NOT PASS** - _will want to remove secondary `cta-button-click` event_
Click on "Make an appointment" default button click on VAMC - `pittsburgh-health-care` | ![image](https://user-images.githubusercontent.com/48527022/106514462-4466cf00-64a2-11eb-82cf-b2c505cad7ae.png) | ![image](https://user-images.githubusercontent.com/48527022/106514674-914aa580-64a2-11eb-9e4b-dc91413041e4.png) | ✔️ **PASS** - _maintained existing pre-configured "Patient Task" event action
Click on "See All Locations" white secondary button from `Pittsburgh-health-care` | ![image](https://user-images.githubusercontent.com/48527022/106515148-3cf3f580-64a3-11eb-9e53-a3369e2a04be.png) | ![image](https://user-images.githubusercontent.com/48527022/106515061-19c94600-64a3-11eb-8822-42b9bf287242.png) | ✔️ **PASS**
Click on 'See all stories" white secondary button from `Pittsburgh-health-care` | ![image](https://user-images.githubusercontent.com/48527022/106515603-ecc96300-64a3-11eb-9f7d-79783e3b3b8a.png) | ![image](https://user-images.githubusercontent.com/48527022/106515657-feab0600-64a3-11eb-8dbd-2ce0d102129d.png) | ✔️ **PASS**
WITHIN WIZARD - Click on "File a disability claim online" from `/disability/eligibility` | ![image](https://user-images.githubusercontent.com/48527022/106516546-336b8d00-64a5-11eb-91ce-233a074d7756.png) | ![image](https://user-images.githubusercontent.com/48527022/106516584-40887c00-64a5-11eb-80b4-16c08514b90e.png) | ✔️ **PASS** - **NO DOUBLE EVENT FIRE**

**Comment by jonwehausen** [comment]
@bsmartin-ep Please see case below where `button-type` populated with `primary` even though it's a `default` -- you can find this on staging.va.gov/resources/what-your-decision-review-or-appeal-status-means/

![image](https://user-images.githubusercontent.com/48527022/107531114-840c7580-6b8a-11eb-95e0-01e192d1d4b2.png)

**Comment by jonwehausen** [comment]
@bsmartin-ep Oops! This is actually great -- since our `button-type` classification is driven by the class name as it should be according to the design system, and our `button-background-color` is driven by what color is applied through the CSS. 

This is a great example of where we can report on these types of convention / styling anomalies.

**Comment by jonwehausen** [comment]
Buttons PR has been approved @bsmartin-ep : https://github.com/department-of-veterans-affairs/vets-website/pull/15678#pullrequestreview-587804884
