### ISSUE TITLE
Standardized Design System Components - Form Controls

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#14493]
## Description 

*   Standardize data layer events and variables to track [form control components](https://design.va.gov/components/form-controls) across [www.va.gov](http://www.va.gov)

## Data Layer Specification
- Please refer to design system documentation [here ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-design-system-components.md) for specification 

## Acceptance Criteria

- [ ] Data layer for form control components has been deployed universally

- [ ] QA has been completed

## Definition of Done

- [ ] All appropriate issue tagging is completed

- [ ] All AC completed

**Comment by jonwehausen** [comment]
### TextArea Component [With Analytics] QA

| Description of Interaction | Event Structure | Test Status
| -- | -- | -- |
Type something into the box and click away | ![image](https://user-images.githubusercontent.com/48527022/113940281-35b2d600-97cb-11eb-8918-4573804011f0.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
### TextInput Component [With Analytics] QA

| Description of Interaction | Event Structure | Test Status
| -- | -- | -- |
Type something into the box and click away | ![image](https://user-images.githubusercontent.com/48527022/113940444-76125400-97cb-11eb-9a36-9ddadca8aa4e.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
### Select Component [With Analytics] QA

| Description of Interaction | Event Structure | Test Status
| -- | -- | -- |
Select something from the dropdown | ![image](https://user-images.githubusercontent.com/48527022/113940743-efaa4200-97cb-11eb-9436-64b4c8731954.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
### Radio Buttons [With Analytics] QA

| Description of Interaction | Event Structure | Test Status
| -- | -- | -- |
Option 2 selected from the radio buttons | ![image](https://user-images.githubusercontent.com/48527022/113941045-719a6b00-97cc-11eb-83db-6739cc211f94.png) | ⚠️ **DOES NOT PASS** 

@bsmartin-ep I believe we may want to collect `label` here within the `options` structure to capture the plain language text of the option

**Comment by bsmartin-ep** [comment]
Please re-test @jonwehausen...


![image](https://user-images.githubusercontent.com/62304138/116002253-d32d4880-a5c6-11eb-901e-19617992fd63.png)

I decided to match the component-library params directly.  If there is any confusion, it should be addressed there first.

**Comment by jonwehausen** [comment]
@bsmartin-ep Thanks for correcting -- getting a broken build this AM. 

![image](https://user-images.githubusercontent.com/48527022/116090691-227c8300-a672-11eb-9528-bbc0744148d3.png)

**Comment by jonwehausen** [comment]
@bsmartin-ep Can avoid above, got mine local to build now.

**Comment by jonwehausen** [comment]
### QA ROUND 2 - Radio Buttons [With Analytics] QA

@bsmartin-ep Thanks for your changes here, testing has passed. 

| Description of Interaction | Event Structure | Test Status
| -- | -- | -- |
Option 2 selected from the radio buttons | ![image](https://user-images.githubusercontent.com/48527022/116092974-4640c880-a674-11eb-8023-924a13b1094d.png) | ✔️ **PASS**
Option 3 selected from the radio buttons | ![image](https://user-images.githubusercontent.com/48527022/116093113-683a4b00-a674-11eb-9d54-37de280955a3.png) | ✔️ **PASS**
Option 1 selected from the radio buttons | ![image](https://user-images.githubusercontent.com/48527022/116093370-991a8000-a674-11eb-8346-afec5018fbd9.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
GTM Testing has passed here @bsmartin-ep !

**Comment by jonwehausen** [comment]
@bsmartin-ep to close following production merge

**Comment by bsmartin-ep** [comment]
Merged on 5/11...

https://github.com/department-of-veterans-affairs/vets-website/pull/17122
