### ISSUE TITLE
Standardized Design System Components - Modals

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#14494]
# Google Analytics Implementation 

## Description 
- Standardize data layer events and variables to track [modals](https://design.va.gov/components/modal) across va.gov

## Data Layer Specification
```javascript
    'event': 'int-modal-show',
    'modal-status': this.props.status,
    'modal-title': this.props.title,
    'modal-primaryButton-text': this.props.primaryButton.text,
    'modal-secondaryButton-text': this.props.secondaryButton.text,

```

## Acceptance Criteria
- [ ] Data layer for modals has been deployed universally
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@bsmartin-ep this has been updated with the most up-to-date specification

**Comment by jonwehausen** [comment]
## QA Testing on Local

@bsmartin-ep 

| Description of Test Case | Data Layer | Code Path | Test Status | Test Notes 
| -- | -- | -- | -- | -- |
_Existing GI Bill comparison tool learn more Modal click_ |  ![image](https://user-images.githubusercontent.com/48527022/107373185-3d4c4c00-6ab4-11eb-8b0f-d98ce55955bd.png) | va.gov/vets-website/src/applications/gi/containers/Modals.jsx | ✔️ **PASS** | N/A
_Connected app modals_ | _No modal event fire_ | /va.gov/vets-website/src/applications/personalization/profile/components/connected-apps/ConnectedApp.jsx | ⚠️ **DOES NOT PASS** | _Looks like actual button components rather than modal components_

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

As discussed, can you QA the workspace for this?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000463

You can trigger the dataLayer changes by pasting an event like this into your browser console:

```js
document.body.dispatchEvent(
  new CustomEvent("component-library-analytics", {
    detail: {
      componentName: "Modal",
      action: "show",
      details: { 
            title: "Modal title", 
            status: "info", 
            primaryButtonText: "Continue", 
            secondaryButtonText: "Cancel"
      },
    },
  })
);
```

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep - I'm seeing the event coming into GTM and everything looks good.

Here's a screenshot of the DL:
![image](https://user-images.githubusercontent.com/66263904/110394390-9b277180-8029-11eb-9ec3-486ef20f972a.png)

Here's a screenshot of the GTM tag:
![image](https://user-images.githubusercontent.com/66263904/110394501-c742f280-8029-11eb-9c2a-282a6f98eb6e.png)

**Comment by jonwehausen** [comment]
@bsmartin-ep Here is a test on the sign in modal dataLayer that is populating with `undefined` for modal metadata

![image](https://user-images.githubusercontent.com/48527022/111165680-b5a3a280-8575-11eb-9502-b2882c32e5bf.png)

Let me know if this is a scenario where we won't have a modal metadata. The `(not set)` default value worked great where needed 👍 

### Request
- Could you add in a default value check to check if the auto event variable "Click Text" populates? And if not null to use that, if click text is also null, then we fallback to `(not set)` and use that

**Comment by jonwehausen** [comment]
### QA Test Case

| Description of Test Case | Data Layer Screenshot | Tag Screenshot | Test Status
| -- | -- | -- | -- | 
Click on "Opt-out" modal on `education/opt-out-information-sharing/` | ![image](https://user-images.githubusercontent.com/48527022/111211189-7e98b580-85a4-11eb-95de-dfdfefe55321.png) | ![image](https://user-images.githubusercontent.com/48527022/111211537-e64f0080-85a4-11eb-8c1b-9beb54869c84.png) | ✔️ **PASS**
Click on "Disconnect" modal in connected apps section `/profile/connected-applications` | ![image](https://user-images.githubusercontent.com/48527022/111212338-dbe13680-85a5-11eb-9f20-03fff58fed56.png) | ![image](https://user-images.githubusercontent.com/48527022/111212412-f1eef700-85a5-11eb-8d5f-383910190d73.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
GTM has been published to begin collecting modal opens sitewide

Package containing event listener code will be published in alert box release

**Comment by jonwehausen** [comment]
@bsmartin-ep A post-launch finding for the modal link clicks: 

While this is really neat insight... 😄 -- it looks like are getting a couple inadvertent `int-modal-click` fires on session time outs: 
https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210325&_u.date01=20210325&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:int-modal-click

Here is the location of the session time out modal: `https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/platform/user/authentication/components/SessionTimeoutModal.jsx`

**Comment by jonwehausen** [comment]
After speaking with @bsmartin-ep, in order to make this event more generic and in alignment with the true nature of this development for when modals are shown, we would like to make a slight adjustment to the naming of the modal event. 

We will adjust the name of the modal event from `int-modal-click` to `int-modal-show` -- this has been reflected in the data layer specification within the description.
