### ISSUE TITLE
enable oauth for sentry

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#145]
## Description

A key pain point for onboarding is granting access to Sentry. In a recent update, we lost the ability for users to self-register. This means that we have to use the UI or API to create a user. We also don't have the ability to send email from the environment, so Sentry can't send the invite itself. The sign-up URL also has to be provided to a user via some other method. We believe that this can be mitigated by implementing OAuth and ensuring users are in the VA GitHub org.

Not going to tackle move away from SOCKS as part of this particular issue.

## AC

- [ ] user in the VA GitHub organization can self-register to the vets-gov organization in Sentry

**Comment by annaswims** [comment]
if that ends up being difficult, it looks like it's possible to create users from the command line  https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry-cron-vagov-utility.yml#L79

**Comment by wyattwalter** [comment]
This is turning out to be difficult not because of anything that Sentry is doing, but the firewall at VA is sometimes intercepting the SSL negotiation. We have their certs included in the chain, but it seems that some version of requests or some combination of Python packages is turning a cert verification error into:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /user (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'inappropriate fallback')],)",),))
```

We can't seem to intercept this by disabling the certificate verification. From reading online, it's normal for this error to indicate _any_ sort of SSL or TCP negotiation. It's possible that the firewall is blocking this connection, but it seems to _only_ happen within the requests library on certain containers/virtualenvs. We see it also with our Ansible virtualenv. I can't reproduce the behavior with a stock install of requests + certifi + urllib3 on the same versions.

We are engaging with network engineering folks next to see if there's anything they can provide for troubleshooting.

**Comment by njdister** [comment]
I discovered this occurs when pyOpenSSL gets installed.  If requests detects that it's installed, it automatically monkey patches urllib3 to use pyOpenSSL instead of the system OpenSSL library.  This turns out to be troublesome for us since the TIC does not support whatever smaller scope of SSL ciphers pyOpenSSL expects.  Removing pyOpenSSL resolves the issue though I have not performed full testing of sentry itself, only of the requests library against the Github API.

**Comment by ricetj** [comment]
@tskinn is this ok to close now?

**Comment by tskinn** [comment]
@ricetj  No, not yet. We decided to separate moving hostnames and turning on github oauth. I just moved hostnames last night so now I think after I finish updating Jenkins hostname tonight I plan on turning on sentry oauth tomorrow night hopefully.

**Comment by ricetj** [comment]
Live
