### ISSUE TITLE
Form Detail Page: Apply invalid form error message to `400 bad` pdf form link

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14525]
## Apply invalid form error message to `400 bad` pdf form link on form detail pages

**User story:**
As a Veteran, when I try to download a form, if the form cannot be downloaded or opened because of a `400 bad` form problem, I want to get a message telling me so I'm not clicking on the form link over and over. 

**Example:** 
On this About VA form 10-0388 page https://www.va.gov/find-forms/about-form-10-0388/ - the PDF form link https://www.va.gov/vaforms/medical/pdf/10-0388%cover.pdf goes to a 400 bad request page sometimes, but sometimes doesn't do anything - doesn't open, doesn't download, no message, so the user can't tell what is happening. 

For `400 bad` situations, please give the user the same  experience used on [Ticket #12181](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12181) -- the message text +  mailto: experience.

**Reference slack thread:** 
https://dsva.slack.com/archives/CUB5X5MGF/p1602079540048500?thread_ts=1602004504.036500&cid=CUB5X5MGF

**Comment by MarciMcGuireGCIO** [comment]
Moving from Public Websites to Decision Tools; changing assignees as appropriate.

**Comment by MarciMcGuireGCIO** [comment]
Adding link to this Slack thread that contains useful information: https://dsva.slack.com/archives/C01DWJFD45D/p1609278689012400

**Comment by zacharymorel** [comment]
Through development, we have discovered that we cannot handle 400 errors for forms that are hosted on a different domain other than **va.gov**. However, for every form that shares the same domain as va.gov, we will have error handing.

**Comment by MarciMcGuireGCIO** [comment]
Thank you for the update.  This is something that you have yet to do, or it's already done?

**Comment by zacharymorel** [comment]
> Thank you for the update @zacharymorel . This is something that you have yet to do, or it's already done?

It's "done", currently going through peer review.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO this is ready to be validated at https://staging.va.gov/find-forms/about-form-10-0388/

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel the PDF download link doesn't seem to do anything in IE on Windows, but works perfectly in Chrome, Firefox and Edge.  It also works in Safari and Chrome on iPhone 11.

**Comment by zacharymorel** [comment]
Can you perhaps do a video capture here?

**Comment by MarciMcGuireGCIO** [comment]
https://user-images.githubusercontent.com/73354907/104780750-42390c80-574f-11eb-806a-f2e8fc8bbd47.mp4

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel let me know when you're done so I can remove the video. Thx!

**Comment by zacharymorel** [comment]
Definitely does, thank you!

**Comment by zacharymorel** [comment]
I guess well be using https://github.com/department-of-veterans-affairs/va.gov-team/issues/17941 after all to fix the IE bug!

**Comment by zacharymorel** [comment]
Everything else good?

**Comment by MarciMcGuireGCIO** [comment]
Yep!
