### ISSUE TITLE
Documentation request for On this page component

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#14527]
### What is your documentation request, question, comment, or issue?

The design system team needs assistance with checking a piece of documentation for the "On this page" component: https://design.va.gov/components/on-this-page-jump-links

I'm writing documentation for the sections: "Usability guidance: how to" and "Accessibility" 

I spoke with VFS designers, product owners, and accessibility specialists to gather information. I followed the format of the USWDS documentation for their design system components. Ex: https://designsystem.digital.gov/components/card/

Note: I based the first accessibility point after this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7877

Here is the current draft:

**Usability Guidance**
- **Make sure to keep the first link and its corresponding heading close together.**  Keeping the links and headings in close proximity helps users make the connection that the links correspond to sections on the page
- **For content pages, have a minimum of 2 H2 sections.** The article will have to have a minimum of 2 H2 sections in order to display the On this page component links.
- **Do not use components for very short sections if we can display sections on one screen.** If using this component for 2 sections, do not use component if sections are very short. 

**Accessibility**
- **Heading levels should only increase by one.** Proper order of heading levels convey the structure of the page for users who use screen readers.  When heading elements are applied correctly, the page becomes much easier to navigate for screen reader users and sighted users alike.
- **Focus should be on the destination.**  When a user clicks an item in on this page component, focus should move to the heading that it’s linked to. 
- **Allow enough spacing between components.** Space should be 1.5 rem (36px) from the bottom of the descender to the top of the ascender

**Comment by lianilychee** [comment]
hey @CrystabelReiter -- thanks for the request!  Amy is aiming to turn this around by the end of this week.

**Comment by amygoldman** [comment]
Hi @CrystabelReiter! Here are my suggestions: https://docs.google.com/document/d/1Hqfzap9VhVz6Qo3tmaoLXflnXDKtQ76TukffP6lbtZw/edit?usp=sharing 

If you have any trouble opening the link, let me know. I can also post my feedback here if that's easier for you.

**Comment by CrystabelReiter** [comment]
Thanks @amygoldman ! it looks I need to request access.

**Comment by CrystabelReiter** [comment]
Got access to the document! thank you everyone

**Comment by caw310** [comment]
Example of the component in global sense. 
https://www.va.gov/pittsburgh-health-care/health-services/ 

Make a react component. Chis and Brooks to look into this.

**Comment by lianilychee** [comment]
Hello!  Wanted to check in on this - do yall still need content review / may I remove Amy from the list of assignees?

**Comment by caw310** [comment]
I think you can remove Amy from the list of assignees.
