### ISSUE TITLE
[Design] HLR New Wizard Design

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#14531]
## Issue Description
As a designer, I need to follow the established patterns from the New Wizard team and translate that into a design for our HLR wizard.

Assumptions:
1. Public Websites team is getting this through design intent/(maybe counsel) pattern approval (skip buttons, overall flow/behavior)
2. BAM1 does UAT specific to HLR
3. HLR UAT may be delayed until we know more about timeline for this from the public websites team

## Acceptance Criteria
- [ ] Update HLR UAT plan to reflect testing of the new wizard (hold off on doing this until we know timeline of new wizard design)
- [ ] Design of new wizard has been completed
- [ ] A review of the design by the 'New Wizard Implementation Team' has been completed (content, IA, accessibility, etc etc)

**Comment by luke-gcio** [comment]
Kevin attending some of the design meetings - putting in progress.

**Comment by kevinstachura** [comment]
The (new) design of the HLR wizard has been completed! It can be viewed here:

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/430329538_HLR_-_Info_Page_-_New_Wizard_-_First_Question

**Please note that this still needs to be reviewed by content and checked off by IA as well.**

IMPORTANT NOTE: We will not have a 'skip wizard' link in this one because we are gathering necessary info via the wizard as Robin points out [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13382#issuecomment-697441357).

@peggygannon we are ready for content review! Please let me know if you would like to use this ticket to comment on content changes or if you would prefer a new ticket or existing ticket for doing so. We have another HLR-specific one out there (#13382) so let me know what you would prefer!

@mnorthuis I believe I have followed the IA you have laid out but would you please just take a look at the flow and ensure I have followed your advisement correctly in the HLR wizard flow?

I will be checking both the Invision comments and the comments left on this ticket so please feel free to give feedback whichever way you prefer. Thanks so much!

**Comment by peggygannon** [comment]
Hi, @kevinstachura My content feedback for the HLR wizard is tracked here: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/13398

**Comment by mnorthuis** [comment]
Hi @kevinstachura, the breadcrumb in the prototype is missing a level - it should include the static HLR page in the hierarchy.   Details here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-higher-level-review.md

Breadcrumb on the form should be: 
Home > VA decision reviews and appeals > Higher-Level Reviews > Request a Higher-Level Review

"Higher-Level Reviews" would take the user back to the HLR static page: https://www.va.gov/decision-reviews/higher-level-review/

**Comment by kevinstachura** [comment]
Ah, thanks for catching that @mnorthuis! I have updated the design of the HLR wizard here:

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/430329538_HLR_-_Info_Page_-_New_Wizard_-_First_Question

The breadcrumbs should now reflect your feedback. Please let me know if I missed anything else!
