### ISSUE TITLE
VSP content feedback - Usability prep - Health care questionnaire

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#14552]
## User story
This ticket captures VSP content feedback on Health care questionnaire

Prototype links: 
https://preview.uxpin.com/a15205c1bedcdfc8fe46fed26c22fa731cab8ae0#/pages//simulate/no-panels?mode=cvhidm
https://preview.uxpin.com/e9e0dc597bb076e74db05f77d35306496a89fca2#/pages//simulate/no-panels?mode=cvhidm

## Acceptance criteria
 - [x] VSP/Peggy provides content feedback and recommendations for the form/tool.
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x]  Product team leaves any comments about feedback they decide not to take
- [ ] Peggy checks form after content feedback has been incorporated

**Comment by peggygannon** [comment]
@kristenmcconnell Here is feedback on the questionnaire form itself. Will drop in more feedback on the landing page content shortly. Let me know if you have any questions. Or want to discuss in person. 


*Feedback key
Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement*


------

*Must*
General/global feedback

1. Our style for H1, H2, H3, labels, button is sentence case. Please sentence case the following; 
-Douglas VA medical center 
-Veteran information
-Prepare for your visit
-Ask another question

2. Hyperlink phone numbers 

*Should*
Current H1: Upcoming appointment questionnaire
I recommend changing this TO: **Questions for your upcoming appointment**

Landing page
Content feedback TK


------

Prepare for your visit screen

Update first label to be more conversational TO: 
What's the reason for your visit? 

Ranked questions for your provider
Recommend updating this TO:  **Additional questions for your provider**

Trying to avoid “ranked” as it isn’t plain language


QUESTION: Can user add more than 1 question? If so I recommend giving them a number, so they're able to prioritize. For example, 

Do you have a question you want to ask your provider? Please enter your most important question first. You can enter up to [xxx] questions. 

-------

Emergency alert
Please update the first sentence TO: 
**If you have an emergency or urgent medical need,** call 911 or go to the nearest emergency room.
Hyperlink 911
Put “or” in Bold

-----

Review detail page

Looks like this page is missing Submit button 
Missing the privacy link boilerplate language and checkbox

------

Confirmation page
Update alert to:  
{alert}
**Your information has been sent to your provider.**
We look forward to see you at your upcoming appointment. 
{end alert}
 

In blue box I recommend updating this sentence to be active: 
We sent your information to: 
[Name of VAMC]

------

Need help footer

Is this the content correct in this footer?  I'm not sure what local coordinator is referring to. also, we should be sure that we have correct phone numbers. 

the general VA number is 844-698-2311.. is this the place we want to send users if they have questions about their form?

**Comment by kristenmcconnell** [comment]
Regarding the "Missing the privacy link boilerplate language and checkbox" on the review page, we are going to be going through a privacy threshold assessment, since our vision will effect the Veteran's health record. We have outstanding questions about that. 

All other feedback has been incorporated.

We are set to have our first testing session on Thursday.

**Comment by peggygannon** [comment]
@kristenmcconnell OK, thank you for the update. I will be uploading the landing page content later today.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell I've update the top of this ticket with the content for the landing page. Please also note, I've tweaked the H1 some more. As discussed on the VSP call, I've tightened up the language and removed the subway map. It's such a short "form" that I don't think it needs the subway steps. 

Let me know if you want to discuss my recommendations on a call.

**Comment by kristenmcconnell** [comment]
@peggygannon Thoughts on using the very condensed "don't use in case of emergencies" wording that you created for the landing page on the review page as well. I like how simple it was and I liked the Note form.

**Comment by peggygannon** [comment]
Hi, @kristenmcconnell Yes, agree. I think we could do that on the review page too. 
Only people who have already made an appointment will get a link to this questionnaire, so I think using the condensed message makes sense within the questionnaire.

**Comment by kristenmcconnell** [comment]
Great. Your feedback has been incorporated into the mobile and desktop prototypes for tomorrow's sessions (except I didn't add the new don't use in case of emergency design to the review page of the desktop prototype). I will after these research sessions, but I don't believe that it will impact the quality of our results for tomorrow. Thank you.

**Comment by kristenmcconnell** [comment]
@peggygannon - Can we close out this story?

**Comment by peggygannon** [comment]
HI, @kristenmcconnell Yes, we can close this out. 

The only open question is about the New Help footer. I wanted to double check that the numbers/info in the footer are correct? We usually use 711 for the TTY number so want to circle back on that. 

Need help footer

Is this the content correct in this footer? I'm not sure what local coordinator is referring to. also, we should be sure that we have correct phone numbers.

the general VA number is 844-698-2311.. is this the place we want to send users if they have questions about their form?

**Comment by kristenmcconnell** [comment]
@peggygannon I have a meeting with the team tomorrow and am bringing this topic up again. I will be sure that we will get it corrected (if need be).

**Comment by peggygannon** [comment]
@kristenmcconnell ok, thanks!
