### ISSUE TITLE
Create PDF for 674 Submission

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#14551]
## Background
With a separate form being submitted when 674 tasks are selected, we need to create a PDF for the 674

## Considerations
- Veteran name and address are reusable
- Field names are probably different compared to the 686?

## Tasks
- [x] Identify fields
- [x] Get fields from payload and map to pdf fields

## Acceptance Criteria
- [x] A PDF is generated for the 674 form

**Comment by kathleencrawford** [comment]
PR submitted here: https://github.com/department-of-veterans-affairs/vets-api/pull/5514
