### ISSUE TITLE
Navbar needs multiple tabbing to get past certain items 

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#14562]
## What happened?
While using keyboard to tab focus through items on the home page (using an Android simulator), I found that I had to tab twice when Home was in focus to proceed.

I found that when I first tabbed into the nav bar, the white background went to a light gray while the Home button was focused upon. The next tab kept focus on Home but the background changed back to white.  The next tab after that, focus moved to Appointments.  This happens on the Profile page, as well.

On the Appointments and Claims pages, a similar thing happens but with the Profile button. When tabbing to the profile button in the navbar, the background of the navbar is white. On the second tab while on Profile button, the background of the navbar changes to gray. The next tab wraps the user back to the Home button (because there is currently no content on the page) and the navbar background changes to white again.

## Specs:
Using a Pixel 3 Android simulator.

## Steps to Reproduce
Tab through navbar while on home, appointments, claims and profile pages.

## Desired behavior
Focus will change each time the tab key is pressed to enable feedback from the screen reader.

## Acceptance Criteria
Focus will change each time the tab key is pressed to enable feedback from the screen reader.

**Comment by digitalken** [comment]
@komaly15 - I'm really running into a similar issue with the navbar after following "Contact VA" button on the home page (while testing the back button.). Once on that page, I need to tab about 7 times on the Profile button in the navbar in order to loop through (via tab) the page again.  The page is pretty sparse, so maybe that has something to do with it?

**Comment by digitalken** [comment]
Logged against:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13862

**Comment by esther-k** [comment]
**11/24**

PASS- on iOS and Android. Keyboard focus changes each time the tab key is pressed without multiple tabbing
