### ISSUE TITLE
Access for Ben Grider

### ISSUE THREAD

**Issue by bdgrider** [department-of-veterans-affairs/va.gov-team#14577]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Ben Grider
- Please Provide your email.
   > benjamin.grider@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >Pivot, Software Developer, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWiRAfHnBYTQ6i1NtqdXMXwD3ERxQWtQhZmil+40wJoQTNUz2vtd9YjYHDzxsifkiw5135LxQWpiEbsx7TNJM2uxc6JHAkPuSIxf4llwoVUJGDcH6vOSXBsxn8SPMYZGAGBng0polilk4nW8UGUYoETvrAh3kuan8/NaJSOrOe5M8z/9pXw5Zj91Xg6LXi7VNm+B3j+lJXmHKKotBASpX+IPaRxuONfa2jnUK2Wf8eh9+Eo2kDFaRGkvGJ8PYTI1MXgL2NlhWymUTNmD1hCt+3XYQMuwKa4IAx3IZNWQG1GUnUzx8DXRSAIfd6fbTENtbcGF5OJ0yoxj5b59DwoQt3lKH33KgWa1cg5OJ/XrvlmaGFR5anApKyxV0up95QvpQwFyQTTV46ZqlbmwlxNrbVVmvxPx/De0ACivNgNd7/eZtA+YMo2plZRwKilC4+wqowpXTKKzmCK65ecgOf+xXfKG8wqPwSwkPX7GLRX9R5HzNUw9qE23oYLLd1tceZk6E= ben@ben-VirtualBox
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
   > Required for support of vets-api and related projects as part of the Lighthouse contract

**Comment by jbritt1** [comment]
Working on SOCKS access now. 

For AWS Access:
User: Ben Grider
COR: Cecilia Lee
Approval required: @Jeff-Hayter

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by bdgrider** [comment]
Should I have received AWS credentials via email? Cannot seem to find them.

**Comment by bdgrider** [comment]
It appears I was able to add socks as a host but I cannot connect when testing per the instructions listed in the guide 

![image](https://user-images.githubusercontent.com/6391122/97615909-44ae8480-19f2-11eb-80ef-dde4382af62b.png)

**Comment by jbritt1** [comment]
> Should I have received AWS credentials via email? Cannot seem to find them. @jbritt1

Your AWS access is awaiting approval still at this time.

**Comment by jbritt1** [comment]
> It appears I was able to add socks as a host but I cannot connect when testing per the instructions listed in the guide
> 
> ![image](https://user-images.githubusercontent.com/6391122/97615909-44ae8480-19f2-11eb-80ef-dde4382af62b.png)

Any reason why the lowercase `n` was used here instead of `ssh socks -D 2001 -N`?

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
