### ISSUE TITLE
[Public Websites/Learning Center MVP 1.0] VSA-QA Test Plan

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14582]
## Product/Feature summary

Validate QA test plan in support of Learning Center MVP 1.0.  The 1.0 beta launch is unique in the sense that it will be an interactive release and would need to be conducted in the 'Demo Environment' since we no-longer have the 'basic-auth' release capability. the environment URL is http://learningcenter.demo.ci.cms.va.gov/
the final/real URL for the LC homepage will be available once the LC homepage is created in the CMS.

Product/Feature Outline: [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp)
Product/Feature Epic: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10111
Product/Feature Pre-Launch Checklist: [Review Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)
Product/Feature Copy deck(s): [Review Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md)
Product/Feature Design prototypes: [Mural Designs](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)
Product/Feature Copy Decks: WIP

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Ryan Thurlwell, Liz Lantz
Content/IA: Beth Potts, Content / Mikki Northuis, IA
Front-end: Nick Sullivan, Kelson Adams
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs (ideally, use [this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md) from VSA Design Lead).  IMPORTANT for authenticated-experiences: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

[Completed - Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/product-use-cases-template.md)

## How to configure this issue

- [x] Product Manager added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Actual Test Runs completed on Staging \[or optional [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by tlei123** [comment]
@brianalloyd @MickinSahni , would this Use Cases ticket #11581 be the one for this Test Plan?

**Comment by brianalloyd** [comment]
@tlei123 yes, the that's the ticket for the test plan use cases.  Let me know if you need anything else in support.

**Comment by jenniferlee-dsva** [comment]
Use case doc is complete. Linked to it above in the og ticket.

**Comment by tlei123** [comment]
@brianalloyd , all test-runs are now completed.

Here are the Test Plan, Test Cases, and Report links for Staging Review:
[Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/685)
[Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&group_id=214)
[Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/142)
[Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/143)

Logged the following defects, mostly breadcrumbs:
#15559 
#15562 
#15565
#15566
#15567 
#15625 

cc @pjhill

**Comment by brianalloyd** [comment]
@tlei123 thanks for the update and support.  CC @jenniferlee-dsva
