### ISSUE TITLE
Terraform Improvements / Module refactoring

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#14580]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a DevOps Engineer, I need simple and well-constructed Terraform modules and documentation so I can easily use existing modules and write/create new modules if necessary.

As a DevOps Engineer, I want to make sure that Terraform module development processes are automated so I can reduce the amount of manual work that my team will need to do.

As a DevOps Engineer, I need to eliminate unnecessary boilerplate and copypasta so modules can be simpler and the number of lines of code I need to write and maintain can be less.

## Hypothesis or Bet
**If** _Terraform modules are simple and easy to use_ **then** _We expect implementation of services and infrastructure to be quicker and easier_.

## OKR
_Which Objective / Key Result does this epic push forward?_
O2-KR1

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jbritt1** [comment]
@dginther have we accomplished this at this time? Should we add an item here to remove the `deprecated` directory within the devops repo that houses the old versions of Terraform modules we were using? I believe all of those have been moved into their own respective repositories and are no longer being leveraged, is that a correct assumption?

**Comment by dginther** [comment]
This is complete.
