### ISSUE TITLE
Access to AWS for LinnJS

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#14597]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Justin Linn
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Name of Team: Caregivers
   > Role: Sr Front End Engineer
   > Company: GovernmentCIO

- [Grant AWS Console access?] Yes
I need AWS access to see production error logs on cloudwatch. Our team only has two developers so I need AWS access for when my Backend developer (@kevinmirc) is out of office.

**Comment by jbritt1** [comment]
For AWS Access:

User: Justin Linn
COR: Mary O'Toole
Approval required: @Jeff-Hayter

**Comment by mlighdc** [comment]
@Jeff-Hayter Can you please approve this request? Let me know if you have any questions. The team's backend engineer is going on vacation and would like the frontend engineer to have access. Thank you!

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
