### ISSUE TITLE
Access for Taylor Rassmann

### ISSUE THREAD

**Issue by taylorrassmannlibertyits** [department-of-veterans-affairs/va.gov-team#14596]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecelia Lee
- Please provide your name.
   > Taylor Rassmann
- Please Provide your email.
   > taylor.rassmann@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse (Team Axolotl), Senior Software Developer, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJOdN0ruzXHTAZhve+HXab6ds/ix95sH9JHjHL+PthnTakRxQ74QLN5lQ1+XxEBI18cHIHhX3Fy4FAC3BW82XYwGj0pyYffZJo2K+JuDx+pu9QIDKQm09dSHiw6eMT0dpv9BfHjZ6wY3PLgcGx8HDBOTCQCU072n3KvZWSLuEUaDUGWQZBi3hUEi6vxsnC3BrLBriRCozRjg0fMmynBRLmqXBzaRWvFI9qKBJCctmuLPCrXu4fvHD46ofvLR4K2R+FPnv5or+pge1+EwxGN5Suk9LctcVYg1NaafSlccsHOoVdwbKKhzdeKXeNUkkUzWlfMbSWz7MAf3sZ0A5Ydjadh0muh8xfT1IKIUqvRHu7xurMJJc0DunqVN2q/CSdigCdksf+v4k1zBTZcp0yIGsyqGIg+d0PN1irfGIEV8DkhzsA7jXSreYlVQ2kjcwmtCObduDZoetYmbOs3gG2PL8Nzpej34P0i8wAtmoj1AZvjNAlifd7uICAWVAQJ9aLOHBYnSu5tea9RtTLoUg2Y7aY1zuggOYds1zQJrBXbTtDj84D+ZUDFh4Lg3rRDbt0Gu8GXCJQe5SqsOpWJafisN1DIM5AY/onQzkJ29CPr5MttTreqZZEOGtL3el/q/Sfe7ED1Ynwj/vvlrzWC5k8F3xZmYkSNAnBx61zvLkDAEBj3w== taylor.rassmann@libertyits.com
```

- Grant AWS Console access?
  > NO

**Comment by taylorrassmannlibertyits** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by taylorrassmannlibertyits** [comment]
Thanks @jbritt1 ! I set up everything successfully!
