### ISSUE TITLE
Missing new section for health_care_local_facility

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#14606]
## Issue Description
Due to new fields there are big sections missing

## Example:
![Screen Shot 2020-10-08 at 11.25.47 AM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/a0cd2160-c16f-4df0-b89c-4119c459a04f)

## Example File
`/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/index.html`

## Tasks
- [x] Figure out why there are missing sections.
- [ ] Resolve issue, and verify the output matches the GraphQL content build.

**Comment by mmiddaugh** [comment]
@mpelzsherman is this related to the recent changes to the Facility health service content structure? Is this considered "drift"?

**Comment by mpelzsherman** [comment]
I am pretty sure that [this block of code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/facilities/facility_health_service.drupal.liquid#L30-L34) is what accounts for the “big missing sections” in the facility pages.

**Comment by mpelzsherman** [comment]
Bumping estimate to 8 due to complexity of data types.
