### ISSUE TITLE
Testing Needed - v2 facility selection page - sort by geolocation

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14600]
Last iteration of the new v2 facility selection page. Allows for Veteran to use their geolocation (based on their browser) to sort the facility list. 
- implementation ticket this maps to - [13269](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13269)
- the relates to [this epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12951) & is part of testing for these two additional testing tickets:
    - test v2 facility selection page - [flat list in alphabetical order](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13306)
    - test v2 facility selection page - [sort by distance ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13267)

**Comment by beth-wodzinski** [comment]
Pass. this was covered by the other 2 tickets and it's all good.

**Comment by narin** [comment]
Thank you @beth-wodzinski.  One thing I wanted to confirm is that we've tested the different eligibility scenarios (e.g. user has to have been seen within the past X months to request an appointment, and user is over request limit).  If either you or @marcynadeau have tested these, we'll move forward with our 20% roll out.  Thanks!
