### ISSUE TITLE
Define and prioritize use cases for how to authenticate users for use in Release\Feature Toggles

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#1460]
As an administrator, I would like to understand the use cases for having admin users in the release\feature toggle tool so that we can design methods to allow\deny authentication in the best possible way.

**Comment by rianfowler** [comment]
add auditing and individual access controls: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1764

add user groups and gate access to toggles by group: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1765
