### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14615]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.
bethpotts25@gmail.com

If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
_Please list any requirements, if any._

## Date Required
_Please share the date you require access._

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bmcgrady-ep** [comment]
@bethpotts if you can select "Use my current email address instead" on [this page](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp) - that connects your VA email with a google account.

**Comment by bmcgrady-ep** [comment]
@bethpotts - Following up on this request, were you able to connect your VA email with a google account?

**Comment by joanneesteban** [comment]
@bethpotts we're closing this ticket, but we can reopen if you don't have access!

**Comment by bethpottsVADEPO** [comment]
@joanneesteban I successfully set up a google account with my va email, now what's next? I see the Welcome to Google Analytics screen.

**Comment by bmcgrady-ep** [comment]
@bethpotts - Thank you for the update here. What is your VA email? I'll provision access to GA once I have your VA email. Thanks!

**Comment by bethpottsVADEPO** [comment]
Thanks for your help! It's beth.potts@va.gov

**Comment by bmcgrady-ep** [comment]
@bethpotts - Okay, you have been added to Google Analytics and should be receiving an email giving with an invitation to Google Analytics. Let me know if you have any trouble with your access.

**Comment by bmcgrady-ep** [comment]
Closing out this request. Feel free to reopen if you have any trouble with your access.
