### ISSUE TITLE
[SCREENREADER]: GIBCT® - Heading levels on school and employer detail views need to increase by one

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1461]
## Description

Heading levels are being skipped in the content areas on VET TEC provider detail views. This can be confusing for screen reader users who rely on headings to navigate content by importance. Screenshots attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screen reader user, I want to hear headings properly nested in the content. 
* As this user, I want to hear one heading level three, then heading level fours, with additional headings nested as appropriate.
* As a visual user, I do not want the layout to change, only the semantic heading levels.

## Environment

* Windows 10
* IE11, Chrome
* JAWS
* https://staging.va.gov/gi-bill-comparison-tool/profile/20020911 (example employer)
* https://staging.va.gov/gi-bill-comparison-tool/profile/15001027 (example school)

## WCAG or Vendor Guidance (optional)

* [VA.GOV design system font size utility classes](https://design.va.gov/utilities/font-size)

## Screenshots or Trace Logs

![Screen Shot 2019-08-30 at 2 39 17 PM](https://user-images.githubusercontent.com/934879/64047456-74cf6e80-cb34-11e9-8533-b53c1bfe915a.png)

**Comment by sonntag-adam** [comment]
Employer
![Screen Shot 2019-09-10 at 7.14.39 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/82bd4d8a-befb-4662-b337-ffbe7c2c73a8)
##
![Screen Shot 2019-09-10 at 7.15.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c1e50d5f-793d-4fa7-92b9-13b2230b8c9a)
##
![Screen Shot 2019-09-10 at 7.15.13 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/be366cbb-587d-41dc-90c4-23d431f3a446)
##
School
![Screen Shot 2019-09-10 at 7.16.36 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9a10410a-6962-43c0-9602-e214c27d7833)
##
![Screen Shot 2019-09-10 at 7.16.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9474f83e-5957-4c09-bf43-b1ea255d8c59)
##
![Screen Shot 2019-09-10 at 7.16.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d0802e1b-1c7d-4088-a6a3-b99d53406d2c)
##
![Screen Shot 2019-09-10 at 7.19.13 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/fc9fa728-19eb-4ab4-9570-4163b7c56996)

**Comment by 1Copenut** [comment]
Added a comment to PR for one additional update: https://github.com/department-of-veterans-affairs/vets-website/pull/10699#issuecomment-530090897
