### ISSUE TITLE
Analytics Reporting Request for [Direct Deposit for Comp/Pen]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#14631]
## Description
- Is this request for Google Analytics implementation or QA?
**GA Implementation**

The authenticated experience team was looking at Direct Deposit analytics and was trying to see if it would be possible to get data/analytics surrounding utilization/enrollment. For example, what % of elligble DD users have completed DD profiles?

### Who is this request for?
**Matt Shea - Samara Strauss**
**#vsa-auth-exp**
    
### What team/project is this work for?
Authenticated Experience - Direct Deposit

### Provide the Domain where Google Analytics needs to be implemented
www.staging.va.gov
    
### PII is passed in URL or title tag (Yes/No)_
No
    
### Please provide any upcoming deadlines or important milestones
We have launched Direct Deposit on VA.gov and already have analytics, but would like to see if this data would be possible to get.

### Website Interactions to Track
1) Percentage of VA.gov user profiles with Direct Deposit info populated
Why: We want to see what % of total DD elligble users have completed profiles
 - % of direct deposit-eligible users with completed profiles/Total users

[Direct Deposit Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/QA/Staging%20Users%20-%20Test%20Cases.md)

Additional Comments:
possible approach:
% of users with edit fields in DD (enrolled)
% of users with "add" field in DD (non-enrolled)

Concern:
It may only be possible to obtain this data when users are logged in, therefore making it hard to get this data or accurate data.

 ## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by mshea0606** [comment]
@MickinSahni @Samara-Strauss for awareness

**Comment by joanneesteban** [comment]
Thanks, @mshea0606 ! Acknowledging receipt. We'll reach out with any questions.

**Comment by jonwehausen** [comment]
Thanks again here @mshea0606, 

We would like to get a meeting on the calendar to understand the details of this request further. 

Could you provide for us a few dates & times to meet with you and the team for sometime next week? Thank you

**Comment by mshea0606** [comment]
@jonwehausen, I've made some changes to the request after getting more information. This request is for Direct Deposit (comp and pen). We are trying to see if we can create a metric or analytics around utilization/adoption. I will set some time up for us to discuss this request further. cc/@Samara-Strauss

**Comment by jonwehausen** [comment]
Thanks for the time today @mshea0606 

Got a chance to dig into this data a bit more here: 
 - There is certainly opportunity for us to work together on a solution where we capture more direct deposit specific eligibility data to improve our ability to segment these users more strictly and ultimately surface a more precise eligibility conversion %. As a first high-level step, let's take a look at the criteria and from there can discuss how the system interprets this criterion and how we might expose to GA for future analytics use. 
 - Per our discussion, with data we do have available today, and confirming LOA level 3 at the very least can serve as identification of those who are definitely eligible: 
     - @bsmartin-ep As a baseline, I gave [**this query**](https://console.cloud.google.com/bigquery?sq=86772881199:d0df35161f9f43e78efde4b00ffad7f7) a shot to first capture users with a LOA level of 3 between 1/1/2020 - 10/1/2020 and then used as a sub-query over the same time period as a filter to only consider these folks among those who have successfully adder their direct deposit information. Could you give this [BigQuery query a review](https://console.cloud.google.com/bigquery?sq=86772881199:d0df35161f9f43e78efde4b00ffad7f7) when you have a moment and let me know your thoughts? We can then discuss if this is viable to share as a high-level preliminary baseline. 

cc: @joanneesteban and @bmcgrady-ep for visibility

**Comment by mshea0606** [comment]
@erikphansen and @lihanli can you please explain how we determine DD eligibility on the Front end and Backend per @jonwehausen's comment above?  Erik mentioned that we can record these two GA events: 1) user is eligible to set up DD but has not set it up 2) User is eligible and has set up DD to get a better understanding of DD utilization.

**Comment by lihanli** [comment]
on the backend if a user is loa3, has MFA, has an EDIPI, and has a participant ID then they are not blocked from DD

**Comment by erikphansen** [comment]
On the FE, there are many reasons to not qualify for DD. As Lihan said, they will be blocked from even getting data from the BE if they aren't LOA3 and have MFA turned on. We don't even call the BE in that scenario and the BE won't even return useful info if it was called.

Things then get a little more complex on the FE:
- if the data from the BE shows that they have bank info set up, well, that means they have set up Direct Deposit already.
- if the data from the BE comes back without bank info but they have a payment address set up, we infer that they are _eligible_ to set up Direct Deposit ([this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3992) was intended to be a new way to determine if a user is eligible for Direct Deposit)
- a user can also be blocked from accessing their Direct Deposit info if they are flagged as having a fiduciary, flagged as incompetent, or flagged as being deceased.

My plan would be to send events to GA when:
- the BE data shows that they already have Direct Deposit set up
- the BE data shows that they do _not_ have Direct Deposit set up, but are eligible since they are getting payments via paper checks (ie, have a payment address set up)

**Comment by jonwehausen** [comment]
Hi Guys, 

Thanks so much for your notes here, this was very helpful context! 

@mshea0606 after taking a look back at the data we currently have available around eligibility -- and hearing the rest of the team members feedback about what's possible, it's clear we're still very limited on what we can provide today / interpret today with LOA level alone and would rather invest in revamping the data layer to support these kind of questions in the future than piece-mealing a query for only a portion of what goes into eligibility criteria. 

As a next step, I have created issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/14631 as a placeholder for a revamped data layer based on user attributes we might collect to understand user eligibility. 

We would like to learn more from you team based on what was said here around what is available / makes sense for us to collect as user attributes.
