### ISSUE TITLE
Nav bar: Appts is listed before Claims

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14637]
## What happened?
The nav bar page options are currently listed (L-R) as: Home, Appointments, Claims, Profile

## Specs
Using a Pixel 3XL Android simulator.

## Desired behavior
The correct order is: Home, Claims, Appointments, Profile

![Screen Shot 2020-10-08 at 5.54.37 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/8f9355c8-75b6-4a2e-87c2-088f8824d8c6)

**Comment by digitalken** [comment]
PASS 10/12/2020 - Navbar now displays correct ordering of "Home, Claims, Appointments, Profile".
