### ISSUE TITLE
1995: Update button and question content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14639]
As a developer, I need to update the 1995 so that it is up to date with the current DEPO patterns and practices.

## Assumptions:
1. There will be no prod flag or feature flag for this work.
2. Spool file updates, if necessary, will be handled in a different story.

## Acceptance Criteria
1. In chapter 3, the "Add Another Service Period" button is replaced with "Add another service period"
2. In chapter 5, the "Do you have a parent who is dependent on your financial support?" question is replaced with "Do you have a parent who depends on you for financial support?"

## Supporting Artifacts: 
1. [Mobile Prototype v3](https://bahdigital.invisionapp.com/share/VUIAEXFPHBC#/screens) as of 09/23
2. [Content Doc v3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ad9acc27708637115a20e2bb502026faf1112604/products/education-careers/application/1995/content/1995-content-doc-v3.0.md) as of 09/23

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14607

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-16 at 11.51.38 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7e57a112-9a1f-4aba-a4f7-9aafe05b467d)
##
![Screen Shot 2020-10-16 at 11.52.25 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5ea16d6c-acba-4770-9965-362181bfc9d9)
##
![Screen Shot 2020-10-16 at 11.52.36 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a094d77f-695b-48d4-9074-64357a54b3ed)
##
![Screen Shot 2020-10-16 at 11.53.11 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4fa3d7de-607c-4e8d-98ef-68dbb33b4ec5)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me!

**Comment by amyknox** [comment]
UX Review 2/2: This checks out for me, too.

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/700&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
Closing story
