### ISSUE TITLE
IA Request [My VA redesign]

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14642]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- [My VA product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/README.md)
- My VA design work
  - [Prototype we used for usability testing](https://vsateams.invisionapp.com/share/XNZWCYAYD45#/screens/444040702)
  - [Latest design updates based on usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21170#issuecomment-800520802)
- [My VA research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-research-findings.md) 
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md#feb-22---feb-26-my-va-20-usability-testing)
- [Content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21543)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
_Provide a list of keywords used by your target audience when they talk about or search for your content_

People don't specifically search for the My VA dashboard. 

**Proposed site map/page structure** 

_Provide link or image of proposed page structure (if more than one page)_

[This is the latest mockup](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21170#issuecomment-800520802). It does a much better job of prioritizing the most needed content over the current design.

**Suggested URL(s)**

_Provide suggested URLs and any background or rationale_

No changes. We should still use https://www.va.gov/my-va.

**Suggested entry points**

_What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc._

In terms of navigation changes, the [OCTO team agreed to add My VA to the logged-out navigation](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21183). Clicking this link will initiate the sign in flow and then drop people on My VA after they log in.

**Crosslinking opportunities** 

_What additional related areas of the site would links to your content/tool be helpful?_

Not sure

**Redirects/canonical tags**

_Will existing pages/tools need to be redirected or canonicalized?_

No, no redirects are needed at this time.

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by Samara-Strauss** [comment]
We won't be ready for this for another couple of sprints, but when we are, let's make sure we discuss the proposal to add My VA to the unauth nav. #19356

**Comment by Samara-Strauss** [comment]
So I don't forget again — reached out to Mikki about this in Slack today.

**Comment by mnorthuis** [comment]
Hi,  I think the general IA design is pretty much established already and the only thing changing is the My VA link in the header for the unauth experience.  Here is a summary of IA for prosperity.  Let me know if there's any questions.  

**Structure, URL and breadcrumbs:**
- This is an update to an existing feature, and no labeling changes are planned, so it will retain its current URL and breadcrumb. 
  - URL: www.va.gov/my-va
  - Breadcrumb:  Home > My VA

**Navigation and entry points:**

Priority | Placement	| Link Destination | Description
--- | --- | --- | ---
MUST  |  VA.gov global header |  www.va.gov/my-va |  This is an existing entry point that currently appears for authenticated users only.  This entry point should also be available for unauthenticated users.  The "My VA" link should always appear on the header as per issue [#19356](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19356)

**Redirects:**
None needed.

**Comment by ajakabcin** [comment]
Confirmed with Mikki we're good to go on this. Thank you!
