### ISSUE TITLE
Get metrics on the steps of the vets-website build script

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#1464]
## User Story
As a VSP front end engineer, I need know how our build script is performing so I can identify improvements.

## Goal
_What outcome(s) do we want to see?_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by timwright12** [comment]
Closing since we've either dealt with this in other tickets or are currently dealing with
