### ISSUE TITLE
Analytics Reporting Request for Comparison Tool Redesign Discovery

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#14646]
Please fill out the following sections:
- [x] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Booz Allen Team: 
  - UX Team: Amy Knox, Jen Jones, Emma Waters

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    - Request is in support of GI Bill Comparison Tool Redesign Discovery effort

## Timeframe for Analytics Requested

- Looking for patterns in data from initial date tracking was available for the CT in this GA instance to present:  Sept 2018 - Oct 2020 

## Analytics to Track Down

- [ ] The "Event Action" GIBCT Form Change tracks updates to the Military Status dropdown.  Can data for users who select, child, national guard / reserves, spouses be separated out from the default selection (Veterans) to allow us to compare engagement across user types? Can you help us out with that? 
For reference, here's the "Top form selections on Landing Page" from the GIBCT Dashboard 
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/cbd8f456-c8da-4a7d-bedb-d8ae1975ebe6)

 - [x] How do we access the data of the "Downloads of all school data excel"?  Is there any additional information we can get around the use of this link (domains using it, dates it was accessed, geography, devices, etc). 

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/74f7b4ad-0f91-431a-8c19-a2ce9febff47)

## Other Helpful Questions to think through
- Who is your audience? Users of the comparison tool
- Why do you need this data? Understanding how various user types engage with the tool
- What are you hoping to find? Are behaviors the same or different
- What is your hypothesis that you're hoping the data will support? 
- What area of the VA are you hoping to assess?
- How frequently do you need this data? TBD - if behaviors in user groups (Military status form changes) are drastically different, it could be something we want to investigate further or plan on tracking on an on-going basis.

## Additional Comments

Please reach out with questions if the data requested isn't specific enough. 

Also, we're open to creative ways to solve for this info.  If it makes more sense to set up a "tutorial" to demonstrate how to access the data, that works for us

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thank you @amyknox ! Acknowledging receipt

**Comment by joanneesteban** [comment]
Thanks, @amyknox. We're reviewing this, and @bmcgrady-ep will pick it up when he's back in office next week.

**Comment by amyknox** [comment]
@bmcgrady-ep - do you have an ETA on this? Want to make sure we have time allotted to review & discuss. Thanks!

**Comment by bmcgrady-ep** [comment]
> @bmcgrady-ep - do you have an ETA on this? Want to make sure we have time allotted to review & discuss. Thanks!

@amyknox - I'm looking into this now. I'll try to have something for you by EOD tomorrow.

**Comment by bmcgrady-ep** [comment]
@amyknox - Here are a couple of reports that should be useful.
1. [Custom GA Report](https://analytics.google.com/analytics/web/template?uid=mpTKeAR8SE2nD5wD3bHmKw) for `Downloads of all school data excel` events. The report shows the page, device category, and city of the `Downloads of all school data excel` events.  To see the report, copy and paste the link into your browser and then use the Education Modernized View for the report.
2. I created a segment for users who select, child, national guard / reserves, or spouses. Here is a [report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20200901&_u.date01=20201021&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.secSegmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22~2Fgi-bill-comparison-tool%22,0%5D,%5B0,%22analytics.eventAction%22,%22RE%22,%22%5EGIBCT%20Form%20Change%22,0%5D%5D&_.useg=userWnqhrRESRPyQhUOqcQ4u9g/) showing that data.

**Comment by bmcgrady-ep** [comment]
Hi @amyknox - here are the two segments that I created for your request:
1. [GIBCT - Users who select child, national guard / reserves](https://analytics.google.com/analytics/web/template?uid=jUf_jzZoTe-LjzITlaZWNA) segment
2. [GIBCT - Active Duty and Veteran Users](https://analytics.google.com/analytics/web/template?uid=2YL1nZnkQ124SnZ8tW--dQ) segment

Each link will prompt you to add the segment to a view. I would recommend adding the segments to the Education Modernized View. This will allow you to specifically see the two segments in the [GA Report](https://analytics.google.com/analytics/web/?authuser=0#/my-reports/uP4_hl6qTm2CzPq2udOk5A/a50123418w177519031p184334251/).

**Comment by bmcgrady-ep** [comment]
@amyknox Here are the other segments:

- [GIBCT - Users who select national guard / reserves](https://analytics.google.com/analytics/web/template?uid=xz-_8wopRa-KkiqANXbd5A)
- [GIBCT - Users who select child](https://analytics.google.com/analytics/web/template?uid=yckMgshvSZW48bNppql6Cg)
- [GIBCT - Users who select spouse](https://analytics.google.com/analytics/web/template?uid=yckMgshvSZW48bNppql6Cg)

Quick note - these segments are users who have **only** selected the specific category. For instance, GIBCT - Users who select child are users who have only selected child and no other option. Let me know if you were looking for something else.
Once again, just select Education Modernized View when importing these new segments.

**Comment by amyknox** [comment]
So when you say "these segments are users who have only selected the specific category" - if they select a different benefit than what's the default OR they select yellow ribbon or change the amount of benefit they have, does that negate the segment?

I tried to create a new segment of just Veteran users, using the links you sent over as a starting point, and the numbers don't look good at all.   

![image](https://user-images.githubusercontent.com/41081945/97365643-62f27400-187c-11eb-9d22-f0a6e140cd03.png)

**Comment by bmcgrady-ep** [comment]
@amyknox - I changed the configuration of the segments a little so that each segment is users who selected that specific category, but that doesn't necessarily mean that the user did not complete one of the other actions.

Here is the [GA Report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20201021&_u.date01=20201027&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22BW%22,%22GIBCT%20Form%20Change%22,0%5D%5D&_.useg=useraUmjZLDeSJ2ZSbFAG_c1fQ,userGeWmwwqrQRmrcEmgv1-bWQ,user5QvXQ1WHRwOjyS9bSkdOfA,userPLOmZL6cRpCdK6OgCfshSw/) reflecting that change. Also, I want to note that the report is specifically looking at `GIBCT Form Change` events, just like the GIBCT GA Dashboard.

**Comment by amyknox** [comment]
@bmcgrady-ep 
To confirm, these segments you've created track users who've updated the "Military status" dropdown:

- GIBCT Active Duty Users
- GIBCT Users who select Child
- GIBCT Users who select Spouse
- GIBCT Users who select national guard / reserves
- GIBCT Users who select child, national guard / reserves, spouses

And... for the segment, 
- GIBCT Veteran users 
Did this segment change the Military Status dropdown to something else then change back to Veteran or did they not change the dropdown status at all? 


Looking at a report like this to get a rough idea of the user roles and what each group is searching for.  Children appear to be much more ambitious in their school selections, view fewer pages and are faster in and out of the tool.  Go figure!

![image](https://user-images.githubusercontent.com/41081945/97618260-30b85200-19f5-11eb-9b6c-319f4c39b49a.png)

**Comment by bmcgrady-ep** [comment]
@amyknox Yes, that is correct. The segments are users who have updated their military status. 

For the veterans segment, it is for users who specifically chose the dropdown status of `veteran`. However, since you pointed that out, I made a change to the veterans segment. The segment now is any user who either changed the Military Status dropdown to `veteran` or one of the following events happened on the `/gi-bill-comparison-tool/` page: `gibct-form-change`, `gibct-autosuggest`, or `gibct-learn-more`.

[Here](https://analytics.google.com/analytics/web/template?uid=gML1j4lVRPqt2mdV0GL_Cw) is the new segment. Let me know if you have any more questions!

**Comment by amyknox** [comment]
@bmcgrady-ep -   I've got what I need so you can close this one. Thank you for all your help with this.
