### ISSUE TITLE
Add  "https://raw.githubusercontent.com/" to Content Security Policy (CSP)

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1465]
We now read the YML file for the homepage banner directly off of GitHub. This means that we need to update our CSP to not block resources from this domain. Right now, our CSP is set to report-only, which is why we can do this currently.

This GitHub-based approach for the homepage banner is likely temporary because it's to be moved to Drupal. So, in the end this may not be necessary, but in the event we see ourselves using this approach longterm, then we should definitely make sure that this work is done.

**Comment by Karak888** [comment]
Moving to closed
