### ISSUE TITLE
Determine scalable solution to link validation in vets-website in an RFC

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1466]
### The problem
I consider this issue to be very high priority, because of how often it seems to come up and the impact it has on the whole front-end team. In order to focus on some of the other CMS/vets-website issues, we need to clear this one up.

#### Broken link checker
Currently, as part of its build for each environment, vets-website executes a **broken link checker**. This tools inspects every image reference and link (`href` value) of every public HTML page in the website. If the link is relative, it confirms that there it's pointing to a valid resource. If not, the build fails.

**This approach made sense when the website content existed inside of vets-website as Markdown under a `content/` directory, as it did during the Vets.gov days.** The reason this made sense is that the validation is executing entirely on what is in vets-website, so the problem originates and can be fixed all in that repo. 

**However, this doesn't make sense now, because the broken-link-checker is executing on content from Drupal - content existing in a database behind a separate system's authentication edited by any number of maintainers throughout the VA ecosystem at any given time.** If content is edited and that edit contains a single broken link, all teams operating under vets-website are oftentimes brought to a standstill - we can't deploy and sometimes cannot merge a pull request. The creates a flurry of CMS, VSA, and VFS engineers/writers pinging each other throughout Slack trying to fix the problem.

Currently, we have managed to always fix the broken links, although it has cost a great deal of developer time and headache (especially due to the context shift required when a broken link comes up - because it brings vets-website to a standstill, fixing that link becomes highest priority). However, as the website content grows under Web Brand Consolidation (WBC), there will be more content edited more and more often, and that resultant standstill created by a broken link will occur more and more often, until it is unmanageable.

#### Accessibility tests
Unfortunately, accessibility tests have a similar issue - Drupal content can be edited in a WYSIWYG, where a content editor can easily input HTML that contains an accessibility issue. This, too, brings all of vets-website to a complete standstill, until either someone with Drupal access fixes the issue or we add an exception into vets-website.

### The solution
First, we need to accept that a broken link or mild accessibility issue cannot continue to break a vets-website build. It is already very difficult to manage, and as the website scales, it will be impossible. Consider this - in the near future, we will begin consolidating facility subdomains (such as pittsburgh.va.gov) into www.va.gov. This alone will increase the scale of the website dramatically. 

I propose moving to a report-only health-check model for HTML validation - including link validation and accessibility. This can exist as a separate Jenkins stage or automated job just before the build is archived. During this stage, we can evaluate the number of broken link references per page, print them into a formatted report, and email the report if possible to a mailing list for Drupal editors to delegate the responsibility of fixing those issues to the team responsible for maintaining the quality of the HTML.

During this health check, we should also define some thresholds to break the build - if there are X link/accessibility issues total site-wide or X% broken links on a certain page, then we determine that the status of the website is not acceptable for a deployment, and send a high priority email to the content editors.

**Comment by ncksllvn** [comment]
Created a PR to write this into an RFC here, https://github.com/department-of-veterans-affairs/va.gov-team/pull/1467.

**Comment by Karak888** [comment]
@ncksllvn is this still an issue, or you just need someone from CMS to do pull request? Let me know how I can help!

**Comment by ncksllvn** [comment]
Still wrapping up! This is just me writing up an approach for broken links that I'll propose to the rest of the team for feedback. If it's received well, we can map out some work from it. Nothing will come from this ticket alone though besides a writeup.

**Comment by ncksllvn** [comment]
Moving to validate because the RFC is about done and just needs to be proposed to the wider engineering group.

**Comment by Karak888** [comment]
Thanks @ncksllvn ! I am sure you already have your recommendations or write-up, but let me know if you would like for me to capture it and save for you somewhere!

**Comment by Karak888** [comment]
moving to close- follow-up with Nick to capture write-up and his recommendations!
