### ISSUE TITLE
School Ratings: Test Data Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14662]
- [x] Review test data to assess suitability for UT 
- [x] Update data as needed

File link:  https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/UX%20Assets/Research/School%20Ratings/school_rating_ux.csv?d=w87d3d378dffd42798124fc82c2166d7c&csf=1&web=1&e=tx5xhJ

**Comment by JenLJ** [comment]
@amyknox Data on staging was reviewed and looks good - closing story
