### ISSUE TITLE
Enable org Codespace for test users

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#14665]
Background:
- Beta test of Github Codespaces has been enabled on the Department of Veterans Affairs organization.

Next steps @department-of-veterans-affairs/github-team:
- Users participating in the Codespace tests need to be granted access through https://github.com/organizations/department-of-veterans-affairs/settings/codespaces

- Users:
@Yuffster-usds 
@stephenBarrs 
@boris-ning-usds 
@CoryTrimmUSDS 
@rianfowler 
@dginther 
@Clark-W-Griswold 
@f1337 
@aaronba-va 
@mchelen-gov 

Notes:
- Codespaces is in beta and for testing purposes only.
- All usage is free to VA
- Initial default user limit is 15, reach out to @Chuxel if additional slots are needed

**Comment by zkoppert** [comment]
@mchelen These users have been granted permission just now.

**Comment by zkoppert** [comment]
ok to close this issue?

**Comment by mchelen-gov** [comment]
@zkoppert Confirmed, thanks!
![image](https://user-images.githubusercontent.com/63597655/95913412-29951100-0d72-11eb-9d76-3f673349e9e3.png)
