### ISSUE TITLE
CT Redesign: Competitive Feature Audit

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14675]
Establish goals for exercise 
Create tool (mural) for capturing input 
Conduct research / reviews 
Identify topline findings  
Share findings

**Comment by amyknox** [comment]
Competitor research we've already completed: 

School Ratings Competitor Review (mural): https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1589996279941/0d404f73fdfcde3a892df831eb304150ad57e381?wid=0-1591732090703

CT Filter Safari (mural): https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1594384732139/5e8e7f793ad7b8cb079c8953caa520eda852ca8d

**Comment by amyknox** [comment]
Priorities for "competitors"

Effective use of:
- Comparing products
- Geolocation
- Natural language search for products 
- Chatbot
- Rich product data display
