### ISSUE TITLE
CT Maintenance: Mobile Table Display / 508 - Draft UI

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14671]
Draft mobile table layout for School locations accordion 
Share w UX team to validate approach 
Update / Refine

Support for #[14220](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14420)

**Comment by ccruzgra** [comment]
Also related to [#14420](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14420).

**Comment by ccruzgra** [comment]
@amyknox  This is the link to 14420: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14420

**Comment by watersemma** [comment]
Here is the proposed mobile table updates. https://bahdigital.invisionapp.com/share/B8IAF9K75NU Screenshot attached for your convenience. 

![Screen Shot 2020-10-21 at 2.31.48 PM.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/9f7b821e-0d00-4902-9e14-51c65da93084)

**Comment by amyknox** [comment]
Looking good! Closing this issue
