### ISSUE TITLE
clean up uses of require_dependency

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#14688]
## Issue Description
`require_dependency` is no longer meaningful when `zeitwerk` loading is enabled.  It should be removed throughout the app.

**Comment by erluti** [comment]
This PR is part of the work, https://github.com/department-of-veterans-affairs/vets-api/pull/5787

Probably makes sense to do a PR for each module in the modules directory.

**Comment by holdenhinkle** [comment]
This is somewhat related - https://app.zenhub.com/workspaces/platform-cop-backlog-6359535e384ff5a473132130/issues/gh/department-of-veterans-affairs/va.gov-team/14689

**Comment by pjhill** [comment]
Wow -- awesome! That's a ton of merged PRs!
It's gone --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/a733c63f-47c1-4267-9cd4-ea26719d558a)

**Comment by pjhill** [comment]
Oh @gia-lexa, I guess we are kind of cheating by assigning story points after the fact, but what would you estimate the points at for this task?

My estimate would be something like 5 points.
