### ISSUE TITLE
Save email: Service integration

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14699]
This is a backend task to save a user's email. The associated UI is included in different stories. 

## Acceptance Criteria:

1. Make call to save a user's email address on the Email page
2. Selecting the "Save" button will save the fields in the edit screen and on the Personal Information page. The saved fields should persist & appear to the user if & when:
     - The user navigates to other pages in the app, then returns to the Personal Info / Edit page(s)
     - The user logs out of the app, signs back in, and returns to these pages

**Comment by digitalken** [comment]
Added to TestRails.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/24**

Pass on iOS and Android. Moving to Design QA
