### ISSUE TITLE
[DUE ON NOV 16th] Redirect Request: REAP

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14704]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
The Reserve Educational Assistance Program (REAP) ended on November 25, 2015, but under the National Defense Authorization Act of 2016, some REAP benefits remained in place until November 25, 2019. This program is officially retired, and we need to archive the page. 

### Requestor team info
Tammy Hurley in Education Service has made this request. She has already removed the REAP content on the business side. 

### Implementation date
Date new URL(s) will be live: ASAP, as soon as we can implement

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/education/other-va-education-benefits/reap/ | https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
www.vets.gov/education/other-educational-assistance-programs/reap/ | Update redirect to: <br> https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
www.benefits.va.gov/gibill/reap.asp | Update redirect to: <br> https://www.va.gov/education/about-gi-bill-benefits/post-9-11/

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
I updated the table above to include 2 additional pages that are currently redirected to the VEAP page.  Those redirects should be updated to the new destination.  All redirects should be case insensitive.   This redirect can be implemented when your team is ready.

**Comment by lunascoop** [comment]
Hi @bethpottsVADEPO can you let me know the appropriate stakeholder to notify for these redirect updates? Thanks

**Comment by bethpottsVADEPO** [comment]
Tammy Hurley, Luke Tickner, and Joseph Welton. Thanks!

**Comment by lunascoop** [comment]
@ncksllvn @kelsonic this redirect is scheduled for 11/16. Stakeholders have been notified.

**Comment by kelsonic** [comment]
PRs are up, won't merge until 11/16 👍 

https://github.com/department-of-veterans-affairs/vets-website/pull/14833
https://github.com/department-of-veterans-affairs/devops/pull/7930

CC @lunascoop

**Comment by mnorthuis** [comment]
@kelsonic @bethpotts I incorrectly added two VEAP pages to redirect, I meant to add two REAP pages.  I updated the original description with the correct URLs for the bottom 2 redirects.  So sorry for that mistake.

**Comment by kelsonic** [comment]
Uh oh, thanks for the heads up @mnorthuis! The redirects are already live so I'll get a PR up to fix this asap

**Comment by mnorthuis** [comment]
@kelsonic If the incorrect ones were merged already, they will need to be reverted back to their original redirect: 

URL | Redirect to
www.vets.gov/education/other-educational-assistance-programs/veap/ | www.va.gov/education/other-va-education-benefits/veap/
www.benefits.va.gov/gibill/veap.asp | www.va.gov/education/other-va-education-benefits/veap/

**Comment by kelsonic** [comment]
PRs merged + deployed (mostly), part of the redirects will go out tomorrow with the daily deploy unless we want to do an off-schedule, specifically this update here: https://github.com/department-of-veterans-affairs/vets-website/pull/14976

**Comment by lunascoop** [comment]
Corrected URLs are redirected. Closing ticket.
