### ISSUE TITLE
Download & View - Service Verification letter

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14707]
## User story
As a user, I want to view my **Service Verification** letter in my device's file viewer so I can save it to my files. 

## Acceptance Criteria
1. Selecting 'View letter' from the Service Verification letter page should open the letter .pdf with the OS file viewer (separate story for [loading screen](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14725))

## Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
@bridgethapner mind double-checking the a11y guidelines above? Is there anything else we should add to accessibilityHint? 

cc: @esther-k

**Comment by esther-k** [comment]
@bessgreen the labels might be better switched to hints. 
ex. back button: Label: back, Hint: go back to service verification letter

**Comment by bridgethapner** [comment]
@bessgreen What do you think about adding the first sentence from the letter description here? A couple of examples:

"This is a .pdf of your Service Verification letter. This letter shows your branch of service, the date you started active duty, and the date you were discharged from active duty. You can save it to your files on your mobile device." 

"This is a .pdf of your Commissary letter. If you’re a Veteran with a 100% service-connected disability rating take this letter, a copy of your DD214 or other discharge papers, and your DD2765 to a local military ID and pass office. You can save it to your files on your mobile device."

Edge case of the custom letter: "This is a .pdf of your Benefit Summary and Service Verification Letter. This letter has been customized. You can save it to your files on your mobile device."

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Blocked: Letters service is down. Moving this ticket out of Sprint 7 / can reprioritize for a later sprint.

**Comment by digitalken** [comment]
Testing...
