### ISSUE TITLE
Schema - caregiver certification checkboxes

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#14701]
As a CSC,
I would like to see a PDF that indicates whether the Primary Family Caregiver is:

An immediate family member
Not an immediate family but currently lives with the Veteran full time or will do so upon to approval to the PFAFC
Note: designs are still in progress, and it's possible we might not need to make any front end changes. See @jonathanjnelson

**Comment by jonathanjnelson** [comment]
For [awareness](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12794l)

**Comment by jonathanjnelson** [comment]
Linking #12794 for awareness
