### ISSUE TITLE
Letters overview page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14706]
## User story
As a user, I want a letters landing page that tells me which address I have on file, before I view my letters. 

## Acceptance Criteria

1. Selecting VA letters & documents routes to a new page called "Letters"
2. Styling and UI matches the design
3. Include placeholder for Mailing address button (this functionality is handled in a separate [story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13940))
4. UI for "View letters" button (routing is handled in a separate story)

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636878

## Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Back button in top left
     - accessibilityLabel = “back”
     - accessibilityHint= "Go back to profile"
     - accessibilityRole = “button”
- Mark “Letters” as Header 1

**Mailing Address**
- Mark “Mailing address” as Header 2
- Field
     - accessibilityLabel= Mailing Address
     - accessibilityValue= contents of field
- Right caret should be marked as: 
     - accessibilityLabel= "Edit this information"
     - accessibilityHint= "Navigates to a new page where you can edit your mailing address"
     - accessibilityRole= button

**View Letters**
- Title= “View Letters”
- accessibilityHint= “View a list of your VA letters” 
- accessibilityRole= “button”

## Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Tested in TestRail. Passed functionality/UI, failed accessibility.
Multi-part bug logged for accessibilty:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14706
