### ISSUE TITLE
Navbar - Profile Icon does not fill in "head" when selected, leaves white rather than dark blue

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#14715]
## What happened?
When selecting the Profile page, the Navbar icon still has a white outlined head rather than a dark blue filled in head.

## Specs:
Pixel 3XL simulator

## Steps to Reproduce
Select Profile in the Navbar to navigate to the profile page.

## Desired behavior
When landing on the profile page, the icon in the Navbar should have a blue head rather than an outlined head.

## Acceptance Criteria
Body and head in the profile icon will be filled in dark blue when selected.

![provileNavbarIcon.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/10089e46-c2c0-4654-93a0-a6787f6d4405)

**Comment by digitalken** [comment]
Issue linked to story:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13862

**Comment by bessgreen** [comment]
correct icon: 

![profile.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ead9bd5e-0d57-4417-810f-49c4562ca6c5)

**Comment by digitalken** [comment]
PASS 8/14/2020 - Profile button now has filled in head in nav bar when selected.
![14715pass.gif](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/e3d1bb7a-12a6-42bc-a6c3-792aab0e96a9)
