### ISSUE TITLE
Direct deposit - Confirm & Save (FE validation)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14714]
## User story:
As a user, I want to confirm that my direct deposit info is correct before I save it to my profile.

## Acceptance Criteria:
1. The bottom of the Direct Deposit edit screen contains a checkbox so the user can confirm that their info is correct
2. Create active/disabled states:
     - Checkbox becomes active and is able to be selected by the user once the other 3 fields have a valid entry (i.e. a 9-digit routing number, an account number of no more than 17 digits, and an account type)
3. Save button in the top right corner (separate story for the BE integration to save information).
4. Save text becomes active when the user has done all of the following:
     - Entered a value in Routing #, Account #, and Account type fields.
     - Selected the confirmation checkbox

## Design:
Disabled state: https://adhoc.invisionapp.com/d/main#/console/20546460/431636876/preview
Active state: https://adhoc.invisionapp.com/d/main#/console/20546460/432050369/preview

### Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

### Accessibility Implementation Guidelines 
- Save button in top right
     - accessibilityLabel= “Save”
     - accessibilityHint= “Saves changes”
     - accessibilityRole= “button”
     - accessibilityState= Denote when disabled vs. enabled
- Checkbox
     - accessibilityLabel= “I confirm that this information is correct”
     - accessibilityHint= "Confirms your direct deposit information"
     - accessibilityRole= “checkbox”
     - accessibilityState= Denote when checked vs. unchecked

**Comment by bessgreen** [comment]
Before this checkbox was added, we were following this [requirement](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13907) for when the Save button should activate:

- 'Save' text becomes active when user enters a value in Routing #, Account # and Account type fields.


@bridgethapner with the addition of this checkbox, what are the new requirements for Save button & when the user can select the checkbox?

**Comment by bridgethapner** [comment]
- Let's keep the same 'Save' criteria with the addition of the user must have selected a checkbox. 
- The checkbox should become active and able to be selected by the user once the other fields have been entered.

**Comment by bessgreen** [comment]
@bridgethapner thanks! I'm assuming we'll also want a disabled state for the checkbox?

**Comment by digitalken** [comment]
Testing:

1. Verify the bottom of the Direct Deposit edit page contains a checkbox so user can confirm that their information is correct.
2. Verify checkbox states for active / disabled:
  a. Checkbox becomes active once the other 3 fields have valid entries:
     i. 9-digit routing number
     ii. account number of 17 digits or less
     iii. an account type.
  b. Checkbox is disabled otherwise.
3. Verify there is a save button in top right corner and is active when:
  a. Valid routing number, account number, account type fields; AND
  b. Confirmation checkbox is selected.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/19**

UI and functionality pass. Accessibility does not pass on Android. Moving to Design QA for review
