### ISSUE TITLE
Access for Christine Kies

### ISSUE THREAD

**Issue by christineyost** [department-of-veterans-affairs/va.gov-team#14716]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Christine Kies
- Please Provide your email.
   > christine.kies@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA API, software engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABgQDQH2WMSgzgvanybKq68yoSHmslCBljyj7nEpi+jMafK1cp0ZdQnorqNF//QwSsmL1orVhmZbVorYItkfIqIFPJ3EgU9rsQUhQN/d93uQHnEBNnDvIC/6WLTKyiU23TEol8Cka1gMUIhGvh4Xgf4LKC9XCJnVe3X/mP2VbEFfVecZOo+IOaGEWJhU3p6XyOUV2anTHlm0KEzD7XeNYdUYCw2EP1+0pYxAKZ8yf1vK9LRK6SQp+bu4XJGCb1axsbOV5awfdiVokJr1lUAt0WOcO2R+xLYu+Z4YUThFPxz66pHnG4b+Le/wO1NiACmRsta548kp4WH/W9UX+aPLTVaBG6q9QANTnFeyV0PdW4cZJHAdBSXZlo9ytWOdauljEEW4Czi386jux0sEbyRonGWAnEejHVksK/7tQSNRZGc0Edf4QqRQE6+SaHT90rKGDHsgeOhi81k4kcC6QDz2PE7EEgyo1AgixeOaX6xlDQI+7wJHwQPOvHSRz0Pd5/WkZM2Ts= christinekies@Christine-Kies-Macbook.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
     Need AWS access for development, troubleshooting, and access to log files

**Comment by jsev-io** [comment]
Requesting AWS Access
cc: @Jeff-Hayter 
User: Christine Kies
COR: Cecilia Lee

**Comment by jsev-io** [comment]
@christineyost You have been granted SOCKS proxy access. Please verify.

**Comment by christineyost** [comment]
@jsev-io I'm getting `socks@172.31.2.171: Permission denied (publickey).` When running `ssh socks -D 2001 -N`

**Comment by christineyost** [comment]
@jsev-io Never mind, I've got it working now. I think I forgot to add the SSH key to my local agent the first time `ssh-add -K ~/.ssh/id_rsa_vagov` Sorry about that!

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS access.

**Comment by jsev-io** [comment]
Thanks @Jeff-Hayter 
@christineyost 
I will get your account created and contact you directly with the details when complete.

**Comment by jsev-io** [comment]
AWS Credentials for @christineyost have been delivered via slack.
