### ISSUE TITLE
Screen reader is not picking up correct information for some buttons on home page, some repetitive information.

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#14722]
## What happened?

Home (page title): 
  Read:  (Never seems to be read.)

Crisis line button:
  Read:  "Crisis line button. Go to Veteran's Crisis line button. Double tap to activate."
  Expected: "Talk to the Veterans Crisis Line now. Go to Veteran's Crisis line. Button. Double tap to activate."  (Extra "button" is repetitive.)

Claims and appeals:
  Read:  "Claims and appeals home nav button. Claims and appeals dot allyhint menu item. Double tap to activate."
  Expected: "Claims and appeals. Check your claim or appeal status. Menu item. Double tap to activate."

Appointments:
  Read: "Appoints home nav button. Appointments dot allyhint menu item. Double tap to activate."
  Expected:  "Appointments. View your medical appointments. Menu item. Double tap to activate."

## Specs:
Android Pixel 3XL simulator with TalkBack enabled.

## Steps to Reproduce
With TalkBack enabled, use screen reader to read home page buttons.

## Desired behavior
Crisis line button:
  Expected:  "Talk to the Veterans Crisis Line now. Go to Veteran's Crisis line. Button. Double tap to activate"

Claims and appeals:
  Expected: "Claims and appeals. Check your claim or appeal status. Menu item. Double tap to activate."

Appointments:
  Expected:  "Appointments. View your medical appointments. Menu item. Double tap to activate."

## Acceptance Criteria
Text of buttons or hints should be read to user without duplication of "button".  Hints should be read back to user rather than the name of the hint file.

(Note: Only included Claims and appeals button, but Appointments is similar.)
![homeButtonsRepetitive.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/81e306ce-9975-4ba7-b1fa-9907646286bf)

**Comment by digitalken** [comment]
Linked story:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13950

**Comment by esther-k** [comment]
@digitalken 

Via the story, the crisis line button should be read as:
"Talk to the Veterans Crisis Line now. Button. Go to Veteran's Crisis line. Double tap to activate"

**Comment by digitalken** [comment]
Excellent.  Thanks @esther-k !

**Comment by esther-k** [comment]
**11/24**

PASS - on iOS and Android. The correct a11yHints are being read by the screen reader.
