### ISSUE TITLE
Loading screen for letters

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14725]
## User story
As a user, I want to know that my letter is loading so I'm not staring at a blank screen for an extended period of time. 

## Acceptance Criteria
1. Selecting the "View letter" button triggers a loading screen
2. Loading indicator component leverages React Native indicator: https://reactnative.dev/docs/activityindicator
3. Loading screen requirements:
     - Display top navigation bar
     - Display bottom toolbar
     - Display loading indicator common component
     - Display text message in Mobile Body
     - Margin left-right: standard gutter
     - Margin top: marginBetween 
4. This screen appears until the rendered letter is ready to display

## Designs
https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/434431466_Letters_-Loading-

**Comment by digitalken** [comment]
Added to TestRails.

**Comment by digitalken** [comment]
11/24/2020 - Pass on iOS and Android - Just seeing mock operation in Service Verification Letter for now.  Moving to design QA.
