### ISSUE TITLE
Use VSP bot to trigger Pact verification webhook

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#14734]
The Pact verification job use should use the API token from the VSP bot. @va-vfs-bot

**Comment by LindseySaari** [comment]
Possibly generate a personal API token for the slackbot. Or whoever has access to the bot can configure that.

Sync w/ someone from Ops?

**Comment by LindseySaari** [comment]
Closing this in favor of a discussion in the #temp-integration-testing channel [conversation](https://dsva.slack.com/archives/G011B11C1L7/p1602782045066700)

TLDR... Ops wants to move the pact broker into our AWS infrastructure and off of heroku. With this change, CircleCI will no longer have access to the broker. The solution will also require moving the pact verification task out of circle and either into Jenkins (temporary) or into AWS CodeBuild.  This infra change will also affect the current webhook defined in the broker for contract changed events.
