### ISSUE TITLE
BAM 1: Targeted Email to PTSD Veterans

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#14739]
## The Problem

The BAM/Claims team has discovered a bug (since fixed) which appears to have impacted disability claims submissions by an estimated 1- to 2-thousand PTSD veterans.  The issue was triggered by a bug related to a  PTSD related questions in the application.   When the veterans attempted to submit their online form they received an "application error" message.

## The Proposed Solution

To ensure these veterans are provided the assistance they need, the BAM team would like to send a communication -- optimally a VA.gov branded targeted email or possibly a text message -- 
to explain and apologize for the issue and to tell them the issue is now fixed if they want to re-do the process online.  

**Do note:**  (10/9 phone conversation with John Hashimoto) The VA business owner, Paul Shute, says he does not consider this an issue that absolutely needs to be resolved via direct communication with the veterans.  Rationale:

- We've had issues like this in the past and we did not deem direct communication to be vital
- He suspects that the majority of these veteran applicants worked with a VSO representative to complete the application process (he's going to check the data system to try to confirm this).
- He says a direct communication to one of these veterans via text or email may cause them unnecessary concern -- e.g. they may have already completed their disability claim application via other means, but have forgotten -- so the messaging may cause unnecessary stress.

## Steps to Resolve

If a text or email communication is deemed necessary, the following paths are being pursued as options:

- [x] **Vet Resources** Per Lauren Alexanderson, Tim Hudak of VEO may be able to help.  **_Update:_** Tim is providing assistance via VEO email platform.

- [x] **GovDelivery:** According to Angela Gant-Curtis, this service-provider may be able to provide email service for this purpose.  (John is following up with Jill Konek at jill.konek@granicus.com). **_Update:_** Did not hear back -- and Tim Hudak of VEO has stepped up to help.

- [X] **VA Education business unit:**According to Matt Self, Luke Tichner and Joseph Welton have a tool in place to send marketing emails and they may be able to help with this use case.  (John is following up with Luke) **_Update:_** John opted not to reach out based on Tim Hudak's offer to assist.

- [X] **VA Notify:** Which goes into production next week will purportedly have email capability, per Shane Elliot. (John is following up with Shane) **_Update:_** Not fully functional yet -- and not yet offering email capability. For more details on VANotify capabilities and roadmap, here is the team's [product outline.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/status_reports/implentation_tracker.md)

## Status 

- 10/14: Tim Hudak of VEO is allowing us to utilize VEO's email solution to deliver our targeted email to impacted veterans.  The platform will allow us to monitor campaign metrics: Deliver rate, Open rate.  Tim is working to confirm NCC will be able to handle calls prompted by the email (e.g. if you need further assistance, contact VA Call Center).

**Comment by luke-gcio** [comment]
Lots of info came back on this:

The following is our final update on the analytics from the send on the 5th

On 11/5/2020, VA sent #VetResources Newsletter:  Action may be needed on your online VA Disability Claim to 2,507 recipients opened by 2,600 (total) 1,177 (uniques) and drove 182 clicks to embedded links. Additional analytics: open ratio 47%, bounce ratio 1% and unsubscribed as 0.
Top links accessed from this send were: File for disability compensation , VA.gov and How to file a VA disability claim

Asking Anna to rerun the query.

**Comment by johnhashva** [comment]
•	On 11/5/2020, VA sent #VetResources Newsletter:  Action may be needed on your online VA Disability Claim to 2,507 recipients opened by 1,838 and drove 122 clicks to embedded links. Additional analytics: open ratio 40%, bounce ratio 1% and unsubscribed as 0.
•	Top links accessed from this send were: File for disability compensation , VA.gov and How to file a VA disability claim
