### ISSUE TITLE
"I am here" indicator obscured by pins

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14744]
## What happened?
"I am here" indicator is obscured by search result pins for facilities near Veteran's location
![image](https://user-images.githubusercontent.com/55411834/95880230-84a81300-0d34-11eb-83fd-87827ef4ac95.png)

## Steps to Reproduce
- URL: https://www.va.gov/find-locations/?address=135%20Eaton%20Drive%2C%20Pagosa%20Springs%2C%20Colorado%2081147%2C%20United%20States&context=Pagosa%20Springs%2C%20Colorado%2081147%2C%20United%20States&facilityType=urgent_care&location=37.26%2C-107.08&page=1&serviceType&zoomLevel=4

## Desired behavior
**_Need design input_**

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Will be addressed in next iteration of map enhancements

**Comment by jilladams** [comment]
Parent epic is closed, FL is now ticketed in va.gov-team repo. Closing orphaned tickets, as we are iterating FL separately.
