### ISSUE TITLE
[Launch] HLR: Internal Testing with Lighthouse

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14747]
## Issue Description
In lieu of having stakeholders attend UAT (which has a significant amount of privacy considerations) we wanted to demo the capability to our stakeholders.  We believe this is the best format since it allows them to not only experience the application but get a better opportunity for feedback and discussions.

## Acceptance Criteria
- [x] Demo scheduled and completed
- [x] Any future work captured in tickets
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
@luke-gcio (and @mattpointzxer0 fysa) posting here (for posterity) our decision to allow Lauren Sylvia and Jane Chi (only) observe and participate in the moderated UAT sessions planned for mid-October.   Limiting the number of participants to just two reduces risk -- and the addition of two SMEs could/should prove beneficial in the event the veterans who serve as test participants have any questions.
