### ISSUE TITLE
Scheduled Downtime Notification Discovery

### ISSUE THREAD

**Issue by mlighdc** [department-of-veterans-affairs/va.gov-team#14767]
As the Caregiver Support Program team, I want to be able to inform 10-10 CG users (veterans and caregivers) that our systems are down for maintenance or experiencing an outage.

**Comment by mlighdc** [comment]
@ala-yna Downtime notification was discussed as part of ToT today (10/13/20). I searched open issues and did not find one. @jonathanjnelson there is specific text the platform team would like the different applications to use. Can you please help review what we currently have? Preferred text is below.

![image](https://user-images.githubusercontent.com/35788031/95911254-3ebc7080-0d6f-11eb-958b-c33c0456bb92.png)

For configuration steps - https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications/

**Comment by lianilychee** [comment]
hello!  The verbiage is as follows:
>This application is down for maintenance.
We’re making some updates to this tool. We’re sorry it’s not working right now. Please check back soon.

Seeking guidance on where the notification language is documented in #VFS-platform-support: https://dsva.slack.com/archives/CBU0KDSB1/p1602690085037900

**Comment by mlighdc** [comment]
Thanks @lianilychee

**Comment by LinnJS** [comment]
@mlighdc I have completed the FE implementation of this downtime feature in this [draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14585). It looks like the downtime message its self is hardcoded using the verbiage above that @lianilychee mentioned and in the [docs](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications/) it mentions that custom downtime messages are highly discouraged.

The remainder of the work is going to be adding all external services to the [DevOps config[(https://github.com/department-of-veterans-affairs/devops/blob/a4b5432061ae60a4f77952bbe5f668a1355ee007/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L232) and making sure these dependancies are wired up to Pager Duty. As I understand it Pager Duty is kind of acting as a feature flip for the maintenance window. 

So the next step is to identify all BE Dependancies wire them up to Pager Duty which looks like is mostly BE work for when @kevinmirc gets back. MVI is already added so I figure we need to add CARMA and maybe others.

**Comment by mlighdc** [comment]
Thanks @LinnJS. From what Liani's said, they are discouraging custom messages because she did an audit and noticed that they were inconsistent.

**Comment by LinnJS** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14585) with FE implementation

**Comment by kevinmirc** [comment]
Just created three PagerDuty services: `External: CARMA`, `Staging: External: CARMA`, `Dev: External: CARMA` for prod, staging, and dev. The dev service will be used for Review Instances, Sandbox, Dev, and Local environments. In PagerDuty, these services are assigned to the team **VSA: Caregivers**.

- [ ] There is a PR in the devops repo to update the API config to reference the CARMA PagerDuty service in each env (7922)
- [ ] There is a PR in vets-api to reference to the DEV CARMA PagerDuty service for localhost (https://github.com/department-of-veterans-affairs/vets-api/pull/5215)

After these are merged and deployed, @LinnJS will need to do the following:
- [ ] Update the [external services list in the UI](https://github.com/department-of-veterans-affairs/vets-website/blob/90152b7cdf5b53d6650b44fed832995dbf7660cb/src/platform/monitoring/DowntimeNotification/config/externalServices.js) to include **carma**
- [ ] Update the [forms dependency list](https://github.com/department-of-veterans-affairs/vets-website/pull/14585/files#diff-d1af91da45b51ff664a757a47e763834951f9c1e61c8da2981bc40d1b00e997fR78) to include CARMA.

**Comment by kevinmirc** [comment]
Discovery summarized here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14767#issuecomment-721363558

**Comment by LinnJS** [comment]
@kevinmirc this work was just added to this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14585/files)

**Comment by kevinmirc** [comment]
Testing the backed of the Scheduled Downtime Notification for CARMA today and everything worked as expected:
- Can schedule a downtime period for the CARMA service.
- That period will show up in `/v0/downtime_windows`.

⚠️  Note: This endpoint will pull Maintenance Windows, from the PagerDuty API, with the status of **open**, _not_ **ongoing**. So in order for the maintenance window to show up in the list, maintenance must be _scheduled_ (avoid _immediately_ setting the service to "maintenance" mode).

⚠️ Note: Maintenance windows shown in this API are cached and new maintenance windows may take up to three minutes to show up.

**Comment by SKasimow** [comment]
@RudyOnRails hi - just happened upon this ticket and looks like ti has some background on pager duty. passing along as it might be helpful.

**Comment by RudyOnRails** [comment]
@SKasimow thanks. it underlines our thoughts on entering a scheduled down time into Pager Duty.

I don't have access yet, so I will put a request into Platform Support.
