### ISSUE TITLE
VAMobile should be announced "V-A Mobile" but I'm hearing "vomible"

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#14764]
## What happened?
When TalkBack is enabled on Android device, the program name VAMobile is spoken as "vomible" and not understandable.  This has been heard when enabling TalkBack the first time on the home screen, too. (Having difficulty reproducing the home screen version reliable, however. I think it is perhaps TalkBack announcing that the user is in the VAMobile app when I first enable it.)

## Desired behavior:
When VAMobile is read it should say "V-A Mobile".

## Severity:
Low

## Specs:
- Pixel 3XL on Android 10
- User:  ben.morgan@id.me
- Android using TalkBack

## Steps to Reproduce
- Enable TalkBack on Android device.
- Navigate to VAMobile app on home screen (or wherever it is on device.)  "Vomible" is read.
- Have had varying degrees of success by enabling TalkBack while on the home screen, sometimes "Vomible" is read.

## Acceptance Criteria
- [ ] VAMobile is read as "V-A Mobile".

**Comment by rarroyo23** [comment]
This ticket as been fixed by the fixed on PR https://github.com/department-of-veterans-affairs/va-mobile-app/pull/895/files. I also tested the talkback on Android and iPhone to make sure it says V-A instead of vah.

**Comment by digitalken** [comment]
FAIL - Still saying "VAH" on Samsung phones.  @rarroyo23 - There is code in the app for taking care of the special case of the Samsung phones and "vah", I believe.  This is what it sounds like on the Samsung phone.  (Sending back to In Progress.)



https://images.zenhubusercontent.com/133843125/ace3ce0e-563e-49f8-b170-5ae3d715cb2e/vah.mp4

**Comment by digitalken** [comment]
PASS 8/2/2021 - Sounds good on Pixl 3XL and Samsung.  Closing.
