### ISSUE TITLE
Access for Fareez Ahmed - Government CIO

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/va.gov-team#14766]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product.  Access needed for: dev, staging, prod,  CI environments and Jenkins
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Fareez Ahmed
- Please Provide your email.
   > fahmed@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Public websites - VSA. Senior Software Engineer. GovermentCIO.

- Requesting SSH key authorization?
   > YES / NO 
   - Yes

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpVJtY2N9kcXlLiONFQekvVZq9SpGJF6rQQ5C85DenMieNeXfXXkaI9eDBu22gwYTEyb7fFPfA5nKBSzaqjIx9vvDoDmlOTau8DaABYgvT3r78SH8bU5TSodujxyXl2oJWtsv3Dm7/CtEUGy/oHRxx6iC4Nb21X90nM7ozriwLb5xy116+wu96HkO9qAnwMNjt60S2myL7TCYb5pCxAK1OYwmHzMZxnywSiG+9I5K109JqeaqVVq/GOpSY4ao3DkOpwsELdOrnmqtEPBosrKQ4Vcrx5A/xbJeo316sx206zKSqSNuVA5FZ71Mh3ROFdpy8zSvLgzVYjUKl3+cJBVWMBl9uxc2xsYEdVc6LhQn92CmKyLO1LHUkiRP+HmpNwivu1ptniBhlG08ndmY37do11XYtk4GUNv1yn3Rnc1KIOLLsg+gqLHNPPIj5PvTVoSuIBQ3Rk07KG3f+uUUKJVZ5MTRprYNRPEg+bYNXygtmBiiHWd6tmfX7kYIJbKf4hxs= fareezahmed@Fareezs-MacBook-Pro-2.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jsev-io** [comment]
@youngfreezyVA Please verify that you can access the socks proxy.

**Comment by youngfreezyVA** [comment]
looks like i'm all set 👍 
``` curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.gov
*   Trying 127.0.0.1...
* TCP_NODELAY set
* SOCKS5 communication to sentry.vfs.va.gov:80
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 2001 (#0)
> GET / HTTP/1.1
> Host: sentry.vfs.va.gov
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 302 FOUND
< Content-Language: en
< Content-Type: text/html; charset=utf-8
< Location: http://sentry.vfs.va.gov/auth/login/
< Set-Cookie: sentrysid="gAJ9cQFVBV9uZXh0cQJYAQAAAC9zLg:1kSimb:tn1RHb3Q8hJ-RiOxEZax9S6uHus"; expires=Wed, 28-Oct-2020 15:33:41 GMT; httponly; Max-Age=1209600; Path=/
< Vary: Accept-Language, Cookie
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Robots-Tag: noindex, nofollow
< X-XSS-Protection: 1; mode=block
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0```
