### ISSUE TITLE
rename MviPolicy

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#14770]
`app/policies/mvi_policy.rb` defines `MviPolicy` and should become `app/policies/mpi_policy.rb` and use the inflection to be `MPIPolicy`.

**Comment by erluti** [comment]
this line in the mvi_users_controller `before_action { authorize :mvi, :access_add_person? }` is what uses the policy.  It should also be updated, but it's okay to spin up a new ticket if that doesn't make sense as part of this

**Comment by LindseySaari** [comment]
Yeah, I think the above mpi policy authorization makes sense to include in the same PR since MPIPolicy is derived from the notion of policy classes from the pundit gem. The authorize before_action in the mvi_users_controller automatically infers that :mpi will have a matching MPIPolicy class.
