### ISSUE TITLE
Address feedback v2 of Facility Selection page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14798]
### Based on current v2 of Facility Selection page, we need to address/improve the following items:

**1. Need to add in a H3** _(like we display when show using their home address)_ **when user choose to use their 'current location' to help user understand that we are using the current location based on their browser**

> **Before user selects 'use my current address'**
> ![Screen Shot 2020-10-13 at 6.13.41 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/60c62736-a674-424f-b411-ba2f392d0fb9) 

> **After user selects 'use my current address'**
> ![Screen Shot 2020-10-13 at 6.14.58 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/18fa1e5f-aa9d-4fb0-9d15-6ea00c5871fb)

**2. Need to stylize the following into more an alert + update content to be more 'alert' like**
![Screen Shot 2020-10-13 at 6.18.14 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/e3f46e2b-4fd6-4c5c-bf4a-d2b46397163c)

-----
## Acceptance criteria:
- assist user in understanding they are using their 'current location' by persisting H3 from previous state
- make 'we cannot find your address' an alert

**Comment by lenaecb** [comment]
For #1 - Adding header - @rtwell @narin - for the recommendation here, using actual user's current location... that will require reverse geo-coding which we do not currently support. I think it's quite an effort to get that ability working inside of VAOS. What can we display instead of actual user's current address/location? 

For #2 - Alert - I don't think the modal fits in this scenario. We could make this more actionable by saying 'We could not access your current location. Please enable your browser if you want to use your current location." + dismissible?

**Comment by peggygannon** [comment]
@rtwell @lenaecb 

Hello,  a couple of thoughts from moi: 

1. H3 and toggle back link look good. 

2. Here is recommended tweak to the alert: 
**We can't find your current location**
Be sure to allow your browser to find your current location and try again. 

I see [try again] is styled as a link in the above screenshot. Where does that take users? 


3. I think we might want to tweak the intro copy as well. Right now we say we base the address location on address on file, but we that doesn't apply when users use "current location" 
Suggest we remove the place we based this one from the intro altogether so it works for both scenarios:

{intro}
Below is a list of VA locations where you’re registered that offer {type of care] appointments. Locations closest to you are at the top of the list.

**Comment by rtwell** [comment]
2: In this scenario, a user clicked "use my current location" and then selected "Block" in the pop-up. It looks like this:

![image](https://user-images.githubusercontent.com/12564977/96127539-6e2fc200-0ec2-11eb-9d85-dd9335a341ab.png)

Then we display the alert saying "We cant find your current location…" (we cannot because they blocked it). Clicking "try again" is like clicking "use current location" again/for the first time—it's going to trigger the browser prompt to Allow or Block the browser from detecting your current location. Ideally they will select "Allow" and then we can return a new list based on current location.

**Comment by narin** [comment]
@rtwell @peggygannon  I think if the user had selected "Block" in the past, they will not be prompted if they hit "try again". They would have to go into their browser settings to modify the settings for the va.gov domain.  I _think_ we can detect it if they have explicitly chosen "Block" in the past and display different messaging, but I'd have to verify.

**Comment by rtwell** [comment]
oh…what are the user's options if they block? i'm extremely skeptical our users will know how to modify their browser settings. is their only resort to switch back to address on file?

**Comment by lenaecb** [comment]
@rtwell - Correct, we also discussed that we don't think the users will know how to modify browser to re-enable, and how that works/function is very specific between browsers, so we can't easily provide them (nor would we want to provide them) specific directions. Those directions could become wrong fast based on version of browser. 

If we can't get your address _and_ we have an address on file for you, we fall back to using your address.

**Comment by lenaecb** [comment]
So, we can do two things here:
1. Alert #1 - For times where we can't get your address, but not because you blocked us but because you never grant us access, we display an alert that - _"Be sure to allow your browser to find your current location and try again."_ Where try again does actually work because the user didn't block it. 
2. Alert #2 - conditional if we _know_ you have blocked us from using your location - and say something to the effect - "You have denied  permission to use your current location. To use current location, please update your browser location settings." -- it'd be nice if there was a single online resource to updating your browser location... but we also have to thing of mobile... 

@narin, two questions:
- thoughts on above? and...
- we can do 2 conditional alerts, right?

**Comment by narin** [comment]
@lenaecb Yes this is possible. We can check for permissions before asking them to allow or block.  So to clarify:

1. If user has not granted permission but not yet blocked us, clicking "use my current location" would first show this modal, giving them a heads up that they are about to see the allow/block pop up?
2. If the user has hits block, or has blocked in the past, display alert #2, and links them to some sort of instructional info

**Comment by lenaecb** [comment]
@peggygannon @rtwell - thoughts on my two suggestions/ improvement on those suggestions?

Also we are using location (for both VAMC and actual location) and facility interchangeably, what should we do here?

@narin - I am not sure of the modal. I guess I didn't pick that up in @rtwell suggestion. 

do we need to sync up together on this to hash it out?

**Comment by peggygannon** [comment]
thanks, @lenaecb OK, so to clarify, 

we are going with two different conditional alerts:
1. user has already blocked location

2. user hasn't blocked location feature, but they might need remind them to actually allow or grant access. Would this alert below still work for #2 (I defer to @rtwell on how these alerts appear. we can remove bolding from the heading if this will appear more as a "note" rather than an alert. 
**We can't find your current location**
Be sure to allow your browser to find your current location and try again.

**Comment by narin** [comment]
I think we should sync to hash this out and get on the same page

**Comment by peggygannon** [comment]
@outerpress @narin @lenaecb 

OK, here's what we decided on today's sync: 

1. user has already blocked location: 
{alert}
Your browser is blocked from finding your current location. Make sure your browser’s location feature is turned on. If it isn’t enabled, we’ll sort your VA facilities using your home address that's on file. 
{end alert}
<br>


 2. We decided that the 2nd alert shouldn't be an alert at all, but we'd add content to the spinner text: 
{Spinner language}
Finding your location. Be sure to allow your browser to find your current location. 
<br>

3. updated H3 for current location.. TK.. Peggy still working on that one.

**Comment by outerpress** [comment]
@peggygannon @narin Here's the alert styling using the info alert box, as discussed. 
![Location-Blocked-Alert.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/3c4d0e34-b466-4340-bcdb-805b2d19c3c0)

**Comment by narin** [comment]
I'm putting up a PR for this now.  Just 1 final sign off @peggygannon @outerpress:

## Sort by distance from home address (default view)
![Screen Shot 2020-10-19 at 2 18 11 PM](https://user-images.githubusercontent.com/786704/96513299-c3e3d180-1216-11eb-9d36-8af5939c2ad7.png)

## Loading message while requesting location
![Screen Shot 2020-10-19 at 2 17 03 PM](https://user-images.githubusercontent.com/786704/96513312-c9d9b280-1216-11eb-87f3-1e07acc75c37.png)

## Sorting by current location
![Screen Shot 2020-10-19 at 2 22 33 PM](https://user-images.githubusercontent.com/786704/96513341-d827ce80-1216-11eb-84fc-0940728da406.png)

## User clicked "Block location" info alert
![Screen Shot 2020-10-19 at 2 15 43 PM](https://user-images.githubusercontent.com/786704/96513372-e4ac2700-1216-11eb-8d65-85e75d24f028.png)

**Comment by outerpress** [comment]
Looks good to me @narin

**Comment by peggygannon** [comment]
@narin Looks good. thx!

**Comment by narin** [comment]
Verified on staging.  Closing out.
