### ISSUE TITLE
v2 Facility Selection (feedback) Enable user to toggle between 'home address on file' and 'current location' 

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14801]
As a Veteran who is requesting a VA appointment, if I select 'use my current location' on the facility selection page, but then decide I want to use my 'home address on file' there is no way for me to go back to that state. 

## Acceptance criteria:
- Veteran can go back to 'home address on file' state to sort list based on 'home address on file' if they use and allow 'current location' from browser

Last mock, needs some content input:
![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/fb75ffac-3998-412d-815e-edf06a244970)

**Comment by peggygannon** [comment]
@lenaecb I think this is covered in https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14798?

**Comment by peggygannon** [comment]
@narin @lenaecb @outerpress
Here's recommended H3 for when we aren't showing the current location address. 

For when we CAN show the address, I want to confirm that we'd use this H3>  **Your current location:**


{Updated intro} 
Below is a list of VA locations where you’re registered that offer {type of care] appointments. Locations closest to you are at the top of the list.

H3: Facilities based on your location

**Comment by narin** [comment]
Verified toggle is functioning on staging.  H3 for current location should be up when https://github.com/department-of-veterans-affairs/vets-website/pull/14635 gets deployed.  Closing out
