### ISSUE TITLE
Military Information service integration

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14803]
### User Story/ Task

Integrating with military information service. 

### Acceptance Criteria
1. Military information page should display record of user's military history

**Comment by digitalken** [comment]
Testing:

1. Verify military information page displays record of user's military service history.

**Comment by keli13** [comment]
Added mock data to the backend api call until things get approved in staging. Once approved, will double back and remove the mock data.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Displaying mock data as expected.  Moving to Design QA.
