### ISSUE TITLE
 Sample Content for “Need more help” LC Page component 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14805]
## Issue Description
_Sample content needed for 'Need more help' LC Page component_

## Tasks
- [ ] Provide sample content in support of 'Need more help' LC page component

**Comment by RLHecht** [comment]
There should be content put into the Need More Help section of the following templates in prod:

Multiple Q&A: prod.cms.va.gov/node/6898
Step by step: prod.cms.va.gov/node/6899
Checklist: prod.cms.va.gov/node/6924
Videos: prod.cms.va.gov/node/6950
Images: prod.cms.va.gov/node/6954
About: prod.cms.va.gov/node/7910

**Comment by kelsonic** [comment]
Hey @RLHecht did you just input the Need More Help sections for each of those pages or were they already there previously?

**Comment by RLHecht** [comment]
@kelsonic I had put these in Friday or yesterday. Are you not seeing it?

**Comment by kelsonic** [comment]
Ah perfect! I think I am seeing it but I'm awaiting confirmation from @oksana-c regarding implementation details: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14329#issuecomment-706287525
