### ISSUE TITLE
Redirect Request: Manage debt

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#14806]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
We published, but then had to archive this page (https://www.va.gov/manage-va-debt/) due to stakeholder request. It will be archived until January 2021. Since the page was already indexed and is throwing a 404 error, we'd like to put a temporary redirect in place from https://www.va.gov/manage-va-debt/ to https://www.va.gov/debtman/index.asp until we relaunch the page in January 2021.

### Requestor team info
@DanielleThierryUSDSVA (public websites)

### Implementation date
Date new URL(s) will be live: N/A

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing : ASAP

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/manage-va-debt/ | **Must be implemented as a temporary/302 redirect** <br> https://www.va.gov/debtman/index.asp

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. @mnorthuis and I would like to put a temporary redirect in place for our archived manage debt place to the existing debt management site until we relaunch our page. Because the page was already indexed in search before we pulled it, it's coming up in some cases and throwing a 404 error. If you could please let the stakeholders know this as an FYI , we'd appreciate it. Thanks!

**Comment by leahkeeler** [comment]
Will do Thanks!

**Comment by mnorthuis** [comment]
This redirect is vetted and ready for implementation.  **Please note: This must be implemented as a temporary/302 redirect.**  The page will be published out again in the near future.

**Comment by lunascoop** [comment]
@ncksllvn @kelsonic this is ready to be implemented since it does not need stakeholder notification. This must be implemented as a temporary/302 redirect. See Mikki's previous comment

> This redirect is vetted and ready for implementation. **Please note: This must be implemented as a temporary/302 redirect.** The page will be published out again in the near future.

**Comment by kelsonic** [comment]
PR is open, not totally sure how to make it a 302 but [asking here](https://github.com/department-of-veterans-affairs/devops/pull/7807#issuecomment-710451070).

**Comment by mnorthuis** [comment]
@kelsonic Its not something we have done before, so curious about how we can handle it as well.  I want to make sure we don't send a permanent redirect  to Google since this page will come back.

**Comment by kelsonic** [comment]
PR merged (with 302), should be deployed here shortly!

**Comment by kelsonic** [comment]
Deployed and validated, should be all set! 🙂

**Comment by lunascoop** [comment]
Redirect is live. Closing ticket. Thanks @kelsonic
