### ISSUE TITLE
Remove dashboard imports from ApplicationStatus

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#14804]
## Issue Description
The `ApplicationStatus` component imports the personalization dashboard helpers, which inflates the bundle size of all widgets on static pages which use it. I tried to fix that in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14468), but it proved to be kind of a pain, so I reverted my changes until we can figure out the best way to do this.

## Acceptance Criteria
- [ ] The `ApplicationStatus` component no longer imports the personalization dashboard helpers

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
