### ISSUE TITLE
Proof of Minimal Essential Coverage letter

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14814]
## User story

As a user, I want to see a description of my **Proof of Minimal Essential Coverage** letter with the option to view it on my device. 

## Acceptance Criteria
1. Selecting "Minimal Essential Coverage Letter" from the Letters list page routes to a new page
     - This letter corresponds to the following API label: minimum_essential_coverage
2. Include "Minimal Essential Coverage Letter"as a section header, with the following description (static content):
     - "This letter indicates that you have Minimum Essential Coverage (MEC) as provided by VA. MEC means that your health care plan meets the health insurance requirements under the Affordable Care Act (ACA). To prove that you’re enrolled in the VA health care system, you must have IRS Form 1095-B from VA to show what months you were covered by a VA health care plan."
3. View letter button (downloading/viewing the letter is covered in a separate story)

## Testing
- Test account with this letter on file: vets.gov.user+273@gmail.com

## Assets
Google doc w/ description: https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit#gid=2126117638

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Letters" as Header 1
- Mark "Proof of Minimal Essential Coverage Letter" as Header 2
- For info box:
     - Treat as static text 
- View Letters Button
     - Title= “View Letter”
     - accessibilityHint= “View your letter so you can save it to your mobile device."
     - accessibilityRole= “button”

## Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/9/2021 - Looks good on Android and iOS.  Closing.
