### ISSUE TITLE
Create documentation for current set testing tools for use by external teams

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#1481]
## High Level User Story
As an admin, I need to create documentation of our existing testing tools so I can external teams can understand the testing expectations.

## Goals
- Give something to external teams so they know the expectations 
- Will serve as a baseline for evaluating new tools to ensure they provide added benefits while maintaining or exceeding testing coverage

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)

- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by rianfowler** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend-testing-guidelines.md
