### ISSUE TITLE
Access for Keith Osayande

### ISSUE THREAD

**Issue by keithosayande** [department-of-veterans-affairs/va.gov-team#14825]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Keith Osayande
- Please Provide your email.
   > keith.osayande@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Platypus, Software Engineer, AdHoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJYgfTauwLjOZ8HovPS/f6vCwAsO/NlQJg8Bb90x/B1aO/rhNXV5N/ifAY0gacsSTp51j8/nIA3atnfs4Lr2KoHnokZwNRKlDaiitTTOGmsB6co5NlbhApo6SpMAiBX3FUPvnYAdwvXlqH++1xxFruYGk4iZUit/eTD0voyRtot8GyxEZugRoHPbwhdrLowEn0CpcxmpWupvTG9EzOaDRII9R4ljBIthnwPpN2AOjXiXzRjI9jCzhaHUxlKVucg3ooxyzT+F+yTaWNiT/tOWPWHivZT1XPq3o7/YZMz0EzCRsah8gJcLEIRWRWvispLI4Q0D6OHdVRugiWr1KyrGCJa9PTIbsQSVi/VuPyovteueHek2QxZrCVAth7ON3OLIrVz5ZGh3igqUStoi+q3GoUkJVPH8QynlHLdhkHNTI+9oq7NBrElWrZMckFVgrNcdnLip75pmKhaCdjAza3mLj6eqhz+GnuiIf01415tSUagHF5FwMGFo/ZKOEtXz6Knec= keithosayande@Keith-Osayande-Macbook.local

```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
Need AWS access for developing and maintaining the Lighthouse developer portal and API gateway

**Comment by jsev-io** [comment]
**Requesting AWS Access Approval**
User: Keith Osayande @keithosayande 
COR: Cecilia Lee
cc: @Jeff-Hayter

**Comment by jsev-io** [comment]
@keithosayande You should now have access to the SOCKS proxy - please verify.

**Comment by keithosayande** [comment]
@jsev-io My SOCKS proxy is working properly. Do you know when I should be on on the lookout for my temporary AWS password?

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by jbritt1** [comment]
First time login credentials provided to user.
