### ISSUE TITLE
Redesign the Find a VA Form page 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1482]
PLEASE NOTE THIS EPIC INFO HAS BEEN INCORPORATED INTO NEW EPIC AND WILL BE ARCHIVED IF NEEDED AT LATER DATE, 

## Redesign the Find a VA Form page: https://www.va.gov/vaforms/

Search research indicates that the VA forms page consistently gets high organic search traffic. However it has almost no or very little conversion value.  Because this page already gets high organic traffic and has high potential to provide better conversion: 

- we want to redesign experience on this page to the new VA.gov look and feel. 
- we want to create new content on this page to drive traffic to top tasks and to the top digital versions of form applications. 
- we want to add analytics tracking to all links and downloads.

**Search research attached as FYSA:** 
[Analytics Veterans Affairs Forms Page Organic Nov2018-May2019.pdf](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3352350/Analytics.Veterans.Affairs.Forms.Page.Organic.Nov2018-May2019.pdf)

[vaforms-org-search-keywords-SEMRush.png](https://user-images.githubusercontent.com/43381063/60547498-e08c8b00-9ced-11e9-8962-4c37d0e8e3cd.png)

Also tracked in Master DEPO intake board: 
https://github.com/department-of-veterans-affairs/digitalservice/issues/921

---

@jenniferlee-dsva commented on [Tue Jul 02 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-507857501)

@rtwell - content draft. When you're ready, let's talk. 

[VA-forms-slp-conversion-paths-draft-070219.docx](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3352420/VA-forms-slp-conversion-paths-draft-070219.docx)

---

@jenniferlee-dsva commented on [Mon Jul 08 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-509351870)

@mnorthuis @chrisj-usds @JeffBarnesUSDS @Karak888 @DanielleSoCompany -  FYSA. 

At some point, I'll need your help @mnorthuis and @Karak888. @DanielleSoCompany fyi only bc search related. 

---

@jenniferlee-dsva commented on [Mon Jul 08 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-509368983)

@lkoenigsberg for awareness - I want your spreadsheet! 

---

@lkoenigsberg commented on [Mon Jul 08 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-509376760)

I'll share the sheet shortly @jenniferlee-dsva 

Would love a chance to explore what an authenticated version of this forms page might include if there's still time to do that? 

---

@lkoenigsberg commented on [Tue Jul 09 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-509739551)

[VAFormsAudit.xlsx](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3374192/VAFormsAudit.xlsx)

Attached shows the known list of forms that have been "modernized" so that users may apply online via va.gov.  Would be great if, while redesigning, you could consider the experience for these forms and provide guidance on what we'll need to account for in the future as new forms come online.  This, of course, in addition to the overall conversation regarding what an authenticated experience on the search page might include (or even if we encourage login to see status of existing applications).

Looking forward to talking more!

---

@jenniferlee-dsva commented on [Thu Jul 18 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-512986264)

Stakeholders tracked down. Meeting w/them 7/19. 

---

@jenniferlee-dsva commented on [Fri Jul 19 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-513241277)

Uploading Ryan's DRAFT design. Everything is TBD based on findings and requirements w/stakeholders. fysa. @lkoenigsberg @chrisj-usds 
![forms-search-2](https://user-images.githubusercontent.com/43381063/61542707-1f218580-aa10-11e9-879a-294d11646de1.png)

![forms-results-2](https://user-images.githubusercontent.com/43381063/61542734-2779c080-aa10-11e9-94d9-06343defe788.png)

---

@jenniferlee-dsva commented on [Tue Aug 20 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-523129094)

Uploading spreadsheets Brian McCarthy shared: 

[10B4 Forms Database.xlsx](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3521956/10B4.Forms.Database.xlsx)

[S998 Depot Inventory 6-4-19.xlsx](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3521961/S998.Depot.Inventory.6-4-19.xlsx)

---

@jenniferlee-dsva commented on [Wed Aug 28 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150#issuecomment-525872090)

Uploading agenda deck (with learnings ) from call with forms team. 

[agenda-va-forms-082819.pdf](https://github.com/department-of-veterans-affairs/vets.gov-team/files/3552362/agenda-va-forms-082819.pdf)

**Key learnings:**
- The weird search-action.asp pages that's ranking over main search page was originally created for bots indexing. It was not meant to be a searchable, findable static landing page. 
- The weird forms landing pages (the VA forms team calls these "master form detail" pages) - has a dynamic content part and a static content part. The dynamic content part is not always accurately or completely pulling all relevant forms - for a variety of reasons. Steve said via SQL query. 

**Next step:** 
Kevin Reid is going to get me export of customer facing forms in the forms database, and forms schema/data fields.

**Comment by jenniferlee-dsva** [comment]
Kevin Reid's export of all forms in the VA forms search db. Filtered view shows 1,560 VA forms. 
[database-export-VAForms_82819.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3588053/database-export-VAForms_82819.xlsx)

**Comment by jenniferlee-dsva** [comment]
@Karak888 - There appears to be 3 duplicates is this issue. Can you advise - can we clean this up so there's just one discovery issue, one epic, and new tickets associated w/epic based on our email/convo? 

1/ https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19150  Original discovery issue.
2/ This one - duplicates the ^ issue
3 https://github.com/department-of-veterans-affairs/digitalservice/issues/921 

And then this one is labeled epic milestone, which I'm not sure what it is... 
4/ https://github.com/department-of-veterans-affairs/vets.gov-team/milestone/131

**Comment by mnorthuis** [comment]
@Karak888 When you are ready, please create an IA ticket for this work so we can plan for it.  Thank you!

**Comment by artsymartha68** [comment]
I believe @jenniferlee-dsva said that we don't need to add the Description column in the search results table mockup shown above.

**Comment by jenniferlee-dsva** [comment]
Yes, we're changing the Description field to "Related benefit" (actual nomenclature TBD). @Karak888 @artsymartha68 @lwalsh617

**Comment by Karak888** [comment]
@jenniferlee-dsva @mnorthuis @ncksllvn - this was the Epic that was duplicative that I had originally closed in favor of duplicative Epic #1632 - I am going to close this Epic as I believe people are using 2 separte Epics here.  @lunascoop you had the latest in #1482- PLEASE USE EPIC #1632
