### ISSUE TITLE
 Build  `All articles in: <Category>` landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14835]
## Build  `All articles in: <Category>` landing page

**User story:** As a Veteran, if I click on the `Go to all articles` link or the category link in the breadcrumb, I want to see the full list of articles in that category. 

This work needs:
- [ ] FE

[All articles in a category landing page requirements in product repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/view-all-articles-in-X-category-landing-pg-requirements.md#all-articles-in-x-lc-category-landing-page)

**FE ACs:** 
- [ ] Correct H1 is displaying:
   - `All articles in:` {category}  - Note: the category label should be dynamically generated by the FE based on what category the user clicked on.
- [ ] Search component is displaying per design. 
- [ ] The correct category label is showing in the H1 and the "Showing article for" text. 
- [ ]  Category list of articles are showing, alphabetically by the article-H1
- [ ] Article listing is showing text blurb based on [documented rubric ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/view-all-articles-in-X-category-landing-pg-requirements.md#all-articles-in-x-lc-category-landing-page)
- [ ] The [URL and breadcrumb are correct based on IA pattern](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14445)

**ETA needed by:** 
Oct 22 in cms prod; Oct 23 in demo.

**Comment by jenniferlee-dsva** [comment]
I think Nick already started working on the FE for this, per [slack](https://dsva.slack.com/archives/C0173CAJ7A6/p1602599789251000).

**Comment by jenniferlee-dsva** [comment]
Confirming here [per slack](https://dsva.slack.com/archives/C0173CAJ7A6/p1602701225300900?thread_ts=1602700270.298300&cid=C0173CAJ7A6) - these static landing pages are FE only and will not be created as drupal nodes.

**Comment by ncksllvn** [comment]
Copied from [wip IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-learning-center.md) , URL should use `www.va.gov/resources/[category-name]/` pattern

**Comment by brianalloyd** [comment]
@ncksllvn @kelsonic provide estimate. Moving into this sprint based on ETA needed by: Oct 22 in cms prod; Oct 23 in demo.

**Comment by jenniferlee-dsva** [comment]
the URL pattern for static landing pages aren't confirmed yet, as it is still wip.  @mnorthuis will finalize tomorrow and let us know.

https://dsva.slack.com/archives/C0173CAJ7A6/p1602711628314400?thread_ts=1602620978.269100&cid=C0173CAJ7A6

**Comment by jenniferlee-dsva** [comment]
Confirming Mikki's final recommendation for category landing page URL and breadcrumb pattern:

Category landing page | www.va.gov/resources/[category-name]/ | Home > Resources and support > [category-name] | Category name should be pulled directly from Drupal and used for both the URL and breadcrumb.
-- | -- | -- | --


**Learning center categories are:**

1. Burials and memorials
2. Careers and employment
3. Decision reviews and appeals
4. Disability
5. Education and training
6. Health care
7. Housing assistance and home loans
8. Life insurance
9. Pension
10. Records
11. VA account and profile (MVP 1.0)
12. Other topics and questions (MVP 1.0)

**Comment by jenniferlee-dsva** [comment]
Mikki confirmed - the above pattern is intentionally different from the tag-list pages: https://dsva.slack.com/archives/C0173CAJ7A6/p1602775912322500?thread_ts=1602620978.269100&cid=C0173CAJ7A6

**Comment by jenniferlee-dsva** [comment]
Hello - there's some CMS problem with building the demo rn, so we're unable to validate the FE implementation of this category (and the tag) landing page templates. 

@ncksllvn - would you be able to share screenshots or something here from your local, so I can review and validate?

**Comment by ncksllvn** [comment]
Sure, here's `http://localhost:3001/taxonomy/term/282/`

![image](https://user-images.githubusercontent.com/1915775/97202999-b5536800-178a-11eb-8cd3-cdcd8f42d824.png)

**Comment by jenniferlee-dsva** [comment]
validated - updates adding back in article content type super heads ticketed separately as enhancement
