### ISSUE TITLE
Build  `All articles tagged: <Y>` landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14841]
## Build  `All articles tagged: {Y}` landing page

**User story:** As a Veteran, if I click on a tag link on an article (or -- in 1.1 -- the audience link on the homepage), I want to see the full list of articles in tagged with that tag label. 

This work needs:
- [ ] FE

[All articles tagged landing page requirements in product repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/view-all-articles-in-X-category-landing-pg-requirements.md#all-articles-tagged-y-landing-page)

**FEACs:** 
- [] Latest H1 of the page is showing:
   - `All articles tagged:` {Tag}  - Note: the <Tag> label should be dynamically generated by the FE based on what tag the user clicked on.
- [ ] Search component is displaying per design. 
- [ ] The correct tag label is showing in the H1 and the "Showing x of x articles tagged..." text. 
- [ ]  Tagged list of articles are showing, alphabetically by H1
- [ ] Article listing is showing text blurb based on [documented rubric ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/view-all-articles-in-X-category-landing-pg-requirements.md#all-articles-tagged-y-landing-page) - this is the same for all static listings.
- [ ] The [URL is correct based on IA pattern](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14445)

**ETA needed by:** 
Oct 22 in cms prod; Oct 23 in demo.

**Comment by jenniferlee-dsva** [comment]
Confirming here[ per slack]([url](https://dsva.slack.com/archives/C0173CAJ7A6/p1602701225300900?thread_ts=1602700270.298300&cid=C0173CAJ7A6)) - these static landing pages are FE only and will not be created as drupal nodes.

**Comment by brianalloyd** [comment]
@ncksllvn @kelsonic can you estimate please.  Set for Sprint 33 target but would like to move up if you have the bandwidth.  Needs to be ready NLT ETA needed by: Oct 22 in cms prod; Oct 23 in demo.

**Comment by jenniferlee-dsva** [comment]
Confirming Mikki's final recommendation for category landing page URL and breadcrumb pattern:


Tag landing page | www.va.gov/resources/tag/[tag-name]/ | Home > Resources and support > [h1] | The url will include a "tag" sub-directory that does not contain any content. This will provide context to search engines and users that it is a listing page for a specific tag.The actual tag label should be pulled directly from Drupal and be used for the final segment of the url.The breadcrumb will not include the generic "tag" level because it is not part of the content hierarchy and to avoid exposing an empty directory.
-- | -- | -- | --


**1.0 FE tags**

1. All Veterans
2. Sign in
3. Claims and appeals status
4. Payments and debt

**Comment by jenniferlee-dsva** [comment]
Hello - there's some CMS problem with building the demo rn, so we're unable to validate the FE implementation of article landing page templates.

@ncksllvn - would you be able to share screenshots or something here from your local, so I can review and validate?

**Comment by ncksllvn** [comment]
Sure, here's `http://localhost:3001/taxonomy/term/293/`

![image](https://user-images.githubusercontent.com/1915775/97203238-edf34180-178a-11eb-9a0e-53f9e7c40986.png)

**Comment by jenniferlee-dsva** [comment]
validated closing
