### ISSUE TITLE
GIBCT: OJT facilities displaying NaN for tuition values on search results page

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#14850]
All OJT facilities are displaying `NaN` as the value for Tuition on the search results page in the Comparison Tool. The tuition value should be displayed. For institutions with no value, "N/A" should be displayed. This will apply to most, if not all, OJT facilities.

### Steps to Reproduce
1. Access the GIBCT at https://staging.va.gov/gi-bill-comparison-tool/
2. Select the Employers radio button
3. Type "PUGET SOUND" into the search bar
4. Click Search

### Actual Behavior:
![Screen Shot 2020-10-14 at 1.17.19 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2dda4c3e-211a-45dd-a28a-47f692bc8503)

### Expected Behavior:
![Screen Shot 2020-10-14 at 1.18.30 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3414509a-4abb-4bef-990a-e68f6ee4e7e2)

**Comment by ksantiagomorgan6** [comment]
Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/14625

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-20 at 7.19.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d1359d26-9579-422c-9682-074eaa0cf3db)

**Comment by sonntag-adam** [comment]
Fix is in staging. Testing passes QA
