### ISSUE TITLE
GIBCT: Remove prod flag for OJT housing defect.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14852]
As a developer, I need to remove a prod flag so the updated content is available in the production environment.

## Assumptions:
1. The work completed in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18970 has been reviewed and signed off in staging as of 10/15/20

## Acceptance Criteria
1. The work completed in [#18970](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18970) is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14643

**Comment by delli-gatti-michael** [comment]
Changes are showing in a local production build
![Screen Shot 2020-10-20 at 12.01.41 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/96050882-5fb3-4966-a9b4-75bed9a7768c)

**Comment by delli-gatti-michael** [comment]
This fix is now in prod. Closing this issue
