### ISSUE TITLE
[FE] Move/rename reused code from Profile 1 to appropriate folders

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#14860]
## Description
On September 30th 2020 we launched Profile 2.0 to all users. We need to clean up all unneeded components/logic that are no longer needed to support Profile 2.0.

This is ticket 3 of the steps to remove Profile 1.

Ticket 1 - Remove profile 2 feature flag
Ticket 2 - Identify dead code related to profile 1 and remove it
**Ticket 3 - Reused code of profile 1 in profile 2 needs to be moved to the profile 2 folder && renaming of components/logic where needed**

**Comment by sanlouise** [comment]
@mshea0606 There is nothing to validate on your end since this was a code cleanup 😄

**Comment by mshea0606** [comment]
Thanks @sanlouise
