### ISSUE TITLE
[Bug] SIP: Save in Progress Data has PII

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14866]
## Issue Description
While looking through the FE Sentry logs, we noticed that there were a number of errors that ended up dumping PII into the Sentry logs. PII should only be stored in the database.

## Acceptance Criteria
- [ ] No more PII logged to Sentry as part of SIP
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
This is over a year old - can you confirm if it is a problem that PII is saved in SIP? if it is not close this ticket

**Comment by vhenry07** [comment]
No longer an issue.
