### ISSUE TITLE
Validate all the layers on learning center 1.0 article templates

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14864]
## Validate all the layers on learning center 1.0 article templates

**User story:** As a user, I want to be able to see all the content that's available for an article. 

**AC for each 1.0 article templates:**

- Multiple FAQs article template content fields
- Single Question/Answer article template content fields
- Step-by-step article content template fields
- About article template content fields

See use case F section for [full list of required and optional content fields ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/product-use-cases-template.md#use-case-f) for these article types.

**Comment by jenniferlee-dsva** [comment]
**Validating for Single Q& A template:** 

Sample test page http://preview-prod.vfs.va.gov/preview?nodeId=6897  

•	alert component after intro - content added and preview showing
•	Related info links – no content added, but empty component showing in preview @RLHecht 
•	VA benefit hubs – content added, but not showing in preview @kelsonic / @ncksllvn 
•	Need more help/contact info – no content added @RLHecht 
•	Primary category, additional categories – no content added @RLHecht 
•	Tags – no content added @RLHecht

**Comment by jenniferlee-dsva** [comment]
Validating for step-by-step template:

Sample test page [preview url]

**Comment by jenniferlee-dsva** [comment]
**Validating for Multiple FAQs template:**

Sample test page [preview url]

**Comment by jenniferlee-dsva** [comment]
**Validating for About article template:**

Sample test page [preview url]

**Comment by RLHecht** [comment]
@jenniferlee-dsva The missing content from layers for the single QA have now been added.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I added the preview nodes in the comments above for all the templates I added sample content to.

**Comment by jenniferlee-dsva** [comment]
Thank you @RLHecht !

**Comment by jenniferlee-dsva** [comment]
I think nick and kelson are building the FE for some of those layers still, so I'll validate the others when they've all been built. 

@ncksllvn @kelsonic - Randi added maximal possible sample content to the above pages, so you can test the FE against the above nodes.

**Comment by kelsonic** [comment]
Moving to validate as I believe all related PRs have been merged for this

**Comment by jenniferlee-dsva** [comment]
validating and closing
