### ISSUE TITLE
Download & View - Commissary Letter

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#14873]
## User story
As a user, I want a view screen that displays an image of my **Commissary** letter. 

## Acceptance Criteria
1. Selecting 'View letter' from the Commissary letter page should open the letter .pdf with the OS file viewer
     - Display the letters loading screen (#14725) until the rendered letter can be displayed

## Testing
- Test account with this letter on file: vets.gov.user+228@gmail.com

## Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/9/2021 - Issue logged with iPhones and downloading/viewing - generalized. Closing.
