### ISSUE TITLE
Project Kickoff [Facilities Team: Map enhancements (Phase 1- Limit search to 250 miles)]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#14874]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Attach all relevent artifacts to the ticket
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] Shira will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed and [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- [Product outline- WIP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/map-enhancements/phase-1-limit-search-to-250-miles/product-brief.md) 
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **Facilities Team**
- Product Manager (required): **Michelle Middaugh**
- DEPO Product Lead (required): **Dave Conlon**

Entire VFS team (recommended): 

- **Gibran Rodriguez** (Front end)
- **Leyda Hughes** (Design/research)
- **Chris Logan** (Design/research)
- **Michael Pelz-Sherman** (Front end)_-optional_
- **Lance Sanchez** (Back end)_-optional_

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** NO

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite -> **Requesting Tuesday, October 20 at 11 ET**
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

**Comment by shiragoodman** [comment]
thanks @mmiddaugh ! Can you please update the issue title and "Steps to Complete Project Kickoff" to include your team name? Also, please be sure to attach the product outline to this ticket prior to the kickoff. thank you!

**Comment by mmiddaugh** [comment]
@shiragoodman issue is updated, thank you!
