### ISSUE TITLE
Add Debug to Settings

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14871]
## User Story
As a developer, I want to be able to access a Debug screen from settings in development builds. Initially this can just be key:value pairs in text fields with the ability to copy the value with tap

## Acceptance Criteria: 

- [ ] Debug button at the bottom of the settings menu that opens a Debug Component

- [ ] All of the data fields in the Debug Information section below

- [ ] Tap to copy values in Debug Information

## Debug information:

- access_code

- refresh_token

- id_token

This screen can be revisited and added to in later sprints to add or remove debug settings/data

**Comment by lexicalninja** [comment]
@jjulian I think this is good for a first go, is there anything else you want to see here this first time?

**Comment by jjulian** [comment]
This is all we need for now, and I'd add that we need this implemented by next Tues (10/20) to support testing with the IAM team. Option to leave this on a branch, or merge it to develop only enabled for debug builds.

**Comment by jjulian** [comment]
Also note that id_token comes back with the access_token. I think the app ignores this, but to support this screen we need to store it securely. Storing/displaying the full (most recent) responses from the OAuth service may not be a bad idea for this screen.

**Comment by digitalken** [comment]
Testing:

1. Verify settings has a debug button at the bottom which opens a debug component.
2. Verify debug info for:
  a. access_code
  b. refresh_token
  c. id_token
3. Verify tap to copy values in debug information.

**Comment by digitalken** [comment]
PASS 10/22/2020 - Settings page has debug button and page contains debug info for access_code, refresh_token and id_token with tap to copy values.

![debug.jpg](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/a3d8190c-8f28-455d-a8aa-f8547da1cd42)
