### ISSUE TITLE
Download & View - Benefit Summary and Service Verification Letter

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#14886]
## User story
As a user, I want a view screen that displays an image of my **Benefit Summary and Service Verification** letter. 

## Acceptance Criteria
1. Selecting 'View letter' from the Benefit Summary and Service Verification letter page should open the letter .pdf with the OS file viewer (separate story for [loading screen](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14725))

## Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Blocked: Letters service is down

**Comment by digitalken** [comment]
Testing...
