### ISSUE TITLE
Product Guide Build for Cerner

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14882]
# Product Guide Build for Cerner 

## Description
_Build a quick product guide for Cerner as discussed in product planning_

### Launch Date
- Next Cerner Launch - DATE: Oct 24

### Product Guide
TBD - Build .md document now in LC repository. 

## Tasks
- [x] Update existing guide
- [ ] Share with Contact Center liaison team (If applicable)

## Acceptance Criteria
- Updated product guide for Learning Center MVP 1.0 beta launch.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @clantosswett @lalexanderson-dsva Here's an info sheet for contact center like the one I put together for Chalmers. Lauren, I also pulled in the latest info from that doc we got/edited for Cerner about the transition period. Please let me know if anything looks amiss.

[VA.gov My VA Health contact center information 10.21.20](https://app.zenhub.com/files/133843125/9ada35f5-63d9-4a0d-aba5-f0a7b08a5833/download)

Thanks!
