### ISSUE TITLE
[Bug] - file upload hangs

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#14889]
When I log in as user 229 and go to https://staging.va.gov/track-claims/your-claims/600208426/files

and try to upload [empty_file.txt](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/fixtures/files/empty_file.txt)

The network request for the upload never happens and the page looks like this.
<img width="1082" alt="Screen Shot 2020-10-14 at 10 26 26 PM" src="https://user-images.githubusercontent.com/19188/96069507-5cbbcb00-0e6c-11eb-994c-d54e31496a81.png">

I see [this error in sentry](http://sentry10.vfs.va.gov/organizations/vsp/issues/140/events/0df05a5803854690bedcc1d0c78edddc/?environment=staging&project=4&statsPeriod=14d)

**Comment by annaswims** [comment]
when I try to upload [the same file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/fixtures/files/empty_file.txt) on iphone safari 
the uploader tells me it's 74 bytes
![IMG_1480.PNG](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/b0e4c875-f554-49ac-8832-6d4bfa41a3aa)![IMG_1481 2.PNG](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/abff6221-d4c9-4e80-8e56-eaa87f160425)

**Comment by annaswims** [comment]
this bug is related but maybe different.  Should I make a new ticket?  It's looking like in mobile safari/safari the file body is missing sometimes. 

http://sentry10.vfs.va.gov/organizations/vsp/issues/2757/tags/?project=3&statsPeriod=14d

**Comment by Mottie** [comment]
I was not able to duplicate the file hanging issue, but this fix will prevent zero-byte file uploads. We will be able to test this once it's in staging. I think it'd be best to convert our Nightwatch e2e tests into Cypress e2e tests to better handle uploading testing.

**Comment by Mottie** [comment]
Confirmed that it's working! 🎉  
![Screen Shot 2020-10-27 at 12 01 33 PM](https://user-images.githubusercontent.com/136959/97335783-3c1c4980-184c-11eb-85b6-4c73a7ebb07d.png)

**Comment by annaswims** [comment]
On mobile safari I am able to upload the same 0b file.

**Comment by annaswims** [comment]
never mind.  the test file became not-empty when I saved it to my phone.
