### ISSUE TITLE
Direct Deposit page - Tap to call buttons are too short (minimum 44px X 44px), flagged by Deque

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#14908]
## What happened?
Using Deque and Axe to test on an Android simulator, the tap to call buttons for phone calls are flagged as being too short and don't meet minimum a11y specs.  Axe returned violations on both phone number buttons (and the back button, but this one is already logged.)

## Specs:
- Android Pixel 3XL simulator
- Using Deque and Axe for testing
- Test user:  ben.morgan@id.me

## Steps to Reproduce
- Run Axe accessibility scan on Direct Deposit page.

## Desired behavior
Buttons should be a minimum of 44px by 44px.

## Acceptance Criteria
- [ ] Running Axe scanner on page will return no violations for tap to call buttons.

## Bug Severity
4 - Low

## Linked to Story
13902 https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13902

## Screen shot(s) and additional information
https://mobile-docs.deque.com/attest/android/android-touch-target-size.html

![directDepositTapToCallButtons.gif](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/89c750bb-5181-438f-9fc1-454005f9ae89)

**Comment by esther-k** [comment]
**11/24**

PASS- on Android (no method to test on iOS). Phone number touchpoints meet minimum 44px by 44px requirements on both Axe and Accessibility Scanner
