### ISSUE TITLE
GIDS: gibct_benefit_filter_enhancement feature flag 

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#14901]
The gibct_benefit_filter_enhancement feature flag was affected by refactoring and not working correctly. This caused the "Your military details" and "Your housing allowance" to go missing from the search results page. 

Steps to reproduce:
1. Navigate to https://staging-api.va.gov/flipper/features
2. Observe gibct_benefit_filter_enhancement feature flag is on
3. Navigate to https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=college+of+charleston
4. Observe the filters above are missing

Expected behavior:
Your military details" and "Your housing allowance" is visible on the search results page when the feature flag is on

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14593

**Comment by sonntag-adam** [comment]
This is now fixed in staging.

**Comment by sonntag-adam** [comment]
Closing bug.
