### ISSUE TITLE
Inject JS to hide va.gov header/footer in the webview

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#14906]
## Acceptance Criteria
1. Hide va.gov header/footer when displaying pages in-app using post-load js

**Comment by bessgreen** [comment]
JS from Jonathan:
```
document.getElementsByClassName("header")[0].style.display='none';
  document.getElementsByClassName("va-nav-breadcrumbs")[0].style.display='none';
  document.getElementsByClassName("footer")[0].style.display='none';
```

**Comment by digitalken** [comment]
Testing:

1. Verify va.gov header and footer are hidden for in-app web view of pages.

**Comment by digitalken** [comment]
PASS 10/20/2020 - VA Header and Footer are hidden in app webviews.
