### ISSUE TITLE
[Discovery] - Wizard migration conversation guide

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#14914]
Create conversation guide for research study

**Acceptance Criteria**

- [x] Create conversation guide
- [x] Share with @mnorthuis @peggygannon and @johnhashva for review
- [ ] Update based on team feedback
- [x] Add link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/discovery/research/wizard-research-plan.md)

**Comment by andaleliz** [comment]
@peggygannon @mnorthuis @johnhashva Here's a link to the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/discovery/research/wizard-migration-convo-guide.md) - it's in a better state than when I shared in Slack.  

We'll likely make some tweaks once the prototype is completed, but pinging you here to give you an opportunity to provide feedback or edits.

**Comment by johnhashva** [comment]
@andaleliz looks super-solid.   So good to know we are going to have this opportunity to validate our work before we go into production.  Thanks to you and @chrvalla for orchestrating the sessions.

**Comment by andaleliz** [comment]
submitted guide to Lauren for recruiting
