### ISSUE TITLE
Generic Error State - Errors that we ask users to retry before calling call center

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14917]
## User Story
As a user, if my data doesn't load, I want to understand what I can do to fix it or where to turn for help.

## Error Codes Include:
- 503
- 504

These are things where a service is down for time being, retrying might help. Maybe "We’re sorry. Something went wrong on our end. Please refresh this page or try again later. Or please call the call center."

**Comment by bridgethapner** [comment]
:wave: I have a follow-up question about this error @kreek -- when this error displays, would it always display alone on the screen with no other content? Or would it ever be possible that one API call on a screen may have been successful, and another will not have been?

**Comment by bridgethapner** [comment]
Attached is my first pass at this error state. 

Here's some context from the [Error Message style guide](https://design.va.gov/patterns/messaging-error-messages#next-step) that I used to help make UX decisions: 
1. I see the following guidance on when to direct users to the call center: **"a user can’t resolve an error that is directly related to the website (specifics TBD)"**
2. When VA.gov errors direct users to the call center, they give the user a specific reason to call center about: **"We can’t find your records in our system. If you think they should be here, please try again later or call the VA.gov help desk."**

In keeping with the above, I think we need to give users a clear reason to call the call center, so I've added "If this problem persists..." to tee up the call center information. 

![Generic Error State (refresh then call).png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/e0c9e056-0578-4d47-9879-5b365a331d04)

**Comment by kreek** [comment]
> when this error displays, would it always display alone on the screen with no other content? Or would it ever be possible that one API call on a screen may have been successful, and another will not have been?

@bridgethapner 99% sure no other content. We're trying to move all parallel calls behind the API so that the mobile app can make fewer calls. Some calls will depend on others (letters list -> letter download) but if a failure for one of those happens the user can't get to the next step.

**Comment by bridgethapner** [comment]
This design work is done, the content may change based on VSP feedback. I will create a new ticket for updating content if we need to.

**Comment by bridgethapner** [comment]
@bessgreen [link to UI design](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/435095150) for error states using Mobile Alert CC, [link to copy](https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit#gid=1343695330)
