### ISSUE TITLE
Generic Error State - Msg to Call the Call Center

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14919]
## User Story
As a user, I want to know what to do when there is an error with the app.

## Error Codes:
- 408 (time out, no response from servers, the application stops trying to get a response)
- 500
- 502
- 404 

## [Wireframe](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/435506798)

**Comment by bridgethapner** [comment]
The UX here is done. The content may update based on feedback from VSP. Closing this ticket, will open a new ticket for inputting new content into wireframes as needed.
