### ISSUE TITLE
[FE] Make wrapper for Dashboard

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#14915]
Make a wrapper component that's responsible for showing either the old Dashboard or the new Dashboard.

This logic should take into account:
- a new feature flag to show Dashboard v2
- a new DASHBOARD_VERSION local storage key that can override the feature flag

This wrapper should function a lot like the wrapper we used to handle showing Profile 2.0. https://github.com/department-of-veterans-affairs/vets-website/blob/ce233470ba31355d96282db3dc6174f9ac65c8d9/src/applications/personalization/profiles-wrapper/ProfilesWrapper.jsx

**Comment by erikphansen** [comment]
@mshea0606 you already closed this but you can view the new Dashboard 2.0 (there is nothing there yet) by:
- logging into staging
- opening the web developer console
- type `localStorage.setItem('DASHBOARD_VERSION', '2')`, hit enter, reload the page

Then delete that flag with: `localStorage.removeItem('DASHBOARD_VERSION')`

**Comment by mshea0606** [comment]
It works! Thanks @erikphansen 
<img width="886" alt="Screen Shot 2020-11-02 at 10 11 05 AM" src="https://user-images.githubusercontent.com/60523453/97884230-d3bde400-1cf3-11eb-8677-fc1cf1fc3885.png">
