### ISSUE TITLE
[Discovery] - Final synthesis for wizard migration research

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#14930]
Create final synthesis based on [this template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/research-findings-template.md) for wizard migration research

**AC**

- [ ] First draft published to GH and shared out w/ team 
- [ ] team feedback incorporated into final draft
- [ ] Final synthesis shared w/ team (either link or read-out) [synthesis PDF](https://github.com/department-of-veterans-affairs/va.gov-team/files/5548107/Wizard.Migration.Usability.Study.Synthesis.pdf)
- [ ] Add link to [research history doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md)

**Comment by andaleliz** [comment]
Synthesis completed by Josh and Megan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/discovery/research/wizard-migration-synthesis.md

@joshkimux and/or @mgleo can you please export your deck as a PDF and upload to this folder, and then close out this issue? Thanks again for all your help!

**Comment by mgleo** [comment]
[Wizard Migration Usability Study Synthesis.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5548107/Wizard.Migration.Usability.Study.Synthesis.pdf)
