### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#14934]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
carol.wong@oddball.io 

## Access Requirements
_Please list any requirements, if any._

## Date Required
Not specific date. 

## Product Team / External Team / VA Office
Design System Team / Oddball / VSP

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Hi @caw310.  

You should have received an email in your @oddball.io with your access.

Let me know if you don't see it.

Thanks!

**Comment by caw310** [comment]
> Hi @caw310.
> 
> You should have received an email in your @oddball.io with your access.
> 
> Let me know if you don't see it.
> 
> Thanks!

I got the link. Thank you!
