### ISSUE TITLE
Profile page - User profile information (name, service branch) is not displaying

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#14932]
## What happened?
When I navigate to the user profile page, the user's name, branch of service and service icon are not displaying.
I have tried multiple users and hard restarting the app but I'm still not getting profile info displaying.
Not sure if this is a service issue or something else.

## Specs:
- Android Pixel 3 XL simulator
- user(s) ben.morgan@id.me and patient998@id.me

## Steps to Reproduce
- Start app.
- log in with valid account.
- Navigate to profile page.

## Desired behavior
When navigating to the user profile page, I'm able to see user name, branch of service, and service icon toward top of page.

## Acceptance Criteria
User is able to see their profile information on the profile page (name, service branch, service icon.)

## Bug Severity
3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13885

## Screen shot(s) and additional information

![profilePageMissingInfo.gif](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/7c938eca-dce2-4566-9d45-e5a072eecd97)

**Comment by digitalken** [comment]
@bessgreen - I spoke with Brandon about this and tried to trouble shoot with him, and he's not sure if this is a service issue or just what.  I don't know how to assign it.

**Comment by bessgreen** [comment]
10/27 update:

- **Findings:** When logging in via the OAuth flow, the patient name/military seal does not display in the header. After closing the app and re-opening via biometric authentication, the profile info displays as expected. 
- **Logins used:** patient998@id.me, marcy.nadeau@va.gov
- **Devices tested:** Android Simulator > Google Pixel 3XL

**Comment by bessgreen** [comment]
11/5 update:

- Tested on Samsung Galaxy S9, working as expected. 
- Moving ticket back to Known Issues pipeline until we can test on an iOS device after the next TestFlight release.

**Comment by digitalken** [comment]
11/3 4:05pm update:

- @bessgreen - Tested on Moto G7 and it was working as expected, for a while.  The logo, name and military information went away after a while and wouldn't come back without me logging out and then logging back in.

**Comment by erikphansen** [comment]
Sorry about the noise I created hear by accidentally connecting my PR to this ticket.

**Comment by digitalken** [comment]
PASS 12/7/2020 - Getting data filled in here now.  Some users may or may not have all data. Keeping an eye on it, however.
