### ISSUE TITLE
Investigate and add nonce values to performance dashboards for CSP 

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#14936]
## Background

See threads for background: 

https://dsva.slack.com/archives/CJRQ85PQB/p1602773929257900
https://dsva.slack.com/archives/CQH357ZTP/p1602771949155900

## Tasks

- Add `nonce=**CSP_NONCE**` to appropriate `<script>` elements so that the nginx `sub_filter` directive will replace the nonce placeholder value (`**CSP_NONCE**`) with the actual nonce.

**Comment by billfienberg** [comment]
The nonces have been added to staging. I think that means we can close this ticket. 

![image](https://user-images.githubusercontent.com/6130520/96268694-f7142f80-0f8e-11eb-97ac-d5c2d8f1d9a4.png)

Slack thread: https://dsva.slack.com/archives/CQH357ZTP/p1602807568171800?thread_ts=1602771949.155900&cid=CQH357ZTP

**Comment by kfrz** [comment]
Thanks @billfienberg !
