### ISSUE TITLE
Create enrollment and registration gating mocks

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1494]
## Story
As a veteran who is not registered at any VA location and / or not enrolled in VA healthcare, I want to understand what I need to do in order to schedule a healthcare appointment offline, and what I need to be able to do to use the VAOS tool in the future so that I can interact with the VA healthcare system in a way that is convenient to me.

## AC
- [ ] Create mock for app state where veteran is logged in through an LOA3 account but veteran isn't enrolled in VA healthcare so can't use VAOS.
- [ ] Create mock for app state where veteran is logged in through LOA3 account but veteran isn't registered in any VistA instance so can't access VA online scheduling functionality.
- [ ] Upload mock to GH VAOS design folder
- [ ] Mock includes adequate explanation of situation + actionable next steps for veteran to take to resolve the situation
- [ ] Mock indicates on which app page(s) this UI should live.

**Comment by peggygannon** [comment]
@goldenmeanie @rtwell @markgreenburg Here's a draft of a gating message prompting users to sign in. Let me know if I need to create error message if a user tries to sign in and doesn't meet all or one of the requirements below: 

{user not signed in}

**You need to sign in to use the VA appointment tool**
You can book an appointment online using the VA appointment tool if you meet all of the requirements listed below. You’re:
	Enrolled in VA health care, **and** 
	Registered in at least 1 VA medical center that accepts VA online scheduling
**Note:** You won’t be able to use the VA appointment tool if your health care facility doesn’t support online scheduling.  

{button} Sign in to schedule your appointment

[Find out how to apply for VA health care benefits](https://www.va.gov/health-care/how-to-apply/)
