### ISSUE TITLE
Upload Evidence to Claim - API Work

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#14942]
## User Story
As a user, I can use my phone's camera to upload files to a claim or add files from my phone's files to a claim.

## Wireframes
[The document upload UX flow can be triggered from this screen](https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432345660).

**Comment by bessgreen** [comment]
@jperk51 to investigate services for file upload

**Comment by jperk51** [comment]
Doc type Whitelist: 
pdf, gif, tiff, tif, jpeg, jpg, bmp, txt

**Comment by jperk51** [comment]
Max file size:
50 megabytes
Larger for PDFs? (@lexicalninja)

**Comment by srmyers17** [comment]
- Frontend will have a validation on file type
- Fronted will have a size validation for file
