### ISSUE TITLE
CT: search results are different after refreshing the search results page

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#14944]
If a user refreshes the search results page after performing a regular search, the schools listed in the search results change.

1. Access https://staging.va.gov/gi-bill-comparison-tool/
2. Type "university of california" into the search bar and click search 
3. Note search results
4. Refresh the page
5. Notice search results have changed

#### Initial results
![Screen Shot 2020-10-15 at 4.34.05 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/17cd0bc4-f6ef-4c3b-9643-2a38d76ca1c0)

#### After refresh
![Screen Shot 2020-10-15 at 4.34.19 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6a4a19d5-ee6d-43b7-b0b0-05b420dca35f)

### Expected behavior
Search results are consistent

**Comment by elder-joseph** [comment]
This issue was resolved by https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10810 and is no longer able to be reproduced.

**Comment by delli-gatti-michael** [comment]
Confirmed this is not happening anymore. Closing this bug.
