### ISSUE TITLE
Alert for 'type of care not available in healthcare system'

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1495]
## Story
As a veteran, I want to know what to do when the type of care I'm requesting doesn't exist in the VA healthcare system in which I'm registered so that I can take the next action to get the care I need.

## AC
- [ ] Mock exists for UI state where veteran is registered to a VA healthcare system but that system(s) doesn't have the type of care they're requesting
- [ ] Mock uploaded to VAOS design folder in GH
- [ ] Mock includes information about which page(s) the pages that should include this messaging
- [ ] UI should include appropriate explanation of situation to veterans as well as next steps for them to take to get care they need

## Thoughts
We should understand how / if this should tie into Community Care (i.e., maybe we want to show veterans private options when their thing isn't available at a VA system where they're registered).

**Comment by rtwell** [comment]
here's my initial pass at this—but it needs some content attention from @peggygannon 

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/280ede86-282d-476c-8108-28c3608055a5)

**Comment by markgreenburg** [comment]
@narin do you think we have the data available to show what @rtwell is suggesting? If not, what can we show? For example, I know that we're deep linking to the VA Facility locator page on the appointments list.

**Comment by markgreenburg** [comment]
Chatting with Ryan & Alex - if we can't get facility info without adding another integration, we could do something along the lines of what we do in the appointments list where we use a deep link to facility locator instead.

**Comment by peggygannon** [comment]
Hello @markgreenburg and @rtwell Please see below for my content recommendation for this alert. It would be helpful if we reviewed this at our next content sync to ensue I've captured accurate message and intent. 


**We’re sorry. There are no {type of care} appointments at this location**
 This facility doesn’t accept appointments for this type of care. Please call the medical center for more information. 

{expander text with medical facility address and phone}


OR if we can't add the facility info in the alert, THEN:

**We’re sorry. There are no {type of care} appointments at this location**
This facility doesn’t accept appointments for this type of care. Please call the medical center for more information. 

You can find contact information for this medical center at [our facility locator tool](va.gov/find-locations/).

**Comment by peggygannon** [comment]
@rtwell thank you for the clarification. Would the below update work? 


**We’re sorry. This location doesn't allow online scheduling for {type of care} appointments**
You can't schedule this type of appointment online. Please call the medical center for more information.
You can find contact information for this medical center at [our facility locator tool](va.gov/find-locations/).

**Comment by rtwell** [comment]
perfect! thank you!

**Comment by narin** [comment]
We can now pull facility details pretty easily.  I've combined the original design with the updated copy Peggy suggested:

![image](https://user-images.githubusercontent.com/786704/70180877-b58bd600-1695-11ea-885b-696cc922ae80.png)
