### ISSUE TITLE
Access for Lee DeBoom

### ISSUE THREAD

**Issue by SlakrHakr** [department-of-veterans-affairs/va.gov-team#14954]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Lee DeBoom
- Please Provide your email.
   > lee.deboom@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA API, Engineer, Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQuP0daieVl3hjRl/AoJT1LLXZUtK2t33HAQvWL++I1YCCu95QRAQ43FVa7+KTUKWMDsR0Y2viLahGoDLCN2tk+RJlcFN4lfOOWOi0XpNLEztqXdp2CPWOHyt/3BvXV1aSTrh0xYD9J3vLXVGLba/1ujZqvrcGUjgTZRgc0yAekDwES0xW3a4eSIonhyEXEKdNE5LbVDSZajImFqWp6BF/z8m95q9U2JDBGLVQB9Wa8WILr8UDW+XcCPASC0mRJ5L+74/A4y/LMWlaQ64wVluPJGjiW00gIDYyDxtbxPm6XGt1sAmhUNX/T2eoAYtKhc0rZz+3UFIrh0HpLKcIZsm7zAiuXyvahL8y/0WuTneIXHyE8zZYinY5EfFVpYr7dc/rm5clCUDFmbPOZivp4ZENtg043bE0IHRVMKyVhSzdmwWePvwN5MRiArFi3alYadkUL9qCnCAYBUt0040CuUrANEGVB56P07qC5O9eZvaAmuC20J/zvyDPWxbtCxV2dgM= deboom@DESKTOP-1T82HP7
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
Production access to maintain and deploy services.

**Comment by SlakrHakr** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@SlakrHakr SOCKS Access granted, please verify.

**Comment by jsev-io** [comment]
**Requesting AWS Access**
User: LeeDeboom
COR: Cecilia Lee
cc: @Jeff-Hayter

**Comment by SlakrHakr** [comment]
I have completed my e-QIP, is there anything additional needed before I can get AWS access? Thanks!

**Comment by Jeff-Hayter** [comment]
@SlakrHakr Can you forward me the email that says it was accepted and is being processed?  Once I have that I can approve.

**Comment by SlakrHakr** [comment]
Email forwarded

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by jsev-io** [comment]
Thanks @Jeff-Hayter & @SlakrHakr

**Comment by jsev-io** [comment]
Credentials Provided
