### ISSUE TITLE
Access for Dilloshion Raju (Dillo)

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#14956]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Dilloshion Raju(Dillo)
- Please Provide your email.
   >draju@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Health Care, Senior Backend Engineer, GovernmentCIO

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKP5ggfcuEr4bfzK93PwZfKrwlZwLPTn8cBtdreoq2BNcN4sLDbJY2ryVnRJZGmX/eJNOLns/tmpCZMkSj0WLrejPJ1vxRgbEkb0fKSnBNcQ5li/yvOcPQMdU4Pw3FOjSVBoT3KnMy4oX6SuwATGHt15aQnQj1p80BpQw+l/8xLUZrLIjGG6KcISn7ewdRqYP5tH0twVoZLkBU0HeZe+GFQRhPWe9ayMSREYCaNrZnsYo5xgTefcK7FTNkHStMACZOtQtESnlPtFMjzOZnR2WZFnrIKBFkLCPG2sLcG2tMgUhewwHCLSEwEHopaqzllT6mloeIreLcctXBF7MYPjj/LiYVg43WtmcipM6TD4O8mSWH3X3Zmh3Sl9HZAEto4Bjw/k/ZqtjGH9PqTtuEfOBPWZWtfkI3OKpS9pwb0p/WpFunUR5IgpbTKibXPfDp+B/Bq3sRZhtAG3ScQe0GzUOSJB2yt2QLBDwDIC2c6Rw3fFIRMpIx7l+ohlmNNYROH9sspt/spGWStKABvJobzRRXgXI4wmS8kME5akSRLWxkVfVRvIbZmGdPfeEIAh8dg1PZHrRODem2p2PT2p46JvNH4TJM+6a8hkO4h+V6DGhMYt8gcsD++BKnxfm2NaGLTdqx/WM5J9fiPX7hUUrvH/0OQpPZtdPCpv3080gIOhE/2w== dilloshion@gmail.com

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why? 

@department-of-veterans-affairs/vsp-operations

**Comment by dillo** [comment]
tag: @department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@dillo SOCKS Access granted. Please verify.

**Comment by dillo** [comment]
> @dillo SOCKS Access granted. Please verify.

Works! Thank you!
