### ISSUE TITLE
[Design] Logged-in homepage overview section

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#14952]
## Background

Name tag ticket here #13918

Ryan Thurlwell had the great idea of moving the additional data we had added to the name tag section out into an "Overview" section accessible from the side nav of the dashboard. I think this is an awesome idea we should explore.

[More discussion starting in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13918#issuecomment-709977451)

[Some very messy sketches of how this might work here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13918#issuecomment-710085827)

I included the data I imagine we'd cover here [in the data spreadsheet](https://docs.google.com/spreadsheets/d/1fO3VxUj8U2M268GnpmNmlL8Jdl8E1as33SzuwoTneV8/edit#gid=108371077), but let's discuss in case you don't think this makes the mark. Exact data points can be up for discussion.

## Tasks

- [ ] Create happy path mockup of an overview section
- [ ] Create "no data" mockup of overview section

**Comment by tressaellen** [comment]
Here's a very rough wire-framey first pass. :) 

![My VA Overview](https://user-images.githubusercontent.com/58752772/96284754-81a66000-0f8a-11eb-90c8-f0709e8c685b.jpg)

**Comment by sshein** [comment]
copying my comment here: I actually think after chatting with me at one point, @callen2563  designed a version where "overview" was a part of the left nav, we just used the fancier left nav idea. Maybe she can pull in some ideas from that version.

**Comment by sshein** [comment]
my main question is if someone clicks actions from the overview area, does it lead them to the correct tab on this same page? Or off "My VA" entirely.

**Comment by callen2563** [comment]
This is the version that Shawna is referring to..

https://cassandraallen738782.invisionapp.com/console/HP-desktop-logged-in-ckf3qguc91olj019242g490ji/ckfsf5dyc00ex010y2ug9h0p4/play

**Comment by sshein** [comment]
right! Thanks Cassandra.

**Comment by callen2563** [comment]
Just to clarify the difference with my wireframe is I'm calling that menu item "My Dashboard" instead of "Overview".

**Comment by Samara-Strauss** [comment]
YAY! I am so glad you all are on the same page about this path forward, and also excited to hear you'd mulled over some ideas around this initially :)

I think this section needs to have some visual interest, so let's talk about how we can do that (and @tressaellen I know the mock you posted is intentionally wireframe-y, so not knocking that at all). This is going to be the front door to the whole My VA experience, so we want it to be something that grabs people's attention and uses good hierarchy to draw their eyes to the right pieces of information.

**Comment by rtwell** [comment]
I will add: this overview page is the page has the most room for design exploration—i _highly_ encourage the team to really explore how we can surface a comprehensive overview of what we know about any particular Veteran, at any particular moment in the Veteran's journey, on any particular screen size. the sub-pages (Health care, etc) might be a bit more formulaic, but the overview/dashboard page is the real hero. I cant wait to see what we make!

**Comment by Samara-Strauss** [comment]
> my main question is if someone clicks actions from the overview area, does it lead them to the correct tab on this same page? Or off "My VA" entirely.

I think it depends on the section. For disability rating, that would link off to the disability rating tool. For health care, that would like to the health care section of the dashboard.

Also, I'm thinking about whether for claims, we just link to the claim status tool and don't have a separate claims section of the dashboard. I've been questioning its overall utility.

**Comment by Samara-Strauss** [comment]
> I will add: this overview page is the page has the most room for design exploration—i highly encourage the team to really explore how we can surface a comprehensive overview of what we know about any particular Veteran, at any particular moment in the Veteran's journey, on any particular screen size. the sub-pages (Health care, etc) might be a bit more formulaic, but the overview/dashboard page is the real hero. I cant wait to see what we make!

Agree with Ryan times a thousand.

**Comment by sshein** [comment]
yeah I was looking for the 100% emoji to react to Ryan's post but couldn't find it so went with thumbs up 😆

**Comment by Samara-Strauss** [comment]
So I've been thinking about things today, and I am wondering (again) whether we need the side nav at all, or whether we more heavily lean into the "overview" approach. I sketched out how this might work (it's messy, but hopefully gives enough of an idea), and while we'd certainly be changing direction from the current work (I'm sorry), I also think this is worth discussion.

**Pros**

- After some reflection/reconsidering things/moving from a logged-in homepage design back to My VA redesign, I'm not convinced we have enough data right now in My VA to warrant the side nav, especially considering most people will *not* be the super happy path that has tons of data in each section. Health care does have a lot of content, but every other section, at least as of now, would likely be pretty skimpy.
- This path forward results in less duplication of content we already have elsewhere (eg. do we need a separate claims section in the side nav? or do we just need to show claims updates and link off to the claim status tool?).
- This is a much more iterative approach from what we have now.

**Cons**

- The biggest con is definitely scalability. I don't know where we'd add more information for other benefits. While we don't have a lot of data now, the goal *is* to be able to accommodate growth as teams need, and I don't want to create a design now that breaks 6 months after launch because we decide the side nav is necessary then. I want to set up a scalable path forward so that we can easily integrate new information as we have requests. 

To be honest, I'm totally cool if people think this is a bad idea and we don't proceed forward. This is not a mandate, but hopefully fodder for a discussion or other ideas. We can talk more about this in our meeting on Monday.

![My VA_Overview without side nav](https://user-images.githubusercontent.com/34068740/96310222-ec7c8900-0fd4-11eb-864e-c114efb04eee.jpeg)

**Comment by rtwell** [comment]
First, I would not apologize for pivoting! I love that we are changing it up as we learn new things—agile is what we do!

Secondly, I cannot tell you how refreshing it is to see sketches of what you're thinking! it really helps centralize the problem we're trying to solve from a UX-specific perspective. Thank you!

When I think about a dashboard (particularly on mobile), I ask myself, what are the most _critical pieces of information_ we could surface on a mobile device (also considering the large va.gov header on mobile)? How simple could we make the dashboard? I made a quick wire of how we could approach—this is just a sketch, but I think it communicates the core of what I’m driving towards. I started with what you have in your paper sketch and kept stripping out pieces. We have tools like VAOS/claims status etc that do all the heavy lifting of providing all the details a user might need. I wonder if we could get away with **focusing on the 10,000 foot view only**. I hope these can be a good conversation starter/continuer!

![image](https://user-images.githubusercontent.com/12564977/96454231-92a0dc80-11e9-11eb-8126-4e6293b828da.png)

![image](https://user-images.githubusercontent.com/12564977/96454245-96346380-11e9-11eb-9915-1ddd8c02c6e0.png)

**Comment by Samara-Strauss** [comment]
This is awesome, @rtwell. Thank you so much for more formally mocking this up.

I also wanted to drop in one more sketch which expands on the original "overview" idea. This includes the stats from the original sketch, but also makes this section more valuable by showing updates if they exist. This starts to veer into notification territory, but I don't think this changes our scope that much. The only updates we'd show at this point is for information we already plan to surface in My VA anyway (eg. you have a prescription refill, your claim is about to expire). We wouldn't be on the hook to show updates for anything we don't already plan to handle.

Like the sketch above, this is for discussion purposes and not necessarily marching orders to move forward. Let's talk about it in our meeting later today.

![Another My VA sketch](https://user-images.githubusercontent.com/34068740/96457437-c4b43d80-11ed-11eb-9f7a-5ecb090267c1.jpeg)

**Comment by rtwell** [comment]
yes! now we're talkin'! lots of room to explore—I love the idea of expanding info on desktop and minimizing on mobile 🤔 

side note (totally not necessary at this point in the wires, but it really does affect how this is designed)—i'm working on the WCAG checklist with accessibility folks, and when 508 updates to WCAG 3.0 next year, we cannot get away with "View all", it'll have to say something like "Go to all upcoming appointments" (I think we're also trying to dodge language that is specific to sighted folks AND have to be more specific than just "View all"). While this really adds clarity, it also clutters up a nice tidy dashboard 😢 . Challenge accepted!

**Comment by Samara-Strauss** [comment]
> side note (totally not necessary at this point in the wires, but it really does affect how this is designed)—i'm working on the WCAG checklist with accessibility folks, and when 508 updates to WCAG 3.0 next year, we cannot get away with "View all", it'll have to say something like "Go to all upcoming appointments" (I think we're also trying to dodge language that is specific to sighted folks AND have to be more specific than just "View all"). While this really adds clarity, it also clutters up a nice tidy dashboard 😢 . Challenge accepted!

Oh, 100% agree on having better language. I'm using "View all" and some informal shorthand (like Rx) in sketches for sake of speed and space when I'm working with a sharpie. We absolutely will have clear language like "View disability rating," "View all prescriptions," "View all secure messages," etc.
