### ISSUE TITLE
Contact Center Review for resources and support product (learning center)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14966]
# Request the Contact Center Review 

## What this form is for - Resources and support (formerly called learning center)
Use this template to request a Contact Center review of your product.

### Product Guide
*Please provide product guide link*

[Product guide (.docx)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/resources-and-support-product-guide.docx)
[Product guide (PDF)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/collab-cycle-docs/resources-and-support-product-guide.pdf)

### Launch Date
*Please provide the launch or rollout date and details.*
MVP 1.0 - eta appx Oct 29-Nov 5
MVP 1.1 - eta ~end of December

[MVP phases - 1.0 + 1.1](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/mvp-phases-to-launch)

## Description
*Please provide the name(s) of your product and a high level description of your product.*
This is a new section of the VA.gov site dedicated to support, resources, help, and learning content. It will be referred to as resources and support.  

Primary user story: _As a Veteran, family member, or other beneficiary of VA benefits and services, I want to easily and quickly find information that helps me answer common VA questions without having to call customer service or visit in-person._ 

[Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md#learning-center-product-outline-wip-draft)

[WIP designs](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)

![image](https://user-images.githubusercontent.com/43381063/96481032-fc7cae80-1208-11eb-935f-d833398c29b5.png)

## Acceptance Criteria
- [ ] VSP Analytics & Insights QA has been completed 
- [ ] VSP Analytics & Insights sends artifacts to appropriate contact centers
- [ ] VFS team completes brief VSP Collaboration Cycle Feedback survey [link](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before)

**Comment by Kimberley2019** [comment]
Good Morning @jenniferlee-dsva I have provided the launch details, description, and product guide to the VEO Contact Center.  I have give them until 10/27/2020 to respond with any questions or feedback.  If they do not respond by COB on that day, then we will move forward without their input.  I will keep you posted with anything that they send our way concerning this product guide.

**Comment by Kimberley2019** [comment]
Good Morning @jenniferlee-dsva  The VEO Contact Center did not respond with any feedback or questions.  Therefore, this ticket can be closed.

**Comment by jenniferlee-dsva** [comment]
Tx @Kimberley2019
