### ISSUE TITLE
CT: Add React to GIDS

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14964]
A a developer I need to add the React library to GIDS so that it has the ability to use the same tech stack as the Comparison Tool.

## Assumptions:
1. This work is to only add the library, and will not be an entire refactor.
2. Codeowner for this directory is our team so that back-end does not have to review react changes. 

## Acceptance Criteria:
1. The React library is included as part of the GIDS project.
2. Smoke testing passes

## PRs
Recommend using new PRs, but these can be used for reference: 
Main PR
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/471
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/746
Gem PR
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/492
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/747

## Supporting Artifacts:
1. https://github.com/reactjs/react-rails#rails-5x
2. Initial work was done in this story, but never merged in: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19826

**Comment by jhouse-solvd** [comment]
Spoke w/ @desireeturner and she indicated that they would like to get this resolved within the next 2 weeks if possible ie during this Sprint.

**Comment by desireeturner** [comment]
This is being discussed on slack here: https://dsva.slack.com/archives/CG6N59X40/p1604433713032900

**Comment by dneel-bah** [comment]
Closing as OBE.  The original work was done, but it took a while to approve so the work/pull requests will have to be redone.  Will create a new story when the team is ready to tackle this work.
