### ISSUE TITLE
Access for Tony Williams

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#1496]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > N/A
- Please provide your name.
   > Tony Williams
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I am a VA developer on the VAOS Frontend Team
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  >  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGL0fczRNP3qkp43vmqrn09EuxzR0/ui2O8hVNEyQqh+pxVMQTdXGTahEiCkIJgflQjXEfxfMmpu7UlukxSr4FU+YC8mQOVxddqjFi7nBT3sH7hinvJBuDia94SmLQ4EIqs1zNxjFknE6KOZvtu4HtEq2bicAnzWFIJkSkAJbDtTu2dSV7nfuDLzuDyVtnGAIcATNH6wNwBaS3NQ+5A7xkOw+4BYrLlbSX9qo3ecs6d7AKuKXzlhbysiO9UwlFB2Xpn3RL+GesMRQStG4RPZYtUUYYlWyLr7Qkz3fMxg2bY53Ks5dGruZtNdC20vu4wlrKnUg0c2Kd/C7qcBFPu7dd tonywilliams@Tonys-MBP-2

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Eric Hopkins
User: Tony Williams
