### ISSUE TITLE
EDU: Add logging to spool file processing

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14967]
As a developer, I need to add logging to the spool file processing so that when issues are encountered there is a record that can be used to troubleshoot the issue.

## Assumptions:
1. Not sure what options exist for logging right now? Are there other jobs that provide better notifications on success/failure?
2. Documentation exists that outlines how to access spool files [add link to documentation]

## Acceptance Criteria:
1. The nightly spool file job logs the following information in Production:
    a. Individual submissions that failed
    b. File upload status: success
    c. File upload status: failure
    d. Spool file counts

## Originating Issue Details:
1. The nightly job that generates the spool files and the one that ran for the west coast experienced errors in the middle of the process so we received a number of partial forms in the spool file. Additionally, the east coast file was generated twice.

**Comment by zurbergram** [comment]
AC1

There is already https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/education_form/create_daily_spool_files.rb#L92 if a form is invalid.

It uses the level of `error` for logging, only improvement would be to include the exception or errors that are caught in the logged message.

**Comment by zurbergram** [comment]
There is `info` level logging for which records were submitted, it currently outputs the a count and the ids

https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/education_form/create_daily_spool_files.rb#L129

**Comment by zurbergram** [comment]
Various stats are available to view in promethus
http://prometheus-prod.vfs.va.gov:9090/prometheus/graph?g0.range_input=2h&g0.expr=worker_education_benefits_claim_failed_formatting&g0.tab=1

stats tracked by create spool files
- worker_education_benefits_claim_failed_formatting
- worker_education_benefits_claim_transmissions_#{region_id}_#{type}

**Comment by zurbergram** [comment]
Adding feature flag `sidekiq_create_daily_spool_file_logging` which will flip all logging in `create_daily_spool_files` error level

**Comment by zurbergram** [comment]
Adding a `rescue` to code that writes data to the spool file for each region

```
        rescue => error
          exception = SpoolWriteError.new("Error creating #{filename}.\n\n#{error}")
          log_exception_to_sentry(exception)
```

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5214

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by zurbergram** [comment]
https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/dsva-vagov-staging$252Fsrv$252Fvets-api$252Fsrc$252Flog$252Fvets-api-server.log

**Comment by zurbergram** [comment]
https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/dsva-vagov-staging$252Fsrv$252Fvets-api$252Fsrc$252Flog$252Fvets-api-worker.log

**Comment by delli-gatti-michael** [comment]
Stats are now showing in prod. Closing this issue
