### ISSUE TITLE
Ch36 - Copy mismatches

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#14978]
## Background 
We need to confirm that the design files and the staging environments are synced.

## What happened?
On Staging **Apply for Personalized Career Planning and Guidance** form, copy didn't match provided design prototypes. [See **Steps to Reproduce** for details.]

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Feature-flag authentication: [contact @jason-gcio for HTTP Basic Authentication credentials]
- Test User _(if applicable)_:  For authenticated flows, `vets.gov.user+4@gmail.com` (Alfredo)

## Steps to Reproduce
1. Go to https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction [if prompted for HTTP Basic Authentication login, request credentials from VSA eBenefits team PM.]
1. Under **I know this is the form...**, click **Apply online...**.
1. Scroll down to **subway-map** ("Follow these steps...") section, and observe the following mismatches:
    - **Step 1**: Under **To fill out...** that 2nd & 3rd bullet-items (**Date of birth** & **If your'e a dependent...** are missing.
    - **Step 2**: **...service-connected disability**-related content is missing.
    - **Step 3**: Missing phone number.
1. Scroll back up, click **Start... without signing in**, and on 1st **Claimant Information** [personal info] form-page, observe the following mismatches [these mismatches recur on all subsequent form-pages]:
    - **Form title**.
    - Missing **form number**.

### Screenshots

**Subway-map Step 1**
![ch36-copy-bug-subway-map-step1](https://user-images.githubusercontent.com/587583/96354722-99670c80-108e-11eb-9204-00f87c3fc47b.png)

**Subway-map Step 2**
![ch36-copy-bug-subway-map-step2](https://user-images.githubusercontent.com/587583/96354906-be5c7f00-1090-11eb-9b4a-ff45227f3925.png)

**Subway-map Step 3**
![ch36-copy-bug-subway-map-step3](https://user-images.githubusercontent.com/587583/96354986-bcdf8680-1091-11eb-9f08-542614e0b73f.png)

**Post-Intro-pages form-titles, missing form-numbers**
![ch36-copy-bug-post-intro-form-title](https://user-images.githubusercontent.com/587583/96355295-e948d200-1094-11eb-82da-9eccb8631e4a.png)

## Desired copy
Copy/styling should match design prototypes. [See screenshots below.]

**[Subway-map Step 1](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/132088566/simulate/sitemap)**
![ch36-copy-spec-subway-map-step1](https://user-images.githubusercontent.com/587583/96354758-011d5780-108f-11eb-8198-2ffa6dd4dd30.png)

**[Subway-map Step 2](https://preview.uxpin.com/2dbde8d15bf667f5c584fe4a8a6d011cf9f0a14d#/pages/132088566/simulate/sitemap)**
![ch36-copy-spec-subway-map-step2](https://user-images.githubusercontent.com/587583/96354914-d7fdc680-1090-11eb-9cf5-f45d50b11141.png)

**Subway-map Step 3**
[Missing phone# not provided in prototype.]

**Post-Intro-pages form-title & -number**
![ch36-spec-bug-post-intro-form-title](https://user-images.githubusercontent.com/587583/96355324-36c53f00-1095-11eb-9171-ea0ea0a2e591.png)

## Acceptance Criteria
[See **Desired copy/styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jason-gcio** [comment]
Thank you @tlei123

**Comment by sporeboy** [comment]
This ticket is invalid; new copy/design changes were implemented.

![Screen Shot 2020-12-07 at 11.49.14 AM.png](https://images.zenhubusercontent.com/5d6ec7967521390001c3e794/6928b20f-1b9c-450f-8b30-4caaa4a156d1)
