### ISSUE TITLE
Access for Lindsey Hattamer

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#1497]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Lindsey Hattamer
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Triage Team, BE Engineer, Oddball, Inc.
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

  > ssh-rsa 
  >  AAAAB3NzaC1yc2EAAAADAQABAAABAQDEKEonx99fhK6bKCSYgY6bCRM2vG2TLJasxksesUZuDCC2dcW3vBkjsWs7aSbhJx9C5wVLtcPowUhz+LBXXrAw5rgJEdyZVKPVx2Z57slelTeKPzNVbqnnv1hvDyCKSE5YX3ANfKWEmPHEe8ipeD0RY08zjtX9NVtwwuegKZBh+ANfwl8286hosjxAfis4Kr0DjRi1Fy4VXUyqXr2/URBKRhuyhd85GfS7gEe7fPfGLTgecWvvt1twgl8lHvG7FjCjfoCR64DlB6dgtO6GLhR04CGP6gErhfBm4eeihAN7EgFBdbG9Bn8JGADPRgZL7vlniWmx/UPeQznX/3PacRgH lindseyhattamer@Lindseys-MacBook-Pro.local

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by LindseySaari** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by Jeff-Hayter** [comment]
@ricetj Confirmed.  Please grant access.

**Comment by ricetj** [comment]
Hey @omgitsbillryan, can we close this one out?
