### ISSUE TITLE
EDU: Add keyboard navigation support to Cypress e2e tests

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14970]
As a developer, I need to ~update Cypress~ restore Nightwatch e2e tests to support simulating keyboard navigation in the Comparison Tool so that the test coverage confirms alternate navigation methods are successful.

## Assumptions:
1. The current cypress tab plugin and cypress keyboard button press simulating functionality does not correctly simulate button presses.  This causes e2e keyboard tests to be limited by what can be tested as if a user is using a keyboard to navigate.

## Acceptance Criteria
~1. Cypress keyboard e2e test can navigate through CT Landing Page as if a user was navigating with a keyboard through the page~
1. Nightwatch keyboard e2e test can navigate through CT Landing Page as if a user was navigating with a keyboard through the page

## Supporting Artifacts:
1. N/A

**Comment by cialespr** [comment]
Cypress currently does not support a way to navigate through a webpage using a keyboard. The old night watch E2E test will be revived.

**Comment by ksantiagomorgan6** [comment]
Cypress currently doesn't support the keyboard navigation needed to complete the E2E. I will be reviving the old night watch test.

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14860

**Comment by delli-gatti-michael** [comment]
Test passes in Jenkins. Closing this out
