### ISSUE TITLE
Create comprehensive e2e tests for address validation

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#14987]
We need to create more extensive end-to-end tests for the address validation flow on Profile 2.0. We also need to check that we have enough coverage for updating the user's email address and add additional coverage if necessary.

**Comment by sanlouise** [comment]
@mshea0606 There is nothing to validate on your end, so I will close out this ticket.

**Comment by mshea0606** [comment]
Thanks @sanlouise
