### ISSUE TITLE
Access for Jennie McGibney

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#1498]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > N/A
- Please provide your name.
   > Jennie McGibney
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA developer for VAOS Front End Team
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

  >  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCw2THXhPkXcZDa6tUE9R9TsvWfki+rkutEcqB80NQRWGrUX1Us6CYaepy9W6+m27Q65Mh+pnv61PZLKv6tg5xJ5QGe90c93bYdYgW1VWBjFC9KYyTlG1v8lEQoCh7LLCiWOq5qnM1q43H9p9UHDkodFiwYcid8npr/9q7gQyREZ7FiKRDOTe5dGBDtOXdBIX0OZuU6LDO4SnfoMxjI4Vd1xrr2vNZRq5j013iiYv/Bgln4RqoKrtbJP1fWKrFREDH+EGWsbSdX8LGKnTjicDWHb09eIo9tqTNQNWKvsk83r1YTrklBsknB1idtqsvfYIwVMCnUXymhK8qVhb8oHgbn vhahacmcgibj@MacBook-Pro.fios-router.home

- [Grant AWS Console access?]
  > YES 
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services. 

@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Eric Hopkins
User: Jennie McGibney
