### ISSUE TITLE
Build FE template for the learning center homepage

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#14996]
## Build FE template for the learning center homepage

The test content has been added and ready for FE to build and test with - [ticket #14376](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14376)

**Here is the node** to test FE with https://prod.cms.va.gov/node/8296

**LC homepage requirements:** 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/LC-homepage-requirements.md

**LC homepage designs:**
[Desktop](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b?wid=0-1602260732238) 

[Mobile ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b?wid=0-1602872130292)

**Comment by jenniferlee-dsva** [comment]
Here is the node to test FE with https://prod.cms.va.gov/node/8296

**Comment by brianalloyd** [comment]
@ncksllvn and @kelsonic please add estimate.  I placed in Sprint 33 but can be actioned at anytime.

**Comment by ncksllvn** [comment]
This looks straightforward. Estimating at a 3

**Comment by jenniferlee-dsva** [comment]
Just calling out from our planning call today that the homepage has the ability to display an optional alert - below the search bar.  The test node currently includes a sample alert component content, so the FE can validate it showing. 

Here is the node to test FE with https://prod.cms.va.gov/node/8296

**Comment by kelsonic** [comment]
PR is up for this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14996

**Comment by jenniferlee-dsva** [comment]
validated, closing!
