### ISSUE TITLE
Post-launch BigQuery View Setup - Facility Locator

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#15000]
# BigQuery View Setup
## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- As a starting point, I have made [this query ](https://console.cloud.google.com/bigquery?sq=86772881199:8c4fe7a9669a43a4bc9cd18d1969cbe1) to help create a view from our new facility locator search results tracking
- Would like to continue here in setting up the view to simplify future queries / use within KPI dashboards, other systems, etc

Edge case item to be cognizant of: 
  - Parsing out the event action using `-` For cases where the user may put in their full zip code into the query box, (i.e 84092-3230), we need to make sure our split doesn't exclude these cases (with and without space) and the `searched_query` column consistently returns the correct value

## Acceptance Criteria
- [ ] Date types have been adjusted / casted to best reflect column value nature (i.e `true` should be a BOOLEAN) 
- [ ] View uses standard data normalization as used 
- [ ] Ensure view is configured to update daily (i.e `FORMAT_DATE('%Y%m%d',DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))`)
- [ ] Service type column populates with the correct service type according to service description from dropdown 
- [ ] Query has comments within and header column and has been included in documentation
- [ ] View has been named and setup within non-prod and production
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by JasonTheBearded** [comment]
@jonwehausen @bsmartin-ep here's the link to the query, 
https://console.cloud.google.com/bigquery?sq=86772881199:7338b54de20142bd8bdd7f9cce319064

**Comment by jonwehausen** [comment]
Thanks @JasonTheBearded! 

We will want to tweak this per PII compliance. See steps here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16643#issuecomment-735827010

Together, let's peer review the work to:
- Update existing query to EXCLUDE this data (align with new event action taxonomy) 
- DDL or steps to create a new table from these query results 
- DML to `DELETE` events with event label of `fl-search-results`

cc: @bsmartin-ep

**Comment by JasonTheBearded** [comment]
@jonwehausen facility locator query updated to exclude `searched_query` and `mapbox_place_name` 
link to query is here, https://console.cloud.google.com/bigquery?sq=86772881199:7338b54de20142bd8bdd7f9cce319064

**Comment by bsmartin-ep** [comment]
@JasonTheBearded -

Think we can get the event action where we want it with string manipulation?

https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_replace

**Comment by jonwehausen** [comment]
@JasonTheBearded 
Let's hold off on any further work here until we receive word from Rachel & Joanne on next steps

**Comment by joanneesteban** [comment]
Moving to 'blocked' until we complete the [bug issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16643)

**Comment by jonwehausen** [comment]
@JasonTheBearded we can close this for now
