### ISSUE TITLE
Grafana dashboard for Sum of Errors excludes AppointmentsController

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#15013]
Originally AppointmentsController was excluded from this particular dashboards query because we knew that 409 errors from cancellation were not reason to trigger an alert. That being said, the exclusion here is overly broad in that it also excludes 500 errors as well. We should target and exclude the specific Controller and Error, not the Controller in its entirety.

**Comment by laurenernest** [comment]
Closing. No longer needed
