### ISSUE TITLE
STEM: UAT for SCO emails & Entitlement

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#15018]
The BAH team will be conducting 12 UAT sessions with Veterans starting on 10/26 and running through 11/6 to validate the SCO email and EVSS entitlement functionality associated with the 22-10203 STEM Scholarship application work as expected on Production.

## Assumption
This proposal will not be executed until the Digital Experience Product Office and Education Service approve. This solution will not be executed until STEM 22-10203 Form MVP is 100% rolled out in Production (Deployed 9/10). 
_Update: DEPO and Education Service have approved this approach as of 10/19/2020_

## Problem
The VA.gov Education Application team is currently blocked from testing SCO Email and Remaining Entitlement for the 10203 STEM Form. The VA.gov staging environment currently does not have users with the requisite data (<6mos remaining entitlement & >6mos remaining entitlement) to test the functionality. 

## Proposed Solution
The SCO Email and Remaining Entitlement is currently behind a feature flag in Production. The VA.gov Education Application team would password protect the feature flag, turn it on, and have at least two Veterans (one with <6mos remaining entitlement & one with >6mos remaining entitlement) UAT test the 10203 STEM for with those features enabled. 

The  SCO email will only trigger for eligible applicants so the VA.gov Education Application team will preemptively contact the primary and secondary SCOs ahead of the form submission so they can confirm receipt as well as the SCO of the ineligible applicant to confirm they did not receive an email. 

If we are able to execute this proposal it would allow us to validate the blocked functionality is performing as expected before it is rolled out post MVP (09/10). 

## Execution
- Testing will occur between 10/26 and 11/06 
- We will test with 6 eligible applicants and 6 ineligible applicants
- SCOs will receive notification in advance of testing for the applicants who will be submitting eligible applications associated with their institution. 
- SCOs will be asked to validate that the email was received after the application was submitted.

## Supporting Artifacts
- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/stem/stem-standalone-10203/SCO%20%26%20Entitlement%20UAT

**Comment by johnhashva** [comment]
Approved.

**Comment by desireeturner** [comment]
Testing complete as of this afternoon.
