### ISSUE TITLE
Type of Care API Discovery

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#1502]
## Description
After discussing the first draft of the [API contract](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/engineering/api-contract.yml), we determined more discovery needs to be done around Types of Care. 

The current API requires separate API calls for each clinic/facility to determine the types of care available.  The [new design](https://adhoc.invisionapp.com/share/WATIINRHZ3F#/screens/379622427) reverses the process, asking the user to choose a type of care, then a clinic.  We need to figure out how to streamline the API and minimize the number of API calls possible.

## Acceptance Criteria
- [x] An approach to retrieving types of care has been figured out

**Comment by narin** [comment]
CC: @markgreenburg

**Comment by jbalboni** [comment]
API contract was updated based on new designs. This looks good now.
