### ISSUE TITLE
Access for Micah Chiang

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#1503]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Micah Kaleem Chiang
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > vsa-eBenefits, frontend engineer, Ad Hoc
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsTKXHLaA+k7pClAhO+UhUx8rjXeXArqiktj3Yk6OvPvu7eOBu6XcptYcNkbK56oX0cBDxT0rwma5P7tYkTpN5rBc7qPQuC6AFatkIFSdZ9dASrtjA5l4vQEOCOvRm623+9bqoRlhPSX3XVE5nzFiQKti8+9634Sf5qDxcg/D0iI6i9Yg+ArIRbALKJjvLZWaJ/XTZr/M55UjMcjI0t8q4OGNTCu0KpzfVxiHj/GmP4hP99H2jp7bCdeEAqgQ8dK0z867Wtf3Gjc5A1wBfMY3byicLCsCmAc1zcEtT0DG5mlLzZ8Ku5giGIlKWJTa80pOajBVwznoLw2QIqYtDKgfBpJroZL6Xn2Vxqx37aCSDX8pQHO4OCS7Dl1ZE4flaVZ+mr4ODVmQI5rk1JABH8qj1z1jeBHYUKjZJuvC1bq06ZUTMGAwgZLaESOCgyBN/X9y2QcXJH/lyin12GytQpLp2gkEXJia4O/l8ra1ZTrOORG27Yq7/24JKq5SP0j0Kd64H5j5vI368tlGscvSaOTiirp5P71/kqCQu9Ykx5atbjRBn2K6busCBQ8nWGzR2D/GMxkDc2PNHnyOKzRO7z9Eojs8j8tNAi1sjxXqrIxMB95D18P6oJksRXxAlNyyS7vavDsrzWB23x+4tHvvvyTYzUxoqvq6zeHFzRKJq40+oEQ== micahkchiang@gmail.com

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

# Definition of Done
- [ ] Access acquired

**Comment by micahchiang** [comment]
@department-of-veterans-affairs/vsp-operations tagging you for visibility.

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Micah Chiang

**Comment by Jeff-Hayter** [comment]
@ricetj Paperwork received, approved for both SOCKS and AWS.

**Comment by nwalke** [comment]
AWS console information sent.
