### ISSUE TITLE
Refactor Q&A field_answer in FE Templates

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-team#15041]
## Issue Description

The CMS has deployed a refactored `field_answer` to prod yesterday evening 10/19 based on a field spec change requested last week by Q&A authors. Updated content model is described on the image below.
![Q A field refactoring](https://user-images.githubusercontent.com/16477724/96575519-12808280-128e-11eb-8c09-e03868188d43.jpeg)

## Front end tasks
- Refactor FE queries per content shown on the screenshot to ensure that the content of field_answer is rendered as expected on the Single Q&A and Multiple FAQ templates. 

## Acceptance Criteria
- [ ] field_answer is rendered as expected on the Single Q&A and Multiple FAQ templates.

**Comment by ncksllvn** [comment]
@brianalloyd i picked this up this morning, will be merged by EOD

**Comment by brianalloyd** [comment]
@ncksllvn and @kelsonic this appears to be completed, closing the ticket in support. If not complete please reopen ticket, thanks.
