### ISSUE TITLE
Form 21-530 - "See Additional Page" on Online Application

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#15043]
## What happened?
Per Angela Gant-Curtis: I received an inquiry from Richelle Pearson in VBA regarding VA Form 21-520.  She is looking for a SME in regards VA.gov.  She is currently working as the lead on the Mail Automation team and as they were working to release automation for the [intake of VA Form 21-530](https://www.va.gov/burials-and-memorials/application/530/introduction) they noticed that when the application is submitted through va.gov and input on the 21-530 form for intake it is displaying a “See add’l info page”.  She wants to speak to someone  about whether it is a character limit or the default to add an additional page. 

richelle.pearson@va.gov     Richelle Pearson
Chief of Security, Data and Infrastructure (SDI); PMP
Benefits Systems Management
Veterans Benefits Administration
Office of Business Integration
C: (215) 208-7754

## Specs:
- Device: Unknown
- Browser: Unknown
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] Talk to VA stakeholder to determine if there is a tech issue.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by johnhashva** [comment]
Adding PDF document showing the error which is being reported.
[Uploading 530 Vets.gov.pdf…]()

**Comment by johnhashva** [comment]
[530 Vets.gov.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5411003/530.Vets.gov.pdf)

**Comment by camerontesterman** [comment]
The PDF filler for this form is configured to always put "see add'l info page" in for the address, regardless of number of characters inputted.

**Comment by johnhashva** [comment]
11/From VA business line lead, based on validation testing in production:   

As we were validating the implementation of the below fix, we noticed some inconsistencies. For the most part, the address field is now directly on the form itself (and not on the extra page); however, it’s not consistent. We are seeing that some parts of the address field are still on the additional page, primarily zip code and apt/unit #s. I’ve attached some examples. Are there any opportunities to further mitigate this, such as updating the 530 webform-to-PDF conversion to print the apartment/unit number and zip code fields to the corresponding boxes on the PDF when generated (currently these are printed on an additional blank page) and/or enforce 5 character alphanumeric on apartment/unit number and a 5 or 9 digit numeric on zip code if not already in place.

**Comment by johnhashva** [comment]
Attached here are new examples of various address "issues" related to forms as outlined by the stakeholder (with PII redacted)

[VA 21-530 Application for Burial Benefits_Redacted.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5575282/VA.21-530.Application.for.Burial.Benefits_Redacted.pdf)

[redacted 2.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/5575283/redacted.2.zip)

**Comment by bradl3yC** [comment]
@johnhashva @camerontesterman  is gonna knock out the zip - but in the instance of the example form, if we limit the characters of apartment number to fit on the initial page - it would never have fit his entire address and potentially lead to errors.  It is our recommendation that the apartment number be left unchanged at this point

**Comment by johnhashva** [comment]
@bradl3yC Possible to screenshare today or tomorrow so I can see/reference?

**Comment by bradl3yC** [comment]
It will be the exact same as the form you linked with the exception of the zip being moved to the 1st page.  The apt number moving to the 2nd page is an edge case - normal apt number lengths will go to the first page

**Comment by johnhashva** [comment]
Got it -- thanks.

**Comment by leahkeeler** [comment]
@bradl3yC is this blocked by anything or is it going to be completed this sprint?

**Comment by leahkeeler** [comment]
@johnhashva - This is complete can you please verify so we can close this ticket please?

**Comment by johnhashva** [comment]
@leahkeeler I'll follow up with the VA business stakeholder to validate this and get back.

**Comment by leahkeeler** [comment]
@johnhashva - Can you please confirm closing this ticket?

**Comment by johnhashva** [comment]
@leahkeeler just re-engaged with Richelle, the VA stakeholder with cc: to you. If we don't hear back by tomorrow, we can close this ticket.

**Comment by johnhashva** [comment]
@leahkeeler validated -- and you can close this one.  Thanks.

From: Gatti, Molly A., VBAVACO <molly.gatti@va.gov> 
Sent: Monday, February 22, 2021 6:59 PM
To: Hashimoto, John <John.Hashimoto@va.gov>; Pearson, Richelle, VBAVACO <richelle.pearson@va.gov>
Cc: Self, Matthew <Matthew.Self2@va.gov>; Braddock, Nicholas, VBAVACO <Nicholas.Braddock@va.gov>; lkeeler@governmentcio.com
Subject: RE: Va.gov additional forms

This has been validated, things are looking good! Thank you

Molly
