### ISSUE TITLE
Website build not possible without SOCKS proxy

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#1504]
## User Story
As an engineer without access to the SOCKS proxy, I need to be able to build `vets-website` locally so I can work while I wait for access to the proxy.

## Acceptance Criteria
- [x] Engineers don't need access to the proxy in order to build the website locally

## Possible solutions
- While setting up the CMS feature flags during the build, check the build type; if `localhost`, use a Proxy which returns `true` for any property that doesn't exist
  - We'd have to bypass the actual loading done [here](https://github.com/department-of-veterans-affairs/vets-website/pull/10672/files#diff-8202ac974e37766c7d41224339c3ec37R56)
  - Could set up an object with the defaults, but I don't want that to be confusing for anybody since the _actual_ list comes from the CMS

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by micahchiang** [comment]
Created https://github.com/department-of-veterans-affairs/vets-website/tree/1504-build-locally-without-socks to capture the work for this. 

@cvalarida - wondering if I can get your input on my latest commit. I've added a check to see if a cached feature-flag.json file exists. If it doesn't, then use the old featureFlag.js file. This probably isn't an optimal approach, since it seems we want to move away from featureFlag.js. Though, I'm not sure how a developer without SOCKS proxy would get the feature flags otherwise. The way it stands, I think once a developer has SOCKS proxy, they should only need to run `yarn watch --pull-drupal` once for a file to properly build in cache.

**Comment by cvalarida** [comment]
:wave: Hey @micahchiang! Thanks for looking into this.

As of today, we're planning on doing things a little differently. The short story is we'll stop failing builds for missing feature flags. (https://github.com/department-of-veterans-affairs/va.gov-team/issues/1583)

For this PR, what I'd recommend is changing up [that Proxy](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/load-saved-flags.js#L14) so it looks for the build type and not throw the `ReferenceError` if the build type is `localhost`. I _think_ that should do it for you.

**Note:** You'll have to pass in the `buildOptions.buildtype` from [where `useFlags` is called](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/options.js#L194)...and [`loadFeatureFlags`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/drupal-aws-cache.js#L35), since that calls `useFlags`.

Feel free to hit me up in Slack if you have any questions or want to pair program on this one to bust it out!

**Comment by micahchiang** [comment]
Closing issue since PR for department-of-veterans-affairs/vets-website#10687 has been merged and closed.

**Comment by jason-gcio** [comment]
This was complete in Milestone: eBenefits Sprint 3 before it was being officially tracked
