### ISSUE TITLE
Spike - Upload a Photo

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#15044]
Investigate if VA.gov forms has created a photo upload workflow we can leverage 
If no va.gov forms workflow - create a tech feasibility doc for implementation.
Need to determine how PGD will accept photo upload via our MAP api
Need to determine our integration with our questionnaire in PGD and viewable by the clinician in CPRS

**Comment by julieadair1** [comment]
@jparker0425 do we need to prioritize this work?
cc: @batemapf

**Comment by jparker0425** [comment]
@julieadair1 closing this out. I have never heard any mention of photo uploads, so if this comes up in the future for Check-in, we can create a new epic at that time.
