### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#15048]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

If the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

hayley.evans@agile6.com
natalie.dunbar@agile6.com
nathan.douglas@agile6.com
adrian.rollett@agile6.com

## Access Requirements
"VA.gov CMS Backend" Property

## Date Required
as soon as practicable

## Product Team / External Team / VA Office
VFS-CMS

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bmcgrady-ep** [comment]
@cmaeng - Each of the users have been granted access to Google Analytics and should receive an email that they have been given access.

**Comment by bmcgrady-ep** [comment]
@cmaeng - Closing out this ticket as the users have been given access to Google Analytics. Feel free to reopen if you have any issues with the GA access.
