### ISSUE TITLE
Changing how errors and error state works on forms

### ISSUE THREAD

**Issue by jgacek** [department-of-veterans-affairs/va.gov-team#15051]
### User story(ies)

_As a developer, I want to be able to control the error state of fields, so that newly rendered fields do not show up in an error state_

_Example: As a VFS developer, I need to be able to create a custom error message for the XYZ form, so that I can implement the unique error message content that has been approved via the VSP Collaboration Cycle._

### Additional details/notes/links

_Please include a complete description of the issue or request, including links to relevant documentation and conversations._
Discussion on [slack here](https://dsva.slack.com/archives/CBU0KDSB1/p1603137469229000)

If a user tries to continue onto the next page of a form but they did not fill out all required fields then the form will prevent them from going onto the next page and highlight the empty fields. This is the expected state. Then let's say the user changes one of these fields and it renders new required fields because we are in an error state all these newly rendered fields will also be highlighted red. We want to be able to prevent that so that the newly rendered fields will show up as normal.

### Acceptance criteria

_What must be true in order for this to be complete?_ 
1. Highlight any currently displayed required fields that are blank when the user tries to move onto the next page of the form without filling those fields out
2. After being prevented from moving onto the next page, prevent any newly displayed required fields from being highlighted if the user selects an option that shows more fields (For example: expandUnder and hideIf fields)

### Point(s) of contact

_Who should be kept INFORMED of the status of this request? Please tag them here._
@department-of-veterans-affairs/orchid 

### What type of issue is this? 
- [ ] Bug
- [ ] Request new feature
- [x] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

### How to configure this issue
- [ ] When ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
