### ISSUE TITLE
[Analytics] VEO August Metrics Request

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1505]
## User Story
As a VEO user, I need monthly analytics for Education, Burials, and Claims so I can report on this data to internal stakeholders.

## Goal
Provide monthly data for August in visualization
Provide links to Jack Yang within Google Analytics

## Acceptance Criteria
 - [x] Monthly Data
 - [ ] Visualize Data

## Definition of Done
 - [ ] Attached to a Milestone (when will this be completed?)
 - [ ]  Attached to an Epic (what body of work is this a part of?)
 - [ ]  Labeled with Team (product support, analytics-insights, operations, triage, tools-improvements)
 - [ ]  Labeled with Practice Area (backend, frontend, devops, design, research, product, ia, qa, analytics, call center, research, accessibility, content)
  - [ ] Labeled with Type (bug, request, discovery, documentation, etc.)

**Comment by joanneesteban** [comment]
CSAT updated:
![image](https://user-images.githubusercontent.com/48964695/64214200-71fab380-ce7d-11e9-8f8d-1ee289b72ff0.png)

**Comment by joanneesteban** [comment]
Post-Relaunch Satisfaction:
![image](https://user-images.githubusercontent.com/48964695/64214279-db7ac200-ce7d-11e9-9e76-d1ecf915fe5c.png)

Pre-Relaunch Satisfaction:
![image](https://user-images.githubusercontent.com/48964695/64214296-efbebf00-ce7d-11e9-9f99-3e70686a151a.png)

**Comment by joanneesteban** [comment]
Due by EOD Monday, 9/9.

**Comment by joanneesteban** [comment]
@amycesal here's @nedierecel 's metrics:
![image](https://user-images.githubusercontent.com/48964695/64434631-f40df680-d08e-11e9-876a-cdcbb84d4e9d.png)

Metrics:
GA metrics in this comment
CSAT Pre-Relaunch vs Post-Relaunch
Satisfaction Chart Pre-Relaunch vs Post-Relaunch

**Comment by joanneesteban** [comment]
would you also be able to add this?
![image](https://user-images.githubusercontent.com/48964695/64438698-8f569a00-d096-11e9-8721-5347c628ba46.png)

one chart or multiple - whichever you think is best!

**Comment by amycesal** [comment]
Metrics for September: 
[Metrics_09.01.19.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3587881/Metrics_09.01.19.pdf)
[Metrics_09.01.19.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3587882/Metrics_09.01.19.pptx)

**Comment by joanneesteban** [comment]
Raw Data:
[Metrics for Modernized Data 9.01.19.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3591714/Metrics.for.Modernized.Data.9.01.19.xlsx)

**Comment by amycesal** [comment]
Updated:
[Metrics_09.01.19.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3592339/Metrics_09.01.19.pdf)
[Metrics_09.01.19.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3592343/Metrics_09.01.19.pptx)

**Comment by joanneesteban** [comment]
Lacey has the latest materials and sent it over to the stakeholders on VEO. Thank you @amycesal and @nedierecel for your work on this! Closing this out.
