### ISSUE TITLE
Edit International address (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15059]
## User story

As a user, I want the ability to edit my International addresses directly through the app.

### Acceptance Criteria

1. When a user selects anything other than the United States from the Country picklist, update the following fields:
     - State: Update the hint text to “State” (it is not a required field when it’s an international address)
     - Zip code: Update this field so it displays as “International post code”
2. When the user taps into the State field after a non-US country is selected, this will open the default QWERTY keyboard. 
     - Note: this differs from the U.S.A-driven State field, which opens a picklist. 

## Designs:

- None specific to International address. U.S. Address for reference: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432053040
- See comments below for screenshot of the International Address UI from the va.gov web app

## Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark page title as Header 1 (e.g. “Mailing Address”)
- Cancel button in top left
     - accessibilityLabel = "cancel"
     - accessibilityHint= “Go back to Profile options”
     - accessibilityRole = “button”
- Save button in top right
     - accessibilityLabel= “Save”
     - accessibilityHint= “Saves changes”
     - accessibilityRole= “button”
     - accessibilityState= Denote when disabled vs. enabled
- Mark all fields as text input
     - Include necessary props 
     - Denote if filled vs. unfilled
     - If unfilled, denote placeholder text
     - Denote requiredness 
- If an error occurs, announce error and provide suggestion

## Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
![intl address from va.gov web app.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ddd0dd29-1f4a-4d87-ae90-7b8e52cc64e6)

**Comment by bessgreen** [comment]
@bridgethapner a few questions about International addresses: 

1. Is the “State” field (i.e. State/Province/Region) optional? It appears so based on the screenshot from the web app.
2. Will the user need to type in the State with the QWERTY keyboard? Or is there a list of possible fields that would be driven from the selected country, so the user could then choose the State from a native dropdown?

cc: @lexicalninja @kreek

**Comment by lexicalninja** [comment]
State is optional for international addresses.
For State, if they are filling an international address they would need to fill it in with a keyboard. 
For United States and Military Bases there should be a dropdown list of states/territories

**Comment by lexicalninja** [comment]
![image](https://user-images.githubusercontent.com/7376126/96730765-29050780-137c-11eb-8f79-48aa3d370812.png)


![image](https://user-images.githubusercontent.com/7376126/96730663-0e329300-137c-11eb-9c76-72880c558f37.png)

![image](https://user-images.githubusercontent.com/7376126/96730719-1be81880-137c-11eb-981a-82b8fb908941.png)

**Comment by bridgethapner** [comment]
Thank you for jumping in @lexicalninja! I agree that the AC here looks right - for int'l addresses, the state field is optional & is a freeform text field, not a picker.

**Comment by digitalken** [comment]
Testing:

1. Verify user is able to edit international address through app.
2. Verify that when user selects anything other than the United States from the country picklist:
  a. Updates hint text to "State" and it is not a required field.
  b. Updates zip code to display as "International post code".
3. Verify when user taps into State field after non-US country is selected, it opens a QWERTY keyboard rather than a picklist for US states.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
Functionality passes on Android and iOS. UI passes on Android but fails on iOS. Accessibility does not pass with multi-issue accessibility bug entered. Moving this to Design QA for review

[iOS UI Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16436)

[Accessibility Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16395)
