### ISSUE TITLE
CT: Update CSS of controls

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15054]
As a developer, I need to update the spacing/styling of some of the controls so that the page flows better.

## Assumptions:
1. We do not need a feature or prod flag for this work. Because of this, QA will work with UX to review changes before they're merged. 
2. This issue does need to be reviewed by UX before it can be closed.

## Acceptance Criteria
1. The 'Exclude results with warnings or closings' checkbox is aligned with the other controls in the left panel.
2. The 'programs' margin is 24 px.

## Supporting Artifacts:
1. Adjust alignment of 'Exclude results with warnings or closings' checkbox 
![3.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/31b5ba25-d7cc-4a71-93cf-e5fc4d78bbe7)
2. Update 'programs' margin  from 16 px to 24 px to match
![4.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/c08eaad8-f166-43e0-a8a7-b699155764ff)

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/14863

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
TestRail test case:
https://dsvavsp.testrail.io/index.php?/runs/view/747&group_by=cases:section_id&group_order=asc

**Comment by delli-gatti-michael** [comment]
Changes are live. Closing this issue
