### ISSUE TITLE
Edit Military Base address (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15058]
## User story

As a user, I want the ability to edit my Military Base addresses directly through the app.

## Acceptance Criteria

1. On the edit Address page, include an "I live on a United States military base outside of the United States" checkbox. When this checkbox is selected, AC #2, 3, & 4 below apply. 
2. The City form field changes to an APO/FPO/DPO native dropdown. When this field is selected, user is able to select 1 of the 3 options:
     - APO
     - FPO
     - DPO
3. The State form field updates to a native dropdown with the following 3 options: 
     - Armed Forces Americas (AA)
     - Armed Forces Europe (AE)
     - Armed Forces Pacific (AP)
4. Zip code field persists
5. The Country field should be disabled
     - In this disabled state, the Country should be set to United States

## Designs:
Unchecked military base: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432053040
Checked military base with APO/FPO/DPO field: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431899953 
![2e759b7d-d572-4d0d-b387-9de50bc543a8.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9e3f5dec-d3de-41d9-b698-592d9e9f00c8)

## Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Checkbox
     - accessibilityLabel= “I live on a United States military base outside of the United States”
     - accessibilityHint= "Confirms you live on a base outside of the United States"
     - accessibilityRole= “checkbox”
     - accessibilityState= Denote when checked vs. unchecked
- Mark all fields as text input
     - Include necessary props 
     - Denote if filled vs. unfilled
     - If unfilled, denote placeholder text
     - Denote requiredness 
- If an error occurs, announce error and provide suggestion

## Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bridgethapner** [comment]
Hi there @bessgreen -- thank you for checking in on this. I checked in with the VA.gov team that owns this and **yes** the field should be disabled, and it should also display "**United States**" as the country selection because military bases are considered within the United States. I am having access issues with my Craft/Invision today so cannot update the prototype at the moment, but here is a png showing field disabled and auto-set to **United States**: 

![Edit Mailing Address (Military Base).png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/2e759b7d-d572-4d0d-b387-9de50bc543a8)

**Comment by digitalken** [comment]
Testing:

1. Verify that Mailing Address edit page has a checkbox for "I live on a United States military base outside of the United States".
2. Verify that when user checks the box in #1, the following apply:
  a. The city form field changes to an APO/FPO/DPO native dropdown and user is able to select APO, FPO, or DPO.
  b. The state form field updates to a native dropdown with the following:  
    i. Armed Forces Americas (AA)
    ii. Armed Forces Europe (AE)
    iii. Armed Forces Pacific (AP)
3. Verify zipcode field persists.
4. Verify the country field is disabled and that Country is now to set United States.

**Comment by digitalken** [comment]
Added to TestRail

**Comment by esther-k** [comment]
Functionality passes on Android and iOS. UI passes on Android but fails on iOS. Accessibility does not pass with multi-issue accessibility bug entered. Moving this to Design QA for review

[iOS UI Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16436)

[Accessibility Bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16395)
