### ISSUE TITLE
Contact VA page - Touchpoint size issues for phone number buttons

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#15063]
## What happened?
Touchpoint sizes (minimum 44px by 44px) are not met by phone number links.  They are too short.
The Back button is covered in a previous bug.

## Specs:
- Android Pixel 3XL simulator
- Deque tool
- any user

## Steps to Reproduce
- Visit Contact VA page and run Deque testing tool.

## Desired behavior
Testing tool returns no errors for page.

## Acceptance Criteria
- All touch points are a minimum of 44px by 44px.

## Bug Severity
- 4 Low

## Linked Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14015

## Screen shot(s) and additional information

![contactVApage.gif](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/d102312e-f3fb-4764-973f-013554d3acb7)

**Comment by esther-k** [comment]
**11/24**

PASS- on Android (no method to test on iOS). Link touchpoints meet minimum 44px by 44px requirements on both Axe and Accessibility Scanner
