### ISSUE TITLE
Decision: Where to Host Storybook

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15068]
## Background
Documentation from [Storybook](https://storybook.js.org) will replace the [current component library documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design).

## Issue Description
Need to decide where to host our instance of Storybook. Options are:
- On the Gatsby site
- On a new site
- design.va.gov

---
## Tasks
- [ ] Talk to Kevin, the Service Design team, and the Content & IA team

## Acceptance Criteria
- [ ] Recommendation of where to host
---

**Comment by cvalarida** [comment]
@KevinMHoffmanUSDS expressed his preference in Slack to put the Storybook on design.va.gov. Currently, this is a Jekyll site, so we'll likely have to do some fancy footwork to make this happen. Should be doable, but it'll take some doing.

**Comment by cvalarida** [comment]
RFC: https://github.com/department-of-veterans-affairs/va.gov-team/pull/15824
