### ISSUE TITLE
Access for [Greg Bowman]

### ISSUE THREAD

**Issue by gpbowman-git** [department-of-veterans-affairs/va.gov-team#15065]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia LeeCecilia
- Please provide your name.
   > Greg Bowman
- Please Provide your email.
   > gregory.bowman@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Matsumoto, Software Engineer, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? 
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMJ6xjp3bq8lf9H2BwteIvBQyVbBlNAriMWlfX+sE2irQiAWg5CyB3Cm5+uQ7SwC5v00oAfwf/AvIRchToVuYraZvBTqBdOwBHsitefhTWkCFjk3ehwUtvA0567stla5vtvzL+w9dCeVpWA+vBaVBxfPKc8on6/2ie/w8bZ4vIWAAxMaeDTpDiEqsiYyKcwb62j0nBvODJtiwWoq70UFSFGlYbBuYSbYMSo+yPBJ6yH/Ugrm7t5Q5BtuKNXTS5NlJ+1JwOGpNv36zLIUO4IjP8BiaxC9YTECM5cdQTpZQfPISKGTiMchXVPuqiCfG2RmtWjFOp7EcnbMUckPHS06PXJByd3asXuW8Ts0UKWl+cKnhDqx+I2E31I9Md9Olox1m/0k/kLqPW2JOHK2CbWGtTfJOqMiFYSH+kAoFzHzbkLt5SLaI3nZE6gbzMAO9aC3hCfxPVOZc/mUVT0AY1ucAyF9PWQYi32BlQGu2U2LNYTQWB0AbSSIwdOTcEJJFYJBk= AzureAD+GregoryBowman@DESKTOP-ID8ISVV
```
- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house

**Comment by jsev-io** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
Name: Greg Bowman
COR: Cecilia LeeCecilia

**Comment by pshahVA** [comment]
Team is Lighthouse API's.

**Comment by jbritt1** [comment]
@gpbowman-git, were you able to establish a connection to the SOCKS proxy using the guide?

**Comment by Jeff-Hayter** [comment]
@tskinn @jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
Access granted and temporary credentials passed to user at this time.
