### ISSUE TITLE
Access for [Cris Shupp]

### ISSUE THREAD

**Issue by cshupp1** [department-of-veterans-affairs/va.gov-team#15064]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia LeeCecilia
- Please provide your name.
   > Cris Shupp
- Please Provide your email.
   > cristopher.shupp@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
> Team Name = Matsumoto   
> Company = Libertyits
> Role = Software Engineer

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9blARmk2p8fK/R6BfGMtYjP67gpHAWk/X/vo07YKNOzodTLeoVJ0Vek7nhdRbNsfOm9o7M0A+jXIx6BNSzvqWd1+lDPNsjCXuLev+AFRnNIzuvTmGtsWlsRzQDFdHpL6pjFMm5jZmYNnLv+/lHruJENKsZT86tjHmkivIFf2xnOQBKMcp0PjgZYWHlBre3e5lXtyhxOimDYqLIs5UKgoR1czVmg2LO4i1ustcA5nppz9leKZklwvfZVqeSUlniJnCCXBQ1foNCoCPpVuMFR91B2VG9E4jCLQLCTpbUiLBNRj+FPFNBketDNp22XztS8FBbr3inifXj0tVa28+3y5KpdfsbVgnQUrVQCu3mS8T9ptXmgaU9vOE4bQKA9v6+2rffcFVJC2KvxMXdjlpg6T+UpDQ9/tNbasiBDjqULrgSlf49tHzu6UNomrjsc/z+NErtYjfK9xcIZ1/kmPZBUEd3rP2Zw2RsBhak0CoYV1SIuNqP+dbqzBztQXk8cmUn+U= AzureAD+CristopherShupp@DESKTOP-1EFHNS6
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jsev-io** [comment]
@department-of-veterans-affairs/vsp-operations
