### ISSUE TITLE
Missing page H1 in breadcrumb

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15075]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

On this page https://www.va.gov/coronavirus-research/  the breadcrumb is missing the page title

Screenshot:
![image](https://user-images.githubusercontent.com/43381063/96636426-4938b600-12eb-11eb-992d-3aae57e64c37.png)

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

**The page title should appear in the breadcrumb like this:** 
`Home `> `Volunteer for coronavirus research at VA`

**Comment by jenniferlee-dsva** [comment]
fysa - This might be an issue that maybe might be resolved by making this a root level page in the CMS, like our coronavirus FAQs page. I notice that the FAQs page is a root level page (correctly), but this one, for whatever reason, when it was published, did not set the menu options the same way.

Example menu option settings for coronavirus faqs root page: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/5407405f-58dc-47d9-8d8b-19ab93394a4b)


@RLHecht  - FYSA: I  made this change in the CMS. Can you keep an eye on this with tomorrow's deployment and make sure it works as intended? If it doesn't resolve this breadcrumb bug, it may be a FE issue.

**Comment by RLHecht** [comment]
@jenniferlee-dsva This is still showing just the Home breadcrumb at the top after today's deploy. I guess it is a FE bug?

**Comment by jenniferlee-dsva** [comment]
It is showing properly on the live page now, so will close this ticket. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/3c537e58-0603-4512-aaaa-55d5f1aa2466)
