### ISSUE TITLE
[Design] Content Review for EDU Direct Deposit

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15078]
## Background
Now that the initial designs are completed for EDU Direct Deposit, we need to get some eyes on the copy to ensure it meets the standard before usability testing is conducted.

## Tasks
- Request a review from Peggy for the newly created designs for EDU Direct Deposit

## Acceptance Criteria 
- [x] A copy review has been requested for feedback

**Comment by sporeboy** [comment]
Working with Peggy to get a review of the DD-EDU feature: https://dsva.slack.com/archives/C909ZG2BB/p1603483524494600

**Comment by sporeboy** [comment]
Review feedback here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15518

**Comment by Samara-Strauss** [comment]
@sporeboy, sorry, forgot to ask — can we close this?

**Comment by sporeboy** [comment]
I think we can close this. In discussion w/ Peggy regarding who should handle the landing page content. Might all be PW's responsibility.
