### ISSUE TITLE
Common component: Styling for toggle switch

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15074]
## User story
As a user, I want a toggle switch throughout the app so I can easily turn certain features on or off. 

## Acceptance Criteria

1. Create toggle button with UI/UX styling
     - OFF state (light grey background, white circle on the left)
     - ON state (blue background, white circle on the right)
2. Maintain consistent styling across iOS & Android
3. Update the ReadMe with details for this Common Component

Note for dev: this button will appear on various pages throughout the app, including: Settings, Benefit Summary letter

## Design:
Examples of OFF & ON toggles: https://adhoc.invisionapp.com/d/main#/console/20546460/431636882/preview

## Dev checklist

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/24**

UI and functionality pass. Accessibility fails with a [bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16490) entered. Moving to Design QA
