### ISSUE TITLE
[DESIGN]: Should the primary action be on the left in modals with two action buttons?

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#15082]
## Issue Description
While auditing the Express Care feature, I noticed the cancel appointment modal has two actions. The primary "cancel" action is on the left and the secondary "close modal" action is on the right. Is this a typical design layout? I don't know but my initial impression was that these should be reversed. Adding VSP design for a judgment call. Screenshot attached below.

---
## Tasks
- [ ] Confirm the design is correct, or offer guidance on updates needed

## Acceptance Criteria
- [ ] Design will be updated **or** ticket closed with no work needed

---
<img width="796" alt="Screen Shot 2020-10-20 at 4 12 46 PM" src="https://user-images.githubusercontent.com/934879/96645074-aafb1f00-12ef-11eb-9af7-cf4a536b55b2.png">

**Comment by jbalboni** [comment]
@1Copenut I think we're following the pattern from the rest of the site:

![Screen Shot 2020-11-02 at 2.02.49 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/59ee3f98-aa0e-4427-a449-c6996fab9aec)

**Comment by 1Copenut** [comment]
@jbalboni Cool, I'm okay closing this ticket with that context. Thank you!
