### ISSUE TITLE
Support for multiple Appointment phone numbers in VAMC service locations

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#15092]
Some VAMC service locations have multiple appointment phone numbers, each with their own label.

We currently only display one, with no label.

See e.g. https://prod.cms.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/women-veteran-care.

![Women_Veteran_care_-_Pittsburgh_VA_Medical_Center-University_Drive___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/942fcf44-22e2-464c-996f-fc13bc98fa21)

## Acceptance Criteria
- [ ] **All** appointment phone numbers are displayed, with a label, instead of just one.
- [ ] Both graphql queries and Transformers have been updated to handle the necessary data structure changes

**Comment by mmiddaugh** [comment]
This issue has been resolved. Two phone numbers appear in Staging.
