### ISSUE TITLE
Unauthorized Home screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15099]
## User Story
As a user, I want a home page before I've signed in that gives me the following navigation options:
- Sign in
- Veterans Crisis Line
- Find a VA location

## Acceptance Criteria
1. Styling and UI matches the design
     - VA.gov logo placement is higher than on the splash screen that precedes it
2. UI for Sign in button (navigation is a separate story)
3. Find a VA Location button
     - Create UI
     - Hook up navigation. Selecting this button opens the in-app web view of facility locator (should already be done per [#14163](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14163))
4. Veteran Crisis Line banner (requirements TBD. Opens out-of-app?)

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432863239/preview#project_console

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Mark "Veterans Affairs Mobile - U.S. Department of Veterans Affairs" as Header 1
- Veterans Crisis Line
     - Title = “Talk to the Veterans Crisis Line now”
     - accessibilityHint = “Go to Veterans Crisis Line”
     - accessibilityRole = “button”
- Sign In
     - Title= "sign in"
     - accessibilityHint= “Navigates to the VA mobile site"
     - accessibilityRole= "button"
- Find a VA Location 
     - Title= “Find a VA location”
     - accessibilityHint= “Takes you to the VA Facility Locator page”
     - accessibilityRole= “link”

## Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bridgethapner** [comment]
Hi @bessgreen - As a heads up I just completed #17247 to add a Mobile Alert CC to this screen to signify our app is an internal release. Not sure if you want to roll that into here or handle it in a separate story, but wanted to flag.
