### ISSUE TITLE
Allow prefill to update hidden form fields

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#15093]
### Description

Some form fields can be configured to conditionally render based previously entered form data. Save-in-progress enabled forms have the ability to prefill form data, but at the moment this data is being removed if the field is configured to be hidden.

### Goal

If data has been saved previously for a form, we don't want it to be filtered out when an in-progress form is resumed and the data is prefilled.

### Additional details/notes/links

- [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1603218072278000)

### Acceptance criteria

- [ ] Prefill data populates to fields even if they are hidden

### Point(s) of contact

_Who should be kept INFORMED of the status of this request? Please tag them here._

### What type of issue is this? 
- [x] Bug
- [ ] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
