### ISSUE TITLE
VSP content feedback - staging review- HLR form 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#15096]
## User story
This ticket captures VSP content feedback for Higher-Level Review form. 

prototype link: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/435782598

## Acceptance criteria
 - [x] VSP/Peggy provides content feedback and recommendations for the form/tool.
- [ ]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [ ]  Product team leaves any comments about feedback they decide not to take
- [ ] Peggy checks form after content feedback has been incorporated

**Comment by peggygannon** [comment]
@kevinstachura  here are my content recommendations for the HLR Prototype. I've also dropped these into the prototype as comments. 

Updated content for: 

Subway map page
H2: What’s a Higher-Level Review? 
If you or your representative disagree with VA’s decision on your claim, you can request a Higher-Level Review. With a Higher-Level Review, a senior reviewer will take a new look at your case and the evidence you already provided. The reviewer will decide whether the decision can be changed based on a difference of opinion or an error.

H2: You can’t provide new evidence with a Higher-Level Review
The senior reviewer will only review the evidence you already provided. If you have new and relevant evidence, you can file [a Supplemental Claim]( https://www.va.gov/decision-reviews/supplemental-claim/)

Under Prepare step: 
I don't think we need this content here if we have the paragraph above "You can't submit new evidence"

-----

"You have no issues" alert

**We don't have any issues on file for you that are eligible for a Higher-Level Review ** 
If you think this is an error, please call us at 800-827-1000. We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.
Why isn’t my issue eligible? 

Your issue may not be eligible if: 
*We made the decision over a year ago. You have 1 year from the date on your decision letter to request a Higher-Level Review. **Note:** If you aren’t able to request a timely review due to COVID-19, we may grant you a deadline extension. To request an extension, fill out and submit VA Form 20-0996, with a note attached that you’re requesting an extension due to COVID-19.
*Your issue is for a benefit type other than compensation or pension. To request a Higher-Level Review for another benefit type, you'll need to fill out VA Form 20-0996 and submit it by mail, fax, or in person. 
*The issue or decision isn’t our system yet. You'll need to fill VA Form 20-0996 and submit it by mail, fax, or in person. 
** You and another surviving dependent of the Veteran are applying for the same benefit. And by law, only 1 of you can receive that benefit. You’ll need to [appeal to the Board of Veterans’ Appeals](https://www.va.gov/decision-reviews/board-appeal/)
**You’re requesting a review of a Board of Veterans’ Appeals decision. Refer to the Board’s decision notice for your options. 
**You’re requesting a review of a Higher-Level Review decision. You’ll need to either file a Supplemental Claim or appeal to the Board of Veterans’ Appeals. 

[Download VA Form 20-0996 (PDF)] (https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf)

To learn more about how COVID-19 affect claims or appeals, please visit our [Coronavirus FAQ page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#more-benefit-and-claim-questio).


--------

Updated content for following alerts:

**I would like to have different office do this review.**
You can request that an office different from the one that issued your prior decision do the Higher-Level Review.


We'll call you first to schedule the informal conference. Please choose up to two time periods when it's best to call you.

**We'll make two attempts to call you**
If no one answers, we'll leave a voice mail and a number for you to return the call. If we aren't able to leave a voice mail or get in touch with you after two attempts, we'll proceed with the Higher-Level Review.

**We'll make two attempts to call your representative**
If no one answers, we'll leave a voice mail and a number for them to return the call. If we aren't able to leave a voice mail or get in touch with them after two attempts, we'll proceed with the Higher-Level Review.

**Comment by Mottie** [comment]
Hi Peggy! I've just updated "most" of the content. I didn't touch the "may not be eligible" additional info content since that is still being separately reviewed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/16211

**Comment by peggygannon** [comment]
Closing this issue, as content feedback is now being tracked in this ticket:  

https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/16210
