### ISSUE TITLE
Address validation (FE)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15097]
## User Story
As a user, I want to know when the address I've entered is invalid. 

## Acceptance Criteria

1. On the Address edit page, the Save button becomes actionable (and turns white) when the following is true:
     - All fields on the screen marked "required" contain an entry
2. The Save button is disabled when any "required" field is null

## Designs
Edit address: https://adhoc.invisionapp.com/d/main#/console/20546460/431899953/preview

## Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
@bridgethapner Is there character limit for the address fields? (The screenshot you attached from the web app indicates max 35 characters). If so, are we displaying this to the user in any way, or will this be covered later w/ error messages?

**Comment by bridgethapner** [comment]
Hi there @bessgreen Yes each of the three address fields has a 35 character limit. This character limit is noted in the content spreadsheet & it applies to all address types. For now, we won't display this to the user. I'll create a separate story for this for the backlog.

**Comment by bessgreen** [comment]
@bridgethapner thanks for confirming, I must've missed that in the content doc! I added that as AC in [#13893](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13893).  

Also, do you mind double checking that the AC in this story meets the "basic validation" criteria? (original thread about basic validation in the comments section of [#13893](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13893)) 

cc: @srmyers17

**Comment by digitalken** [comment]
Testing:

1. Verify on the Address page that the Save button becomes active (turns white) when all fields on the screen marked "required contain an entry.
2. Verify the save button is disabled as long as any "required" field is blank.

**Comment by digitalken** [comment]
Test case added to TestRail.

**Comment by esther-k** [comment]
**11/19** 

PASS - on iOS and Android. Moving to design QA
