### ISSUE TITLE
[Bug] Disability Compensation-Veteran Application Submit Issue

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#15104]
## What happened?

Reported by Andrea Downs/VBA VACO

OSVA sent over a request for help with what looks like one Vet submitting a compensation claim through va.gov. OSVA is working with the Dep Sec office to get additional information, but are you tracking issues with service outages related to va.gov and ability to submit a claim (see screen shot):

![image](https://user-images.githubusercontent.com/63107147/96724518-eb08e300-137d-11eb-84e7-4bfb67196258.png)

The individual captured the sequence of screen shots on the attached Word document.

They report they used both eBenefits and MyhealtheVet to login. 

https://www.va.gov/
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction

We don’t know every time the error occurred, but believe the individual tried a few weeks ago, yesterday, and this morning, as they provided the screenshots to recreate the path.

[Screenshot VA Website.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5416094/Screenshot.VA.Website.docx)

 
## Specs:
- Device: Unknown
- Browser: Unknown
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: 
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] User should not encounter issues when submitting disability application.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by leahkeeler** [comment]
I think this should be closed - it's almost 2 years old unless you can replicate

**Comment by alsleaders** [comment]
I'm closing this because I believe we know about all the various errors that might be causing 526 submission failures and we are working on work arounds for them.
