### ISSUE TITLE
Migrate formation-react to the new Storybook repo

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15107]
## Issue Description
Migrate existing `formation-react` code over to the Storybook repo. 

---
## Tasks
- [ ] Migration of the code

## Acceptance Criteria
- [ ] Current existing components will be in the Storybook repo

**Comment by cvalarida** [comment]
We added storybook to the existing component library, so this is obsolete.

**Comment by cvalarida** [comment]
Actually, I take it back. I'm re-purposing this ticket for migrating the whole `formation-react` package code to the new repo, rather than just the components.
