### ISSUE TITLE
Audit and provide recommendations for remaining /healthbenefits/ pages

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#1510]
VHA stakeholders provided a list of approx 100 pages that live on www.va.gov/healthbenefits, which is served from Team Site.  

- [x] Audit/review these pages and determine if they should there is any additional rewriting or parity work needed
- [ ] ~If rewriting/writing a new page is required, determine the IA and page structure recommendations~
- [x] Send recommendations to stakeholders for review and feedback
- [ ] ~Implement redirects as needed based parity and rewriting~

**Comment by mnorthuis** [comment]
@lwalsh617 This issue just documents the audit you are doing of that giant list of pages.  You are welcome to post your findings/recommendations here.

**Comment by Karak888** [comment]
@lwalsh617 can you please let me know if this will be finished by tomorrow EOD?  working on sprint report for sprint 5 which is due tomorrow EOD.  If you do not think that you will be finished tomorrow, please let myself and @jenniferlee-dsva know.  Thanks!

**Comment by Karak888** [comment]
This was sent to Mikki for validation and will then close.

**Comment by Karak888** [comment]
@lwalsh617 @mnorthuis @jenniferlee-dsva - have the recommendations been posted somewhere outside of this ticket?  There is a good chance I may have missed it here, thanks!

**Comment by lwalsh617** [comment]
@Karak888 @mnorthuis @jenniferlee-dsva - The recommendations are in the "Notes" column of the Word doc.

**Comment by Karak888** [comment]
thanks @lwalsh617 Moving to close this, thanks!

**Comment by mnorthuis** [comment]
Still need to clearly identify for stakeholders which pages we are recommending for rewriting/parity work. 

Once that is complete we will send this to stakeholders for review.  Removing tasks pertaining to any IA/content strategy work from this issue, that will be handled separately based on stakeholder feedback and preferred direction.

**Comment by Karak888** [comment]
@lwalsh work is finishing up with #1510, when this is done can we move #2051 redirect work to the ready column? @mnorthuis

**Comment by mnorthuis** [comment]
Sent doc to Jen Lee on 10/18 for communication to stakeholders. Closing this issue. 

[LegacyLeftNavRecs-VHA-10182019.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3745211/LegacyLeftNavRecs-VHA-10182019.docx)
