### ISSUE TITLE
[DESIGN]: Definition lists are not spaced evenly in IE11

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#15103]
## Issue Description
UPDATE: I added a second IE screenshot, and outlined the column widths. It looks like Chrome and modern browsers are setting the columns to even width implicitly, but IE11 needs an explicit width (percentage?) to make the columns balance in width.

While auditing the Express Care feature, I noticed the definition lists aren't spaced evenly in IE11. The screenshot attached isn't from IE, but is meant as an example of the definition lists that are unbalanced. I believe setting a width on the lists or containing divs should resolve the issue.

---
## Tasks
- [ ] Adjust the CSS so definition lists are spaced evenly in IE11

## Acceptance Criteria
- [ ] Design will be updated **or** ticket closed with no work done if the team doesn't feel this is an item that needs updated.

---
### Chrome screenshot
![Screen Shot 2020-10-20 at 9 15 44 AM](https://user-images.githubusercontent.com/934879/96668996-fa5a4300-1321-11eb-9c5f-a5c9fc9f3e78.png)

---
### IE screenshot
![Screenshot (58)](https://user-images.githubusercontent.com/934879/98115774-f58ea680-1e6c-11eb-9550-664a71bfe08a.png)

**Comment by jbalboni** [comment]
@1Copenut Can you clarify what you're saying is unbalanced? I'm not understanding from the screenshot and the description.

**Comment by 1Copenut** [comment]
@jbalboni I added a second screen shot for clarity, direct from IE 11.

**Comment by jbalboni** [comment]
I'm currently unable to reproduce this on my own, working with @1Copenut to see if we can figure out what's going on.

**Comment by 1Copenut** [comment]
@jbalboni Well, either I logged an issue that wasn't or it has been corrected. Either way, not seeing any visual difference in IE and Chrome on Win10, so I'll move this one to close.
