### ISSUE TITLE
Start a new Storybook repo

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15106]
## Issue Description
A new repo will be needed for Storybook in order to migrate components into Storybook system. 

---
## Tasks
- [ ] Setup a new repo

## Acceptance Criteria
- [ ] There is a Storybook repo
---

**Comment by cvalarida** [comment]
@bkjohnson created https://github.com/department-of-veterans-affairs/component-library, but can't make it public.

**Comment by k80bowman** [comment]
@caw310 do you have any context on this? Is it still necessary or can we close it?

**Comment by caw310** [comment]
@k80bowman I don't have context. 
@bkjohnson , can you provide background?

**Comment by bkjohnson** [comment]
I think we can close. Storybook is now a [private package in the `component-library` monorepo](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages/storybook)
