### ISSUE TITLE
CT: Modal scrollbar showing on PC Chrome/Firefox/Edge

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#15111]
When selecting "Will you be taking any classes in person? (Learn more)" on the landing page https://staging.va.gov/gi-bill-comparison-tool the scroll bar appears in the modal pushing over the "X" out of its position. 

Observe the screenshot

Expected results: We need the left image to appear like the right image
![scrollbar.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9e7cbfd2-ab4c-4b83-93d6-06a993cada06)

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/14659

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-10-21 at 2.41.49 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/014bee0a-0baa-4b36-8ba6-968300b809df)

**Comment by sonntag-adam** [comment]
This is fixed and shows correctly in windows in all browsers. Closing bug.
