### ISSUE TITLE
Discovery for 10-10CG Scheduled Downtime Implimentation

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#15113]
As a user I would like to know when a form or external service for the form is scheduled for maintenance this way I do not waste my time filling out information just to get a 5XX. As a developer I also want to reduce errors due to scheduled maintenance.

Run some discovery so we can get implementation details on how to wire up CARMA to the [DevOps Config](https://github.com/department-of-veterans-affairs/devops/blob/a4b5432061ae60a4f77952bbe5f668a1355ee007/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L232). The two services the 10-10CG uses are MVI and CARMA. MVI is already ready to use we need to figure out the steps to add a new service to pager duty and make it consumable like the other services.

**Comment by LinnJS** [comment]
[Frontend Discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14767)

**Comment by LinnJS** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14585) with FE implementation

**Comment by kevinmirc** [comment]
Discovery summarized in original (Frontend) issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14767#issuecomment-721363558
