### ISSUE TITLE
 Remove the formation-react NPM package

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15110]
## Issue Description
 Remove the formation-react NPM package (if possible)

---
## Tasks
- [ ] Removal of the formation-react NPM package 

## Acceptance Criteria
- [ ] formation-react NPM package has been removed without doing any harm
---

**Comment by cvalarida** [comment]
Potentially, we'll only be able to deprecate it, which is also fine.

**Comment by bkjohnson** [comment]
Closing this since it has been deprecated, and we have another issue about actually deleting it from the tools repo: #17255
