### ISSUE TITLE
Accessibility feedback - Design intent collaboration - BAM2 [

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#15123]
**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Point of Contact

**VFS Point of Contact:** 

- VSA - Jennifer
- VSP - Trevor 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

#### Must

1. As the team learns more about how the documents are stored, it will be good to identify the format of the document. 
    - We **must** ensure the documents are 508-compliant, so it is important to know who owns the responsibility for that. If there is a base PDF, for example, it must be 508-compliant before content is appended, so that the final PDF will be compliant. 
    - The team **should** discover who is responsible for ensuring the base form is compliant as soon as possible. We may want to make the VA 508 Office aware, so they can reach out to support the business unit.

#### Should

2. Some of these interaction patterns become quite complex, the team **should** schedule a collaboration session with the VSA accessibility session as ideas evolve. 

#### Consider

> At this time, we do not know how (or if) the paper forms are processed, if they are entered into any BE system and how they trigger a backend process - this will be part of discovery and iterative approach to implement the solution.

1. Regarding this ☝️  statement from the product outline, **consider** asking the VSO contacts about this. During Caregiver Discovery, the DAV representative shared a lot of information about the current mail centers and online application processes.

2. Ahead of usability testing of the designs, **consider** prioritizing participants with disabilities and low-income to identify any cognitive challenges. 

[cc @1Copenut — for review of the above, and to add VSP feedback in the area below]

### VSP feedback
Trevor (VSP) agrees with Jennifer's feedback above. I have just two items to add below.

#### Should
* Provide language explaining why information is being collected, where possible and appropriate. Rebecca did a fantastic job explaining why automobiles are asked as part of the process. This type of information will be important to help veterans feel comfortable and answer honestly.

#### Consider
* The VA Combined disability rating calculator ( https://staging.va.gov/disability/about-disability-ratings/ ) has a very similar feel to some of the add-one inputs your team showed today for automobiles, real estate, bank accounts, etc. It was built over several iterations and vetted with the VA 508 office for good usability.

**Comment by 1Copenut** [comment]
@jenstrickland I added my feedback, two small items. We are 💯

**Comment by rileyorr** [comment]
Thank you for the feedback, @jenstrickland & @1Copenut! 

> We must ensure the documents are 508-compliant, so it is important to know who owns the responsibility for that. If there is a base PDF, for example, it must be 508-compliant before content is appended, so that the final PDF will be compliant.

Absolutely! My understanding is that we will be sending the user's form data to the DMC via a JSON file. The DMC will then populate the PDF on their end. @camerontesterman can you confirm that this is still the submission process we're following? 

> Some of these interaction patterns become quite complex, the team should schedule a collaboration session with the VSA accessibility session as ideas evolve.

I'd like some more information about the accessibility collaborations! Do you have available slots marked off on your calendar for these sessions? Also, what's the format for these sessions? Does our team present the problem and current design solution and we work together to incorporate accessibility? 

> At this time, we do not know how (or if) the paper forms are processed, if they are entered into any BE system and how they trigger a backend process - this will be part of discovery and iterative approach to implement the solution.

Ah, looks like our product outline needs to be updated @leahkeeler. DMC's backend system is called Pega! I've heard that they're transitioning to a new backend system, though. 

> The VA Combined disability rating calculator ( https://staging.va.gov/disability/about-disability-ratings/ ) has a very similar feel to some of the add-one inputs your team showed today for automobiles, real estate, bank accounts, etc.

Thank you for this reference! I'll take a look at this component and research how feasible this is to build within the form system's schema.

**Comment by jenstrickland** [comment]
> > We must ensure the documents are 508-compliant, so it is important to know who owns the responsibility for that. If there is a base PDF, for example, it must be 508-compliant before content is appended, so that the final PDF will be compliant.

> Absolutely! My understanding is that we will be sending the user's form data to the DMC via a JSON file. The DMC will then populate the PDF on their end. @camerontesterman can you confirm that this is still the submission process we're following?

The DMC will need to ensure their PDFs are 508-compliant, so if y'all can make sure they know that, and they know who to contact in the VA 508 Program Office that would be great.

**Comment by jenstrickland** [comment]
> > Some of these interaction patterns become quite complex, the team should schedule a collaboration session with the VSA accessibility session as ideas evolve.

> I'd like some more information about the accessibility collaborations! Do you have available slots marked off on your calendar for these sessions? Also, what's the format for these sessions? Does our team present the problem and current design solution and we work together to incorporate accessibility?

Time slots: I don't currently have slots set aside for these sessions, but I do love the idea. We initially wanted to have VSA accessibility office hours but got the 👎 . However, it looks like a potentially welcome idea, now. 🎉   We'll keep you posted as things evolve on that. Otherwise, what others do is just put time on my calendar. 

Format: Designers usually show their work in progress, and we chat about it. Ryan Thurwell schedules collaboration sessions, and he shows what he's thinking, then I identify any potential issues, and we work on it. He holds control of the Sketch file. Liz uses screenshots of her designs, puts them into a Mural, we chat through them either async or on a call, and she takes notes. Then we might meet again. Ryan's approach takes less time than Liz's.
