### ISSUE TITLE
Analytics Implementation - User Custom Dimension - CMS Team

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#15121]
# Google Analytics Implementation or QA Request

## Description
- Team wants to HAVE a user role custom dimension to segment their GA data according to CMS user role

### Proposed Steps
- We will first want to understand the various user roles in Drupal 
- Develop a datalayer taxonomy to collect that user role 
- Configure user scope custom dimension identifying this user role

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3223#

**Comment by jonwehausen** [comment]
Hi @oksana-c , 

I wanted to loop you for a few updates as a follow-up to our midweek conversation: 
- You can find our original CMS implementation ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5673) detailing the current data layer configuration for Drupal. 
- You should have received an invite to your oksana.cyrwus@agile6.com email with "Approve" GTM access, this will allow you to make config changes and create new versions but not publish -- as our team will publish following QA. 
- Let's setup a conversation to learn more about how we might go about tackling your interest in onboarding a session recording product 

As for this request, we would propose a simple dataLayer push post-login to capture the users' role, here is what we have as a list for possible roles: 
```
'anonymous',
'authenticated',
'content_api_consumer',
'content_editor',
'content_admin',
'content_creator_benefits_hubs',
'content_creator_resources_and_support',
'content_reviewer',
'content_publisher',
'admnistrator_users',
'administrator',
'vamc_content_creator',
```
**We would like to get your clarification on ones we may be missing and/or if there is additional metadata you would like to collect here around users apart from just role. Here is what we propose post-login:** 

```javascript
window.dataLayer.push({
   'event': 'login',
   'user_role': //populate with user role from above   
});
```

Thanks and we look forward to hearing from you. 


cc: @oksana-c @kevwalsh @ndouglas @joanneesteban

**Comment by ndouglas** [comment]
My understanding of #3223 is that we should provide user roles to GTM on each page load event.  What is the benefit of pushing a separate login event over including the user role(s) in the `pageLoad` event?

I'm just a bit confused, so I want to be sure I'm understanding the goal and affected systems, intents and purposes, etc correctly.

Also, users always have multiple roles in Drupal.  At least one of these (`authenticated`) is going to be redundant for our purposes, I think, but I'm not sure if there are any other cases where more than one role per user might matter and should appear in reports/dashboards/etc.  I can pass only the most significant role, but of course that inevitably results in some data loss.  Of course, GA is not friendly to multi-valued fields, so we'll suffer either way.

Thanks!

**Comment by jonwehausen** [comment]
Hi @ndouglas , 

Thank you for clarifying users can and will have multiple roles. 

Great question -- We could certainly push with each `pageLoad` event (and we can certainly go with this route if preferred from a development perspective), however for your awareness the reason for recommending a central `login` event is it corresponds with paradigm / industry shifts to [Google Analytics 4 taxonomy](https://support.google.com/analytics/answer/9267735?hl=en&ref_topic=9756175). 

This is a shift that is inevitably coming so we are beginning to recommend implementations around this transition where feasible...Once in the data layer, we can map values of `user_role` to user properties or in universal analytics user scoped custom dimensions.

Also you are correct GA doesn't handle multi-valued fields well -- the closest thing we can get to is a concatenated string of all of the user roles. For implementation, I would recommend passing all user roles as an array and our team can determine best how we will ingest into GA thru GTM. 

Let us know any further questions you may have. Thanks again.

**Comment by ndouglas** [comment]
>however for your awareness the reason for recommending a central login event is it corresponds with paradigm / industry shifts to Google Analytics 4 taxonomy.

Aha!  That's the bit I was missing.  Thank you very much!

>For implementation, I would recommend passing all user roles as an array and our team can determine best how we will ingest into GA thru GTM.

Makes sense.  Thanks again!

**Comment by oksana-c** [comment]
hi @jonwehausen , thank you for the follow-up and additional info.

I confirm I have access to GTM container VA.gov Internal Drupal CMS (create new versions but not publish). Thank you.
However, I won't be able to utilize proposed edit/QA/publish workflow without being able to create Custom Definitions (dimensions/metrics) in GA.

---

### User scope dimensions

#### User role

I can confirm that the list of roles you collected is correct and agree w/ @ndouglas in that the `authenticated` role is redundant, so we wouldn't send it in the concatenated string.

Re: GTM event: `login` event will be less relevant for us, since we also want to track `anonymous` role, which doesn't require login. So I'd agree w/ @ndouglas  on `pageView` event here.

---

#### User ID

Thank you for asking about additional user info to collect.

We would love to track User ID as one of the User Scope dimensions for the CMS application. This will require enabling User ID tracking in GA and sending User ID in GTM dataLayer.

I've successfully tracked User ID via pageView event in the past, but open to recommendations here.

Here's some Drupal-specific info around User IDs.
Drupal assigns a unique User ID to each user which then, if included in GA reports, can be traced back to a specific person in the CMS. The CMS wants to prevent the exposure of any identifiable user data, so we agreed on the encryption method for tracking User ID which will prevent traceability back to a specific person. We plan on sending a hash of Drupal user id instead of sending the id directly. This way we are still able to group sessions by unique users, but also preventing traceable information from ending up in GA reports. 

---

### Session recording product

We are reviewing some options internally and I will reach out once we have solid candidates to propose. We greatly appreciate your openness to explore options with us.

**Comment by jonwehausen** [comment]
Hi @oksana-c , 

### GA Custom Dimension Access
- Thanks for the notice there, I have increased your privileges within GA from "Collaborate" to "Edit" for the CMS GA property, this should allow you to create custom dimensions
------------------------------------------------------------

### User Role
- Your point here makes sense @oksana-c to allow for us to track `anonymous` role as well
- Now knowing this -- I would agree and recommend we push as part of each `pageView` event
- I personally would recommend pushing all roles for the user to the dataLayer (i.e `userRoles`) as an array simply for the sake of having all of the data available to us now and in the future, and then we can scrub / filter out roles in GTM as needed. 
- Unless you all have a few significant roles that can serve as our primary role identification

### User Id Tracking
- Thanks very much for your thoughts here -- makes sense, agree let's move forward with pushing the hashed Drupal user ID as part of each `pageView` event
- We will need to perform the steps [here](https://analytics.google.com/analytics/web/#/a50123418w196569434p211458524/admin/tracking/user-id/) and can also enable the user ID view. Happy to do this for you or leave up to you 

------------------------------------------------------------

### Session Recording
- Awesome! Look forward to hearing / collaborating more on this effort.

**Comment by oksana-c** [comment]
@jonwehausen , we've deployed the User Role dimension work on the CMS side and I updated the GTM container w/ appropriate variables. 
The GTM container for VA.gov Internal Drupal CMS - Version 7 is ready for QA.

Pasting screenshots below that indicate changes made in GA and GTM made changes:

GA user role dimension:
<img width="1656" alt="Screen Shot 2020-11-18 at 7 57 00 AM" src="https://user-images.githubusercontent.com/16477724/99729683-80c88880-2a78-11eb-9356-04b2c3f65623.png">

GMT - new variable 
<img width="1095" alt="Screen Shot 2020-11-19 at 3 12 42 PM" src="https://user-images.githubusercontent.com/16477724/99730445-b15cf200-2a79-11eb-9dc9-bca46bfdcb45.png">


GTM - updated GA Settings variable
<img width="1184" alt="Screen Shot 2020-11-18 at 7 57 21 AM" src="https://user-images.githubusercontent.com/16477724/99730115-27148e00-2a79-11eb-9b74-e841285a47ba.png">

GTM Preview
Updated container preview shows correct roles for me when tested on prod URL https://prod.cms.va.gov
<img width="817" alt="Screen Shot 2020-11-19 at 3 09 38 PM" src="https://user-images.githubusercontent.com/16477724/99730275-6642df00-2a79-11eb-9f9d-13b77884ea93.png">

Thank you!

**Comment by oksana-c** [comment]
👋 @jonwehausen , checking in to see if you need any more information from us to promote CMS GTM container Version 7 to Live.

**Comment by oksana-c** [comment]
good morning @jonwehausen, 

I'll try to kill two birds w/ this one open issue. 
We started this thread w/ an ask to add User Role dimension and in the meantime also added User ID dimension to GA and GTM container.

QA steps to complete prior to releasing GTM container Version 8 Live:

- [ ] confirm `CMS Prod - User ID` view exists for `Va.gov CMS Backend` property in GA
- [ ] confirm `User ID` and `User Role` dimensions exists( [link](https://analytics.google.com/analytics/web/#/a50123418w196569434p233599643/admin/custom-dimensions/m-content-dimensionsContent.rowShow=10&m-content-dimensionsContent.rowStart=0&m-content-dimensionsContent.sortColumnId=index&m-content-dimensionsContent.sortDescending=false&m-content.mode=LIST) )
- [ ] launch GTM Preview for `VA.gov Internal Drupal CMS` account using Prod URL while logged in https://prod.cms.va.gov/ 
- [ ] confirm you see `User Id` and `userRole` variable values set as shown on the screenshot below.
   - [ ] For user `jonathan.wehausen@va.gov`, you should see the following roles set `["authenticated","vamc_content_creator","content_editor"]` and a hash string set for `userId` that is different from what is shown on my screenshot.
<img width="1691" alt="Screen Shot 2020-12-02 at 7 37 15 AM" src="https://user-images.githubusercontent.com/16477724/100887557-557b6b80-3472-11eb-8353-920f65bfb7d4.png">

Please let me know if more info is needed. Thank you!

**Comment by jonwehausen** [comment]
@oksana-c Thank you again for all your efforts here. 

## QA Testing
- Prior to this testing, we needed to add-in userID to the Fields to Set on the GA Settings variable to be included with the pageview tag  to enable pageviews to flow to the newly created user ID GA view

Test case | Data Layer Screenshot | Tag Manager Screenshot | Test Status
------------ | ------------- | ------------- | ------------- 
User Roles and ID loaded | ![image](https://user-images.githubusercontent.com/48527022/100942770-eaf61a00-34c9-11eb-9bc7-3bbc8039f567.png) | ![image](https://user-images.githubusercontent.com/48527022/100942727-d9ad0d80-34c9-11eb-8a92-7c2cbaf5ecd3.png) ![image](https://user-images.githubusercontent.com/48527022/100942459-6a371e00-34c9-11eb-8f6b-a79bf5a18cdc.png) | ✔️ **PASS**

Closing this issue!

**Comment by oksana-c** [comment]
Thank you @jonwehausen! I confirm we are now getting data for Roles and IDs in GA🎉  VSP Colab cycle survey completed 👍
