### ISSUE TITLE
Update Mockup to Include VRE Orientation in CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15134]
## Background
Given what we have from VRE around orientation, we need to include that content into the CH31 feature.

## Considerations
- Everything that we were given should be included 
- The intent from the business is for the Veteran to click "Next" all the way through to the form before completing the eligibility wizard
- Link shared in slack (Jason : Jim)

## Tasks
- [x] Include the new orientation pieces into the CH31 mockup

## Acceptance Criteria
- [x] The mockup has been updated and shared with the team

**Comment by sporeboy** [comment]
Initial pass of walkthrough available here: https://xd.adobe.com/view/aaf3f28b-b763-4c16-ba02-d1d47e20328e-ffa0/

Working on refined variation; will share that when ready.
