### ISSUE TITLE
Possibly update Cerner alert main CTA button links to use `getCernerURL()` helper

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#15135]
The three new My VA Cerner alerts all send users to the same Cerner URL (`https://patientportal.myhealth.va.gov` in prod, or `https://ehrm-va-test.patientportal.us.healtheintent.com` if not in prod).

Perhaps we should update those links to match what the Public Websites team is using.

## Links
Prescriptions: `getCernerURL('/pages/medications/current')`
Appointments: `getCernerURL('/pages/scheduling/upcoming')`
Secure Messaging: `getCernerURL('/pages/messaging/inbox')`

- [x] determine which URLs are being used on the static pages (added above)
- [x] determine the purpose of `clear-session?to=` in the URLs (was unable to determine the purpose of that part of the URL; the URLs used by the Public Websites team came directly from Cerner)

**Comment by erikphansen** [comment]
@mshea0606 I think that this can be tested in staging... if we have staging users that are enrolled in facility 668

**Comment by erikphansen** [comment]
@mshea0606 I'm actually gonna make a change to some logic to make this easier to validate on staging.

**Comment by mshea0606** [comment]
@erikphansen ok sounds good!
