### ISSUE TITLE
Design Feedback - Design intent Collaboration - BAM2 Debt Resolution FSR Form #5655

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#15144]
- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

**Must:**
- None right now

**Should:**

- Prefill as much info as possible

**Consider:**

- None right now

**Definition of Done:**
- [ ] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by rileyorr** [comment]
Thanks for the feedback @allison0034! We will be pre-filling as much info as possible to make the form easier to complete. 

@emilywaggoner & @CrystabelReiter if neither of you have additional feedback we can probably close the ticket! Thanks all!!
