### ISSUE TITLE
Discovery: IA for teams/vsp/ folders

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#1514]
Work with the VSP team to create an IA for all documentation and files within their team space.

**Comment by meganhkelley** [comment]
Meeting 9/10 to gather feedback from Rachael and Andrea. Matt made changes to branch as documented here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/MJ_rearchitect_teams_vsp_09112019/teams/vsp
