### ISSUE TITLE
Contact VA - It takes many tab clicks to start reading page with TalkBack (Android)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#15145]
## What happened?
I have to click the tab button many times to get going with reading and tabbing through the page.  I thought it wasn't working at all, but after 16 or so tab clicks, TalkBack started going through the page and reading it for me.  Whenever I finally tab through the page, I have to click the tab button another 16 times to start reading through the page again. (After it lands on the profile button.)
(NOTE: Noticing this on other pages, too, like Veterans Crisis Line.)

## Specs:
- Android Pixel 3XL simulator
- TalkBack enabled
- User:  patient998@id.me

## Steps to Reproduce
- Enable Talkback
- From home page, navigate to Contact VA page
- Using the tab button, begin tabbing through page
- NOTICE that it takes 16 tab clicks to start to read or recognize anything on the page and it starts at the back button.

## Desired behavior
User should be able to tab through page without extra tabs that seemingly do nothing.

## Acceptance Criteria
- User is able to tab through the Contact VA page and listen to all text and elements on the page without having to do extra taps to advance.

## Bug Severity
- 4  Low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14015

## Screen shot(s) and additional information

(I'm unable to upload the mpeg that I had recorded as that is not supported by zenhub...)

**Comment by komaly15** [comment]
Seems like this is a package issue w/ react-navigation, may need to monitor this issue for when a fix comes up. Issue got reopened almost 2 months ago, hopefully the fix is in the works.
https://github.com/react-navigation/react-navigation/issues/6909

**Comment by digitalken** [comment]
Closing 7/9/2021 - Added info to similar bug https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17008
