### ISSUE TITLE
Cerner Toggle Feature Staging/Production 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15149]
## Issue Description
_On staging, if we don't have a feature toggle for the Cerner facility and their MVI `isCerner flag = true`, allow the facility to be considered a Cerner facility.
On production, if we don't have a feature toggle for the Cerner facility and their MVI `isCerner flag = true`, do NOT allow the facility to be considered a Cerner facility._

## Front end tasks
- Staging = MVI `isCerner flag = true`, allow the facility to be considered a Cerner facility
- Production = MVI `isCerner flag = true`, do NOT allow the facility to be considered a Cerner facility.

## Acceptance Criteria
- [ ] Cerner toggles are set accordingly which should enable future Cerner support.
- [ ] Validate toggles are working properly and accessible process team

**Comment by kelsonic** [comment]
Thank you for creating this! Super helpful how you add tags + the epic link too 🙏 📈

**Comment by brianalloyd** [comment]
Closing per grooming, feature already available.
