### ISSUE TITLE
[Bug] - Save in progress back button

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#15148]
If I try to resume a form 526 form where I left off in the middle (locally) and click the back button I am taken out of the form.  I would expect to have a way to go to an earlier section of the form. 
![sip_back](https://user-images.githubusercontent.com/19188/96787933-9d619a00-13c0-11eb-978c-e09bb06c76a4.gif)

**Comment by Mottie** [comment]
I've noticed this happens sometimes when I use the save-in-progress menu and select a return page that is no longer valid - given the state of the form data. Try opening the save-in-progress menu and setting it to the introduction page.
