### ISSUE TITLE
Split the Larger 686/674 Submission into Smaller PRs

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15151]
## Background
In order to ensure the 674 submission gets to the right people for approval, we need to split the submission and label it accordingly based on what was selected.

## Previous Tasks
- [x] Create a 674-specific job
- [x] Do a check to see if a 674 workflow was selected, and if found, kick off that other job that applies the correct proctype cod, EP code, BenefitClaimType`*` code to the split submission.
- [x] Move code around the service/lib file
- [x] Pretty comprehensive redo of lib tests
`*` - check

## New Tasks
- [x] Split the larger PR in to two pieces for easier digestion
  - [x] model
  - [x] lib code

## Acceptance Criteria
- [x] A PR for the model has been requested for merging

**Next steps:**
- [x] A PR for the lib code has been requested for merging amongst ourselves

**Comment by digitaldrk** [comment]
PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/5139
