### ISSUE TITLE
 Set up continuous integration to publish Storybook

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15169]
## Issue Description
 Set up continuous integration to publish Storybook

---
## Tasks
- [ ] Backend work to set up CI to publish to Storybook

## Acceptance Criteria
- [ ] New Component and form pattern and updates are published to storybook
---

**Comment by bkjohnson** [comment]
We've found out that we can't rely on the existing deploys in ansible/Jenkins, because they will overwrite the `/storybook` directory in the bucket. This means that we will have to shift the deployment from Jenkins to CircleCI so we can have greater control.

**Comment by bkjohnson** [comment]
We have moved the dev & staging deploys into CircleCI, and we also have storybook deploying to both of those environments. Here is what needs to happen in order for us to close this ticket:

- Deploy to design.va.gov (prod) from CircleCI
    - There isn't a technical reason why we haven't done this yet - we can set this up at any time modeled after dev & staging
    - Need to request access from Ops and wait until we're ready
- Deploy storybook to design.va.gov/storybook
    - Same idea as above - just waiting to finish research

**Comment by bkjohnson** [comment]
As of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/358, we are deploying to design.va.gov from CircleCI. All that we have to do now in order to close this is:

- [ ] Deploy storybook to design.va.gov/storybook
