### ISSUE TITLE
Allow Veterans to apply to PCAFC with only secondary caregiver(s)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#15161]
As a Veteran with a secondary family caregiver
I want to be able to complete the PCAFC application
So that my secondary family caregiver can be recognized by the VA and receive needed support.

Current stage: research and design.

**Comment by jonathanjnelson** [comment]
[Mockups can be seen here](https://vsateams.invisionapp.com/share/6XZ7ELBVFG4#/435629118_Intro_)

**Comment by jonathanjnelson** [comment]
[Updated mockups ](https://vsateams.invisionapp.com/share/DFZC9QLNYUP#/436913294_Intro_2)

**Comment by jonathanjnelson** [comment]
[Flow can be explored here](https://vsateams.invisionapp.com/share/HDZEEIXRBZG#/435554202_Secondary-Slected-No)

**Comment by jonathanjnelson** [comment]
Hi @peggygannon! Hoping to get your feedback on the content of this error message. 

Context: 

If the user selects _no_ to add a Primary Family Caregiver 
and selects _no_ to add a Secondary Family Caregiver 
an error is triggered as the user is required to add at least one family caregiver to the application.

<img width="743" alt="Screen Shot 2020-11-11 at 2 23 38 PM" src="https://user-images.githubusercontent.com/58444931/98860568-82b39b80-2429-11eb-9e3e-50438b109899.png">

**Comment by peggygannon** [comment]
Hi, @jonathanjnelson! a few followup questions on this: 

--will the user get any error message if they click No to Primary Caregiver, but Yes to Secondary Caregiver? 

--for the *what you can do* content, is the desired action that the user go back and select a *Primary* caregiver? or does it not matter---they can select either primary or secondary and be able to continue?

**Comment by jonathanjnelson** [comment]
@peggygannon 

--will the user get any error message if they click No to Primary Caregiver, but Yes to Secondary Caregiver?

_No, the user will only get an error if they select no to both questions._ 

--for the what you can do content, is the desired action that the user go back and select a Primary caregiver? or does it not matter---they can select either primary or secondary and be able to continue?

_It does not matter.  The user will be able to go back and enter primary or secondary and continue_ 

I hope that helps. Let me know if you have any other questions.

**Comment by peggygannon** [comment]
Hi, @jonathanjnelson Here's recommended messaging. We have a similar message in the 526 about adding a disability, so I followed that pattern! 

**We need you to add a Family Caregiver**
We can’t process your application unless you add at least 1 Family Caregiver. Please go back and add either a Primary or Secondary Family Caregiver to your application.

**Comment by jonathanjnelson** [comment]
Thank you @peggygannon! I appreciate it.

**Comment by jonathanjnelson** [comment]
[Updated designs](https://vsateams.invisionapp.com/share/HDZEEIXRBZG#/435554202_Secondary-Slected-No)

<img width="683" alt="Screen Shot 2020-11-16 at 2 08 19 PM" src="https://user-images.githubusercontent.com/58444931/99302593-31cee900-2815-11eb-852f-def106cd76f5.png">

**Comment by peggygannon** [comment]
Hi, @jonathanjnelson Updated screenshot looks good. thx!

**Comment by jonathanjnelson** [comment]
Hi, @peggygannon 

Based on stakeholder feedback, we are going to make a slight tweak to the content. Please let me know your thoughts and if you have any concerns: 

> **We need you to add a Family Caregiver**
We can’t process your application unless you add a Family Caregiver. Please go back and add either a Primary or Secondary Family Caregiver to your application.

**Comment by jonathanjnelson** [comment]
@LinnJS for awareness

**Comment by peggygannon** [comment]
Hi, @jonathanjnelson this look fine. Thank you for following up!
