### ISSUE TITLE
Accessibility feedback - Usability Testing Prep - Public Websites [Wizard Migration]

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#15167]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

VSA: Jennifer
VSP: Trevor

## Feedback

1. Regarding the list of participant criteria, **should** prioritize in the primary criteria / must have, Veterans with cognitive disabilities such as PTSD and TBI, as well as those who do not have a college degree. Recommend including at least two (prefer three) people with a disability rating of 70% or greater, and specifically PTSD or TBI. **Why:** Given the increased incidence of cognitive disabilities for Veterans, and that some of the education benefits are especially for Veterans with a service-connected disability (such as CH31), this is a priority user need. 

1. Comments provided throughout the prototype screens.

**Comment by 1Copenut** [comment]
This feedback looks good. VSP has no additional comments.

**Comment by jenstrickland** [comment]
> We can clean it up for the prototype, but that excessive padding at the bottom of the step list is an issue outside of this wizard migration effort. I think it's an implementation rather than a design-system-component issue as it's not the same on all pages.

Good to have the background on it. That sounds likely. When we move designs forward, we want to share the preferred state, since devs will often code what they see in the designs. We've had some devs code ALL-CAPS because that was what was in the designs, for example. 

Great work!
