### ISSUE TITLE
upgrade css-loader and postcss-loader

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#15178]
## Overview 

- the css-loader on vets-website is over 2 years old and is blocking VFS teams from importing css from third party libraries 
- slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1603310486386000

**Comment by rianfowler** [comment]
## css-loader breaking change resolution 

| Version       | Breaking change     | Resolution     |
| :------------- | :----------: | -----------: |
|   [1.0](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes-2) | remove minimize option    | add `cssnano` dependency as post-css plugin |
||removed module option| not used |
||removed camelcase option|not used|
||removed root option|not used|
||removed alias option|not used|
||update postcss to 6|not a peer dependency |
||minimum nodejs 6.9|vets-website uses nodejs 10.15.3|
||minimum webpack 4|vets-website uses webpack ^4.43.0 |

**Comment by meganhkelley** [comment]
@rianfowler is there anything left to do here before closing this ticket?

**Comment by meganhkelley** [comment]
Upgraded. Announcement: https://dsva.slack.com/archives/CE4304QPK/p1603815025227700

**Comment by meganhkelley** [comment]
Upgraded. Announcement: https://dsva.slack.com/archives/CE4304QPK/p1603815025227700
