### ISSUE TITLE
Determine best option for logging SSO SAML cookie transaction ID value

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#15179]
We [have implemented](https://github.com/department-of-veterans-affairs/vets-api/blob/9e2dd479158f37c1e2f056c57c270bec448faddb/app/controllers/v1/sessions_controller.rb#L160-L184) the creation of a SAML cookie for tracking login requests across va.gov/eauth/ID.me

We are including in this cookie [a transaction ID](https://github.com/department-of-veterans-affairs/vets-api/blob/9e2dd479158f37c1e2f056c57c270bec448faddb/app/controllers/v1/sessions_controller.rb#L180) that we generate, along with [the saml request ID](https://github.com/department-of-veterans-affairs/vets-api/blob/9e2dd479158f37c1e2f056c57c270bec448faddb/app/controllers/v1/sessions_controller.rb#L181).

The transaction ID is not logged anywhere.  That is, there are no `vets-api` logs wherein we can find this ID and then use it for tracking a request to eatuh and ID.me.

Questions:
- Where should log the transaction ID? Rails logs? Add Sentry context with its value?
- If we are also sending the SAML request ID, do we also need the transaction ID?  Is this SAML request ID logged anywhere?

**Comment by jholton** [comment]
@ericbuckley we could use your opinion here.

**Comment by ericbuckley** [comment]
@jholton good point, I think adding that information to the `saml_request_stats` and `saml_response_stats` functions in the V1 SessionController makes the most sense.  Both methods increment statsd counters and emit log messages, the transaction id is only useful in the latter.
