### ISSUE TITLE
Create version 2 of VFS team service blueprint

### ISSUE THREAD

**Issue by emilywaggoner** [department-of-veterans-affairs/va.gov-team#1517]
## Purpose

Now that we are several months into iterating the onboarding process for VSP, we need to iterate the VFS team journey map to reflect the iterations we have made to the process and input we've gathered. [The first version of the VFS team journey map can be found here](https://miro.com/app/board/o9J_kxGvvmc=/). 

## What we need to do

Currently, the journey map does not reflect recently gathered research (pain points, positive feedback), or new steps in the process that we have incorporated. We want to update the journey map to reflect recent findings and identify iterations we've made.

## Def of Done

- [ ] New steps documented into the journey map
- [ ] Outdated steps and feedback retired from journey map
- [ ] New input and feedback incorporated into the journey map 
- [ ] Reviewed with DSVA

**Comment by emilywaggoner** [comment]
Working spreadsheet here: https://docs.google.com/spreadsheets/d/19EfkDr8pJ13gw0XfUlY3LySCKGi27-6vs7w7vsB2_Og/edit#gid=980063488

**Comment by mandifrances** [comment]
Hi @emilywaggoner I'm refining the backlog for Product Support. Does this need to go to the design team or can it be closed?

**Comment by emilywaggoner** [comment]
We can close this one!

**Comment by mandifrances** [comment]
Above comment to close.
