### ISSUE TITLE
Update Sentry to 20.7.0 

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#15175]
## Background

In order to integrate with GitHub, we'll need to upgrade to at least 20.7.0, see this issue on Sentry's forum:

https://forum.sentry.io/t/sentry-using-a-deprecated-github-api-endpoint/10393

and this GitHub changelog:

https://developer.github.com/changes/2020-04-15-replacing-create-installation-access-token-endpoint/

Luckily, upgrading Sentry is as simple as updating the version numbers and running the `install.sh` script (which happens as part of the build stage). 

## Tasks

- [x] Updating `devops` `ansible/build/roles/sentry10/vars/main.yml` versions:

```
sentry_version: 20.7.0
sentry_image: getsentry/sentry:20.7.0
```

- [x] Test locally `APP=sentry10 vagrant provision --provision-with build`

**Comment by kfrz** [comment]
Note on Sentry forums:

https://forum.sentry.io/t/csrf-token-issue/9607

**Comment by kfrz** [comment]
## 2020-10-27

This work happened on 2020-10-22, after which an undocumented change to Sentry's `docker-compose.yml` that introduced an `nginx` service for proxying requests caused conflicts with the existing proxy configuration present on the instance. 

We'll likely have to spin up a testbed to verify assumptions, but it seems like we can route requests ingress to the Sentry-provided `nginx` instance, combine our configuration requirements from `/etc/nginx/nginx.conf` and then test. 

Good news, the GitHub integration worked like a charm with Sentry 20.7.0! 

Demian mentions there's a path forward for using Fargate and ECS to deploy the Sentry service, will follow up on that w/ Bill Ryan in the course of #15302

**Comment by kfrz** [comment]
Once we had access to a test deployment job and environment (`sentry-test.vfs.va.gov`), we hoped to build Sentry 10.0.1 in this environment, and have a reliable pathway to upgrade to `20.6.0`. In the happy path, this upgrade would require:

- Upticking versions in  [`ansible/build/roles/sentry10/vars/main.yml`](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/sentry10/vars/main.yml) to desired version from [getsentry/onpremise](https://github.com/getsentry/onpremise) repository
- Building the new [image](http://jenkins.vfs.va.gov/job/builds/job/sentry10/)
- [Deploying](http://jenkins.vfs.va.gov/job/deploys/job/sentry10-utility/) the new build, which will run the built-in `./install.sh` script from the Sentry repo. This is meant to be idempotent script and will only migrate data if required.

In efforts to rectify the duplicated Nginx configuration above and provide a testable upgrade path, we've discovered difficulties building the 10.0.1 containers with existing playbooks. 

> Removing lines 32-39 in [`sentry10/tasks/main.yml`](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/sentry10/tasks/main.yml#L32) will allow for building a local machine to manually test the install script. 

It's possible we could build and deploy the existing code on `master` and test it in `sentry-test` env, without the work of reproducing the nginx confict. This way we can deploy the upgraded version and avoid the 10.0.1 issues, but might risk some downtime if we need to restart nginx config. 


cc: @jhouse-solvd @omgitsbillryan

**Comment by mleclerc00** [comment]
@kfrz 

I fixed the issues you mentioned, so you should be able to build and test locally to further troubleshoot the nginx configurations.

> In efforts to rectify the duplicated Nginx configuration above and provide a testable upgrade path, we've discovered difficulties building the 10.0.1 containers with existing playbooks.

The newer versions of sentry rely on [symbolicator](https://github.com/getsentry/symbolicator).  As a result the install.sh script would error unless a symbolicator version was explicitly passed to it.

https://github.com/department-of-veterans-affairs/devops/pull/8434

**Comment by jhouse-solvd** [comment]
Passing this to @mleclerc00 to take a deeper look and find out what's needed to move this forward.

**Comment by jhouse-solvd** [comment]
@mleclerc00 - is this good to move to Current Sprint?

**Comment by mleclerc00** [comment]
Probably, still sorting out a couple of things but should be good to go at some point soon.  Also need to figure out when is the best time to get this done, assuming off hours.

**Comment by mleclerc00** [comment]
Also, as a side note here.  From my testing on `sentry-test` and what I read online from many github issues updating directly to the latest version of sentry is the way to go.  So my plan is to move directly to 21.2.0.

**Comment by jhouse-solvd** [comment]
Sentry has been upgraded and migrated to EKS. 

There are currently some known performance issues that Ops is investigating along with other platform teams and leadership. 

Please see https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/27032

Closing.
