### ISSUE TITLE
1995/10203: Missing the blue line under ‘Need Help?’ on confirmation page/UX updates

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#15172]
Steps to reproduce
1. Navigate and submit for both forms and stop on the confirmation page for
https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction
&
https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction

1.  Missing the blue line under ‘Need Help?’
2. The ‘go back to VA’ button at the end of the page should expand in width to match the mock
3. It looks like the padding on this page is 10px but the padding in the mock is 15px I hadn’t noticed it until I got to the phone number - feels very close to the edge.

What it looks like:
![blueline2.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9cab807e-6e25-4999-891a-3f80438b948e)
##
What it should look like
![blueline1.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/06084bf0-0921-49af-9c8b-25d5574007b2)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14887

**Comment by sonntag-adam** [comment]
10203
![Screen Shot 2020-11-09 at 8.11.45 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6043f3e4-5b6a-47e4-a2b9-da5f935cff99)
##
1995
![Screen Shot 2020-11-09 at 8.13.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8fee990e-f604-402d-85c6-ec7bdf0bf2da)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review in staging.

**Comment by JenLJ** [comment]
UX Review 1/2:  The ACs above are checking out for me!

Note:  When I hit Submit application, a red error message appears beneath the button stating that I'm no longer logged in - and then diverts to the confirmation page.  (It's happening too fast for me to get a screenshot of it). I am filling out the application without logging in, but I don't feel like an error should be thrown right before it goes to the confirmation page.

**Comment by watersemma** [comment]
UX Review 2/2: This checks out for me! Thank you.

**Comment by sonntag-adam** [comment]
Closing bug.
