### ISSUE TITLE
Audit Slackbot replies to promote Platform website

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#1518]
There are many slackbot replies that include links to files in the different repos.  Review the replies and update as needed with the new location of files. Also identify/recommend any new slackbots needed for key help documentation.

**Comment by gmaciolek** [comment]
This sounds like it was a great idea. 

Backlogging with the added note that besides considering how we can use Slack to surface help documentation, maybe we should also create a general docs publishing 'release plan' checklist that includes something like: Update other documents and tools that might be impacted by this change with new links.

**Comment by lianilychee** [comment]
Removing the `documentation` and `documentation-support` labels and moving to the team's backlog board https://github.com/department-of-veterans-affairs/va.gov-team/projects/33

**Comment by vbellissimo** [comment]
Cancelling/old task.
