### ISSUE TITLE
Analytics Reporting Request for Sophie (VA Mobile App Team)

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#15182]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
VA Mobile App team has a feature that lets users download letters. We are using this request to determine how to prioritize the different types of letters that are included in MVP.

- What team/project is this work for?  VA Mobile App team

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after)? The last 6 months

## Analytics to Track Down
> Examples
> 
> - [ ] # of letters downloaded by letter type 

## Which Product Questions are you trying to answer?
- What letter(s) are most important/needed by users and therefore should be included in our MVP?

## Additional Comments

We need this information fairly quickly in order to prioritize our backlog.

Tagging team members who may want to follow along: @bessgreen @steve-gov @bridgethapner 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @srmyers17, acknowledging receipt here! Will be in touch soon on this request.

**Comment by jonwehausen** [comment]
@bmcgrady-ep Could you pick this up at your convenience? Thanks in advance

**Comment by bmcgrady-ep** [comment]
@srmyers17 - [Here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.deviceCategory&explorer-table.advFilter=%5B%5B0,%22analytics.deviceCategory%22,%22PT%22,%22mobile%22,0%5D%5D&_r.drilldown=analytics.eventLabel:letter-download) is a GA Report that shows the letter downloads on mobile devices by letter type. Let me know if you are looking for something else.

**Comment by jonwehausen** [comment]
Hi @srmyers17, just wanted to follow-up here if there is anything else we can help with. 

Otherwise we will close and re-open for any further questions you may have. Thanks again.
