### ISSUE TITLE
Usability Testing Prep - eBenefits/Chapt 31 - IA Feedback

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#15189]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This issue describes IA feedback

**MUST**
- The button on the Eligibility page (CH31 Landing) labeled "Apply for Veteran Readiness and Employment" should link the user to the wizard content, not the introduction content on the application
- Breadcrumb and left nav are inaccurate for the Eligibility page (landing page). 

Breadcrumb should be:  Home > Careers and employment > Veteran Readiness and Employment > Eligibility ~for VR&E~

Left nav should be:
![image](https://user-images.githubusercontent.com/20994159/96909657-edde0380-1463-11eb-9bdc-fa8df77a4951.png)

## Definition of Done
- [ ] Must feedback is implemented on staging
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by jason-gcio** [comment]
@mnorthuis - the prototype was meant to reflect that navigation and has been updated; we'll be going into the wizard ahead of the intro page, per @sporeboy 

Also, we will be leaving the breadcrumbs as is and the left nav was not completed here in the prototype.  (I think the landing page was more templatized before we realizes that PW would edit any needed content.)

**Comment by mnorthuis** [comment]
Thank you for the update.  PW team will ensure left nav and breadcrumb are correct on the static page for purposes of launch, just be aware that your reflection of it in the prototype is incorrect, so any navigation related tasks may not be reflected accurately in research.  Thanks!
