### ISSUE TITLE
Access for John Borden

### ISSUE THREAD

**Issue by RockslideJr** [department-of-veterans-affairs/va.gov-team#15187]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > John Borden
- Please Provide your email.
   > john.borden@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA Lighthouse API, software engineer, AdHoc

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsZ7unl3wztG9flsc9+VbQPSJMaBQkjp4VIKoB096Oz6p1yANIbge4yjS4Ds4keBEoDdS1L8+RE3WDS+NBIMRaKeNFl4j5s+KPfGl2JH3Eyg9/hvGDmBN6QgkDFLWjUOAY6mlwYdW8MATPaAgX5miU8xUZXAYLkqicxhQDz+N2RgZ6hS0sV9lrL1GOe3yZ0N3gUWYa1JS0hPjUtQS8bm1TxciCGlhDOac1zjov89qbJFQ6CSoF2Jpfs3oOflx0CkMTLZYRar05usTBYlNmUWMsn4ScO8ed5WCmn30W41QWKd7fn7QGMvoLm6j4X6wDmcT40wNyh/HWXDlDoxFHNezXNzewi+qK1GM8vI2xbYQpFf3DL9LsW898NPHeC13inUX5sVoZu6ByY4JCJIsKAwCKKCkQ2WxkLGyzrrV2wjl2gRtYMNr5PrQdGyaoCr3ox6pUkEYeeDtdhMegYN5TfR6d0Ed1w4SmO/RBevA73nOGYUKTGFFRKKAJO011TUCWxDU= johnborden@John-Borden-Macbook.local
```

- Grant AWS Console access?
  > YES

**Comment by RockslideJr** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
**Requesting approval for AWS Access**
User: John Borden
COR: Cecilia Lee
cc: @Jeff-Hayter

**Comment by jsev-io** [comment]
Hello @RockslideJr 

SOCKS access granted. Please see this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) for getting configured.
Once you've confirmed access, please close this issue. Reach out for any help needed!

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by jsev-io** [comment]
Credentials provided
