### ISSUE TITLE
Discovery:  PPMS Database of In-Network Providers for Community Cares

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1519]
**History:**
The PPMS database stores provider info from a variety of community care-based contracts within the VA. 

**Problem Statement**
Some of the provider info stored in the PPMS database are considered “in-network” (approximately 9 network providers), and some are not. If the provider is not in-network, the VA will not pay for provider services.  

**Questions:**
1. What do we know?
2. What can we do now?
3. What lifts can we provide?

**Goals:** 
Work with OCC Stakeholders to:
- [ ] Identify network affiliations that are contractually required to be "in-network" 
- [ ] Determine why some providers are in-network and some are not.

**Comment by ncksllvn** [comment]
That data representing a model has a `NetworkId` property as well as a `ProviderNetwork` property. I think the latter is just the name of the network matching the former's ID. I think a `NetworkId` of `0` indicates that that they are not in-network.

If my understanding of this work is correct, PPMS contains providers that aren't necessarily part of the Community Cares VA program? And that's what it means for a provider to not be in-network?

**Comment by Karak888** [comment]
@chrisj-usds @jenniferlee-dsva @ncksllvn I just pulled this into Sprint 4. 
 
**Next steps** (per Jen's feedback):
- [ ] Chris to set up intro call meeting with Jen and Azzure (OCC Stakeholder)

**Goal of Call:** 
- Introduce Jen and Azzure to start conversation re:  root problem she is trying to address / reality of contractual needs.

**Comment by Karak888** [comment]
This is just a ticket to track conversations and will create tasks as @jenniferlee-dsva needs.

**Comment by Karak888** [comment]
@jenniferlee-dsva will have a couple more conversations - Discovery ticket (in-flight)

**Comment by Karak888** [comment]
bringing back stakeholder team @Karak888 to create a ticket for demo bi-weekly etc.

**Comment by Karak888** [comment]
@jenniferlee-dsva will schedule call.

**Comment by Karak888** [comment]
@jenniferlee-dsva second call with Azure - next call is 10/16 and will provide more context. confirm ok with messaging for urgent care searches (Tri-West) 2.) solidify what we need to do for in network information.

in network info is provider focused- - does confirm Chris and Jen's initially suspected in network info that azure's team wants us to dispaly has little to no relevance to veterans.

**Comment by chrisj-usds** [comment]
@Karak888 @jenniferlee-dsva 
Had a call yesterday with Zach Fain and others who said that they are not ready for us to take away the link to Tri-West. Want to make sure that what you're hearing from Aszur doesn't conflict with that.

**Comment by Karak888** [comment]
I am including some notes from our initial meeting with PPMS- Slightly nonsensical at points I'm sure, just wanted to capture something to build off of!
[PPMS Initial Meeting Notes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3713662/PPMS.Initial.Meeting.Notes.docx)

**Comment by mmiddaugh** [comment]
@davidconlon based on comments in [1961](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1961), do we still need to incorporate this in/out network consideration? Is this issue still relevant or should it be closed?

**Comment by davidconlon** [comment]
@mmiddaugh followed up with Chris and Jen. We can close based on comments in 1961
