### ISSUE TITLE
Access for [Mark Nunemaker]

### ISSUE THREAD

**Issue by mnunemaker-va** [department-of-veterans-affairs/va.gov-team#15194]
# Instructions
1. Need access for SOCKS
2. ORCHID/IRIS
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
  Bryan Broome - bryan.broome@va.gov
- Please provide your name.
   > Mark Nunemaker
- Please Provide your email.
   > marknunemaker@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   Team Orchid/Iris - QA on the team

- Requesting SSH key authorization?
   YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEInXFvEWkwkUnPCK74TkvUnKpTfsstrWthCJMhPmaC1peT11373Zsd+5wh0gvJ4ZiurxQavdKtPCQazyxYQEH7QH4MtdBxORuAlS8k8a/ipS3p7iG6H1zWIOa3BoUri/HH6Gwk89nrvgYqrLVg91NdjQCrD4ae7hVMiNpyuEqya51j+3W9lgd43yazC5HybgY+Gs3fq0d6Wra65g6xsGnrhqOvqnuHiGqbq7zGhftBYKQF6cbOYj/UaYXMQPuyPjgE1eKPp5Yp9u3c6jtZn33GJmN1kZzeF3627DcYBrVDEcOYHfdbiFI6BTBbduRHiACZHHqE0tVWjPMaD09XG2hoN87ED9p0r8iDsDxavyjkStaOzXnjhM8GfFrb3TcpVn/I01c/gI+MFKLy+FavTpdxzVLbCD/sTMGjgLGiB0Ab9DWGp0IAGGVYOzIgOcyWk+32PhFL8mEpeEzSStquf52qswC1k9adTO4ZSaW1EKtroJqdoCyzSbRZBUJU8V02pM= mnunemak@Marks-MBP
```

- Grant AWS Console access?
  > NO

**Comment by jsev-io** [comment]
Hello @mnunemaker-va 

SOCKS access granted. Please see this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) for getting configured.
Once you've confirmed access, please close this issue. Reach out for any help needed!
