### ISSUE TITLE
Access for Carey Otto, Cindy Merrill, Jenny Spadafora, Lauryl Zenobi, Evangeline Garreau, Mina Farzad, Maria Vidart-Delgado, Brent Schneider, Darcy Duda

### ISSUE THREAD

**Issue by mlvidart** [department-of-veterans-affairs/va.gov-team#15190]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Maria Vidart-Delgado
   > Carey Otto
   > Cindy Merrill
   > Jenny Spadafora
   > Lauryl Zenobi
   > Evangeline Garreau
   > Mina Farzad
   > Darcy Duda
   > Brent Schneider

- Please Provide your email.
   > maria@adhocteam.us
   > carey.otto@adhocteam.us
   > cindy.merrill@adhocteam.us
   > jenny.spadafora@adhocteam.us
   > lauryl@adhocteam.us
   > evangeline@adhocteam.us
   > mina@adhocteam.us
   > Darcy.Duda@adhocteam.us
   > Brent.Schneider@adhocteam.us

- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > We are all members of the UX team at VA Lighthouse APIs, and we're a combination of researchers and designers. We all work for Ad Hoc LLC. 

- Requesting SSH key authorization?
   > NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+ username@mail.com
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
We need to access the transcription service to transcribe interviews that we conduct with non-Veteran users.

**Comment by mydesignrocks** [comment]
Hello @mlvidart - the public ssh key is unique to the respective resources and their workstations (windows/mac).
Can you please have them all submit a unique request with the first set of directions here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/scripts/socks

**Comment by jsev-io** [comment]
**Requesting AWS Access for the following users:** 

Maria Vidart-Delgado
Carey Otto
Cindy Merrill
Jenny Spadafora
Lauryl Zenobi
Evangeline Garreau
Mina Farzad
Darcy Duda
Brent Schneider

COR: Cecilia Lee
cc: @Jeff-Hayter

**Comment by mlvidart** [comment]
> Hello @mlvidart - the public ssh key is unique to the respective resources and their workstations (windows/mac).
> Can you please have them all submit a unique request with the first set of directions here:
> https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/scripts/socks

We don’t need socks proxy, just a limited AWS account with S3 and Transcribe access in iAM. Ref: https://dsva.slack.com/archives/CBU0KDSB1/p1603395713414900

**Comment by mydesignrocks** [comment]
thanks for the clarification @mlvidart and appreciate you chiming in @jsev-io !

**Comment by Jeff-Hayter** [comment]
@jsev-io Here are the people approved for AWS:

Maria Vidart-Delgado
Carey Otto
Cindy Merrill
Jenny Spadafora
Lauryl Zenobi
Mina Farzad
Darcy Duda
Brent Schneider

**Comment by mlvidart** [comment]
@Jeff-Hayter Great news! Do you know why Evangeline Garreau is not on the list? She was on the original request. Thanks for any info.

**Comment by Jeff-Hayter** [comment]
@mlvidart There was no date provided by the COR for Evangeline's eQIP transmittal.  When I receive that I can approve.

**Comment by jsev-io** [comment]
Thanks @Jeff-Hayter for the approval on these.
@mlvidart Now that I'm back from PTO and we have the majority of approvals I'll get those going for you!

**Comment by jsev-io** [comment]
All currently COR approved accounts have been created!
Awaiting approval for Evangeline Garreau, will leave ticket open in the meantime.

**Comment by jsev-io** [comment]
@Jeff-Hayter to confirm, we're still waiting on Evangeline Garreau's eQip confirmation right?

**Comment by Jeff-Hayter** [comment]
@jsev-io Evangeline Garreau approved for AWS.

**Comment by jsev-io** [comment]
@egarreau provided aws credentials. Closing ticket.
