### ISSUE TITLE
[Discovery] Create service blueprint for VFS teams building on VSP

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#152]
## Description
We're having a workshop with stakeholders to help inform MVP decisions. We need a service blueprint to help frame the discussion / illustrate the biggest pain points in the process. 

## Objective
Create a service blueprint that highlights the biggest pain points for VFS teams building on VSP.

## AC
- [x] Service blueprint has been created and reviewed with the team.

**Comment by rroueche** [comment]
@smoonpeyes I would consider this done once the link is stored in the right place in GH, and if the additional pain points discussed during our meeting on 6/5 are added in.
