### ISSUE TITLE
Wrong paragraphs - /careers-employment/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15203]
## Issue Description
The paragraphs are displayed incorrectly. They might need to be sorted.

## Example:
![Screen Shot 2020-10-22 at 4.39.49 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/96b02c52-aa13-40c2-a905-4647970502b8)

## Example File
`/careers-employment/education-and-career-counseling/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.

**Comment by theodur** [comment]
After doing some digging, I discovered that the missing content from the graphql build is nowhere to be found in the cms export. This issues is related to the `fieldFeaturedContent` field. I took a specific sentence from `fieldFeaturedContent` in `/careers-employment/education-and-career-counseling/index.html` and searched for it in the `.cache/localhost/cms-export-content/` directory, but no results were found. I searched for the sentence `You can get these services if one of the following is true.`

This issue may be related to the updated content not be exported in the cms export. The `fieldFeaturedContent` field in both the cms export and graphql builds have the same `entityId` of 4484, but as mentioned above, the information is different.

Planning on confirming with the cms team.

**Comment by indytechcook** [comment]
this is related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3324 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/15321

**Comment by theodur** [comment]
This issue is currently blocked by the issues mentioned above by @indytechcook.

**Comment by indytechcook** [comment]
Please reset, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3324 has been merged and content fix script has been run.

**Comment by theodur** [comment]
After verifying, there are now no more discrepancies between paragraphs for `/careers-employment/education-and-career-counseling/index.html`. Thanks @indytechcook for fixing this issue!
