### ISSUE TITLE
Common component for editable text view

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15200]
## User story
As a user, I want the ability to edit my contact information from the app. 

## Acceptance criteria
1. Create a common component for the editable text view
2. Contains a label and a suggestion/hint text, when null
3. Ability to select into the component to activate the edit state

## Designs
Example from edit phone number: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432057842

## Dev checklist

- [ ] UX/UI
- [ ] Add tests

**Comment by digitalken** [comment]
Testing:

1. Verify user is able to edit my contact information from the app.
2. Verify for accessibility that there is a suggestion/hint text and a label when null. (ghost placeholder text?)
3. Verify ability to go into component and activate edit state.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Tested in TestRail. Passed, User is able to edit contact information (just not saved yet due to backend). Hint text is present for null fields.
