### ISSUE TITLE
Analytics Reporting Request for VANotify email open rates

### ISSUE THREAD

**Issue by saman-moshafi-va** [department-of-veterans-affairs/va.gov-team#15208]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

I wanted some guidance on how/what your recommendations are for VANotify to track open rates for the notification emails we send (successful submission of the 526EZ disability claim on VA.gov)

We plan to use GA pixel to achieve this and need guidance on the image URL.  This is the draft URL:
`<img src="https://www.google-analytics.com/collect?v=1&tid=UA-01010-1&cid=555&aip=1&t=event&ec=email&ea=open&dp=/vanotify/va.gov/va.gov/Form 526ez template&dt=<email subject>">`

Also are there norms/best practices we should follow for the image src?

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Saman Moshafi
    
- What team/project is this work for?

    - VANotify (Notifications for internal VA teams), notification email for 526EZ disability compensation claim
    

## Timeframe for Analytics Requested
Not a high priority for now - asking for direction and best practices + guidance

## Analytics to Track Down

The number of Veterans who open the email (The email is sent after the successful submission of the 526EZ disability claim on VA.gov)

## Which Product Questions are you trying to answer?

The number of Veterans who open the email (The email is sent after the successful submission of the 526EZ disability claim on VA.gov)

## Other Helpful Questions to think through
- Who is your audience? 
  Internal team and stakeholders
- Why do you need this data?
  Understand the number of Veterans who view/read the notifications email
- What are you hoping to find?
  Get a rough estimate of how many Veterans have viewed/read the notification email 
- What is your hypothesis that you're hoping the data will support?
  1. Veternas view/read the notification email after they complete the claim submission online if they need to access relevant data (Claim ID, date the claim was submitted)  
  2. The notifications email will help guide the Veteran to check the status of their claim on VA.gov
- What area of the VA are you hoping to assess?
  Sending notifications
- How frequently do you need this data?
  weekly and onthly

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

We have created the draft image src URL and would like guidance on that.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @saman-moshafi-va , acknowledging receipt!

**Comment by jonwehausen** [comment]
@bmcgrady-ep could you pick this up at your earliest convenience, thanks in advance

**Comment by bmcgrady-ep** [comment]
@saman-moshafi-va - Here is the recommended hit parameters for email opens: `<img src="https://www.google-analytics.com/collect?v=1&t=event&tid=UA-50123418-16&cid=4960577a-5532-4c2b-a088-7f2b6865ba68&aip=1&ec=email&ea=open&el=disability-526EZ--submission-successful&dp=%2Femail%2Fvanotify%2Fva.gov%2Fva.gov%2Fform%20526ez%20template&dt=%3Cemail%20subject%3E&cn=disability-526EZ--submission-successful&cs=gov-delivery&cm=email">`

A couple of notes about the information in the hit parameters:
1. The **tid** is the Google Analytics Property that the data will be sent to, which in this case is the `VA.gov - Production` property.
2. The **cid** is the client ID, which should be a random UUID for each user.
3. The **dp** is essentially the URL that will show up in Google Analytics for this hit. Just wanting to confirm that `/vanotify/va.gov/va.gov/Form 526ez template` is the dp (Document Path) that you want for this hit. Also, Google recommends prepending /email to the dp to help identify that it was an email.

Last question: are you wanting to specifically track **email opens** or track **outbound link clicks** from an email to VA.gov?

**Comment by saman-moshafi-va** [comment]
To answer the question we would like to specifically track email open rates.  
We already have a link to track link clicks: `https://www.va.gov/claim-or-appeal-status/?utm_source=VANotify&utm_medium=email&utm_campaign=526EZ`
I will check the suggested URL and will come back after showing it to our team.

**Comment by saman-moshafi-va** [comment]
So how about using cid=555 and ci=<the unique number we generate>? Since we are including campaign fields, cs and cm?

**Comment by saman-moshafi-va** [comment]
This is the pattern that we came up with, the generated URL will conform to the URL characters and standards.  organization, service and template are internal to VANotify.  **Would this conform to the va.gov standards and guidelines and GA reports?**
```
v=1
t=event
tid=UA-50123418-16
cid=<notification id>
aip=1
ec=email
ea=open
el=<template name>
dp=/email/vanotify/<organization name>/<service name>/<template name>
dt=<email subject>
cn=<template name>
cs=<notification api provider>
cm=email
ci=<template id>
```
example:
```
v=1
t=event
tid=UA-50123418-16
cid=894de4a5-4be3-441c-8d1c-76e054a7a5ff
aip=1
ec=email
ea=open
el=Form 526ez email confirmation
dp=/email/vanotify/va.gov/va.gov/Form 526ez email confirmation
dt=Weʼve received your application
cn=Form 526ez email confirmation
cs=gov-delivery
cm=email
ci=0c1335fc-ca67-408a-b2ae-08b91ffaceba
```

**Comment by saman-moshafi-va** [comment]
For testing is it possible to get a tid for non-production environments? It will be really helpful

**Comment by bmcgrady-ep** [comment]
@saman-moshafi-va - Here is a tid for the VA's non-production GA property: `UA-50123418-17`. The rest of the parameters look fine to me. Let me know if you have any more questions!

**Comment by bmcgrady-ep** [comment]
Per slack conversation with @saman-moshafi-va I am closing the issue.
