### ISSUE TITLE
Enable learning center pages to receive full width banner alerts

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15213]
# Enable learning center pages to receive full width banner alerts

ETA - nice to have right after launch (in case we end up having a sitewide downtime banner) ; latest 1.1 timeframe. 

**See Slack thread for background:** 
https://dsva.slack.com/archives/C0173CAJ7A6/p1603395684467400

`the banner alert data is driven by the CMS, but we need to ensure that specific templates can render that data.`

**Example:** 

- If there's a system sitewide downtime banner, we should be able to show them on the learning center pages. 
- If Randi/Danielle pushes out a Coronavirus banner, they should be able to add it to the LC nodes and have it display on the page. 

**Example screenshot:** 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/9e61a338-a5bc-4de1-9593-1a9fdef32f7a)

**Comment by RLHecht** [comment]
Confirmed this worked on an R&S page with the current Coronavirus full-page alert. Screen shot here. Closing ticket. FYSA @brianalloyd @jenniferlee-dsva  ![Screen Shot 2020-11-06 at 4.32.20 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/cc1ee9d2-337a-4e7e-8cfe-9e45ff9485a5)
