### ISSUE TITLE
Access for Nathaniel Hillard

### ISSUE THREAD

**Issue by NatHillardVA** [department-of-veterans-affairs/va.gov-team#15217]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Zach Goldfine
- Please provide your name.
   > Nathaniel Hillard
- Please Provide your email.
   > nathaniel.hillard@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > OCTO Benefits Delivery, Tech Lead, USDS

- Requesting SSH key authorization?
   > YES
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDn5NeyLrWFPDJQBlqxlz1mmQv3oR/ueMKgE1EhcE+giUL+DwTc4LvERctMOurQchVymgFIC0ZDJ73Ag/2MV0l/thUCBhWYJZN9BoiltNXcTNn7wWg5P8y0JjUEOIDHaW+eqLmR4kITkfLoTk+DxY7E+denWePD7xzO8BYwvH69M+4PjEJXJTwPD6ERgPxaTM3C9iAQt12Scy7sr1tZCZb8R3dzPtOXTNWGXD/0Iv/ngE7WlgdrktWmvvIUeof9C7xK/MVZ2kYtPr75LjxdFkn8ZhdH5l3sqV07tiY73T9xdN+XmBsSvxFRKe+zPR2S9HcEgjtnR2pTz446OJ7Dq11d nathaniel.hillard@va.gov
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
We will be deploying the Claims Attributes API for use in Lighthouse - this will require ECR to store container repositories, ECS to store the cluster itself (using Fargate/EC2), S3 to store artifacts, and SageMaker to store notebooks and training data.

**Comment by NatHillardVA** [comment]
Hi everyone - 
Following [this tutorial]() , it seems like the next step is to tag @department-of-veterans-affairs/vsp-operations -- I'm not working on the VSP operations team directly but will be working with you to help stand up these endpoints

**Comment by mydesignrocks** [comment]
For AWS Access:

User: Nathaniel Hillard
COR: Zach Goldfine
Approval required: @Jeff-Hayter

**Comment by NatHillardVA** [comment]
Hi All - 
I should note I'm actually technically not a contractor, which I think may make a difference (apologies, I'm brand new here!). I work with USDS and am embedded in VA for this project.

**Comment by Jeff-Hayter** [comment]
@mydesignrocks Approved for AWS.

**Comment by tskinn** [comment]
Temporary creds have been sent. Reach out in slack if you have any issues.
