### ISSUE TITLE
Display & format saved address on the Personal Info page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15227]
## User story
As a user, I want the ability to see my saved address on the Personal Information page. 

## Acceptance Criteria
1. The Saved address appears on the Personal Info overview screen, displayed in the following format (push to a new line if a field does not fit on a single line):
     - [Address Line 1], [Address Line 2] (if an entry exists), [Address Line 3] (if an entry exists)
     - _For U.S. Addresses:_ [City], [State Abbreviation], [Zip code]
     - _For Military Base Addresses:_ 
          - [APO/DPO/FPO selection], [Full state] (e.g. **Armed Forces Europe (AE)**) [Zip code]. No comma b/w State & Zip.
     - _For International Addresses:_ 
          - [City], [State], [International Post Code]
          - [Country] (own line)

Note: there is a separate story to [save info on the backend](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14699) 

## Designs
Saved address summary on Personal Info screen: https://adhoc.invisionapp.com/d/main#/console/20546460/431636868/preview

### Example #1: U.S. Address
![Screen Shot 2020-11-03 at 2.26.07 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d1030c47-6df4-4160-bff7-932a9bf8b78d)

### Example #2: Military Base Address
![f1556048-a389-4d65-b5d2-bd15c7928bba.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/67ecd1f8-7ead-4374-8a60-2b587daa47af)

### Example #3: International Address
![9ffa8900-5106-4929-87ea-5830708214c9.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/45888d3a-0846-4563-a488-9ed47ffb2f04)

**Comment by bessgreen** [comment]
hi @bridgethapner, a few questions about how the saved addresses should appear on the Personal Information page (AC #2). I tried playing around w/ the test user accounts in staging environment, but wasn't having luck saving the addresses to see what they'd look like on the personal info summary page - I kept running into error states on the edit screen. 


**For Military Base addresses**, does the screenshot below reflect how this address should display on the Personal Info page? More specifically: 
- should State be spelled out (as shown), or should it just display the AP abbreviation?
- should there be a comma separating State from Zip code?
- Regardless of the type of address: when there are multiple Street Address Lines, should these be grouped together and separated by commas (as shown), or should each Line appear on a new row? 
![Screen Shot 2020-10-23 at 9.27.53 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9ea0aad7-b015-445d-b0fe-a600db4c3e97)


**For international addresses:**
- should the Country be listed on its own line below the City/State/Postal Code, as shown below? (also want to confirm that if we _are_ displaying the Country, we are only doing so with International addresses: the Country should not display for U.S. or Military Base addresses)
![Screen Shot 2020-10-23 at 9.32.05 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9ffa8900-5106-4929-87ea-5830708214c9)

**Comment by bridgethapner** [comment]
Hi there @bessgreen -- I am unfortunately experiencing the same saving issue on staging. I have a touch base with the Profile team tomorrow & can ask them these questions then. They may have insight on some but not all of these Qs, so below I put my thoughts too - **I'll double-check these with the Profile team tomorrow & post a final reply here**. 

**For Military Base Addresses:**
- Display only the state abbreviation
- No comma separating state from the zip code
- When there are multiple Street Address Lines, separate by commas

**For international addresses:**
- Yes, the country should be on its own line
- No, we don't need to display country for Military Base or Domestic addresses

**Comment by bridgethapner** [comment]
@bessgreen Circling back on this, sorry for the delayed response! I was editing my last comment to finalize responses but realized it'd be easier to leave a new comment. I was able to temporarily save some addresses in staging this week and found the following:

### For Military Base Addresses:
1. Display the full state (e.g. "Armed Forces Europe (AE)")
2. No comma separating state from the zip code
3. When there are multiple Street Address Lines, separate by commas

Example: 
![Screen Shot 2020-11-03 at 3.33.49 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/f1556048-a389-4d65-b5d2-bd15c7928bba)

### For international addresses:
- Yes, the country should be on its own line
- No, we don't need to display country for Military Base or Domestic addresses

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**12/07**

Currently, having issues with the backend? Will retest once resolved

**Comment by digitalken** [comment]
PASS 1/20/2021 - Saved US, International and military addresses.
