### ISSUE TITLE
Redirect Request: Sign-in FAQ

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#15229]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
The content from the sign-in FAQ page is being brought over to Resources and support, so we are retiring this page. 

### Requestor team info
Public websites: Beth Potts

### Implementation date
Date new URL(s) will be live: R&S is scheduled to launch on 11/4. 

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : I'd like to make sure R&S is stable and there are no issues before putting the redirect in place. So please implement the redirect on 11/6.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
www.va.gov/sign-in-faq/ | ~www.va.gov/resources/signing-in-to-va-gov/~ https://www.va.gov/resources/signing-in-to-vagov/
www.vets.gov/faq/ | *Update existing redirect to* <br> ~www.va.gov/resources/signing-in-to-va-gov/~ https://www.va.gov/resources/signing-in-to-vagov/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@bethpottsVADEPO We will need the actual user facing URL for the redirect.   I also added an old vets.gov URL that is currently redirected to that page that will need to be updated.  Can you please update with the new url and send back to me?  Thank you!

**Comment by bethpottsVADEPO** [comment]
Updated with the URL! @mnorthuis

**Comment by mnorthuis** [comment]
Redirect is vetted and ready to go when your team is.

**Comment by lunascoop** [comment]
Hi @bethpottsVADEPO can you let me know the appropriate stakeholder to notify for these redirect updates? Thanks

**Comment by bethpottsVADEPO** [comment]
No need to send out your usual email for this one. I've already contacted all the relevant SMEs. Thanks for asking @lunascoop!

**Comment by bethpottsVADEPO** [comment]
@mnorthuis Resources and support isn't quite stable enough to start linking to, so I'd like to **hold off on the redirect** until at least Monday. @ncksllvn @kelsonic do you have a ticket already for this work, and if so, can you update it to hold off on this redirect until Monday? I couldn't find your ticket.

**Comment by bethpottsVADEPO** [comment]
OK, after Nick's last bug fix for R&S goes out with today's deployment, we should be ready to implement this redirect, so I'm pushing this to Tuesday (tomorrow). @mnorthuis is the ticket already created for Nick/Kelson for the redirect?

**Comment by ncksllvn** [comment]
I just assigned myself to this and added our labels plus moved it to In Progress so I don't forget it. cc @brianalloyd IDK if there was an implementation ticket separate from this one but it doesn't matter to me.

**Comment by brianalloyd** [comment]
@ncksllvn sounds good, moved into this Sprint in support.  FYI, no separate implementation ticket outside of this, sounds like one is not needed.  Thanks for working the details.

**Comment by mnorthuis** [comment]
@bethpotts @brianalloyd This appears to be complete, can you confirm?

**Comment by bethpottsVADEPO** [comment]
Closing.
