### ISSUE TITLE
FE bug: Hide alert component when value is "None" - learning center

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15232]
## FE bug: Hide alert component when value is "None" - learning center

For all learning center templates (homepage, landing pages, articles), when the CMS alert component value equals` "None"` do not render any alert on the FE. 

**Screenshot of CMS alert field:** 

https://dsva.slack.com/files/UCV8RHP8R/F01D7HXAAUT/image.png

**ETA:** 1.0.  (Let's sync on workaround if 1.0 is not manageable to fix in time.)

**Comment by brianalloyd** [comment]
@ncksllvn @kelsonic @youngfreezyVA please review and provide estimate, would like to fit into this sprint in support of MVP 1.0 as indicated.  Please advise on burn down capability and estimate then we can do a quick sync if needed.  Thanks.

**Comment by ncksllvn** [comment]
Seeing the "ghost alerts" here, http://preview-prod.vfs.va.gov/preview?nodeId=8520

**Comment by ncksllvn** [comment]
Is this happening for just the Step By Step layout, or all of them?

**Comment by jenniferlee-dsva** [comment]
Validated and closing
