### ISSUE TITLE
[FE] Connected Apps: Replace app list with App Directory Link

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#15235]
## Background
See Design ticket: [[Design] Connected Apps: Replace app list with App Directory Link #15234](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15234)

As we get closer to the Application Directory going live in the Learning Center, the plan is to replace the current list of apps that are now in the Profile under the connected apps section with a link to the app directory.

The goal is to launch when the Learning Center Launches in Early Nov.
When we get an exact date TJ Rice will let us know as well as provide the exact URL.

It looks like our URL is going to be:  http://www.va.gov/resources/find-apps-to-use
and the Target launch date looks to be the week of the 9th hopefully, but I can keep you in the loop on an exact date when we have it.

## Tasks
- [ ] Remove Connected Apps app list and replace with the app directory link.
- [ ] Review with Matt/Samara/TJ Rice

**Comment by Samara-Strauss** [comment]
@bethpotts the link mentioned above – http://www.va.gov/resources/find-apps-to-use — isn't working for me. Is that the correct link to the App directory? Is the app directory live?

**Comment by ricetj** [comment]
> @bethpotts the link mentioned above – http://www.va.gov/resources/find-apps-to-use — isn't working for me. Is that the correct link to the App directory? Is the app directory live?

@Samara-Strauss that will be correct url, but it will not be live until we finish some work on our end. We are shooting for the end of next week.

**Comment by Samara-Strauss** [comment]
Great, thanks for letting me know!

**Comment by mshea0606** [comment]
@sanlouise looks good!
