### ISSUE TITLE
EVSS base service does not use Common::Client::Errrors

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#15231]
[This sentry error](http://sentry.vfs.va.gov/organizations/vsp/issues/466/?environment=production&project=3&query=is%3Aunresolved+level%3Aerror&sort=priority&statsPeriod=14d) is for `Faraday::ClientError`.  

The `Common::Client::Base` (lib/common/client/base.rb) class captures these and turns them into `Common::Client::Errors::ParsingError` or `Common::Client::Errors::ClientError`.  The `EVSS::BaseService` does not inherit from that class or generate the same ClientError to be compatible with other error handling features we have.

We need to better handle `Faraday::ClientError` if we cannot inherit from `Common::Client::Base`.

**Comment by holdenhinkle** [comment]
NA
