### ISSUE TITLE
[Design] Connected Apps: Replace app list with App Directory Link

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#15234]
## Background
As we get closer to the Application Directory going live in the Learning Center, the plan is to replace the current list of apps that are now in the Profile under the connected apps section with a link to the app directory.

The goal is to launch when the Learning Center Launches in Early Nov.

When we get an exact date TJ Rice will let us know as well as provide the exact URL.

![image.png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/5f54c076-9667-4338-8f14-d2c10e631ded)

![image.png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/b7099915-4a92-48a0-b9f0-90f851d83e93)

## Tasks
- [ ] Create mock up of design with app directory link (instead of list of apps)
- [ ] Review with Matt/Samara/TJ Rice

**Comment by Samara-Strauss** [comment]
Can we get this into this sprint? Maybe after design exploration week for My VA.

**Comment by mshea0606** [comment]
I'll pull it into this sprint's objectives

**Comment by mshea0606** [comment]
Hey @callen2563, can you please add an estimate to this ticket when you get a chance?

**Comment by sanlouise** [comment]
@callen2563 We should also update the list under 'What other third-part apps can I connect to my profile' when the user has connected apps, but this should just be a copy update.

![image](https://user-images.githubusercontent.com/14869324/97186001-5ed43280-1766-11eb-92ad-725b75b8f705.png)

**Comment by tressaellen** [comment]
@peggygannon could you take a look at this and offer any suggestions?

For when a user does not have any connected apps, I suggest we remove the header 'Third-party apps you can connect to your profile' and just drop in a button there.

<img width="1126" alt="Screen Shot 2020-10-26 at 2 22 38 PM" src="https://user-images.githubusercontent.com/58752772/97212382-3142b580-1775-11eb-953a-a8821f2440b2.png">

For when a user does have connected apps, we can update the copy in the dropdown to something like this:

To see what apps are available to connect to your profile [visit the app directory].

<img width="1146" alt="Screen Shot 2020-10-26 at 2 21 45 PM" src="https://user-images.githubusercontent.com/58752772/97212415-3e5fa480-1775-11eb-965b-3240a7f020f5.png">

**Comment by Samara-Strauss** [comment]
For the state with no apps connected, we should communicate they have no apps connected. I realize we don't do that now, but I think we should make that a little bit more obvious. Then, we should also communicate they can use the apps directory to see what's available.

**Comment by peggygannon** [comment]
@tressaellen 
Here's my content recommendation for these two states. For the "no apps" connected. I offer two options--one with a link to parallel the treatment for "apps connected" ; the other with the button.

1. no connected apps

A. You don’t have any third-party apps connected to your profile. To find out what apps are available to connect to your profile, [go to the app directory]. 

B. You don’t have any third-party apps connected to your profile. Go to the app directory to find out what apps are available to connect to your profile.
{button} Go to app directory


------

2. Apps connected

To find out what other third-party apps are available to connect to your profile, [go to the app directory].

**Comment by mshea0606** [comment]
@tressaellen @callen2563 can you drop an estimate in this ticket? Thanks

**Comment by tressaellen** [comment]
I think we should go with the button option.

<img width="1162" alt="Screen Shot 2020-10-28 at 2 31 30 PM" src="https://user-images.githubusercontent.com/58752772/97480898-e2c62000-1908-11eb-9508-1cdb166ac921.png">
