### ISSUE TITLE
Bug: Fix wrong date field logic on the `Form last updated` field - Find a VA form

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15241]
## Bug: Fix wrong date field logic on the `Form last updated` field - Find a VA form

**See attached for full description** - sorry it's a PDF; og slacked it to the lighthouse team as we don't have access to their board. Michael Bastos says this is an update to the FE template, not API. 
[https://app.zenhub.com/files/133843125/b8bb129a-0203-48c3-9585-0b1559514be0/download](https://app.zenhub.com/files/133843125/b8bb129a-0203-48c3-9585-0b1559514be0/download)

**Summary:** 
Similar to the logic for the field on the form detail pages, the `Form last updated` field must look at both Issue Date and Revision Date fields from the VA forms DB, and apply logic to display the most recent date. (It will not always be the Revision Date field due to many cases of human errors upstream.)

**Acceptance Criteria:** 
The value displayed in the 'Form Last Updated' on the Find a VA Form Search results will reflect the most recent value when comparing the Issue Date to Revision Date in the VA forms database.  Please see below.  

![image](https://user-images.githubusercontent.com/73354907/100284623-6e998f00-2f3d-11eb-97ea-1fbc999f4d2d.png)

**Comment by zacharymorel** [comment]
Self note; add more e2e testing for UI.

**Comment by MarciMcGuireGCIO** [comment]
Bumping to Sprint 37 as Zach is OOO with new baby!

**Comment by MarciMcGuireGCIO** [comment]
Removed this as a blocker to https://github.com/department-of-veterans-affairs/va.gov-team/issues/14112 since these two can be worked in parallel.

**Comment by MarciMcGuireGCIO** [comment]
This can probably be deployed ahead of everything else in https://github.com/department-of-veterans-affairs/va.gov-team/issues/10758 since it's a bug fix and pretty standalone.

**Comment by zacharymorel** [comment]
Validated on 12/28/2020

https://www.va.gov/find-forms/?q=10-0137

![Screen Shot 2020-12-28 at 11 07 52 AM](https://user-images.githubusercontent.com/26075258/103227733-0d2e5c80-48fd-11eb-9424-48f38a4f1cc4.png)
