### ISSUE TITLE
Design Feedback - Usability Testing Prep: GI Bill Comparison Tool - Ratings

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#15242]
I love this!

- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

**Must:**
- None

**Should:**

There is no hover state on the review accordions. It would be a good idea to add one, consider reviewing the design.va.gov accordions for some ideas
Remove the “$” when showing a %. Eg. “Tuition:$100% in-state”
Right align percentages. Eg. currently on the expanded ratings they are left aligned.

**Consider:**

- None

**Definition of Done:**
- [x] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Allison will close the ticket once those things are all set. Thank you!

**Comment by amyknox** [comment]
Thanks @allison0034 - we'll take a look at the "shoulds" and work on incorporating them
