### ISSUE TITLE
VSP content review - Usability prep - Medallia tool 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#15240]
User story
This ticket captures VSP content feedback on Medallia survey tool. 

Prototype link:  https://staging.va.gov/find-locations/facility/vha_691

Acceptance criteria
 - [x] VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
 - [ ] Teams leaves comments about any feedback they decide not to take
- [ ]  Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
@joanneesteban 

Do we have any say in the opening content? If so, I recommend this for the first screen to set up the content. 

1. **Thank you for visiting our website**
We want you to let us know what you think. You've been randomly selected to participate in a brief customer satisfaction survey. Let us know how we can improve your experience.

2. what does the ? at the bottom left of the screen do? It doesn't go anywhere when I click on it. 

3. should the "Provide feedback" button come first? 

4. I think the "Not right now"  button should be more descriptive.. Recommend "No. I don't want to provide feedback"

5. The options under "Why did you select that rating? (Select all that apply) " don't apply if the user selects "Very bad" or "somewhat bad" in the question above. 

6. Recommend rewriting this question  "Please rate how understandable this site's information is" TO
"Please rate how easily you understood the information on the site" 

7. Recommend rewriting this questions "How did this interaction change your trust in Veterans Affairs?" TO
"How did your experience today affect your trust in Veterans Affairs?"

8. Recommend making Submit button more descriptive "Submit feedback"

**Comment by joanneesteban** [comment]
Thanks, @peggygannon ! Question about the button feedback - would expanding the text in those buttons make it less usable? 

We can change the opening content copy to this. I wanted to also check in on if the copy should be the suggestions above vs. the suggestions from our [first content request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13084).

**Comment by peggygannon** [comment]
Hi, @joanneesteban 

Ah, thank you for letting me know that Amy already provided recommendations!  I think we can go with the original recommendation she provided, but please 

- remove the period from this first sentence: 
Let us know what you think.

-----

Can you clarify your question about the buttons. Are you asking if making the text longer makes it less usable? 

My recommendation to update the content on "Not right now" button is to make sure users with assisted tech devices or cognitive issues  understand what this button is referring to.  My recommendation to change it to: "No. I don't want to provide feedback" is to enable the button content to stand on its own.

**Comment by peggygannon** [comment]
Hi, @joanneesteban do you have any additional questions about my feedback? If not, I was going to close this issue. thx.
