### ISSUE TITLE
Review and validate design in the FE (learning center)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15269]
## Review and validate design in the FE (learning center)

Review sample pages with completed FE and make sure that all the FE is rendering design correctly in IE and Chrome.

- **Sample step-by-step template:**
http://learningcenter.web.demo.ci.cms.va.gov/node/8434/
  - [x] IE
  - [ ] Chrome

- **Sample Multiple FAQs:**
http://learningcenter.web.demo.ci.cms.va.gov/node/8490/
  - [x] IE
  - [ ] Chrome

- **Sample single Q&A:**
http://learningcenter.web.demo.ci.cms.va.gov/node/8538/
  - [x] IE
  - [ ] Chrome

- **Sample About with a table:**
http://learningcenter.web.demo.ci.cms.va.gov/node/8427/
  - [x] IE
  - [ ] Chrome

- **LC homepage:**  http://learningcenter.web.demo.ci.cms.va.gov/resources/
  - [x] IE
  - [ ] Chrome

- **Sample category landing page:** http://learningcenter.web.demo.ci.cms.va.gov/taxonomy/term/283/
  - [x] IE
  - [ ] Chrome

- **Sample tag landing page:** http://learningcenter.web.demo.ci.cms.va.gov/taxonomy/term/292/
  - [x] IE
  - [ ] Chrome

@brianalloyd 
If we can't review all of these prior to Demo,  design review should be done during Demo UAT review as early as possible to give Nick and Kelson time to fix bugs before launch.

**Comment by andaleliz** [comment]
Exciting that we're to this point! A few questions:

- Are both desktop and mobile ready to be reviewed?
- How specific are we getting? E.g. if pixels are off between sections, do we capture that? I'd assume so but not sure where Tze/QA fits in and what they cover from a design perspective.  I haven't been asked to do a review like this before.
- If there is a specific date other than `asap` we can add to this, that'd be helpful.

@rtwell let me know how you'd like to divide this up.

**Comment by jenniferlee-dsva** [comment]
The new mobile table FE is not ready. Fareez is working on those, but it's a stretch for 1.0. So for 1.0, we should focus on being solid for the above listed pages.  

Regarding timing, it is so close to demo, we should do the design validation in the demo (October 28 Wed), ticket bugs, so that we can begin triaging and resolving the most critical things for launch (Nov 4) and less critical things in the sprint following launch. Thoughts @brianalloyd ?  I'm open to other suggestions. 

@andaleliz @rtwell - please be sure to add any design bugs to this[ LC bugs epic. ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15270undefined)

**Comment by jenniferlee-dsva** [comment]
@andaleliz - I replied above and in-line to your qs: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15269#issuecomment-716543763  

Thank you!

**Comment by brianalloyd** [comment]
Thanks @andaleliz and @jenniferlee-dsva concur on timing as stated above and am moving this into Sprint 33 for action, updating labels in support.   Concur with the approach to begin triaging and resolving (10/28-11/3) the most critical things for launch (11/4) and less critical things in the sprint following launch as we ramp up MVP 1.1 action items.  

Reposting: @andaleliz @rtwell - please be sure to add any design bugs to this[ LC bugs epic. ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15270undefined)

**Comment by andaleliz** [comment]
I briefly chatted with @tzelei, it sounds like this duplicates some of the efforts he normally does.  Ideally, I believe @rtwell and I will fill the gaps that his normal process doesn't cover, and figure out a way to document it so it's easy (and ideally consistent w/ previous efforts) for Tze + FE devs to understand.

When @rtwell is back, we should probably sync with Tze so we are all on the same page.

**Comment by jenniferlee-dsva** [comment]
Updated the og ticket with demo URLs. Note: still waiting for a couple of pr's to get merged - so demo not ready until tomorrow

**Comment by andaleliz** [comment]
@jenniferlee-dsva the URL for `about with a table` isn't working for me. Can you confirm that's the correct URL I should be reviewing? Thanks!
http://learningcenter.web.demo.ci.cms.va.gov/node/8427/

**Comment by andaleliz** [comment]
Completed review w/ exception of `about with a table` and `multiple FAQ` - awaiting feedback. Created 4 issues so far, IE specific, cc @tzelei 

#15504 
#15503 
#15488 
#15501

**Comment by andaleliz** [comment]
The Multiple FAQ template in the mural board doesn't appear to have the latest bread layers, but I think the middle (stack of accordions) would still apply.  

However, Nick told me that the accordion view for Multiple FAQ is optional now and that page linked above is set to false.  Apparently there aren't any Multiple FAQs with accordions now.  I'm not sure how the page is supposed to look if it's set to false since there aren't any mock-ups for this - currently looks like an about page. I don't see anything off about it in IE.

If we want to review it w/ accordions, I think we'll need to assign something to a content person to create a page w/ accordions.

**Comment by tlei123** [comment]
> The Multiple FAQ template in the mural board doesn't appear to have the latest bread layers, but I think the middle (stack of accordions) would still apply.
> 
> However, Nick told me that the accordion view for Multiple FAQ is optional now and that page linked above is set to false. Apparently there aren't any Multiple FAQs with accordions now. I'm not sure how the page is supposed to look if it's set to false since there aren't any mock-ups for this - currently looks like an about page. I don't see anything off about it in IE.
> 
> If we want to review it w/ accordions, I think we'll need to assign something to a content person to create a page w/ accordions.

No sweat, @andaleliz !  For MVP 1.0 at least, I'm only QA'ing the required items for each template.  @jenniferlee-dsva , feel free to ping me for a spot-check IF you do have a demo FAQs page w/ optional accordion(s).

**Comment by jenniferlee-dsva** [comment]
Replying to your Qs ^ @andaleliz :

The About with a table is showing for me: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/ea3ce1c7-41e6-4e12-b0bb-627aa1aadda6)

WRT multiple FAQs  - when the `display in accordion` checkbox is NOT checked, the question-answer text just appears like normal text - header (question) and text (answer). This feature isn't working in the demo, but you can see an example on any of our benefit hub page that has faqs as text. Like this: 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/ccedfe72-294d-403e-90b1-49eee7f791fc)![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/36cc54b3-1286-46aa-82ff-e847df1c5447)

**Comment by andaleliz** [comment]
Hmm, when I try to hit that `about with a table` page, I see an internal server error. It also happens in Chrome... I'm not sure what to make of that.  I also don't get any results if I search for "phone" or "phone numbers"
![image](https://user-images.githubusercontent.com/55992116/97486454-d609f200-1931-11eb-8c33-02f963c3158e.png)

I did click around quite a bit and didn't find any pages that resemble the screenshots you pasted or anything with a stack of accordions (though sounds like that should be expected).

**Comment by andaleliz** [comment]
I'm able to pull up the table page in prod, it looks okay there. Going to check this one off as completed in IE.

**Comment by andaleliz** [comment]
Beth just let me know there's a known bug: the multiple FAQ's don't show questions so that's not something we can review the design for right now. FYSA @rtwell 

Maybe we include a design review for that as part of the bug fix.

**Comment by andaleliz** [comment]
I can see the FAQs! Hooray!

The only issue I see with the multiple FAQs is that the heading level order is skipped; opened https://github.com/department-of-veterans-affairs/va.gov-team/issues/15619 cc @tlei123 @jenstrickland

**Comment by jenstrickland** [comment]
Yep, agree with @andaleliz — the questions are coded as `h3`, when they are only preceded by an `h1`. They should be `h2` with a utility class to style them as `h3`. This would be a 508-defect-2 issue, and need to be [remediated in 1-2 sprints post-launch](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2). I'm not sure if y'all want to update the ticket y'all wrote, or if you'd like me to adjust it.

**Comment by brianalloyd** [comment]
Closing per grooming discussion. Comments in individual tickets.
