### ISSUE TITLE
Usability Testing Prep - Medallia - IA Feedback

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#15268]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This issue describes IA feedback

**SHOULD**
_Intercept survey:_
- The second question is a follow up to the response of question 1, however, all of the responses to question 2 are positive experiences.  If a user indicated that their experience was bad in the first question, none of the answers in 2 are appropriate.   Question 2 should be clarified/revised.
- In question 4, clarify what "interaction" you are referring to - was it generally "this visit to va.gov" or is this triggered from a specific interaction that can be named?

_Feedback survey:_
- the rating numbers should have more spacing for tapping

**CONSIDER**
_Intercept survey:_
- There is a small question mark icon in the lower left corner of the opening modal, but you cannot currently interact with it.  It is small, but the modal has very little content, so it is noticeable.  Is it intended to link somewhere or show something?  Add a label or intended interaction for test. 

_Feedback survey:_
- Consider adding a heading to the modal
- Consider reversing the order of the first 2 questions - the user can then indicate what their task was, then indicate if they were able to complete it.  

## Definition of Done
- [ ] Must feedback is implemented on staging
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by jwoodman5** [comment]
Created a new ticket for the recommendations [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24407), which will be addressed at a future date. Closing this ticket as the purposes of the review are completed and there are no *must* do items.
