### ISSUE TITLE
Bug: Wrong font color in intro text discharge upgrade tool page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15267]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_
On this page https://www.va.gov/discharge-upgrade-instructions/  - the intro text font is blue, and it should be using the normal design system black font color. 

Screenshot: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/f01b35f7-a52a-4745-b1bb-6abdd02cb389)

@brianalloyd & @DanielleThierryUSDSVA - I'm not sure which team this goes to, as it is part of the authenticated tool landing page. I believe it's our team, because this is still unauth page. 

Not urgent.

**Comment by brianalloyd** [comment]
I believe it is ours @jenniferlee-dsva, updated labels and can work this in through planning efforts and burn down forward.

**Comment by brianalloyd** [comment]
Resolved, closing in support
