### ISSUE TITLE
Related information FE not matching design (learning center)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15272]
## Related information FE not matching design (learning center)

See Slack thread with comments from Liz and Ryan: https://dsva.slack.com/archives/C0173CAJ7A6/p1603308402414800?thread_ts=1603306717.408100&cid=C0173CAJ7A6

**Example - on this node: http://preview-prod.vfs.va.gov/preview?nodeId=8520**  

Screenshot:
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/98a67339-62cf-4143-928f-b5ebaa028615)

**Component should appear in this order and styling:** 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/59ca6d93-cac7-4be4-a8f7-07fc97c9d891)

**Comment by jenniferlee-dsva** [comment]
@andaleliz for design SME input

**Comment by andaleliz** [comment]
Yes, the second screenshot shows the latest design. The `need more help` text should be in an `h2` element with a class applied to give it the styling of our h3s.

Happy to provide additional input if there are any specific questions.

**Comment by kelsonic** [comment]
Related PR merged, moving to validate

**Comment by jenniferlee-dsva** [comment]
I think the gray also extends full width. (In @rtwell  designs)

**Comment by kelsonic** [comment]
Ah that's going to be really difficult to achieve since we would have to have that be scoped outside of the template container even though the `Last updated` underneath it needs to be container width and not full width to be consistent with our other pages on the site 🤔

**Comment by andaleliz** [comment]
Oh interesting.  How could we have identified that as a high LOE earlier in this process?

**Comment by kelsonic** [comment]
I could have looked at it earlier but we have a lot going on atm lol other than that not sure, wouldn't have really seen it until i got to implementation

**Comment by andaleliz** [comment]
🙂  got it! Just wondering if there was anything design can do to help w/ this sort of thing in the future.

**Comment by jenniferlee-dsva** [comment]
We can ticket this and add to the LC bugs epic. We don't have to worry about this now for demo. It's not a launch blocker.

**Comment by jenniferlee-dsva** [comment]
Thank you @kelsonic

**Comment by brianalloyd** [comment]
Need to add new ticket to match Ryan's design elements as shown on mural board.  Work with Ryan and Kelson to complete.

**Comment by jenniferlee-dsva** [comment]
Per comment here https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15270#issuecomment-744752117

Let's move this remaining 1.0 bug ticket to 1.1 for tracking purposes (so we don't lose it and plan to pick it up in 2021).

**Comment by brianalloyd** [comment]
Validated, closing ticket in support.
