### ISSUE TITLE
Need more help component FE template bug (learning center)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15271]
## Need more help component FE template bug (learning center)

**User story:** 
When I try to call a help phone number listed in the `Need more help` section, I don't want to be confused by duplicate phone numbers showing in the list of phone numbers. 

**ETA:**
_We can schedule to fix this bug prior to launch while we're in Demo, if we need to buy time for completing the remaining templates and layers. I'm just capturing it now so we don't lose this._ 

**Description:**
Need more help component - dupes - showing. 

Examples on these 2 nodes 
http://preview-prod.vfs.va.gov/preview?nodeId=9275 and 
https://prod.cms.va.gov/node/8427

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/25ab0c4b-a0b0-4ada-9909-b84543f59485)

In the CMS, the default value for the VA 311 help desk is selected. Screenshot:
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/0fb47d11-c313-4b2b-9b8e-dfe5c1770d5d)

What should be showing in this section when the default value is selected - see example on this node: http://preview-prod.vfs.va.gov/preview?nodeId=8539

**Hypothesis**
What appears to be happening is that a hub that is selected for a DIFFERENT component (e.g., the **VA benefit** hub component) is bleeding into the` Need more help` component template. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/3f7532f1-4d57-4748-aa89-332d82f2116b)

**Comment by kelsonic** [comment]
Related PR was merged, moving to validate

**Comment by jenniferlee-dsva** [comment]
just validated in prod. works. TY @kelsonic ! Closing.
