### ISSUE TITLE
EDU Form Updates: Investigate Existing Artifacts

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#15286]
Explore GH to locate existing repos for each form - specifically looking for content docs, prototypes that can be salvaged & reused

**Comment by amyknox** [comment]
Form updates sheet Darrell created: 
https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/PI%20Planning%20%26%20Prod%20Release/PI8%20[20201005%20-%20202101XX]/FormsUpdates.xlsx?d=w12cbdc972a0f429897bb6d8e9b3ca31c&csf=1&web=1&e=A5B3sG

**Comment by amyknox** [comment]
Print layout / additional content
- [ ] Respond to questions in spreadsheet for 22-1995
- [ ] Respond to questions in spreadsheet for 22-0994 after 22-1995
- [ ] Prioritize confirmation page Print layout - 22-0994 ... Identify any content that doesn't need to display in the confirmation page.

22-1995 Printer-friendly confirmation, to use as a model:
![Screen Shot 2020-10-20 at 2.08.15 PM.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/8bcf3a93-2663-4592-be3e-ad12abc0b526)
