### ISSUE TITLE
Design - Account for VVC Store_Forward appts

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#15294]
Store_Forward appointments should display similarly to other in-person VA appointments because the Veteran must go into the VA facility. 
The Veteran would likely just have pictures or videos taken and then those would be transmitted to another doc for review. 

Need to confirm 'what' else needs to be displayed as part of these appointments.

**Comment by laurenernest** [comment]
@jbalboni Can you drop screenshots of this kind of appointment from homepage refresh detail pages?

**Comment by jbalboni** [comment]
@laurenernest We don't have any special handling around STORE_FORWARD, so it just displays as a video appointment with no link:

![Screen Shot 2021-06-24 at 9 56 13 AM](https://user-images.githubusercontent.com/634932/123275608-779e0f00-d4d2-11eb-95cd-a737a07e904e.png)

**Comment by laurenernest** [comment]
@jbalboni I switched this ticket from design to dev and copied over some of the description from your PR.

**Comment by laurenernest** [comment]
@jbalboni can you drop a screenshot of what it looks like now?

**Comment by jbalboni** [comment]
@laurenernest 
![Screen Shot 2021-07-14 at 4 53 30 PM](https://user-images.githubusercontent.com/634932/125691460-113ebea3-624d-40e2-9796-e71d65792f34.png)
