### ISSUE TITLE
Transformers add "public://" prefix to download URLs

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#15298]
Pages with download links such as pittsburgh-health-care/about/index.html have a  "public://" prefix added to all download URLs.

This appears to be getting added somewhere in our code, since the prefix is not present in the exported data:
```
❯ find . -name "media*.json" -exec grep "public" {} \; -print
            "value": "notification-accepted-publication-presentation8-2017.pdf"
./media.aa8ef157-4a52-44c0-8487-1106865ce72d.json
            "value": "guidance-notification-publications-research-publicity.pdf"
./media.88072d95-c98e-4b5b-b81b-bc8318b49e20.json
```

## Tasks
- [ ] Identify the source of the `public://` download prefixes and eliminate. The correct format for the download URLs is `/files/<path/to/file>`.

## Acceptance criteria
- [ ] No diffs are found between graphql and cms-export output due to the incorrect `public` prefix.

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/14770.
