### ISSUE TITLE
v2 - VAOS Analytics

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#15291]
# Stakeholder input
## Who is the target user?
- VAOS FE product team
- VAOS Product owner
- VAOS stakeholders

## High Level User Need / Problem / Opportunity
Now that we have baseline analytics tracking within VAOS app (as part of initial MVP rollout), we are doing a v2 of that tracking and the KPIs for the performance of VAOS as a product.

The end state should be a more 'real-time' Domo dashboard that includes links out to performance metrics specific to the app and also tracking of key features recently released. 

## Outcomes / how will we define success
- More users are looking at VAOS data beyond analytics report outs provided by VAOS product managers
- Define enterprise level analytics across the VAOS suite with stakeholders (not just VAOS app analytics)
- Shared data types between FE and VSP analytics on which data to use (user vs event)

## Supporting data we should consider (feedback, analytics)
- DOMO dashboard v1
- In progress DOMO dashboard v2 (using BigQuery)
- GA v3 Dashboard
- Conversion funnels

---
# Next iteration of Epic after initial Stakeholder input:

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## (Optional) Supporting Documentation
_Link to Additional Implementation artifacts- requirements based on policy, data, system-related needs_

## Team Documentation Update
[ ] [VAOS Analytics Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/%5Bdraft%5Dvaos-analytics-definitions.md)

## Issues to create within this Epic

```
- If discovery needed, create Discovery/Research Epic
- If no discovery needed, break epic into corresponding stories and tasks
```

## How to configure this issue
- [ ] **Labeled with `roadmapVAOSR` and `vaos`**
- [ ] **Add Epic to VAOS-R Roadmap Project in Github - must do this in GH, not Zenhub**

**Comment by ldelacosta** [comment]
Closing out this epic. A new epic was created to track analytics work for Appointments team [Epic #57684](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/57684). cc: @JRRoof
