### ISSUE TITLE
Access for Paul Phillips

### ISSUE THREAD

**Issue by PaulPhillips-va** [department-of-veterans-affairs/va.gov-team#15295]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Paul Phillips
- Please Provide your email.
   > paul.phillips@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > IRIS/Team Orchid - Developer [ThoughtWorks]

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC89JnYzWUVwj39h/ZD4DZGpeo4qoRUK8kllaU/tWEfBnqmmKMbwTFZpZy2gkQeJip3sKONxs2i5tJfUXRvzPWX5S90okwczmY8qzR35NT4bNrHHukinScJa8KtI7yIesE3zcAxrXnsfQGC+Ajmv1nH8dsSNNp/BBvx/NQQgDhvWfuFZmPQSIBw5jKCUroC4TrJWTl25BFIbO9XFZjvxh0n+PDNDdAXEg/vrd3LLNh97yVbFupB2TF/PIba+2Cie9pTH6I6pt1S9ABM4dRvOzwRHY8BnSvulDCTsnaaPNqYvuf+0MDSdlm2if/xwumJhN5SrEuRjaMLA3OHAwRr/Ofn paul.phillips@thoughtworks.com
```

- Grant AWS Console access?
  > NO

**Comment by pnwstevan** [comment]
Hi @PaulPhillips-va !

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

**Comment by PaulPhillips-va** [comment]
Now requesting AWS Console access

**Comment by jbritt1** [comment]
### For AWS Access
User: Paul Phillips
COR: Cecilia Lee
Approval Needed: @drorva, @mchelen-gov, or @thepipster

**Comment by drorva** [comment]
Email sent to CORS awaiting confirmation.

**Comment by drorva** [comment]
Approved

**Comment by jbritt1** [comment]
Temporary credentials provided to user at this time.
