### ISSUE TITLE
Provide facility IDs for all facilities 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15309]
## Provide facility IDs for all facilities 

This is related to future Cerner roll outs. 

_User story: As a FE engineer, I need a complete set of all possible facility IDs, so I can create scalable flipper logic for future roll outs._ 

@lalexanderson-dsva - Kelson received the full list of facility names. TY! Could we also get the actual facility ID?  He says he'd like the full complete set of IDs, whether or not they are currently in the Cerner queue. 

Including @brianalloyd here to track for PW FE team. 

Updated Details Concerning anticipated release dates and facilities releases for 2021. 
![Screen Shot 2021-01-19 at 8 06 35 AM](https://user-images.githubusercontent.com/70410912/105065795-7ce6c180-5a3b-11eb-8693-be2e6088231a.png)
![Screen Shot 2021-01-19 at 9 31 08 AM](https://user-images.githubusercontent.com/70410912/105065806-807a4880-5a3b-11eb-9e88-e6d59efb29de.png)

**Comment by kelsonic** [comment]
Assigning myself for visibility 😃

**Comment by brianalloyd** [comment]
@lalexanderson-dsva reaching out to see if any progress on obtaining a complete facility ID list in support of Cerner assistance from the PW team.  Last known was the next facility release will be in January 2021, can you confirm?  Looking for any details as we plan future work support.  Thanks.

**Comment by brianalloyd** [comment]
Adding in @johnhashva to the ticket in support.  @lalexanderson-dsva any luck in obtaining a complete facility ID list in support of Cerner?  TIA.

**Comment by johnhashva** [comment]
@brianalloyd Will put in a calendar reminder to follow up with Lauren in early Jan.

**Comment by brianalloyd** [comment]
Adding in latest information from [Slack convo](https://dsva.slack.com/archives/C52CL1PKQ/p1611072261058400): 
```
Alaska VA: 463 
Boise, ID: 531
Portland, OR: 648
Puget Sound (Seattle WA): 663
Roseburg (Roseburg OR): 653
Walla Walla, WA: 687
White City, OR: 692
```

**Comment by brianalloyd** [comment]
@kelsonic Next facility ID's are listed here for Cerner.  Although I don't see Columbus which is the next full launch and will reach out to acquire in support.

**Comment by CoryTrimmUSDS** [comment]
Hey @brianalloyd - I replied in Slack, but for traceability - the Columbus, OH Facility ID is `757`. The PW team and others rolled out the Appointment functionality last year.

**Comment by kelsonic** [comment]
I think this can be closed since we've added the feature toggles + FE support already for the new facilities 🙂

**Comment by brianalloyd** [comment]
Good call @kelsonic closing now in support.
