### ISSUE TITLE
Sentry 10 Testing Environment

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#15302]
### The Problem
Our Sentry 10 deployment does not have any kind of testing environment. It currently serves `dev`, `staging`, `sandbox` & `prod` all from one EC2 instance. It's difficult to test new features (e.g. version upgrades) when they might break our production sentry reporting.

### Extra Context
- Sentry has a [built-in feature that supports multiple environments](https://docs.sentry.io/product/sentry-basics/environments/) and is a large reason why we went in the direction of having our main sentry deployment connect to all lower and prod environments ([slack discussion](https://dsva.slack.com/archives/CQHBJ5U06/p1600179180174000))
- We attempted to upgrade Sentry from 10.0.1 to 20.0.7 and accidentally took sentry 10 offline for 3 hours
  - the new sentry docker-compose.yml included a new nginx server that was returning `301` responses to our sentry clients, and those clients threw errors since they couldnt interpret that response code

### Work to be Done
- [x] Design what a lower sentry 10 environment would look like
- [x] Create new deployment config
- [x] Update sentry clients with new sentry DSN
- [x] Update route53 (terraform) with domains for new Sentry

**Comment by omgitsbillryan** [comment]
### Option 1: Review Instance Sentry Deployment
Create a new EC2 instance in the `vagov-staging` VPC (where review instances live) & update the `settings.yml` `Sentry.dsn` and the `nginx` `proxy_pass` locations to point to this new Sentry 10 deployment.

**Pros**
- simple to implement
- easy to understand
- low risk

**Cons**
- doesn't exactly mirror our production sentry 10 deployment WRT VPC and sentry clients

### Option 2: Weighted Route53 DNS
Create a new EC2 instance in parallel to the existing Sentry10 deployment & use Route53 with weighted DNS to route some small portion of traffic (e.g. 1/256). Specifically, the new Sentry10-parallel would be it's own brand new BRD deployment in the same VPC as our existing Sentry 10. This would also involve:

- a one-time copy of some sentry docker volumes to a new EBS volume in order to share the same sentry config and DSN private keys
- a separate Jenkins job that updates the route53 dns weights between Sentry10 & Sentry10-parallel
- each deployment would have their own DNS entry for browser traffic (e.g. `sentry.vfs.va.gov` & `sentry-secondary.vfs.va.gov`) but share the `sentry-internal.vfs.va.gov` DNS

**Pros**
- a test env that's as close as possible to production environment
- _might_ allow for:
  - blue / green deployments
  - reducing (or possibly eliminating) the ~1-2 minute downtime we currently incur between Sentry 10 deployments

**Cons**
- higher complexity, since new "Route53 weight" job would be 1st of it's kind
- high risk, since I don't fully know how 2 separate sentry deployments would behave when receiving weighted traffic

**Comment by jhouse-solvd** [comment]
All tasks completed, and PR linked for posterity. Thanks, Bill! Closing.
