### ISSUE TITLE
Tiny copy fixes needed in learning center 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15306]
## Tiny copy fixes needed in learning center

**Component:** 
Search bar

**Description:**
1/ The "All of VA.gov" radio button text should be "All VA.gov" 
2/ In article type superheads, "Step by step" should be "Step-by-step" -- with the hyphens

**ETA:**
Triaged at `Can do anytime` 

Mural mockup 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/4ab6bdfa-e6ac-40ca-a7e4-76a83db3e773)

**Comment by brianalloyd** [comment]
Validated, closing this ticket.
