### ISSUE TITLE
Analytics KPI dashboard request for IRIS Replacement/Contact Us

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/va.gov-team#15303]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- This is a follow up to the initial Analytics consult the team had re: Analytics Playbook and potential success metrics for IRIS replacement
- Some metrics exist on the GA - DAP instance for the existing IRIS [form](https://iris.custhelp.va.gov/). Following our previous meeting, would appreciate help in identifying if any baseline metrics can be derived from the existing GA tracking. 

- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Submit this ticket as an epic
- [ ] Add your team label to follow progress

### KPIs
[Team KPIs](add your team's KPIs here)

- Some initial KPIs that the team is thinking about include the below:
   - Percentage of successful submissions:  
   - Increase in mobile usage?
   - When submitted had the veteran chosen the correct query vs was it required to be rerouted internally?
   - CSAT score

The [link](https://docs.google.com/document/d/1BR3aDBM0c-xr1_QWnAvG9Wl1Sm7eZ39-LDaKQG5tgm8/edit?usp=sharing) to the complete list

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria
Issue 1 - Groom Analytics for [team]
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

Issue 2 - Draft PST Dashboard for [team]
- [ ] Draft dashboard on Domo
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team

**Comment by jonwehausen** [comment]
Thanks @rumyeahs ! Will be hearing from us shortly here

**Comment by joanneesteban** [comment]
KPI Clean Up
- Larger KPI for bullets 2 & 3 above: `Funnel completion/conversion`. The bullets & the additional metrics in the Google Doc will be segmented as part of this KPI. This should include the entry points.

Other background:
- Looking for a late Q1, early Q2 release. Currently only on Staging. Will probably be on Production in April. Current IRIS link: https://iris.custhelp.va.gov/app/ask
- Currently 3 different Oracle forms
- Link to existing IRIS/MHV-TS/GI Bill Reports: https://vaww.va.gov/IRISINFO/reports.asp - need VA.gov email

Action Item for Insights: 
- [ ] look into report above to see which metrics we can help the team glean
- [ ] research into if we can add GTM on top of current IRIS

**Larger KPI dashboarding follow up in Q1 2021.**

**Comment by rumyeahs** [comment]
Hi team, can I also request another investigation to be added to this card:
We have currently identified from code there are only a handful references to the existing IRIS homepage [here](https://iris.custhelp.va.gov/app/home).  We are leaning towards deprecating this in the new solution. Can you please provide if there are any usage stats for this homepage from GA tracking that can help with this decision? Things such as are people visiting the IRIS [Ask A Question page](https://iris.custhelp.va.gov/app/ask) from the homepage, how many users are visiting the homepage, is it significant, etc. 
Please let me know if more details are required. 
Thank you in advance

**Comment by joanneesteban** [comment]
IRIS replacement team is changing. Moving this ticket to blocked on the Platform Analytics side.
