### ISSUE TITLE
 investigation: prismic.ui in drupal content

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/va.gov-team#15315]
1. investigate all the "entities" that compose this page: http://localhost:3001/preview?nodeId=3014
2. https://prismic.io/ -> see if a headless cms / i18 service fits in

**Comment by brianalloyd** [comment]
@youngfreezyVA can you provide an estimate for this ticket?  TY

**Comment by youngfreezyVA** [comment]
> @youngfreezyVA can you provide an estimate for this ticket? TY

done!
