### ISSUE TITLE
Access for Hayley Evans

### ISSUE THREAD

**Issue by hie1** [department-of-veterans-affairs/va.gov-team#15312]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Hayley Evans
- Please Provide your email.
   > hayley.evans@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >VFS-CMS Team, Agile Six, UX Researcher and Designer

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDOq9r6uojQet38p0NPnULurvSNxRxehiURFyRA6dmnBo98l0gy6AKJkNxpQo4WUxXEtMrD5n4sRN0PLkNve+nQz+cd4YctzyfMh8Hv3GTqQ8DDNCp4ssin7jpTbqhwSgIKu+Kd5J73m3HKCCIwawVG4Z9lBU48ui/CSvN8626dmc/BoachHCrWsUEvKtIOCSSfknqcOG6Gcy5CiHpgdq+f7VRV6zRgQjUUs5XuahfhupKRYXNRDksSVe3BCF2OcNw+mUHw844ay+5jWRBuFCl0MnkAbuz0sHapZTOtRMmrJBIuL1x+lX1WKdeCP/D7vFO5ptFlup7Sot4ZhPWsF9n haley.evans-a@agile6-a21.lan
```

- Grant AWS Console access?
  > NO

**Comment by pnwstevan** [comment]
Hi @hie1! 

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.
