### ISSUE TITLE
Military Info Page - Screen Reader is not picking up the correct dates for the period of service 

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#15316]
## What Happened?
While using a screen reader, the period of service dates are being read as: "June 04 minus 1,993. July 10 minus 1,995" and "September 17 minus 1,997. December 31 minus 2002"

The expected readings should be: "June 04, 1993 to July 10, 1995" and "September 17, 1997 to December 31, 2002"

(NOTE:  I'm hearing the dates read correctly with iOS and VoiceOver. -Ken)

## Specs:
- Android Pixel 3 emulator
- With TalkBack enabled
- Any user

## Steps to Reproduce
- Enable TalkBack 
- In the military information page select any of the period of service elements

## Desired Behavior
- When selected, the dates should be read as: "June 04, 1993 to July 10, 1995" and "September 17, 1997 to December 31, 2002"

## Acceptance Criteria
- [ ] The screen reader will read out the period of service dates correctly 

## Bug Severity
- 4 - Low

## Linked Story
- Story #13896

## Screen Shot (s) and Additional Information
Showing the affected elements 

![Screen Reader Military Info Page.png](https://images.zenhubusercontent.com/5f7bb216620a259ab7e50d60/d45601c2-9c8b-499c-9f00-b3e6ba690c4d)

**Comment by esther-k** [comment]
**11/17 Update:**

Issue still persists on Android

**Comment by digitalken** [comment]
PASS 2/22/2021 - Now reading correctly without the 'minus' inserted.  closing.
