### ISSUE TITLE
User research for content creation for VA.gov tools and applications

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#15318]
## User story

As part of the non-technical discovery for the VSP automated content checker, we need to do research on how content is created for VA.gov tools and applications. 
The goal of this research is to get a better understanding of how teams create content, and to identify areas for improvement within the collaboration cycle and if it makes sense to have an automated content checker so teams can automate and fix the most common content errors earlier in the process. 

## Goal
To get a better understanding of product teams' process for creating and writing content for tools and applications. 

## Acceptance criteria

- [ ] Create research plan

 - [ ] Create list of research participants 

- [ ] Create conversation guide

- [x] Create list of questions for a survey for VSA UX designers and PMs to share and identify their what their current content workflow is for the tools and applications being created on VA.gov:
 
- [ ]  Conduct research sessions 

- [ ] Based on these surveys/interviews, do research synthesis and create hypothesis about  current process and pain points/gaps and all insights learned. 

- [ ] Create user journey maps to show how content is created for these 3 types of tools:  
     - VA.gov paper forms being modernized and migrated over to VA.gov   
     - New tool or application being built on VA.gov
     - Content iterations on an existing tool or application

- [ ]  Discovery Research readout. Identify where in the process of each workflow an automated content checked could be inserted

**Comment by shiragoodman** [comment]
hey @peggygannon - just a reminder to please link the survey questions and research participants to this ticket. Thank you!

**Comment by peggygannon** [comment]
**Survey questions**

1.	How do you determine the content needs for your tool or application? 

2.	Describe your process for writing and creating content for the following 3 types of tools. (Please provide as much detail as possible, including who writes the content if it's not a content team member)

a.	A VA.gov paper form that is being modernized and migrated over to VA.gov
b.	A brand-new tool or application being built on VA.gov
c.	Content iterations on an existing tool or application

3.	What current content resources do you refer to when creating the content? 

4.	What is your process for getting stakeholder approval on your content? 

5.	What are your current pain points around writing or creating content for tools/applications? 

**Product teams**
VAOS
VSA Auth Exp
VSA Benefits and memorials 1
VSA Benefits and memorials 2
Clipboard
eBenefits
caregiver 
BAH 
Facilities
IRIS

**Comment by shiragoodman** [comment]
thanks @peggygannon. I think this is a great start. VSP has a [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/research/planning-resources/vsp-research-plan-template.md) template that I think would be really helpful for us to complete in determining our approach. You and @allison0034 can work on completing it together. I also think this research could be useful for guiding content improvements to the collaboration cycle. Let me know what you think!

**Comment by peggygannon** [comment]
**11/13/2020 update** This work is being put on hold so we can focus on collaboration cycle improvements. Moving to icebox for time being.

**Comment by shiragoodman** [comment]
this ticket is no longer necessary due to the Sitewide CAIA team.
