### ISSUE TITLE
Update article rating component design (learning center)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15314]
## Update article rating component design (learning center)

**User story:**
As a Veteran, I want to be able to tell you that an article I looked at help or did not help my problem/question. 

**Related analytics implementation ticket:**
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13774

**Background:**
We changed our initial component language to use the Medallia approved text. However, because Medallia will not be ready to collect user responses, we need to pivot to using Foresee. 

Currently, the Foresee feedback ux uses stars and a submit button. This breaks our current component UX, so we want to rethink how to incorporate user feedback on articles. 

- EX: We don't want to use a submit button -- it will compete with  article CTA button(s) on the page. 
- We want to avoid using the sticky side tab Foresee UX because this can compete with dynamic sticky `back to top` experience on long articles. (And also bc we want it to be clear that we're asking for rating of THIS particular article, not the site or the section in general.)

[Slack thread - comments from Joanne](https://dsva.slack.com/archives/C52CL1PKQ/p1603741994026300?thread_ts=1603737957.022900&cid=C52CL1PKQ)

**Foresee rating design:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/037b3af9-a68d-476a-99aa-e50a684c7a13)

**Current component design:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/019827c4-8283-4a70-80d1-150022782477)

**Related 1.0 tickets for reference:** 
#14302 (FE)
#13774 (Analytics)

**Comment by andaleliz** [comment]
@joanneesteban and @kelsonic I didn't totally follow the slack thread referenced above. Possibly dumb questions but I'm not totally clear on design constraints using this ForeSee component. 

- Sounds like this will still work w/out the submit button, is that right?
- Can we stick with our existing design and send a "Bad" radio button selection as 1 star and a "Good" radio selection as 5 stars? If not, why not?
- Are there any design constraints or requirements I need to keep in mind as we re-think this UX?

**Comment by jenniferlee-dsva** [comment]
I removed the link to epic 2915 bc that's on the CMS team board. Oskana mentioned it's messing them up to see PW work there. Will create a 1.1 epic for PW so we can more easily track PW work.

**Comment by jenniferlee-dsva** [comment]
@andaleliz I can answer your question re: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15314#issuecomment-716898427

It's not about the backend, it's the design of the current foresee tab+modal UX and adapting it to our on-page component model. Would be easier to have a conversation.

**Comment by andaleliz** [comment]
Holding off on this for now, per [this slack thread](https://dsva.slack.com/archives/C1Q4294JJ/p1604330448053100)

![image](https://user-images.githubusercontent.com/55992116/98137525-15839180-1e90-11eb-9514-11181afc579b.png)

**Comment by jenniferlee-dsva** [comment]
This can go into the icebox until Medallia is ready.

**Comment by brianalloyd** [comment]
In talking with Analytics and Insights team yesterday, Medallia timeline is likely to be February/March timeframe.  Will keep Icebox until additional details are known.

**Comment by andaleliz** [comment]
Hey Brian, removing myself as assignee since I'm no longer on the team.  Will leave it to you as to whether or not this goes to Cassandra...

**Comment by jenniferlee-dsva** [comment]
Update from Chante - @brianalloyd: 

https://dsva.slack.com/archives/CNCEXNXK4/p1615404494006500?thread_ts=1615401516.006400&cid=CNCEXNXK4

>The accessibility issues were resolved this week and we are finally going live with our >pilot surveys. Now that this has happened we can start working through the backlog >of medallia requests....

**Comment by brianalloyd** [comment]
@jenniferlee-dsva is the design hardcoded?  Wanted to ask as ideas concerning a thumbs up/down approach Vs. radial button input was discussed internally but wanted to validate with you and gather thoughts and ideas.  CC @johnhashva 
![Screen Shot 2021-04-13 at 9 23 57 AM](https://user-images.githubusercontent.com/70410912/114770661-e7e92100-9d28-11eb-8a6f-633b8ad476c4.png)

**Comment by brianalloyd** [comment]
This work has been completed in separate ticket. Closing in support.
