### ISSUE TITLE
Update VA311 Phone Number in eBenefits Applications

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#15325]
## Description
The VA311 phone number is changing from 844-698-2311 to 800-698-2411. This change (note the ENTIRE number) is scheduled for October 31, 2020.  We will need to update this number in various areas across our eBenefits-owned applications including:
1. [686c-674 helper file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/686c-674/config/helpers.js#L55-L56)
1. [Rated Disabilities list component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/rated-disabilities/components/RatedDisabilityList.jsx#L43-L46)
1. [Rated Disabilities Total Rating States Component](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/rated-disabilities/components/TotalRatingStates.jsx#L23-L26)
1. [View Dependents helper file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/view-dependents/layouts/helpers.jsx#L16-L17)

## Considerations
- Along with updating the number, any file that doesn't use the [Telephone Component](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/telephone/) should be updated to use that as well. 
- Per [this slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1603718764492500) - Go live can either be 10/30 or 11/2 since the number will be ready to use by then, and the old number will still be active for some time. 

## Tasks
- [x] Update the VA311 number in all places listed above

## Acceptance Criteria
- [x] Phone number has been updated and pull request has been submitted

**Comment by jason-gcio** [comment]
I think we can close this?

**Comment by micahchiang** [comment]
Yup this can be closed.
