### ISSUE TITLE
CT Search Results: “$” displaying next to “Tuition” when there is no dollar amount

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#15329]
On the search results page, an estimated tuition value is displayed for institutions. If an institution does not have tuition value, a percentage is displayed instead. Currently, the “$” dollar sign is displayed even when there is no dollar amount.

Expected results: the dollar sign below should not display.

![image (1).png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/016a0120-3948-427b-ab67-5bc6d8d8700f)

**Comment by zurbergram** [comment]
When testing locally feature flag `gibct_school_ratings` should be enabled
https://github.com/department-of-veterans-affairs/vets-website/pull/14871

**Comment by delli-gatti-michael** [comment]
Local Testing complete

![Screen Shot 2020-11-05 at 2.36.11 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/5c00e2e3-f2ff-4690-830d-c1707a495389)

**Comment by delli-gatti-michael** [comment]
This is in Staging. Closing this issue
