### ISSUE TITLE
Build confirmed appointments list view

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1532]
## Story
As a veteran, I want to see a list of all of my confirmed upcoming appointments so that I can know which appointments I need to go to and when they are.

## AC
- [ ] Page available on staging, not on production
- [ ] List on page contains only confirmed future appointments
- [ ] Page conforms to latest mocks: https://adhoc.invisionapp.com/share/WATIINRHZ3F#/screens/379622474
- [ ] UX for view if someone has multiple confirmed upcoming appointments is confirmed with Ryan and integrated into this page
- [ ] Any equivalent business logic in existing VAOS app reviewed and risks documented in this ticket

![Screen Shot 2019-09-04 at 11 37 19 AM](https://user-images.githubusercontent.com/24251447/64274165-6f916b80-cf08-11e9-824d-6417baa2994e.png)

**Comment by jbalboni** [comment]
FYI, that screenshot is for the provider flow, for the type of care flow that we're building the heading is the type of care, rather than the provider name.
