### ISSUE TITLE
CT Ratings: Design Updates from Usability Testing Prep

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#15327]
Draft solution for on-hover state on rating mini-accordions. Review design.va.gov accordions for general design direction

While working on accordion solution, address this as relevant: 
- Right align percentages on expanded ratings accordions. They are left aligned.

**Comment by watersemma** [comment]
https://bahdigital.invisionapp.com/share/Q8IAFCYHFMD

- On hover or on click/tap, the background color of the mini accordion button should update to #F1F1F1
- The section separators are slightly longer now, accordion content is shifted down slightly to allow for breathing room with the added hover state.
