### ISSUE TITLE
CT: No space between "Tuition and fees per year" and "(Learn more)"

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#15324]
Steps to reproduce:
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/11929140
2. Expand the accordion for School costs and calendar 
3. Observe below

There should be a space, like School Calendar

![image.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/390e1fe9-f526-4a8c-bceb-d5f268893ae6)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14870

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-11-05 at 2.25.14 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/14479686-75ec-4552-b307-3384879d0c6d)

**Comment by sonntag-adam** [comment]
Merged. Testing passes QA in staging.
