### ISSUE TITLE
Implement the list table component 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15328]
## Issue Description
Implement the list table component design for responsive tables.

Mockups: https://zpl.io/2yrQGyw

Documentation draft: https://docs.google.com/document/d/1VcT8Wxx6WlmrlLyUGaOUCG4tnbutOybZr_5cJJ6IuLo/edit?usp=sharing
---
## Tasks
- [ ] Implement list table component design
## Acceptance Criteria
- [ ] Development work for implementing the list table component
---

**Comment by bkjohnson** [comment]
Part of this work has been done in: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/492

Continued styling changes happening in: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/496

**Comment by caw310** [comment]
Closing as this is a duplicate.
