### ISSUE TITLE
Analytics Implementation or QA Support for [Bilby Lighthouse, end user experience  - App Directory]

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#15335]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

- Who is this request for?

    - Lighthouse and TJ Rice 
    _ @ricetj  _
    
- What team/project is this work for?
    _This is for VA Lighthouse API's End user experience team (Bilby)_
    
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. http://www.va.gov/resources/find-apps-to-use (this may be changing, but we think this is the url right now) _
    
    _No PII_
    
 
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - We would ideally like to launch mid November

- Typical Website Interactions to Track

    - Because is going to be a list of applications that a user can learn more about interactions would be great to track.
- Users visiting the page
- User clicking on the CTA link
- Users clicking the "Learn more" accordion to uncover more information about the different applications
- Users clicking the different TOS, Privacy policy, or report the app links
- users clicking the outbound links to the app's website _
   
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - User flow to how they got to the page and where they go after getting to the page

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - This is an unauthenticated page, anyone can access when live

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - This will live in the learning center, so we don't have a staging environment for this.

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by ricetj** [comment]
mock up for the app directory (content may change a little)
![Uploading image (9).png…]()

**Comment by jonwehausen** [comment]
Hi @ricetj , 

Thanks for your request here -- I have put a placeholder on the calendar for 11/12 at 1:00PM EST to discuss this request and KPI's here in more detail.

**Comment by ricetj** [comment]
> Hi @ricetj ,
> 
> Thanks for your request here -- I have put a placeholder on the calendar for 11/12 at 1:00PM EST to discuss this request and KPI's here in more detail.

@jonwehausen would it be ok to expand the scopes of the meeting to also cover another static page that is now live in the learning center? This one:https://www.va.gov/resources/connected-apps-faqs/

**Comment by ricetj** [comment]
Product outline
[VAExternal-2152183501-121120-1317-38.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5532449/VAExternal-2152183501-121120-1317-38.pdf)

**Comment by jonwehausen** [comment]
Hi @ricetj , 

Following our conversation today, here is the data layer specification we would like to propose to track some of the key interactions you identified: 

### Data Layer / Items to track
- @brianalloyd As for the items you drafted within the issue, here is the data layer specification we are proposing to track and measure the areas of content you have identified, we will want to connect with an FE to have this implemented.  
- Some of the items below are items that can be configured now in prep for 1.1

Description of Interaction | Screenshot of Interaction | Data Layer Specification
------------ | ------------- | -------------
Clicks on default button CTAs on `/resources` subpages |  ![image](https://user-images.githubusercontent.com/48527022/97979561-64043380-1d9d-11eb-80ae-626e5002d954.png) | `'event': 'cta-button-click',`<br>`'button-type': 'default',`<br>`'button-click-label': 'Get answers to connected apps' //dynamically populate with button text,`<br>`'button-background-color': //rgb code from css of button` (correlation with design system of [standardization ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14491) effort)
Clicks on page tags | ![image](https://user-images.githubusercontent.com/48527022/97980103-41bee580-1d9e-11eb-9f8f-f066b50cfb92.png) ![image](https://user-images.githubusercontent.com/48527022/97980922-85661f00-1d9f-11eb-8ce3-c81f80f236a1.png) | `'event': 'nav-page-tag-click',`<br>`'page-tag-click-label': 'Lorem impsum' //dynamically populate with tag text`<br>`'page-tag-category-label': 'Topics' //dynamically populate with category of tag`
Clicks on breadcrumb links | ![image](https://user-images.githubusercontent.com/48527022/97981319-16d59100-1da0-11eb-82ce-a0793a15f5ce.png) | `'event': 'nav-breadcrumb',`<br>`'breadcrumb-click-label': 'Resources and support' //dynamically populate with click label,`<br>`'breadcrumb-click-level': 2 //from LEFT TO RIGHT, level of the breadcrumb that is clicked`<br>`'breadcrumb-total-levels': 3 //total number of breadcrumbs in series (including one currently on)`<br>`'breadcrumb-mobile-first-enabled': true\|false //Boolean if the mobileFirst flag is used at time of click`
Clicks on additional info component [1.1] | ![image](https://user-images.githubusercontent.com/48527022/97981752-c27ee100-1da0-11eb-8e7e-bd5fedfc860b.png) | `'event': 'int-additionalInfo-expand' //or 'int-additionalInfo-collapse'`,<br>`'additionalInfo-click-label' //dynamically populate with click label`
Clicks on links within "Related information", "VA health", "Need more help?" section | ![image](https://user-images.githubusercontent.com/48527022/99002626-b6b2bd80-250a-11eb-8955-c36b2304d3f0.png) | `'event': 'nav-linkslist',`<br>`'links-list-header': //populate with blue header text (link),`<br>`'links-list-section-header': //dynamically populate with high level section, i.e "Related information"`

**Comment by jonwehausen** [comment]
@ricetj The data layer spec above should be good to go upon your FE's return -- Many of the items above mirror those identified [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196#issuecomment-721089451), I've left off the search tracking as I'll need to coordinate which development team that tracking should be allocated to.

**Comment by jonwehausen** [comment]
Last point here @ricetj -- Per our conversation today around the additionalInfo components executing API calls, let me know if there is another layer of API error tracking you all would like to implement here apart from the `expand|collapse` interaction tracking

**Comment by jonwehausen** [comment]
@bsmartin-ep Many of the items you staged in your workspace here https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382 should also cover us here...

Your JS config should be able to operate here as well and will QA when ready.

**Comment by ricetj** [comment]
@jonwehausen thanks for all of this. I will connect with our FE @LeKeve on this

**Comment by bsmartin-ep** [comment]
@jonwehausen / @bmcgrady-ep -

The workspace for #15196 has been updated to include the Design System changes for this (accordion, app stuff):

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382

Thoughts on using the event itself to split between new and old implementations?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382/variables/146

One thing I think we need to do is include _undefined_ for all these Event Action values so the SPLIT stuff works correctly in BigQuery.

This is a lot of changes, so please let me know if you have any questions.

**Comment by aparcel-va** [comment]
@wwanamaker

**Comment by ricetj** [comment]
@LeKeve has a PR for the analytics in the widget, but it looks like the public website will need to do the other parts of the analytics because they live in their templates. We're launching the app directory today around 4:00 pm est at this url: http://www.va.gov/resources/find-apps-you-can-use, but linking to the page won't happen until Monday.

@jonwehausen I think you said you needed to test the connections? So when it goes live it may be the best time for that.

**Comment by LeKeve** [comment]
PR has been merged. The following interactions are ready to be tracked:

- Clicks on the `Find app` secondary button CTA
- Clicks on additional info component

The remaining interactions will need to be implemented in the static template by the public websites team.

> Last point here @ricetj -- Per our conversation today around the additionalInfo components executing API calls, let me know if there is another layer of API error tracking you all would like to implement here apart from the `expand|collapse` interaction tracking

@jonwehausen The additionalInfo component is no longer executing API calls (all requests are being made on application load) so no further API error tracking will need to be implemented for that particular interaction.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Should `breadcrumb-click-level' and `breadcrumb-total-levels` be integers?

![image](https://user-images.githubusercontent.com/62304138/99884617-ae8b0a00-2bfd-11eb-88d3-d245b589395d.png)

Did you want the `#` in these color hexcodes?

![image](https://user-images.githubusercontent.com/62304138/99884653-e5f9b680-2bfd-11eb-9136-1f55e332afcb.png)

**Comment by joanneesteban** [comment]
Taking @bmcgrady-ep @jonwehausen off this ticket.

**Comment by joanneesteban** [comment]
@bsmartin-ep it looks like this ticket is back in our court. Please feel free to move this back into `in-progress` or `qa-vsp`

**Comment by bsmartin-ep** [comment]
Hi @LeKeve - sorry for the delay.

Would you be able to convert these values to integers?  It shouldn't delay our QA and publishing, but probably a good idea to convert these.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/15335#issuecomment-731618137

Thanks!

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep -

Please QA.  Thanks!

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382

**Comment by bmcgrady-ep** [comment]
### Data Layer QA

Description of Interaction | Data Layer Screenshot | Test Status
------------ | ------------- | -------------
Clicks on default button CTAs on /resources subpages AND clicks on "Find app" secondary button CTA's|![image](https://user-images.githubusercontent.com/66263904/100941698-4834a000-34b7-11eb-85af-c75505180b87.png)|✔️PASS
Clicks on page tags|![image](https://user-images.githubusercontent.com/66263904/100942339-6bac1a80-34b8-11eb-9c0e-a12304ab3b7b.png)|✔️PASS
Clicks on breadcrumb links|![image](https://user-images.githubusercontent.com/66263904/100942531-c8a7d080-34b8-11eb-8432-32f909cd7f8a.png)|❌NO PASS - `'breadcrumb-mobile-first-enabled'` not in the Data Layer
Clicks on additional info component|![image](https://user-images.githubusercontent.com/66263904/100942838-4cfa5380-34b9-11eb-823a-70bd1a381e9f.png)|✔️PASS
Clicks on links within "Related information", "VA health", "Need more help?" section|![image](https://user-images.githubusercontent.com/66263904/100943588-c47cb280-34ba-11eb-8a49-4db658c38fae.png)|✔️PASS
Clicks on accordions|![image](https://user-images.githubusercontent.com/66263904/100943919-68665e00-34bb-11eb-9d0a-06b8d8bb5e7c.png)|❌NO PASS - Old Data Layer still being passed with the event

cc @jonwehausen @bsmartin-ep

**Comment by LeKeve** [comment]
> Hi @LeKeve - sorry for the delay.
> 
> Would you be able to convert these values to integers? It shouldn't delay our QA and publishing, but probably a good idea to convert these.
> 
> [#15335 (comment)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15335#issuecomment-731618137)
> 
> Thanks!

Hi @bsmartin-ep! Those events are actually a part of the template that the Public Websites team owns. The interactions that I have control over are the `Clicks on breadcrumb links` and `Clicks on "Find app" secondary button CTA`. I believe the Public Websites team will have to adjust those values to integers.

**Comment by bmcgrady-ep** [comment]
Hi @LeKeve - Can you make a few changes to these dataLayer events? 
**Clicks on accordions**
```
'event': 'int-accordion-expand' //or 'int-accordion-collapse'
'accordion-section-heading': 'Connected apps FAQs'
'accordion-parent-label': //populate with the text of the accordion when a single-text accordion
'accordion-child-label': //populate with the text of the child label when a multi-text accordion, in this case, undefined
```
**Clicks on breadcrumb links**
This looks good, except that `'breadcrumb-mobile-first-enabled': true|false //Boolean if the mobileFirst flag is used at time of click` needs to be added to the dataLayer

**Comment by LeKeve** [comment]
@bmcgrady-ep That interaction is actually owned by the Public Websites team as well. I misspoke in my previous comment. The interactions that I have control over are the `clicks on "Find app" secondary button CTA's` and `Clicks on additional info component`. My apologies for the confusion.

**Comment by joanneesteban** [comment]
@LeKeve thanks for the info. Can your team reach out to the appropriate people in Public Websites to get this implemented?

**Comment by ricetj** [comment]
> @LeKeve thanks for the info. Can your team reach out to the appropriate people in Public Websites to get this implemented?

Hey hey @joanneesteban we chatted with them, but I think they don't have the time to take this on. If this is something you all need we really have no way of implementing it at all. I would recommend having a chat with the public website team to coordinate these changes. Feel free to close this ticket out as all the things we can implement are in place.

**Comment by joanneesteban** [comment]
Welcome back! If you're okay with not tracking those events, we can continue with the other data tracking. Otherwise, this is something that we'll need your team to coordinate on with the Public Websites team.

**Comment by joanneesteban** [comment]
@ricetj let us know if you'd like to proceed as is, or if we should wait until the Public Websites team can pull this coordination into their sprint!

**Comment by ricetj** [comment]
Hey @joanneesteban let's move forward as is for now.

**Comment by jonwehausen** [comment]
@bmcgrady-ep Can you provide an update here? Thanks in advance

**Comment by bmcgrady-ep** [comment]
@jonwehausen - I believe this is ready to be published out in GTM since we are moving forward as is for now.

**Comment by jonwehausen** [comment]
Thanks @bmcgrady-ep , I have published this out and closed. 

We are now collecting the app names along with the app categories. 

cc: @ricetj @joanneesteban
