### ISSUE TITLE
Document test user accounts for vets-api Docker

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#15341]
test user accounts are not documented for vets-api with docker:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/README.md
https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/running_natively.md

when running vets-api locally, can any of these test accounts be used?
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/Testing/TestAccounts.md

**Comment by gmaciolek** [comment]
@alexpappasoddball Checking in on this--is this something we can quickly update/clarify in our documentation?

**Comment by erluti** [comment]
Development data is essentially all mocked, so login doesn't really affect the data you'll see.  Any of those ID.me accounts can get through the login cycle, I use accounts listed [here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Login/MVI%20Integration/reference_documents/mvi_stagingUsers_fullList.csv).

Is there something specific you're having issues with?

**Comment by gmaciolek** [comment]
Update: I'm going to move this to the documentation backlog. I suspect that there's a lot that could be done to improve the experience of working with test user accounts and updated documentation would be a part of that.

We are also publishing updated environments documentation soon that should help clarify the relationship between development environments and live/mocked data/user accounts.

**Comment by lianilychee** [comment]
Closing.  Have updated documentation on these topics already, though they might need to be transformed for a smoother UX.
