### ISSUE TITLE
Discover and validate ideas for Collaboration Cycle improvements

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#15345]
## Issue Description
Various research sessions with VFS and VSP team have been held with regards to Collaboration Cycle pain points and overall feedback. Now the team needs to determine what potential solutions could be put in place to remedy those pain points. 

As a Collaboration Cycle team member, I want to identify potential solutions, validate their potential for scalability and assess their level of effort for implementation so that I can address identified pain points for VFS teams.

## Acceptance Criteria
- [x] Team has completed a rapid ideation session
- [x] Team has completed a rapid prototyping session
- [x] Potential solutions have been validated for scalability and LOE
- [x] Potential solutions address identified pain points
- [x] Team has decided what solutions to implement for work beginning next sprint
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
Ideation Workshop: https://docs.google.com/spreadsheets/d/1T9AzrVGtx-A3HAoIIdThaJ1qIw2dd-Nyqp6ST-JtCIw/edit#gid=0

Mural board: https://app.mural.co/t/vspproduct9990/m/vspproduct9990/1603955797675/c0c775268c29725b8797b8fee60f8912053619a4
