### ISSUE TITLE
Wrong dates - /outreach-and-events/events/leesburg-virginia-community-veterans-engagement-board/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15358]
## Issue Description
The wrong dates are being displayed

## Example:
![Screen Shot 2020-10-27 at 1.59.42 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/8afd228f-cd37-4ba3-9051-b6ed33f0e79b)

## Example File
`/outreach-and-events/events/leesburg-virginia-community-veterans-engagement-board/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.
- [ ] Fix the issue

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/14884.
