### ISSUE TITLE
Wrong date - /outreach-and-events/events/mst-ptsd-survivor-hear-me-see-me-empowered-advocate/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15359]
## Issue Description
Wrong date is being displayed

## Example:
![Screen Shot 2020-10-27 at 2.08.35 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/67eb1d12-8546-4a97-b014-940fdc757ddd)

## Example File
`/outreach-and-events/events/mst-ptsd-survivor-hear-me-see-me-empowered-advocate/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.
- [ ] Fix the issue

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/14884.
