### ISSUE TITLE
Missing metatags - /health-care/about-va-health-benefits/dental-care/dental-insurance/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15350]
## Issue Description
There are some metatags missing

## Example:
![Screen Shot 2020-10-27 at 1.13.09 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/6d464ff8-2395-46cd-86d1-1ec65b372ab6)

## Example File
`/health-care/about-va-health-benefits/dental-care/dental-insurance/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.
- [ ] Fix the issue

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/14891.
