### ISSUE TITLE
Missing section - /outreach-and-events/events/pave-connect-employer-session-windstream-communications/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15366]
## Issue Description
There is a missing section

## Example:
![Screen Shot 2020-10-27 at 2.44.38 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/584c3649-f35f-49b6-9a8a-27d79fb1652f)

## Example File
`/outreach-and-events/events/pave-connect-employer-session-windstream-communications/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.
- [ ] Fix the issue

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/14915.
