### ISSUE TITLE
[Bug] - va_treatment_facilities - treated_disability_names transformer error

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#15368]
Beginning research notes in https://github.com/department-of-veterans-affairs/va.gov-team/issues/15310

once https://github.com/department-of-veterans-affairs/va.gov-team/issues/17595 is complete we can look at this specfic issue.

# What's happening 
I would expect that all data that is sent to `v0/disability_compensation_forms/submit_all_claim` from the vets-website is valid, according to the [JSON Schema](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21-526EZ-ALLCLAIMS-schema.json) However, [in sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/417/events/bd3855dcc0824571909e9c887db8d1dc/?environment=production&project=3&statsPeriod=14d) we see validation errors. this issue is for one of many of those validation errors.  They affect 110 unique users per week. 

The most common error I'm seeing is `The property '#/vaTreatmentFacilities/0/treatedDisabilityNames' did not contain a minimum number of items 1 in schema`.  In an example I took a deep dive into, I saw that the Save in progress form did have treatedDisabilityNames but the posted form data to `v0/disability_compensation_forms/submit_all_claim` had `[]` for `treatedDisabilityNames`

## supporting example

from the rails console in prod `puts InProgressForm.find(2272307).form_data`
This is the in-progress form data (pre transformation)
````  
"va_treatment_facilities": [
    {
      "treatment_center_name": "James A Lovell",
      "treatment_date_range": {
        "from": "2015-02-XX"
      },
      "treatment_center_address": {
        "country": "USA",
        "city": "North Chicago",
        "state": "IL"
      },
      "treated_disability_names": {
        "condition 1, another condition, more, something, another medical thing": true
      }
    }
  ],
````

the value of treated_disability_names should be an array of strings, but is not.  I redacted the disability names, but you get the point.

[in the vets-api log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/dsva-vagov-prod$252Fsrv$252Fvets-api$252Fsrc$252Flog$252Fvets-api-server.log/log-events$3FfilterPattern$3D$257B+$2524.named_tags.request_id+$253D+$252279cfc9f1-27c9-4e58-a7ce-3cf6014fff31$2522+$257D$26start$3D1603803600000$26end$3D1603821600000), we see this is what is sent to the api -   an empty array.  
````
 "va_treatment_facilities": [
                        {
                            "treatment_center_name": "FILTERED",
                            "treatment_date_range": {
                                "from": "FILTERED"
                            },
                            "treatment_center_address": {
                                "country": "FILTERED",
                                "city": "FILTERED",
                                "state": "FILTERED"
                            },
                            "treated_disability_names": []
                        }
                    ],
````

**Comment by annaswims** [comment]
It's a backend issue.  The FE rejects treated_disability_names that aren't in the listed conditions.  Inflections is converting the key from `Shoulder-Rotator Cuff` to `shoulder_rotator cuff`

condition”:“Shoulder-Rotator Cuff”
“treated_disability_names”:{“shoulder_rotator cuff”:true}},

**Comment by annaswims** [comment]
to start troubleshooting take a look at this test. https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/request/in_progress_forms_request_spec.rb

**Comment by Mottie** [comment]
There is a more detailed discussion [in Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1606932092415400) discussing possible solutions. One of which is to remove the `'X-Key-Inflection': 'camel'` setting in the header to prevent this issue from happening in the future.

To deal with existing altered save-in-progress data, our team came up with a solution where we pass all `treated_disability_names` set to `true` on submission. This will include new disabilities that were deleted, and possible duplicates of the item that was altered. It's better to provide all the information instead of an empty array.

**Comment by Mottie** [comment]
I've merged in the FE work-around for this... it will now pass _all_ `treated_disability_names` that are set as `true` and alert the Veteran if there isn't a matching selection - hopefully this last part alerts Veterans that have attempted to submit the form in the past that there was a problem.

**Comment by edmangimelli** [comment]
This ticket has been superseded by 
#17595 (back-end ticket) (goes into full detail)
#17411 (front-end ticket)
