### ISSUE TITLE
Missing section - /outreach-and-events/events/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15369]
## Issue Description
There is a missing section

## Example:
![Screen Shot 2020-10-27 at 2.51.12 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/b25ee9e0-51ce-47a1-bfb9-ef0e825cd3e8)

## Example File
`/outreach-and-events/events/webcast-veterans-benefits-performance-and-results-for-fy-2020-fourth/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.
- [ ] Fix the issue

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/14915.
