### ISSUE TITLE
Wrong data - /outreach-and-events/events/past-events/page-2/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15365]
## Issue Description
There is wrong data being displayed

## Example:
![Screen Shot 2020-10-27 at 2.40.19 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/9d041a77-7ada-46e9-b788-4324c8c19403)

## Example File
`/outreach-and-events/events/past-events/page-2/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.
- [ ] Fix the issue

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/14914.
