### ISSUE TITLE
Wrong date - /outreach-and-events/events/past-events/page-10/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15363]
## Issue Description
The wrong date is being displayed

## Example:
![Screen Shot 2020-10-27 at 2.33.28 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/6dc5de04-43d6-4cab-94fb-2bd0463aede9)

## Example File
`/outreach-and-events/events/past-events/page-10/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.
- [ ] Fix the issue

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/14884.
