### ISSUE TITLE
Build Mobile Table FE template MVP 1.1

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15375]
## Issue Description
_New ticket, carry over task from MVP 1.0.  I want to begin building the FE mobile table template so that this component is successfully used on Resources and Support.  I referencing the original discover and build effort conducted during R&S MVP 1.0, synopsis of work effort is in ticket #14618_

## Front end tasks
- [ ]  Validate Estimate (Used initial ticket estimation)
- [ ] - Build Mobile Table FE Template
- [ ] - Ensure no CMS dependencies exist (Collaborate with CMS team)

## Acceptance Criteria
- [ ] Ensure layer of the FE mobile table is complete for the content type
- [ ] Make sure [any guidance from the original issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13963#issuecomment-698416821) for this work is taken into consideration
- [ ] Need to groom, review, estimate

## Planning Considerations 
Will apply Site wide (and to the About template)

**Comment by kelsonic** [comment]
@youngfreezyVA has an incoming PR for this (minus the additional info component due to technical constraints)

**Comment by jenniferlee-dsva** [comment]
I just checked one of our live RS table pages and here is the screenshot - this is mobile simulated on Chrome. One thing I noticed here which is not part of the table responsiveness ticket however is that the dynamic back to top didn't appear, though the page does appear to be longer than 2000 px. (I could be wrong.)  

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/2f993bfc-7f2d-4dd4-8496-c81e62084a38)

**Comment by jenniferlee-dsva** [comment]
Here is a validated table on a benefit hub page. Validated and closing. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/4add1793-8a0a-4991-b062-e4c2d2d0df5a)
