### ISSUE TITLE
Start at the beginning of the form without returnUrl

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#15383]
## Issue Description
To remove the need for the API to be aware of the front-end routing, the forms library should navigate the user to the first page of the form after a SiP call if the `returnUrl` is missing.

The way it is right now, the form profiles in the API use magic strings to send users to the first page of the forms. [Example.](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_profiles/va1990.rb#L8)

## Acceptance Criteria
- [ ] The forms library navigates to the first page of the form if the `returnUrl` is missing from the SiP call

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
