### ISSUE TITLE
Audit GA custom dashboards

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#15389]
## Issue Description
What do we know about the dashboarding that we've created for VFS teams to use during rollouts? To inform us of what types of metrics they look at.

---
## Tasks
- [ ] List links of available (ones that we can see publicly on Github/the ones that we made) GA custom dashboards

**Comment by bmcgrady-ep** [comment]
@joanneesteban Here is the [link](https://docs.google.com/spreadsheets/d/1fDZfG32SZqHpjWgByN84fIaTx1iho0-WQDdOK1m4_Ss/edit?usp=sharing) to the GA Dashboard Audit. Let me know what else you would like me to add.

**Comment by joanneesteban** [comment]
Thanks, Ben, for your work on this! Closing this ticket.
