### ISSUE TITLE
Contact Center Review for [VA Lighthouse API, End User Experience (Bilby) - App Directory]

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#15380]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The application directory is an unauthenticated page that will be housed in the learning center on Va.gov. The App Directory is connected to the work in Profile 2.0’s connected application section, that displays applications that a Veteran has connected their data too.

This directory is a list of applications that a veteran can connect their VA data with. It will include the application name, category of the app (ie health), a link to the app’s website, a CTA button that will take the user to the connected apss sign-in FAQ page, a learn more button that when clicked will expand a section that provides more information on the application. The additional information will be a description of the application, the application’s Terms of service, privacy policy, a report this app link, and the type of data the application could ask to collect if the users would want to connect to the application.
### Launch Date
*Please provide the launch or rollout date and details.*

### Product Guide
Have a document, but nowhere to store it. will try to attach after the ticket is created, but please advise. 

### Product Video
static page, no video 

Additional info:
 We are launching this product in the Resources & Support (formerly Learning Center). Happy to join on a call to talk through anything. 

## Acceptance Criteria
- [ ] VSP Analytics & Insights QA has been completed 
- [ ] VSP Analytics & Insights sends artifacts to appropriate contact centers
- [ ] VFS team completes brief VSP Collaboration Cycle Feedback survey [link](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before)

**Comment by ricetj** [comment]
[Application_Directory.Product.guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5447648/Application_Directory.Product.guide.docx)

**Comment by Kimberley2019** [comment]
Good Morning @ricetj  I have provided the launch details, description, and product guide to the VEO Contact Center. I have give them until 11/2/2020 to respond with any questions or feedback. If they do not respond by COB on that day, then we will move forward without their input. I will keep you posted with anything that they send our way concerning this product guide.

Also, do you have a launch date?

**Comment by ricetj** [comment]
> Good Morning @ricetj I have provided the launch details, description, and product guide to the VEO Contact Center. I have given them until 11/2/2020 to respond with any questions or feedback. If they do not respond by COB on that day, then we will move forward without their input. I will keep you posted with anything that they send our way concerning this product guide.
> 
> Also, do you have a launch date?

Hello @Kimberley2019 do please let me know if you need anything other information. Our target for launch right now is the week of the 16th, but that may change.

**Comment by Kimberley2019** [comment]
Good Morning @ricetj The VEO Contact Center has not provided any feedback to the product guide that was given to them.  This ticket is now closed.

**Comment by Kimberley2019** [comment]
@ricetj Just a quick follow up on this.  Is it still projected for the week of the 16th or has that changed?

**Comment by ricetj** [comment]
> @ricetj Just a quick follow up on this. Is it still projected for the week of the 16th or has that changed?

Hello @Kimberley2019 that is still the plan. We are shooting for the end of the week, but will let you know if that changes.

**Comment by wwanamaker** [comment]
Hi @Kimberley2019 , I'm following up on this as TJ is on leave. The feature was pushed into production and I wanted to make sure that the contact center is all set. Do they need anything else from us?

**Comment by Kimberley2019** [comment]
HI @wwanamaker I have not received any input from the VEO Contact Center regarding this feature.  I do not think that they need anything else, if they reach out, I will advise.
