### ISSUE TITLE
Investigate what broke design.va.gov

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#15400]
## Issue Description
I broke design.va.gov by either [removing `deploy_site.sh`](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/333) or [upgrading Jekyll](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/332). [This PR](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/334) reverted the changes and fixed the site. design.va.gov/components (and a few other pages) rendered unexpected HTML.

It's still unclear why this caused the break, but when I tested locally, I wasn't seeing the same thing as was on design.va.gov or staging-design.va.gov. We need to investigate this to figure out why either (or both) of those broke the site. Bonus points for figuring out how to reproduce the error locally.

**Comment by caw310** [comment]
We've since updated Jekyll so this isn't a problem.
