### ISSUE TITLE
Additional Info Component - Global Data Layer Implementation

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#1541]
## User Story
As a FE, I need to be able to embed dataLayer tracking into the [additional information](https://design.va.gov/components/additional-info) so I can automate tracking and give out-of-box insights anytime this component is used in the future. 

## Goal
- Establish and deploy the standard dataLayer for expands and collapses of the additional information component

## Acceptance Criteria
- [ ] Embed this code into the HTML code found in the [documentation](https://design.va.gov/components/additional-info). 
- [ ] Implement this dataLayer code anytime the expand of the dropdown is done. 
```
dataLayer.push({
   'event': 'nav-additionalInfo-expand'
});
```
- [ ] Implement this dataLayer code anytime the collapse of the dropdown is done. 
```
dataLayer.push({
   'event': 'nav-additionalInfo-collapse'
});
```
- [ ] Crawl the application for anywhere the component is used that DOES NOT currently have the profile navigation dataLayer push, and implement the dataLayer structure above.  

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
Hey @nedierecel @jonwehausen! So right now, our additional infos trigger events specific to its context. For example, the one on `/health-care`  triggers `nav-crisis-homelessness-expander`. It looks like it's also passing a property called `additional-info-expander-label` with the value of the button text - `We may be able to help`. Do we want to keep any of that? 

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/6538dbe4-9a7b-4e66-a2e9-7e8f4764ca4b)

**Comment by nedierecel** [comment]
@ncksllvn @jonwehausen 

When those were first created, we were looking on components on a case-by-case scale. However, with this particular use case: 

1. A business question that @jenniferlee-dsva may want to weigh in on - for homeless expanders, we currently track this as an Event Action of :`Crisis Modal Clicked - Homelessness`. Do we want to treat Homelessness interactions distinctly since they are a critical user interaction? If we are to update to global use, the new Event Action would be `Navigation - Accordion - Expand - We may be able to help`.

2. If we do keep them distinct, is it a technical block if we have an exception for the homelessness modals?

**Comment by ncksllvn** [comment]
@nedierecel We can definitely pass the event data into the dataLayer with some extra data indicating that it's a Homelessness additional info toggle, but just curious if we should change that `event` property from `nav-crisis-homelessness-expander` to that `nav-additionalInfo-expand'/collapse`

**Comment by nedierecel** [comment]
@ncksllvn For follow-up - I just noticed the use of the `data-analytics` attribute. Will the `nav-additionalInfo-expand` replace the `nav-crisis-homelessness-expander` attribute, or is it only in the dataLayer event?

**Comment by ncksllvn** [comment]
It looks like the event for the homelessness additional info ultimately looks like this -

```js
window.dataLayer.push({
    event:  'nav-crisis-homelessness-expander'
    'additional-info-expander-label': 'Additional Info - We may be able to help'
});
```

It seems like that to do the work in this ticket, we should update that to -

```js
window.dataLayer.push({
    event:  'nav-additionalInfo-expand'
    'additional-info-expander-label': 'Additional Info - We may be able to help'
});
```

But I'm not a GTM expert - maybe we should/can pass both events into the dataLayer?

**Comment by jonwehausen** [comment]
Hi Nick,

Yes, we would like to move forward with changing to be nav-additionalInfo-expand /collapse.

As far as the 'additional-info-expander-label' variable goes, we can regularly pull in the click text label OOB within GTM, so the most beneficial thing to pass here would be more like a keyword that would give product owners in the future the ability to output whatever tag verbiage they need. 

Since this one needed a "Homelessness" label, why don't we have this be the final push: 

```javascript
window.dataLayer.push({
    'event': 'nav-additionalInfo-expand', /collapse
    'additional-info-expander-label': 'Homelessness'
});
```

We understand this won't be the last time there is a need to have 1-off verbiage included within a global tag structure...so we can let the additional-info-expander-label serve as an optional verbiage customization moving forward.

**Comment by ncksllvn** [comment]
@jonwehausen For that `additional-info-expander-label` property, would it be okay to pull in the whole alert title like -

```js
window.dataLayer.push({
    'event': 'nav-additionalInfo-expand', /collapse
    'additional-info-expander-label': 'How do I get help if I'm homeless or at risk of becoming homeless?'
});
```

**Comment by jonwehausen** [comment]
That's fine too, we didn't want to create extra work for you all but that certainly makes things easier for us.

**Comment by jonwehausen** [comment]
Hi Nick, 

Just wanted to get an updated here -- saw you moved to Review/QA column, is this ready for QA? 

Thanks,
Jon Wehausen

**Comment by ncksllvn** [comment]
Hey @jonwehausen! Apologies for the delay. I just merged the design system updates to define these new events, and have a vets-website pull request open to begin using them. Before I merge the vets-website PR, I wanted to update you on what to expect from GTM. 

The new event is simply: 

```
window.dataLayer.push({ event: 'nav-additionalInfo-expand' })
```

However, the event is triggered by the full AdditionalInfo component instead of the button DOM element, so there are a couple data attributes you should be able to access -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/c255d8a1-8516-4bcc-956f-597c09a42cab)

Does this sound okay? If you're concerned, we can do a manual deployment to our Dev environment and test things there first before merging.

**Comment by jonwehausen** [comment]
Hi Nick, 

Can you give us an update on deployment status for this? 

Thank you sir.

**Comment by ncksllvn** [comment]
Apologies for taking forever on this. This is merged and should be in Staging in the next hour! LMK if you run into any issues grabbing the new attributes and I'll adjust.

**Comment by jonwehausen** [comment]
Thanks a lot for this @ncksllvn ! This is great!

@nedierecel, I've got [this workspace](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/689) setup to leverage the HTML attributes Nick has setup. 

I setup two global JS variables that can pull in the data-label and data-alert-box-title components. 

Let me know your thoughts. @ncksllvn we'll confirm when we're ready to move forward with this adjustment in prod. 

Thanks,
Jon

**Comment by ncksllvn** [comment]
Woohoo! Sounds great to me @jonwehausen!

**Comment by nedierecel** [comment]
Thanks @jonwehausen and @ncksllvn!

Jon, I'm receiving a `Conflict Found` error in GTM. Can you review and then I can QA?

**Comment by jonwehausen** [comment]
HI @nedierecel ,

Thanks for the notice. I have corrected this issue within the Additional Info workspace and is ready for your review.

**Comment by jonwehausen** [comment]
Thanks again @nedierecel!

@ncksllvn We have since published out the GTM functionality to support global additional info tracking. Your team can move forward with the production merge, looks like you guys already have. 

@jenniferlee-dsva Just to loop you in here -- wanted to make sure you and your team understood the homelessness component [here](https://www.va.gov/health-care/) will now be tracked according to this global paradigm moving forward. 

Thanks,
Jon Wehausen

**Comment by nedierecel** [comment]
@jonwehausen @ncksllvn Can we close this issue?

**Comment by Karak888** [comment]
@ncksllvn please let me know if we can close out in this sprint.  Thanks!!

**Comment by ncksllvn** [comment]
close it!

**Comment by Karak888** [comment]
you made my day @ncksllvn !!

**Comment by jonwehausen** [comment]
Yes, my apologies for not responding earlier. Thanks!
