### ISSUE TITLE
Write stories for MegaMenu

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#15426]
## Issue Description
Using the documentation found in [the markdown file for `MegaMenu`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/formation-react/src/components/MegaMenu/MegaMenu.mdx), write Storybook stories for the component.

## Acceptance Criteria
- [ ] All the "stories" found in `MegaMenu.mdx` are written as Storybook stories
- [ ] These stories are found in `packages/formation-react/src/components/MegaMenu/MegaMenu.stories.jsx`

**Comment by bkjohnson** [comment]
I'm pausing work on writing a story for this particular component. Getting the styling just right is challenging, and @cvalarida and I are going to explore the possibility of moving this out of the component library and into `vets-website`.

**Comment by cvalarida** [comment]
Yeah, this doesn't belong in the component library. Moving it into `vets-website` is a separate issue from this, so I'm closing it for now.
