### ISSUE TITLE
Letters service integration

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15439]
## User story
As a user, I want to see a list of letters that are available to me. 

## Acceptance Criteria

1. Service integration with the letters API
     - Make a call to display letters on the Letters list view screen

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 12/17/2020 - Seeing list of available letters.  Moving to Design QA.
