### ISSUE TITLE
Common component: Address summary

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15446]
## Acceptance Criteria:
1. Create common component for the address summary field, which appears on the following pages:
     - Personal Information
     - Letters landing page
2. Contains a header (i.e. "Mailing address") with service-driven address
     - Can span multiple lines, depending on the length / type of address

## Designs
Personal Info page: https://adhoc.invisionapp.com/d/main/#/console/20546460/431636868/preview
Letters landing page: https://adhoc.invisionapp.com/d/main/#/console/20546460/431636878/preview

# Dev checklist

- [ ] UX/UI
- [ ] Add tests

**Comment by digitalken** [comment]
Testing:

1. Verify address summary field appears on the following pages:
  a. Personal Information
  b. Letters landing page.
2. Verify component contains a header ("Mailing address") with a service-driven address.
  a. (The address can span multiple lines, depending on length and address type.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Pass in TestRail.  Sending to Design QA.
