### ISSUE TITLE
Common component: Expand/collapse

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15441]
## Acceptance Criteria
1. Create common component for expand / collapse, which has two states:
2. Collapse state:
     - default view
     - downward-facing caret
3. Expand state:
     - upward-facing caret
     - white box expands vertically (the height of this box is dynamic and will vary)

## Designs
Example from Direct Deposit ("Where can I find these numbers"): https://adhoc.invisionapp.com/d/main#/console/20546460/431636876/preview

# Dev checklist

- [x] UX/UI
- [x] Add tests

**Comment by komaly15** [comment]
AC Updates after discussing it w/ Bridget:

- The underline under the text will now be a solid line, not dotted

- The arrow icon should not move when expanding/collapsing, both the up and down arrows should be in the same spot (so the white box will not expand vertically)

**Comment by digitalken** [comment]
Testing:

1. Verify Expand Collapse component has two states:
  a. Collapse state
    i. Default view.
    ii. downward facing caret.
  b. Expand state
    i. upward facing caret
    ii. white box expands vertically (height is dynamic depending on content.)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/18**

PASS - on iOS and Android. Moving to design QA
