### ISSUE TITLE
Common component: Native dropdown

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15443]
## Acceptance Criteria
1. Create common component for the native dropdown picker, which appears on various edit states throughout the app, including:
     - Direct Deposit edit screen > Account Type field
     - Edit Address > Country & U.S. State fields
2. Selecting a native dropdown field will open the device's OS dropdown menu, allowing the user to choose from a series of options in the menu

## Designs
N/A

# Dev checklist

- [x] UX/UI
- [x] Add tests

**Comment by digitalken** [comment]
Testing:

1. Verify the native dropdown picker appears on various edit states throughout app, including:
  a. Direct Deposit edit screen > Account Type field
  b. Edit address > Country & U.S. State fields
2. Verify that selecting a native dropdown field will open the device's OS dropdown menu and allow the user to choose from a series of options in the menu.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
I'm passing this but I do have a medium bug logged -- not enough to keep from verifying the story is complete, though.  Results in TestRail.  Moving to Design QA.
