### ISSUE TITLE
Common component: Checkbox

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15442]
## Acceptance Criteria
1. Create common component for the checkbox button, which has two states: unselected & selected
2. Unselected state: white container
3. Selected state: blue container with a white check mark
4. UI documentation
     -  Text: Mobile Body
     -  Checkbox background (active): primary #0071bb
     - Checkbox border (active): 1px solid primary #0071bb
     - Check icon color (active): white #ffffff
     - Checkbox background color (inactive): white #ffffff
     - Checkbox border (inactive): 1px solid gray-medium #757575
     - Margin: standard gutter L/R; marginBetween vertical
     - Internal padding between checkbox and text: 10px

## Designs
Unselected: https://adhoc.invisionapp.com/d/main#/console/20546460/431636876/preview
Selected: https://adhoc.invisionapp.com/d/main#/console/20546460/432050369/preview

# Dev checklist

- [x] UX/UI
- [ ] Add tests

**Comment by digitalken** [comment]
Testing:

1. Verify checkbox type button having two states: selected and unselected.
2. Verify unselected state is a white container.
3. Verify selected state is a blue container with white check mark.
4. Verify UI is (visually as best as possible:
  a. Text: Mobile body.
  b. Checkbox background (active): primary #0071bb
  c. Checkbox border (active): 1px solid primary #0071bb
  d. Check icon color (active): white #ffffff
  e. Checkbox background (inactive): white #ffffff
  f. Checkbox border (inactive): 1 px solid gray0-medium #757575
  g. Margin: standard gutter L/R; marginBetween vertical
  h. Internal padding between checkbox and text: 10px

**Comment by digitalken** [comment]
Added to TestRail

**Comment by digitalken** [comment]
Passed in TestRail - moving to Design QA.

**Comment by esther-k** [comment]
**11/20 Update**
Android [accessibility bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16484) entered
