### ISSUE TITLE
Common component: Mobile alert

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15445]
## Acceptance Criteria
1. Create common component for the mobile alert box
2. UI: 
      - Border-left: 8px, variable
            - Informational: primary-alt-dark #00a6d2
            - Error: secondary-dark #cd2026
            - Warning: warning-message #fac922
      - Text (Headline): Mobile Body Bold (optional)
      - Text (Body): Mobile Body
      - Text color: gray-dark #323a45
      - Background color: variable
      - Internal padding: 20px top & bottom; 10px left & right 
      - Margin: standard gutter L/R; marginBetween vertical 
      - Optional ClickForAction button at the bottom

## Designs
Example from Service Verification Letter: https://adhoc.invisionapp.com/d/main/#/console/20546460/431636880/preview

# Dev checklist

- [ ] UX/UI
- [ ] Add tests

**Comment by digitalken** [comment]
Testing:

1. Verify mobile alert box (example:  https://adhoc.invisionapp.com/d/main/#/console/20546460/431636880/preview )
  a. Left border
    i. Informational color:  #00a6d2
    ii. error color:  #cd2026
    iii. warning color:  #fac922
  b. Headline:  Bold (optional)
  c. Body:  standard, dark gray #323a45
  d. Padding:  20px top/bottom; 10px left/right
  e. Margin:  Standar gutter l/r; margin between vertical
  f. Optional click for action button at bottom

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
11/23/2020 - Bug 16416 passes, moving to Design QA.
