### ISSUE TITLE
Common component: Large button

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15444]
## Acceptance Criteria
1. Create common component for large button, which will appear throughout the app including the following pages:
     - Letters pages
     - Claims upload flow
2. Details:
    - No border
    - Text color: variable
    - Background color: variable 
    - Text style: Mobile Body Bold
    - Internal padding: 10px total 
    - Margin: standard gutter L/R; marginBetween vertical 
    - Border radius: 5px

## Designs
"View letters" - https://adhoc.invisionapp.com/d/main#/console/20546460/431636878/preview
"View letter" - https://adhoc.invisionapp.com/d/main#/console/20546460/431636880/preview
"Upload evidence" - https://adhoc.invisionapp.com/d/main#/console/20546460/432345660/preview
"Upload" - https://adhoc.invisionapp.com/d/main#/console/20546460/432623523/preview

# Dev checklist

- [ ] UX/UI
- [ ] Add tests

![Screen Shot 2020-10-29 at 3.35.39 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/93f9c4e7-abc6-4103-8fbb-de4697f9ce1c)

**Comment by bridgethapner** [comment]
@bessgreen Here is the documentation for the common button component that's used in the screens you noted above + on the [unauth home screen:](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432863239_Unauth-Home) 

- No border
- Text color: variable
- Background color: variable 
- Text size: Mobile Body Bold
- Internal padding: 10px total 
- Margin: standard gutter L/R; marginBetween vertical 
- Border radius: 5px

**Comment by digitalken** [comment]
Testing:

1. Verify large button (example:  https://adhoc.invisionapp.com/d/main#/console/20546460/431636878/preview ) has the following:
  a. No border
  b. Variable text color
  c. Variable background color
  d. Text style:  Mobile Body Bold (visual verification)
  e. Has internal padding 10px (visual verification)
  f. Margins - Standard gutter left, right, margin between vertical (visual verification)
  g. Border radius 5 px (visual verification)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS - Moved to design QA.
