### ISSUE TITLE
DebtRes-FSR Ch1 Veteran Information Hifi Design 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15475]
As a Veteran Filling out the FSR I expect my personal information as well as a list of debts I am seeking resolution for to be pre-filled. I also want the option to update my personal information if it is incorrect 

Create Hifi Design for Veteran Information to include the following sections 

- C1P1: Veteran information

- C1P2: Debt selection

- C1P3: Contact information

**Comment by rileyorr** [comment]
My first pass at the first chapter has been added to [the UXPin prototype](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701377/simulate/sitemap?mode=i).
