### ISSUE TITLE
Google Tag Manager Preview Mode Debugging Staging Block

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#15473]
## What happened?
Our Google Tag Manager preview needed for testing and validating tags is not functioning in staging

## Steps to Reproduce
- At https://tagassistant.google.com (GTM console) click "Preview" 
- Tags should start firing immediately when the debugging screen has refreshed
![image.png](https://images.zenhubusercontent.com/5d234c844828605fd8bf8ede/81da5a62-a177-40f1-ab41-d9e677647a51)

## Desired behavior
Tags previews / specifications populating within the debugger

## Acceptance Criteria
- [ ] Cause of staging issue blocking GTM identified
- [ ] Fix implemented within staging/production

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jonwehausen** [comment]
![image](https://user-images.githubusercontent.com/48527022/97466181-317bb600-1919-11eb-93ec-b5bc8292ab56.png)

**Comment by jonwehausen** [comment]
### Update
- We have identified the following workarounds thus far: 
   - When starting the debugger, inputting the prod `www.va.gov` domain and then changing in the URL bar to `staging.va.gov` populates the debugger -- **this is the only current way we have to preview a specific GTM workspace**
   - Starting the debugger from the environments tab and inputting `staging.va.gov` will correctly populate tags from the start -- **cannot use with a specific workspace**

_We hypothesize at this point there is a relationship between configured GTM environments and the new tag assistant beta tool that causes issues when starting a standard preview_ -- research continues

**Comment by jonwehausen** [comment]
### Update
- The new tag assistant beta  is not giving us the ability to test unpublished workspaces 
- This directly affects our ability to test new support issues 

### At this point...
- We have escalated directly to Google support and are waiting on their correspondence

**Comment by jonwehausen** [comment]
Other troubleshooting steps we have taken: - Unchecking the "Include debug signal in the URL"- Checked the content security policy is allowing GTM according to documentation- Republishing last version / workspace- Allowing pop-ups in the browser that may have prevented the assistant from opening- Checked Networking tab for blocked resources- Traced CSP error to see if they are GTM or GTM-related
- Checked for GTM debug cookie and checked referrer 
- Start GTM preview to live, then to staging
- Tried incognito mode / Firefox
- Previewing different workspaces (default and new ones) 
- Manually adding ?gtm_debug=x querystring value to URL

**Comment by jonwehausen** [comment]
## Current Workaround

1. Within the workspace, Click Submit and make sure "Publish and Create Version" is selected and change the environment to Staging
2. Go to Admin > Environments, make sure the "Latest" version and "Staging" version show the new version in the version name column.
3. For the "Staging" environment, click the "Actions" expander and then click "Share Link", copy & paste into new tab
4. Start the tag assistant beta with staging.va.gov

**Comment by joanneesteban** [comment]
## Outcomes

- No data loss; 1.5 days lost in data testing/team time
- Bug was a Google-wide issue. Only affected Staging.
- ^ "Current Workaround" fixed the bug
