### ISSUE TITLE
Calling controller should be captured in request chain

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#15482]
## Background

In order to reliably determine which frontend applications are invoking requests to which external services, and more readily understand the impact of external service outages on veteran-facing services, we should indicate the controller path that is calling a given external service client method.

Ultimately, we'd like to be able to query Prometheus for something like this:

`sum(increase(api.request{controller=~"controller_name"}[1h])) by (external_service)`

## Tasks

- [ ] Utilize [request_store](https://github.com/steveklabnik/request_store) to include the controller name on external requests
- [ ] Wire these statistics into StatsD metrics

**Comment by erluti** [comment]
@kfrz Does this cover this use case? https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/concerns/sentry_controller_logging.rb#L30

**Comment by kfrz** [comment]
https://github.com/dcadenas/rubydeps
https://github.com/emad-elsaid/rubrowser

What's the diff between dependency graphs? Can we put this into a CI job? What can we do w/ this information?
