### ISSUE TITLE
Resources & Support: In IE11, search button is not inline with input field

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#15488]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_
![image](https://user-images.githubusercontent.com/55992116/97463098-c7addd00-1915-11eb-91b5-9b05d7086954.png)

## Specs:
Saw this in IE11 via CAG on my Mac, desktop

## Steps to Reproduce
- URL:  http://learningcenter.web.demo.ci.cms.va.gov/resources/

## Desired behavior
Search button should be inline w/ input field

## Acceptance Criteria
- [ ] Search button should be inline w/ input field

cc @tzelei for awareness

**Comment by jenniferlee-dsva** [comment]
great minds - this is already in progress with a duplicate ticket #15610

will close this one.
