### ISSUE TITLE
DebtREs FSR Ch2 Household Income Hifi design

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15481]
As a Veteran filling out the FSR I want the ability to enter my household income to give an accurate representation to the DMC of my overall financial situation. 

This section must contain the following: 
C2: Household income

C2P1: Veteran employment
C2P2: Additional veteran income
C2P3: Marital status
C2P4: Spouse’s employment
C2P5: Spouse’s additional income
C2P6: Household dependents

**Comment by rileyorr** [comment]
All the pages for CH 2's first iteration have been added to [the UXPin prototype](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133702773/simulate/sitemap?mode=i)!
