### ISSUE TITLE
User email address is not always available from SSOe

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#15485]
# Problem
When we tried to do UAT with a veteran, they'd logged on prior to joining the sesion.  I'd added the veteran's email address to the feature toggle but the feature toggle was still showing `false`.  We had to reschedule UAT.  

# Why
Damien was able to look at the IAM logs and said
"that user was logged in to SSOe direct from DS Logon at LOA2.  They never logged in with ID.me.  DS Logon does NOT provide email address and there is no email address on the user record in IAM."

Currently, we reference `user.email` as an id for the [feature toggle ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/user.rb#L323).  During UAT today I didn't consider that the email was nil because the user's email was present in https://api.va.gov/v0/user (probably from VA Profile).

Before SSOe, we were confident that we would get an email address for all LOA3 users from the identity provider. `user.email` looks only at the email address from the identity provider.

We have two options to make this better:
1) get the email from VA Profile for just for feature toggles. 
2) change `user.email` to get the email from VA Profile (possibly only if we don't have it from the identity provider)  But, before making that change someone should think about if there are security implications to that. 

@jbalboni experienced a similar issue https://dsva.slack.com/archives/CHPA76VV5/p1603305988040700 last week

**Comment by bosawt** [comment]
Closing this. This is an issue with MPI not showing email, and SiS will fix this
