### ISSUE TITLE
DebtRes FSR Ch3 Household Assets Hifi Design 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15487]
As a veteran filling out the FSR form I want the ability to enter my assets so the DMC can have an accurate representation on my financial status when evaluating debt resolution  request.

**Comment by rileyorr** [comment]
Initial pass at [CH 3](https://app.uxpin.com/edit/8733985#?id_page=133878135) has been added to the UXPin prototype! There's a couple directions we could go with how we collect these monetary values, so I added a couple versions for us to review with the DMC.
