### ISSUE TITLE
CT: institution profile page accordion headers do not fully darken on hover

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#15491]
The accordion headers on an institution profile page darken when a user hovers over them with their cursor. The lighter gray version of the header is too tall and still shows after the user hovers their cursor over the accordion. The "School ratings" header is the only one that does not exhibit this behavior. All other accordion headers should match the "School ratings" accordion header. This applies to all non-VETTEC institutions.

### Steps to reproduce
1. Access any comparison tool school profile page ([example](https://staging.va.gov/gi-bill-comparison-tool/profile/11800118))
2. Hover over any of the accordion headers using the cursor

### Current behavior
![Screen Shot 2020-10-28 at 10.27.07 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/74f20eec-13e0-484e-87a5-f31284b8de90)

### Expected behavior
![Screen Shot 2020-10-28 at 10.28.52 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e8db2355-6054-4f80-abbd-f79bedee4955)

**Comment by dmccurdybah** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14881

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-11-06 at 10.15.22 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7771bd40-ffd5-4696-b2a9-a220f7724001)
##
![Screen Shot 2020-11-06 at 10.15.26 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f5efd9d4-bdc4-4b51-9aa1-9673451c8914)
##
![Screen Shot 2020-11-06 at 10.15.31 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e277b589-9ed7-4458-83a5-4c835143641b)
##
![Screen Shot 2020-11-06 at 10.15.37 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cc4f6853-c00d-4614-8318-7922235bcb8b)

**Comment by sonntag-adam** [comment]
In staging, closing bug.
