### ISSUE TITLE
DebtRes FSR Ch4 Household expenses Hifi design 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15497]
As a veteran I want eh ability to add my expenses when filling out the FSR form so DMC can have an accurate representation of my financial status

**Comment by rileyorr** [comment]
Added a couple versions of this chapter to [the UXPin prototype](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133946928/simulate/sitemap?mode=i). I'm going to sync with Becca so we can critique this design and I will make updates afterwards.

**Comment by rebeccawalsh** [comment]
I've updated Ch 4 to separate it into 4 pages rather than one and included the new loop list designs into the applicable pages.

https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134307864/simulate/sitemap?mode=i
