### ISSUE TITLE
Resources and support: In IE11, the bottom border for the last item on a list page is lighter than all the other borders

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#15504]
## What happened?
In IE11, the bottom border for the last item on a list page is lighter than all the other borders

![image](https://user-images.githubusercontent.com/55992116/97471020-a7cee700-191e-11eb-8f67-78cec630684f.png)

## Specs:
IE11, on my MacBook via CAG

## Steps to Reproduce
- URL: From the homepage, click "go to more articles" under either topic section, or click on an `All Veterans` tag at the bottom of any article page, or do a keyword search for "account"

## Desired behavior / AC
In IE11, the bottom border for the last item on a list page should be the same color as the borders for other list items.

**Comment by brianalloyd** [comment]
Closing based on Grooming session review.  Decision was that color discrepancy was not intentional.
