### ISSUE TITLE
Resources & Support: In IE11 and Chrome, pagination doesn't have highlight for current page on Category/All Articles tagged list pages

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#15503]
## What happened?
 In IE11 and Chrome, pagination doesn't have highlight for current page on Category/All Articles tagged list pages

![image](https://user-images.githubusercontent.com/55992116/97471020-a7cee700-191e-11eb-8f67-78cec630684f.png)

## Specs:
IE11 and Chrome, on my MacBook via CAG

## Steps to Reproduce
- URL: From the homepage, click "go to more articles" under either topic section, or click on an `All Veterans` tag at the bottom of any article page

## Desired behavior / AC
The number of the page you're on should be in a blue circle, per the pattern we see on the keyword search result page (and DS pagination component)

**Comment by kelsonic** [comment]
I haven't found the pagination at all on the page https://www.va.gov/resources/search/, am I looking on the wrong page? I didn't see a link of where this issue was found in the ticket description 🙂

**Comment by andaleliz** [comment]
@kelsonic I didn't include a URL because it's across all instances.  

I put instructions to reproduce in the description. Homepage refers to va.gov/resources - my apologies, I assumed that that would be a given based on the issue title.
>  URL: From the homepage, click "go to more articles" under either topic section, or click on an All Veterans tag at the bottom of any article page

**Comment by kelsonic** [comment]
Ah ha! I see it now, thanks!

**Comment by kelsonic** [comment]
So the pagination that's currently being used is also used on these other templates:

![image](https://user-images.githubusercontent.com/12773166/99437907-4d4afa00-28d0-11eb-97f9-38229e94d142.png)

I'm assuming this change is desired for all of those templates as well but just want to confirm! 🙂

**Comment by andaleliz** [comment]
Not sure if you are directing that at me, but I think you'd need to coordinate/double check with whoever implemented those other templates too.  Are those new? They look like they could be related to the recent pages John H requested.  

In my opinion. pagination should follow the guidance/examples in the design system, site-wide. https://design.va.gov/components/pagination

**Comment by kelsonic** [comment]
They aren't new, I think they're mostly maintained by the facilities team 🙂 I'll check in with them, thanks Liz!

**Comment by kelsonic** [comment]
Hey @mpelzsherman your team maintains the templates found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15503#issuecomment-729150840) right? Just want to let you know I'm working on this since I think this will change your teams' pages' pagination styling 🙂

**Comment by mpelzsherman** [comment]
@mmiddaugh FYSA
