### ISSUE TITLE
Resources and support: Too much spacing between bottom of process list and CTA buttons, IE11

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#15501]
## What happened?
- Looks like there's too much space between the end of the process list and the CTA buttons (should be 40px)

## Specs:
IE11, on my MacBook via CAG

## Steps to Reproduce
- URL: http://learningcenter.web.demo.ci.cms.va.gov/node/8434/ and http://learningcenter.web.demo.ci.cms.va.gov/node/8474/

## Desired behavior / AC
Should only be 40px of space between the bottom of the image/text in the last step of the process list, and the CTA buttons that follow.

**Comment by brianalloyd** [comment]
Closing, links no longer relevant.
