### ISSUE TITLE
DebtRes FSR Ch 6 Bankruptcy Hifi Design  

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15506]
As a veteran filling out the FSR form I want the ability to give DMC information about my bankruptcy

**Comment by rileyorr** [comment]
Added a first pass of [the bankruptcy screens](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134050599/simulate/sitemap?mode=i) to the UXPin prototype!

**Comment by rileyorr** [comment]
Made some updates to the bankruptcy screens; the original link should still work
