### ISSUE TITLE
Ratings: Hover state updates 

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#15514]
## Assumptions
1. This work is completed behind feature flag gibct_school_ratings created in #13359.

## Acceptance Criteria
1. On the institution profile page within the "School ratings" section, if a rating subcategory (mini accordion) is hovered over, clicked, or tapped then the background color of the mini accordion button should update to #F1F1F1 as seen in SA1.
2. The section separators between rating subcategories (i.e., GI Bill support, Veteran community) are lengthened in accordance with SA1.
3. 20px between accordion and content to allow for breathing room with the added hover state (AC1) in accordance with SA1. 

## Supporting Artifacts
1. Mobile Prototype: https://bahdigital.invisionapp.com/share/Q8IAFCYHFMD
2. Desktop Interactive Prototype: https://bahdigital.invisionapp.com/share/ZHIAFDQQM5D

**Comment by ksantiagomorgan6** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14793

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging ready for review

**Comment by amyknox** [comment]
UX Review 1/2 - This looks good to me on desktop. The highlight on mobile looks too narrow. 
![Image from iOS](https://user-images.githubusercontent.com/41081945/97919977-b5251080-1d26-11eb-83e7-ad126515f30d.png)

@watersemma take a look at the implementation and make sure the hover state is functioning and aligns as you intended

**Comment by watersemma** [comment]
UX review 2/2 Desktop checks out for me. For mobile, the content looks a little tight when the accordion is open. We are missing the 20px of space between accordion and content.
 ![Screen Shot 2020-11-02 at 4.27.18 PM.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/2ca59a2b-c14a-4548-9d50-5b9b67271e61)

**Comment by ksantiagomorgan6** [comment]
Additional PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14810

**Comment by watersemma** [comment]
UX Review 1/2: spacing updates still needed. Missing 10px padding on either end of the accordions so the title and + / - are not touching the edge, including hover state. See images.

![Screen Shot 2020-11-04 at 9.53.33 AM.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/8b92c0ba-7236-4d2c-9ba6-90af0ec2bc04)![Screen Shot 2020-11-04 at 9.51.39 AM.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/f1e00344-2781-4348-8825-5b48d2b21c9b)

**Comment by ksantiagomorgan6** [comment]
Yeah, another story was created for that. It will be the +/- spacing issue and the narrow button issue in one story.

**Comment by watersemma** [comment]
In that case UX Review: 1/2 Good to go! Thank you Kenny!

**Comment by amyknox** [comment]
UX review 2/2 - Good to go.  Thanks Kenny!

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/13994&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
Closing story
