### ISSUE TITLE
VSP content review - Direct deposit for Edu benefits

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#15518]
## User story
This ticket captures VSP content feedback of direct deposit feature for Edu benefits

Prototype link:  https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/

## Acceptance criteria
 - [x] VSP/Peggy provides content feedback and recommendations for the form/tool.
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x]  Product team leaves any comments about feedback they decide not to take
- [x] Peggy checks form after content feedback has been incorporated

**Comment by peggygannon** [comment]
@sporeboy Please see below for content feedback to the direct deposit for EDU benefits content feedback 

Screen 2
Education benefit
Account please update intro sentence TO: 
To update the account where you want us to pay your education benefits, please enter the bank and account information below. 

recommend updating labels TO:  
Routing number (Your bank’s name will appear after you add the 9-digit routing number)
Account number (no more than 17 digits)
Account type

Screen 3 
Recommend updating account type error message update TO: 
Please select  a type of account

Screen 4
Update alert message TO: 
We’ve updated your bank account information for your **Education benefits**

Screen 8
Recommend updating Compensation and pension intro TO: 
To update the account where you want us to pay your compensation and pension benefits, please enter the bank and account information below. 

Screen 9
Recommend updating the alert message TO: 
We’ve updated your bank account information for your **compensation and pension benefits**

**Comment by sporeboy** [comment]
Feedback incorporated. All edits in place: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/

**Comment by sporeboy** [comment]
I have a question: in "Your bank’s name will appear..." the Y is capitalized. In the other parenthetical, "(no more than 17 digits)," the N is not. Is this intentional?

**Comment by peggygannon** [comment]
hello @sporeboy yes, it was, as one is a full sentence, but the other not. But seeing i updated in the mockup, I recommend we make both of them sentences. I've provided a recommendation in the mockup.

**Comment by peggygannon** [comment]
Hi, @sporeboy additional feedback for use cases where someone has DD for one type of payment, but not the other.
https://xd.adobe.com/view/5315e9ba-69ee-4082-bb26-29605bc4ae67-0646/screen/5dbf1181-9771-4bfd-b0ca-b9770bfdf4de


1. Message for no education DD: 

Our records show that you're not receiving education benefit payments. If you think this is an error, please call us at [800-827-1000](make this a hyperlink). 

Where does this education eligibility link take users ?

I recommend updating link to:
[Find out if you’re eligible for VA education benefits] (https://www.va.gov/education/eligibility/)

------

2. Message for no pension and compensation DD

Our records show that you're not receiving disability compensation or pension payments. If you think this is an error, please call us at [800-827-1000](make this a hyperlink). 

Where does this link take users? these are two different benefits with different eligibility criteria. 
[Learn more about compensation and pension eligibility]

**Comment by Samara-Strauss** [comment]
Is this good to close? I think all the copy is complete.

**Comment by peggygannon** [comment]
Hi, @Samara-Strauss I had open question for @sporeboy about the recent copy I posted above yesterday ^^

I was going to close this ticket after I see this last question/update is resolved.

**Comment by Samara-Strauss** [comment]
Got it! Thanks, @peggygannon!

**Comment by sporeboy** [comment]
Hi there @peggygannon !

For "Where does the links take users?", I'm good with your suggestion to link education to the eligibility page. As for comp and pen, seems I need to point to the two (different) eligibility pages. Here are the two mocked pages:

- https://xd.adobe.com/view/5315e9ba-69ee-4082-bb26-29605bc4ae67-0646/screen/a942fa36-4ebd-446f-92ee-65149d9e9584
- https://xd.adobe.com/view/5315e9ba-69ee-4082-bb26-29605bc4ae67-0646/screen/5dbf1181-9771-4bfd-b0ca-b9770bfdf4de

The links would go to their respective eligibility pages:
- Eligibility for VA disability benefits
- Eligibility for Veterans Pension

**Comment by peggygannon** [comment]
Hi, @sporeboy  I don't see the new screens in the mockup links you provided above ^^. I can take a look again, once they latest updates are in there. 

Here is what I'd recommend for those eligibility links: 
[Find out if you're eligible for VA disability benefits](https://www.va.gov/disability/eligibility/)

[Find out if you're eligible for VA pension benefits(https://www.va.gov/pension/eligibility/)
