### ISSUE TITLE
Large font on device causes resizing of header and navigation footer content (too large)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#15534]
## What happened?
I increased the font to maximum size for my device and opened up a web view.  The header and navigation footer content grew large enough to spill out of the header/footer and cause some overlapping of web view content (barely visible in the screen shot of the white lock on top of other white content but cutting off text in the view window [VA] and the tail in 'g' extending down over the dot on the 'i' in locations.)

## Specs:
- Device: (out of matrix device iPhone 6S but approximately the size of an iPhone SE (2nd edition) which is in the matrix.)
- Test User: any user

## Steps to Reproduce
- Increase font to maximum size in accessibility and navigate to a web view (in this case, Find my VA location.)

## Desired behavior
Content in the header/nav footer should not resize with font size choice.

## Acceptance Criteria
- Header and nav footer content will not resize with font size choice.

## Bug Severity
- 3 Medium

## Screen shot(s) and additional information

![webViewControls.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/127941c7-5a11-4407-9f6c-1d7675c9eda0)

**Comment by esther-k** [comment]
**11/18 Update:**

This bug is affecting the save button on the edit phone number pages

**Comment by digitalken** [comment]
Pass 11/24/2020 - Header controls and footer controls are no longer resized with font increase in size.
