### ISSUE TITLE
Documentation - PDF Error - Image invalid alt text

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#15544]
This will be the spike ticket for writing documentation for fixing the invalid alt text for images ( https://dequeuniversity.com/rules/comply-pdf/1.0/image-invalid-alt )

**Comment by humancompanion-usds** [comment]
Improving PDFs that are hosted on VA.gov is not a Design System Team task. The Veteran-facing Forms team has an initiative to look into this process and to try and make improvements: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49748
