### ISSUE TITLE
Figure out what IA and Content needs are from VFS Teams

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1554]
## User Story
To guide teams in the right direction for content and IA, we need to give them guidance and recommendations at the right point in their process.

## Goal
Reach out / collaborate however we need to, to understand the status of all current VFS Team builds, and decide whether we need to get involved and how.

## Acceptance Criteria
- [ ] Know status of all VFS teams' work (and not in a way that duplicates whatever Product Support team is capturing)
- [ ] Have opinions on whether we should get involved, and how
- [ ] Have tickets in appropriate Epic for the involvement needed from us this sprint

**Comment by meganhkelley** [comment]
Closing — at the moment, it does not make sense to track this particular work in a ticket. We have onboarded all VFS teams and they are reaching out to us with review requests as needed.
