### ISSUE TITLE
Maximum font on device leaves very little of scrollable screen below Veterans Crisis Line button (Need new designs?)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#15540]
_NOTE: Possible fix will be covered in [unfix story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16132)_

## What happened?
I increased my font to maximum on my device and went to the home screen.  The Talk to the Veterans Crisis Line now button and header take up over 75% of the screen leaving very little for the actual home screen content to scroll through.

## Specs:
- Device: iPhone 6s (not in matrix but similar sized screen to iPhone SE 2nd gen.)

## Steps to Reproduce
- Increase font on device to maximum and navigate to the home screen.

## Desired behavior
More scrollable part of the screen should be available for viewing rather than have the button content take up 75% of the screen.

## Acceptance Criteria
- User can see a larger scrollable area of the home screen with maximum font selected in accessibility.

## Bug Severity
- 3 Medium

## Linked Story
- none

## Screen shot(s) and additional information

![homePageMaximumFont.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/d2866c1a-b51f-46c4-8ddd-8855c1bae8f4)

**Comment by digitalken** [comment]
@bessgreen - I think we need new direction as to how the Veterans Crisis Line button should respond when increasing the font size on the device.  Having the button increase to 75% of the screen and leaving a small fraction still scrollable probably isn't the right way to go.  But what is?

**Comment by esther-k** [comment]
**11/23**

Pass on iOS and Android. The Veterans Crisis line button is now scrollable with the page and other content can be accessed
