### ISSUE TITLE
Question text should display even when FAQs are not inside accordions

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15554]
## Question text should display even when FAQs are not inside accordions

**What's happening:**

1. When the enable-accordions checkbox is NOT checked, the article should show the question and answer text on the page. 
2. But what is happening now is that only the answer text is displaying, but the question text part of the content doesn't show at all. 

Sample node where this issue is occurring: http://preview-prod.vfs.va.gov/preview?nodeId=9480

**In the screenshot are 3 FAQs. What you see are 3 answer texts, missing the question text which are:** 

- Can I upload new evidence online?
- What if I don't want a fiduciary anymore?
- Are service dogs allowed in VA facilities?

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/873eec4c-eb9d-4a88-bdf9-c53e91517ad2)

**What should happen:**
When the accordion checkbox is empty, both the question text and answer text should appear on the page. Example - like this (from a benefit detail page that uses same checkbox feature): 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/6635e3f8-96f4-4529-8f13-7584ef972d3d)

**Comment by ncksllvn** [comment]
Sorry about this @jenniferlee-dsva. This was just a sloppy mistake I made during the rush the other day. I have a PR open to address it that should be merged soon, https://github.com/department-of-veterans-affairs/vets-website/pull/14766.

**Comment by ncksllvn** [comment]
This is merged. It will go to production (for preview) during today's deployment. I'll ping Steve when it's ready to go to the demo environment.

**Comment by jenniferlee-dsva** [comment]
validated.
