### ISSUE TITLE
Learning Center - Home - Breadcrumbs don't match design prototype

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15559]
## What happened?
On CMS Learning Center demo-environment, Learning Center homepage breadcrumbs didn't match design prototype.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [unauthenticated]

## Steps to Reproduce
1.  Go to http://learningcenter.web.demo.ci.cms.va.gov/resources/ [requires VA network access via CAG].
1.  Near top of page, observe the following mismatches in the breadcrumb:
    a.  **Home** is not a hyperlink
    b.  **> Resources and Support** [non-link, current-page breadcrumb] is missing.

**Screenshot**
![lc-mvp1 0-bug-home-breadcrumbs](https://user-images.githubusercontent.com/587583/97501426-76f6ae00-192e-11eb-83d9-f43ec9ceffac.png)

## Desired behavior
LC homepage breadcrumbs should match design prototype:
<img width="834" alt="lc-mvp1 0-spec-home-breadcrumbs" src="https://user-images.githubusercontent.com/587583/97501482-91308c00-192e-11eb-9b2c-3ccd076777d3.png">

## Acceptance Criteria
[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
Validate with demo rebuild

**Comment by jenniferlee-dsva** [comment]
Validated here http://learningcenter.web.demo.ci.cms.va.gov/resources/
