### ISSUE TITLE
Confirm email is coming from VA Profile

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#15564]
It seems like the email field in Profile might be pulling from the credential provider rather than VA Profile. We'd like to pull from VA Profile to match the email address VA.gov shows. 

## Tasks
- [ ] Confirm that the email address field is pulling from VA Profile and not the credential provider
- [x] Cross-reference VA.gov staging user data with data as it appears in the mobile app

**Comment by srmyers17** [comment]
@lexicalninja

**Comment by jperk51** [comment]
Pretty sure the emails are coming from VA profile, but I am 100% sure the email that appears in the user profile on .gov and on mobile are coming from the same place. Side note: If a user changes this email, the update will appear in the other application fairly quickly. Within a few minutes is what I am seeing while testing changing the email in one app, then checking for the update in the other in staging.
