### ISSUE TITLE
Learning Center - FAQs - Breadcrumbs don't match design prototype

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15562]
## What happened?
On CMS Learning Center demo-environment, FAQs page breadcrumbs didn't match design prototype.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [unauthenticated]

## Steps to Reproduce
1.  Go to http://learningcenter.web.demo.ci.cms.va.gov/node/8233/ [requires VA network access via CAG].
1.  Near top of page, observe that the breadcrumbs have an extraneous **Node** crumb which links to a page that throws "Forbidden" browser-error.

**Screenshot**
![lc-mvp1 0-bug-faqs-breadcrumbs](https://user-images.githubusercontent.com/587583/97502696-e2417f80-1930-11eb-8195-cb3761cd8c0d.png)

## Desired behavior
Breadcrumbs should not have extraneous **Node** crumb.
![lc-mvp1 0-spec-faqs-breadcrumbs](https://user-images.githubusercontent.com/587583/97502812-22a0fd80-1931-11eb-85e4-5ae4def2347b.png)

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
To validate Ethan's PRs with demo rebuild

**Comment by jenniferlee-dsva** [comment]
I tried to validate same FAQs page here: http://learningcenter.web.demo.ci.cms.va.gov/node/8233  but got an internal server error.

![image](https://user-images.githubusercontent.com/43381063/98012815-8a3ec900-1dc7-11eb-951d-63d25c11e916.png)

**Comment by jenniferlee-dsva** [comment]
Tried again and appears resolved. Closing as validated.
