### ISSUE TITLE
Learning Center - Step-by-step - Subway-map images broken

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15567]
## What happened?
On CMS Learning Center demo-environment, Step-by-step page subway-map images were broken.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [unauthenticated]

## Steps to Reproduce
1.  Go to http://learningcenter.web.demo.ci.cms.va.gov/node/8417/ [requires VA network access via CAG].
1.  In **subway map**, observe that all Steps' images are broken.

**Screenshot**
[showing Steps 1-3 here -- ALL Steps' images are broken]
![lc-mvp1 0-bug-step-by-step-subway-map-images](https://user-images.githubusercontent.com/587583/97506912-4ec07c80-1939-11eb-971d-b8e9e6bce69a.png)

## Desired display
Subway-map images should display properly.  [No image examples in design prototype.]

## Acceptance Criteria
[see **Desired display** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
@tlei123 - This is strange one because in prod preview the screenshots render fine: http://preview-prod.vfs.va.gov/preview?nodeId=8417

@brianalloyd - could you work with FE to see which is the source of truth we should go by? Hard to tell because of the discrepancy if this is a FE template issue or a demo environment issue.

**Comment by kelsonic** [comment]
![learningcenter web demo ci cms va gov_node_8417_](https://user-images.githubusercontent.com/12773166/97893961-2b0d8580-1cef-11eb-9ee8-49f34028627d.png)

This is appearing for me now on http://learningcenter.web.demo.ci.cms.va.gov/node/8417/ I think it was just a problem with the environment on Friday CC @jenniferlee-dsva

**Comment by brianalloyd** [comment]
Thanks @kelsonic for validating the details.

**Comment by jenniferlee-dsva** [comment]
Thx @kelsonic . I can too now. 

@tlei123 @pjhill ^ - we are able to see the screenshots in the demo instance now, so this may have been a demo problem rather than a template bug. We will close this as resolved.
