### ISSUE TITLE
Learning Center - Step-by-step - Breadcrumbs don't match design prototype

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15566]
## What happened?
On CMS Learning Center demo-environment, Step-by-step page breadcrumbs didn't match design prototype.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [unauthenticated]

## Steps to Reproduce
1.  Go to http://learningcenter.web.demo.ci.cms.va.gov/node/8417/ [requires VA network access via CAG].
1.  Near top of page, observe that the breadcrumbs have an extraneous **Node** crumb which links to a page that throws "Forbidden" browser-error.

**Screenshot**
![lc-mvp1 0-bug-step-by-step-breadcrumbs](https://user-images.githubusercontent.com/587583/97506080-5f6ff300-1937-11eb-8d0a-ae45cd5bfaed.png)

## Desired behavior
Breadcrumbs should not have extraneous **Node** crumb.
![lc-mvp1 0-spec-step-by-step-breadcrumbs](https://user-images.githubusercontent.com/587583/97506098-6565d400-1937-11eb-94c7-e963abd3a9da.png)

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
Same breadcrumb issue to validate with demo rebuild @brianalloyd

**Comment by jenniferlee-dsva** [comment]
Validated and resolved.
