### ISSUE TITLE
Learning Center - Q&A - Breadcrumbs don't match design prototype

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15565]
## What happened?
On CMS Learning Center demo-environment, Q&A page breadcrumbs didn't match design prototype.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [unauthenticated]

## Steps to Reproduce
1.  Go to http://learningcenter.web.demo.ci.cms.va.gov/node/8540/ [requires VA network access via CAG].
1.  Near top of page, observe that the breadcrumbs have an extraneous **Node** crumb which links to a page that throws "Forbidden" browser-error.

**Screenshot**
![lc-mvp1 0-bug-q a-breadcrumbs](https://user-images.githubusercontent.com/587583/97504511-40bc2d00-1934-11eb-830a-776ecc4c0e39.png)

## Desired behavior
Breadcrumbs should not have extraneous **Node** crumb.
![lc-mvp1 0-spec-q a-breadcrumbs](https://user-images.githubusercontent.com/587583/97504535-4ade2b80-1934-11eb-9b7a-731d895c0edc.png)

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
Same bc issue - to validate with demo rebuild @brianalloyd

**Comment by jenniferlee-dsva** [comment]
I tried to validate on the same single QA but got an internal server error message: http://learningcenter.web.demo.ci.cms.va.gov/node/8540

![image](https://user-images.githubusercontent.com/43381063/98013079-e4d82500-1dc7-11eb-9476-b62fe581ff96.png)

**Comment by jenniferlee-dsva** [comment]
http://learningcenter.web.demo.ci.cms.va.gov/resources/how-can-i-find-a-va-facility/

I was able to validate the breadcrumb pattern on a different Q&A page, so closing this as resolved. There appears to be a server error on the specific QA that Tze reported above however, and will report that to the CMS team.
