### ISSUE TITLE
PM: Coordinate IA and Content Intro for VSA eBenefits Team

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1556]
### User Story
As a PM for a VFS team going through onboarding with VSP, I need to participate in an IA & content intro session along with relevant members of my team, so that we know best practices for IA & content and how to engage with the VSP content & IA team.

### Goal
Schedule and attend IA & content onboarding session with VSP's content and IA team and the PM, content writers, and designers on VSA eBenefits.

### Definition of Done
- [x] VSA eBenefits PM has reached out to schedule IA intro with VSP content & IA team.
- [x] Meeting has been completed: VSA eBenefits has gone over best practices and ROE with VSP content & IA team.
- [x] Document findings and feedback from that meeting to recommend for doc iteration.
- [x] Ticket has been assigned to a sprint and an epic.

**Comment by mnorthuis** [comment]
Meeting complete, closing issue. 
cc @meganhkelley

**Comment by meganhkelley** [comment]
FYI feedback (currently just my notes) documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vfs-onboarding-feedback.md
