### ISSUE TITLE
[Development] HLR: Include Contestable Issue Decision Date

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#15579]
During our end-to-end staging test on 2020-10-23, Kelly (Lighthouse PM) noticed we aren't displaying the decision date with each issue (it looks like we're displaying subject text as title and the description below).

Although the description typically includes a date, *there’s nothing that guarantees that descriptions are unique*:

For instance, we could have:
Issue 1:  left knee --increased rating to 50%
Issue 2:  left knee --increased rating to 50%
Issue 3:  left knee --decreased rating to 40%

Issues 1 and 2 look identical, and, without the decision date, there’s no way for the veteran to tell them apart.
It's important that the veteran contest the correct issue --it could mean the difference between their being approved or denied (or at the very least, being decided quickly).

AC:
- [ ] team up with Kevin to decide what it should look like (the date in parentheses at the end of the description?? no clue)
- [ ] **either always display decision date _OR_ display decision date when issues are identical**

**Comment by kevinstachura** [comment]
For posterity, the design: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/404526248
