### ISSUE TITLE
PM: Coordinate IA Intro for VSA eBenefits Team

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1557]
## User Story 

As a part of the VSP on-boarding process, I need participate in an IA intro session, along with any content writers and designers on my team, so I can properly be on-boarded to the eBenefits  team. 

## Goal 

Schedule and attend IA intro session for PM, Designers and Content Writers. 

## Acceptance Criteria 

IA intro has been scheduled and completed with VSP team.  

 
## Definition of Done 

- [x] Has been scheduled
- [x] This issue is assigned to a sprint 
- [x] This issue is attached to an epic. 
- [x] IA intro session completed **_(set for Tuesday, September 17th at 3 pm ET - 60 minutes)_**

**Comment by jason-gcio** [comment]
@mnorthuis can I schedule this with you or who is the best point of contact?

**Comment by jason-gcio** [comment]
> @mnorthuis can I schedule this with you or who is the best point of contact?

Actually, I see in the epic there are some contacts listed - is it preferred to use Slack or GH to schedule this?

**Comment by jason-gcio** [comment]
> > @mnorthuis can I schedule this with you or who is the best point of contact?
> 
> Actually, I see in the epic there are some contacts listed - is it preferred to use Slack or GH to schedule this?

Nevermind, we're all set :)
