### ISSUE TITLE
Use OR logic for user queries of either singular or plural terms. 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15583]
## Use OR logic for user queries of either singular or plural terms. 

**Question:** Can this search alg/logic be something we can leverage from the search.gov api (i.e., if we integrate it with our custom LC search experience)? 

**What happens now:**
When a user searches "claim" - 2 pages of articles come up in results, including the article using the plural "claims" in the title: http://learningcenter.web.demo.ci.cms.va.gov/resources/search/?query=claim

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/2da7d13e-c781-4d1d-98d6-85a945a48cdd)

However, when the user searches "claims" - only 1 article is brought back: http://learningcenter.web.demo.ci.cms.va.gov/resources/search/?query=claims

**What we want to happen:**
When a user searches on the plural of a word, like "claims,"  the search results should include articles that include the words "claims" OR "claim".  (Using "AND" logic will narrow results; what we want is to expand to include articles with "claims" OR "claim." ) 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/668fe36e-deb3-43ed-bfa2-c8afa8bed673)

**Comment by johnhashva** [comment]
Great question for us to explore with @ncksllvn  In truth, the capabilities/extensibility of this custom search (and Find a Form) are something of a black box to me -- so will want to book some time with Nick and our new Search FE to discuss -- perhaps after next week's launch?

**Comment by jenniferlee-dsva** [comment]
But interestingly for "direct deposit" and "direct deposits" -- separate searches - I get back the same 6 results. (Which is how we want it to work. So is there something special about the search on the claim/s term? Alg logic seems to be there - shrugs.)

**Comment by johnhashva** [comment]
Might be a bug (?).  Add Nick's name to this ticket so he can take a look?

**Comment by jenniferlee-dsva** [comment]
Interesting - the demo env must have just gotten updated, because now when I just tried the same claim/s search, I get different results - okay results. So maybe this logic is already in place!

**Comment by johnhashva** [comment]
Same here!

**Comment by johnhashva** [comment]
Update -- as of 10am est: I'm seeing varying results for the following three term/s:

- claim (12 results)/claims (1 result)
- benefit (7)/benefits (6)
- disability (3) /disabilities (0)
- facility (2)/facilities (1)
- veteran (5) / veterans (0)

**Comment by ncksllvn** [comment]
I did already implement logic for doing some really basic stuff here with plurals.

Basically, if the search term is three characters or more and ends with an "s", then the "s" is stripped off under-the-hood when the search is executed. This means "claims" should renders the same result set as "claim", and "benefit" the same as "benefits." 
 @johnhashva I am not sure why this wasn't the result you were seeing when you conducted your search this morning. I speculate that it could be your browser cache. Could you perform a hard reload on your browser and try once more?

My logic didn't go so far as to un-pluralize a word ending in `ies`. I can add that logic though if we want to.

**Comment by johnhashva** [comment]
Will run a new, hard reload test in about an hour.   As for "ies" -- I can't think of a reason not to -- @jenniferlee-dsva  -- you agree?

**Comment by johnhashva** [comment]
@ncksllvn -- looks good!  Let me know when you un-pluralize "ies" and I'll re-run those terms for validation.

**Comment by ncksllvn** [comment]
The work for "ies" should go out tmw!

**Comment by johnhashva** [comment]
11/10 Update:  Validation check in production **looks spot-on**.  Specifics:

claim (3 results)/claims (3 results)
benefit (2)/benefits (2)
disability (1) /disabilities (1)
facility (1)/facilities (2)
veteran (2) / veterans (2)

**Comment by jenniferlee-dsva** [comment]
this lgtm too. i also checked "fiduciaries" / "fiduciary" which both brought back 1 relevant result. closing this one as validated.
