### ISSUE TITLE
Get JP up and running

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1558]
AC: 
- [x] Get github access
- [x] Assign this ticket to yourself
- [x] Find out what slack channels to join -- work with @accbjt 
- [x] Back end is set up (Anna is a good person to talk to)
- [x] Front end is set up
- [x] Go through Harry's API video @accbjt will find

**Comment by johnpaulashenfelter** [comment]
Started this in #3272

**Comment by johnpaulashenfelter** [comment]
Waiting for socks access in department-of-veterans-affairs/va.gov-team#1633 which is a dependency for booting the front end

**Comment by johnpaulashenfelter** [comment]
Got a copy of cache from @annaswims so I'm ok on frontend now
