### ISSUE TITLE
Add learning center homepage to "Root pages" menu

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15585]
## Add learning center homepage to "Root pages" menu

**Currently the breadcrumb on the RS homepage does this in the demo:** 
https://dsva.slack.com/files/UCV8RHP8R/F01EA88TX96/image.png

What it should be: `Home > Resources and support`

**Resolution:** 
Per this thread, Kevin Walsh advises adding the RS homepage into the Root pages menu (similar to how we put the Coronavirus FAQs in the Root pages menu). 

**The menu can be updated here:** 
https://prod.cms.va.gov/admin/structure/menu/manage/root-benefits-hub

**Comment by RLHecht** [comment]
@jenniferlee-dsva This has been added to the root menu as a disabled menu item. 
<img width="1082" alt="Screen Shot 2020-10-29 at 12 01 35 PM" src="https://user-images.githubusercontent.com/48728214/97599544-7f0e2680-19de-11eb-82a6-ef0e82645727.png">
