### ISSUE TITLE
PW Learning Center MVP 1.1 Epic

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15588]
## PW Learning Center MVP 1.1 Epic

Placeholder to capture and track all PW 1.1 efforts.

**Comment by jenniferlee-dsva** [comment]
Referencing Analytics ticket here, so we don't lose visibility: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196 - this is a  high priority item for 1.1, and FE implementation of analytics should be prioritized over non-critical (doesn't impact function) bugs.

**Comment by FranECross** [comment]
Closing old, obsolete ticket.
