### ISSUE TITLE
Write stronger unit test(s) for R&S Search

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#15598]
We implemented a standalone React app for the Resources and Support search function. It's visible here on the demo site, .http://learningcenter.web.demo.ci.cms.va.gov/resources/search/?query=benefits.

However, because the implementation was on a time crunch, we only implemented testing in the form of smoke tests. We should write more comprehensive tests so that as we iterate on this application, we know we didn't unknowingly break anything. I think we should do this using React Testing Library.

## Acceptance criteria
- [ ] Comprehensive tests are written for the R&S search app
- [ ] Tests do not cause random failures on the master branch

**Comment by ncksllvn** [comment]
@brianalloyd I would like to pick this one up as part of the work I am doing in https://github.com/department-of-veterans-affairs/va.gov-team/issues/15650...Some tests would give a sense of safety as I make changes.

**Comment by brianalloyd** [comment]
Sounds great Nick.
