### ISSUE TITLE
Improve Tag component FE in mobile - learning center

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15593]
## Improve Tag component FE in mobile - learning center

This is a carry over from 1.0. I would put the triage level at `Can do anytime`. 

- In mobile view, the field label `Tags` should not appear on its own line. 
- In mobile view, the tag-terms should expand vertically on super long terms (instead of wrapping).
- In mobile view, the tag-terms should stack when there are more than one and they all don't fit on one line. 

**Today in mobile view:** 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/7bddc646-c88b-4786-b863-7253b21ede8b)

**Should be:** 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/7f6bf03e-8542-4903-a9d1-fa5f74db4e38)

Background ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/14332#issuecomment-713898440

Please work with @rtwell or @andaleliz to validate design implementation.

**Comment by jenniferlee-dsva** [comment]
@brianalloyd - I didn't assign FE to this yet. Thnk we need to see what `critical `bugs come out of Tze's QA test.

**Comment by brianalloyd** [comment]
Agreed, hoping to have his feedback today, so we can start working action plan forward.

**Comment by brianalloyd** [comment]
per @andaleliz the boarder color outline should be 'Primary' and not 'Primary alt'.
