### ISSUE TITLE
PM: Coordinate IA Intro for VAOS team

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1559]
### User Story
As a PM for a VFS team going through onboarding with VSP, I need to participate in an IA intro session along with relevant members of my team, so that we know best practices for IA and how to engage with the VSP content & IA team.

### Goal
Schedule and attend IA onboarding session with VSP's content and IA team and the PM, content writers, and designers on VAOS.

### Definition of Done
- [x] VAOS PM has reached out to schedule IA intro with VSP content & IA team.
- [x] Meeting has been completed: VAOS has gone over IA best practices and ROE with VSP content & IA team.
- [x] Document findings and feedback from that meeting to recommend for doc iteration.
- [x] Ticket has been assigned to a sprint and an epic.

**Comment by rroueche** [comment]
@meganhkelley work with @mnorthuis to fill out the user story, goal, and definition of done for this issue please!

**Comment by meganhkelley** [comment]
IA intro completed 9/23, closing.
