### ISSUE TITLE
Global Search Population/Rendering on R&S page for MVP 1.1

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15608]
## Issue Description
_Build upon the user search experience from MVP 1.0 but building a global search population/rendering from the R&S page_

MVP 1.0 the current "global" search all VA redirects to VA.gov search.  The idea would be to keep users on the R&S page and not redirect with full capability of global search results. 

## Front end tasks
- Provide estimate on ticket in support of grooming. 
- Remove grooming tag once estimated.
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Build a global search population/rendering from the R&S page

## Acceptance Criteria
- [ ] Global search results render and populate on R&S search page (no redirect). 

## Planning Considerations
<details> 

 <summary>Priority</summary>
 
 - Lower priority of search features.  Please prioritize #15598 - Test build - High Priority to improve search results. 
#15583 - plural search terms.

**Comment by jenniferlee-dsva** [comment]
Let's keep this in icebox for 1.1. If it's not confusing to users, there's nothing to fix here, and we haven't opened this to enough people to see if it really is.

**Comment by jenniferlee-dsva** [comment]
Can we put a 'not doing' flag on this or the like?  Rationale - we should probably wait for more user input via data and user research or user testing to see if this is a real user problem. I'll close this for now, but not sure if there is a not doing flag.

**Comment by johnhashva** [comment]
Fully agree @jenniferlee-dsva and @brianalloyd
