### ISSUE TITLE
GIDS: Accreditation DAPIP upload fails on first attempt

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#15604]
## What happened?
The Accreditation DAPIP excel file requires 2 upload attempts to upload

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
On https://staging.va.gov/gids attempt to upload the excel file from https://ope.ed.gov/dapip/#/download-data-files
- notice first upload fails
- without leaving upload form upload again with same file
- notice second uploads succeeds

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_
- Excel file from https://ope.ed.gov/dapip/#/download-data-files uploads for Accreditation on first try

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/758

**Comment by sonntag-adam** [comment]
With https://ope.ed.gov/dapip/#/download-data-files it uploads successfully. With it modified it shows an error. 

<img width="1242" alt="Screen Shot 2020-10-29 at 3 33 08 PM" src="https://user-images.githubusercontent.com/48804582/97624278-416cc600-19fd-11eb-98f2-ad4fde1bbb0a.png">

**Comment by sonntag-adam** [comment]
Testing passes QA
