### ISSUE TITLE
"Go to MHV" button appearing for a facility from the schedule appts page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#15600]
## What happened?

**NOTE TO HOLD ON THIS: Logging this now so we have it, but we don't want to touch the modal right now until the current critical Cerner issues are fixed. Please hold on this until then. Thank you!**

When signed in as a Cerner user, a button that reads "Go to My HealtheVet" is appearing for **Captain James A. Lovell Federal Health Care Center**. The button is correctly sending the user to the VA appointments tool, but the label is saying My HealtheVet. 

We're not sure why this is happening. But we need to update the label to "Go to the VA appointments tool"

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/c5332b81-8b6e-478f-b4f6-f11412d0d498) 

Lauren identified this issue, so I'll add more details below as I have them. Thanks!

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/health-care/schedule-view-va-appointments/
- Test User _(if applicable)_:

## Desired behavior
The button label for all facilities other than Columbus and Mann-Grandstaff should be labeled "Go to the VA appointments tool"

## Acceptance Criteria
- [ ] Button label is updated on live site

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA PW team reviewed this in grooming and wanted to see if this is still a relevant issue or not.  Please advise.

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA Just checking to see if this defect is still an issue. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@FranECross I honestly have no idea. Looks like the last time I touched this ticket was in 2020, and I haven't been close to these widgets in a long time. That said, if this hasn't resurfaced as an issue in all this time, I think we're safe to not worry about it...especially given that the button was always directing to the right place and we're now so far into the MHV on VA.gov initiative. Thanks!

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA Thanks so much! I appreciate you dusting off memory cells to help me with these old tickets so I can get them closed and or worked on. 😁
