### ISSUE TITLE
Common component: Get Directions button

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15609]
## Acceptance Criteria
1. Create "Get Directions" hyperlink with a map icon displayed to its left
     - This is a variation of the **Small Button (icon with text)** CC. See [this story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15626) for details. 
2. Android: selecting this button will provide the option to launch Google Maps. It will use a combination of the location name and the lat/long:
     - `https://www.google.com/maps/dir/?api=1&destination=${URL-Escaped Name}+${Latitude},${Longitude}`
3. iOS: selecting this button will launch Apple Maps. 
     - `https://maps.apple.com/?t=m&daddr=${URL-Escaped Name}+${Latitude},${Longitude}`
4. This button will be used throughout the following confirmed, Upcoming Appointments detail pages:
     - VA Appointment
     - Community Care
     - VAVC at an ATLAS location
     - VAVC at a VA location

## Designs
Example on Appts detail screen: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432457680
.svg: ![button map.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c66ec841-ce84-4cb8-af40-8a0e8118d9ec)

**Comment by bessgreen** [comment]
Blocked: need lat/long from the service

**Comment by bessgreen** [comment]
Blocked: requirements needed - will lat/long be used?

**Comment by lexicalninja** [comment]
# Get directions:
### Android 
Use Google maps for android phones. Combination of the place name and the lat long

```javascript
`https://www.google.com/maps/dir/?api=1&destination=${URL-Escaped Name}+${Latitude},${Longitude}`
```


### iOS
Use Apple Maps for all iOS devices. 

```javascript
`https://maps.apple.com/?t=m&daddr=${URL-Escaped Name}+${Latitude},${Longitude}`
```

Apple Maps refuses to show a name, no matter how you try and format the query, this gets the address from lat long and displays that and leaves the name in the url in case Apple ever fixes this.

We should think about how to test or change Apple maps. At this time there is no way to get a name to display in the destination address. If this solution causes issues we can try something else with the map query option, but for now @ayushchak would like us to use this way.

**Comment by lexicalninja** [comment]
Had to change the url to take the location address, location name and lat long to cover some edge cases

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/19/2021 - Looks good in iOS and Android.  Closing.
