### ISSUE TITLE
Implement Videos template mobile UX and progressive enhancement

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15605]
## Implement Videos template mobile UX and progressive enhancement

[Design and accessibility feedback: ticket #11497 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11497)

**Test content in prod preview:** 
http://preview-prod.vfs.va.gov/preview?nodeId=6950 

Doesn't include missing youtube meta data:

1. Video title
2. Video
3. Missing: Pub date `Ready`
4. Missing: Video length   `Ready`
5. Missing:  YouTube video description    `Ready`

Updated Comments per discussion with CMS (1/27/21)

**Comment by jenniferlee-dsva** [comment]
full set of CMS meta data functionality will not be ready in 1.1, so we can implement the FE of Videos article template after Dec. 

(In 1.1, they will work on brining over the youtube video data + title. Post 1.1, they will add the other meta data we need for this template: video duration + video youtube description + video youtube publication date)

**Comment by brianalloyd** [comment]
Updated ticket details based on CMS confirmation that Missing `Pub Date ` is the last remaining requirement needed but is blocked due to an upgrade to Drupal 9 with an ETA of April 2021.  More details to follow.

**Comment by ncksllvn** [comment]
@kelsonic are you already working on this one?
