### ISSUE TITLE
Add article content type meta data to `All articles...` landing page listings and fix minor text issues

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15607]
## Add article content type meta data to `All articles...` landing page listings and fix minor text issues

**1/** 
**- [ ] The list display on the all articles landing pages should have the same content type superheads that are used on search results listings.**

**Today it looks like this:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/86ea54db-25fd-41e1-b318-b574d7e87ba6)

**We want it to look like this:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/0afd3b72-0e96-4abe-ac5f-111a413c8bc5)

**2/** 
**- [ ] The article content type superhead labels should be:**

1. Question and answer
2. Multiple FAQs  `<-- Currently showing just "FAQs"`
3. Step-by-step
4. About
5. Checklist
6. Images
7. Videos

This update should be done for both the `All articles in: Xcategory` and `All articles tagged: Ytag` landing pages.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn  - apologies if this wasn't clear. I do see the labels now on landing pages, but a couple of the content type labels are showing the older nomenclature. 

2/
**- [ ] The article content type superhead labels should be:**

Question and answer
**Multiple FAQs** `<-- Currently showing just "FAQs"`
Step-by-step   {Confirmed with Randi and Beth that this is correct WITH the hyphens}
About
Checklist
**Images** <-- Currently showing just "Media list"
**Videos** <-- Currently showing just "Media list"

![image](https://user-images.githubusercontent.com/43381063/98138781-7364a900-1e91-11eb-8682-114394306b9d.png)

**Comment by jenniferlee-dsva** [comment]
I'm seeing the content type labels showing up on the All articles category and tag landing pages! 

Rn, I'm only seeing article labels for the article types that are live, but will this also ensure that the right labels will show when other article types get published @ncksllvn? 

Thinking about `Images`, `Checklist`, and `Videos` in the future. Since we don't have any articles of these 3 types, I can't validate it using prod.

**Comment by ncksllvn** [comment]
Hey @jenniferlee-dsva , I'm looking at the code right now and it does reflect those updates. I suppose we could use the demo environment to further validate?

**Comment by jenniferlee-dsva** [comment]
Good idea -We definitely have test images, checklist, and video (unfinished) articles rn, that we can fake publish in the demo. Just asked Steve and Randi if they can get the demo updated for this.

**Comment by jenniferlee-dsva** [comment]
I was able to validate this in the demo! Looks right - closing. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/1caa96f4-ea76-42f0-b179-ec16fca77692)![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/0aaa86cc-6365-4b61-91f8-16058b56bd34)

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/ab280020-3e90-452d-b9e4-30f83008fb9a)
