### ISSUE TITLE
Correct critical broken links across va.gov-team repo

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1561]
@meganhkelley and @mnorthuis to fill out user story, goal, and dod

**Comment by rroueche** [comment]
From Andrew Gunsch:

I ran [`markdown-link-check`](https://github.com/tcort/markdown-link-check) on the entire repo to look for broken links, now that we moved everything. `find . -name \*.md -exec markdown-link-check {} \; | tee ../markdown-link-check-output`

output: [markdown-link-check-output.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/3575935/markdown-link-check-output.txt)

**Comment by mnorthuis** [comment]
Corrected broken links in key onboarding and practice area files.  Closing issue.

**Comment by gunsch** [comment]
Wait, we still have all the broken links identified in https://github.com/department-of-veterans-affairs/va.gov-team/issues/1561#issuecomment-528032768 above --- are those being tracked in another issue?

**Comment by mnorthuis** [comment]
The file was full of external links that weren't actually broken, for example it would spit out a bunch of links to vet.gov-team, but when I looked at the page it worked just fine.   

I have the file stored locally and have not forgotten the list, the focus of this ticket though was to get the critical files fixed. Some of the deeper research notes and meeting notes may require redoing once we bring more content in.   Sound ok?

**Comment by meganhkelley** [comment]
@gunsch we just updated the title and content of this ticket to be more narrowly defined to fixing critical links within the /platform area. We are going to make new (a) new ticket(s) for communicating with VFS teams re: fixing their own other broken links, and will link to this ticket when created.

**Comment by gunsch** [comment]
> The file was full of external links that weren't actually broken, for example it would spit out a bunch of links to vet.gov-team, but when I looked at the page it worked just fine.

That's because of the `vets.gov-team` being a private repo. I think for this round you can just ignore all the private-repo links, and only look at the others. It'll still be helpful once we move that content from `vets.gov-team`, since I think eventually we want to treat any links to `vets.gov-team` as invalid, right?

**Comment by mnorthuis** [comment]
Yes, absolutely.
