### ISSUE TITLE
Bug: Search button should not appear under the search bar - learning center

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15610]
## Search button should not appear under the search bar

This is a Medium. (Button function still works, so not a `critical`  launch blocker. It's very visible to the 6.6% of Veterans who still use IE though, so we should address this shortly after launch if unable to in time for it.)

- On this node http://learningcenter.web.demo.ci.cms.va.gov/node/8222/ 
- In IE browser

**In IE - search button is merged underneath the search bar:** 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/c910ed37-514f-4735-93cd-d80e0808db8a)

**It should look like this, per design:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/29b65d40-e451-46d3-ab35-c5593291dc84)

**Comment by jenniferlee-dsva** [comment]
Geez have I forgotten anyone to @ ?  LOL. For someone who has bandwidth - this looks relatively simple.

**Comment by jenniferlee-dsva** [comment]
I think Kelson is already working on a search bar thing - so maybe @kelsonic to consolidate into your other search bar ticket?

**Comment by kelsonic** [comment]
Oh good idea! I'll snag this one too then 💪

**Comment by ncksllvn** [comment]
Seems to be happening on Find Forms as well

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/58558060-9274-45e6-81ac-aa6080084959)

**Comment by ncksllvn** [comment]
I have to use SauceLabs to run an IE instance remotely. The LC isn't public though so I can't access it from SauceLabs. So I am testing against /find-forms/, thinking that if we can fix it there, we can fix it on /resources/ too.

I noticed a red squiggly on this CSS rule. I wonder if that is the culprit.

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/f838f584-3e82-422b-be6c-4bbf5d28b7a4)

**Comment by ncksllvn** [comment]
OMG that was it

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/69983ab9-baa1-437f-ac6b-2192903e614b)

It was missing a percentage sign...it should have been `flex: 1 0 0%`.

This is a design system change. I'll try to open a PR there.

**Comment by ncksllvn** [comment]
We have a fix for Find Forms!

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/824b0730-7a51-4b9e-8323-94e51e71acc5)

Screenshot shows staging but this will go to prod during today's deployment.
