### ISSUE TITLE
Finalize Images template FE - mobile and desktop - learning center 1.1

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15618]
## Finalize Images template FE - mobile and desktop - learning center 1.1

This is a follow on from the pre-work we already finished during 1.0: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13499

Test node with Images article content: http://preview-prod.vfs.va.gov/preview?nodeId=6954

AC:
- [x]  The FE is accessibility compliant
- [x] The FE works as mobile responsive view
- [ ] ~Pagination~ Show more feature is added per design ( `10 images per page`) - 12/9 updated
- [ ]  Design implementation is validated by @rtwell 

**Images article content fields - required unless noted as optional:**

H1
Intro text
Info alert `(optional)`
CTA button(s)
H2 section header` (optional)`   **_<-- Currently not showing in the FE though it is there in the CMS_**
Image
Image title
Image description `(optional)`  **_<-- Currently missing in CMS_**
Pagination if more than 10 images on a page

**Comment by jenniferlee-dsva** [comment]
@rtwell - can you drop progressive enhancement mobile version of this template here for FE engineer?

**Comment by brianalloyd** [comment]
@youngfreezyVA picking up this ticket for action.

**Comment by jenniferlee-dsva** [comment]
@rtwell - follow up to convo this morning: for images on mobile, iirc you said we would be using 'load more' (instead of pagination). would we use that 'load more' affordance on desktop, too? 

correct anything i've misunderstood ^. 

fysa @youngfreezyVA who is going to complete the Images article template.

**Comment by jenniferlee-dsva** [comment]
Correction - just tb w/ Ryan - he says design will stay with pagination for Images article template - desktop and mobile. @youngfreezyVA fysa. 

@rtwell - please drop mobile design here for Fareez. Tyvm.

**Comment by rtwell** [comment]
@jenniferlee-dsva incorrect! I advocated to sticking with pagination for now. I will drop mobile designs asap.

**Comment by brianalloyd** [comment]
@rtwell checking in to see if you have dropped mobile designs?  If so could you point @youngfreezyVA in the right direction so we can work details and closeout into next sprint for this task.  Thanks everyone, appreciate the support.  CC @jenniferlee-dsva

**Comment by jenniferlee-dsva** [comment]
TBC @rtwell - 
I'm not sure why this needs a mobile version because it's literally just the image title and an optional image description + image. 

But if there's progressive enhnancement involved, FE may  need a mockup.

**Comment by rtwell** [comment]
I would like to drop in some specifications regarding how to handle images on mobile, particularly w/r/t progressive enhancement. i'm collaborating with @jenstrickland to provide clear instructions and guidance.

**Comment by jenniferlee-dsva** [comment]
@youngfreezyVA - just looked over design updates with Ryan. His ETA for uploading all of the updated mocks and specs is EOD today, so you should have everything ready to go on Monday. 

And of course, always feel free to reach out to me or Ryan with requirements Qs.

**Comment by rtwell** [comment]
# Design 

1. There is one maximum optional H2 at the top of the image list
2. Images and their respective content are listed in the following order:
      a.  Title of image (h3)—These are always displayed as h3s, but will need to dynamically change to h2s if there is no h2 present (as it is optional)
      b. Image
      c. Optional image description
3. In lieu of pagination, we use a Show more interaction that displays after 10 images. This interaction reveals 10 more images at a time, until there are no more images. 
4.  There is no Show less interaction. Once a user reveals the next 10 images, they persist. 

## Mobile considerations

1. Images fit to the width of the viewport at the smallest breakpoint.
2. Images stay proportional to said viewport

![image](https://user-images.githubusercontent.com/12564977/101350790-96ea8d00-385d-11eb-90da-95824f287aa0.png)


## Desktop considerations

1. Images are max width 3 columns on desktop (25%)
2. Typography spans a max of 6 columns (50%)

![image](https://user-images.githubusercontent.com/12564977/101350774-8cc88e80-385d-11eb-94e1-3d3dace31e5b.png)

**Comment by rtwell** [comment]
# Progressive enhancement

I look to @jenstrickland for any corrections or additions to this:

![image](https://user-images.githubusercontent.com/12564977/101352430-2133f080-3860-11eb-920f-487412c7ac0c.png)

**Comment by youngfreezyVA** [comment]
hey @jenstrickland hope you had a good weekend... wanted to see if you had any input before i got started

**Comment by jenniferlee-dsva** [comment]
@youngfreezyVA - you can use this preview sample node to test with:  http://preview-prod.vfs.va.gov/preview?nodeId=6954

Or same node in staging: http://preview-staging.vfs.va.gov/preview?nodeId=6954

**Comment by jenstrickland** [comment]
@youngfreezyVA @rtwell Thanks for the nudge!

I recommend using a description list to sidestep heading order issues. Let me know if I can clarify any of this. 

For more info on responsive, progressive images: 

- https://dev.to/stefanoverna/how-to-offer-responsive-progressive-images-in-2020-in-one-line-5fed

- https://piccalil.li/quick-tip/picture-element-as-a-progressive-enhancement/

```html
<h2>Optional h2</h2>
<dl>
  <dt>Title of image 1 (styled as h3)</dt>
  <dd><!-- move styling into the CSS, rather than as shown in the dev.to link -->
    <picture>
      <source srcset="{{webpSrcSet}}" type="image/webp">
      <source srcset="{{srcSet}}">
      <img src="{{src}}" alt="{{alt}}" title="{{title}}" loading="lazy">
    </picture>
  </dd>
  <dd>Optional image description</dd>
</dl>
<dl>
  <dt>Title of image 2 (styled as h3)</dt>
  <dd>image</dd>
  <dd>Optional image description</dd>
</dl>
```

**Comment by youngfreezyVA** [comment]
thanks @jenstrickland I was able to implement the above minus the following tags:
`                                                <source srcset="{{webpSrcSet}}" type="image/webp">
                                                <source srcset="{{srcSet}}">`

unfortunately the cms does not return the properties `srcSet` or `webpSrcSet` for an image, it only returns the following properties:
`{
  "alt": "Sample alt text for image",
  "height": 640,
  "url": "https://prod.cms.va.gov/sites/default/files/2020-12/weird-dynamic-date-field.gif",
  "width": 1024
}`

**Comment by jenstrickland** [comment]
Thanks, @youngfreezyVA ! 

It sounds like the CMS will not allow for responsive images. Once it's in staging, we can test with throttled connections to validate the behavior works as desired. Perhaps even try using WebPageTest to render a video showing the behavior. We'd be looking for:

1. grey fixed container, with alt text renders when image doesn't
1. image loads into fixed container when it can

**Comment by youngfreezyVA** [comment]
hi @rtwell @jenniferlee-dsva @jenstrickland you can find my PR for this one here:
https://github.com/department-of-veterans-affairs/vets-website/pull/15270

only issue is what you've described in lieu of pagination, is essentially pagination (user clicking a button to display next set of records). Since I think the intent was to **_not_** implement pagination, i went ahead and used the additional info component instead. if we are implementing pagination, i would suggest that we groom pagination for this view into a separate ticket, and then I can look into re using the existing `src/site/includes/pagination.drupal.liquid`.
cc: @brianalloyd @kelsonic

**Comment by rtwell** [comment]
forgive my ignorance, but what am i looking at w/r/t that PR—this is where GH overwhelms me and I am paralyzed by fear of clicking on the wrong thing 👻 

as far as the additional info component goes, i would prefer a simple `+ Show more` as a link. We use it on VAOS, so i know it's in production (somewhere…ugh). If that truly isnt feasible, we can start with additional info.

**Comment by youngfreezyVA** [comment]
hehe no worries man. yeah, that is the react version of the `AdditionalInfo` component. since we're in a liquid template, i'll have to use the vanilla JS AdditionalInfo component which is what i'm doing :) Let me go ahead and update the "Show More Images" link text to "Show More".

<img width="772" alt="Screen Shot 2020-12-09 at 10 06 38 AM" src="https://user-images.githubusercontent.com/46791771/101669132-65f98c00-3a06-11eb-9825-3973520b966b.png">

**Comment by jenniferlee-dsva** [comment]
Updated pagination AC in og ticket description --> Show more, per grooming convo with @youngfreezyVA . Thanks Fareez.

**Comment by youngfreezyVA** [comment]
after going through the PR review process, I realized that my PR only updated the mobile view and not the desktop view. still working on this one.
