### ISSUE TITLE
Closed Claims detail page (UI) 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15624]
## User Story
As a user, I want to view my closed claim details. 

## Acceptance Criteria
1. The Closed Claims detail page should display the following elements that already exist on the Active Claims detail page:
     - Claim header with segmented selector
     - Need help section
     - Issues detail UI (when Issues is chosen from the Segmented Selector)
2. The following elements that are displayed in Active Claims detail should be **hidden** from the Closed Claims detail page:
     - Mobile alert
     - Claim step table
     - Estimated decision date
     - Find out why we sometimes combine claims
     - What should I do if I disagree with your decision
3. Create a new section between the header and the Need Help section:
     - Section should display information from the API when the claim was closed
     - This section will include a header (bolded) and informational text below it) 

## Designs
https://adhoc.invisionapp.com/d/main/#/console/20546460/432579848/inspect

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Claim" as Header 1
- Mark "Your [type] claim" as Header 2

**Segmented Selector**
- accessibilityLabel=Name of tab (e.g. Status or Issues)
- accessibilityHint="view your claim___" (e.g. status or issues)
- accessibilityRole="tab"
- Denote selected vs. unselected
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 1 of 2 or 2 of 2)

**Claim Closed Section**
- Mark "Your claim was closed on January 31, 2020" as Header 3

**Need Help Section**
- Mark "Need help?" as Header 3
- Link
     - Title= "800-827-1000"
     - accessibilityHint= “Dials this number via your device’s call function”
     - accessibilityRole= “link”

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...

**Comment by digitalken** [comment]
PASSING 1/11/2021 - Logged minor bug on accessibility issues. Moving tag to Design QA.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18382
