### ISSUE TITLE
Create Community Care / VA care selection page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1562]
## Story
As a veteran, I want to be able to choose between VA and Community Care when both are available.

## AC
- [ ] Page doesn't show unless veteran is eligible for Community Care
- [ ] Confirm behavior when either CC or VA doesn't have a matching facility with the type of care previously selected

![Screen Shot 2019-09-04 at 2.45.28 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/13a9cd16-e38f-4154-bead-af8459c76787)

**Comment by jbalboni** [comment]
Duplicate
