### ISSUE TITLE
Learning Center - About - Breadcrumbs copy mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15625]
## What happened?
On CMS Learning Center demo-environment, About page breadcrumbs didn't match copy specs.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [unauthenticated]

## Steps to Reproduce
1.  Go to http://learningcenter.web.demo.ci.cms.va.gov/resources/ [requires VA network access via CAG].
1.  Near top of page, observe the breadcrumbs end with **Node** instead of the page-title.

**Screenshot**
![lc-mvp1 0-bug-about-breadcrumbs](https://user-images.githubusercontent.com/587583/97641714-c3aab980-1a00-11eb-97da-7f74e1fb560f.png)

## Desired copy
Breadcrumbs should end with same text as in H1 page-title, **Helpful VA phone numbers**.

## Acceptance Criteria
[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
This is a breadcrumb bug that Ethan's PRs will address. @brianalloyd could you make sure we rebuild the demo site on Monday to validate that the new PRs have correctly addressed this? 

**The breadcrumb above SHOULD be showing:** 

Home > `Resources and support` > `Helpful VA phone numbers`

**Comment by jenniferlee-dsva** [comment]
resolved and validated.
