### ISSUE TITLE
Update "done" common components & add to ReadMe

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15626]
## Dev task:

1. Review the following common components that we've already built in the app against the design specs. Update the current implementation of these components as needed to match the criteria below. 

- [x]  **Profile header**
     - Background color: gray-dark #323a45
     - Headline text: Bitter Bold
     - Headline color: white #ffffff
     - Subhead: Mobile Body
     - Subhead color: white #ffffff
     - Margin: no gutter L/R; marginBetween vertical 
     - Internal padding: 20px total

- [x] **Small button (icon with text)** (ex: click-to-call buttons)
     - Padding-top: 10px
     - Padding-bottom: 10px
     - Text style: Mobile Body Link
     - Margin: standard gutter L; marginBetween vertical 
     - Icon background color: primary #0071bb 
     - Icon color: white #ffffff
- [x] **Back button**
     - Text: Mobile Body
     - Icon: chevron-left
     - Color: white #fffff
- [x] **Save button**
     - Text: Mobile Body
     - Icon: chevron-left
     - Color: white #fffff
- [x] **In-app web view**

2. Update the ReadMe with details for the Common Components listed above, as well as the following CCs:
- [x] [Expand / Collapse](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15441)
- [x] [Editable text view](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15200)
- [x] [Address summary](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15446)

**Comment by digitalken** [comment]
Added to TestRail.
