### ISSUE TITLE
Images 404 with cms-export build

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#15628]
Images 404 with cms-export build, e.g. 

http://localhost:3001/img/styles/3_2_medium_thumbnail/public/2019-02/university-drive-consolidation-building2.jpg

**Comment by meganhkelley** [comment]
Removed facilities label, @mpelzsherman thinks this is a general issue not specific to his team

**Comment by theodur** [comment]
I ran a local cms export build, and I'm able to see images 🤔, including the image linked in the ticket. Can you try re running the cms export build and see if you are still having this problem @mpelzsherman.

**Comment by mpelzsherman** [comment]
I wasn't seeing the assets because I didn't run `yarn build`. I thought `yarn build:content` was enough. Closing.

**Comment by theodur** [comment]
The images in the CMS export build are not being saved in the same paths as they are in the GraphQL build.

E.g., the same image being saved in different paths:

GraphQL Build: `/img/styles/3_2_medium_thumbnail/public/2019-02/university-drive-consolidation-building2.jpg`
CMS Export Build: `/img/2019-02/university-drive-consolidation-building2.jpg`

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/15031.
