### ISSUE TITLE
Common component: Segmented selector

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15622]
## Acceptance Criteria
1. Create common component for the segmented selector, which will appear throughout the app including the following pages:
     - Appointments landing page
     - Claims landing page
2. Details:
     - Background color: gray-lighter #d6d7d9
     - Background border: 2px solid gray-lighter #d6d7d9
     - Background border radius: 8px
     - Active button color: white #ffffff
     - Active button radius: 8px
     - Active Text: Mobile Body Bold
     - Inactive button color: gray-lighter #d6d7d9
     - Inactive Text: Mobile Body
     - Internal padding: 4px total

## Designs
Example from Appointments: https://adhoc.invisionapp.com/d/main#/console/20546460/432442341/preview

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/19** 

PASS - on iOS and Android. Moving to design QA
