### ISSUE TITLE
Debt Letters Diary Codes - Rework 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15637]
Hi Peggy, The DMC found an issue with one of the diary codes entries info below - Can you please review?

OLD Content: 

![image.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/e0f776ba-9ec8-401a-bbed-b61fbb5ff024)

New: 

We’re in the process of referring this debt to the U.S. Department of Treasury as required by law. Next Steps: Please pay the full amount online or by phone now. Immediate payment may prevent referral.

[Pay online now](https://www.pay.va.gov/)

Or make a payment over the phone at 800-827-0648 (or 612-713-6415 from overseas).  We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET

**Comment by leahkeeler** [comment]
@peggygannon Checking in on this - as soon as thi sis done, we can move on to staging : )sorry to be a pain

**Comment by peggygannon** [comment]
@leahkeeler Here you go. I couldn't figure out where that one status got mangled. Here's an update: 

**Status:** We're referring this debt to the U.S. Department of the Treasury today. 
**Next step:** Please pay the full amount online or by phone now to prevent referral.  If we don't receive your payment today we're required by law to refer your debt to the U.S. Department of the Treasury.  

Pay online now

Or make a payment over the phone at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET

**Comment by leahkeeler** [comment]
Thank-you so much Peggy!!! I think we are done, been a marathon cc: @craigwheeler

**Comment by craigwheeler** [comment]
awesome ill take care of it thanks everyone! :grinning:
