### ISSUE TITLE
GIDS: Add the ability to export the Accreditation file type

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15630]
As an EDU team member, I need the ability to export the Accreditation file type so that I can review the contents that have been used to generate the most recent version.

## Assumptions:
1. This work is **not** completed behind a prod flag. 

## Acceptance Criteria
1. The user can export the Accreditation file type containing the originally uploaded data in a zip file containing the following csv files:
    a. InstituteCampus
    b. AccreditationRecord
    c. AccreditationAction

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/766
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/764

**Comment by delli-gatti-michael** [comment]
Tested by testrail test case:
https://dsvavsp.testrail.io/index.php?/runs/view/790&group_by=cases:section_id&group_order=asc

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-11-16 at 8.53.27 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/82366c5c-ac4f-42b5-a779-e442e61a1c6b)

**Comment by delli-gatti-michael** [comment]
This is now in Staging. Closing this issue
