### ISSUE TITLE
IA Feedback - Usability testing prep - VA Payments

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#15639]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description
This issue describes IA feedback  - FEEDBACK IS BASED ON PROTOYPE LINKED IN ISSUE, NOT ON WHAT IS AVAILABLE IN STAGING.

**MUST**
- Update breadcrumb in prototype to match IA recommendations: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-payment-history.md
  - Breadcrumb should be: Home > View VA payment history

**CONSIDER**
- How does this tool relate to/support the debt management tools?  What kind of crosslinking should there be, or should there be a deeper connection between the tools?  Consider exploring in research how users think about overpayments - realizing that this may be for a future iteration, but may be a good opportunity to gather some feedback:
  - If they realized they're amount is off, what would they expect to happen or do next?  
  - If they recently made made a payment back to VA for an overpayment, would they expect to see it here?
- Do users expect payments returned be intertwined in the same table?  Realize there is different data in the tables, but if users expect to find them together is there a way it can be accomodated?

## Definition of Done
- [x] Must feedback is implemented on prototype/artifacts
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by jason-gcio** [comment]
- "Must" items are already in staging.
- Consider items:
  - How does this tool relate to/support the debt management tools? What kind of crosslinking should there be, or should there be a deeper connection between the tools? Consider exploring in research how users think about overpayments - realizing that this may be for a future iteration, but may be a good opportunity to gather some feedback:
    - If they realized they're amount is off, what would they expect to happen or do next?
    - If they recently made made a payment back to VA for an overpayment, would they expect to see it here?
  - Do users expect payments returned be intertwined in the same table? Realize there is different data in the tables, but if users expect to find them together is there a way it can be accommodated?
  
**We are considering the crosslinking and further integrations with other debt management tools and will consider these items as we get closer to them.**
