### ISSUE TITLE
Offboarding of Cindy Cruz, Dustin Hughes

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#15646]
# Instructions
Fill out name of individual and *Description* section below.

# Description
The following individuals need to be offboarded:
   > Cindy Cruz
   > BAH Team, UX Designer, 10/16/20
   > @ccruzgra 
   > Socks, GitHub, DSVA Slack, Domo, Google Analytics

   > Dustin Hughes
   > BAH Team, Developer, 11/2/20
   > @hughes-dustin 
   > Socks, GitHub, AWS, DSVA Slack
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jbritt1** [comment]
Slack removals for both users submitted with the slash commands above ^

**Comment by jbritt1** [comment]
PagerDuty access not applicable to either user.

**Comment by jbritt1** [comment]
All Operations related line items complete for these two users.

**Comment by jbritt1** [comment]
@joanneesteban / @bsmartin-ep / @jonwehausen, can one of you confirm GA / DOMO access for these users as time allows pretty please?

**Comment by jonwehausen** [comment]
Hi @jbritt1 , 

Each of these accounts have been removed from Google Analytics and/or DOMO, thanks.

**Comment by jbritt1** [comment]
Thank you @jonwehausen!

**Comment by jbritt1** [comment]
All line items complete for both users (Cindy Cruz & Dustin Hughes) at this time. Closing.
