### ISSUE TITLE
DMC "Debt" Rebranding 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15641]
The DMC would like to explore taking the word "debt" out of the debt portal URL /manage-va-**debt** 

From Meeting on 10/30: 

- Mikki, Danielle, Beth to collaborate to see if there are any options

**Comment by leahkeeler** [comment]
Hi @DanielleThierryUSDSVA @mnorthuis @bethpottsVADEPO - Checking status of how to move forward with this?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @leahkeeler. We met on this yesterday. I'm writing up a next steps recommendation this week and will share with you as soon as it's ready. Thanks!

**Comment by leahkeeler** [comment]
Thank-you y'll are the best

**Comment by DanielleThierryUSDSVA** [comment]
Just connecting to this issue with the recommendations: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15961

**Comment by leahkeeler** [comment]
Closing ticket - DMC will stay with "Debt" as originally scoped
