### ISSUE TITLE
Visually Impaired Veteran - VA.gov Issues/Session Opportunity

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#15645]
## Point of Contact

John Hashimoto @johnhashva 

## User Story or Problem Statement

Veteran John Stuart Newbury (prefers "Jack') is 100% blind and reported at a recent USB VA town hall session in Maine that he has trouble using VA.gov.   In general: Not enough options with specialized accessibility instructions.  Too much content to wade/through.   He says he even had to "recognize matching photos" to authenticate to sign in and upload travel reimbursement documents. Jack does have a JAWS screen-reader and his adept with it.  And still, VA.gov and government sites in general need to be "better" he says.

Contact:
Email: jackn1@midcoast.com (preferred)
Phone: 207-809-0989

## Recommendation

Have an accessibility and UX SME connect with this veteran who welcomes the opportunity for a guided VA.gov walk-through as a way to capture more detailed examples of his challenges/struggles.   This veteran is also very plugged into the visually impaired community and could help us capture more insight/feedback.

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by artsymartha68** [comment]
I have had a couple of emails with Jack so far. 

He does not use a smart phone so is not able to participate in any user research around our new flagship mobile app. 

He is having the most struggles with the Travel Benefit system, and I'm getting in contact with that team to understand their a11y compliance. We think it's the new system mentioned here:
https://content.govdelivery.com/accounts/USVHA/bulletins/2a8412d

**Comment by artsymartha68** [comment]
Closing this out, it's very old and we have made strides in the intervening years, especially with the travel reimbursement project.
