### ISSUE TITLE
View Payment History - VSA-QA Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15648]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

[Product/Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-payment-history/README.md)
[Product/Feature Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1397)
Product/Feature Pre-Launch Checklist: \[provide link]
Product/Feature Copy deck(s): \[provide link, or type "In Design prototypes"]
[Product/Feature Design prototypes](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/grid/)

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to your team roles in VSA Master Org Chart (linked above)
Design/Research: 
Content/IA: 
Front-end: 
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs (ideally, use [this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md) from VSA Design Lead).  IMPORTANT for authenticated-experiences: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

1. Has Received & Returned Pmts - [design prototype](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/6a2de0f2-3a3b-4da0-b252-471e5cdcb7e9/) - `vets.gov.user+228@gmail.com` (Colder) - [TestRail test-case](https://dsvavsp.testrail.io/index.php?/cases/view/1006)
2. No Pmt History - [prototype](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/338e991f-d104-4bf4-b040-ced7f18617a0/) - `vets.gov.user+4@gmail.com` (Alfredo) - [test-case](https://dsvavsp.testrail.io/index.php?/cases/view/1016)
3. API Error - [prototype](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/b605cd69-728a-4b12-988b-558dc734375c/) - [no Staging test-account] - [test-case](https://dsvavsp.testrail.io/index.php?/cases/view/1125)
NOTE: This API error can't be tested on Staging -- Team will provide local-environment screenshot of the error.

## How to configure this issue

- [x] Product Manager added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Actual Test Runs completed on Staging \[or optional [VSA-QA Test Run ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=tlei123&labels=vsa-qa&template=vsa-qa-test-run.md&title=%5BProduct%2FFeature%5D+VSA-QA+Test+Run) created and tracked]

**Comment by tlei123** [comment]
@jason-gcio , I've added 3 scenarios above, which have corresponding links to prototypes and TestRail test-cases:
- No Received Pmts
- No Returned Pmts
- API Error

We'll need Staging test-accounts and matching API mock-data for these.  

NOTE: For API-Error scenario, I've heard it may be tough to mock Staging API-response for this.  Consider the alternative of having F/E Eng. test locally in just attaching screenshot(s) here in this ticket [instead of QA'ing Staging].

cc @pjhill

**Comment by tlei123** [comment]
@jason-gcio , sorry... what exactly was that "additional question" you mentioned in our Shared Support Standup yesterday?  Was that for this, or actually for Ch31?

**Comment by jason-gcio** [comment]
Probably not for this...trying to remember what the additional questions were. 🤔

**Comment by tlei123** [comment]
@jason-gcio , all QA test-runs completed.  TestRail links are below, and will also be added to Stg Rvw #17379 ...

TestRail links:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/724)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/3&group_by=cases:section_id&group_order=asc&group_id=213)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/175)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/176)
