### ISSUE TITLE
IA Request - Healthcare Experience - Questionnaires MVP

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#15647]
## Required Inputs:
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
- Link to [Visit Intro MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
- Link to or attach prototype or [mockups](https://zpl.io/VOOek8j)
- Link to research [readout/results](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/mvp-usability/research-findings.md)
- Link to [MVP-Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/research) 
- Link to [Discovery-Research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/questionnaire/discovery/user-research) 

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords** - Provide a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** - included in mockups

**Suggested URL(s)** - https://www.va.gov/health-care/refill-track-prescriptions/ (not RX but in this menu under manage benefits

**Suggested entry points** - Link in email direct to VA.gov/Questionnaire Manager, Healthcare/manage health benefits, 

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful? VAOS appt. list (future), My VA in healthcare section (future)

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized? none

## Definition of Done
- [X] Issue is created, tagged and assigned to VSP Product Support
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [x] Requesting team closes issue upon implementation

**Comment by mnorthuis** [comment]
@abuckley3385 I do not have access to look at the mockups in Zeplin, can you add me please?

**Comment by mnorthuis** [comment]
Corrected prototype URL for reference: https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780

**Comment by mnorthuis** [comment]
@abuckley3385 @kristenmcconnell  I have a couple of questions regarding some of the user flows represented in the diagram below.  Wondering if you would like to meet to discuss or if you have answers/thoughts to any of these at this point?
cc @peggygannon @DanielleThierryUSDSVA 

![image](https://user-images.githubusercontent.com/20994159/98176128-96a54d80-1ebd-11eb-8a54-a1a804ce7cc6.png)

**Comment by kristenmcconnell** [comment]
@mnorthuis I quickly updated the user flow, which might help answer some of your questions. I would definitely be willing to meet, so I can answer the rest of the questions and any others that arise from the answers.

![User Flow.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/72259a66-0a9c-490e-92bd-2abfe0975588)

**Comment by mnorthuis** [comment]
@kristenmcconnell I think a discussion would be helpful, I have some questions about the above changes, and may be helpful to just talk through things.  I'll ping you in slack to find a time.

**Comment by kristenmcconnell** [comment]
Updated user flow after talking through learnings about text messaging with engineering.

![User Flow.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/ec700ec4-1c8e-425e-882c-c6c9491fed4c)

**Comment by kristenmcconnell** [comment]
@mnorthuis Thoughts on this for the bookmarked states. @mdewey See the question in the red circle. Let me know.

![User Flow.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/7c85dac4-84dd-4df0-8fa9-94f065457467)

**Comment by mnorthuis** [comment]
Hi @kristenmcconnell,  here's where my flows landed after Friday's discussion.  I'm working on finalizing the documentation now, but wanted to see if this matches your thoughts.  Also, please note #3 in the flow.  We had talked about using that unauthenticated view of the questionnaire, but wondering what your thoughts are on simplifying the flow to direct them to to the sign in and the list page so the user doesn't try to link to a form that is already submitted or no longer available.   Let me know your thoughts.

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/f0a7c9e3-0586-41c6-a90b-9d216a454c27)

**Comment by mnorthuis** [comment]
FYI,  in progress IA documentation is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-questionaires.md

**Comment by kristenmcconnell** [comment]
@mnorthuis I just talked through a few of the flows with engineering. 
@DanielleThierryUSDSVA and @peggygannon I had a question about the proposed H1s. 
Attached are some of our questions and comments.

@mdewey Let me know if everything looks correct based upon our discussion.

![User Flow.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/6e02c616-f62d-4008-8d1b-13b40ef0b6a6)

**Comment by mnorthuis** [comment]
Thank you!  I will update my notes for your #1 and #3 notes above.  

For #2, please keep me posted on your conversations.  Taking users to the list page and scrolling to a questionnaire on the page with messaging will work except in those cases where a questionnaire (or link) is no longer valid.  For debt letters, we opted to always send the user to the overarching list page any time they bookmark a detail level, but for that work, invalid and duplicated IDs were a big concern and a big part of that decision. 

For #4, my flows do not represent final H1s, they are just place holders.  That said, I had discussed with Peggy and Danielle about keeping those relatively generic for this initial iteration until we understood more about what data we could use to drive a more dynamic heading.  I also thought that was what we decided in that Friday meeting.  If you think we can do a more dynamic H1 such as "Answer questions for your upcoming [stop code] appointment", that makes for a better H1, but only if that stop code data is clean and all of the questionnaires are for "upcoming appointments".  So let us know what you are thinking there.  That dynamic H1 will likely also feed into the breadcrumb, but the URL will likely remain pretty generic and parameter driven.

**Comment by kristenmcconnell** [comment]
#2. I will let you know. Good to know about debt letters. I will talk to them, because their use case may help with #3 UI.

@peggygannon and @DanielleThierryUSDSVA 
#4. After exploring stop codes more, we think that we can make a more dynamic H1 now. Our first use case's stop code would translate to "Primary care." Also, we thought about what happens to this questionnaire once the appointment is completed and the questionnaire moves to the "completed" tab on the "Your health questionnaire"'s page. Keeping the H1 as "upcoming" doesn't really work in that instance. Could we come up with some H1 wording for a questionnaire that works when it is both "upcoming" and the completed status? Hence why, the team thought about "Primary care questionnaire." Let me know.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell @peggygannon. Yes, sounds like a simple "[appointment type] questionnaire" is the best way to go. Even without "upcoming," an H1 of "Answer questions for your [appointment type] appointment" or another CTA-based H1 wouldn't work once it's in the "completed" tab. Only future concern, which I think @mnorthuis mentioned, is making sure stop codes translate to plain language appointment types. Peggy, let me know if you have other thoughts here re: H1. Thanks!

**Comment by mnorthuis** [comment]
I was wondering if we could use "Answer [appointment type] questionnaire" for the actual form, but drop "Answer" when its displayed on the list page?

**Comment by kristenmcconnell** [comment]
Yes, we will keep an eye on stop codes. Like I said, our first use case will translate to "primary care." It should be close to/the same as the list of specialities in VAOS. 

@mnorthuis I think that your suggestion could work.

**Comment by mnorthuis** [comment]
@kristenmcconnell  Draft of IA is complete and ready for review and can be shared with your team.   I know we have a couple of things to finalize, so will keep this open until those questions are answered.  Findings in research and development, as well as content changes can impact URLs and breadcrumbs, so please keep me posted if anything impacts the information here.  

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-questionaires.md

cc @DanielleThierryUSDSVA @peggygannon

**Comment by kristenmcconnell** [comment]
@abuckley Review @mnorthuis's documentation listed in the previous comments. It looks good to me.

**Comment by kristenmcconnell** [comment]
@mdewey Check it out too.

**Comment by mnorthuis** [comment]
Keeping this open until after research to confirm no changes are needed to draft IA based on findings.

**Comment by mnorthuis** [comment]
All IA work was completed on 11/20/2020, if there is no feedback based on any further development or research findings, this can be closed at your discretion.
