### ISSUE TITLE
Build VA facility selection page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1564]
## Story
As a veteran, I want to be able to choose which VA healthcare system and facility I want to visit for my appointment.

## AC
- [ ] Page shows all registered healthcare systems
- [ ] Page only shows 'select healthcare system' option to veterans who are registered at multiple
- [ ] Page shows all VA locations that have a given selected service once a system is selected
- [ ] Confirm UI for 'no matching facilities for your type of care' with Ryan

![Screen Shot 2019-09-04 at 2.58.14 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/b9bac65c-79f1-47d9-a253-db50c80c5dd5)

**Comment by markgreenburg** [comment]
@rtwell please chime in if this needs more up-to-date mocks; believe this was an area where usability research may have changed our minds a bit.

**Comment by rtwell** [comment]
This is a rough first draft. @peggygannon and @lalexanderson-dsva would love to get your thoughts on this. 

**VA Medical center** link would take the user to the facility locator 

**Go here to manage your pending appointments** would take the user to their pending appointments page

![image](https://user-images.githubusercontent.com/12564977/65170696-32080480-da17-11e9-86a4-1f98b00fe6d1.png)
