### ISSUE TITLE
[DESIGN] CC provider list MVP

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15652]
### Request
Provide desktop, tablet, and mobile specs for the first version of the Community Care provider list to replace the preferred provider form.

- [x] Default state with language selector: no selections, first load of providers

- [x] Error states: Closest city/state not selection, language preference not selected

- [x] Current location (instead of address) selected + current location can't be determined

[/] Default state without language selector + language selection page _(Deferred to next iteration)_
[/] Missing Address state: user doesn't have address in profile _(Deferred to next iteration)_

### Requirements
- Option to select closest city and state
- Option to select preferred language
- Option to select one preferred facility from list
- Option to select no facility preference

### Additional Notes
- Current form: 
![Community Care - preferred provider form copy.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/7f2de265-ee81-41c9-9ac3-9a51456ba7f8)
- [Peggy's content feedback on the test prototype](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15711)

**Comment by outerpress** [comment]
@laurenernest @lenaecb I just want to confirm the "what's your closest city/state" question can be removed/replaced with the list. Does it drive any functionality later in the scheduling flow?

![Screen Shot 2020-11-04 at 10.09.22 AM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/a857220d-5c91-4fb4-81c7-71d493cd2836)

**Comment by laurenernest** [comment]
@outerpress Thanks for calling that out. Let's keep it to err on the side of caution since we're sending that data in the request. I've updated the requirements in the description to reflect that.

**Comment by outerpress** [comment]
@laurenernest a couple of other areas this story touches:

**Review appointment details**
We'll want to clean up the spacing and make sure the language still makes sense (I'm not sure it's clear why we're showing the closest VA facility here).

![Preferred provider page.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/3e443619-6794-43fa-a233-0118b8c1be4d)

**Appointment card**
I'm guessing we don't want to show contact information for appointment requests(?). At a minimum we'll need to make sure the provider name is coming through.

![Screen Shot 2020-11-05 at 5.03.11 PM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/ad7d144b-65be-4718-8290-3e3a8285d903)

**Comment by laurenernest** [comment]
@outerpress I'll make separate tickets for each of those areas: one for the review page and another for the appointment card.

Re: closest facility showing in the review readback - that is odd considering we don't show the language selection. I'm ok with removing it if there's a preferred provider listed, but we should keep it in if the user chose "no preference".

For the appointment card- let's follow the same pattern we're currently using for the contact information. We can make more changes when we do the homepage work.

**Comment by outerpress** [comment]
Thanks @laurenernest !

[Here's an expanded prototype ](https://adhoc.invisionapp.com/share/WAZCTQLXPUK) for the feature, including an error state, and disabled state when "no preference" is selected. 

There are still some sticky parts - I'll want to get feedback at our Design and Content Sync on Monday.

The big one is, we're still loading a lot of decisions on this page so I think the sooner we break out the language question after this is done the better. Also, I'm hoping the language in the alert at the end of the flow can be pared down.

**Comment by laurenernest** [comment]
Here are the placeholder tickets for the styles cleanup
- Review page #15943 
- Request card #15944 

I've also shelled out the work for the language selection so it can be a fast-follow #15945

**Comment by lenaecb** [comment]
@outerpress - one thing I would recommend here, if we can make it feel like a natural part of the experience is to make sure that we keep the 'type of care' visible throughout the booking flow. 

So, something to consider is adding it to part of the H1 - "Tell us about your community care preferences for {type of care}" though that is going to get rather word-y. 

I just want to make sure we're making it very easy for veterans to remember what they had selected and what this appt is for throughout.

**Comment by outerpress** [comment]
That makes sense @lenaecb - is there any background/research I should look at around the problem of veterans losing context during the booking flow?

I agree with you on the wordiness issue - if the header gets too long it won't be read. I'll play with some other options.

And I'm assuming we'd just be making the change for the provider selection page, not the entire booking flow, for this story, right?

**Comment by lenaecb** [comment]
I think it's something for us to keep top of mind @outerpress, but to your point, I believe this was something we observed in our July research (even though that was VA requests).

**Comment by laurenernest** [comment]
@outerpress I updated the description of the ticket with the different state specs we're tracking, including the new one for the Missing Address.

For missing address, it's for the user that doesn't have a residence address in their profile. This is the warning they see earlier in the flow.
![missing address alert.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/11f46c66-0bee-4abd-967a-646425eb2369)

**Comment by outerpress** [comment]
@laurenernest - that's interesting. If the address is missing are we expecting to let them enter a provider some other way, or removing the provider selection question?

Separately, [here's the new version of the prototype](https://adhoc.invisionapp.com/share/BFZED2H362S#/437633293_VAOS-CC-MVP-01). Changes:
* Made the provider question optional, and removed the "I don't know" question
* Added a "Cancel" option to the list
* Added a "Change provider" option to the final card
* Added mobile layout specs

Still to do:
* Alert state when the selection is in progress but not complete
* Missing address state
* Default state without language selector + language selection page
* Add desktop/tablet specs

**Comment by laurenernest** [comment]
@outerpress I have open questions related to the missing address state, but I'm inclined to at least keep the option to select a provider based on current location. A different address entry method might have a high LOE or performance impact for this subset of users so I want to check with the devs to see what's feasible too. We can brainstorm more offline.

**Comment by outerpress** [comment]
@laurenernest - we've seen zero folks drop off the list-loop pattern during research so far (4 participants) - everyone has easily selected a provider.

Given that, I recommend we drop the alert/error state from MVP. We could track drop-offs as part of the analytics if it's a concern.

**Comment by laurenernest** [comment]
@outerpress Agreed. For MVP, we'll use the current validation response with the addition of the red bar next to the list that you've outlined here https://adhoc.invisionapp.com/d/main#/console/20765993/437074027/preview
