### ISSUE TITLE
[Bug] Form 562 Service history

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#15654]
If a veteran has "Air Force National Guard" prefilled as their service branch (from EMIS)  and they're on the service history page http://va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history and click "continue" nothing happens and no errors are visible. Note: "Air Force National Guard" is not a choice in the drop-down

More than 300 veterans were prevented from completing Form 526 this month because of this bug.

**Comment by Mottie** [comment]
We include "Air National Guard" in our list... maybe we can change this name in the form prefill?

https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/21-526EZ-allclaims/schema.js#L293-L306

Or would it be easier to fix when the prefill is passed in the API call?

**Comment by annaswims** [comment]
yeah! let's just change  `Air National Guard` to `Air Force National Guard` in our drop down. I checked and  EVSS just takes a string.   When we do that, I'll have to update all in progress forms that might say  `Air National Guard`, but that's not that bad. .

**Comment by annaswims** [comment]
I take back what I said earlier. Seems like we should keep `Air National Guard` as the proper term and replace the term `Air Force National Guard` in in-progres forms and transform it in the future.

**Comment by annaswims** [comment]
I have the data for affected veterans if we want to email them.

**Comment by annaswims** [comment]
all past data has been corrected.
