### ISSUE TITLE
DebtRes FSR Ch 8 - Confirmation Hifi Desgn

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15657]
As a Veteran who filled out the FSR form and submitted the form, I would like to see a confirmation that the form was submitted and what I should expect next

**Comment by 3obryandogs** [comment]
I added suggested content to Becca and Riley's FSR outline.

**Comment by rebeccawalsh** [comment]
This issue is a design ticket assigned to Riley and me. Reopening because it was closed in error.

**Comment by rebeccawalsh** [comment]
Confirmation screen can be found here: https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134209101/simulate/sitemap?mode=i

**Comment by 3obryandogs** [comment]
Becca,
Do you want me to leave comments there? (a missing phone number, style change)
Thanks!
Susan

**Comment by 3obryandogs** [comment]
Becca,
I left comments on the preview page. A few VA style changes, please.
Thanks!
Susan
