### ISSUE TITLE
Update Community Care preferred provider form to list

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15653]
## Issue Description
As a user, I would like to choose a preferred community care provider from a set of options so that I don't have to manually enter facility information in a form

---
## Acceptance Criteria
- [ ] Update is behind feature flag
- [ ] User can select closest city/state (Note- existing behavior that should be maintained) 
- [ ] User can select preferred language spoken by provider (Note- existing behavior that should be maintained)
- [ ] User can choose no preferred provider
- [ ] User can select a preferred provider from a list of options
- [ ] If user is selecting a preferred provider, min/max selection = 1 provider
- [ ] Max provider options presented to user = 20
- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs: 
- Interaction: https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/437633275
- Individual screens: https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/437633275?browse
- [ ] DESIGN - Max provider options before pagination = 5

**Comment by laurenernest** [comment]
Separate into additional tickets:
- Analytics
- Map PPMS data into format for CC submission
- Sorting by address and current location

**Comment by jbalboni** [comment]
Latest prototype: https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/437633293_VAOS-CC-MVP-01

**Comment by laurenernest** [comment]
@jbalboni @LanceGundersen Added the mobile spec links to the description: One for the page default and one for the flat list. The desktop and tablet versions should be ready later today.

**Comment by laurenernest** [comment]
@jbalboni @LanceGundersen Description has been updated with the project link for the individual state specs and interactions for desktop, tablet, and mobile.
