### ISSUE TITLE
Headers for the webviews

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#15669]
# Tasks

- [ ] Decide: What is the best way to implement this?

- [ ] Coordinate: Meet with VFS Frontend team

Discussions to date: 
- https://dsva.slack.com/archives/C5HP4GN3F/p1601322739034000
- Charles brought this up in 10/27 demo

**Comment by ayushchak** [comment]
Closing since we have decided (and implemented) - headers are hidden in VA.gov webviews.
