### ISSUE TITLE
Check direct schedule feature flag in getLocationsByTypeOfCareAndSiteIds

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#15664]
We should incorporate the direct schedule feature flag into the logic we have to fetch available facilities. In theory this shouldn't make a difference because direct scheduling is turned off in VATS, but we could use the flag to save a call to direct booking eligibility criteria.

**Comment by narin** [comment]
Verified on staging.  Closing out
