### ISSUE TITLE
[Development] BDD/526: Add SIP ID to Form Data So it Can be Given to Call Center

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#15679]
## Issue Description
While we were discussing KPIs for BDD, we realized that we would be much better at diagnosing issues with BDD and 526 in general if the Save in Progress ID is given to the folks at the call center.  This will allow us to do much better debugging of all of the front end validation issues.  This ticket will likely have a small design element to determine how/where to best display the data to the user.  We should also send an email to the call center folks for them to know to ask this when a veteran is on the 526 form.

## Acceptance Criteria
- [x] How/where design completed
- [ ] Implementation
- [ ] Contact call center with information on how to use this (provide screen shot examples and some text on how this should be accomplished)
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
I have created a design for where the SIP data will be located on the form:

<img width="936" alt="Screen Shot 2020-11-17 at 9 11 34 AM" src="https://user-images.githubusercontent.com/54544300/99400381-e5d38100-28b4-11eb-80f3-c5ac144776fb.png">

Let me know if you have any questions!

**Comment by peggygannon** [comment]
Hi, @Mottie 

I have a few followup questions: 

--Will this application ID number now go on every saved message across all forms? 

--is this application ID number the same number on that will populate on the form confirmation page screen after a user submits their application? 

Here is my content recommendation: 

Your application has been saved. It was last saved on [Month, date, year] at [00:00 a.m. or p.m.]
Your application ID number is {number]

**Comment by Mottie** [comment]
> Will this application ID number now go on every saved message across all forms?

Yes, it would give the developers access to the Veteran's save-in-progress data for any of the forms

> is this application ID number the same number on that will populate on the form confirmation page screen after a user submits their application?

No, the ID on the confirmation page is the submission ID. The save-in-progress data, and associated ID, are completely removed once a form has been submitted (I don't know if this is true across all forms, but it is true for form 526 and HLR)

**Comment by Mottie** [comment]
Also, we don't always show the user a submission ID. For our HLR form, the submission ID is super-long, e.g. `12a3b4c5-67d8-901e-23f4-56a7890b12cd` - also known as a [universally unique identifier](https://en.wikipedia.org/wiki/Universally_unique_identifier).

**Comment by Mottie** [comment]
@peggygannon adding the extra content has caused an overflow, so the screenshot now looks like this

![Screen Shot 2020-11-17 at 5 24 59 PM](https://user-images.githubusercontent.com/136959/99462735-efcba300-28f9-11eb-86f7-677abb5e21a5.png)

Note that the application ID is a really small number in the local dev environment, it'll be at least a 7-digit number in production.

**Comment by peggygannon** [comment]
hi, @Mottie Ok, looks good! Thank you for being so good with content updates! 

Just noticed we should add a period at the end of the last sentence:  Your application ID number is {number].
