### ISSUE TITLE
Add GA event to track eligibility loading time

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#15678]
We currently display a transparent loading overlay while we perform eligibility checks on whether a user can schedule at a chosen facility or not.  We want to calculate how long this loading usually takes to determine whether we should put a delay in before this overlay shows.

**Comment by jonwehausen** [comment]
Thanks @narin, will be in touch here soon

**Comment by jonwehausen** [comment]
@bsmartin-ep or @bmcgrady-ep could one of you connect with Narin on the event's we will need here? Thanks

**Comment by joanneesteban** [comment]
@bmcgrady-ep to start work on this.

**Comment by narin** [comment]
@bmcgrady-ep Hi Ben.  Before we spend too much time on this, we wanted wanted to confirm that it's possible to calculate an average of an extra dimension we send along with an event in either GA or Domo?  We want to calculate how many seconds on average this API call takes. Thanks.

**Comment by bmcgrady-ep** [comment]
@narin - Hi Narin! If an event that calculates the eligibility loading time is added, then if you add another dimension to the event you should be able to calculate an average. We would probably use BigQuery to get this data.

Are there currently any events set up in regards to eligibility loading time?

**Comment by narin** [comment]
@bmcgrady-ep Nope, we don't have an event set up for this yet.  Could use your guidance on a naming.

**Comment by bsmartin-ep** [comment]
@narin -

You are referring to this component, correct?

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/components/LoadingOverlay.jsx

**Comment by narin** [comment]
@bsmartin-ep Yes, sorry for the delayed response.  That's the component that will display while eligibility is loading.

**Comment by bsmartin-ep** [comment]
@narin -

We can approach this one of two ways....

1. Add events on the initial button click (or maybe even the API calls) and DIFF those with the loading of the next page.  This would have to be visualized in DOMO via BigQuery.

2. Add an event along the lines of:

```js
{
     'event': 'loading-indicator-displayed',
     'loading-indicator-display-time': 'n'
}
```

...when the LoadingIndicator is hidden.

**Comment by narin** [comment]
@bsmartin-ep I'm thinking the 2nd option should be easier to to implement.  In regards to the `loading-indicator-display-time`, does this have to be an integer, or can we use decimals? (e.g. 1.2)

**Comment by bsmartin-ep** [comment]
@narin -  I think we want to use a GA timing event for this, so optimially `loading-indicator-display-time` would be a **integer** representing the timing in **milliseconds**.

**Comment by bsmartin-ep** [comment]
@bmcgrady-ep / @jonwehausen -

Can you QA this on staging when you have a second?

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000385

```js
{
     'event': 'loading-indicator-displayed',
     'loading-indicator-display-time': 22
}
```

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep - 

I QA'd this (but saw it in a different workspace - https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000391) and the Data Layer looks good. 
![image](https://user-images.githubusercontent.com/66263904/100159387-e945aa00-2e6a-11eb-97d0-de05755f7770.png)

**Comment by bsmartin-ep** [comment]
Apologies @bmcgrady-ep - GTM workspace is updated:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000385

I picked an event category of `API Calls`.  Make sense to you?

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep - Finished up QA for this and it looks good.
Interaction|GTM Screenshot|Results
---|---|---
`loading-indicator-displayed` | ![image](https://user-images.githubusercontent.com/66263904/100278865-bced6480-2f22-11eb-9bfd-80a0ed256cc1.png)![image](https://user-images.githubusercontent.com/66263904/100278899-cd9dda80-2f22-11eb-806f-a9d76f07eab0.png) | **PASS** ✔️

**Comment by bsmartin-ep** [comment]
@narin -

I'm seeing `NaN` for some of these:

![image](https://user-images.githubusercontent.com/62304138/100292346-3484b900-2f4e-11eb-9509-6ab90b9605e6.png)

> ### [Google Analytics Report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20201104&_u.date01=20201125&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&_r.drilldown=analytics.eventLabel:loading-indicator-displayed)

**Comment by joanneesteban** [comment]
Removing @bmcgrady-ep & @jonwehausen until we're back in QA.

**Comment by narin** [comment]
@bsmartin-ep Thanks for QA'ing and catching that `NaN` issue.  I've merged a fix that should be on Staging now and deployed to production today with our daily deploy.

**Comment by bsmartin-ep** [comment]
Thanks @narin!  GTM is published.  You should start seeing data in GA on staging shortly and on production when you are deployed.
