### ISSUE TITLE
[Discovery] BDD/526: Provide Better Error Handling and Debugging Capability for Front-End

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#15680]
## Issue Description
Goal of this issue is to simplify our ability to correlate between validation issues and the SIP data that caused the issue. 

This is still a half baked idea so this story is mostly the work to do some discovery to see if a) how is this possible and b) this is valuable.

## Acceptance Criteria
- [ ] Is this worth doing?
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
possibly just add a sentry tag with in progres form id to http://sentry.vfs.va.gov/organizations/vsp/issues/417/?query=is%3Aunresolved+validation&statsPeriod=14d

**Comment by luke-gcio** [comment]
Closing as duplicate of #14807.
