### ISSUE TITLE
Access for Bridget Hapner

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#15688]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Bridget Hapner
- Please Provide your email.
   > bridget@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA Mobile App, Senior UX Designer, Ad Hoc LLC 

- Requesting SSH key authorization?
   > YES

````
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD86wngMEJm3ceLnBeJoIQmp50mhzZ5a8844TWV6GnHB/q/1Jf8146HRTZUpNWdE3RszE61SNo3sPg8f3CspVCjcfSwgCjn++VGftEelkUffMOvTrfb5lLf9Ptq/u3GGb+U9TbBbx4yS7g1U2wS7EoxNMYVlJyESqJqeZzibTjEdzl/e5EoBMtEPZT+fzB8uC59xpQkYEpCgM1A5IrIHEasXUZc+MnyOrIxufrKtCc20FnCjVM3PpVeBAb8NOHwqBghP0f7tJws/bO1CDDc04ZsJhj+FYKyGCr7keI9MjPJQGNDzV1cz1b4/3KuVnMcWE3ETRz9Y31HW2ctlMiq0TjFjLyv5br2f+lF0GZkRoUzlnWqJlngHRuyhlLHnGTw81TY0fYvdGv/b5rvYeMU2Xk4nbFxDVOzXfvF+pgFdPpY8+Pqfr+ltkR6mBK7D8M1snBypq5PSJz3Wt6xYDoRmzH8csVnIOYforLSfl/1Ut2GF1y3OMken4WqQBhDg+ypEa0= bridgethapner@Bridget-Hapners-MacBook-Pro.local
````

- Grant AWS Console access?
  > NO

**Comment by tskinn** [comment]
Hey @bridgethapner ! Do you need access to the socks proxy (grafana/jenkins/review instances) or AWS? If not we can close this issue. Thanks

**Comment by bridgethapner** [comment]
Hi @tskinn! I need access to Grafana - sorry if my ticket had an error in it, I wasn't sure what SSH key authorization meant.

**Comment by vacoleec3** [comment]
Hi Bridgethapner, I'm the API contract COR (Cecilia Lee). I would love to help you. Can you please let me know what you need from me. Thanks

**Comment by bridgethapner** [comment]
Hi @vacoleec3 - thank you very much for your message. I believe I just need written approval of the access request here.

@tskinn I am having trouble generating my public SSH key. Is VFS able to provide assistance? Thank you in advance for any help you can provide.

**Comment by tskinn** [comment]
@bridgethapner you will need to post your public ssh key in the issue so we can give you access to the socks proxy which will give you access to grafana. Here is a doc on how some of this works and how to create an ssh key pair https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md

**Comment by vacoleec3** [comment]
Hi Bridgethapner,

              Can you please provide the reason and what I should approve? Thanks.

**Comment by bridgethapner** [comment]
@vacoleec3 Yes! I am on the VA Mobile App team and am requesting Grafana access to view events for claims to inform our feature definition. The request is approval for Grafana access.

**Comment by vacoleec3** [comment]
Hi Bridget,

              Please follow the attached web link on GitHub to work on your AWS request. Attached web link is the same you are using.

Hi Andrew,

Can you please help Bridget on her AWS request?

I don’t know why she needs my approval.



Thanks,

Cecilia Lee

API Contract Cor

Technology Strategy & Alignment Services (TSAS)

Demand Management Division 005Q

PH:  (301) 257-2158

        (202) 461-4425/(202) 679-1143

**Comment by tskinn** [comment]
@bridgethapner you should be able to connect to the socks proxy now. Reach out in slack if you have any issues.
