### ISSUE TITLE
 [Design] MyVA Dashboard initial explorations: Research summary

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15685]
## Background

Epic #13924

This research plan is for the round of research we will be doing on the initial dashboard explorations we are working on in #15115.

Tasks

- [ ]  Complete research summary
- [ ] Share findings with team

**Comment by tressaellen** [comment]
Here is the [topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research/MyVA-topline-summary.md) - I'm now working on the full research summary.

**Comment by Samara-Strauss** [comment]
This is great! Nice job. Lots of good findings. I think we can act on some of the findings immediately (eg. clarifying what the benefit applications section is) and some things are hopefully stuff we can add or improve on over time with access to more data (eg. tracking a prescription that has been shipped). Looking forward to the full summary!

**Comment by tressaellen** [comment]
Here's the [research summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research/MyVA-research-findings.md)! Let me know if there's any changes that need to be made. :)

**Comment by Samara-Strauss** [comment]
THIS IS AWESOME! Thank you so much for putting together such a great report.

Going forward, I am relying on both of you to communicate what updates you think need to be incorporated into the designs we're working on now. I've read the report and see some things I think we could maybe do **if the data is available** (around appointments and messages), but it's up to you all to figure out how to apply these findings to the work going forward. Let me know if you have any questions about that.

Otherwise, I think we can close. Great work!

**Comment by tressaellen** [comment]
Thank you!! That sounds good - I'll plan on reaching out to a few people this week to see what data points are possible and will keep you all posted. And I'll go ahead and close this ticket.
