### ISSUE TITLE
Access for Dan Shank

### ISSUE THREAD

**Issue by Clark-W-Griswold** [department-of-veterans-affairs/va.gov-team#15681]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Dan Shank
- Please Provide your email.
   > danshank@gmail.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > FE Tools - Senior Frontend Engineer [Oddball]

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwKQsfHTa9UrTOnW57cB9zhBRa2h/uBxRfvVgT7XJrc5WqIbrJCEZ+aq46fs+tmj4AKb2Dj/xDjWEssIlgOTs9oZgReKG+I4MscbdqGh24iKvtoXMJFX74GlfdLKwmWCsaoYy4J/5bbPX0ykP8+TMKreWLKWr8WegYpd+ouTN41AjLW4XMalvngK4Z5gmF4p7RueRMpLTBvlLKKY6pRJ7KkSGJp6iKjOK1O0X6Sg49GNsbDhYyyArf7vwu9j6knRJ2rBZ7U17FqjkUTgYGudXvp3VZhOli2Vmcqa57kpAD8xIFQX8mDCAnX3FKbgLo6+Lp7BXqEEcnQxRSyNUnxHomGXUkY5dXHW9lhH2jcSHBxQoFkLdxWob0HQp7e5J44FXT5oFomjtLAGjDq9VRWD3AhULGblRUci/xv6fq8lg1qhUaSfDJl1+ntTBBaG/8gF4ZoCKEltFj282pmabCYwz/jcKOOXqYX+EXnQqV+vdCw7s1A16Y1RCXy+JVWhEX8TU= danshank@gmail.com
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by Clark-W-Griswold** [comment]
Tagging @department-of-veterans-affairs/vsp-operations for review.

**Comment by tskinn** [comment]
@Clark-W-Griswold you should be able to connect now. Reach out in slack if you have any issues.
