### ISSUE TITLE
Missing spaces on the 22-1995 form introduction page

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#15692]
On the introduction page for the 1995 form, there are two missing spaces. 

### Current
![Screen Shot 2020-11-02 at 3.34.54 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a1ce0ceb-4c2c-494b-8f9a-3710a723e300)

### Expected
![Screen Shot 2020-11-02 at 3.49.45 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/de434c48-c736-4b9f-beb4-7d3f05ddce24)

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14803

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-11-03 at 9.01.34 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/33a99549-19a5-48fa-814f-4d77456a49a6)

**Comment by delli-gatti-michael** [comment]
Fix is now in production. closing this issue

![Screen Shot 2020-11-03 at 3.09.07 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4b6f7836-c95f-4098-9859-0e0ba189605b)
