### ISSUE TITLE
Feedback - Staging Review - Public Websites - Resources and Support

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#15698]
- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

**Must:**
- None

**Should:**

- Add blue line under "Need help?" title and remove underline from help phone numbers. Like [this example](https://www.va.gov/health-care/apply/application/introduction).

**Consider:**

- None

**Definition of Done:**
- [x] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Allison will close the ticket once those things are all set. Thank you!

**Comment by brianalloyd** [comment]
Thank you @allison0034 for the feedback, acknowledge and will be discussing with our team as we plan for updates.
