### ISSUE TITLE
Create a list of all content in old repos

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1569]
As a member of the product support team, I want a list of all the documentation relevent to our team stored in the va.gov-vfs-teams and vets.gov-team repos so that I can make decisions about what to move to the va.gov-team repo. 

- [ ] Create a list of all the content. @mnorthuis might have an excel template

**Comment by mnorthuis** [comment]
Template to use, fill out as best you can, let me know if there are questions or you need help. 

[Repo Content Audit.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3579221/Repo.Content.Audit.xlsx)

cc @thatmattjohnson

**Comment by accbjt** [comment]
List of files
https://drive.google.com/drive/u/3/folders/0AJ6yVhfytxhFUk9PVA?ths=true

**Comment by accbjt** [comment]
Here is the list broken out by product support team members so we can figure out what we should keep.

https://docs.google.com/spreadsheets/d/1ZoIGnZXdz_BLirl4lnkeFNDSLN4nb90_OTt8V9oNpQA/edit#gid=132796699

**Comment by accbjt** [comment]
I discussed it with @andreahewitt-odd to clarify what docs we are looking for in the list. So what we want to keep in the list is document that we can use now and in the future to support other teams (onboarding, practice area, etc.). What we don't want is product specific files, archived files, and anything else that is not relevant to our team.
