### ISSUE TITLE
[CONSIDER] Map enhancements

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15700]
## Issue Description
This issue to track ideas for consideration in the map enhancement initiative.

[CONSIDER] Magnifying glass on button styling
![image](https://user-images.githubusercontent.com/55411834/97917658-07a80200-1d12-11eb-83b3-e814cde13f94.png)

[CONSIDER] Map info icon 
We may want to tone down the color of the map informational icon in the bottom corner so that it does not distract from the map pins

[CONSIDER] Map info bubble text
If we are able to adjust the text which appears within the map info bubble, we may want to remove the "Improve map" link

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jilladams** [comment]
Parent epic is closed, FL is now ticketed in va.gov-team repo. Closing orphaned tickets, as we are iterating FL separately.
