### ISSUE TITLE
DebtRes FSR Ch2 Household Income Content 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15703]
As a Veteran filling out FSR form, I need content to guide me ot fill out the following: 

2P1: Veteran employment
C2P2: Additional veteran income
C2P3: Marital status
C2P4: Spouse’s employment
C2P5: Spouse’s additional income

 including when I should or should not include my spouse's income and what constitutes my own income.

**Comment by 3obryandogs** [comment]
Suggest content has been added to the FSR outline provided by Becca and Riley.
