### ISSUE TITLE
No upcoming appointments (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15702]
## User story
As a user, I want a screen that tells me when I do not have any upcoming appointments.

## Acceptance Criteria
1. Create UI as shown in designs
     - The "You don't have any appointments" UI will display when a user does not have any Upcoming Appointments
2. VA.gov hyperlink opens the following link out-of-app in the user's browser: https://www.va.gov/health-care/schedule-view-va-appointments/
3. Display this UI when a user does not have any Upcoming appointments

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432581200

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark "Appointments" as Header 1
- Mark "You don't have any appointments" as Header 2

**Segmented Selector**
- accessibilityLabel="upcoming" or "past"
- accessibilityHint="view your__appointments" (e.g. upcoming, past)
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector

**Link**
- Icon
     - Title= “right arrow icon” 
     - accessibilityRole= “image”
 - Link
     - Title= "visit va.gov"
     - accessibilityRole= “link” 

## Dev Checklist 

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
@bridgethapner is AC #2 correct? (same VAOS link as the Appointments Detail page)

**Comment by jmarchi** [comment]
@bessgreen @bridgethapner Are we leaving the upcoming/past toggle in for this screen? If so is it disabled?

**Comment by bessgreen** [comment]
@jmarchi the toggle for Upcoming/Past appointments should still appear and be active: a user could have no upcoming appointments, but have a list of past appointments (and vice versa).

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Going to have to test without mock data.

**Comment by digitalken** [comment]
1/20/2021 - Need to test with real data, not mock.

**Comment by digitalken** [comment]
PASS - 1/29/2021 for UI on Android and iOS.
FAIL - 1/29/2021 for Android Accessibility - Two text blocks that are not actionable instruct user to double tap to activate and VA is being pronounced Vaw in the text body block. PASS for iOS.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19283

Closing because bug can track the defect and it is low priority.
