### ISSUE TITLE
Side navigation widget is missing on VAMC pages when viewed in the preview server

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#15710]
## What happened?
The side navigation widget is missing on VAMC pages when viewed in the preview server.

## Specs:
- any web browser

## Steps to Reproduce
- URL:  http://preview-staging.vfs.va.gov/preview?nodeId=84

## Desired behavior
The side navigation widget should be visible.

## Acceptance Criteria
- [ ] The side navigation widget is visible and contains the expected content

## Dev Notes
From @ncksllvn:

> In line 140 of `src/platform/site-wide/side-nav/helpers.js`
> It's doing some data manipulation that is driven of the URL path, which obviously looks different on preview

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ncksllvn** [comment]
cross-linking to dupe, https://github.com/department-of-veterans-affairs/va.gov-team/issues/21133

**Comment by ncksllvn** [comment]
Should be done as part of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5236
