### ISSUE TITLE
Upcoming Appointment Details: VAVC at Home

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#15714]
## User story
As a user, I want to see details for my upcoming VA Video Connect(VAVC) at home appointment and: add the appointment to my calendar and join the session directly from the app.

## Acceptance Criteria
Note: Canceled UI covered with story #15739

1. Selecting a VA Video Connect at Home appointment from the Upcoming Appointments list routes to a new page with more detail about that appointment
     - Display Back button
2. Styling and UI matches the design
3. The date should be in [Day], [Month XX, XXXX] at [00:00][am/ pm] [Timezone] format
     - The timezone should match the timezone the clinic is in (6 timezones)
4. "Add to calendar" hyperlink with a calendar icon displayed to its left 
     - Tapping on this launches the phone's default calendar app 
     - Calendar app opens with a new event that corresponds to the date/time of the appointment, with the appointment title (VA Video Connect at Home)
5. Placeholder for "Join session" button (covered in a [separate story]
6. "Prepare for video visit" hyperlink (Routing/UI covered in a [separate story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15761))
7. "Visit VA.gov" hyperlink with a right arrow icon displayed to its left
     - Opens the following link out-of-app in the user's browser: https://www.va.gov/health-care/schedule-view-va-appointments/

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432775466

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Back button in top left
     - accessibilityLabel= “Back”
     - accessibilityHint= “Go back to the upcoming appointments list”
     - accessibilityRole= “button”
- Mark "Appointment" as Header 1
- Mark date/time (e.g. Friday, September 25 2020 1:30 p.m. ET) as Header 2
- Mark "How to join your virtual session" as Header 3
- Mark "Need to cancel?" as Header 3

**Links**
- Icons
     - Title= “___Icon” (e.g. Calendar, Right Arrow)
     - accessibilityRole= “image”
 - Link
     - Title= Name of link (e.g. Add to calendar)
     - accessibilityHint= “Adds this appointment to your device's calendar"
          - No hint for "prepare for video visit" link and "visit va.gov"
     - accessibilityRole= “link” 

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.
