### ISSUE TITLE
Upcoming Appointment Details: VAVC at an ATLAS Location

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#15713]
## User story
As a user, I want to see details for my upcoming VA Video Connect(VAVC) at an ATLAS location appointment and: add the appointment to my calendar and get directions directly from the app.

## Acceptance Criteria
Note: Canceled UI covered with story #15739

1. Selecting a VA Video Connect at an ATLAS location appointment from the Upcoming Appointments list routes to a new page with more detail about that appointment
     - Display Back button
2. Styling and UI matches the design
3. The date should be in [Day], [Month XX, XXXX] at [00:00][am/ pm] [Timezone] format
     - The timezone should match the timezone the clinic is in (6 timezones)
4. "Add to calendar" hyperlink with a calendar icon displayed to its left
     - Tapping on this launches the phone's default calendar app
     - Calendar app opens with a new event that corresponds to the date/time of the appointment, with the appointment title (VA Video Connect at an ATLAS Location) pre-filled as the event name
5. ATLAS location is displayed in standard address format:
     - The 1st line should be the street address
     - The 2nd line should be the city, state, and zip code
6. "Get directions" hyperlink with a street icon displayed to its left. 
     - Tapping on this should launch the user's default navigation app
     - Navigation app opens to the coordinates of the ATLAS location
7. The appointment code is generated and displayed via API
8. "Visit VA.gov" hyperlink with a right arrow icon displayed to its left
     - Opens the following link out-of-app in the user's browser: https://www.va.gov/health-care/schedule-view-va-appointments/ 

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204195

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Back button in top left
     - accessibilityLabel= “Back”
     - accessibilityHint= “Go back to the upcoming appointments list”
     - accessibilityRole= “button”
- Mark "Appointment" as Header 1
- Mark date/time (e.g. Monday, October 20, 2020 3:45 p.m. ET) as Header 2
- Mark "How to join your video appointment" as Header 3
- Mark "Appointment code: XXXXXX" as Header 3
- Mark "Need to cancel?" as Header 3

**Links**
- Icons
     - Title= “___Icon” (e.g. Calendar, Street, Right Arrow )
     - accessibilityRole= “image”
 - Link
     - Title= Name of link (e.g. Add to calendar )
     - accessibilityHint= “Adds this appointment to your device's calendar" **OR** "Opens your device's navigation app" 
          - No hint for "visit va.gov" link
     - accessibilityRole= “link” 

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Passes on Android for UI and functionality, fails on accessibility (added to bug 16675). Holding in QA until able to test UI and functionality on iOS.
