### ISSUE TITLE
[Dangerbot] Link to documentation from dangerbot

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#15715]
this should be linked when the dangerbot blocks on migrations https://depo-platform-documentation.scrollhelp.site/developer-docs/Vets-API-Database-Migrations.689832034.html

this should be linked with code length warnings/errors https://depo-platform-documentation.scrollhelp.site/developer-docs/Submitting-pull-requests-for-approval.655032351.html

review other links
i.e. strong migration link conflicts with our policy

via [this Slack conversation](https://dsva.slack.com/archives/CL4FC8UN5/p1604359375007100).

**Comment by erluti** [comment]
Make sure github is the right place to link to.

**Comment by erluti** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5730

**Comment by alexpappasoddball** [comment]
@ericboehs moving this to In progress as I believe this is taken care of in your refactor.  Feel free to let me know if I'm incorrect about that.

**Comment by alexpappasoddball** [comment]
@eric did this ever get in to the refactor or do you have plans to add it?  I believe it is complete but just verifying

**Comment by ericboehs** [comment]
It didn't go in with the refactor.
