### ISSUE TITLE
1995: Update content labels to match DEPO standards

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15720]
As a dev, I need to update the 1995 form labels so that they match the DEPO standard labels.

## Assumptions:
1. This work is completed behind a prod flag.

## Acceptance Criteria:
1. The chapter titles are sentence case:
    a. Applicant information
    b. Education benefit
    c. Military history
    d. School selection
    e. Personal information
    f. Note: "Review Application" is excluded from this because it is a shared component.

2. The following chapter 4 question text is updated:
    a. ~From `Street` to `Street address` (page 1)~
    b. From `Education or career goal (for example, “Get a bachelor’s degree in criminal justice” or “Get an HVAC technician certificate” or “Become a police officer.”)` to `Education or career goal (For example, “I want to get a bachelor’s degree in criminal justice” or “I want to get an HVAC technician certificate” or “I want to become a police officer.”)`
    c. From `Are you getting benefits from the U.S. Government as a civilian employee during the same time as you’re seeking benefits from VA?` to `Are you getting benefits from the U.S. government as a civilian employee during the same time as you’re requesting benefits from VA?`
    d. ~From `Street` to `Street address` (page 2)~
    e. From `When did you stop taking classes or participating in the training program? (Future dates are ok)` to `When did you stop taking classes or participating in the training program? (Future dates are ok.)`

~3. The following chapter 5 question text is updated:~
~    a. From `Street` to `Street address`~

### Notes:
As a result of the impact to non EDU forms, AC 2a, 2d and 3 have been removed from this story.  See first comment below.

## Supporting Artifacts:
1. https://design.va.gov/patterns/form-labels
2. [Forms Updates Tracker.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5482344/Forms.Updates.Tracker.xlsx)

**Comment by dmccurdybah** [comment]
The inputs for AC 2a, 2d, and 3a are built using platform code that generates schemas for address forms. We're overriding the label of the "Street" field instead of fixing it in platform.

The input updated for 2e also fixes the issue on the 5495 form.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14890

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-11-09 at 8.36.32 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d7a4afc4-3a52-4407-b26f-43c7d37d25f2)
##
![Screen Shot 2020-11-09 at 8.36.44 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bf50ad15-afc9-46f5-926e-536464fd33e8)
##
![Screen Shot 2020-11-09 at 8.37.07 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1fe49177-2435-4859-b070-7bd87abd182b)
##
![Screen Shot 2020-11-09 at 8.37.22 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ce764087-b06b-4714-932b-3ecd91dfa35f)
##
![Screen Shot 2020-11-09 at 8.37.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5a52484f-5819-420a-a251-8f264994e4e8)
##
![Screen Shot 2020-11-09 at 8.39.17 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6c23fa3c-1af8-49ff-84b5-8a0b6463c193)
##
![Screen Shot 2020-11-09 at 8.40.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/296222bd-815b-41ad-a0ac-28e9ae741b30)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/748&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me!

**Comment by watersemma** [comment]
UX Review 2/2: This checks out for me as well!

**Comment by sonntag-adam** [comment]
Closing story
