### ISSUE TITLE
COVID-19 Chatbot

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#15725]
## User Story

As a user, I want to ask the COVID-19 chatbot questions in the app.

## Tasks

- [ ] UX Discovery: What do users want to ask, or need to know?

- [ ] Technical Discovery: How could we implement the existing chatbot in the app?

**Comment by eric521237** [comment]
lol

**Comment by ayushchak** [comment]
Closing this ticket given other tickets about COVID features.
