### ISSUE TITLE
Education Form Standardization

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#15721]
The BAH team is working on normalizing a number of education benefits forms over the next few sprints.  The application for 22-1009 / VET TEC, is our top priority. If you could review and respond to questions about this form this week, that would be helpful.  

We'd like your input on Form titles for the follow: 
1. **22-0994, Application for VET TEC**  
The introduction form title is "Apply for Veteran Employment Through Technology Education Courses (VET TEC)" within the form the title is "Apply for VET TEC".
2. 22-0993
3. 22-1990
4. 22-5495

Also, looking for updates you may have to 
- Desktop breadcrumbs
- Mobile breadcrumbs
- URLs

For... 
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/f76188bc-821b-411e-b10b-7da52934db6e)

cc @dneel-bah

**Comment by mnorthuis** [comment]
@amyknox Can you let us know what your timing is on this, so we can slot it into our sprint work accordingly?  Thank you!

**Comment by amyknox** [comment]
@dneel-bah - could you weigh in on timing for this request for Mikki & Peggy? Thank you!

**Comment by dneel-bah** [comment]
@mnorthuis We'll be working these changes into our backlog through the end of the year.  If we could get them spread out over time, I think that would be ideal.  Otherwise if you're looking to knock them all out at once, I'd say we would need the feedback by the beginning to middle of December.

**Comment by peggygannon** [comment]
Thanks @dneel-bah on the timing update.

**Comment by amyknox** [comment]
@mnorthuis &/or @peggygannon - do you have an ETA on this story?

**Comment by peggygannon** [comment]
Hi, @amyknox Mikki and I are discussing this today (11/17).

**Comment by amyknox** [comment]
@peggygannon and @mnorthuis - thanks for letting me know this was on your radar today.  Were you able to make any progress?

**Comment by mnorthuis** [comment]
Hi @amyknox, this is in our plan for this sprint, which ends next Tuesday.  I likely won't be able to focus on this until later this week and will coordinate with Peggy.  We would for sure be done by next Tuesday, Nov 24.  If there's something you need sooner than that, please let us know.

**Comment by amyknox** [comment]
@peggygannon - It looks like there have been updates to language around claims / benefits applications since many of the education forms were last updated.  

Could you confirm these updates are compliant for the following forms: 22-1995, 22-0994, 22-1990, 22-1990E, 22-1990N, 22-5490, 22-5495

* Page subhead “Claim received” should this be “We’ve received your application.”

* Confirmation page, blue box heading “Education benefit claim (Form 22-####)”.  Should this be: “Education benefit application (Form 22-####)”

**Comment by peggygannon** [comment]
hi, @amyknox  I'm not aware of any recent content updates around claims in the benefit applications. I do have in my backlog a task to audit content across all form to ensure consistency, as the apps work is spread across multiple product teams and it's not always clear if my content feedback is implemented. 

Do you have a specific example or application you're referring to with above example?

**Comment by amyknox** [comment]
@peggygannon - the forms we're looking at updating are all education benefit forms: 22-1995, 22-0994, 22-1990, 22-1990E, 22-1990N, 22-5490, 22-5495

We're looking at changing the chapter titles to sentence case, updating any of the form labels to match the form label master list, and updating the confirmation content as relevant. The confirmation page updates are what I'm asking about in the Nov. 18 comment.  

Happy to discuss via slack or phone if more details are required to make sense of this!

**Comment by peggygannon** [comment]
Hi, @amyknox Thanks for the additional info. Here's some updates/feedback from me: 

1. Form chapter titles, subhead, buttons, etc. *should* be sentence-case.  I opened this [ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/261) back in July for the design council to review and slot into their work queue. I have asked them for an update on this. 

2. I'll be looking at all the form confirmation pages and labels as part of my forms content audit. This is work that I'm fitting in between content support requests and reviews :) I will prioritize reviewing the confirmation pages in my audit. 

3. Form labels: Not every edu "label or question" might be listed in the forms label masterlist. When I created this document, I focused on labels that appeared across all forms or all EDU forms. This is also work I'm fitting in as I can, between content support and reviews. 

Let me know if you have any additional questions. I'm hoping design council can prioritize the sentence-casing work soon.

**Comment by mnorthuis** [comment]
@amyknox Here are the recommended changes for all the education forms to bring them up to standards we are using on the new modernized site, as well as ensure they are consistent across the hub.    Please take a look and let me know if you have any questions. 

A couple of things to note:
1) There are 2 H1s for each form - this is applicable once the wizard function is moved from the static page to the /introduction page of the form.   Once the wizard is moved, there are 2 display states of that /introduction page, and for improved accessibility we need the H1 to change when the display state changes to indicate that content on the page has changed.  The "H1 Intro pg" will remain the H1 throughout the rest of the form chapters/steps. 

2.  For URL changes to the forms, the reason those URLs were not updated with WBC is that we were told they were coded to a specific URL - if that link can be eliminated, that would ensure that future IA changes can be handled more easily.  In addition, redirects will be needed from the old URL to the new URL. 
 
[edu-forms-modernization.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5592869/edu-forms-modernization.xlsx)

**Comment by amyknox** [comment]
@peggygannon 

> Could you confirm these updates are compliant for the following forms: 22-1995, 22-0994, 22-1990, 22-1990E, 22-1990N, 22-5490, 22-5495
> 
> * Page subhead “Claim received” should this be “We’ve received your application.”
> * Confirmation page, blue box heading “Education benefit claim (Form 22-####)”.  Should this be: “Education benefit application (Form 22-####)”

**Comment by amyknox** [comment]
@mnorthuis - thank you for the update.

We will tackle the H1s updates for those education forms.  

The URL and breadcrumb appear to be dependent on the wizard migration.  Are those updates that the Public Websites team plans on updating along with the wizard roll out?

**Comment by mnorthuis** [comment]
@amyknox The breadcrumb and URL changes are valid whether or not the wizard is moved, but if its easier to tackle those changes when someone is in the code doing the wizard move, then yes, that is an option, but they could be done before that.   The H1 is partly dependent on the wizard move, because once the wizard is moved to the application, the /introduction page has 2 display states and each display state has a different H1. 

Might be helpful to talk through this, so just let me know.

**Comment by amyknox** [comment]
@mnorthuis - we do have some questions for you. Could we connect early next week - say Tues. 12/1?  What's your availability?

**Comment by mnorthuis** [comment]
@amyknox Yes, definitely.  I'm open between 12-2ET Tuesday.

**Comment by peggygannon** [comment]
Hi, @amyknox 

Answering your questions ^^ 

EDU form confirmation pages should say: 
**“We’ve received your application** (rather than Claim received) at top of screen. 

The Confirmation page, blue box heading “Education benefit claim (Form 22-####)”. Should this be: “Education benefit application (Form 22-####)”

**Comment by amyknox** [comment]
Thanks @peggygannon - one quick follow-up: for the confirmation screen / blue box for STEM, we'd customized the heading to "Rogers STEM Scholarship (Form 22-10203)" as in the image below.  OK to leave that or should it be genericized to “Education benefit application (Form 22-####)”?

![image](https://user-images.githubusercontent.com/41081945/100749104-31f0ec00-33b2-11eb-8a56-18a30e1afa96.png)

**Comment by peggygannon** [comment]
Hi, @amyknox Agree, we should use the customized head for this one. So the above screenshot looks good. thanks for checking on that one!
