### ISSUE TITLE
Learning center search results should not show pagination in breadcrumb

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15730]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

On this search results experience, the breadcrumb is including the pagination. Pagination should not be included in the breadcrumb pattern of search results. 

(This might be  a FE bug, because search results are dynamic pages that are not inside the CMS.) 

http://learningcenter.web.demo.ci.cms.va.gov/taxonomy/term/268/2/

On page 2: 
![image](https://user-images.githubusercontent.com/43381063/98017225-f53ece80-1dcc-11eb-8bb1-68b3f185494d.png)

On page 3: 
![image](https://user-images.githubusercontent.com/43381063/98018286-5fa43e80-1dce-11eb-9008-1b5fe3e02de3.png)

## Specs:
- Device: HP pc
- Browser: Chrome

## Steps to Reproduce
- URL: http://learningcenter.web.demo.ci.cms.va.gov/taxonomy/term/268/
1/ Click on All Veterans tag
2/ Page to next page on results
3/ Note breadcrumb changes to include page numbers

## Desired behavior
_Don't include pagination in breadcrumbs_

## Acceptance Criteria
- [ ] _Search results breadcrumb does not include pagination_

**Comment by jenniferlee-dsva** [comment]
Not a launch blocker, but we should fix this sprint.

**Comment by ncksllvn** [comment]
PR is open!

**Comment by ncksllvn** [comment]
PR is merged; will go live today

**Comment by brianalloyd** [comment]
Closing out, per validation.
