### ISSUE TITLE
Allow SiP "inProgress" messaging to be disabled

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#15735]
### User story(ies)

As a VFS developer, I want a way to disable the "in progress" message on the save-in-progress intro component, so that we don't have redundant text when we don't have any alternative in progress messaging to display.

![image](https://user-images.githubusercontent.com/2008881/98020510-f1ed1800-1db7-11eb-8d43-319a2d1d8dea.png)

### Additional details/notes/links

- https://github.com/department-of-veterans-affairs/vets-website/pull/14697

### Acceptance criteria

- [ ] "inProgress" message can be disabled by setting it to be an empty string

### Point(s) of contact

- @bkjohnson 

### What type of issue is this? 
- [x] Bug
- [ ] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

**Comment by cvalarida** [comment]
See also https://github.com/department-of-veterans-affairs/va.gov-team/issues/13148
