### ISSUE TITLE
Canceled Appointment (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15739]
## User story
As a user, I want to see my canceled upcoming and past appointments

## Acceptance Criteria

1. Appointments List (both upcoming and past)
     - Display Canceled below the appointment information (date/time and location)
2. Modify the UI across all appointment detail pages:
     - Display Canceled below the date/time
     - Hide calendar hyperlink
     - If an upcoming appointment, hide the "need to cancel" card and display the "schedule another appointment" card
3. In addition, modify UI for Community Care Facility Detail:
     - Hide special instructions
4. In addition, modify UI for VAVC at Home:
     - Hide "Join Session" button and related how to join text 
     - Hide "Prepare for video visit" link
5.  In addition, modify UI for VAVC at an ATLAS Location:
     - Hide how to join text (maintain ATLAS location address)
     - Hide appointment code and related text
6.  In addition, modify UI for VAVC at a VA Location **AND** UI for VAVC Using a VA Device:
     - Hide how to join text 

## Designs 
Canceled UI for VA Appointment Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432587387
Canceled UI for Community Care Facility Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433202203
Canceled UI for VAVC at Home Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432868109
Canceled UI for VAVC at an ATLAS Location Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204197
Canceled UI for VAVC at a VA Location Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204500
Canceled UI for VAVC Using a VA Device Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433303805

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines

**Canceled Status**
- Treat as static text 

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRails.

**Comment by digitalken** [comment]
Testing...
