### ISSUE TITLE
Warning notification when app experiencing degradation of service/experience (without downtime)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#15736]
Display a warning to Veterans who are coming into VAOS to use the app but may encounter issues due to degradation in services used by VAOS. 

### Acceptance criteria:
- enable window with following copy below in PagerDuty when we notice degradation in experience for users of VAOS app 

### Message should say:
**You may have trouble using the VA appointments tool right now.**
Some Veterans have reported problems with viewing, scheduling, or canceling their appointments. We’re working to fix the issue now.
If you have trouble using this tool, call your VA health facility or community care provider.
[Find your health facility or provider’s phone number](https://www.va.gov/find-locations/)

**Comment by lalexanderson-dsva** [comment]
We don't usually use the word "customers' in our error messaging. I'd like to get @DanielleThierryUSDSVA eyes on this.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lalexanderson-dsva @lenaecb. Let me know if this works - thanks!

**You may have trouble using the VA appointments tool right now.**

Some Veterans have reported problems with viewing, scheduling, or canceling their appointments. We’re working to fix the issue now. 

If you have trouble using this tool, call your VA health facility or community care provider.
[Find your health facility or provider’s phone number](/find-locations/)

**Comment by lalexanderson-dsva** [comment]
Thanks @DanielleThierryUSDSVA - this works.
