### ISSUE TITLE
Remove `dashboard_show_covid19_alert` feature flag

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#15737]
We no longer need the `dashboard_show_covid19_alert` feature flag. It has been true for months and there will be no need to flip it off. Whenever the COVID alert is removed from the dashboard it can be done by deleting the code.

**Comment by erikphansen** [comment]
@Samara-Strauss I'm pretty sure we will not need the ability to immediately remove the COVID-19 health chat alert from the My VA Dashboard. Let me know if I'm incorrect about that.

**Comment by Samara-Strauss** [comment]
I can't think of a reason why we would need that. I think it's OK to remove the feature flag.
