### ISSUE TITLE
[BUG] GA<>BigQuery Export 11/2

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#15747]
## What happened?
Our daily Google Analytics<>BigQuery export is outside of it's normal morning-AM hours window and has not completed the daily export. 

## Desired behavior
The Google Analytics to BigQuery export executing it's daily export per usual 

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jonwehausen** [comment]
Issue has been escalated to our Google analytics enterprise support

**Comment by jonwehausen** [comment]
Hi Kenny/Jeffrey, 

Hope you both are doing well since we last connected. 

We are reaching out with high urgency as we have noticed today our GA to BigQuery export has still not yet completed for the prior day of 11/2/2020. 

We are outside of our usual AM-hours variance and thus far logs look consistent with what we've seen historically for successful exports. We have included today's log in both JSON and CSV format for your reference. 

If possible, we would like to coordinate a call / working session to resolve as quickly as possible and/or if there is assistance you can provide here we would greatly appreciate it. I can be reached by phone at 301-758-6388.

image.png

Thanks again,

**Comment by jonwehausen** [comment]
### Raw Transcript From Google Chat Support
S
Hi Jon, how are you doing?
Siri · 3:47 PM
Hi Siri, I'm doing well how are you doing?
3:48 PM
S
Glad to hear. I'm doing fine as well. Thanks for checking.!
From your query, I see that you referring to a delay in BQ exports. Am I correct?
Siri · 3:49 PM
Yes that is correct, we are in eastern standard time and still have not yet received our daily export of Google Analytics data to BigQuery for November 2
3:50 PM
S
Could you please confirm if this is the View ID: 184624291?
Siri · 3:51 PM
Yes that is correct
3:51 PM
S
Thanks for confirming. Please allow me 5 minutes while I check the Account details here.
Siri · 3:51 PM
Okay thank you
3:51 PM
S
Thanks for your time.
I've pulled up the Account and I'm checking the View internally. Please allow me 10 minutes of your time.
Siri · 3:58 PM
Okay no problem thank you
3:58 PM
S
Thanks for your time, Jon. I'm checking this internally and could see that the export is being missed on 2nd Nov. They will be back to normal. However, to confirm this further could you please help me with the below details:
1. Bigquery project ID
2. ‘User and viewer’ access for the email ID - analytics360-bigquery-support@google.com.
3. BQ UI uncropped screenshot showing Nov 2nd daily export missing.
Siri · 4:03 PM
Yeah
BQ Project ID: vsp-analytics-and-insights
You should also have an attachment of the 11-02 dataset missing
4:06 PM
S
I can send you a follow up email and you can revert on the same with the uncropped screenshots from the BQ UI>
Also the access for the email ID: analytics360-bigquery-support@google.com
Siri · 4:07 PM
For your number 2, are you saying I need to add that account in IAM?
4:07 PM
S
Yes, here are the steps to add a user to BigQuery Project:

1. Log on to this link: https://console.cloud.google.com/iam-admin/iam/project
2. Click IAM → Add button
3. Enter the user emails (eg: analytics360-bigquery-support@google.com)
4. Select a Role - Project → BigQuery User and BigQuery Viewer
Siri · 4:08 PM
I am seeing BigQuery "Data" Viewer, BigQuery "Resource" Viewer, and BigQuery "Metadata" Viewer
I am assuming "Data" viewer but can you confirm
4:12 PM
S
Yes.
Siri · 4:12 PM
Okay, roles have been granted
4:12 PM
S
Thanks for this. Please allow me 5 minutes while I check this.
Siri · 4:13 PM
Okay thanks, very much appreciated
4:13 PM
S
Also, I could not see any BQ Project linked to the View: 184624291. Could you please confirm on this.
Siri · 4:14 PM
My mistake there!
the correct view id is: 176188361
4:15 PM
S
Thanks for confirming. Let me check this!
Siri · 4:15 PM
Thanks in advance
4:17 PM
S
Thanks for all the details.
Appreciate your patience in this regard.
Siri · 4:21 PM
Sure thing
4:22 PM
S
Could you please share the uncropped screenshot from the BQ UI showing the Nov 2nd export missing.
I'd need this to check with my next level support team. You can upload them in a drive and share the public link with me.
Siri · 4:24 PM
Yes one second
4:27 PM
S
Sure.
Siri · 4:27 PM
Where is the upload feature for this chat?
4:28 PM
S
Sorry but there isn't an attachment option. You can upload in a google drive and share the public link with me.
Siri · 4:29 PM
Okay
https://drive.google.com/file/d/14k0ou7s2B8Deyeyii1_929cCLdNaUs_8/view?usp=sharing4:31 PM
S
Thanks a lot for sharing this, Jon.
Siri · 4:32 PM
No problem
Do you have everything needed at this point?
4:33 PM
S
I'm checking this with my team internally. Would you mind if I take 5 more minutes of yours.
Siri · 4:34 PM
Sure
4:34 PM
S
Thanks for your time.
Siri · 4:40 PM
Sure
4:41 PM
S
Apologies to keep you wait.
Please allow me 10 more minutes of your time as I'm in discussion with my wider team on what is causing a delay for this View.
I sincerely appreciate your patience.
Siri · 4:43 PM
Okay, thank you for your work here
4:43 PM
S
Always happy to assist!
Thanks for your time.
Appreciate your patience.
Siri · 4:52 PM
Sure
4:52 PM
S
Ideally a small time frame of delay is expected in BQ exports. However, in this case, there is a delay and 2nd Nov data is not exported. I'm in discussion with my team and as it is talking longer than expected, I'd like to share my insights over an email after investigation.
Siri · 4:54 PM
Yes, we understand there is some variance in delay, but not receive the export at all is a bit unacceptable here without further causation
4:55 PM
S
Yes, I definitely understand.
I'll discuss this with my team and will get back to you with my insights over the next 24 hours.
Would this be the best email to contact you: jon.wehausen@empiricalpath.com?
Siri · 4:56 PM
Yes please, thanks
4:57 PM
S
Sure. Thanks for your time and patience throughout the chat.
Siri · 4:57 PM
Thanks, can I receive a transcript of this chat?
4:58 PM
S
Sure, I'll share the transcript to the email ID within an hour from now.
Siri · 4:58 PM
Okay thanks

**Comment by jonwehausen** [comment]
## Update 11/4

While we are still waiting to hear more around root cause from Google Support, we now have both 11/2 and 11/3 datasets successfully exported to BigQuery. 

![image](https://user-images.githubusercontent.com/48527022/98126710-e535f600-1e83-11eb-92ee-f997d0cfe34c.png)

### Due to our BQ DOMO SQL datasets configured to append the prior days data with `_TABLE_SUFFIX = FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))`, datasets will need to be manually backfilled to include Nov 2. 

For context, under our current configuration, this problem only arises when our GA > BigQuery export export fails to complete AT ALL for a given day -- in the event the export doesn't complete until afternoon hours, we still have the ability to simply click Run on our datasets without changing any SQL lines. 

As a future item, we may want to explore SQL programmatic automation around this scenario so when and if this happens again, we don't need to manually adjust queries to backfill and can instead rely on the query to pull in all of the most recent data the dataset doesn't currently have. Again this problem is only presented when the export doesn't complete AT ALL for a given day. 

cc: @bsmartin-ep @bmcgrady-ep @joanneesteban @amycesal

**Comment by joanneesteban** [comment]
## Postmortem To Do's

- [ ] Backfill datasets in Domo
- [ ] Follow up with Google on why this occurred
- [ ] Fill out the [Post-mortem template](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/_template.md) w/this bug. Focus on **Impact.** We can share this with Nancy if we need additional follow up.

**Comment by bmcgrady-ep** [comment]
@joanneesteban @jonwehausen - All of the BigQuery datasets have been backfilled and updated with the error scripting code. Here is the [report](https://docs.google.com/spreadsheets/d/1RCJmoFjQxZ4XdNf7zWBGp2lOriKXu2TP6UIyfhLpejc/edit?usp=sharing) showing the progress.

**Comment by jonwehausen** [comment]
@joanneesteban PR link for postmortem can be found here, ready for review: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/184

**Comment by jonwehausen** [comment]
Final postmortem has been published in team sensitive repo
