### ISSUE TITLE
Build 'how would you like to be seen' page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1574]
## Story
As a veteran, I want to choose between phone, office, and telehealth appointment types so that I can get care in a way that is fastest and most convenient for me.

## AC
- [ ] Page shows after 'reason for appointment' page
- [ ] Page asks veterans to select between 3 static options per screenshot below

![Screen Shot 2019-09-04 at 3.51.56 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/9877fa63-dcb5-4a61-af28-91131840acd5)

**Comment by markgreenburg** [comment]
We need more discovery around this in order to understand what the options actually do and whether we can get an accurate list for each system.

**Comment by narin** [comment]
Validated on staging
