### ISSUE TITLE
Collaboration Cycle Feedback Discovery

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#15752]
## Issue Description
VSP Collaboration Cycle feedback to VFS teams is not consistent across all practice areas and throughout the various Collaboration Cycle touchpoints. Before any solution can be applied, we need to discover the similarities and differences in the ways that feedback is being communicated across all practice areas and all collaboration cycle points.

## Acceptance Criteria
- [x] We have reviewed Feedback issue tickets from the following practice areas:
   - [x] Content
   - [x] IA
   - [x] Design
   - [x] QA
   - [x] Accessibility
- [x] We have reviewed Feedback issue tickets from the following Collaboration Cycle touchpoints:
   - [x] Project Kickoff (if applicable)
   - [x] Design Intent
   - [x] Usability Testing Prep
   - [x] Staging Review
- [x] We have identified patterns, trends, similarities and differences across the practice areas and collaboration cycle touchpoints

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by shiragoodman** [comment]
MURAL board: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1604350644537/2a40e0aca3dd25f4ea375b3180201d4bf1f382b5

**Comment by shiragoodman** [comment]
@allison0034 - added you to this ticket. Let me know if you have any questions.

**Comment by allison0034** [comment]
More documentation from previous research can be [found here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/research/collab-cycle-v1/README.md).

**Comment by allison0034** [comment]
The evaluation and suggested solution is on the[ original mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1604350644537/2a40e0aca3dd25f4ea375b3180201d4bf1f382b5). The next steps should be for each practice area to meet and discuss if the proposed solution will work for everyone.

**Comment by shiragoodman** [comment]
@allison0034 can you create a ticket (similar to this one) with proposed next steps? thank you!

**Comment by shiragoodman** [comment]
@allison0034 - can you create a ticket similar to this with proposed next steps? I can help with the Acceptance Criteria
