### ISSUE TITLE
Past Appointment Details (UI)

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#15754]
## User story
As a user, I want to see details of my past appointments

## Acceptance Criteria 

1.  Selecting a past appointment takes the user to the details page for that appointment
     - Display back button
2. Modify the UI across all appointment types:
     - Hide calendar hyperlink
     - Hide the "need to cancel" card
     - Display the "schedule another appointment card"
3. In addition, modify UI for Community Care Facility:
     - Hide special instructions
4. In addition, modify UI for VAVC at Home:
     - Hide "Join Session" button and related how to join text 
     - Hide "Prepare for video visit" link
5.  In addition, modify UI for VAVC at an ATLAS Location:
     - Hide how to join text (maintain ATLAS location address)
     - Hide appointment code and related text
6.  In addition, modify UI for VAVC at a VA Location **AND** UI for VAVC Using a VA Device:
     - Hide how to join text 

## Designs 
Past appointments UI for VA Appointment Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432490747
Past appointments UI for Community Care Facility Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433202202
Past appointments UI for VAVC at Home Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432868108
Past appointments UI for VAVC at an ATLAS Location Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204196
Past appointments UI for VAVC at a VA Location Pagel: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433204499
Past appointments UI for VAVC Using a VA Device Page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/433303804

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

When an appointment has passed, modify the accessibility implementation guidelines for all appointment details pages:

- Back button in top left
     - accessibilityLabel= “Back”
     - accessibilityHint= “Go back to the past appointments list”
     - accessibilityRole= “button”
- Mark "Past Appointment" as Header 1

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**12/07**

UI and functionality pass on iOS and Android. Accessibility fails with a [multi-issue bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17003) entered. Moving to Design QA
