### ISSUE TITLE
Access for Tim Wright

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#15750]
# Instructions

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Tim Wright
- Please Provide your email.
   > timwright12@gmail.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Front End Tools, Staff Software Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9Wg6GRqTyx1E21IayXOawSybkbF8opppDHlBvy9bf+hbhtfSzLhnyh3qJ4KWKNKFaEbsM96DfcnjI5XPEjGylaxDEnQaoY/Y8/xb5SP+gi6uZ0pmNtkojSCsXTvFhLdAokqTe879pctq9nOtSc2AGDIWmb0CsflF+r1IRZwbAuVdEG81U3BH18uKss+HiUyyqCHIXDKJe2UNiT01I91sTFsefNuVKTeWOQpLGRLQmpUu9iH6S061Entbao5BnPa75bhsZp4Fl9fp7AaAksylNvDr9dIR3jdfojZKPHNqn8rwVibMgu5xMzM0+li+Ksqkh5LP2cJ3LsRjSY+BfX2UCkxUXyZshJ50GBAx31IgrhKtLlRmvjd/ztir7QzNUoVzvi1OfIxAjSP2I09G0YTguj8etIEu62vPqA5zwEjtiEYHZMS6k9CaQDKSe3/xwmrYcXfLzQaDlKgVbVnv+lAZ8IUdjK/KpB8kZYiuKIpOqbasLqsLihy1Vzqr5QkCCPn0= timwright12@gmail.com
```

- Grant AWS Console access?
  > YES / NO
  - What AWS services do you need access to and why? 
Trying to get SOCKS working via https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy

**Comment by tskinn** [comment]
@timwright12 you should be able to connect to socks proxy now. Reach out in slack if you have any issues.
