### ISSUE TITLE
Build 'appointment time preferences' page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1575]
## Story
As a veteran, I want to recommend some health appointment times to scheduling clerks so that I can get healthcare at a time that is convenient for my schedule.

## AC
- [ ] Page shows after 'how would you like to be seen' page
- [ ] Page asks veterans to provide one preferred appointment time (required) and up to 2 additional optional times that would also work
- [ ] Page conforms to screenshot of mock below

[Update for new calendar widget]

**Comment by markgreenburg** [comment]
@rtwell to confirm what we should do with this page - seems as though we probably need this but also probably need new mocks to reflect the calendar UI that was originally meant for direct scheduling.

**Comment by rtwell** [comment]
i think we do want this page. I'm leaning toward a little more straight forward approach to the previous/next buttons and just using links at the top cc @lalexanderson-dsva 

Also, i need to figure out a AM/PM annotation, but here's my first stab:
![image](https://user-images.githubusercontent.com/12564977/65278915-170ec080-dafb-11e9-8bc6-76f5260ce6ae.png)

**Comment by rtwell** [comment]
on second thought, i wonder a) should these be check boxes? and b) if stacking them would be easier to implement, esp on mobile:

![image](https://user-images.githubusercontent.com/12564977/65332641-1292e800-db8d-11e9-9b4b-7032815af4ec.png)

**Comment by jbalboni** [comment]
@rtwell The api we're submitting to looks like it doesn't allow you to send both AM and PM at the same time, so radio buttons might make more sense there.

Stacking them is probably slightly easier to implement, but not a big deal either way on the FE. It might depend on how you want to show multiple dates selected at once. Does the AM/PM tooltip thing collapse for dates you've selected but aren't active?

**Comment by rtwell** [comment]
do we need an interface that allows a user to choose a date with both AM and PM selected for the same date? currently, I believe a user can:
![times](https://user-images.githubusercontent.com/12564977/65336472-6c4ae080-db94-11e9-8a67-d88bb8d6d8b9.png)

**Comment by jbalboni** [comment]
I believe this is a duplicate, so I'm closing it.
