### ISSUE TITLE
Alert FE Bug affecting Benefits Hub

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15756]
## Issue Description
_FE bug here. Draft content should not be visible on the FE. i believe graphql is not checking published status before embedding the alert block on that page. This is affecting Benefits Detail Pages and the VAMC system detail page. VAMC editors don’t own any of these alerts, but they do use them (eg the Mental Health one)._

Slack Conversation [Here](https://dsva.slack.com/archives/C52CL1PKQ/p1604434835354000)

This bug was [surfaced by transformer team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15339) when diff'ing between CMS export generated pages, which only has access to published content, with graphql generated pages, which must specify have "published" status in the query. 

## Front end tasks
- Determine Alert Bug
- CMS team triage this issue with a FE engineer from PW.
- Validate Alerts are working once bug is addressed. 

## Acceptance Criteria
- [ ] Alert blocks are not visible on FE unless they are _published_ in CMS. 
- [ ] Designer comments on this issue to approve page styling 
- [ ] Alerts working normal in prod
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by kevwalsh** [comment]
i added one AC, feel free to tweak. 

`- [ ] Alert blocks are not visible on FE unless they are published in CMS. `

i'm unassigning myself, but please feel free to reach out via Slack if you have questions (or in this thread, but you might want to ping me in slack to alert me, cause sometimes i'm slow to see Github notifications).

**Comment by brianalloyd** [comment]
@ncksllvn this is available to be worked with you have bandwidth.  Thanks.

**Comment by brianalloyd** [comment]
PR merged, Validated, closing in support.
