### ISSUE TITLE
GIDS: Seed Accreditation file type data

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15765]
As a developer, I need to seed accreditation file type data so that there is test data available in the local environment for developer and QA team members to use in future stories.

## Assumptions:
1. Seeding loads data from the sample_csv/AccreditationData.xlsx file (https://ope.ed.gov/dapip/#/download-data-files)

## Acceptance Criteria:
1. The local development environment has Accreditation file type seed data.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/769

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Closing this out
