### ISSUE TITLE
DebtRes FSR Ch5 Resolution Options  

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15767]
As a Veteran I want to understand the different resolution options i have with the DMC 1-waiver 2-compromise 3-monthly offsets, payments before I make the choice on FSR form

**Comment by 3obryandogs** [comment]
	Resolution option selection (required). 
o	You have several options regarding repayment of VA compensation, pension and education debt. If you have more than one debt, you can choose an option for each one. For example, you could request a waiver for a compensation overpayment and a debt compromise for education debt. 
	Pay in full – You can pay the entire amount by check, money order through the mail. You also can pay online. Learn more about paying online.
	Repayment plan – You can ask DMC to set up a monthly plan so you can pay off the amount owed.
	For example, if you owe $5,000, you might request to pay $250 a month until the debt is paid off. Steps include:
	Answer FSR questions.
	Include an online “letter” that explains your financial situation and how much you can afford to pay each month. 
	Click “submit.” DMC will contact you by mail within 45 days.
	Debt compromise – If you can’t afford to pay the debt in full or through monthly payments, you can ask DMC to accept a lower amount.
1.	For example, if you owe $5,000, you might offer to pay $4,000. DMC will send your offer to the Committee on Waivers and Compromises for consideration. If it is accepted, DMC will contact you about the terms and how to make payment within 30 days. Steps include:
	Answer FSR questions.
	Write an online “letter” explaining why you are asking for a compromise and the amount you can afford to pay. 
	Click “submit.” DMC will contact you by mail within 45 days.
	Waiver – You can ask DMC to write off all or part of the amount owed based on financial hardship. 
	For example, if you owe $5,000, you can ask DMC to write off the debt. Steps include:
	Answer FSR questions.
	Write an online “letter” explaining why you are asking for a waiver. It should explain why collection of the debt would create a financial hardship.
	Click “submit.” DMC will contact you by mail within 45 days.
	Waivers for education debt will affect the length of time that you are entitled to receive those benefits. For example, if you ask that a semester be waived, VA Benefits Administration will reduce your eligibility for payment for a similar amount of time. 
	If you are requesting a waiver for an education, pension or disability compensation debt, you must submit your request within 180 days of the date you were originally notified of your debt.
	Dispute the debt – You can contact DMC If you believe you do not owe the debt or that the amount is incorrect.

**Comment by 3obryandogs** [comment]
I added the suggestion content to Becca and Riley's FSR outline.
