### ISSUE TITLE
DebtRes FSR Ch 4 Household expenses content 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15766]
As a Veteran filling out FSR form I want helpful content to understand what I should include in the expenses portion of the form

**Comment by 3obryandogs** [comment]
This is what I sent to Peggy for her input/review:
**C4: Household expenses**
This section gathers information about expenses you that you regularly pay to maintain your household and to care for your family. 
•	C4P1: Expenses
Please list monthly costs. For example, rent/house payments, groceries, utilities (gas, water, sewer, etc.), vehicle notes, and credit card payments. Also, consider monthly expenses like child care, school tuition, school meals, medical prescriptions, home or car insurance, transportation (gas, bus, parking), internet, cell phones, etc.

**Comment by 3obryandogs** [comment]
Also child support payments, alimony payments

**Comment by 3obryandogs** [comment]
I added suggested content to Becca and Riley's FSR outline.
