### ISSUE TITLE
DebtRes FSR Ch6 Bankruptcy Content

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15768]
As a Veteran filling out FSR I need to understand how to enter my bankruptcy case

**Comment by 3obryandogs** [comment]
C6: Bankruptcy attestation
This section gathers information if you have declared bankruptcy now or in the past. You can find the details in your legal bankruptcy paperwork.
•	C6P1: Bankruptcy attestation
o	Space is provided below for you to give more details about your bankruptcy case.


Leah and team: What role does bankruptcy play in the financial hardship request? Especially if it's a past event that has been resolved?

**Comment by 3obryandogs** [comment]
Added a line to the top of the Bankruptcy page.
