### ISSUE TITLE
Appointments Service Integration

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#15760]
## User Story / Task 
Integrating with the appointments endpoint. This is a backend task - the associated UI is included in different stories

## Acceptance Criteria

1. Service integration with the appointments API
     - Make a call to display upcoming appointments
     - Make a call to display past appointments 
2. Infer whether or not an appointment is "past" or "upcoming" based on the date
3. An appointment page should display the user's appointment information
4. The canceled status should be displayed in red if an appointment is canceled
5. Verify that the Past Appointments date range picker works when switching between dates
     - Selecting an option from the dropdown will display the appointments where the date corresponds to the dropdown selection

## Related ticket:
Display Join Session Link w/in 30 minute window: [#17916](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17916)

**Comment by digitalken** [comment]
Revisit this test case "Past Appointments List (UI) #13994"
https://dsvavsp.testrail.io/index.php?/cases/view/2110&group_by=cases:created_on&group_order=asc&group_id=-1
when this story is completed.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/2/2021 - Showing live data.
