### ISSUE TITLE
Filter past appointments

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15763]
## User story
As a user, I want the ability to filter out appointments across different date ranges. 

## Acceptance Criteria
1. On the past appointments page, create UI for "Select a date range" filter
2. Selecting the filter box opens the native dropdown picker
     - Default selection is "Past 3 months"
3. Include the following options in the dropdown menu:
     - Past 3 months (includes current month + the 2 previous months)
     - [Month Year] - [Month Year]
          - [5 months before the current month] - [3 months before the current month]
     - [Month Year] - [Month Year]
          - [8 months before the current month] - [6 months before the current month]
     - [Month Year] - [Month Year]
          - [11 months before the current month] - [9 months before the current month]
     - All of 2020
     - All of 2019 (the date ranges will not go past 2019)
4. Abbreviate month names
5. When "Past 3 months" is selected, the appointments list is displayed as a single list under the header "Past 3 months"
6. When any dropdown selection other than "Past 3 months" is selected, the appointments list is displayed by month, from most recent to least recent (same format as Upcoming Appointments)

## Designs
UI on Past Appointments page: https://adhoc.invisionapp.com/d/main#/console/20546460/432457679/preview

Example of dropdown options, where the current M/Y is Nov. 2020:
![Screen Shot 2020-11-02 at 12.34.34 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9ccd23eb-834a-40bf-970f-a35c7c416da4)

[Example of VA.gov desktop functionality](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/3965af6a-b40e-4da2-84d2-911ebd740b28)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

**Date Range Picker**

When not selected (covered in [past appointments story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13994)):
- accessibilityLabel= contents of field (e.g. Past 3 months)
- accessibilityHint="select a date range"
- accessibilityRole="spinbutton"
- accessibilityState= "collapsed"

When selected:
- Denote when dropdown is expanded
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list
- Ensure dropdown area does not "trap" the keyboard focus

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
@bridgethapner @srmyers17  looping you in on AC #4: **"Abbreviate month names [in the Past Appointments filter]".**

The screenshot from the web app UI shows some months are abbreviated ("Dec."), while some aren't ("June"), but it looks like for the mobile implementation, we'll need to either abbreviate all months, or none. To avoid wrapping, abbreviating all seems like the right way to go - but let us know if you think otherwise.

cc: @komaly15

**Comment by digitalken** [comment]
Pass for UI 11/24/2020 - Will be retesting when valid mock or real data is added.

**Comment by digitalken** [comment]
Pass on UI, fail on accessibility.  Bug entered:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16583

Moving to design QA.
