### ISSUE TITLE
Prepare for video visit page

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#15761]
## User story
As a user, I want to know how to prepare for a video visit

## Acceptance Criteria
1. The "Prepare for video visit" hyperlink routes to a new page
     - Display Back button
2. Styling and UI matches the design

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/434394494

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Back button in top left
     - accessibilityLabel= “Back”
     - accessibilityHint= “Go back to the appointment details page”
     - accessibilityRole= “button”
- Programmatically set page title as "Prepare for video visit page" and mark as Header 1
- Mark "Before your appointment" as Header 2
- Mark "To have the best possible video experience, we recommend you:" as Header 2 
- Mark "Medication review" as Header 2

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**12/02** 

UI and functionality pass on iOS and Android. Accessibility fails with [multi-issue bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16846) entered. Moving to Design QA

**Comment by digitalken** [comment]
iOS bug - not recognizing "Prepare for video visit" hyperlink. (Works on Android.)
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16859
