### ISSUE TITLE
CT: Landing page intermittently won't load on mobile

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#15778]
Users have experienced issues with the comparison tool landing page https://staging.va.gov/gi-bill-comparison-tool not loading on their iPhone on both chrome and safari. Seems to be intermittent and not a consistent issue.

Steps to reproduce:
1. Navigate to https://staging.va.gov/gi-bill-comparison-tool
2. Infinite spinner

**Comment by ksantiagomorgan6** [comment]
I was able to resolve the infinite spinner issue on both Safari and Chrome mobile browsers by clearing the browsing data. 

iPhone safari mobile: 

Settings > Safari > Clear History and Website Data

![image_from_ios.jpg](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/1e13562b-f203-429e-8878-271882ffa8b6)

On Chrome open the app press the three dots on the bottom right hand corner

Settings > Privacy > Clear Browsing Data

![image_from_ios-1.jpg](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/ba9fa6a1-6c3e-4573-adda-502f0f5b1e79)

**Comment by amyknox** [comment]
Sadly, this did not solve the issue for me.  But, after I reloaded the page 3 times, that did the trick.

**Comment by ksantiagomorgan6** [comment]
After clearing the cache, you need to force quit your browsers. But glad it works now.

**Comment by desireeturner** [comment]
Team agrees this was resolved sufficiently and we're going to close!
