### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#15776]
# Request Google Analytics access

## User Email Address
- Add Lauren Ernest - new VAOS product manager - lauren.ernest@adhocteam.us
- Add Peter Russo - new Sr. Designer for VAOS - peter.russo@adhocteam.us

Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

## Access Requirements
- Access to Google Analytics
- Access to VAOS domo
- and potentially a quick training session with the crew to help them understand the two tools?

## Date Required
- as soon as y'all can make it happen :)

## Product Team / External Team / VA Office
- VA online schedule, DEPO, OCTO

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @lenaecb ,

Both @laurenernest and @outerpress have been added to Google Analytics and DOMO 😄 

We look forward to working with you both!

**Comment by jonwehausen** [comment]
We are happy to setup a small training as well if would be helpful...would certainly be a good idea to review existing analytics for VAOS.
