### ISSUE TITLE
Letters: Research existing letter functionality.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15773]
As a developer, I need to research and document the existing letters functionality, so that the functionality is understood and be referenced for the inclusion of additional EDU letters.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. Documentation is attached to this story, including but not limited to:
    a. Currently available letters
    b. How letters are accessed (API, resources, etc)
    c. 

## Supporting Artifacts:
1. [Current Letters Page](https://www.va.gov/records/download-va-letters/letters/letter-list)
2. [Letters Repository](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/letters)
3. [Benefits Letter Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/benefit-letters)
4. [Benefits Letter Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/veteran-military-records)

**Comment by dmccurdybah** [comment]
# Current Letters Functionality

## Description

The Letters functionality is accessible in vets-website using the following URL:

    <vets-website-URL>/records/download-va-letters/

Users are required to be logged in and to have a valid address on file. 

A request is made to EVSS via vets-api to get the list of letters available for the user.  This list is displayed along with static content for each letter type, with the exception of the `benfit_summary` letter, which makes an additional call to get additional beneficiary data.

Not all users have mocked letter responses in the dev environment, but `vets.gov.user+1@gmail.com` has multiple letters available.

Letters are downloaded from EVSS via vets-api but this isn't mocked in dev vets-api so downloads fail.

## Currently Available Letters

- benefit_summary
- benefit_summary_dependent
- benefit_verification
- certificate_of_eligibility
- civil_service
- commissary
- medicare_partd
- minimum_essential_coverage
- proof_of_service
- service_verification

It should be possible to add support for any letters in EVSS by adding the letter type to this list in `lib/evss/letters/letter.rb`. Support for non-EVSS letters would require additional config of those letter types to additional services (which would require those other services to exist and be documented)

## Curent vets-api functionality

EVSS service code is in vets-api under `lib/evss/letters`

There are only three endpoints in the vets-api used for letters functionality (in `app/controllers/v0/letters_controller.rb`)

  - `index` - returns an array of letters available for the user
  
  Example response:
  ```json
  [
    {
      "name": "Commissary Letter",
      "letterType": "commissary"
    },
    {
      "name": "Proof of Service Letter",
      "letterType": "proof_of_service"
    },
    {
      "name": "Proof of Creditable Prescription Drug Coverage Letter", "letterType": "medicare_partd"
    },
    {
      "name": "Proof of Minimum Essential Coverage Letter", "letterType": "minimum_essential_coverage"
    },
    {
      "name": "Service Verification Letter",
      "letterType": "service_verification"
    },
    {
      "name": "Civil Service Preference Letter",
      "letterType": "civil_service"
    },
    {
      "name": "Benefit Summary Letter",
      "letterType": "benefit_summary"
    },
    {
      "name": "Benefit Verification Letter",
      "letterType": "benefit_verification"
    }
  ]
  ```
  
  - `download` - download a letter pdf by letter type
    
  - `beneficiary` - returns beneficiary information

    Example response:
    ```json
    {
      "data":{
        "id":"",
        "type":"evss_letters_beneficiary_responses",
        "attributes":{
          "benefitInformation":{
            "monthlyAwardAmount":123.0,
            "serviceConnectedPercentage":2,
            "awardEffectiveDate":"1965-01-01T05:00:00.000+00:00",
            "hasChapter35Eligibility":true,
            "hasNonServiceConnectedPension":false,
            "hasServiceConnectedDisabilities":true,
            "hasAdaptedHousing":false,
            "hasIndividualUnemployabilityGranted":false,
            "hasSpecialMonthlyCompensation":false
          },
          "militaryService":[
            {
              "branch":"ARMY",
              "characterOfService":"HONORABLE",
              "enteredDate":"1965-01-01T05:00:00.000+00:00",
              "releasedDate":"1972-10-01T04:00:00.000+00:00"
            },
            {
              "branch":"ARMY",
              "characterOfService":"UNCHARACTERIZED_ENTRY_LEVEL",
              "enteredDate":"1973-01-01T05:00:00.000+00:00",
              "releasedDate":"1977-10-01T04:00:00.000+00:00"
            }
          ]
        }
      }
    }
    ```

## Screenshots

![Screen Shot 2020-11-13 at 11.56.38 AM.png](https://images.zenhubusercontent.com/5bb388cc38a73929698456e2/3c600647-4aaf-4085-9576-f685732916f9)

![Screen Shot 2020-11-13 at 12.00.14 PM.png](https://images.zenhubusercontent.com/5bb388cc38a73929698456e2/0956c9a6-bf32-4390-9fee-0cd42555e6ec)

**Comment by desireeturner** [comment]
@dmccurdybah Could you add the results of your research to this folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/validated-user-login

**Comment by dneel-bah** [comment]
Q+A
Darrell:
In your notes, it says that the “certificate_of_eligibility” is a currently available letter.
When looking at the “Only returns letters eligible for the user.” comment, it does not appear as if the COE is listed.  Is there a mapping or something happening there?

Devin:
That’s pulled from the documentation for the EVSS service.  It’s possible that we have a letter in our list of allowed letters that is never actually returned *by EVSS, but we would need someone in EVSS to confirm that (edited).

Screenshot showing COE not available.
![letter_screenshot](https://user-images.githubusercontent.com/48260534/99537223-6491f200-2979-11eb-8da4-ab3351d39b3e.png)
