### ISSUE TITLE
Access for Greg Bowman

### ISSUE THREAD

**Issue by gpbowman-git** [department-of-veterans-affairs/va.gov-team#15789]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee - Cecilia.Lee@va.gov
- Please provide your name.
   > Gregory Bowman
- Please Provide your email.
   > gregory.bowman@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Matsumoto, Senior Software Engineer, Liberty IT Solutions

Regarding SSH authorization, I have requested it previously. Here is the ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15065

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house

@department-of-veterans-affairs/vsp-operations please review

**Comment by tskinn** [comment]
@gpbowman-git I'm going to close this in favor of using your previous issue. https://github.com/department-of-veterans-affairs/va.gov-team/issues/15065
