### ISSUE TITLE
Build 'confirm address' page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1578]
## Story
As the VA, I want to enable veterans to confirm & update their address on file so that we can determine their Community Care eligibility (based on drive time) accurately

## AC
- [ ] Page shows existing address on file from PSSG / E&E (i.e., the address with which a veteran enrolls in healthcare)
- [ ] Page allows veteran to update the address on file that's used for CC drive time eligibility checks
- [ ] Page shows after selecting 'create a new appointment' from the home screen (and before 'choose how you would like to make an appointment' screen
- [ ] Page (roughly, since the mock has some wonky formatting) conforms to the latest mock:

![Screen Shot 2019-09-04 at 4.32.59 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/ee8046ba-d9b4-4fda-9206-163914940967)

## Open Questions
- Where does the address come from?
- Is the address updatable from the internet?
- Does updating the address in the source immediately reflect in Drive Time calculations, or is there some caching going on?

## Zenhub link
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1578

**Comment by markgreenburg** [comment]
Not in scope for MVP; too many open questions.

**Comment by lenaecb** [comment]
Adding this to the reevaluate epic. This is not confirmed as a business or user need currently.

**Comment by lenaecb** [comment]
This was completed in a different ticket. [9852](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9852)
