### ISSUE TITLE
Access for Margaret Brazeau

### ISSUE THREAD

**Issue by MaggieBrazeau** [department-of-veterans-affairs/va.gov-team#15799]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Margaret Brazeau
- Please Provide your email.
   > maggie.brazeau@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS CMS Helpdesk - Agile Six

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFflb4U470Pn15RFiAcFl7IhC81Iy04MwcrQzo0r7n4PDNuCLJKmRHrlyn2NyJchcucQzaqp8n8d9GYB8X6eu1txC38QstLLm1MvU8Hv9jNSGp5A1L/VFtxYD/E2/2RP9eq4UzdYpAqoxEplhX9IDuMmRUQwHNVljzBw9lJGK8uJm73oNKsxH8928jdYwErmCzQ+lGty5MpCh7IiknSLATmcAls+VZG/oemVRSCKKa/zMHiuQmlXU6i5JAp7oFhXAzLvP7ESqXF3SiMFs352+abaFh3sJZBT990tNFn9ZU6JAIBMI+sT3SCelHn46PjXL88uUhpgOtyQq9JtiDAF2L2xqr4wHXdbCDb+315KZBn33+0XJaSxn8xtQshYH3NMakBTLhpwEIHGfevNmLUh0GA8wuiLxJ1kEfDg5TydKvDS/YPwcdmqkC4GIoetCGm0KKBRw72adXs5+MaqZcpr5Tw7ITlAdW6hw2lQ52593sjPsyIRd1GHYsH03U2fGzCA0= Missy@LtUhura

```

- Grant AWS Console access?
  >NO
  - What AWS services do you need access to and why?

**Comment by MaggieBrazeau** [comment]
@department-of-veterans-affairs/vsp-operations   

Submitting new request for SSH key approval for second computer.

**Comment by tskinn** [comment]
Your new key has been added.

**Comment by jbritt1** [comment]
User is offboarded (#16765)
