### ISSUE TITLE
Add alert when type of care isn't listed

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15794]
## Issue Description
As a user, I would like a path forward if the type of care I need is not listed so that I can continue to make an appointment.

---

## Acceptance Criteria
- [ ] Display copy for type of care alert
> Not seeing the type of care you need?
> You'll need to call your VA health facility to schedule an appointment. Find a VA location

- [ ] If user clicks/taps Find a VA location, then facility locator opens in a new tab (/find-locations) 
- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs https://adhoc.invisionapp.com/share/BJZCR5H547N
- [ ] ANALYTICS - Track facility locator link clicks

**Comment by lenaecb** [comment]
Check with vsp-analytics for naming of event

**Comment by outerpress** [comment]
@laurenernest specs are here: https://adhoc.invisionapp.com/share/BJZCR5H547N

**Comment by bsmartin-ep** [comment]
@jonwehausen / @laurenernest -

Is this something we could surface without a custom event?  Maybe look at the Facility Locator's previous page path?

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.previousPagePath&explorer-table.advFilter=%5B%5B0,%22analytics.previousPagePath%22,%22PT%22,%22schedule-view-va-appointments%22,0%5D%5D&explorer-table.rowCount=50&_r.drilldown=analytics.pagePath:www.va.gov~2Ffind-locations~2F

Or is this not granular enough?  Or are page URLs not a good pivot?

**Comment by laurenernest** [comment]
@bsmartin-ep We also have a link to the facility locator in the footer of that page so we'd want to distinguish the click from the alert vs the footer.
![Screen Shot 2020-11-10 at 9.48.18 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/8d7e99c1-a45b-4bcd-b53c-2f9b3401a5c8)

**Comment by bsmartin-ep** [comment]
Ah - makes sense @laurenernest.

@jonwehausen -

Thoughts on using `nav-alert-link-click` for this?

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/e55cd0e8-922f-4567-9049-e08234604567)

**Comment by LanceGundersen** [comment]
@bsmartin-ep @jonwehausen pinging you folks to see about which tag to use for this. I have the code ready to go with exception of the analytics piece.

**Comment by jonwehausen** [comment]
Hi team,

Thanks for including me here, @bsmartin-ep with this being an [informational alert box](https://design.va.gov/components/alertboxes#informational-alert), let's use the event name of **`'nav-alert-box-link-click'`** and be sure we include some additional metadata: 

```javascript
'event': 'nav-alert-box-link-click', //consistent for all alert box link clicks regardless of type
'alert-box-type': 'informational', //consistent for alert boxes of informational type
'alert-box-heading': 'Not seeing the type of care you need', //dynamically capture the top level heading of the alert box
'alert-box-subheading': undefined, //no subheading in this case, so just populate with undefined
'alert-box-click-label': 'Find a VA location', //dynamic according to the link label clicked on 
```

@bsmartin-ep We can then adjust our GTM container to reflect this taxonomy...perhaps a nested lookup with `alert-box-type` as an input that outputs "Informational Alert Box - {{DL - alert-box-heading}} - Link - {{DL - alert-box-click-label}}"?

**Comment by laurenernest** [comment]
@LanceGundersen I'm not seeing the alert in staging. Can you double check?

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Here is a GTM workspace with the new alert box link click changes:

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000386

**Comment by LanceGundersen** [comment]
> @LanceGundersen I'm not seeing the alert in staging. Can you double check?

![Uploading Choose_the_type_of_care_you_need___Veterans_Affairs.png…]()

**Comment by laurenernest** [comment]
Confirmed the alert is in Production.
![image (4).png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/9fcc406d-4cda-4f4e-8f36-8650d4fc44c0)

**Comment by bsmartin-ep** [comment]
## QA 

Interaction|Data Layer|GTM tag|Pass
---|----|---|----
Click on "Find a VA Location" link|![image](https://user-images.githubusercontent.com/62304138/101421816-38f09080-38c3-11eb-8adf-3db1097e950f.png)|![image](https://user-images.githubusercontent.com/62304138/101421854-4c036080-38c3-11eb-8a73-aeee3b0fb149.png)| **PASS**

Published.

We should have production data shortly.
