### ISSUE TITLE
Access for Cris Shupp

### ISSUE THREAD

**Issue by cshupp1** [department-of-veterans-affairs/va.gov-team#15790]
Fill out Description
Add the label used by your team (eg: Matsumoto)
Do not remove operations label; this will notify the VSP Operations team of your request
When the issue is closed you will be notified and can continue with on-boarding setup
Description
Please provide your Contracting Officer's Representative (COR) name.
Cecilia Lee - Cecilia.Lee@va.gov

Please provide your name.
Cris Shupp

Please Provide your email.
cristopher.shupp@libertyits.com

Please provide the name of your team, your role on that team, and the name of the company you work for.
Team Matsumoto, Senior Software Engineer, Liberty IT Solutions

Regarding SSH authorization, I have requested it previously. Here is the ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15064
Grant AWS Console access?
YES

What AWS services do you need access to and why?
S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house

@department-of-veterans-affairs/vsp-operations please review

**Comment by pshahVA** [comment]
Team is Lighthouse API's.

**Comment by jbritt1** [comment]
For AWS Access:

User: Cris Shupp
COR: Cecilia Lee
Approval needed: @Jeff-Hayter

**Comment by jbritt1** [comment]
@cshupp1, were you able to establish a connection to the SOCKS proxy using [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)?

**Comment by cshupp1** [comment]
@jbritt1 

$ ./sock_start.bash
Agent pid 1912
Enter passphrase for /c/Users/CristopherShupp/.ssh/id_rsa_vagov:
Identity added: /c/Users/CristopherShupp/.ssh/id_rsa_vagov (AzureAD+CristopherShupp@DESKTOP-1EFHNS6)

AzureAD+CristopherShupp@DESKTOP-1EFHNS6 MINGW64 ~
$ curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.gov
*   Trying 127.0.0.1:2001...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* SOCKS5 connect to sentry.vfs.va.gov:80 (remotely resolved)
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 2001 (#0)
> GET / HTTP/1.1
> Host: sentry.vfs.va.gov
> User-Agent: curl/7.71.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Tue, 10 Nov 2020 17:08:48 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Server: nginx
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: noindex, nofollow
< Content-Language: en
< Vary: Accept-Language, Cookie
< Location: /auth/login/
< X-Frame-Options: deny
< X-Content-Type-Options: nosniff
< Set-Cookie: sentrysid="gAJ9cQFVBV9uZXh0cQJYAQAAAC9zLg:1kcX8S:piYrPsnV9suYvtJOw73h4r3B2O4"; expires=Tue, 24-Nov-2020 17:08:48 GMT; httponly; Max-Age=1209600; Path=/
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host 127.0.0.1 left intact

AzureAD+CristopherShupp@DESKTOP-1EFHNS6 MINGW64 ~

**Comment by jbritt1** [comment]
Yep, `302 found` is exactly what you want there. Were you able to hit the internal tools in the browser as well?

**Comment by cshupp1** [comment]
![image](https://user-images.githubusercontent.com/5719570/98707484-17e16200-234e-11eb-8633-8da2587b842c.png)
@jbritt1 Yup!

**Comment by jbritt1** [comment]
Beautiful, now we are just awaiting approval for AWS access from the COR Jeff Hayter (please be patient with us on this one as it takes some time). Have you submitted an eQIP yet?

**Comment by cshupp1** [comment]
Yes, eQIP is submitted @jbritt1

**Comment by jbritt1** [comment]
Roger, sounds like you are right on track.

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
Temporary credentials passed to user at this time.
