### ISSUE TITLE
Support dynamic heading tags on the Multiple FAQs page 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15797]
## Issue Description
_Support dynamic heading tags on the Multiple FAQs page (when there isn't a section header, then FAQs should render as an H2)_

## Front end tasks
- Estimate Task and Remove needs grooming label
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by brianalloyd** [comment]
Adding @zacharymorel to this ticket to work this sprint.  @ncksllvn @kelsonic can help provide technical context in support.  Zach please provide an estimate, once estimated please remove the `'needs-grooming'` label in support.

**Comment by kelsonic** [comment]
Oops just saw your comment Brian, I'll leave this one 🙂

**Comment by kelsonic** [comment]
Nevermind, as per [this thread](https://dsva.slack.com/archives/C52CL1PKQ/p1604936247045900) I'll be picking this up

**Comment by kelsonic** [comment]
The `fieldQAGroups` has an __optional__ header, which is currently being rendered as an `h2` tag __if it's present__, otherwise we render nothing for the QA Group header. Should I change this to an `h3` tag? I ran an axe a11y test and the headers seem to increment correctly as an `h2` tag, except for the footer which is out of scope for this ticket (that's a site-wide issue)

**Comment by ncksllvn** [comment]
> The fieldQAGroups has an optional header, which is currently being rendered as an h2 tag if it's present, otherwise we render nothing for the QA Group header. Should I change this to an h3 tag? I ran an axe a11y test and the headers seem to increment correctly as an h2 tag, except for the footer which is out of scope for this ticket (that's a site-wide issue)

If there is _not_ a QA Group header, then [this](https://github.com/department-of-veterans-affairs/vets-website/blob/480f2cc282f77dc2fcb1c305a01cb4c0fea9e7b0/src/site/layouts/faq_multiple_q_a.drupal.liquid#L85) should be an H2, not an H3.

**Comment by jenniferlee-dsva** [comment]
Thanks for linking me to a preview - node 8249. Couple things: 

> The fieldQAGroups has an optional header, which is currently being rendered as an h2 tag if it's present, otherwise we render nothing for the QA Group header. 
This is correct and the logic we want, PLUS see below:

> Should I change this to an h3 tag? 
No. 

ADDITIONALLY, we want the this dynamic H2 heading logic **_when there is no QA group header:_** 

- When there is no Q&A group section header, render the questions text on that page as H2s instead of H3s.

**Comment by jenniferlee-dsva** [comment]
Screenshot: 

If group section header is 0, render the questions  (example: "Why should I trust VA.gov?" ) as H2s instead of h3s. 

![image](https://user-images.githubusercontent.com/43381063/98582018-5c0e2d00-2290-11eb-96f1-74277c22790f.png)

**Comment by kelsonic** [comment]
Got it, thanks for the clarification @jenniferlee-dsva and @ncksllvn! 🙂

**Comment by jenniferlee-dsva** [comment]
When this is ready, we can validate against this preview page - which currently includes a group H2, but I can remove that to see if the logic then works for the question texts. 

http://preview-prod.vfs.va.gov/preview?nodeId=8249

**Comment by ncksllvn** [comment]
I think this is patched now @jenniferlee-dsva 

http://preview-prod.vfs.va.gov/preview?nodeId=8249 ->

![image](https://user-images.githubusercontent.com/1915775/98833416-fb0b6400-240b-11eb-8e38-7e75dcec187f.png)

**Comment by jenniferlee-dsva** [comment]
It works! love it. Thank you @ncksllvn . 

I tested the dynamicness by removing the "How we keep your personal information safe" optional header, and the question texts rendered as H2. 

This helps us streamline and remove redundant/repetitive filler header content. Closing as validated.
