### ISSUE TITLE
School Ratings: Update width and spacing on mobile version

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#15805]
## Assumptions
This work is completed behind feature flag gibct_school_ratings created in #13359.

## Acceptance Criteria
1. The width of the mobile view has been updated so that the expand (+) and collapse (-) icons are not cut off on the screen (10px padding). Note this is true in both the "hover" and "select" state. 

## Supporting Artifacts
1. ![8b92c0ba-7236-4d2c-9ba6-90af0ec2bc04.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/cd525e88-4f07-419d-ac20-c6416a21180c)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14895

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-11-09 at 12.02.08 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2a786aed-0110-4f85-b9db-3bffc430f68f)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-11-09 at 12.02.59 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/54c420e0-40f6-4e56-a09b-ad3fe9cc02aa)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/14162&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah this is on staging ready for review

**Comment by watersemma** [comment]
UX Review 1/2: This checks out to me! Thank you!

**Comment by JenLJ** [comment]
UX Review 2/2: This checks out for me too!

**Comment by sonntag-adam** [comment]
Closing story
