### ISSUE TITLE
[FE/Analytics] Direct deposit: How can we approximate number of people with direct deposit info vs. number of people eligible but without direct deposit info?

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15806]
## Background

We are trying to answer the following question: Of the people who are eligible for direct deposit at the VA, how many of them actually have direct deposit set up? To get true metrics on this, we'd probably have to work with EVSS/BGS, which, while not impossible, would be more challenging and would not allow us to readily track progress over time.

So, instead, we'd like to do our best to approximate this through data on VA.gov. Here's one proposal on how to do that:

- Add tagging/tracking on whether we load the direct deposit section in someone's profile or not. This will give us the whole amount of people on VA.gov in a given time period who are eligible for direct deposit.
- Add tracking on whether we show the "Add" link or the "Edit" link (**Note**: We already have tracking on whether people click these CTAs, but not on whether we simply show them). This would give us an approximation of how many people are eligible and have direct deposit information already added and how many people are eligible but have not set up direct deposit.

If we think this would be a good enough way to answer the question "How many eligible profiles have direct deposit set up?", then we can move forward with adding the tagging I mentioned above, and then I will pull in analytics to add that to our direct deposit dashboard.

## Tasks

- [ ] Review this with Matt when he gets back.
- [ ] Implement whatever tagging we need to track these metrics.

**Comment by erikphansen** [comment]
Sounds good and would be pretty easy to implement on the FE. We just need to know the two events/payloads to send to GA.

**Comment by Samara-Strauss** [comment]
Closing this in favor of #15874
