### ISSUE TITLE
Build 'confirmed appointment details' page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1580]
## Story
As a veteran, I want to be able to see the details for any of my confirmed upcoming appointments so that I know where to go and when.

## AC
- [ ] Page shows after a veteran clicks on details button for any confirmed appointment
- [ ] Page does NOT include 'cancel' or 'reschedule' links (tbd in separate tickets)
- [ ] Page conforms to latest mocks below
- [ ] Any risks or data gaps documented in this ticket

![Screen Shot 2019-09-04 at 4.56.21 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/1f4d0419-72a3-43ac-a42e-19a6dcf3e450)

**Comment by jbalboni** [comment]
I don't think we have the address for the facility, but we have the id, so we'll probably need to fetch the address from the current facilities endpoint and display a map that way.
