### ISSUE TITLE
Access for Tim Wright

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#15815]
# Description
I think I may have previously submitted the wrong public key previously, I'm still getting permission denied messages.

- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Tim Wright
- Please Provide your email.
   > timwright12@gmail.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Front End Tools, Staff Software Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCT74RQbYRVHnoaP3K/1qjBI+CKnjXSJkJk/nIP937gFgwTKmM4j2yQ+MwSq8uGRcOIXN3z44H2zgqKz4vsAW2m3bvjQeNEALQOreny30vEGHgnJUT7tvmp483WAm9K3jPoUSiIN05wJ3ObfH6dOYCTenKlufNfvoqCzbJqJIwu4RE7LxvSKUswHFNSHtMnF81NhKvx2ObE1vtbta8IXQigWBP05o0CUJQ+x1oNzXpZ3zhCrtnHiYPqNWM6VK6A7dBLO0dWhgbiyFaLZ6+41AW4g20z27Ii9tYxftYi9I3+c5K/RBCkdeQXtp8x9dDqzcPzyAKozaeoEMBulntfdZWMJNIocHlaNGPHdVSdIdDWIx2CDOeTQIhKqTRsR8ZWdityIIIUi6JVevkvwnjrUzcUj11KPRA79H6Gdcr3/t885E1UOXMhZaUyuEZeFzmRV0gMXxU6tqanWh9sl6GcOOHmnNKyXY2a25LvOWIUI697iNb8Npt1PdtyhF3LlEHT4wEUzgVXZ7tIyiQ6Ph5/EX++8Y0/lBwyBi7Mtkxc5vxehNIJC/F8EzB/WX7afi5tPvld+Wp/yS1112hjVMXFx7nkP82JPgrqcMlaqyjsTr7NEO2ZE9hv0N320PzeiyKRbJwyWVW/Zbzo0O4Kcurag+tsSup/NHnXfWFJCQv9dTilTQ== timwright12@gmail.com

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why? 
 > n/a

**Comment by meganhkelley** [comment]
@timwright12 do you have all the access you need? If so, please close this ticket. Thanks!

**Comment by jhouse-solvd** [comment]
@timwright12 - sorry to spam, but please do let us know if you have everything you need, and I can close the ticket out for us.

**Comment by timwright12** [comment]
@jhouse-solvd yes, I'm good now. Sorry I missed these messages! Closing out.
