### ISSUE TITLE
Missing Regional Benefit office phone numbers

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15818]
## What happened?
Regional Benefit Offices do not have phone numbers displayed on detail pages or within search result cards on Facility Locator. This was identified while on the phone with Sandy Tadeo. We confirmed the information is available in the data source. 

Numbers beginning with 1-800 seem to be missing. 

<details>
<summary> Example from https://www.va.gov/find-locations/facility/vba_301 </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/e2760526-8aee2-43a9-a3ab-c08428543ac5)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/7660741b-85dd-450f-a99e-6729875aeeb2)

</details>

<details>
<summary> Not all facilities are affected </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/fa058eec-37cc-49ff-aa52-c0dc835493ae)
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/9c20e99c-2082-4eae-b8ac-4e1a97927df7)

</details>

## Acceptance Criteria
- [ ] If phone number is available in source data, it should be displayed in search results and on detail pages. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Link to Slack thread https://dsva.slack.com/archives/C0FQSS30V/p1604527877314600

**Comment by davidconlon** [comment]
This is also happening on the search results as well as detail

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/dbfbea4f-dd39-475a-8308-5e382c1f2520)

**Comment by mpelzsherman** [comment]
Confirmed working in prod:

![Find_VA_Locations___Veterans_Affairs](https://user-images.githubusercontent.com/80267/100625342-643b1480-32f2-11eb-9f7e-2cbcb459cfd4.png)

![Boston_Regional_Office___Veterans_Affairs](https://user-images.githubusercontent.com/80267/100625367-70bf6d00-32f2-11eb-90b5-e15ace996868.png)
