### ISSUE TITLE
Different font sizes for hint text on edit fields

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15812]
## What happened?
On the Direct Deposit and Edit Address/Phone/Email screens, the grey "hint" text that appears in each field is not the same font size across all fields. Per the designs, this font size should be 17px. 

## Desired behavior:
Per the designs, the font size for this hint text should be 17px across all fields. 

## Severity: 
Low

## Specs: 

- Samsung Galaxy S9
- User: patient998@id.me

## Screenshots

- Example from Edit Address screen: ![Screenshot_20201104-130152_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ba2b0852-ceee-4e00-ab88-9e10c4c8c350)

- Example from Direct Deposit screen: ![Screenshot_20201104-130630_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e53e3363-94ff-40d9-a93f-1d77e5426eca)

## Acceptance Criteria

- [ ] Hint text across all edit fields is 17px

**Comment by digitalken** [comment]
Note:  Looks good in iOS build. 11/6/2020 @ 12:31 PM...

**Comment by digitalken** [comment]
PASS 11/9/2020 on both iOS and Android.  Hint fonts are consistent sizes.
