### ISSUE TITLE
GI Bill Feedback Tool should not give users error when submitting data

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#15811]
## What happened?

On 2020-11-03 @WillMcCormack [reported](https://dsva.slack.com/archives/CBU0KDSB1/p1604428679479500) users experiencing submission errors with the [GI Bill Feedback Tool](https://www.va.gov/education/submit-school-feedback/introduction). 

Looks like users submitted and ran into this issue on 2020-10-08, 2020-10-13, and 2020-11-3

Relevant API code is in [`lib/gibft/service.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/gibft/service.rb).

## Specs:

From the DSVA Slack thread:

> This complaint was originally submitted on 13 October 2020 on my laptop using Windows 7 Home Premium Service Pack 1 and Firefox 60.8 (see attached).
> This complaint was then submitted today, 3 November 2020 on my laptop using Windows 7 Home Premium Service Pack 1 and Microsoft Edge 86.0 (see attached).

## Steps to Reproduce
Not defined, yet

- URL: https://www.va.gov/education/submit-school-feedback/introduction
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_
Users should not see an error

## Acceptance Criteria
- [ ] GI Bill Feedback tool works when users submit feedback

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by kfrz** [comment]
# 2020-11-04 

- Picked this up to help @ericboehs on support sprint
- This is the result of a job submission, likely failing.  That code lives [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/gi_bill_feedback_submission_job.rb)
- Cloudwatch [query here](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E$25272020-11-04T05*3a59*3a59.000Z$257Estart$257E$25272020-11-03T06*3a00*3a00.000Z$257EtimeType$257E$2527ABSOLUTE$257Etz$257E$2527Local$257EeditorString$257E$2527parse*20*40message*20*27*22timestamp*22*3a*22*2a*22*27*20as*20time*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20parse*20*22*2a*20*2a*20*7c*22*20as*20serverTime*2c*20jobName*0a*7c*20parse*20*40message*20*27*22host*22*3a*22*2a*22*27*20as*20host*20*0a*7c*20parse*20*40message*20*27*22level*22*3a*22*2a*22*27*20as*20level*0a*7c*20parse*20*40message*20*27*22application*22*3a*22*2a*22*27*20as*20app*0a*7c*20parse*20*40message*20*27*22name*22*3a*22*2a*22*27*20as*20loggerName*0a*7c*20parse*20*40message*20*27*22message*22*3a*22*2a*22*27*20as*20msg*0a*7c*20parse*20*40message*20*27*22thread*22*3a*22*2a*22*27*20as*20thread*0a*7c*20parse*20*40message*20*27*22pid*22*3a*2a*2c*27*20as*20pid*0a*7c*20parse*20*40message*20*27*22named_tags*22*3a*7b*22class*22*3a*22*2a*22*27*20as*20class*0a*7c*20filter*20class*20like*20*2fGIBill*2a*2f*0a*7c*20limit*20100$257EisLiveTail$257Efalse$257EqueryId$257E$252713050f43-62fd-4d7f-81fc-3607f072c522$257Esource$257E$2528$257E$2527dsva-vagov-prod*2fsrv*2fvets-api*2fsrc*2flog*2fvets-api-worker.log$2529$2529) shows all GIBill* jobs in prod for 11/3 (CST)

**Comment by alexpappasoddball** [comment]
@ericboehs & @kfrz Is this resolved now, or is there more to do?  If its not we should close

**Comment by kfrz** [comment]
Closing as this is on #vsa-benefits team's board: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7701
