### ISSUE TITLE
Analytics Consult for [Facilities- Vet Centers]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15820]
# Analytics Consult Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
This request is for an exploratory conversation about what analytics are possible beyond the VA.gov realm. 
Who is this request for?

- Facilities Team - Vet Center Initiative
   - Dave Conlon (DEPO Product Owner)
   - Michelle Middaugh (Product Manager)
   - Leyda Hughes (Design/Research)

Additional Comments
- We'd like to schedule a time to talk through options for measuring success for our new Vet Center initiative. In short, we'll be creating a new online presence for these locations. Problem to solve - awareness and findability
- We're interested in exploring options like Google Business Listings, Google/Bing search results, etc. 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks for your request @mmiddaugh !

@joanneesteban Would you mind coordinating with Michelle and team on getting another consult on the calendar? Thanks in advance. 

In the meantime, as it sounds like it would be of interest here, I have added @davidconlon and @mmiddaugh to Google Search Console, you can access that data [here](https://search.google.com/search-console?resource_id=https%3A%2F%2Fwww.va.gov%2F). We can also get you added to Bing Webmaster Tools if desired by following these instructions [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15643#issuecomment-720690780)

**Comment by mmiddaugh** [comment]
@jonwehausen ...If I understand the Search console correctly, it seems that the Facility Locator URL is not indexed but is available to Google.

**Comment by jonwehausen** [comment]
Hi @mmiddaugh , 

I can confirm with you www.va.gov/find-locations is currently live and being indexed by Google Search Console: 

![image](https://user-images.githubusercontent.com/48527022/98615327-546a7a80-22c8-11eb-86bf-9a4271704179.png)

**[Here](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fwww.va.gov%2F&breakdown=query&page=!https%3A%2F%2Fwww.va.gov%2Ffind-locations%2F)** is where you can find Google Search Console data filtered for facility locator. 

cc: @joanneesteban @bsmartin-ep @bmcgrady-ep

**Comment by jonwehausen** [comment]
@mmiddaugh We are going to close this issue per our conversation today, as we now have 16566 opened on our end when we're ready to begin on the SEO audit for vet facilities. Thanks again.
