### ISSUE TITLE
Omit unrelated results - learning center

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15826]
## Omit unrelated results - learning center

**What happened?**
I searched on "service dogs" in the RS search. There is only 1 article about service dogs. But the search results brought back ALL 26 articles in the learning center. 

I **_think_** what is happening is that the results are not omitting any articles but display ranking them ALL by relevance (?).  We do want relevance ranking but only within the subset of actually related results. We don't want to bring back everything to rank display - if what I suspect is happening. 

**What should happen?** 
The results should not include ALL RS articles, only the ones that have "service dogs" somewhere in the article. 

https://www.va.gov/resources/search/?query=service+dogs+

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/462d0b28-1f3a-4964-aeea-4c87df265956)

**Comment by johnhashva** [comment]
I'm not able to replicate this -- works as expected -- e.g. service dogs returns one article about service dogs.   @ncksllvn did this get fixed?

**Comment by jenniferlee-dsva** [comment]
This appears resolved. Will close.
