### ISSUE TITLE
Synthesis: Community Care request interviews

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15823]
## Issue Description
Synthesize findings from sessions conducted with Community Care request managers in November 2020

## Goal of research
- Understand the current data & process that a community care request manager uses to process Veteran's community care requests
- Understand/gather feedback (where possible) about the VAOS requests for community care coming into Community Care request manages
- Understand how and where Community Care Request managers search for type of care/specialties and providers.

## Hypothesis
By understanding how Community Care schedulers use systems to manually process specific requests, and how they search for care providers on behalf of Veterans, we can better understand how to automate/simplify this search experience on Facility locator and VAOS.

## Tasks
Synthesize findings of research 

## Acceptance Criteria
- [ ] Research readout

**Comment by chrisdlogan** [comment]
Research findings can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/community-care/research-findings.md
