### ISSUE TITLE
Bug: Search query not carrying over (learning center)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15825]
## Bug: Search query not carrying over (learning center)

**What happened?** 
When I enter a search term in the search bar - using `Resources and support` option - instead of immediately taking me to the results, I'm taken to a page that says "Enter a query to get started." 

**What should happen?** 
When I enter a query and click the search button, it should take me right to the results page - either with a list of results or, if no results, give me the 'no results' error message. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/33ecdaf7-c844-433c-ae80-b0f7453298f9)

Also - we don't have a search only page in the LC IA  - so there shouldn't be this interim search-only learning center page. 

**The designed UX is:**

1/ User enters a RS search query (from any RS page) --> user is immediately taken to results. 
- If the user used the default RS radio button choice, the results are shown in the RS. 
- If the user used the `All VA.gov` radio button choice, they are taken to the results display on global site search.

**Comment by ncksllvn** [comment]
The fix for this has been merged

**Comment by jenniferlee-dsva** [comment]
Thx Nick - I'll check after today's deployment.

**Comment by jenniferlee-dsva** [comment]
I'm still seeing the bug. Did the daily deployment not go through today?

**Comment by ncksllvn** [comment]
@jenniferlee-dsva No, unfortunately the daily deployment failed today

**Comment by jenniferlee-dsva** [comment]
thx for the 411 Nick. I checked this morning  before seeing your message and it is working now. So a deployment must have gone through sometime after I checked yesterday. Anyway - lgtm, and will close this as validated. Thx @ncksllvn !
