### ISSUE TITLE
CT Site Search - Selective Searching

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#15828]
## What happened?
CT search on production isn't returning full results sets. 
- When you search for "high school" you get 2 results - that's it. 
- When you search for "Stanford" you get 3 results, 2 of which have "High School" in the name of the institution, neither of these is a result returned if you search for "high school"

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/bb401f79-de19-4180-badd-2048eafd79f1)

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/6005835b-8e99-4454-8f87-cf6d8a1f8100)

## Specs:  Observed on:
- Device: PC / laptop
- Browser: Chrome
- Test User NA

## Steps to Reproduce
- URL: https://www.va.gov/gi-bill-comparison-tool/
  - search for: high school
  - search for: Stanford (don't use autocomplete)
- Test User _(if applicable)_: NA

## Desired behavior
The search term should return all results that have the term in the name of the institution, at a minimum.  

## Acceptance Criteria
- [ ] CT search will include all results with the searched term

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zurbergram** [comment]
The issue with "high school" and other searches using only excluded words is because only the `institution_search` column is used for search.  

The 2 results displayed in description are appearing because the institution name only contains excluded search terms

![image](https://user-images.githubusercontent.com/1094999/99698702-16efb500-2a5f-11eb-862f-9c2d6a260a1d.png)

**Comment by zurbergram** [comment]
To test
- upload weams csv > generate > publish
- search for "high school" or a search term only containing [excluded words](https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/config/settings.yml#L38)
  - results should contain institutions whose name is similar to excluded words entered
- search for "standford" or other words that are not excluded
  - results returned should be the same as on staging or prod

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/772

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-11-20 at 8.13.22 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/5ee3d04b-12d0-4e20-9ccc-a6a9abeba121)

---

![Screen Shot 2020-11-20 at 8.30.06 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/1838600a-b13b-4609-b9d9-d69ea96d69d9)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah The fix is on Staging and ready for review

**Comment by watersemma** [comment]
UX Review 1/2: Looks good to me!

**Comment by amyknox** [comment]
UX Review 2/2: LGTM! Thanks!

**Comment by delli-gatti-michael** [comment]
Closing this out
