### ISSUE TITLE
Build /requests GET endpoint

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1582]
## Story
As a backend developer, I want to be able to call a service to get a list of veterans' pending appointments so that the front end can support showing veterans a list of their existing appointment requests.

## AC
- [ ] Staging data recorded to cassettes
- [ ] `/requests` `GET` endpoint exist in vets-api
- [ ] Tests, specs, and swaggers exists for both endpoints

**Comment by saneshark** [comment]
It will still be one endpoint, but make separate requests based on `type` param.

It's code complete here: https://github.com/department-of-veterans-affairs/vets-api/pull/3476
