### ISSUE TITLE
Document Cypress Best Practices on VSP

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#15836]
## Product Outline
VSP Platform

## High Level User Story/ies
As a VFS team engineer, I need to be aware of best practices for the use of Cypress on the Veteran-facings Services Platform so I can create resilient and valuable tests.

## Hypothesis or Bet
If we create well-defined best practices for use of Cypress on VSP then VFS team engineers will create tests with better coverage with fewer support requests to VSP.

## OKR
O4: Get VFS teams to know, use, and love the DEPO Platform products and services.
KR4: By Jan 2021, an E2E testing workflow has been adopted by 50% of active VFS teams

### What must be true in order for you to consider this epic complete? 
- [x] **Final edits are made, and we've captured a list of the Github documentation that needs to be updated**
- [x] **Internal review/approval of new documentation**
- [x] **Pull Request submitted**
- [x] **Draft User Stories for Additional Features based on this documentation**

**Comment by holdenhinkle** [comment]
Documentation for the new Cypress environment variables and custom commands have been added. I'm waiting for the PR for the code updates to be approved and merged to master so I can update the links in this document to the new code then submit a PR for this updated documentation.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/write_documentation_for_new_cypress_viewport_env_vars_and_custom_command/platform/testing/end-to-end/cypress-best-practices-on-vsp.md#iterate-through-top-vagov-viewports

**Comment by holdenhinkle** [comment]
Updated docs to reflect recent changes in code.

Submitted PR - https://github.com/department-of-veterans-affairs/va.gov-team/pull/16653

Update the following sections to reflect recent code changes:

Cypress Custom Commands > Viewport Presets: cy.viewportPreset(preset, orientation, options)
Iterate Through Top VA.gov Viewports
Includes misc. edits.

**Comment by pjhill** [comment]
Resultant documentation is available [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-best-practices-on-vsp.md).
