### ISSUE TITLE
GIBCT Redesign: Research Cost of Living Tools

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15854]
As a developer, I need to research cost of living near the school functionality that can be incorporated into the comparison tool so that the comparison tool users know what living costs will be in the area.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. Documentation outlining cost of living near school tools and/or APIs that can be leveraged within the comparison tool.

    > Documentation includes, but is not limited to:
    > - Pros / Cons
    > - Pricing information
    > - ...

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
## Zillow
https://www.zillow.com/research/data/
http://files.zillowstatic.com/research/public_v2/zori/Zip_ZORI_AllHomesPlusMultifamily_SSA.csv
https://www.zillow.com/research/methodology-zori-repeat-rent-27092/

Zillow Observed Rent Index (ZORI): A smoothed measure of the typical observed market rate rent across a given region. ZORI is a repeat-rent index that is weighted to the rental housing stock to ensure representativeness across the entire market, not just those homes currently listed for-rent. The index is dollar-denominated by computing the mean of listed rents that fall into the 40th to 60th percentile range for all homes and apartments in a given region, which is once again weighted to reflect the rental housing stock. Details available in [ZORI methodology](https://www.zillow.com/research/methodology-zori-repeat-rent-27092/).



### Pros
Has rental data by zipcode by month in a CSV file
### Cons
It's from a private company, no API
### Price
Free

**Comment by zurbergram** [comment]
## Federal Housing Finance Agency
https://www.fhfa.gov/
https://www.fhfa.gov/DataTools/Downloads/Pages/House-Price-Index-Datasets.aspx

### Pros
Government Data

### Cons
Index instead of dollar amount

### Price
Free

**Comment by zurbergram** [comment]
## Consumer Price Index
https://www.bls.gov/cpi/

### Pros
government data

### Cons 
Index instead of dollar amount

### Price 
Free

**Comment by zurbergram** [comment]
## WolframAlpha APIs

https://products.wolframalpha.com/api/

### Pros 
Aggregates data, possibly in a easy to view addable piece to website

### Cons
Costs money
uses index instead of dollar amount
Unknowns
- couldn't test out the Summary Box feature
- Full Results API Explorer doesn't appear to return same information as going to https://www.wolframalpha.com/input/?i=cost+of+living+index+charleston+sc

**Comment by zurbergram** [comment]
## Numbeo

https://www.numbeo.com/common/api.jsp
https://www.numbeo.com/api/doc.jsp
Looks `GET /api/city_prices` and `GET /api/rankings_by_city_current` returns similar dataset to https://www.numbeo.com/cost-of-living/in/Charleston

### Pros
Provides a variety of values to display in either dollar amounts or indices

### Cons
- Costs money

### Price

https://www.numbeo.com/common/api.jsp

**Comment by zurbergram** [comment]
Indices are percentage change from an initial measurement which would require finding original value and calculating relevant information.

**Comment by desireeturner** [comment]
@zurbergram Can you add this research to the following GH folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/school-comparison-tool/redesign/research

**Comment by zurbergram** [comment]
> @zurbergram Can you add this research to the following GH folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/school-comparison-tool/redesign/research

@desireeturner https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/cost-of-living-tools/research.md
