### ISSUE TITLE
Generate blank transformers to reconcile R&S GraphQL changes

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#15861]
### Problem Statement 

Public Websites team recently released (11/4) significant changes to GraphQL with the release of their new Resources and Support (R&S) product. These changes have resulted in the CMS Export Build failing, therefore blocking our work on addressing discrepancies between GraphQL <> CMS Export Build. 

How might we unblock the build so that we can keep addressing discrepancies? 

### Details 

List of transformers that need to be created should be left on this ticket in description or comment. We will create the scaffolding of these transformers to unblock the build, and will work with Public Websites when we onboard them to this work next week on creating the full set of new needed transformers. 

### Acceptance Criteria
- [x] List of new transformers needed documented on this ticket
- [x] CMS Export Build finishes successfully

**Comment by theodur** [comment]
The list of transformers needed are:

`node-faq_multiple_qa`
`node-checklist`
`node-media_list_images`
`node-media_list_videos`
`node-q_a`
`node-step_by_step`
`node-support_resources_detail_page`

There may be more that come up. If so, I will update this comment.
