### ISSUE TITLE
[Bug] 526: Homelessness Question Submits Wrong Information

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#15866]
## Issue Description
Looks like we do not submit "other" and instead submit it as "fleeing" when we are submitting the homelessness questions down to EVSS.

![image](https://user-images.githubusercontent.com/53824125/98295696-22c37d80-1f6f-11eb-9e3c-aed2ed068159.png)

This story will correct it.  Follow-up is whether we need to add "fleeing" as an option because we missed it.  Or whether "fleeing" is part of the updated PDF.

## Acceptance Criteria
- [ ] Correct submission so "Other" shows up correctly.
- [x] Determine whether we need to add fleeing now - Note: I looked at previous (2018) version of the PDF. The question was in there.  We need a front-end and design ticket as well to make this fix.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Looks like it was an intentional choice.  If a veteran answers "yes" to the "do you need to quickly leave?" qestion.

<img width="633" alt="Screen Shot 2020-11-05 at 4 03 21 PM" src="https://user-images.githubusercontent.com/19188/98296521-0cbeb880-1f81-11eb-91a0-9790f8961c65.png">
