### ISSUE TITLE
Personal & Contact Info Page - Screen Reader is incorrectly reading the "VA.gov" text

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#15865]
## What Happened?
While using a screen reader, the first text group "...will be reflected on VA.gov" is being read as "...will be reflected on VA [dot] **governor**"

Android is reading VA.gov as "Vaw dot gov".

## Specs:
- iPhone XR
- With VoiceOver enabled
- User: marcy.nadeau@va.gov

- Android
- Talkback enabled
- User: patient998@id.me

## Steps to Reproduce
- Enable VoiceOver
- Select the first text group on the personal and contact information page 

## Desired Behavior
- When selected, the text should be read  as "...will be reflected on VA [dot] gov"

## Acceptance Criteria
- [ ] The screen reader will read out the correct text

## Bug Severity
- 4 - Low

## Linked Story
- Story #13890

## Screen Shot (s) and Additional Information
Showing the affected element
![Screen Reader - Personal Info .PNG](https://images.zenhubusercontent.com/5f7bb216620a259ab7e50d60/116c4299-95f5-4f04-ac62-fdace64e6f94)

**Comment by digitalken** [comment]
PASS 2/19/2021 - Android and iOS.  Closing.
