### ISSUE TITLE
[Bug] Event Page Breadcrumb issue - Missing "Home"

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#15864]
## What happened?

When the VAMC product implemented the removal of the _Home_ link from all VAMC system page breadcrumbs, there were a few bugs (like, it also it inadvertently removed it, temporarily, from Benefits hub pages). Those bugs were resolved -- but we now have a new issue on the [Outreach Materials ](https://www.va.gov/outreach-and-events/outreach-materials/)and [Outreach Event ](https://www.va.gov/outreach-and-events/events/)pages.

The breadcrumb design intent, as Mikki noted, is that Event and Event listing pages should not have Home links for VAMC products, but **should have them for the Outreach hub**.

Unfortunately, the current FE implementation of breadcrumbs does not currently allow for this kind of variance across products, for content types that are shared across products. The FE liquid templates for Outreach and Event List just removes the Home link altogether, it doesn’t check to see if it’s a VAMC related event or not.

This a FE template that is used for two products right now, Outreach Hub and VAMC. There are probably a couple of different ways to make that check, based on URL or something in the content layer, but CMS team can’t necessarily drive the solution here.  The CMS can provide any support where needed, especially if the FE solution involves something in the content layer.

<img width="948" alt="Screen Shot 2020-11-05 at 3 42 23 PM" src="https://user-images.githubusercontent.com/63107147/98294553-23174500-1f7e-11eb-8cd1-1665e9de8c7a.png">

## Specs:
- Device: All
- Browser: All
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/outreach-and-events/events/
- Test User _(if applicable)_: See missing "Home" link in breadcrumb

## Desired behavior
- Outreach and Event sub-pages should include a Home link in the breadcrumb

## Acceptance Criteria
- [ ] Home link is included in the breadcrumb

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
@zacharymorel could you review and provide an estimate on workflow.  Once estimated please review the 'Needs Grooming' label in support.  Thanks.

**Comment by zacharymorel** [comment]
@brianalloyd is this a dup of https://github.com/department-of-veterans-affairs/va.gov-team/issues/15880

**Comment by brianalloyd** [comment]
@johnhashva and @zacharymorel it looks like Facilities is going to handle this issue.  I know we have several tickets out but recommend we close this issue per Slack convo [here](https://dsva.slack.com/archives/CDHBKAL9W/p1604604224418000) and keep the facilities ticket open as they will action the breadcrumbs issue.  Let me know if that matches both your understandings per Slack convo.  Thanks.

**Comment by brianalloyd** [comment]
@

**Comment by johnhashva** [comment]
@zacharymorel + @brianalloyd this is a dup of #15880 -- and that one has far more helpful detail -- so I will close this one.

**Comment by brianalloyd** [comment]
Thanks @johnhashva. It looks like Facilities is going to action #15880 so I'm going to remove our developers from that ticket as well.  Thanks for the help.
