### ISSUE TITLE
Analytics Implementation - Direct Deposit Eligibility & Status

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#15874]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- In order to provide more comprehensive analytics to VFS teams around our veteran userbase and eligibility for products -- we would like to make improvements to our data layer to collect user attributes that give greater context to different levels of eligibility. 
- The value of this work would be immense in painting a clearer picture of how individual user demographics and attributes are impacting conversions across all products. 
- This work also aligns with enhancements available within GA4 of collecting user attributes

### Datalayer specification 

```javascript
recordEvent(
'event': 'profile-get-direct-deposit-retrieved', 
'direct-deposit-setup-eligible': true, //or false, 
'direct-deposit-setup-complete': true //or false,

) 
```

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@mshea0606 Here is the new ticket I created as a starting point to revamping our data layer to collect user attributes. 

We would certainly want to work with your team in understanding what user attributes and metadata is readily-available post authentication that serve as critical data points in making benefit eligibility decisions and inherently impact application usability. @lihanli and @erikphansen seem to be already getting the ball rolling here with their comments from #14631.

As a next immediate step, is their any documentation you could point us to today that outlines what post-authentication user data is available that might be of interest to us here? From there I'm thinking we could setup a meeting to discuss some of those data points with greater granularity. Your thoughts? 

cc: @Samara-Strauss @erikphansen @lihanli

**Comment by erikphansen** [comment]
I feel like I might be missing something regarding the scope of this ticket. My understanding is that @Samara-Strauss and @mshea0606 simply want to get a sense of what percentage of users who _can_ enroll in comp and pen direct deposit _have_ enrolled in comp and pen direct deposit. This ticket sounds like it covers a much larger scope.

We actually have no way of knowing if someone is eligible and/or enrolled in direct deposit post-authentication. That data is _not_ part of the normal user model. We _only_ know if someone's comp and pen direct deposit status or eligibility when they navigate to their Profile. That is when we make the call to get that info, and we _only_ make the call to get that info if they have the EVSS service available to them _and_ they are LOA3 and have 2FA set up.

**Comment by Samara-Strauss** [comment]
> My understanding is that @Samara-Strauss and @mshea0606 simply want to get a sense of what percentage of users who can enroll in comp and pen direct deposit have enrolled in comp and pen direct deposit. This ticket sounds like it covers a much larger scope.

 @erikphansen is right. The ultimate question we are trying to answer is this: of the people who receive comp & pen payments from the VA, how many people have direct deposit set up? However, to get true metrics on this, we'd have to work with the backend databases. We'll never be able to truly answer this just through VA.gov. **But**, what we can do is use VA.gov data to approximate some of these percentages.

@erikphansen gave a great summary [in this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14631#issuecomment-717404959) of how we might do this.

- We only show direct deposit in the profile **if** the backend tells us someone is eligible for it. Therefore, we could track for how many people the direct deposit section is loaded even if they do not click into that section of their profile.
- If we load the direct deposit section, people either have direct deposit information set up, or they don't. While we currently track whether someone **clicks** an Add (doesn't have dd set up) or Edit (already has dd info on file) link in the direct deposit section, simply also tracking whether someone sees an Add or Edit link would tell us how many people who are eligible for direct deposit in a given time period have direct deposit already set up or not.

If this is confusing, I'm happy to walk you through staging to show you how this works. If you want to see a staging user who already has direct deposit info set up, use 226. If you want to see a staging user who is eligible for direct deposit but does not have it set up, use 204. If you want to see a user who is not at all eligible for direct deposit, use 175.

**Comment by jonwehausen** [comment]
Hi team,

Thank you for all of this information, test users, and context, this was extremely helpful. Also thank you for your patience on the follow-up here. 

### Update / Existing State
After further investigation, I can confirm it is not feasible for us to surface precise accurate metrics to answer the eligibility & setup questions today. While we currently capture users who are LOA3, we don't currently have a consistent method to determine those folks who:
- **are eligible for direct deposit**
- **currently have currently setup**

Per your teams notes -- this makes sense, and yes we would like to propose a few adjustments following your information here. 

We have two existing events related to direct deposit correlating with the API calls: 
- ```'profile-get-direct-deposit-started'```
- ```'profile-get-direct-deposit-retrieved'```

### Proposed Adjustments
- Modify the ```'profile-get-direct-deposit-retrieved'``` event to include 2 variables: 1 for tracking eligibility when the profile loads, and 1 for tracking if direct deposit is currently setup. 
- Proposed new data layer for all `'profile-get-direct-deposit-retrieved'` events:
```javascript
'event': 'profile-get-direct-deposit-retrieved', 
'direct-deposit-setup-eligible': true, //or false, 
'direct-deposit-setup-complete': true //or false, 
```

While unfortunately we won't be able us to surface this insight historically, these changes will enable us to answer this question with great efficiency & precision moving forward. 

Let us know your thoughts here, and keep us posted on the status of implementing this...From there, we can go through our standard QA process and begin collecting this data. 

cc: @mshea0606 @Samara-Strauss @erikphansen

**Comment by Samara-Strauss** [comment]
@erikphansen the proposed adjustments make sense to me. Do they look good to you? If so, we can create a ticket for you to update the data layer.

**Comment by mshea0606** [comment]
@jonwehausen This sounds good to me.

**Comment by erikphansen** [comment]
Yes, making this adjustment is likely 1 (maybe 2 as I haven't actually looked at the code recently) points. The current score of 13 can be adjusted 😆

**Comment by mshea0606** [comment]
Ok great, I will go ahead and make a ticket

**Comment by mshea0606** [comment]
[FE] Direct Deposit Eligibility/Status Analytics Data Layer Changes #16603 has been created  @erikphansen @Samara-Strauss

**Comment by jonwehausen** [comment]
Thanks here folks! 

@erikphansen Yes, not quite a 13 anymore! 😄 That said, at some point we would like to have a brief chat with you and your team to learn more about additional metadata that is available post-auth we can collect in an effort to future-proof some potential user-related eligibility questions we may receive down the line. For now, we'll still with the addition of those two variables 😄

Thanks again here team.   

cc: @erikphansen @mshea0606 @Samara-Strauss

**Comment by erikphansen** [comment]
@jonwehausen If you are interested in generic info we know about all logged-in users, feel free to look at the response from the `GET user/` call that happens on every page load when signed in. That'll give you an idea of the kind of things we could easily send to GA.

**Comment by jonwehausen** [comment]
Thank you for that suggestion @erikphansen! Will do, appreciate it!

**Comment by jonwehausen** [comment]
@erikphansen & @mshea0606 was just curious if you could give a ballpark of when these changes will be implemented? Thanks again in advance here.

**Comment by erikphansen** [comment]
This change was merged in on Monday

https://github.com/department-of-veterans-affairs/vets-website/blob/6ef4de96084582873d8d7085840df5b6d4532409/src%2Fapplications%2Fpersonalization%2Fprofile%2Factions%2FpaymentInformation.js#L53-L64

**Comment by jonwehausen** [comment]
### QA Testing

Test Case  | Data Layer Screenshot | GTM Screenshot | Test Status
------------ | ------------- | ------------- | -------------
Already with direct deposit configured (test user 226) | ![image](https://user-images.githubusercontent.com/48527022/100924920-48c93880-34af-11eb-9bcf-af950ffdf362.png) | ![image](https://user-images.githubusercontent.com/48527022/100926602-b4aca080-34b1-11eb-86d9-82ecdab9d5f3.png) | ✔️ **PASS**
Eligible but does not have DD setup (test user 204) | ![image](https://user-images.githubusercontent.com/48527022/100926676-cee67e80-34b1-11eb-8b6b-5923f0d14a08.png) | ![image](https://user-images.githubusercontent.com/48527022/100926988-3c92aa80-34b2-11eb-89f8-b684eab03df2.png) | ✔️ **PASS**
User is not at all eligible (test user 175) | ![image](https://user-images.githubusercontent.com/48527022/100926742-e887c600-34b1-11eb-9089-99b4947194a2.png) | ![image](https://user-images.githubusercontent.com/48527022/100926831-0523fe00-34b2-11eb-8e1d-aa526371258c.png) | ✔️ **PASS**
Direct deposit failed | ![image](https://user-images.githubusercontent.com/48527022/100925977-baee4d00-34b0-11eb-95c0-4bf9d8725858.png) | ![image](https://user-images.githubusercontent.com/48527022/100927090-5e8c2d00-34b2-11eb-9fa8-e640ee767dd5.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
Thank you for your work here @erikphansen! QA Testing has passed. 

We are now collecting the eligibility & completion status with each retrieval event. 

We should let this data flow in over the coming days / weeks to reach an accurate breakdown of users who are eligibility and/or have direct deposit setup. 

cc: @mshea0606 @Samara-Strauss
