### ISSUE TITLE
Event breadcrumbs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15880]
## What happened?
This issue created to address the odd hyphenation occurring in breadcrumbs for events across VAMC and Outreach hub pages. The breadcrumb seems to be reflecting URL rather than the title of the page (H1).

**A related issue impacting the "Home" breadcrumb will be addressed in #16020.**

This code may also have some hard coding for VA Pittsburgh health care, which seems like a problem, but possibly a different problem.

See Slack thread for possible [solution](https://dsva.slack.com/archives/CDHBKAL9W/p1604604275418100?thread_ts=1604604224.418000&cid=CDHBKAL9W)

## Steps to Reproduce
- URL: (example) https://www.va.gov/outreach-and-events/events/vets-for-vets-celebration-at-the-star-theatre/
- [CMS URL](https://prod.cms.va.gov/outreach-and-events/events/vets-for-vets-celebration-at-the-star-theatre)

Example: https://www.va.gov/outreach-and-events/events/vets-for-vets-celebration-at-the-star-theatre/
Expected breadcrumb: Home > Outreach and events > Outreach events > Veterans Film Festival
Existing breadcrumb: Outreach **and-events**>  Events > **Vets for-vets-celebration-at-the-star-theatre** 

## Desired behavior
The breadcrumb should be driven by the title of the page (H1), not the last string in the URL alias (which are often related to each other but not necessarily). 

[Per @mnorthuis via slack: ](https://dsva.slack.com/archives/CDHBKAL9W/p1604605413420500?thread_ts=1604604224.418000&cid=CDHBKAL9W)

## Acceptance Criteria
- [ ] Breadcrumbs on Events pages in VAMC and Outreach Hub should reflect the H1 title (no hyphens, unless inherent in the name) 
**A related issue impacting the "Home" breadcrumb will be addressed in #16020.**

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
@ncksllvn @kelsonic @zacharymorel  could one of you review this ticket and provide an estimate, if this is something small and timely we might have some room in this sprint to action.

**Comment by jenniferlee-dsva** [comment]
Adding a screenshot showing bug in outreach hub: 
![image](https://user-images.githubusercontent.com/43381063/98380354-74731300-2016-11eb-9246-9c6ae79f9e2f.png)

**Comment by jenniferlee-dsva** [comment]
Edited og ticket desc with Mikki's Slack correction: 

[Per @mnorthuis via slack: ](https://dsva.slack.com/archives/CDHBKAL9W/p1604605413420500?thread_ts=1604604224.418000&cid=CDHBKAL9W)

The breadcrumb for the page Jen has as an example should be:
`Home` > `Outreach and events` >  `Outreach events `> `"Vets for vets" celebration at the star theatre `

**Comment by zacharymorel** [comment]
What is the source of truth for breadcrumbs? 
Are the breadcrumbs should be dynamically generated off of the url + slug?

**Comment by jenniferlee-dsva** [comment]
@zacharymorel  - ^. Not the url. It is almost always the page H1. Sadly, it is not always the H1 - because the benefit hubs' have a much more manual, bespoke breadcrumbing, due to those pages being created prior to VA.gov being in a CMS.

That said, in general -- for the pages/products that were created post-CMS, the breadcrumbs pull from the page H1.

**Comment by zacharymorel** [comment]
Is https://github.com/department-of-veterans-affairs/va.gov-team/issues/15864 a dup?

**Comment by brianalloyd** [comment]
@mmiddaugh it looks like facilities team ill handle this issue per the [Slack Convo](https://dsva.slack.com/archives/CDHBKAL9W/p1604604224418000) so I'm going to remove PW labels and assignees in support.  Please reach out if you need anything else in support.

**Comment by brangi** [comment]
Possible fix https://github.com/department-of-veterans-affairs/vets-website/pull/15237

**Comment by mmiddaugh** [comment]
@kevwalsh, FYI
Gibran has resolved the hyphenation and breadcrumb name of the events themselves but the hyphen in the main breadcrumb (**Outreach and-events**) looks to be text coming from CMS. Are you able to take that part?
![image](https://user-images.githubusercontent.com/55411834/101656827-62fb9d00-3a00-11eb-8feb-0ed3fc4dae9b.png)

**Comment by mmiddaugh** [comment]
Moved Outreach hub breadcrumb into new issue
