### ISSUE TITLE
GIDS: Remove SmarterCSV Gem

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15886]
As a developer, I need to remove the SmarterCSV Gem from the GIDS codebase because it is no longer being used.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The SmarterCSV Gem is no longer included in the GIDS code base.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/gibct-data-service/767

**Comment by sonntag-adam** [comment]
In staging. Closing story.
