### ISSUE TITLE
GIDS: Auto detect if valid/real Excel file

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15885]
As a dev, I need to auto-detect the validity of uploaded excel files so that the handling of the excel files is no longer hard-coded.

## Assumptions:
1. N/A

## Acceptance Criteria
1. A manually created Accreditation excel file can be uploaded to GIDS without error.
2. The Department of Education Accreditation excel file can be uploaded to GIDS without error.

### Technical Notes:
Currently this is done by a setting within code and can only be changed if initial Accreditation upload fails, This https://github.com/department-of-veterans-affairs/gibct-data-service/pull/759 would add code that checks for what determines if the Excel file is valid/real and determine how to process file based on that.

## Supporting Artifacts:
1. https://ope.ed.gov/dapip/#/download-data-files

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/759

**Comment by sonntag-adam** [comment]
Manually created file 
![Screen Shot 2020-11-09 at 7.53.32 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6b027e82-9893-44ea-aaaf-d467855e653a)
##
DAPIP file
![Screen Shot 2020-11-09 at 7.57.59 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5aa1d573-022a-49d7-8f66-693d0c327f3d)

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
