### ISSUE TITLE
Connect to CARMA via review instance

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#15881]
As the Caregiver program,
I want to be able to run end-to-end tests with code still in a review instance
So that I can test new functionality without deploying to Staging and therefore Production.

See: https://dsva.slack.com/archives/CBU0KDSB1/p1603898242158500

**Comment by kevinmirc** [comment]
Blocked by: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15486#issuecomment-745419637

**Comment by kevinmirc** [comment]
Today I ssh'd into a RI. I tried connecting to the fwdproxy URL that was provided, but it would not resolve.

These were the steps I used to test: 
```rb
# 1 - Update Settings
# 
# $ sudo nano config/settings.local.yml
# (update URL to the fwdproxy URL provided)
# $ cd ~/vets-api; docker-compose -f docker-compose.review.yml restart vets-api

# 2- Check client has correct url
# 
# $ cd ~/vets-api; docker-compose -f docker-compose.review.yml exec vets-api bundle exec rails c
# irb> require_relative 'lib/carma/client/client.rb'
# irb> CARMA::Client::Client::SALESFORCE_INSTANCE_URL
# (ensure correct url is set)

# 3- Make request
# 
# irb> client = CARMA::Client::Client.new
# irb> client.create_submission({})
```
The request just hung. I then went to the cmd line in the RI to ping the host. I was able to ping staging salesforce directly but the fwdproxy URL did not resolve.

```bash
$ ping [SALESFORCE STAGING URL]
# ...
5 packets transmitted, 4 received, 20% packet loss, time 4006ms
rtt min/avg/max/mdev = 69.069/69.190/69.449/0.356 ms
```

```bash
$ ping [FWD PROXY URL]
# ...
12 packets transmitted, 0 received, 100% packet loss, time 11262ms
```

**Comment by kevinmirc** [comment]
Blocked: Waiting to be advised by Platform on the above issue.

**Comment by kevinmirc** [comment]
Spun up a RI and was able to confirm that we can connect now to CARMA from RI.

**Comment by ala-yna** [comment]
That's so exciting, thanks Kevin!
