### ISSUE TITLE
FacilitiesQuery module should be in the models directory

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#15889]
`FacilitiesQuery` creates a module space for the `models/facilties_query` directory.  It is currently inside that directory, but to match up with zeitwerk naming conventions it should be moved out to the models directory.  Additionally, we should remove the `requires_relative` from `app/models/base_facility.rb`.

Example commits:
https://github.com/department-of-veterans-affairs/vets-api/pull/5225/commits/95140a12a091ed82ecfccdb202efbe3f84a433f3
https://github.com/department-of-veterans-affairs/vets-api/pull/5225/commits/7f8fb97c55a576a8a262c97fe3bbaf3a33466229

**Comment by ericboehs** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-api/pull/5299
