### ISSUE TITLE
[Development] 526/BDD: Conditionally Show the Rated Disabilities Information

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#15897]
## Issue Description
While doing BDD, our service member was shown the rated disabilities information.  For both 526 and BDD, this information does not apply unless they have rated disabilities.  It is more likely for BDD that they do NOT have rated disabilities but it's possible.  Therefore, we likely need to actually check for rated disabilities when determining what the display content looks like.

![image](https://user-images.githubusercontent.com/53824125/98384760-679cf200-200b-11eb-9b66-d6f04239e0d3.png)
 
That being said, it does say "if you have any", so the value-add to making this change may not be high versus the implementation difficulty.  We have not done usability to determine whether this causes confusion since it is just an informational page.

## Acceptance Criteria
- [ ] If we decide to move forward with this, conditionally show the rated disabilities bullet only when relevant
- [ ] Remove the ", if you have any" from the bullet since we will know

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
I will consult with design on whether to hide the rated message or simply hide the page altogether.

**Comment by ndsprinkle** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15330

The linked PR has been merged after meeting with Kevin. The disabilities orientation page will now conditionally show only when both increase and new are selected. The supporting evidence orientation page will now conditionally show the appropriate message(s) depending on if increase and/or new are selected.
