### ISSUE TITLE
don't autoload erb files for education_forms that are manually loaded

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#15891]
`app/workers/education_form/templates/1990-disclosure` contains files names `_CHXX` for part of building notifications related to education_forms.  These are all accessed in code directly by filename, but the names of these files choke zeitwerk.  Adding  `Rails.autoloaders.main.ignore(Rails.root.join('app', 'workers', 'education_form', 'templates', '1990-disclosure'))` to `config/application.rb` resolves the zeitwerk loading issue.

Example commit:
https://github.com/department-of-veterans-affairs/vets-api/pull/5225/commits/c83fa3af688e6a83ffd41bca88c6f39ed10d60a1

**Comment by LindseySaari** [comment]
It was discovered that this issue needs to go out with the switch over to Zeitwerk mode change. Specs fail with 'undefined method `ignore' for nil:NilClass' in the application.rb when in classic mode.

In the original PR, Zeitwerk mode in application.rb is turned on along with the autoloading ignore for the education_form files here:
https://github.com/department-of-veterans-affairs/vets-api/pull/5225/files#diff-c1fd91cb1911a0512578b99f657554526f3e1421decdb9e908712beab57e10f9L29

A branch for the work was started here: https://github.com/department-of-veterans-affairs/vets-api/tree/15891-dont-autoload-edu-erbs

**Comment by erluti** [comment]
Will be resolved with https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10641
