### ISSUE TITLE
name AppsSwagger after it's filename

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#15899]
`modules/apps_api/app/swagger/apps_api/v0/apps/apps_swagger.rb` is for the class `App`.  This should be renamed to `AppsSwagger` and use the namespace `V0` so that the classname matches the filename.  The class is used in `modules/apps_api/app/controllers/apps_api/docs/v0/api_controller.rb`.

Example commits:
https://github.com/department-of-veterans-affairs/vets-api/pull/5225/commits/dd7d310b61133533417e9987bb11eb93fc48c77f
https://github.com/department-of-veterans-affairs/vets-api/pull/5225/commits/f2aab36074296cfd06192f1c0cd364b67ef340aa
https://github.com/department-of-veterans-affairs/vets-api/pull/5225/commits/d06ad25ddd81ae3ffeb607f2ddb068783426b323

**Comment by erluti** [comment]
Check to make sure if className matters for swagger doc rendering

**Comment by ericboehs** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-api/pull/5301
