### ISSUE TITLE
don't use acronym for patient_generated_data_service

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#15893]
The HealthQuest module has a PGDService, and this acronym seems only useful to this service.  So the acronym should be expanded to "Patient Generated Data" rather than including an inflection.

Example Commit:
https://github.com/department-of-veterans-affairs/vets-api/pull/5225/commits/bd871c4a451553f6e5d4a7463c51e038736382a1

**Comment by ericboehs** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-api/pull/5297
