### ISSUE TITLE
[Discovery] Investigate IE-based infrastructure for e2e testing

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#159]
## Description

As a VFS developer, I want to know that my automated browser tests are also verifying my application works correctly in IE.
As a VSP platform developer, I want to be sure that changes to the platform don't break VFS in IE.

## AC

- [ ] Research what changes to our test infrastructure would be required to run browser tests in IE
- [ ] Estimate difficulty+time proposed changes would take

**Comment by U-DON** [comment]
There is an existing integration with Nightwatch and Sauce Labs that allows developers to locally run E2E tests against Sauce VMs on any browser, including IE. The following documentation still seems up to date:

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/9fd4d5da296a4570fd10e7a6643c8418020c97c0/Practice%20Areas/QA/Cross-Platform%20Testing/cross-platform-testing-plan.md

Sauce Labs also seem to offer other nice features that we have not leveraged, such as video playback and screenshots, which would be helpful in debugging.

It appears that tests can take a very long time depending on how many assets need to be downloaded, especially through the proxy. An example is the basic Facility Locator E2E test.

**Comment by U-DON** [comment]
The output of this work is this [document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Tools%20and%20Improvements/Notes/%5B2019-06-11%5D%20State%20of%20E2E%20Testing%20on%20VA.gov.md) and this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10300) where I settled on TestCafe with BrowserStack as our E2E cross-browser testing solution.
