### ISSUE TITLE
Facilities Team Hackathon

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15906]
## Goals
Empower the team to be inspired and creative about our work 
Generate new ideas/solutions (to address issues or for new features)

## How
Members of the Facilities team will work on something of their own volition/prompted by their own ideas within a set time period and prompt that is relatable for all disciplines

## Rules of engagement
- There is no obligation to prioritize this work or a particular solution
- This is exploratory brainstorming - does not need to be a viable solution
- Partner up or work individually
- Time boxed

## Tasks
1. Choose a problem statement you want to explore solutions to
- How might we reimagine how Veterans learn/get information about VA benefits and services?
- If you could change/add one thing for our Product Suite (Facility Locator/VAMC/Vet Centers), what would it be?
2. Explore possible solutions (ie: experimentation, discovery, sketching, brainstorming)

## Output
- There is no obligation to create "working" code or a polished design, especially given the time box for this activity. 
- Team members will give short (~5-10 min) presentation of their idea to the team following the Hackathon activity. The presentation should include the following -
  - Description of the problem to be solved by this idea
  - Ideas on how to measure success for this work
  - Low-fi artifact, such as Idea sketch/description, discovery findings, Google Drawings sketch, UXPin or Google Slides
  - Include rejected ideas, iterations, etc. 
- Artifacts to be housed in [Github hackathon folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/facility-locator/hackathon-2020.md)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
[ba3ed474-79a2-4bad-bb21-a5f04cf89402-original.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5555115/ba3ed474-79a2-4bad-bb21-a5f04cf89402-original.pdf)

**Comment by brangi** [comment]
Directions - hackathon day - https://github.com/department-of-veterans-affairs/vets-website/pull/14967

**Comment by lildziner** [comment]
**When searching for on VA.gov**

**Problem:** VA.gov often presents more information than a user needs and before they need it. This creates visual problems, information overload and congnitive processing issues, e.g. Covid allerts causing wayfinding obstacles.

- How might reduce cognitive load for our users?
- How might we help focus users to accomplish a task with less noise?

[UXPin screens](https://preview.uxpin.com/c300973e45a11d90a87d54bc788f6461da080480#/pages/134295035/simulate/sitemap?mode=i)
