### ISSUE TITLE
Error Message for Invalid Routing Number

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#15905]
## User Story
As a user, if I enter a routing number that meets the character requirements but is invalid, I want to see a message saying that my routing number was invalid. 

## Tasks
- [x] Review Profile 2.0 Product Guide to see how they handle errors
- [x] Design UI using Mobile Alert common component 

## Invision Link
https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/439369172/preview?scrollOffset=2878

**Comment by bridgethapner** [comment]
@msmanak - just shared the Profile 2.0 Product Guide with you, should be in your email.

**Comment by srmyers17** [comment]
- discovery needed
- @jperk51 to weigh in on whether this is possible on the backend.

**Comment by msmanak** [comment]
![Error-State-Direct-Deposit.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/140cb4bd-1e49-4fbc-a3dc-23ec4e5c826e)

Draft for @bridgethapner review

Text:
(header) "We couldn't update your bank information"
(body) "We couldn't find a bank linked to this routing number. Please check your bank's 9-digit routing number and enter again."

**Comment by bridgethapner** [comment]
@msmanak This looks great! Looking at this, I'm realizing I think it would be ideal for the information the user entered to remain populated in this state so they can revise it rather than having to enter it all again. What do you think? If that sounds good to you, can you update the wireframe to show the fields filled in?

**Comment by msmanak** [comment]
common component:
