### ISSUE TITLE
VFS Support: Create (if necessary) a redirect for /beta-enrollment/all-claims/

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1590]
https://www.va.gov/beta-enrollment/all-claims/ is no longer necessary and should be removed. However, we may need a redirect in its place.

I think this page impact is very minimal, but raising this because we do have a redirect in place for https://www.va.gov/beta-enrollment/claim-increase.

**Comment by mnorthuis** [comment]
@AZSchneider Can you confirm if this beta page still needs to be live?

**Comment by AZSchneider** [comment]
@mnorthuis this page does not need to be live any longer.

**Comment by mnorthuis** [comment]
Thanks @AZSchneider.

@ncksllvn I will get info together for an official redirect request and assign over when ready.  Stay tuned...

**Comment by mnorthuis** [comment]
Redirect request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5626

Closing this issue.
