### ISSUE TITLE
Veteran's Crisis Line Button takes up entire screen on small format phone when largest font is used, can't see anything else on home page.

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#15912]
_NOTE: Possible fix will be covered in [unfix story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16132)_

## What happened?
I switched to the largest font on an iPhone SE and the Veteran's Crisis Line banner button takes up the entire usable screen on the home page and I'm unable to see anything else on the page.  

The problem is more evident with iPhones because they seem to have a larger maximum font than the Androids.

## Specs:
- Device: iPhone SE
- User:  Any user
- Font increased to maximum on the device.

## Steps to Reproduce
- Increase font to maximum size.
- Navigate to home page.

## Desired behavior
The button will scroll up as the user scrolls down the page (allowing the user to view the rest of the page content)

## Acceptance Criteria

- [ ] The button will scroll with the page

## Bug Severity
- 3 Moderate

## Screen shot(s) and additional information

- iOS seems to have a larger maximum font size than Androids.

![vetCrisisLineIphoneSE.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/3b83b33f-8fa7-4448-97c6-93c63f6a0185)

![galaxyS7homeLargeFont.jpg](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/bc2941f3-4bc5-44aa-91cd-faa7506dde6b)

**Comment by esther-k** [comment]
@bridgethapner 

I wanted to get your thoughts on the expected outcome for the crisis line banner during resizing. The outcomes I've looked into are:

1. Un-fix the banner always (make it not sticky)
2. [Use media queries to un-fix the banner](https://www.w3.org/WAI/WCAG21/Techniques/css/C34.html) (set a min-height so it get's fixed or un-fixed depending on the available space)

**Comment by bridgethapner** [comment]
Hi @esther-k - your suggested solve #2 sounds good here.

**Comment by esther-k** [comment]
**11/23**

Pass on iOS and Android. The Veterans Crisis line button is now scrollable with the page and other content can be accessed
