### ISSUE TITLE
Access for Samuel Suddath

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#15914]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Samuel Suddath, ssuddath@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Search and Discovery; Role: Frontend Engineer; Employer: GovernmentCIO
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoNOWxWbI1Zrw9JKmSyjymti0tPzk7aGWbEU51S9dIsk7adpGbphkOjnnuGbFZt7RlPbHFrkD3tArIOVEr/488bNLimDtgmUyZe0tno4WOUmGro1WGWAUKXnjY8sFhFP7dAUhhCgxp92znze+s+U801j4IofacAQp1z7c4uLCiRiGzQkrq0Gq6hg+Et15OVSw95HieJ1VN4Aajo6iGyjpE3fEq/2ra1nUhxQ4xS7DwDPOxu5XH1f3ydm2vZB5hbsTF4zYrh1ke9I3bn4atnyDcbw/llBk3INaRgCsvvEMgHjxgXdv6deC3aF2YTsHV8Wro843ueom+dYAdMDItZBGlMfwKvMpThUcYuHHA7OuIasHW8Vr3oRfBspIFrjJcBIvh/1kCLpfKI9eKnwI7XASRxdpe04RE1VoAIf7RnPdE4iK71fBODpvBcIxgLAUJQHsQ13zZaUa6LRI7Wg1Ne0uSU33NE7X4g6Dgk1aWAfEut2V/9jQAD7wi3QFygt49EF0= samsuddath@Sams-MacBook-Pro.local
```

- [Grant AWS Console access?]
  > NO

- [Grant SOCKS access]
 > YES

**Comment by srsuddath** [comment]
tag @https://github.com/orgs/department-of-veterans-affairs/teams/vsp-operations

**Comment by srsuddath** [comment]
tag: @department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@srsuddath you should be able to connect so socks proxy now. Reach out in slack if you have any issues.
