### ISSUE TITLE
Checklist article - CMS ax defect - learning center

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15915]
## Checklist article - CMS ax defect - learning center

On this example node: http://preview-prod.vfs.va.gov/preview?nodeId=9544

![image](https://user-images.githubusercontent.com/43381063/98411022-4eb03300-2043-11eb-8792-dffa8eaa2458.png)

1/ The section header ("Checklist" in the example) is extraneous `<-- this appears to be a CMS defect.`
2/ The optional section header is represented by the text below "Checklist." The author should be able to specify what the text of this section header is, and it should appear as an H2.  <-- ~not sure if this is FE and CMS~ `we confirmed this one is a FE update`

See example content fields in the CMS: 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/dd20c024-bc24-4d7a-9fb5-23588fe4e7b6)
![image](https://user-images.githubusercontent.com/43381063/98411419-ffb6cd80-2043-11eb-8fa1-f5d96e21e824.png)

Also, the FE appears to not be displaying the optional section blurb text that's in the CMS. 

![image](https://user-images.githubusercontent.com/43381063/98411562-44daff80-2044-11eb-85e9-558121a9b5f9.png)

**Comment by jenniferlee-dsva** [comment]
The correct content fields are:

Optional - Checklist section header <display as H2>
Optional - Checklist section blurb 
Checklist labels <no limit on how many; regular body copy text; up to 300 characters with spaces>

^ Above group can be repeated to create checklist groups chunked up into sections. 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/f786e525-79db-4f87-a031-4d4ec83ad537)

**Comment by oksana-c** [comment]
CMS functionality is tracked in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3445

**Comment by oksana-c** [comment]
@brianalloyd @jenniferlee-dsva 
the corresponding CMS issue has been resolved and closed, so closing this one also. 
department-of-veterans-affairs/va.gov-cms#3445
