### ISSUE TITLE
Build 'community care' request & appointment detail page mocks

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1592]
## Story
As a front end developer, I need to understand the data and UI to show in the appointment list and details views for pending CC appointments.

## AC
- [ ] Mocks exist for  CC requests list & details views (to be attached in this ticket)

The existing pending list doesn't differentiate between VA & CC appointments:
<img width="725" alt="Screen Shot 2019-10-16 at 10 03 11 PM" src="https://user-images.githubusercontent.com/24251447/66974462-c68a7480-f060-11e9-9606-ca7cef0e5466.png">

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/67398080-2957a080-f578-11e9-9396-20b794a7feb0.png)

**Comment by markgreenburg** [comment]
Dupe of #2224 
But also worth noting that this isn't needed because separate `detail` pages don't exist any longer.
