### ISSUE TITLE
School Ratings: Analytics

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#15922]
Review KPIs to identify priorities for ratings 
Draft metrics to track. 
Review w UX team, XF team to validate 
Review with EDU for input

**Comment by amyknox** [comment]
KPI noted on product outline: Number of ratings. 

Other KPIs that address our work specifically may be helpful. 

Thinking we'll want analytics to track 
1. Using jumplink to view ratings (aggregate profile page activity)
2. Click accordion to open & view details about ratings (aggregate by category)
3. Scroll depth to scroll past "About ratings" content

**Comment by amyknox** [comment]
Issue submitted to DEPO insights: [16164](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16164)
