### ISSUE TITLE
[Design] Profile 2.0 bug fix: Add 2FA prompt for when someone is LOA3 but not 2FA and is eligible for direct deposit

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#15923]
## Background

In profile 1.0, if a direct deposit-eligible user was LOA3 but did not have 2FA set up (a rare use case that can happen if people sign on through DS Logon or MHV), we showed the direct deposit section of the profile, but we showed a prompt that told them they had to add 2FA before they could update their information.

Unfortunately, this state somehow got missed in the profile 2.0 transition, so we need a mockup for this state so we can add this functionality back in.

Here is what this looked like (I believe this was the exact copy) in profile 1.0:

![Direct deposit_Gated for 2FA.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/4e5743af-e7b7-4728-86fe-583f76b8d492)

## Tasks

- [ ] Create mockup of 2FA state for direct deposit section for profile 2.0.

**Comment by tressaellen** [comment]
Here is the mock for this:

![DD 2FA.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/54f75199-8689-4af5-abe1-19808432375f)

**Comment by Samara-Strauss** [comment]
FE ticket in #16255
