### ISSUE TITLE
CT Redesign: Data Inventory	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#15928]
"Inventory CT data sources 
Document relationships of data populating CT 
Identify pain points 
Explore under / non-utilized data

**Comment by amyknox** [comment]
Data Providers spreadsheet is [accessible on Booz Sharepoint](https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/PI%20Planning%20%26%20Prod%20Release/PI8%20[20201005%20-%2020210115]/Data%20Provider%20List.xlsx?d=w6d8f73b72c9c49ea8705fc5657577942&csf=1&web=1&e=SSywyP)
