### ISSUE TITLE
Frontend keepalive request should do something with the response body

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#15939]
When we make an SSOe keepalive request on the frontend, the response has a body but we don't currently read it because all of the relevant info is in the headers. The only known impact of this is that chrome dev tools reports the request as not finished yet in the timing tab:
![Screen Shot 2020-11-06 at 2.37.47 PM.png](https://images.zenhubusercontent.com/59ca8f33b0222d5de4793559/b97f4bfa-384d-45bd-8ddc-b9843e922c7a)

But it's also possible this is holding some sort of connection handle open. 

The keepalive code should either call `response.text()` or `response.json()` to read the request body, or it should use a `HEAD` request to make it explicit that we are only interested in the headers. TBD whether the keepalive endpoint will honor a HEAD request, and whether all browsers support HEAD in a fetch request, so up to assignee to test this out. Just reading the response body and dumping it on the floor is probably the safer bet but will make the HTTP gods cry.

**Comment by ericbuckley** [comment]
I just ran a test in FF with the following JS code and the `HEAD` request worked as expected.
```
fetch('https://sqa.eauth.va.gov/keepalive', {
    method: 'HEAD',
    credentials: 'include',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    }
  })
  .then(function(response) {
    console.log(response.headers.get('session-alive'));
    console.log(response.headers.get('session-timeout'));
  })
```
