### ISSUE TITLE
Homepage - CC request card provider name spacing

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15944]
## Steps to Reproduce
1. Go to https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Sign in with Judy Morrison account
3. Scroll down through the cancelled and pending community care request cards

## Actual Behavior
When the Practice Name doesn't have a value, an empty row displays in the preferred provider information.
![15944 bug.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/28b67c6e-4066-4d82-a302-5b54c9420c33)

## Desired Behavior
If an optional field does not have a value, do not show placeholder row.

## Acceptance Criteria
- [ ] If preferred provider doesn't have a practice name value, provider first and last name displays immediately below Preferred provider header [Example](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/aaa621fe-f312-488a-bd5a-f1532438879f)

- [ ] If preferred provider has a practice name value, display it between Preferred provider header and provider first and last name [Example](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/bc07409b-7745-4476-9599-6fb65103cb6d)

- [ ] No impact to confirmed community care card

**Comment by laurenernest** [comment]
@outerpress Spacing look good on these cards?
![Screen Shot 2020-12-04 at 4 05 40 PM](https://user-images.githubusercontent.com/72046525/101226880-bbbae680-364a-11eb-8d68-f4a5af07c696.jpg)

**Comment by outerpress** [comment]
Yep! Looks good to me.
