### ISSUE TITLE
Pickers in Address fields for iOS take input as soon as user lifts finger from picker rather than waiting for user to tap 'done'

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#15942]
## What happened?
After navigating to an address edit/input page, I clicked on a field that uses a picker (Country, State).  The picker comes up fine but as soon as user pulls finger away from picker, it takes whatever value is in the picker and puts it in the field.  So if I'm trying to scroll past the first view and remove my finger, whatever value that is goes into the field.  I have to tap back in the field again for another scroll.  And over and over, if I need to go that far.

## Specs:
- iPhone SE, any user.
- Testflight build 1.0.2 (6). (Was not happening in build 1.0.1)

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
Picker doesn't accept input until user taps on 'done'.  Don't enter input as soon as user picks up finger from picker.

## Acceptance Criteria
Input isn't accepted until user is ready and taps 'done'.

## Bug Severity
- 3 moderate

## Screen shot(s) and additional information
None - would like to include a short vid of the screen but this won't accept video files.

**Comment by bessgreen** [comment]
Hi @lexicalninja & @srmyers17, looping you in on this ticket. 

@keli13 looked into this bug and found that it’s a [known issue](https://github.com/lawnstarter/react-native-picker-select/issues/346) with the library we’re using for the picker. This gives us two options:

1. Wait for a [fix](https://github.com/lawnstarter/react-native-picker-select/pull/368) to be merged in for this library (Considerations: no guarantees that this will be fixed and merged into the library, and by when)
2. Pull in a new library for this feature. (Considerations: DF dev time, priority)

Thoughts on how we should proceed here?

**Comment by lexicalninja** [comment]
The owner released a fix about 45 minutes ago.

@keli13 please make a new PR to update this lib, run it on devices to see if it is fixed and then run all the unit tests to make sure there are no issues. 

Let me know if you have problems and I can help out.

**Comment by esther-k** [comment]
**11/19** 

Pass on iOS (issue only affected iOS). Input for pickers is only taken once 'done' is selected
