### ISSUE TITLE
Discovery: Telehealth and Express Care

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1594]
This is a placeholder ticket to think through the appointment flows and requirements (e.g., video links) we'll have to understand when we integrate telehealth and express care appointment types.

**Comment by lenaecb** [comment]
@markgreenburg - we've got 2 discovery issues (epics) for express care and telehealth. 

Is this still part of MVP? If not, I'll combine those issues and push this issue into the 'post MVP' bucket for more discovery and prioritizing post MVP launch. 

Other issues relating to this:
#1645

**Comment by markgreenburg** [comment]
Telehealth is part of MVP (in terms of being able to request a video visit), Express Care is not.
