### ISSUE TITLE
Full Accessibility & 508 Office Audit [Orchid - VA Form 0873 (Ask a Question)]

### ISSUE THREAD

**Issue by anitadewitt-va** [department-of-veterans-affairs/va.gov-team#15947]
## Steps to complete the Full Accessibility & 508 Audit: 
- [ ] Product Manager: create issue and fill in feature name in the title and other bolded information appropriately
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts
- We are requesting a staging accessibility audit for **VA Form 0873 (Ask a Question)** form at **https://staging.va.gov/ask-a-question**
- Documentation of accessibility checks completed can be found in [TestRail] (https://dsvavsp.testrail.io/index.php?/runs/view/746&group_by=cases:section_id&group_order=asc)
- **There are no known issues.** 

## Additional Notes
As part of this review, VSP will send your product to VA's 508 office for approval (as applicable)

**Comment by anitadewitt-va** [comment]
@shiragoodman This was intended to be a staging review. Please let me know if you would like me to create this card again with the correct issue template.

**Comment by shiragoodman** [comment]
thanks @anitadewitt-va . No worries, it's fine as-is and you do not need to change a thing. For future reference, basic rule of thumb is pre-launch=staging, post-launch=508 audit. :)

**Comment by anitadewitt-va** [comment]
@shiragoodman thanks for letting me know. Do you have an estimate on when this may be picked up?

**Comment by shiragoodman** [comment]
@anitadewitt-va our accessibility specialists (@1Copenut and @noahgelman) are both out of office this week. I will have to discuss availability with them next week when they return.

**Comment by anitadewitt-va** [comment]
Just wanted to call out that our form is currently in progress and that we will need to request a staging audit again around late February/early March. If it doesn't make sense to do both audits, we can push this one back. Just wanted to be mindful of everyone's capacity. 

Thank you

**Comment by shiragoodman** [comment]
hi @anitadewitt-va . In reviewing previous comments, I think now it might make sense to close this ticket and reopen it as a [Staging Review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+Shiragoodman&labels=vsp-product-support%2C+collaboration-cycle%2C+staging-review%2C+collab-cycle-review&template=staging-review.md&title=Staging+Review+%5BTeam+Name+-+Feature+Name%5D) when your team is ready. Thank you for letting us know!

**Comment by anitadewitt-va** [comment]
Will do.
