### ISSUE TITLE
CC review page address spacing

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15943]
## Steps to Reproduce
1. Go to https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment
2. Sign in with Judy Morrison account
3. Select primary care
4. Select community care
5. Choose any date/time
6. Select "yes" to add a preferred provider
7. Fill out only the required form fields (omit practice name and mailing address line 2)
8. Continue request through to the review page

## Actual Behavior
When mailing address line 2 field is not filled out, an empty row displays in the preferred provider address.
https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/3e443619-6794-43fa-a233-0118b8c1be4d

## Desired Behavior
If an optional field does not have a value, do not show placeholder row (similar to practice name)

## Acceptance Criteria
- [ ] If preferred provider doesn't have a mailing address line 2 value, city/state/zip line displays immediately below mailing address line 1
- [ ] If preferred provider has a mailing address line 2 value, display it between mailing address line 1 and city/state/zip

**Comment by outerpress** [comment]
@laurenernest The [spacing issue I saw](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/3e443619-6794-43fa-a233-0118b8c1be4d) that led to this one was from leaving Mailing Address Line 2 blank. 

So I don't know if there's value in adding specs for this, we just need to not be adding a blank space on the review page address if mail 2 is blank.

Though that issue might resolve itself once we switch over to the provider list. Something to validate, either way.

**Comment by jenniemc** [comment]
@laurenernest, the CC preferred provider review page is missing the display of provider's phone number which is a required field. Would you like to include the phone number underneath provider name just like it currently does on the confirmation page? It would look something like

![image](https://user-images.githubusercontent.com/54327023/100748387-42ed2d80-33b1-11eb-893f-eb81ffee82f1.png)

cc: @jbalboni

**Comment by laurenernest** [comment]
@jenniemc For this ticket, don't introduce any new data. This should just be for cleaning up what we currently show on this page.

**Comment by jenniemc** [comment]
roger that
