### ISSUE TITLE
Access for Vanessa Luxen

### ISSUE THREAD

**Issue by VanessaLuxen** [department-of-veterans-affairs/va.gov-team#15949]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffery Hayter
- Please provide your name.
   > Vanessa Luxen
- Please Provide your email.
   > vanessa.luxen@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA CMS, help desk, Agile 6

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDurlyzcV1YU9tj/45lTb/1cB08NDNKE6tttGUM2papz0o1iS2GP9K8C9mvEcFHpviEmLjIdhZPElOXp9XNwIyx1Npqy2IFhFsbmsxqdS/1tVv98x1Fm+kAIxpafzaLe4FYK5HHIXCkBxTXTM0nUJUt4DpX36uWaoicU4DMp/n6prZEN9kbTnw/x0M6A7GvM5bveoWp7dUV8PQVF6dJ/vZHj/1mJHAiSUYuiPgC0KNTfsqef5u15WMP/2WaqvWSP54w13g8MyQR1I6hMo6hdrXCHzK64RfJj2uXyyEpN0Tk3sjhOgc7P3+8X0mezenqk6a+EJPJUR76ZHl1tnFpSrzo+7qJo8ZulywrNKjyHXi5z7+YLzHQpanHkF2S4HsUAnBY4pqasyEkkj1Wf3M5sEDV2L5e8gYk0djCuHvaW0atqqYt3AutZqL14YVIeANByreQRqS5AOnHm/3X+3JHSep96VD0zR9rDTT8gVmJm+HhkInkVD4FLWe8rEJvrgZp4i0= vanes@LAPTOP-L519Q859

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by VanessaLuxen** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. We had an issue this morning in Jenkins that will likely prevent the deploy of your keys for about half an hour or so. Apologies for any / all inconveniences. Please allow up to a half hour and continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
