### ISSUE TITLE
Update hint label for Int'l Post Code

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15946]
## Acceptance Criteria

1. On the International Post Code edit field,  update the hint label to "Post code (required)"

## Context for update:
The current label, "International post code (required)", gets cut off in the edit screen on some devices. Screenshot attached in comments of Galaxy S9.

**Comment by bessgreen** [comment]
![Screenshot_20201106-160504_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/03d510d1-f51c-4019-8316-1d45d6579476)

**Comment by esther-k** [comment]
11/13 - verified fix on android (Google Pixel 3XL & LG LM-Q720 Stylo 5)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/19**

PASS - on iOS and Android. Moving to design QA
