### ISSUE TITLE
[Epic] Style guide edits to live pages in Drupal

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1595]
## High Level User Story
As a content editor without Drupal access, I need to keep a list of style guide edits that need to be made to live pages, so that someone with access can update in Drupal, and we don't lose track of edits needed. 

## Goal
Capture list of changes  (as tasks / stories) that need to be made to live pages to fix style guide discrepencies so that all live pages of VA.gov adhere to the rules of the VA.gov style guide.

## Acceptance Criteria
When a style guide error or discrepancy is discovered on a live page, it should be posted in a comment of the issue and the copy editor is alerted via assignee. The copy editor will then make those changes in Drupal, have them reviewed and set to publish.

**Comment by RLHecht** [comment]
Change all instances of "OJT" on page to "on-the-job training": https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/

**Comment by RLHecht** [comment]
Korean Demilitarized Zone should be abbreviated as DMZ on subsequent references. Pages to change:
https://www.va.gov/disability/eligibility/special-claims/birth-defects/
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/
https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/service-in-vietnam-korea/

**Comment by RLHecht** [comment]
In the alert box on the family member benefits page, change the sentence "Start a confidential Veterans Chat" to "Start a confidential chat."

https://www.va.gov/family-member-benefits/

**Comment by RLHecht** [comment]
Change "active duty service members" to "active-duty service members" per style guide. 

https://www.va.gov/health-care/eligibility/![Screen Shot 2019-09-16 at 11.26.05 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/ff667795-0594-47db-8653-f814b2620303)

**Comment by RLHecht** [comment]
In the alert box, lowercase "benefit letters"
https://www.va.gov/records/download-va-letters/
![Screen Shot 2019-09-18 at 3.30.21 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/b7505e8f-238d-4794-b5d5-84a9ee63440a)

**Comment by RLHecht** [comment]
Style guide updates need to be made to the following page, including sentence casing and "service member" among others.

https://www.va.gov/housing-assistance/

- [ ] Changes made
- [ ] Reviewed and published

**Comment by RLHecht** [comment]
@peggygannon When you get the chance, can you review the style guide changes I've made in all the pages mentioned in the comments above and publish? Thanks!

**Comment by FranECross** [comment]
All stories on this Epic are closed; closing epic
