### ISSUE TITLE
1995: Remove prod flag for remaining content updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15952]
As a developer, I need to remove a prod flag so the accreditation upload functionality is available in the production environment.

## Assumptions:
1. The work completed in #15720 has been reviewed and signed off in staging as of 11/12.

## Acceptance Criteria:
1. The work completed #15720 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15210

**Comment by delli-gatti-michael** [comment]
Changes are now on production. Closing this issue
