### ISSUE TITLE
Investigate why the CMS CD to DEV job is not Triggering anymore. 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#1596]
## Problem
CD to DEV job http://jenkins.vfs.va.gov/job/cms/job/rmw-meta-build-deploy-env/ is not triggering on pushes to develop anymore.

**Comment by tskinn** [comment]
After deleting the job and running the seed job, the git hooks seem to be working again. Unfortunately still no insight into why it stopped working in the first place.

**Comment by ricetj** [comment]
@tskinn can we close this one then?

**Comment by tskinn** [comment]
Yeah it seems to be working fine now.
