### ISSUE TITLE
Grafana (Vets-API Changes)

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#15964]
NOTE: please evaluate possibility of #16033 or the query referenced below before undertaking these proposed changes.
- #16033 has been evaluated and it turns out we're not going to be able to use the query

Our Grafana Alerts Dashboards currently have a "Sum of Errors" query. This query is based on the vets-api controller instead of the underlying VAMF service. What we want to do is to be able to create a grafana dashboard similar to this one, but based on a query on the service integrations. This is going to require making some changes on the vets-api side to an existing StatsD plugin to support a new tag for http status `on_error`. Furthermore, we might want to take this opportunity to introduce better filtering on some of the existing service urls. More details below:

All changes required will take place in the file: lib/breakers/statsd_plugin.rb

The method `send_metric` currently supports receiving tags for `endpoint` and `method`, additionally we want it to support `http_status` but this is part of the `response` object, not the `request` object. As such you will also need to make changes to `get_tags` to support this.

```ruby
    def get_tags(request, response)
      tags = []
      if request
        tags.append("endpoint:#{filtered_endpoint_tag(request.url.path)}") if request.url&.path
        tags.append("method:#{request.method}") if request.method
      end
      if response
        tags.append("status:#{response.status}") if response.status
      end
      tags
    end

...

    def send_metric(status, service, request_env, response_env)
      tags = get_tags(request_env, response_env)
      metric_base = "api.external_http_request.#{service.name}."
      StatsD.increment(metric_base + status, 1, tags: tags)
      if response_env && response_env[:duration]
        StatsD.measure(metric_base + 'time', response_env[:duration], tags: tags)
      end
    end
```

Making changes here, will allow us to create a new dashboard using a similar but different query than the one we currently use for latency whereby we can group by endpoint and http status. If you look at the latency URLs shown, there are a lot of them, and quite a bit of overlap on these as well. What we would like to do is improve the filtering around these. For this you'll want to also look at the method `filtered_endpoint_tag` so that we can look at lumping some of those such as `/cce/v1/patients/xxx/eligibility/Nutrition` as `/cce/v1/patients/xxx/eligibility/xxx` so that they are similarly grouped.

<img width="804" alt="Screen Shot 2020-11-09 at 12 18 02 PM" src="https://user-images.githubusercontent.com/591737/98580523-b5bd2a00-2285-11eb-936f-4cfa1f301a99.png">

Finally, you'll need to update specs. I'm not yet sure where the specs are for this particular plugin, but they very likely exist. You can look at the blame history and past PRs related to this file and hopefully that will point you in the right direction on which specs also need to be updated.

There will be a follow up ticket on this that will involve updating our Grafana dashboards, but this work must occur before that work can be completed.

**Comment by saneshark** [comment]
cc: @kfrz for awareness. You and I talked about this in the past, I think this work is critical to some of the other work we're doing and I thought you should be aware.

**Comment by kfrz** [comment]
Are you looking for the `haproxy` layer response codes, by external service endpoint? I.e. like this:

`sum(increase(haproxy_backend_http_responses_total{proxy=~"va_mobile_back"}[1h])) by (code, endpoint)`

Which would (ideally) return a breakdown of each `/cce/**/*` endpoint and response codes, by time?

**Comment by saneshark** [comment]
This ticket could theoretically be broken out into two tickets. 

1. Introducing the ability to track http status, in particular for the on_error event, but maybe also helpful to know for on_success if it was a 200 or 201. 

2. Improving the filtering for a couple of our urls which are not getting properly grouped because of the unique parameter passed in as part of the url as opposed to a query param.

To my knowledge there isn't any way to get at the error state for backend services, to me this would be a logical place for those tags to live since this is already where we are measuring latency, it would make sense to also track errors. Are you suggesting that that is already available by a different query?

What we currently use is less than ideal because it identifies the rails controller as part of rack statsd middleware. Our controllers could call out to multiple different services, we don't care what controller failed so much as what service failed and what status it returned.

**Comment by saneshark** [comment]
We would want much more granular detail than just `va_mobile_back` - I suspect that that points to the VAMF api-gateway, behind that gateway are a bunch of individual services, we care about the url more than the main gateway. The url tells us which service failed and is much more helpful.

**Comment by saneshark** [comment]
@kfrz could we do something like `sum(increase(haproxy_backend_http_responses_total{proxy=~"va_mobile_back"}[1h])) by (code, endpoint, method)

I think method is also going to be critical to track, because GET, POST, PUT are important to distinguish.

**Comment by kfrz** [comment]
http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping
