### ISSUE TITLE
Account Number is only valid at 17 digits

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15963]
## What happened? 
On the Direct Deposit edit screen, the Account Number is only "valid" (enables the confirmation check box) with a 17-digit string.

## Desired behavior
An account number cannot exceed 17 digits, but it can be fewer than 17. For the purposes of this initial, basic validation, a "valid" account number should be **between 1 and 17 digits**. (This may be refined in future sprints)

## Acceptance Criteria
An Account Number entry between 1 and 17 digits will activate the confirmation checkbox (assuming the 9-digit Routing # and Account Type are selected)

## Bug Severity
3

## Link to story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14714

**Comment by bessgreen** [comment]
- Awaiting requirements for minimum # of acceptable digits. 
- @bridgethapner meeting with VA.gov Profile developers on 11/17 to discuss the rules for this

**Comment by bessgreen** [comment]
Update: Bridget to meet with Profile team in early December. 

This will be a candidate to fix along w/ other Profile enhancements (including error states and more robust FE validation)

**Comment by bessgreen** [comment]
Update from @bridgethapner (via va.gov Profile team): Anything from 1-17 digits is valid

**Comment by digitalken** [comment]
PASS - Save button enables for less than 17 digit account numbers.
