### ISSUE TITLE
International Post Code field opens QWERTY keyboard

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15960]
## Acceptance Criteria:
1. Selecting the International Post Code edit field should open the QWERTY keyboard
     - Note: this differs from the U.S.-driven Zip Code field, which opens the numeric keyboard

## Reason for Update:
- Some international post codes have a combination of letters and numbers

**Comment by esther-k** [comment]
11/13 - verified fix on android (Google Pixel 3XL & LG LM-Q720 Stylo 5)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/19** 

PASS - on iOS and Android. Moving to design QA
