### ISSUE TITLE
Change CTA link from eBenefits to new VA.gov tool in January

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#15965]
On this page https://www.va.gov/find-forms/about-form-28-8832/

the online tool CTA currently points to the eBenefits tool. When the VA.gov feature for this benefit launches in January, the button should point to the new VA.gov tool. 

ETA - sometime in January 2021 - please check with tool PO Steve Kovacs (DEPO) to confirm tool launch date.

**Comment by johnhashva** [comment]
Marci -- a CTA is a Call to Action, typically a button link to an online tool or application at VA.gov.    In this case, it is the Green Button here:

![image](https://user-images.githubusercontent.com/63107147/98948547-92cc8900-24c4-11eb-844e-70a18a679456.png)

**Comment by MarciMcGuireGCIO** [comment]
**Backlog Grooming Note:** We need to reach out to Steve Kovacs for a status on the go-live date for the VA.gov tool for this form.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva assigning to you to touch base w/Steve Kovacs on their go-live date/

**Comment by MarciMcGuireGCIO** [comment]
Note for Sprint planning purposes:  This is a CMS change only; no code change required.

**Comment by MarciMcGuireGCIO** [comment]
Link was added to CMS on 1/4/2021
