### ISSUE TITLE
Feedback Tool: Remove Last 4 SSN Field

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#15978]
As a developer, I need to remove the last 4 SSN field from the form because it is causing errors on submission and the information is not required by Education Services.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The `Please provide the last 4 digits of your Social Security number` is removed from Chapter 1 of the Feedback Tool form (SA#2).

## Supporting Artifacts:
1. [Feedback Tool](https://www.va.gov/education/submit-school-feedback/introduction)
2. 
![image](https://user-images.githubusercontent.com/48260534/98591507-57507580-229e-11eb-88fc-6beff7f65bf5.png)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14924

**Comment by delli-gatti-michael** [comment]
Local testing complete. Will need to validate submission in Production

**Comment by delli-gatti-michael** [comment]
Test case:
https://dsvavsp.testrail.io/index.php?/runs/view/791&group_by=cases:section_id&group_order=asc

**Comment by delli-gatti-michael** [comment]
Changes are live on staging. Closing this issue
![Screen Shot 2020-11-16 at 3.46.10 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/154a02ee-970e-486f-b1ac-c70cdd929b7b)
