### ISSUE TITLE
Error Message: Upstream Claims/Appeals Error

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#15975]
## User Story
As a user, if claims are able to be fetches and appeals is not (or vice versa), I want to see a message explaining that the app will display claims information and not appeals information (or vice versa). 

## Technical Context
Appeals and Claims are fetched from two different services so it’s possible one could be down and the other still up.

## Error State Content
If Appeals Status is unavailable: 
**Appeal status is unavailable**
VA Mobile App is having trouble loading appeals information at this time. Please check back again later. You are still able to view claims information. 

If Claims Status is unavailable: 
**Claims status is unavailable**
VA Mobile App is having trouble loading claims information at this time. Please check back again later. You are still able to view appeals information. 

## Tasks
- [x] UI design
- [x] Add documentation to the body of this ticket for front-end
- [ ] ~~VSP content review~~ _(I don't think we need VSP content review here since we're using the error language from VA.gov)_ 

## Invision Link:
- -https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/439365083/preview?scrollOffset=969
- https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/439369079/preview?scrollOffset=969
- https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/439369080/preview?scrollOffset=969#project_console
- https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/439369081/preview?scrollOffset=969#project_console

## UX Documentation
**common component:**
App Background color: #F2F2F7
Border-left: 8px, variable, Warning: warning-message #fac922
Text (Headline): Mobile Body Bold (optional)
Text (Body): Mobile Body
Text color: gray-dark #323a45
Background color: variable
Internal padding: 20px top & bottom; 10px left & right
Margin: standard gutter L/R; marginBetween vertical
Optional ClickForAction button at the bottom

**Content Language:**

Appeals
(Headline) "Appeal status is unavailable"
(Body) "VA Mobile App is having trouble loading appeals information at this time. Please check back again later. You are still able to view claims information."

Claims:
(Headline) "Claims status is unavailable"
(Body) "VA Mobile App is having trouble loading claims information at this time. Please check back again later. You are still able to view claims information."

**Comment by msmanak** [comment]
![Appeal and claim status unavailable.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/8e4b9850-1369-403d-8f9e-f986c05410e7)

Q: do we want to have this above the current flow of the claim/appeal status or should it be its own page?

**Comment by msmanak** [comment]
common component:

App Background color: #F2F2F7
Border-left: 8px, variable, Warning: warning-message #fac922
Text (Headline): Mobile Body Bold (optional)
Text (Body): Mobile Body
Text color: gray-dark #323a45
Background color: variable
Internal padding: 20px top & bottom; 10px left & right
Margin: standard gutter L/R; marginBetween vertical
Optional ClickForAction button at the bottom


**Content Language:**

Appeals:
(Headline) "Appeal status is unavailable"
(Body) "VA Mobile App is having trouble loading appeals information at this time. Please check back again later. You are still able to view claims information."

Claims:
(Headline) "Claims status is unavailable"
(Body) "VA Mobile App is having trouble loading claims information at this time. Please check back again later. You are still able to view claims information."

**Comment by bridgethapner** [comment]
Hi there @msmanak -- the rest of the UI on the overview screen may display here, so it might be worth showing that in the wireframe to clarify where the error would appear. For example, appeals would display if claims aren't available or vice versa. I see the following logic possibilities here: 

- Appeals can load, claims can't load (user has appeals and list displays)
- Appeals can load, claims can't load (user has no appeals and empty state of list displays)
- Claims can load, appeals can't load (user has claims and list displays)
- Claims can load, appeals can't load (user has no claims and empty state of list displays)

Do you want to set up some time to chat through this one? Feel free to grab time on my calendar tomorrow!
