### ISSUE TITLE
Native Modules for Add to Calendar

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#15977]
As a developer I need an api to interact and send events to the device's native calendar api.

ACs:

- [x] Add event to Android Calendar via Share Sheet
- [x] Add event to iOS Calendar via Action Sheet
- [x] Check for correct permissions in Android
- [x] Check for correct permissions in iOS
- [x] Request correct permissions in Android
- [x] Request correct permissions in iOS

**Comment by lexicalninja** [comment]
created features/add_to_calendar_modules branch in repo

**Comment by lexicalninja** [comment]
update branch is features/calendar due to build errors on other branch

**Comment by lexicalninja** [comment]
QA Considerations when using this:

Android:
- if a user has one calendar app, it should use the default app
- if a user has multiple calendar apps but told the system that one app is default it should open that app
- if a user has multiple calendar apps and doesn't specify it should bring up a share sheet

iOS:
- It should use the default Calendar app.
- iOS forces a user to use the default apps to add events. If a user uses any other app they will need to use a workaround to see the event in their chosen app. This is a fairly common issue with iOS and is almost always solved by adding the calendar account to the system Accounts and making the preferred calendar the default calendar in the iOS calendar settings. On the surface this sounds like a major pain point or issue, but has been the standard in iOS almost from the start. There is no other way to sync different calendars in iOS.

**Comment by bessgreen** [comment]
@bessgreen to update swimlane / move to QA once [#16046](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16046) is QA-ready
