### ISSUE TITLE
GIDS: Unable to upload AccreditationAction CSV

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#15973]
## What happened?

While attempting to upload the CSV in [AccreditationData_11092020.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/5512817/AccreditationData_11092020.csv.zip) received this error message
![image](https://user-images.githubusercontent.com/1094999/98586839-523bf800-2297-11eb-93ee-582892d977e9.png)

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/768

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-11-09 at 3.03.27 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cd7ebdb7-a164-4475-92f0-4d328a1bbc38)

**Comment by sonntag-adam** [comment]
in staging, closing bug.
