### ISSUE TITLE
In-app web view for 'Find your nearest VA location'

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15988]
## Acceptance Criteria
1. On the **How Do I Update My Personal Information** page, the **Find your nearest VA location** hyperlink should open in-app, rather than out-of-app
     - This is the same in-app web view that launches from **Find a VA Location** on the Home page

## Reason for Update
Since the same URL (https://www.va.gov/find-locations/) can be launched across different pages in the app, it should open the same way.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Tested on Android to verify code change is in. iOS build isn't yet up-to-date but code change is verified.  Moving to Design QA.
