### ISSUE TITLE
Past Appointments: Empty State

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#15982]
## User Story
As a user, if I have no past appointments for a given timeframe, I would like to see a message explaining that I had no appointments within that time frame. 

## Copy
"You do not have any appointments for these dates."

## Tasks
- [x] UI design
- [x] Documentation for front-end

## Invision Links
https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/439369623/preview?scrollOffset=5806

## UX documentation
Common Component:

Text (Headline): Mobile Body Bold (optional)
Text (Body): Mobile Body
Text colors: gray-dark #323a45
margin: standard gutter L/R; margin between vertical
Content Review:

(headline) You don’t have any appointments
(body)You do not have any appointments for these dates.

**Comment by srmyers17** [comment]
Two empty states:
- One is for upcoming appointments (another ticket that is done!)
- One for past appointments (this ticket)

**Comment by msmanak** [comment]
@bridgethapner 

"You do not have any appointments for these dates." Would this be considered a header or body for this story?

I can see it go both ways. Do we have the ability to make it date specific or a general idea?

**Comment by bridgethapner** [comment]
@msmanak Good questions. I'm leaning towards using body, what do you think? I'm good with whatever you think is best. Re the ability to make it specific or general - my gut says to keep it general since the filter above the message will display the date range selected. What do you think? Do you think it would be an accessibility issue to not reiterate the date in the empty state message?

**Comment by msmanak** [comment]
![Appointment-past-empty.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/c2f50cda-2aef-46c1-bdc9-145e160fe254)

**Comment by msmanak** [comment]
**Common Component:**
- Text (Headline): Mobile Body Bold (optional)
- Text (Body): Mobile Body
- Text colors: gray-dark #323a45
- margin: standard gutter L/R; margin between vertical

**Content Review:**
- (headline) You don’t have any appointments
- (body)You do not have any appointments for these dates.
