### ISSUE TITLE
No past appointments for selected date range (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15987]
## User story
As a user, I want a screen that tells me when I do not have any past appointments.

## Acceptance Criteria
1. Create UI as shown in designs
     - The "You don't have any appointments" UI will display when a user does not have any Past Appointments for the selected date range
2. VA.gov hyperlink opens the following link out-of-app in the user's browser: https://www.va.gov/health-care/schedule-view-va-appointments/

## Designs
https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/439369623/inspect?scrollOffset=5806
![Screen Shot 2020-12-03 at 1.53.30 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c183e442-516e-41f9-940c-2ec5a5374a3d)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Mark "Appointments" as Header 1
- Mark "You don't have any appointments" as Header 2

**Segmented Selector**
- accessibilityLabel="past"
- accessibilityHint="view your past appointments"
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 2 of 2) 

**Date Range Picker**

When not selected (covered in [past appointments story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13994)):
- accessibilityLabel= contents of field (e.g. Past 3 months)
- accessibilityHint="select a date range"
- accessibilityRole="spinbutton"
- accessibilityState= "collapsed"

When selected:
- Denote when dropdown is expanded
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list
- Ensure dropdown area does not "trap" the keyboard focus

**Link**
- Icon
     - Title= “right arrow icon” 
     - accessibilityRole= “image”
 - Link
     - Title= "visit va.gov"
     - accessibilityRole= “link” 

## Dev Checklist 

- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Revisit test case "Past Appointments List (UI) #13994" https://dsvavsp.testrail.io/index.php?/cases/view/2110&group_by=cases:created_on&group_order=asc&group_id=-1
when this story is completed with corrected data.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Have to test without mock data...

**Comment by digitalken** [comment]
PASS 2/2/2021 - Minor bugs written but passing as a whole.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19428

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19427
