### ISSUE TITLE
Google Analytics/DOMO Access Request

### ISSUE THREAD

**Issue by katieho-va** [department-of-veterans-affairs/va.gov-team#15981]
Hello! We have two new team members on Team Orchid/IRIS. Can we get them access to both Google Analytics and DOMO? Thank you!

1. Mark Nunemaker mnunemak@thoughtworks.com
2. Paul Phillips pphillip@thoughtworks.com

**Comment by jonwehausen** [comment]
Hi @katieho-va , 

Thank you for your request here. 

Both @PaulPhillips-va and @mnunemaker-va should have received emails indicating their GA and DOMO access. 

Please feel free to reach out / re-open this issue if you have any access-related concerns.
