### ISSUE TITLE
Update FE validation rule to include Phone Extension

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15989]
## Acceptance Criteria
1. Update the FE validation for the Edit Phone screens (across all phone types) so that the "Save" button becomes actionable when either of the following are true:
     - The Number field contains 10 digits 
     - The Number field AND Extension field is blank

## Reason for update
- The original requirement did not specify that the Extension should be part of the FE validation. As a result, a user can save a 0-digit Number, but can also enter an Extension and save it.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/19**

PASS - on iOS and Android. Moving to design QA
