### ISSUE TITLE
Access for Noah Gelman

### ISSUE THREAD

**Issue by noahgelman** [department-of-veterans-affairs/va.gov-team#15983]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Noah Gelman
- Please Provide your email.
   > noah.gelman@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Testing Team

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBfX9wwn/z5KSiFK7eT5XT4Cr3AGeu3LalSkhjnc4RVdYryzooqPsijW0OcBGDHvRhc1PdRA6dRE5KdSQJu23H9eXCuMBtL2RddDBUfBTk9fNnKATUiBmwU1UMA8884lO/YKuJmGWFrRfCe3JNBzp9oKySeTj+STYYbKNBB4T4fzorcdKWH6K1zcgKru/jmuJ/QLlgCh4Tn++Qx8G3AAvxJ2JTJnviIV9VvP0htau43aAXoTCF7P6lVUUQMTisJg2K1NeldhRxJc8vy8yteOE5JtkpaMnPo1M2axiDfagmfDaoTOkdM5OM3+J/EqwA8FyhxGhRWh5W6fURPJ8UT82MsibI2wj6MKFulx6EwzKGt3aOTf5gUP/uIh5pUusbyeluCe0dc5q57Pp/1+ZKLMYWtfdDFO7sIiZPVTf4DBjUvKXP5C93OjLnf5TnZW8V1cB5kfEqMWwNaRgYgtEMk7WKVxlc1PS3rsiC8boiKZXB61NOUJBkSHk4Ti3dZNUTs6E= noahg@KLAM-HP

```

- Grant AWS Console access?
  > NO
  - N/A

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
