### ISSUE TITLE
Update FE validation rule for Edit Residential Address

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15995]
## Acceptance Criteria
The validation rules for Mailing Address & Residential Address are different. Make the following changes:

1. Update the FE validation for the Edit Residential Address screen so that the Save button becomes actionable if one of the following is true:
     - All fields on the screen marked "required" contain an entry
     - All fields are empty

Note: the currently-implemented validation rule for Mailing Address is correct and should remain unchanged. This rule says that the Save button becomes actionable when the following is true:
     - All fields on the screen marked "required" contain an entry

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/19** 

PASS - on iOS and Android. Moving to design QA
