### ISSUE TITLE
[Bug] HLR - Contest Issues - unexpected UX for no-issues-found scenario

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15996]
## What happened?
On Staging **Request a Higher-Level Review** form, Step 2 of 4, Contested issues page, the user-experience was unexpected for User with no contested issues found:
1.  **...same office** checkbox still clickable.
2.  Error message for "required" issue-selection displayed upon clicking **Continue**.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vetsgov+test238@id.me`

## Steps to Reproduce
1.  Go to https://staging.va.gov/ and sign-in as **`vetsgovtest+238@id.me` (Nerea)**. [See [this doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.docx) for all test-accounts and credentials.]
1.  Go to https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction
1.  IF eligibility wizard (**Is this the form I need?** section) is displayed, click **Disability...**, **No**, then **Request...**.  Browser replaces wizard content with standard intro content.
1.  IF **application-in-progress** alert is displayed, click **Start... new...**.  [Click **Start** again in confirmation dialog-box.]
1.  Keep clicking **Continue** until **Step 2 of 4: Contested issues** page is displayed.  For this User, under **Select the issue...**, **No items found** message is displayed, instead of contested-issues list.
1.  Observe the following unexpected UX behaviors which are illogical for "No items found":
    - Click **If possible, I would like the same office conduct this review.** -- it's selectable, but shouldn't be.
    - Click **Continue** -- **Please choose a disability** error message is displayed, but shouldn't be.

**Screenshot**
![hlr-bug-issues-no-items-found](https://user-images.githubusercontent.com/587583/98613779-4874bd80-22b4-11eb-8e98-739dbcd7cd77.png)

## Desired behavior
[VSA BaM1 team to spec-out expected behaviors to replace above observations.]

## Acceptance Criteria
- [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
Hi Tze!

This is actually a bug I discovered. User 238 _should_ have one contestable issue to display, but it gets accidentally removed once you get past the intro page.

What you're seeing on this page shouldn't ever be visible. If you don't have any contestable issues, you shouldn't make it past the introduction page - user 234 can be used for this test scenario, but again.. the form should never process past the intro page.

**Comment by Mottie** [comment]
Hi Tze!

This has been fixed in staging - should be in production after 3pm ET.

As I mentioned in my previous comment, user 238 should now show one contestable issue on that page. User 234 has no contestable issues and will not be allowed past the introduction page. There _shouldn't_ be any way to get that view you shared in the screenshots, but I did add some methods to hide the additional content if such a case were to ever happen again.

**Comment by tlei123** [comment]
Ackno

> Hi Tze!
> 
> This has been fixed in staging - should be in production after 3pm ET.
> 
> As I mentioned in my previous comment, user 238 should now show one contestable issue on that page. User 234 has no contestable issues and will not be allowed past the introduction page. There _shouldn't_ be any way to get that view you shared in the screenshots, but I did add some methods to hide the additional content if such a case were to ever happen again.

Acknowledged.  Closing issue now.
