### ISSUE TITLE
[Bug] HLR - Form intro - Copy mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#15994]
## What happened?
On Staging **Request a Higher-Level Review** form intro page, the **Respondent burden** duration didn't match design prototypes.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vetsgov+test238@id.me`

## Steps to Reproduce
1.  Go to https://staging.va.gov/ and sign-in as **`vetsgovtest+238@id.me` (Nerea)**. [See [this doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.docx) for all test-accounts and credentials.]
1.  Go to https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction
1.  IF eligibility wizard (**Is this the form I need?** section) is displayed, click **Disability...**, **No**, then **Request...**.  Browser replaces wizard content with standard intro content.
1.  Scroll down and observe that **Respondent burden** is 15 minutes [not 30 as spec'ed in design prototypes].

**Screenshot**
![hlr-bug-intro-respondent-burden](https://user-images.githubusercontent.com/587583/98610646-465b3080-22ad-11eb-9f9c-48efb4801033.png)

## Desired copy
**Respondent burden** should be **30** minutes [per [design prototypes](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/404076957)]:
![hlr-spec-intro-respondent-burden](https://user-images.githubusercontent.com/587583/98610685-64289580-22ad-11eb-92e3-216b1af08ebd.png)

## Acceptance Criteria
[See **Desired copy** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
The [Higher-Level Review form](https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf) shows a respondent burden of 15 minutes - see the top of page 3/4

<img width="207" alt="Screen Shot 2020-11-12 at 8 56 30 AM" src="https://user-images.githubusercontent.com/136959/98956036-328a1700-24c5-11eb-963a-f7f17526e4fd.png">

**Comment by kevinstachura** [comment]
Hi @tzelei - The prototype in this instance was inaccurate and the staging environment was correct. The prototype has been edited to properly reflect respondent burden time:

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/404076958

Thanks so much for finding this!

**Comment by tlei123** [comment]
^Thx, @kevinstachura !  Closing this as false-positive.
