### ISSUE TITLE
Community Care preference list analytics

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15990]
## Issue Description
Add tracking events to new preferred community care provider list page

---
## Acceptance Criteria
- [ ] Update is behind VA Online Scheduling Provider Selection feature flag
- [x] Track order position of provider selection
- [x] Track provider list pagination clicks
- [x] Track # of "Choose a provider" clicks per user session
- [x] Track continue with no provider selected _(similar to current page)_
- [x] Track continue with provider selected _(similar to current page)_

![Screen Shot 2020-11-17 at 4.29.46 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/eaab149e-6549-4cf8-ac8b-e61983c68e41)
![Screen Shot 2020-11-17 at 4.28.48 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/68a26d93-02f3-4f6b-98ea-48b0c1256eb6)

Note: See [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15990#issuecomment-724865526) below for partnering with analytics

---
## Additional Notes
_Removed from ACs_
- [/] ANALYTICS - Track bounce from page
-- Can use standard bounce tracking in [GA](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fhealth-care~2Fschedule-view-va-appointments~2Fappointments~2Fnew-appointment~2Fcommunity-care-preferences~2F)

**Comment by bsmartin-ep** [comment]
@laurenernest -

Just to get the ball rolling on this....

>  ANALYTICS - Track order position of provider selection

This is feeling like a new custom event we'll have to give you.  When do you expect to have a dev / staging build we could look at?

>  ANALYTICS - Track provider list pagination clicks

Assuming you are using the [standard Pagination component](https://design.va.gov/components/pagination), you should have `nav-paginate-` events firing automatically.  I don't see any now on non-prod yet, but they would show up here...

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22BW%22,%22nav-paginate%22,0%5D,%5B0,%22analytics.pagePath%22,%22PT%22,%22community-care-preferences%22,0%5D%5D

...with this query....

![image](https://user-images.githubusercontent.com/62304138/98711955-b02e1580-2353-11eb-8e36-faef12fb6cf7.png)

> ANALYTICS - Track bounce from page

Unless you have some special business logic for bounces we would need to do in BigQuery, you should be able to pull the standard Bounce in GA:

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fhealth-care~2Fschedule-view-va-appointments~2Fappointments~2Fnew-appointment~2Fcommunity-care-preferences~2F

**Comment by laurenernest** [comment]
@bsmartin-ep Thanks for the info! It'll be a few days before something's in staging to the dev can reach out at that time.

**Comment by laurenernest** [comment]
@bsmartin-ep FYI - I added a couple more items to call out that we need to track the same events on this new version of the page similar to the current version (#15834).

**Comment by LanceGundersen** [comment]
@bsmartin-ep these are the event names I used
 
- Track order position of provider selection `vaos-order-position-provider-selection`
-  Track provider list pagination clicks `vaos-provider-list-paginate`
-  Track # of "Choose a provider" clicks per user session `vaos-choose-provider-click`
-  Track continue with no provider selected (similar to current page) `vaos-continue-without-provider`
-  Track continue with provider selected (similar to current page) `vaos-continue-with-provider`

**Comment by bsmartin-ep** [comment]
@LanceGundersen -

Would `order position of provider selection` be a parameter in the `vaos-choose-provider-click` event?

-----

> Track provider list pagination clicks vaos-provider-list-paginate

Would you consider this a different type of component than https://design.va.gov/components/pagination ?

**Comment by LanceGundersen** [comment]
@bsmartin-ep I forgot the param, I put it as `providerPosition`. 

Regarding the second question. I do as it's not the same structure but maybe it's the same in overall function. @jbalboni what do you think?

**Comment by jbalboni** [comment]
@LanceGundersen @bsmartin-ep The idea is pretty similar to the Pagination component, but the visual presentation is different. There's only one action (showing the next set of results) and you can't go back. You also can't go to arbitrary pages.
