### ISSUE TITLE
Hide the nav bar on edit screens

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#15991]
## Acceptance Criteria
1. Hide the bottom navigation bar on all edit screens, including:
     - Edit Address (all types)
     - Edit Phone (all types)
     - Edit Email
     - Edit Direct Deposit

## Reason for update
- Hide the nav bar on these pages to avoid having two actions of the keyboard + nav bar swapping out at the bottom
- Maintain 1 bottom action element per page

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/19**

PASS - on iOS and Android. Moving to design QA
