### ISSUE TITLE
Document express care flow & page states

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15999]
## Description
Given the various logic a user has to pass through to make an appointment, the express care flow needs to appropriately account for the proper context and consistency

Ideally this documentation would include:

- Data presented with each page

- Screenshots of an example state for each

## Tasks

- [ ] Document current express care pages in flow

- [ ] Document states of each page

## Additional Notes
See #16917 for a similar example

**Comment by jbalboni** [comment]
I've added screenshots and some notes for each state here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/express-care-flow.md

**Comment by outerpress** [comment]
Thanks @jbalboni ! Similar to the direct schedule flow, it'd be helpful to see language from any automated emails that are sent out by the system if possible (and if they exist).

**Comment by jbalboni** [comment]
Yeah, let me see what I can capture. There are emails during different points in the Express Care/request process.

**Comment by jbalboni** [comment]
@outerpress I was only able to generate one email, which came after the Express Care request was marked as resolved in Scheduling Manager. I've added that to the doc I created.

**Comment by outerpress** [comment]
Thanks @jbalboni !
