### ISSUE TITLE
Sort Community Care list by distance from current location

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15992]
## Issue Description
As a user, I would like to see a list of community care providers nearby so I can make an appointment at a facility close to me.

---
## Acceptance Criteria
- [ ] Update is behind VA Online Scheduling Provider Selection feature flag
- [ ] By default, provider options are based on the distance from the Veteran's home address in their profile, starting with the closest
- [ ] If user selects Current Location AND allowed by browser, sort provider options based on the distance from the user's geolocation
- [ ] If user selects Current Location AND not allowed by browser, show messaging AND allow user to switch back to home address reference
- [ ] Copy for blocked browser reads message, "Your browser can't find your current location. Please make sure your browser's location feature is turned on."
- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs:
- https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/438121103
- https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/438121104
- https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/438121105

**Comment by jbalboni** [comment]
I looks like the facilities CC providers api now supports passing lat/long and radius, though it still seems to require a bbox. But since the address param is no longer required, this ticket is unblocked.

**Comment by laurenernest** [comment]
@vbahinwillit FYI on this bug @jbalboni discovered on the similar sort functionality in the VA flow #16962. Let's make sure this is covered for CC.

**Comment by laurenernest** [comment]
@vbahinwillit I added to the ACs the specific copy for the message box when the browser is blocked from finding the current location.

> Your browser can't find your current location. Please make sure your browser's location feature is turned on.
