### ISSUE TITLE
Document VA request flow & page states

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15998]
## Description
Given the various logic a user has to pass through to make an appointment, every path in the VA request flow needs to appropriately account for the proper context and consistency

Ideally this documentation would include:

- Data presented with each page

- Screenshots of an example state for each

## Tasks

- [ ] Document current VA request pages in flow

- [ ] Document states of each page

## Additional Notes
Types of care with VA requests available:
- Amputation care
- Audiology and speech
- Eye care
- Mental health
- MOVE! weight management
- Nutrition
- Pharmacy
- Primary care
- Sleep medicine
- Social work

See #16917 for a similar example

**Comment by jbalboni** [comment]
@outerpress Documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/request_flow.md

**Comment by outerpress** [comment]
Thanks Jeff! This looks great. The different error states are especially helpful.
