### ISSUE TITLE
Document community care flow & page states

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15997]
## Description
Given the various logic a user has to pass through to make an appointment, every path in the community care flow needs to appropriately account for the proper context and consistency

Ideally this documentation would include:

- Data presented with each page

- Screenshots of an example state for each

## Tasks

- [ ] Document current CC pages in flow

- [ ] Document states of each page

## Additional Notes
Types of care with CC available:
- Primary Care
- Audiology - Routine hearing exam
- Audiology - Hearing aid support
- Nutrition
- Podiatry
- Eye care - Optometry

See #16917 for a similar example

**Comment by narin** [comment]
@laurenernest @outerpress  I've added documentation for the cc flow [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/community_care_flow.md).

Please let me know if you'd like any more details to be added

**Comment by outerpress** [comment]
Thanks Narin! The only other thing I'd ask for is a screenshot of any emails that go out (confirmation, etc.) to the user as a part of the process, if there are any. Other than that, this is perfect.

**Comment by narin** [comment]
Added email info @outerpress.  Closing this one out.
