### ISSUE TITLE
[Development] HLR: Content Changes for CST Timing

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16006]
## Issue Description
Since HLR is not doing auto establishment we need to make sure the veteran understands that CST will not be updated for some time.  Luke to reach out to OAR etc to determine what to put there.  This should appear on the confirmation page for HLR where our "standard" method is to let them know it will show up in CST.

## Acceptance Criteria
- [ ] Updated content based on data from OAR
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
Sent an email to Lauren - suggest wording so far:

"Please visit the Claims Status Tool to check the status of your higher level review.  Note: It may take from 7-10 days for the claim to be processed and show up in the status tracker."

**Comment by luke-gcio** [comment]
Moving to Sprint 35, we ended up with about 8 stories post staging review to work on so those take priority over this messaging.

**Comment by luke-gcio** [comment]
Approved by Lauren to have the messaging from above:

> Please visit the Claims Status Tool to check the status of your higher level review. Note: It may take from 7-10 days for the claim to be processed and show up in the status tracker.

**Comment by Mottie** [comment]
@peggygannon Here is a screenshot of what I've ended up with

![Screen Shot 2020-11-18 at 1 25 52 PM](https://user-images.githubusercontent.com/136959/99578129-f31a6980-29a1-11eb-9d20-92e08b07faa9.png)

**Comment by peggygannon** [comment]
Hi, @Mottie Here's my recommendation: 


{CTA button} Check the status of your decision review

**Note:** Please allow some time for your decision review to process through our system. It could take 7 to 10 days for it to show up in our claim status tool.
