### ISSUE TITLE
Document direct schedule flow & page states

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16000]
## Description
Given the various logic a user has to pass through to make an appointment, every path in the direct schedule flow needs to appropriately account for the proper context and consistency

Ideally this documentation would include:

- Data presented with each page

- Screenshots of an example state for each

## Tasks

- [ ] Document current direct schedule pages in flow

- [ ] Document states of each page

## Additional Notes
See #16917 for a similar example

**Comment by jbalboni** [comment]
@laurenernest @outerpress I've added screens and some notes here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/direct-schedule-flow.md

**Comment by outerpress** [comment]
Thanks @jbalboni this is very helpful! I don't know if it's in scope for this effort, but it would also be useful to see any emails we send out (confirmation, reminder, etc.) as part of the direct scheduling flow.

**Comment by jbalboni** [comment]
For the direct schedule flow, I'm not sure if there are emails. I don't think I've seen any, at least. Not sure if @lenaecb remembers if there are emails, or if we need to check with Marcy.
