### ISSUE TITLE
Dev: Gate VAOS on VA.gov and build UIs for error states

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1600]
## Story
As a veteran, I don't want to go through the VAOS scheduling flow if I'm not actually allowed to use the online scheduling tool so that I don't waste my time. If I'm not allowed to use the tool, I want to know why so that I can correct the problem.

## AC
- [ ] Veterans who do not meet criteria documented in #1597 should not be able to start the online scheduling process
- [ ] UI exists for all states that are mocked in #1598

**Comment by peggygannon** [comment]
@markgreenburg @rtwell 

Here's a draft of a gating message prompting users to sign in. I don't know what the mock looks like, so please let me know if this messaging is along the right path? 

{user not signed in}

**You need to sign in to use the VA appointment tool**
You can use the VA appointment tool if you meet all of the requirements listed below. You’re:
	Enrolled in VA health care, **and** 
	Registered in at least 1 VA medical center that accepts VA online scheduling
**Note:** You won’t be able to use the VA appointment tool if your health care facility doesn’t support online scheduling.  

{button} Sign in to schedule your appointment

[Find out how to apply for VA health care benefits](https://www.va.gov/health-care/how-to-apply/)

**Comment by jbalboni** [comment]
@peggygannon Here's some mocked messages from me, based on the two conditions we can have: https://github.com/department-of-veterans-affairs/vets-website/pull/11024

**Comment by markgreenburg** [comment]
Looks good Peggy. @rtwell is this ready for dev?

**Comment by rtwell** [comment]
yes 👌
