### ISSUE TITLE
[Discovery] HLR: We Allow for Blank Address to Submit HLR

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16007]
## Issue Description
If the user does not have an address, we allow them to proceed and submit.  Right now, we link them to the profile page if they want to make an update but we don't prevent them from continuing without a blank address.  This ticket is to think about how to potentially force/gate them to update the address in the profile and then refresh their address confirmation screen to ensure it is not blank.

## Acceptance Criteria
- [ ] We gate them to update their blank address
- [ ] We make sure they don't proceed until we can verify that it was done

**Comment by ndsprinkle** [comment]
Beginning work on this today. Will start with Robin's suggested method of doing this check upon loading the form.

**Comment by ndsprinkle** [comment]
The primary PR for this was merged yesterday and a small bug fix (to handle users not logged in) will be merged shortly.
