### ISSUE TITLE
[Bug] HLR - Review - Profile edits not reflected

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#16001]
## What happened?
On Staging **Request a Higher-Level Review** form, **Review Application** page, after editing **Contact information** on Profile, contact-info changes were not reflected on Review page [even after page-refresh].

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_:  `vetsgov+test239@id.me`

## Steps to Reproduce
1.  Go to https://staging.va.gov/ and sign-in as **`vetsgov+test239@id.me` (Medge)**.  [See [this doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.docx) for all test-accounts and credentials.]
1.  Go to https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction
1.  IF eligibility wizard (**Is this the form I need?** section) is displayed, click **Disability...**, **No**, then **Request...**.  Browser replaces wizard content with standard intro content.
1.  IF **application-in-progress** alert is displayed, click **Continue**.
1.  Advance to **Review Application** page, inputting/selecting any required fields and clicking **Continue** on the way.
1.  On **Review Application** page, click to expand **Veteran information**, then click **Edit on Profile**.  Browser opens Profile page in new tab.
1.  On **Personal and contact information** (Profile) page, under **Addresses**, next to **Mailing address**, click **Edit**, change some address values, then click **Update**.  Browser displays updated address on Profile page.
1.  Under **Phone numbers**, next to **Home** number, click **Edit**, change the number, then click **Update**.  Browser displays updated number on Profile page.
1.  Close browser tab with Profile page.  Browser displays HLR form Review page again.
1.  Refresh **Review Application** page, and observe that Profile changes are not displayed.

### Screenshots

**Profile changes** made via clicking **Edit of Profile** on HLR-form Review page:
![hlr-spec-profile-changes](https://user-images.githubusercontent.com/587583/98618571-bd4cf500-22be-11eb-81ba-99ca15f5fc4e.png)

**Review page** refreshed after above Profile changes:
![hlr-bug-review-contact-info](https://user-images.githubusercontent.com/587583/98618604-cd64d480-22be-11eb-972d-d59d7e86c2ad.png)

## Desired behavior
After making Profile updates, updated contact-info should be reflected on HLR-form Review page.

## Acceptance Criteria
[See **Desired behavior** above.]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
I've discussed this issue with Anna. We will switch over to show the already loaded profile data instead of relying on the form prefill for the address and phone number.

**Comment by Mottie** [comment]
Hi Tze!

This fix has been merged and will be available in staging shortly.
