### ISSUE TITLE
GitHub action to label vets-api PRs

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#16011]
it'd be helpful for utility and organizing in general if a github action could label changes only in `modules/mobile` as "mobile".  Similar for things like "lighthouse" or "vaos" or other code owners

This looks handy https://github.com/actions/labeler

**Comment by ericboehs** [comment]
OMG yes

**Comment by jeff2d2** [comment]
@thilton-oddball Could you please link what is being reviewed into this ticket?
