### ISSUE TITLE
Profile should init a vet360 ID for users who lack it

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#16012]
On staging:
User 1 (who has null values for all of the keys in their `vet360ContactInformation`) cannot update contact info. The POST to create the transaction succeeds but the transaction fails with:
```
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_telephone_transactions",
    "attributes": {
      "transactionId": "cbaa33e6-acf9-490d-af42-f73b3263fa2e",
      "transactionStatus": "COMPLETED_FAILURE",
      "type": "AsyncTransaction::Vet360::TelephoneTransaction",
      "metadata": [
        {
          "code": "CORE103",
          "key": "_CUF_NOT_FOUND",
          "retryable": null,
          "severity": "ERROR",
          "text": "The PersonBio for id/criteria 1,411,740 could not be found. Please correct your request and try again!"
        }
      ]
    }
  }
}
```

User vetsgov+test236@id.me (who has a totally empty object for the `vet360ContactInformation` value that comes back from `GET user/`) cannot even create the POST to create the transaction:
```
{
  "errors": [
    {
      "title": "Forbidden",
      "detail": "User does not have access to the requested resource",
      "code": "403",
      "status": "403"
    }
  ]
}
```

Both users should be able to update contact info.

**Comment by annaswims** [comment]
when this is merged we should see a steep drop in the rate of 403 responses here http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?viewPanel=12&orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v0%2Fprofile%2Faddresses&var-frontend_app=All&from=now-7d&to=now
