### ISSUE TITLE
Analytics Implementation or QA Support for BAM2 DebtRes FSR form

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#16010]
# Google Analytics Implementation or QA Request

This is for implementation on FSR Form. Prototypes [here](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701377/simulate/sitemap?mode=i) We would like to discuss KPIs first, then implementation Thanks! 

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Implementation 

- Who is this request for?

    - BAM2, Leah
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - [BAM@ DebtRes FSR form ]
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @leahkeeler ! 

What availability does you and your team have for the week of Nov 16 - Nov 20? 

You can find my calendar here: https://calendar.google.com/calendar/u/0?cid=am9uLndlaGF1c2VuQGVtcGlyaWNhbHBhdGguY29t

**Comment by joanneesteban** [comment]
@leahkeeler When you get a chance to schedule this, please add me as well! ([Calendar URL](https://calendar.google.com/calendar?cid=am9hbm5lQGFkaG9jdGVhbS51cw))

**Comment by leahkeeler** [comment]
Done! Thanks to both :)

**Comment by jonwehausen** [comment]
### Implementation Notes
- Looking through the KPIs & UXPIN preview, wanted to document the two early items we know for certain will come out of this implementation: 
   - [Standardized Form Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md)
   - [Standardized Wizard Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md)

**Comment by joanneesteban** [comment]
Removing assignees & will reassign during Grooming tomorrow.

**Comment by joanneesteban** [comment]
@leahkeeler do you have dates for when this is going out? We might need to pull this in in our next sprint instead of this sprint.

**Comment by jonwehausen** [comment]
### Forms Library QA Testing

First Header | Data Layer Screenshot | Test Status
------------ | ------------- | -------------
Form start no login | ![image](https://user-images.githubusercontent.com/48527022/103542358-ce535600-4e6a-11eb-910d-56efaafd0542.png) | ✔️ **PASS**
Start form logged in | ![image](https://user-images.githubusercontent.com/48527022/103543112-fd1dfc00-4e6b-11eb-8fc1-9a3f798f13c3.png) | ✔️ **PASS**
Submitted the form, (_ALL Submissions_ - standard `--submission` event) | ![image](https://user-images.githubusercontent.com/48527022/103542766-6cdfb700-4e6b-11eb-961e-f06bfc3807bf.png) | ✔️ **PASS**
Submitted the form (_failed_) | ![image](https://user-images.githubusercontent.com/48527022/103542853-9b5d9200-4e6b-11eb-9813-949e9dcdcadc.png) | ✔️ **PASS**
Click to "finish application later" (saved) | ![image](https://user-images.githubusercontent.com/48527022/103543246-33f41200-4e6c-11eb-8e34-8598d434fbdb.png) | ✔️ **PASS**

 
### Questions
- @bradl3yC Are we able to test a successful submission currently? 
- @leahkeeler or @bradl3yC Is this product going to have a how to wizard associated with it? 
- @leahkeeler Can you provide for us an updated launch date? Thanks in advance

**Comment by bradl3yC** [comment]
@jonwehausen tagging in @craigwheeler for optics - no we do not have a submit callback yet.  To my knowledge, there will be a Wizard intro

**Comment by jonwehausen** [comment]
Thanks @bradl3yC! 

@craigwheeler If you could keep us posted on when a successful submission test may be available, and if there are specific test users needed that would be very much appreciated. In addition, please find our latest Data Layer Spec to support tracking of how to wizards here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md. Please let us know any questions you may have.

**Comment by leahkeeler** [comment]
We are targeting a mid March release - after sprint 42

Thee is a wizard that will be unauthenticated - we will like to track what URLs the Veterans are redirected to from that page (there are redirects to different parts of va.gov

**Comment by jonwehausen** [comment]
Thanks for this information @leahkeeler

**Comment by jonwehausen** [comment]
## Update
- (Slack correspondence)[https://dsva.slack.com/archives/CPE4AJ6Q0/p1614091094017600]
- FSR Wizard is slated for development next sprint
- Please reference (this documentation)[https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md] when setting up analytics for the how to wizard

**Comment by leahkeeler** [comment]
@jonwehausen Do i need to open up a different ticket for DOMO dash or can it be included in this ticket?

**Comment by leahkeeler** [comment]
Hi y'll - not to add complexity to already complex instrumentation but is it possible to get referring URL- ie are Veterans finding this from site navigation/search/search engine(s)  Thanks!

**Comment by jonwehausen** [comment]
Hi @leahkeeler ,

Apologies in advance for the delay here -- Yes if you could please open up a separate ticket for the DOMO dashboard that would be very much appreciated. 

For your recent question, we can certainly leverage Google Search Console along with our onsite search reporting to determine who is finding the app from search tools.

**Comment by jonwehausen** [comment]
@bradl3yC Could you confirm for me the up-to-date URL here and if our [wizard tracking spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md) has been implemented? 

Thanks so much in advance

**Comment by leahkeeler** [comment]
Hi @jonwehausen - I will open a DOMO ticket, Thanks! Sadly, Brad is no loner with us, @craigwheeler or @LinnJS will be your FE point of contacts on this product. Thanks! Leah

**Comment by jonwehausen** [comment]
Thanks for that information @leahkeeler !

@craigwheeler and/or @LinnJS Please see this comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16010#issuecomment-797734283

Would you be able to provide the latest staging URL link for this product? Also confirm whether forms library and how to wizard events have been implemented? 

Thanks in advance

**Comment by craigwheeler** [comment]
Hi @jonwehausen ... the staging url for FSR is https://staging.va.gov/manage-va-debt/request-debt-help-5655 and we're currently implementing analytics to the form this sprint so should be ready for you soon

**Comment by jonwehausen** [comment]
Great, thanks @craigwheeler !

**Comment by jonwehausen** [comment]
## Update
Hi @craigwheeler , 

Thank you for taking the time to read my note here. I have a couple updates for you: 

- In my latest testing of the form submission below, I did not see a `--submission-successful` (or `--submission-failed`) event per our standard forms library event taxonomy, would you have any initial reason for this? You can find our current non-production FSR events [here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22%5Efsr.*%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=50/)
- Also, it would be very much appreciated if we could implement analytics for the [How To Wizard according to this specification
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md)


Thanks again here. 
--------------------------------------------------------------


### QA Testing

| Description of Interaction | Data Layer | GTM Tagging | Test Status
| -- | -- | -- | -- |
Form Start - Starting application without logging in  | ![image](https://user-images.githubusercontent.com/48527022/113052079-b2630600-9174-11eb-8116-c26ca61be554.png) | ![image](https://user-images.githubusercontent.com/48527022/113052114-bee75e80-9174-11eb-84ab-a77ee0979068.png) | ✔️ **PASS**
Prefill failure | ![image](https://user-images.githubusercontent.com/48527022/113052198-d7f00f80-9174-11eb-9e5e-983ce9524869.png) | ![image](https://user-images.githubusercontent.com/48527022/113052242-e2aaa480-9174-11eb-82fa-6dbff3aa7e21.png) | ✔️ **PASS**
Form Saves - Event is triggered for auto form saves (also click tested to save) | ![image](https://user-images.githubusercontent.com/48527022/113052377-0bcb3500-9175-11eb-9da8-c271515dae43.png) | ![image](https://user-images.githubusercontent.com/48527022/113052424-1ab1e780-9175-11eb-8432-c4c2c37e13dc.png) | ✔️ **PASS**
Clicked to continue application after save | ![image](https://user-images.githubusercontent.com/48527022/113052502-37e6b600-9175-11eb-9d05-931593f349f0.png) | ![image](https://user-images.githubusercontent.com/48527022/113052541-4634d200-9175-11eb-9bae-aa59fee621bf.png) | ✔️ **PASS**
Form Submission | ![image](https://user-images.githubusercontent.com/48527022/113052942-be9b9300-9175-11eb-9835-5dfcbff66070.png) | ![image](https://user-images.githubusercontent.com/48527022/113052991-cce9af00-9175-11eb-9856-820377cb8b70.png) | ✔️ **PASS**
Successful Form Submission | _Did not fire event_ | _no event fired_ | ⚠️ **DOES NOT PASS**
Failed Form Submission | _Did not fire event_ | _no event fired_ | ⚠️ **DOES NOT PASS**

**Comment by craigwheeler** [comment]
Hi @jonwehausen I believe there is still some work ongoing with the form submission that maybe affecting this so ill have to look into it once changes have been completed and get back to you if its still failing. Also, ill make sure to implement the wizard analytics according to this most recent specification ... thanks for the update

**Comment by jonwehausen** [comment]
Thanks @craigwheeler! Would you be able to provide an eta of when we should expect the wizard specification to be implemented? Thanks in advance 

_I've reopened this ticket for my visibility but have unassigned you all_

**Comment by craigwheeler** [comment]
Hi @jonwehausen sorry bout that meant to move the ticket to verify and closed in error.. analytics changes have been merged for the Wizard and the form should now be submitting if you would like to verify it should be gtg :thumbsup:

**Comment by jonwehausen** [comment]
Great! Thanks for the quick reply @craigwheeler , we will start this QA ASAP.

**Comment by jonwehausen** [comment]
### How To Wizard Testing

#### Context/Notes
- Events for video tracking, start over, and skip functionality were not implemented with this not being a feature of this FSR wizard
- Testing was executed in accordance with documented spec [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-how-to-wizards.md)

----------------------------


#### QA Results
| Description of Interaction | Data Layer Specification | GTM Tag Screenshot | Test Status
| -- | -- | -- | -- | 
Click on radio button selection for wizard | ![image](https://user-images.githubusercontent.com/48527022/113731259-a1f7e180-96c6-11eb-968e-898ca3866b71.png) | ![image](https://user-images.githubusercontent.com/48527022/113731307-ac19e000-96c6-11eb-8ec5-564dc9d60247.png) | ✔️ **PASS**
Alert displayed following selection of radio button | ![image](https://user-images.githubusercontent.com/48527022/113731499-d79cca80-96c6-11eb-98b7-01e79b54d201.png) | ![image](https://user-images.githubusercontent.com/48527022/113731539-df5c6f00-96c6-11eb-931b-cb3d75ff6526.png) | ✔️ **PASS** -- @craigwheeler @LinnJS _just noticing there's a small typo within the datalayer for `reason-for-alert` with an extra `e` in `related`_ (see screenshot) 
Second alert displayed following seleciton of radio button | ![image](https://user-images.githubusercontent.com/48527022/113731870-1d599300-96c7-11eb-9fca-2b5fea3c0ef9.png) | ![image](https://user-images.githubusercontent.com/48527022/113731963-319d9000-96c7-11eb-93ee-4db6517e2aab.png) | ✔️ **PASS**
Second click on radio button in wizard sequence | ![image](https://user-images.githubusercontent.com/48527022/113732204-63165b80-96c7-11eb-902e-1cacb2dc6e73.png) | ![image](https://user-images.githubusercontent.com/48527022/113732254-6e698700-96c7-11eb-84e0-c5036f95bdd8.png) | ✔️ **PASS** 
Third click on radio button in wizard sequence | ![image](https://user-images.githubusercontent.com/48527022/113732365-87723800-96c7-11eb-9345-d780acf1e0ac.png) | ![image](https://user-images.githubusercontent.com/48527022/113732481-a244ac80-96c7-11eb-9109-8e45e9ecb039.png) | ✔️ **PASS** 
CTA to begin funnel is displayed | ![image](https://user-images.githubusercontent.com/48527022/113732723-d1f3b480-96c7-11eb-8225-3d525c91dc94.png) | ![image](https://user-images.githubusercontent.com/48527022/113732758-de780d00-96c7-11eb-9ea5-e27b5e5c45ad.png) | ✔️ **PASS**
CTA Button click | ![image](https://user-images.githubusercontent.com/48527022/113733278-4e869300-96c8-11eb-9a9f-379fc818dc58.png) | ![image](https://user-images.githubusercontent.com/48527022/113733323-59d9be80-96c8-11eb-8b38-f848c8c84e0f.png) | ✔️ **PASS** 


### Next Steps
- @craigwheeler There are no GTM changes necessary on our part prior before launch. 
- We would just like to verify `--submission-successful` and `--submission-failed` events when submission have been fixed within staging. 
- Supply a few GA links of submissions and wizard events

**Comment by craigwheeler** [comment]
@jonwehausen form submission work was just completed recently so i'll open up a ticket to follow up on successful / failed submissions along with a fix for the `reason-for-alert` typo and get those changes merged in soon

**Comment by jonwehausen** [comment]
Any update on this here @craigwheeler ? Thanks so much.

**Comment by leahkeeler** [comment]
@craigwheeler - are you creating another ticket? is this good to close ?

**Comment by jonwehausen** [comment]
### Update
- Connected with Craig over Slack 4/22 and he confirmed there are currently issues with submissions
- Goal is to have those cleaned up and finalize testing next week pending Craigs confirmation of submissions being available.

**Comment by jonwehausen** [comment]
We are able to see `--submission-successful` events within [GA Non-Production](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22%5Efsr-*%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath). 

Also confirmed `reason-for-alert` DL variable within How to Wizard has been corrected. 

![image](https://user-images.githubusercontent.com/48527022/117904253-01857600-b29f-11eb-917e-34bf662ae0a8.png)


@craigwheeler Closing this here. Thank you for you and your teams work.
