### ISSUE TITLE
Push Notifications -  API implementation

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#16026]
## User Story
As a user, I want to receive push notifications from VA. 

### VEText will power push
For this ticket, build VEText service and api into vets-api
- [x] Get API documentation from VEText
- [x] Build VEText service in vets-api

**Comment by srmyers17** [comment]
- Glue
- Creating new VEText service

**Comment by jjulian** [comment]
* There will be two VEText environments: TEST and PROD
* vets-api Staging <--> TEST (MVI SQA)
* vets-api Prod <--> PROD (MVI PROD)

**Comment by jjulian** [comment]
/mobile/push api is defined and work can begin on the FE portions of this ticket:
- prompt user to opt-in to push
- register with API
