### ISSUE TITLE
Bug: Add line break to TOC links so they don't look like one link on the same line

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#16028]
On this page https://www.va.gov/health-care/get-medical-records/ - there are 2 TOC links but they look merged without a line beak. See screenshot: 

 ![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/dab30807-a06b-4435-ad32-be633c1c2ca2)

Minor bug. ETA - anytime you have bandwidth.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @jenniferlee-dsva! @kelsonic, would you mind fixing this whenever you have a chance since it's in a react file? No rush. Thanks!

**Comment by RLHecht** [comment]
Validated on live site. Closing ticket. Thanks for the fix @kelsonic
