### ISSUE TITLE
Use request limit check when determining which Express Care window to use: back-end 

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#16029]
Currently, when choosing an Express Care window to display to a user, we choose the open window at the facility closest to a users's home address. Then later when check to see if they're over the request limit.

The intent of the Express Care section on the homepage was actually to:

- Find any open windows at facilities a Veteran is registered at
- Filter out any where the Veteran is over the request limit
- Sort the remaining windows by distance from home address and use the closest one

We should be able to do this efficiently now that we can request multiple facilities at once from the limits endpoint: https://issues.mobilehealth.va.gov/browse/VAOSR-1023

It seems that we should be able to pass multiple `institution-code` params in and do one request limits call for multiple facilities. We may need a vets-api change to allow this to work.

Acceptance criteria:
- [ ] Update the vets-api limit service to accept multiple institution code parameters

**Comment by grossb1** [comment]
The front-end work is represented here: #18970
