### ISSUE TITLE
No letters screen (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16035]
## User story
As a user, I want a page that tells me if I don't have any letters available to view.

## Acceptance Criteria
1. When the letters API does not return any letters for a user, the letters list page displays the associated UI
2. Hard-coded copy
3. Phone number with click-to-call capability

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/434420520/preview#project_console
This replaces the Letters list page: https://adhoc.invisionapp.com/d/main#/console/20546460/431636879/preview#project_console

## Accessibility Implementation Guidelines 
- Back button in top left
     - accessibilityLabel = "back"
     - accessibilityHint = “Go back to the letters landing page"
     - accessibilityRole = “button”
- Mark "Letters" as Header 1
- Mark "We weren't able to find information about your VA letters" as Header 2

**Link**
- Icon
     - Title= “phone icon” 
     - accessibilityRole= “image”
 - Link
     - Title= "800-827-1000"
     - accessibilityHint = “Dials this number via your device’s call function”
     - accessibilityRole= “link” 

## Dev Checklist 
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
@keli13 - Is there a user who has no letters available that I can test this one on?

**Comment by digitalken** [comment]
Going to have to test this one without mock data.

**Comment by esther-k** [comment]
**12/16**
UI and functionality pass on iOS and Android. Accessibility fails with [keyboard bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17008). Moving to Design QA
