### ISSUE TITLE
Community care provider - remove selection

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16038]
## Issue Description
As a user, I would like the ability to remove my preferred provider selection so that I can make changes to my provider preferences

---

## Acceptance Criteria

- [x] Update is behind VA Online Scheduling Provider Selection feature flag

- [x] Given a provider is selected, When user clicks/taps Remove provider, Then the preferred provider is removed AND returns to default options (add or no preference)
- [ ] DESIGN - All ~~desktop,~~ tablet, and mobile designs match the specs:
* [Mobile](https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/438169288)
* [Tablet](https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/438300059)
Note: this uses the standard components/styles for modal, buttons etc.

**Comment by outerpress** [comment]
Working spec for the modal that shows up after remove is clicked. This'll use the standard modal component. Need to check the spacing on this one:
![VAOS-CC-MVP-04-ConfRemove.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/850c7d85-bbc4-40e7-9efd-d23610a0255a)

**Comment by outerpress** [comment]
@laurenernest @vbahinwillit I added links in the description to specs that show general layout for reference. This should use the standard modal/button/header styles and components. If you need more detail, let me know.

**Comment by laurenernest** [comment]
@jbalboni @LanceGundersen Just want to confirm that this ticket can be worked on in conjunction with #15653

**Comment by jbalboni** [comment]
@laurenernest It would need to wait for  #15653 to be complete
