### ISSUE TITLE
Update Escalation Playbook

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#16036]

**Comment by laurenernest** [comment]
@grossb1 do we still need this shell?

**Comment by ldelacosta** [comment]
@simiadebowale - Do we still need to have this ready in the near future?

**Comment by simiadebowale** [comment]
@ldelacosta Ideally, we would want this to be completed before going live, especially if we run into any production issues. This will be blocked by #16037 though.

**Comment by simiadebowale** [comment]
@ldelacosta this is the current escalation process: https://docs.google.com/document/d/1hy-OVjp79AyKKbJXFuiCc6Fh8TLnXph7ebsU7gQYJXc/edit

**Comment by ajmagdub** [comment]
Updated the Github [appointments application monitoring](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/engineering/application-monitoring) and [incident repsonse](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/engineering/incident_response) pages.

Specifically added the Datadog URLs I use to diagnose problems: [monitoring urls](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/application-monitoring/monitoring-urls.md)

**Comment by ldelacosta** [comment]
This ticket is complete. Adding @simiadebowale @cferris32 @ryanshaw for awareness. cc: @JRRoof
