### ISSUE TITLE
Sync with On Call Team on Pager Duty Escalation procedures

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#16037]

**Comment by laurenernest** [comment]
@grossb1 is this shell still needed?

**Comment by ldelacosta** [comment]
@JRRoof @simiadebowale - do we think this is something we need to implement in the near future, or can I close this ticket shell?

**Comment by simiadebowale** [comment]
@ldelacosta I haven't had a chance to do this so I think I need to sync with the on call Team. We can leave this ticket open till I complete this task.

**Comment by simiadebowale** [comment]
To get a PagerDuty account, we need to create a ticket with DOTS via => https://vajira.max.gov/servicedesk/customer/portal/1 (CAG access required)

https://vfs.atlassian.net/wiki/spaces/KB/pages/1940127903/PagerDuty+Account+Requests
https://vfs.atlassian.net/wiki/spaces/AP/pages/2263351592/Escalation+process

**Comment by JRRoof** [comment]
My request to get access to those URLs in Confluence was denied:

**Comment by ldelacosta** [comment]
@simiadebowale - are we all set up with this? If yes, can I close it out?

**Comment by simiadebowale** [comment]
@ldelacosta - yes, this ticket can be closed. Thank you.
