### ISSUE TITLE
Common component: Add to Calendar button

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16046]
## Acceptance Criteria
1. Create "Add to Calendar" hyperlink with a calendar icon displayed to its left
     - This is a variation of the **Small Button (icon with text)** CC. See [this story](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15626) for details. 
2. Selecting this button will launch the phone's default calendar app
3. Calendar app opens with a new event populated

Note: this button will be used throughout the Appointments detail pages

## Designs
Example on Appts detail page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432457680

**Comment by komaly15** [comment]
Note: if the user turns off calendar permissions in their settings for ios, as of now the link will not do anything. This will be handled in another story once UI/UX is finalized for this case

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Pass 11/30/2020 - Not yet in iOS build but testrail is set for retest when it becomes available. Moving to design QA.
