### ISSUE TITLE
[Bug] HLR - IE11 - Contested issues - Same office alert - styling mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#16045]
## What happened?
On Staging **Request a Higher-Level Review** Contested issues page, in **IE11**, same-office alert didn't match design prototype.

## Specs:
- Devices: Windows 10 PC, Samsung S9
- Browsers: IE11, Samsung Internet
- Test User _(if applicable)_: 'vetsgov+test236@id.me`

## Steps to Reproduce
1. Go to https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction
1. IF **Is this the form I need?** section (eligibility wizard) is displayed, click **Disability...**, **No**, then **Request...**.  Browser replaces widget content with sign-in alert and regular intro content.
1. In **sign-in** alert, click **Sign in...**, and sign-in as **`vetsgov+test236@id.me` (Charde)**.  [See [this doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.docx) for credentials.]
1. IF **application-in-progress** alert is displayed, click **Continue...**.
1. Click **Back** or **Continue** to go to **Step 2 of 4: Contested issues** page.
1. Select (check) **If possible... same office** checkbox -- checkbox should be filled-in -- and observe that **We will try...** alert-box extends to right-hand-side page-edge.

**Screenshots**
![hlr-bug-ie-same-office](https://user-images.githubusercontent.com/587583/98744215-8f26ee00-236e-11eb-9183-21d2b70b0039.png)
![hlr-bug-s9-same-office](https://user-images.githubusercontent.com/587583/98748807-acac8580-2377-11eb-84dc-6b563645784e.png)

## Desired styling
**We will try...** alert-box should not extend beyond right-hand-side edge of text-column.  [See [design prototype](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/408129938).]
![hlr-spec-same-office](https://user-images.githubusercontent.com/587583/98744437-f04ec180-236e-11eb-879a-cb795dd20e96.png)

## Acceptance Criteria
[See **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
Hi Tze!

I've added a fix that sets the alert box wrapper to `100%` and this prevent the overflow problem we can see in the screenshots. I've verified that this fixes the problem in IE11 on staging. This fix will be available in production after 3pm ET today.

**Comment by Mottie** [comment]
Hi Tze!

We no longer have this alert on the page. In fact the same office checkbox is now on it's own page. Here is our updated design: https://vsateams.invisionapp.com/share/JHZTPGYBEYV#/screens/441615733

**Comment by tlei123** [comment]
Confirmed on Staging that alert's been replaced by verbage shown in above updated design.

Closing ticket now.
