### ISSUE TITLE
[Discovery] - Final artifacts for contact center/IRIS research study

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#16055]
Create artifacts for contact center content team research study:

- [x] map content authoring experience, highlighting details for each call center
- [x] oracle service cloud map, including content flow
- [x] capture teams, systems, audiences and content
- [ ] finalize "footnotes" / findings supplement

**Comment by andaleliz** [comment]
@jenniferlee-dsva (cc @bethpotts and @brianalloyd)

I have some artifacts ready for your review! I've put together some maps and info that I hope are easy to digest. 

[Contact Center Content Teams](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/134110801/simulate/sitemap?mode=i) and [authoring flow ](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/133990266/simulate/sitemap?mode=i) are represented in two maps, each with links that allow you to drill down to get more information.  A couple notes:
- the `content types` and `audiences` screens haven't been created yet.  Would like you to review the `software and systems` screen and let me know your impressions of that format. If it works for you, I'll do the same for content types and audiences
- the `team org chart` links are only active for HRC and DMC; again, interested in your feedback on the first two examples before I create the rest.

The [Oracle Service Cloud information](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/134076808/simulate/sitemap?mode=i) is also mapped out, with links to access a deeper level of info.

Still working on cleaning up the findings supplement document, but figure I can get your review on this while I work on that.  Thanks in advance for your feedback!

**Comment by andaleliz** [comment]
[Findings supplement ](# IRIS / Contact Center Research Findings Supplement 

**Digital Services Veterans Affairs (DSVA), VSA, Public Websites**

Liz Lantz (liz.lantz@adhocteam.us), November 2020

View the [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/contact-center-interviews-1-research-plan.md).

## Purpose

This document serves to supplement the [content team](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/134110801/simulate/sitemap?mode=i), [authoring flow](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/133990266/simulate/sitemap?mode=i), and [Oracle Service Cloud](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/134076808/simulate/sitemap?mode=i) maps created from the findings in our research study.

## Background 

The primary goals for this research study were to:

- Determine to the source of IRIS FAQs, and who has been managing/updating them.
- Understand how IRIS currently fits into each contact center's workflow
- Understand processes around Veteran-facing customer service content authoring and creation for contact centers.
- Understand processes around internal, agent-facing customer service content authoring and creation for contact centers.

## Research Methodology 

The preliminary round of research took place over Zoom. We conducted 1 hour remote interviews with teams at 6 contact centers. 

- Debt Management Center (DMC)
- Health Resource Center (HRC)
- National Cemetery Administration (NCA)
- National Call Center (NCC)
- Office of Care Coordination (OCC)
- Veterans Experience Office Tier 1 Contact Center (VEO)

[This overview of contact center teams](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/134110801/simulate/sitemap?mode=i) provides insight into the purpose of each call center and details about the teams we spoke with.

We also interviewed the team lead for Oracle Service Cloud, the platform IRIS runs on.

Our second round of research included email and Zoom follow-ups with the teams we previously talked to, as well as interviews with other contacts we were referred to.

The [complete list of research questions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/contact-center-interviews-1-research-plan.md#goals) can be found in our research plan.

## Key Findings

1. None of the contact center teams we spoke with publish or update IRIS FAQ content.
2. The contact center teams we spoke with are primarily authoring and managing internal content for contact center agents; most do not handle any external, Veteran-facing content.
3. Three of the teams have a dedicated content staff. Content management is an ancillary responsibility for the other 3 teams.
4. Only IRIS administrators can publish or update IRIS content. 
5. A new IRIS FAQs hasn't been added in at least 7 years, and a request to update an IRIS FAQ hasn't been submitted in at least 2 years.
6. One team (HRC) has a mature content management process with formalized routing and feedback/publication loops.
7. We identified 3 teams responsible for Oracle FAQs; this new responsibility was assigned to 2 teams as a result of the decision to retire the system.
   - NCC recently took ownership of the FAQs, and hasn't touched them.
   - The NCA external content team believes they *would* be responsible for these moving forward; no current owner of this content today. The NCA executive correspondence updated some NCA FAQs based on VA.gov content and then migrated them to KnowVA via eGain.
   - The Education, Client Applications team has always managed the GI Bill help desk FAQs, and has begun the process of migrating them to KnowVA.
8. Content governance is a pain point for teams across VA contact centers. We heard repeatedly that many teams struggle with tracking down SMEs to verify information, and that there is a sense of a lack of content ownership beyond the initial ask to have the content created.

## Supplemental Findings

Our interviews were incredibly informative, and not all of the information we gathered fit appropriately into our maps and flows. The information below captures supplemental details teams shared that may be of interest as our content governance processes evolve.

### Debt Management Center (DMC)

- Two divisions work with content:

  1. Veteran Experience Division (VED), focused on agent-facing customer support content.
     - This team does not have access to Oracle Service Cloud, or IRIS.
  2. Treasury, External Relations and Education Division, focused on external, public-facing content primarily targeted to Veteran Service Officers, School Certifying Officials, and Veterans.
     - This team does have access to Oracle Service Cloud and IRIS, and logs in daily to respond to IRIS inquiries. Pain point: Inability to include attachments when responding to IRIS inquiries.
     - They manage their own version of IRIS standard text in a Word document shared among the team. They call these "pattern paragraphs" and use them in email responses.
     - This division would be the main entry point into DMC. We'd be the point of contact for the FAQS to validate that the answers are correct and coordinate the team to draft/edit content. Since they don't really have a formal process, division chief would approve and put it out there.

- Neither of these divisions has a dedicated content team.

  > We truly don't have the resources to devote somebody to this type of work. It's collateral work for everybody that is doing it.

- VED team lead doesn't feel like there is a set process in place.

  > As we talk about it, I'm feeling like we're fragmented when it comes to our content.

- VED team works with members from the Internal Controls and Process Improvement Division, internally referred to as "Quality". 

  - This team is involved in the review and publication process. They review proposed content to ensure consistency, and that there aren't any discrepancies, redundancies, misinformation, etc. 

    > Our role has become trying to make sure that we give space for everyone to give some feedback, and make sure that all the interested parties know what is going on

  - This team also manages DMC's Sharepoint instance and publishes content once it's approved by division chiefs.

- DMC is rolling out a new debt portal in early 2021 that will replace va.gov/debtman.

  -  The treasury team is helping with the content transition to the new debt portal. 
  - They are currently not sure how any content publication processes will work, or how if the content will stay in the format it is in today (e.g. they have FAQs on the site, and are unsure whether or not it'll stay in an FAQ format)

- DMC is also in the process of implementing Veterans Account Management System (VAMS), which is a CRM based on Sales Force. 

  - Some of the teams "pattern paragraphs" (used to standardized agent email responses, DMC equivalent of IRIS standard text) have been moved from a shared drive into a VAMS feature called "S Docs". 
  - Eventually all of the pattern paragraphs will live in VAMS within the S Docs feature.

- DMC VED agents primaries provide phone support

- The Treasury, External Relations and Education Division handles Ask a Question IRIS inquiries. 

  - IRIS inquires that indicate the customer prefers a call back, or has missing email information will be routed to the VED team.

### National Call Center (NCC)

- One team member uses UI elements to make content easier for agents to use. His role is to publish internal content in eGain.
- Utilize internal templates as guides for content, but doesn't have a tone and voice style guide.
- We were not able to get answers to follow-up questions from this team before the conclusion of our research.

### Office of Community Care (OCC)

- Team leverages a variety of authoring guides during their process, including voice and tone, 508 compliance, and a peer review checklist

- Content team receives requests from 3 different areas of OCC: Community Care Contact Center (C4), Family Members (FM), and ChampVA.

  - They have designated contacts within C4 and FM who submit requests for content. They rely on these content owners to tell them when things have changed in order to keep their content in sync with VA.gov.
  - Those contacts act as liaisons to SMEs.

- The team heavily relies on VA.gov content for their agent-facing articles.

  > If you're giving me a resource I want to know the last date. We love that about the field guidebook and VA.gov - we can look in and see that it hasn't changed since that day.

- Has moved away from the term "scripts" - Agents prefer FAQs

- Has an upcoming initiative to re-do their taxonomy in the KM.

- Differentiates between knowledge articles and FAQs. Over time, FAQs get merged into knowledge articles.

  > FAQs are approved questions we expect people to ask. We rely on those for new things because it's easier for the CSR to see the question rather than navigate through blocks of text.

- Painpoints:

  - Don’t have a good way for routing. Requests come in via email, IM, hallway conversations, etc.
  - Business owners want to put things in the knowledge management system (intranet) that don’t belong there (e.g. IT info).
  - Heavy reliance on SMEs to verify content, and sometimes SMEs are unresponsive. 
  - Many times have to go back for additional info because it doesn’t make sense, the flow isn’t right, or there is contradictory information.
  - Lots of back and forth, waiting for approval. Timeliness is a problem. Sometimes  requester doesn’t have a response.

### Veteran Experience Office Tier 1 Contact Center (VEO)

This contact center handles calls that come in through 2 phone numbers:

- White House VA Hotline.
- VA311

> "We [VA311] provide general information. Agents have knowledge a mile wide, but an inch deep on all VA services."

The team members we spoke with are members of the training team responsible for training the call center agents. From a content perspective, their responsibility is to create and maintain internal training documentation. This documentation is created in the form of videos, power point presentations, and/or Visio documents.

This team wasn't familiar with IRIS or eGain. They "use their own Sales Force version of eGain", which they hope to move over to Microsoft Dynamics.

### National Cemetery Association (NCA)

We spoke with members of two teams:

1. The scheduling office, which has mostly static content that doesn't change much.  The team doesn't have anyone dedicated to content management, and is prioritizing a total overhaul of their content and training processes in 2021. 

   > No one is a writer/editor as a primary role. Everyone does these tasks as an ancillary responsibility. 
   >
   > Chaos. That's really the state we're in right now, for many reasons.

2. The executive correspondence team, which primarily authors individual correspondence in response to inquiries that come through IRIS and VIEWS
   - They rely heavily on VA.gov and other VA-approved content for their correspondence, which helps avoid delays caused by approval processes.
   - The team scrambled when IRIS was suddenly shut off. They evaluated their FAQs, updated as needed based VA.gov content, and moved all their IRIS FAQ content to KnowVA.

### Health Resource Center (HRC)

- This team has the most mature content management process of the contact centers we observed. 
- They leverage the LEAF system to manage review, approval, and publication of contet.
- The LEAF system has groups set up with specific individuals authorized to perform different actions in the content process. All members of the group are notified when that action takes place.
- The Member Services, Knowledge Management team supports HRC content in the form of drafting, editing, publishing and auditing. They also administer the LEAF system
  - KM System Liaison, Beki Lund, is incredibly knowledgable and helpful with all things LEAF, eGain, and KnowVA.

- Fields/metadata observed in LEAF request:
  - request number
  - article ID
  - doc type
  - initiated by
  - date
  - service (e.g. HRC)
  - existing or suggested article title 
  - suggested edit or change
  - last update
  - Audience
- Agents primary focus at HRC help desk is to answer phones. They rotate email duty w/ phone duty every 4-6 weeks.

### Oracle Service Cloud and IRIS 

- The IRIS FAQs we sought to understand are part of a platform called Oracle Service Cloud (OSvC), which was first implemented at the VA 20 years ago.
  - IRIS was launched in 2002 as an internal VA-hosted product, which they continued to do for a number of years.
  - Right Now Technologies took over the system from the VA - first data migration.
  - Oracle bought Right Now Technologies in 2011 - second data migration
- Originally, IRIS FAQs were created from a team with members from the 4 business lines at the VA.
- IRIS didn't have a single agency sponsor, so governance became a problem - nobody owned it.
  - We were hopeful that we could identify the original content authors through data logs, but that isn't possible since what we see in the system today reflects mass-data migrations that took place when the system changed hands. 
- The VA decided to retire OSvC and gave teams 30 days notice. DMC and other contact centers raised red flags since the Ask-A-Question feature is critical to a Veteran's ability to submit inquiries to the VA. This is particularly critical for Veterans who aren't able to place a call to a contact center. The timeline to retire OScV has been extended; update as of 10/26/2020 is that data migration will take place in Q4 2021.
- 6 IRIS workgroups were formed, containing contact center SMEs. 
  - Workgroups were focused on inquiry response and creating/managing cases. 
  - No workgroup was formed to address IRIS FAQs.
  - The OSvC administrator hasn't been part of the workgroups.
- The OSvC admins provided IRIS analytics that may be helpful in prioritizing migrating content to VA.gov.

### Education, Client Applications 

We interviewed Tammy Hurley, who manages the FAQs on gibill.custhelp.gov (GI Bill equivalent of IRIS), to gain insights into their content processes.

- The content management process is intentionally informal and flexible. Tammy strives to maintain consistency while being flexible with the way different folks like to work. Communication takes place primarily via email.
- Stakeholder engagement team are "the people telling us how to communicate all the policy and procedures. They come up with a communications plan". Terry Warren worked with the DMC team to create GI Bill specific content related to debt; could be a good contact for R&S content.
- This team doesn't leverage the workflow and analytics functionality in OSvC
- Tammy has been working on moving the GI Bill FAQs into eGain. Once they're migrated over, she'll figure out who will manage and own that information within Education services. They still don't know who that person would be. 

## Appendix

[Content team](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/134110801/simulate/sitemap?mode=i), [authoring flow](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/133990266/simulate/sitemap?mode=i), and [Oracle Service Cloud](https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/134076808/simulate/sitemap?mode=i) maps

[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/contact-center-interview-1-conversation-guide.md)

[Interview notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/preliminary%20interviews/notes)

[Mural boards used for synthesis available in README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/README.md)
) cleaned up.  @jenniferlee-dsva please review.

**Comment by andaleliz** [comment]
[Findings supplement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/research-findings-supplement.md) is also ready for review @jenniferlee-dsva 

Sorry about the crazy comment I just pinged you in - didn't realize I had the whole doc on my clipboard.

**Comment by jenniferlee-dsva** [comment]
I'll leave granular comments within uxpin, and larger overall feedback here in GH.

**Comment by jenniferlee-dsva** [comment]
Overall feedback for the Oracle Service Cloud journey - https://preview.uxpin.com/559c1f8fc9b065402b80c5a8c26262c8371b1295#/pages/134076808/simulate/sitemap?mode=i

I left very granular comments on the tool. Overall this looks great, and I found it very easy to understand the way you organized and summarized the info!

**Comment by jenniferlee-dsva** [comment]
Hi @andaleliz - for the contact center content teams' journey map, I left comments in the tool. Please also be sure to look at the comments on the overview page as well. 

In general looks good, with those areas I noted for clarifying. For me, the most important update for this journey map would be calling out that that journey is for internal content, and that we interviewed these teams with one assumption (that they create or maintain or use external customer facing content) and  that we learned as part of this effort that that assumption was not true.

**Comment by andaleliz** [comment]
@jenniferlee-dsva thanks for all the feedback! I added clarification throughout the doc and provided additional context via comments on a few more specific questions you had.

>the most important update for this journey map would be calling out that that journey is for internal content

Clarified this in the comments, but the external DMC team does deal with some external content. It's just not **customer support** content.  I updated the copy below the map to clarify this with examples.

> we interviewed these teams with one assumption (that they create or maintain or use external customer facing content) and that we learned as part of this effort that that assumption was not true.

Updated the teams and map pages with this information, and also added the audience and content pages.

Are there any changes you'd like to the supplement document? So excited to wrap this up!

**Comment by andaleliz** [comment]
Ack! Forgot about the remaining team org charts that need to be added. Will do that first thing Monday.

**Comment by andaleliz** [comment]
@jenniferlee-dsva All the org charts and outstanding pieces have been added to the UXPin.  I also added a key finding to the supplement doc:
>When IRIS FAQs were initially created in 2002, SMEs from the business lines were responsible for creating and maintaining the content.  All information available suggests that they created the original FAQ content, but did not do any further work on the FAQs after the initial creation.

I think it'd be good to send this to the participating teams for review and give them a chance to offer any corrections. I shared my flow/team org charts with those teams that granted follow-up meetings but I'm sure they'd all like to see it in this format. 
Thoughts?

**Comment by jenniferlee-dsva** [comment]
Hi Liz - Yes, a formal share out of the findings with participant teams would be great. 

In addition to the artifacts, please add a brief text summary (either in your email message or your presentation). Links to the 2 github files and to your UXPin artifact will be useful, but if you could also provide PDF'd versions to stakeholders, that would be even better. (Many of our VA partners do not have GitHub accounts, and I don't want them to feel like they have to create one just to see the findings.)

**Please include text summary:** 
We begin the research with an assumption that there was a team or teams creating and managing content in IRIS. The research findings did not bear out this assumption. 

Through user interviews with SMEs and contact center content team stakeholders, we learned 3 important facts: 
1/ There is no content team that is responsible for creating and managing IRIS FAQs. 
2/ Each contact center content team is responsible for creating and managing internal agent-facing content for a specific subset of benefits or products. 
3/ What people call "IRIS" is actually not 1 thing, but comprised of 2 public facing websites (IRIS FAQs and GI Bill Help), a web mail inquiry routing system, and an internal facing help/ticketing system for internal users. The software for all of these IRIS 'products' is Oracle Service Cloud. 

**Links to (and PDF'd into one doc):**

- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/research-findings-supplement.md#iris--contact-center-research-findings-supplement

-  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/iris/README.md

- And UX Pin (I understand this probably can't be PDF'd because of the interactivity. Maybe it can be PDF'd with a note to go online to see details??)

**Comment by andaleliz** [comment]
@jenniferlee-dsva "Formal share out" to me means a presentation - is that what you mean?  This isn't something I was planning on, was more thinking of emailing artifacts.  I have availability to do this Thursday before I leave, but I think we'll get a very low attendance rate given the short notice and incredibly busy schedules these teams have.

One correction to your write up - 3 isn't exactly right. No one that I spoke to calls the GI Bill Help desk IRIS. They're similar systems, run on the same platform and both have Answers (what we call FAQs).  But, they have different interfaces, urls, and teams that work on them. 

This is accurate:

>The platform for IRIS 'products is Oracle Service Cloud (OSvC), and there are 2 other similar, public-facing help desk websites that run on OSvC.  These websites, GI Bill Help and MHV Technical support both have an internal-facing system for internal VA users like IRIS, but only GI Bill Help has public-facing FAQs like IRIS.

I'm happy to send an email and PDF everything you requested, including the UXPin (Sketch easily exports to PDF).  I'll copy you and Chante on the email to the teams, and BCC everyone who was an interviewee.

I'll also ask them to let us know if anything related to their team has been miscaptured.

**Comment by jenniferlee-dsva** [comment]
> "Formal share out" to me means a presentation - is that what you mean? 

Sorry - no, I just meant sending all the participants an official - here are the research findings, thank you email.

**Comment by jenniferlee-dsva** [comment]
WRT #3 correction - I was trying to keep things simple enough to grok quickly. The main point being that "IRIS" is not just the web mail inquiry and not just the FAQs. 

Is it still valid to simplify it as: 

> The platform for IRIS 'products' is Oracle Service Cloud (OSvC). The IRIS OSvC products include: the GI Bill Help, MHV Technical support, IRIS FAQs, web mail inquiry routing system, and an internal-facing system for internal VA users.

**Comment by andaleliz** [comment]
I don't think so - IRIS is a totally separate thing. GI Bill Help and MHV are not IRIS products, they're OSvC products just like IRIS. I think of them as siblings.  I think if we want to simplify the point you're trying to make, we could just say:

> IRIS is not a stand-alone system. Rather, it is part of a larger platform, Oracle Service Cloud, that includes similar help-desk interfaces: the GI Bill Help Desk, MHV Technical support, and an internal-facing system for internal VA users.

Not sure if you caught this link in the docs I created, but it may be helpful to understand how it's all connected: https://va-osvchelpdesk.custhelp.va.gov/app/answers/detail/a_id/3

**Comment by andaleliz** [comment]
@jenniferlee-dsva here's the email I'm planning to send. Feel like I should share with you to be sure we are aligned in our communication. The links in the bulleted list aren't live but I'll link them accordingly

----

I’d like to start by thanking each of you for taking the time to participate in our research study. We know you all have multiple priorities and busy schedules, and we greatly appreciate the time you took to help us understand the content processes you’re involved with.

 

We gathered a wealth of information, thanks to you. We began the research with an assumption that there was a team or teams creating and managing content in IRIS. The research findings did not bear out this assumption.

 

Through user interviews with SMEs and contact center content team stakeholders, we learned 3 important facts:

1. There is no single content team that is responsible for creating and managing IRIS FAQs. There are teams at some contact centers who would be responsible for their benefit-specific content in the future.

2. Each contact center content team is responsible for creating and managing internal agent-facing content for a specific subset of benefits or products.

3. IRIS is not a stand-alone system. Rather, it is part of a larger platform, Oracle Service Cloud, that includes similar help-desk interfaces: the GI Bill Help Desk, MHV Technical support, and an internal-facing system for internal VA users.

 

We have collection of artifacts as a result of this research in our GitHub repo and in UXPin, an online tool we use for design files.  I’ll provide links below, but have also attached everything in a PDF for your review.  You shouldn’t need to create an account to review any of the content online.

Research study overview
Contact center teams overview
Contact center authoring flow for internal content
Oracle Service Cloud Overview
Research findings supplement
 

If you find any errors in the data related to your specific team, please let our team know and we’ll fix it as soon as possible.   

Again, thank you for your participation in our study. Our team will be in touch as appropriate to provide further updates on the new resources and support section of VA.gov.

**Comment by jenniferlee-dsva** [comment]
>Not sure if you caught this link in the docs I created, but it may be helpful to understand how it's all connected: https://va-osvchelpdesk.custhelp.va.gov/app/answers/detail/a_id/3

I did previously, after your first session with Michelle. I think we're saying the same thing, different ways. What you have above is fine, but I would like to edit #1: 

1. There is no single content team that is responsible for creating and managing IRIS FAQs. ~There are teams at some contact centers who would be responsible for their benefit-specific content in the future.~

**Comment by andaleliz** [comment]
Sent email to teams - closing out
