### ISSUE TITLE
SEO Strategy for Vet Center pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16069]
## Problem Statement(s)

- Awareness about Vet Centers and their services is quite low among Veterans. 
- Vet Centers are often confused with VA Medical Centers. 
- Veterans searching for services are unlikely to find Vet Centers, their outstations, or community access points among the results. 

## Areas of emphasis for SEO

- Locations (and types of locations: CAP vs outstation vs Vet Center) 
- Services offered 

## Next steps 

next thing to do here would be to create issues for piloting the Schema.org stuff as part of this epic.

## Resources
[Understand how structured data works (Google)](https://developers.google.com/search/docs/guides/intro-structured-data)
[Types of results](https://developers.google.com/search/docs/guides/search-gallery)

## Questions
As we build out the first 10 Vet Center sites...
- How do we leverage How can we leverage schema.org and the CMS content to improve findability and create Google rich search results?
- Can content "hidden" within accordions be used to improve SEO?

We can use our work for Vet Centers to inform a similar effort for VAMCs

**Comment by mmiddaugh** [comment]
Notes from a conversation with @1Copenut and @lildziner 

- Json LD can be used for snippets of text to create meta-data to enhance SEO 
- Use key words from appropriate Schema.org dictionary
- Trevor made a recommendation to the design system to [add a structured data component to address blocks](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/243)
- Need to find out if content which is "hidden" within accordions (ie: `Common conditions` and `Description` content) can be leveraged
   - If not, MVP could focus on surface level words in the `Service (ie: Cardiology)` and `Patient-friendly (ie: Heart and circulation)` names from Service taxonomy

**Comment by mmiddaugh** [comment]
SEO request issue for Analytics team #16566

**Comment by davidconlon** [comment]
next thing to do here would be to create issues for piloting the Schema.org stuff as part of this epic.
