### ISSUE TITLE
Missing section - /find-forms/about-form-va4107/index.html

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#16071]
## Issue Description
There is a missing section in `/find-forms/about-form-va4107/index.html`.

## Example:
<img width="1609" alt="Screen Shot 2020-11-11 at 7 41 00 PM" src="https://user-images.githubusercontent.com/9042882/98892791-e5229100-2455-11eb-98d5-878d3f0e0416.png">

## Example File
`/find-forms/about-form-va4107/index.html`

## Tasks
- [ ] Figure out why the section is missing.
- [ ] Fix the issue

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
