### ISSUE TITLE
Extra divs - /life-insurance/options-eligibility/vgli/index.html

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#16073]
## Issue Description
There are extra `div`s in `/life-insurance/options-eligibility/vgli/index.html`.

## Example:
<img width="1609" alt="Screen Shot 2020-11-11 at 8 00 23 PM" src="https://user-images.githubusercontent.com/9042882/98893974-8dd1f000-2458-11eb-9c62-fe212884e9f5.png">

## Example File
`/life-insurance/options-eligibility/vgli/index.html`

## Tasks
- [ ] Figure out why there are extra `div`s.
- [ ] Fix the issue

**Comment by jhonnyoddball** [comment]
Fix on PR [15088](https://github.com/department-of-veterans-affairs/vets-website/pull/15088)
