### ISSUE TITLE
Wrong href - /health-care/get-reimbursed-for-travel-pay/index.html

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#16072]
## Issue Description
There `href` for a download link is incorrect in `/health-care/get-reimbursed-for-travel-pay/index.html`.

## Example:
<img width="1609" alt="Screen Shot 2020-11-11 at 7 54 07 PM" src="https://user-images.githubusercontent.com/9042882/98893630-ae4d7a80-2457-11eb-84d1-a92581da4144.png">

## Example File
`/health-care/get-reimbursed-for-travel-pay/index.html`

## Tasks
- [ ] Figure out why the href is incorrect.
- [ ] Fix the issue

**Comment by jhonnyoddball** [comment]
Fix on PR [14989](https://github.com/department-of-veterans-affairs/vets-website/pull/14989)
