### ISSUE TITLE
Wrongly ordered metatags - /outreach-and-events/events/..

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#16074]
## Issue Description
There is a metatag that is out of order in `/outreach-and-events/events/pave-connect-employer-session-amazon-entry-level-and-hourly-jobs/index.html` and `/outreach-and-events/events/va-caregiver-support-program-expansion/index.html`.

The same issue is causing the discrepancy in both of these. Not that this should make a difference in the rendering since all the metatags are there, but maybe we can figure out how to make the ordering consistent.

## Examples:
`/outreach-and-events/events/pave-connect-employer-session-amazon-entry-level-and-hourly-jobs/index.html`

<img width="1609" alt="Screen Shot 2020-11-11 at 8 12 03 PM" src="https://user-images.githubusercontent.com/9042882/98894695-316fd000-245a-11eb-96cc-ea440dac38a8.png">

`/outreach-and-events/events/va-caregiver-support-program-expansion/index.html`
<img width="1609" alt="Screen Shot 2020-11-11 at 8 16 24 PM" src="https://user-images.githubusercontent.com/9042882/98894997-e3a79780-245a-11eb-8456-11e8ec2966d1.png">

## Example Files
`/outreach-and-events/events/pave-connect-employer-session-amazon-entry-level-and-hourly-jobs/index.html`
`/outreach-and-events/events/va-caregiver-support-program-expansion/index.html`

## Tasks
- [ ] Figure out why the metatags are out of order.
- [ ] Fix the issue

**Comment by theodur** [comment]
The CMS export seems to have a different `field_date` value than the one pulled from the GraphQL build for the entity `node.d3542034-12c4-4337-89e4-5a29ef3cc1dd.json`. This is the only entity that has a discrepancy with `fieldDate`, which leads me to think this may be a bug in the CMS export.  @indytechcook do you know if this is a bug in the CMS export?

E.g.

GraphQL: 
```javascript
"fieldDate": {
        "startDate": "2020-11-19 19:00:00 UTC",
        "value": "2020-11-19T19:00:00",
        "endDate": "2020-11-19 20:00:00 UTC",
        "endValue": "2020-11-19T20:00:00"
    }
```

CMS Export: 
```javascript
"fieldDate": {
        "startDate": "2020-11-19 14:00:00 UTC",
        "value": "2020-11-19T14:00:00",
        "endDate": "2020-11-19 15:00:00 UTC",
        "endValue": "2020-11-19T15:00:00"
    }
```

node.d3542034-12c4-4337-89e4-5a29ef3cc1dd.json:
```javascript
...
"field_date": [
        {
            "value": "2020-11-19T14:00:00-05:00",
            "end_value": "2020-11-19T15:00:00-05:00"
        }
    ]
...
```

**Comment by indytechcook** [comment]
@theodur not that I know of.  Is this something you have just noticed?

**Comment by indytechcook** [comment]
@theodur recently `field_datetime_range_timezone` was added to replace `field_date`.  I haven't looked at that node json yet but I assume the transformer needs to be updated to use `field_datetime_range_timezone` instead of `field_date`.  The new field adds the ability to add timezones.  I know the frontend templates are already using the new field.

**Comment by theodur** [comment]
@indytechcook Thanks for confirming! I'll make the appropriate changes to the transformer.

**Comment by indytechcook** [comment]
Also, sorry for not informing you before.  There is so much going on I lost track :(

**Comment by theodur** [comment]
No worries!

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/15010.
