### ISSUE TITLE
Review FSR intro page content

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16082]
## Issue Description
Danielle to review FSR intro page content and provide edits.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @3obryandogs. Here are my edits/comments on the FSR intro page. Since you're working directly with the team, please of course work with them on anything that needs to change based on research, etc. And feel free to reach out with any questions.

FYSA @peggygannon @leahkeeler 

[How to Complete Financial Status Report.pgedits_dt edits](https://app.zenhub.com/files/133843125/a07f24d6-719c-4098-8405-28e1ca3f8f86/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @3obryandogs Just making sure you received this? Thanks.

**Comment by 3obryandogs** [comment]
Yes, thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
