### ISSUE TITLE
[FE] Analytics data-layer implementation: Add error codes for address save failures to GA dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#16088]
## Background

In #15237, we have been talking about adding the error codes for when addresses fail to save to the GA dashboard we use to track address validation. This should give us better insight into why we have seen so many failures in saving mailing/home addresses in the last couple of months. We suspect this is due to MPI issues, but this will help us to confirm.

In order to get this, we need to add the following to the data layer [from this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15237#issuecomment-725533501):

When the veteran clicks 'Add' or 'Edit' and an unexpected error occurs on the `/profile/personal-information` page (the errors could occur on address updates or phone number updates) 
![image](https://user-images.githubusercontent.com/66263904/98839389-b4653c00-2402-11eb-8aaf-95bce9f76579.png)
```javascript
dataLayer.push({
  'event': 'profile-edit-failure',
  'profile-action': 'address-suggestion-failure',
  'profile-section': 'home-address' //or 'mailing-address'
  'error-key: 'other-error-enroll', //dynamically pass in the values from Sentry
});
```
**Additional Dev Notes**
There is already a `profile-edit-failure` event being fired when an unexpected error occurs on the `/profile/personal-information` page. The main change to the current dataLayer push is that `error-key` needs to be added.

## Tasks

- [ ] Make data layer update
- [ ] Let @bmcgrady-ep know when the updates have been made in #15237

**Comment by erikphansen** [comment]
Thanks for the `additional dev notes` in this ticket. It's always super helpful to know exactly what changes in functionality are needed.

**Question: can the value of `error-key` be any string or will GA only expect particular values?**

I do suspect, based on [the Grafana dashboard Anna shared (must be on the SOCKS proxy to view)](http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?from=now-7d&orgId=1&to=now&viewPanel=12&var-data_source=Prometheus%20(Production)&var-backend_controller=v0%2Fprofile%2Faddresses&var-frontend_app=All), that we are going to see a _dramatic_ reduction in these errors and that the bulk of the save errors were due to users not being properly initialized into VA Profile.

**Comment by erikphansen** [comment]
OMG I just saw the post in Slack showing we are still seeing a ton of these errors in GA. 😱 So maybe ignore my last paragraph above.

**Comment by Samara-Strauss** [comment]
> Question: can the value of error-key be any string or will GA only expect particular values?

I believe it can be any string, but not 100% sure. @bmcgrady-ep can you give a definitive answer to Erik's question?

**Comment by bmcgrady-ep** [comment]
@erikphansen @Samara-Strauss - Yes, Samara is correct, it can be any string. This is how the errors are currently coming into the error key for Direct Deposit errors: 
![image](https://user-images.githubusercontent.com/66263904/98983505-1646a400-24de-11eb-94b9-62dfedec0ba7.png)

**Comment by sanlouise** [comment]
@bmcgrady-ep The PR linked to this ticket was merged, so you should be able to see the new error keys after today's deploy 😄

**Comment by Samara-Strauss** [comment]
Great, thank you! I'll look for the error codes later today.

**Comment by Samara-Strauss** [comment]
Reopening this. I am still largely seeing "undefined" errors, which isn't helpful to us. @sanlouise any thoughts?

<img width="711" alt="Screen Shot 2020-11-30 at 9 37 18 AM" src="https://user-images.githubusercontent.com/34068740/100623107-b29ae400-32ef-11eb-9914-25de4406b15c.png">

**Comment by Samara-Strauss** [comment]
Gonna close and move this convo to #15237

**Comment by erikphansen** [comment]
@Samara-Strauss #15237 is for Direct Deposit analytics, not Address analytics.
