### ISSUE TITLE
Staging Review BAM2 Debt Letters Iteration 2 <Draft> 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#16083]
## Steps to complete Staging Review: 

- [ ] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] Attach all artifacts before requesting the meeting
- [ ] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] Staging Review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on **feature name**
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts at least 2 days before scheduled review meeting_
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Access information for the tool or feature in staging _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
- Link to your product [test cases](https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_order=asc&group_id=168)/[test plan](https://dsvavsp.testrail.io/index.php?/plans/view/682) in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/151) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/150) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)

## Meeting attendees from **BAM2*
- Product Manager (required): **Leah Keeler**
- DEPO product lead (required): **Matt Self **
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Brad, Craig, Becca, Riley**

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and shira will reach out as needed_

## Additional Notes
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: product, analytics, engineering, information architecture

**Comment by tlei123** [comment]
@leahkeeler fyi, I'm planning to have QA test-runs completed by end of tmrw (Fri 13th), so QA artifacts for Stg Rvw should be available for @pjhill around Mon 16th (around Noon ET).

**Comment by shiragoodman** [comment]
hey @leahkeeler - when you're ready to schedule, please comment here and tag me or else I won't see the update. thanks!

**Comment by tlei123** [comment]
Sorry, @pjhill !  Slight delay in completing test-runs -- waiting on a back-end/API fix right now to restore the bebt-list.

If page is restored successfully today, then I should have QA artifacts ready for you tmrw (Tue).

cc @leahkeeler

**Comment by tlei123** [comment]
@pjhill , all QA test-runs now completed (including automated E2E tests) -- QA-artifact links added/updated above in main Description.

cc @leahkeeler @shiragoodman

**Comment by shiragoodman** [comment]
@leahkeeler can this be closed? looks like the real ticket is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16535

**Comment by leahkeeler** [comment]
better late then never - closing ticket :)
