### ISSUE TITLE
Discovery: Community Care Appointments Data

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1608]
## Story
As a developer, I want to understand which service(s) Community Care appointment data comes from, what data fields are available, and any business rules surrounding this appointment type so that I can build a front end and service layer that will allow veterans to easily see all of their community care appointments & details.

## AC
- [x] Documentation on how to get confirmed & pending CC appointment data (both past and future) for a given veteran exists in GH
- [x] Any associated business logic (e.g., filtering that's required to get to the CC data) documented in GH

**Comment by jbalboni** [comment]
Updated notes doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/engineering/Community%20Care%20notes.md

We will have example requests and appointments in our mock data once we can access VAOS again, which in addition to the notes should cover the existing CC data.
