### ISSUE TITLE
[Design] CC provider selection when no address on file

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16093]
## Request
D/T/M specs for community care provider preference page that accounts for users coming through the flow who don't have a home address in their profile.

## Background
As part of the community care provider selection initiative, users who have a home address in their profile get the new provider list version of the preferences page, and users who don't have a home address in their profile get the original manual preference version.

When we move to using the new VAMF vaos service endpoints (#14091), we will not be able to send provider information as text (as collected in the original preference version).

## Requirements
- Users in the community care request flow can choose a preferred provider
- Users in the community care request flow are not required to choose a preferred provider
- Users can sort the provider list by current location
- Sort by current location is not a default option

## Scenarios
- If any user on provider preference list page, Then show dropdown with sort options
  - If user has home address in profile, Then sort options include: home address, current location
  - If user doesn't have home address in profile, Then sort options include: parent site city/state, current location
- If user has home address in profile, Then default sort by distance from address
- If user doesn't have home address in profile, Then default sort by parent site city/state
- If user selects sort by location AND it's blocked by browser, Then display message (with same click to retry behavior as facilities?)

## Design assets
- [x] [Overview - dropdown](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/a/EL98PER#Inspector)
- [x] [Dropdown sorting selector states](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/a/QbrLaqY)

Specs
- [x] [Mobile](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/a/Kvwjd8g#Inspector)
- [x] [Tablet](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/v/akdEVZ/a/wLMWGYq/r/ovlW73#Inspector)
- [x] [Desktop](https://www.sketch.com/s/f97eb709-584d-4d37-a111-485828bcfafc/v/akdEVZ/a/qe5Wzy2/r/ovlW73#Inspector)

**Comment by outerpress** [comment]
@laurenernest Here's one approach - allow users to enter a city, state, or zip code manually and search based on that, similar to Facility Locator.

- Default: https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/438121106
- List loaded: https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/439895568

Screenshots for reference:

| ![VAOS-CC-MVP-02-NoAddr.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/aeec6f1b-fec3-4883-86aa-8b90592e4dc2)      | ![VAOS-CC-MVP-02-NoAddr2.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/e2ec85d3-70fa-40ad-b34d-40cec5ad27a1)       |

**Comment by laurenernest** [comment]
@jbalboni Thoughts on the approach above? Do we have any of this kind of search functionality elsewhere in VAOS?

**Comment by jbalboni** [comment]
@laurenernest I don't believe we do. In order to do this, we have to use a service like Mapbox to geocode the addresses entered, which is a paid service beyond a certain level of traffic

**Comment by laurenernest** [comment]
I don't want to integrate with a totally different service so let's try other options.

Converting this to a design ticket since we'll likely need more discussion around this state.

**Comment by outerpress** [comment]
For sure, that makes sense. In that case, I think their paths forward are:
* Using browser location
* Skipping this step/letting VA choose
* Calling

I'll mock up an alert state, similar to the state where we can't show providers nearby.

**Comment by outerpress** [comment]
@laurenernest here's that alert state. 

Another way we could go is letting them enter provider info manually - if there's a less painful way to do it than the current experience. Like if it was just entering the provider's name and city/state in one or two form fields. 

![VAOS-CC-NOADDR-02.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/7a864537-f1f0-465f-9d9c-be6f5f66c64e)

**Comment by jbalboni** [comment]
I can check and see if we're required to provide the whole address on the backend. I don't think we are, but I'm don't remember for sure. If not, then providing just provider name, city, and state would be technically doable (or some other combination).

**Comment by jbalboni** [comment]
Verified that I'm able to submit a request which just includes provider name, city, and state and it shows up in the appointment list as you'd expect.

**Comment by laurenernest** [comment]
@jbalboni Are we able to detect if the browser will allow location before the page loads? (to avoid a double alert if they choose current location and get the browser block message)

@outerpress The manual entry of the provider name, city, and state could also be used to cover users who already have someone in mind even when we're able to show a list. Either way, we'd want to make it clear they can continue without one so we don't run into the same situation as the current state (FL and manual form).

**Comment by jbalboni** [comment]
@laurenernest Generally, we have to request the location in order to tell if a user has location services enabled. There is an api to check for permission without requesting the location, but it doesn't work in all of our supported browsers (notably Safari and IE). But even if we did use that, a user will always have to specifically grant permission for our page to get their location the first time they come to the page, so it's not clear to me how much value that api would actually provide.

**Comment by outerpress** [comment]
Here are rough drafts of a couple possible manual entry flows - these need work, but I want to check if this seems like the right direction. I think both flows could work with multiple provider selection, too.

**No provider found**
Similar to the current alert state except:
* We show the manual entry fields
* The fallback messaging is captured in an additional info component

I'm still going back and forth on the alert styling; I'm not sure if it's still helpful, or just distracting.

| Default state  | Add'l info open |
| ------------- | ------------- | 
| ![VAOS-CC-MVP-02-NoProvider-v2](https://user-images.githubusercontent.com/2536801/108002603-f921e580-6fa4-11eb-80a5-2ad8c8fd6714.png) | ![VAOS-CC-MVP-02-NoProvider-v2-addl-info](https://user-images.githubusercontent.com/2536801/108002567-df809e00-6fa4-11eb-97fd-27528faaf883.png) |

**Provider not listed**
* Adds a "provider not listed" option to the end of the series. 
*  Selecting that option would trigger a conditional display with the manual entry fields. 
*  Add'l info content would be the same as in the no provider found flow
 
One potential issue is that In long lists this could get buried. But it might be a good starting point so we can gather data on how often users want to manually enter providers.

| Default state  | Radio selected |
| ------------- | ------------- | 
|  ![VAOS-CC-MVP-02-manual](https://user-images.githubusercontent.com/2536801/108002855-ba405f80-6fa5-11eb-9f90-64d8e7bcd29b.png)  |  ![VAOS-CC-MVP-02-manual-open](https://user-images.githubusercontent.com/2536801/108002880-ca583f00-6fa5-11eb-8d3e-1c19b80883f5.png)  |

**Comment by jbalboni** [comment]
@laurenernest @outerpress If we are wanting to have an option where the user manually enters provider information, we need to talk to the backend team. I believe Brad said the future HSRM integration is built to only allow us to send a list of provider ids in the request, which would mean that we couldn't send free text provider info.

**Comment by outerpress** [comment]
@peggygannon this is ready for content review. You can ignore the earlier any designs posted in previous comments. The current designs are in the Design Assets section of the ticket.

**Comment by peggygannon** [comment]
Hi, @outerpress The only edit I have is to the Note, if no home address is on file

**Note:**To show providers near your home, you need to add your home address to [your VA profile](link to profile).

**Comment by outerpress** [comment]
That sounds perfect, updated the linked Sketch file.

**Comment by outerpress** [comment]
@laurenernest I added D/T/M mocks. I wasn't sure if this'd be done before or after #28379 so I just showed the changes to the provider selection section - happy to add more context if needed. Otherwise this is GTG.

**Comment by laurenernest** [comment]
It'll likely be done after. Moving to Product to update copy docs and dev ticket.

**Comment by laurenernest** [comment]
Updated ticket and [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/cc-provider-preference.md#no-home-address-on-file)

**Comment by outerpress** [comment]
Design work done, closing

**Comment by aarathi-poldass** [comment]
Steps to reproduce:
Scenario 1: If user has home address in profile, then sort options include: home address, current location, parent site city/state
1)	Login to VAOS as cecil.morgan@id.me
2)	Select Primary care and follow steps to enter a cc request 
3)	Validate the sort options include 
i)	Your home address 
ii)	Your current location 
iii)	Parent site city/state
4)	Your home address is set as default 
Scenario 2: If user has no home address in profile, then sort options include: current location, parent site city/state
1)	Login to VAOS as grethel.g.petryniec@id.me
2)	Select Eye care (Optometry) and follow steps to enter a cc request 
3)	Validate the sort options include 
i)	Parent site city/state
ii)	Your current location 
4)	Parent site city/state is set as default and the profile get original manual preference version

Validated by following the above steps and everything is working as expected.
