### ISSUE TITLE
Discovery: parallelization of unit tests in mocha 8

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16101]
Discovery on mocha 8 parallelization options. 

Questions to answer: 
- What would it take to implement this?
- Might this decrease build times (if so, by how much?)
- Might this improve the pain point of flaky tests causing failing builds (if so, by how much?) 
- How would this affect code coverage reporting? (see troubleshooting Eugene had done before)
- If we turn on parallelization and certain tests are failing consistently (how might we tell which tests are failing consistently), should we just turn those off? 

@U-DON has done some work on this, connect for context sharing

Time box to 2 day exploration & team will decide if we want to move forward with implementation

**Comment by meganhkelley** [comment]
@timwright12 some info from Rian: 

Rian Fowler (he/him)  2:47 PM
when i profiled this  a couple of years ago, most of the execution time was spent on babel- the unit tests themselves were pretty fast. parallelizing with jest for example didn’t really net us anything because each runner had to do the babel work. i don’t know how mocha handles parallelization- by default I think it does the transpilation once and runs each of the tests in a single context.
2:47
that’s why i think we should just aggressively timebox it for now- i’m kind of skeptical of it  actually solving anything (edited) 
2:48
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/front-end-standards/documented-decisions/jest/

we don’t really manage how things are imported in vets-website and we don’t have any instrumentation that would alert us to things that would make the build process slow. I’m also not an expert at babel so I’m not sure if there’s a way to prebuild and share things that don’t change much. and i’m sure why babel takes so long or we could use a non-js transpiler . SWC is written in rust and is way faster https://blog.logrocket.com/why-you-dont-need-babel/

i think we’re going to try this parallilization thing for the unit tests and it may solve the flaky test problem but multiply our unit testing time by 8 or more

**Comment by U-DON** [comment]
My experience when I briefly tested Mocha's parallelization is that it didn't really change the run time locally, but it cut the time in half for tests in CI (saving a few minutes).

**Comment by timwright12** [comment]
Pivoting this task to upgrading the testing tools instead of full parallelization of the tests.

PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14991

**Comment by meganhkelley** [comment]
Findings: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/automated_code_quality/11-18-2020-mocha-parallel-tests.md
