### ISSUE TITLE
[SD] Team Onboarding

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16104]

**Comment by denisecoveyduc** [comment]
@mgleo @srsuddath Any outstanding onboarding things that need to be captured in this epic? I feel like we have wrapped up our official onboarding and have now moved into learning on the job. If you agree I will close this epic.

**Comment by srsuddath** [comment]
I agree we have moved into the On The Job Training portion of our onboarding experience!
