### ISSUE TITLE
Discovery: Community Care facility locator

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1610]
## Story
As a developer, I want to understand how to look up CC facilities when a veteran wants to make a CC appointment request so that I can build this functionality into the new UI.

## AC
- [ ] How to look up CC facilities with a given type of care in a given radius from existing residential address (which address is that specifically?) specifically for the purpose of requesting an appointment is documented in GH
- [ ] What data is returned from this lookup, and what data is required / will be needed to support our mocks, documented in GH

**Comment by markgreenburg** [comment]
For context, the existing mocks don't have any requirements for being able to select a specific CC facility, so we probably don't need to figure this out right now. However we should still have an idea of how to look up & filter CC facilities.

**Comment by lenaecb** [comment]
Closing as doesn't appear to be a need now or in the near future. If this comes back, we'll revisit/recreate a new issue to address need.
