### ISSUE TITLE
Audit of existing documentation compared to the Storybook docs

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16114]
## Issue Description
Audit of existing documentation compared to the Storybook docs

---
## Tasks
- [ ] Do a comparison of the documentation that currently exists to what is on Storybook. 

## Acceptance Criteria
- [ ] List showing where document is in both and where there are discrepancies. 
---

**Comment by cvalarida** [comment]
Looks like design.va.gov documentation has useful guidance that isn't reflected in Storybook right now. We'll need to add that all in.

**Comment by caw310** [comment]
@cvalarida , is there a list of what is in design.va.gov but NOT in Storybook right now?
