### ISSUE TITLE
Contact VA page accessibility issues - page description and bluetooth keyboard (tab, up/down/left/right arrows)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#16125]
## What happened?
Page Description with TalkBack (Android:  "Contact 'vuh' screen".
Should hear "V" "A" rather than "vuh".

---------
The following is transferred to bug #17008:
[Tab on the keyboard only goes to buttons.  Should it be this way?  It goes from Back, to Crisis line, to first phone number, to second phone number, then through the nav bar buttons. Then it is 7 or 8 tabs to start again up at the back button.

Keyboard up/down arrows only switch between back button and nav bar after many taps.
Left/right arrows only seem to navigate the nav bar.]

## Specs:
- Device: Android with bluetooth keyboard

## Steps to Reproduce
- Navigate the Contact VA page with Android and keyboard.

## Desired behavior
- VA should be read as "V" "A", no "vuh".
- Navigation of the page by keyboard using tab or arrow keys should be logical and stop on sections of page so user knows where they are on page.

## Acceptance Criteria
- VA should be read as "V" "A", no "vuh".
- Navigation of the page by keyboard using tab or arrow keys should be logical and stop on sections of page so user knows where they are on page.

## Bug Severity
- 3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14015

## Screen shot(s) and additional information

**Comment by digitalken** [comment]
The keyboard issue here (where it is actually working against the previous page) is similar to this bug.  So let's track the keyboard issue on this one: 
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17008

**Comment by digitalken** [comment]
Sending back to @keli13 for a little rework on the "vuh" vs "V" "A" scene...

**Comment by esther-k** [comment]
**12/14**
Pass - on Android, Talkback is pronouncing "Contact VA screen" correctly
