### ISSUE TITLE
Add Pension and Survivor related links to “Frequently used VA forms” 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16127]
## Issue Description
_Explore the possibility of updating  in the “Frequently used VA forms” section found on VA Forms website to include the Pension and Survivor related benefit links_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
All - I already replied directly via email to this stakeholder's request. We are not going to be adding Pension to the Frequently used VA forms" cards. Pension app is not as frequently used as Disability, Health Care, and Education.

**Comment by jenniferlee-dsva** [comment]
Pasting email to Daniel: 

> 
> From: Lee, Jennifer Y. 
> Sent: Tuesday, October 27, 2020 6:43 PM
> To: Joyce, Daniel, VBAVACO <Daniel.Joyce@va.gov>
> Cc: Parker, Ethan, VBAVACO <Ethan.Parker2@va.gov>; Kessinger, Nancy J., VBAVACO <nancy.kessinger@va.gov>; Hashimoto, John <John.Hashimoto@va.gov>
> Subject: RE: Updating VA Forms Page
> 
> Hello Daniel,
> Thanks for reaching out! When we launched this modernized page, we used search data (organic and site search) as well as data on applications to inform what top 3 benefit applications to include in the “Frequently used” section.  That said, the most frequently used benefit applications can change over time, so we will keep an eye on the numbers. 
> 
> One thing you might find of interest – https://www.va.gov/find-forms/about-form-21p-527ez/ 
> We launched modernized form detail landing pages, which includes a button to the web-based application tool if one is available. And the pension form does appear to have one!
> 
> We created these landing pages, so that if someone is looking for your form in organic search, instead of the blank PDF, people can get the landing page – which includes the paper form they searched for but also lets them know there’s a digital tool. 
> 
> We’ll be connecting the form search results to new meta data fields so that the search result of a PDF will also show the web app button (if there is a web app). 
> 
> The whole team is focused on launching another product right now, so we’ve had to postpone that forms search iteration, but it is definitely in our backlog! I will let you know when that goes live, so you can see it in action. 
> 
> Best,
> Jen
>

**Comment by MarciMcGuireGCIO** [comment]
Based on above, I'm gagging this wontfix & closing
