### ISSUE TITLE
Remove CARMA::Models::Base for more explicit hard-coded #to_request_payload methods

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#16129]
**Description**
Retire `CARMA::Models::Base` in favor of a more explicit, hard-coded, `#to_request_payload` on each inheriting model.

**Comment by hdjustice** [comment]
There was a merged PR over a year ago that included this.  Closing the ticket.  Any further work needed will result in a new ticket being created.
