### ISSUE TITLE
Put VA Banner on the component document Storybook link

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#16122]
## Issue Description
Put a VA banner on the component document Storybook link so that users know that they are looking at VSP design system. 

---
## Tasks
- [ ] Put VA Banner on the component document Storybook link

## Acceptance Criteria
- [ ] When I go to the component page on design.va.gov, I see a VA banner 
---

**Comment by cvalarida** [comment]
What does this mean? How is this different from #16119

**Comment by caw310** [comment]
Duplicate 16118
