### ISSUE TITLE
Discovery: Community Care Eligibility

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1612]
## Story
As a developer, I want to understand how to integrate with the new Community Care eligibility API, how to tell if someone is eligible for CC or not, and what eligibility data is returned from the service so that I can build a UI for veterans that will only give them CC options when they should be available, and can give them helpful information about their eligibility status as needed.

## AC
- [x] CCE API swagger is documented in GitHub
- [x] How to tell if someone is eligible for CC based on the service call is documented in GitHub
- [ ] The data that CCE API uses to determine eligibility and the logic for this calculation documented in GitHub (or link to existing documentation provided)

**Comment by jbalboni** [comment]
I have not been able to find existing documentation on the CC api, just training materials for how CC works in VAOS.

**Comment by jbalboni** [comment]
@markgreenburg I added a page in the team repo for CC: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/engineering/Community%20Care%20notes.md

I think that covers the info we need for the first two items, couldn't find much info for the third one.

**Comment by markgreenburg** [comment]
Closing - I don't think we'll need to address the third AC as we're not planning on giving fine-grained info about eligibility.
