### ISSUE TITLE
Unfix Veterans Crisis Line Button

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#16132]
_NOTE: This is in intended to resolve tickets(bugs) #15912 and #15540_

## Acceptance Criteria

1.  Unfix the Veterans Crisis Line banner/button so that it is part of the page scrolling

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**11/23**

PASS - on iOS and Android. Moving to design QA
