### ISSUE TITLE
STEM: Applicants not being CC'd on SCO emails

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#16145]
## What happened?
During our UAT sessions, we had two participants whose applications triggered a SCO email (the applicants met the three eligibility requirements and therefore the email was triggered). The applicants were not CC'd on the email to the SCOs (**confirmed with SCO that they were not included in the CC line**). 

## Desired behavior
Eligible applicants who trigger a SCO email when applying for the STEM Scholarship should be CC'd on the email to their SCO(s). 

## Acceptance Criteria
1. When an applicant who meets the following criteria submits an application for the STEM scholarship, an email is sent to their SCO(s) and they are CC'd on the email. 
   1. 6 months or less of post-9/11 GI Bill entitlement remaining
   2. Enrolled in a STEM program or have a STEM bachelors and are pursuing a teaching certificate
   3. Enrollment data from EVSS matches the information the applicant enters on the "Program details" screen (Step 3 of 6). 

## Supporting Artifacts
1. SCO email that is sent: [https://app.zenhub.com/files/133843125/3a82c552-45e5-4763-a076-c74e61db2ca7/download](https://app.zenhub.com/files/133843125/3a82c552-45e5-4763-a076-c74e61db2ca7/download)

**Comment by zurbergram** [comment]
https://guides.rubyonrails.org/action_mailer_basics.html#example-action-mailer-configuration
https://guides.rubyonrails.org/configuring.html#configuring-action-mailer

There is `config.action_mailer.default_options` but this doesn't appear to be used

A request to work with external to setup `config.action_mailer.observers` classes that notify either Prometheus or Sentry/Cloudwatch with information might need to be made

**Comment by zurbergram** [comment]
Based on https://developer.govdelivery.com/api/tms/tutorial/send_an_email/ which is the service used by vets-api it does not appear that CC or BCC fields are available to use.

### Short term solution
Have both SCOs and applicants in the TO field of the email

### Long term solution
Reach out to VANotify project about including CC and BCC fields in the replacement for govdelivery-tms they are working on

**Comment by desireeturner** [comment]
The CC feature is not currently functional so we have a story in the backlog to come up with an alternative implementation. That said, emails are working as expected and this bug can be closed.
