### ISSUE TITLE
VSP QA feedback for Higher Level Review [Staging Review]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#16163]
## VSP QA feedback on SSO-login [Staging Review]

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

### Links
**Test Plan / Execution logs:**
https://dsvavsp.testrail.io/index.php?/plans/view/103
**Coverage for References Report**
https://dsvavsp.testrail.io/index.php?/reports/view/144
**Summary (Defects) Report**
https://dsvavsp.testrail.io/index.php?/reports/view/145

### Feedback
**Test Execution Logs**
1. **Comment**: Excellent cross-browser coverage is demonstrated in this test plan. I love that you managed to run through IE11 as well -- amazing!

**Coverage for References Report**
1. **✔️ Consider**: It may be beneficial to find a way to more granularly map your reference material to your test cases. It looks like 3 reference tickets were used for basically every test case in this plan. The reference issues had wildly different scopes and details as well. The ideal practice would have a mapping of one or two test cases to an individual user story with clear an concise acceptance criteria that can be verified in the test cases. If the AC are not clear and testable during backlog refinement then product and QA should work together to clarify the stories. 

**Summary (Defects) Report**
1. **✔️ Consider**: [Defect 15994](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15994) looks like a relatively minor copy mismatch. It's important to get this right for various legal obligations, but it seems like this may already be resolved by an update to the requirements.
1. **❗️ Must**: [Defect 15996](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15996) looks to have been resolved today in staging -- hooray! The way this defect reads, this seems like a _must_ verify prior to release kind of defect.
1. **⚠️Should**: [Defect 16001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16001) appears to have a plan for resolution prior to release that is not implemented yet. QA _should_ verify that the proposed change resolves the issue prior to release.
1. **✔️ Consider**: [Defect 16045](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16045) appears to stem from an unusual combination of device and browser. Still, IE11 is in our top 5 most used browsers on the platform, so display issues with restricted view ports should be carefully considered prior to release.

## Definition of Done
- [x] Acknowledge each item of feedback with a decision
- [ ] VSP QA will close ticket after reviewing feedback decisions

**Comment by luke-gcio** [comment]
@tzelei has been sent the last two tickets to close and the we can close this ticket as well.

**Comment by luke-gcio** [comment]
All the linked tickets are closed.  Can we close this, @pjhill ?

**Comment by pjhill** [comment]
> All the linked tickets are closed. Can we close this, @pjhill ?

Awesome -- thanks for following up! Yep, I'll close this ticket.
