### ISSUE TITLE
Analytics Implementation or QA Support for BAH Team - CT Ratings

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#16164]
# Google Analytics Implementation or QA Request

 Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?

Google Analytics implementation

- Who is this request for?

- Amy Knox, Booz Allen team

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?

    - Booz Allen team, GI Bill Comparison Tool / School Ratings
    
- Provide the Domain where Google Analytics needs to be implemented

Implementation will be on GI Bill Comparison Tool School Profile pages

Example: Stanford University - https://staging.va.gov/gi-bill-comparison-tool/profile/31121005

- Please provide any upcoming deadlines or important milestones
    
    - Ratings data has to be collected before this functionality will launch on production. Ratings data that displays on schools now is for test purposes only. 

- Typical Website Interactions to Track

Google Analytics should track

1. **Use of jumplink "See NN ratings by Veterans" at the top of the page.** This link jumps users to view ratings details lower on profile page. We'd like the aggregate use of jumplinks on all profile pages... how many times is the jumplink used across all profile pages, as opposed to how many times was the jumplink used on the Stanford profile vs. Dartmouth profile.
2. **Rating category accordion open / close** The rating category accordions have details about the individual rating categories. This would be helpful to have aggregated by individual rating category (how many times was each of the individual categories opened, across the entire comparison tool)
3. **Scroll depth to/past "About ratings" content.**  We want to see if people are actually getting to the About ratings content.  I'm not familiar with how this is measured so interested in your sage advice here. 

- Additional Comments

    - No authentication required. 

    - Let me know if you have any questions about what we're looking for or suggested modifications. 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks, @amyknox ! Do you have a date for when this tracking should be live in production?

**Comment by amyknox** [comment]
Hi @joanneesteban - this isn't going to be in production until next year.  We have the UI for ratings display but the process for collecting the ratings is just getting started.

**Comment by bsmartin-ep** [comment]
@amyknox / @joanneesteban -


#### Use of jumplink "See NN ratings by Veterans" at the top of the page. 


We will need a developer to trigger this event in the dataLayer on this click:

`nav-jumplink-click`

No other parameters needed.  Just:
```js
'event': `nav-jumplink-click`
```

Let me know if they have any questions.

-------


#### Rating category accordion open / close 

Looks like this is already firing this event:

```js
eventCategory: "Interactions", 
eventAction: "Navigation - Accordion - Collapse - School ratings", 
eventLabel: "nav-accordion-collapse",
```

...so we should be OK there.

--------
#### Scroll depth to/past "About ratings" content.

Scroll depth is automatically tracked site-wide.  Looks like 50% scroll is fired right before they hit "About Ratings" on a desktop and 75% on mobile.

**Comment by amyknox** [comment]
@dneel-bah ⬆️

**Comment by jonwehausen** [comment]
Hi @amyknox & @dneel-bah , 

First I want to apologize for the extended delay on this ticket -- this got pushed down towards the bottom of our queue and I'm now revisiting. 

I took a look at the existing tracking we have in place and for the most part we have the items you identified in the description tracked -- that said there are a few data layer tweaks we will want to make to capture the individual ratings for each accordion. 

![image](https://user-images.githubusercontent.com/48527022/110990388-3fb6f580-8341-11eb-8c54-2baff3d579b1.png)

If we please could adjust the taxonomy for accordions be the below it would be very much appreciated: 
```javascript
'event': 'int-accordion-expand' //'int-accordion-collapse' => this is an adjustment to our design system standardization
'accordion-parent-label': 'Overall experience' //dynamically populate with label of accordion, if accordion only has 1 label always populate this one 
'accordion-child-label': undefined //dynamically populate with secondary label of accordion, with no secondary label, set this as undefined 
'accordion-size': //pass in the exact width from the css class, large or small 
'gibct-rating': '3.4' //include the rating for each accordion
```

Once this is implemented, we can get this QA tested and closed out for good. 

Apologies again for the delay here and look forward to hearing from you.

**Comment by dneel-bah** [comment]
@jonwehausen We will pull these updates into an upcoming sprint and let you know when they are ready to test again.

**Comment by jonwehausen** [comment]
Hi @dneel-bah , 

Thank you very much for this information. 

We look forward to QAing your work here.

**Comment by zurbergram** [comment]
@jonwehausen For
> 'accordion-size': //pass in the exact width from the css class, large or small 

Would you like the value 'small' to be passed in?

The ratings accordions are responsive and do not have a predetermined width.

For the smaller accordions within the larger "Estimate your benefits" accordion, `'accordion-size': 'small'` is sent to Google Analytics, the large ones send `'accordion-size': 'full-content-width'`.

**Comment by zurbergram** [comment]
@jonwehausen For
> ‘gibct-rating’: ‘3.4’

Can this be a decimal number value or does it need to be a String?

**Comment by jonwehausen** [comment]
Hi @zurbergram , 

Thanks for your questions here. 

- Yes, you can pass `'small'` for the smaller accordions and `full-content-width` for the standard size ones
- Great question, please pass in the rating as a decimal number

**Comment by zurbergram** [comment]
Requested changes coming in https://github.com/department-of-veterans-affairs/vets-website/pull/16751

**Comment by jonwehausen** [comment]
### QA Testing

| Description of Interaction | Data Layer Screenshot | Tag Screenshot | Test Status | Test Notes
| -- | -- | -- | -- | -- |  
Click to expand accordion "Overall experience" mini accordion | ![image](https://user-images.githubusercontent.com/48527022/115073683-aee6b300-9ec6-11eb-8637-9820603db92c.png) | ![image](https://user-images.githubusercontent.com/48527022/115073980-113fb380-9ec7-11eb-80c1-4f0c21ebedf0.png) <br> ![image](https://user-images.githubusercontent.com/48527022/115073951-07b64b80-9ec7-11eb-92dd-52ad4bf382ff.png) <br> ![image](https://user-images.githubusercontent.com/48527022/115077610-59ada000-9ecc-11eb-8b1b-29ee01ce456b.png) | ✔️ **PASS** | • _Validated custom dimension index 90 (Component Relative Size) populates with "Small"_ <br> • _Validated custom metric index 49 (GIBCT Accordion Rating) populates with value of `gibct-rating` DL variable_ 
Click to expand to expand accordion "Veteran community" mini accordion | ![image](https://user-images.githubusercontent.com/48527022/115076217-3eda2c00-9eca-11eb-8e92-54f1f060cab2.png) | ![image](https://user-images.githubusercontent.com/48527022/115076244-4a2d5780-9eca-11eb-9a7a-ef27fb1f36c4.png) | ✔️ **PASS** | _same test notes as row 1_ 
Click to collapse accordion "Veteran community" | ![image](https://user-images.githubusercontent.com/48527022/115076439-8f518980-9eca-11eb-8de8-b4fc4d641558.png) | ![image](https://user-images.githubusercontent.com/48527022/115076495-a4c6b380-9eca-11eb-9363-799e85684246.png) | ✔️ **PASS** | _same test notes as row 1_
Click to collapse accordion "Job preparation" | ![image](https://user-images.githubusercontent.com/48527022/115076665-e22b4100-9eca-11eb-91e8-677ab3d7854e.png) | ![image](https://user-images.githubusercontent.com/48527022/115076686-eb1c1280-9eca-11eb-92e4-b754f397cb1a.png) | ✔️ **PASS** | _same test notes as row 1_

cc: @laurensimpson14 @bsmartin-ep  for visibility

**Comment by jonwehausen** [comment]
Thanks for your work here @zurbergram , we greatly appreciate it!
