### ISSUE TITLE
[Authenticated Experience] - Analytics request: Profile 2.0 and Direct Deposit - Calculated tiles

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#16166]
Is it possible to create calculated tiles in GA?

Request 1:
adding "% of Successful submissions" to this [Profile 2.0 dashboard](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-transaction/)

Request 2:
Adding "% Direct Deposit Retrievals Successful" to this [Direct Deposit Dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/)
Adding "% Direct Deposit updates successful" to this [Direct Deposit Dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/)

**Comment by bmcgrady-ep** [comment]
@mshea0606 - Confirming receipt. Thanks!

**Comment by bmcgrady-ep** [comment]
Hi @mshea0606 - Can you clarify what you mean between `% of Successful Submissions` and `% Direct Deposit Updates Successful`? 

I am adding a page in Domo to fulfill this request as this will have to be a custom calculation and we can't do custom calculations in Google Analytics.

**Comment by mshea0606** [comment]
![Screen Shot 2020-11-18 at 11 12 00 AM](https://user-images.githubusercontent.com/60523453/99555969-eccec200-298e-11eb-861e-a3cd8e2204b4.png)

(Failures in Saving Direct Deposit)/(Form submits for Direct Deposit) = % of submits failed right?

so 1 minus (Failures in Saving Direct Deposit)/(Form submits for Direct Deposit = % successful submissions

**Comment by mshea0606** [comment]
For the % Successful submissions for the Profile.....

do we have a failed submission or save failure count to make the same ratio? If not, we can exclude this.

I basically want to see what % of time we save/submit Direct deposit info and dont get a failure/error

then the same thing for the profile at a much higher "overall" level.

Let me know if this makes sense or if I am not understanding these events correctly. Thanks!

**Comment by bmcgrady-ep** [comment]
@mshea0606 - Okay, I was able to replicate what you are asking for. I added you to the Domo page. Let me know if you have any questions!

**Comment by bmcgrady-ep** [comment]
@mshea0606 - Is there anything else I can help you with in regards to this request? If not, I will go ahead and close it.

**Comment by mshea0606** [comment]
@bmcgrady-ep, can you please send me the link to the Domo page?

**Comment by bmcgrady-ep** [comment]
Closing out this ticket. Let me know if you need anything else!

**Comment by joanneesteban** [comment]
@bmcgrady-ep - reopening for juuust another moment. Could you also add the GA source links to each of these charts?

**Comment by bmcgrady-ep** [comment]
@joanneesteban - The GA reports have been added for each of the individual charts.

**Comment by bmcgrady-ep** [comment]
Closing as the GA Reports have been added for the individual charts.
