### ISSUE TITLE
GIBCT Redesign: Research Mapping Nearby Points of Interest

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16161]
As a developer, I need to research mapping nearby points of interest functionality that can be incorporated into the comparison tool so that the comparison tool users can see points of interest near the institution.

## Assumptions:
1. Example behavior:
Another thought UX had was to give the user preset selectable buttons (e.g. food/grocery, transportation, shopping, local points of interest, , parking, gas) and when a user selected one of those, it would display a map with the identified information. Select Food - a map loads showing all the restaurants in the area. Select Parking - maps loads with parking options.
2. DEPO is currently using mapbox and it should be one of the tools we research as part of this story.

## Acceptance Criteria:
1. Documentation outlining point of interest tools and/or APIs that can be leveraged within the comparison tool.

    > Documentation includes, but is not limited to:
    > - Pros / Cons
    > - Pricing information
    > - Whether or not the following points of interest are supported: food/grocery, transportation, shopping, local points of interest, parking, gas
    > - Additional points of interest that might be relevant in the tool

2. Documentation is located in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/school-comparison-tool/redesign/research

## Supporting Artifacts:
1. Mapbox research https://github.com/department-of-veterans-affairs/va.gov-team/issues/14413#issuecomment-706375679

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/nearby-points-of-interest/research.md
