### ISSUE TITLE
Offboarding of Bennie Mosher

### ISSUE THREAD

**Issue by christine-dillman** [department-of-veterans-affairs/va.gov-team#16160]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Bennie Mosher
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Identity Team
   > Last Day: 6 November 2020
   > Company: Oddball
- Please provide any type of access they may have and their GitHub username. 
  > GitHub Username:  benniemosher
  > I am not sure of what access he had.  He also worked on the OPS team before Identity.  I have already removed him from the VSP-Identity group.
  
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jbritt1** [comment]
SOCKS, AWS, and PagerDuty access removed.

**Comment by jbritt1** [comment]
@joanneesteban / @bsmartin-ep / @jonwehausen, please verify GA / DOMO access as time allows. Thanks in advance!

**Comment by bsmartin-ep** [comment]
@jbritt1 -

GA access has been removed for Bennie Mosher.

I don't see DOMO or GTM accounts.

**Comment by jbritt1** [comment]
All line items complete for user at this time.
