### ISSUE TITLE
Edit Email Address page - Long email addresses should have ellipses when too long to fit on one line

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#16165]
## What happened?
When the email address is too long to fit on one line, it should end with an ellipses when the keyboard is closed before tapping the Save button.

Android:  Displays the last visible portion of the email address when tapping the check mark button to close the keyboard.
iOS: Displays the beginning of the email address, as much as can be displayed, when closing the keyboard by hitting the Return button.

## Specs:
- Device: Android Motorola Moto G7
- Device: iPhone SE 1st gen.

## Steps to Reproduce
- Navigate to Person information page and tap to edit or enter your email address.
- Enter an email address that is far too long to be displayed on one line.
- Tap whichever key is needed to close the keyboard.
- View email address before being saved.

## Desired behavior
- Android:  Displays the last visible portion of the email address when tapping the check mark button to close the keyboard.
- iOS: Displays the beginning of the email address, as much as can be displayed, when closing the keyboard by hitting the Return button.

## Acceptance Criteria
See desired behavior.

## Bug Severity
- 4 - Low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13895

## Screen shot(s) and additional information

![editEmailAddressNoEllipses.jpg](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/fdebab80-e71a-44b2-b601-2b04c3084f1a)

**Comment by bessgreen** [comment]
Android's native solution to long entries is to gradually hide the field. Per feedback from Bridget (2/17), we can use Android's native solution _instead of_ ellipses. We will continue to use ellipses on iOS.

**Comment by bessgreen** [comment]
Passes with desired behavior across iOS & Android. 

Closing.
