### ISSUE TITLE
[Discovery] Investigate and document pros/cons of hosted Sentry vs upgrading our on-premise

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#1617]
## User Story
We need to investigate the pros/cons of moving to a hosted Sentry instance, as well as uncover any technical challenges that may arise in the process.

## Goal
We have a solid basis upon which to make a decision about moving our Sentry integration.

## Acceptance Criteria
- [ ] Potential (known) problems a migration from lesser version to extant hosted version might cause are identified and cataloged
- [ ] Benefits and drawbacks are explored and cataloged
- [ ] Rollback/failover plan is brainstormed
- [ ] Analysis report is prepared for appropriate audience 
- [ ] Implementation issues are documented and attached to epic

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alexpappasoddball** [comment]
@kfrz Correct me if I'm wrong but the investigation is likely done seeing that we have this following ticket in our backlog #1555

**Comment by johnpaulashenfelter** [comment]
Closing in favor of upgrading our self-hosted sentry to v10
