### ISSUE TITLE
Reorder credential providers on Access VA Page

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#16172]
## User Story
After a user clicks "Register for a Sign-In Partner" on the Access VA Page, they see an option to create a new account with MHV, DS Logon, or ID.me. We want to reorder the credential providers on the Access VA Page so that ID.me is first.

![Screen Shot 2020-11-13 at 2.44.32 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/6a83bd9e-a5c4-4331-8ae9-85f9fe03cff7)

## Tasks
- [ ] Ask IAM if we can do this

**Comment by bessgreen** [comment]
@lexicalninja to review with IAM team on Tuesday 11/17
