### ISSUE TITLE
Edit direct deposit info page accessibility issues (Keyboard)

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#16174]
## What Happened?
 
**Keyboard**
With Keyboard linked to Android, only a few fields are being jumped to while tabbing or using the navigational keys. The cancel button, save button, and "Where can I find these numbers?" dropdown are being focused and jumped to but the rest of the fields below that can not be accessed

## Specs:
- Device: Android - LG LM-Q720 Stylo 5
- Bluetooth Keyboard

## Steps to Reproduce

**Keyboard**
1. With Keyboard linked to Android, navigate to the edit direct deposit information page 
2. Press tab to get the keyboard focus on the cancel button
3. Press tab or the down arrow key. The save button will be in focus
4. Press tab or the down arrow key. The "Where can I find these numbers" dropdown will be in focus
5. Press tab or the down arrow key. The "Where can I find these numbers" dropdown will be remain (trapped) in focus

## Desired Behavior

**Keyboard**
- With Keyboard linked to Android, the keyboard will not get trapped on the "Where can I find these numbers" dropdown and all the other elements on the page will be able to be focused

## Acceptance Criteria
See desired behavior

## Bug Severity
- 4 - Low

## Linked Story
- Story #13907

## Screen Recordings (s) and Additional Information

[Video of the keyboard bug on Android](https://drive.google.com/file/d/1nBlCjapukYs7nVQDrYLoDesjfPHe30cc/view?usp=sharing)

**Comment by digitalken** [comment]
Closing 7/9/2021 - This bug seems to be covered in this bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17008 about keyboard tabbing issues.
