### ISSUE TITLE
Discovery: Appointment Format & Telehealth

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1618]
## Story
As a designer, I want to understand which appointment formats (visit, phone, video) are available for each care type, and if this is something that's configurable at the facility or system level, so that I can build a UI flow that only presents veterans with options they can take advantage of.

Currently, the VAOS legacy tool offers all three appointment formats for all types of care, even when some formats may not be available at a given facility.

## AC
- [ ] Discovery on whether there are any services that provide appointment format data for care types, facilities, appointment reasons, or any other primary category is documented in this ticket or GH.
- [ ] Documentation exists in GH for a table that definitively shows which appointment formats should be available for each care type (or by any other metric that differentiates availability for appointment formats)

**Comment by lenaecb** [comment]
@markgreenburg - is this something we need to address prior to MVP release?

**Comment by markgreenburg** [comment]
This might be good post-MVP discovery work but certainly isn't anything in-scope for MVP.

**Comment by lenaecb** [comment]
Moving this to reevaluate stories epic. We will resurface this as part potential future work.
