### ISSUE TITLE
Review and update Form label masterlist

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#16185]
## User story
Review and update the forms masterlist to ensure any new form chapter heads and labels are captured. 

## Acceptance criteria
- [ ]  Review form chapter heads to ensure they are all captured in the Form label masterlist
- [x]  Add "home address" and "mailing address" label to the masterlist
- [x]  Fix duplicate entry of Your first name
- [x]  Document label entries that are form specific
- [ ]  Review the following recently launched forms to ensure new any labels are added to the masterlist
    - [x] Debt management tool (https://staging.va.gov/manage-va-debt/)
    - [x]  View VA payment history (https://www.va.gov/va-payment-history/)
   - [x] Caregiver form (https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)
   - [x]  VRE Chapter 36 form (https://www.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction)
   - [x] Rogers STEM scholarship (https://www.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction)
    - [x]  COVID volunteer sign up (https://www.va.gov/coronavirus-research/volunteer/sign-up)
    -  [ ] Higher Level Review form (https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction)
    - [ ]  VRE Chapter 31 form  <br>

- [ ] Update Form label masterlist and share with product teams

**Comment by allison0034** [comment]
@peggygannon I cannot access the Rogers STEM or Higher Level form. I have documented the missing form labels [this Google doc](https://docs.google.com/spreadsheets/d/1sq_YyztJmfv2NN0d06NTq-EwN4xy-KLs-WqsfijqjTI/edit#gid=0). If you have correct logins I can documented the other 2 forms.

**Comment by peggygannon** [comment]
Thanks you @allison0034!  I will incorporate your findings for Caregivers. I am also having trouble accessing HLR and STEM. I will reach out to the devs to figure out why.

**Comment by peggygannon** [comment]
this is complete. I'm rolling over label updates for HLR and Chapter 31 to the next form label update, after those forms have launched.
