### ISSUE TITLE
Review decision review copy in claim status tool

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#16199]
While creating Resources and support pages, the Public Websites team noticed some outdated decision-review language that the claim status tool uses. 
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/claims-status/utils/appeals-v2-helpers.jsx#L290
For example, it uses the term RAMP which has been replaced with the decision review process, and refers to the process as "new". 
Creating this preliminary ticket so that we can revisit in 2021.

**Comment by jacobworrell** [comment]
@lwalsh617 revisiting this old ticket, who is responsible for writing and approving new copy we can use to replace this language.
