### ISSUE TITLE
Rally Point Exploration

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16190]
## Description
It has been suggested that we connect with Laurent to explore https://www.rallypoint.com for discovery opportunities.

##RallyPoint  Info
- Site: https://www.rallypoint.com
- "Tap into a rich network of highly engaged members discussing all facets of life during and after military service."

## Tasks
- [ ] Connect with Lauren Alexanderson (@johnhashva can help make connection)

**Comment by mgleo** [comment]
Possible use of Rally Point: create a message board post/thread asking veterans about their search experience on VA.gov

**Comment by johnhashva** [comment]
@mgleo let me know if you want me to coordinate a quick convo with either Lauren Alexanderson -- who leads our veteran usability efforts -- or want to start with an exploratory convo with Dave Gowell the CEO of rallypoint first.

**Comment by denisecoveyduc** [comment]
Deprioritizing until further notice - possibly redundant to research already conducted. We may explore this in the future.
