### ISSUE TITLE
IRIS Exploration

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#16191]
### Description
Exploring IRIS for data insights. 

### Background/Context/Resources
- Link to files

### Tasks
- [ ] TBD

### Definition of Done 
- [ ] TBD

**Comment by mgleo** [comment]
Requested access to recent Contact Center Monthly Reports similar to these:
[February 2020 Google Sheets](https://drive.google.com/file/d/1ytpv0UOdDrl8itRDiCYX7EOwm8dlStvX/view)
[March 2020 Google Sheets](https://drive.google.com/file/d/162Cn_srmNNQ3d7X62HIOOTdVrm2HSwQN/view)
[July 2020 DOMO](https://va-gov.domo.com/page/1744754544)

**Comment by denisecoveyduc** [comment]
Moved collected information to #18169
