### ISSUE TITLE
VSP IA feedback - Staging review - HLR form

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#16195]
IA Feedback - Staging review - HLR form

**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description

**This feedback is only for the HLR form. The static content page changes and entry points were not available/complete for this review.  These elements will need to be reviewed at a later time prior to launch.**

**MUST**
- Correct the breadcrumb of the form, it should be:   Home > Decision reviews and appeals > Higher-Level Reviews > Request a Higher-Level Review with VA Form 20-0996

## Definition of Done
- [ ] Must feedback is implemented on staging
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by mnorthuis** [comment]
This was not corrected before this form went to production, and will need to be fixed.

**Comment by Mottie** [comment]
@mnorthuis I just merged this fix into the repo master branch. I don't think the change will be available on staging until tomorrow at the latest.
