### ISSUE TITLE
Access for Don Seymour - @department-of-veterans-affairs/vsp-operations

### ISSUE THREAD

**Issue by oragame** [department-of-veterans-affairs/va.gov-team#16200]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Don Seymour
- Please Provide your email.
   > don.seymour@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA VSP, DevOps Engineer, AdHoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEh5l2GL5Za2Wfo3SNU9QKr5XI4nSkcLpa2vvzmIdz0FjHjSLPwaTWARW1xPbG7oNnur3Bx+LTgUqr6eQ6GhVPC43C/Jt1f3rDG/yAlgwYl4OtOgDDA1xlL2MAQJYTVPATR6YBfADOoG6XX0Mp4X1ntPLwrmQkGHxt6ytwNI3FSSXUIu3pvApI9NuXllOV2nTU9IjRrdGpfSUybRt4mRyPcSsMtssu5Xob8cP8BXuMy+apZqqm/9c1QpL7SLh5AUhNhTL8AM9dx0PtQEy+cmS/YhayyikYuQWYS9qdteMJHt1C89Vn6G5J9+ruY2JPOOU8Qy9/BQgUqT1sA6Nke5EJmBxRmqFzXguzP5/HZnpaaM/1Z93anA5VJgBgO+SVfxFm4kYo0RJiyBtq1fzkIuO/e9V9Su/ygIKx5mtaPHtkGKep0GS+0889QH3xnd7ECJtVfdvfu3UJPQE4T4mAwiynu1IOEbrDC0cMco1OMfKM6iBFJ5bvqPI1PF2fkFOdfrM= donseymour@Donald-Seymour-Macbook.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > I need access for DevOps related services in order to perform work duties expected of the VSP team.

**Comment by jbritt1** [comment]
### For AWS Access:

User: Don Seymour
COR: Jeff Hayter
Approval Required: @Jeff-Hayter 

P.S. @Jeff-Hayter, Don is a member of the Operations team, are we able to bypass normal wait times for approval on this user?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by oragame** [comment]
I am getting a 404 when trying to access the ssh config... any ideas? [SSH config](https://github.com/department-of-veterans-affairs/devops/raw/master/ssh/config)

**Comment by jbritt1** [comment]
> I am getting a 404 when trying to access the ssh config... any ideas? [SSH config](https://github.com/department-of-veterans-affairs/devops/raw/master/ssh/config)

Going to guess GitHub team membership isn't quite right yet. Let me dig in a little deeper.

**Comment by Jeff-Hayter** [comment]
@jbritt tagging @drorva Who can approve expedited access for VSP Ops folks.

**Comment by drorva** [comment]
Approved

**Comment by jbritt1** [comment]
Thanks gents @Jeff-Hayter and @drorva! Temp credentials provided to Don at this time.
