### ISSUE TITLE
Analytics Implementation or QA Support for Caregivers

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16204]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

QA of Google Analytics

- Who is this request for?

    - @ala-yna 
    - _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - Caregivers team
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - No specific deadline, but GA & Domo are currently showing misleading info

- Certain conditions/responses that need to be reviewed

    - Both [Domo](https://va-gov.domo.com/page/1905395623?userId=1492182741) and the pie chart in [this Google Analytics dashboard](https://analytics.google.com/analytics/web/#/dashboard/u4Zg-ougQpq-87e5dGIH_w/a50123418w177519031p184624291/_u.date00=20201101&_u.date01=20201116/) are not counting "caregivers-10-10cg--submission-failed-client" as an unsuccessful submission.  Both sources should reflect that event as an unsuccessful submission. 

- Additional Comments

    - See Slack thread:  https://dsva.slack.com/archives/CMJ2V70UV/p1605535027383600

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @ala-yna , acknowledging receipt!

**Comment by jonwehausen** [comment]
Going to close this @ala-yna and include this as an item to our dashboard iteration ticket here: #11477
