### ISSUE TITLE
[Development] 526: Add SIP to Errors on Back End for File Uploads

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16216]
## Issue Description
There are a couple of ways to match SIP and errors and one of the easiest is to simply add the SIP ID to the backend (and front end, but that is likely a separate story, question out to Anna about how this works in our architecture).  This story will have more details as I understand the code arch more. For now, this is focused on file uploads.

---
## Tasks
- [x] If a veteran gets a [file upload error](http://sentry.vfs.va.gov/organizations/vsp/issues/3898/?query=is%3Aunresolved+url%3Ahttps%3A%2F%2Fapi.va.gov%2Fv0%2Fupload_supporting_evidence&statsPeriod=14d), log the SIP data to Sentry so we can easily cross reference

## Acceptance Criteria
- [x] We can match file upload errors to a specific user easily.

**Comment by annaswims** [comment]
It looks like we meant to be logging user id's all along in Sentry, which would be good enough to get the in progress form id.  There's a PR in review to fix the user.id.

**Comment by luke-gcio** [comment]
@annaswims will verify this.

**Comment by annaswims** [comment]
https://api.va.gov/v0/upload_supporting_evidence now has user data.  The CST file upload errors has user data all along
