### ISSUE TITLE
CODEOWNERS file changes for VSP Identity

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#16228]
The VSP identity team should be alerted of any changes to files in `vets-website` and/or `vets-api` that MAY affect authentication.  The team already has rules setup in Sentry to alert them of errors, so it makes sense to do this proactively before the changes hit production.

I recommend the following changes to the `.github/CODEOWNERS` files

#### vets-api
```
# authentication
app/controllers/*/sessions_controller.rb @department-of-veterans-affairs/vsp-identity
app/models/account.rb @department-of-veterans-affairs/vsp-identity
app/models/saml_request_tracker.rb @department-of-veterans-affairs/vsp-identity
app/models/user.rb @department-of-veterans-affairs/vsp-identity
app/models/user_identity.rb @department-of-veterans-affairs/vsp-identity
app/models/user_session_form.rb @department-of-veterans-affairs/vsp-identity
lib/saml @department-of-veterans-affairs/vsp-identity
```

#### vets-website
```
# authentication
src/applications/auth @department-of-veterans-affairs/vsp-identity
src/applications/login @department-of-veterans-affairs/vsp-identity
src/platform/site-wide/ebenefits/ @department-of-veterans-affairs/vsp-identity
src/platform/site-wide/user-nav/containers/AutoSSO.jsx @department-of-veterans-affairs/vsp-identity
src/platform/user/authentication @department-of-veterans-affairs/vsp-identity
src/platform/utilities/sso @department-of-veterans-affairs/vsp-identity
```

**Comment by ericbuckley** [comment]
@hinzed1127 I know it's been a few months since you've worked on this, but do the above `vets-website` rules seem like a good starting point, or would you add/remove any files to the list of "identity" owned modules?

**Comment by joeniquette** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15060
https://github.com/department-of-veterans-affairs/vets-api/pull/5379
