### ISSUE TITLE
Search has top and bottom borders, and too much margin below search container

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#16227]
## What happened?

- the collapsed search container shouldn't have top and bottom borders, based on the [design mock-up](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b?wid=0-1600203327438)
- There's a bunch of margin we don't need between the bottom of the search accordion and the bottom border. I think we just need to remove `.vads-u-margin-bottom--3` from that container.

<img width="400" alt="Screen Shot 2020-11-16 at 2 44 31 PM" src="https://user-images.githubusercontent.com/55992116/99300515-b5d79f80-281a-11eb-8aee-9a1f092e5e96.png">

## Specs:
MacBook, Chrome

## Steps to Reproduce
- URL: va.gov/resources
- emulate iPhone 5

## Desired behavior
Spacing and borders should align w/ the mock-up provided by @rtwell in the Mural template
## Acceptance Criteria
- [ ] No top and bottom borders
- [ ] Should have 24px of margin above and below search component on mobile

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
@youngfreezyVA  @brianlloyd   - Hi just checking in on this ticket status, as it's been 14 days since assigning? Is this ready to validate? 

If no work has been done on this, let's pull this back into backlog and reprioritze against next sprint's work.

**Comment by brianalloyd** [comment]
@jenniferlee-dsva didn't make it into the workflow based on Transformer work and other task alignment for Fareez.  I have this on my grooming list to discuss during tomorrow's planning session for Sprint 36.

**Comment by brianalloyd** [comment]
@youngfreezyVA or @kelsonic is this something you could also pickup for Sprint 36?  Needs estimate and grooming but looks like something that is not to hard to move forward.  LMK, thanks.

**Comment by youngfreezyVA** [comment]
i'd like to get through some of the localization issues before committing, but i'll likely be able to tackle this one.

**Comment by kelsonic** [comment]
Happy to help with this if you need/want @youngfreezyVA! 🙂

**Comment by youngfreezyVA** [comment]
thanks @kelsonic should be good, but will ping if i need the extra hand! 🙏🏽
