### ISSUE TITLE
Integrate Footer Data from Drupal

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1623]
Integratation with Footer data outside of Drupal.

**Comment by Karak888** [comment]
@ncksllvn wanted to ensure it was blocked by CMS implementation but there wasn't a direct blocker to select.  This ticket has a dependency on CMS implementation.  Need to identify what the links are for the footer.

**Comment by Karak888** [comment]
Header mega menu will go through but footer is being reprioritized.

**Comment by Karak888** [comment]
Need to get status on this please @ncksllvn

**Comment by Karak888** [comment]
@ncksllvn do you think we can close this one? Thanks!

**Comment by ncksllvn** [comment]
Sorry, missed your message above. Um, so, this work hasn't been started at all, and I don't know if we're still planning on doing it. The idea was that Drupal would contain all of the footer links, so we were waiting on the Drupal implementation before we would do our part. I think it was de-prioritized though. Up to you to close.
