### ISSUE TITLE
Analytics KPI dashboard request for [Public Websites - Resources and Support]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#16233]
# Request a KPI Dashboard for Resource and Support 

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [x] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [x] Your KPIs are clearly linked back to Veteran outcomes
- [x] Link your KPIs below (KPIs should be in your Product Outline)
- [x] Add your team label to follow progress

### KPIs
Please find the [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md)

Please find [OKR/KPI's](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/public-websites/Learning%20Center%20OKR%20Road%20Map.pdf)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [x] Groom analytics for technical feasibility
    - [x] Document data sources for each metric
    - [x] Document unavailable vs. available metrics
- [x] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [x] Draft dashboard on Domo
- [x] Structure data for ETL
- [x] Pipe available metrics to Domo
- [x] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [x] KPIs have been groomed and connected to Domo
- [x] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by jonwehausen** [comment]
Thank you @brianalloyd!

**Comment by jonwehausen** [comment]
@bmcgrady-ep Please refer to ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15196 for a more detailed list of interested metrics upon review of KPIs and grooming metrics.

**Comment by bmcgrady-ep** [comment]
Learning Center KPI | Metric | Source | Go/No Go
------------ | ------------- | ------------- | -------------
Decrease in Contact Center calls | Total MyVA311 Calls by time period | Call Center Data (MyVA11) | ❌ No Go (need updated data)
Veteran "Customer" Satisfaction | Majority of feedback responses are positive (>50% are at least 3/5) | Foresee | ✔️ Go
Increase traffic to benefit hubs | User Count by Benefit Hubs by time period (day, week, or month) | BigQuery | ✔️ Go
% of sign-ins from the Learning Center | `event action` contains `Login - vagovprod` and `page path` contains `www.va.gov/resources` | BigQuery | ✔️ Go
% of VA.gov profiles created from the Learning Center | event capturing profile creation and page path` contains `www.va.gov/resources` | BigQuery | ✔️ Go
% profile task created by way of the Learning Center | `event label` contains `profile` and `page path` contains `www.va.gov/resources` | BigQuery | ✔️ Go

**Comment by bmcgrady-ep** [comment]
@brianalloyd - Can you review and see if the KPIs look right? I interpreted them from the KRs attached in this ticket.

**Comment by joanneesteban** [comment]
@brianalloyd Just following up on this - would you be able to take a look at how we interpreted your KPIs before we move forward?

**Comment by brianalloyd** [comment]
Yes, of course.  I'll follow up as I might need a walk through to ensure interpretation is accurate.

**Comment by joanneesteban** [comment]
@brianalloyd sounds good! Thanks for reviewing. We'll get started on this.

**Comment by bmcgrady-ep** [comment]
@brianalloyd - I have a couple of questions in regards to a few KPIs listed above. 

- First, can you clarify what is meant by **Traffic to Benefit Hubs**? Is this overall traffic or traffic to Benefit Hubs from the LC? Also, just to make sure I have the correct URL, is it www.va.gov/resources?
- Second, can you clarify what is meant by **% profile task created by way of the Learning Center**?

**Comment by brianalloyd** [comment]
@bmcgrady-ep Thanks for the followup, please reference the below responses to your questions.

> 1. URL listed is correct, and we're trying to track traffic to Benefit Hubs from the LC (Veteran reads an article and is now ready to apply for benefits as an example).  

> 2. The intent of this was to track how many profile tasks were influenced by the LC articles.  If this isn't an area that can be tracked not an issue, I can revise the KPI to reflect a better measurable in future iterations.  

> Not an issue on the profile creation, think we've got enough data points that will cover our initial discovery of behavior and support and can relook these through future evolutions.  Appreciate the help and support.  Please reach back out if you need anything else in support of set up.  Please ping me when these are set up as I might need a walk through just to ensure I'm tracking all the track points.

**Comment by bmcgrady-ep** [comment]
Thanks, @brianalloyd for the clarification! 

@JasonTheBearded - For this KPI dashboard, it looks like we will need a few more BigQuery Domo datasets - one for `Traffic to Benefit Hubs` and one for `% profile task created by way of the Learning Center`.

**Comment by brianalloyd** [comment]
Hi @bmcgrady-ep just following up on the status of the KPI Dashboard and if their remains anything I need to close the loop on in support.  Appreciate it, thanks.

**Comment by JasonTheBearded** [comment]
Thanks @bmcgrady-ep I'll get those datasets set up for you.

**Comment by brianalloyd** [comment]
@bmcgrady-ep and @JasonTheBearded just following up on this ticket for a status update on our Dashboard.  Please let me know how I can support and enable the request. Thanks.

**Comment by bmcgrady-ep** [comment]
@brianalloyd - thank you for your patience here. I shared the KPI dashboard with you. Let me know if you have any questions!

**Comment by brianalloyd** [comment]
@bmcgrady-ep thank you so much for the work on this, KPI dashboard looks great and has the data we need to make informed product decisions forward.  Could you also share with @jenniferlee-dsva and @johnhashva?  TIA.

**Comment by bmcgrady-ep** [comment]
@brianalloyd - The dashboard has been shared out. Also, if you want to filter the date range, you can apply a date range filter across the entire dashboard by applying the filter bar at the top of the dashboard.
![image](https://user-images.githubusercontent.com/66263904/102827219-69462d80-439f-11eb-8d7d-b16c96c45ed4.png)

Additionally, you can apply individual filters to the card by dragging the date range you want inside the card itself, but note that it may affect the other individual cards.

**Comment by joanneesteban** [comment]
@brianalloyd 

Here are some other Domo onboarding links as you get acclimated to using Domo:

- [How to view charts](https://knowledge.domo.com/Training/Self-Service_Training/Onboarding_Resources/Analyzer_Card_(KPI_Card)_Basics)
- [Filtering & exporting charts video](https://www.domo.com/help-center/videos/watch/n9mcuvbDkf4)
- [Filtering charts article](https://knowledge.domo.com/Visualize/Adding_Cards_to_Domo/KPI_Cards/KPI_Card_Building_Part_2%3A_The_Analyzer/045Adding_Filters_to_Your_Chart)
- [Exporting charts article](https://knowledge.domo.com/Engage/Sharing_Content_in_Domo/03Exporting_KPI_Cards)
- [Exporting dashboards](https://knowledge.domo.com/Engage/Sharing_Content_in_Domo/Exporting_Domo_Stories_Pages_to_PDF)
- [Filtering dashboards](https://knowledge.domo.com/Optimize/Filtering_Data/02Applying_Page-Level_Filters)

**Comment by joanneesteban** [comment]
@bmcgrady-ep can you do a couple of layout changes?
- [ ] Edit each chart to be its own layout so that the dashboard can export
- [ ] Add the 'Resources & Support - KPIs' as a title to the dashboard itself
- [ ] Add a link to the team's KPIs to the dashboard

**Comment by jonwehausen** [comment]
@bmcgrady-ep 

### Context 
- Last week, we got a request from Jennifer Lee to incorporate additional pieces into the Resources + Support dashboard. 
- Please see the table below for additional components to incorporate into the dashboard
- R+S is already launched so let's prioritize this work accordingly


## Search Engagement 
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Origin/Acquisition     | Search refinements after initial search (What terms are bringing users to Resources and Support components?)  | Table                   |
|2| Baselining             | Organic Search - want to measure out-preform from previous to post launch                                                                       | Table and/or Line graph |
|3| Conversions/Engagement | How often users switch to search "All VA.gov" after searching resources and support articles.                                                                                 | Table                   |
|4| Conversions/Engagement | Resource & Support (LC) search - How often is R&S search component is engaged                                                       |       Table                  |
|5| Conversions/Engagement | Scroll depth - What are the users behaviors in finding related content                                                                                     | Table                   |
|6| Conversions/Engagement | Search Terms (what are users searching for on LC)              | Table                   |

## Exits/Navigation from an Article
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Navigation/Engagement    | global search in the utility nav  | Table            |
|2| Navigation/Engagement         | Breadcrumb                  | Table and/or Line graph |
|3| Navigation/Engagement  | Global menu (fat nav)                                                                                | Table and/or Line graph (However best to view)     |

## Engagement Metrics
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Navigation/Engagement    | Tags (Which tags are being clicked? Frequency?            | Table   |
|2| Navigation/Engagement         | Related information link clicks/engagement                 | Table  |
|3| Navigation/Engagement  | VA benefits link clicks/engagement               | Table and/or Line graph (However best to view)     |
|4| Navigation/Engagement  | CTA button(s) how many clicks on each page/article, bounce rate post click to determine user behavior              | Table and/or Line graph (However best to view)     |

## Customer Satisfaction via: GA Dashboard or Medalia (DOMO)
|#| Category               | Metric                                                                                                               | Potential Widget Type   |
|---|------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------|
|1| Satisfaction/Engagement    | `How do you rate your experience on this page` track response with comparable between good and bad         | Chart/Graph   |
|2| Navigation/Engagement         | Calls via phone number links in the `Need more help` component                | Table  |

**Comment by joanneesteban** [comment]
@bmcgrady-ep - low lift is grabbing the URLs of where these are located in GA.

**Comment by bmcgrady-ep** [comment]
@joanneesteban - The GA Reports have been added to the sub-page on the original KPI dashboard located [here](https://va-gov.domo.com/page/2036788329).

**Comment by bmcgrady-ep** [comment]
Hi @brianalloyd @jenniferlee-dsva - Does Thursday, 1/14, from 12-1pm EST still work for you to meet and discuss the KPI dashboard? Thanks!

**Comment by brianalloyd** [comment]
Works for me. Looping in @johnhashva as well.

**Comment by johnhashva** [comment]
@bmcgrady-ep I'll be there from 12-12:30pm

**Comment by jenniferlee-dsva** [comment]
@bmcgrady-ep - it's on my calendar, thanks!

**Comment by johnhashva** [comment]
@bmcgrady-ep please include me on the invite (I'll listen in for the first 30m) -- TY.

**Comment by bmcgrady-ep** [comment]
@johnhashva - sure thing! I added the meeting to your VA email.

**Comment by johnhashva** [comment]
@bmcgrady-ep looks like that went to my gmail -- so add this one: john.hashimoto@va.gov

**Comment by bmcgrady-ep** [comment]
@johnhashva - Ah yes, I see that I sent it to your gmail. I resent the invite to the VA email.

**Comment by joanneesteban** [comment]
### Some Notes from 1/14/21 Meeting:
_Not all inclusive_

Product questions we should inform with data:

- How well are we encouraging people to sign in or create an account across all of our VA.gov products?
- How can we advocate Content to send people to the right place faster? Instead of sending people to multiple different pages.
- Which articles are getting the most organic search traffic & which places are pushing that traffic?

Notes from Brian L:
> Can we get a lay down of which “Profile events” are being updated as part of the “Influenced Graph”?
> Here’s a list: Search, CTA, TAGs, Related info, VA Benefits hub, Need more help.

> Learning Center has rebranded 

Traffic to Benefit Hubs Chart:
- [ ] Break this down into _where_ the traffic is coming from by content grouping

Sign-Ins from the Learning Center: 
- [ ] Comparison ratio (resources & support vs. benefit hubs, etc.)

Non-Profile Task Engagement:
- [ ] How many people are engaging with these components & which articles are more successful at having people engage with those components? 
- [ ] How deep are people scrolling on Resources & Support? By components to show comparisons between engagement of each of the components?

**Comment by joanneesteban** [comment]
## Additional Meetings Notes
- Traffic to Benefit Hubs from resources and support
- How much traffic are the resources and support articles sending to the Benefit Hubs?
- Combine sign-ins into one chart
- Comparing R+S sign-ins to Benefit Hubs, Profile, Facility Locator, etc.
- How well are they encouraging people to sign-in?
- Break out non-profile task engagement by component
- Here's a list: Search, CTA, TAGs, Related info, VA Benefits hub, Need more help.
- Break it down by bar chart
- Update Dataset to remove date range
- Update LC to Resources and support
- Search
- Searches from articles (VA.gov vs R+S)
- Refinement - refer to YR or Forms dashboard
- Which articles are getting the most organic search traffic
- What search queries are getting people to the most articles?
- Scroll Depth:
- Back to Top button
- Percent of Profile Events influenced by Learning Center - do some research on how this is being calculated

**Comment by joanneesteban** [comment]
@bmcgrady-ep - Notes from Follow Up. Since these should be higher level, we should add GA reports so that the team can dig in further to the data. Feel free to edit as needed.

## Product Value & Trust
### Findability
- **Product Question**: How well are we encouraging Account Creation?
    -  Question for R&S: Would y'all be able to open a [GTM implementation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) so we can look into tracking account creation?
- **Product Question**: How well are we encouraging folks to sign in across VA.gov? And how well do we do this on R&S vs. other parts of VA.gov? 
    - Question for R&S: Is R&S a product, or is it a benefit hub?
    - Suggested chart: Line graph broken down weekly by R&S vs. other VA.gov Benefit Hubs or Products based on R&S team's answer
    - Example: 
![image](https://user-images.githubusercontent.com/48964695/104772743-e61bbb80-5741-11eb-9423-c14d19ed2548.png)

### Ease of Use
- **Product Question**: How are Veterans using the search bar?
    - Example:
    
![image](https://user-images.githubusercontent.com/48964695/104778795-ef118a80-574b-11eb-88c2-bcef8bf81e7b.png)

- **Product Question:** What are Veterans searching for?
    - Example: 
![image](https://user-images.githubusercontent.com/48964695/104778808-f6d12f00-574b-11eb-8a55-0c7ce9e1b139.png)

- **Product Question:** How are Veterans engaging with R&S components?
- Suggested charts: line graphs breaking down the clicks by buttons & link clicks
**Service Completion**
- **Product Question:** How successful are the R&S articles in providing Veterans the information they need?
  - Example:
![image](https://user-images.githubusercontent.com/48964695/104778838-0781a500-574c-11eb-8225-c276da568438.png)

- **Product Question: ** How are Veterans staying on or leaving the R&S pages?
  - Suggested graph: line chart broken down by exits by global global search in the utility nav, breadcrumb, & Global menu
### Trust
- For R&S: We suggest reaching out to the VSP Contact Center team to get surveys added so we can start to track Veteran satisfaction with Resources & Support.

**Comment by brianalloyd** [comment]
@bmcgrady-ep and @joanneesteban these look good, really like the graphs and comparable.  I reengaged the Contact Center team concerning the Medallia functionality in order to track Veteran satisfaction as that capability still doesn't have a clear path yet and may be a few more weeks before coming online.  

I know @jenniferlee-dsva had specific items she desired here and will tag for comment in support.  Thanks again for the effort and work on this front.  CC @johnhashva

**Comment by bmcgrady-ep** [comment]
Thanks for reviewing them, @brianalloyd! How do they look to you @jenniferlee-dsva?

**Comment by jenniferlee-dsva** [comment]
I will add comments/small tweaks directly in the above notes for ease, so we're not having to reference multiple comments for feedback. @joanneesteban  - thank you for the thorough, accurate meeting notes! SOOO helpful.

**Comment by jenniferlee-dsva** [comment]
@bmcgrady-ep - I [answered questions directly in comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16233#issuecomment-761198925) here and included a couple of comments to the [bullet list items here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16233#issuecomment-761152183).   CC @joanneesteban @brianalloyd

**Comment by jenniferlee-dsva** [comment]
Hey all  @joanneesteban @bmcgrady-ep  CC @brianalloyd -[ per this slack](https://dsva.slack.com/archives/C1Q4294JJ/p1611857922023700?thread_ts=1611680409.011600&cid=C1Q4294JJ) - let's hold off on the 'account creation' data here for now. I think this is much more of a global insights baseline than really being super related to RS. I'd like to discuss this DEPO wide as something to track more globally and what that might mean in terms of relevant places/points to track this.

**Comment by bmcgrady-ep** [comment]
Resource and Support KPI | Metric | Source | Status
------------ | ------------- | ------------- | -------------
How well are we encouraging Account Creation? | Account creations from /resources page | BigQuery | 🔶No Go - We aren't currently tracking account creations
How well are we encouraging folks to sign in across VA.gov? And how well do we do this on R&S vs. other parts of VA.gov?| Line graph broken down weekly by R&S vs. other VA.gov Products (**`event_action = Login - vagovprod`**) | BigQuery | ✔️Go - New dataset is needed to look at sign-ins from Resources vs similar products
How are Veterans using the search bar?| Bar chart of R+S searches (**`event_label = view_search_results and event_action contains Resources and support`**) vs All VA.gov searches (**`event_label = view_search_results and event_action contains All Va.gov`**) | [BigQuery](https://va-gov.domo.com/datasources/4abf5c42-b784-4c5d-b228-e8c35e8d07b0/details/overview) | ✔️Go
What are Veterans searching for?| Top 10 search terms (**`event_label = view_search_results and event_action contains Resources and support`**)  | [BigQuery](https://va-gov.domo.com/datasources/4abf5c42-b784-4c5d-b228-e8c35e8d07b0/details/overview) | ✔️Go 
How are Veterans engaging with R&S components?| Line graphs breaking down the clicks by CTA buttons (**`event_label = cta-button-click`**), Tag Clicks (**`event_label = nav-page-tag-click`**), Related Information Clicks (**`event_action contains Navigation - Link List - Related information`**), and VA Benefit Clicks (**`event_action contains Navigation - Link List - VA benefits`**)  | [BigQuery](https://va-gov.domo.com/datasources/4abf5c42-b784-4c5d-b228-e8c35e8d07b0/details/overview) | ✔️Go
How successful are the R&S articles in providing Veterans the information they need?| Table with top 10 articles with 75% scroll depth (**`event_label = 75% Viewed`**) and top 10 articles with 25% scroll depth (**`event_label = 25% Viewed`**)| [BigQuery](https://va-gov.domo.com/datasources/db81efec-91d0-4d27-b999-a9ea27fada0e/details/overview) | ✔️Go - The dataset will need to be updated.
How are Veterans staying on or leaving the R&S pages?|Line chart broken down by exits by Global Search (**`event_label = view_search_results`** and (**`event_action contains All VA.gov`**), Breadcrumb (**`event_label = nav-breadcrumb`**), Global menu (**`event_label = nav-header-link`**), Footer (**`event_label = nav-footer-resources`**), & Footer Superlinks (**`event_label = nav-footer-superlinks`**)| [BigQuery](https://va-gov.domo.com/datasources/f52c3c5d-d0b5-4fe7-8f0b-d89dd502a822/details/overview) | ✔️Go

**Comment by bmcgrady-ep** [comment]
@JasonTheBearded - For the metrics above, there will need to be a couple of datasets added in DOMO.
1) VA.gov sign-ins from different products (sign-ins from /resources pages, Facility Locator, Profile). @jenniferlee-dsva - any particular list of products you would like the sign-ins to be compared to?
2) A dataset is needed for scroll depth events by page. This [dataset](https://va-gov.domo.com/datasources/db81efec-91d0-4d27-b999-a9ea27fada0e/details/overview) is already setup but will need updating to get the necessary data.

Let me know if you have any questions. (I can re-factor the dataset above, but wasn't sure if you wanted to start with a new dataset).

**Comment by jenniferlee-dsva** [comment]
@bmcgrady-ep - replying to your Q above: 

> VA.gov sign-ins from different products (sign-ins from /resources pages, Facility Locator, Profile). @jenniferlee-dsva - any particular list of products you would like the sign-ins to be compared to?

The ones you mention + benefit hub pages:
RS pages - /resources pages
Facility locator pages - /find-locations
Benefit hub pages :
- /burials-memorials
- /careers-employment
- /decision-reviews
- /disability
- /education
- /health-care
- /housing-assistance
- /life-insurance
- /pension
- /records

Feel free to Slack me next time for a faster response - GH email notifications likely to get buried.

**Comment by bmcgrady-ep** [comment]
@JasonTheBearded - Assigning you to this ticket as well as a couple of datasets will need to be created.

**Comment by bmcgrady-ep** [comment]
> @bmcgrady-ep - replying to your Q above:
> 
> > VA.gov sign-ins from different products (sign-ins from /resources pages, Facility Locator, Profile). @jenniferlee-dsva - any particular list of products you would like the sign-ins to be compared to?
> 
> The ones you mention + benefit hub pages:
> RS pages - /resources pages
> Facility locator pages - /find-locations
> Benefit hub pages :
> 
> * /burials-memorials
> * /careers-employment
> * /decision-reviews
> * /disability
> * /education
> * /health-care
> * /housing-assistance
> * /life-insurance
> * /pension
> * /records
> 
> Feel free to Slack me next time for a faster response - GH email notifications likely to get buried.

@jenniferlee-dsva - Thank you for the response. This will be helpful for our team in building out the dashboard.

**Comment by joanneesteban** [comment]
@brianalloyd - unfortunately, our resources are a bit limited right now and have needed to shuffle our resources around (our teammate who was assigned to work on this in out of office for the foreseeable future due to the Texas blackouts). We're anticipating pulling this work back into another sprint (in March), but please let us know if there are metrics in Google Analytics that we can help you with in the meantime.
