### ISSUE TITLE
VSP IA feedback - Usability testing prep - Vet centers

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#16235]
**Feedback framework**
- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Feedback and Questions

**Consider**
- Although the breadcrumb is not completely defined yet, that element can provide context to the overall page, so ensuring the language and placement are represented in a realistic manner.  Things to consider..
  - Are these pages a direct replacement of the existing single detail pages for Vet Centers (i.e. https://www.va.gov/find-locations/facility/vc_0304V)?
  - Is there intended to be an overall landing page for providing general information about Vet Centers that these pages would be related to?
- Look at reducing the number of links within the "on this page" component for easier scanning.  Some ideas to look at:
  - the first link goes to a section that appears promotional in nature, could remove yellow boxes and label this as an "about us" type section
  - Location and Other access points could be combined into a single option/section for locations
  - The bottom 4 options could be combined into a single option/section for services

## Definition of Done
- [ ] Must feedback is implemented on staging
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by mmiddaugh** [comment]
The design for Vet Centers has changed since this issue was created and additional IA feedback has been provided.
