### ISSUE TITLE
Add custom screener travel question for Alaska (14 days)

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#16239]
@artsymartha68 commented on [Mon Nov 16 2020](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20157)

@artsymartha68 commented on [Mon Nov 16 2020](https://github.com/department-of-veterans-affairs/dsva/issues/32)

@artsymartha68 commented on [Mon Nov 16 2020](https://github.com/department-of-veterans-affairs/vets-website/issues/14980)

We have a request from the field to add a custom question for Alaska travel. They are ok with the 14 day window, same as the other locales we have done. 

I do not have a list of all the Alaska facilities.

**Comment by batemapf** [comment]
en: 'Have you had contact with someone who has traveled outside of Alaska within the last 14 days?'
es: '¿Ha tenido contacto con alguien que haya viajado fuera de Alaska en los últimos 14 días?'

AK facilities code (all): vha_463
