### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#16237]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address

kirkland.wallace@va.gov (Kirkland Wallace)

Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [x] Domo
_Please list any additional requirements, if any._

As per our Slack discussion I am requesting that someone from the analytics team have a brief consultation with the VBA program analyst stakeholder to discuss the kinds of metrics and reports that are available to the program at launch. (This is for PCPG CH36 benefits, form 8832, launching 4 Jan 2021.) 

## Date Required
_Please share the date you require access._

Week of 16 Nov 2020

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

I'm DEPO lead for vsa-ebenefits, stakeholder is a program analyst with Office of Transition and Economic Development.

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @steve-gov , 

Thank you for your request! We have provisioned Google Analytics 360 and DOMO account access for Kirkland at the email you provided (kirkland.wallace@va.gov). She should have received invitation emails for each platform. 

We will close this issue but please feel free to reopen if any access related concerns arise.
