### ISSUE TITLE
Add tracking event to CC review page

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16248]
## Issue Description
To help inform iterations of community care provider selection, add tracking event to community care request review page.

---
## Tasks
- [ ] Track # of CC providers as submission request event

---
## Tech Notes
Per Analytics [comments](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15834#issuecomment-727055684) in #15834, add event as follows:
```js
'event': 'vaos-community-care-submission',
'vaos-number-of-preferred-providers': 1,
...(other parameters already on this event)...
```
![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/58f87b98-cd0f-49c1-942b-ec151d821365)

**Comment by laurenernest** [comment]
@bsmartin-ep Can you confirm you're seeing this on your end?

@vbahinwillit what would you say the LOE for this work was? (points-wise)

**Comment by bsmartin-ep** [comment]
Looks good @laurenernest:

![image](https://user-images.githubusercontent.com/62304138/99884222-88179f80-2bfa-11eb-9db0-5e6b17598b07.png)

@bmcgrady-ep / @jonwehausen -

For QA purposes, these VAOS CC changes are split between two GTM workspaces:

Design system changes:
https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000382

Everything else:
https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000391

**Comment by bmcgrady-ep** [comment]
@bsmartin-ep - Do you have a recommended test user? I have not been able to go through the entire appointment scheduling in staging.

**Comment by bmcgrady-ep** [comment]
### QA for Non-Design system changes
Interaction|GTM Screenshot|Results
---|---|---
DL - vaos-number-of-preferred-providers| ![image](https://user-images.githubusercontent.com/66263904/100161719-3592e900-2e6f-11eb-92cc-346bf2c6f3da.png)![image](https://user-images.githubusercontent.com/66263904/100161828-712db300-2e6f-11eb-8cea-62d54ed8af18.png) | **PASS** ✔️

**Comment by bmcgrady-ep** [comment]
### QA for Design system changes
Interaction|GTM Screenshot|Results
---|---|---
`int-radio-button-option-click` | ![image](https://user-images.githubusercontent.com/66263904/100286522-33dd2a00-2f30-11eb-8944-b8bb7ca9606d.png)| **FAIL** ❌
`vaos-community-care-submission` | ![image](https://user-images.githubusercontent.com/66263904/100288036-0fcf1800-2f33-11eb-89dd-7bfdfe98c986.png)| **PASS** ✔️

cc @bsmartin-ep

**Comment by laurenernest** [comment]
@bmcgrady-ep Thanks for checking the submission event. We're tracking the fix for the incorrect radio button prefix in #16487
