### ISSUE TITLE
R&S Search Bar: Remove bottom border on search

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#16241]
## Issue Description
_Need to remove bottom border on search form's mobile display (since the search has a gray container)_

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by ncksllvn** [comment]
Thank you @brianalloyd but @andaleliz actually beat you to it in this ticket, https://github.com/department-of-veterans-affairs/va.gov-team/issues/16227. I should have flagged it but I was preoccupied at the time. Sorry about that.

**Comment by brianalloyd** [comment]
No issue, I see it now.  I'll close this out as a duplicate.  Thanks @ncksllvn
