### ISSUE TITLE
VSP content review - Usability prep - Vet Center 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#16243]
User story
This ticket captures VSP content feedback on Vet Center prototype. 

Prototype link: https://preview.uxpin.com/603da0b67ccefbbee74fcd8bb77a8fed12baabb5#/pages/134151554/simulate/no-panels?mode=cvhidm

Acceptance criteria
 - [x] VSP/Peggy provides content feedback for the form/tool and any associated static pages
- [ ]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [ ]  Teams leaves comments about any feedback they decide not to take
- [ ]  Peggy checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
Hi, @lildziner @mmiddaugh 

I have some general content questions for this work:  

-- What type of content feedback are you needing at this stage?  I recall that you still needed to get feedback from SMEs on Vet Center taxonomies to ensure they are in alignment with the existing health care taxonomies. Is this still outstanding? 

-- How much of the content on this page is templated vs. specific to the Vet Center? 

-- How will users navigate to these Vet Center pages? 

-- as part of this effort, will there also be changes to existing static pages that mention Vet Centers?

**Comment by lildziner** [comment]
[Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1603629469594/94d7825c23f0eff800a5271bf396293535ef5de7?wid=0-1605618343012&outline=open) with broad outline of the usability test.

**Comment by mmiddaugh** [comment]
Hi @peggygannon 

-- **How much of the content on this page is templated vs. specific to the Vet Center?** We're still working on the governance for this. Generally speaking, we're hoping most of the content will be national (or based on data) with local Vet Centers responsible for the particular services at their location. 

-- **How will users navigate to these Vet Center pages?** They will link from the Facility Locator search results, much like Pittsburgh VAMC. We're evaluating cross-linking opportunities (i.e. from the VAMC page)

-- **as part of this effort, will there also be changes to existing static pages that mention Vet Centers?** Right now we're focused on any links which point to the Facility Locator with the goal of pre-populating Vet Center in the facility type field. Not all of the pages are within our control so we're starting with the low-hanging fruit. 

@davidconlon

**Comment by peggygannon** [comment]
Closing. This effort is still early in the discovery phase. More detailed content feedback will likely be provided at later stage.
