### ISSUE TITLE
Access for Nicole Houston

### ISSUE THREAD

**Issue by nwalker-va** [department-of-veterans-affairs/va.gov-team#16244]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   Cecelia Lee
- Please provide your name.
   Nicole Houston
- Please Provide your email.
   nicole.houston@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   Quokka: engineer: Oddball

- Requesting SSH key authorization?
   NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABgQDFfQ83w5oKJzmbiErt7fh899IZbXuPPhLcgUsVottLvYB1aR6TnO6OUfdP+2M8wibB1v37eU2SAlMRR2kGhe3Lk4N5jrkq1zfD2oUF+X6c+lP2Z5VlnpvtEBU6WQHv6Q+5P3erkdUA72PJfuCoZwtZdSXN2IaBBS9CWDD8rrP/xfIsKJhM0OQzC3Qk2QNxOO6RZQ3oL1xQUOxi0nGNtEmzDEKtVBqHnVV+ypCi/EZKWN1hfdHcDMCJxGDpnsTU1dGjhnApG7ERCoyKSGHWqNPjx+df5Hd5GEa4ACd4pXpxLVFYJFYtq6OhXor/eKQDADUow7TYLkK2RYkX/vRhojMlQgABdaFrOFdvovFbCQ2sBosqgNUd8Its6qlaugN4qTpgplb0gYTjQdg5FzJDzp5+ttWaPdQ6BfhFeePxOGz+7nRRXpHiblujpJQrTJo4vlgOBtH0NyASaLCX14ozeicCoGkMjvcuJrnhB+by485su4inLwV0McD0zhp/q2rW138=nicole.houston@oddball.io
```

- Grant AWS Console access?
  I have AWS Console access, but I need permissions for DynamoDB
  - What AWS services do you need access to and why? 
 Read access for DynamoDB. I am working on a ticket for the developer-portal-backend and trying to run some integration tests, but I keep receiving AccessDeniedException that says I am not authorized to perform dynamoDB: San. I need to run the tests to make sure I didn't break anything.

**Comment by jbritt1** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/7612

**Comment by jhouse-solvd** [comment]
According to a conversation with Nancy Smith @ Oddball, Nicole has the access that she needs, and I believe this can be closed.
