### ISSUE TITLE
Access for Beau Grantham

### ISSUE THREAD

**Issue by beaugrantham-va** [department-of-veterans-affairs/va.gov-team#16254]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Beau Grantham
- Please Provide your email.
   > beau.grantham@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES (already established)

- Grant AWS Console access?
  > YES (already established, needs update, see below)
 
- What AWS services do you need access to and why? 
  > Need to be added to `dvp-developers` and `lighthouse-developers` group per Tom Dugan to use AWS services like CodeBuild.

**Comment by beaugrantham-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by beaugrantham-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@beaugrantham-va I'll get you squared away.

**Comment by jsev-io** [comment]
@beaugrantham-va Group changes updated
