### ISSUE TITLE
Platform Newsletter: November Issue

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#16251]
Requesting content review of the November newsletter.

Link to draft newsletter: https://us19.admin.mailchimp.com/campaigns/wizard/neapolitan?id=4565852#

Target release date for newsletter: by 11/23

**Comment by gmaciolek** [comment]
@jchasia-adhoc Hi James, Amy is going to work on this and will have it reviewed and ready by mid-day Friday.

**Comment by jchasia-adhoc** [comment]
@gmaciolek Thanks! Let us know if there are any questions.

**Comment by lianilychee** [comment]
Closing, the work is very done now.
