### ISSUE TITLE
Public prefix is still showing up in some download URLs

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#16250]
Diffs in /pittsburgh-health-care/university-drive-campus-map/index.html reveal the following:

![index_html_vs__index_html.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/da3ced15-0cb8-4459-afb6-24dd45ba54fc)

Note the `public://` prefix on the download URL.

We also see some incorrect URLs such as `<img src="/img/styles/2_1_medium_thumbnail/public/2019-03/university-drive-map.png"`.

This is not facilities-specific:

```
❯ find . -name "*.html" -exec grep "public:/" {} \; -print
                        "url": "public://hub_promos/life-insurance.png",
./life-insurance/index.html
                        "url": "public://hub_promos/records.png",
./records/index.html
                        "url": "public://hub_promos/education.png",
./education/index.html
                        "url": "public://hub_promos/housing.png",
./housing-assistance/index.html
                            "url": "public://2020-09/ROB1.jpg",
```

The solution applied in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14770) did not fully address this problem, and may need to be applied more broadly. Or maybe we should fix the CMS export to use the correct prefix.

**Comment by jhonnyoddball** [comment]
Fixed on PR [15026](https://github.com/department-of-veterans-affairs/vets-website/pull/15026)
