### ISSUE TITLE
Design Feedback - Usability Testing Prep - Facilities [Vet Center pages]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#16263]
I love the direction of this page!

- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

Thoughts/questions:
What are your thoughts on using the warning color with the feature story style?
Leyda: looking for a lighter tone
Allison/Emily: This is a great opportunity to help the "feature story" style. I would suggest bringing this up in the usability testing. Maybe some A/B testing on colors and styles? There is some concern that we have established a pattern with the warning color.

**Must:**

- Put the address under “Main location and contact info” in the style on [https://design.va.gov/components/address-block](https://design.va.gov/components/address-block)

- Remove the h tag from the Call us 404-417-5414 and Email us atlantavetcenter@va.gov

**Should:**

- “Get Directions” should be on its own line

- “If you need to talk with someone confidentially, after hours, call the Vet Center call center anytime 24/7 at 877-927-8387.” should be in the warning alert color box. You could use the one with the icon or background only [https://design.va.gov/components/alertboxes#warning-alert](https://design.va.gov/components/alertboxes#warning-alert)

**Consider:**

- None

**Definition of Done:**
- [x] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Allison will close the ticket once those things are all set. Thank you!

**Comment by mmiddaugh** [comment]
@lildziner can you confirm this can be closed?

**Comment by lildziner** [comment]
@mmiddaugh yes, thank you. Closing this issue.
