### ISSUE TITLE
[Feature] Dynamic mock form dates

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#16262]
## Description

Mock data is stored in JSON and includes hard-coded date strings, e.g. `2015-12-01`. In some instances, these dates need to be set within a specific time period to make it valid for a specific form. For example:

- Form 526 Benefits Delivery at Discharge flow can only be entered into, or tested, when the military service history includes a discharge date between 90 and 180 days from the current date.
- Form 996 Higher-Level Review can only process eligible contestable issues with decisions in the last year

Currently, we would either need to update the specific data prior to unit/e2e testing, or manually update the dates when working with the form locally or in our staging environment. This includes the mock data pasted into the save-in-progress menu.

This request is to include a manipulation pattern within the JSON to indicate that the date needs to be specifically processed. For example, if today is `2020-11-15`:

- `{+1M+10d}` (add one month and 10 days) would result in a date of `2020-12-25`
- `{-1years-1months+10days}` (subtract one year, subtract 1 month and add 10 days) would result in a date of `2019-10-05`
- Form example:

  ```json
  {
    "contestedIssues": [
      {
        "type": "contestableIssue",
        "attributes": {
          "ratingIssueSubjectText": "Headaches",
          "description": "Acute chronic head pain",
          "ratingIssuePercentNumber": 20,
          "approxDecisionDate": "{-6months}",
          "decisionIssueId": 44,
          "ratingIssueReferenceId": "66",
          "ratingDecisionReferenceId": null
        },
        "view:selected": true
      }
    ]
  }
  ```

The above examples are using the `add` [Moment keys](https://momentjs.com/docs/#/manipulating/add/)

## Acceptance criteria

- [ ] Include dynamic form date data in mock data

**Comment by caw310** [comment]
@Mottie is this still needed?

**Comment by Mottie** [comment]
Hmmm...
- Changing the data in the `vets-api-mockdata` repo doesn't effect the data in staging.va.gov - you have to edit the data in VBMS
- This would be helpful for data you can paste into the [save-in-progress menu](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-use-the-save-in-progress-m), so you don't need to manually edit it
