### ISSUE TITLE
Analytics Implementation for GI Bill Profile Page -  Section 107

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#1627]
# Analytics Implementation or QA Request
This is the Analytics Implementation request for the Colmery Section 107, Housing based on Location. This is a follow-up to the issue posted on #19642. 

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- This request is for tracking engagement with the housing section of the 107 selection on a GI Bill profile page. 

- Who is this request for?

    - Booz Allen Hamilton - VA Education Services
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VSP-Analytics`._
    
- What team/project is this work for?

    - Booz Allen Hamilton - VA Education Services
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. https://staging.va.gov/gi-bill-comparison-tool/profile/14904420
    
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* Select Apply for benefits at the top of the profile page
    - *Other User Interactions*: 

        - Selection of 'Learn More' in 107 question (e.g. where will you take the majority of classes)
        - User selects extension from dropdown
        - User types zip code into text field
        - Scrolling on page and viewing updated benefits
        - Scrolling on page and visits one or more alternate school locations
 

- Sample Users when authentication is required

    - N/A

- Test Users to replicate the event

    - N/A

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [x] Analytics-Insights provides guidance on requests, including any limitations 
- [ ] Analytics-Insights documents dataLayer requirements and updates Google Tag Manager
- [ ] FE implements dataLayer and notifies Analytics-Insights
- [ ] Analytics-Insights validates on staging
- [ ] Analytics-Insights publishes Google Tag Manager

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
9/23/2019 - Additional context was provided to BAH team on how to handle International checkbox

**Comment by nedierecel** [comment]
Adding `blocked` temporarily until devs are able to work on it, per the discussion on the [Vets.gov repo](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19642):

>still tracking this. Dev's have not picked up the story to update the UI yet.

**Comment by nedierecel** [comment]
@amyknox @KevinMHoffmanUSDS I wanted to nudge this request to see if we should expect to validate soon. I understand it is in backlog but wanted to see if it might be a priority soon.

**Comment by amyknox** [comment]
Nedie - 107 updates for international branches & extensions are in staging now.  

Functional permutation visible on this profile page (University of Florida in Panama): https://staging.va.gov/gi-bill-comparison-tool/profile/11816110

107 Question:  Where will you take the majority of your classes?

**Comment by nedierecel** [comment]
Thanks @amyknox Confirming I received this and will QA.

**Comment by nedierecel** [comment]
@amyknox Do you also have a facility that has the extension available? 

QA Findings:
- For this facility, when I entered in my location in the zip, I did not see this expected event after the results appeared `gibctZipCodeExtensionSearch`

_Zip Code Search_
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/eccb3e83-cc39-449b-a3d4-6395f9250dfa)

**Comment by amyknox** [comment]
@nedierecel University of Minnesota has an extension dropdown
https://staging.va.gov/gi-bill-comparison-tool/profile/11802123

**Comment by amyknox** [comment]
@nedierecel - Since you didn't see the event triggers, what happens now? Is remediation work for the analytics team, the Booz team or another team?

If the Booz team, do we need to create the story to outline that work or do you do that?

**Comment by nedierecel** [comment]
@amyknox Apologies for not being clear on next steps. The remediation would be back on the Booz team, using the dataLayer events provided in: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19642#issuecomment-537604711

We can then QA again to ensure that the events outlined here are triggering with the following form interactions:

- [x] How do you want to take classes? 
- [ ] Where will you take the majority of your classes? (Extension Campus Selection)
- [ ] Choose the location where you'll take your classes
- [ ] I'll be taking classes outside of the U.S. and U.S. territories
- [ ] Zip code search

**Comment by amyknox** [comment]
@nedierecel 

For this datalayer push,
dataLayer.push({'event': 'gibct-form-change', 'gibct-form-field': 'gibctExtensionCampusDropdown', 'gibct-form-value': 'Insert location here'});

Some extension campuses use the same name - there are a number of "Strayer University" entries, for example.  We're looking for ways to distinguish these extensions in GA.  We could use the City & State for that extension or we could use the facility code in addition to the name of the institution.   

Interested to get your input on which approach you think would be the best & most va.gov compliant.  

CC - @ksantiagomorgan6

**Comment by nedierecel** [comment]
@amyknox Confirming I've seen this and will look into the compliance piece.

**Comment by nedierecel** [comment]
@amyknox From our Slack discussion, I am leaning toward the former where the school name and its "City & State" are populated into the form-value parameter. This also assumes that there would not be multiple facilities sharing the same City-State combination.

`dataLayer.push({'event': 'gibct-form-change', 'gibct-form-field': 'gibctExtensionCampusDropdown', 'gibct-form-value': 'Strayer University-Virginia Beach VA'});`

The logic in choosing this is that other GA users consuming the data might not readily have access to the facility codes, so this would more cleanly display the facility's location.

**Comment by amyknox** [comment]
Thanks @nedierecel - Kenny's putting it into place and will submit for review tomorrow.

**Comment by nedierecel** [comment]
Confirming that the final QA has been completed on staging, with comments posted for BAH team on https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19642
