### ISSUE TITLE
Analytics Reporting Request for Glennette Clark

### ISSUE THREAD

**Issue by glennettec** [department-of-veterans-affairs/va.gov-team#16276]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Glennette Clark - glennette.clark@usds.dhs.gov

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    - Veteran's Health Experience
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after)?
N/A

## Analytics to Track Down
> Examples
> 
> - [ ] smclinician.myhealth.va.gov/mhv-sm-web/loginhome.action
> - [ ] smclinician.myhealth.va.gov/mhv-sm-web/readmessage.action
> - [ ] smclinician.myhealth.va.gov/mhv-sm-web/leftnav.action

## Which Product Questions are you trying to answer?

I'm running GA on myhealth.va.gov. The sample pages listed above showed up as having Users, Pageviews, Sessions, etc. attributed to them. I'd like to know if they should be counted as regular web pages or do they reference something else. 

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks for the request, @glennettec !

**Comment by joanneesteban** [comment]
Switching to @jonwehausen due to DAP access requirements.

**Comment by jonwehausen** [comment]
Hi @glennettec , 

Thank you for your patience on our fulfillment of this request. 

As a preface to your request -- Just wanted to make you aware the pages you requested metrics for are surfaced directly from the Digital Analytics Program Google Analytics account and this account is not managed by our team directly. 

That being said, I personally do have access to this account and was able to create a [custom report on your behalf](https://analytics.google.com/analytics/web/template?uid=Ifnx_fJTR0eTHIhf3wDd_A). Please feel free to use this custom report template by adding to the Veterans Affairs Agency view and/or this [direct report link ](https://analytics.google.com/analytics/web/#/report/content-pages/a33523145w60822123p68076838/explorer-table.filter=smclinician.myhealth.va.gov&explorer-table.plotKeys=%5B%5D)(minus users unfortunately) . From there you can adjust the date range in the top right hand corner for your desired time frame. 

![image](https://user-images.githubusercontent.com/48527022/100805521-ca13c300-33fc-11eb-982c-80ab5394bedf.png)

To your question, I unfortunately don't have direct access to those pages (i.e smclinician.myhealth.va.gov/mhv-sm-web/leftnav.action
) to pass judgment on if these should be accurately reflected as standard webpages.  If you could provide further context on these pages or how we might be able to access an example, we can make a better determination.

We certainly hope this helps and we look forward to hearing from you.

**Comment by jonwehausen** [comment]
cc: @joanneesteban & @bmcgrady-ep for visibility, no further action needed at this time

**Comment by joanneesteban** [comment]
Thanks, @jonwehausen ! @glennettec we're closing this ticket, but please feel free to reopen if you have any additional questions.
