### ISSUE TITLE
NON-UAT Bug Reporting 

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#1628]
This ticket captures live site bugs that are not part of UAT.
### Bug 1
**Issue:** Download VA benefit letters root page is showing the wrong nav and parent menu.
_(Think this is a Drupal page but we should have a ticket to track it.)_ 
- Device: Government Furnished Equipment (GFE) PC
- Browser: Chrome
- Test User _(if applicable)_: Jennifer Lee

Attached: correct menu/nav (archive view).

![image.png](https://images.zenhubusercontent.com/5d5ab731409ffe1c4506543b/4cc3c3f3-a506-41a5-b565-97a922ccd84f)

### Bug 2
**Issue:** Download VA benefit letters root page is showing the wrong nav and parent menu.
- Device: Government Furnished Equipment (GFE) PC
- Browser: Chrome
- Test User _(if applicable)_: Jennifer Lee

_Currently showing the Careers and employment menu:_
![image(1).png](https://images.zenhubusercontent.com/5d5ab731409ffe1c4506543b/81631cff-133f-4d8c-9715-b4bd4f3aef8f)

### Bug 3
**Issue:** On the Camp Lejeune water contamination page, the VA Form 10-10068b opens in a weird scrolling window that shows like 1 inch of content at a time. 
- Device: Government Furnished Equipment (GFE) PC
- Browser: Chrome
- Test User _(if applicable)_: Jennifer Lee
- Link: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination/

_I don't think this is a Drupal fix, but I'm not sure. It appears this way on both the live Github instance and the Drupal prod.cms instance._

![image(2)](https://user-images.githubusercontent.com/42546515/64568026-abbd3580-d327-11e9-8b58-4465df04b3f9.png)
![image(3)](https://user-images.githubusercontent.com/42546515/64568189-25edba00-d328-11e9-96ba-d5547a26caf9.png)

### Bug 4
**Issue:** Like Bug 3, VA Form 10-10068 opens in a weird scrolling window that shows like 1 inch of content at a time. 
- Device: Government Furnished Equipment (GFE) PC
- Browser: Chrome
- Test User _(if applicable)_: Jennifer Lee
- Link: https://www.clfamilymembers.fsc.va.gov/Home/DownloadForm/10-10068

**Comment by Karak888** [comment]
started by @jenniferlee-dsva tracking to keep updated of non-UAT bugs as list.  @RLHecht will help cover -  This ticket is being closed as it will be split into tickets to work in Drupal!

**Comment by RLHecht** [comment]
@jenniferlee-dsva Just started looking at this to see what the bugs were. I'm not seeing the wrong  nav and parent menu on the Download VA benefits letters page on Drupal or the live site. Can you open it in preview again to see if it's still the case for you?

**Comment by jenniferlee-dsva** [comment]
@RLHecht - Looks like that has been fixed in the CMS now!

**Comment by RLHecht** [comment]
@ncksllvn @kelsonic See bugs 3 and 4 above. Not sure if you guys are the ones to help with this but I'm trying to figure out if there's a way to fix the PDF from opening in that weird two-inch scrolling way. Seems to be happening on both Drupal and Github. Any suggestions?

**Comment by kelsonic** [comment]
@RLHecht I'm not entirely sure where this is rendered in the codebase, yet. I'll discuss the 2 bugs with @ncksllvn here shortly so I can get more details. Thanks! :)

**Comment by kelsonic** [comment]
After reviewing with @ncksllvn, it looks like we don't control either PDFs for bugs 3 and 4. I'm not sure who maintains those forms (https://www.clfamilymembers.fsc.va.gov/Home/DownloadForm/10-10068b and https://www.clfamilymembers.fsc.va.gov/Home/DownloadForm/10-10068) but they will need to update the code on their side. My guess is it's the same team that maintains https://www.clfamilymembers.fsc.va.gov :)

**Comment by RLHecht** [comment]
@jenniferlee-dsva see Kelson's comment above regarding the PDF that isn't showing the whole page when it opens. Do you know who we would reach out to about this?

**Comment by jenniferlee-dsva** [comment]
I think the Agent Orange SME just retired, but I think we can reach out to Misty Sweet in VBA. Do you feel comfortable reaching out to her directly via email, and just CC me? It sounds like we can't fix this but VBA will need to find the form owner to get it fixed - is that it?

**Comment by ncksllvn** [comment]
The form links - https://www.clfamilymembers.fsc.va.gov/Home/DownloadForm/10-10068b and https://www.clfamilymembers.fsc.va.gov/Home/DownloadForm/10-10068 - aren't linking to true PDFs; they're linking to HTML pages with the PDFs embedded in a very strange way. I wonder if we can just ask them for direct links to the PDFs to get around this?

**Comment by RLHecht** [comment]
@jenniferlee-dsva I am comfortable reaching out to Misty and I'll cc you. I'll let her know what's happening and see if she can provide direct links to the PDFs like @ncksllvn just suggested.
