### ISSUE TITLE
Bug: Delete erroneous RS page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#16286]
## Bug: Delete erroneous RS page: https://www.va.gov/resources/search/

This RS search page was mistakenly created as part of the RS search behavior. We resolved that bug, but this page still appears to be valid. (I clicked into it from a random, unrelated GH ticket.) 

To ensure that this page doesn't get indexed, could we delete it? It is an orphan page that we don't use. 

ETA: Not urgent, but before we add RS to sitemap for indexing. 

Including @mnorthuis to confirm that there's no issue with eliminating this unused orphan page.

**Comment by ncksllvn** [comment]
@jenniferlee-dsva that's the search application for R&S (sans query in the URL). It is a React app. What you see when you go there is just wording for the unlikely edge case of when a query isn't present in the URL.

We can remove it from the sitemap and do a redirect to the R&S homepage if there isn't a user query. 

The va.gov/search page is in the sitemap

![image](https://user-images.githubusercontent.com/1915775/99446331-df60fb80-28ec-11eb-9df6-63b836fd53c5.png)

When you go there though it just redirects you the va.gov homepage.

**Comment by mnorthuis** [comment]
@ncksllvn can we implement a redirect to that url when no parameters are present to send the user to the R&S landing page?

If you remove it from the sitemap, then R&S search results will not be indexed.

**Comment by ncksllvn** [comment]
Yeah we can do a redirect when there is no query in the URL l(ike how `va.gov/search` does it.)

**Comment by ncksllvn** [comment]
We can also exclude the page from the sitemap. Should those two things be added as the acceptance criteria in this ticket?

**Comment by jenniferlee-dsva** [comment]
If you recommend we should do that, yes please.

**Comment by ncksllvn** [comment]
It would get rid of whatever SEO value it might have otherwise. Personally I like being able to get to the page w/o a query in the URL but a redirect is the only real way to get rid of any traffic it might get otherwise.

**Comment by ncksllvn** [comment]
This is live 🎉

**Comment by jenniferlee-dsva** [comment]
Validated! Ty!
