### ISSUE TITLE
Access for Brooks Johnson

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#16283]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Brooks Johnson
- Please Provide your email.
   > brooks@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I'm an Ad Hoc employee working on the VSP Design System team as a frontend engineer

- Requesting SSH key authorization?
   >NO 

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > I need to be able to test and setup a deployment to s3 for design.va.gov

**Comment by bkjohnson** [comment]
Tagging @department-of-veterans-affairs/vsp-operations for review

**Comment by omgitsbillryan** [comment]
For AWS Access:

User: Brooks Johnson
COR: Jeff Hayter
Approval required: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@omgitsbillryan Approved for AWS access.

**Comment by bkjohnson** [comment]
Thank you!
