### ISSUE TITLE
Final Punch List for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16299]
`- Consider breaking this ticket up?`
`- Not a conflict for e2e partner testing on Dec 1, 2020`

## Background
Based on the latest list from [Design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/text-revisions/CH36-punch-list-1020.md) we need to implement these items:

Note if out of scope = 🙈

### CH31 throughout
- [x] Double check breadcrumbs

### CH31 screening wizard
- [x] Change H1 to: "Apply for Veteran Readiness and Employment with VA Form 28-1900"
- [x] Remove "I know this is the form I need" section
- [x] Add "Is this the form I need?" section to match prototype
- [x] Change question: "Did you receive an other than dishonorable discharge?" to "Did you receive a discharge status other than dishonorable?"
- [x] Change all stop/alert message boxes within wizard from blue to light gray (#F1F1F1)
- [x] Change link in second alert box (discharge question) to: "Learn more about how to apply for a discharge upgrade"
- [x] Add link in years of separation alert box: "Learn more about VR&E eligibility"

`VR&E orientation module in design TBD; will be added to intro screen`

### VA form 22-1900 intro screen
- [x] Remove hyphen from "Start your application without signing in" link
- [x] Fix typo in Prepare section: lower-case i on "(if you know it)"
- [x] Fix typo in Prepare section: comma after "phone number"
- [x] In Apply section, change first line to: "Complete this Veteran Readiness and Employment form."
- [x] In Decision section change paragraph to match prototype

### VA form 22-1900
- [X] Change form stepper to match current form conventions in mockups
- [X] Fix stepper sequence to align with current step in mockups
~[ ] Change first section header to "Applicant information"~ 🙈
- [x] Change label parentheses for Your VA file number to "(only if different than your SSN)"
- [x] Adjust form address blocks to new pattern (see prototype)
- [x] Change paragraph on Additional info screen to: "The below information is optional. You don’t have to answer these questions now, but we may ask for this information again when we process your application."
- [x] Add "(include K-12 and each year of college)" to years of school question
- [x] Revise all text on Communication pref screen to match prototype

### VA form 22-1900 confirmation screen
- [ ] ~~Remove "Thank you for submitting your application" from blue box~~  Keep
- [x] Add "What happens after I apply?" text block above "How long..." section
- [ ] ~~Confirm with SMEs that processing takes one week~~ Generalize: @sporeboy 
- [X] Confirm 800 number(s): Number is 1-800-827-1000 per [fact sheet](https://www.benefits.va.gov/BENEFITS/factsheets/serviceconnected/CH31FactSheet.pdf)
- [x] Change paragraph at bottom of page to: "Please call our toll-free hotline at 800-827-1000. We’re here Monday through Friday, 8:00 am to 
8:00 pm ET."

### Non-FE Tasks
- [ ] TBD 

## Acceptance Criteria
- [ ] The list above has been completed or noted that is either out of scope or needs more grooming
- [ ] A PR has been requested for merging

**Comment by micahchiang** [comment]
The wizard updates in this punch list are included in this pull request for #16365 - https://github.com/department-of-veterans-affairs/vets-website/pull/14761
