### ISSUE TITLE
How does the app deal with asynchronous back-end tasks?

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#16290]
Vets API has multiple calls that do asynchronous updates, which can lead to data drift between the servers and the app. This can be confusing for a Veteran when they have completed an update of a claim or personal information but the system doesn't immediately reflect those updates.

How should the mobile app/mobile API deal with these situations? 
How is this presented to the Veteran in the app?

**Comment by bessgreen** [comment]
Patrick meeting with Claims dev team on Thursday
