### ISSUE TITLE
documentation on prometheus restore procedures

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#163]
## Description

We do snapshots of the EBS volumes during deploy, but Prometheus seems to be missing some information on how we would restore from backup in the new setup. We should do a tabletop exercise and write the steps needed so we can use them if needed.

## AC

- [ ] documentation of recovery steps needed for Prometheus specifically in "devops" repo

**Comment by ricetj** [comment]
This will change when we upgrade. We are pretty sure restore is 50/50 with current snapshots.
