### ISSUE TITLE
Update button label for authenticated schedule appointment page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16308]
## What happened?
When logged in as a Cerner user, the CTA buttons for non-Cerner VA facilities point correctly to the VA appointments tool, but the labels still say **Go to My HealtheVet**. They should say **Go to the VA appointments tool**.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/e5186e51-b2fa-4095-a466-d3392669f457)

## Specs:
- Device: n/a
- Browser: n/a
- Test User _(if applicable)_: mhvtestvet01

## Steps to Reproduce
- URL: https://www.va.gov/health-care/schedule-view-va-appointments/
- Test User _(if applicable)_: mhvtestvet01

## Desired behavior
The button labels for all non-Cerner facilities should say **Go to the VA appointments tool** 

## Acceptance Criteria
- [ ] Button labels are updated 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kelsonic @brianalloyd. Lauren reported this bug, and I'm submitting issue to fix. Please reach out with any questions. Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @brianalloyd @youngfreezyVA @kelsonic . Just connecting dots here. I'd originally logged a similar bug about this issue during the Cerner launch week. We didn't want to work on it then because we didn't want to potential interfere with the more critical issues. But just want to make sure you know that these 2 tickets are for the same issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15600. 

Also, confirmed with Lauren that it's okay to fix this next sprint. Thank you!

**Comment by kelsonic** [comment]
PR is up 🙂
