### ISSUE TITLE
Access for Trevor Bosaw

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#16303]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Trevor Bosaw
- Please Provide your email.
   > trevor.bosaw@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >Identity team within VSP. I am a Sr. Rails Engineer at Oddball.

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCli2FwlyB+6jaaTkQlrkvqsljYOTN8sqUmyhhFRPKd8Zd8a7xkQiIWdE7yE8SQr24MhTbckxwGWimOFgHEFXsgDQRf1Ha/9r8srowmRm+/feaP6tq9c6ZHwRRVS5REMZ4JgHp2jZU5nc704gEYuUL57FDdR+aebzzNL800nSulAnOgP7NdKVwr6UVG3hsJGn8DYBnc9F/EUk2ZcjtZIrKbbbz81F5jl2E0t7Ox0jahjHYJ+Qn33dPM7AGXjmnfrp0omwiku8XKV90wVBJmSr9iMqEhdDuVqrw4LUBl4gMF5WWzI9GOeKbDEVa8GGhxkVYzc8UfvpRGnRbf+pd9i6dD4UJeOCzF7ixwWDcFHTAQrxVHgFknm5KsplFGfk+bNMLANvoRsNok4e+ujb8gi2l+goJsFRGq3wKQSRqSrnmT+TllcJgsCoUV9YjQS5tOKLQdqHrdQE8arddmM/eyPfYfZjcQuzcmcaYWgGPhAcWD7RD5giW/Tj65zwd7nr0QLCU= bosaw@Trevors-MBP
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
Viewing cloudwatch logs and other log sources. As an engineer on the VSP contract I would like to be able to review logs within AWS which concern the VSP to maintain SSO.

**Comment by omgitsbillryan** [comment]
For AWS Access:

User: Trevor Bosaw
COR: Jeffrey Hayter
Approval required: @Jeff-Hayter

**Comment by pnwstevan** [comment]
Hi @bosawt!

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

**Comment by bosawt** [comment]
Starting proxy server and running test command:
`ssh socks -D 2001 -N `
`curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.gov`
Response includes:
`*   Trying 127.0.0.1...
* TCP_NODELAY set
* SOCKS5 communication to sentry.vfs.va.gov:80
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 2001 (#0)
> GET / HTTP/1.1
> Host: sentry.vfs.va.gov
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 302 Found`


Looks like it's working! Think we can close this ticket.

**Comment by pnwstevan** [comment]
Thanks for confirming SOCKS access!

We should leave this ticket open until your AWS access is approved though, which can take a bit of a time so we keep the tickets open for tracking.

**Comment by bosawt** [comment]
> Thanks for confirming SOCKS access!
> 
> We should leave this ticket open until your AWS access is approved though, which can take a bit of a time so we keep the tickets open for tracking.

Ah sounds good! I'll be watching for that, thanks

**Comment by pnwstevan** [comment]
**For AWS Access**

User: Trevor Bosaw
COR: Jeffrey Hayter
Approval required: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@pnwstevan Approved for AWS.

**Comment by jbritt1** [comment]
Temporary AWS credentials provided to user.
