### ISSUE TITLE
[Bug] Debt Letters - Debt-details - Content mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#16309]
## What happened?
On **Staging Debt Letters debt-details** page, before **On this page**, **Why might I have this debt?** section is missing.

## Specs:
- Device: [device-agnostic]
- Browser: [device-agnostic]
- Test User _(if applicable)_: `vets.gov.user+1@gmail.com`

## Steps to Reproduce
1. Go to https://staging.va.gov/ , and sign-in as **`vets.gov.user+1@gmail.com` (Greg)**.
2. Go to https://staging.va.gov/manage-va-debt/your-debt (debt-list).
3. Under **Current debts**, in the 2nd debt-card (**Post-9/11 GI Bill..**), click **Go to debt details**.  Browser navigates to debt-details page.
4. Above **On this page** section, observe that there's no **How might I have this debt?** toggle-section.

**Screenshot**
![dl-bug-copy-debt-details](https://user-images.githubusercontent.com/587583/99466436-a418f980-28f9-11eb-8a26-8179f494015e.png)

## Desired content
Per [design prototype](https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/132263534/simulate/sitemap?mode=i), there should be a **How might I have this debt?** toggle-section above **On this page**:
<img width="734" alt="dl-spec-copy-debt-details" src="https://user-images.githubusercontent.com/587583/99467177-176f3b00-28fb-11eb-8479-457d8fb4ac98.png">

## Acceptance Criteria
- [ ] [see **Desired content** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by leahkeeler** [comment]
This content is currently under review by DMC - should have finalized by end of this week

**Comment by leahkeeler** [comment]
@tlei123 Can you please validate and close ticket - this is complete

**Comment by leahkeeler** [comment]
@tlei123 - I am going to go ahead and close this ticket - please feel free to reopen if I missed something but 99.9% this is done
