### ISSUE TITLE
CircleCI - API call to trigger pipeline between BE/FE CI

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#16325]
## Issue Description
Once the workflow is in place for vets-website in CircleCI, the vets-api Circle config will need to be modified to trigger the can-i-deploy check against vets-website. This can be done by adding a run step to the verification job to send an API call to trigger a pipeline as seen here: https://support.circleci.com/hc/en-us/articles/360047039292-Step-that-triggers-pipeline-in-different-project. It was decided that triggering a pipeline was the preferred solution to avoid polling for verification status.

Corresponding frontend ticket: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16373

---
## Tasks
- [ ] Add a run step on the backend Circle config to send an API call to trigger the can-i-deploy workflow
- [ ] Verify that the pipeline/API call from vets-api to vets-website CI is successful

**Comment by erluti** [comment]
@LindseySaari Let's make this separate tickets for the FE and BE.  We estimated the BE part of the work as a `2`.

**Comment by U-DON** [comment]
Closing for the reasons mentioned in #16373.
