### ISSUE TITLE
Access for William (Bill) Wanamaker

### ISSUE THREAD

**Issue by wwanamaker** [department-of-veterans-affairs/va.gov-team#16326]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > William Wanamaker
- Please Provide your email.
   > bill.wanamaker@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Koala (account management) and Bilby (end user experience) teams under Oddball on the Lighthouse program. If VA email address is required, it's william.wanamaker@va.gov.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDU9H8+3Zyf2cKYJb2hzV3cyF4ED3FZkvU5AEpwSU2gYbKP64JPcw6wiQ4oH3hpnOpid5VDLdzEyEB3v6Qb8Pp/axCKbAnTyQO9BivUXjMF/R9dYex4fgdWHEmaGjT/P6CGTA+9ZxzjxQsUVcpstNz2kKdfJVq7/RKZCRiqR4dvsLG421naqOhs9M2KhjZfPZm6tN02LksG+epNbogPDFBVxzI5jF0flG6u3Wmhu/7Hkdq+W//Orkg71T4L94uVOhwCh+7FD6fYFfq30MlRywUb7s37DLluxKS7XNqxRUTQ7Yp0EddWGj3DK+4k55ACAy1PC8mpiR02Z2IAg9bZLUT/wbQkX5I1iYXAiwiN78vrpha3VH30sxcqNLJO30GNLSVoJ6szzerPra8p5A6h+eNwF6Di9aVukrt33vWzT+m/BMvqQfsuXVA5t6g1Rpd1vvfrDmwIjA9nxLYox8ekQM/riDxxu7wURU6BP/LmKGXUVg01cYCEFncCvniKgR+vbxM= Bill@WWANAMAK
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by wwanamaker** [comment]
Thanks Jeremy. I was able to get this setup and access sentry via Chrome. TJ recommended I mention that I will need access to review instances. Is that a separate request or configuration related to my SOCKS access?

**Comment by jbritt1** [comment]
> Thanks Jeremy. I was able to get this setup and access sentry via Chrome. TJ recommended I mention that I will need access to review instances. Is that a separate request or configuration related to my SOCKS access?

It is a SOCKS proxy configuration. I kinda assumed that already and put you within the `developers` group in the [updated files](https://github.com/department-of-veterans-affairs/devops/pull/8303/files) so you should be good to go with newly deployed machines. Typically, people get stuck in the `viewers` group first and then later bumped to `developers` group in that config file as more perms are needed. In this case I just went ahead and skipped that step as I was pretty confident you would need that ability right out of the gate.

**Comment by wwanamaker** [comment]
Perfect. Thank you!
