### ISSUE TITLE
Access for John Paul Ashenfelter

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#1633]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   >  Jeffrey Hayter
- Please provide your name.
   > John Paul Ashenfelter
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Product Support, Backend Engineer, Oddball
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

  > ssh-rsa 
  >  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCx6Bvg6YvGvhpTxfpsBBdY3atFpaUnHhImmXl2AkllBmkx0lh+lBpXj/9aOunVfQLHYJFxZ3ZOHWejWF9KO1Qkuu3XSCNNhvBJLQE5XOy0LB2hjZlun324d3oZhTrtR80ksnjRJj2V4pKnJMf1eiyVl3MlTbKQgGBSD+5oUaN2K7tkEYG3WbR+0D+0Bs79DqQV72PNOX9LWG43IaZx5suLcmI74McudmiboBwQ6r/igeMHL/Mvb36XpF33sHe0ZZFtLgfBcNU941W8NHvlhQoOIT3uoGWKt/pDEmeakySXyC8AHG/BbA+SKuIdxZ3tcSP32u4D/A9yXtx9uIjED+nv johnpaul.ashenfelter@oddball.io

- [Grant AWS Console access?]
  > *YES*
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by johnpaulashenfelter** [comment]
Hi @department-of-veterans-affairs/vsp-operations please add me when convenient

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: You
User: John Paul Ashenfelter

**Comment by johnpaulashenfelter** [comment]
@tskinn does @Jeff-Hayter have email or other notifications turned on? Guessing he is not in github a lot

**Comment by Jeff-Hayter** [comment]
@johnpaulashenfelter We're just waiting on you eQIP paperwork to be submitted/accepted.

**Comment by johnpaulashenfelter** [comment]
@Jeff-Hayter thanks for the update!

**Comment by Jeff-Hayter** [comment]
@tskinn SAC adjudication has been received, please grant proxy access.  I'll update this thread after I receive confirmation for eQIP.

**Comment by johnpaulashenfelter** [comment]
YAYAYAY 🎉 Thanks @Jeff-Hayter

**Comment by tskinn** [comment]
@johnpaulashenfelter your ssh key has been merged in. It usually takes about ten minutes for the change to take effect. If you have trouble connecting to socks, reach out in slack in #vsp-operations

**Comment by johnpaulashenfelter** [comment]
Access unlocked 😄

**Comment by Jeff-Hayter** [comment]
@tskinn eQIP received, AWS access can now be granted.

**Comment by johnpaulashenfelter** [comment]
🎉
