### ISSUE TITLE
Organic review of DMC content excluding FSR request

### ISSUE THREAD

**Issue by 3obryandogs** [department-of-veterans-affairs/va.gov-team#16333]
Give a once-over to general DMC content from staging site, and list change requests for Brad/Craig. Meet with Danielle to see where Public Websites are in creation of pages from their end.

**Comment by leahkeeler** [comment]
Review Debt Letters I2 for styling issues 

Done: Provide FE with needed changes and do final review

**Comment by 3obryandogs** [comment]
This Google doc contains the debt letters content with marked/tracked editing suggestions. Or would you prefer it in a Word doc?

https://docs.google.com/document/d/1hJVNgGle56lunZlnx6uFSEkjVXE7Y_UnNsLMaDIrKmM/edit?usp=sharing

**Comment by 3obryandogs** [comment]
Brad and Craig, please let me know if you can't see the editing suggestions in the Google doc.  Or let me know if you'd prefer my edits in a different manner. Thanks!

https://docs.google.com/document/d/1hJVNgGle56lunZlnx6uFSEkjVXE7Y_UnNsLMaDIrKmM/edit?usp=sharing
