### ISSUE TITLE
Merge Controller for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16343]
## Goal
The CH31 Controller needs to be adjusted per [latest review](https://github.com/department-of-veterans-affairs/vets-api/pull/5321)

## Considerations
- Model PR needs to be in place before this can be completed

## Tasks
- [x] Review and implement feedback for previous controller PR submission

## Acceptance Criteria
- [x] Controller PR has been successfully merged

**Comment by digitaldrk** [comment]
Pinged VSP: https://dsva.slack.com/archives/CBU0KDSB1/p1606249461098600

Pinged VSP again: https://dsva.slack.com/archives/CBU0KDSB1/p1606324034131700
