### ISSUE TITLE
Analytics KPI dashboard request for Covid Dashboard - Vaccine Registry

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16348]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Add your team label to follow progress

### KPIs
Covid Dashboard - See Slack #vsp-covid-dashboard

Add [Vaccine Research data](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13198) as an iteration to the Covid Dashboard.

We have submission data, but do not have a funnel to add.

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
@JasonTheBearded 

This request is to add add vaccine research data to the Covid Dashboard. 

We implemented GTM on the vaccine page, and you can find the details [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13198).

Here are the stakeholder's data questions from this Slack conversation:
- How are Veterans finding the vaccination content (either the landing page or the form - i.e. where are they coming from?)
- How many Veterans are coming to the form?
- How many Veterans are completing the form?
- What is the % dropoff?

We should add this as another section to the [Tool Usage page](https://va-gov.domo.com/page/160747235) of the Covid Dashboard.

Section Title: Vaccine Research
Subtitle: Volunteer Registry

Chart: Page Views vs. Successful Submissions vs. Failed Submissions by week
Chart: Funnel & table (see @bsmartin-ep 's [funnel documentation here](https://docs.google.com/document/d/1yU8qovCTnrXs11IlYyqXktQ8ltc5lFMFo-KsRN0vkpo/edit))

^If you have other ideas about how we can better report this data, please share!

**Comment by joanneesteban** [comment]
Vaccine Response charts started on [this page](https://va-gov.domo.com/page/1096571128).

**Comment by joanneesteban** [comment]
@JasonTheBearded added the charts to the dashboard! Usability looks fine on my end. @bsmartin-ep can you QA?

As a future iteration, we may want to combine this data with page entries on the tools to see how Veterans are getting to _all_ vaccine related tools.

**Comment by joanneesteban** [comment]
@JasonTheBearded would you also be able to get started on this portion of the vaccine dashboard? ![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/c49e620c-3a30-4d95-a8bf-fe2fa342ad8b)

**Comment by JasonTheBearded** [comment]
@joanneesteban I certainly can!

**Comment by JasonTheBearded** [comment]
@joanneesteban here's the progress for that section using the research registration data. I'll work on adding pageviews in the next iteration.
![Screenshot 2020-12-08 160720](https://user-images.githubusercontent.com/24949467/101547164-77dc2000-396f-11eb-8e5a-e7a6dea08605.png)

**Comment by joanneesteban** [comment]
Thanks, @JasonTheBearded ! Could we change the top right chart to be a `multi-value gauge` ? Example is in the main covid page [here](https://va-gov.domo.com/page/2077110052/kpis/details/41688618). (Pages Percent Change chart)

![image](https://user-images.githubusercontent.com/48964695/101550163-da87e880-397c-11eb-9478-c44d6d132769.png)

**Comment by JasonTheBearded** [comment]
Definitely @joanneesteban. Do you want the gauge to report on total events or unique events?

**Comment by joanneesteban** [comment]
To be consistent with the other parts of the dashboard, we've been using Total Events (sum of all events).

**Comment by JasonTheBearded** [comment]
@joanneesteban I've added initial viz objects for the 'How veterans are contacting about the vaccine' and 'How Veterans are viewing vaccine content'. Let me know if I need to make any changes to those card. Thanks!

**Comment by joanneesteban** [comment]
See: [16981](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16981) for Vaccine Registry (this is actual sign ups. The current data on the dashboard is Research sign ups).

**Comment by bsmartin-ep** [comment]
As discussed @JasonTheBearded, GA events for https://www.va.gov/health-care/covid-19-vaccine/stay-informed:

- covid-vaccination--submission
- covid-vaccination--submission-successful
- covid-vaccination-login-successful-start-form
- covid-vaccination--submission-failed

Plus...

- Event label no-login-start-form (on page www.va.gov/health-care/covid-19-vaccine/stay-informed/form/)
- Event action begins with Default Button CTA - Sign in - might be useful too.

**Comment by joanneesteban** [comment]
Changing the Title of this section on the dashboard to, "How Veterans are interested in the vaccine" since these aren't actual vaccine registrations yet.

**Comment by joanneesteban** [comment]
@JasonTheBearded could you change the data labels in the Legend?

- `Successful Vaccine Registrations` to `Successful Vaccine Interest Registrations`
- `Unsuccessful Vaccine Registrations` to `Unsuccessful Vaccine Interest Registrations`

**Comment by JasonTheBearded** [comment]
@joanneesteban Done. Do you want me to make any changes for the research labels?

**Comment by joanneesteban** [comment]
Thanks! No need to change the research labels now. We may need to do some adjustments after our meeting with Lauren.

**Comment by joanneesteban** [comment]
Additional vaccine interest iterations to the dashboard to be tracked in #17729 . Thanks for the support, here, @JasonTheBearded & @bsmartin-ep !
