### ISSUE TITLE
Adjust Model for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16342]
## Goal
The CH31 Model needs to be adjusted per [latest review](https://github.com/department-of-veterans-affairs/vets-api/pull/5320)

## Tasks
- [x] Review and implement feedback for previous model PR submission

## Acceptance Criteria
- [x] Model PR has been successfully merged

**Comment by digitaldrk** [comment]
UPDATE:
PR updated and requested for re-review: https://github.com/department-of-veterans-affairs/vets-api/pull/5320#issuecomment-729986883

**Comment by digitaldrk** [comment]
Updated PR after Feedback. Pinged VSP:
https://github.com/department-of-veterans-affairs/vets-api/pull/5320

https://dsva.slack.com/archives/CBU0KDSB1/p1606166136026400
