### ISSUE TITLE
Access for Robin Garrison

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#1634]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Robin Garrison
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Benefits and Memorials 1
   > FE Engineer
   > Ad Hoc.
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

  >  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLkPxFR2p8PPuhhS8+XOp7WIkVTNqtvuj+y7yyj0YLigrQeHakHBRBWXIs+A7Woy4s5k0RVkCYkJF7i3YgthUx6EKAlOe+XcE9HpDly9z2GKfHU+v20YNnkdsR4BvGfNqj1m4PHsyTxsYOWg2o+tLBP41Ff24WMNvw4TFX9JOoopDGJkVAnHNaxhAiqT9hEIzjzXBC/814Ax26VHCtkZkW5Za4TK342KTMkFaVNkfUNILMgYtSedKaU65853Td/nOMYZ7V83v5vPnkohkYLb4HkPFp0g5ynGSCnpWe6egJMpR0bVHgw4V+YzRnPFBZ787UW98ScNsmx2tX7+BcJE4n robingarrison@RobinGaisonsMBP.attlocal.net

  I'm not sure why my email is showing GaisonsMBP. I was using the [instructions from here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/internal-tools/#create-an-ssh-public-key). My email is robin.garrison@adhocteam.us.

- [Grant AWS Console access?]
  > NO

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Robin Garrison

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for SOCKS access.
