### ISSUE TITLE
Add Mobile Orientation Screens to CH31 Mockups

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16356]
`hold off on prototypes as we work with mockups`

## Goal
We need to get the first version of the orientation screens in place so that FE can start putting them in place in staging

## Considerations
- Check in with FE on feasibility
- Place mobile screens

## Tasks
- [x] Insert some screens into the mockup that will show the videos and content from the CH31 stakeholders in a mobile view along with the desktop views

## Acceptance Criteria
 - [x] The VRE Orientation content is shown in the the mockup for FE to pick up and iterate

**Comment by sporeboy** [comment]
And here is the link to the down-and-dirty mobile view of the orientation mock: https://xd.adobe.com/view/aaf3f28b-b763-4c16-ba02-d1d47e20328e-ffa0/screen/6168b85b-d902-4cb0-9c8a-c86c5976d382
