### ISSUE TITLE
CC provider preference - missing address (short-term)

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16359]
## Issue Description
While research for the community care preferred provider changes are being conducted and synthesized, we are looking at a temporary solution to cover the use case when a veteran doesn't have a residence address on file.

Short-term - continue to use the current version of the page (form)

---

## Acceptance Criteria
- [ ] Update is behind VA Online Scheduling Provider Selection feature flag
- [ ] If a user does not have a residence address on file, then show original provider preference page
- [ ] If a user has a residence address on file, then show new provider preference page

**Comment by jbalboni** [comment]
@laurenernest This is up on staging now, I'm not sure the best way to test it, though, since we'll need to find users without an address.

**Comment by laurenernest** [comment]
@jbalboni We can use the Cecil account to test. Can you turn on the flag in staging?

**Comment by laurenernest** [comment]
Working as expected for users with and without an address on file. Thanks @jbalboni !
