### ISSUE TITLE
Access for Alayna Abel

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16354]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Alayna Abel
- Please Provide your email.
   > alayna@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Caregiver Team, Product Manager, Ad Hoc LLC

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPkO56rS4vEMGHHihKK0jfLWcXA3JMKvH/MfMtVgrSLmUvpqGSHr1cCbriXKCzvWtkHT2fyw5slX7m55y4rOjUklYBL25Y6oWnqhRN8l6EK9aCD7OmLxHfwdbpXzjtvuwxdiJHyAq1vhshJBgYnD3rEeLVQV/wfJqLlhTmQN6CrocQE/Y1FV6KKeMFBwY6hf8B4UOnJ5MzGSh1kCkh13EU4wFFB/Ui5fnO+NLbkOHPAscCLG5XZM24WlM6crNif1kzoj/EUdm0UQI2n2T3i19rbGVKtCTbZUqGqVLzUK/aVQ0gw/IFZVDSqB7Jxne9DoniVGBjT/ZRZMcq7E1CjUx3JCf9G25vjV7ZmBDlfHctvOQLrmj53fh95mtwyKg+nRlFfNfqFPGGs3tLwEdzP08JK6n1DZKpmqoCIVA4Tjz4nfTblTpQ72wAT420HK76mGFJ6QSriAoegYMvJ8onS9aXTl+BTcnkhGhCW5fhz8eFDBsV+aJOn8TKFQNKq2wwJT0= alayna@
```

- Grant AWS Console access?
  >  NO
  - What AWS services do you need access to and why?

**Comment by ala-yna** [comment]
Tagging @MaryO-USDS for approval. Thanks Mary!

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by ala-yna** [comment]
### Accessing SOCKS proxy from the internet
The ~/.ssh/config file on your local system contains configuration to access the SOCKS proxy from outside the VA network - see Line 28 here.

Run the following command:

`ssh socks -D 2001 -N &`

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#accessing-socks-proxy-from-the-internet

**Comment by ala-yna** [comment]
I have a new laptop and generated a new SSH key. That key is:

`AAAAB3NzaC1yc2EAAAADAQABAAABgQDCCB7w9FRhsqOcHaYYiNddI6iROwQd2hfvg68TG5suImNbg1EDBw910nRFtU5BHFz5Xs79IgS9gLbI3dg8DITzwym6URvoPAIFJ4FwD0msJHlkLTFqT1wDUXac5qlNilwezDINgOK9GQMG5m4AsPfstBtOEDc2peAC42M7Ur5FLJHvdDOWs/WU6rPH7nXGNloCzgT0JbqkjRzLg9VBkseVlb6LtBUeZq1TdZKgsqL++Xnp50RncLrLJghSV/x4/6s7WKVVnjb8JT3X2tzLNwCIvVw3S/2ilPdp5V91bBqx2alkeUFyOJC0v3MntzCyQUtiTaaNz5TCt3YxYI6eZxllPudX3z0DkjnE3hI7VJU2sDZnuKiolU8ak9RRLdhoZsjLpeq4YWPtgmW7FehWxfb69+2owVZcAtuTz/N6bZRWDrbr4loIiX2CC+dY6EPvwPCqbuRn6n0+UxwkMfVxv2c0ExqB2jihl+6u9f26HGKE4SCSg+MkJ5zUgBw9/NYoxB0= alaynaabel@AlaynaAsMacBook`

@mydesignrocks (since I see you're on call) - can you grant me access to SOCKS? Preferably without deleting my old key, until the new one is fully set up. Thank you!

**Comment by mydesignrocks** [comment]
added new key
