### ISSUE TITLE
GIDS: Include Latitude/Longitude of institution in version generation.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16357]
As a developer, I need to include the latitude and longitude in version generation so that it can be used for any forthcoming mapping / near me functionality.

## Assumptions:
1. This story just covers latitude and longitude data from https://collegescorecard.ed.gov/data/documentation/ and IPEDS. Any other data we need will be covered in a follow-on story. 
2. Latitude and Longitude data will be supplied for `institutions` from `ipeds_hd` primarily and will use the `latitude` and `longitude` values from `scorecards` when present if they are not present in `ipeds_hd`.

## Acceptance Criteria
1. Analysis of data coverage of institutions with/without latitude and/or longitude is documented on this story.
2. Institution Latitude is:
    a. included in version generation.
    b. included in the institution export.
    c. available to be used by the front end of the Comparison Tool
3. Institution Longitude is:
    a. included in version generation.
    b. included in the institution export.
    c. available to be used by the front end of the Comparison Tool

#### Development Notes

Latitude | root | location.lat | float | LATITUDE |   |   | IPEDS
-- | -- | -- | -- | -- | -- | -- | --
Longitude | root | location.lon | float | LONGITUDE |   |   | IPEDS

https://github.com/alexreisner/geocoder#basic-search could be used to find latitude and longitude based on physical address if data is not available from scorecard when generating a version.  (Note; this is just for information, based on AC#3, we may have a follow on story if this is recommended).

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Findings for AC1: 
When pulling these values from the latest `ipdeds_hd` file in production we get 8813 matches out of 69343.
When using the `location.lat` and `location.lon` from the Scorecard API as assumed in the story, we have less data. The scorecard file itself contains only 6806 records many of which have 0 values for lat and lon. 

As a result Assumption 2 was added and we will use the data from `ipeds_hd` primarily, but will also add lat and lon values from `scorecards` when those values are not present in `ipeds_hd`, but are present in `scorecards`.

**Comment by elder-joseph** [comment]
### Associated PRs:


 - DB Specific PR: 
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/775
 - Full PR: 
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/774

**Comment by sonntag-adam** [comment]
<img width="857" alt="Screen Shot 2020-11-30 at 10 32 43 AM" src="https://user-images.githubusercontent.com/48804582/100747729-6c598980-33b0-11eb-9425-a6930ed0c84f.png">
##
<img width="1087" alt="Screen Shot 2020-11-30 at 10 34 37 AM" src="https://user-images.githubusercontent.com/48804582/100747753-72e80100-33b0-11eb-8f94-1e7e29f6aa1b.png">

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
