### ISSUE TITLE
Error messaging for validated fields - mapping 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#16361]
Map validated fields in FSR with error states. 

Acceptance: 

1-Agree on validated fields w/design
2-work with FE for error states.

[Reference Guide](https://design.va.gov/content-style-guide/error-messages ) https://design.va.gov/content-style-guide/error-messages

**Comment by 3obryandogs** [comment]
I sent this to Peggy today to see if I'm headed in the right direction.

1.	Have you been employed within the past two years? (*Required)
Informational alert - We need your help to continue working on your request.	
Please answer the employment question so we can continue helping you fill out your request.

**Comment by 3obryandogs** [comment]
The following answers are based on Peggy's approved wording. Each one is specific to the question asked. I used a UXPin preview which currently is undergoing revision.

1.	C2P1: Have you been employed within the past two years? (*Required)
•	Please enter your employment information so we can continue helping you fill out your request. 
2.	C2P1: Are you currently employed?  (*Required)
•	Please enter your employment information so we can continue helping you fill out your request. 
3.	C2P1: Employment start date (*Required) 
•	Please enter your employment start date so we can continue helping you fill out your request. 
4.	C2P1: Employment end date (*Required) 
•	Please enter your employment end date so we can continue helping you fill out your request. 
5.	C2P1: Gross monthly income (*Required)
•	Please enter your gross monthly income information so we can continue helping you fill out your request. 
6.	C2P1 table: Have you been employed within the past two years? (*Required)
•	Please enter your employment history information so we can continue helping you fill out your request. 
7.	C2P1 table: Employment start date (*Required) 
•	Please enter your employment start date so we can continue helping you fill out your request. 
8.	C2P1 table: Employment end date (*Required) 
•	Please enter your employment end date so we can continue helping you fill out your request. 
9.	C2P2: Have you had additional jobs in the past two years? (*Required)
•	Please enter your employment information so we can continue helping you fill out your request.
10.	C2P2: Employment start date (*Required) 
•	Please enter your employment start date so we can continue helping you fill out your request. 
11.	C2P2: Employment end date (*Required) 
•	Please enter your employment end date so we can continue helping you fill out your request. 
12.	C2P4: Do you currently receive Social Security benefits? (*Required) 
•	Please enter your Social Security benefits information so we can continue helping you fill out your request.
13.	C2P4: How much do you receive Social Security benefits? (*Required) 
•	Please enter your Social Security benefits information so we can continue helping you fill out your request.
14.	C2P5: Do you currently receive any additional income? (*Required) 
•	Please enter your additional income information so we can continue helping you fill out your request.
15.	C2P6: What is your marital status? (*Required)
•	Please enter your marriage information so we can continue helping you fill out your request.
16.	C2P7: Has your spouse been employed within the past two years? (*Required)
•	Please enter your spouse’s employment information so we can continue helping you fill out your request.
17.	C2P7: Is your spouse currently employed?  (*Required)
•	Please enter your spouse’s employment information so we can continue helping you fill out your request.
18.	C2P7: Employment start date (*Required) 
•	Please enter your spouse’s employment start date so we can continue helping you fill out your request. 
19.	C2P7: Employment end date (*Required) 
•	Please enter your spouse’s employment end date so we can continue helping you fill out your request. 
20.	C2P7: Gross monthly income (*Required)
•	Please enter your spouse’s gross monthly income information so we can continue helping you fill out your request. 
21.	C2P8: Has your spouse had additional jobs in the past two years? (*Required)
•	Please enter your spouse’s employment information so we can continue helping you fill out your request. 
22.	C2P9: Does your spouse currently receive VA benefits?  (*Required) 
•	Please enter your spouse’s VA benefits information so we can continue helping you fill out your request.
23.	C2P9: What is the monthly payment your spouse receives for compensation and pension benefits?
•	Please enter your spouse’s VA compensation and pension benefits information so we can continue helping you fill out your request.
24.	C2P9: What is the monthly payment your spouse receives for education benefits?
•	Please enter your spouse’s VA education benefits information so we can continue helping you fill out your request.
25.	C2P10: Does your spouse currently receive Social Security each month? (*Required)
•	Please enter your spouse’s Social Security benefits information so we can continue helping you fill out your request.
26.	C2P10: How much does your spouse receive for Social Security each month? (*Required)
•	Please enter your spouse’s Social Security benefits information so we can continue helping you fill out your request.
27.	C2P11: Does your spouse currently receive any additional income? (*Required)
•	Please enter your spouse’s employment information so we can continue helping you fill out your request.
28.	C2P12: Do you have any dependents?  (*Required) 
•	Please enter your dependent(s) information so we can continue helping you fill out your request.
29.	C3P1: What is the amount in your checking and savings account? (*Required)
•	Please enter your financial information so we can continue helping you fill out your request.
30.	C3P1: What is the amount of cash you have available? (*Required)
•	Please enter your financial information so we can continue helping you fill out your request.
31.	C3P1: What is the current value of your U.S. savings bond? (*Required)
•	Please enter your financial information so we can continue helping you fill out your request.
32.	C3P1: What is the current value of your stocks and other bonds? (*Required)
•	Please enter your financial information so we can continue helping you fill out your request.
33.	C3P2: Do you currently own any real estate? (*Required)
•	Please enter your real estate information so we can continue helping you fill out your request.
34.	C3P3: Do you currently own any trailers, campers, or boats? (*Required)
•	Please enter your trailer, camper, or boat information so we can continue helping you fill out your request.
35.	C3P4: Do you currently own any vehicles? (*Required)
•	Please enter your vehicle information so we can continue helping you fill out your request.
36.	C3P5: Do you currently own other assets? (*Required)
•	Please enter your assets information so we can continue helping you fill out your request.
37.	C4P1: How much do you spend on housing each month? … (*Required)
•	Please enter your housing expense information so we can continue helping you fill out your request.
38.	C4P1: How much do you pay for food each month? (*Required)
•	Please enter your food expenses information so we can continue helping you fill out your request.
39.	C4P1 V01: How much do you pay for housing each month? (*Required)
•	Please enter your housing expense information so we can continue helping you fill out your request.
40.	C5P1: Why type of assistance do you want for your Post/9/11 GI Bill debut for tuition and fees (*Required)
•	Please enter your tuition and fees information so we can continue helping you fill out your request.
41.	C6P1: Have you ever been adjudicated bankrupt? (*Required)
•	Please enter your bankruptcy information so we can continue helping you fill out your request.
42.	C7P1: Veteran’s full name (*Required)
•	Please enter your full name so we can continue helping you fill out your request.

**Comment by leahkeeler** [comment]
@3obryandogs to check with @peggygannon --messaging is long

**Comment by 3obryandogs** [comment]
https://docs.google.com/document/d/1wYPCXE_yaahUvk9Ah4fi4SD_rMtv79I3aJ6MqddYF4c/edit

Attached is a document with the shortened error messages. What is the next step?

**Comment by leahkeeler** [comment]
I think we need to make this more specific to the actual field as we discussed during team meeting

**Comment by rileyorr** [comment]
I started a [Google Sheet for the form's error messages](https://docs.google.com/spreadsheets/d/1fi9aV1YdRQRfvLOFmZUFctvzYpkTRH0RQjQ2SPlq-d4/edit?usp=sharing) - will continue working on it tomorrow. @3obryandogs, please add/edit anything that looks off!

**Comment by 3obryandogs** [comment]
I reviewed what was there last night. Made a few minor edits.

**Comment by rileyorr** [comment]
I finished my first pass through the error messages for the form. I'll double-check I didn't miss anything with fresh eyes tomorrow!

**Comment by rileyorr** [comment]
@3obryandogs I took another pass through the error messages and made some edits. Can you please review and make sure they align with our content style guide? I can make a ticket for Peggy to do a final review once you think they're good to go!

**Comment by 3obryandogs** [comment]
@rileyorr - I corrected a couple spellings, and I've sent an email to Jill. I cc'd you and Leah on it.

**Comment by rileyorr** [comment]
@3obryandogs did Jill answer your questions about some of the error messages?

**Comment by 3obryandogs** [comment]
@rileyorr I just emailed Jill again. We'll see ...

**Comment by rileyorr** [comment]
Susan and I met and finalized ever error message we could. There's one outstanding message left that requires the DMC's assistance, but I'm gonna go ahead and remove this as a blocker for frontend implementation.
