### ISSUE TITLE
Add dynamic back to top feature to the other RS article templates

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#16369]
## This back to top feature appears to have been implemented only on the multiple FAQs template, but it is supposed to be implemented on all article templates. 

- [ ] Single Q&A desktop + mobile
- [ ] About desktop + mobile
- [ ] Step-by-step desktop + mobile
- [ ] Checklist desktop + mobile
- [ ] Images desktop + mobile

_I'm not including Videos on this list because Videos template is iceboxed for POST 1.1 CMS work._

Basic requirement from ticket #1346: 
Each article page should enable a dynamic back to top link.  `<-- each RS article template`
This back to top should appear based on page height/length. <--2000 pixels and longer

ETA - NOT urgent. Can implement during or after December freeze.  Transformers and finishing 1.1 templates are higher priority.

**Comment by brianalloyd** [comment]
@kelsonic and @ncksllvn moved this into Sprint 38 and is ready for pick up if you have bandwidth.  Plan to review in planning session on Jan 4, 2021.  Thanks.

**Comment by ncksllvn** [comment]
I'll pick this up. For my awareness though - should this be in our Current Sprint column?

**Comment by brianalloyd** [comment]
Thanks @ncksllvn appreciate it.  Moving it to in-progress in current sprint, thanks for the heads up, greatly appreciated.

**Comment by ncksllvn** [comment]
I merged some work for this that should go live tomorrow

**Comment by brianalloyd** [comment]
@ncksllvn thanks for the work on this, any idea if this is production?  I'm still not seeing the dynamic back to top in other RS articles... going to refresh and clear my cache and check again.

**Comment by ncksllvn** [comment]
At the time of your comment the daily deployment was not finished but it is now. The work is live 🙂

**Comment by brianalloyd** [comment]
Thanks @ncksllvn I also forget the time zone factor on the daily deploy.  Thanks so much, validated and closing.
