### ISSUE TITLE
Content for FSR From error messaging for validated fields 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#16363]
Create content fo error state for validated fields  in FSR

Definition of done: 

1. Review with Peggy
2.Provide content to FE

**Comment by 3obryandogs** [comment]
I sent this to Peggy today to see if I'm on the right track.

1.	Have you been employed within the past two years? (*Required)

Informational alert - We need your help to continue working on your request.	
Please answer the employment question so we can continue helping you fill out your request.

**Comment by leahkeeler** [comment]
dup ticket - closing
