### ISSUE TITLE
VA Forms:  Identify Top Searched for and Downloaded Forms

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1637]
****Request:**
To help us identify an MVP candidate for the _Find a VA Form_, we would like to see analytics for the following VA forms 'master detail' landing pages, individual forms themselves, as well as search results from general forms that are providing the highest traffic (via organic search, via onsite search, and if possible, via the search that's on the **Find a VA form** page), downloads and page visits. 

1. **Analytics on Lisa K's Audit of VA Forms Landing Pages**
From Lisa's audit, which of these 'master detail' landing pages are getting the highest search traffic, downloads, and page visits 
[VAFormsAudit (1).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3591747/VAFormsAudit.1.xlsx)

2. **Analytics from Kevin's DB Export of all raw VA forms**
Identify the top 100 downloaded forms from below DB export
(As desired outcome: I want to know of the 1500+ "public" facing forms in the forms database, which of these are the top 100 most searched (organic, onsite, Find a VA form search), visited, and downloaded.)
[database-export-VAForms_82819.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3591750/database-export-VAForms_82819.xlsx)

**Comment by Karak888** [comment]
@mnorthuis this is what I had started as I am breaking down the tickets into chunks (maybe the work has already been done for some of these, but I will rely on you to help flush these out as needed!

**Comment by mnorthuis** [comment]
@Karak888 I'll need some background on this, haven't been in any discussions of yet.  Maybe a quick chat?

**Comment by Karak888** [comment]
@mnorthuis sorry I wasn't assigning this to you, was just kinda showing some of the breakdowns for larger epic.

**Comment by Karak888** [comment]
@jenniferlee-dsva please review the above and edit away as you see fit.  I just wanted to provide analytics team with some tasks to get started, but am sure I didn't state everything correctly! 
@nedierecel I know you had worked with Jen previously on something similar, so please reach out to her directly and she said she would be available to hop on a call, etc.  Thanks!!

cc: @joanneesteban

**Comment by jenniferlee-dsva** [comment]
@Karak888 - Edited the above with a couple clarifications.

**Comment by Karak888** [comment]
@Karak888 to follow-up with analytics team @joanneesteban and @nedierecel - Is this currently in the works or can we follow up with timeline?  Thanks!

**Comment by nedierecel** [comment]
Thanks @Karak888 - We're going to grab this task for this sprint and deliver early next week.

**Comment by Karak888** [comment]
Thanks so much @nedierecel !

**Comment by nedierecel** [comment]
@Karak888 @jenniferlee-dsva A few updates on the request:

1. Analytics on Lisa K's Audit of VA Forms Landing Pages - We will be able to view top pages by pageviews as well as landing pages by organic search. 

2. Analytics from Kevin's DB Export of all raw VA forms - These actions are not tracked on the legacy section but have a low level of effort to implemen to begin tracking this sprint. Though we won't have historical data, Tracking a few week's worth of data in combination with the pageview analysis should give us some direction. 
- Onsite Search for va.gov/vaforms tool 
- PDF Downloads by form 

Including @jonwehausen @joanneesteban for visibility

**Comment by Karak888** [comment]
Looks great @nedierecel @jenniferlee-dsva will share the VA forms Stakeholder Team.  Closing this out!
