### ISSUE TITLE
Map markers at the same location overlap each other

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#16371]
## What happened?
Search for VA facilities in 10538 zip code. Note that several overlapping markers are created for the same address.

## Desired behavior
We should use [marker clustering](https://docs.mapbox.com/mapbox-gl-js/example/cluster/) to indicate the presence of multiple markers.

## Acceptance Criteria
- [ ] Multiple markers at the same location are rendered as a cluster. When clicked, the map zooms in on that point, and the cluster breaks up into multiple markers.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
closing as duplicate to #16391
