### ISSUE TITLE
Discovery to size issue 11453

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16374]
## Issue Description
@zacharymorel takes the time to do any further technical discovery and ramp up needed to accomplish [11453](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453) before Sprint 36.

---
## Acceptance Criteria
- [x] Personal understanding of the existing data contract and user story/ additional work dependencies.
- [x] If needed, report any additional work dependencies to @MarciMcGuireGCIO and @johnhashva  
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by zacharymorel** [comment]
>Per this thread, our form_details_url was removed from the API. After launching form detail pages, we will need to undo some changes in this PR to re-enable that property, department-of-veterans-affairs/vets-api#4989.

Just a reminder @MarciMcGuireGCIO , we will need some vets api work that will re enable per nicks' comment from above

**Comment by zacharymorel** [comment]
Self note, reference this [a11y documentation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152) when working on the PDF download links.

**Comment by zacharymorel** [comment]
> > Per this thread, our form_details_url was removed from the API. After launching form detail pages, we will need to undo some changes in this PR to re-enable that property, [department-of-veterans-affairs/vets-api#4989](https://github.com/department-of-veterans-affairs/vets-api/pull/4989).
> 
> Just a reminder @MarciMcGuireGCIO , we will need some vets api work that will re enable per nicks' comment from above.

@MarciMcGuireGCIO , I chatted with Nick and Lighthouse team per [this slack thread](https://dsva.slack.com/archives/CUB5X5MGF/p1606757374228900) about some technical pieces with the work to get the flags that are keeping the from details url from populating. 

We need to get with @markgreenburg so that work gets entered in their sprint.
