### ISSUE TITLE
Add new employees and BAM1 stakeholder to DSVA Slack as Full Members

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#16375]
Hello! We have two new hires who started this week on the VSA Project. Can you please add them as a full members to the DSVA Slack. 
Email: rtafoya@governmentcio.com AND skasimow@governmentcio.com

Also, BAM1 has a stakeholder they would like to have added to the DSVA slack: barrett.cooper@va.gov

Thank you!!!

**Comment by LEHigley** [comment]
@YanaRoy added the first two. what channels should barrett.cooper be?

**Comment by LEHigley** [comment]
done!
