### ISSUE TITLE
[Development] 526 - Only send separation location to evss for BDD

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#16376]
it looks like some users are answering the separation location question and then submitting form 526 after they're no longer eligible for BDD.

we get the response “form526.serviceInformation.separationLocationCode.isInvalidValue” from evss 

 I've asked evss [in slack](https://dsva.slack.com/archives/C1VBAHWQL/p1605732568085600)

> I’m thinking the solution is to stop sending separation location after the discharge date has passed, but should we send the separation location if the discharge date is between 0-90 days in the future?

**Comment by luke-gcio** [comment]
Made a swag at the estimate. Looks like you are already working on it, added to sprint 35.

**Comment by annaswims** [comment]
Validated. Last separationLocationCode error was before fix
