### ISSUE TITLE
CircleCI - Modify FE CI to include a workflow that can be triggered via API call from vets-api CI

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#16373]
## Issue Description
The vets-website deploy check in CircleCI polls on the verification status, but it was decided that triggering pipelines between projects is the optimal solution to avoid polling. 

In V1 of the CircleCI API, you could trigger specific jobs, but that's no longer the case in V2. FE will need to refactor the Circle config to wrap the can-i-deploy check in a workflow. 

Corresponding backend ticket: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/16325

---
## Tasks
- [ ] Create a new workflow on the frontend to be triggered via API call to trigger a can-i-deploy workflow
- [ ] Verify that the pipeline/API call from vets-api to vets-website CI is successful

**Comment by U-DON** [comment]
Ultimately deciding against having `can-i-deploy` in vets-website get invoked after `pact_verification` in vets-api.
- Wanted `can-i-deploy` to be immediately visible as a step in the status checks.
    - If for some reason the verification took too long or just never looped back to vets-website, there would be no `can-i-deploy` status check available. This would be an issue when we make it a required check, as devs would be able to merge without a confirmed verification.
    - As a way to always include the `can-i-deploy` status check, I tried having it fail by default and just let the `pact_verification_job` [rerun the failed workflow using Circle's API](https://circleci.com/docs/api/v2/#operation/rerunWorkflow). But having it automatically fail would negatively influence the build metrics and create noise.
    - If instead I let `can-i-deploy` run with an exponential backoff timer and also let the verification job rerun the workflow from failed, it seems it would start a new workflow even if the previous one did not complete. I anticipate that this would strain the system and create a lot of duplicate jobs.
- It got complicated when deciding what the verification job should trigger in vets-website.
    - If I bundle the `can-i-deploy` with the script to invoke the verification, I would have to add logic to prevent an infinite loop.
    - If it's not bundled together, it doesn't give devs a way of manually triggering both the verify and deploy check if anything went wrong before.
- In the end, I decided to keep it simple by just having the `can-i-deploy` workflow periodically check with an exponential backoff timer (3 retries, at intervals of 30 seconds, 1 minute, 2 minutes). This displays the job from the beginning and gives devs a way to manually trigger a verify and deploy check at the same time.
