### ISSUE TITLE
[Build] Transformer for R&S NodeStepByStep

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#16385]
## Issue Description
_Build appropriate transformer for content type NodeStepByStep_

## Front end tasks
- Provide an estimate. 
- Remove 'Needs Grooming' label
- Build transformer and validate connection. 

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Planning Considerations 
<details> 

 <summary>Connected Ticket Details (expand)</summary>

- [Create mobile version for step_by_step MVP 1.1 #14047](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14047)

**Comment by kelsonic** [comment]
Disregard ^^ accidentally tagged this ticket

**Comment by kelsonic** [comment]
@ncksllvn and I paired today and we decided to merge our PRs together into this PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/15116

We've completed all necessary additive work and are just validating the work now so that it passes CI, then we should have both of our transformer PRs merged! 🕺 

CC @brianalloyd

**Comment by ncksllvn** [comment]
There is still a little ways to go w/this but we do have the foundation out there and have learned a lot.

**Comment by brianalloyd** [comment]
Great work @ncksllvn and @kelsonic huge undertaking and appreciate the update on the merge PR.  Super Stars!
