### ISSUE TITLE
Document Sandbox Environment Details

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#16396]
## User Story 

As a user of the platform, I would like to understand the full capabilities and limitations of the Sandbox environment so that I can better develop, test and demo changes.

## Description

Create documentation that assists all personal working with the platform understand in detail what the Sandbox environment is and how to use it in the different development capacities.

The following questions (but not limited to) should be addressed in the documentation created:

At what stage of development should I be expected to use this?
What are the capabilities of this environment
What are the limitations of this environment
How do you access this environment?
How is this environment modified, what is the process to make changes?
What is this environment best used for?
What should this environment not be used for?

## Acceptance Criteria 
- [ ] Sandbox Environment Detailed description is written and stored in location decided upon noted in the epic.

**Comment by erluti** [comment]
Lighthouse has an SLA for sandbox
