### ISSUE TITLE
GIBCT Colmery 107 - 508 Audit

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1639]
This epic will be the container for any issues discovered during the Product Support team's 508 audit of GIBCT Colmery 107 feature improvement: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/1544

**Comment by desireeturner** [comment]
This epic is complete as all of the child issues have been completed.
