### ISSUE TITLE
[DESIGN] Scenarios in which location pins are stacked

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16391]
## Issue Description
Due to close proximity or identical addresses, sometimes pins are stacked, making it difficult to locate specific pins or appear that some locations are missing. Even though we are fit the mp to the locations, some pins may still become stacked due to the spread of facilities across the area. 

---
## Tasks
- Evaluate [Mapbox marker clustering](https://docs.mapbox.com/mapbox-gl-js/example/cluster/) to indicate the presence of multiple markers.
- Determine the best user experience (mobile and desktop) for the following scenarios. 

1. There is a small cluster of locations in one area of the map which cannot be differentiated because of the zoom level needed to show the full list of locations 
<details>
<summary> Example of Scenario 1 </summary>

![image](https://user-images.githubusercontent.com/55411834/99732312-845e0e80-2a7c-11eb-8bf7-b552f1fb80ee.png)

</details>

---

2. A given address applies to more than one provider on the list of results (ie - individual providers at a group practice - identical addresses)
<details>
<summary> Example of Scenario 2 </summary>

![image](https://user-images.githubusercontent.com/55411834/99732519-def76a80-2a7c-11eb-87d9-3066787760a1.png)

</details>

---

3. Addresses are geographically very close together (but not identical) 

---

4. The search returns Identical street addresses (with different suite numbers) for more than one provider on the list (ie - same building - different floor)
<details>
<summary> Example of Scenario 4 </summary>

![screencapture-staging-va-gov-find-locations-2020-11-19-15_45_18](https://user-images.githubusercontent.com/55411834/99733593-9e98ec00-2a7e-11eb-8d02-ff8ac75f7503.png)

</details>

---

5.  All search results are at a distance from the geographic parameter, which causes the pins to be stacked (because the "I am here" indicator prevents a zoom level that would differentiate them. 
<details>
<summary> Examples of Scenario 5 </summary>

![image](https://user-images.githubusercontent.com/55411834/99732152-39dc9200-2a7c-11eb-8e0e-6222b0074d12.png)

![image](https://user-images.githubusercontent.com/55411834/99734850-c8531280-2a80-11eb-85a0-bfe2b76cc9ff.png)

</details>

---

**Consider-** 
- If the user selects a card from the list - how does the corresponding pin receive focus on the map?
- How are those competing search results presented via screenreader?
- If the user zooms in on those results, how do they return to the original view?

---

## Acceptance Criteria
- [ ] Veterans have a way to understand the full list of results, even if addresses are similar or identical.

**Comment by mmiddaugh** [comment]
![image](https://user-images.githubusercontent.com/55411834/101085178-4e388880-356c-11eb-949f-4665af900337.png)
[Slack thread here](https://dsva.slack.com/archives/C0FQSS30V/p1606834192250800)

**Comment by jilladams** [comment]
Parent epic is closed, FL is now ticketed in va.gov-team repo. Closing orphaned tickets, as we are iterating FL separately.
