### ISSUE TITLE
Prometheus debt cleanup

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#164]
## Description

We have several tech debt items that need to be cleaned up around Prometheus. This epic is meant to contain a set that we can swarm and knock out together, please don't use as a place to dump things we'd like to have the Prometheus setup do someday.

## AC

- [ ] sub-issues closed off

**Comment by jhouse-solvd** [comment]
This is old and defunct. Closing.
