### ISSUE TITLE
[Observation session] Static VAOS scheduling page + widget to app

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#16409]
We have received similar feedback below in other [research session](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/july-2020-user-research/2020-july-VAOSR-EC-research-report.md) and now also in a recent Veteran observation session:
1.  The content (and it's placement) is too much on the static scheduling page before you even get to/find the actual button to go into the app. Also the 'COVID' alert can be misleading to users and takes up much the page. 
2. Unauth experience requires too many clicks to get to app - Unauth homepage -> static scheduling page -> click to authenticate in widget -> once authenticated user is taken back to static appointments page instead of dropped into the app

### Acceptance criteria:
- [ ] review for additional suggestions/ways to address two need above
- [ ] content review of static scheduling page - review/work with @DanielleThierryUSDSVA on this
- [ ] follow up with vsp-support & maybe the design council on how we can change the behavior of the widget for static scheduling page widget

![Screen Shot 2020-11-19 at 11.48.28 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/e5ad778e-4537-4145-9b23-08075cd998af)

**Comment by outerpress** [comment]
We did some additional user testing on the SLP and passed the feedback on to public websites folks, and they're actively working on improvements listed here. Closing this one.
