### ISSUE TITLE
Fix Condensed Alert Spacing

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#16411]
## Issue Description
_Fix condensed Alert Spacing based on sketchy style rule_

## Front end tasks
- FE engineer estimate this task (
- Fe engineer remove the needs-grooming label
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by ncksllvn** [comment]
I believe this was done in https://github.com/department-of-veterans-affairs/vets-website/pull/15020

Related Slack thread, https://dsva.slack.com/archives/CDHBKAL9W/p1605036140013400
