### ISSUE TITLE
[Observation Session] Contact Center check in

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#16414]
We observed during a recent feedback session with a Veteran that he received in accurate information when he called HRC number (877-470-5947). 

We did training and updates in March/April with HRC, but it's probably worth re-reviewing now that all scheduling is pointing to VAOS on VA.gov.

### Specific feedback:
- [ ] when veteran was experiencing what he thought was a problem with the app not displaying his facilities, he called the HRC number
- [ ] the veteran was directed to MHV profile to review their 'preferred facility' option
- [ ] MHV profile settings do not translate to VA.gov
- [ ] when that didn't work, the Veteran was transferred to another MHV associated but the transfer resulted in the veteran having to leave a voicemail
- [ ] he still hadn't received a call back to his issue when we spoke

### Acceptance criteria:
- [ ] we need to sync with @clantosswett on HRC scripts + potentially schedule another HRC training of VAOS
- [ ] ensure that HRC reps understand the difference between MHV and VAOS - how they differ and where the connect

**Comment by clantosswett** [comment]
@lenaecb I am assigning this to @starlow00 who is a member of the VSP contact center team. He is going to be working on the development of these scripts and might be following up with you to get more information. Thanks!

**Comment by lenaecb** [comment]
@clantosswett - sounds good! We have a new product manager working with VAOS, so she'll likely be working with you and your team on this. Her name is Lauren Ernest (@laurenernest)

**Comment by laurenernest** [comment]
Tracking in #16612
