### ISSUE TITLE
parse birls and participant ids from SSOe SAML response

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#16415]
The `birls_id` and `participant_id` values from a user's MPI record are needed to complete form 526.  In some cases [MPI Proxy Errors](https://github.com/department-of-veterans-affairs/va.gov-team/issues/10524) prevent us from gathering those values when the user needs them.  However, for those users that are logging in via SSOe, the values should already be present in the SAML Response returned by SSOe (in the [birls_ids](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/mpi/responses/id_parser.rb#L77) and [vba_corp_id](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/mpi/responses/id_parser.rb#L58) values).

If available, we should parse those values out of the SSOe response and add them to the `UserIdentity` class.  The `User` class can then change the `birls_id` and `participant_id` delegated attributes to methods that first look up the value on the user's identity, then fallback to MPI when it's missing.  This should reduce the number of MPI queries needed as more and more users authenticate with SSOe, at least for form 526 processing.

**Comment by joeniquette** [comment]
I'm not exactly clear what values will be present and if it will be encrypted or not, but I do want to point out that the birls_id in my personal case is my SSN. I haven't researched to see if this is always the case, but it is greater than zero. We need to ensure this field is protected and not stored in generally accessible logs.

**Comment by bosawt** [comment]
Since the PR is part of another repo, it looks like I can't link it like I normally would. But it's merged now: https://github.com/department-of-veterans-affairs/vets-api/pull/5410
