### ISSUE TITLE
Service verification letter - Incorrect mobile alert background color

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#16416]
## What Happened?
The mobile alert background color is darker than the designs

## Specs:
- Device: Android - Google Pixel 3XL

## Steps to Reproduce
1. Navigate to the service verification letter page
2. Note the darker mobile alert background color

## Desired Behavior
- The background color should be hex code #F1F1F1

## Acceptance Criteria
- [ ] The background color is hex code #F1F1F1

## Bug Severity
- 4 - Low

## Linked Story
- Story #13942

## Screen Shot (s) and Additional Information
![Service Verification - Android Mobile Alert.png](https://images.zenhubusercontent.com/5f7bb216620a259ab7e50d60/62440f2b-244a-4082-b253-4d2e5e0a46c1)

**Comment by digitalken** [comment]
PASS 11/23/2020 - Background looks correct.
