### ISSUE TITLE
[Observation session] Type of care page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#16412]
Veteran expressed confusion as to why he is only seeing some types of care, but not others. Again this is an ongoing constraint given that online scheduling is only available for very specific care types that are established via OVAC/VA policy. 

This is not new feedback re: limitation of care type. However, we should think about how we're helping veterans understand why they only see this short list of care. 

### Additional feedback from the Veteran for us to consider:
- Veteran did not notice the "not seeing your type of care" alert, seemed to skip over
- Confused by the list of care types

### Considerations: 
- making it very clear throughout scheduling process that the appointments they are booking are what are available online. if they do not see their care type/need, that doesn't mean they can't schedule, it just means they can't schedule for that care online. This comes up on the VA Facilities page too. 
- we should consider this need when we start to do discovery on how to more effective direct a Veteran to call their desired facility straight from the app, and also consider this when looking at real-time communication options in app in the future

### Acceptance criteria:
- [ ] Ideate ways to make it clearer as to why this type of care list is displaying and may be limited
- [ ] Look at analytics to see how many folks are clicking 'facility locator' link (gives us idea of who is seeing their alert/not see the care they want)
- [ ] any feedback from the CC provider selection research sessions?

![Screen Shot 2020-11-19 at 10.34.55 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/b18f26ae-943f-424e-bef2-f79462e8e1bd)

**Comment by outerpress** [comment]
Just noting for when we get to this - one direction we discussed was to add an option like "My type of care isn't listed" and showing the alert text only if that's selected. This would help clean up the page and provide the veteran direct feedback when they need it.
