### ISSUE TITLE
Benefit Summary & Service Verification letter - Incorrect toggle label 

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#16425]
## What Happened?
The first toggle on the page is labeled "letters.benefitService.includeMilitaryServiceInfo"

## Specs:
- Device: Android - Google Pixel 3XL

## Steps to Reproduce
1. Navigate to the service verification letter page
2. Scroll down to view the first toggle
3. Note the label 

## Desired Behavior
- The first toggle should be labeled “Include military service information”

## Acceptance Criteria
- [x] The first toggle will be labeled “Include military service information”

## Bug Severity
- 4 - Low

## Linked Story
- Story #13947

## Screen Shot (s) and Additional Information
![Benefit Summary & Service Verification letter - Android Toggle.png](https://images.zenhubusercontent.com/5f7bb216620a259ab7e50d60/0ef553ca-2739-44ba-8467-1e363dc2d717)

**Comment by digitalken** [comment]
11/24/2020 - Pass on both iOS and Android.  Now says "Include military service information" for toggle.  Closing.
