### ISSUE TITLE
Analytics KPI dashboard request for Testing Team - Accessibility Health

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#16423]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [x] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [x] Link your KPIs below (KPIs should be in your Product Outline)
- [x] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the correct response.
- [x] New dashboard
- [ ] Iteration of current dashboard

### KPIs
[Product Outline for Accessibility Health Dashboard](https://docs.google.com/document/d/1PBCXUENJkhHscmcNW4iouoLxdf3lBQ1B7U3FrTRC0-I/edit?usp=sharing)

* Determine the number of open accessibility issues (total count)
* Determine the number of open accessibility issues by defect severity. Each issue is assigned one defect severity based on the [VSP accessibility rubric](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md).
* Track changes in total defects and defects by severity over time
* Be able to zoom into issues by type, by team, and by severity
* Develop additional insights into input, as well as the previously listed output _(This will most likely be a follow on request)_

### Veteran Outcomes We Want to Measure
* Adherence to Section 508 (accessibility) compliance. Are we getting better, staying the same, or need more improvement?
* Identify if VSP training, documentation, and support is improving VFS teams' adherence

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by pjhill** [comment]
This will be a Q2 effort.
