### ISSUE TITLE
IA feedback - Usability testing prep - Direct deposit for Edu

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#16420]

**Comment by mnorthuis** [comment]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description

**MUST**
- Engage Public Websites team for updates to static content


**CONSIDER**
- For scenario where the user does not have a disability direct deposit, but does have an education one, reverse the order so that education info appears at the top.  In some cases, users may not have direct deposit for disability compensation because they are not eligible for it, so this would ensure that an irrelevant item doesn't appear at the top. 


This issue describes IA feedback

## Definition of Done
- [ ] Must feedback is completed/implemented 
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once complete

**Comment by mshea0606** [comment]
Hey @sporeboy @jason-gcio , is this ticket ok to close?
