### ISSUE TITLE
Review and update margin/padding specs 

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#16424]
## Acceptance Criteria

Reference [MVP Mobile App UI Styles doc
](https://docs.google.com/document/d/1VC-CLWnhevB8HLBBHPwkSJvECn8EBie8HOkJylKE1lo/edit#)

Margin and padding specs should be reviewed and updated throughout the app as necessary to reflect requirements:

**L/R Gutters**
- 20px gutters to the L/R

**General Rules**
- 20px below top navigation bar above screen content
- 40px above bottom nav bar below screen content
- Generally, 20px vertical padding between elements. 
     - Per 11/19 discussion w/ Bridget: 10px vertical padding between headers & items below it
- Text views are all padded horizontally 20px. Text styles should all start/end at the same vertical place inside an element/card regardless of style

**Space between chevron icons and text (VCL, homepage cards)**
- 5px

**Component-specific padding rules: Card**
- 20px between top of card border and card content
- 20px between card content and bottom of card border
- 10px margin between cards

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...

**Comment by digitalken** [comment]
Testing...
