### ISSUE TITLE
Get schema from VA Video Connect App Team

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#16427]
To link from VA mobile app to VA Video Connect we need to get the schema from the VAVC app team. 

- [ ] Figure out what we need to ask
- [ ] Email VAVC app owners

**Comment by bridgethapner** [comment]
@lexicalninja can you post what we need to ask here?

**Comment by lexicalninja** [comment]
Yep! 
We need to contact the VA Video Connect App team and ask what url scheme they use for their app to pick up actions/intents. 

We should also ask if they have a deep linking path or how our app can best open the app the the correct page. 

If there are preferred links for us to use to refer users to their apps in the app stores, in case they are tracking referrals, then those would also be something to request.

**Comment by artsymartha68** [comment]
Info from @stephenBarrs (thanks!)

From the info.plist it looks like the URL Scheme is: vavideoconnect
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>vavideoconnect</string>
			</array>
		</dict>
	</array>

Aaron Steele is the VHA Office of Connected Care PM:
Aaron Steele	aaron.steele@va.gov	(202) 461-7302

LMK if dev team wants any other info I am happy to dig in.  i did not see anything indicating more complex deep linking from url scheme, but did not look in the code base that would handle the URL invoked launch of the app (and it has been many years since I have done any iOS dev)

**Comment by lexicalninja** [comment]
Wait, is this only on iOS?

**Comment by artsymartha68** [comment]
Excellent question! @stephenBarrs is OOO today. 

Repasting what he sent me, it seems to be missing from my cut n paste:

```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>vavideoconnect</string>
			</array>
		</dict>
	</array>
```

**Comment by artsymartha68** [comment]
The App Store says it works on Android.

**Comment by lexicalninja** [comment]
I am not seeing an android app here in play store

**Comment by artsymartha68** [comment]
https://mobile.va.gov/appstore/android

**Comment by artsymartha68** [comment]
Not sure it's in the official play store but this is the VA "App Store"

**Comment by lexicalninja** [comment]
I am looking on my phone and no VA Video connect app is available through the Play Store

**Comment by lexicalninja** [comment]
here is what is in play store
https://play.google.com/store/apps/developer?id=US+Department+of+Veterans+Affairs+%28VA%29

**Comment by artsymartha68** [comment]
What happens if you go here? Sorry, I don't have an Android phone
https://mobile.va.gov/appstore/android

**Comment by lexicalninja** [comment]
Those are links to the play store apps. But VAVC only has a link to the apple app store; there isn't a link to the Play Store. 
if I click on the Android link next to the icon it takes me back to the mobile.va.gov/appstore/android landing page

**Comment by artsymartha68** [comment]
Aaaaah..... here we go. Working as designed? No app on Android?

"VA Video Connect works on Android devices that have an internet connection and a web camera. No application download is required. Ahead of a VA Video Connect appointment, you will receive an email or calendar invite with a link to launch the session."

**Comment by lexicalninja** [comment]
That page needs some help. under each app it has links for ios android and maybe web. But the links just direct back to mobile.va.gov/app-type/<whatever>

**Comment by artsymartha68** [comment]
+1 on the confusion

**Comment by lexicalninja** [comment]
> Aaaaah..... here we go. Working as designed? No app on Android?
> 
> "VA Video Connect works on Android devices that have an internet connection and a web camera. No application download is required. Ahead of a VA Video Connect appointment, you will receive an email or calendar invite with a link to launch the session."

Not technically. It just uses the phones browser, but iOS has an app specifically designed for the form-factor. 

Using the browser just uses the web in whatever responsive way they have decided on. 

If you look at the play store reviews for the VA Launchpad, people are not happy about it

**Comment by artsymartha68** [comment]
Shall I try and set up a meeting with Aaron? Who all would like to attend?

**Comment by lexicalninja** [comment]
Probably. Lets bring this up next time you are at stand up and see who needs to attend. I don't want to assume anything for anyone on the team on this one since it may or may not be a big sticking point.
