### ISSUE TITLE
VSP content review - Staging - App directory

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#16428]
## User story 

This ticket captures VSP content feedback on App Directory in Drupal preview environment.

Preview link: preview-prod.vfs.va.gov/preview?nodeId=9615

## Acceptance criteria

- [x]  VSP provides content feedback for form/tool and any associated static pages 
- [x]  Team incorporates feedback and/or asks follow up questions about the feedback
- [x]  Teams leaves comments about any feedback they decide not to take
 - [ ] VSP checks form/tool after content feedback has been incorporated

**Comment by peggygannon** [comment]
@ricetj 

Is this App Directory a Veteran-facing page? If so, the content nested under the "Learn more" links doesn't adhere to our plain language and VA.gov content style guide guidance. 

Recommendation: please work with @bethpottsVADEPO and @RLHecht to get a content review for this content.

**Comment by ricetj** [comment]
> @ricetj
> 
> Is this App Directory a Veteran-facing page? If so, the content nested under the "Learn more" links doesn't adhere to our plain language and VA.gov content style guide guidance.
> 
> Recommendation: please work with @bethpottsVADEPO and @RLHecht to get a content review for this content.

Hello Peggy, thank you for taking the time to talk with us in the staging review yesterday. I agree that the text here is not as user friendly as one would hope, but this is coming straight from the 3rd party app, so we really don't want to edit or rework any content they are using to market to users.

**Comment by peggygannon** [comment]
thank you @ricetj for your follow up. I'm going to close this issue.
