### ISSUE TITLE
Center loading screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16438]
## User story
1. Center the loading screen, with a margin between the spinner and the text

This updates the original requirements for [#14725](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14725)

## Designs
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14725

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
11/24/2020 Pass on both iOS and Android. Centered vertically in screen. Moving to design QA.
