### ISSUE TITLE
Error message responses for FSR form

### ISSUE THREAD

**Issue by 3obryandogs** [department-of-veterans-affairs/va.gov-team#16439]
Peggy, BAM2 asked me to research error message replies for the FSR form. Would the following be the best option? There are more than 30 such required questions and statements in the form.

Is your spouse currently receive VA benefits?  (*Required) 

**Informational alert - We need your help to continue working on your request.**
Please answer the spouse benefits question so we can continue helping you fill out your request.

**Comment by peggygannon** [comment]
Hi, @3obryandogs 

- I want to be sure this question you listed above is fixed: replace Is with Does

**Does** your spouse currently receive VA benefits? (*Required)

- and few followup questions: 

will this message be shown only if the user skips a required entry? 

do you have a sample design for this yet. I'm wondering if  it's designed to be an alert or a validation error?

**Comment by 3obryandogs** [comment]
Peggy, no I don't. The designers asked me to figure it out. They want a statement when a required field throws back an error message. I looked through the list of options, but needed your input/direction. Thanks!

**Comment by 3obryandogs** [comment]
Peggy, thank you!

Yes, I alerted the designers to the Does your spouse currently receive VA benefits? (*Required)

They want an auto message if the required space is left blank.

**Comment by peggygannon** [comment]
@3obryandogs OK, sounds like this should be a validation alert that would appear if the entry is blank:  We have standardized messaging for this as a "Required form field empty" located  in our error message dictionary: https://design.va.gov/patterns/messaging-dictionary

Here's what I recommend: 
Please enter your [required information] so we can continue with your request. 

[required information] = what the question is asking for.  So for the example above it would be:  Please enter your spouse's benefit information so we can continue with your request.

**Comment by 3obryandogs** [comment]
Peggy,
Thank you! I really appreciate your help and guidance!

**Comment by peggygannon** [comment]
Hi, @3obryandogs is there anything more you need from me on this? Please let me know if you have add'l questions about FSR error messages. Otherwise, we can probably close this error message ticket

**Comment by 3obryandogs** [comment]
Peggy, it’s now in the hands of the design team to do their magic.

Thanks,
Susan

**Comment by 3obryandogs** [comment]
@leahkeeler - who should this go to next? I took Peggy off as an assignee since she's finished with her input.

**Comment by peggygannon** [comment]
Hi, @3obryandogs to answer your process question, once you pass along the error message recommendations to designers, they  they'd place it into their mockup. We'd check it again in the mockup.

**Comment by 3obryandogs** [comment]
According to Peggy's response, it would go to the designers. Does that fit in your planning?

**Comment by leahkeeler** [comment]
@3obryandogs Please provide content in a ticket for FE designers - I can create a ticket

**Comment by 3obryandogs** [comment]
@peggygannon 
**I have been asked me to shorten the error messages for FSR. Here is an example of I proposed:**
C2P1: Have you been employed within the past two years? (*Required)
• Please enter your employment information so we can continue helping you fill out your request.

**Would this shortened answer be OK with you?**
• Please enter your employment information.

**Comment by peggygannon** [comment]
@3obryandogs yes that shorten message will work
