### ISSUE TITLE
Edit Address - Misaligned hint labels on iOS

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#16436]
## What Happened?
_This applies to all of the edit address stories_

On iOS, the hint labels for each field are not centered

## Specs:
- Device: iOS - iPhone XR

## Steps to Reproduce
1. Navigate to either the mailing or residential address page
2. Note that the hint labels are not centered

## Desired Behavior
- The hint labels should be centered on the field 

## Acceptance Criteria
- [ ] The hint labels will be centered on the field

## Bug Severity
- 4 - Low

## Linked Story (s)
- Edit US address #13893
- Edit military base address #15058
- Edit international address #15059

## Screen Shot (s) and Additional Information
Showing misalignment
![Edit Address - iOS Text.jpeg](https://images.zenhubusercontent.com/5f7bb216620a259ab7e50d60/99a8468c-2d96-4262-a792-f30edb865a31)

**Comment by bessgreen** [comment]
## Additional UI issue: 
The hint text for State looks like a larger font size than the other hint text. 

![Image from iOS.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/31ed590d-8cdb-4c0b-8a3c-38a060d1c684)

**Comment by digitalken** [comment]
PASS 12/17/2020 - Hints look centered and matching fonts.  Closing.
