### ISSUE TITLE
EDU: Remove old prod flags

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16430]
As a developer, I need to remove old prod flags so that the update functionality is available in the production environment.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The functionality outlined in #7533 (#14419 is related) is available in the production environment.
2. The functionality outlined in #9243 is available in the production environment.
3. The functionality outlined in #8821 is available in the production environment.

Discuss 8821.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15071

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete. Closing this issue
