### ISSUE TITLE
Design Feedback - Usability Testing Prep - Authenticated Experience — Direct Deposit for EDU

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#16435]
- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

This looks nice! 

**Must:**
- None

**Should:**

- None

**Consider:**

- Putting the bank fraud in the warning or info alert style to draw more attention https://design.va.gov/components/alertboxes

**Definition of Done:**
- [x] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Allison will close the ticket once those things are all set. Thank you!

**Comment by mshea0606** [comment]
@sporeboy is this good to close?
