### ISSUE TITLE
STEM: Remove applicant CC code

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16433]
As a developer, I need to remove the applicant CC code because it is not supported by the email library being used.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The applicant is not CC'ed as part of the SCO email sent on 10203 submission.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5367

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are live. Closing this out
