### ISSUE TITLE
508-defect-2 [AXE-CORE]: App Directory - Heading levels should increase by one

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#16437]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As an assistive tech user, I want to hear headings read out in the correct nesting order.

## Details

Our app headings and sub-headings inside the accordions need to be H2 and H3 headings respectively. Screen shots attached below.

## Acceptance Criteria

- [ ] Axe browser plugin doesn't report a heading nesting best practice warning on future runs
- [ ] Current visual styles are maintained

## WCAG or Vendor Guidance (optional)

* [Heading levels should only increase by one](https://dequeuniversity.com/rules/axe/4.0/heading-order)

## Screenshots or Trace Logs

![Screen Shot 2020-11-19 at 2 22 53 PM](https://user-images.githubusercontent.com/934879/99720651-aacb7c00-2a73-11eb-9460-3649b9e5d32c.png)

---
![Screen Shot 2020-11-19 at 2 23 31 PM](https://user-images.githubusercontent.com/934879/99720682-b323b700-2a73-11eb-849b-f2b7171f2418.png)

**Comment by LeKeve** [comment]
This issue is now ready to be tested in production.

**Comment by 1Copenut** [comment]
We are 💯 Moving to close.
