### ISSUE TITLE
Design Feedback - Staging Review - [Bilby (Lighthouse End-User Experience Team) - App Directory]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#16434]
- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

**Must:**

- Style the Need help? section like the Sketch file under Templates or like this page (remove gray background and the word more) https://www.va.gov/health-care/apply/application/introduction

**Should:**

- None

**Consider:**

- None

**Definition of Done:**
- [ ] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Allison will close the ticket once those things are all set. Thank you!

**Comment by allison0034** [comment]
@ricetj can you please assign the correct designer for this? I was not sure who it was. Thank you! 😊

**Comment by careyotto** [comment]
@allison0034 What mockups are you looking at? The latest prototype does include black links for the additional info component  - the old files had blue because an old version of the design system sketch file included this error. Please let me know if I can be of further assistance. I will be OOO all of next week.

https://www.figma.com/proto/Oi4PR8zuoUwwMB2qbQnWtV/VA.gov-App-directory?scaling=min-zoom&node-id=271%3A5298

**Comment by LeKeve** [comment]
@allison0034 The mockups that Carey provided have the correct color. This is a front end update that needed to be made. The PR is linked to this issue and I will let you know when the changes have been made.

**Comment by allison0034** [comment]
@LeKeve ok thank you. The screen shots that were given to us were blue. I did add one more comment about the "Need more help?" section.

**Comment by ricetj** [comment]
> @LeKeve ok thank you. The screen shots that were given to us were blue. I did add one more comment about the "Need more help?" section.

@allison0034 The "Need More help" section is part of the Resource and Support (formerly Learning center) template. We do not control/ can not change anything there. You will need to talk with the Public Website team about any concerns in that section.

**Comment by allison0034** [comment]
@LeKeve got it, thank you
