### ISSUE TITLE
Identify & document transformers owned by VSA Public Websites

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16440]
## Overview 

The purpose of this ticket is to document ownership of transformers that are relevant to VSA Public Websites team. This will be used in part for triaging discrepancy issues in a forthcoming audit between GraphQL <> CMS Export Build.

## To Do

- Identify [which transformers](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/site/stages/build/process-cms-exports/transformers) should be owned by VSA Public Websites
   - Generate a list & send to VSP
   - Get various teams (VSP, Facilities, CMS) to sign off on this list (Megan to help with approval wrangling)

## Acceptance Criteria (WIP)

- [x] Transformers "owned" by VSA Public Websites team are identified and documented (ownership list is captured) 
   - [ ] VSP, VSA Facilities, CMS have signed off on this list

**Comment by jenniferlee-dsva** [comment]
The full github list still needs FE review, but on glance, these are the ones that I could identify as sitting with PW (and one thing with @johnhashva decision tools team).  There may be others that I didn't recognize and Nick/Kelson/someone on CMS might need to shed light on what they map to. @brianalloyd 

1. block_content-promos
2. node-basic_landing_page
3. node-checklist
4. node-faq_multiple_q_a
5. node-full_width_banner_alert
6. node-media_list-images
7. node-media_list_videos
8. node-q_a
9. node-step_by_step
10. node-support_resources_detail_page
11. node-support_service
12. node-va_forms <-- decision tools team
13. paragraph-audience_topics
14. paragraph-link_teasers
15. paragraph-list_of_links_teasers
16. paragraph-list_of_links
17. paragraph-process
18. paragraph-q_a
19. paragraph-q_a_group
20. paragraph-q_a_section
21. paragraph-react-widget
22. paragraph-rich_text_char_limit_1000
23. paragraph-step
24. paragraph-step_by_step
25. paragraph-table
26. paragraph-wysiwig
27. taxonomy_term-administration
28. taxonomy_term-audience_beneficiaries
29. taxonomy_term-lc_categories
30. taxonomy_term-topics

**Comment by brianalloyd** [comment]
@jenniferlee-dsva thanks for providing the list, @kelsonic and @ncksllvn could you guys review and update as needed.  Thanks.

**Comment by kelsonic** [comment]
This is what we currently have in our PR:

```
# Ownership

The files in this directory are owned by the following teams:

| Team          |   File
| ----------    | ------------------------------
| Facilities    | node-health_care_local_facility.js
|               | node-health_care_local_health_service
|               | node-health_care_region_detail_page
|               | node-health_services_listing
|               | node-locations_listing
|               | node-nca_facility
|               | node-vba_facility
|               | node-vet_center
|               | paragraph-health_care_local_facility_servi
|               |
| Public Web    | block_content-promo
|               | node-basic_landing_page
|               | node-checklist
|               | node-faq_multiple_q_a
|               | node-full_width_banner_alert
|               | node-landing_page
|               | node-media_list_images
|               | node-media_list_videos
|               | node-q_a
|               | node-step_by_step
|               | node-support_resources_detail_page
|               | node-support_service
|               | paragraph-alert_single
|               | paragraph-audience_topics
|               | paragraph-button
|               | paragraph-contact_information
|               | paragraph-email_contact
|               | paragraph-link_teaser
|               | paragraph-list_of_link_teasers
|               | paragraph-lists_of_links
|               | paragraph-process
|               | paragraph-q_a
|               | paragraph-q_a_group
|               | paragraph-react_widget
|               | paragraph-rich_text_char_limit_1000
|               | paragraph-step
|               | paragraph-step_by_step
|               | paragraph-table
|               | paragraph-wysiwyg
|               | taxonomy_term-administration
|               | taxonomy_term-audience_beneficiaries
|               | taxonomy_term-lc_categories
|               | taxonomy_term-products
|               | taxonomy_term-topics
```

**Comment by brianalloyd** [comment]
@kelsonic please confirm this is the final list.  @meganhkelley once confirmed can your team validate so we can close out this ticket in support.  Thanks.

**Comment by kelsonic** [comment]
Nope not the final list! I discovered some more yesterday 😂 will update it today and drop a note here when I do

**Comment by kelsonic** [comment]
Final list:

```
block_content-promo
node-basic_landing_page
node-checklist
node-faq_multiple_q_a
node-full_width_banner_alert
node-landing_page
node-media_list_images
node-media_list_videos
node-q_a
node-step_by_step
node-support_resources_detail_page
node-support_service
paragraph-alert_single
paragraph-audience_topics
paragraph-button
paragraph-checklist
paragraph-checklist_item
paragraph-contact_information
paragraph-email_contact
paragraph-link_teaser
paragraph-list_of_link_teasers
paragraph-lists_of_links
paragraph-media_list_images
paragraph-media_list_videos
paragraph-process
paragraph-q_a
paragraph-q_a_group
paragraph-react_widget
paragraph-rich_text_char_limit_1000
paragraph-step
paragraph-step_by_step
paragraph-table
paragraph-wysiwyg
taxonomy_term-administration
taxonomy_term-audience_beneficiaries
taxonomy_term-lc_categories
taxonomy_term-products
taxonomy_term-topics
```

**Comment by brianalloyd** [comment]
Thanks @kelsonic appreciate the solid effort towards transformer work.  CC @jenniferlee-dsva @johnhashva

**Comment by brianalloyd** [comment]
@meganhkelley what else is needed from our team on this ticket in support of close out?
