### ISSUE TITLE
Edit direct deposit info page - Embedded image missing on iOS

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#16448]
## What Happened?
The embedded image in the expanded section of the "Where can I find these numbers" dropdown is missing on iOS

## Specs:
- Device: iOS - iPhone XR

## Steps to Reproduce
1. Navigate to the edit direct deposit info page
2. Expand the "Where can I find these numbers" dropdown

## Desired Behavior
-  The expanded section should contain the embedded check image

## Acceptance Criteria
- [ ] The expanded section will contain the embedded image

## Bug Severity
- 3 - Medium

## Linked Story
- Story #13907

## Screen Shot (s) and Additional Information
Showing the affected element
![Edit Direct Deposit - iOS Image.jpeg](https://images.zenhubusercontent.com/5f7bb216620a259ab7e50d60/3a98d596-4bcd-4e56-a47e-4cad61cc9c51)

**Comment by digitalken** [comment]
PASS 2/1/2021 - Check images now displays in iOS.
