### ISSUE TITLE
Frontend - apply to PCAFC with only secondary caregiver(s)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16457]
Clones https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15161

**Comment by LinnJS** [comment]
This was addressed in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14999) and was merged last Friday.
