### ISSUE TITLE
Caregiver POA Discovery 

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16452]
## High Level User Story
As a Veteran or Caregiver, I need _____ so I can _____.

See notes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16485

## Goals
_What outcome(s) do we want to see?_ 

## Research questions 

- Can you tell me a little bit about POA and how it is currently being used?
- Are there any reasons (we need to be aware of) that made attaching POA documentation a top priority?
- When would a Veteran upload a POA document?
- What do you know about what document formats a Veteran may want to upload?
- How do you envision that adding POA documentation will change the online application process?
- What's the current paper process for attaching POA documentation?
- Are there any situations when a Veteran would not upload POA documentation?
- What would the risks be with adding this feature?
- Are there any dates/deadlines we have to be aware of?
- What are you looking to achieve with this feature?
- How will we measure if this feature is successful? 
- How will we measure if this feature is unsuccessful?

## Takeaways
- What problem are we trying to solve for Veterans?
- What problem are we trying to solve for program team and CSCs?

**Comment by mlighdc** [comment]
@ala-yna  and @jonathanjnelson would either of you like to drive the conversation tomorrow? Do you have your list of questions ready?

**Comment by jonathanjnelson** [comment]
Hi, @mlighdc 

Here are some questions that @ala-yna and I will revise in the morning. Alayna and I can discuss who will drive the conversation first thing. 

- What problem are we trying to solve for the user? 
- What problem are we attempting to solve for program team?
- Are there any reasons (we need to be aware of) that made attaching POA documentation a top priority?
- When would a Veteran upload a POA document?
- Will adding a POA documentation change the application process? 
- What's the current paper process for attaching POA documentation? 
- Are there any situations when a Veteran would not upload POA documentation? 
- What would the risk be with adding this feature?
- Are there any dates/deadlines we have to be aware of?

**Comment by mlighdc** [comment]
Thanks @jonathanjnelson and @ala-yna .  Couple of suggestions... I would think through the order of the questions for the conversation like you would for any conversation guide for user research. Unless you both know the reasons why POA is needed, I would suggest starting off with a basic question like that so you have background and understanding of how it is used in the Caregiver Application process. I typically like to say something like... assume I know nothing about POA, can you tell me a little bit about POA and how it is currently being used?

I know these are draft questions. The first two questions are stated differently so assuming these are questions to make sure you are asking the right questions after the first two bullets? 

Also, will the above questions provide enough information so you can prototype either something for the Caregiver team to look at or if you are planning for any usability sessions (or maybe combining it with the mini sessions we were thinking about for Secondary Caregivers - not sure what the plans are). It would be good to have a high-level plan or next steps of what you would do after this session with the Caregiver team. So I would be prepare to speak about next steps.

**Comment by ala-yna** [comment]
Thanks @mlighdc and @jonathanjnelson ! I edited the question list a bit and put it in the description of this Github issue. Once we get a sense of the scope for what they have in mind, we can start to think about prototyping. I agree it would be great to do a few usability sessions.

**Comment by ala-yna** [comment]
Notes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16485
