### ISSUE TITLE
Research & Discovery - Express Care

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1645]
### Problem Statement:
Some Veterans have a need right now that requires immediate medical attention or guidance. Express Care is a mechanism by which the VA can provide immediate, same day evaluation via video. 

Given the recent (COVID-19) pandemic, there is a need to give Veterans fast access to care and evaluation via video appointments. 

### Current Hypothesis:
- Veterans will seek Express Care is a separate flow from VAOS, because it is a same day not future facing functionality.
- Flow could be surfaced/launched from our VAOS "view your appointments" landing page, but there may be a better entry point. _What would that entry point be?_ 

### Research questions?
- Understand how Veterans define Express Care, why/when they seek it out, and where they would look to schedule/access this care 
- Understand how veterans use Express Care so that we can design a scheduling flow for this care option that's most useful to veterans and that integrates seamlessly into the overall VA healthcare appointment scheduling flow.
- Do Veterans understand what "Express Care" is/means? Do they distinguish between Express Care and Telehealth?
- We do not want to show express care to veterans who do not have access to it. Right now there are a lot of rules around who can use it. There's some technical discovery involved there to determine if we can conditionally show this option, and the technical conditions under which we would show it. (i.e. we do a PACT call and you don't have a PACT -- don't show.) 
- How would Veterans use an 'express' access? What would they use it for? What is the thing? 
- Is this thing for urgent care or is it just another low barrier pathway to get care access?

### Project Plan Brief 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/express-care-research/express-care-project-brief.md

### Zenhub link
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1645

**Comment by artsymartha68** [comment]
Adding these Express Care/VAOS sample screens that we received in email so we have them handy.

[ExpressCareSampleScreens.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4360686/ExpressCareSampleScreens.docx)
