### ISSUE TITLE
Access for Holden Hinkle

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#16468]
@department-of-veterans-affairs/vsp-operations 

# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Holden Hinkle (Emmerson Hinkle)
- Please Provide your email.
   > holden.hinkle@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Test Team, Rails Engineer, Oddball Inc.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCighaSYxWOCKEmwL/BytMHP5RFeYrgQFDhVHw0+GoT7wHsSLvZ9fHM8VFtONP15CMufx6FfCKKsU4zUV1buUCjF4OvM27GTww0lbjBQbsA6WnaK/TvbKHMP9BLi3D+wymvHHM37auE1RJ3iSt/lWDmoizimCS1LifDgP6HgRAV2kVt0v0FycJmwmX5Ruqu1/QY+SON1S8g0n0lh8oqIuD+A+DpVRZ6klowHd6lemma0fZ/fGf3fdpLnI5RceTKiE3+d5jAliFrO4ueG+sq58hR4uQ6raAQKhXICnuKA42Es7FZc4QIdErfU6G6dPeycm9GPdxFNFh5ntPPwyTJnqp2BoOxGIDg6vfmTFmIZSUQBwCrBsL2hmgmMevHvmhOKGzb94Tkwd5B+MScu33six6J7+kqBmhxUaDJcICKqaMPrsvxz64EiuX8HdAEDtHP61h3DbutYX6Ji8bsJnkX09NBriaMhb2strJw2sbteH/rkSpwWZkyG76LOUnvO2ZiZ18= holdenhinkle@Holdens-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
     > New test team member and will need access to relevant developer services

**Comment by jbritt1** [comment]
For AWS Access:

User: Holden Hinkle
COR: Jeff Hayter
Approval required: @Jeff-Hayter

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
