### ISSUE TITLE
Save phone number: Service integration

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16460]
This is a backend task to save a user's phone number. The associated UI is included in different stories. 

## Acceptance Criteria:

1. Make call to save a user's phone number on the following pages:
     - Home phone
     - Work phone
     - Cell phone
     - Fax number
2. Selecting the "Save" button will save the fields in the edit screen and on the Personal Information page. The saved fields should persist & appear to the user if & when:
     - The user navigates to other pages in the app, then returns to the Personal Info / Edit page(s)
     - The user logs out of the app, signs back in, and returns to these pages

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Bug entered on saving a phone number where there isn't already one existing.
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16907

**Comment by digitalken** [comment]
Inconsistent saves at this time. Alistair is working on new backend stuff so retest after that.

**Comment by digitalken** [comment]
Testing...

**Comment by digitalken** [comment]
PASS 1/14/2021 - Phone numbers are being saved regardless of there was already one there previously or not.  Moving to Design QA.
