### ISSUE TITLE
Determine solution for auto-deploy of content using CMS Export Build

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16478]
### User Story 

As a content editor, I want to see my published content on VA.gov within minutes, without having to ask someone to kick off a manual deploy. 

### Description 

Content editors and VA stakeholders expect that when we release CMS Export Build, the above user story will be met — there will be an auto-deploy that will publish the content to VA.gov. Currently, according to Neil (CMS team), "The content deploy occurs at 2pm, it can also be manually trigger from the CMS.  The content deploy will also be triggered if a site alert is published." 

The purpose of this ticket is to investigate and agree upon a solution for the auto-deploy, and document all next steps in order to implement that solution. 

## Acceptance Criteria for Solution 
_Must have_
- [ ] New content published in CMS automatically publishes on VA.gov with X minutes (ideally 5 or fewer) 
- [ ] Regular deploy of new content in CMS does not require developer intervention (aka does not need to be manually kicked off — manual intervention for troubleshooting is expected)

_Nice to have_
- [ ] Auto-deploy job is not running significantly more frequently than frequency of expected content updates

## Definition of Done for Ticket
- [x] Proposed solution for auto-deploy of content written up in design doc — use [template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/design-doc-template.md)
- [x] Design doc approved by required approvers
- [x] Design doc merged 
- [x] Tickets created for implementation of auto-deploy solution

**Comment by meganhkelley** [comment]
@jhonnyoddball design doc folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering/design-docs

Use the template to create a design doc for your proposed auto-deploy solution, submit it as a PR and ask for review from: Theo, Dan, Neil Hastings, Dror, and Fleet

**Comment by joanneesteban** [comment]
@jhonnyoddball  - Checking in to see if any progress has been made on this transformers ticket.

**Comment by drorva** [comment]
Basic approach:
* create a jenkins job
* Run it every N minutes. Start with 30 or 60 and reduce it over time to 5. This gives us time to analyze if anything fails.
* The Jenkinds job runs a script that does the following:
  * aborts on error `set -e` in a shell script
  * Download the tar file
  * do a `cmp` with the previous run's tar file
    * if they're identical, exit. We're done. 
  * Extract the files
  * rsync the files over the previous extract directory
  * run the build script.
  * From here on, do the standard CMS deploy as before. Double check that we only rsync files that have changed to S3.

**Comment by indytechcook** [comment]
In looking at this and at the step from the planning document `Add CMS Export to Jenkins` I have a few questions about how the process works and what this step means.

`Download the tar file` - Does this refer to the tar file from the `http://prod.cms.va.gov/cms-export/content`?  It sounded like there is a Jenkins job to get this tar file from the CMS and upload to s3 and another job to use that file for the build.

**Comment by mchelen-gov** [comment]
@indytechcook my interpretation was that "Download the tar file" refers to pulling the TAR from the Drupal endpoint you posted, and the only time S3 is involved is for upload of build output.

however i'm not sure how "do a cmp with the previous run's tar file" would be done within the jenkins job

@drorva where is the "previous" tar file coming from, is that a jenkins artifact?

**Comment by drorva** [comment]
The CMS export build fetches the tar file with all the JSON nodes from the Drupal server. 
Once the build and deploy is successful, that file becomes the "previous" tar file. 
The good news is that if for some reason the process fails and there's no previous tar file, the build will just run again.
