### ISSUE TITLE
[FE] Direct deposit for comp & pen: Update copy so it matches eventual direct deposit for edu designs

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#16470]
## Background

As Jim was developing the direct deposit for edu designs, Peggy suggested we [update some of the direct deposit copy](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15518#issuecomment-718869730). We'll implement this copy for direct deposit for edu when we do the direct deposit for edu build, but in the meantime, we should update the direct deposit for comp & pen copy so it's consistent.

**Copy**

Please update the following labels in the direct deposit for comp & pen edit state:

- Routing number (Your bank’s name will appear after you add the 9-digit routing number)
- Account number (This should be no more than 17 digits)

Please update the [saved state confirmation copy](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/51b79b7f-f94e-4edd-85ee-642deb647e6f):

- We’ve updated your bank account information for your **compensation and pension benefits**

## Tasks

- [ ] Update edit state copy
- [ ] Update saved state confirmation copy

**Comment by Samara-Strauss** [comment]
Was this closed because it is finished? Or because it was closed in favor of another ticket. When closing, please include a short note about why. Otherwise, I have no idea what the actual status of the work is.

**Comment by mshea0606** [comment]
Will do. This has been completed.
