### ISSUE TITLE
 [SCREENREADER]: GIBCT® Colmery 107 - Other location error is being fired immediately on Other selection

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1647]
## Description

When I select Other for the location where I'll take classes, the error handler about zip code needing to be a five-digit number fires immediately. This could be confusing to assistive device users, because they haven't entered any information. Animated GIF attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a user, I want the error message to fire after I have incorrectly entered data or left the ZIP Code entry field.
* As a screen reader user, I do not want to hear the error message before I have entered any data into the ZIP code field.

## Environment

* Win10
* Multiple browsers and screen readers
* https://staging.va.gov/gi-bill-comparison-tool/profile/11806124

## WCAG or Vendor Guidance (optional)

* [Error Suggestion: Understanding SC 3.3.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-suggestions.html)

## Screenshots or Trace Logs

![other-location-error-event.gif](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/5d3ba0f2-0b97-4c31-9ccc-1152c2f92a45)

**Comment by ksantiagomorgan6** [comment]
Already fixed and merged 

https://github.com/department-of-veterans-affairs/vets-website/pull/10685

**Comment by 1Copenut** [comment]
@desireeturner I verified the error is not firing on first load of the Other zip code field. 

Do we want the error to fire if users enter an invalid zip code (say 2-3 digits or add letters) and leave the field?

**Comment by desireeturner** [comment]
@1Copenut I confirmed with @amyknox and @dneel-bah that we do want the error to fire if users enter an invalid zip code and leave the field. It looks like it is doing this (immediately) when letters are added but not when fewer than 5 numbers are added.

**Comment by desireeturner** [comment]
Entered https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19674 to cover the update discussed above.

**Comment by delli-gatti-michael** [comment]
@1Copenut looks like the fix for this is live on staging and the issue for entering fewer than five numbers is covered by https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19674. Is this issue ready to be closed?

**Comment by desireeturner** [comment]
@1Copenut Bringing this back to the top of your inbox. See @delli-gatti-michael's comment above. Is this something we can close out or do you have additional feedback?

**Comment by 1Copenut** [comment]
@desireeturner I just re-tested this and it's looking great. Moving to close.
