### ISSUE TITLE
Use `cheerio` dependency instead of `libxmljs`

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#16486]
Per discussion (internal) https://dsva.slack.com/archives/C5HP4GN3F/p1605894432045100. 

The latest `libxmljs` dependency with the recent Node 14 upgrade doesn't have up to date binaries, see https://github.com/libxmljs/libxmljs/issues/582 and the install falls back to `make`ing it from source, which increases the build time and creates an OS level dependency on `gcc-c++`. 

There is a newer, maintained fork that has binaries for Node 14, `libxmljs2`, see https://github.com/libxmljs/libxmljs/issues/582#issuecomment-730960923 and https://www.npmjs.com/package/libxmljs2 if we want to do that. 

> `npm install libxmljs2`

However, @ncksllvn mentioned that they think `libxmljs` is just used for the sitemap and that we can use `cheerio` instead, which is already an existing dependency.

**Comment by ElijahLynn** [comment]
Here is a PR to update to the better maintained `libxmljs2` that ships with binaries so we don't have to `make` from source and would improve build times. I don't know how to do the Cheerio upgrade and this is the next best option > https://github.com/department-of-veterans-affairs/vets-website/pull/15096. _

**Comment by timwright12** [comment]
**vets-website instances**

[sitemap-helpers.js#L1](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/tests/sitemap/sitemap-helpers.js#L1)

[lookup-non-english-pages-in-sitemap.js#L2](https://github.com/department-of-veterans-affairs/vets-website/blob/main/script/lookup-non-english-pages-in-sitemap.js#L2)

**content-build instances**

[lookup-non-english-pages-in-sitemap.js#L2](https://github.com/department-of-veterans-affairs/content-build/blob/main/script/lookup-non-english-pages-in-sitemap.js#L2)

**Comment by jhonnyoddball** [comment]
Expired. Closing
