### ISSUE TITLE
Benchmark GraphQL build & deploy time and prepare to measure for CMS Export Build

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16480]
### Problem Statement 

We have committed to reaching a 5 minute "publish time" with CMS Export build, but we do not have a benchmark for this metric in GraphQL, and we have not defined "publish time". 

How might we define & benchmark this metric so that we can track changes in it over time & build pipeline systems?

### Definition of Done 
- [ ] Determine what makes sense to measure — build time? build + deploy time? Something else? 
   - [ ] Discuss metric definition and get sign off from Megan, Dror, Dan
- [ ] Obtain benchmark of determined metric for GraphQL
- [ ] Make a plan for obtaining this metric on a recurring basis (as necessary) and document it in accessible place
- [ ] Determine whether we can measure this for CMS Export Build before release 
   - [ ] If so, measure
   - [ ] If not, determine plan for measuring during and/or after CMS Export Build release

**Comment by joanneesteban** [comment]
@theodur  - Checking in to see if any progress has been made on this transformers ticket.

**Comment by theodur** [comment]
@joanneesteban I'm currently working on documenting the process for tracking the build time metric, which we have determined should be build time + deploy time since we want to track the *publish time* which is the time it takes to build and deploy content to va.gov.

**Comment by drorva** [comment]
It'd be helpful to break this into the following (and if I remember right the build already has way more info about the various stages than this).
* Download: time from the script started to tar file downloaded
* Transformation: from downloaded to HTML files produced
* Deploy: from the previous step to the HTML file available on the web site.

**Comment by theodur** [comment]
@drorva I've added a [Content Loading Time](https://github.com/department-of-veterans-affairs/va.gov-team/pull/17415/commits/d4035bd41944a9f0ccc8038cd84c6f7d1eb9176c) metric to the documentation which consists of the _download and transformation_ time for the CMS export build, and the _download_ time for the GraphQL build. Since the GraphQL build is running queries and the CMS build has the extra step of downloading and transforming the data; this metric will give a fair comparison between the two builds while only focusing on the time it takes to _"load_" the content. Please let me know your thoughts.

**Comment by drorva** [comment]
@theodur looks good.

**Comment by timwright12** [comment]
Going to add the following data collection to the spreadsheet for both tabs.

**Delta**
The current content loading time can vary wildly from as low as 2mins to near 20mins. Tracking delta between these items should hopefully show that the new CMS export is more stable, having a smaller delta value.

**Median**
Documenting the average build time, this will hopefully be lower with the new CMS export process as well.

**Mean**
Tracking the mean (middle values) for good measure as well, I would expect to see a lot more clustering in the middle with a more stable process.

**Comment by timwright12** [comment]
Linking up a couple important documents here:

[Comparing GraphQL and CMS Export Build Times](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d4035bd41944a9f0ccc8038cd84c6f7d1eb9176c/products/cms-integration/content-build-comparison.md)

[Comparison Spreadsheet](https://docs.google.com/spreadsheets/d/1VLLC9JN44fty0_gFTzCXjbGrkKFBTletcDoAi-3Fci0/edit#gid=0)

**Comment by theodur** [comment]
The documentation has been [merged](https://github.com/department-of-veterans-affairs/va.gov-team/pull/17415) into [va.gov-team/master](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/cms-integration/content-build-comparison.md).
