### ISSUE TITLE
[Content] 526: Update Content on Disability Add Page

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16489]
## Issue Description
When adding a disability it seems to come up often that veterans and service members are unsure whether they are required to use the auto suggested disabilities. Suggest something to draw attention to it (bolding) and changing the wording a little.

https://staging.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/add

![image](https://user-images.githubusercontent.com/53824125/99838215-00606100-2b26-11eb-9d52-daeb10bb1381.png)

Suggest changing the text from:

> If you know the name of your condition, you can type it here. You can write whatever you want and we’ll make suggestions for possible disabilities. (Shorter descriptions are better. For example, foot pain, back pain, or hearing loss.)

To: 

> If you know the name of your condition, you can type it here. **You can write whatever you want and we’ll make suggestions for you, but you do not need to select one of the suggestions.** (Shorter descriptions are better. For example, foot pain, back pain, or hearing loss.)

The bolding is part of the new text so that it is obvious.  I suggest we not have to do usability on this but run this past Peggy.

Note: I am asking Jennifer whether bolding is acceptable or whether we should use another method to draw attention.

Update from Jennifer: 
> We no longer use <b> to bold test, rather we use <strong> which will sometimes convey emphasis.

---
## Tasks
- [ ] Implement change once approved.

## Acceptance Criteria
- [ ] Peggy approved.
- [ ] Jennifer approved

**Comment by jenstrickland** [comment]
The `<p>` element is not allowed to appear in the`<label>`, since it is a block-level element.

## Current code

```html
<label id="root_newDisabilities_0_condition-label" class="schemaform-label" for="root_newDisabilities_0_condition">
  <p>If you know the name of your condition, you can type it here. You can write whatever you want and we’ll make suggestions for possible disabilities. (Shorter descriptions are better. For example, foot pain, back pain, or hearing loss.)</p>
  <span class="schemaform-required-span">(*Required)</span>
</label>
```

## Recommended code

```html
<!-- wrap section in a fieldset -->

<fieldset>

  <legend>New Disability</legend>

  <p>If you know the name of your condition, you can type it here. <strong>You can write whatever you want</strong> and we’ll make suggestions for possible disabilities. (Shorter descriptions are better. For example, foot pain, back pain, or hearing loss.)</p>

  <label id="root_newDisabilities_0_condition-label" class="schemaform-label" for="root_newDisabilities_0_condition">
    What is your disability? <span class="schemaform-required-span">(*Required)</span>
  </label>

<!-- etcetera -->

</fieldset>
```

**Comment by peggygannon** [comment]
@luke-gcio @ndsprinkle Here is my content recommendation below. Please let me know if you have any questions. Thx! 

A few thoughts from me: 

-  I replaced "typing" with "enter" Reading this again, I don't want to assume how users will interact with the site. 
-  I've also made recommendation to the validation error that appears if a condition isn't entered, as well as slight tweaks to the content under "What if I don't know the name of my condition" link. This content is all related with the initial field of condition. 
- I'm also recommending update the header. It currently says "New disability", but the supporting content refers to it as a condition. 

--------

Updated content:  

Header: **New condition** 

If you know the name of your condition, you can enter it below. If you’re not sure of the name, you can enter what you want and we’ll suggest a list of conditions. You don’t have to choose one of the suggested conditions.  
(When entering a condition name, we recommend you use shorter descriptions. For example, foot pain, back pain, or hearing loss.)

Validation error:
Please enter a condition or select one from the suggested list

What if I don’t know the name of my condition? (link)

If you don’t know the name of your condition or aren’t finding a match from the list, enter your symptoms and we’ll help you figure out the name of your condition during the exam process.
Shorter descriptions are better. For example:
	My knee hurts when I walk.
	I have trouble hearing when other people talk.
	My doctor says my cancer may be related to my service.

**Comment by sshein** [comment]
interesting. Do we think moving "you don't have to use one of the suggested conditions" to its own line would help? I'm worried people won't read that block of text so they still won't see it

**Comment by jenstrickland** [comment]
I agree with Shawna. Iirc there was research that people didn't see that, so making it super clear would be helpful. Alternatively, bold that phrase, maybe?

**Comment by sshein** [comment]
oh it looks like this is related https://github.com/department-of-veterans-affairs/va.gov-team/issues/13639

**Comment by luke-gcio** [comment]
Wow this ticket is quite a party now.

**Comment by kevinstachura** [comment]
Oh wow, lots of discussion on this! Really good ideas. I will work on @sshein 's concept of maybe separating out the 'you can save it as entered' concept. Just wanted to throw my concept in there too, before I saw all this:

<img width="858" alt="Screen Shot 2020-12-07 at 9 53 49 AM" src="https://user-images.githubusercontent.com/54544300/101365863-4df10380-3872-11eb-9c68-95fd3e8813c9.png">

As far as users not necessarily reading what the given instructions above, I can see if we have research that indicates that they do not - though I don't recall specific research indicating that. In fact, I remember in a lot of the UAT sessions that users would usually read that first part, however when no pertinent suggestions were returned, they were unsure how to proceed (hence why we need to let them know they can add whatever they want and save).

Will continue massaging this concept and see what sticks. Thanks team!

**Comment by Mottie** [comment]
I combined all the suggestions and ended up with this...  how does it look?

I've also added numbering because during UAT, we always see the Veteran counting their entries

![Screen Shot 2020-12-07 at 10 08 42 AM](https://user-images.githubusercontent.com/136959/101374943-6bbf6800-3874-11eb-9cf2-df2eb1bbd091.png)

**Comment by peggygannon** [comment]
Hi, @kevinstachura and @Mottie here's additional recommendations from me, based on your mockups ^^^

Also, what are your thoughts about doing away with the helper link (What if I don't know the name of my condition), since we've added info to this content about what user can do if they don't find a match? 

also, i don't recommend putting the (*Required) right after You don't have to choose one of the suggested conditions. I'm concerned that that might be confusing to users. 

I moved the line about not having to choose from the suggested list up next to first sentence. I put it as bold here, so the content wasn't so choppy, but defer to you as to what makes sense with design. 

-------- 

**Please tell us the new conditions you want to claim**
Header: New condition

Enter the name of your condition below and we'll suggest some possible matches. **You don’t have to choose one of the suggested conditions.**

If you don’t know the name of your condition or aren’t finding a match, you can save the condition as you've entered it. We’ll help you figure out the name of your condition during your exam. (Shorter descriptions are better. For example, foot pain, back pain, or hearing loss.)

**Comment by Mottie** [comment]
Updates to content with accessibility fixes have been merged.
