### ISSUE TITLE
Establish rollback plan for each phase of CMS Export Build release

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16482]
This ticket is for documenting a rollback plan for each phase of CMS Export Build release.

The rollback may be pretty straightforward, but we should be sure to consider things like: 
- [ ] How fast would rev-proxy changes take effect?
- [ ] How much of a burden will it be on Ops to coordinate with us?
- _what other edge cases or dependencies do we need to consider as part of a rollback plan?_

### Definition of Done 
- [ ] Open questions above are answered and agreed upon by VSP team members
- [ ] Rollback plan is documented as part of release plan ([Google Doc](https://docs.google.com/document/d/1G8HdQfyQwrsHmpOL15NwkrYhEgLXxhGr2r18g1mrTd0/edit#heading=h.6qhhf96uvqnf)) and approved by team & Dror

**Comment by meganhkelley** [comment]
Note that technical release plan should be copied into Confluence and/or va.gov-team (out of Google Docs) at some point

**Comment by U-DON** [comment]
The default proxy URL for the site is `http://www.va.gov.s3-website-us-gov-west-1.amazonaws.com`

https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-prod.yml#L7

We could append the designated key for the CMS export build (something like `/cms-export`) to have the site point to it.

**Comment by U-DON** [comment]
The script that syncs the build to the deployment bucket:
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-speedy-s3-assets/tasks/main.yml#L11-L18

The config for that script:
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-website-vagovprod.yml

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
