### ISSUE TITLE
Use facility locator data on appointment list page

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#1648]
The services we call to get pending and confirmed appointments don't return facility addresses or phone numbers, so we can't full build the mocks for those detail pages.

To get around this, we can pull the data from the `/facilities` endpoint and incorporate it into the page.

AC:
- [ ] Address and facility phone number are displayed on the page
- [ ] The facility data is loaded lazily, and doesn't block the rest of the info on the page from displaying
- [ ] The facility data is saved in the Redux store similar to requests and doesn't have to be fetched if it's already been fetched once

**Comment by markgreenburg** [comment]
@narin or @goldenmeanie do either of you know if this ticket is still needed? I actually think we could use the facility data in a few different places (e.g., if a veteran gets stuck, give him/her info about a given facility to call), but I'm not sure if this data is still necessary for the appointments list views. @goldenmeanie - could you please take a look at what's on the appointments list now on staging.va.gov/vaos and update us on whether or not you think we're missing facility data? I think what's on staging now matches the latest mocks, but I might be wrong.

**Comment by narin** [comment]
@markgreenburg  I'm not sure I've seen the latest mocks and whether the map is still in play, but I believe the [mock data](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/engineering/mock-data.json) from staging does have address info, but not phone.  I'd imagine the phone number is pretty important data in case the vet needs to talk to someone directly.

**Comment by jbalboni** [comment]
This ticket is still needed, in order to display the address and phone in the appointment list items. We don't get either of those for confirmed appointments. It might be something to do consider pushing back in priority, since we can link directly to a facility's facility locator page, which has address and phone.
