### ISSUE TITLE
Text rows where toggle switches are (letters, for example) need to have entire row tappable, not just the toggle switch (iOS)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#16490]
## What happened?
In Android the entire text row is tappable where a toggle switch appears but the same is not true for iOS.

## Specs:
- Device: iOS (iPhone SE)

## Steps to Reproduce
- Navigate to a letters configuration page and find that in iOS, only the toggle is tappable. 

## Desired behavior
Should have the entire row tappable to work the toggle switch because the switch is too small for accessibility.

## Acceptance Criteria
- [ ] Whole text row where toggle switch appears should be tappable.

## Bug Severity
- 4 - Low

## Screen shot(s) and additional information

![toggleSwitchIOS.jpg](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/57097c06-5c33-4c5f-9348-7dce20629a05)

**Comment by komaly15** [comment]
@bessgreen @bridgethapner if we make the entire row tappable, the switch component will lose its animation unless we click directly on the switch (we will not see that circle in the switch move left to right/right to left, it will just update to be on the left or right). For this bug we will need to either lose that animation and make the entire row tappable to pass accessibility, or we need to make the switch bigger to pass the min sizing accessibility requirement.

**Comment by bessgreen** [comment]
@msmanak looping you in here for input!

**Comment by digitalken** [comment]
PASS 1/21/2021 - Entire line is now tappable.
