### ISSUE TITLE
[COGNITION]: GIBCT® Colmery 107 - Other location ZIP code error message is unclear

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1649]
## Description

The error message for valid 5 digit zip codes that return no city uses language I'm unfamiliar with. I'd like to review this with the content team and see if the error message is as clear as we'd like. Screenshot attached.

/cc @peggygannon 

## Point of Contact

**VFS Point of Contact:** _Trevor, Peggy_

## WCAG or Vendor Guidance (optional)

![Screen Shot 2019-09-09 at 1.29.20 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/61078197-a0d5-43d5-aebe-17a2bb70c92b)

**Comment by desireeturner** [comment]
@department-of-veterans-affairs/bah_uxteam Can you review the question posed in this issue regarding content?

**Comment by amyknox** [comment]
@desireeturner - we'll look into this.  This story is impacted by the additional 107 update we discussed with EDU / DSVA this afternoon.

**Comment by amyknox** [comment]
@1Copenut - finalized content is **Zip code must be a 5-digit number**

This is live on production now.  Thanks for your help!
