### ISSUE TITLE
Draft updated coronavirus alert box

### ISSUE THREAD

**Issue by 3obryandogs** [department-of-veterans-affairs/va.gov-team#16492]
Using the resources provided by DMC team, draft preliminary coronavirus alert box. It has been OK'd by Peggy and the DMC team. It now goes to Danielle for her input and to present it to the joint task force for approval.

**Comment by 3obryandogs** [comment]
Peggy, I've been asked to rough out a DMC alert box (to replace the coronavirus box that expires Dec. 31. Leah and DMC requested that I send this to you for first review. Your thoughts?


**VA overpayment collection no longer on hold** 

Collection of VA overpayments will begin Jan. 1, 2021. Collection had been on hold through Dec. 31, 2020, to ease financial burdens on Veterans. Suspension of repayment arrangements have now ended. The Debt Management Center has started sending out notification letters to Veterans for overpayments created after April 3, 2020. 

If you receive VA benefits, we will resume withholding with your Feb. 1, 2021, benefit payment to repay your VA overpayments unless other arrangements are approved by DMC.  If you do not receive VA benefits, repayments will be due Feb. 1, 2021, to the DMC.

If you want to take action on your debt now, please call us or submit your request online at https://iris.custhelp.va.gov/app/ask/

**Comment by leahkeeler** [comment]
Hi @peggygannon I assume this will need approval by the corona virus task force similar to the collection suspension one?

**Comment by peggygannon** [comment]
hi, @3obryandogs @leahkeeler  Yes, this will need to be approved by COVID task force. Here's my recommendation and a few questions below. This recommended alert needs to be reviewed/ approved by covid task force team. 

Question: 
- Do this line mean that Veterans will have to repay their whole debt by Feb 1? I removed it from my recommendation b/c I wanted to understand this line... 
*If you do not receive VA benefits, repayments will be due Feb. 1, 2021, to the DMC.*

- I added a line about health care debt so users know go elsewhere to get updates about that type of "debt" 

-------

**We’ve restarted collection on VA overpayments**
Starting Jan. 1, 2021, we’ll start collection on VA overpayments created after April 3, 2020.  

To start making payments again, please call the VA Debt Management Center at 800-827-0648 (or 1-612-713-6415 from overseas) to avoid additional late charges, interest, or collection actions. 
If you receive VA benefits, we’ll keep part of your monthly benefit payment to help repay your overpayment unless the DMC has approved other payment options for you. 

If you have VA health care copay debt, go to our [pay your copy bill] page to learn about your payment options.

**Comment by leahkeeler** [comment]
@peggygannon @3obryandogs Since the debt letters will be staggered, we ned to avoid any reference to when the debts need to be repaid. Thanks!

**Comment by 3obryandogs** [comment]
Peggy, how should we reword the line about health care copays to remove “debt?” Also, what is the process for getting this to the COVID task force? Do you do that, or is something I can do?

Could we say:

If you have VA health care copay overpayment, go to our [pay your copy bill] page to learn about your payment options.

**Comment by peggygannon** [comment]
Hi, @3obryandogs 

Danielle is part of the COVID task force, so please share this alert with her and she'll get it in the queue for approval. 

How about this update for the health care line: 

If you have VA health care copays, go to our [pay your copy bill] page to learn about your payment options.

**Comment by 3obryandogs** [comment]
Danielle,
The alert box on the DMC needs to be updated since collection will begin again Jan. 1. The following message has been OK'd by Peggy. Would you please put it in the queue for COVID-19 task force? I've been told approval is necessary. Thank you!

**We’ve restarted collection on VA overpayments**

Starting Jan. 1, 2021, we’ll start collection on VA overpayments created after April 3, 2020.
To start making payments again, please call the VA Debt Management Center at 800-827-0648 (or 1-612-713-6415 from overseas) to avoid additional late charges, interest, or collection actions.
If you receive VA benefits, we’ll keep part of your monthly benefit payment to help repay your overpayment unless the DMC has approved other payment options for you.
If you have VA health care copays, go to our [pay your copy bill] page to learn about your payment options.

**Comment by DanielleThierryUSDSVA** [comment]
@leahkeeler @rebeccawalsh We've received JTF/OPIA approval on the following content for this alert. Please note that they've asked us to check in with DMC stakeholders to make sure their legal folks have reviewed. I will follow up with Jill on this and cc you Leah. 

## We’re collecting again on VA debt

On April 3, 2020, we paused collections on new VA debt. On **January 1, 2021**, we started to send out debt collection letters again. If we granted you an extension due to COVID-19, we’ll start collection again on **February 1, 2020**.

If you can’t make your payments, we can help. To avoid late charges, interest, or other collection actions, make a payment or request help now. Call us at <a href="tel:+18008270648" aria-label="8 0 0. 8 2 7. 0 6 4 8.">800-827-0648</a> (or <a href="tel:+16127136415" aria-label="1. 6 1 2. 7 1 3. 6 4 1 5.">1-612-713-6415</a> from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET. Or send us a question through our [online question form (called IRIS)](https://iris.custhelp.va.gov/app/ask).

**Comment by leahkeeler** [comment]
This is live on 1/4 closing ticket
