### ISSUE TITLE
CT Redesign: Draft Prototype

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#16494]
Rough in screens for new UI 
Build screens 
Build interactions, as necessary

**Comment by amyknox** [comment]
@watersemma - after you've reviewed all design intent input, use this story for "comparitor" mobile exploration.

**Comment by watersemma** [comment]
Ideation is tracked collaborative mural board here: https://app.mural.co/invitation/mural/bahdigitalexperience6902/1605879130829?sender=watersemma2223&key=d7bb3c6a-2009-47bc-99cb-b2a024d85822 

Design intent input has been reviewed and is incorporated some
