### ISSUE TITLE
CT Redesign: Features Identification

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#16493]
Identify Feature-level updates to comparison tool 
Prioritize with internal team 
Prioritize with clients

**Comment by amyknox** [comment]
Not prioritizing with clients until after exec briefing

**Comment by JenLJ** [comment]
Features documentation can be found [here](https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/education/_layouts/15/Doc.aspx?sourcedoc=%7BB92D797F-F53D-4E72-81ED-18F70EACEDD9%7D&file=CT%20Redesign%20-%20Features%20Identification.xlsx&action=default&mobileredirect=true&cid=d1a592ab-5988-4485-ad0d-7cb073bb31c7)
