### ISSUE TITLE
alertmanager routing for multiple projects

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#165]
## Description

Our alertmanager config was setup assuming that it'd be used for one project (vets.gov), but has evolved significantly since then. We're now supporting multiple projects in the same set of instances and need to document and implement some tagging strategy to let these co-exist (or launch some discovery if this can't/shouldn't be done this way).

## AC

- [ ] documentation of tagging structure and strategy for projects to co-exist in the same Prometheus instances

**Comment by ricetj** [comment]
We don't how do people get added to PD, how do they set up rotations, and a lot more questions

**Comment by wyattwalter** [comment]
This ticket isn't really "ready" and there's a higher level one here https://github.com/department-of-veterans-affairs/va.gov-team/issues/6770 that covers the larger topic this is a part of. Gonna close this one out and we can break down this project when we get to it.
