### ISSUE TITLE
STEM Automated Decision: Review Email draft content / DEPO	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#16505]
Share content with DEPO for review

**Comment by amyknox** [comment]
@JenLJ 

For the DEPO content review. there currently isn't a dedicated content review template, so use the standard template to create a new issue. You can drop in the email content and any background context there (this is the automatic denial for select STEM applicants) and Peggy will get it in her queue to review.

**Comment by JenLJ** [comment]
Requested review: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/16890
