### ISSUE TITLE
Validated user log-in - Discovery Activity

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#16506]
Get low-down on tech discovery thus far 
Identify all user-facing elements

**Comment by amyknox** [comment]
This story is supposed to be "Validated user log-in: Discovery Activity", not Education Forms.

**Comment by amyknox** [comment]
See SLACK thread for discovery info: https://bah-ssp.slack.com/archives/GH2AHGG7M/p1606940204092100
