### ISSUE TITLE
Make a platform-level function to disable FTUX modals for Cypress tests

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#16507]
In many Cypress tests we have code like this that is used to make sure FTUX (first-time user-experience) modals do no appear:

```
export function mockLocalStorage() {
  // make sure no first-time UX modals are in the way
  window.localStorage.setItem(
    'DISMISSED_ANNOUNCEMENTS',
    JSON.stringify(['single-sign-on-intro', 'find-benefits-intro']),
  );
}
```

We could have a platform-level function, maybe called `disabledFTUXModals()`, that could set the value of `DISMISSED_ANNOUNCEMENTS` to all of the possible modals:

`window.localStorage.setItem('DISMISSED_ANNOUNCEMENTS', '*');`

**Comment by sanlouise** [comment]
@mshea0606 I'm closing out this ticket, it's done on my end and there is nothing for you to verify since the change is not UI-facing.

**Comment by mshea0606** [comment]
Thanks @sanlouise !
