### ISSUE TITLE
STEM Automated Decision: Discovery Efforts

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#16503]
Get the low-down on any Automated Decision discovery points UX needs to support the denial email effort
Work with Education to get copy of other denials

**Comment by amyknox** [comment]
[https://app.zenhub.com/files/133843125/61161b43-d0d5-497e-8ca9-f5b0c1a223c6/download](https://app.zenhub.com/files/133843125/61161b43-d0d5-497e-8ca9-f5b0c1a223c6/download)

**Comment by amyknox** [comment]
Confirmed requirements during 11/30 EDU meeting
Posed question on denial email on DEPO slack... waiting til 12/1 cob to close this

**Comment by amyknox** [comment]
Also, EVSS sync is happening after the application has been submitted so there's no UI on the online application, just need to worry about the email
