### ISSUE TITLE
Research synthesis

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1650]
@goldenmeanie commented on [Wed Apr 03 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17750)

Feedback sessions for homepage and 526 wizard (including assistive devices)

- [x] Collect notes
- [x] Get folks together to talk through feedback sessions
- [x] Generate readout doc

**Comment by smoonpeyes** [comment]
@goldenmeanie Was research synthesis completed?

**Comment by aeltarhoni** [comment]
@smoonpeyes will follow up with Alex Taylor

**Comment by aeltarhoni** [comment]
@goldenmeanie Can you upload the notes to Git?

**Comment by goldenmeanie** [comment]
Sorry about the lag all!

[synthesis uploaded](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability/Disability%20526EZ/research/2019-07-automation/synthesis.md)
