### ISSUE TITLE
STEM Automated Decision: Denial Email draft content

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#16504]
Draft content for STEM denial email

**Comment by amyknox** [comment]
[https://app.zenhub.com/files/133843125/7d246427-8da2-4560-a708-14ad52dbdc1b/download](https://app.zenhub.com/files/133843125/7d246427-8da2-4560-a708-14ad52dbdc1b/download)

**Comment by amyknox** [comment]
@JenLJ - file from Education is attached in the comment above. I reached out in DEPO design to see if anyone had samples of other denial emails... crickets.  I don't think anyone's done this type of work before so look at us... we're leading edge!!  

Let me know if you need more info to get this story rolling.

**Comment by JenLJ** [comment]
Initial draft of denial email on Sharepoint is [here](https://boozallen.sharepoint.com/:w:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/UX%20Assets/Research/STEM-standalone-10203/STEM%20Automated%20Decision%20v1.docx?d=wbe9d3952733645e1a5dff3cfe7cade2e&csf=1&web=1&e=YzUwt2)
