### ISSUE TITLE
[SCREENREADER]: GIBCT® Colmery 107 - Learn more button needs an aria-label for context

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1651]
## Description

The `Learn more` buttons rely on proximity to a label or heading to answer the question "Learn more about what?". This can be improved for assistive devices and screen readers by adding `aria-label` attributes to the buttons. Example screenshots attached.

/cc @peggygannon for Content team guidance as needed

## Point of Contact

**VFS Point of Contact:** _Trevor, Peggy_

## Related Issues
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/1252

## Acceptance Criteria

* As a screen reader user, I want to hear a contextual aria-label read aloud. This text could sound like "Learn more about where you will take the majority of your classes" or "Learn more about locations for taking classes".

## Environment

* Windows 10
* Chrome
* JAWS
* https://staging.va.gov/gi-bill-comparison-tool/profile/11806124
## WCAG or Vendor Guidance (optional)

* [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)
* [Understanding Success Criterion 2.5.3: Label in Name](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html)

## Screenshots or Trace Logs

![Screen Shot 2019-09-09 at 2.25.59 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/b1463e8a-3d2b-4e4d-8403-22de774db495)

**Comment by amyknox** [comment]
@elder-joseph UXers recommend:  Learn more about location-based housing allowance

**Comment by amyknox** [comment]
@peggygannon can you review / approve this content for aria label: 
Learn more about location-based housing allowance

**Comment by peggygannon** [comment]
Hi, @amyknox I recommend a slight tweak (adding "the"): 

Learn more about the location-based housing allowance

**Comment by delli-gatti-michael** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/10729

**Comment by delli-gatti-michael** [comment]
Local testing passes. "Learn more about the location-based housing allowance" is read by voiceover when focused on the Learn More link.

![Screen Shot 2019-09-16 at 8.35.28 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3d2635d6-8171-4675-839f-fe5ed98395fc)

**Comment by 1Copenut** [comment]
[This PR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1640) is working as expected. It has a small redundancy in that screen readers will hear "Learn more" read twice. For future uses of this pattern to create an entirely new label from the previous one for screen readers, we need to add an `aria-hidden="true"` span around the redundant text.

We can also omit the `aria-live` and `aria-atomic` attributes on the parent button. These attributes are not needed for an SR-only label.

```html
<span className="sr-only">
  Learn more about the location-based housing allowance
</span>
<span aria-hidden="true">(Learn more)</span>
```
