### ISSUE TITLE
[Observation session] More clarity on VA location selection page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#16519]
The main issue our test Veteran had with VAOS was when he arrived at the VA location selection page. He assumed that since the app states that "**_Below is a list of VA locations where you're registered that offer Primary care appointments. Locations closest to you are at the top of the list_**." that when he didn't see the Washington, DC facilities that there was an issue with the app.

### What was expected
The Veteran assumed he'd see Washington DC VAMC because that is where he receives care, and wanted an appointment. 

### What actually happened
He was very confused as to how he wouldn't see the DC VAMC in his list to choose from. He became even more confused as to why he was receiving clinics that were 200+ miles away from him. 

### Things we need to research/improve:
- handling the confusion between the list that is shown and the facilities that actually exist in the VA ecosystem
- how might we -  improve clarity on why some facilities are showing and others are not
- How might we - handle experience where the clinics we return are some distance (ex. 100miles) from your home or current location?

**Comment by outerpress** [comment]
@lenaecb @laurenernest : "improve clarity on why some facilities are showing and others are not" - we talked about locations not showing because they have turned off online scheduling. Are there other situations like this, where an expected facility won't show up?

**Comment by laurenernest** [comment]
@outerpress Site registration and online scheduling being on/off for a type of care at that facility are the main factors that would contribute to what could show on the list.

**Comment by outerpress** [comment]
@peggygannon here are the facility page mockups for your review: https://adhoc.invisionapp.com/share/XPZLVDC3JC7

We're going to start by building the V1 version in that mockup so we can collect user data before iterating to V2. This is because V2 has a couple of quirks that might make the comprehension problem worse for users - namely, putting the address/location information under another click, and an odd error state that contains an additional info component (which contains the location functionality). 

But we would like to get your feedback on both versions so we can queue up V2 after V1. 

cc: @rtwell @1Copenut

**Comment by 1Copenut** [comment]
@outerpress Hey! Thank you for the link and explanation. For my part, the tip at the top is the clear winner. It gave me all the conditional information in one place, and let me change to my current location before hunting for a facility. I had a couple of question thoughts, use or discard as you see fit!

1. For the tip at the top, would it a lot of trouble to line up the text that says "Why isn't my facility listed?" on the open and closed states? It moves down and to the left on the open state, which shouldn't be a distraction but draws my eye away from the important information.
1. What do you think about showing all the facilities and doing away with the + Show 7 more facilities link? If we're already rolling up the facilities that don't allow online scheduling, is there a reason not to show users a whole list? Or maybe a round number like 5-10? Thinking out loud.
1. What do you think about adding the home address in the tip expandable content? Maybe as a quick reminder and help veterans decide if that's the right one or if they should switch to the current location. Would make that decision a beat quicker and easier to parse.

**Comment by outerpress** [comment]
@1Copenut Thanks for the feedback!

I added a few more screens to show the different weird states that list can find itself in. The "required" state definitely is a problem I want to iterate on a bit. (Also note, I broke up the two versions into separate projects and updated the comment above to reflect that).

Responses:

1. I'll do a run through later today to fix up spacing issues.

2. That list can get very long, and can show facilities that are way too far away to be useful, since it's everywhere you've registered. I'd prefer to improve ways on making the first couple of results relevant. I don't know if we can say the first 5-10, since you might be in a metro area with a lot of facilities clustered together.

3. Added the home address back into the expandable bit, you're right that is needed.

**Comment by outerpress** [comment]
@peggygannon another note to consider - we should think about communicating in the page instructions that the facility list are only those that offer online scheduling, if that can fit in without blowing it up too much.

**Comment by peggygannon** [comment]
thanks @outerpress I plan to drop in some content recommendations tomorrow!

**Comment by outerpress** [comment]
Sounds great @peggygannon , thanks! One other note, the facilities page and CC provider list are related so we should aim to make the language consistent if possible. "Home address" vs. "address on file" came up as an example in sprint demo today (see screenshot).

![Screen Shot 2020-12-07 at 12.27.59 PM.jpg](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/7b8c58d4-5910-4ff6-86c6-0c2e68848f5d)

**Comment by peggygannon** [comment]
Thanks, @outerpress it's helpful to see these side by side. Can you share the full screen/page for the VA facilities and CC providers, so I can ensure content consistency across the two?

**Comment by outerpress** [comment]
@peggygannon - there are a few states that are similar because of the address vs. location selection functionality:

Home address based:
- [Facilities V1](https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/439374108)
- [CC provider selection](https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/437633276)

Location based: 
- [Facilities V1](https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/439633396)
- [CC provider selection](https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/438121104)

Location blocked:
- [Facilities V1](https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/439633397)
- [CC provider selection](https://adhoc.invisionapp.com/share/BFZED2H362S#/screens/438121105)

**Comment by peggygannon** [comment]
@outerpress Please see below content recommendations for V1. Please let me know if you have any questions. 

A few things to note: 
I'm recommending the "current location" link update so this link can stand alone and is more clear what will happen if user clicks this link

I've tweaked the spinner and browser alert content to be more aligned. I've seen earlier versions of this content in different mockups and iterations, so we need to be sure the messaging about this is same. 


------

V1: Choose a VA location screen updates


**Choose a location**

Select a VA facility for your primary care appointment. The facilities below are based on your home address. 

**Your home address on file**
{address info}
 
{link} Show facilities based on my current location

{additional component link} Why isn’t my facility listed? 

The facilities listed below don’t offer online scheduling. You’ll need to call them directly to schedule your appointment. 


{additional component link} Or, find a different VA location.. QUESTION: where does this link take users? 


Update:  "Please provide a response" validation error > Please choose a facility 

Spinner text update: 
Finding your location. Be sure your browser's location feature is turned on.

{alert} Your bowser can't find your current location. Please make sure your browser's location feature is turned on. If it isn’t enabled, we’ll sort your facilities by your home address that's on file.

**Comment by outerpress** [comment]
Thanks @peggygannon , I'm looking through these now. To answer your Question, the "find a different VA location" link opens the Facility Locator (https://staging.va.gov/find-locations)

**Comment by peggygannon** [comment]
@outerpress 

Here's my suggestions for the additional component content for V2. Can we see this in the mockup? Additional tweak might be needed once we see it on the screen. 

{additional component link} 
Why isn’t my facility listed? 
Facilities listed are based on your home address. You can also sort them by your current location. 

- Your home address on file
{address}

- [Sort facilities based on my current location]

Some facilities don’t offer online scheduling. If your facility isn’t listed, you’ll need to call them directly to schedule your appointment. Or you can [search for a different VA location](/find-locations)

{end additional component content}

**Comment by outerpress** [comment]
I [updated v1](https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/439374106)  @peggygannon , with a couple of notes:

- I kept "your home address on file" at the text level to avoid adding a hierarchy break there, as we chatted about in Slack
- I tried moving the error validation message closer to the facilities list. I'm not sure how much control we have over that positioning, but thought it made more sense there
- The only one I'm not sure about is the two sentence paragraph in the drop down. Is that too much to read? Maybe bullets would be better?

Let me know how it looks to you. I'll start on V2 next.

**Comment by peggygannon** [comment]
@outpress ok, what do you think of this suggestion? 

V1:  {additional component link} Why isn’t my facility listed? 
The facilities listed below don’t offer online scheduling. You can: 
-	Call them directly to schedule your appointment, **or** 
-	[Search for a different VA location](/find-locations/)

**Comment by outerpress** [comment]
@peggygannon I think that looks good! https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/439374108

**Comment by outerpress** [comment]
I took another run at this based on feedback from the design/content sync @peggygannon, breaking out the instructions into a separate header under the list. What do you think? 

![Facilities-Update-v1-2.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/d05c5fdb-e729-4c3c-8893-fd77fed15bba)

**Comment by peggygannon** [comment]
Hi, @outerpress This update looks fine to me.

**Comment by outerpress** [comment]
@laurenernest this should be gtg, at least for V1. I figure we should consider V2 as a separate ticket after we get user feedback on V1.

**Comment by laurenernest** [comment]
@outerpress Great! Do you have the InVision link to the spec that looks like the last screenshot in the comments?

Here's the dev placeholder for v2 #17775

**Comment by outerpress** [comment]
Yep yep, I just added the specs to that ticket @laurenernest

**Comment by laurenernest** [comment]
Additional facility page iterations to be tracked in #17775. Closing ticket.
