### ISSUE TITLE
VSA/Auth Experience - Direct Deposit for Education Benefits - QA Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#16528]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature. Then:
- [x] Add yourself to Assignees
- [x] Fill-out sections below

## Product/Feature summary
\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. 
Also, be sure to include

- [x] [ DD4EDU Product/Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/README.md)
- [x] [DD4EDU Product/Feature Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11537)
- [x] [DD4EDU Product/Feature Design prototypes](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/grid)
- [x] [Existing Direct Deposit "Edit" screens](https://vsateams.invisionapp.com/share/FJW9OGY2B9A#/screens/420471560)
- [x] [Direct Deposit alerts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/error-handling)

## Product-team SMEs
[VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )

**Product Owner:** Samara Strauss
**Product Manager(s):** Matt Shea/Jason Wolf
**Design/Research:** Jim Adams
**Content:**  Peggy Gannon
**IA:** Mikki Northruis
**Front-end:** Erik Hansen
**Back-end:** Lihan Li
**QA:** Tze-chiu Lei

## Proposed use-cases and Staging test-accounts
Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  

Ideally, use [this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md) 

**IMPORTANT**: for authenticated-experiences: Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

[Use Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/product/dd-e-use-cases.md) - based on [spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team/files/5584476/Direct.Deposit_Edu.test.cases.xlsx) provided by Team.

## How to configure this issue
- [x] Product Manager added to Assignees
- [x] Attached to a Milestone: **AE: Sprint 40 (2/27-2/10)**
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team**

## Definition of Done
- [ ] Test Runs completed on Staging
- [ ] QA artifacts delivered

**Comment by tlei123** [comment]
@mshea0606 , I've converted @Samara-Strauss 's use-cases spreadsheet into a [Use Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/product/dd-e-use-cases.md) inside your Product folder.

TestRail test-cases have also been scaffolded.  I'll be creating "TestRail use-case mapping" tickets to satisfy @pjhill 's recommendation for 1:1 mapping 'tween TR test-cases & specific use-cases in the above doc. 

Here are some **follow-up items** for Use-/Test-Cases completion:
- Provide Staging test-accounts for Use Cases B, C, & E.
- Provide Design prototypes for:
  - New DD-Edu section
  - Existing DD edit-screens (if any exist for DD-Comp&Pen]
  - Existing DD alerts (if any exist for DD-Comp&Pen]

Feel free to tag me here for further discussion, or just ping me on Slack.  Thx much!

**Comment by Samara-Strauss** [comment]
> Provide Staging test-accounts for Use Cases B, C, & E.

We're not going to be able to verify staging users until the feature is on staging, unfortunately. We have users that *should* work, but we won't know if they do work until we can actually test things out. I'l definitely have staging users ready for you by the time we're ready to QA.

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 that this ticket exists for when we are ready to formally request QA.

**Comment by tlei123** [comment]
@mshea0606 , I just saw a new **VSP Design System** row w/ **Driect Deposit Component** product in last week's [Platform Collab. Point Tracker update](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/notify/show?ouid=106822717336110668382&urlBuilderDomain=adhocteam.us&rev=6517&fromRev=6510&s=AM5m-fiJiuG-PcY0Bb27mIyHqQ9BsYnp0Q) [scroll to bottom of sheet]...

Is this a new dependency now for our project here?

Pls. let me know.  Thx much!

**Comment by Samara-Strauss** [comment]
Since that's a google doc, I can't view it — can you send a screenshot of what you're seeing or let me know more detail?

**Comment by mshea0606** [comment]
@tzelei , i just talked to Shira Goodman, it will not be a dependency for DD4EDU. I also noticed some information is missing on this tracker. I will send the updates to Shira Goodman to update the tracker. cc @Samara-Strauss

**Comment by tlei123** [comment]
@mshea0606 , please ping me on Slack when you have a Staging Review ticket open.  I'll add the QA artifact links to it...

All QA test-runs now completed.  QA-artifact links are below.

100% Passed; no defects logged.

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/903)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&group_id=402)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/183)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/184)

cc @pjhill @shiragoodman @Samara-Strauss

**Comment by mshea0606** [comment]
Awesome! I'll create the staging review request then tag you in the Auth Exp team channel @tlei123.

**Comment by Samara-Strauss** [comment]
Completed a while ago. Closing.
