### ISSUE TITLE
Discovery: Investigate upgrading to USWDS 2.x

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#16523]
## Background
The VA design system is currently using USWDS 1.x as a base. USWDS is currently on 2.x.

## Discovery goal
Is it worth spending the effort to make the upgrade?

## Questions
- What's the estimated level of effort associated with the upgrade?
- What benefit would we derive from it?
  - What does it do that we don't?
  - What are we re-implementing in the design system that we could lean on 2.x for?

**Comment by caw310** [comment]
Closing. We will write a new ticket to upgrade to USWDS 3
