### ISSUE TITLE
Content audit: Form confirmation pages

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#16527]
## User story
Review confirmation pages for all online forms to ensure consistency in language and content best practices. 

## Acceptance criteria
Review confirmation pages for following forms:

- [ ] EDU 1990
- [ ]  EDU 1990N
- [ ]  EDU 1995
- [ ]  EDU 5490
- [ ]  EDU 5495
- [ ] EDU 10203
- [ ]  EDU VET TEC
- [ ]  Disability
- [ ]  Pension
- [ ]  Health Care
- [ ]  Burial allowance
- [ ] Preneed Burial

**Comment by peggygannon** [comment]
**12/4/2020 update** per depo feedback, this work is on pause.

**Comment by rroueche** [comment]
Hey @peggygannon , I'm sorry for my miscommunication! I think this can still be in the backlog. DEPO hasn't yet determined whether global VA.gov audits should be a part of the platform purview, so while I don't think it should be a _prioritized_ initiative, I think it's fine/good to pick up this work when the priority things are out of the way (i.e. collab cycle reviews, and quarterly initiative work).

**Comment by peggygannon** [comment]
ok, thank you @rroueche for clarifying! I'll reopen and put this in my backlog.

**Comment by shiragoodman** [comment]
@rroueche found this on our backlog. not sure if this still falls under Product Support team bc we're pretty certain Sitewide Content is doing VA.gov audits. Can you please clarify?

**Comment by shiragoodman** [comment]
@bethpottsVADEPO @DanielleThierryUSDSVA FYI - this was a ticket Peggy opened a WHILE ago. Found it on our backlog. See the epic (https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/2231) for reference. I will close out if it's no longer relevant.

**Comment by DanielleThierryUSDSVA** [comment]
Hi and thank you, @shiragoodman. Yes, I think you can close this. We can handle audits and work with design system team. Thanks!
