### ISSUE TITLE
Event start times displayed 5 hours later than expected

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16536]
## What happened?

Outreach hub users have reported an issue with the new time zone data, which is also affecting VAMC events.

The time and time zones appear correctly on event listings page (such as https://www.va.gov/pittsburgh-health-care/events/ and https://www.va.gov/outreach-and-events/events/).  That data matches with the new CMS.

But on event detail pages like https://www.va.gov/pittsburgh-health-care/events/hj-heinz-december-2020-town-hall and https://www.va.gov/outreach-and-events/events/navigating-veterans-benefits-with-the-va/, 

<details>
<summary> the event start time displays as 5 hours later than it should be. </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b06a705f-1709-4dde-a176-3f4814a67bc2)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/83488799-7f1d-471b-a218-f3c164eac85e)

</details>

It could be a UTC conversion problem, since ET is 5 hours after UTC, and the delta looks pretty consistent.

@Kevin Walsh noticed that {% include "src/site/includes/date.drupal.liquid" with fieldDate = node.fieldDate %}
is missing on layouts/event.drupal.liquid 

## Desired behavior
Displayed time should reflect event start time in CMS

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
Investigation log:

1. Tried to reproduce locally. Pulled master and ran `yarn build:content --pull-drupal`. Works fine on my machine. The start times on the events list and event detail pages are identical.

2. Confirmed that the event template (src/site/layouts/event.drupal.liquid) still contains the correct code to assign the date variables:

`{% include "src/site/includes/date.drupal.liquid" %}`

**Comment by mpelzsherman** [comment]
Confirmed that src/site/includes/date.drupal.liquid no longer contains the environment check code.
