### ISSUE TITLE
Request access to Google Analytics and Domo

### ISSUE THREAD

**Issue by kimberlymcm** [department-of-veterans-affairs/va.gov-team#16534]
Google Analytics & Domo access request:

Name(s):
Kimberly McManus (already has GA)
Glennette Clark
Meg Peters (already has GA)
Emily Mann (already has GA)

Email(s):
kimberly.mcmanus@va.gov
glennette.clark@usds.dhs.gov
meg.peters@va.gov
emily.mann1@va.hov

Team: Digital Health Modernization

(Optional) Dashboard:

**Comment by bsmartin-ep** [comment]
@joanneesteban -

We need a DOMO group for the `Digital Health Modernization` team.  Do you want to create the empty group so that you are the owner?

**Comment by bsmartin-ep** [comment]
@kimberlymcm / @emily-mann / @glennettec / @mpeterz -

You should all have GA and DOMO access.  Please check your email for DOMO instructions.

Our COVID response dashboard we discussed yesterday:

https://va-gov.domo.com/page/2077110052

**Comment by bsmartin-ep** [comment]
Access has been granted.  Message me if you have any issues.

Closing.
