### ISSUE TITLE
CT Search for "Texas" doesn't return sufficient relevant results

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#16558]
## What happened?
When searching for "Texas", some schools with Texas in the name aren't coming back. Specifically, there's a Texas A&M in Commerce, TX that doesn't return.

## Behavior observed on:
- Device: PC, iPhone 6s  
- Browser: Chrome, Safari

## Steps to Reproduce
- URL: https://www.va.gov/gi-bill-comparison-tool/
search for: Texas
- URL for search results: https://www.va.gov/gi-bill-comparison-tool/search/?category=school&name=texas&page=1

## Desired behavior
Schools with "Texas" in the name should return in the search results

## Acceptance Criteria
- [ ] Texas A&M in Commerce TX will return in the results.  Other schools with Texas in the name should also return. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/777

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
UX Review 1 of 2: This checks out for me!

**Comment by amyknox** [comment]
UX Review 2 of 2: This checks out for me, too.  Way more results with "Texas" in the name.  Good stuff.

**Comment by delli-gatti-michael** [comment]
Closing this out
