### ISSUE TITLE
[Content] Request | VAOS community care - current location blocked

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16554]
## Background
In the updates to the Community Care provider selection page, users will be allowed to request results based on their current location (default is home address). This page will follow a similar pattern to the Facility selection page v2. When the current location can't be determined due to being blocked by the browser, a blue message box will appear. Frontend development using this copy will be done in #15992

![Screen Shot 2020-11-23 at 4.43.32 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/65d71dab-412d-4c8d-ad06-0f5c501537e7)

---
## Request
- [ ] Copy for the community care message box when location can't be determined

**Comment by peggygannon** [comment]
Hi, @outerpress @laurenernest  Taking a look at this now. Are we wanting to tweak the message for both scenarios/screenshots above?

I didn't realize this message needed to be updated. Is this a request to tightened up the language or  to rework the whole message?

**Comment by laurenernest** [comment]
@peggygannon This is just for what would go in the blue box on the Community Care page. The facility page screenshot is there as an example of what we show in a similar situation elsewhere. We'll use whatever your copy recommendation is for the CC page. It doesn't have to be modified from what's in that screenshot. If you think what's in that CC screenshot works as is, then that's great too!

**Comment by peggygannon** [comment]
@laurenernest ok, thanks. I think we can tighten up the language a bit more. Here's my recommendation for blocked message:  

Your bowser can't find your current location. Please make sure your browser's location feature is turned on.

**Comment by laurenernest** [comment]
Thanks! I've updated our dev ticket.
