### ISSUE TITLE
SEO Audit Request for [Facilities]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16566]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
**What team/project is this work for?** -> Facilities team, Vet Center web presence
    
**What type of analytics support are you looking for?**
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
**What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?**
No specific reference dates - looking for historical key words

## Analytics to Track Down
- [ ] Google search console - key words which drive Veterans to pages for Vet Centers and their services (see suggested words and URLs in the comment section below)
- [ ] Markup recommendations for rich search results based on FAQ structure 
- [ ] Other SEO suggestions to optimize findability
- [ ] Ways to leverage Schema.org

## Which Product Questions are you trying to answer?

As we build new pages to establish a web presence for Vet Centers, we need to solve the lack of awareness about Vet Centers. They are frequently confused with VA Medical centers and although there is an overlap in some services; the setting and manner in delivering these services are unique. Google searches for "Vet Centers" are as likely to surface results for _Veterinarians_ as they are to return Veteran services pages. 
**How can we structure the content on these pages so that Vet Centers are returned in the first few results when Veterans look for a location, help, or the services offered?**
**How can we leverage markup to create rich text results?**

## Other Helpful Questions to think through
**Who is your audience?** Veteran searching for mental help, benefit assistance, or other needs related to their military service
**What are you hoping to find?** 
   - New key words
   - Guidance to inform markup and content structure to make key words findable
   - Understanding of the heading levels which most impact SEO

## Additional Comments

Resources for relevant key words/context
- [Key words on our radar from research and Google trend analysis](https://docs.google.com/spreadsheets/d/1Wh2d6vKhRmNBfPtZCh3GxS7po9xKmIjregef7XfvMOY/edit#gid=1797556819)
- [Schema.org](https://schema.org/docs/meddocs.html)
- [Leyda's entry point user flows in UXPin](https://preview.uxpin.com/603da0b67ccefbbee74fcd8bb77a8fed12baabb5#/pages/134229303/simulate/sitemap?mode=i)
- [Legacy Vet Center page](https://www.vetcenter.va.gov/) and the related [Service page](https://www.vetcenter.va.gov/Vet_Center_Services.asp)
- [Military Sexual Trauma](https://www.mentalhealth.va.gov/mentalhealth/msthome/index.asp)
- [PTSD](https://www.ptsd.va.gov/)

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks, @mmiddaugh ! Is there a date that you needed this by?

**Comment by JasonTheBearded** [comment]
Being discussed with team currently. 
@bmcgrady-ep look at rich text search results for initial discovery, research on schema.org

**Comment by mmiddaugh** [comment]
Thanks for beginning to look into this @JasonTheBearded and @bmcgrady-ep 
Trevor (@1Copenut) is also a good source of info on this. I have notes from a discussion with him [here] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/16069#issuecomment-725706723)

**Comment by bmcgrady-ep** [comment]
### Here are the recommendations from the SEO audit done on Facilities:
**Google Search Console Performance**
Report | Total Clicks | Total Impressions | Average CTR | Report Link
------------ | ------------- | ------------- | ------------- | -------------
7-Day Performance | 489 | 11K | 4.4% | [Report](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fwww.va.gov%2F&hl=en&num_of_days=7&breakdown=query&page=!https%3A%2F%2Fwww.va.gov%2Fpittsburgh-health-care&metrics=CLICKS%2CIMPRESSIONS%2CCTR)
28-Day Performance | 2.85K | 45.1K | 5.4% | [Report](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fwww.va.gov%2F&hl=en&num_of_days=28&breakdown=query&page=!https%3A%2F%2Fwww.va.gov%2Fpittsburgh-health-care&metrics=CLICKS%2CIMPRESSIONS%2CCTR)
28-Day Performance | 13.4K | 303K | 4.4% | [Report](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fwww.va.gov%2F&hl=en&breakdown=query&page=!https%3A%2F%2Fwww.va.gov%2Fpittsburgh-health-care&num_of_months=6&metrics=CLICKS%2CIMPRESSIONS%2CCTR)
28-Day Performance | 27.5K | 654K | 4.2% | [Report](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fwww.va.gov%2F&hl=en&breakdown=query&page=!https%3A%2F%2Fwww.va.gov%2Fpittsburgh-health-care&num_of_months=12&metrics=CLICKS%2CIMPRESSIONS%2CCTR)

**Schema.org Recommendation**
By not having a schema on the facility pages, SEO is not performing as well as it could be performing. There are two main options for incorporating schema.org onto the pages. First, it can be included in the HTML markup as it is on [this](https://www.va.gov/disability/how-to-file-claim/) VA page. The second option is to encode as JSON-LD in a HTML script tag. This example is at the bottom of [this page](https://schema.org/Hospital).

Here are a couple of useful links for testing your SEO performance:

- [Rich Results](https://search.google.com/test/rich-results)
- [Structured Data](https://search.google.com/structured-data/testing-tool) 
- [Markup Helper](https://www.google.com/webmasters/markup-helper/)
- [Search Console Guides](https://developers.google.com/search/docs/guides/search-gallery) - I would recommend starting with Local Business and Events here.

[Here](https://schema.org/docs/full.html) is a link to a full list of different schema.org types. Hospital is the main schema type I would recommend for the locations. [Here](https://www.emagine.com/healthcare-schema-markup-seo/) is one last resource related to the Healthcare schema markup.

**Comment by mmiddaugh** [comment]
Thank you @bmcgrady-ep!
@davidconlon for visibility

**Comment by bmcgrady-ep** [comment]
@mmiddaugh - I'm closing out this issue, but please feel free to reopen if you have any additional questions.
