### ISSUE TITLE
Table Caption Update/Fix

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#16562]
## Issue Description
_Dynamic functionality: If no H2 section header make the table caption headers display as H3 but us H2.  Needs to use an H2 tag but be styled as an H3 display.._

Read background details from Slack Thread [Here](https://dsva.slack.com/archives/C52CL1PKQ/p1606235990424300) `<--In the RS, TOC links are generated by H2s. Workaround that was used: Randi used the optional H2 section header fields. `

Relevant loc to make this work is [Here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/add-id-to-subheadings.js#L67)

Task:

Dynamic functionality: If no H2 section header make the table caption headers display as H3 but us H2.  Needs to use an H2 tag but be styled as an H3 display. 

## Front end tasks
- Please provide estimate on work. 
- Once estimated please remove the 'needs grooming' label
- Implement based on recommendation . 
- Once validate, close out ticket.

**Comment by jenniferlee-dsva** [comment]
Just adding note: Is this a real problem? 

It seems like the issue was how to include TOC links to tables, and the workaround of using the optional H2 section heading fields worked. If this is insufficient or creates undesired problems, what are they?  

Let's make sure this is an actual problem before 'fixing' it.

**Comment by brianalloyd** [comment]
Needs more discovery, will review in future planning/grooming sessions.

**Comment by brianalloyd** [comment]
Reviewed in grooming and ticket has relevancy and will need to discuss with CMS and validate path forward.

**Comment by brianalloyd** [comment]
Validated that this is not a relevant issue as some improvements have been done that bridges the gap suggested in this ticket.  Closing in support.
