### ISSUE TITLE
Update copy in Profile's generic error message

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#16572]
The Profile gets data from many different sources. If there is an issue with one of those data sources, we show a generic error message at the top of every page/section in the Profile. Currently the error has this bit of text:

`We can’t display all the information on this page`

That's not technically accurate since the info on the _current_ page _might_ be fine. The info might be missing on a different page of your profile. A more accurate message would be:

`We can’t display all the information in your profile`

Thoughts, @peggygannon @tressaellen @callen2563?

![Screen Shot 2020-11-24 at 11.33.34 AM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/a3b56653-eb41-41f7-819a-d7c482298a1f)

cc @sanlouise for your awareness

**Comment by tressaellen** [comment]
@erikphansen I think this is a great idea to update this. So if we update it to this then it would read:

**We can’t load all the information in your profile**

We're sorry.  Something went wrong on our end.  We can't display all the information in your profile.  Please refresh the page or try again later.

@peggygannon do you have thoughts?

**Comment by peggygannon** [comment]
@tressaellen @erikphansen Looks good to me. thank you!

**Comment by erikphansen** [comment]
Ooops, closed in error. The PR is still waiting to merge.
