### ISSUE TITLE
[CONSIDER] Facility health service: "Telehealth available"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16584]
## Issue description
It may be useful to display if a given facility health service is available via telehealth (in addition to online scheduling, walk-in availability and referral requirements. This issue to consider adding that data to API and to some/all facility health services.

**Comment by davidmpickett** [comment]
Forthcoming changes to the Service Location paragraph type will add Virtual Service Modalities (aka Telehealth) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13128
