### ISSUE TITLE
Accessibility feedback for Project Kickoff – Authenticated Experience [Preferred VA Facility]

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#16589]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

VSA: Jennifer
VSP: Trevor

## Details

At this time, based on the information in the product outline, feedback is limited to the item noted for consideration below. 

### Consider

1. Along with "Select your preferred VA Medical Center…" consider letting the user know they may select more than one. I see that the checkboxes signal that, but for those who do not work in UI design it is helpful to not make folk think.

![Screen Shot 2020-11-30 at 10 30 03 AM](https://user-images.githubusercontent.com/57469/100629450-4cb25a80-32f7-11eb-9159-5b1e92234bae.png)

**Comment by 1Copenut** [comment]
Looks good @jenstrickland. Feedback isn't a requirement at kickoff but always welcome. This is a good point to surface before design starts.
