### ISSUE TITLE
STEM: SCO Contact / Applicant Alert - EDU Review

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#16597]
Review applicant alert approach w EDU

- additional stories may be required based on input

**Comment by amyknox** [comment]
Reviewed initial approach with Education Service on 11/30. Back to the drawing board to refine with email and possible with-in form alert.

**Comment by amyknox** [comment]
@watersemma - this is the updated alert content from DEPO. 

{ Alert }
We’ll be reaching out to the School Certifying Official (SCO) at this school to confirm your eligibility for the scholarship.
{ /Alert }

If you have time to drop this into the Program details page before the EDU meeting on Thursday, we can review it there. Otherwise, we can shoot for Monday.

**Comment by watersemma** [comment]
![stem-3-school-details copy 4-B Copy.png](https://images.zenhubusercontent.com/5f7e1db6d6b9a95b02babbae/e97a66da-b04c-4a5c-aef3-e4668a1fdb22)

Invision link: https://bahdigital.invisionapp.com/share/SXIAFSCMC2A
can be found in STEM Form 10203 v0.7-desktop

**Comment by amyknox** [comment]
As of 12/14 - Education is "actively reviewing provided language"
