### ISSUE TITLE
Decision Review forms being submitted using Claim Status Tool 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1659]
## High Level User Story
As a Veteran, I need submit my Decision Review forms using the appropriate process so I can ensure my forms are received and reviewed accordingly.

## Goals
_The user should be prompted to complete their Decision Review forms (Higher Level Review and Supplemental Review) using the dedicated process._ 

_Using the Claim Status tool to submit these forms creates a problem because the forms get stored in the eFolder, sans an EP code for tracking, without notifying anyone of their existence and therefore could go unnoticed indefinitely. This issue was identified during a conversation with RVSR (rater inside VA)._ 

## Issues to create within this Epic

```
- Meet with Andrea to understand issue fully & determine scope
- Create research plan
- Recruit for research sessions/Schedule research sessions
- Create conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
```

**Comment by aeltarhoni** [comment]
User stories will be created after meeting with Andrea. @YanaRoy
