### ISSUE TITLE
Create "Wizard" for Collaboration Cycle

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#16607]
## Details
Currently almost all meetings are synchronous and are a one size fits all. We would like to create a wizard of questions for the collaboration cycle to help it be more scalable and get rid of unnecessary touch points within the cycle. This could also help alleviate some paint points.

We have done previous work with the [Ideation Workshop](https://docs.google.com/spreadsheets/d/1T9AzrVGtx-A3HAoIIdThaJ1qIw2dd-Nyqp6ST-JtCIw/edit#gid=2042344382), [ team 1 prototyping](https://docs.google.com/document/d/1Pmsgn6UQr3KPkDOvboOmTU_f-VkO_ASFlpS95UyTrGs/edit#heading=h.69q5mmm56bi1) and [team 2 prototyping](https://docs.google.com/document/d/1EyvkHSIZLOICStn-trJzZVp-KC5CztOji_PJrKYFwsU/edit#heading=h.abie0bv44eqi) 

## Acceptance criteria

- [x] Meet with practice areas to review the collab cycle check list and determine what is applicable to the wizard
- [x] Each practice area decide what questions area applicable for each collab cycle touchpoint
- [x] Each practice are to determine if the questions make a touchpoint synchronous, asynchronous or unnecessary
- [ ] Create a form (probably Google docs) with a list of questions

## User stories
As a Collab Cycle team member, I want to know early information about a VFS team, so I can deduce what help they may need in meeting DEPO Standards, and establish a customized Collab Cycle path to make their experience as quick and smooth as possible.

As a VFS product manager, I want to share what I know without having to do too much hunting, so I don't give up or get too distracted from my own work.

As a VFS product manager, I want to understand how the platform is helping me, so I can trust in the process and be an active (not reticent) participant.

As a member of DEPO, I want VFS teams to be have answers to the appropriate questions at this early stage (which also means not having answers to certain questions), to foster a culture of iteration and user-generated (not business-generated) requirements.

**Comment by shiragoodman** [comment]
@allison0034 can you add the user stories to this work?

**Comment by shiragoodman** [comment]
I also think we should add this User Story: As a VFS Product Manager, I want to know what are the necessary requirements for a VFS team to undergo a Collaboration Cycle touchpoint so that I can better prepare/plan for my team.
