### ISSUE TITLE
Vets-api Instances Disk Space Fills Quickly due to StatsD Exporter Log Filling Up

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#16605]
## The Problem
When the vets-api-server instances run too long (such as over a long weekend), the instances come close to running out of disk space. Specifically, the statsd exporter logs seem to be taking up the lions share of the disk space.

## Extra Context
None.

### Work to be Done
- [ ] Change the statsd exporter log-level to something other than `DEBUG`

**Comment by jbritt1** [comment]
I would tack on reverting [this change](https://github.com/department-of-veterans-affairs/devops/pull/8012) as part of this work as well as the larger root volume will no longer be as necessary once this solution is implemented.

**Comment by omgitsbillryan** [comment]
I would like to verify that changing the statsd_exporter log level back to `info` fixes our disk usage problem before reverting back to 8 GB ebs volume size. [This is the best graph I could come up with](http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.range_input=2w&g0.expr=sum(node_filesystem_free%7Bdeployment_name%3D%22vets-api-server%22%2C%20env%3D%22prod%22%2C%20device%3D%22%2Fdev%2Fnvme0n1p1%22%7D)%20by%20(instance)&g0.tab=0) that charts the free space of each `prod` vets-api instance.

Once today's deploy goes out, we can use the chart ☝️ to try and compare the rates at which free disk space gets eaten up. This will give us more confidence to put the disk size back to 8gb.

**Comment by omgitsbillryan** [comment]
Can you spot the difference? 😉 
![image](https://user-images.githubusercontent.com/3077884/100775027-b5213a80-33d0-11eb-9a08-7053bc023f64.png)
