### ISSUE TITLE
VAOS Contact center Issue Documentation

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#16612]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
The VAOS team is tracking this issue on their board [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16414). I created this issue for us to track separately but did tag @starlow00 so he would know who to reach out to if he had additional questions.

**Comment by starlow00** [comment]
@Kimberley2019 I think the first version in this document that I attached to the other VAOS ticket (#16647) might be what they're looking for here. Am I in the ballpark? [https://app.zenhub.com/files/133843125/34126eba-d7c9-438d-a1d7-0ebc86cfa34c/download](https://app.zenhub.com/files/133843125/34126eba-d7c9-438d-a1d7-0ebc86cfa34c/download)

**Comment by laurenernest** [comment]
@starlow00 That doc doesn't look like it's for VAOS. It looks like it's for using the Facility Locator tool which is part of a different product. Let me know if there's another doc I should be referencing instead, or happy to hop on a call to discuss further if it helps.

**Comment by starlow00** [comment]
@laurenernest Ok. Thank you, sorry for the confusion! I'm going back through a number of tickets and will be in contact soon.

**Comment by starlow00** [comment]
@Kimberley2019 @laurenernest Based on the issue as I understand it at https://github.com/department-of-veterans-affairs/va.gov-team/issues/16414, the attached may address the CC rep training desired. Please let me know if anything else is needed. Thank you![https://app.zenhub.com/files/133843125/9a25c8d0-29cd-4413-98c4-ae6821dd4ddb/download](https://app.zenhub.com/files/133843125/9a25c8d0-29cd-4413-98c4-ae6821dd4ddb/download)

**Comment by Kimberley2019** [comment]
@laurenernest are you able to provide us with the training that you held with HRC back in April or May?  From reading as little more, is the issue that the MHV profile doesn't transfer/translate over to VA.gov?

**Comment by laurenernest** [comment]
@starlow00 Could you re-upload that file? I'm getting an error when trying to open it.

@Kimberley2019 I'll set up time for us to chat.

**Comment by starlow00** [comment]
Hi @laurenernest. Here's a re-upload:
[16414 VAOS MHV CC Document_ST_121020.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5690777/16414.VAOS.MHV.CC.Document_ST_121020.docx)

**Comment by laurenernest** [comment]
Here are the scripts sent to us. I hope that helps!

[VAOS.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5697900/VAOS.docx)
[Scheduling Manager.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5697902/Scheduling.Manager.docx)
[MHV Appointments.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5697903/MHV.Appointments.docx)

**Comment by starlow00** [comment]
Here's an updated draft. Please advise if this isn't the ticket we want this attached to. Thanks!

[https://app.zenhub.com/files/133843125/a8dedd3c-e3aa-4e09-8e94-56ea1d69bf46/download](https://app.zenhub.com/files/133843125/a8dedd3c-e3aa-4e09-8e94-56ea1d69bf46/download)

**Comment by jwoodman5** [comment]
@laurenernest Hi there - I am going back through some of our open tickets and I am curious if you need anything further here? Please take a look at the latest upload and let us know if that is what you need. Thanks.

**Comment by laurenernest** [comment]
@starlow00 Is the document in your [latest comment ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16612#issuecomment-747020865)new? Do you have any edits to the VAOS and MHV Appointments scripts? Those are the two that are related to the veteran-facing apps. Scheduling Manager is an internal app so not a focus in this use case.

**Comment by starlow00** [comment]
Hi @laurenernest I have attached my edits for VAOS and MHV scripts. Sorry for the mixup! Note on both documents that URL links appear to be wrong.
[MHV.Appointments_ST_122420.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5740582/MHV.Appointments_ST_122420.docx)
[VAOS_ST_122420.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5740583/VAOS_ST_122420.docx)

**Comment by laurenernest** [comment]
What are your thoughts on moving all the steps happening in VAOS from the MHV vet doc to the VAOS doc, so that it doesn't look like it's one workflow in MHV? Then the MHV doc only has steps and notes related to that site.

I'll double check the links on the network.

**Comment by starlow00** [comment]
@laurenernest , I've attached the latest here. Is this what you're referring to? For ease of location, the new table inserted into the VAOS doc has a blue background.
[VAOS_ST_123020.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5755487/VAOS_ST_123020.docx)
[MHV.Appointments_ST_123020.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5755488/MHV.Appointments_ST_123020.docx)

**Comment by starlow00** [comment]
Hi @laurenernest Following up on this, as @jwoodman5 and team would like to move some product guides forward if possible. Did the most recent edits work for your team?

**Comment by laurenernest** [comment]
Added comments. I can't speak much to the MHV vet side, but these separation of steps makes more sense from the user experience. Will your team be coordinating with the Help Desk to review and implement the changes?
[VAOS_ST_123020 (LE Edits).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5783122/VAOS_ST_123020.LE.Edits.docx)
[MHV.Appointments_ST_123020 (LE Edits).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5783123/MHV.Appointments_ST_123020.LE.Edits.docx)

**Comment by starlow00** [comment]
Hi @laurenernest. Thank you for looking those over. I will clean these up and apply your edits. As for further coordination, I'm going to bring @jwoodman5 in on this.

**Comment by starlow00** [comment]
@clantosswett , attached here are guides for both MHV and VAOS. Lauren raises one question for the Help Desk that needs to be addressed on the MHV document, marked on the Word doc. VAOS should be good to go in PDF form. Questions, please let us know. Thanks! (cc @jwoodman5)

[https://app.zenhub.com/files/133843125/f4bd3bf3-e95a-40dd-98ca-9548edbed0d3/download](https://app.zenhub.com/files/133843125/f4bd3bf3-e95a-40dd-98ca-9548edbed0d3/download)[https://app.zenhub.com/files/133843125/b5f91e65-d9cf-4f9e-ae81-7e6cbc69febd/download](https://app.zenhub.com/files/133843125/b5f91e65-d9cf-4f9e-ae81-7e6cbc69febd/download)

**Comment by Kimberley2019** [comment]
Closing ticket.  Documentation is in comment above.
