### ISSUE TITLE
[SPIKE] Initial investigation to answering Product <> Endpoint Mapping

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#16614]
## Description

We need to think about how we can solve the question of "how do we use the data we have, in the systems we have, to visualize products performance based on downstream availability".

We have a Products to Backend service mapping found in Grafana that uses a header value.  But with the addition of DataDog to the platform toolset, how we can leverage this to solve this problem.   What other options do we have?

## Sample Use Cases
As a VFS team member (or maybe the Contact Center Team?) I want to easily see a system status showing what systems are down and what VA.gov products are impacted in realtime, so I can take action to best prepare call centers and other entities to communicate appropriately with users.
As a VA Lead I want to be able to look at a report about a VA.gov product and know how often that product has been down over the past month, and what services caused the outages, so I can decide on the top priority back-end services to re-platform/re-architect.

## Acceptance Criteria
- [ ] Options for possible solutions are documented

**Comment by f1337** [comment]
Could we do a quick and dirty grep for `api.va.gov` for starters?

And/or ask VFS teams what endpoints they use?
