### ISSUE TITLE
Make Prometheus Alerts More Readable in Slack

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#16629]
## The Problem
The AlertManager alerts in the #devops-alerts are messy. Specifically they contain,

- broken links
- duplicated information
- unformatted links that are long and clutter up the messaging

Example:
![image](https://user-images.githubusercontent.com/3077884/100275876-9f25fc80-2f2e-11eb-89cd-5be2d0cae752.png)

## Extra Context
[This blog post](https://grafana.com/blog/2020/02/25/step-by-step-guide-to-setting-up-prometheus-alertmanager-with-slack-pagerduty-and-gmail/) has a nice example for a more readable alert, e.g.

![image](https://user-images.githubusercontent.com/3077884/100277126-a0582900-2f30-11eb-8eec-7e51bae6a1a6.png)

## Work to be Done
- [x] Clean up our alerts to make them more readable

**Comment by omgitsbillryan** [comment]
I'm gonna call this one done. I only changed the `devops-noncritical` prometheus receiver. I think 90+ % of alerts come through this receiver. It's still possible however, for alerts to reach the `#devops-alerts` slack channel through the `devops-critical` & `prometheus` receiver. It would be a nice-to-have to [_templatize_ ](https://prometheus.io/docs/alerting/latest/notification_examples/)what was done to the `devops-noncritical` receiver. This way the template could be easily re-use.

**Comment by jbritt1** [comment]
Great job on this work Bill!
