### ISSUE TITLE
10203: Update Print Preview

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16620]
As a developer, I need to update the STEM 10203 print preview so that it is consistent with the format of other submission print previews.

## Assumptions:
1. This update does not require a feature or prod flag; story will be merged at the beginning of the day for staging review prior to afternoon production deployment.

## Acceptance Criteria
1. On the submission confirmation page:
    a. The following link is included in the `What happens after I apply?` section of the print preview: [Learn more about what happens after you apply](https://staging.va.gov/education/after-you-apply/)

## Supporting Artifacts:
1. Current Print Preview: [10203.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5631311/10203_Print_Preview.pdf)
2. Print Preview with Link: [1995_Print_Preview.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5598710/1995_Example.pdf)

**Comment by ksantiagomorgan6** [comment]
Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/15215

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-12-08 at 10.02.37 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6abd2879-5db6-475b-8963-2a0f9c18ef4c)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/24327&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by ksantiagomorgan6** [comment]
The changes made in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/16838 currently in master, satisfy the AC for this story.

**Comment by sonntag-adam** [comment]
Testing passes QA
