### ISSUE TITLE
General Analytics Request for Caregivers

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16627]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
VSA Caregivers

Ming & Alayna

[Slack request link](https://dsva.slack.com/archives/CMJ2V70UV/p1605635829391300)

_Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What type of analytics support are you looking for?
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

## Analytics to Track Down
Caregivers CSAT vs. other VA.gov forms over time

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Created [a chart](https://va-gov.domo.com/page/-100000/kpis/details/496995178) for avg. Caregiver CSAT vs. avg. other VA.gov CSAT week over week.

@amycesal help please! I don't think this captures the entirety of the story, and this is for the current CSAT chart on their dashboard as well. If you take a look at the total scores, the last couple weeks only had a couple of Caregiver survey responses. When you compare that to the average of the other survey responses (week over week has been over 100 responses), it looks great but doesn't have a large enough sample size. 

Compared averages
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/7c0edd6d-ee29-46f4-9a12-75722b777b41)

Compared totals
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/1c250fd6-7074-4bda-974f-00f1059859b1)

Is there a way to show both the averages and the totals (that's readable)? 

I'm thinking a `Variance Line Bar` but that would use two different scales and wouldn't be readable since the scales are too different. Not to mention having two different scales is really difficult for readability in general...

**Comment by joanneesteban** [comment]
Ok, I answered my question for showing the totals on a single series, which fixes the current chart:
![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/1532559f-78cb-4644-b24c-760441fee5c0)

But that option (`Chart Properties` -> `Data Label Settings` -> `Show Total Label`) doesn't exist on the multiple series chart properties.

**Comment by amycesal** [comment]
You could also show a bar chart for each day with the total number of submissions with each score, and have a line chart with the average score. But that's way more complex and involves some beast mode calculations.

**Comment by joanneesteban** [comment]
@bmcgrady-ep is continuing this work in https://github.com/department-of-veterans-affairs/va.gov-team/issues/11477. Closing this issue.
