### ISSUE TITLE
User Survey Request for Search & Discovery - Medallia Pilot

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16625]
# Request the Medallia Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/medallia-request-survey.md)

## Description
Public Websites - Search Results

### Launch Date
*Please provide the launch or rollout date.*

### Staging URLs
staging.va.gov/search/?page=1&query

### Production URLs
https://www.va.gov/search/?page=1&query

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by joanneesteban** [comment]
Note: will prioritize this survey addition as the Medallia goes to Production.

**Comment by joanneesteban** [comment]
Moving this over to the VSP Contact Center team.

**Comment by joanneesteban** [comment]
Slack conversation: https://dsva.slack.com/archives/CBU0KDSB1/p1605548855135400

**Comment by mgleo** [comment]
@joanneesteban once Medallia is up and running how do we view the analytics? cc @johnhashva

**Comment by denisecoveyduc** [comment]
Hi @jwoodman5 We just wanted to follow up on this to see if you can provide is with a rough timeline of when we can expect this?  Once it is up and running how can we view the analytics? Thanks. 
cc: @mgleo

**Comment by jwoodman5** [comment]
Hi @denisecoveyduc We launched our first Medallia pilot last week and plan to roll two additional survey pilots out this week. If all goes well, we should see a full production release early in Q2. Once that happens and our data pipeline is flowing, we will be providing reporting through DOMO. If there are specific data sets or reports you are interested in, we'd like to know. Thanks.

**Comment by denisecoveyduc** [comment]
Hi @jwoodman5  Wondering if we can sync up on next steps to implement the feedback survey for the search results page?  

We anticipate that for this survey the following questions will appear on one screen on the results page:
- Did you find what you were looking for today? [‘yes’ or ‘no’]
- What were you unable to find during your visit today? [text area]
- What is your overall satisfaction with this site? [‘Very Dissatisfied’ through ’Very Satisfied”]

Happy to meet to discuss further if needed. Let us know. Thanks!

**Comment by jwoodman5** [comment]
Hi @denisecoveyduc - we are wrapping our migration effort (from ForeSee to standard Medallia Feedback surveys) early next week and will be open to discuss custom implementation such as yours late next week or the week after. I will reach out on Slack about meeting times. Thanks.

**Comment by jwoodman5** [comment]
@denisecoveyduc and @mgleo Thanks again for the conversation yesterday. I was able to confirm the questions you want for your survey are on the PRA approved list, so this should be pretty straight forward. I'll keep you apprised on timing. Have a nice weekend.

**Comment by jwoodman5** [comment]
Provided Medallia folks with staging implementation details and asked for ETA. Will comment here when that and any other information is available.

**Comment by denisecoveyduc** [comment]
hi @jwoodman5 Just wondering if Medallia has responded or if you have any updates for us?

**Comment by jwoodman5** [comment]
Hi @denisecoveyduc, I have had some back and forth with them and only have a partial timeline so far. The work will take them 2-3 weeks once started, but they haven't committed to a start date. As I mentioned, our main Medallia contact is out until next week and I anticipate things moving faster when he's back. We will stay in touch on it. Thanks.

**Comment by denisecoveyduc** [comment]
@jwoodman5 Sounds great! Exactly the update I was hoping for. Thanks for continuing to progress this for us! Look forward to the next update.

**Comment by jwoodman5** [comment]
Hi @denisecoveyduc - We are live on staging. I checked it out and all looks good, but please do the same and let us know if you agree. Once we have the green light, we can push to production! Thanks.

**Comment by denisecoveyduc** [comment]
Hi @jwoodman5 The team and I had a look and agree with you - it looks great! Ready to push to production! Can't wait to start receiving some results. I assume we may have some feedback to review around the end of June? If that makes sense to you I will reach out then for a report. Thanks for your help!

**Comment by jwoodman5** [comment]
Hey @denisecoveyduc Great! And yes, end of June/start of July would be good timing. Just holler and we'll get you setup. I'll confirm once live in prod.

**Comment by jwoodman5** [comment]
@denisecoveyduc Your survey is now live on production. Please let me know if you have any questions or concerns! Thanks for working with us on this.
