### ISSUE TITLE
Create "ignore" list of words for RS search

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#16626]
This is a [follow on to ticket #15650 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15650)

Currently when you search for a phrase like **'file for pension'** or **'change of address'** in the RS search, the results bring back any article that has each of the words in the title. So any article that has the word "of" / "for" even ones that do not have the relevant keywords like "pension" / "address."

We want to eliminate some of the irrelevant noise in search by omitting certain words that don't provide relevance as standalone search terms. 

**Ignore list of words for RS search:** 

1. "of"
2. "the"
3. "a"
4. "an"
5. "as"
6. "at"
7. "and"
8. "or"
9. "but"
10. "for"
11. "from"
12. "to"
13. "in"
14. "on"
15. "by"
16. "with"
17. "so"
18. "yet"

**Comment by kelsonic** [comment]
Picking up this ticket! 🙂

**Comment by kelsonic** [comment]
PR merged, ready for validation following tomorrow's daily deploy! 🎉

**Comment by jenniferlee-dsva** [comment]
taking a look... oh: where can I go to see the new logic in action?  demo? staging?

**Comment by jenniferlee-dsva** [comment]
well - i think this is live bc i used the live site to test it. 

BEFORE - when i searched on "apply for pension" I received any articles (4)  with the word "for" , "apply", or "pension." 
https://user-images.githubusercontent.com/1915775/98741178-2e9dae00-237a-11eb-8bde-e8346f9947ad.png

NOW - when i do the same search, I only receive 1 relevant article which has the word "pension." This is certainly an improvement! 
![image](https://user-images.githubusercontent.com/43381063/101082557-a3c76200-3579-11eb-9390-bd3a04afcc51.png)

Thank you @kelsonic . I'm going to keep checking, to make sure that no weird unintended behavior is happening, but this simple change should really help reduce irrelevant white noise.
