### ISSUE TITLE
Discovery: Workarounds for system outages

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1663]
@markgreenburg commented on [Fri Apr 26 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18219)

## Story
As a veteran, I want to know that my application will be submitted if I press the 'submit' button so that I don't have to come back to my saved application later and try to resubmit.

## Context
Our overall app error rates are ~10% of all unique submissions, however, only about 2.5% of total submissions fail for reasons we can do something about. This means that about 75% of all errors we encounter are due to system outages upstream of vets-api. Since a majority of these could be solved by re-trying an application at a later time, we may want to think about a better path for veterans than letting their submission fail. Some rough ideas:
- Queue a job when we get an upstream dependency error, retry every ~x hours
- Don't let the veteran submit when we know they will receive an upstream error, show some message instead
- Distinguish between validation & upstream errors so that veterans know whether they should retry later or whether they need to call in / edit their info.
- ...Other ideas go here

## AC
- [ ] Write-up of ways we think we could work around or mitigate the upstream dependency issues we're encountering with BGS & VBMS

---

@cvalarida commented on [Tue Jun 04 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18219#issuecomment-498874048)

I'm a fan of queuing the job, myself. It'll minimize the impact on UX, and won't require the user to come back and do what we could be doing for them.

One additional thought: If it's possible, I think we should submit the data to EVSS' validation endpoint before adding it to the queue. I'm not sure if their validation endpoint will be up if their dependencies are down, though.

**Comment by aeltarhoni** [comment]
@ndsprinkle will look at the possibility.

**Comment by YanaRoy** [comment]
@AZSchneider Is this something we should move forward on?

**Comment by AZSchneider** [comment]
@YanaRoy It would be helpful to the veteran to be able to communicate what's happening and to be able to queue a submission. Yes, let's try to dig in to what options might exist

**Comment by luke-gcio** [comment]
OBE - we have retries to cover this now.
