### ISSUE TITLE
Personal Information - Voice Control / Voice access issues

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#16634]
## What happened?
1. Android:  The links on the Personal Information page "How do I update my personal information" and "How will you use my contact information" are not accessible with Voice Access.  There is no number next to them to identify them as things to tap.

2. iOS:  When I speak the command "Tap Home", because I want to update my home phone number, I'm sent to the Home page instead.  The reason is there are two "Home" elements on the page.  It seems that the navigation "Home" is taking precedence over the "Home" phone number element.  I'm unable to update my home phone number using voice commands.  Need to have some way of defining the difference between "Home" phone and "Home" page.

## Specs:
- Devices: Android: Galaxy Note 9 (latest version); iOS:  iPhone SE (latest version) 

## Steps to Reproduce
1.
- Navigate with Voice access enabled on Android to Personal Information page.
- Observe the numbers next to all the elements on the page.
- Notice the two hyperlinks ("How do I update my personal information" and "How will you use my contact information") are skipped; no numbers.

2.
- Navigate with Voice Control enabled to the Personal Information page.
- Speak "Tap Home".
- Notice that you will be sent to the VA Mobile home page rather than editing your home phone number.

## Desired behavior
1. User is able to voice access the two hyperlinks.

2. User is able to voice command editing of Home phone number.

## Acceptance Criteria
1. User is able to voice access the two hyperlinks.

2. User is able to voice command editing of Home phone number.

## Bug Severity
- 3 - Moderate

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13891

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13890

## Screen shot(s) and additional information

![personalInformationVoice1.jpg](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/c221269d-51d8-45a8-ba52-c6d1bafb2878)

**Comment by komaly15** [comment]
Number 2 of issues will be resolved once this story is completed: https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19189

**Comment by digitalken** [comment]
2/1/2021 - @komaly15 I'm seeing a number now for the "How do I..." link but on two of the Androids, it is showing the zip code of the address instead of just a regular number.  One is the Note 9 that I took the original screen shot above with.  Now it is behaving differently after the fix.  I'm going to send this tag back to you to have a look.  Also, notice there are two numbers pointing to the same part of the screen where the "How do I..." link is now.  They both work, but I think that's odd.  Have a look.  I'm moving it back to in progress.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/81589660-770c-4106-96da-d50e8bfbe624)

**Comment by digitalken** [comment]
PASS 2/22/2021 - Showing the correct amount of numbers (for voice control).  closing.
