### ISSUE TITLE
[Bug] VAMC Facility health services Contact information - Addresses double-spaced

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#16635]
## What happened?
On Staging **Pittsburg VA Medical Center - University Drive** page, under **Health serviced offered here**, all expanded service-specific sections' addresses are double-spaced.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [unauthenticated]

## Steps to Reproduce
1. Go to https://staging.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
2. Scroll down to **Health services offered here** section.
3. Click to expand each service-specific accordion-section, and observe that each address is double-spaced.

**Screenshot**
[1 example here -- all addresses in all accordion-sections have this styling anomaly]
![contact-info-bug-styling-address](https://user-images.githubusercontent.com/587583/100291683-ac95b380-2f3b-11eb-88b8-5205379d6e21.png)

## Desired styling
All addresses should be single-spaced.

## Acceptance Criteria
- [ ] [See **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
This can be fixed by changing the markup from using <p> to <span>, and by eliminating the empty elements.
 
![VA_Pittsburgh_Health_Care___Pittsburgh_VA_Medical_Center-University_Dr](https://user-images.githubusercontent.com/80267/100295647-1fad2300-2f58-11eb-9e0e-2fb94e7e6af6.png)

**Comment by mmiddaugh** [comment]
This will be resolved by https://github.com/department-of-veterans-affairs/va.gov-team/issues/17755
