### ISSUE TITLE
10-10EZ (HCA): ICN in the request does not exist in VA MPI

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#16648]
Steps to reproduce:
1. Login to va.gov
1. Navigate to 1010EZ / HCA: https://www.va.gov/health-care/how-to-apply/
1. Fill out and submit form

Outcome:
1. ICN does not exist in production MVI
1. Unclear how ICN is coming from authenticated flow post to ESR

**Comment by LinnJS** [comment]
[vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15511)

[vets-json-schema PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/559)

**Comment by mchelen-gov** [comment]
Conclusion:
- Bug in ESR sometimes causes ICN stub to be created
- ESR plans to resolve bug
- Current situation causes some HCA applications to go through help desk
- Help desk is successfully able to process these applications, so users are not negatively impacted
