### ISSUE TITLE
FaVAF: Determine need for Domo Dashboard

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#16644]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a stakeholder, I need access to easy-to-interpret metrics for Find a VA Form so I can establish baselines for determining if enhancements are effective.

## Hypothesis or Bet
If we create a Domo dashboard for Find a VA Form, then we should be able to simply and accurately see changes in traffic and user behavior.

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done
There will be a Domo dashboard that captures key metrics for for Find a VA Form - page views, time on page, conversions, and conversion funnel.

**Comment by jenniferlee-dsva** [comment]
FYSA - there is already a DOMO dashboard and KPIs set up for the Find a VA forms search and the form detail landing pages. 

**The KPIs are in the product outline here:** 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign#kpis 

And the GA links to the 2 dashboards are pinned to the forms channel topic/profile: 

**GA Dashboards:** https://analytics.google.com/analytics/web/#/dashboard/MHSfv0WxQySyKRB5IYyw1Q/a50123418w177519031p176188361/

https://analytics.google.com/analytics/web/?pli=1#/dashboard/Pq1Oso_0SWWgHWBkcxwqKg/a50123418w177519031p176188361/

**Comment by MarciMcGuireGCIO** [comment]
Thanks, Jen!

**Comment by MarciMcGuireGCIO** [comment]
Issues to create: 

- Compare existing GA dashboard data to desired metrics
- Identify gaps
- Prepare request for Domo dashboard only if GA data inadequate

**Comment by MarciMcGuireGCIO** [comment]
Closing this.  Oct-Dec GA data due is being purged today due to to PII being collected in the Facility Search.  As a result, a Domo Dashboard will be required to avoid a two-month gap in analytics data.  It's my understanding that Domo Dashboards pull archived GA data from a different data source.
