### ISSUE TITLE
Personnel removal from DSVA CMS related Slack Channels

### ISSUE THREAD

**Issue by JQuaggles** [department-of-veterans-affairs/va.gov-team#1664]
Please remove the following folks from the DSVA CMS Oriented Slack channels (they will remain on slack for other projects but not the CMS). 

- Meghana Khandekar
- Eric Chiu
- Ryan Sibley
- Rohan Bhobe

Channels to be removed from:
#cms-leads
#cms-changemgmt
#cms-outreach
#cms-administration
#cms-demos
#cms-design
#cms-engineering
#cms-facility
#cms-general

**Comment by LEHigley** [comment]
hi @JQuaggles sorry for the delay here! this is done but i couldn't edit cms-leads members

**Comment by JQuaggles** [comment]
No worries, thanks! @LEHigley

**Comment by lisac-usds** [comment]
hi @JQuaggles, would you be able to verify that these members have been removed from the `#cms-leads` channel? (that appears to be a private channel, and slack admins have limited visibility into those, unless we're personally members of it)
If things are all accounted for, I'd like to close this issue.

**Comment by JQuaggles** [comment]
@lisac-usds Yes they are. We can close! Mary removed them for me.
