### ISSUE TITLE
VSP content feedback -  Usability prep - Contact Us form 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#16657]
## User story
This ticket captures VSP content feedback for IRIS Contact us form

prototype link: https://staging.va.gov/ask-a-question

This includes Peggy's feedback in the card, and Rachel's comments on what is incorporated and when.

 **Contact Feedback key**
Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement

----

### Global notes and questions

- [ ] How will users find this form? How does this form relate to the Contact us static page in drupal? 

Working with Public Web site team to address

- [ ] is this form going to have a landing page to let users know what types of messages/queries they can do here? Currently there is the just the SIP message. Do you plan to put content on this landing page? How will users know when to use this form? 

We plan on revising the Landing Page as per Public Web site team collaboration.

- [ ] Is VA Form 0873 actually titled Contact Us? Or is this the IRIS form? 

Still TBD

- [ ] Should this form have a Need help? footnote component along the bottom? 

(Yes, being added)

-------

### Introduction/landing page screen

- [ ] H1: we need to discuss with IA and Public websites team on H1 for this form. There is a current Contact us static page being built out in drupal

Working with Public Web site team to address

- [ ] Is there going to be content on this page? 

Working with Public Web site team to address

-----

### Screen 1

- [x] MUST:  Per VA.gov content styleguide, please sentence case all headings, buttons labels, subheads

SHOULD:  Suggested rewrites to make this content user friendly and plain language: 

- [ ] Step 1 of 4: Your message details 

- [x] Tell us the reason you’re contacting us 

- [x] Category dropdown selections seem limited. What would a user select if they have a question about the status of their claim or VA debt? 

This is content we have for now - more is coming.

MUST: please fix wording of this question below. I don’t understand what we you're trying to ask the user: 

- [ ] How does a Veteran relate to your message?
Are you asking if this person is a Veteran or who is asking the question?  

Will be deleting these as per removing headings.

SHOULD: Suggested rewrite to remove / from question this question:

- [ ] My question is about a VA benefit or service

-------

### Screen 2

- [ ] SHOULD: when I choose I'm a Veteran on the earlier screen, then we should speak to Veteran in 1st person on this next screen, not "tell us about the Veteran" 

- [ ] SHOULD: suggested rewrites to make content more plain language

- [ ] Step 2 of 4: Your military service details

- [ ] Tell us your military service history

--------

### Screen 3
SHOULD: Suggested rewrites below:

- [ ] Step 3 or 4: Your contact information

- [ ] Tell us how we can get in touch with you 

MUST: Per VA.gov style guide and form label list labels should be 

- [X] Your first name

- [X] Your last name 

- [ ] CONSIDER: I don’t think we need US before mail in this label

- [ ] CONSIDER: Recommend we offer more than 1 phone option For example

Mobile phone number
Home phone number

----

Confirmation page screen

- [ ] SHOULD: Suggested rewrite to this paragraph to align language with other confirmation pages and content around email messages. 

Thank you for contacting us. We usually process messages within 5 business days.
If we have questions, we may contact you for more information. If you provided your email address, we'll send you an email to confirm that we received your message. You can also print this page for your records.

- [ ] MUST: Per my earlier feedback, this  page should have a CTA button: Go back to VA.gov 

Will revise as per discussions with Public Web sites team

## Acceptance criteria
 - [x] VSP/Peggy provides content feedback and recommendations for the form/tool.
- [x]  Product team incorporates feedback and/or asks follow up questions about the feedback
- [x]  Product team leaves any comments about feedback they decide not to take
- [ ] Peggy checks form after content feedback has been incorporated

**Comment by peggygannon** [comment]
**Contact Feedback key**

Must = Required
Should = Strongly encouraged/content best practice
Consider = Suggestion or possible enhancement

**Comment by murrayra** [comment]
Hi Peggy - thanks for the feedback! We'll be incorporating much of this either on this card or the [card on the IRIS board](https://github.com/department-of-veterans-affairs/orchid/issues/85).  I've put the content in the actual card and added task boxes to help with the dev team to ensure we incorporate all of them - let me know if that's ok, and will be adding comments throughout with status of when we'll be incorporating all of them.  Thank you!

**Comment by peggygannon** [comment]
thank you @murrayra for your responses/updates above. Appreciate the followup.
