### ISSUE TITLE
Print the OS Check Job Summary Directly in Slack Alert Message

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#16660]
## The Problem
When the OS Check jobs fail, the post to slack only contains a link to the jenkins console output. It would be nice if the `os-check` jenkins jobs printed a summary of which instances failed directly in the slack message.

## Extra Context
- [Relevant slack thread where idea was born](https://dsva.slack.com/archives/C37M86Y8G/p1606757475306600)
- Links to the os-check jobs: 
  - [dev](http://jenkins.vfs.va.gov/job/utility/job/os-check-dev/)
  - [staging](http://jenkins.vfs.va.gov/job/utility/job/os-check-staging/)
  - [sandbox](http://jenkins.vfs.va.gov/job/utility/job/os-check-sandbox/)
  - [prod](http://jenkins.vfs.va.gov/job/utility/job/os-check-prod/)

![image](https://user-images.githubusercontent.com/3077884/100644209-07972400-3309-11eb-95f0-cb3a0ca6aaf4.png)

In the above example ☝️ , @jbritt1 drilled down in the console output of each jenkins job and copy+pasted a summary of which EC2 instances failed.

## Work to be Done
- [ ] Print a summary of which instances failed directly in the slack alert message

**Comment by jbritt1** [comment]
Think this is almost purely cosmetic as it essentially saves a person one step of going and looking at the console output of the job. Given that and the ever-present intention of sunsetting Jenkins entirely I would argue this as extremely low priority. That being said, going to close it. Happy to have it reopened if deemed absolutely necessary and prioritized by Operations team leadership.
