### ISSUE TITLE
Analytics Implementation (Annotation) for Booz Team / STEM Application

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#16668]
# Google Analytics Implementation

## Description
- Is this request for Google Analytics implementation or QA?

Google Analytics annotation.

- Who is this request for?

    - Amy Knox, Booz Allen

- What team/project is this work for?
    
    - Rogers STEM Scholarship application
    
- Provide the Domain where Google Analytics needs to be implemented
     Within the GA annotations tray

- Additional Comments

Please add the following annotation on Nov. 11, 2020: 

> STEM Scholarship staged rollout (moderate - 50%) for remaining entitlement and SCO email functionality.

Please add the following annotation on Dec. 1, 2020: 

> STEM Scholarship 100% for remaining entitlement and SCO email functionality.

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by amyknox** [comment]
@joanneesteban - Since this was still in the icebox, I added another annotation: 100% rollout of the STEM SCO Alert functionality on Dec. 1.

**Comment by bsmartin-ep** [comment]
Annotations added to _All VA.gov Website Data [Production]_ view: 

![image](https://user-images.githubusercontent.com/62304138/100916840-50371480-34a4-11eb-8c1e-0da3843c33d2.png)

Closing.

**Comment by bsmartin-ep** [comment]
(I also updated your permissions on All to include Collaborate permissions.)
