### ISSUE TITLE
Analytics | Translation | Spanish | Corona FAQ 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#16667]
## Google Analytics Implementation

Request is for Google Analytics implementation

## Request to add Google tags to the Spanish language pages being created for the Spanish Corona pages. This includes the Covid FAQ's page ~~and the Research Volunteer info page.~~

**Note: decision was made 12/17/20 to NOT support a Spanish version of the Research Volunteer form.**

<details>

<summary>More Information</summary>

- https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

- https://www.va.gov/coronavirus-research

~https://www.va.gov/coronavirus-research/volunteer/sign-up~

<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

Google Analytics

- Who is this request for?

@DanielleThierryUSDSVA 
@SKasimow 
 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for? 

Danielle Thierry
Sharon Kasimow

Public Websites / Content and Localization

      
- Provide the Domain where Google Analytics needs to be implemented

URL:  va.gov
    
    _Identify if PII is passed in URL or title tag_

N/A
    
   - Please provide any upcoming deadlines or important milestones
    _ex: launch_

Launch date targeted for 1/20/21
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
  **[URLs here]**

- Spanish Corona FAQ page: http://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/ 
- Spanish Volunteer Research page: http://www.va.gov/coronavirus-research-esp/ 

    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._

**We should track same things as we do for the English pages**
-  UVs/PVs
- Source (ie: search, English version of the page)
- accordion clicks
- time spent
- new: add a satisfaction survey in Spanish 
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

N/A

    - [Provide sample users or link to user information here]
No authentication needed

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

N/A

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks, @SKasimow ! Is there a date that you're hoping this is completed by?

**Comment by SKasimow** [comment]
If we could do before the end of next week that would be great!!

**Comment by jonwehausen** [comment]
Assigning to @bmcgrady-ep.

**Comment by bmcgrady-ep** [comment]
Hi @SKasimow could you provide some more information here? Particularly, we are looking for product documentation, KPIs, and URLs to the pages you specifically want tracking on. Thank you!

**Comment by SKasimow** [comment]
@bmcgrady-ep Hi - apologies I was drafting this ticket and didn't mean to assign to you yet! I'm going to take back and will re-assign when complete! Sharon

**Comment by SKasimow** [comment]
@joanneesteban - sorry Joanne. I thought you were asking about when I'd like to have the orientation overview when I replied (got my tickets mixed).

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi Danielle - tagging you on this analytics ticket for our review later; need some help to complete.

**Comment by bmcgrady-ep** [comment]
@SKasimow - Do you have an update on this ticket? Let us know when you want us to start on this ticket.

**Comment by SKasimow** [comment]
@bmcgrady-ep  - good timing. I was just finishing up this ticket and will assign to you. Please lmk if you need any additional info (I should have the URLs on Monday 12/14) and will add them into the ticket. Happy to set up some time to walk-through as this is my first GA ticket :)

**Comment by SKasimow** [comment]
@bmcgrady-ep Update: will have URLs by end of this week (12/18) and will include as soon as I receive.

**Comment by joanneesteban** [comment]
@SKasimow looking forward to the URLs!

To clarify, are you looking for tracking specifically on Spanish pages?

**Comment by SKasimow** [comment]
Hi @joanneesteban - here's a summary of what I think we will need for this effort:

1. set up tracking for the new Spanish-language pages and Spanish Volunteer Research form (similar to the English pages tracking that is in use today).
2. we also want to track the CTRs for the links we will be adding to both spanish and english versions of the page; these are new links and will enable a user to toggle back and forth between english and spanish pages.
3. there is some PII collected on the Research Volunteer form so will need some help understanding how/what we can track (although I imagine we can mirror what we do on the English language version of the form).
4. we would like to provide a survey (but need some help understanding options/frequency etc).

Since this is my first analytics effort, could we set up some time to review these requirements live? Think that would be really helpful for me to have a better understanding of the process.


cc: @DanielleThierryUSDSVA

**Comment by joanneesteban** [comment]
@bmcgrady-ep to meet with Sharon & team on 12/23.

**Comment by bmcgrady-ep** [comment]
@SKasimow - It was nice meeting with you today. Let me know when the staging links are up and I can QA the events.

Here are a few links to the current tracking on the English versions of the pages:

- [Coronavirus Research Page](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2Fcoronavirus-research~2F%22,0%5D%5D)
- [Coronavirus FAQs Page](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.secSegmentId=analytics.pagePath&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2Fcoronavirus-veteran-frequently-asked-questions~2F%22,0%5D%5D)

**Comment by SKasimow** [comment]
@bmcgrady-ep Hi Ben - nice meeting with you as well. One other question that I meant to ask you earlier is re the new links we will be adding; there will be one on the English page to take user to the spanish version of page and vice versa. Do we need new tag or anything to track or is it just a click event?

@youngfreezyVA

**Comment by bmcgrady-ep** [comment]
@SKasimow - It should just be tracked as a Navigation Click, which @youngfreezyVA should be able to see examples of that Data Layer code on other pages. Let me know if you have any other questions.

**Comment by SKasimow** [comment]
@bmcgrady-ep Thanks Ben!

**Comment by bmcgrady-ep** [comment]
Hi @SKasimow - Just following up to see if there is an update on the status of the implementation of this. Once it is completed on your end, I will QA to make sure the analytics are coming in as expected and also will start on the GA dashboard that you requested. Thanks!

**Comment by SKasimow** [comment]
Hi @bmcgrady-ep  - our developer @youngfreezyVA is in the process of adding GA to the page today/tomorrow. We have the Staging Review next week on 1/19 but I will ping you as soon the analytics are incorporated so you can test in advance. Thanks for checking!  Sharon

**Comment by bmcgrady-ep** [comment]
Hi @SKasimow and @youngfreezyVA - I went through the Analytics tracking on the page and found something that needs to be added.
For all navigation link clicks on the page (links that take the user to another page/section of va.gov), the following Data Layer code should be fired:
```
dataLayer.push({
  event: 'nav-covid-link-click',
  faqText: 'How can I stay informed about COVID-19 vaccines at VA?', //pass in the text of the link clicked
  faqSection: 'Coronavirus-specific concerns' //pass in the section of the page
})
```
Here is a screenshot: 
![image](https://user-images.githubusercontent.com/66263904/105063315-d4376280-5a38-11eb-9a00-7436d943de9f.png)

Also, one more thing - do you want the tracking to be in English or Spanish? It is currently in Spanish, so the reporting will only show things in Spanish. If you want it to be in English, then the text passed into Analytics should be in English.

**Comment by SKasimow** [comment]
@bmcgrady-ep Hi Ben - is tracking for all the links on the page something we do today on the english language page? If so, agree this should be added to the spanish page since our goal was to mirror english page.

And since none of us reads/speaks spoanish I think we need the reporting to be in English - good catch!

Sharon

cc @youngfreezyVA @DanielleThierryUSDSVA

**Comment by bmcgrady-ep** [comment]
@SKasimow @youngfreezyVA - Yes, the English page tracks all of the links. Apologizes for the delayed response here.

**Comment by youngfreezyVA** [comment]
thanks @bmcgrady-ep, I am digging in to how the recording of analytics works with the "Get the latest updates on COVID-19 vaccines at VA" link on the english page and will revert with findings. cc @SKasimow

**Comment by bmcgrady-ep** [comment]
@youngfreezyVA - I am seeing all of the link events coming in for the Spanish page. I did notice that the text is still coming in Spanish and was wondering if that could be changed to English.

**Comment by bmcgrady-ep** [comment]
Hi @youngfreezyVA - I am still seeing the text in the event action coming in Spanish. Is this something that you will be able to update on your end?

**Comment by bmcgrady-ep** [comment]
@youngfreezyVA @SKasimow - We found out a way to get the text in English in BigQuery and Domo, so any Domo dashboard would have the text in English.

Closing this ticket out on our end.

**Comment by SKasimow** [comment]
@bmcgrady-ep Thanks Ben. So for GA the text will remain in spanish but Domo will be English. Think the should be fine for now. Maybe something to revisit when we have multiple pages in spanish :)

cc: @youngfreezyVA @DanielleThierryUSDSVA

**Comment by bmcgrady-ep** [comment]
Hi @youngfreezyVA - I noticed that there is one link on the Spanish FAQ page that needs to be tracked. It is the "Read this page in English" link.
![image](https://user-images.githubusercontent.com/66263904/106496028-a232f100-6479-11eb-85c4-19b5c78c5911.png)

The following dataLayer should be added when a user clicks on the link:
```
dataLayer.push({
  event: 'nav-covid-link-click',
  faqText: 'Read this page in English', //dynamically pass in the FAQ text clicked
  faqSection: 'Home' //dynamically pass in the FAQ section
})
```

Let me know if you have any questions. Thanks!

**Comment by SKasimow** [comment]
@youngfreezyVA let me know if a new ticket is needed  for this?

**Comment by youngfreezyVA** [comment]
no new ticket is needed thank you, i created a custom event for that link, but it looks like it should be the same as all the other links. i'm seeing if i can re use the existing logic for the other links

**Comment by youngfreezyVA** [comment]
@bmcgrady-ep confirming that the same structure is fine for the english page and the spanish translation link:
```{
      event: 'nav-covid-link-click',
      faqText: undefined,
      faqSection: undefined,
    }

**Comment by bmcgrady-ep** [comment]
Hi @youngfreezyVA - yes the same structure is fine for the English page as well.

**Comment by bmcgrady-ep** [comment]
The tracking for the links have now been added. Closing out this ticket.
