### ISSUE TITLE
Research BYO and Prescribed Device via Clipboard

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#16672]
Ming- There is a long term plan to include devices as part of the pre-visit information sharing with clinicians so I would like to do some general exploration around that with the upcoming clinician interviews. Clipboard will still be the primary focus. 
- So wearables or medical devices like CPAP or glucometers.

**Comment by kristenmcconnell** [comment]
@abuckley3385 @mlighdc 

Quick thoughts on a set of questions to add to our clinician interviews. 

1. Do you routinely have your patients send you data from devices, such as blood pressure monitors, CPAP machines, glucometers, mobile apps, wearable devices, etc?
   - If yes... 
      - From what particular devices?
      - Are they prescribed by you or BYO?
      - What information are you normally looking for?
      - How does this information impact your interactions with the patient and their quality of care?
      - What other devices might you be interested in reviewing information from?
      - Do you have any concerns about patient-generated data from devices?
   - If no...
      - Why not?
      - What devices or information types might you be most interested incorporating into your practice?


I also these questions here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/stakeholder-interviews/clinician-interviews/november-2020/clinician-questions.md.

Let me know if you think of anything else to ask in this first round.

**Comment by mlighdc** [comment]
The questions look good. Thanks @kristenmcconnell . For our meeting with Dr. Byrne, in addition to questions about workflow once he has the questionnaire responses, do you think it will mostly be the above questions about devices since the team have already talked to Dr. Byrne? Let me know if we all want to touch base before the call with Dr. Byrne. Thanks!

**Comment by kristenmcconnell** [comment]
Updated clinician interview conversation guide based upon some proposed questions from a Presidential Innovation Fellow.

**Comment by kristenmcconnell** [comment]
@abuckley3385 I'm pulling this story into the sprint and closing it out, because I'm actively doing this with the clinician interviews that are ongoing. The interviews and outcomes will be further tracked within #16063 and #16064.
