### ISSUE TITLE
Access for Corey Ferris

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#16681]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Corey Ferris
- Please Provide your email.
   > corey.ferris@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VAOS Team, Senior Software Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlw4ioK0VJSnp+ENfR/7P44c60EHDW4GCY4L5SbZ+62w1a9knaTbpP2EuznOIRKTgs6X2O6fZS8jyQN7zlNLcEiDnI8mYuBiB/yviCoXZjg9kq4dUpzz+I9hahIMqeeaJt823eY0uRp8UCqKVBglPk24LReg6TYgzsjMlNAkpFC+vCs1Iw2tAXW5XjaT63/BX7NLlMekiNT+KzpGozigKHYPtcoRyLvFz5oDShfYBH5B3jNwyclpTot6/9uiXlihaOCn/gerP9L++ZTByt0Rbgj159hmXBd59BCPSmcn2eHoJd2TqSu/0T8fTjCNzHUKfRcKH3k1GxOicTRmY8J+lZ7Pmv8guvk/KGAKREU7W12/pw4OwK/mhf3N05Kgy8EnOu67wD7lL4ZflGoCQ0LpPq5TuHt6qIyQR2euiBEDFq2AESIOtJrOlm16pnoyUjYbeHOrHDxBdOIQtkOmky5EY9gdQN+gd3ZNvNekQhS+QXP1Y3qFVMY8dPt7eB/sdrJBc= coreyferris@Corey-Ferris-Macbook.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
I need access to AWS Console for reviewing logs and AWS API access for programatically reviewing logs

**Comment by jbritt1** [comment]
### For AWS Access

User: Corey Ferris
COR: Crystal Moultrie
Approval required: @Jeff-Hayter

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.
