### ISSUE TITLE
[FE] Determine if we can even tell if someone is eligible who has not yet set up DD for edu benefits

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#16686]
## Background
See ticket: [[FE] Direct deposit for edu build #16479](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16479)

Erik to add more information

## Tasks
- [ ] Determine if we can even tell if someone is eligible who has not yet set up DD for edu benefits

**Comment by Samara-Strauss** [comment]
I thought we were 100% *not* doing this. We haven't gotten any confirmation from stakeholders or BGS devs that we can detect someone is eligible for direct deposit for edu even if they have not added direct deposit info yet. Is there still something to do here?

**Comment by erikphansen** [comment]
No this can probably be closed. I only left it open because I thought someone said (in an email?) that it appears ebenefits _is_ showing a "please set up DD for EDU" in some cases. Anyway let's proceed as though we cannot let people sign up and revisit if that changes.

**Comment by Samara-Strauss** [comment]
Yeah, eBenefits says this is how it *should* function, but they've provided no evidence that it does function this way. Without any evidence from them, and with BGS swearing this functionality doesn't exist, we can't move forward. But maybe it'll be like direct deposit for comp & pen and someone will magically find this functionality later. I wouldn't be surprised if that happens, but for now, I don't think there is anything we can do.

I have created #17345 for Jim to update the mocks accordingly, at which point I can update documentation.
