### ISSUE TITLE
Design Feedback - Usability Test Prep - Review [IRIS]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#16683]
- **Must** for if the feedback must be applied
- **Should** if the feedback is best practice
- **Consider** for suggestions/enhancements

**Must:**
- Change the error messaging on the required fields to follow the [design guidelines](https://design.va.gov/patterns/messaging-dictionary#feedback-messaging) Eg. Please enter your [required information].

- Update the form labels to follow [plain-language guidelines](https://design.va.gov/patterns/form-labels). Eg. “Date of Birth” should be “Your date of birth”

- On each form page, it seems like the Step name and the h2 underneath are saying the same thing, and they are different sizes on the different pages (“Your message,” “Veteran service information,” “Contact information,” Normally on forms, we don’t have that 2nd h2 after the “Step 1 of 6…” (See the [Health Care application](https://staging.va.gov/health-care/apply/application/veteran-information/personal-information) as an example, screenshot below). Please remove that 2nd h2 on each of the form pages - removing it clarifies the hierarchy and keeps it consistent with other forms across VA.gov.![Screen Shot 2020-11-30 at 4.01.52 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/708e1cf3-1073-408c-9ea8-8603e731fa04) 

**Should:**

**Consider:**

**Definition of Done:**
- [ ] Incorporate the **Must** feedback, and let us know on this ticket when they are updated mockups to check out 

- [ ] Leave any comments for feedback you decide _not_ to take

Emily or Allison will close the ticket once those things are all set. Thank you!

**Comment by murrayra** [comment]
Hi @allison0034!

Quick update on the feedback - thank you for this! 

- Change the error messaging on the required fields to follow the design guidelines Eg. Please enter your [required information] - we've added this to our story [here](https://github.com/department-of-veterans-affairs/orchid/issues/212) and the devs will have this done in our current sprint before Dec. 15th, likely done by end of this week
 
- Update the form labels to follow plain-language guidelines. Eg. “Date of Birth” should be “Your date of birth” - we've added this to our story [here](https://github.com/department-of-veterans-affairs/orchid/issues/212) and the devs will have this done in our current sprint before Dec. 15th, likely done by end of this week 

- On each form page, it seems like the Step name and the h2 underneath are saying the same thing, and they are different sizes on the different pages (“Your message,” “Veteran service information,” “Contact information,” Normally on forms, we don’t have that 2nd h2 after the “Step 1 of 6…” (See the Health Care application as an example, screenshot below). Please remove that 2nd h2 on each of the form pages - removing it clarifies the hierarchy and keeps it consistent with other forms across VA.gov.Screen Shot 2020-11-30 at 4.01.52 PM.png - - we've added this to our story [here](https://github.com/department-of-veterans-affairs/orchid/issues/212) and the devs will have this done in our current sprint before Dec. 15th, likely done by end of this week

Do you need to review the updated version on staging before we mark this as closed?
