### ISSUE TITLE
Closed Claims & Appeals (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16698]
## User Story
As a user, I want to quickly navigate through my list of active and closed claims/appeals.

## Acceptance Criteria
1. UI when a user has closed claims/appeals: 
     - Header: "Your closed claims and appeals"
     - Single list of closed claims/appeals, sorted by the most recent updated date
2. Each item in the list should display a summary, in the same format as the Active page:
     - Header for a Claim: Claim for [type] updated on [Month XX, XXXX]
     - Header for an Appeal: [Type] appeal updated on [Month XX, XXXX]
     - Below the header: Submitted [Month XX, XXXX]

**Note:** The following is covered in separate stories:
- Detail views for closed claims/appeals (these Closed Detail pages will have a different UI than the Upcoming Claims/Appeals detail pages)

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432345982/preview#project_console

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines
- Mark "Claims and Appeals" as Header 1

**Segmented Selector**
- accessibilityLabel="closed"
- accessibilityHint="view your closed claims and appeals"
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 2 of 2)

**List of Closed Claims and Appeals**
- accessibilityLabel= "closed claims and appeals list"
- accessibilityRole= "menu"
- Mark "Your closed claims and appeals" as Header 2
- For each menu item:
     - accessibilityLabel= field title (e.g. Claim for disability updated on January 20, 2020)
     - accessibilityHint= "view details of this closed___" (e.g. Claim or Appeal)
     - accessibilityRole= "menuitem"
     - accessibilityValue= contents of field

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
Hi @bridgethapner, can you confirm the following for AC #1?

- the header should read "Your closed claims and appeals"
- this list is sorted by most recent updated date

**Comment by bridgethapner** [comment]
Hi @bessgreen Yes, this is correct!

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
