### ISSUE TITLE
Content feedback - Staging review - Personalized Career Planning Chapter 36

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#16690]
## User story
This ticket captures VSP content feedback for VRE Chapter 36 form in staging.  Staging link: https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction  

## VFS acceptance criteria
- [x]  Let VSP know when the Must feedback has been incorporated
- [x]  Leave any comments for feedback you decide not to take
- [ ]  VFS team closes the ticket

**Comment by peggygannon** [comment]
@jason-gcio @sporeboy content feedback for Chapter 36 staging review is below. Please let me know if you have any questions. 

## Questions 

1. Per [wizard guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md) I don’t believe this form should have this:  “go back” link on the form introduction page

2. SIP alert at the bottom of the form introduction page page. Is this a new design pattern? We have a SIP message at top of this screen. Is the intent to have 2 of these messages on the page?

3. On confirmation page, is it true that VRE applications are processed within 1 week? 

4. On the confirmation page, I wanted to confirm that  VRE claims are posted in the claim status tool? 



--------

## Feedback key

Must = the feedback must be applied
Should = the feedback is best practice
Consider = suggestions/enhancements

## Must feedback

Chapter 36 wizard page: 

Please update wizard intro and questions/alerts according to the content outline:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/chapter%2036-form-wizard.md

-----

Update **Need help?** footnote throughout with new MyVA 411 number

**Need help?**
If you have questions or need help filling out this form, please call our MYVA411 main information line at 800-698-2411[hyperlink] and select 0. We’re here 24/7.
If you have hearing loss, call TTY: 711[hyperlink}

-----

Please fix this parenthetical content  on intro page to match paper form name and what appears on the previous wizard page
Equal to VA Form 28-8832 (28-8832-planning-and-guidance).

-----

Fix this typo: 
Follow the steps below to apply for Planning and career guidance TO: Follow the steps below to apply for career planning and guidance. 

-----


In Chapt 31, the VA file number label is different than what's in Chapt 36
Chapter 31 VA file number (if different than SSN)
Chapter 36 VA file number (if known)
Should these match across forms? 

-----

Please update this language/labels to align with content style guide: 

{checkbox} I live on a U.S. military base outside of the country.

Postal code: please sentence case this label, per style


---------

Your sponsoring Veteran or service member screen:
Please update labels to adhere to guidance in the Forms label masterlist:  

Your sponsor’s first name 
Your sponsor’s middle name
Your sponsor’s last name
Your sponsor’s Social Security number

------

On confirmation page, please move this header out of the blue box: Thank you for submitting your application

------

Name of the VRE program needs to be updated in the blue box content

-------


Update this content to the new VRE program name: 
What happens after I apply?
If you're eligible for career planning and guidance benefits, we'll invite you to an orientation session at your nearest VA regional office.

--------

Under **What if I have more questions?** Update content TO: 

Please call us at 800-827-1000. We’re here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET.

-------


Need to add go back button on confirmation page 

{CTA button} Go back to VA.gov 


--------

## Should feedback

Please reword this question to make it more plain language and understandable: 

Select one of the options below TO:
Let us know which of these describes you: 

{radio button} I’m an active-duty service member
{radio button} I’m a Veteran
{radio button} I’m a dependent spouse
{radio button} I’m a dependent child


------

## Consider feedback

Recommending additional updates to adhere to PL and content best practices:  

**Do you have a service-connected or pre-discharge disability rating?** 
If you have a service-connected or pre-discharge disability rating, you may be eligible for Chapter 31 Veteran Readiness and Employment (VR&E) benefits. With this program, you can get employment support and services to help you find a job and live as independently as possible. 
[Learn more about Chapter 31 eligibility]( https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/)

**Comment by jason-gcio** [comment]
Thanks for this @peggygannon, we will get started right away.

**Comment by micahchiang** [comment]
All feedback points have been addressed in [this pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/15396) **excluding:**
1. Under the "Questions"
    - Question 1 - Our team has received some conflicting guidance around this, waiting for absolute confirmation. 
    - Questions 3 - Might need verification from stakeholder on this timeline for application processing? 
    - Question 4 - Was unable to verify in staging, may need further investigation
2. Chapter 36 Wizard pages
    - Will require a separate pull request.

**Comment by peggygannon** [comment]
Hi, @micahchiang Thank you for your responses. 

Please let me know if you have any additional questions for me. I'm happy to take a look at the updated wizard page once the content is updated per the outline. 

Also, regarding question 1^^, I checked in about this and I think the final decision is up to the teams on whether to include the "go back" link. So you can disregard my question on that.
