### ISSUE TITLE
Adjust Product Health MVP (Google Sheet)

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1669]
## User Story
As a Va.gov product owner, I need to clearly read the Product Health MVP so I can easily use the analytics to improve my product.

## Goal
Adjust the Product Health MVP for usability with the suggestions listed in the Acceptance Criteria section.

## Acceptance Criteria
- [x] Tabs:
    - [x] Hide all tabs except for Weekly and Monthly. Weekly tab should be first.
    - [x] Rename tabs to remove "Weekly" and "Monthly." Just keep dates to reduce confusion. Remove the words, "[UPDATED]"
- [x] Columns:
    - [x] Combine "number of form events" and "form submissions" to be "Total Form Submissions or Visits"; Combine "unique form submissions" and "number of unique total events" to "unique form submissions or visits"
   - [x] Switch total/unique forms section with color-coded section
   - [x] Hide number of form submission weekly trend column
   - [x] Freeze column A
- [ ] Copy/Content
    - [ ] Remove "No Goals" under Key - the clutter confuses users and distracts them from the shaded portion
    - [ ] Goals header should be reworded - maybe "Goals - Shading Key"

## How to configure this issue
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

**Comment by joanneesteban** [comment]
@amycesal Before Friday of next week, please make the changes within the AC to the MVP that are good to go, and note any changes that you are not making with UX/design reasoning (and we can discuss further). Notify @jonwehausen when you're done with those changes. 
Jon, after the design changes are made, please check the code to ensure that the report can still run smoothly.

**Comment by joanneesteban** [comment]
@amycesal Can you add notes about keeping the goals to this issue? We can close this once that's done.

**Comment by amycesal** [comment]
<img width="1314" alt="Screen Shot 2019-10-02 at 8 58 12 AM" src="https://user-images.githubusercontent.com/1656046/66050412-caf84e80-e4f2-11e9-88ba-b52be9125fab.png">
I added the words "shading key" to the goals heading. However, I left the part about conditional formatting at the end, so it's clear how how people can update the shading if they need to. In theory, product owners can use this to set their own goals and it's useful to know how to update the formatting. 

I also left "no goals" in the labeling where are are no goals set. It distinguishes it from "no data" and serves as a call to action if product owners wish to set goals for these metrics.
