### ISSUE TITLE
Active Claims detail | Consolidated claims FAQ page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16699]
## User Story
As a user, I want to understand why the VA would consolidate my claim. 

## Acceptance Criteria
1. Create menu item
2. The "Find out why we sometimes combine claims" list item routes to a new page
3. Styling and UI matches the design

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432462453/preview#project_console
**ListItem from Claims detail page:** 
![Screen Shot 2020-12-01 at 5.50.10 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/46182f8e-42d8-41f0-ab52-768c40c657f2)
**FAQ page:** 
![Screen Shot 2020-12-01 at 5.53.21 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ecd636d5-821d-40e2-9def-5c70c82e6b8f)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

**Menu Item**
- accessibilityLabel="Find out why we sometimes combine claims"
- accessibilityRole="menuitem"
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list

**Consolidated Claims FAQ Page**
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Programmatically set page title as "A note about consolidated claims page" and mark as Header 1
- Mark "A note about consolidated claims" as Header 2

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
