### ISSUE TITLE
508-defect-4 [COGNITION]: App Directory - IE11 should not collapse the Apple Health icon

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#16703]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As an IE11 user, I want to see all of the application icons at the intended size. I might use those icons to identify apps on my device(s).

## Details

IE11 collapses the Apple Health icon incorrectly. Screenshot attached below.

## Acceptance Criteria

- [ ] Apple Health icon presents correctly in IE11

## Screenshots or Trace Logs

![Screenshot (60)](https://user-images.githubusercontent.com/934879/100678133-1940f180-3332-11eb-8d84-cf03af21b577.png)

**Comment by LeKeve** [comment]
Ready to test in production.

**Comment by 1Copenut** [comment]
Verified in IE11 on Production. Moving to close.
