### ISSUE TITLE
Upcoming Appointments List - Accessibility Issues

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#16707]
## What Happened?
**VoiceOver/TalkBack**
1. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, the a11yHint for the Upcoming tab is not picked up
2. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, the tab's (upcoming and past) place in the selector is not denoted
3. With TalkBack enabled on Android, the "Your confirmed appointments..." text is not picked up
4. With TalkBack enabled on Android, the date header text is not picked up 
5. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, the a11yHint for each menu item is not picked up

## Specs:
- Device: Android - Google Pixel 3XL(v.11) with TalkBack enabled
- Device: iOS - iPhone XR(v.14.2) with VoiceOver enabled
- User: marcy.nadeau@va.gov

## Steps to Reproduce: 

**VoiceOver/TalkBack**
For 1: 
1. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, navigate to the Appointments page
2. Select the upcoming tab in the segmented selector
3. Note that the screen reader does not pick the a11yHint "view your upcoming appointments"

For 2:
1. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, navigate to the Appointments page
2. Select the upcoming or past tab in the segmented selector
3. Note that the respective positions 1 of 2 or 2 of 2 are not denoted

For 3:
1. With Talkback enabled on an Android, navigate to the Appointments page 
2. Select "Your confirmed appointments..." text
3. Note that the screen reader does not focus on or pick up the "Your confirmed appointments..." text

For 4:
1. With Talkback enabled on an Android, navigate to the Appointments page 
2. Select any of the header dates (ex. February 2021)
3. Note that the screen reader does not focus not pick up the header text

For 5:
1. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, navigate to the Appointments page 
2. Select any of the menu items 
3. Note that the screen reader does not pick the a11yHint "view details of this appointment"

## Desired Behavior

**VoiceOver/TalkBack**
For 1:
- When the appropriate screen reader (VoiceOver/TalkBack) is enabled on iOS/Android, the upcoming tab's a11yHint will be picked up as "view your upcoming appointments"

For 2
- When the appropriate screen reader (VoiceOver/TalkBack) is enabled on iOS/Android, the upcoming tab position will be denoted as 1 of 2 and the past tab position will be denoted as 2 of 2

For 3:
- When TalkBack is enabled on Android, the "Your confirmed appointments..." text will be able to be focused and picked up 

For 4:
- When TalkBack is enabled on Android, the header dates will be able to be focused and picked up 

For 5:
- When the appropriate screen reader (VoiceOver/TalkBack) is enabled on iOS/Android, each menu item's a11yHint will be picked up as "view details of this appointment"

## Acceptance Criteria
- See desired behavior

## Bug Severity
- 4 - Low

## Linked Story (s)
- Story #13971

## Screen Shot(s) and Additional Information

**Comment by digitalken** [comment]
PASS 1/14/2021 - All issues are working on iOS and Android.  Closing.
