### ISSUE TITLE
Active Claims detail | Need help w/ Claim list item

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16706]
## User Story
As a user, I want to know how to contact the VA if I need help with my claim.

## Acceptance Criteria
1. Create menu item
2.  At the bottom of each Claim detail page, include a new list item called **Need help?** 
     - Stying & UI matches design
3. Phone number is styled as a hyperlink with click-to-call capability
     - Upon selection, the selected number appears in the native call banner

Note: the Appeals detail pages will have a variation of this Help banner

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432345660/preview#project_console
![Screen Shot 2020-12-01 at 5.50.20 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/59fb9866-4452-4c43-a8a7-0f70b58ac030)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Claim" as Header 1
- Mark "Need help?" as Header 3
- Link
     - Title= "800-827-1000"
     - accessibilityHint= “Dials this number via your device’s call function”
     - accessibilityRole= “link”

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
