### ISSUE TITLE
Restore geolocation via browser

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16701]
## Issue description
During map upgrade, the browser prompt to enable geolocation was removed. We intend to add a more elegant solution which gives the Veteran control within a search but in the interest of time for launching, we need to restore previous functionality. 

## Tasks
- [ ] Restore previous functionality for geolocation (prompt via browser)

## Acceptance Criteria
- Veteran can enable geolocation via browser prompt
- When Veteran enables geolocation, the field is populated.

**Comment by mpelzsherman** [comment]
Validated in staging.
