### ISSUE TITLE
Active Appeals detail | Need help w/ Appeal list item

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16709]
## User Story
As a user, I want to know how to contact the VA if I need help with my appeal. 

## Acceptance Criteria
1. At the bottom of each Appeal detail page, include a new list item called **Need help?** 
     - Stying & UI matches design
2. Phone number is styled as a hyperlink with click-to-call capability
     - Upon selection, the selected number appears in the native call banner
3. Visit VA.gov hyperlink opens the following URL, out-of-app: [TBD]

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/438003927/preview#project_console

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Appeal" as Header 1
- Mark "Need help?" as Header 3
- Link
     - Title= Name of link (e.g. 800-827-1000)
     - accessibilityHint= “Dials this number via your device’s call function” **OR** "Navigates to VA.gov claims and appeals"
     - accessibilityRole= “link”

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
@bridgethapner where does the hyperlink referenced in AC#3 route to?

**Comment by bridgethapner** [comment]
@bessgreen Hyperlink in AC #3 goes to: https://staging.va.gov/claim-or-appeal-status/

**Comment by bessgreen** [comment]
Update: hyperlink in AC #3 goes to https://www.va.gov/claim-or-appeal-status/

**Comment by msmanak** [comment]
Is there an option for someone to call via TTY number, I couldn't replicate but seeing if you can?

**Comment by bessgreen** [comment]
@msmanak not sure if that's a question for me or @bridgethapner but we can implement a TTY number if one exists and there is a corresponding UI.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/20/2021 - Passed on Android and iOS, both UI and Accessibility. Closing.
