### ISSUE TITLE
Expand VAMC test suite coverage for system page components 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16708]
## Issue Description
This issue expands VAMC test suite coverage of system page components 

## Tasks
Add unit/automated tests to check for the presence of the following basic required components on system pages:
- The Left Nav is present (except for individual event, news release and story pages)
- Intro paragraph is present on [system home page](https://www.va.gov/pittsburgh-health-care/)
- [Locations page](https://www.va.gov/pittsburgh-health-care/locations/) contains a listing of Main locations, Health clinic locations, Other nearby VA locations
- Calls to action are present (and buttons are stacked in mobile experience) on [Patient and health services page](https://www.va.gov/pittsburgh-health-care/health-services/) and [Locations page](https://www.va.gov/pittsburgh-health-care/locations/) 
- Main and Health clinic locations have a photo, actionable name, address, main phone, mental health phone, and actionable directions link 
- Other nearby VA locations have an actionable name, address, facility type, and actionable directions link 
[Patient and health services page](https://www.va.gov/pittsburgh-health-care/health-services/) has:
- jump link navigation
- "In the spotlight at VA Pittsburgh health care" (three blue boxes)
- Services listing containing accordions for Primary Care, Mental health care, Specialty care, Social programs and services, and Other services

## Acceptance Criteria
- [ ] Tests check for the presence of all required components and responsive design.

**Comment by davidmpickett** [comment]
all issues completed
