### ISSUE TITLE
Active Claims detail | Disagree with claims decision FAQ page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16700]
## User Story
As a user, I want to know what I should do if I disagree with the VA's decision on my disability claim.

## Acceptance Criteria
1. Create menu item
2. The "What should I do if I disagree with your decision on my VA disability claim" list item routes to a new page
3. Styling and UI matches the design
4. Hyperlink opens the following page in the device's browser, out-of-app: https://www.va.gov/decision-reviews/

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432345660/preview#project_console
**ListItem from Claims detail page:**
![Screen Shot 2020-12-01 at 5.50.15 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/93150884-3539-475f-bb4b-7e72061a158c)
**FAQ page:**
![Screen Shot 2020-12-01 at 5.53.46 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/006815d0-1424-4e8f-abf7-b99ea9d14449)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Menu Item**
- accessibilityLabel="What should I do if I disagree with your decision on my VA disability claim?
- accessibilityRole="menuitem"
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list

**Disagree With Claims Decision FAQ Page**
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Programmatically set page title as "What should I do if I disagree with your decision on my VA disability claim page" and mark as Header 1
- Mark "What should I do if I disagree with your decision on my VA disability claim?" as Header 2
- Link
     - Title= "Learn about your decision review options"
     - accessibilityHint= “Takes you to [TBD]"
     - accessibilityRole= “link”

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
@bridgethapner are you able to provide the URL for AC #3: the **Learn about your decision review options** link?

**Comment by bridgethapner** [comment]
@bessgreen Unfortunately claims is timing out in staging at the moment, will check back later today and hopefully be able to share the link then!

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by lexicalninja** [comment]
Here is the link for AC3: va.gov/decision-reviews/

Should this be on all claims details or just on completed claims details?

**Comment by digitalken** [comment]
Testing...
