### ISSUE TITLE
Add support for searching ICD-10 codes in CPRS

### ISSUE THREAD

**Issue by mbmasuda** [department-of-veterans-affairs/va.gov-team#16718]
I am a veteran/VA patient and a software engineer.  I have been trying to figure out how to submit this suggestion for improvement, but the avenues I have tried so far didn't work for me (e.g., submitting a suggestion via the VA IRIS service, calling the electronic service desk 1-800 number listed on the VA OIT website but finding out that is only for VA employee tech support, and also emailing oehrmquestions@va.gov).

I totally get that this repo is for the va.gov website team, and has literally nothing to do with CPRS or the new electronic health record, but I am making this super epic so hopefully I can correspond with someone who knows what I am talking about and can forward this to the right department within the VA.

Thanks!

### High Level User Story/ies
*As a doctor, I want to be able to quickly find the correct ICD-10 code to attach to an appointment note so that the correct diagnosis code(s) are used.*

### Problem Statement 
*My VA doctor told me how difficult it is for her to find the correct ICD-10 code in CPRS so as a result, these bad things can happen:*

1. The actually correct diagnosis is not documented, which could have an adverse effect on a veteran's healthcare.
2. A "mostly correct" diagnosis is assigned instead (because the desired code cannot be found so a similar one is chosen instead).
3. A diagnosis is completely omitted (because it is too hard or time-consuming to find the right code).
4. Due to 2 and 3 above, the VA cannot bill the veteran's insurance for the correct CPT code (for non-service connected issues) and could be losing money that they should theoretically be able to recoup.

From what my doctor told me, I suspect there is a SQL-based database that holds the normalized ICD-10 code data, and she must know exactly how the data is spelled in this db in order to be able to find what she needs.  It would be helpful to implement a search (e.g., Lucene) or, at the very least, a level of indirection that can easily be implemented via a new SQL table with "glossary" words that is joined to the ICD-10 table via a simple join table consisting of the foreign keys to the ICD-10 table and the new glossary table, which would allow doctors to enter words or phrases such as "brain cancer" in order to get a list of ICD-10 codes related to brain cancer from which they can choose.

Ideally, the VA would ask the doctors what terms the doctors would typically use to try to find a specific code so the glossary/search can be pre-populated with logical data, but it might also be helpful to include a way for doctors to add new synonyms to the search/glossary as well.

### Hypothesis or Bet
*There will be less bad data in a veteran's EHR and the doctors will save time and be less frustrated.*

### OKR
*Be excellent :)*

### Success metrics 
1. The amount of time doctors spend entering ICD-10 codes decreases
2. The correctness of data in a veteran's EHR increases (but I'm not sure how to measure this)

### We will know we're done when...
Doctors are able to quickly locate appropriate ICD-10 codes for a given diagnosis without needing to know the exact way the code is spelled out in the existing system

### Additional Details/Notes (optional)
None, but if you have any questions, feel free to ping me

### Artifacts
CPRS

### Communication
- Team that owns this super epic: I have no clue, that is why I made this issue :)
- Teams contributing to this super epic:

**Comment by mbmasuda** [comment]
Hi @Samara-Strauss,

Sorry for randomly tagging you, but I did it because it seemed like you are the person with the most commits to this repo.

I did finally get a reply from VA OEHRM after I had emailed them (their reply came after I had already made this issue), and the person who wrote back to me said he had forwarded my suggestion to the right place withing VA OEHRM and that someone from that department would respond in 7–10 business days.  That correspondence took place on the morning of December 2, so I am expecting to hear something any day now.

I don't know if you know if the VA OEHRM uses Github at all, but if you do, do you know how to find their repo so I can tag someone in that org?

Thanks!

**Comment by Samara-Strauss** [comment]
@mbmasuda — did you mean to tag me? I'm not familiar with this issue/problem, and I've not worked with the VA OEHRM before. However, my guess is that those people do not have access to Github, or if they do, they'll handle replies/correspondence over email. Sorry I can't be more of a help.

**Comment by mbmasuda** [comment]
@Samara-Strauss, yes, I tagged you because I was hoping someone in the VA software engineering team would have a better idea of how to get a hold of another department within the VA since I am not a VA employee.  I know the VA is a very big organization, so I know this was going to be a long shot, but thought I'd give it a try anyways.  :)

Basically, I think the VA is losing money by not being able to bill veterans' insurance for non-service connected care because of the lack of a way for doctors to efficiently find the correct ICD-10 code within CPRS.  Also, this issue could lead to worse health outcomes if the right ICD-10 diagnosis is not entered into a veteran's medical record.

**Comment by Samara-Strauss** [comment]
@mbmasuda — which team are you working on?

**Comment by mbmasuda** [comment]
@Samara-Strauss I do not work for the VA.  I am a veteran and get my health care from the VA.  However, I am a software engineer and was trying to submit this suggestion for improvement on behalf of my doctor at the VA who was telling me how difficult it is for her to do her job due to the way CPRS is implemented.

**Comment by Samara-Strauss** [comment]
@mbmasuda ah, thank you for letting me know! I'm not sure how we handle requests like this, but I'll ask around. Thanks for reaching out!

**Comment by mbmasuda** [comment]
@Samara-Strauss thanks!  Don't waste too much of your time trying to figure it out if you can't find the answer within a reasonable amount of time.  Supposedly VA OEHRM will write back to me by later this week.  If they don't I'll just ping them again.  I am extremely persistent, and now that California is in COVID Lockdown 2.0, I have plenty of free time on my hands!  :) 

Sorry it wasn't clear enough in the beginning that I am not a VA employee!

**Comment by Samara-Strauss** [comment]
No worries, thanks for letting me know!

I don't know there is much my team can help with — we don't work on CPRS, so we wouldn't be able to make moves on this request. I hope OEHRM gets back to you in a timely fashion with a more helpful answer.

**Comment by mbmasuda** [comment]
👍🏼

I'll comment again once I hear back from OEHRM so everyone can know the plan.

**Comment by mbmasuda** [comment]
I got the response from OEHRM's Acting Director of Migration and Syndication Dr. Augie Turano.  Dr. Turano said that the VA's new EHR is rolling out to the 130 VAMCs but is planned to take until 2028 to get it to all of them.  The new EHR should have a better way to find the ICD codes than CPRS.

I wrote back to suggest a standalone lookup API that can be used by anyone (within VA or not) to decouple the ICD stuff from any specific EHR implementation, but then this morning I found that a lookup system and API already exist 🎉🎉🎉

These tools are provided by the WHO and can be generally accessed from https://icd.who.int/

### Lookup UIs (easy for doctors to use):
* **ICD-10**: https://icd.who.int/browse10/2019/en
* **ICD-11**: https://icd.who.int/browse11/l-m/en

### APIs:
* **ICD-10** apparently first came out in 1990, so I don't think there is an API for ICD-10
* **ICD-11**: https://icd.who.int/icdapi

Gonna resolve this issue now.  Thanks for your help!
