### ISSUE TITLE
508-defect-3 [KEYBOARD] App Directory - Back to top button must work consistently with Public Websites' implementation

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#16713]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a keyboard user, I want the "Back to top" button to behave consistently across VA.gov

## Details

Our FAQ page has a "Back to top" button. I'd like to make sure this is behaving consistently with the Public Websites' implementation. Please see https://github.com/department-of-veterans-affairs/va.gov-team/issues/16532 for their current work on this element.

## Acceptance Criteria

- [ ] Back to top button works consistently with Public Websites
- [ ] Back to top button is accessible for keyboard and assistive technology users

## Environment

* https://www.va.gov/resources/connected-apps-faqs/

## WCAG or Vendor Guidance (optional)

* [Consistent Navigation: Understanding SC 3.2.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-consistent-locations.html)

## Screenshots or Trace Logs

<img width="753" alt="Screen Shot 2020-11-30 at 7 33 11 PM" src="https://user-images.githubusercontent.com/934879/100685929-e8b58380-3342-11eb-8e2e-144717e28cdc.png">

**Comment by LeKeve** [comment]
@1Copenut The back to top button is a part of the templates built by Public Websites. I believe they will be the ones to make changes to that button.

**Comment by 1Copenut** [comment]
Thank you @LeKeve, that's helpful context. I'm meeting with the PW engineers this afternoon. I'll keep this issue open for now, with the understanding it has an upstream dependency.

**Comment by laflannery** [comment]
Confirmed that this Back to top button is using the design system component and behaves correctly.  Will close in 1 week unless told otherwise
