### ISSUE TITLE
Developer documentation for `content-build` repo

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16714]
### User Story

As an engineer making changes to the `content-build` repo, I need to understand the basic contents and goals of the repository, so that I can maintain and iterate on it. 

### Definition of Done
- [ ] High-level developer documentation exists for `content-build` repo and is checked in either to the repo itself or va.gov-team
- [ ] Existing documentation (re: vets-website or metalsmith) that needs to be updated is identified and updated

**Comment by meganhkelley** [comment]
@billfienberg assigned this to you for now, we can reassign when we get to it as needed.

**Comment by meganhkelley** [comment]
Open question: How detailed does this need to be?

**Comment by alexandec** [comment]
Updated the content-build repo README in this PR: https://github.com/department-of-veterans-affairs/content-build/pull/57
