### ISSUE TITLE
508-defect-3 [COGNITION]: Buttons that have the same functionality MUST be identified consistently

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#16711]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** Josh Kim

## User Story or Problem Statement

As a user with cognitive considerations, I expect to see the sign in button to be consistently styled as a button throughout the page so that I can navigate confidently.

## Details

The option to sign in is presented to the user differently 3 times on the subway map page. 
1. As a semantic button styled as a button with the text "Sign in" within the navigation
2. As a semantic button styled as a button with the text "Sign in to start your application" within an alert at the top of the page.
3. As a semantic button styled as a link with the text "Sign in to your account."

This presents several issues:
1. Making a link look like a button is materially dishonest. It tells users that links and buttons are the same when they’re not.
2. Buttons behave differently than anchor tags. For example, users may become frustrated when trying to open a new tab when right clicking on a button styled as a link.
3. Inconsistent text generates inconsistent accessible names. Is a user signing in to access their account, to start an application, or for no known purpose at all? Screen reader users may become confused at the inconsistency.

## Acceptance Criteria

- [ ] Buttons are visually styled as buttons
- [ ] Buttons that share the same purpose share the same accessible name

## Environment

* Operating System: all
* Browser: any
* Screenreading device: any
* Server destination: staging, production

## Steps to Recreate

1. Open up the subway map page for [VA Form 28-8832](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction).
2. Open up dev tools and inspect the link styled as a button "Sign in to your account" near the bottom of the page.
3. Confirm it is a button styled as a link.

## Solution (if known)

2 solutions exist depending on design intent:

1. Delete the alert at the bottom of the page. If no clear design intent or research can justify its use, it may be more beneficial to the user to remove it from the page to reduce noise.
2. Restyle the button as a button instead of a link and rename it to be consistent with the original call to action. A primary or secondary button can be used depending on the designer's intent. View the code below for directions on how.

### Before

```html
<div class="usa-alert-body">
  You can save this application in progress, and come back later to finish filling it out.
  <br>
  <button class="va-button-link">
    Sign in to your account.
  </button>
</div>
```

### After

``` diff
<div class="usa-alert-body">
+ <!-- Added a p tag -->
  <p>
    You can save this application in progress, and come back later to finish filling it out.
  </p>
- <!-- Removed the br -->
+ <!-- Changed the class to usa-button-primary OR you can consider changing to usa-button-secondary too-->
  <button class="usa-button-primary">
    Sign in to start your application
  </button>
</div>
```

## WCAG or Vendor Guidance

* [WCAG 2.0 SC 3.2.4: Consistent Identification AA](https://www.w3.org/WAI/WCAG21/Understanding/consistent-identification.html): Components that have the same functionality within a set of Web pages are identified consistently.
* [Adam Silver: But sometimes buttons look like links](https://adamsilver.io/articles/but-sometimes-buttons-look-like-links/)

### Before
<img width="742" alt="Screen Shot 2020-11-30 at 8 03 36 PM" src="https://user-images.githubusercontent.com/14154792/100683834-24eae300-3347-11eb-8ffb-c52c440b5e30.png">

### After
<img width="715" alt="Screen Shot 2020-11-30 at 8 04 03 PM" src="https://user-images.githubusercontent.com/14154792/100683864-33d19580-3347-11eb-9f41-11352db37f6f.png">
OR
<img width="793" alt="Screen Shot 2020-11-30 at 8 05 23 PM" src="https://user-images.githubusercontent.com/14154792/100683955-63809d80-3347-11eb-92b7-57d3e78a1633.png">

The padding is a bit overwhelming here regardless of the solution. Given the amount of noise already on the page, I would recommend the first solution of simply removing it from the page unless a strong design reason exists for it.

**Comment by joshkimux** [comment]
Another note on this-- the start application without signing in is coded as a button instead of a link, so a user won't be able to open this in a new tab.
<img width="517" alt="Screen Shot 2020-12-01 at 2 35 18 PM" src="https://user-images.githubusercontent.com/14154792/100787976-709e9a80-33e2-11eb-9f29-d2cc427276ee.png">

**Comment by jason-gcio** [comment]
We will remove the bottom alert to reduce noise and button confusion.
The classes on the button in the top alert is not available to us to adjust (and probably needs aria tags as well).

**Comment by jason-gcio** [comment]
The bottom alert has been shown to be produced by the Save In Progress mechanic and we are not in a position to remove it easily.

These patterns exist globally and are prevalent throughout the site.  Jesse has some guidance about seeing what is getting pulled in and its availability and adjustability.

**Comment by jason-gcio** [comment]
Might be at Platform level? I think this is across all of VA.gov?

**Comment by ohgreatkate** [comment]
button/link alert has been removed.
