### ISSUE TITLE
Request Contact Center Review for "View VA payment history"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#16724]
**Context:** This feature provides a list of all payments and returned payments for a Veteran, and includes the date, amount, bank and VA department that has sent the payment.  In the event of a return, if there is a reason that is listed as well.  This is a simple, non-transactional view task.

**Launch Date and Details:** The quickest would be after final usability pass (Dec 7-9), staging review (Dec 10-11), UAT/launch (**Dec 14-15** ) but as we get closer to holiday freeze this might be be in the new year.

**URL:** https://staging.va.gov/va-payment-history/payments/ (requires auth)

**Product Guide:** [Link to product guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/payment-history/Contact-Center-Product-Guide-view-payments_v11132020.pdf)

**Product Video:** [Link to product video](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/payment-history/View-Payments-Walkthrough.mp4)

**Transcript:** [Link to transcript](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/payment-history/contact-center-video-transcript.md)

**Comment by Kimberley2019** [comment]
@jason-gcio We are in receipt of the product guide and will review before passing along to VEO Call Center.  We will advise if any questions and/or comments and provide updates accordingly.

**Comment by Kimberley2019** [comment]
@jason-gcio The internal contact center team has done an initial review of the product guide and video and have passed it along to the VEO Tier 1 Contact Center for their review.  

I have advised them the deadline to submit questions and/or feedback is COB (5PM ET) 12/8/2020.  If they do not have feedback or do not respond, I will advise accordingly and close the ticket.

During this time, please advise of any modifications that will need to be passed along.

**Comment by jason-gcio** [comment]
Sounds great! We do have any modifications to this feature and the only tickets we have for it are to move it into UAT after staging review.  We do not anticipate any modifications from Staging Review but will update as we become aware of any.

Thanks very much!

**Comment by starlow00** [comment]
@clantosswett @Kimberley2019 I made some edits to the PDF. Some spacing issues around punctuation marks I added may occur, as I couldn't get my PDF editor (FoxIt Phantom) to select the small spaces between words. Thus, I'm hoping edits are applied manually, rather than by software.
[Contact-Center-Product-Guide-view-payments_v11132020_ST_120420.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5645887/Contact-Center-Product-Guide-view-payments_v11132020_ST_120420.pdf)

**Comment by jason-gcio** [comment]
I reviewed the recommended changes and updated the PowerPoint/PDF.  Just a note, we don't capitalize the feature names on VA.gov and I was trying to keep it the same. They have been edited though to reflect your preference though.
[Contact-Center-Product-Guide-view-payments_v12112020.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5681732/Contact-Center-Product-Guide-view-payments_v12112020.pdf)

Thanks for the feedback, much appreciated!

**Comment by Kimberley2019** [comment]
Good Morning @jason-gcio thank you for including those changes. The contact center did not respond with any questions or feedback.    

Moving forward, we will have our technical writer review the guides and videos and make any suggestions that would be beneficial for agents.

This ticket can now be closed.
