### ISSUE TITLE
[Development] 526/CST: Remove all reference to faxing claim documentation or actual claims

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16733]
## User Story
As a veteran, I would like to not send a fax after January 1, 2021 because it will not be accepted.

## Expected Behavior
Any mention of faxing information for claims or documentation updates needs to be removed from the VA.gov benefits ecosystem, including public websites.

Here are some places we need this done:
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src%2Fapplications%2Fclaims-status%2Futils%2Fappeals-v2-helpers.jsx#L645
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src%2Fapplications%2Fdisability-benefits%2Fall-claims%2Fcontent%2FinstructionalPart3.jsx#L13

**The above are not all the places**

## Acceptance Criteria
- [ ] Fax is removed from BAM1 controlled areas of 526 and CST
- [ ] Any places that are public websites should be added to this story [link]
- [ ] I do not think we need review from content, but maybe just do a quick check with @peggygannon

**Comment by vhenry07** [comment]
Per Michael Young, fax decommission effort has closed out. We're clear to remove fax references.
