### ISSUE TITLE
VSA spot check review for VSA Public Websites [back to top button]

### ISSUE THREAD

**Issue by youngfreezyVA** [department-of-veterans-affairs/va.gov-team#16737]
## Instructions

1. Click or press the gear icon next to the "Labels" heading on the right. Search for your team in the labels list. If your team is not listed in the Labels menu, please leave a comment after you have created this issue. The Product Support team will create a new label for your team.
2. Text inside `<-- comment -->` blocks will not appear in your issue ticket. These comments offer guidance on what information you should provide for each section.

### For reference

**VSA Development Review** - [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review)

## Team Name

VSA Public websites
## Product/Feature Name
Back to top button:
http://localhost:3001/resources/signing-in-to-vagov/
https://github.com/department-of-veterans-affairs/vets-website/pull/15132/files

- [ ] **Design collaboration review** (Review design to discuss accessibility and inclusive design) - This may happen as design evolves.

- [ ] **Development intent review** (Review design to discuss approach to take with development, identify what components and semantic HTML would be appropriate, identify any accessibility issues and how to address) - This would happen as designs are passed to development, before development begins.

- [ x] **Spot check review** (Review and follow the steps in the [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md) first.) This happens well before launch, so that the 508 office can review and any issues addressed *before* launch.

- [ ] **Other:** Please indicate what you're requesting

## Point of contact

Fareez Ahmed
## Preferred times for dev intent checkpoint, if applicable
afternoon PST

## Staging URL and credentials, if applicable

**https://staging.va.gov/resources/signing-in-to-vagov/**

**Comment by jenstrickland** [comment]
@youngfreezyVA Thanks for requesting the spot check. When this is available in staging, would you please update the ticket and comment here? 😅

**Comment by youngfreezyVA** [comment]
no worries @jenstrickland :) will do!

**Comment by youngfreezyVA** [comment]
here is staging url:
https://staging.va.gov/resources/signing-in-to-vagov/

**Comment by jenstrickland** [comment]
OMG @youngfreezyVA —  I forgot something. We can't have screen reader only links, because they receive focus. 🤦‍♀️  I'm sorry! 

@1Copenut — do you think there's a way we can use `aria` to announce the sticky button just above each of the h2s? I was avoiding it because so much I read said `aria-live` has inconsistent behavior, but perhaps we have to do it.

**Comment by 1Copenut** [comment]
@youngfreezyVA (I really like this user name!)

Adding comment from our discussion earlier today. When users press / click the Back to top button, we should set focus back to the `<body>` tag. When users press the `TAB` key again, the skip to content link will be the first element under keyboard focus. That feels like the best approach, and matches the focus handling GOV.UK uses in this example page: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets

We will want to check this behavior in a number of browsers, especially IE11. That browser in particular has a bad tendency to need a tabindex="-1" applied to containers so they will receive keyboard focus. I hope that's not the case here, but wanted to make mention of it.

/cc @jenstrickland

**Comment by jenstrickland** [comment]
Double-checking here, since @1Copenut said that the focus should go to `<body class=" merger" screen_capture_injected="true">` after the back to top button is clicked, so that the next tab press goes to the Skip to content link. Is that right, Trevor?

**Comment by 1Copenut** [comment]
Yes. When I think of back to top, I think of it like pressing the `Home` button that zooms all the way to the top of the page. We don't have any conflicting research or information, so let's set it at the top. This ensures we always have the same element being referenced.

If research shows users would prefer the back to top be set on the `<main>` element, we can adjust later.

**Comment by youngfreezyVA** [comment]
> Double-checking here, since @1Copenut said that the focus should go to `<body class=" merger" screen_capture_injected="true">` after the back to top button is clicked, so that the next tab press goes to the Skip to content link. Is that right, Trevor?

got it, that's a quick fix. re opening pr
