### ISSUE TITLE
Track Secondary-only Applications

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16748]
## User Story

Given that want to keep close eyes on the number of SFC-only applications
I want to pull a report daily for the two weeks following launch
To be able to provide updates and support to the Caregiver Program.

**Comment by kevinmirc** [comment]
Emailed report for the time period: 2020-11-27T15:25:43 UTC - 2020-12-03T17:05:45 UTC

**Comment by kevinmirc** [comment]
Ran query again to get the count for the time period starting at 2020/11/24 00:00:00 and ending at 2020/12/03 23:59:59 UTC:
Total number of applications: `1923 `
Total number of applications that do not have a Primary Caregiver Present: `16 `
