### ISSUE TITLE
Debt Portal - fallback messaging for unassigned diary codes

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#16757]
## Issue Description
When unassigned diary codes are sent, show the following status/alert:

Status: We're updating your account

_Info alert:_
**We’re updating your account**
Please check back in one week for updates. If your account still shows the same information, call us at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET.

---
## Tasks
- [ ] Ensure all unassigned diary codes show the above messaging

## Acceptance Criteria
- [ ] Unassigned diary codes show the above messaging

**Comment by leahkeeler** [comment]
reference 16741 - close
