### ISSUE TITLE
Create document regarding design decisions made in the past

### ISSUE THREAD

**Issue by accbjt** [department-of-veterans-affairs/va.gov-team#1675]
## User Story
As a developer, I need to know if there are any design decisions that were made in the past that can effect my development.

Case: The By Light team was updating user information and the mockup had a success message. When talking to other developers we found out that it was decided in the past that we would not show success messages anymore. We should have a place were we can document this historically.

## Goal
We will have a place to document design decisions.

## Acceptance Criteria
- [ ] A document that has design decisions that were made in the past.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mandifrances** [comment]
Not needed
