### ISSUE TITLE
Access for Jack Schuss

### ISSUE THREAD

**Issue by yakschuss** [department-of-veterans-affairs/va.gov-team#16761]
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Jack Schuss
- Please Provide your email.
   > jack.schuss@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse-Bananapeels - software engineer - oddball

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4OhIsbh0OSW7K0U7UwV2sGoS1m7qNE0PH1ziGNcxDhlScBDYXOb07YqLRw+4AVZ9NEw+S/sgCz9ybSraoJuhxx+ioqelE6WsDmAMjygJYUbiOfy7wDz1hEUwMqaCRTGlSYOAeMI09QhMbyELjxIadV0SVbUvK2xtxcvm5Ya/Y/wnu+uJKF9xTCHLVGMu8YEZu4OO+vRZIPo3TaCbNiWduNZq/WmXREgHcLjN4AZ3yZUA8LD9FJcQI7aE25VF0Jl1lsXb6g0d2YycPK01TS92QKre7ViIQPJDTX7ox5XMjEPl6VT3zY9z3BLjLwPnEcGnkH5T8EmYJJO+Rc7aFmEQxXDFdHNDjwvgMZ2PMPwGRewmgJgkooUyHNcu66j7GgLGO9PNf3KZ1y//AKcxMV0vgQigJ148QYfVT2YMLOiSv/1cOQJ5Rjph+tqHaoufGkDRRvicEOmFUyuDlcaJPexctuE32oxw8RBa2IvDLaKp2xhw80hmOb04Cz0B/x9Aoz4U= jackschuss@Jacks-Mac.local
```

- Grant AWS Console access?
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
