### ISSUE TITLE
Discovery: What data do we need to collect?

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#16762]
**Type of Data**: The preference would be access to authenticated data.  If there will be an option for unauthenticated, the data needs to be identified as unauthenticated.  

**Fields:**
Patient Identifier: ICN would be the preferred patient identifier. 
Preferred VA Facility: List that produces the sta3n / sta6a
Authenticated Data: See Type of data. (Boolean)
Interested in Vaccine: Yes/No/Undecided
Do you want to be contacted about updates?: Boolean
Method: [email, text]
Reason Undecided / No: (list of reasons to determine next action). Examples from Columbia below:

- Due to health conditions
- Concern over the vaccine’s safety
- Unable to travel to a VA

**If unauthenticated, need the following additional information:**

First Name
Last Name
DOB
Primary Contact number
SSN (Can we collect?) - If so, can vetsapi do an ssn lookup to get ICN above? 

First Version of Table:

![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/d6335395-2bd2-4d4d-92c5-f9d5f63f57a5)

**Comment by batemapf** [comment]
@stephenBarrs to connect with Ming re: what is required on Caregiver and @batemapf will learn from Ming about privacy matters.

**Comment by shanemelliott** [comment]
Table Created, Rob will create endpoint tomorrow by COB. 

Three endpoints 

1. Put
2. Get by ICN
3. Get By sta3n

**Comment by shanemelliott** [comment]
A site commented on Travel plans should we collect? Travel plans/other issues which would make appointment or follow up appointment impossible to make based on clinic dates

**Comment by shanemelliott** [comment]
Need to discuss adding:   race, ethnicity to unauthenticated data.

**Comment by shanemelliott** [comment]
forgot email on unauth

**Comment by stephenBarrs** [comment]
@shanemelliott if we can send ICN should we still send SSN?  We should probably have SSN for any Veteran that we cannot find an ICN for.
