### ISSUE TITLE
Offboarding of Maggie Brazeau

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#16765]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Maggie Brazeau
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VFS-CMS, Helpdesk Support, 12/1/20, CivicActions
- Please provide any type of access they may have and their GitHub username. 
  > SOCKS, Google analytics, GitHub userID = MaggieBrazeau
  
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by bsmartin-ep** [comment]
No Google Analytics, Google Tag Manager, or DOMO access for Maggie Brazeau that needs to be removed.

**Comment by bsmartin-ep** [comment]
OK to close @cmaeng?

**Comment by jbritt1** [comment]
@bsmartin-ep:
On the Operations team, we are currently trying out a new process where after these kind of requests are handled we move them to "review/QA" to let our team leadership confirm all things are done and then they close it. If it is okay with you / your team, can we do that process with this one and let Ops team leadership (@jhouse-solvd / @dginther) close this one after they have given it a once-over?

**Comment by bsmartin-ep** [comment]
> If it is okay with you / your team, can we do that process with this one and let Ops team leadership...

Sure thing @jbritt1.

**Comment by bsmartin-ep** [comment]
Reassigning to @jhouse-solvd / @dginther per @jbritt1's [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16765#issuecomment-737252234).

**Comment by joanneesteban** [comment]
Hey @jbritt1 - thanks for the note. We're going to remove the analytics-insights label from this unless you need anything more from us.

**Comment by jhouse-solvd** [comment]
It appears that all relevant access was properly revoked. Closing.
