### ISSUE TITLE
Discovery: What does a Veteran expect to learn about the vaccine / process?

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#16766]
- In general about vaccines
- About their ability to get vaccinated by VA
- From VA.gov vs. other sources?

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf @lalexanderson-dsva FYI - I've started a doc with notes on observations from social media as one way of continuing to listen to Veterans' questions and concerns. Will continue adding to this as we go. 

https://github.com/department-of-veterans-affairs/digitalservice/blob/master/product-lines/health/covid-19/vaccine/research/social-listening.md

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf @lalexanderson-dsva SEO update below

Pasting in the SEO themes that bubbled up when I did my original SEO research using SEMRush on 11.17.20:

1.	When we’ll have a COVID-19 vaccine (various keywords: when will there be a vaccine, when will a vaccine be ready, vaccine updates, vaccine news, vaccine progress, vaccine tracker, how close are we to a vaccine)
2.	Vaccine trials
3.	Specific companies creating COVID-19 vaccines, who is making the vaccine
4.	MMR vaccine and COVID-19
5.	Flu vaccine and COVID-19
6.	Will the vaccine be mandatory?
7.	Vaccine microchip 
8.	Vaccine side effects
9.	Rna/mRNA vaccine

Just pulled keyword data again, and it's still pretty consistent with this. Also seeing the specific question of safety in terms of this new approach to vaccines (mRNA) in social media.

- "coronavirus cure" is getting 2,400 msv and I see some other "cure" type language

**Other SEO notes from SEMRush data:**
- Not seeing any SEO keyword volume specifically around covid vaccine for veterans.
- Not seeing keyword volume specific to vaccine on our **coronavirus faqs page**. 
- Our **coronavirus research volunteer list** landing page does have some vaccine-related keyword volume, but no notable findings to show what people want to know.
- The **VA covid-19 public health page** is ranking 10th for "coronavirus treatment" (msv: 8,100). No other notable vaccine-related keyword volume.

[covid_vaccine-phrase_fullsearch-us_12.5.20.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5647788/covid_vaccine-phrase_fullsearch-us.1.xlsx)

[www.va.gov_coronavirus-faqs-organic.Positions-us_12.5.20.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5647790/www.va.gov_coronavirus-veteran-organic.Positions-us_12.5.20.xlsx)

[www.va.gov_coronavirus-research-volunteer-list-organic.Positions-us_12.5.20.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5647791/www.va.gov_coronavirus-researc-organic.Positions-us_12.5.20.xlsx)

[www.publichealth.va.gov_n-coro-organic-Positions-us_12.5.20.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5647792/www.publichealth.va.gov_n-coro-organic.Positions-us_12.5.20.xlsx)

**Comment by DanielleThierryUSDSVA** [comment]
- Report from contact centers: Veterans asking whether family caregivers can receive vaccine
