### ISSUE TITLE
Active Claims detail | Estimated decision date

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16777]
## User Story
As a user, I want to know when the VA expects to make a decision about my claim. 

## Acceptance Criteria
1. Create menu item
2. On each Claim detail page, include a new list item that contains the UI for an estimated decision date
     - This list item comes after the timeline and before the Consolidated Claims item
     - Stying & UI matches design
3. Date is informed by the API
     - Format: [Month XX, XXXX]

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432345660/preview#project_console
![Screen Shot 2020-12-01 at 5.50.03 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/538b46d3-055a-44a2-839f-3111ff97fff4)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Claim" as Header 1

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
@bridgethapner @jperk51 will there always be an estimated decision date? If not, should we still display the 'Estimated decision date' ListItem, or should we hide this from the Claims detail page?

**Comment by bridgethapner** [comment]
@bessgreen Story #14029 has a UX solution for this - if there's no est decision date we want to show a message saying that in place of the date. 

![Screen Shot 2020-12-07 at 10.32.23 AM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/cf01ecc9-22bb-46aa-8bfd-93b01673b613)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
