### ISSUE TITLE
Claims file upload page | Section 1

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16775]
## User story
As a user, I want the ability to upload files to my claim so the VA can process my claim faster. 

## Acceptance Criteria
1. Selecting the "View file requests" large button from the Active Claims detail page routes to a new page called "File upload" 
2. Create UI for the first section of this page: 
     - Upload a file to your claim
     - Maximum file size
     - Accepted file types
3. Copy in this section is hard-coded

Note: there is a separate ticket for Section 2 (File request list): [#17446](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17466)

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432623517/inspect
![Screen Shot 2020-12-14 at 5.16.57 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/5ddcd6c5-a002-414c-b5ab-b17e4f3dc9fe)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use general done button a11y
- Mark "File upload" as Header 1
- Mark "Upload a file to your claim" as Header 3
- Mark "Maximum file size" as Header 3
- Mark "Accepted file size" as Header 3 

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by msmanak** [comment]
Make sure the upload process is conveyed easily for the blind user as iOS doesn't have a method of capturing correct screens

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Passed both UI and Accessibility - Sending to Design QA.
