### ISSUE TITLE
Active Claims detail | Status/Issues segmented selector

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16785]
## User Story
As a user, I want to view my claim details in two distinct sections (Status/Issues) so it's easier to reference

## Acceptance Criteria
1. At the top of each Claims detail page, create a list item called "Your [type] claim"
2. Display the date in which the claim was received
     - Format: [Month, XX, XXXX]
3. Pull in the segmented selector common component
     - "Status" (default) and "Issues" are two different segmented tabs that each display a unique list of list items below

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432345660/preview#project_console
![Screen Shot 2020-12-01 at 5.49.53 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/5c73fb73-8f20-4c63-9c67-efae51ef2444)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - accessibilityLabel= “Back”
     - accessibilityHint= “Go back to the active claims and appeals page”
     - accessibilityRole= “button”
- Mark "Your Claim" as Header 1
- Mark "Your [type] claim" as Header 2

**Segmented Selector**
- accessibilityLabel=Name of tab (e.g. Status or Issues)
- accessibilityHint="view your claim___" (e.g. status or issues)
- accessibilityRole="tab"
- Denote selected vs. unselected
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 1 of 2 or 2 of 2)

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by esther-k** [comment]
**12/14**
UI and functionality pass on iOS and Android. Accessibility fails with a [multi-issue bug](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17459) entered. Moving to Design QA
