### ISSUE TITLE
Active Claims detail | Issues summary

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16790]
## User Story
As a user, I want to view an issues summary for my claim so I can reference what I've claimed, the date the VA received it, etc. 

## Acceptance Criteria
1. On the Claims detail page, when "Issues" is the selected segment, display a list with the following 4 categories of information:
     - Claim type
     - What you've claimed
          - List of contentions comes through in an array
     - Date received
          - Format: [Month XX, XXXX]
     - Your representative for VA claims
2. All data within each of the 4 headers is service-driven
3. Styling & UI match the design

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432345662/preview#project_console
![Screen Shot 2020-12-01 at 6.33.44 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/30fe9c95-7efd-4572-a01b-036cce67e6f5)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Claim" as Header 1
- Mark "Your [type] claim" as Header 2

**Segmented Selector**
- accessibilityLabel="issues"
- accessibilityHint="view your claim issues" 
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 2 of 2)

**Summary Data**
- Mark "claim type" as Header 3
- Mark "what you've claimed" as Header 3
- Mark "date received" as Header 3
- Mark "your representative for VA claims" as Header 3

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
