### ISSUE TITLE
Personal and Contact Information - Crashes after Voice Control in iOS to "Delete line" after entering phone number in work phone number

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#16792]
## What happened?
Using voice control in iOS, I navigated to Personal and Contact Information.
I navigated to the Work phone number editor.
Using voice control, I entered a phone number.
Using voice control, I said "Delete line".
--> Crash

NOTE: Didn't crash in Address or City.  But it DID crash in Zip code!

## Specs:
- Device: iPhone 6s using Voice Control

## Steps to Reproduce
- Using voice control in iOS, I navigated to Personal and Contact Information.
- I navigated to the Work phone number editor.
- Using voice control, I entered a phone number.
- Using voice control, I said "Delete line".
--> Crash

## Desired behavior
Saying "Delete Line" using voice control should delete the line I've just entered.

## Acceptance Criteria
- [ ] Saying "Delete Line" doesn't crash app.

## Bug Severity
- 1 - Critical - Crashes app.

## Screen shot(s) and additional information
Crash Log:

[https://app.zenhub.com/files/133843125/a1291ae7-93f5-49df-8fd0-cc58b98f2adf/download](https://app.zenhub.com/files/133843125/a1291ae7-93f5-49df-8fd0-cc58b98f2adf/download)

**Comment by digitalken** [comment]
PASS 1/14/2021 - Shows standard keyboard and "delete line" command no longer causes crash.  Closing.

**Comment by lexicalninja** [comment]
Issue moved to [department-of-veterans-affairs/va-mobile-app #2570](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/2570) via [**ZenHub**](https://www.zenhub.com/)
