### ISSUE TITLE
Work with DEPO team to determine final direction of MyVA (dashboard vs newsfeed)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#16806]
## Background
In order to determine the direction of MyVA, Samara will gather input from the DEPO team to help inform the product decision regarding the direction of MyVA (dashboard vs newsfeed approach).

## Tasks
- [x] Samara meets with DEPO team ([meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/newsfeed-or-dashboard-approach.md))
- [x] Direction of MyVA has been determined

**Comment by Samara-Strauss** [comment]
We are taking the traditional dashboard approach.
