### ISSUE TITLE
Replace lodash/fp on vets-website

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1680]
@cehsu commented on [Fri Sep 14 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13253)

As @jbalboni has pointed out, lodash/fp is less efficient at removing unused code than regular lodash.

For example, if you compare a bundle that just imports `lodash/fp/uniqueId` vs `lodash/uniqueId`, the fp version is 47kb and the regular version is 2.65kb.

This will involve replacing merge with a helper that respects immutability ([ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13254)).

**Comment by theodur** [comment]
This work has been completed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/1678.
