### ISSUE TITLE
[PM] Put QA spreadsheet test cases into TestRail

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#16809]
## Background
As part of the VSP process, it is necessary for the QA test cases to be entered into test rail.

## Tasks
- [x] Enter test cases into Test Rail
- [x] Review test cases with Tze

**Comment by mshea0606** [comment]
Test cases are in TestRail and staging user vets.gov.user+378@gmail.com has been created for Direct Deposit for Edu. cc @Samara-Strauss @tzelei

**Comment by Samara-Strauss** [comment]
Is there a link? I think user 378 probably works for most test cases, but there are a couple cases I can think of where we might need a different user. But I don't remember the exact cases we had, so it would be really helpful to actually be able to see what's in Test Rail.

**Comment by mshea0606** [comment]
Just reopened this. I realized I need to make changes to the test cases since we are eliminating the "Add" functionality for EDU direct deposit.  Also, I want to double check some staging users work. Once I make those changes I can post a Test Rail link in here and slack you my Test Rail login info.

**Comment by Samara-Strauss** [comment]
OK, sounds good to me!

**Comment by mshea0606** [comment]
https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc

**Comment by mshea0606** [comment]
Test cases have been updated and staging users have been added. Let me know if you have any questions @tzelei cc/ @Samara-Strauss
