### ISSUE TITLE
Content for Redirect Banner 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#16812]
As A Veteran who has landed on va.gov/debtman I would like to see a banner announcing the new va.gov/manage-va.debt site with URL 

Definition of done: 
1. Create content for banner
2. Get approval from DMC
3. Get approval from Peggy 
4. Give DMC final version to submit to eBenefits site admin

**Comment by 3obryandogs** [comment]
I have emailed Jill with the following preliminary draft:

A new online site - va.gov/manage-va.debt (hyperlink) - is now available from the Debt Management Center to help you learn more about your VA debt and how to repay it.

Please visit va.gov/manage-va.debt (hyperlink) for electronic versions of your VA debt letters and repayment request options. You can fill out your Financial Status Report (VA Form 5655) with step-by-step guides and helpful choices, and then submit it online. There also are answers to your frequently asked questions (FAQs) and ways to contact the Debt Management Center.

**Comment by leahkeeler** [comment]
This is complete and DMC has the working for banner
