### ISSUE TITLE
GIBCT Redesign: Create development sandbox

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16818]
As a developer, I need to create a sandbox for testing the CT redesign features so that the original Comparison Tool codebase is not filled with throw away code.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The sandbox is:
    a. Located at https://[environment].va.gov/gi-bill-comparison-tool-sandbox/
    b. The page is a placeholder page with the title: "CT Redesign Sandbox"
2. The page is configured to only be available in the DEV and Staging environments (NOT Production)

#### Technical Notes:
The path with gi-bill-comparison-tool is a config item. The folder is gi-sandbox. The virtual path will be set with configuration when we publish or test.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/8145

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15219

**Comment by delli-gatti-michael** [comment]
Tested by the following testrail test case

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
This is now showing on Staging at https://staging.va.gov/gi-bill-comparison-tool-sandbox/

![Screen Shot 2020-12-15 at 6.42.32 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d1498070-21d1-4db0-8af4-6f07fb863b46)
