### ISSUE TITLE
Documentation of Downtime Integration

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16816]
## User Story
As a developer it is important to understand the nuances of architecture, implementation, and its limitations. Please add documentation on what is and not included in the FormSystem's implementation depending on whether they are using SaveInProgress or not. It is also important to know what is might look like before pushing to production, please add pictures of the before alert, and currently down notification so developers and designers know what to expect.

## Expected Behavior / AC

Screenshots and frontend implementation notes added to: 
[Downtime Notification Docs](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications/)

**Comment by LinnJS** [comment]
This ticket is blocked due to Gatsby failing locally and in CI. Blocked till resolved by VSP Frontend Tools Team.

https://dsva.slack.com/archives/CBU0KDSB1/p1607027209029400

**Comment by ala-yna** [comment]
The changes look great, @LinnJS! Thank you for making it easier for future teams.
