### ISSUE TITLE
[Tech Debt] 526: Remove V1 In Progress Forms

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#16824]
## User Story
As a veteran, I do not want to get errors when I have an old in progress form that is no longer eligible for V1.

## Expected Behavior
No errors anymore (please reference this story for details #14174)

## Tasks
- [ ] Remove the V1 in progress forms the RDS

**Comment by annaswims** [comment]
We can find v1 forms by finding forms that have a veteran attribute.

https://github.com/department-of-veterans-affairs/vets-api/blob/6650cfba891587d0cc71fc937dd4d0e863d7043f/rakelib/form526.rake#L88

**Comment by annaswims** [comment]
InProgressForm.where(form_id: FormProfiles::VA526ez::FORM_ID).where("(metadata -> 'version')::text ='1'"). destroy_all

**Comment by annaswims** [comment]
v1 forms deleted
