### ISSUE TITLE
508-defect-3: [SCREENREADER]: Focus SHOULD go to H1 on the subway map page after the wizard

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#16826]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** Josh Kim

## User Story or Problem Statement

As a screen reader user, I expect the page title to be read to me when I navigate into a new page so that I know where I am.

## Details

Upon completing the wizard and clicking the apply button, the user will be taken to the subway map page where focus is placed on the first breadcrumb link "Home." Voice Over reads out, "Home, Link, Home" instead of the `h1` "Apply for Personalized Career Planning and Guidance."

This is similar to [this ticket for education benefits](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7519) @1Copenut identified earlier this year.

## Acceptance Criteria

- [ ] Set the focus to the page's `h1` instead of the first link in the breadcrumb

## Environment

* Operating System: Mac, Windows
* Browser: Safari, Firefox
* Screenreading device: VoiceOver (Mac), NVDA (Firefox)
* Server destination: staging,  production

## Steps to Recreate

1. [Go to the form 28-8832 wizard page](https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/introduction).
2. Start screenreading device listed in Environment.
3. Select dependent > yes > yes > apply.
4. Confirm focus is directed to the home link in the breadcrumb. 

## Solution (if known)

Set the focus to the `h1` on the page.

## WCAG or Vendor Guidance (optional)

* [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

## Screenshots or Trace Logs

<img width="732" alt="Screen Shot 2020-12-02 at 1 05 01 PM" src="https://user-images.githubusercontent.com/14154792/100914357-f2ed9400-34a0-11eb-8285-d12ccdf441ec.png">

**Comment by jason-gcio** [comment]
We are going to look into this more...seems like we are going to change the role of the `h1`?  Might need more clarification...

**Comment by joshkimux** [comment]
@jason-gcio More than happy to clarify! Basically, all we need to do is set the focus to the `h1` when the page loads. Currently, it's sending it to the breadcrumb, which isn't what we want. For another example, I'd recommend checking out [this ticket Trevor wrote.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7519)

**Comment by micahchiang** [comment]
Just tested and this has since been fixed. Closing.
