### ISSUE TITLE
Determine Root cause for disconnected Health services page 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16830]
## What happened?
The Pittsburgh health services page appears to be disconnected from Drupal on [Staging](https://staging.va.gov/pittsburgh-health-care/health-services/) and [Prod](https://www.va.gov/pittsburgh-health-care/health-services/). 

**This issue is to determine the root cause of this disconnection.** 

**Errors:**

- Page title should be "Health services", not "Patient and health services"
- Page is missing the intro paragraph
- Page is missing "In the spotlight" section

<details>
<summary> Screenshot from Staging </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/98831bad-28eb-4936-8742-89f815b2c1a2)

</details>

## Expected behavior
<details>
<summary> Expected behavior (seen on Erie devshop) </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b1040af9-b928-4091-843f-10138c48faba)

</details> 

## Acceptance Criteria
Root cause for the disconnection has been determined. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
The root cause of the missing spotlight section was https://github.com/department-of-veterans-affairs/vets-website/pull/15019. The graphql query fragment that pulls this data from drupal was removed accidentally.

The root cause of the title issue was https://github.com/department-of-veterans-affairs/vets-website/pull/14151. I'm not sure why this change was made.
