### ISSUE TITLE
Discovery: Review website performance 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1683]
# Problem 

- `vets-website` has no automatic or consistent web performance metrics or monitoring 

# Goal

- Determine current state of website performance and determine potential improvements to monitoring and performance 

# Potential tasks 

- evaluate the site performance using chrome dev tools 
- find / evaluate performance monitoring tools 
- review current performance monitoring tools (I think we capture some performance monitoring metrics in prometheus- I think it's the `window.performance` object from a low % of users. Keifer may know more) 
- identify quick wins (low effort / high impact) 

# Artifact 

- report on current website performance that focuses on the home page and top 2-3 landing pages 
- additional issues for work / discovery

**Comment by accbjt** [comment]
Here is a list of most visited pages on va.gov. These are the pages I will conduct my baseline performance tests with.

https://docs.google.com/spreadsheets/d/1LvHRWCqBJjJLxo12ENiaV0w6yHLiVonqkC0JzJ--Ow4/edit?usp=sharing
