### ISSUE TITLE
Facility v2 - Show path for facilities with online scheduling off

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16840]
## Issue Description
With the new flat list logic for the facility selection page, we need to provide a way for a Veteran to reach out to a facility if they don't see the one they are looking for.

---

## Acceptance Criteria

- [ ] Existing logic of possible facilities is maintained

- [ ] If online scheduling is off for any facility closer than first available, then display those under "Why isn't my facility listed" CTA

- [ ] When user clicks "Why isn't my facility listed" CTA, then show facilities less than 100 miles

- [ ] If unavailable facilities are listed, When the user clicks "use current location", Then the CTA collapses

- [ ] DESIGN - All desktop, tablet, and mobile designs match the spec:
* Note - use the V1 designs in this InVision spec: https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens

- [ ] ANALYTICS - Track "Why isn't my facility listed" clicks

- [ ] ANALYTICS - Track "Find a different VA location" clicks

**Comment by outerpress** [comment]
@jbalboni @laurenernest I added the spec, just a couple of notes:
* Use the screens marked as V1 in the Table of Contents (first screen in the prototype)
* The language hasn't been reviewed by @peggygannon yet so there may be changes to the instruction and tooltip
* I'll get tablet specs in there shortly, I don't think much will change for larger screen sizes though

**Comment by laurenernest** [comment]
@jbalboni Per the release timing discussion, I've added the 2 analytics events to the ACs. Please update the LOE estimate if necessary. I'm going to hold off on tracking the phone number clicks right now.

**Comment by jbalboni** [comment]
@laurenernest I think we need to confirm with the analytics folks what the events should be for those two clicks. This is what I came up with:

```
vaos-facilities-not-listed-click
vaos-facilities-not-listed-locator-click
```

The only other example I could find of tracking a facility locator click was within an alert box and it didn't make sense to follow that pattern.

**Comment by laurenernest** [comment]
Sounds good!

@bsmartin-ep We'll be adding these [events](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16840#issuecomment-740753474) for the highlighted links below. Let us know if you have any concerns or changes.
![Screen Shot 2020-12-08 at 9 18 28 AM](https://user-images.githubusercontent.com/72046525/101518468-cc16de00-3936-11eb-8c45-28c046c33388.jpg)

**Comment by laurenernest** [comment]
@marcynadeau I don't have a Prod account with a home address on file. Can you please grab a screenshot of this page for validation?

Testing account:
- Should have a home address saved in their profile
- Is registered at more than 1 facility (if possible)
- Nearest site registered at doesn't have online scheduling turned on for type of care selecting

Steps to get to page:
1. Go to https://www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment
2. Select type of care for VA facility
3. If prompted, select VA facility (not CC)
4. When /va-facility-2 page loads:

- get full page screenshot
- click "why isn't my facility listed?" and get screenshot of expanded content

**Comment by jbalboni** [comment]
@laurenernest I think I tested this in staging with judy.morrison. I changed her address through VA Profile to be something close to one of the sites.

**Comment by bsmartin-ep** [comment]
Apologies for the lateness @laurenernest @jbalboni .

These events work for me.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/16840#issuecomment-740779195
