### ISSUE TITLE
BigQuery SQL Update for Scrubbing Address Data and Null Handling for Facility Locator Event Action

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#16849]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
Clean-up facility locator event actions to improve data consistency of null data layer variables 

## Acceptance Criteria
- [ ] Replace address exposure and null data layer variables with `(not set)` in event action 
- [ ] Execute SQL update to replace existing event actions with `(not set)` 
- [ ] Backfill any DOMO Facility Locator datasets
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
GTM Workspace: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000400

**Comment by jonwehausen** [comment]
Relating to #15000 in case @bsmartin-ep and @JasonTheBearded you guys think handling the historical data within the view is a better approach.

**Comment by JasonTheBearded** [comment]
Script is in testing. Additional refinements needed to handle odd entries. Once done and QA complete, will be creating a temporary backup of prod tables prior to the scrub in the event there are any errors during the scrub.

**Comment by jonwehausen** [comment]
Thanks again for all of your work here @JasonTheBearded 

I QA'ed various days within BQ and confirmed address data has in fact been removed. 

### 11/02/2020
![image](https://user-images.githubusercontent.com/48527022/103784463-faf0a480-5007-11eb-9508-f5c746ee8149.png)

### 11/10/2020
![image](https://user-images.githubusercontent.com/48527022/103784572-19ef3680-5008-11eb-88b2-29f516b54c2b.png)

### 11/12/2020
![image](https://user-images.githubusercontent.com/48527022/103784699-4440f400-5008-11eb-9e04-94a53e4c0163.png)

### 11/30/2020
![image](https://user-images.githubusercontent.com/48527022/103784915-8b2ee980-5008-11eb-89e8-038674fd1fb0.png)


Closing this issue! cc: @joanneesteban @bsmartin-ep for visibility
