### ISSUE TITLE
Active Appeals detail | Current status

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16858]
## User Story
As a user, I want to know the current status of my appeal.

## Acceptance Criteria
1. On each Appeal detail page, include a new list item called Current Status
2. Content within this ListItem is API-driven (including the header / subtext) 

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/438003927/preview#project_console

## Accessibility Guidelines
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Acceptance Criteria
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Appeal" as Header 1
- Mark "Current status" as Header 2
- Mark "Your hearing has been scheduled" as Header 3

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
@bridgethapner @jperk51 will an active appeal always have a 'current status'? if so, can we expect that this status always have 2 parts like it does in the InVision screen (i.e. a header summary - 'Your hearing has been scheduled', and the description below it)?

![Screen Shot 2020-12-02 at 5.43.04 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/1235f146-94ca-4a80-a4a3-ea52fe384512)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
12/29/2020 - Content is still mock data and not API driven. Retest.

**Comment by digitalken** [comment]
PASS 1/13/2021 - Moving to Design QA.
