### ISSUE TITLE
Access for Darius Dzien

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#16855]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Darius Dzien
- Please Provide your email.
   > darius.dzien@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Testing Team, Software Engineer/QA Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDACP3EVFbNR4HuByUucN8lqvBqoFsILG+T5sgMAcH6bvATItxSI39v4jPbkAwDS8rYlEUM89Q75KHi6Ff0jaGyleAMU+N5BTaaznLzD4s9/z74gOc0zg/j6pUeRHhBLQM7svnybzPnMVZNfuADgYb/J5A/ejhU9qQlVB2IxhaysGgcCBryyDkK/1S3LU1MdWnS8xeM+PFgbKLKYTEjA+jL0iwynntTnpt6TKhxhSVHB89+JGUG0bns0QZbgctN4gkwIlCi0Qbgn6yUvgH60LHsX1U3WwszhvlqsOGszrLFIuR7r9u11vqvn07ZX6oYOevh3SW9TDbEpHu5UGAw27B5DQ1OBzI5n1FhbBy7+XqIGtG4fgTR9vVO/zd124PfGxsZ/JAbuDPGVT9GnKKbb8tWUe/p6Qz0qEcBegCUHNfQ3bUXbcDbRKaPMQMvNCRaHZRlDhEpVwY6PIp8x8VpoKcScGXIvzbA3JRXccb2d9pn8qTTvnuP+CMz9nSGTB02xD0= dariuszdzien@Dariusz-Dzien-Macbook.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by pjhill** [comment]
@ddzz -- I take it that at this point you have verified your SOCKS access.  If you're good to go with the SOCKS proxy then please close this ticket when you can.
