### ISSUE TITLE
Active Appeals detail | Status/issues segmented selector

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16857]
## User Story
As a user, I want to view my appeals details in two distinct sections (Status/Issues) so it's easier to reference

## Acceptance Criteria
1. At the top of each Appeals detail page, create a list item called "[Type] appeal"
2. Display when the appeal is most up-to-date
     - Format: Up to date as of [Month, XX, XXXX] at [00:00] [a.m./p.m.] [Timezone]
3. Pull in the segmented selector common component
     - "Status" (default) and "Details" are two different segmented tabs that each display a unique list of list items below

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/438003927/preview#project_console

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Appeal" as Header 1
- Mark "[type] appeal" as Header 2

**Segmented Selector**
- accessibilityLabel=Name of tab (e.g. Status or Details)
- accessibilityHint="view your appeal___" (e.g. status or details)
- accessibilityRole="tab"
- Denote selected vs. unselected
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 1 of 2 or 2 of 2)

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 12/28/2020 - With minor bug written on accessibility for segmented selector not announcing position 1 of 2, 2 of 2.
Bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17896

Moving on to Design QA.

**Comment by lexicalninja** [comment]
Once the build with the increased font heights get to QA, we will want to review this component with QA and design because the font/line hight increase has increased the height of the element and we should reduce the height down while keeping the touchable area above 44px
