### ISSUE TITLE
Determine baseline usage for Platform Newsletter

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16869]
## Issue Description
To move towards this O4KR3,
> By Jan 2021, usage metrics are tracked and targets have been established for 5 VSP platform products or services				
we need to understand the baselines for current usage to set initial targets. 

As VSP Product Managers, we also want to start understanding how our own products are being used and eventually set KPIs and KRs for our own services.

---
## Tasks
- [ ] Determine & document the Median (or Average, if not possible) of the monthly Platform Newsletter usage. [Usage tracked here](https://us19.admin.mailchimp.com/reports/#t:campaigns-list). Please document in [column D on the tracker.](https://docs.google.com/spreadsheets/d/1jyIxQAystapzDZ8gRkN4yBtruUsnRKvpjovLatHwgr4/edit#gid=1885541117)

## Acceptance Criteria
- [ ] VSP and DEPO knows the usage targets for Platform Newsletter so that we can understand how often VFS teams are using our products and how we can improve

**Comment by rebekahickey** [comment]
Platform Newsletter performance metrics including monthly average open & click rates documented and tracked here: https://vfs.atlassian.net/wiki/spaces/PPS/pages/1717665795/Platform+Newsletter+Performance+Metrics

**Comment by Khyatinp18** [comment]
2/16/2022:

Closing this since platform deprecated the News letter.
