### ISSUE TITLE
Active Appeals detail | Appeals ahead of you

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16860]
## User Story
As a user, I want to know the current status of my appeal.

## Acceptance Criteria
1. On each Appeal detail page, include a new list item called "Appeals ahead of you"
2. Content within this ListItem is API-driven and displays a number 
     - Format: [XXX,XXX,XXX]

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/438003927/preview#project_console

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "appeals ahead of you" as Header 3
- Ensure the number of appeals is read by the screen reader as XXX,XXX,XXX and not as individual numbers 

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
## User Story
As a user, I want to know the current status of my appeal.

## Acceptance Criteria
1. On each Appeal detail page, include a new list item called "Appeals ahead of you"
2. Content within this ListItem is API-driven and displays a number 
     - Format: [XXX,XXX,XXX]

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/438003927/preview#project_console

## Accessibility Guidelines

## Accessibility Acceptance Criteria

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by msmanak** [comment]
Content within this ListItem is API-driven and displays a number
Format: [XXX,XXX,XXX]

_how will it be announced? Do we have guideline for this?_

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS on Android, waiting on iOS.  1/13/2021

**Comment by digitalken** [comment]
PASS 1/14/2021 on both Android and iOS.  Closing.
