### ISSUE TITLE
Access for Kathleen Crawford

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#1686]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Kathleen Crawford
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > vsa-eBenefits, Backend Engineer, GovernmentCIO
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIHrx7Jd0A+O+YVvngtlk/6kUMOWnYajor8Z0zJr92zxf1zSbKTmIZivyYgo8Mc1dGu+k558V6wUt+8z03mPocmmKLLl4eQD3PgqkfMvpEtEDH1LQm20QOOzjeQA/ROxRCi2YMsRRPYQZNkHtPqUDDo1rqO1sIv6E4bhqZWj+qawB94c/SLf7P+97HPQEUI2VboyygV/jJH2cPJYDQpvRwsKoy5ovF5MtSBcuNxcuESklVefm171s9D95M6EzyQepYCzItJSn8KKltQlOVn7VmkZGdVBnehcmXW8trwX46Hu3xGQSJhg/enegD6JPp3sKvRNenhhVmLrj4Uy+uIikv kathleencrawford@USRMonitors-MacBook-Pro.local

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

FYI @department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Kathleen Crawford

**Comment by Jeff-Hayter** [comment]
@tskinn @ricetj Confirmed, please grant AWS access.
