### ISSUE TITLE
Promo block text in health care global menu is getting cut off

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#16862]
On Chrome: On the global nav > Health care fat nav > promo block

The text in the promo block is cut off at the bottom. Screen shot shows when browser is at 100% font size: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/77b88a2e-f18b-4c50-b5ac-c0946e3f710b)

I can't tell whether this is due to the FE using incorrect font in the promo area -- it doesn't look like our normal font, but may need a designer to verify.

**Comment by jenniferlee-dsva** [comment]
@andaleliz - could you validate whether the font that's being used in the promo block (the text that's getting cut off in the screenshot ^) is our standard font?  It looks different and maybe that is why it's suddenly getting cut off?   

(This component has a character limit, so authors can't enter more text than the max allowed.)

**Comment by jenniferlee-dsva** [comment]
Comparing it to the font used in body copy, it def looks different to me: 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/4e960f50-0bab-4bc1-9a87-0367e9132d9b)

**Comment by andaleliz** [comment]
Looking at the CSS, the font  family and line heights are the same in both `<p>` tags (promo spot and body copy).  Has the copy changed? Are we certain it wasn't cut off before and no one caught it? I tried looking at the wayback machine but for some reason our nav isn't captured there.

I do see some strict height declarations in the CSS that could be tweaked to allow for this greater height, but I think it would impact the nav across the board.  The FE devs could speak better to what might be able to be done there, if the copy can't be reduced.

<img width="500" alt="Screen Shot 2020-12-03 at 9 19 00 AM" src="https://user-images.githubusercontent.com/55992116/101042258-fb9aa480-354a-11eb-813b-ac11a932ed97.png">
<img width="500" alt="Screen Shot 2020-12-03 at 9 17 59 AM" src="https://user-images.githubusercontent.com/55992116/101042265-fdfcfe80-354a-11eb-88f0-faf022aa3909.png">

**Comment by ncksllvn** [comment]
The promo block in the menu is using the same font family as the rest of the page. The only difference I can tell from the web inspector is that promo block has larger line-height. That's all I can tell anyway.

As for the text getting cut off, we have a hardcoded value for the menu's height when expanded. We have incremented it overtime as we have made promo blocks with longer content. Ideally the menu would expand to the right height automatically but it's a complex component and wasn't built that way. So if we want longer content there now we just need to let a FE dev know to bump the value some more.

![image](https://user-images.githubusercontent.com/1915775/103555870-ea60f280-4e7e-11eb-8c8e-f3608a16d0f7.png)

**Comment by ncksllvn** [comment]
It looks like that promo block's content has changed since this ticket was opened so I think we are okay now

![image](https://user-images.githubusercontent.com/1915775/103556535-eaadbd80-4e7f-11eb-8e99-430eb0f9d1dc.png)

**Comment by ncksllvn** [comment]
In summary this ticket may have no action items so I think we are safe to close.

**Comment by ncksllvn** [comment]
cc @brianalloyd

**Comment by brianalloyd** [comment]
Thanks @ncksllvn after looking at it I totally agree as it looks like the blocks have changed since ticket was open.  Closing now in support.  Thanks.
