### ISSUE TITLE
Active Appeals detail | Past events expand/collapse

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16863]
## User Story
As a user, I want to reference a record of when the VA updated my appeal.

## Acceptance Criteria
1. On each Appeal detail page, pull in the expand/collapse common component with the title "View past events"
    - This section is collapsed on default
2. Pull in Appeal Step Table CC. Display list of events, from oldest to newest
     - Each event has a description (bold) and description below it with an associated date
3. Display completed step icon (green circle with check) the left of each event

Related ticket: Appeals Step Table Common Component ([#17296](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17296))

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/438003926/preview#project_console

![claims completed step.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/da70dd6f-0afd-4ab5-ada3-e0b1b0c3c7c5)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Appeal" as Header 1

**View past events component**
- accessibilityLabel="view past events"
- accessibilityHint="view a list of your appeal's past events"
- accessibilityRole="spinbutton"
- accessibilityState= "collapsed"
- Denote when dropdown is expanded
- Ensure dropdown area does not "trap" the keyboard focus

**Appeal Step Table** 
- For each step item: 
     - accessiblityLabel= Text 
- For each item in the table, let the user know the element in the list which is currently being focused and its place in the list

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
