### ISSUE TITLE
General Analytics Request for [Facilities]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#16861]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
**Who is this request for?**

- Michelle Middaugh

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - Facilities
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
Change noticed in November 2020

## Analytics to Track Down

- [x] The rate of search refinements for cc_provider was significantly higher in November (37.08) than the previous averages. (The rate was 6.43 in October)...is this related to the change in the definition?
- [ ] Seeking clarity on **Facility Locator - Search Timing - by Date and Facility Type 2.0** graph on the Dashboard. The "Community Care" line skyrockets in October but then seems to end, along with the line representing "All facilities"
 - [x] What timeframe is represented by **Foresee - Average Score by Facility Type**?

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
[DOMO](https://va-gov.domo.com/page/444997301)

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bmcgrady-ep** [comment]
_The rate of search refinements for cc_provider was significantly higher in November (37.08) than the previous averages. (The rate was 6.43 in October)...is this related to the change in the definition?_
- [Search Refinement % for cc_provider in GA](https://analytics.google.com/analytics/web/#/report/content-site-search-search-terms/a50123418w177519031p184317761/_u.date00=20200201&_u.date01=20210228&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.searchKeyword:cc_provider&explorer-graphOptions.selected=analytics.nthMonth&explorer-graphOptions.primaryConcept=analytics.percentSearchRefinements)
- [Total Unique Searches for cc_provider by month](https://analytics.google.com/analytics/web/#/report/content-site-search-search-terms/a50123418w177519031p184317761/_u.date00=20200201&_u.date01=20210228&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.searchKeyword:cc_provider&explorer-graphOptions.selected=analytics.nthMonth&explorer-graphOptions.primaryConcept=analytics.searchUniques)

As you can see in the two reports above, search refinement % in the dashboard is consistent with the data in Google Analytics. Also, the total unique searches for cc_provider has drastically dropped correlating with the search refinement % going up.

_Seeking clarity on Facility Locator - Search Timing - by Date and Facility Type 2.0 graph on the Dashboard. The "Community Care" line skyrockets in October but then seems to end, along with the line representing "All facilities"_
- I am researching this question a little further. Thank you for the patience.

 _What timeframe is represented by Foresee - Average Score by Facility Type?_
-  Date range is December 2019 - March 2020, so this needs to be updated with the most recent data.

**Comment by mmiddaugh** [comment]
Thanks @bmcgrady-ep I realized the label for Community Care provider changed from `cc_provider` to just `provider` which is why the numbers seemed to change so dramatically.

**Comment by bmcgrady-ep** [comment]
Happy to help @mmiddaugh! [Here](https://va-gov.domo.com/page/1129885232?userId=1831017214) is the new Domo dashboard for Facility Locator based on BigQuery. Let me know if you have any questions.

**Comment by bmcgrady-ep** [comment]
Closing out this issue, but feel free to reopen with any questions.
