### ISSUE TITLE
1990e: Form Content Updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16877]
As a developer, I need to update the 22-1990e form so that it is consistent with DEPO recommendations and other Education Services forms.

## Assumptions:
1. This update does not require a feature or prod flag; story will be merged at the beginning of the day for staging review prior to afternoon production deployment.
2. The 1990e is located here: https://staging.va.gov/education/apply-for-education-benefits/application/1990E/introduction
3. The content updates are based on the DEPO form labels here: https://design.va.gov/patterns/form-labels

## Acceptance Criteria
1. The following chapter titles are sentence case:
    a. Applicant information
    b. Benefits eligibility
    c. Sponsor information
    d. Education history
    e. Employment history
    f. Program selection
    g. School selection
    h. Personal information

2.  In Chapter 3:
    a. 
    > Sponsor first name
    
    is replaced with
    
    > Sponsor's first name

    b. 
    > Sponsor middle name
    
    is replaced with
    
    > Sponsor's middle name

    c. 
    > Sponsor last name
    
    is replaced with
    
    > Sponsor's last name

    d. 
    > Sponsor suffix
    
    is replaced with
    
    > Sponsor's suffix

    e. 
    > Sponsor Social Security number
    
    is replaced with
    
    > Sponsor's Social Security number

    f. 
    > Sponsor file number
    
    is replaced with
    
    > Sponsor's VA number

    g. 
    > Sponsor Branch of Service
    
    is replaced with
    
    > Sponsor's Branch of Service

    h. 
    > Sponsor address
    
    is replaced with
    
    > Sponsor's address

3. On the submission confirmation page:
    a. 
    > Claim received
    
    is replaced with
    
    > We’ve received your application.

    b. The padding above "Education Benefit Claim (Form 22-1990E)" on the confirmation submission screen is reduced.  (Ex. the 10203 has the class vads-u-margin-top--0; per UX 23px is the appropriate amount of space).

    c. 
    > Education Claim (Form 22-1990E)
    
    is replaced with
    
    > Education benefit application (Form 22-1990E)

    d. The content in the "What happens after I apply?" section is:
    > We usually decide on applications within 30 days.
    > 
    > You’ll get a Certificate of Eligibility (COE) or decision letter in the mail. If we’ve approved your application, you can bring the COE to the VA certifying official at your school.
    > 
    > [Learn more about what happens after you apply](https://staging.va.gov/education/after-you-apply/)

    e. The "Need help?" section style matches DEPO patterns (see SA2).
    f. The confirmation page layout and styles match that as shown in SA#1

## Supporting Artifacts:
1. [Confirmation Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f1a746bfe60dd676dca3865056a4249ead1b4c4d/products/education-careers/application/1990e/1990e-outline-draft.md#form-title-apply-to-use-transferred-education-benefits) as of 12/03.

2. For AC 3:
![image](https://user-images.githubusercontent.com/48260534/101051909-03127b80-3554-11eb-92fd-0373337460b7.png)

    a. Example of AC3b:
<img width="1153" alt="1995-confirmation-padding" src="https://user-images.githubusercontent.com/48260534/100279202-14e09700-2f34-11eb-8faa-0acd29527c96.png">

    b. Example for AC3e:
<img src="https://user-images.githubusercontent.com/48260534/100746700-0f110880-33af-11eb-9a0c-9e129f9fcde1.png">

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15301

**Comment by delli-gatti-michael** [comment]
Tested by testrail test case:
https://dsvavsp.testrail.io/index.php?/tests/view/27168

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me!

**Comment by watersemma** [comment]
UX Review 2/2: Looks good!

**Comment by delli-gatti-michael** [comment]
Closing this out
