### ISSUE TITLE
1990n: Form Content Updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16879]
As a developer, I need to update the 22-1990n form so that it is consistent with DEPO recommendations and other Education Services forms.

## Assumptions:
1. This update does not require a feature or prod flag; story will be merged at the beginning of the day for staging review prior to afternoon production deployment.
2. The 1990n is located here: https://staging.va.gov/education/apply-for-education-benefits/application/1990N/introduction
3. The content updates are based on the DEPO form labels here: https://design.va.gov/patterns/form-labels

## Acceptance Criteria
1. The following chapter titles are sentence case:
    a. Applicant information
    b. Benefit selection
    c. School selection
    d. Personal information

2.  In Chapter 1:
    a. 
    > Type of service (Active duty, drilling reservist, IRR, etc.)
    
    is replaced with
    
    > Type of service (Active duty, drilling reservist, National Guard, IRR)

3. In Chapter 3:
    a. 
    > Education or career goal (for example, “Get a bachelor’s degree in criminal justice” or “Get an HVAC technician certificate” or “Become a police officer.”)
    
    is replaced with
    
    > Education or career goal (For example, “I want to get a bachelor’s degree in criminal justice” or “I want to get an HVAC technician certificate” or “I want to become a police officer.”)

4. On the submission confirmation page:
    a. 
    > Claim received
    
    is replaced with
    
    > We’ve received your application

    c. 
    > Education Claim (Form 22-1990N)
    
    is replaced with
    
    > Education benefit application (Form 22-1990N)

    c. The padding above "Education Benefit Claim (Form 22-1990N)" on the confirmation submission screen is reduced.  (Ex. the 10203 has the class vads-u-margin-top--0; per UX 23px is the appropriate amount of space).

    d. The content in the "What happens after I apply?" section is:
    > We usually decide on applications within 30 days.
    > 
    > You’ll get a Certificate of Eligibility (COE) or decision letter in the mail. If we’ve approved your application, you can bring the COE to the VA certifying official at your school.
    > 
    > [Learn more about what happens after you apply](https://staging.va.gov/education/after-you-apply/)

    e. The "Need help?" section style matches DEPO patterns (see SA2).

    f. The confirmation page layout and styles match that as shown in SA#1

## Supporting Artifacts:
1. [Confirmation Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a15352194357da9ba98522a2d062404e1deb0527/products/education-careers/application/1990n/1990n-outline-draft.md#form-title-apply-for-education-benefits-under-the-national-call-to-service-program) as of 12/03.

2. For AC 4:
![image](https://user-images.githubusercontent.com/48260534/101056294-d2811080-3558-11eb-9d82-32147bf77feb.png)

   a. Example of AC4b:
<img width="1153" alt="1995-confirmation-padding" src="https://user-images.githubusercontent.com/48260534/100279202-14e09700-2f34-11eb-8faa-0acd29527c96.png">

   b. Example for AC4e:
<img src="https://user-images.githubusercontent.com/48260534/100746700-0f110880-33af-11eb-9a0c-9e129f9fcde1.png">

**Comment by zurbergram** [comment]
AC3 is in https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/pages/schoolSelection.js#L30

This will affect
- 1990
- 1990e
- 1990n
- 5490
- 5495

**Comment by zurbergram** [comment]
AC2 is in https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/definitions/toursOfDuty.jsx#L82


This will affect
- 1990
- 1990n
- 1995
- 5490
- 5495

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15241

**Comment by delli-gatti-michael** [comment]
Local testing complete
Tested by testrail test case:
https://dsvavsp.testrail.io/index.php?/tests/view/26956&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by watersemma** [comment]
UX Review 1/2 this checks out for me!

**Comment by JenLJ** [comment]
UX Review 2/2:  This checks out for me also!

**Comment by delli-gatti-michael** [comment]
Closing this out
