### ISSUE TITLE
1990e: Add ability to print confirmation page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16878]
As a veteran, I need the ability to print the confirmation page of my 1990e form submission so that I can have it for my personal records.

## Assumptions:
1. This update does not require a feature or prod flag; story will be merged at the beginning of the day for staging review prior to afternoon production deployment.
2. The 1990e is located here: https://staging.va.gov/education/apply-for-education-benefits/application/1990E/introduction

## Acceptance Criteria
1. The user has the ability to print the confirmation page.
    a. The button is located between the "We've received your application" content and the blue submission details box.
2. The printed page layout and styles match that as shown in SA\#1.

## Supporting Artifacts:
1. [sample-print-confirmation.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5667918/sample-print-confirmation.pdf)
2. [Confirmation Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f1a746bfe60dd676dca3865056a4249ead1b4c4d/products/education-careers/application/1990e/1990e-outline-draft.md#form-title-apply-to-use-transferred-education-benefits) as of 12/03.

**Comment by ksantiagomorgan6** [comment]
pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/15360

**Comment by delli-gatti-michael** [comment]
Local testing complete

Tested by testrail test case:
https://dsvavsp.testrail.io/index.php?/tests/view/28369&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on Staging and ready for review

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me

**Comment by amyknox** [comment]
UX review: 2/2 Printer friendly page looks great to me. 

This form 1990E has "Sponsor's Branch of Service" which should be "Sponsor's branch of service" but that's not what this story covers.
