### ISSUE TITLE
BE | Set up Datadog Alerts for 10-10CG 

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16875]
## User Story

As a team member or stakeholder of the 10-10 apps, I want to be able to be notified quickly and understand what technical errors are occurring so that we can address appropriately.

## Expected Behavior

- Add alerts in Slack that describe in non-technical terms any errors that cross a pre-defined threshold
- Send alert to the 1010 Team slack channel 

## Acceptance Criteria

- [x] Alerts are set up for production issues only
- [x] Messaging can be understood in non-technical terms

## From original ticket:
Resources
- https://dsva.slack.com/archives/CLXEU7Z17/p1611862006012400
- https://sentry.io/resources/alert-rules/

**Comment by ala-yna** [comment]
On hold: waiting for Platform to release documentation on setting up Sentry 10/alerts.

**Comment by ala-yna** [comment]
Closed https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6703 in favor of this one.

**Comment by mlighdc** [comment]
@ala-yna why was this not added back to Sprint 37 or 38?

**Comment by SKasimow** [comment]
@lihanli fyi

**Comment by SKasimow** [comment]
Hi @lihanli - could you point this?

**Comment by lihanli** [comment]
i think this is done, the alerts are here: https://app.datadoghq.com/monitors/manage?q=team%3Avsa1010
