### ISSUE TITLE
Refactor/flatten 10-10CG UI schema

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#16874]
## User Story

As a developer it is hard to track the context of data through the 10-10CG due to so many references in other files. Simplify this flow by only abstracting shared definitions, and flatten the constant definitions so they are less nested and are easier to read with out linter configuration. This way it will be easier to maintain and refactor in the future.

## Expected Behavior

The form should function exactly the same with the only difference being more clean, readable, and maintainable code.

## Acceptance Criteria

- [x] There is no regression in form functionality
- [ ] Constants are no longer nested
- [x] Only shared UI definitions are abstracted in another file.

**Comment by mlighdc** [comment]
This will not be done as part of Sprint 37.

**Comment by LinnJS** [comment]
Just opened a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16058) for this ticket

**Comment by ala-yna** [comment]
Hey @LinnJS - I looked through the RI and compared it to what we have in Production. Looks good to me.
