### ISSUE TITLE
Usability Testing Prep [Caregiver - 10-10CG Additional flow]

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#16881]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [x] Attach all artifacts before requesting the meeting
- [ ] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] Shira to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] Usability Testing Prep review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on **feature name**
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md)
- Link to [Staging](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)
- Link to or attach artifact with copy (if separate from prototypes/mockups): N/A 
- Link to [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/Usability-Test-Dec-2020/conversation-guide.md) and script [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/1010cg-mvp/Usability-Test-Dec-2020/conversation-guide.md)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from **Caregiver team**
- Product Manager (required): **Alayna Abel**
- DEPO product lead (required): **Ming Ligh**
- Anyone else from your team who significantly contributed to the artifacts provided (required): **Jonathan Nelson**
- Other specialists: 

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira will reach out as needed_

Preferred meeting time: **Mon, December 7, 3:30pm – 4:00pm**

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by emilywaggoner** [comment]
Hey @jonathanjnelson! Would you mind specifying what the additional flow is? What page does it start on? What selections should be made to trigger the new flow? Where does it end? Etc. (Just want to make sure we are focusing the review on the part of this that's new.) Thank you!

**Comment by shiragoodman** [comment]
@ala-yna when are you planning to do Usability Testing? Since test cases won't be ready until mid next week (per @tlei123), I think it might make sense to move this out to next Thursday 12/10.

**Comment by jonathanjnelson** [comment]
Hello @emilywaggoner! The addition to the form is the page with (see below) - _Would you like to add a Primary Family Caregiver?_ This will allow the user to skip adding primary caregiver information and just add secondary caregiver information to the form. The page lives after the Veteran information. There has been no other design/code changes to the form. We simply want to make sure the addition of the question/page will not be confusing for users and want run a usability test. 

I will be happy to provide an updated user flow. 

![Screen Shot 2020-12-04 at 5 17 29 PM](https://user-images.githubusercontent.com/58444931/101224575-a21e9c80-3654-11eb-86b5-5ac30907a915.png)
