### ISSUE TITLE
Candidate Address Validation Design Work

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1688]
*Historical reference of the first draft of this flow.* 

*- [11339] (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/11339)*

-----------------------------------------------------------------------------------
@artistgreen will upload his UX documentation to this ticket. 

## User Story  

As an UX designer, I need to create UX mock up so the copy team can validate/suggest any content changes needed to finalize the UX designs.

## Goal  

 Have the content/copy team to validate or suggest verbiage to finalize the UX design mock ups. 

.......

## Definition of Done  

- [x] Content team has reviewed the mock ups. 

- [x] Necessary changes/suggestions were made.

- [ ] *This relates to epic ticket #1287 *Check the box below when this has been completed and comment "done".

**Comment by artistgreen** [comment]
Notes from Design/Technical Discovery Meeting w/ @lihanli @erikphansen and @mojaray2k :

We don't have definitive idea of what will be returned for addresses from Vet360
Lihan is waiting on authorization for his API Key requests to be able to determine what is returned
We know Vet360 can return up to 10 address suggestions but are asking the question: 'how may suggestions should we show?'
Based on Lihan's technical discovery, we will know if the returned suggested addresses will be in any order (e.g., order of confidence score)
Erik made the suggestion to visually call out any suggested address differences from the user entered address

**Comment by artistgreen** [comment]
Revision 1 screenshots

![image](https://user-images.githubusercontent.com/53535009/65257256-f29cef00-dace-11e9-9975-22246566bbc7.png)

![image](https://user-images.githubusercontent.com/53535009/65257282-faf52a00-dace-11e9-993a-1bb5e57e9556.png)

![image](https://user-images.githubusercontent.com/53535009/65257290-00eb0b00-dacf-11e9-95b3-0531207f9029.png)

![image](https://user-images.githubusercontent.com/53535009/65257301-06485580-dacf-11e9-8791-90f5b8fea373.png)

![image](https://user-images.githubusercontent.com/53535009/65257315-0cd6cd00-dacf-11e9-8e09-1c56ad7bf540.png)

![image](https://user-images.githubusercontent.com/53535009/65257337-12ccae00-dacf-11e9-8c69-26461bc1727d.png)

![image](https://user-images.githubusercontent.com/53535009/65257358-18c28f00-dacf-11e9-9bea-fe0b2732010c.png)

![image](https://user-images.githubusercontent.com/53535009/65257383-20823380-dacf-11e9-8235-b2d870c71ac4.png)

**Comment by artistgreen** [comment]
Desktop screens - Revision3

![Edit Address Overlay.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/487ab1b9-f261-4a10-aa8d-0aa4d00e74b9)

![Address not recognized - 1.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/ee5858ff-6bba-4531-be2a-0094242146ef)

![Address not recognized - 2.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/707e6dd7-1da7-4732-bcb9-83f9a2dfe5cf)

![Address not recognized - No suggestions.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/b51af16f-6c01-4cb4-add7-65e78ee6a899)

![Address selected update.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/c01ed675-f6c2-4666-a19b-40de83624d36)

![Updated profile.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/8315f122-d440-4bc7-ac52-e1de2c4cfa3a)

**Comment by artistgreen** [comment]
Mobile Screens - Revision3

![Profile.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/a78f1939-fa0b-4b23-b9c0-e5a8a13d2f5e)

![Edit Address Overlay.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/8beca6ca-1751-4626-b396-77e1127aaeb5)

![Address not recognized - 1.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/e625074e-f7c4-4590-bbf7-5c8013e70d6b)

![Address not recognized - 2.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/4d926bc4-8592-4696-b10e-0e90c4ceaacb)

![Address not recognized - No suggestions.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/399c53d8-d9a0-48d6-880f-4a325423140e)

![Address selected updated.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/e7abe342-1591-4f37-a594-10703eee3c1e)

![Updated profile.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/035dee82-c20d-457a-bcaa-ae93a994b4af)

**Comment by artistgreen** [comment]
@Justin-Pickett @erikphansen 

Discussion notes from @lihanli  technical discovery regarding Vet360's Address Validation API:

-  API will always return 1 suggestion, even if the entered address is 100% correct (We do not want to show the correct address and have the user confirm, we just want to update the address in this case)
- API returns suggestions based on 'Confidence Score'
- API has a 'County' field (We do not display a county field in the UI, more for FYI)

**Comment by Justin-Pickett** [comment]
@meganhkelley Please review the above screenshots that @artistgreen has uploaded into this ticket. We need a content review of the language in the screenshots above. Please let us know if there is anything else that is needed on our end.

**Comment by erikphansen** [comment]
@artistgreen just to clarify, isn't it also possible for the API to return 0 suggestions if it can't find anything close to what the user entered?

**Comment by artistgreen** [comment]
@erikphansen  - yes, I edited my entry regarding the technical discovery - thank you!

**Comment by peggygannon** [comment]
@Justin-Pickett Hi, Justin. Taking a look at this ticket. Can you let me know which screens I need to review? Is it the Mobile revision screens? Do the ones above also need to be reviewed or are the mobile ones the most recent?

**Comment by Justin-Pickett** [comment]
@peggygannon , Yes the mobile revision screens and the web versions above as well need review. Thank you.

**Comment by peggygannon** [comment]
@Justin-Pickett OK, thanks. I will have my feedback to you tomorrow.

**Comment by peggygannon** [comment]
@Justin-Pickett Please see below for my recommended content updates for the address validation screens. Please let me know if you want to discuss any of my recommendations over the phone. Thx! 


**Desktop screens**
*Edit address overlay*
Please sentence case all labels: Street address
Please change Zip code to Postal code
Please update character message to: (Maximum 5 characters)

*Mailing address in-line error*
Please update to:
We're saving your new mailing address. Your new address will show on your profile once it's been updated. 

*Error message box at top of page*
Please update to:
**We couldn’t update your profile**
We're sorry. Something went wrong on our end and we couldn't save the update to your profile. Please try again.

*Error message (inline)*
We couldn't save the update to your mailing address. Please try again.

*Address not recognized message*
Please update to: 
**Your address update isn’t valid**
We’re sorry. It looks like the address you entered isn’t valid. Please enter your address again or choose a suggested address below. 

Edit address link should be sentence-case: 
Edit address
also, where does this link go to? 

Suggested Addresses should be sentence-case: Suggested addresses

Please update: You have selected this address header TO: 
**We'll use this address**

**Comment by Justin-Pickett** [comment]
@peggygannon thank you for the revisions. 

@artistgreen please see the recommended changes above. Please update the ticket when these have been corrected. Thank you.

**Comment by artistgreen** [comment]
@peggygannon - Thank you!

I have updated the necessary screens with your copy/changes.

![Edit Address Overlay](https://user-images.githubusercontent.com/53535009/66676823-5c279d80-ec36-11e9-9926-d6e372d812f7.png)

![Address not recognized](https://user-images.githubusercontent.com/53535009/66676838-65186f00-ec36-11e9-924b-3dc1f584dd49.png)

![Address selected update](https://user-images.githubusercontent.com/53535009/66676890-795c6c00-ec36-11e9-88d6-cae4ef499be1.png)

![Mailing address update messaging](https://user-images.githubusercontent.com/53535009/66677023-c7716f80-ec36-11e9-96f0-fb32bcbf71dc.png)

![errors messaging at top and inline](https://user-images.githubusercontent.com/53535009/66676960-ac066480-ec36-11e9-825f-aed9b654cb2e.png)

**Comment by Justin-Pickett** [comment]
@artistgreen has made the revisions for the candidate address design work per @peggygannon suggestions. 

Next steps, @artistgreen  will complete the conversation guide and research plans.

**Comment by peggygannon** [comment]
@artistgreen Updated screenshots look good. Just one more tweak; please be sure all the headers are sentence-cased. There is one screen above where Edit Mailing Address should be changed to:

Edit mailing address

cc @Justin-Pickett

**Comment by artistgreen** [comment]
@peggygannon - Thank you!!  I will make that last edit - good catch and thanks again!

**Comment by artistgreen** [comment]
@peggygannon - can you please take a look at this screen.  This scenario came up later - this screen represents when the system does not recognize the entered address and does not have any suggestions.  The user can either edit their address or choose to continue, which would override the system and use the entered address.  Thank you!

![Address not recognized - 3.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/8c9f7e10-8572-4fd6-872a-6c939c846b46)

**Comment by peggygannon** [comment]
Hi, @artistgreen here's my content recommendation. I suggest putting the link [Edit your address] within the alert message, so it's more visible to the user. 

**We couldn't find a match for your address**
We're sorry. We don't recognize the address you entered.  Please edit your address or click continue to use the address you entered. 
[Edit your address]

**Comment by artistgreen** [comment]
@peggygannon - that sounds great!  Should we still show the entered address?  Thank you!

**Comment by peggygannon** [comment]
@artistgreen Yes, sorry, my note wasn't clear. Yes we should still show the entered address.

**Comment by Samara-Strauss** [comment]
Update needed here per our discussion in standup. Arthur, can you please create a mockup that accounts for the following use case:

- We are not allowing the user to override our address validation with the original address they entered.
- In this case, we will still show suggestions if we have them.
- We will allow them to go back and edit their address.

If you can, please get this to me by some time on Monday morning. If you can't, let me know what a reasonable deadline will be. I need to have the prototype done by EOD on Tuesday because I'll be out so I need this as soon as you can get it to me.

Thank you!

**Comment by artistgreen** [comment]
@Samara-Strauss - yes!  
Will plan to have this to you by mid Monday morning and will let you know ASAP of any delays or issues.

Thanks!

**Comment by artistgreen** [comment]
@Samara-Strauss @Justin-Pickett 

Good morning,

Here are 2 screens that show the 'No override' concept, with and without address suggestions.  

1. Address Invalid and we do not provide any address suggestions.  The user can either go back and edit their address or choose to cancel. (Quick question:  should we consider showing a phone number for users to call in for assistance to edit their address if we do not allow override or any suggestions?)

![Profile  - Address Not Valid with No override and No address suggestions.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/25603714-aa71-460e-b4dc-8dc5a0c252e8)

2. Address Invalid and we provide address suggestions.  The user can go back and edit their address, select a suggested address option or choose to cancel.

![Profile  - Address Not Valid with No override and address suggestions.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/77738b38-75b8-4044-856c-ac4d104adf02)

**Comment by Samara-Strauss** [comment]
> Address Invalid and we do not provide any address suggestions. The user can either go back and edit their address or choose to cancel. 

The one thing that struck me right away is that Cancel looks like the main CTA and overpowers Edit Address, which is what we really want them to do. I understand why you designed things this way based on the pattern where we have suggested addresses, but I wonder if the main CTA button could be Edit Address/we hide the edit link in the use case where there are no addresses to suggest AND we are not allowing them to override. My guess is this would be technically wonky because of hiding the Edit Address link, so I'd suggest checking in with someone technical on this approach. If they think this would be weird from a technical perspective, then we might instead want to hide the cancel button to emphasize the Edit link.

> (Quick question: should we consider showing a phone number for users to call in for assistance to edit their address if we do not allow override or any suggestions?

I think we could, but work with copy/content to figure out what would be most helpful here. 

> Address Invalid and we provide address suggestions. The user can go back and edit their address, select a suggested address option or choose to cancel.

Design 2 looks good.

**Comment by Justin-Pickett** [comment]
We'll be having a technical discussions about the above designs Monday November 4th with @erikphansen and @bradl3yC.

**Comment by artistgreen** [comment]
@Samara-Strauss  - thank you for the feedback!

I agree with you --  went back and forth about the having the 'Edit address' as a CTA button myself :-)I've made the revision to show the 'Edit address' as a CTA button next to 'Cancel'.

I'll work Peggy to get the right copy.

![Profile  - Address Not Valid with No override and address suggestions.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/3386d9c2-d045-4947-8051-9a41a57146af)

**Comment by artistgreen** [comment]
Hi @peggygannon!  We have 2 other scenarios for address validation-override that require copy.  
We would like to explore copy that may display a help line phone number for the user since it could feel frustrating if they think their entered address is correct but we do not allow them to override.

Thank you!

1.  The entered address is invalid and the user can either 'Edit address' or 'Cancel'.  The user cannot 'Continue' and override with their entered address in this scenario.  

![Profile  - Address Not Valid with No override and address suggestions.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/ffcf4765-d72e-40d4-89a7-f943a78d2b97)

2.  The entered address is invalid and the user can 'Edit address', select one of the address suggestions to 'Continue' or 'Cancel'.  The change here is that the user cannot select their entered address.

![Profile  - Address Not Valid with No override - address suggestions.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/4b3db669-3677-40ab-957d-4a26951eaec7)

**Comment by Samara-Strauss** [comment]
> I agree with you -- went back and forth about the having the 'Edit address' as a CTA button myself :-)I've made the revision to show the 'Edit address' as a CTA button next to 'Cancel'.

@artistgreen sounds good, but definitely review this with Erik/Brad. Like I said, if this conditional approach to the Edit link is wonky from a technical perspective, we can leave Edit Address as a link and hide the Cancel button. I wouldn't normally recommend removing those button CTAs but I think it could work in this use case because 1) we'd still have the X button and 2) I am assuming this isn't a super common use case (though we should see if we can get the Vet360 team to give us insight into how common it is that addresses won't be overridable).

**Comment by artistgreen** [comment]
@Samara-Strauss - Great!  Will review with Erik/Brad and get some insight on how often this case may happen from Vet360.

**Comment by peggygannon** [comment]
@artistgreen Hi, here is some copy for the validation messages. I kept this purposely short, so to not make the alert message too long. This would go in the alert box as a new paragraph at the end.
Also, we should clarify and check that VA benefits is the number that users should call. I put this number, as I think it's the catch-all number for a lot of Veteran questions. 

-----

{new paragraph} If you think the address you entered is correct, please call VA benefits at 800-827-1000 for additional assistance. If you have hearing loss, call TTY: 711.

**Comment by Samara-Strauss** [comment]
Thanks for this @peggygannon!

@artistgreen I've updated the screens for the prototype with this new copy.

**Comment by Justin-Pickett** [comment]
@artistgreen are we okay to close this one?

**Comment by Samara-Strauss** [comment]
Yes, we can close this. We can open additional tickets for any updates needed.
