### ISSUE TITLE
1990n: Add ability to print confirmation page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#16880]
As a veteran, I need the ability to print the confirmation page of my 1990n form submission so that I can have it for my personal records.

## Assumptions:
1. This update does not require a feature or prod flag; story will be merged at the beginning of the day for staging review prior to afternoon production deployment.
2. The 1990n is located here: https://staging.va.gov/education/apply-for-education-benefits/application/1990N/introduction

## Acceptance Criteria
1. The user has the ability to print the confirmation page.
    a. The button is located between the "We've received your application" content and the blue submission details box.
2. On the submission confirmation page: `We've received your application` has a period at the end (`We’ve received your application.`)
3. The "No documents required at this time" accordion is not included in the printed page.
4. The printed page layout and styles match that as shown in SA#1.

## Supporting Artifacts:
1. [sample-print-confirmation.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5667918/sample-print-confirmation.pdf)
2. [Confirmation Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a15352194357da9ba98522a2d062404e1deb0527/products/education-careers/application/1990n/1990n-outline-draft.md#form-title-apply-for-education-benefits-under-the-national-call-to-service-program) as of 12/03.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15339

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-12-14 at 7.05.14 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2f381902-c553-44ab-9b83-0503fc2d245d)
##
![Screen Shot 2020-12-14 at 7.05.20 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/55ae108c-2e82-454d-a61d-379c41ba6f0d)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/tests/view/27199&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me!

**Comment by watersemma** [comment]
UX Review 2/2: This checks out for me too!
