### ISSUE TITLE
Content Review - STEM Automated Email

### ISSUE THREAD

**Issue by JenLJ** [department-of-veterans-affairs/va.gov-team#16890]
For the Edith Nourse Rogers STEM scholarship, VA wants to automatically send denial letters to individuals who don't meet certain scholarship criteria.  The team was provided with the formal language for these denials, made revisions and needs a content review to ensure the denial emails meet VA content guidelines.

Document:  [STEM Denial Email Content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-automated-denial-email.md)

---
## Tasks
- [ ] _VSP/Peggy provides content feedback and recommendations for the email_

**Comment by peggygannon** [comment]
@amyknox @JenLJ Below is my review/ recommended edits for the STEM denial letter. Please let me know if you have questions. 

[https://app.zenhub.com/files/133843125/e1fad831-eeba-442f-ba63-bfbe2d7f38ac/download](https://app.zenhub.com/files/133843125/e1fad831-eeba-442f-ba63-bfbe2d7f38ac/download)

**Comment by peggygannon** [comment]
Him @amyknox checking back in to see if you have any questions? If not, I'm going to move this work to my "done' column. thx!

**Comment by amyknox** [comment]
@peggygannon - no questions. Thanks for your help with this!
