### ISSUE TITLE
Revise Facility Locator colors to use colors from Formation

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#1689]
The colors used for the border and text of the info bubble on the Facility Locator use colors that are not close to existing colors provided by the Formation design system's palette. Perhaps these colors can be updated to use something from Formation.

https://github.com/department-of-veterans-affairs/vets-website/pull/10701#discussion_r323006346

It's possible that the rules that use these colors can be removed altogether. It appears that the only place we even use the `infoBubble` ID is in some code that's commented out: https://github.com/department-of-veterans-affairs/vets-website/blob/70ab9058d366e8ae8284393f504c07ec01a50ff2/src/applications/facility-locator/components/FacilityTypeDropdown.jsx#L175

**Comment by mmiddaugh** [comment]
Found this issue hiding (we sort by `vsa-facilities`). Need to confirm if this is still an issue
