### ISSUE TITLE
auto-scaling issues on vets-api

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#169]
## Description

The vets-api service doesn't have a great auto-scaling story to date. As the platform scales, we should strive for a fairly somewhat simple, but direct way to auto-scale at this tier. The instances are likely not tuned well individually right now, especially since a lot of traffic can end up sitting waiting for some upstream node.

## AC

- [ ] auto-scaling rules that account for software limitations (number of connections in use) in addition to hardware resources

**Comment by wyattwalter** [comment]
Ran into an issue today that highlighted some needs on this:

- we're taking defaults on puma and sidekiq worker threads (puma is 16, sidekiq 25)
- database connection pool size is set to 16 in the shared connection template
- we have metrics via statsd currently for puma thread workers, but not the other two items

Because of these inconsistencies sidekiq tried to continue using more threads, but seemingly ran out of db connections in the pool. This caused the worker queue to back up until someone manually upped the ASG size to accommodate and it worked through the queue pretty quickly.

We need to sync up these values and get metrics in order to effectively auto-scale this particular tier of the app.

**Comment by ricetj** [comment]
Is this the same as: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2822

**Comment by wyattwalter** [comment]
Yes, but this one is better built out.

**Comment by wyattwalter** [comment]
Well, I guess they're kind of the same but different 😩

**Comment by wyattwalter** [comment]
We are doing this in https://github.com/department-of-veterans-affairs/va.gov-team/issues/5101
