### ISSUE TITLE
Access for Robin Garrison

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#16905]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Robin Garrison
- Please Provide your email.
   > robin.garrison@adhocteam.us (or robin.garrison@va.gov)
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA: Benefits & Memorials 1 team
   > Front end developer, but I need to get data from AWS occasionally
   > Ad Hoc

- Requesting SSH key authorization?
   > NO (I already have this) 

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
    > I need get access so I can obtain save-in-progress data for saved forms. Our backend developers may not always be available to help while on a call with a Veteran

**Comment by jbritt1** [comment]
### For AWS Access

User: Robin Garrison
COR: Mary O'Toole
Approval required: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by tskinn** [comment]
An AWS user has been created for Robin and he has been given credentials.
