### ISSUE TITLE
Update names of Direct Deposit's Google Analytics events

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#16904]
We currently send data to GA when users are working with their direct deposit information on VA.gov. Unfortunately we use the string `direct-deposit` without specifying that we are referring to direct deposit for compensation and pension. Since we are soon going to support direct deposit for education on VA.gov, and will likely record similar events when users are working with that info, we should probably update the strings we are currently sending to GA to be more specific to _comp and pen_.

My suggestion is to start prefixing all generic mentions of `direct-deposit` with `cnp`. These are the specific strings that would have to change:

`recordEvent({ event: 'profile-get-direct-deposit-started' });`

becomes:

`recordEvent({ event: 'profile-get-cnp-direct-deposit-started' });`

---

`recordEvent({ event: 'profile-get-direct-deposit-failed' });`

becomes:

`recordEvent({ event: 'profile-get-cnp-direct-deposit-failed' });`

---

```
recordEvent({
  event: 'profile-get-direct-deposit-retrieved',
  'direct-deposit-setup-eligible': true|false,
  'direct-deposit-setup-complete': true|false,
})
```

becomes:

```
recordEvent({
  event: 'profile-get-cnp-direct-deposit-retrieved',
  'direct-deposit-setup-eligible': true|false,
  'direct-deposit-setup-complete': true|false,
})
```

(We could also change the 2nd and 3rd keys if you wanted)

---

```
recordEvent({
  event: 'profile-edit-failure',
  'profile-action': 'save-failure',
  'profile-section': 'direct-deposit-information',
  'error-key': errorCode,
})
```

becomes:

```
recordEvent({
  event: 'profile-edit-failure',
  'profile-action': 'save-failure',
  'profile-section': 'cnp-direct-deposit-information',
  'error-key': errorCode,
})
```

---

```
recordEvent({
  event: 'profile-transaction',
  'profile-section': 'direct-deposit-information',
})
```

becomes:

```
recordEvent({
  event: 'profile-transaction',
  'profile-section': 'cnp-direct-deposit-information',
})
```

Is this feasible? Obviously we don't want to mess up any Google Analytics views or dashboards that we are using to analyze how people are using the current direct deposit for comp and pen feature. Please let me know your thoughts.

**Comment by bmcgrady-ep** [comment]
Hi @erikphansen - After looking into this further, this should be fine. It will require some changes in Google Tag Manager to capture the updates, so if you are going to make these changes I would ask that you do them in staging, so I could update the GTM and QA. Also, we would need to create an analytics implementation ticket for tracking purposes.

_For my reference_
Things that will change in GTM:
- Tag - Profile Direct Deposit Retrieves or Failures - API Calls
- Trigger - Profile - Get Direct Deposit Information
- LUT - Profile Direct Deposit Retrieval - Lookup Table
	-- started 
	-- failed 
	-- retrieved
- LUT - Profile Section Navigation - Lookup Table
- DLV - DL - direct-deposit-setup-eligible
- DLV - DL - direct-deposit-setup-complete

**Comment by erikphansen** [comment]
@bmcgrady-ep I had a follow up question about this. Would it be possible for you to change things on your side to (temporarily) track both the existing non-cnp-prefixed strings _and_ the new cnp-prefixed strings at the same time, treating both variants as if they are the same? In other words, could your side of things treat calls to `recordEvent({ event: 'profile-get-direct-deposit-started' })` and `recordEvent({ event: 'profile-get-cnp-direct-deposit-started' })` the same event? That way when we make the switch to the new names in the front end we won't miss anything on the GA side.

Without knowing what changes need to be made on your side, I see this change happening in a few steps:
1. You adjust GA to treat the non-cnp-prefixed direct deposit strings (such as `event: 'profile-get-direct-deposit-started' `) and the cnp-prefixed strings (such as `event: 'profile-get-cnp-direct-deposit-started' `) the same.
2. The FE can then change what events/keys we are sending to GA; we'll stop using the generic non-cnp-prefixed strings.
3. You can just remove anything related to the non-cnp-prefixed strings from GA.

**Comment by bmcgrady-ep** [comment]
Hi @erikphansen - thank you for your patience here. I just want to confirm that you are looking for the current event to fire for both `recordEvent({ event: 'profile-get-direct-deposit-started' })` and `recordEvent({ event: 'profile-get-cnp-direct-deposit-started' })`? Also, just want to make sure that there is no place that both events will fire at the same time, so we won't be firing two events when only one occurred.

**Comment by erikphansen** [comment]
Yeah I think we're on the same page. Basically hoping you can treat `recordEvent({ event: 'profile-get-direct-deposit-started' })` and `recordEvent({ event: 'profile-get-cnp-direct-deposit-started' })` as the same event. No, a user action will never fire both of those. We'll make a single PR in the front end to replace all instances of the generic `direct-deposit` strings with `cnp-direct-deposit` strings.

To make sure this goes seamlessly, we would:
1. Open a nice tidy PR that changes the handful of strings I listed in the top post of this thread.
2. Wait for you to make the changes on your side so you treat the `cnp` versions and non-`cnp` versions the same.
3. Once you give us the thumbs up, we will merge our PR.

No big rush on this. If your side of things could be ready in a week or so that'd be awesome.

**Comment by bmcgrady-ep** [comment]
@erikphansen - Glad we are on the same page. I have the changes staged on my side, but will obviously need to QA on staging.va.gov once the changes are made on your side to ensure everything is properly working. 

Let me know when the changes are made and when I can QA the GTM changes. Thanks!

**Comment by erikphansen** [comment]
Awesome! Thanks!

**Comment by erikphansen** [comment]
@bmcgrady-ep I found a couple more that need to change :(


```
recordEvent({
  event: 'profile-navigation',
  'profile-action': 'add-link',
  'profile-section': 'direct-deposit-information',
})
```

becomes:

```
recordEvent({
  event: 'profile-navigation',
  'profile-action': 'add-link',
  'profile-section': 'cnp-direct-deposit-information',
})
```

---

```
recordEvent({
  event: 'profile-navigation',
  'profile-action': 'edit-link',
  'profile-section': 'direct-deposit-information',
})
```

becomes:

```
recordEvent({
  event: 'profile-navigation',
  'profile-action': 'edit-link',
  'profile-section': 'cnp-direct-deposit-information',
})
```

**Comment by bmcgrady-ep** [comment]
@erikphansen - Thanks for bringing this to my attention. I've updated the additional items on my end.

**Comment by bmcgrady-ep** [comment]
@erikphansen - Can you provide some links to where we can get the new cnp events to fire? Thanks!

**Comment by erikphansen** [comment]
If you sign into staging with user 1 (vets.gov.user+1@gmail.com) and go to https://staging.va.gov/profile/direct-deposit you can edit the user's bank info at the top of that page. Feel free to change the bank info as much as you like. You will need a valid routing number to successfully update the bank info but you can find valid routing numbers with a quick Google for something like `wells fargo routing numbers`

**Comment by bmcgrady-ep** [comment]
@ianMcCullough-ob - If you could QA this workspace using the steps above, that would be much appreciated - https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000439?orgId=oXPY3GFFQwaHnjNHpFLyFg

**Comment by ianMcCullough-ob** [comment]
@jonwehausen, would you be able to set up a 30 min meeting to review my process on this QA job?

**Comment by jonwehausen** [comment]
Hi @ianMcCullough-ob , 

Sure - Do you have availability before 1PM EST tomorrow 1/14? 

Thanks in advance

**Comment by ianMcCullough-ob** [comment]
@jonwehausen I sure do!

**Comment by jonwehausen** [comment]
Okay great, I have setup a :30 minute for tomorrow 1/14 at 10:30 AM EST

cc: @bmcgrady-ep @joanneesteban

**Comment by jonwehausen** [comment]
Spoke with @ianMcCullough-ob morning of 1/14 regarding next steps towards QA. 

cc: @bmcgrady-ep

**Comment by ianMcCullough-ob** [comment]
| Event                          | Data Layer / GTM | Test Status     |
| ------------------------------ | ---------- | --------------- |
| profile-navigation             | ![Screen Shot 2021-01-15 at 10.45.57 AM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/185c4d65-7cb1-4ca8-a2b3-c95764bc186b)           |✔️ <br />**PASS**|
| profile-edit-failure           |  ![Screen Shot 2021-01-15 at 11.22.13 AM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/8d241e27-d6a3-4e42-94a2-6863b4721c83)          |✔️ <br />**PASS**|
| profile-get-cnp-direct-deposit |   ![Screen Shot 2021-01-15 at 10.45.47 AM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/a9393bf1-a2de-4e60-92e1-dbb0e2afe154)         |✔️ <br />**PASS**|

Good afternoon @jonwehausen and @bmcgrady-ep, looks like everything tested as expected. Please review and let me know if you need anything else.

**Comment by bmcgrady-ep** [comment]
Thanks for testing this @ianMcCullough-ob.

@erikphansen - I have published out the changes in GTM and am closing this. Let me know if you need anything else!

**Comment by erikphansen** [comment]
@bmcgrady-ep So we are free to start using the new GA names in production just like we are in staging?

**Comment by bmcgrady-ep** [comment]
@erikphansen - Yes, that is correct the new GA names can be used in production. I will note that while I did a quick double-check on the QA, I noticed some events coming in as `edu-direct-deposit` and `cnp-direct-deposit`. Right now, GTM is only capturing `cnp-direct-deposit` and normal `direct-deposit` events.
