### ISSUE TITLE
Offboarding of Amy Cesal

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#16903]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
Amy Cesal
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
Amy Cesal, VSP Analytics & Insights, 11/30/20, Ad Hoc
- Please provide any type of access they may have and their GitHub username. 
Google Analytics, Domo, Slack
  
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jbritt1** [comment]
No SOCKS / AWS / PagerDuty access for this user.

**Comment by jbritt1** [comment]
@joanneesteban any idea what Amy's GitHub username might be? A people search for her name is bringing up empty results.

**Comment by jbritt1** [comment]
Perhaps she is @amygoldman on here?

**Comment by jbritt1** [comment]
Or perhaps already removed from the org?

**Comment by jbritt1** [comment]
Last one is the case, found it: https://github.com/department-of-veterans-affairs/github-user-requests/issues/5427

**Comment by bmcgrady-ep** [comment]
Removed Amy's Domo access (she did not have Google Analytics access)

**Comment by jhouse-solvd** [comment]
@bmcgrady-ep - Is anything else needed from Operations team at this time?

**Comment by bmcgrady-ep** [comment]
> @bmcgrady-ep - Is anything else needed from Operations team at this time?

Nothing left on my end.
