### ISSUE TITLE
No Claims & Appeals (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#16909]
## User story
As a user, I want a screen that tells me when I do not have any Claims or Appeals

## Acceptance Criteria
1. Create UI as shown in designs
     - This UI will be used across both the Active and Closed views
2. Display this UI when:
     - A user does not have any Active Claims/Appeals
     - A user does not have Closed Claims/Appeals

## Designs
https://adhoc.invisionapp.com/d/main?origin=v7#/console/20546460/432463354/inspect?scrollOffset=5806

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Mark "Claims and Appeals" as Header 1
- Mark "You do not have any submitted claims" as Header 2

**Segmented Selector**
- accessibilityLabel=Name of field (e.g. active or closed)
- accessibilityHint="view your__claims and appeals" (e.g. active or closed)
- accessibilityRole="tab"
- Denote selected vs. unselected
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 1 of 2)

## Dev Checklist 

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Have to test with no mock data.

**Comment by digitalken** [comment]
1/20/2021 - Need to test without mock data.

**Comment by digitalken** [comment]
PASS 1/29/2021 - UI passes on Android and iOS.  Accessibility does not pass with Android (non-actionable text with talkback reads back as double tap to activate) but is fine with iOS.  Closing because I'm tracking the bug and it is minor.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19293
