### ISSUE TITLE
[Design] CC - No providers found error 

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#16918]
Update language for error message that shows when providers are not found in CC Provider list.

## Use Case 1
- [ ] Technical issue retrieving providers ([current error)](https://user-images.githubusercontent.com/8315447/101203702-19463780-3639-11eb-9064-683656909878.png)

### Questions/Considerations
- Should we prompt the user to refresh the page/widget to retry?
- Should the FE detect the error and automatically retry fetching the providers? (not something we currently do in VAOS)
- Should we direct them to call their VA?

---
## Use Case 2
- [ ] Able to retrieve providers, but 0 are returned

### Questions/Considerations
- Should we direct them to call their VA?
- Should the FE try to fetch another set of specialty codes?

**Comment by outerpress** [comment]
@LanceGundersen could you drop a screenshot of the current error state/message here?

**Comment by LanceGundersen** [comment]
![image](https://user-images.githubusercontent.com/8315447/101203702-19463780-3639-11eb-9064-683656909878.png)

**Comment by outerpress** [comment]
@laurenernest my first pass, with some questions:

Use case 1: https://adhoc.invisionapp.com/d/main#/console/20790192/439802127/preview
* Are these errors typically resolved quickly enough that refreshing would be an effective fix? If not, we shouldn't offer that as an option.

Use case 2: https://adhoc.invisionapp.com/d/main#/console/20790192/439802128/preview
* I'm assuming this would be triggered if there are no providers nearby - though we haven't set a limit on that, have we? 
* Are there other situations that would trigger this?

**Comment by laurenernest** [comment]
I'm not confident enough in the consistency a refresh would provide results so let's leave that off.
> Use case 1: https://adhoc.invisionapp.com/d/main#/console/20790192/439802127/preview
> * Are these errors typically resolved quickly enough that refreshing would be an effective fix? If not, we shouldn't offer that as an option.

Good point. We don't have any distance limits set so if 0 are returned, it should mean there aren't any providers in the country that meet the specialty codes we query. I'm checking if we can see total provider counts by specialty.
> Use case 2: https://adhoc.invisionapp.com/d/main#/console/20790192/439802128/preview
> * I'm assuming this would be triggered if there are no providers nearby - though we haven't set a limit on that, have we? 
> * Are there other situations that would trigger this?

Overall, linking out the facility locator seems to be the best option in both cases.

**Comment by laurenernest** [comment]
@peggygannon Tagging you in this ticket to get in your queue. We can discuss in our next sync.

**Comment by laurenernest** [comment]
@outerpress I misspoke. @saneshark clarified there's a radius set in the query.

@LanceGundersen What is the max distance the list will pull up?

**Comment by LanceGundersen** [comment]
@laurenernest it's set to 60 miles but we can change that param.

**Comment by laurenernest** [comment]
We should probably expand this. I created a ticket for it #17104

**Comment by outerpress** [comment]
Thanks all! I updated both use cases:
- Removed the instruction to refresh
- Noted the radius we're searching in, for the none nearby alert
- Added an instruction to continue without a provider (since the question is optional, this should be a valid path)

(I'm realizing I should drop in screenshots since InVision isn't the best at tracking change history - so these are updated in InVision but also here for reference)

![VAOS-CC-MVP-02-NoProvider-error.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/a9d8446e-1728-4cfd-a24a-db553cf6e645)
![VAOS-CC-MVP-02-NoProvider.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/84561a7f-067b-48d1-b689-b14a079676e7)

**Comment by peggygannon** [comment]
@laurenernest and @outerpress Can we discuss this one at our sync Monday?

**Comment by laurenernest** [comment]
@peggygannon Definitely! I made a note to include that in the agenda.

**Comment by peggygannon** [comment]
Hello! @laurenernest @outerpress 
Please see below my content recommendations for this screen. In addition to the error messages, I couldn't help myself and also offered some recommendations for tightening other language!!


H1: Your community care preferences

Request a provider updated content: 
You can request a provider for this care. If they aren’t available, we’ll schedule your appointment with a provider close to your home. 

Error messages: 
Message 1:

**We can’t load provider information**
OR if that's too long ^^
**We can't load provider details**
We’re sorry. Something went wrong on our end. To request this appointment, you can: 
-	Call your VA or community care facility directly. [Find your health facility’s phone number](va.gov/find-locations), **or**
-	Continue your request without choosing a provider. We’ll contact you about a provider. 


Message 2: 

**We can’t find any [type of care] providers close to you**
We can’t find providers within [tk] miles from your [home/current location]. To request this appointment,  you can: 
-	Call your VA or community care facility directly. [Find your health facility’s phone number](va.gov/find-locations), **or**
-	Continue your request without choosing a provider. We’ll contact you about a provider.

**Comment by outerpress** [comment]
Thanks @peggygannon ! I mocked up the two error screens with the new language (below). 

| ![VAOS-CC-MVP-02-NoProvider-error](https://user-images.githubusercontent.com/2536801/102265220-aad06780-3ecb-11eb-8df2-f4ee9ce098a8.png) | ![VAOS-CC-MVP-02-NoProvider](https://user-images.githubusercontent.com/2536801/102265225-ac9a2b00-3ecb-11eb-92ae-5869c5360d1e.png) |

**Comment by peggygannon** [comment]
Thanks, @outerpress 

a few more tweaks
1. In the first error message, please put a period after We're sorry. 

2. Would this tweak work--removing "directly" from the first bullet, in an effort to bring up the "or" ?

-Call your VA or community care facility. [Find your health facility's phone number], **or**

**Comment by outerpress** [comment]
Thanks for catching that! Fixed below.

I can't promise the "or" won't drop to another line, depending on the screen size, but I think it makes sense without "directly":

|  ![VAOS-CC-MVP-02-NoProvider-error](https://user-images.githubusercontent.com/2536801/102288678-d403ee80-3ef1-11eb-8294-9337ba11f061.png) | ![VAOS-CC-MVP-02-NoProvider](https://user-images.githubusercontent.com/2536801/102288685-d6664880-3ef1-11eb-88a5-efff626cb692.png) |
