### ISSUE TITLE
Document appointment card states

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#16917]
To support a redesign of appointment cards we need to document all the ways appointment data is presented to the user in the appointment list. 

Ideally this documentation would include:

- "Types" of appointments (all the ways an appointment or request can show to a user)
- Data presented with each type
- Screenshots of an example state for each

## Tasks
- [ ] Document VA appointment types
- [ ] Document CC appointment types

**Comment by narin** [comment]
@outerpress I've added the documentation to the design folder here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md

Take a look and feel free to let me know if you require any additional info.

**Comment by outerpress** [comment]
@narin this answers a ton of questions - I'll probably have some follow-up when I dig in more, but this covers exactly what I was looking for. Thanks!

**Comment by laurenernest** [comment]
@narin This is so helpful! Do these screenshots and notes represent all the data we have available? Are there any fields we get back that we don't display?

**Comment by narin** [comment]
The data we have available and fields we use will be different depending on each scenario.  There are a ton of fields that come back from the backend that are unnecessary/unused, and then we convert each appointment into FHIR Format.  I've updated the docs with links to the mock data we use to provide some additional context.  Does that work @laurenernest?

**Comment by laurenernest** [comment]
That extra context is great! Thank you!
