### ISSUE TITLE
Add whole phrase matching logic to RS search (learning center)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#16916]
## Add whole phrase matching logic to RS search (learning center)

Today, we filter for individual search terms in the article titles before rank sorting them by body text instances (per ticket [#16915](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16915).

**Hypothesis: Can we further improve relevance by search filtering on phrase matching in addition to just checking for individual words?** 

**Desired outcome:** 
Search results are made more relevant by including phrase matching, and prioritizing articles with whole phrase matches over articles with any instances of separate, individual words. 

**AC:** {3/22 [edited per clarification](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16916#issuecomment-804222809) of "description" field}

1/ Sort first by the number of **exact query phrase matches** (ignoring casing) in the title and full intro or answer text ~description~.

Then... the rest of the sorting logic we already have: 
2/ Sort ties by query word instances found in title descending {`word` instances, not character instances}
3/ Sort ties then by query word instances found in ~description~ full answer or intro text descending
4/ Sort ties by alpha article titles. 

**Example:** 
When a user searches on a term in the RS like `"the brown bananas"`: 

1/ Bring back articles that have instances of` "brown bananas"` in the title and description (intro) text~article tags~. Prioritize/rank these articles as most relevant.
- Is there a way the filtering logic can include a blacklisted word only when it is part of whole phrase matching? 
- EX: When a user searches on "sign in", the phrase match filtering brings back article titles with "sign in" even though "in" is a blacklisted word. 

2/ Bring back articles that have instances of `"brown" `and instances of `"bananas"` in the article title and article tags text. (Exclude blacklisted words like "the" for individual word searches.) Prioritize/rank these as next relevant.

3/Next, sort ties by instances of `"brown bananas,"` `"brown,"` and `"bananas"` in the body text, descending. 

4/ Next, sort ties by alpha article titles.

**Background:**
Today in the Find a VA forms search, the search logic brings back everything that has any of the words in the user's query, as separate independent word searches. Hence, someone searching for "health care application" will get any form that has the word "health" or "care" or "application."

So even the form 'Application for federal employment` will come up on a search for "health care application." (It has the word "application" in the form titles. 

Ideally, the logic will look for phrase matching -  `health care application` - in addition to "health" / "care" / "application" instances, ranking phrase-matching titles above ones with any instance of individual words.

**Comment by jenniferlee-dsva** [comment]
This one may be a little bit complex/more sophisticated than what we've so far tried. We likely need to talk it out first and refine if needed.

**Comment by kelsonic** [comment]
@jenniferlee-dsva Hey! Just wanted to ask if you've had time to review the current search behavior on staging (doesn't include this ticket yet). Should that search behavior be promoted to prod? 🙂

**Comment by ncksllvn** [comment]
Sorry for the the noise - just checked the source code and it looks like the work @kelsonic is still on staging right now, https://staging.va.gov/resources/. @jenniferlee-dsva or @johnhashva when you have a sec, can you check out the search function there, and see how it compares to production?

**Comment by kelsonic** [comment]
It is indeed still relevant today, the updated search behavior was not promoted to prod

**Comment by johnhashva** [comment]
@kelsonic and @ncksllvn I see same result in Staging and in Production using health care application as the test case.  I was assuming Production would show more articles (that we don't want to necessarily see).  Am I missing something?  Do have some example search terms to test against this?  

<img width="533" alt="Screenshot 2021-03-09 143629" src="https://user-images.githubusercontent.com/63107147/110527573-21ed5480-80e5-11eb-9e77-183d18446682.png">

**Comment by ncksllvn** [comment]
> I see same result in Staging and in Production using health care application as the test case. I was assuming Production would show more articles (that we don't want to necessarily see). Am I missing something? Do have some example search terms to test against this?

Gotta defer to Kelson on this!

>(ALSO: There is a weird truncation happening in search result one -- e.g. h_ow to upgrade to a&#..._in production and staging).

Ticket for that is here! I'll prioritize it, https://github.com/department-of-veterans-affairs/va.gov-team/issues/17779.

**Comment by kelsonic** [comment]
This is the current logic:

**Non-prod envs:**
Experiment with new sorting on non-prod envs.
We derive the number of times a keyword is found in the article's title.
We also derive the number of times a keyword is found in the article's description.
We sort first by query word instances found in title descending
We sort ties then by query word instances found in description descending
We sort ties then by alphabetical descending

**Prod envs:**
We sort by title

**Comment by johnhashva** [comment]
@kelsonic is there are way to pull the data in a readable format so we could see (w/o running a bunch of queries) how this maps for, say, 100 top R&S search terms/queries?

**Comment by jenniferlee-dsva** [comment]
@kelsonic @johnhashva @ncksllvn - can you send me the link to the staging environment? 

Sorry I never saw Kelson's January message!  

In the RS search I wouldn't use "health care application" - sorry, that was a bad example - I was mainly referencing the single term search behavior in Find a VA form, which uses similar logic.

**Comment by kelsonic** [comment]
@jenniferlee-dsva https://staging.va.gov/resources/

@johnhashva I'm not sure 🤔

**Comment by jenniferlee-dsva** [comment]
Added AC to ticket description above: 

> AC: {3/17 added}
> 1/ Sort first by the number of exact query phrase matches (ignoring casing) in the title and description.
> 
> Then... the rest of the sorting logic we already have:
> 2/ Sort ties by query word instances found in title descending
> 3/ Sort ties then by query word instances found in description descending
> 4/ Sort ties by alpha article titles.

**Comment by kelsonic** [comment]
@jenniferlee-dsva PR is merged and will be deployed with the daily deploy today (assuming the daily deploy doesn't fail) 🙂

**Comment by jenniferlee-dsva** [comment]
Documenting findings of validation here... I think there's still some refinement to do, but I'd like to better understand how the ranking logic is working. This is  probably complex enough that we should have a call / walk through. 

## First test: "how do i change my name" search query 

- PROD brings back 31 results
- STAGING new logic brings back 31 results

| Article  | PROD order | STAGING order |
| ------------- | ------------- | ------------- |
| How to change direct deposit information for VA disability or pension  | 1 | 2 |
| Can I get a replacement GI Bill benefit Certificate of Eligibility?  | 2  | 5  |
| **How do I change my name in my DEERS record?** | 5 | 1 |
| **How to change your legal name on file with VA** | 18 | 18 |

**Not expected behavior**
Why do articles like `Can I get a replacement GI Bill benefit Certificate of Eligibility?` rank higher (#5) than the `How to change your legal name on file...` article which has both "how" / "change" / and "name"  text many times more than the GI Bill article? The GI Bill article in fact has 0 instances of "how"/ "do"/ "change" / "your"/ and "name." 

It seems like - not sure - step #2 logic `Sort ties by query word instances found in title descending` isn't being applied.

## Second test: "direct deposit" 
- PROD brings back 4 results
- STAGING new logic brings back 4 results

| Article  | PROD order | STAGING order |
| ------------- | ------------- | ------------- |
| Direct deposit for your VA benefit payments  | 1 | 1 |
| What if I don’t have a bank account, but I want to use direct deposit? | 4 | 4|

**Works as expected** 

## Third test: "benefit payments" 
- PROD brings back 7 results
- STAGING new logic brings back 7 results

| Article  | PROD order | STAGING order |
| ------------- | ------------- | ------------- |
| Direct deposit for your VA benefit payments  | 1 | 1 |
| How VA education benefit payments affect your taxes | 2 | 2|

**Not as expected behavior**
In this test, the `How VA education benefit payments affect your taxes` article has 6 instances of the whole phrase "benefit payments" matching (in title and body text), vs. the direct deposit article which only has 2 instances of matching phrase in the title and body. 


## Fourth test: "sign in" 
- PROD brings back 2 results
- STAGING new logic brings back 2 results

| Article  | PROD order | STAGING order |
| ------------- | ------------- | ------------- |
| Signing in to VA.gov   | 1 | 2|
| What if I can’t sign in to VA.gov because my password doesn’t work? | 2 | 1|

**Not as expected behavior**
In this test, the `What if I can’t sign in to VA.gov because my password doesn’t work?` has 3 instances of the phrase "sign in" (title + body) vs. `Signing in to VA.gov` article which has 11 instances of the phrase "sign in" (none in title, 11 in body). 

So with our new logic, the staging order should show `Signing in to VA.gov` article as #1. In this test, it seems like the new phrase matching prioritization isn't being applied.

**Comment by jenniferlee-dsva** [comment]
@kelsonic @brianalloyd - action items from Kelson and my call. @brianalloyd - You're welcome to track this as a follow up separate ticket, but I'd like information scent back to this original one, so I can use the same validation 'tests' above to compare against. 

Main finding - I was mistook "description" field as the body content. But as Kelson explained: the "description" field is actually a limited/truncated (200 character) part of the intro text. 

So, we are going to try refining the logic a bit to include the full intro text, and see if that creates better proximity to the desired behavior. 

**Updated logic AC:** 
1/ Sort first by the number of exact query phrase matches (ignoring casing) in the title and ~description~ **full intro text.** _{note that in Q/As the intro text field is the "answer" field; and all the other articles, it is called the "intro" field.}_

Then... the rest of the sorting logic we already have:

2/ Sort ties by individual query `word` instances found in title descending. _{note refinement Kelson is going to look into making these `word` instances rather than `character` instances -- e.g., looking for the word "I" vs. looking for the letter/character "i" in everything}_ 
3/ Sort ties then by query word instances found in ~description~ **full intro text** descending
4/ Sort ties by alpha article titles.

To do a search of actual body content (minus global components) is a little more effort, but doable according to Kelson. So I'll create a separate ticket for that, as a future backlog item.

**Comment by brianalloyd** [comment]
Thanks @jenniferlee-dsva for the comments and updated AC, love the goal to refine logic to include full intro text.  @kelsonic let's review this during tomorrow's SU.

**Comment by kelsonic** [comment]
PR is up to use the full `introText` for ordering @jenniferlee-dsva @brianalloyd. I didn't think about this initially, but if we were to add a `searchableContent` field in the future it might really increase the file size of our `articles.json` in the near future, which will decrease both searching performance (it could appear laggy) and it will require our users to download a lot more before the page renders + is ready to respond to user input.

For reference, the current addition of the full intro text data point increases our `articles.json` file size from 31kb to 44kb. The addition of a `searchableContent` data point could increase the file size several times the size it currently is (depending on how big each article is). When we experiment with that new `searchableContent` data point, I'll be sure to let everyone know the difference in the `articles.json` file size so we can decide if we want to merge it or not.

**Comment by jenniferlee-dsva** [comment]
Thx for the helpful info @kelsonic . 

- Re this PR - let me know when it's ready to check out in staging. 
- Re the `searchableContent` field - def share your concern about increasing response time.  Please let us know what the increase if any looks like - size but also would be helpful to translate that into time - milliseconds/seconds?

**Comment by brianalloyd** [comment]
@jenniferlee-dsva this PR should be ready for validation in staging.  We're going to break out the additional refinement items into a separate ticket that will nest back to this ticket in support.

**Comment by jenniferlee-dsva** [comment]
I've validated and the  new sorting logic and phrase matching appears to be working,  except for the word `I` instance of search behaving as a character i search. 

## First test: "how do i change my name" search query 

- PROD brings back 31 results
- STAGING new logic brings back 31 results

| Article  | PROD order | STAGING order | 2nd STAGING update |
| ------------- | ------------- | ------------- | ------------- |
| How to change direct deposit information for VA disability or pension  | 1 | 2 | 3  |
| Can I get a replacement GI Bill benefit Certificate of Eligibility?  | 2  | 5  | 2 |
| **How do I change my name in my DEERS record?** | 5 | 1 | 1 |
| **How to change your legal name on file with VA** | 18 | 18 | 15  |


### Not expected behavior:

**Comment by jenniferlee-dsva** [comment]
let's close this as complete and tackle the word vs. letter sitch separately.
