### ISSUE TITLE
Prune unused messaging SCSS

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#1691]
I believe there is a lot of old SCSS for styling features that have been removed from the site, in particular the messaging-related SCSS. Example: https://github.com/department-of-veterans-affairs/vets-website/pull/10701/files/8f076cd09933799828f9f2f81be2003f559e2e5e#r322813067

The unused classes and maybe even entire .scss files should be removed if they are not used anywhere in the app.

**Comment by Justin-Pickett** [comment]
@mojaray2k will looking this ticket.

**Comment by Justin-Pickett** [comment]
@mojaray2k identified more work that still needs to be cleaned up. This item will carry over into the next sprint.
