### ISSUE TITLE
Analytics Implementation for programmatic GTM PII Scrubbing

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#16928]
# GTM Implementation

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Objective
- Create a custom task to automatically listen for various forms of potential PII  and remove data found before sending to GA in the hit payload

## Acceptance Criteria
- [ ] PII cannot be exposed in any field of the Google Analytics payload
- [ ] QA has been completed with various PII test cases
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
### Notes 

@bsmartin-ep I will leave to you if you have / can find a better programmatic approach, but [here](https://www.simoahava.com/gtm-tips/remove-pii-google-analytics-hits/) is what I believe we could do from an implementation perspective for our due diligence and best chance at catching, scrubbing and removing any PII prior to GA ingestion. 

@joanneesteban This would be our first attempt at a PII scrubbing solution for GA360. The solution documented here operates with RegEx matching (_meaning with with each GA hit, the code will perform it's best attempt at finding PII in any part of the GA hit based on the string logic we program_). That said, it's certainly not perfect as this current solution only listens for and removes email addresses. While there are opportunities to add our own RegEx patterns to this code and expand our logic to capture other forms of PII, an all-encompassing programmatic solution to prevent any and all PII may be impractical.  

Let's discuss this solution in greater detail.

**Comment by joanneesteban** [comment]
### Impact
Programmatically redacts email addresses using Javascript
- `4 characters` + `@`+ `4 characters

**Comment by bsmartin-ep** [comment]
This was implemented years ago.
