### ISSUE TITLE
COVID-19 Redirect Request

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#16929]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
We need to secure a vanity url and variations for the covid-19 vaccine page. Worked with Mikki on this already, as it is an urgent need.

### Requestor team info
Product: @batemapf 
Content: @lalexanderson-dsva @DanielleThierryUSDSVA 

### Implementation date
Date new URL(s) will be live: Monday, 12/7

Please indicate when the change/redirect(s) needs to be implemented"
- [X] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

URL to redirect |  Redirect to (new destination)
---  |  ---
www.va.gov/covid-19-vaccine <br> www.va.gov/covid-vaccine <br> www.va.gov/coronavirus-vaccine <br> www.va.gov/covid19-vaccine | www.va.gov/health-care/covid-19-vaccine/  

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
Updated the table to clarify which is the destination url and which are the ones to redirect.

These redirects are ready to go and can be implemented at any time.  They do not necessarily need to wait until the page is live, but they will redirect to a 404 until it is live  (which is no different than if you try to go to them right now).

**Comment by mnorthuis** [comment]
@brianalloyd @kelsonic @ncksllvn In the interest of time, I'm tagging you on this.  These redirects for for the vaccine page going up and can be implemented at any time - even before the page goes live on monday.

**Comment by kelsonic** [comment]
I'm picking this up now

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/8128

**Comment by kelsonic** [comment]
@mnorthuis just want to confirm, I can merge + deploy this asap?

**Comment by mnorthuis** [comment]
Yes, this can be deployed.  The destination page is not live yet, but should be shortly.

**Comment by shiragoodman** [comment]
@kelsonic @brianalloyd  Can this ticket be closed out? VSP work is complete.

**Comment by kelsonic** [comment]
Yupp! 🙂 PR was merged + deployed + validated: https://github.com/department-of-veterans-affairs/devops/pull/8128
