### ISSUE TITLE
Facility Locator appears to trigger re-search when resizing the browser window

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#1694]
Facility locator appears to trigger a re-search when changing the height of the browser window. And when making the window shorter, the search appears to never resolve successfully.

Steps to reproduce:
1. Go to the Facility Locator and make a valid search. In this case, just use this URL: https://www.va.gov/find-locations/?zoomLevel=9&page=1&address=97130&facilityType=all&serviceType&location=45.767522962149904%2C-123.94088745117189&context=Manzanita%2C%20Oregon%2097130%2C%20United%20States
2. Make the browser window taller and see that the loading spinner appears briefly before the search resolves.
3. Make the browser window shorter and see that the loading spinner appears but the search does not appear to resolve.
4. Click on one of the location markers in the map to cause the spinner to resolve.
5. After clicking on one of the location markers, further browser resizes do not cause the spinner to appear again.

GIF of bug:

![facility-locator-resize](https://user-images.githubusercontent.com/20728956/64713010-04e4b080-d471-11e9-96c4-d3972466de7c.gif)

It actually appears that doing multiple window resizes in sequence is the crux of the problem. So it's possible to shrink the window twice in rapid succession to trigger this bug. When the spinner hangs, the following console error is logged:

```
Uncaught (in promise) TypeError: Cannot read property 'place_name' of undefined
    at mapHelpers.js:53
    at w (runtime.js:62)
    at Generator._invoke (runtime.js:288)
    at Generator.e.<computed> [as next] (runtime.js:114)
    at B (MapboxClient.js:4)
    at a (mapHelpers.js:49)
```

**Comment by mmiddaugh** [comment]
This looks similar to the issue reported in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/492

**Comment by mmiddaugh** [comment]
Duplicate to [#1693 ]
