### ISSUE TITLE
IA Request [BAM2 Debt Resolution FSR Form ]

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#16946]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/FSR-Product-Outline.md) 
- Link to or attach [prototype](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701647/simulate/sitemap?mode=i) or mockups
- Link to research [readout/results](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/Debt%20Resolution/Financial-Status-Report/research) ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/how-to-do-research_synthesis.md))
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords** - repay debt, debt, debt letters, FSR, financial status report, debt forgiveness, compromise, waiver, monthly offsets, education loans relayment. 

**Proposed site map/page structure** - Provide link or image of proposed page structure (if more than one page)

**Suggested URL(s)** - va.gov/manage-va-debt si debt landing page 

**Suggested entry points** - What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [ ] Issue is created, tagged and assigned to VSP Product Support
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation

**Comment by mnorthuis** [comment]
@leahkeeler Draft IA is here for initial review: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-fsr.md

**Comment by leahkeeler** [comment]
@craigwheeler - IA when you are ready

**Comment by mnorthuis** [comment]
@leahkeeler @DanielleThierryUSDSVA @peggygannon @rebeccawalsh 

The IA for FSR and corresponding Debtman content is almost complete.  There are a couple of open items left to finalize. 

- Need to finalize the URL of the FSR.  Right now the prototype shows the H1 as "Request help for VA debt", which doesn't reference the term "Financial status report".  I will need to know how important the terms "Financial status report" are to this form.  Typically we include the form name and number in the URL, but if I did that (i.e. /submit-financial-status-report-form-5655) the URL would not match the H1, so this is open issue for us to discuss. 
- The redirects are not fully mapped out, and won't be until all of the content pages within Resources and support are identified and created. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-fsr.md

**Comment by mnorthuis** [comment]
@peggygannon @DanielleThierryUSDSVA @rebeccawalsh I want to follow up on the remaining issue above regarding defining the URL of the FSR.  Can you let me know where we are with finalizing the H1 for that form and whether we are concerned about including "Financial status report" within the name and/or URL?

**Comment by rebeccawalsh** [comment]
@mnorthuis I know that @peggygannon gave us feedback that the H1 should be "Request help for VA debt payments with VA Form 5655"

**Comment by peggygannon** [comment]
Hi, @rebeccawalsh Mikki, Danielle and I met today and are recommending a slight tweak to that H1, to also take into account the FSR now has a wizard 
H1 For the wizard page:  Request help with VA debt
H1 For the FSR form introduction page:  Request help with VA debt with VA Form 5655

I believe Mikki will be adding this to her IA feedback.

**Comment by mnorthuis** [comment]
IA is now finalized and documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-fsr.md

Please let me know if you have any questions. 

Please note:  A redirect issue will need to be created so we can direct traffic from the old debtman pages to the new experience. 

@leahkeeler you can close this issue when you are ready.

**Comment by craigwheeler** [comment]
Hi @mnorthuis  I recently updated the H1, URL and breadcrumbs outlined in [IA Design and Recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-fsr.md) which can be viewed on staging [here](https://staging.va.gov/manage-va-debt/request-debt-help-5655/), let me know if I missed anything or if there should be anymore changes? Thanks

https://staging.va.gov/manage-va-debt/request-debt-help-5655/

**Comment by mnorthuis** [comment]
Thanks @craigwheeler, will review when this comes around for a staging review through the collab cycle.  You are welcome to close this issue if you have the info you need.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16942) to add SEO keywords to FSR

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16942) to add SEO keywords to FSR

**Comment by LinnJS** [comment]
Closing since PR was merged
