### ISSUE TITLE
General Analytics Request for [Leslie Byford]

### ISSUE THREAD

**Issue by Bester1987** [department-of-veterans-affairs/va.gov-team#16974]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- [Leslie Byford]

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - [VA.gov Issue Paper]
    
- What type of analytics support are you looking for?
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
"additional comments" section)
    

## Timeframe for Analytics Requested
_May 2019-December 4, 2020
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

## Analytics to Track Down
> - [x] Number of unique logins
> - [x] Number of health care application received online
> - [x] Number of claim status views
> - [x] Number of online education benefit applications 
> - [x] Number of online burial benefit submissions
> - [x] Percentage increase in customer satisfaction (Foresee) scores
> - [x] Number of Veterans that viewed their personalized homepage (MyVA)

## Other Helpful Questions to think through

- This data is needed as ITSC is updating the VA.gov Issue paper as part of the Presidential Transition initiative. **_*If possible the data is needed on 12/7/2020_**

> Please leave the following blank

## Acceptance Criteria
- [x] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [x] The metrics are shared back with users.

## Definition of Done
- [x] All appropriate issue tagging is completed
- [x] All AC completed

**Comment by joanneesteban** [comment]
Thanks for sending this request, @Bester1987 ! 

@bmcgrady-ep is going to be working on the report for you. We estimate a final report completed for you by EOD tomorrow (12/8), but will try to have this done today. Let us know if you have any questions!  

---

@bmcgrady-ep is it possible to put this up on Domo so we can use these datasets in the future?

**Comment by bmcgrady-ep** [comment]
@Bester1987 - Would you have time to meet and discuss the metrics further, as I have some questions that would hopefully clarify what you are looking for?

**Comment by Bester1987** [comment]
Hi Ben,

Sure! I have some time now or at 2:30, whichever works best for your schedule. Thanks!

Best,
Leslie

**Comment by bmcgrady-ep** [comment]
@Bester1987 - Sure I am available to meet now.

**Comment by bmcgrady-ep** [comment]
Thank you for taking the time to meet with me @Bester1987. 

To recap what we discussed: You are looking to update the metrics that were provided back in May 2019, there isn't much insight into who created the report or how the report was created, but I will do some investigation to see if I can find the original report. Ideally, you would like the data to be from the date range of May 2019 - Present, but you are okay if we can only give you data from December 2019 - December 2020. I will create a report in Domo with the listed metrics and share it with you for your review.

**Comment by Bester1987** [comment]
Thank you Ben. I appreciate your assistance with this request.

**Comment by bmcgrady-ep** [comment]
@Bester1987 for an update on the reporting request - I have all of the requested metrics except for one - `Number of Veterans that viewed their personalized homepage`. I should be able to get that one, but I am going to need to create a dataset for it and should have the completed report for you in the AM.

**Comment by Bester1987** [comment]
Good morning Ben,

Thanks so much for the update!

Best,
Leslie

**Comment by bmcgrady-ep** [comment]
@Bester1987 - I shared the Domo Dashboard with you. Let me know if you have any questions.

**Comment by joanneesteban** [comment]
Thanks, Ben! 

A couple of things to close out on our side:
- [ ] Please add date ranges for these numbers
- [ ] Can you add the GA links for future referencing?

**Comment by bmcgrady-ep** [comment]
@joanneesteban - This has all been updated. Let me know if you need anything else.

**Comment by bmcgrady-ep** [comment]
Met with Leslie Byford this AM and she is happy with the dashboard created in DOMO. We can close out this ticket.

**Comment by bmcgrady-ep** [comment]
Met with Leslie on 12/15 and exported the GA reports (ones linked in the DOMO dashboard) for 2019 and 2020, as well as updated the DOMO Dashboard with the date range: December 1, 2019 - December 1, 2020.

cc: @rroueche @joanneesteban
