### ISSUE TITLE
Add tracking for CC request language preference

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#16972]
To help inform future iterations of the Community Care provider preferences, it would be helpful to know the distribution of preferred languages users include in their request.

## Task
- [ ] Add tracking for preferred language selection

## Acceptance Criteria
- [ ] Preferred language is included in submission event

## Technical Notes
We similarly update the submission event in #15834 for another data point. Example below:
```js
'event': 'vaos-community-care-submission',
'vaos-number-of-preferred-providers': 1,
...(other parameters already on this event)...
```

**Comment by laurenernest** [comment]
@jbalboni Do we track this in the submissions where I can pull this up in GA? Or, do you know of another way we can see this?

**Comment by jbalboni** [comment]
@laurenernest I don't believe there's a way to see this currently, we'd have to add this to the submission event like we did for number of providers.

**Comment by jenniemc** [comment]
Hi @laurenernest, did you want to track the CC preferred language using the same event on the Community Care Preference Page similar to  [#15834](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15834) when the `continue` button is clicked? 

The Community Care Preference Page use 'event':  'vaos-community-care-preferences-continue'.  In fact i cannot find the event 'vaos-community-care-submission' anywhere in our the files (unless someone is working it and has not merged into master as of this morning)

**Comment by jbalboni** [comment]
@jenniemc This is the submission event: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/new-appointment/redux/actions.js#L1039

**Comment by laurenernest** [comment]
No additional tracking on the language preference page is necessary. Only with the submission.

Thanks for adding that link, Jeff!

**Comment by jenniemc** [comment]
@jbalboni , would that mean I add the event tracking on the review page upon submission at [line 78](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/new-appointment/components/ReviewPage/index.jsx#L78) ?

**Comment by jenniemc** [comment]
@jbalboni, I'm adding the ` 'event': '[`${GA_PREFIX}-community-care-submission', [`${GA_PREFIX}-community-care-language']: data.preferredLanguage` to the ReviewPage. 

Do I need to add anything to the additionalEventData object on line 976? https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/new-appointment/redux/actions.js#L976

**Comment by jbalboni** [comment]
@jenniemc I would make your change in the same place as `vaos-number-of-preferred-providers`, it's the same type of data.

**Comment by laurenernest** [comment]
@jonwehausen @JasonTheBearded Here's where we added the language preference in the CC submission. Can you double check it's going through?

**Comment by jonwehausen** [comment]
Hi @laurenernest , 

Thanks for this -- please see my comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20155#issuecomment-810495811)
