### ISSUE TITLE
Create documentation for running diff between GraphQL/CMS Export Build

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16973]
## Details 

VFS teams are responsible for maintaining the transformers for pages they own, and for ensuring that their transformers are ready for the release of CMS Export Build. 

We need to document how to run the diff between GraphQL and CMS Export Build so that VFS teams can do this on their own.

Likely makes sense to add to most recent docs: [Transformers Development Guide](https://vfs.atlassian.net/wiki/spaces/VP/pages/637567205/Transformers+Development+Guide)

**Comment by meganhkelley** [comment]
Related convo: https://dsva.slack.com/archives/C01512KN35G/p1607018383415100

**Comment by mchelen-gov** [comment]
OBE, can this be considered a general "JSON comparison tool"?

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
