### ISSUE TITLE
App start & login/unlock UX

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#16984]
## User Story
UX and Patrick to work together on app start and login/unlock UX to support sync and push notifications in the app.

**Comment by bridgethapner** [comment]
- Meet up to decide how screens go together to define syncronization points

**Comment by lexicalninja** [comment]
Meli and I had a discussion today about how this will work. 
https://docs.google.com/drawings/d/1EN1wyuBp-2WSB3uXP8QbKAbuXBj6Tjlfyz9xVn2-Kg8/edit?usp=sharing

currently, the choice is to use the app splash screen in the prototype for the first screen, then go to log in or unlock, then combine the token exchange and set up areas to one screen. 

This screen would likely have the VA Seal and then some changing text to indicate the job status like "completing your log in" -> "fetching your profile and military data" -> "setting up your home screen" or similar items.

I will look for some examples of this and drop them here for @msmanak to use as inspiration.

**Comment by lexicalninja** [comment]
Here is a breakdown of how the whole process does its work: 

On app start up, there are a number of things that have to happen before a user can get into the app. Some of these things, like auth, are required and some of them are to create a better Veteran experience by pre-calling some data. Here is a list of what needs to happen:

1. Authorization
	- The app needs to check if the user is logged in. If they are logged in and the tokens are good, then skip to Sync Work.
	- otherwise if the user has a stored refresh token, then they are sent to the Unlock Screen.
	- if none of the previous are true, the user is sent to the Log In screen.

2. Token Exchange & Sync Work Screen
	- After the user logs in through IAM or unlocks with biometrics, the device needs to update the access and refresh tokens. This requires an asynchronous call to and API endpoint. 
	- If the token exchange is successful, the skip to Sync Work.
	- otherwise return to log in and inform user there was an error.
	- The app will do some cursory work before the user hits the Home Screen. This work helps by doing some common API calls and functions before a user is in the app. The initial calls make sure the app has data it needs to make the Veteran experience more seamless. This would need to be a screen that indicates that we are setting up your app or fetching your information or something to that effect. I can provide samples of other apps that do this. 
	- The app calls the profile and military history end points. This makes sure the Veteran Name and last branch of service do not need to be fetched when a user hits the profile screen and there will not be a lag before the banner is populated.
	- The app will check to see if it has registered the divece token with VetText and register if needed.
	- The app can also make other setup calls for the API in parallel here, in case we need to cache things like appts or claims or something else that takes a long time.

4. Home Screen
	- The app then routes to the home screen

**Comment by lexicalninja** [comment]
Here is a look at what asana does on the web and in their app for this type of syncing: 
![image](https://user-images.githubusercontent.com/7376126/102642723-bcac4780-4123-11eb-882c-941e20bb1e5f.png)

**Comment by lexicalninja** [comment]
This app changes images and text as it loads content in the background and automatically progresses 
![image](https://user-images.githubusercontent.com/7376126/102642874-f2e9c700-4123-11eb-8c76-1a768cb85760.png)

**Comment by lexicalninja** [comment]
this one just has an animated svg to show that it is still working
![image](https://user-images.githubusercontent.com/7376126/102643038-40feca80-4124-11eb-9278-8427fc8a6784.png)

**Comment by msmanak** [comment]
![Slice-splash screen.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/646e746a-4854-4f57-96de-a4409ffc93ce)

**Comment by bridgethapner** [comment]
@lexicalninja sent me a .gif of this & it looks like you guys implemented the design in the top left with the addition of a check icon. It looks good! 

I have a couple of questions: 
- We have [this loading state](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/438292718_Homescreen_Loading_State) for the home screen too. It seems like the UI in this ticket is covering step 2 in the sign in process outlined above. Do we also expect the home screen to need a loading state? Or will it no longer need that because everything will load while this splash screen is displayed? Just want to make sure I understand if both screens are needed or just 1.
- @msmanak (you may be already doing this so plz disregard if so) I'm interested in your POV on what the voice-over should say should loading take awhile / any other accessibility considerations you think we should note here.

**Comment by lexicalninja** [comment]
@bridget would like to add a warning to the login page or splash screen that indicates the pre-store release versions are not for public consumptions. Can be added to the splash screen and the splash screen can have a 3 or 4 second timer to allow a user to consume this or require some user feedback to move past.

**Comment by bridgethapner** [comment]
@lexicalninja I'm thinking we should add the disclaimer to the unauth home screen to people see it the very first moment they open the app & we don't need to worry about timing this screen for reading

**Comment by lexicalninja** [comment]
@bridgethapner there isnt technically an unauthed home screen. We have a login screen or an unlock screen depending on how credentials are saved. Just put it on both of those screens at the top?

**Comment by bridgethapner** [comment]
@lexicalninja Yes, that sounds great! I have a design in #17247.

**Comment by lexicalninja** [comment]
work for this was started on branch feature/App-startup

**Comment by bridgethapner** [comment]
Moved this back to in progress to answer some lingering questions and finalize for our first App Center release. 

Next steps: Bridget & Patrick meeting tomorrow 1/7 to work together on app unlock UX. Hopefully will finalize then.

**Comment by bridgethapner** [comment]
Met w @lexicalninja today to chat about when we prompt for biometric sign-in & what the UX is like. Here's the decision: 

**MVP Internal Release**
- We'll prompt users to sign in via biometrics on the loading screen before they hit the home screen. So if they sign in with Touch or Face ID they'll immediately move on to the authenticated home screen. 
- The UI will be the system modal
- There won't be a cancel button for now because we need to do more technical/UX work to do this (@lexicalninja want to double-check - this is what we decided, right?)

Copy for system modal to prompt for biometrics
**Title:** Touch ID for VA Mobile OR Face ID for VA Mobile
**Body:** Sign in to view your account


**Things We'll Do Post-MVP**
- We want to add a 'Cancel' button to this modal. We see this use case as important for a scenario where a caregiver is logging in on behalf of a Veteran. We'll need to develop a technical & UX solution for what happens if a user opts out of signing in via biometrics even if they have it turned on and wants to enter their username/password instead.

**Comment by bridgethapner** [comment]
@lexicalninja Are you still using this ticket? If not I'll close it.
