### ISSUE TITLE
Create Manual QA Test Cases

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#16986]
## User Story

As a QA engineer verifying and validating the development of the Vaccine Prep Tool, I need to initially stub out test cases and then iterate the definition of test cases in a test suite.

## Acceptance Criteria

- [ ] Manual test case stubs have been created based on the user stories, prototypes, and initial draft of the front-end / back-end.
- [ ] The steps to a test case representing an E2E flow has been created and tagged as such
- [ ] Candidates with high value for automation have been identified

**Comment by holdenhinkle** [comment]
The manual test case stubs have been updated to reflect the current flow. The following case has been deleted to reflect the same: 
Successful registration with appointment scheduled

**Comment by pjhill** [comment]
Initial creation of these test cases is complete. They likely need to be updated, but future efforts on these test cases will be worked under a new ticket.
