### ISSUE TITLE
Analytics Implementation or QA Support for coronavirus-vaccination 

### ISSUE THREAD

**Issue by stephenBarrs** [department-of-veterans-affairs/va.gov-team#16981]
# Google Analytics Implementation or QA Request

## Description
- This request is for Google Analytics implementation

- Who is this request for?
    - @stephenBarrs @batemapf  @ncksllvn 
    
- What team/project is this work for?
    - coronavirus-vaccination
    
- Provide the Domain where Google Analytics needs to be implemented
    - www.staging.va.gov
    - www.va.gov
    
 - No PII will be passed in URL or title tag

- Please provide any upcoming deadlines or important milestones
    - This product is high priority and will launch within the next week

- Typical Website Interactions to Track
    - Note: this form is **not** built using the VA Form System.  It does use parts of VAFS but not the full implementation. 
    - We need to track the drop off b/w clicking the “sign up” button and hitting the sign in screen.  The "sign up" button will be on a separate page and is used to launch this form.  I think we can accomplish this by looking at page loads of the form root url (`/coronavirus-vaccination`) and then tracking clicks on the `sign in` and `continue without signing in` buttons.  Advice on how to best do this is appreciated. 
    - **onSubmit** - capture the success or failure of the onSubmit event.  This can be a simple capture that does not include specific data elements.  
    - Post MVP we may want to capture specific form field completion to know if any specific field is causing drop off from completion. 

    - /coronavirus-vaccination/  this is the introduction screen of the app
    - /coronavirus-vaccination/apply   this is currently the actual form page of the app.  This is a single page form 
    - /coronavirus-vaccination/confirmation  this is the confirmation page of the app.  
 
- This app is designed to be used by both authenticated and unauthenticated users
    - Any existing test users should be able to access the app in Staging

- Additional Comments

    - It looks like the form scroll depth is being captured by default.  Can you please confirm this?  

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
@bsmartin-ep can you prioritize this for the Covid dashboarding work?

**Comment by bsmartin-ep** [comment]
Hi @stephenBarrs -


### Buttons

The buttons should be tracked with the `cta-button-click` event:


<table>
<tr>
<th>Button</th><th>Data Layer</th>
</tr>
<tr>
<td><strong>Sign in</strong> button</td>
<td>
<pre>
'event': 'cta-button-click',
'button-type': 'default',
'button-click-label': 'Sign in'
'button-background-color': '#0071bb'
</pre>
</td>
</tr>
<tr>
<td><strong>Continue without signing in</strong> button</td>
<td>
<pre>
'event': 'cta-button-click',
'button-type': 'secondary',
'button-click-label': 'Continue without signing in'
'button-background-color': 'transparent'
</pre>
</td>
</tr>
</table>

### Form Submission

The form submission should use our standard [form tracking events](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md).

Reminder some of these events are baked into [certain functions in the forms system](https://github.com/department-of-veterans-affairs/vets-website/blob/58853bd4c447a5f188576d9a257e6a3411769cee/src/platform/forms-system/src/js/actions.js#L82) if you are using that. For instance, I am already seeing the `covid-vaccination-no-login-start-form` firing when I start the no-login form.

<table>
<tr>
<th>Interaction</th><th>Data Layer</th>
</tr>
<tr>
<td>Successful onSubmit</td>
<td>
<pre>
'event': 'coronavirus-vaccination--submission-successful'
</pre>
</td>
</tr>
</table>

Are you looking to just track successful submissions or attempted submissions as well (`--submission`)?

### Page tracking

I see the pageviews coming in realtime, so we should be OK there. I wasn't able to do successfully submit the form though, so I'll want to double check we're seeing all the pageviews we expect.  If it's a new pageload - or a historyState change - we should be OK though.

![image](https://user-images.githubusercontent.com/62304138/101497623-2add5700-3939-11eb-8415-6cd85e646456.png)

FYI - the page title looks a little off, though I'm sure you are aware of that.

-----


(cc @bmcgrady-ep.  Mind double checking this since we're on a deadline?)

**Comment by stephenBarrs** [comment]
hello @bsmartin-ep!    Let me know if I missed anything you need answers to.  Thanks for the quick assistance with this work! 

##Auth vs UnAuth flow tracking
We are sending events for the auth and unauth state once the authentication flow returns to the app so we can know that the authentication succeeds, with [this code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/coronavirus-vaccination/components/Form.jsx#L51):

`    if (isLoggedIn) {
        recordEvent({
          event: 'covid-vaccination-login-successful-start-form',
        });
       ...
      } else {
        recordEvent({
          event: 'covid-vaccination-no-login-start-form',
        });
      }
`

I do see value in also tracking the button clicks to start the form in auth or unauth state, such as seeing if there is a drop off with Veterans failing to authenticate and not continuing the form (difference between clicks on the `authenticate` button and `covid-vaccination-login-successful-start-form` event.    

We will plan to implement the button click events today. 

##URLs being tracked
Note that the current URLs will be changed today or early tomorrow.  The current plan is for URLs like:

- va.gov/health-care/covid-19-vaccine/stay-informed/intro
- va.gov/health-care/covid-19-vaccine/stay-informed/form
- va.gov/health-care/covid-19-vaccine/stay-informed/confirmation

##Form Submission
We plan to track both successful and failed submissions with this code (not merged into Staging yet)
![image](https://user-images.githubusercontent.com/2481110/101534496-3fcfdf80-3965-11eb-9ad9-c339ea254c0b.png)

**Comment by bsmartin-ep** [comment]
Hi @stephenBarrs -

### Auth vs no-auth

I believe the auth event doesn't include a product prefix, so just...

`no-login-start-form`

### URLs being tracked
 
Not a problem on the new URLs.  We just need to make sure we have the right ones when we build any funnels or other reports.

We'll just need to double check each page is being sent as a pageview (which usually happens, but sometimes these SPAs are goofy).

### Form Submission

LGTM. If you're interested in a success rate on the submission, you can trigger a `covid-vaccination--submission` when the fetch or whatever kicks off.

**Comment by stephenBarrs** [comment]
Thanks @bsmartin-ep 

###Auth vs no-auth
without the product prefix will that still track the number of unauthenticated users starting this specific form?

**Comment by bsmartin-ep** [comment]
@stephenBarrs -

I believe the intention is to add the event Page Path as a secondary dimension and use that to determine which form this occurs on.....

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=no-login-start-form&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22no-login-start-form%22,0%5D%5D/

**Comment by stephenBarrs** [comment]
@bsmartin-ep follow up question on capturing the auth and unauth button clicks.  For Auth we are using [this code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/user-nav/actions/index.js#L13) to launch the logon modal which will trigger an analytics event to occur.  Should we still be capturing the additional event as noted above for the `sign in button click`?

**Comment by stephenBarrs** [comment]
@bsmartin-ep We would like to also track an event when an authenticated user who has already submitted the form is launching the form again.  The event could be something like: `covid-vaccination-login-successful-start-form-returning-user`.  We may also want to track if the returning user submitted the form or not.  This is not necessary for MVP.

**Comment by bsmartin-ep** [comment]
@stephenBarrs -

> @bsmartin-ep follow up question on capturing the auth and unauth button clicks. For Auth we are using this code to launch the logon modal which will trigger an analytics event to occur. Should we still be capturing the additional event as noted above for the sign in button click?

As discussed, lets keep both the CTA click and the login modal event just to be safe.

> @bsmartin-ep We would like to also track an event when an authenticated user who has already submitted the form is launching the form again. The event could be something like: covid-vaccination-login-successful-start-form-returning-user. We may also want to track if the returning user submitted the form or not. This is not necessary for MVP.

Also as discussed, if we have an event that fires every time a user logins in via this app, we should be able to use BigQuery (or even GA) to get  a count of users > 1 of these events (and event a data table showing event counts with user counts).  A separate returning user event should not be necessary.

**Comment by stephenBarrs** [comment]
@bsmartin-ep the GA updates were pushed to Staging this afternoon.  The plan is for the app to go live tomorrow afternoon, and have a large public relations push early next week.  What work is remaining on the analytics team side to surface the analytics data?

**Comment by bsmartin-ep** [comment]
@stephenBarrs - I think we just need to add in the `covid-vaccination` prefix to our lookup table.

I went ahead and pushed that to staging and production, so we should see data in non-prod shortly...

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20201209&_u.date01=20201211&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=covid-vaccination/

**Comment by bsmartin-ep** [comment]
@stephenBarrs -

I see data in production:

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20201209&_u.date01=20201211&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=covid-vaccination/

Need anything else for this?  Here's every event occuring on these pages:

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20201209&_u.date01=20201211&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22BW%22,%22www.va.gov~2Fhealth-care~2Fcovid-19-vaccine%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=100/

**Comment by stephenBarrs** [comment]
@bsmartin-ep it looks like we are capturing the events we expect.  is there other work going on to present this data in a Dashboard, or is that something the app team would work on?

**Comment by bsmartin-ep** [comment]
@stephenBarrs -

Yes - that should all be in this KPI dashboard ticket:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/16348

Close this one out then?

**Comment by joanneesteban** [comment]
Thanks, everyone! @stephenBarrs let us know if you need anything else. We're closing this out on our end, but can reopen if needed.
