### ISSUE TITLE
UI design of new Common Component: Delete Button

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#16983]
## User Story
As a user, I would like to be able to delete any phone number, fax, email, or residential address with one click of a button. 

## Tasks
- [x] Design UI of button
- [ ] Document design as a common component

**Comment by msmanak** [comment]
VA.gov research:

**Are you sure?**
This will delete your home address across many VA records. You can always come back to your profile later if you'd like to add this information back in.
![Screen Shot 2020-12-28 at 9.23.44 AM.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/bfa78dab-46cc-4f5f-83ac-f0b681fd2913)
![Screen Shot 2020-12-28 at 9.23.53 AM.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/5b59fca1-b1ad-4f56-a729-28e60e97405e)

**Comment by msmanak** [comment]
![Screen Shot 2020-12-28 at 3.56.03 PM.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/e92c886e-640e-4cc5-a60c-cd8514c4a6c9)![Screen Shot 2020-12-28 at 3.55.53 PM.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/5c7993bd-eeeb-4c2e-9be4-83498ed2e46e)


![Slice-delete.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/db2a7f94-88cf-4c43-a786-c75245400793)

**Comment by bridgethapner** [comment]
I included Meli's option 2 design of this flow in the prototype on the home phone screen, the flow can be triggered from here: https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/442018169

### Just to sum up the feature in 1 place:
- Users should be able to delete any profile information (except Mailing Address) from the edit screen, there will be no edit buttons in the overall Personal & Contact information screen.
- A delete button should only appear when the user currently has information to delete. 
- We will use the Large Button CC and labels should follow the convention "**Remove [name of information]**". 
- When users hit this button, the button should be replaced with a Warning Alert CC that offers two options: **Confirm** or **Cancel**. The copy of the Warning Alert should follow the pattern of: 

Headline: **Are you sure you want to delete [specific form]?**
Body: This will delete your [specific form/task] across many VA records. You can always come back to your profile later if you'd like to add this information back in.
