### ISSUE TITLE
Create Pact Tests

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#16989]
## User Story

As a QA engineer verifying and validating the development of the Vaccine Prep Tool, I need to create Pact tests in order to verify the endpoints used for the product remain available and functioning as expected over time.

## Acceptance Criteria

- [x] Survey the existing [skeletal back-end](https://github.com/department-of-veterans-affairs/vets-api/tree/covid-19-vaccine-registry-service)
- [x] Discuss proper Pact implementation with SMEs on VSP BE-tools team
- [x] Create relevant Pact test

**Comment by holdenhinkle** [comment]
`vets-website branch`: `16989_create_pact_tests`

**Comment by holdenhinkle** [comment]
`vets-api` branch: `16989_create_pact_tests_covid_vaccine`

**Comment by holdenhinkle** [comment]
PRs submitted:
BE - https://github.com/department-of-veterans-affairs/vets-api/pull/5466
FE - https://github.com/department-of-veterans-affairs/vets-website/pull/15281

**Comment by holdenhinkle** [comment]
BE PR merged

**Comment by holdenhinkle** [comment]
New BE branch - 16989_create_pact_tests_for_get_and_patch_requests

PR status for FE (https://github.com/department-of-veterans-affairs/vets-website/pull/15281) was changed to **draft** so it's not accidentally approved and so I can add additional tests for getting and updating saved registration data.

**Comment by holdenhinkle** [comment]
PR submitted for FE consumer tests - https://github.com/department-of-veterans-affairs/vets-website/pull/15281

PR submitted for BE provider tests - https://github.com/department-of-veterans-affairs/vets-api/pull/5508

**Comment by holdenhinkle** [comment]
PRs needed to be approved still.

**Comment by pjhill** [comment]
@holdenhinkle 
- [ ] Request approval from code owners via Slack

**Comment by holdenhinkle** [comment]
The Pact Broker has been down since Thursday. I verified the contracts locally. As soon as the broker is back up I'll rerun `test_and_build` in Circle for the consumer which will verify the pacts, then we'll get this merged!

**Comment by holdenhinkle** [comment]
```
Verifying a pact between Coronavirus Vaccination and VA.gov API
  Given registration data does not exist
    a GET request
      with GET /covid_vaccine/v0/registration
        returns a response which
          has status code 404
          has a matching body
          includes headers
            "Content-Type" which matches /^application\/json/
  Given registration data exists
    a GET request
      with GET /covid_vaccine/v0/registration
        returns a response which
          has status code 200
          has a matching body
          includes headers
            "Content-Type" which matches /^application\/json/
  Given unauthenticated user submits registration data
    a POST request
      with POST /covid_vaccine/v0/registration
        returns a response which
          has status code 201
          has a matching body
          includes headers
            "Content-Type" which matches /^application\/json/
  Given authenticated user submits registration data
    a POST request
      with POST /covid_vaccine/v0/registration
        returns a response which
          has status code 201
          has a matching body
          includes headers
            "Content-Type" which matches /^application\/json/

4 interactions, 0 failures
```

**Comment by holdenhinkle** [comment]
The Pact Broker is still not available:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/031c4343-83f6-4d22-941f-16ff1e4f0d34)

**Comment by holdenhinkle** [comment]
This was just merged to master.

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/dcb5836d-b49d-4a4b-ae68-085e5e96eb20)

**Comment by pjhill** [comment]
Hooray, it is done! Thanks for sticking with this and shepherding it to the finish line, Holden.
