### ISSUE TITLE
508-defect-2 [COGNITION]: Checkbox selections MUST be clear to the user on the review information page 

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#16997]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a user with cognitive considerations, I want to know what I've selected on the review information page so I do not get confused.

## Details

If a user does not check the "I live on a United States military base outside of the U.S." checkbox, it will appear on the review information page as a blank selection instead of yes/no. View screenshot for more details.

## Acceptance Criteria

- [ ] If a user does not make a selection for the "I live on a United States...", "No" is programmatically registered as the response.

## Environment

* Operating System: all
* Browser: any
* Screenreading device: any
* Server destination: staging, production

## Steps to Recreate

1. Enter `https://staging.va.gov/careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832/claimant-address` in browser.
2. Start the application without signing in.
3. On Step 1 of 2, do not check the "I live on a United States..." checkbox.
4. Continue through the flow to the review information page.
5. Expand the applicant information accordion.
6. Confirm no response is registered for the "I live on a United States..." question.

## Solution

The quick workaround solution would be to program a checked response as a "yes" and an unchecked response as a "no." This should resolve the problem on the review information page.

However, if time exists, I recommend revisiting the form flow. Since checking the "I live on a United States..." checkbox dynamically updates fields on the page it exists on, a more robust and elegant solution might be to:
- Rewrite and add a visible label "Do you live on a United States military base outside of the U.S.?"
- Use "yes" and "no" radio buttons instead of a checkbox.
- Place the question on its own page ahead of the rest of the applicant information fields. This will remove the need of dynamically updating the page.

### Before
<img width="690" alt="Screen Shot 2020-12-07 at 11 18 11 AM" src="https://user-images.githubusercontent.com/14154792/101381108-58b49400-3884-11eb-9e11-2ed952118d47.png">

### After, Workaround
<img width="671" alt="Screen Shot 2020-12-07 at 12 05 13 PM" src="https://user-images.githubusercontent.com/14154792/101381202-77b32600-3884-11eb-8676-938f8dd4c09d.png">

### After, Radio Buttons
<img width="732" alt="Screen Shot 2020-12-07 at 12 06 07 PM" src="https://user-images.githubusercontent.com/14154792/101381335-a0d3b680-3884-11eb-83f2-af34ca78a786.png">

**Comment by jason-gcio** [comment]
The suggestion to change this question to a radio yes/no button is an interesting one as it is the ONLY way the Form System will show the results clearly.  

All checkboxes would need to be removed as they don't result in a "yes" or a "no" (in this case anyway, sometimes other checkbox scenarios are relaying different pieces of info like multiple choice). The best solution might be to have the results for checkboxes to pass either either their answer, yes/no or true false as opposed to one-offing in this scenario.  The thinking is that this could end up creating more overhead over all.

We should maybe chat more on this?

**Comment by joshkimux** [comment]
@jason-gcio Would love to chat more about this sometime! 😄

**Comment by jason-gcio** [comment]
This has been fixed, similar to https://github.com/department-of-veterans-affairs/va.gov-team/issues/12996
