### ISSUE TITLE
Create Load Tests

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#16991]
## User Story

As a QA engineer verifying the performance of the vaccine prep tool under load, I need to examine the skeletal back-end, plan for load testing based on analysis of comparable tools, and create load tests in Locust.

## Acceptance Criteria

- [x] Using the skeletal back-end available in [this branch of vets-api](https://github.com/department-of-veterans-affairs/vets-api/tree/covid-19-vaccine-registry-service), plan for a load test of the likely vets-api endpoints.
- [x] Using comparable product launches, discuss likely load on the tool with the product team as well as the VSP analytics team
- [x] Work with the VSP operations team to understand the effect of the likely product load on infrastructure and inform VSP operations team of upcoming load tests
- [x] Create a load test in Locust and store in the [devops repository](https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest)

**Comment by pjhill** [comment]
Additional thought re: execution of the load tests -- let's proactively coordinate the timing of the execution with the vaccine prep tool dev team. I believe current estimates are to have a fairly final fully wired up implementation available after the daily deploy on Thursday 12/10 @ 2pm.

**Comment by pjhill** [comment]
Feedback from the analytics teams regarding estimating load --

> It looks like peak hourly users (total users) is around 370K users with the peak hour being 11AM. For an estimate using the covid screening tool, the peak daily unique pageviews is around 85K and the peak hourly unique pageviews is around 16K and that is happening between 7AM-8AM (I assume due to people coming into work).

**Comment by pjhill** [comment]
## Unauthenticated endpoint
### 10 minute run at 10 requests / second (target 36,000 peak hourly users)
|Name|# requests                    |50% |66%|75%|80%|90%|95% |98%|99% |99.9%|99.99%|100%|
|----|------------------------------|----|---|---|---|---|----|---|----|-----|------|----|
|POST /covid_vaccine/v0/registration/unauthenticated|5715                          |340 |350|370|390|500|720 |1100|1600|3000 |3600  |3600|
|Aggregated|5715                          |340 |350|370|390|500|720 |1100|1600|3000 |3600  |3600|

|Method|Name                          |# requests|# failures|Median response time|Average response time|Min response time|Max response time|Average Content Size|Requests/s|
|------|------------------------------|----------|----------|--------------------|---------------------|-----------------|-----------------|--------------------|----------|
|POST  |/covid_vaccine/v0/registration/unauthenticated|5715      |0         |340                 |403                  |297              |3564             |160                 |9.54      |
|None  |Aggregated                    |5715      |0         |340                 |403                  |297              |3564             |160                 |9.54      |


### 30 minute run at 10 requests / second (target 36,000 peak hourly users)
|Name|# requests                    |50% |66%|75%|80%|90%|95% |98%|99% |99.9%|99.99%|100%|
|----|------------------------------|----|---|---|---|---|----|---|----|-----|------|----|
|POST /covid_vaccine/v0/registration/unauthenticated|17256                         |350 |360|370|390|460|570 |820|1200|3700 |7000  |7100|
|Aggregated|17256                         |350 |360|370|390|460|570 |820|1200|3700 |7000  |7100|

"Method","Name","# requests","# failures","Median response time","Average response time","Min response time","Max response time","Average Content Size","Requests/s"
"POST","/covid_vaccine/v0/registration/unauthenticated",17256,0,350,396,313,7134,160,9.59
"None","Aggregated",17256,0,350,396,313,7134,160,9.59

## Authenticated endpoint
### 10 minute run at 10 requests / second (target 36,000 peak hourly users)
|Method|Name                          |# requests|# failures|Median response time|Average response time|Min response time|Max response time|Average Content Size|Requests/s|
|------|------------------------------|----------|----------|--------------------|---------------------|-----------------|-----------------|--------------------|----------|
|POST  |/covid_vaccine/v0/registration|5659      |0         |420                 |493                  |320              |4591             |160                 |9.44      |
|None  |Aggregated                    |5659      |0         |420                 |493                  |320              |4591             |160                 |9.44      |

|Name|# requests                    |50% |66%|75%|80%|90%|95% |98%|99% |99.9%|99.99%|100%|
|----|------------------------------|----|---|---|---|---|----|---|----|-----|------|----|
|POST /covid_vaccine/v0/registration|5659                          |420 |490|540|560|660|800 |1600|1900|3000 |4600  |4600|
|Aggregated|5659                          |420 |490|540|560|660|800 |1600|1900|3000 |4600  |4600|


### 30 minute run at 10 requests / second (target 36,000 peak hourly users)
|Name|# requests                    |50% |66%|75%|80%|90%|95% |98%|99% |99.9%|99.99%|100%|
|----|------------------------------|----|---|---|---|---|----|---|----|-----|------|----|
|POST /covid_vaccine/v0/registration|17294                         |330 |340|350|370|450|560 |800|1200|2400 |3500  |3600|
|Aggregated|17294                         |330 |340|350|370|450|560 |800|1200|2400 |3500  |3600|

|Method|Name                          |# requests|# failures|Median response time|Average response time|Min response time|Max response time|Average Content Size|Requests/s|
|------|------------------------------|----------|----------|--------------------|---------------------|-----------------|-----------------|--------------------|----------|
|POST  |/covid_vaccine/v0/registration|17294     |0         |330                 |373                  |286              |3598             |160                 |9.61      |
|None  |Aggregated                    |17294     |0         |330                 |373                  |286              |3598             |160                 |9.61      |

**Comment by pjhill** [comment]
# Results 12/14 at 11:30AM
## Overall
|Name                                                                                                                                        |# reqs                            |# fails         |Avg        |Min   |Max       |Median  |req/s     |failures/s|
|--------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------|----------------|-----------|------|----------|--------|----------|----------|
| POST /covid_vaccine/v0/registration                                                                                                        |602935                            |1(0.00%)        |378        |92    |12030     |250     |669.17    |0         |
|Aggregated                                                                                                                                  |602935                            |1(0.00%)        |378        |92    |12030     |250     |669.17    |0         |

## Response time percentiles (approximated)
|Type|Name                          |50%|66%|75%|80%|90%|95% |98% |99% |99.90%|99.99%|100% |# reqs|
|----|------------------------------|---|---|---|---|---|----|----|----|------|------|-----|------|
|POST|/covid_vaccine/v0/registration|250|310|370|420|740|1100|1700|2200|4500  |6300  |12000|602935|
|None|Aggregated                    |250|310|370|420|740|1100|1700|2200|4500  |6300  |12000|602935|

## Error report
|# occurrences|Error                         |
|-------------|------------------------------|
|1            |POST /covid_vaccine/v0/registration: "HTTPError('500 Server Error: Internal Server Error for url: https://staging-api.va.gov/covid_vaccine/v0/registration')"|

**Comment by rjohnson2011** [comment]
Update (1/6): 
I have refactored the locust files to be compatible with the latest version of Locust and added a main.conf file to run the file, which is in line with the previously use test_args files in each directory.
https://github.com/department-of-veterans-affairs/devops/compare/update-locust
After speaking with @pjhill we are going to go about executing each based on a Kanban style.

**Comment by pjhill** [comment]
This test was previously blocked by the upgrade to Locust 1.4.1. The PR completing the upgrade to Locust has been merged and this test is now complete and works with the version of Locust in the `devops` repo.
