### ISSUE TITLE
[Pre-release] Improve local development experience for content-build repository 

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#16995]
The current (and plan for) vets-website and content-build repos are decoupled so that an developer updating CSS or JS for the main vets site (i.e. something not in an application) isn't really possible.

The goal here is to make updates viewable locally without breaking apart all the assets and rearchitecting the system.

**Comment by timwright12** [comment]
PR here: https://github.com/department-of-veterans-affairs/content-build/pull/35

**Comment by meganhkelley** [comment]
@timwright12 is there any work remaining here or should we close this ticket?

**Comment by timwright12** [comment]
@meganhkelley This is complete, I'll close it. Sorry about that.
