### ISSUE TITLE
[Front-End] Web version -Candidate Address Validation

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1700]
## Background

We want the Vet360 API to return to us an array of "candidate addresses" -- or addresses that the user might have intended to type in.

We should consume those addresses and display them to the user, allowing them to choose/ confirm a candidate address for re-submission to Vet360 API for validation.

1. All states of address validation.
2. All specs so they know how things work.
3. All copy.

## User Story  

As an authenticated user, I would like to see a selection of optional addresses if the current address submitted is not recognized by the API, so I can select the appropriate address or chose to "confirm"/ override what is already input.  

1.  The entered address is invalid and the user can either 'Edit address' or 'Cancel'. The user cannot 'Continue' and override with their entered address in this scenario. 

![GetImage.png](https://images.zenhubusercontent.com/5d49a29bd20fa472c4995d30/f9264bb5-9f79-449f-8be7-3c279c5ff1b6)

2.  The entered address is invalid and the user can 'Edit address', select one of the address suggestions to 'Continue' or 'Cancel'. The change here is that the user cannot select their entered address. 

![GetImage (1).png](https://images.zenhubusercontent.com/5d49a29bd20fa472c4995d30/dd192eca-b9f1-47b9-939e-f11ed0c6fbbc)

## COPY 

If you think the address you entered is correct, please call VA benefits at 800-827-1000 for additional assistance. If you have hearing loss, call TTY: 711.

## Goal

 - We are not allowing the user to override our address validation with the original address they entered.
- In this case, we will still show suggestions if we have them.
- We will allow them to go back and edit their address.

## Acceptance Criteria  
# Address validation response handling acceptance criteria
The front end should handle different responses from the address validation/suggestion endpoint (`POST v0/profile/address_validation`) as follows:

1. If the response is a single deliverable suggestion (`"delivery_point_validation": "CONFIRMED"`) with a `"confidence_score"` greater than 80, the user should not see any suggestions. Instead the address the user has entered should be sent directly to the save/update endpoint and the address change flow will appear to function exactly like it does today.
2. If the response is a single deliverable suggestion with a confidence score of less than 80, show the user the suggestion. If the response included a `"validation_key"` then we should also give the user the ability to use the address that they had originally entered.
3. If the response is an error with a validation key, tell the user that the address appears to be incorrect/invalid and prompt them to go back and edit what they entered, but allow them to force it through.
4. If the response is an error _without_ a validation key, tell the user that the address appears to be incorrect/invalid and prompt them to go back and edit what they entered. Do not give them the option to force the address through. Instead present them with a help desk phone number to call if they are sure the address they entered was correct (even though the help desk can't do much at this point).
5. If the response is a single suggestion with a `"delivery_point_validation"` value of `"STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER"` or `"STREET_NUMBER_VALIDATED_BUT_BAD_UNIT_NUMBER"`, tell the user that they appear to have left off the unit number or entered an invalid unit number and prompt them to edit. But also give them the option to force the address through.
6. If the response returns multiple suggestions, only show them the `"CONFIRMED"` addresses. Also prompt them to go back and edit if none of the suggestions are their address. Finally, if there is validation key, allow them to force through the address that they entered. But if there isn't a validation key, present them with a help desk phone number to call if they are sure the address they entered was correct (even though the help desk can't do much at this point).
7. In any other case (I'm not sure what cases are missed here) tell the user that the address does not appear to be correct and prompt them to go back and edit. Also present them with a help desk phone number.

### For case 1
```
{
  "address": {
    "address_line1": "225 irving st #1",
    "city": "San Francisco",
    "address_pou": "RESIDENTIAL",
    "address_type": "DOMESTIC",
    "country_name": "United States",
    "state_code": "CA",
    "zip_code": "94123"
  }
}

{
  "addresses": [
    {
      "address": {
        "address_line1": "225 Irving St Apt 1",
        "address_type": "DOMESTIC",
        "city": "San Francisco",
        "country_name": "USA",
        "country_code_iso3": "USA",
        "county_code": "06075",
        "county_name": "San Francisco",
        "state_code": "CA",
        "zip_code": "94122",
        "zip_code_suffix": "2633"
      },
      "address_meta_data": {
        "confidence_score": 88.0,
        "address_type": "Domestic",
        "delivery_point_validation": "CONFIRMED",
        "residential_delivery_indicator": "RESIDENTIAL"
      }
    }
  ],
  "validation_key": 95384771
}
```

### For case 2
```
{
  "address": {
    "address_line1": "110 washingtonn",
    "city": "portland",
    "state_code": "or",
    "zip_code": "97215",
    "zip_code_suffix": ""
  }
}

{
  "addresses": [
    {
      "address": {
        "address_line1": "110 SE Washington St",
        "address_type": "DOMESTIC",
        "city": "Portland",
        "country_name": "USA",
        "country_code_iso3": "USA",
        "county_code": "41051",
        "county_name": "Multnomah",
        "state_code": "OR",
        "zip_code": "97214",
        "zip_code_suffix": "2127"
      },
      "address_meta_data": {
        "confidence_score": 77.0,
        "address_type": "Domestic",
        "delivery_point_validation": "CONFIRMED",
        "residential_delivery_indicator": "BUSINESS"
      }
    }
  ],
  "validation_key": 1272603069
}
```

### For case 3
This is actually a terrible example and is only shown so you can see _where_ the `validation_key` is buried in the response. But because this error has `"severity": "ERROR"` our backend should be stripping off the validation key since this is not an overrideable error.

```
{
  "address": {
    "address_line1": "washingtonn",
    "city": "portland",
    "state_code": "or",
    "zip_code": "97215",
    "zip_code_suffix": ""
  }
}

{
  "errors": [
    {
      "title": "Address Validation Error",
      "detail": {
        "address": {
          "state_province": {
            "name": "Oregon",
            "code": "OR"
          },
          "country": {
            "name": "USA",
            "code": "USA",
            "fips_code": "US",
            "iso2_code": "US",
            "iso3_code": "USA"
          },
          "address_line1": "Washingtonn",
          "city": "Portland",
          "zip_code5": "97215"
        },
        "geocode": {
          "calc_date": "2019-11-14T15:44:09+00:00",
          "location_precision": 0.0,
          "latitude": 45.5151,
          "longitude": -122.5999
        },
        "address_meta_data": {
          "confidence_score": 0.0,
          "address_type": "Unknown",
          "delivery_point_validation": "MISSING_ZIP",
          "validation_key": 457300252
        },
        "messages": [
          {
            "code": "ADDRVAL112",
            "key": "AddressCouldNotBeFound",
            "severity": "ERROR",
            "text": "The Address could not be found"
          }
        ]
      },
      "code": "VET360_AV_ERROR",
      "status": "400"
    }
  ]
}
```

### For case 5
```
{
  "address": {
    "address_line1": "225 irving st",
    "city": "San Francisco",
    "state_code": "CA",
    "zip_code": "94122",
    "zip_code_suffix": ""
  }
}

{
  "addresses": [
    {
      "address": {
        "address_line1": "225 Irving St",
        "address_type": "DOMESTIC",
        "city": "San Francisco",
        "country_name": "USA",
        "country_code_iso3": "USA",
        "county_code": "06075",
        "county_name": "San Francisco",
        "state_code": "CA",
        "zip_code": "94122",
        "zip_code_suffix": "2652"
      },
      "address_meta_data": {
        "confidence_score": 98.0,
        "address_type": "Domestic",
        "delivery_point_validation": "STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER",
        "residential_delivery_indicator": "RESIDENTIAL"
      }
    }
  ],
  "validation_key": 2125510284
}
```

### For case 6
```
{
  "address": {
    "address_line1": "400 65th St",
    "city": "seattle",
    "state_code": "WA",
    "zip_code": "12345"
  }
}

{
  "addresses": [
    {
      "address": {
        "address_line1": "400 N 65th St",
        "address_type": "DOMESTIC",
        "city": "Seattle",
        "country_name": "USA",
        "country_code_iso3": "USA",
        "county_code": "53033",
        "county_name": "King",
        "state_code": "WA",
        "zip_code": "98103",
        "zip_code_suffix": "5252"
      },
      "address_meta_data": {
        "confidence_score": 100.0,
        "address_type": "Domestic",
        "delivery_point_validation": "UNDELIVERABLE"
      }
    },
    {
      "address": {
        "address_line1": "400 NW 65th St",
        "address_type": "DOMESTIC",
        "city": "Seattle",
        "country_name": "USA",
        "country_code_iso3": "USA",
        "county_code": "53033",
        "county_name": "King",
        "state_code": "WA",
        "zip_code": "98117",
        "zip_code_suffix": "5026"
      },
      "address_meta_data": {
        "confidence_score": 100.0,
        "address_type": "Domestic",
        "delivery_point_validation": "CONFIRMED",
        "residential_delivery_indicator": "RESIDENTIAL"
      }
    },
    {
      "address": {
        "address_line1": "400 NE 65th St",
        "address_type": "DOMESTIC",
        "city": "Seattle",
        "country_name": "USA",
        "country_code_iso3": "USA",
        "county_code": "53033",
        "county_name": "King",
        "state_code": "WA",
        "zip_code": "98115",
        "zip_code_suffix": "6463"
      },
      "address_meta_data": {
        "confidence_score": 98.0,
        "address_type": "Domestic",
        "delivery_point_validation": "STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER",
        "residential_delivery_indicator": "RESIDENTIAL"
      }
    }
  ],
  "validation_key": 178464079
}
```

## Definition of Done  

- [ ] Front-End Development work has been developed for web version

- [ ] QA Testing validated and completed

- [ ] Ticket can be closed.

**Comment by lkoenigsberg** [comment]
See some previous work that might be relevant to this at https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11339 but please use this ticket to continue the conversation as needed.

**Comment by Justin-Pickett** [comment]
I tagged both @erikphansen and @mojaray2k on this work. Whoever has the bandwidth to pick this up when ready please update the ticket.
