### ISSUE TITLE
Rogers STEM Scholarship: SCO Outreach Language

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#17014]
Including 2 small updates to the 22-10203 form to let users know their School Certifying Official will be contacted to help support claim development.  Applicant is notified via a blue info alert (cleared with Emily) on the page where they're inputting school info.  The applicant also receives an email with a copy of the email which goes to the SCO requesting background on the student.  

For you:
1. Review the info alert.  Content below and 2 images showing where the alert appears. 
2. Review the intro content for the email.  (The balance of the email is a copy of the email sent to SCOs). 

Please let me know if you have any questions. An estimated turnaround on this work would be helpful.  Thanks!! 

**STORY ASSETS**

**[Link to email sent to applicant](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-SCO-ApplicantCC-email-20201202.md)** 

**Info alert content:** To help confirm your eligibility, we'll reach out to the School Certifying Officials (SCO) at the school where you'd like to use the scholarship. 

Info alert display
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/ae74b164-2760-492c-b616-aeb3ab8c0562)

Full page display
![stem-3-school-details copy 4-B.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/b474191b-4858-4134-bc59-e656df7f0b0d)

**Comment by peggygannon** [comment]
Hi, @amyknox Please below my content recommendations for the STEM alert and email. Please let me know if you have any questions. 


{Alert}
We’ll be reaching out to the School Certifying Official (SCO) at this school to confirm your eligibility for the scholarship. 

-----

A couple of notes: 
- I recommend putting Roger STEM scholarship earlier in the email subject. 
- My content recommendations are making the language  more active voice

{Email}
Email subject: VA Rogers STEM Scholarship outreach 

Dear << full name from application >>,
We sent the email below to the School Certifying Official (SCO) at << name of school >> to gather information for your Rogers STEM Scholarship application. If the SCO doesn’t respond within 14 days, we’ll follow up with them for the information we need.

Thank you,
Rogers STEM Scholarship Team
VA Buffalo Regional Processing Office

**Comment by amyknox** [comment]
@peggygannon - Education came back with a tweak or 2.  How does this work for you?

We sent the email below to the School Certifying Official (SCO) at << name of school >> to gather information for your Edith Nourse Rogers STEM Scholarship application. We’ll follow-up with the SCO when we process your application for any additional information we need.

**Comment by peggygannon** [comment]
Hi, @amyknox thanks for following up. The SME edits look fine.
