### ISSUE TITLE
Screens using the TextArea components had too much of a margin above and below the text area

### ISSUE THREAD

**Issue by komaly15** [department-of-veterans-affairs/va.gov-team#17017]
Screens using the textArea component had bigger margins above and below the textArea because the textArea also had a margin top and bottom. TextArea needs top and bottom margin to be removed, an components using the TextArea need to be updated

Example: Contact VA screen has too much of a margin between the Veterans Crisis line banner and the TextArea containing the screens text

**Comment by digitalken** [comment]
PASS 12/9/2020 - Top and bottom margins look correct on the various screens now.
