### ISSUE TITLE
Access for Christopher Alexander

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#17025]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Christopher Alexander
- Please Provide your email.
   > chris.alexander@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Front End Tools, Senior Software Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here]
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTvv/EZNucTDMVpqsSrBq1+9auQE8eQ/htdZbQXYK8YAzDYbk42a/AcWoxOgb0dJ80ZeBGG7qqSZAIlZ0Rme3LwRrW6DsY6ddX2YviTl4YA3ZPc79i5m5m/c9JusbH4r6B8ICsH3Vehp+j1s5ThqQWr76J/NyZC5egxh1wnVvL+xb4NfI2pR+1MqgzfjUo0KHj2caTk3oSE1QwX6d1AhWDsb3fB/nPoMic6sXa+Hi16HajUY3RJOIRwWZh1mSLkBN8nmbFWyzBq+M8xAhGIDzeDZ3XPjHlRM+CNk4TPr4S6G1b3/i2oKCjn+Ll8oiXmSK9Lhdg4ctd8utw2HJ2toxTc2Ma9WavSBWWGANV/h96EsAXDar+OaHC2D+OuFrhOnZ9CnWQjvxpKbkvmS5fbMv1nBkX6QzSDXCSUdLAULDhuozvK5D6ig8NbBLCN7vqeZR75kU3V8DyoyocuQFpnzeywNq+nsnonbu/iQYc3uzXSmjYD7jXMNz4K/hmd6MJGFc= chris.alexander@adhocteam.us
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by pnwstevan** [comment]
Hi @alexandec!

We'll need your AdHoc email, not your personal email for this request.

Please update this issue with that and I'll provision SOCKS access ASAP.

**Comment by alexandec** [comment]
Hi @pnwstevan, updated it!

**Comment by pnwstevan** [comment]
Hi @alexandec 

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

Once you've confirmed access, please close this issue.  Reach out for any help needed!

**Comment by alexandec** [comment]
It's working great, thanks @pnwstevan!
