### ISSUE TITLE
STEM - Stand Alone: Format Applicant CC email per VA styles

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17029]
Use VA.gov HTML email format for cc email

**Comment by amyknox** [comment]
Email to student: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-SCO-ApplicantCC-email-20201202.md

Email to SCO (for lower portion of email): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-SCO-email-20200804.md

**Comment by watersemma** [comment]
Email to student: https://bahdigital.invisionapp.com/share/VRIAFTR6C3H

Email to SCO: https://bahdigital.invisionapp.com/share/F9IAFTSGBNQ
