### ISSUE TITLE
STEM - Stand Alone: Update Applicant CC email per DEPO

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17028]
Update applicant cc email per DEPO recommendations

**Comment by amyknox** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-SCO-ApplicantCC-email-20201202.md


Updated alert text for form (per DEPO): 
{Alert}
We’ll be reaching out to the School Certifying Official (SCO) at this school to confirm your eligibility for the scholarship.
