### ISSUE TITLE
Update avg number of days on disability page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#1703]
## User Story
As a Veteran, I need to know how long it typically takes to decide a claim, so I have better expectations on the process. As a VBA stakeholder, I need to provide this information as part of federal guidelines.

**[Replace this content...]**

109
Average number of days to complete disability-related claims in July 2019 

From Misty Sweet: 
**[...on this page...]**

https://www.va.gov/disability/how-to-file-claim/ **_and_** 
https://www.va.gov/disability/after-you-file-claim/

**[...with this content...]**

82.5
Average number of days to complete disability-related claims in August 2019.

V/R
Misty

## Goal
_What outcome(s) do we want to see?_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
@RLHecht (and fysa @Karak888 ) Please make this content update in Github instance this week. I was waiting to do this in Drupal, but because Disability hub pages in Drupal are going to take longer than expected to get out of UAT, this change now needs to be made in GH to be timely.

**Comment by jenniferlee-dsva** [comment]
This change will need to be made in the Drupal instance for 1:1 UAT/Github parity: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1020#event-2562405819

**Comment by RLHecht** [comment]
@jenniferlee-dsva These changes have been made in Github. Here's the PR for the branch: https://github.com/department-of-veterans-affairs/vagov-content/pull/556

FYI @Karak888

**Comment by Karak888** [comment]
need to have this updated in drupal instance so @Karak888 will follow up with @randi and get back to Jen.

**Comment by Karak888** [comment]
@RLHecht @peggygannon is this good to close or not just yet?  Thanks!

**Comment by RLHecht** [comment]
It was updated in Github but I haven't updated in Drupal. Is this out of UAT and able to be worked on @jenniferlee-dsva ?

**Comment by jenniferlee-dsva** [comment]
Disability pages are not out of UAT yet.

**Comment by RLHecht** [comment]
@peggygannon I just made these changes to the two pages in Drupal. Can you please check them? FYI @jenniferlee-dsva

**Comment by peggygannon** [comment]
@RLHecht I checked the pages in Drupal. The updates look good.

**Comment by Karak888** [comment]
moving to close this as updates have been made in GH and in Drupal
