### ISSUE TITLE
CT Redesign: Internal ideation workshop

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17038]
Internal workshop to identify next steps for design effort  
Create stories for design / prototyping based on decisions

**Comment by amyknox** [comment]
Document takeaways then close.

**Comment by watersemma** [comment]
Takeaways have been documented in the mural board. https://app.mural.co/invitation/mural/bahdigitalexperience6902/1607448875956?sender=jonesjennifer26349&key=c360d65b-66dc-4b52-aeac-bca3fda82cbe
