### ISSUE TITLE
Analytics dashboard request for Vaccine Content Viewing

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17049]
# Request a KPI Dashboard

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.
- [ ] New dashboard
- [x] Iteration of current dashboard

Add Vaccine information from the Covid FAQ page/Hub to the Vaccine tab. 

Add the following
Bar chart for interactions related to the Vaccine on the FAQ page.

@DanielleThierryUSDSVA do you have information on where we can find this data? Or if we need to start an implementation ticket to track it?

![image](https://user-images.githubusercontent.com/48964695/101415289-a39acf80-38b5-11eb-9068-c29ac97dbb6c.png)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
@DanielleThierryUSDSVA - is there a separate Vaccine content Hub that we should be tracking?

**Comment by joanneesteban** [comment]
@bsmartin-ep to triage any current FAQ Vaccine data over to @JasonTheBearded to start pulling into Domo.

**Comment by joanneesteban** [comment]
## Sending a secure message for questions about the vaccine on the FAQ page

eventCategory: "Interactions",   eventAction: "Navigation - COVID - send a secure message to your provider - https://www.va.gov/health-care/secure-messaging",   eventLabel: "nav-covid-link-click"

**Comment by DanielleThierryUSDSVA** [comment]
@joanneesteban there will be a new vaccine page soon, yes, but it's not up yet. it will be at https://www.va.gov/health-care/covid-19-vaccine (vanity url: www.va.gov/covid-19-vaccine).

there will also be a tool that's up on staging now: https://staging.va.gov/health-care/covid-19-vaccine/stay-informed/

**Comment by joanneesteban** [comment]
Thanks, @DanielleThierryUSDSVA ! When are you planning on launching the vaccine page? We'll look for a Google Tag Manager implementation ticket to prioritize tracking for that when you're ready.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @joanneesteban. Just got approval on the vaccine page and it's launching today.

**Comment by joanneesteban** [comment]
@DanielleThierryUSDSVA can you please open a [GTM implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) today? As of right now, we don't have any analytics on this page.

**Comment by joanneesteban** [comment]
@bsmartin-ep please prioritize this ticket when it comes in.

**Comment by joanneesteban** [comment]
Actually, @DanielleThierryUSDSVA , it looks like y'all already implemented some analytics! 🎉

We're collecting:
- Page views
- Outbound clicks
- Page entries
- Jumplinks
- Accordion expand/contracts

Let us know if you're looking for more information, and we can get that started for you.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @joanneesteban. We're moving so fast, I'm sure there a little confusion. I just submitted an issue per your request (https://github.com/department-of-veterans-affairs/va.gov-team/issues/17350). If no longer needed, feel free to close. Thank you!

**Comment by joanneesteban** [comment]
@JasonTheBearded would you be able to take a look at the jumplink clicks chart on the Covid dashboard? We should be starting the axes at 0 instead of negative.

**Comment by JasonTheBearded** [comment]
@joanneesteban Fixed!

**Comment by joanneesteban** [comment]
Thank you thank you! Also, @JasonTheBearded is it possible to make the `Vaccine questions being asked` chart title dynamic? Add the date ranges?

**Comment by JasonTheBearded** [comment]
@joanneesteban it is indeed. Let me know if you'd like different flavor text or date formats.

**Comment by joanneesteban** [comment]
Thanks, @JasonTheBearded ! I think the only update is that the time frame text for this & the funnel charts are bigger than the chart titles themselves - could we make them smaller than the titles?

**Comment by joanneesteban** [comment]
Moving to Review. Can close after hearing back from Lauren.

**Comment by joanneesteban** [comment]
@JasonTheBearded - what's the difference between these two data points/labels on the 'Total jumplink clicks to COVID-19 FAQ Vaccine content` chart?

`Coronavirus vaccine`
`COVID-19 vaccine`

**Comment by joanneesteban** [comment]
Closing this issue. Additional Vaccine dashboard work will be on #17729
