### ISSUE TITLE
Display Rubocop Lint Failures in Jenkins Console Output

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#1704]
## User Story
As a VSF engineer, I want to see the rubocop lint failures when my `vets-api` jenkins build fails.

## More Context
A common use-case for anyone who creates a `vets-api` PR:
1. Open PR
2. See a red x ( ❌ ) from jenkins, e.g.
![image](https://user-images.githubusercontent.com/3077884/64723289-3f187700-d49e-11e9-9be6-8d5990a1a62b.png)
3. Click on red x ( ❌) to see why it failed
4. Jenkins output says the rubocop failed, but doesn'y say why, e.g.
![image](https://user-images.githubusercontent.com/3077884/64723409-7ab34100-d49e-11e9-99d5-ffacde41295f.png)

**Comment by omgitsbillryan** [comment]
This looks to be a "sometimes it displays and sometimes it doesnt case" 

https://dsva.slack.com/archives/C0MQ281DJ/p1547821475118700

**Comment by annaswims** [comment]
Alternatively, we could just run rubocop on Codeclimate and not on Jenkins.  It'd make Jenkins a bit quicker and Codeclimate has output that easier to use. 
... Just a thought.

**Comment by omgitsbillryan** [comment]
Assuming Codeclimate doesn't swallow the output the way our Jenkins/Makefile seems to be doing, then it sounds good to me.

As a VFS dev, I don't really care _where_ the rubocop errors live, I only care that I can view it.

**Comment by annaswims** [comment]
yep, here's an example of lots of rubocop violations https://github.com/department-of-veterans-affairs/vets-api/pull/3263

**Comment by LindseySaari** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/3320
