### ISSUE TITLE
Profile: Document error message text & when errors should display

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17044]
## User Story
Document the text of error messages for Profile screens.

### Domestic address: 
- Error message "Country is required" should display when a user tries to save an address but hasn't selected a country. 
- The error message "Street address is required" should display when a user tries to save an address but hasn't entered the street address.
- Error message "City is required" should display when a user tries to save an address but hasn't entered a city.
- Error message "State is required" should display when a user tries to save an address but hasn't selected a state.
- Error message "Zip code must be 5 digits" should display when a user tries to save an address with a zip code that is not 5 digits.

### Military base address:
- The error message "Street address is required" should display when a user tries to save an address but hasn't entered the street address.
- Error message "City is required" should display when a user tries to save an address but hasn't selected APO/FPO/DPO.
- Error message "State is required" should display when a user tries to save an address but hasn't selected a state.
- Error message "Zip code is required" should display when a user tries to save an address with a zip code.

#### International addresses:
- The error message "Street address is required" should display when a user tries to save an address but hasn't entered the street address.
- Error message "City is required" should display when a user tries to save an address but hasn't entered a city.
- Error message "Postal code is required" should display when a user tries to save an address with a zip code.

#### Phone numbers:
- Error message "Please enter a valid phone number" should display when a user has entered a phone number that is less or more than 9 digits

#### Email address:
- Error message "Please enter your email address again, using this format: X@X.com" when a user tries to save an email address without an @ character 

## Tasks
- [x] Define error text for all error messages
- [x] Define when the errors should display

**Comment by bridgethapner** [comment]
@bessgreen

**Comment by bessgreen** [comment]
@bridgethapner @ayushchak question about the zip code field-level errors described above:

1. "Zip code must be 5 digits" should display when a user tries to save an address with a zip code that is not 5 digits.
2. "Zip code is required" should display when a user tries to save an address with a zip code. 

What differentiates when these will appear? Looking at the designs, it seems like #2 can occur for Domestic Address and Military. Is the difference that #2 appears when the user tries to save a blank field, and #1 appears when the user tries to save an entry that is >0 digits, but not equal to 5?

**Comment by bessgreen** [comment]
@bridgethapner for the phone number field error described above, I'm assuming this should appear when the entry is > or < 10 digits, not 9?
