### ISSUE TITLE
STEM Automated Decision: Format email per VA styles

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17047]
Support dev efforts to create HTML effort for applicant CC. 
In other words: apply VA Notify html email styles; share with BA for dev story

**Comment by amyknox** [comment]
Current automated denial email: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-automated-denial-email.md

**Comment by watersemma** [comment]
Automated denial email: https://bahdigital.invisionapp.com/share/MZIAFTUX65T
