### ISSUE TITLE
Add Delete Button Common Component to Profile Screens

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17058]
## User Story
As a user, I would like to be able to delete any phone number, fax, email, or residential address with one click of a button.

Note: users should not be able to delete their mailing address.

## Tasks
- [x] Add CC component to relevant screens

**Comment by msmanak** [comment]
![Screen Shot 2020-12-28 at 3.56.03 PM.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/e92c886e-640e-4cc5-a60c-cd8514c4a6c9)![Screen Shot 2020-12-28 at 3.55.53 PM.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/5c7993bd-eeeb-4c2e-9be4-83498ed2e46e)


![Slice-delete.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/db2a7f94-88cf-4c43-a786-c75245400793)

**Comment by bridgethapner** [comment]
This can be seen [here](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/442018169) on the home phone screen and should display to every profile screen that has an entry EXCEPT mailing Address
