### ISSUE TITLE
Update UI design of Checkbox Common Component to include an error state

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17055]
## User Story
Update UI design of Checkbox Common Component to include an error state

## Accessibility Considerations

**iOS**

- “{label}. Un-selected”
- “{label}. Selected”
- “Dimmed, {label}. un-selected”
- “Dimmed, {label}. selected “

Helper text:
- “{label}, {helper text}. [then whatever task it performs]

error text:
- “{label}, {error text}. [then whatever task it performs]

**Android**

- "{label}, checkbox.”
- "{label} Selected, checkbox.”
- "{label} Selected-disabled, checkbox.” 
- "{label} Not Selected-disabled, checkbox.” 

Helper text:
- “{label}, {helper text}. [then whatever task it performs]

error text:
- “{label}, {error text}. [then whatever task it performs]

**Comment by msmanak** [comment]
![Slice-checklist error state options.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/21f86b15-5c48-4013-b804-d267efd77f85)

**Comment by msmanak** [comment]
direct deposit example: Please note that in Va.gov there's no checkbox so I couldn't find a content language

![Slice-direct deposit example.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/3f8f6abb-158b-4c5a-b80a-95c4f9f4b569)

**Comment by bridgethapner** [comment]
It looks like there are two options above in the ticket -- I incorporated the design on the right into the prototype [here](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/442012725).

### Documentation for error state of Checkbox CC: 
- Error text: Mobile Body Bold, red secondary-dark #cd2026
- Checkbox border: 2px solid red secondary-dark #cd2026
