### ISSUE TITLE
Health Service Hours data is malformed in CMS Export build

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#17063]
/pittsburgh-health-care/locations/beaver-county-va-clinic/index.html has issues with hours' data:

Issues: 
1. there are `<p>` tags in the hours' data causing extra whitespace
2. `field_hours`= 0  in the cms export which corresponds to facility hours, which are “800AM-430PM”, rather than the specified hours. 
3. Formatting of facility hours does not conform to the styling of facility health service contact info (the non-conforming style comes from upstream, VAST, not CMS.)

<detail> 
Front rendered using GraphQL 

![VA_Pittsburgh_Health_Care___Beaver_County_VA_Clinic.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/2f546605-28bf-40a2-862d-59df9312794b)

---
Front end rendered using CMS Export 

![VA_Pittsburgh_Health_Care___Beaver_County_VA_Clinic.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/26edc9ab-c939-47c2-8df0-49d9b5b156a6)

---

**Comment by mpelzsherman** [comment]
This is due to `field_hours` having the wrong value in the cms export.

On https://prod.cms.va.gov/node/1029/edit:

![Cursor_and_Edit_VAMC_Facility_Health_Service_HIV_hepatitis_-_Beaver_County_VA_Clinic___VA_gov_CMS](https://user-images.githubusercontent.com/80267/101846499-13f85980-3b1f-11eb-8a84-8bb2491aef71.png)

Since we’re getting 0 for `field_hours` in the cms export, we’re using the facility’s hours, which are “800AM-430PM”. (This format doesn’t conform to our [style guide](https://design.va.gov/content-style-guide/dates-and-numbers), BTW.)

**Comment by mmiddaugh** [comment]
@kevwalsh @davidconlon

**Comment by indytechcook** [comment]
This was related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3450, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3592.  This was an issue with the incorrect version of the paragraph being the "current" revision of the paragraph.  I resaved the node and the data should be correct now.

**Comment by mpelzsherman** [comment]
Republishing the data fixed the issue. Thanks @indytechcook !
