### ISSUE TITLE
Staff Profile page using wrong thumbnail image

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#17066]
https://staging.va.gov/pittsburgh-health-care/staff-profiles/alan-petrazzi/index.html

![Alan_Petrazzi___VA_Pittsburgh_health_care___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/175100a5-a4b9-4199-ba4d-4c4e470a7a63)

## CMS Export

![Alan_Petrazzi___VA_Pittsburgh_health_care___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/c6d3ff88-1464-4359-8530-fff10660493a)

**Comment by mpelzsherman** [comment]
Blocked waiting on input from the fe-tools team on how to resolve this issue. See [Slack](https://dsva.slack.com/archives/C01512KN35G/p1607472117471100) for details.

**Comment by jhonnyoddball** [comment]
Based on [slack message](https://dsva.slack.com/archives/C01512KN35G/p1607472117471100) by @mpelzsherman

> In `src/site/stages/build/process-cms-exports/transformers/node-person_profile.js`, 
> we use the `getImageCrop` function to produce the thumbnail image URL we need.
> 
> However, this depends on the page on which this node is used. 
> On `pittsburgh-health-care/programs/cardiology`, for example, we need    
> '_1_1_SQUARE_MEDIUM_THUMBNAIL', 
> 
> but on the staff profile pages 
> (e.g. `pittsburgh-health-care/staff-profiles/donald-koenig/`) we need 
> '_23MEDIUMTHUMBNAIL'.
> 
> How can we make this context-aware? Should I look at the ancestorsobject?

## Findings / Tracking

Based on the current state of `src/site/stages/build/process-cms-exports/transformers/node-person_profile.js`, the `fieldMedia` is using the `_1_1_SQUARE_MEDIUM_THUMBNAIL` image style

```
  fieldMedia:
    entity.fieldMedia && entity.fieldMedia.length > 0
      ? {
          entity: getImageCrop(
            entity.fieldMedia[0],
            '_1_1_SQUARE_MEDIUM_THUMBNAIL',
          ),
        }
      : null,
```

### 1st Scenario

**Expected Image source**
`src="/img/styles/1_1_square_medium_thumbnail/public/2019-05/Dr.%20Ali%20Sonel_20190307_0001.jpg"`

**CMS Image source**
`src="/img/styles/1_1_square_medium_thumbnail/public/2019-05/Dr.%20Ali%20Sonel_20190307_0001.jpg"`

```
  layout: health_care_region_detail_page.drupal.liquid
  path: pittsburgh-health-care/programs/cardiology
  entityId: 772
```

**Page node:** `node.016896fb-cf41-4732-83b0-5d14a4607913.json`
**Transformer:** `health_care_region_detail_page`

Image is inside the `field_content_block` field which is type `paragraph`:
**paragraph node:** `paragraph.40b1bed0-81e6-4c03-bcf6-d1b955cb9bda.json`
**Transformer:** `paragraph-staff_profile`

Inside the paragraph there will be the `field_staff_profile` field which contains a node of type `person_profile`

**Page node:** `node.11c15197-195a-4e11-b6e9-5129a686d7cc.json`
**Transformer:** `person_profile`

`field_media` field
`media.ab1a9277-702b-4527-b3b3-d7dcf78a6671.json`

### 2nd Scenario

**Expected Image source**
`src="/img/styles/2_3_medium_thumbnail/public/2019-08/Donald_E._Koenig-Director-VAPHS_20190531_0002.jpg"`

**CMS Image source**
`src="/img/styles/1_1_square_medium_thumbnail/public/2019-08/Donald_E._Koenig-Director-VAPHS_20190531_0002.jpg"`

```
  layout: person_profile.drupal.liquid
  path: pittsburgh-health-care/staff-profiles/donald-koenig
  entityId: 790
```

**Page node:** `node.ba32a631-a688-467f-92f6-1c730b90d8de.json`
**Transformer:** `person_profile`

`field_media` field
`media.fe94fb3b-2513-45c2-91f7-c002685342ab.json`

### Discrepancy

There are 2 `person_profile` nodes that use 2 different image styles.

How can we determine which one is supposed to be used?

**Comment by jhonnyoddball** [comment]
### Possible solution

Check If parent node is either `entityType` === "paragraph" or  `entityBundle` === "staff_profile"
then we can use `_1_1_SQUARE_MEDIUM_THUMBNAIL` otherwise use `_23MEDIUMTHUMBNAIL`

**Comment by mpelzsherman** [comment]
I created a draft [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15302).

Unfortunately it only works for the first staff profile node on the cardiology page.
I don't know how to handle the second staff profile node.

![VA_Pittsburgh_Health_Care___Cardiology___Veterans_Affairs](https://user-images.githubusercontent.com/80267/101846997-2f179900-3b20-11eb-9e8f-e92cbd8d7a1a.png)
