### ISSUE TITLE
Refactor/flatten 10-10EZ Form Config Schema

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#17071]
## Technical Task

As a developer it is hard to track the context of data through the 10-10CG due to so many references in other files. Simplify this flow by only abstracting shared definitions, and flatten the constant definitions so they are less nested and are easier to read with out linter configuration. This way it will be easier to maintain and refactor in the future.

## Expected Behavior

The form should function exactly the same with the only difference being more clean, readable, and maintainable code.

## Acceptance Criteria

- [x] There is no regression in form functionality
- [x] Pages and chapters are broken up by directory and files

**Comment by mlighdc** [comment]
This will not be done in Sprint 37.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15813)

**Comment by LinnJS** [comment]
Having issues with UT failing on start and not on any particular suite or test case posted in VSP support [here](https://dsva.slack.com/archives/CBU0KDSB1/p1612279739133800)
