### ISSUE TITLE
526 All Claims - edit definition of service-connected disability

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#1707]
@djmunoz1 commented on [Tue Nov 06 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14883)

Currently, the definition of service-connected reads as follows:
![Screen Shot 2018-11-06 at 11.45.42 AM.png](https://images.zenhubusercontent.com/5a008bb78a75884b90863d96/d5144639-16ad-4c02-8d9b-01293b9719c2)

Now, we want to edit the first sentence (per SME request) so it reads:
"To be eligible for service-connected disability benefits, you’ll need to show that your disability was caused by an event, injury, or disease during your military service..."

Where to find the modal:
https://staging.vets.gov/disability-benefits/apply/form-526-all-claims/new-disabilities/follow-up/0
![Screen Shot 2018-11-06 at 11.45.50 AM.png](https://images.zenhubusercontent.com/5a008bb78a75884b90863d96/3ace395c-d7bd-442b-937a-f634081a5e77)

**Comment by Mottie** [comment]
Forgot to connect this to https://github.com/department-of-veterans-affairs/vets-website/pull/10738
