### ISSUE TITLE
Error Handling within vets-api

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1708]
## User Impact
Knowing what errors are possible and how they work can let us better inform the end user about what is happening with their data.

### Tasks
- Investigate what exceptions are baked in the the vets-api today

### Considerations 
- Are they specific to this call we are looking at or is there a general error handling service with EVSS?

### Notes
- What did we learn about those exceptions?
  - Can a list be shared?

### Definition of Done
- [ ] Identified exceptions in the vets-api
- [ ] Any notes for the Call Center should be uploaded to `feature/$feature-name/call-center` in GitHub

**Comment by kathleencrawford** [comment]
@micahchiang i got a 500 error on one of the test users as well.  but i also received this error for test user #2:

{
    "errors": [
        {
            "title": "Forbidden",
            "detail": "User does not have access to the requested resource",
            "code": "403",
            "status": "403"
        }
    ]
}

trying to find out if all the possible error codes are documented somewhere...

**Comment by micahchiang** [comment]
@kathleencrawford - Nice, that's definitely helpful. I wonder what causes a 403 to be returned instead of a 401 or some other error. I got the 401 with tester user + 0 which doesn't have rated disabilities set up, similar to tester user + 2.  I wonder if Silvio would know of all possible error codes and their triggering conditions since he built the /rated_disabilities endpoint.

**Comment by kathleencrawford** [comment]
@micahchiang thats interesting - i could have sworn i got a 500 error using test user +0.  i guess further testing is needed.  i have a follow up call with Silvio today and planned on asking him exactly what you wrote!

**Comment by kathleencrawford** [comment]
Notes from my 1:1 with Silvio...vets-api error mapping can be found here:

https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/locales/exceptions.en.yml

* This is a comprehensive list of all expected exceptions within vets-api, not specific to rated disabilities.

**Comment by kathleencrawford** [comment]
Errors specifically related to the disability compensation form can be found here:

https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/disability_compensation_form/service_exception.rb

**Comment by kathleencrawford** [comment]
@jason-gcio @micahchiang 

Please review my notes/comments above based on my discussion with Silvio.  I think this is enough info to close this ticket but please confirm or let me know if I'm missing anything.

I did not ask about any call center updates as it doesn't look like we'll be adding any new error codes at this point (and I'm assuming that question would be for someone else anyway).

**Comment by kathleencrawford** [comment]
And one more:

https://pint.ebenefits.va.gov/wss-form526-services-web-v2/swagger-ui/index.html?url=https://pint.ebenefits.va.gov/domain1/wss-form526-services-web-v2/rest/swagger.yaml#/

**Comment by jason-gcio** [comment]
Thanks @kathleencrawford & @micahchiang this looks good.  I think I agree that the Call Center probably has these in hand but either way, I put these notes into their folder just in case.  I'll close this!
