### ISSUE TITLE
Create SLO Templates in DataDog

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#17089]
## Description

While the BE Tools team waits for DataDog to have full production infrastructure support, we want to create the SLO reporting templates that will be used to report on when the production data starts being sent.

## Goals
Templates are created in DataDog and ready (the best they can be) to be able to report on SLOs for external services when Production data is available
There is a define path to distribute these reports outside of DataDog to stakeholders who will not navigate to DataDog itself.

## Acceptance Criteria
- [x] SLO definition metrics template is created and ready for use with production data
- [x] Screenboard is available for sharing to stakeholders

**Comment by alexpappasoddball** [comment]
@kfrz here is the ticket for creating the templates we have been discussion

**Comment by alexpappasoddball** [comment]
@kfrz I believe this one is done as well as you have all the known External Service SLO's configured now, is that correct?

**Comment by kfrz** [comment]
Staging data SLOs for availability: 

https://app.datadoghq.com/dashboard/rk8-tt9-22h/external-service-performance?from_ts=1611761627869&live=true&to_ts=1611765227869
