### ISSUE TITLE
Mobile address validation endpoint

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#17086]
### User Story
As a FE developer I want an endpoint where I can check that a user's address is valid so I can let them know if they need to make any corrections

### Acceptance Criteria
A new mobile endpoint exists that returns if an address is valid or not. It will also return which fields are invalid and address suggestions for the 'official' address on record.

**Comment by srmyers17** [comment]
- new step in address flow that allows for suggested address
- call this endpoint for validation and potential suggestions @bridgethapner 
- if users keeps, address they entered, must pass validation key back

**Comment by srmyers17** [comment]
Q: Are there any special considerations for different address types (military, domestic, international)?
Service has more than what USPS has.
