### ISSUE TITLE
Access for Ryan Johnson

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#17099]
# Instructions
1. [x] Fill out **Description**
2. [x] Add the label used by your team (eg: `BAH-526`)
3. [x] Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Ryan Johnson
- Please Provide your email.
   > ryan.johnson@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSP Testing Team, Role: Senior Software Engineer, Company: Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDR3DgrOvyNSuBckbUDLaJA6wDRAHN4A/odeobR4TuOwpycCCud/Lz3hftSLdqHOKBUCp9wKGdeVDzvm93zVhSUQtpEIwM/jEAe/izbBgQ0VRuiYykV79KnfA70+rKygI+iwQ+ZUu/L+gFp25MgoGUgM+Jpp7uds6ckmlC7dTq0jfzXobt0rx2Yf6+rQSSLhjbjgpUipR25I/Y8wxyYBgqZykVK7LvtD1mtSevFwHkKJbtwUTnVHfpaLwhnzwueuxoyN4xPtKTIhkV2JoKktydmO9rRlCFNf0HH3B65Wfwi52wjhRRjbQX3XS5AP/sR68KAsXmYPcQuE+AH3Kz+9kBEzwMsem5tPK3U8L0uGli21g53KydaARqE079BqGbLIrn7UBSoNTHJlgT78sZJ1jfqsyQjuGHHeNP4N0pJYWSzMrCi/alT3oKYUqBJt/FddPqvQ83z/VUnywH0GDM8gHQ4fiSB7MqPZUbOE7urw+EjlpCtbWKcPFzbqzEnYC5IVB0= ryan@Ryans-iMac.local
```

- Grant AWS Console access?
  >  NO, just need access to SOCKS proxy.
  - What AWS services do you need access to and why? 

@department-of-veterans-affairs/vsp-operations Please review

**Comment by pnwstevan** [comment]
Hi @rjohnson2011 

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

**Comment by pjhill** [comment]
@rjohnson2011  --Have you had a chance to verify SOCKS access?  If you're good to go with the SOCKS proxy then please close this ticket when you can.
