### ISSUE TITLE
Appointments detail | Hide categories with null states

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17094]
## User story
As a user, if I have sparse appointment details, I do not want to see any categories with empty states. 

## Acceptance Criteria
1. On the upcoming Appointments detail pages, for any categories that are data-driven, these should be hidden from the UI when the API does not return any data. This includes:
     - Community Care: **Special instructions**
     - VA Video Connect at an ATLAS location: **Appointment code**
     - VA Video Connect at a VA location: **Provider**

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/5/2021 - Not seeing any empty categories.
