### ISSUE TITLE
Skip unpublished bios on pittsburgh-health-care/returning-service-member-care

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#17097]
On pittsburgh-health-care/returning-service-member-care:

![VA_Pittsburgh_Health_Care___Returning_service_members.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/de060771-54ef-4ded-9844-3cc20df11d10)

See https://github.com/department-of-veterans-affairs/va.gov-team/issues/15460 for more info.

**Comment by mmiddaugh** [comment]
This issue is resolved - tested using draft profiles on New Jersey health care
