### ISSUE TITLE
Some image links have prod.cms.va.gov prefix in cms-export build

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#17101]
Some image links (e.g.. on pittsburgh-health-care/index.html) have a **prod.cms.va.gov** prefix in the cms-export builds only. 

These paths do not appear in the graphql build. They will not work unless you are behind the SOCKS proxy.

These paths will also cause the Jenkins builds to fail because the server is not reachable from the review instance containers.

The **prod.cms.va.gov** prefix appears in the following files:

```
❯ find . -name "*.html" -exec grep -q "prod.cms" {} \; -print
./pittsburgh-health-care/index.html
./pittsburgh-health-care/locations/index.html
./pittsburgh-health-care/medical-records-office/index.html
```

**Comment by jhonnyoddball** [comment]
Note:
Maybe we will need to replace `https://prod.cms.va.gov/` inside `getImageCrop with [this](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/constants/drupals.js#L54) since it will not work inside Jenkins

**Comment by meganhkelley** [comment]
I wonder if this is at all related to #13455?

**Comment by meganhkelley** [comment]
@mpelzsherman @mmiddaugh could y'all please help us understand the priority of this issue and how it affects your team? Thanks!

**Comment by jhonnyoddball** [comment]
> I wonder if this is at all related to #13455?

@meganhkelley I don't think so, this only affects images

**Comment by mpelzsherman** [comment]
This is a blocker for releasing the cms-export build. It is causing broken links when I try to view the pages locally.

![VA_Pittsburgh_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/80267/103666213-535d6e80-4f42-11eb-9849-57c7010e99bf.png)

I am pretty sure this will impact the public websites pages too, once that team brings their pages into alignment with graphql.

**Comment by meganhkelley** [comment]
@mpelzsherman thanks for the info! We will prioritize accordingly

**Comment by mpelzsherman** [comment]
I've also confirmed that this issue exists in the review instance built by @indytechcook .

The images download OK when viewed with SOCKS, but the prod.cms.va.gov URL's **will not work** in production.

![VA_Pittsburgh_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/80267/103674364-ab996e00-4f4c-11eb-8440-583e2c4585c9.png)

**Comment by meganhkelley** [comment]
Updates from Jhonny: 
1/14: initial approach did not work (comments above). tried new approach - using URLs from s3 buckets. this approach is working but having trouble with build

1/15: troubleshooting missing node

**Comment by jhonnyoddball** [comment]
I have used the site's [bucket constants](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/constants/buckets.js) to allow the images to be public.

TODO:
@meganhkelley 
I have used only the prod link since that's what we are using for all cms content, however, we will need make it a little more dynamic in the future and be able to use the correct environment.

```
[VAGOVPROD]: 'https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com'
```
