### ISSUE TITLE
Content for vaccine comms tool

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17102]
# Intro page

[url] va.gov/covid-19-vaccine/stay-informed

[h1] **COVID-19 vaccines—Stay informed and help us prepare**

[intro text]
We’re working to get COVID-19 vaccines to Veterans as quickly and safely as possible based on CDC guidelines and available supply. We need your help to prepare. And we want to keep you informed at every step.

Sign up below to help us understand your interest in getting a vaccine. We’ll send you regular updates on how we’re providing vaccines across the country—and when you can get your vaccine if you want one. We’ll also offer information and answers to your questions along the way.

**Note:** You don’t need to sign up to get a vaccine. And you can change your mind about getting a vaccine at any time. We’ll use the information you provide to understand your interest and communicate with you. <br>
[Learn who will get a COVID-19 vaccine first based on CDC guidelines](va.gov/covid-19-vaccine)

[sign in component]

**Sign in to save time** 

When you sign in, we can fill in some of your information for you. 

[button 1: Sign in] [button 2: Continue without signing in]

# Form

[url] va.gov/covid-19-vaccine/stay-informed/form

[h1] TBD after accessibility chat
[note for authenticated path only] **Note:** Any changes you make to your information here won't change your information in your VA.gov profile or any other accounts.

[form fields]

First name

Last name

Date of birth
[Month/Day/Year]

Social Security number (SSN)

Confirm Social Security number (SSN)

Email address

Phone

Zip code

Are you interested in getting a COVID-19 vaccine at VA?

Yes
No
I'm not sure yet.
I prefer not to answer.

[button] Sign up

# Confirmation page

[url] va.gov/covid-19-vaccine/stay-informed/confirmation

[h1] We've received your information

Thank you for signing up to stay informed about COVID-19 vaccines at VA. When we have new information to share about our COVID-19 plans and your vaccine options, we'll send you updates by email or text.

You can also visit our main [COVID-19 vaccines at VA page](www.va.gov/covid-19-vaccine) for the latest information and answers to common questions. 

**Remember:** You don’t need to sign up to get a vaccine. And you can change your mind about getting a vaccine at any time. We’ll use the information you provide to understand your interest and communicate with you. If you want to update your information later, you can submit a new form.

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf Can you double check me on this copy and specifically these Qs:

1. Intro screen: Sign in to save time component: Just revised this to avoid the word "application." But if someone is signed in, will we save their form so they could come back and update it later? If yes, I could add a line around that as well.

2. Confirmation: 2 questions. 1) We'll send some updates by email, but some maybe by text, right? I've included both for now. 2) "If you want to update your information later, you can submit a new form." - We wanted to add this, yes? If they can also come back to a saved form and update it, I can add that too.

**Comment by batemapf** [comment]
- copy looks good.
- not sure about save in progress. that might only be triggered when going to a new page. will need to talk with the team about this.
- yes to email and text
- on the update info, the two paths are: (1) if you are not authenticated, submit another form; (2) if you are authenticated, you will see the info you previously submitted, which you can update and resubmit.

one potential add:
- we need to message to authenticated users that changes they make on this form to their contact info _will not_ update in other places at VA.

another add:
- we will likely need two boxes for SSN if we are going mask it, one to enter, one to confirm

another possible add:
- do we want middle initial (optional)? less for our purposes, more for people who have a common/shared name and want to be particular

**Comment by DanielleThierryUSDSVA** [comment]
@batemapf @ncksllvn Wasn't sure about middle initial so didn't update above yet. Doesn't seem like it could hurt?

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn @batemapf content for landing page alert below:

## Stay informed and help us prepare

Sign up for an easy way to stay informed about our COVID-19 plans. 

When you'll sign up, we'll also ask about your interest in getting a vaccine when one is available to you. By sharing your interest, you can help us better prepare as we work to offer vaccines to more Veterans.
 
**Note:** You don’t need to sign up to get a vaccine. 

[blue button: Sign up to stay informed]

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn @batemapf  

2 updates from my call with @1Copenut. Also adding 2 lines of text to keep the context from the first screen and stress the "you don't need to sign up to get a vaccine" note again. If you don't think we need that text, we can remove.

Both of these updates are on the form page: va.gov/covid-19-vaccine/stay-informed/form 

## Update 1

[url] va.gov/covid-19-vaccine/stay-informed/form

[Update the H1 to the language below and add 2lines of text beneath H1]

**Fill out the form below to sign up**

We’ll send you regular updates on how we’re providing COVID-19 vaccines across the country—and when you can get your vaccine if you want one. You don't need to sign up to get a vaccine.

## Update 2

Update the button to:

Sign up to stay informed

Use an aria label to update button text to the below for screen readers:

Sign up to stay informed about COVID-19 vaccines

**Comment by ncksllvn** [comment]
@DanielleThierryUSDSVA Making sure I follow...the first update should look like this?

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/8a5ae2c3-ec86-465d-99c2-eb14c64bbe68)

**Comment by DanielleThierryUSDSVA** [comment]
@ncksllvn Above looks good. And for authenticated users, we'd also have the note re: info not changing in other places below this. Heads up that we'll be testing other content messaging for this too I think. 

And then here's the content for the "off" state of the flipper component:

![image](https://user-images.githubusercontent.com/62957278/101661836-c1cc1100-3a16-11eb-88ab-2d62d51fb163.png)

## Check back soon for an easy way to stay informed and help us prepare

We're creating an easy way for you to sign up to stay informed about our COVID-19 vaccine plans.
When you sign up, we’ll also ask about your interest in getting a vaccine when one is available to you. By sharing your interest, you can help us better prepare as we work to offer vaccines to more Veterans.

**Note:** You don't need to sign up to get a vaccine.

**Comment by ncksllvn** [comment]
Hey @DanielleThierryUSDSVA , the widget should be available after today's daily deployment! 

From Drupal, you'll be able to add it by adding a React widget of type `va-covid-vaccine-updates-cta`.

**Comment by DanielleThierryUSDSVA** [comment]
Awesome. Thanks, @ncksllvn!
