### ISSUE TITLE
Lighthouse API review and PR to remove methods from the serializer

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17109]
## User Story
The **forms_details_url** node in the Lighthouse API currently returns **nil** because the URLs were not ready to be made public when the Find a VA Form search result page initially was released. 

Based on this [Slack thread] (https://dsva.slack.com/archives/CUB5X5MGF/p1606760848230400?thread_ts=1606757374.228900&cid=CUB5X5MGF), the Decision Tools team has a dependency on the Lighthouse team to do a review and a PR to remove methods from the serializer.   This [pull request] (https://github.com/department-of-veterans-affairs/vets-api/pull/4989/files) also provides some info.

## Expected Behavior
Lighthouse API response will return a form-specific URL for any form that has a details page.

## Acceptance Criteria

- [ ] forms_details_url in the Lighthouse API response will return a given form's associated URL if a detail pages exists for that form.
- [ ] 438 form detail links should be populated after the change.
- [ ] Clicking on a given link goes to a valid page that corresponds to the details for the appropriate form.

**Comment by MarciMcGuireGCIO** [comment]
@markgreenburg adding you as an assignee on this issue so you have visibility.  Related to our meeting on 12/18. Thanks!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO This looks like it can be closed?

**Comment by MarciMcGuireGCIO** [comment]
Yup!
