### ISSUE TITLE
Content feedback - FSR form prototype

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#17118]
## User story
Provide content feedback on 1st mockup of Financial Status Report form.

**Comment by peggygannon** [comment]
@3obryandogs @rebeccawalsh @rileyorr 

Content feedback on FSR form uploaded here. Please let me know if you have any questions. 
@DanielleThierryUSDSVA will  also be uploading her additional feedback to this ticket. 

[https://app.zenhub.com/files/133843125/6d820c17-b35b-4253-9709-28604cf73921/download](https://app.zenhub.com/files/133843125/6d820c17-b35b-4253-9709-28604cf73921/download)

**Comment by peggygannon** [comment]
HI, @rebeccawalsh @rileyorr @3obryandogs Hello! I'm checking back in on this ticket to see if you have any questions for me about my recommendations ^^?

**Comment by rebeccawalsh** [comment]
@peggygannon  Hi there!

Yes! So we picked up the collaboration of your feedback on [this google document](https://docs.google.com/document/d/1lDLgssP5Fe_AJ8TKgpoPJHff4Aobi-3u/edit), to make it easier to see what we're talking about. I asked a bunch of questions, and it was generally pending rework by Susan. Susan is no longer working on this contract, so we'll need to figure out how to work with you or PW content writers to finalize some of those content areas that needed to be PL'd and improved.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @peggygannon. My recommendations are in [issue #19096](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19096), if you want to reference them for any future VSP reviews. Thanks!
