### ISSUE TITLE
[Development] Breadcrumbs and Header copy is mismatched on 526 (Disability Compensation)

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#1712]
@katelyncai commented on [Thu Jun 13 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18961)

**Steps to Reproduce**
url: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/

**What happened:**
The breadcrumbs for this form are `File for disability compensation` while the header reads `Apply for disability compensation`

![Screen Shot 2019-06-13 at 10.43.51 AM.png](https://images.zenhubusercontent.com/5b913be3b2cc7b6c78ecf2f3/229c691c-53d8-442a-b0d1-a4ff9efe9e81)

**Desired behavior:**
As a Veteran, I would expect to see a consistent breadcrumbs title and header so that I can easily navigate around VA.gov.

**Comment by Mottie** [comment]
This ticket is on hold per Peggy Gannon:

> hello. thank you for adding me to this PR. The disability hub pages are in the process of getting migrated over to the new CMS, Drupal, so I think we should hold off making changes to the static pages until that migration is complete end of Sept), as the pages in drupal are now the most recent.

**Comment by peggygannon** [comment]
Hi, @Mottie I just checked the drupal files and the page header says "File for disability compensation"

Is there another place you're seeing "Apply for disability compensation"? The correct header should be "File for disability compensation" 

here's a screenshot: 
![2019-11-13](https://user-images.githubusercontent.com/17554224/68807216-4bdf5580-061c-11ea-9fa2-c3696c2c520e.png)

**Comment by Mottie** [comment]
The title displayed in the browser tab is showing "Apply for.." - I ended up looking at my pull request (https://github.com/department-of-veterans-affairs/vagov-content/pull/553/files) and noticed there were a few files that had this issue both in the title and page description.
