### ISSUE TITLE
General Analytics Request for Liz

### ISSUE THREAD

**Issue by LizCallaghan** [department-of-veterans-affairs/va.gov-team#17121]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Liz Callaghan and Chris Johnston

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    - this is for DEPO to be used at an executive level budget presentation
    
- What type of analytics support are you looking for?
-one time metrics report
    

## Timeframe for Analytics Requested
need by COB Wednesday 12/9/2020

## Analytics to Track Down
> Examples
> 
> - VA.gov number of unique users since January 2020
> - VA.gov number of unique login successes since January 2020
> - CSTAT Scores for VA.gov from January 2018 to October/November 2020

## Which Product Questions are you trying to answer?
Trying to show increased usage of VA.gov and key online services

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [x] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [x] The metrics are shared back with users.

## Definition of Done
- [x] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bmcgrady-ep** [comment]
Hi @LizCallaghan - I added you to the DOMO dashboard for this reporting request. Let me know if you have any questions!

**Comment by bmcgrady-ep** [comment]
@LizCallaghan - Is there anything else that you need help with in regards to this ticket? Feel free to let me know!

**Comment by bmcgrady-ep** [comment]
Closing out this ticket. Feel free to reopen with any additional questions related to this request.
