### ISSUE TITLE
Appointment timezone should match clinic location

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17129]
## What happened?
The appointment timezone is dynamic and updates to match the timezone of the user's device. 

## Specs:
- Device: iOS - iPhone 11

## Steps to reproduce: 
1. View the appointments summary page. This should correspond to the device's current timezone. 
2. Log out of the app. 
3. In the device's settings, select a city in a different timezone (e.g. switch from Los Angeles to New York)
4. Log back into the app and view the appointments summary page. The appointment times should have changed to match the newly selected timezone (e.g. PST --> EST)

## Desired Behavior
The appointment timezone should correspond to the clinic's timezone, regardless of the device location. 

## Acceptance Criteria
- [ ] An appointment timezone will correspond to the clinic location
- [ ] An appointment timezone will not change even when altering the device's timezone (_note_: this will help test virtual appointment types that do not display a clinic location)

## Linked story
Story [#13971 ](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13971)(AC #4)

## Screen shots
![EST.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/7509421b-b786-4362-8191-8a543a9733fa)
![PST.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e29e97d6-6b33-46b2-9e46-52c0f38ec9d2)

**Comment by bessgreen** [comment]
@lexicalninja looping you in on this ticket

**Comment by digitalken** [comment]
PASS - Switched to EST and times on clinics were still in PST.  Added to Calendar, which put it in my timezone time of EST.
Closing but putting in Design Review.
