### ISSUE TITLE
Access for Steven Bair

### ISSUE THREAD

**Issue by sbair-va** [department-of-veterans-affairs/va.gov-team#17134]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Steven Bair
- Please Provide your email.
   > steven.bair@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse API Development and Operations, Software Engineer, Liberty IT Solutions
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBPZFk3KNWwaIwddEaLEz0aOfZJrj70sHQXC6y/mPnomV3sRSY09b8XxFTfDzbYTV+lmK1glKQRp0a0fb7x0oNSX39cP9xAsNu95FrofMriGnfANscD5tZ57/qMw14el1mYNZ9VNlmjcsaaBk8ivN+4D7uSZyiPkp1pH4yLjkCOdMmBdoYPpzCgtsE1hCElKyfCOdmZVL0w/H1KTA7dkgTUhGK6t3/ykyFaUiCOCMugCWlyxWhREfEPjpGGRnLN4JH+m0C1KAy3YgQ++DsH7sM30nui0GkR1yYkx3+qHASNK/1aXaKIVZpdc4mrrRrZf9Yor4gRUPWNuHNxPBV63lLhyhD6iz00BiqmleJUGKYE/81Zl8S00Qc/vG3mphdQn7ZIWgLeklVqWeWxW782ZC1Q4vPxtUHErT9S98FJ/aJXy5tXJ8oJhCYcpJlceP2A5oe1BMcSpnf+jhwBE1zmy6xGH4nb6A1HN8EBgFLINBzrQF2QgLIdOuTmLhkTtkPXuc= AzureAD+StevenBair@WIN-JV77JQBA3DN
```

- [Grant AWS Console access?]
  >  NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by sbair-va** [comment]
New computer and SSH key. Previously granted under:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8043

Old key can be replaced. Please let me know if any additional information would be beneficial or if this process (for a new laptop) should be completed a different way.

**Comment by sbair-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by pnwstevan** [comment]
Hi @sbair-va!

I've updated your SSH key as requested; please confirm and then close this ticket if working as expected.  Thanks!

**Comment by sbair-va** [comment]
Confirmed - thank you very much!
