### ISSUE TITLE
Access for Ero Gray

### ISSUE THREAD

**Issue by erogray** [department-of-veterans-affairs/va.gov-team#17131]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Ero Gray
- Please Provide your email.
   > ero.gray@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS-CMS team, Helpdesk Manager, CivicActions, Inc.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC41reV9H5f70Cqq3Olo36L/hvtJFSQZ5NmROQ5ipCGLLNFpUa67fc5aJXCTP6vzghLpcmwcFV3NTu7Ds/tS0DI+uvYFgOgK3dsOsOI9p5tKZ/n2CYsP9MpEfcb3aM1YO37EbKLpM/HDzscyGB0SsOOWyLTltneKosx/rzsrEZGMyCeFozaMix9tHTAKIqM7mgpZu5PD1HJkTLp60doZ654wh853mWhafFYzRCNV0N1tvI3A/BLZvF/ejU4mlcTlAC3PHmH3Xi1Gqyl8aJV/CndM7u1macn5/EiofFUo+Een5ATp70TvVnU8an1YD0JPNF/3hXFtbBGnQb5vOmmdcmN ero@Ero-MacBook.domain
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why? 
n/a

**Comment by pnwstevan** [comment]
Hi @erogray!

SOCKS access granted - please review this [guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to configure and use the SOCKS proxy.

Once you've confirmed access, please close this issue.  Reach out for any help needed!

**Comment by erogray** [comment]
Thanks @pnwstevan ! Seems to be working.
