### ISSUE TITLE
Misc. copy updates

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17138]
## Acceptance Criteria

Make the following copy changes across the mobile app:

1. Direct Deposit overview screen:
     - Original copy: View and edit your direct deposit information for disability compensation and pension benefits. When you make updates on the VA mobile app, those changes will be reflected on VA.gov.
     - Update to: Add, review, or change your direct deposit information for disability compensation and pension benefits. Any updates you make here will also update on VA.gov.
2. Personal & Contact information overview screen:
     - Original copy: When you edit information on the VA mobile app, those changes will be reflected on VA.gov.
     - Update to: Any updates you make here will also update in your VA.gov profile.
3. Appointments overview screen
     - Original copy: Your confirmed appointments are displayed below. Appointments that have been requested but not yet confirmed are not shown.
     - Update to: Here are your confirmed appointments. This list doesn't include appointments you've requested but not yet confirmed.
4. Update any existing a11y hints/labels as needed

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
testing...
