### ISSUE TITLE
Staff Profile pages are different on Staging and Prod

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#17132]
## Issue description
Pittsburgh staff profile pages are different on staging compared to production. this can be problematic from testing perspective. It's challenging to know what expected behavior is when the environments are different. 

**Causes an issue in Tugboat/review environments which impact roll-outs and new editors**

**The correct behavior is on Prod**

Example:  https://staging.va.gov/pittsburgh-health-care/staff-profiles/alan-petrazzi/

<details>
<summary> Sidenav is present on Prod </summary>

![image](https://user-images.githubusercontent.com/55411834/102550093-7818a180-407a-11eb-8d65-333881656251.png)

</details>
---
<details>
<summary> Sidenav is missing on Staging </summary>

![image](https://user-images.githubusercontent.com/55411834/102550155-9088bc00-407a-11eb-9308-e8413702b80d.png)

</details>

There's also a Javascript error on the page: 

```
helpers.js?c526:139 Uncaught TypeError: Cannot read property 'filter' of undefined
    at normalizeSideNavData (helpers.js?c526:139)
```

NOTE: Whether or not Side Nav is expected is not within scope of this issue. 

## Tasks
- [x] Understand the reason staging and production are different - what environment checks are in play?

**Comment by mmiddaugh** [comment]
The side nav issue is present only on Staging. Fine on [Prod](https://www.va.gov/pittsburgh-health-care/staff-profiles/alan-petrazzi/)

**Comment by mpelzsherman** [comment]
Fixed. Removed non-prod logic.

**Comment by mmiddaugh** [comment]
Looks good to me! Closing this issue.
