### ISSUE TITLE
Past Appointments date range selector - up/down arrows don't seem to work

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#17137]
## What happened?
(NOTE: See also iOS pickers in address edit pages in profile.)

The up/down arrow selectors for the date range on iOS don't seem to be doing anything. I can tap and tap, but nothing happens. I can alternatively slide my finger up or down and select the date I want.

When I use voice command to show numbers (to identify the tapable locations on the screen), it shows numbers by these up/down arrows so it thinks they should be selectable. When I say those numbers, nothing happens.

## Specs:
- Device: iOS iPhone 6s ver. 14.2

## Steps to Reproduce
- Navigate to the Appointments page.
- Tap Past in the toggle.
- Tap to select a date range.
- Try to change the range using the up/down arrows on the left of the chooser.

## Desired behavior
Up/down arrows will change the selection in the chooser.

## Acceptance Criteria
Up/down arrows will close the dropdown menu, and the cursor will navigate to the previous field (if Up arrow is selected) or to the next field (if Down is selected). 

## Bug severity
- 3 - Moderate

## Screen shot(s) and additional information
Notice the "show numbers" screen where the OS recognizes that they are controls -- yet they don't work.

![iOSpastAppointments.jpg](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/b4a412bb-0ba4-44b5-bdd4-9a8ac32fa64f)

**Comment by komaly15** [comment]
Moving back to "Known Issues" for now, a story will be made for the implementation of these arrows since there will be cases where the arrows are shown and cases where they are not, depending on the screen/other inputs on the screen

**Comment by digitalken** [comment]
Closing this one as it is no longer applicable for new requirements surrounding up/down arrows in picker.  12/21/2020.
