### ISSUE TITLE
[Bug] Search - Type Ahead - Safari - Unexpected tabbing focus

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#17142]
## What happened?
On Staging **homepage** or **Search VA.gov** page, in Safari browser, Tabbing out of page-header's Search text-field moves focus to browser address-box [on homepage (for both Macbook and iPhone)] or main text-field in main-content [on Search VA.gov page (for Macbook only)], instead of to the search button to the right of the page-header text-field.

**NOTE**: Keyboard-nav testing is typically done by VSA Accessibility Specialists, not VSA-QA, so this defect may be [or become] a duplicate.

## Specs:
- Device: Macbook Pro
- Browser: Safari

## Steps to Reproduce
1. Go to https://staging.va.gov (homepage)
1. In **page-header**, click **Search** button.
1. In newly-displayed text-field, type **benefits**.
1. Press **Tab**.
1. Observe that focus moves to browser address-box, instead of the search button to the right of the page-header's text-field.
1. Do one of the following (depending on device) to go to search-results page:
    - For Macbook, **Shift-Tab** back into page-header's search text-field, then press **Enter**; or
    - For iPhone, tap **Cancel** next to address-box, then tap **search** (magnifier-icon) button next to page-header search text-field.
1. On **Search VA.gov** (search-results) page, repeat Steps 2-4.
1. Observe that on this page focus moves to the main search text-field on the page's main-content [for Macbook] or the browser address-box [for iPhone], instead of the search button to the right of the page-header's text-field.

## Desired behavior
Tabbing out of page-header's search text-field should move focus to the button next to the field.  Tabbing again (from button focus) should set focus on 1st option of suggestions dropdown.

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by srsuddath** [comment]
Hey @tlei123 I noticed that this issue occurs on the already production VA.gov as well. What behavior are we expecting when we hit tab while the search field is focused and there is user input there?

**Comment by tlei123** [comment]
> What behavior are we expecting when we hit tab while the search field is focused and there is user input there?

@srsuddath , we're expecting the tab-focus to move from the field to the magnifier button on the right.  Sorry for the late reply!

**Comment by srsuddath** [comment]
@tlei123 no worries at all, can you check something in your local settings for me? if you go to: Select Safari > Preferences > Advanced is the 'Press tab to select each item on the webpage" selected?

**Comment by srsuddath** [comment]
@tlei123 I would like to close this ticket as it is fixable using browser settings.

**Comment by tlei123** [comment]
Testing: tagging myself @tlei123 to verify auto-email notification.

**Comment by tlei123** [comment]
Validated in my Safari w/ 

> @tlei123 no worries at all, can you check something in your local settings for me? if you go to: Select Safari > Preferences > Advanced is the 'Press tab to select each item on the webpage" selected?

Just validated that enabling **Safari > Preferences > Advanced > Press tab to select each item on a webpage** indeed fixed this issue.

Closing ticket now.

Thx much, @srsuddath !

cc @denisecoveyduc

**Comment by srsuddath** [comment]
Thank you @tlei123 for checking this out! Why this feature is disabled by default in safari is absolutely baffling to me!
