### ISSUE TITLE
Project Kickoff Decision Tools - Post MVP Launch Enhancements

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17148]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all relevant artifacts to the ticket
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] Shira will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] Kickoff meeting completed 
- [x] [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline [Find a VA Form Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/README.md)
- Explanation of the problem space
We are working on post-launch enhancements that fall into these categories:

1. Features in the original design that weren't implemented in the MVP due to data/API dependencies
2. Bug in the MVP
3. Minor enhancements to improve user experience (more clearly-worded message for deleted forms, ability to sort by last updated)

- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): Marci McGuire
- DEPO Product Lead (required): John Hashimoto
- Entire VFS team (recommended): Zach Morel
- Other specialists:  Laurel Laurence. Tze-chiu Lei, someone from analytics

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite 

John, Zach and I are available during these times:  
Fri 12/11 11:30 AM and 4:00 PM
Mon 12/14 at 2:30 PM
Tue 12/15 at 10:30 AM and 2:30 PM

**Comment by shiragoodman** [comment]
@MarciMcGuireGCIO Have you checked the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) to see my teams availability? We typically only schedule in the timeslots marked "CALENDAR BLOCK." Would any of the available times (where we don't already have a meeting booked) work for you and your team?

**Comment by MarciMcGuireGCIO** [comment]
Yes, I did check that, but John and/or Tze were both booked at those times.  Thanks!

**Comment by shiragoodman** [comment]
ok I can schedule at one of your requested timeslots but I can't guarantee that my full team will be available. In the future, please try to accommodate your schedule. We provide 7 different 30 minute timeslots throughout the week so that we can make sure we're fully available. Scheduling outside of those block can be challenging.

**Comment by MarciMcGuireGCIO** [comment]
Thank you. I was having trouble finding a slot that works for John and Tze, because Tze's was showing busy every day that your team's calendar had blocked time, but I think maybe that's because he has those hours blocked off?

**Comment by shiragoodman** [comment]
lol yes, that's exactly it. Tze use to be a default attendee of the Collab cycle review meetings, so it's likely he still has those blocked times on his calendar.

**Comment by MarciMcGuireGCIO** [comment]
Thank you all for taking time to meet with us today.  Here is the Post-MVP epic:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/10758

**Comment by shiragoodman** [comment]
hi @MarciMcGuireGCIO and the VSA Decision Tools team! Thank you for answering our questions at Project Kickoff today. After reviewing your responses to our questions, we're recommending the following Collaboration Points:

- Usability Testing Prep
- Research Plan Review
- Analytics Request
- Contact Center Review
- Staging Review
- Privacy & Security Review

Post launch:
- Full Accessibility and 508 Office Audit
- Post-launch Check-in

Additional details for the above collaboration points can be found in our[ Collaboration Cycle guidance.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md) The Platform Collaboration Point Tracker has been updated. Please let me know if you have any questions.

**Comment by MarciMcGuireGCIO** [comment]
Thank you!

**Comment by MarciMcGuireGCIO** [comment]
> hi @MarciMcGuireGCIO and the VSA Decision Tools team! Thank you for answering our questions at Project Kickoff today. After reviewing your responses to our questions, we're recommending the following Collaboration Points:
> 
> * Usability Testing Prep **<-- probably not needed**
> * Research Plan Review **<-- probably not needed**
> * Analytics Request
> * Contact Center Review
> * Staging Review
> * Privacy & Security Review
> 
> Post launch:
> 
> * Full Accessibility and 508 Office Audit
> * Post-launch Check-in
> 
> Additional details for the above collaboration points can be found in our[ Collaboration Cycle guidance.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md) The Platform Collaboration Point Tracker has been updated. Please let me know if you have any questions.

**Comment by shiragoodman** [comment]
@MarciMcGuireGCIO per your last comment, if you don't think the Usability Testing Prep is needed, ok. However, I would highly recommend and encourage you to reach out to Lauren Alexanderson (per the Research Plan Review) since you are planning to test with Veterans. She can assist with that.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, Shira!  Will do!
