### ISSUE TITLE
526 All Claims: Design - Usability feedback content update (adding attachments)

### ISSUE THREAD

**Issue by aeltarhoni** [department-of-veterans-affairs/va.gov-team#1715]
@peggygannon commented on [Wed Oct 24 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14557)

Problem: When adding multiple items, people are not always sure if they need to do anything other than continue. “Do I need to save?”

On screens where users can upload a document, make language more clear about their next steps. 
- [ ] Add 'Save' button to the editable form in any add another flow (Service Periods, Add new contention, and Uploads); give same treatment as adding new condition
- [ ] change 'remove' button to link

This affects the following pages on All Claims
![2018-10-24 (7).png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/23e7a6be-216e-4200-afcb-6956d6796748)

**Comment by YanaRoy** [comment]
Is this still applicable given that the ticket was created in 2018 pre va.gov?

**Comment by smoonpeyes** [comment]
It's still a valid concern, but not a high priority.

**Comment by luke-gcio** [comment]
Not sure if this applies anymore since it does save attachments automatically as they are uploaded.  @kevinstachura can you review?

**Comment by kevinstachura** [comment]
I think what Peggy meant to say was that there is no action for the user to confirm that they have indeed uploaded the file and it has been 'saved'. I don't see this as a 'showstopper' as we have not seen any negative feedback on this during our BDD testing (which is still 526 and has file upload like this). Further, we do have visual confirmation of the application being saved during the upload process (under the progress buttons):

<img width="576" alt="Screen Shot 2020-07-15 at 11 57 21 AM" src="https://user-images.githubusercontent.com/54544300/87567663-907f2d00-c692-11ea-866b-d72692ce41bc.png">


That said, we should test for this specifically the next time we do usability on 526 or BDD. It's a good point. Additionally, we should look into global form patterns to see if there is a consistent 'save' button on these cards in other form implementations to determine if we're following convention and being consistent across va.gov.

**Comment by luke-gcio** [comment]
Closing but we will be adding this to the general "part 2" 526 usability.
