### ISSUE TITLE
User automatically logged out immediately after log in (IE only)

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17198]
## What happened?
In IE, user is getting logged out right after logging in.

Reported by @beth-wodzinski 

## Specs:
- Device: 
- Browser: IE
- Test User _(if applicable)_: Judy Morrison

## Steps to Reproduce
- In IE, go to **_URL TBD_**
- Sign in with ID.me account Judy Morrison
- Complete through 2FA

## Actual behavior
User is automatically signed out after passing 2FA

## Desired behavior
Page behind authentication loads

**Comment by beth-wodzinski** [comment]
Hi Lauren,

Browser:
[cid:image001.png@01D6CE1E.69DDC290]

I log in to Vaos as Judy Morrison (or any of our test patients) using id.me. IT goes through the two factor authentication and then . . . logs me out.

Aarathi was able to reproduce it.

I was able to log in to VAOS in Chrome as usual; it’s just IE that’s weird. I first noticed this yesterday. This morning I restarted my computer and it’s still happening.

**Comment by laurenernest** [comment]
@beth-wodzinski Which page are you starting from before you try to log in?
- https://staging.va.gov/health-care/schedule-view-va-appointments/
- https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
- or are you coming in from MHeV?

**Comment by beth-wodzinski** [comment]
I just checked and it happens with both those urls.

**Comment by jbalboni** [comment]
I wasn't able to reproduce this trying in IE11 on Windows 10, but I know that staging is having some app login issues right now, too, which could interfere.

I'm pretty sure I remember an issue like this getting a reported a while back for SSOe, though, so maybe that has reappeared in some cases.

**Comment by jbalboni** [comment]
@beth-wodzinski What OS are you using IE 11 on? I've tried on Windows 11 and 7 without seeing this issue in staging. If you haven't tried it, I'd be interested if clearing your cache has any effect (not sure if restarting will clear it).

**Comment by laurenernest** [comment]
@beth-wodzinski is this still an issue?

**Comment by beth-wodzinski** [comment]
Yes; I am still not able to log in to VAOS in IE.

**Comment by jmercado-va** [comment]
I was able to recreate this issue in staging with three different ID.me test users: judy.morrison, cecil.morgan, and michael.moreno using IE version 1909 (OS Build 18363.1377) running on Win10--i cleared my cache/cookies after each try. It goes thru various redirects then flashes a few screens as if it's going to work but ultimately displays the logout error screen which also disappears after a few moments.

**Comment by jmercado-va** [comment]
Here's the recording of the error--the redirects and error appear then disappear so it's difficult to capture a screenshot.

https://user-images.githubusercontent.com/54673140/112355305-e6858500-8ca3-11eb-951a-6be5d8f4ecbe.mp4

**Comment by saneshark** [comment]
Looking at this video it looks like the user is getting signed in, so it's not an issue that ID.me can help with -- instead one of the two cookies, either the VA.gov session cookie or MHV SSO cookie is probably not getting set in IE for whatever reason.

There is more information on how this will be tested further in this slack thread: https://dsva.slack.com/archives/CSFV4QTKN/p1616610431032100

But the plan is to try to reproduce off peak hours so that we can tail the logs in cloudwatch and get a better picture of why this user got signed out immediately after getting signed in. It's very difficult to see the reason in the client / web browser because of how quickly the redirects happen.

**Comment by saneshark** [comment]
@jmercado-va it might not be a VPN issue but it could be certain access control settings as part of VA's IE configuration that cause it to drop certain headers. I distinctly recall a similar issue we experienced with MHV employees logging into VA.gov using DS Logon using GFE both on and off the network. 

More technically, after some research the identity team has noticed that when using CAG's IE 10+ the `access-control-allow-headers` are getting dropped. Usually one might think this is happening at the TIC or proxy level of some sort, but seeing as you are experiencing this issue both on and off the VA network it most likely having to do with how VAIT has chosen to provision IE on GFE. It *could* also be a problem with IE more broadly, and not part of special security provisioning by VAIT. 

That being said, I'm not sure there is a clear path to resolve this issue.

**Comment by laurenernest** [comment]
Issue is being tracked by the Identity team #15709. Closing this ticket.
