### ISSUE TITLE
Dashboard | Review VAOS Errors in Grafana

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17197]
## Issue Description
The existing VAOS Errors dashboard in Grafana may not be current.

---
## Tasks

- [ ] Review setup and update if necessary
Or,

- [ ] Remove dashboard if no longer needed

**Comment by saneshark** [comment]
We've created a new dashboard to track VAMF failures. This will work better for triggering alerts but first we need to establish a baseline before switching over.
