### ISSUE TITLE
(WIP) Dashboard | PPMS, Facilities API status for CC

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17191]
## Issue Description
There are known uptime issues with PPMS. While we are integrated with the facilities api for community care provider selection, we'll need to monitor impact to the provider selection page.

---
## Tasks
- [ ] Create visualization for tracking PPMS status/errors

**Comment by laurenernest** [comment]
@LanceGundersen Can you upload that spreadsheet you put together with the tests you ran?

@saneshark Please update this ticket with the technical work needed specifically to cover our MVP configurations.

**Comment by laurenernest** [comment]
@saneshark @grossb1 Do you still want/need this ticket?

**Comment by laurenernest** [comment]
@grossb1 assigning to you for next steps

**Comment by grossb1** [comment]
Check with Lance to see if there is already something similar in Grafana that the facility-locator or VSA-facility team created

**Comment by ajmagdub** [comment]
This ticket was created when Grafana was our only application monitor; we switched to Datadog. In Grafana, a separate dashboard was needed for PPMS calls; with Datadog, a separate dashboard is unnecessary.

The following Datadog log query monitors PPMS calls:
[PPMS calls](https://vagov.ddog-gov.com/logs?agg_m_a=count&agg_m_b=count&agg_m_c=count&agg_m_source_a=base&agg_m_source_b=base&agg_m_source_c=base&agg_t_a=count&agg_t_b=count&agg_t_c=count&cols=host%2Cservice%2C%40payload.status%2C%40duration&ff_display=a%2Cb%2Cc&fromUser=true&messageDisplay=inline&query_a=vaos%20service%20call%20%40payload.url%3A%2A%2Fppms%2Fv1%2Fproviders%2F%2A%20env%3Aeks-prod%20%40http.status_code%3A2%2A%20&query_b=vaos%20service%20call%20%40payload.url%3A%2A%2Fppms%2Fv1%2Fproviders%2F%2A%20env%3Aeks-prod%20%40http.status_code%3A4%2A%20&query_c=vaos%20service%20call%20%40payload.url%3A%2A%2Fppms%2Fv1%2Fproviders%2F%2A%20env%3Aeks-prod%20%40http.status_code%3A5%2A%20&refresh_mode=sliding&storage=online_archives&stream_sort=desc&view=spans&viz=timeseries&from_ts=1712758917107&to_ts=1712845317107&live=true)
