### ISSUE TITLE
Design Feedback - Usability Testing Prep -  Healthcare Experience - Questionnaires MVP

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#17190]
## Acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
If the tabs test well please fill out a [new feature ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?template=feature_request.md). This will be nice to add to our design system : )

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Make sure the font weight on the into paragraph is 400. In this link it looks a little light but that may be the mock up

**Should:**
- Change the Sign in or create an account button color to green. Similar to the track [prescriptions page](https://www.va.gov/health-care/refill-track-prescriptions/). I do not feel this is a must because we have it both ways currently on va.gov but I reached out to Crystabel and she agreed it should probably be green

- On the review page, remove the accordions and try well formatted text instead. A best practice of accordions is that only the first one should be expanded when a user enters the page and that you only expand one at a time. In the mock up they are all expanded. I think that is because you want the user to view all the information. [Design.va.gov](https://design.va.gov/components/accordions.html) says “If visitors need to see most or all of the information on a page. Use well-formatted text instead.”

**Consider:**
- None

**Comment by kristenmcconnell** [comment]
@allison0034 Thank you for the feedback. I have some questions/comments.

I'm using the "lead" font class from the design library for all intro paragraphs (granted I am a version behind in my library...I was going to update after this round of testing). 
![Screen Shot 2020-12-10 at 10.20.08 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8a075333-4b14-4e1c-b4cc-02dca0da3a45)

I will definitely change the button to green.

About the review page, engineering told me that both of the accordions are closed by default. If that is not correct, let me know. This page is mostly auto-generated by the forms library. I have both accordions open in this prototype to promote conversation on what content is shown. This is our second test on that page, so I'm not so worried about the actual accordion behavior for this test.

**Comment by allison0034** [comment]
@kristenmcconnell if both accordions are closed then you are fine to use them. I assumed you wanted them open given the comp. Thanks for the response and nice work!

**Comment by kristenmcconnell** [comment]
Great. I updated the buttons. I think it is good to close from my end.
