### ISSUE TITLE
VA.gov Backends - Establish a better intake process for bringing new VA backends online

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#172]
## Description

Our process for bringing up new VA backends is not scaling well as the frequency of these backends being needed has increased while we bring on external teams. There's a number of systems that need to work independently which need varying bits of information in order to work: fwdproxy (needs some terraform and proxy configuration changes), PagerDuty services, vets-api configuration, ESECC requests, breakers in vets-api all interplay here. To make matters worse, often we have to request lower environments from ESECC first and wait for a "production need" for the backend, and then make a second request for the production service.

## Pain Points being addressed:
- Confusing when currently bringing on a new backend.
- highly complex and difficult for VSP Operations to bring up a new backend. 

## User Story
As a VFS team, I need to be able to bring new backends up easier, so that developers can feel empowered to bring to services to VA.gov.

## Goals
New backed process for scalability 

## VSP OKRs 
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## KPIs
- Increase in customer NPS				
- Reduction in volume of "non-human-needed" support requests month over month

**Comment by jhouse-solvd** [comment]
Please see #17349 for a more current iteration of this effort. 

Closing.
