### ISSUE TITLE
RD: Backend Service

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1720]
### Tasks
- Investigate how the backend service on the front end makes a call 

### Definition of Done
- [x] Use the backend service to retrieve data from vets-api

### Notes
- What did we learn about this?
- [ ] Any notes for the Call Center should be uploaded to `feature/$feature-name/call-center` in GitHub

**Comment by micahchiang** [comment]
@jason-gcio - I've updated the definition of done for this ticket to more closely align with the purpose of a backend service - to retrieve data from an api. I will transfer the original definition of done (pull and display data) to the other ticket in this sprint that deals with frontend display.

**Comment by micahchiang** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/api/index.js handles calls to the backend and is used in both redux actions and plain react components. 
- When should it be used in one over the other?

**Comment by micahchiang** [comment]
Typically backend requests are handled in asynchronous redux actions: 

https://github.com/department-of-veterans-affairs/vets-website/blob/d238bdd6f73e8e769609c2c2ea037cede3f56108/src/applications/personalization/profile360/actions/index.js

A wrapper function is provided in a util file that handles importing an `apiRequest` function from src/platform.
