### ISSUE TITLE
[FE] Provide specific alert when VA profile updates fail due to MVI errors

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#17210]
## Background
Front end devs will put in temp messaging to be updated by content
See [slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1608141192198800?thread_ts=1608137686.190000&cid=C909ZG2BB)

Error # - definition - action to be taken
**ADDR301** - when user trys to create an address but already has an an active address with the purpose of use (POU)- TBD

**MVI202** - Duplicate ID ticket which should go to almost none after VA Profile releases a Prod change on Wed 12/16.  That means that VA Profile will accept the Contact Info Update from VA.gov. NOTE: Not everyone is blocked from logging in to VA.gov if they have a duplicate ID. The duplicate ID blocking happens through our SSOe, but right now, we are only putting 30% of traffic through the SSOe version of the build. That means 70% of traffic still goes through the old version of login, which does allow people with duplicate IDs to sign in. This explains why these people are able to go to the profile and make updates. - TBD

**MVI209** - Due to the Vet having two Corporate PIDs in MPI - Fixing it would require opening a ticket with the corporate team to manage the identity issue with MPI

**MVI207** - 

## Tasks
- [ ] Create alerts for different error types as needed (once we have more information and following VA Profile deploy on 12/16/20)

**Comment by mshea0606** [comment]
As of right now, we are going to wait a few days to see the effects of the VA Profile fix, and wait for Erik/Sandra to complete other error-related tickets prior to determining how we should handle messaging.

**Comment by Samara-Strauss** [comment]
This can be moved to the backlog. [As you can see from the analytics](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/), now that we've fixed the tracking issues we were having, the errors are not nearly as much of an issue as we thought. *If* you really want to work on this, fine by me, but given Tressa and Cassandra's limited availability to help with UX, I would recommend moving this to the backlog.
