### ISSUE TITLE
Testing for SSOe in Prod

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#17213]
Need to login with accounts and make sure it works.

**Comment by srmyers17** [comment]
We're estimating our work, this doesn't include the work to upload the certs on the vets-api and IAM team, which could take longer.

**Comment by jjulian** [comment]
I'm working with IAM and devops today to get this connection established. Waiting to get approved by the ESECC.

**Comment by jbritt1** [comment]
I think this is good to go at this time: https://dsva.slack.com/archives/CBU0KDSB1/p1610651980022900?thread_ts=1610140925.277700&cid=CBU0KDSB1. Thanks all for your patience and apologies for the delays.
