### ISSUE TITLE
[Spike] Toolkit Framework Decision

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#17219]
## Description

Choose a framework that the toolkit will be built upon

## Acceptance Criteria
- [ ] Framework has been decided and document

## Notes
- CLI Best Practices [guide](https://clig.dev/) - **useful read!!**
- [Demo spike](https://github.com/department-of-veterans-affairs/vsp-toolkit) was built on [`oclif`](https://oclif.io/)
- Other considerations: [TTY Toolkit](https://ttytoolkit.org/), [Thor](https://github.com/erikhuda/thor/blob/master/lib/thor.rb)

**Comment by alexpappasoddball** [comment]
@erluti This is done.  Would you add the notes on the decision and close this out?

**Comment by erluti** [comment]
Decided on TTY because it's fully-featured and built on ruby.  Our MVP for the toolkit is vets-api related, so ruby is already a requirement.
