### ISSUE TITLE
Wrap generator command with Toolkit

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#17220]
## Description

The new rails generator should be able to be invoked by the toolkit with one command

## Acceptance Criteria
- [ ] Rails generator is invoked by the toolkit with one command

**Comment by erluti** [comment]
Duplicate of https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17527
