### ISSUE TITLE
[526] Determine if users should be able to add blank conditions to the 526 application

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#1724]
## Purpose
During the demo of work for #1365, we learned that Veterans can add blank/unknown conditions to the 526 application. We need to determine if this is the appropriate user experience. 

### Screenshot 
Currently, Veterans can add blank conditions to the 526 application. (In the below screenshot, a blank condition has been added.)
![image.png](https://images.zenhubusercontent.com/5b744a5479b04b75031e37c2/8f888d68-ed5a-4729-9931-8f735d6d887b)

## Def of Done
- [ ] Determine the consequences of submitting blank conditions to the application
- [ ] Determine if form validation is a more appropriate solution
- [ ] Document recommendations and, if needed, create a Front End ticket for proposed work

**Comment by smoonpeyes** [comment]
@YanaRoy Tagging you for awareness.

**Comment by kevinstachura** [comment]
Per @SMLuthi - "For a “condition” to be valid, it requires a condition and cause" 

So we will need to prevent users from submitting blank conditions via the 526 form with validation checks. Next step is to create a ticket for this for design and FE dev.
