### ISSUE TITLE
dangerbot should be running

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#17249]
Investigate why this PR didn't even get a warning message from Dangerbot https://github.com/department-of-veterans-affairs/vets-api/pull/5439

discussion started here https://dsva.slack.com/archives/CQHBJ5U06/p1607465545096500

**Comment by erluti** [comment]
@thilton-oddball contributed this PR that should improve the situation https://github.com/department-of-veterans-affairs/vets-api/pull/5480

**Comment by erluti** [comment]
This PR is still weirdly not getting noticed by dangerfile https://github.com/department-of-veterans-affairs/vets-api/pull/5468

**Comment by thilton-oddball** [comment]
This has been completed and deployed.
