### ISSUE TITLE
Update RS homepage content in the CMS for 1.1 FE

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#17251]
## Update RS homepage content in the CMS for 1.1 FE

New ~interim~ 1.1 design mockups are in [related FE ticket #15649 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15649)

**AC:**
- [x] Update "Find articles by..." text to "Browse by topic"
- [x]  Add more` Browse by topic` benefit topic categories - [See FE ux logic](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/LC-homepage-requirements.md#browse-by-topics-section)
- [x]  Add `Browse by audience` section and content via taxonomy dashboard in the CMS - [See FE ux logic](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/LC-homepage-requirements.md#browse-by-audience-section) - Update 12/16: This is ready now in the CMS.

### Additional info

???

FYSA @brianalloyd @bethpottsVADEPO

**Comment by RLHecht** [comment]
This work is all done. For the Browse by topic section I added in decision reviews and education and kept in Jen's Benefits and Memorials with the test copy for now. I also turned on the audience tag for All Veterans, Vietnam Veterans and Family Members and Caregivers. I think this ticket can now be closed. FYSA @brianalloyd @jenniferlee-dsva @kelsonic

**Comment by jenniferlee-dsva** [comment]
Thank you @RLHecht !

**Comment by brianalloyd** [comment]
Thanks @RLHecht great work.
