### ISSUE TITLE
Menu item in megamenu in Drupal is not showing up on FE

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#17258]
Menu item in megamenu is not showing up on FE. This was reported in [this slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1607474749185300) in #cms-support by a CMS editor. 

## Expected Behavior

Randi added Educational and career counseling to the megamenu menu in Drupal (http://prod.cms.va.gov/admin/structure/menu/manage/header-megamenu?destination=/admin/structure/menu), but it’s not showing up in the va.gov menu under Careers and employment. 

## Acceptance Criteria

- [ ] See screenshot

![Slack___cms-support___Digital_Service___VA](https://user-images.githubusercontent.com/643678/101700025-569c3200-3a4a-11eb-8902-f392b412d403.jpg)

**Comment by kevwalsh** [comment]
So i just learned that the megamenu is actually not pulling at all from Drupal, but is pulling from https://github.com/department-of-veterans-affairs/vets-website/blob/acd838649213ab0ec3c20917ec98b36b5ef526af/src/platform/landing-pages/header-footer-data.json ... which explains this "bug". Still an FE issue, but the premise of the issue title and description is invalid!   /cc @RLHecht

**Comment by youngfreezyVA** [comment]
lol.. was literally just saying that haha. I need the "href" to add it to the links array :)

**Comment by kevwalsh** [comment]
@youngfreezyVA i was just chatting with @ncksllvn about this. he's not convinced the megamenu is not coming from the content API. i suppose the way to know would be to make the edit to that json file and see if it shows up locally?

**Comment by RLHecht** [comment]
@youngfreezyVA I don't see the link in the megamenu. Has this been fixed?

**Comment by youngfreezyVA** [comment]
@RLHecht Yes. this issue was auto closed when the PR was merged in to master, and the changes will be reflected after the next deployment.

**Comment by RLHecht** [comment]
@youngfreezyVA I see this is now in the header but it's not in the right position. It should go directly below the How to apply line. It's in the correct order within Drupal but I'm guessing that doesn't matter. Can you update this? Thanks!

**Comment by youngfreezyVA** [comment]
there was a bug in the existing sort function when building the links array. just pushed a fix

**Comment by brianalloyd** [comment]
Thanks @youngfreezyVA for the follow up and bug fix.

**Comment by brianalloyd** [comment]
Closing this out as it appears validated and resolved.

**Comment by RLHecht** [comment]
@brianalloyd the order of the items still needs to be changed but I can check back after today's deploy. It might have needed this build to work.

**Comment by brianalloyd** [comment]
Thanks @RLHecht I'm going to reopen the ticket, sorry for the preemptive closure.

**Comment by erogray** [comment]
Hi @brianalloyd and @RLHecht  — it looks like the menu item is now showing up in the correct place, can you confirm? Thanks!

**Comment by brianalloyd** [comment]
@erogray its also showing correct on my end as well.  I'll let @RLHecht confirm then we can close out this issue if AC has been achieved.  Thanks.

**Comment by RLHecht** [comment]
@erogray Looks good to me! We can close this ticket. FYSA @brianalloyd
