### ISSUE TITLE
Update Privacy Policy URL

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17263]
## Acceptance Criteria:
1. Update the URL on the Privacy Policy ListItem so it points to: https://www.va.gov/privacy-policy/

Original ticket: [#13967 ](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13967)

**Comment by esther-k** [comment]
**12/11**
Pass on iOS and Android. Moving to Design QA
