### ISSUE TITLE
[Bug] Facility Locator - Instruction in empty result-list missing required Facility-type selection

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#17261]
## What happened?
On Staging **Find VA locations** page, initial instruction in the empty results-list panel is missing the required Facility-type selection.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]

## Steps to Reproduce
1. Go to **https://staging.va.gov/find-locations** [this defect is same regardless of geolocation permission].
2. In empty **result-list column** (left of mapbox), observe that the **initial instruction** copy is missing the required Facility-type selection before "and click search".

**Screenshot**
![fl-me-bug-copy-init-instr](https://user-images.githubusercontent.com/587583/101700035-96a6e900-3a39-11eb-9fda-7e10fdecac53.png)

## Desired copy
Instruction should include mention of required Facility-type selection before "and click search".

## Acceptance Criteria
- [ ] Before the Veteran triggers an initial search, the instruction copy in the empty **result-list column** (left of mapbox) says 

> Please enter a location (street, city, state, or postal code) and facility type, then click search above to find facilities.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Good catch, @tlei123 thank you!

**Comment by mmiddaugh** [comment]
From staging: 
![image](https://user-images.githubusercontent.com/55411834/102381444-78377500-3f86-11eb-9f50-96ee936840a5.png)
@tlei123 this fix is available for your review in staging

**Comment by tlei123** [comment]
Validated on Staging.

cc @mmiddaugh @brangi

**Comment by tlei123** [comment]
New post-Staging-Review test-run just completed, incl. all failed test-cases for the 2 defects found (this one and #17305:

[New Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/179) (no defects).
