### ISSUE TITLE
General Analytics Request for Digital Health Modernization Team

### ISSUE THREAD

**Issue by mpeterz** [department-of-veterans-affairs/va.gov-team#17262]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [X] Description
- [X] Timeframe for Analytics Requested
- [X] Analytics to Track Down
- [X] Which Product Questions are you trying to answer?
- [X] Additional Comments

## Description
Who is this request for?
The *Digital Health Modernization Team.* Here are points of contact:
- Aryeh Jacobsohn - aryeh.y.jacobsohn@omb.eop.gov
- Meg Peters - meg.peters@va.gov - @mpeterz 
- Emily Mann - emily.mann1@va.gov - @emily-mann 
- Kimberly McManus - kimberly.mcmanus@va.gov - @kimberlymcm 
- Glennette Clark - glennette.clark@usds.dhs.gov

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?
The *Digital Health Modernization Team.* We are working on understanding the health experience for Veterans, starting with My HealtheVet analytics. 
    
- What type of analytics support are you looking for?
Glennette Clark of USDS has built a dashboard that shows My HealtheVet data in Google Analytics Data Studio platform. (It pulls Google Analytics data from VA's instance of GA.) But due to permissions issues, no one outside of Glennette's domain (usds.dhs.gov) can access the dashboard. 

Ultimately we'd like to create a health analytics dashboard in Domo. As the first step towards that, in the short term we're requesting that the Analytics & Insights team recreate the dashboard Glennette built in Google Analytics in the VA environment. We met with @bmcgrady-ep December 16 to discuss this plan.

Here's a PDF of the health dashboard.  
[Google_Analytics_Behavior_Overview_-_12_02_2020,_9_40_AM (1).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5712638/Google_Analytics_Behavior_Overview_-_12_02_2020._9_40_AM.1.pdf)

A couple things:
* Since we'll integrate this GA dashboard into Domo later, we'd like it to be clear (visually on the dashboard) that these analytics are for My HealtheVet.
* Ideally the COVID comparison on page 5 would show the same number of months before and after COVID. Is it possible to do that dynamically? 

**Shortly after creating the initial GA dashboard...**
Once we finish our current qualitative user research in December, we'd like to add the following data for top health task workflows. To plan this, we'd like to meet with someone from the Analytics & Insights Team in January to discuss the best way to get this info.
* Common user paths between My HealtheVet, eBenefits, and VA.gov
* How are people getting to the top workflows (exs: send secure message, refill prescription)? 
* Where do they get stuck between VA websites?

  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
We'd love to get the GA dashboard with the data sets in the attached PDF around January 8. Many thanks to the Analytics & Insights Team!

## Analytics to Track Down
> Examples
> 
> - [ ] Metric 1
> - [ ] Metric 2
> - [ ] Metric 3

## Which Product Questions are you trying to answer?
The attached PDF has the analytics we want to see and track. 

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @mpeterz , 

Thanks for your request here, acknowledging receipt

**Comment by aryeh-usds** [comment]
Aryeh Jacobsohn's handle is @aryeh-usds

**Comment by mpeterz** [comment]
Just a heads-up to @bmcgrady-ep and @jonwehausen that @aryeh-usds will be the point of contact for this while I'm out Dec 21 to Jan 1. Thanks so much!

**Comment by bmcgrady-ep** [comment]
Thanks for the update @mpeterz!

**Comment by mpeterz** [comment]
Hi, @bmcgrady-ep. I'm back in the office and noticed that this request is blocked. As requested, we did provide the PDF of the dashboard Glennette created in Data Studio (see above). Do you have all the info you need? Thank you!

**Comment by bmcgrady-ep** [comment]
Hi @mpeterz - Thank you for bringing this to my attention. I did not originally see the PDF of the Data Studio report, which is why I moved it to Blocked. I moved it back to In Progress and will work on replicating the report in Google Analytics.

**Comment by mpeterz** [comment]
Thanks, @bmcgrady-ep!

**Comment by bmcgrady-ep** [comment]
Here are some links to reports in GA that replicate the Data Studio Report. One thing that I will specifically note is that all of these reports are generic reports in Google Analytics, so they will not look exactly like the Data Studio Report, but essentially contain the same information.

- [Audience Overview](https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p178570976/_u.dateOption=last30days/)
- [Demographics Overview (Gender and Age)](https://analytics.google.com/analytics/web/#/report/visitors-demographics-overview/a50123418w177519031p178570976/_u.dateOption=last30days/)
- [Users by Country](https://analytics.google.com/analytics/web/#/report/visitors-geo/a50123418w177519031p178570976/_u.dateOption=last30days/)
- [Device Breakdown Report ](https://analytics.google.com/analytics/web/#/report/visitors-mobile-overview/a50123418w177519031p178570976/_u.dateOption=last30days&explorer-graphMode.mode=lineChart&explorer-table-tableMode.selected=pie)
- [Site Search Terms](https://analytics.google.com/analytics/web/#/report/content-site-search-search-terms/a50123418w177519031p178570976/_u.dateOption=last30days/)
- [Event Action Breakdown](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p178570976/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction)
- [Top Referrers Report](https://analytics.google.com/analytics/web/#/report/trafficsources-all-traffic/a50123418w177519031p178570976/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.source&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.medium&explorer-table-tableMode.selected=data)
- [Most Popular Pages](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178570976/_u.dateOption=last30days/)
- [Most Popular Pages by Page Title](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p178570976/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.pageTitle&explorer-table.plotKeys=%5B%5D)

I am working on adding the Covid reports in as well.

**Comment by bmcgrady-ep** [comment]
@mpeterz - Let me know if the GA reports above help out or if you are looking for something else.

**Comment by mpeterz** [comment]
@bmcgrady-ep  - Thanks for sending the reports. You are asking if we'd like to use these reports in the new dashboard we've requested?

**Comment by bmcgrady-ep** [comment]
@mpeterz - With the size of the Data Studio report that you sent over, it would probably have to be a couple of different GA dashboards. I am happy to build these out, but wanted to confirm that you are okay with this. Also, want to let you know that the GA reports above will be more robust than the custom GA dashboard in that you can do more detailed analysis with the links above.

**Comment by mpeterz** [comment]
Thanks, @bmcgrady-ep. I'm also wondering if there were reports in the Data Studio dashboard from Glennette that we can't get. 

Once I hear from you, I will run this by the team. If we have questions, we might want to chat. Thank you!

**Comment by bmcgrady-ep** [comment]
Hi @mpeterz - Thank you for your patience here. I have created 3 different dashboards in Google Analytics to help report on the same metrics that are in the Data Studio dashboard. 

Here they are:
- [Audience Overview](https://analytics.google.com/analytics/web/template?uid=DlVMr42LTJa4ruHmKnI-sg)
- [Content Overview](https://analytics.google.com/analytics/web/template?uid=sjWNxIbhQL-XnB1ok0tqKg)
- [Covid-19 Overview](https://analytics.google.com/analytics/web/template?uid=TLO3AgwqSYmo3KL0HlLi2g) (time comparison)

For each of these links, it will ask you to select a Google Analytics view and I would recommend selecting the myhealth.va.gov view in Google Analytics. Let me know if you have any trouble getting the dashboards setup. Also, feel free to reach out with any changes you would like to the dashboards.

**Comment by mpeterz** [comment]
Thank you very much, @bmcgrady-ep! @aryeh-usds and I might have some questions.

**Comment by bmcgrady-ep** [comment]
You're welcome! I am closing this ticket, but feel free to reopen if you have any questions.
