### ISSUE TITLE
Fail the Jenkins build if the fallback to the cache fails

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#1726]
## Problem
If the Metalsmith build script failed due to a Drupal content issue, we'll try to fall back to the cache. If there's no cache to fall back to, there's little point in trying again to query Drupal again and go through the exact same process to get the exact same failure. This just takes up more resources and causes the build to take longer before failing.

## Acceptance Criteria
- [ ] The Jenkins build fails if the fallback to the cache fails

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
Note to my future self: Ensure this doesn't happen already by pushing up a branch with an intentionally-failing Metalsmith build (just `throw` an exception). Pretty sure this ticket still needs to be done, but it's worth double-checking.

**Comment by meganhkelley** [comment]
@cvalarida is this ticket still needed? If not, please close if applicable. Thanks!

**Comment by cvalarida** [comment]
Ooh, good call. Totally forgot about this. I'm sure it's still applicable, but it's a pretty low priority, I think. I'm not sure how often the stars align for this to to happen these days. And when it does, it just means we're using more Jenkins juice than we need to for like another 5 minutes tops, I'd estimate.

Closing now because I'm not convinced it's worth the time spent on it.
