### ISSUE TITLE
Analytics Implementation for Decision Tools - Find a VA Form post-launch MVP

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17273]
# Google Analytics Implementation 

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics

- Who is this request for?

    - @johnhashva John Hashimoto-
    - @zacharymorel Zachary Morel
    - @MarciMcGuireGCIO Marci McGuire
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    -  Decision Tools team, Find a VA Form - post-launch MVP.  The Find a VA Form product was fully implemented in Oct 2020, but at that time was not instrumented to track clicks for the online tool Call to Action links.  In addition, we are now adding two new features for which we would like to track clicks: 
         - A link in the search results to connect the search page to form detail pages whenever they exist -- see https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453
         - A sorting option that will allow users to sort search results by date -- see https://github.com/department-of-veterans-affairs/va.gov-team/issues/14112

- Provide the Domain where Google Analytics needs to be implemented
    -  www.staging.va.gov and eventually va.gov production
    
    _Identify if PII is passed in URL or title tag_
       -  No PII 

    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    - We would like to put this into Production ~Jan 12, 2021~ Jan 18, 2021

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* 
    - Conversions to form PDF downloads are already being tracked from the MVP implementation located at https://www.va.gov/find-forms/.
    - When a user conducts a search for a form for which a details page exists,  the search will now display a CTA link to this detail page.  We would like to track the clicks on these links as well as the conversions listed above (PDF downloads or access to the online tool).
             - Sample detail page URL: https://www.va.gov/find-forms/about-form-10-10ez?_ga=2.118238336.842717027.1609168281-1140567477.1604065121
             - Screen shot:      
     ![detail-page-link](https://user-images.githubusercontent.com/73354907/103228935-ef162b80-48ff-11eb-98e6-51e1c5564a68.png)
    - When a user conducts a search for a form for which an online tool exists
             - Sample online tool URL: https://www.va.gov/health-care/apply/application/introduction?_ga=2.118238336.842717027.1609168281-1140567477.1604065121
             - Screen shot:
     ![online-tool-link](https://user-images.githubusercontent.com/73354907/103228943-f4737600-48ff-11eb-91dc-d303e93c4d47.png)
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._   
        - When a user conducts a search, the search results will also provide a facility for sorting the results by date.  We would like to determine how many users are taking advantage of this sort option:
            - Mockup of sort tool (not yet implemented): 
        ![sort_links](https://user-images.githubusercontent.com/73354907/103228949-f806fd00-48ff-11eb-8a53-9dbb627b7258.png)
    - We would also like to understand how often users are having to modify their search terms before getting a satisfactory result set that leads them to the desired PDF download or online tool.  The plan is to use this metric to show:
1) Reduced ratio of search modifications to PDF form download
2) Reduced ratio of search modifications to form detail page access
3) Reduced ratio of search modifications to online tool access
4) Reduced ratio of total Find a VA Form visits to search modification events
- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
     - N/A this is part of the unauth experience

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
     - N/A this is part of the unauth experience

- Certain conditions/responses that need to be reviewed
    -  Only ~400 VA forms have details pages, so the only time the detail page CTA links will be displayed in the search results is when that condition is true for the form listed.
    -  Only a small subset of forms have online tools, so the only time that button will be displayed is when that condition is true for the form listed.
    - Sorting, once implemented, will be displayed for any search yielding > 1 result.

- Additional Comments

    - The new links to the form detail pages should be visible on Staging the week of 12/21 or 12/28.  We do not yet have an ETA on when the sort feature will be available as it is in design.  

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @MarciMcGuireGCIO , acknowledging receipt here

**Comment by MarciMcGuireGCIO** [comment]
@joanneesteban @jonwehausen updating to advise that the Lighthouse API should be modified today or tomorrow to expose the links we want to track, and the addition of the links to the UI should be deployed behind a feature flag today or tomorrow as well. 

cc: @zacharymorel @johnhashva

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @markgreenburg the feature flag has been deployed on vets-website to prod. You can now remove the serializer flags.

**Comment by jenniferlee-dsva** [comment]
Hi @MarciMcGuireGCIO @jonwehausen - just a quick note of clarification. The Find a VA form GA dashboard does not currently track clicks to online tool CTA buttons. 

When we launched the find forms page, online tool CTAs were not yet available (bc the CMS had not yet been hooked up for form page rich meta data). 

So in any case, for the dashboard update, I believe @jonwehausen, it would need to include the new additions: 
- clicks to online tool CTA buttons (when a form has one; not all do)
- clicks to the form detail landing page link (when a form has one - most, but not all do)
- date sort functionality usage

**Comment by MarciMcGuireGCIO** [comment]
@jenniferlee-dsva thank you for clarifying.  I will add the link to the online tool CTA to our current analytics request since work on that has not yet been started.

**Comment by MarciMcGuireGCIO** [comment]
@jonwehausen, I've updated this request to provide better clarity, along with some relevant screen shots.  Let me know if you have questions!  Thx!

**Comment by jonwehausen** [comment]
# Data Layer Specification

## Context 
- @zacharymorel The spec you will find below is a consistent spec with what has been implemented for other new search areas of the site: most notably the ahead search roll-out and resources + support roll-out
- Our goal here is to design the data layer consistent yet flexible enough to capture the same level of insight for our growing search touch points

## On Search - When a user executes a search and search results are returned

### Full Spec Example
```javascript
recordEvent({
    'event': 'view_search_results', //remains consistent, push this event with each search
    'search-page-path': '/find-forms', //populate with '/find-forms', remains consistent for all searches from find-forms page
    'search-query': '10-10ez', //populate with full query user used to execute search 
    'search-results-total-count': 3, //populate with total number of search results returned
    'search-results-total-pages': 1, //populate with total number of search result pages returned
    'search-selection': 'Find forms', //populate with 'Find forms' for all searches from /find-forms page
    'search-typeahead-enabled': false, //populate with boolean false, remains consistent since type ahead won't feature here
    'type-ahead-option-keyword-selected': undefined, //populate with undefined since type ahead won't feature here
    'type-ahead-option-position': undefined, //populate with undefined since type ahead won't feature here
    'type-ahead-options-list': undefined, //populate with undefined since type ahead won't feature here
});
```

## On Search Results Click - When a user clicks on a search result link 
![image](https://user-images.githubusercontent.com/48527022/103233473-3f46bb00-490b-11eb-9c99-8fe0ae679a83.png)

### Full Spec Example
```javascript
recordEvent({
  'event': 'onsite-search-results-click', /remains consistent, push this event and metadata with each search result click
  'search-page-path': '/find-forms', //consistent for all search result clicks from this page
  'search-query': '10-10EZ', //dynamically populate with the search query 
  'search-result-chosen-page-url': 'https://www.va.gov/find-forms/about-form-10-10ez', //populate with the full href of the form detail page or tool page
  'search-result-chosen-title': '10-10EZ Instructions and Enrollment Application for Health Benefits', //or 'Download VA form 10-10EZ (PDF)' or 'Go to online tool'
  'search-result-type': 'title', //populate with 'pdf' if pdf, or 'cta' if "Go to online tool" 
  'search-results-pagination-current-page': 1, //populate with the current pagination number at time of result click
  'search-results-position': 4, //populate with position on page of result click
  'search-results-total-count': 999, //populate with the total number of search results at time of click
  'search-results-total-pages': 100, //populate with total number of result pages at time of click
  'search-selection': 'Find forms', //populate consistently with 'Find forms'
  'search-results-top-recommendation': undefined, //consistently populate with undefined since there's no top recommendations surfaced here
  search-typeahead-enabled: false, //consistently populate with false since there's no type ahead enabled for this search feature
});
```

## Search Results Filtering/Sorting - When the sort has completed and results have been reorganized and returned back to user
![image](https://user-images.githubusercontent.com/48527022/103238580-28a76080-4919-11eb-8a93-2168c22af827.png)

### Full Spec Example
```javascript
recordEvent({
  'event': 'onsite-search-results-change', 
  'search-query': '10-10EZ', //dynamically populate with the search query 
  'search-results-change-action-type': 'sort', //will consistently classify these actions as 'sort', leaves the door open for other search enhancements to user "filter"
  'search-results-change-action-label': 'newest', //'oldest' //populate according to user selection  
  'search-results-pagination-current-page': 1, //populate with the current pagination number 
  'search-results-total-count': 999, //populate with the total number of search results 
  'search-results-total-pages': 100, //populate with total number of result pages 
});
```


### Next Steps
- @zacharymorel Please let me know any questions you have here, please don't hesitate to ask -- this spec is ready to begin implementation. 
- @MarciMcGuireGCIO @jenniferlee-dsva the above spec will cover your search-related questions and allow us to measure this data in a similar manner to other search areas of the site
- We will begin staging the google tag manager adjustments on our part in preparation for QA testing when data layer has been implemented

**Comment by zacharymorel** [comment]
Note to self: Provide link of PR to GA team.

**Comment by jonwehausen** [comment]
@bsmartin-ep or @bmcgrady-ep 

Can one of you QA these two GTM containers once @zacharymorel changes have been made available in staging? 
- [Search Results Type Addition to Event Action](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000434)
- [Search Sort Feature](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000436)

### Context of Changes
- There shouldn't be any changes necessary to the existing `view_search_results` tagging, only the new event for the sorting and adjustment to the event action to include `'search-result-type'`
- Please test these workspaces not just with /find-forms but with other areas of search at `/search/` and `/resources` for example

**Comment by zacharymorel** [comment]
@jonwehausen the following events for **_On Search Results Click - When a user clicks on a search result link, cta, or pdf_** and **_On Search - When a user executes a search and search results are returned_** are currently on staging. 

The Sorting feature is still in discover phase. So a separate GA implementation work will be done with it then. 
Here is the user story tracking the work listed above. https://github.com/department-of-veterans-affairs/va.gov-team/issues/17898

**Comment by jonwehausen** [comment]
## Data Layer QA Testing

@zacharymorel Please see the following data layer test results. 


### On Search

Description of Interaction | Data Layer Screenshot  | Test Status
------------ | ------------- | -------------
_Search for a legitimate form - "10-10ez"_ | ![image](https://user-images.githubusercontent.com/48527022/103702903-ca135f80-4f74-11eb-99ad-a145deda3b83.png) | ✔️ **PASS**
 _Search for an illegitimate form (0 results) - "12345" | ![image](https://user-images.githubusercontent.com/48527022/103703381-75241900-4f75-11eb-9165-4f488edcec3b.png) | ✔️ **PASS**

### On Search Results Click 

Description of Interaction | Data Layer Screenshot  | Test Status
------------ | ------------- | -------------
Click on a search result title link - performed search of "10-10ez" | ![image](https://user-images.githubusercontent.com/48527022/103703689-fe3b5000-4f75-11eb-9adb-b49ef655598c.png) | ⚠️ **DOES NOT PASS** <br><br>_`'search-result-type'`_ should be `'title'` in this scenario
Click on CTA - performed search of "10-10ez" | ![image](https://user-images.githubusercontent.com/48527022/103703899-6427d780-4f76-11eb-9c2c-b2a514f10446.png) | ✔️ **PASS**
Click on PDF | ![image](https://user-images.githubusercontent.com/48527022/103704120-c1238d80-4f76-11eb-8f27-dcbe0fb91c8d.png) | ✔️ **PASS**
Click on a pdf result in 3rd position | ![image](https://user-images.githubusercontent.com/48527022/103704285-0e9ffa80-4f77-11eb-94ae-d453a06b4396.png) | ✔️ **PASS**

### Next Steps 
- @zacharymorel Thanks for the notice on the sorting functionality. Just curious of if you have an eta of when that will be implemented for our awareness. Looks like the only piece of the data layer we need to correct is the `'search-results-type'` when it's the standard `'title'` click
- @bsmartin-ep this will then be ready for your GTM tagging QA following Zach's updates

**Comment by jonwehausen** [comment]
cc: @ianMcCullough-ob @joanneesteban for visibility

- Another example of our QA documentation above @ianMcCullough-ob for your awareness

**Comment by jonwehausen** [comment]
Per @MarciMcGuireGCIO roll-out date has been adjusted to Jan 18. 

cc: @bsmartin-ep

**Comment by zacharymorel** [comment]
2nd Pull Request submitted.

**Comment by zacharymorel** [comment]
@jonwehausen The Form Title event is ready for validation!
https://staging.va.gov/find-forms/?q=caregiver

**Comment by jonwehausen** [comment]
## Data Layer QA Round 2

### On Search Results Click 

Description of Interaction | Data Layer Screenshot  | Test Status
------------ | ------------- | -------------
Click on a search result title link - performed search of "caregiver" | ![image](https://user-images.githubusercontent.com/48527022/103944427-a598be00-5101-11eb-8482-4290f730ad53.png) |  ✔️ **PASS**
Click on CTA - performed search of "caregiver" | ![image](https://user-images.githubusercontent.com/48527022/103944525-c7924080-5101-11eb-8484-500414842d3d.png)  | ✔️ **PASS**
Click on PDF | ![image](https://user-images.githubusercontent.com/48527022/103704120-c1238d80-4f76-11eb-8f27-dcbe0fb91c8d.png)  | ✔️ **PASS**

@zacharymorel this looks good! Appreciate your work here!

**Comment by jonwehausen** [comment]
@bsmartin-ep We can do the GTM QA here now

**Comment by zacharymorel** [comment]
Sweet, let me know once that passes/ fails so I can close a related user story or continue working on it.

**Comment by bsmartin-ep** [comment]
## QA - On Search Results Click 

Description of Interaction | Data Layer  | Tagging | Test Status
------------ | ------------- | ------------- | ----
Click on a search result title link - performed search of "caregiver" | ![image](https://user-images.githubusercontent.com/62304138/104136837-ae3dfe00-5366-11eb-9fd9-50293137dc17.png) |![image](https://user-images.githubusercontent.com/62304138/104136854-c6ae1880-5366-11eb-8288-22d91e9cb317.png)  | ???
Click on CTA - performed search of "caregiver" | ![image](https://user-images.githubusercontent.com/62304138/104136886-fd842e80-5366-11eb-963f-db171a333abc.png) | ![image](https://user-images.githubusercontent.com/62304138/104136913-23113800-5367-11eb-8dbd-5e7c46ac5f5d.png) | ???
Click on PDF |![image](https://user-images.githubusercontent.com/62304138/104136934-3ae8bc00-5367-11eb-999a-e6aa6f22b16b.png)  | ![image](https://user-images.githubusercontent.com/62304138/104136946-4cca5f00-5367-11eb-98b2-cc3ad826a5ed.png) | ???

One question @jonwehausen - should the new `search-result-type` go to the end of the Event Action as not to disturb the indices of the existing values?

**Comment by MarciMcGuireGCIO** [comment]
@jonwehausen -- just following up on ^^.  I think Zach had a question for you above.  Thanks!

**Comment by jonwehausen** [comment]
Thanks @bsmartin-ep , and great call. 

I have moved `'search-result-type'` into CD index 120 as a result of your feedback. If you could quickly re-QA with the CD population. We can then publish and close here!

@zacharymorel @MarciMcGuireGCIO there shouldn't need to be anymore changes on your teams part and we will be ready to go following our latest QA.

**Comment by MarciMcGuireGCIO** [comment]
Thanks all!  Excited to start seeing this in action!

**Comment by bsmartin-ep** [comment]
## QA

Description of Interaction | Data Layer  | Tagging | Test Status
------------ | ------------- | ------------- | ----
Click on a search result title link - performed search of "caregiver" | ![image](https://user-images.githubusercontent.com/62304138/104493708-6fe15280-55a3-11eb-88fc-3bac40189684.png) |  ![image](https://user-images.githubusercontent.com/62304138/104493756-825b8c00-55a3-11eb-9ac7-a81572a82435.png) | :heavy_check_mark: **PASS**
Click on CTA - performed search of "caregiver" | ![image](https://user-images.githubusercontent.com/62304138/104493875-b20a9400-55a3-11eb-9cdc-b8eb6c4e380f.png)  | ![image](https://user-images.githubusercontent.com/62304138/104493919-bfc01980-55a3-11eb-9f62-87d886b1d618.png)   | :heavy_check_mark: **PASS**
Click on PDF | ![image](https://user-images.githubusercontent.com/62304138/104493983-d6667080-55a3-11eb-9b55-7dddc5b7d622.png) | ![image](https://user-images.githubusercontent.com/62304138/104494045-ebdb9a80-55a3-11eb-81ca-20c8f68a06d3.png)  | :heavy_check_mark: **PASS**

These interactions LGTM @jonwehausen.  Sort stuff in the other GTM workspace is on hold, correct?

**Comment by jonwehausen** [comment]
Yes that's correct @bsmartin-ep !

@zacharymorel & @MarciMcGuireGCIO we can close this ticket. If we could have you all please create a new ticket for the sorting feature when that functionality is revisited, that would be very much appreciated. 

Tracking here has officially been published and is ready for go-live. 

cc: @joanneesteban @jason-gcio @bsmartin-ep
