### ISSUE TITLE
FE: Implement `Browse by audience` section design on RS homepage

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#17276]
## This is a sub ticket of #15649. 

**You can test the FE template update against this test CMS content in preview-prod: http://preview-prod.vfs.va.gov/preview?nodeId=8296**

AC - New design elements to update/add in the FE are in the primary ticket #15649:

- [x] Add ` Browse by audience`  design in the FE - [See FE ux logic](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/LC-homepage-requirements.md#browse-by-audience-section)
- [x]  508 compliant
 - [ ] Functionality validated by @jenniferlee-dsva before go-live
 - [ ] Mobile and desktop designs and ix validated by @rtwell before go-live**

~Note: Currently blocked until audience content links added on RS homepage by[ content, ticket #17251](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17251)~  Test content is ready in the above preview node. (Updated 12/17)

### CMS info:

Per [Slack](https://dsva.slack.com/archives/C0173CAJ7A6/p1608221042061300?thread_ts=1608151541.058500&cid=C0173CAJ7A6), Kevin Walsh says: 
"the machine name [of the audience taxonomy on homepage]  is called `field_audience_rs_homepage `(its’ a boolean field, where True = Promoted), the checkbox label is “Promoted to Resources and Support Homepage”.

**Comment by jenniferlee-dsva** [comment]
This ticket is currently blocked so we don't need to work on this until post-code freeze. 

(It's the `Browse by topic` ticket #15649 that we need before code-freeze.

**Comment by ncksllvn** [comment]
Since the "Browse by audience" section doesn't have a relationship to the R&S homepage's content model, we would need to form the relationship during the build process. We already do some build tasks for the R&S section so it isn't a totally new thing.

Tech details -> [This is the file we'd work with.](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/create-resources-and-support-section.js) Basically, what I imagine is having an additional function `addAudienceDataIntoResourcesHomepage` or something like that (definitely doesn't need to be that) that we call.

**Comment by jenniferlee-dsva** [comment]
Added ^ info from Kevin re CMS field. 

Per Slack, Kevin Walsh says:
"the machine name [of the audience taxonomy on homepage] is called field_audience_rs_homepage (its’ a boolean field, where True = Promoted), the checkbox label is “Promoted to Resources and Support Homepage”.

**Comment by ncksllvn** [comment]
Per our [Slack thread](https://dsva.slack.com/archives/C0173CAJ7A6/p1610044993099900), the only audience tag we are currently using is `All Veterans`. This means that if we went live now, the only audience-type listed under `Browse by audience` would be `All Veterans`, which isn't useful. Therefore, this work is effectively blocked until we have associated other audience-types to R&S articles.

**Comment by brianalloyd** [comment]
Thanks @ncksllvn we'll keep this in the backlog until we can review with @jenniferlee-dsva and @johnhashva.  Think we continue to monitor other audience-types for R&S articles in order to build a more inclusive library in the following months.  Thanks for working the details in support.

**Comment by ncksllvn** [comment]
Per standup I am going to try to feature flag this work so that it shows in staging but not production

**Comment by ncksllvn** [comment]
This should be on staging at some point today, https://staging.va.gov/resources/

**Comment by jenniferlee-dsva** [comment]
Hi @ncksllvn 
So on staging, I "promoted" 6 audiences to the homepage, but then when I go to view the RS homepage preview, the `Browse by audience` section does not appear at all. 

**Promoted these 6 audiences to the rs home in Staging:** 

1. All Veterans
2. Family members and caregivers
3. Gulf War Veterans
4. LGBTQ Veterans
5. Service members
6. Vietnam War Veterans

Just to double check, I previewed here: https://staging.va.gov/resources/  and http://preview-staging.vfs.va.gov/preview?nodeId=8296

**Comment by jenniferlee-dsva** [comment]
Like this in staging: 

![image](https://user-images.githubusercontent.com/43381063/104500192-192c4680-55ac-11eb-8797-29608aa88f9f.png)

**Comment by ncksllvn** [comment]
Hm. At some point, the website build was changed so that all environments point to Drupal in prod. I wonder if preview-staging is wired up to Drupal prod even though preview-staging is obviously a staging environment

**Comment by ncksllvn** [comment]
@jenniferlee-dsva can you try promoting some audiences in Drupal prod, then checking preview-staging?

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - I "promoted" those tags to the prod.cms rs home and the staging preview does not show them. (fwiw, the prod preview doesn't either.) 

now, i didn't do anything to the rs homepage itself. (bc my understanding is that we promote them from the taxonomy dashboard.)  KW did say there should be a [field in the rs homepage called field_audience_rs_homepage](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17276#issuecomment-747538896) -- but there's nothing in the RS homepage edit view where an editor would manually check anything.

**Comment by brianalloyd** [comment]
@ncksllvn what's the current status on this ticket, reading through the notes it appears some troubleshooting was happening and wanted to see if this was ready for validation?  Thanks.

**Comment by ncksllvn** [comment]
It’s on staging now - https://staging.va.gov/resources/

Due to a positioning issue, we need to port the blue beta banner out of the CMS and into FE code though. It was a bit of a circus doing it before so I gave it a rest for a few days. I’ll try to port it over tomorrow though

**Comment by jenniferlee-dsva** [comment]
@brianalloyd @ncksllvn Replying to above. 
I think Nick is saying above that this bug is a little messy to undo and will try to do this today.  So this is captured not just in Slack, will post here, too, re duplicate in-body alert component. 

The optional alert component -- if enabled in the CMS  -- should appear just once, below the search bar (and before browse links). 

And [per Ryan Thurlwell's design review](https://dsva.slack.com/archives/C0173CAJ7A6/p1610746368016900?thread_ts=1610723867.004900&cid=C0173CAJ7A6) - A-Ok and thank you for using the standard expander text component!

![image](https://user-images.githubusercontent.com/43381063/105364757-8737c580-5bcb-11eb-9fb1-d5c0de3ce424.png)

**Comment by ncksllvn** [comment]
I just opened a PR to publish the FE code's blue beta banner to all environments. This means we will be able to take the CMS's beta banner down this afternoon. Just to restate - the reason for this is that the main content of `/resources` is basically just a list of dynamic content blocks and the beta banner was just another item in that list. However, the "Browse by audience" is a strict FE component not tied to the CMS. This created an issue bc the "Browse by audience" needed to be position between items in that list of content blocks - after the beta banner but before the rest of the page. The easiest solution was to just move the beta banner into FE code.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - With your change above, will Randi/Beth still be able to publish in-body alert content via the CMS?

**Comment by ncksllvn** [comment]
> @ncksllvn - With your change above, will Randi/Beth still be able to publish in-body alert content via the CMS?

They can still do alert banners in the alert content, but this particular beta banner, being strictly position above the "browse by audience" would be in FE code, so a FE dev would need to do updates to it. I haven't asked Randi to remove the beta banner yet though, so if that's an issue I can hold off

**Comment by jenniferlee-dsva** [comment]
I think I'm starting to grasp the issue, but could we hop on a call to make sure?

**Comment by ncksllvn** [comment]
Sure, I can do that

**Comment by ncksllvn** [comment]
Per call w/ @jenniferlee-dsva we're proceeding in a different direction. We're going to render the "Browse by audience" section by having editor add a List of Links w/a heading that says `Browse by audience` exactly. When that is the case, the actual audience tags will render automatically below. Screenshot of the result ->

![image](https://user-images.githubusercontent.com/1915775/105393700-a72ab180-5bea-11eb-83b5-bb5dbcbb8f31.png)

**Comment by ncksllvn** [comment]
^ this means that an editor will have full control of when that component shows and where on screen it will render, instead of needing a FE dev to do any changes.

**Comment by jenniferlee-dsva** [comment]
Thx @ncksllvn ! I'm validating this as complete and closing this ticket, @brianalloyd . 

For future reference, I have also noted the editorial step when content team is ready to add audience links to the homepage here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/LC-homepage-requirements.md#for-content-editorpublisher-cms-process--fe-logic-on-the-browse-by-audience-section
