### ISSUE TITLE
Move DIC to Disability Hub

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#1727]
## User Story
As a surviving spouse, dependent or parent, I need to easily find DIC benefit info, so I can apply and access the benefit I'm eligible for.

## Goal
Move DIC into Disability where users expect to find it and ensure there is crosslinking in Survivors Pension, Burials and Family hubs. 

## Acceptance Criteria
- [x] DIC page and all DIC rates pages are moved to Disability hub with new URLs
- [x] All existing links to DIC and DIC rates pages are updated to reflect new URLs
- [x] DIC rates pages are removed from Burials hub page and Burials left nav
- [x] Old DIC page URLs are redirected to their new locations
- [x] Links to the DIC rates pages are added to the Disability hub page
- [x] Links to DIC and DIC rates pages are added to Disability left nav
- [x] Content and link to DIC is added to Survivors Pension page
- [x] Content and link to Survivors Pension is added to DIC page
- [x] All master IA documentation is updated

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
@jenniferlee-dsva What is the status of these pages in Drupal?   They will need their URLs updated to reflect that we are moving them to Disability as part of this work. 

/burials-memorials/survivor-dic-rates/
/burials-memorials/survivor-dic-rates/
/burials-memorials/parent-dic-rates/
/burials-memorials/parent-dic-rates/

**Comment by jenniferlee-dsva** [comment]
Burials hub is out of the first pass of UAT, and we'll be going back next week to make SME feedback and other style guide updates. (@peggygannon  and @AnneHurley  - please correct status if I'm behind.) 

@mnorthuis, if you create a ticket with the specific changes that need to be made to the above 4 pages, Peggy and I can implement/review/publish. (Ex: exactly where in the Disability left nav these need to be added.)   RE Disability hub -- I'm going through first pass of UAT bug review for Disability, and these pages should be ready next week for SME and style guide updates.

**Comment by mnorthuis** [comment]
I'm going to convert this issue to an epic.  There are a lot of moving pieces to keep track of here.  I will document final IA in one issue.  We can discuss how we want the other tickets broken out to accomplish all the items listed in the acceptance criteria above.  I feel like that will work better than passing a single ticket back and forth between people.

**Comment by mnorthuis** [comment]
@Karak888 I think  you can use my acceptance criteria as a guide on what needs to be done. I'm not sure if you want to group those by role on the team or some other way though.  If you want to set up time to talk through, feel free to!

**Comment by Karak888** [comment]
will do, thanks @mnorthuis !

**Comment by mnorthuis** [comment]
@Karak888 you can reference issue #1729 for detailed notes on the changes.

**Comment by Karak888** [comment]
@mnorthuis-  @Karak888 updating menu and nav links in drupal - kara create new tasks / tickets for the remaining acceptance criteria - 

@Karak888

**Comment by Karak888** [comment]
currently have DIC page in burials benefits hub and needs to be moved to disaibility hub.  All associated tasks that need to be done before moving DIC to burials. @AnneHurley is going to check with Mikki and @RLHecht.  after Drupal go live or before?

**Comment by jenniferlee-dsva** [comment]
Uploading for @AnneHurley - to touch base with Mikki on open questions. [https://app.zenhub.com/files/133843125/64892f59-bd66-48ec-85c1-def464022fba/download](https://app.zenhub.com/files/133843125/64892f59-bd66-48ec-85c1-def464022fba/download)

**Comment by jenniferlee-dsva** [comment]
@Randi - please see word doc attached above.

**Comment by Karak888** [comment]
@RLHecht will update in Drupal and work with Nick/ @kelsonic

**Comment by RLHecht** [comment]
@mnorthuis Trying to get my ducks in a row with this issue. The three pages that need to move from Burials to Disability, two of them don't lie in Drupal yet: /survivor-dic-rates and /parent-dic-rates. They are in burials in Github but with no text. Do these pages need to be written before any of the other work with them happen?

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - to clarify: /survivor-dic-rates and /parent-dic-rates links in the Burials nav point to legacy URLs.

**Comment by mnorthuis** [comment]
@RLHecht @jenniferlee-dsva The ticket for the rewriting effort for those pages is here:  https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1832

**Comment by RLHecht** [comment]
@mnorthuis Not sure the ticket mentioned above is the right one for the rewriting effort.

**Comment by mnorthuis** [comment]
@RLHecht sorry!  Corrected link above...I left off the last digit of the issue #.

**Comment by Karak888** [comment]
need to wait until @ncksllvn and @kelsonic are back for redirect work.

**Comment by jenniferlee-dsva** [comment]
Separating out the DIC RATES rewrite and migration into drupal, so the move to Disability can move forward without new rates pages. DIC rates ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3040

**Comment by Karak888** [comment]
redirect part is last part of ticket and needs  @ncksllvn when gets back.

**Comment by ncksllvn** [comment]
Is the summary here that we need to implement the redirects as described [here](/disability/dependency-indemnity-compensation/)?

FYI we have a few domains mentioned there - www.va.gov, www.vets.gov, and benefits.va.gov.

**Comment by ncksllvn** [comment]
Ah, and we also need to actually move the pages to their new destination, as described [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1729#issuecomment-530843089).

**Comment by RLHecht** [comment]
@ncksllvn I can move the pages to the new destination but need you guys to help with the redirects and I think it all needs to happen at the same time. I was told with Drupal that we can't play around with the menu items until we are going to publish so I need to wait till everything is ready to be worked on at the same time.

**Comment by ncksllvn** [comment]
Hm, okay. I'll get some work ready to implement these redirects, then we can plan on launching all of this on Monday?

**Comment by jenniferlee-dsva** [comment]
@RLHecht - before the DIC page gets redirected from Burials to Disability, we need to give Angie Smith heads up. Since we're late into the week, let's launch on Wednseday to give her a chance to share with her manager first. Can you give me the new Disability hub URL and the Burials URL that we're redirecting from? 
(CC @ncksllvn )

**Comment by jenniferlee-dsva** [comment]
@RLHecht - I see it - is it this one page?

CURRENT: /burials-memorials/dependency-indemnity-compensation/ 

NEW:  /disability/dependency-indemnity-compensation/

**Comment by RLHecht** [comment]
@jenniferlee-dsva The two legacy rates pages would need to move out of the "More resources" section of the left nav in Burials and go into Disability, correct? Until we turn them into the new pages we've been working on.

**Comment by jenniferlee-dsva** [comment]
^ @RLHecht - yes, the 2 rates nav links are staying legacy pages for now, and just moving link location to Disabiity. (Not sure exactly where in Disability, so pls confirm with Anne/Mikki.)

Then, when the rates pages are rewritten, we can replace those links pointing to legacy pages with our new Drupal pages (plus redirect/retire). 

+ @AnneHurley - Can we discuss in today's weekly sync and make sure it's all coordinated and communicated with stakeholder?

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  @RLHecht  Yes I'm happy to communicate with Angie and other SMEs - I just need a quick debrief from one of you summarizing what she needs to know. Happy to proceed.

**Comment by ncksllvn** [comment]
Not to disrupt the conversation, but for reference, I have two pull requests open to implement the redirects outlined in https://github.com/department-of-veterans-affairs/va.gov-team/issues/1729#issuecomment-530844035.

- Vets.gov and www.VA.gov redirects (server-side) - https://github.com/department-of-veterans-affairs/vets-website/pull/11122
- benefits.va.gov (client-side, due to origin domain not being www) - https://github.com/department-of-veterans-affairs/devops/pull/5937

Should we plan on doing these Wednesday before 2 PM ET so that it all goes in the daily deployment?

**Comment by jenniferlee-dsva** [comment]
Thanks @AnneHurley - the essential points for Angie would be... everything Angie might need to know to share with her management: 

- Page name:
- Current URL inside the Burials hub:
- New URL inside the Disability hub:
- With a note that we will redirect the ^ Burials URL to the new Disability location + where else we are adding links pointing to the DIC page -- if we're adding for example on the Disability hub page, etc.) 
- Plus when all this will happen -- looks like Wednesday ETA per Nick's message above. 

Can you also please re-confirm here for everyone before Wednesday morning ET if for whatever reason Angie says to hold? (So we don't merge/deploy this if so.)

**Comment by RLHecht** [comment]
Here is a list of all pages where we need to change the DIC page link once we move the DIC page to disability. @jenniferlee-dsva If these were linked with the node ID in Drupal instead of the URL /burials-memorials/dependency-indemnity-compensation, does that mean they update to the new hub automatically? If so, I can go in to all of these and check that's how they are linked so we don't have to manually update each one later one.

[ ] https://www.va.gov/burials-memorials/eligibility/ (in related links)
[ ] https://www.va.gov/burials-memorials/plan-a-burial/ (in related links)
[ ] https://www.va.gov/burials-memorials/bereavement-counseling/ (in related links)
[ ] https://www.va.gov/burials-memorials/ (in the "Get Veterans burial benefits" section)
[ ] https://www.va.gov/burials-memorials/ (both rates pages linked to in More information and resources section)
[ ] https://www.va.gov/disability/ (in the "Get VA disability compensation (pay)" section)
[ ] https://www.va.gov/family-member-benefits/ (in "Benefits for spouses, dependents, and survivors" section)

**Comment by RLHecht** [comment]
@ncksllvn We are now planning to do this work for Friday 11.22 deployment (not 11/20) to give stakeholders enough time to review. Thanks!

**Comment by AnneHurley** [comment]
@mnorthuis @RLHecht @ncksllvn  - Question re the deploy date of 11/22 - has this list of URLs been sent to the SMEs, and who's shepherding it?

**Comment by jenniferlee-dsva** [comment]
@AnneHurley re your Q - the list of URLs in Randi's above message are not being redirected. (At least in this ticket.)

**Comment by RLHecht** [comment]
@AnneHurley Right. That's just a list of all the places the DIC page is mentioned on other pages, so we need to make sure when the page gets moved to disability that those links get updated to point to disability/dependency-indemnity-compensation instead of burials-memorials/dependency-indemnity-compensation. Not sure that needs to be shared with SMEs. It's just a way for us to keep track of the pages.

**Comment by jenniferlee-dsva** [comment]
Also - just remembered - in Drupal, if we were already using the node Ids, instead of the literal URLs, those text links should automagically point to the new location. (I think.)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I think that is the case too but will confirm with Kevin. I will also check all these pages to make sure the Node ID was actually used.

**Comment by RLHecht** [comment]
@Karak888 Should this move to icebox until the bug is fixed? Or leave here with a note that we are waiting on the fix before moving ahead with this ticket?

**Comment by RLHecht** [comment]
Drupal bug fixed so this can move forward. @jenniferlee-dsva and @ncksllvn Could we do this by Friday 12/6? Nick, when you do the redirect work I need to do the Drupal changes so that it all goes live at the same time. Mikki is good with the redirects. @AnneHurley would need to let the stakeholders know this is finally happening.

**Comment by jenniferlee-dsva** [comment]
@RLHecht @AnneHurley -  yes, please move forward but with 1 caveat: We committed to 7 business days advance notice to the VBA digital team, so we can communicate this now and give them the date 7 bus days out when the client side redirect happens. (Per this message from Nick: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1727#issuecomment-555132029 )

So here's how I think it needs to happen - this is a weird one because there are 2 redirects happening - one internally (within Drupal) and one externally (from benefit.va.gov to new Drupal page). 

1/ Move the Burials page to Disability; implement the INTERNAL redirect. Anne to communicate to Angie (please CC me, Misty, Adrianne, and Sandy, and Selina). This can happen immediately, since Angie has been waiting on this FOREVER. (LOL)

2/ Selina - please communicate to Misty and team (CC Angie, me, and Anne) about the client side redirect (see Nick's linked comment), using our template email and process, with the 7 days notice. 

If there's any confusion, please explain the first redirect is internal (moving it from Burials to Disability) and the second is to retire the legacy source URL. Because I'm still loopy with sick, @ncksllvn - can you validate this sounds right?

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  Will send out that email shortly.

**Comment by ncksllvn** [comment]
I have a pull request ready that implements the client-side redirects and another that implements server-side. Assuming that nothing has changed since the original planned launch date of 11/22, they should still be good to go.

**Comment by RLHecht** [comment]
@ncksllvn  There are two legacy pages under More Resources in the burials that need to move to more Resources in disability when the main DIC page moves: https://www.benefits.va.gov/Pension/current_rates_Parents_DIC_pen.asp and https://www.benefits.va.gov/Compensation/current_rates_dic.asp

Are these part of that PR?

**Comment by AnneHurley** [comment]
@mnorthuis @RLHecht @lunascoop - There are so many moving pieces in this ticket - @mnorthuis - could you help me and Randi figure out what-all we need to do at this point? I want to make sure we capture all the missing pieces (I believe I will be writing blurbs to link to the new pages, for example), matching DIC rates here and elsewhere. It'd help me so much if we could get a final checklist of the last things to do, and who needs to do them. Can we? thanks much.

**Comment by Karak888** [comment]
@RLHecht will look into legacy pages and coordinate at same time she moves the DIC under disability hub. @AnneHurley will reach out to SMEs to let them know we are doing them at the same time.

**Comment by lunascoop** [comment]
@ncksllvn @Karak888 The redirect notification was sent to the stakeholders with **12/11** as the scheduled live date.

**Comment by ncksllvn** [comment]
@lunascoop does the redirect notification sent to stakeholders refer to the redirects on benefits.va.gov?

**Comment by lunascoop** [comment]
@ncksllvn Yes, I included the benefits.va.gov redirects in my notification. Specifically, here's what I wrote:
<img width="750" alt="Screen Shot 2019-12-05 at 10 24 21 AM" src="https://user-images.githubusercontent.com/42546515/70248842-8a62be80-1749-11ea-87de-d980989b5c47.png">

**Comment by ncksllvn** [comment]
Dang it, this is confusing. Per [Kara's comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1727#issuecomment-561777002), I think we're planning on moving the pages in Drupal and doing the www redirects tomorrow as a phase 1, then doing the redirects from benefits.va.gov as a phase 2. Is that still right?

**Comment by lunascoop** [comment]
Per our slack call @RLHecht and @ncksllvn will move forward w/ the internal redirect tomorrow, 12/5, and implement the client-side redirect on 12/11.

**Comment by Karak888** [comment]
@ncksllvn your comment above is correct.  @RLHecht will be moving the pages in Drupal and working with you to handle the www redirects tomorrow as a phase 1 (12/5/19),.  Phase 2 will be redirecting  benefits.va.gov by 12/11/19 (per communication email that @lunascoop send out to SMEs). 

CC:  @jenniferlee-dsva

**Comment by RLHecht** [comment]
@mnorthuis I've moved the main DIC page and those two rates pages to Disability. Here is a screenshot of where they lie in the left nav. Please tell me if this is not correct. It won't be live on the site until after today's Drupal deployment in the afternoon. This is just in Preview on Prod at the moment. FYSA @jenniferlee-dsva 

![Screen Shot 2019-12-06 at 9.42.10 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/853ead20-c230-486e-b15d-86f9c468b82d)![Screen Shot 2019-12-06 at 9.43.29 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/d1b4668b-a296-43c5-83c0-dc59ad6f396c)

**Comment by ncksllvn** [comment]
Drupal work and server-side redirect is out - https://www.va.gov/burials-memorials/dependency-indemnity-compensation/

**Comment by ncksllvn** [comment]
I believe this just leaves the redirects on benefits.va.gov as the outstanding item on this ticket.

**Comment by RLHecht** [comment]
@AnneHurley Just a reminder, we still need the blurbs on the two pages mentioned at the top of this ticket.

**Comment by ncksllvn** [comment]
Are the redirects from benefits.va.gov included on this ticket too? I see `Old DIC page URLs are redirected to their new locations` but I figured that was only the www.va.gov redirects.

**Comment by mnorthuis** [comment]
All redirects for this work (both in drupal and client side/legacy page redirects) are documented in issue #3809.

**Comment by mnorthuis** [comment]
@RLHecht The 2 rates links in the left nav should be placed after the compensation rates option.  I also do not see the links on the Disability hub page?

**Comment by AnneHurley** [comment]
@mnorthuis @Karak888 @RLHecht 
Picked up from #3040:
Here's the page:
https://www.va.gov/disability/dependency-indemnity-compensation/

Right now we have links under More Resources in left nav to what the current rates are for spouses and for children and parents. But couldn't we rewrite that section in the middle of the page and add those links in the body of the page? I'd be looking for it on this page if I were interested in this topic.

Note to Randi - I'll defer to you about how best to set up the two links under that blurb. I thought we could list two links like the below but I may be misremembering.


Suggest:

H2: What kind of benefits can I get?
Body copy: If you qualify, you can get tax-free monetary benefits. The amount you receive depends on the type of survivor you are.
DIC benefit rates for surviving spouses and children
[[https://www.benefits.va.gov/Compensation/current_rates_dic.asp]]
DIC benefits for surviving parents
[[https://www.benefits.va.gov/Pension/current_rates_Parents_DIC_pen.asp]]

**Comment by RLHecht** [comment]
@jenniferlee-dsva I've added Anne's related links text to both the DIC page and the Survivors Pension page. Also on the main DIC page, I added the links to the two legacy rates pages under the "What kind of benefits can I get?" section. Can you please review both pages and publish if they look good? That should complete the work for this ticket. The Drupal links are:

preview-prod.vfs.va.gov/preview?nodeId=590
preview-prod.vfs.va.gov/preview?nodeId=855

**Comment by ncksllvn** [comment]
I believe we have met all of the acceptance criteria for this ticket. Can we close it?

**Comment by lunascoop** [comment]
@mnorthuis @ncksllvn  @Karak888 @jenniferlee-dsva, I have validated that the redirects have gone live and will notify the stakeholders, close this ticket and update my communication log.

**Comment by RLHecht** [comment]
@lunascoop we still need @jenniferlee-dsva  to approve text that was added to two pages on here. See my comment above.
