### ISSUE TITLE
Update 5103 approach on 'Evidence needed' pg

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#1728]
## User Story
As a VBA stakeholder, I need to refer Veterans to specific source legal content about evidence requirements.

@RLHecht - On this page: https://www.va.gov/disability/how-to-file-claim/evidence-needed/

1.	Pull the source PDF link / https://www.vba.va.gov/pubs/forms/VBA-21-526ez-ARE.pdf /  to the top of the “What should the evidence show to support my disability claim?” section, so we can ensure all users read it before moving on to reading through the accordions.  The PDF link is at the bottom of accordions: "View the evidence requirements listed on the 21-526EZ paper form for disability claims (PDF)"

2.	Update the intro verbiage at the top of that accordion section like this. 

## Updated text:

**Notice to Veterans and service members of evidence needed:** We’re required by law to tell you what evidence you’ll need to provide to support your disability claim. 

For your convenience, the information below is a summary of evidence requirements (called “section 5103 notice”). You can view the [official evidence requirements in VA Form 21-526EZ (PDF)](https://www.vba.va.gov/pubs/forms/VBA-21-526ez-ARE.pdf)."

## Screenshot - where updated text goes:
![image](https://user-images.githubusercontent.com/43381063/64750853-495f6300-d4e8-11e9-819f-cea7dbadc1a6.png)

## Screenshot - delete/move up this PDF link to above ^:

![image](https://user-images.githubusercontent.com/43381063/65046964-918ae500-d92f-11e9-82a8-1166256eb9ad.png)

##How to configure this issue
- [x ] **Attached to a Milestone** (when will this be completed?) [This issue needs to be made post CMS UAT freeze, associated with this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1020 ]
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
This legal text refinement was supposed to go out this week via Drupal -- based on original schedule of hub coming out of UAT this week.  But now that it's going to be another 2 weeks of UAT for Disability hub, this text should go live via Github this week. 

Note - this update will ALSO need to be made post-UAT freeze in Drupal: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1020#event-2562405819

FYSA @Karak888 @peggygannon

**Comment by RLHecht** [comment]
@jenniferlee-dsva These changes have been made in this PR: https://github.com/department-of-veterans-affairs/vagov-content/pull/557
FYI @Karak888 @peggygannon

**Comment by RLHecht** [comment]
@jenniferlee-dsva added you as a reviewer to the PR, which is in the above comment.

**Comment by Karak888** [comment]
@Karak888 to get Jen answer as to how we close this but maintain tracking.

**Comment by RLHecht** [comment]
@jenniferlee-dsva  I made the above change in Drupal. @peggygannon can you please review?
