### ISSUE TITLE
[BE] modify Ch33BankAccountsController#index method to also return bank name

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#17294]
> http://linktestbepbenefits.vba.va.gov/DdeftWebServiceBean/DdeftWebService
> The findBankNameByRoutngTrnsitNbr operation returns the bankName for the routngTrnsitNbr

use the `findBankNameByRoutngTrnsitNbr` api to return bank name in `Ch33BankAccountsController#index` api

**Comment by Samara-Strauss** [comment]
I put this down for the sprint starting 12/30 after you get back from break.
