### ISSUE TITLE
Common Component: Appeal Step Table

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17296]
## Acceptance Criteria
1. Create common component for the Appeal Step Table that meets the following specs: 
2. **Overall list**
      - Margin: no gutter L/R; marginBetween above and below component
3. **Accordion**
     - Common Component: Additional info
     - Internal padding: 20px total
4. **Rows**
      - Background color: white #ffffff
      - Margin: 0px between rows
      - Internal padding: 20px total; 10px between icon and text
      - Border-bottom: 1px solid gray-light #aeb0b5
      - Headline text: Mobile Body Bold
      - Body text: Mobile Body
      - Icon: Background-color: green-darker #195c2; Border: 1px solid green-darker #195c27; Icon: fa-white-check; Icon-color: white #fffff

## Designs
https://adhoc.invisionapp.com/d/main/#/console/20546460/438003926/inspect
![Screen Shot 2020-12-10 at 12.39.53 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/01e9204e-4903-47b1-b739-56cdd84d5570)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Testing...
