### ISSUE TITLE
Common component: Claim Step Table

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17295]
## Acceptance Criteria
1. Create common component for the Claim Step Table that meets the following specs: 
2. **Overall list**
      - Margin: no gutter L/R; marginBetween above and below component
3. **Rows**
     - Background color: white #ffffff
     - Margin: 0px between rows
     - Internal padding: 20px total; 10px between icon and text
     - Border-bottom: 1px solid gray-light #aeb0b5
     - Headline text: Mobile Body Bold
     - Body text: Mobile Body
     - Icon (left): Variable
     - Icon (right): fa-chevron-down and fa-chevron-up, #212121; 16px
     - Button: Large Button, display variable
     - Button header: Mobile Body Bold, display variable
4. Step icons (3 options):
     - **Past Step**
          - Background-color: green-darker #195c27
          - Border: 1px solid green-darker #195c27
          - Icon: fa-white-check
          - Text color: white #ffffff
     - **Active Step**
          - Background-color: primary #0071bb
          - Border: 1px solid primary-darker #003e73
          - Text: Bitter Bold
          - Text color: white #ffffff
     -  **Future Step**
          - Background-color: gray-light #aeb0b5
          - Border: 1px solid gray-light #aeb0b5
          - Text: Bitter Bold
          - Text color: white #ffffff
5. Add specs to ReadMe

## Designs
https://adhoc.invisionapp.com/d/main/#/console/20546460/440039998/inspect
![Screen Shot 2020-12-10 at 12.41.37 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/de83ae48-49c5-403c-b37e-2ba2d01e663b)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Passing with a minor capitalization bug. 12/18/2020 Moving to Design QA.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17763
