### ISSUE TITLE
VFS Support: Complete IA work for moving DIC to Disability hub

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#1729]
**See epic for user story, goal and acceptance criteria. **

This issue documents the IA/navigational changes required. 

## IA Tasks:
- [x] Identify all pages impacted by this change
- [x] Define IA and document changes in Site Map
- [x] Define navigation and crosslinking changes and document 
- [x] Identify and document redirects needed and document in Master URL Mapping

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
IA work complete and this issue is referenced in the epic so team members can see details of work.  

@Karak888 is it ok to close this issue?

**Comment by Karak888** [comment]
um, yes please!!! and I'll close on my end now!

**Comment by Karak888** [comment]
@RLHecht here are the list of URLs
