### ISSUE TITLE
Stop recording address validation errors in Sentry when we no longer need it

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#17315]
On Thursday, December 10, 2020 we merged [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15259) that started logging additional error data to Sentry so that we could determine _why_ we could not properly parse the errors and report accurate data to GA.

Once we start seeing this new data in Sentry we should be able to better handle those errors and remove the additional Sentry logging that was added.

We should be able to search for new errors in production [in Sentry](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&groupStatsPeriod=14d&project=4&query=is%3Aunresolved+%2Fpersonal-information+source%3Aprofile&statsPeriod=14d) by searching for something like `is:unresolved /personal-information` and/or `is:unresolved source:profile`

Hopefully Sentry will help us identify the shape of the error and where it is coming from at which point we can write another ticket to fix the problem.

- [This is the GA Dashboard](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/_u.date00=20201205&_u.date01=20201208/) that is showing `undefined_undefined-address-suggestion-failure` errors we are trying to better diagnose.

**Comment by erikphansen** [comment]
I just dug into Sentry and see no evidence of our logging actually happening, despite the fact that we have seen a few dozen instances of `undefined_undefined-address-suggestion-failure` showing up in Google Analytics. This might have to do with me not knowing how to use Sentry :-/

**Comment by sanlouise** [comment]
Closing, ticket is done and no more validation should be needed.
