### ISSUE TITLE
Facilities COVID-19 vaccine support

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17321]
## Product Outline
This issue to house all COVID-support related issues pertaining to the Facility Locator and VAMC front end

## High Level User Story/ies
As a Veteran, I need to find a facility with COVID-19 vaccine services so I can be vaccinated
#

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jilladams** [comment]
One remaining issue here re: cypress test has also been tagged into the epic re: unrolling COVID for more consideration. Closing this epic.
