### ISSUE TITLE
[Ongoing Service] Testing Tools - Maintain Stable Versions

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#17332]
## User Story
As a VFS/VSP developer, I want to ensure that I'm using the latest features and most stable versions of the tools that we use on the platform.

## Artifacts
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md))
- Link to product README ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md))

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by pjhill** [comment]
These upgrades were completed. I expect we will be handling version upgrades differently in the future.
