### ISSUE TITLE
Text content for appointment reminder notifications

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17331]
## User Story
As a user, I can get notifications from VA that tell me I have an appointment coming up soon.

## Tasks
- [ ] Determine content for appointment reminder push notifications

**Comment by ayushchak** [comment]
[] What is allowed? PII Concerns
[] Push notifications - insert prescription here; click here to refill (Ayush to add pharmacy examples from Capsule)

**Comment by bridgethapner** [comment]
I updated this ticket to be just for Appointment Reminder notifications (will we have other notification types at app stores launch?)

**Comment by msmanak** [comment]
"title": "VA Appointment Reminder",
"body": "You have an upcoming VA appointment."

@lexicalninja what's the system response for multi-appointments?

My interpretation is cluster messages that is offered by OS

**Comment by lexicalninja** [comment]
If you mean one notification with multiple appts, we don't send that message so it wouldn't happen.
If you mean multiple notifications for different appts, that is up to the OS to display them on the lock screen/notification tray. It won't change the message content at all.
