### ISSUE TITLE
Security Review AI's before Direct Deposit Launch - Sentry Field Names

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1733]
Sentry field names: everything needs to be sanitized

Looks like only account_number is currently sanitized

Link to the the vets.gov repo - [19647] (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19647)

**Comment by Justin-Pickett** [comment]
@lihan, can you notate the feedback you are waiting to receive from VSP in this ticket just for visibility. Thank you.

**Comment by lihanli** [comment]
waiting on pr review here https://github.com/department-of-veterans-affairs/vets-api/pull/3304
