### ISSUE TITLE
Remove `#to_pdf` stubs in integration test for Form1010cg::DeliverPdfToCARMAJob spec

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#17335]
Original PR: department-of-veterans-affairs/vets-api#5465

**Description**
The `Form1010cg::DeliverPdfToCARMAJob` has an integration test to ensure that all the pieces work together to deliver the attachment to CARMA. In this spec we stub `#to_pdf` because the cassette has a file contents of the string `<PDF_CONTENTS>` base64 encoded.

This is a problem since we do not get a full test of adding the job to the queue, generating the PDF, delivering it, and deleting the related resources.

**Risk**
If changes were made to the PDF generation process, or how it's attached to the request to CARMA, we could potentially not have a failing test signifying that the bug was introduced.

**Accept Criteria**
Remove the `#to_pdf` stub in order to have a full, top-to-bottom, integration test.

**Comment by hdjustice** [comment]
Closing - This ticket has not been addressed in over a year, and there are no initiatives linked.  Any new work will have new tickets created.
