### ISSUE TITLE
Add specs for CARMA::Models::Attachments#submit encountering a 400-500 responses

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#17334]
Original PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5465

**Description**
Add test cases for when CARMA responds with 400-500 errors in order to document cases and handle them.

**Comment by hdjustice** [comment]
a PR ticket was merged over a year ago including this work.  if any new work is needed, a new ticket can be created.
