### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#17343]
# Request Google Analytics and/or Domo access

## What this form is for
I'd like to request access to google analytics to do some quant research on dropoffs for the online 526 form 🙇 

## User Email Address
[Link to DSVA Slack channel thread](https://dsva.slack.com/channels/vfs-platform-support)
Email: josh.kim@adhocteam.us

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics

## Date Required
Ideally as soon as possible, or by Friday December 18th.

## Product Team / External Team / VA Office
Shared Resource on VSA

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bmcgrady-ep** [comment]
@joshkimux - I just granted you Google Analytics access. You should be receiving an email with a Google Analytics invitation. Let me know if you have any issues getting into Google Analytics.

**Comment by bmcgrady-ep** [comment]
Closing this ticket as access has been given.
