### ISSUE TITLE
Security Review AI's before launch - Filtering data from other (non-Sentry) logging

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1734]
Confirm we're filtering same data from other (non-Sentry) logging

Should be OK because whitelist, but please confirm

Link to the the vets.gov repo - [19647] (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19647)

**Comment by lihanli** [comment]
confirmed https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19647#issuecomment-530178568
