### ISSUE TITLE
Access for Emily Wu

### ISSUE THREAD

**Issue by emilywu-tw** [department-of-veterans-affairs/va.gov-team#17355]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea
- Please provide your name.
   > Emily Wu
- Please Provide your email.
   > ewu@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @department-of-veterans-affairs/thoughtworks 
   > Role: Developer
   > Company: ThoughtWorks
   > I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana / Sentry so we can
   >   - Modify / update Jenkins job configs
   >   - Kick off Jenkins jobs
   >   - Review Prometheus data, some of which is imported into the scorecard
   >   - Review Grafana data for the scorecard
   >   - Review logs in different environments to facilitate testing along the path to production

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrdqNDeSUtrzk3wK8WgazMgcVbK/N1Vh3Q7bD8pPJbPVBYzUd/MVQq+0N9GopSNbnZSTsm7q0wP3nxzeCvodFrIrb0Hk1W9K/B9pmBuUkX9jn/N7LnSYuv9gZweicHse+rHjap/tJIis81ZLlO6jga4CQGp6doUtY9LLjLQ41yMDLp8c/S4HbRclIyu/B2JQxHt+YIYfqXZFfOijDxFEPFw95n2ma/GizWx5BFGeAz9JBilxexMM0fZD/Lvyw5Hue9VuivrVz1bAL6XNvKJkHGTwrFYczn0NbNpYza53q8MWSkU4geVZBjLpHxy2oeXjuqRGXDQwPwUjnOEoS2mK7jJXh7BrFT3DyM/dfxBnglin27TfyUZv48GwB+LREvoaH16wjK2Cp+Z+pmXdKk/Rsg966nG8/AP0nAzeUQxHBYgFfKjxh56SK1THYB8MPgrs2w3/mmwtX6b184ne5jJpodc3hs5D/kDN7Zi8CJruExdeol3EGkxtnaI83NdAVDhzM= ewu@EmilyWuComputer
```

- Grant AWS Console access?
  > NO

**Comment by emilywu-tw** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@emilywu-tw you sould now have access to the socks proxy. Reach out in slack if you have any issues connecting.
