### ISSUE TITLE
Analytics Implementation or QA Support for COVID-19 vaccines content mini-hub page

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17350]
# Google Analytics Implementation or QA Request

## What this form is for

Google Analytics, Domo dashboard tracking for COVID-19 vaccine mini-hub page

- url: https://www.va.gov/health-care/covid-19-vaccine/
- main vanity url: http://va.gov/covid-19-vaccine
- other vanity urls: http://va.gov/covid-vaccine, http://va.gov/coronavirus-vaccine 

<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

GA implementation

- Who is this request for?

    - @DanielleThierryUSDSVA @lalexanderson-dsva @batemapf 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?

     - COVID-19 team (Public websites, OCTO Health)
    
- Provide the Domain where Google Analytics needs to be implemented

- url: https://www.va.gov/health-care/covid-19-vaccine/
- main vanity url: http://va.gov/covid-19-vaccine
- other vanity urls: http://va.gov/covid-vaccine, http://va.gov/coronavirus-vaccine 
    
no
    
- Please provide any upcoming deadlines or important milestones

    asap

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* 
    
    - http://va.gov/ (homepage banner when updated with link to vaccine content page)
    - https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ (question/link on FAQs page to vaccine content page)
    -  Sitewide (non-homepage) banners (ex. at https://www.va.gov/disability/)
    - Links from promos in health care hub mega menu and benefit hub page
   - Links from VAMC sites
   - Incoming links from other sources (social media, etc.)
   - Links from best bets
    
    - *Other User Interactions*: 
    
    - Clicks on form sign up from alert (once published) to va.gov/health-care/covid-19-vaccine/stay-informed/
    - Clicks on links within page
    - Interactions with accordions on page
    
- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@joanneesteban -

A quick run-through of the available metrics:

<table>
  <tr>
   <td>http://va.gov/ (homepage banner when updated with link to vaccine content page)
   </td>
   <td>This would be a `nav-warning-alert-box-content-link-click` event.  We would need to double check it is firing correct on the new link.
<p>
Ready to test this on staging?
   </td>
  </tr>
  <tr>
   <td>https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ (question/link on FAQs page to vaccine content page)
   </td>
   <td>If you just want to see all traffic from this page to the vaccine page, we should be able to look at the Previous Page Path of the vaccine page.
<p>
Individual (internal) links would be in something like:

> eventCategory: "Interactions", 
eventAction: "Navigation - COVID - send your VA provider a secure message - https://www.va.gov/health-care/secure-messaging", 
eventLabel: "nav-covid-link-click"

   </td>
  </tr>
  <tr>
   <td>Sitewide (non-homepage) banners (ex. at https://www.va.gov/disability/)
   </td>
   <td>Not seeing individual event tracking on these links.
<p>
They  would use a `nav-warning-alert-box-content-link-click` event. though a developer would need to add that.
<p>
We could also use the Previous Page Path for this one, though that may be difficult if this is site-wide.
   </td>
  </tr>
  <tr>
   <td>Links from promos in health care hub mega menu and benefit hub page
   </td>
   <td>Just to double check, what are the URLs for these?
   </td>
  </tr>
  <tr>
   <td>Links from VAMC sites
   </td>
   <td>This should be available in Previous Page Path (or maybe Full Referrer)
   </td>
  </tr>
  <tr>
   <td>Incoming links from other sources (social media, etc.)
   </td>
   <td>This should be available in Full Referrer, Social Reports, source/medium reports.
   </td>
  </tr>
  <tr>
   <td>Links from best bets
   </td>
   <td>What are "best bets" in this context?
   </td>
  </tr>
  <tr>
   <td>Clicks on form sign up from alert (once published) to va.gov/health-care/covid-19-vaccine/stay-informed/
   </td>
   <td>Is this VEText / VANotify?
   </td>
  </tr>
  <tr>
   <td>Clicks on links within page
   </td>
   <td>Outbound links (like to cdc.gov) are good to go.
<p>
Jump links / Table of contents links are in:

eventCategory: "Interactions", 
eventAction: "Navigation - Jumplink Click - More helpful information and resources", eventLabel: "nav-jumplink-click"
<p>
<em>Operation Warp Speed</em> is an Outbound Download, which is tracked.
<p>
<em>More helpful information and resources</em> at the bottom are in events like: 

> eventCategory: "Interactions", eventAction: "Navigation - Link List - More helpful information and resources - Coronavirus FAQs: What Veterans need to know", 
eventLabel: "nav-linkslist"

Any other internal links on the page I'm missing?
   </td>
  </tr>
  <tr>
   <td>Interactions with accordions on page
   </td>
   <td>Those are tracked in events like:

> eventCategory: "Interactions", 
eventAction: "Navigation - Accordion - Expand - If I get the COVID-19 vaccine, can I stop wearing a mask in VA facilities?", eventLabel: "nav-accordion-expand"
   </td>
  </tr>
  <tr>
   <td>
   </td>
   <td>
   </td>
  </tr>
</table>

**Comment by joanneesteban** [comment]
Thank you for the rundown, @bsmartin-ep ! @DanielleThierryUSDSVA - would you be able to take a look at Brian's comment above and let us know if you need anything else tracked? (The accordion clicks should give us information on which Q&As are being read the most.) Otherwise, we can go ahead and close out this ticket. Thanks!

**Comment by joanneesteban** [comment]
@DanielleThierryUSDSVA if you have additional metrics you would like tracked for this page, please let us know! Closing this ticket.
