### ISSUE TITLE
[Analytics] Show unique events alongside total events for address save errors

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#17367]
## Background

On our [address validation dashboard](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/) the errors chart only shows total events:

<img width="1280" alt="Screen Shot 2020-12-11 at 2 46 04 PM" src="https://user-images.githubusercontent.com/34068740/101950173-d3521c00-3bc2-11eb-9379-6cf06397c1b7.png">

As you can see, we're receiving a very high amount of address save errors. **However**, when you look at the [contact information dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/3Z1vT6SlQqevdav1s72QwA/a50123418w177519031p176188361/), you can see the total events are drastically different than the unique events for save errors. 

I would love to be able to see the ratio of total vs. unique errors on the [address validation dashboard](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/) so that we have a better sense of for how any people (roughly) these errors are effecting. My hypothesis is that there is a small group of people who are trying to save the address form multiple times, and that is why we are seeing such a high error count.

## Tasks

- [x] Acknowledge receipt and let Samara know when you might be able to get to this.
- [ ] Add unique events alongside total events for the total address save failures chart.

**Comment by Samara-Strauss** [comment]
@bmcgrady-ep I think you can handle this without a frontend dev, but let me know if we need to bring in Sandra or Erik for any reason.

cc/ @mshea0606 for awareness that this ticket was created.

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - Acknowledging receipt. I'll be working on this ticket this week, so you should be hearing from me shortly.

**Comment by Samara-Strauss** [comment]
Great, thank you!

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - The Address Validation has been updated to include the unique events for the address errors. Let me know if you need anything else!

**Comment by Samara-Strauss** [comment]
Thank you! Looks good. This is hugely helpful.

**Comment by mshea0606** [comment]
Thanks @bmcgrady-ep, this is great !
