### ISSUE TITLE
STEM: Notify applicant when contacting SCO

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#17363]
As an STEM applicant, I need to be notified when the SCO is being contacted in support of processing the application so that the application is compliant with regulations.

## Assumptions:
1. This work is completed behind a feature flag as outlined in AC1.

## Acceptance Criteria
1. This story is completed behind feature flag `stem_applicant_email` and production flag.
2. The following content is displayed, in Chapter 3,  at the bottom of the "Your school ID and contact details" section (see SA2):
    > We'll be reaching out to the School Certifying Official (SCO) at this school to confirm your eligibility for the scholarship.
  a. This is behind a production flag
3. On submission, when an email is sent to the SCO, the applicant is sent an email populated using the template in SA3.
  a. This is behind the feature flag `stem_applicant_email`
  b. a preview version is available at http://localhost:3000/rails/mailers that either uses fake data or most recent 10203 submission

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/9c33414b19cdc387b49f9b1e2f455f456a8530ca/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md#form-title-apply-for-the-rogers-stem-scholarship-6) as of 12/11
2. 
![stem-3-school-details copy 4-B Copy](https://user-images.githubusercontent.com/48260534/101946244-bf0b2080-3bbc-11eb-9449-4cc6b1f22bce.png)

3. [Applicant Email](https://github.com/department-of-veterans-affairs/va.gov-team/files/5681098/STEM-SCO-CC-Email-20201210v2.docx)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5555

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15446

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me

**Comment by amyknox** [comment]
It looks like the alert box is too wide. Per artifact 2, it should be the same width as the text fields.  

![image](https://user-images.githubusercontent.com/41081945/102925058-b3dbae80-4460-11eb-8800-daeb1c5ccc7d.png)

**Comment by amyknox** [comment]
UX 2/2 = We're good. 

Thanks for [the additional info](https://bah-ssp.slack.com/archives/C01DEL71Q11/p1608669668148300?thread_ts=1608565880.142800&cid=C01DEL71Q11), Matt.

**Comment by delli-gatti-michael** [comment]
Closing this out

[Testrail test case](https://dsvavsp.testrail.io/index.php?/tests/view/32654&group_by=cases:section_id&group_order=asc&group_id=51)
