### ISSUE TITLE
Active Appeals detail | Details summary

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17369]
## User Story
As a user, I want to view a summary of my appeal details so I can reference what is currently on appeal. 

## Acceptance Criteria
1. On the Claims detail page, when "Details" is the selected segment, display items that are **Currently on appeal**, formatted in a bulleted list 
     - All data within this list is service-driven
2. Styling & UI match the design

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/438004285/inspect

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Appeal" as Header 1
- Mark "[Type] appeal" as Header 2

**Segmented Selector**
- accessibilityLabel="Details"
- accessibilityHint="view your appeal details" 
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 2 of 2)

**Currently on Appeal**
- Mark "currently on appeal" as Header 3
- Ensure each appeal is read together by the screen reader (ex. "service connection, post-traumatic stress-disorder" should be read together instead of as two separate items) 

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by msmanak** [comment]
Addressed this with @bessgreen but the voiceover announcement here is out of order within the data pulling from the backend. It should be listed and group into sections within each listed disability.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/11/2021 - Moving to Design QA.
