### ISSUE TITLE
Claims and Appeals (Active and Closed) - Accessibility (multiple issues)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#17362]
## What happened?
This covers Claims, both Active and Closed.

1.  Segmented selector is not speaking accessibilityHint "view your active claims and appeals". (Android)

2. "Your active claims and appeals" and "Your closed claims and appeals" texts are not being read. (Android)

3. Segmented selector is not tall enough.  Height is only 38px and minimum touchpoint size is 44px.

## Specs:
- Device: Android Motorola Moto G7 (latest OS) Talkback enabled.

## Steps to Reproduce
- Enable Talkback on phone.
- Navigate to Claims page.
- Highlight the active selector buttons so they are read by Talkback.
- Attempt to highlight and read "Your active claims and appeals" and "Your closed claims and appeals" texts.

## Desired behavior
- Segmented selector hints are read as indicated.
- "Your active claims and appeals" and "Your closed claims and appeals" texts are being read. 
- Segmented selector is 44px tall.

## Acceptance Criteria
- [x] As above in desired behavior.

## Bug Severity
- 4 - Low

## Linked Story
#16698 and #14477

## Screen shot(s) and additional information

![segmentedSelectorClaims.jpg](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/7e11eada-e582-4d64-b1fe-c417f71a3d91)

**Comment by esther-k** [comment]
**12/17**
Pass - Accessibility issues are resolved on iOS and Android
