### ISSUE TITLE
Security Review AI #2 for Direct Deposit (post launch)

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1737]
[low-pri] 

Ask EVSS: Why do we always indicate VETERAN status to EVSS?

**Comment by Justin-Pickett** [comment]
@lihanli please update this ticket with the necessary info so we can close this out.

**Comment by lihanli** [comment]
> At the present time eBenefits has only supported DS Logon authentication, so using “DSLogon” made sense. We are in the process of adding support for additional credentials (ID.me and MHV) so there will be additional options in the near future from that perspective. However, anything you send most likely has to mirror exactly what IAM would send for SSOi, since that is the target we  have been working on.
> 
>  As far as the “VETERAN” value, we support Veterans, spouses and family member dependents today, but again your usage would have to match what we get from IAM SSOi. I am adding Michael Harlow who is doing some work on this area right now who can probably provide additional details.
> 
> Currently, the EVSS APIs decide if a user is a Veteran based on several criteria, but the “VETERAN” value in the JSON header is not one of these criteria. Using the JSON header, the APIs determine a user is a Veteran when associationReason is BD or null and headOfFamily is null.
> 
>  
> 
> Some of the EVSS APIs return different data if a user is not a Veteran. For example, the letter generator API will provide a different list of letters to dependents.
> 
>  
> 
> Today I learned that MVI has a Person Type indicator that can identify Veterans and Dependents, so EVSS may be changing the way we identify users in the future.
