### ISSUE TITLE
School Ratings: Add Google Analytics to track user interaction

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#17374]
As a developer, I need to add Google Analytics tracking to the ratings functionality so that we can develop an understanding about how users are interacting with the tool.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The "See NN ratings by Veterans" link on the institution profile page triggers the following event on click:
    > 'event': `nav-jumplink-click`

## Supporting Artifacts:
1. Originating story: #16164

**Comment by elder-joseph** [comment]
Associated PR:

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/15438

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-12-21 at 12.27.11 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2dcb1db8-2b85-4d4a-9876-123b67ea3333)

**Comment by sonntag-adam** [comment]
This is now in staging. Testing passes QA
