### ISSUE TITLE
Closed Appeals detail page (UI) 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17373]
## User Story
As a user, I want to view my closed appeal details. 

## Acceptance Criteria
1. The Closed Appeal detail page should display the following elements that already exist on the Active Appeals detail page:
     - Appeal header with segmented selector
     - View past events accordion with Appeals Step CC 
     - Current status UI (with modifications detailed in AC #3) 
     - Need help UI
     - Details summary (when Details is chosen from the Segmented Selector)
2. The following elements that are displayed in Active Appeals detail should be **hidden** from the Closed Appeal detail page:
     - Appeals ahead of you
3. Current status section:
     - May contain a combination of hard-coded & service-driven data.* (see dev note below)
4. When there is > 1 issue listed, update the copy to the following so it reflect plural items: "The [judge/reviewer] granted the following issues"

**Notes for dev**
-  Assignee will need to work with Patrick on this ticket to figure out what goes where, what is hard-coded vs. service-driven, etc. 
- You should be able to leverage the work in this completed [ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/325) for Current Status on Active Appeals Detail

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/438003929/inspect

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use [general done button a11y](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17185)
- Mark "Your Appeal" as Header 1
- Mark "[type] appeal" as Header 2

**Segmented Selector**
- accessibilityLabel=Name of tab (e.g. Status or Details)
- accessibilityHint="view your appeal___" (e.g. status or details)
- accessibilityRole="tab"
- Denote selected vs. unselected
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector (e.g. 1 of 2 or 2 of 2)

**Current Status**
- Mark "Current status" as Header 2
- Mark "The board has made a decision on your appeal" as Header 3

**Need Help**
- Mark "Need help?" as Header 3
- Link
     - Title= Name of link (e.g. 800-827-1000)
     - accessibilityHint= “Dials this number via your device’s call function” **OR** "Navigates to VA.gov claims and appeals"
     - accessibilityRole= “link”

**Details Summary**
- Mark "currently on appeal" as Header 3
- Ensure each appeal is read together by the screen reader (ex. "service connection, post-traumatic stress-disorder" should be read together instead of as two separate items) 

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
Hi @bridgethapner, a few questions about the Closed Appeal detail page: 

1. When 'Details' is the selected segment, does this page display the same information as the Active Appeal detail page? 
2. On the Current Status section, what is data-driven vs. hard-coded? Including an annotated screenshot below with initial assumptions.
3. Under "The judge granted the following issue", will multiple issues be combined into 1 bullet point and separated by commas? Or could there be multiple bulleted items in this list? 
     - If the latter: should the copy above it update to "The judge granted the following issues" when there are multiple items? 

![Screen Shot 2020-12-11 at 3.44.48 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/817383a0-fe32-4a17-80d7-6941a3c11c4b)

**Comment by bridgethapner** [comment]
1. When 'Details' is the selected segment, does this page display the same information as the Active Appeal detail page? **Yes.**

2. On the Current Status section, what is data-driven vs. hard-coded? Including an annotated screenshot below with initial assumptions. **This is a really good question. I would like to work this out with @lexicalninja & @jperk51 next week. I think we need to work with Jayson to understand what all can come from the service before we decide. I'd like to know if in the service, every closed claim shows the same type of data like we have here. If yes, then I think we can hardcode what's highlighted in blue. If no, then I think we need to see if we can pull everything from the service so we always reflect what's right for that specific claim.**

3. Under "The judge granted the following issue", will multiple issues be combined into 1 bullet point and separated by commas? Or could there be multiple bulleted items in this list? **There could be multiple items in this list & yes we should use "The judge granted the following issues" when it's multiple.**

**Comment by komaly15** [comment]
note for QA: this can't be tested until the appeal service integration is complete and we are using real data, mock data won't reflect these changes

**Comment by digitalken** [comment]
Added to TestRail.
