### ISSUE TITLE
Analytics Vaccine dashboard request - Stretch Goals

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17380]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.
- [ ] New dashboard
- [x] Iteration of current dashboard

---
# Stretch Goals
Include Vaccine topics
- [ ] [Chatbot chart](https://va-gov.domo.com/page/1614417801/kpis/details/630223200)
- [ ] All Contact Center charts
- [ ] [Covid FAQ link clicks](https://va-gov.domo.com/page/1614417801/kpis/details/962331489)
- [ ] [Overall topic mapping](https://va-gov.domo.com/page/2077110052/kpis/details/803527659)
---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Adding a separate section on the Covid Homepage for vaccine sign ups.

@joanneesteban to send wireframe.

**Comment by joanneesteban** [comment]
@JasonTheBearded additions & wireframes below!

## Stretch Goals
- [ ] Add vaccine hub as a page to [Pageviews for COVID related pages](https://va-gov.domo.com/page/2077110052/kpis/details/1663907456), [COVID Pages Percent Change](https://va-gov.domo.com/page/2077110052/kpis/details/41688618), and the text list on [Covid-19 Digital Response](https://va-gov.domo.com/page/2077110052)
![image](https://user-images.githubusercontent.com/48964695/102362770-c5194c80-3f82-11eb-9d77-82a7da20da59.png)
---
- [ ] Add a vaccine section on [Covid-19 Digital Response](https://va-gov.domo.com/page/2077110052)
Data: Successful vaccine registrations

### Example
![image](https://user-images.githubusercontent.com/48964695/102366959-3824c200-3f87-11eb-99a7-90397cf16135.png)
---
- [ ] Add vaccinations as a topic to [Percent of engagement with each topic across mediums ](https://va-gov.domo.com/page/2077110052/kpis/details/1592687996) and [VA.gov Response Topic Mapping](https://va-gov.domo.com/page/2077110052/kpis/details/803527659) on [Covid-19 Digital Response](https://va-gov.domo.com/page/2077110052)
![image](https://user-images.githubusercontent.com/48964695/102367367-b08b8300-3f87-11eb-990f-85da1b84c96f.png)

![image](https://user-images.githubusercontent.com/48964695/102367390-b97c5480-3f87-11eb-838b-a42f6ab4e02b.png)
---
_If we receive vaccine data_
- [ ] Add vaccinations as a prompt type to [VA311 Interactive Voice Response (IVR) number of selected prompt types](https://va-gov.domo.com/page/1614417801/kpis/details/755716693) and text explanation on [Topic Trends](https://va-gov.domo.com/page/1614417801)
![image](https://user-images.githubusercontent.com/48964695/102367772-22fc6300-3f88-11eb-9d16-2ee30077f62b.png)
---
_If we receive vaccine data_
- [ ] Add vaccinations as a topic to [Veterans Experience Office (VEO) calls by issue](https://va-gov.domo.com/page/1614417801/kpis/details/89257193) on [Topic Trends](https://va-gov.domo.com/page/1614417801)
![image](https://user-images.githubusercontent.com/48964695/102367952-54752e80-3f88-11eb-9b1a-8e188a9ba888.png)
---
- [ ] Add Covid-19 vaccines as a topic to [Top Chatbot Categories](https://va-gov.domo.com/page/1614417801/kpis/details/630223200) on [Topic Trends](https://va-gov.domo.com/page/1614417801)
![image](https://user-images.githubusercontent.com/48964695/102368126-838ba000-3f88-11eb-90a1-64b2d8eed9ec.png)
---
- [ ] Add Covid-19 vaccines as a topic to [COVID FAQ Link Clicks by Week](https://va-gov.domo.com/page/1614417801/kpis/details/962331489) on [Topic Trends](https://va-gov.domo.com/page/1614417801)
![image](https://user-images.githubusercontent.com/48964695/102368325-ba61b600-3f88-11eb-9c4b-4833b04a23c1.png)
---
- [ ] Add Vaccination Registration as a section to [Tool Usage](https://va-gov.domo.com/page/160747235).
Data: Completed registrations

### Example
![image](https://user-images.githubusercontent.com/48964695/102369788-57711e80-3f8a-11eb-8a0a-43af922f84ec.png)

**Comment by joanneesteban** [comment]
Forward the final spreadsheet to Danielle & Chante to review before publishing.

**Comment by JasonTheBearded** [comment]
@joanneesteban Completed the requested changes. Please let me know if there's anything else

**Comment by joanneesteban** [comment]
These look great! Thanks for working on this, @JasonTheBearded & @bsmartin-ep ! Moving to Stand By until @clantosswett  gets Vaccine topics segmented by the Contact Centers. (CC: @jwoodman5 for visibility into Contact Center data for Covid Vaccines)

**Comment by joanneesteban** [comment]
@JasonTheBearded Are we able to add "vaccines" to the Contact Center charts/series above? If we can, let's do that and we can close the ticket. If we can't, let's document here and close the ticket.

**Comment by JasonTheBearded** [comment]
@joanneesteban I added the vaccine topic to the VEO Contact Center chart but we do not have vaccine data yet for IVR and NCC. So I think we can close this ticket :)
