### ISSUE TITLE
General Analytics Request for va.gov/geriatrics

### ISSUE THREAD

**Issue by HikeBandit** [department-of-veterans-affairs/va.gov-team#17386]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
For the page https://www.va.gov/GERIATRICS/pages/Home_and_Community_Based_Services.asp, we see that Time on Page increased 3X during a brief period in November. We also see that compared to the previous period, pageviews increased 14%. We find that most pageviews come from Direct sources. Can you find out 1) why the time-on-page and pageviews increased?
- [ ] Timeframe for Analytics Requested
Please get back to me by 12/17/2020
- [ ] Analytics to Track Down
Cause of increased pageviews and time on page.

- [ ] Which Product Questions are you trying to answer? 
Why is this page increased 14% in pageviews during November. 

- [ ] Additional Comments

## Description
- Sherri DeLoof, Sherri.Deloof@va.gov
- Margery Spears, margery@searchenginecatalyst.com

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- This is for va.gov/geriatrics
  
- What type of analytics support are you looking for?
  - [X] metrics clarification (verification that the metrics you are looking at are being read accurately)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
Nov. 2020 vs. the previous period

## Analytics to Track Down
> Examples
> 
> - [ ] Pageviews
> - [ ] Time on page

## Which Product Questions are you trying to answer? 
_Why did the pageviews for the https://www.va.gov/GERIATRICS/pages/Home_and_Community_Based_Services.asp page increase 14% and why did the time-on-page increase?

## Other Helpful Questions to think through
- Audience: Caregivers and geriatric veterans
- We want to understand this to better serve our website audience
- We seek a data-based explanation of this anomaly

## Link to Metrics
![image](https://user-images.githubusercontent.com/63690878/101956276-25d80c00-3bb4-11eb-8031-6d8e4b31c122.png)

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._
Please contact margery@searchenginecatalyst.com for questions.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @HikeBandit , 

Thank you for your request, acknowledging receipt here.

**Comment by rroueche** [comment]
Thanks @jonwehausen ! @joanneesteban has escalated this to Chris J and I to take a look.

**Comment by rroueche** [comment]
As communicated in the email thread out about this request, this is unfortunately out of the scope of what we're able to do. Thank you for understanding.
