### ISSUE TITLE
Claims Detail | Update segmented selector label

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17398]
## Acceptance Criteria
1. On the Claims detail page, update the label for the right segment from "Issues" to "Details" 
     - Update the associated a11y labels/hints to reflect this change

## Designs
![Screen Shot 2020-12-11 at 3.14.24 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/5a85fd1f-447f-4024-9bc4-7013fffde620)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 12/16/2020 on iOS and Android.  Moving to Design QA.
