### ISSUE TITLE
Determine & document best practices for using va.gov-teams/teams folder

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#1739]
### User Story 
As a user of the va.gov-team repo (as a member of a VSF or VSP team), I need to know how to use the va.gov-team/teams folder, so that I can find what I need quickly and easily. 

### Goals
Create documentation for best practices of using the va.gov-team/teams folder. Communicate those best practices to all VSF and VSP teams. 

### Definition of Done
- [ ] Create documentation of best practices for using the va.gov-team/teams folder.
- [ ] Communicate best practices to all VSF and VSP teams.

**Comment by mnorthuis** [comment]
I think this is a duplicate of #1246?

**Comment by meganhkelley** [comment]
Yep, totally is. Closing.
