### ISSUE TITLE
Active Claims detail | Update UI for list item

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17399]
## Acceptance Criteria
1. On the Claims Detail page, under the Details segment make the following update to the UI: 
     - The list of contentions under "What you've claimed" should appear as a bulleted list

## Designs
(Bridget to update) https://adhoc.invisionapp.com/d/main#/console/20546460/432345662/inspect

Example from Appeals detail page: 
![Screen Shot 2020-12-11 at 7.02.51 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ec628065-3bd4-417b-a408-3ad3494d1f39)

**Comment by digitalken** [comment]
Added to TestRail.
PASS 12/23/2020  on Android and iOS.  Sending to Design QA.
