### ISSUE TITLE
Expand visual regression testing coverage 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#174]
- Highest traffic landing pages on www.va.gov that are part of `vets-website`
  - www.va.gov
  - www.va.gov/claim-or-appeal-status/
  - www.va.gov/find-locations
  - www.va.gov/track-claims/your-claims
  - www.va.gov/records/get-veteran-id-cards/vic/
  - www.va.gov/welcome-kit/
  - www.va.gov/va-payment-history/

**Comment by rianfowler** [comment]
The teamsite script selects specific parts of the page to generate images from to avoid false positives caused by dynamic elements that change frequently (e.g. dates). Suggest following the same pattern by validating the critical elements on the pages (e.g. element that react mounts to)

**Comment by billfienberg** [comment]
Here are some visual regression options I've heard of:

- https://percy.io/
- https://applitools.com/visual-testing/
