### ISSUE TITLE
Accessibility feedback for Staging Review - Facilities [Map enhancements]

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#17403]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** Jennifer

## Details

This epic contains accessibility feedback for the Staging Review - Facilities [Map enhancements].

**Comment by jenstrickland** [comment]
@mmiddaugh I've completed the accessibility staging review — except the JAWS+IE11 pairing, due to bug [#17305](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17305).

@1Copenut — Ready for VSP's review.

**Comment by 1Copenut** [comment]
@jenstrickland I agree with the feedback you've offered here. https://github.com/department-of-veterans-affairs/va.gov-team/issues/17405 appears to be mostly fixed. I think the Search this area of map should receive focus each time there's a map "reflow" event, what do you think?

**Comment by mmiddaugh** [comment]
All associated issues have been closed
