### ISSUE TITLE
508-defect-1 ❗ Launchblocker [COGNITION, FOCUS MANAGEMENT]: When "Search this area" button is introduced, it must be announced and available to assistive technology

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#17405]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** Jennifer

## User Story or Problem Statement

As a user of a screen reader, I expect to hear an interactive option, focus moved to that element, and be able to activate it, so I can navigate the screen by keyboard or switch.

## Details

When navigating a search results screen by screen reader and keyboard, if a user zooms in or out on the map there is an announcement to "Search this area" but it is not possible to activate that button.

## Acceptance Criteria

- [ ] When the "Search this area" button is introduced, it is announced for screen readers

- [ ] When the "Search this area" button is introduced, focus is moved to the relevant `<button>`

- [ ] When the "Search this area" button is introduced, focus is visible on the relevant `<button>`

## Environment

* Operating System: MacOS
* Browser: Safari
* Screenreading device: VoiceOver
* Server destination: staging

## Steps to Recreate

1. Enter `https://staging.va.gov/find-locations/?address=Portland%2C%20Maine%2004103%2C%20United%20States&context=Portland%2C%20Maine%2004103%2C%20United%20States&facilityType=health&location=43.69%2C-70.30&page=1&searchString=Portland%2C%20Maine%2004103%2C%20United%20States&serviceType` in browser
2. Start screenreading device listed in Environment
3. Navigate to the map area
4. Zoom in or out
5. Verify that "Search this area" is announced
6. Verify that using the space bar does not activate the "Search this area" button
7. Verify that it is not possible to tab through the interface and see a focus halo on the "Search this area" button

## WCAG or Vendor Guidance (optional)

* [WCAG 2.0 Level AA - 2.4.7 Focus Visible](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html) - Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible. 

* [WCAG 2.0 Level A - 2.4.3 Focus Order](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html) - If a Web page can be navigated sequentially and the navigation sequences affect meaning or operation, focusable components receive focus in an order that preserves meaning and operability. 

* [WCAG 2.0 Level A - 3.2.2 On Input](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-unpredictable-change.html) - Changing the setting of any user interface component does not automatically cause a change of context unless the user has been advised of the behavior before using the component.

**Comment by mmiddaugh** [comment]
The fix for this is available on Staging for your review @jenstrickland

**Comment by jenstrickland** [comment]
The fix introduced another change. When I use VoiceOver now and activate Zoom In button, I hear:

1. Map
2. A B C D E F Zoom In, Zoom Out, https://www.mapbox.com/, Mapbox logo, link Search this area of map, group

I expect that when I activate the Zoom In button, I should hear "button, Search this area of map".

![Screen Shot 2020-12-16 at 8 55 50 AM (2)](https://user-images.githubusercontent.com/57469/102357658-90a29200-3f7c-11eb-97f1-97caf2827d6c.png)

**Comment by brangi** [comment]
@jenstrickland, this is another issue that I don't think can be solved without leveraging accessibility plugin - https://github.com/mapbox/mapbox-gl-accessibility but that was not the scope of this release. cc @mmiddaugh

**Comment by brangi** [comment]
@mmiddaugh closing this one since the main issue is fixed, we need to log another ticket to fix it on safari

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17656
