### ISSUE TITLE
Contact Center Review for [VSA: Content and Localization - Spanish Translation for Corona Pages]

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17414]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high level description of your product.*
**Corona FAQ** page in spanish. See slide:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/Corona%20FAQ%20-%20Contact%20Center%20Review.pptx 
### Launch Date

*Please provide the launch or rollout date and details.*

Targeted for 1/20

### Product Guide
*Please provide product guide link*

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] VSP Analytics & Insights QA has been completed 
- [ ] VSP Analytics & Insights sends artifacts to appropriate contact centers
- [ ] VFS team completes brief VSP Collaboration Cycle Feedback survey [link](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before)

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi Danielle - assigning you this ticket per our discussion. You were going to check with your contact on how they handle spanish language callers so we can determine what to add to the in-language pages.

Also, check to see whether they needed any type of info/slides for this effort.

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - have you had a chance to follow-up on this and what we need to provide (if anything)?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. Chante is back in the office today. I have a message out to her and will follow up here as soon as I know more. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. I spoke with Chante this morning. Different contact centers have different ways of handling callers who need help in languages other than English. So she is going to check with the different centers and get back to us with more info. Thanks!

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Thanks for update! Did she need any training materials (ie product guide) from us or is the new page just an item to make the call centers aware of?

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - any updates? Do we need to provide anything?

**Comment by jwoodman5** [comment]
@SKasimow Hi there - I was reviewing the collab cycle tracker and just saw this. Are you ready for a Contact Center Review? Thanks.

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason - @DanielleThierryUSDSVA has been discussing with Chantelle (?) from Contact Center but should we be working through you?

**Comment by jwoodman5** [comment]
Hi @SKasimow - Logging here per our chat earlier. Yes, please work with me on these and I can bring @clantosswett in when necessary. Thank you much.

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason - please see the slide created for Contact Center updates and let me know if this is on track or if you need anything more/different. Thanks, Sharon

**Comment by jwoodman5** [comment]
@SKasimow I do think this is in line with what we would be looking for with a small update like this. Thanks for sharing. I will get this in front of our content specialist for official review. cc// @starlow00

**Comment by starlow00** [comment]
Hi @SKasimow and @jwoodman5. I only had small edits to the header and the in-box caption. PPTX attached.
[https://app.zenhub.com/files/133843125/d41823e0-3ab7-42d1-a904-1f439e3a6f8b/download](https://app.zenhub.com/files/133843125/d41823e0-3ab7-42d1-a904-1f439e3a6f8b/download)

**Comment by SKasimow** [comment]
@jwoodman5 @starlow00 Thanks both! My cut and paste skills appreciate your refinements :)

**Comment by starlow00** [comment]
Hi @SKasimow (cc @jwoodman5, @Kimberley2019). I've been told that VEO wants larger images, so I put something together. Questions, let me know. Attached are the PPT and PDF, v2. [https://app.zenhub.com/files/133843125/3f405d82-8607-40c1-99b9-b35c045ebaaa/download](https://app.zenhub.com/files/133843125/3f405d82-8607-40c1-99b9-b35c045ebaaa/download)
[https://app.zenhub.com/files/133843125/008000fc-7a7e-488f-9dff-4514fd293687/download](https://app.zenhub.com/files/133843125/008000fc-7a7e-488f-9dff-4514fd293687/download)

**Comment by SKasimow** [comment]
@starlow00 Hi - both pages are live now so you can replace the mocks with screen grabs which should look nicer :)

**Comment by starlow00** [comment]
Thanks, Sharon @SKasimow. These have the most up-to-date page images, v3 (cc @Kimberley2019) 

[VSA_ContentLocalization_012021_v3.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5876340/VSA_ContentLocalization_012021_v3.pptx)

[VSA_ContentLocalization_012021_v3.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5876343/VSA_ContentLocalization_012021_v3.pdf)

**Comment by SKasimow** [comment]
@starlow00 Ah so much cleaner/better - thank you! Let me know if you get any questions from contact center I can answer.

**Comment by SKasimow** [comment]
Closing as completed.
