### ISSUE TITLE
Add feature toggle helper for setting toggle values during tests 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1741]
# Problem 

- end to end tests use the staging toggle values. 

# Tasks 

- create a helper for setting the values during tests that run in the browser 

# Notes 

- maybe set these values in a config like the manifests file
- consider defaulting to true during tests using and object proxy in the toggle selector

**Comment by alexpappasoddball** [comment]
@brandonrapp @rianfowler Is there something the backend needs to do here?  We believe this to be a front end thing.  We are going to remove the backend label for now as we clean up our backlog/ready column.  Let us know if there is anything we need to do.

**Comment by laineymajor** [comment]
closing as this has not been reviewed/commented on since 2019
