### ISSUE TITLE
Consider caching provider list on the front end

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#17419]
Typically when we fetch a list of data on the front end, we will cache it in Redux so that we don't have to fetch it again for the same parameters.

Currently, we're not doing this for the CC providers, even though they query could take a while. We should consider doing so. We'd have to store it in Redux with some kind of composite type of care and location key.

Or, we could take this opportunity to explore using swr or react-query for this page.

**Comment by laurenernest** [comment]
Pending direction determined after FE review of React state management research.

**Comment by laurenernest** [comment]
@jbalboni Was a solution for this determined in the FE meeting?

**Comment by jbalboni** [comment]
@laurenernest We're still doing some research on the approach Narin did a spike on, so it probably shouldn't hold up this ticket. I think we could go ahead and work on this ticket with our normal Redux caching approach.
