### ISSUE TITLE
Add alias resolution to node environment 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1742]
# Overview 

- `vets-website` supports babel aliases for several core folders like `platform/` for browser apps but does not support similar aliasing for node apps (e.g. testing scripts) 

# Goal 

- Determine if aliasing is possible in node apps 

# Notes 

- Maybe use this: https://www.npmjs.com/package/require-alias
- Maybe drive the alias behavior in both environments with a single configuration

**Comment by U-DON** [comment]
[`module-alias`](https://www.npmjs.com/package/module-alias) seems to be an actively supported module that is fairly simple to configure.

**Comment by U-DON** [comment]
Seems like the `babel-plugin-module-resolver` should work just fine by calling `require('@babel/register')` before any code is executed. In the code base's current state, tests can already abbreviate their import paths.

**Comment by rianfowler** [comment]
tried this out: https://github.com/department-of-veterans-affairs/vets-website/pull/10793#pullrequestreview-291944140
