### ISSUE TITLE
Use va.team repo as client documentation site source 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1743]
# Problem 

- documentation is being consolidated into [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team) repo
- the client documentation site houses its documentation [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/documentation) and is falling out of sync with latest documentation 
- client documentation site (gatsby based) offers features not available in plain github such as search indexing and easy page linking (side bar, header links) 

# Goal 

- try moving one of the pages from the client documentation site into the new repo and pulling the content into the gatsby website 
- identify any additional work that needs to be done to support using the new repo as a data source for all of the client documentation site's content 

# Notes 

- maybe add the link to the repo document to the markdown front matter and automatically generate a link in the footer with content update instructions 
- use a document that isn't already represented in the new repo- like the feature toggle documentation. There is a lot of onboarding documentation that needs to be reconciled against the client documentation site's IA - that is out of scope for this ticket but should be considered when identifying new work 
- some prior work has been done to use github repos as a data source. talk to @accbjt about this

**Comment by U-DON** [comment]
Completed with merge of department-of-veterans-affairs/veteran-facing-services-tools#173.
