### ISSUE TITLE
Content Feedback - Staging review  - Your VA payments 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#17434]
## User story

VSP content feedback for View VA payments on staging.  Staging link: https://staging.va.gov/va-payment-history/payments/

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

**Comment by peggygannon** [comment]
staging link: https://staging.va.gov/va-payment-history/payments/

**Comment by jason-gcio** [comment]
This all looks pretty straightforward, except for Question 3: do you mean the type of payments that will show up?  We did some discovery around where payments would come from that I would need to look for but this should be true.

**Comment by jason-gcio** [comment]
For Question 2: The landing page mentions a "Veterans Help Line" but I think I like your more agnostic "benefits assistance" piece more.  We will make that change.

**Comment by jason-gcio** [comment]
Question 1: The top funnel will be from the home page, to a landing page that holds more info.  I don't believe there have been any requests to make changes to that page, perhaps other than the note I made (above) about the "Veterans Help Line."

**Comment by peggygannon** [comment]
HI, @jason-gcio for Question 3, I wanted to make sure that content (in bold below), which appears in the right rail is true. that updating information in your profile will also update across your VR&E and health care benefits? These 2 benefit types weren't in this content in the mockup I saw previously,  so am just confirming this addition is accurate. 


Go to your profile to make updates to your contact and direct deposit information. Any changes you make in your profile will update across your disability compensation, pension, claims and appeals **VR&E, and VA health** care benefits.

**Comment by jason-gcio** [comment]
@peggygannon - Ah I see, ok.  I think that is meant to just be a general statement based on the fact that profile info is used everywhere but we can definitely verify that is the case.  Next iteration for this feature removes the right rail so if this is redundant or needs to be reworked we will check in on it again.  I will have an update on this question soon though.

**Comment by jason-gcio** [comment]
Ticket with content changes: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17702

**Comment by jason-gcio** [comment]
@sporeboy - this is a reminder for me to remember this tomorrow \o/
