### ISSUE TITLE
Test User Discovery Research Epic

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#17445]
## High Level User Story
As a member of the identity team, I want to understand the teams that utilize test user accounts so that I can produce a good quality product that is easy and enjoyable to use.

## Goals
- Discover how teams are being impacted by the test user account process
- Obtain user feedback as it relates to using test user accounts through user interviews
- Understand pain points
- Offer solutions as decided by the Identity team
- Conduct usability testing with prototyping

**Comment by nsoutouras** [comment]
Closing as TUD is transitioned to Testing Tools Team
