### ISSUE TITLE
Create Public and Private Keys

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#17447]
### Description:
Info provided by the LH system admin person that will grant the access:
Clients requiring system-to-system auth will use the OAuth 2.0 Client Credentials Grant (RFC6749 - Section 4.4) to obtain an access_token for use with Lighthouse APIs.
Client authentication shall be private_key_jwt as described in the OpenID spec.
Clients will generate an RSA key-pair and provide Lighthouse the public key in JWK format.
Example:
```
{
  "kty": "RSA",
  "n": "mYi1wUpwkJ1QB8...",
  "e": "AQAB",
  "alg": "RS256",
  "use": "sig"
}
```
openid.net
Final: OpenID Connect Core 1.0 incorporating errata set 1
OpenID Connect Core 1.0 incorporating errata set 1

### Tasks:  
- [ ] update [this doc](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/health%20quest%20service.md) to reference two different envs (MAP and LH) and update the connections we will make to MAP. 

- [ ] Here is the ticket used to request the keys. [#13188 Please generate Public/Private Key pairs for Clipboard Questionnaire app integration with MAP](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13188)

**Comment by stephenBarrs** [comment]
We will need three sets of keys for accessing LH for Sandbox QA/Staging and Production.  The private keys should be stored in CredStash for access from the vets-api BE Clipboard application.

**Comment by dillo** [comment]
Created a new issue and tagged `operations` https://github.com/department-of-veterans-affairs/va.gov-team/issues/17668

cc: @mlighdc @abuckley3385 @stephenBarrs
