### ISSUE TITLE
Active Claims detail | Status/Issues segmented selector - Accessibility Issues

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#17459]
## What Happened?
**VoiceOver/TalkBack**
1. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, the a11yHint for the segmented selector is not picked up
2. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, the position for each tab in the selector is not denoted

**Axe / Accessibility Scanner**
3. Using Axe and Google Accessibility Scanner, the segmented selector is measured to be 33px tall. Touchpoints must be a minimum of 44px by 44px

## Specs:
- Device: Android - Google Pixel 3XL(v.11) with TalkBack enabled
- Device: iOS - iPhone XR(v.14.2) with VoiceOver enabled
- User: marcy.nadeau@va.gov

## Steps to Reproduce: 

**VoiceOver/TalkBack**
For 1: 
1. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, navigate to the active claims detail page
2. Select the status or issues tab in the segmented selector
3. Note that the screen reader does not pick the a11yHint "view your claim___" (e.g. status or issues)

For 2:
1. With the appropriate screen reader (VoiceOver/TalkBack) enabled on iOS/Android, navigate to the active claims detail page
2. Select the status or issues tab in the segmented selector
3. Note that the respective positions 1 of 2 or 2 of 2 are not denoted

**Axe / Accessibility Scanner**
For 3:
1. Enable Axe or Accessibility Scanner on Android
2. Navigate to the active claims detail page
3. Run Axe or Accessibility Scanner on the page

## Desired Behavior

**VoiceOver/TalkBack**
For 1:
- When the appropriate screen reader (VoiceOver/TalkBack) is enabled on iOS/Android, the segmented selector's a11yHint will be picked up as  "view your claim___" (e.g. status or issues)

For 2
- When the appropriate screen reader (VoiceOver/TalkBack) is enabled on iOS/Android, the status tab position will be denoted as 1 of 2 and the issues tab position will be denoted as 2 of 2

**Axe / Accessibility Scanner**
For 3:
- The selector and the buttons within it should be a minimum of 44px by 44px

## Acceptance Criteria
- See desired behavior

## Bug Severity
- 4 - Low

## Linked Story (s)
- Story #16785

## Screen Shot(s) and Additional Information 
![Active Claims Detail Segmented Selector Touch Point.png](https://images.zenhubusercontent.com/5f7bb216620a259ab7e50d60/dedd7c3a-55fc-4f1c-9112-0d005290bb07)

**Comment by digitalken** [comment]
1/12/2021
PASS on Android devices.
Hold for iOS build.
