### ISSUE TITLE
[Discovery] Create research plan

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#1745]
## Goal
Create a research plan to learn how Veterans are using the claim status tool to upload Decision Review forms. 

## Acceptance Criteria
- [x] Research plan has been reviewed with the team
- [x] Recruiting ticket (with research plan attached)has been created and shared with Lauren Alexanderson
- [x] Link to research plan has been added to this ticket

**Comment by kevinstachura** [comment]
@AZSchneider for your review: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/discovery-SEP-2019/research-plan.md

**Comment by smoonpeyes** [comment]
Done. Closing this ticket.
