### ISSUE TITLE
FE bug on How to apply for a discharge upgrade page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#17462]
## On this page: https://www.va.gov/discharge-upgrade-instructions

Note: This isn't affecting functionality or accessibility.

**Bug 1 - Desktop & Mobile:** 
- Intro text is using blue font color for some reason. Correct color should be black. Please consult design system or a designer for exact color #.

**Bug 2 - Mobile:** 
- Left margin is too smooshed up against edge and is getting ever so slightly cut off. 

![IMG_2323.PNG](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/a2c2e539-f529-402c-80d5-6be6e539a28b)

**Comment by ncksllvn** [comment]
Fixes are live, https://www.va.gov/discharge-upgrade-instructions

**Comment by brianalloyd** [comment]
Validated, thanks @ncksllvn for working the details.
