### ISSUE TITLE
Claims File Upload page | Section 2 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17466]
## User story
As a user, I want to see how many file requests I have from the VA. 

## Acceptance Criteria
1. On the File Upload page, create a section called "You have [#] file requests from VA
     - The # is service-driven and should correspond to the number of "Upload" sections below
     - If the # equals 1, change the copy so it reflects the singular noun: "You have 1 file request from VA"
2. Create UI for the Request/Upload section, which contains: 
     - Request Title, in bold (service-driven)
     - Description of the file request from VA (service-driven)
     - Large button CC, titled: "Upload"
3. There should always be at least 1 file request from the VA listed on this page

Note: there is a separate ticket for Section 1 of this page: [#16775](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16775)

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432623517/inspect
![Screen Shot 2020-12-14 at 5.39.42 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/0d39b135-985d-4edd-a80d-e11d8f4b7613)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Mark "You have [#] file requests " as Header 2
- Mark "[Request Title]" as Header 3

**Upload Button**
- Title= “Upload”
- accessibilityHint= "opens a file upload menu"
- accessibilityRole= “button”

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by msmanak** [comment]
Make sure the upload proccess is conveyed easily for blind user as iOS doesn't have a method of capturing correct screens @bessgreen

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/8/2021 - both UI and accessibility. Moving to Design QA.
