### ISSUE TITLE
Claims: 'Ask for your Claim Decision' Flow

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17465]
## User Story

As a user, I want to be able to tell VA to go ahead and start evaluating my claim if I don't plan to upload additional evidence. 

## VA.gov reference screenshots
![Screen Shot 2020-12-14 at 4.36.41 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/9c8feb97-90e8-4d06-96cd-4e6cf315a69d)
![Screen Shot 2020-12-14 at 4.36.49 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/2af91a9a-aeaa-4902-97c9-02de572f4e87)

**Comment by bridgethapner** [comment]
@lexicalninja :wave: 

I started this work by adding an Informational Alert to the bottom of the [first screen of the file request flow](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432623517) & putting all the content from VA.gov's "Ask for your claim decision" [screen](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/440446462) together using our components. 

Next I need to design the success message -- Can you look in the CST code & see what copy it displays to the user after they hit "submit" on this screen? Thank you!  

Minor thing -- I added a Large Button component into the Informational Alert component here, but don't think that CC is currently set up to do that. 

![Claim-Upload-1.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/11921d0f-c446-47cf-9c89-ee7b351f03f3)
![Ask for your Claim Decision.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/7a5e5915-93c6-44b5-a5b8-3c157a1b959b)

**Comment by lexicalninja** [comment]
@bridgethapner Here is the notification text that gets sent up after successful submit:
```javascript
{
   title: 'Request received',
   body: 'Thank you. We have your claim request and will make a decision.',
}

**Comment by bridgethapner** [comment]
Thanks, Patrick! 

UX for [this flow](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432623517): 
- User can click 'View details' from the first screen of the Claims File upload flow to get to info screen.
- Users will need to select the checkbox to active the save button.
- When they hit 'Submit' they see a Success Alert
- Back button takes them back to the first screen of the Claims File upload flow & the Info Alert for 'Ask for your Claim Decision' should no longer appear. 

I believe the CC for the checkbox has an unselected state already, but I think we need to add:
1. A disabled state to the CC for the large button: Everything the same as the large button except background-color: #D6D7D9
2. A success state to the CC for the alert: Everything the same as the current CC except border-left: #2E8540

**Comment by bridgethapner** [comment]
cc @bessgreen I think this flow is set, please lmk if you have any questions!

**Comment by lexicalninja** [comment]
I am currently requesting the mobile end-point be created, but we are using this as a chance to set up a process for requesting new API endpoints. It should not take long, but we are creating an issue template for new endpoints that we can use in zenhub and help balance the front end work better than just pinging them on slack asking for new things. I will update this ticket or the integration ticket when that is ready

**Comment by bessgreen** [comment]
@bridgethapner after a user has successfully submitted their claim decision, will they still see the file requests on the **File Upload** screen? Or will these be hidden? 

![Screen Shot 2021-01-14 at 2.38.54 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/97209dd9-7850-4ffa-83e4-2e62bade3479)
