### ISSUE TITLE
Enhancement: RS mobile views, left margin is too smooshed to the edge and cutting off text 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#17470]
## Enhancement: RS mobile views, left margin is too smooshed to the edge and cutting off text 

**This appears to affect the following:** 

1/ The bottom layer components on all of the RS article templates (starting from `Related information` component on down, except the `Need more help`). 

2/ The `Last updated: {date}` field on all RS pages (articles, all articles landing pages, RS homepage).

3/ The article list on all of the `All articles` landing pages. 

**See sample screenshots of mobile pages in comments.** 

### Mobile specs for FE:
@rtwell  says we don't have design specs for this, and that we should be using whatever is already being used on other pages showing mobile correctly. Please go to the [Health Care Benefit hub landing page](https://www.va.gov/health-care/) and view it on a mobile device. You'll be able to see  that there's a little bit of space padding on the left edge/margin. That's how these RS pages in mobile should be appearing.

**Comment by jenniferlee-dsva** [comment]
## Bottom layers on article templates: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/0296da43-a908-4f7e-82a3-f6c4145329c1)

AND

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/19675261-d365-4a6b-9ae4-3dfb62a20324)

**Comment by jenniferlee-dsva** [comment]
## `All articles` landing pages:

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/c276fc4d-0143-4742-a115-7a748bce0efe)

AND 

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/2c153895-59e2-45b6-8ba0-939050b40b16)

**Comment by rtwell** [comment]
The left margin should be the same as it is across VA.gov. I have no idea what specification that is, but these pages should follow the same treatment.

**Comment by brianalloyd** [comment]
@sanlouise can you provide a status update on this ticket?  If you could include status and any breadcrumbs to help the next engineer working this that would be great.  Thanks for the assistance this sprint.

**Comment by brianalloyd** [comment]
I just reviewed this on Mobile and it looks good from my vantage point.  @jenniferlee-dsva or @johnhashva can you all take a look in support of validation?  Thanks.

**Comment by brianalloyd** [comment]
Update: Ticket still needs to be worked on FE.  @johnhashva reviewed 1/3/2021.

**Comment by brianalloyd** [comment]
Validate, closing
