### ISSUE TITLE
Error |  Claims unavailable

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17471]
## User story
As a user, I want to know when I cannot access my claims because of an upstream error, even if my appeals are available. 

**Technical context**
Appeals and Claims are fetched from two different services so it’s possible one could be down and the other still up.

## Acceptance Criteria
1. Create UI for an error state when claims cannot be loaded, but the user has a list of appeals which _can_ be loaded
2. Pull in mobile alert CC
     - Copy is hard-coded
     - This error message appears between the segmented selector and the list of claims/appeals
3. Triggered when the claim service is down (see comments for more info)

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/439369081

## Corresponding UX ticket
[#15975](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15975)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Mobile Alert**
- Mark "Claims status is unavailable" as Header 2

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
{
  "data": [
    {
      "id": "600117255",
      "type": "claim",
      "attributes": {
        "subtype": "Compensation",
        "completed": true,
        "dateFiled": "2020-01-01",
        "updatedAt": "2020-01-01T00:00:00.00Z"
      }
    }
  ],
  "meta": {
    "errors": [
      [
        {
          "service": "claims",
          "errorDetails": [
            [
              {}
            ]
          ]
        }
      ]
    ]
  }
}

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/29/2021 - Both iOS and Android.
