### ISSUE TITLE
Error | Address Recognition w/ suggestions

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17480]
## User story
As a user, I want the app to inform me if my inputted-address has formatting issues and provide suggestions for similar, valid addresses.

## Acceptance Criteria
1. Create UI for when a user's inputted address cannot be confirmed with USPS and the service returns at least 1 suggested address
     - This screen should display after a user has entered an address on the edit screen and hits "Save". 
     - Hide "Cancel" and "Save" buttons on this page
2. Pull in the [**No suggestions** error page](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17695) with the following modifications:
3. Update copy on mobile alert
4. The **You Entered** section contains 2 large buttons: "Use this address" (primary) and "Edit address" (secondary)
    - Selecting "Use this address" will save this address, and return the user to the Personal Information screen  _or_ the Letters overview page (depending on where the user came from) with this address displayed
    - Selecting "Edit address" returns the user back to the edit page
5. Create a section for **"Suggested Addresses"**
     - Display a list of similar addresses that are returned from the USPS service
     - This list should include at least 1 suggested address
     - Radio button next to each suggestion
6. Rules for radio buttons:
     - On default navigation to this page, the first suggested item is selected
     - A user cannot select more than 1 suggestion
     - A user cannot de-select a suggestion (i.e. there will always be 1 suggestion selected)
7. In the Suggested Addresses section, create UI for a large button: "Use suggested address"
     - Selecting this button will save the selected suggested address, and route the user back to the Personal Information overview page _or_ the Letters overview page (depending on where the user came from) . This selected address will be displayed on the overview page. 
8. At the bottom of the page, create UI for a large button: "Cancel"
     -  Selecting this button will cancel out the edit flow and return the user to the Personal Information overview page  _or_ the Letters overview page (depending on where the user came from), without any changes saved

## Testing
**Invalid address to trigger this error state:**
1015 Florida St
Washington, DC 20002

**Suggested address that gets returned:**
1015 Florida Ave NE
Washington, DC 20002

## Designs: 
https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/441187434

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Mark "mailing address" or "residential address" as Header 1

**Mobile Alert**
- Mark "Please confirm your address" as Header 2

**You Entered Section**
- Mark "You entered" as Header 2

**Suggested Addresses Section**
- Mark "Suggested addresses" as Header 2
- Addresses as a group (more than one address):
     - accessibilityRole= “radio group”
- Each individual address:
     - accessibilityLabel= Text
     - accessibilityRole= “radio”
     - accessibilityState= Denote when selected vs. unselected

**Use this Address Button**
- accessibilityLabel= “use this address”
- accessibilityHint= "Saves changes and navigates to the personal information page"
- accessibilityRole= “button”

**Edit Address Button**
- accessibilityLabel= “edit address”
- accessibilityHint= "navigates to the edit address page"
- accessibilityRole= “button”

**Use this Address Button**
- accessibilityLabel= “use this address”
- accessibilityHint= "Saves changes and navigates to the [personal information]/[letters overview] page"
- accessibilityRole= “button”

**Cancel Button**
- accessibilityLabel= “cancel”
- accessibilityHint= "Cancels changes and navigates to the previous page"
- accessibilityRole= “button”

## Dev Checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Hi @msmanak & @bridgethapner, hoping you can weigh in on the following UX questions for this page:  

1. The "Edit address" button on this screen has different copy than the other 3 [USPS Validation](https://adhoc.invisionapp.com/d/main#/console/20546460/441187431/preview) pages ("Edit this address"). Is that intentional? Or should the copy be the same? 
2. Should any of the radio buttons be selected upon default? 
     - If not: Does the "Update" button need to have a disabled state when no radio buttons are selected? 
3. What happens when a user hits "Cancel"? What page are they routed to? 
4. Is there any way for a user to ignore the suggested addresses, and select/save the one that they entered?

**Comment by msmanak** [comment]
@bessgreen 

1. You are correct it should be "edit this address", I will fix one of the screens to follow.
2. not selected by default, users should select
3. Good question, I believe for va.gov it cancels the process but need to check with VAOS team again to verify.
4. They can ignore by selecting the button "use this address"

**Comment by msmanak** [comment]
3. Cancel goes back to original profile screen on Va.gov so id expect that to be similar action unless @bridgethapner wants to change it to edit screen page

**Comment by bessgreen** [comment]
Thank you, @msmanak! A few follow-ups: 

5. Re: #2 above: Once a user has selected a radio button, are they able to de-select it (i.e. not have any Suggested Addresses selected)? 
6. Re: #6 above: I'm not seeing a "use this address" button in the UI. Can you clarify?

![Screen Shot 2020-12-28 at 3.43.07 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/cd13239e-fcfb-4bf6-8af9-9f629f02b19d)

**Comment by bridgethapner** [comment]
Hi there @bessgreen :wave: -- just catching up on the latest here

7 - Looking at #17563, it looks like Meli added a button 'Use this address' to this scenario to match the other 3 address validation scenarios. Does that help to answer #6 above? (I like the numbering convention, trying to stick with it!)

8 - To keep with standard radio button behavior, we shouldn't allow unselection once selected. So a user can't unselect, but they can navigate away from their selection by hitting Cancel, Edit Address, or change their selection.

3 - Reviewing Meli's note above, I agree with her that the 'Cancel' button should go back to the Personal & Contact Information screen. 

2 - Regarding the question about pre-selection -- I think we should pre-select the first Suggested Address. I think pre-selecting an address & offering an actionable button right off the bat is clearer than having a default disabled state or a subsequent error message should a user try to hit 'Update' without making a selection -- since there are a lot of buttons on this screen, this seems the clearest course of action. Lots of complexity here! We can also revamp this flow in more detail down the line once we have the capacity to usability test it in detail.

**Comment by bridgethapner** [comment]
One more addition here - Let's update the bottom CTA to accept a Suggested Address should say 'Use Suggested Address' rather than Update. This copy is reflected in the wireframes.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - Minor bug written on accessibility ("Vaw" rather than "Vee" "A") closing.
