### ISSUE TITLE
[Ongoing Service] Collaborative VSP Research Projects

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#17488]
## Artifacts
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md))
- Link to product README ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md))

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by Khyatinp18** [comment]
2/21/2022:

Closing this issue since it's no longer needed.
