### ISSUE TITLE
Updated first name, last name, date of birth not present when user goes back to update their submission

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#17481]
## What happened?
The user does not see their updated first name, last name, and/or date of birth when they go back to the form to update their last submission. Instead, they continue to see their account-level first name, last name, and date of birth.

## Steps to Reproduce
- An loa3 user logs in, navigates to va.gov/health-care/covid-19-vaccine/stay-informed, and clicks  the ‘Sign up to stay informed’ button.
- The user’s first name, last name, and date of birth are pre-populated.
- The user updates their first name, last name, and date of birth and completes the rest of the form, submits it, then logs out.
- The user logs back in, navigates back to va.gov/health-care/covid-19-vaccine/stay-informed and clicks the ‘Sign up to stay informed’ button.
- The updates the user made to their first name, last name, and date of birth when they first submitted the form are not present, but the answers to the rest of the form fields are pre-populated.

## Desired behavior
When the user updates their first name, last name, or date of birth on a form submission, and later goes back to update their submission, they should see the values for their first name, last name and date of birth from their last submission.

## Acceptance Criteria
- To prevent confusion, one of the following scenarios might work better:
  - Show the first name, last name, and date of birth values from their last submission.
  - If you don’t want the user to be able to update their first name, last name, and date of birth values on their submission, don’t let them; display those values as text instead of in form fields.

**Comment by pjhill** [comment]
This is OBE.
