### ISSUE TITLE
General Analytics Request for [Authenticated Experience team - MyVA Dashboard - Matt Shea]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#17498]
# Metrics Reporting Request

## Instructions
Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?
**Matt Shea**
**Samara Strauss**

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?
**Authenticated Experience - MyVA Dashboard**
    
- What type of analytics support are you looking for?
** KPI Domo Dashboard (needed to get baseline metrics for MyVA, so we can compare to the new MyVA once we redesign it)**
    
## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
**As soon as possible, but this is not critical**

## Analytics to Track Down
** - % of VA.gov traffic that goes to MyVA page** 
**- # of visits to MyVA page**
**- # of clicks on MyVA (interactions)**
**- % of MyVA sessions that included a click (interaction)**
**- # of submissions/saves (if possible)**
**- MyVA Foresee score**

## Which Product Questions are you trying to answer?
**- What % of people go to MyVA (increasing or decreasing after launching MyVA 2.0)**
**- Interaction levels/types with MyVA**
**- Customer satisfaction levels/impact**

## Other Helpful Questions to think through
**- Who is your audience? VA.gov/MyVA users**
**- Why do you need this data? It is critical to determine baseline performance of MyVA and will allow us to track the impact of the MyVA redesign**
**- What are you hoping to find? We hope to find an increase in MyVA visits, interactions, and Foresee customer satisfaction scores**

## Additional Comments
Please let me know if you have any questions or if any of the items requested are not possible. Thanks!

Please leave the following blank
## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Acknowledging receipt, thanks @mshea0606

**Comment by bmcgrady-ep** [comment]
MyVA KPI | Metric | Source | Go/No Go
------------ | ------------- | ------------- | -------------
`% of VA.gov traffic that goes to MyVA page` | Total VA.gov Users / Total MyVA Users | BigQuery | ✔️ Go
`# of visits to MyVA page` | pageviews of `page path` matching RegExp `^www.va.gov(\/my-va\/**or**\/my-va\?postlogin\=true**or**\/my-va\/\?postlogin\=true)$` | BigQuery | ✔️ Go
`# of interactions MyVA page` | `event category = Interactions` with `page path` matching `www.va.gov/my-va` | BigQuery | ✔️ Go
`# of MyVA sessions that included an interaction` | Session-based custom segment with  `event category = Interactions` with `page path` matching `www.va.gov/my-va` | BigQuery | ✔️ Go
`# of submissions/saves` |  `event label = dashboard-preferences-saved-successful` and `page path` containing `www.va.gov/my-va` | BigQuery | ✔️ Go
`MyVA Foresee score` | ForeSee scores for page URL containing `www.va.gov/my-va` | ForeSee | ✔️ Go


GA Links:
[Number of interactions MyVA page](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventCategory&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=250&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22%5Ewww.va.gov~2Fmy-va.*%22,0%5D,%5B0,%22analytics.eventCategory%22,%22PT%22,%22Interactions%22,0%5D%5D)
[Number of Visits to MyVA page](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22%5Ewww.va.gov(%5C%5C~2Fmy-va%5C%5C~2F%7C%5C%5C~2Fmy-va%5C%5C%3Fpostlogin%5C%5C=true%7C%5C%5C~2Fmy-va%5C%5C~2F%5C%5C%3Fpostlogin%5C%5C=true)$%22,0%5D%5D/)
[Number of Submissions/Saves](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=250&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22%5Ewww.va.gov~2Fmy-va.*%22,0%5D,%5B0,%22analytics.eventLabel%22,%22PT%22,%22saved%22,0%5D%5D)

**Comment by mshea0606** [comment]
Thanks @bmcgrady-ep !

**Comment by mshea0606** [comment]
![KPI- Auth Exp](https://user-images.githubusercontent.com/60523453/103783288-85d09f80-5006-11eb-95d8-2ed6c2656b57.png)

**Comment by mshea0606** [comment]
<img width="746" alt="Screen Shot 2021-01-06 at 10 04 39 AM" src="https://user-images.githubusercontent.com/60523453/103783361-9d0f8d00-5006-11eb-8e89-3ce7ce4d85ad.png">

**Comment by mshea0606** [comment]
MyVA CTA interactions to track:
"Find VA Benefits"
"Apply for VA Healthcare"
"Find out how to file a claim"
"File a claim"
"Continue your application"
"View Claim"
"View all of your claims"
"Schedule an appointment"
"View your profile"

**Comment by mshea0606** [comment]
per our conversation @bmcgrady-ep , Thanks!

**Comment by bmcgrady-ep** [comment]
Thanks for the update @mshea0606. I have started staging the dashboard in Domo.

**Comment by bmcgrady-ep** [comment]
@JasonTheBearded - Can you set up a few Domo datasets for this KPI dashboard? One dataset would be % of logged-in users who visit the /my-va page **by month**. The other dataset would be for MyVA CTA interactions (`event label = dashboard-navigation`) **by month**.

**Comment by JasonTheBearded** [comment]
@bmcgrady-ep what determines a user is logged in? is the a hook on the URL or a specific event I need to look for? Also do the interactions need to be split out by the event action or is it just total number of interactions? thanks!

**Comment by bmcgrady-ep** [comment]
@JasonTheBearded - There is a custom dimension (CD 22) that specifies the level of access (LOA). We are wanting the LOA = 3, which shows that the user is logged-in. For interactions, it is just the total number of interactions.

**Comment by JasonTheBearded** [comment]
@bmcgrady-ep datasets are set up.
For % of Logged-In users: https://va-gov.domo.com/datasources/5c465e8d-67ea-4eb3-bc22-81ec9273e5a0/details/overview
For MyVA CTA Interactions: https://va-gov.domo.com/datasources/5b9580ff-b805-4c51-a470-38ff7662e155/details/overview

**Comment by bmcgrady-ep** [comment]
@JasonTheBearded - Thank you for getting the datasets up. I added the cards to the KPI Dashboard.

**Comment by mshea0606** [comment]
Thanks @bmcgrady-ep! Ill take a look today and let you know if i have questions!

**Comment by bmcgrady-ep** [comment]
@joanneesteban - Can you please review [this dashboard](https://va-gov.domo.com/page/2047315758)? Thanks!

**Comment by bmcgrady-ep** [comment]
I met with @mshea0606 yesterday to discuss the MyVA dashboard. There are a couple of changes needed for the dashboard. 
1. Add a chart for Increased MyVA Utilization (Total MyVA users / Total VA.gov users per month)
2. Look into why the CTA interactions chart doesn't match the CTA interactions table.

**Comment by joanneesteban** [comment]
@jonwehausen - to help look into why Domo isn't lining up w/GA on [this chart](https://va-gov.domo.com/analyzer?pageId=2047315758&cardid=1830180380)

**Comment by bmcgrady-ep** [comment]
@joanneesteban - [This](https://va-gov.domo.com/page/2047315758) dashboard is ready for design work/grooming.

**Comment by MickinSahni** [comment]
@ajakabcin

**Comment by Samara-Strauss** [comment]
Closing this. First, this should have never been submitted, as we already had My VA stats in GA. I apologize, as it was never communicated to me that this conversation had been started.

Second, we are now talking about My VA redesign analytics in #23336.
