### ISSUE TITLE
Access for Greg Bowman

### ISSUE THREAD

**Issue by gpbowman-git** [department-of-veterans-affairs/va.gov-team#17504]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   Cecilia.Lee@va.gov
- Please provide your name.
  Greg Bowman
- Please Provide your email.
  gregory.bowman@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   Team Matsumoto, Lead Developer, Liberty IT Solutions

- Requesting SSH key authorization?
   YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMJ6xjp3bq8lf9H2BwteIvBQyVbBlNAriMWlfX+sE2irQiAWg5CyB3Cm5+uQ7SwC5v00oAfwf/AvIRchToVuYraZvBTqBdOwBHsitefhTWkCFjk3ehwUtvA0567stla5vtvzL+w9dCeVpWA+vBaVBxfPKc8on6/2ie/w8bZ4vIWAAxMaeDTpDiEqsiYyKcwb62j0nBvODJtiwWoq70UFSFGlYbBuYSbYMSo+yPBJ6yH/Ugrm7t5Q5BtuKNXTS5NlJ+1JwOGpNv36zLIUO4IjP8BiaxC9YTECM5cdQTpZQfPISKGTiMchXVPuqiCfG2RmtWjFOp7EcnbMUckPHS06PXJByd3asXuW8Ts0UKWl+cKnhDqx+I2E31I9Md9Olox1m/0k/kLqPW2JOHK2CbWGtTfJOqMiFYSH+kAoFzHzbkLt5SLaI3nZE6gbzMAO9aC3hCfxPVOZc/mUVT0AY1ucAyF9PWQYi32BlQGu2U2LNYTQWB0AbSSIwdOTcEJJFYJBk= AzureAD+GregoryBowman@DESKTOP-ID8ISVV
```

- Grant AWS Console access?
  YES
  - What AWS services do you need access to and why? 
I need production access for the Benefits Intake API in order to provide support.

**Comment by tskinn** [comment]
@gpbowman-git it looks like you've already been granted access using this other ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/15065

Is there a reason you created this new issue? If you are having problems connecting you can reach out in slack.

**Comment by gpbowman-git** [comment]
I do have an AWS key and can access the lower level environments. However, I need to also be able to access production. Currently, we are working with a member of Team Dash, Mike Bastos, who has access to production and we have to go through him for all things production related, but he is a temporary resource of ours and we need someone on our team to have access to AWS in production.

**Comment by tskinn** [comment]
@gpbowman-git what resources do you need access to exactly? Are they lighthouse specific?

**Comment by jsev-io** [comment]
@gpbowman-git 
You'll be taking over as lead for the liberty team, right?

**Comment by gpbowman-git** [comment]
I am the team lead on the Benefits intake API team in lighthouse. Mike Bastos is assisting us currently with anything production related.

**Comment by gpbowman-git** [comment]
I need SSM access into vets-api server and workers for rails console access and production s3 bucket access for vba_documents.

**Comment by tskinn** [comment]
k thanks you should have access now. If furthur updates are needed feel free to open this ticket and ping us in slack.
