### ISSUE TITLE
Negative values can be submitted for DOB year on COVID vaccine registration page

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#17516]
## What happened?
When registering to receive COVID vaccine updates on the [COVID registration form](https://staging.va.gov/health-care/covid-19-vaccine/stay-informed/), a negative value can be entered for the DOB, and the form can be submitted successfully.

## Specs:
- Device: MacBook
- Browser: Chrome
- Test User: None required

## Steps to Reproduce
- URL: https://staging.va.gov/health-care/covid-19-vaccine/stay-informed/
- Click on **Continue without signing in**
- Fill out al required fields for the form. Enter a negative value for the date of birth year.
- Click **Submit form**

## Desired behavior
The user should receive a notification to enter a valid year, and the form is not submitted.
OR
Negative values cannot be entered into the year field.

## Acceptance Criteria
- [ ] Users see an error when the year is invalid OR
- [ ] Negative values cannot be entered for the DOB year

## How to configure this issue
- [ ] **Labeled with Team** (`covid-vaccine-distro`, `vsp-testing-team`, `bug`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`)
- [ ] **Labeled with `Bug`**

**Comment by pjhill** [comment]
OBE
