### ISSUE TITLE
Ask for Claim Decision page (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17511]
## User story
As a user, I want to be able to tell the VA to start evaluating my claim if I don't plan to upload additional evidence.

## Acceptance Criteria
1. Selecting the "View details" button from the File Upload page routes to a new page
2. Create section called "Ask for your claim decision" with copy below it
     - Copy is hard-coded
     - Some copy is formatted in a bulleted list
3. Pull in checkbox common component
     - Default state: unchecked
     - Display corresponding text next to the checkbox
4. Pull in large button common component, titled: "Submit" (separate story for routing/functionality/validation)
     - Update the common component with the following disabled state: background-color: #D6D7D9
     - Default state: disabled

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/440446462/inspect#project_console

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left
     - Use general done button a11y
- Programmatically set page title as "Ask for your claim decision page" and mark as Header 1
- Mark "Ask for your claim decision" as Header 2

**Checkbox**
- accessibilityLabel= Text value 
- accessibilityHint= "Confirms that you have submitted all evidence that will support your claim"
- accessibilityRole= “checkbox”
- accessibilityState= Denote when checked vs. unchecked

**Submit Button**
- accessibilityLabel= "submit" 
- accessibilityHint= "submits your claim request"
- accessibilityRole= “button”

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/20/2021 - A couple of small bugs I'm tracking in the test runs so I'll go ahead and let this one through.

Padding on the right of the bulleted list needs some work. Some phones have an issue, others don't.
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18797

Some minor accessibility issues for some Android phones.
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18799
