### ISSUE TITLE
Claims File Upload page | Section 3

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17510]
## User story
As a user, I want the ability to ask the VA to start evaluating my claim if I don't have any more documents to submit.

## Acceptance Criteria
1. On the File Upload page, below the File Request list, create a section that would display an alert for the user to ask the VA for their claim decision
     - Pull in the mobile alert CC
2. Style & UI matches design
     - Title: "Ask for your Claim Decision"
     - Description below
     - Large button CC, titled: "View details" (separate story for routing)
3. Implement rules for when this alert should display: 
     - This will appear when the Claim is in step 3 of 10, and if claim.attributes.waiverSubmitted is false or null.

Note for dev: Connect w/ Patrick on AC # 3 (see comments below). 

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/432623517/inspect
![Screen Shot 2020-12-15 at 4.17.21 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/0712c490-4814-4131-a76c-6b3b77b61b61)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Mark "Ask for your Claim Decision" as Header 3

**View Details Button**
- Title= “view details”
- accessibilityHint= "navigates to the claim decision details page"
- accessibilityRole= “button”

## Dev Checklist
- [ ] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
@bridgethapner will this alert always display on this page? or will it be service-driven (example scenario: if a user has uploaded all of their file requests, would they still see this?)

**Comment by msmanak** [comment]
make sure the upload process is easy for a blind person. iOS doesn't have a way to announce if the thing was captured correctly. @bessgreen

**Comment by bridgethapner** [comment]
Looping in @lexicalninja about your question @bessgreen -- Patrick, can you easily tell if the Ask for a Decision feature is service-driven or always on the web? I'm 99% sure it should be always on...but we should do whatever the web is doing.

**Comment by lexicalninja** [comment]
It shows up if its in phase 3 (out of 10, not the reduced 5. So the first development phase) and if claim.attributes.waiverSubmitted is false or null.

Have the person who grabs the ticket ping me and I will send the page and go over the relevant code with them

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/11/2021 - Moving to Design QA.
