### ISSUE TITLE
[PM] Create product outline for VA Notification Preferences

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#17528]
## Background
We will begin work related to adding VA notification preferences to the profile soon and need to create a Product Outline.

## Tasks
- [x] [Create product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)

**Comment by mshea0606** [comment]
@Samara-Strauss can you please add an estimate to this ticket? Thanks!

**Comment by Samara-Strauss** [comment]
Done https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md
