### ISSUE TITLE
Submit claim decision request (UI & FE validation)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17520]
## User story
As a user, I want to be able to tell the VA to start evaluating my claim if I don't plan to upload additional evidence.

## Acceptance Criteria
1. On the "Ask for your claim decision page", the checkbox must be selected in order for the **Submit** button to be enabled
2. Upon hitting **Submit**, the screen will be replaced to display a success message
3. Pull in mobile alert CC:
     - Update the common component with the following success state: border-left: #2E8540
     - Style & UI match designs
4. Back button routes to the first screen of the Claims File upload flow
     - The Info Alert for 'Ask for your Claim Decision' should no longer appear 
     - claim.attributes.waiverSubmitted is true

## Designs
Launch page with active Submit button: https://adhoc.invisionapp.com/d/main#/console/20546460/440446462/preview
Success message: https://adhoc.invisionapp.com/d/main#/console/20546460/440796656/preview
![Screen Shot 2020-12-17 at 3.10.13 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d7a4d89a-4da8-401e-8efb-ee8b8293f9b4)
![Screen Shot 2020-12-17 at 3.09.11 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b696b224-4428-4a0c-8a0a-69727dc79474)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left (custom a11y)
     - accessibilityLabel = "back"
     - accessibilityHint= “Navigates to the file upload page”
     - accessibilityRole = “button”
- Programmatically set page title as "claim request confirmation page" and mark as header 2
- Mark "Request received" as Header 2

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/13/2021 - Good on both iOS and Android.  Moving to Design QA.
