### ISSUE TITLE
[Product Research] Audit/score VA.gov Search results relevance

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#17534]
## High Level User Story
As a product manager, I want to know how "effective" VA.gov search is based on query results relevancy/precision.

## Goals
- To understand how helpful VA.gov search (as powered by Search.gov) is at helping veterans and site users accomplish their goals (e.g., get answers, complete tasks)
- To determine what level of relevancy/precision is acceptable for VA.gov search.
- If it is found that VA.gov search is not "effective," determine if optimization and tuning is possible by Search.gov to improve VA.gov search.

## How To Conduct this Research/Analysis

- Leveraging a version of the "Precision analysis" framework outlined in ["Search Analytics for Your Site"](https://rosenfeldmedia.com/books/search-analytics-for-your-site/) authored by Louis Rosenfeld.  At a high level, that framework consists of:
  - Measuring the number of relevant search results divided by the total number of search results. It tells you how many of the search engine’s results are good ones. 
  - To test precision, we will develop a scale for rating each result that a tested query retrieves, based on the information the searcher provided. The scale rating:
   - Relevant (r): The result’s ranking is completely relevant.
   - Near (n): The result is not a perfect match, but it’s clearly reasonable
for it to be ranked highly.
   - Misplaced (m): It’s reasonable for the search engine to have retrieved the result, but it shouldn’t be ranked highly.
   - Irrelevant (i): The result has no apparent relationship to the query.
- We will then calculate precision for each query using three simple standards—strict, loose, and permissive— to reflect a range of tolerances for different levels of precision.
  - Strict: Only results ranked as relevant were acceptable (r).
  - Loose: Both relevant and near results were counted (r+n).
  - Permissive: Relevant, near, and misplaced results were counted (r+n+m).

## Acceptance Criteria

- [x] The precision analysis framework (weighted scoring model) is expressed in a spreadsheet format, with the top searches to be scored included. (assigned to @johnhashva)
- [x] The framework is reviewed and approved by the S&D team (e.g. this model works) and a member of the analytics team (@assigned to @denisecoveyduc)
- [x] The raw analysis (e.g. the searches/scoring) is conducted (assigned to @denisecoveyduc)
- [x] The data is synthesized into insight about the effectiveness of VA.gov search (assigned to @johnhashva) 

## How to configure this issue
- [x] **Labeled with `discovery` and `research` and `team-name`**

**Comment by denisecoveyduc** [comment]
Sprint 38 we will begin this work knowing that it will likely roll over into Sprint 39 given the size of the effort

**Comment by denisecoveyduc** [comment]
Adding the summary for team review @srsuddath @mgleo Please review one more time on your own and highlight any questions, thoughts, etc.  Please indicated completion with a thumbs up reaction when complete. Thanks [VA.gov Search Analysis Report - 2020.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5796786/VA.gov.Search.Analysis.Report.-.2020.pdf)
