### ISSUE TITLE
[Discovery] Create Conversation Guide

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#1753]
## Goal
Create a conversation guide to moderate Claim Status Tool research sessions

## Acceptance Criteria
- [x] Conversation Guide has been created and added to Github repo
- [x] Conversation Guide has been reviewed with the team
- [x] Share Conversation Guide with Perigean (Slack or via Research Tracker)

**Comment by smoonpeyes** [comment]
@kevinstachura Have you linked the conversation guide to the Perigean research project tracker? I think that's the last step before closing this ticket.

Conversation guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/discovery-SEP-2019/conversation-guide.md

**Comment by kevinstachura** [comment]
Conversation Guide has been shared with Perigean.
