### ISSUE TITLE
[Design] Submit MyVA wireframes for copy review

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#17530]
## Background
After we finalize the mobile and desktop wireframes we need to have the copy reviewed.

## Tasks
- [x] Submit wireframe to Peggy for review
- [ ] Iterate and finalize copy

**Comment by mshea0606** [comment]
@tressaellen @callen2563 Can you add an estimate to this ticket? Thanks!

**Comment by Samara-Strauss** [comment]
Depending on how far we get with wireframe finalization this week, we might have to move this one until after break.

**Comment by Samara-Strauss** [comment]
Officially moving this out of sprint 37. We're not going to be ready yet. I would rather spend the time getting the information on the dashboard right than worry about rushing to get ready for copy.

**Comment by mshea0606** [comment]
@Samara-Strauss ok, yeah that makes sense.

**Comment by tressaellen** [comment]
This will now be tracked in [this epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18991), so I am closing this ticket.
