### ISSUE TITLE
STEM: Remove `stem_applicant_email` Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#17551]
As a developer, I need to remove the `stem_applicant_email` feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. This feature flag was created in #17363.
2. UAT has been completed for this effort as of 01/25/2021.
3. The new functionality is live in production with no need remaining need for the toggle.
4. The limited production rollout is completed as of 01/25/2021.

## Acceptance Criteria
1. The feature flag `stem_applicant_email` is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5821

**Comment by sonntag-adam** [comment]
In all environments, testing passes QA.
