### ISSUE TITLE
Stop recording _all_ contact info save failures as `address-save-failure`

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#17556]
When a VA PRofile transaction fails, we are always recording the `error-key` with an `address-save-failure` suffix without checking to see if it actually _was_ address that failed:

https://github.com/department-of-veterans-affairs/vets-website/blob/482d6fa322be32e699c8c6919392c6d85c4aede7/src%2Fplatform%2Fuser%2Fprofile%2Fvap-svc%2Factions%2Ftransactions.js#L139

We should:
- [ ] continue using this suffix if the transaction was an address save failure so we don't mess up our GA stats
- [ ] use different suffixes if phone numbers or email addresses fail to save

**Comment by joanneesteban** [comment]
Hello! Checking in here to see if/where you might need support from VSP Analytics?

**Comment by erikphansen** [comment]
@joanneesteban no help needed! This one is actually done.
