### ISSUE TITLE
[Discovery] Complete Research Synthesis

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#1755]
## Goal
Synthesize research data to understand why veterans are submitting Decision Reviews through the Claim Status Tool so that we can make recommendations

## Acceptance Criteria
- [x] Key findings have been identified and opportunities to improve veteran experience
- [ ] Create Research Readout and share with team
- [ ] Conduct session between Research and PM to discuss findings and additional future enhancements

**Comment by kevinstachura** [comment]
Research Summary has been created and is located here: 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/discovery-SEP-2019/research-summary.md

@azwilling - for awareness

**Comment by YanaRoy** [comment]
see ticket #2687
