### ISSUE TITLE
[Analytics] Can we make the address validation errors table clickable so we can see a more detailed report?

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#17552]
## Background

Back again with another request related to the [address validation dashboard](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/_u.date00=20201209&_u.date01=20201215/).

Is is possible to make the errors table (below) clickable so I could drill into this table and see what errors are occurring on what days? This would be super helpful in determining whether an issue is consistent over time or seems to occur as the result of an event (eg. database is down; there's a bug that was introduced; etc).

<img width="711" alt="Screen Shot 2020-12-16 at 12 47 06 PM" src="https://user-images.githubusercontent.com/34068740/102386493-21896580-3f9d-11eb-80eb-fc59a433f91e.png">

## Tasks

- [x] Acknowledge receipt
- [x] Let Samara know if this is possible
- [x] If possible, implement the change

**Comment by Samara-Strauss** [comment]
cc/ @mshea0606 for awareness

**Comment by bmcgrady-ep** [comment]
Hi @Samara-Strauss - I added the link in the table, so you can further drill-down into the metrics. Let me know if you need anything else.

**Comment by Samara-Strauss** [comment]
This is great. Thank you!!

**Comment by mshea0606** [comment]
Thanks @bmcgrady-ep !
