### ISSUE TITLE
Access for Jim Ray

### ISSUE THREAD

**Issue by jimiray** [department-of-veterans-affairs/va.gov-team#17570]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > James Ray

- Please Provide your email.
   > jim.ray@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >  VSP Identity team, Sr. Rails Engineer, Oddball

- Requesting SSH key authorization?
   > YES

   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+uFzdnV/IWXvrgwx+INoM3/BjMWdKcY5jHMucnW7ow1KVzhGwxeqZ0JA7O8cu2frh7nimksOSoQLahcaEwyYB41T9DblGKVH4CJWL6qXlR4zGol/YK8ChFAOeZGzCLKiy5+kuVqePY8Oz371pkf35FXkZCek3GmlsAl8X9u0tJfKaGve5t1XNm9nl5nJF185V/KMbruA+X7BntlqjxQ1UObIxFsBWXBwPiQ9cJweIlpIAv8oU/8KSQj6qdIE2xvG9dmAUfrjVHvijJRoq6DCOuxaGlsFXI1/oIixslqYRlCxNzr+7Ws05j+b4QtKQSeqo6/SDPJLs+dLu10/U8lLBCmOqMeBWB8NlY/k0bmJOfjRqijmYE6LZYe0aekEkZnUO5w6GLJRVEu6S8OIfAGx5X8bCIAD7nLDfF75CD8/T8x5ximfvVWJSB2BwYFFKNkp+/wrLO+wDJBTN17LyPW3nB28AEwwSLvzRmBD41L9i54BErIaI9U1D8LoxWXxBl80= jim.ray@oddball.io
```

- Grant AWS Console access?
  > YES
  - I would like to request additional READ ONLY access into EC2, Load Balancers, AMIs, security groups, S3, API Gateway, direct connect, VPC, Route 53, S2S VPN, VPGs, (essentially all the networking components such as route tables, IGs, etc), and cloudtrail. Their may be more later, but this is a good start. The reason I am requesting this is because I am trying to perform a security review of the entire implementation of SSOe. I also am currently troubleshooting logging for the SSOe solution which requires me to be able to see load balancers and other instance data associated with the cloudwatch logs. Each of the permission requests above are strictly associated with reviewing each of the components that are involved with the SSOe solution and determining where we have security gaps and troubleshooting gaps in SSOe return logs.

**Comment by tskinn** [comment]
@Jeff-Hayter 
Name: James Ray
COR: Jeffrey Hayter

**Comment by tskinn** [comment]
@jimiray you should have access to the socks proxy now. Reach out in slack if you have any issues. Once Jeff gives the go ahead we will get you accses to AWS.

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS.
