### ISSUE TITLE
[FE] Record more info to Sentry when users encounter a 301 error from VA Profile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#17572]
## Background
Investigate if 301 errors are FE's fault or if it's a VA profile issue. Also, we need to record information in Sentry when users encounter a 301 error from VA Profile.

## Tasks
- [ ] Record more info to Sentry when users are unable to add a contact info record due to a 301 error

**Comment by erikphansen** [comment]
Quick follow up: Sandra and I did a screenshare with Joshua Lindsey from the VA Profile team. He showed us that the call to `GET` contact info from VA Profile returns a mailing and residential address for a user. Then when they make an update to their address, VA.gov makes a `POST` when it should be making a `PUT`. We need to figure out why VA.gov acts as though the user does not have an address on file in these situations. At this point I'm honestly not sure what data we could record that would shed light on this issue. But I think if we're going to record more info we should be doing it _only_ when we see these 301 errors from VA Profile, _not_ every single time a user attempts to add an address.

**Comment by erikphansen** [comment]
I'm closing this one. Based on what we learned today, @sanlouise has [merged a fix](https://github.com/department-of-veterans-affairs/vets-website/pull/15411) that should resolve the majority of the 301 errors. Early next week we can take a fresh look at the types of save errors we are still seeing in GA and figure out which ones to attempt to resolve next.
