### ISSUE TITLE
Build Decision Review API Service Integration

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1757]
## User Story or Problem Statement
As a Veteran, I want to ensure the information I entered via an online submission method has been processed so that I can ensure my request has been received for review.

## Goal
To Build a service integration with the lighthouse Decision Review API within vets-api

## Objectives or Key Results this is meant to further
- Create integration points with higher review API
- Allow vets-api to submit a higher review for the veteran
- Wrap up response in a digestible format

## Acceptance Criteria
- [ ] Build `service.rb` file with integrations to Higher Review endpoints
- [ ] Build `service_exceptions.rb` file to include error map for exceptions returned from upstream
- [ ] Create configuration file and update settings file with routing/version data
- [ ] Create Virtus model Response models for data returned by service calls

**Comment by SMLuthi** [comment]
Im currently investigating whether this can service can be added straight into the `lib` folder as has been the practice in the past or if this needs to be built out as a module as seems to be standard practice for external services. Until this question is answered, this work is blocked.

**Comment by SMLuthi** [comment]
This integration is currently blocked due to testing purposes. Once all the endpoints are exposed on the dev environment cassettes can be written and the integration can be completed.

**Comment by SMLuthi** [comment]
The lighthouse has "finished" their integration of their endpoints on staging. This ticket is now unblocked and can hopefully be completed.
