### ISSUE TITLE
Access for Benefits API Team

### ISSUE THREAD

**Issue by gpbowman-git** [department-of-veterans-affairs/va.gov-team#17587]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   Cecilia.Lee@va.gov
- Please provide your name.
   Greg Bowman
- Please Provide your email.
   gregory.bowman@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   Benefits Intake API (Lighthouse), lead developer, Liberty IT Solutions

- Requesting SSH key authorization?
   YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMJ6xjp3bq8lf9H2BwteIvBQyVbBlNAriMWlfX+sE2irQiAWg5CyB3Cm5+uQ7SwC5v00oAfwf/AvIRchToVuYraZvBTqBdOwBHsitefhTWkCFjk3ehwUtvA0567stla5vtvzL+w9dCeVpWA+vBaVBxfPKc8on6/2ie/w8bZ4vIWAAxMaeDTpDiEqsiYyKcwb62j0nBvODJtiwWoq70UFSFGlYbBuYSbYMSo+yPBJ6yH/Ugrm7t5Q5BtuKNXTS5NlJ+1JwOGpNv36zLIUO4IjP8BiaxC9YTECM5cdQTpZQfPISKGTiMchXVPuqiCfG2RmtWjFOp7EcnbMUckPHS06PXJByd3asXuW8Ts0UKWl+cKnhDqx+I2E31I9Md9Olox1m/0k/kLqPW2JOHK2CbWGtTfJOqMiFYSH+kAoFzHzbkLt5SLaI3nZE6gbzMAO9aC3hCfxPVOZc/mUVT0AY1ucAyF9PWQYi32BlQGu2U2LNYTQWB0AbSSIwdOTcEJJFYJBk= AzureAD+GregoryBowman@DESKTOP-ID8ISVV

```

- Grant AWS Console access?
  YES
  - What AWS services do you need access to and why? 

Mike Bastos asked me to create a ticket and tag Julian Severino (@jsev-io) to explain the typical workflows that we need to support the Benefits Intake API in production. We primarily need read access to the vba_documents_upload_submission table in order to check statuses, pull guids, and check error details. On very rare occasions we might have to perform updates on records in that table, but that is not ideal and would be discouraged and used only if absolutely necessary.

Mike Bastos has supported this API and has used the Rails console in the past to query the model and pull the necessary data.

@jsev-io Please reach out to me with questions. Mike said you had some ideas about how to give us what we need while limiting out production access.

**Comment by mleclerc00** [comment]
Hi @gpbowman-git

Can you confirm that you have all of the access needed so I can close this ticket.

**Comment by gpbowman-git** [comment]
I have the necessary access. Thank you!

**Comment by jhouse-solvd** [comment]
See the comment above from Gregory. 

Closing.
