### ISSUE TITLE
[Vagrant] Nginx startup error related to "sentry10.vfs.va.gov" makes testing revproxy changes difficult

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#17585]
## The Problem
An nginx startup error relating to sentry10 dns makes testing revproxy changes in vagrant difficult.

### Steps to Reproduce
1. Get latest code from `devops` repo on the `master` branch
2. Builds revproxy in vagrant 
```APP=revproxy-vagov vagrant up --provision-with build```
3. Deploy revproxy-vagov-dev in vagrant
```CONFIG=revproxy-vagov-dev vagrant provision --provision-with deploy```
4. ssh into vagrant box
```vagrant ssh```
5. change to root user
```sudo su -```
6. Attempt to start nginx
```/usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf```

**Expected Result**
nginx starts properly

**Actual Result**
An error is observed in the log:
```
[root@localhost nginx]# cat /var/log/nginx/error.log 
2020/12/16 19:54:15 [emerg] 10946#10946: host not found in upstream "sentry10.vfs.va.gov" in /usr/local/openresty/nginx/sites-enabled/website_server.conf:143
```
`openresty` is not running:
```
[root@localhost nginx]# service openresty status
nginx is stopped
```
Nginx cannot be manually run:
```
[root@localhost ~]# /usr/local/openresty/nginx/sbin/nginx -c /usr/local/openresty/nginx/conf/nginx.conf
nginx: [emerg] host not found in upstream "sentry10.vfs.va.gov" in /usr/local/openresty/nginx/sites-enabled/website_server.conf:143
```

## Extra Context
A simple workaround exists: remove the `sentry10` location directive from the `website_server.conf` nginx config and restart nginx.

## Work to be Done
- [ ] Fix nginx startup error such that vagrant can once again be used to test revproxy changes

**Comment by jbritt1** [comment]
@omgitsbillryan is this work still relevant / necessary?

**Comment by omgitsbillryan** [comment]
AFAIK, yes. I ran into this a few months ago I think, when testing some kind of new revproxy feature.

**Comment by jbritt1** [comment]
Will this still be relevant once we finally sunset the old Sentry stuff?

**Comment by omgitsbillryan** [comment]
I'm not sure w/o digging into this. At the least it's related, so I'll go ahead and link that here https://github.com/department-of-veterans-affairs/va.gov-team/issues/16156

**Comment by jbritt1** [comment]
Opening a convo on this one with the team: https://dsva.slack.com/archives/CTYQL39FE/p1655907899502919

**Comment by jbritt1** [comment]
Vagrant is very rarely used by our team and others, testing revproxy changes is pretty easy/safe in dev, sentry should be sunset and this would be a non-issue anyway. Closing.
