### ISSUE TITLE
Up/Down arrow functionality for iOS picker

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17599]
## User story
As an iOS user, I want to see up/down arrows when navigating through form field entries so I can more easily jump to the previous/next fields. 

## Notes for dev: 

The Up/Down arrows that display in the iOS dropdown picker should do the following, when selected:
     - The dropdown menu closes
     - The cursor moves to the previous field (if the user selected Up) or the next field (if the user selected Down)

There are 3 possible scenarios to account for regarding _when_ these arrows should display:
     1. The dropdown menu is _not_ a form field, or it is a form field with a single entry. In this case, the arrows would not display at all. Example: Past Appointments > Date range picker
     2. The dropdown menu is part of a form field, and that field is nested between other fields. In this case, both arrows would display. Example: Mailing Address > State
     3. The dropdown menu is part of a form field, and that field is either the first or last field in the sequence. In this case, only one arrow would display (Down arrow if the field is first in the list, or Up arrow if the field is last in the list). Example: Edit Address > Country 

## Acceptance Criteria
1. Update the native iOS pickers so the up/down arrows only display on form field options. The arrows should be hidden from the following picker(s):
     - Past Appointments > Date Range picker
2. The Up/Down arrows should display on form fields that are nested between other fields. This includes the following pickers:
     - Edit Address (U.S. or Military Base) > State
     - Edit Address (Military Base) > APO/FPO/DPO
     - COVID-19 Vaccine Form > Will you be in this zip code for the next 6 to 12 months?
3. The Down arrow should display and the Up arrow should be hidden on form fields that are the first entry field on the form. This includes the following pickers: 
     - Edit Address > Country
4. The Up arrow should display and the Down arrow should be hidden on form fields that are the last entry on the form. This includes the following pickers: 
     - Direct Deposit > Account Type
     - COVID-10 Vaccine Form > Are you interested in getting a COVID-19 vaccine at VA?
5. Implement functionality for the Up / Down arrows with the following UX:
     - Selecting the Up arrow closes the picker and moves the user's cursor to the previous field on the form
     - Selecting the Down arrow closes the picker and moves the user's cursor to the next field on the form

## Designs
Example UI with no arrows:
![Screen Shot 2020-12-16 at 11.04.32 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c6f7b4cb-c475-41f5-bb09-0bb262344a7e)

Example UI with both arrows:
![Image from iOS (8).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4f4bd2b6-4565-4a52-ba4b-0ee9bc5ee540)

**Comment by digitalken** [comment]
Entering into TestRail and testing...
