### ISSUE TITLE
Use PurgeCSS to reduce the size of style.css

### ISSUE THREAD

**Issue by Clark-W-Griswold** [department-of-veterans-affairs/va.gov-team#17593]
Use PurgeCSS to remove unused styles from the render-blocking `style.css` after the content and application build.

There are still some build concerns to hash out.

**Comment by cvalarida** [comment]
Original conversation can be found at https://dsva.slack.com/archives/GLDNCMRSP/p1608076697013100

**Comment by cvalarida** [comment]
I originally thought PostCSS was needed, but we definitely don't need it. I had seen [PurgeCSS](purgecss.com) as a PostCSS plugin, but it's also standalone. I just ran our production `style.css` against the built output of VA.gov and saw we can reduce the size of the CSS file by ~50%.

![image.png](https://images.zenhubusercontent.com/599c8bb68f62dc7798c3b1dc/21aecc74-2320-4c15-8914-033e252f6646)

**Comment by cvalarida** [comment]
Updated the original description with information from :point_up:.

**Comment by cvalarida** [comment]
Took me a little while to think through the question of when to run this. What I came up with is the following

# The problem
`style.css` is used for site-wide styles, both on static pages and in React applications. To purge unused styles, we need to have access to both the HTML from the content build and the JS from the application build.

# The solution
Make each build (content & application) responsible for only the things in itself. This will prevent one build depending on the other.

What this means is that no application can rely on any styling in a site-wide `style.css`. If it uses a style, it must import it in its own CSS. Likewise, the content CSS will only be responsible for styles on the static pages.

# The approach
1. Make the content build create the `style.css`
1. Get each application building all the CSS it needs
    - This can be done in parallel with the first step
1. Create `site-wide.css` and `react-page.css`
1. Change the content templates to use the appropriate style sheets

## Content build
The goal here is to get the content build to also build the CSS it will use. This will remove the implicit dependency on the application build.

1. Copy all the site-wide `.scss` files to the content build repo
    - This assumes we're deploying the content from this repo right now
1. Build the `style.css` in the content build
    - The tricky part here might be the filename replacement in the HTML files
    - Right now, I believe we're using the webpack manifest, but this will move this file outside of that process, so it won't be in that manifest

## Applications building their own CSS
This is to remove the dependency on the content build's `style.css`.

1. Add importing `style.scss` into each application's style sheet
1. Add the [PurgeCSS PostCSS plugin](https://purgecss.com/plugins/postcss.html) to remove the unused styles in the application
    - There's also a [Webpack plugin](https://purgecss.com/plugins/webpack.html#installation), but since we're using the `postcss-loader`, we can use the PostCSS plugin

## Removing unused styles from static page CSS
Here, we set up the style sheets for static pages with the unused styles removed.

1. Run PurgeCSS on `style.css` against all the HTML in the content build to generate `site-wide.css`
    - For the prod build, this can use the same hash as `style.css`
1. Run PurgeCSS on `style.css` against a built application landing page's HTML to generate `site-wide.css`
    - For the prod build, this can use the same hash as `style.css`

## Change the content templates
Finally, the home stretch! Everything is in place now, so we just need to use all the CSS files in the right templates.

At this point, we'll have a `style.css` that we aren't using for anything except generating `site-wide.css` and `react-page.css`. We may or may not want to delete it. I don't know.

**Comment by laineymajor** [comment]
@ndsprinkle Does this tie into what you are currently doing? If so, how?

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new bug.
