### ISSUE TITLE
"Get Started" tools and docs that kick start development

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#176]
Epic for custom or off the shelf tools (oss or services) that help VSP teams quickly learn to build on the platform

## Objectives
- Consolidation
- Should be easy for engineers to update docs
- Should be easy to add images and diagrams

**Comment by jholton** [comment]
## Current list of relevant documentation:
[VA Digital Services Handbook](https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/index.html):
- Provides a general user-centered agile delivery processes.
- Does not address `vets-api` or `vets-website` specifically.
- The source of this documentation can be found [here](https://github.com/department-of-veterans-affairs/va-digital-service-handbook).

[Documentation for External Contractor teams working on the Veteran-facing Services Platform (README) ](https://github.com/department-of-veterans-affairs/vets-external-teams):
- Provides Code of Conduct, FAQ and standards for communications, tools and reviews
- Provides [introduction to Vets API](https://github.com/department-of-veterans-affairs/vets-external-teams/tree/master/DeveloperDocs/vets-api) for new teams
- Provides [introduction to Vets Website](https://github.com/department-of-veterans-affairs/vets-external-teams/tree/master/DeveloperDocs/vets-website) for new teams

[VA.gov Client application documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/):
- Provides documentation on getting `vets-website` up and running locally.
- Provides standards and requirements for visual design and form creation.
- Provides documentation of the client platform architecture and structure.
- The source of this documentation can be found [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/documentation).

[`vets-website` README](https://github.com/department-of-veterans-affairs/vets-website):
- Lists common commands
- Links to `VA.gov Client application documentation` as the source of other relevant documentation

[`vets-api` README](https://github.com/department-of-veterans-affairs/vets-api/):
- Provides basic 'up-and-running' instructions

Did I forget anything?
