### ISSUE TITLE
Claims & Appeals Service Integration | Overview screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17607]
## User Story / Task 
This is 1 of 3 stories to integrate with the Claims endpoint. This is a backend task - the associated UI is included in different stories. 

## Acceptance Criteria

1. Service integration with the claims API to call the following endpoint:
     - The overview screen that lists Active/Closed claims & appeals
2. On the overview screen, calling this endpoint should infer whether or not a claim/appeal is "active" or "closed" based on the status

## Related tickets:

- Claims detail integration: [#17626](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17626)
- Appeals detail integration: [#17627](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17627)

**Comment by bessgreen** [comment]
blocked: Claims & Appeals endpoint is returning a 500 error

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/19/2021 - Has been integrated.  Closing.
