### ISSUE TITLE
10-10EZ Address - VSA-QA Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#17614]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- [Product/Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/10-10ez-address-project/project-outline.md)
- [Product/Feature Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12474)
- [Product/Feature Flows](https://slack-files.com/files-pri-safe/T03FECE8V-F01HXA4D9ED/10-10ez_-_address_flow_2.2.pdf?c=1608764827-a9e58bad6184ac43)
- [Product/Feature Design prototypes](https://vsateams.invisionapp.com/share/3WZ5PNQSX67#/screens/435149169_Unathenticated-_Yes_-_V-2-2_?browse)

## Product-team SMEs

**Consistent with [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

## Proposed use-cases and Staging test-accounts

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **[Use Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/10-10ez-address-project/use-cases.md)** 

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Product references provided by Product Team.
- [ ] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 2 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@ala-yna , please work w/ your Team to [develop the Use Cases here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/10-10ez-address-project/use-cases.md) -- I just created this draft doc in your product folder and linked this ticket to it.

Feel free to ping me on Slack if you have questions/issues.  Thanks much!

**Comment by ala-yna** [comment]
@tlei123  - We're working on updating https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/10-10ez-address-project/use-cases.md

The team is currently QAing in an RI - I'll let you know when it's been merged into Staging :)

**Comment by ala-yna** [comment]
@tlei123 it has been merged! Would love to have you take a look if you have time, thank you!

**Comment by tlei123** [comment]
@ala-yna , all QA test-runs now completed.  QA-artifact links are below.

2 defects logged: #19364 #19365

TestRail links:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1108)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&group_id=822)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/186)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/187)

@pjhill , FYI, there's no Staging Review for this existing-feature update.

**Comment by ala-yna** [comment]
Thank you Tze! I'll have the team look into the defects. I believe the first has to do with the save-in-progress bugs that we've identified, which should be resolved by #18969.
