### ISSUE TITLE
Grouped items are read as separate announcements on VoiceOver

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17612]
## What happened?
1. iOS (VoiceOver): On the Personal Information page:
     - **Date of Birth** and the description below it are read as 2 separate announcements
     - **Gender** and the description below it are read as 2 separate announcements
2. iOS (VoiceOver) and Android (Voice Assistant): On the Appointments detail pages:
     - The Date and Time are read as 2 separate announcements
3. iOS (VoiceOver) and Android (Voice Assistant): On the Appointments detail pages that display a facility address:
     - The Address is read as individual announcements (one per line)

## Specs:
- Devices: Android: Galaxy S9; iOS:  iPhone 11

## Steps to Reproduce
1.
- Navigate with VoiceOver enabled on iOS to Personal Information page.
- Select "Date of birth". Notice how "Date of birth" is selected/announced separately from the data below it. 
- Select "Gender". Notice how "Gender" is selected/announced separately from the data below it. 
- **In contrast**: The Address, Phone, and Email ListItems are read as single announcements, as expected
     - Example for Fax number ListItem: "Fax. 3028887577" is a single announcement

2.
- Navigate with VoiceOver / Voice Assistant enabled to the Upcoming Appointments detail page
- For this example, select the Community Care appointment on Saturday, February 6, 2021 (however, this appears to be a universal issue across all Appointment Detail pages)
- On the Appointment Detail page, select "Saturday, February 6, 2021". Notice how it is selected/announced separately from the time on the next line: "11:53 AM PST"

3. On the same Appointment Detail page (see #2 above), select any line on the facility address. Notice how each line in the address is selected/announced separately.

## Desired behavior
1. VoiceOver will select & announce the entire ListItem together, rather than in separate lines.

2. VoiceOver / Voice Assistant will select & announce the Date and Time together. 

3. VoiceOver / VoiceAssistant will select & announce the entire address together. 

## Acceptance Criteria
1. When VoiceOver is enabled, "Date of Birth" and the corresponding user data is read as as one announcement. 
2. When VoiceOver is enabled, "Gender" and the corresponding user data is read as as one announcement. 
3. When VoiceOver (iOS) & Voice Assistant (Android) are enabled, the "Date" and "Time" on the Appointments Detail pages are read together as one announcement. 
4. When VoiceOver (iOS) & Voice Assistant (Android) are enabled, the facility address on the Appointments Detail pages is read as one announcement 

## Bug Severity
- 4 - Low

## Screen shot(s) 

![Image from iOS (11).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/55b82096-2ae6-4dc9-9a2f-9d2e1f2f2e7e)

![Image from iOS (10).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/59a2d616-5859-46cf-aaa4-4a2f00cf2e57)

![Image from iOS (9).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/662c77f4-55c5-43d2-a5d3-d3a1f5755748)

**Comment by digitalken** [comment]
PASS 2/19/2021 - Groups as single items now, both iOS and Android.  Closing.
