### ISSUE TITLE
Observability Tools: Centralized Logging - Ensure all production logs are readily available (using Loki/Grafana)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#17615]
## Problem Statement 
The current logging solution (CloudWatch) is insufficient for current needs. Due to a lack of available features and information being logged, developers rely heavily on the Platform Operations team. This makes it challenging to leverage log data to understand how infrastructure and applications are running so that developers can take steps to troubleshoot, fix, and improve software on their own. 

How might we improve developer experience on the platform with access to accurate and reliable logs?
How might we provide a single interface for searching and analyzing logs?
How might we streamline developer operations with easy-to-use web-based tools and data visualization? 

## Hypothesis or Bet
Our hypothesis is that by implementing centralized logging tools, we can promote enhanced observability for infrastructure services and components running in the production environment, empowering developers to better troubleshoot, debug, and improve the quality of their software.

## We will know we're done when... ("Definition of Done")
Platform crew and VFS Developers will be able to access logs collected by Loki through the Grafana UI in production. 
Here's the list of services that will be logging to Loki: 
- revproxy
- fwdproxy
- vets-API
- EKS services
- CMS

Note: AWS service logs like RDS, ELB, ECS will NOT be logging to Loki as part of this initiative. 

## Known Blockers/Dependencies 
_NONE_

## Projected Launch Date
End of Q3 2021

### Documentation
* **`PRODUCT_NAME`**: Logging (or "Centralized Logging")
* **Product Outline**: [LINK](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474593902/Centralized+Logging+using+Loki+and+Grafana)
* **README**: [LINK](https://github.com/department-of-veterans-affairs/va.gov-team/blob/9b03f1947528fd23d4e8aa8db8eccbd622303cab/platform/logging/readme.md)
* **User Guide**: [LINK](https://depo-platform-documentation.scrollhelp.site/developer-docs/Centralized-Logging-with-Loki-and-Grafana.619119010.html)

### Testing

* **Usability test**: Not relevant to this tool
* **Manual QA**: Not relevant to this tool
* **Automated tests**: N/A

### Measurement

* **Success metrics**: _see product outline, above_
* **Release plan**: _skipped_

## TODOs
- [x] Convert this issue to an epic
- [x] Add your team's label to this epic

**Comment by jhouse-solvd** [comment]
Interesting thread from Chris Dyer regarding his team's usage of CloudWatch queries to understand form submission success/failure rates: 

https://dsva.slack.com/archives/CBU0KDSB1/p1624380954178700

**Comment by mchelen-gov** [comment]
is there any dependency on BE Tools or CMS teams to implement this or will it be transparent for them?

**Comment by jhouse-solvd** [comment]
> is there any dependency on BE Tools or CMS teams to implement this or will it be transparent for them?

Forgive me for not providing an earlier reply, but this will be transparent for those teams. App logs for vets-API and cms are being collected with Loki and can be viewed in Grafana. 

Let us know if you need any additional info.

**Comment by jhouse-solvd** [comment]
This initiative has been successfully completed. All artifacts have been linked, and the solution is live. 

Closing.
