### ISSUE TITLE
Offboarding investigation of Margery

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#17617]
# Description

It seems that this individual: margery@searchenginecatalyst.com _may_ have access to Google Analytics, based on their involvement in this [analytics request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17386). It's possible they were just sent screenshots from someone else who has access, but **could you please check and confirm whether they do indeed have direct access to the VA's Google Analytics account?**

If they do have access, please provide information about where the request to grant their access came from, because I received a note from DEPO that it may not have gone through us.

--- 
 
## AC
 - [ ] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [ ] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [ ] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [ ] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [ ] Pagerduty access removed (if applicable) 
 - [ ] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by joanneesteban** [comment]
@rroueche confirmed no Google Analytics or Domo access.

**Comment by joanneesteban** [comment]
@rroueche closing this ticket. Let us know if you need us to audit access!
