### ISSUE TITLE
EDU Form: Update misc content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#17619]
As a developer, I need to update the content of various forms so that it the user experience is consistent across forms.

## Assumptions:
1. This update does not require a feature or prod flag; story will be reviewed by QA & UX locally or on a review instance before being merged at the beginning of the day for staging review prior to afternoon production deployment.
2. The content updates are based on the DEPO form labels here: https://design.va.gov/patterns/form-labels

## Acceptance Criteria:
1. In form 1990e:
    a. In chapter 3, `Sponsor's Branch of Service` is sentence case (Sponsor's branch of service)
    b. In chapter 3, `Sponsor's VA number` is replaced with `Sponsor's VA file number`
2. In form 0994:
    a. When the “Continue to VA Form 22-1990” button appears, the text is displayed on a single line

## Supporting Artifacts:
1.

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15453

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/tests/view/32667&group_by=cases:section_id&group_order=asc&group_id=51)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by amyknox** [comment]
UX Review 1 of 2: 

PASS - In form 1990e:
a. In chapter 3, Sponsor's Branch of Service is sentence case (Sponsor's branch of service)
b. In chapter 3, Sponsor's VA number is replaced with Sponsor's VA file number

I can't get to 0994 on staging. Will try tomorrow.

**Comment by watersemma** [comment]
UX Review 2 of 2: Pass!

**Comment by delli-gatti-michael** [comment]
Closing out
