### ISSUE TITLE
[Research] Familiarize with backend set up of the online 10-10EZ

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#17618]
### Findings

**Endpoints**: 
- `POST /v0/hca_attachments`
- `POST /v0/health_care_applications`

**Schema**
- [src](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/10-10EZ/schema.js)
- [dist](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/10-10EZ-schema.json)

**Models**
- `HealthCareApplication`
- For Attachments:

  Uses CarrierWave to store in S3 before sending it to VOA.

  - `HCAAttachment`
  - `HCAAttachmentUploader`

**Services**
- `HCA::Service`
- `HCA::EnrollmentSystem`

**Destination**
- VOA (Veterans Online Application) / ES (Enrollment System) at the HEC (Health Eligibility Center)
  - More info: [DevOps Docs](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/Enrollment%20Service.md)
  - Wsdl: [Vets-API Config](https://github.com/department-of-veterans-affairs/vets-api/tree/master/config/health_care_application/wsdl)

**Processing**
- Attachments is created
- Form is submitted
- XML message is created (attachments are appended)
- Messages is sent
- Confirmation code is passed back to UI from ES

**Adding Address**
- New address should be inserted in `HCA::EnrollmentSystem::veteran_to_demographics_info`
  - [veteran_to_demographics_info](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/hca/enrollment_system.rb#L568)
  - The test expects a single address, this needs to be updated `spec/lib/hca/enrollment_system_spec.rb:951`

**Comment by mchelen-gov** [comment]
Some links to relevant BE code:

Code: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/health_care_application.rb
Tests: https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/request/health_care_applications_request_spec.rb
Swagger: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/swagger/swagger/requests/health_care_applications.rb
Swagger tests: https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/request/swagger_spec.rb#L431

**Comment by mchelen-gov** [comment]
meeting notes 12/18:
```
ESR API query
- fields
- attachment data

SOAP message
- validate for required fields (or return error)
- read ICN, grab record from MPI
- applies business rules
 - validates with other services (service connected disability ratings)
- sends resulting messages to VistA (preferred facility stations)
 - eligability status:
  - automated approval
  - pending
   - manual review


attachments come through as binary based on file type (pdf, doc)

how to add new field to ESR?
- first add in ESR
- then update FE

additional address field
- already in prod
- validation on formatting of address = all fields are present (state code, etc)
- business rules = UAM validation with post office
- the field is flagged as "unmailable" but the application is not failed

environments:
- dev, qa, prepod

testing & validation

on submission takes ~1 min
- login to UI
- all will be in pending state
- we can see field values

auth:
- whitelist for certificate

GFE postman submit request?
- dev, sqa
- preprod, prod are protected

our staging -> their preprod

testing for address field?
- stakeholder wants to test in staging
```
