### ISSUE TITLE
Google Tag Manager - Standardize GTM to Design System: Release Plan

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17621]
## Guidance

_This Release Plan Template is intended to help ensure your new VSP product or feature is ready for launch and will deliver the desired user outcomes._
* _In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necessary prior to going live._
* _In Phase 2, you will define the launch communications plan and post-launch KPIs. **You can close this ticket once you have completed Phase 2**._
* _Phase 3 is optional - you may use it to document post-launch results._

_Fill out the **Planning** sections to start, then the **Results** sections as you complete each phase of testing._

---

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- Desired date range or test duration: 1 quarter of GTM support
- Desired number of users: 25% of VFS teams
- The group(s) from which you'll recruit test users: VFS
- How you'll recruit test users: use the Collaboration Cycle during the Analytics process
- How you'll give test users access to the product: This should be automatic when they interact with Analytics during the Collaboration Cycle. Anytime they add analytics tracking to products that include components within the Design System, they should be using the GTM standardization templates
- What "Success" criteria will you look at launch? 

| Product Question to Answer                                                            | Metric                                                                                                                                                         |
|---------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Service Completion: Did VFS teams use our tags?                                       | % of live VFSs with standardized Google Tag Manager implemented                                                                                                |
| Health: Did the standardization decrease the need to customize events?                | (How many times did we customize the standardized metrics?) % of Platform Analytics fixes (bugs, or cont'd custom support) for standardized GTM implementation |
| Trust/Satisfaction: Is this making customer support more satisfying for our team?     | Platform Analytics quarterly team health                                                                                                                       |
| Trust/Satisfaction: How satisfied are the VFS PMs and FEs with using these analytics? | VFS Satisfaction                                                                                                                                               |
| Ease of Use: Is this making it faster for Platform & VFS teams to implement GTM?      | Time to complete Google Tag Manager customer support (_including testing_)                                                                                                          |
| Other: Are we helping the Design System team surface accessibility issues?            | Number of tagging requests where the VFS team isn't using a Design System component, but should be                                                             |

- How you'll measure your "Success" criteria? 
  - Collaboration Cycle Point tracker
  - Github issues - time to complete (w/in the `Stand by - VFS FEs` swim lane)

### Results:

- Number of users: x 	

- Results per your "Success" criteria:

- Number of bugs identified / fixed: x/x

- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no

  - If yes, what: lorem ipsum  

### Planning:

- Desired launch date: March 2021
- Post-launch KPI 1:
- Post-launch KPI 2:
- Post-launch KPI 3: 

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with VSP handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by jonwehausen** [comment]
@joanneesteban Please find the latest design system documentation, along with the tentative sprint cycle where each code will be embedded.

**Comment by joanneesteban** [comment]
Thanks for the documentation & update, Jon! The documentation looks great. I notice that the schedule continues to the middle of May? Can you please readjust what the expectations should be for this work to be completed by the end of March? This was originally a Q4 2020 Initiative and has been brought over to Q1 2021, which ends at the end of the month of March.

**Comment by jonwehausen** [comment]
### New tickets to potentially use for success measurement
- 23336
- 23163

**Comment by joanneesteban** [comment]
Initiative impact review was held on 5-27-2021. Planning to check in on our analytics again towards the end of Q3. Closing this ticket.
