### ISSUE TITLE
Claims & Appeals Service Integration | Claim details

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17626]
## User Story / Task 
This is 1 of 3 stories to integrate with the Claims endpoint. This is a backend task - the associated UI is included in different stories. 

## Acceptance Criteria

1. Service integration with the claims API to call the following endpoint:
     - Claim by ID on the details screen
2. A Claims detail page should display the pertinent information about the user's claim

## Related tickets:

- Claims/Appeals overview screen integration: [#17607](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17607) 
- Appeals detail integration: [#17627](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17627)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/9/2021 - Getting actual claims and appeals data rather than mock.  Closing as integrated.
