### ISSUE TITLE
Claims & Appeals Service Integration | Appeals details

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17627]
## User Story / Task 
This is 1 of 3 stories to integrate with the Claims endpoint. This is a backend task - the associated UI is included in different stories. 

## Acceptance Criteria

1. Service integration with the claims API to call the following endpoint:
     - Appeal by ID on the details screen
2. An Appeals detail page should display the pertinent information about the user's appeal

## Related tickets:

- Claims/Appeals overview screen integration: [#17607](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17607) 
- Claims detail integration: [#17626](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17626)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/10/2021 - Appeals details has been integrated.  Closing.
