### ISSUE TITLE
Notifications Service Integration

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17628]
## User Story / Task 
As a user, I want to receive push notifications from VA. 

## Acceptance Criteria

1. Service integration with the /mobile/push API
     - Make a call to display notifications on the user's device
     - For MVP, this includes notifications for appointment reminders

## Related tickets
- BE API implementation: [#16026](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16026)

**Comment by ashley-matthews** [comment]
This is being taken care of by https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/20515
