### ISSUE TITLE
Join Virtual Session | Android

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17633]
## Acceptance Criteria

1. For Android devices, the **Join Session** button links a url provided by the appointment data via(/v0/appointments)
     - The above link opens in the user's browser, out-of-app

**Note for dev**:
-  Requirement to only display the **Join Session** button within 30 minutes of the appointment start time is handled in a separate ticket.

## Related tickets
- Join Virtual Session | iOS: [#15762](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15762)

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432775466

## Accessibility Implementation Guidelines 
**Join Session Button**
- Title= “Join Session”
- accessibilityHint= “Navigates to the VA Video Connect appointment"
- accessibilityRole= “button”

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/11/2021 - Sending to Design QA.
