### ISSUE TITLE
Holidays are Selectable When Choosing Date/Time for Appointment Requests

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#17639]
Holidays should probably not be selectable when entering an appointment request.

**Comment by laurenernest** [comment]
@outerpress On the request calendar, are these greyed out dates what it should look like for holidays/non-schedulable days?
![Screen Shot 2020-12-17 at 10.14.43 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/b6ae0210-69d7-48b3-971f-281930c85cba)

**Comment by outerpress** [comment]
@laurenernest Yep, same disabled/grayed out style for unavailable appointments whether holiday or non-schedulable for any other reason

**Comment by laurenernest** [comment]
@saneshark Do we have access to this holiday date data or would it come back as any other unavailable date?

**Comment by laurenernest** [comment]
@jbalboni Do we have access to this holiday date data or would it come back as any other unavailable date?

**Comment by jbalboni** [comment]
I don't know of any data or requirements around disabling holidays.

**Comment by laurenernest** [comment]
Won't address at this time, but documented for future review.
