### ISSUE TITLE
Update a11y for in-app web view and profile pages - iOS accessibility issues

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va.gov-team#17647]
## What Happened?
1. With VoiceOver enabled on iOS, a11y for the refresh, left, right, or open in browser buttons are being read in the wrong order
2. With VoiceOver enabled on iOS, the a11yLabel for the right arrow button and open in browser button are being picked up incorrectly
3. With VoiceOver enabled on iOS, extra text/information is being picked up for the refresh button

## Specs:
- Device: iOS - iPhone XR (v.14.2) with VoiceOver enabled
- User: ben.morgan@id.me

## Steps to Reproduce
For 1:
1. With VoiceOver enabled on iOS, navigate to an in-app web view page
2. Select the refresh, left, right, or open in browser button
3. Note that Voice over is reading the a11y order as hint. role. label

For 2: 
1. With VoiceOver enabled on iOS, navigate to an in-app web view page
2. Select the right arrow button or the open in browser button
3. Note that VoiceOver is reading the a11yLabels as right arrow (for the right arrow button) and share (for the open in browser button) 

For 3:
1. With VoiceOver enabled on iOS, navigate to an in-app web view page
2. Select the refresh button 
3. Note that VoiceOver is reading "refreshes the page. button. refresh. sky(?)"

## Desired Behavior
For 1:
- With VoiceOver enabled on iOS, the a11y order will be read as label. role. hint

For 2:
- With VoiceOver enabled on iOS, the a11yLabel for the right arrow will be picked up as accessibilityLabel= forward. The a11yLabel for the open browser will be picked up as accessibilityLabel= “open in browser”

For 3:
-  With VoiceOver enabled on iOS, a11y for the refresh button will only be picked as:
     - accessibilityLabel= “Refresh”
     - accessibilityHint= “refreshes the page”
     - accessibilityRole= “button”

## Acceptance Criteria
- See desired behavior

## Bug Severity
- 4 - Low

## Linked Story (s)
- Story #17130

## Screen Shot (s) and Additional Information

**Comment by digitalken** [comment]
PASS 2/24/2021 - Sounds good on iOS.  Closing.
