### ISSUE TITLE
Upgrade Locust to 1.4.1

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#17650]
## User Story

As a VFS team engineer, I need an updated version of Locust in order to perform load testing on my endpoints in vets-api. Python 2.X is being sunset and it is becoming more and more difficult to maintain an environment that supports the very old version of Locust that is currently prescribed in the devops repo.

## Expected Behavior

Locust 1.4.1 configured for use in the devops repository.

## Acceptance Criteria

- [x] Locust 1.4.1 is configured in devops/loadtest
- [x] Existing load tests contained devops/loadtest have been refactored to work with Locust 1.4.1

**Comment by rjohnson2011** [comment]
Update (1/6):
I have refactored the locust files to be compatible with the latest version of Locust and added a main.conf file to run the file, which is in line with the previously use test_args files in each directory.
https://github.com/department-of-veterans-affairs/devops/compare/update-locust
After speaking with @pjhill we are going to go about executing each based on a Kanban style.
