### ISSUE TITLE
Initiative Kickoff [VSA Caregivers: Sign as a representative]

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#17660]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Attach all relevant artifacts to the ticket
- [x] Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] Shira will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] Kickoff meeting completed 
- [x] [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/initiatives/sign-as-a-rep/initiative-outline.md)
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from VSA Caregivers
- Product Manager (required): Alayna
- DEPO Product Lead (required): Ming
- Entire VFS team (recommended): Justin, Kevin, Jonathan, Mike C.
- Other specialists: Josh, Tze

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** No (?)

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

Wednesday, Jan 6th

**Comment by ala-yna** [comment]
@shiragoodman, let me know if you need anything else!

**Comment by shiragoodman** [comment]
scheduled for 1/6/2021 at 11:30 am ET

**Comment by shiragoodman** [comment]
hey @ala-yna and Caregivers team. Thank you for meeting with us today for your kickoff meeting and for answering our questions. After discussion, we think it would be best if your team/initiative went through a full Collaboration Cycle, however we could probably hold some of the reviews asynchronously if you would prefer. I have added your initiative to the Platform Collaboration Point Tracker as well. Please let me know if you have any questions.

**Comment by ala-yna** [comment]
Closing this - we met on 1/6
