### ISSUE TITLE
Test the Documentation for Cypress E2E Keyboard Helper

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#17664]
## User Story

As a VFS team engineer, I need clear documentation that describes best practice use and examples for implementing the Cypress E2E Keyboard helper on my product.

## Expected Behavior

Clear documentation for the E2E Keyboard Helper is discoverable and self-serve from beginning to end.

## Acceptance Criteria

- [x] Read through the documentation for E2E Keyboard Helper
- [x] Discover a product for which the keyboard helper would be useful
- [x] Implement a solution that uses the keyboard helper to perform an in-depth evaluation of accessibility
- [ ] Discuss gaps in documentation with Noah and work with Noah to fill in gaps

**Comment by pjhill** [comment]
- [ ] Check on the key event issues that were encountered in the first go around of this evaluation in Noah's latest push to his branch

**Comment by CBonade** [comment]
Noah had written a test for this that matched the descriptions of what he wrote up in the docs. The docs will need to be updated when this goes live to move the features listed as `experimental` into being merged with the other documentation.  Everything in that documentation is used in this test and the test seems to work flawlessly.
