### ISSUE TITLE
Add polyfill for ChildNode.remove()

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#17661]
IE11 does not support ChildNode.remove(), as seen on https://caniuse.com/childnode-remove:

![Cursor_and_Can_I_use____Support_tables_for_HTML5__CSS3__etc.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/c1d9bb2a-f004-4511-8d21-66c5c926fe26)

We should add a polyfill to `src/platform/polyfills/preESModulesPolyfills.js` so we don't have to worry about this function crashing IE11.

**Comment by timwright12** [comment]
PR for this: https://github.com/department-of-veterans-affairs/vets-website/pull/18586
