### ISSUE TITLE
Design Feedback - Staging Review - eBenefits - Personalized Career Planning and Growth (CH36)

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#17676]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- We appreciate all your hard work and trying to make improvements on current design patterns.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
-  Put the “Thank you for submitting” in a [success alert](https://design.va.gov/components/alertboxes#success-alert), moving forward we want the submitting alerts to be in the success style to help differentiate them from info alerts![Screen Shot 2020-12-16 at 1.44.37 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/063f96d8-20fc-4ca6-bdbb-ad3c5ef1c709)
- Put the “How long will it take” in [this style](https://design.va.gov/patterns/benefit-applications#after-you-apply) 
![Screen Shot 2020-12-16 at 1.33.31 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/c631788c-188a-4192-b3c6-8900ad0a6507)
- For the alerts, this is using a new design pattern that has not been tested. We agree that there is a need for a better pattern for alerts, especially looking at mobile. Our recommendation would be to do usability testing specific to alerts (A/B would probably great). More about this discussion can be found in [this Slack thread](https://dsva.slack.com/archives/CLY6Q69RV/p1608232916497200).

**Should:**

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by jason-gcio** [comment]
Must 1/ - Confirming that the "Thank you..." has already been moved
Must 2/ - Ticket #17699 addresses this
Must 3/ - Confirming next action items for these alerts with team
