### ISSUE TITLE
Design Intent Collab [Content & Localization - Translations | Spanish Corona Pages] -- Accessibility Feedback

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#17673]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
* Review the [VSP guidance and findings on localization](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/resources/localization/accessibility-for-localization.md)

**Consider:**
* Trying out the localization Codepen ( https://codepen.io/tpierce_402/full/wvWZJdB ) with one or more screen readers to get a sense for the correct and incorrect reading of localized content.

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by SKasimow** [comment]
@1Copenut Hello - please refer to ticket for work done to meet this requirement: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17918 for this requirement.


CC @youngfreezyVA

**Comment by 1Copenut** [comment]
@SKasimow Can you point me to any pull requests associated with issue #17918 ?

**Comment by SKasimow** [comment]
Adding in @youngfreezyVA to advise...

**Comment by youngfreezyVA** [comment]
hi @1Copenut here is the PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/15289
it is a WIP and incorporates suggestions from your codepen. here is the lang attribute being set:
https://github.com/department-of-veterans-affairs/vets-website/pull/15289/files#diff-87cfcd77dc2ca13698eebe19ce454bf18ca6c555f757e0759fbcf9155d02ced4R22
