### ISSUE TITLE
rename toolkit repo to match command name

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#17670]
Teletype requires the directory to match the command name.  This can make it difficult to develop on after a clone if the developers doesn't remember to rename the directory.  Rename the repo to match the toolkit name.

**Comment by alexpappasoddball** [comment]
@kfrz Looks like this is blocking the final pieces, any update on this one?

**Comment by alexpappasoddball** [comment]
@kfrz seeing this is done [here](https://github.com/department-of-veterans-affairs/vtk) if you are good we can close this ticket!
