### ISSUE TITLE
Contact Center Review for eBenefits - PCPG CH36

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17681]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Personalized Career Planning and Guidance or CH36 is where Veterans can complete a form and be contacted for career counseling and guidance.

### Launch Date
January 4, 2020

### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/contact-center/Contact-Center-Product-Guide-CH36_v12152020.pdf

### Product Video
Shared via Slack

### Product Video Transcript
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/contact-center/CH36-video-transcript.md

## Acceptance Criteria
- [x] VSP Contact Center Team QA has been completed 
- [ ] VSP Contact Center Team sends artifacts to appropriate contact centers
- [x] VFS team completes brief VSP Collaboration Cycle Feedback survey [link](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before)

**Comment by starlow00** [comment]
@jwoodman5 , drafts with suggestions attached. Questions, let me know!
[https://app.zenhub.com/files/133843125/7fc70621-9c0a-475c-bac0-8a02144c29cf/download](https://app.zenhub.com/files/133843125/7fc70621-9c0a-475c-bac0-8a02144c29cf/download)

[https://app.zenhub.com/files/133843125/4511f9c3-3285-47f8-aa06-a7d155446d81/download](https://app.zenhub.com/files/133843125/4511f9c3-3285-47f8-aa06-a7d155446d81/download)

**Comment by jwoodman5** [comment]
Awesome. Thank you, @starlow00!

**Comment by jwoodman5** [comment]
@jason-gcio The contact center team review is complete and suggestions are noted two comments above. I see the acceptance criteria mentions the Analytics & Insights team which is now separate from the contact center team. Do you mind if I update the A/C to reflect? Thanks.

**Comment by jason-gcio** [comment]
Sure thing, go for it @jwoodman5!
Thanks for the feedback, glad to have your sets of eyes on this.  Here is the revised version:
[Contact-Center-Product-Guide-CH36_v12182020.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5718347/Contact-Center-Product-Guide-CH36_v12182020.pdf)

**Comment by jwoodman5** [comment]
@jason-gcio I made that update to the A/C and checked out items off then assigned back to you for the final A/C item. Please let me know if we can do anything further to help. Thanks.

**Comment by jason-gcio** [comment]
@jwoodman5 - thank you!

**Comment by starlow00** [comment]
@clantosswett This appears to be one of those tickets (product guide and video) that needs to go to VEO review. Can you please assist me in making that connection? (cc @jwoodman5)

**Comment by Kimberley2019** [comment]
@jason-gcio @starlow00 I have just discovered that this has not been sent to VEO for their review.  I will get this over to them asap for their feedback and approval.

**Comment by Kimberley2019** [comment]
I have received the video from Jason Wolf and have sent the guide and video to the VEO Contact Center as of today.  I have informed them that feedback is needed by 5PM ET on 1/27/2021.  If no feedback is received, then we can proceed as is.

**Comment by starlow00** [comment]
@Kimberley2019 Here are the PPT and PDF with better images and larger text, all for readability. Questions, let me know!

[https://app.zenhub.com/files/133843125/681e625c-bca6-4f48-a7ad-5b59c9250b85/download](https://app.zenhub.com/files/133843125/681e625c-bca6-4f48-a7ad-5b59c9250b85/download)[https://app.zenhub.com/files/133843125/d93be0e7-e798-426e-a3c5-bd7a18a1c53f/download](https://app.zenhub.com/files/133843125/d93be0e7-e798-426e-a3c5-bd7a18a1c53f/download)

**Comment by Kimberley2019** [comment]
Thank you so much @starlow00 for getting this done.  I will pass along to VEO for their review and approval on the requests that they have made.

**Comment by Kimberley2019** [comment]
Ticket closed.  No other feedback or suggestions from VEO Contact Center.
