### ISSUE TITLE
Manually add FACILITY_MENU_NAMES for VISNs 1,7,8, and 20 (contingency plan)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17682]
## Issue description
As a contingency plan to the [discovery of a dynamic solution](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17256), we may need to manually add for FACILITY_MENU_NAMES for VISNs 1,7,8 and 20 so the node and data load processes are not blocked.

## Tasks
- [x] Manually add FACILITY_MENU_NAMES for VISNs 1,7,8 and 20 (list from Stan below in comment)

## Acceptance Criteria
- [ ] Facility builds for VAMCs in VISNs 1,7,8 and 20 include the side nav component.

**Comment by mmiddaugh** [comment]
[VAMC_Systems_InProgress.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5731599/VAMC_Systems_InProgress.xlsx)

**Comment by mpelzsherman** [comment]
Adding the following:

VISNs 1 (va-altoona-health-care), 7 (pittsburgh-health-care) and 8 (va-wilkes-barre-health-care) are already in the FACILITY_MENU_NAMES array.

VISN 20 is listed as "VA Fayetteville Coastal health care" in the spreadsheet. It will be added as 'va-fayetteville-coastal-health-care'.

**Comment by mpelzsherman** [comment]
For the AC, I assume "Facility builds" refers to DevShop instances?

**Comment by davidconlon** [comment]
@mpelzsherman you're looking at the wrong column in the spreadsheet for what should be in array.
VISN is column B.

Facility Builds refers to any case in which the systems are built.
Can be validated in a local build, staging, or DevShop because we don't want to publish in Prod.

**Comment by mpelzsherman** [comment]
Oops! Thanks @davidconlon .

I see there are many rows per VISN. I will add entries for all of them.

There is no column in the spreadsheet that contains the FACILITY_MENU_NAMES array entry. Unless I hear otherwise, I'll assume it's the plain language name, all lower case, hyphen-separated.

**Comment by davidconlon** [comment]
@mpelzsherman re: the names, I'd need to see what's already there, for erie, pittsburgh et al.
I think your hypothesis sounds possibly correct with the exception that they may drop the "VA". 

Can you include examples of the current naming convention that's already in drupal so we can confirm?

**Comment by mpelzsherman** [comment]
You can view the current list [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js#L9).

Copying & pasting here for your convenience:

```js
const FACILITY_MENU_NAMES = [
  'pittsburgh-health-care',
  'va-altoona-health-care',
  'va-butler-health-care',
  'va-cheyenne-health-care',
  'va-coatesville-health-care',
  'va-eastern-colorado-health-care',
  'va-eastern-oklahoma-health-care',
  'va-erie-health-care',
  'va-lebanon',
  'va-montana-health-care',
  'va-oklahoma-health-care',
  'va-philadelphia-health-care',
  'va-salt-lake-city-health-care',
  'va-sheridan-health-care',
  'va-western-colorado-health-care',
  'va-wilkes-barre-health-care',
  'va-wilmington-health-care',
  'va-altoona-health-care',
  'va-fayetteville-coastal-health-care',
];
```

**Comment by davidconlon** [comment]
yes - please use the plain language name, all lower case, hyphen-separated (including "va")

Can we update the AC's to fix "va-lebanon" to reflect the proper naming convention "va-lebanon-health-care" or should we create a separate issue for that?  I'm not sure what is involved in that.

**Comment by mpelzsherman** [comment]
👍  Thanks.

We can fix va-lebanon in this PR. It's just a matter of changing the entry on our end.

**Comment by mmiddaugh** [comment]
@SgardnerPMP can you or someone from your team confirm these build successfully?
