### ISSUE TITLE
Error |  Address Recognition: Confirm Unit Number

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17698]
## User story
As a user, I want the app to inform me if the unit number on my my inputted-address cannot be verified. 

## Acceptance Criteria
1. Create UI for when a user's inputted address cannot be confirmed with USPS because of some issue with the unit number 
     - This screen should display after a user has entered an address on the edit screen and hits "Save". 
     - Hide "Cancel" and "Save" buttons on this page
2. Pull in the [**No suggestions** error page](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17695) with the following modifications:
3. Update the copy on the mobile alert to match designs
     - Error message title: "Please update or confirm your unit number"
4. Re-send to validation
     - Context: Final submission only happens after a user picks a suggested address, or one comes back with over 90% confidence rating

## Testing
**Invalid address to trigger this error state:**
301 Mission St
Unit 1100-B
San Francisco, CA 94105

## Designs: 
https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/441187431

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Mark "mailing address" or "residential address" as Header 1

**Mobile Alert**
- Mark "Please update or confirm your unit number" as Header 2

**You Entered Section**
- Mark "You entered" as Header 2

**Edit this Address Button**
- accessibilityLabel= “edit this address”
- accessibilityHint= "navigates to the edit address page"
- accessibilityRole= “button”

**Use this Address Button**
- accessibilityLabel= “use this address”
- accessibilityHint= "Saves changes and navigates to the [personal information]/[letters overview] page"
- accessibilityRole= “button”

**Cancel Button**
- accessibilityLabel= “cancel”
- accessibilityHint= "Cancels changes and navigates to the previous page"
- accessibilityRole= “button”

## Dev Checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/12/2021 - Functionally works as advertised on Android and iOS.  Found a few issues with accessibility that I logged here:

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19952

Issues covered in bugs so I'm closing.
