### ISSUE TITLE
Error | Address Recognition w/ no suggestions

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17695]
## User story
As a user, I want the app to inform me if my inputted-address cannot be verified, so I can go back and edit it.

## Acceptance Criteria
1. Create UI for when a user's inputted address cannot be confirmed with USPS & there are no suggested addresses
     - This screen should display after a user has entered an address on the edit screen and hits "Save". 
     - Hide "Cancel" and "Save" buttons on this page
2. Style and UI matches design for this page
3. Pull in mobile alert common component
     - Title (in bold) with static copy below it
4. **"You entered:"** section
     - Copy in this section should match the user's input, formatted as an address  
7. "Edit this Address" button
     - Pull in Large Button CC
     - Selecting this button returns the user back to the edit page
8. "Use this address" button
     - Selecting this button will save this address, and return the user to the Personal Information screen  _or_ the Letters overview page (depending on where the user came from) with this address displayed
9. "Cancel" button
     - Selecting this button will cancel out the edit flow and return the user to the Personal Information overview page _or_ the Letters overview page (depending on where the user came from), without any changes saved

## Testing
**Invalid address to trigger this error state:**
121775 Florida Ave NE
Washington, DC 20002

## Designs: 
https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/441187433

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Mark "mailing address" or "residential address" as Header 1

**Mobile Alert**
- Mark "Please confirm your address" as Header 2

**You Entered Section**
- Mark "You entered" as Header 2

**Edit this Address Button**
- accessibilityLabel= “edit this address”
- accessibilityHint= "navigates to the edit address page"
- accessibilityRole= “button”

**Use this Address Button**
- accessibilityLabel= “use this address”
- accessibilityHint= "Saves changes and navigates to the [personal information]/[letters overview] page"
- accessibilityRole= “button”

**Cancel Button**
- accessibilityLabel= “cancel”
- accessibilityHint= "Cancels changes and navigates to the previous page"
- accessibilityRole= “button”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
## User story
As a user, I want the app to inform me if my inputted-address has formatting issues and provide suggestions for similar, valid addresses.

## Acceptance Criteria
1. Create UI for when a user's inputted address cannot be confirmed with USPS & there are no suggested addresses
     - This screen should display after a user has entered an address on the edit screen and hits "Save". 
     - Hitting "Cancel" will cancel the address input completely and return the user back to the Personal Information page
2. Style and UI matches design for this page
3. Pull in mobile alert common component
     - Title (in bold) with static copy below it
4. **"You entered:"** section
     - Copy in this section should match the user's input, formatted as an address  
7. Edit Address button
     - Pull in Large Button CC
     - Selecting this button returns the user back to the edit page
8. Checkbox to "Use this address" 
     - Pull in checkbox CC
9. Save button is disabled until the checkbox is selected
10. Selecting "Save" will return user to the Personal information screen and display their saved address

## Designs: 
https://adhoc.invisionapp.com/d/main#/console/20546460/437865413/preview#project_console

## Accessibility Implementation Guidelines 

## Dev checklist

- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by lexicalninja** [comment]
From talking with profile devs: 
Is there always an address suggested?
You will get just garbage suggestions and the UI will just say “Are you really sure you want to use that email?”

Would see a payload similar to this: 
```json
{
    "addresses": [
        {
            "address": {
                "addressLine1": "215 Jackson Way",
                "addressType": "DOMESTIC",
                "city": "Manzanita",
                "countryName": "United States",
                "countryCodeIso3": "USA",
                "stateCode": "OR",
                "zipCode": "97130"
            },
            "addressMetaData": {
                "confidenceScore": 0,
                "addressType": "Domestic",
                "deliveryPointValidation": "MISSING_ZIP"
            }
        }
    ],
    "validationKey": -1078597055
}

```

Notice the confidence score and delivery point validation values

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - UI Looks good, Accessibility has a couple of issues (common with all of these address stories.). Closing.
