### ISSUE TITLE
Front end for backend status (api.va.gov/v0/backend_statuses)

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#177]
## User Story
As a VSP stakeholder I want a [github like status](https://www.githubstatus.com/) page as a FE for api.va.gov/v0/backend_statuses
so that I can quickly see the status of all the upstream services.

## Acceptance Criteria
An independent status page exists @ somewhere like status.va.gov (or we can start a status page for the entire US gov va.status.gov)

**Comment by timwright12** [comment]
Note: CORS issue with https://api.va.gov/v0/backend_statuses needs to be resolved before this work can move forward. After that, it should be a pretty quick addition to the FE Support Dashboard

**Comment by timwright12** [comment]
PR for this https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/788

**Comment by timwright12** [comment]
I released this to the FE Dashboard, but we're still trying to find where the CORS policy is set: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/status/

**Comment by timwright12** [comment]
Issue filed with Ops to update CORS: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38044

**Comment by timwright12** [comment]
Speaking with Console Services, we think we found the CORS policy at:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L9
https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/application.rb#L55

Going to try and update it to see it gets us what we need
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/9397

**Comment by timwright12** [comment]
This is live: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/status

Closing out
