### ISSUE TITLE
Update appointments endpoint to return va and cc booked appointments

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#1770]
## User Story 
As a developer I want `GET /appointments` to return both regular VA appointments and Community Care booked appointments so that the FE has to make less calls.

## Acceptance Criteria
- [ ] `GET /appointments` return two lists, `va_appointments` and `cc_appointments`, depending on the `type` passed in

**Comment by jbalboni** [comment]
Can we close this?
