### ISSUE TITLE
Contact Center Review for Facilities Team: Facility Locator (map enhancement initiative)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17718]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The [Facility Locator](https://va.gov/find-locations/) is VA's single source of truth for customers to find details about all VA and VA-approved facilities, across VHA, VBA, and NCA and Community Care. It serves many purposes, from finding basic facility address and phone information to preparing for a visit, to understanding eligibility for community care.

This update is an initiative aimed at enhancing map functionality to improve usability and accessibility. It does not include major changes in workflow. 

### Launch Date
The changes are available in [Staging](https://staging.va.gov/find-locations/) and should be sent to Prod in the next few days. 

### Product Guide
[Product guide link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/Facility-Locator-product-guide-updated%2012.17.2020%20(1).pdf

### Product Video
*Please provide product video link* -> _Due to the straightforward nature of the application, we were previously told that a product video is not necessary for Facility Locator. If you determine otherwise, please let us know._ 

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] VSP Analytics & Insights QA has been completed 
- [ ] VSP Analytics & Insights sends artifacts to appropriate contact centers
- [ ] VFS team completes brief VSP Collaboration Cycle Feedback survey [link](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before)

**Comment by starlow00** [comment]
@jwoodman5 Attached Product Guide with suggested edits 
[17718_Facility-Locator-product-guide_12.17.2020_ST_122120.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5726408/17718_Facility-Locator-product-guide_12.17.2020_ST_122120.pdf)

**Comment by jwoodman5** [comment]
@mmiddaugh Can you please take a look at our suggested edits in the previous comment and let us know what you think? Thank you!

**Comment by mmiddaugh** [comment]
Hi @jwoodman5  thanks for the review. I've incorporated many of the suggested changes but left some words capitalized because of branding (such as Community Care) or to reflect the words on the screen (such as "Facility type"). The updated version is available at [Product Guide Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/17718_Facility-Locator-product-guide_12.17.2020_ST_122120.pdf). Also,  the application changes are now available in Production. Happy New Year!

**Comment by starlow00** [comment]
@clantosswett Following up on this, as @jwoodman5 and team would like to move some product guides forward. Do you know if has gone for VEO review?

**Comment by starlow00** [comment]
Hello @mmiddaugh (cc @Kimberley2019). Do you happen to have the original Word document for this, and would you mind sharing a copy as soon as you're able? VEO is asking for larger images, and it's much easier to work in a non-PDF format. Thank you for your time!

**Comment by starlow00** [comment]
Contacted Michelle Middaugh via Slack re. this ticket.

**Comment by starlow00** [comment]
Per feedback from VEO and @mmiddaugh, document has been updated in Google Docs at
https://docs.google.com/document/d/1-1qGhJZP3Gzt2vTs1MUAYGJjPNiP7_p8dGjFmYD4fmQ/edit?ts=6011a7e1#heading=h.ya1iws22tlcg

PDF attached[https://app.zenhub.com/files/133843125/f87a4b49-b9e6-4261-8573-c5d9df62c6c9/download](https://app.zenhub.com/files/133843125/f87a4b49-b9e6-4261-8573-c5d9df62c6c9/download)

(cc @jwoodman5)

**Comment by Kimberley2019** [comment]
Product Guide was sent over to VEO and they have until COB on 2/15/2021 to respond with any suggestions or questions.  If nothing is heard by then, then this ticket can be closed.

**Comment by Kimberley2019** [comment]
This ticket will now be closed.  No feedback from VEO by the indicated date.
