### ISSUE TITLE
Analytics Covid dashboard request - Vaccine Information Hub iteration

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17729]
# Covid Dashboard - Vaccine Content iteration

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.
- [ ] New dashboard
- [x] Iteration of current dashboard

### Iteration 1: 
**Iterate on the `How Veterans are viewing vaccine content` section.** 
- [x] Change the section title to `What vaccine topics Veterans are interest in` 
- [x] Change the chart title, `Total jumplink clicks to COVID-19 FAQ Vaccine content` to `Total Vaccine Information Hub jumplink clicks`
- [x] Chante the chart title, `Vaccine questions being asked` to `Vaccine Information Hub question clicks`
- [x] Clarify the difference between these two data points/labels on the 'Total jumplink clicks to COVID-19 FAQ Vaccine content` chart:

`Coronavirus vaccine`
`COVID-19 vaccine`

### Iteration 2: 
**Add another section to the `Vaccine Response` dashboard, above the `What vaccine topics Veterans are interested in` section, titled `How Veterans are engaging with the Vaccine Information Hub`.** 

- [ ] Add a funnel for information engagement/completion (this doesn't have to be a funnel per se, but can be the metrics that show this information.) Title this funnel or section: `How Veterans are engaging with the information`
_Discovery question for @JasonTheBearded @bsmartin-ep _: How can we show service completion for information engagement? Some ideas (using the [KPI framework](https://vfs.atlassian.net/wiki/spaces/~173922865/pages/614531245/VA.gov+Analytics+-+KPI+Framework) for Content products):
- Time on page (difference between page entries & exits - @bsmartin-ep has examples)
- Bounce rates
- Scroll depth
- Is it possible to show a funnel that shows how many people enter the page and then read the information? Would this even show a completed user journey? (Check in w/ @lalexanderson-dsva ) Examples:

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/087fa7c7-03a8-45aa-8bef-f944216c4ef9)

**AND/OR**

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/31293f69-7b6a-4b1a-bb9b-ac1c134c0a21)

- [x] Add a funnel for information calls to action completion (the call to action right now. This can & will change given new calls to action). Title this, `How Veterans are completing vaccine information calls to action.` 

Example: ( @bsmartin-ep have we shown auth & unauth dropoffs in the same funnel?)

![image.png](https://images.zenhubusercontent.com/5cbde0c0353363084a079083/1e474540-baba-43aa-a9f1-36ae7bd09400)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by JasonTheBearded** [comment]
@joanneesteban @bsmartin-ep are we tracking scroll depth on the Vaccine Hub page? I'm not seeing any events for the page, www.va.gov/health-care/covid-19-vaccine/

**Comment by joanneesteban** [comment]
@JasonTheBearded @lalexanderson-dsva @rroueche 

Notes from 1/8/21 Covid Dashboard Meeting:

Action Items:
- [ ] Vaccine funnel should be moved to Calls to Action. With this, clarifying the product title of Vaccine Research Volunteer. Will put subtitles.
- [ ] Retitling the funnels to button clicks to clarify sign in vs. not signed in
- [ ] Clarifying the numbers for users who are already signed-in
- [ ] Do we have the number of users who click the sign in button overall?
- [ ] Do the users click the VA.gov top sign in button?
- [ ] Ask Patrick: do signed-in users see different buttons?
- [ ] Clarify `Google/Organic`, `Google/CPC`, `links.gd/referral`, `direct/none`
- [ ] Add avg line to avg time on page chart

Insights:

- If data is accurate, the sign in button is being clicked by a very small percentage of this hub’s users.
- Chatbot has little usage compared to the information hub
- Question order should be looked at based on this data

**Comment by JasonTheBearded** [comment]
Action Items are complete @joanneesteban

**Comment by joanneesteban** [comment]
Waiting on feedback, and can close after Covid Meeting on Friday, 1/15. Thanks for your work here, Jason!

**Comment by joanneesteban** [comment]
Some insights:
So far in January,
- The average daily use of the chatbot for vaccine questions is 6.3 users
- The largest source of entry to vaccine pages has been through organic Google searches (no ads)
- Veterans are spending an avg. of 1.9 min on the Information Hub
- The 'Questions you may have about the COVID-19 vaccines' accordion is being used far less than the other two jumplink clicks
- There is a large discrepancy between the number of question clicks within the Information Hub
- There are 49.21% more Veterans _not_ signed into the Vaccine Interest page than those who are signed in when they start the form 
- Signed in Veterans who completed the form was 17% higher than Veterans not signed in.
- 30% of Veterans who start the Research Interest form have completed it.

**Comment by joanneesteban** [comment]
All discussed vaccine data/charts have been added. The Analytics team will be on stand by in case future iterations need to be made. Closing this ticket. Thanks for working on this, Jason!
