### ISSUE TITLE
Events display incorrect times on Outreach Hub

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17724]
## What happened?
When an Outreach Hub user selects a non-EST time zone for an event, it is incorrectly translated to EST on the FE.

[Drupal page](https://prod.cms.va.gov/outreach-and-events/events/philippine-and-pacific-islands-veterans-va-benefits-training-session)
![image](https://user-images.githubusercontent.com/55411834/102633830-35080e00-410e-11eb-8ae7-874a5b5b518e.png)

---
[Preview]( preview-prod.vfs.va.gov/preview?nodeid=15055)
![image](https://user-images.githubusercontent.com/55411834/102633855-3d604900-410e-11eb-80bd-94c621a482e8.png)

## Desired behavior
The intended behavior is to display time in the time zone selected by the user

## Acceptance Criteria
**Confirm functionality for both the Outreach hub events and VAMC events** 
- Event times on the [outreach event listing page](https://www.va.gov/outreach-and-events/events/) display in the time zone specified by the user 
- Event times on the individual event detail page in Outreach hub display in the time zone specified by the user
- Event times on the [VAMC event listing page](https://www.va.gov/pittsburgh-health-care/events/) display in the time zone specified by the user 
- -VAMC event times on the individual event detail page display in the time zone specified by the user

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by cmaeng** [comment]
Confirmed with the user that once published, it incorrectly shows as 9:00am EST on the Event List and Event Detail pages, even though the content in CMS is 9:00am Philippine time.

FE event list page: https://www.va.gov/outreach-and-events/events
![image](https://user-images.githubusercontent.com/60702623/102664248-57bb1680-4150-11eb-94b7-22f5d75484eb.png)

FE event detail page: https://www.va.gov/outreach-and-events/events/philippine-and-pacific-islands-veterans-va-benefits-training-session/ 
![image](https://user-images.githubusercontent.com/60702623/102663953-cea3df80-414f-11eb-83fd-db66e4eb1f62.png)

Have not been able to test if this is the same for VAMC pages.

**Comment by mpelzsherman** [comment]
Confirmed in prod.
