### ISSUE TITLE
General Analytics Request for PW

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#17720]
# General Analytics Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for ~Analytics Requested~ Request
- [ ] ~Analytics to Track Down~ n/a
- [ ] ~Which Product Questions are you trying to answer?~ n/a
- [ ] ~Additional Comments~ n/a

## Description
Who is this request for? 

- Jen Lee in PW

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for? 

    _this adds context for the data_
    - PW - Resources and support KPI DOMO dashboard https://va-gov.domo.com/page/1522082003
    
- What type of analytics support are you looking for?
  - [ ] Please fix product name. It should be "Resources and support," not "Resource and Support"
  - [ ]  Please add @bethpottsVADEPO  to dashboard analytics view.
    

## Timeframe for ~Analytics Requested~ Request
_Please provide the timeframe for the metrics you are requesting._
Week after Xmas holiday break is fine.

> Please leave the following blank

## Acceptance Criteria
  - [x] Please fix product name. It should be "Resources and support," not "Resource and Support"
  - [x]  Please add @bethpottsVADEPO / beth.potts@va.gov /  to dashboard analytics view.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by johnhashva** [comment]
@jenniferlee-dsva can I jump in to this request and get added to the dashboard as well?

**Comment by jenniferlee-dsva** [comment]
Sure! (I thought Brian had already added you, sorry.)

**Comment by bmcgrady-ep** [comment]
Hi @jenniferlee-dsva - Confirming receipt. Should I include Learning Center in the title of the KPI dashboard?

**Comment by bmcgrady-ep** [comment]
@jenniferlee-dsva - The KPI dashboard name has been updated and Beth Potts has been added. Feel free to reopen this ticket if you need anything else.
