### ISSUE TITLE
Calendar truncated at smaller screen sizes

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#17725]
The calendar is being cut off by the browser window at ~340px. Our smallest breakpoint is 320px so we should support that at a minimum.
Saw this on staging, Chrome Version 87.0.4280.88 (Official Build) (x86_64), zoom level 100%, cache cleared.

![staging.va.gov_health-care_schedule-view-va-appointments_appointments_new-appointment_request-date(iPhone 5_SE) (2).png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/273a7fef-411e-4766-b94b-a3058e9c8dea)

**Comment by laurenernest** [comment]
@outerpress Can you confirm this now looks as expected?

**Comment by outerpress** [comment]
Looks great! It's working and not truncated in Chrome.
