### ISSUE TITLE
Video link in appointment details

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1772]
## Story
As a veteran I want to be able to join my confirmed video / telehealth appointment from my appointment details page so that I don't have to check my email. (Veterans get video link email on day of request & 24 hours before video appointment).

## Current functionality
- Button is enabled 30 minutes prior to start time, until 4 hours after start time
   - The timezone is factored in, compares user local timezone to timezone of appt (think this is facility, but not positive)
- ~~If you're on iOS, there's a message that you must download an app (https://itunes.apple.com/us/app/va-video-connect/id1224250949?mt=8)~~
   - ~~Not sure if this is required for Android, it's not mentioned~~ (Separated into #2238)
- There is one type of video appointment, MOBILE_GFE, which does not display a link, it displays a message that you should join the session using the device provided to you
   - There's no time window for this message
## AC
- [ ] Video link in telehealth-type appointment details
- [ ] Veterans are able to click link to connect directly to their appointment within x time of appointment

**Comment by markgreenburg** [comment]
@rtwell I think we need a mock for where this link / button / etc. would go in the details page for telehealth appointments, and what the interactions around it would be. E.g., should it only appear within a given time from the appointment.

**Comment by jbalboni** [comment]
@markgreenburg @rtwell I added some info to the description that has the functionality used in the current app.

**Comment by rtwell** [comment]
This is what we're going to test next week— @lalexanderson-dsva for 👀 

![image](https://user-images.githubusercontent.com/12564977/65277208-694de280-daf7-11e9-9fd3-c3beb8160570.png)
![image](https://user-images.githubusercontent.com/12564977/65277232-74087780-daf7-11e9-9252-5cc8ba980460.png)

**Comment by narin** [comment]
Separated iOS app download prompt into new ticket since some design/content guidance is required: #2238
