### ISSUE TITLE
Inconsistent formatting for View Payment History table

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#17728]
## What happened?
When paginating through payments on the [View Payment History](https://staging.va.gov/va-payment-history/payments/?postLogin=true) page on staging with account `vets.gov.user+14@gmail.com`, the table formatting formatting and table length is inconsistent between pages, such as pages 5 and 6.

## Specs:
- Device: MacBook Pro
- Browser: Chrome
- Test User: vets.gov.user+14@gmail.com

## Steps to Reproduce
- URL: https://staging.va.gov/va-payment-history/payments/
- Test User: vets.gov.user+14@gmail.com
- Click on pagination links
- <img width="691" alt="Screen Shot 2020-12-18 at 11 41 17 AM" src="https://user-images.githubusercontent.com/3535749/102644534-989e3580-4126-11eb-8aee-81a74acd1acd.png">
- <img width="678" alt="Screen Shot 2020-12-18 at 11 41 29 AM" src="https://user-images.githubusercontent.com/3535749/102644564-a0f67080-4126-11eb-96ae-477405b74ba0.png">

## Desired behavior
Table styling (length, column width, etc.) should be consistent between pages

## Acceptance Criteria
- [ ] Payment history formatting is consistent between pages

## How to configure this issue
- [ ] **Labeled with Team** (`vsp-testing-team`, `vsa-ebenefits`)
- [ ] **Labeled with Practice Area** (`frontend`, `design`)
- [ ] **Labeled with `Bug`**

**Comment by jason-gcio** [comment]
Checking to see if the full width view (after removing the sidebar components) addresses these issues

**Comment by jason-gcio** [comment]
Looks great:
![image](https://user-images.githubusercontent.com/53826255/129944846-43717ed2-cba8-4f39-84c2-ab4e6c5c8b39.png)
