### ISSUE TITLE
Claim Source Addition to 526 Submissions

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#17727]
## User Story
As a VBMS user, I want to be able to see the claim source distinguished between VA.gov and other sources.

## Expected Behavior
We pass a parameter (not required) down to EVSS on all 526 submissions.  This can be hardcoded.

**Info from the EVSS email describing this:**

The code changes to support a claim source element in 526 submissions is now ready in the EVSS Dev (INT) and Test (PINT) environments.

This change is planned to go to Production on the evening of January 6th.

The new element (`claimSubmissionSource`) is optional in the 526 schema so you do not HAVE to provide it, but ideally both VA.gov and Lighthouse will start sending this as of January 7th.

Currently the name provided with the claimSubmissionSource will be reflected in the daily 526 report/spreadsheet produced by EVSS in a column with the same name.

Partners would need to be encouraged to incorporate new source element into form526 request payload when we are done with upcoming release:

“We've added a new source element in form 526 request payload. The schema has been updated to reflect this new element. The element is not a required field, is a string that captures the name of the calling application (Lighthouse, Va.gov etc.). In our schema form526.xsd, the element is displayed as:

`<xs:element name="claimSubmissionSource" type="xs:string" minOccurs="0"/>`

In an ideal request payload, the value will need to be included as:

```
{
                "form526": {

                                "claimantCertification": true,

                                "standardClaim": false,

                                "autoCestPDFGenerationDisabled": false,

                                "bddQualified": false,

                                "claimSubmissionSource": "Lighthouse",

                                "applicationExpirationDate": "2021-03-20T13:32:49+00:00",

                                "directDeposit": {

                                                "accountType": "CHECKING",

                                                "accountNumber": "xxxx",

                                                "routingNumber": "yyyyyyyyyy",

                                                "bankName": "zzzzzzzzzzzzzzz"

                                },
                                ...
                                ...
}
```

For VA.gov we would expect a value such as “VA.gov” (the previous default built in on the EVSS side) to be used. For Lighthouse, this could be a generic value such as “Lighthouse”, or you can use names for each front-end application you support to further distinguish between your consuming applications.

If no value is provided, this will show up in our report as “Source is not found”. Previously we always defaulted this to “VA.gov” and did not distinguish Lighthouse submissions.

## Acceptance Criteria
1. Tested with EVSS

**Comment by luke-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/disability-compensation-claim/bdd/form526_12.18.2020.xsd

**Comment by annaswims** [comment]
@luke-gcio I switched this over to a back end ticket

**Comment by annaswims** [comment]
code has been merged. I'll validate in staging after it's been deployed.
