### ISSUE TITLE
General Analytics Request for Covid Interest

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17726]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

Patrick B - Vaccine Interest Form
    
- What type of analytics support are you looking for?
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
Since launch

## Analytics to Track Down
- Number of authenticated vs unauthenticated clicks on Interest button

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by JasonTheBearded** [comment]
@bsmartin-ep for capturing the auth difference should I be looking at the event actions for 'www.va.gov/health-care/covid-19-vaccine/stay-informed/form/' and 'www.va.gov/health-care/covid-19-vaccine/stay-informed/form?postlogin=true'?

**Comment by joanneesteban** [comment]
@bsmartin-ep to send over info.

**Comment by bsmartin-ep** [comment]
@JasonTheBearded -

The `?postLogin=true` querystring will just tell you that the user triggered the login process FROM that page, which is probably not what you want.

Some options...

You can look at the click events on the buttons on https://www.va.gov/health-care/covid-19-vaccine/stay-informed:

### Sign In

Event Label = 'cta-button-click'
Event Action starts with 'Default Button CTA - Sign In'
Page path = 'www.va.gov/health-care/covid-19-vaccine/stay-informed'

### Continue without signing in

It looks like the CTA secondary button tracking is not live (FYSA @jonwehausen), but you can look at this event on the next page:

Event Label = 'no-login-start-form'
Page Path starts with 'www.va.gov/health-care/covid-19-vaccine/stay-informed/form'

---------------

You can also look at the login events and custom dimensions for the session.

Your best bet is probably looking for users with an Event Label regex `^login-success-.*$'` before whatever you want to track (maybe Event Label = 'covid-vaccination--submission-successful' if I'm reading this right?).

**Comment by joanneesteban** [comment]
Data is being tracked in #17729 . Closing this ticket.
