### ISSUE TITLE
Copy mismatch for View Payment History when there are no payments

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#17731]
## What happened?
The [prototype](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/338e991f-d104-4bf4-b040-ced7f18617a0/specs/) for the [View Payment History](https://staging.va.gov/va-payment-history/payments/) page includes a contact phone number, but this phone number does not appear on staging.

## Specs:
- Device: MacBook Pro
- Browser: Chrome
- Test User: vets.gov.user+4@gmail.com

## Steps to Reproduce
- URL: https://staging.va.gov/va-payment-history/payments/
- Test User: vets.gov.user+4@gmail.com
- `We don’t have a record of VA payments made to you` component does not display a contact phone number.

## Desired behavior
Payment History page should show contact phone number as shown in the [prototype](https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/screen/338e991f-d104-4bf4-b040-ced7f18617a0/specs/).

## Acceptance Criteria
- [x] Contact phone number is shown when there is no payment history.

## How to configure this issue
- [ ] **Labeled with Team** (`vsa-ebenefits`, `vsp-testing-team`)
- [ ] **Labeled with Practice Area** (`frontend`, `design`)
- [ ] **Labeled with `Bug`**

**Comment by jason-gcio** [comment]
We can’t find any VA payments made to you, or returned VA payments. Some details about payments may not be available online. For example, payments less than $1 for direct deposit, or $5 for mailed checks, will not show in your online payment history. If you think this is an error, or if you have questions about your payment history, please call 800-827-1000. 

VA pays benefits on the first day of the month for the previous month. Please wait at least 3 business days (Monday-Friday) before reporting non-receipt of a payment.
