### ISSUE TITLE
'No appointments' UI mocks

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1774]
As a veteran, I want an explicit indication when I have no upcoming appointments so that I don't think the tool is broken.

AC:
- [ ] Mock exists for no appointments

**Comment by jbalboni** [comment]
From @rtwell on another ticket:

This is a rough first draft. @peggygannon and @lalexanderson-dsva would love to get your thoughts on this. 

## Confirmed appointments

**VA Medical center** link would take the user to the facility locator 

**Go here to manage your pending appointments** would take the user to their pending appointments page

![image](https://user-images.githubusercontent.com/12564977/65171233-60d2aa80-da18-11e9-9eaf-53892f45aa95.png)

## Pending appointments

**VA Medical center** link would take the user to the facility locator 

**Go here to manage your confirmed appointments** would take the user to their confirmed appointments page

![image](https://user-images.githubusercontent.com/12564977/65171289-7ea00f80-da18-11e9-9abb-4b7ab5f70258.png)

**Comment by markgreenburg** [comment]
@goldenmeanie @rtwell these mocks probably need updating given that the content is filler and we're consolidating the pending & confirmed appointments into one list.

**Comment by rtwell** [comment]
I believe, given our new approach of a consolidated list of appts, we only need one screen for this:

![image](https://user-images.githubusercontent.com/12564977/67407823-13e97300-f586-11e9-8c51-7735d919b81d.png)
