### ISSUE TITLE
CT Redesign: Deliverable Prep	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17757]
Work with Leads to identify visuals to enhance  discovery deliverable
Create visuals
Gather feedback
Refine visuals

**Comment by amyknox** [comment]
Deck is here: https://boozallen.sharepoint.com/:p:/r/teams/benefitsintegrationplatform/education/_layouts/15/Doc.aspx?sourcedoc=%7BCE486B24-0C9C-4F2B-9422-EE012BFE3DED%7D&file=DRAFT_GIBCTProductRoadmapFY21.pptx&action=edit&mobileredirect=true&PreviousSessionID=c1642b8d-43ac-04b4-55dc-b59bbc3b35e2&cid=089c23d1-f1a0-4b6a-8a24-985d3863c79e&CID=7AC8675A-CDF7-41A6-813F-9D790E68BD33&wdLOR=c314620B1-DAAF-4AAC-BC85-6AA92972F561
