### ISSUE TITLE
Error UI when confirmed or pending appointment fetches fail

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1775]
## Story
As a veteran, I want to understand why I can't see any of my appointments when I know I've booked / requested some.

## Context
It's possible that the request to fetch either pending or confirmed appointments will fail (there is one call made for each of these two lists) for whatever reason. If we don't have a UI for this, the veteran will be confused as to why they can't see what they know to exist.

## AC
- [ ] When confirmed or pending appointment fetch fails, error messages show in tool to inform veteran of current situation.

**Comment by markgreenburg** [comment]
@jbalboni can you confirm that the fetches for both pending & confirmed appointments also retrieve all of the appointment details for each list? I.e., one call to retrieve appts + all details and another call to retrieve requests + all details, rather than separate calls for list and individualo appt details. Want to make sure I understand how many calls are being made so that we know what the full range of error cases is.

**Comment by jbalboni** [comment]
That's correct, though there are actually three calls:

- Get appointments from VistA
- Get booked CC appointments
- Get appointment requests

So that's potentially a little tricky of one of the first two fail, but not both, because we combine those into one page.

**Comment by markgreenburg** [comment]
@rtwell I believe currently we just show the standard 'something went wrong' messaging (@jbalboni can correct me if I'm wrong). Please let us know if you want a different error message when any of the `get va appointments / cc appointments / requests` service calls fail
