### ISSUE TITLE
CT Redesign: InVision Alignment & SOP

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17756]
Collaborate with developers to identify optimal use of InVision Inspect
Figure out whether to add team members to existing team or create new space, or 3rd unspecified option
Identify options for contractor access, if possible
Document general use guidelines in team Confluence for posterity

**Comment by amyknox** [comment]
Booz Sharepoint resource: [UX Staging Review activities](https://boozallen.sharepoint.com/:w:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/UX%20Assets/Process%20Docs/Initial%20draft%20of%20UX%20Staging%20Review%20Activities%20v2.docx?d=w72b93f5b8573404bac054aaebda1cc78&csf=1&web=1&e=lZQhLI)

**Comment by JenLJ** [comment]
UX Review Process - Draft referencing how review is conducted including how InVision Inspect is incorporated 

https://boozallen.sharepoint.com/:w:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/UX%20Assets/Process%20Docs/UX%20Story%20Review.docx?d=wec8e01672ca3426db0f484d95bb956a9&csf=1&web=1&e=BTvDpO

**Comment by JenLJ** [comment]
Received thumbs up/confirmation from devs and QA that UX can use InVision Inspect to convey the following:

- Margins, padding and spacing
- Size of element(s)
- Fonts
- Icons
- Colors

**Comment by JenLJ** [comment]
Potential format for UX Review tracker:  https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/UX%20Assets/Process%20Docs/UX%20Review%20Tracker.xlsx?d=w3c8f8a282c4546599d3d2a11680bbcdd&csf=1&web=1&e=usOOgf

**Comment by amyknox** [comment]
UX Review Process and Tracker both look great. 

@watersemma - do you have any input on or insights into "Figure out whether to add team members to existing team or create new space, or 3rd unspecified option"?

**Comment by amyknox** [comment]
Decided to add developers as VA.gov team members. Sent email to Santiago with request
