### ISSUE TITLE
CT Redesign: Features Follow-up

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17758]
Identify outstanding questions on features & work with team and EDU to unearth resolutions

**Comment by amyknox** [comment]
Features questions documented here: https://boozallen.sharepoint.com/:w:/r/teams/benefitsintegrationplatform/education/VAGov%20Document%20Library/Working%20documents/UX%20Assets/CT-Redesign/Features_Outstanding%20Questions.docx?d=we697e7c0529a4118b1e4d86317b63177&csf=1&web=1&e=ZANeZw
