### ISSUE TITLE
Mock & build Cancel appointment flows

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1776]
## Story
As a veteran, I want to be able to cancel my appointments and requests if my circumstances change so that I don't have to stand my provider up.

## UIs for cancel flow
- [x] Where to cancel from (i.e., how to access the cancel functionality and what it looks like)
- [x] What are the steps in the process (i.e., how to present cancel options to veterans)
- [x] What if a cancellation attempt fails? We presumably need to show some sort of error; do we need different screens based on any specific errors?
- [x] What if cancelling is not possible in a specific situation due to business rules? (_note: this is an edge-case where we could get a specific 'unauthorized'-type error back, but generally there should be no reason that a cancellation wouldn't be allowed_)

## AC
- [x] Mocks exist for UIs listed above
- [x] Mocks uploaded in GH or attached to this ticket
- [ ] Master sketch files updated with mocks

## Mocks:
Cancel button functionality in the appointments list:
![appointments-list](https://user-images.githubusercontent.com/24251447/67508568-ddc7f400-f656-11e9-9c2b-9b8e31cc0d66.png)

~Select a reason~ & confirm cancellation:
![VAOS-Your-appts-cancel-confirm@2x.png](https://images.zenhubusercontent.com/59b9397cb0222d5de47791dd/25a4a74c-95d2-4a00-b528-4b770d7547fc)

Note: we removed the reason question. Everyone was confused and it doesn't do anything. Reason is required on the back end so we will submit "I cannot make this appointment" silently.

If the cancellation works, they get this screen:
![VAOS-Your-appts-confirm-Cancel-Success@2x.png](https://images.zenhubusercontent.com/59b9397cb0222d5de47791dd/6eda60d1-8171-4031-868e-f858d56edebd)

If it doesn't work, they get this one:
![VAOS-Your-appts-confirm-Cancel-Error@2x.png](https://images.zenhubusercontent.com/59b9397cb0222d5de47791dd/0da0577a-551d-4602-8c91-12ed5b6d536f)

**Comment by markgreenburg** [comment]
@goldenmeanie can you please add a mock for the UI that should show if a cancellation attempt fails for whatever reason? I'm thinking that there isn't really more helpful info that we could show in that case, so probably just need to do something along the lines of existing va.gov patterns?

**Comment by rtwell** [comment]
@markgreenburg can we list the actual reasons that a cancel request couldn't happen?

I know one reason is that the clinic has disabled online canceling, but are there other error types we should capture here? like a network error, etc?

**Comment by goldenmeanie** [comment]
OP updated with new mocks for
- Cancel confirm
- Cancel success
- Cancel error

**Comment by markgreenburg** [comment]
If possible, use the 'broad' reason (@goldenmeanie do you remember what the reason text was?), or first available reason returned by the service (the cancellation reasons are pulled from a service, they're not static).
