### ISSUE TITLE
STEM AD: Delete stale applications

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17769]
As a developer, I need to delete form 22-10203 applications, so they are no longer processed.

## Assumptions:
1. Form submission storage includes the form submission and data saved as part of #17768.
2. DEPO has approved storage solution.

## Acceptance Criteria
1. This story is completed behind feature flag `stem_automated_decision`.
2. Form 22-10203 application submissions with a `processed_at` of greater than one year ago are deleted on a daily basis.

## Supporting Artifacts:
1. N/A

**Comment by shawkey-daniel** [comment]
As a developer, I need to delete form 22-10203 applications, so they are no longer processed.

## Assumptions:
1. This work is completed behind a feature flag as outlined in AC1.

## Acceptance Criteria
1. This story is completed behind feature flag stem_automated_decision.
2. A job is created to delete stale form 22-10203 applications.
   a.  Job will find saved form 22-10203 with created date of greater than one year ago.
   b. Job will delete found items.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/5740

**Comment by sonntag-adam** [comment]
Testing passes QA
