### ISSUE TITLE
STEM AD: Store application with applicant identifier

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17768]
As a developer, I need to store the form 22-10203 details on VA.gov for business logic to determine routing for future submissions.

## Assumptions:
1. This work is to be completed behind the feature flag `stem_automated_decision`.

## Acceptance Criteria
1. A table is created to store form 22-10203 submissions of VA.gov authenticated users.
2. Form details are stored in encrypted format.
3. Applicant UserId is stored as an identifier for retrieval.
4. Table will contain a status field with possible values of INIT, PROCESSED, DENIED.

## Supporting Artifacts:
1. N/A

**Comment by shawkey-daniel** [comment]
As a developer, I need to store the form 22-10203 details on VA.gov for business logic to determine routing for future submissions.

## Assumptions:
1. N/A

## Acceptance Criteria
1. A table is created to store form 22-10203 submissions.
2. Form details are stored in encrypted format.
3. One way hash of the applicant SSN is stored as an identifier for retrieval.
4. Controller method is available to store form submission.
5. Controller method is available to retrieve form based on one way hash of applicant SSN.
6. Controller method is available for deletion of stored form.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/5607
- https://github.com/department-of-veterans-affairs/vets-api/pull/5608

**Comment by sonntag-adam** [comment]
[Uploading... Screen Shot 2021-01-11 at 11.50.46 AM.png]

**Comment by sonntag-adam** [comment]
Testing passes QA
