### ISSUE TITLE
STEM AD: TIMS Work

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17772]
As a developer, I need to create a new TIMS doc type and corresponding spool file to record a permanent record of the STEM automated decision.

## Assumptions:
1. The new TIMS doc type name has been socialized and approved by the TIMS team.

## Acceptance Criteria
1. The new doc type "10203DNY" is created and supported in vets-api.
2. A spool file is created to support the new doc type.
3. The spool file contains all of the form 22-10203 details for future reference.

## Supporting Artifacts:
1. N/A

**Comment by shawkey-daniel** [comment]
As a developer, I need to create a new TIMS doc type and corresponding spool file to record a permanent record of the STEM automated decision.

## Assumptions:
1. The new TIMS doc type name has been socialized and approved by the TIMS team.

## Acceptance Criteria
1. The new doc type "10203DNY" is created and supported in vets-api.
2. A spool file is created to support the new doc type.
3. The spool file contains all of the form 22-10203 details for future reference.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-api/5644

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5644

**Comment by sonntag-adam** [comment]
Spool file denial created, mirroring contents of 10203 with the exception of 10203DNY and VA Form 22-10203DNY

![Screen Shot 2021-01-15 at 11.53.30 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d3455f7a-9b00-44dd-a3d4-c77c1b62d030)

**Comment by sonntag-adam** [comment]
Testing passes
