### ISSUE TITLE
Intro audits

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#17774]
## Issue Description
Since the VA.gov relaunch in 2018, we've made some updates to our approach to intros on the page (the top paragraph on each page that appears in a larger font - see image below for example).

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/0914ac58-291f-4c82-a7a1-2b1b60990a74)

- We've worked to shorten our intros across new pages because usability research tells us that many people skip intros when they read a page. We've also implemented a 1,000 character limit for intros within our Resources and Support section, and we'd like to match that in our benefit hub pages.
- We've also changed our wording from "Find out..." types of CTAs to "Read below to find out..." CTAs to make the direction of the intro more clear.
- We'd also like to do a sweep for any long sentences (>20 words) as a general Plain Language health check.

### What's needed

Going benefit hub by hub, audit the page intros and note the following for each:
- Page URL
- The total character count of the page's intro text
- Whether we need to edit to change from a more general "Find out" kind of CTA to a "Read below to find out" CTA.
- Any sentences in the intro that are >20 words

**Here are the hubs. You can go down the left nav to capture all the pages in each. Please use a separate tab in an Excel spreadsheet for each hub:**

- Health care: https://www.va.gov/health-care/about-va-health-benefits/
- Disability: https://www.va.gov/disability/eligibility/
- Education: https://www.va.gov/education/about-gi-bill-benefits/
- Careers and employment: https://www.va.gov/careers-employment/vocational-rehabilitation/
- Pension: https://www.va.gov/pension/eligibility/
- Housing assistance: https://www.va.gov/housing-assistance/home-loans/
- Life insurance: https://www.va.gov/life-insurance/options-eligibility/
- Burials and memorial benefits: https://www.va.gov/burials-memorials/eligibility/
- Records: https://www.va.gov/records/get-military-service-records/

 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @3obryandogs. Please review this ticket and let me know if you have any questions.

@brianalloyd @RLHecht FYSA Current writing needs on the debt management site are winding down, so @bethpottsVADEPO and I have discussed having Susan work on some of our backburner needs such as auditing intros for length for a bit.

**Comment by 3obryandogs** [comment]
Will do!

**Comment by 3obryandogs** [comment]
@DanielleThierryUSDSVA - please look at the first sheet. Let me know if this is what you have in mind.



[audit 1.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5726808/audit.1.xlsx)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @3obryandogs. Yep, this looks like it's on the right track. Thanks!

**Comment by 3obryandogs** [comment]
Danielle,
This file wouldn’t load in github. I hope you can access it.

Kind regards,
Susan

**Comment by brianalloyd** [comment]
Thanks for the update, adding this to our board for tracking purposes.  Thanks.

**Comment by lunascoop** [comment]
Here's the excel spreadsheet: 
[Intro Audit.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5912769/Intro.Audit.xlsx)

**Comment by RLHecht** [comment]
Iceboxing this

**Comment by FranECross** [comment]
It appears that the audit was completed; closing old ticket.
