### ISSUE TITLE
STEM AD: Add POA to 10203 Spool Documents

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17773]
As a VCE, I need to be notified when the applicant has a POA and is denied by automated decision, so I can notify the POA of the decision.

## Assumptions:
1. This work is completed behind a feature flag as outlined in AC1.

## Acceptance Criteria
1. This story is completed behind feature flag `stem_automated_decision`.
2. Power of Attorney (POA) field is added to table for [22-10203 form](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17768)
3. [Job](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17771) created for automated decision is modified to lookup and update POA field value from the EVSS service.
4. When the 10203 submission results in an Automated Decision, the [spool file](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17772) includes whether the applicant has a Power of Attorney or not (as seen in SA #1).

## Supporting Artifacts:
1. [10203DNY Spool Document with POA](https://app.zenhub.com/files/133843125/49bea521-e65c-4fab-b791-68e171c270dd/download)

**Comment by shawkey-daniel** [comment]
As a VCE, I need to be notified when the applicant has a POA and is denied by automated decision, so I can notify the POA of the decision.

## Assumptions:
1. This work is completed behind a feature flag as outlined in AC1.

## Acceptance Criteria
1. This story is completed behind feature flag stem_automated_decision.
2. POA field is added to table for [22-10203 form](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17768)
3. [Job](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17771) created for automated decision is modified to lookup and update POA field value from the EVSS service.
4. [Spool file](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17772) is modified to persist the POA value.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PRs:
- https://github.com/department-of-veterans-affairs/vets-api/pull/5666
- https://github.com/department-of-veterans-affairs/vets-api/pull/5706

There weren't any test users with mocked EVSS gi bill benefit info that also had a POA, so I've added a POA to the `stem-poa` vets-api-mockdata` branch. Using this locally requires adding the following to the `settings.local.yml` file:

```
evss:
  mock_vso_search: true
```

**Comment by delli-gatti-michael** [comment]
[Testrail Test Case](https://dsvavsp.testrail.io/index.php?/tests/view/44135&group_by=cases:section_id&group_order=asc&group_id=51)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by desireeturner** [comment]
We have requested test data to be able to test this on staging, but we don't know how long that request will take (it has taken a very long time in the past). That said, we're comfortable considering this done based on our local testing.
