### ISSUE TITLE
Bug: Articles listings and RS search listings are showing weird html tag text

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#17779]
## Bug: Articles listings and RS search listings are showing weird html tag text

This might be a content only bug on the `Get a Premium My HealtheVet account` article or it might be a FE bug. It's hard to tell, so need both Randi and Nick/Kelson to assess. 

**Severity: Low.** 

**What's happening?**
On the 'All articles in/tagged' list pages & on the RS search results listings, the intro text excerpt that appears in lists is showing `a&#` before the ellipses `...`

**Desired behavior:**
The intro excerpt should not display `a&#`  before the truncation ellipses. The text should pull from the intro text and use ellipses `...` to indicate truncation, at around the first 200 (or so) characters including spaces. 

### Search results screenshot:
![image](https://user-images.githubusercontent.com/43381063/102801190-dac3b300-4382-11eb-80d9-dce1c1ff37bb.png)

### All articles landing page screenshot:

![image](https://user-images.githubusercontent.com/43381063/102801446-3beb8680-4383-11eb-95d8-01847dc9b873.png)

**Comment by jenniferlee-dsva** [comment]
@brianalloyd - I connected this to the 1.1 learning center epic, but you can triage this for a post-1.1 sprint or a future bug sprint.

**Comment by jenniferlee-dsva** [comment]
@RLHecht - If this is a content bug, you might be able to fix this anytime.

**Comment by brianalloyd** [comment]
Thanks @jenniferlee-dsva for the find.  @RLHecht @kelsonic can you both take a look and advise if this is a FE or Content issue or both?  Please provide an estimate in support of grooming.  Thanks.

**Comment by jenniferlee-dsva** [comment]
I'm not sure this is a content source issue. This might be far fetched - but could it be somehow related to this platform issue re graph ql/content export? 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18955

I am really not sure, so do ignore if this looks obviously unrelated. @brianalloyd @kelsonic (Again, this is "Low" as far as bug severity goes.)

**Comment by ncksllvn** [comment]
Basically, each search result gets 200 characters to show under its title before we put the `...` in there. In HTML, some special characters are represented by multiple characters but display on-screen as just a single special character. What's happening is that the FE is truncating text in the middle of those characters.

**Comment by jenniferlee-dsva** [comment]
I'm not sure... Here is the intro text that is being truncated in the results. The ellipses symbol `... `is added after the word `a` and before the word `Premium`: 

![image](https://user-images.githubusercontent.com/43381063/105752034-cd1ac380-5f14-11eb-82df-79211cd3170f.png)

**Comment by ncksllvn** [comment]
Yeah it looks like that is no ordinary "a". I  was wondering about that too, so I looked at the underlying raw content. The source looks like this - ` how to upgrade to a&#xA0;Premium&#xA0;<strong>My HealtheVet&#xA0;`

Or here is that character rendered into this GH comment - a&#xA0;

**Comment by jenniferlee-dsva** [comment]
So many things about this is odd to me. Like why do we even bold "My HealtheVet"? We don't bold proper nouns or branded terms in general, I don't think, do we?  (@RLHecht )

**Comment by RLHecht** [comment]
@jenniferlee-dsva As our style we bold MyHealtheVet, ID.me, and DSLogon. https://design.va.gov/content-style-guide/bold-text

**Comment by jenniferlee-dsva** [comment]
Ah, thank you @RLHecht . I think I vaguely recalled that, but thought that was only for within the context of talking about signing in and not in all body content contexts. Np.

**Comment by kelsonic** [comment]
I found a good solution using that `he` library. I'm going to reduce the truncating characters from 200 to 190 though due to the lines going over 2 lines:

![image](https://user-images.githubusercontent.com/12773166/111510477-6eebaf00-8713-11eb-99ab-821b3d4c764b.png)

**Comment by brianalloyd** [comment]
Change looks good @kelsonic, had a good time following your thought process on this ticket from the above comments.  @jenniferlee-dsva would you like to validate in support of ticket closure?  Thanks.

**Comment by kelsonic** [comment]
Will need to be validated following daily deploy today 👍

**Comment by brianalloyd** [comment]
Validated, looks good @kelsonic thanks for the solid work as usual.
