### ISSUE TITLE
Integration for Benefit Summary Letter page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17785]
## User Story / Task
Integration for the Benefit Summary & Service Verification letter page. This page contains service-driven content.

## Acceptance Criteria
1. Benefit Summary & Service Verification letter page contains service-driven content in the following 5 sections:
     - Discharge type
     - Active duty start
     - Separation date
     - Monthly award
     - Service-connected rating
2. The data in these 5 sections should be identical on both the overview page AND in the corresponding .pdf download
3. If the user has more than 1 service period, update the UI on the overview page to display the 3 most recent service periods.
     - List these service periods by the most recent active duty start date
     - When a user has >1 service periods listed, they cannot opt into each period individually: they can either choose to **_include all_** of them in their letter, or **_exclude all_** of them in their letter. 
     - See attached screenshot for mock UI

## Related tickets:
UI ticket: [#13947](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13947)
Download letter: [#14886](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14886)
Bug: [#17764](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17764) 

## Designs
**UI when there are multiple service periods (AC #3):**

![updated-periods-of-service.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/de26ceae-163a-4f85-bab3-b1d3c391674e)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by keli13** [comment]
Military service data for Benefits Summary and Service Verification Letter(ex. has 1 period of service) currently does not match the data on Profile -> Military information(ex. has 4 period o service). This is likely due to mock data for the endpoint.

**Comment by digitalken** [comment]
Unable to test until it isn't mock data on this page. 1/21/2021.

**Comment by digitalken** [comment]
2/11/2021 - Integration is completed.  Closing.
