### ISSUE TITLE
alarm on sidekiq retries queue

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#17794]
there's an alarm for when the sidekiq queue is too big, but there's not one for the retry queue.

For example, we had a db issue and our workers couldn't start. When we got them starting again, the jobs failed and went  into the retry queue.

Our dashboards and alarms showed everything was good but we had thousands of jobs failing and retrying over and over. This wasn't obvious until viewing the /sidekiq stats (via setting up a ruby server to serve /sidekiq through an SSM port forward).

## Acceptace Criteria

- [x] Update [SidekiqStatsJob](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/sidekiq_stats_job.rb) to report [SidekiqRetry.new.size](https://github.com/mperham/sidekiq/wiki/API#retries)
- [x] Update [statsd-exporter-mapping.conf](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/statsd-exporter-mapping.conf) with new retry count
- [x] Create Prometheus alert rule (probably in devops repo) for retry size
- [x] Update the [Grafana Job queue dashboard](http://grafana.vfs.va.gov/d/000000013/job-queue?orgId=1)

**Comment by cbtkc** [comment]
All steps have been completed. Prometheus will need to be redeployed to pick up the new retry queue size alert.
