### ISSUE TITLE
Optimize Sentry 10 EBS Volume Disk Usage

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#17796]
## The Problem
Sentry 10 is continuously running out of disk space.

## Extra Context
- The `kafka` volume is suspiciously using 95 GB of data which doesn't seem right
```
[root@ip-172-31-0-230 sentry10]# docker system df -v
...
VOLUME NAME                                                        LINKS               SIZE
sentry-kafka                                                       1                   92.9GB
sentry-postgres                                                    1                   151.8GB

```
- [Slack conversation](https://dsva.slack.com/archives/CJYRZK2HH/p1608578651498100?thread_ts=1608572324.496500&cid=CJYRZK2HH)
- [Initial slack alertmanager alert](https://dsva.slack.com/archives/C24RH0W11/p1608484349177100)

## Work to be Done
- [ ] Discover if kafka is incorrectly configured in [sentry onpremise](https://github.com/getsentry/onpremise)
- [ ] Implement a long-term solution that prevents sentry 10 from running out of disk space

**Comment by jbritt1** [comment]
Has this been mitigated at this time?

**Comment by jhouse-solvd** [comment]
We've moved Sentry into EKS and upgraded the version. This is no longer relevant. 

Closing.
