### ISSUE TITLE
Add Link from Spanish Corona FAQ Page to English Corona FAQ Page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17808]
## **User Story**

As a spanish speaking vet or caretaker seeking information on the Coronavirus, I would like to be able to view the Corona FAQ page  in spanish. 

## **Scenario 1:**

Given I am viewing the Coronavirus FAQ page in spanish ( http://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/ )
AND
I click the link for english "Read this page in English"
THAN
I should be taken to the english version of the page (https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ )

## Acceptance Criteria

 - [ ] User can link to english version from the spanish versions of the Corona FAQs 
-  [ ] Accordion sections open and close on page when clicked
-  [ ] Accessibility checklist has been verified by dev
-  [ ] Data is being sent to GA

## **Lo Fi Mocks:** https://app.zenhub.com/files/133843125/551c44c5-1638-401e-a504-9192e9c42a9c/download

**Comment by youngfreezyVA** [comment]
@SKasimow this looks great, thanks for putting it together!
Let me know when this is ready for development

**Comment by SKasimow** [comment]
@youngfreezyVA Thanks! Per @DanielleThierryUSDSVA she expects to be able to publish the FAQs on Jan 8th and is checking on the Volunteer Research page. In the meantime though you should be able to work on the English pages/adding links and breadcrumbs in preview instance, right?

**Comment by youngfreezyVA** [comment]
yup, i can work on polishing up the appearance of the link against the mocks, the breadcrumbs come from the CMS.

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - can you confirm that text in links should have "English"  capitalized and "spanish" is lowercase (ie"Read this page in English")

**Comment by SKasimow** [comment]
@youngfreezyVA revised this ticket to address adding link on spanish page only (prior to 1/19)

**Comment by SKasimow** [comment]
Closing as completed.
