### ISSUE TITLE
Backend - distinguish between mailing and residential address to the health care application

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#17809]
Schema Change: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/557

## User Story

As a Veteran
I want to be able to distinguish between my mailing and home address on my health care application
While logged in or unauthenticated
So that I can be contacted in the best way by the VA.

See: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17618

## Expected Behavior

- An authenticated or unauthenticated user can have separate mailing and home addresses on the 10-10EZ

## Acceptance Criteria

- [ ] Requirements/Design documentation updated first before coding starts.
- [ ] Rigorously tested before being deployed to Production
- [ ] QAed by @tlei123

**Comment by tlei123** [comment]
@ala-yna  @kevinmirc , just in case this really is post-Staging-Review copy-validation, I've just added the key QA-requirement [per our post-mortem mtg] item to the top of this ticket's AC checklist.

IF this is actually before Staging Review, please just remove me from this ticket, and make sure requirements are updated before tasks are assigned to Engineers, then at least 2 Sprints before Staging Review open a Test Plan ticket for me to start planning.
