### ISSUE TITLE
Add error message logging to login_stats in the session_controllers

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#17801]
When we log a failed request in the session_controllers, specifically for the rails log: `Rails.logger.info("LOGIN_STATUS_FAILURE, tags: #{tags_and_error_code}")`, we don't give very good information when the error doesn't have a code (and is given the 'unknown error code', or '007'. We should add an `error_message` field to this, something like:

`Rails.logger.info("LOGIN_STATUS_FAILURE, tags: #{tags_and_error_code}, error_message:#{error&.message}")`

**Comment by bosawt** [comment]
Unfortunately we likely won't be able to see the results of this directly, it should just be that certain error messages are clearer now. I confirmed that we haven't seen the DoubleRender error lately though

**Comment by nsoutouras** [comment]
General tech debt
