### ISSUE TITLE
Loading screen for Direct Deposit

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17802]
## User story
As a user, I want to know that my bank account information is saving. 

Note for dev: loading screen for Letters is already built. original ticket: [#14725](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14725) 

## Acceptance Criteria
1. Selecting the "Save" button on the Direct Deposit edit page triggers a loading screen
2. Pull in the LoadingComponent common component 
3. This screen appears until the account information is validated and is ready to display on the Direct Deposit summary page
4. Copy: “We are saving your direct deposit information.”

## Designs
N/A for this scenario. Here is a similar design for the letters loading screen: https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/434431466_Letters_-Loading-

**Comment by komaly15** [comment]
please use the `LoadingComponent` common component for this loading screen

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/4/2021
Sending to design Qa.
