### ISSUE TITLE
Update bad link in 10-10EZ

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#17819]
**Description**:
A link on the 10-10EZ is directing users to a strange URL that doesn't resolve.

See: https://dsva.slack.com/archives/CMJ2V70UV/p1608653782131800?thread_ts=1608649525.130600&cid=CMJ2V70UV

**Reproduce**
- Start the 10-10EZ
- Navigate to Financial Information section
- Select “yes” to enter financial information
- See link

**Acceptance Criteria**:
Update link to direct to: https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits

![image (2)](https://user-images.githubusercontent.com/7391284/102912576-8fc1a280-444b-11eb-8cf6-ffc3e06c20ea.png)

**Comment by LinnJS** [comment]
Link to where this is located on VA.gov
http://localhost:3001/health-care/apply/application/household-information/financial-disclosure

**Comment by LinnJS** [comment]
Link that is in the application 
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/hca/helpers.jsx#L273

**Comment by LinnJS** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15463

**Comment by LinnJS** [comment]
Follow vsp-opertions chats [here](https://dsva.slack.com/archives/CJYRZK2HH/p1608657197013400)

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/15465

**Comment by kelsonic** [comment]
Whoops, sorry, closing my PR in favor of Justin's PR that was already up + approved: https://github.com/department-of-veterans-affairs/vets-website/pull/15463
