### ISSUE TITLE
IA Request [Authenticated Experience, Direct Deposit for Edu]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#17816]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After completion of usability/protyping, prior to moving to development

## Required Inputs:
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/README.md)
- [Link to mockups](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/)
- [Link to research readout/results](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing/dd-edu-synthesis.md)
- Link to [research history master-list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable

**SEO Keywords** - Provide a list of keywords used by your target audience when they talk about or search for your content
- Profile
- Direct Deposit
- Compensation
- Pension
- Education Benefits
- Benefits
- Fraud
- Change
- Update

**Suggested URL(s)** - Provide suggested URLs and any background or rationale
- https://staging.va.gov/profile/direct-deposit

**Suggested entry points** - What is the primary entry point for users to find your new content/tool 
- www.va.gov/profile
- www.va.gov/change-direct-deposit

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?
- N/A

## Definition of Done
- [x] Issue is created, tagged and assigned to VSP Product Support
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation

**Comment by mnorthuis** [comment]
@mshea0606 @sporeboy Can you drop a link to the Public Websites ticket here for reference and so we can connect the work?

**Comment by mshea0606** [comment]
[Content for Direct Deposit Landing Page #14367](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14367) [Mock](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/72860e86-bed9-4e10-8794-223ebb03794f/)

**Comment by mshea0606** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17826

**Comment by mnorthuis** [comment]
Hello,  I reviewed the provided artifacts and scope of this work, and no IA changes are needed. 

The Public websites team will update the content on the static landing page and link to the appropriate page within profile. 
The eBenefits technical team will be responsible for sunsetting and redirecting the existing tool within ebenefits.va.gov. 
No link/navigation component changes are needed within va.gov. 

Please let me know if there are any specific questions. You can close this issue if no follow up is needed.

**Comment by mshea0606** [comment]
Thanks @mnorthuis! cc @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Sounds good! Can we close this out?

**Comment by mshea0606** [comment]
@Samara-Strauss @sporeboy -  this has been closed
