### ISSUE TITLE
Investigate how bad link was introduced on 10-10EZ

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#17820]
Pre-req: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17819

**Comment by LinnJS** [comment]
This link was introduced in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/5456/files#diff-cd33826c40e2829da2e8fe3d0af464a5a4e0c2c9358bdf8f94aad6c101d9b226R96) on May 10, 2017

**Comment by bradl3yC** [comment]
@kevinmirc the domain vaftl.us expired and it was purchased by someone outside of the US.  
```
Domain Name: vaftl.us
Registry Domain ID: D773B6EB70F9447F5AC8BA9D69A56740A-NSR
Registrar WHOIS Server: whois.communigal.net
Registrar URL: www.galcomm.com
Updated Date: 2020-10-07T00:03:40Z
Creation Date: 2020-10-02T00:02:02Z
Registry Expiry Date: 2021-10-02T00:02:02Z
Registrar: Communi Gal Communications Ltd.
Registrar IANA ID: 418
Registrar Abuse Contact Email:
Registrar Abuse Contact Phone:
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Registry Registrant ID: C5C436946F6FA4719BD8C149DB19E262B-NSR
Registrant Name: Milen Radumilo
Registrant Organization:
Registrant Street: 17 Strada C. A. Rosetti
Registrant Street:
Registrant Street:
Registrant City: Bucharest
Registrant State/Province:
Registrant Postal Code: 010281
Registrant Country: ro
Registrant Phone: +40.213253054
```

**Comment by LinnJS** [comment]
Follow vsp-opertions chats [here](https://dsva.slack.com/archives/CJYRZK2HH/p1608657197013400)

**Comment by short000** [comment]
Security related POCs: @joeniquette, @f1337.
RE from @joeniquette: "This likely should be reported up through DEPO so they can coordinate a comprehensive review of all links within va.gov and our forms... POCs are Fleet, myself, then probably Andrea (filling in for Nancy), Dror, Kevin, and Rachel."

**Comment by ala-yna** [comment]
@joeniquette / @f1337 - wanted to follow up and make sure this was on your team's radar.

**Comment by ala-yna** [comment]
Gotcha. @drorva, your thoughts? Where/what team should this go to?

**Comment by drorva** [comment]
my understanding of the sequence of events.
* This used to be "VHA Innovation Future Technology Laboratory" see https://web.archive.org/web/20181230113618/http://vaftl.us/
* At some point they moved out of that domain and let it expire
* Someone else grabbed it. 
I guess the best defense is to catch the invalid link when the domain expired, but other than that, I don't think there's a way for us to tell if a link is going to where it was intended or not.

**Comment by joeniquette** [comment]
There are automated ways to maintain domain information, then bounce this off of registered links within the codebase, then ensure none of the domains are out of compliance (not owned by who we expect them to be owned by). It should come down to two parties, platform ops and the group that adds links to their platform component. It is not enough, in my opinion, to expect that all domains are being maintained by other parties, we must take responsibility for where we are sending users, or not send them to those locations at all.

One hiccup to review is dynamically created links, this still however can be automated, it's just not as easy as the above. 

I recommend we create a "status check" which performs domain inventories (registered to va.gov and within our code bases), checks expired certs too while we are checking them, and then checks for any discrepancies. This should/cold create some type of alert, either a github action or slack notification, both? Certainly easier to create than most people may have thought and it avoids what could end up being some fairly significant issues.

**Comment by drorva** [comment]
This sounds like a big can of worms since there are at least two types of teams that create content
* VFS teams as part of the apps they are creating
* CMS content creators. We're expecting to have tens if not hundreds of facilities generating their own content.
Specifically with the second group it sounds like it'll be a challenge to make sure that links are compliant.

Example: a facility links to a local event hosted by the city. The city moves their domain. How do ensure it's legit without a manual review?

**Comment by mchelen-gov** [comment]
@drorva Agreed, maybe we should spin off some discovery tickets around these?

**Comment by joeniquette** [comment]
There will certainly need to be a limit in terms of responsibility, but otherwise this is part of hosting a platform on an external space. We must strive to ensure there is as little manual review as possible, hopefully only when alerts are sent to the team which indicates a potential issue.

**Comment by rroueche** [comment]
@drorva and @mchelen could you stub out those "discovery" tickets you mentioned and label them with a security label, so we can start to have a backlog of security-improvement tasks to pick up when we make room for it in the future?

**Comment by mchelen-gov** [comment]
Added a few things to @drorva 's excellent summary:

1. There is a 1010EZ page https://www.va.gov/health-care/apply/application/introduction
2. It had a link to `http://www.va.gov/healthbenefits/cost/income_thresholds.asp`
3. That link redirects to `http://nationalincomelimits.vaftl.us`
4. This used to be "VHA Innovation Future Technology Laboratory" see https://web.archive.org/web/20181230113618/http://vaftl.us/
5. At some point they moved out of that domain and let it expire
6. Someone else grabbed the domain and it now loads spam/malware


Created research Epic for investigation of solutions:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/18823

**Comment by mchelen-gov** [comment]
followup ticket to remove the redirect from va.gov: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18873
