### ISSUE TITLE
508-defect-2 [KEYBOARD]: Focus MUST be returned to the Edit button when Update page is pressed or clicked

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#17825]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** _Josh._

## User Story or Problem Statement

As a keyboard user, I expect a consistent experience for focus when using the edit and update page buttons.

## Details

The Update page button for issues eligible for review does not return focus to the Edit button on the review page. Users need a consistent experience so they won't have to re-orient or discover where their focus is when it is not returned to Edit. Video attached below.

## Acceptance Criteria

- [ ] Focus returns to the edit button upon clicking the update page button

## Environment

* Operating System: any
* Browser: any
* Screenreading device: any
* Server destination: staging

## Steps to Recreate

1. Enter `https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/review-and-submit` in browser.
2. Complete test case 3 and reach the review page.
3. Open the issues eligible for review accordion.
3. Click "Edit".
4. Click "update page" button.
5. Confirm focus does not return to "Edit."

## Solution 

Return focus back to the edit button.

## WCAG or Vendor Guidance (optional)

* [Keyboard: Understanding SC 2.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html)

## Screenshots or Trace Logs
Focus is not returned to the edit button. It works for request an informal conference though!

https://user-images.githubusercontent.com/14154792/102921498-75db8c00-445a-11eb-8b84-06c7c602610c.mov

**Comment by Mottie** [comment]
Fixed in staging! 😸

**Comment by joshkimux** [comment]
Confirmed this has been fixed. Great work @Mottie 🥳
