### ISSUE TITLE
Annotate GA for missing Event Action data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#17832]
## Issue Description
With the GA Event Action data scrub, data that many of our VFS teams look at will be missing. VSP Analytics & Insights should add annotations reflecting the scrub to GA so that our users can understand how to read the data.

---
## Tasks
- [ ] Add annotation marking the missing data in Google Analytics

## Acceptance Criteria
- [ ] Users going into GA understand that the data from the scrub date range is missing without having to request information from the VSP Analytics & Insights team

**Comment by jonwehausen** [comment]
@bsmartin-ep Can you handle adding the GA annotation for that date range as well?

**Comment by bsmartin-ep** [comment]
Annotation added to prod and non-prod:

```
Due to a potential PII / PHI issue, event actions from 10/11/20 to 12/2/20 were deleted.

github.com/department-of-veterans-affairs/va.gov-team/issues/16643
```
