### ISSUE TITLE
Benefit Summary letter -  accessibility corrections

### ISSUE THREAD

**Issue by msmanak** [department-of-veterans-affairs/va.gov-team#17839]
## What happened?

1. iOS (voiceover): profile letter page under  "benefit summary and service verification letter"

- discharge type and description read as two different announcements
- active duty start and description read as two different announcements
- separation date and description read as two different announcements
![IMG_8243.PNG](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/df8af665-aad4-4a4a-a693-4f7026ba69bd)

2. menu items under  VA benefit and disability information should be read as switch/toggle:
![IMG_8242.PNG](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/7de95478-b5f9-4730-bf96-4e9898112ad7)

## Desired behavior 
1. VoiceOver will select & announce the entire ListItem together, rather than in separate lines.
"discharge type;  description"
"active duty start;  description"
"separation date; description"

2.
- ios: (switch) “{title}, switch on”
- ios: (switch) “{title}, switch off”

- Android“{title}, on. Toggle switch”
- Android “{title}, off. Toggle switch”

**Comment by digitalken** [comment]
PASS 2/19/2021 - All being read as single announcement. iOS and Android.  Closing.
