### ISSUE TITLE
Asking a user to add biometrics

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#17837]
## User Story
As a user, I will allow VA mobile app to use biometrics on my device. 

## Context
The app start up is tricky, because of that biometrics part. Flow will be: spalsh screen -> log in -> get tokens -> ask for biometrics -> store token -> sync profile stuff & we need to iterate on what this flow looks like.

**Comment by bridgethapner** [comment]
I'm working with @lexicalninja on this. Decisions we've made: 
- We definitely want to ask folks permission to opt into biometrics

Things we've learned:
- Our library doesn't have an easy way to do this, we need to build our own thing

Next steps: Patrick investigating technical LOE

**Comment by lexicalninja** [comment]
related to #16984

**Comment by bridgethapner** [comment]
- This screen will present to users immediately after they return to the app from the sign-in flow the first time they sign in.
- Copy should be dynamic based on the device's capabilities if technically possible. @lexicalninja is this feasible?

Attached is a UI for this. 

This is not an industry-standard opt-in UI, they typically use a system modal. Our current React library doesn't allow us to easily use system components here b/c of the way we're storing credentials, so we're building our own. CC'ing @ayushchak for your awareness, no action needed just keeping you in the loop! 

![Biometrics Opt In.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/7ff8e48a-2e5a-416e-95c4-7191f9864b7a)

**Comment by bridgethapner** [comment]
@lexicalninja Same Q here - are you referencing this ticket? If not I'll close it
