### ISSUE TITLE
[FE] Typo on Intro Page

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#17848]
## What happened?
_A typo was discovered on Intro page of the 10-10CG_

## Steps to Reproduce
- URL: https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction

![Typo on Intro Page](https://user-images.githubusercontent.com/58444931/103017933-59028f80-4512-11eb-98d7-edd93fc1b3ea.png)

## Desired behavior
_Content should be updated to "10-10EZ"_

<img width="658" alt="Screen Shot 2020-12-23 at 11 31 54 AM" src="https://user-images.githubusercontent.com/58444931/103018079-98c97700-4512-11eb-828b-771dcae8b59e.png">

## Acceptance Criteria
- [x] _Update content_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by LinnJS** [comment]
Opened PR for this issue [here](https://github.com/department-of-veterans-affairs/vets-website/pull/15532)

**Comment by ala-yna** [comment]
<img width="621" alt="Screen Shot 2021-01-05 at 4 17 42 PM" src="https://user-images.githubusercontent.com/15709424/103700079-e9f55400-4f71-11eb-8c6e-cf4d370b8618.png">

Validated in Staging & Production.
