### ISSUE TITLE
Add loading screen for pages w/ API-driven data

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17859]
## Context for this task
Patrick created a generic loading screen component for screens that are pulling data from the API, so it doesn't flash a blank screen. 

## Acceptance Criteria
1. Make a sweep across the app and add the loading screen component to areas that are displaying API-driven data. This includes:
     - Appointments
     - Claims
     - Profile
     - Personal & contact information
     - Military Info
     - Direct deposit
     - Letters landing page
     - Letters list page
     - Benefit Summary & Service Verification Letter page

**Comment by digitalken** [comment]
I think I'm going to need non-mock data for this.

**Comment by digitalken** [comment]
2/3/2021 - Was able to verify a majority of the pages where the loading screen should appear for api-driven data. Some are still on mock data.  Closing.
