### ISSUE TITLE
UI update | Increase type styles

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17850]
## Acceptance Criteria
Make the following global changes across the app:

1. Increase **Bitter Bold** type style from 20px/26px to 24px/30px
2. Increase **Mobile Body** and **Mobile Body Bold** from 17px/26px to 20px/30px
 
## Mockups
![Screen Shot 2020-12-23 at 11.45.37 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e599bfb3-7a89-4fd3-9dd0-261dc3c444b6)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/5/2021 - Large founts showing up around the various screens.  Moving to Design QA.
