### ISSUE TITLE
[FE] Signature box title should be sentence case 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#17855]
## What happened?
_The title in Secondary Family Caregiver signature box needs to be sentence case_

## Steps to Reproduce
- URL: https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/review-and-submit

<img width="430" alt="Screen Shot 2020-12-23 at 12 01 51 PM" src="https://user-images.githubusercontent.com/58444931/103020594-b1d42700-4516-11eb-93a6-76d48f773c51.png">

## Desired behavior
_Change titles for Secondary Family Caregiver signature box title to: 

_Secondary Family Caregiver applicant information_

<img width="508" alt="Screen Shot 2020-12-23 at 9 20 30 AM" src="https://user-images.githubusercontent.com/58444931/103021422-19d73d00-4518-11eb-8869-cab2087ca05e.png">

## Acceptance Criteria
- [ ] Update content

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by LinnJS** [comment]
This work should be included in the work in this [ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18329) which is in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15418).

Needs to be validated by @jonathanjnelson

**Comment by LinnJS** [comment]
This was confirmed to be fixed in [this ticket](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/18329) by @jonathanjnelson and I.
