### ISSUE TITLE
UI update | Misc. padding changes

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17853]
## Acceptance Criteria

1. On the Contact VA page, reduce padding between the elements in the ListItem **by half**
2. On Step 3 of the Active Claims Step Table, **double** the padding between “You have 2 file requests from VA” and the Large Button CC
 
## Mockups
![Screen Shot 2020-12-23 at 11.50.59 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c87159c1-8a73-4d44-968c-77fc40bf022e)

![Screen Shot 2020-12-23 at 1.41.27 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f89de27a-d47b-4877-a9b3-1a66d17a3629)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/4/2021
