### ISSUE TITLE
Footer - Update VVC support hours to 24/7.

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17851]
## Issue Description

Note from OCCHD

> In addition, the reference to VVC support should be changed to 24/7.  Thanks

![Screen Shot 2020-12-23 at 8.41.43 AM copy.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/5478a97b-1723-4054-a7a0-f2fad77f2f60)

---
## Acceptance Criteria
- [ ] CONTENT - Last sentence in footer copy reads

> We’re here 24/7.

**Comment by laurenernest** [comment]
@peggygannon Is there a standard way we use "24/7" across va.gov?

**Comment by peggygannon** [comment]
Hi, @laurenernest here's our standard language for this. 
Please update that line to:

We’re here 24/7.

**Comment by laurenernest** [comment]
@jenniemc What would you say the LOE for this work was, points-wise? 1?

**Comment by jenniemc** [comment]
Yupe, 1pt is right
