### ISSUE TITLE
Access for Jack Schuss

### ISSUE THREAD

**Issue by yakschuss** [department-of-veterans-affairs/va.gov-team#17854]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Jack Schuss
- Please Provide your email.
   > jack.schuss@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > BananaPeels/Lighthouse API - Software Engineer - Oddball.io

- Requesting SSH key authorization?
   > NO 
   - (Have SSH access already)

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
  AWS Console tools - for insight into development code being written as well as monitoring/debugging tools.

**Comment by yakschuss** [comment]
@department-of-veterans-affairs/vsp-operations  - tagging here for notification

**Comment by jbritt1** [comment]
#### For AWS Access:
User: Jack Schuss
COR: Cecilia Lee
Approval needed: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by jbritt1** [comment]
Temporary credentials provided to user.
