### ISSUE TITLE
Update review page variants

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1785]
## Story
As a developer, I want to understand what to show to veterans depending on their appointment flow they went down so that I can build the right thing.

## Variants
- Community Care appointment request flow review
- VA appointment request flow review
- Direct schedule appointment flow review

## Usability updates from existing mocks:
- Location and clinic should be grouped together.

## AC
- [ ] New mocks for flows attached to this ticket

**Comment by rtwell** [comment]
## Direct schedule

![image](https://user-images.githubusercontent.com/12564977/67721780-cddd4680-f9ad-11e9-87aa-b63b83206cce.png)

## Community care

![image](https://user-images.githubusercontent.com/12564977/67721789-d2096400-f9ad-11e9-8671-def625df095a.png)

## VA Appointment request

![image](https://user-images.githubusercontent.com/12564977/67721888-067d2000-f9ae-11e9-86fc-7520f3790194.png)

**Comment by peggygannon** [comment]
@markgreenburg Is this also true for the Edit contact details? If a user clicks on that link to edit their contact info, then they'll have to go through the tool again and redo their appointment?

**Comment by markgreenburg** [comment]
@peggygannon you wouldn't have to start completely over in any of these cases - you'd just go back to the page that has that specific data. So in the case of contact details, you'd just get moved back one page to the contact details screen. Does that help?

**Comment by peggygannon** [comment]
I've uploaded content recommendations to the Review pages in:
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2224
