### ISSUE TITLE
Facilities API Issue

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#17858]
## Description

See thread [here](https://dsva.slack.com/archives/CBU0KDSB1/p1605895009424800)

## Goals
Determine the path forward to solve the issues outlined in the thread.

**Comment by alexpappasoddball** [comment]
@kfrz Do mind diving into this next week if you have some time and document in this ticket how you think we can best move forward with this?

**Comment by alexpappasoddball** [comment]
@drorva @davem-va @rtravitz @tskinn Unable to tag Adam and Peter on this, if anyone wants to forward it over.

Just for clarity, we will only have 1 team member around until the new year.  We will try and get it looked into but based on available resources no promises.

**Comment by rtravitz** [comment]
I did some looking at the access logs to determine where the requests to `v0/facilities` endpoints are coming from. Attaching a [file with the results from the past six hours](https://app.zenhub.com/files/133843125/6e9444d6-08da-49e3-aa94-559e73476c47/download). 

The biggest users are still in the 10 space. Wonder if there's any way to track down who those are.

You can reproduce with this:
```
awslogs get -f '[ip, d1, d2, ts, req="*/v0/facilities*", ...]' -s 1m -GS dsva-vagov-prod/var/log/nginx/access.log > logs.txt
cat logs.txt | awk '{ addrs[$1]++ } END { for (ip in addrs) print ip, addrs[ip] }' | sort -k2 -nr
```

**Comment by LindseySaari** [comment]
The FacilityLocatorUpdateErrorsWarning and FacilityLocationDownloadJob were both removed from the sidekiq scheduler/cron jobs as they were creating noise in the oncall channel for data sync issues for various facilities.  Existing facilities models/data in vets-api are no longer being maintained and the data is stale. The data on v0 has been stale for months. There are still a few customers utilizing v0 facilities so a depreciation plan and path forward needs to be defined

**Comment by drorva** [comment]
Close this?
