### ISSUE TITLE
General Analytics Request for Margery

### ISSUE THREAD

**Issue by HikeBandit** [department-of-veterans-affairs/va.gov-team#17866]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- margery@searchenginecatalyst.com and herri.Deloof@va.gov

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._ Sorry - no Slack access.
    
- What team/project is this work for? VA.Gov/grecc

    _this adds context for the data_
    - [Insert team and project)
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
  - [X] Analytics admin support
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)? 01/01/2021

## Analytics to Track Down
Request: Can you consolidate the Google Analytics data for www.va.gov/grecc/ and www.va.gov/grecc/index.asp into one report? It's a monumental pain to add the separate data together for every report. Please contact margery@searchenginecatalyst.com for questions.

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @HikeBandit , thank you for your request! We will triage & prioritize accordingly, we will be in touch soon.

**Comment by jonwehausen** [comment]
Hi @HikeBandit , 

Could you provide for us a bit more depth of what metrics you would be looking to consolidate into one report? 

This will help us understand the level of effort for delivering you and your team the report. 

Thanks so much in advance, we look forward to hearing from you.

**Comment by HikeBandit** [comment]
In the Behavior reports (All pages and Landing pages, especially), we always have to manually add the metrics (pageviews, unique pageviews, time on page, etc.) for the pages that end in index.asp and those that don't, ie, www.va.gov/grecc/ and www.va.gov/grecc/index.asp. These are the same pages. This seems like an unnecessary and time-consuming step that should be fixed for all of VA.gov pages, but I'd like to see them fixed for va.gov/geriatrics and va.gov/grecc in particular. I believe you need to change the Default page to include index.asp. Does that help?

**Comment by jonwehausen** [comment]
Hi @HikeBandit , 

Yes, this helps greatly, thank you for your explanation here, and apologies in advance for the manual summing up to this point. 

**We hope the below steps can help cut down on this time now and in the future**

## Steps

1) Within the [All Pages Report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22(%5Ewww.va.gov~2Fgrecc~2F$%7C%5Ewww.va.gov~2Fgrecc~2Findex.asp)%22,0%5D%5D&explorer-table.plotKeys=%5B%5D), click the 'edit' button over to the right to show the advanced filtering
![image](https://user-images.githubusercontent.com/48527022/103925615-d1a64600-50e5-11eb-92b3-6250dd689865.png)
2) Make sure the first dropdown says _"Include"_, the dimension says _"Page"_ and change the dropdown to say _"Matching RegExp"_, add in the following in the text field `(^www.va.gov/grecc/$|^www.va.gov/grecc/index.asp$)` and click Apply
![image](https://user-images.githubusercontent.com/48527022/103926007-58f3b980-50e6-11eb-8530-8d6a3ce98d6c.png)
3) This should then isolate to only those two versions of the page -- you can then look at the top bar for the combined totals and/or averages
![image](https://user-images.githubusercontent.com/48527022/103925973-4da08e00-50e6-11eb-8e69-fef586e14cd5.png)

**Comment by HikeBandit** [comment]
Thank you, Jon. This is helpful.
________________________________

**Comment by joanneesteban** [comment]
Thanks for providing support, Jon! 

@HikeBandit - we're closing this ticket, but please let us know if you have any other questions for us on these reports, & we can reopen!
