### ISSUE TITLE
Add Content to CH31 Orientation Module

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17860]
### Goal
Add several "chapters and slides" to CH31 orientation module on 28-1900 intro screen.

### Considerations
- [Orientation PDF](https://dsva.slack.com/files/U7721SMFG/F01J8BRHWC8/vr_e_turbo_mockup.pdf?origin_team=T03FECE8V&origin_channel=DNDN2C66N)
- [Turbo Orientation]()

Content outline per orientation PDF:
1. Basic benefit information (6 bullet points)
2. VR&E Process Overview (5 sentences)
3. VR&E Process: Application (5 checkboxes)
4. VR&E Process: Entitlement Determination (4 checkboxes)
5. VR&E Process: Evaluation & Planning (3 checkboxes)
6. VR&E Process: Services (3 checkboxes)
7. VR&E Process: Completion (3 checkboxes)
8. VR&E Process: Review
9. VR&E Tracks: Overview
10. VR&E Tracks: Track 1 (done)
11. VR&E Tracks: Track 2 (done)
12. VR&E Tracks: Track 3 (done)
13. VR&E Tracks: Track 4 (done)
14. VR&E Tracks: Track 5 (done)

### Tasks
- [ ] Create additional content "slides" and chapters in CH31 mocks

### Acceptance Criteria
- [ ] Updated orientation module in CH31 mockups/prototype, with a link in this ticket

**Comment by sporeboy** [comment]
Initial cut of new content placed in orientation mocks: https://xd.adobe.com/view/aaf3f28b-b763-4c16-ba02-d1d47e20328e-ffa0/

**Comment by sporeboy** [comment]
Initial content added to orientation module. Next steps:

- Consolidated content into vastly fewer "slides"
- Rewrite content to plain-language standard and incorporate VA.gov phrasing
- Create module "stepper" to indicate slides and position in orientation presentation
- Incorporate any definitive design standards regarding video presentation

**Comment by sporeboy** [comment]
There are several concerns that will *likely* need to be addressed:

- Orientation is extremely long
- Language will require revision for clarity, VA styling and language
- Process steps are redundant with summary information
- Module is out of context
- Orientation info is relatively inaccessible as reference
- Module is a barrier to completing the form

At some point, Design, Content and Accessibility teams will need to be involved; revisions cycles will follow.
