### ISSUE TITLE
UI update | Claims nav bar icon

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17864]
## Acceptance Criteria
1. On the bottom nav bar, change the icon for the unselected Claims page with the attached .svg (see Bridget's comment below for the icon)

## Mockups![Screen Shot 2020-12-23 at 1.49.37 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/419ec432-3e7c-4fbc-a5c7-27b0b3a94fd6)

**Comment by bridgethapner** [comment]
![claims.svg](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/3728d68c-3b53-4846-9c59-7cb8868e3a57)

**Comment by digitalken** [comment]
PASS 1/8/2021 - Weight looks even around the perimeter of the icon.
