### ISSUE TITLE
UI update | Table header padding & text size

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#17865]
## Acceptance Criteria

1. Increase ‘Table Header Label’ type style from 14px/18px to 20px/30px
2. Add 10px of padding between ‘Table Header Label’ and tables
      - Do a sweep across the app & apply this change globally 
 
## Mockups
![Screen Shot 2020-12-23 at 2.00.21 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4d25b8b2-d783-4c7f-a8c4-e6113a1fcc1f)

**Comment by digitalken** [comment]
Added to TestRail.
