### ISSUE TITLE
How to handle database failures after 10-10CG was successfully submitted to CARMA.

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#17876]
**Description**
When a 10-10cg is submitted to CARMA, we **must ensure** that the user gets a 200 successful. We save the submission to the database after it's submitted to CARMA (because the background job needs to reference the submission id and veteran's name).

We call `save` instead of `save!` to ensure that an error doesn't bubble up to the UI, misleading the user to think it was not successful.

**A/C**
Figure out a way to handle these situations.

**Considerations**
- Maybe we can log to sentry with the `claim.guid` and the `submission.carma_case_id` if `save` fails. We can then rely on Sentry to report the cases where this has failed.
- We could queue the background job without storing anything in the database (by passing the form data and submission id as parameters - form data being encrypted).

code: https://github.com/department-of-veterans-affairs/vets-api/blob/d83ca89a8bad6789681bf5ed5d533bd034fc3e19/app/services/form1010cg/service.rb#L83

**Comment by tchrisdyer** [comment]
Needs grooming

**Comment by kevinmirc** [comment]
Updates ticket title and submission to be more descriptive of the real need. Added some suggestions as well for how to handle these.

**Comment by hdjustice** [comment]
This ticket is no longer applicable, since we have integrated with Mulesoft as a middleware between VA.gov and CARMA to help resolve wait times and submission failures.
