### ISSUE TITLE
Access for Dean Zaslow

### ISSUE THREAD

**Issue by zaslow** [department-of-veterans-affairs/va.gov-team#17873]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Dean Zaslow
- Please Provide your email.
   > dean.zaslow@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I have recently joined Ad Hoc as a Senior Software Engineer on the Platypus team within the VA Lighthouse API program, which handles the VA API platform.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCilGFZsgPDQymHpJtFg0u1E761z5hcvS8lJSCd1Fzw69h4aQaDdA4s8O94fn6J4HiFlajsV3sqCu8Xdu5T55/4l1F+nCLA7HK3kWylK7gZPRktEGWEnmT4bBS1DrSaSEEXbN2oYz6TkoAnpIRypE0c2534m4WTVbONayH6nogFUSa39HLwZ3L7/gZUNC2OQbbE/CMMv3pqWS1AFAf8nCFamsIwnnq6IiFEt3fUwQmpT0XMTW0uW+nJfZl2kuWyuhOrqNy6FRPc93t/r1aX1j8+SleLFHmM33AqEEyljxpsbqI2dUipSQB7lr0fVJ5SbDY2zGP493V/w4zSLEB5+PAD zaslowd@BKSQ-CQWH-MAC.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
 > AWS console, EC2, ECS, and any other AWS infrastructure/services that support the VA API platform, since I will be helping maintain it

**Comment by zaslow** [comment]
@department-of-veterans-affairs/vsp-operations: Please review at your convenience

**Comment by jbritt1** [comment]
#### For AWS Access: 

User: Dean Zaslow
COR: Cecilia Lee
Approval needed: @Jeff-Hayter

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by wyattwalter** [comment]
Hey @Jeff-Hayter , is there any update on the approval here by chance?

**Comment by Jeff-Hayter** [comment]
@wyattwalter Not yet, hope to  have an update soon.

**Comment by Jeff-Hayter** [comment]
@wyattwalter Approved for AWS.

**Comment by jbritt1** [comment]
Temporary credentials provided to user.
