### ISSUE TITLE
[Discovery] Explore Adding GA to Spanish Corona FAQ and User Research Page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17872]
This is work to explore implementation of Google Analytics in advance of the pages being created in Drupal.

## User Story1: 

_As a PM I would like to have GA implemented on 2 new spanish pages (FAQs + Volunteer) so I can track and measure metrics (should match current English page tracking).

## User Story2: 

_As a PM, I would like to add click event tracking on the the links/toggles added to both the English and Spanish pages

## Expected Behavior

_I would like to see the same data currently available on the English version of the pages via GA reporting or through DOMO. 
_I would like to see data for clicks on new links added to English and spanish pages

## Acceptance Criteria

- [ ] _Confirmation that page is sending data to GA

**Comment by youngfreezyVA** [comment]
this is how we'd call the GA function:
@SKasimow can you confirm the event name when you have a moment:
`<a onclick="recordEvent({ event: 'nav-featured-content-link-click' });" href="{{ node.fieldFacilityLocation.entity.entityUrl.path }}">{{ node.fieldFacilityLocation.entity.title }}</a>`

**Comment by SKasimow** [comment]
@bmcgrady-ep Hi Ben - can you answer the question above re: what the event name will be or point us in the right direction for this?

Thanks, Sharon

cc: @youngfreezyVA

**Comment by bmcgrady-ep** [comment]
@SKasimow @youngfreezyVA - That looks like the correct event name to me. Can you include a screenshot of the interaction for this specific event?

**Comment by SKasimow** [comment]
@youngfreezyVA can you provide for Ben?

**Comment by youngfreezyVA** [comment]
![Uploading Screen Shot 2021-01-07 at 9.03.54 AM.png…]()
