### ISSUE TITLE
General Analytics Request for Reporting: Content and Localization | KPI Dashboard

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17871]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- [Insert Name(s)] 
**Content and Localization**
@SKasimow 
@DanielleThierryUSDSVA 

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - [Insert team and project)

This request is for creation of a dashboard enabling us to monitor and measure performance of the new spanish language pages being created for corona/covid information

The initial page will be the "Corona FAQs" which will be followed by spanish versions of the "Research Volunteer" form and "Covid Vaccine" page.

The "Corona FAQs" will be published ~1/20; other pages are TBD.
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
  - [x] **Recurring dashboard**

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

Ideally, we would be able to have reports at or shortly after the launch date.

## Analytics to Track Down
> Examples
> 
> - [ ] Metric 1
> - [ ] Metric 2
> - [ ] Metric 3

- UVs/PVs
- Source (ie: search, English version of the page)
- device
- browser language
- clicks to English version of this page (and conversely want to track the number of clicks FROM the English version of the page to this spanish version)
- accordion clicks
- time spent
- spanish satisfaction survey (implementation date TBD - shooting for late Jan/early Feb)
- click tracking for ALL links on page

## Which Product Questions are you trying to answer?

- how do users get to this page?
- how do the key metrics compare to english version of this? Same or higher satisfaction? Lower bounce rate? More time spent?

## Other Helpful Questions to think through

- Who is your audience?
LEP Vets and caretakers, native language is spanish.

- Why do you need this data?
Measure usage and satisfaction to help decide whether to continue providing translated content.

- What is your hypothesis that you're hoping the data will support?
That native speaking spanish vets/caretakers find the information they are looking for in a way they can easily understand. 
This under-served group feels more valued by having content available in spanish.

- What area of the VA are you hoping to assess?
LEP Vets and caretakers, native language is spanish.

- How frequently do you need this data?
Weekly with monthly roll-ups.

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks for your request @SKasimow! We will be in touch shortly.

**Comment by SKasimow** [comment]
@bmcgrady-ep Hi Ben - here's the dashboard request we discussed prior to the holiday. Please let me know if you need additional info or want to discuss. Thanks!  Sharon

cc: @DanielleThierryUSDSVA

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi Danielle - Ben willl be constructing a dashboard report for us soon and wanted to make sure I covered the key metrics we will want to track. Can you take a quick look and lmk if there is anything we should add to the list?

Thanks,

Sharon

**From ticket: **

UVs/PVs
Source (ie: search, English version of the page)
device
browser language
clicks to English version of this page (and conversely want to track the number of clicks FROM the English version of the page to this spanish version)
accordion clicks
time spent
spanish satisfaction survey (implementation date TBD - shooting for late Jan/early Feb)
Which Product Questions are you trying to answer?

how do users get to this page?
how do the key metrics compare to english version of this? Same or higher satisfaction? Lower bounce rate? More time spent?

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @SKasimow! I don't specifically see all link clicks on the list - may already be covered, but wanted to mention just in case. Otherwise, this looks good to me.

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA - thanks for reviewing - I added in tracking for all links!

**Comment by joanneesteban** [comment]
@SKasimow would you be able to link the KPIs you set up in our meeting the other day?

@bmcgrady-ep - [Notes](https://dsva.slack.com/archives/CKCRMLGAC/p1611606782006600) on Slack

**Comment by joanneesteban** [comment]
@bmcgrady-ep 

Two dashboards:
- A sub-dashboard for the Covid Dash
- The team's separate KPI Dashboard

**Comment by SKasimow** [comment]
@joanneesteban @bmcgrady-ep Sure...here it is: https://docs.google.com/spreadsheets/d/1F96U1Z4X9h2i68CjSrNUhjCLbPsvzxBFD_0QAe5paYg/edit#gid=81708125

**Comment by SKasimow** [comment]
@bmcgrady-ep Thanks Ben - I've been out a couple of days but will aim to review this afternoon!

**Comment by bmcgrady-ep** [comment]
### Spanish Covid FAQ Page Dashboard Sub-page
Spanish Covid FAQ Metric | Source | Status
 ------------- | ------------- | -------------
Pageviews and Unique Pageviews | BigQuery | ✔️ Go
Spanish Covid FAQ Traffic Source | BigQuery | ✔️ Go
Accordion and link clicks on Spanish Covid FAQ | BigQuery | ✔️ Go
Average time on Spanish Covid FAQ page | BigQuery | ✔️ Go
Satisfaction Survey | Medallia | Future 🔶 Go

@SKasimow - Thanks for clarifying the above metrics. One more request I would ask of you is to provide questions that each of the above metrics answers for you, so we can add that into the table. Thank you!

**Comment by SKasimow** [comment]
@bmcgrady-ep Hi Ben - sure, I've listed below:

* Pageviews and Unique Pageviews: What is the traffic volumes for this page currently and  over time?. How does this compare against English pages traffic and growth?

* Spanish Covid FAQ Traffic Source: How do users find this page? Do we need to create more awareness for it?

* Accordion and link clicks on Spanish Covid FAQ and Average time on Spanish Covid FAQ page: how engaged are users with this page? Is it similar/different to engagement and time spent on english version?

* Satisfaction Survey: are readers finding it useful to have a spanish version of the CoronaFAQs available? Do they rate this page more or less favorably than the english version

Let me know if this is in line with what you are looking for.

Thanks,

Sharon

cc @DanielleThierryUSDSVA

**Comment by bmcgrady-ep** [comment]
@SKasimow - Thank you!

@mandy-uxd or @JasonTheBearded - I am moving this request into the "Ready for Work" column as the metrics have been groomed. Note: there are two separate dashboards for this request. One dashboard is for the Content and Localization KPIs and the other dashboard is for a sub-page of the COVID dashboard. Let me know if you have any questions.

**Comment by joanneesteban** [comment]
> Pageviews and Unique Pageviews: What is the traffic volumes for this page currently and over time?. How does this compare against English pages traffic and growth?

@SKasimow - can you let us know what product information you would like to know from this metric? What problem you're looking to solve? We've found that the volume vs. English is really low and won't give a good visual. Can you give us an understanding of the product question you're looking to solve? We can look into which metrics might help you from here.

**Comment by SKasimow** [comment]
@joanneesteban Hi Joanne! We're trying to assess whether the spanish FAQ page has similar increases/decreases to the English version of the page as a way to understand whether traffic patterns are similar (on a relative basis). If they differ widely, may be something to drill into further to help us understand this audience better.

Also, we should see more spanish traffic soon as we will be adding a spanish version of the Covid Vaccine page. 

Does this help?

**Comment by JasonTheBearded** [comment]
@mandy-uxd Initial dashboard creation for the Spanish COVID FAQ subpage is complete and the dash is ready for design review. Thanks!

**Comment by mandy-uxd** [comment]
Design review is complete and @JasonTheBearded is working on the updates. We should be able to share mid next week.

**Comment by JasonTheBearded** [comment]
Updates complete from review. Ready for demo.
cc @joanneesteban

**Comment by JasonTheBearded** [comment]
Demo complete. Marking ticket as done.
