### ISSUE TITLE
User Survey Request for Content and Localization

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17870]
# Request~~the Foresee~~ Medallia Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/medallia-request-survey.md)

## Description
*Please provide the name(s) of your product and a high level description of your product.*

Request is to add the "always present" survey to the spanish Corona FAQ

### Launch Date
*Please provide the launch or rollout date.*

~Jan 20, 2021

### Staging URLs
*Please provide staging URLs*

### Production URLs
*Please provide Production URLs*

www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/  

~~www.va.gov/coronavirus-research-esp/~~

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by SKasimow** [comment]
@joanneesteban Hi Joanne - can you lmk if we are able to support a spanish version of the survey? I can provide the translation if needed.

**Comment by jonwehausen** [comment]
Hi @SKasimow , 

Unfortunately I can't give you a clear-cut answer on whether the Medallia surveys support Spanish language. I personally have not managed the Medallia roll out enough to make that determination. 

@joanneesteban or Sarkis should be able to give you a yay/nay on if this is possible

**Comment by SKasimow** [comment]
Hey @jonwehausen - thanks for taking a look. Can you either add Sarkis to this thread or let me know his/her full name so I can see if they can answer while Joanne is OOTO? Thanks! Sharon

**Comment by jonwehausen** [comment]
Note here to discuss this request with @joanneesteban: 
- Slack context: https://dsva.slack.com/archives/C1Q4294JJ/p1609283152203300

**Comment by joanneesteban** [comment]
Removing the `analytics-insights` label and redirecting to the VSP Contact Center team.

**Comment by joanneesteban** [comment]
@jwoodman5 FYI

**Comment by SKasimow** [comment]
@jwoodman5 Hi - can you let me know when we might be able to add the survey to our page?

**Comment by jwoodman5** [comment]
@SKasimow Hi Sharon - we have been heavily focused on the 508 issues and I have not been able to confirm this for you. I am working on it, though, and hope to have some idea for you tomorrow. Thank you for your patience.
