### ISSUE TITLE
GIBCT: First option in drop-downs is bold for all browsers on Windows

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#17880]
## What happened?
When expanding any drop-down in the GIBCT using a windows machine, the first option is always bold. On windows, the currently selected option should be in **bold**. Currently, the first option is always bolded. 

![Screen Shot 2020-12-28 at 11.30.04 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d727b498-ad96-4c91-9661-f7844ab41c1e)

## Specs:
- Device: Windows VM
- Browser: Chrome, Firefox, IE, Edge
- Firefox on Mac

## Steps to Reproduce
1. Access https://staging.va.gov/gi-bill-comparison-tool/profile/3V000142/CISCO%20SYSTEMS%20-%20CCDP
2. Expand the `Choose the training program you'd like to attend` drop-down
3. Notice "CERTIFIED ETHICAL HACKER" is bold despite the fact that it is not the currently selected program
4. Select any program besides "CERTIFIED ETHICAL HACKER" and click update benefits
5. Expand the drop-down again
6. Notice "CERTIFIED ETHICAL HACKER" is bold despite the fact that it is not the currently selected program

## Acceptance Criteria
- [ ] The currently selected option is bold in the drop-down

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15632

**Comment by sonntag-adam** [comment]
Testing passes QA
