### ISSUE TITLE
[SPIKE] Appointment ID flow (Lighthouse and Map)

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#17887]

**Comment by mlighdc** [comment]
Elements that comprise of the MAP/MAS generated Appointment ID:
- Appended with Patient ID and Facility ID (this is not enough to be an unique identifier as patient may have multiple appointments at the same facility
- so also would inlcude locationIEN, fmApptDate, patient DFN,Station

**Comment by dillo** [comment]
Here's the current appointment flow diagram illustrated in sequence fashion:
https://drive.google.com/file/d/1Oq9i7SCSAjKTzC-SNlmHDhlsjcXXWIb1/view?usp=sharing

After discussing with @abuckley3385, I'm revising it to show a general-purpose audience what fields are used to generate the appointment IDs in MAS/MAP and also adding visual place holders to indicate what unique identifiers will be added for the Lighthouse PGD service.

**Comment by dillo** [comment]
Updated file + adding to Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/appointment-id.md
