### ISSUE TITLE
EYB 107 Question Learn More modal: Close button not properly aligned on Modal

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#17897]
In the Estimate your benefits section of an institution profile page, a user is asked "Did you use your Post-9/11 GI Bill benefits for tuition, housing, or books for a term that started before January 1, 2018?" which is followed by a "learn more" link. Clicking this link opens a modal (screenshot below). The close button on this modal is not properly aligned.

## Steps to reproduce
1. Access any profile page (ex. [College of Charleston](https://staging.va.gov/gi-bill-comparison-tool/profile/11929140))
2. Under Estimate your benefits, expand the military details section
3. For "What's your military status?" Select Veteran
4. For "Which GI Bill benefit do you want to use?" Select Post-9/11 GI Bill (Ch 33)
5. Click The Learn More link for "Did you use your Post-9/11 GI Bill benefits for tuition, housing, or books for a term that started before January 1, 2018?"

## Current behavior
Modal displays with the exit button misaligned
![Screen Shot 2020-12-29 at 8.13.44 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/dbe968be-6754-451c-82fc-1d276e665227)

## Expected behavior
Exit button is aligned like all other modals (see example screenshot below)
![Screen Shot 2020-12-29 at 8.15.30 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/bcdfd905-d6c6-40a1-8dd2-7317699a292a)

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15486

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-12-29 at 9.09.11 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/be09da30-2dc7-467a-a31c-fa60a2491d0b)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me

**Comment by amyknox** [comment]
UX Review 2/2: This checks out for me, too.
