### ISSUE TITLE
Tutorial on creating a new endpoint in Vets-API, from initial setup to validation in production

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#179]
## Story

As a VFS team member, I want a tutorial that covers the entire process of adding a new endpoint into Vets-API, from initial repository setup to having a PR successfully merged and validated in production, so that I can add Veteran facing functionality to VA.gov in the prescribed manner, without initial VSP personnel dependencies/blockers.

## Goal

To have a maintained, best practices tutorial that can be accessed asynchronously, enabling the scaling of multiple VFS team contributions to Vets-API.

As a VSP team I want a tutorial on creating an endpoint the 'api.va.gov' way (service, model/response object, controller, serializer, specs, docs) so that I don't have to poke around existing code to learn how to build one.

## Considerations 

- how to get Vets-API up and running 
- run specs locally
- run rubocop locally 
- access Jenkins 
- access Sentry 
- access a review instance
- access a dev or staging instance
- logging into dev and staging
- test users
- migrations 
- how to integrate a service into Vets-API
- how to add an endpoint for a service that is integrated into Vets-API
- breakers
- swagger docs
- load testing
- betamocks
- simplecov
- how to run Vets-API and vets-website together
- how to get the cookies from a logged in user to call Vets-API endpoints

## Tasks

TBD

**Comment by rtluu** [comment]
This work has been consolidated and captured in #128
