### ISSUE TITLE
Search this Area button doesn't work in IE11

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#17909]
Happens in production, but not staging.

Steps to reproduce:

1. search for 45805, VA Heath, all services
1. click “zoom out” button 6 times
1. click “search this area of map” button

Nothing happens. Console error is shown:

`Object doesn't support property or method 'remove'`

**Comment by tlei123** [comment]
@mpelzsherman , this bug looks fixed on [prod](https://www.va.gov/find-locations).  If your test result corroborates, then feel free to Close this bug.

Thx much!
