### ISSUE TITLE
Obtain JWT token from Lighthouse

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#17904]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** the vets-api to authenticate and obtain a JWT token from Lighthouse

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
Provide the ability for the Health Quest module to obtain a JWT token from Lighthouse so that the vets-api can use it to obtain FHIR resources from that service.

## Tasks
- [ ] Create a service in the vets-api health quest module that can handle authentication against the Lighthouse.

## Acceptance Criteria
- [ ] Call the authentication endpoint on Lighthouse and get back a valid JWT token in the response.

**Comment by dillo** [comment]
WIP: https://github.com/department-of-veterans-affairs/vets-api/compare/master...17904_lighthouse_jwt
