### ISSUE TITLE
Comparison Tool: Horizontal gold line appears when using Safari

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#17905]
When a Safari user closes a modal in the Comparison Tool, a horizontal gold line appears on the page. This line should not appear.

## Steps to reproduce
1. Using Safari, access https://staging.va.gov/gi-bill-comparison-tool
2. Click any of the Learn More links to open one of the modals
3. Close the modal
4. Scroll down slightly

https://user-images.githubusercontent.com/45575003/103294324-a9b93300-49bf-11eb-8846-d75ca838e1b4.mov

## Current Behavior
A gold line appears in line with the bottom of the Safari window
![Screen Shot 2020-12-29 at 9.59.04 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ea6b33db-3da5-4a6f-87b7-76cddb9e8b34)

# Expected Behavior
No gold line after closing a modal

![Screen Shot 2020-12-29 at 10 22 17 AM](https://user-images.githubusercontent.com/45575003/103294403-ceada600-49bf-11eb-9566-7e306885be04.png)

**Comment by ksantiagomorgan6** [comment]
Pull Request: https://github.com/department-of-veterans-affairs/vets-website/pull/15549

**Comment by sonntag-adam** [comment]
Testing passes QA
