### ISSUE TITLE
Find VA Forms Post-Launch MVP VSA-QA Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#17919]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.

## Product/Feature summary

We are making a few changes with this update:

1. **Iterate Find VA Forms Search Results** (links search results to forms details page where they exist).  The search page and details pages have both launched, but were not connected.
2. New info message for deleted forms - previously, users encountered a generic "not found" message.  This enhancement clarifies that the form has been deleted/deprecated.
3. Add 'sort by form last updated' function - this fulfills a need expressed by 

- Product/Feature Outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/README.md
- Product/Feature Epic: 
     - **Connect search results to form detail pages:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453 
     - **Connect search results to Online Tools:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/11453 
     - **New info message for deleted forms:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/11625
    - ~Add 'sort by form last updated' function~ Edit 1/8/2021 Marci McGuire - this has been pulled out of scope due to longer-than-anticipated decision on final design
     
- Product/Feature Copy deck(s): See PDF prototype link below for relevant copy
- Product/Feature Design prototypes: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/design/VA-Form-search-landing-results.pdf - **PLEASE NOTE** -- the text in the prototype that says "Revision Date" was later changed to "Form last updated" during the MVP.  We don't currently have the design source to make that change to the prototype.

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Original design intent was done by Ryan Thurlwell
Content/IA: 
Front-end: Zachary Morel
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

Link to **Use Cases doc**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/find-va-form-use-cases.md

**Pertinent Uses Cases are  in the Find VA Forms - [Search Landing Page Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/find-va-form-use-cases.md#find-va-forms---search-landing-page-use-cases) section 

   -  [A](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/find-va-form-use-cases.md#use-case-a)
   - [B](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/find-va-form-use-cases.md#use-case-b)
   - [C](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/find-va-form-use-cases.md#use-case-c)
   - [D](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/find-va-form-use-cases.md#use-case-d)
## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [X] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod environment].  https://dsvavsp.testrail.io/index.php?/runs/view/1189&group_by=cases:section_id&group_order=asc&group_id=824
- [ ] Test Reports generated.  These should be provided to VSP at least 2 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by MarciMcGuireGCIO** [comment]
@tlei123 I believe I am finished with my parts of the QA test plan.  Thank you very much for all your help.

**Comment by tlei123** [comment]
@MarciMcGuireGCIO , all QA test-runs completed.  Test plan/cases and report links below -- I'll also updated/add links to our Staging Review ticket #17926.

100% Passed - no defects logged.

[Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1188)
[Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/136&group_by=cases:section_id&group_order=asc&group_id=828)
[Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/180)
[Summary (Defects) report
](https://dsvavsp.testrail.io/index.php?/reports/view/181)
