### ISSUE TITLE
Replace confirmed appointment list mock data with vets-api service call

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#1791]
Fetch from vets-api instead of using mock data.

Service: GET /vaos/appointments
Query parameters:
- startTime
   - ISO datetime
   - Today's date
- endTime
   - ISO datetime
   - Today's date plus 4 months
- useCache
   - boolean
   - false
- pageSize
   - number
   - 0

Data returned:
- Two arrays, one with VistA appointments, the other with Booked CC appointments

AC:
- [ ] Service requested matches above endpoint and parameters
- [ ] Data returned is properly passed through to page components

**Comment by markgreenburg** [comment]
@jbalboni do we need similar tickets for `systems` and `requests`?

**Comment by jbalboni** [comment]
@markgreenburg Yeah, though I think there might be one for requests.
