### ISSUE TITLE
Contact Center Review for Decision Tools - Find a VA Form Post-MVP enhancements

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17927]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Find a VA Form Post-MVP enhancements

### Launch Date
[Tentative] Jan 12, 2020. 

 This update is relatively straightforward and adds the following features to the existing Find a VA Form MVP launched earlier this year:
    - 1. Search results now link to form detail pages where applicable
    - 2. A more informative message is displayed when a user searches for a form that has been deleted
    - 3. Users have the ability to sort search results by _Form Last Updated_ date
   
### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/contact-center

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by starlow00** [comment]
Hi @jwoodman5 . Not sure if you wanted to see this first before sending it on. 
[17927 Find VA Forms_Product Guide_ST_123020.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5755542/17927.Find.VA.Forms_Product.Guide_ST_123020.pptx)

**Comment by starlow00** [comment]
Hello @MarciMcGuireGCIO. In the previous comment, I have attached a PPT file with minor edits for style guide consistency, as well as a couple of comments/suggestions on slides 1 and 14. Please let me know if you'd prefer it in a different format. Thanks! (cc @jwoodman5)

**Comment by MarciMcGuireGCIO** [comment]
Thank you!

**Comment by MarciMcGuireGCIO** [comment]
Note to self: Could not find an existing video for this product on the VA's YouTube channel.  I have [inquired on Slack](https://dsva.slack.com/archives/G01HTL622H0/p1609364966000100) if we can proceed with our Jan 12 launch and follow quickly behind (within a few business days) with a video.

**Comment by MarciMcGuireGCIO** [comment]
Updated PPT and PDF product guide are located in https://github.com/department-of-veterans-affairs/va.gov-team/upload/master/products/find-va-forms-redesign/contact-center

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO let's review this PPT together at today's SU.  Based on a quick glance, there are a few slides I think we need to change to fully show the product experience.   We can talk about the Product video as well.

**Comment by MarciMcGuireGCIO** [comment]
Ok, sounds good.

**Comment by MarciMcGuireGCIO** [comment]
Per above comment, the PPT has been updated to show search results that have an online tool.  Link has not changed.

**Comment by starlow00** [comment]
@clantosswett will send as resource to VEO contact. (cc @jwoodman5)

**Comment by jwoodman5** [comment]
@MarciMcGuireGCIO It looks like you updated the PDF version too, but can you please confirm before I send it off to VEO? Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Yes, that is correct. I exported a new PDF to correspond to the updated PPT.

**Comment by jwoodman5** [comment]
Thank you much, @MarciMcGuireGCIO!
