### ISSUE TITLE
Yellow Ribbon [EPIC]: Temporary message to improve search success rate

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#17938]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/yellow-ribbon-mvp-product-brief.md)

## High Level User Story/ies
As a Veteran in search of Yellow Ribbon schools, I need to know how to formulate my search so I can improve my chances of finding the school(s) I am interested in.

## Hypothesis or Bet
If we provide Veterans with some simple instructions on using complete school names rather than abbreviations, we bet that they will be able to find the information they are looking for more quickly.

## OKR
Value: Veterans will not need to refine searches as often to get the desired results.

## Definition of done
- Draft message
- Design message placement
- Get message approved/refined by Content team
- Get message and placement approved/refined by Accessibility team
- Add message to Yellow Ribbon search page
- Review message on Staging
- Approve on Staging
- Deploy to Production

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman This is the search tip message I mentioned in the kickoff last Friday.  I believe the consensus was that we did not need a full Collab cycle since it was simply adding a message to help users better formulate their search term.  Can you please confirm that I understood that correctly?  Thank you!

**Comment by shiragoodman** [comment]
Correct. you don't need to go through full Collab Cycle. I see Peggy provided some content guidance so that's great. @allison0034 would you take a glance and see if there's any design concerns? If not, @MarciMcGuireGCIO you should be good to go.
