### ISSUE TITLE
Homepage - update appointment label for phone-only

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17933]
## Issue Description
As a user, I would like to see when I have a confirmed VA appointment over the phone so that it's clear when I don't have to go in to a VA location.

---

## Acceptance Criteria

- [ ] If appointment is phone-only, display appropriate card state on homepage

- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs:
- Desktop/Tablet: https://adhoc.invisionapp.com/share/7MZT9KV6UAY#/screens/441320010
- Mobile: https://adhoc.invisionapp.com/share/7MZT9KV6UAY#/screens/441320009

- [ ] CONTENT - Label text matches the guidance from the Content team:

> VA APPOINTMENT over the phone

## Definition of Done

- [ ] ACs are met

- [ ] Appointment card documentation is updated https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md

---
## Additional Notes
- Backend dependency - https://issues.mobilehealth.va.gov/browse/VAOSR-1334

### Out of Scope
The additional instructions text in the details

**Comment by laurenernest** [comment]
@jenniemc I don't see this updated appointment card in the documentation. Can you get a screenshot please?

>  Appointment card documentation is updated https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md

**Comment by jenniemc** [comment]
You got it. The appointment card documentation is updated with the VA phone screenshot
