### ISSUE TITLE
Detail page borks for VHA location (FL)

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#17944]
## What happened?
"Lecanto VA Clinic" detail page borks when the name is clicked from the search results list. Other locations (ie: "Brooksville VA Clinic") in the same result list link successfully to detail pages. 

## Steps to Reproduce
Search for Lecanto, FL/VA Health (https://www.va.gov/find-locations/?address=Lecanto%2C%20FL&facilityType=health&pag[…]16%2C-82.4876&context=Lecanto%2C%20Florida%2C%20United%20States)

Error on https://www.va.gov/find-locations/facility/vha_673GH: `breadcrumbs.js:58 TypeError: t.toFixed is not a function`
The json looks good on https://api.va.gov/v1/facilities/va/vha_673GH 

## Desired behavior
VA health facilities have functional detail pages available from the results list. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
I can't reproduce this given the info provided.

Is this browser-specific?

What do you mean by "borked"?

**Comment by mpelzsherman** [comment]
Tested this in production with IE11, seems to be working fine.

**Comment by mmiddaugh** [comment]
@davidconlon this issue seems to have been resolved.
