### ISSUE TITLE
Create Thumbnail View for Dependent Verification

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#17947]
## Background
Dependency Verification will have some twists and turns and we should create a map of what the different possibilities might be.

## Considerations
- Using the View Dep page, we can check if there has been update within a year and if not, then adjust buttons from default to "Is this correct, Y/N?"
  - Yes: Submit the #538 on their behalf, saving to eFolder as receipt, and affecting the diary entry
  - No: Go to the 686
- Modal introduction might be a second stage or separate flow

## Tasks
- [x] Map out high level thumbnail views of potential user journeys

## Acceptance Criteria
- [x] Share user journeys with team, link in this ticket

**Comment by sporeboy** [comment]
Initial draft of verify/view/change dependents diagram complete: https://xd.adobe.com/view/95773c75-de5a-4e55-8c35-34a91425155d-c024/
