### ISSUE TITLE
Outage Notification Procedure Implemented for Contact Centers

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#17950]
## User Story

_As a contact center agent, I want to be notified when there is a planned or un-planned outage so that I can inform and assist Veterans more efficiently when contacted regarding outages_

## Expected Behavior

_Contact centers should be notified in advance of planned outages on VA.gov. They should also be notified automatically or as quickly as possible when un-planned outages occur._

## Acceptance Criteria

- [ ] _Define planned outage communication procedure for contact centers_
- [ ] _Implement planned outage communication procedure for contact centers_
- [ ] _Define un-planned outage communication procedure for contact centers_
- [ ] _Implement un-planned outage communication procedure for contact centers_

**Comment by jwoodman5** [comment]
No documented policy or procedure currently. We need to figure if/how/when contact centers currently get notified and documented requirements to provide proactive notifications.

**Comment by Kimberley2019** [comment]
@edpearson20 will be looped in when/if it comes to technical abilities for this.

**Comment by jwoodman5** [comment]
Started conversations to understand our current outage notification procedures and learned there have been talks in the past about this. It seems to be rather complicated and lost steam. There are two distinct components - unplanned outages and planned outages. Our monitoring and associated notifications are not streamlined (from what I heard) for unplanned outages and the major complexity lies there. For planned outages, I will be working on a communication pipeline.

**Comment by Kimberley2019** [comment]
@clantosswett Are you aware of any historical information around outage notifications?

**Comment by jwoodman5** [comment]
@Kimberley2019 Chante and I have chatted about this and it really comes down to formalizing processes within VSP and ensuring we (and the contact centers) are included in the chain of communication.

**Comment by Kimberley2019** [comment]
My apologies @jwoodman5 That's what I get for just jumping in to things. ;)

**Comment by jwoodman5** [comment]
> My apologies @jwoodman5 That's what I get for just jumping in to things. ;)

Haha, good things! I appreciate your diligence!
