### ISSUE TITLE
Task: Accessibility Spot Check for Spanish Corona FAQ (Jan 12)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17964]
Reminder to do an accessibility spot check on Jan 12th....

**Comment by SKasimow** [comment]
Hi @youngfreezyVA is this complete or do I need to update the date?

**Comment by youngfreezyVA** [comment]
it’s complete.

**Comment by SKasimow** [comment]
Closing out as completed.
