### ISSUE TITLE
Implement Google Analytics on Spanish Corona FAQ page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17962]
For implementation of Google Analytics once spanish version of FAQ page is in Drupal

## User Story 1: 

_As a PM I would like to have GA implemented on the new spanish page Corona FAQ page so I can track and measure metrics (should match current English page tracking of this page).

## User Story 2: 

_As a PM, I would like to add click event tracking to the link/toggle on the new spanish Corona FAQ pages which will enable users to click over to view the English Corona FAQ page (the link will be placed above h1).

## Expected Behavior

_I would like to see the same data currently available on the English version of the pages via GA reporting or through DOMO. 
_I would like to see data for clicks on new links added to English and spanish pages

## Acceptance Criteria

- [ ] _Confirmation that page is sending data to GA

**Comment by SKasimow** [comment]
@youngfreezyVA hi - can you estimate this ticket yet?

**Comment by youngfreezyVA** [comment]
i would estimate this as a 3, the points field isn't showing up for some reason

**Comment by SKasimow** [comment]
@youngfreezyVA Closing as completed.
