### ISSUE TITLE
Fix inconsistencies of title casing of certain terms on Veteran-facing pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#1796]
User Story or Problem Statement
There are several terms used on benefit pages where the capping is inconsistent. Some pages these terms are lowercase, others they are capped, and some we even have written both ways on the same page. Examples: Veterans Pension, Aid and Attendance, Vocational Rehabilitation and Employment. A Word doc is attached with more examples and the pages they can be found on.
[https://app.zenhub.com/files/133843125/7abad06f-6615-49a7-abd1-0a2c1a7ccb90/download](https://app.zenhub.com/files/133843125/7abad06f-6615-49a7-abd1-0a2c1a7ccb90/download)

Terms to update:
- [x] Veterans Pension (should be capped)
- [x] Veteran-owned small business (should be lowercase when spelled out)
- [x] Vocational Rehabilitation and Employment (should be capped when using full name)/voc rehab (lowercase)
- [x] direct deposit (lowercase)
- [x] Character of Discharge (capped when referring to Character of Discharge review process)

## Goal
Terms need to be consistent in capping across all pages and all hubs and the correct capitalization should be added to the VA.gov style guide.

## Objectives or Key Results this is meant to further
Terminology needs to be consistent in order to inspire trust and confidence in our customers. 

## Acceptance Criteria
- [x] Discuss terms with content team during Content Weekly meeting to determine if there is any backstory on how we should be capitalizing them. 
- [x] Establish the correct style for terminology, updating the affected pages in Drupal
- [x] Add/update correct terminology in style guide

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Karak888** [comment]
@RLHecht to send out documentation and this will be disussion for wider group.  @peggygannon discrepencies between vets.gov styling with whats on live site.  To be discussed at next content meeting @jenniferlee-dsva

**Comment by RLHecht** [comment]
Just discussed list in Content Weekly meeting (9/24). Making changes to live pages and updating information in style guide where necessary.

**Comment by RLHecht** [comment]
@peggygannon I have updated all "Veteran-owned small business" references in Drupal on the pages below. Can you please review and publish?

- https://www.va.gov/careers-employment/veteran-owned-business-support/
- https://www.va.gov/careers-employment/

**Comment by RLHecht** [comment]
@peggygannon I updated the "direct deposit" reference in Drupal on this page. Can you please review and publish?

- https://www.va.gov/disability/

**Comment by RLHecht** [comment]
@peggygannon I updated the "Character of Discharge" reference in Drupal on this page. Can you please review and publish?

- https://www.va.gov/disability/eligibility/

**Comment by RLHecht** [comment]
@peggygannon I updated the "Vocational Rehabilitation and Employment" reference in Drupal on this page. Can you please review and publish?

- https://www.va.gov/claim-or-appeal-status/

**Comment by RLHecht** [comment]
@ncksllvn Please change the text in this green button to read "Apply for Veterans Pension benefits" (cap the word Pension): https://www.va.gov/pension/eligibility/

Also on the page it clicks through to: https://www.va.gov/pension/application/527EZ/introduction change the H1 to cap the word Pension so it reads "Apply for Veterans Pension benefits." It also needs to be changed in the text above the subway map and at the bottom of step 2 "Learn about Veterans Pension rates." 

I can also make these changes on this second page if you can show me where it is.

**Comment by ncksllvn** [comment]
@RLHecht just made those updates - should be live in an hour!

**Comment by Karak888** [comment]
closing this issue as updates have been made.

**Comment by ncksllvn** [comment]
@RLHecht alrighty, just did another sweep so it should be corrected by EOD tomorrow
