### ISSUE TITLE
OCTO Health - COVID - VSA-QA Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#17965]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

**NOTES**:
- QA test-scope for this **content language-translation** project is limited to **functional React-widgets**, as VSA-QA has no language-expertise to validate translated-content.
- The only functional, React-widgets on this page are **accordions**, and testing will be limited to these elements.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- [Product/Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/spanish-translation/coronavirus-mvp/product-outline.md)
- Product/Feature Epic: \[provide link]
- Product/Feature Copy deck(s): \[n/a]
- Product/Feature Design prototypes: \[n/a]

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: 
Content/IA: 
Front-end: 
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: \[n/a -- the only functional elements on the translated page will be accordions, which doesn't warrant any use-cases documentation]

## How to configure this issue

- [ ] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Product references provided by Product Team.
- [ ] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 2 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@SKasimow , all test-runs completed.  QA-artifacts links are below, and will also be updated in Staging Review ticket #17392 .

100% Passed - no defects found.

[Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1156)
[Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/183&group_by=cases:section_id&group_order=asc)
[no Coverage for References (Cases) report - the accordions tested are not specific to this product.]
[Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/182) - no defects found.

**Comment by SKasimow** [comment]
@tlei123 Nice - thank you for quick turn-around!

cc: @youngfreezyVA @DanielleThierryUSDSVA

**Comment by SKasimow** [comment]
Closing as completed.
