### ISSUE TITLE
Content Build Separation: Run content validation script on a schedule in Jenkins

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#17968]
## Description
As part of the content build separation epic, we pulled accessibility tests out of the Jenkins pipeline and would like to run them on a daily schedule (4pm ET - just trying to schedule after the deploy, so if there's a better time, that's fine too). We'll need it to send failures to slack as well, but I have that commented out in the script right now since we're not releasing yet.

## Background/context/resources
I pulled the relevant jobs into a file to be run https://github.com/department-of-veterans-affairs/content-build/blob/master/Jenkinsfile.integration -- if any updates need to be made, please feel free, or let me know and I can make them.

As an example, the schedule job should be running the setup, build, and integration parts of this: http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fcontent-build/detail/feature%2F7953-create-content-validation-script/223/pipeline/

## Technical notes
We tried getting this working in Circle, but were not success. If Ops could help getting that set up, that would be fine as well, ultimately we just need the job running on a schedule and don't necessarily care where.

---

## Definition of Done
- [ ] Jenkins Integration job run on a daily schedule

## Links
**Background**: https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/7953
**Task**: https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/7964
**Epic**: https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/2719

**Comment by timwright12** [comment]
@jhouse-solvd @dginther I submitted this PR https://github.com/department-of-veterans-affairs/devops/pull/8334 -- if someone could let me know if it solves this issue, or if we need to do more work to get this active in Jenkins, it would be much appreciated!

**Comment by jhouse-solvd** [comment]
@timwright12 - sorry for not responding sooner. I see that the PR was merged, and I know that there are some relevant conversations happening now. let me know if there is anything specific needed on this ticket at this time?

**Comment by timwright12** [comment]
@jhouse-solvd this ticket can be closed out now that content separation is released

**Comment by jhouse-solvd** [comment]
@timwright12 - excellent. thank you. 

Closing.
