### ISSUE TITLE
508-defect-2 [COGNITION]: Contact Us - Table of contact links and information must have well-formed HTML

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#17984]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a screen reader user, I want to hear column headers announced correctly as I move through the table of contact information and hours of operation.

## Details

The "Call Us" table was not announcing the second column heading during the first round of screen reader testing. I dug into the HTML and noticed the table is using multiple `<tbody>` elements, which don't seem necessary given there's no sections or divisions in the table. Screen shot attached below.

## Acceptance Criteria

- [ ] Table uses just one `<tbody>` element
- [ ] Table retains correct responsive layout handling for mobile width viewing
- [ ] Columns announce correctly to screen readers
- [ ] No axe errors are shown by browser plugin or CI/CD axe checks

## Environment

* http://preview-prod.vfs.va.gov/preview?nodeId=8472 (must be on the network)

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)
* [MDN: Tables with multiple bodies](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody#Multiple_bodies)

## Screenshots or Trace Logs

![Screen Shot 2020-12-31 at 11 24 11 AM](https://user-images.githubusercontent.com/934879/103421072-22ef8c00-4b60-11eb-8220-6ddf1e899a16.png)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you try to resolve this?

**Comment by RLHecht** [comment]
@1Copenut is the issue with HTML in the headers of each column in the table? If so, that's something front end related because content editors just plug in the text. I did add in line breaks in the third column to keep the "Monday through Friday" on one line and the times on the second line. Trying to figure out what needs to be fixed here and whether it's for the CMS team or front-end.

**Comment by 1Copenut** [comment]
@RLHecht The table on the page should only have one `<tbody>` tag inside it. Right now each row is being rendered in HTML as a `<tbody>` and I was having trouble parsing the table with some screen readers. It's permissible to have multiple body elements, but this doesn't feel like a situation where we'd want to use them.

**Comment by RLHecht** [comment]
Thanks, @1Copenut @brianalloyd This task seems to be for FE. Not sure of Nick and Kelson's priorities in upcoming sprints, so do you want to take a look and assign? Thank you!

**Comment by ncksllvn** [comment]
I think this work was finished yesterday as a side effect of https://github.com/department-of-veterans-affairs/vets-website/issues/15910

**Comment by ncksllvn** [comment]
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/38305272-1214-4608-8401-4380eaeaa32d)

@brianalloyd we can add this to our sprint and then close it

**Comment by brianalloyd** [comment]
Thanks @ncksllvn, Validated and closing.
