### ISSUE TITLE
Refactor "address_validation" Load Tests for Locust 1.x

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#17989]
# Tasks
- [x] Test the refactored code by executing the load test
- [x] Review execution results and ensure that the test run looks normal
- [x] Record the results of the load test in order to establish a baseline

**Comment by rjohnson2011** [comment]
Refactored and populated using a CSRF token and Cookie from the staging endpoint.
Got a majority of failures 23920/23289(97.36%), though some successes.
