### ISSUE TITLE
Refactor "coronavirus_chatbot" Load Test for Locust 1.x

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#17995]
# Tasks
- [x] Test the refactored code by executing the load test
- [x] Review execution results and ensure that the test run looks normal
- [x] Record the results of the load test in order to establish a baseline

**Comment by rjohnson2011** [comment]
Rewrote endpoint per `https://staging.va.gov/coronavirus-chatbot/` and changed from POST to GET request.
