### ISSUE TITLE
Automatically deploy/remove DS Logon outage banner

### ISSUE THREAD

**Issue by davidsbao** [department-of-veterans-affairs/va.gov-team#180]
_This issue requires discovery, and estimation on the agreed upon solution approach_

## Purpose
As a Veteran using digital services, I want to know if I will be able to use my DS Logon credential to access the benefits and services on VA.gov.

## Background
When DS Logon is unusable, users need to be warned that they may not be able to use their DS Logon credential to log in to VA.gov.  If they already have an MHV or ID.me credential, then they will be able to use one of those to still be able to log in and access the same benefits and services; if they do not, then they can create a new ID.me credential.

Our current process of communicating this is through a banner on the login modal that warns users that DS Logon may not be working. This banner is manually managed through a PagerDuty alert, and the typical workflow is as follows:
- Email notification is received by a VFS team member (e.g. certain DSVA folks are on a list serve) from the eBenefits team saying that DS Logon is down (since eBenefits itself goes 100% down if DS Logon isn't working)
- VFS team member notifies the #vetsgov-devops Slack channel that the banner needs to go up
- VSP engineer goes into PagerDuty and manually sets the banner for a specified amount of time
- Either the specified time expires, or a VFS team member notifies #vetsgov-devops that DS Logon is back up and running, at which point the PagerDuty alert needs to be manually taken down

## What We Need to Do
For the vast majority of DS Logon outages, we need to be able to have the banner be deployed and removed automatically. That way, we can eliminate the need for the manual steps above to be followed.

## Definition of Done
- If a DS Logon outage is detected, then the warning banner should be automatically deployed
- If a DS Logon outage is cleared, then the warning banner should be automatically removed

#### Considerations
- DS Logon is rarely entirely offline and inaccessible, outside of scheduled maintenance windows (such as the occurrence from Saturday, June 1, 2019, at 0900 ET to Sunday, June 2, 2019, at 1500 ET). The more typical "outage" is more of a "brown out" where it can become increasingly slow to load the DS Logon login page, and subsequently the login requests themselves may become increasingly slow (e.g. 30-90 seconds). There have also been times where some users may encounter issues with DS Logon, but others are still able to log in successfully. We will need to strike a balance to be able to automatically deploy/remove the banner, but not do either action too prematurely.
- We will most likely want to also have a manual method of controlling the banner when necessary (e.g. scheduling the banner for a period of scheduled maintenance)
- We will most likely want to have automated alerts posted into Slack when the banner is automatically deployed/removed

**Comment by davidsbao** [comment]
cc: @leahbannon @batemapf

**Comment by davidsbao** [comment]
Per @batemapf - may want to consider #100 along with this item.

**Comment by batemapf-usds** [comment]
Thanks @davidsbao. Re: #100, was looking specifically at this [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/100#issuecomment-498784941).

**Comment by batemapf-usds** [comment]
In addition to:

> Email notification is received by a VFS team member (e.g. certain DSVA folks are on a list serve) from the eBenefits team saying that DS Logon is down (since eBenefits itself goes 100% down if DS Logon isn't working)

DSVA also receives outage email notifications about the Defense Manpower Data Center (DMDC) which is the DS Logon data center. These are delivered to a shared VA mailbox. These notifications include links to the VA incident tickets (guessing these are ServiceNow tickets).

**Comment by annaswims** [comment]
DS Logon availability is currently a blind spot in our monitoring tools.  We don't make any calls directly from vets-api do DS Logon and the user is redirected to DS logon and then redirected back if their login is successful.

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/180 could be helpful in detecting brownout situations.

**Comment by annaswims** [comment]
@boris-ning-usds made a tool that is no longer active to monitor DS logon. https://github.com/fartbagxp/monitor-dslogon . 

We could possibly revive/replicate it, but I think the most cost-effective way might be just to look at the ratio of login attempts to successful logins.

My proposed approach is:
On the backend - 
*  add a metric to prometheus/Grafana for login attempts by type
*  after baseline metrics have been gathered, add an alert rule that triggers when the rate of successul logins to login attempts falls below the threshold. 

On the frontend - 
* Change the DowntimeNotification banners to reference the /backend_status api, rather than the /maintenance_windows.  backend_status would include  the current state of the service 

````
Valid statuses are:
- `active`: The service is enabled and has no open incidents.
- `warning`: The service is enabled and has one or more acknowledged incidents.
- `critical`: The service is enabled and has one or more triggered incidents.
- `maintenance`: The service is under maintenance, no new incidents will be triggered during maintenance mode.
- `disabled`: The service is disabled and will not have any new triggered incidents. 
````

**Comment by annaswims** [comment]
It would be best if the selected solution could also apply to id.me and MHV logins as well.  

Even more broadly, there are several different external services we get paged for only to put up a downtime banner.  It would be nice if we could automate the banners and only get paged for severe/prolonged events.
