### ISSUE TITLE
Refactor "facilities_api" Load Test for Locust 1.x

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18006]
# Tasks
- [x] Test the refactored code by executing the load test
- [x] Review execution results and ensure that the test run looks normal
- [x] Record the results of the load test in order to establish a baseline

**Comment by rjohnson2011** [comment]
`GET,/services/va_facilities/v0/facilities?lat=XX&long=XX,403 Client Error: Forbidden for url: /services/va_facilities/v0/facilities?lat=XX&long=XX,56726`

Need to generate API key, not sure where.
