### ISSUE TITLE
Refactor "hca_ee" Load Test for Locust 1.x

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18013]
# Tasks
- [x] Test the refactored code by executing the load test
- [x] Review execution results and ensure that the test run looks normal
- [x] Record the results of the load test in order to establish a baseline

**Comment by rjohnson2011** [comment]
Tested with fresh sessions.json and getting `GET,/v0/health_care_applications/enrollment_status,404 Client Error: Not Found for url: https://staging-api.va.gov/v0/health_care_applications/enrollment_status,9645`
