### ISSUE TITLE
Refactor "preneed" Load Test for Locust 1.x

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18019]
# Tasks
- [x] Test the refactored code by executing the load test
- [x] Review execution results and ensure that the test run looks normal
- [x] Record the results of the load test in order to establish a baseline

**Comment by rjohnson2011** [comment]
Test seems to run but throws a warning in the logs, may need additional refactoring. Timeboxed this and attempted before moving on to next one.
