### ISSUE TITLE
Refactor "ppiu" Load Test for Locust 1.x

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18018]
# Tasks
- [x] Test the refactored code by executing the load test
- [x] Review execution results and ensure that the test run looks normal
- [x] Record the results of the load test in order to establish a baseline

**Comment by rjohnson2011** [comment]
Am able to generate the GET portion of the loadtests but am unable to find the corresponding POST endpoint for payment_information in the app to spoof the cookie and CSRF token.
