### ISSUE TITLE
PTSD Review with SMEs for 526

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18039]
## User Story

_As a user I would like to have this feature because it would help me with this pain point_

## Expected Behavior

_Add expected behavior of the described feature here_

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by vhenry07** [comment]
Closed complete.
