### ISSUE TITLE
Fix SIP Data Post-Fix (Post #17595)

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18037]
## User Story
I want to be able to submit my form without errors.

## Expected Behavior
Bad SIP data that was manipulated by the inflection bug is no longer preventing successful submission. The details is to what is happening is in #17595.

## Acceptance Criteria
- [ ] Cross reference impacted veterans to submission attempts (before November we did not know whether someone attempted to submit but after November we have that data)
- [ ] We send an email to impacted veterans like we did for PTSD issue - possibly
- [x] Is there a way to save the users into a script so we can run the SIP data in the future to see if anyone has no more SIP and therefore we can conclude they submitted?

**Comment by annaswims** [comment]
I have a csv (note to self: ipf_fix.csv)that has the in-progress form id, user_id and email address (if they got that far in the form) of each form that was updated by https://github.com/department-of-veterans-affairs/vets-api/pull/5651

**Comment by annaswims** [comment]
Because we know who already clicked in this case, I'm open to re-submitting on behalf of the veteran.

**Comment by edmangimelli** [comment]
related https://github.com/department-of-veterans-affairs/va.gov-team/issues/18510 ?
