### ISSUE TITLE
[Design] Mock-up first time user experience (MyVA Dashboard)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18044]
## Background
We need to create the design for the first time user experience.

## Tasks
- [ ] Create mock for the first time user experience
- [ ] Review with Matt/Samara

**Comment by tressaellen** [comment]
@Samara-Strauss @mshea0606 Here is a first pass at wireframes for a FTUX for MyVA.

![My VA FTUX desktop.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/0134dfbf-c592-4182-8626-008784d7e266)

![myVA FTUX mobile.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/475f0158-6133-406a-a5a7-5db8f3fbae84)

**Comment by Samara-Strauss** [comment]
Thank you! Can you also throw together a mockup (in addition to this one — this one is great) that shows what it would look like if some of these applications were in progress? That'll be super helpful for documentation purposes, so we can clearly show how the design will progress and change. So, this would be something like:

- Show the health care application in progress.
- Keep the "get started" CTAs for disability and education as-is.

**Comment by tressaellen** [comment]
Here is a mock that shows what it would look like if the health care application was in progress.  If this looks good then we're good to close. :)

![My VA FTUX desktop step 1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f184bcaf-e297-4b6e-84fd-9ec4e39a6be6)

**Comment by Samara-Strauss** [comment]
Great! Thank you!
