### ISSUE TITLE
PTSD Best Practices Review - Working with Users with PTSD 

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18040]
## Problem Statement
This is part of our work to make the PTSD questionnaire better for our veterans.

We looked into best practice when it comes to designing for veterans - Trauma-informed Design Principles, as well as best practice when interviewing veterans with PTSD / Trauma.

## Description
A report was made outlining best practices used when interviewing people with PTSD and we used Trauma-Informed Designed Principles to outline best practice when designing for people with PTSD. 

Documet can be found here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/nov-2020/Trauma%20and%20UX%20design%20(1).pdf

[Trauma and UX design (1).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5810238/Trauma.and.UX.design.1.pdf)

## Acceptance Criteria
- [x] Do we produce some artifacts, guidance?
- [x] Does anyone need to approve anything (besides PM/PO)?

**Comment by chrvalla** [comment]
This project is completed. 
A report was completed and linked to this ticket.
