### ISSUE TITLE
Upgrade metalsmith-layout

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#18045]
The current version of metalsmith-layout (^1.6.5) in the vets-website and content-build process is throwing a deprecation warning because of Buffer() usage. This is fixed in the current version of metalsmith-layout (2.3.1).

This is a ticket to execute that upgrade.

**Comment by k80bowman** [comment]
I was able to get a version of this working, but there are a couple of tricks.

1. Alongside the update to the metalsmith-layouts plugin we will need to install the [jstransformer-consolidate](https://github.com/jstransformers/jstransformer-consolidate/tree/5e9d720bb572125c328a48d0265b5e341b690078) package.
    - NOTE: there is a jstransformer-liquid package, but it is old and out of date. I do not recommend using it (it breaks our build).
2. We will need to update the [config object for the layouts plugin](https://github.com/department-of-veterans-affairs/vets-website/blob/36a4078abeffd9a6ab6928091808252ffd512226/src/site/stages/build/index.js#L208-L213) inside `src/stages/build/index.js`.
    - remove `engine: 'liquid'`
    - add `engineOptions: { engine: 'liquid' }`

**Comment by timwright12** [comment]
From @k80bowman 
> We decided that, since it didn’t actually fix the problem we were looking at, it wasn’t worth updating the plugin at that time.
