### ISSUE TITLE
Duplicate side menu entry

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#1805]
## What happened?

On this page: https://staging.va.gov/disability/about-disability-ratings/

The "About disability ratings" accordion is duplicated. 

![Screen Shot 2019-09-16 at 1 34 02 PM](https://user-images.githubusercontent.com/136959/64985504-9d709b80-d88a-11e9-91d5-3bc60eadc576.png)

Note: This only applies to the staging.va.gov site. This is **not seen** on the [va.gov site](https://staging.va.gov/disability/about-disability-ratings/https://www.va.gov/disability/about-disability-ratings/)

## Specs:
- Device: all
- Browser: all
- Test User _(if applicable)_: none

## Steps to Reproduce

Go to the above URL, see a duplicate "About disability ratings" entry under "More resources". Both menus work as expected.

## Desired behavior

There should be a single "About disability rating" entry.

## Acceptance Criteria

- [ ] Single entry

**Comment by jenniferlee-dsva** [comment]
@Mottie - I wanted to flag that this page currently has a couple of in-flight things that might/not factor into this issue. But just wanted to make all the folks aware who are currently working various updates related to this page -- in both Drupal and Gh heroku/md.  

FYSA @JeffBarnesUSDS @jefflbrauer @kevwalsh @RLHecht @peggygannon

**Comment by Mottie** [comment]
This doesn't seem to be an issue anymore.
