### ISSUE TITLE
[Design] Review Erik's initial DD for Edu build 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18050]
## Background
Once the BE changes are in (listed below), Jim can review the initial build for DD for Edu. 
#17292 and #17294

## Tasks
- [x] Review DD for Edu on staging
- [x] Provide feedback

**Comment by Samara-Strauss** [comment]
This is blocked by #17292 and #17294 and can only be completed once those tickets are done.

**Comment by sporeboy** [comment]
First: this looks great! Amazing attention to detail!

These we relatively last minute text revisions and weren't in the prototype:
- Change success message for C&P change to, "We’ve updated your bank account information for your **compensation and 
pension benefits.** This change should take place immediately."
- Change success message for EDU change to, "We’ve updated your bank account information for your **education benefits.** Your next payment will be deposited into your new account."
- Remove periods from all field validation error labels; e.g. "Please enter your account number"
- In "Please enter **the** bank’s 9-digit routing number," change "the" to "your"
- For consistency, change "the" to "your" in "Please select the type that best describes **the** account"

That's all I have at the moment. :-)

**Comment by mshea0606** [comment]
Thanks @sporeboy! cc @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Thanks @sporeboy. This is great. FE implementation is in #18051.
