### ISSUE TITLE
Split same office page into multiple pages 

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18066]
## User Story
As a veteran with accessibility issues, I want the pages I use on VA.gov to be clear and not confusing.

## Expected Behavior
Go from one page to more than one (whatever was decided in the 508 story).

Based on #17814 accessibility feedback.

## Acceptance Criteria
- [ ] Josh Kim gives us a thumbs up

**Comment by kevinstachura** [comment]
Design for the 'same office' screen is located here:

https://vsateams.invisionapp.com/share/JHZTPGYBEYV#/441615733_HLR-Contested-Issues-Same-Office

Please let me know if you have any questions - thanks!

**Comment by luke-gcio** [comment]
Can we close this?

**Comment by kevinstachura** [comment]
Yeah we can close this. Link is here: https://vsateams.invisionapp.com/share/W5U21BDFTQK#/442028930_HLR-Contested-Issues-Same-Office
