### ISSUE TITLE
Enable GitHub Actions workflow to update the CMS content caching Lambda function from S3

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#18062]
# Background

The FE Tools team is looking into keeping a continuously updated cache of CMS content in S3 using a regularly running Lambda function (#17187).

As one of the initial steps, we'd like to add a workflow in GitHub Actions that builds the function and versions it.

# Requirements

The workflows for both the `vets-website` and `content-build` repos would require permissions to:
- Upload to S3
- Update and invoke Lambda functions
- List and update Lambda function aliases

Perhaps there could be a GitHub Actions user in AWS per repo with the policies that allow these operations.

As we are in the midst of an effort to separate the app and content builds, the `vets-website` and `content-build` repos will require access to different sets of buckets.

`vets-website` buckets:
```
vetsgov-website-builds-s3-upload

dev-va-gov-assets
staging-va-gov-assets
prod-va-gov-assets

dev.va.gov
staging.va.gov
www.va.gov

apps.dev.va.gov
apps.sandbox.va.gov
apps.staging.va.gov
apps.www.va.gov
```

`content-build` buckets:
```
dev.va.gov
staging.va.gov
www.va.gov

content.dev.va.gov
content.sandbox.va.gov
content.staging.va.gov
content.www.va.gov
```

# Specifics

Roughly, the steps in the content caching job in GitHub Actions might look like this:

Build the function in CI and zip it.
Get the checksum or hash of the zipped file.
Store the zipped file in an S3 bucket at a key corresponding to the checksum if it doesn't already exist.

Check the [list of function aliases](https://docs.aws.amazon.com/lambda/latest/dg/API_ListAliases.html) for an alias matching the checksum.
If an alias doesn't exist yet for the checksum:
- [Update and publish the function code](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionCode.html) using the archived function from S3.
- [Create the alias](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateAlias.html) for the new version of the function.

If the current branch is **not** `master`, [synchronously invoke](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html) the new version of the function (aliased with the checksum).

If the current branch is `master`, also get the version that the `master` alias points to. If the master alias doesn't match the version of the checksum alias:
- [Update the `master` alias](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/update-alias.html) to the version currently aliased with the checksum.
- Synchronously invoke the new version of the function (aliased with `master`).

**Comment by dginther** [comment]
In this case, we want to use Github Actions instead but I believe the below from Julian is still the best approach.

from Julian: 
For this use case what I'm imagining is:
- General CircleCI user created
- Role for required actions (trigger lambda, upload to s3, etc) created.
- CircleCI user has ability to assume said role based on actions necessary
  during deployment, role is assumed (requires awscli dependency which I imagine is addressed)
- actions performed using assumed credentials from role

**Comment by U-DON** [comment]
Updated title and description to reflect the move to GitHub Actions. Also updated the description with specific buckets that certain repos would need access to.

**Comment by jsev-io** [comment]
Thanks @U-DON 
Will work on creating some IAM resources related to this.
