### ISSUE TITLE
VRE Auth endpoint adjustment

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#18069]
## Issue Description

Throughout the development of the Ch31 form with our new integration partners VRE, we've had to adjust VRE staging endpoints while they develop on their side. They have asked for us to make staging adjustments again.

I have securely sent the auth url to @jbritt1

---
## Tasks
- [x] Change staging auth endpoint for va.gov

## Acceptance Criteria
- [x] endpoint is changed and deployed to staging

**Comment by jbritt1** [comment]
Credstash value updated with new value passed via Keybase.

Currently there is some WIP to hardcode versions. This change was accounted for within that pull request with [this commit](https://github.com/department-of-veterans-affairs/devops/pull/8294/commits/a47feb0d24d47a740528c74ea153f86a87f3d9a2).

**Comment by jbritt1** [comment]
#### Deploying to staging

vets-api-server: http://jenkins.vfs.va.gov/job/deploys/view/Staging/job/vets-api-server-vagov-staging/2033
vets-api-worker: http://jenkins.vfs.va.gov/job/deploys/view/Staging/job/vets-api-worker-vagov-staging/2012
