### ISSUE TITLE
Vets-website Deploys - Slack outage prevents website deploy due to failed notification

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18067]
## Description 

On 1/4/21 there was a Slack outage. During that time, a content-only deploy failed because the job failed to notify Slack. Presumably, this would also be an issue with any FE deploy (& others as well?) 

## To Do 

- [ ] Get DEPO & VSP leadership approval to change this behavior
- [ ] Update deploy of vets-website so that Slack notification job is not required

**Comment by meganhkelley** [comment]
Related to Slack thread with @ ncksllvn https://dsva.slack.com/archives/CBU0KDSB1/p1609782958429500

Nick Sullivan  19 minutes ago
you're correct - basically it seems like Slack being down would prevent us from doing any FE deployment

Nick Sullivan  19 minutes ago
for reference, this is the specific job that failed, http://jenkins.vfs.va.gov/job/deploys/job/vets-website-vagovprod/

Nick Sullivan  19 minutes ago
number 835

**Comment by meganhkelley** [comment]
@jhouse-solvd is this something your team would need to take lead on, or would FE tools push this forward and just keep y'all in the loop?

cc @Clark-W-Griswold @dginther

**Comment by jhouse-solvd** [comment]
@meganhkelley - forgive me for not responding sooner. I somehow missed some notifications but catching up now. is this something that is still needed?

**Comment by meganhkelley** [comment]
@jhouse-solvd no problem! Glad you found it though. This hasn't been addressed and is still theoretically an issue, as far as I know. Priority depends in part on our confidence in Slack's uptime.

**Comment by jhouse-solvd** [comment]
@meganhkelley - thanks for the info. we will keep this open and discuss with the team in the near future.

**Comment by jhouse-solvd** [comment]
@timwright12 - With all of the work that's been done with content deploys, is this still a dependency / point of failure?

**Comment by mchelen-gov** [comment]
This still exists in FE Jenkins config such as: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/Jenkinsfiles/deploys/warn-release-deploy#L106

resolution options:
- FE team wraps slack messages in try/catch for FE team Jenkins files
- FE teams updates FE team Jenkins files to use `common.slackNotify()` and Ops will take responsibility for `common.groovy`

**Comment by laineymajor** [comment]
Fixed in GHA implementation/not using jenkins. Closing.
