### ISSUE TITLE
[Design] Content updates for the contestable issues "why can't I find my issue" text

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18065]
## User Story
As a veteran, I want to make sure I am clear as to why my contestable issue is not eligible or showing up for HLR.

## Expected Behavior
Good content.  Update will be posted here by Luke after he hears from Lauren.

## Acceptance Criteria
- [ ] Approved by Peggy.
- [ ] Approved by Lauren (if changes are made)

**Comment by kevinstachura** [comment]
_"Update will be posted here by Luke after he hears from Lauren."_

@luke-gcio do we currently have this updated content (in an email for example)? Or is Lauren still working on the wording?

**Comment by luke-gcio** [comment]
We do not need to do this. OBE.
