### ISSUE TITLE
Create a web component for accordions

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18079]
## Issue Description
Create a web component for accordions

---

## Acceptance Criteria
- [ ] Clicking the gray header toggles content visibility
- [ ] Styles match current USWDS implementation
- [ ] Web component for accordion is in the design system

**Comment by caw310** [comment]
This ticket covers
HTML
CSS
Javascript

**Comment by bkjohnson** [comment]
The component has been created: https://github.com/department-of-veterans-affairs/component-library/pull/30

I am now preparing for a staging review by adding some axe tests: https://github.com/department-of-veterans-affairs/component-library/pull/43

**Comment by bkjohnson** [comment]
This is finished. We have two related PRs awaiting merge:

- https://github.com/department-of-veterans-affairs/vets-website/pull/15941 - This will make the new accordion component available in `vets-website`
- https://github.com/department-of-veterans-affairs/component-library/pull/31 - This will add documentation in storybook for the new accordion component.
