### ISSUE TITLE
[Design] Homepage iterations prototype

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18070]
Prototype for MVP and additional releases for the new homepage design.

**Link to prototype:** 
https://adhoc.invisionapp.com/share/A3ZQUMB8DH7

**Current state of appointment cards:** 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md

**Fields to show for new appointment types:** 
https://docs.google.com/spreadsheets/d/1zGfyAjwLgcU6KNpCQK09hQzKoN4ZmrM8u5Ejpitem1Q/edit?usp=sharing

**Content review notes:**
Our main goal is to make the appointments list easier to scan, and keep appointment cards consistent so they're easy to understand. This applies to both structure and language.

Some areas to focus on from a content perspective:
* [Appt statuses filter menu](https://adhoc.invisionapp.com/share/A3ZQUMB8DH7#/screens/440676963):
     * Label - Show by type
     * Types - Upcoming, Requested, Past, Canceled
* [The pending appointments alert](https://adhoc.invisionapp.com/share/A3ZQUMB8DH7#/screens/440676965)
* [The canceled appointments alert](https://adhoc.invisionapp.com/share/A3ZQUMB8DH7#/screens/440676962) - note that we may not have data to support this
* Names of the different appointment types:
     * VA Appointment
     * VA Appointment over the phone
     * Community Care
     * VA VIDEO CONNECT at home
     * VA VIDEO CONNECT at a VA location
     * VA VIDEO CONNECT using a VA device
     * VA VIDEO CONNECT at an ATLAS location	
     * Express Care request		
* The current CTA cards above the appointments list - Schedule an appointment and Express care.
* If possible we should reduce the repetitive use of the word "appointment." This will help reduce visual clutter by making language more specific.

**Comment by outerpress** [comment]
Added a link to the prototype, Narin's documentation of the current state, and a spreadsheet showing what fields should show for which appointment type in the new design (not final).

**Comment by peggygannon** [comment]
Thanks, @outerpress I've added some comments to the prototype. Do you also need me to review the other artifacts listed above?

**Comment by outerpress** [comment]
Thanks @peggygannon ! I made changes and responded to questions. No need to respond to the other artifacts - those are just there for general context on the feature.

I did add couple of new pages - nothing too new content-wise but they could use your eyes:
* List showing past appointments:
     * Mobile - https://adhoc.invisionapp.com/share/A3ZQUMB8DH7#/screens/441727919
     * Tablet - https://adhoc.invisionapp.com/share/A3ZQUMB8DH7#/screens/441732394
* List showing canceled appointments:
     * Mobile -  https://adhoc.invisionapp.com/share/A3ZQUMB8DH7#/screens/441727921
     * Tablet - https://adhoc.invisionapp.com/share/A3ZQUMB8DH7#/screens/441732395

**Comment by outerpress** [comment]
@peggygannon a couple more screens to look at, the home page CTAs @narin surfaced in https://github.com/department-of-veterans-affairs/va.gov-team/issues/18161

* All CTAs (mobile) - https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/441820504
* In context (mobile) - https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/441820505
* In context (desktop) - https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/441820506

**Comment by peggygannon** [comment]
Thanks, @outerpress thanks, I've added comments to the prototype for the home page CTAs. Let me know if you have any questions.

**Comment by outerpress** [comment]
Thanks! I made the changes, aside from the breadcrumbs (see the note I added there).

**Comment by peggygannon** [comment]
@outerpress OK, thank you. Updates to the CTAs look good.

**Comment by outerpress** [comment]
@laurenernest I think we should start another ticket for tweaks that come from the collab cycle and research feedback, once we figure out what we want to do there, since that seems like a new, if relatively minor, iteration. I'm closing this one out, but reopen if you want to work it another way.
