### ISSUE TITLE
[Epic] Communications permissions MVP (ie. notification preferences)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18071]
Note: The VA Profile team prefers to refer to this work as "Communications Permissions", but it's unlikely that language will be user facing. 

**Helpful artifacts:**
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
- [MVP UX decisions (and designs linked at bottom of page)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/design/notifications-ux-decisions.md)

**Comment by Samara-Strauss** [comment]
Closing. This is for the notification preferences MVP, which finished in 2021.
