### ISSUE TITLE
Update Pact documentation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18077]
## Details 

Fleet & Peter Hill wrote up some additional info about contract testing: https://vfs.atlassian.net/wiki/spaces/VI/pages/691208196/Contract+Testing

This needs to be consolidated with our current documentation about Pact: 
* [Contract testing README, for basic info about contract testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/contract-testing/README.md)
* [Pact user guide, for more detailed documentation about how to set up Pact for VFS teams](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/contract-testing/how-to-use-pact-for-contract-testing.md)

## To Do 

- [ ] Copy info from Confluence page into appropriate place(s) within va.gov-team docs (Eugene)
- [ ] Review va.gov-team docs for clarity before socializing with VFS teams
   - [ ] Eugene to review
   - [ ] Megan to review

**Comment by holdenhinkle** [comment]
Overall, the content in this [confluence page](https://vfs.atlassian.net/wiki/spaces/VI/pages/691208196/Contract+Testing) is already covered in [How to use Pact for contract testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/contract-testing/how-to-use-pact-for-contract-testing.md#introduction).

Closing this ticket now.
