### ISSUE TITLE
UI update | Center items in top nav bar 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18086]
## Acceptance Criteria
Make the following global styling changes to the top nav bar:

1. Center the page header in the top nav bar to give equal padding between top and bottom
2. Center the icon fa-chevron-left to the midline of 'Back' _(this may already be done)_

## Mockups
![b1f0d3f2-4072-4ab8-835e-c661289b08bf.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/7f3319fc-3dfe-4d9a-8f59-1db502c236f4)![4d6eb228-baee-42d8-a0d6-24ca8bf35b60.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/8dcf5fc7-c0f2-40a7-a8f8-c94b367e11ec)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/22/2021 - Looks good in random sampling, both iPhone and Android. closing.
