### ISSUE TITLE
Settings Landing Page accessibility issues

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#18089]
## What happened?
1. Android does not tab or arrow to "Settings" heading and describe page using the keyboard.

2. Android / iOS does not say "switch" for accessibilityRole on Touch / Face ID line.

## Specs:
- Device: Android Moto G7 and iOS iPhone 11 with appropriate page reader.
- Bluetooth keyboard

## Steps to Reproduce
1. Use Android phone with keyboard and tab or arrow key to go through the page.  Does not stop on Settings header.

2. Use either Android phone or iOS phone with appropriate page reader. When landing on Touch / Face ID line, it reads it as a menu item and doesn't say anything about the switch and whether it is selected or not. (Unless I'm doing something wrong.)

## Desired behavior
1. Android tabs or arrows to Settings header on the page.

2. Phones recognize the switch and denote whether selected or not.

## Acceptance Criteria
1. Android tabs or arrows to Settings header on the page.

2. Phones recognize the switch and denote whether selected or not.

## Bug Severity
- 4 - Low

## Linked to story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13957

## Screen shot(s) and additional information
n/a

**Comment by DF-ClaytonMatulich** [comment]
Regarding AC 1: Since header Titles are not actionable, they should not be able to be reached by tabbing to, or arrow keying to.

**Comment by digitalken** [comment]
PASS 1/21/2021 - On both Android and iOS, acknowledges switch or switch/button.
