### ISSUE TITLE
UI update | Copy change for address pages

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18088]
## Acceptance Criteria:

1. On the Personal information page, update the ListItem copy from "Residential Address" to "Home address"
     - Note that "address" should not be capitalized
     - Ensure that this change is also made on the corresponding page header
     - Update any a11y hints to reflect this change
2. Update "Mailing Address" to "Mailing address" in the following places:
     - **Personal Information** page (ListItem)
     - **Mailing address** page (page header)
     - **Letters** page (ListItem)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/11/2021 - Copy updated.  Moving to Design QA.
