### ISSUE TITLE
Document Social security in form patterns library

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18093]
## Issue Description
Document Social security in form patterns library

---
## Tasks
- [x] Document Social security in form patterns library

## Acceptance Criteria
- [x] There is documentation for  Social security in form patterns library
---

**Comment by CrystabelReiter** [comment]
Related tickets:https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/296
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/361

**Comment by CrystabelReiter** [comment]
Current masked version in covid vaccine form: https://github.com/department-of-veterans-affairs/vets-website/pull/15265
