### ISSUE TITLE
[Analytics] Identify data changes due to the Mission Act release

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#181]
## User Story
As a VA.gov platform product owner/stakeholder, I need to know if the users and goals for my product change due to the launch of the Mission Act so that I can determine if any metrics changes are due to my product adjustments or related to press launches.

## Objective
Analyze data to determine and document any changes the Mission Act may have on users, conversions, and successes on VA.gov.

## AC
- [ ] Analytics have been documented and shared with the team. 

### Research Resource
Analytics-Insights Issue #99 : This is more specific to the Colmery Act and how it affects the EDU team.

**Comment by joanneesteban** [comment]
@nedierecel On the analytics side of this, let's monitor users and goals to determine any shifts on edu login and forms (and other platform products) as public relations events occur and the Mission Act launches this week.

**Comment by nedierecel** [comment]
@joanneesteban In reviewing the subdomain https://missionact.va.gov, I noticed that this page is tracked to DAP (as expected) and to another Google Analytics and Google Tag Manager account that I do not currently have access to.

I'll monitor increases to the hub pages, but we do not have visibility on this particular page as an entry point.

Follow-up:
May you help locate stakeholders who could help us add our Google Analytics code to this page?

**Comment by joanneesteban** [comment]
@nedierecel Will track that down. There's a chance we won't get access to that, so you can continue to monitor any increases to hub pages as the primary for this issue.

**Comment by nedierecel** [comment]
@joanneesteban 

- *91% lift in Pageviews to /health-care/ hub when comparing the day Mission Act changes went into effect vs. the same day in the previous week (6/6/2019 vs. 5/30/2019)*: https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p184318975/_u.date00=20190606&_u.date01=20190606&_u.date10=20190530&_u.date11=20190530/

- *Expanding the date range from 6/6/2019-6/10/2019 vs. the previous period of 6/1/2019-6/5/2019 shows an increase in completed HCA goals*
https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goals-overview/a50123418w177519031p184318975/_u.date00=20190606&_u.date01=20190610&_u.date10=20190601&_u.date11=20190605&_.goalOption=1/

- *Biggest source of external referrers came from email from 6/6/2019-6/10/2019:* https://analytics.google.com/analytics/web/?authuser=0#/report/trafficsources-all-traffic/a50123418w177519031p184318975/_u.date00=20190606&_u.date01=20190610&_u.date10=20190601&_u.date11=20190605&_.goalOption=1/
