### ISSUE TITLE
STEM AD: Automated Decision Email Update

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#18115]
A. Confirm with Mikki that form in Find Forms search are going to stay there awhile OR redirects will be implemented if they move.

Form STEM Automated Decision Email (located [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-automated-denial-email.md)):

1. Update content document to include link to VA Form 20-0998 instead of "attachment" in this content: 

> We've enclosed a copy of VA Form 20-0998, "Your Rights to Seek Further Review of Our Decisions" for more information about these options. You can also download the required forms at www.va.gov/vaforms/ or by contacting us at (888) GI BILL 1 (888-442-4551) to request a form. 

Form is located here: https://www.vba.va.gov/pubs/forms/VBA-20-0998-ARE.pdf

2. Consider updating form to include links to these forms as well

> 
> - If you have new or previously unprovided evidence to prove your eligibility for this scholarship, you can file a Supplemental Claim by [completing VA Form 20-0995].
> - If you don't have new evidence but would like a more senior reviewer to look at your case, you can request a Higher-Level Review by [completing VA Form 20-0996].
> - If you don't agree with the decision on your Supplemental Claim or Higher-Level Review, you can ppeal to a Veterans Law Judge by [completing VA Form 10182].

Find those forms using this search: https://www.va.gov/find-forms/

3. Review with DEPO for blessing on update

4. Review with Education for awareness.

**Comment by amyknox** [comment]
Per UX team discussion: Please get Peggy's input on link style & content. We'll address email updates based on new requirements from EDU in a future story.

**Comment by JenLJ** [comment]
Peggy's feedback can be found at:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/18139
