### ISSUE TITLE
Mobile alert & step table appear on Closed Claims page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18129]
## What Happened?
The Closed Claims detail page displays the following elements:
- Mobile alert
- Claims step table

These elements are specific to the Active Claims detail page, and should **not** appear on the Closed Claims detail page.

## Steps to Reproduce
1. Navigate to Claims/Appeals page
2. Select "Closed" segmented selector
3. Select a claim from the list
4. Observe mobile alert & step table

## Desired Behavior
The Closed Claims detail page should not display the mobile alert and step table.

## Acceptance Criteria
See Desired Behavior. 

## Bug Severity
- 3 - Medium

## Linked Story
#15624: See AC #2

**Comment by digitalken** [comment]
PASS 1/8/2021 - No longer shows mobile alert and claims step table.
