### ISSUE TITLE
Fix the About Disability Ratings page due to a CMS anomaly

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#1812]
## User Story or Problem Statement

Problem description. Due to a CMS anomaly, we can't have a subway map with charts in it like in this disability page: https://vagov-content-pr-268.herokuapp.com/disability/about-disability-ratings/

## Goal
Change the organization of the page to remove the subway map and just use H4s that say "Step 1, Step 2, etc." 

## Acceptance Criteria
- [x] Update page in Drupal so CMS team can migrate it into Drupal.
- [x] Fix a few content issues due to SME feedback.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jenniferlee-dsva** [comment]
@RLHecht - Just caught one thing on the Github source. The "(not rounded)" text should actually be appearing as part of the h3 below where it appears now. 

**Screenshot here:** 

![image](https://user-images.githubusercontent.com/43381063/65003500-c3b42c80-d8c6-11e9-9c96-e39798e93692.png)

**Comment by RLHecht** [comment]
@jenniferlee-dsva I just moved that text to the chart. It's currently also styled as an H4. I was trying to have it be smaller text next to it but when I look in the preview, it's showing it on a separate line. Not sure if this would be the case in the Heroku instance but that is still not working so I can't check it.

**Comment by jenniferlee-dsva** [comment]
Perfect! Thank you @RLHecht !  Let's send this updated content over to Jeff Brauer and Kevin W. and just let them know we haven't been able to heroku preview it, so we'll do that in Drupal preview.

**Comment by RLHecht** [comment]
Just previewed these changes in Drupal and they all look good.

**Comment by Karak888** [comment]
closing this ticket as this work was previewed in Drupal.
