### ISSUE TITLE
Update API wrapper

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18137]
## Acceptance Criteria

1. Update API wrapper so that, if the access token is expired, the wrapper should refresh the token and reattempt the original request instead of throwing an error. If the refresh fails, take the user back to the login screen

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/14/2021 - Seems to be working correctly.  I've only seen the refresh working correctly, no need to send me back to the login page.  No errors, however!  Moving to Design QA.
