### ISSUE TITLE
Follow-on Content Review: STEM Automated Denial Email

### ISSUE THREAD

**Issue by JenLJ** [department-of-veterans-affairs/va.gov-team#18139]
Update: Links to applicable forms have been added and a few modifications have been made to directions on how to access forms.  Review is only needed within the "What you should do if you disagree with our decision" section since no other updates were made.

For the Edith Nourse Rogers STEM scholarship, VA wants to automatically send denial letters to individuals who don't meet certain scholarship criteria. The team was provided with the formal language for these denials, made revisions and needs a content review to ensure the denial emails meet VA content guidelines.

Document: [STEM Denial Email content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-automated-denial-email.md)

## Acceptance Criteria
- [x] Content feedback by Peggy/VSP team

**Comment by peggygannon** [comment]
@JenLJ 
As these links will appear in an email, I recommend we don't hyperlink the form name, but instead provide the full URL so people know where they will be redirected to. 

For example: 

If you have new or previously unprovided evidence to prove your eligibility for this scholarship, you can file a Supplemental Claim by completing VA Form 20-0995. Go to www.va.gov/find-forms/about-form-20-0995/ to download this form. 

If you don't have new evidence but would like a more senior reviewer to look at your case, you can request a Higher-Level Review by completing VA Form 20-0996. Go to https://www.va.gov/find-forms/about-form-20-0996/ to download this form. 

If you don't agree with the decision on your Supplemental Claim or Higher-Level Review, you can appeal to a Veterans Law Judge by completing VA Form 10182. Go to https://www.va.gov/find-forms/about-form-10182/ to download this form. 


You can read more about these options on VA Form 20-0998, "Your Rights to Seek Further Review of Our Decisions".  Go to https://www.va.gov/find-forms/about-form-20-0998/ to download this form.
