### ISSUE TITLE
Update Cypress environment variable viewport data with December, 2020 data

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#18134]
## Issue Description
The Cypress environment variable viewport data needs to be updated with December, 2020 data

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by holdenhinkle** [comment]
PR submitted - https://github.com/department-of-veterans-affairs/vets-website/pull/15535/files

**Comment by holdenhinkle** [comment]
Here's the Google doc that has the December, 2020 data - https://docs.google.com/spreadsheets/d/1NST-3GDZ-WLkhKdr0LT7xw1cnU3pkuctTGwEywFheGY/edit#gid=1856581931

**Comment by holdenhinkle** [comment]
PR for updating documentation was submitted, approved, merged - https://github.com/department-of-veterans-affairs/va.gov-team/pull/18140

**Comment by holdenhinkle** [comment]
`src/platform/site-wide/user-nav/tests/e2e/00-required.cypress.spec.js` is failing in CircleCI and is blocking.

Otherwise, this ticket is complete.

**Comment by holdenhinkle** [comment]
PRs have been approved and merged.

This ticket is complete.

**Comment by pjhill** [comment]
Great work!
