### ISSUE TITLE
Faraday client configuration spec set up is extracted into shared helper

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#1814]
## User Story or Problem Statement
As a VSP API engineer writing specs I want to use a common Faraday client configuration to avoid module namespace collisions. 

## Goal
Service class specs are easily written and highly performant, without repeating excess setup/teardown code.

## Acceptance Criteria
- [x] Specs identified where we're using a configuration, and extraction pattern applied
- [x] Faraday client methods are stubbed 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by LindseySaari** [comment]
Current specs using a configuration:

**Comment by LindseySaari** [comment]
Current specs using a configuration:
