### ISSUE TITLE
Write design doc for Web Component implementation

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18150]
## Issue Description

We have done some initial discovery around Web Components and have decided to write a design doc to serve as a record before further development happens.

---
## Tasks
- [ ] Write a design doc

## Acceptance Criteria
- [ ] Design doc is approved
---

**Comment by bkjohnson** [comment]
I'm planning on having the web component loader happen in `static-pages` inside of `vets-website`.

## Current vets-website metrics

`6.2M Jan 11 11:41 build/localhost/generated/static-pages.entry.js`

## Bundle size with web components

`6.3M Jan 11 11:54 build/localhost/generated/static-pages.entry.js`
