### ISSUE TITLE
Identify and Document Contact Center Resource Repositories

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#18166]
### Issue Description

We need to fully understand where product guides and videos are stored internally as well as how they are provided to contact centers to use as a resource and where they are stored for contact center use

---

### Acceptance Criteria
- [ ] _All items listed below are included in a single github document_
- [ ] _Internal product guide repository is identified and documented in our team space in github [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center)_
- [ ] _Internal product video repository is identified and documented in our team space in github [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center)_
- [ ] _External (contact center) product guide repository is identified and documented in our team space in github [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center)_
- [ ] _External (contact center) product guide repository is identified and documented in our team space in github [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center)_
- [ ] _Process for providing contact centers with product guides and product videos is identified and documented in our team space in github [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center)_

---
### How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starlow00** [comment]
Note: Tied to ticket [14318](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/14318).

**Comment by starlow00** [comment]
In progress, digging through and listing GitHub directory of CC repositories. Documenting in Word doc.

**Comment by Kimberley2019** [comment]
Finalized product guides and videos are stored internally by the VA.gov Contact Center team.  The location can be accessed below.

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/contact-center

Whether or not the individual product teams retain a copy for their repository is unknown.

We provide the VEO contact Center with approved product guides and videos by uploading them to their SharePoint site through our [SharePoint Upload Process](https://docs.google.com/document/d/1merXujj9Kz1jTiglWgL7q58oJRaq_4PGGiC-CWMTE5Y/edit).

**Comment by starlow00** [comment]
Limited at this point due to my lack of SharePoint access, but this gets us started:

[https://app.zenhub.com/files/133843125/66b6af39-4bd7-4298-b264-ed1cf129b051/download](https://app.zenhub.com/files/133843125/66b6af39-4bd7-4298-b264-ed1cf129b051/download)

**Comment by starlow00** [comment]
Up-to-date document in Google docs: 
https://docs.google.com/document/d/1DrJFtGxXDLw1hvy5LxclW4BWf-CQZs0xkeeBVlqZh0Y

**Comment by jwoodman5** [comment]
Updated github version of the document [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/contact-center-resource-repositories.md). Closing.
