### ISSUE TITLE
[Design] Update form labels on 10-10EZ

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18168]
## User Story

- As a Veteran, I would like the field labels under Dependents and Spouse Information to be labeled with their names because it would help reduce confusion when filling out those fields.

## Expected Behavior

- Field labels should correspond to the person that they are about

## Acceptance Criteria

- [x] Mockups created 
- [x] Field labels confirmed with VSP content
- [x] Mockups attached to Front end ticket

**Comment by jonathanjnelson** [comment]
Please see [mockups and documentation](https://preview.uxpin.com/903944290fe90e22d55c50f5c986d954a637cf6d#/pages/135618577)
