### ISSUE TITLE
Homepage - Update past appointment card styles

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18164]
## Issue Description
On the VAOS homepage, update the styles for past appointments.

---

## Acceptance Criteria
- [ ] Changes are behind the va_online_scheduling_homepage_refresh feature flag

- [ ] When VAOS homepage loads, default view is Upcoming appointments

- [ ] When selecting Past from dropdown, display past appointments

- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs:
- Mobile - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/wL9pyOm#Inspector
- Mobile template - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/kaglvRD#Inspector
- Desktop/Tablet - https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d/a/9PEAv3p#Inspector

**Comment by jbalboni** [comment]
@LanceGundersen Here's the guidance I got from @outerpress and @laurenernest on handling Express Care requests, based on their status:

Proposed/pending: 
- shows in upcoming page (if less than two days old)
- shows in past page (if more than two days old)

Canceled:
- shows in upcoming page (if less than two days old)
- shows in past (if more than two days old)
- always shows in canceled page

Fulfilled: 
- always shows in past page
