### ISSUE TITLE
KPI Dashboard Request for [Authenticated Experience - VA.gov]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18176]
# Metrics Reporting Request
## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Authenticated Experience Team: Matt Shea

  _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
      
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
  - [x] KPI Dashboard
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
- We are looking to have these metrics by the end of Jan so we can include them in the January KPI report.

## Analytics to Track Down
> Examples
![image](https://user-images.githubusercontent.com/60523453/103784943-98e46f00-5008-11eb-9096-0081493b80ec.png)
> - [ ] # of VA.gov profiles (# of users who logged into the profile in the past year*)
> - [ ] % of VA.gov Profiles that are LOA3 (segment of the above that are LOA3*)

## Which Product Questions are you trying to answer?
We are trying to determine interaction with the VA and also the utilization of the Profile.

## Additional Comments
- Let me know if you have any questions!  Thanks - Matt

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
@mshea0606 - hi! We're looking into the IA of our dashboards, and it looks like these are additional KPIs for your products. Would you say that these KPIs are under your Profile 2.0 product, or are these other Auth Exp parent product KPIs?

**Comment by joanneesteban** [comment]
@bmcgrady-ep 
- If these are Profile 2.0 KPIs, add to the current KPI dashboard & we'll re-evaluate the design of the dashboard 
- If these are for a different product, add a sub-page

**Comment by mshea0606** [comment]
These are KPI's for Auth Experience on VA.gov as a whole. 
So the product is VA.gov.

**Comment by joanneesteban** [comment]
Thanks, Matt! @bmcgrady-ep can you make this a sub-page?

**Comment by bmcgrady-ep** [comment]
Hi @JasonTheBearded - for this dashboard, we are going to need datasets for the following items:
- Total number of logins to VA.gov production by month and by year (event action = `Login - vagovprod`
- % of VA.gov Profiles that are LOA3 (a segment of the above where LOA = 3)
Let me know if you have any questions about the data we are looking for.

**Comment by JasonTheBearded** [comment]
@bmcgrady-ep what's a good start date for this dataset?

**Comment by bmcgrady-ep** [comment]
@JasonTheBearded - For the monthly dataset, July 2020 - Present.

**Comment by JasonTheBearded** [comment]
Thanks @bmcgrady-ep! Since this is a monthly dataset, do we only want to show full months? i.e. if run today the dataset would show monthly data for 7/2020 - 12/2020?

**Comment by bmcgrady-ep** [comment]
Yep, exactly!

**Comment by JasonTheBearded** [comment]
@bmcgrady-ep dataset set up, https://va-gov.domo.com/datasources/f13cdb2e-fd1f-4b72-8db6-0f2e82a30dd5/details/overview let me know if you need anything else!

**Comment by bmcgrady-ep** [comment]
Thanks @JasonTheBearded! The data between BigQuery and GA seems to be very different. You can see the GA reports in the [Domo dashboard](https://va-gov.domo.com/page/1223795645).  How exactly are the logins and the LOA3 logins being queried?

**Comment by JasonTheBearded** [comment]
Thanks for the check @bmcgrady-ep, looks like the filter looking for login event actions wasn't capturing all the events, I'm fixing that and making sure the BQ counts match to GA.

**Comment by JasonTheBearded** [comment]
Also to answer your question about LOA3, the query is checking that the value for the custom dimension index 22 is 3, which we had previously discussed was the location for LOA

**Comment by bmcgrady-ep** [comment]
Thank you!

**Comment by JasonTheBearded** [comment]
@bmcgrady-ep Query fixed and DOMO dataset updated, keep in mind because of the PII scrub the GA numbers will be lower than BQ. Let me know if you need anything else.

**Comment by bmcgrady-ep** [comment]
@JasonTheBearded - Thank you for getting the Domo dataset updated. It looks great!

@mshea0606 - I added you to the dashboard so you could look over it. Let me know if you have any questions!

**Comment by bmcgrady-ep** [comment]
@mandy-uxd  - When you have a chance, this dashboard is ready for a design review.

**Comment by Samara-Strauss** [comment]
Closing. This is no longer needed.
