### ISSUE TITLE
Get Contact Center Call Transfer Data

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#18189]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ianMcCullough-ob** [comment]
Hey @edpearson20, [here is a Google Doc](https://docs.google.com/document/d/1FCBJFDZy9DPdTRk8KS66BxcPK0yG1qb1OSqta3-2TTU/edit?usp=sharing) that outlines info I'm looking for. You should have write access to that doc, all others can only view.
