### ISSUE TITLE
Access for [Jonathan Nelson]

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#18182]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Jonathan Nelson
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Name of Team: Caregivers
   > Role: UX Designer and Researcher 
   > Company: Ad Hoc, LLC 

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD5HhkFp3mFPoi8tUCdqOLQHBWttbOUrC1Hbn9Dekt4q1mNRJLxAb71wYsPLgJzKXqxV/06k8ic5iZ6MuQLbcXUGEZofVZ9tKZ0neIJzYrdiIHZrqdkCe4tOIBljMOeXxz1LkxzRhP0pp1KGXlqZsH5ysrAXHlzJL+NqQspjzNkA12sOMywxew0RgtlqLczzY0WR1w3g6jUspcue3SY/NAi3v2EDG+Er49OemxLqFOO8RKzFJoXTjPrBcSYyDRirCAsNSlSLJuEONSu9kLh4hWf+aVYlC15tSFcY/HAT7XIUcDk2ggbPMWH7GSfr2Pd4PvnVFyUUl+ZvBOP7POU9Q5vjX5Y+vwWv0aizJVUjrxjHje676wnnuWBFbJU59YEs4xn76H0j9geBRVoWX4QZMy9QHKL9BQYBSUOR2dOlEZMtOEJUiydwqoGu56MentPau7DBZQjSOehjnNJiATS7Lqy4YgmLv57FB9yfd0Du6n8XYCJvreyNwayZiWMTzwS9U= jonathannelson@jonathalsonsmbp.lan
```

- [Grant AWS Console access?] No
  > YES / NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by jonathanjnelson** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by mydesignrocks** [comment]
Can we have them produce a standard (RSA-2048) key please

**Comment by jonathanjnelson** [comment]
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD5HhkFp3mFPoi8tUCdqOLQHBWttbOUrC1Hbn9Dekt4q1mNRJLxAb71wYsPLgJzKXqxV/06k8ic5iZ6MuQLbcXUGEZofVZ9tKZ0neIJzYrdiIHZrqdkCe4tOIBljMOeXxz1LkxzRhP0pp1KGXlqZsH5ysrAXHlzJL+NqQspjzNkA12sOMywxew0RgtlqLczzY0WR1w3g6jUspcue3SY/NAi3v2EDG+Er49OemxLqFOO8RKzFJoXTjPrBcSYyDRirCAsNSlSLJuEONSu9kLh4hWf+aVYlC15tSFcY/HAT7XIUcDk2ggbPMWH7GSfr2Pd4PvnVFyUUl+ZvBOP7POU9Q5vjX5Y+vwWv0aizJVUjrxjHje676wnnuWBFbJU59YEs4xn76H0j9geBRVoWX4QZMy9QHKL9BQYBSUOR2dOlEZMtOEJUiydwqoGu56MentPau7DBZQjSOehjnNJiATS7Lqy4YgmLv57FB9yfd0Du6n8XYCJvreyNwayZiWMTzwS9U= jonathannelson@jonathalsonsmbp.lan
```

**Comment by tskinn** [comment]
@jonathanjnelson you should be able to connect to socks proxy. Reach out in slack if you have any issues.
