### ISSUE TITLE
Output Drupal URL

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#1819]
## Task
Output the Drupal URL next to "Successfully piped Drupal content into Metalsmith!"

## Acceptance Criteria
- [ ] The URL is in the build log

**Comment by cvalarida** [comment]
Originally found in https://github.com/department-of-veterans-affairs/vets-website/pull/10270.

@jonpugh Turns out there's some overhead in getting the actual URL used where we're logging `Successfully piped Drupal content into Metalsmith!`. We do have this, though. Does this fill the need?
![image](https://user-images.githubusercontent.com/12970166/65001764-b89cd480-d8a5-11e9-9d54-116ad78fde4e.png)

**Comment by jonpugh** [comment]
Apologies @cvalarida that line came from our original PR and was submitted and merged a few weeks ago. (same with the file path of local cache log)

I can't find the PR right now, but if you look at the `git blame` for that logging, it was cherry-picjked or recommitted from our branch.

CC: @ElijahLynn

**Comment by cvalarida** [comment]
Sounds good! Thanks! :raised_hands:

**Comment by ElijahLynn** [comment]
I don't see this in latest master, we still need this I think.

**Comment by ElijahLynn** [comment]
Getting this on master. 

![image](https://user-images.githubusercontent.com/1504756/65283447-01de6580-daec-11e9-9f3e-baa7907fcdc1.png)

**Comment by cvalarida** [comment]
Looks like that screenshot is pulling from the cache, which wouldn't output any Drupal URL.

**Comment by ElijahLynn** [comment]
K, per Slack: `npm run build -- --pull-drupal` needs to be run, with the `--`. If `yarn` is used then the `--` is not needed.
