### ISSUE TITLE
Upgrade axios to fix vulnerability

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#18193]
Axios needs to be upgraded to remove a high severity vulnerability

Applies to `vets-website`, `content-build`, and `generator-vets-website`

- [x] `vets-website` [vulnerabilities](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot)
- [x] `content-build` [vulnerabilities](https://github.com/department-of-veterans-affairs/content-build/security/dependabot)
- [x] `generator-vets-website` [vulnerabilities](https://github.com/department-of-veterans-affairs/generator-vets-website/security/dependabot)

**Comment by meganhkelley** [comment]
Jhonny: We don't use axios dependency directly. From what we've seen there are dependencies that use axios as a dependencies. Either need to upgrade the 4-5 dependencies that use axios or we create exceptions. 

First step here is to determine a solution.

**Comment by meganhkelley** [comment]
Tim: I think yarn resolutions can force deps to use updated versions (assuming they work together)

**Comment by jhonnyoddball** [comment]
All high severity vulnerabilities were fixes in all 3 repos
