### ISSUE TITLE
VTK MVP Feedback

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#18200]
## Description

Since the MVP of the toolkit is available, we will need to get feedback from one VFS team to see what improvements or modifications can or should be done.

## Definition of Done
- [x] Feedback from VFS is collected
- [x] Proposed changes are captured in ZenHub tickets to be prioritized

**Comment by LindseySaari** [comment]
Notes from feedback meeting: https://docs.google.com/document/d/1dTUyY_8kWuTym_fNq6A54H3Ctl628kotP0lQMpoF_ss/edit?ts=5fff8ea5

**Comment by LindseySaari** [comment]
Other comments:

I think that slicing this into models/libs/controllers is a good way to chunk
the workload.
Engine Tasks
  Generate new engine (3pts)
  Copy PPMS Models/Tests to Engine (5pts)
  Copy Lighthouse Models/Tests to Engine (3pts)
  Copy V1 PPMS Client/Tests to Engine (5pts)
  Copy Lighthouse Client/Tests to Engine (3pts)
  Copy V1 VA Controller/Tests to Engine (5pts)
  Copy V1 CCP Controller/Tests to Engine (3pts)
  Copy V1 VA_CCP Controller/Tests to Engine (3pts)
  Mount Engine to /v1/facilities (Flipper?) (5pts)
Engine Questions
  How do we want to handle multiple engine versions
  How do the engines interact with initializers (StatsD)
