### ISSUE TITLE
BE Tools Onboarding Improvement

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#18201]
## Description

The onboarding process right now is the responsibility of one developer.  We need to consider what improvements to the content we can make to ensure we are providing the most value to the teams onboarding, and allow for our team to share the responsibility.

## Definition of Done
- [x] Content of the onboarding is reviewed and modified as needed
- [x] A shared document is created in Confluence for BE Teams members to utilize 
- [x] A rotation type program is agreed upon in the BE Tools team

**Comment by thilton-oddball** [comment]
As I prepared to transfer the info I have used in the past for the BE Tools orientation for new VFS members into Confluence, I realized that Michael Fleet has already created a page back in November that has all of the information I have used plus a little more.

https://vfs.atlassian.net/wiki/spaces/~800255295/pages/754286628/VFS+Orientation

**Comment by alexpappasoddball** [comment]
@thilton-oddball The documented listed above is in Fleets personal space in his scratchpad section.  Lets take the information in this and make one with edits in our sections. 
This is a personal preference note, but I would rather see more explanation to each section instead of a list of links and titles.  I think we could make it a little more informative by breaking it out into the logical sections, each section should have a description and then some supporting links.  That way, as a VFS engineer, I can skim through one page and have a good understanding of how we work and how to interact with us.  And if I need more context, that is when I dive into the links.

**Comment by thilton-oddball** [comment]
https://vfs.atlassian.net/wiki/spaces/pilot/pages/937656409/VFS+Orientation+DRAFT
