### ISSUE TITLE
EKS "platform-tools" cluster in STAGING - Install DNS 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18203]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by tskinn** [comment]
I've used the yaml provided here to install external dns in the staging cluster.

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/k8s/external-dns-vagov.yaml

**Comment by jbritt1** [comment]
We moved away from the "platform-tools" nomenclature and currently have a working EKS cluster in staging. Is this okay to close at this time?

**Comment by jbritt1** [comment]
Old ticket, refers to previous nomenclature that we have moved away from. Closing.
