### ISSUE TITLE
Move promtail installation to Loki repo 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18202]
## Description
We already know that we can easily install promtail. We just need to ensure that it gets installed along w/ the deployment of Loki in an automated fashion. This is likely just converting its existing chart/values yaml files into somethign that can be picked up by tanka/jsonnet. 

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jbritt1** [comment]
It _seems_ this would be blocked until Loki is installed on the staging cluster as it depends on values and resources generated by the creation of Loki pod(s).

**Comment by jbritt1** [comment]
Installed Promtail on staging cluster via Helm yesterday, but this will have to be destroyed a deployed via ArgoCD once we get to a place where all the pieces are in place and we set a standard for deployments to our clusters.

**Comment by jhouse-solvd** [comment]
This will be pretty straight forward, but needs to be re-deployed once Loki is up and running in this cluster. 

Taylor mentions that right now there is a pretty terse values yaml file that can be easily converted in a jsonnet file for use w/ Tanka.

**Comment by jbritt1** [comment]
Opening conversation between sub-teams about best path forward for this task: https://dsva.slack.com/archives/CTYQL39FE/p1612878114127600.

**Comment by jhouse-solvd** [comment]
This is being done in #18156. closing
