### ISSUE TITLE
Create "Type of Facility" Page

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#1821]
## Story
As a veteran, if I'm eligible for Community Care, I want to be able to specify whether I'd like to be seen at a VA medical center/clinic or a Community Care facility.

Maps to this mockup: https://adhoc.invisionapp.com/share/KYTTUL9GU92#/screens/382961723

## Screenshots
![image.png](https://images.zenhubusercontent.com/560c1d84638e718c995d70da/67d82543-7b34-4003-8f52-737e7563e9d0)

## Acceptance Criteria
- [ ] Page shows for veterans who are eligible for Community Care

**Comment by narin** [comment]
I don't think there was a ticket created for this page yet. CC: @markgreenburg 

@jbalboni I saw some references in the code to `typeOfFacility`.  Did you start work on the page at all yet? If not I'll pick this up next.

**Comment by markgreenburg** [comment]
Looks like #1821 was that ticket for this but let's tie the work to this ticket since that one's closed as a dupe.
