### ISSUE TITLE
Identify / Measure Impact of EVSS `homelessSituationType` Bug

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#18219]
# Description

Some Form526 submissions are failing due to bad values being sent in the homelessSituationType field. [Continue...](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18210)

# Acceptance Criteria
- [x] Identify Form526 submissions affected by the [EVSS homelessSituationType bug](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18210).
- [x] Measure impact.

**Comment by annaswims** [comment]
some code:

## submissions affected in a week
```ruby
[8.days.ago..1.day.ago], workflow_complete: false)
ids=[]
submissions.each do |fs|
  if fs.form_json.include?("homelessSituationType")
    homelessness = JSON.parse(fs.form_json).dig("form526","form526", "veteran", "homelessness")
    ids << 
    [fs.id, fs.workflow_complete, fs.submitted_claim_id, homelessness]
  end
end
```

## submissions affected in a month 
(they all seem to be non_retryable_error)
```ruby
jobs = Form526JobStatus.where(status: "non_retryable_error", job_class:"SubmitForm526AllClaim",  error_class: "Common::Exceptions::BackendServiceException", updated_at: [1.month.ago..Time.now])
ids=[]
jobs.each do |job|
  fs=job.form526_submission
  if fs.form_json.include?("homelessSituationType")
    homelessness = JSON.parse(fs.form_json).dig("form526","form526", "veteran", "homelessness")
    ids << [fs.id, fs.workflow_complete, fs.submitted_claim_id, homelessness]
  end
end
```

552 of 996 jobs in the last month that failed with Common::Exceptions::BackendServiceException were homeless vets.

**Comment by annaswims** [comment]
not 100% but it looks like 4611 affected in the last year.

**Comment by annaswims** [comment]
All unsuccessful form526 submissions with homelessness data and the dates they went on to have a later successful submission of on va.gov
````ruby
@edipis=[]
incomplete_submissions = Form526Submission.where(submitted_claim_id: nil)

CSV.open('tmp/homeless.csv', 'wb') do |csv|
  csv << %w[form526_submission_id form526_submission_date first_name last_name edipi workflow_complete submitted_claim_id email_address later_completed_dates homelessness_details]
  incomplete_submissions.each do |fs|
    form_json = JSON.parse(fs.form_json)
    homelessness = form_json.dig("form526","form526", "veteran", "homelessness")
    if homelessness 
      later_completed_dates = Form526Submission.where.not(submitted_claim_id: nil).where(user_uuid: fs.user_uuid).where('created_at > ?', fs.created_at).pluck(:created_at).join(",")
      email_address = form_json.dig("form526","form526", "veteran", "emailAddress")
      @edipis << fs.auth_headers["va_eauth_dodedipnid"]
      csv << [fs.id, fs.created_at, fs.auth_headers["va_eauth_firstName"],  fs.auth_headers["va_eauth_lastName"], fs.auth_headers["va_eauth_dodedipnid"], fs.workflow_complete, fs.submitted_claim_id, email_address,  homelessness]
    end
  end
end
````

**Comment by annaswims** [comment]
There have been 7,398 submissions through Va.gov that did not succeed and included homelessness from 2875 veterans.

1,302 Veterans have submitted a claim through VA.gov that included homelessness and had no successful submissions after their failed submission.

**Comment by annaswims** [comment]
I have a file with all the potentially affected veterans.  It has info on any form526 submission that did not succeed for any reason.  It includes name, edipi, form submission date, email address, homeless contact.

It also has the dates of later successful submissions through va.gov, if any for that veteran. 


(note to self it's called  homeless_full.csv)

**Comment by annaswims** [comment]
I sent the data (form526_submission_id form526_submission_date first_name last_name edipi SSN email_address later_completed_dates_and_claim_ids homelessness_details disabilities) to paul and will follow up next week to add claims data from the Claims Status Tool.

**Comment by annaswims** [comment]
Stats presented at our 2pm meeting today

There have been 7,398 Form 526 submissions through VA.gov that did not succeed (for any reason*) and included homelessness.

The 526 failed submissions were from 2,875 veterans.

1,302 Veterans have submitted a claim through VA.gov that included homelessness and had no successful submissions through VA.gov after their failed submission.

*Over the years the way we categorize errors has been updated but I wanted the most inclusive version of who was affected.

**Comment by annaswims** [comment]
got more VBA data from Paul.  
The final impact is that 1,380 homeless/at risk veterans submitted a claim to va.gov that did not make it to VBA on the same day. 
I emailed Paul a list of those veterans with their last-submitted contact info.
