### ISSUE TITLE
Generic Error State | Refresh before calling help center

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18227]
## User story
As a user, if my data doesn't load, I want to understand what I can do to fix it or where to turn for help. 

## Acceptance Criteria
1. Create UI for a generic error state that advises a user to try refreshing the app, before calling the help center
     - Add to each screen with an API call
2. Pull in mobile alert CC
     - Copy is hard-coded
     - Include 2 phone numbers with click-to-call capability
3. "Try again" large button
     - Selecting this button will attempt to retry pulling the data for the page
     - If the retry fails, display the same error state screen
2. Error codes that trigger this screen include:
     - 503
     - 504
     - 408 (time out, no response from servers, the application stops trying to get a response)

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/435095150

## Corresponding UX ticket
[#14917](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14917)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Mobile Alert**
- Mark "The VA mobile app isn't working right now" as Header 2

**Two phone numbers (links)**
- Title= Name of link, (e.g. 800-698-2411, select 0) 
- accessibilityHint= “Dials this number via your device’s call function” 
- accessibilityRole= “link”

**Try again button**
- Title= "Try again"
- accessibilityHint= “Try again to load VA Mobile app” 
- accessibilityRole= “button”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
@bridgethapner the design includes a message to "Please refresh this screen". From a UX-standpoint, how is refresh intended to work? Pull-down is a common approach on mobile apps, but a button to refresh would probably be more a11y-friendly (similar to the Try Again button on the No Network Connection error state: https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/437850383)

cc: @lexicalninja

**Comment by bridgethapner** [comment]
Good question. Refresh is intended to work by pull down to refresh. I looked around a bit online for guidance and tips on accessible refreshing UX. I didn't find much, but I think we should go ahead and add the "Try Again" Large Button CC at the bottom of the alert because it does seem like that is more A11y-friendly. The prototype is updated to reflect. 

I think our current Warning Alert CC is only built to allow 1 action at the end, though -- Patrick can you confirm we can offer two actions within a Warning Alert? Is additional work required to update this CC to take this?

![Generic Error State (refresh then call).png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/9cc89639-bef7-4f9f-9902-7bd434302e93)

**Comment by lexicalninja** [comment]
The alert box is built to have any UI added to the alert after the header and message text.

**Comment by bessgreen** [comment]
Q: does this error always assume the context of the screen (e.g. if there is a Back button, does that persist)?

**Comment by bridgethapner** [comment]
@bessgreen Good question. Would this error show on a detail screen? My understanding of when this error would occur would be that it would affect all of claims, so users wouldn't get past the initial screen.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Get the password for the 1401 user and we're (hopefully) golden on testing this one.  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19691

**Comment by digitalken** [comment]
PASS 2/24/2021 - UI looks good but logging a small bug on accessibilityHint for the 'Try Again' button.  Closing.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/20408
