### ISSUE TITLE
Clean up msw-mocks.js

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18226]
The `personalization/profile/msw-mocks.js` is nearly 2K lines. A lot of the mock calls have a lot in common. And many of the mock calls are full of data that is not really required. Cleaning this file up could help with when we add new mocks in the future. Making the mocks a little more focused on providing the data that's actually needed would make it a little easier to understand the functionality that's being tested.

**Comment by sanlouise** [comment]
Closing with comment, this was a cleanup so nothing to validate on the FE
