### ISSUE TITLE
Generic Error State | Call help center

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18229]
## User story
As a user, I want to know what to do when there is an error with the app.

## Acceptance Criteria
1. Create UI for a generic error state that advises a user to call the help center
2. Pull in mobile alert CC
     - Include 2 phone numbers with click-to-call capability
3. Copy is variable depending on whether or not it is an app-wide error or service-level error
     - App-wide: "The VA mobile app isn't working right now"
     - Service-level: "The [service name] service isn't working right now", where the service name reflects the page name (e.g. Appointments) _(TBD  need clarity on this requirement and how this is different than #19079 and #18230)_
4. Error codes that trigger this screen include:
     - 500
     - 502
     - 404

**Notes for dev**
- Page-level error for Claims, Appointments

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/435506798

## Corresponding UX ticket
[#14919](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14919)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Mobile Alert**
- Mark "The VA mobile app isn't working right now" as Header 2

**Two phone numbers (links)**
- Title= Name of link, (e.g. 800-698-2411, select 0) 
- accessibilityHint= “Dials this number via your device’s call function” 
- accessibilityRole= “link”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Need to validate AC #3B: service-level errors. What scenarios will trigger these? As this applies to C&A, will this conflict with the **Claims & Appeal unavailable** error state? (#19079)

**Comment by digitalken** [comment]
2/3/2021 - Was able to generate the generic error and wrote a bug on text formatting (too much padding above mobile alert) and accessibility issues with Android.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19459

**Comment by digitalken** [comment]
FAIL 2/10/2021 for Android TalkBack issues, button hint. (no specs for button hint.). Recorded in bug.  Closing.

Bug:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19789
