### ISSUE TITLE
Generic Error State | No network connection

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18231]
## User story
As a user, when there is a network error, I want to see an error message that clarifies what is happening.

## Acceptance Criteria
1. Create UI for a generic error state when there is no network connection. This page will appear when the user tries to make a request, and the app detects that there is not an available connection.
     - Header 2: "VA Mobile App can't be loaded."
     - Body: "You aren't connected to the internet. Please check your internet connection and try again."
2. "Try again" Large Button (note: designs show this as a hyperlink, but please create this with the Large Button CC instead)
     - Selecting this button will make a call to try and reconnect the app and reload the page
3. Scenarios that trigger this screen include:
     - Device is offline
     - Can't connect to network
4. Page header/bottom nav bar will persist. 
     - Users should be able to navigate to other pages with the same error persisting 

## Designs
https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/437850383

## Corresponding UX ticket
[#14351](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14351)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
 - Mark "VA Mobile App can't be loaded." as Header 2

**Try again button**
- Title= "Try again"
- accessibilityHint= “Try again to load VA Mobile app” 
- accessibilityRole= “button”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/4/2021 - Minor bug logged on Accessibility "Title" for the Try again button.  Closing.
