### ISSUE TITLE
Error | Invalid routing number

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18233]
## User story
As a user, if I enter a routing number that meets the character requirements but is invalid, I want to see a message saying that my routing number was invalid.

## Acceptance Criteria
1. Create UI for an error state when a routing number is invalid
     - This error appears after a user has hit "Save" on the direct deposit edit page, and their routing number is invalid
2. Pull in mobile alert CC
     - Copy is hard-coded
     - Error state appears at the top of the page, above the check dropdown image
3. When this error state appears, the information the user entered should remain populated in each field so they can revise it rather than having to enter it all again (as shown in designs)

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/439369172

## Corresponding UX ticket
[#15905](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15905)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Mobile Alert**
- Mark "We couldn't update your bank information" as Header 2

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/4/2021 - Pass both Android and iOS.
