### ISSUE TITLE
Analytics Reporting Request for Digitized Modernization Council Meeting

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1823]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Camelia Parham and Chris Johnston
    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
- What team/project is this work for?
    _this adds context for the data_
    - Meeting with the Digitized Modernization Council Meeting
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
Previous 18 months (Mar '18-Sept '19)

## Analytics to Track Down
- Monthly satisfaction scores dating back (ideally) 18 months.
- Two scores shown one for all of va.gov ( including all the "legacy" pages) and one for just the new, "modernized" pages.

## Which Product Questions are you trying to answer?
How are veterans satisfied with the modernized products on va.gov?

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
@amycesal Could you put this on Microsoft PPT? (and redesign as necessary?)

https://docs.google.com/presentation/d/1G92yeWeA-rtZ1KxrdKvJg7LjQo_Msneea8wY6I5qalQ/edit#slide=id.p

**Comment by joanneesteban** [comment]
Data caveat: Foresee does not track modernized vs. legacy pages in the same way that Google Analytics does because currently, Foresee does not separate out surveys based on separate pages but instead sends out an intercept survey that captures users from across the site at the end of a full user cycle. 

We can generate CSAT impact over time from the question, "Did you notice the redesign?", which segments the CSAT into "yes" and "no" responses. We can assume that CSATs from users who noticed the redesign can give us insight into satisfaction with the relaunch, and customers who did not notice the redesign can give us insight into satisfaction from users who did not distinguish the pages on va.gov from vets.gov. The question was asked starting November 8, 2018 after the relaunch of va.gov.

**Comment by amycesal** [comment]
powerpoint: 
[CSAT - Sep '19.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3627327/CSAT.-.Sep.19.pptx)

**Comment by joanneesteban** [comment]
Thanks, @amycesal! Closing out this issue.
