### ISSUE TITLE
Error | Upstream appointment error

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18232]
## User story
As a user, if one type of appointment is successfully fetched but another type is not, I want to see a message explaining that the app will display some appointments and not others.

**Technical context**
VA and Community Care appointments are fetched from two different services - and are then merged - so it’s possible one could be down and the other still up.

See comments section for what this response looks like. 

## Acceptance Criteria
1. Create UI for an error state when some appointments cannot be loaded
     - This error could appear for both upcoming & past Appointments
     - Error displays below the segmented selector, and above any appointments that have successfully loaded
2. Pull in mobile alert CC
     - Copy is hard-coded (note: omit "upcoming" from the copy that is shown in designs)
3. Include static copy below the mobile alert 

## Designs
https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/439368937

## Corresponding UX ticket
[#15974](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15974)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Mobile Alert**
- Mark "We can't load some of your VA appointments" as Header 2

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Blocked: not yet ready for FE dev. 

Alastair to update the Appointments service so it distinguishes between different types of appointments.

**Comment by bessgreen** [comment]
Got confirmation from @kreek that the appointment service has been updated w/ the necessary changes to implement this error state. 

Unblocking this ticket and moving into Sprint 12.

**Comment by bessgreen** [comment]
**200 response:** 

```
{
  "data": [
    {
      "id": "8a4812b77035101201703a2086750033",
      "type": "appointment",
      "attributes": {
        "appointmentType": "COMMUNITY_CARE",
        "comment": "testing",
        "facilityId": null,
        "healthcareService": "practice name",
        "location": {
          "name": "practice name",
          "address": {
            "street": "street address",
            "city": "city",
            "state": "CA",
            "zipCode": "81203"
          },
          "lat": null,
          "long": null,
          "phone": {
            "areaCode": "888",
            "number": "888-8888",
            "extension": null
          },
          "url": null,
          "code": null
        },
        "minutesDuration": 60,
        "startDateLocal": "2021-03-12T18:01:00.000-09:00",
        "startDateUtc": "2021-03-13T03:01:00.000Z",
        "status": "BOOKED",
        "timeZone": "America/Anchorage"
      }
    }
  ],
  "meta": {
    "errors": [
      {
        "status": "502",
        "source": "VA Service",
        "title": "Backend Service Exception",
        "detail": "<html>\\r\\n<head><title>500 Internal Server Error</title></head>\\r\\n<body>\\r\\n<center><h1>500 Internal Server Error/html>\\r\\n"
      }
    ]
  }
}
```

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
@keli13 @bessgreen - any ideas on how this might be tested?

**Comment by digitalken** [comment]
Use user in this story to test.  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19691

**Comment by digitalken** [comment]
PASS 2/24/2021 - Mobile alert is good from UI and accessibility perspective on iOS and Android.  Closing.
