### ISSUE TITLE
Generic Error State | Missing records

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18230]
## User story
As a user, I want to know when I cannot access a service because I don't have the requisite ID and therefore need to be directed to the call center.

This error state will affect the following parts of the app: 
- Claims
- Letters

## Acceptance Criteria (TBD - validation needed)
1. Create UI for an error state when a user's records cannot load due to a missing ID
2. Pull in mobile alert CC
     - Copy is hard-coded
     - Include 2 phone numbers with click-to-call capability
3. Error codes / scenarios that trigger this screen include:
     - 401 (TBD - status message)

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/435506787

## Corresponding UX ticket
[#13991](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/13991)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Mobile Alert**
- Mark "We can't match your information to our records" as Header 2

**Two phone numbers (links)**
- Title= Name of link, (e.g. 800-698-2411, select 0) 
- accessibilityHint= “Dials this number via your device’s call function” 
- accessibilityRole= “link”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
TBD: FE team is blocked - need further requirements. AH to investigate when & where this error state appears.

**Comment by bridgethapner** [comment]
Closing until we find a use case where this error would display
