### ISSUE TITLE
Error | Claims unavailable w/ no Appeals

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18244]
## User story
As a user, I want to know when I cannot access my claims because of an upstream error, even when I do not have any appeals on record. 

**Technical context**
Appeals and Claims are fetched from two different services so it’s possible one could be down and the other still up.

## Acceptance Criteria
1. Create UI for an error state when claims cannot be loaded, and the user does not have any appeals 
2. Pull in mobile alert CC
     - Copy is hard-coded
3. Below the mobile alert, create UI for a null Appeals state: "You do not have any appeals" 
4. Triggered when the claim service is down (see comments for more info)

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/439365083

## Corresponding UX ticket
[#15975](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15975)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Mobile Alert**
- Mark "Claims status is unavailable" as Header 2

**No appeals message**
- Mark "You do not have any appeals" as Header 2

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
2/8/2021 @ 9:52 AM - Looks good (now) on Android.  Need to test on iOS.  
Also, holding out because of TestRail not showing my test runs currently.

**Comment by digitalken** [comment]
2/8/2021 @ 10:28 - Looks good on iOS.  I'll hold off on closing until I can find out what is going on with TestRail and my test runs.
