### ISSUE TITLE
Loki - Automated Deploy to “platform-tools” STAGING cluster

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#18241]
## Product Outline
[Centralized Logging - Product Outline](https://vfs.atlassian.net/wiki/spaces/VI/pages/891355706/Centralized+Logging+-+Product+Outline)

## High Level User Story/ies
As an Ops engineer, I need Loki installed in "platform-tools" STAGING cluster so that I can capture/access logs about the resources in that EKS cluster.

## Hypothesis or Bet
**If** we learn how to deploy Loki into EKS clusters in an automated way, then we will develop the process for bringin centralized logging via Loki to other teams.

## OKR
O2: Make it easier and more satisfying to build and operate the DEPO Platform.

## Definition of done
Loki mirrors existing configuration from "platform-tools" DEV cluster and is using CicrcleCI + ArgoCD for automated build and deployment 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jhouse-solvd** [comment]
1. `vsp-infra-loki` has its own git repo
2. circleci it out to be able to get the image to ECR
3. Helm it as a deployment first to platform-tools-staging EKS cluster
4. Roll back and perform the same using argocd
5. We need dns name, s3 and all during this process

**Comment by mydesignrocks** [comment]
loki is now available in staging. dns as cname annotation is pending and will circle back with an update upon availability.

**Comment by mydesignrocks** [comment]
loki-staging.vfs.va.gov is available as well...

**Comment by jhouse-solvd** [comment]
This is good to go. Closing
