### ISSUE TITLE
Sidekiq and Rails Mailers publicly accessible on non-production environments

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#18240]
[Ryan Link reported](https://dsva.slack.com/archives/CBU0KDSB1/p1609962129084300) our staging [sidekiq](https://staging-api.va.gov/sidekiq/) and [mailers](https://staging-api.va.gov/rails/mailers) are publicly accessible. This is also true for [sandbox](https://sandbox-api.va.gov/sidekiq/) and [dev](https://dev-api.va.gov/sidekiq/).

A suggested solution of adding Basic Auth has been recommended.

Also recommended was adding a robots.txt file so these pages won't show up in search engines.

**Comment by ryanlink** [comment]
Thanks for reporting this, @catherinetcai!

**Comment by ericboehs** [comment]
Our production sidekiq webui is difficult to access. We're currently discussing adding id.me. I've proposed we also use this for this ticket. Fleet appears to be onboard.

[Slack Convo](https://github.com/department-of-veterans-affairs/vets-api/pull/5593) [Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17806) [Draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5593)

**Comment by jeff2d2** [comment]
Closing as #22354 is a replacement.
