### ISSUE TITLE
Some VAMC facility pages not building

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#18242]
## What happened?
The CMS team has uncovered an odd issue in preparation for the rollout VAMC facilities in Erie.

When the facilities are published and then a front end content release triggered, some of the pages are not being built.

They are present in the pages.json but never get built into html. 

![image](https://user-images.githubusercontent.com/5752113/103921228-3f4f7380-50e0-11eb-8cc6-08d6a405c581.png)

Example:
http://eriehealthcare.demo.ci.cms.va.gov/erie-health-care/locations/venango-county-va-clinic  is published however 
http://eriehealthcare.demo.ci.cms.va.gov/static/erie-health-care/locations/venango-county-va-clinic  does not exist.

http://eriehealthcare.demo.ci.cms.va.gov/erie-health-care/locations/ashtabula-county-va-clinic is published  it does exist
http://eriehealthcare.demo.ci.cms.va.gov/static/erie-health-care/locations/ashtabula-county-va-clinic

Examining .cache/vagovdev/drupal/pages.json  we find that both pages are represented in the data, but only one is built.

Settings for both nodes are identical other than some differences in string content.

Reference to the original issue raised in #CMS-support https://dsva.slack.com/archives/CDHBKAL9W/p1609822249314800

## Desired behavior
All published facilities are present in  html build

## Acceptance Criteria
- [ ] All published facilities are present in  html build

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by SgardnerPMP** [comment]
Erie-health-care is scheduled to launch into Dual-state on **Monday January 11th, 2021.**   If this bug cannot be resolved, by Friday, Suggest the environment be deleted and we create a new environment to start from in Devshop to resolve any broken links and prep Erie-health-care for dual state.

**Comment by swirtSJW** [comment]
@SgardnerPMP  Just to be clear, this is not a devshop issue.  A new demo environment will not solve the issue. We can reproduce this defect on all environments (except prod because we can not run it on prod).   This is a front end content build issue.

**Comment by mpelzsherman** [comment]
Can someone please provide a non-devshop URL (e.g. staging.va.gov) that SHOULD be working, but is not?

**Comment by SgardnerPMP** [comment]
Understood. @swirtSJW.    @mpelzsherman I can provide you a Staging URL, but from my understanding we do not publish from Staging, so please tell me if is not what you are looking for, respectfully. https://staging.cms.va.gov/section/veterans-health-administration/vamc-facilities/va-erie-health-care

**Comment by SgardnerPMP** [comment]
We are using Devshop to validate that all pages and links are working prior to moving into Dual-state and publishing the full system.   If this cannot be confirmed in Devshop, I will need validation from another platform to in order to proceed to publication into Dual State.
Thank you.

**Comment by swirtSJW** [comment]
@mpelzsherman   Staging and dev get rebuilt with a new database on every merge so the content would have to be published and then frontend rebuilt... and by the time that was complete the environment would be getting rebuilt due to new code.  They are not really the right place to test publishing content.   This is all reproducible locally too.

**Comment by swirtSJW** [comment]
To debug locally:

1. Build local CMS. (web gets built as part of that)  
2. go to https://va-gov-cms.lndo.site/admin/content/bulk?title=&type=All&moderation_state=All&taxonomy_entity_index_tid_depth=183 (that domain will only work if the CMS is running locally.)
3 Login as me u:steve.wirt@civicactions.com    p:drupal8
3. perform these two clicks, in order
![image](https://user-images.githubusercontent.com/5752113/103931014-9f004b80-50ed-11eb-88a4-4c69eb4fd647.png)
4. Then click 
![image](https://user-images.githubusercontent.com/5752113/103931595-8e040a00-50ee-11eb-8ea6-b6ae6bf75c13.png)
5.  Then click the "Apply to selected items"   - this will publish all the unpublished Erie content.
6. When that completes, go to your terminal and run `lando web-build`  
7. When that completes, the entire vetsweb will be present at http://va-gov-cms.lndo.site/static/
8. The pages.json can be found here `.cache/vagovdev/drupal/pages.json`
