### ISSUE TITLE
[FE] Privacy Act update 

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#18257]
//TODO: fill in

**Comment by abuckley3385** [comment]
@mdewey  what is this ticket for?

**Comment by mdewey** [comment]
This ticket was made with the intent to just notify the platform team, [but that was handled already](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17199#issuecomment-767003612.
). 

Even though it's on Platform's roadmap, This could turn into an implementation. Depending on priority

**Comment by mdewey** [comment]
I think this is good to close. So I am closing this.
