### ISSUE TITLE
Understand VA.gov feature for LOA3 user who is not in Vet 360 

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#18251]
When a user is LOA3 but is not in Vet 360, they shouldn't be able to see certain elements from their Profile. We want to be the same as the web to deliver a consistent profile experience across web and mobile. 

**Questions to answer**
- [ ] How does VA.gov handle this use case?
- [ ] What are all the elements that should be hidden in this scenario? 
- [ ] What does the error look like for Vets who see this (both copy and UI)?

**Comment by bridgethapner** [comment]
Couldn't find anything in the Product Guide

Posed a question about this to the Profile team: https://dsva.slack.com/archives/C909ZG2BB/p1610052966381700

**Comment by bridgethapner** [comment]
Alright, so I looked into this a bit and got some feedback from some Profile engineering folks. From what I understand from their responses [here](https://dsva.slack.com/archives/C909ZG2BB/p1610052966381700), the way VA.gov handles this scenario is initializing the Veteran with VA Profile via the **/v0/profile/initialize_vet360_id** API, then they can see their Profile information.

I need help from technical folks to understand 1) if I'm understanding this right 2) if we can technically handle this the same way as the web / what the LOE is for that. Before I loop any tech folks in -- @ayushchak how do you recommend we handle this for right now? I think we can make an exec call for MVP to just hide it, or investigate further...thoughts?

**Comment by ayushchak** [comment]
Team discussed and decided to hide for MVP given other priorities at the moment. Current possibility: make information unavailable with a little alert modal.
