### ISSUE TITLE
[BE/devops] VA Profile: Rename references to vet360 in devops

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#18259]
## Background

Related issue: #18258

Vet360 has been named to VA profile, vet360 references in the devops repo should be renamed to va_profile.

**Dependency**: May need help for someone from devops.

## Tasks 

- [ ] Complete work that Lihan is able to do on his own in this ticket.
- [ ] Create new ticket for devops folks and figure out who to assign it to.

**Comment by Samara-Strauss** [comment]
Revisit this in sprint 44.

**Comment by Samara-Strauss** [comment]
Let's use this issue to track the work Lihan is able to complete, and then we can create a separate ticket for someone if devops if that work is a big enough lift.

**Comment by Samara-Strauss** [comment]
PRs have been created and need to be reviewed. Already got a review from platform, but also requires a review from identity and devops. Once those are reviewed and approved, we can close this out and create a new ticket to track the work that needs to be done by the devops team.
