### ISSUE TITLE
[BE] General AE: Remove references to vet360 from backend code (part 1)

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#18258]
## Background

We have removed references to Vet360 from the frontend code, but these references still exist in the backend code. We should replace references to Vet360 with VA Profile

## Tasks

- [ ] Replace references to Vet360 in the backend code with VA Profile.

**Comment by mshea0606** [comment]
no blockers at this time

**Comment by Samara-Strauss** [comment]
Lihan has resumed work on this ticket.

**Comment by Samara-Strauss** [comment]
Merged some changes, but the latest merge requires changes on VA Profile's end.

**Comment by Samara-Strauss** [comment]
VA Profile needs to release version 2 of their API in order to rename the attribute, so this may take a while. @lihanli will you check in with them about whether VA Profile has a timeline for this?

**Comment by Samara-Strauss** [comment]
@lihanli I'm going through our backlog and found this ticket. Do you know if VA Profile updated their API? If so, we could get this on your plate for a future sprint.

**Comment by lihanli** [comment]
they haven't updated their api yet as far as i know

**Comment by Samara-Strauss** [comment]
I'll check in with them to confirm.

**Comment by Samara-Strauss** [comment]
[Ian said](https://dsva.slack.com/archives/C7TE0PFTL/p1636578921077500) this is on for their next PI, which starts next week.
