### ISSUE TITLE
Integrate with address validation endpoint

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18264]
## Acceptance Criteria
1. Make a call to hit the address validation endpoint
     - This will determine which address error to display

**Note for dev**
This task should be completed before any of the 4 Address Validation Error tickets: #17695, #17480, #17700, #17698

**Comment by lexicalninja** [comment]
#### Is there always a validation key?
Not always. Very few times there will be no validation key. If that is the case they cannot use that address. 

There are slightly different messages for no validation key that with validation keys. 

#### What are the validation messages?
[Address Validation Messages](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/user/profile/vap-svc/constants/addressValidationMessages.js)

#### What message should the app display?
[Utility function to get message key](https://github.com/department-of-veterans-affairs/vets-website/blob/c3b1ea1a493e91a413cec35777801c8a9d372365/src/platform/user/profile/vap-svc/util/index.js#L8)

**Comment by lexicalninja** [comment]
Just a note, there is a lot of movement in this part of the repo, so if something seems off, please ping me and I will find the links again

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - Getting address validation, so validation endpoint is integrated.  Closing.
