### ISSUE TITLE
UI update | copy for No Claims & Appeals

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18265]
## Acceptance Criteria
1. Update the copy for the **No Claims & Appeals** UI:
     - Change header from "You do not have any submitted claims" to "**You do not have any submitted claims or appeals"**
     - Change body from "This app shows only completed claim applications. If you started a claim but haven’t finished it yet, go to eBenefits to work on it." to **"This app shows only completed claim and appeal applications. If you started a claim or appeal but haven’t finished it yet, go to eBenefits to work on it."**
2. Update any a11y labels & hints to reflect the copy changes

Original ticket:[ #16909](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16909)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Pretty sure I need non-mock data for this one.

**Comment by digitalken** [comment]
PASS 2/9/2021 - New text as expected.  Closing.
