### ISSUE TITLE
Homepage - document current analytics

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18276]
## Issue Description
In order to establish baseline metrics in analytics dashboards and identify gaps, document current analytics implementation on the VAOS homepage.
- Event actions, including CTA labels and respective states
- CTAs without tracking (e.g. VVC Join appointment button doesn't fire event)
- Performance and session-based tracking (e.g. total number of appointments shown in each tab)

**Comment by jbalboni** [comment]
Events:

- vaos-schedule-appointment-button-clicked
   - Fired when starting the new appointment flow from the links on the homepage (top of the page or within the no appointments found alert)
- vaos-schedule-project-cheetah-button-clicked
   - Not live project cheetah alert when starting that flow
- vaos-express-care-request-button-clicked
   - Fired when starting the express care flow from the link on the homepage
- nav-tab-click
   - Fired when a tab is clicked
   - `tab-text`: Upcoming, Past, Express Care
- vaos-get-future-appointments-started, vaos-get-future-appointments-retrieved, vaos-get-future-appointments-failed
   - Fired when upcoming appointments are fetched on the homepage
   - Failed event is fired if any of the fetches fail: requests, va, or cc
- vaos-get-pending-appointments-started, vaos-get-pending-appointments-retrieved, vaos-get-pending-appointments-failed
   - Fired when requests are fetched on the homepage
   - Failed event is fired if the request fetch fails
   - It's not clear if we really need this set of events, it's a subset of the future appointments ones. Only the failed events will fire at different times from future-appointments
- vaos-get-past-appointments-started, vaos-get-past-appointments-retrieved, vaos-get-past-appointments-failed
   - Fired when past appointments are fetched on the past appts tab
   - Failed event is fired when either the va or cc appointment fetches fail
- vaos-cancel-appointment-submission, vaos-cancel-appointment-submission-successful, vaos-cancel-appointment-submission-failed
   - Fired when a user cancels a request or appointment
   - `appointmentType` in additional data is set to `pending` or `confirmed`
- vaos-number-of-items-retrieved
   - Fired whenever a list of items are successfully fetched for the appt list, items are filtered into different types:
   - type: `express_care`
   - type: `upcoming`
   - type: `video_home`
   - type: `video_va_facility`
   - type: `video_gfe`
   - type: `video_atlas`
   - type: `video_store_forward`

**Comment by jbalboni** [comment]
@laurenernest Are there other things you're looking for here?

**Comment by laurenernest** [comment]
This is great! I'll let you know if more context is needed.
