### ISSUE TITLE
File upload / Take photo buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18277]
## User story
As a user, I want multiple options for file upload so I can submit my documents. 

## Acceptance Criteria
1. On each of the file request items, replace the current **Upload** button with 2 large buttons:
     - **Select a file** (primary action)
     - **Take photos** (secondary action)

Note: routing not needed for this story. This is only for the UI / a11y labels.

## Designs
![Screen Shot 2021-01-14 at 9.59.15 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/301398a0-29f4-467d-aa52-0ffd90a5a5cf)
https://camo.githubusercontent.com/9d4586de2d1b460b3f49619392b881cff71b5f0e9dcb226505e6957b3320b77d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f35663233313062392d633166392d346661612d396630302d333838393536313065326131

## Accessibility Acceptance Criteria

1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

**Select a file button**
- Title= "Select a file"
- accessibilityHint= “Select a file and upload to your claim” 
- accessibilityRole= “button”

**Take photos button**
- Title= "Take photos"
- accessibilityHint= “Take photos and upload to your claim” 
- accessibilityRole= “button”

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
Questions: 

1. Is the content behind the overlay ever visible without the overlay (i.e. when the action sheet is not displayed)?

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/21/2021 - Android and iOS.  Did notice an issue on the keyboard tabbing through the previous page on Android and I'm updating that other bug (#17008) with the file upload page.
