### ISSUE TITLE
508-defect-3 [COGNITION]: COVID Vaccine Trials - Checkboxes should not be separated from additional information inputs

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#18272]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a user, I want to make sure all of my answers are recorded. When additional information fields appear away from the question I am answering, I might miss them.

## Details

The "What is your gender?" question gives users an option to self-describe. If users check this option, an additional text input appears after the next checkbox. The input should come directly after this checkbox. An option might be to put the "Prefer to self-describe" checkbox last, after Prefer not to answer. Screenshot attached below.

## Acceptance Criteria

- [ ] Checkboxes are reordered or the team decides on another course of action that makes the relationship clear between the checkbox and its additional text input

## Environment

* https://staging.va.gov/coronavirus-research/volunteer/sign-up

## WCAG or Vendor Guidance (optional)

* [Meaningful Sequence: Understanding SC 1.3.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html)

## Screenshots or Trace Logs

![Screen Shot 2021-01-07 at 4 48 44 PM](https://user-images.githubusercontent.com/934879/103954285-7e45ef00-5109-11eb-82ce-156b68823c3f.png)

**Comment by stephenBarrs** [comment]
This will require a change to `vets-json-api` to update the Schema: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/560

**Comment by stephenBarrs** [comment]
The changes to vets-json-schema and vets-website have been merged and this fix is now available

**Comment by 1Copenut** [comment]
Verified the fix has been deployed and working as expected. Moving to close.
