### ISSUE TITLE
[FE] Look into analytics error discrepancies

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#18270]
## Background

On 1.7.21, I met with Mike Richard to talk about analytics error tracking. I noticed there are a couple of high-count errors that we're not seeing on our dashboard in the same time period (12/31/20 - 1/6/21) — MVI202 and MVI201.

**VA Profile's error dashboard for 12/31 - 1/6**

![Screen Shot 2021-01-07 at 4.41.35 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/f1d30173-5195-4814-b92b-e9f474744ca9)

**Our GA dashboard for 12/31 - 1/6** 

![Screen Shot 2021-01-07 at 4.50.43 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/dc1d707b-ed4b-4e50-bbb5-dbfede3c45e5)

## Tasks

- [ ] Determine why we aren't seeing MVI201 and MVI202 errors on our GA dashboard.
- [ ] Make updates to FE tracking if necessary.

**Comment by erikphansen** [comment]
It's possible that our GA dashboard view isn't showing the events because it's not configured to show them. I wonder if the 201 and 202 errors in Mike's dashboard were triggered by errors when attempting to initialize someone into VA Profile. In that scenario we'd make a call that looks something like:

```
recordEvent({
  event: 'profile-edit-failure',
  'profile-action': 'save-failure',
  'profile-section': 'initialize-vet360-id',
  'error-key': `${errorCode}_${errorKey}-initialize-vet360-id-save-failure`,
})
```

while a call to GA when there is an error updating an address would look something like:

```
recordEvent({
  event: 'profile-edit-failure',
  'profile-action': 'save-failure',
  'profile-section': 'mailing-address',
  'error-key': `${errorCode}_${errorKey}-mailing-address-save-failure`,
})
```

Mostly unrelated: it's a tiny bit concerning that some of the titles on our GA dashboard do not appear correct. "Total Address Suggestion Failures" is clearly not the correct name for a table that has errors related to address suggestions as well as address saves and email saves.

**Comment by Samara-Strauss** [comment]
> The GA dashboard is probably not set up to show VA Profile init errors, like it isn't set up to show phone number update errors.

Can you explain this to me more? Is it that VA Profile can detect errors that they're not sending over to us? And why aren't they sending them over? I just don't know enough to understand what's going on here.

> Mostly unrelated: it's a tiny bit concerning that some of the titles on our GA dashboard do not appear correct. "Total Address Suggestion Failures" is clearly not the correct name for a table that has errors related to address suggestions as well as address saves and email saves.

We can easily get this updated to "Total Contact Information Failures."

**Comment by Samara-Strauss** [comment]
Request to change the name of the table here: #18281.

**Comment by erikphansen** [comment]
I don't understand how this GA dashboard view is set up either. But surely there must be something close to a raw data view that'll show us `-initialize-vet360-id-save-failure` and `-phone-save-failure` errors in addition to the `-address-save-failure ` errors this dashboard is showing. @bmcgrady-ep Can you assist with this at all?

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss @erikphansen - The GA dashboard is showing all the errors happening on the `profile-edit-failure` and `address` as the event action. If you prefer, I can change the dashboard to show all the profile errors as shown in this [GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210107&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension57&explorer-table.rowCount=50&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22profile%22,0%5D%5D&_r.drilldown=analytics.eventLabel:profile-edit-failure/).

**Comment by Samara-Strauss** [comment]
@bmcgrady-ep that report shows contact information errors and direct deposit errors. For the address validation dashboard, I am only interested in contact information errors, not direct deposit errors.

Still there are errors showing in the report you linked that are related to contact information that aren't showing in the address validation report — MVI202 and MVI201 being the two most notable examples. Is this because of how those errors are classified?

**Comment by erikphansen** [comment]
@Samara-Strauss @mshea0606 Welp we might want to look into refining how we report errors to users when we cannot init them in VA Profile since that's the source of most of the 201 and 202s. Right now we just show them a very simple "We’re sorry. Something went wrong on our end. Please refresh this page or try again later." alert.

**Comment by Samara-Strauss** [comment]
OK, we can probably revisit #17210.

- For MVI202 — we can check in with the login team to see how they are addressing duplicate identity issues when people are logging in to VA.gov. We might also need to do more digging with the VA Profile team to make sure we fully understand what this error is communicating.
- For MVI201 — I'm surprised these people are able to update their contact info at all if they can't be found in MPI. I would have imagined that when they got to the profile itself, we showed them the "can't be found in MPI" error we already have... we do already have this error, correct?

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - Gotcha. I was able to update the dashboard to include MVI202 and MVI201 errors. Let me know if you need anything else.

**Comment by Samara-Strauss** [comment]
Thanks, @bmcgrady-ep!

@erikphansen as you probably saw in Slack, [this is the error we are showing if we initialize the profile and can't find someone n MPI](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Design/design-specs/profile-images/account-security/Account%20Security%20-%20Not%20in%20MPI.jpg). Again, I am not sure how these people are able to submit contact information in the first place, but we could potentially show similar messaging for the MVI201 error. However, I am not sure what next steps might be for them to get the issue resolved.

**Comment by erikphansen** [comment]
@Samara-Strauss yeah you read my mind. Something is up. If we do not find someone IN MPI, we do not given them access to any part of their profile other than the Account Security section. We really need to figure out why our `GET user` call would indicate they are in MPI, so we give them access to their contact info data, but VA Profile does not think they are in MPI. This is all over my head and seems like some sort of identity issue either on our side or VA Profile's side.

**Comment by Samara-Strauss** [comment]
OK, I'm glad I'm not totally off base here. Let's regroup on Monday on this one. I can start by asking in the VA Profile channel if they have any idea what might be causing this.

**Comment by erikphansen** [comment]
And maybe @lihanli could help us figure out `vaProfile.status` value is set when we call `GET user/`. Basically when `GET user/` returns data where `vaProfile.status` is something other than `"OK"` we treat the user as though they are _not_ in MPI and block them from most of the Profile. But it seems like there are times when `vaProfile.status === "OK"`, so we allow them access to their contact info, but calls to VA Profile can return an error indicating that they are not in MPI.

**Comment by Samara-Strauss** [comment]
So it sounds like the question is still... why is the login/initialization flow detecting someone is in MPI, but VA Profile is not?

**Comment by erikphansen** [comment]
Correct. Sadly this is totally outside of my area of understanding. But if we can find the right people to chat about this and I'd like to observe.

**Comment by lihanli** [comment]
the `vaProfile.status` value actually comes from the MPI response. the documentation says the value is "The status of the last MVI response or not authorized for for users < LOA 3". 
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/mpi_data.rb#L94

**Comment by Samara-Strauss** [comment]
@lihanli so what does that mean? Sorry, I'm not technical enough to meaningfully move this forward beyond asking a lot of questions, and I'm not sure what to make of the code above. Is this something that can help us figure out why we are showing people the profile who might not be in MVI, even though, in theory, those people shouldn't be seeing profile information in the first place?

**Comment by lihanli** [comment]
if a user's `vaProfile.status` is OK then they should be in MPI. i asked in the vsp-identity channel to make sure but from skimming the code it looks like that is the case. as far as va profile saying a user is not in MPI when we are getting data from MPI saying the user is found i'm not sure why that would be happening.

**Comment by erikphansen** [comment]
@lihanli do you think we're going to need to find some real users who are running into this issue to better diagnose it and figure out why `vaProfile.status` is `OK` but VA Profile is throwing an error because they are not in MPI?

**Comment by lihanli** [comment]
i think that would be a good thing to log. i made an issue for it here https://github.com/department-of-veterans-affairs/va.gov-team/issues/18349

**Comment by Samara-Strauss** [comment]
Question: Is the goal of #18349 to log when this is happening, and then validate whether those users are actually in MPI or not? I'm assuming that is the expected outcome, but let me know if that assumption is incorrect.

Also, I'm trying to figure out if/when we need to pull the VA Profile team in, and I might wait if we think we can get more information from our own internal investigation before pulling them in. Does that sound like a plan, or do you think it would be productive to involve the VA Profile team at this point?

**Comment by lihanli** [comment]
the goal of #18349 is to gather user details to show to the va profile team in order to ask them why users that are in MPI are getting a "not found in MPI" error from their API. [someone in #vsp-identity](https://dsva.slack.com/archives/CSFV4QTKN/p1610395116347400) has already confirmed that a user with `vaProfile.status` of OK should be in the MPI database.

i don't think we need to involve the va profile team until the logging code is added and the data has been collected.

**Comment by Samara-Strauss** [comment]
Got it! Thank you. Will hold off on involving VA Profile until we have more data.

**Comment by mshea0606** [comment]
See ticket [[BE] log when users have a mvi_response.status of OK then return a va profile MVI201 error #18349](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18349)

**Comment by Samara-Strauss** [comment]
☝️ To be clear, we are closing this ticket because the original purpose — figure out why 202 and 201 errors aren't showing up — has been resolved. Ben McGrady updated the dashboard so we should be seeing those come in now. It was an issue with what analytics were getting pulled in, not a problem with tracking overall.

The next thing we need to investigate is why 201 errors are happening in the first place. These errors indicate someone tried to update their contact info who wasn't in MPI, yet we shouldn't be initializing the profile for people who aren't in MPI in the first place. So, Lihan is going to do some tracking on this phenomenon in #18349, and then we'll circle back with VA Profile as we have more information.
