### ISSUE TITLE
Update `direct-deposit`-related strings sent to GA, prefixing them with `cnp-`

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18280]
Based on [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16904), we should update some of our existing Direct Deposit-related GA strings to be specific to Direct Deposit for Comp and Pen.

To make sure we don't break stuff, I suggest we first apply this change to non-prod envs first and confirm that things look good on the GA side. 💡Idea: make a new helper to return the strings with or without `cnp` depending on if the code is running in prod or not.

Before we merge this into `master` to deploy to staging we should confirm with @bmcgrady-ep that they are ready for the new events, but based on [his comment here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16904#issuecomment-756294678) I think we are good to go!

## Acceptance Criteria

These are the specific strings that would have to change:

`recordEvent({ event: 'profile-get-direct-deposit-started' });`

becomes:

`recordEvent({ event: 'profile-get-cnp-direct-deposit-started' });`

---

`recordEvent({ event: 'profile-get-direct-deposit-failed' });`

becomes:

`recordEvent({ event: 'profile-get-cnp-direct-deposit-failed' });`

---

```
recordEvent({
  event: 'profile-get-direct-deposit-retrieved',
  'direct-deposit-setup-eligible': true|false,
  'direct-deposit-setup-complete': true|false,
})
```

becomes:

```
recordEvent({
  event: 'profile-get-cnp-direct-deposit-retrieved',
  'direct-deposit-setup-eligible': true|false,
  'direct-deposit-setup-complete': true|false,
})
```

(We could also change the 2nd and 3rd keys if you wanted)

---

```
recordEvent({
  event: 'profile-edit-failure',
  'profile-action': 'save-failure',
  'profile-section': 'direct-deposit-information',
  'error-key': errorCode,
})
```

becomes:

```
recordEvent({
  event: 'profile-edit-failure',
  'profile-action': 'save-failure',
  'profile-section': 'cnp-direct-deposit-information',
  'error-key': errorCode,
})
```

---

```
recordEvent({
  event: 'profile-transaction',
  'profile-section': 'direct-deposit-information',
})
```

becomes:

```
recordEvent({
  event: 'profile-transaction',
  'profile-section': 'cnp-direct-deposit-information',
})
```

---

```
recordEvent({
  event: 'profile-navigation',
  'profile-action': 'add-link',
  'profile-section': 'direct-deposit-information',
})
```

becomes:

```
recordEvent({
  event: 'profile-navigation',
  'profile-action': 'add-link',
  'profile-section': 'cnp-direct-deposit-information',
})
```

---

```
recordEvent({
  event: 'profile-navigation',
  'profile-action': 'edit-link',
  'profile-section': 'direct-deposit-information',
})
```

becomes:

```
recordEvent({
  event: 'profile-navigation',
  'profile-action': 'edit-link',
  'profile-section': 'cnp-direct-deposit-information',
})
```

**Comment by erikphansen** [comment]
Ah right we have some unit tests that check these values that have changed.

**Comment by bmcgrady-ep** [comment]
Hi @erikphansen - does this mean I can QA this in staging on my end?

**Comment by erikphansen** [comment]
@bmcgrady-ep we will merge [this](https://github.com/department-of-veterans-affairs/vets-website/pull/15583) once it is passing all of its tests. Then you can start seeing how things work in staging. @sanlouise or I will let you know once it is done!

**Comment by sanlouise** [comment]
@bmcgrady-ep I just merged in the PR, so you should be able to start testing this in staging today!
