### ISSUE TITLE
[Analytics] Change the name of GA table from "Total Address Suggestion Failures" to "Total Contact Information Failures"

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#18281]
## Background

On [the address validation GA dashboard](https://analytics.google.com/analytics/web/#/dashboard/pq_-PrkvQleUdCBbV7eq7Q/a50123418w177519031p176188361/), the table we are using to show errors has changed over time, and the title "Total Address Suggestion Failures" no longer applies. We should change the name of this table to accurately reflect what we are now showing — Total Contact Information Failures.

![Screen Shot 2021-01-07 at 4.50.43 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/3371fb6e-3166-427b-b799-be67977f14c8)

## Tasks

- [x] Change name of table to "Total Contact Information Failures"
- [x] Let Samara know when this is done

**Comment by bmcgrady-ep** [comment]
Hi @Samara-Strauss - I've updated the name to "Total Contact Information Failures".  I'm closing out the ticket, but feel free to reopen with any additional questions.

**Comment by Samara-Strauss** [comment]
Thank you!
