### ISSUE TITLE
Capture the daily number of dropped applications since 10-10CG launch

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#18291]
**Description**
We track the daily stats of 10-10CG submissions in Sheets and Excel. Update both sources with the number of attachments that have been dropped since the production release of the form.

**Comment by kevinmirc** [comment]
Completed.

**Comment by hdjustice** [comment]
Hi @dfong-adh Is there a need for this ticket to be open?  It closed more than 3 years ago.  Thanks!
