### ISSUE TITLE
EDU Form: Remove Feature Flag usage for OMB/Expiration date updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18294]
As a developer, I need to remove the 'edu_form_omb_and_expiration' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. This feature flag was created in #18293
2. UAT has been completed for this effort and EDU signed off as of 02/02/21.
3. The new functionality is live in production with no need remaining need for the toggle.

## Acceptance Criteria
1. The usage of feature flag 'edu_form_omb_and_expiration' is removed.
2. The feature flag is 'off' when displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16080

**Comment by sonntag-adam** [comment]
In staging and prod. Testing passes QA.
