### ISSUE TITLE
EDU Form: Create Feature Flag for OMB/Expiration date updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18293]
As a developer, I need to create a feature flag for the form OMB content so that it is not displayed in production as development is completed.

## Assumptions:
1. The Feature Flag is configured per environment.
    a. Feature flag for edu form updates is available in both vets-api and vets-website repos.
2. When the feature flag is:
     a. Off: The content changes are not visible.
     b. On: The content changes are visible.
3. The feature flag is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. The Feature Flag `edu_form_omb_and_expiration` is available to be used for the form OMB content updates.
2. The Feature Flag description is: "Update OMB # and expiration dates for forms"

## Tasks
1. Follow feature flags documentation to create edu form feature flag.
2. Follow feature flags documentation to create edu form feature flag.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by ksantiagomorgan6** [comment]
FE PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15665
BE PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5686

**Comment by delli-gatti-michael** [comment]
The flag is now present in all environments. Closing this issue
