### ISSUE TITLE
Unit Test Coverage - Improve unit test coverage of vets-website 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#183]
## User Story
As a platform we need to improve detection of regressions in vets-website by leverging a strong unit test approach to ensure we can better identify problems that would lead to a poor experience for veterans. 

## VSP Q1 + Q2 2020 OKRs
O5: All customers comply with the Platform's standards.

## Short term tasks 

#184 - Create app specific unit test coverage report for vets-website 
#189 - Expand unit test coverage of Facility Locator
#190 - Expand unit test coverage of GI Bill Comparison Tool

## Medium / Long term 
Make it easy to maintain high test coverage 

- investigate using Jest or Jest-like features
  - see [Why we use mocha instead of Jest](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/front-end-standards/documented-decisions/jest/)
  - incorporate jest-like snapshot testing of react components into mocha: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15830
- Improve unit test output 
- Facilitate test driven development for common tasks (e.g. fix the watch task, patterns for TDD)
- Improve test run time (this could part of facilitating TDD) 
- process to automatically report / monitor unit test coverage for apps

**Comment by wyattwalter** [comment]
We can pick up whatever report is generated in Jenkins with something like this: https://github.com/department-of-veterans-affairs/vets-api/blob/master/Jenkinsfile#L33

vets-website uses a scripted pipeline, so the syntax will look a bit different.

**Comment by timwright12** [comment]
two of these 3 items are closed and one was addressed in another ticket, closing out.
