### ISSUE TITLE
CT: Remove Secondary SCO information from the Profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18307]
As an Education Services Team Member, I need to see the secondary SCO information removed from the profile page, so that users contact the correct person.

## Assumptions:
1. This work is completed behind a prod flag.

## Acceptance Criteria
1. The "secondary" SCO section and all SCOs not of type "Primary" are not displayed on the CT profile page.

## Supporting Artifacts:
1. 
![image](https://user-images.githubusercontent.com/48260534/104738300-5828dc00-5713-11eb-8f7a-9670120197ac.png)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1245&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging, testing passes QA.
