### ISSUE TITLE
CT: Add IPEDS to Caution Flag Mappings

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18306]
As a Education Team Member, I need caution flags that are applicable to multiple locations of an institution to be displayed on all applicable locations so that the users of the Comparison Tool are aware of any caution flags related to that location.

## Assumptions:
1. This work is completed behind a prod flag.
2. Additional research details can be found in story #18619.

## Acceptance Criteria:
1. The settlement caution flags in the VACautionFlag file are assigned to each Facility Code that has the same IPEDS as the row in the file.

## Supporting Artifacts:
1. https://www.va.gov/gi-bill-comparison-tool/search?category=school&name=AMERICAN+INTERCONTINENTAL

## Technical Notes:
1. IPEDS is called "cross" in the institution table.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/783

**Comment by zurbergram** [comment]
sql to find institutions that have a cross/ipeds value associated with an institution in VaCautionFlags but the institution’s facility_code is not in VaCautionFlag

```
select institution, facility_code, "cross"
	from institutions join (
	SELECT "cross" as ipeds
          FROM institutions JOIN va_caution_flags ON institutions.facility_code = va_caution_flags.facility_code
          WHERE settlement_title IS NOT NULL
            AND settlement_description IS NOT NULL
            AND "cross" IS NOT NULL
          GROUP BY "cross"
	) ipeds_list on institutions.cross = ipeds_list.ipeds
	WHERE institutions.cross IS NOT NULL
	AND institutions.facility_code not in (select facility_code from va_caution_flags)
	AND institutions.approved is true
```

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1362&group_by=cases:section_id&group_order=asc)

**Comment by delli-gatti-michael** [comment]
Verified in Staging. Closing this out
