### ISSUE TITLE
Access for Katryn Bowman

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#18302]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Katryn Bowman
- Please Provide your email.
   > katy.bowman@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > FE Tools, Sr. Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQfwr2iBWss1QJM2klEAi4RYy52HoOrZILUC7wj/KUk4IcWLKG1u5R8A8J8zX1T590Dks8sYEDwaN2TwxFAmSAQxb2pRjGpYYXHDSGuUM61/1G1WE+1METRAmUg/BrdM84spv+9x99gMuD+SyQ/1ETI7JXDyzo1vrapC9yAfh7PrXajnhnrjKYdDWqrJniGAYqniXdL59V30bZdJKx3axS8dT39adul5KoAtCrK7AEDpCSTbsFcm0BTpZTQXm7krDTgtjHPTfplZAIuICB2LwRXZJn9XqJljl4VNWGpct3ZqHMl6z8GoprTLpN57pce/Z6CgssyPEBwNYyntX6a0Ue31VsS68maCg6bxMo0Ws6yDNu19E9TLj4OgYCq6vdIZI4QxK+P12YAPR2aPzN9Auy2hobtDIREJOIYeEbsNdNmJciL0HoRzqNlTRGLGfwGHwon90niw+bQZEDLWJT2U6vBt5gSsv/ZIwC9BjPD1qbOomvTedXXrM5cZ84LyeCKF8= katrynbowman@Katryn-Bowman-Macbook.local

```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
      - I need access for work on the FE tools team and va.gov

**Comment by tskinn** [comment]
@k80bowman you should be able to connect to the socks proxy. Reach out in slack if you have issues.

**Comment by tskinn** [comment]
@k80bowman can you clarify which AWS services you need access to? I'm not sure if all FE devs need access to AWS so just trying to verify. Thanks

**Comment by k80bowman** [comment]
@tskinn I was told to request blanket access since I am on the FE Tools team.

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Jeff
Name: Katryn Bowman

**Comment by Jeff-Hayter** [comment]
@tskinn  Approved for AWS.
