### ISSUE TITLE
Write up testing plan

### ISSUE THREAD

**Issue by ayushchak** [department-of-veterans-affairs/va.gov-team#18305]
Ayush and Bridget to write up a testing plan for the VA Mobile App's internal/soft release.

Questions for Steve:
- Who is this going out to? Are they slack users? If yes, which workspaces?
- Do we need to set up an email inbox?

We'll write up a checklist following this

**Comment by bridgethapner** [comment]
**Checklist for readiness to release the app to internal testers:**
- [ ] IAM integration is in production & tested
- [ ] App Center is set up
- [ ] Instructions for how to download/sign up for App Center are made
- [ ] We have made a Slack channel to invite testers to
- [ ] We have tester emails

**Questions**
- [ ] Are we all aligned that we'll handle this passively / asynch via Slack? We can set up follow up convos on an ad hoc basis
- [ ] I feel like we can ask for general feedback & say we want to hear about issues for sure. I don't think we need a structured survey - what does everyone else think? PS - does PRA apply here?

**Comment by bridgethapner** [comment]
- [ ] Let's do a Teams Channel
- [ ] Make one person's VA email open 
- [ ] How are we getting people -- Steve is putting together a doc and sharing out with us
- [ ] Add a question along the lines of how likely are you to recommend to someone you work with or other Veterans?

**Comment by ayushchak** [comment]
Draft language for testing

_Hello There,

We’re reaching out to you because we would love to have you test our preliminary internal release of the VA Mobile App - your feedback is extremely valuable to us identifying issues and building a strong app for Veterans across the country. We’re looking for your honest thoughts and experiences as testers!

Please share your feedback between February 1, 2021 and February 12, 2021, please follow the steps below:

Download the VA Mobile test app: This app will be available for your review from February 1st through 12th through App Center - a mobile app testing platform. We are attaching instructions on how to download the test VA Mobile app in this email.
Share your thoughts: You can do this in one of two ways:
Freeform feedback - Join the #va-mobile-app-beta-test channel on Teams. If you have any thoughts - small or large - you can share them here!
Survey feedback - We’re also running a structured survey through SurveyMonkey - this contains a few features that we want your feedback on.

Please let us know if you have any questions - we’re excited to hear from all of you!

Best,
The VA Mobile App Team_

**Comment by bridgethapner** [comment]
I'm closing this and moving the comment with text for the Internal email over to the other ticket
