### ISSUE TITLE
Record errors when we cannot create a VA Profile transaction

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18303]
When there is a failure to create a VA Profile transaction, we are not currently reporting that to GA: https://github.com/department-of-veterans-affairs/vets-website/blob/e4a5f7fc2881c0233b30f91b250b812123df1573/src/platform/user/profile/vap-svc/actions/transactions.js#L203-L209

We _are_ reporting successful transaction creations: https://github.com/department-of-veterans-affairs/vets-website/blob/e4a5f7fc2881c0233b30f91b250b812123df1573/src/platform/user/profile/vap-svc/actions/transactions.js#L191-L195

TODO:
- [X] Figure out what data to send GA when we have an error creating a transaction. Perhaps it'd be identical to when a pending transaction fails: https://github.com/department-of-veterans-affairs/vets-website/blob/e4a5f7fc2881c0233b30f91b250b812123df1573/src/platform/user/profile/vap-svc/actions/transactions.js#L136-L141
- [ ] Record an event [like this](https://github.com/department-of-veterans-affairs/vets-website/blob/e4a5f7fc2881c0233b30f91b250b812123df1573/src/platform/user/profile/vap-svc/actions/transactions.js#L136-L141) when we are [unable to initialize a transaction with VA Profile](https://github.com/department-of-veterans-affairs/vets-website/blob/e4a5f7fc2881c0233b30f91b250b812123df1573/src/platform/user/profile/vap-svc/actions/transactions.js#L203-L209)

**Comment by joanneesteban** [comment]
@erikphansen thanks for flagging.  Do you need support from the VSP Analytics team?

**Comment by erikphansen** [comment]
Thanks for the reminder on this, @joanneesteban!

@bmcgrady-ep Could you weigh in on this when you have a few minutes? Hopefully the ticket is clear but let me know if you have any questions.

**Comment by bmcgrady-ep** [comment]
Hi @erikphansen - sorry for the delay here. After looking into this, I would recommend it being identical to when a pending transaction failure occurs as you mentioned above. Let me know if you have any more questions.

**Comment by erikphansen** [comment]
I think this can be closed? I made [a new ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19318) to actually update the FE code and record these errors to GA.
