### ISSUE TITLE
CT: Remove prod flag for secondary SCO removal

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18309]
As a developer, I need to remove the prod flag for the secondary SCO removal so that the updated UI is available in all environments.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of 01/29/21.

## Acceptance Criteria
1. The prod flag created in #18307 is removed and the functionality implemented in that story is available in production.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15862

**Comment by sonntag-adam** [comment]
Testing passes QA
