### ISSUE TITLE
Analytics KPI dashboard request for [Public Websites - Campaign Landing Page]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#18315]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [X] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [X] Your KPIs are clearly linked back to Veteran outcomes
- [X] Link your KPIs below (KPIs should be in your Product Outline)
- [X] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.
- [X] New dashboard
- [ ] Iteration of current dashboard

### KPIs
[Public Websites - Campaign Landing Page (CLP) Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/README.md)

[Public Website - CLP Stake of Product](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/state-of-product.md)

_Note: The State of Product is included as it has additional details that relate to the defined OKR/KPI's._

**_This is a draft request, product is in build process and expected to be in beta NLT mid-February 2021. Request a meeting to review the details and determine how best to track via multiple, simultaneous campaigns at any given time from various VA stakeholders_**  

### OKR/KPI Dashboard
[Campaign Landing Pages KPI's](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/Screen%20Shot%202021-01-08%20at%201.47.16%20PM.png)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Fantastic! Thanks for opening this, @brianalloyd ! Would you be able to clarify your KPIs in metrics before we get started on the dashboard? It looks like CSAT is one of the metrics, but would you be able to break down the other metrics that you're looking for?

> We will know the initial set of functionality is meeting the desired user and business outcomes when the CLP template is used by (or via the PW content team on behalf of) at least three business stakeholders -- and there are no requests for major changes. 

Can you clarify "used by" in this KPI?

> To measure the effectiveness of the CLP for campaign purposes, we will require the use of CTAs that would be prominently required and automatically tracked as a primary metric (e.g. whatever campaign X's success measure is, at least one required CTA button would be required that would automatically be tracked by analytics)

Are these button clicks? Or is there a larger user journey that could serve as a proxy for the CLP effectiveness?

> Every content component/panel in the template - whether it is the video panel or the downloadable resources panel - should be automatically tracked. Instrumenting this auto-tracking capability into the CMS front-end template will not only ensure the ability to track CLP performance but also will be used as a lever to govern the business users of the template.

For "every content component," are you looking for how the entire template is being used? The most effective/most trafficked components? 

Thanks!

CC: @MickinSahni

**Comment by brianalloyd** [comment]
@joanneesteban thanks for the quick follow up, we're in the process of defining those metrics now and will update the ticket with additional details as they are defined.  As I mentioned above this is a draft request:
> This is a draft request, product is in build process and expected to be in beta NLT mid-February 2021. Request a meeting to review the details and determine how best to track via multiple, simultaneous campaigns at any given time from various VA stakeholders

Thinking it might be beneficial to host a quick round table to review the details and discuss best options as this is a unique product for VA stakeholders that will likely require unique tracking elements.  CC @johnhashva
