### ISSUE TITLE
CT: Add State Search Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18312]
As a developer, I need to create a feature flag for including state abbreviations in search so that the functionality can be toggled on or off until it's ready for production.

## Assumptions:
1. The Feature Flag is configured per environment.
    a. Feature flag for edu form updates is available in both vets-api and vets-website repos.
2. When the feature flag is:
     a. Off: Search results do not include results based on state abbreviation
     b. On: Search results include results based on state abbreviation
3. The feature flag is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. The Feature Flag `gibct_state_search` is available to be used for the state abbreviation search enhancements.
2. The Feature Flag description is: "Include state abbreviation when searching on comparison tool"

## Tasks
1. Follow feature flags documentation to create state search feature flag.
2. Follow feature flags documentation to create state search feature flag.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by elder-joseph** [comment]
Associated PRs:

Front End: https://github.com/department-of-veterans-affairs/vets-website/pull/15693
Back End: https://github.com/department-of-veterans-affairs/vets-api/pull/5710

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-01-19 at 12.40.25 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a73c3918-3d63-4a19-a793-236a893dc830)
##
![Screen Shot 2021-01-19 at 12.40.34 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/baa4caba-6613-452c-90ec-40f925d23c80)

**Comment by sonntag-adam** [comment]
In all environments. Closing story.
