### ISSUE TITLE
CT: Add ability to search using state abbreviation

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18313]
As a Comparison Tool user, I need to be able to search by state abbreviation, so I can find schools in my state besides ones that have the state in the name.

## Assumptions:
1. This work is completed behind the `gibct_state_search` feature flag (#18312)
2. Full state name conversion to abbreviation is not part of this story.

## Acceptance Criteria:
For the non VETTEC search: 
1. Search by state abbreviation (ex. TX, AL, SC) returns all institutions within that state.
2. Search by "city, state abbreviation" returns all institutions within that city and state.

For the VETTEC search:
3. Search by state abbreviation (ex. TX, AL, SC) returns all institutions within that state.
4. Search by "city, state abbreviation" returns all institutions within that city and state.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PRs:

`vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/15744
`gibct-data-service`: in progress

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-01-26 at 8.11.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6dab4ac5-72a7-40e6-ac32-8485149cabe7)
##
![Screen Shot 2021-01-26 at 8.11.13 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f4b7b4d3-881e-463d-af13-8026df99f7d4)
##
![Screen Shot 2021-01-26 at 8.12.20 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/81952916-e0c3-47ee-bd18-cb1305ff5615)
##
![Screen Shot 2021-01-26 at 8.12.30 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c59cd752-a293-4a15-ad57-5a21c9e1d01f)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1282&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging, testing passes QA
