### ISSUE TITLE
Analytics KPI dashboard request for 22-1995

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#18316]
# Request a KPI Dashboard

## What this form is for
22-1995: Request change of location or program of study

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.
- [x] New dashboard
- [ ] Iteration of current dashboard

### KPIs / Data from Google Analytics

**Metric: Successful submissions**
- How many users that start the form, complete and submit it?

**Metric: Location of drop-offs**
- When users don't complete the form, where are they dropping out? 

**Metric: Time on task** 
- How long does it take users to complete the online form? 

**Metric: Traffic source**
- Where do users who submit this form come from? 

### KPIs / Metrics Outside Google Analytics
_Education Service is interested in tracking the following metrics if they're relatively easy to capture_

**Call Center** 
-	Number of calls re: 22-1995
-	Topic of calls
_Source: Call Center Data_

**Backend Data**
-	Service availability
-	Network availability
_Source: Prometheus / ?_

**Website speed – Front end performance metrics** 
-	URL performance
-	Page load time
_Source: Speedcurve / ?_

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [x] Groom analytics for technical feasibility
    - [x] Document data sources for each metric
    - [x] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Thanks, Amy! We'll pull this in when we have resources in the next couple sprints.

**Comment by joanneesteban** [comment]
@jonwehausen - to groom metrics.

**Comment by jonwehausen** [comment]
## Metrics Grooming

### Google Analytics/BigQuery Metrics

| KPI | Question | Metric to use | Metric Feasibility 
| -- | -- | -- | -- |
Successful submissions | How many users that start the form, complete and submit it? |  Total events of starts, total events of submissions successful | 🔶 GO 
Abandonment Rate | When users don't complete the form, where are they dropping out? |  Funnel Visualization - Identify each step and percentage + total drop-offs between steps | 🔶 GO 
Time to complete | How long does it take users to complete the online form? | Average time to complete from BQ -- @JasonTheBearded as we've discussed this may be an opportunity for us to segment for those who complete all in one sessions and those who do not | 🔶 GO |
Submissions by Source/Medium/Campaign | Where do users who submit this form come from? | Successful submissions by source/medium/campaign (traffic sources) | 🔶 GO 

### Non-GA/BQ Metrics

| KPI | Source | Metrics to use | Metric Feasibility 
| -- | -- | -- | -- |
Number of calls + source of calls | Call Center | Total # of Calls + Topic of calls | 🌀 [Inquired](https://dsva.slack.com/archives/CNCEXNXK4/p1612464696007900) contact center team 
Service availability + network availability | BE | Uptime | 🌀 [Inquired](https://dsva.slack.com/archives/CQHBJ5U06/p1612466699071100) BE tools team
Page load time + speed | Speedcurve | Time speed | 🌀 _Confirm needing to ask FE tools?_

cc: @joanneesteban @JasonTheBearded

**Comment by jonwehausen** [comment]
@joanneesteban & @JasonTheBearded 

- GA/BQ metrics look good to me
- @JasonTheBearded I'll take a look what datasets we may have already created to answer these and document them 
- For the non-GA/BQ metrics, is FE the best to reach out to for Speedcurve? 

Thanks

**Comment by jonwehausen** [comment]
@JasonTheBearded & @joanneesteban 

- Comment [here ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18316#issuecomment-773553055) has been updated with an additional column for DOMO dataset grooming
- Hopefully gives you all a better starting point on next steps, let me know if there's anywhere else I can help

**Comment by amyknox** [comment]
Hi @JasonTheBearded - do you have an ETA for this effort?

**Comment by joanneesteban** [comment]
Hi @amyknox - unfortunately, Jason is out of office for the foreseeable future due to the Texas blackouts, and our team is at capacity right now. We're hoping to pull this back in in another sprint (March), but please let us know if you need support finding some of the data in Google Analytics. Thank you for your patience!

**Comment by amyknox** [comment]
Thanks @joanneesteban - Any word on how @JasonTheBearded is doing?  

Also, do you have a smaller target than "March" for when this might be pulled into your team's work?

**Comment by amyknox** [comment]
@joanneesteban & @JasonTheBearded - It looks like the 22-1995 dashboard was built (per [this comment on 23221](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23221#issuecomment-827688025)) but I can't find it in GA.  Can you point me in the right direction?

**Comment by JasonTheBearded** [comment]
Hey @amyknox! The ticket you linked is in relation to the standardized forms dashboard we are currently building in DOMO, we'll be releasing it in the near future and it will contain the 22-1995 data.

**Comment by amyknox** [comment]
That'll be great.  We've been waiting on that one for quite awhile. Looking forward to seeing the new & improved, standardize format.

**Comment by amyknox** [comment]
22-1995 was one of the first Standardized KPI Dashboards that VSP Analytics team created in DOMO.  It launched this summer and is a thing of beauty.  Closing this ticket because it's done.
