### ISSUE TITLE
CT: Remove State Search Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18314]
As a developer, I need to remove the 'ct_state_search' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. This feature flag was created in #18313
2. UAT has been completed for this effort and EDU signed off as of 02/26/21.
3. The new functionality is live in production with no need remaining need for the toggle.

## Acceptance Criteria
1. The feature flag 'ct_state_search' is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/800
- https://github.com/department-of-veterans-affairs/vets-website/pull/16433
- https://github.com/department-of-veterans-affairs/vets-api/pull/6215

**Comment by sonntag-adam** [comment]
In all environments. Closing story.
