### ISSUE TITLE
Abstract 1010CG Signature Box content and E2E Test 

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#18329]
## Summary
During the 1010CG postmortem we wanted to add more friction to updating signature box content so a copy & paste error is less likely so we need to make Unit Test to force FE developer to double check the content changed before publishing. We also need to abstract content to make it easier to maintain in a separate file rather than looking through code to edit content.

## Expected Behavior

When updating 1010CG signature box content should see line for line diff in E2E test

## Acceptance Criteria

- [x] Abstract signature box content
- [x] Add E2E test for update diffs

**Comment by mchelen-gov** [comment]
where is the code that needs unit test?

**Comment by LinnJS** [comment]
@mchelen-gov this is the [code](https://github.com/department-of-veterans-affairs/vets-website/pull/15418/files#diff-9444fc584b44d34e126a59a479baff028625e1a44314af87983c25130390e79fR27-R62) I am unit testing. I realized when talking about it in standup I made it sound like the code was already implemented when its not. So this ticket is for the implementation and UT.

**Comment by LinnJS** [comment]
Awaiting validation from design ( @jonathanjnelson )

**Comment by mchelen-gov** [comment]
Per discussion with @LinnJS and understanding risk reduction goal of @mlighdc the preferred implementation is E2E (Cyprus) tests rather than Unit Tests.
- E2E tests catch problems from outside the individual component that may affect the output
- E2E tests allow refactoring of code logic while validating correct output
