### ISSUE TITLE
[FE] Build Error alert to show when we cannot connect to a Direct Deposit endpoint

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18339]
## Background
See design/copy ticket: [Design/copy] Create error messages to show when we cannot connect to a Direct Deposit endpoint #18338

mocks with Peggy's copy in-place:
- [No-load EDU](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/8a43a64c-1644-4213-8afb-296d824d1019/)
- [No-load C&P](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/da4b50a6-875c-4f2b-8449-4044e7bebdc2/)

## Tasks
- [ ] Build alerts to show when we have a problem connecting to one of the direct deposit endpoints but we are showing the Direct Deposit page because the user is eligible for the other direct deposit feature on the page.

**Comment by erikphansen** [comment]
This was done with https://github.com/department-of-veterans-affairs/vets-website/pull/15750 Not sure how this didn't get closed before!
