### ISSUE TITLE
Sign as a Representative

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18347]
## Product Outline
[Initiative Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/initiatives/sign-as-a-rep/initiative-outline.md)

## High Level User Story
As the legal representative of a Veteran, 
I need a way to sign a form on behalf of a Veteran, and upload documentation related to my authority to do so,
So I can help my Veteran fill out online forms/

## Hypothesis or Bet
**If** _we give representatives a way to complete online forms_ **then** _we expect more forms to be completed, especially by those who have a legal representative._.

## OKRs
Objective: Make it easier for Veterans with representatives to fill out the online form
Key result: number of applications filled out by representatives

## Definition of done 
- The ability to complete the online family caregiver application as a representative is available in production

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ala-yna** [comment]
Next steps as of 2/3:
- [Product] Schedule Design Intent Review
- [Design] Research plan & conversation guide
- [Design/ Product] Finalize mockups prior to research (align with content, align with Caregiver stakeholders, consult with OGC)
- [Design] Run research study
- [Design] Synthesize findings
- [Frontend] Research frontend components available for attachments
- [Frontend] Research attachment error states
- [Design] Mockup attachment error states 


- [Design/Product] Update Product Guide

**Comment by LinnJS** [comment]
Created tickets and implementation steps during March 22nd Backlog grooming/artictecturhe meeting

### Frontend
- Add feature flip to FE
- Add yes/no/no do you want to sign as Rep. Page
- Add document upload page
- Update signature page and transform data if needed

### Backend
- Add Feature flip to BE
- [Discovery] Upload size and extension restrictions to CARMA, vets-api, S3
- Update schema for document upload
- Update schema for signature upload
- Accept PDF attachment on submission
  - Add document upload endpoint
  - Update document upload background job
- Add signature data on PDF generation
- Create s3 bucket for POA attachments and update environment configs

**Comment by kevinmirc** [comment]
I've added a flag to hide the API route in production while this is in the development and testing stages.

Before we release it to production, we will need to remove that flag.
