### ISSUE TITLE
UX/UI for app startup / unlock

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18341]
## Dev task 
Here is a breakdown of how the whole process does its work: 

On app start up, there are a number of things that have to happen before a user can get into the app. Some of these things, like auth, are required and some of them are to create a better Veteran experience by pre-calling some data. Below is a list of what needs to happen. 

## Acceptance Criteria

1. Authorization
     - The app needs to check if the user is logged in. If they are logged in and the tokens are good, then skip to Sync Work.
     - otherwise if the user has a stored refresh token, then they are sent to the Unlock Screen.
     - if none of the previous are true, the user is sent to the Log In screen.
2. Token Exchange & Sync Work Screen
     - After the user logs in through IAM or unlocks with biometrics, the device needs to update the access and refresh tokens. This requires an asynchronous call to and API endpoint. 
     - If the token exchange is successful, the skip to Sync Work.
     - otherwise return to log in and inform user there was an error.
     - The app will do some cursory work before the user hits the Home Screen. This work helps by doing some common API calls and functions before a user is in the app. The initial calls make sure the app has data it needs to make the Veteran experience more seamless. This would need to be a screen that indicates that we are setting up your app or fetching your information or something to that effect. I can provide samples of other apps that do this. 
     - The app calls the profile and military history end points. This makes sure the Veteran Name and last branch of service do not need to be fetched when a user hits the profile screen and there will not be a lag before the banner is populated.
     - The app will check to see if it has registered the device token with VetText and register if needed.
     - The app can also make other setup calls for the API in parallel here, in case we need to cache things like appts or claims or something else that takes a long time.
3. Home Screen
     - The app then routes to the home screen

## Designs
- Homescreen: https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432863239
- LOA gating screen: https://adhoc.invisionapp.com/d/main#/console/20546460/433563910/preview#project_console
- Request for biometrics: https://adhoc.invisionapp.com/d/main#/console/20546460/441815124/preview#project_console
- System unlock modal: 

## Corresponding UX / discovery ticket
[#16984](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16984)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
@jmarchi - I'm getting left over data in the profile screen from the previous logged in user still.  Shouldn't the current user's information be fetched and ready to populate before I actually view the Profile screen?  Specifically:
"The app calls the profile and military history end points. This makes sure the Veteran Name and last branch of service do not need to be fetched when a user hits the profile screen and there will not be a lag before the banner is populated."
Is this ready for testing?

**Comment by jmarchi** [comment]
@digitalken 
That work is done as part of this ticket https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18709 which is currently in PR

**Comment by digitalken** [comment]
@jmarchi - ahh, ok.  Thanks John.  It gets confusing when acceptance criteria on one story is actually being done in another...

**Comment by digitalken** [comment]
PASS 1/28/2021 - All indications are that this seems to be working.
