### ISSUE TITLE
Make Sidekiq UI's unavailable publically

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#18344]
## Description

Stemming from a security issue, we need to make sure that the Sidekiq UI's are not publicly accessible.  This is a quick fix to address the security issue, more will be discussed and implemented in the future.

## Definition of Done
- [x] All lower environment Sidekiq UIs are removed from being publicaly available.

**Comment by erluti** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/8340
