### ISSUE TITLE
[BE] log when users have a mvi_response.status of OK then return a va profile MVI201 error

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#18349]
## Background
The log-in flow is detecting someone is in MPI, but VA Profile is not.

See ticket: [[FE] Look into analytics error discrepancies #18270](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18270#issuecomment-758196764)

Users that have a `mvi_response.status` of OK should be in MPI. we should log users that are found in MPI but still receive `MVI201` errors from va profile and ask va profile why these errors are happening

## Tasks
- [x] add user logging code
- [x] ask VA Profile about the log data to determine next steps

**Comment by lihanli** [comment]
@erikphansen do you know if these errors are happening in transaction or non-transaction API calls or both?

**Comment by erikphansen** [comment]
@lihan Our GA dashboard is showing the `MVI201`s coming from the `GET /profile/person/status/{transaction_id}`, which means the errors occur when trying to initialize someone in VA Profile. It's possible there are `MVI201`s happening when trying to _create_ a transaction but we are not currently logging those in Google Analytics.

**Comment by lihan** [comment]
@erikphansen You pinged the wrong lihan 🤣

**Comment by mshea0606** [comment]
@lihanli see Erik's comment above

**Comment by mshea0606** [comment]
@mshea0606 to ask VA Profile team what could be causing these errors based on the log data we went them

**Comment by mshea0606** [comment]
@lihan Ian McEwan is looking into this. They have everything they need and have created an issue and will start work on it in Sprint 42. [Slack](https://dsva.slack.com/archives/C7TE0PFTL/p1613676887099500?thread_ts=1611332694.003100&cid=C7TE0PFTL)
