### ISSUE TITLE
Complete front end security review questions for HLR

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18356]
## User Story
As someone responsible for VA.gov application security, I want to make sure there are not front end issues with HLR.

## Expected Behavior / Tasks
Complete the security review questions from https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/174.

- [x] Determine if we do any Google Analytics and/or Sentry logging in the FE, and follow-up via Slack with @f1337.

## Acceptance Criteria
- [x] Send the info to @f1337

**Comment by edmangimelli** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/3825#issuecomment-604968356

(thanks @Mottie)

**Comment by Mottie** [comment]
Our analytics review #3825 was just completed. We are only using GA. No Sentry events are being logged.

**Comment by luke-gcio** [comment]
Sent the info to Mike.  The main ticket is still open but the ticket to remind us to do it (this one) can be closed.
