### ISSUE TITLE
Claims - Revisit File Upload UI

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#18361]
Per 1/11 discussion, revisit the UI considering the following: 
- We'll use the device's camera
- We won't do edge detection for now
- We will have 2 ways to upload: take a photo and select a photo
- We need a way to communicate the 50 MB limit as the user is uploading 
- We want to display the file name the user is uploading against in the UI on the upload screen

**Comment by bridgethapner** [comment]
@bessgreen @jmarchi Here's an updated flow for uploading from the camera based on our conversation yesterday. 

- The second screen in would be triggered by **Take Photos**, a user would see a screen explaining they can upload a doc up to 10 pages via the app. 
- Once they take a photo, they'd see **Upload** or **Add another photo**. The CTA to **Add another photo** displays until there are 10 photos.
- I don't think we need a size detection error message if we keep the uploading at 10 photos.

cc @ayushchak @lexicalninja for your awareness. 

![claims-upload-update.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/5f2310b9-c1f9-4faa-9f00-38895610e2a1)

**Comment by bessgreen** [comment]
@bridgethapner thank you for turning these around so quickly!! We have a few follow-up questions, but overall this is pretty straightforward.

1. It looks like users will only be able to upload files _or_ take photos for a single request - not both. Is this correct?
2. Does the **Select a file** path on Screen #1 trigger a similar UX/UI as **Take photos?** For example:
     - The **Select a file** button triggers a variation of Screen #2 (we can sub out "photos" for "files")
     - Max of 10 possible files that a user can upload
3. Is there any way to delete a photo/file after it's been uploaded, but before it's submitted? Or will the user need to Cancel the upload flow and start over?
4. Are we omitting file/page names (e.g. **Page 1**) from Screens #3-4?

**Comment by bridgethapner** [comment]
@bessgreen 

1. Yes
2. Yes a version of screen #2 sounds good with different wording. Then I think we can open the file upload plugin we use, whatever that looks like. People should only be able to select 1 file to upload. 
3. Can this be handled by the Camera UI? Is there a Delete or Retake option that UI can offer us?
4. Yes

**Comment by bessgreen** [comment]
@bridgethapner 

3. "Retake" will be an option when the user has the camera open, but this wouldn't cover the scenario of when a user has uploaded it to Screen #3-4 and wants to delete from the File upload page.

Do you think this is an MVP use case, or something we should revisit down the line?

**Comment by bessgreen** [comment]
Per 1/14 standup discussion: 

Deleting a photo from the File Upload page is not in scope for this initial implementation.

**Comment by bessgreen** [comment]
@bridgethapner on the success screen at the end of this flow, do the **Back** & **View all file requests** buttons route to the same page (Screen #1 above)?

**Comment by bridgethapner** [comment]
@bessgreen Yep! Back to screen 1.
