### ISSUE TITLE
Access for [Mark Viterna]

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#18370]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
  Cecilia Lee Cecilia.Lee@va.gov
- Please provide your name.
 Mark Viterna
- Please Provide your email.
 mark.viterna@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
Team Name = Matsumoto
Company = Libertyits
Role = Software Engineer

- Requesting SSH key authorization?
YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here]ssh-ed25519 

```
ssh-rsa  AAAAC3NzaC1lZDI1NTE5AAAAIKrltSO8TjnkQ4+lDod8MHM2LC9rAdtZ4uJ8qJWbthE7 mark.viterna@va.gov
```

- Grant AWS Console access?
YES
S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house

**Comment by mydesignrocks** [comment]
SOCKS access granted. Please continue with the guide to establish a connection to SOCKS proxy

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Cecilia Lee
Name: Mark Viterna

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS.

**Comment by jbritt1** [comment]
Temporary AWS credentials provided to user.
