### ISSUE TITLE
App startup | Biometrics opt-in

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18381]
## User story
As a user, I want the ability to opt into biometrics the first time I log into the app to make future login attempts easier. 

## Acceptance Criteria
1. Create UI for biometrics opt-in page
     - hard-coded copy
     - 2 large buttons
2. "Use Touch ID" button
     - Label is dynamic and will update depending on the device's capabilities. Other options include: "Use Face ID", "Use fingerprint", or "Use face recognition"
     - Selecting this button will opt the user into using biometrics
     - This will switch the biometrics toggle on the app Settings page to "ON"
3. "Skip" button
     - Selecting this button will opt the user out of using biometrics
     - This will switch the biometrics toggle on the app Settings page to "OFF"
4. Selecting either large button will direct the user to the app home screen
5. Rules for when this page appears in the auth flow:
     - This screen will appear immediately after a user returns to the app from the sign-in flow **the first time they sign in**

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/441815124

## Corresponding UX/discovery ticket
[#17837](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17837)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark "Do you want to allow VA Mobile to use Touch ID?" as Header 1

**Use [Touch ID] button**
- **note**: [Touch ID] can also be [Face ID], [fingerprint], or [face recognition], depending on the device
- accessibilityLabel= “use [Touch ID]”
- accessibilityHint= "allow the app to use biometrics and navigate to the home page"
- accessibilityRole= “button”

**Skip button**
- accessibilityLabel= “skip”
- accessibilityHint= "do not allow the app to use biometrics. navigate to the home page"
- accessibilityRole= “button”

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
hi @bridgethapner, are you able to review/validate AC #4-5?

**Comment by bridgethapner** [comment]
@bessgreen AC 4-5 are correct!

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Note: anchoring the buttons to the bottom of the screen is an accessibility issue when increasing the font size on the page.

**Comment by digitalken** [comment]
PASS 1/26/2021 - Android and iOS look good.
