### ISSUE TITLE
Accessibility Feedback - Staging Review - Back to Top Component

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#18399]
## VFS acceptance criteria
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket(s) after fixes have been verified

## Thoughts/questions
- This will be the epic to store accessibility tickets within the Back to Top staging review.

**Comment by mmiddaugh** [comment]
Related issues:

- 508-defect-2 [FOCUS]: Back to top button's focus halo MUST be visible on Safari #25001
- "Back to top" defects #24752 (for landmark and ARIA hidden defects)

**Comment by artsymartha68** [comment]
Can this issue be closed? The two linked issues are closed.
