### ISSUE TITLE
HCA Address Military Base Checkbox

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#18394]
## User Story

As a Veteran 
I would like to label my address as a military base outside of the US
so that my mail gets routed to me correctly

## Expected Behavior

Address has boolean value for isMilitaryBase in both of the HCA addresses

## Acceptance Criteria

- [ ] Each address has question whether or not address is a military base

**Comment by LinnJS** [comment]
![image.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/52b38fb0-103b-49fb-bcf5-9c2afc4eb94c)

**Comment by jonathanjnelson** [comment]
[Designs can be seen here](https://preview.uxpin.com/f29610401565ccb4171ceb77a292d831cd89c3ce#/pages/134730905)

**Comment by ala-yna** [comment]
See feedback here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13059

**Comment by tchrisdyer** [comment]
Moving out of Sprint 49 in order to get additional information on requirements.

**Comment by hdjustice** [comment]
Closing this ticket - has not been addressed in a year.  If work is needed, a new ticket will be created under an initiative
