### ISSUE TITLE
Create app specific unit test coverage report for vets-website 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#184]
## Ticket Update (5/25/2021)

The goals of this ticket have not changed, we just want to get a better output for users of the platform. The end state should be a breakdown by application of the unit test coverage outputting on the [Frontend Support Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard).

### Definition of Done

[ ] Side nav item in the dashboard for "Unit test coverage"
[ ] Landing page should contain a table of applications within vets-website that displays the unit test coverage for each app, similar to the console output.
[ ] Documentation should be added to the page so users know what they're looking at and how to read it.
[ ] New dashboard is released
[ ] Update is announced to teams via Slack

<hr />

### Problem:
- Need to understand the health of each application including unit test coverage 
- Currently our unit test coverage report does not aggregate metrics by application
  - running the coverage report on a specific directory includes platform dependencies in the coverage report 

### Goal:
- Generate an application specific unit test coverage report 

### Notes:
- see `npm run test:coverage` in `package.json` 
- this may be difficult or not possible- recommend having a strict time box for discovery 
- example coverage report ran on an application directory 
![Screen Shot 2019-06-05 at 11.19.53.png](https://images.zenhubusercontent.com/5a5d4c174b5806bc2bc2db50/19339772-7f64-40b0-a36a-27cd5d77fec5)

**Comment by theodur** [comment]
A first pass for a solution to this was pushed out here: https://github.com/department-of-veterans-affairs/vets-website/pull/11768

**Comment by theodur** [comment]
A finalized version of the script was merged in https://github.com/department-of-veterans-affairs/vets-website/pull/11886.

**Comment by brandonrapp** [comment]
This is ready to ship!

**Comment by timwright12** [comment]
Opening this ticket back up with added context in the description.

**Comment by k80bowman** [comment]
Notes so far: 

- Here is the script we already have for generating an app-specific unit test coverage report: https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/app-coverage-report.js
- I was also looking at this PR where Jhonny added the new Frontend Support Dashboard: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/618

**Comment by Cgfor3** [comment]
Most of this effort was completed in the first pass. The second half is following what Jhonny did for the FE Dashboard and getting a space up to display the coverage report.

**Comment by Cgfor3** [comment]
Small update to coverage report script that writes custom report to file https://github.com/department-of-veterans-affairs/vets-website/pull/17688

**Comment by Cgfor3** [comment]
After discussion with @oseasmoran73 and @timwright12 we came to the conclusion to prioritize finishing the React page before setting up a build pipeline to upload the unit test coverage report file to S3.

**Comment by Cgfor3** [comment]
Yesterday the first draft for standup up the app-specific coverage report page was finished. Applying spacing updates and content changes today.

Handoff will include building a pipeline to upload the coverage report data to S3.

**Comment by Cgfor3** [comment]
## Final Update for handoff:
- Spent Friday trying to update the `generateCoverage` function inside the `app-coverage-report.js` script on vets-website to include `total` percentages for unit tests but was ultimately unsuccessful. 
  - Updating the initial filter allowed the `total` through, but I wasn't able to update the `reduce` method to allow it to pass through
    - Once this is figured out, you'll need to copy the file into [the unit test coverage report directory](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/184-unit-test-coverage-dashboard/packages/documentation/src/pages/unit-test-coverage-report) to test.

### Findings
-  The total accounts for unit tests in `src/application` as well as `src/platform` and `src/site`
  - Simply displaying the total will not be representative of just the `src/application` tests
  - Some of the applications are reporting 0s for each category which is also skewing the total results

### Next Steps
- Once the `app-coverage-report` script is generating the file with all the data we need/want, we will need to setup a deployment pipeline that runs the `yarn test:coverage-apps` script and uploads the generated json file to S3. This process can be run independently on whatever cadence seems appropriate.
- After this has been set up, we will need to update the implementation in the `veteran-facing-services-tools` to retrieve the file from S3 as opposed to just reading the json file from the same directory.
- We can inform other teams that this asset is now readily available for consumption (assuming teams are still interested in creating tables/dashboards in BigQuery)

**Comment by k80bowman** [comment]
In the interest of making it easier to find, I went ahead and opened a draft PR for Calvin's branch in the `veteran-facing-services-tools` repo (creating the dashboard itself): https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/639

**Comment by k80bowman** [comment]
Opened a PR to add the total unit test coverage to the log output and test-coverage-report.json file: https://github.com/department-of-veterans-affairs/vets-website/pull/17828

**Comment by k80bowman** [comment]
Done! The report should upload to S3 on every unit test run on the `vets-website` `master` branch. Then it will be automatically updated here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/
