### ISSUE TITLE
Bug: Unable to request a veteran ID card

### ISSUE THREAD

**Issue by lkoenigsberg** [department-of-veterans-affairs/va.gov-team#1840]
Page not found when clicking the button at the bottom of https://staging.va.gov/records/get-veteran-id-cards/apply/.  Possible the URL has changed?

**Comment by erikphansen** [comment]
I get the same error message in prod using the test user provided by @lkoenigsberg. It's due to an error from `GET https://api.va.gov/v0/id_card/attributes `:
```
{
  "errors": [
    {
      "title": "Request failed",
      "detail": "No EDIPI or not found in eMIS",
      "code": "VIC002",
      "status": "403"
    }
  ]
}
```

@lihanli could this be because the test user we're using isn't fully fleshed out?

**Comment by lihanli** [comment]
@erikphansen yea, the production user must be loa3, must have an EDIPI, and their title 38 status must be v1, v3, or v6 (https://github.com/department-of-veterans-affairs/vets.gov-team/issues/6042)

**Comment by erikphansen** [comment]
Thanks, @lihanli. So @lkoenigsberg I'm not going to worry about the error you see with that particular user.

**Comment by erikphansen** [comment]
So we can just send logged in users directly to  https://access.va.gov/accessva/?cspSelectFor=vic but will that maintain the logged-in experience for vets like we've had in the past? A little more background re: the reason for this change would be awesome! This VIC stuff is all new to me. I remember hearing that some other team was working on VICv2, so I'm guessing that this might be that change going live?

**Comment by lkoenigsberg** [comment]
@lkoenigsberg find out more about VIC and VIC pages

**Comment by ncksllvn** [comment]
I don't know how to test this in prod and in general don't have a lot of knowledge about this product, but it looks like the green button at the bottom of `/records/get-veteran-id-cards/apply/` appears to be redirected using the `url` property [here on staging](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L148),  and [here on prod](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L148).

Staging looks like an internal VBA URL, while Prod is https://vicbdc.vba.va.gov/VIC/veteran/login. I can hit the Prod URL but I don't have credentials to see the authed experience. I wonder if that URL should be updated? There's also a `vic-signing.key` - maybe that's expired?

**Comment by lkoenigsberg** [comment]
So it sounds like we might be fine on production but there's no way to know.  Can we maybe change the URL on staging to the one that's on production so that we can find a user to test with?

I don't want to escalate to the VIC team until we've explored it further.

**Comment by ncksllvn** [comment]
Hey @lkoenigsberg, this wouldn't have impacted the functionality of the button at the bottom of the VIC application like the description here describes, but there was an incident on Sunday that would have affected the VIC landing page, causing `/records/get-veteran-id-cards/apply/` to render as not found during a certain timeframe. We wrote a [postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/09-15-19-react-apps-not-rendering.md) about that. If this report came in on Sunday, it was probably due to this incident.

However, if the "not found" is definitely happening after clicking the green button, then this is separate and should be investigated further.

**Comment by lkoenigsberg** [comment]
Definitely happening after I click the green button, at least on staging.

**Comment by ncksllvn** [comment]
I don't have VA network access right now - do you mind posting a screenshot of what you see on that page that the green buttons leads to?

**Comment by lkoenigsberg** [comment]
<img width="1204" alt="Screen Shot 2019-09-20 at 4 11 30 PM" src="https://user-images.githubusercontent.com/51327745/65355994-5869a380-dbc1-11e9-8809-7ab636463202.png">

**Comment by ncksllvn** [comment]
Hm, assuming you're connected to the VA network...then yeah, that does look like a good reason to reach out to partners at that domain. It seems like their domain may have changed something 🤔

**Comment by erikphansen** [comment]
Rian Fowler tested this on prod (since he's a Veteran) and it worked.

**Comment by lkoenigsberg** [comment]
Closing ticket.
