### ISSUE TITLE
Add mobile alert with prototype disclaimer to login screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18406]
## User story
As a Veteran participating in research or VA employee beta testing the app, I want to know that the app I'm testing is a prototype and not an officially released VA app so I understand the context of what I'm being asked to test.

## Acceptance Criteria

1. On the unauthorized home screen, add a mobile alert CC to the top of the screen, below the VCL banner:
     - Use Mobile Warning Alert CC with only a Mobile Body Bold title to top of home screen
     - marginBetween between Veterans Crisis Line button and top of alert
     - Copy "Internal release for testing only"

## Designs
https://camo.githubusercontent.com/4e98f7e4d666488afe074c9f1f27cd33ec4ee3e55a6dcb705b0d11dfe4a2cbba/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f65646263393638312d393232632d343530612d396562382d373437623139363463353661
![Screen Shot 2021-01-12 at 9.38.34 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f24a42a2-5635-4d02-b777-16429c6ea85e)

## Corresponding UX ticket
[#17247](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17247)

## Accessibility Implementation Guidelines 

**Mobile Alert**
- Mark "Internal release for testing only" as Header 2

**Comment by digitalken** [comment]
PASSIN UI/UX, failing Accessibility on Android. (iOS is ok)
Most Androids (except for Google Pixel 3) gives extra instructions with Talkback about double tapping to enable, etc.  Bug logged. Closing story.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19084
