### ISSUE TITLE
Discovery on scalability of CMS using CMS Export

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18405]
## Details 

* https://dsva.slack.com/archives/C5HP4GN3F/p1610379137294200
* https://dsva.slack.com/archives/CBU0KDSB1/p1610408646346500

Understand the scalability limitations of the CMS (once it's using CMS Export). 
Megan to get number of VISNs or nodes or pages from Stan. 

Benchmarks: https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=105374863

**Comment by mchelen-gov** [comment]
Can anyone confirm if these numbers are for **nodes** or **entities**?

**Comment by mchelen-gov** [comment]
Done in spreadsheet / OBE for higher node counts.

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
