### ISSUE TITLE
Analyze all locations capitalizeEachWord is used and remove from places that modify JSON

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18401]
## Problem Statement
`capitalizeEachWord` is manipulating the JSON data for disability names. This is not as expected as `capitalizeEachWord` should be used for display purposes only. Remove all uses of `capitalizeEachWord` where JSON data is manipulated and potentially try to still title case the disabilities outside of JSON manipulation (display purposes only).

## Expected Behavior
`capitalizeEachWord` should not modify JSON data for disability names

## Acceptance Criteria
- [ ] `capitalizeEachWord` does not modify JSON data for disability names

**Comment by vhenry07** [comment]
Closing as work addressed in another ticket.
