### ISSUE TITLE
Remove all uses of sippableId function/conversions of disability names to lower case

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18402]
## User Story
Verify that it is okay to remove the `sippableID` function (originally, it was implemented to prevent an issue regarding disabilities with periods in their name, but we no longer allow users to type this character) and then remove all uses and references of the function. We would like to do this as it would be ideal to not be manipulating any JSON references to the original disability names. 

The two primary files using this function are `prisonerOfWar.js` and `vaMedicalRecords.js` through `makeSchemaForNewDisabilities` and `makeSchemaForAllDisabilities` respectively in `utils.jsx`. `addDisabilities.js` also needs to have `sippableID` removed, but it is only used there to lookup the disabilities reference in `prisonerOfWar.js` and `vaMedicalRecords.js`.

Related: https://github.com/department-of-veterans-affairs/vets-website/pull/15706

## Expected Behavior
JSON data for disability names is not manipulated

## Acceptance Criteria
- [ ] Reviewed with a few internal engineers, not just rely on PR

**Comment by vhenry07** [comment]
Closing as this has been addressed in other work.
