### ISSUE TITLE
Main nav's "Contact Us" button can wrap when logged-in user has a long name

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18412]
If users have a long name, the "Contact Us" button in the main nav can wrap:

<img width="1147" alt="Screen Shot 2021-01-12 at 10 43 58 AM" src="https://user-images.githubusercontent.com/20728956/104360259-a21c8280-54c5-11eb-951d-9e4e828c1116.png">

The CSS responsible for this issue _might_ be tangentially related to [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11849). ie, fixing one issue could potentially make the other worse.

**Comment by brianalloyd** [comment]
Validated and closing ticket.  Thanks @sanlouise for the support.
