### ISSUE TITLE
(Placeholder) Usability Testing Prep [BaM2, FSR]

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#18410]
## Steps to complete Usability Testing Prep: 
- [X] VFS Product Manager: create this issue and fill in the team name and feature name in the title and other bolded information appropriately
- [ ] VFS: Attach all artifacts before requesting the meeting
- [ ] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ Andrea Hewitt 
- [ ] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VFS: At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP: Practice area reviewers create sub-issues attached to this one with feedback for your team 
- [ ] VFS: Completes attached feedback tickets based on acceptance included in each practice area feedback ticket 
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/FSR-Product-Outline.md)
- Link to or attach prototype or mockups (TBD) 
- Link to or attach artifact with copy (if separate from prototypes/mockups)
- [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/jan-2021/research-plan.md) & [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/jan-2021/conversation-guide.md)
- Link to regression test plan (TBD)
- Link to test cases/test plan in TestRail (TBD)

## Meeting attendees from BaM2
- Product Manager (required): @leahkeeler 
- DEPO product lead (required): @mattpointzxer0 
- Anyone else from your team who significantly contributed to the artifacts provided (required): @rileyorr, @rebeccawalsh, @craigwheeler, @bradl3yC 

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira will reach out as needed_

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by shiragoodman** [comment]
@rileyorr can this be closed?

**Comment by rileyorr** [comment]
@shiragoodman yup!
