### ISSUE TITLE
Content Feedback - Usability prep - VAOS homepage refresh

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#18411]
## User story

VSP content feedback on refresh of VAOS homepage. 
Link to prototype: https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens

## VFS acceptance criteria

- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

**Comment by peggygannon** [comment]
@outerpress @laurenernest 
Please note, content feedback is fairly light due to I had provided earlier feedback on these screens. 


Feedback key
Must = the feedback must be applied
Should = the feedback is best practice
Consider = suggestions/enhancements

----------

**Thoughts/questions**

Static landing page
I didn’t provide any feedback on this page, as this content isn’t final and is still to be determined in conjunction with the Public Website team. 

**MUST**

https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/440922971
please style all phone numbers per our styleguide xxx-xxx-xxxx

https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/440676961
please use sentence case for headers
VA Appointment > VA appointment

https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/441371953
please use sentence case for these headers
Community care
Special instructions

https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/441371953
one this screen, please make sure the intro content includes the edits on the earlier screen

---------

**SHOULD**

https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/440676961
Recommend more descriptive text for these links: 
Print TO Print appointment details
Reschedule TO Reschedule appointment

-------

**CONSIDER**
https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/441371953

Instead of using "Special instructions" on this screen, could we use same header that is used on the EC card? 
**You shared these details about your concern**

**Comment by outerpress** [comment]
Thanks Peggy! I made most of these changes, with one question and one note:

> https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/440676960
> I don't recommend using all caps and red font for "Canceled". I defer to Accessibility experts, but I recommend that we not use all caps or red bold font for this word.

At @allison0034 's recommendation I'm playing with the [label style](https://design.va.gov/components/labels) for this status notification ([example](https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/442619368)). Did you have a specific argument against all caps? I think 1 or 2 words that are in all caps are generally okay if you're trying to create a scannable header like this.

> https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/440676961
> Recommend more descriptive text for these links:
> Print TO Print appointment details
> Reschedule TO Reschedule appointment

 We'll be testing if these are clear enough as is during usability testing (see [this section of the test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/jan-2021-appts-list-test/conversation-guide.md#task-2---find-appointment-details))

**Comment by peggygannon** [comment]
Hi, @outerpress yes, I am recommending against using all caps because it can reduce the readability for users with low-vision or vision impairment. It's harder for them to read all caps b/c  the words have a more uniform shape.   

It would be good to test this during your usability sessions.

**Comment by outerpress** [comment]
@peggygannon we've made most of the changes, the rest I've added to a new content review ticket that includes user feedback and a few other things we found along the way. So I'm closing this one and I'll add you to the new one: https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/23018

Thanks!
