### ISSUE TITLE
[FE] "PO Box" in user's home address

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18424]
## Background
We can add a simple check for obvious PO boxes when users are updating their **home address**, just in case they thought they were editing  their **mailing address**. 

It would be something they could get around if they wanted to.

## Tasks
- [ ] Create frontend PO box/home address check

**Comment by mshea0606** [comment]
We will get copy first then work on implementing it.

**Comment by SKasimow** [comment]
@Samara-Strauss - is this something we wanted to do and just didn't get to? Wondering if I should add into backlog?

**Comment by Samara-Strauss** [comment]
No, we can close this.
