### ISSUE TITLE
508-enhancement [COGNITION]: Direct Deposit Component - Consider adding a figure + figcapture pattern for the check image

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#18439]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor, Crystabel_

## Details

I have a hunch that our alt text description for the check image would be beneficial for all users. We assume a lot that users can see and understand the image explainer for finding routing number and bank account number.

I took some time to experiment with a figure + figcapture pattern as the Thoughtbot team outlined in this article: https://thoughtbot.com/blog/alt-vs-figcaption

It works really well with screen readers and would give all users an image + text explanation of how to find relevant information. Tagging @CrystabelReiter for awareness, because this would be a visual adjustment too.

## Proposed Solution (if known)

```html
<figure>
  <img src="/" alt="Personal checks have all the information to set up direct deposit" />
  <figcaption>
    Your bank’s routing number is listed along the bottom-left edge of a personal check. Your account number is listed to the right of that. Routing numbers must be nine digits and account numbers can be up to 17 digits.
  </figcaption>
</figure>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

**Comment by CrystabelReiter** [comment]
@1Copenut Can you tell me more about the visual adjustment? How would the image look different from how it does now? Thanks!

**Comment by 1Copenut** [comment]
@CrystabelReiter If we went this direction, the `<figcaption>` text would be presented underneath the image of the check, maybe centered or slightly indented from the left. I've been thinking about this pattern off and on for a while, as a way to keep `alt` text streamlined, but offer all users a more in-depth explanation for images like checks, maps, etc. that might benefit from it.

**Comment by CrystabelReiter** [comment]
@1Copenut Thanks for the further explanation. :) ! I'll talk to Chris and Carol and see how we can fit it in to the next sprint

**Comment by taylorkaren** [comment]
Issue moved to [department-of-veterans-affairs/va-forms-system-core #255](https://github.com/department-of-veterans-affairs/va-forms-system-core/issues/255) via [**ZenHub**](https://www.zenhub.com/)
