### ISSUE TITLE
[Discovery] Where to put our data (Data Warehouse) for the Product Health Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1843]
## Problem Statement
How might we store data from across multiple platforms (Google Analytics, Grafana, Foresee, Call Centers, PA&I) so that the data can be easily displayed in one platform?

## Goal
Determine the best data warehouse solution for hosting data from across multiple platforms. The dashboard should be accessible for members of VSP teams and have the potential to integrate with whichever platform (https://github.com/department-of-veterans-affairs/va.gov-team/issues/406) is used for the product health tool.

## Objective
Research cost and processing estimates for potential data warehousing solutions so that we can provide data warehousing recommendations for the Product Health Tool.

## Acceptance Criteria
- [ ] Use [technical discovery](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3403) to determine cost benefit analysis
- [ ] Research volume of Foresee data (Jon)
- [ ] A readout of finding is documented
- [ ] Determine best data warehouse solution for product health tool
- [ ] Writeup for data warehousing justification

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
[Checklist Spreadsheet](https://docs.google.com/spreadsheets/d/1tYzIGe3bWug8Ryy0MuaJ3ubNhPrYxSIxW_hGXEw0FYI/edit#gid=0)

**Comment by joanneesteban** [comment]
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3842

**Comment by nedierecel** [comment]
@jonwehausen I added criteria to help research volume of extracting Foresee data before we migrate to Medallia. Can you login and see if it's possible to (a) estimate the entire export of historical Foresee data and (b) download as a flat file since we might not be able to connect to it via an API after we migrate?

**Comment by joanneesteban** [comment]
## Recommendation Meeting on 12/12

**Documents Reviewed in the Recommendation Meeting:**
[Recommendation](https://docs.google.com/document/d/16GQVzAn0JIZBa5mnxkQpV-A4BYZxIwRQSOMq9Nx-Kmk/edit#)
[Miro Board](https://miro.com/app/board/o9J_kvmr7cU=/)
[Cost Benefit Analysis](https://docs.google.com/spreadsheets/d/1tYzIGe3bWug8Ryy0MuaJ3ubNhPrYxSIxW_hGXEw0FYI/edit#gid=0)

**Meeting Recording**: [link](https://zoom.us/recording/play/jJwDuLgVytdRdmSsuPtzG5PSihT5nW5OMqwz70V7GJkVjt3mwK-i30uN6mzWjWKr?continueMode=true)

## Reference Docs for the Product Success Tool's Goals:
[Product Brief](https://docs.google.com/presentation/d/1sI32UbQRqpKqOhBT8lkUuOHgfD4UUkV2cd5Pzw1fP9w/edit#slide=id.g6b3252761e_0_450)
[Product Outline](https://docs.google.com/document/d/1GuuhRXT8-NjEHdFHysNg1VA1o89Qr0_Mkrg46Q8kBeI/edit#)

**Comment by nedierecel** [comment]
@joanneesteban It's still very rough, but I am inserting a list of to-do's that we can map more concretely against our sprints and epics. This can be found in our team's [Data Warehouse and BI Tool Google doc](https://docs.google.com/document/d/1ucllAvbzH6IpnZBmQ0eNOZayQS6IQiyFZ5OqcKBWcdU/edit#bookmark=id.s1rcwoi5m3or).

**Comment by nedierecel** [comment]
@joanneesteban The markdown file can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/research/product-success-data-warehouse-bi-recommendation.md
