### ISSUE TITLE
Add 'vaccine' topic to VEO DOMO webform dataset

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#18430]
Chante -

As discussed [in this Slack thread](https://dsva.slack.com/archives/C010AJ1L2EN/p1610469224017600?thread_ts=1610136955.017000&cid=C010AJ1L2EN), please add the `Vaccine` topic / column to the VEO webform dataset in DOMO:

https://va-gov.domo.com/datasources/47b70ab0-d566-4a5f-b974-06018467582d/details/data/table

Once that is done, I can add the topic to our lookup spreadsheet and re-run the ETLs.

Thanks.

**Comment by clantosswett** [comment]
New topic added. Let me know if there is something else you need me to do.

**Comment by bsmartin-ep** [comment]
"Vaccine Inquiry" call type has been added the lookup table and linked to topic "COVID-19 Vaccine".

Let me know when you're adding data to the column and I'll triple check the ETL looks good.

Closing...
