### ISSUE TITLE
Access for Kelson Adams (@kelsonic)

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#1845]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.

**Mary O'Toole**

- Please provide your name.

**Kelson Adams**

- Please provide the name of your team, your role on that team, and the name of the company you work for.

**`vsa-public-websites`, Senior Frontend Engineer, GovernmentCIO**

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBpZ+OW5i8AloYMP35IQcBrEn9xMGdrheXWvGFzVRQTWidDlAkCSQ28/HagaFqT2854HZezpGkD53jsEMymxdNnDgREzItLIxFKT7MaAe9/+UJhKPUlsgHlZPhEEqBe3USQ8MhMgXm5EeAgS3FiSooEGo3T4++bebtXFZ1e1LR3OH9YA7QXKLzylUHUEsxpCAyqFpFqsoMQTqkjgWU2Zs/Krh8ggNQIlokF1IxQv0U1PoqdrTzK7rlUvecUpOmO9TzoRC8/n9UGUkqJRbgf/Kd/mrEJzLlPQYCQeNDqmV9m3Hvea9KKoiXmsZtn3ozAgLBT/+yWsA0BeYoCPRBWFdr kelsonadams@USRMonitors-MBP.home
```

- [Grant AWS Console access?]

**No**

**Comment by kelsonic** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Kelson Adams

**Comment by Karak888** [comment]
@kelsonic can we please move this someplace else for tracking or maybe in you GH acct?  Thanks!~

**Comment by kelsonic** [comment]
Moving this to closed.

**Comment by ricetj** [comment]
Still open, please do not close if you still need access.

**Comment by kelsonic** [comment]
Hey @ricetj, I think I should be all set for SOCKS proxy access now :)

**Comment by ricetj** [comment]
> Hey @ricetj, I think I should be all set for SOCKS proxy access now :)
Ok @kelsonic  I will close if you no longer need AWS access

**Comment by ricetj** [comment]
> Hey @ricetj, I think I should be all set for SOCKS proxy access now :)

@kelsonic Do you still need AWS access?

**Comment by kelsonic** [comment]
@ricetj I meant that I am ready for SOCKS proxy access now https://dsva.slack.com/archives/CLXEU7Z17/p1575308869094700 Sorry for the confusion!

**Comment by kelsonic** [comment]
I should have said "I've completed eqip so I should be ready to be granted SOCKS access now" 👍

**Comment by Jeff-Hayter** [comment]
@ricetj SOCKS approved.  @kelsonic Do you have an eqip confirmation email from the security office yet?  That may take a few days to come through.
