### ISSUE TITLE
Update new appointment data flow diagram for flat facility page and provider selection

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#18477]
We should update the new appointment flow data flow diagram to account for two recent changes:

- Flat facility page (we now call the criteria endpoints instead of parent-sites and institutions)
- CC provider selection (document the PPMS call)

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/engineering/data_inventory

**Comment by narin** [comment]
[Link to updated diagram](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1#R7V1Zl%2BI4sv41nKl5II934DE3uvpOV06eylp6nvo4bQG%2BZWzaNmTm%2FPqRZHkXYIzkBVT1kGC8yCEp9H0RoYiRer9%2B%2Fy0wN6svvg3ckSLZ7yP1YaQo8kRW4B905CM%2Bosi6Hh9ZBo5NzsoOvDj%2FBeSgRI5uHRuEhRMj33cjZ1M8aPmeB6yocMwMAv%2BteNrCd4tP3ZhLUDnwYplu9ehPx45W8dGpLmXHPwNnuUqeLEvkl7WZnEwOhCvT9t9yh9THkXof%2BH4Uf1q%2F3wMXSS%2BRS3zdfM%2BvacMC4EV1Lvjx7e%2Bfj%2F%2F%2B8udv5sO%2FfjrLf02Xxt1Y1kjrdqa7Ja88UgwX3vHOdnbw4xJ9vPfX663nRB9I0vCJ8A9wnaXz6rj4YHwBfHbumuToFjUijD6IRI2%2Ft%2BiN7xa%2BF41D3N%2B38ARZ27xnP5bv4TrlI%2BHG9NLW3T%2FimxjmegO%2Feq%2FhJm6NZcGWzndQVPONGTlQUCGSz%2BTOsbzRBDZmXngL9EsIgp1jgb%2Bijw3Ap6Svln9i7nC1aYcb%2B7u32UZxc0%2B%2BMxLlSc%2B6f2L%2FAn%2Bg0b7ytyEaBfmBcR8PDCJBNFGRDBs8Hx489U3%2FvY2QWBUJNstuQ7RO%2BIiHjotedOGaS2YvWjqoFGaPEvhbzwZoSkvw57eVE4GXjWmhX9%2BgCobHVtHahd9k1OAo8H%2BBe9%2F1A3y1%2BnCL%2Fqe%2FJBoNnbtwXDd35gL%2FI%2FOUqGXZIN9z52kT9B8e34EgcqDevIVi8eBvkY8aY5JvLlgQCVqOt0T3ksi95ubacdHq8Bm4O4Bukb52XrcRdYeeAt5zh4iu%2Bw34axAFaBi%2BJyvNjKg2svToiSJ%2By%2FS4nujxVV6HJxeaZO1YpjfP1Cv8QDTsKdpWomlbpj2MO%2FiB0p86%2Bl%2Ftv%2FgfG5FPpJLI5clMr8hc1mWK0A2dgdDv%2Flr%2B36308%2FZpPv88d7%2BF9p%2Fbl7FckTCw4RJPvvoB1GVL3zPdx%2BzoXbEPsnP%2B8NGoxpL%2FfxBFH2RimNvIL%2FZL%2FEz0oL2rddIufxtY4OCgmRLcYwZLEB0fXtX%2BCYALl79dsS0cRvf0kke3oRiV0T25qY5vfUob3prOSeoz5ZKFPlUnRaHPpKoW12YUiWsTXlp8OrlkiVeUOE3ismzw0uFUkU9mVyVynSJxSaUNcpmbxPVLlrghT49KfKJQBJ4eZC%2Fwi9bjuqEVBa7Q9DhN4prGS%2BK6fMkSV7UaSoUKxaFu5yVyqrWpJPIjQjbDTWznWzjvqGP6JXVlppTGuUEZ5zTWqXFbPNWLHueyVNIsMoXnz2iYfKrykrisqBUJn0I65WakEwox%2BPgT9eGNnnz9D%2BlS%2FOXhvfDtI%2F%2FtGQQOfHsQkIOVTk4tPfssQHs78yjFJePxKMFVjBGNV3dFeGkrdmzD28DDlmuG8RMTq%2Fbf7hjbw8YWlBAUdM7cTTGQv%2FrvyD6OzWXIQv7qBzYIxvAw%2FBJftIYCc7z4Z2mTHXcdD4yToY6t6zdK%2BuPGtO30pvmrrG0Qok5Fx%2BHki9IfsKn%2BLXc7DS0Q%2BR9J69Fvnh%2BsTTdrChyxsNWp4Y9yCnrW2IFD34uqjcI%2FRoHphQt4VXK9B9IT3qBYireXDnkSYttsM3FXxOp4KzhrMkHt64%2BqyPc1D0mT2ryyu8Sg3eU58KEGztvc4%2FtVDMx7LNSb9n03P25vlv6O7r7ZScgWHuKZMmAvzHf8BlIIwtDxPaxU4FB3Fk6zFxuCd2QOp2PsU4OTJozaeOSzGeCXIw%2BU%2FAWSOcQxWOAh0hRwsoJYCKg%2FnBAvFEt4OjyOrlwE%2Fhr%2B%2BfLjd6QN%2FSBeRUiXhbwcPHW8PlgdH8Vl%2B1w4B9xARX9MyVvD0z2jJnEAB1CbSkNtKXNnj9pUvVvUVsBsGYRjh9rq%2BPGaozi1JopTNdYoDl96GwTmR%2B6Eje9gf39652d0IEccJmWTxFTPj6HjF%2BjFiAv4IW5DNgTTlzmDvQmQeTkgsxaK%2B4Fl87EBYbKMxSE3vURvX%2FdE3sDRgaIBxiQaBMXdoFca%2B4txvbc5HxE8%2BRGWnesSXAA1iQInoWSbkYnG6Jb8Qtb9aIUhQRa%2FYno2FqAfwwMH9en8EWMDu63Alvnn378mTcbd9RmYbrRCMnyJG3pDGvytYbRNXaAsPeEZwfoBRWzaDiKPRZWfW0gHtxPAcyaUKwK2%2FciuRSgny3rZtk%2FxitNs%2B6kXkQOWmwgsdwaW0zrDcuf5F%2FoKlqhrbptAioc9jIpm%2BNvKKDGnQ0dLyRthbLQPMzWyQAjQhHrtu%2FfL8988AY9qPfP%2BfpQEb7eEkYSOPqSjXwNWGlqrvO5eTn2Qj%2FeNcBf1%2BfUhbk2tWk%2FpiJuf9TRxzgrE3Qhx6wO3nibf%2B2U9pUUxisXmAi2r%2FaUrp%2B2XqwHyO2AuuXeoEphVFKHNuLdoKitzG%2ByA629AcLMzsWtfmYP3DdSUaCvmChsv0Vm%2BFeaJz1%2FCKCz4TVv8pjgj7ytzkBfLuT5calCiX9u2BCuzbnHpabGYXUJQ5tGVdCSoaEYx9iMdEck9YhBMLiv1PwNQaAhQeJVW4nC72cCpjNdtFBnWT6y110q8IEF143S1mqdvNCY%2FOs2sxDXgRls4g%2F%2Fy%2FzUf8%2FcDfrwdFSMFW8Fw3QAfemgk%2Fyf%2Fjh75BvDi8fcW4GaY%2BVakyNrE51hQjyCE64PQ%2BwdG7FDrI%2F1iWr9ivO5E%2FwgxmYyKM5ungVpYrVu0WgvL9DEG0MOw3krWFYVmmabtf1PKIJBdUMDwDdMnY%2F2jZmRNaQnsT0uUcFL2QOwB%2B9U7lQ3IRnnze0xwuNEGWnaTI%2FC4frzngxOgba3K%2FGu6Pj5WM6whnVrRL7SFjr4%2BnwtcKVs8MOCUUIq1Ml6tfOcIMpq%2F2JzgkXEuE9zYghQEzkDzSKOpvVEf%2BZ7RaBuPFrho%2Br%2BgnufY9r3AlulQis2ZsB8CNJx4Y%2BGmTf%2FDt8h2IIYEgaUczyVRfHntCx%2BGxVKA%2FDgZy1bmWVye9hMCFUFUhaB3g5i4Lt7m8R2RcQ%2BZM4orBm43Sdv52UEOlw%2B0Njoxb7cROlpDfoNe0VlkxDJM1SMmF1hBjshuv7o08RzlKIijII7siWMvRgyrUXGVe%2FNzW6IfQGQ6bn4Z7NU2%2FaNb8vOLznyXR5qHwG8O5X0U19bTwBwFhp1skKUgpdMakevNQlTsyS05ADlOa9GTuQYHL86O3Np2AMKw5tnPq6Lj%2F9C5nyEDr3vfex%2FOYsczi34YET%2FcSHU2WDNPXHiu2qyp6qU0pJphUFK%2FqhrFsKkbE16hDbI2eMvm%2FngH8O5EfyaPhJ9zD4HfsmegL8kjmsc%2B1M2xrPdrw5sxfNv2%2FhHQvDcTy%2FDR7jSYm8HPTKEtQlNEvHK3gTOZA8J11k6N3E1UOrKfXOyJbiEm7dBaAXvrYqNNUrQFfsKVTAqVWxK7fbmRfY484VKPZR8VYXR7vrkS%2Bhcjc%2FLwP%2F%2BRSLutAdQ58K%2FthOaryzCQpUA1w8j07NggmsXhWBAOHJ5Bww9uzgfPaoegRX1OoKXpqpMUZhol1IGWYFnhltLauOSsF2fAwbpREezhYKPNdXo5p3FCP%2FfFRlQumKgtbK5LxCrQ6iUHUj%2BbeJXYOaETDSximoYp44hTXOoPfvoLDnAMJw9BTXRufIu0LuC4WDgQCwfYkFaMN1Bc4zV8uRWHSOzzACw3ANMY63IUy4mwmGNLGiJoji16IaN5lKb5%2BJS6zP0gA4f%2FZNjKBvCfdux0StDqqP%2Fm4DD1RWDGf1NpkrAFrCiQvKHcUX5EF41PVCQ3lruiIVWNlQdL2bN4M0RSnNMYCqux8dkM8UqVrUMjsvE2Kom7WIdT%2BJJEcEbux4FE9fdwX2%2BF6mq1qS63fDPGVFBd6nbngXo%2BlL5yycHyxd6HRN1usCFkjXmXtIpjPHMqtldRUTRM9D2uOAGVBOxXx8XDUPIxPI0TYCPcEq1M%2FHrmDsRbGV8B8BIAm%2BCYFcgQDtazwAw48Mcvty90pmxmXYGDuuSMEoclNlw8lbk3I91rXBgdrB8zeK%2FPC1TwaLDYJo6q%2F5QbNPGQQoOpBoc49bmPOMY8eSrUckE8e9GRRo8biFvoHs%2FnER8f20u2C5qRAAWnEfk1Bd%2BJWPGdyawu3%2BGWx8joOI3RqKd8p27Vob7xnYuv69NzSnPIqVbJJZSA%2BR5ykJNK8Bzycll1X7I5pK%2FUrhHA%2Fly%2FVatQU0SKFXoqgHPJxh4cL%2FY%2FYB%2BOlTAFr7gjh5GUzyQigi0ItiDYAl%2B2IMty53Rh0k0kYIM9O00pBhc2UbfuldyvSvSTQTnDuu25Sa96Lml3%2F3hgbxfgAcZQ5kC9jTf%2F95RKNt74z5wqnpNsqT8M8WwyNxAq9MSF6lTzFDC6cTmlgWBPgj0J9tQNe9KNaZE9KRRfi0olTyov8pS0QJCnkyB43RJm8rRXEHwmd9Lbg%2By5Wa96Thbl3a6APL1sX%2FFGbAknSk73LfeSQO3xxeVi5nLVOw5540SUXR%2Bccd9DHNKJgV1SIm4ArLFPLsAaXrAz82gz9j7WSg8Rx%2F06ax7ldn6QHU5NS9EdvvtdnPSB7JzCoctoHxr7Bz2ua9m5esjd%2B2dfyZKSCK%2BvsFsQcQi7RZd2i4mslry%2BklI1XKSu4bzhQp3wMlxMdWG4aEB%2FjZr0N%2BnMjtPDGNNSNlKF9Pu%2B9DDVC%2FQ20sOIOptXwM6Lm%2FhC17%2BsJDFJ0c1aiWLMHYS8KDnCuED468mkEYen5lPnBkNf4Juwf5EsG0kr%2FtHBGyVaYrr93fF22s7IyLfND%2B47IVEgH%2Fzyke6%2FXGyjbXAdWyJdp449loH6KfQs6%2F582AZsy3sJ0i1ItyDdTEm3kVaJTUh33fKyarlYKDvO3U0K%2FqFz7snAOPesVMfWkA6nZK1c0A7nngjOffmcO%2BcgRH6c%2F%2FpeHT9Un0j3ZvvqIuyYhBSjJKrJq7QBJZ98nKTHdHEiQ9hXUG8o91gcfpDl5Zk%2ForN8uy1umvnlv3u%2FPP%2BNa%2FgzAR6sH0CoSOsB1m2xkG%2FpMJVsEFqBs%2BmQNVyHihY8QPCAwzxAl%2BoGDUu8eMCsG99bnzD9tCamnzEvotYI009VqcQm5SN1FihXKPqIP6qfClR%2F%2Bag%2BjXPNSvOsQRiayxogrU%2FY%2Fqxg13GujHv4EUZgPUJbDeEQniNnAbqMnJF65IiQuLnY%2BEPKnA%2F1xvLX2JeqzlviHIP3h50bHNfHEOCvwAx9b5RUEDDPi9IW7glBSwQtaSEm0DBK8JAWE0j1T6SEhj0vGVSJYC68ZDZ0XqIdcTZ0xUtmgpdcPi%2F5viFBLpsALACcftbgvA0HuEf2Upz4Q1vm%2FIGi95Pxdc3dYqe%2BXOPtSgJcC3AtwHUX4FqlpFlMC07lwbXMrQrVVO0EXA88%2BCfhOseDf2TWgPys3k7aLfDuPh15RL%2F2TYUOEI2nXoKTbIJ9QuOMqjK%2F%2BlAv2WORKGOQKJ7Jq3DcRcJ198tDzKdNvIMkzsTA%2BhF3cHbgqQX1Y9TMN9aY2Fw%2BFJW1MhSlmHk1mplX44VE07cQ2ETY4nq8%2BgtbnFjFheWtz2pRWN6O0cZrs7xNypY3o3PDG7pewJ1Lhzv3%2Fnq99eL9HfdxqoPnwN85sHndw555rhqC9ANOIenT8%2FOXl%2FyW%2F1MXx7jwdqHMgmVtTl8Ea2cOQc9gD1goxRsGF6r4ioc%2Fa4SFrNTRttl%2BsiN39r0lp1sHpu1sORjXwg2wHNONBzrrm29qxU2ffFcQPDe8cYPx3kVWjz%2FwNro4u8w93hHpNLQfnfpkHpY2PjUYTRaFSSwfLrOOZxale%2BiKTSn1qWBEghEJRtTJ%2FkO1zIimSRqQPCWaUSiRRgIzeZQUVy4j0hf1HHmcbJDvjAMQ6mb8ZB4QfGYPdxNucsk9rPashzXRw4x7WO9VDyvVrLjE7B6i9HbIlrBw%2FbfKKIhF%2FZOsLnKx%2F8KVuUHnrd%2BXcF1d3aA7WCt4uxsbUqwQUXH6%2Brtv0S13H4M1U9MmN3ph0dRUJTmSWzXlZCN9wZA44bVqJiqVYkhcyWWYg8RSx4SkKDSwREncWWKp8f0r0CrfEDq2yo%2BFwpzEoK7Yz%2BRQhqv07Ns3rDDGGAXSxosP%2BxsPT%2FVh5dgQWxa0j8RmpMhSJdKTYm82KOBK52VulpVu6mkPUC8nK9hRvdyvEtpJs6t62Vr5foiNvFFlAneqpFlMtWlp45hmUDQyLZJF5pZQUdsfyYIUYVPti41ZeDc1riNW0rxXpmKVWSmCSZnQVmJaIk1u3T4dkoZlrzc1pabe1PpFWbSZ6Ld6%2FdYvY0LS7n0L3ojY%2FzOVmeVqbGXZY6LmSklYNWlaVXMKbXnjtx9%2FUHruMJJkPJPUmjNp2q%2BJVGWQeOJsvbQeSDKNtmVEieZVaTAUu%2FqI0dx8DX13G4HbwEpQPTqafdPSPsxPTwZTSy3HQKsaZWqplKllcCNpCSQVU2vf2nN8x53Cem41SoGhKlLRVqRIRG9yTWih1SCBaG5fyJRNM9F0NmX1KghhwfXycCWOz7puuqfqJZpPC%2BCkwSB%2BBjX56tOl6nV1crKsdayTtXKSoUmxosHxC5JhxzcpkXz1Ca%2Fqjyzm%2B%2Bs7Gln6tJWRdSFOgDZGVj9w5Pkja6a0MrIuxCjQxshibv7saGTJyWZgvkNL6ziiJBtN%2FykMpiakmBrPx9%2BlWX9saszV3nn0qgafbdmqy9GZqUmlMtcTSlUIWaLQHJlbVYjJhZikmk8eo65%2FxOiXf2R29WCvfs%2F1K8QuaXdO6z3gnEPopdNi07FFPq21MHTlp8vlAoVTivKjRnLwU34XEsx6xhSqjxz6NYWqwIEyhTowg%2FOcQVrZo0WLiWnVPD4dVGwFlwmk151APVuD9MoE%2Brpnqbm0aSPLnc%2BbyeGg7sZuJSeM0K8WTg4n3Eq6Ua5xTMvIS8Mc3NKgTarbK1j0fCH7oxS6fiR631DKFjBK59NCSLk5FRPEy7jzv4KdA96uvr8ncg0ncrv9vb8uouhvBv0tF%2Ft71rl2n%2FFZ1%2B99b%2BEEa5Kz5sq7farOSt2udN7tVTYqUlZcXLKvXC13G0S1ckJ2ktj0Zunv6LlNd9KolL1r1yiDZt1MppQ8WwNMZZrr92YpgAaSWemJSy6iWxa5iGg3fi5lG%2BKQllUob5FviJwg8g0dxGRaOXZEomDxtB5SIeM8tw2bsA0V0YviRzWieflUGa0EHE30qnWuNBZi8zu5rjQcWMQeSUonI6RXvc3cL9Hf3hY07QpoWlqAKg2dkNYQgNbKitqnQhS5wlHjEAQ7B1WdOFieIn8FeXnE8cKPMAJrTPbgEJ4jDoMuI2ektayIkLgWqfruWS5ArRgyH%2BRS2iJ1vnIp6NRN4YyvwAyxwXKBQ5lOKggncscKLie4XCfVNGZqicvNlGq8RIrmClyOW1KKFKYK7HbJ2E2UD2OBsUT5sD6hIFE%2BrF9qUQAeAXgOA54sxW939cNkiU%2BgoIgdoscOwZ6k9HmrUSSyNBEY9%2FIxbmqfxEnYUiPlkEDu6aZJKymUN0Z5ice5G3C1N96eZ3ISeJjDq7w4mOHxMHPiGVVNgi3xqbK172k83oyYh%2BESCB%2FprHlY6Z8xOw3wI1zTW265FKh7AmbwihZiC0dUzcMoJvyfoHZ2dvjhi8BH4zEtYhZvhA2TYfNPHq8e1%2BxMh4pkenahCZ%2F8DQpkM10OT7%2BL7f6oW9EfH48ktxFl5MREOw%2FE6l%2Bw3Ln%2BGsHjBY8XPJ4tj5drOS5oGz3TLQUcSN2MC4%2FPV55OavVkq1gIXGCJ3SIjtAlwWib6lGI9Oi3pDr%2FAREpq%2B0c4T5zXJM58ARfqbZAmAYGwDP0tdddJ%2B7L3z9D6m7HPznCVKAOyZjHpYLWcQl%2Bm7fOkFu1qsL0bfg18NBGzwDSUYeWLbwN0xv8A)

@jbalboni can you please take a look?

![image](https://user-images.githubusercontent.com/786704/108391444-9314a880-71c6-11eb-9df2-d824beb541a1.png)
![image](https://user-images.githubusercontent.com/786704/108391839-f272b880-71c6-11eb-9e90-f75ab0937c49.png)

**Comment by jbalboni** [comment]
@narin Looks good to me.
