### ISSUE TITLE
[FE] Profile: Update location link for View Payment History

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#18472]
## Background

Now that the [payment history tool is live on VA.gov](https://www.va.gov/va-payment-history), we need to update the View Payment History in the Direct Deposit tab of profile. We have it linking to eBenefits, so now we can link it to the page on VA.gov.

![Screen Shot 2021-01-13 at 9.31.30 AM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/59c947eb-27c7-49fa-a361-9622aac00eeb)

## Tasks

- [ ] Change the location of the View Payment History link to https://www.va.gov/va-payment-history/payments/

**Comment by Samara-Strauss** [comment]
Let's try to get to this ASAP since we don't want to be sending people to eBenefits at this point.

**Comment by sanlouise** [comment]
@mshea0606 The link is updated and ready for your validation :)

**Comment by Samara-Strauss** [comment]
Looks great! Thank you!

**Comment by Samara-Strauss** [comment]
Oh, because I'm paranoid, I need to ask — that link update is in a separate branch from the other direct deposit work, correct? I want to make sure we don't prematurely launch any of the edu functionality that isn't ready to go out yet.

**Comment by erikphansen** [comment]
Yes. DD4EDU is behind a feature flag

**Comment by Samara-Strauss** [comment]
Figured :) Alright, this update is good to go! Thank you!!
