### ISSUE TITLE
STEM AD: Create 10203 submission details report

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18484]
As an Education Services team member, I need reporting done on the number of 10203 submissions and denials each day, so that I can monitor the number of automated denials vs the total number of submissions.

## Assumptions:
1. This story is completed behind feature flag `stem_automated_decision`

## Acceptance Criteria:
1. A daily report is sent out that contains the 10203 and 10203 DNY spool file submissions from the previous day.
    a. In staging, the distribution is: Brian.Grubb@va.gov, Joseph.Preisser@va.gov, Lucas.Tickner@va.gov, tammy.hurley1@va.gov, Ricardo.DaSilva@va.gov, kyle.pietrosanto@va.gov, lihan@adhocteam.us, Delli-Gatti_Michael@bah.com, Darrell.Neel@va.gov, Neel_Darrell@bah.com, shawkey_daniel@bah.com, sonntag_adam@bah.com, Turner_Desiree@bah.com
    b. In production, the distribution is: Brian.Grubb@va.gov, Joseph.Preisser@va.gov, Lucas.Tickner@va.gov, tammy.hurley1@va.gov, Ricardo.DaSilva@va.gov, kyle.pietrosanto@va.gov, Joshua.Lashbrook@va.gov, shay.norton@va.gov, dana.kuykendall@va.gov, Jennifer.Waltz2@va.gov, kathleen.dalfonso@va.gov, lihan@adhocteam.us

2. The report header has the following columns names:
    a. Submitted VA.gov Applications - Report YYYY-MM-DD
    b. Claimant Name
    c. Veteran Name
    d. Confirmation #
    e. Time Submitted
    f. Denied (Y/N)
    g. POA (Y/N)
    h. RPO
3. Each row of the report contains the following information when available
    a. Claimant Name: Name of claimant from application [string]
    c. Veteran Name: Name of veteran from application [string]
    d. Confirmation # : Confirmation number from submission [string]
    e. Time Submitted: Date + Time form was submitted [format: 2021-01-06 10:45 AM]
    f. Denied: Y/N indicator of if the submission was denied or not
    g. POA: Y/N indicator of if the applicant has a Power of Attorney or not ( or blank if not available)
    h. RPO: Name of the RPO to which the submission was directed
4. The last row in the report displays the following:
    a. Total Submissions and Denials
    b. Count of Total Submissions
    c. Count of Total Denials

## Supporting Artifacts:
1. [new_10203_submission_report.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5809880/new_10203_submission_report.xlsx)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5726

**Comment by desireeturner** [comment]
We received confirmation from Kyle Pietrosanto that he received the report during yesterday's EDU call (01/28/21). Based on that we are good to close this issue.

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/tests/view/44159&group_by=cases:section_id&group_order=asc&group_id=51)
