### ISSUE TITLE
Update location in Add to calendar ICS file to reflect phone appointments

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#18488]
In the ICS file created from the Add to calendar link, we set a location. For VA appointments, we use the VA facility. However, for phone appointments, we should probably indicate that it's a phone call, not a physical location.

May need to do some research as to how you can note that in an ICS file, or if we should just say something like "Phone call" in the location field.

**Comment by jenniemc** [comment]
@laurenernest , @outerpress , this ticket is to correct the text within Add to Calendar file for `phone appointment`. So what i'm describing is out of scope for this ticket but want to bring it up anyways. 

### Regular Homepage confirmed phone appointment card: 

This is the screen image for the phone appointment. While it does indicate `VA Appointment over the phone`, it shows the facility address and the `Directions` link
![image](https://user-images.githubusercontent.com/54327023/109338289-0c9a3f80-7834-11eb-9178-1ade12b180ec.png)

This screenshot fixes the Add to Calendar bug replacing the facility address for `Phone call`

![image](https://user-images.githubusercontent.com/54327023/109338041-b62d0100-7833-11eb-9125-1627514dddb6.png)
 
### Homepage Refresh confirmed phone appointment card:
![image](https://user-images.githubusercontent.com/54327023/109339571-d52c9280-7835-11eb-9025-9fe1e08197e1.png)

The details page does not say `VA Appointment over the phone`
![image](https://user-images.githubusercontent.com/54327023/109339228-55062d00-7835-11eb-9985-31ea0486c377.png)

**Comment by outerpress** [comment]
Thanks for catching that @jenniemc !

@laurenernest I'll put together states for phone appts - pending, confirmed, and canceled. I have some questions about what data should/shouldn't show for these but can discuss them separately if this is going to be a new ticket.

**Comment by laurenernest** [comment]
Here's the ticket to cover this label change #20547
