### ISSUE TITLE
VSP onboarding: re-create transformer for node-press_releases_listing

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18494]
## Description

Review the CMS [documentation](https://vfs.atlassian.net/wiki/spaces/VP/pages/637567205/Transformers+Development+Guide) and re-create the following for the `node-press_releases_listing` bundle:
- Input schema
- Transformer
- Output schema

Start with branch called `cms-press_releases_listing`

_Annotate questions or suggestions to the documentation pages in confluence. Add other suggestions as a comment to this ticket._

## Prerequisites

- Grab the `pages.json` from `yarn build:content --pull-drupal`
- CMS export from `yarn build:content --use-cms-export --pull-drupal`
- The CMS export can be found in `.cache/localhost/cms-export-content/`

## Test
Test transformer using `node script/cms/test-bundle-transformers.js --bundle "node-press_releases_listing" --print 8`

[Example](https://staging.va.gov/pittsburgh-health-care/news-releases/index.html) of page that uses this transformer

### Build Setup
1. yarn build:content --pull-drupal
2. mv build/localhost/ build/graphql-localhost/
3. yarn build:content --pull-drupal --use-cms-export
4. mv build/localhost build/cms-export-localhost/
5. Run `diff -ur graphql-localhost/pittsburgh-health-care/news-releases/index.html cms-export-localhost/pittsburgh-health-care/news-releases/index.html | delta`

*** Delta is needed to run the command with colors (not required) (edited) 
*** If wanted to compare only HTML code without debugging info - Delete the contents of src/site/includes/debug.drupal.liquid

## Acceptance criteria 
- validate output of transformers. Instructions [here](https://vfs.atlassian.net/wiki/spaces/VP/pages/637567205/Transformers+Development+Guide#Validation)
- validate the html output is the same as the graphQL by comparing the builds (followed instructions above)

**Comment by billfienberg** [comment]
Notes from pairing session with @k80bowman:

- [Branch](https://github.com/department-of-veterans-affairs/vets-website/tree/cms-press_releases_listing-2020-01-13)
- [Thread](https://dsva.slack.com/archives/CQH357ZTP/p1610563699386500)

**Comment by billfienberg** [comment]
Relevant Files:

- build/cms-export/pittsburgh-health-care/news-releases/index.html
- src/site/layouts/press_releases_listing.drupal.liquid
- src/site/stages/build/process-cms-exports/transformers/node-press_releases_listing.js
- src/site/stages/build/process-cms-exports/schemas/input/node-press_releases_listing.js
- src/site/stages/build/process-cms-exports/schemas/output/node-press_releases_listing.js

**Comment by billfienberg** [comment]
Questions:

- If the schemas pass, but the diff fails, does that mean that the transformer is wrong, the CMS export data and the GraphQL don’t match, both, or neither?
- Is there anything we can do to reconcile the GraphQL data with the CMS export data before anything goes through the transformer? 
- It seems like the schema validation can confirm if the shapes match, but it would be unreasonable to expect the diff to pass if the inputs are different, correct?

**Comment by meganhkelley** [comment]
Does anyone have remaining Qs here or a need for another Q&A session, or can we close this ticket? @timwright12 @billfienberg @alexandec @k80bowman cc @Clark-W-Griswold

**Comment by billfienberg** [comment]
> Does anyone have remaining Qs here or a need for another Q&A session, or can we close this ticket? @timwright12 @billfienberg @alexandec @k80bowman cc @Clark-W-Griswold

Good question. It feels like the spirit of this ticket is to learn how how all the pieces (GraphQL data, CMS export data, input schemas, output schemas, the transformer, the schema validation, diff) fit together. If that is the goal of this ticket, then my gut says it's done, and we can close it. 

If the goal of the ticket is to get a diff where the transformed CMS Export data perfectly matches the GraphQL data, then I don't think we should close it.
