### ISSUE TITLE
Complete "nice to haves" for HLR security review

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18495]
## User Story
As a developer, I want to make sure the back end systems I work with are capable of handling the expected throughput from our system.

## Description
- Determine the paper/fax form volume today, to get an idea how much traffic we may incur.
- Ensure we aren’t going to flood CaseFlow (N/A, no auto establishment) or CentralMail with unexpected traffic.
-- Note from Luke: Is the CentralMail issue not something that should be answered by Lighthouse? Update: I have asked the question to Lighthouse

## Acceptance Criteria
- [x] Tell Michael Fleet the answers to the above.

**Comment by edmangimelli** [comment]
main ticket https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/174

**Comment by luke-gcio** [comment]
174 was closed, submitted all responses to blockers and nice to haves.
