### ISSUE TITLE
[Discovery] Evaluate ability to programmatically retrieve weekly/monthly analytics data from GA

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#185]
## User Story
As a Product Owner, I need to have automatic, regular, and easy to consume analytics updates in order to use data regularly as a part of my workflow.

## Discovery Question
Can we pull real-time data that shows weekly and monthly analytics and display it somewhere for edu stakeholder to access?

## Constraints/Assumptions
- We can pull the data programmatically

## AC 
- [ ] Discovery has been conducted
- [ ] A readout of findings is documented
- [ ] If we can pull the data from GA, update the Google Sheets MVP so that it populates the fields automatically from GA weekly and monthly
## Resources
- [Google Sheet EDU Prototype](https://docs.google.com/spreadsheets/d/1go-gIeGXb_W-XdJzW3xLT__UUspXX5hwfY2K0ovqkTo/edit#gid=1289815191)

### Example of Automated Weekly Analytics
- [Script that handles automated collection and delivery of metrics from GA to Sheets](https://script.google.com/a/oddball.io/d/19O_-27JeC1Syna9fLLfoXNP37zLednwufJH8iu15tmO9EkqGi4zylWSP/edit)
- [Script that handles file interactions with `Drive` and `Slack`](https://script.google.com/a/adhocteam.us/d/1QD0jK62NXaa9Cj0hqSP8CLvlg-iUdW_uns0_ra6Rem1XVeNRW381vEui/edit?usp=sharing_eip&ts=5ccb4891)
- [Analytics Sheet that script outputs to](https://docs.google.com/spreadsheets/d/1L_w8FhhcOttMitKB3_9ge8UN01GcSXmaPZWDIRJIhxI/edit#gid=972187789)
- [Automation Issue Reference](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17972)

**Comment by rroueche** [comment]
@jholton and @joanneesteban for awareness, I updated the last acceptance criteria to: ```If we can pull the data from GA, update the Google Sheets MVP so that it populates the fields automatically from GA weekly and monthly```

**Comment by jholton** [comment]
From looking at the [GA Reporting API v4 documentation](https://developers.google.com/analytics/devguides/reporting/core/v4/) and the current [weekly analytics script](https://script.google.com/a/oddball.io/d/19O_-27JeC1Syna9fLLfoXNP37zLednwufJH8iu15tmO9EkqGi4zylWSP/edit), I believe it is possible to update to update the Product Health prototype programmatically with GA data.
The GA API makes retrieval [Goal Conversions and Event Tracking](https://developers.google.com/analytics/devguides/reporting/core/dimsmets) data possible, which is the types of data we are targeting for our MVP.

The current weekly analytics script provides a great example/starting point for implementing this work.  

Given the lift involved, implementing this should be it's own issue for sprint work (as opposed to being AC for this issue).  Thoughts on that, @rroueche?

**Comment by joanneesteban** [comment]
Discovery has been completed and the build for automation is high effort. Created a [new issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/284) to address the automated GA pull, which will need an engineer assigned, and closing this discovery ticket.
