### ISSUE TITLE
[FE] Analytics cnp string update

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18505]
## Tasks
- [x] Check with Ben Mcgrady that the cnp updated google analytics string is ok
- [x] Remove isprod check

**Comment by erikphansen** [comment]
@bmcgrady-ep on Monday, Jan 25, can you confirm that everything looks fine in GA? We will no longer be using the non-CNP-prefixed tags and strings after today's deploy goes out. Thanks!

**Comment by bmcgrady-ep** [comment]
@erikphansen - Everything is looking fine in [GA](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210123&_u.date01=20210126&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.filter=profile-get&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25). Let me know if you need anymore help!
