### ISSUE TITLE
Update BGS Gem for Read Diaries

### ISSUE THREAD

**Issue by kathleencrawford** [department-of-veterans-affairs/va.gov-team#18506]
## Goal
We need to call the BGS Diaries Web Service to determine whether or not the Veteran needs to verify the status of their dependents.

## Tasks
- [x] Update BGS gem to allow the `readDiaries` service to be utilized

## Acceptance Criteria
- [x] BGS gem code is submitted and a PR is requested for merging

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/bgs-ext/pull/56
