### ISSUE TITLE
Add a "First Seen" Sentry Alert Rule

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#1851]
### Background
A recent issue existed in Sentry that didn't have a high enough affected users or volume of errors in order to trigger a Sentry Alert, but it was something we wanted to know about - [Link to Sentry Issue](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/71623/?query=is%3Aunresolved)

### More Context
There are too many issues in Sentry to only key off of "First Seen", so we will have to get creative in combining this attribute with some minimum volume or affected users metric. 
### Work to be Done
- [ ] Create a Sentry Alerting Rule that keys off of "First Seen"

**Comment by LindseySaari** [comment]
This issue did not require a PR, just a rule change in Sentry. The new rule can be viewed here: http://sentry.vfs.va.gov/settings/vets-gov/projects/platform-api-production/alerts/rules/
