### ISSUE TITLE
Picker options are not accessible using Voice Control on iOS

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18523]
## What Happened?

1. With Voice Control enabled on iOS, after selecting a native picker, there is not a way to scroll through the options in the picker using voice control 

## Specs:
- Device: iOS - iPhone11 with Voice Control enabled

## Steps to Reproduce: 
1. With Voice Control enabled on iOS, navigate to any page in the app that has a native picker, such as the Edit Address page
2. Select the Country picker using voice control
3. When the picker is opened, try to scroll through it by saying "scroll up" or "scroll down
4. Note that the picker cannot scroll through the picker options

## Desired Behavior
When Voice Control is enabled, the user should be able to open the picker and scroll through the menu options by announcing them. 

## Acceptance Criteria
- See desired behavior

## Bug Severity
- 3 - Medium

## Screen Shot(s) and Additional Information 
![c3a8af36-d6fb-44d1-aaaa-a3beaacef59e.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/8a9ec848-53f6-4309-92a0-220aaee50120)

**Comment by bessgreen** [comment]
Note: @komaly15 worked on a similar [bug fix](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/16583) for Android. The iOS/VoiceOver issue in this ticket is due to a problem with the package.

**Comment by bessgreen** [comment]
@ayushchak fyi

**Comment by bessgreen** [comment]
Blocked. No known solution.

**Comment by digitalken** [comment]
4/28/2021 - FIXED with new picker.  Closing.

**Comment by chriscm2006** [comment]
@bessgreen "Increment month. The "Increment BLANK" terminology is how one would interact with native pickers. 

Sorry for randomly interjecting. This is a public issue and some people internally were trying to use this as evidence that the Native Picker isn't accessible. Turns out it's just Voice Control creating confusion! Thought this might be useful information!
