### ISSUE TITLE
Analytics Implementation or QA Support for Decision Tools - Find a VA Form sort feature

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18525]
# Google Analytics Implementation 

## What this form is for 
- Event capture for a new sorting feature being implemented in the Find a VA Form product
<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics

- Who is this request for?

    - @johnhashva John Hashimoto
    - @zacharymorel Zachary Morel
    - @MarciMcGuireGCIO Marci McGuire
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    -  Decision Tools team, Find a VA Form - sort feature.  More details are available here -> https://github.com/department-of-veterans-affairs/va.gov-team/issues/17901

- Provide the Domain where Google Analytics needs to be implemented
    -  www.staging.va.gov and eventually va.gov production
    
    _Identify if PII is passed in URL or title tag_
       -  No PII 

    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    - We would like to put this into Production **Feb 9, 2021**

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* 
 
        - When a user conducts a search, the search results will also provide a facility for sorting the results by Last Updated date.  We would like to determine how many users are taking advantage of this sort option:
            - Mockup of sort tool (not yet implemented as of 1/13/2021):
  
![image](https://user-images.githubusercontent.com/73354907/104511355-95c62180-55ba-11eb-8699-939ca624c31f.png)

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
     - N/A this is part of the unauth experience

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
     - N/A this is part of the unauth experience

- Certain conditions/responses that need to be reviewed
    - Sorting, once implemented, will be displayed for any search yielding > 1 result.

- Additional Comments
    - The new sorting feature should be available on staging the week of Jan 26

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by zacharymorel** [comment]
Note to self: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17273

**Comment by zacharymorel** [comment]
@jonwehausen The Sorting Analytics is now live on https://staging.va.gov/find-forms/?q=health .

**Comment by jonwehausen** [comment]
### QA Testing
@zacharymorel Very much appreciated here. Confirmed and closing 

Description of Interaction | Data Layer Screenshot | Tag Screenshot | Test Status
| -- | -- | -- | -- |
Click on **"Last Updated (Oldest)"** in dropdown | ![image](https://user-images.githubusercontent.com/48527022/105902814-22c29f00-5fed-11eb-9260-d0c0e1aa817c.png) | ![image](https://user-images.githubusercontent.com/48527022/105903256-a5e3f500-5fed-11eb-8886-3c67be428ef3.png) | ✔️ **PASS**
Click on **"Last Updated (Newest")** | ![image](https://user-images.githubusercontent.com/48527022/105902954-4a196c00-5fed-11eb-85c5-b7c1035360a4.png) | ![image](https://user-images.githubusercontent.com/48527022/105903323-bb591f00-5fed-11eb-8f38-f9a771facf49.png) | ✔️ **PASS**
