### ISSUE TITLE
Create Product Support Team OKRs

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1853]
As a product support team, we want OKRs so we know what our overall mission and goals are for the team. 

AC:
- [ ] OKRs are created

**Comment by andreahewitt-odd** [comment]
https://docs.google.com/presentation/d/1if-Cvp7ylIlPBbj5QyU5akHt4MILxxbVPgjGwF--560/edit#slide=id.g639ada1118_0_51

**Comment by johnpaulashenfelter** [comment]
OKRs are here: https://docs.google.com/document/d/1B71DHv22vNeNFtt27YEUN1sdX3AJNqMedp3a4NgaIgU/edit
