### ISSUE TITLE
Spike: Research into feasibility of highlighting diff in suggested addresses

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#1854]
When suggesting an address to the user after they have input their address, the suggested addresses would ideally highlight the parts of the suggestion that are different from the address the user input. We should spend a little time researching if it's feasible for the FE to do this.

Technical discovery information on how to write the function that will do this work. @Erik will verify if this is feasible or not.

**Comment by artistgreen** [comment]
![Profile-suggest an address-address not recognized message-rev1.png](https://images.zenhubusercontent.com/5d49d1baa8585c0001b6a7a8/d11b3b07-550a-499e-8be5-797a4141ab37)

**Comment by erikphansen** [comment]
Highlighting the diff in suggested address vs the input address seems totally doable. Closing this.
