### ISSUE TITLE
Homepage - apply cancel functionality to appointment details pages

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18545]
## Issue Description
Apply existing functionality to cancel a request or confirmed appointment to the new appointment details pages.

---

## Acceptance Criteria
- [ ] Changes are behind the va_online_scheduling_homepage_refresh feature flag

- [ ] When user clicks/taps cancel, request or confirmed appointment is canceled

- [ ] Appointment detail page has a unique URL

**Comment by narin** [comment]
@laurenernest @outerpress After the users cancels, should we remain on the details page and update it to the Canceled state, or should we redirect them to the list page?

**Comment by outerpress** [comment]
If we send them on the details page in the canceled state it'll act as a confirmation after they've canceled. Sending them to the list page it might be confusing, esp if they have to scroll around to find the canceled event.

So I'll say go with your first option - remain on the details page and update it to the Canceled state.
