### ISSUE TITLE
Address deletions fail if address fails address validation

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18549]
[Slack thread with VA Profile team](https://dsva.slack.com/archives/C7TE0PFTL/p1608138662207400)

Attempting to delete a saved address can fail if that address fails address validation. This is because a delete operation must pass the same address validation step as any other address add/edit operation.

I believe that a delete operation should be able to skip the validation step. We should work with the VA Profile team to change how deletes are handled on their end. If that is not possible, we will need to change how we handle deletions on VA.gov, inserting a call to the validation API before making the delete.

Steps to reproduce:

1. First make sure the address on file is one that does not pass address validation thus requires manually confirming that it is the correct address. `123 elm st, San Francisco, CA 94122` works.
2. Attempt to delete that address.
3. The deletion will fail. (Note that, likely due to [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18547), the browser will not scroll to the error alert at the top of the address edit form)

The errors from the `profile/status/{transaction-id}` look like:

```json
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_address_transactions",
    "attributes": {
      "transactionId": "11fcca2c-619b-4827-8242-3db4efa00066",
      "transactionStatus": "COMPLETED_FAILURE",
      "type": "AsyncTransaction::Vet360::AddressTransaction",
      "metadata": [
        {
          "code": "ADDRVAL112",
          "key": "addressBio.AddressCouldNotBeFound",
          "retryable": null,
          "severity": "ERROR",
          "text": "The Address could not be found"
        },
        {
          "code": "ADDR306",
          "key": "addressBio.lowConfidenceScore",
          "retryable": null,
          "severity": "ERROR",
          "text": "VaProfile Validation Failed: Confidence Score less than 80"
        }
      ]
    }
  }
}
```

**Comment by erikphansen** [comment]
This is still happening in staging and prod.

**Comment by erikphansen** [comment]
This should be [fixed with the 14.2 release that was due to go out on Feb 8](https://dsva.slack.com/archives/C7TE0PFTL/p1610720897001900?thread_ts=1608138662.207400&cid=C7TE0PFTL) but the issue still exists in prod.

**Comment by mshea0606** [comment]
Current status: VA Profile team is fixing this issue via bug ticket VAPro-t1-1496.

**Comment by Samara-Strauss** [comment]
Do we have an estimated date for this fix?

**Comment by mshea0606** [comment]
They don't have an estimate at this time

**Comment by Samara-Strauss** [comment]
Ok, got it. Thanks!

**Comment by Samara-Strauss** [comment]
3.5.21 — VA Profile says they fixed this in their QA environment. @erikphansen can you validate this in staging?

**Comment by erikphansen** [comment]
Update: still can't delete an address that requires validation, but the error is different now. This was using staging user 36:
```json
{
  "data": {
    "id": "",
    "type": "async_transaction_va_profile_address_transactions",
    "attributes": {
      "transactionId": "fd69dcf8-9af0-4aa5-8cd1-d120f68ba6bb",
      "transactionStatus": "COMPLETED_FAILURE",
      "type": "AsyncTransaction::VAProfile::AddressTransaction",
      "metadata": [
        {
          "code": "ADDR155",
          "key": "AddressTypeLookupMismatch",
          "retryable": null,
          "severity": "ERROR",
          "text": "Address Type value does not match Lookup Service"
        }
      ]
    }
  }
}
```

**Comment by Samara-Strauss** [comment]
3.5.21 — Next steps: This issue is going to be escalated to the VA Profile production operations (ProdOps) team. They will reach out to us over email for more information.

**Comment by erikphansen** [comment]
Sounds like @lihanli will have to start sending titlecase address types instead of ALL CAPS. Example: `'Domestic'` instead of `'DOMESTIC'` https://dsva.slack.com/archives/C7TE0PFTL/p1614965261044500 Or is that a change the FE will need to make as well, Lihan?

**Comment by lihanli** [comment]
i can take whatever case the frontend sends and change it to the correct one on the backend https://github.com/department-of-veterans-affairs/va.gov-team/issues/21031

**Comment by erikphansen** [comment]
Perfect. Thanks!

**Comment by Samara-Strauss** [comment]
@lihanli I will add #21031 to next sprint so it doesn't distract from this sprint's work.

**Comment by Samara-Strauss** [comment]
Adding blocked label to indicate we can't make any progress here until VA Profile fixes things on their end.

**Comment by Samara-Strauss** [comment]
Via [Slack](https://dsva.slack.com/archives/C909ZG2BB/p1616158569058300?thread_ts=1616156699.057900&cid=C909ZG2BB) — Erik confirmed earlier this week that this is still not working.

**Comment by Samara-Strauss** [comment]
**From 3.19.21 VA Profile call**

@lihanli @erikphansen I posted [in Slack](https://dsva.slack.com/archives/C7TE0PFTL/p1616174259003700), but Mike Richard mentioned that in order to continue their investigation, VA Profile needs more information on the sequence of calls we are making when we want to delete an address. Please follow-up with him directly in Slack, as I don't have any more detail than this.

**Comment by Samara-Strauss** [comment]
**From VA Profile call 3.19.21**

I was told this was elevated to Josh Lindsey, who is investigating what is going on. Nothing needed from our team at this time, but Josh will likely follow-up once his investigation is complete.

**Comment by lihanli** [comment]
deleting `123 elm st, San Francisco, CA 94122` works for me on staging

**Comment by erikphansen** [comment]
it works now!

**Comment by erikphansen** [comment]
Confirmed with a couple addresses that require validation in order to get saved. I was able to delete both of them. So I am gonna close this.

**Comment by erikphansen** [comment]
Also confirmed in prod.

**Comment by Samara-Strauss** [comment]
YAY! This is great news! I will let Mike Richard know.
