### ISSUE TITLE
General Analytics Request for Dependency Verification Special Project

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/va.gov-team#18546]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Steve Kovacs (steve-gov)

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - Special project of the office of the Chief Financial Officer
    
- What type of analytics support are you looking for?
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

Calendar Year 2020

## Analytics to Track Down

1. In CY2020, how many Veterans logged into VA.gov 1-3 times?
2. In CY2020, how many Veterans logged into VA.gov more than three times?

## Which Product Questions are you trying to answer?

We are forming product hypotheses around broad cohorts of Veterans: those who are either frequent, infrequent, or non-users of Va digital platforms.

What will be the level of effort to contact Veterans who are infrequent users or non-users of VA digital platforms and direct them to specific digital services in a timely way?

Further context: https://dsva.slack.com/archives/C1Q4294JJ/p1610577882244700

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@steve-gov -

We have a couple ways of looking at this.  Do we want to count individual login events or sessions where a login event occurred?

The numbers I gave you in Slack are the latter.  As in - how many sessions with a login event does each user have.

Counting successful "modernized" login events on va.gov  (`login-success-idme`, `login-success-dslogon`, `login-success-myhealthevet`) for CY 2020, we get:

Description | Users 
 -- | -- 
1-3 login events | 6,044,072 
\>3 login events | 954,317

Is this what you are looking for?  This would include (I believe) both LOA 1 and 3.

**Comment by steve-gov** [comment]
This will work for now, thanks.
