### ISSUE TITLE
"Are you sure?" deletion alert stays pinned to bottom of window

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18547]
When the "Are you sure?" confirmation alert is visible during a contact info deletion operation, it constantly forces the browser to scroll so that the alert is pinned to the bottom of the window.

To reproduce:
1. Start the process of deleting an existing contact info field
2. The "Are you sure" confirmation alert will appear and the page will scroll so that is positioned at the bottom of the page
3. Scroll the page up or down
4. Make a change to the contact info field
5. The page will again scroll so that the alert is positioned at the bottom of the page.

https://user-images.githubusercontent.com/20728956/104530076-07ed3500-55c0-11eb-888d-bb973ebea60d.mp4

**Comment by erikphansen** [comment]
I just noticed this same thing occurs with the `We’re sorry. We couldn’t update your <contact info>. Please try again. ` error alert. When it is on screen, any updates to the contact info form trigger a scroll so that the alert stays pegged to the top of the browser window.

**Comment by erikphansen** [comment]
@ajakabcin I just merged a PR for this. It will _eventually_ be on staging where it can be validated, but who knows when :(

**Comment by ajakabcin** [comment]
confirmed on staging - no longer seeing this issue
