### ISSUE TITLE
[spike] vtk feedback: Explore other success metric options

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#18556]
## Issue Description
We currently commit module changes after invoking the module generator with a standard commit message . A developer expressed that they did not like the initial commit that is created by the generator and had concerns about squashing commits. The commit message is used for tracking success metrics for module generator usage. The developer also expressed that the commit message approach won't work long term since we squash commits

## Other Notes
The two approaches that are currently being explored are using Google Analytics and DataDog.  

## Definition of Done
- [x] Document outlining the listed approaches above and a decision on which one we are going with and initial steps to complete.
- [x] Ticket describing new approach to success metric.  Consider what it takes to implement including tokens for tracking service.

**Comment by erluti** [comment]
Perhaps vtk could spawn a thread to post uses to Google Analytics or DataDog or Prometheus (or whatever).

**Comment by erluti** [comment]
Doing a `git add .` has it's own issues beyond just trusting devs to leave the message we're tracking.

**Comment by LindseySaari** [comment]
[Datadog events](https://docs.datadoghq.com/api/v1/events/)

**Comment by alexpappasoddball** [comment]
@LindseySaari Updated the ticket a tad bit!

**Comment by alexpappasoddball** [comment]
@ericboehs & @LindseySaari, The last step of this ticket would be to wright out the decisions we've made and why. We can do that here in the ticket, or in Confluence in our team section. Then this ticket can be closed and we can move on to [this](url) ticket!

**Comment by LindseySaari** [comment]
On 1/19/2021, the backend tools team met with the analytics team to discuss potential success metric tracking options for the vtk toolkit usage. We discussed two potential options, DataDog and Google Analytics. It was decided that DataDog was the the preferred solution over GA. 

Why not GA?
A GA solution wouldn’t be as straightforward because it’s typically used for tracking webpages. In our case, we wouldn’t be invoking via a webpage and rather sending off a post request from within the toolkit. The solution would involve some non-standard architectural decisions and we’d have to insert a URL (which is required) for the calls to the GA API.  In short, we would have to “fake” the url since the GA call wouldn’t be coming from a webpage. The analytics team developers also expressed that there wouldn’t be as much customization with GA and we’d like to have the ability to pass along metadata with the post request. 


Why DataDog? 
The developer preferred solution was decided upon as DataDog. 

- We would have the ability to set up visualization for PMs or developer view 
- More control over custom metadata
- No need for a url since we’re not invoking via webpage
