### ISSUE TITLE
"Crash" when Personal and contact information letter is chosen (Android and iOS)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#18550]
## What happened?
When I select the "Personal and contact information" letter config page, it pauses for a moment and then (on the Android) it scrolls up off the screen leaving a white screen.  With iOS, I can't see the scroll but I'm left with a white screen.  I've repeated it with a few different logins. (but I found one where it doesn't crash, so it seems like it might be data related somehow.)

## Specs:
- Any Android, iPhone 
- Logins that "crash": vets.gov.user+100@gmail.com, vets.gov.user+150@gmail.com
- Logins that don't "crash": vets.gov.user+50@gmail.com, vets.gov.user+1@gmail.com

## Steps to Reproduce
Log in as user that crashes (See Specs).
Navigate to the Personal and contact information letter config page.

## Desired behavior
Config page continues to display.

## Bug Severity
- 2 - High

## Linked to story
none

## Screen shot(s) and additional information
none

**Comment by bessgreen** [comment]
1/14: received approval from Bridget to hide null fields on the Benefit Summary configuration page

**Comment by digitalken** [comment]
PASS 1/21/2021 - No crashing with example accounts on Android or iOS.
