### ISSUE TITLE
IA Feedback - Usability Testing Pre - VAOS refresh

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#18558]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- The prototype shows a change in the H1 on the static landing page. The H1s and URLs utilized in the live experience are based on SEO and previous user research and data.   If you are proposing a change to the H1s and/or the corresponding URLs (which follow the same keyword data and should be consistent/match), research/user feedback, as well as SEO data is needed to support that.  I do not see a line of questioning or a research goal that focuses on the terminology, findability and navigation components. These should only be changed in the prototype if user feedback will be collected during testing to either prove/disprove the change.  If research shows positive responses to the change it is recommended that the team also have corresponding search and SEO data to support the change.
- The breadcrumbs on both the VAOS home page as well as on the appointment detail page do not align with the H1s of the previous page.  On mobile, only the previous page component of the breadcrumb is shown, that component should be the same as the H1 of the previous page.  In other words, if the previous page is "Your appointments", that is what the breadcrumb should be.  

**Should:**

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by outerpress** [comment]
Thanks for the feedback Mikki!

I changed the static landing page text back to its current state. Thanks for the background on that. I understand that page is part of a larger set of pages and am talking to @DanielleThierryUSDSVA about potential changes. The current page title/bread crumb will work for now. I'm mainly interested in testing whether moving the CTA up the page a bit will improve things.

The header for the home page is still an issue. In VAOS today the h1 reads "VA appointments" and the breadcrumb reads "VA online scheduling." If we left this as is, the breadcrumb would look like this from the appt detail page:

<img width="736" alt="Screen Shot 2021-01-18 at 3 59 25 PM" src="https://user-images.githubusercontent.com/2536801/104972313-490d8c80-59a6-11eb-95ca-57aa83b677fc.png">

My worry is that users will expect clicking "Schedule and view appointments" will bring them back to the home page, since those are the main actions on that page.

It makes sense that the h1 and breadcrumb should match, so we just have to find a new title for the home page. @peggygannon what are your thoughts on this? I dropped in "Manage appointments" as a working title (in the breadcrumb) but am open to whatever works best.

**Comment by peggygannon** [comment]
@outerpress are you referring to the first page of the VAOS tool when you say home page? .va.gov/health-care/schedule-view-va-appointments/appointments?

**Comment by outerpress** [comment]
Yep @peggygannon that's right. The shorthand I've been using is:
* Static landing page: va.gov/health-care/schedule-view-va-appointments/
* Home page: va.gov/health-care/schedule-view-va-appointments/appointments

**Comment by mnorthuis** [comment]
Hi @outerpress,  the recommendation from an IA standpoint for these static pages is that once a user is authenticated, they bypass the static landing page because it doesn't typically provide any value to the user AND for the reason you mention above - it feels duplicative to the actual tool.  The primary purpose of static landing pages are for SEO and unauthenticated users.  Based on that, then the static landing page is removed from the breadcrumb when you are authenticated, because its bypassed and the user cannot access it anymore.  So the breadcrumb when you are in the tool (or scheduling home page as you refer to it) would be: 
Home > Health care > VA online scheduling > Appointment detail

That is the approach we have been recommending for other authenticated tools.

**Comment by outerpress** [comment]
Thanks @mnorthuis that makes sense. The VAOS static page might be a bit different than others, as we check on that page if a user is registered at a Cerner facility and redirect them to another portal from that page if so (@laurenernest I'm a little fuzzy on this flow, correct me if I'm wrong here.) Ideally we'd let them pass through the static page if they're authenticated, as you described.

I'm wondering though if we'd lose anything by dropping the breadcrumb to the static landing page once a user is logged in from any source. I'll take a look at those flows. It'd be nice to simplify that breadcrumb trail a bit.

**Comment by outerpress** [comment]
(Months later...sorry! Other work took precedence over this.)

@laurenernest  I think we just need to update the current breadcrumb (Which says "VA online scheduling") to the use the header for VAOS home ("VA appointments") to call this done.

I want to take a closer look at the breadcrumbs in the detail view, but will create a new ticket for that.

**Comment by outerpress** [comment]
@mnorthuis here's the new ticket for what we chatted about re: the VAOS thumbnail/detail view concept: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23104

And we're looking at the h1 and breadcrumb name in this content review ticket: https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/23018

I think that covers everything so I'm going to close this one, but let me know if I'm missing anything. Thanks!
