### ISSUE TITLE
Assist VAOS team with initial 508 findings

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#1856]
Assist the VAOS team in understanding the existing 508 findings. Provide examples how the design system and best practices could reduce or mitigate these findings. A spreadsheet has been provided to @1Copenut offline documenting findings for the existing product.

**Comment by 1Copenut** [comment]
I have provided initial findings as a attached text document.

**Comment by 1Copenut** [comment]
[Initial accessibility notes (text file)](https://app.zenhub.com/files/133843125/770622c7-f94e-4c3e-9357-384b3ba30d6f/download)
