### ISSUE TITLE
DebtRes FSR Income - Content needed fo rGross monthly income

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#18567]
Story: As a Veteran filling out FSR I would like to understand what gross income means so I can put the right amount into the field

![image.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/ef6d68e5-476a-46ab-b42e-b6f438658d0c)

Tasks: 

- [x] Write content

- [x] Provide Content to FE dev

**Comment by rileyorr** [comment]
Danielle provided helper content for the 'gross monthly income' field and I've added it to [the UXPin prototype](https://app.uxpin.com/edit/8733985#?id_page=136159504) with the VSP design council's recommended styling.

**Comment by leahkeeler** [comment]
@rileyorr uxpin is asking me to log in so I can't see it. Does FE have a tix for this?

**Comment by rileyorr** [comment]
@leahkeeler my bad! I posted the wrong link; I've updated my original comment with a link that should be viewable. This work is captured in the content update epic

**Comment by leahkeeler** [comment]
Perfect! Thanks - closing tix
