### ISSUE TITLE
Project Kickoff: Yellow Ribbon Search - Handle School Abbreviations

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18565]
## Steps to complete Project Kickoff
- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all relevant artifacts to the ticket
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/yellow-ribbon-mvp-product-brief.md
- We will be making updates to the existing Find a Yellow Ribbon School search to handle school abbreviations ~and implement additional filtering at the front end~ to better refine and reduce the number of search results.
- Any other artifacts you have so far
- Review of changes that will need to be made to handle abbreviations are described in this GH Epic: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/16405
- Description of the filtering problem is outlined in this GH issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17940

## Meeting attendees from **Decision Tools Team**
- Product Manager (required): **Marci McGuire**
- DEPO Product Lead (required): **John Hashimoto**
- Entire VFS team (recommended): **Zach Morel, FE Engineer**
- Other specialists: **Laurel Lawrence, Design/Research, Josh Kim, Tze-chui Lei, Selina Cooper or Laura Walsh (Content)**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** NO

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
     - **Friday Jan 22 @ 2:00 PM**
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

**Comment by MarciMcGuireGCIO** [comment]
Updating scope of work to clarify that this does _not_ cover filtering, which is addressed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/18840

**Comment by shiragoodman** [comment]
hi @MarciMcGuireGCIO  - as discussed, we are recommending the following Collaboration Cycle touchpoints:
- Analytics Request
- Privacy and Security Review

For the minor design change you are planning, we'd recommend attending Design Office hours. They are on Tuesdays from 2-3 ET. The zoom info can be found in our [VSP Collaboration Meetings Calendar. ](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York).

The [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) has been updated. Please let me know if you have any questions/concerns. Thanks!

**Comment by tlei123** [comment]
@MarciMcGuireGCIO , once there's an Epic for this work, pls. let me know.  Thx much!

**Comment by joshkimux** [comment]
@MarciMcGuireGCIO Likewise! Please tag me when an epic is prepared!

**Comment by MarciMcGuireGCIO** [comment]
@joshkimux @tlei123 per your request, I'm tagging you since this kickoff is now connected to an epic.

**Comment by MarciMcGuireGCIO** [comment]
Updating title of kickoff to reflect what we talked about.
