### ISSUE TITLE
508-defect-1 ❗ Launchblocker [SEMANTIC MARKUP, COGNITION]: Groups of form elements MUST have group labels (e.g. <fieldset> and <legend>)

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#18568]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader user, I need to know that a range of form inputs are grouped together, so that I may understand the scope of the use case.

## Details

Groups of form elements **MUST** have group labels (e.g. `<fieldset>` and `<legend>`, to meet Section 508 requirements. The current code in the wizard wraps the date fields within a `<div>` with a `<label>` instead of a `<fieldset>` and `<legend>` pairing.

## Acceptance Criteria

- [ ] Change the html as follows, or an alternative standards-compliant manner that programmatically associates the labelling content with the inputs

### Current code

```html
<div>
  <label>
    Date or anticipated date of release from active duty
  </label>
  <!-- Date fields -->
</div>
```

### Recommended code

```html
<fieldset>
  <legend>
    Date or anticipated date of release from active duty
  </legend>
  <!-- Date fields -->
</fieldset>
```

## Environment

* Operating System: all
* Browser: all
* Screenreading device: all
* Server destination: staging

## Steps to Recreate

1. Enter `https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction ` in browser
2. Answer "Yes" to "Currently active duty..." question
3. Start screen reader, and tab to date fields
4. Verify that there isn't a semantic correlation between "Date or anticipated date" and the date fields

### Current code

```html
<div>
  <label>
    Date or anticipated date of release from active duty
  </label>
  <!-- Date fields -->
</div>
```

### Recommended code

```html
<fieldset>
  <legend>
    Date or anticipated date of release from active duty
  </legend>
  <!-- Date fields -->
</fieldset>
```

## WCAG or Vendor Guidance (optional)

* [WCAG 2.0 Level A - 1.3.1 - Info and Relationships: Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

* [Wuhcag 1.3.1 – Info and Relationships (Level A)](https://www.wuhcag.com/info-and-relationships/)

* [WCAG 2.0 Level A - 4.1.1 - Parsing](http://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html)

## Screenshots or Trace Logs
<img width="1656" alt="Screen Shot 2021-01-14 at 10 44 35 AM" src="https://user-images.githubusercontent.com/14154792/104615173-f99e2800-5656-11eb-9211-fa543055d60c.png">
<img width="1299" alt="Screen Shot 2021-01-14 at 10 42 21 AM" src="https://user-images.githubusercontent.com/14154792/104615222-0884da80-5657-11eb-8bef-9db02843777d.png">

**Comment by taylorkaren** [comment]
KT: This is an issue on a specific form, not a Forms Library issue. Removing the forms label.

**Comment by RakshindaAslam** [comment]
cc @christinec-fftc @lydiahooper @RakshindaAslam

**Comment by RakshindaAslam** [comment]
Waiting for this to be closed based on info from @Mottie. cc @joshkimux

**Comment by joshkimux** [comment]
https://user-images.githubusercontent.com/14154792/236014039-3be12c49-e148-4fde-946b-3085adfdcfb2.mov

@Mottie and @RakshindaAslam confirming this has been fixed! Y'all are superstars 🥇
