### ISSUE TITLE
508-defect-1 ❗ [SEMANTIC MARKUP, COGNITION]: Error message MUST be semantically linked and persistent to the year input field

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#18578]
[508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Josh_

## User Story or Problem Statement

As a screen reader user, I want to know if an error exists so that I can correct it.

## Details

Error messaging is currently done using a tooltip which has several issues:
- It's not semantically linked with the input field
- It's not persistent, so if a user tabs off of the field the error will no longer be accessible
- It only activates upon triggering `enter` on the keyboard, since no clear button exists users may become lost on how to progress in the wizard
- It's too small and disappears when the user attempts to zoom in

Edit: It appears this situation only occurs when the user does not select a month prior to attempting the year.

## Acceptance Criteria

- [ ] Error message is handled as documented in [VA design system guidance for form feedback](https://design.va.gov/patterns/form-feedback)

## Environment

* Operating System: any
* Browser: any
* Screenreading device: any
* Server destination: production

## Steps to Recreate

1. Enter `https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction` in browser
2. Select "yes" in wizard
3. Tab to year field and write in "777777"
4. Tab off and confirm no validation is provided
5. Tab back into the year field and key `enter`
6. Confirm a tooltip appears

## Proposed Solution 

Follow design system guidance for form field validation.

## WCAG or Vendor Guidance (optional)

* [The problem with tooltips and what to do instead by Adam Silver](https://adamsilver.io/articles/the-problem-with-tooltips-and-what-to-do-instead/)
* [Tooltips in WCAG 2.1. by Sarah Higley](https://sarahmhigley.com/writing/tooltips-in-wcag-21/)

## Screenshots or Trace Logs

<img width="788" alt="Screen Shot 2021-01-14 at 11 23 05 AM" src="https://user-images.githubusercontent.com/14154792/104622127-dbd4c100-565e-11eb-8949-d18c77a444b8.png">

**Comment by Mottie** [comment]
After some quick investigation, the tooltip you're seeing is built-into the browser when there are min & max attributes. Demo: https://codesandbox.io/s/hungry-dream-3dkx9?file=/src/index.js

I'm not sure if this can be disabled on the browser level, but we might be able to improve the displayed error message when specifically an invalid year is entered.

**Comment by joshkimux** [comment]
@Mottie ideal state, there would be a submit button that could provide feedback to the user which is more of a design problem with the wizard than something that can be remediated right now 😢 

In this case where there isn't an explicit method of receiving feedback, we may have to go with your suggestion of providing an error message when an invalid year is entered.

**Comment by joshkimux** [comment]
@Mottie For a short term fix, would we be able to throw an error on blur for when the user tabs out of the month input field?

**Comment by Mottie** [comment]
I'd have to look. If I recall correctly, the validation isn't run until a full date (all 3 fields are filled) is available

**Comment by Mottie** [comment]
@joshkimux https://github.com/department-of-veterans-affairs/component-library/pull/26

**Comment by joshkimux** [comment]
@Mottie you're the best as always 💯

**Comment by Mottie** [comment]
This fix can be seen in staging now 🎉

**Comment by joshkimux** [comment]
Tooltip no longer appears 🥳 

https://user-images.githubusercontent.com/14154792/107518553-26bdf780-6b7d-11eb-8ac3-013d9c28c857.mov

But-- no validation is provided if a user decides to continue on with just the year filled in. @kevinstachura , is there a possibility users may skip the day/month fields? If so, is there a way we can make it more explicit to the user that these are required without the presence of a submit/continue button? I'm thinking:

- Validation on blur for the day/month fields stating that each are required
- More explicit instructions on the need for a specific date

**Comment by joshkimux** [comment]
I think I brought this up already in the past, but we should also consider making the day input accessible. If a screen reader were to move backwards from year to the day and then to the month, the following issues can occur:
- Upon `shift` + `tab` ing to the "Day" field, JAWS will announce to use the arrow keys to change the selection; however, the field will provide no feedback because it is not active until the "Month" field is completed. 
- A user might then try to type in the date e.g. when typing in 12, JAWS will announce "1, 2." They may _believe_ they've inputed something into the field, when in reality they haven't input anything at all.
- They may then `shift` + `tab` backwards to Month and fill it in. Upon doing so, they will receive no feedback of an announcement.
- They may then tab forwards to the day field again, to hear "Day combobox, to change the selection use the arrow keys" at which point they will finally receive an error.

This interaction isn't as bad on Safari as using the arrow key will implicitly suggest no options are available (see clip below)
https://user-images.githubusercontent.com/14154792/107531410-cd5cc500-6b8a-11eb-9863-1ec2a3990ad6.mov

@1Copenut @Mottie thoughts on this?

**Comment by Mottie** [comment]
I'm still thinking adding an `aria-describedby` to each element will fix the problem.

As for the invalid date screenshot above (year `9999`), this will be fixed in https://github.com/department-of-veterans-affairs/vets-website/pull/15935. What you will see is an error for any date over 100 years in the future and no blue (was grey) box when there is a date error.

**Comment by joshkimux** [comment]
@Mottie ohh, gotcha! Thank you for clarifying 🙇

**Comment by Mottie** [comment]
My PR has been merged. Please let me know if the invalid date error behaves as you'd expect. I can come back to adding the `aria-describedby` to each date field if you think that is the best solution.

**Comment by joshkimux** [comment]
@Mottie Will do, thank you as always! 🥳

**Comment by joshkimux** [comment]
@Mottie I recall seeing in another ticket that @k80bowman and team are prioritizing a new date input field that's text only 👀 
I wonder what our appetite might be to switch this one over to prevent the following issue for screen reader users from happening:

<img width="821" alt="Screen Shot 2022-05-12 at 11 46 15 AM" src="https://user-images.githubusercontent.com/14154792/168115793-01120413-cf88-4d60-afad-85f8c94fa8f7.png">

Given that this is a precise date that folks _should_ have on paper, I think it makes sense to use the open date input field here. 

The main challenge would be that there still isn't an explicit "continue" button as this is still using the old wizard pattern. That will likely made error messaging a bit complicated to solve for 😓 

Would love your thoughts there... maybe we could volunteer to test the check eligibility pattern that the design system team is writing up  👀

**Comment by taylorkaren** [comment]
@joshkimux : I've read your comment for this issue on the [tracking sheet](https://docs.google.com/spreadsheets/d/1M9wfqjLNjecPvwhl8XmJxBJi2CbiOyRS-_9uI3Dn678/edit#gid=0) that "Tooltips were used to provide error messaging in a date select box component within a wizard. It has since been fixed." Since that is fixed, can we close this ticket?

If there is still work to do related to some of the comments on this ticket, please open new ticket(s) for those specific issues.

**Comment by joshkimux** [comment]
Let's close it out!
