### ISSUE TITLE
Front End: Update labels for dependent's info and spouse's information 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#18574]
## Issue Description
_As a Veteran, I would like the field labels under Dependents and Spouse Information to be labeled with their names because it would help reduce confusion when filling out those fields._

## Steps to recreate 

_Spouse labels_ 
- Go to: https://staging.va.gov/health-care/apply/application/introduction
- Under _Martial status_ select: Married ![Screen Shot 2021-01-14 at 10.44.48 AM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/ef7c24f0-bc1c-4d02-9b18-f2f53bfd00e6)
- Select _yes_ for disclosing financial information  
![Screen Shot 2021-01-14 at 10.48.44 AM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/6c816b8f-351d-455e-bad2-f82c1f259072)
- Update the labels under _Spouse's information_ 

_Dependent labels_

- Select _yes_ for _dependent information_ 

![Screen Shot 2021-01-14 at 11.08.15 AM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/6cd9c140-ab2a-48b2-aecb-9a0d771fd488)

- Update _Dependent's labels_

See attached [mockups and documentation](https://preview.uxpin.com/903944290fe90e22d55c50f5c986d954a637cf6d#/pages/135618577)

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
For awareness: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18168

**Comment by LinnJS** [comment]
Link to [designs](https://preview.uxpin.com/903944290fe90e22d55c50f5c986d954a637cf6d#/pages/135618577)

**Comment by LinnJS** [comment]
Link to [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15766)

**Comment by LinnJS** [comment]
Added work to this ticket so all address field labels show "Street address" instead of "Street"

![Screen Shot 2021-01-20 at 4.52.34 PM.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/cb8f6d1a-b550-4ca9-b7ba-5d4b9c4639ca)

**Comment by jonathanjnelson** [comment]
Please update content for two fields: ![Artboard.jpg](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/a81b8fac-f3b4-4891-a32c-bd9c07bcdb30)
