### ISSUE TITLE
Chrome bug:  Yellow line showing on some RS pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#18570]
## What happened?
_On Chrome, on 2 RS pages (listed below), there is a weird yellow line that spans the full width of the screen. This line is not part of the design. I've checked other pages and didn't see them affected. However, even on the 2 reported pages below, I noticed that sometimes the line shows and sometimes doesn't. But if leave and come back a few times, it will appear again. So it appears to be a bug that appears occasionally rather than persistently._

## Severity: 
Low/minor

## Specs:
- Device: HP pc
- Browser: Chrome

## Steps to Reproduce
- URL: https://www.va.gov/resources/what-your-claim-status-means/
- URL: https://www.va.gov/resources/tag/claims-and-appeals-status/

## Screenshots - Please ignore IE note - it's actually on Chrome

1. 
![image](https://user-images.githubusercontent.com/43381063/104614935-b5ab2300-5656-11eb-8aaf-93c3e5251771.png)

2.
![image](https://user-images.githubusercontent.com/43381063/104615072-dbd0c300-5656-11eb-935e-0e95bde3876d.png)

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [x] _Weird yellow line is not showing_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jenniferlee-dsva** [comment]
Please ignore the IE note on the screenshots. These are actually showing on Chrome. (I checked in Firefox and IE, and they're not showing there. Though not sure if that's bc this is unique to Chrome or bc this is a bug that plays hide and seek and only shows some of the time.)

**Comment by brianalloyd** [comment]
Thanks @jenniferlee-dsva, appreciate the details on this, super helpful.

**Comment by brianalloyd** [comment]
Validated solution, fixes site wide, closing ticket in support.
