### ISSUE TITLE
vtk feedback: Docker support for vtk

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#18576]
ensure vtk commands can be run from docker bash

add vtk install to dockerfile

**Comment by erluti** [comment]
At one point we had discussed maybe setting up a `make vtk` entry in the makefile.  Was there a separate ticket for that?

**Comment by alexpappasoddball** [comment]
Have we updated the readme or changelog to bump the version and note the addition of docker support and what that means for the toolkit?

**Comment by thilton-oddball** [comment]
Yes, I added that in yesterday.
