### ISSUE TITLE
Create feature toggle record

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18575]
## Item Description
Document all existing feature flags to use as a record/change log.

- Add file to va.gov-team/products/health-care/appointments/va-online-scheduling/product/ in GH

- Include a table with the following headers: Toggle Name, Description, Ticket to Add, Related Epic, Ticket to Remove, Comments

- Complete the Toggle Name and Description Field

- If visible in the code, complete the Ticket to Add field

_Lauren will find/add the rest of the info_

**Comment by jbalboni** [comment]
This is the backend feature flag definitions, the source of truth for what flags exist: https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml

**Comment by jbalboni** [comment]
Created: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md

**Comment by laurenernest** [comment]
Thank you for that source of truth link! Closing ticket.
