### ISSUE TITLE
Open camera and take photo

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18599]
## User story
As a user, I want the ability to take photos from my device and upload them to my VA claim. 

## Acceptance Criteria
1. The **Take photos** large button from the Take Photos page opens the device's action sheet*:
     - A user can choose from their: 1) camera (pulled from the react-native-image-picker library), 2) camera roll, 3) cancel https://www.npmjs.com/package/@expo/react-native-action-sheet
2. User has the ability to close out the camera and return to the Take Photos page (either by Confirming a photo or canceling the flow - see notes below)

Note: 
1. The camera controls should include:
     - Take photo
     - Retake
     - Confirm / Save  
2. There will need to be a filter on file size/types _(Q: where does this filter need to be implemented? Camera or File Upload page?)_. 
     - Max file size: 50 MB
     - Accepted file types: pdf (unlocked), gif, jpeg, jpg, bmp, txt

## Designs
N/A

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/26/2021 on both Android and iOS.  Took a little figuring out because I wasn't familiar with the choices, but it passes.
