### ISSUE TITLE
Validate scalability of CMS Export before release

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18592]
## Details 

The current CMS build pipeline, using GraphQL, is not able to scale to support publishing the new VAMC sites. Megan will provide info from Stan G. & Dave C. about the expected timeline & rate of publishing for the new VAMC sites.

We hypothesize that using CMS Export instead of GraphQL will allow the CMS to scale to support publishing of the new VAMC sites. 

This ticket represents discovery to validate that hypothesis as much as possible before release. 

Potential questions to look into: 
* What is currently the limitation preventing scalability of the CMS? Will this limitation be entirely removed when we switch from GraphQL -> CMS Export? 
* Conversations on this topic often include discussion of "the CMS side" and "the build pipeline side" or "the VSP side" — where are the scalability limitations, exactly, how do they depend on one another, etc. (AKA — understand all possible bottlenecks and how they interact) 
* Profile memory used during build
   * VFS teams have raised issues about running out of memory ([Slack thread](https://dsva.slack.com/archives/C5HP4GN3F/p1610379137294200)) and said that this will not be improved by the switch to CMS Export — is this relevant? Is this one of our bottlenecks? 
* Can we run any tests to validate the scalability before release of CMS Export? 
* Once we release CMS Export, what guidance should we give VFS teams on timing of publishing the new VAMC sites? 
   * Does our guidance change based on our confidence in the scalability? 

## Acceptance Criteria
- [x] Findings on above questions & related discoveries have been written up (likely should be stored in Confluence) & shared with team 
- [x] Discuss findings at a cross-team CMS Export engineering sync (make sure we've covered all possible bases)

**Comment by meganhkelley** [comment]
Average = 400-500 nodes per system
Typically, these are distributed across approximately 40-50 pages 
These numbers account for the initial release — as soon as a system is published, VA stakeholders are given access to edit the content on that system, and nodes and pages will increase thereafter (at a rate of between 20-30 new pages over the first month after the system is published)

Goal by end of 2021 = publishing 142 systems
Goal by end of Q1 2021 = publishing 33 systems 

VAMC team wants to scale up to publishing 10 systems/sprint 

For end of Q1 2021, "publishing" means entering "dual-state" — this is a term that VSA VAMC team uses to mean that the legacy site, which uses the legacy Teamsite CMS, is still active & receiving public traffic. For our scalability conversations, "dual state" means published. The only difference between "dual state" and what the VAMC team calls "go live" is the amount of public traffic being directed to the URL.

Also needing to publish soon: 10 vet centers in Q1, each vet center will have 2 pages (unknown number of nodes). Goal is to scale out over the next 3 months — Q2 will publish the remaining 290 vet centers
Changes to content model to account for vet centers will be coming in Q1, owned by VSA Facilities team

**Comment by meganhkelley** [comment]
The folks about when investigating technical bottlenecks are the CMS team — Steve and Neil to start with, probably. They'll know what the existing bottlenecks are and how they've been handled thus far.

**Comment by meganhkelley** [comment]
@k80bowman @timwright12 could y'all please estimate this ticket before you move it to In Progress? Thanks!

**Comment by timwright12** [comment]
Gathering metrics here: https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=0

**Comment by k80bowman** [comment]
Documenting answers to the questions above here: https://docs.google.com/document/d/1wZCO0cuVb-tE2UUUXtlN8WvoAD3HA-ytfWY_SbU4TfQ/edit?usp=sharing

**Comment by meganhkelley** [comment]
Metalsmith issue ticket: https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/19232

**Comment by timwright12** [comment]
@meganhkelley The scalability findings are complete in the spreadsheet https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=0
