### ISSUE TITLE
Select a file page | No files added

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18596]
## User story
As a user, I want the ability to select files from my device and upload them to my VA claim. 

Dev note: 
- The UI for the **Select a file** page will have 3 variations. This ticket is for the first variation, when no files have been uploaded to the page.
- The designs display the flow for the **Photo Upload** flow. The **Select a File** flow is virtually identical, except for several copy changes. These copy changes will be detailed in the AC below.

## Acceptance Criteria
1. Selecting the **Select a file** large button from the File upload request list routes to a new page
     - Page header: File upload
2. Header 2 includes copy that will be partially data-driven
     - Copy: Select a file to upload for [Request Title Goes Here] _(note this copy change from designs)_
3. Copy below Header 2 is hard-coded:
     - Copy: Please select a file from your phone's files. _(note this copy change from designs)_
4. "Select a file" large button (UI only) _(note this copy change from designs)_

## Designs
https://camo.githubusercontent.com/9d4586de2d1b460b3f49619392b881cff71b5f0e9dcb226505e6957b3320b77d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f35663233313062392d633166392d346661612d396630302d333838393536313065326131
![Screen Shot 2021-01-14 at 10.15.31 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e12842eb-6fa7-4653-95cf-bce084abaf64)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Cancel button in top left
     - Use general done button a11y
- Mark "File upload" as Header 1
- Mark "Select a file to upload for [Request Title Goes Here]" as Header 2

**Select a file button**
- Title= "Select a file"
- accessibilityHint= “Select a file from your device” 
- accessibilityRole= “button”

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/27/2021 - both UI and accessibility but added this to the existing bug on the keyboard access previous page.
