### ISSUE TITLE
Add Google Analytics Tracking for New Link Added to English Corona FAQ page (post 1/19 Staging Review)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#18597]
## User Story 1: 

_As a PM I would like to have GA tracking for the new link being added to the english version of the Corona FAQ page (which takes a user to the spanish version of the Corona FAQ page) so that I can track and measure CTR. 

## Expected Behavior

_I can run reporting on click data for the new link via GA reporting or through DOMO.

## Acceptance Criteria

- [ ] _Confirmation that page is sending data to GA

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - this was the ticket you said was in place now, correct? If so I will close out...thanks,

Sharon

**Comment by youngfreezyVA** [comment]
yup!
