### ISSUE TITLE
Loading screen for saving Profile information

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18598]
## User story
As a user, I want to know that my Profile information - including address, email, and phone number - is saving.

## Acceptance Criteria
1. Create 3 loading screens for when a user hits "Save" on the following edit pages:
     - Address (Mailing, Home)
     - Phone (Home, Work, Cell, Fax)
     - Email 
2. Pull in the LoadingComponent common component 
3. This screen appears until the information is validated and is ready to display on the Personal Information summary page
4. Copy for each:
     - Address: "We are saving your address."
     - Phone: "We are saving your phone number."
     - Email: "We are saving your email address."

## Designs
N/A for these scenarios. Here is a similar design for the Direct Deposit loading screen: 
![Image from iOS (14).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/691988a2-6300-4a1a-9b8f-2220db250cb9)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/20/2021 - Saving screen present for address, phone, email and banking.
