### ISSUE TITLE
508-defect-2 [COGNITION]: Direct Deposit Component - Save button must have an accessible label

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#18606]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a screen reader user, I would like to hear an accessible label read aloud so I know what I'm saving in the direct deposit edit in place.

## Details

Our primary save button needs an `aria-label` or a more descriptive visible label so all users understand they're saving direct deposit information. Some users might have to navigate back through the form or listen to the heading a second time to understand the relationship as the UI stands now.

## Acceptance Criteria

- [ ] Save button has either an `aria-label` or a more descriptive visual label
- [ ] Label should say "Save direct deposit information" or something similar

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2021-01-14 at 2 26 54 PM](https://user-images.githubusercontent.com/934879/104651828-d0dd5900-567d-11eb-8da3-1f7a495a8d7a.png)

**Comment by caw310** [comment]
@cvalarida , if you have time in the next sprint, please take a look at this one.

**Comment by k80bowman** [comment]
This looks like a forms system issue. We will need to do a little digging to find a page where this button exists and then test it to make sure the issue is still valid before attempting a fix.

Once the work is complete, please work with @CourtneyChambers77 to verify that the issue is resolved.

**Comment by pdavies88** [comment]
@CourtneyChambers77 please test by going to this link and logging in to see the form and scroll down to direct deposit information: https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply

**Comment by CourtneyChambers77** [comment]
@Preston, I have evaluated the save button - Save button must have an accessible label #18606 I have tested with Accessibility tool and it reads with JAWS 21
<img width="473" alt="image" src="https://user-images.githubusercontent.com/95867638/149036481-9083812c-e265-43e5-a155-f0cf5aca7722.png">

**Comment by preston** [comment]
I think you have the wrong "preston". I no longer work for VA.
