### ISSUE TITLE
Quality Assurance Feedback - Usability Testing Prep - VAOS Homepage Refresh

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18601]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Are there portions of the homepage for which you already have test cases that you can reuse / recycle for this effort?
- There appear to be about [5 regression tests defined](https://dsvavsp.testrail.io/index.php?/suites/view/21&group_by=cases:section_id&group_order=asc&group_id=115). Will these be applicable for this effort?
- Are you planning to refactor the existing VAOS E2E tests to reflect the refresh, or will you be re-writing E2E from scratch?
- You have a great collection of stubbed out test cases here -- good job!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
As you move forward with formally defining the product based on user feedback, please provide traceability for test cases by using the `References` field in the test case to refer to the story or use case where you define the relevant acceptance criteria or requirements.

**Should:**

**Consider:**

**Comment by laurenernest** [comment]
@pjhill Thanks for these notes!

> Are there portions of the homepage for which you already have test cases that you can reuse / recycle for this effort?

- Basically everything under the Appointment list folder can be reused, or used without modification.    

> There appear to be about 5 regression tests defined. Will these be applicable for this effort?
- It looks like 3 of them could be used/updated as it relates to this effort (MVP)

> Are you planning to refactor the existing VAOS E2E tests to reflect the refresh, or will you be re-writing E2E from scratch?
- I'll leave that decision to our QA support, but do you have a recommendation? This work work will only cover one page/step in the greater flow.

**Comment by pjhill** [comment]
> * Basically everything under the Appointment list folder can be reused, or used without modification.
>
Terrific, if they are all still relevant then I recommend incorporating as many of them as you think would be attainable for your team's QA resources. Reusing tests is one of the core benefits from using test management software, so I encourage you to leverage that!

> * It looks like 3 of them could be used/updated as it relates to this effort (MVP)
> 
Sounds good!

> * I'll leave that decision to our QA support, but do you have a recommendation? This work work will only cover one page/step in the greater flow.
>
I would recommend working with the existing e2e test given that you are changing a small subset of the overall flow.
