### ISSUE TITLE
Document different Auth Approaches (ID.me vs GitHub)

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#18600]
## Description

Sidekiq (the job queuing tool used on the platform) was previously exposed to the public in the Dev/Staging/Sandbox environments and were restricted once a security vulnerability was discovered.  There are other tools that were identified as being a risk and had Auth put in front of them (Pact broker) at about the same time.  In order to expose these, and future tools, to developers we need a robust, easy way to add authentication to an application.

Our previous user management tool was GitHub teams.  There is also ID.me available to use leveraging a whitelist of email address.

We need to investigate GitHub and ID.me through a pros vs cons list of each to determine if either of these, or a combination of them, would be a suitable solution to apply auth to tools identified as having vulnerabilities, and future tools that we decide to deploy for use by developers.

## Outstanding questions
- Who is going to manage access and updating the appropriate user list for whatever approach we take

## Definition of Done
- [ ] A Pro's vs Con's list is documented and available for review
- [ ] A proposed solution is documented and sent for review from Engineering Lead & DEPO Lead & Ops Team & FE Tools Team for review.

**Comment by alexpappasoddball** [comment]
One thought that Philip and I were talking about is looking into if ID.me could leverage a GitHub team as its white list.  That would allow anyone with an ID.me account to be added to our already established user management tool (GitHub teams).

**Comment by alexpappasoddball** [comment]
@erluti Take a look at this and edit as you see necessary!

**Comment by erluti** [comment]
> One thought that Philip and I were talking about is looking into if ID.me could leverage a GitHub team as its white list. That would allow anyone with an ID.me account to be added to our already established user management tool (GitHub teams).

I was trying too say that vets-api could hook into Github to use a team as a whitelist.  A feature like this could also be used to manage the flipper whitelist.

**Comment by erluti** [comment]
Using github teams as whitelist is possible, just maybe not straightforward.  [Documentation for getting a list of a teams member is here](https://docs.github.com/en/rest/reference/teams#list-team-members).  The team members come back by github username, but that's not something ID.me knows.  So then we'd have to look [up all the users on that list individually](https://docs.github.com/en/rest/reference/users#get-a-user) and see if one of them has the email that matches their ID.me login.  This would mean they would have to have a github email that's also used for their ID.me sign up for this to work.  We could store/cache user lookup results so this wouldn't necessarily be a huge process for each login, but it would add an esoteric requirement to their ID.me login.

**Comment by jeff2d2** [comment]
Closing as #22354 is a replacement.
