### ISSUE TITLE
Take photos page | with photo(s) added

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18603]
## User story
As a user, I want the ability to view the photos I've uploaded with the option to upload more. 

Dev note: 
- The UI for the **Take photos** page will have 3 variations. This ticket is for the second and third variations:
     - Variation 2: when 1-9 photos have been uploaded to the page
     - Variation 3: when 10 photos have been uploaded to the page

## Acceptance Criteria
1. Confirming a photo from the camera will return the user to the **File upload** page
2. Update Header 2 to display the [Request Title] (omit the hard-coded copy from the "no photos" screen)
3. Display a preview of the selected photo on this page
4. When there are multiple photos:
     - Stack photo previews in a row from left-to-right, where the first confirmed photo will retain the top left position
5. Create two large buttons:
     - Upload (UI only)
     - **Add another photo** - Selecting this button re-opens the camera and allows the user to continue taking/adding photos
6. When 10 photos have been added to the page, hide the **Add another photo** button
     - Only the **Upload** button should display
7. If a user tries to add a photo that exceeds the file limit (50 MB) or does not meet the requirements for format (pdf (unlocked), gif, jpeg, jpg, bmp, txt), display an error message (no designs - add copy as needed)

## Designs
https://camo.githubusercontent.com/9d4586de2d1b460b3f49619392b881cff71b5f0e9dcb226505e6957b3320b77d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f35663233313062392d633166392d346661612d396630302d333838393536313065326131
**1-9 photos:** 
![Screen Shot 2021-01-14 at 1.16.31 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/35e468cd-8ab0-479e-bd56-d960875d5a93)
**10 photos:**
![Screen Shot 2021-01-14 at 1.41.33 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d1f75e40-4068-41bd-9c35-15a5b0751ee7)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Cancel button in top left
     - Use general done button a11y
- Mark "File upload" as Header 1
- Mark "[Request Title]" as Header 2

**Photos**
- accessibilityRole= image (this should be marked for each uploaded photo)

**Upload button**
- Title= "Upload"
- accessibilityHint= “Upload your photos to your claim” 
- accessibilityRole= “button”

**Add another photo button**
- Title= "Add another photo"
- accessibilityHint= “Add another photo using your device's camera” 
- accessibilityRole= “button”

**Comment by digitalken** [comment]
PASS 1/27/2021 - both UI and Accessibility, Android and iOS.
