### ISSUE TITLE
CT: Research functionality prior to introduction of VACautionFlag file

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18619]
As a developer, I need to research how the data was consumed prior to the introduction of the VACautionFlag file so that I can determine how to make an update to the system.

## Assumptions:
1. The following CSVs data files were replaced by the VACautionFlag file:
    a. Settlement
    b. SchoolClosure
    c. Sec702School

## Acceptance Criteria
1. How the Settlement file data was mapped to OPEId/Facility code is documented.
2. How the SchoolClosure file data was mapped to OPEId/Facility code is documented.
3. How the Sec702School file data was mapped to OPEId/Facility code is documented.

## Supporting Artifacts:
1. Original Epic #10150
2. Original Research Story #10440

**Comment by zurbergram** [comment]
Previously `ope6` was included in the SQL statements for the following caution flags
- accreditation
- mou
- hcm

`ope6` is generated on weams upload by taking middle 6 digits of `ope` value
ex. ope is `01234567` and ope6 is then `123456`

**Comment by zurbergram** [comment]
Original work was in https://github.com/department-of-veterans-affairs/gibct-data-service/pull/612

**Comment by zurbergram** [comment]
https://ope.ed.gov/dapip/
From https://www.dodmou.com/Home/EnterOpeidBeforeCreateUserAccount
> The Office of Postsecondary Education Identification (OPE ID) number is assigned by the U.S. Department of Education to identify schools that have Program Participation Agreements (PPA) so that its students are eligible to participate in Federal Student Financial Assistance programs under Title IV regulations. The first 6-digits of the OPE ID number relate to the education institution, and are followed by a 2-digit suffix used to identify branches, additional locations, and other entities that are part of the eligible educational institution.

**Comment by zurbergram** [comment]
Settlement caution flags were associated by IPEDs id previously from the settlements file.

Sec702 was associated by facility code in Sec702Schools file or state in the Sec702 file (currently still checks this file if no value provided in VaCautionFlag file).

School Closure is associated by facility code.

**Comment by zurbergram** [comment]
For settlement file multiple institutions share the same IPEDs id value
![image](https://user-images.githubusercontent.com/1094999/105538379-4f12ae80-5cc1-11eb-9fa0-b8dee3e8d4b3.png)

Example
![image](https://user-images.githubusercontent.com/1094999/105538395-55a12600-5cc1-11eb-819b-20b7764a9ec0.png)
