### ISSUE TITLE
Edit fields are not easily selectable

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18618]
## What happened?

On both Android and iOS, the edit fields (such as Line 2 & 3 on Edit Address) are not easily selectable - especially on iOS. For some fields, I need to tap in a specific spot in order for it to be selected. 

## Specs:
- Device: Samsung Galaxy 9
- Device: iPhone 11

## Steps to Reproduce

1. Navigate to the Edit Address page
2. On iOS, try to tap the Street Address fields (Line 1, 2, 3) on the right half of the screen. Do the same for City and Zip.
     -  Notice how the fields aren't selected - only when you tap closer to the left side of the screen are they selectable. 
     -  Country and State, which are dropdown, appears to be easier to select
3. On Android, Line 2 & 3 of Address are also difficult to select. 

## Desired behavior
An edit field should be selectable by tapping anywhere on the field. 

## Acceptance Criteria
See Desired Behavior

## Bug Severity
- 3 - Medium

**Comment by digitalken** [comment]
PASS 1/22/2021 - Easily selectable to the right of the field labels.  Closing.
