### ISSUE TITLE
Upload photos & files to claim w/ success message

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18612]
## User story
As a user, I want to see a success message when I've upload my photos/files to VA and see a success message. 

Note: the same success message appears for both Photo upload & File upload. 

## Acceptance Criteria
1. Upon hitting "Upload" on the File Upload or Photo Upload page, all of the uploaded files/photos should be aggregated into 1 file that is sent to VA
     - Note: review aggregating requirement w/ Patrick to understand technical approach
2. Filter on file size/types:
     - Max file size: 50 MB
     - Accepted file types: pdf (unlocked), gif, jpeg, jpg, bmp, txt
3. Upon a successful upload, the screen will be replaced to display a success message
4. Back button
     - Routes to the File Request overview page (this page: https://adhoc.invisionapp.com/d/#/console/20546460/432623517/preview)
5. Pull in mobile alert CC:
     - Style & UI match designs
6. "View all file requests" large button 
     - Also routes to the File Request page 

## Designs
https://camo.githubusercontent.com/9d4586de2d1b460b3f49619392b881cff71b5f0e9dcb226505e6957b3320b77d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f35663233313062392d633166392d346661612d396630302d333838393536313065326131
![Screen Shot 2021-01-14 at 2.54.30 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4b5598d1-696c-4519-b95e-6c56b60898af)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Back button in top left (custom a11y)
     - accessibilityLabel = "back"
     - accessibilityHint= “Navigates to the file request page”
     - accessibilityRole = “button”
- Mark "File upload" as Header 1
- Mark "Your file was uploaded" as Header 2

**View all file requests button**
- Title= "View all file requests"
- accessibilityHint= “View all file requests and return to the file request page” 
- accessibilityRole= “button”

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/27/2021 - Both UI and accessibility, Android and iOS.
