### ISSUE TITLE
Android - dropdown text is smaller than non-dropdown text

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18615]
## What happened?
Android: The text in the dropdown fields is smaller than the text in non-dropdown fields. 

## Specs:
- Device: Samsung Galaxy 9

## Steps to Reproduce
1. Navigate to the Edit Address page on Android (there are similar issues with Edit Phone, Edit Email, and Edit Direct Deposit). 
2. Observe the smaller font for the dropdown fields: Country, State, APO/FPO/DPO

## Desired behavior
Font in all dropdown fields should be the same size

## Acceptance Criteria
See Desired Behavior

## Bug Severity
- 3 - Medium

## Screen shot(s) and additional information

![Screenshot_20210114-153331_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/eadf0aae-5e42-478e-a5dc-363859624e37)

**Comment by bessgreen** [comment]
This issue is a result of using the default Android styles for the dropdown fields. A decision was made to use the default styles because they allow the dropdowns to be accessible while using TalkBack. As we don't have control over the native styles, we will not be able to adjust the dropdown font sizes. 

Potential options:

1. Reduce the font size of the other fields so they match the font sizes of the dropdowns
2. Revert back to the custom Android style for dropdowns. This will make the dropdowns non-accessible while using Talkback.
3. Investigate options for creating our own library where we have control over the font sizes _and_ its accessible.

**Comment by lexicalninja** [comment]
adding the useNativeAndroidPickerStyle: false to the props fixes the font, but there is a bug in the library for this that makes the chevron disappear. There is also an issue of padding that causes stacked inputs to be slightly off

![image](https://user-images.githubusercontent.com/7376126/105229007-eabce700-5b28-11eb-92f8-ff3c9431e96e.png)

see https://github.com/lawnstarter/react-native-picker-select/issues/364

**Comment by bessgreen** [comment]
@lexicalninja we were originally using the useNativeAndroidPickerStyle, but we removed it because it created issues with accessibility (we were unable to open the picker using voice access). 

cc: @komaly15

**Comment by lexicalninja** [comment]
OK, we will need to do number 2 or number 3. Its not just the font size, but the fonts are different as well. It does not seem to be picking up the font-family in android either. We can start to look at what is going on in the picker and build out our own in a future sprint before app store release. Number 2 is probably the best way to maintain a11y even though it might look off for a bit. 

I am open to any suggestions

**Comment by bessgreen** [comment]
Logging some additional UI implications that will occur with the Profile 2.0/field error changes. On Android, there isn't a way to tell if the picker is open or closed, which means:

1. When the picker is open, the focused state (i.e. the thicker blue border) will not appear on the dropdown field
2. When the picker is has been opened/closed with no selection made, the field error will not appear on the dropdown field
     - However, if no selection is made in the dropdown, the field error will appear upon hitting "Save"


If we ultimately create a custom picker for MVP, we can revisit these UX/UI requirements in addition to the a11y requirements described above.

**Comment by bessgreen** [comment]
Blocked: will likely require a custom implementation. Custom Picker: #21131

**Comment by digitalken** [comment]
CLOSING 4/30/2021 - No longer a valid bug because placeholder text is now removed for spin counter type drop downs.
