### ISSUE TITLE
Drop-downs with longer hints are cutoff by arrow (Android)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18617]
## What happened?

On Android: drop-downs with longer hints are cutoff by the native dropdown arrow. This occurs on the following pages:
     - Direct Deposit edit screen
     - Edit Address (military)

## Specs:
- Device: Samsung Galaxy 9

## Steps to Reproduce
1. On the Edit Address page, check the "Military Address" box so that the APO/FPO/DPO picker is in view. Notice how the hint text is cutoff, and the dropdown arrow is not right-aligned like the other picker arrows for Country and State
2. On the Direct Deposit edit page, observe similar behavior for the Account Type field. 

## Desired behavior
1. The dropdown arrow should be right-aligned on all fields
2. The hint text should not be cut off unless it is encroaching on the right-aligned arrow. In this case, ellipses can be used.

## Acceptance Criteria
See desired behavior

## Bug severity
- 4 - Low

## Screen shot(s) and additional information
![Screenshot_20210114-161047_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/73f63255-cb22-4bfa-b2b1-f1d5d04ff414)

**Comment by digitalken** [comment]
FAIL 1/21/2021 - The drop down arrow on the Address entry page is not right aligned.  Hint texts are good, however.  Sending back for rework.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/ba5a630f-97b1-4c71-a9d1-8e420e708808)

**Comment by digitalken** [comment]
@komaly15 - placed this back into "in progress" for you.  -Ken

**Comment by digitalken** [comment]
PASS 1/22/2021 - Corrections have been made, text doesn't get cut off and arrow alignment is good.
