### ISSUE TITLE
STEM AD: Update handling of EVSS data retrieval

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18622]
As a developer, I need to update the way data is retrieved from EVSS in support of the automated decision so that an error does not happen when the user has logged out.

## Assumptions:
1. This story is completed behind feature flag `stem_automated_decision`.

## Acceptance Criteria:
1. The EVSS entitlement data can be retrieved after the user has logged out of va.gov.
2. The EVSS entitlement data can be retrieved after the user object has been purged from cache (1 hour after submission).

### Technical Notes:
1. Use encrypted auth_header column in ATD table and store after submission, then pull from table and connect to evss.
2. Update initalize in https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/service.rb to accept a user object or headers.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/5794
- https://github.com/department-of-veterans-affairs/vets-api/pull/5793

**Comment by delli-gatti-michael** [comment]
V-EBC-8412 submitted 2/8/21 should show as denied on the 10203 submission report generated on the morning of 2/9/21

**Comment by dmccurdybah** [comment]
Null check PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5895

**Comment by dmccurdybah** [comment]
Additional null check PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5927

**Comment by delli-gatti-michael** [comment]
Submissions from 2/18 are shown as expected on the 10203 SSR generated the morning of 2/19. Closing this issue.
