### ISSUE TITLE
Initialize Users in VA Profile

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#18624]
In the use case of a use being LOA3 but not being in VA Profile, the web Profile initializes the user into VA Profile using the /v0/profile/initialize_vet360_id API. Post MVP, we want to also be able to initialize users. This ticket is so we don't lose track of doing that work and can come back and write clear FE and BE tickets later. cc @ayushchak 

Context from VA.gov profile team: https://dsva.slack.com/archives/C909ZG2BB/p1610052966381700

**Comment by patrickvinograd** [comment]
Is this not already addressed via the code in https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/mobile/app/services/mobile/v0/profile/sync_update_service.rb#L53

@kreek ?

**Comment by lexicalninja** [comment]
@kreek @patrickvinograd is this ticket good to close or do we need work on the backend?

**Comment by kreek** [comment]
We can close it, on login we check if a user has a Vet360 id and if not create one for them in the code @patrickvinograd noted above.
