### ISSUE TITLE
Review instances of `{strict: false}` on schema validation across VAOS

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#18625]
Several request specs have their schema validation check configured with `strict` set to false, this ticket is to:
1.  Understand why those were included in the first place.
2.  Update tests/schemas to reflect and accurately validate response bodies being returned to vets-website.

**Comment by ajmagdub** [comment]
Looks like the use of the <code>strict: false</code> is as it is currently being used in vets-api's tests is correct. 

The schema validations use the JSON::Validator.validate method. With the <code>JSON::Validator.validate</code> method if <code>strict:</code> were true then that would mean all properties are considered to have '"required": true' (have to be present) which is not what is wanted. With <code>strict: false</code> only properties that the schema explicitly indicates are required have to be present.
