### ISSUE TITLE
Select a file page | with file added

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18635]
## User story
As a user, I want the ability to select files from my device and upload them to my VA claim. 

Dev note: 
- The UI for the **Select a file** page will have 2 variations. This ticket is for the second variation:
     - Variation 2: when 1 file has have been uploaded to the page
- The designs display the flow for the **Photo Upload** flow. The **Select a File** flow is virtually identical, except for several copy changes. These copy changes will be detailed in the AC below.
- Similar ticket for Photo Upload page: [#18603](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18603
)

## Acceptance Criteria
1. Confirming a file from the file picker will return the user to the **File upload** page
2. Update Header 2 to display the [Request Title] (omit the hard-coded copy from the "no files" screen)
3. Display a "preview" of the selected file on this page. This preview will contain the file name, rather than an image preview
4. Create one large button:
     - Upload (UI only)
5. A user should not be able to add/upload more than one file

## Designs
https://camo.githubusercontent.com/9d4586de2d1b460b3f49619392b881cff71b5f0e9dcb226505e6957b3320b77d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f35663233313062392d633166392d346661612d396630302d333838393536313065326131
![Screen Shot 2021-01-14 at 1.41.33 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d1f75e40-4068-41bd-9c35-15a5b0751ee7)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
- Cancel button in top left
     - Use general done button a11y
- Mark "File upload" as Header 1
- Mark "[Request Title]" as Header 2

**Upload button**
- Title= "Upload"
- accessibilityHint= “Upload your files to your claim” 
- accessibilityRole= “button”

**Comment by bessgreen** [comment]
Next steps: review requirements w/ AH:
- Number of possible files to add? 
- Aggregating multiple file types? (ex: .pdf + .jpg?)

**Comment by bessgreen** [comment]
1. Limit to uploading 1 file, or 1-10 photos
2. File aggregation for photos: ideally, multiple photos will be compiled into a single, multi-page doc. Separate ticket for investigation spike: 
3. File "image preview" - display file name instead of an image.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/28/2021 - both Android and iOS.
