### ISSUE TITLE
Automate Credential Scanning

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18636]
## Issue Description
In order to keep our data secure when we provision access within the VA, we need an easy and reliable way to track potential data leaks to our public repository. How might we automate credential scanning during the PR process so that it doesn't make it into a public branch?

---
## Tasks
- [ ] Automate credential scanning during the PR process

## Acceptance Criteria
- [ ] We have an automated way to ensure that our data doesn't leak into public repos.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @michelle-dooley, we're doing an audit of our backlog and came across [this epic](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/17339).

Are you able to confirm if this task was completed?
