### ISSUE TITLE
DebtRes FSR VSA-QA Test Plan

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#18643]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- [Product/Feature Outline:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/FSR-Product-Outline.md)
- [Product/Feature Super-Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14439)
- Product/Feature Copy deck(s): Design Prototypes
- [Product/Feature Design prototypes](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701647/simulate/sitemap?mode=i):

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: 
Content/IA: Mikki 
Front-end: Craig, Brad
Back-end: Cameron
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases 

1-Veteran does not have any VA benefits to prefill the FSR form
vets.gov.user+42@gmail.com (Russell)

2-Veteran has VA benefits to prefill the FSR form
vets.gov.user+228@gmail.com (Colder)

3-Veteran has one debt
vets.gov.user+14@gmail.com (Jerry)

4-Veteran has multiple debts
vets.gov.user+1@gmail.com (Greg)

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: \[provide link]

## How to configure this issue

- [ ] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Product references provided by Product Team.
- [ ] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 2 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@leahkeeler , all QA test-runs now completed.  QA-artifact links are below, and will also be updated into our Staging Review ticket #21206:

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1263)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/8&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=881)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/208)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/209)

Defects logged: 
- Closed: #21080, #21190, #21202, #21229, #21272, #21343, #21396, #21400
- Open: #21241, #22349, #22355, #22615, #22618

**Comment by tlei123** [comment]
Closing this ticket:
- QA follow-up to be tracked in QA-feedback #22929
- QA-logged open-bugs-query: https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+is%3Aissue+label%3Abug+author%3Atlei123+in%3Atitle+financial+status+report [conduct another test-run once this list is empty]
