### ISSUE TITLE
Transfer Medallia Knowledge to VSP Contact Center

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#18646]
## Issue Description
As the VSP Contact Center team is rolling out the Medallia pilot, how can VSP Analytics & Insights share pertinent and historical information so they can roll out as smoothly as possible? This ticket is to track those conversations.

---
## Tasks
- [ ] Add relevant Medallia information as needed so that VSP Contact Center has what they need to roll out Medallia

## Acceptance Criteria
- [ ] Medallia pilot is successfully released

**Comment by joanneesteban** [comment]
## ForeSee Information & Ownership

I think it would make sense for ownership of ForeSee to transfer over as well. 

- I go into ForeSee weekly, but that’s just to manually update our data in Domo & will plan to do a data dump into BigQuery before the surveys in ForeSee are deprecated.
- ForeSee ownership has been pretty simple. We can only make edits to the Feedback survey. Everything else goes through ForeSee, which really just means emailing Jon Cioffi.
- To get access to the ForeSee web app, you need to email Jon Cioffi with the emails. Jeff Barnes stated that access should only be granted to those with VA.gov emails.
- In the ForeSee web app, you can make edits to the Feedback survey, including adding and removing URLs from the Feedback survey. This is a super low effort task. I can share how you can do this on your own.

**Comment by joanneesteban** [comment]
## Piloting the A11/Intercept Survey

- Email Jon Cioffi (& CC Jeff Barnes for awareness): to deprecate the ForeSee `VA Main 2` survey so they’re not both showing up on Prod or Staging
- VSP Analytics: to ensure we can get a similar CSAT since we need a consistent way to show the VA.gov overall CSAT, and to ensure we have tracking on the survey.
- VSP FE Tools: to ensure that everything’s ok on the VA.gov platform.
- Sarkis: he mentioned needing to review surveys before they launch.

**Comment by joanneesteban** [comment]
## Using Medallia vs. Implementing surveys on VA.gov autonomously

VFS teams should use the Medallia tool so that 
- all of the customer feedback goes through the VA/VEO’s tools
- we continue to increase transparency between VA's departments
- all WBC VA.gov customer feedback data is in one place
- we can ensure that VA.gov surveys have gone through PRA

**Comment by joanneesteban** [comment]
## PRA Approval

[This sheet](https://docs.google.com/spreadsheets/d/1gkjignCqZV8qTYentLHvh9sZLy_Cnjj1eGodT6-pPzY/edit#gid=782170026) tracks the PRA approved questions.

You can request additional questions and answers to be PRA approved by having your DEPO lead email Evan Albert.

**Comment by jwoodman5** [comment]
@joanneesteban Can you please share Jon Cioffi's email address? Thanks.

**Comment by Kimberley2019** [comment]
Closing.

**Comment by jwoodman5** [comment]
> @joanneesteban Can you please share Jon Cioffi's email address? Thanks.

Address is - Jon.Cioffi@verint.com

**Comment by jwoodman5** [comment]
Question: What is the best way for me to get information about the ForeSee CSAT score?

Answer: ForeSee has some [documentation](https://www.foresee.com/blog/better-together-nps-csat/), but I think the best way to get closer to that calculation is asking Jon C from Verint. In general, it comes from the large intercept survey.

**Comment by joanneesteban** [comment]
@jwoodman5 thanks - @JasonTheBearded is there already a BQ connection to the GTM that's in place for Medallia?

**Comment by joanneesteban** [comment]
Facility Locator URL removed from 5 Star Survey in VA.gov Production on 2021-03-15, 15:04 EST.

**Comment by joanneesteban** [comment]
ForeSee Data uploaded via CSVs to BigQuery on 2021-03-15. Track here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19880

**Comment by jwoodman5** [comment]
@joanneesteban Do you think this needs to remain open?

**Comment by joanneesteban** [comment]
Probably not, thanks for flagging!
