### ISSUE TITLE
Open file picker and upload file

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18640]
## User story
As a user, I want the ability to select files from my device and upload them to my VA claim. 

There is a separate ticket for the camera / photo upload flow. This ticket is specific to the file upload flow.

## Acceptance Criteria
1. The **Select a file** large button from the File upload page opens the device's action sheet* to pick files
     - A user can choose from their: 1) camera roll, 2) file folder, and 3) cancel: https://www.npmjs.com/package/@expo/react-native-action-sheet
2. User has the ability to close out the file picker and return to the File upload page, either by selecting a file or by canceling the flow

Note: 
1. There will need to be a filter on file size/types. File picker library should support the file types indicated below.
     - Max file size: 50 MB
     - Accepted file types: pdf (unlocked), gif, jpeg, jpg, bmp, txt

## Designs
N/A
Launch page (note: design below reflects UI for the Photo Upload page. The File upload page is virtually identical, with the only modifications being copy changes.)
![Screen Shot 2021-01-15 at 9.49.08 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4de3cec6-1681-402b-9a47-81c6006bb2e5)

**Comment by bessgreen** [comment]
https://www.npmjs.com/package/react-native-document-picker (gif not supported)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/27/2021 - both Android and iOS.

**Comment by digitalken** [comment]
Stuck this one back in QA to have another look after the next build... 1/27/2021 @ 3:51 PM.

**Comment by digitalken** [comment]
PASS 1/28/2021 on iOS, Android.
