### ISSUE TITLE
Developer documentation: how to use json comparison script

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18656]
## Details

The primary validation method for GraphQL <> CMS Export will be a json comparison script, tracked in ticket #13762

Once it is complete, VFS teams are expecting to use this tool to determine what discrepancies they need to fix in transformers they own to reach parity between GraphQL <> CMS Export. 

This ticket represents documenting, for VFS and VSP developers, how to use that comparison tool.

Likely makes sense to put these docs in Confluence, either on the same page as the Transformer Development Guide or on another page that is cross-linked

## Acceptance Criteria
- [x] Developer documentation exists for how to use json comparison tool
- [x] Docs have been sent to VFS teams

**Comment by meganhkelley** [comment]
Note — I assume this comparison tool will primarily be used in the short term, during the release of CMS Export. 

Because of that, if it's easier to hold a recorded training/Q&A session, we could do that — the primary objective of this ticket is to unblock teams and enable them to use the comparison tool, once it has been completed.

**Comment by theodur** [comment]
The comparison tool may be used as part of the development process as well. I imagine this would be for as long as we compare the CMS export content against the GraphQL queries.

**Comment by theodur** [comment]
Documentation: https://vfs.atlassian.net/wiki/spaces/VP/pages/637567205/Transformers+Development+Guide#Diff-JSON-outputs
