### ISSUE TITLE
CT Redesign: Testing Prototype Sync

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#18655]
- UX team alignment on tasks for testing & screens for prototype.  
- Run thru draft discussion guide 
- Document UI & potential flows 
- Reconcile with testing workshop priorities

**Comment by amyknox** [comment]
TO DO
- [ ] Jen make updates to script
- [ ] Jen to run thru script / dry-run 
- [ ] Amy to run thru script / dry-run
- [ ] Jen / Amy share notes EOD (Slack today)
- [ ] Jen / Amy touchbase tomorrow morning (1/21)
- [ ] TBD - document all screens for task flows NLT noon 1/21
