### ISSUE TITLE
Refactor Code for Widget (links) on the Corona FAQ Spanish + English  Pages

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#18650]
Per the code review for the Corona FAQ spanish page,  we need to refactor the widget as recommended here:  

https://github.com/department-of-veterans-affairs/vets-website/pull/15289/files#r558427051 

Note: it was deemed acceptable to launch as-is and refactor post-launch.

**Comment by youngfreezyVA** [comment]
I looked into the recommendations and I think React is overkill for this. Refactoring to a react based approach is not needed
