### ISSUE TITLE
[Call Center] Education Call Center & HRC Data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1866]
## User Story or Problem Statement
How might we get data from Health Resource Center and Education Call Center?

## Goal
-Be added to weekly and/or monthly reports sent out by EDU call center.
-Get full access to all VA.gov tracked issues in HRC CRM. 
-_stretch:_ See if it's possible for us to get access to MS Dynamic instance being used by HRC

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [x] Follow up with EDU call center on report request
- [x] Set up time to meet with Sylvia to discuss available data and access to HRC's instance of MS Dynamics
- [x] Meet with ID.me to learn more about their call center data tracking and see if we can get access to data. 
- [x] If given access to data, add to github.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Had a conversation with Sylvia and she was able to share HRC data for VA.gov calls for the past 4 months.

**Comment by clantosswett** [comment]
We have followed up with EDU but have not heard back about getting added to their weekly/monthly reports. We will continue to reach out but for now, the work involved does not require an issue to be active. Additionally, we spoke with ID.me and are setting up a bi-weekly sync and will be discussing if we can get access to their contact center data as well.
