### ISSUE TITLE
Format phone number extensions on Personal Information page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18671]
## User story
As a user, I want the ability to view my saved number, including the extension. 

## Acceptance Criteria
1. When a user has saved a phone number and an extension, the phone number + extension should display on the Personal Information page, following this format:
     - (000)-000-0000, ext. 0000
2. When the extension is too long to fit on one line, wrap to a new line
3. Update service so the extension is passed through

## Designs
Not in InVision, but see screenshot below from staging:
![Screen Shot 2021-01-15 at 2.23.16 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/588cc60c-1e24-4e4f-8490-730ff94b1f85)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS - 1/29/2021 - Only able to test on one where the phone number was already entered.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/55cd8704-3f9d-4a51-bc96-6f5b16fd74da)
