### ISSUE TITLE
Document current analytics for Type of Care and Type of Facility pages

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18674]
## Background
Depending on the type of care, the "start" of the Community Care or VA request flow may happen on different pages. Event-based tracking, rather than by URL, could help more appropriately inform funnel/completion tracking.

### Question to Answer
- Where and when does `vaos-community-care-path-started` event fire?

## Item Description
Document the current analytics implementation on the Type of Care and Type of Facility pages.
- Event actions, including CTA labels and respective states
- CTAs without tracking (e.g. VVC Join appointment button doesn't fire event)
- Performance and session-based tracking (e.g. total number of appointments shown in each tab)

**Comment by jbalboni** [comment]
- vaos-update-address-alert-displayed
   - On type of care page when user has no residential address
- nav-warning-alert-box-content-link-click
   - Fires when a user clicks on link within no residential address alert box
   - alertBoxHeading: `To use some of the tool’s features, you need a home address on file`
- vaos-community-care-path-started
   - Fires after clicking Continue on the type of care page if user is eligible and type of care is podiatry
   - Fires after a user chooses the community care facility type of the type of facility pages
   - First after Audiology type of care page
- vaos-cc-eligible-yes
   - Fires if user is CC eligible and is registered at CC enabled systems

**Comment by laurenernest** [comment]
@jbalboni 2 follow-up questions:

1. Do you mean this page `/health-care/schedule-view-va-appointments/appointments/new-appointment/audiology`?

> - vaos-community-care-path-started
>   - First after Audiology type of care page


2. It looks like the only other place we need the path started event to fire is `/health-care/schedule-view-va-appointments/appointments/new-appointment/choose-eye-care` after clicking Continue with Optometry selection. Does that seem right/possible?
