### ISSUE TITLE
Sentry error: Location not found after selecting facility

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#18689]
Error: http://sentry.vfs.va.gov/organizations/vsp/issues/16146/?environment=production&project=4&query=is%3Aunresolved+vaos&statsPeriod=14d

Might have something to do with facility configuration (580).

**Comment by narin** [comment]
I spent some time trying to figure out what is going on here but was unable to.  I fetched the facility details of vha_580 and there didn't seem to be anything amiss.  It _might_ have to do with the type of care being eye care according to the Sentry breadcrumbs but I couldn't reproduce it. It has only affected one user so far so I'm deprioritizing it for now and maybe someone else might be able to spend some time on it.

**Comment by jbalboni** [comment]
This hasn't happened in two months and only happened once, I'm closing this.
