### ISSUE TITLE
[Development] Form 526 -  BE update rated disabilities

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#18681]
## background
When a veteran creates a form526 we [prefill](https://github.com/department-of-veterans-affairs/vets-api/blob/c559b92a521a6614fc087316a09dd3b75235fee4/app/models/form_profiles/va526ez.rb#L72) rated_disabilities_information when a veteran starts a form.  However, it's possible that the veterans rated disability info will be updated in the upstream system before the veteran submits the form, especially if they start the form and come back to it later. 

discovery issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12941
sample data: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/163 
front end issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13128

## issue description
- Back end will create a new controller specifically for 526 (and probably HLR at some point)
- Back end will pull the new rated disabilities and add to the in progress response (if the rated disabilities are different, the metadata will be updated to change the return URL to direct users to the rated disabilities page)

- Front end adds manipulation logic on the rated disabilities page to handle the changed rated disabilities (theoretically, the places the rated disabilities were previously mentioned throughout the form should be properly updated and handled as the user goes through the form)

**Comment by annaswims** [comment]
@Mottie / @ndsprinkle

When I find that a veteran's rated disabilities list has updated, should I update the rated disabilities hash or put the new data somewhere else?  I'd lean towards just replacing the current rated disabilities. 

I'd think we'd want to update the returnUrl in the metadata to have them go back to the `/disabilities/rated-disabilities` page, if they were past that page. Is the best way to know if they've gotten to the rated disability page if they have `                "view:selected": true` within a rated disability?

Should I add an attribute to the metadata like `"ratedDisabilitiesUpdated": true` also?

**Comment by Mottie** [comment]
> replacing the current rated disabilities

I'd vote for that too!

> if they've gotten to the rated disability page if they have ` "view:selected": true` within a rated disability

I think that'd work. A user can't get past that page if they've opted to include rated disabilities. If they're not including rated disabilities, then there won't be any `"view:selected"` options set. So we don't need to return them to that. page.

> Should I add an attribute to the metadata like `"ratedDisabilitiesUpdated": true` also?

I'd vote for yes.. since it'd be easier for us to check a flag instead of filtering through the data each time. That meta data setting will get ignored upon next save-in-progress save, right? We shouldn't retain it.

**Comment by annaswims** [comment]
>>Should I add an attribute to the metadata like "ratedDisabilitiesUpdated": true also?

>I'd vote for yes.. since it'd be easier for us to check a flag instead of filtering through the data each time. That meta data setting will get ignored upon next save-in-progress save, right? We shouldn't retain it.

yeah, my thought was that the FE would remove `"ratedDisabilitiesUpdated": true` or make it false before the next save.

**Comment by Mottie** [comment]
> the FE would remove `"ratedDisabilitiesUpdated": true`

We'd have to modify the platform code to do that. We don't typically alter the SiP data/meta data.

**Comment by annaswims** [comment]
ok, I'll just return ratedDisabilitiesUpdated true/false in the metadata

**Comment by annaswims** [comment]
Cache PR was merged.

**Comment by annaswims** [comment]
Re-opening. @Mottie pointed out that only veterans who selected that they were claiming an increase need to be returned to that page. 
![Screen Shot 2021-02-15 at 10 37 33 AM](https://user-images.githubusercontent.com/19188/108126126-79188000-7077-11eb-9ae8-660b6149b60e.png)
