### ISSUE TITLE
508-defect-1 ❗  Launchblocker [SCREENREADER, COGNITION]: Language of parts in English MUST be set to EN

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#18698]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Josh_

## User Story or Problem Statement

As an English speaking screen reader user, I want to hear "Read this page in English" in English.

### Read this page
Currently the "Read this page in English" link has the `lang` attribute of `es` which is Spanish, not English. This will cause the screen reader to read this string with a Spanish accent which both English and Spanish speaking users may not understand.

### Breadcrumb's Spanish page title
Since the breadcrumb is _outside_ the `div` that holds the `lang="es"` attribute, the page title is still read out in an English accent instead of a Spanish accent. 

### Other instances
There are also instances where no `lang` attribute exists including:
- `<a href="https://gibill.custhelp.va.gov/">Ask a question&nbsp;(en inglés)</a>`
- `<a href="https://www.mobile.va.gov/app/va-video-connect" target="_blank" rel="noopener ">VA Video Connect (en inglés)</a>`
- `<a href="https://jkodirect.jten.mil/Atlas2/page/login/Login.jsf" target="_blank" rel="noopener ">Joint Knowledge Online&nbsp;(en inglés)</a>`

## Acceptance Criteria

Example:
- [x] The "read this page in English" link  uses `en` as the value for the `data-lang` attribute, not `es`
- [x] A `lang` attribute with the value of `en` is added for screen reader support to the "read this page in English" link
- [x] A `lang` attribute with the value of `es` is added for screen reader support to the "Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos" link in the breadcrumb
- [ ] A `lang` attribute with the value of `es` is added for screen reader support to the div with `id="content"`
- [ ] A `lang` attribute with the value of `en` is added for screen reader support to any other English content within the `main`

## Steps to Recreate

1. Enter `https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/` in browser
2. Start any screenreading device
3. Tab to "Read this page in English"
4. Confirm the string is read in a Spanish accent

## Proposed Solution

Add `lang="en"` and update `data-lang="es"` to `data-lang="en"`

#### Before

```html
<a class="i18-toggle" data-lang="es" href="/coronavirus-veteran-frequently-asked-questions">
  Read this page in English
</a>
```

#### After

```html
<a class="i18-toggle" data-lang="en" lang="en" href="/coronavirus-veteran-frequently-asked-questions">
  Read this page in English
</a>
```

#### Before

```html
<a aria-current="page" href="/coronavirus-veteran-frequently-asked-questions-esp" id="9ed8077a8ef1af8415b0f6e2c2678435">
  Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos
</a>
```

#### After

```html
<a lang="es" aria-current="page" href="/coronavirus-veteran-frequently-asked-questions-esp" id="9ed8077a8ef1af8415b0f6e2c2678435">
  Preguntas frecuentes sobre el coronavirus: Lo que necesitan saber los Veteranos
</a>
```

#### Before

```html
<div id="content" class="interior">
```

#### After

```html
<div id="content" class="interior" lang="es">
```

## WCAG or Vendor Guidance (optional)

* [Success Criterion 3.1.2: Language of Parts](https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html)

## Screenshots or Trace Logs
<img width="1345" alt="Screen Shot 2021-01-18 at 4 50 20 PM" src="https://user-images.githubusercontent.com/14154792/104966250-6a727680-59ae-11eb-9879-3e3ddec89995.png">

**Comment by 1Copenut** [comment]
@joshkimux Great call here! I'd offer a possibility that the `data-lang="es"` might be needed for an upstream hook. In that case, adding the `lang="es"` attribute will give screen readers the cue they need and maintain current functionality.

**Comment by joshkimux** [comment]
@1Copenut Updated accordingly!

**Comment by joshkimux** [comment]
Reopening this ticket as the div with `id="content"` no longer has a `lang="es"` attribute

**Comment by joshkimux** [comment]
@youngfreezyVA I've updated the acceptance criteria accordingly!

**Comment by youngfreezyVA** [comment]
i thought that was a part of the change requested. i'll add it back in
