### ISSUE TITLE
App loading

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18709]
## Dev task:
1. During the auth flow, preload the user's profile information
     - This should occur after a user has entered their login information, but before the Home screen loads
2. Result (for QA): After the auth flow and upon navigating to the Profile page, the user's profile information (name, branch of service) should already be loaded

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/28/2021 - In Android I see the loading profile screen at startup and when I go to profile, the correct stuff shows up immediately.  On iOS, I sometimes don't see the loading profile screen but when I go to profile, all the new info is available immediately.
