### ISSUE TITLE
Discovery of EVSS/VBMS API interactions for possible move to BGS/VBMS direct

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18713]
## Epic Description
Continued evidence supports a desire to move off of EVSS.  More details will be added and this will likely be converted to an Epic.

## Purpose
We have our initial mapping of EVSS -> BGS/VBMS replacement APIs.

## Acceptance Criteria
- [ ] Lay out roadmap/stories for additional discovery

**Comment by michelpmcdonald** [comment]
The current plan is that Lighthouse is going to take over the sunsetting EVSS services.
We have captured in more detail in current tickets:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/41341
