### ISSUE TITLE
IA feedback - Staging review - Spanish translation

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#18711]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- This feedback is for 1 of the 3 pages intended to launch: https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/
- Feedback for the other 2 pages will need to be reviewed once they are ready

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- English version of the page must have a link to the Spanish version so users can toggle between the pages if needed.   This can be validated either in the preview environment or once the content is fully live.  Please provide appropriate links and comment once available. 

**Should:**

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by SKasimow** [comment]
Hello @mnorthuis - pages are now live:

Spanish page:  https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/ 

English page:  https://www.va.gov/coronavirus-veteran-frequently-asked-questions/


cc: @joshkimux @DanielleThierryUSDSVA

**Comment by mnorthuis** [comment]
Thank you!
