### ISSUE TITLE
Create new Zenhub workspace

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#18717]
Goals:
- Retain existing Zenhub features with improved performance and UX

AC:
- [x] Create new "VSA - Caregiver" workspace
  - https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/board?notFullScreen=false&repos=133843125&showPipelineDescriptions=false
- [x] Configure workspace filter to `vsa-caregiver` label
  - https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/board?notFullScreen=false&repos=133843125&showPipelineDescriptions=false
  - https://help.zenhub.com/support/solutions/articles/43000455864-optimizing-workspace-load-times
 - [x] Configure columns to match current board

**Comment by ala-yna** [comment]
Closing this out - columns have been migrated, and the new space has proved to be significantly faster and more useful. Thanks Mike!
