### ISSUE TITLE
Modal story in Storybook is broken

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#18727]
## Issue Description
The [Modal story in Storybook](https://design.va.gov/storybook/?path=/docs/components-modal--default) hangs. It's unclear what the root cause is right now, but the symptoms include:
- Not rendering the story
- Maxing CPU usage
- Rendering the browser tab unresponsive (at least in Vivaldi, a Chromium browser)

Potentially, there's an infinite loop somewhere along the way.

## Acceptance Criteria
- [ ] The Modal story renders

**Comment by caw310** [comment]
@bkjohnson , reassigning to you for now. Will move this to the next sprint to give us time to replan our sprint work with Chris out for the next month.

**Comment by k80bowman** [comment]
Opened [PR](https://github.com/department-of-veterans-affairs/component-library/pull/66)

**Comment by k80bowman** [comment]
Should be all fixed now 🙂
