### ISSUE TITLE
Update Manual Test Cases for COVID Vaccine Prep Tool

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18729]
## User Story

The COVID Vaccine Prep Tool development process was rapid and included several important changes in the days immediately preceding release. As a COVID Vaccine Prep Tool QA tester, I need test cases with updated scenarios that more accurately reflect the behavior of the product released to production. Existing test cases are present in the [Vaccine Preparation Tool project in TestRail](https://dsvavsp.testrail.io/index.php?/projects/overview/33).

## Expected Behavior

Existing test cases include steps that can be followed literally in order to achieve expected behaviors in the COVID Vaccine Prep Tool.

## Acceptance Criteria

- [x] Manual test case steps have been updated to include new behaviors and remove behaviors no longer present.
- [ ] All possible user journeys within the product have been verified with test cases.

**Comment by ddzz** [comment]
Three TestRail test cases were updated to reflect minor changes to the test flow. This task only considered tests for the original sign-up feature built by the COVID prep tool team; additional features developed since then are considered out of scope.

**Comment by pjhill** [comment]
Completed
