### ISSUE TITLE
Update routing for submitting claim decision request + hide file request UI

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18735]
## User story
As a user, I no longer want to see any file requests from VA after I've submitted my claim decision request.

## Acceptance Criteria
Make the following updates to the submission flow for **Ask for my Claim Decision**

1. When the success message (mobile alert CC) displays after a successful submission, the **Back button should route to the Claim Detail page** (this is the page with the claim step table)
2. On the Claim Detail page, the following should also happen:
     - File request mobile alert at the top of the page should no longer display
     - Step 3 of the claim should no longer display the file request header ("You have 2 file requests from VA") 
     - Step 3 of the claim should no longer display the **View file requests** large button 

## Dev note:
The above AC is an update to the following ticket: [#17520](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17520
)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/3/2021 - All as requested.
