### ISSUE TITLE
VA request - Increase character limit in reason for appointment field

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18732]
## Issue Description
In response to veteran feedback, we'd like to increase the character limit in the reason for appointment field.

![Screen Shot 2021-02-02 at 7.09.54 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/524b5b4f-0ed4-4a55-9d2d-9b06bf5cbd5b)

### Backend Dependencies
VAMF Work
https://issues.mobilehealth.va.gov/browse/VAOSR-1407
https://issues.mobilehealth.va.gov/browse/VAOSR-725

VarResources Release
https://issues.mobilehealth.va.gov/browse/NGD-8426
https://issues.mobilehealth.va.gov/browse/VAOSR-1483

---

## Acceptance Criteria
- [ ] Users can enter up to 250 characters

**Comment by laurenernest** [comment]
Pending BE release slated for 1/29

**Comment by laurenernest** [comment]
VAR Resources 4.27.2 updated release target is 2/15

**Comment by laurenernest** [comment]
New release target is 2/19

**Comment by grossb1** [comment]
Putting this in blocked until back-end changes are live.

**Comment by laurenernest** [comment]
@LanceGundersen @grossb1 var-resources 4.27.2 was deployed and verified in Production today. we're good to proceed with our changes.
