### ISSUE TITLE
Spike - Image aggregation

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18730]
## Dev task
1. Investigate FE options for compiling multiple photos into a single .pdf document after a user has uploaded their photos

**Comment by keli13** [comment]
https://github.com/Anyline/react-native-image-to-pdf

Pros
 - works on both ios and android
 - handles pagination to a degree
 - has compression support to a degree
 - supports
 	- android minSDK 19
 	- ios min platform 8.0

 Cons
  - not well maintained(last update was 11 months ago)
  - no typescript
  - no extensive docs
  - not highly configurable
  	- ex. you cant change the destination of the pdf output

Sample pdf:
[https://app.zenhub.com/files/133843125/d6107f21-8f2e-437a-97fe-39b6fcfb6cee/download](https://app.zenhub.com/files/133843125/d6107f21-8f2e-437a-97fe-39b6fcfb6cee/download)
