### ISSUE TITLE
Analytics Implementation or QA Support for Platform Documentation 

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#18746]
# Google Analytics Implementation or QA Request

## Description
**- Is this request for Google Analytics implementation or QA?**
  - We can handle Google Analytics

**- Who is this request for?**

    - @lianilychee, via #VSP-content-ia
    
**- What team/project is this work for?**
  - VSP Content/IA, Platform Documentation
    
**- Provide the Domain where Google Analytics needs to be implemented**
  - https://depo-platform-documentation.scrollhelp.site/developer-docs/
  - No PII is passed

**- Please provide any upcoming deadlines or important milestones**
  - Would like to release to VFS teams by end of January 2021

**- Typical Website Interactions to Track**

<details>
- Traffic 
  - Home page https://depo-platform-documentation.scrollhelp.site/developer-docs/
    - Getting started https://depo-platform-documentation.scrollhelp.site/developer-docs/Getting-started.582811797.html
      - Accessing Internal Tools https://depo-platform-documentation.scrollhelp.site/developer-docs/Accessing-Internal-Tools.591036433.html
      - Setting Up VA.gov Locally https://depo-platform-documentation.scrollhelp.site/developer-docs/Setting-Up-VA.gov-Locally.687931400.html
    - Platform architecture https://depo-platform-documentation.scrollhelp.site/developer-docs/Platform-architecture.604012545.html
      - GitHub Repos https://depo-platform-documentation.scrollhelp.site/developer-docs/GitHub-Repos.619053226.html
      - Environments https://depo-platform-documentation.scrollhelp.site/developer-docs/Environments.603488279.html
        - Development Environment https://depo-platform-documentation.scrollhelp.site/developer-docs/Development-Environment.808058891.html
        - Staging Environment https://depo-platform-documentation.scrollhelp.site/developer-docs/Staging-Environment.807305245.html
        - Sandbox Environment https://depo-platform-documentation.scrollhelp.site/developer-docs/Sandbox-Environment.808058909.html
        - Production Environment https://depo-platform-documentation.scrollhelp.site/developer-docs/Production-Environment.794984459.html
        - Review Instances https://depo-platform-documentation.scrollhelp.site/developer-docs/Review-Instances.810385495.html
    - Developing on VA.gov https://depo-platform-documentation.scrollhelp.site/developer-docs/Developing-on-VA.gov.603652104.html
        - Frontend Developer Documentation https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-Developer-Documentation.687931428.html
        - Submitting Pull Requests for VSP Engineering Review https://depo-platform-documentation.scrollhelp.site/developer-docs/Submitting-Pull-Requests-for-VSP-Engineering-Review.655032351.html
        - How VSP Uses Code Owners https://depo-platform-documentation.scrollhelp.site/developer-docs/How-VSP-Uses-Code-Owners.655032344.html
        - Using Review Instances https://depo-platform-documentation.scrollhelp.site/developer-docs/Using-Review-Instances.590774288.html
        - Vets API Database Migrations https://depo-platform-documentation.scrollhelp.site/developer-docs/Vets-API-Database-Migrations.689832034.html
        - Pull Request Best Practices https://depo-platform-documentation.scrollhelp.site/developer-docs/Pull-Request-Best-Practices.688259145.html
        - Contract Testing Overview https://depo-platform-documentation.scrollhelp.site/developer-docs/Contract-Testing-Overview.687931536.html
        - Using Pact for Contract Testing https://depo-platform-documentation.scrollhelp.site/developer-docs/Development.591134721.html
    - Integrations https://depo-platform-documentation.scrollhelp.site/developer-docs/Integrations.603619334.html
      - Vets API https://depo-platform-documentation.scrollhelp.site/developer-docs/Integrations.603619334.html#
        - Overview https://depo-platform-documentation.scrollhelp.site/developer-docs/Overview.844955712.html
        - Development https://depo-platform-documentation.scrollhelp.site/developer-docs/Development.591134721.html
        - Documentation https://depo-platform-documentation.scrollhelp.site/developer-docs/Documentation.721780779.html
        - Authentication https://depo-platform-documentation.scrollhelp.site/developer-docs/Authentication.721420316.html
        - Authorization https://depo-platform-documentation.scrollhelp.site/developer-docs/Authorization.721387554.html
        - Forms https://depo-platform-documentation.scrollhelp.site/developer-docs/Forms.721453145.html
        - PDF Generation https://depo-platform-documentation.scrollhelp.site/developer-docs/PDF-Generation.721780786.html
        - Request Processing https://depo-platform-documentation.scrollhelp.site/developer-docs/Request-Processing.724992009.html
        - Response Serialization https://depo-platform-documentation.scrollhelp.site/developer-docs/Response-Serialization.721420368.html
        - Service Objects https://depo-platform-documentation.scrollhelp.site/developer-docs/Service-Objects.721780810.html
        - Vets-API Endpoint Punch List https://depo-platform-documentation.scrollhelp.site/developer-docs/Vets-API-Endpoint-Punch-List.590872597.html
        - Settings https://depo-platform-documentation.scrollhelp.site/developer-docs/Settings.721616976.html
      - External Integrations https://depo-platform-documentation.scrollhelp.site/developer-docs/External-Integrations.640909834.html
    - Deployment https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployment.604078088.html
        - Deployment Process https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployment-Process.590970953.html
        - Feature Toggles https://depo-platform-documentation.scrollhelp.site/developer-docs/Feature-Toggles.590938137.html
    - Monitoring https://depo-platform-documentation.scrollhelp.site/developer-docs/Monitoring.603291671.html
        - Tracking Application Errors with Sentry https://depo-platform-documentation.scrollhelp.site/developer-docs/Tracking-Application-Errors-with-Sentry.590774316.html
        - Sentry Tagging Standards https://depo-platform-documentation.scrollhelp.site/developer-docs/Sentry-Tagging-Standards.590741551.html
        - Aggregating Data with StatsD https://depo-platform-documentation.scrollhelp.site/developer-docs/Aggregating-Data-with-StatsD.688947297.html
        - Triaging API Errors https://depo-platform-documentation.scrollhelp.site/developer-docs/Triaging-API-Errors.687931492.html
    - Security https://depo-platform-documentation.scrollhelp.site/developer-docs/Security.603488296.html
        - Identity and user authentication https://depo-platform-documentation.scrollhelp.site/developer-docs/Identity-and-user-authentication.603815942.html
    - Support https://depo-platform-documentation.scrollhelp.site/developer-docs/Support.604012552.html
</details>

- **No authentication**

- **No additional comments at the moment**
  - We are sprint planning tomorrow to see what portion of implementation and strategy we can take on.  Confluence Cloud has a GA plug-in.

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by joanneesteban** [comment]
Thanks, @lianilychee ! For "traffic," what type of interactions would you be looking for?

**Comment by joanneesteban** [comment]
@lianilychee - can you please provide documentation for the plug in? We can start looking into GA tracking on our end once we get the documentation.

**Comment by joanneesteban** [comment]
And if you have your KPIs ready - that would be really helpful in determining what we'll need to track!

**Comment by lianilychee** [comment]
> For "traffic," what type of interactions would you be looking for?

Ooooh I'm not strong on this, so cobbling together terms from Googled knowledge: 
* source (are they coming from Slack, Newsletter, or...?) <-- IIRC this requires unique links per source
* number of visitors to a given page
* exit pages

Let me pick my team's brains during SU (on Thurs 2/4) to see; I'll edit this comment + post another comment if there are any changes.

> can you please provide documentation for the plug in?

For look/feel, we're using Scroll Viewport: https://help.k15t.com/
For GA, we're using GA for Confluence: https://wiki.resolution.de/doc/gafcc/setup-google-analytics-for-atlassian-confluence-cloud <-- not to be confused with another plug in called "GA _in_ Confluence".

> if you have your KPIs ready

The only quant KPI I have in my product outline is "Volume of support requests" - the rest are qual measurements.

**Comment by gmaciolek** [comment]
Hello @joanneesteban! I'm jumping in here to see if we can get a GA account set up yet this sprint. At a minimum, we would need a GA tracking ID to complete our objective for this sprint. I can plug the tracking ID into the ScrollViewport to get it all connected. Is that a realistic time frame for your team?

I realize we have work to do on our end to set goals, identify KPIs and determine what metrics from GA can help us understand the success of the Platform website, but we need to set aside time for that in an upcoming sprint. In general, I assume that the following generic GA metrics will ladder up to our eventual goals: overall page views, bounce rate, pages per session, session duration. We will have a few landing pages that link off (similar to how the current [homepage MVP](https://department-of-veterans-affairs.github.io/va.gov-team/) does) and we'll want to know what links people are click on for those pages.

We also have some ideas for non-GA insights such as surveys and on-page ratings, but again, we have yet to set our goals and define success metrics so it's clear how all of this information comes together.

**Comment by jonwehausen** [comment]
@lianilychee @gmaciolek For the sake of future-fitting this for any future tagging you may need, are you all able to specify our GTM container ID within the plugin? `GTM-T2ZTDXZ`

This should allow us to then start collecting pageviews and we can repurpose our existing GA property for documentation to include confluence while setting up some filtered views.

**Comment by gmaciolek** [comment]
@jonwehausen I added the GTM container ID to the Scroll Viewport settings and checked the source code. It looks to me like it's tracking: https://depo-platform-documentation.scrollhelp.site/developer-docs/
[](url)

![image](https://user-images.githubusercontent.com/3953849/112176005-bbc4ff00-8bc5-11eb-9978-07818120fcca.png)

**Comment by bsmartin-ep** [comment]
Thanks @gmaciolek.  GTM tag is loading, but I'll need to add the new domain to get pageviews into GA.  

I'll take care of this today.

**Comment by bsmartin-ep** [comment]
@laurensimpson14 -

As discussed, this is ready for your QA:


GTM

- Renamed GTM container to VSP - GitHub TOC and Platform Docs
- Created [this workspace](https://tagmanager.google.com/#/container/accounts/144676348/containers/30787921/workspaces/5) which adds a trigger to load PVs for depo-platform-documentation.scrollhelp.site

GA

- Renamed [this property](https://analytics.google.com/analytics/web/#/a50123418w224573768p240292331/admin/property/settings) to VSP - VA.gov Documentation
- Renamed view _All Website Data_ to _All Documentation Sites _
- Added new view: [Backend development documentation - depo-platform-documentation.scrollhelp.site](https://analytics.google.com/analytics/web/#/a50123418w224573768p240292331/admin/view/settings)
- Renamed old TOC view to [Client application documentation - department-of-veterans-affairs.github.io](https://analytics.google.com/analytics/web/#/a50123418w224573768p227831524/admin/view/settings) to match.  Also added a similar hostname filter (we were just looking at subdir before).


## :warning:  One weird QA thing:  

The GTM workspace is sending all hits in GTM debug mode to a fake GA UA ID (UA-123456789-0) so you won't actually see them in GA.  @jonwehausen - is there a workaround to this or do we just examine the tag in GTM, publish, then check in GA?

**Comment by laurensimpson14** [comment]
@bsmartin-ep I've QAd and everything looks good. Like you noted though, I did see that the debug mode was sending to a fake GA ID - my console was saying "UA-12345678-90". 
If there isn't a workaround for it then I think we are good to publish & then check GA after.

**Comment by bsmartin-ep** [comment]
@lianilychee -

GTM and GA changes have been published.

We now have 3 documentation GA properties:

- [All Documentation Sites (Client and backend)](https://analytics.google.com/analytics/web/#/report-home/a50123418w224573768p212889364)
- [Backend development documentation - depo-platform-documentation.scrollhelp.site](https://analytics.google.com/analytics/web/#/realtime/rt-content/a50123418w224573768p240292331/)
- [Client application documentation - department-of-veterans-affairs.github.io](https://analytics.google.com/analytics/web/#/realtime/rt-content/a50123418w224573768p227831524/)

**Comment by bsmartin-ep** [comment]
Does everything look as expected @lianilychee ?  OK to close this out?

**Comment by bsmartin-ep** [comment]
Confirmed with the requesting team this looks OK.  Closing.
