### ISSUE TITLE
Identify and store fields from MPI Response that we can derive from SSOe payload

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#18741]

**Comment by bosawt** [comment]
All data that we currently use from MPI that is stored in the SSOE response, we should leverage. To do this, we should identify the fields now in the User model that pull from MPI, and potentially pull from UserIdentity model if possible (this is similar to the birls_id, participant_id, etc work I've done. So it's possible we'll want to split this up into individual fields).

Implementation would look similar to this:
https://app.zenhub.com/workspaces/vsp-identity-5f5bab705a94c9001ba33734/issues/department-of-veterans-affairs/vets-api/5539

**Comment by bramleyjl** [comment]
Most of the possible work to obtain user attribute information from `UserIdentity` over MPI has been completed in the course of other refactoring. The MPI-explicit methods that remain on the User model fall into the following categories:

Use case requires information directly from MPI, either to compare against the same information from UserIdentity, as part of the User profile serializer, or to meet some edge case: 
- edipi_mpi
- first_name_mpi
- gender_mpi
- last_name_mpi
- mpi_profile_birth_date
- ssn_mpi

Information is not available from UserIdentity:
- active_mhv_ids
- address
- given_names
- historical_icns
- home_phone
- mhv_account_state
- mhv_ids
- mpi_profile?
- normalized_suffix
- suffix

Deprecation planned:
-  va_profile
-  va_profile_error
-  va_profile_status
- sec_id_mpi
