### ISSUE TITLE
CT: Additional lines in school locations on profile page and /mo incorrect placement

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#18747]
## Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/31005124
2. Scroll down to school locations
3. Change to 768px and below 
4. Observe additional lines
5. See that /mo falls below the amount

![Screen Shot 2021-01-20 at 7.17.52 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/95409265-8ebd-4aa2-b642-f067224963cb)

## Expected behavior:

Those lines should not appear when reducing to 768px and below. The /mo should be on the same line as the amount

![Profile - OLD-DOMINION - Mobile Table Display@2x.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f2aeec27-788f-4a1a-be17-75418bd03d3a)

**Comment by amyknox** [comment]
@ksantiagomorgan6  The mobile screengrab that's attached to the story has the correct styling for fonts & layout.  

There's a weird element at the bottom of the School locations panel where the "Showing 6 of 6 locations" is appearing superimposed on the Cautionary information accordion heading. It should be within the School locations panel, with typical padding.  

LMK if you have Qs - or need a more refined view.

**Comment by ksantiagomorgan6** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/15794

**Comment by sonntag-adam** [comment]
Testing passes QA
