### ISSUE TITLE
New VA.gov primary header/footer, navigation, and menus

### ISSUE THREAD

**Issue by andrewlewandowski** [department-of-veterans-affairs/va.gov-team#1875]
## High Level User Story
As a user on VA.gov, I need streamlined main menus and global utilities so I can get to all content and tools in 1-2 clicks/taps.

## Hypothesis/(es)
**If** we redesign our global header and footer with new navigation and menus **then** we expect user satisfaction scores will increase because users can get to all content and tools in just 1-2 clicks.

## Goals
* Get users to all content and tools in just 1-2 clicks/taps
* Increase visual emphasis/affordance on Facility Locator and Sign In/Account menu items
 * The design for both should be adjusted for when a user is signed out vs. signed in
* Optimize Facility Locator and Sign In/Account design for mobile
* Add Tier 2 content menu
* Further iterate or flesh out Tier 3 content menu (should this move to the footer?)
* Remove visual and UX differentiation between main menus (e.g, "VA Benefits and Health Care") and global utilities (e.g., "Search")

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`, `Automation + Instrumentation`, `Support`, `Capacity-building`)

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by FranECross** [comment]
@jilladams This looks like an outdated/old header/footer epic, not really tied to the current Federal/Footer initiative and work. Do you object to me closing it? Thanks!

**Comment by jilladams** [comment]
This is a Q for @davidconlon  probably. Hilariously: Andy Lewandowski who made this epic back in the way back, is now working at the White House and is the strategic lead behind us adopting the Federal Header / Footer. So yeah: I'd say this probably safe to close, but will let Dave confirm.

**Comment by FranECross** [comment]
Added to next Product Sync meeting agenda
