### ISSUE TITLE
Filter out contestable issues that have existing Higher Level Reviews

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18752]
## User Story
As a veteran, I don't want to accidentally ask for a decision review for an issue under an existing Higher Level Review.

## Expected Behavior
When we filter the contestable issues list, we need to cross check against Claims Status Tool and filter out anything that has an existing higher level review.

## Acceptance Criteria
- [ ] Talk to Lighthouse, maybe we can get them to do this filtering

**Comment by luke-gcio** [comment]
Conversation in Slack:

https://dsva.slack.com/archives/C5AGLBNRK/p1611157771036800

**Comment by vhenry07** [comment]
Closing as this work is being done by Lighthouse.
