### ISSUE TITLE
VAWEB - update GraphQL query and template

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#18755]
ACs
- [x] Coordinate with Public Websites FE team about switching out `field_intro_text` with `field_intro_text_limited_html` on `page` content type. 
- [x] Possibly update this directly, but will have Transformer implications.

**Comment by brianalloyd** [comment]
@kevwalsh we have this for action, planning to work it into next sprint.

**Comment by brianalloyd** [comment]
@kevwalsh at the point for validation, can you take a look and let us know if this is at a point for close out?  Thanks.

**Comment by brianalloyd** [comment]
Closing per Validation.  @kevwalsh please circle back if their is anything else you need our team to action on this, thanks.
