### ISSUE TITLE
Track Research Readiness

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#18759]
# Research readiness checklist

**Method 1: Moderated testing with Veterans (Feb 1-5)**: We'll test the live code prototype on Android only with Veterans recruited by Perigean in moderated 60-minute sessions. 

Research Plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-research/usability-testing/round-2/research-plan.md
Discussion Guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-research/usability-testing/round-2/discussion-guide.md

### We’re ready to go to submit our research plan when: 

- [x] IAM integration is in production & tested and ready for testers **[Owner: Patrick/Jonathan]**
- [x] We feel confident we’ll be ready to cut an APK of the app we’re ready to test by 1/26 **[Owner: Everyone]**
- [x] Instructions for how to download/sign up for Android APK are ready and in the discussion guide **[Owner: Jen]**

### We’re ready to start testing when:
- [x] We’ve identified someone who has LOA3 credentials and an Android to test with **[Owner: Jen]**
- [x] We've run a pilot test **[Owner: Bridget/Jen]**
- [x] We've run 1-2 test set up of APK only (production release, not debug version) with Ad Hoc folks with Androids **[Owner: Bridget/Jen]**
- [x] The moderator (Bridget) has a backup release in Test Flight that can be accessed using staging credentials (in case APK doesn’t work) **[Owner: Bridget/Patrick]**
- [x] We have a Mural for note-taking **[Owner: Bridget/Jen]**

---

**Method 2: Unmoderated, asynchronous testing with VA employees (Feb 1-12)**: Release the app to 15-20 VA folks and ask for them to submit feedback, with a focus on asking them to communicate to us about any bugs/issues they run into. 

### We’re ready to release the app to internal testers when: 
- [x] Instructions for how to download/sign up for Test Flight are made and exported as a PDF **[Owner: Bridget/Jen]**
- [x] Microsoft Teams OR Slack is set up **[Owner: Steve]**
- [x] Bridget, Jen, and Ayush have access to the Microsoft Teams OR Slack channel **[Owner: Steve]**
- [ ] We have emails for all testers **[Owner: Steve]**
- [x] We’ve written an intro email to all testers explaining the feedback we are seeking from them **[Owner: Bridget/Ayush]**
- [x] We've identified a survey platform for asynch feedback **[Owner: Bridget/Ayush]**
- [x] We’ve created a survey **[Owner: Bridget/Ayush/Jen]**

**Comment by bridgethapner** [comment]
- Explore Optimal Workshop for survey
- Survey Monkey is a possibility

**Comment by bridgethapner** [comment]
Draft language for testing email to internal VA folks

_Hello There,

We’re reaching out to you because we would love to have you test our preliminary internal release of the VA Mobile App - your feedback is extremely valuable to us identifying issues and building a strong app for Veterans across the country. We’re looking for your honest thoughts and experiences as testers!

Please share your feedback between February 1, 2021 and February 12, 2021, please follow the steps below:

Download the VA Mobile test app: This app will be available for your review from February 1st through 12th through App Center - a mobile app testing platform. We are attaching instructions on how to download the test VA Mobile app in this email.
Share your thoughts: You can do this in one of two ways:
Freeform feedback - Join the #va-mobile-app-beta-test channel on Teams. If you have any thoughts - small or large - you can share them here!
Survey feedback - We’re also running a structured survey through SurveyMonkey - this contains a few features that we want your feedback on.

Please let us know if you have any questions - we’re excited to hear from all of you!

Best,
The VA Mobile App Team_

**Comment by bridgethapner** [comment]
We can use Optimal Workshop for the survey - it doesn't require a license & I have the credentials. The account is in regular use by folks working on VA.

**Comment by bridgethapner** [comment]
Bridget & Jen are set up with access to Teams on CAG :tada: - YAY! Shout out to Jen for getting set up so quick & helping me get set up with the right software. I'll let Steve know.

**Comment by drjecker** [comment]
Message to post at the start of the teams channel:

Thank you for testing our preliminary internal release of the VA Mobile App. Your feedback is extremely valuable to us identifying issues and building a strong app for Veterans across the country. We’re looking for your honest thoughts and experiences as testers!

Please share your feedback between February 1, 2021 and February 12, 2021, and follow the steps below:

1. Download the VA Mobile test app: This app will be available for your review from February 1st through 12th through App Center - a mobile app testing platform. Instructions on how to download the test VA Mobile app are in your email.
2.  Share your thoughts: You can do this in one of two ways:
- Share your thoughts - small or large -  here!
- Survey feedback - We’re also running a structured survey through SurveyMonkey - this contains a few features that we want your feedback on.

Have questions, post them here and we'll get back to you.

**Comment by drjecker** [comment]
For the internal `#veterans` channel at Ad Hoc:

Hello Ad Hoc Veterans! We'd love to have you test our preliminary internal release of the VA Mobile App and give us honest feedback. If you are interested please go to #va-mobile-app-test between February 1, 2021 and February 12, 2021.

For the `#va-mobile-app-test` channel:
Welcome! Thank you for your interest in testing our preliminary internal release of the VA Mobile App. Your feedback is extremely valuable to us identifying issues and building a strong app for Veterans across the country. We’re looking for your honest thoughts and experiences as testers!

We are looking to gather your feedback between February 1, 2021 and February 12, 2021. If you are interested drop a note below or contact me or `@Bridget Hapner` and we will send you email instructions. 

Once you have the app installed you can share your thoughts in this channel or via our structured [Optimal Workshop survey](https://adhoc.optimalworkshop.com/questions/84o51p5v).

Have questions, post them here and we'll get back to you.
