### ISSUE TITLE
[Documentation] - Analysis using GitHub vs ID.me as an auth solution

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#18763]
## Description

A security vulnerability was identified with the publically accessible Sidekiq UI, working with other teams that have similar apps up, we want to investigate a more robust way to implement authentication on developer tools that leverage existing tools on the platform.  The tools that are readily accessible on platform to investigate are ID.me and GitHub.

## Definition of Done
- [x] Document is created outlining the pros & cons of both the solutions outlined above
- [x] Included in the document should be any other potential solutions if Identified as a possibility
- [x] Included in the document should be a recommendation for a path forward.

**Comment by erluti** [comment]
Finished a first pass here:
https://vfs.atlassian.net/wiki/spaces/VI/pages/976781382/Tool+Logins

**Comment by erluti** [comment]
Final document: https://vfs.atlassian.net/wiki/spaces/VI/pages/976781382/Tool+Logins
