### ISSUE TITLE
Set up process for content review of the app

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#18765]
# User Story
As a user using the VA mobile app, I want to read plain and clear language.  

# Tasks
- [ ] Reach out to sitewide content team for help
- [ ] Determine a process for how we will work together (e.g. use Google Sheets? Tickets and Invision?)

# Deadline for review
We don't have a firm deadline yet because we do not have a planned release date.

**Comment by artsymartha68** [comment]
Assigning to @DanielleThierryUSDSVA

**Comment by bridgethapner** [comment]
Thanks, @artsymartha68! 

@DanielleThierryUSDSVA We have an invision prototype that shows most of the app's content: https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/432863239. There also are some flows (signing in, uploading a file to a claim) that are only shown in the build, which can be accessed via Test Flight on iPhone. I can invite you to the Test Flight build whenever you are ready. Also happy to meet to talk about a good process or walking through any features.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @bridgethapner!

I can start with comments in the invision app and send questions over as I go. I have an Android phone, so not sure if I can access Test Flight?

**Comment by bridgethapner** [comment]
Hi @DanielleThierryUSDSVA! Unfortunately, Test Flight is only for iOS. If you have an Android, we can send you an APK file of our latest build for local installation onto your phone and provide corresponding staging accounts to sign in to view the features in the latest build. 

I was just chatting with @bessgreen on our team, who brought up a good point that reviewing the APK file of our live build would be the most efficient thing -- although the Invision prototype is fairly up to date, there are enough discrepancies between it and the build that it might not be the best artifact for your review. 

Does reviewing the app via an APK file sound ok to you? If so, I can set up a time to walk you through the setup of the file & provide the right staging accounts.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @bridgethapner. Yes, let's chat early this week. A link to my public view calendar is in my slack profile. Feel free to grab a time that works for you.

Here are my thoughts:

- I think the fastest/easiest way for me to provide guidance/any needed content rewriting is to add comments in the prototype. I'm going through the prototype this weekend and dropping in comments. And then let's talk through questions and/or any discrepancies early next week. 

- Then the full review of the live build can be part of the collab cycle staging review.  We can share my prototype comments with Peggy so she's aware of those while doing her review. 

- I'm noticing some tweaks that we should make in some of the error messages. But, since those are sitewide components, I want to talk through whether it makes sense to note that here _and_ in sitewide documentation.  

Thanks!

**Comment by bridgethapner** [comment]
Thanks Danielle! I grabbed time for us tomorrow at 2:30 ET, it looked like that was free but let me know if that doesn't work and I can shift. All your notes sound great - looking forward to talking tomorrow.

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht @bethpottsVADEPO Just tagging you for awareness as we set up more of our sitewide content process. I've added our product support labels as well. I'd been working with the mobile app team before, and helping out now before they go to their full staging review. Thanks!

**Comment by bridgethapner** [comment]
Hi there @DanielleThierryUSDSVA ! I have added you to a Mural board labeled **Mobile App: Content** that has screenshots of the Claims File Upload flow and the work Meli is doing around TTY. Please let me know if you have any issues accessing it. As a heads up, @msmanak will be refining the Claims File Upload UX, so what we have in the Mural will change. But I still wanted to go ahead and share what we have now, thinking that it would be beneficial for UX & content to work together closely on this flow.

**Comment by bridgethapner** [comment]
I also just want to loop in @ayushchak, our Product Lead, into this ticket for visibility! Ayush, Danielle is helping us refine and revise content across the app :tada: We are using a combo of the old Invision prototype + a Mural board to show Danielle the app.

**Comment by bridgethapner** [comment]
@DanielleThierryUSDSVA Hi there - After our work session on Friday 3/12, I made a new ticket (#22110) capturing a list of the areas we discussed following up on. Is it ok with you if I close this ticket, and we shift over to working from that ticket on the remaining areas?

**Comment by bridgethapner** [comment]
Closing this ticket in favor of #22110.
