### ISSUE TITLE
Update phone number format

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#18772]
## Acceptance Criteria
1. Update the formatting of a saved phone number so the area code does not include the parens: (  ) 
     - Example of a correctly-formatted phone number: **212-555-8797**
2. Apply this change across all 4 phone number types (home, work, cell, fax)

## Context for this ticket
This change is to match the mobile app with the web app's implementation. Screenshot taken from web app:![Screen Shot 2021-01-27 at 11.39.14 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/208479d8-195b-4ee7-b135-1c8fb5308274)

**Comment by bessgreen** [comment]
@bridgethapner the designs indicate that there should be a dash after the parenthesis: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636868

Can you confirm if the designs & current implementation are correct? Or should we omit the dash after the parenthesis, as indicated in the bug description above?

**Comment by bessgreen** [comment]
@lexicalninja input from @bridgethapner: "I checked VA.gov, and we should keep the dash and remove the parens."

Assuming we want to make this change, I will update the description of this ticket to remove the parens, and keep the dash.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/8/2021 - Looks good on both Android and iOS.
