### ISSUE TITLE
New subdomain.va.gov header and footer

### ISSUE THREAD

**Issue by andrewlewandowski** [department-of-veterans-affairs/va.gov-team#1877]
## High Level User Story
As a user on a VA.gov subdomain or web application not hosted on the primary VA.gov domain, I need a new header and footer so I can get access to VA.gov and federally required links.

## Hypothesis/(es)
**If** we research, design, and build a secondary header and footer **then** we expect customer satisfaction scores to increase because the VA digital ecosystem will become more consistent and easier to navigate between experiences.

## Goals
_What outcome(s) do we want to see?_ 

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`, `Automation + Instrumentation`, `Support`, `Capacity-building`)

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by jenniferlee-dsva** [comment]
@Karak888 -  I'm updating this epic/issue with clarifying information. This epic is essentially a continuation of the WBC header/footer injection that began with VA.gov Nov 2018 launch. 

Purpose is to provide a more consistent, unifying user experience on legacy subdomain areas of the VA website -- something.va.gov. This is in addition to (and on the way towards) much longer term solution of providing Drupal templates. 

This is primarily an engineering epic, no design work. 

History
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/64e5b99f39fad7551b08d5b4da7141b56128e0f4/VA.gov%20Relaunch%202018/Teamsite/ProductOutline.md

Tasks
1/ Compile a list of subdomains that currently don't have and need the official header and footer. We will focus on the areas that are currently in our About VA mega menu.
2/ Give list to Platform team (please cc @JeffBarnesUSDS  for awareness) to work with Josh Tuscher to prioritize and add injection work into their backlog. 

FYSA @batemapf @JeffBarnesUSDS @leahbannon @andrewlewandowski

**Comment by Karak888** [comment]
headr footer injection to other areas of VA.gov - received spreadsheet and will be reviewing with @jenniferlee-dsva @JeffBarnesUSDS  FYSA @batemapf @leahbannon

**Comment by jenniferlee-dsva** [comment]
Josh Tuscher's triage of legacy pages for header/footer injection attached. Jeff Barnes and I are going over with him next week. 

[subdomain_header_footer_audit-v2-101819-jt.xlsx](https://app.zenhub.com/files/133843125/8cd20c23-d80b-4f0a-9c12-57769d9ad51b/download)

**Comment by Karak888** [comment]
FYA @jenniferlee-dsva

**Comment by jenniferlee-dsva** [comment]
This ticket can be closed. I have sent Josh's subdomain spreadsheet to the Platform team to implement injection. That work is tracked here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5086 

Tasks
[x] 1/ Compile a list of subdomains that currently don't have and need the official header and footer. We will focus on the areas that are currently in our About VA mega menu.
[x] 2/ Give list to Platform team (please cc @JeffBarnesUSDS for awareness) to work with Josh Tuscher to prioritize and add injection work into their backlog.
