### ISSUE TITLE
Apply new VA.gov page navigation and menus to benefit hubs

### ISSUE THREAD

**Issue by andrewlewandowski** [department-of-veterans-affairs/va.gov-team#1878]
## High Level User Story
As a user on one of the 9 benefit hubs, I need new on-page navigation and menus so I can get to all hub content in 1-2 clicks/taps.

## Content work
* We will need to move up any content pages that are published at the 5th and 6th levels up (the new section navigation only allows for four levels: spoke (no content), parent page, child page, grandchild page

## Design work
* We may need to adapt our new page navigation and menus for the benefit hubs

## Hypothesis/(es)
**If** _we make this change_ **then** _we expect this to happen_.

## Goals
_What outcome(s) do we want to see?_ 

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`, `Automation + Instrumentation`, `Support`, `Capacity-building`)

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by Karak888** [comment]
associated epic onpage navigation and Menu for Pittsburgh - that work will be applied to benefit hubs.  

@Karak888 IA placeholder - deep levels of navigation 
change on page nav so we only allow 3 /4 levels of pages 

begin to identify pages below levels 3/4 and bring them up to surface to level above. 

@jenniferlee-dsva will add some examples and tickets will come out of this epic to work. 

Kick - Off will need to be done on hub by hub navigation @ncksllvn @kelsonic will need drupal access to look into things on CMS.

**Comment by Karak888** [comment]
@Karak888 to create a ticket to do audit benefit hub URL that need to be moved up a level to (3 OR 4, @jenniferlee-dsva to find out from Andy)
