### ISSUE TITLE
EDU: Update YTD Report Distributions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18787]
As an Education Services Team member, I need the email distributions for the YTD reports to be updated so that people who are no longer on the project are not receiving unnecessary emails.

## Assumptions:
1. This work does not require a prod or feature flag.

## Acceptance Criteria:
1. The staging YTD report distribution contains the following recipients:
    - Brian.Grubb@va.gov
    - Joseph.Preisser@va.gov
    - Lucas.Tickner@va.gov
    - tammy.hurley1@va.gov
    - Ricardo.DaSilva@va.gov
    - kyle.pietrosanto@va.gov
    - matthew.ziolkowski@va.gov
    - Michael.Johnson19@va.gov
    - lihan@adhocteam.us
    - Delli-Gatti_Michael@bah.com
    - neel_darrell@bah.com
    - shawkey_daniel@bah.com
    - sonntag_adam@bah.com
    - turner_desiree@bah.com

2. The production YTD report distribution contains the following recipients:
    - 222A.VBAVACO@va.gov
    - 224B.VBAVACO@va.gov
    - 224C.VBAVACO@va.gov
    - Brian.Grubb@va.gov
    - Joseph.Preisser@va.gov
    - Lucas.Tickner@va.gov
    - tammy.hurley1@va.gov
    - Ricardo.DaSilva@va.gov
    - kyle.pietrosanto@va.gov
    - Joshua.Lashbrook@va.gov
    - shay.norton@va.gov
    - Brandon.Scott2@va.gov
    - Christina.DiTucci@va.gov
    - John.McNeal@va.gov
    - kathleen.dalfonso@va.gov
    - michele.mendola@va.gov

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5801

**Comment by delli-gatti-michael** [comment]
lgtm
