### ISSUE TITLE
Update cypress-testrail-reporter plugin to latest version

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18781]
## User Story

As a QA resource on a VSP / VFS team, I need the latest version of cypress-testrail-reporter in order to get access to recent bugfixes and enhancements.

## Expected Behavior
The latest cypress-testrail-reporter is able to communicate with our TestRail instance and insert execution records.

## Acceptance Criteria

- [x] Dev dependencies have been updated to reference the latest version of cypress-testrail-reporter plugin.

**Comment by holdenhinkle** [comment]
PR for `vets-website` - https://github.com/department-of-veterans-affairs/vets-website/pull/16049
PR for documentation update - https://github.com/department-of-veterans-affairs/va.gov-team/pull/19957

**Comment by holdenhinkle** [comment]
PRs have been merged. This task is complete.

**Comment by pjhill** [comment]
Confirmed
