### ISSUE TITLE
EDU: Update Spool Submission Report Email Distributions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18788]
As an Education Services Team member, I need the email distributions for the spool submission reports to be updated so that people who are no longer on the project are not receiving unnecessary emails.

## Assumptions:
1. This work does not require a prod or feature flag.

## Acceptance Criteria:
1. The staging Spool Submission Report distribution contains the following recipients:
    - Brian.Grubb@va.gov
    - Joseph.Preisser@va.gov
    - Lucas.Tickner@va.gov
    - tammy.hurley1@va.gov
    - Ricardo.DaSilva@va.gov
    - kyle.pietrosanto@va.gov
    - lihan@adhocteam.us
    - Delli-Gatti_Michael@bah.com
    - Darrell.Neel@va.gov
    - Neel_Darrell@bah.com
    - shawkey_daniel@bah.com
    - sonntag_adam@bah.com
    - Turner_Desiree@bah.com

2. The production Spool Submission Report distribution contains the following recipients:
    - Brian.Grubb@va.gov
    - Joseph.Preisser@va.gov
    - Lucas.Tickner@va.gov
    - tammy.hurley1@va.gov
    - Ricardo.DaSilva@va.gov
    - kyle.pietrosanto@va.gov
    - Joshua.Lashbrook@va.gov
    - shay.norton@va.gov
    - dana.kuykendall@va.gov
    - Jennifer.Waltz2@va.gov
    - kathleen.dalfonso@va.gov
    - lihan@adhocteam.us

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5801

**Comment by delli-gatti-michael** [comment]
lgtm
