### ISSUE TITLE
Files have non-public URL in Jenkins

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18791]
## Details 

Related to Slack thread: https://dsva.slack.com/archives/CQH357ZTP/p1611075264039400

Key piece of conversation pasted in comment below. 

## Definition of Done

- [ ] Files in Jenkins use public URL
- [ ] CMS build finishes successfully in Jenkins
   - [ ] And/or, any new issues discovered are documented on a separate ticket

**Comment by meganhkelley** [comment]
Bill Fienberg  1 day ago
This TODO is one year old. Does it still need to be done? Is it still relevant?
const transform = entity => ({
  // TODO: Change this to get the actual derivative from the CMS export data
  url: getDrupalValue(entity.uri) ? getDrupalValue(entity.uri) : '',
  filename: getDrupalValue(entity.filename),
});
Source: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/process-cms-exports/transformers/file.js#L4 (edited) 

Jhonny Gonzalez  24 hours ago
right! I did that for the images

Jhonny Gonzalez  24 hours ago
we need to do it for files too

Bill Fienberg  24 hours ago
So what you did for images also needs to be done for other file types (specifically, PDFs)?
If so, do you think we should a create a ticket for that work?

Bill Fienberg  24 hours ago
Is this the derivative transformation you wrote for images (media-image)?
https://github.com/department-of-veterans-affairs/vets-website/blob/a18df6814aca6d[…]te/stages/build/process-cms-exports/transformers/media-image.js
src/site/stages/build/process-cms-exports/transformers/media-image.js:15-19
    derivative: {
      url: encodeURI(entity.thumbnail[0].url.replace('public:/', '/img')),
      width: entity.image[0].width,
      height: entity.image[0].height,
    },
Show more
<https://github.com/department-of-veterans-affairs/vets-website|department-of-veterans-affairs/vets-website>department-of-veterans-affairs/vets-website | Added by GitHub

Jhonny Gonzalez  24 hours ago
We might need a ticket for that
:+1:
1

Bill Fienberg  24 hours ago
Would you like me to create the placeholder ticket, and you can add/edit the details?

Jhonny Gonzalez  24 hours ago
Sure

Christopher Valarida  24 hours ago
Done? I think @Theo Bentum fixed it already, but forgot to remove the comment. :disappear:
2 files 
image.png

image.png

:+1:
1

Jhonny Gonzalez  23 hours ago
I think we still need derivative so we can override the path with a public one

**Comment by jhonnyoddball** [comment]
We need to find out where is Jenkins getting the main path from

**Comment by meganhkelley** [comment]
Update — this is essentially finished but not yet merged

Related to (blocking) #18408
