### ISSUE TITLE
Error | Photo exceeds max size

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18798]
## User story
As a user, I want to know when I cannot upload a photo to my claim because it exceeds the maximum file size. 

**Notes for dev:** 
- No designs for this error state. Please reference all AC for copy. A similar design for a different error state is linked below to cross-reference. 
- The total limit for **all photos** uploaded cannot exceed 50 MB
 
## Acceptance Criteria
1. Create UI for an error state when a photo cannot be added to the upload screen because it exceeds the total limit of 50 MB (either because the photo itself is >50 MB, or because other photos have already been uploaded and this photo will push the sum of all photos over the 50 MB total limit) 
2. This error state appears after a user has selected a photo from their gallery or taken a photo with their camera. It displays on either of these pages: 
     - [**Take photos - no photos added**](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18584)
     - **[Take photos - with photos added, variation 2](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18603)**. This error should only appear when 1-9 photos have been added (variation 2). It should not appear if a user has successfully uploaded 10 photos (variation 3).
3. Pull in mobile alert CC 
     - Left border: #CD2026
     - This alert appears at the top of the page, below Header 1 and above Header 2
4. Copy: "This file cannot be added because it exceeds the maximum file size. You have used [#] MB of the 50 MB limit."
     - Second sentence: the [#] should reflect the total size of all files that have **successfully been uploaded** to the screen. This # does **not** include the size of the file that they unsuccessfully tried to add
     - Copy is unbolded
5. This error state persists until the user navigates away from the page

## Designs
Similar error state: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/439369081
![Screen Shot 2021-01-20 at 5.21.41 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/52288947-8ff7-4c04-a22e-b1fb9ce741cd)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
FAIL UI/UX - Error mobile alert is not placed in correct location according to designs, both Android and iOS.  
Bug entered:  
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19095

**Comment by digitalken** [comment]
PASS 1/28/2021 both UI and accessibility.
