### ISSUE TITLE
Design of COVID-19 vaccination form 

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#18796]
# User Story
As a user of the VA mobile app, I want to be able to sign up for regular updates on how VA is providing vaccines across the country.

**Comment by ayushchak** [comment]
Doesn't have the logic of .gov on error states, front-end validation, etc. Form design is also probably changed, getting aligned with what is on the web.

**Comment by bridgethapner** [comment]
Closing this as we've decided to move forward with linking to the website
