### ISSUE TITLE
Access for Matt Leclerc

### ISSUE THREAD

**Issue by mleclerc00** [department-of-veterans-affairs/va.gov-team#18793]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Matt Leclerc
- Please Provide your email.
   > matt.leclerc@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA VSP, Software Engineer, AdHoc

- Requesting SSH key authorization?
   > YES 
- What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5YihPv970E9MgW2VyBfkuWc4ND2H7yhH+AXwGN1deMFDQ2A9F70QZpEY7hQWbSbJWDztInHbyzwuiYN2r+4N0TQ2Lt24KZshGOeuw9XKVXIKV1UVK688EfBqLMk216rKrz+mS/zY8p6XNwavnvfcLlMvt730VMUyTJSGltMEunhCo8ddAVWIEJX4JsktC+P1eFr/chxzAnKgz5poSj6zMHooK+LECpfwYaFctoTvsYRpKsrlI4b68YZPy0Bj1vMg5yj/sL3WjQ9YhyBNRmipSdQ7pnqsrXPx2q8kOiWazl7KcrrsTOFKUI3F9AqHbEhLgxbBLU47yDmypY9HyLYPYQtxnagvpi8loHnT+RXlJg/fEP0rT92QqYc+zTlhBtNnQnJBKJpSsJTdzvuL9lfO2u3pU5XIKJRngszFk0HhXxzA5vE8vgk5Etyio6RriOTR1mFEWUKM7SIuwCC9I4Z9MzVl/THlS+O0UhDcNDBS/vvc8klZfF1ed+EqBH69z7rM= mattleclerc@Matt-Leclerc-Macbook.local
```

- Grant AWS Console access?
  > YES
- What AWS services do you need access to and why? 
  >  Access for Software Engineer related services in order to perform work duties expected of the VSP team.

**Comment by tskinn** [comment]
@Jeff-Hayter 
Name: Matt Leclerc
COR: Jeff

**Comment by tskinn** [comment]
@mleclerc00 you should be able to connect to the socks proxy now. Reach out in slack if you have issues.

Once Jeff gives the signal we can give you AWS access.

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS.
