### ISSUE TITLE
Access for Ron Tafoya - VAMC-Upgrade team - GovernmentCIO

### ISSUE THREAD

**Issue by ronrtafoya** [department-of-veterans-affairs/va.gov-team#18792]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product. Access needed for: dev, staging, prod, CI environments and Jenkins.
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Ron Tafoya
- Please Provide your email.
   > rtafoya@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA-VAMC-UPGRADE/VAMC-UPGRADE, Role: Digital Content Editor-Writer, Company: GovernmentCIO

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX8KLJJr1XV/8K5vcQywGlUVhrntVrKQOYZ/cpBLFvTu7CpCPB8mjkxjz4SPwKytL7IVpghznFqGGUX52P6weO9XQt736WP3w9xB3AQUuUiB7yXUfqUBK+63XbSs4Rwlt+F5eMia0BpTAMGDkZI/D1bIes1r2wsrp2IJ/YatGFb3mCVLmWJK06oYBNT2Kqw0SdZ7DmpJMQ0+8xvYPk8WYM9OBHgnXuwaEjHZrspJJll8B8zXaCfngMkvvfGChfRMOEvHf6TJK2U7N9lacCJr+tYmLkqQ/R5DmR5oHn9KgamlxWuwoAoRPr5mambXQdGedaWmsKH4zsLJhDKwnz1QBpULPl+5eeHfCErFjJzsc1AtDjP3yy2/b8GxCOzKMlXyBDCSFV+RDWlX0pkSiV/M3JDMiTShF/LaMkuorrbYcwY0XaGDzfcQngRbKGQbLTzEkogKIODtRGSAN0tmvdiMBjDcCjzGtg4Y2yUeK40PxG2kt+o0ft23RdXAjkJ0wF9hs= rontafoya@Rons-MacBook-Pro.local

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why? Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product. Access needed for: dev, staging, prod, CI environments and Jenkins.

**Comment by tskinn** [comment]
@ronrtafoya You have posted the your private ssh key to a public repository. You need to regenerate an ssh key and remove the one you have posted here from any where that it is being used immediately.

You should only post your public key here. Thanks.

**Comment by ronrtafoya** [comment]
I replaced the text with the public key, sorry about that.

**Comment by tskinn** [comment]
No worries, it happens. Thanks for updating!

**Comment by tskinn** [comment]
@ronrtafoya you should be able to connect to the socks proxy now. If you have issues connecting reach out in slack. Thanks
