### ISSUE TITLE
Create a starter template that creates a "Hello, World!" endpoint

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#188]
## User Story
As a VSP developer I want a started template that I can clone/generate so that I can see how a bare bones app is wired up in vets-api

## Acceptance Criteria
You can clone a repo or run a generator that creates a simple rails engine to add a basic endpoint to vets-api. The template should create all things, model, controller, serializer etc potentially with options for resources that live in vets-api (Postgres via ActiveRecord) vs remote resources (response object via upstream api)

**Comment by batemapf** [comment]
@kreek would it be helpful to have a non-VA.gov dev (or two) test out what you've put together? Might have a couple of new USDS engineers available...

**Comment by kreek** [comment]
@batemapf that'd be great, have a couple things to clean up (should be done today) but once that's done people could start trying it out.
