### ISSUE TITLE
Error | File exceeds max size

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18804]
## User story
As a user, I want to know when I cannot upload a file to my claim because it exceeds the maximum file size. 

**Notes for dev:** 
- No designs for this error state. Please reference all AC for copy. A similar design for a different error state is linked below to cross-reference. 
- In the file upload flow, only 1 file can be added. This file cannot exceed 50 MB.
 
## Acceptance Criteria
1. Create UI for an error state when a file cannot be added to the upload screen because it is greater than 50 MB
2. This error state appears after a user has selected a file from their device's file folder or camera roll. It displays on the following page: **[Select a File - no files added](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18596)**
3. Pull in mobile alert CC 
     - Left border: #CD2026
     - This alert appears at the top of the page, below Header 1 and above Header 2
4. Copy: "This file cannot be added because it exceeds the maximum file size.”
     - Copy is unbolded
5. This error state persists until the user navigates away from the page

## Designs
Similar error state: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/439369081
![e12842eb-6fa7-4653-95cf-bce084abaf64 (1).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/048498c3-6600-414a-a66a-bc9e7a70bc09)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 1/28/2021 - Both Android and iOS.
