### ISSUE TITLE
[Design] Homepage research synthesis

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18802]
Synthesis will be saved in the research folder when it's complete: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/research/jan-2021-appts-list-test

**Comment by outerpress** [comment]
Research is complete, report is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/jan-2021-appts-list-test/report-out.md

@laurenernest I'll put some time on your calendar so we can run through and talk about next steps. Feel free to add anyone else who you'd like to attend.
