### ISSUE TITLE
Content review: VAOS tool in staging

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#1881]
## User Story or Problem Statement
As a member of a team building with or on VSP, content needs to be reviewed to ensure it's accurate, aligns with VA style, and is error-free. 

## Goal
Peggy reviews VAOS tool on staging ensure plain language and screens follow VA.gov content styleguide. 

Research synthesis doc:
https://www.figma.com/file/2VX8fV3vdJyxHbwt2fzUG5/Self-Schedule-Synthesis?node-id=0%3A2463 (edited) 
FIGMA doc:
https://www.figma.com/file/KGChcQHMrTReo7T7cML418/VAOS-Flow?node-id=0%3A1
https://www.figma.com/file/KGChcQHMrTReo7T7cML418/VAOS-Flow?node-id=66%3A0

**Comment by peggygannon** [comment]
**9/30/19 update**

Meeting with VAOS team to sync on content needs/areas to focus on for the prototype.

**Comment by rtwell** [comment]
https://vsateams.invisionapp.com/share/USU2W52K37A

**Comment by peggygannon** [comment]
VAOS content review on staging is complete. Dev implementation tickets have been created for the edits.
