### ISSUE TITLE
Consider moving breadcrumbs and adding a My VA button in profile

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#18815]
Since we are updating the nametag in profile to match the nametag in MyVA, we need to consider if we need to update the rest of the elements to be consistent with MyVA. Specifically this includes:

- moving where the breadcrumbs to be below the nametag
- And adding a My VA button

All changes are shown in the screenshot below. 

![Screen Shot 2021-01-21 at 10.13.07 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/60bcf007-dbe5-4563-8f10-a7726fc53214)

**Comment by Samara-Strauss** [comment]
If we pursue this, note that it would be a link, not a button, per the final My VA design.

**Comment by Samara-Strauss** [comment]
We have already removed the profile bread crumbs, and we are not going to add a button that goes to My VA. Closing.
