### ISSUE TITLE
Remove feature toggles + legacy content (Auth/Unauth Cerner Pages) 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#18821]
## Issue Description
_We need remove the feature toggles + legacy content from the unauth/auth Cerner pages as we don't want the old legacy content_

[Slack Convo](https://dsva.slack.com/archives/C52CL1PKQ/p1611246851010300?thread_ts=1611237927.001400&cid=C52CL1PKQ) for Reference 

<img width="721" alt="Screen Shot 2021-01-21 at 9 47 15 AM" src="https://user-images.githubusercontent.com/70410912/105383323-3d041380-5bce-11eb-8b94-03ec204d20f4.png">

## Front end tasks
- Provide estimate and remove 'needs grooming' label
- remove toggles and legacy content from Cerner pages 

## Acceptance Criteria
- [ ] Validate toggles are removed 
- [ ] Legacy content is removed from Cerner pages (old legacy content)
- [ ] Site and content are functioning properly post removal

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
FE PR is open: https://github.com/department-of-veterans-affairs/vets-website/pull/16110/files

**Comment by kelsonic** [comment]
Oh gosh, I just noticed that those feature toggles are heavily in use on the vaos team I think, so I won't be sending up a BE PR to remove them

**Comment by brianalloyd** [comment]
Thanks @kelsonic moving this to Validate and will close out once PR has merged.
