### ISSUE TITLE
KPI Dashboard Request for [VAOS - Community Care Provider Selection MVP]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#18828]
## Request
New Domo dashboard specific to work related to the Community Care Provider Selection initiative.

---

### Initiative Overview
Title - Community Care Provider Selection
Objective - Improve the Community Care provider selection experience

KPI - Completion of provider preferences step(s)
KPI - Community Care request submissions

- [ ] Funnel for full flow (app homepage to submission)
  - eventLabel = 'vaos-schedule-appointment-button-clicked'
  - www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/
  - eventLabel = 'vaos-community-care-path-started'
  - www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/request-date/
  - www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/community-care-preferences/
  - www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/community-care-language _(new page step in funnel)_
  - www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/reason-appointment/
  - www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/contact-info/
  - www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review
  - eventLabel = 'vaos-community-care-submission'
  - eventLabel = 'vaos-community-care-submission-successful'

- [ ] Count + Editable date range of `vaos-cc-eligible-yes` event

### Provider Preferences Original
- [ ] Count + Editable date range of selection of 'yes' on page
- [ ] Count + Editable date range of facility locator selection on page
- [ ] Count + Editable date range of Continue with 'yes' selection
- [ ] Count + Editable date range of Continue with "no preference" selection

### Provider Preferences New (Selection)

- [ ] Bar chart (position, count) order position of provider selection
- [ ] Count + Editable date range of provider list pagination clicks
- [ ] Count + Editable date range of "Choose a provider" clicks per user session
- [ ] Count + Editable date range of Continue with no provider selected
- [ ] Count + Editable date range of Continue with provider selected

### Submissions
In `vaos-community-care-submission` event:

- [ ] Bar chart (number of preferences, count) for number of preferred providers user requests `vaos-number-of-preferred-providers`
  - _Note - only expecting to see 0 or 1 with MVP. could go up to 3 in further iterations._
- [ ] Bar chart (languages, count) for language preference selected in requests _param TBD_
- [ ] Table of success/fail submissions
- [ ] Table of submissions by type of care ([GA comparable](https://analytics.google.com/analytics/web/#/dashboard/bhah2LQPRrKpwVq7lknoWg/a50123418w177519031p176188361/))

### Staged Rollout
**Funnel comparison**
[Release plan
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/cc-provider-selection-release-plan.md)

| Current | New |
| ---------- | ---------- |
| eventLabel = `vaos-community-care-legacy-provider-page` | eventLabel = `vaos-community-care-provider-selection-page` |
| www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/reason-appointment/  | www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/community-care-language |
| www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/contact-info/  | www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/reason-appointment/ |
| www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review  | www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/contact-info/ |
| eventLabel = 'vaos-community-care-submission'  | www.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review |
| eventLabel = 'vaos-community-care-submission-successful'   | eventLabel = 'vaos-community-care-submission' |
|  | eventLabel = 'vaos-community-care-submission-successful' |

---

## Additional Notes
Dev tickets: #15834, #15990, #16248, #16487, #19304

**Comment by jonwehausen** [comment]
Thanks @laurenernest , we will triage and get back with you

**Comment by joanneesteban** [comment]
@laurenernest - thanks for opening this! Question: are you looking for an update to your existing funnel or for a new funnel?

**Comment by laurenernest** [comment]
@joanneesteban for this one, new funnel so we can see the whole picture from start of appointment, and there's a new step to compare.

**Comment by laurenernest** [comment]
@joanneesteban I added a "Staged Rollout" section to help track metrics as we launch. Let me know if you need me to split out into a separate ticket.

**Comment by laurenernest** [comment]
@joanneesteban Do you think this work will be done by EOD 2/17? I'm trying to determine how much I'll need to set up myself in GA to track our canary test.

**Comment by joanneesteban** [comment]
@laurenernest 
apologies, this fell under the radar for our team, and we'll need to push the Domo creation back. Do you need support finding the data in GA?

**Comment by joanneesteban** [comment]
Moving the Domo dashboarding side of this back to our backlog until we're able to pull this in.

**Comment by laurenernest** [comment]
@joanneesteban Here's the GA ticket. Thanks for the help! #20155

**Comment by joanneesteban** [comment]
@laurenernest checking in on this one too. Is this info captured in https://github.com/department-of-veterans-affairs/va.gov-team/issues/26851?

**Comment by laurenernest** [comment]
@joanneesteban The funnels are captured in #26851, but not the other details. I think I can get them in GA so closing ticket.
