### ISSUE TITLE
[Discovery] Look into load time for design system REACT components

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18826]
## Issue Description
There have been reports of load time being very slow that could be due to DS REACT components. Look into load time for design system REACT components

---
## Tasks
- [ ] Discovery

## Acceptance Criteria
- [ ] Findings and recommendations on ways to reduce load time. 
---

**Comment by caw310** [comment]
We should gather information so we can identify how the DST will address this issues. 
Figure out how much of this is a DS issue.

**Comment by k80bowman** [comment]
Original discussion thread from January 20, 2021 is here: https://dsva.slack.com/archives/CBU0KDSB1/p1611179049258500

**Comment by k80bowman** [comment]
The web-components bundle that is loaded on every page is quite large. According to webpagetest, it takes 872ms to download the web-components.entry.js file. It is 135.7kb compressed (509.1kb uncompressed).

Here is the treemap:
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/7ef2fcf6-556b-4c1a-9252-c2968b59541c)

Google's Lighthouse tool says that we could get rid of 93.4kb of unused JS:
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/4c1dcfab-1e3f-4e74-9c91-cf5a122c9013)
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/84b1d600-2f28-49b4-a3da-6a3cd2932169)

There are definitely some things we could do to reduce the size of this file.
- Get rid of moment.js
    - Brooks has an old [PR](https://github.com/department-of-veterans-affairs/component-library/pull/39) here.
    - There have been some [concerns](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22635) in the past about moving from moment to datefns, but those may not be valid anymore, at least not for the component library.
- Update react-components to use an actual bundler like webpack or rollup (which is what we're using for the web-components)
- Audit dependencies -- there are several dependencies we are importing and then only using a small part of
    - Lodash
    - datefns (is this necessary? How much can we accomplish just using native JS date functions?)

**Comment by k80bowman** [comment]
- Moved  #19954 from icebox to Reviewed/Needs Prioritizing and added link to existing PR
- Created #33187
- Created #33188
