### ISSUE TITLE
Main facility appointment phone number is not displayed when needed

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18824]
## Issue Description
In two places (Critical care and Patient advocates accordions) on the [University drive staging environment](https://staging.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/), the appointment phone label appears without a phone number. 
- CMS indicates to use the general facility phone number 

When the "use main phone number" box is checked, GraphQL should get the facility phone number and display on the front end.

![image](https://user-images.githubusercontent.com/55411834/105764442-2fbf8f80-5f14-11eb-9a4d-359391de3d8d.png)

---
## Tasks
- [ ] Modify liquid template logic to display the main phone number (`fieldPhoneNumber` ) if `fieldUseMainFacilityPhone` is true AND `fieldPhoneNumbersParagraph` is empty.

## Acceptance Criteria
- [ ] When the editor indicates the main facility number should be used, and there is no location-specific number, the main number is rendered on the front end.

**Comment by swirtSJW** [comment]
This phone number resides with the parent.  It  does not reside on the facility service node, so it has to be grabbed from the parent during the build of the page on the front end.

**Comment by mmiddaugh** [comment]
This may also require a transformer. Too soon to tell.

**Comment by brangi** [comment]
@mmiddaugh @swirtSJW is this **"main phone number"**?

<img width="1249" alt="Screen Shot 2021-01-26 at 3 55 55 PM" src="https://user-images.githubusercontent.com/100468/105910911-33741480-5fef-11eb-8354-032a7957776e.png">

**Comment by brangi** [comment]
> ~The phone number should be sent from CMS to the front end~
> When the "use main phone number" box is checked, GraphQL should get the facility phone number and display on the front end

How does the frontend knows that the box is checked, is there any boolean value to check?

**Comment by mpelzsherman** [comment]
The boolean value to check is `fieldUseMainFacilityPhone`.

**Comment by mpelzsherman** [comment]
I checked the [transformer](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/process-cms-exports/transformers/paragraph-service_location.js#L30) and confirmed that `fieldUseMainFacilityPhone` is already being populated. There should be no need for any additional transformer work for this ticket.

**Comment by mmiddaugh** [comment]
Looks good to me, @brangi
