### ISSUE TITLE
Project Kickoff - Decision Tools - Find a VA Form Sorting

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18838]
## Steps to complete Project Kickoff
- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all relevant artifacts to the ticket
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline [Find a VA Form Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/README.md)
- We are adding a sorting feature to the Find a VA Form product
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **Decision Tools**
- Product Manager (required): **Marci McGuire**
- DEPO Product Lead (required): **John Hashimoto**
- Entire VFS team (recommended): **Zachary Morel (FE), Laurel Lawrence (Design)**
- Other specialists: **Josh Kim, Tze-chiu Lei, Selina Cooper or Laura Walsh (content)**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** NO

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now  
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite  **Monday, Jan 25 at 3:30 PM**
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

**Comment by tlei123** [comment]
[TEST-ONLY] Tagging myself to double-check email-notification settings.  @tlei123 @tzelei

**Comment by tlei123** [comment]
@MarciMcGuireGCIO , once you have an Epic for the Sorting work. Please let me know.

Thx much, and sorry I missed the Kickoff mtg!

**Comment by shiragoodman** [comment]
@tlei123 the kickoff is on Monday 1/25. you should have an invite :)

**Comment by tlei123** [comment]
> @tlei123 the kickoff is on Monday 1/25. you should have an invite :)

Oops, sorry @shiragoodman / @MarciMcGuireGCIO !  Got this mixed up w/ the Yellow Ribbon mtg I missed!  :D

**Comment by MarciMcGuireGCIO** [comment]
@tlei123 same app, slightly different ticket.  LOL

**Comment by shiragoodman** [comment]
Hi @MarciMcGuireGCIO . Thanks for meeting with us today. Because you're already at the end of your build, here's what we recommend:

- Staging Review (just create a ticket when you're ready to schedule)
- Privacy & Security Review
- Please reach out to [Contact Center](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md) team to see if your Product Guide and/or Product Video will need to be updated.

Please let me know if you have any questions. The Platform Collaboration Point Tracker has been updated.
