### ISSUE TITLE
Research: 10-10EZ multiple address not auto-filling unless both addresses are present

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#18832]
## User Story

As a Veteran
I would like as much profile info as possible to be auto-populated
so my application process is more streamlines and do not have to duplicate data entry efforts

## Two addresses
1. Login as a veteran with both mailing and home address on their profile
1. Go to 10-10EZ form
1. Mailing address and home address are populated

### One address
1. Login as a veteran with only mailing address in their profile
1. Go to 10-10EZ form
1. Mailing address is not populated

## Expected Behavior
- A veteran with only mailing address in their profile will have that mailing address populate on the 10-10EZ

## Goal 
- [ ] Understand why auto-fill isn't working with Veteran profiles that have only one address

## Acceptance Criteria

- [ ] Document how to reproduce the issue in Staging (with test accounts)
- [ ] Submit to VSP/ VA profile for feedback
- [ ] Document steps for reproduction locally
- [ ] Create a followup ticket for resolution based on feedback

**Comment by mchelen-gov** [comment]
@kevinmirc @LinnJS updated with my best understanding of current & expected behavior, please correct as needed

**Comment by LinnJS** [comment]
Yesterday was having issues replacing profile information on localhost even when running vets-api natively. Turns out there is a hard coded redux action [here](https://github.com/department-of-veterans-affairs/vets-website/blob/827bebb9ab73d1ac34b8423e4ad7244155d7710a/src/platform/user/profile/vap-svc/util/local-vapsvc.js#L104-L128) Met with Sandra and Erik from auth exp team and they walked me though where that hard coded data was and how to mock API request in safari.
