### ISSUE TITLE
Scheduled 02/03: Redirect Request: Legacy Pension Rate Pages

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#18837]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
Redirecting legacy pension rate pages to rates pages on va.gov

### Requestor team info
Sitewide Content

### Implementation date
Date new URL(s) will be live: Already live

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing: Seven business days after stakeholder notification

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.benefits.va.gov/PENSION/rates_survivor_pen18.asp | https://www.va.gov/pension/survivors-pension-rates/past-rates-2019/
https://www.benefits.va.gov/PENSION/rates_survivor_pen17.asp | https://www.va.gov/pension/survivors-pension-rates/past-rates-2018/
https://benefits.va.gov/PENSION/protected_pension_rate_tables_pen18.asp | https://www.va.gov/pension/protected-pension-rates/past-rates-2019/
https://benefits.va.gov/PENSION/protected_pension_rate_tables_pen17.asp | https://www.va.gov/pension/protected-pension-rates/past-rates-2018/
https://www.benefits.va.gov/PENSION/rates_veteran_pen18.asp | https://www.va.gov/pension/veterans-pension-rates/past-rates-2019/
https://www.benefits.va.gov/PENSION/rates_veteran_pen17.asp | https://www.va.gov/pension/veterans-pension-rates/past-rates-2018/

### Definition of done
- [ ] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
Redirects are vetted and documented and ready to go when you are.  Please be sure redirects take capitalization into consideration - many legacy pages have varying capitalization (i.e. "PENSION" versus "Pension" versus "pension")

**Comment by lunascoop** [comment]
Hi @kelsonic @ncksllvn here's a legacy page(s) redirect request scheduled for **02/03**. Please see Mikki's comment posted above regarding casing. 

> Please be sure redirects take capitalization into consideration - many legacy pages have varying capitalization (i.e. "PENSION" versus "Pension" versus "pension")

I'll be notifying stakeholders shortly (cc: @bethpottsVADEPO, @brianalloyd )

**Comment by kelsonic** [comment]
PR is up, won't merge until 02/03 👍 https://github.com/department-of-veterans-affairs/va.gov-team/issues/18837

**Comment by kelsonic** [comment]
PR merged! Redirects will go out with the daily deploy today 💯

**Comment by lunascoop** [comment]
Redirects are live and working as they should. Sending final notification to stakeholders and closing ticket. Thanks @kelsonic (cc: @ncksllvn @brianalloyd @bethpottsVADEPO @mnorthuis
