### ISSUE TITLE
[Product/Research] - What should the experience be for Veterans with a pre-existing health care application?

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18848]
**Goal**

What should Veterans with a pre-existing health care application be able to do on VA.gov? Submit a new form? See another message?

Relates to: #18731

**Comment by mlighdc** [comment]
@ala-yna and @kevinmirc - what is the status of this ticket? What needs to happened as a next step to see if we keep this open or closed.

**Comment by ala-yna** [comment]
@tchrisdyer / @Dene-human  - this might be something to ask about in the next conversation with the health care team.

**Comment by hdjustice** [comment]
Closing this ticket - has not been addressed in over a year.  If work is needed, a new ticket will be created under an initiative.  There is an open ticket for improvements to "Already Enrolled" UX #28081.
