### ISSUE TITLE
Provide CD numbers of dropped PDF cases to Caregiver Program team

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18846]
A/C
- Make a combined list of all "dropped" applications
- Ask CARMA to look up the CD numbers

**Comment by kevinmirc** [comment]
There are two sentry "issues" for this error. Most error occurrences are found in [issue 6552](http://sentry.vfs.va.gov/organizations/vsp/issues/6552/events/oldest/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Acaregivers_assistance_claims), and some are in [issue 5207](http://sentry.vfs.va.gov/organizations/vsp/issues/5207/events/oldest/?end=2020-12-08T23%3A59%3A59&environment=production&project=3&query=+controller_name%3Acaregivers_assistance_claims+&start=2020-12-08T00%3A00%3A00&utc=true).

**Comment by ala-yna** [comment]
@kevinmirc should we close this one and open one that speaks to the errors that are coming from Sentry?

**Comment by kevinmirc** [comment]
Yes. I'd say this is complete.

**Comment by kevinmirc** [comment]
For this ticket, we've collected and sent the CD numbers for all the submissions identified by our logs. There are more cases that we've identified from Sentry and the ticket to gather those IDs is located here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19329
