### ISSUE TITLE
Run content-only deploy on a schedule

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18845]
## Details

Run the content-only deploy job (created in #18844) on hourly schedule. 

Design doc: https://github.com/department-of-veterans-affairs/va.gov-team/pull/17304/files

Open questions: 
* Does this only need to happen during "hours of operation"? What about weekends?
   * This would not add significantly more effort 

## Acceptance Criteria

- [x] We observe that the content-only deploy job is running on the scheduled timer (validate day after implementation) 
- [ ] ~Build that is uploaded to S3 matches the build from the pipeline~

**Comment by meganhkelley** [comment]
This job should be run during CMS business hours — 8-8 ET on weekdays.

**Comment by timwright12** [comment]
**Schedule**:

- daily for 1-2 days
- 3 times a day for 1-2 days
- Hourly 8AM - 8PM Eastern

cc @theodur

**Comment by theodur** [comment]
Draft PR for updating cron: https://github.com/department-of-veterans-affairs/devops/pull/8568

**Comment by theodur** [comment]
When we deploy the initial release, we will run the content only deploy daily at 11 AM EST. This gives us and the CMS team time to troubleshoot things that could go wrong before the daily full auto deploy.

**Comment by theodur** [comment]
The [PR](https://github.com/department-of-veterans-affairs/devops/pull/8568) has been approved by devops. Content only deploy is ready to be pushed.

**Comment by meganhkelley** [comment]
@theodur was this acceptance criteria specific to CMS Export? 

> Build that is uploaded to S3 matches the build from the pipeline

**Comment by theodur** [comment]
@meganhkelley Yeah that criteria was specific to CMS export and doesn't apply anymore.

**Comment by meganhkelley** [comment]
1x/day schedule implemented 

Phase 2 ticket #21158
