### ISSUE TITLE
SSN validation occurs for a Caregiver that I've removed from my application

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#18849]
**Description**
When filling out the 10-10CG, the duplicate SSN validation is being executed for a caregiver that I've removed from the application. 

**Reproduction Steps**
1) Start the 10-10CG
2) Select "Yes, I want to enter a PC"
3) Enter same SSN as veteran
4) Go Back to "Do you want to add a PC"
5) Select "No, I don’t want to add PC"
6) Select "Yes I want to enter **SC1**"
7) Enter **any** ssn for the SC1
8) ⚠️ The field will be invalid (says the ssn is used somewhere else)

**Considerations**
- Now that adding caregivers is optional on the 10-10CG, are there other validations that are being run when a caregiver is removed from the app.

**Comment by LinnJS** [comment]
Draft PR just opened [Here](https://github.com/department-of-veterans-affairs/vets-website/pull/16087)

**Comment by LinnJS** [comment]
I noticed what seemed to be a Platform bug when I hit the "Update" button on the review page accordion for a page it does not seem that the "Update" button triggered data validation like you might expect from behavior like the continue button. Feels like you would need to sanitize that data as well. Will bring up with VSP platform support today.

**Comment by kevinmirc** [comment]
I tested this in the RI and it worked as expected. Good to merge :thumbsup:
