### ISSUE TITLE
Project Kickoff: Decision Tools - Yellow Ribbon Filtering Enhancements

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18840]
## Steps to complete Project Kickoff
- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all relevant artifacts to the ticket 
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline ([Yellow Ribbon Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/yellow-ribbon-mvp-product-brief.md))
- We are making improvements to the Yellow Ribbon search product to provide additional filtering options in the hopes that it will help refine and reduce the number of relevant results.
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Marci McGuire**
- DEPO Product Lead (required): **John Hashimoto**
- Entire VFS team (recommended): **Zachary Morel, Laurel Lawrence**
- Other specialists: **Josh Kim, Tze-chiu Lei, Selina Cooper or Laura Walsh (Content)**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** NO

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite **Tuesday, 1/26/2021 at 11:30 AM**
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

**Comment by shiragoodman** [comment]
hey @MarciMcGuireGCIO would you be able to share how this initiative is different than the [Yellow Ribbon Search Improvements?](https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/18565)

**Comment by MarciMcGuireGCIO** [comment]
Hi @shiragoodman, since there is still research & design for the filtering feature I am de-scoping it from this ticket, and have opened separate one solely for the filtering.

**Comment by shiragoodman** [comment]
Hi @MarciMcGuireGCIO . Thanks for meeting with us today. We recommend the following Collab Cycle touchpoints:
- Staging Review
- Contact Center Review (your Product Guide will likely need updating)
- Analytics Request
- Privacy and Security Review

The Platform Collaboration Point Tracker is updated. Please let us know if you have any questions!

**Comment by shiragoodman** [comment]
Also, you can probably do 1 Analytics Request for both initiatives (filtering and search improvements). @joanneesteban let me know if you have questions and I can catch you up.

**Comment by MarciMcGuireGCIO** [comment]
Thank you., Shira!
