### ISSUE TITLE
Create a Recommended Version of the CH31 Content

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#18852]
## Background
We need to provide an alternative to the initially porposoed content from the LoB that is more amenable to the Veteran experience and the design constraints we are wokring within.

## Considerations
Recommendations:

- Orientation is extremely long: Consolidate content into as few ‘slides’ as possible, potentially “doubling-up” sections
- Language will require revision for clarity: Revise copy to align with plain-language mandate
- Align with VA.gov style guide
- Process steps are redundant with summary information
- Drop process slides in favor of summary/process map
- Module is out of context, and orientation info is inaccessible as reference for process:
- Put the orientation module on VR&E content pages; put links on form intro and confirmation page
- Module is a barrier to completing the form: Present a bypass link to users; keep visible throughout orientation
- Consider content going onto its own page and not within the gateway to a form

## Tasks
- [x] Implement a mocked version of the recommendations above that would lead to cleaner, easier Veteran experience

## Acceptance Criteria
- [x] A mockup has been created and is ready to share (Sabrina)

**Comment by sporeboy** [comment]
Revised mocks available here: https://xd.adobe.com/view/76c8e03c-ff8e-498b-ada5-0e2c08a8d8bd-239b/

**Comment by sporeboy** [comment]
Implemented:

- Consolidated content into as few ‘slides’ as possible
- Revised copy to align with plain-language mandate
- Aligned text with VA.gov style guide
- Removed process steps in favor of all-in-one subway map
- Created concept mock for placing wizard/questions on content page
- Created concept mock for placing track-videos content page
- Added a bypass link to users that is visible throughout orientation
- Added title, caption and time for embedded videos
