### ISSUE TITLE
Enable retries for Cypress on CI

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#18853]
Cypress 6 supports retries of failing tests without having to use a plugin. In order to reduce the amount of false failures from flaky tests, we need to enable retries on Jenkins and CircleCI. This should reduce the number of failing builds we see on CircleCI and Jenkins, which will have a significant, positive effect on commits going through the CI pipeline.

[Cypress documentation for retries](https://docs.cypress.io/guides/guides/test-retries.html#Global-Configuration).

**Comment by pjhill** [comment]
[PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/15748)

**Comment by pjhill** [comment]
Retries have been enabled for a while to no ill effect -- hooray! We can address refinement of the retry recommendations in subsequent tickets if necessary.
