### ISSUE TITLE
Refine and Formalize Call Center Review Process

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#1885]
## User Story or Problem Statement

How might we improve the process of notifying call center leads about new features and functionality so that they can take the proper steps to notify call centers prior to a launch. 

## Goal
-Have a clearly defined way for teams to notify the call center lead about upcoming releases that will affect users. 

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [x] Review previous documentation
- [x] Make and changes or adjustments based on current processes
- [x] Document any changes
- [x] Communicate out to VSP and VFS teams and implement process

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@Kimberley2019 Here is the documentation for the process that has in place but not strictly followed. 
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-contact-center-review.md#request-a-contact-center-review

**Comment by Kimberley2019** [comment]
@clantosswett This document is close in nature to the advanced notice document that I have created.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/triage/call-center/advanced-notice.md

Incorporating the two into one document that can be shared with the VSA/VSP teams when we have our introductory meetings would be beneficial, this way it can be implemented.
