### ISSUE TITLE
Optimize the format of the header/footer data for smaller page sizes and quicker startup

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#18864]
## Issue Description
_If you look at view-source:https://www.va.gov/ around line 104... you'll see a huge block of uncompressed JSON. If we removed all that whitespace, we'd save about 20k in size_

<img width="938" alt="Screen Shot 2021-01-22 at 8 56 28 AM" src="https://user-images.githubusercontent.com/70410912/105513588-bca5e700-5c8f-11eb-84dd-ba10e5da0b2a.png">

[Slack Convo](https://dsva.slack.com/archives/CBU0KDSB1/p1611324132077400)

Sort of related, if you’re in there tweaking the formatting of that JSON, this could be a consideration: https://joreteg.com/blog/improving-redux-state-transfer-performance#option-3-turn-your-state-into-js-string-containing-escaped-json

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
Waitin on VSP review for this

**Comment by brianalloyd** [comment]
Thanks @ncksllvn

**Comment by ncksllvn** [comment]
This will go live today but I am debugging something related to this and the preview server. It seems preview-staging is down. 
![image](https://user-images.githubusercontent.com/1915775/106008869-c1024380-6085-11eb-9269-8a30e4678537.png)

**Comment by brianalloyd** [comment]
@ncksllvn shifting this into sprint 40 for tracking, we can close out once debugging has wrapped.

**Comment by ncksllvn** [comment]
This is done. All pages on www.va.gov should be about 24KB lighter and the page should also render a bit faster. I might try to collect a metric about the performance increase to see if it's noticeable.

**Comment by brianalloyd** [comment]
@ncksllvn this is awesome work, love the lighter pull and would love to show case the performance increase if you can gather some metrics.  That would also give us a comparable forward.  Thanks.  Closing ticket per validation.
