### ISSUE TITLE
STEM AD: Display EVSS warning when remaining entitlement is > 180 days

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18861]
As a STEM scholarship applicant, I need to be notified of my remaining entitlement when it does not meet the eligibility requirements so that I can have the most accurate information available when completing the application.

## Assumptions:
1. This work is completed behind a prod flag.

## Acceptance Criteria
1. When the EVSS service is available and the applicant's remaining entitlement is > 180 days, the warning is always displayed in the summary.

## Supporting Artifacts:
1. ![EVSS_entitlement_warning](https://user-images.githubusercontent.com/48260534/105510786-1365ed80-5c9d-11eb-9422-ba7781e63f33.png)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15866

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1361&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
