### ISSUE TITLE
Non-showstopper design tweaks for facility service locations

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#18866]
This is a placeholder ticket for capturing non-showstopper design tweaks for facility service locations structured content.

<details> 
<summary> Padding around appointment button is not equal on all sides. (this example from Primary Care) </summary>

![image](https://user-images.githubusercontent.com/55411834/105553972-ac0f6400-5cc3-11eb-8b39-29fff24f1534.png)

</details>

<details>
<summary> City, state and zip should not be included in facility health service location information </summary>

![image](https://user-images.githubusercontent.com/55411834/105558356-a1f16380-5ccb-11eb-8edb-2e8d853d4416.png)

</details>

## Acceptance Criteria
- [x] Days of the week in the Hours section should have periods (e.g. Mon., not Mon)
- [x] Spacing above and below the "appointments" button is visually equal
- [x] City, state and zip do not appear in facility health service location information

**Comment by mmiddaugh** [comment]
Abbreviation of day in hours looks good. 
City and state no longer are included in the address. 

<details> 
<summary> Screenshot from staging </summary>

![image](https://user-images.githubusercontent.com/55411834/106807142-0c889480-6626-11eb-9ed2-f6f9d7425eda.png)

</details>


However, @mpelzsherman did we lose the "Walk-ins accepted" line? Following screenshot is from staging....please see the screenshot in the issue description for "before" 
![image](https://user-images.githubusercontent.com/55411834/106807268-304bda80-6626-11eb-93c3-62afae4a9c66.png)

**Comment by mmiddaugh** [comment]
`Walk-ins accepted ` not appearing is as expected based on the data value in CMS. It is different from the staging scrrenshot in the description because of work Gibran did to refactor the values. All good. Closing this as complete.
