### ISSUE TITLE
CT: Anchor tag for "visit the Post-9/11 GI Bill website." not working correctly

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#18860]
## Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool
2. Select the link "visit the Post-9/11 GI Bill website." in the blue box in the bottom right corner
3. Link navigates to https://www.va.gov/education/about-gi-bill-benefits/post-9-11/#location-based107
4. Observe it does not land on the location-based 107 part of the page

## Expected results:

When selecting the link it should land on the location-based 107 part of the page below
![Screen Shot 2021-01-22 at 8.33.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/dc66dcb6-8788-4ef5-84c7-e8c45f525970)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15754

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Fix is now on Staging. Closing this out
