### ISSUE TITLE
EDU Form: Update 0994 Privacy Act Statement content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18878]
As an EDU Services Team member, I need the Privacy Act Statement content of the 0994 form to be updated so that the form is compliant with OMB standards.

## Assumptions:
1. This work is completed behind the feature flag `edu_form_omb_and_expiration` #18293 

## Acceptance Criteria
1. The 0994 Privacy Act uses the shared component.
2. The respondent burden time is 10 minutes.
    a. The respondent burden content is:

    > **Respondent Burden:** We need this information to determine your eligibility for education benefits (38 U.S.C. 3471). Title 38, United States Code, allows us to ask for this information. We estimate that you will need an average of 10 minutes to review the instructions, find the information, and complete this form. The VA cannot conduct or sponsor a collection of information unless a valid OMB (Office of Management and Budget) control number is displayed. You are not required to respond to a collection of information if this number is not displayed. Valid OMB control numbers can be located on the OMB Internet Page at www.reginfo.gov/public/do/PRAMain. If desired, you can call 1-800-827-1000 to get information on where to send comments or suggestions about this form.

    b. The privacy act notice content is:

    > **Privacy Act Notice:** The VA will not disclose information collected on this form to any source other than what has been authorized under the Privacy Act of 1974 or title 38, Code of Federal Regulations, section 1.576 for routine uses (e.g., the VA sends educational forms or letters with a veteran’s identifying information to the Veteran’s school or training establishment to (1) assist the veteran in the completion of claims forms or (2) for the VA to obtain further information as may be necessary from the school for VA to properly process the Veteran’s education claim or to monitor his or her progress during training) as identified in the VA system of records, 58VA21/22/28, Compensation, Pension, Education, and Vocational Rehabilitation and Employment Records - VA, and published in the Federal Register. Your obligation to respond is required to obtain or retain education benefits. Giving us your SSN account information is voluntary. Refusal to provide your SSN by itself will not result in the denial of benefits. The VA will not deny an individual benefits for refusing to provide his or her SSN unless the disclosure of the SSN is required by a Federal Statute of law enacted before January 1, 1975, and still in effect. The requested information is considered relevant and necessary to determine the maximum benefits under the law. While you do not have to respond, VA cannot process your claim for education assistance unless the information is furnished as required by existing law (38 U.S.C. 3471). The responses you submit are considered confidential (38 U.S.C. 5701). Any information provided by applicants, recipients, and others may be subject to verification through computer matching programs with other agencies.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
[Current OMBInfo text](https://github.com/department-of-veterans-affairs/component-library/blob/master/src/components/OMBInfo/OMBInfo.jsx)

https://github.com/department-of-veterans-affairs/vets-website/pull/15781

**Comment by dneel-bah** [comment]
Due to the privacy policy language updates being placed on hold, AC1b has been updated to be the current language.

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1302&group_by=cases:section_id&group_order=asc

Testing passes QA
