### ISSUE TITLE
Analytics QA Support for CMS Core Application Team - Custom User Sections Dimension in GA/GTM

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-team#18885]
# Google Analytics QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

    QA of a new Google Analytics dimension and GTM container updates.

- Who is this request for?

    Oksana Cyrwus (@oksana-c)
    
- What team/project is this work for?
    [CMS Core Application Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms#cms-core-application-team)

   Updates to existing GTM container "Va.gov Internal Drupal CMS".
    
- Please provide any upcoming deadlines or important milestones
    Updates to GA config and GTM container are already implemented and waiting to be QA'ed and published.

- Sample Users when authentication is required
   
   QA can be performed by @jonwehausen who has an account in Drupal CMS - jonathan.wehausen@va.gov

- Certain conditions/responses that need to be reviewed
     
     Steps to verify GA account updates:
    - [x] locate VA.gov CMS Backend property in Google Analytics
    - [x] locate custom dimensions list and confirm `User Sections` dimension is present (dimension ID = 11)
    - [x] review updates to GTM container "VA.gov Internal Drupal CMS" https://tagmanager.google.com/?authuser=1#/versions/accounts/144676348/containers/11546709/versions 
         - [x] confirm that `userSections` variable with dimension ID 11 is added to GA Settings variable

    Steps to QA dataLayer value for the new `userSections` dimension:
    - [x] login as jonathan.wehausen@va.gov
    - [x] spin up GTM container preview using "VA.gov Internal Drupal CMS" account in GTM
    - [x] confirm that dataLayer variable `userSections` is set to `all`. Note, that users who have been assigned a limited number of Sections in CMS will have Section IDs concatenated by comma instead of `all`. We're planning on creating custom segments based on User Sections once we have some data. Once confirmed please publish Version 10 of the GMT container that is currently pending approval.

- Additional Comments

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by jonwehausen** [comment]
Thank you for your work here @oksana-c! Please find the QA results below

### QA Testing

1) Validated Custom Dimension 11 enabled and identified as User Sections with user scope
![image](https://user-images.githubusercontent.com/48527022/105843590-e6b81b80-5fa5-11eb-8733-9cfb92ff3d57.png)

2. Validated data layer and GTM tag

Description | Data Layer | GTM Tag | Test Status
| -- | -- | -- | -- | 
Page load - identifying `userSections` variable | ![image](https://user-images.githubusercontent.com/48527022/105843828-3860a600-5fa6-11eb-86a1-1b07ea3c27d6.png) | ![image](https://user-images.githubusercontent.com/48527022/105843917-5a5a2880-5fa6-11eb-861a-a86cc2b89404.png) | ✔️ **PASS**

@oksana-c While I was unable to test with users other than myself, I trust the implementation looks good and I've published version 10 as a result.

**Comment by oksana-c** [comment]
thank you @jonwehausen !
