### ISSUE TITLE
EDU Form: Update Privacy Act Statement content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#18881]
As an EDU Services Team member, I need the Privacy Act Statement content of the forms to be updated so that the form is compliant with OMB standards.

## Assumptions:
1. The modal text is being pulled in from another repo other either `component-library` ~or `veteran-facing-tools`~.
2. Confirmed with EDU on 01/27 that the privacy ac statement in the forms listed in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18881#issuecomment-768502690) should also have the updated text.

## Acceptance Criteria
1. The Privacy Act Statement content:
    a. The respondent burden content is:

    > **Respondent Burden:** We need this information to determine your eligibility for education benefits (38 U.S.C. 3471). Title 38, United States Code, allows us to ask for this information. We estimate that you will need an average of 10 minutes to review the instructions, find the information, and complete this form. The VA cannot conduct or sponsor a collection of information unless a valid OMB (Office of Management and Budget) control number is displayed. You are not required to respond to a collection of information if this number is not displayed. Valid OMB control numbers can be located on the OMB Internet Page at www.reginfo.gov/public/do/PRAMain. If desired, you can call 1-800-827-1000 to get information on where to send comments or suggestions about this form.

    b. The privacy act notice content is:

    > **Privacy Act Notice:** The VA will not disclose information collected on this form to any source other than what has been authorized under the Privacy Act of 1974 or title 38, Code of Federal Regulations, section 1.576 for routine uses (e.g., the VA sends educational forms or letters with a veteran’s identifying information to the Veteran’s school or training establishment to (1) assist the veteran in the completion of claims forms or (2) for the VA to obtain further information as may be necessary from the school for VA to properly process the Veteran’s education claim or to monitor his or her progress during training) as identified in the VA system of records, 58VA21/22/28, Compensation, Pension, Education, and Veteran Readiness and Employment - VA, and published in the Federal Register. Your obligation to respond is required to obtain or retain education benefits. Giving us your SSN account information is voluntary. Refusal to provide your SSN by itself will not result in the denial of benefits. The VA will not deny an individual benefits for refusing to provide his or her SSN unless the disclosure of the SSN is required by a Federal Statute of law enacted before January 1, 1975, and still in effect. The requested information is considered relevant and necessary to determine the maximum benefits under the law. While you do not have to respond, VA cannot process your claim for education assistance unless the information is furnished as required by existing law (38 U.S.C. 3471). The responses you submit are considered confidential (38 U.S.C. 5701). Any information provided by applicants, recipients, and others may be subject to verification through computer matching programs with other agencies.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/component-library/pull/20

**Comment by dneel-bah** [comment]
@zurbergram While confirming the other forms, EDU informed us that the updated phrase should be `Veteran Readiness and Employment` instead of `Vocational Readiness and Employment`.  Please update the PR with the correct update.

**Comment by dneel-bah** [comment]
Other forms that use the component:

- caregivers: 
    - /family-member-benefits/apply-for-caregiver-assistance-form-10-10cg
- burials: 
    - /burials-and-memorials/application/530
- ask-a-question: 
    - /ask-a-question
- hca: 
    - /health-care/apply/application
- financial-status: 
    - /financial-status-report
- vre: 
    - /careers-employment/vocational-rehabilitation/apply
    - /careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832
- pensions: 
    - /pension/application/527EZ
- health-care-questionnaire: 
    - /health-care/health-questionnaires/questionnaires/answer-questions
- veteran-representative: 
    - /veteran-representative
- edu-benefits:
    - Previously discussed: 1995, 0994, 10203, 1990, 1990e, 1990n, 5490, 5495
    - NEW: feedback-tool
- disability-benefits: 
    - /view-change-dependents/add-remove-form-686c 
    - /decision-reviews/higher-level-review/request-higher-level-review-form-20-0996
    - /disability/file-disability-claim-form-21-526ez

**Comment by dneel-bah** [comment]
Another update, this language update is on hold pending an official change.  From EDU:

> The Privacy Statement on the forms cannot be updated until the Rule is final and we receive a new Federal Register citation and the SORN is updated, as not only the name will be updated but the Federal Register reference will change.  
>  
> The records are maintained in the appropriate Privacy Act System of Records identified as “Compensation, Pension, Education, and Vocational Rehabilitation and Employment Records-VA (58VA21/22/28),” published at 74 FR 29275 on June 19, 2009, and last amended at 84 FR 4138 (February 14, 2019).
>  
> We can follow up with you once this is finalized.

**Comment by dneel-bah** [comment]
Closing this issue as OBE; EDU will notify the development team when an update is ready.
