### ISSUE TITLE
Access for Aubrey Arcangel

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#18884]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Aubrey Arcangel
- Please Provide your email.
   > aubrey@thesocompany.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Testing Team, Full-Stack Engineer, The So Company

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABgQDqLphhbLR1fYxJPCN11Yh+7/NRzdGcKZYlBRm0MqRY4q//52++mnCyKb3qEvfi8qeppm2a3bDaInb8rQ/3lWFU1YHPqt35clN5DyRJz5VdIYl3EV/wH8mIAMQDKKyeLIZxgoxID6fV+hXcIOfl+EGmUVmyHYIoCprJsska9mq08PKpb5+fOIIEMzZgn/GsWQkyUNgVd0it1ckbVSCBtxwmTClUvrDyOfpRpHxveGFdZl2f4vpyBGb2TcVL2jLN+IEDHBeaR+vwstvvZDYZ5b3MSDgL3Vh3wAvpgEGjPfSPWxd7SXFfNEBOe93PxWKZCONRFTHiFluJDYmLBJvThJAtkTUS5+VrNlsHlgUVtYbWB1FTDKSKl3sRU0A/kojksuurKNyWMqlrVh2vAIBwdZJhjxJ8m9fR90mL3pLFjMgEeBN7sNK4Xtac9zBP89M6Qac/5i4RoEybWHN9d5geEMZS32YWN4FhScZckVDvYd4q26jkwRihzLUUVis23br5ySU= aaworkmacpro@MacBook-Pro
```

- Grant AWS Console access?
  >  NO

**Comment by tskinn** [comment]
@aubreyarcangel you should be able to connect to the socks proxy. Reach out in slack if you run into issues. Thanks
