### ISSUE TITLE
Text formatting issues on LOA1 page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18886]
## What happened?
Three minor formatting issues on the LOA 1 gate page:

1. In Header 1, both words of "Sign in" should be capitalized, as indicated in designs
2. In the following sentence, the word "and" should be bolded, as indicated in designs: "1. Your Social Security number, and" 
3. In the following sentence, there is a space missing between two words: "You can offer proof in 1of 2 ways:"

## Specs:
- Device: Samsung Galaxy S9

## Steps to Reproduce
In the login flow, observe the LOA1 gate page against the designs: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/437053959

## Desired behavior
1. In the page header, capitalize both words: "Sign In"
2. The word "and" should be bolded in the following sentence: "1. Your Social Security number, **and**"
3. Include a space between "in" and "1" in the following sentence: "You can offer proof in 1 of 2 ways:"

Designs: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/437053959r.

## Acceptance Criteria
See desired behavior. 

## Bug Severity
- 4 - low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/15100

## Screen shot(s) and additional information
![Screenshot_20210122-121750_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f1c44075-291b-472a-89ef-a34f5b6f0196)

**Comment by digitalken** [comment]
PASS 1/29/2021 - All issues look good.
