### ISSUE TITLE
Slack Customer Support Dashboard

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#18894]
The VSP Service Design team has started collecting data on Slack customer support requests via the Support Bot and the support tracker spreadsheet so we can better understand how VSP teams' time is spent responding to customer support requests. How might we make Slack customer support data available to VSP stakeholders so we can identify areas to focus on to make improvements that enable VFS teams to find answers or get unblocked on their own? 

This ticket is meant to provide the Analytics team with the desired metrics, questions we want to answer, and links to technical documentation.

**Support Bot Metrics** 

For a given time period:
- Total # of Github issues opened by the Bot.
- Issues labeled with x. 
- Issues including a link.
- Issues closed in x # of days.
- Issues responded to in x # of hours.

**Support Request Spreadsheet Metrics** 

For a given time period:
- Total # of support requests
- Support requests by VSP team
- Support requests by type
- Support requests responded to with documentation
- Support requests resolved with documentation
- Support requests  closed in x # of days.

**Questions we want to answer**

- What is the volume of Slack customer support requests VSP teams receive over time?
- How many of those requests are resolved by documentation?
- What are the most common types of Slack customer support requests?
- On average, how long does it take to resolve the most common types of Slack customer support requests?			
- Which support request types could be made self-service?	

**Access to Data**

- Support Bot technical documentation: [https://github.com/department-of-veterans-affairs/va.gov-support-slackbot](https://github.com/department-of-veterans-affairs/va.gov-support-slackbot)
- Board for Github issues opened by the Bot to track support requests: [https://app.zenhub.com/workspaces/vsp-support-5f905a8f492914000e4bb357/board?repos=297988048](https://app.zenhub.com/workspaces/vsp-support-5f905a8f492914000e4bb357/board?repos=297988048)
- Support request tracker spreadsheet: [https://docs.google.com/spreadsheets/d/1BmFJKmkJsgXaj_kebn16veLVJ5H52wlCjmbpS5JdXKo/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1BmFJKmkJsgXaj_kebn16veLVJ5H52wlCjmbpS5JdXKo/edit?usp=sharing)

**Comment by jonwehausen** [comment]
Thanks for your request @jchasia-adhoc , we will triage and get back with you.

**Comment by Khyatinp18** [comment]
2/21/2022:

Closing this issue since this is no longer a priority.
