### ISSUE TITLE
 AWS Staging:  Veteran user on VPN service for Community Care  the find provider near my location will not work correctly

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#18893]
Though there is no complete way to "solve" for the VPN use case, but improvements to accuracy can help this experience. Three [possible approaches](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/geolocation_discovery.md) were outlined in this [spike](#19282).

## Tasks
1. `enableHighAccuracy`
2. `maximumAge`

_Note- please raise any performance concerns that come from testing the implementation._

### Out of Scope
`speed` changes are out of scope of this ticket as it requires design specs.

---

## Original Description
Logging this defect.  If a veteran user uses a VPN service, the find provider near my location will not work correctly.  1) Login as hard coded CC eligible veteran.  2) Select  Schedule Appt 3) For Type of Care, select Podiatry 4)Select a date/time appt preference 5) Tell us your community care preferences, select +Choose a Provider 6) Select "Or, use your current location" 7) Expected response: Providers near my current location display (Denver/Boulder metro area  8)Actual Response:  Providers in Kentucky and Ohio display (edited) 

**From Triage with Jeff**: 
Marcy to Jeff:   When Chrome ask to allow the app to use my current location the address that then populates location is this:  2701 South Belmont Street, Ashland, Kentucky 41102, United States.  Why Kentucky?  It is just bizarre.

Jeff Balboni  [9:44 AM]
Cool. That’s what I suspected. Since your computer probably doesn’t have GPS, I think the browser location feature tries to use IP address for location, and the IP address while on a VPN depends on the VPN server you’re connecting to.
[9:45 AM] Could be worth noting in the app. VPNs aren’t uncommon, especially for people looking at the site while at work.  Lauren and Peter can decide if they want to add any messaging for it.

**Comment by laurenernest** [comment]
@jbalboni are we able to detect if the user is using a VPN? trying to see if a potential message would need to be a blanket statement about potential incorrect results or if we can target specifically to VPN users.

**Comment by jbalboni** [comment]
@laurenernest As far as I know, no, we can't directly detect if a user is on a VPN. It does look like the Geolocation API we use has an `accuracy` property, so we could do some testing to see if that is particularly low for someone on a VPN and/or desktop.

**Comment by outerpress** [comment]
@jbalboni Is this a problem with VA facilities too? If so, maybe we should look for helpdesk issues where users have reported that issue, or issues around facilities not showing up correctly to get a better sense of how widespread it is. 

I'm just hesitating to add more messaging - the longer the message, the more likely all users are to skim over it.

Accuracy might be an interesting tool, if we could say our confidence level in user's location, and only trigger it if the confidence level is low. This would work best if we also showed the address we think they're at.

**Comment by jbalboni** [comment]
@outerpress Yeah, would be an issue anywhere where we use current location from the browser.

**Comment by laurenernest** [comment]
Created a spike ticket so we can do some testing before triaging this. #19282

**Comment by laurenernest** [comment]
@jbalboni Based on the spike #19282, do we have a technical preference on how we make these improvements?

**Comment by LanceGundersen** [comment]
![image.png](https://images.zenhubusercontent.com/5f3eac7874547508dad0702d/d5efb5ab-e098-4680-b650-9fd754ca6bc0)

**Comment by laurenernest** [comment]
@LanceGundersen Thanks for posting your testing results! Based on the results of these changes (especially the negative impact to Primary Care VA) and the technical recommendation in the PR not to pursue, I'm closing this ticket as won't fix.

If we choose to proceed with any visual warnings of accuracy concerns, we'll handle in another ticket.

cc @jbalboni @narin @outerpress
