### ISSUE TITLE
Integrate Total Combined Disability Rating on 'My Rated Disabilities Page'

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1889]
## Story
As a user, I want to view my Total Combined Disability Rating (TCDR), so I can know how much benefit pay I will receive. I want the option to know how this value is calculated in case I have questions about my rating. 

## Task
- Display TCDR on the rated disabilities page per this mockup: https://xd.adobe.com/view/ebfa6df6-c0aa-4ea9-413e-98793ba7a5a3-9dcb/
- Data is retrieved and passed to the frontend

## Definition of Done
- [ ] The TCDR is displayed in a way consistent with the mockup above.

**Comment by micahchiang** [comment]
@jason-gcio - I've made #1975 to capture the backend work required for total combined disability rating feature. This ticket can house the frontend work required to display that rating.

**Comment by steve-gov** [comment]
If we can't get it into the current EVSS package we're pulling from, this is an alternative: https://developer.va.gov/explore/verification/docs/disability_rating
