### ISSUE TITLE
Expand unit test coverage of Facility Locator 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#189]
Problem: 
- Unit test coverage of Facilities Locator is too low to detect / prevent regressions 

Goal:
- Improve defect prevention by expanding unit test coverage

Notes:
- Review existing tests and ensure critical UX paths have coverage 
- Consider recent work and problems with the Facility Locator when deciding what to test
- Use your discretion when testing complicated logic- if the work results in brittle or difficult to maintain tests, consider breaking the work into refactoring + unit testing tickets 
- Currently there's not an easy way to see unit test coverage for an app. See #184. Use your discretion to determine when this work is done

**Comment by timwright12** [comment]
Current Facility locator coverage data:

**Lines**: 51.36%
**Functions**: 32.62%	
**Statements**: 50.28%	
**Branches**: 49.16%

**Comment by timwright12** [comment]
Closing in favor of:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23627
https://github.com/department-of-veterans-affairs/va.gov-team/issues/10677
