### ISSUE TITLE
Discovery on common CMS Export build errors

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18901]
## Summary

Given a large scale increase in the volume of CMS users and content, there is a risk that build errors will overwhelm manual resolution process and cause release delays.

## Details 

There are a variety of common errors that break the CMS Export Build. Examples are: broken links in CMS content, and circular reference errors. 

We need to understand a few things about these errors: 
* What causes them (can they be caused when new content is published? Are they only caused by changes to the content model? To transformers?) 
* How often they happen, approximately
* How difficult they are to fix, approximately (if there are differences in LOE to fix different error categories) 

Addressing some of these error types may end up being required for release of V1 of CMS Export — understanding that is part of the goal of this ticket. Others will be able to be addressed independent of/after release.

Related tickets: 
* Generalized solution for circular reference errors in CMS export #18899
* Validate scalability of CMS Export before release #18592
* Broken link handling for v1.0 release #19215
* Design doc for handling broken links #14092

## Definition of Done 

- [x] Common build errors identified 
- [ ] Build errors that need to be addressed before release of CMS Export V1 are identified and prioritized
- [ ] Tickets to address created

**Comment by mchelen-gov** [comment]
Spun off ticket for broken link handling: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19215

**Comment by meganhkelley** [comment]
Spun off ticket for metalsmith error: https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/19232

**Comment by timwright12** [comment]
**Working doc:**
https://docs.google.com/document/d/1JQ1Q0zBvyr2iStpY55DWFf57Oc7Ftq2WJBoVpPM_uXc/edit?usp=sharing

**Comment by meganhkelley** [comment]
Doc has been reviewed by VSP team members https://docs.google.com/document/d/1JQ1Q0zBvyr2iStpY55DWFf57Oc7Ftq2WJBoVpPM_uXc/edit#heading=h.cjut1j1ox9x2

@jhonnyoddball is doing some discovery around generalized solutions for these build errors. 

Not looking into the broken links since there is already separate work happening around that. For the others, questions to answer are:
* is there a way to prevent each of these issues from breaking the build, or decrease the frequency of those errors?
* would that work be something VSP would need to do or CMS or someone else?

We'll time box this solution discovery to a couple days and check back in early next week.

**Comment by meganhkelley** [comment]
Comments left on doc regarding possible future solutions. We are not continuing with this work at this time due to conversations about GraphQL vs CMS Export (& needed decision there). Broken link validation is discussed in separate ticket.
