### ISSUE TITLE
Pending Rated Disability Items Investigation

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1890]
## Story
As a backend engineer, I want to know how 'pending disabilities' are generated and defined, and where they live, so I can query that data and send it to the appropriate frontend application for consumption.

## Considerations
- Upon clicking for more information on a pending item, the user is taken to the Claim Status Tool
- If this appears to be a dead-end, note findings and discuss

## Tasks
- [ ] Investigate the location (within EVSS) of the data surrounding pending items and how it would be queried from `vets-api`.

## Definition of Done
- [x]  The location or source for this data has been found.

**Comment by micahchiang** [comment]
@jason-gcio - I've updated the title of this ticket to reflect the story. Since we have #1420 that deals with frontend development, this ticket is more closely associated with backend work.

**Comment by steve-gov** [comment]
As per the blocking issue, "Pending Disabilities" is actually just a list of claims in process. That is not a function we want to replicate on this page at this time. Directing user to the Claim Status tool is sufficient for this function.

Requires: New design issue, replacing the Pending Disabilities table with a CTA to view the Claim Status Tool page.
