### ISSUE TITLE
UI updates for Edit Address  

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18907]
## User story
As a user, I want a page to edit my address that indicates which fields are mandatory. 

**Note for dev**: This ticket does not include field-level errors OR deleting addresses.

## Acceptance Criteria
Make the following updates to the UX/UI on the Edit Address pages (Home, Mailing):

1. Military base checkbox: 
     - Remove this from the ListItem so it displays on the screen background, rather than inside the white box
2. Country:
     - Display Dropdown Field CC
     - Mark as "Required"
3. Street Address Line 1:
     - Display Input Field CC
     - Label this field as: "Street address line 1" (departure from designs)
     - Mark as "Required" 
     - Include helper text with specified character limit
4. Street Address Line 2 & 3:
     - Display Input Field CC
     - Label these fields as: "Street address line 2" and "Street address line 3" (departure from designs)
     - Include helper text with specified character limit
5. City
     - Display Input Field CC
     - Mark as "Required"
6. State _(Note: there are 2 versions of State. This applies to the State field when there is no address on file, or when U.S. is the selected country)_
     - Display Dropdown Field CC
     - Mark as"Required"
7. Zip code
     - Display Input Field CC
     - Mark as "Required"
8. APO/DPO/FPO
     - Display Dropdown Field CC
     - Mark as "Required"
9. State _(Note: this is the second version of State, when a non-U.S. country is selected)_
     - Display Input Field CC
10. International Post Code
     - Display Input Field CC
     - Mark as "Required"
11. Clear the Edit Address form and any associated field errors when either of the following occur:
     - User selects or deselects the Military Address box
     - User switches the country dropdown from US to any other country, and vice versa

## Designs
**Edit Address form:**
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432053040
**Source of truth for form-field specs:** 
https://adhoc.invisionapp.com/d/main#/console/21114574/445194525/preview?scrollOffset=538.888916015625

Original discovery ticket, for reference:
## Accessibility Implementation Guidelines
**Inactive state(empty):**
Formfield: “{label}, empty."
Formfield/Message: “{label, Hint message}, empty. "
Dropdown: “{label}, empty."
Dropdown/Message “{label, Hint message}, empty. "

**Focused state(editing):**
Formfield: “{label}. Editing - {Input text}. "
Formfield/Message:“{label, hint message}. Editing - {Input text}. "
Dropdown: “{label}. Editing - {Input text}."
Dropdown/Message “{label, hint message}. Editing - {Input text}. "

**Activated state:**
Formfield: “{label}. Filled - {Input text}. ”
Formfield/Message:“{label, hint message}. Filled - {Input text}. ”
Dropdown:“{label}. Filled - {Input text}. ”
Dropdown/Message “{label,hint message}. Filled - {Input text}. ”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/22/2021 - Looks good on Android and iOS, Closing.
