### ISSUE TITLE
[Bug] HLR - IE11 - Issues eligible for review - Issues detail-contents styling anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#18919]
## What happened?
In **IE11**, on Staging **Request a Higher-Level Review** > **Step 2 of 5: Issues eligible for review** form-page, the Issues' detail-contents are right-aligned and spills out beyond right-border of the boxes.

## Specs:
- Device: Windows PC
- Browser: IE11
- Test User _(if applicable)_: vetsgov+test236@id.me

## Steps to Reproduce
1. Go to https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction
1. IF **Is this the form I need?** section (eligibility wizard) is displayed, click **Disability...**, **No**, then **Request...**.  Browser replaces widget content with sign-in alert and regular intro content.
1. In **sign-in** alert, click **Sign in...**, and sign-in as **`vetsgov+test236@id.me` (Charde)**.  [See [this doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.docx) for credentials.]
1. IF **application-in-progress** alert is displayed, click **Continue...**.
1. Click **Back** or **Continue** to go to **Step 2 of 4: Issues eligible for review** page.
1. Observe that the Issues' detail-contents are right-aligned and spills out beyond right-border of the boxes.

**Screenshot**
![hlr-bug-styling-ie11-issues](https://user-images.githubusercontent.com/587583/105564599-2b129580-5ce0-11eb-944d-1efd66919df5.png)

## Desired styling
All issues' detail-contents should be left-aligned and contained within the boxes. [See [this design-prototype](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/404526248)]
![hlr-spec-styling-issues](https://user-images.githubusercontent.com/587583/105564627-3fef2900-5ce0-11eb-9020-4ebf4537753f.png)

## Acceptance Criteria
- [ ] [See **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tlei123** [comment]
@luke-gcio @Mottie , I couldn't find Veronica when searching for Assignee, so I added you two to this newly discovered defect.

**Comment by Mottie** [comment]
Fix has just been merged.

**Comment by tlei123** [comment]
Closing.  IE11 no longer supported.
