### ISSUE TITLE
VFS Support: Determine content and IA needs to support eBenefits.

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#1891]
### User Story

As a member of eBenefits, I need to review my current content and IA needs with VSP, so that I can adhere to best practices and ROE and build veteran-facing apps with agility and human centeredness.

### Goal(s)

In our onboarding meeting with eBenefits <> Content & IA, eBenefits identified that they have existing content & IA that needs reviewed. The goal here is to identify those existing support needs and establish a plan (re: content & IA reviews) for moving forward.

### Definition of Done
- [x] Meeting between Content & IA <> eBenefits
- [x] Findings from that meeting have been documented, next steps have been captured in ZH or elsewhere.

**Comment by mnorthuis** [comment]
My notes on 9/25 meeting with full eBenefits team:

**General process for migrating**
- notifying users and handling traffic/redirects - they added this to their launch checklist to come back to as they get closer to launch.  eBenefits has its own timeline and process for initial messaging and then full redirect. 

**View rated disabilities tool** 
- this is their next thing, mockups are done, discovery research focused on eBenefits experience will happen within the next week or so
- Discussion around this vs disability rating tool created by global ux team; suggested connecting so they can determine how the tools can co-exist and benefit from one another.  Will need to discuss potential linking between tools.  
- Global UX tool is unauth exp, eBen tool is auth experience
- Discussed how this tool relates to profile, should it be part of that? Per content/ia, currently profile acts as a jumping point but that could reverse after personalizetion 2.0.  Discussed current flow that includes static pages that lead to authenticated tools

**View/add/remove dependents** 
- Currently exists in disability only, may need to move to global position
- Likely starting in 4-6 sprints
