### ISSUE TITLE
Make FL query attributes visible for troubleshooting

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18914]
## Issue Description

Update the parameters according to API call and include in the URL 

This change won't resolve the bug which is preventing the parameters from being read and used in the request. That will be addressed in a separate issue. 

## Acceptance Criteria
- [ ] URL parameters include all info from API call 
- [ ] For Community care queries, include the following parameters (address or lat/long, type, specialty, radius, bounding box, page, per page)
- [ ] For VA queries, include the following parameters (lat/long, facility type, service type, radius, bounding box, page, per page)

---

Bug: We cannot send a community care search URL to use for troubleshooting. We are no longer parsing the community care attributes and we need a way to understand what was sent in the query and easily rerun the query. 

## Acceptance Criteria
- [ ] Community care parameters are read and the map renders results according to the query/search parameters

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
@mmiddaugh - the issue with Community Care searches is a separate bug. Steps to reproduce:

1. Search for Optometrist (location doesn't matter)
2. Refresh the page.

A 500 error occurs. This is because we are not converting the specialty code in the URL into a Service Type on the front end.

**Comment by mmiddaugh** [comment]
Community care example: 
address: Fraternity Court West, Raleigh, North Carolina 27606, United States
bbox[]: -79.43
bbox[]: 35.03
bbox[]: -77.93
bbox[]: 36.53
type: provider
specialties[]: 152W00000X
page: 1
per_page: 10
trim: true
radius: 11
latitude: 35.78
longitude: -78.68
