### ISSUE TITLE
Mobile side-nav focus not properly managed in Safari

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18916]
When opening the mobile side nav (https://staging.va.gov/health-care/schedule-view-va-appointments/), focus should go to the "close" button. This does not always happen in Safari (Version 14.0.2). Sometimes focus remains on the trigger button. This is hard to replicate reliably. And it does not seem to affect Safari on iOS devices.

Steps to replicate (maybe):
1. Go to https://staging.va.gov/health-care/schedule-view-va-appointments/
2. Open the side nav using the keyboard, not the mouse. Focus should be on the "close" button.
3. Close the side nav with the keyboard.
4. Open the side nav using the keyboard again. Focus is not on the "close" button.

This does not seem to affect other browsers.

This video shows both this issue and https://github.com/department-of-veterans-affairs/va.gov-team/issues/18917

https://user-images.githubusercontent.com/20728956/105561687-630fdd80-5ccc-11eb-823a-2743ad85cdd3.mp4

**Comment by erikphansen** [comment]
@brianalloyd This should be on staging within an hour and can be validated.

**Comment by brianalloyd** [comment]
Closing per validation.
