### ISSUE TITLE
508-defect-2 [COGNITION]: "Prepare for your visit accordion" Heading levels SHOULD increase by one in a logical order

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#18913]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** _Josh_

## User Story or Problem Statement

As a screen reader user, I want to navigate the hierarchy of the page content using heading levels to save time and frustration.

## Details

Headings on the page should increase by one in a logical order. Currently, due to the absence of headings within the accordion elements, there is a skipped level between the `h2` and `h4` headings on the page. Placing the accordion buttons within a `h3` should resolve this issue without the need of editing their collapsible content's headings.

Something very similar to this was addressed on the BAM team by @Mottie not too long ago in this ticket: [Add headers inside review accordion #15717](https://github.com/department-of-veterans-affairs/vets-website/pull/15717).

## Acceptance Criteria
**For the "Prepare for your visit" area, only** 
- [x] Accordion buttons are contained within a `h3`
- [x] When each of the accordions are expanded, AXE does not throw an issue for skipped headings
- [x] The [headingsMap chrome extension](https://chrome.google.com/webstore/detail/headingsmap/flbjommegcjonpdmenkdiocclhjacmbi?hl=en) reveals a logical order of headings

**NOTE: this is not ready to ship until CMS has also improved the editorial experience (separate issue)**

## Environment

* Operating System: any
* Browser: any
* Screenreading device: any
* Server destination: staging

## Steps to Recreate

1. Enter `https://staging.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/` in browser.
2. Expand the Transportation and Services accordion
3. Run an AXE scan
4. Confirm the issue "Heading levels should only increase by one" is flagged

## Solution 
Place all the accordion buttons within an `h3`, this will allow their strings to be read as headings to screen readers.

<img width="1792" alt="Screen Shot 2021-01-22 at 6 28 20 PM" src="https://user-images.githubusercontent.com/14154792/105559640-b2abd480-5cdf-11eb-868a-e43d71b0bd7a.png">

## WCAG or Vendor Guidance (optional)

* [Headings - Web Accessibility Tutorials](https://www.w3.org/WAI/tutorials/page-structure/headings/)

## Screenshots or Trace Logs

<img width="1120" alt="Screen Shot 2021-01-22 at 3 14 28 PM" src="https://user-images.githubusercontent.com/14154792/105559328-dd495d80-5cde-11eb-851b-a9a550b1ecaa.png">

**Comment by mpelzsherman** [comment]
Do we also need to increase the heading levels inside each accordion?

**Comment by joshkimux** [comment]
@mpelzsherman No need! By converting the accordion titles to `h3`s, we'll be able to bridge the `h2` (Prepare your visit) and `h4` (the heading levels _inside_ each accordion) gap.

Basically, instead of `h2` Prepare your visit -> `h4` Van services for vans, we'll now have `h2` Prepare your visit -> **`h3` Transportation services**  -> `h4` Van services for vans

**Comment by mmiddaugh** [comment]
Blocking this one until we discuss solutions with CMS team

**Comment by brangi** [comment]
@mmiddaugh can you confirm with josh that the other accordions don't need this fix?

**Comment by mmiddaugh** [comment]
@brangi the Prepare for your visit accordions are the only ones within the scope of this issue. We do have [an issue(https://github.com/department-of-veterans-affairs/va.gov-team/issues/18988) to audit the headings for all accordions. We'll address any issues identified separately. 

@joshkimux this issue is ready for your review when you are available

**Comment by joshkimux** [comment]
@brangi @mmiddaugh 
Great work with fixing the headings for the prepare for your visit accordions! 
![image](https://user-images.githubusercontent.com/14154792/110377411-5e0bb100-8022-11eb-84ce-30c4bbcad92a.png)
