### ISSUE TITLE
Mobile side-nav trigger can render on top of page contents

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18917]
In Safari, if you very quickly switch from desktop view to mobile view, for example by opening the web inspector on the right-hand side of the window, the menu trigger can be on top of page contents, obscuring the contents. This can be fixed by adjusting the size of the browser, triggering an `onresize` event.

This video shows both this issue and https://github.com/department-of-veterans-affairs/va.gov-team/issues/18916

https://user-images.githubusercontent.com/20728956/105561687-630fdd80-5ccc-11eb-823a-2743ad85cdd3.mp4

**Comment by erikphansen** [comment]
@brianalloyd This should be on staging within an hour and can be validated.

**Comment by brianalloyd** [comment]
Closing per validation.
