### ISSUE TITLE
Allow same month/year for a VA facility visit during 526 flow

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18929]
## User Story
As a veteran, I may visit a VA hospital all in the same month and I want to be able to say that when using the 526 form.

## Expected Behavior
The issue is below:

<img src="https://user-images.githubusercontent.com/53824125/105735399-de51d900-5ef0-11eb-9128-98209ef06e46.png" height=500>

You can see that the validation is too restrictive.  We need to allow same month/year as a valid selection.

## Acceptance Criteria
- [ ] Double check when (if) this changed.  I thought before it was a specific date.

**Comment by annaswims** [comment]
same for https://staging.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records-release. Probably just want to review that the start and end date can be the same in the entire app.
