### ISSUE TITLE
Rerun Submission times stats on the 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18927]
## User Story
As a Veteran
I would like the submission times on the 10-10CG to be as short as possible
So that I feel confident in my submission 

## Expected Behavior
- In November 2020, we calculated a number of metrics around submission times (#16456)
- Now that we've released background processing, I want to rerun those metrics so that we can understand the impact of our work

## Acceptance Criteria

- [x] Stats are rerun
- [x] Let's find a good place to store these kinds of metrics (Caregivers - Product Github space?)
- [x] Alayna to add story to VSA Product Tracker

**Comment by kevinmirc** [comment]
| Date (UTC) | Average | Min | Max | 95th Percentile | Standard Deviation |
|------|------:|------:|------:|------:|----:|
 |Sunday, November 1, 2020 | `12.378` | `6.366` | `36.126` | `23.132` | `5.115` |
 |Monday, November 2, 2020 | `11.547` | `6.110` | `6.1494` | `15.822` | `5.222` |
 |Tuesday, November 3, 2020| `12.663` | `6.297` | `76.285` |`33.886` |`9.114`|
 |Wednesday, November 4, 2020| `10.092` | `6.593` | `18.511` |`13.389` |`1.846`|
 |Thursday, November 5, 2020| `10.370` | `6.365` | `53.528` |`13.283` |`3.475`|
 |Friday, November 6, 2020| `10.157` | `5.640` | `23.699` |`14.547` |`2.411`|
 |Saturday, November 7, 2020| `10.039` | `6.532` | `17.489` | `13.349` |`1.740`|

**Comment by kevinmirc** [comment]
Metrics were added to the Caregiver product documentation: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/metrics
