### ISSUE TITLE
[BUG] EVSS Schema vs code mismatch

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#18924]
We've been getting a lot of 500 errors from EVSS (https://github.com/department-of-veterans-affairs/va.gov-team/issues/13949
).  A Major cause is that there was a mismatch between EVSS documentation and code. Aside from the the homeless issue, (https://github.com/department-of-veterans-affairs/va.gov-team/issues/18210)  it seems that we may get a 500 error if we send a SpecialIssueTypeCode aka [specialIssues]( https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21-526EZ-ALLCLAIMS-schema.json#L52) with a slash rather than an underscore.  

As far as I can tell we don't use retirement code, but that should be verified. 

Full emails from Michael Harlow in comments.

**Comment by annaswims** [comment]
On Jan 22, 2021, at 3:26 PM, Harlow, Michael F. (Insignia Tech)  wrote:

Luke,
 
The form526 API is currently designed to send “special issue” PTSD data to VBMS. This happens when a PTSD SpecialIssueTypeCode is included in the JSON request in the "specialIssues" element. However, it appears that VA.gov is not currently sending this data and EVSS won’t accept it until we update the schema to match the Swagger model.
 
Here are the 4 different PTSD types that EVSS will support after the Feb 3 release.
 
PTSD_1 (related to: PTSD - Combat)
PTSD_2 (related to: PTSD - Non-Combat)
PTSD_3 (related to: PTSD - Personal Trauma)
PTSD_4 (related to: Non-PTSD Personal Trauma)
 
Here's an example of a createContentions request with PTSD_1 that would be sent to VBMS.
 
<ns5:createContentions>
<ns5:contentionsToCreate id="10" claimId="-8562926799839200839" actionableItem="true" awaitingResponse="default value" classificationCd="10" levelStatusCode="P" medical="true" partcipantContention="abnormal heart (related to: PTSD - Combat)" secondaryToContentionID="0" title="abnormal heart (related to: PTSD - Combat)" typeCode="NEW" workingContention="abnormal heart (related to: PTSD - Combat)">
              <ns2:submitDate>2021-01-22-05:00</ns2:submitDate>
              <ns2:issue inferred="false" narrative="PTSD - Combat" typeCd="PTSD_1"/>
              <ns2:issue inferred="false" narrative="VONAPP Direct Connect" typeCd="VDC"/>
              <ns2:startDate>2021-01-22-05:00</ns2:startDate>
       </ns5:contentionsToCreate>
</ns5:createContentions>
 
Please let us know if you plan to add these PTSD attributes to the form526 JSON requests. I will verify that VBMS supports this change when it’s deployed in staging next week.
 
Thanks,
Michael

 
On Fri, Jan 22, 2021 at 9:02 AM Harlow, Michael F. (Insignia Tech) <Michael.Harlow@va.gov> wrote:
Anna,
 
The form526 schema update that went live on Wednesday appears to have fixed the 500 errors coming from the API. However, there is the potential for similar errors where the schema doesn’t match the API documented in the Swagger models.
 
Here are 6 elements in the schema that don’t match the Swagger model. I understand that VA.gov is not using retiredStatusType, so we plan to update the schema to use underscores instead of spaces in the next EVSS release. At the same time, we would like to fix the PTSD mismatch by updating the schema to use underscores instead of slashes. Is VA.gov using the PTSD values in SpecialIssueTypeCode?
 
<xs:simpleType name="SpecialIssueTypeCode">
    <xs:restriction base="xs:string">
        <xs:enumeration value="ALS"/>
        <xs:enumeration value="HEPC"/>
        <xs:enumeration value="POW"/>
        <xs:enumeration value="PTSD/1"/>   Swagger: PTSD_1
        <xs:enumeration value="PTSD/2"/>   Swagger: PTSD_2
        <xs:enumeration value="PTSD/4"/>   Swagger: PTSD_4
        <xs:enumeration value="PTSD/3"/>   Swagger: PTSD_3
    </xs:restriction>
</xs:simpleType>
 
<xs:simpleType name="retiredStatusType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="RETIRED"/>
        <xs:enumeration value="PERMANENT DISABILITY RETIRED LIST"/>   Swagger: PERMANENT_DISABILITY_RETIRED_LIST
        <xs:enumeration value="TEMPORARY DISABILITY RETIRED LIST"/>   Swagger: TEMPORARY_DISABILITY_RETIRED_LIST
    </xs:restriction>
</xs:simpleType>   
 
There have not been any 500 errors since 9:00PM on 1/20, so it’s very likely the highlighted enumerations are not being used. However, I wanted to verify with you before making any changes.
 
Thanks,
Michael

**Comment by annaswims** [comment]
I've verified that there is no code interacting with SpecialIssueTypeCode on the back end.  Once we verify the same on the FE we can close.

**Comment by Mottie** [comment]
It looks like we only work with the POW specialIssue entry in the submit transformer. It not referenced by the `uiSchema` at all, meaning the items in that list are never displayed to the Veteran.
