### ISSUE TITLE
Identify and remove unused fields from health_care_region_detail_page transformer

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#18922]
The new transformer diff tool is generating many false positives due to fields that are either 1) not needed by the templates or 2) not included in the GraphQL queries or transformers.

## Acceptance Criteria

- [ ] The transformer diff tool generates zero false positives due to unused fields in the health_care_region_detail_page transformer

A list of transformers we own can be found [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/process-cms-exports/transformers/README.md#L7).

**Comment by mmiddaugh** [comment]
Individual issues have been created for the identified issues and are linked within [this epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19035)
