### ISSUE TITLE
Finalize IA and mapping for migration of content from vets.gov-team/Practice Areas/Research

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#1893]
### User Story
As a VFS team, I need to be able to access research documentation in the new public va.gov-team repo, so that I can proceed with user research according to best practices and guidelines.

### Goal(s)
Based on Lauren's (content owner of vets.gov-team/Practice Areas/Research) audit of her content and her proposed folder structure, review proposed folder structure, re-map content as needed, and prep map as a spreadsheet for migration. 

### Definition of Done
- [x] Matt to review proposed folder structure provided by Lauren for migration of content from vets.gov-team/Practice Areas/Research to va.gov-team/platform/research
- [x] Matt to make necessary changes to proposed folder structure (review with Mikki)
- [x] Matt to review proposed changes to folder structure with Lauren
- [x] Matt to remap files as needed for migration of content from vets.gov-team/Practice Areas/Research that is formatted as Bill (or other engineer) needs for file migration
- [x] Mikki to review mapping before it is handed off to Bill (or other engineer)
- [x] This story is assigned to an epic

**Comment by thatmattjohnson** [comment]
completed as of 9/26/2019.
