### ISSUE TITLE
Analytics Implementation or QA Support for Caregiver Team; Health Care Application

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18939]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics implementation

- Who is this request for?

    - @ala-yna 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - We're adding an additional page to the 10-10EZ (health care application) that allows Veterans to add an optional home address. 
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - https://staging.va.gov/health-care/apply/application/veteran-information/veteran-home-address
    - https://va.gov/health-care/apply/application/veteran-information/veteran-home-address
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - Launching on 1/25/21

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - va.gov/health-care/apply/application/veteran-information/veteran-home-address
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - n/a

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - n/a

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Fill out the form as an unauthenticated user
    - On the mailing address page, select No for the question "Is your Is your home address the same as your mailing address?"

- Certain conditions/responses that need to be reviewed

    - n/a
- Additional Comments

    - I would like to track the number of hits on that specific page,
    - I would also like it to have it added to the flow in our Domo dashboard (https://va-gov.domo.com/page/980067552)

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by jonwehausen** [comment]
Thank you for your request here @ala-yna , I have closed this issue and passed along to the team to add in the new page to the funnel visualization on the HCA dashboard. 

Please see this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16547

cc: @joanneesteban @mandy-uxd @JasonTheBearded
