### ISSUE TITLE
Security / privacy review for Facility Locator fields

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#18930]
@joanne -

Here are all the potential dimensions we can collect from _Facility Locator_ search results and clicks.

Can we get confirmation that all of these fields are safe to collect from a security and privacy perspective?

Thanks!

--------

### Search Results returned

DataLayer Variable | Example Value | Description
------------ | ------------- | ------------- 
`'fl-facility-type-filter'` | `'VA health'` | The facility type the user used to filter on search, `undefined` if not used
`'fl-service-type-filter'` | `'Primary Care'` | The service type the user used to filter on search, `undefined` if not used
`'fl-allowed-location'` | `true` `//false` | if the user used the allow location functionality to auto-search, `true` if so, `false` if not
`'fl-results-returned'` | `true` `//false` | `true` if the search returned ANY results, `false` if no results returned
`'fl-total-number-of-results'` | `101` | Contains the full number of results returned ,
`'fl-total-number-of-result-pages'` | `5` | Stores the total number of result pages returned for the search
`'fl-mapbox-returned-place-type'` | `"place_type"` | ![image](https://user-images.githubusercontent.com/48527022/88317176-e7b27c80-cce6-11ea-8444-a03fb4f1e368.png)
`'fl-closest-result-distance-miles'` | `32.4` | Stores the top result's distance
`'fl-time-to-return-results'` | `4023 //in milliseconds` | Stores the total time taken to return the search results

### Clicks on Search Result Facilities

DataLayer Variable | Example Value | Description
------------ | ------------- | -------------
 `'fl-facility-name'` | `'Charlotte Hall VA Clinic'` | Store the name of the facility 
 `'fl-facility-type'` | `'VA Health'` | Store the type of facility 
 `'fl-facility-id'` | `'vha_688GD'` | Store the facility ID 
 `'fl-facility-classification'` | `'Primary Care CBOC'` | Store classification of facility
 `'fl-result-page-number'` | `4 //if on the 4th result page` | Store the result page number user is currently on (pagination number)
 `'fl-result-position'` | `5 //if the 5th result on the page` | Store the search result position in the list

**Comment by joeniquette** [comment]
I'm not sure we should/can store:

- 'fl-service-type-filter'
- 'fl-closest-result-distance-miles'

They could be used in combination to be seen as health related identifying information. Especially in the more rural areas where only one person is located 32.4 miles away from a facility. I would be willing to discuss if their is enough entropy with these results that doesn't allow identification and thus then the creation of "PHI" because of the combination of attributes.

**Comment by bsmartin-ep** [comment]
Moved to sensitive repo...
