### ISSUE TITLE
[FE] Make reusable navigation action/CTA button 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18936]
## Background
The new MyVA has a different secondary CTA button.

## Tasks
- [ ] Create updated reusable navigation/action button 
- [ ] Determine correct semantic markup with the accessibility team

**Comment by erikphansen** [comment]
Pretty sure this doesn't really need to be done anymore, but we'll pull it into this sprint and confirm.

**Comment by erikphansen** [comment]
Closing this. The fancy link that looked like a button has been removed from the designs and has been replaced with a simple link.
