### ISSUE TITLE
[Enhancement] Validate Addresses on the 10-10EZ

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18931]
## Product Outline
[Initial Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/10-10ez-address-project/project-outline.md)

## High Level User Story/ies
As a Veteran,
I want my online form to validate my addresss
So that I can be sure that the VA will be successful in communicating with me.

## Hypothesis or Bet
**If** we validate addresses on the 10-10EZ **then** we expect the VA to be more successful communicating with Veterans.

## OKR
- Successful communication with Veterans after HCA submission

### What must be true in order for you to consider this epic complete? 
- Understand the needs of the HCA business team
- Prototype and test designs that help Veterans confirm addresses on forms (specifically HCA)
- Frontend and backend requirements have been researched, documented, and implemented
- Work is released to Production

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by hdjustice** [comment]
Closing this epic - has not been addressed in over a year.  If work is needed, a new epic will be created under an initiative
