### ISSUE TITLE
[Launch] HLR: Prepare Product Guide for Higher Level Review

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#18948]
## User Story or Problem Statement
As a veteran, I need to be able to get help from the call center so I can effectively navigate through the request for review process.

This story captures the work for the call center product guide for Higher Level Review.

Here is the GitHub documentation on how to do this:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/3717881c2f1a488f5e215f6ee11010e32cf1956c/platform/call-center/request-contact-center-review.md

## Tasks
- [x] Create Product Guide
- [ ] Review with contact center

**Comment by kevinstachura** [comment]
The product guide is completed and can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/Higher%20Level%20Review%20-%20Product%20Guide%20-%20Jan%202021.docx
