### ISSUE TITLE
Find a VA Form - Remove sort feature toggle, do PR, deploy to Prod

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18950]
## User Story

As a FE engineer, I want to remove feature toggle that prevented the new sorting feature from being displayed in Production so that our users can start using it.

## Expected Behavior

Sorting feature is displayed on Production

## Acceptance Criteria

- [x] Remove feature toggle that hid sort feature on Production
- [x] Complete Peer Review
- [ ] Deploy to Production

**Comment by zacharymorel** [comment]
@kelsonic or @ncksllvn Can I schedule an async feature flag removal peer preview with on of you on Monday 2/8 so we can launch on 2/9?

**Comment by ncksllvn** [comment]
Yeah go right ahead, we can approve today so it's ready to go

**Comment by zacharymorel** [comment]
Oh we can do that? That's great!

**Comment by ncksllvn** [comment]
If you just mean to open a PR today and have it approved so all you have to do is click merge on launch day, then yep, we do that all the time w/redirects!

**Comment by zacharymorel** [comment]
Okay, I appreciate that. I was wondering if there was some policy against something like so. 
Well, you should see a PR soon once the my sprint begins.

**Comment by ncksllvn** [comment]
Sounds good!

**Comment by zacharymorel** [comment]
@ncksllvn  https://github.com/department-of-veterans-affairs/vets-website/pull/15819 !

**Comment by ncksllvn** [comment]
LGTM 🚀

**Comment by zacharymorel** [comment]
This will hang in validation until I we are ready to go.
