### ISSUE TITLE
HTML entities showing false positive discrepancies between GraphQL <> CMS Export

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#18955]
## Details 

Notes from FE Tools standup 1/25

* JSON comparison script, HTML entities
   * HTML entity example - ampersand 
   * HTML entities are being added to the qraphQL queries but not to the CMS export content
      * They’re technically the same string, but the entitity is being added in the graphQL 
      * We could ignore this? But maybe we could get these entities into the CMS export? Or take them out of the graphQL query?
      * Jhonny: passed the encode function into a helper that converted the ampersand to amp

## To Do

- [ ] Determine how to address — fix the root cause? Ignore the discrepancies in the comparison tool? Something else? 
- [ ] Address appropriately according to determined solution

**Comment by theodur** [comment]
HTML entities are being converted (_stripped_) in multiple places in the `src/site/stages/build/process-cms-exports/transformers/helpers.js` file. Removing HTML entity conversion reduces the number of `nodes with differences` from 1532 to 1512.

**Number of differences with HTML entities being stripped**
![Screen Shot 2021-01-25 at 4.44.12 PM.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/622d812f-4d79-4cc5-81e3-cc91cbcb7869)

**Number of differences with HTML entities NOT being stripped**
![Screen Shot 2021-01-25 at 4.46.06 PM.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/19dc24f4-4e45-4bd0-9341-565ab14ac11d)

**Comment by theodur** [comment]
Resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/15804.
