### ISSUE TITLE
CMS export JSON diffs for Public Websites Transformers 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#18954]
## Issue Description
_The PR for the comparison tool has been merged, and documentation has been written for how to use it. Now Public Websites FE team needs to run the diff and fix identified discrepancies to all owned transformers_

Refer to Identify & document transformers owned by VSA Public Websites [#16440](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16440)

## Front end tasks
- Groom ticket and remove 'Needs Grooming' label 
- Run JSON comparison tool and fix any discrepancies to all PubWeb transformers
- Validate transformers are preforming properly before close out 

## Acceptance Criteria
- [ ] Fix any known transformer discrepancies to all PubWeb Transformers  
- [ ] Unit tests pass
- [ ] Validate transformers are preforming properly and will pass platform testing ISO cutover plan

Tread any comments or issues on this ticket for documentation purposes.

**Comment by kelsonic** [comment]
Do we close this?

**Comment by kelsonic** [comment]
Closing because of https://dsva.slack.com/archives/C01512KN35G/p1613768774348100
