### ISSUE TITLE
Access for Stephen Barrs

### ISSUE THREAD

**Issue by stephenBarrs** [department-of-veterans-affairs/va.gov-team#18968]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > OCTO employee 
- Please provide your name.
   > Stephen Barrs
- Please Provide your email.
   > stephen.barrs@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Multiple teams including Covid Vaccine work and Clipboard app, Engineer, Department of Veterans Affairs

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key?
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC141b8FG1cQ0XB9gSoWQsueiuttT9bRB7WOWgskCaRakC8shQXOkFxsmQHkD8Z5F7HDCfg8uRF1nVwDNt56EqAdX2slUZ7yi6SyZ8Fxd1A6205r6ue608dLHcjbx232wcEDJPOFXzQbPOmXmRNNtpeigYgwC0ovJ7guWb9g+OO0t54OqNYWmvCS+UC4dwrcpNCXbmLlDUzK37afgVTAJfFILL4cEPqPCvENRDXwuAazIbBpAIKYVPxUo8dX9hIi2WMDthaRWKZE8roOg/KjHDNingGEXvVfZ6ua7Aj6vJ1Oa8ZI8SQaveasaBHzVVCqKvEOwmNtdjQxvM8AudZ9AKjmEXaKbgJpuY4EchsGtA3mZnbhmIekSuLP8/ZQrRGz0cZAyQmktZgOe+ViuWfyZLoC87XXafA4ZFmFd7Xjv2Zt1JbbFn0oJVhBYEUBseotJx5ddI4rnn7ts79gGE5fGInsc0a2wDO/n32/pxWvmvuXyswwgfpARjhUTQ5dSeRCv2W+RNOw/CNeYqhPWfANdNfrIDi5FJDoYdioYy6xs4EMvtn8MDAdVq0larHXffdEt8vzVuCOvMncoJQyI8Y/QvFbbbmoWUjpJCMN9p7B4sl26lXkMOLrcZyBXThHUVw6fbvD74sXKc+f4rj4ujtttbAfFHY6dz3qrAKwPtiTt6KiQ== stephen.barrs@va.gov
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why?  
  > Need access for troubleshooting and log file review.  This came up for me a month ago and without access I had to lean on some other engineers to assist.  [Slack thread ](https://dsva.slack.com/archives/C01FNSTQD7H/p1608143627200500?thread_ts=1608049918.000400&cid=C01FNSTQD7H)for reference.  

   > I have access to `socks` and internal tools but still need access to AWS Console and Pager Duty.

**Comment by stephenBarrs** [comment]
@department-of-veterans-affairs/vsp-operations tagging you per instructions.  Thanks!

**Comment by jbritt1** [comment]
@stephenBarrs your SSH key is already in our system, so your SOCKS should already be good to go.

**Comment by jbritt1** [comment]
### For AWS Access:

User: Stephen Barrs
COR: OCTO Employee
Approval Needed: @Jeff-Hayter

**Comment by stephenBarrs** [comment]
@jbritt1 how do i request access to Pager Duty?

**Comment by jbritt1** [comment]
> @jbritt1 how do i request access to Pager Duty?

We are currently out of licenses for PagerDuty and to my knowledge that has already been escalated up the chain.

**Comment by jbritt1** [comment]
@jhouse-solvd / @dginther / @f1337 ☝️

**Comment by jbritt1** [comment]
Tagging some folks from leadership for awareness.

**Comment by f1337** [comment]
Hey @stephenBarrs, hit up Demian or myself in Slack and we'll get you into PD. Thank you!!

**Comment by stephenBarrs** [comment]
@f1337 Thanks!  I will be back to this early next week.

**Comment by mleclerc00** [comment]
@stephenBarrs was this ever sorted out?

**Comment by stephenBarrs** [comment]
@mleclerc00 @f1337 So sorry I have not followed back up on this issue.  I do still need access to Pager Duty and access to be able to SSH in to review instances.

**Comment by mleclerc00** [comment]
You should be able to ssh into review instances now.  I will leave pager duty up to Michael or Demian.

**Comment by mleclerc00** [comment]
Pinging @Jeff-Hayter for AWS approval

**Comment by stephenBarrs** [comment]
Thanks @mleclerc00!  I am an FTE VA employee with OCTO , do I still need @Jeff-Hayter approval?  @drorva what is policy for approval for OCTO employees?  Thanks!

**Comment by Jeff-Hayter** [comment]
@mleclerc00 Approved for AWS.  FTE only need Dror's approval I believe cc: @jhouse-solvd

**Comment by drorva** [comment]
Approved, but we need to sort out the Pager Duty licenses.

**Comment by stephenBarrs** [comment]
Thanks @Jeff-Hayter and @drorva!  @mleclerc00 any chance the AWS access can be completed this morning?

**Comment by mydesignrocks** [comment]
@jbritt1 - wondering if these are the right groups that Stephen should be part of?
["dsva-vfs-all", "dsva-vfs-developers", "force-MFA"]

**Comment by jbritt1** [comment]
> @jbritt1 - wondering if these are the right groups that Stephen should be part of?
> ["dsva-vfs-all", "dsva-vfs-developers", "force-MFA"]

Yes, let's roll with those first two groups (force-MFA is included in dsva-vfs-all https://console.amazonaws-us-gov.com/iam/home?region=us-gov-west-1#/groups/dsva-vfs-all)

**Comment by mydesignrocks** [comment]
ah! true - thank you! @jbritt1

**Comment by mydesignrocks** [comment]
can you please verify your AWS access now @stephenBarrs

**Comment by mydesignrocks** [comment]
AWS Access Granted
Hello!
You can log in by visiting --> https://dsvagovcloud.signin.amazonaws-us-gov.com/console
Your username is:
Your initial password is:
You'll need to:
Change your password upon first login.
Create your own virtual MFA device in IAM, log out, then log back in using the token successfully before you can interact with any services.
Lastly, you'll need to create your own access keys.
Password Policy Details
Minimum Password Length of 20 Characters
One Uppercase Letter
One Lowercase Letter
One Number
One non-alphanumeric character
Let me know if you have any issues!

**Comment by stephenBarrs** [comment]
@mydesignrocks I have my AWS access set up and working.  I have tested in Staging but not yet in prod.  Thanks for all the help!

**Comment by jhouse-solvd** [comment]
@stephenBarrs - let us know once you've had a chance to confirm and if we can then close this one out. thank you, sir!
