### ISSUE TITLE
Debt Letters I2 - Downtime alert 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#18973]
The DMC has systems update every day from 12:30am to 3:00am, the Veterans need ot be notified they will not be able to access the information in the Debt Portal from DMC API during that time. 

Info: https://design.va.gov/patterns/messaging-dictionary#scheduled-downtime-notifications

Definition of done: 

- [x] Create designs 

- [x] Create ticket for FE to add to portal

**Comment by rebeccawalsh** [comment]
I worked with Danielle and she provided some content for our use case where it will be down every night:

See the mockups here: https://preview.uxpin.com/067dc9cad4c5966bc8a5f3a400cf10206e6a51d4#/pages/136055677/specification/sitemap?mode=i

**Comment by rebeccawalsh** [comment]
FE Ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19297
