### ISSUE TITLE
Fix runtime error during the error-state of the widget initialization

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#18982]
On React widgets like the `/find-forms/` widget, we show an error message if the widget for some reasons fails to load - generally this is due to an issue downloading the JS. However, on IE, a runtime error occurs while trying to show that error message. We should fix this so that IE shows the proper error message when it occurs.

**Comment by ncksllvn** [comment]
@brianalloyd I noticed a bunch of these errors in Sentry (a system we use to capture errors happening on the website.) This is a quick and easy fix so I grabbed it. Can we add it to our sprint?

**Comment by brianalloyd** [comment]
Done, looks like a quick pick up.  Thanks @ncksllvn

**Comment by ncksllvn** [comment]
Will go live today but no easy way to verify this, as it fixes an issue on slow internet speeds

**Comment by brianalloyd** [comment]
Sounds good @ncksllvn guess we can gauge it over time and validate the intended fix is working.  Thanks for implementing.

**Comment by brianalloyd** [comment]
@ncksllvn closing the ticket, as mentioned we can gauge progress and reopen if needed.  Thanks.
