### ISSUE TITLE
[Design] MyVA LOA3 First-time user experience copy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18992]
## Background information

[Desktop Invision Link 1](https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/screens/443287788) 
[Desktop Invision Link 2](https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/screens/443287789)

## Tasks
- [ ] Work with Peggy to finalize copy for the first-time user case
- [ ] Review with Matt/Samara

**Comment by tressaellen** [comment]
@peggygannon - here are the screenshots for a first time user experience on MyVA.  Let me know if you have any questions!

![My VA FTUX](https://user-images.githubusercontent.com/58752772/105863872-cdab6c80-5f9d-11eb-9427-fdeb62d04e89.jpg)
![My VA FTUX 2](https://user-images.githubusercontent.com/58752772/105863885-d1d78a00-5f9d-11eb-9b87-a7ef0404dcd4.jpg)

**Comment by peggygannon** [comment]
@tressaellen @callen2563 Please see below content recommendations for these two screenshots. Please let me know if you have any questions. We should look at this again once the mockups are updated to make sure recommendations work/make sense. 


here is suggestion for intro content, I recommend also having sitewide content team take a look. 

**My VA**
Welcome to My VA, your personalized guide to the VA benefits and services you’ve earned. You can check the status of your in-progress claims and applications or manage your health care information, like appointments, prescriptions, and messages from your health care team.  
You can also get information about how to apply for and manage other VA benefits you may be eligible for. 

Go to profile> change TO: Go to your profile


Apply for benefits> change TO: Apply for VA benefits
Benefits you might be interested in> change TO VA benefits you may be eligible for

**Health care**
With VA health care, you’ll receive coverage for the services you need to help you get and stay healthy, like regular checkups with your health care provider and appointments with specialists. 
{CTA button} Apply for VA health care 
QUESTION: will this button take users directly to health care application?


**File a claim>change TO Disability compensation**
With VA disability benefits, you can get disability compensation for an illness or injury that was caused, or made worse, by your military service. 
{CTA button} File a disability claim
QUESTION: will this button take users directly to the disability application?

**Education benefits**
GI Bill benefits can help Veterans, service members, and their qualified family members find the right college or training program, pay for school, or get education and career counseling.  
{CTA button} Apply for VA education benefits
QUESTION; will this button take users directly to the education application?

------

2nd screenshot

Dates shouldn’t be rendered in ordinal time
for example, January 22 NOT January 22nd

Apply for VA benefits
QUESTION: Can we be more specific about the number of applications in progress. Like could we say: 

You have [x] applications in progress
You have no applications in progress

Card 
card

**Comment by callen2563** [comment]
@peggygannon @tressaellen Is it possible to cut the healthcare card copy down a bit? Also the copy for the education benefit CTA is a tad too long. Let me know your thoughts. thanks! 
![My VA FTUX](https://user-images.githubusercontent.com/68560244/107078837-ed703b00-67bc-11eb-8c2a-4efd2cfc8625.jpg)

**Comment by peggygannon** [comment]
Hi, @callen2563 will take a look,  and offer some additional recommendations.. thx!

**Comment by peggygannon** [comment]
Hello, @callen2563 please see below for recommended trims to these two chunks of content/CTA. Please let me know if you have any questions or need add'l cuts. 


**Health care**
With VA health care, you’ll receive coverage for services like regular checkups with your health care provider and specialist appointments.
{CTA button} Apply for VA health care
QUESTION: will this button take users directly to health care application?

**Education benefits**
VA education benefits help Veterans, service members, and their qualified family members with needs like finding the right school or training program and paying tuition. 
{CTA button} Apply for education benefits
QUESTION: will this button take users directly to 1990 EDU application?

**Comment by callen2563** [comment]
@peggygannon @tressaellen I've made the copy updates it looks much better :) Yes, to both of your questions about the CTA's.

![My VA FTUX](https://user-images.githubusercontent.com/68560244/107393726-1ba98f80-6ac9-11eb-9a4e-04843f85ce4f.jpg)

**Comment by peggygannon** [comment]
thanks, @callen2563!  It looks like My VA is scheduled for a usability prep review on Friday... I'll be reviewing the My VA prototype updates as part of my CC review.  Thx!
