### ISSUE TITLE
Onboarding Screen #2 - Appointments

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18998]
## User story
As a user, I want an onboarding flow the first time I enter the app so that I understand how to navigate the app.

## Acceptance Criteria
1. Create UX/UI for Onboarding Screen #2: Appointments
2. Rules for when this screen appears:
     - This screen displays after selecting "Continue" from Onboarding Screen #1
     - This screen should only display the first time a user logs into the app. On subsequent logins, this screen should not appear
3. All copy is hard coded
4. Pull in carousel CC
     - Left button: Skip
     - Right button: Continue (routing not needed for this story)
     - Dot #2 in the carousel should be active
5. "Skip" button closes out this screen and takes the user to the Home page

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/439613502

## Corresponding UX ticket
#13483

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark "Easily track your appointments" as Header 2

**Skip button**
- accessibilityLabel= "skip”
- accessibilityHint= "Exit onboarding tutorial and navigate to the Home page"
- accessibilityRole= “button”

**Continue button**
- accessibilityLabel= "continue”
- accessibilityHint= "Continue to the Claims and Appeals onboarding page"
- accessibilityRole= “button”

**Carousel indicators**
- accessibilityLabel= "Carousel indicators”
- accessibilityHint= "Viewing page 2 of 4 of the onboarding tutorial"
- accessibilityRole= progressbar

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/10/2021 - Looks good on Android and iOS.  Closing.
