### ISSUE TITLE
[Design] MyVA LOA1 copy 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18990]
## Background

[Desktop Invision Link](https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/screens/443287792)

## Tasks
- [ ] Work with Peggy to finalize copy for LOA1 use case
- [ ] Review with Matt/Samara

**Comment by tressaellen** [comment]
@peggygannon - here are the screenshots for the LOA1.  Based on [previous conversations](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18043) - we need to update the copy in this alert to better reflect what users can access on this page.  So maybe something about accessing claims, health care, and benefit information.

**Verify your identity to access more VA.gov tools and features**

We need to make sure you’re you - and not someone pretending to be you - before we can give you access to your personal and health-related information.  This helps to keep your information safe, and to prevent fraud and identity theft.  

**This one-time process takes about 5-10 minutes.**

[Verify your identity]

![My VA LOA1](https://user-images.githubusercontent.com/58752772/105867110-2b8d8380-5fa1-11eb-8d0b-80798b9ba4ad.jpg)
![My VA LOA1 (2)](https://user-images.githubusercontent.com/58752772/105867127-30eace00-5fa1-11eb-9490-533c39dbed90.jpg)

**Comment by tressaellen** [comment]
Here's a rough first pass at this.

**Verify your identity to access more personalized tools and features**

We need to make sure you’re you - and not someone pretending to be you - before we can give you access to your claims, benefits and health-related information. This helps to keep your information safe, and to prevent fraud and identity theft.

This one-time process takes about 5-10 minutes.

[Verify your identity]

**Comment by peggygannon** [comment]
@tressaellen @callen2563 Please let me know if you have any questions. 

**Verify your identity to access more online tools and features**
We need to make sure you’re you - and not someone pretending to be you - before we can give you access to your personal and health-related information.  This helps to keep your information safe.
Once you verify your identity, you’ll be able to access more features to help track and manage your benefits, like checking the status of your claims or sending a secure message to your health care team. 

**This one-time process takes about 5-10 minutes.**

{CTA button} Verify your identity

**Comment by callen2563** [comment]
@peggygannon @tressaellen (need to cut down copy in healthcare card and education CTA)
![My VA LOA1](https://user-images.githubusercontent.com/68560244/107080697-a3d51f80-67bf-11eb-9949-5028ced683ad.jpg)

**Comment by peggygannon** [comment]
Hi, @callen2563 I provided recommendations for trimming EDU and health care content in this ticket: 
https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/18992

**Comment by callen2563** [comment]
@peggygannon @tressaellen Thanks! This copy has been updated.. 
![My VA LOA1](https://user-images.githubusercontent.com/68560244/107394996-6e377b80-6aca-11eb-96ad-abad5711db43.jpg)
