### ISSUE TITLE
[Design] MyVA LOA3 user who has everything copy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18995]
## Background

[Desktop invision link](https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/screens/443287786)

## Tasks
- [ ] Work with Peggy to finalize copy for LOA3 user with everything use case
- [ ] Review with Matt/Samara

**Comment by tressaellen** [comment]
@peggygannon - this is the screenshot for if a user has claims, healthcare, applications in progress and has updates in each of these. 

Everything is open for review *except for* the title (MyVA) and anything that is in the grey boxes (those came from the design system).

_Note_ - the related links in the health care section need to be consolidated into 1 link since they go to the same place. 

Let me know if you have any other questions.

![My VA Desktop Everything](https://user-images.githubusercontent.com/58752772/105864323-47435a80-5f9e-11eb-8418-f74e1ce03434.jpg)

**Comment by peggygannon** [comment]
Hi, @tressaellen question: regarding this  note: *Note - the related links in the health care section need to be consolidated into 1 link since they go to the same place*.

where will this consolidated link take users?

**Comment by tressaellen** [comment]
@peggygannon the link will take them to https://staging.va.gov/health-care/get-medical-records

**Comment by peggygannon** [comment]
@tressaellen @callen2563 Please see below for recommendations to this screenshot. Let me know if you have any questions. I would like to see this again once mockup is updated to make sure recommendations work/make sense.


Top bar: 40% Service connected
Recommend updating TO one of the below to make this content more clear. I realize the 2nd one might be a tad long??
Your disability rating: 40% service connected OR
You have a 40% service-connected disability rating

Dates shouldn’t be rendered in ordinal time
January 22 NOT January 22nd

Go to profile should be> Go to your profile

Claims and appeals
Can we update headers to follow this pattern?  [benefit type] claim received [date]
For example: 
Disability compensation claim received [date]
Education benefits claim received [date]
Health care benefits claim received [date]


Health care section
What do you think about the updates to card headings? I'm recommending this o take into account if a user doesn't have a "latest message" or if a user "has more than 1 upcoming appointment on same day"


Latest message> Messages
Next appointment > Appointments
Prescription update > Prescriptions


What would the Message or Appointment card look like if a user has two appointments or two messages for the same day? 

For the Appointment card, can we put the **type** of appointment in the card info?  


Links under health care cards
I recommend updating them to: 
You have 2 unread messages.
You have 6 upcoming appointments. 
You have 3 prescription updates.


Change “Related links” header TO>Manage your health care benefits

[Get your lab and test results](https://www.va.gov/health-care/view-test-and-lab-results/)
[Get your VA medical record] (https://www.va.gov/health-care/get-medical-records/)


Apply for benefits change TO> Apply for VA benefits

QUESTION: Can we be more specific about the number of applications in progress? 
Could we say:

You have [x] applications in progress
You have no applications in progress

{CTA button} Continue application change TO> Continue your application

Benefits you might be interested in change TO>VA benefits you might be eligible for

**Comment by callen2563** [comment]
@peggygannon @tressaellen 
Hi Peggy, I've updated the copy per your suggestions, the only issue I ran into was on the blue box / links on mobile. I wasn't able to fit "you have 2 new appointments / prescriptions" in that space. Do you have any suggestions on how to shorten those? Thanks!  
![My VA Mobile](https://user-images.githubusercontent.com/68560244/106813492-0eab1d00-663f-11eb-9ceb-7a60c1b49f23.jpg)

**Comment by peggygannon** [comment]
Hi, @callen2563 @tressaellen 

We could remove the "You have" from the link and just start with the number. Like this:
I recommend also checking with @joshkimux to see if there are any accessibility concerns with not having a full sentence there 

2 unread messages
6 upcoming appointments 
2 prescription updates


Also I want to be sure we update this button CTA to the below? This button appears in other places on VA.gov and we should be consistent in the language: 
{CTA button} Continue application change TO> Continue your application

**Comment by joshkimux** [comment]
@peggygannon I believe the purpose of the link is clear with "2 unread messages"! It would fail if they were just "messages" or "appointments" but the number and description provide a good amount of context 👍

**Comment by callen2563** [comment]
@peggygannon @tressaellen 
![My VA Desktop](https://user-images.githubusercontent.com/68560244/107081016-0e865b00-67c0-11eb-8ba3-0e4aa62c70ce.jpg)

**Comment by peggygannon** [comment]
Hi, @callen2563 I provided recommendations for trimming EDU content in this ticket: 

https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/18992

**Comment by callen2563** [comment]
@peggygannon @tressaellen This copy had also been updated..

![My VA Desktop](https://user-images.githubusercontent.com/68560244/107395364-ba82bb80-6aca-11eb-8fef-135f3635a162.jpg)
