### ISSUE TITLE
Onboarding Screen #1 - App overview

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18997]
## User story
As a user, I want an onboarding flow the first time I enter the app so that I understand how to navigate the app.

## Acceptance Criteria
1. Create UX/UI for Onboarding Screen #1. Rules for when this screen appears:
     - This screen displays to the user after they've logged in, immediately before they see the authenticated Home screen
     - This screen should only display the first time a user logs into the app. On subsequent logins, this screen should not appear
2. Display the VA logo at the top of the screen (left-aligned, along with the content below it)
3. In Header 2, "[name]" is dynamic and should display the user's **first** name, as it's returned from the Profile endpoint
4. Hard-coded copy below Header 2
5. Pull in carousel CC
     - Left button: Skip
     - Right button: Continue (routing not needed for this story)
     - Dot #1 in the carousel should be active
6. "Skip" button closes out this screen and takes the user to the Home page

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/439611290

## Corresponding UX ticket
#13483

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark "Welcome to VA Mobile, [name]" as Header 2

**Skip button**
- accessibilityLabel= "skip”
- accessibilityHint= "Exit onboarding tutorial and navigate to the Home page"
- accessibilityRole= “button”

**Continue button**
- accessibilityLabel= "continue”
- accessibilityHint= "Continue to the Appointments onboarding page"
- accessibilityRole= “button”

**Carousel indicators**
- accessibilityLabel= "Carousel indicators”
- accessibilityHint= "Viewing page 1 of 4 of the onboarding tutorial"
- accessibilityRole= progressbar

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
**Designs**
![Screen Shot 2021-02-08 at 1.39.09 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/3a918511-0761-4fe4-9f60-fdc755957f9d)

@bridgethapner @ayushchak looping you both in here on how @komaly15 implemented these screens. The designs above indicate that the text in the middle of the screens is centered, but the VA logo breaks that and is slightly above the text. There were feasibility challenges with implementing the content like this, so we've centered all of the content in the middle, like so: 

**Build**
![Screen Shot 2021-02-08 at 1.16.01 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d2cd8ebe-c8f3-49c9-8681-514d19707128)

Let us know if this is something you'd like us to revisit, or if this implementation meets the requirements. If we don't want the content centered and it should be closer to the top, we can do this - we'd just need a guideline along the lines of "All content is ### pixels from the top of the screen."

**Comment by bridgethapner** [comment]
Hi Bess and Komal - this looks GREAT to me & definitely meets the requirements. It's exciting to see onboarding in the build!

**Comment by digitalken** [comment]
PASS 2/10/2021 - Looks good on Android and iOS.  Closing.
