### ISSUE TITLE
Expand unit test coverage of GI Bill Comparison Tool 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#190]
Problem: 
- Unit test coverage of GI Bill Comparison Tool is too low to detect / prevent regressions 

Goal:
- Improve defect prevention by expanding unit test coverage

Notes:
- Review existing tests and ensure critical UX paths have coverage 
- Consider recent work and problems with the GI Bill Comparison Tool when deciding what to test
- Use your discretion when testing complicated logic- if the work results in brittle or difficult to maintain tests, consider breaking the work into refactoring + unit testing tickets 
- Currently there's not an easy way to see unit test coverage for an app. See #184. Use your discretion to determine when this work is done

**Comment by timwright12** [comment]
GI test coverage for lines is 76.72% via the coverage report: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report

The stated goal is 75%, some items dip into the 60s, but not enough to merit a ticket. Going to close this out.
