### ISSUE TITLE
[Product Discovery] COVID-19 Vaccine Finder - VA Data Distribution

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#19009]
### Description

Google has announced that the company will soon display locations that offer Covid-19 vaccinations in its Search and Map products, further bolstering awareness of the virus — and how to avoid it.

The feature is rolling out in the coming weeks, beginning in four states: Arizona, Louisiana, Mississippi and Texas. Google (GOOGL) announced Monday (1/25/2021) that searches for "vaccines near me" have increased five fold since the beginning of the year and it's implementing this feature to ensure it is "providing locally relevant answers."

The VA is already supplying information about local facility COVID-19 testing via data aggregator Castlight, which Google sources for its Search and Map testing listings.  [More details here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11568).

Google will reportedly rely on Castlight and [VaccineFinder.org ](https://vaccinefinder.org/) as suppliers of vetted COVID vaccine information.

### What Needs to Happen 

- [ ] VA.gov Search team will find out more about how this info will be collected and distributed via Castlight and VaccineFinder.org (Assigned to @johnhashva )
- [ ] Once more information is known -- e.g. the data format, how it will be displayed, if it will allow for specific VA information that needs to be included in any listing -- report back to VA product and communications leadership (@lalexanderson-dsva + @davidconlon + VHA Digital Media Comms) to determine next steps.
- [ ] If the decision is made to move forward, determine how data/info will be provided -- and by which team.

**Comment by johnhashva** [comment]
2/17 Update:  Zoom call held with Sophia Golden of Castlight and Kara Sewalk of Boston Children's Hospital to discuss in more detail how VA.gov COVID vaccine VAMC availability and distribution data might be made available on both VaccineFinder.org and to Google for Search and Maps.   Castlight is acting as the data/technology provider powering the BCH-managed VaccineFinder.org site with the CDC 

As a follow up, Castlight provided the data import document for providers reporting inventory through VaccineFinder. The relevant information for public display is also listed in the document. Additionally they included a link to the enablement material they share with providers on how to load this file. I have also attached a template with the required fields highlighted. Again, we have not landed on a path forward for ingesting data that is just for public display and will not be shared back with CDC, so this may change. That being said, this should give you a sense of the data fields we will be collecting. 
 
- [Data Import Document](https://vaccinefinder.org/resources/VaccineFinder_Data.Import.Document_V3_20210209.pdf)
- [Quick Start Guide Public Display Information File Upload](https://vaccinefinder.org/resources/Quick.Start.Guide.for.Vaccine.Finder.Public.Display.Information.Fields.-.File.Upload.w.Phone.pdf)

Attached is the template with the Vaccine provider required data fields highlighted.  As of mid-Feb, a path forward for ingesting data that is just for public display and not be shared back with CDC, had not yet been decided.. That being said, the Excel should give VA.gov a sense of the data fields Castlight will be collecting. 

[provider-profile-blank-template.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6043181/provider-profile-blank-template.xlsx)

**Comment by johnhashva** [comment]
2/25 Update: VaccineFinder.org launched

Details from news accounts:

The Centers for Disease Control and Prevention in partnership with Boston Children's Hospital and Castlight Health is launching a new tool which allows Americans to search for COVID-19 vaccine providers with stock of vaccine where they live. 

- The tool, which builds on the existing VaccineFinder.org platform, will capture inventory data from vaccine providers around the country. 
- In most states, the initial launch is limited to certain providers — those getting vaccine directly from the federal government. In Alaska, Indiana, Iowa, and Tennessee, the tool shows all the vaccine providers, including hospitals, clinics, and public health vaccination sites.
- Residents of those four states can look up their cities or zip codes and find an interactive map of all the places administering COVID-19 vaccines and see which ones have vaccine doses in stock.

**Comment by denisecoveyduc** [comment]
@johnhashva will follow up with @davidconlon to discuss next steps.
