### ISSUE TITLE
Change Online Tool link for form 21-674 in CMS

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#19005]
Editing to reflect slight tweak to URL as of 9/20/2021 per Mikki N. suggestion - still resolves to same place

~~@John Hashimoto~~ Dave Conlon when you have time, can you please change the Online Tool URL for form 21-674 in the CMS, same as you did yesterday for 21-686c?  @Jason let me know we're not ready to link to the va.gov version just yet.  Form page in question is https://www.va.gov/find-forms/about-form-21-674.  

The URL should be  https://www.ebenefits.va.gov/ebenefits/dependents, and later (Jason will let us know)- ~~https://www.va.gov/view-change-dependents/add-remove-form-686c/introduction~~  https://www.va.gov/view-change-dependents/add-remove-form-686c

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO this is done and should go out with today's deploy.   If you will, please check this in production tomorrow AM.

**Comment by MarciMcGuireGCIO** [comment]
Thank you!  Will do!

**Comment by jason-gcio** [comment]
I really appreciate the help, thanks again!

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva @jason-gcio confirming that this change is now on Production.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO + @jason-gcio re-opening this issue as this ebenefits link is now showing "Application Unavailable" and I've temporarily removed the online tool link from the Form 21-674 details page. 

<img width="875" alt="21-674-eBenefits-App Issue" src="https://user-images.githubusercontent.com/63107147/106359848-2a32c280-62e3-11eb-8fa6-5a164c48b770.png">

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO + @jason-gcio + @swirtSJW  Added a working and validated ebenefits online tool link -- https://www.ebenefits.va.gov/ebenefits/about/feature?feature=dependent-compensation -- per Jason.

**Comment by MarciMcGuireGCIO** [comment]
Moving to Icebox until we are "go" to change URL to https://www.va.gov/view-change-dependents/add-remove-form-686c/introduction

**Comment by MarciMcGuireGCIO** [comment]
Hey there @jason-gcio - just checking in to see if there's any movement on needing this link added to Find a VA Form.  LMK!  Thanks!

**Comment by jason-gcio** [comment]
Getting close, I'll have another one for you here soon for the CH31 feature.  I'll ping you though and we can make a ticket for that too.

**Comment by MarciMcGuireGCIO** [comment]
👍🏻 Thanks, @jason-gcio !

**Comment by MarciMcGuireGCIO** [comment]
Howdy do, @jason-gcio.  Scouring through out backlog I ran across this ticket again.  Is this link ready to be changed now?  Thanks!

**Comment by jason-gcio** [comment]
It's pretty close - end of the week prolly?  We are at 80% and turning a corner soon...same for the other ticket (686)

**Comment by MarciMcGuireGCIO** [comment]
Awesome! I'll put those into this Sprint.  Just hit me up when you're ready!

**Comment by MarciMcGuireGCIO** [comment]
@jason-gcio - Are you read for us to replace https://www.ebenefits.va.gov/ebenefits/dependents with https://www.va.gov/view-change-dependents/add-remove-form-686c? Thx!

**Comment by jason-gcio** [comment]
@MarciMcGuireGCIO - we are ready to go!  Let's proceed with that update for 686c + 674 🎉

**Comment by MarciMcGuireGCIO** [comment]
@jason-gcio got it!  Thanks!  cc @davidconlon.   The other ticket is #18985

**Comment by davidconlon** [comment]
@MarciMcGuireGCIO 
Can you confirm the AC's for this

- [ ] Update "Online Tool" for find-forms/about-form-21-686c from https://www.ebenefits.va.gov/ebenefits/dependents to https://www.va.gov/view-change-dependents/add-remove-form-686c
- [ ] Update "Online Tool" for /find-forms/about-form-21-674 from https://www.ebenefits.va.gov/ebenefits/dependents to https://www.va.gov/view-change-dependents/add-remove-form-686c

**Comment by MarciMcGuireGCIO** [comment]
@daveconlon - it's slightly different.  They go to two similar URLs, but not identical:

21-686c goes to https://www.va.gov/view-change-dependents/view
and 21-674 goes to https://www.va.gov/view-change-dependents/add-remove-form-686c

**Comment by MarciMcGuireGCIO** [comment]
@jason-gcio @davidconlon -- confirming that this change is in Prod and links to the correct page.  

**New URL shown in status bar:**
![image](https://user-images.githubusercontent.com/73354907/134170824-f7ddc862-e379-4e02-8439-9d1e4efc4e52.png)

**Page to which it links**
![image](https://user-images.githubusercontent.com/73354907/134170888-01ca6878-ebbe-40de-8f2c-90ee4718d086.png)

**Comment by MarciMcGuireGCIO** [comment]
@jason-gcio - do you mind double-checking which URL we should be linking this form to? @bethpottsVADEPO pinged me on Slack because it appears to be a circular reference.  

Here's the link to the thread on Slack: https://dsva.slack.com/archives/CUB5X5MGF/p1632849162024900

Thank you!
