### ISSUE TITLE
Common component: carousel

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19001]
## Acceptance Criteria
1. Create common component for the carousel, which will appear on the Onboarding screens
2. UI details:
     - Background-color: primary-darker #003E73
     - Header: Mobile Body Bold
     - Body: Mobile Body
     - Standard gutter L/R, marginBetween header and body
     - Carousel controls: 
          - Height: 70px
          - Background-color: #1A5180
          - L/R controls: Mobile Body
          - Padding-bottom (below text): 22px
          - Padding-top (above text): 22px
          - Active carousel dot: #fff
          - Inactive carousel dot: #fff at 50% opacity (if this is overly-complex, use the following hex code as a secondary option: #8CA8C0)
          - Spacing to match design (~6px between carousel dots) 
3. Add animation when navigating between screens in the carousel: slide screens L/R*
     - Note: for initial implementation, there is no way to navigate back to the previous screen (i.e. sliding a card to the Right)
4. Add specs to ReadMe

## Note for dev
We will not need to incorporate swiping gestures for the initial implementation of the carousel - however, we will likely incorporate L/R swiping for a later release. 

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/439611290
![Screen Shot 2021-01-26 at 9.46.38 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/795d99f5-28d8-4037-b9b7-7f230d73d9c9)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/10/2021 - Looks to spec.  Animation works.  Closing.
