### ISSUE TITLE
[Design] MyVA Cerner copy

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19002]
## Background

[Dekstop Invision Link](https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/screens/443287794)

## Tasks
- [ ] Finalize copy with Peggy and Danielle
- [ ] Review with Matt/Samara

**Comment by tressaellen** [comment]
Hello @peggygannon and @DanielleThierryUSDSVA - we are looking for some changes for the Cerner/MHV alert on the new MyVA dashboard. We need a single notification that shows within the health care section if someone is detected to be going to any of the facilities using Cerner and then a CTA for the user to get to Cerner. 

We're hoping to greatly simplify the [current Cerner alert](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13831#issuecomment-700941068) (see mockup below). (I haven't updated any of the copy in what is shown in the mockup- I will leave that to you) Let me know if you have any additional questions or if I can help clarify anything. Thank you!!

![MHV](https://user-images.githubusercontent.com/58752772/105872768-3f3be880-5fa7-11eb-9249-37505c867a37.jpg)

**Comment by Samara-Strauss** [comment]
Thanks for this, @tressaellen!!

@peggygannon @DanielleThierryUSDSVA let us know if you want to regroup on this at all. This drastically simplifies [what we have now](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13831#issuecomment-700941068). As Tressa mentioned, with the new dashboard, having three separate notifications doesn't work. Also, having an alert that effectively takes up more space than the section itself doesn't seem like a smart approach either. I'm hoping we can take a more streamlined approach here that still accounts for the Cerner integration while not totally disrupting people who may also have information in MHV.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @tressaellen @Samara-Strauss! I'll take a look at this by tomorrow and add thoughts.

**Comment by DanielleThierryUSDSVA** [comment]
Made some minor edits for flow. Let me know if this works, @tressaellen @Samara-Strauss. And one question: This is really about just viewing their info, right? Not needing to manage it/use the tools? I think that's right based on the context, but just wanted to make sure. 

**Your VA health care team may be using our new My VA Health portal**

Our records show you’re registered at one or more facilities that now use our VA My Health portal. 

To view all of your information, you may need to sign into My VA Health. To open the portal, you may need to disable your browser’s pop-up blocker. If you’re prompted to sign in again, use the same account you used to sign in on VA.gov.

[Go to My VA Health]

**Comment by Samara-Strauss** [comment]
Thanks for this, @DanielleThierryUSDSVA! Before we give a 👍 or 👎 , we *might* be making a design update here.

@tressaellen @callen2563 this probably (and understandably) got missed yesterday among a million other things you were doing, but could you please [review this convo with Erik/me](https://dsva.slack.com/archives/C909ZG2BB/p1611849117070800) and make the necessary updates to the Cerner mocks? The TL;DR is that we are *not* going to show the rest of the health care section to Cerner users and only show the alert, which means we need a primary CTA to Cerner in the alert (already have that) and a secondary CTA to MHV (need that). And also, if you have serious concerns about the approach, let us know. This is the time to bring those up in case we need to make and finalize other tweaks to the design or copy.

**Comment by yuchunfox** [comment]
Glad to see this issue available as a platform of communication.  Has anybody tried to bring this kind of discussion onto the Teams for the VA public?

**Comment by callen2563** [comment]
@peggygannon @DanielleThierryUSDSVA @tressaellen Let me know if you have any thoughts here. Thanks! 
![My VA Desktop Cerner-MHV](https://user-images.githubusercontent.com/68560244/107086842-89ec0a80-67c8-11eb-90a4-64d03ba6ab46.jpg)

**Comment by callen2563** [comment]
@peggygannon @DanielleThierryUSDSVA @tressaellen Just checking in to see if there are any copy updates needed for this mock. Thanks :)

**Comment by Samara-Strauss** [comment]
It should be "Manage your health care at..." and not "Manage your appointments at..." since people may also be managing prescriptions and secure messages in Cerner. Otherwise, this copy should be fine since it looks like it mostly carries over from the existing copy.

**Comment by peggygannon** [comment]
HI, @callen2563 I don't have any additional edits beyond what Samara addressed above^^

 I do want to confirm that (Using VA My Health) is just placeholder here in this alert, and will not show to the user? 

thx!

**Comment by DanielleThierryUSDSVA** [comment]
That's intended to signal which facility is using the new portal. Good question, though, of whether it's needed?

If we do keep it, we need to switch the word order from "Using VA My Health" to "Using My VA Health." I see that order switch in the original ticket, so we should check the existing alerts as well (I'll check the ones on the unauth pages).
