### ISSUE TITLE
Distance shown on selected provider doesn't reflect sorting used

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#19010]
Steps to reproduce:

1. Go through the CC flow to the CC preferences page
2. Choose Add a provider
3. Sort by current location
4. Choose closest provider
5. See the chosen provider info in the grey box

Actual behavior: provider distance from residential address is shown
Expected behavior: ~~provider distance is shown from the sorting origin selected when choosing a provider, or~~ the distance is omitted

The technically easiest way to fix this is to omit the distance, because in order to have the correct sorting origin across page changes we'd have to move the sorting method into Redux.

**Comment by laurenernest** [comment]
Do you need Peter's input on this one?

**Comment by jbalboni** [comment]
@laurenernest Yeah, I think if you or him want to tell us which of those expected behavior options is best, that'd be helpful. I haven't gone back and looked at the design to see if that distance is actually shown there.

**Comment by laurenernest** [comment]
Yeah, distance is shown in the designs. 
![image](https://user-images.githubusercontent.com/72046525/106299409-f59f0800-6209-11eb-812b-f8e396c34723.png)

@outerpress If this selected provider view applies to a selection from either the address or location sort list:
- is it the intent that the distance match the sorting distance?
  - if yes, are you ok with removing the distance to resolve this issue and doing the work to show it properly to another ticket, or do we need it done for launch? (I'm good with either so deferring to UX)
  - if no, we can close as working as expected

**Comment by outerpress** [comment]
> is it the intent that the distance match the sorting distance?

Yep, the distance should match the origin selected by location as Jeff described in expected behavior.

> if yes, are you ok with removing the distance to resolve this issue and doing the work to show it properly to another ticket, or do we need it done for launch? (I'm good with either so deferring to UX)

I'd say we need distance. The list makes a lot less sense without it. If I'm just scanning the list, I have to do a lot more work to understand how they're organized without the mileage. Open to other arguments though!

**Comment by jbalboni** [comment]
To clarify, I only meant the distance shown in the card after you select a provider, not the distances in the list.

**Comment by outerpress** [comment]
My bad, I read too quickly. The distance on the selected provider will be helpful for keeping context between the list and your selection.  If the data is the same between both list and selection it's easier for me to confirm I picked the right one.

_That said..._ it's definitely not as important to see in the selected provider as it is in the list. So I'd be okay if it was a later addition. But we should add it.

Thanks for the clarification!

**Comment by laurenernest** [comment]
I created a new ticket (#19335) to make the appropriate changes to show the distance by location, and struckthrough that part of the expected behavior for this ticket.

**Comment by narin** [comment]
@laurenernest The fix for this ended up being super quick, so I'm closing out this ticket and connecting my PR to #19335
