### ISSUE TITLE
Contact Center Review for Find a VA Form - Add 'sort by last updated' feature

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#19027]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Find a VA Form - we are adding a new feature to give users the ability to sort search results by "Form Last Updated" date.

### Launch Date
- We plan to launch at 100% on Feb 9

### Version Number
1.2

### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/contact-center/FindVAFormsSearch-ProductGuide.pdf

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by joanneesteban** [comment]
@jwoodman5 - tagging you and the Contact Center team in this ticket!

**Comment by jwoodman5** [comment]
@starlow00 We just got this product guide review. I dropped it in the ready column for when you can have a look. Thanks. cc// @Kimberley2019

**Comment by starlow00** [comment]
Hi @MarciMcGuireGCIO. Do you happen to have the original PowerPoint file for this?

**Comment by MarciMcGuireGCIO** [comment]
Hi Steve, I've archived the earlier versions here:  https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/contact-center/archive

**Comment by starlow00** [comment]
@MarciMcGuireGCIO and @jwoodman5:

v1.2 pptx and pdf are ready. Some images were made larger—requiring minor design tweaks—and the table of contents was adjusted. Questions, please let me know!

[FindVAFormsSearch-ProductGuide_v1.2.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5890069/FindVAFormsSearch-ProductGuide_v1.2.pptx)

[FindVAFormsSearch-ProductGuide_v1.2.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5890071/FindVAFormsSearch-ProductGuide_v1.2.pdf)

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @starlow00 !

**Comment by Kimberley2019** [comment]
This guide was sent to VEO contact center for their review and feedback.  They have until COB of 2/11/2021 to provide any questions or feedback that they may have.  If no response is received by that day, then this ticket will be considered complete and will be closed.

@MarciMcGuireGCIO one of the requirements that the VEO call center has requested is that each product guide and video have a version number.  Would you be able to update the guide to reflect the version number (which is the date that you sent us the guide and/or video).  This will ensure that moving forward, the call center always has the most up to date versions.

**Comment by MarciMcGuireGCIO** [comment]
@Kimberley2019 I can update with the version number.

**Comment by Kimberley2019** [comment]
@MarciMcGuireGCIO thank you so much for being willing to do that.  It was a request that they recently made and we updated our documentation to include those details; however, that was AFTER you had submitted your guide for review.
Thank you for your understanding.

**Comment by MarciMcGuireGCIO** [comment]
Happy to do it!

**Comment by Kimberley2019** [comment]
Hi @MarciMcGuireGCIO here is an example: FindVAFormsSearch-ProductGuide_**v01-21-2021**.pptx

I have bolded the desired version number format in the example above.

**Comment by MarciMcGuireGCIO** [comment]
Thank you! :)
