### ISSUE TITLE
JSON Parity - health_services_listing transformer

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19033]
## Acceptance Criteria

- [ ] The transformer diff tool generates zero diffs from the health_services_listing transformer (non-arrays)

**Comment by mpelzsherman** [comment]
Reducing estimate to 3 because the diff tool now reports only one issue:

```js
  {
    "diffType": "Property Missing",
    "path": "fieldOffice/targetId",
    "graphQL": 2356
  }
```

**Comment by mmiddaugh** [comment]
Archiving this issue but keeping track by linking in Facilities Transformer support (collection of issues) #17956
