### ISSUE TITLE
JSON parity - health_care_region_page transformer

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19032]
## Acceptance Criteria

- [ ] The transformer diff tool generates zero diffs from the health_care_region_page transformer

**Comment by mpelzsherman** [comment]
The diff tool array data has some major differences in the array lenghts:

```js
{
  "diffType": "Array Length",
  "path": "reverseFieldRegionPageNode.entities",
  "graphQL": 7,
  "cmsExport": 59
}
``` 
Not sure what’s going on there. I’m guessing the filter in the transformer isn’t doing the same thing as the graphql query filter?

**Comment by mmiddaugh** [comment]
Archiving this issue but keeping track by linking in Facilities Transformer support (collection of issues) #17956
