### ISSUE TITLE
JSON parity - press_releases_listing transformer

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19039]
The new transformer diff tool is generating many false positives due to fields that are either 1) not needed by the templates or 2) not included in the GraphQL queries or transformers.

## Acceptance Criteria

- [ ] The transformer diff tool generates zero false positives due to unused fields in the press_releases_listing transformer transformer

**Comment by mpelzsherman** [comment]
Diffs with the latest tool [changes](https://github.com/department-of-veterans-affairs/vets-website/pull/15971):

```js
  {
    "diffType": "Property Missing",
    "path": "fieldOffice/targetId",
    "graphQL": 318
  },
  {
    "diffType": "Property Missing",
    "path": "fieldOffice/entity/title",
    "graphQL": "VA Pittsburgh health care"
  }
```

**Comment by mmiddaugh** [comment]
Archiving this issue but keeping track by linking in Facilities Transformer support (collection of issues) #17956
