### ISSUE TITLE
Add screen tracking for analytics

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#19047]
## Task overview
In order to identify opportunities for enhancement, we will need to track time spent on screens. 

## Acceptance criteria
1. Add screen tracking with the React Navigation and React Native Firebase libraries. Reference the following links for instructions: 
     - https://rnfirebase.io/analytics/screen-tracking#react-navigation
     - https://reactnavigation.org/docs/screen-tracking/
2. Provide analytics on how long a user spends on each screen

**Comment by ayushchak** [comment]
* Screen tracking to see how long a veteran spends on each screen (time to complete a transaction, etc.)
* Specific discovery needed to address points where errors come up 
* Links above will have instructions on action steps
