### ISSUE TITLE
JSON parity for story_listing transformer

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19040]
The new transformer diff tool is generating many false positives due to fields that are either 1) not needed by the templates or 2) not included in the GraphQL queries or transformers.

## Acceptance Criteria

- [ ] The transformer diff tool generates zero false positives due to unused fields in the story_listing transformer

**Comment by mpelzsherman** [comment]
Dropping estimate to 3 since the diff tool now reports only one diff:
 ```js
  {
    "diffType": "Property Missing",
    "path": "fieldOffice/targetId",
    "graphQL": 2356
  }
```

**Comment by mmiddaugh** [comment]
Archiving this issue but keeping track by linking in Facilities Transformer support (collection of issues) #17956
