### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by ayushchak** [department-of-veterans-affairs/va.gov-team#19049]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

Ayush Chakravarty
ayush@adhocteam.us

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [X] Google Analytics
- [X] Domo
_Please list any additional requirements, if any._

Requesting domo to understand if we can leverage it for VA Mobile app - but if it's not available for us, that's fine.

## Date Required
_As soon as feasible_

## Product Team / External Team / VA Office
_VA Mobile App_

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @ayushchak, 

You should have received an invite to both DOMO and Google Analytics. 

We will close this out but please feel free to reopen if you have any access related issues/concerns. Thanks
