### ISSUE TITLE
BUG - DISCOVERY - Missing provider in VA.gov Community Care provider results

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#19045]
## What happened?
Veterans who search for Community Care providers are not getting full results - some providers are missing.

Location: Waterbury, CT, 06708-1459, Lat/Long 41.56,-73.06
Facility Type: Community Providers (in VA's network)
Specialty: Occupational Therapist (225X00000X)

https://www.va.gov/find-locations/?page=1&address=06708-1459&facilityType=provider[…]context=Waterbury%2C%20Connecticut%2006708%2C%20United%20States

## Specs:
- Device: All
- Browser: ALL
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/find-locations/?page=1&address=06708-1459&facilityType=provider&serviceType=225X00000X&location=41.56%2C-73.06&context=Waterbury%2C%20Connecticut%2006708%2C%20United%20States
- Test User _(if applicable)_: N/A

PPMS query: https://dws.ppms.va.gov/v1.0/ProviderLocator?address=41.56%2C-73.06&radius=10&specialtycode1=225X00000X&maxResults=10

VA.gov locator is dropping the second result for "ACCESS REHAB CENTERS LLC" located at 134 Grandview Ave

 "CareSite": "ACCESS REHAB CENTERS LLC",
      "CareSiteAddress": "134 GRANDVIEW AVE WATERBURY, CT 06708-2507",
      "CareSiteAddressStreet": "134 GRANDVIEW AVE",
      "CareSiteAddressCity": "WATERBURY",
      "CareSiteAddressState": "CT",
      "CareSiteAddressZipCode": "06708-2507",

## Desired behavior
VA.gov doesn't drop providers _and_ accurately deduplicates providers.

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by darkbushido** [comment]
We currently Deduplicate the data from PPMS in two way

1. Providers are deduplicated by `ProviderIdentifier`, the assumption what that its a unique identifier. 
2. Place of Services are deduplicated by 
    - Street
    - City
    - State
    - Zip
    - care site name
    - caresite phone number
    - latitude
    - longitude
    - provider identifier

This one isn't showing because both locations have the same provider identifier.
```
    {
      "Miles": 0.059499999999999997,
      "Minutes": 0.2167,
      "ProviderName": "ACCESS REHAB CENTERS LLC",
      "ProviderSpecialty": "Occupational Therapist",
      "SpecialtyCode": "225X00000X",
      "HPP": "Unknown",
      "CareSite": "ACCESS REHAB CENTERS LLC",
      "CareSiteAddress": "64 ROBBINS ST WATERBURY, CT 06708-2613",
      "CareSiteAddressStreet": "64 ROBBINS ST",
      "CareSiteAddressCity": "WATERBURY",
      "CareSiteAddressState": "CT",
      "CareSiteAddressZipCode": "06708-2613",
      "CareSitePhoneNumber": "203-267-0406",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "CCN Region 1",
      "NetworkId": 14,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1033293691",
      "Latitude": 41.559462000000003,
      "Longitude": -73.059475000000006,
      "GeoWarning": null,
      "Telehealth": false,
      "SubServices": []
    },
    {
      "Miles": 0.79020000000000001,
      "Minutes": 2.7000000000000002,
      "ProviderName": "ACCESS REHAB CENTERS LLC",
      "ProviderSpecialty": "Occupational Therapist",
      "SpecialtyCode": "225X00000X",
      "PreferredMeansReceivingReferralHSRM": false,
      "PreferredMeansReceivingReferralSecuredEmail": false,
      "PreferredMeansReceivingReferralMail": false,
      "PreferredMeansReceivingReferralDirectMessaging": false,
      "PreferredMeansReceivingReferralFax": false,
      "ProviderType": "GroupPracticeOrAgency",
      "HPP": "Unknown",
      "CareSite": "ACCESS REHAB CENTERS LLC",
      "CareSiteAddress": "134 GRANDVIEW AVE WATERBURY, CT 06708-2507",
      "CareSiteAddressStreet": "134 GRANDVIEW AVE",
      "CareSiteAddressCity": "WATERBURY",
      "CareSiteAddressState": "CT",
      "CareSiteAddressZipCode": "06708-2507",
      "CareSitePhoneNumber": "203-573-7130",
      "WorkHours": null,
      "ProviderGender": "NotSpecified",
      "ProviderNetwork": "CCN Region 1",
      "NetworkId": 14,
      "ProviderAcceptingNewPatients": false,
      "ProviderPrimaryCare": false,
      "QualityRanking": null,
      "ProviderIdentifier": "1033293691",
      "Latitude": 41.560164,
      "Longitude": -73.060948999999994,
      "GeoWarning": null,
      "Telehealth": false,
      "SubServices": []
    }
```

```
 "ProviderIdentifier": "1033293691",
```

**Comment by davidconlon** [comment]
here's what I'm thinking, knowing it's not a perfect solution (see below, for discussion)

I realize that this proposal will show _both_ the "Group Practice/Agency"  followed by any and all "Individual" doctors who might be part of that group practice/agency, but I think more is better than less, as long as they aren't duplicated.

Thoughts?


If "ProviderType": "GroupPracticeOrAgency"

Deduplicate on

o	Street
o	City
o	State
o	Zip
o	care site name
o	caresite phone number
o	latitude
o	longitude
o	provider identifier


if "ProviderType": "Individual"

Deduplicate on

o	Provider Name
o	Street
o	City
o	State
o	Zip
o	latitude
o	longitude
o	provider identifier

**Comment by mmiddaugh** [comment]
Seems we should remove the provider identifier as a dedup attribute if it isn't a unique item
Also, how might dedup impact future pagination?
