### ISSUE TITLE
PIF issues - too many claims

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#19078]
## User Story
As a veteran, I don't want to go through an application all the way to the end and find out I have submitted "too many claims".

## Expected Behavior
One of the errors a lot of veterans are getting:

> Claim could not be established. Contact the BDN team and have them run the WIPP process to delete Cancelled/Cleared PIFs

The person we need to talk to is named Epharm Bogale <epharm.bogale@evokeconsulting.com>.  They are the ones that own this PIF process and already have a way to clear the PIF.  Not sure what PIF stands for.

## Acceptance Criteria
- [ ] We create a ticket to add a message to veterans on what to do OR
- [ ] The BDN team has a CRON job or equivalent that does this before it becomes an issue

**Comment by luke-gcio** [comment]
Previous ticket where we just started to retry these issues #11351.

**Comment by annaswims** [comment]
I was mistaken in sprint planning when I mentioned #11351. That handled when the PIF was"in use" not when there were too many.

**Comment by annaswims** [comment]
Validate that this is an error we actually see before digging in more.

**Comment by annaswims** [comment]
Where did the "a lot" info come from @luke-gcio? I see that this has affected 8 veterans over the past 90 days. 

In case we decide do some sort of automated alert this will find affected submissions
`jobs = Form526JobStatus.where(job_class: "SubmitForm526AllClaim", updated_at: [90.days.ago..Time.now]).where("error_message like '%PIFs%'")`

**Comment by annaswims** [comment]
PIF stands for Pending Issue File

**Comment by vhenry07** [comment]
Awaiting email response from Epharm Bogale.

**Comment by luke-gcio** [comment]
Thanks, @annaswims, I should not have said "a lot". After talking to Harlow it seems to be what you said.  In my convo with @vhenry07 I did mention it should be lower priority (if we do some dev for it) but for now I have reached out to the contact to see whether this is something that can be handled on their end.

**Comment by vhenry07** [comment]
Another email sent 2/16.

**Comment by vhenry07** [comment]
Closing - no response from contact.
