### ISSUE TITLE
Error | Claims & Appeals unavailable

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19079]
## User story
As a user, I want to know when I cannot access my claims & appeals because of an upstream error.

## Acceptance Criteria
1. Create UI for an error state when claims and appeals cannot be loaded
     - This error is triggered when both the claims and appeals services are unavailable
2. Hide the segmented selector at the top of the page
     - The mobile alert should be 20px from the bottom of the blue page header (see attachment below)
3. Pull in mobile alert CC
     - Copy is hard-coded:
          - Header 2: Claims and appeal status are unavailable
          - Supporting copy: VA Mobile App is having trouble loading claims and appeals information at this time. Please check back again later.
4. There should not be any page content to display below the mobile alert, aside from the nav bar

## Designs
None for this error state. Use this as a general reference:
![Screen Shot 2021-01-26 at 1.30.20 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c40dc586-db9b-464c-a712-1d85ee2dfdbf)
Mobile alert is 20px from the bottom of the page header:
![Screen Shot 2021-01-26 at 1.42.40 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/302364bf-47ae-43d5-be4a-4f87d4bb8f72)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 
**Mobile Alert**
- Mark "Claims and appeal status are unavailable" as Header 2

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
PASS 1/29/2021 - UI is good on both Android and iOS.  "VA" pronounced as "Vaw" so tagged onto another Claims bug for an error notification doing the same thing.  iOS is good.  closing.
