### ISSUE TITLE
Deprecate content in vets.gov/Practice Areas/Research that has been copied over to va.gov-team/platform/research

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#1907]
## User Story
As a VFS team member who might land on research documentation in the vets.gov-team repo, I need to know that that content is out of date so that I don't use it to conduct research.

## Goal
All old content in the vets.gov-team/Practice Areas/Research repo that has been copied over into the new repo should be marked as out of date and no longer in use. 

## Definition of Done
- [ ] Matt to draft language and formatting that can be pasted at the top of all outdated content on the vets.gov-team repo to identify that content as outdated and no longer in use
- [ ] Matt, @mnorthuis , @meganhkelley  (and Andrea? Rachael?) to connect on which files should have the drafted "this is outdated" language
- [ ] Matt to paste drafted language at the top of all documents in vets.gov-team/Practice Areas/Research as determined by group in step above. Question: can this be done by an engineer?
- [ ] This story has been assigned to an epic

**Comment by accbjt** [comment]
Here is a sample csv file of how the references document should look like when doing the deprecation. We will use this file with our script to deprecate the file.

https://drive.google.com/a/oddball.io/file/d/1P8pNvW0Ko7wn4hVhC9G70jD5tJBTBtLO/view?usp=sharing
