### ISSUE TITLE
Confirmation screen for photo/file upload

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19086]
## User story
As a user, I want to see a confirmation page after I've hit "Upload" that tells me this action is final and cannot be undone, along with options to "Confirm upload" or "Go back".

## Acceptance Criteria
1. Upon hitting "Upload" on the File Upload or Photo Upload page, route the user to a new page where they can confirm that they want to upload their files
     - Header 1: File upload
     - No Back or Cancel buttons in the header
     - Copy (Mobile Body): "Please confirm you are ready to send your [Request Title] for processing."
     - Large Button CC (primary action): "Confirm upload"
     - Large Button CC (secondary action): "Cancel"
2. Selecting "Cancel" returns the user to the previous page
     - Upon returning to the File/Photo Upload page, any files/photos that the user had previously uploaded should still appear
3. Selecting "Confirm upload" will trigger the photo/file upload, and route the user to the success screen (#18612) 

## Designs
None - use this screen as a reference for text & 2 large buttons:
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/441815124

Reference for how this page fits into the current flow:
![Screen Shot 2021-01-26 at 8.14.27 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/5db09311-490f-4e5e-8673-fe8f69e4531c)

## Accessibility Implementation Guidelines 

**Confirm upload button**
- accessibilityLabel= “Confirm upload”
- accessibilityHint= "Upload your information to VA for processing"
- accessibilityRole= “button”

**Cancel button**
- accessibilityLabel= "Cancel”
- accessibilityHint= "Cancel and go back to the upload page"
- accessibilityRole= “button”

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
Hi @bridgethapner, after testing out the File Upload flow in the app, we thought it could be beneficial to add some form of confirmation button after a user has hit "Upload", since this action cannot be undone. 

Curious to hear your thoughts though and whether or not you think this is something we should incorporate as a fast-follow! 

![image (1).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b6a67b02-4327-48bc-977d-34bf1b1cf9cc)

**Comment by bridgethapner** [comment]
This sounds great! Thanks for flagging this - agree this is a good idea considering the finality of the action.

I don't think I'll have time to get to design work here until after the research weeks. Could we add a screen for now with some CC elements as a placeholder to come back and refine in the coming sprints? Maybe something like: 

Text: Please confirm you are ready to send your [file name] for processing (Mobile Body) 
Button: Confirm upload (using Large Button CC) 

Let me know what you think!

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/1/2021 - iOS and Android, UI and Accessibility.
