### ISSUE TITLE
Update copy for null Appeals

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19081]
## Acceptance Criteria
1. Make the following copy changes to the null Appeals message*: 
     - Header 2: You do not have any appeals
     - Supporting copy: This app shows only completed applications but you don't have active appeals.

*Note: this message occurs on the Claims Error state when the user does not have any Appeals on file

## Designs
![Null appeals.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/60849313-0d0d-4204-964a-ae182fcfeef0)

## Related ticket
#18244

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/9/2021 - Updated text as expected.  Closing.
