### ISSUE TITLE
Explore Closed Caption Transcripts for Campaign Landing Pages (508/a11y Recommendation)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#19082]
## Issue Description
_This is an exploratory ticket to determine future direction of Closed Caption Transcripts for CLP as recommend by a11y team._

## Issue Defined
Youtube supports closed captioning out of the box in the iframes. the text can be specified manually by the video owner in youtube, otherwise is generated automatically by speech recognition.

Should we consider transcript options for all users and for accessibility SEO. this will need to wait until we've had a chance to think more holistically about Digital Asset Management and the future of VA Youtube integration with CMS before adding functionality to the CMS that doesn't exist in youtube. Some questions to ask are: Who would create these transcripts? Do media production teams at VA already do this, as part of the manual CC?

**A11y Feedback:** It would amazing if transcripts could be added as a field even if Youtube doesn't necessarily support it upstream. It provides a great, and often more comfortable, alternative to having to watch an actual video for just about everyone-- especially for people with low bandwidths or who are both Deaf and blind! There's also SEO benefits and it helps users search /scan through information faster when they're short on time.

Design Mock Up:
![110029925-1247c780-7d03-11eb-9eb9-b9258f56d647](https://user-images.githubusercontent.com/70410912/112183948-5a506080-8bc4-11eb-89a7-65f4012b2b9c.png)

## Front end tasks
- TBD

## Acceptance Criteria
- [ ] TBD

**Comment by FranECross** [comment]
@laflannery This is the only (old) ticket left in an old epic, and I'm wondering if it's still something that you / the a11y group wants to explore? TIA!

**Comment by FranECross** [comment]
Will not be explored...
