### ISSUE TITLE
FSR content collaboration

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#19096]
## Issue Description

Review FSR content and provide content edits. Team to discuss and collaborate on any questions.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rebeccawalsh. Here's full doc. Capturing in ticket for tracking. Just let me know if you or the team have questions. Thanks!

[FSR content review_danielle_01.25.21](https://app.zenhub.com/files/133843125/5e4b60da-d119-4ae8-b9d0-8b54a41d47a0/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rebeccawalsh. Here's the FSR wizard content. I'm out today for the holiday, but happy to talk over questions, thoughts tomorrow. Also, I'm going to ask our editor to do a double check on phone numbers and check for typos. Thanks! 

[FSR Wizard Mapping-125-danielle](https://app.zenhub.com/files/133843125/dfcea5db-a666-4424-932f-37e442f28b94/download)

**Comment by DanielleThierryUSDSVA** [comment]
[FSR Wizard Mapping-125-danielle_2](https://app.zenhub.com/files/133843125/b5b9ce19-fff4-42d4-960e-7b27b242e1a7/download)

**Comment by rebeccawalsh** [comment]
Thanks, Danielle! I've updated our [github document for this issue here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/design/wizard-design-content.md), so if you have any more adjustments, feel free to edit there! I will be making some quick mockups for each content block to attach as well.

**Comment by rebeccawalsh** [comment]
Here is a link to all of the cards created with this content! https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136854443/simulate/sitemap

**Comment by DanielleThierryUSDSVA** [comment]
This looks awesome, @rebeccawalsh. Thanks so much for the great collaboration on this!

**Comment by RLHecht** [comment]
Pretty sure this ticket can be closed but @DanielleThierryUSDSVA please reopen if you still need it.
