### ISSUE TITLE
Update file request card UI after a successful submission

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19098]
## Acceptance Criteria
After a successful file/photo submission, the following should happen to the card for that File Request:

1. The File Request card should still display on the Request Overview page (i.e. Screen #1 in the design flow below)
2. Hide the large buttons at the bottom of the card ("Select a file" and "Take photos")
3. Between the Request Title and the Request Description, add copy that reflects the date when the successful upload occurred: 
     - Check icon (see attached asset below)
     - Date format: MM/DD/YY
4. Update the following Header 2s so the # of file requests is reduced by 1, and accurately reflects the # of outstanding requests (Screenshot attached below w/ red circles to indicate where these changes should occur):
     - Mobile alert on the Claims Detail page
     - Header 2 in Step 3 of the Claims Step table
     - Header 2 on the File Request page, which appears before the list of file requests. This header will also update when a user has 0 outstanding requests: "You have 0 file requests from VA"
5. Once all file submissions have been successfully uploaded (e.g. 0 open file requests remaining), hide the following from the Claims detail page:
     - Mobile alert: "You have # file requests from VA"
     - Header 2 in Step 3 of the claims table: "You have # file requests from VA"
     - "View File Requests" large button

## Note for Dev/QA
When a user submits their last file request and views the Success mobile alert page, they should be able to go "Back" to the File Request page (as they would in any other scenario). The File Request page will indicate "You have 0 file requests from VA". Once they go "Back" to the Claims Detail page, they will not be able to return to the Request Overview page, as a result of AC #5. 

## Designs
https://camo.githubusercontent.com/9d4586de2d1b460b3f49619392b881cff71b5f0e9dcb226505e6957b3320b77d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f35663233313062392d633166392d346661612d396630302d333838393536313065326131

- Request Overview page w/ a post-submission card:
![Screen Shot 2021-01-26 at 7.47.06 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/37fe6804-7d34-47aa-ae2c-9992296f26ad)

- AC #4: circles indicate which headers should update after a successful submission
![Screen Shot 2021-01-27 at 1.54.14 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/7c418a2f-2a39-42b5-9a38-75c0d283544b)

## Accessibility guidelines
Mark "Uploaded MM/DD/YY" as Header 2

**Comment by bessgreen** [comment]
@bridgethapner are you able to share an .svg of this icon? 
![Screen Shot 2021-01-26 at 8.01.58 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/0073c694-903c-4e5e-8d2a-1571f90690fa)

**Comment by bridgethapner** [comment]
@bessgreen yep! ![fa-check-circle.svg](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/34fe3992-125b-4c7f-a068-4276d7df9d6e)

**Comment by digitalken** [comment]
PASS 2/1/2021 - Android and iOS.
