### ISSUE TITLE
Error photo exceeds max size - Error is not located according to designs

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#19095]
## What happened?
1. The mobile alert error notification is supposed to appear at the top of the page between H1 and H2, but appears below the photo thumbnails at bottom of page.
2. The copy in the error state does not meet the requirements

## Specs:
- Device: Android and iOS

## Steps to Reproduce
1. Upload too large of files to trigger the size error.

## Desired behavior
1. Mobile alert should appear at the top of the page, below Header 1. 
2. Correct copy for error message: "This file cannot be added because it exceeds the maximum file size. You have used [#] MB of the 50 MB limit."
     - This copy should be unbolded

## Acceptance Criteria
![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/2e635e03-020c-4cf2-a77f-948bf57b75c2)

## Bug Severity
- 3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18798

## Screen shot(s) and additional information
Actual screen shots of both iOS and Android showing error locations.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/7fae20d0-fbb6-4e4c-a0ee-38d41f6279bb)

**Comment by bessgreen** [comment]
@digitalken I added a second issue to this ticket regarding incorrect copy. See above as Issue #2.

**Comment by komaly15** [comment]
The file/photo upload error stories didn't make it into the newest build, just verified that the error message has been updated, it just isn't in yet. Moving this to QA @digitalken @bessgreen

**Comment by digitalken** [comment]
PASS 1/28/2021 - Looks good.
