### ISSUE TITLE
Tutorial for all things related to setting up and working Vets-API

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#191]
## User Story

As a VFS developer I want to know how to setup and apply Vets-API, so that I can be proactive about what I might encounter when shipping a PR through to production.

## Considerations

- how to get Vets-API up and running 
- run specs locally
- run rubocop locally 
- access Jenkins 
- access Sentry 
- access a review instance
- access a dev or staging instance
- logging into dev and staging
- test users
- betamocks
- simplecov
- how to run Vets-API and vets-website together
- how to get the cookies from a logged in user to call Vets-API endpoints

**Comment by jholton** [comment]
The docs in `vets-api/docs/setup` have not been updated in over two years. 
As we complete our documentation initiatives, this directory should probably be eliminated to reduce sources of confusion and/or conflicting information.

**Comment by johnpaulashenfelter** [comment]
Docker has handled much of this, onboarding much of the rest. Closing.
