### ISSUE TITLE
Identify and update links on va.gov-team that point to old Research content

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#1910]
## User Story
As a VFS team member, I need to be directed to current Research documentation, so that I can conduct Research correctly. 

## Goal(s)
Identify links on va.gov-team that point to any Research content we just copied over from the old repo. Update those links on va.gov-team so that they point to the new Research content on va.gov-team.

## Definition of Done
- [ ] Work with engineer to identify links that need to be updated.
- [ ] Determine how to update outdated links (can this be done by an engineer, or does it need to be manual?)
- [ ] Update outdated links 
- [ ] This story is assigned to an epic

**Comment by accbjt** [comment]
Here is a sample csv file of how the references document should look like when doing the url replacement. We will use this file with our script to replace the old url with the new url in the file.

https://drive.google.com/a/oddball.io/file/d/1CxnwjuDIzOS600mcgov9yYAYR5Nc8mvm/view?usp=sharing
