### ISSUE TITLE
[Analytics] Research and upload all Staff Profiles for VISN-8, Leadership, Health Services program, etc. [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#19108]
## Story
As a VAMC team member, I need to have all staff profiles ready and loaded in drupal, so I can quickly complete creation, and data load in one visit.

## Goal
- Assure one and done data load to VISN-8 pages upon creation. 

## Resources - Tools - Documentation
[VISN-8 Playbook locations](https://drive.google.com/drive/folders/1YuZ_PJFIEhmOuMhj55oh0lT3aL1uy6Tg)
[Staff reference documents](https://drive.google.com/drive/folders/1mkSEO3YzLLWC5OdM7LDMukT52s_xFaDo)

## Staff Profiles for the the following Health Service Programs
- [x] Leadership Page
- [x] Caregiver-support
- [x]  Homeless-Veteran-Care
- [x] LGBT-Veteran-Care
- [x] Mental-Health_Care
- [x] Minority-Veteran-Care
- [x] Patient-Advocates
- [x]  Returning-Service-Member-Care
- [x]  Suicide-Prevention
- [x] Women-Veteran-Care
* Include photos if available for individual caregivers
* ATTENTION: there may be duplicates, caregivers will support more than one Health Service Program (NOTE: where duplicated) 

## Acceptance Criteria
- [x] All Staff Profiles have been documented for Analytics for creation of Health Service pages.

**Comment by bcastoe** [comment]
Task #19108 - Research and upload all Staff Profiles for VISN-8, Leadership, Health Services program, etc. [BA] - is Complete and moved to Validate.

- Bay Pines Caregiver/Coordinator performed a QA on data previously collected and data loaded to Drupal
- Caribbean Caregiver/Coordinator performed a QA on data previously collected and data loaded to Drupal
- Miami Caregiver/Coordinator performed a QA on data previously collected and data loaded to Drupal
- North Florida South Georgia Caregiver/Coordinator performed a QA on data previously collected and data loaded to Drupal
- Orlando Caregiver/Coordinator performed a QA on data previously collected and data loaded to Drupal
- Tampa Caregiver/Coordinator performed a QA on data previously collected and data loaded to Drupal
- West Palm Beach Caregiver/Coordinator performed a QA on data previously collected and data loaded to Drupal
