### ISSUE TITLE
[Design] MyVA 2.0 Research plan for usability of finalized designs

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19120]
## Background
Now that we have finalized design for MyVA, we need to create a research plan and convo guide in preparation for usability testing.

## Tasks
- [x] Create research plan
- [x] Review with Matt/Samara

**Comment by tressaellen** [comment]
Here is the [Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-research-plan.md) - it's still a WIP just fyi

**Comment by tressaellen** [comment]
@Samara-Strauss - the research plan is ready to be reviewed. I'd love your thoughts on something though - depending on if we want to run a mobile only study vs a desktop study that will effect the number of participants that we need. 

If we just do mobile we will need:
 - 4 ios
 - 4 android 
**(8 total)**

If we do mobile + desktop we will need:
 - 4 ios
 - 4 android 
 - 4 desktop users
**(12 total)** 

This would effect the timeline of the project, so let me know what you think and I can adjust the research plan accordingly. (Right now it's written up as mobile only)
