### ISSUE TITLE
Benefits Summary Letter Verification Screen needs Loading Component

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#19134]
The Benefits Summary Letter Verification Screen currently does not have a loading indicator when first pulling the letter data from the server. This should be updated to follow the current app pattern for loading indicator. 

We will likely need UI/UX to indicate what text to use along with the loader.

**Comment by lexicalninja** [comment]
@bessgreen I think this was taken care of a while ago, right?

**Comment by bessgreen** [comment]
@lexicalninja yep, all letters should have a loading screen. Closing this ticket.
