### ISSUE TITLE
Design Feedback - Usability Testing Prep - Booz Allen - GI Bill Comparison Tool Redesign

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#19159]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- This is full of a lot of complex and new UI... great work! Be sure to test the new pattern top filter and comparison table, and don't forget mobile.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Make all Cancel links blue and underlined in drop downs.
- Move all “Apply” (primary buttons) to the left and Cancel to the right for desktop (see Sketch file for examples) or make the primary button the full width and put cancel below it.
- Remove border and rounded corners the label style on cards (see Sketch/Styles/Cards)
- VAOS recently did some testing around tabs (scheduling/upcoming appt). I am requesting these tabs be added to the design system. Change your tabs to match VAOS
![tabs.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/4f411635-4e28-4353-95a3-012e41a1d2ed)
- On a [school details screen](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055403), bold the table headers in the gray background to be consistent with our [current table styles](https://design.va.gov/storybook/?path=/story/components-table--default) (Eg under Your estimated benefits, bold Gi Bill Pays to school). Similar to the style you use on the [compare table](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055400). Side note: I would not do this for your Tuition and fees section. That is totaling costs so the layout is appropriate there. Considering your table is much more complex than our current table guidelines, you may be placing them side by side to save room, in which case as long as it tests well that would be fine.
- Make the type ahead letters bold and the letters that fill in not bold. There is a search type ahead feature getting ready to go into production (currently in staging) and this will match that ![Screen Shot 2021-01-26 at 10.11.47 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/be4f4e5b-151e-4e9d-b540-97fb612f7853)

**Should:**
- In the top search area it seems there are 2 sections, the search and then filters. I think it would help to label each are with a title of “Search” and “Filter”
- Icons alone don't typically tell users exactly what we want. It might be better to pair the icons with “yes” or “no” text ![Screen Shot 2021-01-26 at 1.58.17 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/528f59d8-e56e-4c59-b4c2-90a211645f66)
- I think the little gray circles by themselves don't make it overly obvious that the user can swipe. Maybe add chevrons or even better would be Previous/Next

**Consider:**
- There is a new list loop pattern the design system council has been working on. On mobile view you could have the primary button large and take up the width and the Cancel (secondary) below it. [See this example](https://www.sketch.com/s/fa4429ed-e901-4eb5-8239-7924020e67da/a/0RdyDG/play)
- Consider removing the chevron form the View Details link. We currently do not have any exact guidelines around the single/double chevron use, however there is a lot going on in this table so removing it may make it look cleaner… or not… just a thought.
- We have been trying to redesign alerts for mobile for a while now. Even on desktop your alerts appear a bit squished. You could try a new design and as long as you include alerts specifically in your user testing we could approve a new style. My suggestion would be trying to place the icon above the alert title or removing the left colored bar. 

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by amyknox** [comment]
Allison - thanks for the thoughtful input.  2 questions for you: 

Under "Must" you specified we should remove border and rounded corners the label style on cards (see Sketch/Styles/Cards). 
 Could you confirm whether this is referencing the pill (yellow arrow) or the card's corners and the white borders (red arrows)
 
![image](https://user-images.githubusercontent.com/41081945/106052324-6eda1600-60b7-11eb-873b-a54bc99f4d2a.png)

You also mentioned the new list loop pattern the design system council has been working on saying "on mobile view you could have the primary button large and take up the width and the Cancel (secondary) below it."

Do you mean it should be applied in an instance such as this https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055354

Thanks!

**Comment by allison0034** [comment]
@amyknox I was referring to the yellow arrow. Those are labels/tags correct? You do bring up a good point about the cards, our Sketch file has those as square as well so if you have time change those to square also. I dont think that will impact user testing so if there is no time you can change it for staging. The label/tag looked a little too much like a button at first glance so it should be changed for user testing.

For the button question, I was thinking in the [filter drop downs](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055348). Looking at our Sketch file and things in production we have it both ways. Primary on left and secondary on right OR full width primary and secondary below it. Since your filter drop downs are narrow (similar to a mobile width) I thought you may want the option.

Sorry, one more thing, I am wondering if you should add a Cancel link to [this drop down](https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055347) too, just to be consistent. Or you could just user test it and see if it is intuitive enough without it.

**Comment by allison0034** [comment]
@amyknox something I just realized, in our design office hours @watersemma showed on the compare table, that the gray school card was sticky when the user scrolled. I dont see that reflected in the prototype. Do you still plan on doing it?

Also, on the compare table, does the gray school card swipe horizontally or will the whole page? Eg if a user scrolls down and is in the tuition section and tries to swipe will it go to the next school? Or will they have to scroll back to the top to switch schools?

Thank you!
