### ISSUE TITLE
EVSS release monitoring and discussions for new 400s

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#19158]
## User Story
As a veteran, I want the 526 form to not break while I am using it.

## Expected Behavior
EVSS is releasing an update that converts the 500s to 400s with details.  We want to make sure we understand what they have changed and that there are no impacts or code changes on our end.

## Acceptance Criteria
- [x] Talk to EVSS about their new 400s, get some documentation

**Comment by annaswims** [comment]
Good news.  It looks like the response Michael emailed is pretty much like [this one](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/support/vcr_cassettes/evss/disability_compensation_form/submit_400.yml) we already test.   So, nothing bad will happen if they roll out changes at any time.  

I think we do want to look at the code [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/evss/disability_compensation_form/service_exception.rb) to make sure we're categorizing the error as non-retryable.

**Comment by annaswims** [comment]
On a related note, it looks like we're getting more attributes in our error messages
(`FILTERED-CLIENTSIDE` is something we filter out)
````json
{
  claim_id: None, 
  end_product_claim_code: None, 
  end_product_claim_name: FILTERED-CLIENTSIDE, 
  inflight_document_id: None, 
  messages: 
  [
    {
    key: form526.submit.establishClaim.serviceError, 
    severity: FATAL, 
    text: Error calling external service to establish the claim during Submit
    }
  ]
}
````

**Comment by edmangimelli** [comment]
> On a related note,[ it looks like ](http://sentry.vfs.va.gov/organizations/vsp/issues/137/events/273ce4b6bc9f4267bbca8b4c3c819ee7/?project=3&statsPeriod=14d)we're getting more attributes in our error messages
> (`FILTERED-CLIENTSIDE` is something we filter out)
> 
> ```
> {
>   claim_id: None, 
>   end_product_claim_code: None, 
>   end_product_claim_name: FILTERED-CLIENTSIDE, 
>   inflight_document_id: None, 
>   messages: 
>   [
>     {
>     key: form526.submit.establishClaim.serviceError, 
>     severity: FATAL, 
>     text: Error calling external service to establish the claim during Submit
>     }
>   ]
> }
> ```

Ah that's interesting. That doesn't agree with [their docs](https://www.ebenefits.va.gov/wss-form526-services-web-v2/swagger-ui/index.html?url=https://www.ebenefits.va.gov/wss-form526-services-web-v2/rest/swagger.yaml#/form526/submit), although 200 requests can have those fields (well, I suppose it's hard to tease out from swagger whether extra fields are explicitly prohibited)

**Comment by edmangimelli** [comment]
I think we're OK, as far as handling these new types of errors goes (handling errors with keys like "form526.disabilities[0].specialIssues[0].IsNotValid").
They will end up mapped to [evss.unmapped_service_exception](https://github.com/department-of-veterans-affairs/vets-api/blob/aa69b9246083cbf593b8089e712390f177a403d0/config/locales/exceptions.en.yml#L1974), which should be fine for our error handling (they'll be a non-retryable error, which makes sense) and our front-end error messaging.

@annaswims let me know if this doesn't sound right / you have concerns.
