### ISSUE TITLE
Research Adding Debt History to Debts Index Response

### ISSUE THREAD

**Issue by voidspooks** [department-of-veterans-affairs/va.gov-team#19150]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
When a debt is resolved (paid off or closed), it won't show up in the Debt-Letter UI. Is there a data source to pull historical debts for a user. Can we build out a UI for users to see all historical debts not just active debts.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rileyorr** [comment]
Discussed in backlog grooming that our next step is to reach out to Jill + Pavan for more info

**Comment by denisecoveyduc** [comment]
#47391 will move this work forward.
