### ISSUE TITLE
 [DISCOVERY] investigate localizing authenticated content with PII

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#19151]
**Spike ticket to explore approach(es) to localizing authenticated content with P11.**

**What issues do we need to solve for when it comes to translating content with PII (example Volunteer Research form).**

**  [  ]   **  Document considerations we need to account for

** [ ] ** How do we solve for associated issues (long term v short term?)

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - can you add points for this and close out when completed by tomorrow?

**Comment by youngfreezyVA** [comment]
having an api key with the associated cloud providers (Google, AWS, etc) translation API should suffice:
https://stackoverflow.com/a/5388330

In terms of a short term solution, PII would be dynamic in nature (the name or info, depends on the person), so using a static json file (which we are currently doing in spanish FAQ page) won't be technically feasible. 

If we were to use React as a short term solution, we could encrypt the information before and after translation:
https://stackoverflow.com/a/50449488
