### ISSUE TITLE
GIDS: DB Migration Cleanup

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19166]
As a developer, I need to remove redundant migration code, so that the codebase is cleaner and easier to maintain.

## Assumptions:
1. N/A

## Acceptance Criteria
1. All migrations in db/migrate created prior to 2021-01-26 are removed.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/784

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Closing this out
