### ISSUE TITLE
[Design] MyVA: Copy updates

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19165]
## Background
This ticket is for the design/copy updates that come out of the copy review of the tickets in this epic: [MyVA 2.0 copy #18991](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18991)

## Tasks
- [x] Make list all copy updates
- [x] Get these copy updates for all states to FE

**Comment by callen2563** [comment]
@Samara-Strauss @mshea0606 I have updated all of the copy tickets in GH and updated the screens in Invision as well. This is good to close.

**Comment by Samara-Strauss** [comment]
Where was copy documented for frontend?
