### ISSUE TITLE
Display or Provide Link to Decision Letter

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#19167]
## User Story
As a veteran, I want Kevin to provide the best experience possible when viewing my decision letters.

## Expected Behavior
Take another look at the design (and accessibility) for the #13405 ticket.

## Acceptance Criteria
- [x] Review the past documentation on this and determine how we would proceed from a design perspective

**Comment by kevinstachura** [comment]
This ticket references #[13405](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13405) which displays some decision data. Before implementing something like the Invision mockup shows, we would need to do some technical discovery to determine if something like that is possible (i.e. where to grab that data from and show it on the UI).


We could probably implement another version of this that is more scaled down, so the user just has a link to the [letters app](https://www.va.gov/records/download-va-letters/) from their closed claim detail screen on the CST. This is much more feasible in the short term and I think we can get it done. We just need a ticket for design and research around this.
