### ISSUE TITLE
Function of Cancel Button and Error Validation on Withdrawal from Legacy Appeals 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1916]
## User Story or Problem Statement
As a designer, I need to confirm the application process navigation button pattern so I can ensure a consistent experience for Veterans.

## Definition of Done
- [x] Confirm the application process navigation
- [x] If pattern is different from original Higher-Level review designs, post an updated in the Comments section of this ticket.
- [x] _ *This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
<img width="933" alt="Screen Shot 2019-09-19 at 11 51 07 AM" src="https://user-images.githubusercontent.com/54544300/65260106-d6e81780-dad3-11e9-8118-96f01f6bc8b6.png">

**Comment by smoonpeyes** [comment]
## Recommendations
- We do not typically use the disabled style for progress buttons in the application forms.
- Instead, use a [field-level validation on the checkbox](https://design.va.gov/patterns/form-feedback) if the Continue button is selected without first checking the box. We can decide on the specific copy during the content review.
- Replace the Cancel button with the Back button. The Back button returns the user the previous page.

## Revised mockup
https://vsateams.invisionapp.com/share/W5U21BDFTQK#/385333423_02-Withdraw-From-Legacy-System

**Comment by Mottie** [comment]
Should I make a ticket about what text to show in the error message?
