### ISSUE TITLE
[Design] HLR (Step 1) Review Contact Information Pattern

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1917]
## Goal
Review step 1 of the proposed Higher-Level Review application an ensure that the Contact Information section aligns with patterns used on VA.gov.

## Definition of Done
- [x] Review Contact Information pattern and compare to other patterns on VA.gov
- [x] If needed, update designs with any changes
- [x] Communicate design changes with the team
- [x] Request content review from VSP (Yana create a ticket and assign Peggy Gannon)

This relates to epic ticket #1053. Check the boxes above when this has been completed and comment "done"

## Screen Shots

<details>
<summary>Step 1a</summary>

<img width="325" alt="HLR-1of6-Confirm_Veteran_Details" src="https://user-images.githubusercontent.com/136959/66575996-8e54d480-eb3c-11e9-919f-6deb9cde1dca.png">
</details>

<details>
<summary>Step 1b</summary>

<img width="325" alt="HLR-1of6-Confirm_Veteran_Details" src="https://user-images.githubusercontent.com/136959/66777168-da31b180-ee8d-11e9-963f-45b875dd85c4.png">
</details>

**Comment by rileyorr** [comment]
@YanaRoy & @Mottie I reviewed the original mockup and compared it to other patterns on VA.gov. A Veteran's contact information is typically displayed separately from their details, so I created new screens to reflect that pattern. Additionally, different components needed to be used for the contact information section to align with current patterns in the design library. If everything looks good, please create a ticket for Peggy to review content. Otherwise, I look forward to your feedback! 

**Screen 01: Veteran Details**
https://vsateams.invisionapp.com/share/3QU4YCL2DA5

**Screen 02: Contact information (default)**
https://vsateams.invisionapp.com/share/V7U4YFTT8DN

**Screen 03: Contact information (expanded)**
https://vsateams.invisionapp.com/share/VTU4YCG6RSN

**Comment by Mottie** [comment]
Thanks @rileyorr!

So will the personal info block be separate from the contact information? Meaning will they be moved into two separate steps?

Otherwise, the new design looks good to me, and answers a few questions I had planned to bring up with the design team.

**Comment by Mottie** [comment]
Actually, does the collapsed mailing address need to be inside of an [address block component](https://design.va.gov/components/address-block)? Having the blue bar on the left looks off when comparing it to the phone & email block.

**Comment by rileyorr** [comment]
**So will the personal info block be separate from the contact information? Meaning will they be moved into two separate steps?**
So they're technically part of the same step, but once the Veteran selects "Continue" they would be presented with the new screen showing their contact information. We want to break up the amount of information presented to reduce cognitive overload. 

**Actually, does the collapsed mailing address need to be inside of an address block component? Having the blue bar on the left looks off when comparing it to the phone & email blocks.**
I was comparing my address component design to the way it's currently presented in "Apply for disability compensation" VA Form 21-526EZ. I've attached a screencap from that form below.
<img width="582" alt="Screen Shot 2019-09-27 at 3 17 58 PM" src="https://user-images.githubusercontent.com/46329147/65796217-0b924980-e13a-11e9-8235-bd2a40132570.png">


**And, what will the checked "My address will be changing soon" checkbox result look like. In form 526, it opens a forwarding address block. Should that be incorporated inside the mailing address component, or open an entirely new forwarding address block?**
I think for consistency with the current VA Form 21-526EZ, we would want it to open an entirely new forwarding address block. That's what the current pattern is right now.

**Comment by rileyorr** [comment]
@YanaRoy @peggygannon What steps do I need to take to receive a content review for this mockup?

**Comment by Mottie** [comment]
This is what the mailing address card looks like without the left border & padding. I feel like it needs to be bolder?

![](https://user-images.githubusercontent.com/136959/66241382-858b7b00-e6c4-11e9-947e-faf65b033e45.png)

**Comment by rileyorr** [comment]
@Mottie I double-checked with Jen this morning and she said for accessibility purposes having the text styled this way is fine. She mentioned she will likely do some testing for how it functions with screen readers and get back to me with potential changes. Also, when we test the design with Veterans we can see if they have trouble using the component with this new styling.

**Comment by rileyorr** [comment]
@meganhkelley Tagging you per Yana's instructions to get a content review for this ticket.

**Comment by meganhkelley** [comment]
Hey @rileyorr thanks! What is your timeline on this/when do you need the content review completed by?

**Comment by peggygannon** [comment]
@rileyorr does the screenshot above different from the one that appears in the HLR mockup in this issue?   https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2011

If not, then you can apply the content edits I provided in the mockup for this screen. So the into paragraph should read: 

This is the contact information we have on file for you. We'll send any important information about your Higher-Level Review to this address. Any updates you make here to your contact information will  only apply to this application. 

cc @meganhkelley

**Comment by Mottie** [comment]
@peggygannon The image in the first post was from the original Mural design. We have since switched to using inVision. I have updated the screenshot and the missing "Higher-Level Review" reference has since replaced the "disability claim" reference.

**Comment by peggygannon** [comment]
Hi, everyone. I think this issue can be closed, as I have provided my content review for this screen in the HLR mockup, being tracked here: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2011
