### ISSUE TITLE
[FE] Investigate EVSS Claims endpoint speed

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19171]
## Background
We need to investigate how long it actually takes claims data to come back

## Tasks
- [x] Check if this is available on the BE
- [x] Check how we could log this in google analytics

**Comment by erikphansen** [comment]
Anna helped me determine that it averages 2-8 seconds prod to get the claims data from EVSS. Sometimes it takes a lot longer. Given that, it does not seem prudent to block showing the entire My VA Dashboard until we get this data.

My current plan is to have Claims data loaded after most of the My VA Dashboard data has loaded. So, the UX for a Vet who needs to fetch Claims data will be:

1. See main loading spinner as most Dashboard data loads
2. Most of the Dashboard will load, but a spinner will be shown under the Claims and Appeals heading
3. When that call resolves after 5-10s (possibly much longer in some cases) the will see their Claims and Appeals data

**Comment by mshea0606** [comment]
Thanks! @erikphansen
