### ISSUE TITLE
0994 Form Intermittently Inaccessible in Staging and Dev environments

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#19172]
When attempting to access the [0994 Form](https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction), either an error is displayed or the page does not fully load. This occurs using any browser but is most common when using Internet Explorer.

## Steps to reproduce
1. Access the 0994 form on [Staging](https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction) or [Dev](https://dev.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction)

## Expected Result
0994 intro page loads successfully
![Screen Shot 2021-01-27 at 11.32.30 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/08e5995f-5da0-4456-a3e8-ee0fd1a176d6)

## Actual result
The user sees one of the following:
![Screen Shot 2021-01-25 at 1.05.06 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c0b83986-e436-4ea7-8313-a4e5ff727cc0)

---

![Screen Shot 2021-01-25 at 2.13.51 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/590138e1-3a96-4e51-893a-f27dfe3341f5)

**Comment by zurbergram** [comment]
This appears to be an issue with cookies

Clearing cookies should resolve issue

issue with cookies is being looked into see https://dsva.slack.com/archives/CBU0KDSB1/p1611937477001300
