### ISSUE TITLE
Add mock error states to test accounts

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19174]
## Context for this task
This task is a stop-gap in order to demo the UI for various error states using mock data. There is a separate ticket to revert this ticket, which the FE team will implement post-demo. (#19175)

## Acceptance Criteria:
1. Display the following mock error state on the Claims & Appeals page: 
     - Error state: **Claims unavailable with Appeals** (#17471)
     - User account that should display this error: vets.gov.user+1401@gmail.com
2. Display the following mock error state on the Claims & Appeals page:
     - Error state: **Appeals unavailable, no Claims** (#18245)
     - User account that should display this error: vets.gov.user+1402@gmail.com
3. Display the following mock error state on the Claims & Appeals page:
     - Error state: **Claims & Appeals unavailable** (#19079)
     - User account that should display this error: vets.gov.user+1414@gmail.com

**Comment by digitalken** [comment]
PASS - 1/29/2021 - Seeing all mock states on test accounts as indicated.
