### ISSUE TITLE
Update: nav bar only appears that the top of the stack

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19189]
## Acceptance Criteria
1. Update the app navigation so the bottom nav bar only appears at the top of each stack (Home, Claims & Appeals landing, Appointments landing, Profile landing)
2. Within each stack, users will use the Back/Cancel buttons to get back to the top of each stack
     - Ex: On the Select a File page, the bottom nav bar should not appear. The user will have to use the Cancel/Back buttons until they reach the top of the Claims & Appeals stack. Once they reach the Claims & Appeals landing page, the bottom nav bar should display. 

## Reference diagram
![Screen Shot 2021-01-26 at 10.44.03 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/046b7761-bce3-4f24-8e28-15a025dfaa17)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/8/2021 - Ran around everything and nav bar is gone when it should be.  iOS and Android.
