### ISSUE TITLE
[Design] Scale display of large number of disabilities (step 2 of 6)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1918]
## User Story or Problem Statement
As a designer, I need to identify a way to display multiple number of disabilities so the Veteran can locate the needed disabilities without confusion.

## Goal
_Create a user-friendly view of a large number of disabilities_

## Acceptance Criteria
- _As a system user, I want to avoid being confused by a large number of items in a single view._

## Definition of Done
- [ ] Identify current issue of large number of disabilities displayed
- [ ] Identify design of proposed solution for displaying large number of disabilities
- [ ] Request content review from VSP (Yana create a ticket and assign Peggy Gannon)
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots

**Comment by YanaRoy** [comment]
Not MVP priority per designers

**Comment by luke-gcio** [comment]
Closing, not an MVP priority (per old comment) and we should use UAT and usability to determine if version 2.0 would have updates to this.
