### ISSUE TITLE
Offboarding of Nicole Houston

### ISSUE THREAD

**Issue by sophiatareen** [department-of-veterans-affairs/va.gov-team#19191]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Nicole Houston
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Lighthouse API team, Software Engineer, Inactive as of 1/15/2021
- Please provide any type of access they may have and their GitHub username. 
  > Username: nwalker-va
  > Accounts to be removed: 
  >> Deactivate dsva-vetsgov IAM account
  >> Deactivate dsvagovcloud IAM account
  >> Deactivate dsva IAM account
  >> Deactivate dsvasupport IAM account
  >> Remove user from VSP Google Analytics
  >> Remove access to DSVA SOCKS Proxy/Jumpboxes (Open PR to remove SSH public key from authorized_keys and email address from global/config.yml)
  >> **including all of the items in the AC. This person has left her organization (Oddball), so she should completely removed from all accounts.**
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by jbritt1** [comment]
I believe this is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/18308

**Comment by sophiatareen** [comment]
Thank you! 

@jsev-io Hello! I am an Associate PM on the Lighthouse program. I see that you already created a ticket for Nicole earlier in January. I have been tracking down the steps to offboard team members - do you typically create requests for all team members? Feel free to slack me in Lighthouse workspace to continue the convo!
