### ISSUE TITLE
Tutorial for integrating a brand new external service into Vets-API

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#192]
## User Story

As a VFS developer, I want a tutorial on integrating a new external service into Vets-API the "api.va.gov" way, so that I can leverage and existings Vets-API standards, common patterns, and best practices.

**Comment by jholton** [comment]
Would a brand new service live inside a Rails Engine, or in the global code base (i.e. `lib/`)?

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/tutorials/endpoint-punch-list-presentation.md
