### ISSUE TITLE
Audit intro pages for online forms

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19217]
## Issue Description

We need to do an audit of all our online forms to see what we list in the H1 and what we put in the subhead underneath (where it says "Equal to Form 123456").

We want to make sure we are consistent. Questions that have come up: If the form number is in the H1 now, what should we do for the subhead? Only the name of the form? What if the name of the form is also part of the H1? Before we can answer these we need to see what we are currently doing.

Updated spreadsheet:

[https://app.zenhub.com/files/133843125/a83c6caf-3fd4-4f77-b873-69e9f5c2f5d5/download](https://app.zenhub.com/files/133843125/a83c6caf-3fd4-4f77-b873-69e9f5c2f5d5/download)
## Tasks
- [x] Account for all the H1s and subheads immediately under the H1

## Acceptance Criteria
- [x] Spreadsheet completed

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the updated spreadsheet. I only touched the columns A, B, D, and E. I wasn't sure what the Wizard page was vs. the Form Introduction page. Also, I didn't account for forms that you need to log into eBenefits to complete since those wouldn't have a head and subhead. Let me know if that's right. 

Updated spreadsheet is above.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you upload this audit to the repo (our internal one)?

**Comment by RLHecht** [comment]
This has been added to our sitewide content team folders: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content

It's listed as H1s for form wizard pages.xls

Closing out this ticket.
