### ISSUE TITLE
[Design] Prevent selection of disability claim that already has a HLR in progress

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1921]
## User Story or Problem Statement
As a claimant, I need to select only applicable disability claim(s) for which I can file a HLR so I can do not duplicate efforts.

## Goal
_Identify disability claims that can have a HLR filed against them_

## Acceptance Criteria
- _The system allows user to select only the applicable disability claims for HLR_

## Definition of Done
- [ ] _Identify design for selection of disability claim applicable for HLR_
- [ ] _ *This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
<img width="310" alt="HLR-2of6-Select_Contested_Issues" src="https://user-images.githubusercontent.com/54544300/65260889-1e22d800-dad5-11e9-87ba-b832ed5351c2.png">

**Comment by kevinstachura** [comment]
It is believed that the API returns data with which we can determine the eligibility of contesting via HLR. Data here:

```{"claim": {
   "appealPossible": "No",
   "attentionNeeded": "No",
   "baseEndProductCode": "336",
   "benefitClaimTypeCode": "336BDD",
   "claimConsolidatable": false,
   "claimPhaseDates":    {
      "currentPhaseBack": false,
      "everPhaseBack": false,
      "latestPhaseType": "Under Review",
      "phase1CompleteDate": "02/22/2019",
      "phaseChangeDate": "02/22/2019",
      "phaseMaxEstDate": "05/09/2019",
      "phaseMinEstDate": "03/25/2019",
      "phaseTypeChangeInd": "12"
   },
   "claimTrackedItems": {},
   "consolidatedTrackedItemsList": [],
   "contentionList":    [
      "Hepatitis (related to: Hepatitis C) (New)",
      " sinusitis (Secondary)"
   ],
   "date": "06/06/2019",
   "dbqList": [],
   "decisionNotificationSent": "No",
   "developmentLetterSent": "No",
   "endProductCode": "336",
   "id": "600150232",
   "jurisdiction": "National Work Queue",
   "mailingAddress":    {
      "addressLine1": "National Work Queue",
      "addressLine2": "810 Vermont Avenue NW",
      "addressLine3": "",
      "city": "Washington",
      "state": "DC",
      "zip": "20420"
   },
   "maxEstClaimDate": "08/04/2019",
   "minEstClaimDate": "05/06/2019",
   "newEvidenceReceived": false,
   "pastEstClaimDate": false,
   "pastEvidenceDueDate": false,
   "pastPhaseEstDate": false,
   "poa": "DISABLED AMERICAN VETERANS",
   "programType": "CPL",
   "status": "PEND",
   "statusChanged": false,
   "statusType": "Compensation",
   "submitterApplicationCode": "VBMS",
   "submitterRoleCode": "VBA",
   "tempJurisdiction": "",
   "vbaDocumentList": [],
   "waiver5103Submitted": false,
   "wwd": [],
   "wwr": [],
   "wwsnfy": []
}}
```

Given this is the case and we can choose to not show issues that are ineligible for an HLR, it's therefore unnecessary to design a solution for this - the system itself should be able to take care of it.
