### ISSUE TITLE
Back/Cancel/Done buttons are cut off on some screens

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19218]
## What Happened?
On some screens in the app, the Back/Cancel/Done buttons in the header are cut off at the top, including:
     - Find a VA Location (web view)
     - IAM page during login

(*NOTE: It looks like the 'B' or 'D' on the 'Back' or 'Done' is slightly getting the top shaved in every web view. -Ken Harrison)

## Specs:
- Device: Google Pixel 3X
- (NOTE* I found this in all of my Android devices but not iOS. Samsungs, Moto, Pixel. -Ken Harrison)

## Steps to Reproduce
1. Navigate to the IAM page during the auth flow. Observe the Back button. Notice how the "B" is slightly cut off at the top. 
2. Navigate tot he Find a VA Location page. Observe the Done button. Notice how the "D" is slightly cut off at the top. 

## Desired Behavior
Back/Cancel/Done buttons should not be cut off at the top. 

## Acceptance Criteria
See desired behavior

## Bug Severity
- 4 - Low

## Linked Story
N/A

## Screen Shot (s)
![Screenshot_20210128-113343.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/0ce6bf43-75b0-4745-b56e-a84db5ef8003)
![Screenshot_20210128-113409.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d73646d8-b42f-4cc8-ab40-c744c0fff7a7)

**Comment by digitalken** [comment]
PASS 2/16/2021 - Looks to be fixed.  Closing.
