### ISSUE TITLE
Remove the Cypress exception for the health care application

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#19221]
See: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13999

The Cypress axeChecks were adjusted to be more strict (#13647); the health care application was granted an exception to the rule. Now that the rules have been cleaned up, we'd like to remove the exception. 

A/C:

 - [x] The temporary exception for issue 13647 is removed
 - [x] The hca app passes all Cypress axe checks

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15823)
