### ISSUE TITLE
Search "We think you meant" Frontend implementation

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#19225]
## Description
Search & Discovery Team have defined Spelling Improvement as a next priority and have decided to add a “No results for...” message to notify users when they are presented with results for a corrected term.  This task will involve front end work to make users aware that no results were found for a misspelled query and instead results are shared for a term that is closely associated and perceived to be the one that they are looking for. 

Examples of terms that will showcase this experience:

- benefets
- prscriptions
- CHAMVA

Examples of terms that do not showcase this experience (these terms show results for a misspelled term because the misspelling can be found in the content)

- goverment
- sexual harrassment
- perscriptions

## Search.gov Flag Description
- This implementation will only happen when a flag is raised by search .gov due to a spelling error. 
- This flag will only be raised when the misspelled term does not appear within the content itself. 

## Design
![Screen Shot 2021-05-21 at 9.28.54 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/db73bbaf-9aa7-4228-a8fc-be03eef793ad)

## Definition of Done
- [x]  "No results for..." prompt is visible to VA.gov visitors who search for a misspelled query

**Comment by denisecoveyduc** [comment]
@srsuddath to update the top comment with new implementation details

**Comment by denisecoveyduc** [comment]
@mgleo can you confirm that I have updated the comment above with the most recent design? Any additional specs for @srsuddath

**Comment by mgleo** [comment]
[Invision link with "No results for..."](https://vsateams.invisionapp.com/console/UI-Search-Consistency---desktop-cknr2uisl2tl101ymmt48cx3z/ckoycyvys00qg01154omqe7ap/play)

**Comment by denisecoveyduc** [comment]
Bumped by #25224. Shifting to sprint 49

**Comment by srsuddath** [comment]
This ticket is awaiting validation in staging review before it can be closed

**Comment by srsuddath** [comment]
feature is live on the review instance
