### ISSUE TITLE
Continue synthesizing research results from 526 PTSD form

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#19222]
## User Story

_As a veteran with PTSD, I need to be able to properly submit form 526 _

## Task Description
- Complete Affinity Session to find the specific recommendations. Finish a research report (Topline summary and a slide deck with the full findings/recommendations, and document all in Github

## Acceptance Criteria

- Outbrief to the team (30 minute session)
- Final research report to be completed

**Comment by chrvalla** [comment]
Research report will be completed by February 11, 2021.

**Comment by chrvalla** [comment]
Affinity session is complete, synthesizing is complete.

**Comment by vhenry07** [comment]
Closing complete.
