### ISSUE TITLE
Best bet leading to a bad URL

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19226]
## Issue Description
When searching for "526" on VA.gov, the second result in the best bets, leads to a non-working page. I'm not sure if there is a replacement page or if it should be removed. When searching "526" on /find-forms, the only one that comes up is 526EZ, which is the first result in the best bets.

URL it's showing: https://www.va.gov/disability-benefits/apply/form-526-disability-claim/introduction/
![Screen Shot 2021-01-28 at 3.51.12 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/8de6d734-2f5e-420e-8b67-bda78c068e91)
## Tasks
- [ ] Remove or replace second result in best bets

## Acceptance Criteria
- [ ] Broken URL no longer showing in search

**Comment by RLHecht** [comment]
@johnhashva I just found this broken link in a best bet when doing some other work so I created this ticket for you. Let me know if you have any questions.

**Comment by johnhashva** [comment]
I've fixed this by deleting that old BB for a more up to date alternative, seen here.  @RLHecht please validate and close.

![Uploading Screenshot 2021-01-28 160529.png…]()

**Comment by RLHecht** [comment]
You're fast! Looks good to me. Closing ticket! FYSA @brianalloyd
