### ISSUE TITLE
Search Spelling Suggestions Backend Implementation

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#19224]
## Description

Search & Discovery Team have defined Spelling Improvement as a next priority. This task will involve backend work to surface the Search.gov provided spelling suggestion to the front end for consumption.

## Tasks
- [ ] Update Backend to allow forward spelling suggestion response from search.gov

## Definition of Done
- [ ] Search response from search.gov contains a spelling suggestion as part of the api reponse.

**Comment by denisecoveyduc** [comment]
BE no longer required with new implementation
