### ISSUE TITLE
Error | File could not be uploaded

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19236]
## User story
As a user, I want to know when my photos/files could not be uploaded to VA due to an upstream error.

## Acceptance Criteria
1. If the upload endpoint returns a service error, display an error message that informs the user their file couldn't be uploaded
2. This error message would appear after a user selects "Confirm upload" from the confirmation screen
3. Style & UX/UI matches design
     - Copy is hard-coded
     - Error message includes a Large Button: "View all file requests"
          - Selecting this button routes the user to the File Request Overview page
4. If a file upload was unsuccessful, the following UI elements should remain unchanged and **not** reflect a successful upload: 
     - File Request Overview page: Section header (e.g. "You have 2 file requests from VA")
     - File Request Overview page: The file request should still display the 2 large buttons to Select a file/Take photos
     - Claim Detail page: Alert above the step table 
     - Claim Detail page: Step 3 --> File request label above the large button
    

## Related tickets
Successful upload: #18612

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447964913

## Accessibility Implementation Guidelines 
- Back button in top left (custom a11y)
     - accessibilityLabel = "back"
     - accessibilityHint= “Navigates to the file request page”
     - accessibilityRole = “button”
- Mark "File upload" as Header 1
- Mark "Your file could not be uploaded" as Header 2

**View all file requests button**
- Title= "View all file requests"
- accessibilityHint= “View all file requests and return to the file request page” 
- accessibilityRole= “button”

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by ashley-matthews** [comment]
Not launch critical

**Comment by digitalken** [comment]
PASS 6/3/2021 - Looks good on iOS and Android.  Closing.
