### ISSUE TITLE
Research: Evaluate FE build failures since Nov 1

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#19234]
AC:
- [ ] Count number of Jenkins build failures on `vets-website` `master` branch from 2020-11-01 to 2021-02-01
- [ ] Categorize build failures by cause
- [ ] Create followup ticket to generate ongoing report
- [ ] Create followup tickets to research each category

**Comment by laineymajor** [comment]
@mchelen-gov we are doing backlog refinement. Is this something you want now that Jenkins is gone?

**Comment by mchelen-gov** [comment]
Oh definitely not, this is super outdated 😅
