### ISSUE TITLE
Claims Integration | File upload

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19238]
## User Story / Task 
This is a backend task to integrate with the file upload endpoint

## Acceptance Criteria

1. Service integration with the claims API to call the following endpoint:
     - Upload
2. Call this endpoint after a user confirms the upload for 1 file

## Note for QA
Once this story is complete, retest the following file upload tickets:

- #19098
- #18735

**Comment by bessgreen** [comment]
Blocked: can't start this ticket until Claims & Appeals integration is merged

**Comment by bessgreen** [comment]
Unable to test this until we receive test accounts with this feature:
     - Active Claim in Step 3 
     - Tracked items w/ open file requests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/21/2021 - Looks good on Android and iOS.  Closing.
