### ISSUE TITLE
Access for [individual]

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#19239]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Veronica Henry
- Please Provide your email.
   > vhenry@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Claims & Appeals, Product Manager, GovernmentCIO

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4L2+WATRUFotccrwKlGYQeiXKE6kCRPiElU7cH27k3r7jn8czJCJBptM+lBDnxHCpgeI6JHofAQpaW7Z/RpE3u55Tecr0+D8sNURLSjNmM4/g2fqBxbbMNttpzgwCOp1BLh39JmqMmXzr+cg8pbk0SOfLlKHbjLhIXnMjija48rWNbdyfmna00+kfVGGaindXYC3zUiMAbTwcjWznkntc4GGRgPxztxqbhj5hxl7DFgkbzINlKuvS/NdXtbPL7Ngu66VuvzGmsQdekGn2E5qEpPEwm62ov8E5bTUe1exPVmiW0L0P2DEvdsH/2TKhOmDhK4jQMmJ5S8z3ZU3oZlz37g+rTF2f1lInpK9zDUAXGByPIZIq4f04firNfqjzlcgla6pCDiOJE4hUeiPpMKAh2YtR9HWNWOwQEe2BwJy+0vzJaVA0Mudj5HXXQdrkXGaeGA/thRArHTYY+tJ0vk3egS7p77Sn24pdemdzX79VTHn0wW9V6LFODBBUp3aVBz0= vhenry@VHenrys-MBP.attlocal.net

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
