### ISSUE TITLE
HLR: Confirm Veteran Details page (step 1)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1924]
## User Story or Problem Statement
As a claimant, I need to review, update and confirm my contact information so the VA has my most up to date and accurate info.

## Goal
_Provide access to view and edit contact information_

## Acceptance Criteria
- _The user is able to confirm contact information already available in system_
- _The user is able to edit contact information already available in system_

## Definition of Done
- [ ] _Build out of Confirm Veteran Details page_
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shot

<details>
<summary>Step 1a</summary>

<img width="325" alt="HLR-1of6-Confirm_Veteran_Details" src="https://user-images.githubusercontent.com/136959/66575996-8e54d480-eb3c-11e9-919f-6deb9cde1dca.png">
</details>

<details>
<summary>Step 1b</summary>

<img width="325" alt="HLR-1of6-Confirm_Veteran_Details" src="https://user-images.githubusercontent.com/136959/66777168-da31b180-ee8d-11e9-963f-45b875dd85c4.png">
</details>

**Comment by tlei123** [comment]
Hi, @Mottie @YanaRoy , is #1917 the related UX tic for this?  I see that tic's not due this Sprint, and I'm looking for info on error messages.

Please let me know.  Thx much!

**Comment by Mottie** [comment]
Hi @tlei123! 
- I've been working with user 226
- Yes #1917 is the design ticket for this step
- I haven't seen any designs with error messages for step 1, but I've been following the recommendations from #1711

**Comment by tlei123** [comment]
Thx, @Mottie !  I just asked Silvio about [actual test-data on Staging](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1359#issuecomment-540811552).

Testing this new Step 1 page on Staging is contingent upon actual contact test-data being in-place behind the actual API endpoint(s), since Staging does not use mocked-data.

I'll add any updates here.

cc @YanaRoy

**Comment by tlei123** [comment]
@rileyorr & @Mottie, I've started a QA Manual Testing Matrix for Step 1 Veteran Details page.

Please review it, and make any edits and/or add any comments as needed there*: https://1drv.ms/x/s!AtFPwFnvF2TMdHaJmfZJb2dXakQ

Thanks much!

*This is an MS OneDrive experiment I'm running to enable easier online viewing/editing of the Matrix.  Anyone with the above link can view/edit the spreadsheet, as well as start and participate in Comment threads (under the Review tab).  Hope you like it!
