### ISSUE TITLE
Alphabetize module generator file insertions

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#19242]
## Issue Description
When the module generator runs, it inserts entries for the newly generated module/engine into the simplecov_helper spec_helper and routes files. The current method of insertion doesn't alphabetize the entries and just inserts after the # Modules comment. It would be best to insert the new entry wrt alphabetization. 

A branch was started here:
https://github.com/department-of-veterans-affairs/vets-api/tree/18712-alphabetize-generator-entries

---
## Tasks
- [x] Alphabetize the file entries

**Comment by alexpappasoddball** [comment]
Not an explicit part of the toolkit so no need for a changelog update.  Looks good to me!
