### ISSUE TITLE
[Research] Create an automated downtime message when dependencies (MPI, Salesforce) are down

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#19245]
**Description**
The online 10-10CG depends on MPI and Salesforce. We regularly see MPI timeouts for hours at a time, making submissions fail. We'd like to prevent people from submitting or starting the form when we already know it’s not going to go through using a downtime message that automatically shows up when we know a dependency is having performance issues.

**Comment by kevinmirc** [comment]
Relates to: https://github.com/department-of-veterans-affairs/va.gov-team/pull/19107

**Comment by mlighdc** [comment]
@kevinmirc what is the status of this? It looks like some may have been pushed around early February but not sure of the follow-up.

**Comment by hdjustice** [comment]
Closing this ticket - has not been addressed in over a year.  If work is needed, a new ticket will be created under an initiative
