### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#19240]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

vhenry@governmentcio.com

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [ x] Google Analytics
- [ x] Domo
_Please list any additional requirements, if any._

## Date Required
_02/01/21._

## Product Team / External Team / VA Office
_Claims & Appeals

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bmcgrady-ep** [comment]
Hi @vhenry07 - You have been added to Google Analytics and DOMO. Let me know if you have any issues with your access.

**Comment by vhenry07** [comment]
I'm all set. Thank you.
Veronica Henry | PMP
Sr. Product Manager
| *mobile* 702-509-6192
| *e.* vhenry@governmentcio.com
