### ISSUE TITLE
Update number of days to complete disability related claims for December

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19246]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Sandy Tadeo on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Sandy for most recent number 
- [x] Input number into both Drupal pages
- [x] Review and publish

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
@lunascoop December's number is 156.4. Could you please update the 2 pages? Thanks!

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

How to file a VA disability claim: http://preview-prod.vfs.va.gov/preview?nodeId=905
The VA claim process after you file your claim: http://preview-prod.vfs.va.gov/preview?nodeId=870

**Comment by RLHecht** [comment]
Thanks, @lunascoop I published these. Moving to validate and will close once live.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
