### ISSUE TITLE
Enforce passing `lint:sass` when doing `git commit`

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#1925]
Because what's the point of having linting rules for our Sass if we don't enforce them?

About a week ago I cleaned up the warnings we get when running our `lint:sass` script (https://github.com/department-of-veterans-affairs/vets-website/pull/10700). Since then a few new (very easy to fix) warnings were introduced.

- I propose we enforce passing `lint:sass` via a git commit hook similar to how to enforce passing `lint:js`.
- I also propose we make Jenkins fail when `lint:sass` does not pass (cuz how else are we gonna make people update their git hooks?)

**Comment by erikphansen** [comment]
I'd be happy to do this work, FWIW

**Comment by meganhkelley** [comment]
@cvalarida @bkjohnson is this done? I know you just did some work on sass linting

**Comment by bkjohnson** [comment]
Yup:

https://github.com/department-of-veterans-affairs/vets-website/blob/4c05289331dfd528048e067c044357b5ab3973c5/package.json#L27

https://github.com/department-of-veterans-affairs/vets-website/blob/4c05289331dfd528048e067c044357b5ab3973c5/script/hooks/pre-commit#L3
