### ISSUE TITLE
Update number of days to complete disability related claims for September

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19259]
## Issue Description
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Sandy Tadeo on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

## Tasks
- [x] Email Sandy for most recent number 
- [x] Input number into both Drupal pages
- [x] Review and publish

## Acceptance Criteria
- [x] Most current number of days is on live site.

**Comment by RLHecht** [comment]
Tanekwa Bounes sent September's number: 142.8. @lunascoop can you please make this change on the 2 pages listed above? Thanks!

**Comment by lunascoop** [comment]
@RLHecht these pages are ready for review.

The VA claim process after you file your claim: http://preview-prod.vfs.va.gov/preview?nodeId=870
How to file a VA disability claim: http://preview-prod.vfs.va.gov/preview?nodeId=905

**Comment by RLHecht** [comment]
Thanks @lunascoop Just reviewed and published these pages. FYSA @bethpottsVADEPO

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
