### ISSUE TITLE
HLR: Select your contested issues page (step 2a & 2b)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1926]
## User Story or Problem Statement
As a claimant, I need to be able to view and select applicable disability claims so I can file for a Higher-Level Review.

## Goal
_Provide user ability to identify and select eligible disability claims.

## Acceptance Criteria
- _A system user can view all of their contested issues_
- _A system user can select all of their eligible contested issues_

## Definition of Done
- [ ] _Build out of Contested Issues page, and sub-steps_
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shot

<details>
<summary>Step 2a</summary>

<img width="652" alt="Screen Shot 2019-10-24 at 1 20 25 PM" src="https://user-images.githubusercontent.com/136959/67513840-4ae08700-f661-11e9-88ca-1146c872efc2.png">
</details>
<details>
<summary>Step 2b</summary>

<img width="620" alt="Screen Shot 2019-10-24 at 1 25 13 PM" src="https://user-images.githubusercontent.com/136959/67514106-c3dfde80-f661-11e9-9131-aee85a45124b.png">
</details>

**Comment by Mottie** [comment]
Step 2 originally had the user select their contested issue(s) & step 3 allowed them to add notes. In the new design these steps have been combined as sub-parts of step 2 to more closely match how form 526EZ was handling it. I will update the other issues to fix the step order and information. Top post has been updated.

**Comment by Mottie** [comment]
Split out step 2c - move the work to #1927
