### ISSUE TITLE
CT Redesign: Final Testing Prototype

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#19266]
Build out fully-functioning prototype for usability testing

**Comment by amyknox** [comment]
MOBILE
•	Separate prototypes for each task.
•	LANDING PAGE… Adjustment
o	Should location be visible on landing?
o	Update estimates / Refine schools & programs
•	Link to Indiana University profile profile page (View details _17) 

GENERAL
•	Updating the “Compare” button so the text is different than Compare Tray label? 
o	Tray label “Compare ^”
o	Button “Compare schools”
o	Heading “You’ve selected these schools to compare:” 
•	What’s the feasibility of adding more hotspot options so we don’t get stuck during tasks?
o	For instance: selecting Amherst / Bloomington in whichever order. 
Nice to have
•	Search – Show the number of search results on search results page
Post-test 
•	Desktop / Landing: Can we make it 3 stacked components? 
•	Search / Show search criteria (post-test solution)
•	Should we add an “Update estimate” heading to the content below the search elements

**Comment by amyknox** [comment]
From Jen: 

- Remove search results and Dayton input on slides 13-15 (desktop)
- Update search result counts on all wireframes
- Restore disclaimer on initial wireframe (discussion between Emma and Jen)
- Update all breadcrumbs

**Comment by amyknox** [comment]
@watersemma - one more: 
At the beginning of task 1, could we add the screen that has the location field activated but no type-ahead for "Day…" in that field?

Update default search to include "Near" and always display "Refine search" button below.

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/3577c12b-9598-4b68-a256-fe222e6f83b7)

**Comment by watersemma** [comment]
- Button “Compare schools” Update has been applied to desktop. See screens 'CT_Redesign_Desktop_23' - 'CT_Redesign_Desktop_26'

**Comment by JenLJ** [comment]
Wireframe transition links adjusted to match updates made to "CT_Redesign_Desktop_23" to "CT_Redesign_Desktop_26"

**Comment by watersemma** [comment]
Updates on mobile:

- breadcrumbs have been updated
