### ISSUE TITLE
STEM Automated Denial: Design Asset Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#19278]
Review existing claims status design assets 
Capture in easy-to-digest format 
Share with team

**Comment by amyknox** [comment]
Notes from Kevin Stachura , Claims Tool designer

> Claims Tool on staging (sometimes you'll get a loading spinner for awhile): https://staging.va.gov/track-claims/your-claims
> 
> Here's also a screenshot version of what it looks like for an appeal item in the CST: https://vsateams.invisionapp.com/share/FXY0COTKMRD#/424622570_CST_-_Claims_Listing
> 
> User 228 - 'Colder Polarbear' should have a healthy list of claims!
