### ISSUE TITLE
[Design] Display site info for failed community care requests?

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#19272]
Currently, when there's an error submitting a community care request, we'll show a message about the error and provide a link to the FL to call your facility. For regular VA requests, we show you the info for the facility where you were making a request, in addition to the error message.

Do we want to do the same thing for CC requests, and show the facility info for the parent site where their request was being directed?

**Comment by outerpress** [comment]
Great idea @jbalboni , it makes sense to keep those consistent and provide that helpful info for CC requests as well.

**Comment by outerpress** [comment]
@jbalboni could you drop in a screenshot of the error message as it appears in regular VA requests? I don't think I can easily pull that one up.

**Comment by jbalboni** [comment]
@outerpress Pasted below. You can see in the review data I chose Cheyenne, WY as my closest site, that's the facility info we could show.

![Screen Shot 2021-02-12 at 3 41 59 PM](https://user-images.githubusercontent.com/634932/107820485-dc897180-6d48-11eb-8d9e-806baa80db40.png)

**Comment by outerpress** [comment]
Thanks @jbalboni, just to make sure we're on the same page I mocked up a CC submission error with facility info as suggested. Let me know if you were thinking something different. This'd definitely be faster than using FL to dig up that info.

![VAOS-CC-error-submit](https://user-images.githubusercontent.com/2536801/107996277-e0113880-6f94-11eb-8989-7b59a9341783.png)

**Comment by outerpress** [comment]
Reworked this a bit:
- Tweaked the message - @peggygannon could you provide content recs?
- Removed directions link
- Added TTY number
- Linked facility name - this would link to facility's page if we have that data - otherwise, header would not be linked (just bold)

![VAOS-CC-error-submit.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/93d69c3e-3a82-46a0-972e-31fd79ff5295)

**Comment by peggygannon** [comment]
Hi, @outerpress ok, thank you. I will take a look.

**Comment by peggygannon** [comment]
Hi, @outerpress just a few tweaks to the CC message: 

**We couldn't schedule this appointment**
We're sorry. Something went wrong when we tried to submit your request. You can try again later, or call your VA medical center to help with your request. 
{name of VA medical center, etc}



Can we also use this slightly abbreviated message for regular VA requests?

**Comment by outerpress** [comment]
Thanks @peggygannon! Looks good to me

> Can we also use this slightly abbreviated message for regular VA requests?

[Is this the one?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/request-flow/review_config_error.png) If so, seems like it'd make sense to align those. The main difference is the "try again later" note, looks like.

cc @laurenernest

**Comment by laurenernest** [comment]
Dev ticket created #28256

@outerpress can you add a spec (just the alert part is fine) to cover the details around the facility info?

**Comment by outerpress** [comment]
Yep @laurenernest added specs to dev ticket, closing this one.
