### ISSUE TITLE
HLR: Add choose jurisdiction & notes page (step 2c)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1927]
## User Story or Problem Statement
As a claimant, I need to be able to view and select applicable disability claims so I can file for a Higher-Level Review. Then choose if I want to use the original jurisdiction to do the review (previously step 4) and add a note (previously step 3, now 2c).

## Goal
_Provide user ability to choose to use the same jurisdiction and add a note for each eligible issue for a HLR_

## Acceptance Criteria
- _A system user can choose if they want to use the same or different jurisdiction for each eligible issue_
- _A system user can add a note to each eligible issue_

## Definition of Done
- [ ] _Build out of choose jurisdiction & add Notes page_
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shot
<details>
<summary>Step 2c (one or more issues)</summary>

<img width="633" alt="Screen Shot 2019-10-24 at 1 21 18 PM" src="https://user-images.githubusercontent.com/136959/67513962-824f3380-f661-11e9-8f36-10219b2573f7.png">
</details>

**Comment by Mottie** [comment]
Merged with #1926.

**Comment by Mottie** [comment]
Reopening this issus. Changed step 3 to step 2c. I split this out from #1926 because even-though the steps were combined, the of amount of work did not change.
