### ISSUE TITLE
HLR: Request Original Jurisdiction page (step 4)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1928]
## User Story or Problem Statement
As a claimant, I need to identify and select the jurisdiction of my contested claim so I can the same office that issued my prior decision could conduct the review.

## Goal
_Allow user to view and selected the Original Jurisdiction where the decision for their issue was made_

## Acceptance Criteria
- _The system user can view jurisdictions_
- _The system user can select jurisdictions_

## Definition of Done
- [ ] _Build out of Request Original Jurisdiction page_
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
<img width="552" alt="HLR-4of6-Request_Original_Jurisdiction" src="https://user-images.githubusercontent.com/54544300/65262595-b1114180-dad8-11e9-8f82-c3b5e5155a64.png">

**Comment by Mottie** [comment]
Merged with #1926.
