### ISSUE TITLE
Arrows in ListItems don't automatically scale (or at all)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19299]
## What happened?
On iOS:
After increasing the device's font size, the arrows in ListItems and in the Home screen cards either do not scale, or they only scale after tapping into them & returning back to the ListItem.

After decreasing the font size in the device's settings, any arrows that _did_ scale are still large - they only return to the smaller size after clicking into the ListItem. 

## Specs:
- Device: iPhone 11

## Steps to Reproduce

1. Log in with a user that has active Appointments. 
2. On an iOS device, view the Home screen cards and ListItems, such as the Claims & Appeals list
3. Go to the device's settings and max out the font size
4. Re-open the app & view the Home screen cards. Notice how the arrows on the Home screen cards did not scale. 
5. View the Upcoming Appointments page. Notice how the arrows in each ListItem didn't scale. 
6. Tap into an Appointment to enter the detail page. Hit "Back" to return to the Upcoming Appointment page. Notice that the arrows in each ListItem are now scaled, as expected. 
7. In the device's settings, return the Font Size to a smaller size. 
8. Re-open the app on the Appointment detail page. Notice how the arrows in each ListItem are still large, while the rest of the app has scaled down accordingly. 

## Desired behavior
Arrow icons will scale automatically with the font size.

## Acceptance Criteria
See desired behavior.

## Bug Severity
- 4 - Low

## Linked to Story
N/A

## Screen recording / screen shots
**Link to screen recording** 
https://drive.google.com/file/d/1A9CTwIGKeUCr_eRrmcWr_3H9xutI462m/view?usp=sharing

**Android (arrow scales as expected):**
![Screen Shot 2021-01-29 at 2.31.52 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/bcef9923-72bc-4b99-b9e0-5a072c07b691)

**Comment by digitalken** [comment]
@bessgreen - I've noticed that I have to kill the app and restart in order for the arrows to resize correctly with iPhone.  (Or log out, then log back in... can't remember which offhand.)

**Comment by komaly15** [comment]
Note: once font size is updated in ios and you go back to the app, it takes a couple seconds for the icon size to to be updated

**Comment by digitalken** [comment]
PASS 2/17/2021 - Arrows take a fraction of a second to resize when going back to screen but do so without user having to log in again or kill the app.
