### ISSUE TITLE
UI update | Add padding around ListItem arrows

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19298]
## Acceptance Criteria

1. On the 3 Home screen cards (COVID-19 vaccines, C&A, Appointments), add 20px padding-right to create more space between text & the arrow-right icon
2. On all List Items in the app that contain the arrow-right icon, make the following global change:
     - Add 20px padding-right to create more space between text & the arrow-right icon

## Mockups / Reference points
![Screen Shot 2021-01-29 at 1.57.01 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/80628774-5dcb-4b37-89f3-0379ff1fc8f8)
![Screen Shot 2021-01-29 at 2.02.23 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/563ed2f1-a6f2-414d-9afa-abb1cacc7838)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - Padding has been added.  Closing.
