### ISSUE TITLE
HLR: Request an Informal Conference (step 3)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1929]
## User Story or Problem Statement
As a claimant, I need to provide the adjudicator with my available days and times for an informal conference so I can ensure I am available during those time frames to meet and discuss my HLR form.

## Goal
_Give the user an opportunity to provide availability for an informal conference_

## Acceptance Criteria
- _The system user can request an informal conference_
- _The system user can provide time and day preference_

## Definition of Done
- [ ] _Build out of Request an Informal Conference page_
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
<img width="407" alt="HLR-5of6-Request_Informal_Conference" src="https://user-images.githubusercontent.com/54544300/65263993-b15f0c00-dadb-11e9-8242-1fb5d8be9b2f.png">

**Comment by Mottie** [comment]
Changed to step 3/4 of the HLR form. The design has changed, so I will update the screenshot when that design is available.
