### ISSUE TITLE
UI update | Active states to Large Buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19295]
## Acceptance Criteria
Make the following global changes to large buttons in the app:

1. For primary action Large Buttons (i.e. buttons with a blue background), make the following updates to the active state:
     - Background color: change from **primary-blue** to **primary-darkest**
     - Text color should be the same as the default state
2. For secondary action Large Buttons (i.e. buttons with a white background / blue border), make the following updates to the active state:
     - Border color: change from **primary-blue** to **primary-darkest**
     - Text color should be the same as the default state

## Mockups / Reference points
![Screen Shot 2021-01-29 at 1.42.47 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d014992b-8fc2-46a9-89ae-c37e15bc2266)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - Updates to buttons have been made.  Closing.
