### ISSUE TITLE
UI update | Borders + active states to home screen cards

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19294]
## Acceptance Criteria
Make the following global styling changes to the cards on the home page:

1. Add a border to the Claims & Appeals and Appointments cards. Border specs:
     - 2px
     - solid border
     - **primary-blue** #0071bb
2. Update the active state for the Claims & Appeals and Appointments cards:
     - Text color should be the same as the default state
     - Border color: change from **primary-blue** to **primaryDarkest** #112e52 _(note: screenshot below says primary-darker, but primaryDarkest is correct)_
3. Update the active state for the COVID-19 card:
     - Text color should be the same as the default state
     - Background color: change to **primaryDarkest** #112e52

## Mockups / Reference points
**1.** 
![Screen Shot 2021-01-29 at 1.26.51 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/8bfb0b50-5499-4a60-8967-8b9040129c7a)
**2.**
![Screen Shot 2021-01-29 at 1.29.48 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/6e5491e6-ee9d-4b83-a616-e322f04e7519)
**3.** 
![Screen Shot 2021-01-29 at 1.29.43 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/191f0403-46a7-410d-a9af-bae7f7202dbc)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - Updates have been made.  Closing.
