### ISSUE TITLE
Documentation - Improve `vets-website` FE documentation 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#193]
Support ongoing VSP efforts by filling critical documentation gaps. Client documentation can be found here: 
- [Client Documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/internal-tools/)
- [documentation site package](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/documentation)

## Short term tasks 
- #196 Document Drupal CMS
  - This will probably be an epic 

## VSP Q1 + Q2 2020 OKRs 
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

**Comment by meganhkelley** [comment]
Adding `content-ia-team` label now that we have a dedicated technical writer to help with this, and tagging @kristinagore for awareness

**Comment by brandonrapp** [comment]
We are working on cleaning up our documentation as part of our active and maintenance development work so we do not need to prioritize a standalone super-epic for this.
