### ISSUE TITLE
Biometrics toggle is "On" after opting-out in the auth flow

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19307]
## What Happened?
After hitting "Skip" to opt out of Biometrics during the login flow, the Biometrics toggle on the Settings page is switched to "On".

## Specs:
- Device: iPhone 11
- Build: VA Mobile 1.0.17 (33) for iOS

## Steps to Reproduce
1. Before logging in, hit "Reset first time login" in the developer screen
2. Sign out
3. Go through the login flow. When the Biometrics Opt In page appears, hit "Skip"
4. When the app loads, navigate to the Settings page, and notice that the Biometrics toggle is set to "On"

## Desired Behavior
Opting out of biometrics should result in the biometrics toggle to be "Off".

## Acceptance Criteria
1. When selecting "Skip" from the Biometrics Opt In screen, the toggle on the settings page should be set to "Off"
2. When selecting "Use [FaceID]" from the Biometrics Opt In screen, the toggle on the settings page should be set to "On"

## Bug Severity
- 2 - High

## Linked Story
#18381 - See AC #3

## Video
https://images.zenhubusercontent.com/133843125/53e86e7e-764c-4bec-ba71-3c88b0355a3e/image_from_ios.mp4

**Comment by digitalken** [comment]
PASS 2/16/2021 - Both Android and iOS have toggle OFF when skipping for biometrics on first sign in. Closing.
