### ISSUE TITLE
Add tracking to display of new CC Provider Selection page

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19304]
## Description
As Product, I would like to be able to identify in analytics how many users see the new Community Care Provider Selection page so that I can track the impact.

In the MVP, users without a resident address in their profile will still be directed to the old form. The event will also help inform the counts for users who do not have profile information the page is optimized for.

## Tasks
Add appropriate event(s), coordinating with Analytics team as necessary for guidance

## Acceptance Criteria

- [ ] Event for GA fires that distinguishes if user sees new page or old page

**Comment by narin** [comment]
Hey @laurenernest would the following event names work? We have some existing cc events with the `community-care` prefix, so I'm not sure if it's necessary to get guidance from the analytics team:
* `vaos-communtiy-care-provider-selection-page`
* `vaos-community-care-legacy-provider-page`

**Comment by laurenernest** [comment]
@narin good call following the same cc pattern we already have. looks good to me!
