### ISSUE TITLE
Access for Ron Tafoya - VAMC-Upgrade-Team - GovernmentCIO

### ISSUE THREAD

**Issue by ronrtafoya** [department-of-veterans-affairs/va.gov-team#19305]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Ron Tafoya
- Please Provide your email.
   > rtafoya@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Please see closed issue ticket #18792, Taylor Skinner is expecting this new issue/ticket. Please re-set my public key for SOCKS access using the pasted text below and thank you. Please contact me with questions.

- Requesting SSH key authorization?
   > 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOVpHobXq/5oJVXcde0vHYob+bcIaz4NQAlxke3/HG5AHrwiucZT0LT2aeWFsKxJzyphfWoeqfxt7PCfi9Jm9zCocPCh0Rk5JWdpugb8C6Eizlr/ipmV/OcbE+JY9yPg+9JCTc5ePeLYBkugWjIrF7s9wJzXVTeEUcbCQRocyBKutpf5nOFZIWQhmZswi5q4K9BYdtpFLXNEvEc+zmbltanZTrQrhQxlw6i69EEVNrnPhlXaxMrLSXBpoVUFFis1L6ZYWHPzI2dr3am5JaJVWd2FCuWBLHlUtLwUiAx811l+PbGW7czF791QomodaPztJodKOwzQgQawDJM26LFY4MVljxuR96muYRPTGNjefdsCcrUTNsREgoj/h1FQD77eLYUmU2jMCc2ZVrTdsW3DNN/7jFX1CCdQqFqwwlbJ+uqi1VXRUW5bOAELBxRF60TqzdikAWXMG6H/Fry6hJUiElEGDAo1UWaStnQysV7nDk839AzFxA3As2CH29Tn3ehsE= rontafoya@Rons-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES / NO
  - What AWS services do you need access to and why? SOCKS access, see closed issue #18792

**Comment by jbritt1** [comment]
### For AWS Access

User: Ron Tafoya
COR: Mary O’Toole
Approval needed: @Jeff-Hayter

**Comment by mleclerc00** [comment]
jBritt1 jumped the gun here, no need for AWS approval per the previous ticket, just socks

https://github.com/department-of-veterans-affairs/va.gov-team/issues/18792

**Comment by mleclerc00** [comment]
@ronrtafoya, the change to your ssh key has been pushed.  Give it a test when you get an opportunity and let me know if you have any other issues.

Thanks!

**Comment by ronrtafoya** [comment]
Thank you all--I'm able to get into Jenkins and CMS production, and I can see the CMS staging login, but my credentials don't work there. I'll need to follow up elsewhere for that I think (if anyone has input let me know). So you guys got my SOCKS up (thank you).  I'm guessing you all can close this. Regards, RT

**Comment by jbritt1** [comment]
Anytime Ron, we are all happy to help.
