### ISSUE TITLE
General Analytics Request for VAOS

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19306]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- @laurenernest 

    
- What team/project is this work for?

    - VAOS - the most immediate need is related to the Community Care Provider Selection MVP, but would be used for upcoming initiatives as well
    
- What type of analytics support are you looking for?
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
August 1, 2020 to present

## Analytics to Track Down

- [ ] Total logged in users across all of VA.gov

## Which Product Questions are you trying to answer?
- What are appropriate threshold percentages to set feature toggles to in staged rollouts?

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
  - The subsection of users who might see the new feature is small and the first % rollout would be set higher (e.g. 80%) to increase the chances of a good sample size
- What area of the VA are you hoping to assess?
- How frequently do you need this data?
  - For every initiative in setting up the release plan

## Link to Metrics
N/A

## Additional Comments
I'm trying to put together a release plan for Community Care Provider Selection. VAOS is authenticated and within the app, only some users are eligible to request a Community Care appointment.

My understanding is that feature toggles apply to either all VA.gov users or a percentage of all VA.gov users, not specifically targeted to a specific app. For example, if I set the toggle to 25%, some of that percentage may not even use VAOS so in reporting and analysis, the consideration is that it's not 25% of VAOS users were exposed to the toggled feature.

Though the percentage of VAOS users that may be exposed to this CC feature are small (relative to app usage), we'd like to monitor downstream service performance so are not inclined to turn on 100%.

I'd ideally like the query parameters to use to gather this data so I can adjust reference dates as needed and use again in the future (as opposed to one-time total count).

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @laurenernest  ,

Thank you again for your request and providing great context. 

Please leverage [this segment](https://analytics.google.com/analytics/web/template?uid=Wtfhv9rIRImi0gQcSLiaTA) -- this segment correlates with our collection of LOA level post-login. 

I would then recommend adding this segment to the standard audience reports [here](https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/).

![image](https://user-images.githubusercontent.com/48527022/106460117-d3eb8e00-6460-11eb-8cdc-773040569791.png)

Using such segment will allow you to reference the logged in users at any point and adjust the date range within the standard GA report -- Please keep in mind when the segment is applied GA unfortunately only allows for 90 days of historical data to be analyzed. 

From here, we can estimate the % of logged in users who were exposed to the app feature and further among those given the feature how many engaged.

**Comment by laurenernest** [comment]
Thanks! Does this look right? So I could estimate about 1.2 mil users are logged in that would be the percentage the toggle is taken from?
![Screen Shot 2021-02-01 at 7 58 25 AM](https://user-images.githubusercontent.com/72046525/106483449-60974b80-6463-11eb-9929-b966139eb631.jpg)

**Comment by jonwehausen** [comment]
Hi @laurenernest , 

Yes, looks great! Yes - that is the correct user count. 

Fysa, if you would like to correlate against all site visits (regardless of the specific user) where someone logged in, please use the Sessions number. 

Will close this but please feel free to reopen if needed!
