### ISSUE TITLE
[Bug] Form 526 New disabilities page

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#19315]
If I...
* start a new application for disability, 
* get to the new disabilities page, and enter nothing https://staging.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/add
* click the back button on the page
* click the continue button on the page
I see this screen and the "add another condition" button is present but does nothing when I click on it.  

The form data:
````json
  "newDisabilities": [
    {}
  ],
  ````
<img width="841" alt="Screen Shot 2021-02-01 at 10 26 58 AM" src="https://user-images.githubusercontent.com/19188/106479299-2f754600-6478-11eb-8e90-caf698d807ae.png">

**Comment by Mottie** [comment]
Since this is occurring in the local dev environment, I'd say it's because the BDD feature flag is not enabled. Maybe it's about time to remove the feature flag?
