### ISSUE TITLE
HLR: Submit Application page (step 4)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1931]
## User Story or Problem Statement
As a claimant, I need to review and submit my HLR form so I can ensure all of the information I provided is accurate and submit my form.

## Goal
_Create a user friendly view of information to be reviewed and submitted_

## Acceptance Criteria
Scenario: System user wants to review and submit their HLR form
- GIVEN the HLR review form has been completed by a user
- WHEN the user reviews their provided form responses
*and* confirms their responses are accurate
*and* selects to submit their application
- THEN the system submits their HLR form

## Definition of Done
- [ ] _Build out of Submit Application page_
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
<img width="529" alt="HLR-6of6-Submit_Application" src="https://user-images.githubusercontent.com/54544300/65263948-9ab8b500-dadb-11e9-9817-e1eed0c46678.png">

**Comment by Mottie** [comment]
Changed to step 4/4; No new design is available, will update the screenshot when available

**Comment by ndsprinkle** [comment]
@YanaRoy Robin and I met and I will pick up this issue to work on.
