### ISSUE TITLE
[Bug] Form526 new disabilities page - duplicate disabilities

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#19319]
![Screen Shot 2021-02-01 at 11 05 00 AM](https://user-images.githubusercontent.com/19188/106485254-664e5a80-647e-11eb-8069-a3f4a737acb1.png)
On the form 526 [add new disabilities page](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/add) a veteran is allowed to add the exact same disability name twice.

 EVSS will reject claims that have duplicate disabilities with the error `form526.disabilities.isDuplicate: Claimant has added a duplicate disability` so we should validate the the names aren't duplicates.

**Comment by Mottie** [comment]
oops

**Comment by Mottie** [comment]
First half of the fixes are done... next up are the platform changes for the review & submit page.
