### ISSUE TITLE
HLR: Submitted page (confirmation step)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1932]
## User Story or Problem Statement
As a claimant, I need a confirmation that my HLR form has been submitted so I can verify that I have completed the process on my end.

## Goal
_Create a confirmation page_

## Acceptance Criteria
Scenario: System user wants to confirm their HLR form has been submitted
- GIVEN the HLR form has been completed by a user_
- WHEN the user submits the form_
*and* all errors have been resolved
- THEN the system provides a confirmation stating that the HLR form has been submitted

## Definition of Done
- [x] _Confirmation/submitted page built_
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

**Comment by Mottie** [comment]
@carolynwill This needs a design review. The screenshot above is from the outdated Mural design. I could not find an update in the inDesign pages.

**Comment by carolynwill** [comment]
Thanks for flagging @Mottie! I'll have a look and provide an updated design for you.
