### ISSUE TITLE
Provide CD numbers of dropped PDF cases (Sentry) to Caregiver Program team

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#19329]
**Scope**
For the cases identified in sentry, **up to January 25th**.

**AC**
- [x] Gather the claim IDs for all of the 10-10cg submissions that resulted in any of the sentry errors ([6552](http://sentry.vfs.va.gov/organizations/vsp/issues/6552/events/latest/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Acaregivers_assistance_claims), [5207](http://sentry.vfs.va.gov/organizations/vsp/issues/5207/events/latest/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Acaregivers_assistance_claims)).
- [x] Provide that list to CAMRA so they can add the CD numbers
- [x] Send the completed report to the Caregiver Program

**Comment by ala-yna** [comment]
Closing this - the timeout errors from 10/1 - 1/25 were went to the Program on 2/3.
