### ISSUE TITLE
Update End to End test for Yellow Ribbon FE.

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#19332]
## Issue Description
Yellow Ribbon FE end to end test currently utilizes night watch testing which is now deprecated and no longer running during the pipeline build. 
We need to update it to use Cypress which then it could be ran.

## Front end tasks
- Convert Nightwatch test to Cypress engine.
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin

## Acceptance Criteria
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel does this need grooming, or do you have a sense of how big an effort it is?

**Comment by zacharymorel** [comment]
Oh good question. 

This effort should be a 3. Basing that off of the Find Forms refactor I had to do.

**Comment by MarciMcGuireGCIO** [comment]
Thx. I'll go ahead and drop that estimate on here.

**Comment by zacharymorel** [comment]
I think I still see this as an important piece for our next sprint.
We currently are without end to end test coverage.

**Comment by MarciMcGuireGCIO** [comment]
Awesome, Zach!
