### ISSUE TITLE
STEM AD: Add user to 10203 submission details report

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19333]
As an Education Services team member, I need reporting done on the number of 10203 submissions and denials each day, so that I can monitor the number of automated denials vs the total number of submissions.

## Assumptions:
1. This story is completed behind feature the pre-existing feature flag.

## Acceptance Criteria:
1. A daily report is sent out that contains the 10203 and 10203 DNY spool file submissions from the previous day.
    a. `robert.shinners@va.gov` is included in the production report distribution

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-api/pull/5876

**Comment by delli-gatti-michael** [comment]
lgtm
