### ISSUE TITLE
Analytics Implementation or QA Support for [Authenticate Experience - Direct Deposit for Edu]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19334]
# Google Analytics Implementation or QA Request

**## What this form is for?**
Analytics set up for Direct Deposit for Edu on the VA.gov profile

 **Additional Comments**
- Staging link: https://staging.va.gov/profile/direct-deposit
- Staging user: vets.gov.user+378@gmail.com (Has DD4edu)
- [Staging user credentials in Sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-direct-deposit.md)
    
## Description
**Is this request for Google Analytics implementation or QA?**
GA implementation

**Who is this request for?**
Authenticated Experience team 
- DEPO Product Lead (required): **Samara Strauss**
- Product Manager (required): **Matt Shea, Jason Wolf**
- Designer (required): **Jim Adams**
- Frontend engineer(required): **Erik Hansen**
- Backend engineer (required): **Lihan Li**

Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
**What team/project is this work for?**
Authenticated Experience - Direct Deposit for Education Benefits

**Provide the Domain where Google Analytics needs to be implemented**
Va.gov/profile/direct-deposit
 
 **Identify if PII is passed in URL or title tag**
No

**Please provide any upcoming deadlines or important milestones**
Estimated launch: Early April

### Interactions to Track

**Information retrieval***
- Count of successful DD4edu information retrievals
- Count of failed DD4edu information retrievals 
- % of successful DD4edu retrievals

**Saves/submissions**
- Count of successful DD4edu saves/submissions
- Count of failed DD4edu information saves/submissions
- % of successful DD4edu saves/submissions

**Edits**
- Clicks to "edit" bank info

**Education benefit eligibility**
- Clicks to "Find out if your are eligible for education benefits"

**View payment history**
- Clicks to "View your payment history" 

**Searches for direct deposit from the profile**

- Number of searches week-to-week of searches for "direct deposit" from the Profile
  - **Note**: Remember that there are multiple pages in the profile, so this needs to account for all of the URLs, not just /profile, which is a retired URL that automatically forwards to /profile/personal-information.

 **Staging Users**
[Direct Deposit Staging Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-direct-deposit.md)

> Please leave the following blank
## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by mshea0606** [comment]
@Samara-Strauss @bmcgrady-ep @bsmartin-ep , Interactions to track and staging link/users have been updated.

**Comment by Samara-Strauss** [comment]
> % of successful DD4edu retrievals
> % of successful DD4edu saves/submissions

Do we need this explicitly? Feel free to keep if there is a reason. Otherwise, I would assume we can extrapolate this from successes/failures.

> Clicks to "edit" bank info
> Clicks to "edit account"
> Clicks to "edit routing number"
> Clicks to "edit account type"

This is representative of Profile 1.0 functionality. Please review staging/the mocks if you need to. There's only one Edit link now.

> Clicks to "View your payment history"

We can keep this if we want, but this already exists on the direct deposit for C&P dashboard, so I would say this is optional.

Also, is it possible to get the error types like we have for the direct deposit for C&P dashboard? For reference, this is what we have on the C&P dashboard:

<img width="500" alt="Screen Shot 2021-02-08 at 1 28 35 PM" src="https://user-images.githubusercontent.com/34068740/107264937-9f07aa00-6a11-11eb-9755-ab2bca64dd37.png">

**Comment by Samara-Strauss** [comment]
I added this in the main issue above, but flagging here for greater transparency — I've added this to the desired metrics list:

> **Searches for direct deposit from the profile**
> 
> Number of searches week-to-week of searches for "direct deposit" from the Profile

We are still seeing a lot of people searching for direct deposit from the profile, which is strange because the feature is very obviously IN the profile. However, it only shows if you're eligible to update direct deposit information. I want to see if searches go down once we add direct deposit for edu, or if this makes no difference in apparent find-ability.

**Comment by bmcgrady-ep** [comment]
@mshea0606  @Samara-Strauss - I have staged these changes in Google Tag Manager and everything looks good with the minor exception of on missing variable (in comparison to what is currently coming in for the cnp-direct-deposit events).

 onLoad of the profile direct deposit page for edu, the following dataLayer should be implemented:
```
dataLayer.push({
  event: 'profile-get-cnp-direct-deposit-retrieved',
  **direct-deposit-setup-eligible: true,**
  direct-deposit-setup-complete: true
})
```
The variable that is bolded is what is currently missing from the dataLayer load.

**Comment by Samara-Strauss** [comment]
Thanks for this @bmcgrady-ep! @mshea0606 can you please make sure this work gets passed off to FE?

**Comment by mshea0606** [comment]
@Samara-Strauss Yes, I'll create a FE analytics implementation ticket today

**Comment by erikphansen** [comment]
@bmcgrady-ep I can add the `direct-deposit-setup-eligible: true` to my existing call that looks like this:
```
recordEvent({
  event: 'profile-get-edu-direct-deposit-retrieved',
  // NOTE: the GET profile/ch33_bank_accounts/ is not able to tell us if a
  // user is eligible to set up DD for EDU, so we are only reporting if
  // they are currently enrolled in DD for EDU or not
  'direct-deposit-setup-complete': isSignedUpForEDUDirectDeposit(response),
})
```
As you can see in the comment, we have no way of knowing if someone is eligible for DD4EDU. The API for education benefits is not as fleshed out as the one for comp and pen benefits.

So if you need me send `direct-deposit-setup-eligible` and hardcode its value to `true` or `false` I can do that. But it feels misleading/inaccurate.

**Comment by Samara-Strauss** [comment]
> So if you need me send direct-deposit-setup-eligible and hardcode its value to true or false I can do that. But it feels misleading/inaccurate.

We do not need to track whether someone can add direct deposit for edu the way we track eligibility for direct deposit for comp & pen because, as Erik mentioned, we can't detect this for direct deposit for edu. You can take that out of the datalayer, @bmcgrady-ep.

**Comment by bmcgrady-ep** [comment]
@erikphansen @Samara-Strauss - You're correct, if eligibility isn't currently being tracked, then we don't need to pass it into the dataLayer.

**Comment by bmcgrady-ep** [comment]
@jonwehausen / @bsmartin-ep - When one of you have some time, can you QA this [workspace](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000453?orgId=oXPY3GFFQwaHnjNHpFLyFg)? Thank you!

**Comment by jonwehausen** [comment]
Thanks @bmcgrady-ep , yes will pickup the QA here.

**Comment by erikphansen** [comment]
@bmcgrady-ep so no updates are needed on the FE? Direct deposit for EDU is hooked up to GA properly as far as you can tell?

**Comment by jonwehausen** [comment]
## QA Testing

- Tested with user +378 who had DDEdu setup

Test Case | Tag Screenshot | QA Status
| -- | -- | -- |
_Get edu direct deposit API call started_ | ![image](https://user-images.githubusercontent.com/48527022/108757694-2c6df280-7518-11eb-82a3-a25bf48bcd16.png) | ✔️ **PASS**
_Get edu direct deposit API call retrieved_ | ![image](https://user-images.githubusercontent.com/48527022/108758921-b10d4080-7519-11eb-90e8-38c6d0f65349.png) | ✔️ **PASS**
_Get edu direct deposit API call - failed_ - simulated manual DL push | ![image](https://user-images.githubusercontent.com/48527022/108759121-f467af00-7519-11eb-8040-c095be2acedc.png) | ✔️ **PASS**

**Comment by jonwehausen** [comment]
@erikphansen Just letting you from our testing we did in fact see the `direct-deposit-setup-complete` variable pushed with the `profile-get-edu-direct-deposit-retrieved` event -- this can be please removed from this event push if not needed to track eligibility and completion per you all's conversation here. 


![image](https://user-images.githubusercontent.com/48527022/108759829-e1a1aa00-751a-11eb-9ffe-453ad6a4721a.png)

@bmcgrady-ep As a result, I removed the `direct-deposit-setup-complete` variable from that event taxonomy in "Profile Direct Deposit Retrieval - Lookup Table" in order to avoid sending this variable to GA. 

In any case tagging has been published and data is now collecting.

**Comment by jonwehausen** [comment]
@bmcgrady-ep Assigning back to you for final closure.

**Comment by bmcgrady-ep** [comment]
Thanks for the QA @jonwehausen. 

@mshea0606 I'm closing out this issue as the updates have been made on our side.

**Comment by Samara-Strauss** [comment]
Reopening this temporarily — we still need handoff of the actual dashboard. @bmcgrady-ep is already checking on this for us [Slack](https://dsva.slack.com/archives/C909ZG2BB/p1614699930116900). Feel free to hand off here or in Slack, and I'll close this once we have the actual dashboard.

**Comment by Samara-Strauss** [comment]
Nevermind, apparently we needed a different request for the actual dashboard? Closing this. We can open up a ticket to get the actual dashboard created based on the tracking above.
