### ISSUE TITLE
[Design] Add My VA to unauth nav and add sign-in flow to prototype

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#19356]
## Background

Product decisions in #14581.

[Per a discussion within the OCTO team](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14581#issuecomment-771175209), we've decided to add My VA to the unauth nav to help guide people to this page. This is all pending usability testing, but assuming it tests well, this is the plan going forward.

I'd like us to update the mocks to reflect the following flow so we can test people's reactions and understanding in our upcoming round of usability testing:

- My VA should show in the unauth navigation. **Do not add My Health to the unauth nav, just My VA**.
- Clicking My VA should trigger the sign in flow.
- Once a user completes the sign in flow, they'll land on the My VA dashboard.

## Tasks

Update the mockups/prototype to reflect the following:

- [x] My VA in the unauth nav
- [x] The sign in flow (triggered after clicking My VA)

**Comment by Samara-Strauss** [comment]
@tressaellen @callen2563 let me know if you want to meet briefly to discuss this. I'm happy to answer any questions, but hopefully it's pretty straight forward.

cc/ @mshea0606

**Comment by mshea0606** [comment]
@Samara-Strauss is this for this sprint or should we move it until after usability testing?

**Comment by Samara-Strauss** [comment]
Yes, this is for this sprint. This screen needs to be included for usability testing, so please create both a desktop and mobile mockup of it. 

For the unauth desktop nav, I think My VA would remain where it is in the auth nav:

<img width="1017" alt="Screen Shot 2021-02-08 at 2 31 55 PM" src="https://user-images.githubusercontent.com/34068740/107271740-a41d2700-6a1a-11eb-9cbe-ae3a96f56a1e.png">

This means that on mobile, My VA would go in the menu for the unauth state:

<img width="500" alt="Screen Shot 2021-02-08 at 2 31 16 PM" src="https://user-images.githubusercontent.com/34068740/107271770-b26b4300-6a1a-11eb-8d0c-7eabfee3923f.png">

**Comment by Samara-Strauss** [comment]
Also, re: desktop design — since we are NOT adding the My Health link to the unauth nav as well, this means My VA is now hanging out on its own. We should propose a design where it's more proximal to "Find a VA Location", though that would likely mean also leaving it in that position (and maybe also moving My Health?) in the auth nav. If you can mock up all of these, that would be great, and we can review with the Public Websites team and various design keepers to settle on an approach.

**Comment by Samara-Strauss** [comment]
Done. Prototype is in #19164.
