### ISSUE TITLE
[FE] Ensure we collect GA data on the View Payment History link

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#19352]
## Background

We need to make sure we record clicks on the 'View Payment History' link even though we no longer send users to eBenefits. 
Originally, the EbenefitsLink that was used sent `event: 'nav-ebenefits-click'` upon clicking the link.

Exact event string TBD.

## Tasks
- [ ] Add GA data recording to [View Payment History link](https://github.com/department-of-veterans-affairs/vets-website/blob/a1a50aba7059361594494d016b085bd31f92e0ef/src/applications/personalization/profile/components/direct-deposit/BankInfoCNP.jsx#L250)
- [ ] Also update [the new link](https://github.com/department-of-veterans-affairs/vets-website/blob/e7ea94ee72c08db5e827f0ad136cedf350bafa4b/src/applications/personalization/profile/components/direct-deposit/PaymentHistory.jsx#L13) that will roll out with DD4EDU

**Comment by bmcgrady-ep** [comment]
@sanlouise - Thank you for the patience here.

For the View Payment History link clicks, I would add this tracking:
![image](https://user-images.githubusercontent.com/66263904/106788863-c3791600-660e-11eb-885e-41c6ca2a555e.png)
```
dataLayer.push({
  event: 'profile-navigation',
  profile-action: 'view-link',
  profile-section: 'view-payment-history'
})
```

For the Education Benefits link clicks, I would add this tracking:
![image](https://user-images.githubusercontent.com/66263904/106788975-e3a8d500-660e-11eb-969e-2304c9d5289f.png)
```
dataLayer.push({
  event: 'profile-navigation',
  profile-action: 'view-link',
  profile-section: 'education-benefits'
})
```

**Comment by erikphansen** [comment]
@bmcgrady-ep We also have a link we show when when someone does not appear to have Comp and Pension benefits: `Find out if you’re eligible for VA disability benefits`. I assume the tracking for that would be similar to the `Find out if you’re eligible for VA education benefits`, but with a different `profile-section`:

```
dataLayer.push({
  event: 'profile-navigation',
  profile-action: 'view-link',
  profile-section: <what string would you like us to put here?>
})
```

**Comment by bmcgrady-ep** [comment]
@erikphansen - Here is what I would recommend for the dataLayer.push
dataLayer.push({
  event: 'profile-navigation',
  profile-action: 'view-link',
  profile-section: 'disability-benefits'
})
