### ISSUE TITLE
Add to query parameters for FL troubeshooting

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19366]
## Issue description
Need to add additional query parameters to aid in troubleshooting. Anything sent in backend should be present in URL) 

Currently sending: 
**VA facility:**
https://www.va.gov/find-locations/?page=1&address=27606&facilityType=urgent_care&serviceType=NonVAUrgentCare&location=35.78%2C-78.68&context=Raleigh%2C%20North%20Carolina%2027606%2C%20United%20States

**Community care:**
https://www.va.gov/find-locations/?page=1&address=27606&facilityType=provider&serviceType=111N00000X&location=35.78%2C-78.68&context=Raleigh%2C%20North%20Carolina%2027606%2C%20United%20States

## Acceptance Criteria
- [ ]Query parameters include Facility type, service type or PPMS specialty code, lat/long and radius 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
@ryguyk thinks this might be resolved

**Comment by ryguyk** [comment]
This looks to be resolved. I clicked on the links given in the description, then, in a separate browser, copied the search form and clicked "Search". Then I looked at the generated URL. Here is what I got:

### VA facility:
#### Original
https://www.va.gov/find-locations/?page=1&address=27606&facilityType=urgent_care&serviceType=NonVAUrgentCare&location=35.78%2C-78.68&context=Raleigh%2C%20North%20Carolina%2027606%2C%20United%20States
#### Now
https://www.va.gov/find-locations/?page=1&address=27606&facilityType=urgent_care&serviceType=NonVAUrgentCare&latitude=35.750696&longitude=-78.708426&radius=11&bounds%5B%5D=-79.458426&bounds%5B%5D=35.000696&bounds%5B%5D=-77.958426&bounds%5B%5D=36.500696&context=Raleigh%2C%20North%20Carolina%2027606%2C%20United%20States

### Community care:
#### Original
https://www.va.gov/find-locations/?page=1&address=27606&facilityType=provider&serviceType=111N00000X&location=35.78%2C-78.68&context=Raleigh%2C%20North%20Carolina%2027606%2C%20United%20States
#### Now
https://www.va.gov/find-locations/?page=1&address=27606&facilityType=provider&serviceType=111N00000X&latitude=35.750696&longitude=-78.708426&radius=11&bounds%5B%5D=-79.458426&bounds%5B%5D=35.000696&bounds%5B%5D=-77.958426&bounds%5B%5D=36.500696&context=Raleigh%2C%20North%20Carolina%2027606%2C%20United%20States
