### ISSUE TITLE
[Bug] 10-10EZ Address - Authenticated - Mailing address not pre-filled from Profile

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#19365]
## What happened?
On Staging **Apply for health care benefits > Veteran Information > Mailing address** form-page, for User w/ Mailing address saved in Profile, mailing-address fields are not pre-filled from Profile.

## Specs:
- Devices: [device-agnostic]
- Browsers: [browser-agnostic]
- Test User: Only-Mailing-in-Profile: `vets.gov.user+99@gmail.com` (Randall)

## Steps to Reproduce
1.  Go to https://staging.va.gov/health-care/apply/application/introduction
2.  Click **Sign in to start your application** button, and sign-in via **ID.me** as **`vets.gov.user+99@gmail.com` (Randall)**.
3. Advance to **Veteran Information > Mailing address** form-page, completing required fields and clicking **Continue** on the way there.
4. Observe that mailing-address fields are not prefilled from Profile.

[See also missing-Home-address-field bug #19364]

## Desired behavior
For any User with Mailing address in Profile, mailing-address fields should be pre-filled.

## Acceptance Criteria
- [ ] [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ala-yna** [comment]
@tlei123, this should be resolved with https://github.com/department-of-veterans-affairs/va.gov-team/issues/18832. Please close out this ticket once you're able to confirm.

Thanks!

**Comment by tlei123** [comment]
@ala-yna , fix validated on Staging.  Closing issue now.
