### ISSUE TITLE
[Bug] 10-10EZ Address - No addresses in Profile - Mailing-address page missing Home-address field

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#19364]
## What happened?
On Staging **Apply for health care benefits > Veteran Information > Mailing address** form-page, for authenticated Users listed below, **Is your home address the same as your mailing address?** field was missing.

## Specs:
- Devices: [device-agnostic]
- Browsers: [browser-agnostic]
- Test Users:
  - (a) Authenticated - No-addresses-in-Profile: `vets.gov.user+113@gmail.com` (Greg)
  - (b) Authenticated - Only-Mailing-in-Profile: `vets.gov.user+99@gmail.com` (Randall)
  - (c) Authenticated - Maling-Home-different-in-Profile: `vets.gov.user+100@gmail.com` (Norman)

## Steps to Reproduce
1.  Go to https://staging.va.gov/health-care/apply/application/introduction
2.  Click **Sign in to start your application** button, and sign-in via **ID.me** as (a) **`vets.gov.user+113@gmail.com` (Greg)**, (b) **`vets.gov.user+99@gmail.com` (Randall)**, or (c) **`vets.gov.user+100@gmail.com` (Norman)**
3. Advance to **Veteran Information > Mailing address** form-page, completing required fields and clicking **Continue** on the way there.
4. Below Mailing-address form-fields, observe that there's no **Is your home address the same as your mailing address?** field.

[See also pre-fill bug #19365]

### Screenshot
![qa-bug-10-10ez-no-addr-in-profile-missing-home-addr-field](https://user-images.githubusercontent.com/587583/106531901-59486000-64ac-11eb-800b-53d4adf9628b.png)

## Desired content
Mailing-address form-page should display **Is your home address the same as your mailing address?** field.

### Design-prototype
![spec-10-10ez-home-addr-field](https://user-images.githubusercontent.com/587583/106532274-1b980700-64ad-11eb-9710-7265af6ece84.png)

## Acceptance Criteria
- [ ] [See **Desired content** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ala-yna** [comment]
Closing this ticket; should be fixed by https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/18834
