### ISSUE TITLE
Broken images in local cms-export build

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19367]
Most image paths in the cms-export build are broken.

Steps to reproduce:

1. yarn build:content  --use-cms-export --pull-drupal
2. View any pages with images

These are showing up as legit diffs in the JSON diff tool, e.g.:

  {
    "diffType": "Property Edited",
    "path": "mainFacilities/entities/0/fieldMedia/entity/image/derivative/url",
    "graphQL": "https://prod.cms.va.gov/sites/default/files/styles/3_2_medium_thumbnail/public/2019-02/university-drive-consolidation-building2.jpg",
    "cmsExport": "/img/styles/3_2_medium_thumbnail/public/2019-02/university-drive-consolidation-building2.jpg"
  }

![VA_Pittsburgh_Health_Care___Veterans_Affairs.png](https://images.zenhubusercontent.com/5ee91ea93ee2bbe222cd827f/a932db28-b0ac-417e-9c80-952cecbb894e)

**Comment by mchelen-gov** [comment]
@mpelzsherman is that build output coming from Jenkins or local?

**Comment by theodur** [comment]
This same issue is also affecting files/documents in the CMS export:
```json
{
    "diffType": "Property Edited",
    "path": "fieldContentBlock/20/entity/fieldMedia/entity/fieldDocument/entity/url",
    "graphQL": "https://prod.cms.va.gov/sites/default/files/2020-11/survivor-quick-start-guide.pdf",
    "cmsExport": "/files/2020-11/survivor-quick-start-guide.pdf"
}
```

**Comment by jhonnyoddball** [comment]
Images are no longer broken

We just need to fix the image url `diff`

**Comment by meganhkelley** [comment]
Standup update from Jhonny: found solution but will be testing it with multiple nodes and doing cleanup, should have that up today or tomorrow

**Comment by jhonnyoddball** [comment]
Fixed with PR [16005](https://github.com/department-of-veterans-affairs/vets-website/pull/16005)
