### ISSUE TITLE
Set ASG timeout for PROD, DEV, and STAGING 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#1937]
From the CMS team task:
Set ASG timeout to 30 seconds for PROD (and 5 seconds for DEV and STAGING) so that deployments will speed up by 7 minutes.

**Comment by tskinn** [comment]
This has been taken care of in https://github.com/department-of-veterans-affairs/devops/pull/5558 and https://github.com/department-of-veterans-affairs/devops/pull/5569

**Comment by ricetj** [comment]
ok closing
