### ISSUE TITLE
Create a process for updating Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#19382]
# Description
Given that the Cypress team is releasing minor version every few weeks and major versions a few times per year we need a standard process for upgrading to new minor version and new major versions.

# Acceptance Criteria
- [ ] A Cypress upgrade process document has been created in va.gov-team
- [ ] The Cypress upgrade process document contains a specific process for upgrading to new minor versions
   * How to perform the upgrade in vets-website
   * How to document changes from Cypress' changelog into our best practices document
   * How much notice to give VFS teams
- [ ] The Cypress upgrade process document contains a specific process for upgrading to new major versions
   * How to perform the upgrade in vets-website
   * How to document changes from Cypress' changelog into our best practices document
   * How much notice to give VFS teams

**Comment by ddzz** [comment]
`va.gov-team` PR has been merged: https://github.com/department-of-veterans-affairs/va.gov-team/pull/19811

**Comment by pjhill** [comment]
This effort generated the [Cypress Upgrade Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-upgrade-guide.md) which the team will use going forward to upgrade Cypress.

**Comment by pjhill** [comment]
This effort generated the [Cypress Upgrade Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-upgrade-guide.md) which the team will use going forward to upgrade Cypress.
