### ISSUE TITLE
Provide CD numbers of dropped PDF cases to Caregiver Program team

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#19384]
**Scope**
For the cases identified in sentry **from January 25th - January 31**. Also, collect the timestamp of when the submission request was made for Ranga to cross-reference with their timestamps.

**AC**
- [x] Collect sentry errors (populate the spreadsheet).
- [x] Gather the claim IDs for all of the 10-10cg submissions that resulted in any of the sentry errors ([6552](http://sentry.vfs.va.gov/organizations/vsp/issues/6552/events/latest/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Acaregivers_assistance_claims), [5207](http://sentry.vfs.va.gov/organizations/vsp/issues/5207/events/latest/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Acaregivers_assistance_claims)).
- [x] Provide that list to CAMRA so they can add the CD numbers
- [ ] Send the completed report to the Caregiver Program

**Comment by kevinmirc** [comment]
Blocked - Before collecting more case IDs, we want to get the Caregiver Program up to speed on what this issue is and understand (1) if they need the case IDs, (2) how they will use them, and (3) how frequently they will need the data.

**Comment by ala-yna** [comment]
Sent to the program on 2/4.
