### ISSUE TITLE
R&S Disability: Create new spreadsheet for SME review

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#19396]
###Issue
Because the bulk of disability-related IRIS questions were updated prior to 2015, we have very little disability content for R&S articles. 
We need to go back to the original IRIS spreadsheet and pull all disability questions into a new spreadsheet for SME review.

###Tasks
- [ ] Create new spreadsheet (Laura)
- [ ] Create another GH ticket for DE review (Laura)

**Comment by lwalsh617** [comment]
@bethpotts @bethpottsVADEPO -- 
Here's the spreadsheet. A few things to note:
![image](https://user-images.githubusercontent.com/53535663/107805594-8eb63e80-6d33-11eb-9d64-d41b2dd03377.png)
Happy to walk through it on a call if that's helpful. 
L
[FAQs-irishost_Disability.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5973618/FAQs-irishost_Disability.xlsx)

**Comment by lwalsh617** [comment]
[rs-disability-irisfaqs-migrate-030821.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6102537/rs-disability-irisfaqs-migrate-030821.xlsx)
@bethpotts @bethpottsVADEPO  -- Here is the updated spreadsheet for disability faqs. Per our call on Friday, I pulled all the ones that we do not want to migrate (because they're tier 1) so it's now a shorter list for the SME to review. Let me know if you have any questions.

**Comment by bethpottsVADEPO** [comment]
I think we can close this ticket now. I had Paul review these (the really specifically disability ones) and he said articles about them would be good to have:

- What is Combat-Related Special Compensation and why is it important?
- How do I get a copy of my rating decision?
- What is a Non-compensable disability?
- What is the difference between VA compensation and severance disability?
- Are there other VA benefits related to compensation?
- How does VA determine someone's net worth?
- If I am already receiving monthly payments or a service-connected disability can I get a VA pension too?

You can proceed with writing these.
