### ISSUE TITLE
Discovery: identify steps for taking over subdomain

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#1939]
We need to figure out how to get pittsburgh.va.gov pointed at the VFS infrastructure.

There are steps fairly well known at VA for obtaining a new domain and tearing down an old one, but nothing related to moving a domain from one system to another.

Need to do some discovery starting with site owner and DSVA to figure out what steps might be necessary.

**Comment by wyattwalter** [comment]
We setup a call on Monday to kick this off with the site owner.

**Comment by ricetj** [comment]
Talking to Boris next week.

**Comment by ricetj** [comment]
Had meeting with Web Ops, went well and moving forward with more discovery.

**Comment by wyattwalter** [comment]
@ricetj at this point do we need to continue with this particular issue, given that WebOps was ok with keeping status quo? I'm not sure what'll happen if we have launches that require a bunch of redirects.. but it sounds like the process itself is relatively simple should we need to take over one in the future.

**Comment by ricetj** [comment]
Agreed, let's close and just keep this process documented for future use
