### ISSUE TITLE
STEM AD: Create API Endpoint to use to retrieve Denial Data Display

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19390]
As a developer, I need to create an API endpoint that retrieves the automatic denial data for a user so that it can be used to display the information on a user facing page.

## Assumptions:
1. N/A

## Acceptance Criteria
1. An API endpoint exists that:
    a. Accepts an authenticated user
    b. Returns the 10203 submissions associated with that user from the `education_stem_automated_decision` and `education_benefits_claims` tables.
2. The new data returned by the endpoint includes:
    a. automated_denial - boolean
    b. form "isEnrolledStem" answer
    c. form "isPursuingTeachingCert" answer
    d. form "benefitLeft" answer
    e. EVSS remaining_entitlement (days at time of process)
    f. denied_at:  if automated_denial  is true then this would be education_stem_automated_decisions.updated_at
    g. submitted_at (user submission date)

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-api/pull/5957
- https://github.com/department-of-veterans-affairs/vets-api/pull/5950

**Comment by dmccurdybah** [comment]
The new endpoint should return a list of submitted 10203 forms for logged in users

http://localhost:3000/v0/education_benefits_claims/stem_claim_status

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
This is in staging and can be viewed by going to the following link while logged in as a user with a 10203 submission:
https://staging-api.va.gov/v0/education_benefits_claims/stem_claim_status

Closing this story
