### ISSUE TITLE
Access for Nathan Douglas - AWS Console

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#19398]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Nathan Douglas
- Please Provide your email.
   > nathan.douglas@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Senior Software Engineer on the Agile Six VFS-CMS team

- Requesting SSH key authorization?
   > NO, have it already 😁 

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
@ElijahLynn recommended I get AWS access to learn about the Devops side of things.

**Comment by oragame** [comment]
**### For AWS Access:**
User: Nathan Douglas
COR: Jeff Hayter
Approval Required: @Jeff-Hayter

**Comment by ElijahLynn** [comment]
This is required initially for Cloudwatch logs access and dashboard building etc. and to debug server/infra issues from time to time etc.

**Comment by jsev-io** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by jsev-io** [comment]
Access credentials and instructions delivered to user.
