### ISSUE TITLE
Title of Past Appointments list should update with date range

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#19392]
## What happened?
When interacting with the dropdown selector on the 'Past' state of the Appointments overview screen, the list title reads "Past 3 months" for any selected date range.

## Specs:
- Device: iPhone 6 Plus
- Test User: Bridget

## Steps to Reproduce
- Test User: User +228 has past appointments in different date ranges

## Desired behavior
Title of Past Appointments list should match the selected date range: 
- "Past 3 months"
- "Sep 2020 - Nov 2020"
- "Jun 2020 - Aug 2020"
- "Mar 2020 - May 2020"
- "All of 2021"
- "All of 2020" 

## Acceptance Criteria
- [ ] List title updates to match the dropdown selection text 

## Screenshots
![IMG_1028.PNG](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/07ad069d-11ed-451e-ac71-bcd1f47e381f)
![IMG_1029.PNG](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/9d08cef3-2617-4052-875c-053186af9304)

**Comment by digitalken** [comment]
PASS 2/4/2021 - Past 3 months changes with selection.
