### ISSUE TITLE
Prepare examples of VA waterfall traps to walk product owners through during onboarding

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#194]
## Story
As a VFS Product Team Lead, my team didn't have time to iterate and explore options based on feedback because waterfall deadlines were being dictated and we lacked of top cover from leadership

## Goal
Help new VFS Product Teams embrace iterative development by conveying the detriments of waterfall through examples and  strategies for operating in agile.

## AC
- [ ] Documentation has been created that highlights the traps of waterfall strategies for operating in an agile manner
- [ ] This documentation has been incorporated into the onboarding process for new teams.

## Def of Done
- [ ] AC is complete
- [ ] Connected to an epic

**Comment by andreahewitt-odd** [comment]
Part of PM presentation?
