### ISSUE TITLE
Adding 2 new CMS groups to DSVA Slack

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#19408]
Looking to set up 2 new slack groups for the Durpal CMS team. Please let me know if this isn't the correct intake for this type of request. Thanks!

**Name:** CMS core application team
**Handle:** `@cms-core-application-team`
**Purpose (optional):** to increase collaboration and awareness with the CMS core application team
**Default channels:** #cms-team #cms-support
**Members:** Adrian Rollett, Neil Hastings, Nathan Douglas, Oksana Cyrwus, David Addison, Rachel Kauff, Jordana Mello, Elijah Lynn, Eric Oliver, Ero Gray, Vanessa Luxen

**Name:** CMS product support team
**Handle:** `@cms-product-support-team`
**Purpose (optional):** to increase collaboration and awareness with the CMS product support team
**Default channels:** #cms-team #cms-support
**Members:** Clarence Maeng, Kevin Walsh, Jane Xiong, Natalie Dunbar, Steve Wirt, Ethan Teague, Kaise Lafrai

**Comment by LEHigley** [comment]
hi @cmaeng i'm just getting to this now and it looks like it's all done? sorry for the delay!
