### ISSUE TITLE
Take over va-cms-bot account, credstash, MFA

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#1940]
Elijah will reach out

**Comment by ricetj** [comment]
@ElijahLynn is this something that still needs done?

**Comment by ElijahLynn** [comment]
Yeah, right now I am the only one with the 2fa access. I do believe it is in our credstash already. I think I need to do a transfer to @wyattwalter.

**Comment by jbritt1** [comment]
We also should consider spreading access to va-vfs-bot throughout the ops team due to this conversation: https://dsva.slack.com/archives/CJYRZK2HH/p1581620875013600. Does this need to be its own ticket or could it be added to this and tackled simultaneously?

**Comment by jbritt1** [comment]
Actually, I think even after access to these bots is dispersed we will want to include some sort of documentation / process for new ops team members. So maybe that answers my question on making it its own ticket(s).

**Comment by ricetj** [comment]
The VSP doesn't need access to your bot unless there is some Infra work that needs to happen, so we are closing this ticket.

**Comment by ElijahLynn** [comment]
I think this is good to close too. At the time this was noted, I didn't fully understand the different team roles.
