### ISSUE TITLE
Fix for displaying "On this page" in spanish on Corona FAQ page vs English (short-term)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#19407]

**Comment by SKasimow** [comment]
Problem: as a content creator for VA.gov, I would like to have the drupal component for "On this page" on the Corona FAQ spanish page be displayed in spanish vs english.

Acceptance Criteria:

[ ] Identify a short-term solution for this issue
[ ] See spanish text for "On this page" (awaiting translation)

Screenshot:
https://app.zenhub.com/files/133843125/743a8900-54a1-425d-ab91-8d99dccfeb4d/download


Background / Approach: 

The short term solution would be grabbing the on this page by ID ( document.getElementById("on-this-page")) and using this object to toggle the values:

  en: {
    linkTitle: 'Read this page in English',
    langToggleLink: '/coronavirus-veteran-frequently-asked-questions',
    onThisPage: 'On this page',
  },
  es: {
    linkTitle: 'Leer esta página en Español',
    langToggleLink: '/coronavirus-veteran-frequently-asked-questions-esp',
    onThisPage: "Spanish Translation of On this Page"
  },
};

**Comment by SKasimow** [comment]
Research ticket for reference: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18527

**Comment by youngfreezyVA** [comment]
put the placeholder text in a feature branch while we wait on spanish translation

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA hi - just a reminder for the translation text when you send in your next set of asks :)

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow Got confirmation from VHA translation group that this should be:

En esta página

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Thanks Danielle!

@youngfreezyVA - here's the text (above); can you make update the page?
