### ISSUE TITLE
[FE] DD4edu accessibilty scans required pre-staging review

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19410]
## Background
There are some 508 checks/scans needed prior to the Staging Review for DD4edu.

[Staging review 508 scans/checks](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md)

## Tasks
- [x] Axe scans in daily development - read more about the axe browser plugin
- [x]  Axe scans included in end-to-end (e2e) tests

**Comment by erikphansen** [comment]
I ran the aXe scans in staging with user 378 and it didn't reveal any issues with the DD4EDU feature.
