### ISSUE TITLE
[Bug] Form526 incorrect addresses. 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#19423]
Michael Walker from EVSS [alerted us to an issue](https://dsva.slack.com/archives/C8R3JS8BU/p1612301669042400) with incorrect veteran addresses being submitted to EVSS.  @annaswims has an email with more PII examples. 

The RO rep who submitted the error info says she has seen around 10 of these in recent weeks.

We no longer have the In-progress form data ,  but we do have the translated data we sent to evss, which is indeed incorrect. 
The strikethrough parts of the address are incorrect.  The veteran lives at a domestic US address with a city/state.
> {"country"=>"USA", 
"addressLine1"=>"redacted correct address line1", 
~~"type"=>"MILITARY", 
"militaryPostOfficeTypeCode"=>"APO", 
"militaryStateCode"=>"AA", ~~
"zipFirstFive"=>"27103"}

@annaswims was able to reproduce at least part of the bug. If I toggle the "I live on a United States military base outside of the United States" checkbox I am no longer able to select states. 

![Screen Shot 2021-02-02 at 5.51.58 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/257d7db1-9fa0-40ff-9ddd-1cb16df59c81)

## Acceptance criteria
- [ ] Notify Michael walker when complete

**Comment by annaswims** [comment]
To see the prod data in the rails console:
`JSON.parse(Form526Submission.where(submitted_claim_id: 82548441).first.form_json).dig("form526", "form526", "veteran", "currentMailingAddress")`

**Comment by Mottie** [comment]
I think the reason that the state dropdown was only showing AA, AE and AP as choices is because the city was set to APO. As soon as you update the city value. I will strip out extra data from the prefill and submitted mailing address
