### ISSUE TITLE
Draft User Model for Identity

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#19421]
[Start of document](https://docs.google.com/spreadsheets/d/1H8NGzU9E5-u-jyVvsoYekSkdojcOISdugSePf7ZXc34/edit?usp=sharing)

**Comment by jimiray** [comment]
@joeniquette I found information on [SCIM](http://www.simplecloud.info/), System for Cross Domain Identity Management, and think it's a good fit. But we would also need to write schema extensions for relationship data and person type. And I also found a corresponding specification named [UMA](https://simpleidserver.readthedocs.io/en/latest/topics/use-uma-to-protect-api.html) that's used to protect SCIM information. This may be a good approach to delegation.

**Comment by jimiray** [comment]
Identity Module and Class attributes:

https://whimsical.com/identity-mind-map-B4UBDcYGnE2CntRTE6Cjdh

**Comment by jimiray** [comment]
@bosawt @joeniquette @bramleyjl Attached the mind map for identity from Whimsical. Please provide feedback.

**Comment by joeniquette** [comment]
oauth, odic, military/overseas addresses (I'll check in the MPI document)

**Comment by jimiray** [comment]
@bosawt 
1. I don't think so, but I'll update the diagram based on some recent thinking based on recent prototyping.
2. Yes, or at least as far as I'm aware, I based the SAML on what's present now.
3. I had not looked at the IAMUser, I'll look now.

**Comment by jimiray** [comment]
Whimsical MindMap is here: https://whimsical.com/identity-mind-map-B4UBDcYGnE2CntRTE6Cjdh
