### ISSUE TITLE
Process for incorporating new VA.gov products into Performance Dashboard data

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#19424]
### Background
- The [VA.gov performance dashboard](https://www.va.gov/performance-dashboard/) was updated in 2020, and the team the built it has since moved on to other work.
- It's pretty straightforward and [well documented on github](https://github.com/department-of-veterans-affairs/vets.gov-status)
- It draws its data from Foresee and from Google Analytics
- As we’ve added new products to VA.gov, we don’t routinely add them to this dashboard, and as a result they're probably not getting counted in the sections in which they belong (health, benefits, etc.)
- Adding new products is very easy, once the events associated with the transaction are tagged / added in our Google Analytics
- For example, here's a PR where one product team attempted to add a product to the scorecard. It involved just updating a YML file, but did require some support from the previous builders of the performance dashboard.  https://github.com/department-of-veterans-affairs/vets.gov-status/commit/fb4d44f946e2a38a4ec52f96da88737502bfe4cb

### Solution idea
How might we update our process (either collab cycle, or launch checklist, or analytics, or other process) to 1) consider if a new product should be added to the performance dashboard and 2) enable a VFS team to do so (i.e. edit YAML file with new product name and associated GA tag?)

**Comment by johnny-jesensky-adhoc** [comment]
Closing this out -- the Performance Dashboard is currently being managed by the IIR Team, who we've been collaborating with on ensuring the dashboard continues to function with GA4 data.

There is ongoing discussion on improvements to the dashboard from their team.
