### ISSUE TITLE
CT Redesign: EYB Panel - Concepts for improved data display

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#19434]
Work with Dev to understand data sources
Draft concepts to explore solutions
Review with UX team
Respond to feedback & incorporate as appropriate

**Comment by JenLJ** [comment]
Mural with design:  https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1612271586595/bba9c799de908a15ae8a92b7ec0f40d2e0c6715d
