### ISSUE TITLE
[AXE-CORE]: Definition list DD and DT elements must be contained by a DT

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#1943]
## Description

Definition lists being used in our forms are returning invalid markup errors in axe. Screenshots attached below for the non-logged-in Healthcare and Education forms showing the elements in question.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Related Issues
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/1709

## Acceptance Criteria

* As a tester using the [axe plugin](https://deque.com/axe) I do not want to see any errors related to definition lists in our form system.
* As a user, I do not want to see any visual changes in the form review step that uses definition lists.

## WCAG or Vendor Guidance (optional)

* [Parsing: Understanding SC 4.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html)

## Screenshots or Trace Logs

![Screen Shot 2019-09-19 at 4 25 38 PM](https://user-images.githubusercontent.com/934879/65282928-c21f7a00-dafb-11e9-85fd-0770628d8042.png)

---
![Screen Shot 2019-09-19 at 4 32 44 PM](https://user-images.githubusercontent.com/934879/65282942-c8155b00-dafb-11e9-93c3-79de7f6c29c9.png)

**Comment by 1Copenut** [comment]
@brandonrapp I first discovered this issue in the 526 v1 form, but after talking with one of the devs working on it, realize it's a wider issue, so closed that one off and opened this sitewide issue for the Tools team to investigate. LMK if I can help QA or answer questions.

**Comment by brandonrapp** [comment]
Thank you @1Copenut! We will get someone to look at this shortly. We will be sure to grab you if we have questions!

**Comment by Mottie** [comment]
I was working on the platform ReviewFieldTemplate for another issue and ended up fixing this issue in https://github.com/department-of-veterans-affairs/vets-website/pull/11120
