### ISSUE TITLE
Add another mock error state to test account

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19431]
## Context for this task
This task is a stop-gap in order to demo the UI for various error states using mock data. There is a separate ticket to revert this ticket, which the FE team will implement post-demo. (#19175)

## Acceptance Criteria:
1. Display the following mock error state on the Claims & Appeals page: 
     - Error state: **Claims unavailable, no Appeals** (#18244)
     - User account that should display this error: vets.gov.user+366@gmail.com

**Comment by bessgreen** [comment]
@digitalken please confirm when you've passed this ticket. Once complete, we will remove the mock C/A errors from 4 test accounts (#19175).

**Comment by digitalken** [comment]
PASS 2/8/2021 - I don't think I need this anymore @bessgreen .
