### ISSUE TITLE
Rework user validation messaging on 10-10EZ to be less aggressive  

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#19435]
## Design Task

According to our user [messaging guidelines](https://design.va.gov/patterns/messaging-dictionary) the HCA seems to be a little out of spec. Please look through the HCA to confirm our user validation meets our guidelines to be less aggressive.

## Expected Behavior

User messaging and validation errors are more welcoming do not user verbiage like "must"

## Acceptance Criteria

- [ ] User validation on the HCA (10-10EZ) meets our messaging guidelines

## Additional context
During this [Peer Review](https://github.com/department-of-veterans-affairs/vets-website/pull/15813) the verbiage was called out by a coworker

![image.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/ba2ea42f-f752-47ff-8476-a8522fb26d0c)

**Comment by mlighdc** [comment]
@Dene-human I think some of Jonathan's tickets got lost in the transition. I am going to add you as assignee. Not sure why these were not transfer over to you to start looking at.

**Comment by Dene-human** [comment]
I'm not sure. I haven't done a full indexing of the EZ error messages in their entirety

**Comment by hdjustice** [comment]
Closing this ticket, plan to do a complete content review of the 10-10EZ
