### ISSUE TITLE
[FE] Mirror the new NameTag of the Dashboard onto the Profile

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#19436]
## Background
We added the updated name tag to myVA2, and we now need to also show this updated name tag on the Profile when the feature flag for myVA2 is turned on.

## Tasks
- [ ] Add updated name tag to the Profile
- [ ] Ensure mobile styling is correct on both my VA and the Profile.

**Comment by mshea0606** [comment]
Looks good @sanlouise !
