### ISSUE TITLE
UI update | Font style & padding changes

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19432]
## Acceptance Criteria

1. Global change: Increase the size of Bitter Bold type styles from 24/30 to 26/32
2. On the Direct Deposit overview screen, update the footer copy to the Mobile Body font style
3. On the Direct Deposit overview screen, reduce the padding between the elements at the bottom of the screen* by half from marginBetween: 20px to 10px
     - *These elements begin with the Footer text, and end with the 711 number

## Mockups / Reference points
**1.** 
![Screen Shot 2021-02-02 at 6.01.17 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/3cb6c6b4-3a0c-4883-859a-ebe6e1557f75)

**2. & 3.**
![Screen Shot 2021-02-02 at 6.10.00 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/1ede0771-8d6b-47d0-a78d-aaf9817a61a0)

**Comment by digitalken** [comment]
PASS 2/11/2021 - Looks good from my observation on the devices.  Closing.
