### ISSUE TITLE
Make all checkbox lists use a checkbox group

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#19438]
## Technical Task

During a [Peer Review](https://github.com/department-of-veterans-affairs/vets-website/pull/15813) it was called out that when you have a list of checkbox its better for 508 accessibility to have them grouped by a fieldset. In order to accomplish this in the form system we need to wrap the checkboxes in a checkbox group.

## Expected Behavior

All checkbox lists are wrapped in a fieldset to accommodate 508 accessibility 

## Acceptance Criteria

- [ ] All checkbox list on the HCA are wrapped in a fieldset

## Additional context
![image.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/ef8f5d5f-a926-4b2a-8ac0-7e58c5065726)

**Comment by dat-gcio** [comment]
@ala-yna @LinnJS Closing this one out. Turns out that the checkboxes are wrapped in just one <fieldset>. Spoke to Rob about it and it turns out that it only nest additional ones when we add validation, but that's a separate issue on the platform side.
