### ISSUE TITLE
Design: Update content to reflect phone number used in footer 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#19446]
## User Story

_As a user who needs help filling out the online the 10-10CG, I want to understand what offline support is available to me
so that I can successfully submit my application._

## Expected Behavior

_Add expected behavior of the described feature here_

## Acceptance Criteria

- [x] _Update design to approved content_

- [x] _Attach to front end ticket_

**Current footer**

![Screen Shot 2021-02-03 at 9.34.55 AM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/f92f5129-ecc8-474e-a017-628efdd283d9)

**Desired designs**

![Screen Shot 2021-02-03 at 9.40.56 AM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/6a3e1225-10a9-457f-b09a-1e42d290fa9d)

**Comment by jonathanjnelson** [comment]
Designs were updated: https://preview.uxpin.com/d894e30b16689e39e29c852774f95d6e05a7adc8#/pages/137285242

**Comment by mlighdc** [comment]
@Dene-human can you please figure what is the status of this? Seems like a simple update if it is not done already.

**Comment by Dene-human** [comment]
Frontend ticket created #[25542](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/25542)
