### ISSUE TITLE
Determine Caregiver team needs for dropped PDF errors

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#19447]
Describe what occurs in these cases:
- User submits application
- Submission successfully entered into CARMA
- PDF attachment is not successfully entered into CARMA
- Error message is shown to user

A/C:
- [x] Create writeup of the issue for Caregiver Program @kevinmirc 
  - https://dsva.slack.com/archives/CMJ2V70UV/p1612377961098100?thread_ts=1612369597.096400&cid=CMJ2V70UV

  > We are seeing instances of “timeout errors” when applicants submit the form.
Typically, when a user submits their form, the data gets sent from va.gov to CARMA, and CARMA will reply with an acknowledgment that it was received.
Recently, we’ve seeing an increasing number of submissions where the data is passed to CARMA, but CARMA does not respond with an acknowledgment. In these cases, va.gov will wait 60 seconds for a response, and when a response it not received, it considers the submission a failure and renders an error message to the user (saying that the submission was not successful). When looking into these errors, we discover that in almost all cases, the data did successfully reach CARMA, and a case was successfully created.
The most important to note in these cases it that (1) the user received an error message when submitting, (2) the PDF will not be attached to the CARMA case, and (3) there may be a duplicate submissions (if the user applied again after seeing the error message).
We’ve seen 122 occurrences of this error (as of Feb 3, 2020 1:12pm EST), almost all of which happened in January. With the help of the CARMA team, we’ve gathered the CD-Numbers for some of these cases.
Up to this point, we’ve ruled out the possibility of this error being and application bug, and it is more likely an issue on the networking connection between the two systems. The platform team of va.gov has been notified of this issue. The CARMA team is reviewing logs to gather more information.

- [x] Does Caregiver team need CD number list of applications with dropped PDF files?
- [ ] If so, how often?
- [ ] Create followup tickets for batches if needed

**Comment by ala-yna** [comment]
We determined that we're going to provide an update every week. Here is the ticket for this week's batch:
https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/19563
