### ISSUE TITLE
Determine next steps to address network connection failures between CARMA & VA.gov

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#19440]
Given the results of the Platform team investigation (here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19503)
Let's understand and document the next steps
To address the period connection failure between CARMA & VA.gov

A/C
- [ ] Evaluate research findings from Platform
- [ ] Create tickets for tasks in our team 
- [ ] Create tickets for tasks outside our team that need escalation

**Slack Threads**:
- 01/29/21 - https://dsva.slack.com/archives/CBU0KDSB1/p1611938061012300
- 02/02/21 - https://dsva.slack.com/archives/CBU0KDSB1/p1612289646168600

**Comment by kevinmirc** [comment]
Consider extending timeout on fwdproxy as part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/19609 based on Platform's response: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19503#issuecomment-776140178

**Comment by kevinmirc** [comment]
Closing since the Platform ticket to research the issue was closed: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19503#issuecomment-775454609
