### ISSUE TITLE
Send the CSV of broken links to Slack

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#1945]
## Task
Send the CSV of broken links in a Slack notification from Jenkins.

## Acceptance Criteria
- [ ] That CSV is sent
- [ ] The notification goes to #cms-general

**Comment by cvalarida** [comment]
According to [this](https://jenkins.io/doc/pipeline/steps/slack/), we should have a `slackUploadFile` command, but I tried that and the error output was that the function didn't exist.

**Comment by cvalarida** [comment]
**Update:** Looks like in order to use `slackUploadFile`, we have to be running in `botUser` mode ([source](https://plugins.jenkins.io/slack)). I found how to do that, but when testing the connection in `botUser` mode, it resulted in a failure: 
![image](https://user-images.githubusercontent.com/12970166/66607895-0f769080-eb6a-11e9-8343-e8d4e6ab0a64.png)

According to the documentation,
>You need to provide the Bot User OAuth Access Token credential as the integration token credentials to use this feature.

This might be the problem, but I'm not sure how to debug it further.

**Comment by meganhkelley** [comment]
@cvalarida is this ticket still needed or should we close?

**Comment by meganhkelley** [comment]
Bill: this is still needed. 

Moving to backlog.

**Comment by meganhkelley** [comment]
@jefflbrauer is this something your team still needs us to do?

**Comment by acrollet** [comment]
This is no longer relevant.

**Comment by mchelen-gov** [comment]
resolved by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5050
