### ISSUE TITLE
Generic Error State - Formatting and accessibility issues

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#19459]
## What happened?
1. There is too much padding space between the bottom of the page header and the top of the mobile alert.  Should be 20px.

2. Android w/TalkBack enabled:

- "The VA mobile app isn't working right now".  "VA" is pronounced "Vaw".  Want to hear "V" "A".
- The telephone link: 800-698-2411, select 0.  The "select 0" is pronounced "select minus zero".

## Specs:
- Device: Android Samsung Galaxy Note 9
- I used user vets.gov.user+277@gmail.com

## Steps to Reproduce
1. View page with either phone platform.

2. Using vets.gov.user+277@gmail.com, I visited his military information page to generate the error.  Read the page with TalkBack enabled.

## Desired behavior
1. Padding matches designs.

2. "VA" is pronounced "V" "A", not "Vaw".  
"Select 0" does not announce an invisible "minus" between "Select" and "Zero".

## Acceptance Criteria
See above.

## Bug Severity
- 4 - Low

## Linked Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18229

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/a73693f9-2a1a-4a33-b07e-e803227ca710)

**Comment by digitalken** [comment]
Fail - 2/17/2021 - Formatting is good.  "Select minus zero" is fixed, but the phone number is announced strangely.
800-698-2411 is said with talkback as "8 billion, 6 million 9 hundred 82 thousand 4 hundred eleven."
There is a phone number on the Contact VA screen (reached from the Home screen) and it has a phone number that you can use for a model.  (I've got another bug I'm going to write on that page for the header pronouncing "vaw"...)

@DF-ClaytonMatulich - See what is going on here and duplicate it!  Sending this back to "in progress."

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/f7603095-1601-436b-ad63-e34b65d5b7ba)

**Comment by DF-ClaytonMatulich** [comment]
@digitalken The phone number issue is duplicated in this ticket https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19789. A PR for that , which will be in soon, will fix this.

**Comment by digitalken** [comment]
PASS 2/22/2021 - As noted, my failure was a dupe.  Closing.
