### ISSUE TITLE
Define the information used for appointments generated from Add to calendar links

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#19468]
# Request
The ICS file that's created for the add to calendar link for appointments has fields chosen by developers, and might not be the best way of presenting appointment data. It would be nice to have a design for what data we use for each type of appointment:

- In person VA appointments
- ATLAS video appointments
- At home video appointments
- VA device video appointments
- Community care appointments
- VA location video appointments

The data we currently set in the calendar event are:

- Summary (title)
   - Generally this is the small title at the top of the appointment card
- Description
   - This is typically either video instructions or booking notes for in person appointments
- Start date and end date
- Location
   - Generally the address of the VA or CC facility. Empty for video appointments, "Phone call" for phone appointments

Other fields could be used from the [iCalendar](https://en.wikipedia.org/wiki/ICalendar) spec.

---

## Current examples
![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/4aa8cde0-8d12-4a15-bc86-cad0b41c5e79)

---
Suggested changes for content review are in the ICS column here: https://docs.google.com/spreadsheets/d/17iq2C8Ghz11Hy5n57DcMslA7yMYlccUNrRYfdu5bfew/edit?ts=60368245#gid=0

**Comment by jbalboni** [comment]
FYI @outerpress @laurenernest something to look at once the ticket to fix the current add to calendar events is fixed.

**Comment by outerpress** [comment]
Do we have documentation that lists the data we display for each confirmed appointment type? Something where I could reference the name for our data fields and and map them to the appropriate iCalendar field would be helpful.

Otherwise I can base it on this:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md

**Comment by laurenernest** [comment]
No other data list documentation that I'm aware of.

**Comment by outerpress** [comment]
Any risks of exposing PHI if we show them in personal calendar events? I'm wondering if we can/should show their reason for visit or (eventually, when we have the data) type of care to help clarify what the appt is for. @laurenernest @jbalboni

**Comment by outerpress** [comment]
I captured calendar language in the [ICS column in this spreadsheet](https://docs.google.com/spreadsheets/d/17iq2C8Ghz11Hy5n57DcMslA7yMYlccUNrRYfdu5bfew/edit?ts=60368245#gid=0)

A couple of notes:
* The HTML isn't meant to show what the final state should be, I'm just using it to show layout (line breaks, links, etc.)
* I'm assuming we can link directly to the appointment's detail page from a calendar event created by one of these

@peggygannon fyi, this'll need a content review - we'll run through it at our next sync

**Comment by laurenernest** [comment]
To your earlier question- there could be PHI concerns but we can ask.

**Comment by peggygannon** [comment]
Hi, @outerpress Here are content recommendations for the ICS fields. Please let me know if you have any questions about the recommendations. Thx! 

[VAOS ICS fields.content review.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6321201/VAOS.ICS.fields.content.review.xlsx)

**Comment by laurenernest** [comment]
Two dev tickets created: #23606 and #23607

**Comment by outerpress** [comment]
Dev is complete, closing
