### ISSUE TITLE
Add Latency metrics to DataDog External Service SLO report

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#19472]
## Description

With the draft External service SLO report being built out in DataDog, only availability has been added.  We need to include an additional metric that shows latency for each service, mimicking what is presented in the current report

## AC
- [ ] Latency metric is available for each service on the draft report (using any available data)

**Comment by LindseySaari** [comment]
[Suggested solutions documented here](https://vfs.atlassian.net/wiki/spaces/VI/pages/1077412038/DataDog+Latency)

**Comment by jeff2d2** [comment]
@jhouse-solvd I believe that we are blocked by an ops issue on this. Do you know which issue that is so I can link them?

**Comment by jhouse-solvd** [comment]
This issue is #21465, which I've also linked as a blocker to this issue.

**Comment by jhouse-solvd** [comment]
Closing. (Please see #42065 or #13677 for details)
