### ISSUE TITLE
File Upload Doc Type

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#19470]
## Background
For applicable workflows that require a file uploaded, we need to establish what that file is.

## Considerations
- 10 => "`UNKNOWN`" should be included
- As of right now, the file uploader is optional, which is nice for testing
- Ask the question, and if the are not sure, automatically pass "`UNKNOWN`"
- To be passed from the FE to BE as `DocType`
- Here is an [example](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16362)

## Tasks
- [x] Establish the list of docytypes for files that are to be uploaded by the Veteran

## Acceptance Criteria
- [x] A list of potential docs types has been shared with both BE and FE in a mockup

**Next Steps:**
Ticket to implement on FE
Ticket to consume on BE

**Comment by sporeboy** [comment]
Here is a list of relevant doc codes I found:

Document Codes for 686c/674

Add Spouse Uploader

- 10 => "UNKNOWN",
- 14 => "Affidavit",
- 61 => "Marriage Certificate / License",
- 119 => "VA 21-4171 Supporting Statement Regarding Marriage",

Add Child Uploader

- 10 => "UNKNOWN",
- 13 => "Adoption Decree",
- 25 => "Birth Certificate",
- 58 => "Medical Treatment Record - Government Facility",
- 59 => "Medical Treatment Record - Non-Government Facility",
- 663 => "Medical Opinion",
-

**Comment by sporeboy** [comment]
The upload dropdown placement for Add Spouse is here: https://xd.adobe.com/view/e185627d-0f83-4762-747d-d646b4557713-97b4/screen/d6460303-5b1a-4889-8aaf-44868c14429a/

The upload dropdown placement for Add Child is here: https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/f3a518de-ab91-4103-bddb-e7004a7425c3/

**Comment by sporeboy** [comment]
The select list contents will need to be re-written to plain language standards then mapped to the corresponding code.

An issue that comes up is selecting a single doc code for multiple uploads. This need to be resolved.
