### ISSUE TITLE
Form validation prevents you from going "back" in a multi-page form

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#19473]
Sometimes form validation prevents you from going "back" in a multi-page form.

To reproduce:
1. Start working on any benefit application
2. Move past the first page
3. Set focus on any required field
4. Then click the `back` button

![validate-error](https://user-images.githubusercontent.com/20728956/91746273-35859480-eb71-11ea-9df0-601a208ded1e.gif)

This also affects places where we are using `SchemaForm` outside of the form system, such as updating contact info in the Profile:

1. open an empty field to edit it
2. focus a required a field
3. then cancel to exit edit mode

You get a validation error and the form does not close:

![close.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/7ce46255-331f-402e-8891-4db987fc8433)

This issue is due to the form system's `liveValidate` feature (a prop on the `Form` component from `@department-of-veterans-affairs/react-jsonschema-form`), which validates the form whenever data changes. Specifically, each form input has an `onBlur` handler that triggers validation. When a user clicks the `BACK` or `CANCEL` button, the first thing that happens is the previously focused form input's `onBlur` handler fires. This triggers form validation. And that form validation somehow* short circuits the user's click on the `BACK` or `CANCEL` button. _The button's click handler is never fired_.

This issue was originally documented in https://github.com/department-of-veterans-affairs/va.gov-team/issues/9765.

And [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/14220) was submitted to fix it, but isn't an ideal solution and was never merged.

**Comment by erikphansen** [comment]
@cvalarida @bkjohnson Mentioning you so your team can file this appropriately.

**Comment by taylorkaren** [comment]
Forms Library Team Ticket: https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/formulate/87.

**Comment by micahchiang** [comment]
@k80bowman - feel free to close this ticket out, as the [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/20048) @bjmccotter7192 recently merged fixes this issue.

**Comment by k80bowman** [comment]
Great, thank you!
