### ISSUE TITLE
Project Kickoff [VAOS - VAOS for Distribution]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19486]
## Steps to complete Project Kickoff
- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all relevant artifacts to the ticket
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/vaos-for-distribution-initiative.md)
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation
- [Prototype](https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/443560117_Home)

## Meeting attendees from **requesting team**
- Product Manager (required): **Lauren Ernest**
- DEPO Product Lead (required): **Lauren Alexanderson**
- Entire VFS team (recommended): **Peter Russo, Jeff Balboni, Kam Karshenas**
- Other specialists: **Peggy, Trevor, Mikki**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** NO

## Scheduling
- 2/8 3:30pm ET
- 2/9 3:30pm ET

**Comment by shiragoodman** [comment]
hey @laurenernest. Below are our recommended Collab Points for VAOS for (vaccine) Distribution:

- Usability Testing Prep (we should be able to accommodate an asynch review).
- IA Request
- Analytics Request
- Contact Center Review
- Staging Review
- Privacy & Security Review
 
The Platform Collaboration Point Tracker is updated. This initiative falls under the "New" tab.

Let me know if you have any questions!

**Comment by laurenernest** [comment]
Usability Test Prep ticket #19822
IA Request ticket #19821

**Comment by laurenernest** [comment]
Created a shell analytics ticket for prioritization #20129
