### ISSUE TITLE
Load Web Components in vets-website

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#19483]
## Issue Description

The Design System team will be building a Web Component library with `vets-website` in mind. In order to use the Web Components in `vets-website`, we will have to load them in a way that the browser knows what to do when it finds one on the page.

---

## Acceptance Criteria
- [ ] `vets-website` has a dependency on the WC library
- [ ] Web Components are loaded in their own webpack entry file
- [ ] Web Components successfully render in the browser

**Comment by caw310** [comment]
Dependency on a11y review.
