### ISSUE TITLE
Access for [Kristen McConnell]

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#19481]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Kristen McConnell
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Name of Team: Healthcare Experience
   > Role: UX Designer and Researcher 
   > Company: Ad Hoc, LLC 

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCt85kNChi9rQRYSfIlCAZKxx/8zgWnDhiAo5L/G281R+fCEscSP6YzkXKfu4UbEbZ8olskG2CGc5f9xLrc2X/UsvfybuwC/Om7aPefX2KZoWkfHNv/fjGdi/AdsgTPvYHHOMoMNW4M74ep2rhqh9mmrKHMRzhlMopYzzDjU+Xd+sR3teI9ooR2H29Q7CGBbTh5PZ4YaDXoXcy3CoQLu7gtvDpEtElsOJ5P6CRYIEv4Drpj1cSp1EZkDTbOFzre0skHupZruslLTCqAFrpwYU4zDRCyxFofC7uhZwX0gM9rWuKsokBYXpaT5QhArT3eQlXXnNLd6Y7hfXv4jZFoY5T4SEuuQnzebyHvjagDYPx/GPaKAW4C/6gpuIUpb2Cl3YqRemLbrPP/n8miVgh99ykd2I9MC6XC3L2G9ASwuAt2fvztuMG52u7ZF4wKP2R0hIYDiq7dlGyuqYopVEI1BUPPr1bsQ/BZelSXWQl+hmKePhf5aDcMbJbRF7fVFTTouqk= kristenmcconnell@KristensMacBook.hsd1.pa.comcast.net
```

- [Grant AWS Console access?] No
  > YES / NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by kristenmcconnell** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by mleclerc00** [comment]
@kristenmcconnell, we have successfully added you to socks so you should have access now.  When you get the opportunity, give it a go and let me know if you have any other issues.

Thanks!

**Comment by mleclerc00** [comment]
@kristenmcconnell just checking in to make sure everything is working as expected
