### ISSUE TITLE
General Analytics Request for [VAOS - data backfill]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19488]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
- Who is this request for?
  - Lauren Ernest

- What team/project is this work for?
  - VAOS
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
- As far back as possible to present

## Analytics to Track Down
- Number of users on the VAOS app homepage (/health-care/schedule-view-va-appointments/appointments/)

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
https://va-gov.domo.com/page/1315231862 "Number of Veterans who log in / access VAOS"

## Additional Comments
- This is the GA equivalent I think (I hope) it's supposed to represent- https://analytics.google.com/analytics/web/template?uid=W_utzG6JTdeRU777VhHfdw
- The data stops at Nov 2020. Can we get a current view?

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
Thanks @laurenernest.  We'll get to this as as soon as possible.

**Comment by bsmartin-ep** [comment]
Look OK @laurenernest?

https://va-gov.domo.com/page/1315231862

**Comment by laurenernest** [comment]
@bsmartin-ep Yes! Thank you!
