### ISSUE TITLE
[Cheetah MVP] Screener page error state

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19487]
## Description
On the Screener page, a user must select yes or no to continue down one of the paths.
Add error state is user tries to continue without a selection.

---

## Acceptance Criteria

- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] Given user is on Screener page, When clicks Continue without making a yes/no selection, Then show error

- [ ] DESIGN - Designs match the specs https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9/a/YGGRmxe#Inspector
![Screen Shot 2021-02-05 at 1.27.59 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/cd61afe5-00d9-4adc-8f24-5a312badfe55)

**Comment by jbalboni** [comment]
@laurenernest We can close this ticket, this validation state is built into the form library we use, just by marking the field as required.

**Comment by laurenernest** [comment]
Closing. Not needed per comment above.
