### ISSUE TITLE
STEM AD: Begin limited rollout for new functionality.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19494]
As a developer, I need to remove the prod flag for the entitlement warning in the 10203 form so that the updated UI is available in all environments.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of 2021-03-22.
2. STEM Introduction Page for AC2: https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction

## Acceptance Criteria
1. The prod flag created in #18861 is removed and the functionality implemented in that story is available in production.
2. On the introduction page, the sentence:
    > If your application isn't approved, you’ll get a denial letter in the mail.

    is replaced with

    > If your application isn't approved, you'll get a denial letter in the mail or a claim status notification by email.

3. The 'stem_automated_decision' feature flag is enabled for the limited rollout starting at 20%.

## Supporting Artifacts:
1. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md#5-decision)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16493

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2021-03-24 at 10.42.02 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/43b821b6-ed87-4484-a1c1-ddc1b5a0ea9a)

---

![Screen Shot 2021-03-24 at 10.41.35 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f0392925-fd4a-4caf-a7c4-b3915ac9da3f)

**Comment by delli-gatti-michael** [comment]
Changes are now live. Closing this issue

**Comment by delli-gatti-michael** [comment]
Changes are live and the feature flag is enabled for 20%. Closing this issue
