### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by RachaelMR** [department-of-veterans-affairs/va.gov-team#19490]
# Request Google Analytics and/or Domo access

## User Email Address
rachael.roueche@va.gov or rachael.roueche.va@gmail.com

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [ ] Domo

## Date Required
whenever

## Product Team / External Team / VA Office
OCTO-DE, Platform Crew Lead

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Current vagov email is an alt for a gmail account and cannot be used.

I DM'd Rachel the procedure to disconnect this alt and create a full Google account.

**Comment by RachaelMR** [comment]
@bsmartin-ep thanks Brian! Just removed, let me know if that unblocks you. Thanks!

**Comment by jonwehausen** [comment]
Hi @RachaelMR , 

Per your prior confirmation of disassociating your va.gov email, you should now be able to create a Google Account with your VA.gov email per our standard access provisioning process. 

Rachel, when you have a moment, please [complete this sign up form](https://accounts.google.com/signup/v2/webcreateaccount?flowName=GlifWebSignIn&flowEntry=SignUp) with your `rachael.roueche@va.gov` email address. The blue text in the middle should say "Create a new gmail address instead" at the time of clicking "Next" (_screenshot example below_)

![image](https://user-images.githubusercontent.com/48527022/108381001-64ea9500-71d5-11eb-8cc2-c2db82293ced.png)

**Once this is complete, let us know and we can provision your GA access quickly from there**

Thanks for your time here.

**Comment by RachaelMR** [comment]
Thanks Jon, done! Should I expect a link sent to my inbox about my analytics access? Thank you!

Rachael

**Comment by jonwehausen** [comment]
Great thanks @RachaelMR! Yes, you should have now received an email to your inbox indicating your Google Analytics access to your Rachael.Roueche@va.gov email.

We will close this GH issue but please feel free to reopen should you have any further access-relates questions/concerns. 

Thanks again and have a great day.

**Comment by rroueche** [comment]
Yay thank you @jonwehausen !
