### ISSUE TITLE
Resolve two accessibility issues with design system components

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#19492]
Resolve accessibility issues with the below two design components --

1. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/357
1. https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/366

**Comment by ddzz** [comment]
PR to fix these issues: https://github.com/department-of-veterans-affairs/component-library/pull/28

**Comment by ddzz** [comment]
PR to add the fix to `vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/16006

**Comment by pjhill** [comment]
Looks good -- PR merged
