### ISSUE TITLE
Write VSP documentation standards to set expectations during oboarding

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#195]
## Story
As a new VSP Product Team member, I'm not sure where to document our work and the conventions I should be adhering to when writing my apps documentation.

## Goal
Make it very very clear to new Product Team members where they should be capturing their product's documentation and the standards their documentation must meet to get approval to launch services on VA.gov.

## AC
- [x] Documentation has been created that lays out the IA/organization of the `va.gov-team` documentation
- [x] Documentation has been created that outlines the standards and expectations new documentation must meet 
   - how to title your files
   - how to create links
   - how to structure your product folder
   - how to write commits
   - how to write a product outline
- [ ] The documentation created in this ticket is incorporated into the onboarding process to be shared with new VFS Product teams

## Def of Done
- [ ] AC is complete
- [x] Connected to an epic

**Comment by rtluu** [comment]
# Documentation Best Practices at Va.gov

Documentation is an integral part of working on the VA Platform. This document is a guide containing standards and best practices for how documentation is written and maintained as well as the expectations for new documentation creation and organization.

[More to add soon]

**Comment by smoonpeyes** [comment]
@rtluu I think this is a great start. I like the idea of always linking to the ReadMe.

**Comment by emilywaggoner** [comment]
Yeah this is awesome @rtluu. A few that I would like to add:

- **Write descriptive, readable titles for your documents**: Avoid naming your documents by date or number. Instead, give documents titles that are logical and readable by humans. Separate the words with dashes. It's okay if they get a little long! For example: [tools-for-getting-started-with-the-us-forms-system.md](https://github.com/usds/us-forms-system/blob/master/docs/getting-started/tools-for-getting-started-with-the-us-forms-system.md)
- **Fix errors you find**: Maintaining healthy documentation requires everyone to pitch in. If you find a broken link, or any other type of error, do what you can to fix it yourself or track down someone who can help.

[I know that last one is similar to the one about fixing out-of-date things, but I think it's worth calling out the same directive for errors too.]

**Comment by emilywaggoner** [comment]
Created the document here: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Onboarding/product-development-documentation-best-practices.md

Need to validate with a PM on the item that instructs how to structure a product folder. @minafarzad would you mind taking a look when you have a moment?

**Comment by andreahewitt-odd** [comment]
@minafarzad Can you take a look at the request above?

**Comment by mnorthuis** [comment]
Moving this task under the current va.gov-team repo structure work.  As part of this work we should publish best practices and guidelines around using the repo.   The work done above will be a start to that work.

**Comment by mnorthuis** [comment]
Will review this work to incorporate as needed into the repo guidelines created.

**Comment by mnorthuis** [comment]
@meganhkelley @thatmattjohnson this is an old ticket, I think we can confirm we've covered all of the thoughts here in documentation and close this.

**Comment by meganhkelley** [comment]
@mnorthuis agree that this can be closed. The doc discussed here is now at: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/product-development-documentation-best-practices.md

I read through the doc and it's all still in line with our current strategy. we still need to improve our documentation ~onboarding~ orientation and include this info there, but that should be tackled as part of our documentation standards setting initiative, tracked separately.
