### ISSUE TITLE
CLP Refinement Punch List - FE Build 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#19500]
## Issue Description
_Some refinement is needed post PR for Campaign Landing Page, punch list listed below for FE work effort.  Also plan to capture any internal bugs or needed fixes from our team walk through this afternoon via this ticket_

## CLP UAT Refinement Task List 
- [x] The short bright-blue border-bottom that accents a couple titles appears to have different lengths/widths. I think it has a relationship with the title above it.
- [x] Make sure the calendar event works when someone clicks the "add to calendar" link. I notice a runtime error about a missing description.
- [x] Change all layouts to consolidate all of the CMS-preview elements to the top of the page
- [x] Get the YouTube video working (does the content model include the "embed" link? we also need to adjust the width/height of the iframe because it doesn't do that automatically like an image)

Items from team walkthrough (Capture Here)
- [x] Validate Hero Image Resolution is set appropriately. **FOLLOW HERE: https://dsva.slack.com/archives/C01DS1XDEQ0/p1613075910016200**
- [x] Log into ebenefits needs arrow icon at the end (Validate design specs - ask Ryan) **FOLLOW HERE: https://dsva.slack.com/archives/C01DS1XDEQ0/p1613072241009900**
- [x] Downloadable Resources - calls out for 'other languages' but doesn't have build-in on CMS to add or show on FE element.  _(Action Item - follow up with CMS)_ **FOLLOW HERE: https://dsva.slack.com/archives/C01DS1XDEQ0/p1613072382011100**
- [x] Events - Need to understand if something is virtual (zoom link) or other sources, how is that going to be displayed? (Should get the exact events from the event calendar.  FE needs to see exact data source example (Zoom link for example). **FOLLOW HERE: https://dsva.slack.com/archives/C01DS1XDEQ0/p1613075462013300**
- [x] Check margins on Mobile/Table some areas need adjusted for view.
- [x] Dynamic (blue, white) staggering background needs to be applied.  Do we want this into a separate ticket? 
- [x] Follow up, on https://github.com/department-of-veterans-affairs/va.gov-team/issues/16749

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
Add to calendar link works for me:

![image](https://user-images.githubusercontent.com/12773166/107547845-2593c700-6b8b-11eb-96ea-a3dc4f7d7980.png)

What was wrong with it? No runtime errors when I click on it too

**Comment by ncksllvn** [comment]
there was a runtime error in the JS console about the meta description missing. presumably we added the meta description and now that runtime error doesn't occur anymore.

**Comment by kelsonic** [comment]
Makes sense! Thank you! 🙂

**Comment by brianalloyd** [comment]
Validated, closing in support.
