### ISSUE TITLE
[Product] Audit homepage refresh states

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19501]
- [ ] Audit appointment cards old vs new (captured in tickets)

- [ ] Write up any missing tickets

Current homepage appointment cards https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md

**Comment by outerpress** [comment]
@ldelacosta @JRRoof y'all can close this one, this is from the first time we redesigned the list
