### ISSUE TITLE
Missing `mailto:` prefixes in hardened VAMC health services  content

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#19509]
## Issue Description
After cutting over to the hardened health services content, we discovered broken link errors caused by missing `mailto:` prefixes on the service location email addresses

![image](https://user-images.githubusercontent.com/55411834/106944384-bda13480-66e3-11eb-9f3b-55c829629b31.png)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/15944

**Comment by mpelzsherman** [comment]
Evidence:

![VA_Pittsburgh_Health_Care___Pittsburgh_VA_Medical_Center-University_Dr](https://user-images.githubusercontent.com/80267/107253085-f69f1900-6a03-11eb-8ef6-809ab8fd4267.png)
