### ISSUE TITLE
Access for Glen Stevenson

### ISSUE THREAD

**Issue by gstevenson-va** [department-of-veterans-affairs/va.gov-team#1950]
# Instructions
1. Socks access
2. VSA
3. @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Glen Stevenson
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA, DevOps Engineer, GovernmentCIO
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

  > ssh-rsa 
  >  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHYerbzwcRrb1BdJuUmpq47DDOYT4D/N70UEXelALj5ZK96+tz8uhyW6659DFDi+8NGxJpbhNiX2KQisFOYiGi8cqBxIyx4xNy2uB8BLAqNirLIlacJPZEgzLySEVS5jze6qQiT9nbx5HWrQm5HyWJjoKbnmS1kQXxV3pGXqQcCsuJblDF9bk2B59nx83WwPegpmCD90qJmDyr6jWfA8u/PGWwlsjSILVFaS1zfRcHG9kJVFHcH8LC+G5KShQakDCrEQjl4i4TQalYgvxxm384r6hl8L1uUf8cH02okt6FJYm7Eva0bTffdlGepJPvZ7TtBJrOiiNLkIV6qIZGlekt glenstevenson@USRMonitors-MBP

- [Grant AWS Console access?]
  > YES 
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Glen Stevenson

**Comment by gstevenson-va** [comment]
I forgot to add that yes, I need AWS console access.

**Comment by ricetj** [comment]
> I forgot to add that yes, I need AWS console access.

Updated 🎉

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS.

**Comment by Jeff-Hayter** [comment]
@jbritt1 @ricetj Approved for AWS.
