### ISSUE TITLE
CT: Add country name to free text search

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19516]
As a Comparison Tool user, I need to be able to search by country name, so I can find schools in a foreign country where I can use my benefits.

## Assumptions:
1. This work is completed behind the `gibct_state_search` feature flag (#18312).
2. This search is for the full country name and does not include the country abbreviation.
2. Search by country name will have a higher weight, but will continue to include search results by name, city, and alias that are similar to the country name

## Acceptance Criteria:
For the non VETTEC search: 
1. Search by country name returns all institutions within that country.

For the VETTEC search:
2. Search by country name returns all institutions within that country.

## Supporting Artifacts:
1. Google Analytics fo Foreign Country Searches: [CT-Search-CityCountrySearch-20210203.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5934905/CT-Search-CityCountrySearch-20210203.docx)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/785

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1375&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.

**Comment by dneel-bah** [comment]
@sonntag-adam Staging deploy failed, this needs to be retested in staging once a successful deployment occurs.

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by desireeturner** [comment]
This feature only allows for searching country name in English.
