### ISSUE TITLE
UX/UI when user cannot access Military Information

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19521]
## Acceptance Criteria
1. Implement the UX/UI indicated in the linked designs when a user navigates to the 'Military information' page
     - Copy is hard-coded
2. When there is not a military branch seal, left-justify the user's name
     - Name is 20px from left edge
3. Display this screen when either occur:
     - 'Military service' is false (i.e. not an authorized service)
     - A call is made to the endpoint and returns a null state (i.e. authorized, but no data is returned)

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/446769839
![Screen Shot 2021-03-22 at 3.45.55 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f28705fd-a4ab-4b4b-aed6-ec64e5eac0dc)

## Accessibility Implementation Guidelines

- Mark "We can't access your military information" as Header 2

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bridgethapner** [comment]
I'm working through this in #20017 - charting "unhappy paths". Question for ya @bessgreen - is this story for being unauthorized for Claims & Appeals only or more features?

**Comment by bessgreen** [comment]
@bridgethapner I originally created the ticket as a catch-all for all the areas where we were seeing unexpected error states and blank screens - I figured as we defined the requirements further, I'd create new FE tickets to pass on to the dev team. 

All that said, feel free to use this ticket and/or break it out however you need! Totally flexible on that front.

**Comment by bridgethapner** [comment]
@bessgreen Thank you so much! 

I think I'm getting somewhere on access issues for Appointments (and health care in general) and Claims  -- I don't know if being unauthorized for Letters is something we anticipate running into after resolving some of the sign-in data inconsistency issues. @lexicalninja do you know?

**Comment by lexicalninja** [comment]
It could happen if they have never used anything or have no current history, so there should at least be an off-ramp for this.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/2/2021 - Looks good overall on iOS and Android.  Logged small bug on missing final period in paragraph and accessibility - not hearing header 2 text marked as header.  Closing.

Linked bug:

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22589
