### ISSUE TITLE
Create test case data for test users 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#19534]
In order to QA FSR, test users need to have the following data scenarios created: 

1-Veteran does not have any VA benefits to prefill the FSR form 
2-Veteran has VA benefits to prefill the FSR form 
3-Veteran has one debt
4-Veteran has multiple debts 

Definition of done: Create data and tie to test users. Provide test users to @tlei123 with attached scenario

**Comment by camerontesterman** [comment]
CC: @tlei123

**1-Veteran does not have any VA benefits to prefill the FSR form**
vets.gov.user+1@gmail.com

**2-Veteran has VA benefits to prefill the FSR form**
vets.gov.user+228@gmail.com

**3-Veteran has one debt**
vets.gov.user+14@gmail.com

**4-Veteran has multiple debts**
vets.gov.user+1@gmail.com

**Comment by tlei123** [comment]
@camerontesterman , I found some use-case anomalies on Staging and help your help addressing them please:

- **1 - No benefits to prefill** [test-acct-1 (Greg)]:
  This actually has benefits prefilled.  We need no benefits at all please.
  ![fsr-testacct1-debts-prefilled](https://user-images.githubusercontent.com/587583/109843646-881b3880-7c08-11eb-8670-4ee628ace89b.png)
- **2 - has benefits prefilled** [test-acct 228 (Colder)]:
  While this does have benefits prefilled as spec'ed, it does not have any debts prefilled.  I thought this was not a valid use-case.  We need one debt please.
  ![fsr-testacct228-no-debts-prefilled](https://user-images.githubusercontent.com/587583/109844384-4ccd3980-7c09-11eb-8b8d-aef7262cbb60.png)
- **3 - Has 1 debt** [test-acct-14 (Jerry)]:
  Like w/ above Use-case 2, this actually has no debts.  We need one debt please.
  ![fsr-testacct14-no-debts](https://user-images.githubusercontent.com/587583/109846248-36c07880-7c0b-11eb-9bc7-4d3a4557985f.png)

cc @leahkeeler

**Comment by leahkeeler** [comment]
@camerontesterman - Can we mock up the data for this?

**Comment by camerontesterman** [comment]
@tlei123 I have a question on user 1 - 4, once I know the requirements for these two users I can find some users that meet the criteria.

1-Veteran does not have any VA benefits to prefill the FSR form **(debts needed yes/no?)**
2-Veteran has VA benefits to prefill the FSR form **and at least one valid debt**
3-Veteran has one debt **and at least one valid debt**
4-Veteran has multiple debts **(debts needed yes/no?)**

**Comment by camerontesterman** [comment]
> @camerontesterman - Can we mock up the data for this?

Partially. Since this is in staging it is using BGS data that isn't mocked, however the DMC data is mocked.

**Comment by tlei123** [comment]
> @tlei123 I have a question on user 1 - 4, once I know the requirements for these two users I can find some users that meet the criteria.
> 
> 1-Veteran does not have any VA benefits to prefill the FSR form **(debts needed yes/no?)**
> 2-Veteran has VA benefits to prefill the FSR form **and at least one valid debt**
> 3-Veteran has one debt **(benefits yes/no?)**
> 4-Veteran has multiple debts **(debts needed yes/no?)**

1 - **Yes, but no need to add debts** -- I'm already seeing two debts for test-acct 1.  Just need existing benefits deleted.
2 - **Yes, need one debt added** please for test-acct 228.
3 - **Yes, but no need to add benefits** -- I'm already seeing two benefits for test-acct 14.  **Just need 1 debt added**.
4 - [same as for #1 (you provided the same test-acct 1)].  @leahkeeler , unless you have any objections, I'll be combining this and #1 (same provided test-acct) into a single TestRail test-case.

**Comment by camerontesterman** [comment]
@tlei123 

Ok - for case 1 you should now use Frank Arnold (vets.gov.user+5@gmail.com) this user has a debt, but no benefits.

I added debts for cases 2 and 3, those users will be the same (228 and 14)

The changes for these cases will go into effect with the next deployment of vets-api in staging.

**Comment by tlei123** [comment]
@camerontesterman , thx!  Just one case left to double-check on Staging and fix if needed...

1 - Veteran does not have any VA benefits to prefill (and has a debt) [test-acct 5 (Frank)]:
  This is actually showing no debts and benefits are showing prefilled right now.  Need one debt added, and all Benefits deleted please.

Cases 2-4 are now fixed on Staging.

If a fix is indeed needed, please tag me here when done.  Thx much!

**Comment by camerontesterman** [comment]
I've updated user 42 and added one debt. This user does not currently have benefits showing in staging, so it should meet the requirements for case 1.
