### ISSUE TITLE
Analytics Implementation | Anchor Tags | C&L

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#19547]
# Google Analytics Implementation or QA Request

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

This is a request for GA implementation

- Who is this request for?

    - Sharon Kasimow
    - Jennifer Lee
    - Danielle Thierry

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
  
What team/project is this work for?
   
- This work is for Public Websites and being done by the C + L team 
    
Provide the Domain where Google Analytics needs to be implemented:

- www.va.gov    

- No PII will be passed

Please provide any upcoming deadlines or important milestones
    
    - late April '21

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
URL: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/     

    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
- Event tracking for clicks on the `new question text anchor link UX affordance` (anchor link is copied)
- Aggregate click rate %age on the new UX link affordance based on sessions in a 30 day period.
- Number of links shared per UV session, daily, weekly, monthly
- Source tracking to identify UVs/PVs entering the page from clicking a link  received
- Errors (fail to copy)

-Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A 

- Certain conditions/responses that need to be reviewed

    - [When a SENDER-user clicks on the new UX affordance, the question anchor link URL is copied to their clipboard.]
    - Determine baseline average click rate of page engagement links, so we can accurately determine if the engagement rate with the new UX affordance is in line with baseline or not. (I.e., success or not success). 
                  - 1.5%

- Additional Comments

    - [ Question - can we tell how the link was shared (ie: gmail vs twitter vs Facebook) - when a RECIEVING-user clicks on the shared link and comes to the question on the page? ]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by SKasimow** [comment]
@jenniferlee-dsva Hi Jen - here's a draft ticket for analytics we'll want to implements/items to track. Please review and lmk if you have any additions/changes. Thanks!  Sharon

**Comment by jenniferlee-dsva** [comment]
Hi @SKasimow - take a look at above tweaks. I defined how we want to see click rate - as aggregate %age rather than raw # of clicks - on the new UX feature. Also, because we're only providing copy functionality on the new UX - I don't think we can determine HOW that copied link is shared just by a user clicking on that affordance. 

But, possibly - ? - GA might be able to track via INCOMING page visits where the user was referred from (gmail, Facebook?) via our question anchor link?  So I clarified that as a question for the analytics team under Additional Comments section.

**Comment by SKasimow** [comment]
Hi @jenniferlee-dsva - yes like how you defined click rate; that's good!

Yes, hopefully analytics can see the referrer source.

Thanks for reviewing!

**Comment by SKasimow** [comment]
@joanneesteban Hi Joanne - can we get someone to take a look at this soon  as I *think* we will need a new analytic event for a user clicking the new "copy" icon we will be adding to the Coronavirus FAQ page.


cc: @jenniferlee-dsva

**Comment by SKasimow** [comment]
Per Slack convo, we want to be able to use record-event to:

1. Track when a user clicks on the share icon
2. Track when users land on the page using the deep anchor link (i.e., traffic to this deep linked content).


https://dsva.slack.com/archives/CBU0KDSB1/p1617913025139200

**Comment by youngfreezyVA** [comment]
#1 is complete, #2 i need to implement, wasn't aware of that req until now. I guess what we could do is on page load, if there is an id hash in the url, send that to recordEvent.

**Comment by SKasimow** [comment]
@youngfreezyVA it was part of the slack convo I embedded above. You can check with Brian to confirm that ^ works if you aren't sure :)

**Comment by jonwehausen** [comment]
Hi @SKasimow  & @youngfreezyVA,

First I want to apologize for the delay here -- this request somehow didn't make it's way onto our tracking board upon creation so we apologize there. 

For solutioning this tracking -- we would like to propose a `recordEvent` be hard coded within `vets-website` where the landing page shifts or is loaded to the anchor link page position. Please use this specification below: 

```javascript
  event: 'anchor-page-load', 
 'anchor-text': //text from the anchor link URL following "#"
```

This way we aren't reliant directly on the # within the page URL and can keep our page tracking within Google Analytics clean and tidy. 

For explicit jumplink click scenarios (_where the user intentionally clicks on a jump link and skips down to that section of the page_), we will continue to track those as `nav-jumplink-click`

### Questions
- @youngfreezyVA Could you provide an example of a working anchor link today? We will need one for testing purposes anyhow

**Comment by SKasimow** [comment]
Adding @jenniferlee-dsva ^

**Comment by youngfreezyVA** [comment]
Great, this is all I needed, thanks for answering the engineering ask.
> ```js
>   event: 'anchor-page-load', 
>  'anchor-text': //text from the anchor link URL following "#"
> ```

**Comment by jonwehausen** [comment]
Thank you @youngfreezyVA! I have reopened this issue on our side for QA purposes. 

Would you have a working example of an anchor link URL today?

**Comment by jonwehausen** [comment]
### QA Testing

| Description of Interaction | Data Layer Screenshot | Test Status | Test Notes
| -- | -- | -- | -- | 
Loading a page (auto jumping to section of page) with a anchor link URL -- `https://staging.va.gov/coronavirus-veteran-frequently-asked-questions-esp/#pruebas-de-covid-19-en-va` | ![image](https://user-images.githubusercontent.com/48527022/116290745-d01a8f80-a761-11eb-83dd-96dd5e02372e.png) | ✔️ **PASS** | @youngfreezyVA this is perfect, thank you for this
Clicking of jumplink to jump to section ![image](https://user-images.githubusercontent.com/48527022/116290978-0fe17700-a762-11eb-9bad-6aca69d826af.png) | N/A | ⚠️ **DOES NOT PASS** | @youngfreezyVA Apologies I know this event was there prior, but we will want to push a `nav-jumplink-click` event on each of the language pages for explicitly when a jumplink is clicked

@youngfreezyVA In order to maintain consistency here, for the jumplink event could you also include the anchor text as metadata here: 

```javascript
event: 'nav-jumplink-click', 
'anchor-text': //anchor text without the "#"

```

**Comment by youngfreezyVA** [comment]
that's not the right jumplink :) please see the video on the PR

**Comment by jonwehausen** [comment]
Okay, apologies there @youngfreezyVA -- appreciate the video!

To be sure we're on the same page: 
- The following specification should be used for the jumplinks at the top 
```javascript
  event: 'nav-jumplink-click', 
  'anchor-text': //anchor text without the "#"
```
- Apologies again for not providing sooner...If wanting to take a step further and track the chain icon clicks (copy), please use the following specification: 
```javascript
 event: 'int-copy-to-clipboard-click', 
'anchor-text': //anchor text copied without the #
```

**Comment by youngfreezyVA** [comment]
no worries. I think using the term jump link has confused a few folks. there is no navigation interaction for this feature, so i think all we need is the second event above.

**Comment by jonwehausen** [comment]
@bsmartin-ep Could you please QA this [GTM workspace](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000507)?

### Context of Changes 
- Added in `allowAnchor` `true` to in fields to set base config to universally collect UTM parameters when anchors are used
- Created new tag for anchor page load, instead of using custom dimension passing into event action
- Set Non-Interaction to `True` on the page load scenario
- Added to the Interaction lookup table for the `int-copy-to-clipboard-click` when the anchor copy icon is clicked

**Comment by bsmartin-ep** [comment]
### QA

Interaction|dataLayer|GTM tagging|Pass?
---|---|---|---
Load [page with anchor](https://staging.va.gov/coronavirus-veteran-frequently-asked-questions-esp/#pruebas-de-covid-19-en-va).|![image](https://user-images.githubusercontent.com/62304138/116488827-5d90d900-a861-11eb-9e04-46fda360d59d.png)|![image](https://user-images.githubusercontent.com/62304138/116488843-68e40480-a861-11eb-8f6a-a61c34699dbb.png)|✔️ **PASS**
Click shareable-link button|![image](https://user-images.githubusercontent.com/62304138/116488911-9761df80-a861-11eb-893f-9ec74282d695.png)|![image](https://user-images.githubusercontent.com/62304138/116488931-a183de00-a861-11eb-901d-289193c6acfd.png)|✔️ **PASS**
Click anchor / jumplink URL|![image](https://user-images.githubusercontent.com/62304138/116489047-f45d9580-a861-11eb-8766-fbb8dfc294f6.png)|???|<p>@jonwehausen - I think I was (mistakenly) under the impression that any link with a `#` was logging an event   or PV, but t[hat doesn't appear to be the case](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000507/triggers/735). </p><p>Do we want a `nav-jumplink-click` here or no need to track this?</p>

**Comment by bsmartin-ep** [comment]
@youngfreezyVA -

re: `nav-jumplink-click`

You _shouldn't_ need to have the inline onclick recordEvents if you're using _addJumplinkListeners_....

```js
PAGE_EVENT_LISTENERS.set(
  '/coronavirus-veteran-frequently-asked-questions-esp/',
  [addJumplinkListeners, addQaSectionListeners],
);
```

I'm also seeing a CSP error originating from the inline click...

![image](https://user-images.githubusercontent.com/62304138/116563084-b435fb80-a8d1-11eb-8ac4-be6915e1f6c4.png)

**Comment by youngfreezyVA** [comment]
@bsmartin-ep if you look at the git history you'll see i added that code in dude

**Comment by youngfreezyVA** [comment]
again... there is no nav jump link click in this feature. while its great to be in the weeds, i'd suggest coming up for some air, and understanding the actual requirements

**Comment by bsmartin-ep** [comment]
I am aware you are the one who added the event handler @youngfreezyVA.  Just noting that...

1. There are analytics events on the page that are in the code and not working.
2. A CSP error is occurring that may be related.

**Comment by youngfreezyVA** [comment]
1. those analytics events are not needed for this feature, are you QA'ing the page or this feature?
2. that is a completely unrelated error.

**Comment by bsmartin-ep** [comment]
@SKasimow - our GTM changes have been published.  You should shortly see the new events in our non-prod GA property...

[Link to GA event report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20210429&_u.date01=20210429&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22~2Fcoronavirus-veteran-frequently-asked-questions-esp%22,0%5D%5D)

**Comment by SKasimow** [comment]
@jonwehausen @bsmartin-ep @youngfreezyVA Hi all - I'm not following all of ^ but if we are not in synch on the analytics tracking, think next best step would be to set up a short call and review live.

Let me know if we still need alignment and can set this up :)

+  @jenniferlee-dsva

**Comment by bsmartin-ep** [comment]
@SKasimow - this implementation looks good.   We found a CSP error that is affecting certain tracking on staging and production.  We'll open a separate ticket to deal with that.

Thanks!

Closing...

**Comment by SKasimow** [comment]
Many thanks @bsmartin-ep @jonwehausen for your support!

+ @jenniferlee-dsva
