### ISSUE TITLE
[Ongoing Service] Incident response. 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#1954]
## User Story and Problem Statement
As a member of VSP and VFS, I want to see incidents responded to and addressed in a timely manner, so that the site can continue to a reliable place for Veterans to access their benefits.

### High Level User Story/ies
These tasks are for ensuring we address issues in a timely manner and any follow-up work to prevent further incidents in the future. 
 
## Measuring Success (KRs/KPIs)
- [VSP KR] Increase in customer NPS
- Percent of incidents (i.e. problems requiring a post-mortem) remediated within seven days

**Comment by jbritt1** [comment]
I think we are holistically solving this right now with the addition of the SRE team. Closing at this time, but easy enough to reopen if this were to be brought back around and prioritized or in the event anyone disagrees.
