### ISSUE TITLE
Generic Error State - No Network Connection - Accessibility Title for 'Try Again' button is incorrect

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#19541]
## What happened?
With text reader software enabled on device, the Title for the 'Try Again' button should not be "VA Button".  It should be "Try Again".

## Specs:
- Device: Both Android and iOS

## Steps to Reproduce
Generate the generic error then read the button with the screen reader software (Talkback, Voiceover).

## Desired behavior
Device reads back "Try Again".

## Acceptance Criteria
Device reads back "Try Again."

## Bug Severity
- 4 - Low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/18231

## Screen shot(s) and additional information

Try again button:

- Title= "Try again"
- accessibilityHint= “Try again to load VA Mobile app” <- Current hint of "Tries to reconnect to internet" is just fine. Ignore this line.
- accessibilityRole= “button”

**Comment by DF-ClaytonMatulich** [comment]
This bug is fixed by the PR for the refactor that added the Basic Error component. I believe that was done by @jmarchi .

**Comment by digitalken** [comment]
PASS 2/18/2021 - Sounds correct now.  Closing.
