### ISSUE TITLE
Icons don't scale with larger text size

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19555]
## What happened?
When increasing the device's text size, the blue .svg icons throughout the app do not scale with the text size; instead, they maintain their original size. 

Note for dev/QA: This ticket only applies to the blue click-to-action icons. There is a separate ticket to investigate scaling the icons for the Claims Step Table (#19559). 

## Specs:
- Device: Both Android and iOS

## Steps to Reproduce
1. In the device settings, max out the font size. 
2. Open the mobile app
3. Navigate to any page with blue .svg icons, such as:
     - Veteran Crisis Line: phone, text, chat icons
     - Upcoming appointment detail: calendar, arrow, phone icons
4. Notice how the blue icons do not scale with the text

## Desired behavior
Icons scale with text size.

## Acceptance Criteria
1. When the device font size increases, also increase the size of the blue icons, including:
     - Phone (click-to-call)
     - Text (open messaging app)
     - Chat (VCL crisis chat page)
     - Calendar (Add appt to calendar)
     - Arrow (visit VA.gov)

## Bug Severity
- 4 - Low

## Linked to Story
N/A

## Screen shot(s) and additional information
![Screen Shot 2021-02-05 at 9.27.03 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/fb4fa4e0-50e5-4b26-9db3-226bdd6fda2a)

**Comment by digitalken** [comment]
PASS 2/10/2021 - Icons scale with text size.  Closing.
