### ISSUE TITLE
Compare PDF error spreadsheet with Google Analytics

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#19551]
Look at spreadsheet of errors and compare with Google Analytics

**Comment by mlighdc** [comment]
Hey @ala-yna not sure why this assigned to me. Aren't supposed to be looking into this.

**Comment by mchelen-gov** [comment]
@mlighdc I think you had wanted to take a look at these, I'm not sure what was needed to check for though?

**Comment by mlighdc** [comment]
Thanks @mchelen. I believe the request was to have @ala-yna take a first pass at this to see how big the gap is.

**Comment by tchrisdyer** [comment]
Hi @mchelen and @mlighdc  - since I'm taking this on from Alayna, can you give me a quick summary of what I need to do here?

**Comment by mlighdc** [comment]
@tchrisdyer happy to provide the background about this. Might be easier to talk through this. This is something I requested Alayna do last October.

**Comment by tchrisdyer** [comment]
I did a comparison of the Logged submission data from Kevin’s Google Sheet vs the Google Analytics submission data. I used November 1, 2020 - March 31, 2021:

- The Total Difference between the two datasets over that time period was 2,121 (Logs > GA).
- The Average difference was around 5%

Closing this ticket.
