### ISSUE TITLE
Campaign Landing Page MVP 1.0- VSA-QA Test Plan

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#19554]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature Outline: [CLP Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/README.md)
- Product/Feature Epic: [CLP EPIC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4621)
- Product/Feature Copy deck(s): [Product Feature Deck](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/Pilot-campaign-landing-pg-DEPO-pilot-050120.pdf)
- Product/Feature Design prototypes: [CLP Mural Design](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1607363793772/b7f9e809d68ace9c8d75ab649a758ed7653c8461)
- State of Product Artifact: [CLP State of Product with use cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/state-of-product.md)

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Ryan Thrulwell 
Content/IA: Mikki Northuis
Front-end: Kelson Adams, Nick Sullivan 
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

- [Product use-cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/Collab%20Cyle%20Docs/product-use-cases.md)

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: [CLP Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/Collab%20Cyle%20Docs/product-use-cases.md)

## How to configure this issue

- [X] **Product Manager** added to Assignees
- [X] Attached to a **Milestone** (when will this be completed?)
- [X] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [X] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [x] Test Reports generated.  These should be provided to VSP at least 2 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Staging Review ticket**: #16139

**Comment by brianalloyd** [comment]
@tlei123 just checking in to see if you had any issues or questions with the provided test cases?  We're scheduled for Staging Review this Thursday and wanted to validate.  Thanks.

**Comment by tlei123** [comment]
> @tlei123 just checking in to see if you had any issues or questions with the provided test cases? We're scheduled for Staging Review this Thursday and wanted to validate. Thanks.

Hi @brianalloyd !

Yes, I have some questions:

- I have 2 links to Use Cases.  Which one is the latest?
  - [State-of-Product](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/state-of-product.md#key-artifacts) [provided above in main description], or
  - [Use-Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/Collab%20Cyle%20Docs/product-use-cases.md)
- Where is/are the pages to be QA'ed?
- What are the login credentials [if needed] to access the page(s)?
- Do my [TestRail test-cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=904) look good to you?  [I can start running them today]

**Comment by brianalloyd** [comment]
@tlei123 thanks for the follow up.  Let me see if I can answer details below:

- The Use-Cases doc should be the latest (that was inflight when we completed the ticket)

- Preview is here of a mock campaign:  http://preview-prod.vfs.va.gov/preview?nodeId=16139.  Let me know if this works, as a staging review as not been set yet and needs to be viewed from CMS preview environment. 

- Not required. 

- Yes, Test Rail cases look good, please reach out and we'll assist in any way we can.  

Appreciate the support, CCing @johnhashva.

**Comment by tlei123** [comment]
@brianalloyd , thanks much for the quick response!

Yes, the page link works; no login req'd.

No help needed; I'll start test-runs today, and update this ticket with QA-artifact links when done.  Feel free to check this tic again tmrw (Tue) morning.

cc @johnhashva

**Comment by tlei123** [comment]
Sorry, @brianalloyd @pjhill !  Test-runs still not done just yet...

Would you two happen to be able to hit the preview-page using Mac Safari?
https://preview-prod.vfs.va.gov/preview?nodeId=16139

I couldn't from my end, and I'm suspecting SOCKS-proxy.  Mac Chrome & Mac Firefox could access the page fine, albeit with known issue of long rendering time.  Before I give up on Safari, I just wanna double-check w/ you two.

I'll check back again tmrw (Tue) morning.

cc @johnhashva

**Comment by pjhill** [comment]
@tlei123 
I can't get that preview to load anywhere! I have the proxy setup and can load various internal tools such as Jenkins, but I still can't reach that preview page.

**Comment by brianalloyd** [comment]
@tlei123 I could access the link via Mac Chrome but not Safari and believe your socks-proxy hunch might be the culprit.  I can have our team review and validate today as well in support.

**Comment by tlei123** [comment]
> I can have our team review and validate today as well in support.

@brianalloyd , yes, please do.  I'll watch this tic and your team slack-channel for updates.  Thx much!

@pjhill , fwiw, for Mac Chrome & Mac Firefox, i initially had problems loading this page too, BUT it turned out for these 2 browsers that's just due to the preview environment taking real long to render -- it also seems i had to clear cookies & refresh a few times.  Only my Mac Safari threw up a "no internet" error which is why I'm suspecting it's just not seeing my SOCKS-proxy at all.

**Comment by brianalloyd** [comment]
@tlei123 our team looked into it and we're able to hit the link on all above browsers via Mac, and are wondering if it might be a SOCKS-proxy issue.  This will all be cleared up once we have a staging URL however that is still being worked as we want to ensure it's VA internal only and not releasable.  More to follow as we work issues.

**Comment by tlei123** [comment]
@brianalloyd , strangely enough, now I can't get the page to load in ANY Mac browser.

@ncksllvn , @kelsonic , any ideas?  I could load the page in Chrome & Firefox yesterday, just not Safari.  But now all 3 are crapping out.

**Comment by kelsonic** [comment]
@tlei123 The preview servers are down every week day from 3:30 - 4ish pm EST as the CMS is updating

**Comment by kelsonic** [comment]
So that was likely the cause, you should be able to access the URLs now, e.g.

http://preview-staging.vfs.va.gov/preview?nodeId=16139
http://preview-prod.vfs.va.gov/preview?nodeId=16139

**Comment by tlei123** [comment]
@kelsonic , thx!  Neither page is loading here yet, but if all *.va.gov subdomains are on AWS then maybe it's 'cuz I'm in the west region and caches here haven't refreshed.

I'll keep trying.  :)

**Comment by tlei123** [comment]
@brianalloyd , all test-runs now completed.  After retrying unsuccessfully most of the afternoon, finally got Safari to load the page after a long bout w/ System Preferences > Network > Proxies settings.

Although a few text-links' destinations didn't load, I'm confident they're not broken-links.  Same test results overall as with Chrome & Firefox.

One defect logged: #20629 [styling anomalies]

Below are the TestRail QA-artifact links [which I'll also update into our Stg Rvw ticket]:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1450)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=904)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/195)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/196)

**Comment by kelsonic** [comment]
You could try it in incognito! Maybe it's an extension you have or something that's causing the issue, very odd indeed 🤔

**Comment by brianalloyd** [comment]
@tlei123 thanks for the follow up and work on this ticket, I've got the noted defect/bug for action and appreciate all the hard work and support as usual.
