### ISSUE TITLE
Icons in Claim/Appeal step table don't scale with font size

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19559]
## What happened?
When increasing the device's text size, the icons in the Claim Step Table & Appeal Past Events table do not scale with the text size; instead, they maintain their original size. 

**Note for dev:** Investigate whether or not we can scale these icons, similarly to the blue .svg click-to-action buttons (#19555). If the existing icons cannot be scaled, we may need to request .svgs for all possible variations of these icons.

## Specs:
- Device: Both Android and iOS

## Steps to Reproduce
1. In the device settings, max out the font size. 
2. Open the mobile app
3. Navigate to either of the following pages:
     - Active Claims Detail. View the Claim Step Table.
     - Active Appeals Detail. View the Past Events Step Table. 
4. Notice how the icons in the table do not scale with the text. 

## Desired behavior
Icons scale with text size.

## Acceptance Criteria
1. When the device font size increases, also increase the size of the icons in the step table, including:
     - Past step (green check)
     - Current step # (blue filled w/ a darker border)
     - Future step # (grey filled)

## Bug Severity
- 4 - Low

## Linked to Story
N/A

## Screen shot(s) and additional information
![Screen Shot 2021-02-05 at 9.38.52 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/076dcd54-cb73-4e3b-aa97-f25f84060a33)

**Comment by digitalken** [comment]
PASS 2/10/2021 - Icons are now scaling with larger font sizes in step table.  Closing.
