### ISSUE TITLE
CT: Create desktop sticky nav custom component

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19569]
As a developer, I need to create a custom component that supports a sticky navigation bar so that when we begin development we have all of the necessary components available.

## Assumptions:
1. Use CT sandbox for testing a mock implementation of the control.
2. The display of a navbar below 951px is handled in a separate story.
3. This implementation should work with all institution types (IHL, VETTEC, etc).

## Acceptance Criteria:
1. A "sticky" navigation bar with jump links custom component exists with the following behavior:
    a. The nav bar is sticky once it hits the top of the viewport.
    b. The nav bar style is displayed down to resolutions of 951px wide.
    c. A jump link for each section on the profile page (ex. Estimate your benefits, Institution details, etc)
    d. Clicking a jump link takes the user to that section of the page with the nav bar at the top of the view port and the start of the section below the nav bar.

## Supporting Artifacts:
1. ![Screen Shot 2021-02-10 at 11 12 10 AM](https://user-images.githubusercontent.com/1094999/107537450-de103980-6b90-11eb-9a62-ce7188f0d3b5.png)

2. [Invision Prototype stuck](https://bahdigital.invisionapp.com/d/main#/console/14222462/296055841/preview)
3. [Invision Prototype unstuck](https://bahdigital.invisionapp.com/d/main#/console/14222462/296055832/preview)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16003

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by JenLJ** [comment]
Foremost - this looks really good, just a few tweaks based on a UX discussion!

1.  UX talked this morning and we would like the grey navigation bar to be the same width as the VA header/footer. 

![Screen Shot 2021-02-24 at 9 46 25 AM](https://user-images.githubusercontent.com/36964225/109018054-c2735b80-7685-11eb-86b8-00728f4c1a03.png)

2. When the grey bar transitions to sticky, there is a very small shifting of the links to the left (just a few pixels).  Can we modify this so the text position is consistent regardless of whether the grey bar is static or sticky?


3. Question:  When using the jumplinks, the sections typically appear directly underneath the sticky header. The exception to this is the topmost link (Estimate Your Benefits).  Is there a reason why this jumps to a slightly higher position than the other links?
![Screen Shot 2021-02-24 at 9 51 36 AM](https://user-images.githubusercontent.com/36964225/109018246-f0f13680-7685-11eb-8a1e-cb7c534502ec.png)
![Screen Shot 2021-02-24 at 9 51 47 AM](https://user-images.githubusercontent.com/36964225/109018252-f189cd00-7685-11eb-99b0-f6b8e854893d.png)

**Comment by amyknox** [comment]
No additional comments.  2/2
