### ISSUE TITLE
CT: Create custom search component

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19566]
As a developer, I need to create a custom search component that supports the redesigned CT search functionality so that when we begin implementation of the full redesign we have all of the necessary components available.

## Assumptions:
1. Use CT sandbox for testing using a mock implementation of the nested controls.
2. The tabs (search schools, employers, VET TEC) are a separate component / handled in a separate story

## Acceptance Criteria:
1. The component contains:
    a. A free text search for the name of the school.
    b. A free text search for the location of the school.
    c. A distance dropdown
    d. The current "Your benefits" components (SA2 - benefits form & online classes filter) in a collapsible drop-down like menu
    e. A school preferences collapsible drop-down like menu
    f. A degrees and majors drop-down like menu

2. The distance dropdown options are:
    a. 10 miles
    b. 25 miles
    c. 50 miles

3. The school preferences collapsible menu contains:
    a. An "Institution type" input
    b. A level of institution input
    c. Warning and closings input

4. The degrees and majors menu contains:
    a. A Level of degree input
    b. A free text major search input

5. The level of degree input options are:
    a. All
    b. Bachelor's
    c. Associate
    d. Master's
    e. Doctoral

6. The institution type input options are:
    a. Flight
    b. For Profit
    c. Private
    d. Public

## Supporting Artifacts:
1. [Invision Prototype](https://bahdigital.invisionapp.com/d/main#/projects/prototypes/14222462)
2.  
<img width="253" alt="Screen Shot 2021-02-12 at 8 23 27 AM" src="https://user-images.githubusercontent.com/48260534/107773417-a11c8200-6d0b-11eb-9f7c-c45f71a6c785.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16162

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by watersemma** [comment]
UX 1/2: Looks go to me!

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me!

**Comment by amyknox** [comment]
UX Review 3/2: This needs to work on PC, too. 

![image](https://user-images.githubusercontent.com/41081945/109330678-f12a3700-7829-11eb-94df-003e28220420.png)

![image](https://user-images.githubusercontent.com/41081945/109330696-f5565480-7829-11eb-95ee-5e411b4cc19b.png)

Typo
![image](https://user-images.githubusercontent.com/41081945/109330718-fab39f00-7829-11eb-8f9b-10ac17ecf1fd.png)

Possibly a data issue but AC says Institution Type dropdown should be title case.  Same issue with Degree / Majors, Level of Degree dropdown
![image](https://user-images.githubusercontent.com/41081945/109330778-0ef79c00-782a-11eb-8317-ddd2d8ad9de1.png)

**Comment by dmccurdybah** [comment]
Label update PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16202
