### ISSUE TITLE
Discovery: generating a pID and/or BIRLS ID for service members applying for disability claims

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1957]
@djmunoz1 commented on [Tue Sep 18 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13357)

FROM GDIT: There are edge cases for 526 where user is not found in Corp or BIRLS, eBen handles this by adding the record in corpDB or BIRLS id (often same as ssn) before starting 526. This means there will be a much higher possibility of users not having a participant record (pID) in Corp. 

AC
-[ ] We need to work with the Griffins team to outline the scope of work involved to add a user's pID or BIRLS number if one does not exist and lay that out for implementation no later than PI11.

There has already been some preliminary discussion so if we can hand over this effort to Griffins entirely and they already have it in the queue, can we document that here to make sure we are tracking progress?

Other notes: 

We need to think about the identity aspect of this and include id.me in the conversation to document how instances of veterans without a participant ID handled? MVI will have to be part of this conversation because correlation of IDs happens in conjunction with that group. 

In eBen, when a user is logging in and is not in Corp DB or BIRLS VA file number they can log in. eBen also uses IAM for security

---

@djmunoz1 commented on [Tue Sep 18 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13357#issuecomment-422602932)

sequence of events as we understand them today:

users log in and call is made to MVI --> if EVSS service criteria met (pid, birls id, edipi) user is found and granted access

for BDD in eBen:

users log in and call is made to MVI --> EVSS service access denied if pID or BIRLS id is missing (this is NOT necessarily every service member --> EVSS creates and adds the missing data into birls (for birls id) or corpDB (for pID) --> MVI call is successful

---

@davidsbao commented on [Wed Sep 26 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13357#issuecomment-424744944)

Notes from Griffins:
- Issue #13117 is tracking the use of MVI.Orchestration upon login/completion of identity proofing. Essentially, instead of only searching against MVI's primary view, we will conduct a fallback search to DMDC to attempt to identify the user. If they are found in DMDC, they will be added to MVI for future use.
- For 526 (and any other similar tool), the tool should be able to check the user's state for the following:
    - Is the user logged in? If not, they must login in order to continue
    - Is the user identity proofed? If not, they must complete identity proofing in order to continue
    - Is the user in MVI? If not, they must be blocked
    - Is the user in MVI, but not in CORP/BIRLS? If so, they must be added to CORP in order to continue
        - Note that if we are not already making their CORP ID available in the user call, Griffins will need to make this improvement
    - Is the user in MVI and in CORP/BIRLS? If so, they may continue
- Some things to consider during the remainder of discovery:
    - What is the exact user flow in eBenefits? How, if at all, is a user notified that they are being added to CORP?
    - We will likely want to model some of the user behavior around the handling for health tools in VA.gov (#10863), happy to talk through those details

---

@aeltarhoni commented on [Tue Sep 17 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13357#issuecomment-532320435)

@YanaRoy will address

**Comment by luke-gcio** [comment]
Closing - Original Claims was the solution to this.
