### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#19576]
# Request Google Analytics and/or Domo access

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

mike.lumetta@adhocteam.us
william.kim@adhocteam.us
giles.wells@oddball.io
eddie.otero@oddball.io
charley.stran@oddball.io
Sophia.Tareen@adhocteam.us
pam.lougheed@adhocteam.us
lauryl@adhocteam.us

## Access Requirements
Please check the analytics tools you need access to:
- [X] Google Analytics
- [ ] Domo
_Please list any additional requirements, if any._

## Date Required
_Please share the date you require access._

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._
VA Lighthouse APis

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
GA access has been granted for these users.  They should have all received an email with more information.

Our primary properties are:

- VA.gov - Production
- VA.gov - Non-Production Environments

Let me know if you have any questions.
