### ISSUE TITLE
GIDS: Retrieve new data via Scorecard API fetch

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19571]
As a developer, I need to update the Scorecard API fetch so that data needed for the redesign is available when we begin development of the new functionality.

## Assumptions:
1. No prod/feature flag is required for this story.
2. Data check warnings / errors are not included as part of this story.

## Acceptance Criteria:
1. The following data can be retrieved by GIDS using the scorecard API:
	a. Unitid
	b. Opeid6
	c. Control
	d. Main
	e. Cipcode
	f. Cipdesc
	g. Credlev
	h. creddesc
2. The data retrieved as part of AC1 can be exported from GIDS to a CSV.

## Supporting Artifacts:
1. https://collegescorecard.ed.gov/data/documentation/

**Comment by elder-joseph** [comment]
Associated PRs:

Full PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/791
DB Specific PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/790

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-02-26 at 1.46.09 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e4ea376e-5749-43b1-98bc-f429c54afdbf)
##
![Screen Shot 2021-02-26 at 1.46.18 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ba3c44d6-6eb3-4721-966d-dc10397c4280)

**Comment by sonntag-adam** [comment]
Testing passes QA
