### ISSUE TITLE
ATO - PagerDuty Documentation

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#19578]
## Description
Faith has been asked by Dror to provide any document that states the description and how we are using PagerDuty on the platform. 

## Background/context/resources
https://dsva.slack.com/archives/G01CWAJEVC2/p1612384581008300

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@troymosher - Though this is an old request, it may still be relevant. 

Do you have the required PagerDuty documentation for the purposes of ATO?

**Comment by troymosher** [comment]
Slack link is no longer available.  I would say this can be closed as the issue is stale.  If a future need arises for more detailed PagerDuty documentation we will create a new issue as needed.
