### ISSUE TITLE
GIDS: Add ability to upload CIP codes

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19572]
As a developer, I need to be able to upload the CIP codes into GIDS, so that data can be used to display new information as part of the CT redesign.

## Assumptions:
1. No prod/feature flag is required for this story.
2. Data warnings / errors are not included in this story.

## Acceptance Criteria:
1. A CIP code CSV with the following columns is a GIDS accepted file format for upload:
	a. CIPFamily: string
	b. CIPCode: string
	c. Action: string
	d. TextChange: bool
	e. CIPTitle: string
	f. CIPDefinition: string
	g. CrossReferences: string
	h. Examples: string
2. The CIP code CSV is able to be exported from GIDS.

## Supporting Artifacts:
1. [CIPCode2010.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/5934968/CIPCode2010.csv.zip)

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/787

DB Migration PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/788

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/tests/view/64656)

**Comment by delli-gatti-michael** [comment]
The above file is now uploaded to Staging. Closing this issue
