### ISSUE TITLE
Common component: Input field

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19584]
**Note for dev**: this ticket only applies to the input fields. There is a separate ticket for the dropdown fields (#19585).

## Acceptance Criteria
1. Create common component for the text input field
2. UI details:
     - Border: 1px solid gray #5B616B
     - Background: white
     - Text: Mobile Body
     - Helper text (optional): Source Sans Pro, Regular ~14/18px,~ 16/22px #323A45
3. When there is a required label:
     - Red secondary dark, #CD2026
4. UI when field is in focus:
     - Border: 2px solid, #003E73
5. UI when there is an error:
     - Border: 2px solid red secondary dark, #CD2026
     - Background: white
     - Label text: Mobile Body Bold
     - Error text: Mobile Body Bold, #CD2026
6. Add specs to ReadMe

## Designs / Mockups
**Source of truth for specs:** https://adhoc.invisionapp.com/d/main#/console/21114574/445194525/preview?scrollOffset=538.888916015625

Original discovery ticket, for reference:
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f31356438313362652d396532652d343463652d613131352d643533633831363763666363 (1).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4273f893-4aa2-4cc1-8d26-2213cfa82d31)

## Discovery ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17031

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Sending this ticket back to In Progress to update font size for helper text.

**Comment by digitalken** [comment]
PASS 3/12/2021 - Looks good on iOS and Android.  Closing.
