### ISSUE TITLE
Update dropdown field common component

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19585]
**Note for dev**: this ticket only applies to the dropdown fields. There is a separate ticket for the text input fields (#19584).

## Acceptance Criteria
1. Update specs for the dropdown field common component
2. UI details:
     - Border: 1px solid gray #5B616B
     - Background: white
     - Text: Mobile Body
     - Helper text (optional): Source Sans Pro, ~14/18px,~ 16/22px, #323A45
     - Dropdown icon: fa-sort in #323A45 
3. When there is a required label:
     - Red secondary dark, #CD2026
4. UI when field is in focus:
     - Border: 2px solid, #003E73
5. UI when there is an error:
     - Border: 2px solid red secondary dark, #CD2026
     - Background: white
     - Label text: Mobile Body Bold
     - Error text: Mobile Body Bold, #CD2026
6. Add specs to ReadMe

## Designs / Mockups
**Source of truth for specs:** https://adhoc.invisionapp.com/d/main#/console/21114574/445194525/preview?scrollOffset=538.888916015625

Original discovery ticket, for reference:
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564386535326636316335336664303030313733633564652f31356438313362652d396532652d343463652d613131352d643533633831363763666363.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/3ed8970e-5584-4e07-bc57-fbf10c9a02cd)

## Discovery ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17031

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Sending this ticket back to In Progress to update font size for helper text.

**Comment by digitalken** [comment]
Pass 3/12/2021 - Good overall, minor bug logged on Android where the drop down error does not disappear when a valid entry is chosen by the user.  Bug tracked, so closing story.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21482
