### ISSUE TITLE
UI updates for Edit Email

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19582]
## User story
As a user, I want a page to edit my email address that indicates which fields are mandatory. 

**Note for dev**: This ticket does not include field-level errors OR deleting an email address.

## Acceptance Criteria
Make the following updates to the UX/UI on the Edit Email page:

1. Email field
     - Display Input Field CC
     - Mark as "Required"

## Designs
**N/A. Similar design for Edit Phone:** 
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432057842
 **Source of truth for form-field specs:** 
https://adhoc.invisionapp.com/d/main#/console/21114574/445194525/preview?scrollOffset=538.888916015625

## Accessibility Implementation Guidelines
**Inactive state(empty):**
Formfield: “{label}, empty."
Formfield/Message: “{label, Hint message}, empty. "
Dropdown: “{label}, empty."
Dropdown/Message “{label, Hint message}, empty. "

**Focused state(editing):**
Formfield: “{label}. Editing - {Input text}. "
Formfield/Message:“{label, hint message}. Editing - {Input text}. "
Dropdown: “{label}. Editing - {Input text}."
Dropdown/Message “{label, hint message}. Editing - {Input text}. "

**Activated state:**
Formfield: “{label}. Filled - {Input text}. ”
Formfield/Message:“{label, hint message}. Filled - {Input text}. ”
Dropdown:“{label}. Filled - {Input text}. ”
Dropdown/Message “{label,hint message}. Filled - {Input text}. ”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/22/2021 - Looks good on iOS and Android.  Existing bug on iOS for editing fields while VoiceOver is activated.  Closing.
