### ISSUE TITLE
Common component: Radio buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19597]
## Acceptance Criteria
1. Create common component for the radio button, which has 2 states: unselected, selected
2. UI details for unselected state:
     - Border: solid, #757575, 1px; position: inside
     - Fill: solid, #FFFFFF
3. UI details for selected state: 
     - Outer border: solid, #0071BB, 2px
     - Inner border: solid, #FFFFFF, 2px
     - Fill: #0071BB
4. Add specs to ReadMe

**Note for dev:** There is a separate ticket to include a disabled state (#19684)

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/441187434
- .svgs attached below

**Comment by bessgreen** [comment]
![Radio Button - Unselected.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f4e39bf9-c8e8-4516-ae52-71ac0ac89b15)

![Radio Button - Selected.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/97d9188c-9453-44a9-bd52-7ff63c4fe37d)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - Radio buttons look good.  Closing.
