### ISSUE TITLE
write postmortem for fwdproxy deploy on 2019-09-19

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#1959]
Primary discussion in Slack during incident here: https://dsva.slack.com/archives/C30LCU8S3/p1568928128052400

Draft of document started here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/12

## AC

- [x] incident review written and reviewed
- [x] any improvement items tracked via issues and linked here

**Comment by ricetj** [comment]
@wyattwalter to create a few tickets from this PM

**Comment by wyattwalter** [comment]
Going to review at next SRE call: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/12

**Comment by ricetj** [comment]
Done
