### ISSUE TITLE
Find a VA Form [Discovery] Identify tasks needed to improve search string matching

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#19601]
#  Description

Discovery task to identify and estimate Research, Design, FE, other work required to improve the way strings are matched in the Find a VA Form Search.  See problem description in Epic - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17244

## How to Configure This Issue
List tasks and issue numbers in Epic - https://github.com/department-of-veterans-affairs/va.gov-team/issues/17244

**Comment by zacharymorel** [comment]
As seen in this table here:
![Screen Shot 2021-02-10 at 1 09 59 PM](https://user-images.githubusercontent.com/26075258/107552303-5121ac00-6ba1-11eb-8a11-d206f24a26d8.png)
Do we have aggregated data telling us of common queries that are missing a "-"?

**Comment by johnhashva** [comment]
We do -- it's in a Google doc that @MarciMcGuireGCIO has access to.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel @johnhashva is correct.  I'll send you the link.

**Comment by MarciMcGuireGCIO** [comment]
Note: 3 points for Zach + Laurel's time.

**Comment by MarciMcGuireGCIO** [comment]
@laurellawrence when you have a chance to estimate time for you to break down tasks on this, let me know and I'll add to Zach's 3. Thx!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO do you still have the data of the top queried forms that "I queried this form but what form I meant" value?

**Comment by MarciMcGuireGCIO** [comment]
Yes, I'll send on Slack.  I combined the different variations to re-rank the most popular forms.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO So, out goal here is to really hone down on when a consumer queries "1010ez", do we always want that to translate to "10-10ez*" ?

**Comment by MarciMcGuireGCIO** [comment]
I'll ask @johnhashva to also chime in, but you could do a transformation on the search term and CMS form name to do an apples to apples comparison.  That transformation would nullify spaces, special characters, the word "VA" and the word "form"  and convert lower case to upper.  Nothing would change in how we display those, but during the actual comparison, you'd be comparing the two transformed terms.   

If you think of the spaces, dashes, words "form" and "va" simply as formatting, like a phone number, it helps.

![image](https://user-images.githubusercontent.com/73354907/108883924-01e16f80-75d4-11eb-8ac0-7d22619906cc.png)

**Comment by zacharymorel** [comment]
> I'll ask @johnhashva to also chime in, but you could do a transformation on the search term and CMS form name to do an apples to apples comparison. That transformation would nullify spaces, special characters, the word "VA" and the word "form" and convert lower case to upper. Nothing would change in how we display those, but during the actual comparison, you'd be comparing the two transformed terms.
> 
> If you think of the spaces, dashes, words "form" and "va" simply as formatting, like the dashes and parentheses in a phone number, it helps.
> 
> ![image](https://user-images.githubusercontent.com/73354907/108883924-01e16f80-75d4-11eb-8ac0-7d22619906cc.png)

I came up with two possible solutions after studying the existing data/ schemas and Lighthouse API model interface.
A. Your comment is definitely a possibility. 
B. I have used an approach where a column is added called **SearchableTerm** and its a string that holds the patterns that we are looking for, so for the row(s) _10-10EZ_, _10-10EZ (esp)_, and _10-10EZR_, the value of **SearchableTerm** would be something like _10-10EZ, 1010EZ_, _10-10_,. We'd then do a wildcard matching on the **FormName** column, **Title** Column, and the **SearchableTerm** column.

**Comment by MarciMcGuireGCIO** [comment]
Awesome, @zacharymorel.  I'll defer to you as the engineer on how to best accomplish that.  It might also be worthwhile to run by some other engineers to see if they may have already implemented something similar.

**Comment by johnhashva** [comment]
This is super promising!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @johnhashva This will require a collab with Lighthouse and the CMS engineers. 

As far as dependencies go, it will require the CMS engineers to add the field on to the form node so we can fill it out the **SearchableTerm(s)** for each node. After that is done, the Lighthouse engineer team will need to update their API to reflect the new field on the VAFrom nodes from the CMS.
