### ISSUE TITLE
Extend timeout on VA.gov <--> CARMA connection

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#19609]
Research: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18555

**Description**
Extend the timeout on the connection to CARMA.

A/C:
- [x] Timeout is extended to 120 seconds (2 minutes) on vets-api
- [x] Extend the timeout of the fwd proxy if needed (see PR).
- [x] Extend timeout on front-end if needed (see PR).
- [ ] Verify that change has reduced timeout errors and if so, closeout backlog ticket.

**Comment by kevinmirc** [comment]
Blocked: Waiting to get the latest credentials for connecting my local env to CARMA, so I can test the timeout changes.

**Comment by ala-yna** [comment]
Closed - won't do. We decided to keep the current timeout of 60 seconds because we didn't want to change the reverse proxy for the rest of the platform.
