### ISSUE TITLE
Copy change: "Proof of Service Card"

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19608]
## Acceptance Criteria
1. Update the copy for the "Proof of Service Letter" to "Proof of Service Card" in order to match the va.gov web app. This change should appear on the following screens:
     - Letters list page (ListItem)
     - Proof of Service Card overview page (Header 2)
2. Ensure that any relevant accessibility labels/hints are also updated (if applicable) 

## Related ticket
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14812

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - Updated in both places.  Closing.
