### ISSUE TITLE
Create E2E test for MegaMenu

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1960]
With the MegaMenu configuration moving to the CMS, the data is now more dynamic than ever, and we should confirm its safety before deploying any changes. The most standard way for us to do that is via an E2E test. This will allow us to confirm that the MegaMenu is still working as expected before each deployment.

**Comment by ncksllvn** [comment]
Adding `cms` label, because this work is warranted based on work in that realm.

**Comment by Karak888** [comment]
This was handled by CMS - @nick to look for PR
