### ISSUE TITLE
508-defect-1 ❗ Launchblocker [SCREENREADER]: An equivalent alternative MUST be provided for the image of the check

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#19611]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Josh_

## User Story or Problem Statement

As a blind user, I expect alternative instructions to finding my bank account numbers that don't rely on visual characteristics alone. As a mobile user, I expect to be able to read instructions to finding my bank account numbers.

## Details

[The current alt text on the image of the check fails to meet WCAG 2.0 1.3.3 Sensory Characteristics](https://www.w3.org/WAI/WCAG21/Techniques/failures/F14.html) because the instructions rely on location _(e.g. bottom left edge)_. [It also fails to meet WCAG 2.0 1.1 Text Alternatives](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content), as non-text content MUST have a text alternative that serves an equivalent purpose. In this case, for a blind user, there may be more suited instructions to finding their bank account numbers as opposed to a physical printed check.

For mobile users, this is also frustrating as the image will not scale well on a smaller device. Instructions may be barely legible due to the use of a rectangular .png image more suited for desktop use.

## Acceptance Criteria

- [ ] An alternative, text-based method of providing instructions with equivalent purpose is provided

## Environment

* Smaller mobile devices e.g. iPhone 5
* Any screen reader

## Steps to Recreate

1. Enter `https://staging.va.gov/profile/direct-deposit` in browser
2. Begin editing one of the accounts
3. Expand "Where can I find these numbers"
4. Inspect the image of the check using your choice of devtools
5. Confirm alt text relies on vision
6. View the page on a mobile device view, preferably iPhone 5/SE
7. Confirm text on image is barely legible

## Proposed Solution

A simple, low effort fix for both mobile and screen reader users would be to simply provide an instructional list of multiple methods to find bank account numbers.

For example, the image could have a blank alt attribute `alt=""` with instructions directly below:

```html
<img src="/img/direct-deposit-check-guide.png" alt="">
<ul>
    <li>From the bottom left edge of your check and in left to right order you can find your: routing number, account number, and check number</li>
    <li>Log in to your bank account online and view your account's details. The routing number and account number should be provided there.</li>
    <li>Contact us at help@help.com</li>
</ul>
```
Copy here should not be used, just referenced as an example. @peggygannon would your 💯  talent be able to help with this? 🙇 

### Before
<img width="1247" alt="Screen Shot 2021-02-08 at 11 23 45 AM" src="https://user-images.githubusercontent.com/14154792/107274601-9cf81800-6a1e-11eb-855e-b47c35e75949.png">
<img width="768" alt="Screen Shot 2021-02-08 at 3 19 03 PM" src="https://user-images.githubusercontent.com/14154792/107276518-23155e00-6a21-11eb-8dd8-73f21575a425.png">

### After
<img width="738" alt="Screen Shot 2021-02-08 at 3 29 31 PM" src="https://user-images.githubusercontent.com/14154792/107277844-ffebae00-6a22-11eb-89f4-a06a9ee28ee3.png">

**Comment by peggygannon** [comment]
thanks, @joshkimux will take a look and suggest copy updates.

**Comment by peggygannon** [comment]
@sporeboy @joshkimux Question: will we still show the image of the check, or will these set of instructions replace the image.?  If we're replacing, then I might tweak the first line a bit. 

{add'l component} Where can I find these numbers? 

The bank routing number is the first 9 digits on the bottom left corner of a  printed check.  Your account number is the second set of numbers on the bottom of a check,  just to the right of the bank routing number.
If you don’t have a printed check, you can:  
-	Sign in to your online bank account and check your account details or a bank statement, **or**
-	Call your bank

**Comment by joshkimux** [comment]
@peggygannon We'll still show the image of the check, but the set of instructions provides an alternative to blind users and mobile users. It should be ok if you reference the visual check in the content provided there's other options ( like signing in / calling a bank :D ) that provides alternatives to other users.

That being said, I think ideally the content shouldn't have to reference the image of the check as it may be frustrating for mobile users if instructions ask them to reference an image that's really squished.

**Comment by peggygannon** [comment]
@joshkimux thanks for the clarification! Please let me know if the content suggestions above ^^ will work. 

cc @sporeboy

**Comment by joshkimux** [comment]
@peggygannon I think the content suggestion above is 💯 , thank you for the speedy suggestion 🙏 
@sporeboy would love your thoughts too.

**Comment by mshea0606** [comment]
@sporeboy to include peggy's content above

**Comment by sporeboy** [comment]
Opting not to show explanatory text for screenreader. 

```
<img src="dd-check-img.svg" alt="where to find the routing number and account number" aria-describedby="check-description">
<p class="show-or-hide" id="check-description">The first set of numbers on the bottom-left of your check is the bank's routing number. The set of numbers in the middle is your account number. The number at the far right is the check number. We don't need the check number.</p>
```

**Comment by sporeboy** [comment]
@peggygannon @joshkimux We're looking at a relatively low-impact solution for the image description. The code above uses alt-text for a general description, and an "invisible" description referenced using aria-describedby.

Understanding Josh'd win-win scenario above, I prefer hidden text for the screen reader to reduce the visual overload.

Peggy, I used your copy as a starting-point and I made a few edits to make it read in-line. Please let me know if you have further suggestions. Thanks all!

**Comment by mshea0606** [comment]
@1Copenut will validate this ticket since @joshkimux is out on PTO.

**Comment by peggygannon** [comment]
Thanks, @sporeboy So I want to confirm that code in your comment above is the "invisible" description referenced using aria-describedby?

Here are some recommended content tweaks to the last line. I recommend adding an *or* between the options to distinguish that these are three different options:

If you don't have a paper check, review your bank statement or check your account details online or call your bank.

**Comment by joshkimux** [comment]
> @peggygannon @joshkimux We're looking at a relatively low-impact solution for the image description. The code above uses alt-text for a general description, and an "invisible" description referenced using aria-describedby.
> 
> Understanding Josh'd win-win scenario above, I prefer hidden text for the screen reader to reduce the visual overload.
> 
> Peggy, I used your copy as a starting-point and I made a few edits to make it read in-line. Please let me know if you have further suggestions. Thanks all!

@sporeboy quick question to clarify, are you intending for the check:
1. to always be visible _outside_ of the show/hide "Where can I find these numbers?" That way it can then reference the `p` _within_ the show/hide that you've written up? 
2. Or do you intend for the `p` to be hidden to all sighted users like the `sr-only` class?

Depending on what the intent is, the implications/consequences would be very different 🙇 

Do let me know if you'd be free to hop on a call sometime to talk about it this week as I just got back from PTO! 😄 
@peggygannon would love to have you on as well 🙇

**Comment by sporeboy** [comment]
@joshkimux Welcome back!

The check/SVG is initially hidden within the, "Where can I find these numbers?" accordion. The explanatory caption would be hidden to sighted users. Couldn't recall what the screen reader-only class was, so I had a placeholder "show-hide" class. Probably created confusion there.

**Comment by joshkimux** [comment]
@sporeboy Thank you! ✨ 

Ahhh, gotcha! Thank you for the additional context, I understand what you mean now! 🙇 

I agree with you that reducing the amount of content could reduce the cognitive load on the page for sighted users on desktop. However, it may not provide an equivalent experience for:

- mobile users, who may struggle to see a smaller image within a box (particularly since it's rectangular), text is typically easier to read in this case
- those on slower bandwidth connections, who may opt out of viewing images at all
- some instances of users with cognitive disabilities, who may prefer written instructions over an image
- and sighted users who may not have a checkbook on hand (I think the content on accessing a bank account online which @peggygannon wrote up and you further simplified would do the trick provided its visible)

For those reasons, I still think it would be valuable to keep the hint text visible to everyone-- particularly the bit on accessing a bank account online vs. just a checkbook (I personally have went on for a _long_ time without ordering a checkbook from my bank 😆 ).

Since this is already within a show/hide container, I don't think it adds on too much extra weight to the page. Using bullets as well, as opposed to a paragraph, will make it easier to process too.

Let me know your thoughts. I'm more than happy to explain the above in more detail too 🙇

**Comment by erikphansen** [comment]
@joshkimux just to confirm the path forward:

1. Replace the PNG of the check with the new SVG of the check
2. Add Peggy's text below the check image:

---
The bank routing number is the first 9 digits on the bottom left corner of a printed check. Your account number is the second set of numbers on the bottom of a check, just to the right of the bank routing number.

If you don’t have a printed check, you can:

- Sign in to your online bank account and check your account details or a bank statement, or
- Call your bank
---

@peggygannon there appears to be a typo in the following line. Can you clarify:

> Sign in to your online bank account and check your account details or a bank statement, or

**Comment by peggygannon** [comment]
Hi, @erikphansen Yes, thanks for this. An error got introduced into the recommended content. I broke up that first bullet to make these options more clear:  

The bank routing number is the first 9 digits on the bottom left corner of a printed check. Your account number is the second set of numbers on the bottom of a check, just to the right of the bank routing number.

If you don’t have a printed check, you can:

- Sign in to your online bank account and check your account details, **or**
- Check your bank statement, **or**
- Call your bank

**Comment by erikphansen** [comment]
@peggygannon Perfect. I updated my comment above. Thanks.

**Comment by joshkimux** [comment]
> @joshkimux just to confirm the path forward:
> 
> 1. Replace the PNG of the check with the new SVG of the check
> 2. Add Peggy's text below the check image:
> 
> The bank routing number is the first 9 digits on the bottom left corner of a printed check. Your account number is the second set of numbers on the bottom of a check, just to the right of the bank routing number.
> 
> If you don’t have a printed check, you can:
> 
> * Sign in to your online bank account and check your account details, **or**
> * Check your bank statement, **or**
> * Call your bank
> 
> ~@peggygannon there appears to be a typo in the following line. Can you clarify:~
> 
> > ~Sign in to your online bank account and check your account details or a bank statement, or~
> 
> Peggy clarified below. This comment has been updated with the correct copy.

Yes, this is correct!

**Comment by jason-gcio** [comment]
Hi all - just wanted to touchbase on this ticket...does another ticket need to be created and/or should we leave this ticket open in Validate?

**Comment by erikphansen** [comment]
Your call, @jason-gcio. I am happy to finish this ticket off. It's all FE dev work at this point. But if you want to make a new ticket for me that's fine, too.

**Comment by jason-gcio** [comment]
Ok, lets save electrons and keep this one since it has the most detail and context.  Thanks @erikphansen!

**Comment by erikphansen** [comment]
Great. I'll remove all other assignees since this is my responsibility now. Should be done by EOW.

**Comment by erikphansen** [comment]
@joshkimux this can be validated on staging now!

**Comment by Samara-Strauss** [comment]
@joshkimux can you prioritize validating this? We have a go/no-go for launch later today, so it would be really helpful to know if we're squared away on this or not. Thank you!

**Comment by joshkimux** [comment]
@Samara-Strauss I was out on PTO! I've just reviewed this now and it requires one more little tweak.
@erikphansen could we add `role="img"` to the `img` of the check? This will negate the screen reader from reading out all the contents within the svg and treating it as a group.

See below for why:

### Without `role="img"` on an svg

https://user-images.githubusercontent.com/14154792/113153410-0fa69800-9205-11eb-8b64-f70a4970c058.mov

### With `role="img"` on an svg

https://user-images.githubusercontent.com/14154792/113153406-0e756b00-9205-11eb-85d5-bf0de9b0d51f.mov

**Comment by Samara-Strauss** [comment]
> @Samara-Strauss I was out on PTO! I've just reviewed this now and it requires one more little tweak.

Thank you! Yes, AJ let me know you were out yesterday. I don't have visibility into the contractor calendar, so I didn't know! But thank you for getting to this so quickly this morning.

**Comment by erikphansen** [comment]
PR is up. But it requires disabling an ESLint rule which gives me pause. https://github.com/department-of-veterans-affairs/vets-website/pull/16603

**Comment by Samara-Strauss** [comment]
☝️ @joshkimux any thoughts?

**Comment by joshkimux** [comment]
@erikphansen , ESLint is calling out a redundant role since we're using the `<img>` tag along with a `role="img"`. [This is perfectly OK in the case of SVGs though as documented on deque.](https://deque.com/blog/creating-accessible-svgs/)

**Comment by joshkimux** [comment]
One more note, could we replace the `alt` with `aria-labelledby="id-here"` ? @erikphansen 
e.g.

``` html
<img role="img" src="check.svg" aria-labelledby="caption"/>
<p id="caption">
  The bank routing number is the first 9 digits...
</p>
```

**Comment by joshkimux** [comment]
@erikphansen Ignore the previous comment I deleted! 🙇 
After testing on a screen reader, I think it would be more appropriate if the alt text was simply `alt="A personal check"` along with an `aria-describedby` pointing to the `p` below to avoid repetition/verbosity.

**Comment by erikphansen** [comment]
@joshkimux Updated! This also seemed like the perfect time to use a `figure` and `figcaption` so I made that change as well. Had to override some styles to make that work, but it still looks right:

<img width="381" alt="Screen Shot 2021-03-31 at 9 00 07 AM" src="https://user-images.githubusercontent.com/20728956/113174976-c9026f00-91ff-11eb-9c2e-403a2e367942.png">

**Comment by joshkimux** [comment]
@erikphansen Even better! 🥳 
Let me know when this goes up on staging and I'll validate + close accordingly 👍

**Comment by erikphansen** [comment]
@joshkimux The latest changes have been merged. Should be on staging sometime later this evening.

**Comment by joshkimux** [comment]
@erikphansen Just saw! I've tested once again, and this is now no longer a launchblocker as the alternative is being read out.

Adding `<figure>` is the right way forwards, but it also means we need to add in some minor changes to ensure it has better coverage for assistive technology and so that it will be less verbose. I realized this after testing again (see video below).

These are defect-level-4s, but if it's a quick fix it would make the figure much easier to navigate 😄 

### Original
```html
<figure>
  <img src="/img/direct-deposit-check-guide.svg" 
    role="img" 
    alt="A personal check" 
    aria-labelledby="check-caption">
  <figcaption id="check-caption">
    <p>The bank routing number is the first 9 digits on the bottom left corner of a printed check. Your account number is the second set of numbers on the bottom of a check, just to the right of the bank routing number.</p><p>If you don’t have a printed check, you can:</p>
     <ul>
      <li>Sign in to your online bank account and check your account details, or</li>
      <li>Check your bank statement, or</li><li>Call your bank</li>
    </ul>
  </figcaption>
</figure>
```


https://user-images.githubusercontent.com/14154792/113309671-6085c180-92d5-11eb-932a-239ebe979247.mov

In this video, the caption is repeated three times in a row.



### Proposed

```diff
+ <!-- Add role="figure" and aria-labelledby="check-caption" to the <figure> for better AT coverage -->
+ <figure role="figure" aria-labelledby="check-caption">
  <img src="/img/direct-deposit-check-guide.svg" 
    role="img" 
    alt="A personal check" 
- <!-- Remove aria-labelledby from the image to reduce verbosity as the caption is covered by use of figure -->
-    aria-labelledby="check-caption">
  <figcaption id="check-caption">
    <p>The bank routing number is the first 9 digits on the bottom left corner of a printed check. Your account number is the second set of numbers on the bottom of a check, just to the right of the bank routing number.</p><p>If you don’t have a printed check, you can:</p>
     <ul>
      <li>Sign in to your online bank account and check your account details, or</li>
      <li>Check your bank statement, or</li><li>Call your bank</li>
    </ul>
  </figcaption>
</figure>
```

**Comment by erikphansen** [comment]
@joshkimux new ticket created. Feel free to add any missing labels or edit it in any way. https://github.com/department-of-veterans-affairs/va.gov-team/issues/22522
