### ISSUE TITLE
508-defect-4 [COGNITION]: Text on image should not blur on zoom

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#19613]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Josh_

## User Story or Problem Statement

As a user who uses magnification tools, I expect text on images to retain their quality and not become blurry or grainy on zoom.

## Details

The use of a .png as opposed to a .svg causes the image to degrade when zoomed on.

## Acceptance Criteria

- [x] Text on image does not lose quality on zoom

## Environment

Any browser zoomed to 200%-400%

## Steps to Recreate

1. Enter `<https://staging.va.gov/profile/direct-deposit>` in browser
2. Edit the field
3. Expand the help text
4. Zoom in 400% on the check image
5. Confirm it's blurry

## Proposed Solution (if known)

A .svg would do the trick here. I've attached one here (github doesn't allow svg so it's wrapped in a zip)
[check.svg.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/5946766/check.svg.zip)

## Screenshots or Trace Logs

<img width="1133" alt="Screen Shot 2021-02-08 at 3 46 20 PM" src="https://user-images.githubusercontent.com/14154792/107280011-c8323580-6a25-11eb-85de-322c4273a3df.png">

**Comment by mshea0606** [comment]
@sporeboy @erikphansen  to use svg image listed above

**Comment by mshea0606** [comment]
@sporeboy will update image then tag Erik to implement change

**Comment by sporeboy** [comment]
Cleaning-up old tickets. PNG was replace with SVG (scalable vector graphic). Image does scale with zoom.

@erikphansen The old SVG looks like it's still in place--don't know if you're in a position to replace it. But below is the SVG cleanup I posted back on 2/17.

![dd-check-img.svg](https://images.zenhubusercontent.com/5d6ec7967521390001c3e794/dbe35765-cc58-4cdc-bdb1-75bcae3b58be)
