### ISSUE TITLE
Survey Tests That Remain In Nightwatch

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#19619]
* How many tests are still only in Nightwatch?
* Who owns the tests that are currently only in Nightwatch?

**Comment by holdenhinkle** [comment]
Here's a google doc that lists all Nightwatch tests (platform/application + product) - https://docs.google.com/spreadsheets/d/1DXj0GzObcfxBn6LKhOD9QO7kF8iZEWciAjHFfBkrFfs/edit?usp=sharing

**Comment by pjhill** [comment]
Excellent -- here's the results in MD table for posterity (in case the document evaporates somehow).

|spec                                                                                              |src         |owner/product         |
|--------------------------------------------------------------------------------------------------|------------|----------------------|
|src/platform/forms/tests/save-in-progress/01-sip-finish-later.e2e.spec.js                         |platform    |forms                 |
|src/platform/forms/tests/save-in-progress/01-sip-load-fail.e2e.spec.js                            |platform    |forms                 |
|src/platform/forms/tests/save-in-progress/01-sip-review.e2e.spec.js                               |platform    |forms                 |
|src/platform/forms/tests/save-in-progress/01-sip-autosave.e2e.spec.js                             |platform    |forms                 |
|src/platform/user/tests/unauthed-flows.e2e.spec.js                                                |platform    |user                  |
|src/platform/testing/e2e/megamenu/megamenu.e2e.spec.js                                            |platform    |megamenu              |
|src/platform/monitoring/DowntimeNotification/tests/DowntimeNotification.e2e.spec.js               |platform    |monitoring            |
|src/platform/site-wide/user-nav/tests/user-nav.e2e.spec.js                                        |platform    |site-wide             |
|src/platform/site-wide/tests/accessible-modal.e2e.spec.js                                         |platform    |site-wide             |
|src/platform/site-wide/tests/sanity-check/smoke-test.e2e.spec.js                                  |platform    |site-wide             |
|src/platform/site-wide/banners/index.e2e.spec.js                                                  |platform    |site-wide             |
|src/applications/personalization/rated-disabilities/tests/e2e/ratedDisabilitiesError.e2e.spec.js  |applications|personalization       |
|src/applications/personalization/rated-disabilities/tests/e2e/ratedDisabilitiesSuccess.e2e.spec.js|applications|personalization       |
|src/applications/coronavirus-chatbot/tests/01-buttons.e2e.spec.js                                 |applications|coronavirus           |
|src/applications/coronavirus-chatbot/tests/00-load-error.e2e.spec.js                              |applications|coronavirus           |
|src/applications/letters/tests/01-authed.e2e.spec.js                                              |applications|letters               |
|src/applications/veteran-representative/tests/00.veteran-representative-entry.e2e.spec.js         |applications|veteran-representative|
|src/applications/gi/tests/e2e/01-keyboard.e2e.spec.js                                             |applications|gi                    |
|src/applications/yellow-ribbon/00-required.e2e.spec.js                                            |applications|yellow-ribbon         |
|src/applications/pre-need/tests/00-all-fields.e2e.spec.js                                         |applications|pre-need              |
|src/applications/disability-benefits/disability-rating-calculator/tests/00-all-fields.e2e.spec.js |applications|disability-benefits   |
|src/applications/edu-benefits/tests/feedback-tool/01.feedback-tool-keyboard.e2e.spec.js           |applications|edu-benefits          |
|src/applications/edu-benefits/tests/feedback-tool/00.feedback-tool.e2e.spec.js                    |applications|edu-benefits          |
|src/applications/edu-benefits/tests/edu-apply-wizard.e2e.spec.js                                  |applications|edu-benefits          |
|src/applications/edu-benefits/0993/tests/e2e/00.0993-opt-out.e2e.spec.js                          |applications|edu-benefits          |
|src/applications/post-911-gib-status/tests/01-authed.e2e.spec.js                                  |applications|post-911-gib-status   |
|src/applications/static-pages/tests/application-status.e2e.spec.js                                |applications|static-pages          |
|src/applications/coronavirus-screener/tests/00.coronavirus-screener.e2e.spec.js                   |applications|coronavirus-screener  |
|src/applications/terms-and-conditions/tests/00.terms-and-conditions.e2e.spec.js                   |applications|terms-and-conditions  |
|src/applications/caregivers/tests/00.caregivers.e2e.spec.js                                       |applications|caregivers            |
|src/applications/claims-status/tests/e2e/04.claim-ask-va.e2e.spec.js                              |applications|claims-status         |
|src/applications/claims-status/tests/e2e/00.claims-list-breadcrumb.e2e.spec.js                    |applications|claims-status         |
|src/applications/claims-status/tests/e2e/06.claim-estimation.e2e.spec.js                          |applications|claims-status         |
|src/applications/claims-status/tests/e2e/00.claims-list-empty.e2e.spec.js                         |applications|claims-status         |
|src/applications/claims-status/tests/e2e/01.claim-status.e2e.spec.js                              |applications|claims-status         |
|src/applications/claims-status/tests/e2e/06-claim-estimation-breadcrumb.e2e.spec.js               |applications|claims-status         |
|src/applications/claims-status/tests/e2e/01.claim-status-decision.e2e.spec.js                     |applications|claims-status         |
|src/applications/claims-status/tests/e2e/02.claim-files.e2e.spec.js                               |applications|claims-status         |
|src/applications/claims-status/tests/e2e/00.claims-list.e2e.spec.js                               |applications|claims-status         |
|src/applications/claims-status/tests/e2e/05.claim-additional-evidence.e2e.spec.js                 |applications|claims-status         |
|src/applications/claims-status/tests/e2e/01.claim-status-est-past.e2e.spec.js                     |applications|claims-status         |
|src/applications/claims-status/tests/e2e/05.claim-document-request.e2e.spec.js                    |applications|claims-status         |
|src/applications/claims-status/tests/e2e/01.claim-status-est.e2e.spec.js                          |applications|claims-status         |
|src/applications/claims-status/tests/e2e/03.claim-details.e2e.spec.js                             |applications|claims-status         |
|src/applications/claims-status/tests/e2e/01.claim-status-est-current.e2e.spec.js                  |applications|claims-status         |
|src/applications/pensions/tests/00-all-fields.e2e.spec.js                                         |applications|pensions              |
|src/applications/coronavirus-research/tests/00.covid-vaccine-trial.e2e.spec.js                    |applications|coronavirus-research  |
|src/applications/discharge-wizard/tests/00-required.e2e.spec.js                                   |applications|discharge-wizard      |
|src/applications/burials/tests/00-all-fields.e2e.spec.js                                          |applications|burials               |
|src/applications/login/tests/00.login-page.e2e.spec.js                                            |applications|login                 |
