### ISSUE TITLE
Search results total is incorrect in mocked response

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#1962]
### Status

UNRESOLVED

### Severity Analysis

*Estimate of how critical this bug is*

`sev 3`
- Can go out in a regular deploy but still needs fixed ASAP
- Can be put into the owning team's backlog and scheduled by PM

### User Impact 

- *Who is the user impacted by this problem?*

Any user that is using the search feature/

- *How does this problem affect the user?*

The primary results are usually on the first page, which is completely inaccessible

### Description

I don't know if this is due to the search not working locally, or an actual issue...

In my local development environment (not on staging.va.gov - it's working there), using the search at the top of the page shows results from page 2 onward. I am unable to see any results, nor access page 1. I tried setting the search parameter to zero, but the results and the pager still shows as page 2. Either way, no results are shown, only the Top recommendations section.

![Screen Shot 2019-09-23 at 8 40 36 AM](https://user-images.githubusercontent.com/136959/65433454-a8738080-dde2-11e9-8d54-65969551c17f.png)

### Steps to Reproduce

- Click Search dropdown at the upper right on any page
- Search for any subject, e.g. "526ez"
- Result
  - The results page will report "Showing 11-20 of 999 results"; but no results are seen.
  - The pager starts on page 2. Using the pager will reload the page, but I still see "Showing 11-20 of 999 results"

#### Expected Results

The results and pager to behave as it does on the staging.va.gov site. Show results. Get the pager working properly. 

#### Actual Results

- No search results shown
- Pager does not allow going to page 1.
- Pager always shows the second page as results.

### Further Details

None

### Proposed Solution

Notify the code owners

**Comment by kfrz** [comment]
I don't believe this is severe issue, but I agree it needs some improvement. The API returns a response that is mocked out when running locally - this is likely some sort of difference in the response being sent to in production/staging than we have mocked.

We will investigate the disparity and likely have to update the mocks accordingly. 

/cc @alexpappasoddball I'm going to put this onto our board as it's not a `UX` issue - as we can see it is not a problem here, with results < 10 or otherwise. 

https://va.gov/search/?page=1&query=21-526ez+disagreement

**Comment by kfrz** [comment]
Confirmed modifying the mock data set [here](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/search/default.yml) has a very high results number which doesn't match actual results set.

**Comment by LindseySaari** [comment]
PR is here: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/97

Not exactly sure how to link the issue to vets-api-mockdata
