### ISSUE TITLE
Access for Nick Sprinkle

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#1963]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O’Toole
- Please provide your name.
   > Nick Sprinkle
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I am a front end engineer on the benefits/memorial team and work for Oddball.
- [Grant AWS Console access?]
  > YES
- Public SSH Key
  > ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwdY3GJyXNpIpNFpL+RhRER/JZrG9Do30WuYEt2bRX6D9+KNi4FJp7u9T1cYYvMppmbI1Rs3PDjxPHA92IYMdJAJTkRf1fjwFSeUvE/pcgT6i41jDmw8sbwoVUoKssstNfl+q2TcI9eXiwjalfkWdbgtQEoIm/opzJYVrbShNrMpubZX+lSAYyRSPfz7JCImx17nCCbYc0JGERLMUjU3T6PI0BsKSEv07LG3/6+dPFeuaJVq8sJzrXJwEVGoxtBx/qDKKlG4HfWFIb8xREz75zgA0YVK+l7d4GcRYxTWZ/w5XIFDlarNVaSht/RTOgjEJm2Dq8Lw4IQp6cAJ4bRZOj ndsprinkle@ubuntu

**Comment by ndsprinkle** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Nick Sprinkle

**Comment by ndsprinkle** [comment]
@tskinn When are these keys going to be authorized? I also have this PR created to get them added to the devops repo: https://github.com/department-of-veterans-affairs/devops/pull/5708

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for SOCKS access.

**Comment by jbritt1** [comment]
Ref: https://github.com/department-of-veterans-affairs/devops/pull/5708

**Comment by Jeff-Hayter** [comment]
@jbritt1 @ricetj Approved for AWS.

**Comment by jbritt1** [comment]
Initial login credentials / instructions communicated via Slack DM.
