### ISSUE TITLE
Module generator - Add FactoryBot config to engine file 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#19647]
## Issue Description
It was brought up in the [#vsp-tools-be channel ](https://dsva.slack.com/archives/CQHBJ5U06/p1612821413088600) that some initialization code needs to be added to the module generator engine file to loads factories automatically when running specs. 

The following code needs to be added to the engine.rb template file
```
initializer 'model_core.factories', after: 'factory_bot.set_factory_paths' do
    FactoryBot.definition_file_paths << File.expand_path('../../spec/factories', __dir__) if defined?(FactoryBot)
end
```
---
## Tasks
- [x] Add code to the engine template file
- [x] Verify changes when running the generator

**Comment by alexpappasoddball** [comment]
Looks good!
