### ISSUE TITLE
Alert not showing in preview of single Q&A article (RS)

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#19653]
## What happened?
_Single Question&Answer article template:
I added an alert component (non-reusable), then saved the article as a draft. In preview, it doesn’t show up._

**See Slack thread:** https://dsva.slack.com/archives/CDHBKAL9W/p1612881195097000?thread_ts=1612879548.095600&cid=CDHBKAL9W 
- It is only the non-reuseable alert that is not showing up in the FE.

## Steps to Reproduce
- URL: https://prod.cms.va.gov/resources/how-to-update-a-legal-name-change-with-va  
- OR any single q&a article template, in staging or prod preview

1. Create a standalone single q&a article.
2. Check the alert component box.
3. Select non-reusable alert.
4. Add alert content, and save draft of article.
5. Preview the page.

> Note: For now, I’m using a workaround: I removed the alert in the AX and included the alert text as a Note inside the answer intro text field, so this isn't urgent yet.
> However, the article template (all RS article templates in fact) is supposed to allow an alert component to display when it is enabled in the CMS.

## Desired behavior
_For the alert component to appear in preview below the answer text and above the CTA button._

## Acceptance Criteria
- [x] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
Thanks @jenniferlee-dsva for spinning up this ticket, I'm slotting this for this sprint for action.

**Comment by brianalloyd** [comment]
Validated - closing per validation.  Thanks @ncksllvn for the fix on this one.
