### ISSUE TITLE
Metrics Reporting Request - COVID FAQ Per Link Engagement

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#19657]
# Metrics Reporting Request

## Description
Who is this request for?

- Sharon Kasimow, Jennifer Lee
    
- What type of analytics support are you looking for?
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
Jan 5 - Feb 3 2021

## Analytics to Track Down

> What we’d really like to know is the average click rate for each link. This could then be used as the
> benchmark for what we should expect to see for each new anchor link on that page.
> Since there are so many links we’d need to get the averages for, I was thinking we could 1) take the top 5 most clicked links and bottom 5 least clicked links on the page and come up with an average. Or,
> we could benchmark based on # of clicks in the content body per PV.

## Which Product Questions are you trying to answer?
- Baseline engagement for a new link 

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
```sql
SELECT
 AVG(percent_engagement_rate)
FROM
(
SELECT
  A.date,
  A.event_action,
  A.total_events,
  A.unique_events,
  B.total_pageviews, 
  B.unique_pageviews,
  ROUND(((A.unique_events / B.unique_pageviews) * 100),2) as percent_engagement_rate
FROM 
(
SELECT 
  date, 
  hits.type as hit_type,
  hits.eventInfo.eventCategory as event_category,
  hits.eventInfo.eventAction as event_action,
  hits.eventInfo.eventLabel as event_label,  
  count(*) as total_events, 
  COUNT(DISTINCT CONCAT(fullVisitorId, CAST(visitStartTime AS STRING))) as unique_events
FROM 
  `vsp-analytics-and-insights.176188361.ga_sessions_*` as GA,
  UNNEST (GA.hits) as hits
WHERE 
  _TABLE_SUFFIX BETWEEN '20210105' AND '20210205'
  AND REGEXP_CONTAINS(hits.eventInfo.eventAction, r'Navigation - COVID.*')
  AND REGEXP_CONTAINS(hits.type, 'EVENT')
GROUP BY 
  1,2,3,4,5
HAVING
  COUNT(DISTINCT CONCAT(fullVisitorId, CAST(visitStartTime AS STRING)))  > 10
ORDER BY 
  5 ASC
) A
JOIN
(
SELECT
  date,
  count(*) as total_pageviews, 
  COUNT(DISTINCT CONCAT(fullVisitorId, CAST(visitStartTime AS STRING))) as unique_pageviews
FROM 
  `vsp-analytics-and-insights.176188361.ga_sessions_*` as GA,
  UNNEST (GA.hits) as hits
WHERE 
  _TABLE_SUFFIX BETWEEN '20210105' AND '20210205'
  AND hits.type = 'PAGE'
  AND REGEXP_CONTAINS(hits.page.pagePath,'www.va.gov/coronavirus-veteran-frequently-asked-questions/')
GROUP BY 
  1
) B
ON A.date = B.date
ORDER BY 
  percent_engagement_rate DESC
)
```

**Comment by jonwehausen** [comment]
## Notes
- Query above takes a stab at grabbing the total and unique events, as well as the total and unique pageviews for `www.va.gov/coronavirus-veteran-frequently-asked-questions/` between January 5 - Feb 5
- Currently filters for where there were at least 10 unique events - to keep the engagement rate not skewed by unique events of 1
- Current calculation comes out to an average engagement rate of 1.47%

@JasonTheBearded Do you think you would have a second to QA this query?

**Comment by JasonTheBearded** [comment]
@jonwehausen QA complete on the query. Looks good to me.

**Comment by jonwehausen** [comment]
@SKasimow @jenniferlee-dsva 

The average "click rate" or "engagement rate" has been calculated here. We filtered to only include those links that had at least 10 unique clicks in attempt not to drive down the engagement rate unnecessarily. 

As it turns out, 1.5% is the average per-link engagement rate. Our calculation takes the unique event totals for each link from each day between January 5 and February 9 and divides each by unique pageviews for the FAQ page for the day. 

![image](https://user-images.githubusercontent.com/48527022/107534479-e9ae3100-6b8d-11eb-840a-31322e3104f2.png)

I will move this to our review column for your approval prior to closing. 

Thanks and let us know any further questions you may have.

**Comment by jonwehausen** [comment]
BigQuery query link for future use: https://console.cloud.google.com/bigquery?sq=86772881199:2b2d49c49ba44a1c87d4fce7a8743cb8
