### ISSUE TITLE
Analytics Reporting Request for [VAOS - Recurring Metrics Domo Dashboard-Community Care]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19659]
## Background
The VHA Office of Community Care requests recurring metrics for appointments on VAOS.

## Request
Domo dashboard with metrics frequently referenced by the business.

### Dashboard Details
- [ ] Total community care submissions: total, successful, failed
  - Chart with monthly totals
  - Quick "all time" total count (Aug 2020 to present)

- [ ] Total community care submissions by type of care: primary care, optometry, podiatry, routine hearing exam, hearing aid support, nutrition and food
  - Chart with monthly totals

### Existing GA reference
[VAOS Key Data 3.0 Dashboard](https://analytics.google.com/analytics/web/#/dashboard/bhah2LQPRrKpwVq7lknoWg/a50123418w177519031p176188361/)
![Screen Shot 2021-02-09 at 8 17 23 AM](https://user-images.githubusercontent.com/72046525/107393989-3cb1b680-6ab0-11eb-863c-c82b159b25f4.jpg)    ![Screen Shot 2021-02-09 at 8 17 14 AM](https://user-images.githubusercontent.com/72046525/107393994-3de2e380-6ab0-11eb-983c-c1a46e5edb34.jpg)

**Comment by joanneesteban** [comment]
Hi @laurenernest - unfortunately, we're a bit strapped for resources right now, and will need to push this dashboarding back at least a sprint (in March). Let us know if you need support finding these metrics in GA.

**Comment by laurenernest** [comment]
@michelle-dooley this will be covered in #26851. good to close.
