### ISSUE TITLE
EDU Spool Submission Reports on Staging contain no data

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#19658]
Every morning, two reports (Spool Submission Report and 10203 Spool Submission Report) are sent out which contain submissions on Staging from the previous day. The reports sent on the morning of 2/9/21 did not contain any data despite there being submissions on Staging the previous day.

### Expected behavior 
The reports contain submissions from the previous day

### Actual Behavior
Reports contain no data

![Screen Shot 2021-02-09 at 11.17.35 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b734ceb0-79d4-4acf-b38b-36bfcbcc65dc)

![Screen Shot 2021-02-09 at 11.17.22 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ee49d40a-7aea-4226-a76d-db4fc9a1ec19)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5895
https://github.com/department-of-veterans-affairs/vets-api/pull/5896

**Comment by delli-gatti-michael** [comment]
Closing this out as the report is no longer blank #20077 covers the issue of submissions not being denied
