### ISSUE TITLE
VFS Support: Content Review for Rated Disabilities (Mockup)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#1965]
## Story  
As a member of the eBenefits team building with VSP, we need our content reviewed before a usability session to ensure it's accurate, aligns with VA style, and is error-free.

## Goal  
**Content:** To review the content in the [**Rated Disabilities**](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/) mockup and make sure it meets the standards.  

**Context:** The Veteran will be coming to this page for 3 main things with a few secondary actions.  There are a few error states shown in the mockup as well.  We think the url might be https://www.va.gov/disability/my-rated-disabilities/

1. See their Total Rated Disabilities Calculation - this tells them how much benefit pay they can seek from the VA.  
  1a. In case there is an error or if the Veteran wants to learn more about this, there are some helpful links available.  
  1b. In case there is need for an adjustment, there is a link with info on that as well.  
2. See the breakdown of that calculation - in case there is more or less than expected, the Veteran can see what is included in the formula for the Total Rated Disabilities Calculation  
3. Track and manage any pending rated disabilities - in the event that there are other ratings that have not yet been accounted for, the Veteran can see their status.  
  3a. The Veteran can click for more details in the Pending Status table and be taken over to the Claim Status Tool  

**Design elements to consider:** There do not appear to be any unformatted sections in the mockup at this time, but we should note that we are not sure what will be shown in the left sidebar nav at this time.  

**User research:** A review before presenting and asking for user feedback is anticipated.

## Considerations  
We have thought about some of the impacts on IA for [**this and a few of our other features**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/impact-on-ia.md).

## Acceptance Criteria
- [x] Feedback has been shared with the eBenefits Team

**Comment by peggygannon** [comment]
Hi, @jason-gcio 

Can you tell me when you need the content review to be completed by? Have user sessions been scheduled?

**Comment by peggygannon** [comment]
adding link to the Rated disabilities user flow diagram: 

https://xd.adobe.com/view/68c319f0-5bff-469e-4426-a1c628ed6c3c-1ef2/screen/67636adb-e65d-4b64-984d-09fd65f2a588/Disabilities-1/

**Comment by peggygannon** [comment]
@jason-gcio @sporeboy Hi, Jason and Jim, I've updated the Rated Disabilities mock up with my content suggestions/recommendations. Please let me know if you have any questions about my review. Thx! 
https://xd.adobe.com/view/ebfa6df6-c0aa-4ea9-413e-98793ba7a5a3-9dcb/

**Comment by jason-gcio** [comment]
I believe all the feedback has been provided (thank you!) but wanted to check in and see if there was anything else we needed to look at for this ticket.
cc: @meganhkelley, @peggygannon

**Comment by peggygannon** [comment]
@jason-gcio Thank you for checking in. I think we are good at the moment. I know there are some upcoming user testing sessions. Depending on what feedback comes out of those sessions, we might have additional content updates to make.

**Comment by peggygannon** [comment]
Hello! @jason-gcio Do you think we can close this ticket? If there are further content updates based on the user research sessions, I recommend that we track those updates in a new ticket.

**Comment by peggygannon** [comment]
Hi, @jason-gcio I'm closing this issue, as the initial content review was completed. If there are additional content updates needed based on user research, please open a new ticket for that work. thx! 

cc @meganhkelley

**Comment by jason-gcio** [comment]
Hey @peggygannon, sorry I hadn't closed this sooner. Thank you!
