### ISSUE TITLE
Field errors for Edit Email (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19669]
## User story
As a user, I want to understand why my email cannot be saved so I can fix the field that was flagged as invalid. 

## Acceptance Criteria
1. On the Edit Email page, the Save button should always be enabled, even when all fields are null
2. When there is a field-level error, display the mobile alert error CC at the top of the page:
     - Copy is hard coded: "Check your email address"
     - The error alert should disappear when all field level errors are resolved/have disappeared
3. Create UI for the field-level error below the Email field:
     - "Enter your email address again using this format: X@X.com" 
     - This error should display when the field is blank, or the entry does not contain the "@" character
4. When the Email field has an associated error, update the UI for that field to display the error UI (as detailed in the input field #19585 ticket): 
     - Label text: Mobile Body Bold
     - Border: 2px solid red secondary dark, #CD2026
     - Error text: Mobile Body Bold, #CD2026
5. The field-level errors should appear when any of the following occur:
     - A user taps into a required input field and leaves the field without completing it
     - A user tries to save the form without interacting with a required field. In this case, the error message displays when "Save" is selected
6. A field-level error should disappear when any of the following occur:
     - For dropdown fields: user makes a selection from the dropdown
     - For input fields: user begins typing into the field
     - A user hits "Cancel" to exit the form

## Designs
N/A. Similar design for field-level errors on the Edit Address page: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/442012480

## Discovery ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17044

## Accessibility Implementation Guidelines

**Error state:**
Formfield: “{label}. error - {Validation text}.”
Formfield/Message: “{label, hint message}. error - {Validation text}.”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/22/2021 - OK on iOS and Android.  Closing.
