### ISSUE TITLE
Field errors for Edit Address (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19662]
## User story
As a user, I want to understand why my address cannot be saved so I can fix the fields that were flagged as invalid. 

## Acceptance Criteria
1. On the Edit Address pages, the Save button should always be enabled, even when all fields are null
2. When at least 1 field level error appears on the form, the corresponding mobile alert error should also appear at the top of the page
     - Copy is hard coded
     - The mobile alert should disappear when all field level errors are resolved/have disappeared
3. Any fields that have an associated error will update to display the error UI (as detailed in the input field #19585 & dropdown #19584 CC tickets): 
     - Label text: Mobile Body Bold
     - Border: 2px solid red secondary dark, #CD2026
     - Error text: Mobile Body Bold, #CD2026
4. Create UI for the following field-level errors below the specified field: _(Note: these field-level errors will only appear next to fields that are already marked as *Required)_
     - Country: "Country is required"
     - Street Address Line 1: "Street address is required"
     - City: "City is required"
     - State (for non-international addresses): "State is required"
     - Zip code: "Zip code is required" OR "Zip code must be 5 digits"
         - "Zip code is required" should display when the field is blank
         - "Zip code must be 5 digits" should display when the field contains an entry that is >0 characters, but not equal to 5
     - APO/DPO/FPO: "City is required"
     - International Post Code: "Postal code is required"
5. Fields that are not indicated as *Required should not have an associated field-level error
6. The field-level errors should appear when any of the following occur:
     - A user taps into a required input field and leaves the field without completing it
     - A user tries to save the form without interacting with a required field. In this case, the error message displays when "Save" is selected
7. A field-level error should disappear when any of the following occur:
     - For dropdown fields: user makes a selection from the dropdown
     - For input fields: user begins typing into the field
     - A user hits "Cancel" to exit the form

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/442012480

## Discovery ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17044

## Accessibility Implementation Guidelines

**Error state:**
Formfield: “{label}. error - {Validation text}.”
Formfield/Message: “{label, hint message}. error - {Validation text}.”
Dropdown:“{label}. error - {Validation text}.”
Dropdown/Message“{label, hint message}. error - {Validation text}.”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/22/2021 - Looks good on Android and iOS except for known issue with clearing dropdown errors on Android. Can still Save, so OK.
