### ISSUE TITLE
App-wide copy changes (Part 1 of 2)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19671]
## Context for this ticket
Since some of the copy changes cannot currently be verified in QA, this task has been split up into 2 tickets:
#19671 | Part 1 of 2: can be verified by QA
#22314 | Part 2 of 2: cannot be verified by QA

## Acceptance Criteria
1. Using the spreadsheet linked below, implement all copy changes that have been approved by the DEPO team and do not require a follow-up:
     - In Column A, all rows marked "Yes" should be implemented. Any rows that are marked "No" can be omitted for this story

**Notes**
- See Column E for additional notes about text placement, font weight, etc.
- Optional: use Column H as needed to track of progress

## Content changes spreadsheet
**See tab:** "Copy changes"
https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit?usp=sharing

**Comment by bessgreen** [comment]
Note: depending on when this ticket is prioritized for dev, another ticket may be warranted in order to address the remaining changes that still require feedback from DEPO.

**Comment by digitalken** [comment]
PASS 3/29/2021 - These items are the ones that I've been able to verify as of this date on QA.  Part 2 of 2 are items that QA is blocked from verifying at this time.  Closing.
