### ISSUE TITLE
Typeahead analytics tagging bug fixes

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#19682]
There is currently an issue where:

1. Search Typeahead is ENABLED
2. A user is presented with typeahead options but chooses NOT to search using them
3. Typeahead suggestions list is NOT populating in event logging.

Need to investigate this issue and fix accordingly

Also, need to add the following variable to search data analytics
search-dropdown-used: true or false

**Comment by jonwehausen** [comment]
@srsuddath Thanks a bunch for opening this ticket. Fysa, here is an example where 'test' was entered and the search was performed **WITHOUT** selecting a type ahead option -- `type-ahead-options-list` is blank

![image](https://user-images.githubusercontent.com/48527022/107510601-37b53b80-6b72-11eb-9357-4912bd12c61d.png)

**Comment by jonwehausen** [comment]
@srsuddath and I spoke over Slack: 

- Will want to adjust the logic on the `search-dropdown-used` (can adjust naming as needed for clarify) variable to fire with `true` ANY time the heading dropdown is used, with typeahead, without typeahead, organically, etc. 
- Not yet able to `type-ahead-options-list` in data layer in staging

**Comment by srsuddath** [comment]
```type-ahead-options-list``` should be working now

**Comment by srsuddath** [comment]
Closing this issue and opening a new one for search-dropdown-used -> sitewide-search-app-used
as there will be some cross team communication needed there
