### ISSUE TITLE
Search Autofocus exploration

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#19683]
## Description

research is needed in order to commit to the autofocus enhancement for site-wide search

## Tasks

- [x] Investigate whether or not downshift supports an autofocus feature for the input field on site-wide search

## Definition of Done
A decision has been made on whether or not this feature can be added while maintaining the current downshift implementation.

**Comment by denisecoveyduc** [comment]
This was a stretch goal for Sprint 41 - rolling over into Sprint 42 for further exploration.

**Comment by srsuddath** [comment]
This ticket has been completed, autofocus is implemented
