### ISSUE TITLE
Analytics KPI dashboard request for Decision Tools Team - Find a VA Form

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#19689]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [x] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [x] Your KPIs are clearly linked back to Veteran outcomes
- [x] Link your KPIs below (KPIs should be in your Product Outline)
- [x] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the correct response.
- [X] New dashboard **(new Domo dashboard)**
- [ ] Iteration of current dashboard

### KPIs
[Link to product KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/README.md#kpis)
As info, I have created quite a few custom dashboards based on general metrics and existing events.  Those reports can be downloaded in bulk via these two links:
- [Bulk download batch 1](https://analytics.google.com/analytics/web/template?uid=r3dMF0kuRNSdxAYmMk3yZg)
- [Bulk download batch 2](https://analytics.google.com/analytics/web/template?uid=ipQWJEO4TqqntEbAweWRzA)

Details about each report's KPI purpose is provided in the attached spreadsheet, and I am hoping that your team can confirm that my search criteria are correct. 
[Analytics Request Info.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5954063/Analytics.Request.Info.xlsx)

There are also four new reports that we would like created, but I was not able to determine if the required data existed.  Information about those reports is also included in the spreadsheet, and they would be called:

- **Form Search Landing Internal Referrers**
- **Form Search Terms with Zero Results**
- **Form Search Terms with > 5 Results**
- **Form Detail Internal Referrers**

We would like to be able to access these reports from a shared central location and for them to display in the correct time frame (past month or several months) when we open them.

We also would like a Domo dashboard with six widgets as described below.
#### Widget 1

Pie Chart showing organic search referrers to the Find a VA Form Search Landing Page.  The search criteria can be found in the _CR - Form Search Page - Organic Search Insights_ custom report template

#### Widget 2 

Pie Chart showing organic search referrers to Find a VA Form Detail Pages.  The search criteria can be found in the _CR - Form Detail Organic Search Insights_ custom report template

#### Widget 3 

Stacked bar graph [similar to this one for Caregivers](https://va-gov.domo.com/page/1905395623/kpis/details/1629771016) (denoted as _Combo A_ in pink on the spreadsheet) that overlays the metrics from these three reports:
- CR - Form Search Landing Unique Pageviews
- CR - Form Search Landing Bounce Rate
- CR - Form Search TOTAL Unique Searches

#### Widget 4

Stacked bar graph (denoted as _Combo B_ in lavender on the spreadsheet) that overlays the metrics from these three reports 
- CR - Form Search Landing Unique Pageviews
- CR - Form Search TOTAL Unique Searches
- CR - Form Search TOTAL Search Refinements

#### Widget 5

Stacked bar graph (denoted as _Combo C_ in yellow on the spreadsheet) that overlays the metrics from these three reports 
- CR - Form Search Landing Unique Pageviews
- CR - Form Search TOTAL Detail Page Links Clicked
- CR - Form Search Landing TOTAL PDF Downloads
- CR - Form Search Landing TOTAL Online Tool Clicks

#### Widget 6

Stacked bar graph (denoted as _Combo D_ in green on the spreadsheet) that overlays the metrics from these three reports 
- CR - Find Form Detail Pages Unique Pageviews
- CR - Form Detail TOTAL Online Tool Clicks
- CR - Form Detail TOTAL PDF Downloads

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Hi @MarciMcGuireGCIO - unfortunately, our team is a bit strapped for resources to start working on this at the moment. We think we'll be able to get to this in a couple of sprints (in March).

We're looking into getting you Google Analytics links where we can so you can see some of the data in the meantime (CC: @bmcgrady-ep ).

**Comment by MarciMcGuireGCIO** [comment]
@joanneesteban thanks.  I've created GA custom reports for most; there were a few that I didn't know how to do, which I noted in the spreadsheet I attached to this ticket.

**Comment by joanneesteban** [comment]
@MarciMcGuireGCIO great! @bmcgrady-ep - when you get a chance this sprint, would you be able to take a look at GA to see if there's already a report?

**Comment by JasonTheBearded** [comment]
@MarciMcGuireGCIO what view are you using to create those custom reports?

**Comment by MarciMcGuireGCIO** [comment]
@JasonTheBearded  - All VA.gov Website Data [Production]

**Comment by JasonTheBearded** [comment]
KPI Validation complete

| KPI  | Metric  | Metric to Use | Metric Feasibility  |
| --- | --- | --- | --- |
| Widget 1 | Organic Search referrers to Landing Page | traffic source to va.gov/find-forms/ | 🔶 GO |
| Widget 2 | Organic Search referrers to Detail Pages | traffic source to all va.gov/find-forms/about-form-* | 🔶 GO |
| Widget 3 | Form Search Landing Page Unique Pageviews | count of distinct sessions to page | 🔶 GO |
| Widget 3 | Form Search Landing Page bounce rate | number of single page visits | 🔶 GO |
| Widget 3 | Form Search Landing Page unique searches | count of distinct sessions that include **view_search_results** event label | 🔶 GO |
| Widget 4 | Form Search Landing Page Unique pageviews | count of distinct sessions to page | 🔶 GO |
| Widget 4 | Form Search Landing Page unique searches | count of distinct sessions that include **view_search_results** event label | 🔶 GO |
| Widget 4 | Form Search Landing Page search refinements | count of distinct sessions that include multiple searches | 🔶 GO |
| Widget 5 | Form Search Landing Page Unique pageviews | count of distinct sessions to page | 🔶 GO |
| Widget 5 | Form Search Landing Page Total Detail Page links clicked | count of distinct events that include **onsite-search-results-click** event label and **title** search type(custom dimension 120) | 🔶 GO |
| Widget 5 | Form Search Landing Page Total PDF Downloads | count of distinct events that include **PDF Downloaded** event actions | | 🔶 GO |
| Widget 5 | Form Search Landing Page Total Online Tool clicks | count of distinct events that include **onsite-search-results-click** event label and **cta** search type(custom dimension 120) | 🔶 GO |
| Widget 6 | Form Search Detail Page Unique pageviews | count of distinct sessions to all va.gov/find-forms/about-form-* | 🔶 GO |
| Widget 6 | Form Search Detail Page Total Online Tool clicks | count of distinct events that include **cta-primary-button-click, cta-button-click** event label | 🔶 GO |
| Widget 6 | Form Search Detail Page Total PDF Downloads | count of distinct events that include **PDF Downloaded** event actions for all .gov/find-forms/about-form-* pages | | 🔶 GO |

**Comment by MarciMcGuireGCIO** [comment]
👏🏻 so exciting to see this!

**Comment by JasonTheBearded** [comment]
@MarciMcGuireGCIO for a couple of these metrics they reference 'Since launch' for the time span. Do you happen to know what the launch date is?

**Comment by MarciMcGuireGCIO** [comment]
@JasonTheBearded it could start July 1 2020 for the landing page (va.gov/find-forms/) and Oct 1 2020 for the detail pages. (va.gov/find-forms/about-form-)

**Comment by JasonTheBearded** [comment]
Dashboard creation complete. Ready for design review @mandy-uxd

**Comment by mandy-uxd** [comment]
Hello @MarciMcGuireGCIO,

We've been working on your dashboard and it's almost ready to go. One question -

We built the stacked bar charts as you requested, but a grouped bar chart may be better suited for these data points since it is easier to see the differences between the values. Would you like us to keep the stacked bar charts or switch to grouped? It only takes a few minutes to switch it.

Stacked: 
![image](https://user-images.githubusercontent.com/77311128/111244720-b281d400-85c0-11eb-9bd1-fb94cebd2318.png)

Grouped: 
![image](https://user-images.githubusercontent.com/77311128/111244751-be6d9600-85c0-11eb-97e3-85ec7fd410f1.png)

**Comment by MarciMcGuireGCIO** [comment]
Hi Mandy, thank you!  Yes, I see what you are saying about the stacked bar.  You're right; the grouped bar does show the data more clearly.  This totally works for me.  What say you, @johnhashva?

**Comment by johnhashva** [comment]
Agree @MarciMcGuireGCIO and @mandy-uxd

**Comment by JasonTheBearded** [comment]
@jonwehausen @bsmartin-ep Would one of you be able to do a QA check of this dashboard? https://va-gov.domo.com/page/1785082329, it's the one we walked through earlier this week and I completed my changes. Would like an extra set of eyes to make sure the data looks good. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
- Widget 1 ✔️ (slight diff, but very close)
- Widget 2 ✔️  (slight diff, but very close)
- Widget 3 & 4 - In GA, when I look at **Total Unique Searches** with a **Start Page** of (regex) _.*www.va.gov/find-forms/.*_ - I'm showing 170,076 for February, whereas Domo is showing 105,216.  Perhaps my regex is off? Am I also counting global searches started from that page?
- Widget 5 ✔️  (slight diff, but very close)
- Widget 6 - in GA, when I look at **Unique Pageviews** including (regex) _^www.va.gov/find-forms/about-form.*_, I'm showing 172,378 for Feb, where Domo is showing 156,504.  And when I look at Event Action (regex) _PDF Downloaded_ on page (regex) _^www.va.gov/find-forms/about-form.*_ I see 124,003 for Feb where Domo shows 111,801.

**Comment by JasonTheBearded** [comment]
Hi @MarciMcGuireGCIO, thanks for these notes! 

For Widgets 3 & 4 - Are you wanting to include searches from the detail pages as well or just the Landing page?

For Widget 6 - I made a few corrections to the calculations in DOMO to better capture pageviews and pdf downloads. Originally it was capturing just the distinct sessions for pageviews, so if a user viewed multiple forms in a single session, it was counting all those views as one. A similar issue with the PDF downloads where it was counting all downloads in a single session as one instead of a unique download for each pdf link. I took the distinct count request from our meeting on Monday a little too far. But that's now corrected and these numbers should line up better with the GA numbers.

Thanks again for your patience!

**Comment by MarciMcGuireGCIO** [comment]
Sure thing, @JasonTheBearded! Glad that was helpful!

On Widgets 3 & 4, we are only wanting to count the landing page searches. 

Thank you for tweaking Widget 6!

**Comment by JasonTheBearded** [comment]
Thanks @MarciMcGuireGCIO! I took a look at the GA report pulling the total unique searches and the regex is also including all the detail pages. I have the domo data filtered to exclude the detail pages when pulling those unique searches, so that's where the number difference is coming from.

**Comment by MarciMcGuireGCIO** [comment]
Cool deal.  Thank you for checking that.  My regex-foo is weak.  LOL

**Comment by JasonTheBearded** [comment]
Regex can be a challenge regardless of experience level haha. Let me know if you have any other questions, otherwise we'll go ahead and close this ticket.

Again I really appreciate your patience on this, thanks @MarciMcGuireGCIO!

**Comment by MarciMcGuireGCIO** [comment]
@JasonTheBearded Thanks, and thank you for putting this together!  Looks great!

**Comment by JasonTheBearded** [comment]
Glad to hear it! I'll go ahead and close this ticket then. Thanks!
