### ISSUE TITLE
[Cheetah MVP] - Check facility availability at start of flow

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19686]
## Issue Description
As a user, I would like to see if any facilities I'm eligible for allow online vaccine scheduling before I start the flow so that I don't take steps to make an appointment only to find out I can't do it online.

## Technical notes

We should add this check for the overall cheetah form flow, so that the check runs not only when you click Learn more on the CTA, but also if you navigate directly to the cheetah flow. This is similar to what Express Care does in src/applications/vaos/express-care/index.jsx by fetching the current EC windows and we should follow that pattern.

In order to make the check, we could do the same call that the facility page does to get a list of available facilities. Or, we can do a simpler check that just fetches data from the direct booking eligibility criteria endpoint, which is part of the calls to get the available facilities.

---

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] Given user clicks Learn more CTA on VAOS homepage, When there's at least one schedulable vaccine appointment for any facility they are eligible, Then user can continue through scheduling flow
- [ ] Given user clicks Learn more CTA on VAOS homepage, When there are no schedulable vaccine appointments for any facility they are eligible, Then user gets Contact a facility page

- [ ] Given Contact a facility page, When user has a home address in their profile, Then show max 2 eligible facilities nearest address
- [ ] Given Contact a facility page, When user does not have home address in their profile, Then show max 5 eligible facilities in alpha order

- [ ] Given Contact a facility page, When user clicks "Search for more facilities.", Then open Facility Locator page in a new tab

- [ ] ~~ANALYTICS - Track occurrences of this page~~ _(Lauren waived 2/22)_

- [ ] CONTENT - Contact a facility page header and body content matches copy in specs

- [ ] DESIGN - Designs match the specs https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9/a/1KKgar5#Inspector
![Screen Shot 2021-02-10 at 10.58.05 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/3dd915af-8348-4f34-ae06-ff75e0a8fdb3)

**Comment by vbahinwillit** [comment]
I need a little more information on what tag should be used for tracking this page? Is a new take required or do we have an existing one? Thanks.

**Comment by laurenernest** [comment]
@vbahinwillit I think the only other place we track something like this is in CC so this will likely be new. What's the URL for this page? Based on my latest understanding of the URL structure for these facility pages in this flow, we may be able to waive an additional tracking method.

**Comment by vbahinwillit** [comment]
@laurenernest - Sorry for the late reply. The URL is "http://localhost:3001/health-care/schedule-view-va-appointments/appointments/new-project-cheetah-booking/contact-facilities".

**Comment by laurenernest** [comment]
@vbahinwillit Thanks! I left a note in the description and waiving this AC for this ticket.
