### ISSUE TITLE
Add 2 additional mock errors to test account

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19691]
## Context for this task
This task is a stop-gap in order to demo the UI for various error states using mock data. There is a separate ticket to revert this ticket, which the FE team will implement post-demo. (#19175) **This ticket has also been updated with a new set of AC to add these mock accounts to another test user: 1414.**

## Acceptance Criteria
1. Display the following mock error state on the Appointments page:
     - Error state: **Upstream Appointments Error** (#18232)
     - User account that should display this error: vets.gov.user+1414@gmail.com
2. When creating the Appointments mock error, the list of Upcoming/Past appointments that do appear should **not** include representation from all 6 appointment types. This error occurs when the service cannot return at least 1 type of appointment (such as Community Care)
    - For example: If there is a theoretical service error with Community Care appointments, then Community Care appointment types should not appear in the Upcoming/Past list.
3. Display the following mock error state on the Claims page: 
     - Error state: **Generic Error with Refresh** (#18227)
     - User account that should display this error: vets.gov.user+1414@gmail.com --> This Refresh mock error will replace the "Claims & Appeals are unavailable" mock error that currently exists
     - For this mock error, the Refresh button should simulate a failed call (i.e. the button is selectable, but the mock error always persists)
_____

Original AC, for reference
~~## Acceptance Criteria:
1. Display the following mock error state on the Appointments page: 
     - Error state: **Upstream Appointments Error** (#18232)
     - User account that should display this error: vets.gov.user+1401@gmail.com
2. When creating the Appointments mock error, the list of Upcoming/Past appointments that do appear should **not** include representation from all 6 appointment types. This error occurs when the service cannot return at least 1 type of appointment (such as Community Care)
    - For example: If there is a theoretical service error with Community Care appointments, then Community Care appointment types should not appear in the Upcoming/Past list.
3. Display the following mock error state on the Profile page: 
     - Error state: **Generic Error with Refresh** (#18227)
     - User account that should display this error: vets.gov.user+1401@gmail.com
     - For this mock error, the Refresh button should simulate a failed call (i.e. the button is selectable, but the mock error always persists)~~

**Comment by digitalken** [comment]
2/17/2020 - Need the new passwords to these users.

**Comment by digitalken** [comment]
2/24/2021 - This is present but I need it a little longer while @bessgreen checks on some copy for the upstream appts. error.

**Comment by digitalken** [comment]
PASS 2/24/2021 - Closing.
