### ISSUE TITLE
Access for [Nichole Harris]

### ISSUE THREAD

**Issue by NCHLiberty** [department-of-veterans-affairs/va.gov-team#19690]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

Please provide your Contracting Officer's Representative (COR) name.
Cecilia Lee Cecilia.Lee@va.gov

Please provide your name.
Nichole Harris

Please Provide your email.
nichole.harris@libertyits.com

Please provide the name of your team, your role on that team, and the name of the company you work for.
Team Name = Matsumoto
Company = Libertyits
Role =Product Manager

Requesting SSH key authorization?
YES

What is your public SSH key? If you don't have a SSH Key or know how to find it [click here]ssh-ed25519
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbdoJAXJXEOTkbx8+kBY7GlTjacUoQnxjPe1lvROUmsY2F9+J6UgVXjroXk3YxPw3SqdPUh84HEHP/xlSovXCOudLldQPYlvYCt1E5rNgo/YVSRQjLbkWO2iAVinKRwEc1PLe3zaxNwr5sObqNTcohFvqven711D68ZDuDUAiSP70op45rC685H6XO0cD2yG6gB2s8uDja5ZD/z2YwVNT8zQkmWWbq8b0CMwRrBjhvHSTdP8ysd8PajihNmztbka/bWlF9gjG59f3NgSegiCc7fTXcUxb6NrxGQH2g7yPIYRKi+dVE9PBRXOa4Rur57xLXg89svC72ZkXcLPt4XPjt+pzNDUApbTTCR+rZjjYnOLn7EJjbnuXq8edq/TnCRjZ/PeQ/2bL/7IaffWTq5ZfnMBykkrBl7ZxOi4JW4HUIeGKosk/R3PodgtiRXbTFkWWCxVsHtp85pjrEjhSXLiYUM1JjQIT/xBEYrDo16efWFy1yarGWUcoAM7FdPlZY1C0= AzureAD+NicholeHarris@WIN-JO913FR0J10

Grant AWS Console access?
YES
S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house

**Comment by jbritt1** [comment]
### For AWS Access:

User: Nichole Harris
COR: Cecilia Lee
Approval required: @Jeff-Hayter

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by NCHLiberty** [comment]
Thanks!

**Comment by mleclerc00** [comment]
@NCHLiberty 

was the aws access ever sorted for you?

**Comment by NCHLiberty** [comment]
TBH i keep getting side-tracked and haven't completed the process but as far as I did get it seemed to be working as expected per the instructions....i'll try to finish up soon and come back if any issues. you can probably close this ticket?

**Comment by mleclerc00** [comment]
Awesome thanks for the response.  I will close this ticket and if you need anything further we can address it in a new one.

**Comment by drorva** [comment]
Request sent to CORS. Awaiting confirmation.
