### ISSUE TITLE
Analytics Reporting Request for [VAOS-Recurring Metrics Domo Dashboard-Program]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19698]
## Background
Our prime/program requests recurring metrics for VAOS.

## Request
Domo dashboard with metrics frequently referenced by the program.

### Dashboard Details
- [ ] Monthly total of users logged in
  - Include partial month counts
- [ ] Total appointments submitted
- [ ] Conversion rate
  - Existing GA reference- [Appointments submitted and conversion](https://analytics.google.com/analytics/web/template?uid=mfBmqnM8TeSZVP2hgMFZOg)
![Screen Shot 2021-02-09 at 2 27 48 PM](https://user-images.githubusercontent.com/72046525/107437019-34bf3a00-6ae3-11eb-89c9-deb4e0137434.jpg)

**Comment by joanneesteban** [comment]
Hey @laurenernest - unfortunately, we're a bit strapped for resources, and will need to push this dashboarding back at least a sprint (in March). Let us know if you need support finding these metrics in GA.

**Comment by laurenernest** [comment]
No problem! This is a lower priority compared to our initiative-related requests.

**Comment by laurenernest** [comment]
@michelle-dooley this will be covered in #26851. good to close.
