### ISSUE TITLE
We need an "application has expired" state

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#19702]
It's possible for an in-progress application to expire. We should represent this state like we do on the current My VA Dashboard.

Example: In this screenshot, this application has expired so we shouldn't give them the option to "continue"

![applications-in-progress-mobile.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/934b4ba0-dc51-43c6-b142-3761dd70940b)

This is what we show people on the current Dashboard:

![application has expired.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/18cb611d-2160-415c-b677-9a26998e3de2)

For reference, [this is the relevant code](https://github.com/department-of-veterans-affairs/vets-website/blob/c82bdfb3832e6369a258afbd03582cd034ee8abf/src/applications/personalization/dashboard/components/FormItem.jsx#L55-L85) for the current "expired" state.

**Comment by callen2563** [comment]
I have created the expired state for benefit applications and uploaded it to InVision with the other screens here: 
https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/445338903_My_VA_Desktop_Application_Expired
