### ISSUE TITLE
Stop showing expired, saved-in-progress applications on My VA Dashboard v1

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#19703]
On the current My VA Dashboard, the `remove this notification` button that appears on expired in-progress applications does not work.

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/360f1ab6-bf72-4426-8d30-ebd896fd638c)

This used to be handled by the `FormList` component that was deleted long ago. We should be calling the `removeSavedForm` action creator. https://github.com/department-of-veterans-affairs/vets-website/blob/42135a1b4ea1cc8741fed41aa3bd7053da99ef11/src/applications/personalization/dashboard/actions/index.js#L34-L44

**Comment by Samara-Strauss** [comment]
Per #20775, for My VA 2.0, we are no longer going to allow removal of expired apps on the dashboard. **Instead, we just won't show applications as in-progress once they have expired.** We can apply the same logic to My VA 1.0.

**Comment by erikphansen** [comment]
Merged and closing as I don't think there's an easy way for this to be validated.
