### ISSUE TITLE
[DISCOVERY] Analyze array differences reported by diff tool

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19710]
The diff tool still seems to be reporting diffs due to array sorting issues.

After running `yarn cms:diff:json`, health_services_listing-2803-array.json (for example) tons of “Array Edit” diffs, with no Array Length issues. 

There is no sorting currently on either the graphql or transformer; sorting is done in src/site/stages/build/drupal/metalsmith-drupal.js

Similar issues in press_releases_listing-2805-array.json.

Either the diff tool needs to be made sort-agnostic, or the graphql and transformer need to use identical sorting. Further analysis is needed to determine the correct steps here.

## Acceptance Criteria

-[ ] Determine cause of the array differences and create a plan to resolve.

**Comment by mmiddaugh** [comment]
Archiving this issue but keeping track by linking in Facilities Transformer support (collection of issues) #17956
