### ISSUE TITLE
[Design] MyVA 2.0: Create copy updates documentation and provide to FE

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19723]
## Background
We need to make sure to create documentation around the copy updates for the various states in a way that is easy for Erik/Sandra to use. 

## Tasks
- [x] Create MyVA copy updates documentation
- [x] Share documentation with FE

**Comment by callen2563** [comment]
I have created and updated the copy doc for development to reference and shared it with them. It lives here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/my-va-copy.md
