### ISSUE TITLE
[Design] MyVA 2.0: Recruit for research

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19724]
## Background
We need to recruit participants for usability testing for MyVA dashboard 2.0. 

# Tasks
- [x] Tressa kicks off recruiting with Lauren Alexanderson.

**Comment by Samara-Strauss** [comment]
The details in this ticket aren't helpful. What this ticket needs to be:

- Tressa kicks off recruiting with Lauren Alexanderson.

Otherwise, there is nothing to do, since Perigean handles the recruiting.

**Comment by Samara-Strauss** [comment]
@tressaellen recruiting has formally been kicked off, yes? If so, we can close this. This ticket was just to mark that we've actually formally kicked off this process with Lauren and she has kicked things off with Perigean.

**Comment by tressaellen** [comment]
@Samara-Strauss it hasn't been kicked off officially, Lauren hasn't had time to review our artifacts yet. Hopefully by end of day today.

**Comment by Samara-Strauss** [comment]
Got it! Sorry, was confused and made an assumption based on your post in Slack. Totally fine. Just wanted to see if I could close this, but we should absolutely leave this open until Lauren approves our materials and initiates things with Perigean.

**Comment by tressaellen** [comment]
No worries! It's been a bit of a weird process this go-around. I'll close this when Lauren gets back to me.

**Comment by tressaellen** [comment]
Recruiting has been kicked off!

**Comment by Samara-Strauss** [comment]
YAY!!
