### ISSUE TITLE
HCA Screener

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#19726]
## User Story

_As a user I would like to have this feature because it would help me with this pain point_

## Expected Behavior

_Add expected behavior of the described feature here_

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by ala-yna** [comment]
Goal: mitigating duplicate submissions

(Fall 2018)
Q: How are people submitting health care applications?
- Over 50% are from Veterans who had previously submitted applications.
- The thought was that this was how Veterans were changing their address?
- Turns out to be confusion around application decisions, people not knowing what the status was. 
- People had been admitted but had no idea, or were eligible and had no idea.
     - ~Half of all applications (7k/month) were duplicate/unneeded

**Comment by mlighdc** [comment]
@ala-yna can you help provide some context?

**Comment by ala-yna** [comment]
Used this ticket to take notes when we talked to Samara about the HCA screener.

**Comment by ala-yna** [comment]
Some of this information may be useful to @Dene-human as we work on updating the HCA.

**Comment by mlighdc** [comment]
Got it. It was unclear since it was written up as a user story vs. .md file.

**Comment by mlighdc** [comment]
Changed header to indicate notes about 10-10EZ duplicate applications.
