### ISSUE TITLE
[Tech debt] Delete deprecated CMS code

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#19722]
While I was working through my PR to make GraphQL more efficient, I was puzzled about some of the code I encountered and had trouble understanding what was its purpose. It was complex. Basically, it did a "Find and replace" on certain values, and I didn't understand why we didn't just use the correct value in the first place. 

Upon investigation, the code was left over from a CMS feature flag, https://github.com/department-of-veterans-affairs/vets-website/commit/7b54b495ccddc229a811231aefba897066aa7e35#diff-78d2ba7081dd26ac2a8a81b3bc6c0c80461f62412580c370dff8564362e33ee4R71.

We should remove unnecessary complexity by delete `src/site/utilities/stringHelpers.js` and all references to it. We'll get a GraphQL error if we do it wrong, so it isn't high risk.

**Comment by ncksllvn** [comment]
@brianalloyd this is a tech debt ticket I'd love to do next sprint....this code was confusing and doesn't do anything anymore.

**Comment by brianalloyd** [comment]
@ncksllvn can we close out this ticket based on the merged PR above?

**Comment by brianalloyd** [comment]
Closing.
