### ISSUE TITLE
CT: Create mobile sticky nav custom component

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19721]
As a developer, I need to create a custom component that supports a sticky navigation bar so that when we begin development we have all of the necessary components available.

## Assumptions:
1. Use CT sandbox for testing a mock implementation of the control.
2. The display of a navbar above 950px is handled in a separate story.
3. This implementation should work with all institution types (IHL, VETTEC, etc).

## Acceptance Criteria:
1. A "sticky" navigation bar component exists with the following behavior:
    a. The nav bar is sticky once it hits the top of the viewport.
    b. The nav bar style is displayed up to resolutions of 950px wide.
    c. An up navigation arrow
    d. A down navigation arrow
2. The up navigation arrow is:
    a. Disabled when the user is viewing the header or the top section of the page.
    b. Enabled when the users is viewing a section other than the header/top section of the page.
    c. Moves to the next section higher on the page when clicked.
3. The down navigation arrow is:
    a. Disabled when the user is viewing the last section of the page.
    b. Enabled when the user is viewing a section other than the last section of the page.
    c. Moves to the next section lower on the page when clicked.

## Supporting Artifacts:
1. 
<img width="416" alt="Screen Shot 2021-02-10 at 8 28 23 AM" src="https://user-images.githubusercontent.com/48260534/107516146-f9bc1580-6b79-11eb-99dd-7bc81cb15175.png">
2. [Invision Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222473/296056063/preview) - Note; sticky nav doesn't work in the prototype.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16115

**Comment by JenLJ** [comment]
On iPhone 11, I took screenshots of the frames immediately before and after the transition - and the Estimate your Benefits heading is getting cut off.
![Sticky Nav 1](https://user-images.githubusercontent.com/36964225/109054937-87385300-76ac-11eb-8ef0-638fa45502d5.png)
![Sticky Nav 2](https://user-images.githubusercontent.com/36964225/109054938-87d0e980-76ac-11eb-9123-811b0adb2c99.png)

**Comment by amyknox** [comment]
This works and looks as expected for me. 2/2
