### ISSUE TITLE
Remove settings.js

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1973]
# Overview 

The settings file (https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/js/settings.js) should no longer be used by vets-website apps.

# Tasks 

- Document how the settings file is currently used 
- Remove the settings.js file
- Test for regressions on va.gov and teamsite pages

**Comment by bkjohnson** [comment]
Closed by https://github.com/department-of-veterans-affairs/vets-website/pull/12264
