### ISSUE TITLE
[PM] DD4edu: Conduct Contact Center review

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19734]
## Background
As part of the VSP collaboration cycle requirements, we need to conduct the contact center review

[Contact Center Review Request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#contact-center-review)

## Tasks
- [x] Compile artifacts
- [x] Submit request
- [ ] Conduct CC review
- [ ] Make any changes if needed

**Comment by mshea0606** [comment]
Request submitted: Contact Center Review for [Authenticated Experience - Direct Deposit for EDU] #19899

**Comment by jason-gcio** [comment]
@mshea0606 - I am going to remove this from the EBN board while we are in planning to avoid confusion, we can move them back after if you would like.

**Comment by Samara-Strauss** [comment]
This ticket isn't necessary. I'm making sure everyone has everything the need in #19899. Assuming they do, I'll re-close that issue and there is no further action required with the contact center team.
