### ISSUE TITLE
Update ESLint Dependencies

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#19748]
## Dev task
ESLint dependencies should be able to be updated to work with TS and RN. 

These updates are major updates and may require significant work to get the lint in line with our code base.

| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
 | @typescript-eslint/eslint-plugin | 2.34.0 | 2.34.0 | 4.15.0 | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/parser | 2.34.0 | 2.34.0 | 4.15.0 | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  
| eslint | 7.15.0 | 7.19.0 | 7.19.0 | devDependencies | https://eslint.org |  |
 | eslint-plugin-react | 7.21.5 | 7.22.0 | 7.22.0 | devDependencies | https://github.com/yannickcr/eslint-plugin-react |  |
| eslint-plugin-tsdoc | 0.2.7 | 0.2.11 | 0.2.11 | dependencies | https://tsdoc.org/ |  |

**Comment by digitalken** [comment]
Dev task - Closing 2/22/2021.
