### ISSUE TITLE
[Epic] My VA: Frontend build of health care data

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#19743]
## Background
Specs https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md

The health care component should be responsible for loading RX, secure messages, and/or upcoming appointment data if the user has access to those features

Slack convo re: getting appointment data from VAOS apis https://dsva.slack.com/archives/CMNQT72LX/p1611848483055100

**Comment by Samara-Strauss** [comment]
Gonna close this. Looks like all the tickets originally tagged here are completed.
