### ISSUE TITLE
[BE] Regression testing for direct deposit in staging for EVSS R17.12 release

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#19753]
## Background

[From Slack](https://dsva.slack.com/archives/C8R3JS8BU/p1612976001056000):

> EVSS will deploy our R17.12 release to PINT1 environment on Thursday morning, 2/11/2021. This release updates every VA.gov consumed service that we host; therefore, once the deployment is completed, we ask that a regression test be performed and completed by COB Friday, 2/12/2021. Monday is a holiday and Tuesday, we push to Dark Prod, so results (hopefully good) are needed before the Dark Prod push. I will send you both an email with the details of the changes in these services. I will also let you know on Thursday when PINT1 is ready for your testing. Thanks much in advance.

## Tasks

- [ ] Run regression testing **by end of day Friday, 2/12/21** in staging for direct deposit once the EVSS R17.12 release is complete
- [ ] Let EVSS know how it went, whether there are issues or no issues

**Comment by lihanli** [comment]
i tested viewing and updating direct deposit info for user `vets.gov.user+378@gmail.com` on staging and it's working

**Comment by Samara-Strauss** [comment]
Great, thank you!
