### ISSUE TITLE
Investigate API availability for Total Combined Disability Rating.

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#1975]
## User Story or Problem Statement
As a backend engineer, I need to know where the Total Combined Disability Rating (TCDR) comes from so I can query that data and send it the appropriate frontend application.

Additionally, if it's discovered that TCDR needs to be calculated on our end, I want to send a 'final calculated value' to the frontend to avoid having to calculate it there. 

## Goal
_What outcome(s) do we want to see?_
- We want to determine where we get the value for TCDR or if it is something that we need to calculate on our own.

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by steve-gov** [comment]
If we can't get it into the current EVSS package we're pulling from, this is an alternative: https://developer.va.gov/explore/verification/docs/disability_rating
