### ISSUE TITLE
Design Feedback - Staging Review - [VAOS - Community Care Provider Selection]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#19757]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Nice work!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- If you use the info alert with the blue right bar, put it on a white background since it is on a gray card. See Sketch/Styles/Cards for example. The alerts with the blue side bar and icon are not mobile friendly. You could use a blue info box callout instead. See Sketch/Styles/Content Presentation for example.![Screen Shot 2021-02-09 at 1.08.30 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/3893f063-18c5-4018-921d-b59c36216493)
- Add X to top right of modal to close
- Make sure the cancel button on modal is using the right style. It looks like it is dark blue, not light blue.
![Screen Shot 2021-02-09 at 1.09.45 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/a3f3f050-0c45-4116-9b85-8e7146a49f15)

**Should:**

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by 1Copenut** [comment]
@allison0034 I'm running the a11y review now, and looking at the + Choose a provider button that appears as a link. My feedback will be to make this a [standard Collapsible Panel](https://design.va.gov/storybook/?path=/docs/components-collapsiblepanel--default) unless you have a different recommendation.

**Comment by allison0034** [comment]
@1Copenut I agree with this! @peggygannon would that change what the + expand should say?

**Comment by peggygannon** [comment]
@allison0034 @1Copenut I think the current head "Choose your provider" will still work

**Comment by outerpress** [comment]
>The alerts with the blue side bar and icon are not mobile friendly. You could use a blue info box callout 

Love it! The info alert was definitely too much. [Mockup with info box callout. ](https://adhoc.invisionapp.com/share/F3106OHDSJ9G#/screens/444665371)

> Add X to top right of modal to close - Make sure the cancel button on modal is using the right style. It looks like it is dark blue, not light blue.

👍 👍 

>  My feedback will be to make this a standard Collapsible Panel unless you have a different recommendation.

I'm worried users might not expect a collapsible panel to allow input, since these are generally used to display static information. It might lead to skipping over this question. Are other inputs using a collapsible panel like this? Or list-loop patterns? (CC: @rtwell @1Copenut )

Thanks!

**Comment by laurenernest** [comment]
"Must" feedback has been implemented with #19966
