### ISSUE TITLE
Update react-native-gesture-handler library

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#19768]
## Dev task
The react-native-gesture-handler library needs to be updated, but there are some breaking changes for our apps testing that need to be fixed.

You will need to remove `/node_modules/react-native-gesture-handler/jestSetup.js` from the `setupFiles` in the `jest.config` file in the app. 

You will also need to add mocks for the following: 
```
jest.mock('react-native-gesture-handler', () => {
	const NOOP = () => {
		// do nothing
	}
	return {
		attachGestureHandler: NOOP,
		createGestureHandler: NOOP,
		dropGestureHandler: NOOP,
		updateGestureHandler: NOOP,
		Direction: {
			RIGHT: 1,
			LEFT: 2,
			UP: 4,
			DOWN: 8,
		},
		State: {
			BEGAN: 'BEGAN',
			FAILED: 'FAILED',
			ACTIVE: 'ACTIVE',
			END: 'END',
			UNDETERMINED: 'UNDETERMINED',
		},
	}
})
```

If you have questions, please ask @lexicalninja or @jmarchi

**Comment by digitalken** [comment]
2/18/2021 - Closing Dev Task.
