### ISSUE TITLE
Content Feedback - Usability  testing prep - My VA

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#19762]
## User story
VSP Usability prep content review of My VA. 

Link to prototype: https://vsateams.invisionapp.com/share/XNZWCYAYD45#/screens/444040702_My_VA_Mobile

## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

**Comment by peggygannon** [comment]
Hello, @callen2563 @tressaellen Please see content feedback for My VA usability prep. Let me know if you have any questions.


**Thoughts/Questions**

1. Regarding the content on the status cards for  "Claims" and "Application in progress"  cards. I want to confirm that that status content is pulled from somewhere else and we can't tweak it?  

2. I feel like the "Service-connected disability rating" content in the banner is getting lost


-------

**Must**

- Claims and appeals cards: Please remove the word “date”  as the date is already listed in the card. 


- Please change: What benefits does the VA offer TO: What benefits does VA offer?

 We don't use “the” before VA when it’s used as a noun.


- Continue application button, please update  TO: "Continue your application"  to align with how this button content appears elsewhere on the VA.gov. 


------

**Consider**

Recommend removing the “day” of the week from the appointments and prescriptions card. We don’t include "days" on the other dates in the dashboard. We should be consistent in how we present dates.

**Comment by tressaellen** [comment]
Hi @peggygannon I've incorporated your 'Must' points.

> Regarding the content on the status cards for "Claims" and "Application in progress" cards. I want to confirm that that status content is pulled from somewhere else and we can't tweak it?

From @erikphansen -

Yes and no. Form names and specific info about the type of claim/appeal or the status of the claim/appeal comes from a shared resource and should remain consistent. Other text we can easily control. Is there a specific request?

> I feel like the "Service-connected disability rating" content in the banner is getting lost

We all assumed people wouldn't be able to see this easily, but users had no problem finding or understanding their disability rating so I think we're probably good here.

> Recommend removing the “day” of the week from the appointments and prescriptions card. We don’t include "days" on the other dates in the dashboard. We should be consistent in how we present dates.

We ended up removing the cards in the prescriptions section, so I left the "day" of the week in the appointments card so it will match what is shown in VAOS

**Comment by peggygannon** [comment]
Hi, @tressaellen thank you for the followup!

**Comment by tressaellen** [comment]
@peggygannon are we good to close this ticket?

**Comment by peggygannon** [comment]
Hi, @tressaellen Yes, this can be close. thx!
