### ISSUE TITLE
PROD Previews Slow and Timing Out

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#19787]
The CMS team received a report on Jan. 28th from Lisa Trombley on VAMC Upgrade team that previews were very slow and sometimes timing out. 

To temporarily unblock the VAMC Upgrade team, @tskinn increased the timeout on the PROD Preview server from 60 to 300 seconds. 

I was able to reproduce consistently in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4151 and the GQL cache is getting invalidated on any node save, not just the node that is being requested by the query. @ncksllvn said he may have an idea on how to reasonably improve this slowness. 

Related internal threads:
* https://dsva.slack.com/archives/CDHBKAL9W/p1611856292037400 (support request on Jan 28th)
* https://dsva.slack.com/archives/CBU0KDSB1/p1611857007368600 (increased ELB timeout for temporary unblocking)
* https://dsva.slack.com/archives/C01512KN35G/p1612984982200600 (technical discussion with @ncksllvn and I)
* https://dsva.slack.com/archives/C52CL1PKQ/p1612986446391700 (triage to this ticket)

## Tasks
- [ ] Improve preview speed (@ncksllvn)
- [ ] Revert ELB timeout (@tskinn)

**Comment by acrollet** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-cms #5228](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5228) via [**ZenHub**](https://www.zenhub.com/)
