### ISSUE TITLE
Jenkins includes job trigger in Slack message

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#1979]
## User Story
As a VA.gov engineer, I need to know what/who triggered a `vets-website` Jenkins deploy job in Slack to speed up the triage of issues or questions about the job should they arise.

## Goal
The existing Slack notification includes information about what/who triggered each Jenkins deploy job.

## Objectives or Key Results this is meant to further
 - Reliability: ensure VA.gov is a reliable site for Veterans (and their families) to use.
 - Agility: incentivize VFS Teams to build performant applications in an agile way.
 - Ownership: ensure long-term VA ownership of, maintenance of, and iteration on VFSs.
 - Self-service: ensure VSP scalability through increased self-service tooling and documentation.

([Source](https://docs.google.com/presentation/d/1-8LlD8jljlv-C9IIQO1fHDC4ok0NzpJF3nLfwnx5610/edit#slide=id.g5bcedc037d_2_89))

## Acceptance Criteria
- [ ] When a Jenkins job is triggered, the Slack "warn" message identifies who/what triggered the job.

**Comment by wyattwalter** [comment]
We don't plan on using Jenkins for the long-term. This is low priority enough that I don't think we'll realistically get to it. Closing.
