### ISSUE TITLE
Analytics KPI dashboard request for Debt (formerly known as BAM2) add data to DOMO 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#19791]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.

**- [ ] Iteration of current dashboard**

### KPIs
Can you please add the following to DOMO 

1. Debt Details Page --> Page views, avg time on page 
2. number of unique visitors, number of repeat visitors over 3 month period 

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Thanks, @leahkeeler  ! We'll let you know when we're able to triage this & pulled it into our sprint.

**Comment by joanneesteban** [comment]
Hi @leahkeeler unfortunately, our team is a bit strapped for resources to for us start working on this at the moment. We think we'll be able to get to this in another sprint (in March).

Let us know if you need support finding some of the data Google Analytics in the meantime (CC: @bmcgrady-ep ).

**Comment by leahkeeler** [comment]
@joanneesteban No problem, March is fine with us

**Comment by JasonTheBearded** [comment]
Hi @leahkeeler can you provide the URL for the debt details page? Thanks!

**Comment by leahkeeler** [comment]
HI @JasonTheBearded 

https://www.va.gov/manage-va-debt/ is the landing page 

for logged in experience it is https://www.va.gov/manage-va-debt/your-debt/ which we refer to as debt details page

**Comment by JasonTheBearded** [comment]
Perfect, thanks @leahkeeler!
