### ISSUE TITLE
[Design] MyVA: Mock up desktop screens

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19795]
## Background
We need to mock up desktop screens in preparation for usability testing.

## Tasks
- [x] Mock up latest screens for desktop

**Comment by callen2563** [comment]
![My VA Desktop Cerner-MHV](https://user-images.githubusercontent.com/68560244/107575426-e3d04400-6bbd-11eb-9c62-7ee73d70ce10.jpg)
![My VA No updates](https://user-images.githubusercontent.com/68560244/107575431-e468da80-6bbd-11eb-8a61-fdd792345ff1.jpg)
![My VA Desktop](https://user-images.githubusercontent.com/68560244/107575435-e468da80-6bbd-11eb-92b7-d5c80c83aced.jpg)
![My VA LOA1](https://user-images.githubusercontent.com/68560244/107575437-e5017100-6bbd-11eb-8597-bc0593dce324.jpg)
![My VA FTUX](https://user-images.githubusercontent.com/68560244/107575441-e5017100-6bbd-11eb-8f60-7147dbdcc629.jpg)
