### ISSUE TITLE
508-defect-3 [SCREENREADER]: VAOS CC Provider Select - Choose a provider should use our Collapsible Panel component

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#19799]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a screen reader user, I want to understand the Choose a provider interaction will present more information on the current page.

## Details

The current Choose a provider button swaps the gray box with a larger box and some radio buttons. It would be better to use the [Collapsible Panel component](https://design.va.gov/storybook/?path=/docs/components-collapsiblepanel--default). This will offer more contextual cues to assistive technology. Screenshot attached below.

## Acceptance Criteria

- [ ] Custom button swapped out for standard Collapsible Panel

## Environment

* https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/community-care-preferences
* Test user Judy

## WCAG or Vendor Guidance (optional)
* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2021-02-10 at 3 51 23 PM](https://user-images.githubusercontent.com/934879/107577309-e334af00-6bb7-11eb-9682-642935b43f46.png)

**Comment by 1Copenut** [comment]
Cross-linking to https://github.com/department-of-veterans-affairs/va.gov-team/issues/19757 as there's an active discussion about this element going on, and it relates to UX and accessibility jointly.

**Comment by laurenernest** [comment]
Additional design work related to this topic will be handled in #21802 as part of a larger improvement effort.

Closing this ticket as it won't be implemented specifically with this initiative.
