### ISSUE TITLE
508-defect-4 [COGNITION]: VAOS CC Provider Select - Are there ways to make buttons appear as buttons instead of links?

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#19804]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a screen reader user or a user with low or reduced vision, I may have trouble determining buttons that appear visually as links.

## Details

Design and Accessibility are trying to move toward a visual style where buttons are not presented as links. This has a couple of key improvements:
1. For visual navigation users like Dragon Speaking Naturally, users can say "Click the NAME button" and it will execute their command on the first try. If users say "Click the NAME link", it may not execute their command.
2. For users with low or reduced vision, we could have situations where they are advised to click a button like "Remove provider" that looks like a link.

/cc @rtwell for awareness

## Acceptance Criteria

- [ ] Review the issue with design to see if it's something the team wants to pursue
- [ ] Consult with a11y specialist as needed, OR
- [ ] Close the issue if the team opts not to change this item

## Environment

* https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/community-care-preferences
* Test user Judy

## WCAG or Vendor Guidance (optional)

* [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

## Screenshots or Trace Logs

![Screen Shot 2021-02-10 at 4 33 48 PM](https://user-images.githubusercontent.com/934879/107582262-e1221e80-6bbe-11eb-92aa-63794fdb6bfd.png)

---
![Screen Shot 2021-02-10 at 4 34 12 PM](https://user-images.githubusercontent.com/934879/107582275-e5e6d280-6bbe-11eb-8526-026c3f9c6870.png)

**Comment by laurenernest** [comment]
Additional design work related to this topic will be handled in #21802 as part of a larger improvement effort.

Closing this ticket as it won't be implemented specifically with this initiative.
