### ISSUE TITLE
Access for Jack Schuss (new SSH key/computer)

### ISSUE THREAD

**Issue by yakschuss** [department-of-veterans-affairs/va.gov-team#19807]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Jack Schuss
- Please Provide your email.
   > jack.schuss@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse - BananaPeals - Software Engineer - Oddball

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDJEpzBqzG3DmjJ48UStLvup2kDweAQb5+Z+9Y1hSOJU jackschuss@gmail.com

```

- Grant AWS Console access?
have access

**Comment by yakschuss** [comment]
Ideally I’d like to be able to use my laptop as well, if possible/allowed. @mleclerc00

**Comment by mleclerc00** [comment]
Hi @yakschuss sorry about that.  I have restored your old key as well as adding the new one.  The deploy was successful so you should be able to connect with both computers.  When you get a chance let me know if it works on your end and if there is anything else I can help with.

Thanks!

**Comment by yakschuss** [comment]
No problem! Seems to work well. Thank you!
