### ISSUE TITLE
Publish banner for Tropical Storm Karen

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1981]
Using text:

> For the latest Tropical Storm Karen-related facility, pharmacy and resource updates, visit [here](https://www.caribbean.va.gov/emergency/index.asp).

**Comment by ncksllvn** [comment]
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/a3e795d3-3841-44bd-a866-f35b2b0dea2f)

**Comment by Karak888** [comment]
Verified and moving to close this issue.
