### ISSUE TITLE
VAOS::UserService#new_session_token - VAMF returning status 502

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#19817]
#### As of this 02/10/2021 (02/03/2021-02/10/2021) there were 689 occurrences of this error.

* URL: ` /users/v2/session`

Team will investigate Prometheus, Cloudwatch and the vets-api code-base to determine root-cause of this issue.

#### Deliverables
* A brief summary of the the results including any data that will help VAMF in identifying the issue.
* Include any supporting documents as attachments (e.g. spreadsheet, etc...).
* A list of any tickets that were opened in Jira.

**Comment by cferris32** [comment]
There were 167 instances of a 502 error on the `/users/v2/session` endpoint from Feb 1, 2021 to March 12, 2021. Multiple request ids were analyzed to look for a pattern in the failures. There is no descernable pattern on these errors being tied to a particular controller, and the payloads from VAMF contain variously structured HTML segments indicating a bad gateway or unavailable service. Attached below is a complete log of the relevant records for this time period.

[https://app.zenhub.com/files/133843125/487a1fe2-913f-4dc2-ad0d-9b737602783e/download](https://app.zenhub.com/files/133843125/487a1fe2-913f-4dc2-ad0d-9b737602783e/download)
