### ISSUE TITLE
IA Request [VAOS, VAOS for Distribution]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19821]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to product outline
  - [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/vaos-for-distribution-initiative.md)
- Link to or attach prototype or mockups
  - [Prototype](https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/443560117_Home)
- Link to research readout/results
  - [TBD](#)
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach final content including H1s (if separate from prototype/mockup)
  - _Content changes will likely happen until launch due to evolving situation_

## Information Architecture Worksheet (Optional)
Link to the [current pages in flow](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/Cheetah%20MVP%20IA%20Notes.png). The pages that are new and specific to this flow vs existing pages used for flow are indicated in the diagram.

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by laurenernest** [comment]
@mnorthuis Research will run concurrently with this development. We have a few pages that will be new and specific to this flow. Let me know if you need to wait for the research results or if you're able to provide guidance on the URLs for the new pages without it.

**Comment by mnorthuis** [comment]
Hi @laurenernest, because these new pages are within an existing form flow (and therefore part of an existing URL) , you can go ahead and propose those URLs and I will review for adherence to formatting guidelines.  

In general, I would recommend using a single key word to represent that step in the flow.  Use the H1 of the page to inform your word choice.  You should also take inventory of all the URLs within the flow to ensure they don't conflict with one another.  If you need assistance let me know and I can definitely collab on it.

**Comment by laurenernest** [comment]
Sounds good! Thank you!

**Comment by laurenernest** [comment]
Here's documentation for the flow with updated URLs https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md

Some of the content is still changing so the H1s aren't final, but would still love any thoughts you have.

**Comment by mnorthuis** [comment]
@laurenernest @DanielleThierryUSDSVA Hi, thanks for the above link.  In looking at the screenshots, the experience has evolved a bit from when I last saw it, so I just wanted to clarify a couple things in terms of labeling/content. 

Do the screenshots in the link above represent final copy/H1s?
Can you define when you utilize "facility" vs "location" vs "clinic", I was not clear in looking at this when each term would/should be used. 
Can you let me know if "booking" is the term we are using here versus "appointment?

cc @peggygannon

**Comment by laurenernest** [comment]
The screenshots are close to "final". There are a couple more recent updates that aren't reflected there yet. I also say final loosely as there's a lot that could change once we're in a pilot phase and gather feedback.

In the context of scheduling, clinic is a more specific location at a larger facility where appointments can be booked.

For "booking", are you looking at the URL with `new-covid-19-vaccine-booking` in it? We can change that to `new-covid-19-vaccine-appointment` for consistency. There isn't a particular need to use booking in this instance.

**Comment by mnorthuis** [comment]
Hi @laurenernest, I have a quick question...

There are 2 pages you have URL as `/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/contact-facilities`.    One is if there are no facilities, and the other is if they are trying to schedule their 2nd dose.  Is this technically the same page with different messaging, or are they different pages?

**Comment by laurenernest** [comment]
Same page and purpose, but with different messaging depending on the scenario.

**Comment by mnorthuis** [comment]
A few thoughts/recommendations based on the screenshots provided.  You are welcome to close this issue at your discretion once you have the information you need.  

- For the breadcrumb, consider adding the word "appointment" to the last segment of the breadcrumb and the small caps above the H1.   Home > Health care > Schedule and view appointments > VA online scheduling > New COVID-19 vaccine appointment

- I walked through the URLs proposed and reviewed the H1s as well as the URLs used elsewhere on the site and within VAOS.  My goal was to make them concise and consistent.  Here are my recommendations: 

Page | URL
-- | --
New   covid appt | /health-care/schedule-view-va-appointments/appointments/new-appointment-covid-19-vaccine
New   covid appt - contact facility | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/contact-facility
New   covid appt - dose history | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/confirm-doses-received
New   covid appt - Choose facility | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/choose-facility
New   covid appt - Choose clinic | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/choose-clinic
New   covid appt - Select date | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/select-date
New   covid appt - Second dose  info | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/second-dose-info
New   covid appt - Contact info | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/contact-info
New   covid appt - Review | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/review
New   covid appt - Confirmation | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/confirmation
