### ISSUE TITLE
Access for Adrian Rollett

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#19834]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Adrian Rollett
- Please Provide your email.
   > adrian.rollett@agile6.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Senior Software Engineer on the Agile Six VFS-CMS team

- Requesting SSH key authorization?
   > NO, have it already

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
@ElijahLynn recommended I get AWS access to learn about the Devops side of things.

**Comment by ElijahLynn** [comment]
For AWS Access:
User: Adrian Rollett
COR: Jeff Hayter
Approval Required: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
Thanks @ElijahLynn.  Once the Ops team gets eyes on this I can approve.

**Comment by ElijahLynn** [comment]
> * What AWS services do you need access to and why?
>   @ElijahLynn recommended I get AWS access to learn about the Devops side of things.

And to view Cloudwatch Logs and view Cloudwatch Insight Dashboards.

**Comment by jsev-io** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by jsev-io** [comment]
Access credentials and instructions delivered to user.
