### ISSUE TITLE
Error | Letter cannot be loaded

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19836]
## User story
As a user, when my letter won't download due to some issue with the service, I want to see an error message that clarifies what is happening with the ability to try downloading it again.

## Acceptance Criteria
1. Create UI for an error state when there is an error downloading a letter .pdf. This error will appear after the user hits "View letter" and the .pdf fails to download.
     - Copy: "Your letter could not be downloaded." (Mobile Body)
2. "Try again" Large Button
     - Selecting this button will make a call to try and download the letter

## Designs
None. Please model the UI after the No Connection error:
![Screen Shot 2021-02-11 at 5.01.28 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4fc5e723-7325-4df9-85c7-3226cae3775b)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

**Try again button**
- Title= "Try again"
- accessibilityHint= “Try again to download your letter” 
- accessibilityRole= “button”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
PASS 2/18/2021 - Android and iOS.  Closing.
