### ISSUE TITLE
App startup sign in screen - "VA" is pronounced as "Vaw" rather than "V" "A" (Accessibility)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#19830]
## What happened?
Android with Talkback enabled is saying "Vaw" instead of "V" "A".

## Specs:
- Device: Android Samsung Galaxy Note 9 with talkback enabled

## Steps to Reproduce
- Read the startup screen with TalkBack enabled on an Android

## Desired behavior
Pronounces "V" "A" rather than "Vaw".

## Acceptance Criteria
Says "V" "A".

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/41033a74-2d6c-4f25-801c-880f56a5d0f9)

**Comment by digitalken** [comment]
Fail - 2/17/2021 - Now it is saying "Find a "Vee" "A" location. Go to "vaw" facility locator. Button.  Double tap to activate."
Can we get it to say "Vee" "A" for both, @komaly15 ?

**Comment by komaly15** [comment]
yep, updating that now

**Comment by digitalken** [comment]
PASS 2/2/2021 - VA in both places now.  closing.
