### ISSUE TITLE
Missing copy from No Network Connection error

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19838]
## What happened?
The **No Network Connection** error is missing the section header copy, as specified in #18231, AC #1:
     - Header 2: "VA Mobile App can't be loaded." - _**missing**_
     - Body: "You aren't connected to the internet. Please check your internet connection and try again." _**missing punctuation**_

## Specs:
- Device: iPhone 11

## Steps to Reproduce
While logged into the app, kill the WiFi connection and press any button to make a call, which should trigger the **No Network Connection** error.

## Desired behavior
1. This error state displays the following header: "VA Mobile App can't be loaded." (Mobile Body Bold)
     - This should be marked as **Header 2** for accessibility
2. The supporting copy below contains a period <.> after each sentence

## Acceptance Criteria
See desired behavior

## Bug Severity
- 4 - Low

## Linked Story
#18231

## Screen shot(s) and additional information
![Image from iOS (12).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/51c923f6-e4e6-4b5b-bfbc-e4b06d34eebe)

**Comment by digitalken** [comment]
PASS 2/18/2021 - Title is present and punctuation corrected.  Closing.
