### ISSUE TITLE
Analytics KPI dashboard request for HLR

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#19844]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the correct response.
- [x] New dashboard
- [ ] Iteration of current dashboard

### KPIs
[Team KPIs](add your team's KPIs here)

[HLR KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/README.md)
- Number of HLR submissions (input KPI)
- Time to HLR decision (input KPI)
- Is there a higher ratio of accepted HLR claims than before (input KPI for part of the ratio)
- % of "rejected" HLR claims (input KPI)

Baseline KPI's - HLR

- HLR Submissions: Total HLR EPs established FY 2020 through July. Average: 7k a month
- HLR ADC: Monthly and FYTD average days pending, through July.
- HLR Grant Rates: Grant rates, from PA&I’s monthly AMA Reports website. Average 17.1%

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Thanks @vhenry07 ! We'll let you know when we're able to triage this & pulled it into our sprint.

**Comment by joanneesteban** [comment]
Hi @vhenry07 - unfortunately, our team is a bit strapped for resources to start working on this at the moment. We think we'll be able to get to this in a couple of sprints (in March).

We're looking into getting you Google Analytics links where we can so you can see some of the data in the meantime (CC: @bmcgrady-ep ).
