### ISSUE TITLE
Form 526ez and 996 (HLR) url path determination

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#1984]
Per @mnorthuis 

> the 526 has an old URL that was grandfathered in from vets.gov - so its not necessarily the format we want to follow moving forward ( i.e. /disability-benefits directory is not valid and we have a different approach to form names in URLs).

The intro page for form 526EZ is:
https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction

Once you are logged in and start working on the form, it redirects to:
https://staging.va.gov/disability-benefits/apply/form-526-disability-claim/resume

I was asking what path should form 0996 (Higher-Level Review) use. So once this has been determined, I can finish work on #1914.

**Comment by mnorthuis** [comment]
URL will be based on full IA review - please set up some time for IA review.  Thanks!

**Comment by Mottie** [comment]
@YanaRoy

**Comment by mnorthuis** [comment]
@Mottie talked with the team Friday, sounds like a lot of work is still in progress, so its hard to nail down IA structure and URL until some things are worked out a bit more.  I have an idea of what this will look look like, but want the team to have a chance to work through design.  Please let me know if this becomes a blocker for you.

**Comment by Mottie** [comment]
It's not a blocker. The path can be updated relatively quickly.

**Comment by mnorthuis** [comment]
All IA feedback, including recommend URLs are documented here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3822
