### ISSUE TITLE
Access for Matthew Roth

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#19840]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Doris Lin (meichih.lin@va.gov)
- Please provide your name.
   > Matthew Roth
- Please Provide your email.
   > roth_matthew@bah.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > BAH Team supporting Education on VA.gov (Comparison Tool, etc)

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2qIjDxEBSHX8uXUl7Xz7b1pkNA+5cPk2U1kQg67r42djP/xPO2E6kPM9REBN6tHw22L34Xs2HkMT+oq2jcN0NshmBZwXP2oAl37GziPTAThXX7lloLmumlgbuLZPsxs/0Xr4mi/5OItYIXTk6JN/JEeOqZHjDp/LijZ2T8uXtZyANWDE4RHAYhgXbfc8YvFOK/EMJb35Im3mI5zr1p47vjrCVb6tNmRk1ylzkNi7H/Y4m+ksb8HbIO7AOd3NlvdSnEvX2ueMH0sIAP6gcXZq8OKQ+AvKlCxwQdIdhmjhUXgWZGlftBd3MMoaSq8UjecSrp4sxbT1l+0G6xa35ISzch3QukmIJJnNuWmRnUrKnENlXcO8dWVIVNVP13moYwklFO13T+T4TLks3Q13A8iVqr4yqs+/jRYUSZYNLMYXwaJ6ZkZB5OWAaA+tqfj9hYITBjeqyQMjXO+xI9P86/VtqdzN8L+1EWn6Zyc/emVniUScRsHjfIh14j507Zl6Jics= matthewroth@C02CJ047MD6V
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by zurbergram** [comment]
I lost access to previous SSH key and needed to create a new one

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/vsp-operations Please review.

I lost access to previous SSH key and needed to create a new one.

**Comment by jsev-io** [comment]
@zurbergram 
You should now have access using this key. 
Thanks

**Comment by zurbergram** [comment]
Confirmed it is working
