### ISSUE TITLE
Update Chapter 33 rates that begin August 1-HOLD UNTIL END OF JULY

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#19848]
## Issue Description
Stakeholder Tammy Hurley provided the updated rates for Chapter 33, which go into effect August 1, 2021. We need to update these numbers on our own education rates pages. 
**Note:** We currently don't have education rates pages but they may be built by this time. If that's the case, these numbers should be added in starting August 1, 2021.

[https://app.zenhub.com/files/133843125/4772aacd-bd19-4fa5-9555-9a08b334b2f5/download](https://app.zenhub.com/files/133843125/4772aacd-bd19-4fa5-9555-9a08b334b2f5/download)

## Tasks
- [ ] Update Chapter 33 rates 

## Acceptance Criteria
- [ ] Most current rates are on live page

**Comment by RLHecht** [comment]
@bethpottsVADEPO I think it's safe for us to close this ticket since we won't be creating education rates pages in time for this work to be done. But if you think we should leave in the icebox for when we eventually do build these, let me know.

**Comment by bethpottsVADEPO** [comment]
I agree. Closing!
