### ISSUE TITLE
Analytics KPI dashboard request for BDD

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#19846]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.
- [ x] New dashboard
- [ ] Iteration of current dashboard

### KPIs

- Number of Benefits Delivery at Discharge (BDD) submissions (input KPI)
- Time to BDD decision (input KPI)
- % of BDD claims that are closed as BDD (vs. converted to a regular claim) (input KPI)

- % of "rejected / diverged" BDD claims (input KPI)
- 
- Time to complete BDD form
- 
- Does anyone get stuck on a screen for some time?
- How many people eventually give up (as a rate/%)
- Can we compare this to legacy methods (eBenefits)
- Time on page
- Number of BDD claims successfully "adjudicated" within n days (North Star Metric)

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Thanks @vhenry07 ! Same with the HLR dashboard request: we'll let you know when we're able to triage this & pull it into our sprint.

**Comment by joanneesteban** [comment]
Hi @vhenry07 (as with HLR) - unfortunately, our team is a bit strapped for resources to for us start working on this at the moment. We think we'll be able to get to this in another sprint (in March).

We're looking into getting you Google Analytics links where we can so you can see some of the data in the meantime (CC: @bmcgrady-ep ).

**Comment by bmcgrady-ep** [comment]
Hi @vhenry07 - Here are some GA Reports that should help you answer some of your KPI questions:

- Number of Benefits Delivery at Discharge (BDD) submissions (input KPI) ([GA Report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210222&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=disability-526EZ--submission-successful&explorer-graphOptions.selected=analytics.nthWeek/))
- Does anyone get stuck on a screen for some time? ([GA Report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20201201&_u.date01=20210222&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=250&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22www.va.gov~2Fdisability~2Ffile-disability-claim-form-21-526ez~2F%22,0%5D,%5B1,%22analytics.pageviews%22,%22GT%22,%221000%22,0%5D%5D&explorer-graphOptions.selected=analytics.nthWeek&explorer-table-dataTable.sortColumnName=analytics.avgPageDuration&explorer-table-dataTable.sortDescending=true/))
- Time to complete BDD form (This can only be answered with BigQuery, not Google Analytics)

**Comment by vhenry07** [comment]
Thank you.

**Comment by jonwehausen** [comment]
Hi @vhenry07 , 

We want to apologize in advance for previously delivering aggregate 526EZ metrics. 

In order for us to ensure we have (and can deliver) the correct metrics for BDD this go-around, can you give us a bit more context into where within the application BDD is established? We understand the benefit is offered within 180 to 90 days before the veteran leaves the military, we just want to understand more tactically within the application how that submission is performed. We also understand the wizard is designed to funnel the correct eligible users into the application. Any guidance /  examples of the clicks / paths the user takes for BDD submissions we would very much appreciate it. 

Thanks and we look forward to hearing from you.

**Comment by vhenry07** [comment]
Hi Jon, not a problem. Had to learn a little more about this myself. BDD is embedded in Form 526ez, and that's probably what makes this difficult to pinpoint. We have been able to gather data submission data from Grafana, so this time and with our stakeholder's access to data in Tableau, may have everything we need. Let's close this ticket and I'll revisit if needed. Thanks.
