### ISSUE TITLE
VAOS::SystemsService#get_request_eligibility_criteria - VAMF returning status 502

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#19856]
#### As of this 02/10/2021 (02/03/2021-02/10/2021) there were 85 occurrences of this error.

* URL: `/facilities/v1/request-eligibility-criteria`

Team will investigate Prometheus, Cloudwatch and the vets-api code-base to determine root-cause of this issue.

#### Deliverables
* A brief summary of the the results including any data that will help VAMF in identifying the issue.
* Include any supporting documents as attachments (e.g. spreadsheet, etc...).
* A list of any tickets that were opened in Jira.

**Comment by ajmagdub** [comment]
The following is a summary of events per day of VAMF 502 errors for the get_request_eligibility_criteria From Feb. 2021 to Mar. 18. 2021.

|   Date    | Count  |
| --------- | ------ |   
|2021-02-01 |   4    |
|2021-02-02 |  15    |
|2021-02-08 |   1    |
|2021-02-09 |   2    |
|2021-02-12 |   5    |
|2021-02-19 |   6    |
|           |        |
|2021-03-01 |   1    |
|2021-03-03 |   1    |
|2021-03-04 |   1    |
|2021-03-05 |   3    |
|2021-03-06 |   2    |
|2021-03-07 |   2    |
|2021-03-08 |   4    |
|2021-03-10 |   1    |
|2021-03-12 |   1    |
|2021-03-13 |   1    |
|2021-03-15 |   1    |
|2021-03-16 |   1    |
|2021-03-17 |   1    |        

Here are the request Request Ids for the above errors:

**Feb. 2021**

52e13d16-9bfb-44fc-bdb5-c5b9b5bacbf1
34cb529e-5879-459a-b74f-bba22534a8e6
14b4ecb6-f71b-4d9f-a6ae-fd36ed8f0946
d10659e7-5b31-44dc-bad8-be1a7ef426aa
eaea6beb-c79a-4b3e-b682-3fc92fa02560
484c6e08-e957-4f35-ab2b-0356de3882ef
84911b47-dee6-4d80-8244-7c3bb1d0e598
fdd67e3e-245b-4e0f-864c-889f88a937e5
81f5e3a3-054a-4753-91f1-9035ec6bdbf0
88664946-fcbf-4bac-b4e3-7168050141ec
4789c75b-9c49-4729-9f6c-2b7919c77c78
cfda81c0-c931-45cb-bcd2-6a0450b4fbec
97bf8d96-c8f7-4021-9449-7a55f504667b
33c2f86f-fc0f-4c56-9b7f-9db98e5ad773
fb77f93f-bc0a-4d92-ac82-9a6680a6349d
987e5a3a-cab5-46bd-af77-3c11ccfc7a0c
eb21d022-c85c-461f-9344-5cb820d0afa4
b81755be-7b26-448e-9b63-0eb06bb36768
f3fb45ba-f932-4941-b3b2-40c96b6bd486
7d7b23f1-4288-4ea6-bae4-049218372a2f
861f74e5-3247-4b1a-a768-566eb52a3fd5
3b5bc3d7-5356-496e-9dfe-fcb68b30ed2f
0aee46ea-2869-4dea-ac6a-7b807fb15488
0282c355-ff4a-4066-b6e6-623fce653cf0
b87f3f14-9cef-4dc6-a069-243d9ea3b686
d40eb2c4-7093-4093-ab7a-04379bb0614d
f8aca5ad-ba8d-4417-bfc1-4c8d88a2dacd
4e994038-ee9c-4402-a173-e3931626e209
bd72ae90-a2ff-42ed-b5b2-99df2d418542
0810e061-94cc-4b71-ba4a-10ba1a3461db
03f2c5c7-a1ca-43c8-9991-712950d42258
0d96be23-f778-472d-8048-4c1fa526c39b
1ae96799-a223-4260-a4a9-7e070d7bafd8

**Mar. 2021** 

82805794-0990-4340-a6ac-4797eb2e1fc0
44f34ce2-4d16-4e9d-8589-beb0360ccb73
a225e383-297e-4136-8652-cb9f04d2d387
ce2f29ea-dcf1-44e0-a998-a81a8d369a74
812a5d9d-cc61-43b0-88ba-2fcf5e027a56
41ef8609-e6b5-4890-bc17-f0d892145aa6
e6bb2722-3006-44f0-8b70-beb779177fe0
0af6b64f-9344-452b-b4c9-6471dd46bd52
86a973db-1be0-42d1-bf4c-ad767206d007
659458fa-6981-4b70-9230-2f0d9ef7b174
74cf2f23-e940-443b-b7a4-ffc0923a6f80
0d65041d-03c3-4f44-83bf-6ebecb3b8063
b5c0757f-d2de-411a-8990-09d54f3858d0
4fc096bb-1ebf-424f-a076-22edb9560fdc
ad3a49ac-8a21-4ef7-8cf5-2237f8410cfa
ebde4b33-8c2e-44bf-9e67-ca92670ad34a
4b026414-ed5b-409c-8480-3caf3e005a5b
6b69a4f4-f9bc-4982-9292-3f17363e0916
068693dc-4d67-4d01-9a93-5da868ebab01
b0ca0cc8-e25a-4572-9554-731afa5fc2bc    

The following file contains extracted records with messages from VAMF, most of which are 'bad gateway' messages:[19856_request-eligibility-criteria.txt](https://app.zenhub.com/files/133843125/7f28584c-5c55-4de7-b9dc-c9789fa8e832/download)
