### ISSUE TITLE
VAOS::AppointmentRequestsService#get_requests - VAMF returning status 500

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#19859]
#### As of this 02/10/2021 (02/03/2021-02/10/2021) there were 33 occurrences of this error.

* URL: `/var/VeteranAppointmentRequestService/v4/rest/appointment-service/patient/ICN/xxx/appointments`

Team will investigate Sentry, Cloudwatch and the vets-api code-base to determine root-cause of this issue.

#### Deliverables
* A brief summary of the the results including any data that will help VAMF in identifying the issue.
* Include any supporting documents as attachments (e.g. spreadsheet, etc...).
* A list of any tickets that were opened in Jira.

**Comment by cferris32** [comment]
There were 246 instances of 500 errors on the appointments endpoint from Feb 1, 2021 to March 11, 2021. Multiple request ids were analyzed to look for a pattern in the failures. No discernible pattern in the error responses were found, with the response payloads generally containing some variation of a BackendServiceException or a 500 Bad Gateway HTML segment. Attached below is a complete log of the relevant records for this time period.

[https://app.zenhub.com/files/133843125/6d6a9d6a-9c13-4b02-93ff-3bfe76927fdf/download](https://app.zenhub.com/files/133843125/6d6a9d6a-9c13-4b02-93ff-3bfe76927fdf/download)
