### ISSUE TITLE
Access for Arnaud Tako

### ISSUE THREAD

**Issue by takoarnaud** [department-of-veterans-affairs/va.gov-team#19853]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Arnaud Tako
- Please Provide your email.
   > arnaud.tako@adhocteam.us

- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > vsp-operations team, Sr Software Engineer, Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3EvD4pIonys8qBAb6bReVwFA2AC8ux8M9/TJeUnKnk4btEbN0V+R5aP7W7f+CYSyfzOf3Q2utxyQUGDzS41VxxoTbvVKpO8yiQuOHnyh0qN/qcVSUcvWhiFwjAi9+rbyB4OHpoB/hvobEUb3AqG1bvFPgUNTfdMyYdGTlxvcVkhJeqE/wiGoQhcgtU4qOBnQ9gTFZClzzQhrPsmLAr7R6t8YNP1LeJtvcUOAS09WuJPyF7w5iMCk994EbGgj9M3hXP1JIhd+11PVBYDpet8ajikOc8+33UCeaXL9qPGOqOz2AH/FzzjlPMa1Umkwbf6u22Dlzlh54fRSwDbFoD+7w1xnmSVF9AveQldb9mHy3ApPS5R3Y41QyjCMrTxRxz6y1U3uWnj6P7P57fXHm4jkIcxuNv/GK+HKz0Ubsilv3ijJnWjYTOGJyDKgpYzsvM/66thKX2Q3RQjgJv3TA8geTv7bTrgyTk5eMBa9gu2rLFueH5xf/bJ8qbHTQBstti3w80NHgSXyURO8aQce9oll1PCy796ESZtt/vlZpapYd1mSSx19IZn7qbBY7c1c1Q6K8sGT4u8N9U1wt1H4NmveQXNoytQ2+UI10r8IQeDo6McUresElSiNHS59DAEYw26wNAuRsHBY0MtlaAPLSTMsjTArYPIm2sEc9dADXvjnGqw== arnaud.tako@adhocteam.us

```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why?

**Comment by jsev-io** [comment]
cc @Jeff-Hayter 
Arnaud, username @takoarnaud, is a new member of the VSP Operations Team 
Requesting approval for AWS Access

**Comment by jhouse-solvd** [comment]
@Jeff-Hayter - just bumping for visibility. we hope to add our team member @takoarnaud  to AWS whenever possible. pending your approval. Thank you, sir!

**Comment by mleclerc00** [comment]
We still waiting on approval for this?

**Comment by Jeff-Hayter** [comment]
@mleclerc00 Approved for AWS.

**Comment by mleclerc00** [comment]
Thanks, I will work on this shortly
