### ISSUE TITLE
[Discovery] Separate CMS build from vets-website

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#1985]
## Problem Statement
As an engineer separating out the CMS concerns from the build process, I need to understand what all the pieces are and how they fit together so I can ensure the pipeline is stable at the end of it.

## Goals
- The problem is clearly defined
- Every place CMS concerns are introduced to `vets-website` is documented
- A plan is in place to get the work done

## Acceptance Criteria
- [ ] Pain points with the current approach are captured in a comment
- [ ] All the CMS touch points are documented in a comment
- [ ] An RFC is drafted for how to isolate the CMS concerns

**Comment by meganhkelley** [comment]
This is tracked as part of #2719
