### ISSUE TITLE
VAOS::AppointmentRequestsService#get_requests - VAMF returning status 502

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#19851]
#### As of this 02/10/2021 (02/03/2021-02/10/2021) there were 134 occurrences of this error.

* URL: ` /var/VeteranAppointmentRequestService/v4/rest/appointment-service/patient/ICN/xxx/appointments`

Team will investigate Prometheus, Cloudwatch and the vets-api code-base to determine root-cause of this issue.

#### Deliverables
* A brief summary of the the results including any data that will help VAMF in identifying the issue.
* Include any supporting documents as attachments (e.g. spreadsheet, etc...).
* A list of any tickets that were opened in Jira.

**Comment by ajmagdub** [comment]
The following are the summary results of the Redis cache of the Rails API server logs 
for VAMF 502 errors when accessing the endpoint:
`/var/VeteranAppointmentRequestService/v4/rest/appointment-service/patient/ICN/xxx/appointments`

| Date               | count              |
| ------------- | ------------- |
|  20210201      |         4           | 
|  20210202     |       24            |
|  20210204     |         1             |
|  20210208     |         5            | 
|  20210209     |         2            |
|  20210210      |        4            |
|  20210212      |        7            |
|  20210216      |        3            |
|  20210217      |        4            |
|  20210219      |      14            |
|  20210222      |        1            |
|  20210223      |        2           |
|  20210224      |        6           |  
|  20210227      |         1           |
|                         |                      |
|  20210301      |          1            |  
|  20210304     |          5            | 
|  20210305     |        11            |      
|  20210306     |          4            |
|  20210307     |          7            |
|  20210308     |        10            |
|  20210309     |          4            |
|  20210310      |       15            |
|  20210312      |          1             |
|  20210313      |          2            |
|  20210314      |          1            |
|  20210315      |          4           |
|  20210316      |          4           | 
|  20210317      |          1            |

attached is a sample of appointments 502 errors extracted from CloudWatch. The Bad Gateway returned from VAMF do not  point to a systemic error from VAMF.
[VAMP-appt-502.txt](https://app.zenhub.com/files/133843125/c6f3d581-9a14-4052-bb28-48616a4d65ee/download)
