### ISSUE TITLE
[BE] rename app/models/async_transaction/vet360 folder and classes

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#19858]
main issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18258
rename `app/models/async_transaction/vet360` folder and classes

**Comment by lihanli** [comment]
@erikphansen @sanlouise do you know if this change to va profile transactions will break anything on the frontend? both `type` attributes will be changed

### old response
```JSON
{
  "data": {
    "id": "",
    "type": "async_transaction_vet360_address_transactions",
    "attributes": {
      "transactionId": "b6459e8f-7333-4bd1-a64e-0c102c316542",
      "transactionStatus": "RECEIVED",
      "type": "AsyncTransaction::Vet360::AddressTransaction",
      "metadata": []
    }
  }
}
```
### new response
```JSON
{
  "data": {
    "id": "",
    "type": "async_transaction_va_profile_address_transactions",
    "attributes": {
      "transactionId": "b6459e8f-7333-4bd1-a64e-0c102c316542",
      "transactionStatus": "RECEIVED",
      "type": "AsyncTransaction::VAProfile::AddressTransaction",
      "metadata": []
    }
  }
}
```

**Comment by erikphansen** [comment]
Actually, yes :( We use `attributes.type` in one place. I'll see if I can make that more flexible...

**Comment by erikphansen** [comment]
@lihanli [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16029) will make our FE flexible enough to handle `attribute.type` values that contain either `Vet360` or `VAProfile`

**Comment by erikphansen** [comment]
Ha, I thought that this was a PR, not an issue. I guess I didn't need to rush my fix 😆
