### ISSUE TITLE
Triage Form526 Front end validation errors

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#19860]
[In sentry  ](http://sentry10.vfs.va.gov/organizations/vsp/issues/241/events/?query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdisability%2Ffile-disability-claim-form-21-526ez%2Freview-and-submit&statsPeriod=14d). we see that veterans see schema validation errors when they attempt to submit a form 526 about 500 times a day.  

I'd think that https://github.com/department-of-veterans-affairs/va.gov-team/issues/2138 is a fix, but we might also need validators that notify as a veteran progresses through the form.

# Acceptance Criteria
- [ ] Triage the most common validation errors and create issues to address each

**Comment by Mottie** [comment]
Closing this issue in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/27926 epic.

The work in #2138 mentioned above was merged and now available _only_ in staging. We're working on getting research done to implement this in production
