### ISSUE TITLE
Redirects in Life Insurance based on parity work 

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#1986]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15519*

**Goal**
After all parity work work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
- [x] Determine if all parity changes are complete/live and log tickets that track the approval status
- [x] Validate previously documented redirects and update as necessary
- [x] Create a new parity redirect issue in va.gov-team repo with the list of redirects and reference the original issue and the content approval ticket
- [x] Close the old issues in vets.gov-team repo and reference the new issue in va.gov-team repo
- [x] Communicate upcoming redirects to stakeholders prior to implementing
- [ ] Assign out tickets to front-end or devops as appropriate
- [ ] Validate redirects in prod and update documentation when complete

Legacy URL  |  Redirect to
-- | --
www.benefits.va.gov/insurance/disabledvet.asp | /life-insurance/options-eligibility/
www.benefits.va.gov/insurance/sgli.asp | /life-insurance/options-eligibility/sgli/
www.benefits.va.gov/insurance/sglidisabled.asp | /life-insurance/options-eligibility/sgli/ 
www.benefits.va.gov/insurance/fsgli.asp | /life-insurance/options-eligibility/fsgli/ 
www.benefits.va.gov/insurance/tsgli.asp | /life-insurance/options-eligibility/tsgli/ 
www.benefits.va.gov/INSURANCE/apply-for-VGLI.asp | /life-insurance/options-eligibility/vgli/
www.benefits.va.gov/insurance/vgli.asp | /life-insurance/options-eligibility/vgli/ 
www.benefits.va.gov/insurance/vgli_rates_new.asp | /life-insurance/options-eligibility/vgli/ 
www.benefits.va.gov/INSURANCE/getvgli.asp | /life-insurance/options-eligibility/vgli/
www.benefits.va.gov/insurance/s-dvi.asp | /life-insurance/options-eligibility/s-dvi/ 
www.benefits.va.gov/insurance/vmli.asp | /life-insurance/options-eligibility/vmli/ 
www.benefits.va.gov/insurance/abo.asp | /life-insurance/totally-disabled-or-terminally-ill/

**Comment by mnorthuis** [comment]
@jenniferlee-dsva @Karak888 
All parity work for life insurance is done per this issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16293.
This ticket covers just the redirects related to the parity work.  Legacy rewriting will be handled separately. 

This list has not been sent to the Life Insurance stakeholder for review yet.  Can you confirm that that contact is still Lori Hamilton and let me know how we should communicate this to her?

**Comment by mnorthuis** [comment]
Blocked until ops/front end team can determine approach for implementation of redirects.

**Comment by mnorthuis** [comment]
@Karak888 these redirects are vetted and can be scheduled for implementation once your team has communicated to the stakeholder.   Please use this issue for implementation.

**Comment by Karak888** [comment]
this can be implemented @ncksllvn @lunascoop - but communication can go out with date but won't happen before code freeze.

**Comment by lunascoop** [comment]
@ncksllvn @jenniferlee-dsva @Karak888 Stakeholder comm sent out. **01/06/20** is the expected redirect date.

**Comment by lunascoop** [comment]
@kelsonic @ncksllvn @mnorthuis I have validated that these redirects have gone live and will notify the stakeholders. Closing ticket.

**Comment by mnorthuis** [comment]
I don't see any of these redirects live yet and wasn't aware we were ready to do life insurance.  Can you please confirm the status @lunascoop?

**Comment by mnorthuis** [comment]
complete
