### ISSUE TITLE
Missing services in CMS export version of VAMC pages

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#19864]
# Description

Due to either a transformers bug or an issue with the CMS export data, some services are missing on VAMC pages, e.g.

/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

To see which services are missing, run the following Javascript command in the Chrome console:

```js
contentData.fieldLocalHealthCareService.map(s => s.entity?.fieldRegionalHealthService?.entity.fieldServiceNameAndDescripti?.entity?.name)
```

<details><summary>Graphql</summary>

![VA_Pittsburgh_Health_Care___Pittsburgh_VA_Medical_Center-University_Dr](https://user-images.githubusercontent.com/80267/107703429-9de0b200-6c89-11eb-868d-99fb9f407f93.png)
</details>

<details><summary>CMS Export</summary>

![VA_Pittsburgh_Health_Care___Pittsburgh_VA_Medical_Center-University_Dr](https://user-images.githubusercontent.com/80267/107703490-b51f9f80-6c89-11eb-965d-ff8f29f23d2c.png)
</details>

# Acceptance Criteria

Find root cause of the missing service data and fix if possible, or work with CMS team to resolve.

**Comment by mmiddaugh** [comment]
Archiving this issue but keeping track by linking in Facilities Transformer support (collection of issues) #17956
