### ISSUE TITLE
Onboarding screen: update formatting of user's name

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19872]
## Acceptance Criteria
1. On Onboarding Screen #1, update the formatting of the user's name so only the first letter of each word is capitalized, and all other letters are lowercase
     - Ex: Update JESSE to Jesse
     
## Screenshots
Onboarding screen for vets.gov.user+49@gmail.com:
![Screenshot_20210211-145033_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/14e1e4ce-ee49-44f9-9f21-f344bfb71d43)

Profile screen for vets.gov.user+49@gmail.com, where the name is correctly formatted:
![Screenshot_20210211-144924_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/fe790928-8e9e-40cc-988d-a2fd64cd7edd)!

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 2/16/2021 - Only first letter of name is capitalized.  Closing.
