### ISSUE TITLE
Connect BigQuery<>ForeSee

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#19880]
## Issue Description
Connect BigQuery to ForeSee so that VFS teams can get historical information on Veteran satisfaction with VA.gov.

Discovery work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19876

---
## Tasks
- [ ] Set up ForeSee data in BigQuery to pull new survey data

## Acceptance Criteria
- [ ] We can get all historical ForeSee survey question and answer data

**Comment by JasonTheBearded** [comment]
Google Cloud Bucket set up to receive foresee export files. Once files loaded will set up script to load foresee files to BigQuery tables

**Comment by joanneesteban** [comment]
Files Uploaded to BigQuery:
| Data | File Names |
| --- | --- |
| VA Main Intercept Survey 2017 - Answer Mapping | CustomExtract-AMapping-VA Main V2-2017-031221.csv |
| VA Main Intercept Survey 2017 - Responses | CustomExtract-Data-VA Main V2-2017-031221.csv |
| VA Main Intercept Survey 2017 - Question Mapping | CustomExtract-QMapping-VA Main V2-2017-031221.csv |
| VA Main Intercept Survey 2018 - Answer Mapping | CustomExtract-AMapping-VA Main V2-2018-031221.csv |
| VA Main Intercept Survey 2018 - Responses | CustomExtract-Data-VA Main V2-2018-031221.csv |
| VA Main Intercept Survey 2018 - Question Mapping | CustomExtract-QMapping-VA Main V2-2018-031221.csv |
| VA Main Intercept Survey 2019 - Answer Mapping | CustomExtract-AMapping-VA Main V2-2019-031221.csv |
| VA Main Intercept Survey 2019 - Responses | CustomExtract-Data-VA Main V2-2019-031221.csv |
| VA Main Intercept Survey 2019 - Question Mapping | CustomExtract-QMapping-VA Main V2-2019-031221.csv |
| VA Main Intercept Survey 2020 - Answer Mapping | CustomExtract-AMapping-VA Main V2-2020-031221.csv |
| VA Main Intercept Survey 2020 - Responses | CustomExtract-Data-VA Main V2-2020-031221.csv |
| VA Main Intercept Survey 2020 - Question Mapping | CustomExtract-QMapping-VA Main V2-2020-031221.csv |
| VA Main Intercept Survey 2021-01-01 - 2021-03-14 - Answer Mapping | CustomExtract-AMapping-VA Main V2-2021-031521.csv |
| VA Main Intercept Survey 2021-01-01 - 2021-03-14 - Responses | CustomExtract-Data-VA Main V2-2021-031521.csv |
| VA Main Intercept Survey 2021-01-01 - 2021-03-14 - Question Mapping | CustomExtract-QMapping-VA Main V2-2021-031521.csv |
| VA 5 Star Survey - 2019 | VA.gov_Stars_Only_-_1090-0008__2019_respondents_2021-03-12.csv |
| VA 5 Star Survey - 2020 | VA.gov_Stars_Only_-_1090-0008__2020_respondents_2021-03-12.csv |
| VA 5 Star Survey - 2021-01-01 - 2021-03-14 | VA.gov_Stars_Only_-_1090-0008__20210101-20210314_respondents_2021-03-12.csv |

**Comment by JasonTheBearded** [comment]
@joanneesteban All foresee files loaded into BigQuery.

**Comment by JasonTheBearded** [comment]
All files loaded, closing ticket.
