### ISSUE TITLE
Troubleshoot auth issues with DSL and MHV logins

### ISSUE THREAD

**Issue by ayushchak** [department-of-veterans-affairs/va.gov-team#19889]
As a vet, I would like to be able to log in with different accounts, but it's not clear what the issue is here. Why can't users see any information on the mobile app when they can see the corresponding information on staging.va.gov?
Use case: Greg Anderson (see Slack DMs for test login details or contact Ayush)

**Comment by lexicalninja** [comment]
should be complete with back end change and our internal user indicated that all data matched up on all 3 accounts
