### ISSUE TITLE
Query Time Report

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#19894]
## Description

There is a request to have a report that shows the time it takes queries to run so we can identify which ones need to be optimized.

## AC
- [ ] Report is available that shows longest running queries at the top

**Comment by alexpappasoddball** [comment]
@ericboehs This is one of the things we talked to Dror about and should groom and prioritize it appropriately.

**Comment by ericboehs** [comment]
I reached out to ops about this. They said Datadog does have some integration with Postgres/RDS but [powa](https://powa.readthedocs.io/en/latest/) would work better.

**Comment by ericboehs** [comment]
Should we add [pghero UI](https://github.com/department-of-veterans-affairs/vets-api/pull/5531)? We'd auth with same auth for Sidekiq/Feature Flipper.

**Comment by ericboehs** [comment]
Another option here is to just push the stats over to prometheus/datadog via StatsD similar to how we do [Sidekiq stats](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/sidekiq_stats_job.rb#L12-L19).

**Comment by ericboehs** [comment]
Investigate if we can get this from RDS already.
