### ISSUE TITLE
[Site Scheduled Maintenance] EVSS Maintenance Wednesday, 3 March 9:00-10:00pm ET 

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#19891]
## Why you're here 

There is a planned **maintenance outage scheduled for Wednesday, March 3 from 9-10pm ET.**  Details are as follows:

- EVSS will go-live to Production with the R17.12 Release (CHG0164267 / RLSE0014272) on Wednesday, 17 February from 9:00-10:00pm ET (pre-validation will begin at 8:30pm ET). eBenefits (EBN), Stakeholder Enterprise Portal (SEP) and va.gov-consumed services will be unavailable during this event. Below is the timeline.
- Important: EVSS Depends on the following partner systems to be available from 8:30pm ET until 10:00pm ET to cover our full pre and post release validation window: BDN, BGS, CORP, DMDC/DS Logon, IAM AcS, MVI, OGC, VAAFI, VBMS, VDR, VIS, VRS. 
- If no issues are encountered, the outage will last approximately 15 minutes (from 9pm to 9:15pm ET).

---

### Frontend engineering support 

- [X] **Other**
   * Determine if we need to invoke the [Sitewide system maintenance downtime banner](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/banners/banner-alerts.md) and codify decision here.
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Wednesday, Feb. 17 from 9-10pm ET.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: *Public Websites*
- DEPO product owner: *John Hashimoto*
- Product manager: *Brian Lloyd*
- Designer: *Laurel Lawrence*
- FE engineer: *Nick Sullivan*
- Product/team Slack channel: *vsa-public-websites*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by johnhashva** [comment]
@brianalloyd putting this on our radar for next week.  I'm trying to get more clarity from the EVSS lead who sent this notification -- will the outage last one hour or 15 minutes.  The notice strikes me as confusing.   In either case: I want to confirm from Nick/Kelson that the specific authenticated products impacted will have "modal maintenance messages" invoked -- and that lessens the need for us to go sitewide.

**Comment by johnhashva** [comment]
@brianalloyd just got some clarity from the EVSS team about duration:  _We allocate 1 hour in case we run into an issue, but 99% of the time we are only down about 15 minutes. This is because we have 2 production domains (one is “dark” and one is “live”). We deploy our new releases to our “dark” prod domain in advance of our “go-live” events and VA business tests. Then on “go-live” evenings, all we have to do is run a couple of scripts to swap our dark prod domain with live prod domain, thus making the previous dark domain live which contains the new release. We validate after the domain swap, so if there are issues observed, we can quickly swap the domains back._

**Comment by brianalloyd** [comment]
Thanks @johnhashva the additional clarity from EVSS helps a great deal in ensuring this is handled appropriately, thanks for including in this ticket.  I'm going to loop in @ncksllvn and @kelsonic to assess the specific authenticated products impacted will have "modal maintenance messages" invoked as described above.   We can also review this during Tuesday's SU to ensure we're aligned on actions forward.

**Comment by johnhashva** [comment]
@brianalloyd Tonight's maintenance event has been canceled due to the weather in Texas and impact to operations resources.  Pushing off until early March.

**Comment by johnhashva** [comment]
@brianalloyd let's keep this ticket open to re-use when this event happens in March.  Good for awareness, since we've decided that a HP maintenance banner **will not be necessary.**

**Comment by brianalloyd** [comment]
@johnhashva sounds good, placing in our backlog in support of March review.  Thanks.

**Comment by johnhashva** [comment]
Closing -- This site maintenance event occurred without incident.

All,

The EVSS Sustainment combined R17.12/R17.13 release has completed successfully.

CHG0170442 / RLSE0014369

v/r

“B”

Bonnie A. W. Craig
Configuration/Release Manager (EVSS & NBEKRSS)
9th Way Insignia
410.279.4628 (m) | 443.837.5554 (o)
