### ISSUE TITLE
IA Feedback - Usability Testing Prep - My VA

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#19898]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- The standard mobile breadcrumb only has 1 segment - the previous page.  On the My VA page, the mobile breadcrumb would be a single link to "Home".
- Sign in is required to get to "My VA", the prototype doesn't represent this.  Either the prototype should show that a user is already signed in, or, it should simulate a sign in flow after clicking "My VA". 

**Should:**

**Consider:**
- On mobile, the experience is a long list of stacked items, and could be a challenge to decipher what/where the individual sections are.  Consider testing whether users understand/what they expect should all be on the page, whether they scroll and clearly see/understand the individual sections.  May be helpful to add an "on this page" type component. 

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by Samara-Strauss** [comment]
@tressaellen has all of this feedback been addressed?

**Comment by tressaellen** [comment]
@Samara-Strauss yes! 

@mnorthuis we updated the sign-in screen in the prototype, and the breadcrumb is updated. I'm also following up with development as well to make sure that's reflected in the build. 

> On mobile, the experience is a long list of stacked items, and could be a challenge to decipher what/where the individual sections are. Consider testing whether users understand/what they expect should all be on the page, whether they scroll and clearly see/understand the individual sections. May be helpful to add an "on this page" type component.

In testing, users were easily able to find each of their sections so I think we should be okay without the "on this page" component. If it ends up being an issue in future testing then we can revisit this.

**Comment by Samara-Strauss** [comment]
Sorry for the delay in reply — this ticket looks good to close, so I'm gonna close it. Please reopen if necessary.
