### ISSUE TITLE
List Loop Component Work 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#19895]
This Epic will be used to compile or group the various pieces of work needed on adding List Loop to the Design System. 

As discussed, we will create a Simple or Basic List Loop component and then a Complex List Loop component. Tasks for each version will consist of the following: 

- Audit of existing uses cases
- Design of a standard version of the component
- Documentation describing guidelines and usage 
- Development of the component with reusable code

**Comment by humancompanion-usds** [comment]
@caw310 - I'm curious why this one is in the Reviewed/Needs prioritizing bucket. In my mind List and Loop is 4 distinct patterns and only one of which is implemented in the Forms library. I don't see how it could be turned into a component. Seems like the issues were completed as well. Perhaps this should be closed?
