### ISSUE TITLE
Scheduled for 03/03: Redirect Request: Life insurance calculator and uninsurable legacy pages

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#19892]
### Description
On the left nav in the life insurance hub, we updated the links for **Deciding how much life insurance to get** and **Life insurance if you have preexisting conditions** to go to new life insurance articles in Resources and Support. They used to link to two legacy pages, the **life insurance calculator** and **uninsurable**, which we'd like to link to those same articles in Resources and Support.

### Requesting team info
Sitewide Content

### Implementation date
Date new URL(s) will be live: *Pages are live*

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing : seven (7) business days after stakeholder notification

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.benefits.va.gov/INSURANCE/introCalc.asp | https://www.va.gov/resources/deciding-how-much-life-insurance-to-get/
https://www.benefits.va.gov/insurance/lifeins101.asp |  https://www.va.gov/resources/deciding-how-much-life-insurance-to-get/
https://www.benefits.va.gov/INSURANCE/uninsurable.asp | https://www.va.gov/resources/life-insurance-if-you-have-preexisting-conditions/
https://www.benefits.va.gov/insurance/dividends_options.asp | https://www.va.gov/resources/life-insurance-dividend-payment-options/

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [ ] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by lunascoop** [comment]
Posting Slack comment here:

> Good morning @Mikki. I created a redirect request ticket for 2 life insurance pages, but wasn't sure if I should add a 3rd legacy URL. Should we also redirect https://www.benefits.va.gov/insurance/lifeins101.asp, which is the main page? It includes a link to the life insurance calculator page (which is already included in the redirect ticket) and a link to the VGLI Comparison Questionnaire page, which we also directly link to in the left nav under Options and eligibility (see screenshot).

 
<img width="1035" alt="Screen Shot 2021-02-12 at 10 02 32 AM" src="https://user-images.githubusercontent.com/42546515/107825387-034ba600-6d51-11eb-9e8b-a5bfd483024a.png">

**Comment by mnorthuis** [comment]
@lunascoop Yes, looks like that 3rd legacy URL was intended to be redirected to the new calculating your needs page as well per the original redirect ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2213. 

I added that URL to the original description above, all of these have been reviewed and are ready to go. PLEASE ENSURE THAT THE REDIRECTS ARE NOT CASE SENSITIVE, as legacy pages/links also exist with different casing (i.e. /INSURANCE versus /insurance)


@bethpottsVADEPO @DanielleThierryUSDSVA  FYI, I am not tracking all pages/URLs launched within Resources and support, and therefore not logging/keeping track of legacy pages that are redirected to those articles.

**Comment by bethpottsVADEPO** [comment]
@lunascoop I should hear back from Lori Hamilton tomorrow about who else to include on your redirect email. I wanted to ask about the third new life insurance page we put up too--is this one getting redirected?: https://www.va.gov/resources/life-insurance-dividend-payment-options/

**Comment by bethpottsVADEPO** [comment]
@lunascoop Here's who Lori identified for the redirect email for LI:
**Note:** Please _don't_ send the mail to dennis.nicastro
mychaellee.askew@va.gov
larry.eby2@va.gov
ruth.berkheimer@va.gov

And from the original list of redirects in the ticket Mikki linked to, I do see dividend-payment-options listed, so please add that to the email too (4 total redirects to our 3 new pages):

https://www.benefits.va.gov/insurance/dividends_options.asp | /life-insurance/dividend-payment-options/

**Comment by bethpottsVADEPO** [comment]
Also send it to Lori! @lunascoop

**Comment by lunascoop** [comment]
Hi @ncksllvn and @kelsonic these URLs are scheduled to be redirected on **03/03**. Stakeholders are being notified. @bethpottsVADEPO

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/16133 Won't merge until morning of 03/03, redirects will go out following the daily deploy on 03/03.

**Comment by lunascoop** [comment]
I've validated that these redirects are live. Closing ticket and notifying stakeholders. Thanks everyone!
