### ISSUE TITLE
[FE] Profile: Remove "Your" from "Your Profile"

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19890]
## Background
See ticket: [Content/IA] Evaluate new My VA title #13738

[Slack conversation](https://dsva.slack.com/archives/C909ZG2BB/p1600386040001800), there were some nomenclature/content inconsistencies pointed out that are worth resolving.

- Content recommends removing "Your" from the Profile breadcrumb and the left nav, So these both would now read "Profile" not "Your profile"

![image](https://user-images.githubusercontent.com/60523453/107777994-86e5a280-6d11-11eb-91e2-948a9901dd59.png)

## Tasks
- [ ] Remove "Your" from "Your Profile"

**Comment by Samara-Strauss** [comment]
We can add this ticket for next sprint. No immediate action needed.
