### ISSUE TITLE
Create list of engineering best practices we want to communicate w/VFS in onboarding

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#199]
## Stories
As a VFS team Developer, I need to know what will be reviewed/expected in future code reviews, so that I can integrate best practices from the beginning, thus hopefully also getting through code reviews more quickly.

As a VSP Developer, I need submitted PRs to adhere as much as possible to VSP standards, so the reviews can go more quickly and so I can focus my attention on more nuance and avoid missing errors due to review fatigue.

## Goals
Consolidate key engineering best practices and expectations into a template of talking points that we would want to convey to new VFS team engineers in a 60 minute engineering-focused onboarding meeting.

## Recommended talking points
- How to avoid PR becoming large/Expectations on PR size
- Feature-flag-based development
- How to used Review instances
- Aiming to integrate and deploy code at around a weekly basis
- How to get follow-up help or guidance (esp during this time when documentation is in iteration mode)

## AC
- [x] Talking points have been documented in Github or relevant documentation source (maybe the Onboarding Template Deck)
- [x] Talking points don't diverge from rest of VSP alignment / future plans on what we hope to see of VFS team engineering
- [x] The document created is referred to/accessible from the onboarding material for new teams

## Def of Done
- [x] AC is complete
- [x] Shared w/DSVA for review

**Comment by rroueche** [comment]
This is related to #106 but is more tightly scoped to getting in place some talking points and/or examples to go over with Engineers from a new VFS team as a part of their initial onboarding.

**Comment by rtluu** [comment]
@rianfowler https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/13

can you give this a  👀

**Comment by hpjaj** [comment]
Associated PRs:

- https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/13 - merged
- https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/14 - merged
- https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/15 - in code review

**Comment by accbjt** [comment]
This was actually already done. Henry finished this up and we integrated it into the system.
