### ISSUE TITLE
General Analytics Request for [VAOS Product/UX Questions]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19902]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Lauren Ernest, Peter Russo
    
- What team/project is this work for?
    - VAOS general user behavior analysis
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)? n/a

## Analytics to Track Down
n/a

## Which Product Questions are you trying to answer?

- Are we able to see how much time a user spends on a given page?
- Can we see when a user abandons a page after receiving an error?

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics

- Funnels https://va-gov.domo.com/page/443732151
- Error events https://va-gov.domo.com/page/1315231862/kpis/details/655651605

## Additional Comments
Some of our pages include options for user to choose from (e.g. calendar with times, list of providers) which may take a user time to make a selection. Particularly with a direct book calendar page, our hypothesis is the user will abandon the flow if they can't find a time.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks, @laurenernest ! We'll let you know when we're able to triage this & pulled it into our sprint.

**Comment by joanneesteban** [comment]
Hi @laurenernest ! We're anticipating being able to pull this into another sprint (March).

To help us plan, can you let us know if you're hoping to see this data in over time (check in on it every week/month), or are you looking to see the data one time? Or, are you hoping to get support with reading the data already in the dashboard according to your product questions above?

**Comment by laurenernest** [comment]
If the answer to either of our 2 insights questions is "yes" then the next question would be "how?"
- If it's something available in the dashboards we currently have, then it would be support for reading that data. 
- If it's not something we can see from our current dashboards, then time spent on page is something we'd monitor over time (likely bi-weekly or monthly) and abandonment after error would be more targeted one-off reports of that behavior (that we'd likely check in on after making adjustments)

**Comment by joanneesteban** [comment]
@laurenernest , doing some ticket clean up: is this support captured in the [KPI dashboard ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26851) that was recently opened?

**Comment by laurenernest** [comment]
> @laurenernest , doing some ticket clean up: is this support captured in the [KPI dashboard ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26851) that was recently opened?

Not exactly. The scenarios are more of specific metrics with as they relate to the funnels. For example, of a step abandonment total, how many times was an error shown. This would help distinguish those who abandoned because of a technical issue vs usability.

**Comment by joanneesteban** [comment]
Thanks for the clarification, @laurenernest! Would you be able to go [our office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguide-5.AdditionalAnalyticsSupport) next week? We can go over how to grab these metrics then! CC: @laurensimpson14

**Comment by laurenernest** [comment]
Thanks for the help everyone!

Segment created: Sessions with VAOS error

Exits with new segment: https://analytics.google.com/analytics/web/#/report/content-exit-pages/a50123418w177519031p176188361/_.useg=user_0u8EUltTVmBBRaw6O2vbw,builtin1&explorer-table.filter=schedule&explorer-table.plotKeys=%5B%5D/

Custom report: Errors on VAOS pages https://analytics.google.com/analytics/web/#/my-reports/FbSVU-MKSdmW-TCMjWre8g/a50123418w177519031p176188361/304-table.secSegmentId=analytics.pagePath&304-table.plotKeys=%5B%5D/
