### ISSUE TITLE
CT: Tag not persisting from search results card to profile.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#19907]
## What happened?
The 'Women only' tag on the Spelman College card displays in the search results but not on the school profile page.

## Specs:
- Device: Mac
- Browser: Chrome
- Test User: N/A

## Steps to Reproduce
- URL: 
- Search Results: https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=Spelman
- Profile Page: https://staging.va.gov/gi-bill-comparison-tool/profile/31002911

## Desired behavior
The applicable tags are supposed to show on both the search results page and the school profile page.

**Comment by delli-gatti-michael** [comment]
PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/16062

**Comment by ksantiagomorgan6** [comment]
Test passes, fix is in staging and prod
