### ISSUE TITLE
General Analytics Request for [VAOS-Missing wk of 1/31 data in Domo]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#19904]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Lauren Ernest
    
- What team/project is this work for?

    - VAOS KPIs
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)? week of Jan 31, 2021

## Analytics to Track Down
Scheduling completion

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
https://va-gov.domo.com/page/1769944412/kpis/details/1233396151
![Screen_Shot_2021-02-12_at_8_46_33_AM](https://user-images.githubusercontent.com/72046525/107796820-205f8500-6d0f-11eb-85cb-c04adb9fc641.png)

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Thanks, @laurenernest ! We'll let you know when we're able to triage this & pull it into our sprint. (Appreciate the screenshot! Very helpful!)

**Comment by joanneesteban** [comment]
@laurenernest Brian will look into the missing data for you this sprint!

**Comment by bsmartin-ep** [comment]
Data has been fixed @laurenernest.   

https://va-gov.domo.com/page/1769944412/kpis/details/1233396151

Closing...
