### ISSUE TITLE
Deploy CMS Export to dev

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#19909]
## Details 

CMS Export build output was added to S3 as part of #18407 

The next step is to have the CMS Export build output publish to the dev environment, so that people can start viewing and validating that output before we switch over from GraphQL. 

Related to & need to coordinate with:
* solution for adding comparison tool to build pipeline (discovery ticket #19156)
* rollback plan (#16482)

## To Do 
- [ ] Determine approach for how to do this
- [ ] Determine how we confirm it's the CMS Export build in dev (Chris & Tim have a solution for this)
- [ ] Message this change to necessary folks — announce in ToT & Slack **before this is released to dev**, and connect with VSP Ops re: anything they need to know

## Acceptance Criteria
- [ ] Staging and Production must continue to use GraphQL
- [ ] CMS Export build errors should not disrupt Staging & Production - GraphQL must continue as expected in those environments 
- [ ] GraphQL build will be continued to executed for dev, but dev.va.gov will display the output of CMS Export

**Comment by meganhkelley** [comment]
Notes from team mtg 

We can either make a change in the build process that we have, or we could make a change in the deployment process (to deploy the results of CMS Export build instead of GraphQL) - in that case we'd only change the deploy, not the build. Or we can change the build process and leave the deploy as is. 

Tim: The conditionals we have set up right now that are looking for CMS Export, replace them with vagovdev. That should do it. If we want to wire up a normal GraphQL dev build we can do that. The conditionals should already be set up. 

Eugene: Would that end up pushing the CMS Export build into the S3 key where the GraphQL build is currently? I was thinking more of the deploy approach -- modifying the devops repo.We could update which path it is from the archive S3 that gets pushed to the deploy S3 but I'm still investigating. 

Chris: May end up with an intermediate state of 6 builds (3 GraphQL, 3 CMS Export), and for each one of those we can deploy whichever one we want in whichever environment. Is that valuable in practice? 

Eugene: Also thought we might end up in that state. Maybe the 4th is temporary where we focus on the CMS Export build of the env we're currently testing. This also ties into rollback plan because the approach we determine here will affect how we would roll it back.

**Comment by meganhkelley** [comment]
@alexandec before closing this ticket (when applicable) could you please leave a comment or update the ticket body with info about the approach we used for this? We'll presumably use that info in order to create/refine tickets for pushing to staging & prod

**Comment by alexandec** [comment]
@meganhkelley sure, here's a summary of the implementation:

- Modify the vagovdev build to use CMS Export instead of GraphQL
- Modify the vagovdev build so it doesn't fail the entire build process when an error occurs
- Create a vagovdev-graphql build which runs in parallel and uses GraphQL. This build is not deployed -- it's for comparison purposes only
- Add a FORCE_LEGACY_GRAPHQL constant which is initially set to false. It can be set to true to force use of GraphQL in the vagovdev build. This allows us to easily switch back if we encounter issues with the CMS Export data

We could use a similar approach for staging and prod, except that we probably do want to fail the build on errors in those environments.
