### ISSUE TITLE
Quality Assurance Feedback - Usability Testing Prep - Authenticated Experience - MyVA 2.0

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#19913]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- As your prototypes begin to settle into more concrete forms, consider a few things as you develop your test plan --
1. Consider using the [Cypress Best Practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-best-practices-on-vsp.md) that we have collected here as you design your e2e test.
2. Your mobile first prototypes are great to see! Consider using the [`cy.viewportPreset()`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-best-practices-on-vsp.md#viewport-presets-cyviewportpresetpreset-orientation-options) helper that we created in order to automatically test and iterate through the most popular mobile viewports on the platform.
3. Please do use [TestRail ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance/testrail)to create your test plan.
4. I strongly recommend scheduling time into your project for exploratory testing. There is a markdown template for an exploratory test charter [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/manual-testing/exploratory-charter.md). And, a test template for ad hoc / exploratory testing is available in TestRail as well.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
N/A

**Should:**
N/A

**Consider:**
N/A

**Comment by Samara-Strauss** [comment]
Done ages ago. Closing!
