### ISSUE TITLE
Address errors - After turning the screen to landscape and then back to portrait, user is unable to scroll to top of screen again

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#19949]
## What happened?
Android:  (No longer happening in iOS) 
Enter an address that causes one of these errors to appear:

- 17698 - Error | Address recognition: confirm Unit Number
- 17700 - Error | Address Recognition: Add Unit Number
- 17695 - Error | Address Recognition w/ no suggestions

and rotate the device to landscape.  Then rotate the device back to portrait.  The user can no longer scroll to the top of the screen to see the mobile alert common component.

iOS:  Not an issue anymore.
Android:  Sometimes need to scroll down the page a little in landscape and then rotate back to portrait to get it stuck.  *** Android is sometimes intermittent.  When in landscape mode and the problem exists, sometimes the user can scroll down the page a bit and then rotate and it comes back to normal.

## Specs:
- Device: Samsung Galaxy Note 9

## Steps to Reproduce
- See above.

## Desired behavior
When rotating back to portrait, user is still able to scroll the complete screen.

## Acceptance Criteria
See above.

## Bug Severity
- 3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17695

But happens with #17698, 17700, and 17695

## Screen shot(s) and additional information

This shot is from an iPhone XR:

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/87c3287c-dba0-485f-90cd-e5cd0c978328)

**Comment by keli13** [comment]
Have not be able to reproduce with simulator or pixel 3 xl device.

**Comment by digitalken** [comment]
Still able to make this one happen, @keli13 .  Sending it back to you.

**Comment by digitalken** [comment]
PASS 6/18/2021 - Looks good now.  Closing.
