### ISSUE TITLE
[Epic] Resources and support content 1.1

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#19945]
## Content epic: Resources and support 1.1

Epic to organize RS content work for 1.1

**User story:** As a Veteran, family member or other beneficiary, I want a way to get my VA questions answered quickly. 

**Purpose of this epic:** 

- To 'migrate' legacy IRIS FAQs content into the new RS. 
- To 'migrate' other legacy tier 2 benefit-adjacent support content into RS.

**Comment by jenniferlee-dsva** [comment]
Hey - @bethpottsVADEPO @brianalloyd @johnhashva - I thought it might be helpful to gather the content tickets separately now from the PW 1.1 epic, so it's easier to manage remaining FE work vs. content work. (Since content work will continue well into 2021, after FE work has been completed.) 

This way, you can close out the PW epic when all the FE tickets are closed, since the content team now has their own "Sitewide content" flag.

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA Do you know if the few still-open stories on this 2020 epic are still viable, or can be closed? Thanks!

**Comment by mmiddaugh** [comment]
closing this issue
