### ISSUE TITLE
Remove moment from component-library

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#19954]
## Issue Description

The `moment` dependency is in [maintenance-only mode](https://momentjs.com/docs/#/-project-status/). This, combined with the fact that `moment` contributes to a significantly larger bundle size, are good reasons why we should switch to `date-fns` in the `component-library`. This transition has already begun: https://github.com/department-of-veterans-affairs/component-library/pull/33

---
## Acceptance Criteria
- [ ] Unused functions in `validations.js` file which rely on moment are removed
- [ ] Components which import `moment` (`<MonthYear>`, `<Date>`) are refactored to use `date-fns` and the standard Date object)
- [ ] `moment` is no longer a dependency in `component-library`

**Comment by k80bowman** [comment]
Existing [PR](https://github.com/department-of-veterans-affairs/component-library/pull/39). Needs update and work needs to be finished.
