### ISSUE TITLE
"Privacy Policy" capitalization error

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19956]
## What happened?
On the Settings page, the **Privacy policy** ListItem displays as **Privacy Policy**. Designs indicate that "policy" should not be capitalized.

## Specs:
- Devices: Any

## Steps to Reproduce
1. In the app, navigate to the Settings page and observe the **Privacy Policy** ListItem
2. Compare against the designs: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636883

## Desired behavior
1. The ListItem displays as **Privacy policy**, where only "Privacy" is capitalized

## Acceptance Criteria
See desired behavior

## Bug Severity
- 4 - Low

## Screen shot(s) 

![Screen Shot 2021-02-12 at 4.12.42 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ce0845a2-8ad2-4471-8ee1-32f55fa2e55b)

**Comment by digitalken** [comment]
PASS 2/22/2021 - As seen in Designs...  Closing.
