### ISSUE TITLE
Address Recognition - Confirm Unit Numbers - Accessibility issues

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#19952]
## What happened?
1.  Android isn't speaking the 'b' after the unit number. (See the screen shot.)

2. Hint for 'Edit Address' button shows: accessibilityLabel= “edit this address” in story.  Implementation says "Edit Address".

3. Accessibility hints for the 'Use this address' button seem to be copy/pasted from the Edit Address button. Gives the same hints.

## Specs:
- Device: 
For 1. Android Samsung Galaxy Note 9, Samsung Galaxy S7.  (I can hear the "b" announced with Google Pixel 3XL and Motorola Moto G7.)

For 2, 3.  All devices.

## Steps to Reproduce
- Generate the error screen and read with text reading software.

## Desired behavior
1. Android reads all characters in the address including complete unit number identifiers.

2. and 3.  Follows requirements.

## Acceptance Criteria
See above.

## Bug Severity
- 3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17698

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/eecd5136-c5f2-4df4-b0b1-094c3bb2b125)

**Comment by DF-ClaytonMatulich** [comment]
"Edit address" button a11y hint is correct. "Use this address" button a11y hint is incorrect.

**Comment by DF-ClaytonMatulich** [comment]
Note for QA @digitalken : Disregard the issue with the missing "b" on voice over. Since this issue is coming from a user input we will not make a change accommodate for certain screen readers.

**Comment by digitalken** [comment]
PASS 2/17/2021 - Button hints are now correct. closing.
