### ISSUE TITLE
[DISCOVERY] Setting up a single node for an english page and a spanish page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#19955]
The Coronavirus FAQ spanish page uses a unique node that was set up for this page.

We understand it is possible to have both pages (english and spanish) exist under one node, which would make it easier to keep track  and update spanish pages.

This request is to research:

-  what work would need to happen to enable this
- what's the level of effort
- which engineering team can do the work (ie only CMS engineer?)

**Comment by SKasimow** [comment]
Hi @youngfreezyVA - we have a discovery/research request to get a better understanding of the above. 
We can review on our "live" stand-up today :).

**Comment by youngfreezyVA** [comment]
this is possible but sounds like it would be better suited to use our CMSs translation capabilities if we go the route of sharing the node. while this is possible i don't think it's scalable
