### ISSUE TITLE
Update Review Instances to run CMS Export

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#19969]
## Summary

After CMS Export is merged into staging and prod we'll be expecting people to use is, so they will need a place to test their work. Review instances will need to be updated to use CMS Export as they are currently using the standard `yarn build` command, which uses GraphQL.

This can be reverted when the --use-cms-export flag is removed, but in the meantime we'll need to update the build.

## Details 

The build commend at https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/review-entrypoint.sh#L5 needs to be updated and the pipeline/RI needs to be tested.

## Definition of Done 

- [ ] Review Entry Point is updated
- [ ] Review instance passes through the Jenkins pipeline
- [ ] The review instance deploys successfully with CMS Export

**Comment by timwright12** [comment]
Working branch: `feature/add-cms-export-to-review-instances`

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
