### ISSUE TITLE
Fraud Investigation

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#19968]
Requested help with log interpretation by Cory Trimm on Feb 12, 2021.

Two users had the same name, and one of them was able to view the address of another user.

I was given the user ICN, checked some logs during a time frame to confirm that the user appeared to follow our auth flow properly. From the logs I was able to view, I did not see any evidence of malicious fraud, looked like the user in question had logged normally, and the originating IP address matched up with the real location of the user

**Comment by joeniquette** [comment]
Follow up work can be done here to automate the searching of this information. I will create a new ticket which lays out a request to get Athena working to streamline the data extraction from cloudwatch logs.
