### ISSUE TITLE
Investigate SauceLabs and other vendors for cross-platform testing

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#19967]
Due to potential issues with using BrowserStack for cross-platform testing as described in [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19380), we need to investigate other vendors that could be used for cross-platform testing. Since we have partial integration of SauceLabs with our Nightwatch suite, SauceLabs will be investigated first. SauceLabs currently has a [beta version](https://wiki.saucelabs.com/display/DOCS/2021/01/21/Cypress+on+Sauce+Labs+Cloud+Beta+is+Live) of support for Cypress.

A list of "must have" requirements for a cross-platform testing vendor has been created:
- The vendor must support Cypress
- Cross-browser support should include IE11
- Live testing should be supported
- Mobile testing

**Comment by holdenhinkle** [comment]
Spreadsheet listing BrowserStack alternatives - https://docs.google.com/spreadsheets/d/1xGfsq7Yp9SPJh0FUA1kiISagHk5l_WGQ2-V3gFVJPZk/edit?usp=sharing

**Comment by pjhill** [comment]
Moving to icebox for now as this initiative has been back-burnered.
