### ISSUE TITLE
[EPIC]: Review TTY calls to action and links for consistent message and behavior

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#19962]
This will serve as an epic (possibly a super epic) for capturing TTY improvements on VA.gov and our VA mobile app. We're looking to make our language, iconography, and link functions as consistent as possible, while leveraging device and platform-specific enhancements.

Improvements might include things like:

* Reviewing content for inclusive language
* Updating accessible labels
* Modifying URLs so links behave properly on mobile devices

**Comment by andaleliz** [comment]
@humancompanion-usds came across this in researching another TTY issue - curious if this is something the DS team is going to work on in the future?

**Comment by humancompanion-usds** [comment]
@andaleliz - I think this has mostly been done in the support for TTY in the va-telephone component. But I grabbed the 2 issues Trevor had filed for selecting an icon and getting that icon into the va-telephone component for TTY and prioritized them for us to tackle.

**Comment by andaleliz** [comment]
@humancompanion-usds that's awesome, thank you! Glad I followed up.

**Comment by caw310** [comment]
Closing this as tickets associated with this are done.
