### ISSUE TITLE
Content Feedback - Usability Prep - VAOS for Distribution

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#19964]
## User story
Content feedback for VAOS for distribution prototype
link to prototype: https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560117_Home

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

**Comment by peggygannon** [comment]
## Thoughts/questions
-

## Feedback key
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**


**Should:**


**Consider:**

**Comment by peggygannon** [comment]
@outerpress @laurenernest Please see below for content recommendation for Usability prep for VAOS vaccine distribution. 

**Thoughts/questions**

H2 = Schedule your first COVID-19 vaccine
yet CTA button below it says  "Learn more"  
The header implies that user will be able to start scheduling on next screen. We need to align header and button content to more accurately reflect what next screen will show users.  Are users "learning more" about the vaccine or are they starting to "schedule" it? 

Is there a step missing btw these two screens? Like should we be showing users that we are searching for the facility closest to them? 
https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/444881381
https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560132tis 

Seems like this screen should come earlier in the flow:
https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/444881383

Is the second dose scheduled the VA clinic? I think the content should be more clear how and when this is schedule.


**Must**

All instances of COVID > COVID-19
All instances of vaccination or vaccinations > vaccine or vaccines

*this is to align with how we treat this on the vaccine static page*


Please update this link to: Learn more about COVID-19 vaccines at VA. 
Where does this link take users?


**Should **

https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560132 on this screen please update the second line intro to please update content to make clear that the facilities below offer appt. TO:
Contact one of the facilities listed below to schedule your vaccine appointment.

https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560131
please update this intro content on this page: 
You can only schedule the first COVID-19 vaccine online. If you need to get the second dose,  please contact one of the VA health facilities listed below. 

https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560121
please update intro content to: 
You’ll need to get both doses of the vaccine at the same VA facility. Plan to return 3 to 4 weeks after your first dose for your second dose. 

https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443906785
please update intro content to: 
Each clinic offers vaccine appointments at different times.

https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/445239019
please update intro to: 
Plan to return 3 to 4 weeks after your first dose for your second dose. We’ll schedule your second dose after you receive your first.
 

https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560125
update link to: Can I choose which vaccine I get? 
Where does this link take users? 


https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560126
Per an on earlier review, I had provided these recommended edits to condense this content: 

This is the contact information we have on file for you. This is how we'll contact you about your appointment. Any updates you make to this information here, will only apply to this tool. If you want to update your contact information for all your VA accounts, [go to your profile page].

https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560128
recommend tweaking H1 to: We’ve scheduled your appointment


**Consider**

n/a

**Comment by outerpress** [comment]
Thanks @peggygannon , great feedback as always. I made most of your recommended changes. There were a couple of minor conflicts with @DanielleThierryUSDSVA 's feedback but the resolution seemed clear. You can see the conversation thread in the Invision comments if you like.

I made some larger changes to resolve issues that came up during review:

**Problem: rough transition from home CTA to flows**
* I updated the home CTA on all flows to ask the question we assume veterans will have on entering VAOS - how do I schedule my appointment. The aim is to give us flexibility to ease those we can't serve into calling a facility, while allowing others to call or schedule online. 
* I added the [schedule your appointment page](https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/445361554) after the CTA in all flows. The CTA on this page now changes based on what flow you're in. 

**New requirements**
* I changed all the calendar pages [(starting here)](https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/445239020) to support the additional information we want veterans to consider. Could you review these as well? The content has changed significantly

**Unresolved**
The [Plan your second dose page](https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560125) could still be clearer. Danielle had some suggestions there that I want to look at more closely.

FYI @laurenernest @allison0034

**Comment by outerpress** [comment]
@laurenernest - this feedback was incorporated into the prototype, which we're now iterating on based on user research, so I think this can be closed. (I'm tossing it your way instead of closing it myself in case you need to capture anything else from it.)
