### ISSUE TITLE
Content Feedback - Staging review - EDU Direct Deposit

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#19963]
## User story

Staging review for Direct Deposit for EDU benefits
Staging link: https://staging.va.gov/profile/direct-deposit

## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

**Comment by peggygannon** [comment]
Hi, @mshea0606 @sporeboy 

Hello, please see below for content feedback for this staging review. Let me know if you have any questions. 


**Must** 

1. Page H1 should match the left nav. Right now, there is mismatch: 
H1= Direct deposit information
left nav= Direct deposit

I recommend updating left nav to Direct deposit information to align with treatment on the other profile pages


2.  "Update" CTA button should be more descriptive and tied to content above. 
Suggestion changing Update TO> Update account

*We'll also need to update button CTA that appears under Disability compensation and pension benefits*



3. per: this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19611 I've added content instructions for how to find routing and account numbers on check


**Should**
n/a

**Consider**
n/a

**Comment by sporeboy** [comment]
Side nav revised: https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/

**Comment by sporeboy** [comment]
There is a comment addressing text for the check image in [#19611](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19611)

**Comment by sporeboy** [comment]
The description for the "Update" button will be handled using an aria label.
