### ISSUE TITLE
Clicking "edit address" from validation view wipes out user-entered address

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#19978]
## Background
When viewing the Address Validation screen, clicking the "edit address" link should return to the edit view and the form should be filled with _the address they had just entered, not the address they have saved on file._ This way they can easily make an adjustment to the address they entered.

## Bug
Currently, clicking on the "edit address" link returns them to the edit view but the form is populated with the address as it was when they started the edit process. This is a regression. It used to work correctly.

https://user-images.githubusercontent.com/20728956/108006361-190ad680-6fb0-11eb-8a06-56fa6b6ef772.mp4

**Comment by Samara-Strauss** [comment]
Fixed!
