### ISSUE TITLE
Access for Jeffrey Wallace

### ISSUE THREAD

**Issue by jw81** [department-of-veterans-affairs/va.gov-team#19972]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Jeffrey Wallace
- Please Provide your email.
   > jeff.wallace@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA API, Sr. Rails Engineer, Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCigSVHJpsG1k5QS4AxMi9ryyacPcV3xDKhjHlMB6yO7u+q8raB6JdXi3B7JWozLg95rCdDqPfQqDuSTLisk7HB+A3yk9FvbxVSivTr2PS9FKOkO1yAdMQORe7sWDCKelkwJ0IDK6Wln8e1YbO9eO2YXtI86ssy43yucwRZkQRGfca45quH8QPQ5W42QQL3k67szPSuHfUAOYf90WmIaNmGdRuzWP1CNpCJzH1fkT5zwiIrF/x3IIYmuT7J7BoJ+Fi5HtUJ8UvrQUApdfLWw/t6b+b3Js4vHki3ObUumcCVd/lpe8TVO8MNS4ZIX+L+2aOcZ1UreBq3rKtx773ypwr0tIj54jsNw0L1L8tOvuorx6bYkyOxRmDHaQLGx65izWNqO/Q0T7+lTeonyuabUgjOZdr/B5aLmqSrdGHYT/3I7fazUvo8A+tooirLGPUEK34hEnMRC/ANbOEujU8npH9RFjODNIGsdPV4MNP433u/SiHbm4t3r/Z0X9znoNjAfvU= jeffreywallace@Jeffreys-MBP-2.lan
```

- Grant AWS Console access?
  > NO

**Comment by jw81** [comment]
Adding comment with tag as instructed :: @department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@jw81 You should now have SOCKS proxy access and can continue with the directions in that section to verify.
Thanks,

**Comment by jw81** [comment]
@jsev-io thank you.
However, I think I may have provided an incomplete copy of my public ssh key.
I neglected to include the final segment that shows my username on my machine. (which is probably why I can't connect after continuing on with the doc)
I will update the ticket with the full copy of my public ssh key.
My apologies.

**Comment by mleclerc00** [comment]
Hi @jw81,  

I checked your ssh key that is provided versus the one pushed to the proxy and the only thing that is missing is the comment which should have no effect.  Are you having troubles connecting to resources via socks?

**Comment by jw81** [comment]
Hi @mleclerc00 ,

Yeah, when I run ::
`ssh socks -D 2001 -N`

I get ::
```
dsva@52.222.32.121: Permission denied (publickey).
kex_exchange_identification: Connection closed by remote host
```

So it looks like my key isn't being accepted.

**Comment by mleclerc00** [comment]
closing request

https://dsva.slack.com/archives/CBU0KDSB1/p1614016425026700
