### ISSUE TITLE
CT Redesign: Post-Test - Identify & define UI Solutions

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#19984]
As a UX Designer, I want to have a thorough understanding of what functionality needs to be modified so I can make relevant updates to the prototypes.  

- [ ] Team work to identify and define high-level solutions to issues identified during testing

**Comment by amyknox** [comment]
Mural board here: https://app.mural.co/t/bahdigitalexperience6902/r/1553290563937
