### ISSUE TITLE
Update terser-webpack-plugin in vets-website

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#19980]
terser-webpack-plugin dependency is multiple versions behind.

Slack Thread: https://dsva.slack.com/archives/GLDNCMRSP/p1613434946103600

**Comment by laineymajor** [comment]
@jhonnyoddball please reference/link to dependency management work upcoming

**Comment by jhonnyoddball** [comment]
Terser-webpack-plugin was fully upgraded to the latest version with in the full [webpack upgrade to version 5](https://github.com/department-of-veterans-affairs/vets-website/pull/19403)
