### ISSUE TITLE
[Discovery] Define isolated monitoring approach so App teams can have a dedicated view of their tools' status

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#200]
## Story
As a VFS App developer, I need a way to visualize the status of my tools so I can troubleshoot my production/live apps.

## Goals
VFS creators can quickly identify errors in their tools and begin their resolution process.

## AC
- [ ] A list of items that engineering needs to holistically understand the status of their tools.
- [ ] Come up with a plan for testing if this information is actionable and what other information would be valuable to have

## Def of Done
- [ ] AC is complete
- [ ] Connected to an Epic

**Comment by rtluu** [comment]
Require VFS teams to set up one or multiple of the following monitoring systems in order to go live so that they can monitor their apps in production.

Ideas for how this could be accomplished:
- Tags in Sentry
- Alert/Emails
- Queries in Prometheus that monitor the services being user
   - Graphana dashboard on top
- Proper pager duty alerts

**Comment by rianfowler** [comment]
Made this for FE but it seems relevant: [Improve app telemetry](https://github.com/department-of-veterans-affairs/va.gov-team/issues/243)

**Comment by annaswims** [comment]
BE will write documentation on when and how to log info to sentry or AWS.
