### ISSUE TITLE
VSA Onboarding - Angela Fowler

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#20000]
## Welcome to the VSA Program

Welcome! This issue will be used to track your onboarding to the VSA Program.

---

## Pre-Onboarding

**Operation Lead Tasks**

- [x] Send Welcome email to New Hire (request GitHub Username)

*Send Notifications with New Hire details (name, position, start date) to:*

- [x] Admin Analyst
- [x] VA Leadership
- [ ] VA PO
- [x] Practice Lead
- [x] VSP Onboarding

**Access, Paperwork and Program File Updates**

- [x] Access to [Shared Google Drive](https://drive.google.com/drive/u/1/folders/0ACZ1e6Rs_6sDUk9PVA)
- [x] Access to VSA PTO Calendar
- [x] Request [Access to VA Organization in GitHub](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19&labels=add-user-to-org%2C+new-user%2C+user-created&template=add-user-to-the-va-organization.md&title=ADD+USER+TO+ORG+-+%5BUSERNAME%5D)
- [x] Access to [VSA GitHub Repositories](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-vsa/members)
- [x] Access to GCIO/AdHoc Slack Workspace
- [x] Request access to DSVA Slack Workspace
- [ ] Request Hardware/Software (GCIO Only)
- [x] Request New Hire to Complete VA Onboarding Paperwork (GCIO Admin Analyst)
- [x] Schedule Program Overview Meeting

---

## Onboarding

**New Hire Tasks**

*Day 1*
- [x] [Watch Chris Johnston va.gov Backgrounder recording](https://drive.google.com/file/d/1BTYPaR0p9hYD4qd-OCCduyIRTRr77S1O/view?usp=sharing)
- [x] Review [VSA Onboarding Doc](https://drive.google.com/file/d/1I3BJT2L49xT2WgufLDO1wqW84zLSPs8G/view?usp=sharing)
- [x] Attend VSA Program Overview Meeting
- [x] Make Calendar Public (Free/Busy)
- [x] Complete VA Onboarding paperwork (sent by VSA Admin Analyst)

*Month 1*
- [ ] GCIO Only: Complete [Skill Matrix](https://docs.google.com/spreadsheets/d/1h8Pei6G14QS2QO0VNdnswmJW0WLol4aRjXpSJdp9kpA/edit#gid=0)
- [ ] Request SOCKS Access, after SAC Adjudication
- [ ] Complete VSP Orientation (Invite sent by VSP team)

**Operation Lead Tasks**

- [x] Inform Practice Lead, Product Manager to trigger communication
- [x] Conduct VSA Program Overview Meeting
- [x] Update Org Chart and Share with New Hire
- [x] Add New Hire to #va-vsa
- [ ] Send out org announcement on #va-vsa
- [ ] Request New Hire to Complete Skills Matrix (GCIO only)
- [x] Add New Hire to Program-wide Meetings
- [ ] Add New Hire to The Platform Newsletter (James Chaisa)

**Practice Lead Tasks**

- [x] Send Intro Comms to New Hire
- [x] Conduct Practice-specific Onboarding Meeting with New Hire
- [ ] Add New Hire to Practice-specific meetings
- [ ] Schedule Accessibility Orientation meeting with New Hire and VSA Accessibility Specialists 

**Product Manager Tasks**

- [ ] Send Intro Comms to New Hire
- [ ] Conduct Intro Meeting with New Hire
- [ ] Add New Hire to Product team meetings

**Program Manager Task**

- [ ] Check in with New Hire

**Comment by artsymartha68** [comment]
Closing on Angela's behalf, helping clean up some old issues.
