### ISSUE TITLE
Sentry error grouping

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#20005]
## Issue Description
Sentry 10 doesn't currently group errors as they were in Sentry 9. It looks to be that we used to group by some combination of exception.message but current error groupings don't follow the same strategy. It's difficult for developers to triage errors when the groupings cannot be understood. Grouping strategies should be investigated and revisited. A current workaround may be to group by [transaction](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&project=3&query=is%3Aunresolved+transaction%3ASidekiq%2FEVSS%3A%3ACreateUserAccountJob&statsPeriod=90d) 

---
## Tasks
- [ ] Investigate current grouping strategies

**Comment by LindseySaari** [comment]
Conversation [here](https://dsva.slack.com/archives/CBU0KDSB1/p1613425940184600)

**Comment by LindseySaari** [comment]
[Fingerprinting rule documentation](https://docs.sentry.io/platforms/ruby/data-management/event-grouping/fingerprint-rules/)

**Comment by alexpappasoddball** [comment]
We gave Kam admin access to this correct?  Is there something we want to follow up with him on this at some point?  Should we create a reminder or review and document what/how he did it so we have a record?
