### ISSUE TITLE
Update SLO endpoint

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#20014]
IAM has made a change to the single logout endpoint and have asked us to make any required adjustments on our end to match.

Email message from IAM:

> Today VA.gov triggers the logout process using the SSOe pkmslogout (https://eauth.va.gov/pkmslogout?filename=vagov-logout.html).  With the implementation of SLO, there will be a new common logout URL that will trigger SLO and send back-channel SLO messages to partners. VA.gov will need to move to the new logout URL to ensure users who navigated to My VA Health (Cerner Patient Portal) have their session closed.  Additionally, will VA.gov want to/be able to receive the SOAP SLO messages? If so what are the VA.gov SLO endpoints across environments?
Steve Dickson
Project Manager (Green Threads, LLC)

**Comment by jimiray** [comment]
@joeniquette @christine-dillman This is the card that's delayed based on the changes in priority for IAM, should we move it back to backlog for now?

**Comment by joeniquette** [comment]
Please confirm with the request team that they are going to shelve this or if they want to move forward with any of the components.

**Comment by jimiray** [comment]
From Steven Dickson:

Hi Jim,

Yes, there was a change in priority for this and we are now planning to release it during one of our VIP17 releases.  Exact date is currently TBD, but between 4/17 and 6/19.

Can we just move this to the backlog?

**Comment by bramleyjl** [comment]
PR for this change: https://github.com/department-of-veterans-affairs/vets-api/pull/7175
