### ISSUE TITLE
Document role of CMS Export in build pipeline

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#20015]
## Details 

Existing CMS Export documentation is scattered and primarily targeted towards VFS developers (i.e. the [Transformer Development Guide](https://vfs.atlassian.net/wiki/spaces/VP/pages/637567205/Transformers+Development+Guide)) 

In discussing the release of CMS Export to dev.va.gov with VSP Ops, Jesse & Demian requested that we document this work somewhere to assist in future troubleshooting. 

[Slack thread](https://dsva.slack.com/archives/CJYRZK2HH/p1613152045337100)

Demian Ginther  4 days ago
Happy to know whatever level of information you think is needed, are you documenting the new process somewhere?
like, if we needed to troubleshoot the process and figure out why it was broken, is docu for that going to be around?
if not, then we might want a slightly more involved posture.

Jesse House  22 hours ago
To Demian's point, It does sound like a good point of clarification in your communication that this is a specific deployment that is not currently owned by Ops, so that there's no confusion on where to turn if issues arise. Also, definitely in favor of providing documentation / diagrams, etc when something goes live (maybe not Dev, but definitely staging and prod), so that we can provide cross-team support for the platform and make sure people know where to look for answers. Even a high-level reference for 1) here's the thing, 2) here's what it does, 3) here's how it works, 4) here's where you find it's components/code is extremely useful.

## Open Questions
- [ ] Determine where this documentation should go & be cross linked from (maybe with the transformers docs currently in Confluence? Maybe with existing docs on the build pipeline?) 

## Acceptance Criteria
- [ ] Documentation of CMS Export role in build pipeline has been written and is uploaded to a documentation site 
- [ ] Peer review by 1+ member of VSP FE Tools
- [ ] Share with Ops 
- [ ] Documentation includes "current state" (at time of writing) and "future state" (at time of release to staging and prof, to be updated later)

**Comment by mchelen-gov** [comment]
OBE or alternatively update docs for current GQL build process? https://vfs.atlassian.net/wiki/spaces/VP/pages/567607297/WIP+CMS+export+transformation+overview#Overview.1

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
