### ISSUE TITLE
[Analytics] VA.gov performance dashboard: Update direct deposit tracking so data is pulled in correctly

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20022]
## Background

**This is not urgent, so please feel free to prioritize it against other work accordingly.**

On 2.16.21, we noticed that there is no data being pulled in for direct deposit updates on [the VA.gov performance dashboard](https://www.va.gov/performance-dashboard/). 

![Screen Shot 2021-02-16 at 11.57.10 AM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/9e5d8300-c582-45c4-94d9-afb9e0963b68)

We know that direct deposit is up and working, as [we can see that in GA](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/). This issue likely is a result of updates we made to direct deposit tracking when we launched Profile 2.0 at the beginning of October. While the work in GA was updated, those changes never made it over to the performance dashboard.

## Tasks

- [x] Update performance dashboard tracking so that it is correctly pulling in direct deposit data. You can use "Form Submits for Direct Deposit Information" as the metric we use to populate the performance dashboard.

**Comment by stephenBarrs** [comment]
PR for Performance Dashboard update: https://github.com/department-of-veterans-affairs/vets.gov-status/pull/3964

**Comment by Samara-Strauss** [comment]
Fixed!
