### ISSUE TITLE
[BE] store invalid addresses in PII logs table

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#20025]
https://dsva.slack.com/archives/C7TE0PFTL/p1613488754081700

http://sentry.vfs.va.gov/organizations/vsp/issues/6740/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Aaddresses&statsPeriod=14d

store addresses that violate length validation in PII logs table to investigate how these addresses 
are escaping frontend validation

**Comment by Samara-Strauss** [comment]
No immediate action required. Adding this to next sprint, though do let us know if you tackle this sooner.

**Comment by Samara-Strauss** [comment]
CC/ @erikphansen that Lihan has added tracking for the address issue in #20079
