### ISSUE TITLE
Saving Direct Deposit information goes to a blank screen

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#20032]
## What happened?
Saved a valid Bank of America routing number with any old account number and get a blank screen after hitting the Save button.  The Save and Cancel buttons never go away and I can hit the Save button over again, get the spinner and notice about saving the information, then the blank (white) screen stays there with the Direct Deposit header, with Cancel and Save buttons active.

## Specs:
- Device: Android Samsung Galaxy Note 9, iOS iPhone XR
- Test User _(if applicable)_: Using +228 with the following Bank of America routing number:  021000322

## Steps to Reproduce
- Log in as user with DD edit ability and enter the B of A routing number: 021000322 and any account number, choose checking or savings, then Save.

## Desired behavior
Takes entered data and returns to previous page showing the account has been saved.

## Acceptance Criteria
see above

## Bug Severity
- 2 - High

## Linked to Story
n/a

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/e0ec9cb2-cf83-450a-aa11-0c0928eeddcd)

**Comment by bessgreen** [comment]
**Update:**

I tried to save the Routing # referenced in the ticket above: Bank of America, **#021000322**.

The form seemingly saved, but when it returned to the DD overview screen, the account summary that displayed did not match my entry: 
![Image from iOS (13).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e88c3f5c-f9cd-4a1a-a3d1-b1dc6a336b79)

**Comment by digitalken** [comment]
@keli13 - I just tried this and everything performed as expected.  I'm thinking this was a backend problem but we probably need to figure out something for handling backend problems on this call rather than just going to a blank page.  (2/17/2021 @ 1:00 PM-ish)

**Comment by keli13** [comment]
User has the 'directDepositBenefits' permission so it allowed to see direct deposit but there is a separate PPIU check(permission) that needs to added in order to verify that the user can update their bank information.  

Will need to wait for update from BE before fixing this ticket.

**Comment by bessgreen** [comment]
Corresponding BE ticket: #20164

**Comment by digitalken** [comment]
PASS 4/1/2021 - Now get the generic error w/refresh for the problem.  Canceled, went back in to try again and was greeted with the form.  Closing.
