### ISSUE TITLE
Clarify how to verify pacts locally when using the Docker workflow

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#20033]
Update the 'Using a local file if blocked by frontend' section in  [How to use Pact for contract testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/contract-testing/how-to-use-pact-for-contract-testing.md) to include the commands to verify a pact in both native workflow and the docker workflow.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/va.gov-team/pull/20018

**Comment by holdenhinkle** [comment]
This task is complete.

**Comment by pjhill** [comment]
:tada:
