### ISSUE TITLE
Open Minor update to Cypress Viewport Updater Bot documentation regarding manually updated vcr cassette files

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#20034]
Update the [Cypress Viewport Updater Bot documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/automatic-cypress-viewport-updater.md):

Make sure both the  `google_analytics_request_report.yml` and the `google_analytics_after_request_report.yml` VCR cassette files are included in the 'Google Analytics VCR Cassettes Were Manually Updated' section.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/va.gov-team/pull/19831

**Comment by holdenhinkle** [comment]
This task is completed.

**Comment by pjhill** [comment]
Thanks for keeping docs up-to-date.
