### ISSUE TITLE
[Cheetah MVP] Update appointment confirmation page

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20040]
## Item Description
Update the appointment scheduling confirmation page for COVID clinics.

## Acceptance Criteria

- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] Confirmation alert message displays

- [ ] Appointment type label displays
- [ ] CONTENT - Appointment type label is "COVID-19 VACCINE"

- [ ] Date and time of appointment displays

- [ ] Confirmation icon and label displays
- [ ] Facility name and address displays
- [ ] Directions link displays
- [ ] If user clicks Directions link, Then open default maps app with facility address pre-populated
- [ ] Facility phone number displays

- [ ] Add to calendar link displays

- [ ] If user clicks Add to calendar link, Then download/open (respective to device) calendar file with the following pre-populated:
- Appointment type
- Location
- Time

- [ ] View your appointments button displays

- [ ] If user clicks View your appointment button, Then display VAOS homepage

- [ ] DESIGN - Designs match specs https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9/a/kaaOx9r#Inspector
_(Note- Copy in specs is FPO)_
![Screen Shot 2021-03-02 at 7.57.23 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/d1899ff6-c576-446e-a7b6-8a48e388250d)

**Comment by laurenernest** [comment]
@LanceGundersen Here are the links to the documentation and screenshot folder. Can you please update with your changes? Thanks!

[Flow doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md)

[Screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/design/cheetah-flow)

**Comment by LanceGundersen** [comment]
@laurenernest done
