### ISSUE TITLE
Migrate from moment to date-fns in the component library

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#20059]
## Issue Description
Moment is officially considered ["a legacy project"](https://momentjs.com/docs/#/-project-status/) by the maintainers. We should move to an actively-maintained project such as `date-fns`.

This issue covers migrating the component library.

## Acceptance Criteria
- [ ] `moment` is removed from the `component-library` dependencies
- [ ] No regressions are introduced

**Comment by k80bowman** [comment]
duplicate. Tracking work with #19954.
