### ISSUE TITLE
Require the latest master branch before merging in the component library

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#20053]
## Issue Description
To avoid regressions from merges, we should enable the GitHub setting to require the latest `master` commit in a branch before allowing a merge.

![image](https://user-images.githubusercontent.com/12970166/108124964-a1df4c00-705c-11eb-9119-f84bfd34df6f.png)

---
## Tasks
- [ ] Enable [the option](https://docs.github.com/en/enterprise-server@2.22/github/administering-a-repository/managing-a-branch-protection-rule) in the [repo settings](https://github.com/department-of-veterans-affairs/component-library/settings/branches)

**Comment by bkjohnson** [comment]
@k80bowman I'm closing this since it's already been done.
