### ISSUE TITLE
GIDS: Upgrade rails to 6.0.3.5

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20067]
As a developer, I need to upgrade GIDS to Rails v.6.0.3.5 so that GIDS is using the most recent version of the library.

## Assumptions:
1. N/A

## Acceptance Criteria
1. Rails is on version 6.0.3.5.

## Technical Notes:
In vets-api GemFile it is using 
gem 'rails', '~> 6.0.3.5'
https://github.com/department-of-veterans-affairs/vets-api/pull/4069

## Supporting Artifacts
1. N/A

**Comment by ksantiagomorgan6** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/792

**Comment by sonntag-adam** [comment]
Testing passes QA
