### ISSUE TITLE
Migrate from moment to date-fns in the forms library

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#20061]
## Issue Description
Moment is officially considered ["a legacy project"](https://momentjs.com/docs/#/-project-status/) by the maintainers. We should move to an actively-maintained project such as `date-fns`.

This issue covers migrating the forms library.

## Acceptance Criteria
- [ ] `moment` is not imported anywhere in the forms library
- [ ] No regressions are introduced

**Comment by k80bowman** [comment]
duplicate. Tracking with #19954.
