### ISSUE TITLE
SSL on review instances

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#20078]
Our review instances currently do not support SSL.

This makes it impossible to test various features, including browser-based geolocation.

## Desired outcome

The review instances support SSL, so we can test features that require a secure connection.

**Comment by jsev-io** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by mpelzsherman** [comment]
Hi - any updates on this?

**Comment by jhouse-solvd** [comment]
@mpelzsherman - will raise this with the team and determine what's possible here.

**Comment by jhouse-solvd** [comment]
@mpelzsherman - we've done some pre-work (creating a Certificate Authority in AWS ACM for internal resources), and we think it would be pretty easy to issue a certificate from there, but would need to work through some of the technical details to do this as Infrastructure as Code. 

There are a few other higher priorities on the plate right now, but Ops can potentially look at picking this up at the beginning of the next quarter (a couple of sprints from now, early April). 

We are also working on improvements to overall delivery infrastructure and will be re-evaluating review instances / ephemeral dev instances. However, this sounds like a great iteration that would improve what we have now, and so will consider prioritizing this work to address this pain point sooner than later. We definitely understand the limitation here and want to work to improve the experience with review instances / environments. 

Tagging @drorva for additional visibility (can also help us prioritize accordingly).

**Comment by mpelzsherman** [comment]
Hi @jhouse-solvd - any updates on this?

**Comment by jhouse-solvd** [comment]
@mpelzsherman - no updates as of yet. this work is not yet in progress, and we will need to prioritize for a forthcoming sprint. once we have a better idea on timing, we will pick this up and share additional details.

**Comment by mpelzsherman** [comment]
Hi @jhouse-solvd . Just checking on status. FYSA, we are adding some geolocation features in our current sprint, and the lack of SSL support on the review instances is a pretty major impediment to proper testing.

**Comment by jhouse-solvd** [comment]
@mpelzsherman - we've created #26372 and are considering this for the upcoming sprint. please feel free to check it out and provide feedback. I will report back with more soon.

**Comment by mpelzsherman** [comment]
Hey @jhouse-solvd - this is very exciting news! Thanks!!

**Comment by mpelzsherman** [comment]
@jhouse-solvd - any updates?

**Comment by jhouse-solvd** [comment]
@mpelzsherman - if it's okay with you, I'm closing this one in favor of:

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/26372

I've made some updates on that ticket which is also linked to a specific PR. 

Closing.
