### ISSUE TITLE
CLP Refinement Punch List - Internal UAT

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#20087]
Issue Description
Some refinement is needed post PR for Campaign Landing Page, punch list listed below for FE work effort. Also plan to capture any internal bugs or needed fixes from our team walk through this afternoon via this ticket

[Google Doc for Reference](https://docs.google.com/document/d/1gUTTX0-8Cm-nBVQ5CI_k15bgqSXHpGNm/edit)

CLP UAT Refinement Task List

- [ ] Panel 6: There needs to be the ability to include a URL for the Call to Action text – not sure how Add a link to an external blog or other list of stories is supposed to work.  Should be a Call to Action option with a URL field.  (CTA needs to be hardcoded)
- [x] Panel 11: The text in the VA benefit blocks is far longer than anticipated.  (kadams@governmentcio.com have a look at how this is done on the homepage. it uses a different teaser text summary.)
- [x] Panel 7: The PDFs are not downloading as expected – I’m getting a different file type.
- [x] Panel 8: Panel 8: Events: Selecting an existing Event from the library can result in:
- Long text description - max 150 characters.  
- No Where info
- Not sure where the “Find out about upcoming VA events near you” title comes from – but it appears we don’t need it.
- [x] Social Media Share (Test and Validate it's working as intended). 
 
- [x] For Preview state, we should only show the Panels that are used – not all the empty panels.
- [x] Tier 1 Issue: There is an Add to Calendar link/component in the This Page is For that should not be there.
- [x] Video in Media Library did not display on the front end. (Need to fix this element or validate when code fix will be deployed)
- [x] Remove the carrot in the “Read the press release for details”?  (per Randi, to be consistent we can leave the carrot off)
- [x] Panel 10: The YouTube link for VHA is broken (FE issue, working on VA Healthcare)
- [x] Creating an event in the Outreach event library resulted in:
- Did not include title “Veterans town hall in Pittsburgh”
- Did not include Where info
- [x] Panel 9: Frequently asked questions panel: Should the accordions be going all the way to the end of the blue space?
The blue background on the FAQ and the VA Benefits panels aren’t going as far left as the other panels are. Is this part of the PR that Kelson is merging today? 
![Screen Shot 2021-02-17 at 10 05 07 AM](https://user-images.githubusercontent.com/70410912/108240030-b0367200-7107-11eb-9dde-308bf0a45e4c.png)

**Comment by kelsonic** [comment]
Social media share buttons won't work properly until we are on staging (not the preview servers) since it's taking your `hostUrl`

**Comment by kelsonic** [comment]
>Panel 6: There needs to be the ability to include a URL for the Call to Action text – not sure how Add a link to an external blog or other list of stories is supposed to work. Should be a Call to Action option with a URL field. (CTA needs to be hardcoded)

@brianalloyd I'm a bit confused with this one and what I can do to resolve it?

**Comment by brianalloyd** [comment]
Good question @kelsonic, let me see if we can get you some clarity.  I believe the issue was to hard code the CTA. I think it's just using a default value ATM.

**Comment by johnhashva** [comment]
@kelsonic I'm seeing quite a few of the FE issues resolved -- should @RLHecht and I wait until another deployment (today or Monday) to take a second look and validate all FE issues are closed?  Don't want to keep reloading all day -- just easier for me (at least) to set aside time for a panel-by-panel look.

**Comment by kelsonic** [comment]
I would wait until today's deployment so I can get [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16108) merged + deployed 🙂

**Comment by kevwalsh** [comment]
My understanding is that the Panel 6 CTA text was hardcoded in FE as "See more stories". Content editors would not be able to specify that.

**Comment by johnhashva** [comment]
Great reminder @kevwalsh  -- you're right and that approach works.
