### ISSUE TITLE
Discover and Evaluate Test Case Management Software

### ISSUE THREAD

**Issue by peterhill-oddball** [department-of-veterans-affairs/va.gov-team#2008]
As part of an effort to formalize and expand the capabilities of QA on the platform, VSP needs to discover and select the best test case management software for use by VFS teams on the platform.  In my experience, some key features to consider for a TCMS are --
1. Create and edit test cases within the software
2. Create test plans in the software
3. Integrate with GitHub
4. Link to User Stories / Requirements
5. Log test case executions
6. Create bug reports from the software
7. Report on test case execution
8. Customize workflow
9. Customize reports
10. Categorize / organize test cases beyond inclusion in a sprint / release
11. Collect test cases into a test plan based on labels and test case metadata

A quick scan of TCMS that integrates with GitHub showed these three tools --
1. [TestQuality] (https://github.com/marketplace/testquality)
2. [Kiwi] (https://github.com/marketplace/kiwi-tcms)
3. [TestRail] (https://www.gurock.com/testrail/github-test-management)

**Comment by peterhill-oddball** [comment]
[TestLodge](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2008) looks fairly interesting.  Their "GitHub" integration is pretty much just creating issues from the test case execution in GitHub.  Which is probably all that we need.

**Comment by peterhill-oddball** [comment]
TestLodge evaluation --
- [ ] Create and edit test cases within the software
- [ ] Create test plans in the software
- [ ] Integrate with GitHub
- [ ] Link to User Stories / Requirements
- [ ] Log test case executions
- [ ] Create bug reports from the software
- [ ] Report on test case execution
- [ ] Customize workflow
- [ ] Customize reports
- [ ] Categorize / organize test cases beyond inclusion in a sprint / release
- [ ] Collect test cases into a test plan based on labels and test case metadata

**Comment by U-DON** [comment]
@peterhill-oddball: How do you feel TestLodge stacks up against TestRail? From a first glance, I think the latter also has the GitHub integration, but not sure if you've had more experience with it. Also seems like a fairly trusted and mature product from its list of teams that use it and from what I've read in forums.

**Comment by peterhill-oddball** [comment]
> @peterhill-oddball: How do you feel TestLodge stacks up against TestRail? From a first glance, I think the latter also has the GitHub integration, but not sure if you've had more experience with it. Also seems like a fairly trusted and mature product from its list of teams that use it and from what I've read in forums.

I don't have any experience with any of these tools, unfortunately.  I'm going to do a checklist for each tool, and start a trial instance up when I can.  Do please weigh in with your personal experiences if you have any!

**Comment by peterhill-oddball** [comment]
[Kiwi](https://github.com/marketplace/kiwi-tcms) evaluation --

- [ ] Create and edit test cases within the software
- [ ] Create test plans in the software
- [ ] Integrate with GitHub -- details
- [ ] Link to User Stories / Requirements
- [ ] Log test case executions
- [ ] Create bug reports from the software
- [ ] Report on test case execution
- [ ] Customize workflow
- [ ] Customize reports
- [ ] Categorize / organize test cases beyond inclusion in a sprint / release
- [ ] Collect test cases into a test plan based on labels and test case metadata

**Comment by peterhill-oddball** [comment]
TestRail evaluation -- 

- [ ] Create and edit test cases within the software
- [ ] Create test plans in the software
- [ ] Integrate with GitHub
- [ ] Link to User Stories / Requirements
- [ ] Log test case executions
- [ ] Create bug reports from the software
- [ ] Report on test case execution
- [ ] Customize workflow
- [ ] Customize reports
- [ ] Categorize / organize test cases beyond inclusion in a sprint / release
- [ ] Collect test cases into a test plan based on labels and test case metadata

**Comment by peterhill-oddball** [comment]
Switching to a spreadsheet which is shared [here](https://drive.google.com/file/d/1gXS3Ma1Vx11lPz4mlgi_8y6wGOdSV8rX/view?usp=sharing).

**Comment by peterhill-oddball** [comment]
I need to discuss the results of the evaluation with others.  Additionally, we need to address a few questions:
1.  What kind of budget do we have for this tool?
2.   Is a cloud or privately hosted tool preferred?
3.  How many users do we expect for this kind of tool?

**Comment by peterhill-oddball** [comment]
Preliminary evaluation of software is complete.
