### ISSUE TITLE
Scheduled 03/04: Redirect Request: VR&E Process Legacy Page

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#20088]
### Description
We recently discovered a legacy page that was supposed to have been redirected to our modernized VA.gov page, but never got the redirect. So we’d like to put that in place now to avoid duplicate content. See related Slack thread here: https://dsva.slack.com/archives/C52CL1PKQ/p1612882707339200

### Requesting team info
Sitewide Content

### Implementation date
Date new URL(s) will be live: Pages are live

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing: Seven (7) business days after stakeholder notification 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.benefits.va.gov/VOCREHAB/VRE_Process.asp | https://www.va.gov/careers-employment/vocational-rehabilitation/

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [ ] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
This redirect is vetted and can be implemented when you are ready.  Please note that the redirect cannot be case sensitive, all variations of casing will need to be account for (i.e. "VOCREHAB" versus "vocrehab").

**Comment by lunascoop** [comment]
Hi @ncksllvn and @kelsonic. This redirect is scheduled for **03/04**. Stakeholders have been notified. Also, please see Mikki's most recent comment about casing. Thanks!

**Comment by lunascoop** [comment]
The redirect is live and working as intended. Closing ticket and updating stakeholders. Thanks!
