### ISSUE TITLE
Refactor some of the names in theme

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#20085]
## Dev task
UI/UX is working on a design library to use for building new screens. In order to help us transfer design to front end code, we need to change some things to use a shared nomenclature. The following names need to be changed in the theme files:

- [x] `marginBetween` should be renamed to `standardMarginBetween` and `condensedMarginBetween: 10` should replace any other dimension we use in places like cards and cta's for vertical spacing of 10.

- [x] `theme.colors.background.main` should change from `#F2F2F7` to `colors.grayLightest`

- [x] button colors need to reflect whether they are for `buttonPrimary` or `buttonSecondary`. This means that `theme.colors.background.button` will need to change to `buttonPrimary`, and anywhere that we use a border color or text color should now have a `buttonPrimary` or `buttonSecondary` prefix, i.e. `theme.border` should now have a `buttonSecondary`, `buttonSecondaryActive`, and `buttonSecondaryDisabled` color added. Any special text colors should also get added if we are using them.

This is a start to some larger changes that will be happening in the theme area over the coming sprints.

**Comment by komaly15** [comment]
Note for QA: for this story please go through the app and verify vertical margins are still correct, and verify all buttons still look as what is specified in designs

**Comment by digitalken** [comment]
PASS 2/24/2021 - Looks good and seems normal, from what I could find.  Closing.
