### ISSUE TITLE
Remove `profile_show_direct_deposit` feature flag

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#2009]
After we have released Direct Deposit to all users, we should remove the `profile_show_direct_deposit` feature flag entirely.

This involves:
- [ ] remove the flag from local, staging, and prod environments using the Flipper UI
    - localhost:3000/flipper/features
    - https://staging-api.va.gov/flipper/features
    - https://api.va.gov/flipper/features
- [ ] update front end code that checks for that feature flag
    - the redux selector at https://github.com/department-of-veterans-affairs/vets-website/blob/5dd83de9f1d29c8342fde041ca3fc35429301df2/src/applications/personalization/profile360/selectors.js
    - references to `profileShowDirectDeposit` and `showDirectDeposit` in the ProfileView component (which means that the ProfileView no longer need to be a redux container component)

**Comment by Justin-Pickett** [comment]
Will follow up with @erikphansen  on this item after we roll DD out on 10/2.

**Comment by erikphansen** [comment]
@Samara-Strauss @Justin-Pickett I can merge in this work at any time. But maybe we should just wait until direct deposit has been removed from eBenefits? Your call!

**Comment by Samara-Strauss** [comment]
I think you can remove this any time, though prob won't go out until after the code freeze is lifted.

**Comment by erikphansen** [comment]
Okay, I'll merge.
