### ISSUE TITLE
"Search this area" button lags

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20099]
## Issue Description
"Search this area" button seems to be lagging - causing it to appear/disappear. 

The buggy Search this area focus became evident during a VA benefits search - see [this Loom](https://www.loom.com/share/6664cc1442a14ece97877bf0a6e0c34e). Notice the presence of the "Search this area" button. It disappears during zooming in/out and does not always reappear when expected. The button is visible but seems to lag and disappears or errors when I try to initiate a search. 

My tests were performed on a Windows machine running Chrome. 

## Steps to reproduce
- Search for "Washington DC"
- Zoom out until most of Virgina and Maryland are visible. The "Search this area of the map" disappears.
- Zoom in a few times. The "Search this area of the map" button does not re-appear until you've zoomed in past the point where it disappeared.

## Acceptance Criteria
- [x] STA button disappears when zoomed out > 500 miles, and reappears when zoomed < 500 miles

**Comment by mpelzsherman** [comment]
Validated by @tlei123
