### ISSUE TITLE
Map all of the different development repos/resources

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#201]
## Story
As a VFS developer, there are many repos for engineering resources and it is difficult to navigate and know what's relevant.

## Goal
Create a map of all the different repos with information about:
- The audience
- The purpose
- The state (outdated/inactive, etc.)

## AC 
- [x] A map has been created for the different repos and their purposes
- [x] The map is leveraged to inform how we organize the documentation moving forward

## Def of Done
- [x] AC is complete
- [x] Connected to an epic

**Comment by rtluu** [comment]
A preliminary list has been started in this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/176#issuecomment-499609679

**Comment by rtluu** [comment]
# Current list of relevant documentation:

## For External Contract Teams
[VA Digital Services Handbook](https://department-of-veterans-affairs.github.io/va-digital-service-handbook/delivery/index.html):
- Provides a general user-centered agile delivery processes.
- Does not address `vets-api` or `vets-website` specifically.
- The source of this documentation can be found [here](https://github.com/department-of-veterans-affairs/va-digital-service-handbook).

[Documentation for External Contractor teams working on the Veteran-facing Services Platform (README) ](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams):
- Provides Code of Conduct, FAQ and standards for communications, tools and reviews
- Provides [introduction to Vets API](https://github.com/department-of-veterans-affairs/vets-external-teams/tree/master/DeveloperDocs/vets-api) for new teams
- Provides [introduction to Vets Website](https://github.com/department-of-veterans-affairs/vets-external-teams/tree/master/DeveloperDocs/vets-website) for new teams

## For Engineers


### Frontend
[`vets-website`](https://github.com/department-of-veterans-affairs/vets-website):
- Code repository for the frontend of VA.gov
- Lists common commands
- Links to `VA.gov Client application documentation` as the source of other relevant documentation

[VA.gov Client application documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/):
- Frontend documentation repo on getting `vets-website` up and running locally.
- Provides standards and requirements for visual design and form creation.
- Provides documentation of the client platform architecture and structure.
- The source of this documentation can be found [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/documentation).

### Backend
[`vets-api`](https://github.com/department-of-veterans-affairs/vets-api/):
- Code repository for the frontend of VA.gov
- Provides basic 'up-and-running' instructions


## Non Code Repos - Workflow Management
[Vets.gov-team Repo](https://github.com/department-of-veterans-affairs/vets.gov-team)
- PRIVATE repo for the legacy vets.gov contract that stores non-code documents created and used by the VA.gov Team 
   - Practice Areas
   - Product Documentation for tools created on VA.gov
   - Administrative Instructions
   - Tickets/Workflow for Vets.gov contract [Ends 6/30/19]

[VA.gov-team Repo](https://github.com/department-of-veterans-affairs/vets.gov-team)

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/breakers - Implements the circuit breaker pattern for Ruby using a Faraday middleware
https://github.com/department-of-veterans-affairs/vets-api-mockdata - test data for vets-api
https://github.com/department-of-veterans-affairs/generator-vets-website Maybe?

**Comment by wyattwalter** [comment]
There's also this that we use for common Jenkins functions, in active use: https://github.com/department-of-veterans-affairs/va.gov-devops-jenkins-lib

**Comment by rtluu** [comment]
Thanks for sharing! I've updated the comment above to incorporate all of your additional items!

**Comment by rtluu** [comment]
@gunsch & @rroueche can you think of any additional repos/source we may have missed?

**Comment by gunsch** [comment]
new, replacing the "PRIVATE" parts of `vets.gov-team`:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive

**Comment by rtluu** [comment]
@gunsch I updated the list above to incorporate ☝️ this new repo

**Comment by rtluu** [comment]
I created an MD file for this that lives here. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Administrative/va.gov-repo-map.md

Going to close this issue
