### ISSUE TITLE
Update hourly content auto-deploy solution documentation to use GraphQL

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#20100]
## Details 

VSP FE wrote a design doc for an hourly content auto-deploy solution that would use CMS Export. Due to expected pivot back to GraphQL, we will now need to implement this auto-deploy using GraphQL. 

This ticket represents updating that solution — either updating the design doc or documenting elsewhere (& linking from the design doc). 

## Acceptance Criteria
- [ ] Document hourly content auto-deploy solution that uses GraphQL 
- [ ] Get approval from everyone who approved the previous solution 
   - [ ] Solicit feedback from peer reviews on our team and CMS team 
- [ ] Create tickets to represent implementation of the new solution

**Comment by theodur** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/20312

**Comment by theodur** [comment]
All changes have been approved, and the PR has been merged.
