### ISSUE TITLE
[Content build] Improve the output when a GraphQL query resolves with errors

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#20101]
During a content build, when a GraphQL query returns with errors the output is very minimal. We should make sure to print out all of the details to help us debug what causes a content build to fail.

Relevant thread, https://dsva.slack.com/archives/CDHBKAL9W/p1613585547207700?thread_ts=1613585283.207000&cid=CDHBKAL9W

**Comment by brianalloyd** [comment]
@kelsonic for pickup!

**Comment by kelsonic** [comment]
PR merged, ready for validation + closing

**Comment by brianalloyd** [comment]
Validated and Closing.
