### ISSUE TITLE
EDU: Remove BAH accounts from code / applications.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20107]
As a developer, I need to remove emails and accounts for users that are no longer supporting the project so that they no longer have access to data / systems.

## Assumptions:
1. Code cut-off is still being negotiated between 08/31 and 09/02.  Please confirm with Will prior to beginning this story.

## Acceptance Criteria
1. The following email addresses are removed from all reports in staging and prod:
    a. Delli-Gatti_Michael@bah.com
    b. neel_darrell@bah.com
    c. shawkey_daniel@bah.com
    d. sonntag_adam@bah.com
    e. turner_desiree@bah.com
    f. Darrell.Neel@va.gov
    g. Darla.vanNieukerk@va.gov

2. All BAH accounts are removed from GIDS in staging and prod.

3. All BAH accounts are removed from Feature Flag Access in staging and prod.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/7697

**Comment by zurbergram** [comment]
For AC2 will need to submit a BE platform support ticket to request that all bah email address users are removed from the GIDS database table users

**Comment by zurbergram** [comment]
In Staging:
The CreateDailySpoolFiles Error email only has BAH email addresses.
The SpoolSubmissionsReport mailer only has BAH email addresses that are added when is a 1995 STEM application.

**Comment by zurbergram** [comment]
For AC2 
https://dsva.slack.com/archives/CBU0KDSB1/p1631713339075000

**Comment by dneel-bah** [comment]
No emails were received today, and I have confirmed that I no longer have GIDS access after OCTO has confirmed removal of accounts.  Closing this issue as completed.
