### ISSUE TITLE
[design + content] Define signed in/out states of the 'File a Higher-Level Review' page

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#2011]
## User Story or Problem Statement
As a Veteran, I need to be prompted to log in to VA.gov so I can file a Higher-Level Review online. If I'm logged in, I need to know what to expect during the application process.

## Goal
Define the design and content for the signed-in/out states of the Higher-Level Review page. 

## Design pattern for the Apply Now page
https://dev-design.va.gov/patterns/benefit-applications#apply-now

## Signed out default shell (needs design/content update)
![Screen Shot 2019-09-23 at 3.31.07 PM.png](https://images.zenhubusercontent.com/5b744a5479b04b75031e37c2/9f75ec2e-367f-4690-b893-196f717ea914)

## Acceptance Criteria
- [x] Designs for the signed-in/out states of the page have been shared with the team
- [x] Content has been reviewed and approved by VSP
- [x] Link to design/content is attached in Comments
- [x] Front-end ticket is created for implementation

**Comment by smoonpeyes** [comment]
@peggygannon Can you review content on the pages below?

**Higher-Level Review Apply Now (Signed-Out state)**
https://vsateams.invisionapp.com/share/W5U21BDFTQK#/385994365_Signed_Out-File_A_Higher_Level_Review

**Higher-Level Review Apply Now (Signed-In state)**
https://vsateams.invisionapp.com/share/W5U21BDFTQK#/385994366_Signed_In-File_A_Higher_Level_Review_

**Comment by smoonpeyes** [comment]
@rileyorr Assigning you to this ticket to incorporate any feedback from @peggygannon after I'm gone.

**Comment by peggygannon** [comment]
@rileyorr  I've made comments in the Higher-Level Review mock up. I have some questions about some of the content on the screens. I think it would be helpful if we met to discuss and go over my questions. Let me know when would be a good time to discuss? thx

https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/385994365/comments

cc @meganhkelley

**Comment by rileyorr** [comment]
@peggygannon Thank you for your comments! I'm happy to meet to discuss the content. I'm available today between 2:00 pm - 4:00 pm ET, tomorrow between 1:00 pm - 3:00 pm ET, and Friday between 10:00 am - 12:00 pm ET. Let me know what time works for you!

**Comment by peggygannon** [comment]
Thanks @rileyorr How about we discuss tomorrow at 1:30 p.m. ET? I can send you an invite. 

cc @meganhkelley

**Comment by peggygannon** [comment]
@rileyorr Hi, Riley, I updated the HLR mockup with some additional content recommendations. Please let me know if you have any questions or need to sync up with me over the phone. I've made a note that some of my edits should be shared with a SME to ensure I've interpreted the content accurately.  Let me know if you have any questions! 


https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/385994365/comments

cc @meganhkelley @YanaRoy

**Comment by carolynwill** [comment]
Blocked due to InVision access

**Comment by YanaRoy** [comment]
@carolynwill - please review the updates peggy included in her content review and incorporate them into the design mockups.
