### ISSUE TITLE
Project Kickoff [Content and Localization Team - Anchor Links]

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20111]
## Steps to complete Project Kickoff
- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] VFS: Attach all relevant artifacts to the ticket
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting

* Link to rough draft of product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))

DRAFT: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/anchor-tags.md

* Explanation of the problem space

Today, question/answer links are not automatically generated in a way that's easily accessible by visitors to the Coronavirus FAQs page. Someone seeking a link to a specific FAQ would need to go into the 'inspect' element in their browser to find the link; most users won't bother to do that, even if they know how.

So when a vet, caregiver or customer service representative wants to direct someone to a specific question/answer on the Coronavirus FAQ page, they can only share a link at the page level leaving it up to the recipient to navigate through the long list of information to find the specific content they seek. This can be frustrating and time-consuming.

The goal of this experiment is to make it quick and painless to share specific content contained within a page.

- Any other artifacts you have so far

- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Sharon Kasimow**
- DEPO Product Lead (required): **Jen Lee**
- Entire VFS team (recommended): **All**
- Other specialists: **Fareez Ahmed, Josh Kim, Tze Lei, Jason Woodman, Mikki Northius**

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES/NO
- Yes

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
* **Please schedule for 2/26 @ 2pm et**
- Write that preferred time slot here (on this ticket), and VSP will send you a meeting invite
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

**Comment by shiragoodman** [comment]
Meeting scheduled for 2/26 at 2pm ET

**Comment by SKasimow** [comment]
@shiragoodman @andreahewitt-odd Hello - per convo with Shira, I am closing this ticket out and will instead open a ticket using the  Collab process to kick-off this initiative.

Sharon

cc: @jenniferlee-dsva
