### ISSUE TITLE
Access for Emily Wu

### ISSUE THREAD

**Issue by emilywu-tw** [department-of-veterans-affairs/va.gov-team#20116]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Emily Wu
- Please Provide your email.
   > ewu@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @department-of-veterans-affairs/thoughtworks 
   > Role: Developer
   > Company: ThoughtWorks
   > I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana / Sentry so we can
   >   - Modify / update Jenkins job configs
   >   - Kick off Jenkins jobs
   >   - Review Prometheus data, some of which is imported into the scorecard
   >   - Review Grafana data for the scorecard
   >   - Review logs in different environments to facilitate testing along the path to production

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDC7t1P051B4ahlE82CxthJyR1TW2qaACaXmI8nl6ChOvVi4w6uCGPPQgGOAApP/Avlr15bB2pdeqpoY2Ut7iR5UfrN3AOVjEaRW+7JzxJEmd40tENeFSGseCnDEE485jqcvV2bZZ3uH2Fmd66Nsc0UADHFdv2ncYarYEns0n7mwnX57R98dC7ZGCMJksi4wYj6TEUrmghyzii6ryLPTCAsbD5N4ZL89veWpsDqSLcAF7yxAiH5NJ4sWTgfqBdpBrYidJEaak2OXsvc5hmsbgUiNYMjXPKacLTgtEd+iREwQWgdfBOPFe8gr2vGc0P4BHVbqc25FgsqTadyhFNwD3umzZ35g3toFe6OAFKCXoLXLNCv7kVI/aFogV7xYQnBQjJVfOux4CJgPwLeRhco3Vv1bZSsL2RtdlfdBsPiJzFt472oxi6QgPeBqY89gvkyf5zi55qfLLMnrXD+j71fKqT+3Ax8ci+x3UAm6Z55HD2ItpfAEAsElcj4hkThvBhj6Ws= emilywu@Emilys-TW-MBP
```

- Grant AWS Console access?
  > YES
- What AWS services do you need access to and why? 
  > I will be needing AWS console access in order to use SES, Pinpoint, Cloudwatch, Cloudtrail, SNS, and the Lambda services. This will allow me to work on and test functionality that the VANotify team is implementing.

**Comment by emilywu-tw** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
@Jeff-Hayter 
Requesting AWS Access
User: @emilywu-tw 
COR: Courtney Bethea

**Comment by emilywu-tw** [comment]
Hi @jsev-io @Jeff-Hayter , I was just informed that my COR is now Cecilia Lee (cecilia.lee@va.gov). Apologies for any issues this may have caused!

**Comment by emilywu-tw** [comment]
hey @jsev-io, just wanted to check in and see where this is at. Thanks!

**Comment by jsev-io** [comment]
cc: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@jsev-io Approved for AWS.

**Comment by mleclerc00** [comment]
Thanks, will get around to this today
