### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by KD-VA** [department-of-veterans-affairs/va.gov-team#20112]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [ ] Domo
_Please list any additional requirements, if any._

## Date Required
_Please share the date you require access._

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bmcgrady-ep** [comment]
Hi @KD-VA! Thank you for opening the access request. Can you please provide an email so that we can give you access? Also, are you wanting access to Google Analytics, DOMO, or both?

**Comment by KD-VA** [comment]
Hi Ben,

Thanks for your help. You want the gmail account? This would be Dhillon.VA@gmail.com<mailto:Dhillon.VA@gmail.com>. And I need access to both please, but especially Google Analytics. Thank you!

Respectfully,

Kiran Dhillon

Veterans Experience Office
Department of Veterans Affairs

**Comment by bmcgrady-ep** [comment]
@KD-VA - Thanks for the update. I provisioned ou with access to both Google Analytics and Domo. Please let me know if you have any issues with your access.

**Comment by KD-VA** [comment]
Ben,

Thank you so much! I believe I have access now to what I need. Thanks!

Respectfully,

Kiran Dhillon

Veterans Experience Office
Department of Veterans Affairs

**Comment by bmcgrady-ep** [comment]
Great! I am closing out this ticket. Feel free to reopen if you run into any access issues.
