### ISSUE TITLE
Missing copy on Direct Deposit account summary

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20117]
## What happened?
On the Direct Deposit overview page, the word "account" is missing after "Savings" or "Checking".

## Specs:
- Devices: Any
- Test user: vets.gov.user+50@gmail.com (or any user with an existing bank account)

## Steps to Reproduce
1. In the app, navigate to the Direct Deposit landing page. Observe the Account summary. 
2. Compare against the designs: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/431636875
3. Notice how the word "account" is missing next to Savings or Checking

## Desired behavior
1. When an account has been added to the user's profile, it should either display as:
     - Savings account
     - Checking account
**Note**: In the designs, the word "account" is capitalized. This should be lowercase, as specified in the Desired Behavior above.

## Acceptance Criteria
See desired behavior

## Bug Severity
- 4 - Low

## Screen shot(s) 
![Screen Shot 2021-02-17 at 1.57.42 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/95576015-6de1-4d8c-94b6-d8dbced74993)

**Comment by digitalken** [comment]
PASS 2/22/2021 - "account" is now present.  Closing.
