### ISSUE TITLE
CMS Export environment audit

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20121]
## Issue Description
This issue will collect CMS export discrepancies that were detected by viewing VAMC pages in the dev environment. 

### Images
<details>
<summary> Location images are not visible on system home page, Locations page and facility pages</summary>

![image](https://user-images.githubusercontent.com/55411834/108277690-1090d800-7137-11eb-96c3-1e56689f61ea.png)

</details>

<details>
<summary> Story thumbnail image is not visible on system home page or on individual story pages</summary>

![image](https://user-images.githubusercontent.com/55411834/108277805-433ad080-7137-11eb-807e-337a2b466f10.png)

</details>

<details>
<summary> System image is not visible between heading and CTA buttons </summary>

![image](https://user-images.githubusercontent.com/55411834/108278064-ad537580-7137-11eb-9450-2a7c1384b11d.png)
</details>

Campus maps and [Consolidation Building floor plans](https://dev.va.gov/pittsburgh-health-care/consolidation-building-floor-plans/) do not display on https://dev.va.gov/pittsburgh-health-care/university-drive-campus-map/

Staff photos do not display (such as on https://dev.va.gov/pittsburgh-health-care/programs/cardiology/)

## Events
<details>
<summary>Events block is completely missing (should follow stories on system home page) </summary>

![image](https://user-images.githubusercontent.com/55411834/108278200-ef7cb700-7137-11eb-90cb-c1f39f57c776.png)

</details>

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
The issues with missing images will need to be addressed by VSP.

Are we supposed to be showing past Events on the system home page?

**Comment by mmiddaugh** [comment]
No longer needed. Closing
