### ISSUE TITLE
Anchor Tags | User Experience | Using Copy Feature

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20125]
## User Story

As a product manager, I would like to clearly convey the ability to copy and share a link to a specific piece of content on a given  page.

As a user I would like to have this feature because it would help me easily share specific information on pages that can be lengthy.

## Expected Behavior

~**Please note, this ticket just describes the behavior/function of the icon. Placement, colors, visual treatment etc will be provided by~
~Creative team**~

**COPY**

~1. The "Copy" icon will be shown at the end of each question on the Coronavirus FAQ page~
~2. Upon hovering over the icon, the circle enclosing the icon will change color to help users understand that the icon is actionable~
~3. Once the icon is clicked on, a confirmation message "Link Copied" will display next to the icon~
~4. The icon will change color to provide a visual clue that it has been copied (although it can be copied again)~
~5. The icon will revert back to the initial color upon a page refresh or new visit~

### design specs
feel free to [inspect specific colors, sizes](https://www.sketch.com/s/e4461f10-60cd-46f6-9479-69f0a4d71bab/a/ygVwY3b#Inspector), etc in sketch for teams!

#### mobile

![image](https://user-images.githubusercontent.com/12564977/109320070-9be82880-781d-11eb-8954-be4f3f4d61a2.png)

#### desktop (linking to an accordion)

![image](https://user-images.githubusercontent.com/12564977/109320349-eb2e5900-781d-11eb-8e35-304ffc73d486.png)

### accessibility and design notes
1. height and width of the button to the line height of our `h3`s hopefully to avoid weird line height changes when type wraps (which happens to be ~26px)
2. When the button + text cannot be displayed to the right of the button (because there is not enough room to the right of the button), it displays to the left, overlapping the h3 (see spec)
3. we could consider making the entire h3 + button interactive @1Copenut i defer to your expertise here
4. on click/tap, we display "Link copied" (or whatever the content team recommends) for 10 seconds
5. on click/tap, use a live-region to announce the "Link copied" text and keep the focus on the button. Since the text is an addition, we could do something like
```
<div aria-live="polite" aria-relevant="added text">
  <button aria-label="Copy RELEVANT_TEXT sharable link">
    <!-- SVG or Font Awesome goodness -->
  </button>
  <div>
    <p>Link copied</p>
  </div>
</div>
```
6. The accessible label will contain relevant, content specific titles for the screen reader to announce, e.g. “Copy [**How can I stay informed about COVID-19 vaccines at VA**] sharable link”.
7.  in the accordion instance, we will link the title of the accordion
8. behavior is identical on desktop and mobile, excluding a hover state
9. we do not need a `visited` state for the button

**PASTE**

1. Upon pasting the copied link into an application such as email, Slack, Facebook etc., the link will display as a hyperlink URL

## Acceptance Criteria

Mobile View:

- [ ] The copy icon will be visible at the end of each question
- [ ] Upon hovering, the square enclosing the icon will change color to help users understand that the icon is actionable
- [ ] Once clicked, the text "Link copied" is displayed next to the icon for 10 seconds
- [ ] On  click/tap when using a screen reader, the screen reader will announce the "Link copied" text and keep the focus on the button
- [ ] The accessible label will contain relevant, content specific titles for the screen reader to announce, e.g. “Copy [How can I stay informed about COVID-19 vaccines at VA] sharable link”.
- [ ] When the button + text cannot be displayed to the right of the button (because there is not enough room to the right of the button), it displays to the left, overlapping the h3 

Desktop View (linking to an accordion):  

- [ ] The copy icon will be visible at the end of each answer in the Q/A
- [ ] Upon hovering, the square enclosing the icon will change color to help users understand that the icon is actionable
- [ ] Once clicked, the text "Link copied" is displayed next to the icon for 10 seconds
- [ ] On  click/tap when using a screen reader, the screen reader will announce the "Link copied" text and keep the focus on the button
- [ ] The accessible label will contain relevant, content specific titles for the screen reader to announce, e.g. “Copy [How can I stay informed about COVID-19 vaccines at VA] sharable link”.
- [ ] When the button + text cannot be displayed to the right of the icon/button (because there is not enough room to the right of the button), it displays to the left, overlapping the h3 
- [ ] Shareable link takes user to the title of the accordion which is defaulted to open

Desktop (for questions not within an accordion)

- [ ] For Q/A's **not** contained within an accordion, place icon at the end of the question
- [ ] Upon hovering, the square enclosing the icon will change color to help users understand that the icon is actionable
- [ ] Once clicked, the text "Link copied" is displayed next to the icon for 10 seconds
- [ ] On  click/tap when using a screen reader, the screen reader will announce the "Link copied" text and keep the focus on the button
- [ ] The accessible label will contain relevant, content specific titles for the screen reader to announce, e.g. “Copy [How can I stay informed about COVID-19 vaccines at VA] sharable link”.
- [ ] When the button + text cannot be displayed to the right of the icon/button (because there is not enough room to the right of the button), it displays to the left, overlapping the h3 
- [ ] Shareable link takes user to the title of the accordion which is defaulted to open

**Comment by youngfreezyVA** [comment]
hi @SKasimow can you let me know which colors to use for which states? ie clicked, hover, page load

**Comment by SKasimow** [comment]
@youngfreezyVA Hello - yes, included the color (and other details) in this ticket (comment section):

- https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19867 

**Pasting here too:** 
> @youngfreezyVA Hi - until the new design resource is available to detail the necessary specs, please mock as best as you are able with the following design elements we touched on earlier today with Jen:

- decrease the size of the icon
- change to blue
- place a thin, medium gray circular line around the icon (a la NYT)
- upon hover add background color to circle (try the medium gray and we can see if it shows up well with the blue icon) (a la NYT)
- use sentence case for test "Link copied"
- display "Link copied" for 5 seconds
- after clicking icon, the color should change from blue to gray (?? I don't recall what color we said to use for this)
- for Q/A's inside an accordion, place the icon at the end of the answer text
- for Q/A's not contained within an accordion, place icon at the end of the question once accordion is in OPENED state
- if there is room, "Link copied" should appear to the right of the icon
- if there isn't enough room, or if adding the text will result in an additional line, place"Link copied" text to the left of the icon
- in focus state there should be a light blue border around the icon to help with focus
- the"Link copied" text should have same border in focus state

**Comment by SKasimow** [comment]
@youngfreezyVA let me know if that is specific enough until we have design support on - board

**Comment by youngfreezyVA** [comment]
yes that works, thank you

**Comment by SKasimow** [comment]
@youngfreezyVA: adding the design specs from Ryan for your convenience.

### design specs
feel free to [inspect specific colors, sizes](https://www.sketch.com/s/e4461f10-60cd-46f6-9479-69f0a4d71bab/a/ygVwY3b#Inspector), etc in sketch for teams!

#### mobile

![image](https://user-images.githubusercontent.com/12564977/109320070-9be82880-781d-11eb-8954-be4f3f4d61a2.png)

#### desktop (linking to an accordion)

![image](https://user-images.githubusercontent.com/12564977/109320349-eb2e5900-781d-11eb-8e35-304ffc73d486.png)





### accessibility and design notes
1. height and width of the button to the line height of our `h3`s hopefully to avoid weird line height changes when type wraps (which happens to be ~26px)
2. When the button + text cannot be displayed to the right of the button (because there is not enough room to the right of the button), it displays to the left, overlapping the h3 (see spec)
3. we could consider making the entire h3 + button interactive @1Copenut i defer to your expertise here
4. on click/tap, we display "Link copied" (or whatever the content team recommends) for 10 seconds
5. on click/tap, use a live-region to announce the "Link copied" text and keep the focus on the button. Since the text is an addition, we could do something like
```
<div aria-live="polite" aria-relevant="added text">
  <button aria-label="Copy RELEVANT_TEXT sharable link">
    <!-- SVG or Font Awesome goodness -->
  </button>
  <div>
    <p>Link copied</p>
  </div>
</div>
```
6. The accessible label will contain relevant, content specific titles for the screen reader to announce, e.g. “Copy [**How can I stay informed about COVID-19 vaccines at VA**] sharable link”.
7.  in the accordion instance, we will link the title of the accordion
8. behavior is identical on desktop and mobile, excluding a hover state
9. we do not need a `visited` state for the button

**Comment by SKasimow** [comment]
@jenniferlee-dsva Hi Jen - can you take a look at this ticket (namely the acceptance criteria) to make sure I have everything represented correctly based on Ryan T's mocks. I also want to make sure the placement of the copy link for NON-accordion questions is correct since that wasn't covered in this update.

Thanks!

**Comment by noahgelman** [comment]
The design proposed looks accessible.

The accordion  copy link however is a bit confusing. I think the copy link icon should go next to the link that it is copying as opposed to the bottom of the section.
