### ISSUE TITLE
[DISCOVERY] Link Previews | Anchor Links

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20122]
After pasting a copied Coronavirus FAQ link into an application to share (ie: Slack, Outlook or Gmail) the URL along with a "link preview" appears (see example below).

https://www.va.gov/coronavirus-veteran-frequently-asked-questions/#i-dont-have-symptoms-but-i-fee

**Veterans AffairsVeterans Affairs
Coronavirus FAQs: What Veterans need to know | Veterans Affairs
Get answers to VA related Veteran questions about the coronavirus, your VA health appointments, health facility questions, and what Veterans and family members need to know.**

While a preview like this can be useful, if it isn't specific to the Q/A being shared it could  generate  confusion on the part of the sender and/or recipient. 

Therefore, we need to understand:

- Where is the "link preview" generated?

- Is the preview modifiable and able to be tied to content from the specific Q/A being shared vs the default page-level preview?

- Are we able to set up previews as well as dis-able them?  (I believe a user can configure previews to show/not show but unsure on the dev side what we have control over)

**Comment by youngfreezyVA** [comment]
researching the following after consulting with Nick + Kelson:

- https://github.com/department-of-veterans-affairs/vets-website/blob/676cffae72c083f648de26ad8320e69ce86808b6/src/site/includes/metatags.drupal.liquid#L63
- https://ogp.me/
- https://api.slack.com/robots

**Comment by SKasimow** [comment]
@youngfreezyVA can you point this ticket?

**Comment by SKasimow** [comment]
@closing ticket since we determine ok to leave "as-is" for current experience
