### ISSUE TITLE
Analytics Implementation  [VAMC - Lebanon-health-care]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#20131]
Analytics Implementation  [VAMC - lebanon-health-care website]

# Google Analytics Implementation 

## Description
- Google Analytics implementation is required for lebanon-health-care VAMC website to match the pilot project and standards as set at va.gov/pittsburgh-health-care/ , so owners, PAOs, and stakeholders can have a consistent view and standard data sets to review and make decisions from regarding VAMC web pages.

- Who is this request for?
    * VAMC-upgrade - va.gov/lebanon-health-care
    * Product Manager - Stan Gardner - sgardner@govermentcio.com
    * Product Owner - Dave Conlon - david.conlon@va.gov
   
    
- What team/project is this work for?
    * VAMC - Upgrade
     * Main Slack Channel - vsa-vamc-upgrade
          
- Provide the Domain where Google Analytics needs to be implemented
    * va.gov/lebanon-health-care/
    
    _Identify if PII is passed in URL or title tag_
    * N/A
   
- Please provide any upcoming deadlines or important milestones
    **Go-Live for lebanon-health-care, set in 30 days from Dual-State.  Estimated approximately February 9th, 2021**
   
    - Typical Website Interactions to Track

    - * Please implement the exact KPI and tags set up for Pittsburgh-health-care, see the original request below 
    
    - [Please see most recent VAMC Analytics Implementation request #18822](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18822)
    - [Please also see original VAMC Analytics Implementation for Pittsburgh request #1846](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1846)
    
- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - N/A  "This is a website open to public access via va/gov

- Certain conditions/responses that need to be reviewed
    - N/A

- Additional Comments

    ** VAMC- upgrade will be repeating this process request 140 more times as VAMC websites come online.  This should become a standardized template to initiate on all future VAMC websites.**

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by jonwehausen** [comment]
Hi @mmiddaugh / @SgardnerPMP ,

## KPI Update
- I made sure to give your [KPI dashboard ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15132) a read prior to this post. What you have had requested for tracking we will have covered following implementation 👍 -- the next phase will be for us to work with you all on those items and groom them into measurable KPIs to articulate within the dashboard. 


### Dev Notes
- Please have your FE's reference [this data layer specification](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18822#issuecomment-772103021) for all other VAMC page roll-outs moving forward. 
- There are several items that have prior tracking -- however have slight modifications to the event names, taxonomy and data layer variables to push towards our goal of GTM standardization

Please reach out with any further questions you may have.

**Comment by joanneesteban** [comment]
@SgardnerPMP can we close this ticket as well?
