### ISSUE TITLE
0994: Remove Feature Flag for form updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20138]
As a developer, I need to remove the 'edu_form_omb_and_expiration' feature flag toggle so that it is no longer configurable, and the new functionality is permanent.

## Assumptions:
1. This feature flag was created in #18293
2. This work has been signed off by EDU as of 2021-03-19.
3. The new functionality is live in production with no need remaining need for the toggle.
4. We will wait to remove the feature flag (by merging in these changes) until the week of 04/05.

## Acceptance Criteria
1. The feature flag 'edu_form_omb_and_expiration' is removed.
2. The feature flag is not displayed here: https://[environment]-api.va.gov/flipper/features.

## Supporting Artifacts:
1. N/A

**Comment by sonntag-adam** [comment]
In all envs. closing story.
