### ISSUE TITLE
Attachments page | No file added (1 of 6)

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#20139]
## User Story
As a user, when I'm composing a message, I want the ability to upload a file or photo from my device and then upload it to my secure message. 

## Acceptance Criteria
1. Selecting the **Add files** button from the Compose a Message form page routes to a new page, called "Attachments"
     - "Cancel" button in the header. Selecting this button returns to the **Compose a Message** page
2. Create UX/UI for this page
     -  Content on this page is hard-coded
     - File formats are styled as a bulleted list
3. Below the page description, display large button: "Select a file" (routing not needed for this story)

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449230092

## Accessibility Implementation Guidelines
 
- Mark "File attachment" as Header 2
 
**Select a file button**
- accessibilityLabel = "Select a file"
- accessibilityRole= "button"
- accessibilityHint= "Select a file from your device"

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

Attachment restrictions:
     - User may attach up to 4 files
     - Acceptable formats: doc, docx, jpg, pdf, png, rtf, txt, xls, xlsx
     - Size limitations:
       - Single attachment cannot exceed 3 MB
       - Total attachment cannot exceed 6 MB

**Comment by ashley-matthews** [comment]
### **User Story**
As a user, I want to be able to add attachments to my message so that I can provide more context to my message. 

### **Acceptance Criteria**
- When a user replies to message thread or composes a new message, they can add an image or file from their phone to the message
- When a user selects to add an attachment, they can choose a file from an album or use their camera to take a photo

### **Tech Notes**

### **Design**

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/21/2021 - Looks good on Android and iOS.
