### ISSUE TITLE
Maintain up-to-date stats for the 10-10 Apps

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#20142]

**Comment by kevinmirc** [comment]
Slack thread on pushing clowdwatch logs to Prometheus/Grafana:

> **Mike Chelen (he/him)**
> @Kevin Mircovich ah ok hmm, can the raw submission metrics be written from cloudwatch into prometheus?


> **Neil Hastings** 
> The CMS team has done this to monitor instance of a log certain log message appearing.  Let me know if you need any support.  FYI, all when loki goes live, it's my understanding that logs will no longer be in cloudwatch so this method will stop working

more: https://dsva.slack.com/archives/C01UB5A823V/p1619099248036400

**Comment by SKasimow** [comment]
Hi @lihanli - just tagging you on some epics/tickets related to back-end tooling. Once you have a chance to review, lmk and we can set up time to go through recommendations. Thanks!

**Comment by lihanli** [comment]
i don't think this issue is necessary anymore, logs have already been migrated from cloudwatch to loki

**Comment by SKasimow** [comment]
Closing...any open tickets are contained within: https://app.zenhub.com/workspaces/vsa---10-10-team-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/37335
