### ISSUE TITLE
Switch to using a GraphQL filter to remove unneeded QA nodes

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#20147]
Now that we execute multiple GraphQL queries, we have more flexibility in writing them. For example, as part of the `filter` in the `nodeQuery` for QA Nodes, we can add a condition to require `fieldStandalonePage` to be `true`. Currently, we are just querying for all of the QA Nodes and then filtering the ones we don't need later on in the the build. We will get a small performance bump from this in our build.

Steps
- Add the GraphQL filter here, https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/nodeQa.graphql.js#L104
- Remove this function, ` excludeQaNodesThatAreNotStandalonePages` https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/create-resources-and-support-section.js#L338
- Test using `yarn build:content --pull-drupal`

**Comment by kelsonic** [comment]
@brianalloyd I don't think we should add this, after adding the field_standalone_page filter it actually increased the time from 0-1s to around 7-15s per node QA slice:

![image](https://user-images.githubusercontent.com/12773166/126648216-89caed95-ebe7-4f5b-9e7c-7a64cfd3d1d5.png)

![image](https://user-images.githubusercontent.com/12773166/126648305-fc539b39-86f4-422a-898c-906b6eaa5f0a.png)

**Comment by kelsonic** [comment]
Going to close this ticket for now, feel free to reopen if desired! 🙂
