### ISSUE TITLE
Add RTL tests for "Benefits you might be interested in"

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#20159]
We should update the existing `ApplyForBenefits.unit.spec.jsx` with new tests that cover the "Benefits you might be interested in" content.

Ideally the tests would be added to [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16093), but Jenkins constantly fails unit tests so I'm merging it right now since I'm able to.

**Comment by Samara-Strauss** [comment]
Done!
