### ISSUE TITLE
Veteran names need to conditionally render to avoid null and "middleName": "NOT_FOUND"

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#20151]
Not all Veteran accounts have all of the names in them. When a first, last or middle name is rendered the app should be filtering out any name values that are undefined, null or "NOT_FOUND". 

ideally this is done with a helper function that takes the key for name value as string and returns the proper formatted string or empty string/optional string

**Comment by digitalken** [comment]
PASS 2/22/2021 - Previously, a user showed up as Sean Not_found Gptestkfive.  Not the 'Not_found' is gone and only first and last names display.  Closing.
