### ISSUE TITLE
Create Word doc for COVID vaccine translation effort

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#20169]
## Issue Description
We need to send our [COVID-19 vaccine page](https://www.va.gov/health-care/covid-19-vaccine/) to a translator so we can create a Spanish version of the page. A sitewide content member needs to create a Word doc with all of the content. We should make sure to number each question so that when the translation comes back it is easier to match up the Spanish with the English version. 

## Tasks
- [x] Create Word doc of vaccine page (Selina)

## Acceptance Criteria
- [x] Word doc created and numbered with all content ready to be sent to translator

**Comment by lunascoop** [comment]
@RLHecht the Word doc has been created.

[COVID-19 Vaccine Page Translation 2-18-21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6005916/COVID-19.Vaccine.Page.Translation.2-18-21.docx)

**Comment by RLHecht** [comment]
Thank you @lunascoop ! @DanielleThierryUSDSVA here you go!

**Comment by DanielleThierryUSDSVA** [comment]
Thank you so much, @lunascoop @RLHecht!

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow
