### ISSUE TITLE
General Analytics Request for Search & Discovery Team - Right Rail Data

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#20168]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Search & Discovery Team - Onsite Search 

    
- What type of analytics support are you looking for?
  - [X] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested

What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

- Jan 1 , 2019 - Jan 31, 2021

## Analytics to Track Down
> - [ ] Would like to get a better understanding of how many users are clicking on the links in the right rail on the search result page. 

![Right Rail Links.png](https://images.zenhubusercontent.com/5f7f60ca14e26c658f77b9f5/a1dc3dea-fffc-41b7-8592-128bf063dcb5)

## Which Product Questions are you trying to answer?

- We are collecting data regarding the effectiveness and usage of the links on the right side of the search results page. The right rail contains links which during user research it has been identified that they may not be as effective as we might hope. We are interested in understanding how many users click on each of those links. A monthly breakdown would be great to see how useful those links have been over time.

## Other Helpful Questions to think through
- Who is your audience? Search and Discovery team
- Why do you need this data? to determine usefulness of links in right rail
- What are you hoping to find? how many users click on those links looking for information
- What is your hypothesis that you're hoping the data will support? We are hypothesizing that few users are clicking on those links and they are not very useful. I fact we think they may be detracting from the overall experience. 
- What area of the VA are you hoping to assess? Search experience on VA.gov
- How frequently do you need this data? Just once for now. Based on the data we may choose to remove the right rail entirely. 

## Link to Metrics
n/a

## Additional Comments
Hopefully this is a singular ask. 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
## Next Steps
- Lauren to supply GA report link for `nav-searchresults` link clicks

**Comment by denisecoveyduc** [comment]
Hi @laurensimpson14 just wondering if we have any ETA for this report link?
cc: @jonwehausen

**Comment by laurensimpson14** [comment]
Hi @denisecoveyduc, 

I've pulled a report to show the total number of clicks to the right rail on the search results page. The date range is set to Jan 1, 2019 - March 23, 2021. In your request you asked for it to go to Jan 31, 2021, but Google Analytics will not allow the end date to be set in the future. If you meant to put Jan 31, 2020 then you can modify the dates using the date range found in the top right corner: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20190101&_u.date01=20210323&_r.drilldown=analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22Navigation%20-%20Search%20Results%20-%20More%20VA%20Search%20Tools%22,0%5D%5D/

Please note - the report above may take a while to load! Also, in the report I linked above ^ there are 6 results as opposed to the existing 5 in the menu. It looks like item #6 (VA handbooks and other publications) was renamed or removed.
 
I know your goal is to see if this menu is helpful to users, so I've also pulled a report on how many pageviews the search results page has gotten in the same time period. The report linked above shows that the menu was clicked on 240,198 times, and this report shows that the search results page was viewed 12.4 million times - so nearly 2% of all pageviews used the right rail menu: https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20190101&_u.date01=20210323&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fsearch~2F/
 
I hope this helps you with analyzing the benefit of the menu.
 
Please let me know if these links fully address your request and if you need anything else.

**Comment by denisecoveyduc** [comment]
Hi @laurensimpson14 this is fantastic thank you! As we hypothesized those links aren't being used that frequently. 
As we explore how to integrate those into our new designs we wondered how their usage compares to the other search tools we have identified. What we would love to understand is how to sort this list by popularity (aka usage) so that we highlight the most frequently used search tools first. Do you know if there are existing GA reports or DOMO dashboards that we could review for the following search tools?

GI Bill® Comparison Tool
Find a Yellow Ribbon school
Resources and Support
Grave Locator
Find Locations
Find a Facility

**Comment by laurensimpson14** [comment]
Hi @denisecoveyduc I've done a search and I haven't found any search-related dashboards. If you're looking for a quick way to glance at popularity and compare overall search volume across all products I can create a small custom report in GA with each of those search start pages and unique searches. I should have time to get this completed on Monday afternoon.

**Comment by laurensimpson14** [comment]
@denisecoveyduc I've created a custom report to show popularity/usage by the number of pageviews of each of the tools. The only tool that I was not able to include was the Grave Locator tool. Unfortunately, I'm not able to get data for that page since we don't attach it to our GA property. 

Here is a link to the report: https://analytics.google.com/analytics/web/template?uid=0-uCbBC2T0WTT4mIQ3iXSQ
For the View select VA.gov - Production > All VA.gov Website Data [Production] (176188361). You can change the date range in the top right corner. 

Below is a list of what search tool the column "Page path level 2" is referencing in the report.
	1. /find-locations/ - Find a Location Tool
	2. /search/ - Site Search Tool
	3. /gi-bill-comparison-tool/ - GI Bill Comparison Tool
	4. /resources/ - Resources and Support
	5. /education/ - Find a Yellow Ribbon School
	6. /directory/ - Find a Facility

Please let me know if this addresses your request, if you need anything else, or if this ticket is OK to close out.

**Comment by denisecoveyduc** [comment]
@laurensimpson14 Thank you! This is very valuable information for us and exactly what we were looking for. Ok to close out this issue now. 

cc: @MarciMcGuireGCIO I will DM you but worth looking at this information from your perspective as well. If you change the data range for the FY 2020 you can see form related searches appear on rows 7,11,13,15 and 16 

cc: @johnhashva FYI - We anticipate using this information to inform the results page redesign @mgleo is working on now.

**Comment by laurensimpson14** [comment]
Wonderful, I hope you have a great rest of your day!

**Comment by cindymerrill** [comment]
@denisecoveyduc I appreciate you sharing the links to these analytics reports with me (during a meeting yesterday), but I'm unable to see the reports. When I click on the link, I get taken to the "Welcome to Google Analytics" page instead. Is there something not set up correctly in my account, or do I need to have some additional access or privilege?

**Comment by denisecoveyduc** [comment]
@laurensimpson14 Can you advice? Will Cindy or others require special permission to access this report? Thanks in advance.

**Comment by laurensimpson14** [comment]
@cindymerrill It looks like you have the right permissions in GA to be able to view the report (under the email 
cindy.merrill@adhocteam.us). Is it possible that you were trying to access it under a different account? 

When you click the [link to the report](https://analytics.google.com/analytics/web/template?uid=0-uCbBC2T0WTT4mIQ3iXSQ) it should ask you to select a View. The View in this case is under VA.gov - Production > All VA.gov Website Data [Production].

**Comment by cindymerrill** [comment]
Hi Lauren,

I was at first in the wrong google account, and when I changed it, here's
what I see (is this the report I'm supposed to be seeing?):

[image: image.png]

**Comment by laurensimpson14** [comment]
@cindymerrill Would you mind re-attaching the screenshot? I'm only seeing text saying that there is an image, but I don't see the actual image.

**Comment by cindymerrill** [comment]
Here it is (guess it didn't attach when I replied via email):
![image](https://user-images.githubusercontent.com/69914583/113431488-aeabcb00-9390-11eb-88e8-f6d3b100dbfc.png)

**Comment by cindymerrill** [comment]
I appear to not have the access I need to see the dashboards that @brianalloyd and @denisecoveyduc have showed me, so maybe that's the same reason I'm not seeing your reports correctly.

**Comment by laurensimpson14** [comment]
From what I can tell you have the right permissions, so I'm not sure what could be causing the issue. I'm looping in @jonwehausen. Jon, can you help us figure out why Cindy is not able to view the reports?

**Comment by jonwehausen** [comment]
Thanks for investigation @laurensimpson14 

@cindymerrill -- Certainly strange you have not been able to view reports up to this point..., we apologize for the inconvenience -- At this time I temporarily removed and re-added `cindy.merrill@adhocteam.us`. Please check your email for a GA invitation and accept the invite, if after acceptance you're still not able to see reports, we may need to jump on a call briefly and do a screen share to further diagnose what may be happening here. 

Thanks so much.

**Comment by cindymerrill** [comment]
I accepted your new GA invitation, but still I can't see any reports.
Whenever I click the link of a GA report, I see a "Welcome to Google
Analytics" page with my personal Google account (I can tell by the profile
picture). So I change to my Ad Hoc Google account, and then I see a GA
screen, which is not the report that was just shared with me.

Also, I'm unable to open some DOMO dashboards, such as this one that Brian
wanted me to see: https://va-gov.domo.com/page/1522082003

Yes, please let's meet and do a screen share so you can see what's going on.

Thanks!

--Cindy

**Comment by laurensimpson14** [comment]
@cindymerrill Would you be available tomorrow to do a screen share? Any time between 9:00 am - 11:00 am EDT, 12:00 - 12:30 pm EDT, or 3:00 - 4:00 pm EDT.

**Comment by cindymerrill** [comment]
I could do 12-12:30 or 3-4 pm Eastern.

--Cindy

**Comment by laurensimpson14** [comment]
Great - I just sent you a calendar invite for 3:30 pm!

**Comment by cindymerrill** [comment]
Sorry, Lauren--I thought you were scheduling for today, not tomorrow. From
the times you list for tomorrow, I'm available only from 3-3:30, and I have
a hard stop at 3:30.

--Cindy

**Comment by laurensimpson14** [comment]
The appointment that I had scheduled at 3:00 is flexible, so I can still do that time. I've moved the invite to 3:00 pm tomorrow, let me know if that still works for you!

**Comment by cindymerrill** [comment]
Hi Lauren,

Thank you for all your help today! At the moment, here's the only DOMO
dashboard that I don't currently have access to but would like to:

   - https://va-gov.domo.com/page/439942537?userId=172439387 (WIP - KPIs -
   Search & Discovery - Type Ahead)

--Cindy

**Comment by laurensimpson14** [comment]
@cindymerrill I'm glad we were able to get you into the dashboards! I've just granted you access to that DOMO dashboard. Please let me know if you're now able to view it, if you need anything else, or if this ticket is okay to close out.

**Comment by cindymerrill** [comment]
Thank you, Lauren! I can now see that DOMO dashboard.

Is there any training on using DOMO and Google Analytics that I could do so
that I can learn how to use them both?

**Comment by laurensimpson14** [comment]
A few options for GA: 
- [VFS-facing GA folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/google-analytics)
    - [Walkthrough video](https://drive.google.com/file/d/1UdD1IAtdO_ODsTfIz-L7er9a8BXqNdT3/view)
    - [Google Analytics cheat sheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/google-analytics-cheat-sheet.md)
    - [Google Analytics FAQ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/google-analytics-frequently-asked-questions.md)
- The Insights and Analytics team also has open office hours for GA or DOMO reporting questions every Wednesday at 11:30 am Eastern at [this Zoom link](https://www.google.com/url?q=https://zoom.us/j/97206546239?pwd%3DcmpYWnJpU2w1eTM0WUtyV0Q4dkFLUT09&sa=D&source=calendar&ust=1618405743948000&usg=AOvVaw0al3aw-_gxNZCmXX_E2JLG)

Options for DOMO training: 
- [How to view charts](https://knowledge.domo.com/Training/Self-Service_Training/Onboarding_Resources/Analyzer_Card_(KPI_Card)_Basics)
- [Filtering & exporting charts video](https://www.domo.com/help-center/videos/watch/n9mcuvbDkf4)
- [Filtering charts article](https://knowledge.domo.com/Visualize/Adding_Cards_to_Domo/KPI_Cards/KPI_Card_Building_Part_2%3A_The_Analyzer/045Adding_Filters_to_Your_Chart)
- [Exporting charts article](https://knowledge.domo.com/Engage/Sharing_Content_in_Domo/03Exporting_KPI_Cards)
- [Exporting dashboards](https://knowledge.domo.com/Engage/Sharing_Content_in_Domo/Exporting_Domo_Stories_Pages_to_PDF)
- [Filtering dashboards](https://knowledge.domo.com/Optimize/Filtering_Data/02Applying_Page-Level_Filters)
- And the office hours for reporting questions are an option here too (see the Zoom link in the GA list)

**Comment by cindymerrill** [comment]
Thanks for the resources, Lauren! I will look into them. It's OK with me to
close this ticket.

--Cindy
