### ISSUE TITLE
Design Feedback - Usability Testing Prep [VAOS, VAOS for Distribution]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#20172]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**
- Use info and [alert boxes](https://design.va.gov/storybook/?path=/docs/designer-documentation-alert-box--page) if you feel certain text is getting lost as long as the text is info or alerts.

**Consider:**
- Suggestion about that page where users cannot schedule online. I think I just kept assuming that they were trying to schedule online. Now that I know you will have the option of online or calling I think the verbiage could def use a little lift. Maybe something like “Scheduling options” instead of "Learn more" for the button. Then I think that next page will make more sense. @peggygannon may have other opinions. 
![Screen Shot 2021-02-18 at 3.20.18 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/332d0dbc-784c-4895-af9a-6b74f9ad325e)
![Screen Shot 2021-02-18 at 3.20.30 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/09a6d363-efd7-4e21-a42a-29b55fbf5bc5)

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by outerpress** [comment]
Thanks @allison0034 !

* I tweaked the home CTA based on your comments and some that came up during the content review. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/19964 for detail there.

* I thought about the alert styles some more and:
    * I don't think it makes sense if we [can't offer them any online scheduling options](https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560132) because we've (hopefully) eased them into that flow and made it more of a natural path - learn how you can schedule > you can schedule over the phone. 
    * It does make sense to alert them [after the screener catches them](https://adhoc.invisionapp.com/share/GU1028Y9YDTX#/screens/443560131) because they thought they were on a path, and that's been cut short. Added alert styling there.

**Comment by allison0034** [comment]
@outerpress looks great!
