### ISSUE TITLE
Re-enable main Facility Locator Cypress test (search.cypress.spec.js) on Jenkins

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#20178]
This test:

src/applications/facility-locator/tests/e2e/search.cypress.spec.js

.. was found to be "flaky" and crashing on Jenkins about one out of every 15-20 runs.

This was blocking builds, so the testing team disabled the test on Jenkins.

However, without this test running in our build pipeline, it no longer prevents code from being released to production that could break our search feature.

The test still runs in CircleCI, but CircleCI isn't required to merge, and Ops is moving away from it.

@ddzz has [suggested](https://github.com/department-of-veterans-affairs/vets-website/pull/16059#discussion_r578581468) that "alloting more resources to our Jenkins machines" may resolve the issue.

## Tasks
- [ ] Run the test in Jenkins and document the current level of flakiness since the Cypress upgrades
- [ ] Assuming the test is still flaky, determine cause and resolve.

**Comment by ddzz** [comment]
The other suggestion I have is to mock out Mapbox API calls in order to reduce map animations in these tests since these animations appear to be causing the crashes.
