### ISSUE TITLE
Update a11y announcements for radio buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20173]
## Acceptance Criteria
1. Update the accessibility announcements for radio buttons:
     - accessibilityRole=radio _(these are currently announced as "checkbox")_
     - accessibilityState= denote when "selected" or "unselected"

**Comment by bessgreen** [comment]
@msmanak @ayushchak can you weigh in on what the requirements should be for the announcement copy? More specifically:

1. What phrase should be announced when a selectable element is in focus? i.e. "Double tap to activate", "Double tap to open", etc.

2. Will the same phrase be used for all selectable elements? Or will there be different phrases for different elements? Elements include: buttons, links, menu items, edit fields, switches, and check boxes. If we need different phrases for different elements, can you weigh in on what those should be?

**Comment by msmanak** [comment]
## Update
Buttons/links, menu items **do not need** "double tap to activate" announcement

edit fields | switches **needs** "double tap to activate" announcement

**Comment by bessgreen** [comment]
AC has been updated to reflect the requirement gaps, which are documented in the screenshot below:

![Screen Shot 2021-02-25 at 4.26.32 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9164d95b-ec7b-4877-b0e9-c1d2e2783c9e)

**Comment by bessgreen** [comment]
This requirement was completed w/ the form wrapper changes:

"Update the accessibility announcements for input fields & dropdown fields:
     - accessibilityState= denote whether the field is "empty", "filled", or "editing" _(note: the build announces "editing", but not "filled" or "empty")_"


Omitting this requirement from the ticket, as it should already be finished.

**Comment by digitalken** [comment]
PASS 3/29/2021 - Used 51 Weber Rd, Columbus, OH, 43202 to get multiple radio buttons available.  Looks good on Android and iOS.  Closing.
