### ISSUE TITLE
Show a different view for In-progress Applications that have expired

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#20177]
We now have [a design for a Benefit Application that has expired](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19702). We now need to update the `ApplyForBenefit` component to show this new state when the application has expired. [This is the relevant code](https://github.com/department-of-veterans-affairs/vets-website/blob/c82bdfb3832e6369a258afbd03582cd034ee8abf/src/applications/personalization/dashboard/components/FormItem.jsx#L55-L85) for how we are doing it in My VA v1. Also note that [on My VA v1 it's not possible to delete expired applications](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19703); we should ensure that that functionality _does_ work with v2.

**Comment by Samara-Strauss** [comment]
Done!
