### ISSUE TITLE
Use breadcrumbs on new appointment details pages

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#20180]
I believe this Manage Appointments link at the top of the details page should actually be our normal breadcrumbs likes:

![Screen Shot 2021-02-18 at 4.44.52 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/bad7f051-0239-47af-9c1b-8ce54a2090ab)

Currently we've been coding them exactly as they're displayed in the specs, but I believe that's just the mobile state? Pretty sure the general va.gov pattern would be for these to be regular breadcrumbs, following the style of the homepage and form flow pages.

**Comment by jbalboni** [comment]
@laurenernest @outerpress Am I correct in what I said above?

**Comment by laurenernest** [comment]
I'll let Peter have the final say, but yes we should be following the general VA design system which does look different between desktop and mobile.

https://design.va.gov/components/breadcrumbs

**Comment by outerpress** [comment]
Correct and correct y'all. I didn't intend to deviate from our standard breadcrumbs. I just didn't get around to mocking up tablet views for those states.

**Comment by jenniemc** [comment]
@laurenernest @outerpress Would you have any objection that the trailing breadcrumb reads `Details page` instead of `Manage appointment` since the Details link is what sends the user to the details page. 



![image](https://user-images.githubusercontent.com/54327023/109857144-5ade8280-7c28-11eb-856f-b2ab2db4598f.png)

**Comment by laurenernest** [comment]
@jenniemc Let's use `Appointment detail` instead. In general, we should avoid the use of "page" in the breadcrumb.

**Comment by jenniemc** [comment]
@laurenernest `Appointment detail` breaks the breadcrumb into two lines. Plus the line height is very large causing a large gap between the line break. Can you think of another phrase that's shorter without causing a line break?

![image](https://user-images.githubusercontent.com/54327023/109881279-05b16980-7c46-11eb-9874-4ef73ec1a6ba.png)

**Comment by laurenernest** [comment]
That extra padding should've been addressed in #17364 so the fix might have to be carried over here.

Is there an issue with the component that's causing the extra padding or are we doing something different with it?

**Comment by jenniemc** [comment]
I'll reach out to Lance to see about the previous fix.
