### ISSUE TITLE
Attachment filename header is double-quoted

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#20188]
## Problem:
When downloading a file attachment from the secure messaging API, the API includes a response header like `Content-Disposition: attachment; filename="test.pdf"`
However, it appears that MHV is providing us with the value for  this header with quotes, and then we are additionally quoting it, so it's winding up as:
`Content-Disposition: attachment; filename="%22test.pdf%22"`

User agents like browsers use this parameter to know how to name a downloaded file so downloads are getting named `%22test.pdf%22`; hardly ideal.

## Solution:
Strip quotes out of the parsed filename in the SM::Client#get_attachment method before returning the result.

**Comment by narin** [comment]
Verified that filename is stripped of quotes when downloading through Postman. Closing out.
