### ISSUE TITLE
Add API docs for secure message write operations

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#20189]
Mobile API docs for secure messaging are partially there - none of the write operations such as creating a message, moving a message, deleting a message are documented yet.

**Comment by patrickvinograd** [comment]
1. Verify these operations working as expected in CURL
2. Update API docs to include these operations.

Operations:
- Send a message
- Send a message with one or more attachments
- Delete a message
- Reply to an existing message

**Comment by narin** [comment]
@patrickvinograd I've been able to verify the DELETE, but with any of the POSTs for sending or replying, I'm receiving the following 502:
```
{
    "errors": [
        {
            "title": "Operation failed",
            "detail": "Something went wrong. Please try again later.",
            "code": "SM99",
            "source": "No content to map to Object due to end of input",
            "status": "502"
        }
    ]
}
```
The request bodies I've been trying match the ones we have in the existing specs.

Are there any avenues for me to debug this further, or is there someone on the MHV side I should reach out to?

**Comment by narin** [comment]
After some additional debugging on review instances, it looks like we are not sending the request body properly with our `POST` requests.  Continuing to investigate.
