### ISSUE TITLE
Project Kickoff [Claims & Appeals - Notice of Disagreement]

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#20196]
## Steps to complete Project Kickoff
- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [ ] VFS: Attach all relevant artifacts to the ticket
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [ ] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))

  Draft - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/readme.md

- Explanation of the problem space

Veterans are still using a paper form to submit disagreement claims appeals. If the veteran disagrees with an initial claims decision, they have three appeals paths: supplemental claim, higher level review, and notice of disagreement. Currently VA.gov only supports Higher Level Review, which does not allow for submission of any new evidence. This functionality does not exist on eBenefits either, so digitization will allow veterans to file appeals using VA.gov. Although Supplemental Claims is "next" in terms of typical route for a veteran, a business decision has been made to work with Lighthouse and OAR on NOD next.

We believe that bringing this to VA.gov will greatly reduce the time-to-a-decision for veterans.

- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): Veronica Henry
- DEPO Product Lead (required): Matthew Self
- Entire VFS team (recommended): Robin Garrison, Anna Carey, Ed Mangimelli, Kevin Stachura, Christian Valla
- Other specialists: Fareez Ahmed, Josh Kim, Tze Lei, Jason Woodman, Mikki Northius

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES

## Scheduling
- Please reference the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York) (times shown are ET)
- Note an available time slot within a recurring "[CALENDAR BLOCK] Review Group Office Hours" slot that works for your team and is at least 2 business days from now
- Write that preferred time slot here, and VSP will send you a meeting invite
**Wednesday, February 24, 11:30**
- _If no available time slots work for your team, write your availability and requirements here and Shira/Andrea will reach out as needed_

**Comment by sshein** [comment]
please add me as optional to this meeting as well thank you

**Comment by shiragoodman** [comment]
hey @vhenry07 and @sshein  - This has not been scheduled due to a time conflict, however we rolled out changes to the Collab Cycle on Friday. We no longer require Project Kickoffs, and instead have an asynch Collaboration Cycle Kickoff. 

Would you be able to close this ticket, review our [Getting Started with the Collaboration Cycle guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md#questions-about-your-product), and open a Collab Cycle Kickoff ticket, when ready? Please let me know if you have questions.

**Comment by vhenry07** [comment]
Opening a new collab cycle kickoff ticket.
