### ISSUE TITLE
QA Medallia for va.gov/ormdi Launch

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#20199]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- QA Medallia GTM implementation for ORMDI launch
- Medallia was previously deployed and QAed within the modernized tools container as part of this [GH issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18278) the Medallia configuration has now been mirrored in the Brand Consolidation Legacy container to support /ormdi launch 

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by jonwehausen** [comment]
@ianMcCullough-ob this is officially ready for testing -- 

A couple things to note: 

- Since this is the legacy site I had to swap our use of `recordEvent` for a standard `dataLayer.push` in the custom HTML
- Please notice & test on `survey--submission` event fire, custom dimension 125 collects each survey `unique_name` and it's value to ensure collection of survey submission metadata

**Comment by ianMcCullough-ob** [comment]
| Tag Values                     | Screenshot                                                   | Status |
| ------------------------------ | ------------------------------------------------------------ | ------ |
| survey--submission             | ![Screen Shot 2021-02-23 at 12.29.31 PM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/24764320-da74-4d83-a624-af0916e704a2) |Pass|
| survey-submit-close            | ![Screen Shot 2021-02-23 at 12.29.54 PM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/b99643e2-fe35-4a4e-a81b-5939d08300d0) |Pass|
| survey--submissions-successful | ![Screen Shot 2021-02-23 at 12.29.44 PM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/c06cf045-beeb-4bfc-afee-39396f6a0b4b) |Pass|
| survey-invitation-decline      | ![Screen Shot 2021-02-23 at 12.27.24 PM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/faa8de8c-f664-469b-b8c4-b1a876af0c06) |Pass|
| survey-no-submit-close         | ![Screen Shot 2021-02-23 at 12.28.19 PM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/8e4a7d9d-859d-426c-a9dd-aa19ec4575a2) |Pass|
| survey-invitation-accept       | ![Screen Shot 2021-02-23 at 12.27.44 PM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/fa42ade0-72d2-4c3e-a29a-b238104ac794) |Pass|
| survey-invitation-display      | ![Screen Shot 2021-02-23 at 12.27.07 PM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/cd8fa969-311f-4890-8738-138a7f447a3c) |Pass|
| survey-button-click            |                                                              |        |
| survey-start-form              | ![Screen Shot 2021-02-23 at 12.27.53 PM.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/9dde1c0b-6a19-4e6c-9e0b-ed06ff1463a9) |Pass|

Hey @jonwehausen, I tested everything that we tested on [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18278#issuecomment-770050899) and it all looks good, but I'm not finding anything that populates for "survey-button-click."

**Comment by jonwehausen** [comment]
Hi @ianMcCullough-ob , 

- Thanks for calling out - `suvery-button-click` is our translation of the custom event `MDigital_Feedback_Button_Clicked` found in [this documentation](https://github.com/department-of-veterans-affairs/va.gov-team/files/6036685/Medallia.Digital.Custom.Events.Integration.Guide.2.pdf)
- From what I'm seeing, that event only fires for certain types of surveys (i believe exclusively feedback surveys) 
- As long as we have that `survey-start-form` event firing, that should be the context we need there

**Comment by ianMcCullough-ob** [comment]
@jonwehausen thanks for clarifying. Need anything else from me on this?

**Comment by jonwehausen** [comment]
Nope! Testing Looks great @ianMcCullough-ob, here are each of the scripts we discussed today: 

**NON-MODERNIZED**
```javascript
<script nonce="2Obg9dyrqzSb6rSM1jSK0w==">
  (function(window) {
    function withFormContent(acc, data) {
      //console.log("acc.content data",data.Content);
      acc.content = data.Content;
    }
    function withFeedbackUUID(acc, data) {
      acc.feedbackUUID = data.Feedback_UUID;
    }
    function mEvent(name, action, opts) {
      opts = opts || {};
      var custom = opts.custom;
      var label = opts.label;
      function handle(event) {
        var start = +new Date();
        var cm = window.cm || function() {};
        var mData = event.detail;
        var eData = {
          category: 'Medallia',
          action: action,
          label: label || mData.Form_Type,
          value: mData.Form_ID,
          myParams: {}
        };
        if (custom) {
          for (var i = 0; i < custom.length; i++) custom[i](eData.myParams, mData);
        }
        var end = +new Date();
        console.log('send', 'event', eData, end - start);
        window.dataLayer.push({
          'event': eData.action,
          'survey-tool': eData.category,
          'survey-form-id': eData.value,
          'survey-status': eData.label,
          'survey-details': eData.myParams
        });
      }
      window.addEventListener('MDigital_' + name, handle);
    }
    mEvent('ShowForm_Called', 'survey-show-form-call');
    mEvent('Form_Displayed', 'survey-start-form');
    mEvent('Form_Next_Page', 'survey-next-click');
    mEvent('Form_Back_Page', 'survey-back-click');
    mEvent('Form_Close_Submitted', 'survey-submit-close');
    mEvent('Form_Close_No_Submit', 'survey-no-submit-close');
    mEvent('Feedback_Submit', 'survey-submit', {
      custom: [withFeedbackUUID, withFormContent]
    });
    mEvent('Submit_Feedback', 'survey--submission', {
      custom: [withFeedbackUUID, withFormContent]
    });
    mEvent('Feedback_Button_Clicked', 'survey-button-click', {
      custom: [withFeedbackUUID]
    });
    mEvent('ThankYou_Displayed', 'survey--submission-successful', {
      custom: [withFeedbackUUID, withFormContent]
    });
    mEvent('Invite_Displayed', 'survey-invitation-display', {
      label: 'Invite'
    });
    mEvent('Invite_Accepted', 'survey-invitation-accept', {
      label: 'Invite'
    });
    mEvent('Invite_Declined', 'survey-invitation-decline', {
      label: 'Invite'
    });
    mEvent('Invite_Skipped', 'survey-invitation-skip', {
      label: 'Invite'
    });
  }(window));
</script>
```

**MODERNIZED**
```javascript
<script nonce="2Obg9dyrqzSb6rSM1jSK0w==">
  (function(window) {
    function withFormContent(acc, data) {
      //console.log("acc.content data",data.Content);
      acc.content = data.Content;
    }

    function withFeedbackUUID(acc, data) {
      acc.feedbackUUID = data.Feedback_UUID;
    }

    function mEvent(name, action, opts) {
      opts = opts || {};
      var custom = opts.custom;
      var label = opts.label;

      function handle(event) {
        var start = +new Date();
        var cm = window.cm || function() {};
        var mData = event.detail;
        var eData = {
          category: 'Medallia',
          action: action,
          label: label || mData.Form_Type,
          value: mData.Form_ID,
          myParams: {}
        };
        if (custom) {
          for (var i = 0; i < custom.length; i++) custom[i](eData.myParams, mData);
        }
        var end = +new Date();
        console.log('send', 'event', eData, end - start);
        recordEvent({
          'event': eData.action,
          'survey-tool': eData.category,
          'survey-form-id': eData.value,
          'survey-status': eData.label,
          'survey-details': eData.myParams
        });
      }
      window.addEventListener('MDigital_' + name, handle);
    }
    mEvent('ShowForm_Called', 'survey-show-form-call');
    mEvent('Form_Displayed', 'survey-start-form');
    mEvent('Form_Next_Page', 'survey-next-click');
    mEvent('Form_Back_Page', 'survey-back-click');
    mEvent('Form_Close_Submitted', 'survey-submit-close');
    mEvent('Form_Close_No_Submit', 'survey-no-submit-close');
    mEvent('Feedback_Submit', 'survey-submit', {
      custom: [withFeedbackUUID, withFormContent]
    });
    mEvent('Submit_Feedback', 'survey--submission', {
      custom: [withFeedbackUUID, withFormContent]
    });
    mEvent('Feedback_Button_Clicked', 'survey-button-click', {
      custom: [withFeedbackUUID]
    });
    mEvent('ThankYou_Displayed', 'survey--submission-successful', {
      custom: [withFeedbackUUID, withFormContent]
    });
    mEvent('Invite_Displayed', 'survey-invitation-display', {
      label: 'Invite'
    });
    mEvent('Invite_Accepted', 'survey-invitation-accept', {
      label: 'Invite'
    });
    mEvent('Invite_Declined', 'survey-invitation-decline', {
      label: 'Invite'
    });
    mEvent('Invite_Skipped', 'survey-invitation-skip', {
      label: 'Invite'
    });
  }(window));
</script>
```

cc: @jwoodman5 @billfienberg @ianMcCullough-ob

**Comment by billfienberg** [comment]
@jonwehausen in the code you provided, there is a `nonce` attribute on the `script` element:

```
<script nonce="2Obg9dyrqzSb6rSM1jSK0w==">
```

Do you know where that `2Obg9dyrqzSb6rSM1jSK0w==` value came form? Do you know if we should keep that value or replace it with the placeholder [nonce value we use everywhere else](https://github.com/department-of-veterans-affairs/vets-website/search?q=csp_nonce) (`**CSP_NONCE**`)?

**Comment by jonwehausen** [comment]
Hi @billfienberg, 

Great question - the `nonce` attribute value you see there came from Medallia's documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/files/6039545/Medallia.Digital.Custom.Events.Integration.Guide.2.pdf).

Should be totally fine to replace that with our **CSP_NONCE**

**Comment by billfienberg** [comment]
Cool. Thanks, @jonwehausen.

Here's the PR to add the modernized script to `vets-website`:

https://github.com/department-of-veterans-affairs/vets-website/pull/16175

**Comment by ianMcCullough-ob** [comment]
| Tag Values                     | Screenshot                                                   | Status |
| ------------------------------ | ------------------------------------------------------------ | ------ |
| survey--submission             | ![survey-submission.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/e3fc8d06-bb8d-4e4b-85dc-b832d1f80677) |Pass|
| survey--submission data layer | ![survey--submission-successful dl.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/da1ec309-f23b-4a33-8e69-989545e89be9) |Pass|
| survey-submit-close            | ![survey-submit-close.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/cb76da0c-b5ed-4dc8-a569-a19676e4ec6a) |Pass|
| survey--submissions-successful | ![survey--submission-successful.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/671d54bd-87da-4819-b5fe-e99721443e58) |Pass|
| survey-invitation-decline      | ![survey-invitation-decline.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/5b305a85-8b7b-4ef3-bd2a-3410bbde053c) |Pass|
| survey-no-submit-close         | ![survey-submit-no-close.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/2442a59b-5935-41ab-80da-5607e06989df) |Pass|
| survey-invitation-accept       | ![survey-invitation-accept.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/ecba8531-184b-42c4-879c-1b045c6a9c94) |Pass|
| survey-invitation-display      | ![survey-invitation-display.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/76109523-7369-48e3-ab27-227f65342d94) |Pass|
| survey-start-form              | ![survey-start-form.png](https://images.zenhubusercontent.com/5f8db741ece9322d39872b91/ffd07739-9565-4ad3-8c26-5633e3cceb3f) |Pass|

@jonwehausen and @jwoodman5 just tested the form on ORMDI on staging and everything looks good.

**Comment by jonwehausen** [comment]
Thanks for your testing here @ianMcCullough-ob !

The GTM implementation has been published and Google Analytics custom dimensions have been made active. 

Data collection will begin when the survey is made live (and the scripts [discussed here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20199#issuecomment-785255864)  have been moved to production)

Closing this GH issue. 

cc: @joanneesteban @jwoodman5 @ianMcCullough-ob @billfienberg
