### ISSUE TITLE
Confirm any size limitations on secure message fields

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#20195]
Most APIs have a size limit on various user-entered fields.

We know of:
- size limit on attachments.

Currently unknown:
- number of attachments
- length of subject
- length of message body

We might be able to figure these out from MHV API docs or existing vets-api/vets-website code, otherwise we'll need to ask MHV.

Once known:
1. Document in API docs
2. Make sure mobile app is respecting these with some user-friendly UX
3. Make sure mobile API responds with sensible error messages if limits are exceeded.

**Comment by drjecker** [comment]
Here's what I've documented so far:

### Subject line:
From an email between Patrick and Barry:

> In the UI, the subject line is restricted to 50 characters, but the field in the database allows up to 512 characters. There is no restriction on the message body in either the UI or the database (datatype: CLOB). I’m thinking that it would be a good idea for the Flagship Mobile app to adhere to this 50 character subject line limit to prevent issues between the mobile app and the MHV Portal and SM Clinician Portal. The 50 character limit was driven by the business.

### Number of attachments from current web UI/experience:
- Maximum is 4 files 
- Total size of all uploads can't exceed 6.0 MB

### Length of message body:
Not sure on this one. @narin have you found this out?
