### ISSUE TITLE
Discovery on incremental metalsmith builds

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#20207]
## Details 

Incremental metalsmith builds have come up in the context of improving content build scalability. CMS Super team discussed this (?), Dror has brought this up, etc. 

This ticket is to gather all relevant context on incremental build discussions, and determine whether it is a feasible option for us to pursue for the content build. 

Tim tried this plugin at one point but it didn't work, but it still may have useful info/approaches for us to use: https://github.com/axa-ch/metalsmith-incremental

## Definition of Done 
- [ ] Document high level recommendation for future work (including team responsible for completing that work)
   - [ ] VSP peer reviews
   - [ ] CMS team reviews

If we decide to pursue incremental builds & need to write a design doc or other solution documentation, that will be tracked in a separate ticket.

**Comment by timwright12** [comment]
Closing since we were asked to halt/pause this work in favor of a future initiative.
