### ISSUE TITLE
Master Detail Landing Pages: Content for Forms based on the top 25 highly ranked search forms

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2020]
**Overview:**
This ticket is to create content templates for Master Detail Landing Page Forms, based off of the top 25 highly searched forms.  

**Precursor Work:** 
- [x] Determine which master landing page forms receive the highest traffic (template based on analytics forms)
- [x] Custom landing pages for our digital tool products (that have a paper form counterpart) even if they're not currently ranking in search.
- [x] Copydecks for custom landing pages for digitial tool products 
- [ ] IA discussion around where this will live on the site, the URL and how users will navigate to it
- [ ]  Redirect Validation

**Comment by Karak888** [comment]
@artsymartha68 will handle design, @jenniferlee-dsva will determine who from content team should pick this up.

**Comment by Karak888** [comment]
@lwalsh617 to reach out to @nedierecel and connect with @artsymartha68 - to get started- @jenniferlee-dsva will send spreadsheet of info from analytics dashboard info to @lwalsh617

**Comment by jenniferlee-dsva** [comment]
@lwalsh617   @artsymartha68            
For some reason, I'm not able to upload the csv files here, so I will Slack them to you.

**Comment by nedierecel** [comment]
@Karak888 @lwalsh617 Thanks for connecting - I am applying an exclusion to filter out the non-VA network data. A few caveats:

1. The logic is we exclude any activity from sessions from a VA Network Domain; if, for whatever reason, a VA facility doesn't use the VA Network Domain, those employees might be included.
2. Timeframe - The YTD view is a bit sluggish; would a 6-month timeframe be acceptable?

**Comment by lwalsh617** [comment]
@nedierecel Sounds good! Thank you!

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 @artsymartha68 - I've reviewed and added comments to the spreadsheet, attached here. 

[25-Top-Form-Detail-Custom-LPs_10-24-19-jlcomments.xlsx](https://app.zenhub.com/files/133843125/b1e646ee-98b2-4a37-bae6-1ba963f14846/download)

Enough complexity and oddballs that we may need to talk through ^. Couple things not covered by comments in the spreadsheet:

@Karak888 - FYSA

@lwalsh617 
1/ In addition to the top 25 highly searched forms, can you please make sure that we have captured the VA.gov digital tools?  I.e., I want to make sure that we create custom landing pages for our digital tool products (that have a paper form counterpart) even if they're not currently ranking in search. 

2/ In looking at the level of complexity for the 25 on the spreadsheet, I think we do need to provide these custom form LPs as individual Word copydecks. Something simple as you suggested, that captures all the content, and can be a companion to the design page examples that Martha is working on. 

3/ On those ^ copydecks, please also include at the top of each copydeck, a place where we can include SEO and IA info for when we start building these. Some of this, you'll need to consult with Mikki later to determine, but others, we can provide when we're closer to delivering. (Can make a new ticket just for this phase of work .)

- BREADCRUMB: {Mikki}
- CANONICAL URL: {Mikki}
- META (BROWSER) TITLE: 
- META DESCRIPTION: 
- 1-2 SEO TERMS: 

4/ For the not-custom form landing page @lwalsh617 - please provide a simple 'shell' copydeck, per your suggestion - not showing actual content, but the content fields/types on the page, plus the templated standard elements (like the default Helpful links section). Something that shows all the elements possible on a not-custom LP. 

@artsymartha68  - just recapping our call together: 
- Design files for the 3 variations of the custom LPs
- Design file for the not-custom LP (where it's literally just 1 form per LP), showing different states/scenarios - e.g.,  with online CTA/ without online CTA... and I forget what else we discussed - sorry!

**Comment by artsymartha68** [comment]
See #2691 for my latest "patterns" design draft.

**Comment by jenniferlee-dsva** [comment]
Per our call today - uploading doc with content fields. Highlighting the new fields from this call. 

[forms-lp-versions.docx](https://app.zenhub.com/files/133843125/ea1be931-e638-4af6-8feb-92b7268ae4d8/download)  @artsymartha68  @lwalsh617

**Comment by Karak888** [comment]
Thanks @jenniferlee-dsva!  @lwalsh617 would you kindly let me know where you are in this process so I can track (and try to be knowledgeable) on my end.

**Comment by lwalsh617** [comment]
@Karak888 I'm posting the latest copy deck here. Next--which may be a new ticket or new task on current ticket is SEO which I'm currently working on. 
[VA Forms LP WIP copy_v0.4_11-19-19.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3870162/VA.Forms.LP.WIP.copy_v0.4_11-19-19.docx)

**Comment by jenniferlee-dsva** [comment]
I'm looking at your copydeck ^ @lwalsh617

**Comment by Karak888** [comment]
@mnorthuis adding you for IA of where this will live and redirect validation.  Thanks!

**Comment by Karak888** [comment]
Closing this ticket as work is complete.

**Comment by jenniferlee-dsva** [comment]
@Karak888 and CC @lwalsh617 - noting it here so we don't lose next step (which should be a new task/ticket as part of the main epic). Per convo with Laura a couple weeks ago: I started to review the WIP copydeck but we both decided it would be better to do that AFTER Laura's SEO research work and incorporating her SEO findings into the custom master detail landing pages. 

So the next task/ticket would be to incorporate Laura's SEO findings into the ^ copydeck. 

Per convo, if bandwidth is an issue, the current priority is to get the "View your disability ratings" static landing page updates in the queue, in time for their tool launch.

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - when the copydeck is FINAL, please upload it to this repo, as Word file and as a PDF. (Martha's design documentation is already there.)Thank you!
