### ISSUE TITLE
CT: Research Yellow Ribbon Degree Drop-down implementation

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20209]
As a developer, I need to research the yellow ribbon implementation within the comparison tool so that the team can understand how to improve the usability for comparison tool users.

## Assumptions:
1. N/A

## Acceptance Criteria
1. Documentation is created and attached to this story of how the yellow-ribbon degree level dropdown:
    a. is populated
    b. impacts conditional questions
    c. impacts the estimate your benefits grey box display
    d. any other impact not listed above

## Supporting Artifacts: 
1. Sample school to reference: https://www.va.gov/gi-bill-comparison-tool/profile/31817033
<img width="431" alt="Screen Shot 2021-02-19 at 1 49 42 PM" src="https://user-images.githubusercontent.com/48260534/108548098-5a093080-72b9-11eb-8313-5b5c669d6572.png">

**Comment by ksantiagomorgan6** [comment]
In the example school given it looks correct locally. 
![Screen Shot 2021-02-23 at 2.57.49 PM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/c56f68f8-dbc1-4ba6-adcd-ef5393a86e6c)

in prod it looks like this
![Screen Shot 2021-02-23 at 3.20.03 PM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/3b2b2318-e0e7-45db-b595-559a54a88406)

Looks like the solution to this would be correct data in the staging / production`YellowRibbonProgramSource.csv` file

Prod VS Local Data
![Screen Shot 2021-02-23 at 3.18.52 PM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/f6ce42cf-a7ea-44ad-b265-4c8c3cd16829)

**Comment by ksantiagomorgan6** [comment]
As for the enter an amount in the list it is used to enter a custom dollar amount and removes the populated division or school box.
![Screen Shot 2021-02-24 at 7.37.43 AM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/42f7a02a-8be8-4703-8f86-7ca94f3b378e)


With the Enter amount option selected


![Screen Shot 2021-02-24 at 7.37.55 AM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/eb095dbe-8224-415c-bee0-5e94c8dc6d3e)
it is being pushed onto the list every time the yellow ribbon section is rendered. 
` yellowRibbonDegreeLevelOptions.push({
      value: 'customAmount',
      label: 'Enter an amount',
    });`

**Comment by zurbergram** [comment]
Data in YellowRibbonProgramSource is related to Weams rows by `facility_code`

"Degree Level" is populated from the `degree_level` column in related rows in YellowRibbonProgramSource

If "Enter an amount" is selected

- then "Yellow Ribbon amount from school per year" is shown with a default value of $0

if a degree level value is selected 

- then the "Division or school" and the "Yellow Ribbon amount from school per year" appear
- The "Division or school" is populated with each unique `division_professional_school` found for the institutions
- The "Yellow Ribbon amount from school per year" is populated with the contribution amount for the selected program based on 

"Yellow Ribbon amount from school per year" amount affects these values displayed in Estimated Benefits per term

![Screen Shot 2021-02-26 at 2 06 18 PM](https://user-images.githubusercontent.com/1094999/109343744-ce088300-783b-11eb-972e-0a0ed1c3c572.png)


the following is all starting at https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi/selectors/calculator.js#L388


All amounts with `paid by VA` are the same as the corresponding `paid by school` amount

![Screen Shot 2021-02-26 at 2 11 37 PM](https://user-images.githubusercontent.com/1094999/109344316-8b937600-783c-11eb-88da-7dc715acb566.png)

number of terms is dependent on answers to

![Screen Shot 2021-02-26 at 2 24 13 PM](https://user-images.githubusercontent.com/1094999/109345539-4f611500-783e-11eb-98f1-725b4cbfbdff.png)

If the amount entered into "Yellow Ribbon amount from school per year" (`yellowRibbonAmount`) equals 0
- then set all yellow ribbon benefit terms to 0
else
- do math to determine yellow ribbon benefit term values (all 6 possible)

The yellow ribbon benefit total of each "paid by school" term is used to determine displayed value "Yellow Ribbon: Total per year" 

"Yellow Ribbon: Total per year" is added to "Tuition and fees: Total per year" which is displayed as "GI Bill pays to school:"

"GI Bill pays to school" and total scholarships is subtracted from "Tuition and fees per year"  which determines what is displayed for "Out of pocket tuition"


![Screen Shot 2021-02-26 at 2 34 46 PM](https://user-images.githubusercontent.com/1094999/109346501-c6e37400-783f-11eb-9cab-ab4fcf6cc20d.png)

yrBenSchoolTerm1 = yellow ribbon benefit term 1, this is `paid by school`
yrBenVaTerm1 = this is `paid by VA`
yrBenTotal = "Yellow Ribbon: Total per year" 
tuitionFeesTotal = "Tuition and fees: Total per year"
totalToSchool = "GI Bill pays to school:"
+inputs.scholarships = total scholarships
+inputs.tuitionAssist = "Tuition and fees: Total per year" for either in or out of state
totalLeftToPay = "Out of pocket tuition"

**Comment by zurbergram** [comment]
![image](https://user-images.githubusercontent.com/1094999/109347886-cfd54500-7841-11eb-8e96-f45c90233c5d.png)

**Comment by zurbergram** [comment]
i think `tuitionFeesPerTerm === tuitionFeesTerm1;` is causing it not look like Yellow Ribbon is affecting anything

```
    const shouldHaveNoYrBenTerm1 =
      !yellowRibbonElig ||
      yellowRibbonAmount === 0 ||
      oldGiBill ||
      giBillChapter === 31 ||
      tuitionFeesPerTerm === tuitionFeesTerm1;
```

**Comment by zurbergram** [comment]
@dneel-bah Please see https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/data/yellow-ribbon-calculations.md

**Comment by dneel-bah** [comment]
Documentation has been reviewed and covers requested research information.  Closing the story as complete.
