### ISSUE TITLE
[Spike] Audit Gem Version in vets-api

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#20201]
## Description

There are over 300 gems installed on vets-api, about 160 have updates available to them.  In order to get ahead of potential issues and security threats we need to identity which gems have updates available, and out of those create a priorityseverity list so that we can slowly start upgrading them.

##Audit
[Working document can be found here](https://docs.google.com/spreadsheets/d/1XAANeTmGK2-kSDyxk3qjlS3aODSWBIgFhPHAH7by9Ns/edit?ts=602fd283#gid=1749343339)

## Acceptance Criteria
- [ ] An audit is completed and documented which show which outdated gems should be upgraded in priority order
- [ ] Tickets are created (gems can be grouped or stand alone based on LOE) and added to the backlog.

**Comment by alexpappasoddball** [comment]
@thilton-oddball here you go!  Also, @LindseySaari I added your outdated gems spreadsheet, thank you for putting that together.  Do you think we can change the permissions to anyone with the link instead of locking it down to just the BE tools team?  I can't seem to change that setting as I'm not the owner.

**Comment by LindseySaari** [comment]
Permissions updated! ✔️

**Comment by LindseySaari** [comment]
[Outdated Gems Spreadsheet](https://docs.google.com/spreadsheets/d/1XAANeTmGK2-kSDyxk3qjlS3aODSWBIgFhPHAH7by9Ns/edit#gid=1471246704)

**Comment by LindseySaari** [comment]
[Helpful gem update commands](https://medium.com/cedarcode/updating-gems-cheat-sheet-346d5666a181)

**Comment by alexpappasoddball** [comment]
@thilton-oddball @LindseySaari Lets make sure that doc is as good as we need it and close this ticket out in favor of the moving forward with the actual updating of the gems by today!
