### ISSUE TITLE
Error handling on availability check for project cheetah

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#20203]
If we encounter an error trying to determine if someone is eligible for the cheetah flow (e.g. they have at least one facility available), what should we display to the user?

**Comment by jbalboni** [comment]
cc @outerpress

**Comment by laurenernest** [comment]
@jbalboni Is this error temporary for this specific check before the next step or is this error telling us there will also be a problem with scheduling with a facility later in the flow?

**Comment by jbalboni** [comment]
@laurenernest The call we make for this check is the same one we make to build the list of facilities to choose from. I don't know of any cases where we expect to get an error, so it's probably temporary when it happens. But the user is definitely stuck if it fails.

**Comment by laurenernest** [comment]
In this case, we'd like to put them in the flow to schedule since it's still possible for them to find an appointment.

**Comment by jbalboni** [comment]
If this call is failing, we can't show them facilities to choose from.

**Comment by laurenernest** [comment]
no longer needed
