### ISSUE TITLE
Create Refresh / Redeploy / Update Schedule for EKS Worker Node EC2 Instances

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#20210]
## The Problem
Our EKS EC2 worker nodes get deployed once and exist indefinitely. We need a way to refresh/update/redeploy these instances on a set schedule, so that they stay up to date with the latest security patches.

## Extra Context
- The EKS worker EC2 nodes are getting flagged by the [`os-check` job](http://jenkins.vfs.va.gov/job/utility/job/os-check-dev/):
```
07:02:22  fatal: [ip-10-247-96-99.us-gov-west-1.compute.internal]: UNREACHABLE! => changed=false 
07:02:22    msg: |-
07:02:22      Data could not be sent to remote host "ip-10-247-96-99.us-gov-west-1.compute.internal". Make sure this host can be reached over ssh: ssh: connect to host ip-10-247-96-99.us-gov-west-1.compute.internal port 22: Connection timed out
07:02:22    unreachable: true
07:02:22  fatal: [ip-10-247-97-20.us-gov-west-1.compute.internal]: UNREACHABLE! => changed=false 
07:02:22    msg: |-
07:02:22      Data could not be sent to remote host "ip-10-247-97-20.us-gov-west-1.compute.internal". Make sure this host can be reached over ssh: ssh: connect to host ip-10-247-97-20.us-gov-west-1.compute.internal port 22: Connection timed out
```
- We [originally wanted to ignore these instances](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18119), but decided to instead honor the rules for `os-check` and created this ticket instead

## Work to be Done
- [ ] Investigate solutions for updating / redeploying EKS worker EC2 nodes
  - [ ] Answer this question: should the EKS nodes be ssh accessible?
- [ ] Implement said solution to make sure EKS nodes get refreshed on a set schedule

**Comment by omgitsbillryan** [comment]
One possible solution to updating our EKS instances on a schedule 👉  https://github.com/hellofresh/eks-rolling-update

**Comment by jhouse-solvd** [comment]
@mleclerc00 - I'm not sure if any of this behavior has been resolved/improved with your recent work with EKS worker nodes, but can you take a look and close with comment if you're confident that's been addressed? Thank you.

**Comment by mleclerc00** [comment]
This has been addressed with the EKS rolling update work that has been done

https://github.com/department-of-veterans-affairs/va.gov-team/issues/25092
