### ISSUE TITLE
Field errors for Edit Direct Deposit (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20223]
## User story
As a user, I want to understand why my direct deposit information cannot be saved so I can fix the fields that were flagged as invalid. 

## Acceptance Criteria
1. On the Edit Direct Deposit page, the Save button should always be enabled, even when all fields are null/disabled
2. When there is at least 1 field-level error, display the mobile alert error CC at the top of the page:
     - Copy in error alert is hard coded: "Please check your direct deposit information"
     - The error alert should disappear when all field level errors are resolved/have disappeared
3. The checkbox should always be enabled
     - Remove the disabled state
4. Any fields that have an associated error will update to display the error UI (as detailed in the input field #19585 & dropdown #19584 CC tickets): 
     - Label text: Mobile Body Bold
     - Border: 2px solid red secondary dark, #CD2026
     - Error text: Mobile Body Bold, #CD2026
5. Create UI for the following field-level errors below the specified field _(note: follow the copy specified in this AC, as there are differences in the designs)_:
     - Routing number: "Please enter the bank's 9-digit routing number." 
     - Account number: "Please enter your account number." 
     - Account type: "Please select the type that best describes the account." 
     - Checkbox: "Please confirm this information is correct."
6. The field-level errors should appear when any of the following occur:
     - A user taps into a required input field and leaves the field without completing it
     - A user tries to save the form without interacting with a required field. In this case, the error message displays when "Save" is selected
7. A field-level error should disappear when any of the following occur:
     - For dropdown fields: user makes a selection from the dropdown
     - For input fields: user begins typing into the field
     - A user hits "Cancel" to exit the form

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/442012725

## Discovery ticket
#17057

## Accessibility Implementation Guidelines

**Error state:**
Formfield: “{label}. error - {Validation text}.”
Formfield/Message: “{label, hint message}. error - {Validation text}.”
Dropdown:“{label}. error - {Validation text}.”
Dropdown/Message“{label, hint message}. error - {Validation text}.”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Hi @bridgethapner, I cross-referenced the designs & the discovery ticket (#17057) and it looks like there are differences in the field error copy for the following 2 fields: 

Account Type:
     - Field error in designs: "Please select the type that best describes the account."
     - Field error in UX ticket: "Please select an account type." 

Checkbox: 
     - Field error in designs: "Check to confirm the information is correct." 
     - Field error in UX ticket: "Please confirm this information is correct." 

Can you advise on which copy is correct?

**Comment by bessgreen** [comment]
@bridgethapner follow-up question about the various states for the checkbox. Based on the designs, it looks like the checkbox can assume any of the following states:

1. Disabled
2. Active / unselected
3. Active / selected
4. Active / unselected with a field error

When the checkbox is in state #4, should we allow the user to check the box even if they have incomplete form fields? Or, should state #4 only appear if the user has completed the other fields on the form, skipped the checkbox, and hit Save? 

Design that corresponds to this scenario: https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/442012725

**Comment by bridgethapner** [comment]
@bessgreen :wave:

- For the Account type dropdown "Please select the type that best describes your account" is the correct copy.
- For the confirmation checkbox "Please confirm this information is correct" is the correct copy.
- Re the questions about the checkbox -- good question! I think you are right that we should allow the user to select even if they have incomplete form fields. I'm realizing that if a user tries to save their DD information with multiple fields empty, the checkbox would need to turn straight from state #1 (disabled) to state #4 (active with field error) which doesn't feel intuitive. So I think the requirements should be: 
     - Checkbox is always active
     - Checkbox delivers the error state if a user tries to hit 'Save' without selecting the checkbox

**Comment by bessgreen** [comment]
@bridgethapner thank you!

Added a new requirement (AC #2) to remove the disabled state on the checkbox, so it's always active even if the user has not completed the form.

Also - based on some of Danielle's copy changes in the prototype, there are a few areas where she's requested we remove "Please". Should we do the same for these field errors? 
     - Ex: "Please enter the bank's 9-digit routing number." We can simplify to "Enter the bank's 9-digit routing number."
Let me know what you think - I'll defer to you here!

**Comment by bridgethapner** [comment]
Thanks @bessgreen! The web uses "please" for DD text so my gut is to leave it here unless Danielle specifically says we should remove it - let's ask her POV on that in our follow-up conversation about open Qs.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Note for QA / @digitalken:

When testing the focused states & field errors, there are currently 2 caveats for Android devices. (This is a result of using the default picker style - there is a follow up task (#21131) to create a custom picker to address these gaps.)

The following will not currently appear on Android pickers:

1. Dropdown fields will not apply the focused state
2. Dropdown fields will only apply the field errors when the user hits "Save" on a blank entry

**Comment by digitalken** [comment]
PASS 3/10/2021 - Minor bug entered on when the error field should go away, otherwise looks good on iOS and Android.  Closing.
