### ISSUE TITLE
Staging Review Design System Team - Accordion Web Component (Accessibility review)

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#20228]
## Artifacts - _please provide the following artifacts at least 4 days before scheduled review meeting_
- Epic https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/16678 - Product outline  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/design-system/web-component-pilot.md-  Release plan https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/17166
 - Link to accordion web component on staging.  https://dev-design.va.gov/storybook/?path=/docs/components-va-accordion--default

## Meeting attendees from Design System TEam
- Product Manager (required): Carol Wong
- DEPO product lead (required): Kevin Hoffman and Ryan Thurwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Brooks Johnson, Chris Valarida, Crystabel Reiter (optional)

VSP will only invite those specified, so be sure to list your content, IA, accessibility and QA specialists, if applicable.

## Scheduling
Tuesday at 11:30am ET
Wednesday at 1:30pm ET

**Comment by peggygannon** [comment]
Hi, @caw310 I'm not able to access the Accordion component with this link.  I want to confirm that this is the correct link posted above? https://dev-design.va.gov/storybook/?path=/docs/components-va-accordion--default. 

I'm getting this message: 


![2021-02-23](https://user-images.githubusercontent.com/17554224/108893354-d9527900-75c5-11eb-87de-22db5ada1535.png)

**Comment by caw310** [comment]
> Hi, @caw310 I'm not able to access the Accordion component with this link. I want to confirm that this is the correct link posted above? https://dev-design.va.gov/storybook/?path=/docs/components-va-accordion--default.
> 
> I'm getting this message:
> 
> ![2021-02-23](https://user-images.githubusercontent.com/17554224/108893354-d9527900-75c5-11eb-87de-22db5ada1535.png)

@peggygannon , it seems that a merge overwrote that page. Brooks has updated it so give it a few minutes and try again.

**Comment by allison0034** [comment]
@caw310 I think there is an extra space and dash at the end of the product outline link so it is returning page not found

**Comment by caw310** [comment]
@allison0034 , I think the link melded with the next item. I fixed.

**Comment by peggygannon** [comment]
thanks, @caw310 thanks, Carol. I have no content feedback.

**Comment by allison0034** [comment]
@caw310 no design feedback : )

**Comment by shiragoodman** [comment]
@caw310 the recording is available in our [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) under the New tab
