### ISSUE TITLE
Remove CMS Export from dev

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#20220]
## Details 

Remove CMS Export from dev 
Announce this change in Slack (vfs-all-teams, vfs-frontend, vfs-engineers) 

Ticket to put it in dev was #19909

**Comment by alexandec** [comment]
PR is here: https://github.com/department-of-veterans-affairs/vets-website/pull/16173. We can reference this in the future if we need to reinstate the CMS Export build.
