### ISSUE TITLE
UI updates for Direct Deposit 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20222]
## User story
As a user, I want a page to edit my direct deposit info that indicates which fields are mandatory. 

**Note for dev**: This ticket does not include field-level errors. 

## Acceptance Criteria
Make the following updates to the UX/UI on the Edit Direct Deposit page:

1. Routing number
     - Display Input Field CC
     - Mark as "Required"
     - Include helper text with specified character limit ("Your bank's name will appear...")
2. Account number
     - Display Input Field CC
     - Mark as "Required"
     - Include helper text with specified character limit
3. Account type
     - Display Dropdown Field CC
    -  Mark as "Required"
4. Checkbox
     - _No modifications for this ticket_

## Designs
DD Edit form:
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/432050369
**Source of truth for form-field specs:** 
https://adhoc.invisionapp.com/d/main#/console/21114574/445194525/preview?scrollOffset=538.888916015625

Original discovery ticket, for reference:

## Accessibility Implementation Guidelines
**Inactive state(empty):**
Formfield: “{label}, empty."
Formfield/Message: “{label, Hint message}, empty. "
Dropdown: “{label}, empty."
Dropdown/Message “{label, Hint message}, empty. "

**Focused state(editing):**
Formfield: “{label}. Editing - {Input text}. "
Formfield/Message:“{label, hint message}. Editing - {Input text}. "
Dropdown: “{label}. Editing - {Input text}."
Dropdown/Message “{label, hint message}. Editing - {Input text}. "

**Activated state:**
Formfield: “{label}. Filled - {Input text}. ”
Formfield/Message:“{label, hint message}. Filled - {Input text}. ”
Dropdown:“{label}. Filled - {Input text}. ”
Dropdown/Message “{label,hint message}. Filled - {Input text}. ”

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/10/2021 - Logged a couple of bugs on this with accessibility and text size. (Text size bug was probably on the common component, though.)  Closing the story.
