### ISSUE TITLE
[Cheetah MVP] Use consistent terminology across pages

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20230]
## Issue Description
Update all pages in the flow to use consistent terminology.

---

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] All references to `covid` are `COVID-19`

- [ ] All references to `vaccination` (singular) are `vaccine`
- [ ] All references to `vaccinations` (plural) are `vaccines`

**Comment by jenniemc** [comment]
Hi @laurenernest and @outerpress, for this ticket to make consistent use of terminology [Cheetah MVP] I was wondering do you also have an updated heading for choosing facility page and choosing clinic pages? It currently reads, "Choose a VA location for your project cheetah booking" and "Choose a clinic for your Project Cheetah appointment".

**Comment by laurenernest** [comment]
Good catch @jenniemc! Those can say "Choose a location" and "Choose a clinic" respectively.
Hopefully we don't have any other cheetahs on the loose :)
