### ISSUE TITLE
[Cheetah MVP] Document current pages of flow

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20231]
## Description
Due to the rapid iterations of the cheetah flow, I would like to document all pages and content as we have developed so far. This will help more accurately capture the next round of updates and be able to get IA feedback for the URLs.

## Acceptance Criteria

- [ ] Full page screenshots for all pages and states included in the flow
- [ ] URLs for all pages included in the flow
- [x] Copy for all pages included in the flow
  - _Work with Lauren to document the copy (need to capture heading types)_

**Comment by jbalboni** [comment]
@laurenernest Pages are outlined here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md

**Comment by laurenernest** [comment]
1. Can you add the following:
- Contact facility page after that homepage CTA check (screenshot and URL even if same/similar as the other Contact facility)
- Facility Selection - Sort by current location
- Facility Selection - Multiple facilities, no address on file (alpha sort?)
- Facility Selection - Single facility

2. For the No clinics alert modal, is that header an H3?

**Comment by jbalboni** [comment]
@laurenernest Updated. Heading is an h3 on the modal, though I'm not sure why that's the default in our modals.
