### ISSUE TITLE
MCP Discovery Research Epic 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#20234]
## High Level User Story
As a Veteran I want the ability to see my medical copays in the debt portal in a consolidated view with my other debts 
## Goals
The first step is to understand the business process of why a Veteran may have a medical copay and the paths to payments, resolutions in as-is scenario 

## Issues to create within this Epic

```
- Create research plan
- Recruit for research sessions/Schedule research sessions
- Create conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
```

## How to configure this issue
- [ ] **Labeled with `discovery` and `research` and `team-name`**

**Comment by rebeccawalsh** [comment]
All tickets completed
