### ISSUE TITLE
STEM AD: Add denied 10203 submissions to list view

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20241]
As an education team member, I would like an applicant to view the status of their denied application when it has been denied based on reasons that will immediately make them ineligible, so that the time to notify the applicant is reduced.

## Assumptions:
1. Completed behind feature flag `stem_automated_decision` (#13829)
2. Login to claims page here: https://staging.va.gov/claim-or-appeal-status/
3. 10203 denials are added to page found here: https://staging.va.gov/track-claims/your-claims
4. The new denial card functionality is integrated with the current claims/appeals card functionality.

## Acceptance Criteria:
1. A card is displayed on the page for each unique 10203DNY denial that the applicant has received.
2. The title of the card is "Your Edith Nourse Rogers STEM Scholarship Application updated on [Month DD, YYYY]
3. The status of "Denied" is displayed on the card
4. The date the application was submitted on is displayed on the card
5. The "view details" button appears but is not functional.
6. The denials are sorted descending by updated date (most recent updates first).
    a. The denials are included in the listing of other claims / appeals

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222481/296056346/preview)
   1. [Link to prototype for folks without accounts](https://bahdigital.invisionapp.com/share/CUIAG8PZ85J#/screens/296056346)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content.md)
3. #17771 - Story outlining how a claim is determined to be denied or not.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16233

Local URL: http://localhost:3001/claim-or-appeal-status/

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1498&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-03-04 at 6.49.14 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7d58578f-8a8e-4469-8e88-a73fc14291c3)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me

**Comment by amyknox** [comment]
UX Review 2/2: This checks out for me

**Comment by sonntag-adam** [comment]
Closing story
