### ISSUE TITLE
Request access to foersee

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#20243]
# Request Foresee and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

I'd like to better understand the change in customer satisfaction for Disability over the past year
  https://www.va.gov/performance-dashboard/
I know that domo is the future and Foresee is the past, but I'd like to understand the change in User Satisfaction over time.

## User Email Address
anna@adhoc.team

## Access Requirements
Please check the analytics tools you need access to:
- [ ] foresee
- [ ] Domo
_Please list any additional requirements, if any._

## Date Required
not urgent 

## Product Team / External Team / VA Office
VSA - Claims and Appeals
*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by joanneesteban** [comment]
Thanks for opening, Anna! Redirecting to the Contact Center team, @jwoodman5 .

**Comment by annaswims** [comment]
Could you also give @edmangimelli access too? ed.mangimelli@adhocteam.us

**Comment by jwoodman5** [comment]
Hi @annaswims - Sure thing, I will ad Ed to the request also. However, ForeSee can only add folks with VA.gov email addresses. Can you please provide those as well? Thanks.

**Comment by annaswims** [comment]
Ed.Mangimelli@va.gov and anna.carey@va.gov

**Comment by jwoodman5** [comment]
Thanks @annaswims. I put the request in and will confirm when you and Ed should be able to login.

**Comment by annaswims** [comment]
any updates @jwoodman5 ?

**Comment by jwoodman5** [comment]
@annaswims I was not clear on the process at first, but now understand you should have received a login/setup email at your va.gov email address. Can you please confirm if you did? Thanks.

**Comment by edmangimelli** [comment]
>Can you please confirm if you did? Thanks

I did!

**Comment by edmangimelli** [comment]
Thank you @jwoodman5 !

**Comment by edmangimelli** [comment]
@annaswims thanks for adding me! appreciate it 🍻

**Comment by jwoodman5** [comment]
@annaswims and @edmangimelli I asked our ForeSee contact to have your invitation sent again. Can you please check your va.gov email and complete the process within 5 days? Apologies it has been an ordeal. This was a new process to me and is a bit clunky. Also, please let me know if you don't get the email within that time frame as well. Thanks!

**Comment by annaswims** [comment]
Could you please resend the invite? I found the invite but it'd expired. It got mixed in with junk mail, didn't realize it would come from okta

**Comment by jwoodman5** [comment]
Hi @annaswims I did that and will let you know when I get confirmation, but please check within a couple of days as communication/confirmation hasn't been great so far. Thanks.

**Comment by edmangimelli** [comment]
@jwoodman5 reset my password 👍 
thanks again

**Comment by jwoodman5** [comment]
Thanks for the confirmation @edmangimelli. @annaswims you should have received a new ForeSee email as well. Please confirm when you're set and I'll stop bugging them :)

**Comment by jwoodman5** [comment]
@annaswims Did you have success as well?

**Comment by annaswims** [comment]
it worked! Thanks!
