### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#20245]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address

Please add ssuddath@governmentcio.com to the search and discovery team Typeahead DOMO Dashboard.

Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [x] Domo
_Please list any additional requirements, if any._

## Date Required
As soon as possible - Feb 24th, 2020. 

## Product Team / External Team / VA Office
Search & Discovery Team

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
Sam has been added to DOMO and the dashboard.  However, I think @joanneesteban will need to add him to the _Search and Discovery_ DOMO group.

I'll keep this open for now.

**Comment by bsmartin-ep** [comment]
Sam has been added to the correct DOMO group.  Closing...
