### ISSUE TITLE
[FE] Add message for upper limit of characters on form fields

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#20240]
Figure out and add an upper limit message for all the form fields

[for reference 1mb of raw text](https://gist.githubusercontent.com/khaykov/a6105154becce4c0530da38e723c2330/raw/41ab415ac41c93a198f7da5b47d604956157c5c3/gistfile1.txt)

**Comment by mdewey** [comment]
Blocked until a decision is finalized .

**Comment by mdewey** [comment]
The decision has been reached, see reference ticket

**Comment by mdewey** [comment]
@kristenmcconnell  and @abuckley3385  This is staging, can you take a look and provide feedback. Here is a long text file to test (https://raw.githubusercontent.com/mmcky/nyu-econ-370/master/notebooks/data/book-war-and-peace.txt)

**Comment by kristenmcconnell** [comment]
@mdewey Question about the second sentence in the error message "This field should be less than 500,000 characters. Please remove 5,904,606 characters" 

It doesn't have a period at the end of it. I know that this is the default messaging. If the default is without a period at the end, then lets go with it. I just want to make sure that we didn't accidentally remove a period.

**Comment by mdewey** [comment]
There are no periods in the [default messages.](https://github.com/department-of-veterans-affairs/vets-website/blob/31515d9da1f5d0d607ea2b3813ca4a721c14634e/src/platform/forms-system/src/js/validation.js#L25)

**Comment by kristenmcconnell** [comment]
@mdewey Then, I say that it looks good to me.
