### ISSUE TITLE
Find a VA Form - Search Tips

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#20257]
## User Story

As a Veteran or caregiver, I would like to be presented with some simple suggestions to improve the quality of my search terms so that I can find the form I am searching for without having to refine my search term multiple times.

## Expected Behavior

The Find a VA Form search page would display a brief suggestion on how one might format search terms to improve the success rate of being presented with the desired matching result(s).

## Acceptance Criteria

- [ ] Story is groomed and clearly defined
- [ ] Story is estimated, converted to an epic & broken into sprints of work
- [ ] Collab cycle-related tasks are created
- [ ] All work to implement, including collab cycle tasks are completed & tested
- [ ] Update is peer-reviewed and reviewed on Staging by PO, PM
- [ ] Feature flags are removed
- [ ] Change is live on Production

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 do you happen to recall what suggestion you mind for adding a helpful tip to Find a VA Form search?

**Comment by callen2563** [comment]
Let me check with the design system team to see what the help tip format should be and I will get back to you

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @callen2563.  John seemed to recall that you made a specific recommendation that seemed very straightforward, but we could not remember what that was.

**Comment by callen2563** [comment]
oooh that was for Yellow Ribbon, I had suggested the form label should say "Enter full school name" but I don't remember having a solution for this one

**Comment by MarciMcGuireGCIO** [comment]
Ahhh ok!  Thanks!

**Comment by callen2563** [comment]
So after looking at the form label and the message that pops up under the form if you type in an incorrect search term, form number etc. I would recommend leaving this message text as since it matches Yellow Ribbon help text and other tools.

**Comment by MarciMcGuireGCIO** [comment]
Cassandra reviewed and determined that the existing search tip is consistent with other VA.gov search tools and should provide enough guidance on improving the search term.
