### ISSUE TITLE
Access for [individual]

### ISSUE THREAD

**Issue by as-va** [department-of-veterans-affairs/va.gov-team#20253]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Adam Stilton
- Please Provide your email.
   > adam.stilton@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse, Software Engineer, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChrFPc59ZIJ8rPJLbdHIUrQFr/EguCcL3Myj2cFYQH06s3wUTjUeeXLwv3QbnDJ0ZqOclpvHqglTAuS6IRVboOLtevG0OgzbB5fnhXDJlt4VVIXpqcEMfQ6gNmalfjhA5jDtzfGTrYrxCm7mVUd/lYXIqvP4Su4R9RrZ4z1zf+E4Q9wAuBypMh8VkSCLGktav8Gfgh25xibfMyF0tv/4v2uwgzDoXLok+EbbgTEh5rWksLiWx+NlKrtRVYAqRZpWij5/3vvzvk8fRBB9yOQJqLadoNT1Fww/N7RmLeMASsXhyf3JY9Sw+4NLL94OgnchiGuYe42f328UdxRSRadeYvVQMoZcs31dqIbRQZ7GS78bWbri/IoTwZDbWfSDM8a0jSPSEBTXbObbEFWAV8HXDC01rAT5L8+DT7NQS0yU1BBjPA6rpmJCsfxakjfLWVCOqrMjdc95O7KfdslMg8gXy6cVuS8Nj4u5K6HVYlQTMoX1ZLqXqd2dLfOZEA2VqmNDM= AzureAD+AdamStilton@WIN-145HI4724UT
```

- Grant AWS Console access?
  > NO

**Comment by mydesignrocks** [comment]
Socks added
