### ISSUE TITLE
Build Covid-19 Vaccine Page | Spanish

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20256]
**User Story**
As a spanish speaking vet or caretaker seeking information on the Covid Vaccine, I would like to be able to view this information in spanish.

**Scenario 1:**
Given I am viewing the Covid Vaccine page in english: https://www.va.gov/health-care/covid-19-vaccine  
OR
tagalog:  https://www.va.gov/health-care/covid-19-vaccine-tag/
AND
I click the link for spanish "Leer esta página en Español/ 
THAN
I should be taken to the spanish version of the page: http://www.va.gov/health-care/covid-19-vaccine-esp/ 

**Acceptance Criteria**
 

1. User can link to spanish version from the English or tagalog version of the Covid Vaccine page 
2.  Accordion sections open and close on spanish page when clicked
3.  Accessibility checklist has been verified by dev
4.  Data is being sent to GA
5. All launch-gating accessibility items found for Corona page are addressed

**Scenario 2:**
Given I am viewing the Covid Vaccine page in spanish: https://www.va.gov/health-care/covid-19-vaccine-esp/
OR
tagalog: https://www.va.gov/health-care/covid-19-vaccine-tag/
AND
I click the link for english "Read this page in English"
THAN
I should be taken to the english version of the page: https://www.va.gov/health-care/covid-19-vaccine/

**Acceptance Criteria**
 

1.  User can link to english version from the spanish or tagalog version of the Covid Vaccine page 
2.  Accordion sections open and close on spanish page when clicked
3.  Accessibility checklist has been verified by dev
4.  Data is being sent to GA
5. All launch-gating accessibility items found for Corona page are addressed

**Comment by SKasimow** [comment]
I/A URL Info: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/cto-spanish-content.md

**Comment by youngfreezyVA** [comment]
@SKasimow can you provide the node ID for the spanish content? thanks
