### ISSUE TITLE
STEM AD: Add denial details content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20268]
As an education team member, I would like an applicant to view their rejected application and the reason for rejection when their application has been denied based on reasons that will immediately make them ineligible, so that the time to notify the applicant is reduced.

## Assumptions:
1. Completed behind feature flag `stem_automated_decision` (#13829)
2. Login to claims page here: https://staging.va.gov/claim-or-appeal-status/
3. 10203 denials are added to page found here: https://staging.va.gov/track-claims/your-claims

## Acceptance Criteria:
1. The user has the ability to access the denial details from the [claims listing page (Assumption 3)](https://staging.va.gov/claim-or-appeal-status/)
2. The URL for the details page is: https://[environment].va.gov/track-claims/your-stem-claims/[10203 denied claim identifier]/status
3. The page title is "Your Edith Nourse Rogers STEM Scholarship Application"
4. An information alert displays "Your application was denied on [Date: MMM. D, YYYY]."
    a. March, April, May, June, July are not abbreviated
    b. All other months are abbreviated to 3 letters.
5. The sub-title of the section is: "Why we denied your claim"
6. The first content section displays why the applicant was denied:
    a. The title of the section is: "You did not meet these criteria for the Rogers STEM Scholarship:"
    b. The content of the section matches that outlined in the content document (SA2)
    c. If the user has > 180 days of entitlement remaining, the entitlement denial reason content is displayed.

7. The second content section displays why the applicant would have been approved:
    a. The title of the section is: "You met these criteria for the Rogers STEM Scholarship:"
    b. The content of the section matches that outlined in the content document (SA2)
    c. If the applicant has entitlement data in EVSS, the Post 9/11 GIBill content is displayed.
    d. If the user answered yes to one of the following questions `"Are you enrolled in a science, technology, engineering, or math (STEM) degree program?"` OR `"Do you have a STEM undergraduate degree and are now pursuing a teaching certification?"`, the program eligible reason content is displayed.

8. The third content section displays the appellate rights of the applicant:
    a. The content of the section matches that outlined in the content document (SA2)

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222481/296056346/preview)
   a. [Link to prototype for folks without accounts](https://bahdigital.invisionapp.com/share/CUIAG8PZ85J#/screens/296056346)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/files/6091556/STEM_AD_Temporary_Content.txt)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16263

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1512&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah this is ready in staging.

**Comment by JenLJ** [comment]
In the sub-bullets that reference a variable date (usually when service and school data files were reviewed), the date is currently showing in brackets [ ].  It wasn't called out in the story, but the brackets should not be included.  
![Screen Shot 2021-03-11 at 7 14 57 AM](https://user-images.githubusercontent.com/36964225/110786600-545c9600-823a-11eb-95b4-950fae2e4971.png)

**Comment by amyknox** [comment]
UX 2/2 
Other than the date formatting Jen noted, this matches the assets provided on the story.  Be sure to catch the square brackets on the You met these criteria for the Rogers STEM Scholarship section 
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/f155d78b-884f-4f4e-8b71-e474787bace4)

**Comment by elder-joseph** [comment]
Hi @JenLJ and @amyknox, I appreciate the reviews. I took note of the brackets and have removed them in the content update story.

**Comment by sonntag-adam** [comment]
Closing story
