### ISSUE TITLE
[design] Design Eligibility page for the Higher-Level Review application

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#2026]
## User Story or Problem Statement
As a Veteran, I need to understand if I am eligible to apply for a Higher-Level Review so I know if applying for a High-Level Review is worth my time.

## Acceptance Criteria
- [x] The Eligibility page follows the [VA.gov Benefits Application Design pattern](https://dev-design.va.gov/patterns/benefit-applications#eligibility).
- [x] Left nav has been designed according to IA recommendations from #1913
- [x] Design shared and reviewed with the team
- [x] Plan for Content review (create a content review ticket for this and assign to Peggy Gannon)
- [x] Front End ticket created

**Comment by YanaRoy** [comment]
@carolynwill @kevinstachura to discuss details of this ticket.

**Comment by kevinstachura** [comment]
@peggygannon @mnorthuis  - wanted to get this ticket and a couple others on your radar as they require IA analysis for a left navigation. Will set up quick meeting to discuss

**Comment by carolynwill** [comment]
![02-request-higher-level-review copy](https://user-images.githubusercontent.com/10746807/68208963-5ce6f180-ffa0-11e9-8481-08f57a94c70e.png)
