### ISSUE TITLE
Investigate/Update gems with constraints

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#20266]
## Issue Description
Often developers set an intentional constraint on a gem due to breaking changes in later versions that may not be compatible. We will need to investigate if our defined gem constraints can or cannot be updated. 

Running `bundle outdated --groups` will point out gem constraints. 

[Gem update spreadsheet](https://docs.google.com/spreadsheets/d/1XAANeTmGK2-kSDyxk3qjlS3aODSWBIgFhPHAH7by9Ns/edit#gid=1749343339)

---

## Acceptance Criteria
- [ ] Run automated test suite
- [ ] Test manually
- [ ] Check each updated gem’s CHANGELOG — if available — for potential backward-incompatible changes.
---

**Comment by ericboehs** [comment]
As we move through the gem updates, we naturally are coming across constraints.
