### ISSUE TITLE
Find a VA Form: Most popular forms related to search topic

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#20273]
## User Story

As a user, if I enter a certain topic such as "health", I would like to be presented with the most popular forms related to that topic to possibly help me find what I'm looking for faster.

## Expected Behavior

When a user enters a key term such as "health" or "education", rather than bombard them with a potentially hard-to-navigate list of forms, we can provide links to the most popular forms in that category.

## Acceptance Criteria

- [ ] Story is groomed and clearly defined
- [ ] Story is estimated, & broken into sprint-sized pieces of work
- [ ] Collab cycle-related tasks are created
- [ ] All work to implement, including collab cycle tasks are completed & tested
- [ ] Update is peer-reviewed and reviewed on Staging by PO, PM
- [ ] Feature flags are removed
- [ ] Change is live on Production

**Comment by zacharymorel** [comment]
This seems similar to : https://github.com/department-of-veterans-affairs/va.gov-team/issues/10754
Are we solving the same problem here?

**Comment by MarciMcGuireGCIO** [comment]
Let's look at them.

**Comment by MarciMcGuireGCIO** [comment]
This has been added to the LIghthouse API on staging; will roll in with the UI changes scheduled for 7/6/2021
