### ISSUE TITLE
General Analytics Request for VAOS-backfill funnel data in Domo

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20270]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Lauren Ernest

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - VAOS
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
Jan 10 to present

## Analytics to Track Down
Community Care funnel data

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?
  - Daily

## Link to Metrics
https://va-gov.domo.com/page/443732151/kpis/details/1819615075

## Additional Comments
Data stops at Jan 9. Can this be updated updated daily like the VA funnel?
![Screen Shot 2021-02-22 at 10 07 42 AM](https://user-images.githubusercontent.com/72046525/108757333-8cf03600-74fe-11eb-95d6-00a72cde210d.jpg)

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
Funnel dataset has been backfilled and scheduled.  Closing...

![image](https://user-images.githubusercontent.com/62304138/108785204-ef692680-753e-11eb-8b0a-485e4303f9e5.png)
