### ISSUE TITLE
[OBE] Design the After You Apply page for the Higher-Level Review application

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#2028]
## User Story or Problem Statement
As a Veteran, I need to understand what to expect after I apply for a Higher-Level Review so I that I know how long the process might take and how to interact with VA if I have questions.

## Acceptance Criteria
- [ ] The `After You Appy` page follows the [VA.gov Benefits Application Design pattern](https://dev-design.va.gov/patterns/benefit-applications#after-you-apply).
- [ ] Left nav has been designed according to IA recommendations from #1913
- [ ] Design reviewed and shared with the team
- [ ] Content reviewed and finalized (create a content review ticket for this and assign to Peggy Gannon)
- [ ] Front End ticket created

## Current Page on va.gov
https://staging.va.gov/decision-reviews/after-you-request-review/

**Comment by kevinstachura** [comment]
@peggygannon @mnorthuis  - wanted to get this ticket and a couple others on your radar as they require IA analysis for a left navigation. Will set up quick meeting to discuss
