### ISSUE TITLE
Upload 10-10CG Dataflow diagram .sketch file to va.gov-team-sensitive

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#20293]

**Comment by mlighdc** [comment]
@tchrisdyer, Jonathan was the Designer before Dene so I assigned Dene for her visibility.

**Comment by kevinmirc** [comment]
We can rely on the latest data flow diagram, I don't see a need to update the .sketch file.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/260#issuecomment-838947481
