### ISSUE TITLE
Consider replacing Moment with date-fns

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#20292]
A different date library, date-fns, is being used in some platform code. It's unlikely that we could completely exclude Moment from our build, but we could potentially avoid moment-timezone, because date-fns uses built in browser apis (and the design system team polyfilled that for older browsers).

We should explore:
- How much effort would it take to convert our existing timezone related logic to use date-fns?
- What is the bundle size impact of using just date-fns (i.e. is date-fns + moment less than moment/moment-tz).

**Comment by LanceGundersen** [comment]
@laurenernest @jbalboni Findings: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/date_library_discovery.md

**Comment by jbalboni** [comment]
Closing this, will create some follow up tickets to do some of the work.
