### ISSUE TITLE
Find a VA Form: Update Search Results according to Style Guide; increase visibility of CTA links

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#20295]
## User Story

As a Veteran or caregiver, I want Find a VA Form search results to have a consistent appearance with the rest of VA.gov so that I don't have to re-orient myself with a different look and feel and briefly wonder if something is clickable.

## Expected Behavior

The list of results presented should be displayed in a manner that is consistent with the rest of VA.gov, and should provide clear visual cues that links and buttons are clickable.

![image](https://user-images.githubusercontent.com/73354907/109338290-0d32d600-7834-11eb-9aff-063cfe76d20d.png)

## Acceptance Criteria

- [ ] Story is groomed and clearly defined
- [ ] Story is estimated, & broken into sprint-sized pieces of work
- [ ] Collab cycle-related tasks are created
- [ ] All work to implement, including collab cycle tasks are completed & tested
- [ ] Update is peer-reviewed and reviewed on Staging by PO, PM
- [ ] Feature flags are removed
- [ ] Change is live on Production

**Comment by zacharymorel** [comment]
Does this need a designer?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I'm thinking not, as long as we follow these guidelines - https://design.va.gov/components/buttons and have the detail page links underlined.

I aaw the design & rationale for the "secondary" button (current CTA button) on that design system page , but I'd argue that the Online Tool CTA is **not** a secondary action that we are trying to downplay.  Agree, @johnhashva?   

I also see that the green button was created because some users were overlooking the blue buttons, so that's an option since green is already used on the Detail pages.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO CTA is on Staging: https://staging.va.gov/find-forms/about-form-10-10cg/

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel, my apologies.  

We should have had a quick chat to discuss.  This was actually intended to change the detail page link & button in the _search results_ so they are more prominent.  

In an [earlier comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20295#issuecomment-785328927), I mentioned that https://design.va.gov/components/buttons#primary-buttons explains the reasoning behind the green button (it was changed from blue to stand out more), so we'd want to keep that on the detail page and also use it on the Online Tool button.

**Comment by MarciMcGuireGCIO** [comment]
I'll add some screen shots above to clarify

**Comment by zacharymorel** [comment]
Ha whoops. No worries @MarciMcGuireGCIO . 
YES, give all the screen shots!

**Comment by MarciMcGuireGCIO** [comment]
Thanks! :) Added image & comments above.

**Comment by zacharymorel** [comment]
Okay, I am revisiting this now.

**Comment by jenniferlee-dsva** [comment]
Hey, a qq - was this an ask by accessiblity? 

I ask bc Ryan and I deliberately did not use the primary button design because it's not technically "primary" -- there could be multiple instances of these on a results for example.

**Comment by jenniferlee-dsva** [comment]
Design changes always need a design consult.

**Comment by jenniferlee-dsva** [comment]
We also do not underline links that use the carat > affordance. This was cleared with the 508 person at the time when we launched -- though I understand, if the guidance has changed.

**Comment by rtwell** [comment]
hi there chiming in!


the design system team is currently auditing and consolidating both our link styles, how we use buttons vs links, and the guidance for both. until that work is fully fleshed, i recommend:

1. **links**: there does not need to be an underline. 
2. **CTA**: please keep as a secondary button.

**Comment by MarciMcGuireGCIO** [comment]
Closing ticket per above commentary.

**Comment by MarciMcGuireGCIO** [comment]
@jenniferlee-dsva @rtwell Thank you both for the valuable feedback. I was in meetings and wanted to read through the comments before responding further. You both bring good points, and we will keep an eye on our click metrics and any upcoming design systems changes.
