### ISSUE TITLE
Access for [Cris Shupp] 

### ISSUE THREAD

**Issue by cshupp1** [department-of-veterans-affairs/va.gov-team#20297]
Fill out Description
Add the label used by your team (eg: Matsumoto)
Do not remove operations label; this will notify the VSP Operations team of your request
When the issue is closed you will be notified and can continue with on-boarding setup
Description
Please provide your Contracting Officer's Representative (COR) name.
Cecilia Lee - Cecilia.Lee@va.gov

Please provide your name.
Cris Shupp

Please Provide your email.
cristopher.shupp@libertyits.com

Please provide the name of your team, your role on that team, and the name of the company you work for.
Team Matsumoto, Senior Software Engineer, Liberty IT Solutions

Regarding SSH authorization, I have requested it previously. Here is the ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15064

Grant AWS Console access?
YES
What AWS services do you need access to and why?
I need production access for the Benefits Intake API in order to provide support.

**Comment by mleclerc00** [comment]
### For AWS Access:

User: Cris Shupp
COR: Cecilia Lee
Approval required: @Jeff-Hayter

**Comment by NCHLiberty** [comment]
Hello. Checking in on this request. We face a lot of obstacles and delays due to having only one team member with this access today. Can you provide a rough timeframe estimate? Thanks!

**Comment by mleclerc00** [comment]
Hi @NCHLiberty we just waiting for approval from @Jeff-Hayter so access can be provided

**Comment by Jeff-Hayter** [comment]
@mleclerc00 Approved for AWS.

**Comment by mleclerc00** [comment]
Thanks, will get around to this today
