### ISSUE TITLE
Compile list of Practice Area meetings and slack channels that would be helpful for new VFS Teams

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#203]

**Comment by rroueche** [comment]
# User Story

As a VFS team member, I need to feel welcome in practice area meetings where collaboration, feedback, and updates are happening, so that I have a friendly venue for raising issues, learning what other things are happening on VA.gov, and getting feedback on my own work prior to more official review meetings.

# Hypothesis

Frequent feedback enables teams to pivot faster to get closer to the things they need to have in place to launch, good to get eyes on what they're working on

# Goal

Include practitioners in the slack channels and regular meetings for their practice areas, for opportunities to get feedback/ideate/collab

# AC
- [ ] List of practice area meetings is in onboarding documentation
- [ ] List of practice are slack channels is in onboarding documentation
- [ ] Both of those things are included in onboarding meeting collateral

# Definition of Done
- [ ] AC met
- [ ] Collateral provided to DSVA for review

**Comment by emilywaggoner** [comment]
Started a draft for this here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Intake/June%202019%20MVP%20Workshop/meetings-and-slack-channels.md
@rroueche Let me know if you think there is a better place to store this work, and any other thoughts you have so far on the general structure/approach. I'm positive there are more meetings/syncs to track down and add!

**Comment by smoonpeyes** [comment]
@emilywaggoner Do we need to change you to be the owner of the VA.gov Weekly Design + Content + Research sync?

It looks like we still need info on how to get people added to meeting invites. Would it simply be reaching out to the meeting owner? Should they also get added to the demo meeting?

**Comment by emilywaggoner** [comment]
@smoonpeyes Yes, we can change it to me after next Monday's meeting I think. There is probably a more sophisticated way to get people into these meetings but I've been thinking for the MVP it would be totally reasonable to have the teams reach out to the meeting owners. Good idea to add the demo meeting to the list as well.

**Comment by rtluu** [comment]
hey @emilywaggoner & @smoonpeyes, just came across this item and wanted to check in to see if there is more work to be done here. LMK at your convenience!

**Comment by accbjt** [comment]
@emilywaggoner @rroueche How does VFS teams get access to Slack, ZenHub, and GitHub. Is the support team responsible for this task or does someone else do this. If the support team is responsible, how do we make sure we have the resources to do it before we on-board the first team.
