### ISSUE TITLE
Facilities found outside map when using Search this area button

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20302]
## What happened?
Please see [this Loom](https://www.loom.com/share/bae53b16a6af4b238790d0ea2ec1d57f). 

# Steps to reproduce

1. Search with parameters: Polson, Montana + Community care providers + Optometrist
2. After a successful search, drag the map to the east until the "Bob Marshall Wilderness" appears in the center, and initiate a new search using the "Search this area button". 

Matching locations are shown in the list, but they are not shown on the map.

## Specs:
- Device: Windows
- Browser: Chrome

## Desired behavior
Locations returned in the result list should be visible on the map

**Comment by mpelzsherman** [comment]
This diagram created by @darkbushido illustrates the problem:

<img width="338" alt="Poulson__MT_CCare_Optometrist_-_Google_My_Maps" src="https://user-images.githubusercontent.com/80267/109698990-0373e000-7b5e-11eb-9292-745b5e18721c.png">

Our code is using the corners of the bounding box to compute the radius. We should be using the values indicated by the red line instead: the latitude of the center point and longitude of the left side.

**Comment by mmiddaugh** [comment]
Fix looks good to me
