### ISSUE TITLE
Analytics Implementation or QA Support for VAOS (VAOS for Distribution Initiative)

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20309]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Implementation, guidance, QA

- Who is this request for?

    - Lauren Ernest
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - VAOS - VAOS for Distribution initiative
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
    - https://www.va.gov/health-care/schedule-view-va-appointments/appointments/
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - targeting mid-March for MVP dev complete

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
      - See [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/Cheetah%20MVP%20IA%20Notes.png) for more info (sensitive repo)
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
      - Facility phone number clicks
      - KMI link clicks
      - FL link clicks

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Same as above

- Certain conditions/responses that need to be reviewed

    - See link under Conversions for more info

- Additional Comments

    - There will be additional changes to this flow before launch

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by laurenernest** [comment]
This might end up being mostly for GA reports, but created a ticket just in case additional work is needed.

**Comment by joanneesteban** [comment]
@laurenernest - confirming here if you're looking for GTM implementation or a GA report? Thanks!

**Comment by laurenernest** [comment]
For sure a report, but since this is a new flow with new pages I wasn't sure if there was any other GTM implementation that needed to happen.

**Comment by laurenernest** [comment]
We'll be tracking this flow with distinct start and submission event names. Ticket here #20035

**Comment by jonwehausen** [comment]
Hi @laurenernest , 

Thank you for your patience on this request. 

After taking a look at your mockup [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/Cheetah%20MVP%20IA%20Notes.png) and walking through the flow I would agree we should implement a distinct `vaos-covid19-path-started` event at the beginning of the covid19 scheduling, and a `vaos-covid19-submission` and `vaos-covid19-submission-successful` event. This is in alignment with what we've down for other scheduling flows. 

For your awareness, there won't need to be any GTM changes we need to make here. 👍 

Additional small piece to note, I personally wasn't able to effectively fire a `vaos-covid19-path-started` event within my application-side staging testing -- that said, I do see the event implemented within `vets-website` [here](https://github.com/department-of-veterans-affairs/vets-website/blob/3f3afca1209882160cd79690c154a0d81c6eac15/src/applications/vaos/project-cheetah/redux/actions.js) and I'm sure @jbalboni has put in place where you all would like to consider that vaccine flow "started". 

I did see if we had any examples of a `vaos-covid19-path-started` within our non-prod property and did not see any examples: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20210301&_u.date01=20210323&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.filter=covid19&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=2500. We would appreciate your coordination here on where we should be seeing this event fire today within the flow. Once we can verify this, we can perform final testing and close. 

Here is a full list of the covid19 events names I've seen thus far: 
- `vaos-schedule-covid19-button-clicked`: // when the schedule covid 19 button is clicked 
- `vaos-covid19-path-started`: //when the covid19 path should be considered started
- `'vaos-covid19-screener-no'` //following answer to "Have you received a covid19 vaccine?" with option no
- `'vaos-covid19-screener-yes'` //following answer to "Have you received a covid19 vaccine?" with option yes
- `'vaos-covid19-submission'` //on all attempts to submission of covid vaccine submisison
- `'vaos-covid19-submission-successful'` //when covid vaccine submission is successful

@jbalboni I haven't seen a `vaos-covid19-submission-failed1` event, but please feel free to add this in for failed submission attempts as well if not already.

**Comment by laurenernest** [comment]
Thanks for confirming no GTM changes are needed :) 

The failed event was implemented in #20035, but I'm not sure if we've had occurrences in staging yet.

Staging - With the current version of the flow, `vaos-covid19-path-started` and `vaos-schedule-covid19-button-clicked` should occur at the same time (They were different in our first version of the flow). I'll write that up for our team to fix.

Production - The earliest we anticipate real data is Tue, 3/30 with the pilot we're doing. Though there may be some events between 3/25-3/29 due to testing.

**Comment by jonwehausen** [comment]
Sounds great @laurenernest , and thank you for that context. 

Let us know when you've got that fixed and we can verify the `vaos-covid19-path-started` and `vaos-schedule-covid19-button-clicked` events and close this out. 

I also noticed in your request for : 
>Facility phone number clicks
>KMI link clicks
>FL link clicks

Here is a [custom report template](https://analytics.google.com/analytics/web/template?uid=rSBwd22_T0K8Dkpp4GjMPw) you can add to the All VA.gov Website Data [Production] view that is a Previous Page Path report for VAOS. This report lists the pageviews for **pages where the previous page path was within the VAOS IA (url structure), and the next page was not also a VAOS IA page**. You could then for example use the search box on the right hand side for _"facility"_ to see your list of facilities VAOS is leading users to. 

@laurenernest Could you elaborate on what you're looking for with KMI links (apologies I'm not familiar)? 

For facility phone number clicks, we can [provide a report that showcases the top phone numbers](https://analytics.google.com/analytics/web/template?uid=2_3XpdQURWmy_8KzqR9PpQ) that are clicked within the VAOS IA. Unfortunately, this is captured by out outbound link tracking we have site-wide so it doesn't provide context into what facility it was for example. That said, there are certainly examples of the top phone numbers that can be traced to facilities (i.e  `Outbound Link Clicked: tel:+14076311000`)

Shifting this ticket to our QA column.

**Comment by laurenernest** [comment]
We're working on that fix now and we'll let you know.

That Previous Page Path report is perfect! For KMI (keep me informed), I'm looking at clicks out to the COVID-19 vaccine page so this covers it.
- ? Once we have Prod data for the pilot, if I change the "Include" filter regex to `^www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking.*` that would narrow down to only the clicks from the new flow, correct?

The Phone Number Clicks report is great! I'll look for a way to map those phone numbers to facilities manually.

**Comment by jonwehausen** [comment]
Yes that is correct @laurenernest, you can re-use and adjust that `Previous Page Path` as needed for any page-level granularity you're looking for and don't care to any VAOS pages -- of course you can also flip the secondary filter from `Exclude` to `Include` for when you do and do not want to consider VAOS pages. 

Hope this is helpful -- we'll wait to hear from you on the `path-started` event fix.

**Comment by laurenernest** [comment]
The path started events should be showing now.

**Comment by laurenernest** [comment]
Thanks for confirming! Good to close.
