### ISSUE TITLE
"Stay Informed" Widget is Translated to Spanish

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20310]
# The "Stay Informed" widget should be displayed in spanish on the spanish Vaccine page:

![Screen Shot 2021-02-22 at 8.32.56 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/72ed106c-97e9-4f0e-8760-bc7a042554ec)

Note: it will link to english sign-up form.

# **User Story**

# ** Scenario 1: **

As a user viewing the spanish version of the Covid Vaccine page (insert link) I would like to have information directing me to the sign up page to keep informed.

Sign-up page: https://www.va.gov/health-care/covid-19-vaccine/stay-informed

# **Acceptance Criteria**
 
1. User can click link to the english version of the "sign up" form  
2.  Accessibility checklist has been verified by dev
3.  Data is being sent to GA

**Comment by SKasimow** [comment]
@youngfreezyVA - let me know if there is anything specific that needs to be defined once you have a chance to review. 
I assume analytics can be copied over from English widget.

**Comment by DanielleThierryUSDSVA** [comment]
Hi. Status update from translation service. Hoping to have translation for this by Monday. Should not be later than Tuesday. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@youngfreezyVA @SKasimow Here's the Spanish translation for this component. Thank you!

[for direction only: stay informed callout]
**Manténgase informado sobre cómo recibir la vacuna contra COVID-19**

Inscríbase para una manera fácil de mantenerse informado sobre cómo recibir la vacuna contra COVID-19 en el VA.
Cuando se inscriba, también le preguntaremos acerca de sus planes de vacunas. Su centro de salud del VA local puede usar esta información para determinar cuándo contactarle una vez que su grupo de riesgo sea elegible. Por favor, tenga presente que estas actualizaciones solo están disponibles en inglés en este momento.

**Nota:** Intentaremos contactar a todos los Veteranos elegibles en cada grupo de riesgo. No es necesario que se inscriba para recibir la vacuna.
[Button] Regístrese para mantenerse informado (en inglés)

**Comment by DanielleThierryUSDSVA** [comment]
And when you need it, here's the Tagalog translation:

[for direction only: stay informed callout]
## Manatiling nakikibalita tungkol sa pagpapabakuna para sa COVID-19

Mag-sign up para sa madaling paraan ng pakikibalita tungkol sa pagpapabakuna para sa COVID-19 sa VA.

Kapag nag-sign-up kayo, magtatanong din kami tungkol sa inyong mga plano sa bakuna. Maaaring gamitin ng inyong lokal na pasilidad-pangkalusugan ng VA ang impormasyong ito para matukoy kung kailan makikipag-ugnayan sa inyo kapag naging kwalipikado na ang inyong pangkat ng panganib (risk group). Pakitandaan na ang mga update na ito ay nasa English lang sa ngayon.

**Paalala:** Susubukan naming makipag-ugnayan sa bawat-isang kwalipikadong Beterano sa bawat pangkat ng panganib. Hindi ninyo kailangang mag-sign up para makapagpabakuna.

[button] Mag-sign up para manatiling nakikibalita (sa English)

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Thanks Danielle!

cc @youngfreezyVA

**Comment by youngfreezyVA** [comment]
<img width="793" alt="Screen Shot 2021-03-01 at 5 01 43 PM" src="https://user-images.githubusercontent.com/46791771/109580665-cea94f80-7aaf-11eb-81e2-d679a8f71fc6.png">
does this look ok? @SKasimow @DanielleThierryUSDSVA

**Comment by youngfreezyVA** [comment]
also, I noticed there is an `appTitle` as well for the widget... "Covid 19 Vaccination Information"
I've put `Información de vacunación contra Covid 19`
as a placeholder, let me know if there is already a better translation :)

**Comment by SKasimow** [comment]
@youngfreezyVA this looks GREAT!!

**Comment by SKasimow** [comment]
@youngfreezyVA where is the app title for the widget showing? not seeing it on screenshot above...

@DanielleThierryUSDSVA for approved translation

**Comment by youngfreezyVA** [comment]
oh its internal to our micro apps architecture, it doesn't show up on the UI, not sure if that needs to be translated in that case

**Comment by SKasimow** [comment]
@youngfreezyVA I don't think so but @DanielleThierryUSDSVA can you confirm?

**Comment by youngfreezyVA** [comment]
I was wondering if this set of text needs to be translated also or not:
```import React from 'react';
import AlertBox, {
  ALERT_TYPE,
} from '@department-of-veterans-affairs/component-library/AlertBox';

export default function OffState() {
  return (
    <AlertBox
      status={ALERT_TYPE.INFO}
      headline="Check back soon for an easy way to stay informed and help us prepare"
      content={
        <>
          <p>
            We're creating an easy way for you to sign up to stay informed about
            our COVID-19 vaccine plans.
          </p>
          <p>
            When you sign up, we’ll also ask about your interest in getting a
            vaccine when one is available to you. By sharing your interest, you
            can help us better prepare as we work to offer vaccines to more
            Veterans.
          </p>
          <p>
            <strong>Note:</strong> You don't need to sign up to get a vaccine.
          </p>
        </>
      }
    />
  );
}```

**Comment by SKasimow** [comment]
@youngfreezyVA Can you show me where this alert appears on the English page?

**Comment by youngfreezyVA** [comment]
![image](https://user-images.githubusercontent.com/46791771/109839310-d6760a80-7bfb-11eb-9b57-4648ad1d025c.png)
this is what shows up when the associated feature toggle is turned off
cc: @ncksllvn
