### ISSUE TITLE
Stakeholder & SME Interviews for HealthRecord Discovery

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#20315]
- [ ] Complete [interview list on this page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/health-record/interviews.md) to inform our research and priorities 
- [ ] Document Notes from each session 
- [ ] Include in Key findings for Stakeholders Research

**Comment by abuckley3385** [comment]
Placing on hold to pick up CheckIn project.

**Comment by julieadair1** [comment]
@jparker0425  - any idea if this is something we still need to address? 
cc: @batemapf

**Comment by jparker0425** [comment]
Not sure what this was related to @julieadair1  (prior to us coming on board). This was on hold apparently due to check-in being prioritized and there are no items listed, so I am going to close this and if anything ever comes up again we can open a new one.
