### ISSUE TITLE
Investigate Efficacy of Pending Items on Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2031]
## Goals
Determine whether the information provided in the Claim Status Tool for Pending Ratings is the same as what is trying to be displayed on Rated Disabilities.  It might be possible that we don't need this feature.

## Definition of Done
- [x] Establish whether or not the Pending information is redundant

**Comment by steve-gov** [comment]
Confirmed that "Pending Disabilities" are actually claims in process.

![pending-disabilities](https://user-images.githubusercontent.com/25468689/65714930-ebd32680-e050-11e9-9d8a-a878af5b8b56.gif)

**Comment by steve-gov** [comment]
Better screencap: 

![pending-disabilities-2](https://user-images.githubusercontent.com/25468689/65715632-56d12d00-e052-11e9-8acb-66b4b703dbcf.gif)
