### ISSUE TITLE
Update checkbox CC: add error state

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20311]
## Acceptance Criteria
1. Update the checkbox common component to include an error state
2. UI details:
     - Border: solid, #CD2026
     - Width: 2px
     - Error text: Mobile Body Bold, #CD2026
3. Scenarios when this error state will appear:
     - Checkbox is unselected, and user tries to "Save" the form
     - Checkbox is selected, then unselected

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/442012725
svg: ![Container.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9634f3be-377c-4028-ac00-dbdca95d4a1e)

![Screen Shot 2021-02-22 at 5.46.21 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/41de1ac1-3889-4812-a466-04dc5abcbaef)

**Comment by digitalken** [comment]
Added to TestRun.

**Comment by digitalken** [comment]
PASS 3/10/2021 - Looks good.  Designs aren't right for text content.  Seeing "Please confirm this information is correct" on the device and it was confirmed as valid.  Closing.
