### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va.gov-team#20324]
# Request Google Analytics and/or Domo access

## What this form is for
I would like access to the VA.gov Google Analytics so I can ensure that the Lighthouse metrics match the VA.gov metrics for Appeal submissions.

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.
I'm not sure which email you'll need:
kelly@adhocteam.us (Google Account)
kelly.lein@va.gov

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [ ] Domo
_Please list any additional requirements, if any._

## Date Required
Soon please

## Product Team / External Team / VA Office
Lighthouse Team looking to track VA.gov usage of our API

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
@kellylein GA access has been granted to your AdHoc email.  You should receive an email shortly.

Let me know if you have any questions.

Closing...
