### ISSUE TITLE
CMS Export Retrospective

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#20325]
WIP meeting agenda for March/April
# Ground Rules
**Regardless of what we discover, we understand and truly believe that everyone did the best job they could, given what they knew at the time, their skills and abilities, the resources available, and the situation at hand.**

# Background

# Timeline

| Date | Event | Reference |
| --- | --- | --- |
| Nov 2019 | Superteam formed | [Charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/cms-metalsmith-build/2019-11-superteam-draft-charter.md) |
| Feb 2020 | CMS Export epic created | [Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5989) |
| Jan 2021 | CMS Export status: pipeline implemented only in dev env, transformers code incomplete | [RFC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20165) |
| Jan 2021 | CMS Export status: pipeline implemented only in dev env, transformers code incomplete | [RFC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20165) |
| Jan 2021 | CMS Export benchmarks show poor scaling performance | [Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18592) |
| Jan 2021 | GQL benchmarks show build failure at =<13k nodes | [Benchmark](https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=682480522) |
| Jan 2021 | VAMC Rollout is projected to exceed 13k nodes by mid-April | [Roadmap](https://docs.google.com/spreadsheets/d/1pa0EgHuOXINvool4QHjV3lIDyYf-p9JRr8z1AuW4HFE/edit#gid=0&range=M13)
| Feb 2021 | Refactor of monolithic GQL query | [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15974)
| Feb 2021 | GQL multiquery successfully bencmarked to 14k nodes | [Benchmark](https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=1540963105&range=G18:I18)
| Feb 2021 | EOL CMS Export | [RFC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20165)
| Mar 2021 | CMS team scales Drupal infrastructure | 
| Mar 2021 | FE Tools optimizes downstream GQL build | [Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20763)
| Mar 2021 | FE Tools implements automated content-only builds | [Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18845)
| Mar 2021 | GQL multiquery successfully benchmarked to >=35k nodes | [Benchmark](https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=1569583465)

# Topics

- How could GQL perf improvements have been discovered earlier?
- What were the original assumptions that led to the decision to move forward with the transformers?
- Could these have been verified sooner?
- What communication issues contributed to delays in reaching a decision to pursue alternative approaches?

# Lessons Learned

- Cross-team collab needed for build pipeline

# Action Items

Have retrospective meeting.

# Result

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/cms-metalsmith-build/cms-export-retrospective.md

**Comment by mpelzsherman** [comment]
Additional topic suggestions:

- What were the original assumptions that led to the decision to move forward with the transformers? 
- Could these have been verified sooner?
- What communication issues contributed to delays in reaching a decision to pursue alternative approaches?

**Comment by mpelzsherman** [comment]
One more:

- When the decision was made to spend developer time on the parallel graphql queries, should this have been communicated more widely?

**Comment by mchelen-gov** [comment]
interesting [slack thread](https://dsva.slack.com/archives/C01512KN35G/p1593450223135300) from June, some things that stand out to me are:
- many different parts of build system contributed to confusion about what servers & infra are the bottleneck
- goal was defined as all-or-nothing target, thereby ruling out partial solutions
- related objective (preview server) with undetermined solution contributed to feature scope
- cms export technical hurdles had not been fully discovered

**Comment by mpelzsherman** [comment]
> interesting [slack thread](https://dsva.slack.com/archives/C01512KN35G/p1593450223135300) from June

What stands out to me is how quickly and forcefully the parallel query approach was dismissed. At this point, the transformers had been under development for 8 months or so (this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10973) dates back to Oct. 2019).  It should have already clear that there were significant challenges with the tome-sync/transformer approach.
