### ISSUE TITLE
Delete Contact Information CC

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20334]
## User story
As a user, I want the ability to delete my contact information from my VA profile.

Note: please reference the Content Spreadsheet for page-specific copy. See tab: **Delete Contact Info Copy** https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit?usp=sharing

## Acceptance Criteria
1. Create common component for deleting contact information fields (Home Address/Phone/Email)
      - On the edit screens, display a Large Button below the form:
          - Pull in Large Button CC _(note: the wireframes show a darker blue button, but please use the primary blue #0071BB that we're using on other large buttons.)_
          - Button label: "Remove [page name]"
2. Rules for when the **Remove [page name]** button should appear:
     - This button should only display on edit screens that contain a saved entry
     - Test: if the Personal Information overview page does not display an entry, the edit page should not display this Large Button
3. Selecting the **Remove [page name]** button does the following:
     - Large button disappears
     - Display mobile alert in place of the button
4. Mobile alert UI _(Note: please reference spreadsheet linked above for the exact copy across each page)_
     - Header 2: "Are you sure you want to delete your [page name]?"
     - Description: "This will delete your [page name] across many VA records. You can always come back to your profile later if you'd like to add this information back in." 
     - Large Button (primary): Confirm (UI only)
     - Large button (secondary): Cancel
5. Cancel button removes the mobile alert and reinstates the **Remove [page name]** button on the edit screen
6. Apply this common component (AC 1-5) to the following edit pages (all EXCEPT mailing address):
     - Home address
     - Home phone
     - Work phone
     - Cell phone
     - Fax
     - Email address

## Designs
Design #1: https://adhoc.invisionapp.com/d/main/#/console/20546460/442018169/preview#project_console
Design #2: https://adhoc.invisionapp.com/d/main/#/console/20546460/442018170/preview#project_console

## Content
https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit?usp=sharing

## UX ticket
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/17058

## Accessibility Implementation Guidelines

**Remove [page name]** button:
accessibilityLabel= “Remove [page name]”
accessibilityRole= "button"
accessibilityHint= "Remove [page name] from profile"

- Mark "Are you sure you want to delete your [page name]?" as Header 2

**Confirm** button:
accessibilityLabel= "Confirm"
accessibilityRole= "button"
accessibilityHint= "Confirm you want to delete your [page name] and go back to the Personal Information page"

**Cancel** button:
accessibilityLabel= "Cancel"
accessibilityRole= "button"
accessibilityHint= "Cancel and continue editing"

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/29/2021 - (GUI only.)  Accessibility fails as all accessibility hints for the big buttons are missing.  Logged the bug so I'm going to close this ticket out.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22296
