### ISSUE TITLE
Access for Jesse Abando

### ISSUE THREAD

**Issue by jabando-va** [department-of-veterans-affairs/va.gov-team#20335]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Jesse Abando
- Please Provide your email.
   > jesse.abando@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Shanktopus 
Role: Software Developer
Company: Liberty IT Solutions.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCgdiZqJ6o+HhZKTMSYIGZYqLJyRHjXHdJpJbGXhpk/Y8CAku0bf6Zo+Mu2dZNqzD2PLYxS3l165KO1rNU4HCCixsPpvZw3BqIGTYc41Uj+zZDZMKtwpSyxT7qBSPdgLHb56PGmCPhkL7mD5VSl/f9yZEc+X5FezBjOi8+RydDuex0ozKqKlpx634nwqD+oQNpGNOtjvVD9y60esQvM+wImyNeO5TpPMQmlHkAN4yV6FO8efn+g6taKPKl6rnPIupcTA3ssfAZuU1EIgJlxFoK4p40456AcyUrxRdRfkLmsVEa2xLae5YzYar654idxUmfn1hNoWJ+uVt4cDeKHQsCg5kbxHGPm9/mpug2jhGphaYC/FcMMfbi/Jb6pVWn/jASv4plSg6MfvDR+QrX42Qt2zg1la1Hzb41KiiHTNu3IvVU/KTLfUqo/mE8smge3PaLOdF7xvlra4aFCKVyck1rXWmyCLQXk160D4mk4PF0gxZcbvGppJE33/+hd2Xa2yk8= AzureAD+JesseAbando@WIN-8VCGAPBFQPP
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jjabando1** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by mleclerc00** [comment]
Hi @jjabando1,

I have added your key to the socks configuration so you should access now.  If you get a chance please test this out and let me know if you have any further issues.

Thanks!
