### ISSUE TITLE
Analytics Implementation for Facilities - Vet Centers 1.0

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20347]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description

What is this request for?
- Request for Google Analytics implementation 

Who is this request for?
 - Michelle Middaugh

What team/project is this work for?
 - Facilities - Vet Centers 1.0

Provide the Domain where Google Analytics needs to be implemented
- new Vet Center pages (URL TBD)
- These pages are unauthenticated and have no PII risk

Please provide any upcoming deadlines or important milestones
- Deadline for the initial roll-out of first 10 pages -> March 31, 2021
    
## Requested interactions

Page | Description of interaction | Screenshot | Data layer specification | Label
-- | -- | -- | -- | ---
**Main page** | Clicks on `Jumplinks` | ![jumplinks](https://user-images.githubusercontent.com/55411834/109728472-79367680-7b73-11eb-9c78-fed5504ec707.png)| `'event': 'nav-jumplink-click'` |  
**Main page** | Clicks on `Get directions` link from main page | ![image](https://user-images.githubusercontent.com/55411834/109728559-adaa3280-7b73-11eb-95b1-05a11cba3578.png)| `'event': 'directions-click'` |  
**Main page** | Clicks on `View other locations` link | ![image](https://user-images.githubusercontent.com/55411834/109728606-cadf0100-7b73-11eb-9fb9-1f238e8da9b7.png) | `'event': 'view-other-locations-click'` |  
**Main page** | Opening/closing `Prepare for your visit` accordions | ![image](https://user-images.githubusercontent.com/55411834/109728661-e1855800-7b73-11eb-8548-4db242b10e4e.png) | event': 'int-accordion-expand', //OR 'int-accordion-collapse''accordion-label' //populate with accordion parent label | Accordion-label= "appointments", "parking", "transportation", what to bring"
**Main page** | Opening/closing `Service`  accordions | ![image](https://user-images.githubusercontent.com/55411834/109728737-0679cb00-7b74-11eb-8aa5-13021ea1c769.png) |   | Accordion-label = "Mental health care","Military sexual trauma care", "Minority Veteran care",  etc
**Main page** | Clicks on phone numbers within `Service` accordions | ![image](https://user-images.githubusercontent.com/55411834/109728823-2c9f6b00-7b74-11eb-8547-2aa6e89f18e6.png)|   | Add prefix with accordion-section-label to indicate the number was clicked from within an accordion (and which accordion)
**Main page** | Clicks on any Spotlights `link` or `CTA ` | ![image](https://user-images.githubusercontent.com/55411834/109728708-f7931880-7b73-11eb-9c49-cde47456d42d.png)|   |  
**Main page** | Events on `How we're different than a clinic`accordions | ![image](https://user-images.githubusercontent.com/55411834/109728869-42149500-7b74-11eb-863b-41aee3985ece.png) |   | accordion-section-label = "What are Vet Centers", "Eligibility", "Enrollment", "Privacy"
**Main page** | Clicks on main location phone number | ![image](https://user-images.githubusercontent.com/55411834/109728924-56f12880-7b74-11eb-9a16-99cbc2e13ef3.png) |   |  
**Main page** | Scroll depth for main page | | Can get from GA |  
**Locations page** | Clicks on `Get directions` link from Locations page | ![image](https://user-images.githubusercontent.com/55411834/109728972-6ec8ac80-7b74-11eb-9a46-6b039ef11064.png)|   | Add prefix to indicate the user clicked from the Locations page
**Locations page** | Scroll depth for Locations page | | Can get from GA |  
**Locations page** | Clicks on Location phone numbers | ![image](https://user-images.githubusercontent.com/55411834/109729402-0d550d80-7b75-11eb-8fbf-bff20ce9e213.png) |   | Add prefix to indicate the user clicked from the Locations page |

## Additional Information
[Link to uxpin](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/136042529/simulate/no-panels?mode=cvhidm)
> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by joanneesteban** [comment]
@mmiddaugh confirming that this is separate from VAMC and Facilities?

**Comment by mmiddaugh** [comment]
@joanneesteban yes - this is to prepare the data layer for the new Vet Center webpages which will soon be rolling out for the first 10 locations. I think we just need a bit of help with the data layer specifications but I tried to take as much as I could from the VAMC specs to make it _(hopefully)_ more efficient for your team

**Comment by jonwehausen** [comment]
Hi @mmiddaugh , 

Thank you for your patience on this request. I will be working through this data layer specification today. 

Do you have a staging URL at this point you could provide or are you still in the build process?

**Comment by mmiddaugh** [comment]
We're beginning the build process this sprint,  hoping for the rollout of the first 10 by mid-late April. 
We will be validating the templates in Tugboat.

**Comment by jonwehausen** [comment]
### Data Layer Specification 

- @mmiddaugh Thank you for your patience on this request -- I believe this covers everything you initially had above just condensed to include redundant actions agnostic of page location (accordions, directions, phone numbers, etc)
- Was able to take a look at @brangi 's mockup [here](https://web-zxlmoigkwacrdik2fa9rcshntpmrauhr.demo.cms.va.gov/escanaba-vet-center/locations/)


Description/Screenshot of interaction | Data layer specification | Dev Notes
| -- | -- | -- | 
Any clicks on jumplinks | `'event': 'nav-jumplink-click'`
Clicks on directions links ![image](https://user-images.githubusercontent.com/48527022/115393948-417d9f80-a1b0-11eb-9dfa-df0c95bd3128.png) | `'event': 'directions-link-click',`<br>`'vet-center-facility-name': //i.e 'Escanaba Vet Center - Marquette' populate with the name of the vet center facility` 
Clicks on phone number links ![image](https://user-images.githubusercontent.com/48527022/115393966-48a4ad80-a1b0-11eb-991d-890ba3e1bc0b.png) | `'event': 'phone-number-link-click',`<br>`'vet-center-facility-name': //i.e 'Escanaba Vet Center - Marquette' populate with the name of the vet center facility` 
Clicks on View other locations link | `'event': 'view-other-locations-click'` |  💡 _Where is this link going to lead to?_ If this is the only link of its kind on the page for view other locations, we don't need an event here and can instead use a previous page path report 
All accordions expands & collapses on main, locations, and services pages ![image](https://user-images.githubusercontent.com/48527022/115394566-e5674b00-a1b0-11eb-87f2-bdd1040de79d.png) | `'event'': 'int-accordion-expand', //OR 'int-accordion-collapse'`<br>`'accordion-parent-label' //populate with accordion parent label, or if only one label populate this variable only`<br>`'accordion-child-label': //only populate when the accordion has two labels, otherwise populate with undefined`<br>`'accordion-section-label': //header label above group of accordions'`
Clicks on links **within** accordions | `'event'': 'nav-accordion-link-click',`<br>`'accordion-parent-label' //populate with accordion parent label, or if only one label populate this variable only`<br>`'accordion-child-label': //only populate when the accordion has two labels, otherwise populate with undefined`<br>`'accordion-section-label': //header label above group of accordions'`
Scroll depth | _None_ | We will turn this on via GTM with no data layer changes necessary

**Comment by jonwehausen** [comment]
@mmiddaugh This is ready for your team to implement as you move through the build process. 

Shifting to standby on our team's board.

**Comment by mmiddaugh** [comment]
Thank you @jonwehausen and team

**Comment by jonwehausen** [comment]
@bsmartin-ep & @laurensimpson14 Please see workspace: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000515 for these events. 

We will need to change the logic on `Facility Telephone Click` when the page path for vet centers becomes available

**Comment by mmiddaugh** [comment]
Our implementation (#23889) is ready for validation when you are able @bsmartin-ep @laurensimpson14

**Comment by laurensimpson14** [comment]
@mmiddaugh I've QA'd and published all tracking for the Vet Center location pages (see notes below), however I was unable to find the "main page" to QA the other items. Do you have a URL to the main page that you could please send me? 

### QA
Page | Description of Interaction | Screenshot | QA - Status | 
-- | -- | -- | -- | 
**Main page** | Clicks on `Jumplinks` |  | **Needs QA** |  
**Main page** | Clicks on `Get directions` link from main page |  | **Needs QA** |  
**Main page** | Clicks on `View other locations` link |   | **Needs QA** |  
**Main page** | Opening/closing `Prepare for your visit` accordions |   | **Needs QA** | 
**Main page** | Opening/closing `Service`  accordions |   |  **Needs QA** | 
**Main page** | Clicks on phone numbers within `Service` accordions |  |  **Needs QA** | 
**Main page** | Clicks on any Spotlights `link` or `CTA ` |  |  **Needs QA** |  
**Main page** | Events on `How we're different than a clinic`accordions |   | **Needs QA**  | 
**Main page** | Clicks on main location phone number |   |  **Needs QA** |  
**Main page** | Scroll depth for main page | | **Needs QA** |  
**Locations page** | Clicks on `Get directions` link from Locations page | ![image](https://user-images.githubusercontent.com/80417436/119548783-92128a80-bd64-11eb-90ec-dbce04b080f5.png) ![image](https://user-images.githubusercontent.com/80417436/119548447-3811c500-bd64-11eb-84e2-1db1baca8f9e.png) | ✔️ Tracking Correctly | Add prefix to indicate the user clicked from the Locations page
**Locations page** | Scroll depth for Locations page | ![image](https://user-images.githubusercontent.com/80417436/119548875-ace4ff00-bd64-11eb-919a-521bfd102f13.png) ![image](https://user-images.githubusercontent.com/80417436/119548907-b2dae000-bd64-11eb-9115-49c96364d4ff.png) | ✔️ Tracking Correctly |  
**Locations page** | Clicks on Location phone numbers | ![image](https://user-images.githubusercontent.com/80417436/119549027-d1d97200-bd64-11eb-9085-f3262b04d827.png) ![image](https://user-images.githubusercontent.com/80417436/119549043-d56cf900-bd64-11eb-9f45-87decb7356e3.png) |  ✔️ Tracking Correctly | Add prefix to indicate the user clicked from the Locations page |

**Comment by laurensimpson14** [comment]
@mmiddaugh I wanted to follow-up to see if you have a URL to the main page for QA?

**Comment by mmiddaugh** [comment]
Hi @laurensimpson14 I think there's a disconnect here. The screenshots you've included are for detail pages on the Facility Locator. This request was related to new pages which will be implemented for Vet Centers. Based on the feedback we were given (and following the pattern used on VAMC pages, the Facilities team has already added the data layer. The pages are not yet available in Staging or Prod as they are built in CMS and not yet published.

**Comment by joanneesteban** [comment]
@mmiddaugh Hi! Checking in - is this in Staging or Prod yet?

**Comment by mmiddaugh** [comment]
Hi @joanneesteban we have two sites in Prod 🎉 
https://www.va.gov/nashville-vet-center/
https://www.va.gov/colorado-springs-vet-center/

**Comment by laurensimpson14** [comment]
@mmiddaugh Everything looks great! All of the data layer specifications are working correctly. I implemented a couple of tweaks in GTM on how we're pulling in the phone numbers and scroll depth. Once that is QA'd on our end and published, you'll be all set. 

### QA
Page | Description of Interaction | Screenshot | QA - Status | 
-- | -- | -- | -- | 
**Main page** | Clicks on `Jumplinks` | ![image](https://user-images.githubusercontent.com/80417436/127324830-bd0c89cb-c73d-4727-b889-fe55ccce3238.png) | ✔️ Tracking Correctly |  
**Main page** | Clicks on `Get directions` link from main page | ![image](https://user-images.githubusercontent.com/80417436/127325144-8cb58dcd-a337-43c2-a285-72b5d2ffa7b6.png) ![image](https://user-images.githubusercontent.com/80417436/127325055-44c060c8-c0ed-43b1-8f44-e78770b9c61d.png) | ✔️ Tracking Correctly |  
**Main page** | Clicks on `View other locations` link | ![image](https://user-images.githubusercontent.com/80417436/127325279-19e338b9-fb97-45f4-a831-54ea6b0b2d4f.png)  | 🟡 Is this the only link on the page that goes to the URL `https://www.va.gov/nashville-vet-center/locations`? If so, then this is tracking correctly. We track internal link clicks automatically using the `previous page` dimension in Google Analytics. |  
**Main page** | Opening/closing `Prepare for your visit` accordions | ![image](https://user-images.githubusercontent.com/80417436/127325757-823bf8f3-000c-4e02-b0db-0f37fa9ac41a.png)  | ✔️ Tracking Correctly | 
**Main page** | Opening/closing `Service`  accordions | ![image](https://user-images.githubusercontent.com/80417436/127325802-a17c0ad7-b1ed-4ff3-8960-14809c317bfe.png) |  ✔️ Tracking Correctly | 
**Main page** | Clicks on phone numbers within `Service` accordions | ![image](https://user-images.githubusercontent.com/80417436/127325934-1b59632d-f1bd-4419-9b6c-fedf373b1ab7.png)  | 🟡 This is tracking, however I've made a slight update in the GTM container | 
**Main page** | Clicks on any Spotlights `link` or `CTA ` | ![image](https://user-images.githubusercontent.com/80417436/127326101-4ab3c933-bd69-492b-aed6-d43dc021644f.png) | ✔️ Tracking Correctly - all outbound link clicks (such as the ones to blogs.va.gov) are automatically tracked |  
**Main page** | Events on How we're different than a clinic's accordions | ![image](https://user-images.githubusercontent.com/80417436/127326290-dadda74d-568f-496c-97b3-ead8a25e7c55.png) | ✔️ Tracking Correctly  | 
**Main page** | Clicks on main location phone number | ![image](https://user-images.githubusercontent.com/80417436/127326342-4192805e-c57c-4bec-bba1-c227d20b9dea.png)  | 🟡 This is tracking, however I've made a slight update in the GTM container | 
**Main page** | Scroll depth for main page | | 🟡 Not tracking - I've made an update in GTM to track this. @bsmartin-ep Could you please QA the two changes in the `20347 - Vet Centers Scroll Tracking` container [here](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000550)? |

**Comment by bsmartin-ep** [comment]
Interesting.  Don't think I was aware our global telephone click tracking puts them under "Outbound Links".

![image](https://user-images.githubusercontent.com/62304138/129220228-a441896b-b835-44e8-9908-d5b48e2b704d.png)

Interaction|Tag|Pass/Fail
---|---|---
Scroll Depth|![image](https://user-images.githubusercontent.com/62304138/129220629-be0d658e-0399-4ecd-8669-e658ad16763b.png)| :green_circle: Tracking correctly
Main phone number click|![image](https://user-images.githubusercontent.com/62304138/129220834-87fd66ac-7e72-4c4e-be3b-40c5daed2d81.png)|:green_circle: Tracking correctly
Services accordion phone number click|![image](https://user-images.githubusercontent.com/62304138/129221043-0292084a-b2e6-4815-bd2e-61d92bebbfb3.png)|:green_circle: Tracking correctly

LGTM @laurensimpson14.  Published.
