### ISSUE TITLE
Create S3 bucket for dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#20349]
The identity team requires the ability to search through vets-api logs for several purposes. Two of the most important are fraud waste and abuse investigations and troubleshooting SSOe issues. Cloudwatch and aws logs queries are too slow and inefficient. If we can have an AWS S3 bucket created for the dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log log group which goes back to the creation of the log group and is carried forward, then we can use Athena to create queries which are cheaper and faster.

Once the S3 bucket is created, the Identity team can attempt the Athena integration, pending permission validation.

If there is a location where a terraform file can be modified to create this S3 bucket, please let me know as I can go down that path if preferred. 

Sorry for the lack of template, Jesse, if there is another location or template please let me know.

**Comment by jhouse-solvd** [comment]
@joeniquette - Thanks for this. We will discuss as a team as we head into this next sprint. at first glance, it seems super straight forward, but will get some technical eyes on it and provide a refined ETA.

**Comment by jhouse-solvd** [comment]
@joeniquette - @jsev-io has some information that he is going to share here with you so that we can understand how we might address this need for you

**Comment by jsev-io** [comment]
Bucket and Access to related services created.

**Comment by jhouse-solvd** [comment]
@jsev-io / @joeniquette - Just following up here: What's next?

**Comment by joeniquette** [comment]
I believe we are all set here. Last test for me on this is running a successful sql command against the database I created in Athena. I think we can close this ticket though. Thank you for the teams help on this!!

**Comment by jhouse-solvd** [comment]
@joeniquette - glad to hear it! feel free to re-open or create a new one if anything more is needed. closing
