### ISSUE TITLE
Integration | delete cell phone

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20357]
## Acceptance Criteria
1. On the Cell phone edit page, selecting the "Confirm" large button will make a call to the relevant delete endpoint, so that the saved information is deleted from the user's profile
2. Selecting this button routes the user back to the Personal Information page
3. On the Personal Information page, the Cell phone ListItem should display the null state

## Designs
https://adhoc.invisionapp.com/d/main/#/console/20546460/442018170/preview#project_console

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/9/2021 - Looks good on iOS and Android.  Closing.
