### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#20350]
## User Email Address
ed.mangimelli@adhocteam.us

## Access Requirements
- [x] Google Analytics
- [ ] Domo

## Date Required
if possible this week, but it's not an emergency

## Product Team / External Team / VA Office
Claims & Appeals (previously Benefits & Memorials 1) / VSA

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by bsmartin-ep** [comment]
GA access has been granted to @edmangimelli.  You should receive an email.

The primary production va.gov property is _VA.gov - Production_ and the primary view is:

All VA.gov Website Data [Production]
https://analytics.google.com/analytics/eb/#/report-home/a50123418w177519031p176188361
