### ISSUE TITLE
Integration | delete home phone

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20355]
## Acceptance Criteria
1. On the Home phone edit page, selecting the "Confirm" large button will make a call to the relevant delete endpoint, so that the saved information is deleted from the user's profile
2. Selecting this button routes the user back to the Personal Information page
3. On the Personal Information page, the Home phone ListItem should display the null state: "Please add your home phone number"

## Designs
https://adhoc.invisionapp.com/d/main/#/console/20546460/442018170/preview#project_console
![Screen Shot 2021-02-23 at 5.28.19 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f6fe2e6f-a879-46ea-88cb-0b193d814e82)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/9/2021 - Looks good on iOS and Android.  Closing.
