### ISSUE TITLE
[OBE] Configure in pre-prod environment

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2035]
## User Story or Problem Statement
As the Backend Engineer on the Benefits and Memorials team, I need to complete a series of configuration tasks in the pre-production environment so I can establish the implementation and complete the integration with MVI.

## Goal
_Complete configuration in pre-prod environment_

## Tasks
- [ ] Configure in pre-prod environment

## Acceptance Criteria
- [ ] Completed pre-prod configuration

**Comment by SMLuthi** [comment]
MVI will by pass this testing step due us not having access to their pre-prod environment.
