### ISSUE TITLE
Integration | delete work phone

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20356]
## Acceptance Criteria
1. On the Work phone edit page, selecting the "Confirm" large button will make a call to the relevant delete endpoint, so that the saved information is deleted from the user's profile
2. Selecting this button routes the user back to the Personal Information page
3. On the Personal Information page, the Work phone ListItem should display the null state: "Please add your work phone number"

## Designs
https://adhoc.invisionapp.com/d/main/#/console/20546460/442018170/preview#project_console

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/9/2021 - Looks good on iOS and Android.
