### ISSUE TITLE
[Design] DD4edu - Kick off UAT recruiting

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20388]
## Background
We need to kick off the recruiting process for DD4edu UAT so that we can get Veterans scheduled and, in turn, ensure the work we have done so far meets their needs.

## Tasks
- [x] Initiate the recruiting process with Perigean

## Acceptance Criteria
- [x] Confirm recruiting has been kicked off

**Comment by sporeboy** [comment]
Incorporated feedback in convo guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/discovery-interviews/coe-discovery-convo-guide.md

Lauren review/research kick-off requested.

**Comment by jason-gcio** [comment]
Thanks @sporeboy - can you leave a comment here for an approximate time Perigean was engaged?

**Comment by Samara-Strauss** [comment]
Closing since recruiting has officially been kicked off with Perigean.
