### ISSUE TITLE
BE/PM |Profile: Follow up with VA Profile Re: "Address line too long" errors

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20397]
## Background
We are going to need to follow up with VA Profile on this. I'll try to summarize what is happening:

A user enters an address with an Address Line 1 length of less than 35 characters

We send that address to the validation API to check its validity

The validation API returns a single, confirmed, high-confidence address (and that suggested address has an Address Line 1 length greater than 35 characters)

We take the suggestion from the validation API and send it to the update endpoint

The request to update fails because the Address Line 1 is too long

In summary: As Lihan said, the address validation API can return addresses that are too long and violate VA Profile's rules. Worth noting: even if you bypassed the validation API and sent the address from item 1 directly to the update endpoint, the update would still fail because VA Profile runs that address through validation before saving anyway (they have done this for as long as I've been on this project).

### Possible solutions:

1. ~VA Profile totally drops this 35 character limit~ **From Samara**: We likely can't do this because of other systems that VA Profile connects to. Those character limits may originate in other systems. But, this needs to be confirmed.
2. ~VA Profile gives us some way to get around the 35 character limit~ **From Samara**: We likely can't do this because of other systems that VA Profile connects to. Those character limits may originate in other systems. But, this needs to be confirmed.
3. VA Profile adjusts the validation API to never return address lines that are longer than 35 characters and/or breaks long address lines into multiple lines/fields
4. ~We (and any other client that saves addresses with VA Profile) updates our logic to shorten addresses from the validation API if they have lines longer than 35 characters or break long address lines into multiple lines/fields~ UPDATE Monday, March 22, 2021: I'm realizing that this would not work without using an override key.
5. When address validation returns a single, confirmed, high-confidence address that has a line that's too long, ignore the suggestion and instead save the user-entered address along with the override key

## Tasks
- [ ] Get a meeting with VA Profile on the calendar
- [ ] Create an action plan for going forward

**Comment by mshea0606** [comment]
This can be discussed in the VA Profile meeting on Friday.

**Comment by Samara-Strauss** [comment]
Followed up again [in Slack](https://dsva.slack.com/archives/C7TE0PFTL/p1614785281026300). Awaiting response and plan for next steps.

**Comment by Samara-Strauss** [comment]
3.5.21 — Next steps: @lihanli will need to supply addresses to VA Profile over a secure channel.

**Comment by lihanli** [comment]
the va profile team knows about the address now, i sent it through teams

**Comment by Samara-Strauss** [comment]
Thank you @lihanli. We can follow up with them next week on this.

**Comment by Samara-Strauss** [comment]
Added blocked label since we can't do anything on this until VA Profile moves things forward.

**Comment by Samara-Strauss** [comment]
**From 3.19.21 VA Profile call**

Mike Richard says this issue has occurred once in the last six months according to their records. @erikphansen do we have any way of detecting whether this is actually happening more often than that? If we trust that metric and don't have any reason to believe this issue is occurring more often, they will likely de-prioritize this and fix it some time in the future.

**Comment by erikphansen** [comment]
I am pretty _our_ API is the one rejecting addresses that are too long.

1. User enters address that's <35 characters
2. We send that to address validation, which returns a single suggestion that's 36+ characters
3. The FE then sends that to our vets-api save endpoint
4. Our vets-api save endpoint rejects it because it's too long

Does that sound right to you, @lihanli?

In the past week, 3 people have gotten this error a total of 26 times. Looks like 1 person has tried 17 times :(

<img width="1092" alt="Screen Shot 2021-03-19 at 5 25 40 PM" src="https://user-images.githubusercontent.com/20728956/111853683-4f05e800-88d9-11eb-9c36-3f54be9dc416.png">

**Comment by Samara-Strauss** [comment]
@erikphansen thank you for doing this digging. Any thoughts on how to move forward?

**Comment by erikphansen** [comment]
Nothing new. I think that VA Profile should look into ways around this. The underlying issue is still that their address validation system is giving us addresses that they consider invalid.

We _can_ just move forward with item 5 in the original post above. And we might need to do that in the short term so these Veterans can update their address. But this seems like something VA Profile needs to resolve.

**Comment by lihanli** [comment]
yes vets-api will return an error if any of the address lines are over 35 characters

**Comment by Samara-Strauss** [comment]
Thanks for this. I let Mike Richard know [in Slack](https://dsva.slack.com/archives/C7TE0PFTL/p1616432283011700), though I don't know that this will up their priority level on addressing this. 

In terms of next steps, we have a couple options:

- Wait a little longer to see if VA Profile decides to fix this properly.
- Decide we want to move forward without VA Profile and implement solution 5.

My gut says to give this another week or two, but if they don't make any moves, we should move forward.

**Comment by Samara-Strauss** [comment]
Mike didn't have an update on this in this week's VA Profile meeting, but said to check back next week with him.

**Comment by Samara-Strauss** [comment]
4.30.21 Update — Rachel Fulton from VA Profile is looking into this, but no other updates beyond that.

**Comment by Samara-Strauss** [comment]
Update from today's VA Profile meeting: VA Profile is exploring an internal fix. They are thinking about changing the character limit, but this could affect downstream partners, so they have to figure out if this is a feasible solution or not.

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - was reviewing older tickets and came across this one. I know you won't be at the VA Profile meeting on 8/25 but I can ask about it or wait till the following meeting if you prefer.

+ @tpharrison since this looks to potentially impact BE

**Comment by Samara-Strauss** [comment]
Thank you for checking in about this. The last comment from me was literally my last work day before Lila was born, so I'm not surprised this got dropped out of nowhere 😆

**Comment by SKasimow** [comment]
Oh no! I bet you thought you had found all the "loose ends" at this point! LoL

**Comment by mtcA6** [comment]
mentioned this on a call with VA Profile (Karisa Strickland, Barry Wilbanks, Chante Lantosswett) on 6/26/2023 waiting to hear back about this.

**Comment by tpharrison** [comment]
@mtcA6 According to the VA Profile swagger docs, the `addressLine1` field has a maximum size of `100`.

I'll open a ticket to update the validation rule in vets-api to allow for this length.

**Comment by mtcA6** [comment]
@tpharrison even though VA Profile can accept 100 characters, is there a downstream requirement of fewer characters?

**Comment by tpharrison** [comment]
@mtcA6 I doubt it - VA Pro wouldn't be able to accept it if there was.  But I can verify against their QA environment when I work on the ticket.
