### ISSUE TITLE
[PM] DD4edu: Submit Privacy and Security Review request

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20395]
## Tasks
- [ ] Submit request for Privacy and Security Review

**Comment by Samara-Strauss** [comment]
Closing. This is already being tracked in the sensitive repo. Not sure why this duplicate ticket was created.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/228#issuecomment-789163252
