### ISSUE TITLE
[PM] DD4edu Determine Communications needs (GTM strategy)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20390]
## Background
We need to determine what/if any comms and marketing is needed.

## Tasks
- [ ] Meet with comms and determine appropriate next steps
- [ ] Implement comms suggestion

**Comment by MickinSahni** [comment]
Contact Center taking look at Product Guide, etc.: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19899#issuecomment-778407045

Need to determine next steps re: redirects from eBenefits (potentially work with Jason)

**Comment by mshea0606** [comment]
Next steps: Banner will be on Ebenefits page, @starlow00/@jason-gcio  to create/finalize content by end of this week. The time frame/design of this banner will be decided by Mike Walker # evss-dev. @Kimberley2019  will reach out to @clantosswett regarding what is needed (if anything) on the va.gov side and provide updates here to keep everyone in the loop. Also, Here is a link to the [Direct Deposit mock up](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/)

**Comment by Samara-Strauss** [comment]
Hi all, I am stepping in for now since Matt rolled off the team yesterday.

> Next steps: Banner will be on Ebenefits page, @starlow00/@jason-gcio to create/finalize content by end of this week. The time frame/design of this banner will be decided by Mike Walker # evss-dev.

eBenefits already has a banner they show to direct people to VA.gov for comp & pen, so we can just use that and have them adjust the language to accommodate both direct deposit for comp & pen and direct deposit for edu. 

<img width="933" alt="Screen Shot 2021-03-02 at 2 28 29 PM" src="https://user-images.githubusercontent.com/34068740/109703716-c874ab00-7b63-11eb-8859-3606ba01c9ac.png">

I'll be in touch with Melissa Rebstock and Joseph Preisser (who is replacing Luke Tickner) as we have a definite date for starting our phased launch.

> @Kimberley2019 will reach out to @clantosswett regarding what is needed on the va.gov side and provide updates here to keep everyone in the loop.

@Kimberley2019 @clantosswett do you all manage feature announcements on VA.gov? Or should we check in with public websites/the sitewide team about this?

**Comment by starlow00** [comment]
Contacted @clantosswett to verify information.

**Comment by Kimberley2019** [comment]
I have reached out to the Public Websites channel and was able to grab the attention of Brian Lloyd and he has looped in more assistance that will be able to help us maneuver though this process.

**Comment by Samara-Strauss** [comment]
I guess I'm wondering if we need to do much of anything at all if eBenefits is going to point users to VA.gov, but I can talk to @brianalloyd to see what our options might be.

**Comment by starlow00** [comment]
Hi @Samara-Strauss (cc @Kimberley2019) . I've attached a draft of banner language (4 tagline options plus a more info closer). Let me know what you think. If changes are needed for whatever reason, I'll be happy to assist. 
[Direct Deposit Banner Language ST 030421.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6087290/Direct.Deposit.Banner.Language.ST.030421.docx)

**Comment by Samara-Strauss** [comment]
- Which banner is this?
- Where does this banner display on the site?
- How long does the banner display?

**Comment by starlow00** [comment]
Hi @Samara-Strauss. To my knowledge, the copy I provided addresses the request for banner language that points out to the user/Veteran how they can now just click the Edit link to quickly go in and make changes to their direct deposit info without having to go to a different page and log in. I understood it to be something that would perhaps appear at the top of the page where the Edit links appear, as a text banner. Beyond that, I would need to defer to @mshea0606 or @Kimberley2019.

**Comment by Samara-Strauss** [comment]
@starlow00 Matt has rolled off the contract, and I think what was originally needed was probably misunderstood or miscommunicated. I apologize for that.

TBH, I don't think we need an additional banner on VA.gov for this for now. **The plan**: We'll rely on the eBenefits  banner to point users to the feature until we generally figure out how to better elevate direct deposit on VA.gov (a known issue). Closing this. No further action is needed from anyone.

**Comment by starlow00** [comment]
@Samara-Strauss Ok, thank you for the clarification.
