### ISSUE TITLE
Schedule VFS Team onboarding meeting dates

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#204]
# User Story
As a VFS team (including my VA Stakeholders), I need to have an onboarding meeting with the VSP team so I can get an understanding of the services, documentation, support that will be available to me as I work on VSP as well as what to expect of "reviews".

As the VSP team, I need to have an onboarding meeting with new VFS teams so I have awareness of what support to plan for.

# Goal
Include people, including stakeholders, from platform support team in initial new VFS team kickoffs.

# AC
- [ ] Full meeting scheduled w/appropriate people invited
- [ ] Eng breakout scheduled w/appropriate people invited
- [ ] ^ Approach documented in onboarding docs
- [ ] Capture/document contact information for VFS team members

# Definition of Done
- [ ] AC complete
- [ ] Shared w/DSVA for review

**Comment by rtluu** [comment]
@rroueche, quick q. Are there any more specifics about what team we're onboarding? I've heard whisperings about Insignia? Do we have a target date for that initial discussion or a sense of the individuals to include (and hopefully their emails)?
