### ISSUE TITLE
Evaluate results of schema.org improvements

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#2040]
Follow up to the work here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/1284

In the work behind the ticket above, our schema.org implementation was improved in five pages of the website. We should now use Google Analytics to determine if the schema.org improvements in those five pages has resulted in more users coming to the site.

This is difficult to measure, but this [suggestion](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1284#issuecomment-534554723) seems like our best method of measuring any change - 

> See if organic sessions increase to these as landing pages from date of publish onward. (We'd have to make sure to filter by organic vs. looking at all pageviews)

_Note: The schema.org changes were published on 9/24, but because search engines (Google) will need to process the changes to the page, we may have to wait at least a few days before the changes are visible on Google.com._

**Comment by kelsonic** [comment]
@Karak888 @ncksllvn For the following pages, what specific Google Search queries would we like to track (to see if the presentation of our *search engine results pages* improves with the recent PRs that update the schema.org implementation)?

- [] https://www.va.gov/disability/eligibility
- [] https://www.va.gov/disability/add-remove-dependent
- [] https://www.va.gov/discharge-upgrade-instructions 
- [] https://www.va.gov/education/eligibility
- [] https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit

**Comment by ncksllvn** [comment]
I think this ticket is semi-blocked right now because I'm not able to successfully pull up the FAQ Widget on Google.com for any one of these pages and it seems like we should check out the FAQ widgets rendering on Google.com ourselves before attempting to measure its success. 

When we are ready, I'm thinking we can check the amount of users that land on each one of those pages after an organic search, and compare last week's (before changes) with sometime later (after we can observe the FAQ widget ourselves.) 

- [/disability/eligibility](https://analytics.google.com/analytics/web/#/report/trafficsources-organic/a50123418w177519031p184624291/_u.date00=20190915&_u.date01=20190921&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.landingPagePath:~2Fdisability~2Feligibility~2Findex.html) - About 1,511 users
- [/education/eligibility](24291/_u.date00=20190915&_u.date01=20190921&explorer-segmentExplorer.segmentId=analytics.landingPagePath&explorer-table.plotKeys=%5B%5D&explorer-table.filter=~2Feducation~2Feligibility) - 854
- [/disability/add-remove-dependent](https://analytics.google.com/analytics/web/#/report/trafficsources-organic/a50123418w177519031p184624291/_u.date00=20190915&_u.date01=20190921&explorer-segmentExplorer.segmentId=analytics.landingPagePath&explorer-table.plotKeys=%5B%5D&explorer-table.filter=~2Fdisability~2Fadd-remove-dependent) - 807
- [/discharge-upgrade-instructions](https://analytics.google.com/analytics/web/#/report/trafficsources-organic/a50123418w177519031p184624291/_u.date00=20190915&_u.date01=20190921&explorer-segmentExplorer.segmentId=analytics.landingPagePath&explorer-table.plotKeys=%5B%5D&explorer-table.filter=~2Fdischarge-upgrade-instructions) - ~1,100 
- [/education/gi-bill/post-9-11/ch-33-benefit](https://analytics.google.com/analytics/web/#/report/trafficsources-organic/a50123418w177519031p184624291/_u.date00=20190915&_u.date01=20190921&explorer-segmentExplorer.segmentId=analytics.landingPagePath&explorer-table.plotKeys=%5B%5D&explorer-table.filter=~2Feducation~2Fgi-bill~2Fpost-9-11~2Fch-33-benefit) - ~9,000

**Comment by Karak888** [comment]
@kelsonic @ncksllvn are we at a point where we can get this pulled into ready to evaluate or Sprint 6 or still need more time?  Thanks!

**Comment by Karak888** [comment]
@kelsonic will take a look on original ticket and follow up with comparison screenshot.

**Comment by Karak888** [comment]
waiting on FAQs and these pages may have been moved to Drupal.  HTML could have been modified or previous version were ported (potential)- schema.org was implemented on some of this pages as a small experience.  Work has been eclipsed by drupal pages..  @Karak888 what is most effective way to implement schema.org on series of pages.  extremely difficult to evaluate google schema.org.

**Comment by kelsonic** [comment]
It looks like our schema.org implementation is not making its way to Google or, if it is, Google is straight up ignoring it and using their own Q&As on SERPs.

#### Search Engine Results:
![image](https://user-images.githubusercontent.com/12773166/71693025-a8333b80-2d68-11ea-98ce-a78fa265e948.png)

#### Our Code:
![image](https://user-images.githubusercontent.com/12773166/71693113-e16bab80-2d68-11ea-993f-aa8fef6de3b4.png)

Note the difference between our question and answers vs the ones Google is displaying. This leads me to believe that Google is ignorang our schema.org implementation in favor of creating their own Q&As.

### What does this mean?
I hypothesize this means that continuing work on schema.org-related tasks may actually be futile since it's in Google's hands to actually use our schema.org implementation. I propose we either 1) stop implementation work on schema.org items and/or 2) schedule a call with a Google specialist to see if they do actually still respect schema.org implementations (@Karak888 do you how to get in touch with our Google contact?).

I'll leave it up to @Karak888 for next steps on this ticket but for now I'll move it to Icebox 🙂

**Comment by kelsonic** [comment]
I totally forgot about this ticket. Hey @MickinSahni should we leave this in Icebox or close it you think?

**Comment by ncksllvn** [comment]
I personally don't think we're ever going to be able to do a true evaluation of schema.org's effectiveness, unless Google provides a specific tool or insights into it, or a Google rep personally helps us.

**Comment by kelsonic** [comment]
Agreed. Looks like that's what I was mentioning in my massive comment earlier too haha https://github.com/department-of-veterans-affairs/va.gov-team/issues/2040#issuecomment-570350468

**Comment by MickinSahni** [comment]
Closing this out. No prioritized problem to solve at the moment.
