### ISSUE TITLE
General Analytics Request for Mission Act Congress Report 

### ISSUE THREAD

**Issue by lalexanderson-dsva** [department-of-veterans-affairs/va.gov-team#20403]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?
Mission Act Report to Congress 
@lalexanderson-dsva  / @clantosswett  / @davidconlon / @johnhashva / @DanielleThierryUSDSVA 

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _Geri Young is coordinating the report to Congress on Mission Act. They need analytics from us on anything to do with Mission Act / community care._
    
- What type of analytics support are you looking for?
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_All metrics are needed by March 1, 2021._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
Calendar year 2020

## Analytics to Track Down
> Examples
> 
> - [ ] Unique visits to pages listed below
> - [ ] Top links clicked on pages listed below
> - [ ] Downloads if applicable.
> - [ ] Use of community care features on the facility locator (see @davidconlon team)
> - [ ] Community care requests submitted through VAOS 
> - [ ] 1010 CG applications submitted through va.gov. 

Sites/Pages/tools for report:
- https://missionact.va.gov/ 
- https://www.va.gov/health-care/eligibility/
- https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/ 
- any pages on www.va.gov/pittsburgh-health-care (@davidconlon )
- Welcome Kit downloads https://www.va.gov/welcome-kit/
- any other pages on va.gov related to mission act or community care (@DanielleSoCompany  may know more). 
- 
Applications for which community care usage data is needed
- 1010 CG: https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction (@mlighdc ) 
- VAOS: https://www.va.gov/health-care/schedule-view-va-appointments/appointments (@laurenernest ) 
- Facility Locator: https://www.va.gov/find-locations (@davidconlon ) 

## Which Product Questions are you trying to answer?
How did Veterans and caregivers use community care information? 
How did Veterans and caregivers use/access community care resources? 

## Other Helpful Questions to think through
- Who is your audience? Congress
- Why do you need this data? Because Mission Act must submit a report to Congress every year
- What are you hoping to find? n/a
- What is your hypothesis that you're hoping the data will support? Not really
- What area of the VA are you hoping to assess? Community Care
- How frequently do you need this data? Annually 

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Please coordinate with the folks named to get the data needed. Would love to submit this as a visual analytics report to Geri. I keep getting adhoc additions to this request, so will update this ticket if needed._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by laurenernest** [comment]
Here's the VAOS dashboard with that data (would be good to have Analytics team validate)
https://analytics.google.com/analytics/web/template?uid=tumrAEYPRZqNfW2LVj5hbA


[Analytics All VA.gov Website Data [Production] VAOS Key Data 3.0 20200101-20201231.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6037585/Analytics.All.VA.gov.Website.Data.Production.VAOS.Key.Data.3.0.20200101-20201231.pdf)

**Comment by joanneesteban** [comment]
@lalexanderson-dsva - do you know the product owner for missionact.va.gov? We don't believe we have data on this URL.

**Comment by mmiddaugh** [comment]
@davidconlon here are the Mission Act relevant stats for Facility Locator: 

<details>
<summary>Total 2020 Community care provider searches </summary>

2020 Total unique searches | 4,981,492
-- | --
2020 unique Community care provider searches | 250,407

</details>

<details>
<summary>2020 Top 5 Community care searches </summary>

Service type (search term) | Corresponding NUCC code | Unique searches
-- | -- | --
Clinic/Center: Urgent Care | 261QU0200X | 48,887
Clinic/Center: Primary Care | 261QP2300X | 31,266
Chiropractor | 111N00000X | 5,661
Optometrist | 152W00000X | 5,362
Nurse Practioner: Primary Care | 363LP2300X | 3,905


</details>





<details>
<summary> Top 5 Community Care specialty searches by month </summary>

Month | Total unique searches of any type | Service type (search term) | Corresponding NUCC code | Unique searches(% of total)
-- | -- | -- | -- | --
January 2020 | 411,041 | Clinic/Center: Urgent Care | 261QU0200X | 3676(.89%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 1,389(0.34%)
  |   | Chiropractor | 111N00000X | 677(0.16%)
  |   | Optometrist | 152W00000X | 395(0.10%)
  |   | Acupuncturist | 171100000X | 373(0.09%)
February 2020 | 347,441 | Clinic/Center: Urgent Care | 261QU0200X | 2,133(0.61%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 1,590(0.46%)
  |   | Chiropractor | 111N00000X | 514(0.15%)
  |   | Acupuncturist | 171100000X | 382(0.11%)
  |   | Optometrist | 152W00000X | 367(0.11%)
March 2020 | 412,853 | Clinic/Center: Urgent Care | 261QU0200X | 4,280(1.04%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 2,301(0.56%)
  |   | Chiropractor | 111N00000X | 477(0.12%)
  |   | Nurse Practitioner: Primary Care | 363LP2300X | 289(0.07%)
  |   | Dermatology | 207N00000X | 274(0.07%)
April 2020 | 365,271 | Clinic/Center: Urgent Care | 261QU0200X | 5,161(1.41%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 1,323(0.36%)
  |   | Pharmacy: Community/Retail Pharmacy | 3336C0003X | 432(0.12%)
  |   | Pharmacy | 333600000X | 269(0.07%)
  |   | Emergency Medicine | 207P00000X | 245(0.07%)
May 2020 | 365,251 | Clinic/Center: Urgent Care | 261QU0200X | 4,895(1.34%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 1,486(0.41%)
  |   | Pharmacy: Community/Retail Pharmacy | 3336C0003X | 382(0.10%)
  |   | Chiropractor | 111N00000X | 251(0.07%)
  |   | General Acute Care Hospital | 282N00000X | 218(0.06%)
June 2020 | 389,210 | Clinic/Center: Urgent Care | 261QU0200X | 4,103(1.05%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 1,143(0.29%)
  |   | Pharmacy: Community/Retail Pharmacy | 3336C0003X | 371(0.10%)
  |   | Emergency Medicine | 207P00000X | 249(0.06%)
  |   | Chiropractor | 111N00000X | 245(0.06%)
July 2020 | 420,904 | Clinic/Center: Urgent Care | 261QU0200X | 3,927(0.93%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 1,394(0.33%)
  |   | Pharmacy: Community/Retail Pharmacy | 3336C0003X | 357(0.08%)
  |   | Optometrist | 152W00000X | 320(0.08%)
  |   | Emergency Medicine | 207P00000X | 309(0.07%)
August 2020 | 388,915 | Clinic/Center: Urgent Care | 261QU0200X | 4,446(1.14%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 2,585(0.66%)
  |   | Pharmacy: Community/Retail Pharmacy | 3336C0003X | 565(0.15%)
  |   | Optometrist | 152W00000X | 492(0.13%)
  |   | Pharmacy | 333600000X | 393(0.10%)
September 2020 | 556,483 | Clinic/Center: Primary Care | 261QP2300X | 6,935(1.25%)
  |   | Clinic/Center: Urgent Care | 261QU0200X | 4,795(0.86%)
  |   | Nurse Practioner: Primary Care | 363LP2300X | 901(0.16%)
  |   | Chiropractor | 111N00000X | 758(0.14%)
  |   | Pharmacy: Community/Retail Pharmacy | 3336C0003X | 723(0.13%)
October 2020 | 483,343 | Clinic/Center: Primary Care | 261QP2300X | 4,609(0.95%)
  |   | Clinic/Center: Urgent Care | 261QU0200X | 4,422(0.91%)
  |   | Optometrist | 152W00000X | 677(0.14%)
  |   | Chiropractor | 111N00000X | 647(0.13%)
  |   | Dentist | 122300000X | 562(0.12%)
November 2020 | 407,522 | Clinic/Center: Primary Care | 261QP2300X | 3,428(0.84%)
  |   | Clinic/Center: Urgent Care | 261QU0200X | 3,364(0.83%)
  |   | Optometrist | 152W00000X | 745(0.18%)
  |   | Dentist | 122300000X | 585(0.14%)
  |   | Chiropractor | 111N00000X | 555(0.14%)
December 2020 | 433,258 | Clinic/Center: Urgent Care | 261QU0200X | 3,685(0.85%)
  |   | Clinic/Center: Primary Care | 261QP2300X | 3,083(0.71%)
  |   | Optometrist | 152W00000X | 998(0.23%)
  |   | Chiropractor | 111N00000X | 686(0.16%)
  |   | Dentist | 122300000X | 510(0.12%)

</details>


<details>
<summary> Urgent care searches by month </summary>
For April - July, the total community urgent care searches include the following

- Facility type = Urgent care + Service type = Community urgent care
- Facility type = Community care providers + Service type = Clinic/Center: Urgent Care (261QU0200X)

For August - December, the total community urgent care searches include the following </summary>

- Facility type = Urgent care + Service type = Community urgent care
- Facility type = Urgent care + Service type = All Urgent care
- Facility type = Community care providers + Service type = Clinic/Center: Urgent Care (261QU0200X)
- Facility type = Urgent care + Service type = All Urgent care

Month | Facility type | Service type | Unique searches
-- | -- | -- | --
April 2020 | Urgent care | Community urgent care | 21,377
  | VA health | UrgentCare | 1,606
  | Urgent care | VA urgent care | 133
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 5,161
  | Urgent care searches of any kind |   | 28,277
  | Community urgent care searches |   | 26,538
  | Urgent care benefit clickthrough |   | 2,929
  |   |   |  
May 2020 | Urgent care | Community urgent care | 24,027
  | VA health | UrgentCare | 1,574
  | Urgent care | VA urgent care | 141
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 4,895
  | Urgent care searches of any kind |   | 30,637
  | Community urgent care searches |   | 28,922
  | Urgent care benefit clickthrough |   | 2,622
  |   |   |  
June 2020 | Urgent care | Community urgent care | 28,845
  | VA health | UrgentCare | 1,511
  | Urgent care | VA urgent care | 219
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 4,103
  | Urgent care searches of any kind |   | 34, 678
  | Community urgent care searches |   | 32,948
  | Urgent care benefit clickthrough |   | 2,759
  |   |   |  
July 2020 | Urgent care | Community urgent care | 32,358
  | VA health | UrgentCare | 1,504
  | Urgent care | VA urgent care | 224
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 3,927
  | Urgent care searches of any kind |   | 38,013
  | Community urgent care searches |   | 36,285
  | Urgent care benefit clickthrough |   | 3,356
  |   |   |  
August 2020 | Urgent care | Community urgent care | 29,128
  | Urgent care | UrgentCare | 1,169
  | VA health | VA urgent care | 878
  | Urgent care | VA + Community care* | 142
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 4,446
  | Urgent care searches of any kind |   | 35,763
  | Community urgent care searches |   | 33,716
  | Urgent care benefit clickthrough |   | 1,970
  |   |   |  
September 2020 | Urgent care | Community urgent care | 29,459
  | Urgent care | VA urgent care | 3,220
  | VA health | UrgentCare | 701
  | Urgent care | VA + Community care | 524
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 4,795
  | Urgent care searches of any kind |   | 38,699
  | Community urgent care searches |   | 34,778
  |   |   |  
October 2020 | Urgent care | Community urgent care | 26,305
  | Urgent care | VA urgent care | 2,493
  | VA health | UrgentCare | 651
  | Urgent care | VA + Community care | 495
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 4,422
  | Urgent care searches of any kind |   | 34, 266
  | Community urgent care searches |   | 31,222
  |   |   |  
November 2020 | Urgent care | Community urgent care | 22,666
  | Urgent care | VA urgent care | 2,056
  | VA health | UrgentCare | 602
  | Urgent care | VA + Community care | 397
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 3,364
  | Urgent care searches of any kind |   | 29,085
  | Community urgent care searches |   | 26,427
  |   |   |  
December 2020 | Urgent care | Community urgent care | 24,077
  | Urgent care | VA urgent care | 2,107
  | VA health | UrgentCare | 664
  | Urgent care | VA + Community care | 486
  | Community care providers | Clinic/Center: Urgent Care (261QU0200X) | 3,685
  | Urgent care searches of any kind |   | 31,019
  | Community urgent care searches |   | 28,248

</details>

<details>
<summary> Community urgent care and Community pharmacy care pharmacy searches by month (Sept - Dec 2020) </summary>

  | Community urgent care searches | Total Community care pharmacy searches | Facility type = Pharmacy | Community care providers + Pharmacy: Community/Retail Pharmacy (3336C0003X) | Community care providers + Pharmacy (3336C0002X) | Community care providers + Compounding pharmacy (3336C0004X) | Community care providers + Speciality pharmacy (3336S0011X) | Community care providers + MCO pharmacy (3336M0003X) | Community care providers + Mail order pharmacy (3336M0002X)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
September 2020 | 38,699 | 797 | 45 | 723 | 25 | 1 | 2 | 1 |  
October 2020 | 31,222 | 368 | 66 | 277 | 21 | 1 | 3 |   |  
November 2020 | 26,427 | 189 | 58 | 123 | 7 |   | 1 |   |  
December 2020 | 28,218 | 184 | 60 | 116 | 7 |   |   |   | 1

</details>
 
Note: our method for tracking clicks on the urgent care benefit button changed with the mash-up release in August so I need to gather them separately. I'll update this data when available.

**Comment by mlighdc** [comment]
@joanneesteban is the analytics team able to help pull the data for both health enrollment and the Caregiver pages? I can get the number of applications sent to the Caregiver backend system and compare it with the numbers you have. Thank you!

**Comment by bsmartin-ep** [comment]
@lalexanderson-dsva / @DanielleThierryUSDSVA -

Can I get some clarification on "Unique visits to pages"?

In GA, a "unique pageview" would be counting a user's pageview to a particular page **only once per session**.  

Are you looking to count every pageview to these pages no matter how many times it is visited in a session?

**Comment by joanneesteban** [comment]
Thanks, @mlighdc ! Appreciate it! We should have those numbers. For `health enrollment`, I'm assuming you're referring to the Health care application (HCA)?

**Comment by mlighdc** [comment]
Yes @joanneesteban - 10-10EZ (HCA)!

**Comment by joanneesteban** [comment]
@mlighdc thank you!!

**Comment by joanneesteban** [comment]
@lalexanderson-dsva - a head's up that we won't be able to get granular data (like links clicked) on the missionact.va.gov specific pages since that isn't on our modernized Google Analytics, and DAP isn't retrieving detailed events.

**Comment by mlighdc** [comment]
@lalexanderson-dsva from a CARMA perspective below are the numbers for the calendar year 2020. This number is different than what Joanne would be able to see from GA because (1) GA does not capture all interactions due to some veterans opt-out; (2) there is a time zone difference between what is being used by logs (UTC) and CARMA (Easter time); and (3) from a CARMA standpoint, the numbers below is what has been successfully received by CARMA. Applications that have some form of data error on VA.gov will not be submitted to CARMA (e.g. MPI match).

Since the 10-10CG became available on VA.gov on October 1, 2020 and through December 31, 2020, there has been approximately 23,817 applications successfully submit online for the Program of Comprehensive Assistance for Family Caregivers. Online submissions accounted for 62% of all applications submitted for the time period (October 1 – December 21, 2020).

**Comment by joanneesteban** [comment]
@mlighdc just saw your message. We have this chart for Caregivers. Like you said, it doesn't align with CARMA's numbers (1374 difference). 

![image](https://user-images.githubusercontent.com/48964695/109557244-d4019c80-7aa5-11eb-8dbb-6a171dbf3e5c.png)


@lalexanderson-dsva Our team has been working on this report for the last few days and would like to close this out; please let us know if we'll need to fix this discrepancy, or if you would like [the report](https://va-gov.domo.com/page/465824186) as is.

**Comment by lalexanderson-dsva** [comment]
@mlighdc @joanneesteban - this is great. I'll note the CARMA difference when i submit the report.

**Comment by lalexanderson-dsva** [comment]
You can close this.
