### ISSUE TITLE
Investigate Most Frequent Form 526 Stopping Point

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#20410]
Investigate Most Frequent Form 526 Stopping Point _that isn't currently being tackled by another ticket_.
Stopping point being: *for unsubmitted forms*, the page/point where the Veteran stops filling out the form.

1. Crunch the Form526 save-in-progress data to get a list of where Veterans are stopping in the form
2. For each stopping point, tally up how many Veterans stopped there. Sort the list by this number.
3. Go down the list  to find the most common stopping point **that isn't currently being tackled.** Communicate the stopping points to research so they can investigate.

## Acceptance Criteria
- [ ] Tackle the next biggest Form526 stopping point (see instructions above). If investigating this is a big enough lift, feel free to split this into two tickets: research and implementation.

**Comment by annaswims** [comment]
The data has been posted to [Where and Why Did Veterans Stop In the Form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering/Where%20and%20Why%20Did%20Veterans%20Stop%20In%20the%20Form/README.md)

We'll use it in planning in our usability study.  Also, we're reviewing the data as a team on Wednesday.

**Comment by annaswims** [comment]
**review-veteran-details/military-service-history/reserves-national-guard - 743, ** already have a design ticked to explore combining with military service history
** supporting-evidence/private-medical-records-upload - 872,** seems logical, may take time to gather docs.
 **supporting-evidence/evidence-types - 953,**
 **review-veteran-details/military-service-history - 1118, ** take not at usability study, this shouldn't be that hard, is it that this is an eligibility gate?**
 **review-and-submit - 1161,** these are likely all validation and submission errors, we have good, actionable data on this. 
  **veteran-information - 1181,  ** is there a usability issue?
  **new-disabilities/follow-up/0 - 1343, ** is there a usability issue?
  **supporting-evidence/additional-evidence - 1345, **  seems logical, may take time to gather docs.
  **supporting-evidence/va-medical-records - 1481, **  seems logical, may take time to gather docs.
  **new-disabilities/add - 2026**.  is there a usability issue?

**Comment by annaswims** [comment]
follow-up usability study https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/26719
