### ISSUE TITLE
STEM AD: Load test endpoint

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20411]
## Value Statement
As a member of the development team, I need to ensure that the new automated denial endpoint is performant so that when the new automated denial functionality is live it does not have a negative impact on the claims tool. 

## Assumptions: 
1. None

## Acceptance Criteria: 
1. Load testing has been completed against the 'stem_claim_status' endpoint (http://localhost:3000/v0/education_benefits_claims/stem_claim_status) on staging. 
2. Load testing results have been captured on GitHub and linked in the comments of this story

## Supporting Artifacts: 
1. Example for load testing: https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest/education_benefits_claim_10203_stem
2. https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest#load-testing

**Comment by dmccurdybah** [comment]
devops branch: `stem-ad-load-test`

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/devops/issues/8708
