### ISSUE TITLE
Compose a Message form (UI)

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#20426]
## User story
As a Veteran, I want to compose a new message so that I can communicate a new question or need to my healthcare team.

## Acceptance Criteria
1.  Create UX/UI for the form on the "Compose Message" page using the form wrapper component
2. Recipient section:
     - Marked as "Required"
     - Pull in dropdown field CC.
     - _Note: the dropdown options will be service-driven and are not included in this ticket_
     - Default option: empty row that acts as a placeholder
3. Subject section:
     - Marked as "Required" 
     - Pull in dropdown field CC (note - departure from designs
     - Dropdown options: General, COVID, Appointment, Medication, Test, Education
     - Default option: empty row that acts as a placeholder
4. Subject line section:
     - Mark as "Required", but only when "General" is the selected subject 
     - Pull in input field CC
     - Include helper text
     - Restrict input field to max 50 characters
5. Attachments section:
     - Pull in Form Attachments CC #22610
     - Label for FAQ link: "How to attach a file" (routing not needed for this story)
     - Large button: "Add files"
6. Message section:
     - Marked as "Required"
     - Pull in text box CC
7. At the bottom of the screen, create 2 large buttons:
     - Primary: "Send" (routing not needed for this story)
     - Secondary: "Cancel" (routing not needed for this story)
8. In the nav bar header, replace the "Back" button with a "Cancel" button
     - _Note: this may be a departure from the designs linked below, but "Cancel" is what we're using on the Profile forms & the Claims Upload flow_

**Not included in this story**: 
- Field errors #22667

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364867

### Form fields
**Inactive state(empty):**
Formfield: “{label}, empty."
Formfield/Message: “{label, Hint message}, empty. "
Dropdown: “{label}, empty."
Dropdown/Message “{label, Hint message}, empty. "

**Focused state(editing):**
Formfield: “{label}. Editing - {Input text}. "
Formfield/Message:“{label, hint message}. Editing - {Input text}. "
Dropdown: “{label}. Editing - {Input text}."
Dropdown/Message “{label, hint message}. Editing - {Input text}. "

**Activated state:**
Formfield: “{label}. Filled - {Input text}. ”
Formfield/Message:“{label, hint message}. Filled - {Input text}. ”
Dropdown:“{label}. Filled - {Input text}. ”
Dropdown/Message “{label,hint message}. Filled - {Input text}. ”

### Large buttons
**Add files**
- accessibilityLabel = "add files"
- accessibilityRole= "button"
- accessibilityHint= "add files to this message"

**Send**
- accessibilityLabel = "send"
- accessibilityRole= "button"
- accessibilityHint= "send this message"

**Cancel**
- accessibilityLabel = "cancel"
- accessibilityRole= "button"
- accessibilityHint= "cancel this message and return to the previous page"

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/14/2021 - Looks good on iOS and Android.  Closing.
