### ISSUE TITLE
Determining title casing for Aid and Attendance and Housebound allowance

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#2042]
## User Story or Problem Statement
As a content team member, I need to know proper casing for terms used on VA.gov so I can maintain consistency across all benefit hubs.

## Goal
Determine if the term Aid and Attendance and Housebound allowance is a proper name that should be capped in all instances on the website. Currently we have it written different ways.

## Objectives or Key Results this is meant to further
Maintaining consistency across all hubs and pages on VA.gov and ensuring that the style guide is the single source of truth.

## Acceptance Criteria
- [ ]  Jen to discuss the term and casing with Misty Sweet
- [ ] Once proper capitalization is determined, Randi will update all affected pages so it is consistent across all hubs. She will also make sure style guide is updated with correct capitalization.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Karak888** [comment]
@RLHecht just trying to get things ready for end of/ beginning of next sprint- is it safe to assume that these will not go out by EOD tomorrow ?  I know you are waiting on approvals, etc. just more of a gut check?  thank you!!!

**Comment by jenniferlee-dsva** [comment]
@Karak888 - Sorry, this is blocked because of me. I'll unassign @RLHecht for now, so it's only showing up for me. I've had dozens of things with VBA to check in on, and this one keeps dropping lower.

**Comment by Karak888** [comment]
@jenniferlee-dsva needs to get in touch with Misty Sweet.

**Comment by FranECross** [comment]
@RLHecht I'm going through our backlog and ran across this older ticket. Do you know if it's still needed? Is it correct that this ticket (and its Epic) should still live with Public Websites? Thanks! cc @jilladams

**Comment by RLHecht** [comment]
@FranECross wow, this is a super old one! This is back when the content team was part of Public Websites. We can move it to the CAIA backlog but there's nothing for your team to do on this. Thanks for flagging!

**Comment by megzehn** [comment]
@bethpotts suggested leaving this as is for now: Aid and Attendance and Housebound allowance

We can close this ticket. Thanks!
