### ISSUE TITLE
Integration Testing to support upcoming MPI change

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#20422]
We currently have a request to implement some form of integration testing to support an upcoming MPI change that adds a `personalRelationship` tag to include information about an associated user. Since there are changes on the `vets-api` end as well as `MPI`, we're requesting some kind of accommodation with integration testing.

The following describes our particular use case:
- We are adding the ability to sign in with a User that is not a Veteran, but who is associated to one, and perform various actions as an associated User.
- Our MVP will be to allow the ability to download a Dependent Benefits Letter
- Our need from MPI in this case, is to query MPI for the non-Veteran User, get back that user's information, and enough of the associated Veteran's information to request a benefits letter download.

According to the MPI Service documentation, a `personalRelationship` tag has been added that includes the information we potentially need, which can be retrieved by setting `<modifyCode code="MVI.COMP1.AMS"/>` instead of `<modifyCode code="MVI.COMP2"/>`. 
The problem we ran into, however, is that we don't currently have any mock data that includes relationship associated information (and the mock data doesn't check for `modifyCode` changes currently, it will return a user as if you had set `<modifyCode code="MVI.COMP2"/>`, regardless of what you actually set the tag to).
We don't have any real integration testing accommodations to turn to when we are not able to leverage mocking, but we were able to SSH into a staging instance and attempt to query with the changed tag. When we did this, instead of getting back a user with filled out (or empty) `personalRelationship` information, we get an MPI Response error. 
We identified the need to do this manual testing on Staging as a potentially dangerous practice, as if we had implemented a feature due to the current MPI Service doc specification, we could have potentially introduced an error that would have prevented MPI queries in general, effectively bringing down the site until the change was reverted

**Comment by bosawt** [comment]
Action Items/Deliverables:
- Some mechanism to run programmatic tests against live test stacks for external services
- Confirmation that we're able to call the MPI Service on the Staging stack through this mechanism, and are able to retrieve the response (It probably would make sense for my team to write the actual tests beyond the confirmation that MPI is callable)

This is intentionally a little vague, as ultimately it'd be cool if this was a blueprint for other integration testing. So we're definitely willing to work with you and/or compromise to come up with a solution that is beneficial to the future of integrations in general. Here are two ways I've seen this done:
- One system I worked on was Rails focused, so the integration tests were written in RSpec, and tagged with `integration`. These tests were not actually run locally, or as part of a PR merge. They were only run as part of the deploy process (although if they failed the deploy was stopped until they were fixed). The advantage of this solution is that the tests are easily written and maintained, as they are quite similar to other RSpec tests. The disadvantage of this solution was that the nature of integration tests are somewhat flaky, and holding up a weekly deploy meant there were many times when the engineering team was forced to drop everything immediately to basically confirm that the integration tests just needed to be retried as an external service was being flaky. Perhaps we could offset this by adding the integration tests as part of the Jenkins PR process. As for an example of what this may look like, consider this file in the `vets-api` repo: `spec/lib/mpi/service_spec.rb`. This file makes mocked calls out to MPI, but instead of hitting the service, it uses a service called `VCR` that retrieves mocked responses and serves it up for these tests. An integration test suite in RSpec would look like this, but without the `VCR` mocks, it'd be actual calls to the service.
- Another implementation I've seen was on a system that was full of different services in different languages, not just Rails. We had the relevant routes in `Postman`, and set up routes in there with a set of tests. You can even chain `Postman` curl calls together, so you could set up an authorization `Postman Collection` that authorizes a user, and then hits MPI and runs tests on the curl response. The advantage of this setup is that the test writing become documentation as well, making it quite easy to see exactly how these calls are supposed to be made (in `Postman`, you can easily see the headers passed, the parameters, etc). The disadvantage is that it's a bit harder to get this in a place we can commit the changes, and I don't think it's feasible to have a VA-wide `Postman` account that is synced between all users. I also am not sure how to get this into something like Jenkins, although it very well may be possible.

Our ultimate solution could definitely be something other than these options, but I'm just trying to describe the context and scope of what the ask here is. Please lemme know if you have any other questions!

**Comment by rjohnson2011** [comment]
In the process of coordinating with Operations team how to best trigger GitHub Actions inside the staging security perimeter.

**Comment by rjohnson2011** [comment]
To invoke Github Actions inside the staging security perimeter we were directed towards the `notifications-api` repo by Ops team - https://dsva.slack.com/archives/CJYRZK2HH/p1616448430055900?thread_ts=1616173359.044200&cid=CJYRZK2HH. 
This can be done via `aws ssm run-command` in a repo set up with proper AWS credentials.

Our current course of action is creating a private `testing-tools-team` repo with AWS credentials set up for a self-hosted running on Github Actions, per a discussion with @pjhill @dginther  - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22290 

Ops team is helping create this repo - https://dsva.slack.com/archives/CJYRZK2HH/p1617030519111700. Once that is done, Testing Tools Team is ready to push GA scripts and test MPI request operability.

**Comment by rjohnson2011** [comment]
@dginther @JoeTice @pjhill An internal repo for `testing-tools` is created and available to both Testing Tools and Operations teams as admins.
https://github.com/department-of-veterans-affairs/testing-tools

Awaiting AWS credentials for self hosted runner on Github Actions to test the MPI responses.

**Comment by jhouse-solvd** [comment]
When I spoke w/ @dginther, he was working on getting the credentials for the service account created and added to the repo. The next bit of work will be to set up the self-hosted runner for GitHub actions.

**Comment by rjohnson2011** [comment]
Checking in to see if there's an ETA on the self-hosted runner setup. Trying to plan out the next sprint.

**Comment by jhouse-solvd** [comment]
@rjohnson2011 - Please see the attached blocker ticket blocker and see if you can access the runner / provide feedback if needed?

**Comment by rjohnson2011** [comment]
Thanks! I will test this and let you know if I run into any blockers regarding permissions.

**Comment by rjohnson2011** [comment]
The MPI request is now returning a successful response (see ticket https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/23862). Big thanks to @dginther for his work unblocking this!

Github Actions to MPI can be invoked here: https://github.com/department-of-veterans-affairs/testing-tools/runs/2688247656?check_suite_focus=true

![image.png](https://images.zenhubusercontent.com/5fb40598d06a06671e842a63/20318850-80
70-4596-bbbe-706ded0c0d82)

@bosawt I believe this is the extent required to satisfy this ticket. Please take a look and let me know if anything else is required or if we can close.

**Comment by bosawt** [comment]
Awesome! I looked and confirmed that it matches a staging WSDL (just wanted to prove it wasn't a mocked response). This is great, thanks for doing this! @rjohnson2011 

I think my only remaining question, with regards to extending the testing for the MPI service. Is there a recommended approach for adding new tests? For example, if it's possible to hook this up with the `vets-api` repo, we could include a set of `RSpec` tests defined as `integration tests` that only get run in an `integration` context (and not through the normal test suite). 
Otherwise, we could set up a test wrapper for MPI curl commands in this repo, and keep it all within this.

Does one of those options make more sense than the other?

**Comment by rjohnson2011** [comment]
@bosawt Discussed the two approaches with the Testing Tools team. We're inclined to leverage the successful MPI curl call in the testing-tools repo and go for the test wrapper method. Everything should be set up in the repo to get that working quickly. Our primary concern with the other approach is potential blockers involving the `vets-api` hook up that might delay progress. 

If you're interested in a brainstorm involving what the test wrapper would look like @pjhill and I are happy to chat further.
