### ISSUE TITLE
Update Type of Care List

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2043]
The type of care options for veterans need to be updated to clarify the sleep medicine options for veterans (based on feedback) and to remove express care since MVP will not handle these.

Sleep medicine option should show a follow up page (like what we do with audiology) 

## AC
- [ ] Type of Care page does not include Express Care
- [ ] Type of Care page includes 'Sleep Medicine' option
- [ ] Type of Care page does not include CPAP or home sleep study options
- [ ] If 'Sleep Medicine' option chosen, veteran gets follow up page that asks them to choose between CPAP and home sleep study options
- [ ] Veteran does not get sleep medicine follow-up page if they don't select 'sleep medicine' from the type of care list
- [ ] '(including hearing aid support)' is next to audiology option (not in bold)
- [ ] Subbheaders gone for mental health & specialty care
- [ ] 'Outpatient mental health' just reads 'Mental health'

![Type of care - DS](https://user-images.githubusercontent.com/24251447/65991529-1e1ac480-e453-11e9-8979-264f758175e4.png)

**Comment by markgreenburg** [comment]
@rtwell do we have some content to put into the sleep medicine follow up page? Kind of like the helper content we have for audiology?

**Comment by rtwell** [comment]
i would get that from @peggygannon and @lalexanderson-dsva

**Comment by markgreenburg** [comment]
@vbahinwillit here are two other tweaks based on new designs:

- Put '(including hearing aid support)' next to audiology option (not in bold)
- Remove subbheaders for mental health & specialty care
