### ISSUE TITLE
[PM] Onboarding: AJ Jakabcin

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20439]
## Background

Welcome, AJ! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to team members

Please schedule a short chat with each of these folks (internal mtgs can come from Ad Hoc account):

- [x] Erik Hansen
- [x] Sandra Hallie
- [x] Lihan Li
- [x] Tressa Furner
- [x] Liz Lantz

### Meetings with Samara

- [x] Project overview call (we can have more than one of these if necessary)
- [x] PO/PM roles and responsibilities call 

### Onboarding to ceremonies

- [x] Observe standup and be ready to run after 1 - 2 standups
- [x] Observe sprint planning and then be ready to manage the next sprint planning session
- [x] Observe grooming and then be ready to manage the next grooming session
- [x] Observe Team of Teams and then be ready to give the update in the next meeting

### Products/Projects

You'll talk about these more formally in your meeting(s) with Samara, but here are some helpful resources to review in the meantime:

**My VA 2.0 redesign**

[My VA folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va)

- [x] [My VA 2.0 project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/README.md)
- [x] [My VA 2.0 Zenhub tickets](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/board?labels=my-va-dashboard&repos=133843125)
- [x] [My VA staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)

**Direct deposit**

*Current project*: Direct deposit for edu

[Direct deposit for edu folder]()

- [x] [Direct deposit for edu project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/README.md)
- [x] [Direct deposit for edu Zenhub tickets](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/board?labels=direct%20deposit&repos=133843125)

*Past project/current product*: Direct deposit for compensation & pension

[Direct deposit for comp & pen folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit)

- [x] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [x] [Direct deposit staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-direct-deposit.md)

**Communications preferences** (aka Notification preferences)

- [x] [Communications preferences project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
- [x] [MVP documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/communications-permissions-mvp-definition.md)
- [x] [Communications preferences Zenhub tickets](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/board?labels=notifications-settings&repos=133843125)

**Preferred medical facility**

- [x] [Preferred medical facility project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/README.md)
- [x] [Preferred medical facility Zenhub tickets](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/board?labels=preferred-facility&repos=133843125)

**Profile**

- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [Profile folder and list of products](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile)

**Comment by ajakabcin** [comment]
Completed documented onboarding tasks!
