### ISSUE TITLE
Change text on Correspondence Training page per stakeholder request

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#2044]
## User Story or Problem Statement
Per a stakeholder request, text to the correspondence training page needs to be updated.

## Goal
In the intro of this page: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/correspondence-training/, change the text from "Correspondence training (coursework completed by mail)" to "Correspondence training (coursework completed by mail, online, or some other device)"

## Objectives or Key Results this is meant to further
Stakeholder request

## Acceptance Criteria
- [x] Page updated in Drupal by Randi
- [x] Page reviewed in Drupal by Peggy

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@peggygannon I've made this change. Please review and publish. @KevinMHoffmanUSDS FYI

**Comment by KevinMHoffmanUSDS** [comment]
@RLHecht Thank you!

**Comment by Karak888** [comment]
@peggygannon can you please review this and let @RLHecht know when it is good to go live?

**Comment by peggygannon** [comment]
@RLHecht @Karak888 looks good. this update has been published.

**Comment by KevinMHoffmanUSDS** [comment]
@peggygannon @Karak888 @RLHecht Thanks, y'all!

**Comment by RLHecht** [comment]
Change was validated on live site. Closing issue.
