### ISSUE TITLE
[VTK] - Bootstrap/Setup Command

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#20450]
## User Stories

As a user of VTK, I want to be able to use one command on my computer that will download and install all the dependencies I would need to run vets-api or vets-website locally. 

## Acceptance Criteria
- [ ] VTK installs all dependencies needed to run either vets-api or vets-website (including software, repo's, etc)
- [ ] If the tool already exists on my system it should skip that step
- [ ] messages should be displayed to user if there was an error that caused it to fail and direction on how to fix and what to do next

**Comment by ericboehs** [comment]
I wrote this when I onboarded: https://gist.github.com/ericboehs/55cadc4483637f6a98a8104409dc2717. Should be useful.
