### ISSUE TITLE
Cancel VA appointments

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20457]
## User story
As a user, I want the ability to cancel my VA appointment directly from the mobile app.

## Acceptance Criteria
1. For upcoming VA Appointments, (i.e. in-person appointments), update the **Need to cancel?** ListItem for all appointments that have not been canceled. 
2. UI elements for the Cancel card:
    - Update header: "Cancel this appointment"
    - Description: "If you want to reschedule..."
     - Large button (UI only - routing is handled in a separate story): "Cancel appointment"

## Designs
https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/443191227

## UX ticket
#18915
          
## Accessibility Implementation Guidelines

- Mark "Cancel this appointment" as Header 3

**Cancel button**
- Title= Cancel appointment
- accessibilityHint= “Cancel this appointment" 
- accessibilityRole= “button"

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS - 3/4/2021 - Two bugs logged, however. 1) Cancel appointment button had capitalized 'A', but shouldn't. 2) Accessibility, the Cancel button is missing the hint.
