### ISSUE TITLE
Confirmation screen for appointment cancelation

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20459]
## User story
As a user, I want to see a confirmation page after I've hit "Cancel appointment" that gives me options to: confirm the cancelation, or go back to the appointment detail screen without canceling. 

## Acceptance Criteria
1. Upon hitting "Cancel appointment" on the VA appointment detail page, route the user to a new page where they can confirm that they want to cancel the appointment
     - Header 1: Appointment
     - No Back or Cancel buttons in the header
     - Copy (Mobile Body): "Do you want to cancel your appointment?"
     - Large Button CC (primary action): "Yes, cancel this appointment" (UI only - routing is covered in a separate story)
     - Large Button CC (secondary action): "No, take me back"
2. Selecting "No, take me back" returns the user to the previous page

## Designs
None - use the File Upload confirmation screen as a reference (#19086):
![Screen Shot 2021-02-24 at 4.23.17 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f35a8fbe-6633-4d32-8722-8bda00fb1703)

## Accessibility Implementation Guidelines 

**Yes, cancel this appointment button**
- accessibilityLabel= “Yes, cancel this appointment”
- accessibilityHint= "Cancel this appointment"
- accessibilityRole= “button”

**No, take me back button**
- accessibilityLabel= "No, take me back”
- accessibilityHint= "Go back to the previous page"
- accessibilityRole= “button”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Confirmation UX/UI on va.gov web app:

![Screen Shot 2021-02-24 at 5.25.11 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/a5008623-d343-4f80-95fa-74e4d52c7ac8)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/9/2021 - Looks good on iOS and Android.  Closing.
