### ISSUE TITLE
General Analytics Request for VAOS-validate usage report

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#20458]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Lauren Ernest for OVAC

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - VAOS
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

## Analytics to Track Down

- [ ] Appointment flow starts
- [ ] Time of day usage

## Which Product Questions are you trying to answer?
_Questions from the business_
- What is the peak time for VAOS usage?
- What times of day should VAMF deployments happen/avoid?

## Other Helpful Questions to think through
- Who is your audience? OVAC
- Why do you need this data? Evidence instead of assumptions
- What are you hoping to find? High impact times that could add risk to the user experience when changes are made in a service
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data? 

## Link to Metrics
https://analytics.google.com/analytics/web/template?uid=ob9gC_4oS9SJp4eEuBNo4A

## Additional Comments
- Is this report set up correctly to determine usage times?
- What are the hours of the day based on? (UTC, report viewer, user-specific)

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by johnny-jesensky-adhoc** [comment]
Outdated request - closing.
