### ISSUE TITLE
Successful cancelation

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20462]
## User story
As a user, I want to see an alert that informs me if I've successfully canceled my appointment. 

## Acceptance Criteria
1. If the backend call to cancel an appointment is successful, display a success alert at the top of the appointment detail page
2. UX/UI details for mobile alert
     - Pull in mobile alert CC
     - Alert copy is hard-coded
3. This alert should persist on the page until the user navigates away. Upon returning to this page, the error should not display.
4. The appointment detail card should also display the red **Canceled** indicator below the appointment date/time
5. The cancellation card at the bottom of the screen should be replaced with a card reading: "To schedule another appointment, please visit VA.gov or call your VA medical center."

## Designs
https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/443191411

## UX ticket
#18915

## Accessibility Implementation Guidelines 

- Mark "Your appointment has been canceled" as Header 2

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/9/2021 - Looks good on iOS and Android.  Closing.
