### ISSUE TITLE
Missing side nav for Eastern Oklahoma

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20478]
## What happened?
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bcf11da3-fe61-4fb9-a516-9b732d6d2a6a)
`Eastern-oklahoma-health-care` does not have the left navigation menu in Tugboat (where they are testing). Stan is fairly certain it was available in the DevShop environment prior to moving to Tugboat.  

## Steps to Reproduce
This needs to be done with CAG
- Open https://tugboat.vfs.va.gov
- My projects > CMS
- Repositories > CMS Demo environment
- Previews > Eastern Oklahoma Health Care
- Vets-website - https://web-ee8rfzidxqrextxhrymyuyl4at6qwfig.demo.cms.va.gov/eastern-oklahoma-health-care/
- Observe the left nav is no present 

## Desired behavior
Let nav component should be present 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
Is Eastern OK the only VAMC affected? That would be weird.

Could this just be a faulty entry in [FACILITY_MENU_NAMES](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js)?

**Comment by brangi** [comment]
How do I access to `CMS` 
<img width="1154" alt="Screen Shot 2021-02-26 at 12 41 43 PM" src="https://user-images.githubusercontent.com/100468/109341470-1752d580-7830-11eb-8dc5-e20634492018.png">

**Comment by brangi** [comment]
@mmiddaugh...I can see that there is no data coming from facilitySideBar, where can we check the `vets-website` version on this environment? 

<img width="1165" alt="Screen Shot 2021-03-01 at 1 21 13 PM" src="https://user-images.githubusercontent.com/100468/109550917-81b87f80-7a95-11eb-865e-6dfd70f89989.png">

In comparison with Pittsburgh for example

<img width="1239" alt="Screen Shot 2021-03-01 at 1 20 54 PM" src="https://user-images.githubusercontent.com/100468/109551002-9e54b780-7a95-11eb-8adb-0514378d5009.png">

**Comment by brangi** [comment]
@mmiddaugh closing this issue as it has been validated - https://dsva.slack.com/archives/C0FQSS30V/p1614718901241800?thread_ts=1614268130.133100&cid=C0FQSS30V
