### ISSUE TITLE
Add Attachments | BE

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#20472]
### **User Story**
As a user, I want the ability to upload a file or photo from my device and then upload it to my secure message. 

### **Acceptance Criteria** 

Verify functionality from vets-api: 
1. When a user replies to a message thread or composes a new message, they can add an image or file from their phone to the message

2. When a user selects to add an attachment, they can choose a file from an album or use their camera to take a photo

3. Attachment restrictions:
     - User may attach up to 4 files
     - Acceptable formats: doc, docx, jpg, pdf, png, rtf, txt, xls, xlsx
     - Size limitations:
       - Single attachment cannot exceed 3 MB
       - Total attachment cannot exceed 6 MB

**Comment by narin** [comment]
AC #1 and #2 are complete. Need to verify the attachment restrictions with MHV team.

@ashley-matthews just to be clear, are these the restrictions that the mobile app wants to uphold, or are these restrictions that we've already documented and expect from MHV?

**Comment by narin** [comment]
Confirmed in our discussion that the above restrictions are imposed by the MHV API.

Updated OpenAPI docs with additional info about file attachments.
