### ISSUE TITLE
Reply to Message form

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#20486]
## User story
As a user, I want to be able to respond to a message that has been sent to me so that I can communicate back-and-forth with my healthcare team.

## Acceptance Criteria
1.  Create UX/UI for the form on the "Reply" page using the form wrapper component
2. Message header displays service-driven data that is populated from the message that is being replied to:
     - To: display **Provider name**
     - Subject: display **Subject: Subject line** (2 service-driven fields)
3. Attachments section:
     - Pull in Form Attachments CC #22610
     - Label for FAQ link: "How to attach a file" (routing not needed for this story)
     - Large button: "Add files"
4. Message section:
     - Marked as "Required"
     - Pull in text box CC
5. At the bottom of the form, create UI for 2 large buttons:
     - Primary: "Send". Hook up the **Send confirmation page** (#20817), so that when a user selects the large button, it routes to a page where they can confirm whether or not they want to send their message.
          - _Note: sending the message from the confirmation page is covered in a separate story._
     - Secondary: "Cancel" (routing not needed for this story) 

**Not included in this story**: 
- Field errors #22667

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447461529

### Form fields
**Inactive state(empty):**
Formfield: “{label}, empty."
Formfield/Message: “{label, Hint message}, empty. "
Dropdown: “{label}, empty."
Dropdown/Message “{label, Hint message}, empty. "

**Focused state(editing):**
Formfield: “{label}. Editing - {Input text}. "
Formfield/Message:“{label, hint message}. Editing - {Input text}. "
Dropdown: “{label}. Editing - {Input text}."
Dropdown/Message “{label, hint message}. Editing - {Input text}. "

**Activated state:**
Formfield: “{label}. Filled - {Input text}. ”
Formfield/Message:“{label, hint message}. Filled - {Input text}. ”
Dropdown:“{label}. Filled - {Input text}. ”
Dropdown/Message “{label,hint message}. Filled - {Input text}. ”

### Large buttons
**Add files**
- accessibilityLabel = "add files"
- accessibilityRole= "button"
- accessibilityHint= "add files to this message"

**Send**
- accessibilityLabel = "send"
- accessibilityRole= "button"
- accessibilityHint= "send this message"

**Cancel**
- accessibilityLabel = "cancel"
- accessibilityRole= "button"
- accessibilityHint= "cancel this message and return to the previous page"

## Dev checklist
- [x] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/3/2021 - Good in iOS and Android.  Closing.
