### ISSUE TITLE
Add unit test coverage report to vets-website jenkins jobs 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2048]
follow the suggestion mentioned [here](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/183#issuecomment-535222733) to add unit test coverage reporting to jenkins. 

The report should look similar to this: http://jenkins.vfs.va.gov/job/testing/job/vets-api/job/master/lastCompletedBuild/Coverage/

**Comment by annaswims** [comment]
I think these reports will meet your needs
Total coverage over time:
https://codeclimate.com/github/department-of-veterans-affairs/vets-website/trends/test_coverage_total
current coverage per file:
https://codeclimate.com/github/department-of-veterans-affairs/vets-website/code?sort=-test_coverage

**Comment by rianfowler** [comment]
@gunsch @annaswims I added the links here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/unit-test-coverage-reports.md
