### ISSUE TITLE
Access for Mark Viterna

### ISSUE THREAD

**Issue by mviterna** [department-of-veterans-affairs/va.gov-team#20487]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
Cecilia Lee Cecilia.Lee@va.gov
- Please provide your name.
Mark Viterna
- Please Provide your email.
mark.viterna@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
Team Name = Matsumoto
Company = Libertyits
Role = Software Engineer

- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9goxrP0kG9kj96jm8e2FGhTKCLCq6xFjApDDqbCiSkIr4l31/sbvrXqOlKMvdzT7DemiVCzEPr5QbVv95eo28/hhphmW+bJTYFeVCI7Z1g/PFr1bP2iuPwx8u0GSNywOE8/jl9TleVSbcOcVSsNnBjOAbCJS6Z7dwTpOIdwFOguf+G38qGwuobcA+H1dtwm+hOSjfKHo7msrRhulyMezrLPfwtVZGCyg0bvk7uU4d0zuLZUg+Q0U8tjKJm7YM/YcyuNFsCv2LohfcmCoEbGBDVJE15Ar9x4CX/ze9a00smfpoZzGIIgXh6/cz+3+4atzMZaTO4LGKHeG5LPrhOXt4G7So9cEoRhO6M4Y09dbTDNoYqFFfger7MYi1xsQGsA7aIMKIpXk92P+YJ5UZd+QnlDIMzaqr9WgDWeUZ4PbcWvdoeZTWXeec0kJmGcwI3lm+DxPFn/OkpHHxqpdSg/A7iPfx85nqUVjHi5QLLXKJNxO5iiqBoErYwvQfWT7yW38= mark.viterna@va.gov

```

- Grant AWS Console access?
  > YES / NO
YES - S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house. Needed to track and troubleshoot production issues for Benefits Intake and Forms API. Please mirror Greg Bowman's access.

**Comment by mleclerc00** [comment]
### For AWS Access:

User: Mark Viterna
COR: Cecilia Lee
Approval required: @Jeff-Hayter

**Comment by NCHLiberty** [comment]
Hello. Checking in on this request. We face a lot of obstacles and delays due to having only one team member with this access today. Can you provide a rough timeframe estimate? Thanks!

**Comment by mleclerc00** [comment]
Hi @NCHLiberty we just waiting for approval from @Jeff-Hayter so access can be provided

**Comment by mviterna** [comment]
@mleclerc00 @Jeff-Hayter Thanks for helping us out with this. Please let me know if there is any business justification needed here. Right now we only have one dev with prod access and we actually had a prod issue come up recently as a result of not having access to check things on AWS.

**Comment by mviterna** [comment]
@Jeff-Hayter I've emailed you an encrypted copy of my COE to your VA email. Do we have an ETA on when this ticket will be complete?

**Comment by Jeff-Hayter** [comment]
Perfect - @mleclerc00 Approved for AWS.

**Comment by mleclerc00** [comment]
Thanks, I will work on this shortly

**Comment by mleclerc00** [comment]
@mviterna your permissions have been updated to match Greg Bowman.  When you have a minute test it out and let me know if you have any issues.

**Comment by mviterna** [comment]
@mleclerc00 Looks great! I'm all good, was able to log in
