### ISSUE TITLE
Handle partial results returned from MAS

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#20483]
We need to communicate to users in some way when we get partial results back from MAS, due to an error in a downstream service.

Currently the two services that MAS calls that could have errors are the Video Visit Service and the VistA Data Service. If the former fails, we have video visits. If the latter fails, we won't have in person VA and phone appointments.

The appointments list generally puts up an error message if any of the three services we call (requests, VA appointments, CC appointments) fails, rather than show partial results.

Logging for these errors:
http://sentry.vfs.va.gov/organizations/vsp/issues/20201/?environment=production&project=3&query=is%3Aunresolved+vaos&statsPeriod=14d

We've had a couple incidents where these partial results spike. Generally, we get less than 15 a day.

**Comment by outerpress** [comment]
@jbalboni is the error message the same if any of those services fails? (See screenshot below)

I think it makes sense to continue that pattern for the MAS errors. My guess is veterans would find a partial list suspect and look for other ways to get their appointments if they saw that state.

@rtwell do you have any additional background on this? Also, is the only way to find your appointments if they're not showing in MHV or VAOS to call? (Out of scope for this, but this is where trustworthy appt reminders would come in handy.)

cc: @laurenernest 

<img width="574" alt="Screen Shot 2021-02-25 at 8 24 57 AM" src="https://user-images.githubusercontent.com/2536801/109184325-bbab1e00-7743-11eb-84eb-d7b34f822eac.png">

**Comment by jbalboni** [comment]
@outerpress Yes, it's always the same.

**Comment by outerpress** [comment]
@jbalboni let's stick with the current VAOS pattern and put up the error message if those services fail instead of a partial list.
