### ISSUE TITLE
[Research] What is the timeout for the Form 10-10CG submission API call

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#20482]
**Description**
Understand what the timeout is for the js HTTP client so we can extend the backend timeout to 2 mintues.

**Resources**
- Platform thread https://dsva.slack.com/archives/CBU0KDSB1/p1614269139271400

**Comment by LinnJS** [comment]
Slack [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1614269139271400)

**Comment by ala-yna** [comment]
Closing - research confirmed that there is no timeout on the frontend.
