### ISSUE TITLE
Set up SM test accounts 

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#20492]
Test account set up so that we can test sending messages back and forth between the veteran facing portal and the clinician facing portal

**Comment by patrickvinograd** [comment]
The following test users should be working with SM:

###  ID.me:
* vets.gov.user+41 (DAYT)
* vets.gov.user+226 (DAYT)
* vets.gov.user+261 (SLC)
* vets.gov.user+262 (DAYT)
* vets.gov.user+263 (SLC)
* vets.gov.user+264 (DAYT)

### MHV:
* MHVZACK (DAYT)

DAYT/SLC indicates which pseudo-facility they are assigned to. All these users are currently assigned to one triage team that routes to me and Patrick S. More people can be  added or more triage teams defined as we get more people clinician access.

**Comment by patrickvinograd** [comment]
Closing for now.
