### ISSUE TITLE
Stop disabling `Edit Contact Info` form's Update button

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#20494]
## Background
If a user clicks the `edit your address` from the address validation screen, the edit form's `Update` button will be disabled until they actually make a change to the data in the form. This feels like a bug. I can very easily imagine the following scenario:

1. User edits their address
2. Address validation flags it as invalid
3. User quickly clicks on the `edit your address` link from the validation screen
4. They are returned to the edit view and decide "Yes, this is my address, I don't need to change anything."
5. At this point they cannot continue with their address update because the form's `Update` button is disabled

## Solution (Tuesday, March 2, 2021)

Stop disabling the `Update` button entirely. That will result in a regression where [the update would fail silently](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12632). So in this case we'd allow them to click the `Update` button and then act as though the update succeeded and exit the edit mode.

---
Below is the original text of this ticket, before we settled on the solution above:

## Proposed Solution

Currently, the `Update` button on a contact info form will be disabled if the data that's in the form matches the data that was used to _pre-fill_ the form; either the address on file if they are just starting the edit process, or the address they just entered if they returned the the edit view from the validation screen.

This logic should be changed so that the `Update` button will be disabled if the data in form matches the data that is _currently on file_ for the user. So if the user is editing their Home Address, the button will be disabled if the data in the form matches what is in Redux under `user.profile.vapContactInfo.homeAddress`

### Other Solutions

Stop disabling the `Update` button entirely. But that would result in a regression where the update would fail silently. https://github.com/department-of-veterans-affairs/va.gov-team/issues/12632. There is a case to be made that buttons should never be disabled and it's better to allow users to click the button and _then_ present them with an error (supporting links needed). So in this case we'd allow them to click the `Update` button and then either:

- present them with an error telling them they didn't actually make any changes to their contact info
- or, act as though the update succeeded and exit the edit mode

I actually prefer this second solution.

## Developer Notes

There are some [commented-out Cypress assertions](https://github.com/department-of-veterans-affairs/vets-website/blob/7858ce22c27e432045d0a36c8b0b51a05f770869/src/applications/personalization/profile/tests/e2e/address-validation/edit-after-validation.cypress.spec.js#L63-L83) in the `edit-after-validation.cypress.spec.js` file. If you uncomment them, they will fail. But once this issue is addressed, they will pass.

**Comment by tressaellen** [comment]
Hi @erik - I also prefer the second option. Do you know if there is any guidance around this situation at the VA (disabled buttons vs not disabled)? I just want to make sure we're not changing a pattern that was established for a reason.

**Comment by erikphansen** [comment]
As far as I know we are the only ones who have ever disabled buttons. We also do it on the current My VA Find Benefits page. This is all my fault 😁

**Comment by tressaellen** [comment]
Well then I'll trust you as the mastermind! Let's go with the 2nd option. :)

**Comment by erikphansen** [comment]
@ajakabcin this can be validated on staging now. Please let me know if you need more context to do so!

**Comment by ajakabcin** [comment]
Confirmed. Closing

**Comment by ajakabcin** [comment]
Just noting here the new bug that was introduced as part of the fix - #22114
