### ISSUE TITLE
Clinician/Admin Portal Access

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#20491]
Request + gain access to clinician/admin portal

**Comment by narin** [comment]
@patrickvinograd Can you point me to the forms to get access to the clinician UI when you get a chance? Thanks.

**Comment by patrickvinograd** [comment]
I will document the steps (probably in va.gov-team-sensitive) so others can follow along.

**Comment by patrickvinograd** [comment]
I documented the steps here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/mhv-lower-clinician-admin-access.md

Patrick S and Patrick V have access, Jen and Narin are working on it, so closing this issue as lack of access is not blocking work.
