### ISSUE TITLE
Create agenda and deck for all team onboarding

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#205]

**Comment by rroueche** [comment]
# User story

As a VFS team (including my VA Stakeholders), I need to have an onboarding meeting with the VSP team so I can get an understanding of the services, documentation, support that will be available to me as I work on VSP as well as what to expect of "reviews".

As the VSP team, I need to have an onboarding meeting with new VFS teams so I have awareness of what support to plan for.

# Goal

Have an agenda and deck prepared to go over what support will look like for the VFS team, and specifically/separately for the Engineering team.

# AC
- [ ] Deck template(s) -- full team and Engineering team -- for onboarding kickoff stored in GH
- [ ] Deck for Insignia team kickoff filled in and ready to use
- [ ] Where to store the team specific ones?? ^

# Definition of done
- [ ] AC met
- [ ] Reviewed with DSVA

**Comment by smoonpeyes** [comment]
@rroueche Is there a deck in progress?

**Comment by hpjaj** [comment]
Linking to the WIP deck:

https://docs.google.com/presentation/d/1hWMttdxXOqjidIj3lOSsxycmkl1ZQefHz-oPh3tkHOk/edit?ts=5d13e9c8#slide=id.p2

Let me know if you are not able to access/update the deck!

**Comment by hpjaj** [comment]
Actually, the link I attached above does not appear to be to the correct deck 🤔

@rroueche - Can you pls link me to the deck that you and Andrew created, for the initial "all VFS team" onboarding meeting?  The one that you all started to build for Insignia.

**Comment by hpjaj** [comment]
This has been migrated to Google Slides, and lives in the new [Oddball VSP Product Development](https://drive.google.com/drive/u/1/folders/0ACGojOPyZxgPUk9PVA) shared Google Drive:

https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.p1

**Comment by smoonpeyes** [comment]
@rroueche @gunsch @emilywaggoner 
Will there be a brief section that talks about each of the practice areas?

**Comment by hpjaj** [comment]
@rroueche @gunsch - At your earliest convenience can you pls update the team on where you all are at with this, what expectations you have for the product support team members roles to be in this presentation (if any), etc.

**Comment by rroueche** [comment]
@emilywaggoner is going to move communication norms from the practice area onboardings over to this full-team presentation instead, and since we're having separate practice area onboardings and slack channels and weekly/biweekly meetings, we're not going to include discreet sections for them in the full-team one. (especially since they’ll all happen on one day.)

**Comment by emilywaggoner** [comment]
The feedback has been incorporated and communication norms is now in this deck.

**Comment by andreahewitt-odd** [comment]
@smoonpeyes Can you add this deck to github?

**Comment by smoonpeyes** [comment]
Presentation added: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/templates/VFS-Full-Team-Onboarding.pptx
