### ISSUE TITLE
[Due on 03/02] Redirect Request: Careers parity work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2050]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15515*

**Goal**
After all parity work work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
### Steps to complete
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [x] Ticket is closed - *@ requesting team*

Legacy page | Redirect to New page
-- | --
www.benefits.va.gov/vocrehab/employment_tracks.asp | /careers-employment/vocational-rehabilitation/programs/
www.benefits.va.gov/VOCREHAB/independent_living.asp | /careers-employment/vocational-rehabilitation/programs/independent-living/ 
www.benefits.va.gov/vocrehab/eligibility_and_entitlement.asp |/careers-employment/vocational-rehabilitation/eligibility/ 
www.benefits.va.gov/vocrehab/application_roadmap.asp | /careers-employment/vocational-rehabilitation/how-to-apply/ 
www.benefits.va.gov/VOCREHAB/edu_voc_counseling.asp | /careers-employment/education-and-career-counseling/ 
~www.benefits.va.gov/vocrehab/vsoc.asp~ | ~/careers-employment/vetsuccess-on-campus/~
www.benefits.va.gov/gibill/careerscope.asp | /careers-employment/careerscope-skills-assessment/

**Comment by mnorthuis** [comment]
All parity updates were approved and implemented per this issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16289.

**Comment by mnorthuis** [comment]
Blocked until ops/front end team can determine approach for implementation of redirects.

**Comment by mnorthuis** [comment]
Per discussion with VBA stakeholder Bettye Hodge, we will not be retiring/redirecting the VSOC page.  

Recap from @jenniferlee-dsva: We will remove VSOC locations and counselors contacts list and instead link to: https://www.benefits.va.gov/vocrehab/vsoc.asp

Page crossed off list of redirects above.

**Comment by mnorthuis** [comment]
@Karak888 please let me know once above redirects list has been communicated to appropriate stakeholders, then I will move this forward.

**Comment by MickinSahni** [comment]
2020-02-19 PW Grooming:
- Anne to pre-vet this one before we send this to Mikki
- To gain visibility on these in-between steps, we're going to move it to "In Progress" during the pre-vet and VSP vetting and then assign to a sprint when it's time to implement the redirect

**Comment by AnneHurley** [comment]
@lunascoop  All the URLs at the top of this page are live. 

In addition, the one we initially crossed off the list, is also live: https://www.va.gov/careers-employment/vetsuccess-on-campus/

Note that the above VetSuccess page ^ is in review with the SMEs as further edits were needed. But the first draft of the parity rewriting is live at the URL above.

@jenniferlee-dsva  FYSA

Free to redirect all of the above.

**Comment by mnorthuis** [comment]
@AnneHurley Just to clarify, all of these pages were live before, these redirects are based on parity updates to our version of the page so we can retire the legacy page. Are you saying that our parity updates are done and our pages have all the information that the legacy pages do? 

I get nervous when I see "parity" and "rewriting" used interchangeably. :-)

For the VSOC page, we were asked to remove some content and link to a legacy page rather than have it on our page.  Looks like we did do that.

**Comment by AnneHurley** [comment]
@mnorthuis  This work was parity work. All the pages have the relevant information the legacy pages did. In some cases we created several new pages based off the legacy pages, but since they are new, we don't need to do redirects. Sorry if what is above was confusing. 

Also we do have the VetSuccess page, formerly known as VSOC, live on VA.gov. I didn't check to see if the legacy page was also still live, but since the new one IS live, and since we've been working with stakeholders for updates to it, it seems to me we can start the ball rolling on that redirect as well.

**Comment by mnorthuis** [comment]
@AnneHurley see note above regarding the VSOC page, last direction was not to redirect that legacy page. 

> Per discussion with VBA stakeholder Bettye Hodge, we will not be retiring/redirecting the VSOC page.
> 
> Recap from @jenniferlee-dsva: We will remove VSOC locations and counselors contacts list and instead link to: https://www.benefits.va.gov/vocrehab/vsoc.asp
> 
> Page crossed off list of redirects above.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  Sorry, I'm confused. I know we are keeping the legacy VetSuccess on campus and counselor info, which we are linking to from our new VA.gov page on VetSuccess. Does that mean we wouldn't redirect general URL traffic from the legacy page to our new page which we're working on? I assumed we are redirecting the traffic, but keeping the legacy page as the place listing the campuses and counselors. Just that the main informational page is on VA.gov, and is the one we're working on. Can you clarify?

**Comment by lunascoop** [comment]
Stakeholder comm sent. @ncksllvn redirect implementation scheduled for 03/02. Ready for PR.

**Comment by AkucherGCIO** [comment]
02-27-02 PW Standup
PR has been raised .

**Comment by ncksllvn** [comment]
PR merged, should go live today

**Comment by AkucherGCIO** [comment]
03/02/20 Pw standup
Selina will validate and close this ticket.

**Comment by lunascoop** [comment]
Redirects were implemented successfully. Closing ticket and notifying stakeholders.
