### ISSUE TITLE
Add claims/file upload mock data to test account

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20501]
## Acceptance Criteria
1. Display the following mock claims data for test user vets.gov.user+366@gmail.com
     - Replace any existing mock errors with the mock data detailed in AC #2
2. Mock data should include:
     - An active claim in Step 3, with open file requests
     - At least 2 open file requests
     - Ask for My Claim Decision flow
     - Ability to navigate the file/photo flow

**Comment by digitalken** [comment]
PASS 2/26/2021 - User has mock data - kill app to reset.  Closing.
