### ISSUE TITLE
[File Upload] Standard (global) solution for managing file uploads

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#20503]
### The Problem
We have a number frontend apps and `vets-api` endpoints that deal with file uploads. Each app & endpoint combo handle uploads as a "one-off" kind of solution. Each unique solution comes with potential tradeoffs involving security vulnerabilities & performance degradation. 

We want to have some kind of unified / intentional / global rules & restrictions that apply to all uploads so as to protect va.gov as a whole from such performance & security vulnerabilities.

### Extra Context
- [Comment on a related issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15687#issuecomment-783693628) regarding upload that inspired the creation of this ticket
- We have inconsistent use of `client_max_body_size` in our revproxy configs - [we set it to 50m, 151m, 5g, & 0 (unlimited size) in various places
](https://github.com/department-of-veterans-affairs/devops/search?q=client_max_body_size)
### Work to be Done
- [ ] Design document created
  - [ ] RFC process to engineering stakeholders
- [ ] Implement global upload safeguards according to RFC ☝️ 
  - [ ] revproxy
  - [ ] vets-api
  - [ ] vets-website

**Comment by jhouse-solvd** [comment]
No immediate urgency for this, but good to consider for the long-term. May be something that BE Tools should / could be involved in as well. There's also been conversation about using a different upload procedure. There's been other request(s) to increase upload limit. Definitely good to see how this syncs with other efforts before implementing a solution.

**Comment by dginther** [comment]
@dginther to check with BE Tools / OCTO-DE leadership as to whether this is still something we would like to look into.

**Comment by jhouse-solvd** [comment]
Spoke w/ Roger, Emily, and Daniel from the IET today. This issue is useful for tracking down previous implementations and associated pain points.

**Comment by ewilson-adhoc** [comment]
Adding IET label for now, since this may be work that we will tackle in the future.

**Comment by ewilson-adhoc** [comment]
The problem statement has been added to our epic, https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/37590 -- we should close this story since this work is captured in the epic.
