### ISSUE TITLE
Update prototype with changes to submission experience

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#20507]
## User Story

In #20320, we generated content for an updated submission experience on the 10-10CG. Because of time constraints, we were unable to update the prototype before making the frontend changes. The prototype should match the updated form experience.

## Acceptance Critera

- Prototype is updated to reflect the changes designed in [this ticket](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20320) and implemented in [this one](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20405).

**Comment by mlighdc** [comment]
@jonathanjnelson what is these status of the content/copy/text for the spinner? I believe Justin is waiting for the copy.

**Comment by ala-yna** [comment]
@mlighdc, this is just a ticket to ensure that the prototype is kept up to date. Content was discussed [here](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20320) and added to the Justin's ticket [here](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20405).

**Comment by jonathanjnelson** [comment]
Please see:https://preview.uxpin.com/669525e992a5edd248b84db96767fc607630185b#/pages/137132433?mode=d

**Comment by ala-yna** [comment]
Confirmed the prototype was updated (linked above)
