### ISSUE TITLE
Create a new error message after a 10-10CG submission reaches the timeout limit

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#20508]
## User story

- As a Caregiver, I want to understand what the next best step is after waiting for 2 minutes to submit a 10-10CG, so that I can learn if my submission has gone through or not. 

## Questions to answer
- What information should a Veteran see?
- Can we address the long CARMA processing times?
- Can we try to resend the PDF?

**Comment by hdjustice** [comment]
Closing this ticket - We have since integrated with Mulesoft, and will be addressing timeouts in new tickets/initiatives
