### ISSUE TITLE
How can VFS teams handle outages of critical external services?

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#20514]
## Background

- A number of VFS teams rely on MVI's backend service as a part of their products. However, MVI has completely gone down a number of times, causing Caregiver (and likely other services) error rates to spike dramatically and dangerously.

- Most recently, on February 12, a MVI outage caused the Caregiver error rate to reach [over 20%](https://analytics.google.com/analytics/web/#/dashboard/u4Zg-ougQpq-87e5dGIH_w/a50123418w177519031p184624291/_u.date00=20210212&_u.date01=20210212/), a 700% increase from our typical error rate of 2.64%.  

- The only tool available to us as the time was the [downtime tool](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications), which was insufficient because (1) this wasn't scheduled maintenance and (2) we don't know what other teams rely on the MVI PagerDuty alert.

## Ask

How should catastrophic, system-level outages like this be handled by the Platform? How can we prevent almost 100 veterans from filling out a form, even though we know it won't go through? Who is responsible for what? Specifically:
- #on-call should be aware of the outage
- #on-call should have a solution in place
- *bonus* - PM/POs of respective teams should know that downtime is happening

## Proposed Solution
- When MVI is down, an on-call engineer could trigger the downtime functionality. (What is the impact of this across teams?)
- VSP should maintain a log of when these extended downtime windows have happened.

**Comment by mchelen-gov** [comment]
Edited to clarify that outages refers to services external to VSP.

**Comment by mlighdc** [comment]
@mchelen can you let us know what you think the next steps are?

**Comment by hdjustice** [comment]
@lihanli @lzapson Do either of you know if this has been addressed?  This is a really old ticket, but if the issue still exists where we should address external outages, I dont want to close this.
cc: @markfallows

**Comment by mchelen-gov** [comment]
> @lihanli @lzapson Do either of you know if this has been addressed?  This is a really old ticket, but if the issue still exists where we should address external outages, I dont want to close this.
> cc: @markfallows 

Originally this was a request for Platform to provide additional support for unscheduled downtime of external services.

If this is still a requested feature from Platform it should be submitted through: https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html

Separately, VFS teams are free to implement any monitors and alerts that would be helpful for their application.

**Comment by hdjustice** [comment]
Closing this ticket for now.  We will open a ticket for Platform feature, if we continue to experience system-level outages and need the additional support and logging.
