### ISSUE TITLE
Technical DOC: Possible work needed from Lighthouse and CMS to enable search string matching improvements.

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#20517]
## Issue Description
In its current form, the Find a VA Form search does a string comparison between the search term entered and the form name and form title, yielding poor results when the user does not include dashes, or uses a partial form name.

The inclusion of technical details below could help ratify this issue.
See table as an example:

![Screen Shot 2021-02-25 at 2 50 50 PM](https://user-images.githubusercontent.com/26075258/109208883-dfd52200-7778-11eb-9839-4bd9ff34c676.png)

## Technical Details (This is all up for debate)
- A new field added to the VA Form Nodes in the CMS called _SearchableTerms_ which is a string that holds the patterns that the stakeholders are looking for.
- i.e. form name: **10-10EZ**, the value of **SearchableTerms** would be something like **'10-10EZ 1010EZ 1010'**
- Next we need a new column in the lighthouse database table that holds the forms migrated over from the CMS to store that new CMS, **SearchableTerms**, field.
- We then need to migrate the lighthouse db to add the new column, add it to the rails model serializer, and update the model query to be able to query that column. SEE query on lighthouse model: https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_forms/app/models/va_forms/form.rb#L20

**Comment by zacharymorel** [comment]
This is the issue created from this discovery: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19601

**Comment by MarciMcGuireGCIO** [comment]
Lighthouse team has created their own ticket.  Closing.
