### ISSUE TITLE
Redirects in Health Care based on legacy rewriting work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2051]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17973*

**Goal**
After all legacy rewriting work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
- [x] Determine if all parity changes are complete/live and log tickets that track the approval status
- [x] Validate previously documented redirects and update as necessary
- [x] Create a new parity redirect issue in va.gov-team repo with the list of redirects and reference the original issue and the content approval ticket
- [x] Close the old issues in vets.gov-team repo and reference the new issue in va.gov-team repo
- [x] Communicate upcoming redirects to stakeholders prior to implementing
- [x] Assign out tickets to front-end or devops as appropriate
- [ ] Validate redirects in prod and update documentation when complete

Current Page/URL  |  Redirect to
---  |  ---
www.va.gov/HEALTHBENEFITS/access/index.asp | /health-care/
www.va.gov/HEALTHBENEFITS/access/seamless_care.asp | /health-care/about-va-health-benefits/where-you-go-for-care/
www.va.gov/healthbenefits/cost/index.asp | /health-care/about-va-health-benefits/cost-of-care/
www.va.gov/healthbenefits/cost/financial_assessment.asp | /health-care/about-va-health-benefits/cost-of-care/
www.va.gov/HEALTHBENEFITS/vadip/index.asp | /health-care/about-va-health-benefits/dental-care/dental-insurance-program
www.va.gov/healthbenefits/cost/copays.asp | /health-care/copay-rates/
www.va.gov/healthbenefits/cost/copay_rates.asp | /health-care/copay-rates/
www.va.gov/healthbenefits/apply/active_duty.asp | /health-care/eligibility/active-duty/
www.va.gov/healthbenefits/apply/returning_servicemembers.asp | /health-care/eligibility/active-duty/
www.va.gov/HEALTHBENEFITS/resources/priority_groups.asp | /health-care/eligibility/priority-groups/
www.va.gov/healthbenefits/vhic/index.asp | /health-care/get-health-id-card/
~www.va.gov/healthbenefits/vtp/beneficiary_travel.asp~ | ~/health-care/get-reimbursed-for-travel-pay/~
www.va.gov/healthbenefits/cost/make_a_payment.asp | /health-care/pay-copay-bill/
www.va.gov/healthbenefits/cost/debt.asp | /health-care/pay-copay-bill/
www.va.gov/healthbenefits/cost/disputes.asp | /health-care/pay-copay-bill/dispute-charges/
www.va.gov/healthbenefits/cost/financialhardship.asp | /health-care/pay-copay-bill/financial-hardship/

**Comment by Karak888** [comment]
maybe make 1506 a ticket but tbd

**Comment by mnorthuis** [comment]
**Tickets tracking the rewriting work**

**DONE** Cost of care rewriting: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16095#

**DONE** Active Duty rewriting: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2391

VHIC rewriting: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16957

VADIP rewriting: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17004

Priority groups rewriting: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17005

Beneficiary Travel rewriting: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16955

**Comment by Karak888** [comment]
@jenniferlee-dsva to send spreadsheet to stakeholder week of 10/28

**Comment by Karak888** [comment]
@jenniferlee-dsva sent this to SME for feedback. @Karak888 to review against other page

**Comment by Karak888** [comment]
similar to redirect work for / health care.

**Comment by Karak888** [comment]
sent to Jenny HL and is having her team review.  Putting into icebox until we receive feedback.

**Comment by mnorthuis** [comment]
I have removed the redirect for Beneficiary travel in the list above, all others are ready for redirect.  

Assigning ticket over to you @Karak888 to schedule and implement.

**Comment by Karak888** [comment]
thanks @mnorthuis !!

**Comment by jenniferlee-dsva** [comment]
@Karak888 @meganhkelley - Looks like we can start redirecting these ^?  I know we're heading into code freeze but we can queue these up to be ready post-freeze?

**Comment by Karak888** [comment]
@lunascoop please reach out to SMEs to get timing of redirect request and once @mnorthuis verifies my request form, add in the timing for when these should go. :cc @ncksllvn @jenniferlee-dsva

**Comment by mnorthuis** [comment]
@Karak888 @lunascoop Let's use your redirect request ticket #4334 to track this work. I'm going to close this one so we don't have multiple tickets to keep track of.
