### ISSUE TITLE
[Launch April 6] Redirects in Education based on parity work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2052]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15512*

**Goal**
After all parity work work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Acceptance Criteria / Definition of Done:**
- [x] All information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

Legacy page | Redirect to New page 
-- | --
www.benefits.va.gov/gibill/education_programs.asp | /education/
www.benefits.va.gov/gibill/get_started.asp | /education/
www.benefits.va.gov/gibill/montgomery_bill.asp | /education/about-gi-bill-benefits/
www.benefits.va.gov/gibill/coop_training.asp |  /education/about-gi-bill-benefits/how-to-use-benefits/co-op-training/
www.benefits.va.gov/gibill/correspondence_training.asp | /education/about-gi-bill-benefits/how-to-use-benefits/correspondence-training/
www.benefits.va.gov/gibill/entrepreneurship_training.asp | /education/about-gi-bill-benefits/how-to-use-benefits/entrepreneurship-training/
www.benefits.va.gov/gibill/flight_training.asp |/education/about-gi-bill-benefits/how-to-use-benefits/flight-training/ 
www.benefits.va.gov/gibill/accelerated_payments.asp | /education/about-gi-bill-benefits/how-to-use-benefits/accelerated-payments/
www.benefits.va.gov/gibill/non_college_degree.asp | /education/about-gi-bill-benefits/how-to-use-benefits/non-college-degree-programs/ **note  below**
www.benefits.va.gov/gibill/onthejob_apprenticeship.asp | /education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/
www.benefits.va.gov/gibill/independent_distance_learning.asp | /education/about-gi-bill-benefits/how-to-use-benefits/online-distance-learning/
www.benefits.va.gov/gibill/foreign_school_information_for_students.asp | /education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/ **see note below**
www.benefits.va.gov/gibill/licensing_certification.asp | /education/about-gi-bill-benefits/how-to-use-benefits/test-fees/ **see note below**
www.benefits.va.gov/gibill/national_testing.asp | /education/about-gi-bill-benefits/how-to-use-benefits/test-fees/
www.benefits.va.gov/gibill/tuition_assistance.asp | /education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/
www.benefits.va.gov/gibill/tutorial_assistance.asp | /education/about-gi-bill-benefits/how-to-use-benefits/tutor-assistance/ 
www.benefits.va.gov/gibill/higher_learning.asp | /education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs/ 
www.benefits.va.gov/gibill/workstudy.asp | /education/about-gi-bill-benefits/how-to-use-benefits/work-study/
www.benefits.va.gov/gibill/mgib_ad.asp |  /education/about-gi-bill-benefits/montgomery-active-duty/
www.benefits.va.gov/gibill/mgib_sr.asp |  /education/about-gi-bill-benefits/montgomery-selected-reserve/
www.benefits.va.gov/gibill/post911_gibill.asp |  /education/about-gi-bill-benefits/post-9-11/
www.benefits.va.gov/gibill/choosing_a_school.asp | /education/choosing-a-school/ **see note below**
www.benefits.va.gov/gibill/school_locator.asp | /education/choosing-a-school/
www.benefits.va.gov/gibill/school_decision.asp | /education/choosing-a-school/ **see note below**
www.benefits.va.gov/gibill/principles_of_excellence.asp | /education/choosing-a-school/principles-of-excellence/ 
www.benefits.va.gov/gibill/apply.asp | /education/how-to-apply/
www.benefits.va.gov/gibill/national_call_to_service.asp | /education/other-va-education-benefits/national-call-to-service-program/ 
www.benefits.va.gov/gibill/reap.asp | /education/other-va-education-benefits/reap/  **see note below**
www.benefits.va.gov/gibill/veap.asp | /education/other-va-education-benefits/veap/  **see note below**
www.benefits.va.gov/gibill/survivor_dependent_assistance.asp | /education/survivor-dependent-benefits/ 
www.benefits.va.gov/GIBILL/DEA.asp  | /education/survivor-dependent-benefits/dependents-education-assistance/  **see note below**
www.benefits.va.gov/GIBILL/Fry_scholarship.asp | /education/survivor-dependent-benefits/fry-scholarship/ 
www.benefits.va.gov/gibill/post911_transfer.asp | /education/transfer-post-9-11-gi-bill-benefits/
www.benefits.va.gov/gibill/fgib/VetTec.asp | /education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/
www.benefits.va.gov/GIBILL/fgib/VetTec_Veteran.asp | /education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/ 
www.benefits.va.gov/GIBILL/FGIB/VetTecTrainingProviders.asp | /education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/  **this isn't a Veteran facing page**

**Comment by mnorthuis** [comment]
Parity updates are complete and live based on this issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15111.

**Comment by mnorthuis** [comment]
@peggygannon  This[ issue](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15111) states that all parity edits are approved and live, but the issue below has a number of questions that came up after the fact that I'm not sure if they were resolved or not.  Can we chat about this one?

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15512

**Comment by mnorthuis** [comment]
@lunascoop Can you help track down whether we answered/modified content to accomodate all the open questions mentioned in this issue for education?

department-of-veterans-affairs/vets.gov-team#15512

**Comment by peggygannon** [comment]
Hi, @mnorthuis @lunascoop I don't think we updated content for the questions I raised in issue 15512. I recall Beth was going to followup with stakeholders on those questions, but I'm not sure that happened before the transition. 

If not, then global-ux team might need to reach out to EDU stakeholders about those open parity questions.

**Comment by lunascoop** [comment]
Hi @mnorthuis @peggygannon I reviewed the pages mentioned in issue 15512 and here's what I noted. I also included the original comment/question. I will search for additional tickets that pertain to this issue.

www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/non-college-degree-programs/
**Original comment:** Add barber/beautician school to this page?
**Review:** Content regarding barber/beautician school has not been added.

www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools/
**Original comment:** Incorporate the below note onto the page?
IMPORTANT: Some schools located in the United States offer courses in a foreign country under contract with the Department of Defense. These courses are not considered foreign training. Similarly, “Junior Year Abroad” programs and similar programs offered by schools in the United States are not considered foreign training
**Review:** The _important_ content seems to have been added to the page. See excerpt below:
"Exception: Programs at schools located in the United States that offer courses in a foreign country through the Department of Defense don’t qualify as foreign training. Also, year abroad and similar programs offered by schools in the United States don’t qualify as foreign training."

www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/test-fees/
**Original comment:** Add the below info to the page?
Fees connected with obtaining a license or certification are not reimbursable.
**Review:** Verification needed that content has been updated per the above statement. According to the website, the above statement isn't entirely true as certain license and certification fees are reimbursable. There is a URL link (WEAMS) to where a user can find covered licenses and certifications and the reimbursed amount.

www.va.gov/education/choosing-a-school/
**Original comment:** Add a link to the GI Bill Comparison Tool to this page?
add links that appear at the bottom of this page (https://www.benefits.va.gov/gibill/choosing_a_school.asp) to the new VA page?
**Review:** Link to new GI Bill Comparison Tool was added via the "Find which schools we've approved" bullet point. However, there was no link to the above URL added. Need to confirm if this update is complete.

www.va.gov/education/how-to-apply/
**Original comment:** Add a link to VA's interactive map for checking local processing times?
**Review:** Link to VA's interactive map for checking local processing has not been added.

www.va.gov/education/other-va-education-benefits/reap/
**Original comment:** Add information about Colmery Act and reservists crediting their REAP eligibility toward Post-9/11 benefits?
**Review:** Information above has not been added.

www.va.gov/education/other-va-education-benefits/veap/
**Original comment:** Add Air Force Eligibility requirements to this page?
**Review:** Information above has not been added.

www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/
**Original comment:** Add Additional Assistance information to this page?
**Review:** Information above has not been added.

**Comment by mnorthuis** [comment]
Thank you @lunascoop for doing all the digging!  I won't be able to redirect the legacy pages if we have not accounted for the content yet.  I think we should create a ticket with the information above (or however we want to track it) for doing the content work to get these pages up to parity. That will remain a blocker for these redirects.   Selina, can you work with Kara/Jen on creating the ticket and getting that content work done?

**Comment by mnorthuis** [comment]
Blocked until content edits are complete.

**Comment by mnorthuis** [comment]
I can find confirmation of all of the above pages being ready with the exception of these 4.

@Karak888 I am assign this ticket to you, all have been vetted and documented.  You can schedule these to be done once the below pages are also ready.  

legacy URL |  Redirect to
-- | --
www.benefits.va.gov/gibill/post911_gibill.asp | /education/about-gi-bill-benefits/post-9-11/
www.benefits.va.gov/gibill/school_decision.asp | /education/choosing-a-school/
www.benefits.va.gov/gibill/apply.asp | /education/how-to-apply/
www.benefits.va.gov/gibill/reap.asp | /education/other-va-education-benefits/reap/

**Comment by mnorthuis** [comment]
@AnneHurley Please see my previous notes on this one...I was able to find through tickets that the parity work is complete on all but the 4 mentioned in the previous comment.

**Comment by MickinSahni** [comment]
PW Grooming 
- Will require Anne's pre-vetting before Mikki assigns this to PW for implementation
- Moving this to Ready (and then In Progress) during the background work

**Comment by AnneHurley** [comment]
Auditing content on these remaining 4 pages per @mnorthuis & @lunascoop 

legacy URL |  Redirect to
-- | --
www.benefits.va.gov/gibill/post911_gibill.asp | /education/about-gi-bill-benefits/post-9-11/
www.benefits.va.gov/gibill/school_decision.asp | /education/choosing-a-school/
www.benefits.va.gov/gibill/apply.asp | /education/how-to-apply/
www.benefits.va.gov/gibill/reap.asp | /education/other-va-education-benefits/reap/

**Comment by MickinSahni** [comment]
2020-03-18
* Removing `needs-grooming` label as the work is clear. Need to prioritize against other commitments

**Comment by AnneHurley** [comment]
legacy URL |  Redirect to
-- | --
www.benefits.va.gov/gibill/post911_gibill.asp | /education/about-gi-bill-benefits/post-9-11/
www.benefits.va.gov/gibill/school_decision.asp | /education/choosing-a-school/
www.benefits.va.gov/gibill/apply.asp | /education/how-to-apply/
www.benefits.va.gov/gibill/reap.asp | /education/other-va-education-benefits/reap/

1. va.gov/education/about-gi-bill-benefits/post-9-11/ -- THIS PAGE CONTAINS ALL THE PARITY UPDATES NECESSARY TO BE REDIRECTED.
2. va.gov/education/choosing-a-school/ -- THIS PAGE CONTAINS ALL THE PARITY UPDATES NECESSARY TO BE REDIRECTED.

**Comment by AnneHurley** [comment]
@MickinSahni @lunascoop @mnorthuis @jenniferlee-dsva  Creating a new ticket to capture need to rethink/reorganize the REAP page. Perhaps that's info that we can now pull into the main GI Bill benefits page.

**Comment by MickinSahni** [comment]
2020-03-19 PW Standup
- Anne's portion is complete. Mikki vetting + implementation is remaining
- pulling out of sprint and into Ready until vetted and ready to implement the redirects

**Comment by MickinSahni** [comment]
2020-03-23 PW Standup
- Awaiting vetting before we implement this ticket by PW!

**Comment by mnorthuis** [comment]
In reading through comments, it appears that all parity work is complete. 

I removed one line for yellow ribbon page/content that is already redirected and does not need to be touched as part of this work.   All other redirects are ready to go.

**Comment by MickinSahni** [comment]
Thanks, Mikki. 
@AnneHurley @lunascoop — safe to slot for sprint 18?

**Comment by lunascoop** [comment]
@MickinSahni That should work. I'll send out the stakeholder comm tomorrow.

**Comment by AnneHurley** [comment]
@MickinSahni  - Yes good to go. thx

**Comment by MickinSahni** [comment]
2020-03-25 PW Planning
- Sending out stakeholder comms and scheduling for April 6

**Comment by lunascoop** [comment]
Stakeholder comm sent. @ncksllvn @kelsonic scheduled for **April 6th**.  Updated URL list in the initial comment to exclude the URL below, which was stricken through.

www.benefits.va.gov/gibill/yellow_ribbon.asp | /education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/
-- | --

**Comment by MickinSahni** [comment]
2020-03-27 PW Standup
- Redirects on-schedule for April 6
- Note: [one redirect removed](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2052#issuecomment-604015135) from list

**Comment by ncksllvn** [comment]
I opened a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12046) for this based on the issue description because it seems like it was kept up-to-date. LMK if there changes required though.

**Comment by MickinSahni** [comment]
2020-03-30 PW Standup
- Selina to review the open PR

**Comment by MickinSahni** [comment]
2020-04-01 PW Standup
- Selina to review [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12046)

**Comment by MickinSahni** [comment]
2020-04-02 PW Standup
* reviewed PR, left feedback on PR for Nick to review

**Comment by MickinSahni** [comment]
2020-04-03 PW Standup
- This one is still a go for next week

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- Good to go for redirects today

**Comment by lunascoop** [comment]
Redirects have been validated. Closing ticket and updating stakeholders. Thanks everyone!
