### ISSUE TITLE
Solution for tagging PRs

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#20526]
## Issue Description
It was discussed that we should investigate a solution that tags PRs with the appropriate labels. When on the support rotation, it's often difficult to determine if the backend tools team is needed for a PR review. E.g. Lighthouse or VAOS PRs. By having an auto tagging mechanism, we would be able to better filter PRs for review purposes. 

The tagging solution could be based upon coding changes in specific files or directories that belong to codeowners.

---
## Tasks
- [ ] Investigate auto tagging solution

**Comment by ericboehs** [comment]
I think this action should do it: https://github.com/actions/labeler

**Comment by cbtkc** [comment]
@thilton-oddball implemented a solution for this - think this can be closed.
