### ISSUE TITLE
508-defect-4 [TTY]: Consider a review for inclusive language in landing page TTY call to action

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#20527]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor, Meli_

## Related Issues
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/23664
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/23579

## User Story or Problem Statement

As a TTY user, I would find value in a consistent call to action that had familiar language, iconography, and possibly linked text.

## Details

The VA Mobile team is taking a close look at TTY links for inclusive language, universal icons, and reducing redundancy. Our section landing pages might benefit from a language review, to see if the current text "If you have hearing loss, call TTY: 711." is the right CTA.

## Acceptance Criteria

- [ ] Issue is reviewed by the Sitewide Content team
- [ ] Content changes are coordinated with CMS team as needed

## Environment

* https://staging.va.gov/health-care/ (and other top-level informational pages)

## Screenshots or Trace Logs

![Screen Shot 2021-02-26 at 8 02 20 AM](https://user-images.githubusercontent.com/934879/109311125-0348ad00-780b-11eb-8cbf-9189285c660a.png)

---
<img width="561" alt="Screen Shot 2021-02-26 at 8 06 59 AM" src="https://user-images.githubusercontent.com/934879/109311144-080d6100-780b-11eb-9655-d709be43a054.png">

**Comment by DanielleThierryUSDSVA** [comment]
Hi @1Copenut @msmanak. Thanks for creating this ticket. Yes, let's definitely review. Want to set up a call to chat through some ideas for how we might want to approach?

**Comment by 1Copenut** [comment]
I just sent a meeting invite for Monday, 4/19. Thank you!

**Comment by 1Copenut** [comment]
@DanielleThierryUSDSVA I'm going to close this issue because we've had the initial discussion, agree there's a need for consistent TTY language, and will open relevant tickets for that work.
