### ISSUE TITLE
Form wrapper common component

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20523]
## Acceptance Criteria
1. Create wrapper around form inputs to handle form functionality. This form will be used on the following parts of the app:
     - Contact Info forms (Address/Phone/Email)
     - Direct deposit form
     - COVID-19 form
2. Tasks include:
     - Determine when to show field errors
     - Check when the form is good to submit
     - Check when the form is bad and can't be submitted

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/22/2021 - Working for the new form errors.  Closing.
