### ISSUE TITLE
Investigate GI Bill Data Services CI pipeline and figure out how we can test that the docker container starts and runs.

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#20522]
There was an update to the Gi Bill Data Service service which upgraded the Rails version, but failed to upgrade the Bundler version in the Dockerfile. This caused the service to be unable to start. This should have been found in the CI pipeline and the merge should not have been allowed.

According to https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/Gibct%20Data%20Service.md the Operations team is responsible for this service.

Investigate the Jenkinsfile in this repo:
https://github.com/department-of-veterans-affairs/gibct-data-service

determine where we can add a test that will make sure that the service can start in the Docker container that is defined in the Dockerfile in that repo.

**Comment by jhouse-solvd** [comment]
Ops is responsible for the gids service. In the pipeline, we need to test that it starts up, and/or add documentation that instructs developers to validate that the docker container runs successfully. 

The risk is that a developer upgrades rails for the app, but doesn't update the docker definition to make sure that it builds. 

So, this service could easily be broken if a change like the above was made. @dginther  to take a look and understand LOE.

**Comment by jhouse-solvd** [comment]
Closing this in favor of moving forward on migrating GIDS to EKS
