### ISSUE TITLE
Dynamically maintain a list of facilities that CARMA accepts for 10-10CG submission

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#20533]
**Description**
When sending a 10-10CG submission to CARMA, CARMA will look at the "Planned Facility" station number to route the application to the proper processing facility. CARMA has a list of facilities that they can accept. Periodically poll for this list so we can update the "Planned Facility" pick-list on the form, so users can always have a full list of qualified facilities to pick from when applying.

**User Story**
As a user filling out an Online 10-10CG,
I'd like to select a "Planned Facility" from a list of up-to-date facilities.

**Comment by hdjustice** [comment]
This ticket is no longer necessary, as we will be connected to Lighthouse/Facilities API to retrieve the most up to date facilities list for selection.
