### ISSUE TITLE
Redirects in Disability based on legacy rewriting work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2053]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue:https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17974*

**Goal**
After all parity work work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
- [x] All information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

Current Legacy Page URL  |  Redirect to
--  |  --
~https://www.benefits.va.gov/compensation/effective_dates.asp *This URL is already redirected, but the redirect needs to be updated to the newer page*~ | ~https://www.va.gov/disability/effective-date/~
www.vets.gov/disability-benefits/after-you-apply/date/  *This URL is already redirected, but the redirect needs to be updated to the newer page* | https://www.va.gov/disability/effective-date/
https://www.benefits.va.gov/compensation/rates-index.asp | https://www.va.gov/disability/compensation-rates/
https://www.benefits.va.gov/compensation/resources-rates-read-compAndSMC.asp | https://www.va.gov/disability/compensation-rates/
https://www.benefits.va.gov/compensation/read_rates.asp | https://www.va.gov/disability/compensation-rates/
https://www.benefits.va.gov/compensation/resources_comp01.asp | https://www.va.gov/disability/compensation-rates/veteran-rates/
https://www.benefits.va.gov/compensation/resources_comp02.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2018.asp | https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
https://www.benefits.va.gov/compensation/sb2018.asp | https://www.va.gov/disability/compensation-rates/birth-defect-rates/
~https://www.benefits.va.gov/compensation/dbq_disabilityexams.asp~ *Per vets.gov issue [#16793](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16973) content is retiring and VBA will handle redirect* | ~https://www.va.gov/disability/dbq-questionaires/~
~https://www.benefits.va.gov/compensation/dbq_overview.asp~ *Per vets.gov issue [#16793](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16973) content is retiring and VBA will handle redirect*| ~https://www.va.gov/disability/dbq-questionaires/~
~https://www.benefits.va.gov/compensation/dbq_veteraninstruct.asp~ *Per vets.gov issue [#16793](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16973) content is retiring and VBA will handle redirect*| ~https://www.va.gov/disability/dbq-questionaires/forms/~
~https://www.benefits.va.gov/compensation/dbq_ListByDBQFormName.asp~ *Per vets.gov issue [#16793](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16973) content is retiring and VBA will handle redirect*| ~https://www.va.gov/disability/dbq-questionaires/forms/~
~https://www.benefits.va.gov/compensation/dbq_ListBySymptom.asp~ *Per vets.gov issue [#16793](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16973) content is retiring and VBA will handle redirect*| ~https://www.va.gov/disability/dbq-questionaires/forms/~
https://www.benefits.va.gov/compensation/claimexam.asp | https://www.va.gov/disability/va-claim-exam/
https://benefits.va.gov/compensation/add-dependents.asp | https://www.va.gov/disability/add-remove-dependent/
www.vets.gov/disability-benefits/apply/dependents/form-686c-dependents *This URL is already redirected, but the redirect needs to be updated to the newer page*  | https://www.va.gov/disability/add-remove-dependent/
www.vets.gov/disability-benefits/apply/dependents *This URL is already redirected, but the redirect needs to be updated to the newer page* | https://www.va.gov/disability/add-remove-dependent/

**Comment by mnorthuis** [comment]
This issue is blocked until the URL change for the `/effective-dates` page is done per this issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16956

**Comment by mnorthuis** [comment]
Issues documenting status of rewriting work in Disability:

**DONE** Rates pages: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16956

C&P Exam and Add Dependent pages were handled in parity - cannot find issue documenting completion of work.

**Comment by mnorthuis** [comment]
All items (not crossed out) in the list above can be redirected once stakeholders are notified. 

Assigning to you @Karak888 so it can be scheduled.  Please use this ticket to complete implementation.

**Comment by mnorthuis** [comment]
@lunascoop These are the remaining redirects that need to be implemented in disability.  Can you please confirm with the team that the writing work is complete and if so let's create a clean redirect request for these.

**Comment by MickinSahni** [comment]
Grooming: 
- Vet this one before creating a clean redirect request

**Comment by lunascoop** [comment]
@MickinSahni @mnorthuis Can we close this ticket as a new ticket (#6087 ) was created per Mikki's previous [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2053#issuecomment-584900031)?

**Comment by mnorthuis** [comment]
Tracked in #6087. Closing.

**Comment by MickinSahni** [comment]
@lunascoop @mnorthuis is the new ticket #6087 going to track the actual redirect implementation? 

If so, I'm going to remove this ticket from our (public websites) sprint 15 commitments in favor of the new ticket in a future sprint.

**Comment by lunascoop** [comment]
@MickinSahni Yes the new ticket will track the redirect implementation.

**Comment by MickinSahni** [comment]
cool. thanks, selina. removing this from sprint 15 commitments. cc @AkucherGCIO
