### ISSUE TITLE
Access for Jennifer Nguy

### ISSUE THREAD

**Issue by jnguy-va** [department-of-veterans-affairs/va.gov-team#20535]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Jennifer Nguy
- Please Provide your email.
   > jennifer.nguy@va.gov | jennifer.nguy@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse, Developer, Liberty IT Solutions

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZ7QYOA4V8FmHoez2lDj27YQLYeCMrSLLF7QBDSG0NyRWPnZDLsOkdc8++fAhjUvTY09Qesv4EXkuP7cJzfWliCrJ0yJJGqO9B4+kyJGIRWyAW5VQfpYy/cPGBEDeKiAUDL0QSOiTXt6XpltnqZA5uqlkL/wy0MDXqTbuJMsKe4YCubUwM0MO1Us7CT5edA3y+mOdrUf2AxNHcHCeZYAonSKBer+kpAjL5UiSCaJPffCI68jf9HlHj/1870GbriQS93BiJc3mEzMzIjjnKsZj249JgSDKqWbadroN3CzEU1ib4etFx2+h16KFCBzVZbNrrXyKzvry2xvFwWLFzi7uQ8szLL1yGta+7a0N1t0pT3bwT0abnKLqdSKQgcRF7RpJ3wHMo5uLkPM+r5A1ttHRQS3tLmHjukJ4J/nBEN826XQnAGVLpvWLSSPuXzi6bV0zCtaltcOrJP2acs0U9Do5M0R3y0CJ3WGBxACHcgWTR3GCHMz7E3xneKJn2jCyfD60= VHAMASTER+VHAISPNGUYJ@ORL-LTLN1562740

```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
Access to cloudwatch logs and kibana metrics (and other logging) for Facilities and CCE.

**Comment by mleclerc00** [comment]
@jnguy-va

which one of these email addresses is tied to your github account?

**Comment by mleclerc00** [comment]
For AWS Access:
User: Jennifer Nguy
COR: Cecilia Lee
Approval required: @Jeff-Hayter

**Comment by jnguy-va** [comment]
> @jnguy-va
> 
> which one of these email addresses is tied to your github account?

jennifer.nguy@libertyits.com

**Comment by mleclerc00** [comment]
Hi @jnguy-va,

I have added your key to the socks configuration so you should access now.  If you get a chance please test this out and let me know if you have any further issues.

Will keep this ticket open and revisit once AWS approval is given.

Thanks!

**Comment by Jeff-Hayter** [comment]
@mleclerc00 Approved for AWS.
