### ISSUE TITLE
VA Profile: Resolve MVI 201 errors 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20537]
## Background
VA Profile is returning an error saying people aren’t in MPI when we’re able
to initialize them in MPI on our end.

Related ticket: [BE] log when users have a mvi_response.status of OK then return a va profile MVI201 error #18349

[Slack convo](https://dsva.slack.com/archives/C7TE0PFTL/p1611332694003100)

Current status: 2/26/21: Triaging ticket to get info back from MVI to see what’s going on 

## Tasks
- [ ] VA Profile to investigate what is going on with MVI
- [ ] AE meets with VA profile to determine next steps

**Comment by mshea0606** [comment]
Current status: 2/26/21: Triaging ticket to get info back from MVI to see what’s going on

**Comment by Samara-Strauss** [comment]
3.5.21 — Next steps: This issue is going to be escalated to the VA Profile production operations (ProdOps) team. They will reach out to us over email for more information.

**Comment by Samara-Strauss** [comment]
Adding blocked label to indicate we can't fix this without action from VA Profile.

**Comment by Samara-Strauss** [comment]
From today's VA Profile meeting — Josh Lindsey is supposed to be looking into this, but Mike didn't have an update on that today. He said to check in with him next week to see if he's had a chance to regroup with Josh.

**Comment by Samara-Strauss** [comment]
4.30.21 Update — Still waiting for word on this from Josh Lindsey, but no other updates on this besides that in today's VA Profile meeting. I've pinged him in Slack as well to see if I can get an answer more directly.

**Comment by Samara-Strauss** [comment]
5.4.21 update: Just had a call with Josh Lindsey, and he said in his preliminary investigation, it looks like the following is happening:

- A request to create is being made for a new VA Profile. 
- Almost simultaneously, there is also a request to retrieve. MPI is then responding that they don’t exist.

Josh said he needs Lihan's help to look into this further, but still awaiting more details on what that might look like.

**Comment by Samara-Strauss** [comment]
Latest from Josh Lindsey via Slack:

> MVI201 - Initial triage of the MVI201 is that VA.gov is sending ICNs that are not in MPI (or not exposed in the 1305/1306 VAPRO makes), as such they are considered an invalid identity. A list of ~1.8K of these requests was sent to group to support identity lineage / provenance identification.
> 
> Status: Blocked
> 
> Lihan – Data request for request / response to MPI on one of the ICNs to demonstrate that the ICN is in the response and the current status.
> Danny – Send a data request to understand why a few of the ICNs do not show in MPI toolkit or 1305/1306 responses.

**Comment by Samara-Strauss** [comment]
@lihanli assigning back to you temporarily so we can track down information for Josh Lindsey. This is his request [via Slack](https://dsva.slack.com/archives/C7TE0PFTL/p1621278686183000?thread_ts=1621269708.182300&cid=C7TE0PFTL):

> I’m looking for Va.gov audit/trace information for 1 or more of the ICNS, demonstrating the request from VA.gov to MPI where the ICN were contained in the response.

@lihanli do you need any more information from Josh to be able to fulfill this request?

cc/ @ajakabcin for awareness

**Comment by Samara-Strauss** [comment]
Latest update: Josh Lindsey has documented these issues and asked for more information from MPI on what resolution would look like. These issues were forwarded to Lihan and myself on 5/18/21.

**Comment by Samara-Strauss** [comment]
Latest from Lihan:

> i was able to verify the icns are invalid, i talked to him (Josh Lindsey] about it and he says MPI is looking into the issue

**Comment by Samara-Strauss** [comment]
Update from today's VA Profile meeting: MPI is working on a fix for the 201 error, but I don't have a date for an estimated fix.

**Comment by Samara-Strauss** [comment]
10.01.21 -- This issue has been resolved according to VA Profile.
