### ISSUE TITLE
[Research] Update "Planned Facilities" list when a VA Facility changes names

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#20531]
**Description**
The 10-10CG has a list of station numbers. When the name of one of these facilities changes, we should update the static "Planned Facility" picklist on the form.

**Implementation Plan**
At the start of the form, the front-end will load the facilities list from the API. It will use that data to populate the pick list on the front-end.

The API will be responsible for maintaining list and its labels. A background job will regularly fetch all facility labels from Lighthouse and update the labels that have changed.

Once this is implemented on vets-api, we can remove the list in vets-json-schema, and update all code (frontend, backend, and schema) that depend on it.

**Considerations**
- Supporting changes to list of station numbers (not just lables)
  - These changes should (and do) should support future need to pull list of station numbers form CARMA.
- Validating the `plannedFacility` property
  - Currently, the 10-10cg schema relies on the list of station numbers for validation of the value provided for the `plannedFacility` property. We may need move the enum validation from the schema (only validate type) to the backend (on claim.valid?).
  -  We may have to settle for just validating a type of string (so AR validations are not dependent on a redis/PG call)
- How to handle the removal of a facility from list
  - If a submission went through to CARMA with facility _n_, but that facility was removed from the list before attachments were delivered (in the case that a claim is built and validated). The same could also happen if a facility was selected after it was removed from the list in the backend.
  - To support removals of facilities from this list without creating submission/attachment errors, we should:
    - have a flag `deprecated_at` for each facility that was removed from the CARMA list
    - Have then endpoint not return deprecated facilities, so it's not an option for users to select.
    - Have all dependent code (claim validation, pdf generation, etc.) use the full list of facilities (including deprecated ones).
- Logging
  - We should maintain an audit log of what changes occur to the list on every update (which facilities were added, changed, or deprecated).

**Tickets**
- 0 [Backend] (tentative) Create migration if needed
- 1 [Backend] Create Redis/PG store that contains the list of PCAFC facilities
- 2 [Backend] Create an endpoint that serves the list of PCAFC facilities (grouped by state, heavily cached).
- 3 [Backend] Update the 10-10cg submission to validate planned facility property from PCAFC facilities list in API
- 4 [Schema] Remove the enum constraint on `plannedFacility` property on 10-10cg schema.
- 4 [Front-end] Start using the facilities list provided by API (remove references to schema's list).
- 4 [Backend] Remove dependencies of the schema's list of facilities (i.e. pdf generation).
- 5 [Schema] Delete the Caregiver Program facility list from vets-json-schema.
- 4 [Backend] Create process to update facility labels and updates cache.

**Comment by tchrisdyer** [comment]
We can use this as the Research ticket for using the Facility API to retrieve Facility names to match with our static list of station IDs.

**Comment by kevinmirc** [comment]
@dat-gcio Would you be able to pull a pick list, from vets-api, at the start of the form? Does the form system allow this?

**Comment by dat-gcio** [comment]
@kevinmirc Is it possibly, talking with platform support right now on options, and how custom it is.

**Comment by dat-gcio** [comment]
@kevinmirc Definitely possible with a custom widget. Fully support pulling from an api, even if it's more work on the FE.

**Comment by kevinmirc** [comment]
I've updated the description with a plan for maintaining an up to date list of facilities (and labels), with a list of tickets that outline how it needs to be done. The number prefixed described the order in which in needs to be completed (some can be done in parallel).

This plan assumes that the front-end can pull the list of facilities from the API, at the start of the form, and use that list in the planned facility pick list.
