### ISSUE TITLE
Maintain an up-to-date list of "Planned Facilities" for the 10-10CG pick list

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#20530]
**Description**
The Online Form 10-10CG has a list of facilities where the user (1) chooses "where they plan to receive care" and (2) which PCAFC facility the form gets routed to for processing.

This list should always be updated with the facility's most up-to-date name, and should include all facilities that CARMA can accept as a processing facility.

**Comment by ala-yna** [comment]
Migrating to https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/19433
