### ISSUE TITLE
Prefill contact info

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2054]
## Story
As a veteran with an existing VA.gov account, I want my contact information to be prefilled for me in the online scheduling tool when I so that I don't have to type it in again.

## AC
- [ ] Email address for appt contact preferences prefilled to veteran's email on file for both requests and direct schedule appointments
- [ ] Phone number for appt contact preferences prefilled to veteran's email on file for both requests and direct schedule appointments

**Comment by erikphansen** [comment]
@markgreenburg which phone number should be prefilled? Home, mobile, and work are all available options.

**Comment by markgreenburg** [comment]
Let's use mobile if available, and home if no mobile available.
