### ISSUE TITLE
[Alerting] Prometheus alerts should have a purpose and/or deployment_name tag(s) that match their respective EC2 tag values

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#20548]
From https://github.com/department-of-veterans-affairs/devops/pull/8587:

Currently, some alerts do not have the "purpose" or "deployment_name" labels for filtering by the alert manager route matcher. 

![image](https://user-images.githubusercontent.com/1504756/109352528-d6f35780-782f-11eb-9f58-764ebfee84f7.png)

Per @omgitsbillryan: 

> All our alerts (especially nodes.rules) should have a purpose and/or deployment_name tag(s) that match their respective EC2 tag values. This would make future alert matching & routing much simpler. Would also be nice to see these immediately in the alert itself rather than having to search instance i-abcd... in AWS console to figure out what instance is being affected.

**Comment by jhouse-solvd** [comment]
We'll be creating some epics soon related to Datadog <-> PagerDuty integration, and this will be good to think about. Will likely move this content into that ticket and close this one out.

**Comment by ElijahLynn** [comment]
> We'll be creating some epics soon related to Datadog <-> PagerDuty integration, and this will be good to think about. Will likely move this content into that ticket and close this one out.

Thanks for the heads up!

**Comment by jhouse-solvd** [comment]
@ElijahLynn - datadog picks up the tags for EC2 instances automatically, so this will probably be a "freebie" as we build out our Datadog install. But, we will keep this ticket around to validate the desired behavior. (updated title)

**Comment by ph-One** [comment]
Now that we are on DataDog, we have confirmed to have these tags. Please reference https://github.com/department-of-veterans-affairs/va.gov-team/issues/28206 for related work (migrating prom rulesets to DataDog).
