### ISSUE TITLE
Loading screens to delete contact info

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20559]
## User story
As a user, I want to see a loading screen that tells me that the app is deleting my profile information.

## Acceptance Criteria
1. Upon selecting "Confirm" from the delete contact info mobile alert (#20334), display a loading screen while the app is working to delete the information. There will be 3 variations of this loading screen for address, phone, and email.
     - Pull in loading screen CC
     - Copy for deleting home address: "We're deleting your address"
     - Copy for deleting any phone number: "We're deleting your phone number"
     - Copy for deleting email: "We're deleting your email address" 

## Designs
Similar design:
![Screen Shot 2021-02-24 at 5.30.39 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/db434859-3a86-4c8f-954a-19f6608267ef)

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/12/2021 on Android and iOS.  Closing.
