### ISSUE TITLE
STEM Scholarship Automated Denial - Content Review

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#20551]
Booz Team is integrating the ability to automate the denial of select ineligible STEM Scholarship applicants.  Applicants can be automatically denied if they have too much of their Chapter 33 benefit remaining (More than 6 months) or if they self-report that they are not pursuing an eligible STEM degree (or have a STEM degree and are pursuing a teaching certification).  

2 items for you to review here
1. Content doc for claims status tool
2. Content doc for email to denied applicant

**Content doc for the Claims Status Tool is here:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content.md

For your reference, the prototype is here: https://bahdigital.invisionapp.com/share/G7IAG7A2XKD 
NOTE: Only the relevant criteria will appear under each "You did not meet" and "You met" headings, even though the prototype shows all possible items under each 

In addition, a brief email will go out to the denied applicant to direct them back to the site to check their status.  

**Content doc for the email is here:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-email-content.md

**Comment by peggygannon** [comment]
Hi, @amyknox will the Claim Status tool work be coming through the Collaboration Cycle?

**Comment by amyknox** [comment]
Great question! 

We need to connect with Mikki on IA / breadcrumbs and do the security review but it's all baked into the existing tool so we weren't planning to start the collaboration cycle over for this unless we had to.

**Comment by peggygannon** [comment]
Ok, thanks, @amyknox Agree, you might not need the full Collaboration Cycle reviews! 

With the launch of CC custom tracks last week, we're now asking teams to go through an asynch CC "kickoff" where teams will  answer questions to determine what level of support they'll need.   For the Claim Status Tool updates it sounds like you'll need content and I/A. By when you submit a kickoff ticket, we'll be able to confirm if anything else is needed. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md#questions-about-your-product

**Comment by amyknox** [comment]
@peggygannon - This effort is bit of a Frankenstein's monster WRT the collaboration cycle. We had some meetings in the old cycle and were in the middle of the our design process when the collaboration cycle relaunched.   

We are planning the Security & Privacy review, of course, and staging review.  Mikki is looking at the url & breadcrumbs.  So I think we're good with all that.  

Is it possible to give an ETA on the content review? FWIW, it's mostly drawn from STEM content which you've already reviewed. 

Thanks!

**Comment by shiragoodman** [comment]
Hi @amyknox. Under the new Collaboration Cycle enhancements that Peggy mentioned, we are no longer supporting one-off content reviews (or IA, or other practice areas). All of the support that our team provides will now be within the boundaries of the Collaboration Cycle. Would you want to set up a 15 min call and we can discuss the best approach? We still want to be able to provide support but have to be mindful of how we intake.

**Comment by amyknox** [comment]
@shiragoodman - yes, let's definitely have a quick call. I'll probably want to rope in my BA and PM, too.  When works for you?

**Comment by shiragoodman** [comment]
@amyknox my calendar is linked in my Slack profile and should be up to date!
