### ISSUE TITLE
CT Redesign: LP - Degree / Program Search - Solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20553]
Defiinition of Done: Document approaches to improve degree / program search functionality

Tasks
- [x] Explore possible ways to address the challenge on mobile devices 
- [x] Document approaches with greatest potential
- [x] Discuss pros/cons with UX team
- [x] Cascade potential solutions to desktop view
- [x] Discuss desktop solution with UX team

**Comment by amyknox** [comment]
Mural for solutions: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1614213424605/b2d28e86b6944d3e22809581f4fd3eecf51f31e6

**Comment by amyknox** [comment]
Solve for mobile first, get input and then work into desktop
