### ISSUE TITLE
22-0994 VET TEC benefit application content updates 

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#20550]
Legislation has changed.  Previously, applicants had to be Veterans to be eligible.  Now active-duty service members with 180 or fewer days to release from active duty are eligible for the VET TEC program. We're updating the content within the application to reflect this change.  

Updated content is on the "Military service" page of the application only.  You can find the updated content here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/vettec-0994/design/0994-content.md#chapter-title-step-2-of-7-military-service

**Comment by peggygannon** [comment]
Hi, @amyknox Please see content tweaks/recommendations below. 

Also, the static landing page will also need content tweaks with this new legislation:  https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/

You can work with the sitewide content team on updates to that page. Thx! 


-----


VET TEC is only available to Veterans or service members within 180 days of their release from active duty. Please consider submitting your VET TEC application when you're within 180 days of separating **from** service, or are no longer on active duty.

{ If date selected is 180 days or less from current date, display the following message}

We may contact you to verify that your **expected** release from active duty is ~~expected~~ within 180 days from this application's date ~~of this application~~. If we contact you, we may ask for a copy of your DD214 or a certification of your expected release date. You can request that certification from your Military Personnel Office.

~~As with all VA education benefits, an honorable discharge is required to be eligible for VET TEC.~~ You’ll need an honorable discharge to be eligible for VET TEC.  

{ end: if yes }

**Comment by amyknox** [comment]
@peggygannon - thanks for the input. To clarify, do you intend for the words you've bolded above to be bold in the application or is that just for emphasis in this ticket?

**Comment by peggygannon** [comment]
hi, @amyknox sorry about that! that was just for emphasis in the ticket so you'd see my recommendation more easily. 
Here's my recommendation for the intro content. I think we should break the sentence up into 2 bullet points for easier readability (bold here is what I'm recommending we bold for the application). 

**To be eligible for VET TEC, you need to be:**
-  A Veteran with at least one day of unexpired education benefits, **or**
-  A service member with 180 days or less left on active duty 
 You can complete the VET TEC application to see if you’re eligible for the program, even if you haven’t yet selected the training program you'd like to attend. [Learn more about the programs covered under VET TEC].

**Comment by amyknox** [comment]
_Thanks for the clarification on bolding, that makes total sense._ 

_Normally, I'd be fine with the bullets for eligibility but on this page, there's another bullet list that appears just above the eligibility criteria so want to double check this doesn't look too odd to you.  I should have put the whole content chunk in there the 1st go 'round to save us time! You can see it live in the [GH content doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/vettec-0994/design/0994-content.md#1prepare) and  [the VET TEC application intro](https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction)._  


**1. Prepare**

**To fill out this application, you’ll need your:**
- Direct deposit information
- Highest level of education
- Previous high-tech industry experience, if applicable
- Information about the training provider or program you want to attend (optional)

**To be eligible for VET TEC, you need to be:**
- A Veteran with at least one day of unexpired education benefits, or
- A service member with 180 days or less left on active duty

You can complete the VET TEC application to see if you’re eligible for the program, even if you haven’t yet selected the training program you'd like to attend. [Learn more about the programs covered under VET TEC]().

**What if I need help filling out my application?** An accredited representative, like a Veterans Service Officer (VSO), can help you fill out your application. [Get help filing your claim]().

**Comment by peggygannon** [comment]
Hi, @amyknox thank you for dropping that in here. Yes, I realize this would make another bullet list. Since this is new eligibility information, we should make this as clear and easy to find for users. My concern with putting this new eligibility information in one sentence is that users could overlook and not read it. Here is a screenshot below of a form intro page where we've used more than 1 bullet list. 

![2021-03-01 (1)](https://user-images.githubusercontent.com/17554224/109577753-fd70f700-7aaa-11eb-8f1f-3b38e15d4afb.png)

**Comment by amyknox** [comment]
Ok.  Thanks for sharing the screenshot.  I'm with you on wanting to make things clear & easy for applicants to find.  2 bullet lists it is!
