### ISSUE TITLE
BDD service history and validation error

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#20556]
when I'm on the military service history page disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history

with a service history of 

````
    "servicePeriods": [
      {
        "serviceBranch": "Army",
        "dateRange": {
          "from": "2001-08-27",
          "to": "2021-05-31"
        }
      }
````
and I click continue, nothing happens.  
If I click edit on the service history I see a validation error. But there should be no validation error because BDD allows for future discharge dates.

<img width="804" alt="Screen Shot 2021-02-26 at 4 40 53 PM" src="https://user-images.githubusercontent.com/19188/109358278-7ecd4d00-7851-11eb-93b4-746e2eab4dcd.png">

**Comment by Mottie** [comment]
Since this is occurring in the local dev environment, I'd say it's because the BDD feature flag is not enabled. Maybe it's about time to remove the feature flag?

**Comment by Mottie** [comment]
The check does need an update to make sure the page title matches this service end date behavior.

**Comment by annaswims** [comment]
yes, my mistake. The BDD feature toggle was not enabled locally.

**Comment by annaswims** [comment]
I still see this issue in prod. I resumed an old form, went back to the wizard and said I wanted to start a new form, chose BDD and still saw this:
![Screen Shot 2021-03-15 at 12 09 38 PM](https://user-images.githubusercontent.com/19188/111184671-901f9480-8587-11eb-8f24-9197745ee0f4.png)


Also, if I click back and then forward I see this - No visible error message but when I click on the "Continue" button nothing happens. 
![Screen Shot 2021-03-15 at 12 11 51 PM](https://user-images.githubusercontent.com/19188/111184777-af1e2680-8587-11eb-9642-3056ce12de85.png)

**Comment by annaswims** [comment]
We have a report from Barry of two veterans experiencing this bug in prod.

**Comment by Mottie** [comment]
I was hoping https://github.com/department-of-veterans-affairs/vets-website/pull/16228 would have fixed it... are there any more details about the error? Were they filling out a BDD? Did they restart the form at any point?

**Comment by annaswims** [comment]
I've forwarded an email with PII to your va email, @Mottie, but there's a screenshot from 3/24 where someone puts 5/9/2021  (46 days away) day in to the separation date for the navy.  

Is the problem that we arent' handling 0-90 days properly?  They should still be able to submit a standard claim from 0-90 days before discharge, right?

**Comment by Mottie** [comment]
Oh, I get it... when they are between 0 and 90 days, they aren't eligible for BDD, but the date is still in the future. Ok, I'll work on this today.

**Comment by Mottie** [comment]
Fix merged in, not sure if it made it in time for production build today
