### ISSUE TITLE
Access for Nick Walke

### ISSUE THREAD

**Issue by nwalke** [department-of-veterans-affairs/va.gov-team#2056]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Nick Walke
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Operations, DevOps Engineer, Oddball
- What is the **public** SSH key?
  >  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXA92+0M2i6xl1zJ+hmwerwrrGc2fKoU4M02DAXtfIYYfnENBN9DOlGtw82X7rJwTsNmhMI51SOFbkLtdziVnCNdIL/MN64ZgAJrR/E+pDt39rMMWl1kSlkMfTg1fBX15z4/BafirDm+0GD2lYxI7yBFPcCct3FkyzL0LJj4ebH7eTnVYUZtfmqZYeHrixUFDv2oGwYt09LEuRmiAxGGhiEk2YDVtA7btH76f+I8sw7shd+3kIWdF6d3XmNbJBcAKHStcKJ8TPxfUaeAFpzgBrE9xcHaCgeDkFLA1XDNJoc2uwALHV8w0+7M0T3oqdTd4Sl0BszjmZIgYz0HCLE/iV nick@oddball.io

- [Grant AWS Console access?]
  > YES

**Comment by nwalke** [comment]
@department-of-veterans-affairs/vsp-operations ^

**Comment by ricetj** [comment]
@Jeff-Hayter
COR: Yourself
User: Nick Sprinkle

**Comment by Jeff-Hayter** [comment]
@ricetj Confirmed, please grant AWS access.
