### ISSUE TITLE
Access for Tze-chiu Lei (VSA Engineering Support)

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#2057]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Tze-chiu Lei
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Engineering Support -- Team Lead Joe Costa (jcosta@governmentcio.com);
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > [SSH public-key already set up]

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by tlei123** [comment]
Hi, @department-of-veterans-affairs/vsp-operations!  Please grant me AWS access, per info provided in Description above.  Thanks much!

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Tze-chiu Lei

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS access.

**Comment by ricetj** [comment]
@tlei123 do you still need AWS access?

**Comment by tlei123** [comment]
> @tlei123 do you still need AWS access?

Yes, TJ.  I still need AWS but still waiting on VA Onboarding and basic VA network access upstream.  

If you prefer to Close this tic and Open a new one when my onboarding's all done.  Feel free to do so.
