### ISSUE TITLE
STEM Automated Denial:  IA Check-in	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20572]
## Definition of Done
Breadcrumbs & URL for STEM AD details page are confirmed with VSP IA	

## Tasks
- [x] Discussion with DEPO IA Resource about work
- [x] Respond to any questions

**Comment by amyknox** [comment]
VSP Issue: IA Request: Booz Team - STEM Denial in Claims Status Tool#20656

**Comment by amyknox** [comment]
IA to be addressed at Midpoint Review, if not sooner.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/20726
