### ISSUE TITLE
STEM Automated Denial: Prototype Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#20571]
## Definition of Done
STEM AD protototype has been updated with VSP input	

## Tasks

- [ ] Prototypes are updated to incorporate VSP input on content & IA

## Assets 

Content Doc -  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content-V2.md

Content doc for Claims Tool  - word version with VSP changes tracked. [https://app.zenhub.com/files/133843125/fa17b60e-c8fd-42aa-a343-d2c5330fdea0/download](https://app.zenhub.com/files/133843125/fa17b60e-c8fd-42aa-a343-d2c5330fdea0/download)

Accessibility feedback  https://github.com/department-of-veterans-affairs/va.gov-team/issues/21058 to make sure accessibility issues are addressed.

Prototype v1 - https://bahdigital.invisionapp.com/d/main#/projects/prototypes/14222481

**Comment by amyknox** [comment]
@watersemma - The content assets for STEM AD updates are complete so this story is ready when you are.

**Comment by watersemma** [comment]
STEM AD prototype is updated. Content changes and accessibility feedback have been incorporated. (v1.2) Take a look here: https://bahdigital.invisionapp.com/share/U5IAGCMFH7R

**Comment by amyknox** [comment]
**Need help? links styling per DEPO...**  
Given the accessibility issues with labeling it as an H3 tag, just make it the H2 and apply that css class as we discussed. And then sub headings would be H3 (although in reality they should visually be H4). We really should have css classes for this. And they should be named better, like H3-styles and H4-styles. Then you could code it as an H2 and just apply that style. But that isn't my department. : (
<H2 class="H3-styles">This is my section</H2>
     <H3 class="H4-styles">This is my subsection that belongs inside the section</H3>

**Comment by amyknox** [comment]
@watersemma - a couple more updates to the sidebar per QA. Per [design.va.gov](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers), the phone numbers shouldn't have a 1 in front of them unless they're international. Formatting as follows 

**Veterans Crisis Line:** 
800-273-8255 and select 1

**Education Call Center:**
888-442-4551 (inside the U.S.)
+1-918-781-5678 (outside the U.S.)
