### ISSUE TITLE
Janssen (J&J) COVID-19 vaccine content updates: Translation coordination

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#20596]
## Issue description
Coordinate translation of updates with translation vendor and QA check with VHA volunteer translation team.

Translation needed for:
- Spanish (priority - expedited/asap request)
- Tagalog (quick 2nd priority)

## Related documents

- Will post final content doc with changes once available

---
## Tasks
- [x] Send English content doc (with changes highlighted) to translation team with request for expedited turnaround (priority - Spanish first) (Randi)
- [ ] Build out rest of translation workflow tickets (Randi/Sharon)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht This coming week is going to have a large volume of fast-paced changes due to building out translation of COVID-19 vaccine page + the new Janssen (J&J) vaccine approval and relevant messaging. I'm setting up tickets to make sure we're ready. I created this one for the initial translation coordination. Please feel free to adjust this, and build out the associated tickets for the implementation work. Thank you!

cc @SKasimow for awareness.

**Comment by DanielleThierryUSDSVA** [comment]
[Janssen vaccine page updates for translation_03.02.21](https://app.zenhub.com/files/133843125/3da68724-318e-4bfa-b5d1-8bf3f8f27b73/download)

@RLHecht Here's the doc for the translation team. Let me know if you think this approach works!

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Closing as I think this has all been completed (but lmk if not the case).

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht can you confirm?

**Comment by RLHecht** [comment]
Yep, this is good to close. The rest of this work was completed in other tickets. Thanks!

**Comment by SKasimow** [comment]
Thanks!
