### ISSUE TITLE
Add blank columns w/suggested outcomes data to track

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#206]

**Comment by rroueche** [comment]
# User Story
As a product owner, I need access to business outcomes data about my tool so I can understand if it's improving the Veteran experience, and if not, can prioritize iteration.

# Goal
Include in the Google Sheets MVP suggested outcomes to track in Education space - they can be blank since we probably don't actually have access to this data. But the hypothesis is that by calling out what we *want* it will help Edu and us be able to *get* it.

# AC
- [ ] Google Sheets MVP includes 1-2 outcome and/or KPI-related metrics (even if the data is blank)

**Comment by joanneesteban** [comment]
Considerations:
- [ ] Easy to interpret (/define terms, provide context)
- [ ] Outcomes data should be actionable for product teams
