### ISSUE TITLE
Email and text message notification guidelines

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/va.gov-team#20603]
The design of email templates is now part of the design system - https://design.va.gov/patterns/email_template

We would also like to add some basic content guidelines for email and text message notifications. I've created a draft we would appreciate input on. https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/design/content-guidelines.md

**Comment by shiragoodman** [comment]
hey @toddstanich  - is this in support of the new self service UI your team is looking into?

**Comment by toddstanich** [comment]
@shiragoodman not specifically related to the self service UI. When we worked with the design system team to add the email template to the design system, we briefly discussed adding some content guidelines to the documentation site. This is following back up on that.

**Comment by shiragoodman** [comment]
@toddstanich thank you for the info! That's helpful.

**Comment by peggygannon** [comment]
Hi, @toddstanich Below is recommended content guidance for notifications. Please let me know if you have any questions about my recommendations. 

You might also want to get feedback from Danielle and Beth on this guidance as well.  

[https://app.zenhub.com/files/133843125/24003f4b-b456-4a0b-ad06-8dcf02870fef/download](https://app.zenhub.com/files/133843125/24003f4b-b456-4a0b-ad06-8dcf02870fef/download)
