### ISSUE TITLE
Collaboration Cycle Kickoff | Translations | C&L Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20611]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [x] VFS: Attach any available artifacts.
- [ ] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [ ] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11599

- Link to wireframes, mockups, or prototypes

Example: https://design.va.gov/storybook/?path=/docs/components-select--default

- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

**Will your work result in visible changes to the user experience?**
- [x] Yes
- [ ] No

**Is your work a new product/feature or an iteration to an existing product/feature?**
- [ ] New
- [x] Iteration

**Will your work impact only static content pages?**
- [x] Yes
- [ ] No

**Are you making changes to the visual design?**
- [x] Yes
- [ ] No

**Are you making changes to content?**
- [ ] Yes
- [x] No

**Are you making a change to the user flow?**
- [x] Yes
- [ ] No

**Are you making a change to urls, navigation, or entry points?**
- [x] Yes
- [ ] No

**Are you doing research with VA.gov users?**
- [x] Yes
- [ ] No

**Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?**
- [x] Yes (should be available by 3/5)
- [ ] No

**If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?**
- [x] Yes
- [ ] No

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @SKasimow. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, we are recommending the following Collaboration Cycle touchpoints:

- Design Intent
- Information Architecture (IA) Request
- Analytics Request
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch:

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

The following practice areas will be included throughout the Collaboration Cycle process:

- Design
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our [Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) page for next steps.

**Comment by shiragoodman** [comment]
hey @SKasimow  - since this is an urgent request due to COVID, my prior comments on this ticket is not applicable. Please do whatever you need to get your product launched. Thanks!

**Comment by SKasimow** [comment]
@shiragoodman Thanks Shira.

**Comment by SKasimow** [comment]
@johnhashva @brianalloyd Hello! Adding you in for reference. The new nav menu was just launched today :)

**Comment by SKasimow** [comment]
@shiragoodman Hi Shira,

Just wanted to let you know we have decided to do some usability testing for this effort; I've updated the ticket to reflect this.  Sharon
