### ISSUE TITLE
STEM AD: Remove stem degree / teaching certification from automated denial process consideration

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20616]
As a developer, I need to remove the STEM degree and certificate questions from the automated denial process so that the denials are accurate due to a change in the eligibility criteria.

## Assumptions:
1. Completed behind feature flag `stem_automated_decision` (#13829)
2. This is temporary until the updated eligibility criteria is added to the form.

## Acceptance Criteria:
1. An automated denial is ONLY processed when the applicant has > 180 days of entitlement remaining.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6050

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/tests/view/80535)
