### ISSUE TITLE
DebtRes FSR -Create alert for submission failed 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#20623]
Create an alert for failed submit of FSR form

- save in progress will save the form, Veteran can come back at a later time to submit 
Once alert is created a FE ticket needs to be made to implement

**Comment by rileyorr** [comment]
[Added the alert to UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138809468/simulate/sitemap?mode=i) and reached out to Craig to confirm that the form will save even if submission fails. 

@troyriser can you do a quick content spot check before I create a frontend ticket? I based the content off [the design system's error message suggestions](https://design.va.gov/patterns/messaging-error-messages). Thank you!

**Comment by rileyorr** [comment]
[Added a ticket for frontend implementation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24933).
