### ISSUE TITLE
Decide How to Handle Long Veteran Names

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#20626]
Lighthouse's HLR API<sup>1</sup> has fairly small character limits for Veteran name fields.
During the [spike in failed HLR API requests](https://dsva.slack.com/archives/C5AGLBNRK/p1614265801040800?thread_ts=1614264914.038800&cid=C5AGLBNRK) that happened on 2021-02-25, a couple of the failed requests were because a Veteran's name was too long.

How do we want to handle this? Automatically truncate the name?

`Eddddddddddddd` -> `Edddddddddd.` ?

or maybe: 

`Eddddddddddddd` -> `Edddddddd...` ?

The restrictions on Veteran names right now:

```
first name
  max length of 12 characters
  no min length --can be blank or empty

middle name
  not required

last name
  max length of 18 characters
  must be non-blank
```
([schema](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/b6f33f49e6d476d8eb348c68efda7d9d2c654eb9/src/schemas/HLR-create-request-headers/schema.json))

Technical Note:
I don't believe we're currently using the schema linked above. The name stuff is all handled [here.](https://github.com/department-of-veterans-affairs/vets-api/blob/8a5ff67dbb80b0c7d3a8f7587aa2f9fa5e50a388/lib/decision_review/service.rb#L87)
## Acceptance Criteria

- [x] Decide how to handle long veteran names
- [x] Update [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20627) with decision

### Footnotes

_1.  [the API](https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current) we call to create HLR forms and submit them to CentralMail as [a pdf](https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf)._

**Comment by edmangimelli** [comment]
not sure what to put for estimate

**Comment by vhenry07** [comment]
Decision made to include as many characters as possible even if name gets truncated, as we already send other unique identifiers.
