### ISSUE TITLE
Implement -> #20626 Decide How to Handle Long Veteran Names

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#20627]
## Acceptance Criteria
- [ ] Implement whatever was decided in https://github.com/department-of-veterans-affairs/va.gov-team/issues/20626 (better error message, automatic truncation, etc.)

**Comment by edmangimelli** [comment]
@annaswims would you mind estimating this one (after #20626 is complete ? idk)

**Comment by vhenry07** [comment]
Decision made to include as many characters as possible even if name gets truncated, as we already send other unique identifiers.

**Comment by edmangimelli** [comment]
Spoke with @annaswims about this one and she suggested we get LH to do this truncation (and we change our schema to allow any length characters). This makes the most sense in the long run. LH will eventually be doing auto-establishment/sending structured data, so this schema change is inevitable. It would be easiest for both parties to make the schema more permissive now and let LH handle adding and removing the truncation. If _we_ handle the truncation, it sets us up for a silent bug: LH changing their schema without us knowing, and we truncate needlessly indefinitely.
Will speak to LH about this.

**Comment by edmangimelli** [comment]
temporary fix 

> because this is affecting veterans right now, gonna put some truncation code in our back end immediately which we can roll back depending on what LH wants to do
> cc @annaswims

temporary fix PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6107

**Comment by edmangimelli** [comment]
[conversation with LH](https://lighthouseva.slack.com/archives/CJD573TMZ/p1615300605013800)

**Comment by edmangimelli** [comment]
temporary fix deployed

**Comment by edmangimelli** [comment]
this problem affected 3 veterans (from initial launch (50%) to now)

**Comment by edmangimelli** [comment]
[It doesn't seem like LH wants to](https://lighthouseva.slack.com/archives/CJD573TMZ/p1615303798016400?thread_ts=1615300605.013800&cid=CJD573TMZ) tackle [this.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20627#issuecomment-793966558)

I was going to spin up a ticket to continue the conversation with LH, but I think they're passing on this (which is fine).

cc @vhenry07 @annaswims

**Comment by annaswims** [comment]
👍 Ronnie and I aren't cool enough to have an invite to lighthouse slack.
