### ISSUE TITLE
Analytics Implementation | C&L Team | Menu Option for Translated Content

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20634]
# Google Analytics Implementation

## What this form is for

We are publishing the Covid-19 Vaccine page in both spanish and tagalog and so we need to add a menu option on the english page to allow users to choose a language.

English page: https://www.va.gov/health-care/covid-19-vaccine/ 
Spanish page: https://www.va.gov/health-care/covid-19-vaccine-esp/
Tagalog page: https://www.va.gov/health-care/covid-19-vaccine-tag/<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics
- Who is this request for?
 @SKasimow @DanielleThierryUSDSVA 
- What team/project is this work for?
Content and Localization Team (C+L)
Covid Vaccine - spanish and tagalog versions
Corona FAQ - addition of tagalog page
- Provide the Domain where Google Analytics needs to be implemented
Va.gov

    _Identify if PII is passed in URL or title tag_
    
No 
- Please provide any upcoming deadlines or important milestones
ASAP -  Congressional request and page for Covid-19 Vaccine will go up this week
   - Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
The URLs for spanish and tagalog versions have been requested from I/A and will add here as soon as they are available.
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
We are adding a choice of either english, spanish of tagalog from each version of the Covid-19 page and need tracking for this new component (which will be built in React).

Additionally the "Stay Informed" widget near the top of the Covid-19 Vaccine page is also being translated and will need tracking.

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by bmcgrady-ep** [comment]
Hi @SKasimow - Here are the developer requirements for the analytics implementation of these pages.

For the Tagalog and Spanish pages, please have your developer implement the same Data Layer that is on the English page (just as was done with the Spanish Covid FAQ page).

For the **Stay Informed** button tracking: 
![image](https://user-images.githubusercontent.com/66263904/110389562-f0f81b80-8021-11eb-974b-6734fc5da335.png)
The following dataLayer should be added when a user clicks on the button:
```
dataLayer.push({
  event: 'cta-button-click',
  button-type: 'default',
  button-click-label: 'Go to the chatbot',
  button-background-color: 'rgb(7, 56, 101)' //pass in the color of the button
})
```

As for the menu, can you please send over a staging link when the functionality is built out? Thank you!

**Comment by SKasimow** [comment]
@bmcgrady-ep - thanks Ben!

@youngfreezyVA

**Comment by bmcgrady-ep** [comment]
@SKasimow @youngfreezyVA Here is a Data Layer code to implement for the menu:
![image](https://user-images.githubusercontent.com/66263904/111523709-fd6f2900-8731-11eb-9987-d944a5dcf0cd.png)
```
dataLayer.push({
  event: 'nav-pipe-delimited-list-click',
  pipe-delimited-list-header: 'English'
})
```

Also, I'm not seeing any events coming into va.gov for CTA button clicks
![image](https://user-images.githubusercontent.com/66263904/111526302-f39af500-8734-11eb-860a-4a1f30e338ee.png)

**Comment by SKasimow** [comment]
@youngfreezyVA - Analytics feedback

**Comment by SKasimow** [comment]
@youngfreezyVA will this be completed in current sprint?

**Comment by youngfreezyVA** [comment]
it was already completed

**Comment by jonwehausen** [comment]
Hi @youngfreezyVA , 

Thank you very for your work here. We greatly appreciate it. 

After reviewing, it looks like the DL variable for `pipe-delimited-list-header` was implemented as camel case `pipeDelimitedListHeader`. Would you be able to adjust this variable to be hyphenated case? 

In addition, it looks like the DL variable is not populating with the correct language the user selects from the pipe delimited list. We apologize if this wasn't communicated clearly [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20634#issuecomment-801349386)

Please see QA results below: 

| Description of Interaction | Data Layer Screenshot | Test Status 
| -- | -- | -- | 
Click on "Espanol" from `https://www.va.gov/health-care/covid-19-vaccine/` | ![image](https://user-images.githubusercontent.com/48527022/113638449-df1b8f80-9644-11eb-957c-1d48722cce3b.png) | ⚠️ **DOES NOT PASS**
Click on "English" from `https://www.va.gov/health-care/covid-19-vaccine-esp/` | ![image](https://user-images.githubusercontent.com/48527022/113638520-096d4d00-9645-11eb-93d8-2c86720a0e0a.png) | ⚠️ **DOES NOT PASS**
Click on "Espanol" from `https://www.va.gov/health-care/covid-19-vaccine-tag/` | ![image](https://user-images.githubusercontent.com/48527022/113638612-42a5bd00-9645-11eb-88e0-8ee70ae842be.png) | ⚠️ **DOES NOT PASS** 

@SKasimow For you awareness, despite these test results, we maintained enough context passed to the event as to still have an understanding of which language users have toggled to -- that said, we will still want to get the items identified above corrected. Thanks so much.

**Comment by jonwehausen** [comment]
Hi @youngfreezyVA , 

Great thank you! We greatly appreciate your help here. I see in your PR it looks as though you also noted there is a need to adjust the language that DL variable is populating with, thank you 👍 

Great question -- and yes agree it's uncommon to use kabab. We've been using it even before my time, so don't know the true origin but from my experience it does allow us to 1) more easily find our events in code and differentiate from other code 2) permit readability within Google Analytics for non-tech users

**Comment by SKasimow** [comment]
@jonwehausen Thanks for checking this Jon!

When I go into GA to pull analytics on menu usage, I assume I want to look at events and then what else do I need to specify to get clicks for each lang?

**Comment by jonwehausen** [comment]
### QA Testing

@youngfreezyVA Thank you for your correction here, very much appreciate it! 

Please see QA results below: 

| Description of Interaction | Data Layer Screenshot | Tag Screenshot | Test Status 
| -- | -- | -- | -- | 
Click on "Espanol" from `https://www.va.gov/health-care/covid-19-vaccine/` | ![image](https://user-images.githubusercontent.com/48527022/114766548-875fe100-9d34-11eb-8969-0337835bfdea.png) | ![image](https://user-images.githubusercontent.com/48527022/114766589-95adfd00-9d34-11eb-826a-84f8756d1210.png) | ✔️ ✔️ **PASS**
Click on "Tagalog" from `https://www.va.gov/health-care/covid-19-vaccine/` | ![image](https://user-images.githubusercontent.com/48527022/114766681-b24a3500-9d34-11eb-9c15-fe97cb2dbe5b.png) | ![image](https://user-images.githubusercontent.com/48527022/114766713-bbd39d00-9d34-11eb-810d-433bb14b88a9.png) | ✔️ ✔️ **PASS**
Click on "English" from `https://www.va.gov/health-care/covid-19-vaccine-tag/` | ![image](https://user-images.githubusercontent.com/48527022/114766831-e45b9700-9d34-11eb-8235-ee6b878d48bc.png) | ![image](https://user-images.githubusercontent.com/48527022/114766874-f2111c80-9d34-11eb-8271-371a8128598d.png) | ✔️ ✔️ **PASS**

------------------
Hi @SKasimow , 

Great question -- You can find all of the click events for the respective languages [here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210326&_u.date01=20210413&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22.*covid-19-vaccine.*%22,0%5D%5D&explorer-table.rowCount=50&_r.drilldown=analytics.eventLabel:nav-pipe-delimited-list-click). Something to note here, as mentioned prior before @youngfreezyVA 's fix, we were missing the `en`, `tl` and `en` values within the `Event Action` so for historical data (before the fix), you'll just want to look at the page path to determine which language was clicked on (the same goes for ones where it's the full name of `Espanol`, `Tagalog` or `English`. Best rule of thumb if you want to quickly total all new+old events for each language would be looking at the page path. Moving forward, we'll start to only see the events with the two letter language abbreviation and the old events will fade away. 

Hope this helps and please do let us know any other questions you may have. We will close this ticket but please feel free to reopen should you have any other questions or reach out on `#vfs-platform-support`. Thanks!
