### ISSUE TITLE
CLP Bug - Preview-page Events section are missing description-paragraphs below event-titles.

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#20631]
## Issue Description
_During QA testing it was identified that preview-page Events section are missing description-paragraphs below the event-titles_

Need to map one sentence descriptive text under each of these seen here.

<img width="722" alt="Screen Shot 2021-03-01 at 3 40 39 PM" src="https://user-images.githubusercontent.com/70410912/109568728-8d5f7280-7aa4-11eb-965a-251a1b29d1b9.png">

[Slack Convo](https://dsva.slack.com/archives/C52CL1PKQ/p1614625740099800)

## Front end tasks
- Estimate ticket and remove 'needs grooming' label 
- Should be a brief text description under each of those Event "teasers"
- Determine if FE work or CMS. 

## Acceptance Criteria
- [x] Follows design intent
- [x] brief text description under each of those Event "teasers"
- [x] tested and validated in CMS preview

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
We have the option to use `fieldBody`, `fieldDescription`, or `fieldIntroText` here. Originally we were using `fieldBody`:

![image](https://user-images.githubusercontent.com/12773166/109673879-af540600-7b33-11eb-9f37-88d01ec371c2.png)

However, we determined that it was too long. So then we started using `fieldDescription`. However, now we're noticing that `fieldDescription` comes back `null` for one of the events chosen for the Mission Act CLP. Which field should we be using? CC @kevwalsh @johnhashva

**Comment by johnhashva** [comment]
@kelsonic noticing the same thing.  That's the right meta-field -- but as I'm testing this finding some weirdness so will schedule a show and tell with you.

**Comment by brianalloyd** [comment]
@kelsonic just checking on the status of this ticket, little lost on the comments, is this ready to be validated?  Thanks.

**Comment by kelsonic** [comment]
I believe John decided on using the `fieldDescription` field, so we should be all set since it's already implemented to support that! 🙂

**Comment by brianalloyd** [comment]
Thanks @kelsonic closing out in support.
