### ISSUE TITLE
Products Used Discovery Adjustments

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#2064]
## User Story
As a implementation specialist with the intention of reaching self-service, I would like a global framework of identifying the product being used in GTM. 

There is already a product in place, but would like to revisit to align more closely with new products. 

## Goals
- Establish a framework to scale the product used across the application
- Align more closely with product documentation

## Acceptance Criteria
- [ ] Revamp lookup tables to more closely align with product identifications
- [ ] Make necessary changes to scale across the application
- [ ] Document how this will be used by future teams

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
## Strategic Results

Via @jonwehausen : Updating this implementation gives us a more comprehensive view on how veterans are engaging with various product areas. This sprint - we validated Google Tag Manager to accurately reflect the most up-to-date URLs on the platform leveraging  product directory documentation. In the future (like in the VBA example we saw) when someone comes to us with the question of -- "What product areas areas are experiencing the most traffic / growth?" , this is a functionality that we can confidently lean-on for that information.

**Comment by joanneesteban** [comment]
@bsmartin-ep and @jonwehausen to regroup on this on 3/25.

**Comment by bsmartin-ep** [comment]
@jonwehausen  -

I've updated the workspace to include our changes to the Product Index and Product Areas:

https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-WFJWBD&check_preview_status=1&gtm_auth=etDo92NYjodl51tKG-KZjA&gtm_preview=env-807&gtm_debug=x

Two questions....

1.  Should the _Disability_ Product Area be used anywhere?  _/disability/_ pages are tracked in the _Benefits_ Product Area right now.

2.  Should the actual facility pages (ex https://www.va.gov/directory/guide/facility.asp?id=6415) be tracked as in _Product Used - Facility Locator (13)_ dimension?

**Comment by jonwehausen** [comment]
@bsmartin-ep Changes have been QAed and look great, we should be ready to publish. 

@joanneesteban who would you recommend to engage with as a product SME that can quickly go thru our configuration and verify we are not missing any relevant URLs to each product.

**Comment by bsmartin-ep** [comment]
@jonwehausen - The discussed changes should be ready in the workspace.  I had a question about the Disability CS below.

#### Product Used - Index

> **Changed:<br>**
> ^/letters.\* --> ^/records/download-va-letters.\*<br>
> ^/facilities.\* --> ^/(facilities|find-locations).\*<br>

-------

### Product Area Used - Benefits

> **Added:<br>**
> ^/claim-or-appeal-status.*

-------

### Product Area Used - Disability (new)

> **Added:<br>**
> ^/disability.\*<br>
> ^/claim-or-appeal-status.\*
> 
> (Note:  this was added to the GTM base config as custom dimension 32 - Product Area Used - Recommendations Health Care.  @jonwehausen  - Remove "Recommendations" from name?)
> 

-------

### Product Area Used - Education

> **Added:<br>**
> ^/careers-employment/vocational-rehabilitation.*

-------

### Product Area Used - Other

> **Added:<br>**
> facility\.asp\?id=  (example: www.va.gov/directory/guide/facility.asp?id=682)
> ^/facilities.\*
> 
> **Removed:<br>**
> ^/facilit.* (no longer matching anything)
> 
> **Changed:<br>**
> ^/records/download-va-letters.\* (removed slash)
>

**Comment by jonwehausen** [comment]
@bsmartin-ep I updated the custom dimension index within GA and GTM for "Product Area Used - Disability" to be 63 -- this was a previously unused index.

**Comment by jonwehausen** [comment]
@joanneesteban Changes have been published out. 

Opened #7988 as what we're proposing to repurpose this functionality in the future as a much more simplified and efficient solution.
