### ISSUE TITLE
Resolve issue with failing Nightwatch test

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#20649]
[Reference Jenkins for more details regarding failure.](http://jenkins.vfs.va.gov/job/testing/job/vets-website-integration-testing/)

> 08:03:11  FAILED:  1 assertions failed and 17 passed (15.717s)
08:03:11  
08:03:11   _________________________________________________
08:03:11  
08:03:11   TEST FAILURE:  1 assertions failed, 17 passed. (1m 6s)
08:03:11  
08:03:11   ✖ applications/pre-need/tests/00-all-fields.e2e.spec
08:03:11  
08:03:11     - Begin application (15.717s)
08:03:11     Timed out while waiting for element <.autosuggest-item> to be present for 5000 milliseconds.  - expected "found" but got: "not found"
08:03:11         at Object.completeBenefitSelection (/application/src/applications/pre-need/tests/preneed-helpers.js:140:6)
08:03:11         at beginApplication (/application/src/applications/pre-need/tests/00-all-fields.e2e.spec.js:88:15)
08:03:11         at Object.BeginApplication [as Begin application] (/application/src/platform/testing/e2e/helpers.js:106:7)
08:03:11  
08:03:11  npm ERR! code ELIFECYCLE
08:03:11  npm ERR! errno 1
08:03:11  npm ERR! vets-website@1.0.1 nightwatch:docker: `nightwatch -c config/nightwatch.docker-compose.js --suiteRetries 3 "--tag" "integration"`
08:03:11  npm ERR! Exit status 1
08:03:11  npm ERR! 
08:03:11  npm ERR! Failed at the vets-website@1.0.1 nightwatch:docker script.
08:03:11  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
08:03:11  
08:03:11  npm ERR! A complete log of this run can be found in:
08:03:11  npm ERR!     /application/.npm/_logs/2021-03-02T13_03_11_364Z-debug.log

**Comment by billfienberg** [comment]
![image](https://user-images.githubusercontent.com/6130520/109726471-6a9e8e00-7b78-11eb-97ee-d3d1afc9d58e.png)

I see the following error when manually reproducing the test*:

>`Error Please select an option from the suggestions`

*I wasn't running the API locally at the time of testing.

**Comment by billfienberg** [comment]
It looks like the `v0/preneeds/cemeteries` endpoint is 503-ing on staging. 

![image](https://user-images.githubusercontent.com/6130520/109830536-32449180-7c04-11eb-9d91-a7ceab801234.png)

https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/burial-benefits

>`staging-api.va.gov/v0/preneeds/cemeteries:1 Failed to load resource: the server responded with a status of 503 (Service Unavailable)`

**Comment by billfienberg** [comment]
![image](https://user-images.githubusercontent.com/6130520/109832035-9c116b00-7c05-11eb-94be-13665e39c685.png)

>`{"errors":[{"title":"Service unavailable","detail":"An outage has been reported on the Preneeds since 2021-03-03 15:47:53 UTC","code":"503","status":"503"}]}`

https://staging-api.va.gov/v0/preneeds/cemeteries

Search results for `cemeteries` in `vets-api`: https://github.com/department-of-veterans-affairs/vets-api/search?q=cemeteries

**Comment by billfienberg** [comment]
The cemetery dropdown works on prod. 

![image](https://user-images.githubusercontent.com/6130520/109844945-3d062300-7c12-11eb-9cc5-8e2e65fc18b8.png)

**Comment by billfienberg** [comment]
## Lower Environments (Dev) have the same problem

![image](https://user-images.githubusercontent.com/6130520/110001384-f419a180-7cd9-11eb-8a49-079ea83b8a2f.png)

https://dev-api.va.gov/v0/preneeds/cemeteries

## Links

- [Slack thread in vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1/p1614787206037100)
- [Potentially relevant Sentry error](http://sentry.vfs.va.gov/organizations/vsp/issues/14878/?environment=staging&query=is%3Aunresolved+cemeteries&statsPeriod=14d)

**Comment by pjhill** [comment]
## Tasks
- [ ] Disable cemetaries endpoint test
- [ ] Create a support ticket assigned to BE Tools with the aim to have BE Tools team pursue the longterm fix for the endpoint

**Comment by billfienberg** [comment]
It looks like the [Daily Accessibility tests](http://jenkins.vfs.va.gov/job/testing/job/vets-website-integration-testing/) have been green since 2021-03-18. 

![image](https://user-images.githubusercontent.com/6130520/112183248-106b7880-8bcc-11eb-8d1d-09398c7e1a5d.png)

**Comment by billfienberg** [comment]
> Create a support ticket assigned to BE Tools with the aim to have BE Tools team pursue the longterm fix for the endpoint

Support ticket labeled with `tools-be`: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21943
