### ISSUE TITLE
Analytics Implementation: Authenticated Experience - Direct deposit for education GA dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#20652]
# Metrics Reporting Request

## Description
Who is this request for?

Authenticated Experience - Direct deposit for education GA dashboard.

Original tracking details are in #19334.
    
- What type of analytics support are you looking for?

Putting the direct deposit for edu analytics into a GA dashboard. This dashboard can be similar to the existing [GA dashboard for direct deposit for comp & pen](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/), though there are some key differences for direct deposit for edu because we don't track all the same metrics as we do for comp & pen. This is what we are looking to track (and what tracking was implemented for in #19334):

- % of successful direct deposit for edu retrievals
- % of successful direct deposit for edu saves/submissions
- Clicks to the "Edit" link for direct deposit for edu
- If possible, error keys like we have on the direct deposit for comp & pen dashboard
- Clicks to "View your payment history"
- Top searches from the profile (this is so we can see if the searches for "direct deposit" reduce or remain high)

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

We are looking to have this dashboard ASAP. We're sorry for the last minute request — we thought a dashboard would be part of the request in 19334, but it was not clear that was only for tracking.

## Analytics to Track Down

See above.

## Which Product Questions are you trying to answer?

- Overall health of feature
- How much user interaction the feature gets
- Whether adding direct deposit for edu to the profile reduces searches for "direct deposit" from the profile

## Link to Metrics

N/A

## Additional Comments

N/A

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by Samara-Strauss** [comment]
Estimated delivery of the dashboard is some time during the week of 3/8. [Slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1614976624226100?thread_ts=1614976223.225800&cid=C909ZG2BB)

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - [Here](https://analytics.google.com/analytics/web/template?uid=g34XitqpSLuplLvX007szQ) is the GA dashboard for Edu Direct Deposit User Interactions.

One thing that I will note: There currently is no distinguishment between View Payment History link clicks for EDU and CNP. There are two solutions for tracking this. The first solution would be to implement tracking in the Data Layer for the View Payment History link clicks. The second solution would be a custom segment. I created a custom segment that would only show the events that happen for sessions with EDU profile logins. 

If you want to go the Data Layer route, then a developer would need to implement the following Data Layer on View Payment History Link clicks:![image](https://user-images.githubusercontent.com/66263904/110817511-9ccf8000-8249-11eb-90ec-450167784b5d.png)

**For EDU Profiles**
```
dataLayer.push({
  event: 'profile-navigation',
  profile-action: 'view-link',
  profile-section: 'edu-view-payment-history'
})
```

**For CNP Profiles**
```
dataLayer.push({
  event: 'profile-navigation',
  profile-action: 'view-link',
  profile-section: 'cnp-view-payment-history'
})
```

**Comment by Samara-Strauss** [comment]
> One thing that I will note: There currently is no distinguishment between View Payment History link clicks for EDU and CNP. 

That's because unlike direct deposit, all payment types are tracked in the same place regardless of what benefit they're for. So, there's no need to distinguish between payment type here. I mostly included the View Payment History link here for convenience-sake, even though it is also on the comp & pen dashboard.

<img width="670" alt="Screen Shot 2021-03-11 at 11 33 28 AM" src="https://user-images.githubusercontent.com/34068740/110821037-aebb1e00-825d-11eb-8678-41e714c88258.png">

Question — which view should I select? All VA.gov? WBC only?

**Comment by bmcgrady-ep** [comment]
Okay, thank you for clarifying. Please use the All VA.gov View.

**Comment by Samara-Strauss** [comment]
Awesome, thank you! I'm in!

Two things:

1. I am not seeing sections for successful saves/submissions and failed saves/submissions, which were part of the original request. Can you add those?
2. Question: I just set up the dashboard about 2 minutes ago, but we did have 1 successful UAT participant around 11:30 ET today that accessed this feature in production. However, I am not seeing successful retrieval data (the system successfully retrieved his info) or clicks to the edit link (he clicked this a couple of times) showing up on the dashboard. Is this indicative of a problem, or is this because I hadn't finished setting up the dashboard yet?

<img width="1280" alt="Screen Shot 2021-03-11 at 1 53 38 PM" src="https://user-images.githubusercontent.com/34068740/110839977-2eeb7e80-8272-11eb-9630-d8a35eb21020.png">

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - I made a few updates to the dashboard, but also make sure that the date range is set to today's date (March 11th).

Let me know if this helps.

**Comment by Samara-Strauss** [comment]
Ah, silly me! You're right — part of the problem was that the date range didn't include today. Totally forgot that's the default.

I changed the date range to include today, and successful retrievals are coming through! But I'm still not seeing anything for the clicks to the Edit link, which I would expect to see. I can always check back tomorrow on this, as I know that sometimes the data is incomplete for the current day.

<img width="1279" alt="Screen Shot 2021-03-11 at 4 05 43 PM" src="https://user-images.githubusercontent.com/34068740/110855090-eb017500-8283-11eb-9c02-a1562baa7d8a.png">

Also, let me know when we can expect to see successful saves and failed saves on the dashboard. Thanks!

**Comment by Samara-Strauss** [comment]
Hi @bmcgrady-ep — we are still not seeing anything populating in the "Clicks edit link" box even through our second UAT participant. Successful retrievals updated, so that appears to be working fine. Can you look into this?

Also, let me know when we can start seeing data for successful and failed saves on the dashboard.

![Screen Shot 2021-03-12 at 12.43.13 PM.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/1305d923-4a3b-4400-a519-e687d2870eea)

**Comment by bmcgrady-ep** [comment]
@Samara-Strauss - I am seeing events coming into staging from testing. Do you have a test user I can use on Production (va.gov) to see if the edu events are coming in?

**Comment by Samara-Strauss** [comment]
@bmcgrady-ep no, unfortunately we do not have production users. However, our UAT participants are all testing in production — feature is behind a feature flag and is only accessible in production for those participants during testing. So, I can assure you *something* is not working right, as we've seen our two participants click the edit link in testing.

**Comment by bmcgrady-ep** [comment]
Hi @Samara-Strauss - I updated the dashboard to include the failures and successes in form submits of Direct Deposit information. Also, I am seeing EDU Direct Deposit events coming into GA staging, so it looks to be working correctly on staging.

**Comment by Samara-Strauss** [comment]
@bmcgrady-ep is there an updated link to the dashboard? [This is the one I have](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/JXXY4MjTQlOjEa0HsEM3KA/a50123418w177519031p176188361/) and it is not yet showing save successes/failures. I'm assuming maybe that's because there's a new link, so let me know if that's correct or not.

**Comment by Samara-Strauss** [comment]
Following up on this: @bmcgrady-ep is there a new link to the updated dashboard?

**Comment by bmcgrady-ep** [comment]
Hi @Samara-Strauss - Can you check and see if [this link](https://analytics.google.com/analytics/web/template?uid=Aq5oURL4SI62d2KTZLFW7A) works for you? Thanks!

**Comment by Samara-Strauss** [comment]
It works! Thank you! I think we are good to close this out. Thank you so much for all of your help.

**Comment by bmcgrady-ep** [comment]
Glad it works! Feel free to reach out if you need any more help!
