### ISSUE TITLE
Content Feedback - Staging review - Eastern Oklahoma VAMC

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#20653]
## User story
Content staging review for East Oklahoma VAMC. 
Access information: https://staging.va.gov/eastern-oklahoma-health-care/ 

List of page to review, per slack message: 
https://dsva.slack.com/archives/CPQFCQKEH/p1614875650125600

- [x] About us
- [x] History
- [x] Suicide Prevention
- [x] Pharmacy
- [x] Billing and Insurance
- [x] Mental Health

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

**Comment by peggygannon** [comment]
@SgardnerPMP Please see below content feedback for the following eastern Oklahoma VAMC pages: 

- [x] About us
- [x] History
- [x] Suicide Prevention
- [x] Pharmacy
- [x] Billing and Insurance
- [x] Mental Health

----

Feedback key: 
Must = the feedback must be applied
Should = the feedback is best practice
Consider = suggestions/enhancements

**Must**

1. Eastern Oklahoma Health Care Systems is written in 2 ways:  
on About us page it's written as two words: Eastern Oklahoma Health Care System 
on History page it's written as 1 word: Eastern Oklahoma Healthcare Systems

which is correct? 

2.  History page (https://staging.va.gov/eastern-oklahoma-health-care/history/)
- Missing an “and” in this sentence. Jack Cleveland Montgomery (1917-2002) was a U.S. Army officer **and** a member of the Cherokee nation who received several military decorations for his actions in World War II. 

3. The suicide prevention accordion on health services page

- This link  to the Suicide prevention page isn't functioning: Learn more and connect with a care coordinator.  


4. Suicide prevention page

- Missing breadcrumb at top of page

- There’s no content on how people should connect with a Eastern OK care coordinator on this page. Should there be contact information/numbers for Eastern Oklahoma coordinator on this page, instead of the global How do I talk to someone right now crisis alert?  


5. Pharmacy accordion on the health services page

- The link to the Pharmacy isn’t functioning and It should also read: “Learn more about our pharmacy services”


6. Mental health accordion on the health services page

- Link to mental health page is not functioning

7. Mental health page (https://staging.va.gov/eastern-oklahoma-health-care/mental-health-care/)

- There’s no content on how people should connect with a Eastern OK care coordinator. Should there be contact information/numbers on this page? 
 

------

**Should**


1. Under suicide prevention accordion on health services page: Fix extra white space before bullet points


2.  Pharmacy page (https://staging.va.gov/eastern-oklahoma-health-care/pharmacy/)

Please make this sentence case: Pharmacy locations

for the Pharmacy location hours, please bump down the first line of hours for better readability
Hours: 
Monday through Wednesday, 8:00 a.m. to 4:30 p.m. CT

**Comment by SgardnerPMP** [comment]
Outstanding. Thank you.
