### ISSUE TITLE
IA Request: Booz Team - STEM Denial in Claims Status Tool

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#20656]
## Required Inputs:
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-decision_product-outline.md)

- [Link to prototype](https://bahdigital.invisionapp.com/share/G7IAG7A2XKD)

- [Link to final content including H1s (if separate from prototype/mockup)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content.md)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**Suggested URL(s)** - Provide suggested URLs and any background or rationale (to match existing)
https://staging.va.gov/track-claims/your-claims/
https://staging.va.gov/track-claims/your-claims/[claimID]/status
 
**Suggested Breadcrumbs** 
Home› Check your claims and appeals› Status details  (what's used in the tool for general claims status)

Home › Check your claims and appeals › Rogers STEM Scholarship Status (customized for STEM denials)

-- 

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?  Nope. 

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
Hi @amyknox, 

I think customizing the last segment of the breadcrumb for this type of status would be fine.  I would suggest that you keep reference to "status" or "status details" for consistency purposes and to keep an accurate label for the purpose of the page.

I'll put this in my notes for the mid-point review as well.   Beyond that, I don't believe there is any other IA work for this effort, so you are welcome to close this issue at your discretion.

**Comment by mnorthuis** [comment]
@amyknox Is this good to close?
