### ISSUE TITLE
Find a VA Form: Transforming search terms

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#20651]
Explore feasibility of handling search strings on front end so that we can find a good match between what users are entering vs. the way forms are named.

List of all current forms & names: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/post-mvp-releases/form-data-mgmt/data_eval-Feb-2020.md#form-vagov-feature-matrix

Search Terms being entered vs. actual form name is on tab **Rollup, Rank Changes**
[VA.gov Search Results Relevancy Audit (Jan-Dec 2020)-De-duped.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6070228/VA.gov.Search.Results.Relevancy.Audit.Jan-Dec.2020.-De-duped.xlsx)

**NOTE**:  For other parties reviewing this, this to find an interim solution to the basic problem described in the linked EPIC. Once Lighthouse has the capacity to implement a similar solution to what is laid out in [this technical doc](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20517), we will deprecate this work. 

**DECISION** 3/3/2021 - For the first iteration of this, we will attempt to include the search aliases within the Front End to avoid creating additional dependencies on Lighthouse and the CMS.  

Acceptance Criteria:

- For GA, Zach will have to change where he captures the analytics for the search term.  We need to capture the unadulterated search term.
- Document findings here on this doc.

**Comment by MarciMcGuireGCIO** [comment]
List of all current forms & names: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/post-mvp-releases/form-data-mgmt/data_eval-Feb-2020.md#form-vagov-feature-matrix

Search Terms being entered vs. actual form name is on tab **Rollup, Rank Changes**
[VA.gov Search Results Relevancy Audit (Jan-Dec 2020)-De-duped.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6070228/VA.gov.Search.Results.Relevancy.Audit.Jan-Dec.2020.-De-duped.xlsx)

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO  This PR is merged now. We should be seeing this live on staging give or take an hour.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Current back of string _auto correcting_.

`VA + space => delete
  FORM => delete
  ESPANOL => spanish
  Starts w/ **20** | 20123 => 20-123
  Starts w/ **21'** | 21123 => 21-123
  Starts w/ **22** | 22123 => 22-123
  Starts w/ **25** | 26123 => 26-123
  Starts w/ **29** | 29123 => 29-123
  Starts w/ **40** | 40123 => 40-123
  21P => 21P-
  1010 => 10-10
  1010EZ => 10-10EZ
  1010 EZ => 10-10EZ
  10-10 EZ =>  10-10EZ`
