### ISSUE TITLE
Improve application form generator output

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#2066]
## User Story or Problem Statement

As a front-end engineer, when I use the [VA.gov application generator]() to build a new form, it would help speed up the process if it would also update the following files:

- `src/applications/personalization/dashboard/helpers.jsx`
  - This file is accessed by the `<SaveInProgressIntro>` component to get specific details about the form.
  - The contents of this file also appears to not be very DRY. Most of the same information is included in the `manifest.json` and `config/form.js` files that it directly references for each form (e.g. form names & tracking prefixes).

- `src/platform/forms/constants.js`
  - This file is the source of all available form IDs accessed by the `config/form.js` file.
  - Would it also be benefinicial to centralize the OMB number & expiration date for the form in this file? The generator currently adds this information into the `IntroductionPage.jsx` file in an `<OMBInfo>` component.

- `src/content`
  - This folder contains an empty markdown file (with some YAML) meant to be added to the `vets-content` repository. This will be outdated soon.

- `src/applications/{folder}/{form}/container/IntroductionPage.jsx`
  - Should this be in the `components` or `containers` folder?
  - Does it need to include all the extra form schema? IIRC, it included direct deposit form items.
  - I was using form 526EZ as a reference. From comparing it to the new form, I noticed some essential components were missing, like the `<SaveInProgressIntro>` component and a few others that I don't immediately recall without building another new form.

## Goal
_What outcome(s) do we want to see?_

Make adding new forms as painless as possible. It's already pretty good, but easier is always nicer :D

## Objectives or Key Results this is meant to further
- Make adding a new form template super-easy.
- Include saved form data
- Simplify/Reduce the included form schema.

## Acceptance Criteria
- [ ] Update the form building process to follow the most-current needs (save in progress & auto-fill forms, etc)

**Comment by laineymajor** [comment]
@micahchiang what about this one? It's rather old, but I wanted to check with you before closing.. Thanks!

**Comment by micahchiang** [comment]
@laineymajor - you can close this out, thanks!

**Comment by rmessina1010** [comment]
Expired. Closing.
