### ISSUE TITLE
Research lazy loading frontend Login components

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#20671]
Alex researched load times of assets on va.gov and documented them [here](https://docs.google.com/spreadsheets/d/1DKaQMQxPalmEkPmT1dsnIl77N69_bBJUt5eh9TWu0DY/edit#gid=0). For rows 5-8 the team would like to know the effort it would take to implement the recommendations listed. The outcome of this ticket should be a documented plan/ticket to implement the recommendations.

**Comment by AGarcia-Clarity** [comment]
Also created a ticket of my recommendations here https://github.com/department-of-veterans-affairs/va.gov-team/issues/16961

**Comment by joeniquette** [comment]
![Screen Shot 2021-03-02 at 12.25.15 PM.png](https://images.zenhubusercontent.com/5f6a5e454ede530876cfc425/5ac8c75d-7e17-4603-9daf-e253556a46cd)

**Comment by AGarcia-Clarity** [comment]
After trying to modify the Webpack configuration manually, the `webpack.config.js` on vets-website is too finicky for direct modifications.

Instead I would like to suggest using a combination of `@loadable/component` and `react-loadable-visibility` functionalities.  The `@loadable/component` will allow us to implement **lazy-loading** on the FE and `react-loadable-visibility` will ensure these components are not loaded until they are visible (using the IntersectionObserver API).  We will have to also implement the IntersectionObserver polyfill to be loaded as well.
