### ISSUE TITLE
Display "Generic Error w/ Refresh" for unexpected errors

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20672]
## User story
As a user, if the mobile app runs into an error, I'd prefer to see an error screen with the ability to refresh the page, rather than a blank screen. 

## Acceptance Criteria
1. If the app runs into an unexpected error, show the following error state by default instead of a blank screen:
     - **Generic Error State | Refresh before calling help center** (#18227)

**Comment by digitalken** [comment]
PASS 3/4/2021 - Tested on user 366 by going to Letters page.  Got the "Try Again" refresh error.  Closing.
