### ISSUE TITLE
"View Your Claims" Instead of "View Pending"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2067]
## Story
As a member of the eBenefits Team, I would like to learn more about call to actions in the VA.gov website.  This would potentially lead to replacing the "Pending Disabilities" table with a call to action for the end user to be sent to the Claim Status Tool.

## Considerations
- Keep text generic, brief, and simple; be clear to signal exactly what will happen when a veteran clicks a button or link.
- Need to understand current system conventions for handling "featured" call-outs, panels, or links to other site tools.

For **track and manage benefits** an example might be "_Check your VA claim or appeal status_" and it would take the user to the [Claim Status Tool  ](https://www.va.gov/claim-or-appeal-status/)

## Tasks
- Review Design System and codebase for current patterns/components
- Engage with Content/IA about setting up a time to talk about any:
  - impact on content, and 
  - impact on IA
- Engage with Global UX about setting up a time to talk about CTAs and if there is any guidance to be above and beyond the [VA.gov style guide](https://design.va.gov/content-style-guide/)
  - Some found references include: [button labels](https://design.va.gov/content-style-guide/button-labels), [next steps](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Platform/Design%20System/Guidelines/Error%20handling/Content%20Style%20Guide.md#cta), [alert boxes](https://design.va.gov/components/alertboxes), [featured content](https://design.va.gov/components/featured-content)
- Edit current mockup to reflect guidance provided by Content/IA and Global UX 

## Definition of Done
- [x] A review by Content/IA (& Global UX, bc its all going to the same people) has been requested (or the review already submitted has been updated)
- [x] Feedback has been received (meeting with Peggy thursday 10/3)

**Comment by sporeboy** [comment]
Updated mockups to reflect content changes to accommodate an RD link to the Claims Status Tool.
