### ISSUE TITLE
Clipboard Integration - AVS <> Clipboard (#168)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20685]
The clipboard team would like to add 3 questions to the Pre Visit Summary (PVS)

integration with lighthouse - stephen barrs has done that. 

next step integrate with AVS - integrate code into pvs

- discovery - how to compensate for icn inconsistencies to allow for end to end functionality
- testing with stable icn

testing challenge - there are several different environments and there are issues with ICN inconsistencies

----
Original Ticket: 

"Shane: 1) Both ways
	2) Send appointment Reminder. / Questionnaire email that is formatted differently.  And specific to the veteran.
	3) For MVP 1)AVS, 2)email.
	4) End of January?

![image](https://github.ec.va.gov/storage/user/2120/files/a63cc100-3638-11eb-98e0-c709037371c2)

Shane: https://dsva.slack.com/archives/G01F0DXHD3K/p1608580898011600

Transferred on 4 Mar 2021. Original Column: In Progress, Original Labels: development

**Comment by Kennon-git** [comment]
rob made coding changes necessary to configure other sites and their corresponding longcodes. time to "flip the switch" for eastern colorado

**Comment by kjduensing** [comment]
duplicate

**Comment by Kennon-git** [comment]
waiting for team to create dummy recent appointments / encounters.

**Comment by Kennon-git** [comment]
wait until it is in production but our piece is ready
