### ISSUE TITLE
Form0781 submission bug

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#20686]
[this bug](http://sentry.vfs.va.gov/organizations/vsp/issues/1435/events/5d717a99bbf04f96bd2a3960b87cb599/?environment=production&project=3&statsPeriod=14d) is preventing submission of form Form0781 Statement in Support of Claim for Service Connection for PTSD

**Comment by vhenry07** [comment]
Closed as duplicate of 22439
