### ISSUE TITLE
Support Bot - next iteration post-pilot

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#20683]
Support Bot Pilot Findings: 

- Bot user experience: The responsiveness and speed of the bot can slow down conversations and cause delay in recording or resolving support requests.
- Reporting: Low adoption of labeling support requests results in a lack of metadata for reporting metrics.
- Guidance and expectation setting: Without provided Support staff with direct, written expectations on what to track and how, data will be inconsistent or inaccurate across different teams or products.

Goals for the next iteration:
- Replace bot command interactions with Slack workflows that trigger the bot to log data.
- Bot automatically applies labels for VSP team, question type from the workflow form and links to documentation provided to resolve the request. 
- VSP support staff are required to categorize the request before closing the ticket.
- Setup training sessions with Support staff to explain guidelines for what to track and procedures for responding to and tracking support requests.
- Ensure all information provided to VFS folks about how to request platform support is consistent, clear, and easy to refer back to. In cases where VFS folks do not follow guidelines, there is a standard approach for Support Staff to change their behavior.

Measuring Success:
User adoption
- Volume of customer support requests that are automatically logged and tagged
- time it takes to compile customer support reports

We are able to answer the below questions:
- What is the volume of Slack customer support requests VSP teams receive over time?
- How many of those requests are resolved by documentation?
- What are the most common types of Slack customer support requests?
- On average, how long does it take to resolve the most common types of Slack customer support requests?	
- Which support request types could be made self-service?

**Comment by Khyatinp18** [comment]
2/21/2022:

Closing this issue since it's no longer a priority.
