### ISSUE TITLE
Update appointment API calls

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20682]
## Context for this task
Appointments are now pre-cached in staging. A background worker retrieves the default range of appointments (< 3months, > 6 months) after the user profile is fetched. So if you call GET /mobile/v0/appointments with a query param of useCache=true (given enough time after the profile call, e.g. on the appointments screen rather than at login) it will return the appointments in roughly 150ms rather than 3-4 seconds. If you’re making a call after an update on .gov or cancelling through the app make sure to use useCache=false to get the updated list.

## Dev task
1. Update appointment API calls with the **useCache** flag. Use this flag unless the user makes an update through the app, such as canceling an appointment

**Comment by digitalken** [comment]
Closing 3/18/2021 - Nothing for QA to test.
