### ISSUE TITLE
Reconsider HLR contestable issues timeout 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#20695]
we are seeing timeouts from the HLR contestible issues endpoint http://sentry.vfs.va.gov/organizations/vsp/issues/17731/?statsPeriod=14d
Is there anything we can do about it besides raise the timeout? It looks like it's consistent with the responses lighthouse gets from caseflow.

va.gov -> lighthouse.
![Screen Shot 2021-03-02 at 1.30.13 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/2ab013a0-6e67-415a-8c7d-29035a101ef3)

lighthouse -> caseflow
![Screen Shot 2021-03-02 at 1.29.45 PM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/fe434e0e-251e-4454-8a4d-aed6645a7fc1)

**Comment by edmangimelli** [comment]
approach we ended up going with https://github.com/department-of-veterans-affairs/vets-api/pull/6125#discussion_r591757251
