### ISSUE TITLE
0994: Update form introduction content and remove prod flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#20703]
As a developer, I need to remove the prod flag for the service history chapter updates so that they are available in the production environment.

## Assumptions:
1. This work has been signed off by EDU as of 2021-03-19.
2. The introduction page is located here: https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/introduction
3. The feature flag `edu_form_omb_and_expiration` is flipped in production after this is merged.

## Acceptance Criteria
1. The work completed in #20197 & #21524 is available in the production environment.
2. The content in the "Prepare" section of the 0994 introduction page is:

> #### 1.	Prepare
> 
> **To fill out this application, you’ll need your:**
> *	Direct deposit information
> *	Highest level of education
> *	Previous high-tech industry experience, if applicable
> *	Information about the training provider or program you want to attend (optional) 
> 
> **To be eligible for VET TEC, you need to be**
> * A Veteran with at least one day of unexpired education benefits, **or**
> * A service member with 180 days or less left on active duty
> 
> You can complete the VET TEC application to see if you’re eligible for the program, even if you haven’t yet selected the training program you'd like to attend. [Learn more about the programs covered under VET TEC](https://www.benefits.va.gov/gibill/fgib/VetTec_Veteran.asp).
> 
> **What if I need help filling out my application?** An accredited representative, like a Veterans Service Officer (VSO), can help you fill out your application. [Get help filing your claim](https://staging.va.gov/disability/get-help-filing-claim/).

## Supporting Artifacts:
1. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/vettec-0994/design/0994-content.md#1prepare)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16445

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/tests/view/89298&group_by=cases:section_id&group_order=asc&group_id=51)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now live. Closing this issue
