### ISSUE TITLE
508-enhancement [MOBILE DESIGN]: Consider conducting mobile screen reader research with iOS users

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#20719]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Josh, Angela, Trevor_

## User Story or Problem Statement

As a researcher, I want to better understand how mobile screen reader users interact with typeahead searches.

## Details

Our typeahead implementation requires users to touch the input and re-establish focus (away from the keypad) before they can swipe right to listen to options. I think it's worth setting up research sessions to determine if users understand this paradigm and iterate as necessary.

## Acceptance Criteria

- [ ] Participants are [recruited from an inclusive audience](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/inclusive-research-recommendations.md#guidelines-for-inclusive-research-recruiting)
- [ ] 5-7 user research sessions are conducted
- [ ] Research is documented and synthesized with other a11y specialists

**Comment by denisecoveyduc** [comment]
After discussing this with @cindymerrill, we have no plans to conduct research with mobile screen reader users for the first iteration of typeahead. As we continue to iterate and move into Typeahead 2.0 we will keep this top of mind.
