### ISSUE TITLE
GA Events for Rated Disabilities Page

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#2072]
## User Story or Problem Statement
As a member of the eBenefits team or the GA/Insights team, I need to know how users are interacting with the Rated Disabilities Page, so I can gather data about traffic, number of users, etc.

## Goal
Fire appropriate GA events on Rated Disabilities so we gain insight into how often it's accessed and how it is being used.

## Tasks
- Engage with GA/Insight Team to understand:
  - We need event names supplied to us from the GA / Insight team similar to how other events are fired in other applications. i.e. `recordEvent({ event: 'profile-get-direct-deposit-failure' });`
  - Gain any feedback from the GA/Insight Team that might help for other event names

## Acceptance Criteria
After staging:
- [x] We receive event names from GA / Insight team that we can use in Rated Disabilities  

**Next Steps**
- Events are successfully fired and recorded in GA.
- Establish baseline metrics

**Comment by micahchiang** [comment]
@joanneesteban, @nedierecel  - As we move towards deploying rated disabilities to staging, I wanted to kick off a conversation about what sort of events this page should fire. I've attached a screenshot of the page to this comment. Would it be possible, just by looking at it, for you to give us an idea of:

1. How many events would need to be implemented.
2. The names of the events.

I have seen some events being pushed by the dataLayer. Would this need to be done here? Basically I am wondering, since our eBenefits team is all fairly new, what sort of configuration we need to do on our end to register rated disabilities with GA.

<img width="672" alt="Screen Shot 2019-10-21 at 12 39 28 PM" src="https://user-images.githubusercontent.com/15097156/67237300-d955ce00-f3ff-11e9-8707-8f58c8eaa227.png">

**Comment by nedierecel** [comment]
@micahchiang Thanks for sharing. 

1. For Event Tracking - Outside of 'Check Your Claims and Appeals' and the right rail content, are there any other user interactions that are expected to take place that might not be visible in this mock?
2. For Pageview Tracking - Does this page render a unique URL than /track-claims/? Are there any other historyChanges that take place as the screen loads? I ask as it impacts how we measure pageviews to Rated Disabilities.
3. For other measurement - is there a need to measure how many rated disabilities a veteran has open at one time (of course all non-PII)? CC: @jason-gcio here for input

These answers will help us craft recommendations for GA event tracking. Thanks!

CC: @jonwehausen

**Comment by micahchiang** [comment]
@nedierecel - Responding to some of your questions / comments above
- As far as I know, there are no other user interactions that are expected to take place. However, I could be off, so will let @sporeboy and @jason-gcio weigh in. 
- `We can measure successful and failed loads of rated disabilities. Are you currently seeing any of these events pushed into the dataLayer?` 
       - Can you clarify this? We currently aren't pushing any events to the dataLayer.

- Pageview Tracking: Per #2584, there are two URLs involved with Rated Disabilities:
1. Static page URL: www.va.gov/disability/check-disability-rating/
2. Report/dynamic page URL: www.va.gov/disability/check-disability-rating/rating
- The static page is one that will be configured by global ux. 

At this time I don't believe veterans will have the option to click on individual disabilities and view more information on them. They are there purely to be viewed. Hope this information helps. Let me know what else you need / what needs to happen next to move forward towards integrating Rated Disabilities into GA. Thanks!

**Comment by nedierecel** [comment]
@micahchiang Thanks for the context above. 

*Our Next Steps*
1. The starting place for the Analytics Insights team will be to provide you with how to track a) successful loads and b) failed loads. I'll prepare the naming conventions for these requirements after doing a peer review with @jonwehausen 

*Additional Discovery for the eBen Team*
For errors, it looks like there are a few types of errors that can occur - e.g. complete failure of all ratings to load OR a failure to load a specific rated disability. 

Is it possible for you to pass back an `errorKey` for either of those occasions?

_Use Case_
The veteran gets a failure in loading all of their rated disabilities. The `errorKey` you get back is in a text or numeric key like `0421` (my made up value!). Could you translate that in a dataLayer parameter like `failed-load-all-ranked-disabilities`?

**Comment by micahchiang** [comment]
@nedierecel - As it stands, there are several possible scenarios regarding error states:

 _Total Combined Rating_ 
- failed to load, 500 error (something is wrong in our system)
- failed to load, 40x error (no rating found for the veteran).
- successfully loaded, 200 response. 

_Rated Disability List_
- failed to load, 500 error (something wrong in our system).
- failed to load, 40x error (veteran has no list of rated disabilities).
- successfully loaded, 200 response.

#### Some things to consider:
1. As of right now, there are no cases where an individual disability would fail to load but the rest of the list would succeed. It's either all or nothing. 
2. _Total Combined Rating_ and _Rated Disabilities List_ will most likely be supplied by two separate API calls, which is why I made the distinction above. For both of them, we would receive response codes (`errorKey`?) which could be used to craft a dataLayer parameter like the one you mentioned above.

**Comment by micahchiang** [comment]
Proposed event pushes for rated disabilities:
1. _Disabilities List Load Successful_: `window.dataLayer.push({'event': 'disability-ratings-load-success'});`
2. _Total Combined Rating Load Successful_: `window.dataLayer.push({'event': 'disability-combined-rating-load-success'});`
3. _Disabilities List 500 error_: `window.dataLayer.push({'event': 'disability-ratings-load-failed', 'error-key': '500 internal error'});`
4. _Disabilities List 401 error_: `window.dataLayer.push({'event': 'disability-ratings-load-failed', 'error-key': '401 no disabilities found.'});`
5. _Total Combined Rating 500 error_: `window.dataLayer.push({'event': 'disability-combined-rating-load-failed', 'error-key': '500 internal error.'});`
6. _Total Combined Rating 401 error_: `window.dataLayer.push({'event': 'disability-combined-rating-load-failed', 'error-key': '401 no combined rating found.'});`
7. _Navigate to Claims Status Tool_: `window.dataLayer.push({'event': 'disability-navigation', 'nav-action': 'claims-status-tool' });`

@jason-gcio, @steve-gov, @nedierecel - Above are proposed data layer event pushes for both disability list and total combined rating. Note: there's a helper function in `vets-website` called `recordEvent` which we would use instead of calling `window.dataLayer.push()` directly.

@nedierecel - I found this document about requesting implementation from GA https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/analytics-communication-guide.md. When is the right time to fill out an implementation or QA request template with the analytics team? Is it after our app has been deployed to staging? Should I have done that before doing all of this 😬? Should events be added to our application before filing a request? Sorry for all the questions!

**Comment by nedierecel** [comment]
@micahchiang No worries, and thanks for the dataLayer requirements. 

Typically the implementation request to collaborate on the events is completed before staging (or as early as possible). I was treating this as the official request. No worries--the team can complete the template for the next round of iterations on the tool!

Correct on the `recordEvent` - we can utilize that for the above. 

Next steps:
1. For naming conventions, I'll look through your list and make a few suggestions. 
2. After we collaborate on revised naming, you'll implement on FE and alert us when it's on staging.
3. We'll QA and ensure that the events are properly recorded. If there's a way we can recreate some of those errors, please let us know so we can test the error states.

**Comment by micahchiang** [comment]
Thanks @nedierecel! These look good to me. Any update on the event name for the navigation piece you mentioned above? I think that's the only one left that we need :)

**Comment by nedierecel** [comment]
@micahchiang I'll review today - 

To help with that last navigation piece, can you please share a sample user so we can review a test profile? We want to see what is being used from the design system, as we are moving to globalizing the call-to-action links. 

CC: @jonwehausen

**Comment by micahchiang** [comment]
@nedierecel here's some info you can use:
- access here: https://staging.va.gov/disability/check-disability-rating/rating/
- 2nd test user (row #3) from here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/mvi-staging-users.csv

**Comment by micahchiang** [comment]
Hey @nedierecel - hope you had a good weekend. For your reference, we have another ticket, https://github.com/department-of-veterans-affairs/va.gov-team/issues/2859, to deal with implementing the above GA events into our application in `vets-website`. I'm referencing it here in case this ticket gets closed out. Feel free to add the seventh tracking event (navigate to claims status tool) to that ticket as a comment. Thanks!

**Comment by nedierecel** [comment]
@micahchiang Thanks for letting me know. I'll comment on the navigation tracking in #2859.
