### ISSUE TITLE
Error | Attachment file size exceeds limit

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20727]
## User story
As a user, I want to know when I cannot upload an attachment to my message because it exceeds the file size limit.
 
## Acceptance Criteria
1. Create UI for an error state when a file cannot be added to the form page because it is >3 MB
2. This error state displays on the Attachments page (#20139). It appears after a user has selected a file from their device's camera, photo gallery, or camera roll
3. Pull in mobile alert CC 
     - Left border: #CD2026
     - This alert appears at the top of the page, below the top nav bar
4. Copy: "The file you are trying to upload exceeds the 3 MB limit. Please reduce the file size and try again."
     - Copy is unbolded
5. This error state persists until the user navigates away from the page

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449230096

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/20/2021 - Looks good on both Android and iOS.  Closing.
