### ISSUE TITLE
Investigate resubmission attempts after time out errors

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#20741]
Of a random selection of 10 cases of Veterans who saw a timeout error on the 10-10CG, I want to know

- Claim IDs
- Case IDs
- IP address (unique identifier)
- How long the first submission took
- How long the second (if applicable) submission took
- Timestamp of the first submission
- Timestamp of the second submission (if applicable) 
- If any submission went through successfully to CARMA 
- If any submission had a PDF attachment
- Who was on the application? (PFC, SFC, SFC2, etc)

**A/C**
- [x] Of the cases in row #s `26, 29, 35, 56, 76, 97, 113, 150, 156, 161` in [this spreadsheet](https://docs.google.com/spreadsheets/d/1OVghvx8yFkOSNnnzpHZulbdDnqQRGohAOr4SELO0L7M/edit#gid=998813922), provide the above data points.
- [x] Do users experiencing this error re-submit?
  - For the most part, yes. There was one user who did not.
- [x] Are resubmissions successful?
  - Hit-or-miss.
- [ ] How long after a timeout do users re-submit / re-apply?
- [x] How long is the processing time of the successful re-submission?
  - 6 seconds in three cases, 60+ seconds in one case, all others experienced an issue.
- [x] Write up a quick summary of findings  - what conclusions, if any, can we draw from this research?

**Findings**
Although there were few cases where users were able to re-apply successfully, many experienced another issue on their following attempt. These issues included another timeout, a CARMA DB error, or validation. I don't think it's fair to say that "re-applying usually goes through without issue".

**Comment by kevinmirc** [comment]
We can also identify users who've experienced an error and resubmitted within GA by filtering users who experienced the event label `caregivers-10-10cg--submission-successful` **and** `caregivers-10-10cg--submission-failed-client`.

I will still do the spot check in our logs though and see how consistent it is with this GA report.

![Screen Shot 2021-03-04 at 10.48.49 AM.png](https://images.zenhubusercontent.com/5df3b02f7e9c5dbde476fd6a/7c9f0ee6-8880-4d60-84c9-bb5dbc018e20)

![Screen Shot 2021-03-04 at 10.50.35 AM.png](https://images.zenhubusercontent.com/5df3b02f7e9c5dbde476fd6a/c23b5517-3b01-40dc-9f0b-94b0f2a38d3c)

**Report**: https://analytics.google.com/analytics/web/#/report/visitors-legacy-user-id/a50123418w177519031p184624291/_u.date00=20210228&_u.date01=20210228&_.cusegid=custom&_.cuseg=%7B%22visit%22:%5B%7B%22simple%22:%7B%22conditions%22:%5B%5B%5B0,%22analytics.extensible_data_5_3%22,%22EQ%22,%22caregivers-10-10cg--submission-successful%22,0,null%5D%5D,%5B%5B0,%22analytics.extensible_data_5_3%22,%22EQ%22,%22caregivers-10-10cg--submission-failed-client%22,0,null%5D%5D%5D%7D,%22templateId%22:%22CONDITION%22,%22criteriaId%22:%22condition0%22%7D%5D%7D&_.cusegname=%3CPreview%3E&_.useg=custom&reportHeader.usegmode=PREVIEW&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=10/

**Comment by kevinmirc** [comment]
Results:

| Row | Req. 1 Timestamp | Req. 1 Duration | Req. 2 Timestamp | Req. 2 Duration | At least one successful submission | At least one successful attachment | Submission Schema (PFC, SFC, SFC2, etc) |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 26 | --- | --- | `2021-01-20T03:40:47.864397Z` | --- | --- | --- | --- |
| 29 | --- | --- | --- | --- | --- | --- | --- |
| 35 | --- | --- | --- | --- | --- | --- | --- |
| 56 | --- | --- | --- | --- | --- | --- | --- |
| 76 | --- | --- | --- | --- | --- | --- | --- |
| 97 | --- | --- | --- | --- | --- | --- | --- |
| 113 | --- | --- | --- | --- | --- | --- | --- |
| 150 | --- | --- | --- | --- | --- | --- | --- |
| 156 | --- | --- | --- | --- | --- | --- | --- |
| 161 | --- | --- | --- | --- | --- | --- | --- |

**Comment by kevinmirc** [comment]
Completed.

**Comment by kevinmirc** [comment]
Data was collected, but reopening to answer the questions in A/C.

**Comment by kevinmirc** [comment]
**Findings**
Although there were few cases where users were able to re-apply successfully, many experienced another issue on their following attempt. These issues included another timeout, a CARMA DB error, or validation. I don't think it's fair to say that "re-applying usually goes through without issue."
