### ISSUE TITLE
VTK Feedback Collection (Phase 2)

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#20745]
Collect and analyze feedback from users of the toolkit to determine best phase 2 features.

**Comment by ericboehs** [comment]
@andreahewitt-odd Could you post the results here or prime Jeff to be able to do this please?

**Comment by jeff2d2** [comment]
[Survey results](https://app.optimalworkshop.com/a/adhoc/questions/results/573713c7-eba7-4a50-bedb-cbd236612110#/t/results/analysisTools/questions)
