### ISSUE TITLE
File attachments for replies and new messages are corrupt

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#20750]
Attachments are making it through to the clinician, have the right filename/mime type, but have a different checksum and are not valid/viewable jpg/pdfs.

**Comment by patrickvinograd** [comment]
Did some further debugging, but no solution as of yet. Findings:

* The contents are intact within Rails; it caches the contents in a temp file and that still looks valid.
* We are sending the multipart payload with `Content-Transfer-Encoding: binary` as per the MHV SM API spec.
* But, when I download the uploaded file, and inspect it with hexdump, I see that it has a bunch of extraneous `ef bf bd` character sequences. This is the unicode replacement character for unknown characters. So it seems like something along the way is not treating this as binary but instead trying to parse it as unicode and inserting these replacement characters.
* I was able to reproduce the issue sending a message with attachment via curl from the forward proxy, so again that seems to rule out our rails code.
* The MHV portal doesn't have this issue, messages sent from patient to clinician arrive just fine.

One thing that may be worth trying is sending the attachment content with `Content-Transfer-Encoding: base64` (and base64 encoding it of course. But that will take some doing in Faraday so I'd like to get some indication of whether it will work. If that's what the MHV portal client code is doing, we can follow suit. This would be a change within the backend code, no need to change how mobile client is sending to vets-api.

**Comment by patrickvinograd** [comment]
The issue with corrupted attachments is resolved. It turns out that we were using a different API endpoint than the MHV portal, and the API gateway for our endpoint needed some configuration change for binary content to be preserved. 

Keeping this open as I did have to make a minor vets-api change to get attachments to be processed by Rails properly. Will use this ticket to track that change.
