### ISSUE TITLE
New UI Menu | Language Options | Covid-19 Vaccine Page 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20754]
# Story 
As a product manager, I would like to provide users with a clear, highly visible option to read content in english, spanish, and tagalog when viewing the Covid-19 Vaccine page.

- The english, spanish, and tagalog Covid-19 Vaccine pages will all display a language selection option in the H1. It should look  and functions similarly to the Gov.UK example (shown below).

English | Español  | Tagalog 

UI Guidance for ^ :

- 16 pixels
- Source Sans font
- For "on-state" use standard dark grey color
- For "off-state" use standard blue and underline text
- No icon
- Text should align with content

(Note: add a lang attribute)

# Acceptance Criteria

PLACEHOLDER

# UI  Example based on GOV.UK: 

![Screen Shot 2021-03-03 at 10 59 48 AM](https://user-images.githubusercontent.com/74627978/109867833-f970e080-7c34-11eb-9ea9-88384f9fda00.png)

**Comment by SKasimow** [comment]
Hi @sshein - here is the ticket for the UI language selection treatment we need design assistance with.  We will be adding to the Corona FAQ page too.  Let me know if you have any questions...appreciate the help!

Sharon

**Comment by sshein** [comment]
cool. So the bullets in the story above are coming from Ryan, and you just need someone to take those bullets and make a visual?

**Comment by SKasimow** [comment]
@sshein Yes. He also wanted to check with Trevor for accessibility and I have time set up for tomorrow to get his input. I'll update if anything changes.

**Comment by sshein** [comment]
ok, why don't you or @rtwell update this ticket when you have more info about accessibility and we'll see what is still left to be specced

**Comment by sshein** [comment]
oh it looks like @youngfreezyVA already coded something and uploaded a video https://github.com/department-of-veterans-affairs/vets-website/pull/16256 - has @rtwell seen this and provided feedback or do you want myself or one of my team members to do so?

**Comment by rtwell** [comment]
i have not seen it—here's a quick comp that refines what @youngfreezyVA has already (so quickly!) started:
https://www.sketch.com/s/e4461f10-60cd-46f6-9479-69f0a4d71bab/a/bgrnRjJ#Inspector

**Comment by SKasimow** [comment]
@rtwell Thanks for the comp Ryan! Yes @youngfreezyVA is working fast and furious to get these updates in :)

Fareez and I did meet with @1Copenut today and got some good feedback from him so we're set there and will have him review once we have updated version.

Also, just fyi we have been using 'Espanol' (with tilde over "n") vs 'Spanish'.

+ @DanielleThierryUSDSVA for awareness.

**Comment by youngfreezyVA** [comment]
@rtwell implemented your design in the updated PR, cheers 🍻
