### ISSUE TITLE
"Patient Lookup" RX Tracking Tool

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20752]
call centers want a way to look up call tracking - after RX tracking. 
simplest display prescription tracking message in existing tool. 
what they would prefer is a way to look up the data not the messages themselves.

**Comment by shanemelliott** [comment]
![rxtraking..png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/d713d441-dec0-4b60-84d8-3e422217c9cf)
