### ISSUE TITLE
Advanced sidekiq queue

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#20767]
## Issue Description
It was mentioned in the [#platform-support](https://dsva.slack.com/archives/CBU0KDSB1/p1614781057024500) channel that we should consider using the advanced sidekiq queue. Everything as of current is default priority. We may consider scaling based upon the number of jobs waiting to be processed vs scaling based upon memory/cpu. Long running jobs cause backups since they're making calls to external services that are often slow. 

See the link above for additional details

**Also** in the [procfile](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Procfile#L2), the queue order is out of place. critical should be placed before default to ensure the proper process ordering (processed in queue definition priority from left to right). 

### Suggested solution:
The best way to handle this might be to make a queue just for EVSS file uploads and have it lower priority than the other queues and then possibly scale up the number of workers.

---
## Tasks
- [ ] Review sidekiq queues

**Comment by ericboehs** [comment]
I think we should have 4 queues that are prioritized in this order:

- critical
- mailer
- default
- low

With sidekiq, if [you specify multiple queues](https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues), sidekiq will work on the first ones first. For example, to do the above, we could change our sidekiq command to:

```
sidekiq -q critical -q mailer -q default -q low
```

It would first work all critical jobs, then mailer, then default, etc. I notice we have a config/sidekiq.yml so we may need to specify it in there instead. I prefer CLI args over the config but I'm not sure it makes sense to use both.

To further mitigate against job contention, we could have dedicated workers which only work critical/mailer jobs. I'd suspect a single worker with multiple threads would be sufficient.

One consideration, is that adding more workers will use additional db/redis connections (I think it's one per thread?). I'm not sure what our redis connection limit is. I do know our db connection limit is very high though.
