### ISSUE TITLE
Replace JSDOM with Cheerio in linkAssetsToBucket function

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#20763]
## Details 

From #20206

Synopsis
My analysis determined that Cheerio is faster than using regex to traverse HTML files and update source paths. It would be worth creating a card to refactor the linkAssetsToBucket function from the Prearchive stage to use Cheerio. As part of this refactor I would recommend breaking that function up into smaller, more easily understandable parts and add unit tests. This draft PR can serve as a place to start.

Recommendation 
Update the linkAssetsToBucket function from the Prearchive stage to use Cheerio. As part of this refactor I would recommend breaking that function up into smaller, more easily understandable parts and add unit tests. [This draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16215) can serve as a place to start.

## Definition Done 

- [ ] Replace JSDOM with Cheerio in the linkAssetsToBucket function (required)
- [ ] Break function up and make it easier to read 
- [ ] Add unit tests for this function

**Comment by k80bowman** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16276)

Running into an issue where there are slight differences in the way Cheerio outputs the HTML vs the way JSDOM output the HTML. The two main differences are:
1. The way they handle HTML entities
2. The way they handle empty HTML attributes

We aren't concerned with the differences in how they handle empty HTML attributes, that will not cause any problems. The HTML entities shouldn't cause any problems, but might. I'm digging into that now.

**Comment by k80bowman** [comment]
We were able to resolve all issues and this work is merged! It also helped resolve some memory issues we were having with the prearchive step.
