### ISSUE TITLE
Investigate the Total Calc Percentage?

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2076]
## Story
As an eBenefits Team member I want to see if there is a better way to present the visual of this percentage for more effective communication.

## Considerations
- A circular indicator might lead some viewers to perceive that a higher number is advocating for a Veteran to be more disabled, versus its intent which is, how much benefit is available to that Veteran.
- A circular bar is not currently part of the VA.gov's Design System as of today and would be introducing a newly created component.
- Would simply having a large percentage number with supporting language make the intent clear of what that Total Calc actually is?
- Strong argument that the circle is about status and not progress
- The original work done had little to no research done and was somewhat limited in their resources.

## Tasks
- Discuss: Jim, Jesse, Micah, and Aricka, anyone else?
- Seek feedback from/ with research

## Definition of Done
- [ ] Gain feedback on the circular indicator from the user interviews.

**Comment by micahchiang** [comment]
It sounds like this is something we will be discussing as we conduct user interviews. Moving it into the ready column.
