### ISSUE TITLE
[FSR] Empty state for when there are no debts

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#20773]
## Issue Description
_Currently, an authenticated user can technically access the FSR form when they do not have an active debt. However, we want to prevent users from submitting general FSRs since this iteration focuses on VBA debt. Veterans could potentially submit an FSR that was meant for a different department or debt type._

---
## Tasks
Once an authenticated Veteran navigates into the form from the introduction page, there's a fetch call for debts. If there are no debts returned, display the empty state in [this UXPin mockup](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/137187972/specification/no-panels?mode=i). 

## Acceptance Criteria
- [ ] _The provided empty state displays when the API call returns no debts for the authenticated Veteran_
- [ ] _The empty state has been QA tested_

**Comment by craigwheeler** [comment]
Need a user to test for when there are no debts the following user cases outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/fsr-use-cases.md) need mock data for localhost updated by BE
