### ISSUE TITLE
[FE] Stop showing expired applications on My VA 2.0 

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#20775]
## Background

Currently, there is functionality that allows My VA to (1) show expired applications and (2) then allow for the removal of those applications from My VA. A simpler implementation would be just to not show applications once they expire.

## Tasks

- [x] Remove expired applications from My VA 2.0
- [ ] ~Retain all current work on removing items from My VA behind a flag in case we want to utilize this functionality later~

**Comment by erikphansen** [comment]
Merged and closing as I don't think there's an easy way for this to be validated.
