### ISSUE TITLE
Form 526 Usability Study - Results

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#20777]
## Issue Description
Summary and slide desk

---
## Tasks
- [x] Formally document results of study and post to GitHub.

## Acceptance Criteria
- [x] Documentation posted to GitHub
---

**Comment by chrvalla** [comment]
Completed. Findings can be found here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd/BDD%20Research/BDD-Usability-test-April2021

Closed.
