### ISSUE TITLE
In-app notification UI

### ISSUE THREAD

**Issue by ayushchak** [department-of-veterans-affairs/va.gov-team#20774]
## User Story
Determine what UI should present in the app IF a user gets a notification from the app while they have the app open.

## Findings
- In app Jiggle

**notification settings**
- Banner
- sound
- Vibrations
- Icon badge

## Requirements (work in progress)

- in app badge (Maximum number shown ##, size 14px by 14px)
- in app banner ( WIP)

**Comment by msmanak** [comment]
## Notifications Turned on after system prompts

1. User clicks yes for push notification, push will turn on for all notification until user turns off in settings.
2. Toolbar bubble will indicate how much messages per tab
3. in app notification will show banner. (time:-----)
- {#} one new secure message, review your messages (link to secure messages)
- 1 new appointment scheduled, _review your appointment_ (link to appointments)
 4. when user clicks banner/tab button:
- banner will link to tab
- bubble will disappear after in category.

## Notifications Turned off after system prompts
1. User clicks no for push notification
2. Notifications are turned off until user goes to settings to change

## Design Decisions
 Banner: 
- Background color:
- font size: Use hint font
- underline "review...."

Bubble
- 14 by 14px with 12 pt font
- Number constraints:

**Comment by msmanak** [comment]
![Slice-notification.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/af827257-153b-4d9d-a0e6-c867e4bf6841)

WIP

**Comment by lexicalninja** [comment]
@msmanak for this part `1 new appointment scheduled, review your appointment (link to appointments)` we can't actually know if there is a new appt scheduled. We are getting a notification that there is an upcoming appt and don't know a number. We can probably consider just a notification dot without any numbers as an option here. What do you think?
