### ISSUE TITLE
Generate reproducible IDs in the nonce plugin

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2077]
## User Story
As an engineer, I need the Metalsmith build to be idempotent so I can tell when something I've done changes the output .

### Background
The plugin that adds the `nonce`s to scripts also wraps `onclick` handlers in a script with a `nonce`. It ties the original handler back to the element it belongs in by ID. If the element doesn't have an ID, it'll generate a random one.

### Possible solution
Rather than generating an ID randomly, we can generate one based on the filename and handler index so it's reproducible between builds.

## Goal
Consecutive builds with no changes produce the exact same output.

## Acceptance Criteria
- [ ] The ID generated in the `nonce` plugin is predictable

**Comment by rianfowler** [comment]
`nonce` value is [generated by the reverse proxy](https://github.com/department-of-veterans-affairs/devops/blob/0eb82373423c7f96ce131982196aa266c73089bc/ansible/deployment/config/revproxy-vagov/templates/nginx_revproxy.conf.j2#L322-L325) on each visit but we're not adding the value correctly to our script tags' `nonce` attribute:

<img width="369" alt="Screen Shot 2019-11-01 at 11 10 54 AM" src="https://user-images.githubusercontent.com/4998130/68042444-877f3480-fc98-11e9-8165-6a444c92d826.png">

May need to confirm this with devops but I think the rev proxy is replacing for `CSP_NONCE` with the generated value (linked above): 

`sub_filter **CSP_NONCE** $cspNonce;`

**Comment by rianfowler** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3046

**Comment by rianfowler** [comment]
This works- can't see the nonce in the DOM explorer. have to look at the raw response in the network panel in chrome.

**Comment by rianfowler** [comment]
<img width="1187" alt="Screen Shot 2019-11-14 at 16 29 04" src="https://user-images.githubusercontent.com/4998130/68904788-fda18380-06fb-11ea-84cb-0937595c5863.png">
<img width="1187" alt="Screen Shot 2019-11-14 at 16 29 10" src="https://user-images.githubusercontent.com/4998130/68904789-fda18380-06fb-11ea-8a09-746389fd5544.png">
