### ISSUE TITLE
[Ongoing Service] Offboard departing customers

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2078]
## User Story

As a VFS team picking up work on an existing product on VA.gov, I need to know what development has happened on that product and related products in the past, so that I can efficiently move the product forward.

As a VSP team member responsible for access management, I need to enforce a standard protocol for access management offboarding, so that I can ensure that the only people with access to VA.gov systems are current team members building on and in support of VA.gov.

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)

- [VSP KR] Increase in customer NPS
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- Percent of teams with contracts ending who meet documentation offboarding standards
- Duration of access management delay (number of days after a team member’s end date before access is revoked to all systems) — _need to refine_

## Details and Notes

This super epic tracks the actual offboarding of VFS teams with contracts ending. It is blocked by defining what that process should look like: Offboarding - Launch offboarding process #2117

### Goal(s)

- Minimize loss of knowledge between different teams working on the same VA.gov product over time.

### Assumptions and Hypotheses

- We **hypothesize** that **if** we set clear expectations regarding documentation for VFS teams throughout their contract, **then** we will reduce the burden of documentation offboarding at contract end.
- We **hypothesize** that **if** VFS teams with contracts ending meet VSP documentation standards and undergo documentation offboarding reviews, **then** those teams will make it easier for future VFS teams to pick up work on the same product.
- We **hypothesize** that **if** we have well documented products, **then** new VFS teams will begin building sooner and have a better, more self-service onboarding experience.

**Comment by vbellissimo** [comment]
Cancelling/old task.
