### ISSUE TITLE
Discovery: IHM with BVA Appeals

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#20797]
How can we augment their existing workflow. They use a system called caseflow, not VistA - what information can we get?

- Understand the rest of the workflows
- how to build a solution
- propose a timeline

Need answers to questions: 
- [ ] research with hearing coordinators
- [ ] authentication - understand technical 
- [ ] what information can we get from caseflow?

----
- [x] Paras: Investigate How do we get phone numbers? how will we identify user? let VBA know we're waiting on a dependency from VAprofile, would it be useful for the veteran to send the case number instead?
- [x] Shane: NT username 
- [x] Andy: Can we add a URL parameter to the load balancer?
- [ ] Paras: Follow up with VBA on unscheduled visits
- [x] Julia: Mockups
- [x] Julia: Workflow draft
- [x] Shane: Research CDW MVI/MPI Tables
- [x] Shane / Paras / Julia: VEText Portal IMH walkthru
- [ ] Technical session for authentication now that we have answers back from the board

**Comment by Kennon-git** [comment]
we can add a parameter to the URL and pass that through. This will be hosted in the portal.

**Comment by kjduensing** [comment]
Mockups and workflow drafts shared this morning

**Comment by kjduensing** [comment]
Paras will schedule meeting w/ Julia next week.

**Comment by Kennon-git** [comment]
waiting for research flows. 

paras waiting on sal - been non-responsive

**Comment by pcshah1026** [comment]
Attached, you will find the messaging estimates for BVA IMH.  

[https://app.zenhub.com/files/133843125/3cbb5685-1f96-4ccd-a54c-e43b66868411/download]

**Comment by jwowk** [comment]
Per John Gosnell, BVA decided not to proceed with IMH
