### ISSUE TITLE
Determine documentation offboarding process and best practices

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2079]
## High Level User Story
As a VFS team whose contract is ending, I need to know what documentation to create or refine and where to put it, so that a future VFS team can pick up work on the same product.

## Hypothesis/(es)
**If** we set clear expectations regarding documentation for VFS teams whose contracts are ending, **then** those teams will make it easier for future VFS teams to pick up work on the same product.

## Goals
- Determine what offboarding should look like for VFS teams' documentation
- Create a process to efficiently and effectively communicate offboarding expectations to VFS teams

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`, `content-ia-team`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by vbellissimo** [comment]
Cancelling/old task.
