### ISSUE TITLE
[Jenkins/Vets-API] Better messaging when daily automated deployment fails

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#20792]
## The Problem
When the vets-API daily auto-deploy job fails because of a failing `master` vets-API CI, the messaging is ambiguous. There's no clear way for someone who is unfamiliar with the Jenkins job to know exactly:

1. What to go look at next
2. Why exactly the auto-deploy failed

### Walkthrough an Example
1. The auto-deploy job fails and notifies slack:
![image](https://user-images.githubusercontent.com/3077884/109874683-7011dc00-7c3d-11eb-98d9-10e44e904592.png)
2. A user clicks the link in slack to the auto-deploy job
3. A user scrolls the output and sees:
```
16:12:55  Build status: ERROR
16:12:55  GitHub reports problem with build. Cancelling pipeline
```
4. Now what?? 🤷 

## Extra Context
Slack link of a user asking this question - [link](https://dsva.slack.com/archives/C0MQ281DJ/p1614806209039300?thread_ts=1614805976.038300&cid=C0MQ281DJ)

## Work to be Done
- [ ] Improve the wording of the console output of the auto-deploy job when `vets-api` `master` CI has a failing build
- [ ] Include a direct link to the Jenkins job of the failing `master` CI

### Optional Work
- [ ] Improve the slack messaging for this case especially since right now it's just generic:

**Comment by rmtolmach** [comment]
Jenkins is being sunset in near future. No future improvements needed.
