### ISSUE TITLE
discovery - AVS: identify a process for end to end testing of Clipboard and AVS 

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20795]
Issues:

- [ ] ICN Inconsistencies - Testing AVS with Clipboard and Lighthouse will be difficult as the EMR (VistA ) and Lighthouse do not have pts with the same ICNs. 

- [ ] API work in AVS Not done yet. Suggestion was to get static data and use to present during the end-to end demo.

**Comment by shanemelliott** [comment]
https://dsva.slack.com/archives/C0136TS768M/p1616513665030900 -  Will get data necessary for demo tomorrow.

**Comment by shanemelliott** [comment]
Are there any additional details you'd like to share with your provider about this appointment?
I am experiencing lower back pain and I can’t sleep.
Are there any other concerns or changes in your life that are affecting you or your health? (For example, a marriage, divorce, new baby, change in your job, or other medical conditions.)
My toddler is not sleeping through the night and wants to sleep with us.
Do you have a question you want to ask your provider? 
Please enter your most important question first.
When do you think the COVID vaccine will be available? 
Do you think my spouse and I can get the vaccine at the same time?
Can you refer me for PT for my back?

**Comment by shanemelliott** [comment]
[https://app.zenhub.com/files/133843125/1808e8dd-2502-4a51-a139-919323aae826/download](https://app.zenhub.com/files/133843125/1808e8dd-2502-4a51-a139-919323aae826/download)
