### ISSUE TITLE
Yellow Ribbon: Change School Label to "Enter Full School Name"

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#20804]
## User Story

_As a user I would like to have a label that explains how to enter the search term because it would help me know to enter the full name of a school without needing to expand the search tip below.

## Expected Behavior

The current "School Name" label would be changed to say "Enter Full School Name" or something similar.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Our design guide asks us to use sentence case. 
So are we okay with "Enter full school name"?

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel that looks good to me, and it's plain language.

**Comment by zacharymorel** [comment]
PR merged. The changes should be live soon.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel on Staging, right?

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO can I close this issue now?

**Comment by MarciMcGuireGCIO** [comment]
Yep!
