### ISSUE TITLE
Discovery: content & IA offboarding approach

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2080]
## User Story or Problem Statement
Problem description. How might we (as content & IA) go about creating best practices for VFS teams' documentation when they are offboarding? 

## Goal
- Discuss what role Content & IA team should play in VFS teams offboarding
- Determine next steps for creating offboarding best practices for VFS teams regarding their documentation

## Acceptance Criteria
- [x] Content & IA team meet to discuss 
- [ ] Ideas from that meeting have been captured, next steps have been captured 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by vbellissimo** [comment]
Cancelling/old task.
