### ISSUE TITLE
Confirmation screen to send message form

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20817]
## User story
As a user, I want to see a confirmation page after I've hit "Send" that gives me options to: confirm sending the message, or go back to the Compose Message / Reply screen. 

## Acceptance Criteria
1. Upon hitting "Send" on the Compose Message or Reply page, route the user to a new page where they can confirm that they want to send the message
     - Header is carried over from the previous screen
2. Pull in mobile alert CC
     - Header 2: **Send this message?**
     - All copy is hard-coded
     - Large Button CC (primary action): Send message (UI only - routing is covered in a separate story)
     - Large Button CC (secondary action): Go back to editing
3. Selecting the secondary action button returns the user back to the form page

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449485451_Confirm_Send

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark 'Send this message?' as Header 2

**Send message**
- Title= "send message"
- accessibilityHint= “send this message” 
- accessibilityRole= “button”

**Go back to editing**
- Title= "go back to editing"
- accessibilityHint= “continue editing your message” 
- accessibilityRole= “button”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/4/2021 - Looks good in Android and iOS.  Closing.
