### ISSUE TITLE
Error alert | Unsuccessful send

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20819]
## User story
As a user, I want to see an alert that informs me if there was an error that prevented my message from sending. 

## Acceptance Criteria
1. If a message fails to send, display an error alert at the top of the Compose or Reply form page (depending on which form was used to send the message)
2. This alert displays when the backend fails to send the message for any reason. <strike>This includes the following error code:
     - SM903 - Send Message Service Error </strike> --> Not specifically checking for this error code, just displaying alert if the send message/reply endpoints return any errors
3. UX/UI details for mobile alert
     - Pull in mobile alert CC
     - Copy: hard-coded
     - Display 2 phone numbers with click-to-call capability _(Note: the icon for the TTY/711 number is not correct in the designs. Please use the icon that currently exists in this component)_
4. Preserve the state of the form content below the mobile alert, so that the user has the ability to try and re-send their message without starting over

## Designs
Example from Compose: https://adhoc.invisionapp.com/console/share/YM10HVPXJE7V/601892051
Example from Reply: https://adhoc.invisionapp.com/console/share/YM10HVPXJE7V/601892052

## Accessibility Implementation Guidelines 
- Mark 'Message failed to send' as Header 2

**Two phone numbers (links)**
- Title= Name of link, (e.g. 877-327-0022) 
- accessibilityHint= “Dials this number via your device’s call function” 
- accessibilityRole= “link”

## Dev checklist
- [x] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
FAIL 5/20/2021 - Mobile alert is displaying above wrong screen.  Should display above original message form (either compose or reply) but it is displaying above the send confirmation screen.

Bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/25056

**Comment by digitalken** [comment]
PASS 6/10/2021 - Looks good on iOS and Android.  Closing.
