### ISSUE TITLE
Support for VFS Teams: Documentation Offboarding

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2081]
## High Level User Story
As a VFS team whose contract is ending, I need to know what documentation to create or refine and where to put it, so that a future VFS team can iterate on the same product.

## Hypothesis/(es)
**If** we support VFS teams with capturing and storing documentation about their team and product before their contract ends, **then** the next VFS team who works on the product in question will be able to onboard more efficiently and build better veteran-facing apps

## Goals
- VFS teams capture critical, non-sensitive information about their product and team in an accessible place, such as the va.gov-team repo, to be accessed by the next team to work on that product.

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`, `content-ia-team`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by vbellissimo** [comment]
Cancelling/old task.
