### ISSUE TITLE
Successful send

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20818]
## User story
As a user, I want to see an alert that informs me if I've successfully sent my message.

## Acceptance Criteria
1. If the backend call to cancel an appointment is successful, display a success alert on a new page, called "Sent"
2. Display Back button in the header: 
     - Routes to the Inbox page
3. UX/UI details for mobile alert
     - Pull in mobile alert CC
     - Copy: Hard coded
4. At the bottom of the mobile alert, include a button labeled "Go to Inbox"
     - Selecting this button also routes to the Inbox page
5. The sent message should appear in the user's Sent folder

## Designs
https://adhoc.invisionapp.com/share/C910DKQGZPMW#/screens/446525919

## Accessibility Implementation Guidelines 
- Mark "Sent" as Header 1
- Mark "Message sent" in the mobile alert as Header 2
- Mark "Important:" as Header 3

**Go to Inbox button**
- accessibilityLabel = "go to inbox"
- accessibilityRole= "button"
- accessibilityHint= "go to the inbox page"

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/21/2021 - Looks good on iOS and Android.  Closing.
