### ISSUE TITLE
Attach file from action sheet (2 of 6)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20813]
## User Story
As a user, I want a the ability to attach files and photos to my message. 

## Acceptance Criteria
1. Selecting the **Select a file** button from the Attachments page opens the device's action sheet
2. Display the following options in the action sheet:
     - Camera
     - Photo gallery 
     - File folder
     - Cancel
3. Selecting "Camera" opens the app camera
     _- Note: Pull in the same camera / controls that are used in the Claims File Upload flow (#18599)_
4. Selecting "Photo gallery" opens the device's native photos app
5. Selecting "File folder" opens the device's action sheet, and presents options for ways to select a file from the device to select a file 
6. Selecting "Cancel" closes out the action sheet with no changes made
7. For all options in the action sheet, implement a filter on file size/types:
     - Size limitations:
       - Single attachment cannot exceed 3 MB
       - Total attachments in the message cannot exceed 6 MB
     - Acceptable types: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449230093

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/21/2021 - Looks good on iOS and Android.
