### ISSUE TITLE
Integration | send message + loading screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20816]
## User Story
As a user, I want the ability to send my message from the app, and also see a loading screen that tells me that the app is sending my message.

## Acceptance Criteria
1. From the **Confirmation** screen (#20817), selecting the "Send" button will make a call to the send (?) endpoint
     - This occurs in 2 flows: Compose Message and Reply to a Message
2. Display a loading screen while the app is working to send the message:
     - Pull in loading screen CC
     - Copy: "We're sending your message."

## Designs
https://adhoc.invisionapp.com/d/main/#/console/21165105/446525918/inspect

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/21/2021 - Looks good on iOS and android.  Closing.
