### ISSUE TITLE
Attachment page | File added (3 of 6)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20814]
## User Story
As a user, I want a the ability to a view the photo/file I've added before I confirm that I want to attach it to the message.

## Acceptance Criteria
1. Once a file has been added from the device's action sheet (#20813), return the user to the Attachments page
2. Below the page description, display the following:
     - If a photo has been uploaded from the Camera or Photo gallery, display a preview of the image (leverage #18603)
     - If a file has been uploaded from the File folder, display the name of the file that was uploaded (leverage #18635)
3. Photo preview: specify a max width and height so the photo doesn't take up the entire screen
     - _Note: this is handled differently than on Claims File Upload, which fixes the width/height of the photos so that 3 can fit in 1 row. For SM, we don't need to restrict the photo preview to 1/3 of the row, since the user can only upload 1 photo to this screen at a time._
4. Replace the "Select a file" large button with 2 large buttons:
     - Primary: "Attach" (UI only - routing is covered in a separate story)
     - Secondary: "Cancel" 
5. Selecting "Cancel" cancels out the Attachments flow and returns the user back to the Compose Message form, without any changes made to their message

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449230095

## Accessibility Implementation Guidelines
 
- Mark "File attachment" as Header 2

**Photos**
- accessibilityRole= image
 
**Attach button**
- accessibilityLabel = "attach"
- accessibilityRole= "button"
- accessibilityHint= "attach file to your message

**Cancel button**
- accessibilityLabel = "cancel"
- accessibilityRole= "button"
- accessibilityHint= "cancel and return to your message" 

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/21/2021 - Looks good on iOS and Android.  Closing.
