### ISSUE TITLE
Confirmation screen to remove attachments (5 of 6)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20815]
## User Story
As a user, I want to see a confirmation screen where I can confirm whether or not I want to delete an attachment from my message. 

## Acceptance Criteria
1. Selecting the "Remove" button from a file on the **Compose a Message** / **Reply** screen routes to a new page, so that the user can confirm whether or not they want to delete the attachment
     - On the confirmation page, maintain the same page header that's used on the previous page
2. Confirmation page displays a mobile alert
     - Pull in mobile alert CC
     - Copy is hard-coded
     - 2 large buttons
3. Primary large button: "Yes, remove attachment" (UI only. Routing not needed for this story.)
4. Secondary large button: "No, go back to message"
     - Selecting this button returns the user to the previous page, without making any changes

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449230097

### Form page
**Remove link**
- accessibilityLabel = "Remove"
- accessibilityRole= "link"
- accessibilityHint= "Remove attachment"

### Confirmation page
- Mark "Remove attachment?" as Header 2

**Remove attachment button**
- accessibilityLabel = "Yes, remove attachment"
- accessibilityRole= "button"
- accessibilityHint= "Remove attachment from this message"

**Go back to message button**
- accessibilityLabel = "No, go back to message"
- accessibilityRole= "button"
- accessibilityHint= "Go back to the previous page"

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/21/2021 - Looks good on Android and iOS but there is a minor bug that was logged on the text (and a11y label) for the actual remove button.  Tracked elsewhere so I'm closing this story.


https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23598
