### ISSUE TITLE
Confirmation screen to cancel Compose Message form

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20820]
## User story
As a user, I want to see a confirmation page after I've hit "Cancel" that gives me options to: cancel the draft, or go back to the Compose Message screen. 

## Acceptance Criteria
1. Upon hitting the "Cancel" large button on the Compose Message page, route the user to a new page where they can confirm that they want to cancel the draft
     - Header is carried over from the previous screen
2. Display a mobile alert on the page
     - Pull in mobile alert CC
     - Copy in the alert is hard-coded
     - Display 2 buttons at the bottom of the alert
3. "Cancel and go to Inbox" button (primary action UI)
     - Selecting this button routes the user to the Inbox page without saving or sending the message
4. "Go back to editing" button (secondary action UI)
     - Selecting this button returns the user to the Compose Message form. Their message should retain the same state as when they left it (i.e. any edits they made to field entries, attachments, etc. should be visible when they go back to the page)

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/448823099_Cancel_Message

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark 'Cancel this message?' as Header 2

**Cancel and go to Inbox button**
- accessibilityLabel= "cancel and go to inbox"
- accessibilityHint= “cancel this message and go back to the Inbox page” 
- accessibilityRole= “button”

**Go back to editing button**
- accessibilityLabel= "go back to editing"
- accessibilityHint= “continue editing your message” 
- accessibilityRole= “button”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/4/2021 - Looks good on iOS and Android.  Closing.
