### ISSUE TITLE
Load Balancing Version 2.0 (#67)

### ISSUE THREAD

**Issue by sjspakoski** [department-of-veterans-affairs/va.gov-team#20834]
Transferred on 4 Mar 2021. Original Column: IceBox, Original Labels: VEText

**Comment by shanemelliott** [comment]
Andy, is this done?

**Comment by wamccarty** [comment]
Essentially, but until we move completely to SSO, it is hard to say if there are more changes will be required.   The two are tied together.

**Comment by Kennon-git** [comment]
I will add a task to the inbox for this for discussion.
