### ISSUE TITLE
Access for Holden Hinkle (AWS)

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#20840]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Holden Hinkle (Legal name is Emmerson Hinkle)
- Please Provide your email.
   > holden.hinkle@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Testing Tools Team, VSP. Rails Engineer. Oddball, Inc.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCighaSYxWOCKEmwL/BytMHP5RFeYrgQFDhVHw0+GoT7wHsSLvZ9fHM8VFtONP15CMufx6FfCKKsU4zUV1buUCjF4OvM27GTww0lbjBQbsA6WnaK/TvbKHMP9BLi3D+wymvHHM37auE1RJ3iSt/lWDmoizimCS1LifDgP6HgRAV2kVt0v0FycJmwmX5Ruqu1/QY+SON1S8g0n0lh8oqIuD+A+DpVRZ6klowHd6lemma0fZ/fGf3fdpLnI5RceTKiE3+d5jAliFrO4ueG+sq58hR4uQ6raAQKhXICnuKA42Es7FZc4QIdErfU6G6dPeycm9GPdxFNFh5ntPPwyTJnqp2BoOxGIDg6vfmTFmIZSUQBwCrBsL2hmgmMevHvmhOKGzb94Tkwd5B+MScu33six6J7+kqBmhxUaDJcICKqaMPrsvxz64EiuX8HdAEDtHP61h3DbutYX6Ji8bsJnkX09NBriaMhb2strJw2sbteH/rkSpwWZkyG76LOUnvO2ZiZ18= holdenhinkle@Holdens-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why?
  - Currently, I need to run rails console in prod. I'm not sure what else I'll need access to in the future. Please give me access to whatever services a full stack engineer might typically need access to. Thank you!

**Comment by mleclerc00** [comment]
### For AWS Access:

User: Emmerson Hinkle
COR: Jeff-Hayter 
Approval required: @Jeff-Hayter

**Comment by mleclerc00** [comment]
@holdenhinkle

It looks like you already have socks access from what I can tell. Is this request solely for AWS or are you also having issues with socks?

**Comment by holdenhinkle** [comment]
It's solely for AWS. Thanks.

**Comment by Jeff-Hayter** [comment]
@mleclerc00 Approved for AWS.
