### ISSUE TITLE
Quality Assurance Feedback - Staging Review - Public Website - Campaign Landing Page

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#20846]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- The links for Events in the test environment do not appear to work. I'm assuming this is an environmental issue, but you may want to have a look:
  - [Veterans town hall in Pittsburgh, PA](http://preview-prod.vfs.va.gov/outreach-and-events/events/veterans-town-hall-in-pittsburgh-pa-0)
  - [Facebook Live: Community care info session
](http://preview-prod.vfs.va.gov/outreach-and-events/events/facebook-live-community-care-info-session-0)
## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
The visual issues described in [20629](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20629) are significant and must be addressed prior to release.

**Should:**
None

**Consider:**
None

**Comment by brianalloyd** [comment]
I think these are all related to the CMS preview prod environment, once we have a CLP published to staging I think these issues will be resolved.  Team is actively working #20629 during this sprint, and hope to have the identified bugs resolved.  Appreciate the review and support.

**Comment by brianalloyd** [comment]
@pjhill PW team has completed the work on "the visual issues described in 20629 are significant and must be addressed prior to release", can you review and close out in support.  Thanks.

**Comment by pjhill** [comment]
> @pjhill PW team has completed the work on "the visual issues described in 20629 are significant and must be addressed prior to release", can you review and close out in support. Thanks.

Thanks for the update, Brian. It looks like Tze is still working on verifying the fixes in the [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20629).

I just tried the preview page myself, and it doesn't look like all the image loading issues are resolved at least. I believe you all were floating the idea of promoting the preview page to a different environment with hopes that some of these issues might be resolved. Have you done that?
