### ISSUE TITLE
Duplicate Message (Durham)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20856]
## Task
Research - why did this veteran get duplicate messages? was it before deduping?

### Definition of Done
Team understands why a duplicate message was sent
Mitigation plan established if it is an ongoing issue

----------
----------

### Notes

Vet received a duplicate message after signing up for an appointment.
![Screen Shot 2021-03-04 at 12.29.00 PM.png](https://images.zenhubusercontent.com/60099ba779174e24ae511332/b02e2437-c50d-46e0-971f-50a12866dffa)

**Comment by shanemelliott** [comment]
We started excluding duplicates on 2/19.  this can be closed.
