### ISSUE TITLE
VCOVID Vaccine: Manage responses when a patient is already scheduled at that time. 

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#20855]
Rob, 

This means the vet had an appointment @ the time you attempted to schedule.  WE will need to include logic for this. 

Shane

From: Greer, Elizabeth (Mtn-Home) <Elizabeth.Greer2@va.gov> 
Sent: Thursday, March 4, 2021 9:26 AM
To: Durkin, Robert M. <Robert.Durkin@va.gov>; VHALOM VEText <VHALOMVEText@va.gov>
Subject: RE: Vaccine Outreach Missing Appt

The Veteran had a previously scheduled appointment with the BRI-RN PACT #3 clinic. Do you think when the Veteran was offered the open Vaccine slot on the same day/time as his previously scheduled appointment with the Nurse it caused a glitch in the system and it did not schedule the appointment in Vista?

From: Durkin, Robert M. <Robert.Durkin@va.gov> 
Sent: Thursday, March 4, 2021 9:50 AM
To: Greer, Elizabeth (Mtn-Home) <Elizabeth.Greer2@va.gov>; VHALOM VEText <VHALOMVEText@va.gov>
Subject: RE: Vaccine Outreach Missing Appt

Elizabeth,

So when VEText attempted to schedule this patient into the Mar 22 slot at 10am, VistA did not return an error code that VEText looks for to determine if the schedule attempt was successful or not, but VistA did return this message:

“Appointment in BRI-RN PACT # 3 already scheduled at the same time.”

I’m not sure what this means, and since there was no associated error code VEText assumed that the patient was scheduled successfully.

Is the above message meaningful to you?

Rob

From: Greer, Elizabeth (Mtn-Home) <Elizabeth.Greer2@va.gov> 
Sent: Thursday, March 4, 2021 8:16 AM
To: VHALOM VEText <VHALOMVEText@va.gov>
Subject: Vaccine Outreach Missing Appt

This Veteran shows on the Direct-Scheduled Appointments list as having a scheduled appt on March 22@10:00. But I am not showing a scheduled appt for this Veteran in the clinic.

 

Here is a screen shot from Vista showing he does not have any scheduled appointments in any Covid clinic.

**Comment by Kennon-git** [comment]
Rob to check if issue is fixed.
