### ISSUE TITLE
Setup Single Argocd

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#20872]
Setup a single Agrocd in the utility EKS cluster that can deploy applications to the utility cluster and all other EKS clusters.

**Comment by tskinn** [comment]
The argocd running in the utility cluster is now deploying traefik and other apps to the utility, dev, and staging EKS clusters.

**Comment by jbritt1** [comment]
Is this okay to close at this time?
