### ISSUE TITLE
Accessibility Documentation

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#20887]

**Comment by ayushchak** [comment]
Here's what we need:

1. Take a look at this checklist: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-accessibility-audit.md

You can use the TestRail account credentials that Ken Harrison uses to access the ideal list that VSP uses. Reach out to him with more questions.

2. Match that list with what actions we've been taking. Are there any steps that we're missing? If so, what are they and can we remediate this? If we are missing steps, please flag this to Bridget and Ayush. If we're not, please create a one-pager with the 

3. Pull together the following documents
-5 dev tickets where we have accessibility criteria as a sample of how we approach accessibility on a feature-by-feature basis.
- DF's accessibility plan


Template is here: https://docs.google.com/document/d/1jkylJgqzQWVTpQ04uPIEmitzDfWTNw6S381eny-ZS88/edit#

**Comment by msmanak** [comment]
added spreadsheet: https://docs.google.com/spreadsheets/d/1laJaAA69DLcozAuxCwBq74Itl8oPhxD270FV4877ppE/edit#gid=1651462990
