### ISSUE TITLE
EVSS encrypted PDF troubeshooting

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#20884]
I've learned by email the when sends the error EVSS_15001 it means that EVSS is rejecting an encrypted PDf.  In the 3 instances I spot-checked the PDF was a Vaccination record that was generated by the DOD.  It's encrypted but doesn't require a password to view or print. 
 I'd prefer that EVSS make the change to accept these pdf's.

```
Creator:        ActiveReports 11
Producer:       ActiveReports 11
CreationDate:   ��
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          2
Encrypted:      yes (print:yes copy:no change:no addNotes:no algorithm:RC4)
Page size:      612 x 792 pts (letter)
Page rot:       0
File size:      18747 bytes
Optimized:      no
PDF version:    1.3
```

**Comment by annaswims** [comment]
More details: http://sentry.vfs.va.gov/organizations/vsp/issues/40845/events/?project=3&query=EVSS_15001&statsPeriod=14d

`NAME` is the veteran's redacted name, but it looks like the file names suggest that many/most  the rejected docs are generated from the DOD.

11. OPR (1 Nov 14 - 31 Oct 15).PDF
AF422A.PDF
AF422A.PDF
AF469 profile.PDF
AF469 Shaving Waiver - NAME.PDF
apnea.PDF
NAME IMMUNIZATION.PDF
DA3881_I WANT A LAWYER.PDF
DD2766 IMMUNIZATIONS.PDF
DD2766 newest.PDF
DD2766 newest.PDF
DD2766.PDF
DD2766.PDF
DD2807 - Completed.PDF
DD2807 - NAME.PDF
DD2807 Medical.PDF
DD2807 NAME 23 July 21.PDF
DD2807-1.PDF
DD2807.PDF
DD2807.PDF
DD2807.PDF
DD2807.PDF
DD2807.PDF
DD2807.PDF
DD2807_Michelle Medico.PDF
DD2807Medical History.PDF
NAME IMM.PDF
FBI BACKGROUND INVESTIGATION.pdf
NAME IMMUNIZATION.PDF
NAME HST REPORT.PDF
Immunizations_NAME_14Jun2021.PDF
Immunizations_NAME_24Jun2021.PDF
NAME LT big toe Xray.pdf
NAME_Immunization.PDF
Outpatient Record_NAME_20210629 (ASIMS).PDF
PHA-2021.PDF
PHA-Dec2017.PDF
PHA-Dec2019.PDF
PHA-Dec2020.PDF
Post Deployment Health Assessment (PDHA).PDF
NAMEL_ Immunizations 1Nov19.PDF
NAME, Sexual Harrassment Vol Stat.txt
NAME AF Form 348 Final LOD.PDF

**Comment by annaswims** [comment]
brought it up with EVSS: https://dsva.slack.com/archives/C8R3JS8BU/p1631048213010900

**Comment by annaswims** [comment]
EVSS is tracking in EVSS-9873 https://vajira.max.gov/browse/EVSS-9873

**Comment by vhenry07** [comment]
Our work is complete but we will leave this open to track resolution with EVSS
