### ISSUE TITLE
Practice Area Feedback - Staging Review [Public Website - Campaign Landing Page]

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#20883]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
![image](https://user-images.githubusercontent.com/12564977/110026571-cc890000-7cfe-11eb-8451-ab6824e04991.png)

1. Images should always be the same size/ratio

2. Videos require intro text

**Should:**

Is there any way to format the bottom-most section the same way we do on [VA.gov](https://www.va.gov/
)? I'm referring specifically to the header, as seen here:

![image](https://user-images.githubusercontent.com/12564977/110027072-87190280-7cff-11eb-928a-9c1bc2a3648b.png)

in regards to the back to top component, is there a way to align the button the right-most "column" like this:
![image](https://user-images.githubusercontent.com/12564977/110027496-0ad2ef00-7d00-11eb-8517-2384a6610d73.png)
if this flexibility (utility class, maybe?) needs to be added to the component, lmk

On mobile, in the What you can do section, can we make the spacing in the gray boxes equal above and below? the spacing we have on desktop is perf if we can replicate that. 

![image](https://user-images.githubusercontent.com/12564977/110028300-11159b00-7d01-11eb-98b5-4c2f0a211f9c.png)

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by rtwell** [comment]
oh and for transcripts:
![image](https://user-images.githubusercontent.com/12564977/110029925-1247c780-7d03-11eb-9eb9-b9258f56d647.png)

**Comment by brianalloyd** [comment]
@kevwalsh dialing you into this ticket as well as I think Video sizing perimeters is likely a CMS fix.  I have this slotted for next sprint based on burndown and time box so let's thread here on solution-ing.

**Comment by brianalloyd** [comment]
Connected ticket [#20629](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20629)

**Comment by johnhashva** [comment]
@rtwell (with @brianalloyd FYSA) -- should the Download (PDF) links be aligned at bottom of the box to ensure we avoid this --

<img width="785" alt="CLP_PDF_Download link alignment" src="https://user-images.githubusercontent.com/63107147/110523158-bb196c80-80df-11eb-8d14-f1630a134027.png">

**Comment by rtwell** [comment]
@johnhashva that's actually [how it's designed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/CLP-Maximal.png). Note—mobile [looks a bit different](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/CLP-Maximal-mobile.png) as the space collapses.

i must have missed it, sorry about that!

**Comment by johnhashva** [comment]
Gotcha @rtwell  -- we'll get it fixed.  TY.

**Comment by brianalloyd** [comment]
Talked with @johnhashva and feel confident that we've accomplished all task in support.  Closing in support.

**Comment by brianalloyd** [comment]
Breaking out "Back to Top" recommendation to Ticket [#22087](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22087)
