### ISSUE TITLE
Access for Travis Hilton

### ISSUE THREAD

**Issue by thilton-oddball** [department-of-veterans-affairs/va.gov-team#2088]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Travis Hilton
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP - Tools & Improvements, BE Engineer, Oddball, Inc.
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDazNoJiOkHoGEevzhdFLR9giVDRr2MZzYLNMrRu6J6nnPBl11W9zC/O0FOsNHsgmhVDCBj5NcXmBDW94sUejHLhxLf/NIA0qMfZg6qBn17P6u7yOD9oX88x8Ou7jHHqYRmAo1GqgowL+dBIECWxU4qHoOyTTsYJkDjIJ+T4JwE7/VwRzpalFsLcIRm6mb++wlCb+11tblewY6kBs39BA1ElT5wHQPhw8MF35XBhVdBQihy1LZMTe+iOJUU8uu5UT6gP3FuL5qvlrYmp24JsozdUFG4/1g/9jd+g4om91TNq1O5EPSKj6kiYisChgIv//2qJDFDHfSHiD22ivhcRXtl travishilton@Traviss-MBP.attlocal.net

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by thilton-oddball** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter
COR: Yourself
User: Travis Hilton

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for both SSH and AWS.

**Comment by tskinn** [comment]
@thilton-oddball reach out in slack in #vsp-operations if you have trouble with your socks proxy. You should have access now.
