### ISSUE TITLE
Privacy & Security Review 

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#20886]
## Description
VSP typically conducts a Privacy & Security Review as part of the collaboration cycle. What modified version of this do we need to conduct before launching the app?

**VA Approver**
- Leanna, in partnership with technical team

**Date needed by**
- draft doc by 4/15

**Acceptance Criteria**
- [x] We know who signs off on the app from a security perspective
- [ ] We have documentation on mobile app security on GH
- [ ] We have approval documented on GH

## Reference documentation
- In progress: https://docs.google.com/document/d/1tKqz5dry4vhWGYc6mz6K0XZkUVvxVEsn86N8YLYBQBc/edit?ts=60429c0f#
- VSP Collab Cycle: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-privacy-security-review.md

## Status & Tasks
- 5/10: No need to have USDS person look, they didn't have enough context. Next step is to move this to GH and then we can close this ticket

- 4/26: John Kemp had light comments. Is the USDS person also looking?

**4/20**
- Jonathan to set up time to meet with security person at Ad Hoc, John Kemp
- Dror was curious about pin

**4/13**
- Finish draft of document 
- Talk to mobile app developer from USDS 
- Talk to security lead at Ad Hoc

**Comment by ayushchak** [comment]
In Progress here: https://docs.google.com/document/d/1tKqz5dry4vhWGYc6mz6K0XZkUVvxVEsn86N8YLYBQBc/edit?ts=60429c0f#

**Comment by leanna-usds** [comment]
Next steps: 

- research best practices for securing health app (do we need a PIN?) - i think @ayushchak?
- engage ad hoc security expert (@leanna and @cgreim)

**Comment by ambikaroos** [comment]
Doc is added to Github here (cc @jjulian): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product/MVP-launch/privacy-security-review.md

Approval by @leanna-usds documented here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/product/MVP-launch

Closing this ticket
