### ISSUE TITLE
Misc. updates to Claims File Upload

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20891]
## Acceptance Criteria
1. In the **Select a File** flow, remove the "Camera roll" option from the action sheet
     - Only the "File folder"/"Cancel" options should remain in the action sheet. _(Note: The "Camera roll" option will persist in the **Take photos** flow)_
2. Update the large button label from "Take photos" to "Take or select photos". This button displays on the following pages:
     - File Upload Request page
     - Take Photo page, when no photos have been added
     - Ensure that the accessibilityLabel is also updated to reflect the new copy
3. In the **Take Photos** action sheet, update the copy from "Camera roll" to "Photo gallery"

## Screenshots for reference
![Screen Shot 2021-03-04 at 1.28.02 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4b8ccddf-cfce-4cc8-adf4-4e1572e1f0e4)

## UX / Discovery work
https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1614021860699/69c02be078ff1d1a882a789809db284fa1c919ab

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/19/2021 - Looks good in both iOS and Android.  Closing.
