### ISSUE TITLE
RTC ORder Cnx By AVSCONNECTOR (#116)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20907]
"Happy Friday Everyone  😊

            Could someone assist me with this.

This RTC was entered but no appointment was scheduled off of the order.  When the clerk went in to schedule this patient the order is showing that is was dc’d by “AVSCONNECTOR,COA”

I know that when an appointment is showing that it was cancelled by  “AVSCONNECTOR PROXY” that it was cancelled by the patient via vetext but this one is only the RTC order and  did not involve any appointment.

Any info would be helpful.

Thanks so much!
Transferred on 4 Mar 2021. Original Column: In Progress"

**Comment by shanemelliott** [comment]
you can close this out.
