### ISSUE TITLE
End of Day Processing (#134)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20900]
Folded into #20664

"**Summary:**  
This is a feature for VEText that will assist MSAs in marking Veterans as no-shows.

As a Medical Support Assistant working in a clinic at the end of the day I can mark Veterans as a no-Show easily and all at one time.

We need to keep this on the list in the I Am Here Epic

**To Do List:**

**Update 10/06:**
 

Transferred on 4 Mar 2021. Original Column: In Progress, Original Labels: clean-up, question"

**Comment by shanemelliott** [comment]
This is a feature for VEText that will assist MSAs in marking Veterans as no-shows.

As a Medical Support Assistant working in a clinic at the end of the day I can mark Veterans as a no-Show easily and all at one time. 

We need to keep this on the list in the I Am HEre Epic.
