### ISSUE TITLE
design.va.gov Direct Deposit Pattern anchor link

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#20924]
## What happened?
The navigation anchor link to the Direct Deposit Pattern on design.va.gov doesn't work.  

Currently links to https://design.va.gov/patterns/form-templates#direct-deposit

Should link to https://design.va.gov/patterns/form-templates#direct-deposit-form

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/f5bb84f6-7dd6-4683-bf5a-c0efe78ce09f)

## Specs:
- Device: PC 
- Browser: Chrome
- Test User NA

## Steps to Reproduce
Current URL for link is: https://design.va.gov/patterns/form-templates#direct-deposit
Should link to https://design.va.gov/patterns/form-templates#direct-deposit-form 

## Desired behavior
Should link to https://design.va.gov/patterns/form-templates#direct-deposit-form

When you click "Direct deposit" in the left nav, it'll take you to the direct deposit pattern on that page

## Acceptance Criteria
- [ ] Navigation directs to https://design.va.gov/patterns/form-templates#direct-deposit-form

## How to configure this issue
- [ ] **Attached to a Milestone**  ??
- [ ] **Attached to Epic** ??
- [ ] **Labeled with Team**  
- [ ] **Labeled with Practice Area**  
- [ ] **Labeled with `Bug`**

**Comment by k80bowman** [comment]
Closing, this seems to be resolved.
