### ISSUE TITLE
VEText- API for Reporting (#78)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20937]
Folded into #21436

"Create

Transferred on 4 Mar 2021. Original Column: Decision Needed, Original Labels: VEText, Data"

CTO group that is doing centralized reporting for all cto products. at one point they were trying to get access to our data to integrate into that reporting, would need to expose an api.

Shane - is this moving forward?

**Comment by shanemelliott** [comment]
- [ ] Create Documentation of endpoints made available for the Reporting Ream , Julia and Patrick on vetext-data.
