### ISSUE TITLE
Message Detail Report modification (#158)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20931]
"1. In the last few weeks the report has changed. All the fields were previously filled in. Now if the Veteran sends more than one text message in a day, the Veteran name and Appointment fields are blank after the first message. I really need to be able to tell who sent the message without multiple filtering and searching.
2. We are an integrated site, VA Heartland West. I need to be able to run this report for Kansas City alone. I am getting our entire orbit and have to sort through it all
3. I cannot run this report for multiple days. I have to run each day at a time for weekend and holidays and combine them. This is very time consuming.
Transferred on 4 Mar 2021. Original Column: Intake)"

**Comment by shanemelliott** [comment]
resolved.
