### ISSUE TITLE
"Check My configuration  feature" (#Note)

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20936]
"Note - no details in the card
Transferred on 4 Mar 2021. Original Column: Intake"

**Comment by shanemelliott** [comment]
For VETExt.  WE have had many sites over the years change someting in their configuration and things stop working.  We need to either develop rules in the app that do not allow a user to change a configuration that will lead to unexpected outcomes.  OR, a button tht can run a sanity check on the VEText Configuration.

**Comment by Kennon-git** [comment]
Folded into #20765
