### ISSUE TITLE
Add accessibilityState to disabled buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20953]
## Acceptance Criteria
1. Add an accessibilityState to the large button when it's disabled:
     - Android accessibilityState: "disabled"
     - iOS accessibilityState: "dimmed"
     - Currently, this button appears on the **Ask for your Claim Decision** page _(test user with mock claims data: vets.gov.user+366@gmail.com)_

## Designs
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/440796655

**Comment by digitalken** [comment]
PASS 3/9/2021 - Good on iOS and Android. Closing.
