### ISSUE TITLE
Analytics - Implementation & Reporting

### ISSUE THREAD

**Issue by ayushchak** [department-of-veterans-affairs/va.gov-team#20993]
## Description
Before launch, we need to make sure all events we want to track are created in the codebase and available in Firebase/Google Analytics

**Acceptance Criteria**

- [ ] All events are created in the code
- [ ] All events are tracked in Firebase
- [x] Documentation on what KPIs we are tracking, and how, is in Github (link to spreadsheet from OKR doc)
- [x] Plan for how to report to internal stakeholders

## Reference Documentation
- Metrics spreadsheet: https://docs.google.com/spreadsheets/d/1G-Ru00IIEVCeMbYMqWVDTLO0f4WDdVrchPp0dIHM1N4/edit
- KPIs Mural: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1613007404272/108c1e88d13efc92238f084d47d942ed012eb51f
- OKRs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product/mobile-okrs.md
- VSP Analytics Review: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-analytics-request.md

## Status & Tasks
- 6/3: Ayush and Patrick finished Tier 1 metrics
- 5/27: Patrick working on this this week
- 5/24: Implementation moving forward
- 5/20: Subset of team met and are aligned on high level metrics. Ayush putting together an excel, Leanna pulling this into a slide
5/14: Ayush to send some high level metrics to Leanna, which she'll share with stakeholders and set expectation that this will be the metrics and will be sent on a weekly basis
- 5/14: Ayush and Patrick have a weekly meeting on implementation
- 5/10: we decided on the tags, and we're going to communicate it to VSP (Rachael, Joanne, Brian, Leanna)

- 5/3: Miscommunication between us and VSP. We should have a sync with Patrick/Ayush and Joanne and Brian Martin
- 4/26: VSP might help with this in their next sprint, we need them to tell us what the tag is for our event names
- 4/20: Patrick is tracking down who is in charge of Google Cloud Platform at VA
- Below conversation was had: Firebase can handle all our needs. Joanne might be able to help with dashboards in a couple sprints
- 4/16: Concern from VSP about implementing analytics (either VSP doing it, or mobile doing it ourselves) - needs a follow up conversation with Ayush/Jonathan/Patrick/Leanna

**Comment by ayushchak** [comment]
https://docs.google.com/spreadsheets/d/1G-Ru00IIEVCeMbYMqWVDTLO0f4WDdVrchPp0dIHM1N4/edit#gid=0

**Comment by leanna-usds** [comment]
+ scorecard

**Comment by leanna-usds** [comment]
@ayushchak can I help you with this at all?

**Comment by ayushchak** [comment]
Next steps // Metrics addition process:
1. Ayush and Patrick (Leanna optional) to collaborate on identifying each event and explaining it to Patrick.
2A: If it's front end, Patrick will pass this onto Bess, who will put it in a ticket for DF to put into the front end. 
2B: If it's a back end metric, we will pass it to the right team (secure messaging or broader mobile app) to incorporate into their ongoing Grafana work.

We will do 10-15 of these at a time, in tandem with other development work so that we will complete by June.

**Comment by ayushchak** [comment]
Dashboard shell for executives is here: https://docs.google.com/spreadsheets/d/18TEzJjnLCkyAn4DZOZS15czBlVw_jRgzMp3oR9LvCVY/edit#gid=915529237

**Comment by ambikaroos** [comment]
Closing since launch critical metrics are done, Tier 2 and 3 metrics are in progress but are not launch critical
