### ISSUE TITLE
Legal Review Needed?

### ISSUE THREAD

**Issue by ayushchak** [department-of-veterans-affairs/va.gov-team#20995]
## Description
Is there any sort of legal review the app needs to go through?

**Date needed by**
- 5/1

**Acceptance Criteria**
- [x] We know whether or not we need legal approval to launch a VA app
- [x] If we do need a legal review, a new ticket is added documenting what items are required from us

## Status & Tasks
- Leanna is chasing this down, do not have an answer one way or the other yet

**Comment by leanna-usds** [comment]
@ayushchak can you add detail to this plz and I'll track it down

**Comment by ayushchak** [comment]
This may or may not be required. On apps at other companies, there is a broader legal review making sure that we are not running into any liability issues, and we want to verify that this is not required.

Questions might include
- Any licenses required?
- Any liability notices that need to be added or removed?
- Any features that might require additional de-risking from a legal perspective?

**Comment by ayushchak** [comment]
Leanna will get terms from other apps for us to adapt to our context.

**Comment by leanna-usds** [comment]
I've asked everyone, the consensus is that we'll ask for forgiveness. (Jeff, Charles, Chris)
