### ISSUE TITLE
Mobile alert w/ a11y disclaimer for File Upload screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#20999]
## User story
As a user, if I rely on accessibility tools to navigate the mobile app, I want to see a disclaimer on the File Upload page informing me that this flow isn't fully accessible, along with guidance on where I should go for a more accessible experience.

## Acceptance Criteria
1. On the **Take or select photos** page, display an informational mobile alert below the page copy
     - Pull in mobile alert CC
     - Copy: hard-coded
2. Mobile alert persists on this page and cannot be dismissed

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/449809367
![Screen Shot 2021-04-20 at 8.31.25 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/caccee77-0519-4c73-a8d4-405adf7d550f)

## Accessibility Implementation Guidelines

- Mark "This feature is not yet fully accessible" as Header 2

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Blocked: awaiting content from VA

Open questions: 
1. should this alert also display on the File Upload flow?

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/3/2021 - Looks good on Android and iOS.  Closing.
