### ISSUE TITLE
COVID-19 form: button + routing

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21008]
## User story
As a user, I want a button to access the COVID-19 form on VA.gov. 

Note for dev/QA: this task will replace the COVID-19 form page.

## Acceptance Criteria
1. Update the UI on the **COVID-19 vaccines** card button:
     - [Default UI](https://adhoc.invisionapp.com/d/main#/console/21114574/445194522/preview): white background, blue border
2. Upon selection, the card button routes to the following URL out-of-app in the device's browser: 
     - https://www.va.gov/health-care/covid-19-vaccine/stay-informed

## Designs
N/A

## Accessibility Implementation Guidelines

**COVID-19 vaccines card button:**
- accessibilityLabel= "covid-19 vaccines"
- accessibilityRole= “menu item"
- accessibilityHint= "sign up for information on the covid-19 vaccine"

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Blocked: see open questions

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/4/2021 - Look good on iOS and Android.  Closing.
