### ISSUE TITLE
FE Tools documentation improvements backlog

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21014]
## Details 

There are a variety of documentation improvements needed across the platform. This ticket will be used to gather links of things that are out of date or need to be updated as we come across them, to be addressed in a batch in 2021. 

**Client application documentation homepage**: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started

**Va.gov Docs**: https://department-of-veterans-affairs.github.io/va.gov-team/

App Generator: https://github.com/department-of-veterans-affairs/generator-vets-website

**Comment by mchelen-gov** [comment]
Specifically regarding build & deploy process:
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/static-site
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/cms
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/build-deploy-flows
- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/deploy/
- https://vfs.atlassian.net/wiki/spaces/VP/pages/567607297/WIP+CMS+export+transformation+overview#Overview.1

**Comment by meganhkelley** [comment]
Document best practices for app architecture. May be out of scope for this docs updating initiative.

Mike Chelen (he/him)  8 hours ago
is it possible to describe some of these use cases and current architecture? that would help inform implementation options & tradeoffs

https://dsva.slack.com/archives/C01512KN35G/p1617121257178100?thread_ts=1617048921.136400&cid=C01512KN35G

**Comment by meganhkelley** [comment]
https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/9535

**Comment by meganhkelley** [comment]
https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/10568
