### ISSUE TITLE
*.vets.gov certificate renewal for November 2019

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2102]
The *.vets.gov certificate is coming up for renewal soon. We need to renew this soon to give Gateway Ops time to get this applied at the TIC.

**Comment by ricetj** [comment]
We have about 3 weeks

**Comment by wyattwalter** [comment]
Sent the new cert to Gateway Ops and opened a ticket for them to update at the TIC gateway.

**Comment by wyattwalter** [comment]
All of this is done internally. I let GW Ops know they can action this anytime and don't need to coordinate with us. Hopefully it'll get actioned soon and we can close this. For now, parking in "QA/review".

**Comment by wyattwalter** [comment]
Looks like this cert was replaced at the gateway now too.
