### ISSUE TITLE
Access for VBA OFM Benefits Delivery Protection and Remediation (BDPR)

### ISSUE THREAD

**Issue by dfein-rpg** [department-of-veterans-affairs/va.gov-team#21023]
- Please provide your Contracting Officer's Representative (COR) name.

Erick Zenteno, Erick.Zenteno@va.gov

- Please provide your name.

-Daniel Fein (access was previously terminated due to inactivity, account needs to be reactivated. Previous request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/8812)
-Justin Starkman (new user)
-Shikhar Jamuar (new user)
-Nathaniel MacArthur (new user)
-Mihnea Ionescu (new user)
-Alejandro Shea (new user)
-Hyewon Kim (new user)
-Nualwan Narong (new user)

(Submitted by Daniel Fein with support from Joe Niquette)

- Please Provide your email.

-Daniel.Fein@va.gov
-Justin.Starkman@va.gov
-Shikhar.Jamuar@va.gov
-Nathaniel.MacArthur@va.gov
-Mihnea.Ionescu@va.gov
-Alejandro.Shea@va.gov
-Hyewon.Kim@va.gov
-Nualwan.Narong@va.gov

(submitted by Daniel.Fein@va.gov)

- Please provide the name of your team, your role on that team, and the name of the company you work for.

We are currently being referred to as the VBA Benefits Delivery Protection and Remediation (BDPR) team (previously the VBA Fraud Waste Abuse (FWA) Team or the the VBA Data Quality & Fraud Prevention (DQFP) Team)

[if requesting SSH key authorization] Not needed

[Grant AWS Console access?]

YES
The VBA BDPR team requires access to OIT resources to support successful detection and investigation support of fraud occurring against VBA benefit recipients. Team will use this data to proactively act on suspicious authentication and login events, incorporating it into persistent monitoring capabilities deployed to detect potential fraud; and use data such as IP addresses to perform connected case analysis in support of investigations against criminal fraud rings and actors. After a meeting with Charles Worthington, ID.me and VA.gov where we discuss the recent detection efforts of fraud prevention we discovered that the data on CloudWatch is the missing factor to conflate identities from multiple datasets.

**Comment by jbritt1** [comment]
Awaiting feedback from Operations team leadership / COR: https://dsva.slack.com/archives/CBU0KDSB1/p1616510522421700

**Comment by jbritt1** [comment]
### AWS Access:

Users: there are quite a few in the list above
COR: Erick Zenteno
Approval needed: @Jeff-Hayter

**Comment by jhouse-solvd** [comment]
<img width="1688" alt="Screen Shot 2021-04-02 at 13 29 07" src="https://user-images.githubusercontent.com/46828900/113451728-75d31c80-93b7-11eb-97b1-0cbf46384c6f.png">

**Comment by jhouse-solvd** [comment]
Looks like we should be good to go based on above email response. 

@omgitsbillryan - if this is possible for you to do today or Monday, that would be great. Jeremy may also be able to follow up 

CC: @jbritt1

**Comment by jsev-io** [comment]
These users have been created and will receive credentials today.

**Comment by jsev-io** [comment]
One time Credentials for non-slack users provided to @dfein-rpg  to provide to team.
Marking Complete
