### ISSUE TITLE
Nav bar: Update icons & replace Appts with Health care

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21038]
## User story
As a user, I want to see a button on the navigation bar that will route me to the Health care page of the app. 

## Acceptance Criteria
1. On the bottom nav bar, replace replace the "Appointments" button with a "Health" button
     - Update label
     - Update icons for selected/unselected states
2. Additionally, update the nav bar icons for Home, Profile, & Claims, including the selected/unselected states
     - Folder linked below contains latest .svgs
3. Update accessibility labels (see guidelines below)

Note: Routing not needed for this story

## Designs
Nav bar icons: https://drive.google.com/drive/folders/1MQJxqFhiW8Bcj_-5g_ZCyx75oCQUjgrf?usp=sharing
Designs https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens

## Accessibility Implementation Guidelines

**Health nav bar button**
Title= Health
accessibilityRole= “tab"
Denote sequence: "3 of 4"
Denote when this tab is "Selected"

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/1/2021 - Looks good, UI and accessibility, on iOS and Android.  Closing.
