### ISSUE TITLE
VA Notify Email

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21033]
## Issue Description
After BDD claim submitted, is electronic text or email sent to claimant?

---
## Tasks
- [x] Provide Mike Hillegas with VA notify email

## Acceptance Criteria
- [x] Request sent
---

**Comment by annaswims** [comment]
Checked with VA notify 
https://dsva.slack.com/archives/C010R6AUPHT/p1615922725000700
Maybe this is the latest
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/images/Launched.png
