### ISSUE TITLE
NOD - Back-end Lighthouse Integration

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21045]
## Issue Description
Call Lighthouse endpoints and document frontend options

---
## Tasks
- [x] Code endpoints. 

## Acceptance Criteria
- [ ] ~Built version is shown to team and shared with Designer for further iteration, if needed.~ Code is written but still being review by VSP (I think it will take a little bit for them to review all of it (bunch of PRs))
---

**Comment by edmangimelli** [comment]
PRs
https://github.com/department-of-veterans-affairs/vets-api/pull/6210
https://github.com/department-of-veterans-affairs/vets-api/pull/6211
https://github.com/department-of-veterans-affairs/vets-api/pull/6212
https://github.com/department-of-veterans-affairs/vets-api/pull/6213
https://github.com/department-of-veterans-affairs/vets-api/pull/6235
