### ISSUE TITLE
IA Feedback - Midpoint review - STEM Automated Denial

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#21042]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- If you are customizing the breadcrumb label on the status detail page for the STEM application, I would recommend that you continue to use "status" or "status detail" within the breadcrumb so the purpose of the page is still clear in how it relates to the previous page and the URL.  The current tool does not customize the breadcrumb because we don't have good data, but if you are able to, I think this is fine as long as context is clear. 
- For the "More resources" section on the status detail page, consider using the related items/more resources content style similar to what is used in the very bottom section of this page: https://www.va.gov/education/how-to-apply/ (grey box for "Other VA benefits". 

**Consider:**
- For the section "What you should do if you disagree...", consider providing the link to the decision review content more prominently than linking to the forms.  The forms can update and change, and the decision review content area will ensure that the most recent form is provided, as well as other methods of requesting a specific type of review.

**Comment by amyknox** [comment]
@JenLJ @watersemma FYSA

**Comment by amyknox** [comment]
Great stuff. Thanks, Mikki!
