### ISSUE TITLE
Analytics Reporting Request for Chante Lantos-Swett

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#2105]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
I am looking for some metrics on the various contact us links shown on VA.gov. Specifically, the "contact us" drop down in the VA.gov header as well as the Contact Us links shown in the footer. See screenshots for visualization of the the links I'm referring to. 

    

## Timeframe for Analytics Requested
No pressing timeline but ideally before the end of this week if possible. 

## Analytics to Track Down
> Examples
> 
> - [ ] How many clicks do these links or buttons get and how does it compare to the most popular links on VA.go?
> - [ ] If possible, what percentage of clicks to these "contact us" links are the first click after arriving to VA.gov (let me know if this doesn't make sense and I can try and explain better).
> - [ ] The average number of clicks a user takes to get to one of these "contact us" links. 

## Which Product Questions are you trying to answer?
I am trying to get a better sense of how quickly VA.gov users start looking for a way to contact VA for help or support. I'm also trying to get a sense if users view VA.gov as a place to find out how to contact the VA. 

## Additional Comments
None

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by clantosswett** [comment]
![Contact_Us_Footer](https://user-images.githubusercontent.com/32465263/65906792-26aac680-e391-11e9-8084-83a8fe91d2a2.PNG)
![Contact_Us_Header](https://user-images.githubusercontent.com/32465263/65906793-26aac680-e391-11e9-91bc-a0183b6ed977.PNG)

**Comment by nedierecel** [comment]
@clantosswett I built a quick dashboard that summarizes interactions with any of the Contact Us links in the footer. Please use [this link to access it within Google Analytics](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/dashboard/07-qJyK9QS6TRS57Z8-8CQ/a50123418w177519031p184624291/). 

#### Observations
- In looking at the past 30 days, the phone link yielded almost 400 clicks per day. (11882 total events/30 days)
- The second report shows clicks to the phone number by device type. The majority of clicks come from a mobile device, but there's a small percentage that come from desktop.

There is one link coming in without information, which I've highlighted below. It may be the TTY link, but I need to confirm:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/63f87d4e-b02b-442e-9393-2fd504ac4abb)

**Comment by clantosswett** [comment]
Thanks @nedierecel It's kind of embarrassing to say this but I don't have access to GA. Is it possible to get me an account so I can sign in and take a look? Thanks!

**Comment by joanneesteban** [comment]
@clantosswett you should be set now!

**Comment by clantosswett** [comment]
@nedierecel Thank you so much for this initial report. One quick question.  I might have missed it but were you able to run this report for the header "contact us" links? They are found in the contact us drop down menu. Additionally, is there any way for us to see the users journey to clicking these links? I'm just trying to dig a little and see what our users activity looks like when it comes to finding a phone number to call. Thanks!

**Comment by clantosswett** [comment]
Attached is the spreadsheet that lists out where all phone numbers are listed on VA.gov. I am only really concerned with the top 7 numbers listed in the spreadsheet. 

[Va.gov call center inventory.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3687242/Va.gov.call.center.inventory.xlsx)

**Comment by nedierecel** [comment]
Thanks @clantosswett - this is very helpful! I'll add locations and amount of interactions with these phone numbers to the dashboards. 

FYI - When I pull the user journey reports, they will be separate from the dashboard.

**Comment by nedierecel** [comment]
@clantosswett I added the top 7 phone numbers to the list, and I'll work on adding the phone number in the "Contact Us" dropdown.

Is it okay to spin off the user behavior request into a new issue and tackle that at the end of this sprint or beginning of next?

**Comment by nedierecel** [comment]
@clantosswett I added the top 7 phone numbers to the list, and I'll work on adding the phone number in the "Contact Us" dropdown.

Is it okay to spin off the user behavior request into a new issue and tackle that at the end of this sprint or beginning of next?

**Comment by clantosswett** [comment]
@nedierecel that update is super helpful. Thank you! I will probably reach out over slack with some follow up questions. In the meantime, it is totally find to spin off the user behavior request into a new issue. Thanks!

**Comment by nedierecel** [comment]
@clantosswett One other item that I will spin off into another issue is the tracking of the `Contact Us` in the header. Though we're tracking the click on the phone number as a link, it gets lumped into the count for all clicks to 844-698-2311; the issue though is that we can't separate the `Contact Us` header activity from the rest. 

I'll close this issue for the initial dashboard and will tag you on the follow-up work.

**Comment by clantosswett** [comment]
Hmm okay. So are you saying that if any of the links shown in the contact us drop down are shown somewhere else on the site (i.e. footer, benefit hub pages, etc) then any clicks on those links will be counted toward total clicks on the contact us drop down in the header? Additionally, if a user clicks on the "contact us" drop down in the header but doesn't click on a link from the drop down, will that click not be counted or can it simply not be distinguished? I hope these questions make sense. Feel free to follow up by slack if you'd like additional clarification. Thanks!
