### ISSUE TITLE
Request access to Google Analytics [CMS team]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-team#21068]
# Request Google Analytics
Please grant read-only access to CMS team members to the "VA.gov CMS Backend" property

### Requesting Access for the following users

jane.xiong@agile6.com
vanessa.luxen@civicactions.com

### Requesting Access Removal for the following accounts that were off-boarded form the project

howard.brande@agile6.com
daniel.milller@agile6.com
nick.bloom@agile6.com
hayley.evans@agile6.com

## Access Requirements

- [x] Google Analytics "VA.gov CMS Backend" Property

## Date Required
No hard deadline, but in the next week would be great. Thank you!

## Product Team / External Team / VA Office

`#CMS-team`

---

### Definition of Done
- [x] Provide access to user
- [x] Ensure user received email confirmation

**Comment by bmcgrady-ep** [comment]
Hi @oksana-c - The requested users have been added to Google Analytics and should be receiving an email with their access. Also, I searched for all of the users you requested to be removed and it looks like their access has already been removed by someone else.

**Comment by oksana-c** [comment]
thank you @bmcgrady-ep
