### ISSUE TITLE
AMI and snapshot cleanup

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2106]
There was a tool written and dropped into the `devops` repo to clean up snapshots not associated with AMI's, but it hasn't been scheduled to run. This is leaving snapshots laying around that are detached from AMI's that we've already de-registered. We should do this regularly with the defaults (1 year) via Jenkins as a first step to get a sizable list of snapshots cleaned up.

https://github.com/department-of-veterans-affairs/devops/tree/master/utilities/remove_old_snapshots

There's some conflicting bits of info in the readme about this tool about what the threshold should be around cleaning up these artifacts. There's a sibling tool in this directory that de-registers AMI's and leaves these snapshots around, losing almost all metadata that we have about the snapshot, but then tried to remain true to some policy (that's not linked) in keeping the snapshots around. Need to figure out what's actually required here and either adjust these two tools.

**Comment by tskinn** [comment]
Currently there are 1737 EBS snapshots totaling 42,948 GB

**Comment by ricetj** [comment]
@tskinn is there any PRs for this guy?

**Comment by ricetj** [comment]
@tskinn can this guy get closed?
