### ISSUE TITLE
Quality Assurance Feedback - Midpoint Review - STEM Automated Denial

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#21069]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- 5 test cases already, hooray!
- I see some test cases are already passing. Please be sure to review / revisit these test executions before release.
- I know that test data is a concern for verifying some of the changes related to power of attorney. What's your timeline for attaining the appropriate test user / test data?

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
None

**Consider:**
None

**Comment by desireeturner** [comment]
@pjhill Regarding the test user for POA, that is something you have been supporting us on through @shawkey-daniel.

**Comment by pjhill** [comment]
> @pjhill Regarding the test user for power of attorney (POA), that is something you have been supporting us on through @shawkey-daniel.

Indeed -- I wasn't sure if you needed any other data / test credentials than the one that I've previously discussed with your team. Also, I want to hold myself accountable with this review.  Thanks for the response!

**Comment by shawkey-daniel** [comment]
@pjhill We need the POA user to also have > 180 of entitlement, so it would be denied. Thanks
