### ISSUE TITLE
Offboarding of Kalil Smith Nuevelle

### ISSUE THREAD

**Issue by sophiatareen** [department-of-veterans-affairs/va.gov-team#21061]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Kalil Smith Nuevelle
- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > VA API (Lighthouse), Software Engineer, June 2020, Ad Hoc
- Please provide any type of access they may have and their GitHub username. 
  > ex: SOCKS, Pagerduty, Google analytics, ect.
- SOCKS
- Pageduty
- Google Analytics
- dsvasupport, dsva, dsva cloud, dsva-vetsgov IAM account
- Github Username: kalilsn
  
 
## AC
 - [x] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @KevinMHoffmanUSDS, @drorva

**Comment by mleclerc00** [comment]
No socks, AWS, or Pagerduty access found

**Comment by mleclerc00** [comment]
His github user is no longer part of the VA Github Org

https://github.com/kalilsn

**Comment by mleclerc00** [comment]
@joanneesteban / @jonwehausen / @bsmartin-ep, could one of you confirm GA/DOMO access removal for this user if exists?

Much appreciated!

**Comment by bsmartin-ep** [comment]
@mleclerc00 - I see no GA/GTM/DOMO access for Kalil.
