### ISSUE TITLE
Health care landing page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21074]
## User story
As a user, I want to see a landing page dedicated to all health-related features in the app, including Appointments and Secure Messaging.

## Acceptance Criteria
1. Create Health care landing page, which can be accessed by selecting either:
     - Health button on the navigation bar (#21038)
     - Health care card button on the Home page
2. Page features include:
     - Header: "Health care"
     - This page should not display a Back button, since it is at the top of the stack
     - Display the Veteran Crisis Line banner 
     - Health button on nav bar reflects selected state
3. Create UX/UI for **Appointments** card button
     - Copy is hard-coded
     - Selecting this button routes to the Appointments overview page
4. Create UX/UI for **Messages** card button
     - Copy is hard-coded
     - Note: "unread" tag & routing not needed for this story
5. On the Home page, consolidate the Appointments & Messages cards into 1 single card for Health care. 
     - Label: Health care
     - Description: View your appointments and send messages
6. Update file structure for screens

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364857

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced
### 
## Accessibility Implementation Guidelines

**Mark "Health" as Header 1**

**Appointments card button**
- accessibilityLabel= "appointments"
- accessibilityRole= "menuitem"
- accessibilityHint- "view your medical appointments"

**Health card button**
- accessibilityLabel= "health"
- accessibilityRole= "menuitem"
- accessibilityHint= "go to health"

**Health care card on Home page**
- accessibilityLabel= Health care
- accessibilityRole= “menu item"
- accessibilityHint= "go to health"

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/2/2021 - Looks good, UI and accessibility, on iOS and Android. Closing.
