### ISSUE TITLE
Letters card button on Home screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21070]
## Acceptance Criteria
1. On the Home page of the app, create a new card button for "Letters"
     - Copy is hard-coded (see designs for reference)
2. Implement routing: selecting this card routes to the **Letters & documents** landing page

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364848
![Screen Shot 2021-03-17 at 2.52.17 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/269344f7-69d2-462b-b422-036e62e97581)

## Accessibility Implementation Guidelines

**Letters card on Home page**
Title= Letters
accessibilityRole= “menu item"

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/19/2021 - Looks good on iOS and Android, UI and accessibility.  Closing.
