### ISSUE TITLE
Common component: Footer button

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21083]
## Acceptance Criteria
1. Create common component for the footer button, which will appear on the Messages overview & Message detail pages
     - For app store launch, this button will have 2 variations: **Compose a Message** and **Reply**
2. When this button appears in the UI, it will be anchored at the bottom of the page, so that the page content scrolls behind it
3. Preliminary specs:
     - Background color: variable
     - Text color: variable
     - Text style: Mobile Body Bold
     - Icon: variable
4. For this initial implementation, the size & background color of the footer button should be the same as the bottom nav bar
5. Add the **Compose a Message** button to the following pages (UI only):
     - Inbox list
     - Folders list
     - Sent folders list
     - Drafts folders list
     - Deleted folders list
     - Custom folders list
     - Null pages: No messages in Inbox / Sent / Custom Folder
6. Add the **Reply** button to the following pages (UI only):
     - Message detail pages (Page header: "View message")

Note for dev: there is a follow-up task (#22400) to update the common component once we get additional specs from UX team

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364845
![Screen Shot 2021-03-08 at 10.25.38 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/05492300-0769-4150-a347-90b3453ee1b5)
![Screen Shot 2021-03-09 at 4.20.32 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ba027ae2-6ffb-4608-9f8c-cb05df1e827f)

**Comment by bessgreen** [comment]
.svgs: 


### Compose a Message:
![edit.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c0739b9e-d851-4c31-a8a6-0902d624bae8)

### Reply:
![reply.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/5c8ffca1-9b38-4ba8-8a64-e2f9ded1fa1d)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/7/2021 - Looks good in Android and iOS.  Closing.
