### ISSUE TITLE
Display read/unread message indicators

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21084]
## User story
As a user, I want visual indicators throughout the Health pages that inform me when I have unread messages.

## Acceptance criteria
Implement UI changes when there are unread messages:

1. On the Messages page, the **Inbox** selector will include  a <(#)> with the # of unread messages
     -  If there are 0 unread messages, do not display any number in the selector
2. On the Message page, the unread message ListItem(s) will display a blue dot to the left of the sender name
3. On the Sent messages page, display a "READ" indicator when the readReceipt attribute has the value "READ" 
4. On the Health landing page, the **Messages** card button will display a tag with the # of unread message
5. Display loading screen for the Health landing page:
     - Pull in loading spinner CC
     - Copy: "We're loading your health care information"

## Designs:
https://adhoc.invisionapp.com/share/C910DKQGZPMW#/screens/446399749
https://adhoc.invisionapp.com/share/C910DKQGZPMW#/screens/446420151
![Screen Shot 2021-03-05 at 5.45.30 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b163dc08-9efa-4459-89f8-862cf1a6b766)![Screen Shot 2021-03-05 at 5.45.02 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/17a5beff-b9ce-45e3-9127-8d06530aa3e8)

## Accessibility Implementation Guidelines

**Messages card button & Inbox selector** 
- When both of these elements display a #, tack on the following statement to the existing accessibilityHint:
- accessibilityHint: "You have <#> unread messages"

**Message ListItem:**
- Update the accessibilityHint to include: "Unread."
     - Note: If there are multiple, variable hints (ex: an unread message w/ attachments), these hints should be read in the order that they're displayed. Ex: "Unread. Has attachments. View details of this message."

**Comment by patrickvinograd** [comment]
Note - for read/unread status of a message, the `readReceipt` attribute will have the value `null`  for unread messages and `"READ"` for read messages.

**Comment by digitalken** [comment]
PASS 4/27/2021 - Looks good on iOS and small bug logged for accessibility on Samsung phones. (Minus before the number of new messages on the Health home screen.)

Also logged another bug that may or may not be valid, depending on expectations of polling for number of new messages remaining.  See https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23898

Closing because bugs are minor or edge-casey and tracked in zenhub separately.
