### ISSUE TITLE
Messages overview navigation

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21082]
## User story
As a user, I want to navigate through my messages and folders, as well as compose a message.

Note: This story applies to overview navigation and the Compose a Message footer.

## Acceptance Criteria
1. Selecting the **Messages** card button from the Health landing page routes to a new page, called "Messages"
2. The Messages page has two views: Inbox or Folders
     - Pull in segmented selector common component
     - _Note: The "(#)" new message counter on the Inbox segment is covered in a separate story_

## Designs
https://adhoc.invisionapp.com/share/C910DKQGZPMW#/screens/446420151

## Accessibility Implementation Guidelines

- Mark "Messages" as Header 1

**Segmented Selector**
- accessibilityLabel="inbox"
- accessibilityHint="view messages in your inbox"
- accessibilityRole="tab"
- accessibilityState="selected"
- For each tab in the selector, let the user know the element in the selector which is currently being focused and its place in the selector

**Compose a Message button**
- accessibilityLabel= "compose a message"
- accessibilityRole= "button"
- accessibilityHint= "navigate to the compose message page"

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/7/2021 - Looks good on iOS and Android.  Closing.
