### ISSUE TITLE
No 'Premium' MHV Account 

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#21088]
### **User Story**
As a user, if I cannot see secure messaging within the mobile app, I want to know what I need to do in order to upgrade my account. 

### **Acceptance Criteria** 
- If an MHV identifier is not found within MPI during login, the user will not have access to secure messaging
- When that happens, this is the expected experience: 
  - A screen displays w/ instructional copy describing the issue, how it can be resolved, and sets expectations about when secure messaging will be available to them. _(Did we land on the placement? After logging in? In place of the secure messaging home screen_?)
  - A link directs the user to the MHV webflow to establish a premium account.

**Comment by drjecker** [comment]
Here are a couple of proposed designs. Content needs work.

<img src="https://images.zenhubusercontent.com/602e6bbb345265c801d416d8/3bcef949-5193-4160-b6e1-4c274c976b49" alt="Screenshot of no MHV account open screen"  width="250">
<img src="https://images.zenhubusercontent.com/602e6bbb345265c801d416d8/60bb5d9e-dfb2-480b-b991-064ea2524eec" alt="Screenshot of no MHV account closed screen" width="250">

**Comment by drjecker** [comment]
@bessgreen Added a comment on our SM MVP Error States and Fields for DF doc that this is done, and you can find it in the Invision prototype here, but there isn't a clickthrough for it. https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/450085684_Not_Enrolled_MHV_Premium_
