### ISSUE TITLE
Inbox list (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21081]
## User story
As a user, I want to navigate through my messages, and see a list of messages in my inbox. 

## Acceptance Criteria
1. Create UI when the "Inbox" segment is selected on the Messages page
2. The Inbox page will display a list of messages. Messages are organized by the date in which the message was received, from most recent date to least recent
3. Each message ListItem should include:
     - Header: Name of sender
     - Line 2: **Subject: subject line** (ex: Appointment: Appt on March 2nd)
          - _Note: "subject line" is optional and won't always be returned from the API_
     - Line 3: Date & time the message was sent. Format: "18 Mar 2021 @ 1233 PDT". _Note: ensure that 'year' is also included_
     - _Note: The "unread" dot and the "attachments" icon are covered in separate stories_

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364845

## Accessibility Implementation Guidelines

- Mark "Inbox" as Header 2

**Inbox list**
- For each field:
     - accessibilityLabel= contents of ListItem
     - accessibilityHint= "view this message thread"
     - accessibilityRole= "button"
     - accessibilityValue= let the user know the element in the list which is currently being focused and its place in the list

**Compose a message button**
- accessibilityLabel= "compose a message"
- accessibilityRole= "button"
- accessibilityHint= "navigate to the compose a message page"

**Comment by johnnthough** [comment]
Hello are you in need of a UI designer?

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/9/2021 - Looks good in iOS and Android.  Closing.
