### ISSUE TITLE
Analytics Implementation or QA Support for VFS Platform Support/508

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#2108]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?

- Who is this request for?

    - [Jennifer Strickland]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - [VA.gov — Global UX, Authenticated Experience, Benefits & Memorials 1, eBenefits, Caregiver, Facility Locator, Benefits & Memorials 2, Medical Center Sites VISN 4, Unauthenticated Experience]
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - [https://www.va.gov/]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [N/A - seeking to monitor statistics over time]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Seeking to understand the number and behavior of users that sign in and users that do not, particularly to know the devices and browsers of visitors, time spent on page, paths followed (a.k.a. 'red paths')]

- Sample Users when authentication is required

    - [N/A]

- Test Users to replicate the event

    - [N/A]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@jenstrickland I've added you to the weekly report that is sent each Monday, and you should have access to Google Analytics. Please let me know if you have any issues accessing.
