### ISSUE TITLE
No Contacts Assigned 

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#21090]
### **User Story** 
As a user, if I have no contacts in secure messaging, I want to know how to get them so that I can send a message. 

### **Background**
- There will be cases where users have an MHV identifier (allowing them access to MHV features such as secure messaging), but do not have any secure messaging contacts assigned to them.
- Users are unable to send messages without assigned contacts. 
- This scenario can happen for a few reasons: 
  - Their provider does not use secure messaging
  - They have not yet been assigned to a triage group, and this assignment process is done manually by MVH coordinators using the secure messaging administrator interface

### **Acceptance Criteria** 
- When a user has no contacts assigned, a screen displays in place of the secure messaging inbox screen
  - Mobile App home screen -> Health -> Secure Messaging -> No contact screen

### **Current Experience**
This is the current message that displays in MHV:
<img alt="screenshot of current error" src="https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/dc669c3c-5725-4048-83a1-2e128bd31ee6" width="450">

**Comment by drjecker** [comment]
### Design
UI is here in Invision: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/448880937_No_Contacts_Error

### Notes for dev
This should display when a does not have at least one triage group that they are associated with. ([reference to unhappy paths mapping](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1614017071435/8061f2093dc4679b4b1da3ab3f20423c8f1c8f66))

- Button should go to Inbox
- Headline is Mobile Body Bold
- Paragraph is Mobile Body

API Error:
```
SM119:  'Triage team does not exist' when trying to create new message
 detail: 'Triage team does not exist'
```

### Copy
Headline: **We can’t match you with a provider**
Paragraph: We’re sorry. To send a Secure Message, both you and your VA primary care provider must be enrolled in the Secure Messaging program. Please contact your primary care provider to see if they can enroll you in the program.
Button: Return to Inbox

**Comment by drjecker** [comment]
@bessgreen this has a UI/design for it in Invision as notes above, but doesn't have a click through for it.
