### ISSUE TITLE
Draft definitions of Tiers 1, 2, and 3 and what constitutes a handoff from one to the next

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#211]
# User Story

As VSP/VA.gov/Contact Centers, I need to have standardized understanding of what constitutes a Tier 1, 2, or 3 issue so that I can efficiently hand issues off when appropriate without a lot of discussion/back-and-forth each time.

# Goal

Draft initial ideas around what constitutes Tier 1, 2, and 3 that the Triage team can discuss/iterate on with members of impacted groups once we connect with them.

# AC

- [ ] Initial draft of tier definitions / criteria in Triage GH documentation

**Comment by annaswims** [comment]
from the PWS: 

Provide Tier 2/3 support as necessary to resolve platform-originated bugs/issues discovered on the VSP. However, if bugs/issues originate from Veteran-facing services built or maintained by other VA teams Tier 2/3 support will not be required under this contract. Tier 2 Support is comprised of technicians experienced and knowledgeable about the Veteran-facing Services Platform that can assist end-users to resolve problems. Tier 3 Support is comprised of developers and engineers that analyze technical problems and define root causes. The Contractor shall expect approximately 60 calls per day, however more calls may be experienced when there are issues with VA legacy systems.
