### ISSUE TITLE
Set up content office hours

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21106]
## User story

As a VA.gov writer or designer who is creating content, I need dedicated time to collaborate informally with the VA.gov content leads in order to ask questions, workshop specific screens, and better understand the nuances of the VA.gov content strategy, voice, tone, and plain language standards.

## Issue description

Set up dedicated office hours. Pilot with small groups, and tweak and expand as we go.

**Comment by bethpottsVADEPO** [comment]
Done!
