### ISSUE TITLE
NOD - Usability Testing

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21119]
## Issue Description
What pain points exist in usability for NOD

---
## Tasks
- [ ] Complete testing

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by kevinstachura** [comment]
Testing is complete and the summary can be found in our NOD folder:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Notice-of-Disagreement
