### ISSUE TITLE
Add VA mobile URLs to forward proxies and update settings

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#2112]
## User Story
As a developer I want the VA Mobile base URLs added to the forward proxies, and the forward proxy URL added to the env's setting file, so that we can connect to VAOS services.

### Notes
Their sandbox env has a dynamic base URL :( so we won't be adding it at this time.

**Staging**: https://veteran.apps-staging.va.gov/
**Production**: https://veteran.apps.va.gov/

**Comment by wyattwalter** [comment]
Hey @kreek, can we get a good health check URL so we can monitor our connect to this service easily?

**Comment by kreek** [comment]
@wyattwalter they said we can use {base_url}/users/v2/ e.g. https://veteran.apps.va.gov/users/v2/ for prod.

**Comment by ricetj** [comment]
> @wyattwalter they said we can use {base_url}/users/v2/ e.g. https://veteran.apps.va.gov/users/v2/ for prod.

cc: @tskinn for awareness
