### ISSUE TITLE
Source-App-Name is not being sent on 10-10cg submission

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#21126]
## Technical Task

We need to be able to track application submissions via automated tooling so we can react to user needs as we find them. Currently for Grafana needs to filter on `HTTP_SOURCE_APP_NAME` which on the FE is referenced as `Source-App-Name` so we can filter by our specific application data.
  

## Expected Behavior

When a application is submitted we need to be sending `1010cg application caregiver assistance` as `Source-App-Name` on the FE

## Acceptance Criteria

- [ ] BE is receiving `HTTP_SOURCE_APP_NAME` so it can be filtered in Grafana

**Comment by LinnJS** [comment]
@kevinmirc do you mind confirming all the info in the ticket is described correctly as per our discussion this morning?

**Comment by kevinmirc** [comment]
Summary of issues:
- On `POST /v0/caregivers_assistance_claims` the `HTTP_SOURCE_APP_NAME` is not provided.
  - This causes the [Back-end to Front-end App Mapping Dashboard](http://grafana.vfs.va.gov/d/zGS4XzkMk/backend-to-frontend-app-mapping?orgId=1&var-data_source=Prometheus%20(Production)&var-backend_controller=v0%2Fcaregivers_assistance_claims&var-frontend_app=All&from=now-7d&to=now) in grafana to be missing a front-end source.
  - There may be other places this header is used, but I'm not aware of them at this time.
- On `POST /v0/caregivers_assistance_claims/download_pdf` the value sent for `HTTP_SOURCE_APP_NAME` is `caregivers-10-10cg-` which is not an acceptable value based on [the allowlist](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/statsd_middleware.rb))
  - This was confirmed in our production logs:
    ```json
    {"host":"9d7210ddc69d","application":"vets-api-server","timestamp":"2021-01-23T02:34:31.599749Z","level":"warn","level_index":3,"pid":89,"thread":"puma threadpool 005","named_tags":{"request_id":"REDACTED","remote_ip":"REDACTED","user_agent":"REDACTED","ref":"REDACTED","csrf_token":"REDACTED"},"name":"Rails","message":"Unrecognized value for HTTP_SOURCE_APP_NAME request header... [caregivers-10-10cg-]"}
    ```

**Comment by kevinmirc** [comment]
Please also consider the additional endpoint recently added: `POST /v0/form1010cg/attachments`. This endpoint should probably also receive the same app source header.

**Comment by dat-gcio** [comment]
Closing this out. Dashboard looks good.
