### ISSUE TITLE
Notice of Disagreement - hi-fi concept changes

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21121]
## Issue Description
Potential changes to hi-fi concepts from testing
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by kevinstachura** [comment]
Changes during this sprint have been completed and can be found in the prototype:

https://vsateams.invisionapp.com/share/8Y10I6K7DU9R#/screens/447558866
