### ISSUE TITLE
General Analytics Request for [Public Websites - Benefit Hubs]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#21134]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
This request is for the Public Websites team as we lean forward into a discovery of the benefit hubs and a potential optimization of the benefit hubs.  I'm looking to gain insight on the benefit hubs to include traffic, funnel details, user behaviors, bounce rate along with scroll depth and critical CTA datasets.   the below hubs are what we're looking to gain more insight into:

<img width="257" alt="Screen Shot 2021-03-05 at 10 40 09 AM" src="https://user-images.githubusercontent.com/70410912/110357231-4ddedc00-7ff8-11eb-8f14-d0ac9fdd4a88.png"> 

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- Public Websites - Benefit Hub Insights - Ideally we would like a 6 months read out on all things analytics as it pertains each of the benefit hubs mentioned above as the intent is to use the data to analyze trends and potential areas for optimization of the hubs.  

    
- What type of analytics support are you looking for?
  - [X] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze  - Discovery work is programmed for Q2 2021, so ideally would like to have this report back by end of March 2021 if possible.  

## Analytics to Track Down
- [ ] Traffic - page clicks 
- [ ] Bounce Rate 
- [ ] Scroll Depth 
- [ ] CTA clicks 
- [ ] Login details 
- [ ] User behaviors 
- [ ] Home Page Traffic 
- [ ] Top header/navigation clicks, scroll depth, redirects 
- [ ] Left-hand navigation metrix

## Which Product Questions are you trying to answer?
Ideally we would like a 6 months read out on all things analytics as it pertains each of the benefit hubs mentioned above as the intent is to use the data to analyze trends and potential areas for optimization of the hubs.  

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
@brianalloyd hi! We'll work on some getting you some links in Google Analytics to support this. We'll get back to you when we have more info!

**Comment by brianalloyd** [comment]
Thanks @joanneesteban i may add some additional details to this ticket tomorrow post meeting with @johnhashva.  I'll let you know post update.  Thanks for the assist on this, greatly appreciated.

**Comment by jonwehausen** [comment]
### Next Steps
- @laurensimpson14 to deliver various content grouping reports for Benefit Hubs

**Comment by laurensimpson14** [comment]
@brianalloyd Below are links to Google Analytics reports I was able to pull for you that pertain to the benefit hubs. I've set all of the dates to a 6 month period of September 15 - March 15. If you'd like to adjust the dates you can do so in the top right of each report.

* Starting with the home page, this report will show you all navigation clicks within the white benefit hub boxes that are over the blue background. This will help you understand which pages/hyperlinks under Health care, Disability, Education, and Records are the most used: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200915&_u.date01=20210315&_r.drilldown=analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&explorer-table.filter=navigation%20-%20zone%20one&explorer-table.rowStart=0/
* On the home page below the white boxes with the blue background are 11 other benefit hubs (Service member benefits, Family member benefits, Burials and memorials, Careers and employment, etc.). Here is a report to show you clicks to those: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200915&_u.date01=20210315&_r.drilldown=analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Navigation%20-%20Link%20List%20-%20(Service%20member%20benefits%7CBurials%20and%20memorials%7CFamily%20member%20benefits%7CCareers%20and%20employment%7CHousing%20assistance%7CPension%7CLife%20insurance%7CEducation%20and%20training%7CRecords%7CHealth%20care%7CDisability)%22,0%5D,%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2F%22,0%5D,%5B0,%22analytics.eventAction%22,%22EQ%22,%22Navigation%20-%20Link%20List%20-%20Pensione%22,1%5D%5D&explorer-table.secSegmentId=analytics.pagePath/
* Here is a report to show when a user clicked "VA Benefits and Health Care" on the main navigation at the top of the page. This will help you see how many users enter the funnel of that menu: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200915&_u.date01=20210315&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Navigation%20-%20Header%20-%20Open%20Top%20Level%20-%20VA%20Benefits%20and%20Health%20Care&explorer-table.plotKeys=%5B%5D/
* Once the "VA Benefits and Health Care" menu is open, this report will allow you to see which sub menu was expanded: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200915&_u.date01=20210315&_r.drilldown=analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10&explorer-table.filter=second%20level&explorer-table.rowStart=0/
* From the sub menus this report will show you which links were clicked: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200915&_u.date01=20210315&_r.drilldown=analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22Open%20Second%20Level%22,1%5D,%5B0,%22analytics.eventAction%22,%22PT%22,%22Navigation%20-%20Header%22,0%5D%5D/
* I've also pulled a report that is grouped by benefit hub that shows pageviews, average time on page, and bounce rate: https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20200915&_u.date01=20210315&explorer-segmentExplorer.segmentId=analytics.pageGroup1&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25/
* And, finally, this is a report that shows scroll depth. Something to note - we don’t have scroll depth tracking on every single page for the sake of hit volume. You can filter this report for certain pages by selecting “advanced” next to the search bar above the data, then select “Include” from the drop down, then “Page” from the drop down, then the match type you’d like from the drop down, and then type in the pages you’d like to filter for, and select “Apply”. Here is the report: https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200915&_u.date01=20210315&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Scroll%20Depth&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath/

That’s a lot of data! I hope this helps you with analyzing the trends and areas for optimization for the hubs. Once you identify a few potential areas feel free to create a ticket for us to pull more reports on those specific hubs. 

Please let me know if these links fully address your request and if you need anything else.

**Comment by brianalloyd** [comment]
@laurensimpson14 thanks so much for the effort and GA pull on this, I'll begin digging into the problem set and will circle back if additional resources are needed in support of our analysis.  Thank you so much.

**Comment by laurensimpson14** [comment]
Wonderful, hope you have a great day @brianalloyd 🌞
