### ISSUE TITLE
Common component: Custom picker

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21131]
## Acceptance Criteria
1. Create common component for a custom picker, which appears upon selecting a dropdown input field
2. Picker appears as a modal
     - Height of the modal is dynamic depending on the # of items in the list
     - For longer list items, the picker header remains locked, and the list items scroll behind it
     - Minimum amount of padding between the top of the screen & top of the modal: 60px
3. Display overlay in front of the page content
     - Fill: #212121, 80% opacity
4. Header
     - Cancel/Done controls: Mobile Body
     - Header: Mobile Body Bold
5. Items in list:
     - Mobile Body, 20px
6. Selected item:
     - Background-color: #E1F3F8
     - Icon: middle-aligned
     - Padding between text/icon: follow the current "Lists / Standard List / Rows / Simple Row" (see comment from Meli below)
7. If the picker header wraps to a new line:
      - Copy should be center-aligned
      - Copy should also be middle-aligned with the Cancel/Done buttons
8. "Cancel" closes out the picker with no changes made
9. "Done" closes out the picker and applies the selected item to the dropdown field
10. Lock the size of the picker so that it remains the same height/width when a user increases the text size on their device
11. Add animation when picker opens
12. Add specs to ReadMe

## Open design questions
1. Minimum amount of space between the top of the modal and the top of the screen?
2. Selected item:
     - How much padding between the text & the icon? 
     -  Should the icon always be middle-aligned? (If the text wraps to another line, should the icon have the same amount of padding above/below it?) 

## Designs
https://adhoc.invisionapp.com/d/main#/console/21180613/448387584/preview#project_console
.svg for selected item: ![Check.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f0bb1d0c-f56d-4969-a67a-68b7f6f13e3f)

## Accessibility Implementation Guidelines 

**Cancel button**
- accessibilityLabel= "Cancel”
- accessibilityHint= "cancels selection and closes the menu"
- accessibilityRole= “button”

**Done button**
- accessibilityLabel= "done”
- accessibilityHint= "confirms selection and closes the menu"
- accessibilityRole= “button”

**Placeholder (first menu option)**
- accessibilityLabel= "no selection" + sequence in list of the total count
     - Ex: "no selection. 1 of 229." 
- accessibilityRole="menu item" 
- accessibilityState= denote when "selected"

**Items in picker**
- accessibilityLabel= [item name] + sequence in list of the total count
     - Ex: "United States. 2 of 229." 
- accessibilityRole="menu item" 
- accessibilityState= denote when "selected"

## Accessibility Acceptance Criteria 

1. Can be accessed/navigated with voice control software
2. Font size of the dropdown input field is configurable 
3. Recognizes when the picker is open vs. closed, and as a result, would allow the app to:
      - display a focused state, and 
     - display an error state if it's opened/closed with no value selected

**Comment by msmanak** [comment]
**1. Minimum amount of space between the top of the modal and the top of the screen?** Ideally 60px for Full screen/400px for half screen
2. Selected item:
- **How much padding between the text & the icon?** Follow the current "Lists / Standard List / Rows / Simple Row" which is what I pulled the list from. 

- **Should the icon always be middle-aligned? (If the text wraps to another line, should the icon have the same amount of padding above/below it?)** Good point, what is it like for other rows within the app

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/23/2021 - Functionality.
FAIL 4/23/2021 - Accessibility.  Not hearing any text for choices or I'm hearing irrelevant text.  See bug #23265 for details.

**Comment by digitalken** [comment]
PASS 4/30/2021 - Looks good on iOS and Android.  Closing.
