### ISSUE TITLE
Adjust the VAMC side-navs to work on the Preview Server

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#21133]
## Issue Description
Currently, sidebars on VAMC pages do not support the preview server, meaning that previews of any page under the VAMC sections do not include a sidebar. This is because the sidebar's React component relies on a [helper function](https://github.com/department-of-veterans-affairs/vets-website/blob/26d23e642c19ae07b853bfad63b0af31e760c5ac/src/platform/site-wide/side-nav/helpers.js#L140) that doesn't support the URLs that the preview server uses. 

We should adjust this behavior, so that VAMC content editors can see the sidebars when they preview pages. It will help build confidence in their previews

## Front end tasks
- [ ] It might be fixed by now already but we received an alert from the preview server about a facility side nav being misconfigured. Failed to find a facility sidebar with a name that matches the VAMC office label "VA Oklahoma City health care".
- [ ] the separate issue about the sidebar is that during render, the sidebar checks some stuff about the document location, and doesn't account for the preview server.

## Acceptance Criteria
- [ ] Side-Navs properly render on Preview Server 

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
Updated @brianalloyd thanks for making the ticket

**Comment by ncksllvn** [comment]
cross-linking to dupe, https://github.com/department-of-veterans-affairs/va.gov-team/issues/15710

**Comment by acrollet** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-cms #5236](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5236) via [**ZenHub**](https://www.zenhub.com/)
