### ISSUE TITLE
Update the Cypress Viewport Updater Bot so it automatically updates the newly added default viewport values

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#21132]
The following was recently added to `cypress.json` to set the default Cypress viewport to the top desktop viewport used by VA.gov users:

```
  "viewportWidth": 1920,
  "viewportHeight": 1080,
```
## Tasks: ##
- [x] Update these values automatically when the Cypress Viewport Updater runs each month.

## Acceptance Criteria: ##
- [x] The Cypress Viewport Updater Bot will successfully update the `viewportWidth` and `viewportHeight` values in `cypress.json`

**Comment by pjhill** [comment]
Good call -- this should be a small maintenance thing we should tackle in the near future.

**Comment by holdenhinkle** [comment]
This was already done.
