### ISSUE TITLE
Update burial allowance rates with new October $ values

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#2114]
@AnneHurley - Please update the allowance rates on the Github instance, so it's live by the 10/1 effective date - it'll have to go in time for 2pm deploy. Please loop in @peggygannon or @RLHecht for PR review. 

This page needs to be made in Github because we're still not able to make this page go live via Drupal. 

- On this page https://www.va.gov/burials-memorials/veterans-burial-allowance/  
- On the GITHUB instance

## Rates info from Angie's email
[Per convo - update the amounts that are captured on our burial hub page. We can add missing table info from VBA source pages later, after the Drupal version w/other SME feedback goes live with rest of hub.]

1.	Update the Burial allowance Corporate rate tables to reflect the statutory increase for Veterans who die while properly hospitalized at VA expense 
a.	$796 effective 10/01/2019

2.	Update the Plot allowance Corporate rate tables to reflect the statutory increase for Plot Allowance 
a.	$796 effective 10/01/2019
3.	Update the State Cemetery Allowance Corporate rate tables to reflect the statutory increase for State Cemetery Allowance
a.	$796 effective 10/01/2019
4.	Update the rates for Philippine Veterans as follows:
a.	Full Rate = $796 effective 10/01/2019
b.	Half Rate = $398.00 effective 10/01/2019

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] _Make live in Github on October 1
- [ ] _Make same change to Drupal version. so when Burials hub goes live, this change is not lost

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

@Karak888 fysa

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  @Karak888  I will get the first two rates updated, but Jen since we don't yet know where those other two rates live, I will hold off on those for now, correct?

**Comment by jenniferlee-dsva** [comment]
Yes please and thank you. 

"Those other two rates" - yep, exactly @AnneHurley . Once the whole hub goes live via Drupal, we should look at the non-CEM legacy source pages (referenced in Angie's email) and see if the info lives there; and add them to our hub allowance page table.

**Comment by AnneHurley** [comment]
SME Angie Smith said not to worry about placing those 2 rates on VA.gov for the time being, so this task is done.
