### ISSUE TITLE
Content for Unauthorized for Claims Screen

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#21146]
# User Story
Write content for what a user should see if they are not authorized for Claims.

# What the web shows today
![Screen Shot 2021-02-17 at 8.39.13 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/b87d6875-4a86-4d67-841c-6bca16ebc51d)

**Comment by ayushchak** [comment]
Scenarios:

![image.png](https://images.zenhubusercontent.com/5fe0ec4b688d8a4f0c4e9df3/6c00e328-c317-4090-b63b-969c91fbb8a7)


#We can't find any claims for you
##We don't see your information in our claims database. If you think this is an error and need additional information, please visit [VA.gov resource](link) or (XXX)XXX-XXXX.

**Comment by bridgethapner** [comment]
Thank you! Using this for the UI design will leave the phone # as a placeholder for now
