### ISSUE TITLE
Midpoint Review Debt Resolution Team, Financial Status Report

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#21140]
## Steps to complete Midpoint Review 
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members.
- [ ] VSP: Schedule meeting with VSP reviewers and VFS team attendees (listed below).
- [ ] VFS: At least 2 days before scheduled meeting/review, attach all artifacts listed below and ensure VSP reviewers have appropriate access to secured applications.
- [ ] VSP: Create feedback tickets and link to the Midpoint Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to VSP feedback tickets.
- [ ] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061). 
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/FSR-Product-Outline.md)
- [Link to staging](https://staging.va.gov/manage-va-debt/request-debt-help-5655/) - we will be working through a mocked authenticated experience, found by clicking "Start your application without signing in" on the introduction page.
- Link to content brief (if applicable) - N/A
- [Link to research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021/research-plan.md)
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_ - N/A
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) for QA practice area review - N/A

## Meeting attendees from requesting team
- Product Manager (required): Leah Keeler
- DEPO product lead (recommended): Matthew Self
- Anyone else from your team who significantly contributed to the artifacts provided (required): Rebecca Walsh, Riley Orr
- Content, IA, accessibility, and QA specialists (if applicable): Danielle Thierry, Mikki Northuis

## Scheduling
Would you like this review to be asynchronous? Please refer to the Midpoint Review guidance for the difference between a synchronous meeting and an asynchronous review.
- [ ] Yes
- [x] No
- [ ] Whichever is faster
 
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0%40group.calendar.google.com&ctz=America%2FNew_York)? 
**date/time** 3/9, 3/10, or 3/11, flexible
 
Please note:
- Time slots are required for both synchronous meetings and asynchronous reviews.
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 2 business days from request date.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
hey @rebeccawalsh  - for the synchronous vs. asynchronous question, we're essentially asking if you want to have a meeting with us (synchronous) where we share with you our high level findings and give you an opportunity to ask questions OR do you want us to just write up our findings in a ticket, no meeting required (asynchronous). Either option will give you a full write up of our findings.

**Comment by rebeccawalsh** [comment]
@shiragoodman Synchronous is fine - if all of the time slots were taken, we'd pick asynchronous if it would satisfy the checkpoint faster.

**Comment by shiragoodman** [comment]
@rebeccawalsh we ask for 2 full days to review, so the earliest I can get you in is Thursday 3/11 at 1:30 ET. I'll send the appointment out by EOD.
