### ISSUE TITLE
[FE] Direct deposit for edu: UAT

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21142]
## Background

We are running UAT for the direct deposit for edu feature between 3/11 - 3/17.

## Tasks

- [x] Manage feature toggle
- [x] Add participants to the list of people who can see direct deposit for edu in production
- [x] Attend sessions

Separate tickets will be created in the event that there are issues that need fixing.

**Comment by erikphansen** [comment]
I'm putting a 3 on this. It should be easy, but there are a fair amount of sessions spread over many days. It's mostly just disruptive and I really don't know how to score something like this. ¯\_(ツ)_/¯

**Comment by Samara-Strauss** [comment]
@erikphansen totally fine! I understand this stuff is a bit of a disruption from code time, but it's also important! 3 sounds good.

**Comment by Samara-Strauss** [comment]
UAT is wrapped! We can close this out.
