### ISSUE TITLE
Access for Theo Bentum (AWS)

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#21154]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Theo Bentum
- Please Provide your email.
   > theo@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Frontend Tools Team, Frontend Engineer, Ad Hoc LLC
- Requesting SSH key authorization?
   > NO. I should already have my SSH key authorized. I am only requesting AWS access.

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why?
     > I need access to services that involve the Front End Deployment of the vets-website (VA.gov). Primarily S3.

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Jeffrey Hayter
Name: Theo Bentum

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS.

**Comment by jbritt1** [comment]
Temporary credentials provided to user.
