### ISSUE TITLE
GIBCT Inaccessible in local builds

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#21150]
The Comparison tool currently will not load on a local build. When a user tries to access http://localhost:3001/gi-bill-comparison-tool/ an error message is displayed.

### Steps to reproduce
1. On a local build (using the master branch for `vets-website`, `vets-api`, and `gibct-data-service`), attempt to access http://localhost:3001/gi-bill-comparison-tool/

### Expected behavior
1. GIBCT Landing Page is displayed
![Screen Shot 2021-03-08 at 2.41.57 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b155fe4d-dd8d-4d99-b7a3-9b49d96a463a)

### Actual behavior
1. User receives the following error:
![Screen Shot 2021-03-08 at 2.42.06 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4174de1d-1b99-4ba8-973d-9a3cd894a2f0)

2. Console error:
![Screen Shot 2021-03-08 at 2.01.21 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a61e3616-f0e7-44df-9a1f-e7e3ac341edb)

3. Response at http://localhost:3000/v0/gi/calculator_constants
![Screen Shot 2021-03-08 at 2.42.24 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2e42769a-0235-427c-9ca5-53a11da16bc8)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/797

**Comment by delli-gatti-michael** [comment]
local testing complete
