### ISSUE TITLE
alert the auth exp team if the DirectDepositEmailJob fails

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#2115]
work with the platform team to create an email alert that is sent to an auth exp developer if the `DirectDepositEmailJob` fails. this job should never fail and it is a security risk if it doesn't work.

**Comment by Justin-Pickett** [comment]
@lihanli will follow up with the Platform team regarding this ticket.

**Comment by Justin-Pickett** [comment]
@lihanli any updates regarding this ticket?

**Comment by Justin-Pickett** [comment]
Closing this ticket out.
