### ISSUE TITLE
Update references to SSOe

### ISSUE THREAD

**Issue by jimiray** [department-of-veterans-affairs/va.gov-team#21176]
Update references to SSOe / SAML attributes.

**Comment by AGarcia-Clarity** [comment]
@nsoutouras I'm pretty ticket can be closed as work has already been completed by Trevor (ref: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login/ssoe/ssoe_saml_response_attributes.md).

This might be a duplicate ticket.
