### ISSUE TITLE
Add sr-only span ahead of error message

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21179]
## Issue Description
As a Veteran using a screen reader I need to differentiate errors and labels so I know what actions need to be taken.
As the Facility Locator team, we need to ensure the facility locator error messages meet design system standards 
This from [Josh's feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18351#issuecomment-793031718) on #18351

## Tasks
-[ ] Add in a sr-only span with "error" written inside it ahead of the error message itself 
span class="sr-only">Error<span

## Acceptance Criteria
- [ ] Error messages alert screen readers clearly that an error exists.
- [ ] Josh approves change

**Comment by mmiddaugh** [comment]
Looks good to me! 
![image](https://user-images.githubusercontent.com/55411834/111657784-62c62700-87d1-11eb-8298-1be0ea36eaf2.png)

@joshkimux can you validate when you have a moment?

**Comment by joshkimux** [comment]
<img width="1200" alt="Screen Shot 2021-03-18 at 12 56 51 PM" src="https://user-images.githubusercontent.com/14154792/111665756-6cf41f80-87e9-11eb-8fe7-20fc36395937.png">

It's working great! Thanks team!
