### ISSUE TITLE
Access for Jeff Wallace

### ISSUE THREAD

**Issue by jw81** [department-of-veterans-affairs/va.gov-team#21187]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
## ( NOTE :: Just requesting AWS access.  I already have SOCKS proxy access. )
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Jeff Wallace
- Please Provide your email.
   > jeff.wallace@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA API, Engineer, Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPcmQn/wa+nB2IEv55Ba1FWO+d9+Z6cNcadl33UYB2yNZQutoCD38U+38rQ0c2gfigpq4h+Fg+BzitgnrdaIJqBqlwPhbp1NV93AuKuojnKQ2Rm9VdHDSGVj9kFDbXK4Zrb92kNOO9zh/sZex8CuZcTKcZ/6eTvUsh61DvIkjxqtoHnVg3KjhUBgrAE+aCoRcpo99iDGXMP7+9mevOgLF0HIeHUzZI2UANd2uEfl2RUmBjDClyqCwxV89IOYnhQaK1j94qV+Fwao8T8TAAsNS5R4E/E4iqs+R+VZ30i3NxJFXSXZ3Dor/0r2g+MtMcKWrJLBNKkOiup57vIRBR5jaV7LhgL/8y1Qx6NEiuTIqS4WZ1FTYTR4UsGWthNtkWkmA0viXnfSY6p/dni/C//OVNGtRByQshg7kaLM5XCqocIKTUgMd4Pkxch6SvIJOhHHFiBMHZL43bzPGNiqE2qjW+CR5jsAAtVfPiqJwBag/d1LRGq3gHPTE4qm5X4jjiB9U= jeffreywallace@Jeffreys2013MBP.lan
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
      Production access to maintain and deploy services.

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Cecilia Lee
Name: Jeff Wallace

**Comment by tskinn** [comment]
for posterity linking to https://github.com/department-of-veterans-affairs/va.gov-team/issues/19972

**Comment by jw81** [comment]
@tskinn or @department-of-veterans-affairs/vsp-operations, any chance there's been an update on this ticket?

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS.

**Comment by mleclerc00** [comment]
Thanks, will get around to this today
