### ISSUE TITLE
Establish rotational Product Support Model across all practice areas

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#2118]
How can we take the shared support model that engineering practices use, but expand it to design, product, analytics etc

**Comment by rroueche** [comment]
- This seems like it could be better tackled w/scalability
- Isn't this a goal of the Service Design team to figure out?

------------------

high effort, but low priority right now bc want to see if we can get a more scalable state first w/existing model but introducing automation and improvements identified by Service Design team. Not sure we need to blow up our current model and move to a rotational (or other) one yet.

**Comment by andreahewitt-odd** [comment]
Service design is working on a VSP support model that will include this work.
