### ISSUE TITLE
Sent messages list (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21195]
## User story
As a user, I want to navigate through a list of my sent messages.

## Acceptance Criteria
1. Selecting "Sent" from the Folders page routes to a new page
2. "Sent" section header is 20px from the top nav bar
3. Under the "Sent" section header, display a list of sent messages. Messages are organized by the date in which the message was sent, from most recent date to least recent
4. Each message ListItem should include:
     - Header: Name of recipient
     - Line 2: **Subject: subject line** (ex: Appointment: Appt on March 2nd)
          - _Note: "subject line" is optional and won't always be returned from the API_
     - Line 3: Date @ time. Format: "18 Mar 2021 @ 1233 PDT". _Note: ensure that 'year' is also included_

Note: "Read" receipt, unread tag, and attachment icon are covered in a separate ticket. 

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447368262

## Accessibility Implementation Guidelines

- Mark "Sent" as Header 2
- For each field:
     - accessibilityLabel= contents of ListItem
     - accessibilityHint= "view details of this message"
     - accessibilityRole= "button"
    - accessibilityValue= let the user know the element in the list which is currently being focused and its place in the list

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/8/2021 - Looks good on iOS and Android, closing.
