### ISSUE TITLE
Folders page (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21194]
## User story
As a user, I want to navigate through my folders page, including my sent messages & custom folders.

## Acceptance Criteria
1. Create UI when the "Folders" segment is selected on the Messages page
2. This page is organized into 2 sections:
     - Folders
     - My Folders
3. Folders section 
     - Create ListItem for "Sent" messages (routing not needed for this story)
4. My Folders
     - This section is service-driven and can contain any number of ListItems are returned from the API (associated routing not needed for this  story)
     - Display the list of custom folders in alphabetical order
5. If the "My Folders" section is null (i.e. a user does not have any custom folders), hide this section from the UI

## Designs
https://adhoc.invisionapp.com/share/C910DKQGZPMW#/screens/446420152

## Accessibility Implementation Guidelines

- Mark "Folders" and "My Folders" as Header 2

**My Folders list**
- accessibilityLabel= "my folders list"
- accessibilityRole= "menu"
- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list

**Comment by johnnthough** [comment]
Hello are you in need of a UI designer?

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/7/2021 - Looks good for UI.  Accessibility fails.  Logged bug so I'm closing this story.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22897
