### ISSUE TITLE
View message detail & thread (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21197]
## User story
As a user, I want to read my message and view other messages in the same thread.

## Acceptance Criteria
1. Selecting a message from the Inbox/Sent/Custom folder list routes to a new page, called "View message" _('m' should be lowercase)_
2. Content header displays on a grey background above the ListItems
     - Format for content header: Subject + (optional) Subject line
     - Ex: "Appointment: Appt on March 2nd"
3. Page content below the header is organized by a series of individual messages (ListItems) that can be expanded/collapsed to view the contents of each message
     - Pull in step table CC (#17295) for this page
4. Create UX/UI when a message is expanded:
     - Sender name
     - Date & time the message was sent
     - Message body
5. When a message is collapsed, hide the message body from the UI
6.  Messages are organized by the date in which the message was sent, from least recent to most recent
7. On default navigation to this page, only the most recent message should be expanded
     - Multiple accordions can be expanded simultaneously

**Not covered in this ticket:**
     - Attachments icon 
     - Reply toolbar button (#21083)

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447478540
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447478541

## Accessibility Implementation Guidelines

- Mark Subject + Subject line as Header 2

**Step Table**

For each item ("message") in the table:
- accessibilityLabel= Text
- accessibilityHint="view more details"
- accessibilityRole="spinbutton"
- accessibilityState= Denote when dropdown is expanded or collapsed
- Ensure the heading and date text are grouped together and read together by the screen reader
- Ensure dropdown area does not "trap" the keyboard focus

**Reply button**
- accessibilityLabel= "reply"
- accessibilityRole= "button"
- accessibilityHint= "reply to this message"

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/15/2021 - Looking good in Android and iOS.  Closing.
