### ISSUE TITLE
Testing - Talk with teams representing the staging testing use cases to understand their needs and challenges more deeply

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#2119]

**Comment by clantosswett** [comment]
Any sense of timeline on this issue and the broader epic? The inability for call center agents to replicate a veterans' signed in view on VA.gov could be a potential blocker to standing up some work in the near future, so it would be great to get a sense of timing so we can determine if we need to build out a process to the current work arounds.
