### ISSUE TITLE
Message detail w/ attachments + open in file viewer

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21198]
## User story
As a user, I want to read my message detail and see any attachments that were sent in the thread.

## Acceptance Criteria
1. Update UX/UI for the message detail page to include a section for attachments
2. This section will appear at the bottom of each accordion when that message contains at least 1 attachment
     - If a message does not contain any attachments, this section should not appear in the UI
3. Pull in attachment link CC 
     - Refer to designs for spacing/padding when there are multiple attachments
4. Selecting an attachment link will open the file in the device's file viewer
5. Display a loading spinner while the device works to open the file

## Designs
Launch page: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/448493167

## Accessibility Implementation Guidelines

- Mark "Attachments" as Header 2

For each attachment:
- accessibilityLabel= Text
- accessibilityHint="view this attachment"
- accessibilityRole="button"

- For each item in the list, let the user know the element in the list which is currently being focused and its place in the list

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/26/2021 - iOS and Android on UI.
FAIL 4/26/2021 - iOS on accessibility. (Android passes.)

See bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23801
