### ISSUE TITLE
Display 3 photos per row on photo upload screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21196]
## Context for this task
In the Claims File Upload > Photo upload UX, the photo previews are currently a fixed height/width. This means that depending on a user's device size, this page will either display 2 or 3 photos in a single row. In order to minimize the amount of white space, we want to update this so that regardless of device size, the page can display up to 3 photos in a row. 

## Acceptance Criteria
1. On the Take photos page (#18603), update the way the app displays photo previews. The height/width of the photo previews should be dynamic so that the page can display up to 3 photos in a single row (regardless of device size). 

## Screenshots of current experience
Larger device w/ 3 in a row
![Screen Shot 2021-04-06 at 9.28.29 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b95dcd86-c685-4fbd-a4a2-b56d2aebaf09)

Smaller device w/ 2 in a row: 
![IMG_B28ECCBEA670-1.jpeg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/70e6417c-0509-452d-8e59-39788498d704):

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/15/2021 - Looks good on iOS and Android.  Closing.
