### ISSUE TITLE
Draft initial approach for global "output" - sharing expected impact and resolution w/wide audience of stakeholders

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#212]
# User Story

As any interested/impacted person across the VA ecosystem, I need a way to learn when an issue has been resolved, so that I know I no longer need to follow up or can take any necessary action.

# Goal

Draft an initial approach (whether it's an email list ppl can join, slack channel, or other global option) that acts as the standard way we "wrap up" issues (i.e. communicate they are complete). We can test this at a small scale and iterate/pivot as needed.

# AC
- [ ] Test solution decided upon
- [ ] Test solution exists
- [ ] Test solution is documented in GH within Triage documentation

**Comment by minafarzad** [comment]
@rroueche @gunsch are y'all working on this?

**Comment by gunsch** [comment]
Not currently AFAIK

**Comment by kfrz** [comment]
@gunsch @rroueche is the spirit of this ticket essentially captured in this extant documentation: https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Postmortems ?

**Comment by gunsch** [comment]
> @gunsch @rroueche is the spirit of this ticket essentially captured in this extant documentation:

@kfrz I don't think so? Postmortems are one piece of the picture, but I think "how do we proactively communicate that outward" is a separate piece
