### ISSUE TITLE
Reexamine eBenefits links in Claim Status Tool. 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#21207]
As part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/8212 we learned that  Active users are being logged out after viewing eBenefits https://github.com/department-of-veterans-affairs/va.gov-team/issues/21201 .  That is a bug that should be addressed, but it also seems like we're directing users to eBenefits for features that we'd now expect users to complete on VA.gov.  We should reexamine the "Additional services" section. 
<img width="1009" alt="Screen Shot 2021-03-09 at 8 58 47 AM" src="https://user-images.githubusercontent.com/19188/110481658-ce174700-80b5-11eb-86ad-616c0bc91a20.png">

**Comment by Mottie** [comment]
It looks like on other pages, we just tell the user to call the VA help line instead.

**Comment by Mottie** [comment]
cc: @saderagsdale
