### ISSUE TITLE
Attach a file FAQ page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21200]
## Acceptance criteria
1. On the Compose a Message and Reply form pages, the "How to attach a file" helper link routes to a new page
     - Header is carried over from the previous screen
2. All content is hard-coded
     - See designs for copy & formatting 
          - _Note: the linked designs should be used as guidance for the UI. Please use existing common components (including their specs/padding), rather than the specs in the linked designs_
3. Below the page content, display 2 numbers with click-to-call capability:
     - 1-877 number
     - TTY / 711 number: pull in the TTY component (note: the designs display an icon for the TTY number that is different than the icon we're currently using in the component. Please display the icon that's used in the component - screenshot below)
4. Preserve state on the Compose/Reply form when the user navigates back

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/448889662
 Correct TTY icon: 
![Screen Shot 2021-04-20 at 2.20.26 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/6f575d14-6567-41d5-b177-17aa0fd12ed5)

## Accessibility Implementation Guidelines

**How to attach a file button** (on the Compose/Reply form)
- accessibilityLabel = "how to attach a file"
- accessibilityRole= "link"
- accessibilityHint= "view more information about how to attach a file to your message" 
____
- Mark "How can I attach a file to a Secure Message?" as Header 2

**Two phone numbers (links)**
- Title= Name of link, (e.g. 711) 
- accessibilityHint= “Dials this number via your device’s call function” 
- accessibilityRole= “link”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by drjecker** [comment]
@bessgreen FYI not sure this will be a tooltip. The icon I used def looks like one so I may need to replace it, but how it works hasn't formally been decided. It may just link out to a screen. I've created a ux ticket [#22080](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22080) for it if you want to review that.

**Comment by drjecker** [comment]
Copy is below:

**How can I attach a file to a Secure Message?**

- Select the Add Files button on a new Secure Message or on a Secure Message that you are replying to.
- Select the file you would like to attach.
- Select the Attach button.

**Note:** If you are unable to attach a document to a Secure Message confirm that your document meets the requirements for size and type:

- You may attach up to 4 files which must be in one of the following formats: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx.
- The file size for a single attachment cannot exceed 3 MB and the total size of the attachments cannot exceed 6 MB.

If your problem persists, please contact the My HealtheVet Help Desk. We’re here Monday–Friday, 8:00 a.m.–8:00 p.m. ET.

877-327-0022 

If you have hearing loss, call TTY:

711

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/6/2021 - Looks good on iOS and Android with the exception of the following:

Minor bug on bullet formatting - bullets are not indented.
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/24371

Minor bug on accessibility for the FAQ link button.
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/24369

Closing.
