### ISSUE TITLE
STEM AD: Update content to be more plain language

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#21203]
As a developer, I need to update the content of the STEM automated denial in the claims and appeals tool so that it is more plain language and easier for the user to understand.

## Assumptions:
1. Completed behind feature flag `stem_automated_decision` (#13829)
2. Login to claims page here: https://staging.va.gov/claim-or-appeal-status/
3. 10203 denials are added to page found here: https://staging.va.gov/track-claims/your-claims

## Acceptance Criteria
1. The contents of the STEM automated denial card page match supporting artifact 1.
2. The contents of the STEM automated denial details page match supporting artifact 1.

## Supporting Artifacts:
1. [Current Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a88b7378be8502a5d1b7aaeed8cfc12dd27d94bd/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content-V2.md)
2. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222481/296056346/preview)
   a. [Link to prototype for folks without accounts](https://bahdigital.invisionapp.com/share/CUIAG8PZ85J#/screens/296056346)
3. [Original Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d51b0f460e00651843eb79c2480543eda72591f8/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content.md)

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16328

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1513&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
Needs periods here
![Screen Shot 2021-03-15 at 8.29.23 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4ad1a681-7dd7-4484-8c4d-6a34e218b4b4)

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16358

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me

**Comment by amyknox** [comment]
UX 2/2

1. There shouldn't be a period at the end of this line (Image 1)
2. Too much spacing between heading and follow-on content in right sidebar (Image 2)
3. Not enough spacing after H3's You didn't meet the following criteria for the Rogers STEM Scholarship / You met these criteria for the Rogers STEM Scholarship and the following bullet points (Image 3)
4. Download PDF links (Image 4)
-- Should open in a new tab
-- When you click through on a download PDF link and try to get back to the status details page, you get logged out and have to reauthenticate to return to the status details page

**Image 1**
![image](https://user-images.githubusercontent.com/41081945/111806075-fc600800-88a7-11eb-82a2-1a8d6a5992f3.png)
 
**Image 2**
![image](https://user-images.githubusercontent.com/41081945/111806218-24e80200-88a8-11eb-80c5-1d1bb7243ec4.png)

**Image 3**
![image](https://user-images.githubusercontent.com/41081945/111806473-65478000-88a8-11eb-9d74-835b30731b67.png)

**Image 4**
![image](https://user-images.githubusercontent.com/41081945/111806898-d4bd6f80-88a8-11eb-8cf0-89be4c6688ca.png)

**Comment by amyknox** [comment]
PDF link aria label should also include the following

`aria-label="Opens in new browser tab" `

**Comment by amyknox** [comment]
In the works as of 3/22 stand up

- Remove period from the end of the info alert message at the top of the page
- Update aria labels for form downloads

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16457
-Remove period (21203)
-Update download links (21570)

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me!

**Comment by watersemma** [comment]
UX Review 2/2: This checks out for me!

**Comment by sonntag-adam** [comment]
Closing story.
