### ISSUE TITLE
Document error states on the 10-10CG (Current state)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21213]
As a Veteran
I want to understand the status of my submission
And what next steps are necessary 
After submitting the 10-10CG

## Acceptance Criteria
- What types of errors are possible
- What status code does it generate
- What message do Veterans see for each error type
- What next steps are Veterans encouraged to take
- Documented in Github as a flowchart

**Comment by sshein** [comment]
Met with @kevinmirc and @LinnJS to start on this - created initial flow, Kevin will translate to a spreadsheet w/ screenshots
![10-10CG User Submission Flow.png](https://images.zenhubusercontent.com/5d4c59b26a82cc000106fdf0/70c50a9d-7483-4a0b-aa40-044343cfde4e)

**Comment by kevinmirc** [comment]
Just a quick update on where this stands:

I've gathered recordings and images of the user-experiences based on different errors occurring during submission. I will be documenting this in our va.gov-team repo: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/ux-capture.

Currently, I only have documentation of the mapping and an explanation of each error, but I'll be uploading videos and images of each page and state on Monday.

Thanks!

**Comment by sshein** [comment]
ooh this looks exactly like what I was thinking - yay!

**Comment by kevinmirc** [comment]
Okay.... Documentation of each error flows is complete. You can find this information can here: 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/ux-capture.

For each error scenario, I've added the messaging as text and image. I've also documented the "call-to-action"s we provide to the user and what actions they are able to perform in that state.

Videos are too large to upload. So, what I did instead is upload images in a series so you can see what UI appears throughout the submission process. Most notable is the "On Error" column in the images section. This shows what the user sees as soon as the error occurs (with no scrolling around the page). For each error case, I've also added a "Message" column to see the error clearly (which sometimes requires scrolling by the user). To see the full-size image, right-click the image and select "open in new tab" or "open image in new tab".

Please let me know if you'd like me to include any additional information or have suggestions on the format.

Thanks!
