### ISSUE TITLE
Finalize flowchart of error states on the 10-10CG 

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21216]
As a Veteran
I want to understand the status of my submission
And what next steps are necessary
After submitting the 10-10CG

## Acceptance Criteria
- What types of errors are possible
- What status code does it generate
- What message do Veterans see for each error type
- What next steps are Veterans encouraged to take
- Documented in Github as a flowchart

Based on designs created in #21212

**Comment by tchrisdyer** [comment]
Closing this as it is already documentented.
