### ISSUE TITLE
HLR GUID

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21218]
## Issue Description
Kelly Link dug into your Grafana and GA metrics in order to compare them to ours to ensure nothing is being lost.  We realize that the current setup is NOT AT ALL conducive to troubleshooting.  I’m curious your thoughts on how soon we could get the change in to start saving the HLR response GUIDs.

Link to [discussion](https://dsva.slack.com/archives/C5AGLBNRK/p1615239398110500). 
---
## Tasks
- Start saving HLR response GUIDs.

## Acceptance Criteria
- [x] Implemented solution
---

**Comment by edmangimelli** [comment]
@annaswims is this ticket and [your ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20862) overlapping?

**Comment by edmangimelli** [comment]
@kellylein we do save the GUID for failed requests (at least temporarily).

(unfortunately, our biggest problem at the moment are timed-out connections where we never get a GUID back.)

**Comment by annaswims** [comment]
the change to log HLR id to a table went in today. https://github.com/department-of-veterans-affairs/va.gov-team/issues/21447

We should start seeing id's in the table as soon as the deploy goes out today (it's delayed)
