### ISSUE TITLE
Create Design - NOD

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21225]
## Issue Description
Create hi-fi concepts for NOD
---
## Tasks
- [x] Create design

## Acceptance Criteria
- [x] Completed design
---

**Comment by kevinstachura** [comment]
The hi-fi designs have been created and are located here:

https://vsateams.invisionapp.com/share/8Y10I6K7DU9R#/447558866_NOD_-_Info_Page
