### ISSUE TITLE
[Epic] Migrate burials and memorials benefit-adjacent content from tier 1 to R&S

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#21226]
## High Level User Stories
As a Veteran, service member or caregiver, I want to get my specific questions about burials and memorials compensation answered quickly without having to dig into long pages to find what I need. I want to be able to find Q&As that will help me get the information I need.

As a member of sitewide content, I want to migrate the benefit-adjacent burials and memorials compensation content into resources and support. I want to assess each page within the burials and memorials hub and determine what's tier 1 and what's tier 2. Then create drupal articles to house this content.

**Note:** This work has no IA component/considerations and will not require a concurrence step with program office SMEs (though we're definitely alerting them to this work). We are not migrating whole pages--simply lifting and shifting benefit-adjacent Q&As from existing pages into new articles in R&S.

## Hypothesis or Bet
If we group the self-help/support content in resources support where each Q&A can have its own H1/url, it will be easier to find. And users will be able to more easily get the information they need.

## Definition of Done
All burials and memorials pages have been assessed, and the benefit-adjacent content that currently lives in tier 1 has moved to resources and support.

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by RLHecht** [comment]
This work is complete. Closing.
