### ISSUE TITLE
[Bug] Financial Status Report - Unauth'd Intro-page sign-in redirect error

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#21229]
## What happened?
On Staging, **[Request help with VA debt (VA Form 5655)](https://staging.va.gov/manage-va-debt/request-debt-help-5655/)** (FSR) form unauthenticated Intro-page, sign-in redirect failed to return to form's Intro-page.

## Specs:
- Devices: [so far, Win10 PC desktop, Galaxy S8, Galaxy Tab S6, but I'm surmising it's device-agnostic]
- Browsers: [so far, Win Chrome, Samsung Internet, but I'm surmising it's browser-agnostic]
- Test User _(if applicable)_:
  - `vets.gov.user+228@gmail.com` (Colder)
  - `vets.gov.user+14@gmail.com` (Jerry)
  - `vets.gov.user+1@gmail.com` (Greg)

## Steps to Reproduce
- URL: https://staging.va.gov/manage-va-debt/request-debt-help-5655/ [do NOT sign-in beforehand]
- Test User _(if applicable)_: [see **Specs** above]
- On unauthenticated Intro-page, sign-in, then observe sign-in redirect brings up 404-page. [See screenshot below]
[see also video below]

**Screenshot**:
![fsr-bug-unauthd-redirect-404](https://user-images.githubusercontent.com/587583/110510137-205d6580-80c0-11eb-9bdc-6b42b0e94e63.png)

**Video capture**:
https://user-images.githubusercontent.com/587583/110510210-32d79f00-80c0-11eb-8775-8714b51e5c23.mp4

## Desired behavior
- [x] Intro-page sign-in redirect should successfully return to Intro-page.

## Acceptance Criteria
- [see **Desired behavior** above]

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by LinnJS** [comment]
I fixed this in the past with Caregiver would not mind taking this task can knock it out pretty quickly. Just takes a bit of coordination with the DevOps team.

**Comment by LinnJS** [comment]
@leahkeeler @craigwheeler do we have a information architecture plan yet from VSP?

**Comment by craigwheeler** [comment]
yep all approved info is here ... https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-debt-fsr.md

**Comment by tlei123** [comment]
Validated on Staging.

**Comment by tlei123** [comment]
Sorry, @LindaLi123 , for some reason, this sign-in redirect bug's occurring again.  

@LinnJS @craigwheeler , I noticed the form-URL's changed to https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/ so maybe the previous fix was for .../request-debt-help-5655/ ?

**Comment by tlei123** [comment]
Just re-checked Staging, and sign-in redirect is now working again.


https://user-images.githubusercontent.com/587583/123681336-8ea86e00-d7fe-11eb-8aff-a5a9731e1c4b.mp4
