### ISSUE TITLE
[Research] Investigate auto-focus bug on review page 

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21222]
## User story
As a Veteran
I want to understand the status of my submission
And what next steps are necessary
After submitting the 10-10CG

## Acceptance criteria
- Investigate why certain errors are not auto-focused on the review page
- Resolve the issue or create a ticket for platform

**Comment by LinnJS** [comment]
[Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1615485699012700) to initial conversation with Platform Support

**Comment by LinnJS** [comment]
A ticket was created [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/409) to create a VSP Design System team discussion.

**Comment by LinnJS** [comment]
Follow up with platform from a week from today

**Comment by ala-yna** [comment]
https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/21962 was created to follow up based on the Platform team's work
