### ISSUE TITLE
[Design] Iterate on Sign as a Representative design

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21230]
Based on the research synthesis done last sprint (#20316)
We want to iterate the designs for the Sign as a Representative flow
So that we can ensure it provides the best user experience to Veterans and Caregivers.

## Acceptance Criteria
- Prototypes are updated
- Content approved by VSP
- Prototypes are ready for implementation

**Comment by sshein** [comment]
https://dsva.slack.com/archives/CMJ2V70UV/p1615334155010900

**Comment by sshein** [comment]
Designs shown to team today
[https://app.zenhub.com/files/133843125/aae14196-b172-47bf-a6ec-027f87eee18d/download](https://app.zenhub.com/files/133843125/aae14196-b172-47bf-a6ec-027f87eee18d/download)

**Comment by sshein** [comment]
Hi @DanielleThierryUSDSVA do you have time to give content suggestions on this design by Thursday of this week?  Here is a link to the page I'd like input on - It's a link to the inspect mode so you can copy and paste content wherever you'd like.  Thanks!

https://preview.uxpin.com/e3a1c4cfb7408175af0bc54173e311d14a406ae2#/pages/137428181/specification/no-panels?mode=i

**Comment by DanielleThierryUSDSVA** [comment]
Hi @sshein. Yes, no problem! Will post edits by Thursday. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @sshein. Let me know what you think of the content below. I'm still mostly focused on my USDS research discovery sprint, but will check back later today/tonight for any questions. Thanks!

# Representative

Some family caregivers are also the Veteran’s legal representative. These representatives have the legal authority to make certain decisions for the Veteran. 

Here’s what you should know:
- You can still apply for this program even if you’re not the Veteran’s legal representative. 
- If you are the Veteran’s legal representative, you can upload a document to show your legal status now. Uploading your document may speed up your application process.

**Would you like to upload a document to show that you’re the Veteran’s legal representative?**
Yes
No

**What type of document does a legal representative need?**
To show that you’re the Veteran’s legal representative, you’ll need to upload one of these current documents:
- Power of attorney, **or**
- Legal guardianship order, **or**
- Another document that confirms your legal status as the Veteran’s representative. An appropriate attorney or court must issue this document. 

**Note:** Being a Veteran’s closest family member or next of kin doesn’t mean you’re their representative. You need a separate legal document to show your status as the representative. 


*One other thought:* We could also consider this for that 3rd bullet: 

- Another legal document that confirms your legal status as the Veteran’s representative. This document can be from by a federal, state, local, or tribal court.

**Comment by sshein** [comment]
awesome, this looks great, thank you! I'll run it by the program team.  I assume 
"What type of document does a legal representative need?" is still an "additional info / revealing" component?

**Comment by DanielleThierryUSDSVA** [comment]
Yes, additional info component! Thanks, @sshein!

**Comment by sshein** [comment]
After making Danielle's copy changes above, we ran the designs by the Caregiver Program team. Overall, they approved the direction, however they wanted the option to collect whether or not the user was a legal representative, even if they did not have documentation to upload. We don't want to directly ask if they are a representative because that scared caregivers off. We are landing with the following designs: https://preview.uxpin.com/54121d54fe375ffb5905e08f159c522bd6b5bc06#/pages/137561797/simulate/no-panels?mode=i

@DanielleThierryUSDSVA wondering if you can take another look at this point and if you have thoughts on the 3 bullet options. I did tell the Program team that we should test this in staging with users before launching to production to make sure it works for them.

**Comment by sshein** [comment]
@DanielleThierryUSDSVA we created a new ticket for finalizing copy in this upcoming sprint so if you can add your comments here that would be great https://github.com/department-of-veterans-affairs/va.gov-team/issues/21964 - thanks!
