### ISSUE TITLE
SPOOL: Track spool file creation by RPO

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#21243]
As a developer, I need to track the spool file creation by RPO so that during the retry processing only spool files for RPOs that have not been processed are processed.

## Assumptions:
1. This work is completed behind a prod flag.

## Acceptance Criteria
1. The spool file processing tracks the completion of spool creation and transfer by RPO.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
goal is to create this flow for when a failure happens
- on day 1: failure for eastern RPO happens, only western RPO is spool file is created
- day 1 retry attempt 1 out of 5: doesn’t make a new western RPO cause not a “new” run of job, successfully makes an eastern RPO file
- emails western RPO from first run and eastern RPO from first retry

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6187
https://github.com/department-of-veterans-affairs/vets-api/pull/6169

**Comment by zurbergram** [comment]
Prod flag testing of vets-api is tricky, switching to feature flag `spool_testing_error_1`
