### ISSUE TITLE
[Bug] Financial Status Report - 2 Debts - Only one type of Repayment/relief statement page displayed

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#21241]
## What happened?
On Staging, **[Request help with VA debt (VA Form 5655)](https://staging.va.gov/manage-va-debt/request-debt-help-5655/)** (FSR) form, with 2 Debts selected and different Repayment/relief options selected, only 1 type of Statement-page displayed [for whichever option had been selected for 2nd Debt].

## Specs:
- Devices: [so far, Win10 PC desktop, Galaxy S8, Galaxy Tab S6, but I'm surmising it's device-agnostic]
- Browsers: [so far, Win Chrome, Samsung Internet, but I'm surmising it's browser-agnostic]
- Test User _(if applicable)_: `vets.gov.user+1@gmail.com` (Greg)

## Steps to Reproduce
- URL: https://staging.va.gov/manage-va-debt/request-debt-help-5655/
- Test User _(if applicable)_: `vets.gov.user+1@gmail.com` (Greg)
- Advance to **Repayment/relief options** page, completing required-fields and clicking **Continue** on the way there if necessary.
- For 1st Debt, choose **Extended...** or **Compromise**, enter a **payment** amount, then **Continue**.
- For 2nd Debt, choose **Waiver**, click **By checking...** checkbox, then **Continue**.
- Observe that next **Supporting statement** page, observe that type of statement is for **Waiver** [for 2nd-Debt option-selection], and not for **Extended...**/**Compromise** [for 1st-Debt option-selection].
[see also Video below]
[It appears that Statement-page displayed was for whichever Repayment/relief option had been selected for the 2nd Debt.]

**Video**:
https://user-images.githubusercontent.com/587583/110517869-a4b3e680-80c8-11eb-9856-0ebf56cf4b43.mp4

## Desired behavior
- IF different Repayment/relief options are selected for the 2 Debts, either:
  - [ ] 2 separate Statement-pages should be displayed [1 for each type of Repayment/relief option-selection], or
  - [ ] A "combined" Statement-page should be displayed [supporting both types of Repayment/relief option-selections].

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tlei123** [comment]
Still not fixed on Staging.

**Comment by leahkeeler** [comment]
@tlei123 Can you please validate and close

**Comment by tlei123** [comment]
@craigwheeler , could you let me know how this was fixed?

I'm still seeing only the debt-**waiver** statement-page after choosing **a non-waiver option for one debt and the waiver option for the other** -- no debt-**payment** statement-page's presented.

![bug-2-debts-waiver-stmt](https://user-images.githubusercontent.com/587583/114066496-a4864280-9850-11eb-9c99-1eb283ad78b6.png)


The only way to get the debt-**payment** statement-page displayed is by **choosing a non-waiver option for both debts**.

**Comment by rebeccawalsh** [comment]
@tlei123 I just looked through staging, and things appear to be working as intended.

**If you select compromise or monthly payments, you get:** 
![image](https://user-images.githubusercontent.com/6361930/114075222-520a4d80-9873-11eb-99ef-1e8208cd04f2.png)

**If you select waiver for _any of the debts_, you get:**
![image](https://user-images.githubusercontent.com/6361930/114075290-664e4a80-9873-11eb-86db-2eb368f0eacb.png)

We do this because a personal statement is required for any FSR where a waiver is requested on any debt. For any FSR submitted that doesn't ask for a waiver, no personal statement is required (so we cannot make it so)

**Comment by rebeccawalsh** [comment]
@tlei123 Oh! Is your point centered on the language for combined requests rather than the *Required functionality? If so, we could keep the *Required logic, but keep the question itself generic as "Please tell us more about why you need help with this debt" -- I don't see a big problem with that.

**Comment by tlei123** [comment]
Thx, @rebeccawalsh !  The reason I logged a behavior bug is there's prob'ly some app-logic behind that sentence being different depending on resolution options chosen.

@craigwheeler ,  ^ looks like we've got a feasible solution from Rebecca now.  Let me know what you think, or if you agree then just work w/ her to finalize statement-page language for the body-test sentence.

**Comment by craigwheeler** [comment]
@tlei123 If waiver is selected for ANY debt it becomes a required field and the phrase "Please tell us more about why you need a debt waiver." is displayed to the user otherwise the default behavior is the field is not required and the message "Please tell us more about why you need help with this debt payment." is used. @rebeccawalsh if we need to make changes go ahead and update the ticket and move it to ready and ill make the necessary changes 👍

**Comment by tlei123** [comment]
@rebeccawalsh @craigwheeler , if you're satisfied this doesn't need fixing, feel free to Close.  Maybe it's just me who got confused by the possible absence of a non-waiver statement-page, and this is arguably an edge case.  :)

**Comment by craigwheeler** [comment]
seems like everything is functioning correctly as is so if @rebeccawalsh you're okay with how it is now go ahead and close this issue or lemme know if we need updates tks

**Comment by rileyorr** [comment]
@craigwheeler hopping in here while Becca's on PTO - it looks like we should update the content based on previous comments between @rebeccawalsh and @tlei123 

If only non-waiver debt resolutions are selected:

> Please tell us more about why you need help with this debt

If a waiver is selected with or without other resolutions selected:

> Please tell us more about why you need help with this debt *Required

Let me know if that makes sense - ty!!

**Comment by craigwheeler** [comment]
okay gotcha so were just updating the content to be consistently the same for both and only if waiver is selected it becomes required... ill open a pr and get it updated thanks for clarifying!

**Comment by tlei123** [comment]
Fix validated on Staging.
