### ISSUE TITLE
SPOOL: Update processing retry functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#21246]
As an EDU team member, I need each spool file to only be generated once per day so that the RPO team can appropriately process each claim.

## Assumptions:
1. This work is completed behind a prod flag.

## Acceptance Criteria
1. If the spool file process fails, on retry, the only RPOs that are processed are the ones that were not successful on the previous attempt.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
goal is to create this flow for when a failure happens
- on day 1: failure for eastern RPO happens, only western RPO is spool file is created
- day 1 retry attempt 1 out of 5: doesn’t make a new western RPO cause not a “new” run of job, successfully makes an eastern RPO file
- emails western RPO from first run and eastern RPO from first retry

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6187
https://github.com/department-of-veterans-affairs/vets-api/pull/6169

**Comment by zurbergram** [comment]
Testing

1. Submit a form for a RPO
2. Check `spool_file_events` table notice no rows
3. Run CreateDailySpoolFiles job
4. In `spool_file_events` table notice there is now a row for each RPO the form submissions would go to, this row should have a `successful_at` timestamp and a `retry_attempt` of 0
5. In `vets-api/tmp` there should be a file with format `<rpo>_<date>_vetsgov.spl` with first submission
6. Remove `successful_at` timestamp from the row
7. Submit a form for the same RPO again
8. Run CreateDailySpoolFiles job
9. The file with format `<rpo>_<date>_vetsgov.spl` should now contain both submissions
10. In `spool_file_events` table the row for the RPO should have a `successful_at` timestamp and a `retry_attempt` of 1

**Comment by zurbergram** [comment]
Prod flag testing of vets-api is tricky, switching to feature flag `spool_testing_error_1`
