### ISSUE TITLE
SPOOL: Create notification for when spool file processing fails

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#21244]
As an EDU team member, I need to be notified when a spool file has not been generated for an RPO so the RPO can be notified and the technical team can take the necessary steps to generate a new spool file.

## Assumptions:
1. This work is completed behind `spool_testing_error_3`.

## Acceptance Criteria
1. An email notification is sent to the following recipients when a spool file has not been generated for the RPO for the staging environment:
    a. sonntag_adam@bah.com
    b. shawkey_daniel@bah.com
    c. neel_darrell@bah.com
    d. turner_desiree@bah.com
    e. mccurdy_devin@bah.com
    f. roth_matthew@bah.com
    g. delli-gatti_michael@bah.com

2. An email notification is sent to the following recipients when a spool file has not been generated for the RPO for the prod environment:
    a. Joseph.Preisser@va.gov
    b. Shay.Norton-Leonard@va.gov
    c. PIERRE.BROWN@va.gov
    d. VAVBAHIN/TIMS@vba.va.gov
    e. EDUAPPMGMT.VBACO@VA.GOV

3. The subject of the email is: "Error Generating Spool file on MM/DD/YYYY"
4. The body of the email is:
    a. If during spool file creation
    > There was an error generating the spool file for RPO ### on MM/DD/YYYY.

    b. For other errors that occur
    > There was an error generating spool files on MM/DD/YYYY

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/8758

**Comment by zurbergram** [comment]
Slack integration issue, https://github.com/department-of-veterans-affairs/va.gov-team/issues/15175#

**Comment by zurbergram** [comment]
Currently it looks like the FROM email address used in Sentry config is not considered to be a valid sender from the host IP it is coming from resulting in the strict VA and BAH email filtering it out, [external is aware and is looking into the issue to update configuration](https://dsva.slack.com/archives/CBU0KDSB1/p1616615425112700?thread_ts=1616511600.424200&cid=CBU0KDSB1) 

Relevant slack discussions, there's some PagerDuty discussion in threads as well
https://dsva.slack.com/archives/CBU0KDSB1/p1616419668288700
https://dsva.slack.com/archives/CBU0KDSB1/p1616511600424200

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6336

**Comment by zurbergram** [comment]
Merging note because of the order of work done, PR for https://github.com/department-of-veterans-affairs/va.gov-team/issues/22084 will have to be merged before this story's PR

**Comment by desireeturner** [comment]
We're going to flip the feature flag for this on Monday 04/05.

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/1734)
