### ISSUE TITLE
Update bucket references in content-build to point to new app s3 bucket

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21259]
## Details 

Following completion of #11914 and #7978, bucket references in the content-build repo need to be updated to point to the new app s3 bucket. 

## Definition of Done 

- [x] dev.va.gov is publishing content via content-build and apps via vets-website

**Comment by timwright12** [comment]
Draft PR for this when we're ready to start https://github.com/department-of-veterans-affairs/content-build/pull/59

**Comment by timwright12** [comment]
Looking through the code here, it seems like the bucket references are used for: 
- Assets (images, fonts, some JS)
- CSS/ JS references

With that in mind we'll either need to deploy assets to the app bucket or update all the references to either point to apps or content buckets.

Will investigate the best path here

**Comment by timwright12** [comment]
This ticket is prepped and waiting on #7978

**Comment by theodur** [comment]
The PR for this has been merged https://github.com/department-of-veterans-affairs/content-build/pull/59. Will verify dev.va.gov is using assets from https://s3-us-gov-west-1.amazonaws.com/apps.dev.va.gov.

**Comment by theodur** [comment]
After confirming, dev.va.gov is now pointing to the app bucket for its assets. https://dev.va.gov/generated/file-manifest.json
