### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#21250]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

https://dsva.slack.com/archives/CKCRMLGAC/p1614806653046900?thread_ts=1614705522.036600&cid=CKCRMLGAC

dror.matalon@va.gov

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [ ] Domo
-[x] bigquery
Need to access big query from domo.

## Date Required
03/09/21

## Product Team / External Team / VA Office
OCTODE

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @drorva , 

Thank you for opening this request. 

You should have received an email to your dror.matalon@va.gov email address with an access link to BigQuery. We have given your account the following roles in GCP IAM: 
![image](https://user-images.githubusercontent.com/48527022/110795296-adc9c280-8244-11eb-95d8-941abf93fc94.png)

This access will allow you full read access to our BigQuery datasets. For reference on the BigQuery export schema, please see these couple resources: 
- **[Collapsible Tree](https://storage.googleapis.com/e-nor/visualizations/bigquery/ga360-schema.html#section-collapsible-tree)**
- **[Google Documentation](https://support.google.com/analytics/answer/3437719?hl=en)**

Lastly, I have setup your API credentials key that is needed for initial setup of BigQuery datasets. I [sent you a message this AM over Keybase](keybase://chat/jonwehausen,dror/2) and Slack [here](https://dsva.slack.com/archives/CKCRMLGAC/p1615470108012300?thread_ts=1614705522.036600&cid=CKCRMLGAC) -- Let me know how you would like to share the API key securely.

**Comment by jonwehausen** [comment]
Hi @drorva , 

I have shared your JSON key over keybase in a direct message. 

You should now be able to take the `.json` contents and input them as your authentication method when setting up the BQ dataset. 

![image](https://user-images.githubusercontent.com/48527022/110988348-6cb5d900-833e-11eb-950d-99cb6618845b.png)


I will close this ticket but please feel free to reach out / reopen should you have any issues at all -- thank you very much for your time.
