### ISSUE TITLE
[FE] My VA: Revert prescriptions work for My VA 2.0

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21254]
## Background

Given the amount of [confusion in usability testing around the prescriptions section we mocked up for the My VA 2.0](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-research-findings.md), we are largely removing that content from the My VA 2.0 design and paring the prescriptions section down to a CTA to view and manage all prescriptions.

Unfortunately, Sandra had already done a good amount of work on this, so now we need to revert that code.

## Tasks

- [ ] Revert prescriptions work for My VA 2.0

**Comment by sanlouise** [comment]
Merged and closing
