### ISSUE TITLE
Merge Creds into DevOps

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21266]
We need to get a PR merged into a devops repo so that credentials are available for our CH31 feature release

## Acceptance Criteria
- [x] Make a PR into [Devops FWD Proxy](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/fwdproxy)

**Comment by digitaldrk** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/8695
