### ISSUE TITLE
If user gets an "app isn't working right now" error on the Cancel appointment screen, they are stuck

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#21269]
## What happened?
Was testing the Cancel appointment screen and tried to cancel an appointment that I had already canceled on another phone (but this phone still showed it as upcoming), and I got the "The VA mobile app isn't working right now" error.  The problem is, there is no way to navigate off this page when the happens.  I can't go back, I can't go forward.  I have to quit the app and start it up again.

## Specs:
- Device: This particular instance was with an iPhone XR

## Steps to Reproduce
- I was logged into a user with two phones.
- Navigate to the Upcoming appointments page with both phones.
- Cancel an appointment with one phone.
- Cancel the same appointment with the other phone. (At least this is how this occurred for me.)

## Desired behavior
User won't be stuck on a page when an error happens -- they'll be able to navigate back out.

## Acceptance Criteria
User won't get stuck on a page with no way to navigate back out.

## Bug Severity
- 3 - Medium

## Linked to Story
I was testing canceling appointments.
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/20463

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/972b750f-87ae-4018-9c9c-694ad3d8b882)

**Comment by bessgreen** [comment]
Ticket to add Back buttons to confirmation screens: #21339

**Comment by digitalken** [comment]
FAIL - Android is OK but iOS is not aligned correctly, too low.  Should be even with the header title. @DF-ClaytonMatulich , I'm sending it back to "in progress".

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/3c7e9149-3fe2-497a-9600-22361086f433)

**Comment by DF-ClaytonMatulich** [comment]
Note: It looks like this visual bug appears when IS_TEST is true (integration test environment). There is a current issue where sometimes builds are created with that environment variable set , and visual bugs like this , among other a11y differences, surface to users.

**Comment by digitalken** [comment]
PASS 3/17/2021 - Looks good in the new build.  Closing.
