### ISSUE TITLE
No sent messages (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21279]
## User story
As a user, if I don't have any messages in my Sent Folder I want to see a message saying that in the app.

## Acceptance Criteria
1. Create UX/UI when a user does not have any messages in their 'Sent' folder
     - Copy is hard-coded: "You don't have any messages in your Sent folder"
2. Below the copy, display large button: "Go to Inbox"
     - Selecting this button routes to the Inbox page
3. The following elements should persist on this page:
     - Back button (should route to the previous page, i.e. the Folders tab on the Messages page)
     - Compose a Message footer button

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447948349_Sent_-_No_Messages

## Accessibility Acceptance Criteria

- Mark "You don't have any messages in your Sent folder" as Header 2

**Go to inbox button**
- Title= "Go to inbox"
- accessibilityHint= "view messages in your inbox" 
- accessibilityRole= “button”

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
4/12/2021 - I've not found a user where I'm able to test this yet.  Setting to QA Blocked for now.

**Comment by digitalken** [comment]
PASS 4/12/2021 - Looks good in both Android and iOS.  Accessibility OK, too.  Closing.
