### ISSUE TITLE
Update contact info page to match new mocks

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#2127]
Update contact info page to match:

![Screen Shot 2019-10-01 at 9.59.35 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/9672c80a-93d7-4d7a-8fda-3f350f7848a9)

@goldenmeanie to confirm the UX for the contact info page (and whether it should be the same across the two flows).

**Comment by markgreenburg** [comment]
@goldenmeanie @rtwell I think Jeff's contact info page mock is out of date - could y'all please provide the latest?

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/67720064-72a95500-f9a9-11e9-9e82-3a243cecac8f.png)

![image](https://user-images.githubusercontent.com/12564977/67720070-763cdc00-f9a9-11e9-935b-e8c1f9bb66da.png)

**Comment by markgreenburg** [comment]
@peggygannon note that phone & email are always required by the VA. The radio choice is there to reinforce that this will be the _preferred_ comms method the VA uses, but will not be the only comms channel if they can't get a hold of the veteran through it. I.e., the VA has an obligation to get in touch with the veteran through any means possible.

**Comment by peggygannon** [comment]
@markgreenburg @rtwell @goldenmeanie 

Please see below for my content recommendation for this screen

{page header} **Contact information**

How would you like us to contact you? 
{radio buttons}
Email
Phone
Mail

This is the contact information we have on file for you. We’ll use this information to contact you about scheduling your appointment. You can update your contact information here, but the updates will only apply to this tool. 
If you want to update your contact information for all your VA accounts, please [go to your profile page](va.gov/profile).

{label} Email address

{label} Phone number

Best times for us to call you
{checkboxes}
Morning (8:00 a.m. – noon ET)
Afternoon (noon – 4:00 p.m. ET)
Evening (4:00 – 8:00 p.m. ET)

**Comment by jbalboni** [comment]
Updated mock: ![image.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/423f075b-e5ae-4565-bc1a-57e9a64c9414)
