### ISSUE TITLE
[Cheetah MVP] Plan ahead content & CTA updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21274]
## Issue Description
Update the Plan Ahead page based on user testing.

---

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] CONTENT - Copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/VAOS_for_Distribution_Copy-plan_ahead.docx)

- [ ] DESIGN - Designs match the specs (copy is FPO): https://www.sketch.com/s/aca1478c-8cfa-433e-8e06-d42b53aaa60d/a/R1a1Ool#Inspector

- [ ] Given user selects covid scheduling on the homepage, When there's at least 1 facility with online scheduling available, Then show "COVID-19 Vaccine first dose" (formerly "Plan ahead") page

- [ ] Start scheduling button does **not** display here

- [ ] If user clicks "COVID-19 vaccines at VA page" link, Then open `/health-care/covid-19-vaccine/` in a new tab

- [ ] ANALYTICS - Track "COVID-19 vaccines at VA page" link clicks

- [ ] If user clicks Back button, Then VAOS homepage displays

- [ ] If user clicks Continue button, Then Screener page displays

![21274 changes.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/91c71b25-f847-4a84-89cb-293d570bda14)

## Definition of Done

- [ ] All acceptance criteria is met

- [ ] Flow [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md) and screenshots are updated

**Comment by laurenernest** [comment]
@jenniemc I just updated the links to the spec and copy doc. Hopefully you haven't started yet 🤞

**Comment by jenniemc** [comment]
@laurenernest, I'm using `vaos-cheetah-go-to-main-COVID-19-vaccines-at-VA-clicked` as the event name for analytics.  If you prefer something else let me know.

**Comment by laurenernest** [comment]
We should follow a similar pattern to our other events, and also not include Cheetah in anything.

`vaos-(destination page descriptor)-link-clicked`

@jbalboni Trying to think of any other examples besides the one to Facility Locator

**Comment by jenniemc** [comment]
Gotcha. Updating event name to: `vaos-COVID-19-vaccines-at-VA-link-clicked`
