### ISSUE TITLE
Update a11y announcements for nav bar tabs

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21270]
## Acceptance Criteria
Update the a11y announcements for the 4 nav bar buttons.

1. Home
     - Title= "Home"
     - accessibilityRole= “tab"
     - accessibilityValue= "1 of 4"
     - accessibilityState= denote when "Selected"
2. Claims
     - Title= Claims
     - accessibilityRole= “tab"
     - accessibilityValue="2 of 4"
     - accessibilityState= denote when "Selected"
3. Appointments _(note: this tab is ultimately changing to 'Health' - depending on when this ticket is worked on, these updates may already be made via #21038)_
     - Title= Appointments
     - accessibilityRole= “tab"
     - accessibilityValue= "3 of 4"
     - accessibilityState= denote when "Selected"
4. Profile
     - Title= Profile
     - accessibilityRole= “tab"
     - accessibilityValue= "4 of 4"
     - accessibilityState= denote when "Selected"

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS - 3/19/2021 - Sounds good on both iOS and Android.  Closing.
