### ISSUE TITLE
No messages in inbox (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21278]
## User story
As a user, if I don't have any messages in my Inbox, I want to see a message saying that in the app.

## Acceptance Criteria
1. Create UX/UI when a user does not have any messages in their Inbox
     - This UI should appear when "Inbox" is the selected segment
2. All copy is hard-coded

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447948347_Inbox_-_No_Messages

## Accessibility Acceptance Criteria

- Mark "You don't have any messages in your Inbox" as Header 2

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
4/12/2021 - Don't have a user where I can test this yet. Setting to QA blocked for now.

**Comment by digitalken** [comment]
PASS 4/12/2021 - Looks good in iOS and Android.  Accessibility bug is logged - When there are no messages, "You don't have any messages in your Inbox" should be marked as header 2.  

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23089

Closing as bug is being tracked.
