### ISSUE TITLE
Compose a Message | page layout

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21276]
## User story
As a Veteran, I want to compose a new message so that I can communicate a new question or need to my healthcare team.

## Acceptance Criteria
1. Selecting the **Compose a Message** button routes to a new page, called "Compose"
2. Display the Veteran Crisis Line banner
3. Page layout is split into 2 sections:
     - Section 1: expand/collapse accordion on grey background
     - Section 2: form on white background
4. Create UX/UI for Section 1: 
     - Pull in expand/collapse CC (#15441)
     - Default: accordion is collapsed
     - All copy is hard-coded
5. On default, accordion is collapsed
6. Create placeholder for Section 2. (Form UI is covered in #20426)

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364867

## Accessibility Implementation Guidelines

**Mark "Compose" as Header 1**

**When will I get a reply? component**
- accessibilityLabel="when will I get a reply?"
- accessibilityHint="view more about when to expect a response"
- accessibilityRole="spinbutton"
- accessibilityState= "collapsed"
- Denote when dropdown is expanded
- Ensure dropdown area does not "trap" the keyboard focus

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
PASS 4/12/2021 - Looks good on Android and iOS, both UI and accessibility.
