### ISSUE TITLE
Create service blueprint / product flow diagram illustrating how Triage works

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#213]
# User Story

As VSP Triage Team I need to have a documented MVP process to try out so that I can have a standard approach to handling issues, and learn what works and doesn't work well for iteration purposes.

As a VFS Team / VA Business Owner, I need to know what to expect of the Triage process so that I can effectively leverage it, and handle issues if / when they get assigned to me.

# Goal

- Post process in public channel for alignment between all parties.
- Capture process in service blueprint, so as we try it out we can continue to record pain points and success points over time for iteration purposes

# AC
- Process documented in GH Triage docs
- Process documented via Service Blueprint visual
- Shared w/DSVA

**Comment by rroueche** [comment]
@annaswims @gunsch @leahbannon @hpjaj would love your feedback: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/Platform/Triage%20%26%20Tier%202%2B3%20Support

**Comment by gunsch** [comment]
Looks good so far! Made a number of minor edits to the Process doc but over

Note: now at https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/Platform/Teams/Triage/

**Comment by annaswims** [comment]
For a future iteration, here's the criteria we currently use to categorize incidents. 
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/OnCall/Incident%20Categorization.md
