### ISSUE TITLE
Display issues with button in sitewide nav on screens < 768px

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#21317]
## What happened?
1. On an iPhone 12 device in Safari, and iPhone 5 in Chrome emulator, the sign-in button is slightly higher than the Search and Contact us buttons/links in the site wide navigation. Check out how it hits the green line in the screen shot.  
![image](https://user-images.githubusercontent.com/55992116/110659326-78fc3380-8190-11eb-80e5-939cc9058555.png)

2. On an iPhone 12 in Safari, when a user is logged in, their name is slightly lower than the other two buttons/links. I didn't see this in Chrome emulator for any device, so you may have to check around a bit to hunt down exactly all the browser/devices where this happens.
![IMG_4646](https://user-images.githubusercontent.com/55992116/110659475-9cbf7980-8190-11eb-9a60-e96b9eebdcb7.jpg)

3. On iPhone 5 in Chrome emulator, the users name is getting slightly cut off. I saw this on the name Tamara. Longer names get a `. . .` so I think there's some logic for longer names that maybe just needs to be tweaked.
![Screen Shot 2021-03-10 at 11 01 46 AM](https://user-images.githubusercontent.com/55992116/110659567-b3fe6700-8190-11eb-9216-c5199e2a3519.png)

## Specs:
- Device: Chrome emulator, safari on iPhone 12
- Browser: Chrome and Safari
- Test User _(if applicable)_: Tamara E Ellis, line 34 in our [staging users doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

## Steps to Reproduce
- URL: va.gov, or staging.va.gov for authenticated screens
- Test User _(if applicable)_: Tamara E Ellis, line 34 in our [staging users doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)
1. Visit the site on a mobile device or in a browser window < 768px wide
2. Check out the alignment of the buttons
3. Log in with Tamara, and check the alignment (you may need to switch devices)

## Desired behavior
1. `Search`, `Contact Us`, `Sign In`/ Users name should all be aligned
2. We should not see characters partially obscured when a user is logged in

## Acceptance Criteria
- [x] Partial letters aren't getting cut off
- [x] `Search`, `Contact Us`, `Sign In`/ Users name are aligned when browser is less than 768px wide, across devices and browsers (I'm not sure what the full list is, but please check across browsers/devices, not only the 2 listed here)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by kelsonic** [comment]
PR up: https://github.com/department-of-veterans-affairs/vets-website/pull/16512

### Unauth
![image](https://user-images.githubusercontent.com/12773166/112508961-a67eda80-8d55-11eb-8902-9be25b5c818a.png)

### Auth
![image](https://user-images.githubusercontent.com/12773166/112508900-9666fb00-8d55-11eb-8773-fd753647d9fc.png)

**Comment by brianalloyd** [comment]
Reviewed and fixes look good, appreciate the work on cleaning up this element @kelsonic.  Closing ticket.
