### ISSUE TITLE
Pagination | Appointments

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21328]
## User story
As a user, I want pagination on my Appointments list pages so that if I have many upcoming/past appointments on file, the page content loads faster.

## Acceptance Criteria
1. Pull in the pagination common component to the Upcoming & Past appointment pages
2. Copy between the buttons: "Appointments #A to #B" ~of #C"~

## Designs
Example on the SM page: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364845_Inbox

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines

**Left arrow button**
- accessibilityHint= "Previous page"
- accessibilityRole= link
- accessibilityState= denote when the button is inactive: "dimmed" (iOS) or "disabled" (Android)

**Right arrow button**
- accessibilityHint= "Next page"
- accessibilityRole= link
- accessibilityState= denote when the button is inactive: "dimmed" (iOS) or "disabled" (Android)

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by lexicalninja** [comment]
@bessgreen for this AC `There should not be a scenario where both L/R buttons are disabled` isnt this true if there are between 1 and 10 total items total?

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/30/2021 - Looks good on iOS and Android.  Closing.
