### ISSUE TITLE
Pagination | Claims & Appeals

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21329]
## User story
As a user, I want pagination on my Claims & Appeals list pages so that if I have many active/closed claims on file, the page content loads faster.

## Acceptance Criteria
- [ ] Add pagination component with basic API wire up. No saving of previously loaded data.
1. Pull in the pagination common component to the Active & Closed claims and appeals pages 
2. Copy between the buttons: "Claims and appeals #A to #B of #C"
- [ ] Track previously loaded data

## Designs
Example on the SM page: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364845_Inbox

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines

**Left arrow button**
- accessibilityHint= "Previous page"
- accessibilityRole= link
- accessibilityState= denote when the button is inactive: "dimmed" (iOS) or "disabled" (Android)

**Right arrow button**
- accessibilityHint= "Next page"
- accessibilityRole= link
- accessibilityState= denote when the button is inactive: "dimmed" (iOS) or "disabled" (Android)

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Blocked: follow up w/ AH about endpoints for active & closed C/A

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/24/2021 - Looks good on iOS and Android with a minor bug logged against iOS with bluetooth keyboard.  Mostly likely this issue also exist on Messages with the bluetooth on iOS, too.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/25175

Closing.
