### ISSUE TITLE
Common component: pagination

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21331]
## Acceptance Criteria
1. Create common component for the pagination buttons, with the specs indicated below:
2. General rules
     - Background-color: gray-lightest #F1F1F1
     - Text: Mobile Body 
     - Text-align: center
     - Margin: 0
     - Padding: 
          - top/bottom: 40px
          - left/right: 20px
3. Buttons:
     - Border-radius: 5px
     - Background-color: variable
          - Active: primary #0071bb
          - disabled: gray-light #aeb0b5
     - Icon: variable
          - fa-chevron-left
          - fa-chevron-right
     - Icon fill: white #fff
     - Margin: 10px (between text and buttons)
     - Padding:
          - top/bottom: 15px;
          - left/right: 18px
     - Width/height: Should end up being 46px x 46px after applying the above
4. If copy wraps to a new line:
     - Copy should be center-aligned
     - Copy should also be middle-aligned with the L/R buttons
5. The pagination component should only display on a page when there are >10 total records associated with a page
6. Display a max of 10 records on a page
     - The app will gradually load in more data as the user navigates through the pagination buttons 
7. Copy between the buttons: "[Variable label] #A to #B" ~of #C"~
     - #A = the sequence of the record displayed at the top of the page (e.g. 1, 11, 21, etc.) 
     - #B = the sequence of the record displayed at the bottom of the page (e.g. 10, 20, 24)
     - ~#C = total number of records ~
8.  Rules for active/disabled buttons:
     - The active arrow buttons display when a user can navigate to a page in the indicated direction
     - The disabled arrow buttons display on the first & last pages: on the first page, the L arrow will be disabled; on the last page, the R arrow will be disabled
     - There should not be a scenario where both L/R buttons are disabled _(see AC #5)_
9. Add specs to ReadMe

Note: 
1. Temporarily omitting the "total #" part of the requirement until it is supported in the backend (AC #7). This requirement is covered in a separate ticket: #23472
2. Pagination will appear on the following pages:
     - Appointments list pages (upcoming/past)
     - Claims & Appeals list pages (active/closed)
     - Messages list pages (Inbox, Sent list, folders lists)

## Designs
.svgs: https://drive.google.com/drive/folders/1_eYd_BgVnehUyxlNO6zwSjdh3mxW1oi3
designs: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364845_Inbox
![Screen Shot 2021-03-31 at 1.50.25 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/37d6a0e1-c2f1-4569-b4f4-df029e77de44)

**Comment by drjecker** [comment]
@bessgreen Design specs for UI are in [Style guide](https://docs.google.com/document/d/1VC-CLWnhevB8HLBBHPwkSJvECn8EBie8HOkJylKE1lo/edit#bookmark=id.z3b5z45m8ogb).

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/30/2021 - Looks good on iOS and Android with a minor bug logged for padding.  Closing.


https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/24072
