### ISSUE TITLE
Add "Back"/"Cancel" button to confirmation screens

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21339]
## User story
As a user, if the app displays a generic error, I want a way to navigate away from the page without having to kill the app. 

Note for dev: this ticket should resolve issue #21269. This is an issue on Cancelation screens, which currently do not display a "Back" button in the header.

## Acceptance Criteria
1. Add a "Back" button on the following page:
     - Appointments: Cancelation confirmation page (test user: judy.morrison)
2. Add a "Cancel" button on the following page:
     - Claims File Upload: Upload confirmation page (test user: +366)
2. In both instances, selecting "Back"/"Cancel" should navigate to the previous page

## Screens for reference
![Screenshot_20210310-095330_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f2198c81-af27-4f72-bf26-4a05cca3c649)
![Image from iOS (24).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ad7c5b70-4007-402b-9f1a-3527f77a7019)
![Image from iOS (27).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/a3e98d5d-1cbc-4a30-ab45-c07320a03f9d)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/18/2021 - Looks good on Android and iOS.  Closing.
