### ISSUE TITLE
Test site for AWS credit process

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#21333]
Need to write a policy / SOP on how to get AWS credits

Need to work with a site to determine best process to procure AWS credits 

- [x] Determine test VA Health Center (Memphis - Coatesville is very eager to be a part as well)
- [x] SOP for aws credits

**Comment by Kennon-git** [comment]
beverly has sent sop to charles for review
once approved move forward with pilot sites.

**Comment by Kennon-git** [comment]
beverly finalizing and running it through to determine if we need two vha test sites

**Comment by Kennon-git** [comment]
paras reaching out to sites

**Comment by Kennon-git** [comment]
paras has a few more sites we can contact - last week the cto's office approved the budget, will see if some budget can go to pharmacy. 

beverly tried the sop with another center and it worked.

**Comment by Kennon-git** [comment]
paras to reach out to 4 more sites this week.

**Comment by Kennon-git** [comment]
currently waiting for opt ins

**Comment by Kennon-git** [comment]
paras to reach out to Lebanon and other sites for updates

**Comment by kjduensing** [comment]
Following up!

**Comment by Kennon-git** [comment]
working through process with VISN 6. still in progress.

**Comment by Kennon-git** [comment]
2237 is in process. waiting on a tech perspective to launch. 2 way message testing.

**Comment by Kennon-git** [comment]
have sites identified. still waiting on the tech perspective. VAnotify still testing
