### ISSUE TITLE
Direct Deposit helper text font size is too small - Should be 17px for label and 15px for helper text.

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#21332]
## What happened?
The helper text appears too small for the direct deposit page.  
The label text should be 17px and the helper text should be 15px.
The label text looks more like about 9 or 10px at most.

## Specs:
- Device: Both iOS and Android

## Steps to Reproduce
View text on direct deposit page and compare to designs.

## Desired behavior
Matches designs.

## Acceptance Criteria
Matches designs.

## Bug Severity 
- 3 - Medium

## Linked to story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/20222

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/637ff633-c1d8-46ff-8452-d7c835a5bb69)

**Comment by digitalken** [comment]
@bessgreen, I think the font difference as shown in my screen shot of the device above is too much.  The helper text, in my opinion, is just too small compared to the label text.  Maybe something a little larger for the helper text, if we're going to keep the same size label.  Here's some comparison sizes.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/8644e32f-300d-4bab-a547-1cf5fd7c821d)

**Comment by bessgreen** [comment]
@digitalken requirements from AH: helper text should be 16px with a line height of 22px. 

Tickets #19585 and #19584 address these updates.

**Comment by digitalken** [comment]
PASS 3/12/2021 - Looks good on iOS and Android.  Closing.
