### ISSUE TITLE
Complete Topline Summary for LGY Discovery

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21340]
## Background
Now that discovery research is complete, we need to complete the topline summary so we can analyze any recommended changes that arose.

## Tasks
- [x] Complete the topline summary of LGY discovery in GH

## Acceptance Criteria
- [x] Notes are saved in GH

**Comment by sporeboy** [comment]
Notes transcribed... Topline includes findings, recommendations and next steps.

The topline summary here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/research-design/discovery-interviews/coe-discovery-topline-summary.md
