### ISSUE TITLE
SM frontend wireframe implementation

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#21359]
Build out the initial screens for secure messaging to validate that the overall navigation flow, API alignment, etc. 

We are using the mobile design system and aiming for good fidelity with the designs here:
https://adhoc.invisionapp.com/share/C910DKQGZPMW#/screens/446399749
but these will be considered wirefame-level implementation and do not subsume the other frontend SM tickets.

Work is happening in this branch:
https://github.com/department-of-veterans-affairs/va-mobile-app/tree/secure-messaging-feature

Add items to this list as we progress, check off as we merge to branch. Add your name if you are taking on a task. 
Punchlist:

| Task | DF Issue | Owner | Started | Outstanding |
| ---- | -------- | ----- | --------- | --- |
| Main screen with Inbox/folders navigation| [21082](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21082) | Patrick | :heavy_check_mark: |                                                              |
| List messages in inbox | [21081](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21081) | Patrick | :heavy_check_mark: ||
| List folders | [21194](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21194) | Patrick | :heavy_check_mark: ||
| List messages in folder| [21380](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21380) | Patrick | :heavy_check_mark: |-Dynamic header name|
| Fix doubly-nested nav header | [21038](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21038) | Narin| :heavy_check_mark: ||
| Unread count for inbox | [21084](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21084) | Patrick | :heavy_check_mark: |-Need to display count on eventual "Health" Screen|
| Indicator for read/unread status of each message in inbox| [21084](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21084) | Patrick | :heavy_check_mark: |-Needs proper icon (using * asterisk instead of blue circle indicator)|
| Replace hard-coded API request actions with actual API invocation || Narin |:heavy_check_mark: |                                                              |
| View message/message thread| [21197](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21197) |Narin | :heavy_check_mark: |-User/provider avatars<br />-Attachment icon<br />-View attachment|
| Reply message footer | [21197](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21197) | | ||
| Compose message screen and footer| [21276](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21276) | | ||
| Possible - prefetch recipients?| [21276](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21276) | | ||
| Redo tab nav to have health tab with appointments/messaging screen | [21038](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21038) | | ||
** **All items need unit tests/styling/accessibility**

**Comment by narin** [comment]
Updated with links to corresponding DF issues

**Comment by patrickvinograd** [comment]
Some misc tweaks:
- [ ] Inbox should not show in list of system folders
- [ ] Listing messages in Sent folder should display the recipient, not the sender

**Comment by narin** [comment]
Feature branch has been merged into `develop` and handed off mobile dev work to DF team. Closing out.
