### ISSUE TITLE
Update TTY icon + hint text

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21363]
## Acceptance Criteria
1. Update the click-to-call common component to include a variation for TTY. This variation will display when the click-to-call number is:
     - 711 (all pages _except_ VCL)
     - 800-799-4889 (only VCL pages)
2. Update the click-to-call icon 
3. Include helper text below the button (16/22px) 
     - See designs for copy
4. Implement these changes on the following pages of the app:
     - Contact VA
     - Veteran Crisis Line (in-app and pre-login)
     - Direct Deposit overview
     - Generic error state | call help center
     - Generic error state w/ refresh
5. Update ReadMe w/ new specs

## Designs
.svg: ![Group.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/16670cc7-e1b0-409b-89bb-ddf0e7b948a8)
![Screen Shot 2021-03-10 at 11.34.18 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/66e9474b-40e2-4392-a15e-5099b76432d7)
https://adhoc.invisionapp.com/share/AX108RJZPB6E#/screens/445194522

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/19/2021 - Looks good on Android and iOS except for the direct deposit over page where the text doesn't seem to be respecting the right margin. Bug entered, closing story.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21808
