### ISSUE TITLE
Add TTY to Appointment detail screens

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21374]
## Acceptance Criteria
TBD

## Open questions
1. Add the TTY click-to-call common component (#21363) to the Appointment detail pages
     - TTY number displayed: 711
     - This applies to Upcoming/Past, Confirmed/Canceled appointments
2. The TTY UI should display on the detail card, below the facility phone number
     - If there is not a facility phone number displayed, do not display the TTY UI
3. The TTY UI should also display on the cancel card for upcoming/confirmed VAVC & CC appointments
     - Display the TTY UI below the facility phone number
     - If there is not a facility phone number, do not display the TTY UI

## Designs
https://adhoc.invisionapp.com/share/AX108RJZPB6E#/screens/445194522

**TTY UX/UI:**
![Screen Shot 2021-03-10 at 4.26.28 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4c25591a-7ec8-48b3-a790-c97010222d2c)

### Reference
![Screen Shot 2021-03-10 at 4.25.30 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e47d253b-8c53-4379-9490-bed31f70be0a)
![Screen Shot 2021-03-10 at 4.27.32 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/0882eba2-eab2-480e-9b8e-7d28dea143e9)

**Comment by digitalken** [comment]
PASS 3/19/2021 - Looks good on Android and iOS.  Closing.
