### ISSUE TITLE
Discovery for VAMC data layer 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21371]
## Issue Description
We need to implement the data layer for VAMC systems and facilities. Because these pages are rolling out rapidly, we need a general implementation method (rather than applying it to a specific system/location)

## Tasks
- Confirm any current behavior
- Determine what still needs to be done to implement the data layer (Reference #18822 as needed.)
- Find out if data layer specifies the page where the interaction occurs

## Acceptance Criteria
- Individual tasks are in issues that can be groomed/estimated (see column in table below)

Description/Screenshot of Interaction | Data Layer Specification | Dev Notes | Issue |
| -- | -- | -- | -- |
[Sidenav (left nav) ](https://design.va.gov/storybook/iframe.html?id=components-sidenav--page&viewMode=docs)|  `'event': 'nav-sidenav' //consistently populate for side navs`<br>`'sidenav-click-action': //'expand', 'collapse', 'click-through'`<br>`'sidenav-click-label': //populate according to sidenav clicked on`<br>`'sidenav-click-level': //number representing the indent level of the navigation level clicked on`<br>`'sidenav-parent-label': //label of next 1-level higher parent, undefined if is parent`<br>`'sidenav-accordion-header': //label of the collapsible accordion header`<br>`'sidenav-section-title': //h4 in design system docs` |   • Please populate `undefined` for `'sidenav-accordion-header'` since those aren't present here  <br> • All clicks here can populate `'sidenav-click-action'` with `'click-thru'` since there's no accordions here <br> • Please populate `undefined` for `'sidenav-section-title'`  <br> • As an example, populate `'sidenav-parent-label'` with `'Work with us'` when "Jobs and careers", "Internships and fellowships", and/or "Volunteer or donate" is clicked <br><br> **It would be very much appreciated if this same spec could be updated to be on `'/pittsburgh-health-care'` pages as well**
CTA Hublinks ![image](https://user-images.githubusercontent.com/48527022/109010784-390c5b00-767e-11eb-8ab3-a80afbb99712.png) | `'event': 'cta-hub-link-click'` | Looks to be coming from  `<script nonce="">` at the bottom of view page source
Jumplinks <br> ![image](https://user-images.githubusercontent.com/48527022/106677652-1dce9400-6587-11eb-973c-7132dc56195a.png) | `'event': 'nav-jumplink-click'` | Looks like these are already implemented through an `onclick` handler within the HTML 😄 
CTA buttons ![image](https://user-images.githubusercontent.com/48527022/106677883-93d2fb00-6587-11eb-8c1a-b63771805b8d.png) | `'event': 'cta-button-click' //consistently populate for ALL types of button clicks`<br>`'button-type' //'primary', 'secondary', 'default'`<br>`'button-click-label': //dynamically populate with text of button`<br>`'button-background-color': //dynamically populate with the hex code background color of the button` | These also are now being captured with our global button listener 👍 😄 
Accordions (Collapsible Panels) ![image](https://user-images.githubusercontent.com/48527022/106678067-f2987480-6587-11eb-9453-30e30910f06e.png) |  `'event': 'int-accordion-expand', //OR 'int-accordion-collapse'`<br>`'accordion-parent-label' //accordion parent label (if only one label on accordion, populate this value and make `accordion-child-label` undefined)`<br>`'accordion-child-label': //dynamically populate with secondary label of the accordion`<br>`'accordion-section-label': //populate with the label of the section where the accordion is present` | • This is a new taxonomy using 'int' instead of `'nav'` -- this is intentional to standardize our naming conventions further <br> • If the accordion only has 1 label, just populate the `'accordion-parent-label'`, otherwise populate both if there are 2 labels ![image](https://user-images.githubusercontent.com/48527022/106678263-5622a200-6588-11eb-8c12-053fdc410558.png) <br> • `'accordion-section-label'` should be things like "Primary care", "Mental health care", "Specialty care", etc | #21555
Accordion embedded links - _Static links contained within accordions_ ![image](https://user-images.githubusercontent.com/48527022/109008567-7a4f3b80-767b-11eb-8326-a5444f98ae3b.png) | `'event': 'nav-accordion-link-click, //consistent for any embedded link within an accordion`<br>`'accordion-parent-label': //accordion parent label (if 2 labels on accordion`<br>`'accordion-child-label': //accordion child label (populate with undefined if only one label` | • this event diffes from the prior accordion event to be prefixed with `nav` to help indicate the user navigated to a different page | #21556
Featured content (light blue boxes) ![image](https://user-images.githubusercontent.com/48527022/109005793-59391b80-7678-11eb-8329-9830887aafc2.png) | `'event': 'nav-featured-content-link-click' //consistently populate for all featured content link clicks`<br>`'featured-content-heading': //dynamically populate according to the header of the featured content`<br>`'featured-content-click-label': //dynamically populate according to the link label` | **For where the click class begins with `feature`, as seen in "In the Spotlight" section** ![image](https://user-images.githubusercontent.com/48527022/109005735-49b9d280-7678-11eb-9192-a7f52290ef83.png) | #21157
Breadcrumbs ![image](https://user-images.githubusercontent.com/48527022/106678784-6be49700-6589-11eb-80c0-8cf7fa2143f0.png) | `'event': 'nav-breadcrumb',`<br>`'breadcrumb-clickLabel': //dynamically populate according to the breadcrumb label clicked on`<br>`'breadcrumb-clickLevel': //level number clicked on`<br>`'breadcrumb-totalLevels': //total number of click levels`<br>`'breadcrumb-mobile-first-enabled': //boolean for if the mobile first prop is used` | This looks to be included as part of global event listeners within `<script nonce="">` at the bottom of view page source with the `breadcrumb-mobile-first-enabled` missing
Alert boxes (link click) ![image](https://user-images.githubusercontent.com/48527022/106679003-ce3d9780-6589-11eb-95f5-a0dff725ecb5.png) |  `'event': 'nav-alert-box-link-click' //consistent for all links within an alert box`<br>`'alert-box-status': //dynamically populate according to the type of alert box, 'warning', 'error', 'info'`<br>`'alert-box-headline': //dynamically populate according to the top level heading of the alert box`<br>`'alert-box-headline-level': //dynamically populate with headline level of the component`<br>`'alert-box-click-label': //dynamically populate according to the click label of the link`<br>`'alert-box-background-only: //dynamically populate with boolean true\|false if alert box background only prop was used`<br>`'alert-box-closeable': //dynamically populate with boolean true\|false if alert box is capable of being closed` | #21158 
`Alert boxes (close click) | `'event': 'int-alert-box-close' //consistently populate when an alert box is closed`<br><br> **use variables listed above as well** | • Populate variables reflecting click content with `undefined`, i.e `'alert-box-click-label'`  | #21158

**Comment by mpelzsherman** [comment]
Re: sidenav:

Clicking on the sidenav links causes a full page refresh, so the `dataLayer` variable is re-set each time.
So we need these requirements to be written in terms of the data sent to GA in the "collect" requests.

**Comment by mpelzsherman** [comment]
> Determine what still needs to be done to implement the data layer

We need to add more key/value pairs to the object sent to `recordEvent` in the `onClick` handlers (see above).

**Comment by mpelzsherman** [comment]
All of the `collect` requests sent to GA include a `dl` and `dt` parameter which appear to be derived from the URL.
DL stands for "document location": https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dl
DT stands for "document title": https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dt

These are already included in all requests, so no additional work needs to be done here.

![VA_Prescription_Refill_And_Tracking___Veterans_Affairs](https://user-images.githubusercontent.com/80267/111681192-5ce43c00-87f9-11eb-8835-1b5e065521fc.png)

**Comment by mpelzsherman** [comment]
For React-based sidenav components, we will need to modify the `trackEvents` [function](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/side-nav/components/SideNav.js#L42) to add the new params requested.

**Comment by mpelzsherman** [comment]
I'm having trouble finding the "global button listener" code for the CTA buttons. I'll need help from @bsmartin-ep and/or @jonwehausen on this.

**Comment by mpelzsherman** [comment]
For debugging we may want to add a `console.log` statement to `recordEvent` so we can see the data being added to the dataLayer before navigation.

**Comment by mpelzsherman** [comment]
Confirmed that the CTA buttons are already working as requested, so no issue is needed.

**Comment by mpelzsherman** [comment]
Confirmed jump links are already working, no issue needed.

**Comment by mpelzsherman** [comment]
Created and estimated just one additional ticket:

1. [SideNav](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21748) - 5

Other issues have already been implemented.
