### ISSUE TITLE
Design Exploration for Results Page Redesign 

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#21376]
## Description

Search results page design exploration for ways to incorporate other search tools

## Background/Context/Resources

Right rail is being discontinued and was not seen on certain screen widths

## Tasks

- [x] Mock up several possibilities for incorporating other search tools into the search results page

## Definition of Done

- [x] Drafts of several search result page designs that include a variety of ways to present other search tools

**Comment by denisecoveyduc** [comment]
This issue will roll over into Sprint 44 to allow for more exploration as the UI Search Consistency discussions continue. @mgleo will update issue as needed with comments to capture status.

**Comment by mgleo** [comment]
Progress so far:
![Eligibility page_desktop_logged out Copy@1x](https://user-images.githubusercontent.com/5553542/112206371-39036a80-8bec-11eb-9c17-06c338ae7561.png)

**Comment by mgleo** [comment]
Progress so far. 'Filter' option:
![filter-top.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/92e10cc8-c324-4aab-bc81-7a80ad99e20f)![filter-second.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/64f3bf7b-ed33-4fd4-a79a-cae5d98742b0)

**Comment by mgleo** [comment]
Progress so far. Additional options:
![all-links.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/0fd27eca-1a75-47fd-b721-58e2cdbb4784)
![blue-highlight.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/0ea65a3d-6746-4c8d-8846-a975a4290a90)
