### ISSUE TITLE
[FE] My VA: Look into how to handle 'Applications in progress' errors

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21377]
## Background

Original conversation in #21177.

It is unclear what errors we might need for the "Applications in progress" section of the dashboard, if any. Erik and Sandra will look into this and let Tressa know if design is needed.

## Tasks

- [ ]  Look into what errors we might need for the "Applications in progress" section of the dashboard 
- [ ] If design is needed, regroup with Tressa

**Comment by erikphansen** [comment]
@tressaellen I've dug into our code and if there was ever an error with getting the list of in-progress applications, we have no way of knowing that. So showing some sort of error if we cannot fetch in-progress applications is _not_ something we need to do.

Closing this since my research is done.
