### ISSUE TITLE
10-10CG: Reevaluate legal note at the bottom of the pages

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21388]
While [adding a spinner to the review page](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20405), it was noted that the "Note" on the bottom of the 10-10CG signature page is does not follow best accessibility practices. The note currently reads: "Note: According to federal law, there are criminal penalties, including a fine and/or imprisonment for up to 5 years, for withholding information or providing incorrect information. (See 18 U.S.C. 1001)"

## Acceptance Criteria
- Update designs
- Approved by accessibility 
- Create a ticket for front end implementation

**Comment by sshein** [comment]
Proposal to:
- remove "Note" messaging
- remove first spinnner message
- keep second spinner message.

When a user clicks submit, they should see the message outlined below![Screen Shot 2021-03-10 at 1.14.39 PM.png](https://images.zenhubusercontent.com/5d4c59b26a82cc000106fdf0/0b6b7914-fc4f-4f74-906a-7c6b5ce0aa71)
