### ISSUE TITLE
508-defect-2 [TTY]: VAOS - Appointment cards must have TTY: 711 links for deaf/hard-of-hearing users

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21389]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement
As a user who might want to make a Text Telephone (TTY) call, I would like to have that link available on the VAOS appointment card. If I don't have TTY set up on my smart phone, I would have to exit the VAOS application to call 7-1-1.

## Details
I've been working with Meli on the VA Mobile team to standardize TTY language and affordances. The mobile app has a telephone link and TTY links on their appointment cards. Our web application should do this as well for max consistency and usability. Screenshot attached below.

/cc @artsymartha68, @rtwell, and @outerpress for visibility

## Acceptance Criteria

- [ ] TTY links are added to all appointment cards
- [ ] Links are ideally built using our [Telephone component](https://design.va.gov/storybook/?path=/docs/components-telephone--default)
- [ ] TTY text the correct content pattern. **TTY:** is text only, and **711** is linked text. The Telephone component is encouraged because it adds a correct `aria-label` automatically.

## Environment
* https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
* Test user Judy

## Proposed Solution (if known)

```javascript
<div>
  // Previous content
  TTY: <Telephone contact="711" />
</div>
```

## WCAG or Vendor Guidance (optional)
* [Making actions keyboard accessible by using keyboard event handlers](https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls)

## Screenshots or Trace Logs
![Screen Shot 2021-03-10 at 3 57 59 PM](https://user-images.githubusercontent.com/934879/110706443-76fc9980-81bd-11eb-85d5-52a481e284b8.png)

**Comment by outerpress** [comment]
@1Copenut I'm seeing a couple different ways to list TTY number - it seems to show up regularly in parens after the main number, but I just wanted to check with you since it's not called out in the design system:

For example:

Main phone: 111-111-1111 (TTY: 711)

**Comment by 1Copenut** [comment]
@outerpress I'm sorry I'm so slow rolling back around to this. I mocked up a card (badly) in Chrome dev tools for an exemplar:

<img width="954" alt="Screen Shot 2021-03-12 at 12 28 54 PM" src="https://user-images.githubusercontent.com/934879/111843028-6f7c7500-88ce-11eb-8279-3258a848c5bc.png">

**Comment by outerpress** [comment]
Not a problem Trevor - thanks for the quick mock but just a couple clarifying q's:
* Is this the/a standard VA pattern for listing TTY numbers? I'd like to tweak it a bit.
* "TTY" seems like a good candidate for the abbr tag, as it may be confusing those unfamiliar with it - thoughts?

**Comment by outerpress** [comment]
Let's go with this - mostly the same but no extra space between Phone and TTY to help make it clear they're associated. I'll revisit this pattern in the appt cards for the new home page - we can iterate further there.

![Appt + TTY](https://user-images.githubusercontent.com/2536801/111845231-adbf6780-88c1-11eb-97d1-421137d0a925.png)

**Comment by 1Copenut** [comment]
@outerpress Is there any way we could verify these links aren't too close together on mobile? There's a lot of information that could be pressed accidentally.

**Comment by outerpress** [comment]
@1Copenut For main phone I'm using the standard 24px line height/16px spacing defined in the design system.  

Also, looking at the [WCAG success criterion 2.5.8](https://www.w3.org/WAI/WCAG22/Understanding/pointer-target-spacing), we have a couple of the exceptions to the 44x44 px guidance:

- If there is a mechanism to change the target sizes or spacing to meet the minimum, such as a button to change the sizes and layout of the targets - VAOS allows pinch zoom
- If the target is inline within a sentence there doesn’t need to be a minimum target size - not sure if this qualifies, but these are basically sentences with a couple of breaks.

When we carry this over to the new homepage I'm interested in doing some broad accessibility testing on the live site. I'll reach out to you separately about that.

**Comment by 1Copenut** [comment]
Props to you @outerpress for going to the WCAG2.2 spec!!! I agree with the points you've provide here and would be happy to help wherever I can for broad a11y testing.

**Comment by 1Copenut** [comment]
This fix looks good. I reviewed it with headingsMap and axe-core. The headings lined up nicely and this gives us a good way to add 711 links to each card. I'm going to move this one to closed.
