### ISSUE TITLE
Batching of one way messages 

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#21381]
## Task
Answer the question: **Is there a way to space out the message sends?** 
- Need to spread messages across several hours
- Need to give veterans ample time to respond before the call centers close (before 4:30pm EST)

### Definition of Done
A solution is decided upon

### Subtasks
- [ ] Testing
- [ ] Proposed Solution

### Notes
Some one way messages are prompting veterans to contact call centers. These messages go out to 1000+ veterans at the same time, which sometimes overwhelms VA call centers. 

Is there a way to space out the message sends? 

**Parameters**

- Need to spread messages across several hours
- Need to give veterans ample time to respond before the call centers close (before 4:30pm EST)

Output
- [ ] Rob to test & propose solution

Issue raised in office hours 10 Mar 2021 by Joseph Carbondale? Minneapolis, MN

**Comment by shanemelliott** [comment]
Attached is a simple workflow of a process I think might be beneficial for us.

Essentially it is a sql table used as a queue.   Any process can put records into the table/queue (ideally through a common set of business rules).   And a processor will pick them up accordingly.

How would it be beneficial?   For starters, covid vaccine outreach.    It could be helpful in a number of ways.   1) we could "batch" at any time.  The idea being that the "batch" process puts records into the queue with a send date/time.   The processor would honor that date time and not send before time.  The batch process could be done daily and randomize and chunk out the messages into ?10 minute intervals over a set period of time.   Or maybe a cohort could be batched individually chunking out the messages based on the cohort's timezone or even to the specifications of the request.  

There are a number of other processes that might be made simpler using this process.  
The outbound processor would operate on the queue table, processing records into a "processed" table.   We could scale up threads and/or containers to process heavier loads for large blasts.   It may have some fail-safes, maybe to not process between certain hours, or ???   but the basic idea is that it just picks up messages and sends them out.
Anyway,  just brainstorming.

**Comment by shanemelliott** [comment]
[Uploading... sms-outbound-processor.pdf]

**Comment by kjduensing** [comment]
Reduced # of servers to accomplish this.
