### ISSUE TITLE
Contact Center Review for Debt Resolution - Online FSR Form

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#21383]
# Request the Contact Center Review 

## What this form is for
This is for the online FSR Form 5655 which is the next product to be released after debt portal. Please note this form is very long - we are iterating on how to best present the video - it is too long to watch or download if it is not broken down -- we will upload as soon as we have a solution identified. 

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The online FSR form is an online version of Form 5565 which is the Financial Status Report Form utilized to request a debt waiver, compromise or monthly payment plan by Veterans 

### Launch Date
May 17th 2020
### Product Video
This form is very long, we are working through how to best present this in a video 

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by jwoodman5** [comment]
@leahkeeler Hi there - do you have a link to the product guide and/or video? Thanks.

**Comment by Kimberley2019** [comment]
Also, @leahkeeler if these items are not ready as of yet, can you provide an ETA of when you may be adding them to this ticket?  Thanks in advance.

**Comment by leahkeeler** [comment]
Hi @jwoodman5 @Kimberley2019 - This will be completed in this sprint - so 3/23 -- I will remove the <Draft> in ticket name and ping you when it's ready to review - Thanks!

**Comment by troyriser** [comment]
@jwoodman, @Kimberley2019, @starlow00, the initial draft of The VSA Manage Your VA Debt Reference Guide, filename VSA_Manage_Your_VA_Debt_Reference_Guide_20210311.docx, is ready for review. Thanks.[https://app.zenhub.com/files/133843125/21699fa8-7dfe-4dd7-b7ba-8028c894ad6e/download](https://app.zenhub.com/files/133843125/21699fa8-7dfe-4dd7-b7ba-8028c894ad6e/download)

**Comment by starlow00** [comment]
Hello @leahkeeler and @troyriser. The attached is ready for your review. Please let me know if you have questions/additions/etc. Once everything is as you like it, I can upload a reference copy to VEO. Thanks!

[VSA-Debt-Reference-Guide_ST_031521.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6144868/VSA-Debt-Reference-Guide_ST_031521.docx)

**Comment by leahkeeler** [comment]
It looks like minor edits @troyriser once edits are made - can you please give @starlow00 a thumbs up - Thanks! Leah

**Comment by troyriser** [comment]
@starlow00 The latest draft of the Manage Your VA Debt Reference Guide is attached, with all corrections accepted and addressed.

I did have a query in an inserted comment regarding "MyHealtheVet" usage, which you preferred as "MyHealtheVet". Search engine results refer to it as "My HealtheVet", with a space between 'My' and 'HealtheVet'. A small thing, I know, but I'm likely to encounter the term frequently and want to be sure. Thanks.

[https://app.zenhub.com/files/133843125/e2cfe351-4068-41f9-824a-317caf0cdac5/download](https://app.zenhub.com/files/133843125/e2cfe351-4068-41f9-824a-317caf0cdac5/download)

![My_HealththeVet_usage_examples.jpg](https://images.zenhubusercontent.com/60467c8abc36ad08c0959f50/dc91a5ef-646a-4e85-84b2-d4513f66c32b)

**Comment by starlow00** [comment]
@troyriser There should indeed be a space. Thank you for the spot! I will forward to VEO.

**Comment by starlow00** [comment]
Uploaded to VEO, recorded in KM Docs catalog, notified team.

**Comment by leahkeeler** [comment]
[https://app.zenhub.com/files/133843125/d869466b-0e4f-4431-ac28-a61e923f883c/download](https://app.zenhub.com/files/133843125/d869466b-0e4f-4431-ac28-a61e923f883c/download) product guide. 

Video to follow

**Comment by starlow00** [comment]
Hi @leahkeeler . Are there changes to the guide since last time that you'd like me to review?

**Comment by leahkeeler** [comment]
This is a whole different product from the debt portal - so entirely new guide

**Comment by starlow00** [comment]
Hi @leahkeeler . Attached is the draft with my edits. Questions/concerns, please let me know!
[Debt Resolution - Online FSR Form 21383_ST_050721.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6444859/Debt.Resolution.-.Online.FSR.Form.21383_ST_050721.docx)

**Comment by troyriser** [comment]
@starlow00 @leahkeeler Thank you so much for the in-depth review of the FSR User Guide, Steven. You made some good catches and I appreciate the level of detail. I've incorporated all of your revisions and updated the screen captures in those Figures where updates have been applied by the dev team to the release version. I've uploaded two documents, one is the 'redline' version with viewable markup and comment responses and the other document is the finalized 'clean' deliverable version, with all changes accepted and all comments deleted. The 'redlined' version is denoted by the title--which, it now occurs to me, might be changed by this system. A quick glance at the markup version should tell you which is which.
[VSA_DRT_FSR_USER_GUIDE_20210516.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6494637/VSA_DRT_FSR_USER_GUIDE_20210516.docx)
[VSA_DRT_FSR_USER_GUIDE_20210516_ST_REDLINE.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6494638/VSA_DRT_FSR_USER_GUIDE_20210516_ST_REDLINE.docx)

**Comment by starlow00** [comment]
Great, thanks @troyriser (cc @leahkeeler ). I will take a look and make sure VEO gets the latest clean copy for review.

**Comment by starlow00** [comment]
Sent to VEO for review

**Comment by starlow00** [comment]
VEO approved. Closing.
https://dvagov.sharepoint.com/:w:/r/sites/VACOveohotline/Training%20Files/KM%20Docs/VA.GOV/Product%20Guides/Debt%20Reference%20Guide%20Form%205655/VSA-form-5655-product-guide-v2.docx?d=wca5af7aa9b4d4df190bacb1b15339892&csf=1&web=1&e=IoRGSQ
