### ISSUE TITLE
VAMC Kiosks vt

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#21405]
**User Story**

**Overview**

**Why**

**How**

**Intersections**

**Future State**

**Tasks*

Kiosk - Clinician/VA Staff Facing Application (#Note)

### 15
"Development is complete.  Working through testing.   

Charles Henderson 
 from VA BHHCS wants to show all appointments to stop using VETlink 
Transferred on 4 Mar 2021. Original Column: In Progress"

**Comment by ambikaroos** [comment]
Note research beginning on this kiosk initiative here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/remote-discovery/research-plan.md
