### ISSUE TITLE
Verify source of VAMF 504 errors

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#21415]
Verify source of VAMF 504 errors and attach any relevant documentation, log print-outs, etc...

**Comment by ajmagdub** [comment]
We looked at the VAOS timeout errors for Mar. 06, 2021 and found 124 timeouts between '2021-03-07T02:06:55.773716Z' and 
'2021-03-07T03:09:21.238980Z'. Captured the CloudWatch records using the following commands (records stored in the file, [20210306-Faraday-Timeouts.txt](https://app.zenhub.com/files/133843125/76e9643d-5315-436c-baec-b8907a656a4b/download)):

**awslogs get dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log -s '2021-03-06T19:00:00-07:00' -e '2021-03-06T20:30:00-07:00' -f '{($.payload.service = "VAOS") && ($.payload.error = "Faraday::TimeoutError*")}' \
| ruby -pe 'sub(/^.*?\|/, ""); sub(/patients\/.+\//, "patients\/FILTERED\/")' \
| jq** 




The file, [sample-timeout-cloudwatch-records.txt](https://app.zenhub.com/files/133843125/30042072-eca4-4519-9bef-949e9cf60457/download) contains a sampling of full records for individual record ids in the  20210306-Faraday-Timeouts.txt file. The following commands were used to extract the records:

**awslogs get dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log -s '2021-03-06T19:00:00-07:00' -e '2021-03-06T20:30:00-07:00' -f '{($.payload.service = "VAOS") && ($.payload.error = "Faraday::TimeoutError*")}' \
| ruby -ne 'puts $1 if /"request_id":"(.*?)"/'**

**Comment by ajmagdub** [comment]
MAPSUP ticket, https://issues.mobilehealth.va.gov/browse/MAPSUP-1377, opened for tracking purposes
