### ISSUE TITLE
[Discovery] Determine UX goals and objectives for NOD claims

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2142]
## Goal
The goal is to gain a clear understanding of the UX work needed to allow Veterans to complete Board Appeal claims on VA.gov. 

## Acceptance Criteria
- [ ] Meeting with stakeholders to discuss background, goals, and objectives
- [ ] Agree on a plan for upcoming UX work
- [ ] Create epic and related tickets for UX work

## Stakeholders (don't contact until further notice from Andrea)
CASEFLOW SIDE
John Gosnell - Product Owner (also at BVA)
Geoffrey Stienblock - lead Product Manager for all Caseflow products

CASEFLOW CONTRACTOR SIDE
Lauren Peterson - Product Lead
Peter Karman - Engineering Lead
Dustin Ware - Product Owner

OVERALL
Troy Hamilton
Eric Hickam - Product Line Manager for Appeals

**Comment by kevinstachura** [comment]
As of now, we still need to chat with Maria Vidart to confirm the latest on the research has already been conducted and what gaps we may need to fill (for example, talking to veterans). Our best assumptions for work necessary at this point are as follows:

- Prelim Research on the experience for VSOs to input data / go through the process for a NOD appeal
- Prelim Research on the experience for lawyers to handle the NOD appeal
- Research on the experience for veterans to submit a NOD appeal
- Create the concept product, collab with SME team
- Test the concept
- Make changes to concept, present to SME team
- Begin creating hi-fi concepts 
- Test hi-fi concepts (usability testing) 
- Potential changes to hi-fi concepts from testing

These are the UX activities that we believe still exist and will need to be accomplished for this product.

**Comment by kevinstachura** [comment]
Closing this as we have identified the goals and objectives we believe are still necessary for this project.
