### ISSUE TITLE
VA.gov Search Consistency - Compile possible fields

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#21438]
## User Story

As a designer, I want to compile a spreadsheet of all possible fields/metadata that may appear in a search result so that I can take them into account while working on a consistent design pattern.

## Expected Behavior

Form searches and results across VA.gov may contain a wide variety of metadata, and we want to create a design that takes those into account so that we can achieve as much as consistency as possible.

## Acceptance Criteria

- [x] Review the different search products on VA.gov
- [x] Assess the different fields that can be displayed in the results for each tool.  Note - it may be necessary to work with a SME to uncover cases where all metadata is not displayed in all cases.
- [x] Compile a [spreadsheet](https://docs.google.com/spreadsheets/d/1KnkaMDBeOZUR9n1sG_w3JB1cpAWvg-rWOLuJPjbUwsI/edit?usp=sharing) of all possible fields.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563, @mgleo - This is a good example of a "maxed out" search result for Find a VA Form: 
https://www.va.gov/find-forms/?q=21-4138
It has the  most "related to" categories of any other form.  If you click
https://www.va.gov/find-forms/about-form-21-4138, the text under "When to use this form" is what we would want to show as a blurb in the search result.

This spreadsheet also lists the form fields currently in the system so you can get a feel for the sizes that we may encounter.

**Comment by MarciMcGuireGCIO** [comment]
The primary goal is to entice people to use the online tool when one exists.  Otherwise, we would want them to download the PDF.

**Comment by callen2563** [comment]
Here is the [list of possible fields](https://docs.google.com/spreadsheets/d/1M0XRg8q0UDsmQpKUh3Rjv2MidGFYsqOA3MJoOOWrUw8/edit?usp=sharing) for Find a Form

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 @mgleo Morning! How are things going on this?  Will the fields be compiled by the end of the current sprint? Thanks!

**Comment by mgleo** [comment]
Yes, it should be completed by the end of the sprint. 
Here's a [link to the spreadsheet](https://docs.google.com/spreadsheets/d/1KnkaMDBeOZUR9n1sG_w3JB1cpAWvg-rWOLuJPjbUwsI/edit?usp=sharing) to see progress so far. I also added it to the original ticket post above.

**Comment by MarciMcGuireGCIO** [comment]
Great!  Thank you, @mgleo!

**Comment by MarciMcGuireGCIO** [comment]
Just wanted to check if it's OK to close out this ticket.  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Creating new issues for design of elements for Global, R&S, Find a Facility

**Comment by mgleo** [comment]
> Just wanted to check if it's OK to close out this ticket. Thanks!

Yes, this ticket can be closed.

**Comment by MarciMcGuireGCIO** [comment]
Hey - we didn't have an estimate on this.  How many points was it?  Thanks!

**Comment by mgleo** [comment]
I'd say a 5.
