### ISSUE TITLE
Add field error to Claims Decision page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21448]
## Acceptance Criteria
1. On the **Ask for your claim decision** submission page, remove the disabled state from the "Submit" button, so it's always active
     - Update this page to use the form wrapper component
2. On this same page, add an error state + field error to the checkbox CC. The field error should display if the user hits "Submit" while the box is unchecked.
     - Copy for field error: "Check to confirm the information is correct." 

## Designs
**Similar field error on the DD checkbox:**
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/442012725
**Ask for your claim decision page**
https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/440796655

## Open questions
1. Display a mobile alert at the top of the page when there is an error? 
     - If so, copy needed.

**Comment by bessgreen** [comment]
@msmanak should we also display a mobile alert error at the top of the page whenever the field error displays, since this is what we're also doing on the Contact Info/DD forms? 

If so, can you advise on what the copy should be in the mobile alert? Thank you! 

cc: @bridgethapner

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/29/2021 - Looks good, button is always active, error shows as expected when submitted unchecked.  Closing.
