### ISSUE TITLE
Bug: Weird flash and slow loading - VA.gov 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#21459]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

See attached video screen grab. When I land on VA.gov, the page doesn't load right away and flashes a weird block of text before finally loading. 

The text that flashes appears to be the homepage emergency banner text. Not sure if this is a platform bug or a PW FE bug or CMS bug or all? 

### Screen grab: 

![weird-lag-and-flash-before-loading-031221](https://user-images.githubusercontent.com/43381063/110958414-ad036000-831a-11eb-9735-5409814a906b.gif)

## Specs:
- Device: Macbook
- Browser: Chrome
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL: VA.gov

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_
Page should load right away without flashing odd block of text. 

## Acceptance Criteria
- [ ] _Page should load right away without flashing odd block of text._

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ncksllvn** [comment]
Hey @jenniferlee-dsva , we did a deployment this morning that fixed this in prod. It was a great big thing yesterday, https://dsva.slack.com/archives/C52CL1PKQ/p1615482535397200. I'm writing the postmortem today.

**Comment by brianalloyd** [comment]
Thanks for reviewing @ncksllvn and thanks for the yesterday's work on fixing the issue.

**Comment by brianalloyd** [comment]
Closing this out based on deployment to fix the issue.
