### ISSUE TITLE
STEM AD: Update asynchronous processing to support Veteran UAT

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#21455]
As a member of the team developing STEM AD, I need a way to run the asynchronous processing so that we are able to effectively evaluate the success of UAT. 

## Assumptions
1. STEM AD is behind the feature flag stem_automated_decision (#13829)
2. Processing job runs every hour on the hour between 6am-6pm if EVSS is up.
3. Email and reports are only sent once very early in the morning (3-4:45AM)
    - `CreateDailySpoolFiles` at 3am M-F EST
    - `CreateSpoolSubmissionsReport` at 4:15am M-F EST
    - `Create10203SpoolSubmissionsReport` at 4:30am M-F EST
    - `Create10203ApplicantDecisionLetters` at 4:45am M-F EST
4. Jobs can be run manually in staging. We need to ask platform if it is possible in Prod too. 

## Acceptance Criteria
1. Users who are ineligible for STEM due to entitlement remaining who are also in the white list are able to create STEM automated denial records that are processed by the jobs and users not in the white list cannot. 

## Tasks
- [ ] Feature flag has been updated so that processing of STEM is no longer behind stem_automated_decision

**Comment by dmccurdybah** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6147
