### ISSUE TITLE
Add copy to loading screens

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21452]
## Context for this task
As a user, whenever I see a loading screen in the app, I also want to see a description explaining the reason behind the wait time.

## Acceptance Criteria
1. Add copy to the Appointments loading screen:
     - Copy: "We are loading your appointments"
2. Add copy to the Claims & Appeals loading screen:
     - Copy: "We are loading your claims and appeals"

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 3/18/2021 - Looks good on iOS and Android.
