### ISSUE TITLE
Verify read receipt behavior in secure messaging API

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#21453]
During a sync meeting there was a question about the semantics of the read receipt attribute of messages. Specifically whether that is only a read/unread indicator for the recipient of the message, or whether that status flows back to the sender.

**Comment by patrickvinograd** [comment]
**Does the sender of a message see the `read_receipt` attribute change when a recipient views their message?  YES**

I verified this by sending a message in staging. Immediately after sending the message, I retrieved the sent message and observed that `read_receipt` was `null`:
```
{
  "data": {
    "id": "1788051",
    "type": "messages",
    "attributes": {
      "message_id": 1788051,
      "category": "OTHER",
      "subject": "test message for read receipt verification",
      "body": "test message for read receipt verification",
      "attachment": false,
      "sent_date": "2021-03-11T23:35:05.000Z",
      "sender_id": 653432,
      "sender_name": "GPRSRESYSFIVE, ALANA ",
      "recipient_id": 1763526,
      "recipient_name": "VA Flagship mobile applications interface_SLC10",
      "read_receipt": null
    },
    "relationships": {
      "attachments": {
        "data": []
      }
    },
    "links": {
      "self": "http://127.0.0.1:3000/mobile/v0/messaging/health/messages/1788051"
    }
  }
}

I signed in to the clinician portal and viewed the message as a recipient. I then retrieved the message (again as the sender) and now the `read_receipt` attribute changed to `"READ"`:
```
{
  "data": {
    "id": "1788051",
    "type": "messages",
    "attributes": {
      "message_id": 1788051,
      "category": "OTHER",
      "subject": "test message for read receipt verification",
      "body": "test message for read receipt verification",
      "attachment": false,
      "sent_date": "2021-03-11T23:35:05.000Z",
      "sender_id": 653432,
      "sender_name": "GPRSRESYSFIVE, ALANA ",
      "recipient_id": 1763526,
      "recipient_name": "VA Flagship mobile applications interface_SLC10",
      "read_receipt": "READ"
    },
    "relationships": {
      "attachments": {
        "data": []
      }
    },
    "links": {
      "self": "http://127.0.0.1:3000/mobile/v0/messaging/health/messages/1788051"
    }
  }
}
```

**Comment by patrickvinograd** [comment]
**Does the recipient of a message see the read_receipt attribute change when they view the contents of a message? YES**

I sent a reply to the test patient, then listed messages in inbox. read_receipt was null:
```
  {
      "id": "1788060",
      "type": "messages",
      "attributes": {
        "message_id": 1788060,
        "category": "OTHER",
        "subject": "test message for read receipt verification",
        "body": null,
        "attachment": false,
        "sent_date": "2021-03-11T23:46:33.000Z",
        "read_receipt": null
      },
      "links": {
        "self": "http://127.0.0.1:3000/mobile/v0/messaging/health/messages/1788060"
      }
    }
```

I then retrieved the message and verified that read_receipt changed to "READ" in both the individual message response and subsequent list messages in inbox responses:
```
  {
      "id": "1788060",
      "type": "messages",
      "attributes": {
        "message_id": 1788060,
        "category": "OTHER",
        "subject": "test message for read receipt verification",
        "body": null,
        "attachment": false,
        "sent_date": "2021-03-11T23:46:33.000Z",
        "read_receipt": "READ"
      },
      "links": {
        "self": "http://127.0.0.1:3000/mobile/v0/messaging/health/messages/1788060"
      }
```

**Comment by patrickvinograd** [comment]
Also, the clinician UI does have a "Read Receipt" column in their Sent folder that updates when a patient views a message.

**Comment by patrickvinograd** [comment]
Assigning to Jen and Melissa just to make sure they see it. Upshot is that both parties to a message can see the read_receipt status changed to READ when the recipient views it. 

This ticket can be closed at your leisure.

**Comment by melissa-lefevre** [comment]
Thanks Patrick!
