### ISSUE TITLE
STEM AD: Most recent claims are not appearing on claim status page on staging

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#21466]
## What happened?
Claims not showing up in list of claims on claim status page despite showing on the back end as processed (all on staging)

## Steps to Reproduce
- URL: https://www.staging.va.gov/claim-or-appeal-status/
- Test User _(if applicable)_: >6 months remaining entitlement: vets.gov.user+220@gmail.com - Kent Warren
Steps to reproduce
1. Submit an application for STEM that is ineligible due to remaining entitlement greater than 6 months. 
2. Wait until the application is processed (at the top of the hour)
3. Refresh the following page to view the recently submitted claim: https://www.staging.va.gov/claim-or-appeal-status/
4. Claim does not appear at the top of the list, but shows on the back end. In the screenshot below, you can see that the most recent claims are from March 11, but the claim in question was submitted on March 12
![Screen Shot 2021-03-12 at 12.07.04 PM.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/4a325882-621d-420b-82c5-2556a5225790)

## Desired behavior
1. Submit an application for STEM that is ineligible due to remaining entitlement greater than 6 months. 
2. Wait until the application is processed (at the top of the hour but will soon be every two minutes)
3. Refresh the following page to view the recently submitted claim: https://www.va.gov/claim-or-appeal-status/
4. Claim appears at the top of the list of claims (sequential order with most recent claim at the top).

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16351

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-03-15 at 3.44.53 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/27daf9a8-2521-45a5-83c1-616c1a7c2105)

**Comment by sonntag-adam** [comment]
Testing passes QA
