### ISSUE TITLE
SPOOL: Create feature flags to initiate errors 

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#21460]
As a ___ I need to ____ so that _____. 

## Assumptions 
1. The failures will not occur as part of this story. That work will be done in the stories in AC 1a-1c. 

## Acceptance criteria
1. New feature flags have been created that cause failures to support testing of the following stories: 
   a. Support testing of track file spool file creation by RPO (#21243)
   b. SPOOL: Create notification for when spool file processing fails (#21244)
   c. SPOOL: Update processing retry functionality (#21246)
2. The new feature flags have the following naming convention: spoolTestingError1, spoolTestingError2, spoolTestingError3

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6161

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2021-03-16 at 10.42.59 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/37f8412d-cc26-4598-94ca-6b737d9ba8bd)

**Comment by delli-gatti-michael** [comment]
This is in staging. Closing this issue
