### ISSUE TITLE
UI updates to biometrics opt in screen

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#21470]
## Acceptance Criteria
1. On the biometrics opt-in screen, styling & UI match latest designs
2. Header text is Bitter Bold
3. Body text is Mobile Body
4. 40px of padding below Header text & below the paragraph of text, 20px padding (standard margin) between all other elements
5. Text is conditional based on device biometric capabilities _(see see section below for copy)_
6. Update label for primary Large Button:
     - "Turn on [Touch ID/Face ID/Fingerprint/Face recognition/Iris]"

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447232683

## Copy for AC 5
**Do you want to allow VA Mobile to use Touch ID?** 
Touch ID lets you use your fingerprint to sign in to this app. You can always change this later in your app settings. 

**Do you want to allow VA Mobile to use Face ID?** 
Face ID lets us recognize an image of your face to sign you in to this app. You can always change this later in your app settings. 

**Do you want to allow VA Mobile to use Face recognition?** 
Face recognition lets you use facial recognition to sign into this app. You can always change this later in your app settings.

**Do you want to allow VA Mobile to use Fingerprint?** 
Fingerprint lets you use your fingerprint to sign into this app. You can always change this later in your app settings.
 
**Do you want to allow VA Mobile to use Iris?** 
Iris lets us recognize a video image of your eyes to sign you in to this app. You can always change this later in your app settings.

## Accessibility Implementation Guidelines
Update primary large button accessibilityLabel= "Turn on [Touch ID/Face ID/Fingerprint/Face recognition/Iris]"

**Comment by bridgethapner** [comment]
# UI design
In invision here: https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447232683

# Notes for dev: 
- Header text is Bitter Bold
- Body text is Mobile Body
- 40px of padding below Header text, 20px padding (standard margin) between all other elements
- Text is conditional based on device biometric capabilities ([see row 14 here for all copy](https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit#gid=1717481343))

**Comment by digitalken** [comment]
PASS 3/26/2021 - Looks good except for iOS is missing a space between FACE/TOUCH and ID in the header and on the button, but the space is in the body of the text.  Logged a bug on that.  Closing.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22209
