### ISSUE TITLE
Spike - package to multi-select photos

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21474]
## Context for this task
Currently, the package that we're using for the photo upload flow does not support multi-selecting images from the photo gallery.

## Dev task
1. Investigate other packages that would allow a user to select multiple images from their camera roll 
2. The package should also support existing functionality, including:
     - Filtering by file size (50 MB)
     - Filtering by type. Supported file types: pdf (unlocked), gif, jpeg, jpg, bmp, txt

**Comment by komaly15** [comment]
Looks like https://www.npmjs.com/package/react-native-image-crop-picker will be our best option to multi select photos. By far the most widely used package, and MIT licensing, and works with our current checks. 

After selecting the photos we can get back the file path, the base64 representation of the file, each files size, and the type of file it is. We can't add pdf's or text files to image galleries, but it is able to grab jpeg, jpg, and gifs successfully. It can also grab bmp files but looks like there is a conversion to jpeg for those files. Like current implementation, the checks for file size and type will need to be done after the images are selected. Also, it looks like we can set the max number of photos to select for iOS but not android (if set, the user is unable to select more images after hitting the max). For android or for both we would need to do the number of files check after the images have been selected.
