### ISSUE TITLE
Drop down error (Android) does not go away when value is chosen for the field

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#21482]
## What happened?
In the Direct Deposit form, I didn't fill in anything and went directly to push the Save button to make all the errors appear.  I then went through and filled in the routing and account numbers, and the errors went away.  I filled in the check box and that error went away.  However, even though I chose a value for the Account type, the error remained on the screen.  It is supposed to go away when something is chosen.

SIDE NOTE:  The only way to make an error appear for the spin button field on the Android was try to submit the form without choosing a value.

## Specs:
- Device: Samsung Galaxy Note 9

## Steps to Reproduce
- Try to submit the empty Direct Deposit form to make the errors appear.
- Fill in routing number and account number to make those field errors disappear.
- Notice that even after choosing a value from the spin drop down, the error does not disappear.

## Desired behavior
Error goes away when valid choice is made.

## Acceptance Criteria
- Error goes away when valid choice is made.

## Bug Severity
- 3 - Medium

## Linked to story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19585

## Screen shot(s) and additional information

Even though "Savings" has been chosen for the drop down / spin button field value, the error is still visable.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/c85f1e97-e1a5-4915-8551-8ab80f3100e2)

**Comment by bessgreen** [comment]
This issue is a result of the Android default picker style.

**Comment by digitalken** [comment]
PASS 4/30/2021 - New picker fixed this.  Closing.
