### ISSUE TITLE
Schedule and view appointments: Minor content tweaks

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21495]
As part of our work to streamline this page, we'll:

- Change the H1 to "Schedule and manage VA appointments"
- Remove the COVID-19 vaccine alert in the header
- Add a note about the vaccine (with a link to the page) beneath the intro
- Shorten the intro

**Comment by DanielleThierryUSDSVA** [comment]
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/0b1e9db4-a11a-49d1-a111-d2420d553f7c)

**Comment by RLHecht** [comment]
This page has been published with the changes. The left nav and mega menu have been updated and the vaccine alert has been removed from the page. Moving to validate and will confirm all ok after next deploy.

**Comment by RLHecht** [comment]
Changes are live on site. I've also updated this text on the health care hub landing page. Closing ticket.
