### ISSUE TITLE
CT Redesign: Landing Page - Search by…  Solutions (Desktop)	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#21497]
Mobile solution has been addressed on desktop	

* Identify viable desktop solution based on mobile approach 
* Discuss pros/cons with UX team

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1616442793012/b7a6c5074d689d24adff3029dcbb67be1534f7fe
