### ISSUE TITLE
CT Redesign: Landing Page - Search by…  Solutions

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#21496]
Document approaches to more clearly indicate what Employer and VET TEC search are and where they are	"

* Review current functionality for baseline understanding 
* Explore possible ways to address the search challenges on mobile devices  
* Document approaches with greatest potential 
* Discuss pros/cons with UX team"

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1616442793012/b7a6c5074d689d24adff3029dcbb67be1534f7fe
