### ISSUE TITLE
COVID-19 vaccine mini-hub: Update main content section based on new info (while law is in Congress)

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21494]
## Issue Description
We need to update content to:
- Reflect changing reality of phases at VA facilities
- Answer people's questions about the new law around expanded eligibility going through Congress

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lalexanderson-dsva** [comment]
Approved content to add:

Our goal is to offer a COVID-19 vaccine to all Veterans who want one. A law is currently going through Congress that would allow us to offer vaccines to all Veterans, and possibly their caregivers and spouses. Until the law passes, we won't know who will be eligible. We also won't know how quickly we can get enough vaccine to offer one to Veterans and family members who aren't receiving care at VA.

If you’d like to get regular updates about COVID-19 vaccines at VA, [sign up to stay informed](https://www.va.gov/health-care/covid-19-vaccine/stay-informed). 

Your employer, pharmacy or local public health officials may offer you a COVID-19 vaccine. We encourage you to take the first opportunity you have to get a vaccine at the most convenient location for you.

**Comment by lalexanderson-dsva** [comment]
Draft doc showing changes: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EWD8ktYGmVhIvf_KHZBuUt4BH_XCooSR0IcjGCbqRLrJcA?e=oHgIrD 

I don't think we need to get the yellow content approved. Randi is going to start laying this out in Drupal while i get the new content JTF approved.

**Comment by lunascoop** [comment]
@RLHecht here's the Word doc for review that I assume is for the translators.
[COVID-19 vaccine mini-hub main section updates 3.15.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6144477/COVID-19.vaccine.mini-hub.main.section.updates.3.15.21.docx)

**Comment by lalexanderson-dsva** [comment]
The approved content:

Our goal is to offer a COVID-19 vaccine to all Veterans who want one. Legislation is currently going through Congress that if passed, would allow us to offer vaccines to all Veterans, and possibly their caregivers and spouses. Until this legislation passes and becomes public law, we won't know who will be eligible. We also won't know how quickly we can get enough vaccine to offer one to Veterans and family members who aren't receiving care at VA.
 
If you’d like to get regular updates about COVID-19 vaccines at VA, sign up to stay informed. {hyperlinks to www.va.gov/health-care/covid-19-vaccine/stay-informed}
 
Your employer, pharmacy or local public health officials may offer you a COVID-19 vaccine. We encourage you to take the first opportunity you have to get a vaccine at the most convenient location for you.

**Comment by lalexanderson-dsva** [comment]
@RLHecht, per our discussion yesterday, you were going to make the changes @DanielleThierryUSDSVA recommended to the mini hub, including adding the approved content. Note the changes to the approved content, above. (They were adamant that we not shorten legislation to law b/c they didn't want to imply that it was already law). 

@clantosswett want to make sure you're aware of this approval for the contact centers.

**Comment by RLHecht** [comment]
@lalexanderson-dsva Selina is inputting all the changes and I'll review it. If all has been approved we should be able to get this live later today. I can do a manual content release so we don't have to wait until tomorrow.

**Comment by lunascoop** [comment]
@RLHecht this page is ready for review.
http://preview-prod.vfs.va.gov/preview?nodeId=11463

**Comment by RLHecht** [comment]
@lunascoop These updates have been reviewed and all looks good. @lalexanderson-dsva just confirming that this can be published.

**Comment by lalexanderson-dsva** [comment]
Sorry if i'm being obtuse - i do not see the new content on that demo page.

**Comment by RLHecht** [comment]
@lalexanderson-dsva It's on the Drupal page in drop-down section. Click on the header "Will VA offer vaccines to more Veterans and family members in the future?"
<img width="823" alt="Screen Shot 2021-03-16 at 4 03 10 PM" src="https://user-images.githubusercontent.com/48728214/111372516-1cf24d00-8671-11eb-8e50-334042dc78e2.png">

**Comment by lalexanderson-dsva** [comment]
Yup. I'm being obtuse. Go ahead and get this out.

**Comment by RLHecht** [comment]
This page is published. I sent the revised updated content around the new legislation to the translators on 3/16. Sending copy of reworked top section to translators as well.

**Comment by RLHecht** [comment]
This page is live. Closing ticket and will open a separate ticket to track the translation work. FYSA @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
@lunascoop Here is the Spanish translated text for this work: [https://app.zenhub.com/files/133843125/6b8ae123-94d1-4807-a215-9ddd8b60f8b9/download](https://app.zenhub.com/files/133843125/6b8ae123-94d1-4807-a215-9ddd8b60f8b9/download)

**Comment by lunascoop** [comment]
@RLHecht the page is ready for review. http://preview-prod.vfs.va.gov/preview?nodeId=16359

**Comment by RLHecht** [comment]
This was reviewed and published. Will send to VHA translation team for final review
