### ISSUE TITLE
[epic] COVID-19 content work: 3/15 - 3/26

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21491]
Purpose of this epic is to make it easy for the team to keep track of COVID-19 content work while Danielle is out.

Folder with content: https://dvagov-my.sharepoint.com/:f:/g/personal/danielle_thierry_va_gov/ErmHD8kiDqhCjevPdN7tankBm8c-fB-b2h-vrCCd_oakZA?e=3zcDF7

**Comment by RLHecht** [comment]
Work completed in this epic. Closing.
