### ISSUE TITLE
CT Redesign: LP - Results by distance - Solution (Desktop)

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#21501]
Document approaches to more clearly indicate the distance from a searched location	

* Identify viable desktop solution based on mobile approach 
* Discuss pros/cons with UX team

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1615827374173/343e53579ea11eda60544a1b3ba93976075a95ab
