### ISSUE TITLE
STEM Automated Denial: Analytics Request	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#21506]
Analytics story is prepped and ready to submit to VSP when development is complete

- [x] UX has reviewed analytics request collab cycle input in GH 
- [x] UX has reviewed analytics request issue / template 
- [x] UX has reconciled analytics with EDU-approved KPIs 
- [x] UX submits request if functionality is in place & ready for analytics tags

**Comment by amyknox** [comment]
Analytics request info: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-analytics-request.md

Analytics request ticket (WIP): https://github.com/department-of-veterans-affairs/va.gov-team/issues/21747
- need valid test user with denied stem application
