### ISSUE TITLE
Sequestered Account Error State

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#21515]
### **Background**
* In order for users to see MHV features, they have to have an MHV account. 
* If the user has a different type of credential (example: LOA3 ID.me credential) and no MHV account, then there is a mechanism to create an MHV account for them behind the scenes via API so that they can access MVH features.
* Vets.gov used to create such accounts when SM was a live feature on the site. 
* The main difference between a "sequestered" MHV account and a  "standard" MHV account is that there is no MHV username/password associated with the sequestered account. _(there may be other differences not know to us_
* We know if a user has the appropriate account (whether sequestered or not) by the MHV account identifier that lives in MPI. 

### **User Story**
As a user, if I cannot see secure messaging on the mobile app because I don't have a sequestered account, I want to see an error page directing me to create the correct account. 

### **Acceptance Criteria** 
TBD
Questions
- Do we have the info we need to determine the best next steps for the user (either upgrade their account or create a MHV account)?

**Comment by drjecker** [comment]
Closing this ticket as we've learned:
_Already-sequestered accounts should behave the same exact way as a normal MHV Premium account so they shouldn't need their own special path in the mobile app._
