### ISSUE TITLE
Analytics Reporting Request for Caregiver team on the Health Care Application

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21516]
Hello Analytics team! We need your help tracking down some data, as well as interpreting the [funnel](https://analytics.google.com/analytics/web/#/report/conversions-goal-funnel/a50123418w177519031p184318975/_u.date00=20200101&_u.date01=20201231&funnel_goaloption_1-graphOptions.selected=analytics.nthMonth/). 

Below are some specific questions:
1) Comparing the 2019 and 2020 funnels, the numbers don't quite add up. In 2020 we had more people enter the funnel and less people drop out but we also had less submissions than 2019. What could explain that?
2) Where can I see how many people took the Foresee surveys [here](https://va-gov.domo.com/page/980067552/kpis/details/1201400353?userId=1492182741)?

Thanks!

**Comment by joanneesteban** [comment]
Adding Slack thread here: https://dsva.slack.com/archives/CBU0KDSB1/p1615822003124700

**Comment by bmcgrady-ep** [comment]
@ala-yna - [Here](https://va-gov.domo.com/analyzer?cardid=1323954828) is the ForeSee data that you requested.

**Comment by ala-yna** [comment]
Access requested!

**Comment by bmcgrady-ep** [comment]
@ala-yna - I added the Foresee chart to the KPI dashboard. Feel free to reach out with any additional questions.
