### ISSUE TITLE
Load Balancing Version 2.0

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#21512]
@wamccarty 

> "This is essentially done, but until we move completely to SSO, it is hard to say if there are more changes will be required. The two are tied together."

**Comment by kjduensing** [comment]
Currently: not everyone using SSO. Telling users it's in testing - switch to telling users it's in prod. Discuss when/how to force everyone to using it.

**Comment by kjduensing** [comment]
Talk through Wed
