### ISSUE TITLE
Add ability to run axe-checks to new Liquid Template Unit Testing Tool

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#21525]
## Issue Description
As an engineer who writes `liquid` templates for VA.gov, I need to be able to run axe-checks on `liquid` templates using the new Liquid Template Unit Testing Tool.

The axe-check implementation will allow us to write tests like this (a quick example):

```
it('passes an axe check', () => {
  const container = await renderHTML(layoutPath, data);
  executeAxeCheck('https://www.va.gov/something', container);
});
```

---
## Tasks
- [x] Add the ability to execute axe-checks on a given .`liquid` template / fixture combination.

## Acceptance Criteria
- [x] Engineers will be able to execute axe-checks on a given .`liquid` template / fixture combination.

**Comment by holdenhinkle** [comment]
# Research Links

## mocha + axe-core
### axe-core repo
This example demonstrates how to use axe with the Mocha unit testing framework:
https://github.com/dequelabs/axe-core/tree/develop/doc/examples/mocha

https://github.com/dequelabs/axe-core/blob/develop/doc/examples/mocha/test/a11y.js
```
describe('axe', function() {
  'use strict';

  document
    .getElementsByTagName('body')[0]
    .insertAdjacentHTML(
      'beforeend',
      '<div id="working">' +
        '<label for="has-label">Label for this text field.</label>' +
        '<input type="text" id="has-label">' +
        '</div>' +
        '<div id="broken">' +
        '<p>Not a label</p><input type="text" id="no-label">' +
        '</div>'
    );

  it('should report that good HTML is good', function(done) {
    var n = document.getElementById('working');
    axe.run(n, function(err, result) {
      expect(err).to.be.null;
      expect(result.violations.length).to.equal(0);
      done();
    });
  });

  it('should report that bad HTML is bad', function(done) {
    var n = document.getElementById('broken');
    axe.run(n, function(err, result) {
      expect(err).to.be.null;
      expect(result.violations.length).to.equal(1);
      done();
    });
  });
});
```

### Example: "Using aXe in Mocha Unit Tests"
https://github.com/isner/axe-mocha-unit

https://github.com/isner/axe-mocha-unit/blob/master/test/a11y.js
```
  
/* global describe, it, axe, document */

describe('axe', function () {

	it('should report that good HTML is good', function (done) {
		var n = document.getElementById('taco-button');
		axe.a11yCheck(n, {}, function (result) {
      result.violations.length.should.equal(0)
			done();
		});
	});

	it('should report that bad HTML is bad', function (done) {
		var n = document.getElementById('broken');
		axe.run(n, {}, function (error, result) {
      result.violations.length.should.equal(1)
			done();
		});
	});
});
```

### axe-mocha
OLD!!!!
~~https://www.npmjs.com/package/axe-mocha
3 weekly downloads
Last published, 6 years ago~~

---

## mocha + jsdom
Interesting post - https://github.com/dequelabs/axe-core/issues/1167

---

## jest + jsdom + jest-axe
How to - https://robertwpearce.com/catch-low-hanging-accessibility-fruit-with-axe-core.html

**Comment by holdenhinkle** [comment]
Notes from VSA Demo, 03/15/2021:

Next Steps:

- Add to Jenkins pipeline
  - Confirm - may already running with existing unit tests
- VSA - Remove any Cypress tests no longer needed
- See if we can run axe checks
- Consider using Testing Library?
  - Easier to debug
  - Queries are easier to write

**Comment by holdenhinkle** [comment]
Axe checks are working...

Draft PR - https://github.com/department-of-veterans-affairs/vets-website/pull/16394

**Comment by holdenhinkle** [comment]
`axe-core` is working with Mocha. I basically recreated the `axeCheck()` Cypress custom command so it creates the same `options` config for `axe.run()`.

To-do:
- recreate the `expandAccordions()` Cypress custom command
- replace `jsdom` with `cheerio`
- improve violations logging

**Comment by holdenhinkle** [comment]
Cheerio will not work for this project. Cheerio is a lean implementation of core jQuery designed specifically for the server and does not produce a DOM object with HTML standards on which we can use Document methods to query the DOM. This also means that we can't use `axe-core` with it.

From Cheerio docs:
"Cheerio parses markup and provides an API for traversing/manipulating the resulting data structure. It does not interpret the result as a web browser does. Specifically, it does not produce a visual rendering, apply CSS, load external resources, or execute JavaScript. If your use case requires any of this functionality, you should consider projects like Puppeteer or JSDom."

**Comment by holdenhinkle** [comment]
The `css` file is generated during the build so there’s no way to reference it in the `html` that’s generated from the `liquid` templates. Therefore, we can't run axe checks on things that require the `css`, like color-contrast, etc.

Trevor Pierce is going to help me create a smart default `options` object that we pass into `axe.run()` so checks exactly what we want it to check. We'll remove `options` as an optional argument to `axeCheck()`.

Because the `css` isn't included, we don't need a function like `expandAccordions()`.

This tool will only be for:
- testing the logic unit `liquid` templates
- running `axe` checks that don't require `css` (still SUPER helpful)

**Comment by holdenhinkle** [comment]
PR for documentation update - https://github.com/department-of-veterans-affairs/va.gov-team/pull/21696

This ticket is 99% done. The only thing left to do is to meet with Trevor to finalize the options we're passing to `axe.run()`. Trevor and I will connect tomorrow regarding this.

I should be able to submit these PRs tomorrow to finish this ticket.

**Comment by holdenhinkle** [comment]
Getting sort of a false positive on this test regarding the `title` tag - src/site/layouts/tests/vamc/health_care_region_page.unit.spec.js

The `title` on the page is present. However, the axe-check is picking up that the `title` is missing from iframes on the page - https://github.com/dequelabs/axe-core/issues/169

> Ok, it's got to be the iframes causing the error to show up. So this is a feature, not a bug... sort of. We need to be able to distinguish between errors in the main page versus errors in iframes. Put a flag or label on iframe errors to let people know where to look for the issue. It's confusing as it is now. It seems like it's reporting false positives, even though it's not.

There are a bunch of iframes in this template - src/site/includes/google-analytics.liquid

**Comment by holdenhinkle** [comment]
A 'quick' note:

It turns out above axe violation wasn't about the `title` tag; the `frame-title` check is for that. `axe-core` is erroneously reporting a violation with the title tag on the page. I'll submit an issue for that.

It turns out we need to disable the `document-title` check anyway, because `liquid` template `include` files (not entire page templates) will also be tested by this tool and those files are missing the `title` tag (along with the `html`, `head`, and `body` sections, etc., etc., etc.).

Here's the problem:

If you want to test the `breadcrumbs` `include` file (`src/site/includes/breadcrumbs.drupal.liquid`) the `html` used to instantiate a new `JSDOM` object looks like this:

```
<nav data-template="includes/breadcrumbs" aria-label="Breadcrumb" aria-live="polite" class="va-nav-breadcrumbs"
  <!-- lots of liquid code here -->
</nav>
```

The resulting `html` document looks like this:

```
<html>
<head></head>
<body>
  <nav data-template="includes/breadcrumbs" aria-label="Breadcrumb" aria-live="polite" class="va-nav-breadcrumbs"
    <!-- lots of liquid code here -->
  </nav>
</body>
</html>
```

Just like a browser, `JSDOM` adds whatever `html` is missing to make the document valid.

Notice there's no `title` tag in the `head` of the document. Because of this, we can't perform axe-checks to make sure a `title` is present, so we need to disable the `document-title` check.

If you want to test the presence of a title tag, and that the title isn't an empty string, you'll have write unit tests for those 'the old fashion way'.

**Comment by holdenhinkle** [comment]
pr - https://github.com/department-of-veterans-affairs/vets-website/pull/16394

documentation pr - https://github.com/department-of-veterans-affairs/va.gov-team/pull/21696

Both have been approved.

This ticket can be closed.

**Comment by pjhill** [comment]
Nice work!
