### ISSUE TITLE
Bug:  Pagination link logic and alignment on Outreach hub

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#21528]
## What happened?
Pagination link logic and visual alignment seem off. See screenshot and [desired behavior ](#desired-behavior) for details.

This may be a global template issue. Might be worth taking a quick look at some other products that use pagination logic.  

### Screenshot
![image](https://user-images.githubusercontent.com/43381063/111189009-058d6400-858c-11eb-8cd8-07236439bd22.png)

## Specs:
- Device: Macbook
- Browser: Firefox

## Steps to Reproduce
- URL: https://www.va.gov/outreach-and-events/outreach-materials/
- Search for some materials, so you bring up pagination UX. I had selected `Health care` and `Poster, flyer...` in the dropdowns. 

## Desired behavior
_Pagination links should appear per design system. Please consult a designer._

- In the example I'm attaching, there shouldn't be a `First`/`Last` or `Prev`/`Next` links because there's only one page of results. (There are no previous or next pages.)
- Also, when they do appear in the correct context (i.e., multiple pages of results), should the links be aligned on the same line? 
- The `First` and `Prev` links should never appear on the first page of results, since the user is already on the first page and there's no previous page to go to. 
- Ditto when the user is on the last page of results, there shouldn't be a `Last` and `Next` links, since the user would be on the last page and there wouldn't be a next page to go to. 
- Also, the page number 1 link: Since I'm on page 1, why is it linked? It's clickable but all it does is refresh the page because I'm already on page 1. UX should be that the page # is bolded but not a clickable link when I'm _ON_ that page. 

## Acceptance Criteria
- [x] _Pagination links appear per the design system._

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
Reviewed in grooming, @kelsonic to review and advise on possible fix.

**Comment by kelsonic** [comment]
Just a heads up but this is a custom pagination component it looks like + the code has not been touched for 2 years+, so I'll try to swap it out for our reusable component 🙂

**Comment by kelsonic** [comment]
PR is up to remove `Last` + `First` since our pagination component doesn't include that. I wasn't able to change any of the functionality because I have no clue where that custom javascript is coming from, it looks like @ethanteague built it so he may have some ideas though.

Regardless, the PR updates the styling so it will at least look more consistent with our other pagination components! 🙂 https://github.com/department-of-veterans-affairs/content-build/pull/209

![image](https://user-images.githubusercontent.com/12773166/120526159-2351b480-c396-11eb-9e62-893eac4314bb.png)

**Comment by brianalloyd** [comment]
Validated, looks good, closing in support.
