### ISSUE TITLE
0994: Conditionally display Service History Note

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#21524]
As a veteran, I need to be informed only of being active duty possibly impacting my housing allowance only when I specify that I am on active duty or will be going on active duty so that I do not have to read information that is not relevant to me.

## Assumptions:
1. This vets-website work is completed behind a prod flag.
2. This vets-api work is completed behind feature flag 'edu_form_omb_and_expiration' #18293.

## Acceptance Criteria
1. The following content is only conditionally displayed when the applicant answers "No" to the question "Are you on full-time duty in the Armed Forces? (This doesn't include active-duty training for Reserve and National Guard members.)"
    > "Note: Your eligibility for monthly housing allowance may be affected if you're called to active duty while receiving VET TEC benefits. Please let us know as soon as possible if there's a change in your military status."

## Supporting Artifacts:
1. Requested changes: [22-0994_changes_with_0218_updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6010463/22-0994_changes_with_0218_updates.docx)
2. [0994_Spool_Updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6012320/0994_Spool_Updates.docx)
3. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/vettec-0994/design/0994-content.md#chapter-title-step-2-of-7-military-service)
4. [Prototype](https://bahdigital.invisionapp.com/share/2CIAGBREFK8#/screens/296056883)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16384

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1534&group_by=cases:section_id&group_order=asc)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
UX Review 1/2:  This checks out for me

**Comment by amyknox** [comment]
UX Review 2/2: This checks out for me, too.
