### ISSUE TITLE
[Site Scheduled Maintenance] EVSS Maintenance and eBenefits Unavailable (March 17 and March 19)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#21529]
There is a planned maintenance outage scheduled for Wednesday, March 3 from 9-10pm ET. Details are as follows:

- EVSS will go-live to Production with the R17.14 Release (CHG0170995 / RLSE0014377) on **Wednesday, 17 March from 9:00-10:00pm ET** (pre-validation will begin at 8:30pm ET). 
- eBenefits (EBN), Stakeholder Enterprise Portal (SEP) and va.gov-consumed services will be unavailable during this event. Below is the timeline.
- Important: EVSS Depends on the following partner systems to be available from 8:30pm ET until 10:00pm ET to cover our full pre and post release validation window: BDN, BGS, CORP, DMDC/DS Logon, IAM AcS, MVI, OGC, VAAFI, VBMS, VDR, VIS, VRS.
- **If no issues are encountered, the outage will last approximately 15 minutes (from 9pm to 9:15pm ET).**
- For VA.gov - a HP site maintenance banner will not be implemented/needed because the specific authenticated products impacted will have "modal maintenance messages" invoked
- Separately: EVSS will undergo ESS CRISP Monthly Linux/Unix Patching & Database Patching  (CHG0180476) on Friday, 19 March from 10 PM ET until Saturday, 20 March at 8 AM ET. eBenefits (EBN), Stakeholder Enterprise Portal (SEP) and va.gov-consumed services will be unavailable during this event.

**Comment by johnhashva** [comment]
@brianalloyd Just added a note about a separate EVSS maintenance event on Friday, 3/19 -- which will last several hours and we need to determine whether that one -- given its expected duration -- does require a HP banner.

**Comment by brianalloyd** [comment]
Thanks @johnhashva I'll place this in our grooming list for this week, so we can address this as a team.  Thanks for sending the details, greatly appreciated.

**Comment by johnhashva** [comment]
Closing as both EVSS maintenance events occurred as planned w/o incident.
