### ISSUE TITLE
Update address in forms library with Street address line 2

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#21533]
## Issue Description
There was a request to Tweak wording on address fields. See ticket 393. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/393

Crystabel has updated the Sketch file and documentation.  Forms library needs to be updated to match design and documentation. 

---
## Tasks
- [ ] Update street address line 2

## Acceptance Criteria
- [ ] Address is updated in forms library
---

**Comment by k80bowman** [comment]
@CrystabelReiter This card says to "update the address in the forms library", but I found a couple of other places where we are using three address fields that are labeled differently (and aren't using the forms library). Should we update those as well?

- https://github.com/department-of-veterans-affairs/vets-website/blob/2d2841efc17644249ae568db8d91850c808d6ba1/src/applications/disability-benefits/all-claims/utils.jsx#L437-L448
- https://github.com/department-of-veterans-affairs/vets-website/blob/2d2841efc17644249ae568db8d91850c808d6ba1/src/applications/disability-benefits/all-claims/pages/contactInformation.js#L128-L139
- https://github.com/department-of-veterans-affairs/vets-website/blob/2d2841efc17644249ae568db8d91850c808d6ba1/src/applications/financial-status-report/pages/veteran/contact.js#L115-L119

**Comment by CrystabelReiter** [comment]
@k80bowman Yes let's update any line underneath Street address to Street address line 2 and Street address line 3 (if form has a line 3)

**Comment by k80bowman** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16473) merged
