### ISSUE TITLE
Follow Up on Franchise Fund

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#21547]
Follow up with Ryan - they were to provide feedback on why VA VISN notifications would be a good fit for franchise fund. 

Need to make sure they have all info they need to move forward with decision.

**Comment by Kennon-git** [comment]
Shane and Paras working on non-IT justification for AWS pinpoint

**Comment by Kennon-git** [comment]
we have non-it justification for AWS pinpoint. paras setting up a meeting to identify next steps to implement franchise fund.

**Comment by kjduensing** [comment]
Mtg Thursday

**Comment by kjduensing** [comment]
Meeting scheduled this week with Charles to go over.

**Comment by Kennon-git** [comment]
meeting scheduled this week .

**Comment by Kennon-git** [comment]
took care of action items, need to schedule follow up meeting with blake

**Comment by pcshah1026** [comment]
Shane sent to PBM leadership to see if they will sponsor/support our plan to move to Franchise Fund.

**Comment by pcshah1026** [comment]
@pcshah1026 schedule meeting with Blake and Ryan.
