### ISSUE TITLE
Add README to va-gov/eslint package in tool repo 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2154]
the eslint package is missing a readme. it should describe how linting works in the tools repo and how to update hte eslint rules.

**Comment by timwright12** [comment]
This is the directory in question:
https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/vagov-eslint

**Comment by timwright12** [comment]
I'm almost certain that we are not using this linting right now, but we should be

**Comment by laineymajor** [comment]
@it-harrison should this be grouped with your current support ticket?

**Comment by it-harrison** [comment]
> @it-harrison should this be grouped with your current support ticket?

No, this is not related.

**Comment by timwright12** [comment]
Closing this out as we're using a new linting and deprecated this one.
