### ISSUE TITLE
Vaccine appointments on homepage list

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21540]
## Issue Description
Currently, vaccine appointments display on the homepage appointment list as a standard VA Appointment. Update appointment cards to reflect vaccine-specific information.

VAMF dependency - https://issues.mobilehealth.va.gov/browse/VAOSR-1489 

---

## Acceptance Criteria
- [ ] If appointment is for COVID vaccine, Then label is `COVID-19 VACCINE`

- [ ] COVID vaccine appointment **cannot** be canceled online

- [ ] Given appointment is for COVID vaccine, When user tries to cancel appointment, Then cancel message displays

- [ ] User can close cancel modal

- [ ] CONTENT - Card and modal copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/VAOS_for_Distribution_Copy-homepage.docx)

- [ ] DESIGN - Designs match the specs
- Card https://www.sketch.com/s/aca1478c-8cfa-433e-8e06-d42b53aaa60d/a/9PVg2OP#Inspector
- Cancel modal https://www.sketch.com/s/aca1478c-8cfa-433e-8e06-d42b53aaa60d/a/3OnxaEz#Inspector
![21540 cancel modal.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/57d4b52e-ad96-47d6-9b0a-465685367eb7)

### Out of Scope
Scope of this ticket does not include the appointments list that's part of the Homepage Refresh work (va_online_scheduling_homepage_refresh). To be handled separately.

---

## Definition of Done

- [ ] All ACs are met

- [ ] Cheetah flow [screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/design/cheetah-flow) and [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md) are updated

- [ ] Appointment card [screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/design/appointments-cards) and [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointment-cards.md) are updated

**Comment by jbalboni** [comment]
@vbahinwillit I saw that you grabbed this, but I don't think we can complete it yet, without the backend dependency.

**Comment by laurenernest** [comment]
@marcynadeau MAS 1.26.0 is now in production. Can you verify this in production?

**Comment by marcynadeau** [comment]
@laurenernest verified if vet selects cancel, message pops up that informs veteran to contact the VAMC.
