### ISSUE TITLE
Implement data layer for VAMC new site alert

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21558]
### Issue Description
This is one task of the work from #21371. 

---
## Tasks
- [ ] Implement data layer to track events on the VAMC alert boxes using a repeatable, scalable method to capture data for new roll-outs

Description/Screenshot of Interaction | Data Layer Specification | Dev Notes | 
| -- | -- | -- | 
Alert boxes (link click) ![image](https://user-images.githubusercontent.com/48527022/106679003-ce3d9780-6589-11eb-95f5-a0dff725ecb5.png) |  `'event': 'nav-alert-box-link-click' //consistent for all links within an alert box`<br>`'alert-box-status': //dynamically populate according to the type of alert box, 'warning', 'error', 'info'`<br>`'alert-box-headline': //dynamically populate according to the top level heading of the alert box`<br>`'alert-box-headline-level': //dynamically populate with headline level of the component`<br>`'alert-box-click-label': //dynamically populate according to the click label of the link`<br>`'alert-box-background-only: //dynamically populate with boolean true\|false if alert box background only prop was used`<br>`'alert-box-closeable': //dynamically populate with boolean true\|false if alert box is capable of being closed`
`Alert boxes (close click) | `'event': 'int-alert-box-close' //consistently populate when an alert box is closed`<br><br> **use variables listed above as well** | • Populate variables reflecting click content with `undefined`, i.e `'alert-box-click-label'`

## Acceptance Criteria
Data will be tracked on me VAMC systems as they roll out
We are able to answer the following questions: 
- How often do Veterans clink within the beta alert to return to the original VAMC page?
- How often do Veteran close the beta alert to view the new modernized page?

**Comment by mpelzsherman** [comment]
There is no way to close these alerts, so that part of the AC isn't possible unless we add one.

Would you like me to add a way to close the alerts?
