### ISSUE TITLE
[Cheetah MVP] COVID Appt does not display in upcoming appointment list

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21567]
## What happened?
Reported by Marcy in #21487

After I book a COVID appointment, the appt is not displaying on upcoming appointment list. I have to refresh the page to have it displayed. This is not happening in the normal appt flow. 

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- Go through steps to direct schedule COVID appt.
- At the end of the booking process, system confirms booking details.
- Select to "view your appointments". System takes you back to home page. 

COVID appt is not displayed in list of upcoming appointments. User must refresh page to see new COVID appt.

## Desired behavior
COVID appt displays in upcoming appointments. 

## Acceptance Criteria
- [ ] Appointments display in list on page load and user does not have to refresh page

## Definition of done
- [ ] All ACs are met

- [ ] If needed, VAMF tickets are created and linked to this ticket

**Comment by jbalboni** [comment]
I have this fixed in another ticket, should go out with the #21545 work.
