### ISSUE TITLE
Cheetah-Update copy on Screener and Confirmation pages

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21564]
## Issue Description
Update the description copy on the Screener page and the information in the alert on the Confirmation page.

---

## Acceptance Criteria
- [ ] Changes are behind va_online_scheduling_cheetah feature flag

- [ ] CONTENT - Screener page copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/VAOS_for_Distribution_Copy-received_dose_screener.docx)
- [ ] CONTENT - Confirmation page copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/VAOS_for_Distribution_Copy-confirmation.docx)

**Comment by jbalboni** [comment]
@laurenernest The way the (*Required) is used in the copy doc conflicts with the form system that we use for these pages. That tag has to be included on label/legend for a given form field. Tony's PR has the (*Required) tag on the note text, which is consistent with the rest of the form pages, generally. The calendar is an exception because it doesn't use the form system and doesn't have a clear single label/legend anyway.

**Comment by laurenernest** [comment]
Thanks for the heads up. Good to stay with the form system and I'll update the copy doc.

cc @outerpress Let's revisit the required tag placement change.

**Comment by outerpress** [comment]
Thanks for the info! This is not ideal, but for now we can add a label and requiredness indicator above the radios: "Please select your answer. (*Required)"

![HP-received-CVAX-empty Copy](https://user-images.githubusercontent.com/2536801/111527534-44065880-871d-11eb-89eb-54902af72644.png)
![HP-received-anyVAX-no Copy](https://user-images.githubusercontent.com/2536801/111527538-45378580-871d-11eb-9ccf-0950b03fdb63.png)

**Comment by jbalboni** [comment]
@vbahinwillit Do you want to update your PR with these changes?
