### ISSUE TITLE
Update link section on design.va.gov 

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#21571]
With the addition of the action link, we need to specify other link styles designers can use. The current link styles on this page need to be updated to include the active link style, as well as, the visited link style needs to be the correct color. 

Current page: https://design.va.gov/design/typography
Zeplin mockup: https://zpl.io/VDj1xKW

- [ ] Update design.va.gov with updated link styles

**Comment by k80bowman** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/416
