### ISSUE TITLE
Links in staging and prod are being overridden to invalid destination

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#21576]
**Description**
The 10-10CG has links that are being overridden to invalid destinations, in each deployment environment.

|ENV|Page|Link|Is|Should Be|Image|
|---|---|---|---|---|---|
|STAG|Submission Successful|www.va.caregiver.gov|https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/www.va.caregiver.gov|www.va.caregiver.gov|<img width="300" alt="Screen Shot 2021-03-16 at 11 15 01 AM" src="https://user-images.githubusercontent.com/7391284/111335948-2d8fcc80-864b-11eb-8d0c-fb328109a9df.png">|
|PROD|Review and Submit|Privacy Policy|https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/[object%20Object]|(?)|<img width="300" alt="Screen Shot 2021-03-16 at 11 18 10 AM" src="https://user-images.githubusercontent.com/7391284/111335956-2ec0f980-864b-11eb-9ad0-50d8fe0b620f.png">|

**Comment by kevinmirc** [comment]
@ncksllvn tracked down where this error is occurring in [a platform support thread](https://dsva.slack.com/archives/CBU0KDSB1/p1615909573017800)

Assigning this ticket to @LinnJS to make the updates and correct the issue.

**Comment by LinnJS** [comment]
Was fixed in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16385) that got merged today.
