### ISSUE TITLE
permission based security library

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#21573]
Create authentication EJB library for the cohort management application.    Ideally the library will be able to be consumed by the vetext portal to move to permission based security instead of hierarchical roles.

**Comment by Kennon-git** [comment]
this is needed in VEText for adhoc messaging functionality. is currently blocking administrators from using inactive veterans functionality.

**Comment by kjduensing** [comment]
Discuss naming conventions (currently mostly database work).

**Comment by kjduensing** [comment]
Discuss roles and use cases Wednesday

**Comment by Kennon-git** [comment]
in prod. first use case is the ad hoc messages tab. permission vs role. 
rob needs to tighten functionality to make it user friendly.
