### ISSUE TITLE
STEM AD: Update form aria label text on claim details page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#21570]
As a developer, I need to update the aria label text for forms on the claims detail page so that that content is compliant with section 508 and the users are communicated the appropriate information when tabbing through the page.

## Assumptions:
1. Completed behind feature flag `stem_automated_decision` (#13829)
2. Login to claims page here: https://staging.va.gov/claim-or-appeal-status/
3. 10203 denials are added to page found here: https://staging.va.gov/track-claims/your-claims
4. Origination of this story: #21058

## Acceptance Criteria
In the "What should I do if I disagree with your decision?" section of the claim details page:
1. The "Download VA Form 20-0995" link:
    a. alt/aria-label text is: `Download Decision Review Request for Supplemental Claims VA Form 20 - 0 9 9 5. Opens in new browser tab`
    b. url is: https://www.vba.va.gov/pubs/forms/VBA-20-0995-ARE.pdf
    c. clicking link opens in form in new tab
2. The "Download VA Form 20-0996" link:
    a. alt/aria-label text is: `download Decision Review Request: Higher-Level Review VA Form 20 - 0 9 9 6.  Opens in new browser tab`
    b. url is: https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf
    c. clicking link opens in form in new tab
3. The "Download VA Form 10182" link:
    a. alt/aria-label text is: `download Decision Review Request: Board Appeal for Notice of Disagreement VA Form 1 0 1 8 2.  Opens in new browser tab`
    b. url is: https://www.va.gov/vaforms/va/pdf/VA10182.pdf
    c. clicking link opens in form in new tab 
4. The "Download VA Form 20-0998" link:
    a. alt/aria-label text is: `download Your Rights to Seek Further Review of Our Decisions VA Form 20 - 0 9 9 8.  Opens in new browser tab`
    b. url is: https://www.vba.va.gov/pubs/forms/VBA-20-0998-ARE.pdf
    c. clicking link opens in form in new tab

## Supporting Artifacts:
1. [Current Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content-V2.md)
2. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222481/296056346/preview)
   a. [Link to prototype for folks without accounts](https://bahdigital.invisionapp.com/share/CUIAG8PZ85J#/screens/296056346)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16457

**Comment by delli-gatti-michael** [comment]
Local Testing complete

![Screen Shot 2021-03-22 at 3.55.59 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/47070296-0d58-44e4-9788-598e7aa68f10)

---

![Screen Shot 2021-03-22 at 3.53.38 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2b87fc70-9a6c-4213-9238-36f80d81e6f2)

---

![Screen Shot 2021-03-22 at 3.54.04 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a3ba14ad-b67c-4a4e-9075-98add7724c73)

---

![Screen Shot 2021-03-22 at 3.56.09 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/db7dadba-7e0d-48e0-8024-2c9cadd79660)

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me

**Comment by delli-gatti-michael** [comment]
User: vets.gov.user+220@gmail.com
Password is in the [sensitive repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

Link: https://staging.va.gov/track-claims/your-stem-claims/8488/status

**Comment by watersemma** [comment]
UX Review 2/2: Good to go! I appreciate your patience.

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1552&group_by=cases:section_id&group_order=asc)
