### ISSUE TITLE
Flaky vets-api RSpec Causing Random CI Failures `va_appointments_adapter_spec.rb`

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#21589]
## The Problem
One of the rspecs in `vets-api` occasionally fails. This causes a failed CI on the `master` branch.

```
rspec ./modules/mobile/spec/models/adapters/va_appointments_adapter_spec.rb:374 # Mobile::V0::Adapters::VAAppointments with appointments that have a missing status includes a hidden status
```

[Source](http://jenkins.vfs.va.gov/job/testing/job/vets-api/job/master/4297/console)

## More Context
These flaky failures can lead to disruptions to the daily production deploy of `vets-api`. The production deploy jenkins job requires that the most recent CI run is passing:
![image](https://user-images.githubusercontent.com/3077884/111361267-072a5b00-8664-11eb-8b1c-7640497f86ec.png)

[Source](https://github.com/department-of-veterans-affairs/vets-api/commits/master)

## Work to be Done
- [ ] Fix flaky rspec
or 
- [ ] Add logic (retry or skip) to make sure this test doesnt flake out and cause CI to fail

**Comment by ericboehs** [comment]
Looks like @kreek might be able to address this one.
