### ISSUE TITLE
Remove FE usage of `AsyncTransaction::Vet360::*` strings

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#21587]
Now that https://github.com/department-of-veterans-affairs/vets-api/pull/5973/ has been merged, we can update the FE code to stop looking for `AsyncTransaction::Vet360::*` strings.

The FE code should be updated in two places:
- https://github.com/department-of-veterans-affairs/vets-website/blob/6c70966ccde1d9baa4851f1194e55a1c0ba737bd/src/platform/user/profile/vap-svc/containers/VAPServicePendingTransactionCategory.jsx#L22-L33
- https://github.com/department-of-veterans-affairs/vets-website/blob/6c70966ccde1d9baa4851f1194e55a1c0ba737bd/src/platform/user/profile/vap-svc/constants/index.js#L30-L45

**Comment by SKasimow** [comment]
@adamwhitlock1 - is this still needed?

**Comment by adamwhitlock1** [comment]
Yes, it does look like this is still needed. Should be a pretty quick ticket

**Comment by adamwhitlock1** [comment]
this was merged and no issues encountered when removing the old strings. Will close out now.
