### ISSUE TITLE
[Discovery] react-18-next, integration with github repo

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#21582]
enable json edibility for content editors

**Comment by youngfreezyVA** [comment]
i opened a draft PR up for `react-i18-next` integration:
https://github.com/department-of-veterans-affairs/vets-website/pull/16443/files
in this implementation, the `translationsContent` json can be pulled from any github repo, so I think we are good on this for discovery purposes. For actual implementation, I was thinking about adding a markdown file to the `vagov-content` repo similar to whats being done in `pages/coronavirus-research.md`. would need a follow on ticket if we agree that this is the approach we want to take
cc: @DanielleThierryUSDSVA @Yuffster-usds

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA @Yuffster-usds Hello - can you provide some feedback on whether there are any issues/concerns with re-using the vagov-content repo?

**Comment by youngfreezyVA** [comment]
@DanielleThierryUSDSVA @Yuffster-usds +1 to @SKasimow's question above. alternatively, we can have a repo dedicated to internationalization/translated content, which would just have a single json file for now. but eventually, it could be the integration point for any machine learning solutions

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - I know we need an answer to above ^ but can this ticket be closed?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow @youngfreezyVA. I don't think I'm the best person to answer this question. I only raised the possibility of GH because of the difficulties in trying to do localization correctly in the existing Drupal template and the fact that these pages are going to be separate from the benefit hub content. 

But I think this is ultimately more of a technical discussion and I would defer to @Yuffster-usds and the platform team on this. I definitely think it's important to get platform feedback.

Thanks!

**Comment by SKasimow** [comment]
@youngfreezyVA Hi Fareez - can you let us know what the recommendation is after you speak with @Yuffster-usds and platform team?  Thanks, Sharon

cc: @DanielleThierryUSDSVA

**Comment by SKasimow** [comment]
@youngfreezyVA did you get direction for this? can we close?

**Comment by youngfreezyVA** [comment]
Since I didn't hear back from anyone -- I think we can close with the assumption that we will keep the json translations in the public websites repo.

**Comment by SKasimow** [comment]
Aligns with Michelle. Closing this.
