### ISSUE TITLE
Add UI for when there are no appointments or requests

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#2158]
We need a message to show up whenever there are no requests or appointments sent back from the api.

Here's the mock screens. We can leave out the first sentence that has the "insert description here" text for now. These would display on the existing `/vaos/appointments/confirmed` and `/vaos/appointments/pending` pages:

![image](https://user-images.githubusercontent.com/12564977/65171233-60d2aa80-da18-11e9-9eaf-53892f45aa95.png)

![image](https://user-images.githubusercontent.com/12564977/65171289-7ea00f80-da18-11e9-9abb-4b7ab5f70258.png)

In order to simulate no appointments available, you can replace the contents of [confirmed.json](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/actions/confirmed.json) with this:

```
{
  "vaAppointments": [],
  "ccAppointments": [],
}
```

And for requests, you can replace the contents of [requests.json](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/actions/requests.json) with:

```
{
  "appointmentRequests": []
}
```

In the components for these pages, we should be able to detect when there are no appointments or requests by checking that the list we get is empty.

**Comment by jenniemc** [comment]
@jbalboni, are you suggesting I modify the existing ConfirmedAppoinmtentListItem.jsx and PendingAppoinmtentListItem.jsx to display the message above when api returns no confirmed appointments and no appointment requests on the respective webpages?

**Comment by jbalboni** [comment]
@jenniemc It would be the PendingAppointmentListPage and ConfirmedAppoinmtentListPage files, but yes, that's correct.

**Comment by jenniemc** [comment]
Thanks @jbalboni

**Comment by jenniemc** [comment]
@jbalboni @markgreenburg, can you provide the URL for the link, VA Medical Center, should hyperlink to?

**Comment by jbalboni** [comment]
I think it would link to `/find-locations` (i.e. https://www.va.gov/find-locations, but you can leave off the va.gov part)

**Comment by jenniemc** [comment]
thanks!
