### ISSUE TITLE
VAOS vets-api documentation - clinic_institutions_controller

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#21599]
Identify gaps and update `vaos.yaml` to reflect how a client would interact with the associated endpoints. This would include request structure, parameters definitions (e.g. required, type, etc...) and response and error structure. The final .yaml file should be easily compiled into a swagger document that can be viewed in a swagger UI type tool.

**Comment by ajmagdub** [comment]
The clinic_institutions_controller endpoint swagger api doc was already included in the vaos.yaml file. Verified that it was correct and this ticket could be closed without any changes to the vaos.yaml file.
