### ISSUE TITLE
Remove vets-api/docs/api directory

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#216]
Migrated from `vets.gov-team` [ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/5601)

In the `vets-api` repo, the `docs/api` directory contains markdown files that document endpoints, including request and response examples.
We currently have Swagger documentation that does the same thing.

While the [matter of us continuing with Swagger or some other type of documentation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/129) is still undetermined, it is our current standard as of this writing.

The `docs/api` is redundant and given that it hasn't been updated in over two years is certainly incomplete/outdated.

## AC
- [x] For endpoints that have Swagger documentation, delete the corresponding `docs/api` file
- [x] For endpoints that do not have Swagger documentation (which is hopefully none), create a GH issue for the creation of Swagger docs.  Please include a link to the corresponding existing `docs/api` file, and instructions to delete it afterwards.
- [x] Delete the `docs/api` directory when all it's contents are gone

**Comment by LindseySaari** [comment]
I think this ticket is complete? I'm not seeing the docs/api directory

**Comment by jholton** [comment]
Yup.  Looks like Travis took care of it.
