### ISSUE TITLE
Find a VA Form [Bug]: Searches starting with specific digits fails to fire the button click event

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#21615]
## What happened?
When a 3+ character search term starts with the digits 20, 21, 22, 26, 29, or 40, the search button click event fails to fire in Safari or Internet Explorer.   This appears to be directly related to recently-added logic to "auto-corrects" those strings -- see https://github.com/department-of-veterans-affairs/va.gov-team/issues/20651#issuecomment-797594089.   

This bug impacts only 10 of the top 1000 search terms used since July 2020; with those specific terms ranking between 203 and 999 in popularity.

## Specs:
- Device: iPhone 11, Windows 10
- Browser: Safari, IE 11
- Test User: N/A

## Steps to Reproduce
- URL: https://www.va.gov/find-forms
- Test User _(if applicable)_: N/A
- Enter any of the following search terms 200, 210, 220, 260, 290, or 400 into the search bar and press **Search**
- Observe that the search button fails to trigger an event

## Desired behavior
Entering any of the above search terms and pressing Search should return a search result or a "not found" message.

## Acceptance Criteria
- [ ] Any string entered into the search box should allow the Search button click event to fire in order to produce a result or "not found" message.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO good catch!

**Comment by zacharymorel** [comment]
Thank you, opening a PR now.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO This is live on https://staging.va.gov/find-forms/?q=200

**Comment by MarciMcGuireGCIO** [comment]
Confirmed it is working now! Nice job, @zacharymorel 

cc @johnhashva
