### ISSUE TITLE
[Design]: Clarify language around adding a Primary Family Caregiver

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21611]
## Background 
In the [usability studies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/1010cg-mvp) we've done on the 10-10CG, caregivers have repeatedly expressed confusion around the wording of the "Would you like to add a Primary Family Caregiver" question.  Let's reword that question to make it less confusing to Veterans/Caregivers. 

## User Story
As a Caregiver, 
I want to understand how to apply for the PCAFC and complete the form without confusion
So that I can best assist the Veteran I care for. 

## Acceptance Criteria
- Content updated
- Prototype updated
- Front end implementation ticket created
- Content approved by VSP, Caregiver program team

**Comment by sshein** [comment]
short term copy tweaks are below:
![Primary.png](https://images.zenhubusercontent.com/5d4c59b26a82cc000106fdf0/9436297a-125f-4039-bb89-e47cc640e044)![Secondary.png](https://images.zenhubusercontent.com/5d4c59b26a82cc000106fdf0/d7a7cdf1-d187-4044-b87e-c32dd4726fb1)

**Comment by ala-yna** [comment]
Next step: Add to single source of truth prototype and pin to the Caregiver channel ( @sshein )

**Comment by sshein** [comment]
Changes can be seen at the following prototype:

- Primary: https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666481/simulate/sitemap?mode=i
- Secondary: https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666485/simulate/sitemap?mode=i
- And the bottom of the Secondary contact asking if they want to add another: https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666487/simulate/sitemap?mode=i
