### ISSUE TITLE
Bug on Form 526 new disability pages

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#21627]
On  https://www.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/follow-up/0 users see a high number of errors in sentry.  So far it's 5.7k events

`undefined is not an object (evaluating 'e["ui:collapsed"]')`
http://sentry.vfs.va.gov/organizations/vsp/issues/1089/?environment=production&project=4&query=source%3A526EZ-all-claims&sort=priority&statsPeriod=14d

**Comment by Mottie** [comment]
I've merged in a fix... 🤞🏽 let's hope it works
