### ISSUE TITLE
Update chatbot to reflect latest eligibility info

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21628]
## Issue description

Update chatbot to reflect latest eligibility and legislation changes.

### Update 1

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/88a5dd46-2916-4f0c-bebb-5e679d899428)

**Change to:**

At this time, we can only offer COVID-19 vaccines to these 2 groups when the Veteran is eligible based on VA and [CDC COVID-19 risk criteria](https://www.cdc.gov/vaccines/covid-19/phased-implementation.html):

- Veterans who currently receive care through VA, **and**
- Designated primary and secondary family caregivers who are enrolled in our Program of Comprehensive Assistance for Family Caregivers (PCAFC) 

Different VA health facilities are at different phases of our plan. If you're a Veteran who receives care through VA, your local facility will contact you when your risk group is eligible for a vaccine. Designated caregivers are eligible for a vaccine when the Veteran they care for is eligible. 

You can sign up for an easy way to stay informed about getting a COVID-19 vaccine at VA. When you sign up, we’ll also ask about your vaccine plans. Your local VA health facility may use this information to determine when to contact you once your risk group becomes eligible.

[Sign up to stay informed](https://www.va.gov/health-care/covid-19-vaccine/stay-informed)

**Note:** We’ll attempt to contact every eligible Veteran in each risk group. You don’t need to sign up to get a vaccine. Our staff will only provide vaccines to Veterans and caregivers who are currently eligible for one based on VA and CDC risk criteria. 

### Update 2

Add the new question: "Will VA offer vaccines to more Veterans and family members in the future?"

Recommend adding here:

 ![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/122e0598-059c-4536-a055-bbe92e17babc)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @lalexanderson-dsva - no action needed

**Comment by lunascoop** [comment]
@RLHecht I just pinged for a PR review. https://github.com/department-of-veterans-affairs/covid19-chatbot/pull/364

**Comment by RLHecht** [comment]
@lunascoop Just approved it!

**Comment by RLHecht** [comment]
These changes are live on the chatbot. Closing ticket.
