### ISSUE TITLE
Rewriting/Editing of Call-Center FAQ Info

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#2163]
Review the linked documents about two-factor authentication. Light research on these topics may be needed. The main focus will be the FAQ document, which needs to be simplified and put into our plain language style. The docs won't live on the website but will be background info/scripts for folks in our call centers who get queries. 

Feedback and recommendations are needed by end of this week (October 1). 

1.  [DSL 2FA Informational Paper]([https://app.zenhub.com/files/133843125/7a9fdf07-5212-4dd2-9efe-cc04a3f38260/download](https://app.zenhub.com/files/133843125/7a9fdf07-5212-4dd2-9efe-cc04a3f38260/download))- This includes the detailed communication plan, technical strategy, and workflows.  This document previously went out and has not changed.
 
2.  Updated Screenshots with information on what changed within DSL (file too large). Will try to add
 
3.  INPUT NEEDED:  DMDC is working to simplify the [FAQs]([https://app.zenhub.com/files/133843125/afe846d4-8d33-49c2-aa39-22bf53988e56/download](https://app.zenhub.com/files/133843125/afe846d4-8d33-49c2-aa39-22bf53988e56/download)) to make it more user friendly, easier to understand, and really simplify what our users need.  I am requesting your feedback on this draft document.  If we get review and feedback this week, we can get the simplified FAQs as part of this release (screenshot is included in #2).  Please use track changes and comments to provide feedback as soon as possible (this week please).  This document is supposed to assist call centers reduce phone calls so if something is not captured and you get a high volume of calls on, add to end of document with track changes on.  I will compile feedback, questions/answers and hopefully get it out with our 2FA release.  This is a draft document so please point out any grammar, wording, confusing sections.

**Comment by lunascoop** [comment]
Closing issue as this work is essentially "outside" of our team's scope and will impact sprint velocity.

**Comment by Karak888** [comment]
closing this ticket.  Email was sent to Autumn.
