### ISSUE TITLE
STEM AD: Email Applicant 10203 Decision direct link causes error

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#21630]
Steps to reproduce:
1. Login with user 220
2. Submit 10203 
3. Open up email We've made a decision on your STEM Scholarship application
4. Select  https://www.staging.va.gov/track-claims/your-stem-claims/[10203 denied claim identifier]/status in email
5. You receive the error
![Screen Shot 2021-03-16 at 10.49.42 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/757f61ac-d711-4ab7-9f5c-fe8fe1a7d702)
##

Expected Results:
Direct link https://staging.va.gov/track-claims/your-stem-claims/[10203 denied claim identifier]/status loads upon selection

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16413

**Comment by sonntag-adam** [comment]
The direct link now works. Closing bug.
