### ISSUE TITLE
Create VAMF integration document

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#21644]
complete this document: https://wiki.mobilehealth.va.gov/pages/viewpage.action?pageId=192853920

add it to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/engineering/architecture

**Comment by laurenernest** [comment]
@grossb1 is this still needed?

**Comment by grossb1** [comment]
Closing for now, will reopen if VAMF requests that we create this.
