### ISSUE TITLE
Analytics fixes for typeahead 0 suggestion states

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#21648]
## Description

Search.gov resolved a bug fix that was preventing suggestions from dropping off the list after 30 days. As a result analytic fixes are required to ensure that when no suggestions are presented to users it does not count as a user experience failure. Fixes will also better capture the user flow given the new set of suggestions that will appear. 

## Background/Context/Resources

Analytics Request Issue - [#20889](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20889)

## Tasks

- [x] Updating analytics tagging to better capture user flow and ensure that a certain edge cases no longer result in 0 suggestions being recorded, causing analytics to show a user experience failure.

## Definition of Done

- [x] analytics tagging is able to track user experience and account for when 0 suggestions are presented to users.

**Comment by srsuddath** [comment]
PR has been merged with updated analytics
