### ISSUE TITLE
Research Adding DOM Testing Library to Liquid Template Unit Testing Framework

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#21651]

**Comment by holdenhinkle** [comment]
This is complete. Simply import the queries you want from `'@testing-library/dom'` like so:

```
import { getByText } from '@testing-library/dom';
```

Then use it like this:
```
let container;

before(async () => {
  container = await renderHTML(layoutPath, data);
}

// then, it an `it` block:

const node = getByText(container, '3500 Ludington Street');
```

From the [Dom Testing Library docs](https://testing-library.com/docs/queries/about): "All of the queries exported by DOM Testing Library accept a container as the first argument."

Creating a ticket to update the Liquid Template Testing Framework documentation.

This ticket is complete.
