### ISSUE TITLE
[FE] My VA content updates

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#21652]
## Background

There's been some small content changes to MyVA that need to be implemented on the FE. I'm tracking them all here and if things get too complicated, this can be an epic for all of the changes. Also, some of these might already be done, but I'm just going to list everything that we had based off the prototypes to make sure we get it all. 

## Changes

- [x] Please change: What benefits does the VA offer TO: What benefits does VA offer?
- [x] In the drop 'What benefits does VA offer?' down the first three bullets need to be changed to: Health care, Disability compensation, Education and training
- [x] Claims and appeals cards: Please remove the word “date” as the date is already listed in the card.
- [x] Add 'your' to 'Continue application' link ----> "Continue your application" 
- [x] Add 'your' to manage all claims and appeals link--> Manage all your claims and appeals
- [x] In 'Benefits you might be interested in' titles need to be updated to: Health care (no change) | Disability compensation | Education and training
- [x] In 'Benefits you might be interested in' links need to be updated to: Learn how to apply for VA health care | Learn how to file a VA disability claim | Learn how to apply for VA education benefits
- [x]  In 'Benefits you might be interested in' the Education and training blurb need to be updated to: With VA education benefits, you and your qualified family members can get help finding a college or training program and paying for tuition or test fees.
- [x] The health care link in 'Benefits you might be interested in' should go to: https://va.gov/health-care/how-to-apply/

<img width="580" alt="Screen Shot 2021-04-01 at 3 48 39 PM" src="https://user-images.githubusercontent.com/58752772/113346388-41406180-92e0-11eb-8401-c1a4b6e5e053.png">

**Comment by sanlouise** [comment]
Merged and closing.
