### ISSUE TITLE
Spike - check file viewer + file picker for compatibility w/ list of file types

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21661]
## Context for this task
In the Secure Messaging UX, users will have the ability to:
1) View message attachments from their device, and
2) Upload attachments to their messages. 

Regarding #1, the most similar experience we currently offer in the app is for the Letters download / viewing a .pdf in the device's file viewer. Regarding #2, this is most aligned with the Claims File Upload flow. 

However, MHV's list of accepted file types differs from the list that we're using for Claims File Upload. Ideally, the mobile app can support viewing & attaching each of these net new file types.

## Dev task
1. Investigate the file viewer (letters download) and the file picker (claims file upload) that are currently used in the app and check if both can be used with the following file types:
     - doc, docx, jpg, pdf, png, rtf, txt, xls, xlsx
2. If any of these file types cannot be supported, note which ones so we can discuss next steps w/ AH

## Designs
- Example of UI where a user could view their attachments:
- Example of UI where a user could attach a file to a message:

**Comment by komaly15** [comment]
Checked the file picker and file viewer for both iOS and Android, and in all cases we are able to use all the file types listed above

**Comment by bessgreen** [comment]
@drjecker good news! @komaly15 found that the file picker/viewer we're currently using in the app can support the new file types for the Secure Messaging features.

cc: @bridgethapner
