### ISSUE TITLE
CLP test build (Mission Act) on staging with  "password protected" sing-in prompt 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#21665]
## Issue Description
_CLP test build (Mission Act) on staging with a "password protect" sign-in prompt".  this is the action plan reviewed by Nick during planing that uses HTML for a password while on staging environment_

## Front end tasks
- Place CLP test build (Mission Act) on staging with "password protect" prompt 
- Connect to analytics ticket to ensure we can debunk click tracking as intended 

## Acceptance Criteria
- [ ] CLP test build is on staging with appropriate banner/test rails 
- [ ] Ensure analytics click tracking is working in support
- [ ] Valide on staging.
- [ ] Share Password / Username to PO/PM 

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
@kelsonic I talked with @johnhashva today concerning the promote to staging for the CLP build in support of Analytics and when you're ready lets promote and trigger us to validate in staging (with password) and ensure everything is working correctly.  Once validated we'll need to follow up with the CLP Analytics ticket so we can check all data layers with insights team to ensure everything is working properly.  Let me know if you have any questions.

**Comment by kelsonic** [comment]
PR merged, should go out with daily deploy today 👍

**Comment by johnhashva** [comment]
@kelsonic is the password clp123?  clp1234?   No reason not to post here.

**Comment by ncksllvn** [comment]
the password is `clptest123`!

**Comment by brianalloyd** [comment]
Thanks @ncksllvn
