### ISSUE TITLE
[Ongoing Service] Continue Logging/Errors/Metrics work for Identity team success metrics

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#21670]
## User Story
As a memeber of the Identitity Team, I want to continue working to log and track our success metrics so that we can continue to iterate on our offerings. 

## Artifacts
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-outline-template.md))
- Link to product README ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/product-readme-template.md))

## TODOs
- [ ] Convert this issue to an epic
- [ ] Add your team's label to this epic

**Comment by bosawt** [comment]
@joeniquette All tickets in this epic have been completed. Can we close it?
