### ISSUE TITLE
Come up with better approach for organizing Cypress mock data setup

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#21678]
Currently, the way we set up mock data for Cypress is pretty confusing. At the root of it, we're mainly using the same set of mock data we use locally, but there are a few things we generate so that dates are in the future. But it's all buried in several nested functions and it's unclear what effect changing things will have.

AC
- Come up with a clearer organization for the Cypress data set up code
- Update the tests to follow the new approach, or create more tickets to address specific tests

**Comment by LanceGundersen** [comment]
Best Practices https://docs.cypress.io/guides/references/best-practices
- [ ] Selecting Elements => by using highly brittle selectors that are subject to change is an Anti-pattern. Recommend using data-* attributes to provide context to your selectors and isolate them from CSS or JS changes. `data-cy="submit”`
- [ ] Creating "tiny" tests with a single assertion => acting like you're writing unit tests is an anti-pattern. Recommend add multiple assertions and don't worry about it
	- It is common for tests in Cypress to issue 30+ commands. Because nearly every command has a default assertion (and can therefore fail), even by limiting your assertions you're not saving yourself anything because any single command could implicitly fail.
- [ ] Using after or afterEach hooks => using after or afterEach hooks to clean up state is an anti-pattern. Should clean up state before tests run.
- [ ] Unnecessary Waiting => Use route aliases or assertions to guard Cypress from proceeding until an explicit condition is met.

Mocks
- [ ] To make the route mocks more flexible and reusable, we should make each real HTTP call in our application into a separate arrow function mocking that same call. https://blog.bitsrc.io/mocking-http-calls-in-cypress-end-to-end-tests-fa2e6b7caaf7
- [ ] Suggest organizing into a mocks folder structure with the name of the file in relation to the page, call or a combination. Could even be something else altogether.

This file `src/platform/testing/e2e/cypress/support/commands/syncFixtures.js` is pretty neat and if you do a code search for syncFixtures you can see how other teams are using it. Why they named it constants I am not sure but it had me curious if we could do a syncPlugins like that.

The second thought is we could just do the functions like ware currently doing and just rename/restructure it a bit. Ideally it looks like you would just set the function to a task and call that task opposed to calling the function directly.

**Comment by vbahinwillit** [comment]
To address the issues stated above, the following changes to the Cypress e2e tests have been implemented in addition to the changes suggested above:

PageObjects have been added for encapsulation and reuse of testing logic. 
Mock api calls have been refactored and old v0 and v1 api calls have been removed
Documentation has been added

Hopefully this refactor results in tests the are easier to read and maintain.
