### ISSUE TITLE
VA File Number Does Not Exist vs SSN Check

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21680]
## Background
Need to rely first on VA File number, not SSN for a check

## Considerations

> 125480998 
> ebn test user 2
> born 8/18/1988

- VA File Number is different than SSN for this user
- Should we be sending File Number to VBMS instead of SSN?
- VBMS uses VA File number

## Tasks
- [x] Swap out the lookup to be VA file number instead of SSN.

## Acceptance Criteria
- [x] When uploading to VBMS, we use the VA file number to find the right folder, not the SSN

**Comment by jason-gcio** [comment]
What if there is no VA file number or its wrong?
Or if we check for VA file number and don't find one, revert back to SSN?

**Comment by RudyOnRails** [comment]
> What if there is no VA file number or its wrong?
> Or if we check for VA file number and don't find one, revert back to SSN?

Should these questions be answered before I begin on this?

**Comment by kathleencrawford** [comment]
> > What if there is no VA file number or its wrong?
> > Or if we check for VA file number and don't find one, revert back to SSN?
> 
> Should these questions be answered before I begin on this?

We should use VA File Number if we have it.  If not, use SSN
