### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#21685]
# Request Google Analytics and/or Domo access

## User Email Address
[aubrey@thesocompany.com
](mailto:aubrey@thesocompany.com)
## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [ ] Domo
_Please list any additional requirements, if any._

## Date Required
preferably this week, but not a priority. 

## Product Team / External Team / VA Office
Identity and Testing Tools teams

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @aubreyarcangel , 

You should have received an email invite with you Google Analytics access. 

We will close this issue but please feel free to reopen should you have any other access-related questions/concerns. 

Thanks again
