### ISSUE TITLE
[Research] - Improve facility selection on the 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21683]
How might we improve the medical facility selection page on the 10-10CG?

## Background 
In the [usability studies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/1010cg-mvp) we've done on the 10-10CG, Caregivers have been confused around the Veteran facility selection page, which is used on the backend to determine where applications are processed.

## User Story
As a Caregiver/Veteran
I want to confidently select which VA facility the Veteran receives care at
So that Veterans and Caregivers can receive the best support.

## Acceptance Criteria
- Requirements are understood
- Researched with Veterans and Caregivers, if needed
- Content updated
- Prototype updated
- Front end/backend implementation tickets created

**Comment by hdjustice** [comment]
Closing ticket, new tickets will be created as part of the initiative re-start.
