### ISSUE TITLE
Phase 3 content release schedule

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21693]
## Detail 

Phase 2 ticket: #21158

Once CMS team determines phase 3 content release schedule and desired implementation date, record new schedule here and implement

**Comment by theodur** [comment]
[PR](https://github.com/department-of-veterans-affairs/devops/pull/8885) for implementing phase 3 of content release.

[New schedule](https://dsva.slack.com/archives/C01512KN35G/p1617390936238400?thread_ts=1616501984.036700&cid=C01512KN35G):
8AM EST / 5AM PST
9AM EST / 6AM PST
10AM EST / 7AM PST
11AM EST / 8AM PST
12PM EST / 9AM PST
1:45PM EST / 10:45AM PST
4PM EST / 1PM PST
5PM EST / 2PM PST

**Comment by theodur** [comment]
The PR for phase 3 has been merged, and the seed job was updated in Jenkins. New schedule changes are active now.
