### ISSUE TITLE
[Due on 02/25] Redirects in Housing based on parity work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2170]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15518*

**Goal**
After all parity work work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
- [x] Determine if all parity changes are complete/live and log tickets that track the approval status
- [x] Validate previously documented redirects and update as necessary
- [x] Create a new parity redirect issue in va.gov-team repo with the list of redirects and reference the original issue and the content approval ticket
- [x] Close the old issues in vets.gov-team repo and reference the new issue in va.gov-team repo
- [x] Communicate upcoming redirects to stakeholders prior to implementing
- [x] Assign out tickets to front-end or devops as appropriate
- [ ] Validate redirects in prod and update documentation when complete

Current URL  |  Redirect to
-- | --
www.benefits.va.gov/homeloans/veteran_borrowers.asp | /housing-assistance/home-loans/ 
www.benefits.va.gov/homeloans/purchasecashout.asp  | /housing-assistance/home-loans/loan-types/
www.benefits.va.gov/homeloans/purchaseco_buy_process.asp | /housing-assistance/home-loans/home-buying-process/
www.benefits.va.gov/homeloans/nadl.asp | /housing-assistance/home-loans/loan-types/native-american-direct-loan/
www.benefits.va.gov/homeloans/irrrl.asp  | /housing-assistance/home-loans/loan-types/interest-rate-reduction-loan/
www.benefits.va.gov/homeloans/purchaseco_eligibility.asp | /housing-assistance/home-loans/eligibility/
www.benefits.va.gov/HOMELOANS/purchaseco_certificate.asp  | /housing-assistance/home-loans/how-to-apply/
www.benefits.va.gov/HOMELOANS/resources_payments.asp | /housing-assistance/home-loans/trouble-making-payments/
www.benefits.va.gov/homeloans/adaptedhousing.asp  | /housing-assistance/disability-housing-grants/

**Comment by mnorthuis** [comment]
Housing parity review and approval by stakeholders is being tracked here: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16294

Parity work is not yet complete, this issue will be on hold until it is.

**Comment by Karak888** [comment]
@mnorthuis I will be making a request for these redirects to be vetted.

**Comment by Karak888** [comment]
@mnorthuis will follow up with you to ensure vetting is completed (or if I still need to still get redirect request into you.

**Comment by MickinSahni** [comment]
Won't commit to sprint 14 but if we receive go-ahead to implement. At that point, we can estimate/pull it into whatever sprint we're in at the time.

**Comment by lunascoop** [comment]
@mnorthuis Have these URLs been vetted? Thanks

**Comment by mnorthuis** [comment]
The URLs above are mapped correctly and vetted from an IA perspective.  

Your team will need to confirm that the new page has content parity with the old page - the ticket that was tracking that work appears to still be open - department-of-veterans-affairs/vets.gov-team#16294

**Comment by MickinSahni** [comment]
2020-02-13 PW Standup
- Next steps:
  - publish content changes
  - implement redirects

Note: "parity" -- legacy and new content exists and we're compare/contrasting. "rewrite" -- doesn't yet exist on new va.gov tech stack.

**Comment by AnneHurley** [comment]
@mnorthuis @peggygannon @lunascoop  I've reviewed the legacy pages against the current pages based on the URL redirecting above. I've also reviewed the legacy content parity ticket, which looks like we have completed per Peggy. 

I believe that if Peggy's signed off on the parity work, we should be good to proceed with the final redirects. Let me know if any questions. 
@MickinSahni  FYSA

**Comment by AnneHurley** [comment]
@mnorthuis  @lunascoop  I've reviewed the long copydecks Beth created and I believe all the feedback has been captured and incorporated. What else do we need to proceed with the actual redirects? thanks.

**Comment by lunascoop** [comment]
@AnneHurley I'll send out stakeholder comm today and schedule the redirect for next Tuesday, 2/25.

**Comment by MickinSahni** [comment]
2020-02-19 PW Standup
- send out comms to stakeholders and we're ready for redirects on 2/25

**Comment by MickinSahni** [comment]
2020-02-20 PW Standup
- Nick to open PR for this redirect on 2/25
- Nothing more needed from Anne

**Comment by ncksllvn** [comment]
PR open, https://github.com/department-of-veterans-affairs/vets-website/pull/11735

**Comment by ncksllvn** [comment]
PR merged!

**Comment by lunascoop** [comment]
Redirect implementation validated. Closing ticket and notifying stakeholders.
