### ISSUE TITLE
Copy manual review triggers from CircleCI to GHA

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21719]
## Details 

icon-check
sentry-check
eslint-check

## Definition of Done
- [ ] Determine whether these services need to be moved to GHA or whether they are no longer relevant
- [ ] Copy services to GHA as applicable
- [ ] Delete services from CircleCI

**Comment by U-DON** [comment]
- Initially tried to run the PR checks with the default GitHub token, which resulted in the `github-actions[bot]` commenting on the PR. It didn't have sufficient permissions to request a review from `frontend-review-group`, however.
- Decided to try using the token for `va-vfs-bot`, which is the bot that CircleCI uses.
- Got Ops' help to modify the `vets-website` AWS user's policy to be able to pull the token from Parameter Store.
- `va-vfs-bot` successfully commented on the PR and requested review from `frontend-review-group`.

**Comment by U-DON** [comment]
- Tested changes to trigger all three checks.
- Inadvertently staggered an icon change (due to the incorrect formatting the first time) after ESlint disable and Sentry changes. Observed that previous comments were not repeated.
