### ISSUE TITLE
[DISCOVERY] Investigate how we might use Cypress to test links

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#21715]
## Technical Task

To limit risk form links braking we need to do discover to see how we might be able to test links internal and external to ensure they are working as expected and have not broken creating unexpected behavior like directing users to the start of the form.

## Expected Behavior

We are able to use Cypress to e2e test internal and external links on VA.gov

## Acceptance Criteria

- [ ] We are able to e2e test internal links with Cypress
- [ ] We are able to e2e test external links with Cypress (target="_blank")

**Comment by LinnJS** [comment]
Resources on how to test href with target="_blank" [here](https://sqa.stackexchange.com/questions/44725/visiting-a-dynamic-link-that-opened-in-new-tab-in-cypress)

**Comment by tchrisdyer** [comment]
Hey @LinnJS just checking on this ticket. Should we keep this ticket open or were there next steps we need to take?
