### ISSUE TITLE
Right Rail Standardization

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#2172]
## User Story
As a user, I want an easily accessible side bar that gives me information so I can easily learn how to easily file an appeal, contact customer support if necessary, and check pending disabilities or claim status elsewhere on va.gov. 

## Goal
Construct the third and final piece of the migrated eBenefits rated disabilities page.  

## Notes
- Need more definition on what a right rail standard is
- Mockup to share potential layout might be a good idea
- Create a new scaffold that _is_ standardized?
- Better to add in later than develop without validation

## Considerations
- Claim Status Tool should be personalized once you are logged in, linking to the doorway should be fine.
- Pending feedback, this ticket may change.

## Acceptance Criteria
- [ ] Sidebar component is responsive.
- [ ] Link to claims status tool directs user to a page that has all relevant claims statuses and pending disabilities. (Need to verify this is the desired behavior). 
- [ ] Link to claims status tool fires an event that is recorded in GA. 

![Screen Shot 2019-10-01 at 1.15.53 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/5ae27420-90ce-4884-a741-5c6e417a0112)

![Screen Shot 2019-10-01 at 1.16.55 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/970ab48a-f7c7-4edd-a719-c5c3af2e8f0c)

**Comment by ncksllvn** [comment]
Hey all, chiming in here to express interest in this work! I'm not sure I follow the scope of this issue completely, but I think the baseline proposal is establishing the right sidebar that exists today on two applications - the Disability Rating Tool and Claims Status - as its own component in the design system, which I think is a fantastic idea. I consider the design system to be our first point of reference for putting together a new design, with its components serving as building blocks. I think it would be awesome for designers to see that this "Right Rail" component is available in their toolset during that process.

- [Screenshot of Your VA disability rating
](https://user-images.githubusercontent.com/1915775/68973056-45d3ab00-07bb-11ea-8670-10cdb6de9b9e.png)
- [Screenshot of Check your claim or appeal status](https://user-images.githubusercontent.com/1915775/68973089-5be16b80-07bb-11ea-9e25-5ccd9d49c36b.png)

There is clearly a lot in common between the two implementations - A sidebar positioned in the right column with a series of questions and answers. Maybe `FaqBar` or something similar would be a descriptive name, or maybe we'd rather focus on its position on screen as the `RightRail`.

@jaredcunha-usds I'd like your guidance on this potential design system component. It seems immediately actionable as far as building it into the design system and as a React component while we can define usability guidelines on design.va.gov in a later step. What do you think?

**Comment by ncksllvn** [comment]
Also, including @cohnjesse, the engineer that identified this component as common across two applications 🙂

**Comment by cohnjesse** [comment]
I filed a request with the design system team to get the ball rolling on this https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/160

**Comment by cohnjesse** [comment]
@sporeboy I wanted to reach out on this ticket, @1Copenut had mentioned that we should attach any research/ findings on the sidebar component so that the design council can have that stuff. More info here https://dsva.slack.com/archives/C7NJWUA8K/p1594398923024900

**Comment by sporeboy** [comment]
Regarding content in the RH column:

[ View Disabilities/View Dependents convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-usability-study/disabilities-dependents-usability-convo-guide.md#rated-disabilities)
[View Disabilities/View Dependents summary] (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-usability-study/disabilities-dependents-usability-summary.md#tools-page-layout)
[View Disabilities/View Dependents readout PDF](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-usability-study/disabilities-dependents-usability-readout.pdf)

We will be conducting usability testing on the View Payment History feature in the coming sprints. Additionally, the VA Debt Letters feature being developed by BAM2(?) has a RH column and will be tested. We were originally pointed to the Claim Status Tool (BAM1?) as a model; I can't find their research.
