### ISSUE TITLE
Copy linting from CircleCI to GHA

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21722]
## Details 

lint 

## Definition of Done
- [ ] Determine whether these services need to be moved to GHA or whether they are no longer relevant
- [ ] Copy services to GHA as applicable
- [ ] Delete services from CircleCI

**Comment by U-DON** [comment]
Added linting in department-of-veterans-affairs/vets-website#16516. 
- Seems to yield a lot of failures for presumably existing lint errors (~100).
- The sheer number of errors causes the summary publishing action to to take an excessively long time (~20 minutes).
- Investigating why these errors don't occur in our current pipelines.

**Comment by U-DON** [comment]
- Modified the linting step to output a JSON file and used a different action to produce a summary from that file.
- Seems to be much more efficient than using the action that uses JUnit to create that summary (only took a second).

**Comment by U-DON** [comment]
- Linting seems to work as expected in the `circleci-to-gha` branch.
- Confirmed that it reports errors by adding a `console.log` to a file without disabling linting; observed the failure in the linting step and its summary.
