### ISSUE TITLE
Copy unit tests from CircleCI to GHA

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21721]
## Details 

unit-test

## Definition of Done
- [ ] Determine whether these services need to be moved to GHA or whether they are no longer relevant
- [ ] Copy services to GHA as applicable
- [ ] Delete services from CircleCI

**Comment by U-DON** [comment]
I've copied these to a GitHub Actions workflow in department-of-veterans-affairs/vets-website#16516. The job will also publish a summary of failed tests.
