### ISSUE TITLE
Copy build and build-e2e from CircleCI to GHA

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21723]
## Details 

build
build-e2e

## Definition of Done
- [ ] Determine whether these services need to be moved to GHA or whether they are no longer relevant
- [ ] Copy services to GHA as applicable
- [ ] Delete services from CircleCI

**Comment by U-DON** [comment]
Done in the `circleci-to-gha` branch.
