### ISSUE TITLE
[FE] Direct deposit for edu: Wrap updated content in a react widget so it will show conditionally throughout phased launch

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21725]
## Background

[Slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1614971827221400)

**Note: This needs to be done as early in the sprint as possible so we can launch to 10% in the same sprint**.

[These are the proposed changes to the direct deposit content page](https://xd.adobe.com/view/532272b2-b423-4e1b-a8c6-d1a583da3d37-0671/screen/72860e86-bed9-4e10-8794-223ebb03794f/). The only actual change is the section starting "How can I change my VA direct deposit information online?", as the other sections are staying the same. We need to wrap the "How can I change my VA direct deposit information online?" in a react widget so we can conditionally tie it to our phased launch. This way, VA.gov users who have access to direct deposit for edu in production will see the new content, and those who do not yet will still see the old content that directs them to eBenefits.

@kelsonic and @ncksllvn would be the best people to consult with on how to do this. Looks like they've already provided some guidance in Slack.

Please work with @lunascoop to get the widget into the CMS.

## Tasks

- [x] Wrap "How can I change my VA direct deposit information online?" in a react widget so we can conditionally tie it to our phased launch
- [ ] Make sure the react widget makes it into the CMS/Drupal

**Comment by lunascoop** [comment]
The react widget has been added and the updated page is live: https://www.va.gov/change-direct-deposit/

**Comment by Samara-Strauss** [comment]
Great, thank you so much, @lunascoop!

**Comment by Samara-Strauss** [comment]
@erikphansen I'm gonna close this. Feel free to reopen if necessary.

**Comment by Samara-Strauss** [comment]
LOOKS GREAT! Consider it validated.

We can close this, but @ajakabcin, you should still check this out since you'll normally be the point person for validating work!

**Comment by Samara-Strauss** [comment]
> And if you'd like, I can turn it on for your own personal prod account so you can see how it works when you are signed out (old content) vs. signed in as a user with access to the feature (new content).

@erikphansen will you add me on prod? Samara.Strauss@va.gov

**Comment by erikphansen** [comment]
@Samara-Strauss Done. Give it a shot.
