### ISSUE TITLE
PTSD - Create Summary Document

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21728]
## Issue Description
Summarize PTSD research so that we can share it with stakeholders.

---
## Tasks
- [x] Condense data PTSD research (Part 1) presentation into 1-2 document outlining findings and recommendations.

## Acceptance Criteria
- [x] _Topline summary and a slide deck with the full Research Findings_
---

**Comment by chrvalla** [comment]
This research, including a slide deck with all the Research Findings, has been executed and completed. 
All the research can be found here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/nov-2020
