### ISSUE TITLE
Copy e2e tests from Circle to GHA

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21724]
## Details 

e2e-test

## Definition of Done
- [ ] Determine whether these services need to be moved to GHA or whether they are no longer relevant
- [ ] Copy services to GHA as applicable
- [ ] Delete services from CircleCI

**Comment by meganhkelley** [comment]
Duplicative of Testing Tools team ticket, will link and close

**Comment by U-DON** [comment]
Closing in favor of #22884.
