### ISSUE TITLE
Make helper for testing that API calls are made or not made

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#21730]
Code [like this](https://github.com/department-of-veterans-affairs/vets-website/blob/f1159979b2395bdca0b543be8c37339ce898fdd9/src/applications/personalization/dashboard-2/components/apply-for-benefits/ApplyForBenefits.unit.spec.jsx#L176-L193) is repeated in a few tests:
```js
await wait(1)
const fetchCalls = global.fetch.getCalls()
// make sure we are fetching DD4EDU info
expect(
  fetchCalls.some((call) => {
    return call.args[0].includes('v0/profile/ch33_bank_accounts')
  }),
).to.be.true
// make sure we are fetching ESR data
expect(
  fetchCalls.some((call) => {
    return call.args[0].includes(
      'v0/health_care_applications/enrollment_status',
    )
  }),
).to.be.true
```

**Recommendation:** We should make a helper function we can use in tests to make things a little more readable. Maybe something like `shouldCallApi('v0/health_care_applications/enrollment_status')` and also `shouldNotCallApi('v0/messaging/health/folders/0')`

## Tasks
- [ ] Review code and recommendation outlined above
- [ ] If determined to be relevant and necessary proceed with recommendation

**Comment by ajakabcin** [comment]
Closing - referenced code has been deprecated
