### ISSUE TITLE
After errors show on direct deposit edit screen, editing scrolls top field (routing) off screen while trying to type (iOS)

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#21740]
## What happened?
With an error showing in the routing number field, actually typing in it causes the field to scroll up off screen.

I also caused all errors to appear on an iPhone with the default or near default text size showing and when I went to enter into the top field on the page (Routing Number), that field scrolls off the page out of sight when the user is editing that field.  See the screen shots attached. 

## Specs:
- Device: iPhone XR

## Steps to Reproduce
- Navigate to Direct Deposit edit page.
- Tap 'Save' without filling in any fields to cause all field errors to appear.
- Tap into Routing Number field to edit.
- Notice that it scrolls all the way off the page as the keyboard appears.

## Desired behavior
Field remains visible to user while editing.

## Acceptance Criteria
Field remains visible to user while editing.

## Bug Severity
- 3 - Medium 

## Linked to Story
Linked to the bug I was testing:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21397

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/760759d2-3616-47b1-b91b-626c9f462d53)

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/58200a76-ab3f-4d7c-8879-36518d5cda87)

**Comment by bessgreen** [comment]
Update: this issue isn't specific to field errors. On iOS, the same scroll behavior seemingly occurs anytime you tap into a field on the Edit Address form.

**Comment by digitalken** [comment]
PASS 4/1/2021 - Looks good on Direct Deposit form and address form.  Closing.
