### ISSUE TITLE
Additional dataLayer attributes for SideNav

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#21748]
## Description

Add additional dataLayer attributes to SideNav links.

Notes from Michael's discovery re: sidenav and CTA hub links:

Clicking on these links causes a full page refresh, so the `dataLayer` variable is re-set each time.

e.g.

```html
 <a onClick="recordEvent({ event: 'cta-hub-link-click' });"
  href="/health-care/refill-track-prescriptions/"
  class="vads-u-height--full vads-u-width--full">
    <i
    class=" fa fa-prescription-bottle vads-facility-hub-cta-circle">&nbsp;</i>
      <span class="vads-facility-hub-cta-label">Refill and track your prescriptions
        <i class="fa fa-chevron-right vads-facility-hub-cta-arrow">&nbsp;</i>
      </span>
    </a>
```
## Acceptance Criteria

- 'nav-sidenav' _consistently populate for side navs_
- 'sidenav-click-action': "click-through"
- 'sidenav-click-label': _populate according to sidenav clicked on_
- 'sidenav-click-level': _number representing the indent level of the navigation level clicked on_
- 'sidenav-parent-label': _label of next 1-level higher parent, undefined if is parent_
- 'sidenav-accordion-header': _label of the collapsible accordion header_
- 'sidenav-section-title': _h4 in design system docs_

## Notes

• Please populate `undefined` for 'sidenav-accordion-header' since those aren't present here
• All clicks here can populate 'sidenav-click-action' with 'click-thru' since there's no accordions here
• Please populate _undefined_ for 'sidenav-section-title'
• As an example, populate 'sidenav-parent-label' with 'Work with us' when "Jobs and careers", "Internships and fellowships", and/or "Volunteer or donate" is clicked

**Comment by mpelzsherman** [comment]
For React-based sidenav components, we will need to modify the `trackEvents` [function](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/side-nav/components/SideNav.js#L42) to add the new params requested.

**Comment by mmiddaugh** [comment]
no longer needed
