### ISSUE TITLE
Access for Ahmed Ahmed

### ISSUE THREAD

**Issue by aahmed-va** [department-of-veterans-affairs/va.gov-team#21746]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee
- Please provide your name.
   > Ahmed Ahmed
- Please Provide your email.
   > ahmed.ahmed@thoughtworks.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @department-of-veterans-affairs/thoughtworks
Role: Developer
Company: ThoughtWorks
I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana / Sentry so we can

Modify / update Jenkins job configs
Kick off Jenkins jobs
Review Prometheus data, some of which is imported into the scorecard
Review Grafana data for the scorecard
Review logs in different environments to facilitate testing along the path to production

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCgA96RAVv+FMqUUcVrNcf9BatN3beZBJbYntz4Lh+JlfPHn2luBCMSty/lBjRZnNcPPCOngHHBmThogdO5ZYSCFGLF9BcyJwaermIKyaE7DzucOTzCoxyGiWsrrVRHzAf+vsVKmCzMM7mJPynh0skJWNuynufsv+vqg+8Mm/7u4wuKuuBls4SGVhCMxsHUCNHCHTCw1RSBw3w55DFIkqSd/OxaePA3fuJEu9s8Dyfm+sZae7PowhIlBoFCLuHEwgSvmrNjw8YhUq7kjPQ3S/c9GdAec2MOQUB1p2dqVDfkpCowfhCtm2jBuDSFJeYsaHnBpWMVEtTPKFny6CpHGTeosTtpPRNq9dElhjWFweOfb5s0EsCQvnkbS5Qx1CPpVNDUhspySGDke8heNOdna0J9gGy5Ki56uktjhzZn7nY/L3B/F29jN17ftu7EyTTYHIzPEaW/lV7SMVMggSeDa/Xc+K3zcAj8pGj9830yM7akL4XaM7JyoZqPzQiUUjxqzbs= ahmedahmed@Ahmeds-MBP.routerlogin.net
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
