### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-team#21745]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address: **cindy.merrill@adhocteam.us** and **Cynthia.Merrill@va.gov**
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [**X** ] Google Analytics
- [**X** ] Domo
_Please list any additional requirements, if any._

## Date Required
_Please share the date you require access._ **As soon as is reasonable, preferably by Monday Mar 22** 

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._ **Public Websites**

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @cindymerrill , 

Your Google Analytics & DOMO account access has been provisioned through your adhocteam.us email. You should have received invites to your inbox for both. 

We will close this GH issue but please feel free to reopen if needed. 

Thanks so much

**Comment by cindymerrill** [comment]
I would like to request training in Google Analytics and DOMO, which I was told was available by my Product Manager.
