### ISSUE TITLE
Analytics Implementation - STEM Automated Denial

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#21747]
# Google Analytics Implementation 22-10203: Rogers STEM Scholarship - Automated Denial

## Description
- Is this request for Google Analytics implementation or QA?
    - Google Analytics Implementation

- Who is this request for?

    - Booz Allen Team: @amyknox @dneel-bah 
    - 
 
- What team/project is this work for?

    - Booz Allen / VA Education Service, 22-10203 STEM Automated Decision 

    
- Provide the Domain where Google Analytics needs to be implemented
 
   - www.staging.va.gov -> www.va.gov
    
    - No PII is passed in URL or title tag

- Please provide any upcoming deadlines or important milestones
    
    - Limited production rollout to begin 3/19/21

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:*  
    
    - Denied applicant is sent an email with URL directing back to Claims Status Tool: https://staging.va.gov/track-claims/your-stem-claims/8468/status (Image 1)
    - Claims tool has card with Denied status & View details button (Image 2)
    - Status details page has information on reason for denial and various links for more info and support (Image 3)

    
**Image 1**
![image](https://user-images.githubusercontent.com/41081945/111699085-0b927780-880e-11eb-8729-25ffff7f0f13.png)

**Image 2**
![image](https://user-images.githubusercontent.com/41081945/111698345-1a2c5f00-880d-11eb-911e-70f5efad78b5.png)

**Image 3**
![image](https://user-images.githubusercontent.com/41081945/111698844-b35b7580-880d-11eb-9762-f7c0470a0bc7.png)

 - *Other User Interactions*: Details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior.
    
    - How many emails are delivered
    - How many / % that click through & arrive on the Claims Tool landing page
    - How many authenticate
    - How many click through on View details button
    - Clicks on Appeal/Review forms, More resources, Right sidebar

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Test user table here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv).  Test user 220 has several denied applications

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - Same as above

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by jonwehausen** [comment]
Hi @amyknox , 

Thank you very much for your request, we appreciate your thoroughly completing our request template and providing screenshots. 

For initial context, I wasn't able to access any existing denied application claims using `user+220` so the items you see below were  based mostly on your screenshots. I did also try a few other test users with no luck, if you could provide a couple more than allows us to see the full experience we would greatly appreciate it. 

Please find the data layer specification for the items you identified below: 

### Data Layer Specification 
| Description of Interaction + Tracking Component | Data Layer Specification | Dev Notes 
| -- | -- | -- |
_Clicks on right "Need Help" sidebar links_ <br><br> ![image](https://user-images.githubusercontent.com/48527022/112315508-96e19200-8c80-11eb-9797-08bcc2302144.png) | `'event': 'nav-sidebar-right-rail-click',`<br>`'sidebar-right-rail-header': 'Need help?' //populate with underlined heading`
_Appeal / Higher Level Review form downloads_  <br> <br> ![image](https://user-images.githubusercontent.com/48527022/112316536-93023f80-8c81-11eb-8dd8-084ac7a45265.png) | N/A | • **Assuming these are PDF downloads, we have this globally tracked and no data layer implementation needed**
_Clicks on links within "More Resources about VA benefits" links_ <br><br> ![image](https://user-images.githubusercontent.com/48527022/112316900-e70d2400-8c81-11eb-9033-5cd530f864f2.png) | `'event': nav-linkslist'`<br> `'links-list-section-header': 'More resources about VA benefits' //dynamically populate with value of links list section`<br>`'links-list-header': //dynamically populate with text of header clicked, i.e 'Edith Nurse Rogers STEM Scholarship', 'Find a VA Form', 'GI Bill Comparison Tool'` | 
_Click throughs on View details button_ | `'event': 'cta-button-click' //consistently populate for ALL types of button clicks`<br>`'button-type': //dynamically populate with button type, i.e 'primary', 'secondary', 'default'`<br>`'button-click-label': //dynamically populate with text of button`<br>`'button-background-color': //dynamically populate with the background color of the button` | • ⚠️ _These should be tracked via our globalized button listener, we will confirm when page is testable, if not spec to implement has been provided_



### Remaining Tracking Components
| Description of Metric | Questions/Recommendation/Notes
| -- | -- | 
_How many emails are delivered_ | • How soon after application completion are claims status emails typically sent? • Is it completely up to govdelivery for when that email goes out? 
_How many / % that click through & arrive on the Claims Tool landing page_ | **To capture this most optimally, we would recommend to embed UTM parameters within the URL within the emails linking back to the claims tool landing page -- a full URL would look like:** `https://www.va.gov/track-claims/your-stem-claims/8468/status?utm_source=govdelivery&utm_medium=email&utm_campaign=stem_scholarship_decision` <br> **You could also condense that entire UTM-contained URL in a URL shortener if desired**

**Comment by jonwehausen** [comment]
Shifting this ticket to Stand By while data layer is implemented 

### Next Steps for me
- Add event taxonomy for `nav-sidebar-right-rail-click` in GTM

cc: @laurensimpson14 @bsmartin-ep @joanneesteban

**Comment by amyknox** [comment]
Jon – double check user 220.  There are multiple denied STEM claims for that user.

Link to claims status tool in staging: https://staging.va.gov/track-claims/your-stem-claims/8512/status

You can find log-in info for user 220 here:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv


Amy Knox
Email: ***@***.******@***.***>
Office: 240.547.1733

From: jonwehausen ***@***.***>
Sent: Wednesday, March 24, 2021 9:56 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Knox, Amy [USA] ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [department-of-veterans-affairs/va.gov-team] Analytics Implementation - STEM Automated Denial (#21747)


Hi @amyknox<https://urldefense.com/v3/__https:/github.com/amyknox__;!!May37g!eQfaFq9eVRMIIjS6ayFRfT5CVSSRskZNfFwNvEb_kCt6rRKUpgNLDwbM_vITuw$> ,

Thank you very much for your request, we appreciate your thoroughly completing our request template and providing screenshots.

For initial context, I wasn't able to access any existing denied application claims using user+220 so the items you see below were based mostly on your screenshots. I did also try a few other test users with no luck, if you could provide a couple more than allows us to see the full experience we would greatly appreciate it.

Please find the data layer specification for the items you identified below:

Data Layer Specification
Description of Interaction + Tracking Component
Data Layer Specification
Dev Notes
Clicks on right "Need Help" sidebar links

[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48527022/112315508-96e19200-8c80-11eb-9797-08bcc2302144.png__;!!May37g!eQfaFq9eVRMIIjS6ayFRfT5CVSSRskZNfFwNvEb_kCt6rRKUpgNLDwY1J0PjCA$>
'event': 'nav-sidebar-right-rail-click',
'sidebar-right-rail-header': 'Need help?' //populate with underlined heading
Appeal / Higher Level Review form downloads

[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48527022/112316536-93023f80-8c81-11eb-8dd8-084ac7a45265.png__;!!May37g!eQfaFq9eVRMIIjS6ayFRfT5CVSSRskZNfFwNvEb_kCt6rRKUpgNLDwaD8qV2TA$>
N/A
• Assuming these are PDF downloads, we have this globally tracked and no data layer implementation needed
Clicks on links within "More Resources about VA benefits" links

[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/48527022/112316900-e70d2400-8c81-11eb-9033-5cd530f864f2.png__;!!May37g!eQfaFq9eVRMIIjS6ayFRfT5CVSSRskZNfFwNvEb_kCt6rRKUpgNLDwbQ2nKZLQ$>
'event': nav-linkslist'
'links-list-section-header': 'More resources about VA benefits' //dynamically populate with value of links list section
'links-list-header': //dynamically populate with text of header clicked, i.e 'Edith Nurse Rogers STEM Scholarship', 'Find a VA Form', 'GI Bill Comparison Tool'
Click throughs on View details button
'event': 'cta-button-click' //consistently populate for ALL types of button clicks
'button-type': //dynamically populate with button type, i.e 'primary', 'secondary', 'default'
'button-click-label': //dynamically populate with text of button
'button-background-color': //dynamically populate with the background color of the button
• ⚠️ These should be tracked via our globalized button listener, we will confirm when page is testable, if not spec to implement has been provided
Remaining Tracking Components
Description of Metric
Questions/Recommendation/Notes
How many emails are delivered
• How soon after application completion are claims status emails typically sent? • Is it completely up to govdelivery for when that email goes out?
How many / % that click through & arrive on the Claims Tool landing page
To capture this most optimally, we would recommend to embed UTM parameters within the URL within the emails linking back to the claims tool landing page -- a full URL would look like: https://www.va.gov/track-claims/your-stem-claims/8468/status?utm_source=govdelivery&utm_medium=email&utm_campaign=stem_scholarship_decision<https://urldefense.com/v3/__https:/www.va.gov/track-claims/your-stem-claims/8468/status?utm_source=govdelivery&utm_medium=email&utm_campaign=stem_scholarship_decision__;!!May37g!eQfaFq9eVRMIIjS6ayFRfT5CVSSRskZNfFwNvEb_kCt6rRKUpgNLDwZWLjtFRA$>
You could also condense that entire UTM-contained URL in a URL shortener if desired

**Comment by amyknox** [comment]
Just verified 220 has denied STEM applications.  Yep - 4 of them. 

![image](https://user-images.githubusercontent.com/41081945/113179639-d75f8380-921d-11eb-8058-6971c49b6af4.png)

**Comment by jonwehausen** [comment]
Hi @amyknox , 

Thanks for your confirmation here. I can confirm I see `user+200` in fact has denied claims for testing. 

I can also confirm our global tracking on PDF download is in-fact capturing here. You can see examples of these events within our non-prod property [**here**](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22%5EPDF%20Downloaded.*%22,0%5D,%5B0,%22analytics.pagePath%22,%22RE%22,%22.*~2Ftrack-claims~2Fyour-stem-claims~2F.*%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath).

We will be on standby for the remainder of the DL to be implemented.

**Comment by dneel-bah** [comment]
@jonwehausen Were you also able to confirm that the global button listener picked up the items mentioned for "Click throughs on View details button"?  Or will we need to add that tracking after all?

**Comment by amyknox** [comment]
@jonwehausen - double checking the requirements. The right sidebar contents may be moved to the bottom of the page in the not too distant future.  My understanding is there's a motion afoot to deprecate the right sidebar across the entire site.  Curious to get your thoughts on how to best code those links so any shifts in usage can be tracked.  

Does it make sense to maintain the 'nav-sidebar-right-rail-click' implementation or should we use something more generic?

**Comment by jonwehausen** [comment]
### Update

@dneel-bah 
- Currently unable to validate our globalized button tracking with backend appearing to be down 

![image](https://user-images.githubusercontent.com/48527022/114772834-48358e00-9d3c-11eb-8675-b04a4db4a35f.png)

-------------------------------------------------------------

@amyknox , 

Thanks for bringing this to my attention -- and yes I agree we should make the taxonomy for generic with that information. 

Since the sidebar may get moved to the bottom of the page, and from what I can see on the `vets-website` side, this looks to be an extension of `<AskVAQuestions` -- let's refactor the event taxonomy to be 

```javascript
  'event': 'nav-ask-va-questions-link-click', 
  'ask-va-questions-header': 'Need help'
```

**Comment by dneel-bah** [comment]
> ### Update
> @dneel-bah
> 
> * Currently unable to validate our globalized button tracking with backend appearing to be down
> 
> ![image](https://user-images.githubusercontent.com/48527022/114772834-48358e00-9d3c-11eb-8675-b04a4db4a35f.png)
> 
> That said, based on what I see [here](https://github.com/department-of-veterans-affairs/vets-website/blob/fe8220ab4a97dcc082d992b01db16dd5ddce7eaf/src/applications/claims-status/components/StemClaimListItem.jsx#L33) it looks as though these are action links which would not be captured by our button analytics. Were these in fact converted to action links over buttons?
> 
> @amyknox ,
> 
> Thanks for bringing this to my attention -- and yes I agree we should make the taxonomy for generic with that information.
> 
> Since the sidebar may get moved to the bottom of the page, and from what I can see on the `vets-website` side, this looks to be an extension of `<AskVAQuestions` -- let's refactor the event taxonomy to be
> 
> ```js
>   'event': 'nav-ask-va-questions-link-click', 
>   'ask-va-questions-header': 'Need help'
> ```

@jonwehausen 

Yes, the buttons were converted to action links based on feedback from one of the DEPO checkpoints.  Since the links aren't handled by the global handler, should we use the event posted above, or are tweaks necessary?

**Comment by jonwehausen** [comment]
Hi @dneel-bah , 

Thanks so much for this update. 

Per the change from buttons to action links, we would like to pivot to the following data layer implementation: 

```javascript
'event': 'cta-action-link-click', 
'action-link-type': 'primary', // or 'secondary', 'reverse' --- i.e click class of 'vads-c-action-link--blue' = 'secondary' ... based on name of action link button used from css class
'action-link-click-label': //click label for action link
'action-link-icon-color': //rgb code of action link arrow icon color
```

**I have updated both of our data layer taxonomy adjustment within the original [DL specification comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21747#issuecomment-805842488) as well**

cc: @bsmartin-ep As he is starting the work to standardize action links over the coming days

**Comment by jonwehausen** [comment]
@dneel-bah 

Per my last note -- your team can hold off implementing this specification as @bsmartin-ep is going to do the work to catch these site-wide, so as not to risk double firing of events, your team can hold off and we can validate when Brian has completed the global listener work this sprint.

**Comment by sonntag-adam** [comment]
@jonwehausen @joanneesteban this is in staging ready for review.

**Comment by jonwehausen** [comment]
## QA Testing 

@sonntag-adam Please see test results below

| Description of Interaction | Data Layer | Data Layer Test Status | Test Notes
| -- | -- | -- | -- | 
Click on a Need Help? link on the right rail nav | ![image](https://user-images.githubusercontent.com/48527022/116430862-39a7a600-a815-11eb-9cee-511bdf65b803.png) | ✔️ **PASS** | N/A
Clicks within "More resources about VA benefits | ![image](https://user-images.githubusercontent.com/48527022/116431366-b76bb180-a815-11eb-8dc3-7a1920846306.png) | ⚠️ **DOES NOT PASS** | @sonntag-adam We will want to correct `links-list-section-header` to be 'More resources about VA benefits'
Click on "Download VA Form 20-0995" | N/A | ✔️ **PASS** | • Confirmed universal PDF tag is firing here with no datalayer changes necessary ![image](https://user-images.githubusercontent.com/48527022/116431819-1f21fc80-a816-11eb-8af1-4bd8a7c64369.png)

**Comment by jonwehausen** [comment]
@sonntag-adam One other update here (and I apologize in advance for the coordination on my part here). Unfortunately our team was only able to deploy our global action link tracking to the static pages at this time. 

That said if we could have the **`cta-action-link-click`** specification inserted here, that would be very much appreciated. 

If there's additional metadata you all would like to pass with these events: such as the title, status of the claim, and/or submitted on date, please see this full specification: 

```javascript
'event': 'cta-action-link-click', 
'action-link-type': 'primary', // or 'secondary', 'reverse' --- i.e click class of 'vads-c-action-link--blue' = 'secondary' ... based on name of action link button used from css class
'action-link-click-label': //click label for action link, 'View details'
'action-link-icon-color': //name of color from class, i.e 'blue'
'claim-type': //'Dependency', 'STEM Scholarship'
'claim-last-updated-date': //date claim was last updated on
'claim-submitted-date': //date claim was submitted on
'claim-status': //i.e 'Denied', 'Claim received'
```

Thanks and please feel free to reach out with any questions you may have.

**Comment by jonwehausen** [comment]
@bsmartin-ep @laurensimpson14 Please see this GTM workspace as this is now ready for QA once @sonntag-adam's changes have been made: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000514

**Comment by joanneesteban** [comment]
@sonntag-adam @amyknox Hello! The team is checking in on this to see if it's ready to be tested.

**Comment by dneel-bah** [comment]
> @sonntag-adam @amyknox Hello! The team is checking in on this to see if it's ready to be tested.

@joanneesteban The failure and additional request fell through the cracks.  We have captured the failure as a defect and the new request as a story.  They are both in our backlog and will be worked as we have availability.

**Comment by sonntag-adam** [comment]
@joanneesteban this is now in staging ready for review.

**Comment by laurensimpson14** [comment]
@sonntag-adam, @dneel-bah, & @amyknox, 

It looks like there are two items remaining on this ticket to be QA'd (please correct me if I'm wrong!). I've QA'd them below. 

| Description of Interaction | Screenshot of Interaction |Data Layer | Data Layer Test Status | Test Notes
| -- | -- | -- | -- | -- |
Clicks within `More resources about VA benefits` | ![image](https://user-images.githubusercontent.com/80417436/129585758-37668ae6-3bd9-4a50-8f47-8cece9b395ac.png)| ![image](https://user-images.githubusercontent.com/80417436/129585939-53d4f9d1-e4d0-444b-94c2-65137158edbf.png) ![image](https://user-images.githubusercontent.com/80417436/129586212-bac340a8-7fa5-4b1d-a8d8-c48450118b66.png) | 🟡 Passing, although please see the notes to confirm this is tracking correctly | I see that earlier in this ticket Jon wanted to collect these clicks as `More resources about VA benefits` rather than `links-list-section-header`. However, I don't think that this change is necessary. `links-list-section-header` is one of our standard event naming conventions. As long as there isn't a reason that I'm unaware of to change this, then this is tracking correctly and good to go.
Click on `View Details` | ![image](https://user-images.githubusercontent.com/80417436/129583737-35eb1b18-688f-441a-9582-6bf8057d4e63.png)| ![image](https://user-images.githubusercontent.com/80417436/129584041-89adada4-c8b0-4079-a86a-0f557682e43c.png) | 🟡 Passing, although please see the notes to confirm this is tracking correctly | I've clicked on claims with different statuses using test user 220. These statuses include `Claim received`, `Denied`, `Preparation for notification`, `Initial review`, `Evidence gathering, review, and decision`, and `Closed`. The `Action Link CTA Click` only fires for the claims with a status of `Closed`. This is correctly tracking the additional dimensions of claim type, updated date, submitted date, and status (see screenshot). If the claim does not have a status of `Closed`, then clicking `View Details` does not fire the new `Action Link CTA Click` tag. Instead, it fires a `Claims View Details` tag that does not track the additional dimensions of claim type, updated date, submitted date, and status. Is this what was intended? If so, then this is tracking correctly.

**Comment by dneel-bah** [comment]
@laurensimpson14 

Regarding the first item, "Clicks within More resources about VA benefits", the tracker wasn't wired up correctly initially which resulted in Johns feedback.  If you have passed that we can consider it completed.

Regarding the second item, "Click on View Details", I believe that is expected behavior as well.  The STEM automated decision cards displayed will always have a status of closed at this point in time.  If you have passed that we can consider it completed as well.

Based on this understanding, can we close out this ticket?

**Comment by laurensimpson14** [comment]
Hi @dneel-bah Thank you for the additional background! Yes, based on that I'd say we are good to close out this ticket.
