### ISSUE TITLE
Access for Kenneth Santiago

### ISSUE THREAD

**Issue by ksantiagoBAH** [department-of-veterans-affairs/va.gov-team#21752]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Doris Lin (meichih.lin@va.gov)
- Please provide your name.
   > Kenneth Santiago
- Please Provide your email.
   > santiago_kenneth@bah.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > BAH Team supporting Education on VA.gov (Comparison Tool, etc)

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCl/Eb/6kcbZ5DHzWv2IQp6Dgb0qqYI2CeJJx6lOBTd0zfIyYU6zfp3FoOxhMNW3GDDhSzBudetu9K3fjDYJFrTZGB/TxqTfIqbqUXL+Tvc9103M/L5L1ppX7XdUEUo4XvrMEHG7Y8x+9J2YtANjiAaW4ZeUJyzIkuTRzQCn2icXfXYDlKKWu7F5DshMIGyAUtkT5SPPG9gnehOXoYRo4PZ8CQrxIK1IL845d8JP7fV4igKG0L2YCyRQxHlkVicoRGVXnBUaXUrM4f/JHHZR1uxmyvm7EBWR2eSrhJC6xL0qp1tcNslgZlfHFSvEBdfVICr29eWTiU9mDpo6ooeEW/R0IXOoNhWGsu+MiZJYRTvUQvaQv2DSiJqWNNUEqlfa0EtV8jUGI2VqsMLsvmfRusPL8D57AOer/Ew2dWF0hOume/318MS670jVVUmKnSb+NIf8D0NUsKcXOC5obyYDb6eEoQblKAswK8eUDox4qPMNxJns1K7JxPfbSaOK6ZUAbs= kennethsantiago@C02F31X7MD6V
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
  - Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting,
log file review and to apply changes to the running instances and services.

**Comment by ksantiagoBAH** [comment]
@department-of-veterans-affairs/vsp-operations Access for new hire

**Comment by oragame** [comment]
@Jeff-Hayter
Requesting AWS Access
User: @ksantiagoBAH 
COR: Doris Lin

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by desireeturner** [comment]
This can be closed.
