### ISSUE TITLE
Contact Center Review for VAOS - VAOS for Distribution

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21751]
# Request the Contact Center Review 

## Description
VA Online Scheduling - schedule and manage health appointments

### Launch Date
- Pilot (available to select sites) - ~~March 25, 2021~~ March 30, 2021
- Launch TBD

### Version Number
Version 03/18/2021

### Product Guide
~~https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/vaos-product-guide.pdf~~ (The updated file is large so having trouble uploading to folder. See attachment below.)

[VAOS-product-guide.pdf.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/6167922/VAOS-product-guide.pdf.zip)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Hi @laurenernest. Are you able to send me the original working file for this? I'm assuming it was done in Word.

**Comment by laurenernest** [comment]
Hi @starlow00! Here's the working file.

[VAOS-product-guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6173960/VAOS-product-guide.docx)

**Comment by starlow00** [comment]
Perfect, thanks @laurenernest

**Comment by starlow00** [comment]
Hi @laurenernest. Attached is my review draft. It looks good and the links in the Table of Contents work! I added references and links for the figures, which I'm thinking we'll want to add to our "best practices" list going forward.

If you can review and let me know the status within the next couple of days, I can get this to VEO in time for the pilot date. Thanks!

[VAOS-product-guide-ST-032221.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6185774/VAOS-product-guide-ST-032221.docx)

**Comment by laurenernest** [comment]
Thanks! Updated version attached for your review. I also updated the ticket with the new pilot date.
[vaos-product-guide-LE-032321.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6193583/vaos-product-guide-LE-032321.docx)

This latest version was just for the addition of the vaccine scheduling. I'll be doing a more thorough review (or overhaul) later. Do you have a styles template or guide that I should follow?

**Comment by starlow00** [comment]
Hi @laurenernest. Sounds good. The updates look good and ready for VEO, thank you! I moved the list of figures to the end.
I'll make sure VEO receives a copy.

[vaos-product-guide-032421.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6199172/vaos-product-guide-032421.docx)

As for style guide, beyond Chicago and Microsoft style, I use these in-house: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/documentation/style-guide and https://design.va.gov/content-style-guide/word-list

**Comment by starlow00** [comment]
@laurenernest, re. the pilot date, VEO is wondering if 3/30 is a limited release date, a general go-live date, etc. Please inform.

**Comment by laurenernest** [comment]
Very limited. Any facility interested must go through an onboarding with OVAC and OCTO.

**Comment by starlow00** [comment]
Great. Thanks, @laurenernest !
