### ISSUE TITLE
Truncate Strings For Any Lighthouse Character Limit

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#21757]
Recently, we had a problem where [Lighthouse was rejecting HLR submissions because names were too long](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/187c8ef97edd7be5d8612f22d6f792f967a8d272/Postmortems/2021-02-25%20HLR%20Spike%20in%20Failed%20Requests%20(partial%20launch).md).

Lighthouse has some very strict character limits on HLR fields due to the character limits in the [paper form](https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf).
We fixed the name problem by automatically truncating the name (we concluded that, although the name would be incorrect (if shortened), the Veteran would still be identifiable when considering all of the other included identifying information).

**Are there more character limits in the HLR or NOD schemas? How do we want to handle each one?**

(This can be a research ticket that spins off an implementation ticket, or just a single ticket. I envision an engineer starting this one and then pulling in Kevin or Christian.)

## Acceptance Criteria

- [ ] A gameplan for every character limit in the HLR & NOD schemas (even if that gameplan is simply "let it fail")
- [ ] Implement gameplans _or_ spin off a ticket(s) to do so (if necessary)
#### Notes

[The HLR schemas](https://github.com/department-of-veterans-affairs/vets-json-schema/tree/master/src/schemas) (those starting with `HLR-`)
[The NOD schemas](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/decision_review/schemas)

**Comment by annaswims** [comment]
running notes: 

# HLR-create-request-body

[ ] -  [emailAddressText](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/HLR-create-request-body/schema.json#L203)  "maxLength": 44 WAT?

**Comment by kevinstachura** [comment]
@annaswims saved me from this ticket. I was lost in the woods; it was a true Hansel ~and Gretel~ story.

She said she would do some tech digging (which we can see has already begun) and we decided if design changes are indeed necessary, we would discuss at that time.

**Comment by annaswims** [comment]
Found these bugs while working on this ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26714
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26715

**Comment by annaswims** [comment]
I'm partway through HLR schema review and all looks good.  I haven't started verifying NOD yet.

**Comment by annaswims** [comment]
I've update the schemas in vets-json-schema (lighthouse made some small changes)

https://github.com/department-of-veterans-affairs/vets-json-schema/pull/612

**Comment by annaswims** [comment]
new related issue for hlr v2 emails https://github.com/department-of-veterans-affairs/va.gov-team/issues/26984

**Comment by annaswims** [comment]
lighthouse will now allow for long but valid email addresses in NOD so I upped our limit too https://github.com/department-of-veterans-affairs/vets-api/pull/7363

**Comment by annaswims** [comment]
all character limit issues have been addressed
