### ISSUE TITLE
[BUG] Broken link is created by VAMC Past Events listing page when no past events exist in the CMS

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#21762]
## Problem description

If a VAMC region has no past events, the 'Past Events' link is still created and shown on [the page](https://www.va.gov/eastern-oklahoma-health-care/events/):

<img width="1039" alt="Screen Shot 2021-03-19 at 9 55 34 AM" src="https://user-images.githubusercontent.com/101649/111808119-4ee5f800-8899-11eb-8815-58de53df2e7a.png">

This generates a broken link error, because the past events page itself is not generated, and fails the build.

## How to reproduce

In the CMS, remove all past events for a given VAMC.

## Suggested resolution

The build process should be modified to either
- check to ensure that the Past Events link is only generated if there is a past events page, or
- always generate the past events page with placeholder text if no events are available

See [Slack thread ](https://dsva.slack.com/archives/CBU0KDSB1/p1616165909204100)

**Comment by mpelzsherman** [comment]
Per @davidconlon, we're going with option 1: " Past Events link is only generated if there is a past events page".
