### ISSUE TITLE
Helper text below disabled button is missing

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#21767]
## What happened?
Testing the story for the updated disabled button and found the colors to be better (passes contrast test) but the helper text below the button is missing.

## Specs:
- Device: iOS and Android

## Steps to Reproduce
- Logged in as user 366 and went to went to file request in a claim item.
- Scrolled down to "Ask for your Claim Decision
- Tapped View Details to reveal a page with a disabled Submit button.

## Desired behavior
Disabled button has help text explaining it is disabled.

## Acceptance Criteria
Disabled button has help text explaining it is disabled.

## Bug Severity
- 3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21191

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/9de98c35-93b8-4d33-bc4e-4051d4ecc2c9)

**Comment by digitalken** [comment]
@bessgreen - I read the story as applying to disabled buttons in general.  But I see now that only the one disabled button is called out for text.  Did we want to do that with all disabled buttons or was this just directed to the one button for joining the video?

**Comment by bessgreen** [comment]
@digitalken there is an in-progress ticket (#21448) to remove the disabled state from the **Ask for your claim decision** button: it will have a field error instead of a disabled state. 

As a result, the only large button that remains in the app which _also_ has a disabled state is the **Join Session** button. 

Since this is not a bug, this ticket can be closed.

**Comment by digitalken** [comment]
3/22/2021 - Closing.
