### ISSUE TITLE
New law COVID-19 mini-hub and KMI content updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21763]
## Issue Description

Collaborate on content updates to support new law.

Follow-up from conversation with Lauren, Chante, and Randi. I'm drafting some content in this doc that we can collaborate on to get new messaging up asap.

https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/ERwJ2UP1_FBNmCtfAqHSxk0BDRizuQjyfe4tbuZQttTiqg?e=WZcaPY

**Comment by RLHecht** [comment]
This work has already been completed. Closing.
