### ISSUE TITLE
New VAMC site content for sharing medical records

### ISSUE THREAD

**Issue by andrewlewandowski** [department-of-veterans-affairs/va.gov-team#2177]
We need new content for this section on the new VAMC website: https://www.va.gov/pittsburgh-health-care/medical-records-office/#share-your-records-with-provid

Due the the Mission Act, the rules around sharing medical records via VHIE have changed. The content can be drafted and published directly in Drupal.

**This needs to be published on Prod by October 11** (before Beta launch of VAMC Pittsburgh).

**Comment by jefflbrauer** [comment]
Added this to the runbook for tracking

**Comment by jenniferlee-dsva** [comment]
@Karak888 - I think Anne would be perfect for this one because she's already worked on a little bit of content related to VHIE and MISSION Act change. And most of the info and stakeholder approved language can be repurposed from here: https://www.va.gov/health-care/get-medical-records/ 

@andrewlewandowski - you said "in a couple weeks" on Slack msg. Could you provide more specific time frame, so Kara can better prioritize?

**Comment by jenniferlee-dsva** [comment]
@Karak888 - could you hold off on assigning? sorry for the reversal - but looked back at my old notes on this page and it may be a simple case of removing content and cross linking. Andy and I will circle back.

**Comment by andrewlewandowski** [comment]
I added Oct. 11 as a due date. :)

**Comment by jenniferlee-dsva** [comment]
Take a look and let's discuss. Couple things that just didn't seem right, and still not sure about the value of including the participating providers. 

Also, related - this page: http://preview-prod.vfs.va.gov/preview?nodeId=255

“Access your health records” should now change to match the page H1 – “Medical records office”; also teaser text about sharing doesn’t apply now.

I made this change for you but put it in “draft” state, so you can review first.

**Comment by jenniferlee-dsva** [comment]
@Karak888 - please assign Selina to work on a plain language content task for this ticket, with Anne's supervision/feedback. 

**Attached Word doc with specifics for Selina:** 
[pittsburgh-medical-records-office-faqs-100319](https://app.zenhub.com/files/133843125/bdefad26-1b1b-49f1-9b8a-6de06df2bd3a/download)

Task: Revise to make more plain language (as needed)—without changing meaning of the information--and in the new VA.gov content voice and tone, per the style guide. Please work with Anne Hurley. Jen will do final review.

**Comment by jenniferlee-dsva** [comment]
@andrewlewandowski - see attached Word doc. 
[pittsburgh-medical-records-office-faqs-100319-SC-AH-100919-jl.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3708523/pittsburgh-medical-records-office-faqs-100319-SC-AH-100919-jl.docx)

**Comment by Karak888** [comment]
moving to close this ticket per info provided.
