### ISSUE TITLE
Document FacilitiesMap hooks

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21776]
## Issue Description
The main Facility Locator component (src/applications/facility-locator/containers/FacilitiesMap.jsx) has several `useEffect` hooks. The purpose of each of these isn't always obvious.

This task will make FacilitiesMap code easier to understand. 

---
## Tasks
- [ ] Add comments explaining what each `useEffect` hook does.

## Acceptance Criteria
- [ ] FacilitiesMap hooks are well-documented and easier to understand.

**Comment by gescobardev** [comment]
Ready for review
https://github.com/department-of-veterans-affairs/vets-website/pull/17238
Still having issue with trying to link PR to issue. Will continue trying to play around with it.
