### ISSUE TITLE
Conditional Completion on the HCA

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21790]
## High Level User Story/ies
As a Veteran, I need to verify my Veteran status so I can easily complete the health care application. 

## Hypothesis or Bet
**If** _we verify Veteran status and make the finance questions optional_ **then** _we expect conversion rates on the HCA to increase_.

## OKR
**Objective**: Make it easier for Veterans to complete the health care application.
**Key Result**: Improve the conversion rate/

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ala-yna** [comment]
# 3/19 Meeting Notes

### First steps
- Research on the drop off points
### Next steps

If a Veteran has a SCD of 50% or higher, they don't need to provide financial information. 

-VA.gov profile section
- Frontend that interfaces with a bunch of different backend

- VA Profile (Vets360)
- Only address info + (working on) communication preferences
- We can integrate with whatever endpoints are available
- eBenefits did work with disability rating tool (Sabrina and Jason are managing the team now)
- We should be able to access it


Within VA.gov
- If you create an account, as long as you have verified your identity, whenever you go to a page that has personalized information (there are lots of them) 
- Does this person have information and the permission to show? If so, than any data will populate on each page 

- We might be able to do it from within VA.gov - and we might not have to go through VA Profile/Vets360


## Reminder functionality
- Can we send an email/text to remind Veterans to complete the application?
- Next steps: work with the VA Notify team
- As a Platform are we planning on implementing this functionality for all forms?
- Communication preferences are not yet in VA.gov Profile 
- There is functionality that allows Veterans to opt into health care reminders
- Starting to work on a project with Vets360 to store communication/reminder preferences
- Will start in Vets360 and then come into VA.gov profile
- They will send reminders and then you can opt out (default is opt in)
- Shane is the best person to provide more information
- There is no where in profile to indicate what you've opted into or out of 
- You don't really sign up for VA.gov - you use pre-exiting credentials (DS Logon or ID.me)


## Preferred Facilities
- In the VA.gov profile they're starting to work on pulling in preferred facility
- All in service of the VAOS tool
- Pull in full facility list from MPI and then allow them to select what facilities they actually go to
- It won't save back into MPI
- It will be used to help

**Comment by tchrisdyer** [comment]
Closing this ticket in favor of the duplicate ticket #27679
