### ISSUE TITLE
Access for Josh Arebalo

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-team#21815]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Josh Arebalo
- Please Provide your email.
   > josh.arebalo@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Help Desk - Help Desk Manager - Civic Actions

- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiq4U7eQvFUkruRVJ+M1Z49UwaJmilSJyzLASqmF4EYwdbBmEbZyQzDBw1vzCwnV2DWfwqJHjHFEM4XrobM7nkzAnzgpMO6oabUNloi11E2ROGmFEWdZnOJxesHaeTg4lfOkVdAv2ruaHu2uF/Odn+IOq01WW1/PhZsXFG30ywl/d9L7l5vfi4MQmGHPhlmIdWLMqa2VDu9NAUtfqSkEqQ/zSabtNnGzRGI7K76tv081KmSkaTRgrUPlfqLwElirG0DtTZxfX7MKUbUG7ihS3QpkMKqP2iqLQmgBx3G9YeH7eI6u7w2joWu1MQHlA0P+FkOnAnCiYmUAErLlTfv4yb josh.arebalo@civicactions.com

```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by joshworkscivicactions** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
