### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-team#21816]
Josh Arebalo requesting access per VFS-CMS Project Onboarding/Offboarding checklist.

**Comment by bsmartin-ep** [comment]
@joshworkscivicactions - GA access has been granted to your `@civicactions.com` email.

docs:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/navigating-google-analytics.md

Let me know if you have any questions.
