### ISSUE TITLE
10-10EZ application intro

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#21814]
## User story
As a Veteran who wants to apply for VA health care, I need to get the most critical information to help me start the application and understand what happens next.

## Issue Description
Initial content recommendations for application intro page to discuss with 10-10EZ team.

[Apply for VA health care intro page_recommendations_03.20.21](https://app.zenhub.com/files/133843125/c644d82f-7855-4155-bb35-f5f44595c740/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mlighdc and @ala-yna! Following up on my slack mention that I had some thoughts on the 10-10EZ intro page. I've been wanting to look at this page for a long while. And after reviewing/making recommendations on the new Financial Status Report (FSR) intro page, also had some thoughts from that that may be helpful here.

I was thinking that since the new vaccine act may lead to an increase in applications, it would be great to streamline this intro page a bit more sooner rather than later if possible. But, of course, don't want to mess up your team's process. So just let me know if/when you want to talk about these thoughts more. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss! I've been going over the "sign in to save time" component a review as part of the health care intro page. I wanted to check in on the content we created together way back for this and get your thoughts on potential changes to streamline. Let me know what's best - comments in ticket or having a call to go over. Thanks!

# Save time and save your work in progress

You can sign in to VA.gov before you start your application. Here's how signing in now helps you:

- We can fill in part of your information for you to save you time.

- You can save your work in progress. You'll have 60 days from when you start or make updates to come back and finish your application. 

**Note:** You can sign in after you start your application. But you'll lose any information you already filled in. 

[button] Sign in to start your application
[link] [Start your application without signing in](https://www.va.gov/health-care/apply/application/id-form)

**Comment by Samara-Strauss** [comment]
Hey @DanielleThierryUSDSVA! This looks great. One question:

> We can fill in part of your information for you to save you time

Should we be more specific about "part of your information" so people know what that means? Idk if pre-fill is always consistent, so if we can't be more specific there, no worries. This is great otherwise.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @Samara-Strauss! I'm not sure if prefill is always consistent either. But agree, it would be nice to at least give examples:  "part of your information (like your name, SSN, and address)". Who do you think might be able to tell us if there are at least a few elements that are always consistent for prefill?

**Comment by Samara-Strauss** [comment]
> Who do you think might be able to tell us if there are at least a few elements that are always consistent for prefill?

Not sure. Maybe the benefits and memorials team? Though I do think that it's a safe bet that things like name, SSN, and address are *supposed* to prefill. I think it's a matter of whether that information is on file or not (which, I would assume it should be if someone is LOA3 and therefore able to use prefill).

**Comment by mlighdc** [comment]
@LinnJS since you just finished working on the pre-fill bug, can you let us know what fields are typically pre-filled?

**Comment by ala-yna** [comment]
Here's what users see when they go to start the application after signing in:

<img width="372" alt="Screen Shot 2021-04-02 at 10 41 30 AM" src="https://user-images.githubusercontent.com/15709424/113425577-1fa6af00-93a0-11eb-938f-693f54377f0f.png">

Fields that _may_ be pre-filled:
- Name
- Date of birth
- SSN
- Gender
- Mailing and/or home address

**Comment by DanielleThierryUSDSVA** [comment]
@Samara-Strauss @ala-yna @mlighdc Thank you! Sounds like we should be good with listing a few examples then. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Closing this issue and moving work into our larger 10-10EZ content issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25350

**Comment by Dene-human** [comment]
Thank you very much @DanielleThierryUSDSVA The doc is well received. I'll prepare a packet with your copy and an example of the design for the SMEs. 

I'm preparing a working [content source of truth ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/10-10EZ-application-copy.md)and I will keep it updated as we continue making changes. We can close this ticket.

**Comment by mlighdc** [comment]
Thank you @Dene-human and @DanielleThierryUSDSVA !
