### ISSUE TITLE
Cheetah-Handle weekend slots on calendar

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21812]
## Description
As a Veteran, I would like to be able to schedule a vaccine appointment on a weekend if there's an open slot.

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag
- [ ] Show all days of the week (Sun-Sat) by default for all months

- [ ] Applies to direct book calendar only

- [ ] Request calendar does not show weekends

- [ ] DESIGN - All desktop, tablet, and mobile designs match the specs (copy is FPO) 
- Desktop
  - https://www.sketch.com/s/213ff953-c66b-48c1-8b1a-fd171aaba5ff/a/l1kx8yV#Inspector
  - https://www.sketch.com/s/213ff953-c66b-48c1-8b1a-fd171aaba5ff/a/09p1dyy#Inspector
- Tablet https://www.sketch.com/s/213ff953-c66b-48c1-8b1a-fd171aaba5ff/a/Axng934#Inspector
- Mobile https://www.sketch.com/s/213ff953-c66b-48c1-8b1a-fd171aaba5ff/a/agDxzoZ#Inspector
![21812 scope.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/c52ab61d-34d3-49c8-b3c8-356b69ba2637)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/design/cheetah-flow) is updated

---
**Original Description**

When direct booking clinics are set up with open slots on a weekend, they don't display in the calendar.

![image (9).png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/6612659b-4080-4b06-ad8b-12a43f687d89)

**VistA availability with the response body** 
`CHEYENNE VAMROC
                              COVID VACCINE CLIN1
                              MARCH  2021
 TIME  |8      |9      |10     |11     |12     |1      |2      |3      |4
 DATE  |       |       |       |       |       |       |       |       |
FR 19  [2 3 3 3|3 3 3 3|3 3 3 3|3 3 3 3]
00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T08:00:00.000+00:00","endDateTime":"2021-03-19T08:15:00.000+00:00","bookingStatus":"2","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T08:15:00.000+00:00","endDateTime":"2021-03-19T08:30:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T08:30:00.000+00:00","endDateTime":"2021-03-19T08:45:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T08:45:00.000+00:00","endDateTime":"2021-03-19T09:00:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T09:00:00.000+00:00","endDateTime":"2021-03-19T09:15:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T09:15:00.000+00:00","endDateTime":"2021-03-19T09:30:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T09:30:00.000+00:00","endDateTime":"2021-03-19T09:45:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T09:45:00.000+00:00","endDateTime":"2021-03-19T10:00:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T10:00:00.000+00:00","endDateTime":"2021-03-19T10:15:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T10:15:00.000+00:00","endDateTime":"2021-03-19T10:30:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T10:30:00.000+00:00","endDateTime":"2021-03-19T10:45:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T10:45:00.000+00:00","endDateTime":"2021-03-19T11:00:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T11:00:00.000+00:00","endDateTime":"2021-03-19T11:15:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T11:15:00.000+00:00","endDateTime":"2021-03-19T11:30:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T11:30:00.000+00:00","endDateTime":"2021-03-19T11:45:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-19T11:45:00.000+00:00","endDateTime":"2021-03-19T12:00:00.000+
                             CHEYENNE VAMROC
                              COVID VACCINE CLIN1
                              MARCH  2021
 TIME  |8      |9      |10     |11     |12     |1      |2      |3      |4
 DATE  |       |       |       |       |       |       |       |       |
SA 20  [1 1 1 1|1 1 1 1|1 1 1 1|1 1 1 1|1 1 1 1]
00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T08:00:00.000+00:00","endDateTime":"2021-03-20T08:15:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T08:15:00.000+00:00","endDateTime":"2021-03-20T08:30:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T08:30:00.000+00:00","endDateTime":"2021-03-20T08:45:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T08:45:00.000+00:00","endDateTime":"2021-03-20T09:00:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T09:00:00.000+00:00","endDateTime":"2021-03-20T09:15:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T09:15:00.000+00:00","endDateTime":"2021-03-20T09:30:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T09:30:00.000+00:00","endDateTime":"2021-03-20T09:45:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T09:45:00.000+00:00","endDateTime":"2021-03-20T10:00:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T10:00:00.000+00:00","endDateTime":"2021-03-20T10:15:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T10:15:00.000+00:00","endDateTime":"2021-03-20T10:30:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T10:30:00.000+00:00","endDateTime":"2021-03-20T10:45:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T10:45:00.000+00:00","endDateTime":"2021-03-20T11:00:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T11:00:00.000+00:00","endDateTime":"2021-03-20T11:15:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T11:15:00.000+00:00","endDateTime":"2021-03-20T11:30:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T11:30:00.000+00:00","endDateTime":"2021-03-20T11:45:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T11:45:00.000+00:00","endDateTime":"2021-03-20T12:00:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T12:00:00.000+00:00","endDateTime":"2021-03-20T12:15:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T12:15:00.000+00:00","endDateTime":"2021-03-20T12:30:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T12:30:00.000+00:00","endDateTime":"2021-03-20T12:45:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-20T12:45:00.000+00:00","endDateTime":"2021-03-20T13:00:00.000+00:00","bookingStatus":"1","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-21T08:00:00.000+00:00","endDateTime":"2021-03-21T08:15:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-21T08:15:00.000+00:00","endDateTime":"2021-03-21T08:30:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-21T08:30:00.000+00:00","endDateTime":"2021-03-21T08:45:00.000+00:00","bookingStatus":"3","remainingAllowedOverBookings":"0","availability":true},{"startDateTime":"2021-03-21T08:45:00.000+00:00","endDateTime":"2021-03-21T09:00:00.000+`

**Comment by laurenernest** [comment]
@jbalboni I'm unsure if this is a bug or as designed. Do we have it hardcoded in the FE to not display weekends?

@outerpress What should the calendar look like if 1) no weekend slots are available, 2) only one weekend day (Sat or Sun) has available slots, 3) both Sat and Sun have slots available?

**Comment by jbalboni** [comment]
@laurenernest Yeah, it was designed to not show weekends.

**Comment by outerpress** [comment]
@laurenernest here's the first draft showing a calendar that:
1. Can show weekend appts
2. Has a mix of weekend appts available

https://www.sketch.com/s/213ff953-c66b-48c1-8b1a-fd171aaba5ff/p/full-calendar-layouts

Ideally there would be a way to continue showing the current weekday calendar, and only show the full week if clinics are in some way configured for weekend appts.

**Comment by LanceGundersen** [comment]
@marcynadeau I just merged the PR

**Comment by marcynadeau** [comment]
tested and passed.
