### ISSUE TITLE
Analytics Implementation for Downloads on Legacy Sections

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#2182]
# Analytics Implementation or QA Request
I want to understand how PDF downloads are performing on legacy sections of the site, including:
- Content on https://va.gov/vaforms and MHV

This is also a follow up to the MHV training and request from the VSA Global UX team to track PDF downloads in #1828

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?

- Who is this request for?
     - Chip Harmon
   - Jennifer Lee
 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    - MHV and VSA Global UX Teams
  
    
- Provide the Domain where Google Analytics needs to be implemented
    - Legacy sections (Non-modernized Google Tag Manager container)
    ![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/e62f9bc6-14de-45e0-a78a-0304bf9c3dc1)

    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required

    - [Provide users here]

- Test Users to replicate the event

    - [Provide test users here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@jonwehausen Thanks for tackling this in the legacy container. For your visibility, I updated the acceptance criteria to include a screenshot of the naming convention in the legacy container. 

May you update the tag settings to match the ones in the screenshot?

Also, within the Legacy Container, there is an event that tracks `Claims Downloads` on eBenefits. This trigger is found here: `Event - Download VA Letters - Document Click`

Do you think we should create an exception so the new PDF tag doesn't fire on eBenefits events twice?

**Comment by jonwehausen** [comment]
Hi @nedierecel ,

This is ready for your QA. 

I setup a standalone tag for any generic file download...pdf, xlsx, jpg, etc. 

I put in an exception to not fire this tag on the ebenefits/download-letters page.

**Comment by nedierecel** [comment]
@jonwehausen Thanks for the new look-up table. So it aligns with the Modernized container, we could: 

- Update the Modernized version of the tag to also pick up the Click Text (instead of Click URL) and leverage your look-up table here also

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/85ccce92-b386-4897-aec7-6ca07181de51)

- Within both versions of the tags, I know our convention is to typically use the GTM event. In cases where we are scraping, this might not be meaningful to GA users any more. Should we replace leverage {{Click URL}} for Event Label or leave as-is?

**Comment by jonwehausen** [comment]
@nedierecel Great call. 

- I've adjusted this tag in both the modernized and legacy containers to use an Event Action of "file_type Downloaded - {{Click Text}}" and Event Action of "{{Click URL}}" instead of {{Event}}. 

Please see the workspaces here: 

- [Legacy Container - Any File Download Workspace ](https://tagmanager.google.com/#/container/accounts/144676348/containers/9159499/workspaces/93)
- [Modernized Content - Any File Download Workspace](https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/685)
  - Changed the existing PDF download tag to mirror legacy container

**Comment by jonwehausen** [comment]
@nedierecel I think so, users will at least know the file name by the Event Label in this case.

**Comment by nedierecel** [comment]
@jenniferlee-dsva @Karak888 We are getting ready to publish the changes to track PDFs for you to see PDF downloads on the VA Forms pages (and other legacy content). 

**FYI**: We are making a naming event change in Google Analytics that will also impact downloads in our Modernized content. 

For example, a download of PDF version of 10-10EZ on https://www.va.gov/health-care/how-to-apply/index.html:

- Current State: 
  - `Event Action: PDF Downloaded - https://www.va.gov/vaforms/medical/pdf/1010EZ-fillable.pdf` (Includes the PDF URL link)
  - `Event Label: gtm.LinkClick` (This is a Google Analytics term that's not very insightful)

- New State: 
  - `Event Action: PDF Downloaded - Download VA Form 10-10EZ`
  - `Event Label: https://www.va.gov/vaforms/medical/pdf/1010EZ-fillable.pdf` - (The PDF URL link is moved here)

CC: @meganhkelley @lwalsh617 @artsymartha68

**Comment by jenniferlee-dsva** [comment]
Hi @nedierecel - If I'm understanding this - now the event action will show the actual link text; and the event label will show the URL -- and these are what will display on Google Analytics reports? 

I love this! In fact, it would be awesome to expand this beyond VA Forms pages and track these events also on the benefit hub pages. @Karak888 - Maybe this is a new ticket/request...

**Comment by nedierecel** [comment]
@jenniferlee-dsva You are reading that correctly.

And, good news! The work @jonwehausen did in this issue will cover the Modernized content, including the hub pages.

For _historical data_: The data you pull _before_ we make this change will still use the older format:

`Event Action: PDF Downloaded - https://www.va.gov/vaforms/medical/pdf/1010EZ-fillable.pdf (Includes the PDF URL link)`
`Event Label: gtm.LinkClick (This is a Google Analytics term that's not very insightful)`

**Comment by nedierecel** [comment]
@jonwehausen - This should be good to publish. Let's leave in the QA for post-deploy review, and then we'll close out when everything looks good.

**Comment by nedierecel** [comment]
@jonwehausen I noticed a few stragglers coming in where there is no `{{Click Text}}`. To recreate, use the Legacy container and visit https://www.benefits.va.gov/homeloans/appraiser_fee_schedule.asp then click on the map. 

[GA Report for Example blank Click Text](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20191022&_u.date01=20191022&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:PDF%20Downloaded%20-/)

**Comment by jonwehausen** [comment]
Hi @nedierecel ,

Thanks for identifying, great catch!

Here's my proposed solution: 
- If the {{Click Text}} is available, we will use that, if not, we'll assume the name of the file can be grabbed from the URL to give some context to what was downloaded. 
- We use the filename in the event action
- For your map finding above, that would mean the file download event would look like: 
![image](https://user-images.githubusercontent.com/48527022/67493232-97b66480-f645-11e9-9cce-6b2a1ffb2edb.png)

Obviously in this case it's sort of redundant with the Event Label, but at least it's cleaner. Unfortunately there's not anything within the HTML that we could leverage that would give context to the state that was actually clicked on.
