### ISSUE TITLE
NOD Automated Alerts

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#21829]
## Acceptance Criteria

- [x] Just as we now have 526 Grafana slack alerts in dsva/#vsa-claims-appeals, do the same for NOD
- [ ] Test it to make sure it's working

**Comment by annaswims** [comment]
Alerts are configured http://grafana.vfs.va.gov/d/WxQ9lkUGz/claims-and-appeals-alerts?viewPanel=4&orgId=1&from=now-24h&to=now

We'll verify once we have more submissions in staging/prod
