### ISSUE TITLE
[Backend] Unnest Medical Facility Questions on BE

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#21830]
**Description**
The front end will be un-nesting the last medical facility questions on the 10-10cg schema. The backend will need to be updated to accept the new properties and ignore the previously nested ones.

**Summary**:
- [ ] Import schema to backend
- [ ] Write code to support un-nested medical facility questions on API
- [ ] Notify CARMA of data contact change (await approval)
- [ ] Merge schema
- [ ] Merge API

**Comment by hdjustice** [comment]
After discussing this with Lihan, changing how the attributes are formatted and sent is not worth the risk of breaking something in the backend.  There are no issues on how the data is sent currently, and we feel this change is simply not necessary, and not worth the risk.
This was communicated to Stakeholders on 11/4/2022 during routine stakeholder touchbase call
