### ISSUE TITLE
[FE] My VA: Apply For VA Benefits visual updates

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#21837]
- Switch from 3 col to 2 col
- Use the new Action Link
- Updates to the "Benefits you might be interested in" section

[Full specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/apply-for-benefits.md)

**Comment by erikphansen** [comment]
The designs for this are still in flux, but might looks something like this. Note the new colored icons. 
<img width="1084" alt="Screen Shot 2021-03-22 at 10 05 53 AM" src="https://user-images.githubusercontent.com/20728956/112029193-358db780-8af6-11eb-90b7-d1e1d70474ff.png">
![my_va_desktop_everything](https://user-images.githubusercontent.com/20728956/112029201-39213e80-8af6-11eb-985d-a685ae507da9.jpg)

**Comment by Samara-Strauss** [comment]
> Note the new colored icons.

These currently exist on the [homepage](https://www.va.gov/), [hub pages](https://www.va.gov/health-care/), and in the [hub navs](https://www.va.gov/health-care/about-va-health-benefits/), so you should be able to grab these from somewhere.

**Comment by ajakabcin** [comment]
Confirmed on staging
