### ISSUE TITLE
[Frontend]: Clarify language around adding a Primary/Secondary Family Caregiver

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#21843]
## Background

In the [usability studies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/1010cg-mvp) we've done on the 10-10CG, caregivers have repeatedly expressed confusion around the wording of the "Would you like to add a Primary Family Caregiver" question.  Let's reword that question to make it less confusing to Veterans/Caregivers. 

## Technical Task
Update content so it is more concise as described in [design ticket](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/21611).

On the page asking if the user wants to add a PFC:
- [x] Change the question to read "Would you like to apply for benefits for a Primary Family Caregiver?"
- [x] Change the additional info component to read "Learn more about who qualifies as a Primary Family Caregiver"

On the page asking if the user wants to add a SFC:
- [x] Change the question to read "Would you like to apply for benefits for a Secondary Family Caregiver?"
- [x] Change the additional info component to read "Learn more about who qualifies as a Secondary Family Caregiver"

On the page where we ask if the user wants to add *another* SFC:
- [x] Change the last question to read "Would you like to apply for benefits for another Secondary Family Caregiver?"

## Expected Behavior

Additional info content is updated as per designs in the above linked ticket

## Acceptance Criteria

- [ ] Staging environment matches the designs in the [design ticket](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/21611).
- [ ] Content is update for Primary Caregiver
- [ ] Content is update for Secondary Caregivers

**Comment by LinnJS** [comment]
Look at the content on local environment and everything looks good to go!

**Comment by mlighdc** [comment]
Although, not a big risk given the content. Let's make sure we do a retro on this so it will be helpful for all who are familiar with the work or scrubbing in to help. Should figure out how to prevent changes being tested from going into production. @ala-yna flagging so we don't forget to discuss as a team at retro. Thanks.
