### ISSUE TITLE
Content Feedback - Staging review - On this page component

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#21853]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback key
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
@caw310 @CrystabelReiter 

**Consider**

Please see attached content feedback for the On this page jump link documentation: 

[https://app.zenhub.com/files/133843125/fc73afc6-0c44-4f50-a933-b13dda769561/download](https://app.zenhub.com/files/133843125/fc73afc6-0c44-4f50-a933-b13dda769561/download)

**Comment by CrystabelReiter** [comment]
@peggygannon Thank you for taking the time to give me content feedback. 
I incorporated all the consider feedback and deleted the last point in Usability guidance because reading back it was just being repetitive.
