### ISSUE TITLE
[AUTOMATION]: VSP Testing Tools Team - Review CMS preview env axe-core injection for potential timing issue

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21866]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Details
VSA Public Websites reached out to Trevor on 3/22 about an axe issue in the Drupal preview environment. This was a false positive and appears to be happening because axe is injected into the page before all custom JavaScript is loaded. We should move axe to the last injected item or wait for the `DOMContentReady` event to fire.

## Acceptance Criteria

- [ ] CMS preview environment axe helper flags issues correctly

**Comment by pjhill** [comment]
OBE -- changes to aXe scan and enhancements to the scan in Cypress have resolved this issue
