### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#21869]
# Request Google Analytics and/or Domo access

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

Requesting Google Analytics & DOMO access for Emma Waters:  emma.waters@va.gov
 
## Access Requirements
Please check the analytics tools you need access to:
- [ x ] Google Analytics
- [ x ] Domo
_Please list any additional requirements, if any._

## Date Required
_Please share the date you require access._ ASAP - this week would be great. 

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

Booz Allen / Education Application

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @amyknox , 

Thank you for your request. 

Emma has been provisioned Google Analytics and DOMO access at `emma.waters@va.gov`. She should have received an email invite for both. 

We will close this issue but please feel free to reopen should she have any access-related concerns/questions.
