### ISSUE TITLE
Synthesize findings from KPI Workshops

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2186]
## User Story or Problem Statement
How might we synthesize findings from KPI workshops into insights for moving forward with data-driven product decisions?

## Goal
Determine which KPIs Insights needs to maintain and consolidate KPIs so that we can more easily track them in the next quarter.

## Objectives or Key Results this is meant to further
- Track and maintain KPIs every quarter across the VA that are centered around user experiences and goals

## Acceptance Criteria
- [x] Capture all team KPIs in one document or Github
- [x] Aggregate KPIs
- [x] Analyze KPIs to determine
   - [x] Which KPIs are the most common
   - [x] which data sources we can pull from for tracking KPIs
   - [x] which desired metrics are uncaptured

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
[KPI Folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/insights-analytics/kpi-tracking) with [list of set KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/kpi-tracking/kpi-list.md) and [updated processes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/kpi-tracking/kpi-process.md) now available.

KPIs have been consolidated [here](https://docs.google.com/spreadsheets/d/1No7cWp3LgD69dQWgA5bdgo0zx5d-1m-4HW-ZLnasSDM/edit#gid=0); next steps are aggregating for most common KPIs, reaching out to Product Owners/Managers for completed baselines and goals, and providing missing baselines or capturing which metrics are missing.

fyi @nedierecel

**Comment by joanneesteban** [comment]
Next Steps for future issue:
1) Reach out to Product Owners/Managers to:
    - [ ] grab links to updated KPI workshops
    - [ ] help determine any missing baselines
2) Wrangle GA metrics for baselines. Determine uncaptured GA metrics and begin process for capturing those.
3) Cross reference Top Metrics with Product Health Tool @amycesal 
4) Begin looking into low-hanging fruit for uncaptured metrics
5) Determine workshops for this quarter (i.e. measuring and prioritizing your KPIs, re-evaluating KPIs and hypotheses)

**Comment by nedierecel** [comment]
@joanneesteban Thanks for compiling!

In seeing them on one page, there may be a few KPIs that are common but not currently checked off for each team (e.g. *Decrease Errors* can apply to VAOS too)
