### ISSUE TITLE
[FE] My VA: Implement error state for when we can't connect to the health care endpoint

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#21870]
## Background

Design in #21579

[Documentation for the health care section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/health-care-section.md#when-to-show-the-health-care-section)

If we can not detect whether someone has health care or not because we can't connect to the endpoint, we will show an error at the top of the page and not load the health care section.

![Health care section_error_can't connect to endpoint.jpg](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/25296ceb-82aa-485a-b509-9fcab060ca81)

## Tasks

- [ ] Implement health care error for when we can't connect to the health care endpoint

**Comment by tressaellen** [comment]
**We can't access any health care information right now**

We’re sorry. Something went wrong on our end. If you get health care through VA, you won't be able to access your health care information right now. Please refresh or try again later.

<img width="911" alt="Screen Shot 2021-04-01 at 4 42 35 PM" src="https://user-images.githubusercontent.com/58752772/113351749-c1b69080-92e7-11eb-9979-52ee27632945.png">

**Comment by sanlouise** [comment]
Merged & closing since I don't think there is an easy way to validate this on the FE.
