### ISSUE TITLE
PowerBI Reports

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#21881]

**Comment by jwowk** [comment]
3/23/21 - Added Data Definition pages for VEText COVID-19 reports and added "Status" filter for outreach request tracker.

**Comment by jwowk** [comment]
4/7/21 - Updated reports to filter out patientInitiated = true values

**Comment by jwowk** [comment]
4/16 - Resolved issues with scheduling dashboard with Andy's assistance. Completed updated summary report with total response data vs direct schedule response data only.
4/19 - Completed draft Keep Me Informed report with drill down appointment data.

**Comment by Kennon-git** [comment]
SLA reports - shane to provide

**Comment by jwowk** [comment]
5/13 - Completed SLA detailed report and published.

**Comment by jwowk** [comment]
6/3 - Completed COVID-19 Patient Outreach Detail report and published.
6/8 - Completed VEText VistA vs SSO Login report and published.

**Comment by Kennon-git** [comment]
justin working on new cc report

**Comment by jwowk** [comment]
Rob will be adding three new fields to the siteStats table to support a report for CC use case 2 and a future report for use case 3.

**Comment by kjduensing** [comment]
report added before vacation - enabled clinics

possibly adding filter fields

**Comment by jwowk** [comment]
Upcoming Updates
Expand Enabled Clinics to include Excluded clinics and expand available fields (Message Template, Message timeframe)
Update CC report with additional filters, date, station, visn
