### ISSUE TITLE
PM: Coordinate IA and Content Intro for Facility Locator Team

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2188]
### User Story
As a PM for a VFS team going through onboarding with VSP, I need to participate in an IA & content intro session along with relevant members of my team, so that we know best practices for IA & content and how to engage with the VSP content & IA team.

### Goal
Schedule and attend IA & content onboarding session with VSP's content and IA team and the PM, content writers, and designers on Facility Locator.

### Definition of Done
- [x] Facility Locator PM has reached out to schedule Content & IA intro with VSP content & IA team.
- [x] Meeting has been completed: Facility Locator has gone over best practices and ROE with VSP content & IA team.
- [x] Document findings and feedback from that meeting to recommend for doc iteration.
- [ ] Ticket has been assigned to a sprint and an epic.

**Comment by peggygannon** [comment]
Onboarding meeting scheduled for Thursday 10/17.

**Comment by mnorthuis** [comment]
Meeting complete.
