### ISSUE TITLE
Access for MR Ngo

### ISSUE THREAD

**Issue by marungo** [department-of-veterans-affairs/va.gov-team#21887]
Instructions
Fill out Description
Add the label used by your team (eg: BAH-526)
Do not remove operations label; this will notify the VSP Operations team of your request
When the issue is closed you will be notified and can continue with on-boarding setup
Description
Please provide your Contracting Officer's Representative (COR) name.

Cecilia Lee

Please provide your name.

MR Ngo

Please Provide your email.

mrngo@thoughtworks.com 

Please provide the name of your team, your role on that team, and the name of the company you work for.

Delivery Infrastructure Team - Developer [ThoughtWorks]

Requesting SSH key authorization?

YES

What is your **public** SSH key? If you don't have a SSH Key or know how to find it click here for instructions. (Example below)

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKWJcuFUkXKuy2Qe/sAIteISwGe/1jfA24/oQQkTkZAf mrngo@thoughtworks.com

Grant AWS Console access?
NO

**Comment by marungo** [comment]
I am one of the developers who will be working on getting the performance dashboard working again (and migrating the CI from Jenkins to Github Actions)

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
