### ISSUE TITLE
Delete photos or files from upload after selection 

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#21896]
# User Story

- As a user, I want to delete photos once I've selected them for upload so I don't have to start the flow over again. I want to be able to delete multiple photos at one time. 
- As a user, I want to delete a file once I've selected it for upload so I don't have to start the flow over again.

# Corresponding front-end ticket 
Delete photo(s) from upload screen #20992

**Comment by msmanak** [comment]
[Uploading... Claims delete.png]
