### ISSUE TITLE
UX/UI when a user cannot access Appointments/Messages

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21899]
## Acceptance Criteria
1. When a user does not have Appointments AND Secure Messaging in their list of authorized services, implement the UX/UI indicated in the linked designs when a user tries to navigate to the Health landing page
     - Healthcare services is 'false'
2. UI contains header / intro content
3. Below the intro content, create series of 3 'step tables' that can be expanded/collapsed
     - pull in Step Table CC
     - All content is hard-coded
4. Each step table contains 2 click-to-call buttons (6 total)
5. On default, all sections are collapsed
     - Multiple accordions can be expanded simultaneously

## Designs
Collapsed (default): https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447232868
All expanded: https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447232869

## Accessibility Implementation Guidelines

- Mark "We couldn't match your information to our VA patient records" as Header 2
- Mark "What you can do" as Header 3

**Step Table**
For each item in the table:
- accessibilityLabel= Text
- accessibilityHint= "view more details"
- accessibilityRole= "spinbutton"
- accessibilityState= Denote when dropdown is expanded or collapsed
- Ensure dropdown area does not "trap" the keyboard focus

**Phone numbers (links) in each step table**
- Title= Name of link, (e.g. 800-698-2411, select 3) 
- accessibilityHint= “Dials this number via your device’s call function” 
- accessibilityRole= “link”

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by bessgreen** [comment]
UX/UI review: 

AC #5: "Multiple accordions can be expanded simultaneously" - is this the desired behavior? (same UX as Claims Step Table)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/2/2021 - Looks good on Android and iOS. Verified on appointments.  Closing.

**Comment by bessgreen** [comment]
Ticket needs to be revisited. Currently, it only accounts for the Appointment service, but it needs to also account for Messages.

**Comment by bessgreen** [comment]
This screen is no longer relevant, as all LOA 3 users have access to appointments: If a user can access the app, they will have access to appointments, which means they will be able to access the Health care page. 

Closing.
