### ISSUE TITLE
UX/UI when a user cannot access Claims/Appeals

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21898]
## Acceptance Criteria
1. When a user does not have Claims and Appeals in their list of authorized services, implement the UX/UI indicated in the linked designs
     - Claims AND appeals are 'false'
2. This screen will appear when a user tries to navigate to the Claims & Appeals landing page
3. Design notes
     - Copy is hard-coded
     - Implement click-to-call buttons

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447232014
![Screen Shot 2021-03-22 at 3.53.11 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/2d83d987-b1ee-4b1c-83c2-e7e6dda8d633)

## Accessibility Implementation Guidelines

- Mark "We can't find any claims information for you" as Header 2

**Two phone numbers (links)**
- Title= Name of link, (e.g. 800-827-1000) 
- accessibilityHint= “Dials this number via your device’s call function” 
- accessibilityRole= “link”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/2/2021 - Looks good on iOS and Android, UI and accessibility.  Closing.

**Comment by bessgreen** [comment]
QA: use +1417
