### ISSUE TITLE
Monthly VEO Metrics + Metrics after Nov '18

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2190]
## User Story
As a VEO user, I need monthly analytics for Education, Burials, and Claims so I can report on this data to internal stakeholders.

## Goal
Provide monthly data for September in visualization
Provide links to Jack Yang within Google Analytics
Determine how we grab + visualize data next month and the following months

## Acceptance Criteria
 - [ ] Monthly Data
 - [ ] Visualize Data
- [ ] Determine how we grab + visualize data in the following months

## Definition of Done
 - [ ] Attached to a Milestone (when will this be completed?)
 - [ ]  Attached to an Epic (what body of work is this a part of?)
 - [ ]  Labeled with Team (product support, analytics-insights, operations, triage, tools-improvements)
 - [ ]  Labeled with Practice Area (backend, frontend, devops, design, research, product, ia, qa, analytics, call center, research, accessibility, content)
  - [ ] Labeled with Type (bug, request, discovery, documentation, etc.)

**Comment by joanneesteban** [comment]
## CSAT

CSAT on the [vets.gov/va.gov metrics](https://docs.google.com/spreadsheets/d/1L_w8FhhcOttMitKB3_9ge8UN01GcSXmaPZWDIRJIhxI/edit#gid=972187789) sheet is updated.

### What is your overall satisfaction with this site

#### Pre-Relaunch
![image](https://user-images.githubusercontent.com/48964695/66239775-c1c0da80-e6c8-11e9-95e3-13781bdd2aee.png)


#### Post-Relaunch
![image](https://user-images.githubusercontent.com/48964695/66239740-ac4bb080-e6c8-11e9-89ba-0dbce58e4789.png)

---

We should probably note that the Post-Relaunch "What is your overall satisfaction with this site?" total responses is 3.7x more than the total responses for Pre-Relaunch.

**Comment by nedierecel** [comment]
@amycesal I have updated the metrics and am doing a final pass through this late afternoon to validate the numbers.

**Comment by joanneesteban** [comment]
For post-November, I think it makes more sense to start doing a month-by-month historical view, but let's hold off and see if Lacey can get a sense of what the stakeholder wants to answer with the data post-November.

**Comment by nedierecel** [comment]
@amycesal The latest metrics are ready after Jon's review. For visibility, I updated the last set of numbers for HCA as it looked like it repeated the previous time period. I can add this as a footnote within your reports.

**Comment by joanneesteban** [comment]
Metrics sent to Lacey, 10/10/19, who sent to OIT:

[Metrics for Modernized Data 10.01.19.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3713713/Metrics.for.Modernized.Data.10.01.19.xlsx)
[Metrics_10.01.19.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3713714/Metrics_10.01.19.pdf)
[Metrics_10.01.19.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3713715/Metrics_10.01.19.pptx)
