### ISSUE TITLE
Access for [individual]

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#21904]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Dilloshion Raju(Dillo)
- Please Provide your email.
   > draju@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Healthcare/Senior backend engineer/GovernmentCIO

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAACAQDKP5ggfcuEr4bfzK93PwZfKrwlZwLPTn8cBtdreoq2BNcN4sLDbJY2ryVnRJZGmX/eJNOLns/tmpCZMkSj0WLrejPJ1vxRgbEkb0fKSnBNcQ5li/yvOcPQMdU4Pw3FOjSVBoT3KnMy4oX6SuwATGHt15aQnQj1p80BpQw+l/8xLUZrLIjGG6KcISn7ewdRqYP5tH0twVoZLkBU0HeZe+GFQRhPWe9ayMSREYCaNrZnsYo5xgTefcK7FTNkHStMACZOtQtESnlPtFMjzOZnR2WZFnrIKBFkLCPG2sLcG2tMgUhewwHCLSEwEHopaqzllT6mloeIreLcctXBF7MYPjj/LiYVg43WtmcipM6TD4O8mSWH3X3Zmh3Sl9HZAEto4Bjw/k/ZqtjGH9PqTtuEfOBPWZWtfkI3OKpS9pwb0p/WpFunUR5IgpbTKibXPfDp+B/Bq3sRZhtAG3ScQe0GzUOSJB2yt2QLBDwDIC2c6Rw3fFIRMpIx7l+ohlmNNYROH9sspt/spGWStKABvJobzRRXgXI4wmS8kME5akSRLWxkVfVRvIbZmGdPfeEIAh8dg1PZHrRODem2p2PT2p46JvNH4TJM+6a8hkO4h+V6DGhMYt8gcsD++BKnxfm2NaGLTdqx/WM5J9fiPX7hUUrvH/0OQpPZtdPCpv3080gIOhE/2w== dilloshion@gmail.com
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  - Requesting access to Cloudwatch so that I can monitor application(vets-api) logs.

**Comment by jbritt1** [comment]
@dillo it appears you already have SOCKS access / we have you key on file. Are you not able to access SOCKS? Or is this a follow up ticket to request AWS access?

**Comment by dillo** [comment]
> @dillo it appears you already have SOCKS access / we have you key on file. Are you not able to access SOCKS? Or is this a follow up ticket to request AWS access?

@jbritt1 This is a follow-up ticket to request AWS access.

**Comment by jbritt1** [comment]
> > @dillo it appears you already have SOCKS access / we have you key on file. Are you not able to access SOCKS? Or is this a follow up ticket to request AWS access?
> 
> @jbritt1 This is a follow-up ticket to request AWS access.

Roger, thank you for the info.

**Comment by jbritt1** [comment]
### AWS Access

User: Dilloshion Raju(Dillo)
COR: Mary O'Toole
Approval required: @Jeff-Hayter

**Comment by dillo** [comment]
@Jeff-Hayter could I get an update on this, please? Thank you!

**Comment by mlighdc** [comment]
@Jeff-Hayter Can you please review and let us know if you have any question? Thank you!

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
@mlighdc / @dillo, I am on PTO today returning tomorrow. I can pick this up when I return tomorrow or if you require a quicker turnaround you can drop a note in the vfs-platform-support channel in Slack and the oncall staff can likely expedite.
