### ISSUE TITLE
[Discovery] Upload size and extension restrictions to CARMA, vets-api, S3

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#21905]
In order to set the file upload restrictions (acceptable size and extensions), we need to know the restrictions of all the dependent services that will accept the document.

Research the size limit and acceptable extensions for:
- [x] CARMA
  - Ranga suggested 35MB
- [ ] vets-api
- [x] S3
  - 160 GB ([docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html))

Based on the above information, make a decision on what the restrictions should be on the user's side.

---

**Prev**: [#21909](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21909) | **Next**: [#21906](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21906)

**Comment by LinnJS** [comment]
How many documents do we want to allow the user to upload? CARMA currently only allows one document at a time currently as far as @kevinmirc's knowledge.

Would create extra work to combine documents on Backend.
