### ISSUE TITLE
NOD - Work with Content team

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21926]
## Issue Description
Engage content team for assistance with NOD

---
## Tasks
- [ ] Set up call with Beth Potts

## Acceptance Criteria
- [ ] Call scheduled
---

**Comment by kevinstachura** [comment]
We have worked with the content team to add changes this sprint, which can be found here:

https://vsateams.invisionapp.com/share/8Y10I6K7DU9R#/screens/447558866
