### ISSUE TITLE
Requesting ECS access for the vsp-testing team

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#21922]
## Description
I'm requesting ECS access for the `vsp-testing` team. We want to be able to see the console, and also CloudWatch monitoring for ECS, specifically for the Pact Broker.

---

## Definition of Done
- [ ] Members of the `vsp-testing` team are able to see the console and CloudWatch monitoring for the Pact Broker.

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by holdenhinkle** [comment]
This work is in regards to this ticket - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/21122

**Comment by jbritt1** [comment]
New permissions set added to allow read against the pact-broker ECS cluster. Please test, verify, and confirm as time allows.

**Comment by holdenhinkle** [comment]
Thanks Jeremy.

I tried [this link](https://us-gov-west-1.console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#container-insights:performance/ECS:Cluster?~(query~(controls~(CW*3a*3aECS.cluster~(~'dsva-vagov-utility-pact-broker-cluster)))~context~())) which Demain gave us the other day and it's not working. Here's what I see:
![image](https://user-images.githubusercontent.com/9326247/112498191-ad5d1b80-8d5c-11eb-88cb-dddf62735f85.png)

Is that the correct link?

If a try to [view the clusters](https://us-gov-west-1.console.amazonaws-us-gov.com/ecs/home?region=us-gov-west-1#/clusters) I see this:

![image](https://user-images.githubusercontent.com/9326247/112498503-f7de9800-8d5c-11eb-8134-16317242e0d5.png)

**Comment by jbritt1** [comment]
Okay, will work on it further.

**Comment by jbritt1** [comment]
How about now @holdenhinkle ?

**Comment by holdenhinkle** [comment]
Hey @jbritt1, It still looks the same when I click those links:

- https://us-gov-west-1.console.amazonaws-us-gov.com/ecs/home?region=us-gov-west-1#/clusters
- https://us-gov-west-1.console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#container-insights:performance/ECS:Cluster?~(query~(controls~())~context~())

**Comment by jbritt1** [comment]
Do you have an MFA device set up and synced with your AWS account?

**Comment by jbritt1** [comment]
Confirmed with Holden via DM that he is now able to access the links provided for viewing pact-broker ecs cluster metrics. Closing.
