### ISSUE TITLE
NOD Research Reporting 

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21924]
## Issue Description
NOD Research Summary

---
## Tasks
- Prepare top line summary document
- Full findings slide deck

## Acceptance Criteria
- [ ] Completed and posted to Github
---

**Comment by kevinstachura** [comment]
Research summary has been completed and can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Notice-of-Disagreement
