### ISSUE TITLE
Create functions to fetch VATS settings in Location service

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#21921]
We have several instances where we fetch VATS settings and these calls skip our services layer, since they don't have a direct equivalent in the FHIR model.

However, we should include them in our services layer for consistency. Since they're related to locations, I think the Location service would make the most sense.

Additionally, we should evaluate if there's a simpler/clearer format for the settings information that we could return out of the services layer, to avoid propagating the confusing VATS settings logic further. We should check to see if the next iteration of mobile facility service in VAMF has reorganized these settings at all, potentially as a guide for us to follow.

AC
- [ ] Create functions to fetch request/direct booking settings in Location services file
- [ ] Update application code to use the services layer functions instead of the api calls directly
- [ ] If work seems reasonable, return simplified settings format from service layer call and update application accordingly
- [ ] Write JSDoc comments for services function(s)

**Comment by sortizsh** [comment]
relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/44670
