### ISSUE TITLE
NOD - Synthesize Usability Results

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21923]
## Issue Description
NOD Usability
---
## Tasks
- [ ] Synthesize results of usability study.

## Acceptance Criteria
- [ ] Results posted to Github
---

**Comment by kevinstachura** [comment]
Synthesis has been completed and can be found in our summary document:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Notice-of-Disagreement
