### ISSUE TITLE
[Discovery] VA.gov User Questions & Feedback

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#2194]
## User Story or Problem Statement
As a user of the VA.gov site, I need a way to submit feedback about the site to so I can feel engaged and listened to.

# Background
VA.gov uses a service called `iris` for collecting feedback & questions from users.
![image](https://user-images.githubusercontent.com/3077884/66060645-005d6600-e50c-11e9-8c7b-85f3f6590ed0.png)

We think there could be some opportunities for improvement on tool and/or the overall process of submitting questions & feedback to va.gov.

## Goal
The goal of this issue is to do discovery work the current process of submitting questions & feedback to VA.gov, such that, we know enough to identify specific areas for improvement.

## Acceptance Criteria
- [ ] Discover the history of using `iris`
  - [ ] Why do we use it?
  - [ ] Who depends on it?
  - [ ] How do forms submitted get processed & handled
- [ ] Discover if we can / want to replace all or some of it
- [ ] Discover pain points from the perspective of end users
- [ ] Discover if users are kept in the loop after they submit a question

**Comment by alexpappasoddball** [comment]
Maybe there are some metrics we can have Analytics pull for us.
Visits vs Submissions?
Drop offs after X amount of time.
etc.

**Comment by Kimberley2019** [comment]
With modifications and possible deletion of IRIS, this ticket can be closed.
