### ISSUE TITLE
Discharge Upgrade Wizard - Form Updates (Broken PDF link + New Online app)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#21944]
### What's the Problem

There are two issues related to this wizard/product: **Note - we are only addressing issue 1 in this ticket.  Refer to #23068
for info about reverting this link back after help text is added, and #23071 for the change to the link for Air Force Personnel**

1. A veteran user of VA.gov reports that the DD 149 PDF download link contained in the [upgrade discharge status wizard](https://www.va.gov/discharge-upgrade-instructions/) does not seem to work. The PDF form is located at this URL https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf.   Instead of seeing the PDF form, the user gets this confusing message:

![Broken PDF Form Link](https://user-images.githubusercontent.com/63107147/112183219-6c39ff80-8bd4-11eb-977f-211604bfdfb7.jpg)

(Tried VA PC on VPN, personal Mac laptop, personal and VA iPhones). 

2. For US Air Force personnel who use the Wizard (the Wizard literally branches users by service), DD Form 149 has now been replaced by an eApplication at https://afrba-portal.cce.af.mil/#portal -- and we've been asked to route users of the wizard to that website vs. providing the form as a download.

<img width="330" alt="US AF Discharge Upgrade Page" src="https://user-images.githubusercontent.com/63107147/114218970-15ecf080-9938-11eb-86e0-799588d2368a.png">

### What's the Cause

**For Issue #1:**
Per Jen Lee: This is – sadly – a well-known issue. It has to do with the fact that some VA businesses and non-VA businesses are creating PDFs in a dynamic XFA format of Adobe PDF.  (The form you reference is in fact a DOD form, so not created by VA in this instance.) The dynamic XFA Adobe format happens to be the very latest version of PDF formats, and many in VA – and looks like at the DOD as well -- mistakenly believe that the 21st Century Idea Act requires VA to use the very latest Adobe PDF format without regard to whether it is supported by browsers. Unfortunately, this newer dynamic XFA format is not supported by the International Organization for Standardization - ISO. And because it isn’t supported by the ISO, modern browsers like Chrome, Safari, Firefox don’t support it either. 

### What's the Solution

**For Issue #1:**

- We could change the URL link in the Download CTA to this MilConnect FAQ https://www.dfas.mil/correctmilitaryrecords/ which links to an older version of the DD 149 form. This older version opens okay in the browser: https://www.dfas.mil/Portals/98/Documents/CorrectMilitaryRecords/dd0149.pdf?ver=2020-01-08-143351-750

- Or we could include instructional text on our page telling users to download the form first to their desktop.

**For Issue #2:**

- We need content and possibly SME support to rework the Air Force specific results page for the Wizard
- We need to change the **Download Form 149 CTA** link to a Link that tells the user that s/he can apply online for a Discharge Upgrade

### Next Steps

- Let's talk about this ticket in more detail during grooming as its a little tricky.

**Comment by johnhashva** [comment]
@brianalloyd I believe we agreed that Public Websites could jump on this since we are not 100% this is a product managed by the Benefits team and Matt.   With that in mind, I'm adding an additional intake request to this ticket so we can tackle both at once.

**Comment by brianalloyd** [comment]
Sounds good @johnhashva we can work them both into the sprint or future sprints.  Thanks.

**Comment by MarciMcGuireGCIO** [comment]
As described above, the PDF issue is unrelated to the link, but rather related to the browser's built-in PDF reader.  Browser-based readers typically do not handle dynamic PDFs well (if at all) due to the proprietary nature of some features.

As stated above, if the user downloads the form locally and opens with Adobe Reader, it works fine.  Another option is modifying browser settings so that PDFs default to Adobe Reader instead of the internal reader, so that could also be included in recommendations.  In some cases, users won't have authority to change their browser settings (on a work-managed computer, for example), so there still needs to be an alternative solution.

**Comment by MarciMcGuireGCIO** [comment]
Just another thought -- since this is not an isolated issue on VA.gov, it may make sense create a shared content page specific to PDF support that other pages with similar PDF issues can connect to.  That would prevent various teams from having to create their own PDF support info, and would ensure that everyone is giving consistent support info.

**Comment by johnhashva** [comment]
Hmmm.  Let's talk that "shared content page specific to PDF support" idea.  In meantime, let's definitely get the semi broken link issue fixed first -- maybe we start with linking to the old form (quick fix today/tomorrow) while we work on instructional text on our page telling users to download the form first to their desktop.  We will need content support for that as well as the USAF update, I'm thinking.   But LMK your thoughts on this one.

**Comment by johnhashva** [comment]
@mattpointzxer0 + @brianalloyd moving this one over the Decision Tools team since this is a perfect fit for the team and they have some capacity right now.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva I agree; let's get the immediate issues fixed first and think about a content page later.  Do you happen to have a SME I can reach out to on the second issue?

**Comment by johnhashva** [comment]
I do - thought I pasted that in the ticket but must have forgotten.  Here you go -- and here is what he said re: content changes to the page:

**Comment by MarciMcGuireGCIO** [comment]
Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva do you happen to have the screen shot that Alexander refers to in his message?  Thx!

**Comment by johnhashva** [comment]
Dropping screenshot of USAF link page here

<img width="330" alt="US AF Discharge Upgrade Page" src="https://user-images.githubusercontent.com/63107147/114413716-3c02d280-9b7c-11eb-94d4-39f2c0cdaf09.png">

**Comment by zacharymorel** [comment]
Self not when doing work, see this thread: https://dsva.slack.com/archives/C01DWJFD45D/p1618240714138000?thread_ts=1618233190.125600&cid=C01DWJFD45D

**Comment by MarciMcGuireGCIO** [comment]
Splitting this into three distinct issues:

1) Immediate bug fix via updating PDF link to reference older DD0419 PDF version (will remain under this ticket)
2) Restore newer DD0419 PDF version in combination with download instructions  #23068
3) Change to point Air Force respondents to e-Application portal  #23071

**Comment by zacharymorel** [comment]
@johnhashva @MarciMcGuireGCIO 
I'm looking at this React Component, if we get to pick up Discharge Wizard and add it to our current wheel house of Tools to support, there's some serious opportunity for updating the inner workings of the application. This App has not been touched in 3 years (as far as updating code is concerned).

**Comment by johnhashva** [comment]
Good idea @zacharymorel .   @MarciMcGuireGCIO can you take a look in GA to see how popular this tool/wizard is?  BE good to have that in mind as we decide prioritization.

**Comment by MarciMcGuireGCIO** [comment]
Here's March.  Significant traffic on the landing page, but then a sizeable dropoff for the questions themselves. 
![image](https://user-images.githubusercontent.com/73354907/114440714-7712ff00-9b98-11eb-9c59-a3cc6eacf68d.png)

**Comment by MarciMcGuireGCIO** [comment]
By comparison, Yellow Ribbon had 80k total pageviews/18k unique pageviews during the same period.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO and @zacharymorel Sounds like a good product for us to make part of our consideration set for tweaking, enhancement -- along with ongoing maintenance.   You two think it through in context to our other products, priorities and sprint planning.

**Comment by MarciMcGuireGCIO** [comment]
Agreed!  Will do!  Thanks, @johnhashva

**Comment by MarciMcGuireGCIO** [comment]
Note - downloading the form still doesn't totally resolve the issue in cases where the user's system defaults to open PDF docs in something other than Adobe Reader.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO have you verified that the PDF change is live on staging?

**Comment by MarciMcGuireGCIO** [comment]
Yes; looks great!

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva - do we know who initially reported this issue and suggested linking to an alterative PDF?   In updating the same link on another Discharge Upgrade Wizard page today, @zacharymorel discovered that the PDF at the original link now opens.  I confirmed, and saw in the PDF properties that it was changed on 5/5/2021.   Just need to confirm it's OK for Zach to change back to the original PDF link that was problematic.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO First a veteran user, then Jen validated and suggested we link to:

We could change the URL link in the Download CTA to this MilConnect FAQ https://www.dfas.mil/correctmilitaryrecords/ which links to an older version of the DD 149 form. This older version opens okay in the browser: https://www.dfas.mil/Portals/98/Documents/CorrectMilitaryRecords/dd0149.pdf?ver=2020-01-08-143351-750

If the updated version of the original PDF now works, agree -- let's go with that.

**Comment by johnhashva** [comment]
Re-opening because of previous comment.

**Comment by johnhashva** [comment]
I'm confused:

This is the URL that the page originally contained, which gives you the Please Wait:  
https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf

This is the URL that the page now contains, which provides the PDF: 
https://www.dfas.mil/Portals/98/Documents/CorrectMilitaryRecords/dd0149.pdf?ver=2020-01-08-143351-750

I'm guessing we are talking about two different pages.  In any case, looks like we are good to go here and we can close.

**Comment by zacharymorel** [comment]
Yeah this url, https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf , _should_ work now. Does it not for you?

**Comment by johnhashva** [comment]
That link -- https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf --  gives me the Please Wait.

<img width="484" alt="Please Wait for PDF Downloads" src="https://user-images.githubusercontent.com/63107147/117672502-e835da00-b177-11eb-911b-c00571d763c6.png">

This one does not: https://www.dfas.mil/Portals/98/Documents/CorrectMilitaryRecords/dd0149.pdf?ver=2020-01-08-143351-750

Let's talk about/screenshare during Standup today to eliminate any confusion.

**Comment by MarciMcGuireGCIO** [comment]
Tested on WIndows, iPhone
