### ISSUE TITLE
SPOOL: Create PagerDuty Alert

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#21949]
As an EDU developer, I need to create a PagerDuty alert that notifies people when the daily spool file creation job has failed so that the issue can be investigated and addressed without requiring notification from the customer that they have not received the spool files.

## Assumptions:
1. This work does not require a prod or feature flag.

## Acceptance Criteria:
1. A PagerDuty alert exists that notifies:
    a. If possible the #vsa-education slack channel when a failure occurs during CreateDailySpoolFiles spool file creation.
    b. If possible the following EDU recipients via email: Joseph.Preisser@va.gov, Shay.Norton-Leonard@va.gov, PIERRE.BROWN@va.gov, VAVBAHIN/TIMS@vba.va.gov, EDUAPPMGMT.VBACO@VA.GOV when a failure occurs during CreateDailySpoolFiles spool file creation.
    c. The [#oncall](https://dsva.slack.com/archives/C30LCU8S3) channel

## Supporting Artifacts:
1. TBD

**Comment by zurbergram** [comment]
Documentation - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/248
Alert - https://github.com/department-of-veterans-affairs/devops/pull/8783
Increasing metric on exceptions - https://github.com/department-of-veterans-affairs/vets-api/pull/6270

**Comment by zurbergram** [comment]
To test verify alert is listed at 
- http://prometheus-dev.vfs.va.gov:9090/prometheus/rules
- http://prometheus-staging.vfs.va.gov:9090/prometheus/rules
- http://prometheus-prod.vfs.va.gov:9090/prometheus/rules

**Comment by delli-gatti-michael** [comment]
```
ALERT CreateDailySpoolFilesFailureWarning
  IF sum(rate({__name__=~"worker_education_benefits_claim_failed_spool_file_.*"}[1h])) > 0
  LABELS {app="api", component="education_benefits_claim", scope="component", severity="warn"}
  ANNOTATIONS {description="CreateDailySpoolFiles has had a failure within the past hour.  See https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md#createdailyspoolfilesfailurewarning", summary="CreateDailySpoolFiles failure occurred"}
```

Present at http://prometheus-prod.vfs.va.gov:9090/prometheus/rules
