### ISSUE TITLE
/v0/preneeds/cemeteries endpoint doesn't work in dev or staging

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#21943]
## What happened?

The `/v0/preneeds/cemeteries` endpoint has been unavailable in dev and staging for months (it does work in prod). 

That failing endpoint was causing a [failing Nightwatch test](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20649) during the [daily accessibility tests](http://jenkins.vfs.va.gov/job/testing/job/vets-website-integration-testing/). The [failing test has been skipped](https://github.com/department-of-veterans-affairs/vets-website/pull/16320) for the time being. 

- Dev: https://dev-api.va.gov/v0/preneeds/cemeteries
- Staging: https://staging-api.va.gov/v0/preneeds/cemeteries
- Prod: https://api.va.gov/v0/preneeds/cemeteries

Both dev and staging return the following error:

`{"errors":[{"title":"Service unavailable","detail":"Backend Service Outage","code":"503","status":"503"}]}`

### Staging

![](https://user-images.githubusercontent.com/6130520/109832035-9c116b00-7c05-11eb-94be-13665e39c685.png)

### Dev

![image](https://user-images.githubusercontent.com/6130520/112180402-88846f00-8bc9-11eb-8600-7f7b8765cc43.png)

## Relevant Links

- Original GitHub Issue: [Resolve issue with failing Nightwatch test](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20649)
- [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16320) to disable test that was failing because of endpoint being unavailable
- [Slack thread in #vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1/p1614787206037100)
- [Sentry error](http://sentry.vfs.va.gov/share/issue/394e157ce9c44838908b89103da9f2f8/)
- ["It looks like the breakers status for staging preneeds shows down"](https://dsva.slack.com/archives/CBU0KDSB1/p1614886088135500?thread_ts=1614787206.037100&cid=CBU0KDSB1)
- [Slack thread in #vsp-tools-be](https://dsva.slack.com/archives/CQHBJ5U06/p1616518307009700)

### Dev 

1. Visit https://dev-api.va.gov/v0/preneeds/cemeteries
2. Confirm that you see "Service unavailable"

### Staging

1. Visit https://staging-api.va.gov/v0/preneeds/cemeteries
2. Confirm that you see "Service unavailable"

## Desired behavior

The endpoint returns a response similar/identical to https://api.va.gov/v0/preneeds/cemeteries. 

## Acceptance Criteria
- [ ] The endpoint returns a successful response that includes cemetery data

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by alexpappasoddball** [comment]
@thilton-oddball (cc @ericboehs ) can one of you do some investigation to what is happening here?

**Comment by ericboehs** [comment]
Lindsey says the external service is down in breakers.

**Comment by LindseySaari** [comment]
The external service shows as [down in breakers](http://grafana.vfs.va.gov/d/000000022/breakers?viewPanel=1&orgId=1&from=now-2d&to=now&var-data_source=Prometheus%20(Staging)&var-service=All&var-endpoint=All). It's returning a 503 http error seen [here](http://sentry.vfs.va.gov/organizations/vsp/issues/14878/?environment=staging&query=is%3Aunresolved+preneeds&statsPeriod=14d) in Sentry
