### ISSUE TITLE
Accessibility Staging Review Feedback for On This Page Component - Code

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#21957]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh and Trevor

## Must
* Wrap the On this page component in a `<nav>` HTML5 landmark instead of an `<article>`. Article isn't the right grouping for a list of links.

  ```html
  <nav aria-labelledby="otp-heading">
    <!-- AT will anounce On this page, navigation -->
    <h2 id="otp-heading">On this page</h2>
    <ul>
      <li>
        <a href="#if-im-a-veteran">If I’m a Veteran, can I get VR&amp;E benefits and services?</a>
      </li>
      <li>
        <a href="#telephone-contacts">Telephone Contacts</a>
      </li>
      <li>
        <a href="#some-additional-info">Some additional information</a>
      </li>
    </ul>
  </nav>
  ```
* Manage focus correctly for screenreaders and browsers. I did some initial testing with iOS and MacOS VoiceOver, all good. 
  * However, these tickets #21067 and #15244 show an incorrect handling with iOS VoiceOver. I'm not sure what the connection is, but we need to find it.
  * The static content On This Page links are generated by `add-id-to-subheadings.js` file. If I added a `tabindex="-1"` to the headings, iOS + VoiceOver started honoring the proper behavior.

## Should
* Swap the `::before` attribute for an `<i>` so screen readers don't pick up on the down arrow:

  ```html
  <a href="#telephone-contacts">
    <i aria-hidden="true" class="fas fa-arrow-down"></i>
    Telephone Contacts
  </a>
  ```

## Consider
* What do you think about adding a prop: String that users can pass for the headings to target, with `article h2` being a sensible default? I might be solutioning--entirely possible. I've hard-coded selectors in the past and had greater/lesser outcomes. FWIW.
* I would love a link to the source code in the Storybook docs. I often like to review code while reading docs to map the informational and the technical facets.

**Comment by bkjohnson** [comment]
> Wrap the On this page component in a `<nav>` HTML5 landmark instead of an `<article>`. Article isn't the right grouping for a list of links.

The `<article>` isn't grouping anything in the component itself, it just happens to be the way that we currently render markup on long content pages:

![image](https://user-images.githubusercontent.com/2008881/112394912-b2698e80-8cba-11eb-8ad0-13d81685e6a2.png)

I can still put a `<nav>` inside the component but the article will be on the outside.

**Comment by 1Copenut** [comment]
@bkjohnson That's great, thank you. The want there was a named `<nav>` region for assistive tech. This screenshot gives a good representation.

**Comment by bkjohnson** [comment]
Addressed in https://github.com/department-of-veterans-affairs/component-library/pull/59
