### ISSUE TITLE
Launch Disability Calculator widget to production

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#2196]
Moved from https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19144

### Steps

- [x] Update HREF value of [Find your monthly payment amount](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/disability-rating-calculator/components/CalculatedDisabilityRating.jsx#L50) in widget footer
    - This should point to a new page on va.gov that is not yet published. 
    - Use to be tracked by this [ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19138).
- [x] In the CMS, edit the page at `/disability/about-disability-ratings` to add the calculator widget
- [ ] Ensure E2E tests are enabled in vets-website

**Comment by ncksllvn** [comment]
@tlei123 For your awareness, we're planning on going live with this tomorrow 😄

**Comment by ncksllvn** [comment]
@jenniferlee-dsva the updates per your [comment](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19144#issuecomment-537273186) have been made and should visible on Staging in about a half hour! 

Going live tomorrow will be entirely from Drupal - from the admin for that page, we'll just make our content tweaks, add the React widget as a Drupal component, and publish! Then it'll go out during the daily deployment.

CC: @Karak888

**Comment by jenniferlee-dsva** [comment]
Hi @ncksllvn - I've updated the drupal page intro text now, and it is ready for the calculator. Don't hate me but now that we're placing the calculator after the intro para, the first sentence inside the tool is redundant. Can you delete that sentence before adding it? (Sorry!) 

Here are the screen shots of the new intro text on the drupal page and the text that needs to be deleted inside the widget:

![image](https://user-images.githubusercontent.com/43381063/66092165-e4cc7c80-e558-11e9-8028-0a93826328ea.png)

![image](https://user-images.githubusercontent.com/43381063/66092151-cf575280-e558-11e9-98d9-52ee293ce5aa.png)

**Comment by jenniferlee-dsva** [comment]
@RLHecht or @peggygannon - After Nick has added the calculator widget per above, please go to http://preview-prod.vfs.va.gov/preview?nodeId=866 and proofread/review and publish if all looks good. (I updated the intro text.)

**Comment by ncksllvn** [comment]
@jenniferlee-dsva No problem, just opened a PR to remove that sentence. Should be ready soon!

**Comment by RLHecht** [comment]
@ncksllvn I can review and publish. Just let me know when it's ready.

**Comment by RLHecht** [comment]
@ncksllvn I don't see the calculator showing up on the preview page. Is this a problem if I publish it?

**Comment by ncksllvn** [comment]
Hey @RLHecht, I'm going to make a quick edit in the CMS to add the calculator!

**Comment by Karak888** [comment]
@ncksllvn @RLHecht  Has this been validated/verified yet?  Please let me know we need to have this completed by EOD tomorrow. Thanks!!

CC:  @jenniferlee-dsva

**Comment by ncksllvn** [comment]
Yep, we launched it on Friday
