### ISSUE TITLE
Access for Joshua K. Farrar

### ISSUE THREAD

**Issue by joshuakfarrar** [department-of-veterans-affairs/va.gov-team#21971]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Harvey Johnson
- Please provide your name.
   > Joshua K. Farrar
- Please Provide your email.
   > joshua.farrar@pif.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Detailed to ORMDI from GSA. React/Ruby/JavaScript developer and federal employee. I am working on a harassment reporting app for `vets-website` and cannot correctly build due to misconfigured SOCKS proxy issues.

- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfsxu2iQSWoN7lLYFOXdBIssVFJtM5vgtqmUj33q18R23gnjhioL9rNZMA0oj9Ene2zjF6IW5MbbnRb0Gj+XuRv2sr7UDVY0hmkgCtLHyBuiTi7pK6YcxT2ULGok8+VsyLFSBjAa87OK5LZwujILQnQ5fJJyk6We1Ls+7AV9PjblzqeG6gkp3Vlsx/JrEs2uKtOIdiLnjoEJTQ6vfLYxbJ6fDE1C3sTDG/pHCy047Bihii71vx+rqkQt3+rDBDmpZ5PpzdKGaVmzIYNLwsX/bgASt6KweEbS7GekSCjaXEnRMQaNV5NKw7BRfVKYQPp0caS6vb6TNC7prX10ESIaLf joshuakfarrar@FCOH2J-K1RBHV2F
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by joshuakfarrar** [comment]
I am also `joshua.farrar@gsa.gov` and `joshua.farrar1@va.gov`

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
