### ISSUE TITLE
Search UI Consistency: Global Search

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#21977]
## User Story

As a user I would like to see consistent design across all VA.gov search tools, including Global search, so that I don't have to re-learn a new pattern for each tool.

## Expected Behavior

Elements on Global search tool follow the same design patterns as much as possible - see spreadsheet linked in issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/21438

## Acceptance Criteria

- [x] Mockups for Global search completed

**Comment by MarciMcGuireGCIO** [comment]
@mgleo -  this is a new issue for designing the global search elements.  Please assign an estimate when you have a chance. If this is more than can be accomplished in a single sprint, please let me know how it should be divided up.  Thank you!

**Comment by denisecoveyduc** [comment]
Design Intent Meeting occurred on April 20 and as a result the following feedback was provided. Next steps will be extracted  based on comment and new issues will be established. 

Accessibility Feedback - #23387 
Design Feedback - #23458
IA Feedback- #23538
