### ISSUE TITLE
Search UI Consistency: Find a Facility

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#21974]
## User Story

As a user I would like to see consistent design across all VA.gov search tools, including Find a Facility, so that I don't have to re-learn a new pattern for each tool.

## Expected Behavior

Elements on Find a Facility search tool follow the same design patterns as much as possible - see spreadsheet linked in issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/21438

## Acceptance Criteria

- [ ] Mockups for Find a Facility search completed
- [ ] Accessibility has reviewed and provided feedback
- [ ] Design has reviewed and provided feedback

**Comment by mmiddaugh** [comment]
Items identified during audit: 

|	Page	|	Item in question	|	New style to be used	|	Example	|	Design system	|	Storybook or style details
|	---	|	---	|	---	|	---	|	---	|	---
|	https://www.va.gov/pittsburgh-health-care/research/	|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/8f8c5d57-c227-4f05-89b4-1c7936a26cb7)	|	Default text link style	|		|	https://design.va.gov/content-style-guide/links	|	No icon, start with "Download"
|	https://www.va.gov/pittsburgh-health-care/mission-vision/	|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/c6624cbb-b79b-452a-ba12-41abffabb9ba)	|	Underline? size? family?	|		|		|	
|	https://www.va.gov/pittsburgh-health-care/performance/	|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/086a29da-bad5-427c-a71e-ea66212d92fc)	|	Underline? size? family?	|		|		|	
|	https://www.va.gov/pittsburgh-health-care/leadership/	|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/46a8d67a-eb82-4b1e-b5b2-5033b5ec154d)	|	Underline? size? family?	|		|		|	
|	https://www.va.gov/pittsburgh-health-care/work-with-us/jobs-careers/	| ![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/1112b1b0-3060-4707-af17-25af8307c3bf)		|	active link	|		|	https://design.va.gov/components/action-links#how-to-use-other-links	|	Source Sans Pro (Bold), underlined, 16px, #004795
|	https://www.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/	|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/576bac83-3549-4a4d-bc37-4f750c80f9ce)|	Underline? size? family?			|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/3b201e93-7e15-420e-a53b-45f03eb238b2)	|	
|https://www.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/		|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/ebf7a267-63db-46de-aadb-826a306ee6d1)	|	Underline? size? family?	|		|		|	
|https://www.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/		|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/2d4d82cd-b09b-4e9b-9792-b5345fa86733)	|	Underline? size? family?	|		|		|		
|	https://www.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/psychology-internships-and-fellowships/	| ![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/94d8c774-74e2-4108-bf34-8cd5dd5def25)		|	Underline? size? family?	|		|		|		
|	https://www.va.gov/pittsburgh-health-care/research/safety-security/	|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/9ac6b597-ef72-443e-bdd0-aa469c561e8f)	|	Underline? size? family?	|		|		|	Start with "Download", add (PDF) Suggested link text: "Download Research Protocol Safety Survey ​(PDF)"
|	 https://www.va.gov/pittsburgh-health-care/research/safety-security/ ~40 instances on this page	| ![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/1eec1adb-b35e-40eb-9edf-3c13fcf96af6)		|	Default text link style	|		|	https://design.va.gov/content-style-guide/links	|	No icon, start with "Download" - Suggested link text: "Download Office Research Building ​Map (PDF)"
|	https://www.va.gov/pittsburgh-health-care/research/safety-security/ |	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/be7cc1bf-f921-4743-a8db-ae377f3f4fda)				|		|		|	https://design.va.gov/content-style-guide/links	|	Start with "Download", add (PDF)
|	https://www.va.gov/pittsburgh-health-care/research/research-professionals/	|	![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/00ff40f7-f84e-42c6-94d3-83ad91af3805)	|		|		|	https://design.va.gov/content-style-guide/links	|	Start with "Download", add (PDF) Suggested link text: "Download 2019 VA Pittsburgh Research Annual Report ​(PDF)"
|	https://www.va.gov/pittsburgh-health-care/jobs-careers/internships-fellowships/forms/	| ![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/f5a0a780-da1d-46d9-b5cd-f98ad35f9eee)		|	Problem/question: Would following styleguide make this list of forms less scannable?	|		|		|

**Comment by MarciMcGuireGCIO** [comment]
@mmiddaugh I am going to take the Decision Tools label off this since it's been de-scoped from the initial UI design intent review.  Each team that decides to implement can do so as their priorities and capacity allow.  Thanks!
