### ISSUE TITLE
Update UI for "Sign out" + add to Profile 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21986]
## Acceptance Criteria
1. On the Settings page, update the UX/UI for the **Sign out** button so it displays as a Large Button instead of a ListItem
2. Update large button common component to include a state for destructive actions:
     - Default state:
          - Border color: #CD2026
          - Background color: #ffffff
          - Copy: Mobile Body Bold, #CD2026
     - Active state (when pressed):
          - Border color: #981B1E
          - Background color: #ffffff
          - Copy: Mobile Body Bold, #981B1E
3. Update ReadMe and include new specs for the large button
4. Apply a second **Sign Out** button to the Profile page, below the ListItems

## Designs
Default state (on Settings page): https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/450009482
Active state (on Settings page): https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/450009483
Additional button on Profile: https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/450009480

## Accessibility Implementation Guidelines 

**Sign out button**
- Title= "Sign out"
- accessibilityHint= "Sign out of the VA mobile app" 
- accessibilityRole= “button”

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bridgethapner** [comment]
@msmanak tagging you here for follow-up coming out of our hand-off earlier this week since there's no corresponding UX ticket.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/6/2021 - Looks good on iOS and Android, except for Samsung has the ol' "vah" vs "Vee A" issue with the AccessibilityHint.  Also there is a minor bug logged on the text change for active state.  Text needs to match the color of the border.

#24364 and #24366
