### ISSUE TITLE
[DISCOVERY] R&S article ‘Veterans found this article helpful’ feature

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#21988]
## Problem Statement(s)
As a Veterans (or someone that supports Veterans) I want to be able to ‘recognize' content that is helpful to solving and issue or informing and tier 1 action.   This could help increase content confidence through helping more Veterans better understand the benefits they have earned.  

Explore both a mobile and desktop version.  We know that mobile is the primary method in which Veterans and those that support Veterans are using to review content and interact with content tags.  Having an optimized mobile version and share component would be ideal in improving the user experience. 

Similar models used by other platforms as an example:
![Screen Shot 2021-03-23 at 6 09 57 PM](https://user-images.githubusercontent.com/70410912/112235056-7f17f880-8c03-11eb-84a1-58d152c26bce.png)

![Screen Shot 2021-03-23 at 6 10 32 PM](https://user-images.githubusercontent.com/70410912/112235065-82ab7f80-8c03-11eb-9c7e-609aa615b191.png)

## Bet 
As a Veteran I would share articles (content) that I found impactful to other Veterans that I know and support.   

As a person that supports Veterans I would find value in sharing content with Veterans to help them answer their questions and gain the benefits they need and deserve. 

## Outcomes 
Veteran confidence increased through self discovery and source of truth content via VA.gov/resources library. 

Veterans are more informed and are able to share and receive shared content from the Resources and Support library.

## Research 

What is a strong industry standard approach? (Tools for sharing via email content). 

What tools/plugins are needed to support this approach?

Start a research and design plan for review

Collaboration cycle kickoff to begin the process and test hypothesis and bets

**Comment by FranECross** [comment]
Closing old ticket; if this resurrects as a new initiative, new documents and tickets will be created at that time.
