### ISSUE TITLE
Content updates for File upload screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#21985]
## Acceptance Criteria
1. On the **Select a file** page (when no file has been added), update the page content so it reflects the linked designs
     - Page header: "Select a file to upload for [Request Title]"
     - All content below the page header is hard-coded

**Note:** designs indicate the button label is "Select file", but maintain the existing label of "Select a file"

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447962431

## Accessibility Implementation Guidelines

- Mark "Accepted file types:" as Header 2

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Questions:

1. In the designs, the large button label is "Select file". In the app, the current label on this page _and_ the preceding page (File Upload list page) is "Select a file". Should we update the button label on both pages to "Select file", or keep both as "Select a file"?

 ![Screen Shot 2021-03-23 at 4.27.57 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/4aa66b2f-551e-4a05-ae37-1d9b43b1ada7)

**Comment by bridgethapner** [comment]
Please keep both as is in the build of "Select a file" - thank you!

**Comment by digitalken** [comment]
PASS 3/29/2021 - Looks good on Android and iOS.  Closing.
