### ISSUE TITLE
Engineering: Review 686 Dependents Work

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2201]
## Story
As a frontend engineer, I want to know how much of the existing 686c frontend code is complete, so I can gain an accurate idea of the level of effort involved, and other issues, to make this application feature complete. 

## Goals
Primarily, to fully understand work that has already been completed and map any functionality that is still outstanding.

## Tasks
- Review the 686c form [Product Outline](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Disability/Declare%20Dependent%20686) with respect to engineering  
  - [API Calls](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability/Declare%20Dependent%20686/api%20calls.md)
- Spin up the feature locally and identify what is functioning "as-is"
- Identify endpoints and data sources used currently and within previous Dependents work notes.
- Document how much of the current form is code complete
- Document the current testing environment

## Acceptance Criteria
- [x] Develop questions based on review
- [x] Run the current work locally and document results

**Comment by micahchiang** [comment]
Updated this document https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/rainbow-meeting-notes.md with some findings for the frontend in `vets-website`

**Comment by micahchiang** [comment]
@cohnjesse - feel free to update the above document as well with anything you want to add. Otherwise, this ticket can probably be closed out.
