### ISSUE TITLE
Design: General Review 686 Dependents Work

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2202]
## Task
Review the 686 [Product Outline](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Disability/Declare%20Dependent%20686) with respect to research, design and current implementation.

### Goal
Determine the general status of the current 21-686c implementation on VA.gov staging. Produce a document that presents a distillation of repository content; consolidate resources and references into easily accessible links so that team members have a quick reference to repository info.

### Acceptance Criteria
- [x] Document state of current 21-686c implementation on VA staging; include findings that delineate what needs to be done vs has been done 
- [x] Develop questions based on review

**Comment by sporeboy** [comment]
Document of finding here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/design/dependents/readme.md
