### ISSUE TITLE
VRRAP: Create VRRAP Application Framework

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22023]
As a developer, I need to create the framework for the new VRRAP application so that multiple people can work on the effort at a single time.

## Assumptions:
1. This story does not require a prod or feature flag.

## Acceptance Criteria:
1. The registry.json contains an entry for VRRAP with the following information:
    a. appName: Veteran Rapid Retraining Assistance Program	
    b. entryName: vrrap
    c. rootUrl: /vrrap
    d. vagovprod: false
    e. title: Veteran Rapid Retraining Assistance Program
    f. display_title: Veteran Rapid Retraining Assistance Program
    g. description: Form for the Veteran Rapid Retraining Assistance Program
    h. layout: page-react.html
2. The URL:
    a. Is accessible in the local, dev and staging environments.
    b. Is not accessible in the prod environment.

## Supporting Artifacts:
https://github.com/department-of-veterans-affairs/generator-vets-website

**Comment by ksantiagoBAH** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/16515

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Form is now present at https://staging.va.gov/vrrap/introduction

Closing this issue
