### ISSUE TITLE
Messages not loading in Inbox

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#22025]
### User Story
As a user, if messages aren't loading in my Inbox I want to see a message saying that in the app.

### Design
UI is here in Invision: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/448207850_Messages_Not_Loading_-_Inbox

### Notes for dev
This should display when messages aren't loading in their Inbox ([reference to unhappy paths mapping](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1614017071435/8061f2093dc4679b4b1da3ab3f20423c8f1c8f66))

**API Error:** 
```
SM 900:
Detail: ‘Mailbox Service Error
```

**Comment by melissa-lefevre** [comment]
![Error screen 22025](https://user-images.githubusercontent.com/79866060/112322765-913b7a80-8c87-11eb-80bd-4b3f1846206e.png)

**Comment by drjecker** [comment]
@bessgreen this has a UI/design for it in Invision as notes above, but doesn't have a click through for it.

**Comment by drjecker** [comment]
Reopening ticket since the phone number on this may need to change.

**Comment by drjecker** [comment]
Phone number is correct.
