### ISSUE TITLE
Content updates for Photo upload screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22045]
## Acceptance Criteria
1. On the **Take or select photos** page (when no photo has been added), update the page content below the page header so it reflects the linked designs
    - _Note: the designs show a "Back" button in the header. Keep the existing "Cancel" button that currently displays on this page._ 
2. Update content header & supporting copy
     - All copy is hard-coded

**Not included in this story:** Mobile alert w/ accessibility disclaimer. #22463

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/448032283

## Accessibility Implementation Guidelines

- Mark "Use your phone's camera to upload your files" as Header 2

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
FAIL 4/8/2021 - Not correct text copy.  Bug submitted.
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22966

**Comment by kxiao133** [comment]
my bad, i didn't realize there was a separate ticket made for the text error. Moving it back to QA on the board

**Comment by digitalken** [comment]
Blocked until I get a password for user 366.

**Comment by digitalken** [comment]
PASS 4/15/2021 - Looks good on Android and iOS.  Minor issue logged with iOS pronouncing "gov." as "governor."  Closing.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23339
