### ISSUE TITLE
VRRAP: Create schema for new application

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22049]
As a developer, I need to create a schema for the VRRAP application so that UI and spool file development can begin in parallel.

## Assumptions:
1. This work does not need to be completed behind a prod or feature flag.
2. All data collected will need to be available for inclusion in the spool file.

## Acceptance Criteria:
The schema supports capturing the following data elements with the corresponding attributes

1. Name
     a. First - string, required
     b. Middle - string
     c. Last - string, required
     d. Suffix - string
2. Date of Birth - date, required
3. Social Security Number - ssn, required
4. Email address - string, required
5. Mobile Phone number - phone
6. Alternate Phone number - phone
7. Address - address, required
    a. Country
    b. Street Address (Line 1)
    c. Street Address (Line 2)
    d. City
    e. State
    f. Postal Code
8. Direct Deposit - bankAccount
    a. Account Type
    b. Routing Number
    c. Account Number
9. Have you picked a program you’d like to attend using VRRAP? bool
10. What’s the name of the program’s provider? string
11. What’s the name of the program? string
12. What is the location of the program?
    a. City - string
    b. State - string
13. Is it an in-person or online program? (In-Person, Online, It’s both online and in-person) - ???
14. VRRAP confirmation - bool
15. Privacy policy confirmation - bool, required

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
vets-json-schema PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/568

**Comment by dmccurdybah** [comment]
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16519

**Comment by dmccurdybah** [comment]
vets-api PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6286
