### ISSUE TITLE
Setup AWS service account for Performance Dashboard

### ISSUE THREAD

**Issue by shefalinayak** [department-of-veterans-affairs/va.gov-team#22042]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_
We need an AWS service account to be able to:
- manage secrets for Performance Dashboard
- read/write to s3 buckets
  - we store our data in s3 buckets for the dashboard: 
    - s3://dsva-vetsgov-scorecard-dev
    - s3://dsva-vetsgov-scorecard-staging
    - s3://dsva-vetsgov-scorecard-prod

## Background/context/resources
_Any additional context for the reader to know, if applicable_ 
We are migrating the [Performance Dashboard](https://www.va.gov/performance-dashboard/) pipeline from Jenkins to Github Actions
repo: https://github.com/department-of-veterans-affairs/vets.gov-status
slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1616535951030400

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [ ] Please attach your team label and any other appropriate label(s) 
- [ ] Please attach the needs grooming tag if needed
- [ ] Please connect to an epic

**Comment by karlbrown-va** [comment]
@jbritt1 in terms of providing the secret to the team I think one thing you could do is just stick in into the secrets portion of the repo - what do you think? We can give you sufficient permissions if you don't have them.

**Comment by jbritt1** [comment]
> @jbritt1 in terms of providing the secret to the team I think one thing you could do is just stick in into the secrets portion of the repo - what do you think? We can give you sufficient permissions if you don't have them.

I believe that was going to be the plan / starting point. Will reach out when I get it all set up on our end.

**Comment by jbritt1** [comment]
Service account created, parameters created, secrets added to https://github.com/department-of-veterans-affairs/vets.gov-status repo. Will leave this open a bit longer in case Karl has some feedback, observes issues, etc.

**Comment by marungo** [comment]
Thank you so much for the help! We're 95% of the way there. Looks like our last step to upload the site to our s3 buckets with the `--acl public-read` flag is failing because we need `s3:PutObjectAcl` permissions. 

Here is the build that failed:
https://github.com/department-of-veterans-affairs/vets.gov-status/runs/2205010517?check_suite_focus=true

**Comment by jbritt1** [comment]
Added missing permission to service account policy, tested and verified as working in Slack (ref:https://dsva.slack.com/archives/CBU0KDSB1/p1616706501200900). Will catch the Terraform code up as this was a manual change for the test.

**Comment by jhouse-solvd** [comment]
@jbritt1 - Looks like this one can possibly be validated and closed?

**Comment by jbritt1** [comment]
Yep, think this one is good to go. Good eye! Happy to reopen if the team notices any issues. Closing.
