### ISSUE TITLE
Update Back End For Form 526 PDF Updates (if necessary)

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#22056]
Form 526 has been updated [with some minor changes](https://dsva.slack.com/archives/C5AGLBNRK/p1616592322076600?thread_ts=1616590399.073900&cid=C5AGLBNRK)

## Acceptance Criteria

- [ ] Figure out if we need to make any changes for our BE
- [ ] Make any necessary changes
- [ ] Test with EVSS? ([I believe that's what they're talking about here](https://dsva.slack.com/archives/C1VBAHWQL/p1616600693031900))

**Comment by edmangimelli** [comment]
estimate might be too small if we end up doing a lot of back and forth with the EVSS team

**Comment by annaswims** [comment]
EVSS says they'll send a document with changes.  We'll need that to get stared.
https://dsva.slack.com/archives/C1VBAHWQL/p1617111243045700?thread_ts=1616600744.033100&cid=C1VBAHWQL

**Comment by annaswims** [comment]
It looks like there are no mandatory schema changes, though some may be "nice to have"[https://app.zenhub.com/files/133843125/f7a72da4-3de0-4ef1-97e7-41dc2cc77175/download](https://app.zenhub.com/files/133843125/f7a72da4-3de0-4ef1-97e7-41dc2cc77175/download)
