### ISSUE TITLE
1990e form inaccessible using Internet Explorer on Staging

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#22051]
The introduction page for the 1990e form will not load when using Internet Explorer. This is the case whether using a direct link or accessing the form using the wizard. Possibly related to #19172

### Steps to reproduce
1. Attempt to access the 1990e form either using the wizard or [direct link](https://staging.va.gov/education/apply-for-education-benefits/application/1990E/introduction)

### Expected results
1. 1990e intro page loads

### Actual Results
![Screen Shot 2021-03-24 at 11.14.01 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/9dd6b3a3-e954-42ec-b10d-3c1fd976e6af)

**Comment by elder-joseph** [comment]
Bug was found to only be present when using a virtual machine to run Internet Explorer and is not an issue for Windows host machines.
