### ISSUE TITLE
Handle Uploads That Have Periods in Filename

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#22063]
EVSS rejects file uploads that have more than a single period in the name.
Letting EVSS reject them is no good because uploads are often async, consequently, the Veteran will never see the error (or won't see it right away).

Either strip out extra periods or convert them, or reject them earlier.

## Acceptance Criteria
- [x] Decide how to handle this (fix it or reject it sooner)
- [ ] Implement solution

### Notes

Should any of this happen on the front end?

**Comment by annaswims** [comment]
http://sentry.vfs.va.gov/organizations/vsp/issues/30424/?environment=production&project=3&query=upload+transaction%3ASidekiq%2FEVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitUploads&statsPeriod=14d
