### ISSUE TITLE
HLR Automated Alerts

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#22062]
We had an HLR incident on 2/25 that was only caught by manual checking. If we had had automated alerts set up (grafana -> slack?), we would have known about the problem sooner, and, consequently, gotten a solution deployed sooner

## Acceptance Criteria

- [ ] Decide what alerts make sense (we don't want to fill our slack channels with noise, _when_ should we stop everything we're doing to fix a problem (what error rate), etc.) and where they should go (this step might involve entire team)
- [ ] Implement Alerts
- [ ] Test it to make sure it's working

### Notes
Use 526 Grafana slack alerts (in dsva/#vsa-claims-appeals) as a guide

**Comment by annaswims** [comment]
Alerts are configured for when getting contestible issues from lighthouse or creating HLR's has more than 2 failures an hour
http://grafana.vfs.va.gov/d/qCRjZjDMk/hlr-higher-level-review?viewPanel=8&orgId=1
