### ISSUE TITLE
VRRAP: Create introduction page for form

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22068]
As a veteran, I need a way to apply for the Veteran Rapid Retraining Assistance Program so that I can receive benefits for additional training to increase my ability to try and find new employment opportunities.

## Assumptions:
None

## Acceptance Criteria
1. The introduction page is located at the URL: https://[environment].va.gov/vrrap/introduction
2. The breadcrumb of the page is: Home > Education and training > Other VA education benefits > Veteran Rapid Retraining Assistance Program
    a. Home - URL when active: https://[environment].va.gov/
    b. Education and training - URL when active: https://[environment].va.gov/education/
    c. Other VA education benefits - URL when active: https://[environment].va.gov/education/other-va-education-benefits/
3. The title of the page is: Veteran Rapid Retraining Assistance Program (VRRAP)
4. The content of the page matches that as specified in SA1.
    a. Respondent burden, OMB Control #, Expiration date should not be included at this point in time because we do not yet have that information.
5. The layout of the page matches that as specified in SA2.
6. The user has the ability to proceed to the application:
    a. While authenticated
    b. While unauthenticated.

## Supporting Artifacts:
1. [Content Doc](https://app.zenhub.com/files/133843125/b0029371-d7d7-42a7-b4ac-a0df5b083a70/download)
2. [Prototype](https://bahdigital.invisionapp.com/share/CUIAGI923MB#/screens/296058211) - Note: the prototype has not been updated to match the content doc. A similar example to use is the [10203 intro page](https://bahdigital.invisionapp.com/d/main#/console/14222205/296048628/preview)

**Comment by zurbergram** [comment]
Refactor PR (unrelated to actual changes just cleanup and tweaks related to overall form)
https://github.com/department-of-veterans-affairs/vets-website/pull/16559

**Comment by amyknox** [comment]
Per 3/31 [slack convo](https://bah-ssp.slack.com/archives/C01DEL71Q11/p1617199472025400), SaveInProgressIntro will be updated to say: “After 60 days, we’ll delete the **application** and you’ll need to start over.”

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1620&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
Closing story
