### ISSUE TITLE
Homelessness Flash for Form 526

### ISSUE THREAD

**Issue by edmangimelli** [department-of-veterans-affairs/va.gov-team#22066]
Forms can be escalated via BGS API endpoints. Lighthouse adds a _homelessness flash_ to forms when the form data indicates that the Veteran is homeless or at-risk of becoming homeless. This seems like something we should also be doing for Form 526

## Acceptance Criteria
- [x] Research adding a _homelessness flash_ to Form 526

**Comment by edmangimelli** [comment]
needs estimate

**Comment by annaswims** [comment]
this is a good place to start https://github.com/department-of-veterans-affairs/vets-api/pull/6014/files

**Comment by annaswims** [comment]
I think on a high level we know that lighthouse makes some calls to BGS with "flashes" and that they can affect priority of a claim, but I think we should have a better understanding of the implications of these flashes. 

In the [Lighthouse docs](https://developer.va.gov/explore/benefits/docs/claims?version=current) we see [the list of flashes](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/config/schemas/526.json#L23)

````
              "Agent Orange - Vietnam",
              "Amyotrophic Lateral Sclerosis",
              "Blind",
              "Blue Water Navy",
              "Formerly Homeless",
              "GW Undiagnosed Illness",
              "Hardship",
              "Homeless",
              "Medal of Honor",
              "POW",
              "Priority Processing - Veteran over age 85",
              "Purple Heart",
              "Seriously Injured/Very Seriously Injured",
              "Specially Adapted Housing Claimed",
              "Terminally Ill"
````

Some of these things can be inferred like "over 85" or are things we ask about explicitly but some may be more complex like  "GW Undiagnosed Illness"

**Comment by annaswims** [comment]
Had some discussions with Mark Greenburg and Lighthouse.  We will be able to call BGS the same way lighthouse does.  
The code to update flashes for veterans is here and is behind a feature toggle so we can try it out. 
Some flashes can be determined with the data we have, but we'll likely need to ask new questions if we want to consider all possible attributes.
https://github.com/department-of-veterans-affairs/vets-api/pull/7732

**Comment by annaswims** [comment]
I'm going to consider discovery complete and we can create new issues for next steps.
