### ISSUE TITLE
VRRAP: Create spool file entry for submissions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22085]
As an EDU team member, I need VRRAP application submissions sent to the Muskogee RPO via spool file so that they can be processed in a timely manner.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. A spool file entry is created for each VRRAP application submission in the Muskogee spool file (RPO # 351).
2. The header of the spool file document is:

> Claimant First Name - required
> Claimant Middle Initial - blank if not provided
> Claimant Last Name - required 
> Veteran's SSN - required
> Claimant's SSN - required
> Document Type - Hardcoded value: V1990S 
> Facility Code - blank line
> School Name - blank line
> Benefit Type - Hardcoded value: VRRAP

3. The body of the spool file matches that outlined in supporting artifact 1.
    a. If the applicant affirms the self attestation content, all questions in the "VRRAP Attestation questions" section have an answer of "Yes".
    b. If the applicant does not affirm the self attestation content, all questions in the "VRRAP Attestation questions" section have an answer of "No".
    c. If the applicant self attestation is null, all questions in the "VRRAP Attestation questions" section have an answer of "N/A".

## Supporting Artifacts:
1. [vrrap_mock_spool_formatv3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6213602/vrrap_mock_spool_formatv3.docx)

**Comment by delli-gatti-michael** [comment]
Local testing complete

Sample spool file (converted to txt for the sake of uploading to github):
[351_04022021_130518_vetsgov.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/6249950/351_04022021_130518_vetsgov.txt)
