### ISSUE TITLE
Create landing page of all downtime banners used on VA.gov

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2208]
As a UX designer and a content writer, I want a page that displays all the downtime banners, content, where the downtime banner is displayed and where that code lives so that I can audit the downtime banners for UX and if there are any issues, I have enough information to put in tickets for it to be fixed. 

AC:
- [ ] A page is generated (or a list if a page is too hard) of all the downtime banners/content, where it is display and where it lives in the codebase

**Comment by accbjt** [comment]
Here are the images of down time notifications. Some are notifications that are coming and there are messages that are displayed when things are down.
----------
Warning Notifications:

<img width="401" alt="Screen Shot 2019-10-10 at 1 47 44 PM" src="https://user-images.githubusercontent.com/5377648/66658897-46df4e80-ebf7-11e9-969e-a9027c50a548.png">

----------

<img width="409" alt="Screen Shot 2019-10-11 at 6 17 47 AM" src="https://user-images.githubusercontent.com/5377648/66658898-4777e500-ebf7-11e9-84c7-9e69c49ba2e0.png">

----------
<img width="652" alt="Screen Shot 2019-10-11 at 6 42 17 AM" src="https://user-images.githubusercontent.com/5377648/66658901-4777e500-ebf7-11e9-91a4-35bf1f296a89.png">

----------
<img width="405" alt="Screen Shot 2019-10-11 at 7 00 15 AM" src="https://user-images.githubusercontent.com/5377648/66658902-4777e500-ebf7-11e9-885d-5908e9c2f6a2.png">

----------
Notification when down:

<img width="1280" alt="Screen Shot 2019-10-11 at 7 11 44 AM" src="https://user-images.githubusercontent.com/5377648/66658905-48107b80-ebf7-11e9-882f-4b68fe2b5e30.png">

----------
<img width="877" alt="Screen Shot 2019-10-11 at 6 19 23 AM" src="https://user-images.githubusercontent.com/5377648/66658899-4777e500-ebf7-11e9-8748-c93cdd731c7f.png">

**Comment by accbjt** [comment]
@CrystabelReiter above is the screenshots of the down time notifications that I can find. Here is also a link the documentation on our DownTimeNotification component and how a developer uses it. It's useful because it shows you examples of the different versions that you can display.

https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/downtime-notifications/

**Comment by johnpaulashenfelter** [comment]
@andreahewitt-odd I think you can take me off this one

**Comment by peggygannon** [comment]
@johnpaulashenfelter Hello, I have a question about the downtime banners above. They follow VA.gov content style and tone, however, I'm wondering if we could give users a more actionable step in the CTA? 
Some of the notifications ask users to "check back soon," but they don't provide a timeline to do so (should they check back within a day? 24-48 hours?).

Do you know from a dev viewpoint if we're able to provide this level of detail for what is driving these messages? 

cc @andreahewitt-odd @peggygannon
