### ISSUE TITLE
No messages in Custom Folder (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22086]
## User story
As a user, if I don't have any messages in my Custom Folder, I want to see a message saying that in the app.

## Acceptance Criteria
1. Create UX/UI when a user does not have any messages in their custom folder(s)
2. Header is dynamic and should reflect the name of the custom folder:
     - "You don't have any messages in your [custom folder name] folder"
2. Below the copy, display large button: "Go to Inbox"
     - Selecting this button routes to the Inbox page
3. The following elements should persist on this page:
     - Back button (should route to the previous page, i.e. the Folders tab on the Messages page)
     - Compose a Message footer button

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447948348_Custom_Folders_-_No_Messages

## Accessibility Acceptance Criteria

- Mark "You don't have any messages in your [Custom folder name] folder" as Header 2

**Go to inbox button**
- Title= "Go to inbox"
- accessibilityHint= "view messages in your inbox" 
- accessibilityRole= “button”

## Dev Checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/8/2021 - Looks good in Android and iOS.  Closing.
