### ISSUE TITLE
SPOOL: Slack logging notifications

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#22084]
## Issue Description
Send logging from the CreateDailySpoolFiles sidekiq job to [vsa-education-logs](https://dsva.slack.com/archives/C01T05TPTQQ) to notify of how runs went

## Assumptions:
1. This work is completed behind feature flag `spool_testing_error_2`

## Acceptance Criteria
1. All logging within CreateDailySpoolFiles is sent to DEPO slack channel [#vsa-education-logs](https://dsva.slack.com/archives/C01T05TPTQQ)

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
Devops related - https://github.com/department-of-veterans-affairs/devops/pull/8785

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6284

**Comment by zurbergram** [comment]
for local testing verify that CreateDailySpoolFiles works
for staging testing after CreateDailySpoolFiles runs should see a message in [vsa-education-logs](https://dsva.slack.com/archives/C01T05TPTQQ)

**Comment by sonntag-adam** [comment]
Closing story.
