### ISSUE TITLE
CLP - Back to Top alignment 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22087]
## Issue Description
_Based on recent design review post Staging review it was identified that the back to top component, need to be align the button the right-most "column" example below.  Also discussed rounding out the right side but will need @rtwell review and approval in support_

Example: Alignment for CLP Back to Top:
![Screen Shot 2021-03-24 at 11 35 00 AM](https://user-images.githubusercontent.com/70410912/112364300-fb5e1a80-8c9b-11eb-8e45-a7422083090d.png)

[Practice Area Feedback Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20883)

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Back to top is aligned per guidance 
- [ ] Validated and tested - Back to top feature is visual and accessible per desired approach.
- [ ] End-to-end tests show 0 violations.

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
Happy to knock this ticket out but I really think the back to top component's design should be reviewed. When the back to top component is on top of just a white background I think it looks like a UI bug on desktop when the top and bottom right corners are not rounded and the component isn't centered in the viewport CC @rtwell @callen2563 What do you both think? 🙂 

![image](https://user-images.githubusercontent.com/12773166/112513606-2018c780-8d5a-11eb-99c9-8f11017b8e0f.png)

![image](https://user-images.githubusercontent.com/12773166/112513702-36bf1e80-8d5a-11eb-8013-37955cb98a71.png)

**Comment by rtwell** [comment]
thanks for considering this, but I would like to hear from Veterans that this is problematic. let's please focus on the alignment issue. thanks!

**Comment by brianalloyd** [comment]
Validated and closing.
