### ISSUE TITLE
Update label for refresh buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22109]
## Acceptance Criteria
1. On the generic error screens, update the large button labels from "Try again" to "Refresh"
2. Apply this update to the following error screens:
     - Generic error w/ Refresh #18227
     - No network connection #18231
3. Ensure that the accessibilityTitle is also updated to "Refresh"

## Screens for reference
![Screen Shot 2021-03-24 at 1.23.19 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b5c841ea-63b2-4cbb-a160-fc32b296cb00)![Screenshot_20210324-132236_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/267e9f0a-7f13-47c5-beca-58a0c0387fc0)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/2/2021 - Looks good on iOS and Android.  Closing.
