### ISSUE TITLE
"Other locations" VAMC link is broken

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22107]
## Issue Description
VAMC page integration for "other locations" is broken

![image](https://user-images.githubusercontent.com/55411834/112380175-b1cafb00-8cae-11eb-9f8d-87167bbc9c18.png)

## Steps to reproduce:

1. Visit https://www.va.gov/pittsburgh-health-care/locations/
2. Scroll down to the bottom to the "Other nearby VA locations" heading
3. Observe error message

## Expected behavior
- [ ] Other nearby VA locations are is populated with relevant facilities

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mpelzsherman** [comment]
The code was using an outdated API version (v0 instead of v1).
