### ISSUE TITLE
[FE] Profile: Cannot re-edit contact info after making a no-op save

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#22114]
Now that we gracefully allow users to make "no change" updates to contact info, there is a new bug. After you make a "no op" update, you cannot re-edit the field that was just edited until you refresh the page.

1. Click the "edit" button for a piece of existing contact info
2. Immediately hit the "update" button
3. The next attempt to "edit" again will fail silently

https://images.zenhubusercontent.com/133843125/ae95aacf-defe-4810-bc61-2860bd9d1ee0/reedit_fail.mp4

**Comment by erikphansen** [comment]
@ajakabcin another dev just ran into this bug today. It's old but I'd love to consider tackling it soon.

**Comment by tmitchellgcio** [comment]
@erikphansen I have tried all kinds of things. I cannot reproduce this behavior. https://images.zenhubusercontent.com/133843125/75600b69-4ce8-493e-8005-baab35d6810f/2021_09_16_15_41_27.mp4

**Comment by tmitchellgcio** [comment]
@ajakabcin ready for validation

**Comment by ajakabcin** [comment]
Confirmed on staging
