### ISSUE TITLE
In-App Content Review

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#22110]
## Description
VSP typically reviews content for product changes on VA.gov, as part of the [staging review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-staging-review.md).

**Date needed by**
- 4/15?

**Acceptance Criteria**

- [ ] All content in the app has been approved by Danielle
- [ ] Approval is documented in Github

## Reference Documentation
- Content review tracker: https://docs.google.com/spreadsheets/d/1USfiA2rPplfBLiccQk__YNPCY1rg9451Ojj0YLEVfXY/edit#gid=1717481343
- Mural for content review: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1614021860699/69c02be078ff1d1a882a789809db284fa1c919ab
- Invision prototype: https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/431636866_Home

## VA Reviewer
- Danielle Thierry

## Status & Tasks
- 5/14: Bridget met with Danielle and highlighted areas for her to work on, there's a spreadsheet they are working on. Not launch critical.

- 5/10: Bridget & Danielle have a worksession scheduled for Thursday, after that, about 80% of content will have been reviewed. Public websites team can't help with PR content.

- 5/3: Danielle will let us know what her capacity is to help us this week (wouldn't cover app store/marketing copy)

- 4/26: Bridget will figure out what is a priority to have Danielle look at

- 4/20 @bridgethapner to reach out to Danielle today

**4/12**
Danielle has reviewed VA mobile app's content via an Invision prototype and a Mural board. 

Coming out of a work session on 3/12 where we reviewed some questions together, we have a couple of remaining areas where we would appreciate content review across the app's features. This ticket serves to outline those areas (listed below) and shown in UI [here](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1614021860699?sender=bridget7669&key=7ddb134d-3d8c-449a-b2b7-86536362e50c): 

1. **Claims File Upload:** We would like to communicate that the file upload via camera flow is not fully accessible
2. **Claims File Upload:** FAQ / how to upload content narrative
3. **Claims File Upload:** We would like to communicate when an upload fails
4. **Onboarding screens:** Add Secure Messaging
5. **Review of Notifications Setting screen & in-app notifications UI**

Bridget reaching out to Danielle to see if she has capacity to support additional areas we identified 

Note: these are not new requests, just things we talked about on 3/12 put into a list to help clarify what's still open. Everything below the line on the Mural board can be ignored and considered complete.

**Comment by bridgethapner** [comment]
cc'ing @bessgreen and @msmanak for your awareness! Here is the ticket of prioritized content areas outside of Secure Messaging.

**Comment by bridgethapner** [comment]
@leanna-usds @ayushchak Can y'all weigh in on prioritizing areas where we most would like content expertise so we're ready if someone has time for us?

**Here are all the areas I see:** 
- Static landing page
- App store description 
- App store images
- Any remaining parts of the app (grouping this all together, Danielle has reviewed much of app but not all of it as we've developed new screens and error states since our last convo with her)
- Other external comms? Idk what these are yet

**Comment by leanna-usds** [comment]
i'd say 
1. App
2. App store description and images
3. static landing
4. other

**Comment by bridgethapner** [comment]
Thanks, @leanna-usds!

Update: 

1. App Content: @DanielleThierryUSDSVA and I are syncing this coming Thursday 5/13 to review the remaining areas in the app where we would appreciate content review and support (areas identified in ticket above & prioritized in Mural [here](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1614021860699/69c02be078ff1d1a882a789809db284fa1c919ab?sender=bridget7669)).

2. @leanna-usds @ayushchak From what I understand, the PW team can't help us with promotional content which makes sense due to the nature of this content and PW priorities. Are we good to move forward with our team entirely owning app store description and image content? If yes, I'm going to edit this ticket to be about a Content Review for the remaining areas of the app only.

**Comment by ayushchak** [comment]
Okay by me, since we basically have a first version of the assets ready - @leanna-usds, let us know what you think?

**Comment by ambikaroos** [comment]
May re open a similar ticket in the future if we have more support from Danielle's team, at the moment, we don't have a content support person
