### ISSUE TITLE
Redirects in Education based on legacy rewriting work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2211]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18635*

**Goal**
After all legacy rewriting work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
- [ ] All information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

Legacy content URL  |  Redirect to
-- | -----
www.benefits.va.gov/GIBILL/resources/benefits_resources/rate_tables.asp | /education/benefit-rates/
www.benefits.va.gov/GIBILL/comparison_chart.asp | /education/compare-benefit-programs/
https://benefits.va.gov/gibill/fgib/stem.asp | /education/about-gi-bill-benefits/post-9-11/stem-scholarship/
www.benefits.va.gov/gibill/resources/benefits_resources/rates/600_buyup.asp | /education/benefit-rates/600-buy-up-rates/
www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch35/ch35rates100118.asp | /education/benefit-rates/dea-rates/
www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch30/ch30rates100118.asp | /education/benefit-rates/montgomery-active-duty-rates/
www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch1606/ch1606rates100118.asp | /education/benefit-rates/montgomery-reserve-rates/  | /education/benefit-rates/monthly-housing-allowance-rates/
www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080119.asp | /education/benefit-rates/post-9-11-rates/
www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch1607/ch1607rates100118.asp | /education/benefit-rates/reap-rates/
www.benefits.va.gov/gibill/post911_residentraterequirements.asp | /education/benefit-rates/resident-rate-requirements/
www.benefits.va.gov/GIBILL/FGIB/Restoration.asp | /education/restore-benefit/

**Comment by mnorthuis** [comment]
Issue tracking the rewriting of the rates pages: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17828#

**Comment by MickinSahni** [comment]
PW Grooming
- Pre-vet on this, but should be easier than the Education parity vetting 
- Same treatment; do the background work while it's IN Progress but add to sprint when it's time to implement the redirects

**Comment by AkucherGCIO** [comment]
03/11/20 Sprint 17 Planning
@AnneHurley - Pre-vetting needed before Selina reaches out to Micki.

**Comment by MickinSahni** [comment]
2020-03-18 PW Grooming
* Also groomed, but needs to be prioritized. Removing `needs-grooming` label

**Comment by AnneHurley** [comment]
@MickinSahni  This does need grooming after all; several of the above new URLs have not been built in Drupal yet, so to do redirects that has to happen first. We should regroup Monday to figure out a plan. @beeyayjay  and @RLHecht  and @lunascoop  fysa

**Comment by AnneHurley** [comment]
Blocked until all pages are built in Drupal.
