### ISSUE TITLE
Bug: `Related to` field on form search results display

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#22111]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

On the forms search, when results are displayed - the `Related to `field value is not displaying the same value as the `Related to `field on the corresponding form detail landing page. 

## Steps to Reproduce
- URL: https://www.va.gov/find-forms

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

The `Related to` field value that shows on search results should match what appears on that field on its corresponding form detail landing page. 

The logic of this field is **conditional**.  It should use the same logic and data fields that the form landing page is pulling from:
1/ IF the value of this field has a value added by the editor, display that. 
2/ IF the value of this field is null or empty -- i.e., an editor has not selected a rich content value -- show the form administration data from the forms db meta data. 

## Acceptance Criteria
- [ ] _Describe the desired working behavior_ See above.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

### VA forms 10-2850 series show VHA value for `Relate to` but these should all match what the form landing page `Related to` show - "Employment or jobs at VA"

![image](https://user-images.githubusercontent.com/43381063/112381691-40e10e80-8cc1-11eb-8bd9-8df5293c5134.png)

### Example of one of the form landing pages 

![image](https://user-images.githubusercontent.com/43381063/112381969-a208e200-8cc1-11eb-9978-9e9976063621.png)

examples:
https://www.va.gov/find-forms/about-form-10-2850/
https://www.va.gov/find-forms/about-form-10-2850a/
https://www.va.gov/find-forms/about-form-10-2850c/
https://www.va.gov/find-forms/about-form-10-2850d/

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel if you can please make this your top priority tomorrow, that would be great. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel yep!

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO can you re-open -- and include screenshots to validate that this has been resolved then re-close?  I just like to have visual record, when possible, of the fix in place.   Thanks!

**Comment by MarciMcGuireGCIO** [comment]
**Issue before this fix was implemented:** 
![image](https://user-images.githubusercontent.com/73354907/113005967-ef160980-9142-11eb-8f9d-6fe5dc62d8fa.png)

**After fix was implemented:**
![image](https://user-images.githubusercontent.com/73354907/113005948-e9b8bf00-9142-11eb-9e55-954b950f1b5b.png)
