### ISSUE TITLE
No Cheetah path started events in GA Staging

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22120]
## Summary
The Analytics team is seeing `vaos-schedule-covid19-button-clicked` events coming through in the Staging data, but they aren't seeing anything for the `vaos-covid19-path-started`.

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20210301&_u.date01=20210323&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.filter=covid19&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=2500

## Steps to Reproduce
**Test User:** Any

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Select COVID-19 vaccine
3. Click Start scheduling

### Actual Result
The `vaos-covid19-path-started` doesn't fire/track in GA

### Desired Result
The `vaos-covid19-path-started` event fires and counts in GA, in addition to the `vaos-schedule-covid19-button-clicked` event.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made

**Comment by jbalboni** [comment]
@laurenernest I did some more digging on this and I think I misunderstood how this was being fired. So now I'm not sure where we should fire this `path-started` event (the ticket is correct that it's not firing, though).

In the Express Care flow, it's triggered when you continue with Express Care in the first page of that flow. For the vaccine flow, we have `vaos-covid19-start-scheduling-button-clicked` in that spot.

For the regular appointment flow, there are three different path started events and they fire when a user is going down the community care, direct schedule, or VA request parts of the flow.

I'm not sure where we want to put the vaccine one. Maybe in the same place as `vaos-covid19-start-scheduling-button-clicked`, on the Continue button of the plan ahead page?

**Comment by laurenernest** [comment]
Ok, yeah I see how this flow is a little different. Let's go with your suggestion of adding it to the Continue button of the plan ahead page. Thanks!

**Comment by jbalboni** [comment]
@laurenernest This is merged, should be testable on staging late this afternoon or Monday.
