### ISSUE TITLE
VRRAP: Autofill form with available data when user is authenticated

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22126]
As an applicant, I need the VRRAP form to pre-populate with data I have previously provided the VA so that I do not have to spend time re-entering the information that has not changed.

## Assumptions:
1. The data available is based on the profile attached to the authenticated users account.
2. vets.gov.user+205@gmail.com has direct deposit information

## Acceptance Criteria
1. If the user is authenticated, the following elements are pre-populated if the data is available:
    a. First Name
    b. Middle Name
    c. Last Name
    d. Suffix
    e. Date of Birth
    f. Social Security Number
    g. Email address
    h. Mobile Phone number
    i. Home Phone number
    j. Country
    k. Street Address (Line 1)
    l. Street Address (Line 2)
    m. City
    n. State
    o. Postal Code
    p. Account Type
    q. Routing Number
    r. Account Number

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/806df8e395ac92ce1db410f8e8eca8a3371977b6/products/education-careers/application/VRRAP/design/content-doc.md)
2. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222564/296058211/preview)

**Comment by elder-joseph** [comment]
Associated PRs:
`vets-website`: https://github.com/department-of-veterans-affairs/vets-website/pull/16697
`vets-api`: https://github.com/department-of-veterans-affairs/vets-api/pull/6490

**Comment by delli-gatti-michael** [comment]
All fields tested locally with the exception of `Mobile Phone number` & `Street Address (Line 2)`. These can only be tested once the above PR is merged due to a lack of prefill data for local builds.

**Comment by delli-gatti-michael** [comment]
Currently blocked by #22925

The above AC will need to be tested on Staging before this story is closed

**Comment by delli-gatti-michael** [comment]
PR \#2 https://github.com/department-of-veterans-affairs/vets-api/pull/6551

**Comment by delli-gatti-michael** [comment]
Closing this story and opening #23124 to cover some users' pre-fill data not populating.

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1788)
