### ISSUE TITLE
Collaboration Cycle Kickoff: vsa-education - Veterans Rapid Retraining Assistance Program (VRRAP)

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22127]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [x] VFS: Attach any available artifacts.
- [x] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/product-outline.md)
- Content Documents: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/education-careers/application/VRRAP/design
- Prototype is in progress

## Questions

**Will your work result in visible changes to the user experience?**
- [x] Yes
- [ ] No

**Is your work a new product/feature or an iteration to an existing product/feature?**
- [x] New
- [ ] Iteration

**Will your work impact only static content pages?**
- [ ] Yes
- [x] No

**Are you making changes to the visual design?**
- [x] Yes
- [ ] No

**Are you making changes to content?**
- [x] Yes
- [ ] No

**Are you making a change to the user flow?**
- [ ] Yes
- [x] No

**Are you making a change to urls, navigation, or entry points?**
- [x] Yes
- [ ] No

**Are you doing research with VA.gov users?**
- [ ] Yes
- [x ] No

**Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?**
- [ ] Yes
- [x] No

**If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?**
- [x] Yes
- [ ] No

## Additional information
Veterans Rapid Retraining Assistance Program (VRRAP) is an initiative associated with the latest round of COVID-19 relief legislation. The Whitehouse has requested that the form associated with this program be made available to Veterans on VA.gov as soon as possible (the program was effective as of 03/11/21). As such, we do not know that we will be able to incorporate findings and feedback resulting from all of recommended VSP checkpoints in advance of launch (anticipated launch is on or before 4/30/21).

**Comment by shiragoodman** [comment]
Hi @desireeturner. Thanks for completing this Collaboration Cycle Kickoff ticket. We are aware of the urgency of this effort, and are understanding if you are not able to complete the below touchpoints (this is what we'd recommend if urgency was not a factor). Please feel to reach out to our team on the #vfs-platform-support Slack channel and tag @vsp-product-support-members if you need additional support. We will do our best to accommodate.

Based on your responses above, we are recommending the following Collaboration Cycle touchpoints:

- Design Intent
- Information Architecture (IA) Request
- Analytics Request
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch:

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

The following practice areas will be included throughout the Collaboration Cycle process:
Design
Content
Information Architecture (IA)
Quality Assurance (QA)
Accessibility
Product

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by JenLJ** [comment]
Noting - PW and sitewide content teams are also involved in this effort.  They're creating the content for the introduction page to the VRRAP form (the page the user will go to before entering the form).

**Comment by dneel-bah** [comment]
Closing issue as all steps have been marked completed.
