### ISSUE TITLE
Can't reply to messages older then 45 days

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#22134]
### User Story
As a user I can't reply to a message that is older than 45 days, but would like be directed to compose a new message

#### Ideas on how we could handle this:

- Disable reply button and if a user taps it give them an option to compose a new message with info on why they can't reply.
- Hide Reply button on those messages and include an info screen that the message can not reply and suggest composing a new message
- Put alternate text in reply button and give users an info alert that they can't reply and need to compose a new message.

#### How it's currently handled:
<img src="https://images.zenhubusercontent.com/602e6bbb345265c801d416d8/bb99f556-d5c9-4106-8d8e-99aa97904b5c" width="250" alt="screenshot of current error">

**Comment by drjecker** [comment]
### Design
UI is here in Invision: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/448878465_Reply_Expired

### Notes for dev
This should display when a user tries to reply to a message that is older than 45 days. 
- Reply Toolbar Button should **not** display
- Info Alert Button should go to Compose a Message
- Headline is Mobile Body Bold
- Text is Mobile Body

API Error:
```
SM130:
detail: 'Unable to reply because the source message is expired'
```
### Copy
- Headline: **You can no longer reply to this message** 
- Paragraph: You cannot reply to a message that is older than 45 days.  If you would like to contact the sender,  compose a new message. 
- Button: Compose a Message

**Comment by drjecker** [comment]
@bessgreen this has a UI/design for it in Invision as notes above, but doesn't have a click through for it.

**Comment by bessgreen** [comment]
@drjecker if this page contains threaded messages that span multiple days: will the SM130 error get returned when the _most recent_ message is older than 45 days?

**Comment by narin** [comment]
@bessgreen @drjecker Yes only for the most recent message.  To add some additional context, the dev working on this should provide the most recent message ID when making the API call for the reply. This error message would show up if the `sentDate` of the message being replied to is > 45 days.
