### ISSUE TITLE
Redirects in Life Ins based on legacy rewriting work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2213]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18636*

**Goal**
After all legacy rewriting work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
- [ ] All information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

Legacy Page | Redirect to
-- | --
https://www.benefits.va.gov/INSURANCE/resources-contact.asp | /life-insurance/
https://www.benefits.va.gov/insurance/vgli_rates_compare_vgli.asp | /life-insurance/options-eligibility/vgli/
https://www.benefits.va.gov/insurance/tsgli-claim-questionnaire.asp | /life-insurance/options-eligibility/tsgli/
https://www.benefits.va.gov/insurance/tsgli_schedule_Schedule.asp | /life-insurance/options-eligibility/tsgli/loss-standards/
https://www.benefits.va.gov/insurance/bfcs.asp | /life-insurance//financial-counseling-and-online-will-prep/
https://www.benefits.va.gov/insurance/SOES.asp | /life-insurance/about-soes/
https://www.benefits.va.gov/insurance/lifeIns101.asp | /life-insurance/calculate-your-needs/
https://www.benefits.va.gov/insurance/introCalc.asp | /life-insurance/calculate-your-needs/
https://www.benefits.va.gov/insurance/select.asp | /life-insurance/closed-programs/
https://www.benefits.va.gov/insurance/usgli.asp | /life-insurance/closed-programs/
https://www.benefits.va.gov/insurance/vri.asp | /life-insurance/closed-programs/
https://www.benefits.va.gov/insurance/vsli.asp | /life-insurance/closed-programs/
https://www.benefits.va.gov/insurance/nsli.asp | /life-insurance/closed-programs/
https://www.benefits.va.gov/insurance/capped_term.asp | /life-insurance/closed-programs/
https://www.benefits.va.gov/insurance/plans.asp | /life-insurance/closed-programs/plans
https://www.benefits.va.gov/insurance/converting.asp | /life-insurance/convert-to-commercial-policy/
https://www.benefits.va.gov/INSURANCE/popups/non-payPOC.htm | /life-insurance/convert-to-commercial-policy/
https://www.benefits.va.gov/insurance/dividends_options.asp | /life-insurance/dividend-payment-options/
https://www.benefits.va.gov/insurance/vgli_auto_pay.asp | /life-insurance/enroll-auto-pay/
https://www.benefits.va.gov/INSURANCE/file_death_claim.asp | /life-insurance/file-claim/
https://www.benefits.va.gov/insurance/sglivgli.asp | /life-insurance/file-claim/
https://www.benefits.va.gov/insurance/OPA.asp | /life-insurance/manage-your-policy/
https://www.benefits.va.gov/insurance/choose.asp | /life-insurance/manage-your-policy/
https://www.benefits.va.gov/insurance/uninsurable.asp | /life-insurance/uninsurable-medical-conditions/
https://www.benefits.va.gov/insurance/updatebene.asp | /life-insurance/update-beneficiaries/

**Comment by mnorthuis** [comment]
Issues tracking rewriting work:

Myths and rumors page: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17955
Convert to commercial policy: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17956

**Comment by MickinSahni** [comment]
PW Grooming 
- Pre-vet background work before committing to a given sprint

**Comment by AnneHurley** [comment]
@lwalsh617  @mnorthuis  @lunascoop  @MickinSahni  Laura - assigning this to you to do content audit between legacy pages and new pages. Let me know if you find any missing pages, and/or have any other questions. And fine to just leave me on the ticket too so I can help if you need me to.

**Comment by lwalsh617** [comment]
Update -- I reviewed urls and found many missing (pages not live). See attached Word doc for details. 
[Redirects Insurance.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4457200/Redirects.Insurance.docx)

Spoke with @AnneHurley and @RLHecht - Randi found that pages were built in GH, never moved to Drupal and that copy is in draft form.

Here are Randi's notes from Slack:
Here is the life insurance epic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/18105
And here's one ticket that shows that all the life insurance rewrites are in a rough first draft: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/18843
app.zenhub.comapp.zenhub.com

**Comment by mnorthuis** [comment]
Some redirects handled in this issue: https://app.zenhub.com/workspaces/vsp---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/19892

**Comment by mnorthuis** [comment]
Updates now being handled here: https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/50620

closing this older ticket
