### ISSUE TITLE
Documentation Update - Fix links on /login/ github

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#22140]
Many of the links self refer on the following page:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/login

We should try to update the documentation in this folder, consider moving it to confluence, but at minimum update the links (or remove the links).

**Comment by nsoutouras** [comment]
12/13/21 Planning - Work done, ticket was not closed.
