### ISSUE TITLE
[Due on 03/02] Redirect Request: Housing legacy rewriting work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2214]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo - original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18295*

**Goal**
After all legacy rewriting work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
### Steps to complete
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

Current URL  |  Redirect to
-- | --
https://www.benefits.va.gov/homeloans/resources_veteran.asp | /housing-assistance/home-loans/home-buying-process/
https://www.benefits.va.gov/homeloans/purchaseco_loan_fee.asp | /housing-assistance/home-loans/funding-fee-and-closing-costs/
https://www.benefits.va.gov/homeloans/purchaseco_loan_limits.asp | /housing-assistance/home-loans/loan-limits/

**Comment by mnorthuis** [comment]
Issues tracking rewriting work: 

Funding fee and loan costs page: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17865
Loan limits page: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18128
Buying a home page: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18129

**Comment by MickinSahni** [comment]
2020-02-19 PW Grooming
- Ready for Mikki to vet these pages and assign redirect implementation [back to] public websites via this ticket

**Comment by mnorthuis** [comment]
@lunascoop These redirects are vetted and ready to go once stakeholders and your team are ready.

**Comment by lunascoop** [comment]
@ncksllvn stakeholder comm has been sent. Redirect implementation date is **03/02**.

**Comment by ncksllvn** [comment]
PR merged, should go live today

**Comment by AkucherGCIO** [comment]
03/02/20 Pw standup
Selina will validate and close this ticket.

**Comment by lunascoop** [comment]
Redirects were implemented successfully. Closing ticket and notifying stakeholders.
