### ISSUE TITLE
[Research] Propose first research project

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22144]
## Issue Description
_As part of the integration of the new researcher on the Unauth/PW crew a summary of projects and potential research opportunities was provide but not prioritized.  Please review and propose first research project_

[Research Document for Reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-we-work/potential-research-for-unauth.md)

## Acceptance Criteria
- [x] Review research questions document, Veteran tasks, secondary research findings
- [x] Draft research plan 
- [x] Share plan with PO, PMs, Shawna, Meg Peters, Lauryl,  Josh & Angela, and incorporate their feedback 
- [x] Discuss recruiting and launch with Lauren
- [ ] Start collaboration with VSP (if needed)--NOT NEEDED
- [x] Work with PM to build research tickets to account for work and support

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cindymerrill** [comment]
@brianalloyd What does "Review unauth portfolio research document" mean? Are you referring to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-we-work/research-opportunties.md? I'd like to reference the list of research questions that I'm compiling: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-we-work/potential-research-for-unauth.md

**Comment by brianalloyd** [comment]
@cindymerrill yes, that was the document, wasn't sure of title.  Thanks for the follow up.

**Comment by cindymerrill** [comment]
I've shared my high-level research idea with John, and he was supportive. The research plan is targeted to complete by April 9, which will be next sprint, not this one. So should this ticket be moved out of this sprint and into the next one, @brianalloyd ?

**Comment by cindymerrill** [comment]
Started writing a research plan (only partway through): https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/202104-baseline-wayfinding/research-plan.md

**Comment by cindymerrill** [comment]
Finished first draft of research plan. Shared with Lauryl and got some feedback. Also shared with John, Meg, and Shawna. Waiting to see what feedback I get from them before sharing more widely.

**Comment by cindymerrill** [comment]
Revised some of the research plan per feedback from Meg Peters. John shared it with the search team; no feedback from there. Will hear Shawna's feedback and discuss with her, John, and Meg on Thursday (4/15).

**Comment by cindymerrill** [comment]
Revised research plan a bit with Shawn's feedback.

**Comment by cindymerrill** [comment]
Revised to incorporate feedback from Shawna, Meg, and Lauryl. Shared with PMs, and Josh & Angela for their feedback. Plan to share with Lauren by the end of the day Friday to launch recruiting.

**Comment by cindymerrill** [comment]
Revised to incorporate feedback from Josh and Angela. Plan to share with Lauren first thing on Monday morning to launch recruiting.

**Comment by cindymerrill** [comment]
All done with Acceptance Criteria, so closing ticket.

**Comment by cindymerrill** [comment]
Renamed ticket for clarity and reusability for cloning for future research studies
