### ISSUE TITLE
[Research] Summarize findings on Veterans’ pain points and top tasks

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22143]
## Description 
_Summarize findings on 'Veterans’ pain points and top tasks.  Place findings in GH Research document that can be reviewed by supporting teams_

## Acceptable Criteria
- [x] Conduct secondary research on Veterans' tasks and pain points with VA.gov
- [x] Provide a summary document detailing findings for VFS team consumption
- [x] Place document in an accessible location such as Zenhub/Github

**Comment by cindymerrill** [comment]
Here's my working spreadsheet in Google Sheets: https://docs.google.com/spreadsheets/d/1bg5v4uxwFVNR9bIC5nsnJ9cdrdTNjXet8d-ONYTjeCE/edit?usp=sharing

I'm currently reviewing resources listed in **Next Steps** worksheet and collecting Veteran tasks in the **Tasks** worksheet, pain points in the **Pain Points** worksheet, and relevant research findings in the **Past Research Findings** worksheet.

**Comment by cindymerrill** [comment]
Reviewed a LOT of resources today. Not done yet, but made good progress.

**Comment by cindymerrill** [comment]
Scheduled a meeting on Monday with Meg Peters and Shawna to go over my list of top tasks

**Comment by cindymerrill** [comment]
Finished reviewing most resources and compiled [Veteran task list](**url**). Not many pain points found, but collected them plus research and analytics findings [here](https://docs.google.com/spreadsheets/d/1bg5v4uxwFVNR9bIC5nsnJ9cdrdTNjXet8d-ONYTjeCE/edit?usp=sharing).

**Comment by cindymerrill** [comment]
Posted spreadsheet of **Veteran tasks** to Github in new research folder in public websites: 
va.gov-team/products/public-websites/research/[Veteran Tasks on VA.gov.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/Veteran%20Tasks%20on%20VA.gov.xlsx)

Also posted spreadsheet containing **Veteran pain points and other research findings** in the research folder:
 va.gov-team/products/public-websites/research/[Veteran Pain Points and Research Findings on VA.gov.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/research/Veteran%20Pain%20Points%20and%20Research%20Findings%20on%20VA.gov.xlsx)

So this ticket is now complete.

**Comment by cindymerrill** [comment]
Closing ticket since done and doesn't need validating
