### ISSUE TITLE
Researcher to gain access to and train on Google Analytics, DOMO

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22141]
## Description
The intent of this ticket is for Cindy, our new researcher to gain access to and train on Google Analytics/DOMO in support of research activities on the PW/Unauth Crew VFS team space.

## Acceptable Criteria
- [x] Gain Access to Google Analytics/DOMO
- [x] Training and Feel confident with toolset
- [x] Begin to explore big data via DOMO/GA
- [x] Follow up with data assessment and impressions from review

**Comment by cindymerrill** [comment]
I just logged into Google Analytics and DOMO, but I don't know where to start. I submitted a request for training in both, but I'm wondering where the VA.gov dashboards are for starters. Can you please point me to them, @brianalloyd ?

**Comment by cindymerrill** [comment]
Scheduled 1:1's with @brianalloyd , Denise, and Marci to learn about the dashboards they use.

**Comment by cindymerrill** [comment]
Met with Denise and then with Brian to see the dashboards they use, and discovered that I don't have access to them. @brianalloyd is planning to reach out to someone on the analytics team to try to get me the appropriate access. Planning to meet with Marci on Monday.

**Comment by brianalloyd** [comment]
@joanneesteban wondering if you could help ensure Cindy has access to all unauth portfolio dashboards (Resources and Support, Find a Form and Search) in DOMO.  Also it looks like she's not able to link to things in Google Analytics and was wondering if you could also assist on that front as well.  TIA.

**Comment by cindymerrill** [comment]
Today I was able to open Marci's Find a Form dashboard on DOMO (https://va-gov.domo.com/page/1785082329?userId=1492817975), but was unable to open anything of hers in Google Analytics. So, I'm still having access issues, but for the time being, I'm getting some analytics data from other people. Would like to get this fixed eventually. 

This ticket should move into the next sprint without being closed, @brianalloyd .

**Comment by cindymerrill** [comment]
Some diagnostics are going on with the analytics team in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/20168. Today my GA account was deleted and re-added, but I still can't see reports shared with me.

**Comment by cindymerrill** [comment]
Meeting with analytics team scheduled for Wed April 7 to show them what's going on.

**Comment by cindymerrill** [comment]
Had a good meeting today with Lauren Simpson and Jon Wehausen. Lauren gave me access to one DOMO dashboard, and I followed up in the ticket to request access to one more. For Google Analytics, Lauren and Jon gave said that my login problem was unusual but was resolved by creating a new sign-in in Chrome for GA.

Now I should be able to browse analytics.

**Comment by cindymerrill** [comment]
Granted access to requested DOMO dashboard. Requested training but haven't heard anything back yet.

**Comment by cindymerrill** [comment]
Received training links for GA and DOMO. Plan to go through them.

**Comment by cindymerrill** [comment]
Looking for analytics data on VA.gov home page links. Discussed with Kelson in person, with Ryan over slack, and posted to #vfs-analytics.

**Comment by cindymerrill** [comment]
Talked with Brian Martin to get help with analytics for VA.gov home page links. Also asked about scrolling behavior, and submitted a ticket for this.

**Comment by brianalloyd** [comment]
Closing
