### ISSUE TITLE
Redirects in Burials based on legacy rewriting work

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#2215]
**User Story**
As user of VA.gov, if I click on a link or option for a legacy content page, I want to be automatically redirected to the new updated content page, so that I am always seeing the most updated, single source of truth for benefits information. 

*Issue copied from vets.gov-team repo original issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18852*

**Goal**
After all legacy rewriting work is complete, approved and live, the corresponding legacy pages are  redirected to the new versions. 

**Definition of Done:**
- [x] Determine if all parity changes are complete/live and log tickets that track the approval status
- [x] Validate previously documented redirects and update as necessary
- [x] Create a new parity redirect issue in va.gov-team repo with the list of redirects and reference the original issue and the content approval ticket
- [x] Close the old issues in vets.gov-team repo and reference the new issue in va.gov-team repo
- [x] Communicate upcoming redirects to stakeholders prior to implementing
- [ ] Assign out tickets to front-end or devops as appropriate
- [ ] Validate redirects in prod and update documentation when complete

Current Legacy URL  |  Redirect to
-- | --
~https://benefits.va.gov/Compensation/current_rates_dic.asp~ | ~/burials-memorials/survivor-dic-rates/~
~https://benefits.va.gov/COMPENSATION/resources-rates-read-dic.asp~ | ~/burials-memorials/survivor-dic-rates/~
~https://benefits.va.gov/Pension/current_rates_Parents_DIC_pen.asp~ | ~/burials-memorials/parent-dic-rates/~
~https://www.benefits.va.gov/COMPENSATION/resources-rates-read-parentsdic.asp~ | ~/burials-memorials/parent-dic-rates/~
www.cem.va.gov/cem/burial_benefits/burial_at_sea.asp | /burials-memorials/eligibility/burial-at-sea/
https://www.cem.va.gov/cem/burial_benefits/private_cemetery.asp | /burials-memorials/eligibility/burial-in-private-cemetery/
~https://www.cem.va.gov/cem/hmm/types.asp~ | ~/burials-memorials/memorial-items/headstones-markers-medallions/types-inscriptions-emblems/~
~https://www.cem.va.gov/cem/hmm/pre_WWI_era.asp~ | ~/burials-memorials/memorial-items/headstones-markers-medallions/types-inscriptions-emblems/~
~https://www.cem.va.gov/cem/hmm/abbreviations.asp~ | ~/burials-memorials/memorial-items/headstones-markers-medallions/types-inscriptions-emblems/~
~https://www.cem.va.gov/cem/hmm/emblems.asp~ | ~/burials-memorials/memorial-items/headstones-markers-medallions/types-inscriptions-emblems/~
https://www.cem.va.gov/cem/hmm/replacements.asp | /burials-memorials/memorial-items/headstones-markers-medallions/
https://www.cem.va.gov/cem/cems/index.asp | /burials-memorials/find-a-cemetery/

**Comment by mnorthuis** [comment]
DIC Rewriting: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1727

**Comment by mnorthuis** [comment]
Sent list of redirects to Jen Lee for communication to stakeholders on 10/18.

**Comment by Karak888** [comment]
ready need FE engineer to implement redirects. @AnneHurley to send copy to @mnorthuis and @jen

**Comment by mnorthuis** [comment]
@Karak888 none of this content appears to be live yet, still blocked.

**Comment by Karak888** [comment]
needs FE engineering support to start this.

**Comment by AnneHurley** [comment]
[Updated list of Burials redirects URLS]
(https://app.zenhub.com/files/133843125/6ce0e045-c833-4452-a68c-891bd2544270/download)
@jenniferlee-dsva @mnorthuis  FYI I am sending this revised word doc to James in Burials. He can check the top list of redirected URLs, which should all be live.

The second part of the list is of the headstone, memorials, and markers pages, many with a lot of images, which we are going to review with @mnorthuis  and @peggygannon to see whether we can adapt the Pittsburgh clinic image template could work for this.

@Karak888  FYI

**Comment by jen** [comment]
Hi, You have the wrong Jen on this thread. I am Jen Burke = @jen.

**Comment by AnneHurley** [comment]
@mnorthuis @RLHecht @Karak888 

Legacy pages we are keeping because they contain images:
https://www.cem.va.gov/cem/hmm/types.asp
https://www.cem.va.gov/cem/hmm/pre_WWI_era.asp
https://www.cem.va.gov/cem/hmm/emblems.asp

These pages live under :
HMM Pages: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18965, new issue #3020

**Comment by Karak888** [comment]
are in Drupal but not live.  Will wait for @jenniferlee-dsva to get together with @AnneHurley :CC @RLHecht @lunascoop .

**Comment by AnneHurley** [comment]
@mnorthuis @Karak888 @RLHecht  All Burials redirects are mapped and ready to go live. These are the only Team Site pages we are keeping on "cem.va.gov" because they have images:

1. Types https://www.cem.va.gov/cem/hmm/types.asp
2. Pre WWI era https://www.cem.va.gov/cem/hmm/pre_WWI_era.asp
3. Emblems https://www.cem.va.gov/cem/hmm/emblems.asp

4. Replacements: https://www.cem.va.gov/cem/hmm/replacements.asp, has been included in the main HMM page, and approved by SMEs. (#3020 https://github.com/department-of-veterans-affairs/va.gov-team/issues/3020). This ^ legacy URL should redirect to https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/

5. Abbreviations page is in discussion with SMEs. No decision yet on whether to build accordions of this info, or to use functionality from the Yellow Ribbon tool. For now we will continue to use https://www.cem.va.gov/cem/hmm/abbreviations.asp. But this will retire as soon as we can gather the PDF information into a user friendly experience.

6. Find a cemetery -  https://www.cem.va.gov/cem/burial_benefits/private_cemetery.asp On hold for moving until medical center finder functionality is available for us, per @jenniferlee-dsva.

**Comment by mnorthuis** [comment]
@AnneHurley Can you go ahead and submit a redirect request with the list of pages that you want to have redirected so we have clean direction for Nick?

**Comment by Karak888** [comment]
@AnneHurley to send @Karak888 URL's once pages have been rewritten and approved by SMEs.  Some redirects will be on hold as to how to get content into drupal because of images.

**Comment by AnneHurley** [comment]
@mnorthuis @RLHecht  @Karak888 @ncksllvn  See revised Burials redirect URLs. @RLHecht  I believe we have pushed live all the pages we had finished, which should be the full list of all the ones we can do now. The list shows:

[Burials URLs redirect list-January 2020]
(https://app.zenhub.com/files/133843125/86d0df0c-a651-44df-9735-e107eac7f51e/download)- Some Cem.va.gov pages, with images, we will need to keep till we can do images in Drupal
- The Cemetery finder page, on hold for us until Medical Center team has a "find a medical center" tool functionality we can repurpose for this
- The list of approved headstone abbreviations, currently a page with lots of info on PDFs. Stakeholders agree we need to revisit content strategy for pulling this into into Drupal so it's searchable; they would like our recommendations.

**Comment by jen** [comment]
Hi, I’m @jen, but I’m not the Jen you are attempting to include here. —Jen

**Comment by mnorthuis** [comment]
@AnneHurley the link above does not work for me, can you please add the URLs to be redirected to this ticket?  So much back and forth on this one and I want to be crystal clear on what is done and what is not.  :-)

**Comment by AnneHurley** [comment]
[Redirects doc]
(https://app.zenhub.com/files/133843125/e622cdd1-dc34-4119-91d7-39338d516bd2/download)
@RLHecht @mnorthuis 
This should work.

**Comment by mnorthuis** [comment]
Edits needed:
- Please change the title - these redirects include both the parity and the legacy rewriting work.  This is a small nuance, but totally confused me for a bit.
- The last URL in your doc for the legacy "replacements" page is incorrect, that should be redirecting to main HMM page where we put that content: www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/
- Regarding the second to the last legacy url for "need.asp", this one is a bit more complicated and I think we should break it out.  It requires changing the URL of an existing page in drupal, redirecting the old URL, updating old redirects and redirecting this one to the new URL ...like we did with DIC content
- For the burial at sea and burial in private cemetery pages, Randi pinged me about these - the redirects listed here are correct, but I don't think the pages were launched with the correct URLs, so we need to confirm that

**Comment by mnorthuis** [comment]
Please submit a redirect request ticket for the complete list of redirects and I will close this issue.

**Comment by mnorthuis** [comment]
All but 1 of the URLs in this ticket have been handled in a new issue #4645 . 
The redirect for https://www.cem.va.gov/cem/cems/index.asp is postponed until direction for that page is determined.  That work is tracked in #3021 and a redirect ticket for that URL can be created when ready.  
Closing this to reduce clutter.
