### ISSUE TITLE
Liquid Template Testing Tool: Log errors when fixture contains invalid json

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#22152]
## Issue Description
When there’s an error in the `JSON` fixture a unit test fails with the following error, which isn't helpful:

```
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

As an engineer using the Liquid Template Testing Tool, it would be helpful to have an additional error logged to the console that explicitly states why the error occurred.

---
## Tasks
- [x] Log the error when there's an error in the `JSON` fixture

## Acceptance Criteria
- [x] An additional error will be logged to the console that explicitly states why the error occurred when there's an error in the `JSON` fixture

**Comment by holdenhinkle** [comment]
PR submitted - https://github.com/department-of-veterans-affairs/vets-website/pull/16524

**Comment by pjhill** [comment]
So long invalid fixtures!
