### ISSUE TITLE
Design Intent re-Discovery

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#22153]
## Issue Description
The Design Intent touchpoint in the Collaboration Cycle seems to have lost it's way over the last couple months. It appears that VFS teams, VSP and OCTO are not in alignment with regards to the intent of this meeting. Some questions that have been asked recently include:

- What are VFS team expectations of a Design Intent? 
- What is Ryan Thurlwell’s expectations of a Design Intent? (VSP Design tends to focus on the UI, while Ryan's focus has been on the UX)
- Should the Design Intent be a required meeting or optional?
   - What criteria would we use to determine who should be required?
- Should we extend the meeting to 45 minutes? Some meetings lately have exceeded the 30 minute mark.
- What is our teams role at the Design Intent meeting? Should we be providing critical feedback this early on?
- Should teams have a Design Intent meeting prior to meeting with Sitewide Content team? 
- Should platform give content feedback if they haven't synced with Sitewide Content team?
- How do the Sitewide Content teams Content Brief process and our Design Intent Process align?
- Feedback may differ in a synchronous review vs. asynchronous review. Is that acceptable?
- Who should be involved in a Design Intent? 
- what artifacts should be submitted/shared at a Design Intent? low fi vs. hi fi mockups?
- For IA, teams should have high levels flows drafted.

[Current guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-design-intent.md) on the Design Intent touchpoint.

How might we ensure that the Design Intent touchpoint meets the needs of VFS teams?

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by 1Copenut** [comment]
Some thoughts loosely rallied around your bullet points @shiragoodman:

* The Design Intent meeting should be required. WCAG2.1 is going to put renewed emphasis on mobile-first design and plain-language content. If we wait to make these type of advisements (must have mobile prototypes, accessible link text, unclear text content) to midpoint or staging review, we're too late.
* This would give us a chance to cross-link accessibility with design. We could create a design standard that requires mobile-first comps to review (whether lo-fi, hi-fi, something in between) and back it up with accessibility standards.
* I think we could work closely with Sitewide Content in regard to content brief and our design intent plan. When we get the accessibility testing plan up and running, these could be paired with design artifacts to give a good picture of what the team is going to build, what they're going to say, and how they're going to approach accessibility verification.
