### ISSUE TITLE
Research: Make E2E & a11y tests run faster

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#22163]
>How might we improve execution times for E2E and a11y tests in the build pipeline?

Ideas:

- Compare speed of signing up and/or logging in via the UI compared to signing up and/or logging in the e2e tests
- Research how many e2e tests are signing up and/or logging in via the UI

**Comment by pjhill** [comment]
Additional ideas for consideration:
* Does breaking up the sitemap a11y test in consideration of future or current parallelization make sense?
* Does converting the Nightwatch sitemap a11y tests to Cypress get us any speed?
* Is there some simple way of parallelizing the Cypress E2E test execution that doesn't rely on an additional tool such as Cypress Dashboard?

**Comment by billfienberg** [comment]
## Research how many e2e tests are signing up and/or logging in via the UI

### Cypress Tests (files with `*.cypress.spec.js` extension)

There are currently [126 search results](https://github.com/department-of-veterans-affairs/vets-website/search?q=filename%3Acypress.spec.js) for files with with the `.cypress.spec.js` extension (`filename:cypress.spec.js`)

### Nightwatch Tests (files with `*.e2e.spec.js` extension)

There are currently [49 search results](https://github.com/department-of-veterans-affairs/vets-website/search?q=filename%3Ae2e.spec.js) for files with with the `.e2e.spec.js` extension (`e2e.spec.js`)

**Comment by billfienberg** [comment]
💡 

Set up separate npm scripts for each app, and use [`npm-run-all`](https://github.com/mysticatea/npm-run-all) to run them in parallel. 

Kent C Dodds uses `npm-run-all` in his [Cypress Testing Workshop](https://github.com/kentcdodds/cypress-testing-workshop/blob/2113c0fafd48868bd420cebb9f5a762b17698a32/package.json#L25).

**Comment by billfienberg** [comment]
💡 cache dependencies between builds. 

https://github.com/actions/cache

**Comment by billfienberg** [comment]
Notes from pairing session with @aubreyarcangel 

>If you need reproducible dependencies, which is usually the case with the continuous integration systems, you should pass  `--frozen-lockfile` flag. - https://classic.yarnpkg.com/en/docs/cli/install/

## Initial `yarn install --frozen-lockfile` time: 2:56s

![image](https://user-images.githubusercontent.com/6130520/113314081-86a96280-92d1-11eb-8a61-7bda9cbd180b.png)

## Subsequent `yarn install --frozen-lockfile` time: 2:07s

![image](https://user-images.githubusercontent.com/6130520/113314142-97f26f00-92d1-11eb-9aad-d0664ffd01d8.png)

**Comment by billfienberg** [comment]
💡  cache the `.content` folder between builds. 

Some PRs may need fresh content, but I wager a non-trivial number of PRs don't need fresh content, and could build with cached content. 

I wonder if it would be feasible to attempt building via the cached content first, and then pull the latest content if the build fails when using the cached content. 

It looks like it takes 192500ms/192.5 seconds/3:12 minutes to fetch the content. That might be a good place to trim some time off the build. 

![image](https://user-images.githubusercontent.com/6130520/113328153-7e592380-92e1-11eb-9d63-4e2714a7175a.png)

**Comment by billfienberg** [comment]
It looks like the `21-526EZ disability compensation claim form` test is taking over 7 minutes (429168 / 1000 / 60 = 7.15) by itself

```
[2021-04-05T15:46:51.431Z]   21-526EZ disability compensation claim form
[2021-04-05T15:46:51.431Z]     full-781-781a-8940-test.json
[2021-04-05T15:54:12.942Z]       ✓ fills the form (429168ms)
```

Source: http://jenkins.vfs.va.gov/blue/rest/organizations/jenkins/pipelines/testing/pipelines/vets-website/branches/fl%252Frefactor_search_this_area_button/runs/4/nodes/151/steps/153/log/?start=0

**Comment by pjhill** [comment]
Research into Nightwatch and Cypress speed-ups has been completed.
