### ISSUE TITLE
Wrong link under Product Management > Platform collaboration point tracker

### ISSUE THREAD

**Issue by leahbannon2** [department-of-veterans-affairs/va.gov-team#22166]
On [the front page](https://department-of-veterans-affairs.github.io/va.gov-team/), the link under Product Management titled Platform collaboration point tracker goes [here](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) but it should go [here](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886).

You can verify this by clicking on the current, wrong link -- it directs people to the correct link.

**Comment by gmaciolek** [comment]
Hi Leah, Thanks for pointing this out! We are in the process of migrating our documentation to our [Platfom website](https://depo-platform-documentation.scrollhelp.site/).  We're no longer using the front page you linked to. However, the collaboration point tracker link was also wrong on the new site. I updated the link on the Platform website.

Note: The Product Support team hasn't migrated their actual content to the Platform website yet, so it's still linking out to GitHub. They will be doing so soon. 

CC @shiragoodman

**Comment by shiragoodman** [comment]
thanks @gmaciolek !
