### ISSUE TITLE
Standardized Components - Custom Dimensions + Metric

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#22168]
## Description
- In order to most easily capture the utilization of our design system standardized events from Google Analytics, we would like to setup: 
1) A custom metric that increments with each interaction triggered by our data layer development 
2) A custom dimension dimension that determines what version of the design system component library the system is on (i.e `'2.1.0'`)
3) A custom dimension that captures the GTM container version number (_for auditing any GTM changes that may have also occurred_)
4) A custom dimension that consistently collects the click URL with every hit stripping all additional query parameters. 

## Acceptance Criteria
- [x] Allocate and enable a Google Analytics custom metric to increment by 1 with each time an interaction with an event source of `component-library` is generated
   - This metric should ONLY increment for events the analytics and insights team has setup
- [x] Allocate and enable a Google Analytics custom dimension to capture the component library version number from the `JSON` package
- [x] Allocate and enable a Google Analytics custom dimension to capture the GTM container version number
- [x] Allocate and enable a Google Analytics custom dimension to consistently collect the click URL minus any additional query parameters 
- [x] Make the configuration changes within Google Tag Manager to as part of the Google Analytics settings variable name "Base Configuration"

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@bsmartin-ep @laurensimpson14 

Please find workspace to QA here: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000481

### Notes 
- It may be a good idea to publish through environments to staging first to see how this data starts to look in our non prod property
- @bsmartin-ep In unit testing it looks I was already seeing a refresh of `event-source` within the data layer 👍 
![image](https://user-images.githubusercontent.com/48527022/113413211-1873a700-9388-11eb-8abc-a7f4fa7944aa.png)


### Next Steps 
- @laurensimpson14 or @bsmartin-ep to QA GTM workspace

**Comment by laurensimpson14** [comment]
@jonwehausen Everything looks good to be published here. The only thing I noticed was that the "Container Version Number" is being set as `QUICK_PREVIEW` rather than the version number. We'll have to check it again once it's published.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

So this is definitely possible.  We can read the `package.json` file like any other and pull the component-library version:

```js

      import packageJSON from '../../../package.json';

----

      // Get component-library version from package.json
      const dependencies = packageJSON.dependencies;

      const componentLibraryVersion =
        Object.prototype.hasOwnProperty.call(
          dependencies,
          '@department-of-veterans-affairs/component-library',
        ) && dependencies['@department-of-veterans-affairs/component-library'];

      const dataLayer = {
        event: action.event,
        'event-source': 'component-library',
        'component-library-version': componentLibraryVersion,
      };
```

...but I'm a little worried about how expensive this would be to run on every interaction.  Doing some discovery now on how to bank this in some sort of env variable on build.

**Comment by jonwehausen** [comment]
@laurensimpson14 I have branched out the container version number changes into their own workspace and published to dev+staging. 

In order to test this, we can now fire any event within staging.va.gov and using GA console debug (not preview mode) we can see the value populate. 

Once your QA is added here we can then finish that portion by publishing GTM version `389` to production. 

![image](https://user-images.githubusercontent.com/48527022/114441017-da9d2c80-9b98-11eb-971b-6325a4cff0c8.png)

Then we can test + document the remaining parts of the acceptance criteria in this workspace: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000481

**Comment by laurensimpson14** [comment]
@jonwehausen I'm seeing the GTM version being collected in staging (see photo below). 

![image](https://user-images.githubusercontent.com/80417436/114450207-babf3600-9ba3-11eb-85a6-8548b67e7d7e.png)

**Comment by jonwehausen** [comment]
### Update
- The GTM container for this work has been published
- @bsmartin-ep Can you provide an update on the `component-library-version` DL variable? Are you able to use the GH issue or do you need a separate one for your PR? 
   - _The work has been published to begin collecting this when the variable becomes available_

**Comment by jonwehausen** [comment]
Remaining PR: https://github.com/department-of-veterans-affairs/component-library/pull/76#pullrequestreview-642367494

**Comment by bsmartin-ep** [comment]
Looking good.

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension133&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table-dataTable.sortColumnName=analytics.customDimension133&explorer-table-dataTable.sortDescending=true

![image](https://user-images.githubusercontent.com/62304138/116316550-1d0d5e80-a780-11eb-930e-98326097c46f.png)


Closing.
