### ISSUE TITLE
Content Request from vsa-education

### ISSUE THREAD

**Issue by JenLJ** [department-of-veterans-affairs/va.gov-team#22161]
## Why you're here 
President Biden created the Veteran Rapid Retraining Assistance Program (VRRAP) to aid thousands of Veterans are unemployed due to COVID-19. Veterans who meet 6 specific criteria are eligible for VRRAP funding to retrain in high-demand careers. To apply for VRRAP funding, they need to submit an application through VA.gov. Our team is releasing this form on a rapid deadline (4-5 weeks).

### Content support for:
- Unauthenticated (static) VA.gov pages

### Additional support

- Sitewide content review/edit of the intro page.
- Sitewide content review/edit of the form screens
- Sitewide content review/edit of the confirmation page.

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  No
  
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * Product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/product-outline.md
   * Content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/design/content-doc.md
   * Wireframe: https://bahdigital.invisionapp.com/share/CUIAGI923MB
   
Note: Due to the speed of this project, some artifacts are not fully aligned.  Content documentation should be considered the authoritative source when discrepancies are found.

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ X ] **New unauthenticated VA.gov page**
      * URL requested from IA: https://staging.va.gov/education/other-va-education-benefits/vrrap
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* Desired/target implementation date: On or before April 2, 2021

---

### About your team

- Team name: vsa-education
- DEPO product owner: Matt Self
- Product manager: Will McCormack
- Designer: Emma Waters
- FE engineer: Dan Shawkey
- Product/team Slack channel: vsa-education

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by bethpottsVADEPO** [comment]
@JenLJ @WillMcCormack Uploading here a Word doc with my tracked changes. Please let me know if there are questions. I put some notes to you at the top of the doc and some comments in the margins too. I'm co-leading an effort to get standards in place for content components, so you may notice that some of my edits change the messaging that's currently in design system and style guide documentation. These standards are a work in progress and we'll be updating the forms guidance as needed over the next couple months.  JFYI. But just ask me if anything comes up that you'd like to talk through. Thanks!

[VRRAP form notes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6246581/VRRAP.form.notes.docx)

**Comment by JenLJ** [comment]
@bethpottsVADEPO Thank you for the quick turnaround!  I've included a document showing changes that we've accepted (and will incorporate into our content document).  Due to the rapid turnaround for this, we've accepted all changes that will be a part of MVP.  Once launched, we will revisit the rest of the feedback you've provided.  Again - thank you for your flexibility and the quick feedback!
[VRRAP.form.notes_MVP.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6250056/VRRAP.form.notes_MVP.docx)

**Comment by bethpottsVADEPO** [comment]
Sounds good @JenLJ . When you have a ticket created for making the remaining edits, can you please tag me in that? I'm working with Danielle Thierry to standardize content components and labels across the forms. So we'll want to know when these updates get incorporated. 

Thank you for checking the address. I also had asked about a phone number too that I didn't think was right. Just want to make sure that gets addressed. Thanks!

**Comment by JenLJ** [comment]
@bethpottsVADEPO Understood!  Just to confirm, are all the messaging updates you suggested definitive?  Or are the content standards still going through review (and we would need to check in with you to see if anything has been updated)?

We did update the phone number in the Need help section!  Good catch on that!

**Comment by bethpottsVADEPO** [comment]
@JenLJ Thanks for asking about evolving standards. Things are a bit in flux, so it would be good to put a note in your ticket to check in with me before proceeding with the rest of the edits.

**Comment by JenLJ** [comment]
@bethpottsVADEPO For your awareness, the VA asked for some revisions to the eligibility criteria on the subway map and we have updated the criteria to the wording below.

- Age/Eligibility Criteria 1:  “At least 22 years of age but not more than 66 years of age,” 
- VA educational assistance/Eligibility Criteria 3:  “Not eligible for GI Bill or VR&E benefits (or, if you’re eligible for the Post-9/11 GI Bill, you’ve transferred all of your benefits to family members),”
- Unemployment/Eligibility Criteria 6:  “Not receiving unemployment benefits (including CARES Act benefits).”

**Comment by bethpottsVADEPO** [comment]
@JenLJ 
1/ That first edit for the age range gets away from our VA.gov voice. Can you tell me why they asked for that change?
2/ Is there a collab cycle ticket for review of the informational/static page I'm creating? Should be ready today or tomorrow.

**Comment by JenLJ** [comment]
@bethpottsVADEPO 
1 - They didn't provide any justification or explanation for the change.  They just sent a list of changes they wanted to be made.
2 - The collab cycle has been completely upended with this work due to the timeline - so unless you're referring to the kickoff ticket, I don't believe there is one.  Who typically reviews the informational/static pages?  (We can talk with the appropriate people and see if we can't get an expedited review)

**Comment by bethpottsVADEPO** [comment]
1/ I'll push back on that edit when I communicate with the stakeholders about the informational page--it's the same bullets in both places. I'd like to keep this bullet in line with the VA.gov style and plain language standards, with shorter and less repetitive content: Between 22 and 66 years old

2/ @shiragoodman would you like the informational page to have an accessibility or content check point? I created it, so any content collab cycle pass should be pretty straightforward. I'll have a preview link for you today or tomorrow, to assess.

**Comment by mattpointzxer0** [comment]
> 1/ I'll push back on that edit when I communicate with the stakeholders about the informational page--it's the same bullets in both places. I'd like to keep this bullet in line with the VA.gov style and plain language standards, with shorter and less repetitive content: Between 22 and 66 years old

Agree w/Beth this is the right thing to do for the sake of consistency and clarity.

**Comment by shiragoodman** [comment]
thanks @bethpottsVADEPO ! Yes, I think it would be very valuable for VRRAP to undergo a Collaboration Cycle review. @JenLJ we previously discussed doing an asynch review (a [Midpoint Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-midpoint-review.md) would probably be appropriate) for wherever you currently are with your build. @mattpointzxer0 and I also talked about this last week.

**Comment by JenLJ** [comment]
@shiragoodman I've notified leadership of the above conversation about the Midpoint review.  They'll likely discuss and make a decision today.  Currently, we have already completed a Content review (Beth) and an IA review (Mikki).  I know a Privacy and Security review is also in the works.

**Comment by bethpottsVADEPO** [comment]
@JenLJ Sorry that it's confusing about content involvement. My piece of it is setting the standards/creating the page (sitewide content). The platform team may also want to do a content QA checkpoint (it's a separate QA step). I'll let @shiragoodman decide if that's necessary. 

I spoke with @WillMcCormack to confirm that I'll be in touch directly with stakeholders to get their feedback about the static/informational page this week. It's good timing on the heals of the form review that happened today. I also alerted Will to the need for his dev to create the widget entry point to the form. Once that's created, sitewide content can insert it onto the static page. Will post the preview link to the static page in this ticket when it's ready for everyone's awareness.
@mattpointzxer0 JFYI

**Comment by amyknox** [comment]
@bethpottsVADEPO - for "the widget entry point",  are you talking about the wizard (screengrab below)?  If so, VRRAP isn't included in it yet, to my knowledge so I'm curious if you're handling the content creation for the wizard? 

If you're not talking about the wizard, could you explain what "the widget entry point" means to you? 


![image](https://user-images.githubusercontent.com/41081945/113754971-c8754700-96dd-11eb-9661-9a9516c61f6f.png)

**Comment by bethpottsVADEPO** [comment]
@amyknox Yes, the wizard. Here's what you should use (let me know if you have questions/if we're speaking the same language now!):

**How do I apply?**
You can apply online right now. 
BUTTON: [Apply for VRRAP education benefits]

**Comment by shiragoodman** [comment]
Thank you @bethpottsVADEPO. @JenLJ the asynch review is essentially you submitting a ticket with linked artifacts, then we review and provide feedback. The review covers design, IA, content, QA and accessibility. Since this has not had any accessibility involvement up to this point, I highly recommend that you do not skip this step.

**Comment by amyknox** [comment]
@bethpottsVADEPO 
Per our discussion, we want to include a design component in the static content page to route users to the VRRAP application. 

We'll model off the STEM Scholarship static page. The language you're suggesting above is good.  The component is either going to be a primary CTA button OR action link

I'll get back to you on whether we're using the green button OR action link. 

Link to action links: https://design.va.gov/components/action-links  (code snippet accessible there)

Post MVP question: Do we want to update the Education Benefits Wizard?

**Comment by bethpottsVADEPO** [comment]
@amyknox Thanks for the convo to clarify. I'll wait to hear if we're going to use the action link instead of the green button.

**Comment by amyknox** [comment]
@bethpottsVADEPO - The control to direct to the VRRAP application is... 🥁 

**_Action link!_** 

https://dsva.slack.com/archives/C0NGDDXME/p1617740539151500

**Comment by bethpottsVADEPO** [comment]
@amyknox Thanks for checking! As you probably saw in that slack thread (but just putting here for broader awareness), I found out that the action link isn't usable yet in the CMS, so we'll have to go with the green button for now. This VRRAP page will get the update to the action link when the global update is made across the site.

**Comment by amyknox** [comment]
@bethpottsVADEPO -  I hadn't seen that yet so appreciate the update.

**Comment by bethpottsVADEPO** [comment]
@JenLJ Here's the preview link for the static informational page that @shiragoodman recommended would need a new collab cycle ticket. I sent it to stakeholders to review today. Can you usher it through CC?: http://preview-prod.vfs.va.gov/preview?nodeId=17942

**Comment by WillMcCormack** [comment]
@bethpotts thanks for sending this our way, the link isn't loading for me. 

As for the collab cycle ticket is there any way we can leverage the tickets already filed for this form to track the work? As you know we are on a tight timeline so we are trying to take advantage of any opportunities to streamline that we can.

**Comment by shiragoodman** [comment]
hi @WillMcCormack. please review our [Midpoint Review ticket template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=midpoint-review.md&title=Midpoint+Review+%5BTeam+Name%2C+Feature+Name%5D) and see what artifacts we request in order to do our review. We understand that you will not have a lot of these, and that's okay. We'll work with what we can. If you want to leverage an existing ticket that already has these artifacts linked, please just tag me on the ticket and I can add our collab cycle labels so we can track it appropriately. Feel free to DM me if you have any questions.

**Comment by bethpottsVADEPO** [comment]
@WillMcCormack You have to be on the VA network for the preview link to work. Let me know if you're still having trouble loading it. http://preview-prod.vfs.va.gov/preview?nodeId=17942

**Comment by WillMcCormack** [comment]
Thanks @bethpotts I was able to view on my GFE, looks great!

**Comment by amyknox** [comment]
For awareness, VRRAP Midpoint review ([22836](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/22836)) has been submitted.

**Comment by bethpottsVADEPO** [comment]
@shiragoodman Do you know if the static VRRAP page was reviewed along with the form in the midpoint review? 
@WillMcCormack for awareness

**Comment by shiragoodman** [comment]
@bethpottsVADEPO the static page was not reviewed in the Midpoint Review.

**Comment by bethpottsVADEPO** [comment]
@shiragoodman what's your recommendation at this late stage for a collab cycle review? Would the best approach be a new ticket or tack on to an existing collab cycle ticket?

@JenLJ and @amyknox I was reviewing the edits and I think we should add back in "I attest" at the start of this line:
The statements above are true and accurate to the best of my knowledge and belief. { Radio: yes, no }

I realized that this language had probably gone through legal review at some point and is boilerplate, so I don't want to mess with it. Thank you!

**Comment by shiragoodman** [comment]
@bethpottsVADEPO I'd recommend a new ticket as it would be easier for reporting purposes. Also, it's a different team responsible for the work. If you submit today, we can have feedback to you by EOD Friday, possibly sooner.

**Comment by amyknox** [comment]
@bethpottsVADEPO - The "true and accurate" statement has gone through the client & OMB review / approval so we're going to hold with what we have for now. UAT starts this afternoon and we'll address it quickly if necessary.

**Comment by amyknox** [comment]
@bethpottsVADEPO & @shiragoodman For awareness - the VRRAP form could be ready to launch on production as early as Wednesday, 4/21

**Comment by RLHecht** [comment]
This is old work that's been completed. Closing.
