### ISSUE TITLE
Investigate auto logout of certain users

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#22170]
Investigate why some users appear to be auto-logged out immediately after logging in on IE. Details here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17198

**Comment by bosawt** [comment]
This happens because the `keepalive` endpoint is queried right after a successful login. In this case, the `session-alive: true` header is being dropped, the frontend sees this and decides the lack of this header means that the `ttl` should be set to zero, and the session immediately acts as if it had timed out. This is probably overall happening because `access-control-allow-headers` aren't being allowed.

This only appears to happen on Internet Explorer, and only on a CAG machine, behind the VA network. So this is probably is due to a provisioned policy with the CAG machines. I suspect the solution would be to change the Internet Explorer settings to allow certain headers for the `eauth` domain. Additionally, if this is only an issue behind the VA network with certain provisioned policies, probably the solution is just to suggest logging into VA.gov on a different browser

**Comment by AGarcia-Clarity** [comment]
@bosawt Looks like the previous team saw this too and referenced in https://github.com/department-of-veterans-affairs/va.gov-team/issues/15709
