### ISSUE TITLE
Create `searchableContent` field for R&S articles search

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#22181]
# Background

Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16916

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/16916#issuecomment-805199141

> I didn't think about this initially, but if we were to add a searchableContent field in the future it might really increase the file size of our articles.json in the near future, which will decrease both searching performance (it could appear laggy) and it will require our users to download a lot more before the page renders + is ready to respond to user input.
> 
> For reference, the current addition of the full intro text data point increases our articles.json file size from 31kb to 44kb. The addition of a searchableContent data point could increase the file size several times the size it currently is (depending on how big each article is). When we experiment with that new searchableContent data point, I'll be sure to let everyone know the difference in the articles.json file size so we can decide if we want to merge it or not.

# Acceptance Criteria

- [ ] Add `searchableContent` field to each article in R&S search articles.json (all R&S supported entity types)
- [ ] Measure size difference before merging a PR for ^
- [ ] Post the size difference in this ticket and ask for follow-up search functionality AC that relies on the new field

**Comment by kelsonic** [comment]
fysa @brianalloyd @jenniferlee-dsva

**Comment by brianalloyd** [comment]
Thanks @kelsonic appreciate the ticket spin up and work on continued refinement on this.

**Comment by kelsonic** [comment]
Checking to see if we should add this as AC in this ticket: https://dsva.slack.com/archives/C52CL1PKQ/p1616774460279700?thread_ts=1616771872.270900&cid=C52CL1PKQ

- [ ] Search for query instances in `title`/`introText` only if they are a **word** match, not a **set of characters** match. (e.g. a search of `I want ` should look for word instances of `I` in the articles' `title`/`introText`s and not any instance of an `i` character)

**Comment by brianalloyd** [comment]
Think that makes more sense than creating a separate ticket, getting a little hard to track all implemented elements.

**Comment by kelsonic** [comment]
Created `searchableContent` field for all R&S pages -- looks like it increased the size of articles.json from 42kb to 134kb. Good to proceed with using it for ordering logic? CC @jenniferlee-dsva @ncksllvn

**Comment by kelsonic** [comment]
fysa @jenniferlee-dsva https://github.com/department-of-veterans-affairs/vets-website/pull/16827#issuecomment-822585499

> @kelsonic Oh I missed that...so it's about 319% larger than the old. Its current file size is still fine but it means our scalability challenges will be hit sooner. I'm not sure what that limit will be...half a MB would be uncomfortable for me. A query-less search on /find-forms/ yields roughly a 375 KB JSON file, so maybe that can be our ceiling.
> 
> From a quick check in the sitemap it looks there are about 67 Resources articles on the site right now reflected in that articles.json...So that's about 2 KB per article in the new version. That means we'll be at the size of Find Forms by 187 articles and at half a meg at 250.
> 
> I think this is fine to merge but we should get a gauge on how many more articles we intend to publish before Resources is out of beta.
> 
> Long term, this is really beyond the limits of what I imagined a front-end search doing. IDK what team would do it, but we need to figure out a plan for a true API backing this. The easy searches like resources/search?q=DSLogon are the ones that would really benefit.

**Comment by kelsonic** [comment]
Follow-up ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22196
