### ISSUE TITLE
Add an optional subheading to our accordion component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#22180]
@bkjohnson commented on [Thu Mar 25 2021](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/412)

# Feature Request

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Is this feature request relating to an existing component or utility? Please describe.

- Component/utility name: `<va-accordion>`

Right now we have a variant of our accordion on facilities pages which includes an optional subheading:

https://www.va.gov/pittsburgh-health-care/health-services/

![image](https://user-images.githubusercontent.com/2008881/112508300-a75f3e80-8d4c-11eb-9e7c-b270317295d9.png)

This is coming from static markup templates:

- [facility health service](https://github.com/department-of-veterans-affairs/vets-website/blob/e384280a94bf09b15bf1ad5cf086ff5843412e77/src/site/facilities/facility_health_service.drupal.liquid#L11-L13)
- [health service](https://github.com/department-of-veterans-affairs/vets-website/blob/e5656c191d4686f6f6e2995fbc7b7b65e6c9688b/src/site/facilities/health_service.drupal.liquid#L11-L13)

This subheading feature isn't mentioned in [our documentation](https://design.va.gov/components/accordions), and as a result the `<va-accordion>` component wasn't built with it in mind. If we want to be able to migrate these static markup templates over to using the new web component, this feature needs to be added.

**Comment by k80bowman** [comment]
Closing as this work appears to be done: https://design.va.gov/storybook/?path=/docs/components-va-accordion--subheader
