### ISSUE TITLE
"Clear Input" misalignment

### ISSUE THREAD

**Issue by lildziner** [department-of-veterans-affairs/va.gov-team#22188]
## Issue Description
The 'Clear input' button is misaligned on certain screen devices

![image](https://user-images.githubusercontent.com/4960080/112661572-0c8a6100-8e2d-11eb-91fb-c7b32f715d93.png)

![image](https://user-images.githubusercontent.com/4960080/112661400-dc42c280-8e2c-11eb-81dc-ffea1cce3402.png)

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling

--- 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lildziner** [comment]
@mmiddaugh @mpelzsherman @brangi  Apologies if I didn't document this right. Let me know how to do this better next time.

**Comment by mpelzsherman** [comment]
> @mmiddaugh @mpelzsherman @brangi Apologies if I didn't document this right. Let me know how to do this better next time.

You did fine! The missing piece of info was the environment: this was only happening in production, where we are not displaying the "Use my location" link.
