### ISSUE TITLE
Improvements to R&S Search: use word, not character instances

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22196]
## Acceptance Criteria

**FIRST:**
- [x] Move the [experimental sorting logic](https://github.com/department-of-veterans-affairs/vets-website/blob/e5328976f93cd323a73a19af390e1847e4cd67a2/src/applications/resources-and-support/hooks/useGetSearchResults.js) to production.

**ONCE ABOVE IS MERGED + DEPLOYED:**
- [x] Modify [`countInstancesFound`](https://github.com/department-of-veterans-affairs/vets-website/blob/e5328976f93cd323a73a19af390e1847e4cd67a2/src/applications/resources-and-support/hooks/useGetSearchResults.js) method to not count keyword instances by character matches but instead by word matches. e.g. If your query is `sit`, then the word `deposit` should not be considered a keyword instance match.
- [x] Add `i` to a new [`EXPERIMENTAL_SEARCH_IGNORE_LIST`](https://github.com/department-of-veterans-affairs/vets-website/blob/6b80554665fc09e692b153cde90fe69c4d753655/src/applications/resources-and-support/constants/index.js) and use that constant to filter [here](https://github.com/department-of-veterans-affairs/vets-website/blob/e5328976f93cd323a73a19af390e1847e4cd67a2/src/applications/resources-and-support/hooks/useGetSearchResults.js) without affecting production.

**JUMP ON A CALL WITH @jenniferlee-dsva BEFORE MERGING TO SHOW HER THE CHANGES!** 🎉

**Comment by kelsonic** [comment]
Adding blocked until we get the green light to proceed: https://dsva.slack.com/archives/C52CL1PKQ/p1619547398313600?thread_ts=1619536672.303000&cid=C52CL1PKQ

**Comment by jenniferlee-dsva** [comment]
Please see my Slack comment here: https://dsva.slack.com/archives/C52CL1PKQ/p1619557476325100?thread_ts=1619536672.303000&cid=C52CL1PKQ 

@kelsonic @brianalloyd

**Comment by jenniferlee-dsva** [comment]
Ah one more thing - this ticket to search by `word-not-characters` should be applied not only to the intro text field, but to any field being scanned for search:

- article title
- intro text
- searchableContent

**Comment by jenniferlee-dsva** [comment]
@kelsonic - going back to our very old slack convo - we discussed how we don't want to impact searches so that for e.g., searches on "payments", it ends up ignoring articles with the word "payment".  We definitely do not want that. 

We simply want to prevent searches from bringing back anything with the letter `i` (or whatever letter) anywhere. So could we first try something very narrow to address the edge case of the letter i vs. word I situation? 

Whether that is to omit the letter `i` by only searching on the word - space-i-space - or by adding the letter `i` on our block list of words?

**Comment by jenniferlee-dsva** [comment]
@kelsonic - I'm not sure I can ever hope to understand Lodash method, not being an engineer!  I believe @ncksllvn  already had a blacklisted list of words implemented for RS search. So if there's a way to continue to add on to that, that would probably keep things simpler than having a different blacklist list for RS search. 

@ncksllvn - do you remember how we previously implemented the exclude-list of words on RS search?

**Comment by kelsonic** [comment]
@jenniferlee-dsva PR merged that moves the experimental sorting logic to production: https://github.com/department-of-veterans-affairs/vets-website/pull/16990 It will be live today following the daily deploy 🙂

**Comment by jenniferlee-dsva** [comment]
Please disregard my comment (struck out) above. Kelson and I have a modified plan in place after our sync.

**Comment by jenniferlee-dsva** [comment]
per convo with Kelson - this ticket has nothing to do with sort order or sort behavior, so I've edited the ticket name for clarity.

**Comment by kelsonic** [comment]
[PR is up](https://github.com/department-of-veterans-affairs/vets-website/pull/16992) for:

- [ ] Modify [`countInstancesFound`](https://github.com/department-of-veterans-affairs/vets-website/blob/e5328976f93cd323a73a19af390e1847e4cd67a2/src/applications/resources-and-support/hooks/useGetSearchResults.js) method to not count keyword instances by character matches but instead by word matches. e.g. If your query is `sit`, then the word `deposit` should not be considered a keyword instance match.
- [ ] Add `i` to a new [`EXPERIMENTAL_SEARCH_IGNORE_LIST`](https://github.com/department-of-veterans-affairs/vets-website/blob/6b80554665fc09e692b153cde90fe69c4d753655/src/applications/resources-and-support/constants/index.js) and use that constant to filter [here](https://github.com/department-of-veterans-affairs/vets-website/blob/e5328976f93cd323a73a19af390e1847e4cd67a2/src/applications/resources-and-support/hooks/useGetSearchResults.js) without affecting production.

@jenniferlee-dsva Could you let me know when you have time for me to show you the changes locally before we merge in the PR? 🙂

**Comment by brianalloyd** [comment]
@kelsonic validated on Prod, looks like results down from 31 to 23 as short logic has been achieved as reviewed during this weeks session.  @jenniferlee-dsva let me know if we're good to close this ticket in support. 
![Screen Shot 2021-05-04 at 2 42 12 PM](https://user-images.githubusercontent.com/70410912/117067457-46317000-ace7-11eb-9116-f11f8ba52fa6.png)

**Comment by brianalloyd** [comment]
Validated and closing.
