### ISSUE TITLE
0994: Update spacing between fields in Service History Chapter

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22194]
As an EDU developer, I need to update the spacing between the release from active duty date and the note below so that the page is more readable and it is in line with DEPO patterns and practices.

## Assumptions:
1. This work does not require a prod or feature flag.

## Acceptance Criteria
1. The space between the "Enter the date you expect to be released from active duty" question and the note below it is 25px.

## Supporting Artifacts:
1. 
![image](https://user-images.githubusercontent.com/48260534/112669831-896e0880-8e36-11eb-94e6-37329fe47b82.png)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16566

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me

**Comment by watersemma** [comment]
UX Review 2/2 Looks good to me!

**Comment by sonntag-adam** [comment]
Closing story.
