### ISSUE TITLE
School Ratings: Update google analytics tracking of ratings accordions

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22199]
As a developer, I need to update the ratings google analytics so that the interactions with individual rating categories can be tracked.

## Assumptions:
1. This work is completed behind the ratings feature flag #13359.

## Acceptance Criteria
1. The following google analytics attributes are set for each ratings accordion:

> 'event': 'int-accordion-expand' //'int-accordion-collapse' => this is an adjustment to our design system standardization
> 'accordion-parent-label': 'Overall experience' //dynamically populate with label of accordion, if accordion only has 1 label always populate this one 
> 'accordion-child-label': undefined //dynamically populate with secondary label of accordion, with no secondary label, set this as undefined 
> 'accordion-size': //pass in the exact width from the css class, large or small 
> 'gibct-rating': '3.4' //include the rating for each accordion

## Supporting Artifacts:
1. Origination of this story: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16164#issuecomment-797721119

**Comment by zurbergram** [comment]
Sample CSV update - https://github.com/department-of-veterans-affairs/gibct-data-service/pull/803

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16751

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now on Staging
