### ISSUE TITLE
Past Community Care with Cancelled Status shows as Completed

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#22195]
## What happened?
In VistA book a Community Care appointment and put in a cancelled status.  Verify CC appt display in VAOS with cancelled status.  

## Steps to Reproduce
- URL: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/past
- Test User _(if applicable)_: Ruben Moreno
1. Log into VistA and create a clinic appointment in VistA Community Care Clinic where CDW will have the CC flag = True.  
2. Cancel the past appointment in VistA
## Desired behavior
Expected:  VAOS shows past appointment as a Community Care Appointment with a Cancelled Status
Actual:  VAOS shows past appointment as a Community Care Appointment with a Completed Status

![CC_CancelStatus_VAOS](https://user-images.githubusercontent.com/62026291/112673456-59206d00-8e2a-11eb-8e2b-e7406aa8e308.png)

**Comment by marcynadeau** [comment]
From Jeff:  Ah, yeah, I see why. We’re marking all CC appointments as booked, because that’s true for the ones outside of VistA. But it’s wrong for the ones in VistA.

**Comment by jbalboni** [comment]
How to replicate this locally:

1. In confirmed_va.json, set `communityCare` to try on one (non-video) appointment and change the `currentStatus` field to be "CANCELLED BY PATIENT". Set the appointment date to be in the past.
2. View that appointment in the past appointments list

Note that the complication with this ticket is that community care appointments that come from var-resources (confirmed_cc.json) are always marked as completed. It's just CC appointments from VistA that have this issue.

**Comment by marcynadeau** [comment]
@LanceGundersen please let me know when pushed to staging and I will test.
