### ISSUE TITLE
STEM AD: Update the styling of the denial details page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22198]
As an EDU developer, I need to update the spacing on the denial reasons detail page so that the page is more readable and it is in line with DEPO patterns and practices.

## Assumptions:
1. This work does not require a prod or feature flag.

## Acceptance Criteria:
1. The space between the H3 and the content in the right panel is 16px.
2. The space between the header and the bulleted list in the main content panel is 8px.

## Supporting Artifacts:
1. Image for AC1
![image](https://user-images.githubusercontent.com/48260534/112674107-ea4c0f80-8e3b-11eb-9133-a4a58c15640f.png)

2. Image for AC2
![image](https://user-images.githubusercontent.com/48260534/112674173-fd5edf80-8e3b-11eb-8e0c-0f16ee9886cc.png)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16561

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by amyknox** [comment]
Text spacing issues are still present in body content 


![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/8b2dcd0c-dade-4cf4-be2a-4625f738d945)

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16600

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me!

**Comment by amyknox** [comment]
UX Review 2/2: Looks good to me.

**Comment by sonntag-adam** [comment]
Closing story
