### ISSUE TITLE
CT Redesign: Comparison View - Improve ability to distinguish differences - Desktop Solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22207]
Document approaches to improve comparison display on desktop and ability to identify deltas between compared schools	

* Explore possible ways to address the challenge on desktop  
* Document approaches with greatest potential 
* Discuss pros/cons with UX team

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1617710116724/06fd7c751f02d73b05dc3065221dca2cfa5a47e7
