### ISSUE TITLE
Direct Deposit Call Center Report

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#2220]
## User Story or Problem Statement
As a product owner of the direct deposit tool, I need call center data on direct deposit issues, so I can learn about the issues facing users and resolve those issues. 

## Goal
Weekly report from NCC on VA.gov direct deposit issues. 

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] Update NCC CRM to track VA.gov direct deposit issues
- [ ] Set up weekly report from NCC for direct deposit issues
- [ ] Get access to case descriptions if needed for investigation or triage

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Adding blocked label - client not currently engaging.

**Comment by joanneesteban** [comment]
Lower priority on the list of requests from this Call Center - moving to the backlog.

**Comment by Kimberley2019** [comment]
Closing this ticket after discussing that this is not something that we will move forward with.
