### ISSUE TITLE
CT Redesign:Comparison View - Improve ability to distinguish differences - Prototypes; Mobile

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22208]
Mobile prototypes are updated with improved comparison display and ability to identify deltas between compared schools	

* Update mobile prototypes with optimal approach 
* Review for adherence VA.gov styles

**Comment by amyknox** [comment]
@desireeturner - This story was pulled into Sp70 inadvertently.  Let's discuss options for backing it out.

**Comment by amyknox** [comment]
OBE
