### ISSUE TITLE
SAML Tracing

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#22201]
Collection of work related to cookie tracker attributes to trace the complete transaction of a login via SAML.

The attributes in question are for cookie:value
`vagov_saml_request_ENV`:`{"timestamp":"2021-03-24T15:18:06+00:00","transaction_id":"aacd9cf7-4cb7-4188-b43d-1575065bf0fc","saml_request_id":"_788ddef1-9142-4210-9e2b-1fec8522733b","saml_request_query_params":{}}`

**Comment by AGarcia-Clarity** [comment]
:wave: @joeniquette cleaning up the board on Zenhub, can this Epic be closed?
