### ISSUE TITLE
STEM: Phone number fields allow more than 10 digits

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#22214]
In Chapter 5 of the STEM application, the user is asked a series of 'Personal information' questions, including phone numbers. The phone number fields should be limited to 10 characters and only allow numbers. Currently, there is no limit to the number of digits that can be entered and letters are also allowed. 

### Steps to reproduce
1. Navigate to https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction
2. Begin to fill out the form and stop on the Personal information page
3. Enter more than 10 characters into the Phone number fields.

### Expected behavior 
An error should be displayed such as the below example from the 0994 form. The user should not be able to proceed until the error is resolved.
![Screen Shot 2021-03-26 at 3.51.50 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f0a3688a-5dc1-4fa6-b8e9-4a4d258d02b2)

### Actual behavior:
User can enter more than 10 digits without receiving an error and can proceed through the rest of the form
![Screen Shot 2021-03-26 at 3.58.09 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/928fc657-1820-471e-ac97-aa0ab5085d26)

**Comment by dmccurdybah** [comment]
Can be tested locally on vets-website branch `update-schema-version`

**Comment by dmccurdybah** [comment]
vets-json-schema PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/573

**Comment by dmccurdybah** [comment]
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16599

**Comment by dmccurdybah** [comment]
vets-api-pr

**Comment by sonntag-adam** [comment]
In staging. Closing bug.
