### ISSUE TITLE
CT Redesign:Comparison View - Improve ability to distinguish differences - Team Sync

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22211]
Prototypes with improved comparison display (on mobile in particular) and ability to identify deltas between compared schools are reviewed with UXBA	

* Prototype is shared with relevant team members  
* Feedback is collected 
* Prototype is tweaked, per input OR additional stories are written, as necessary

**Comment by JenLJ** [comment]
Shared at mini-sync on April 22nd:

Desktop:
- Like the consistency with using above headers on desktop, but also like the visual style of the one where headers are in line with content
- Question: How will we incorporate Learn more components into the Comparison view?
