### ISSUE TITLE
EDU Forms / VET TEC:  Certification Content Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22219]
VET TEC Content for Certification on confirmation page has been drafted 	

* Content is drafted 
* GH Doc is shared internally (UXBA team).   
* Respond to any questions

**Comment by amyknox** [comment]
Notes from Education Service on VET TEC form updates

[https://app.zenhub.com/files/133843125/dbe4348c-9c5d-4453-b357-c9c7588ac238/download](https://app.zenhub.com/files/133843125/dbe4348c-9c5d-4453-b357-c9c7588ac238/download)
