### ISSUE TITLE
CT Redesign:Comparison View - Improve ability to distinguish differences - Prototypes; Desktop

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22210]
Desktop prototypes are updated with improved comparison display and ability to identify deltas between compared schools	

* Update desktop prototypes with optimal approach 
* Review for adherence VA.gov styles

**DRAFT PROTOTYPES**
1. default compare view  (with control to drive difference functionality)
2. compare view with difference functionality addressed

**Comment by amyknox** [comment]
@desireeturner - This story was pulled into Sp70 inadvertently.  Let's discuss options for backing it out.

**Comment by amyknox** [comment]
Mural with top examples: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1617710116724/06fd7c751f02d73b05dc3065221dca2cfa5a47e7?wid=0-1619025895150
