### ISSUE TITLE
508-defect-2: Operating status, breadcrumb only contains the current page

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#22228]
Label: 18928

    - [508-defect-2]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2

Issue Title: Defect level 2: Operating status, breadcrumb only contains the current page
Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only:  Angela

<h2>User Story or Problem Statement:</h2>
When visiting a page within a web site, I expect to be able to return to previous pages without using the back button.
<h2>Details</h2>
On the "operating status" page, the breadcrumb only contains the current page. There is no way to return home.

## Acceptance Criteria
- [ ] Breadcrumb is designed such that it recreates the path the user took to reach the "Operating Status" page.

Environment

Steps to Recreate

Proposed Solution (if known)

WCAG or Vendor Guidance (optional)

Screenshots or Trace Logs

**Comment by laflannery** [comment]
This is resolved, breadcrumbs have operating status page and the main VA Health care page:
![image](https://user-images.githubusercontent.com/106678594/200415197-de4e6ed3-36d7-458c-8bbd-50e573fb6520.png)
