### ISSUE TITLE
[Bug] Tags component whitespace issues

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22226]
## Issue Description
https://github.com/department-of-veterans-affairs/va.gov-team/issues/16623#issuecomment-805121660

## Acceptance Criteria
![image](https://user-images.githubusercontent.com/12773166/116295353-3ac5ce00-a756-11eb-9b46-d3bf1f3d080b.png)

- [x] Decrease the line height of the type (not the height of the tag-shape) so if/when type has to run onto two or more lines, it minimized the height.
- [x] Ensure the spacing between the tags is always equal both vertically and horizontally. i've used 12 px (1.5 spacing units) in sketch but we can adjust as needed
- [x] Adjust horizontal rules above and bellow the tags section to follow the margins of the rest of the page

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
This gave me a laugh. Here is how Zenhub handles whitespace for their tags.

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/ec3f8a41-c45e-4210-abb0-d2b2730a7a52)

**Comment by brianalloyd** [comment]
@rtwell can I get your review on this ticket, did a quick review and everything looks good on my end in support.

**Comment by kelsonic** [comment]
Heads up that the [recent PR I just merged](https://github.com/department-of-veterans-affairs/vets-website/pull/16970) won't be deployed until tomorrow 🙂

**Comment by brianalloyd** [comment]
Thanks @kelsonic wasn't sure on timing release for the deployment.  We'll program for validation tomorrow.

**Comment by brianalloyd** [comment]
Validate and Closing.
