### ISSUE TITLE
EDU Forms / VET TEC:  Certification Prototype Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22220]
VET TEC protototype is updated with confirmation page revisions	

* Prototype is updated to incorporate EDU updates on confirmation page
* Prototype is reviewed w UX team
* Updates from UX are incorporated

**Comment by amyknox** [comment]
EDU is re-reviewing and will return with an answer early Sp71

**Comment by JenLJ** [comment]
Prototype has been updated with all feedback.  See  https://bahdigital.invisionapp.com/share/EKIAGNW2V86
