### ISSUE TITLE
EDU Forms / 1990e: Certification Prototype Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22225]
VET TEC protototype is updated with confirmation page revisions	

* Prototype is updated to incorporate EDU updates on confirmation page 
* Prototype is reviewed w UX team 
* Updates from UX are incorporated

**Comment by amyknox** [comment]
EDU is re-reviewing and will return with an answer early Sp71

**Comment by amyknox** [comment]
Mural board for background: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1618250576905/b3161a2f68c43a44a03f7d9ee500944ed4349428

**Comment by amyknox** [comment]
Background on The Law
https://benefits.va.gov/gibill/isaksonroe.asp

https://benefits.va.gov/GIBILL/docs/IsaksonRoe/IsaksonRoeFactSheet.pdf

**Comment by JenLJ** [comment]
Prototype: https://bahdigital.invisionapp.com/share/SUIAGOS37X5
