### ISSUE TITLE
EDU Forms / VET TEC:  Certification - DEPO Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22222]
VET TEC protototype has been reviewed by DEPO	

* Prototype is reviewed w DEPO 
* Updates to prototype / content doc are incorporated, if needed

**Comment by JenLJ** [comment]
DEPO Design review on April 6th:

Recommendations:
1. Keep two certifications separate (general one and active duty one).
2. Keep the current order of the checkboxes
3. Only use one "penalty note"
4. For active duty certification, add "if on active duty" to the beginning
5. Keep certification(s) on the Review application page, directly before submission (this is the general pattern they've observed for certifications)

Other notes:
- To Design's knowledge, no one else has had certification questions like this.  They recommended pinging the design channel to ask.
- Emphasized that the electronic version of the form does NOT have to match the paper form
- Stated that the usage of checkboxes (and whether they are required) versus just a statement the user agrees to by signing is a client decision
