### ISSUE TITLE
EDU Forms / 1990e:  Certification Content Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22224]
VET TEC Content for Certification on confirmation page has been drafted 	

* Content is drafted 
* GH Doc is shared internally (UXBA team).   
* Respond to any questions

**Comment by amyknox** [comment]
[https://app.zenhub.com/files/133843125/ce3991fe-88a5-4fb5-b466-ea1835fcdcf3/download](https://app.zenhub.com/files/133843125/ce3991fe-88a5-4fb5-b466-ea1835fcdcf3/download)
