### ISSUE TITLE
Loading screens for Messages pages

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22236]
## User story
As a user, I want to see a loading screen that tells me that the app is loading my messages and folders page.

## Acceptance Criteria
1. Using the loading spinner CC, display loading screens on the following pages with the indicated copy: 
     - Inbox list page: "We're loading your messages"
     - Folders list page: "We're loading your folders"
     - Sent folder list page: "We're loading your messages"
     - Custom folder list page: "We're loading your messages"
     - Message detail page: "We're loading your message" _Note that 'message' is singular_

## Designs
Similar design:
![Image from iOS (35).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/390b7b19-ff95-44dd-be5b-f008567a816c)

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
@drjecker there are a number of screens throughout SM where we'll want to include loading screens. I took a first pass at the copy based on some of the other loading screens in the app, but feel free to weigh in here if you have any changes!

**Comment by drjecker** [comment]
This looks great to me! Let's go with it.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/9/2021 - Looks good on iOS and Android.  Was difficult to see the message for loading folders because the folders always appeared so fast, but I finally got it to pause for a second to verify.  Closing.

**Comment by digitalken** [comment]
PASS 4/9/2021 - Looks good on iOS and Android.  Was difficult to see the message for loading folders because the folders always appeared so fast, but I finally got it to pause for a second to verify.  Closing.
