### ISSUE TITLE
Common component: Message ListItem

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22239]
## Acceptance Criteria
1. Create common component for the Secure Message ListItem, which will appear on the Inbox list page and Sent/Custom folders list pages.
2. Overall list
     - Margin: no gutter L/R; marginBetween above and below component
3. Rows
     - Background color: white #ffffff
     - SVG: right chevron as used in common list component
     - Margin: 0px between rows
     - Internal padding: 20px total; 
     - Border-bottom: 1px solid gray-light #aeb0b5
     - Text:
          - Name text: Mobile Body Bold
          - Subject text: Mobile Body
          - Date text: Mobile Body
          - Margin: 7px between icons and text. If no icon, margin-left: 23px;
4. Variations
     - Unread message: Unread icon SVG left of Name
     - Read message: No icon; Name margin left 23px;
     - Message with attachment: Gray paperclip icon SVG left of Date
     - Message with no attachment: No icon; Date margin left 23px;
     - Messages in Sent folder READ tag:
          - Background-color: gray-dark #323a45
          - Color: #fff
          - Font-family: Source Sans Pro
          - Font-size: 16px;
          - Padding: 
               - top/bottom: 5px;
               - left/right: 10px;

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364845

![Screen Shot 2021-04-06 at 1.47.35 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/30991604-a1af-47a4-901a-d1b46920f454)

## Assets
![message-unread-circle.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/08d25845-ef23-46e4-8dda-419349f88ddd)![paperclip--$color-gray-medium.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b1c637af-5eb2-4713-b034-1d8a2f77c813)

**Comment by drjecker** [comment]
@bessgreen Specs have been added to [UI style doc](https://docs.google.com/document/d/1VC-CLWnhevB8HLBBHPwkSJvECn8EBie8HOkJylKE1lo/edit#bookmark=id.bcbz9gig67fc). Let me know if you have questions.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/22/2021 - Looks good on iOS and Android.  Closing.
