### ISSUE TITLE
[Off-Site Search] Non-Canonical URLs in VA.gov Site Map

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#22242]
## What happened?

SEMRush is reporting that as of March 28 more than 100 modernized VA.gov are "incorrect pages found in the sitemap.xml."  Example pages include:

https://www.va.gov/health-care/covid-19-vaccine/
https://www.va.gov/outreach-and-events/events/
https://www.va.gov/careers-employment/vocational-rehabilitation/

The full list is attached in this PDF.

[SEMrush-Site_Audit__Incorrect_pages_found_in_sitemap_xml-va_gov-28th_Mar_2021.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6217778/SEMrush-Site_Audit__Incorrect_pages_found_in_sitemap_xml-va_gov-28th_Mar_2021.pdf)

### What does this mean?

According to SEMRush: A sitemap.xml file makes it easier for crawlers to discover the pages on your website. Only good pages intended for your visitors should be included in your sitemap.xml file.
This error is triggered if your sitemap.xml contains URLs that:
- lead to webpages with the same content
- redirect to a different webpage
- return non-200 status code
Populating your file with such URLs will confuse search engines, cause unnecessary crawling or may even result in your sitemap being rejected.

### How to Assess, Validate and Address

- Per SEMRush: Review your sitemap.xml for any redirected, non-canonical or non-200 URLs. Provide the final destination URLs that are canonical and return a 200 status code.
- **However, according to Google Search Console, VA.gov is not showing any issues related to non-canonical URLs.** Worth noting: One SEO consultant says _Google ignores it, browsers hide it, SEO is unaffected by it, but SEMRush loves to report it._  More details here: https://webmasters.stackexchange.com/questions/100082/trailing-slash-google-search-console-and-sitemap
- **Indeed, a [GSC Coverage report run](https://search.google.com/u/1/search-console/index?resource_id=https%3A%2F%2Fwww.va.gov%2F&hl=en) on 3/28 shows only two errors** based on Indexing of VA.gov site map.

<img width="1034" alt="Screen Shot 2021-03-28 at 2 11 38 PM" src="https://user-images.githubusercontent.com/63107147/112762818-d0dbcc80-8fcf-11eb-9448-43a2d9723c9f.png">

More details about what the GSC Coverage report tells us: https://support.google.com/webmasters/answer/7440203?hl=en#:~:text=The%20Index%20Coverage%20report%20shows,not%20found%20(404)).

### Next Steps

- [ ] Have @srsuddath review my assessment of this and validate if this is a non-issue for VA.gov.
- [ ]  @srsuddath and @johnhashva should review the GSC indexing Coverage report to determine if the error (Red) and valid, with warning (Yellow) issues require actioning.

<img width="1001" alt="Screen Shot 2021-03-28 at 2 22 38 PM" src="https://user-images.githubusercontent.com/63107147/112763132-282e6c80-8fd1-11eb-9aa1-7b4770e2b859.png">

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by johnhashva** [comment]
Per Nick Sullivan: In SEMrush-Site_Audit_Incorrect_pages_found_in_sitemap, I don't really know what it means to report those pages as non-canonical URLs. For instance, looking at https://www.va.gov/health-care/ , I don't know what could be wrong with that page. Perhaps it is flagged as non-canonical because there is some repeating content on that page. This could be worth looking into. We may come up with some findings that we can relay to the content team - "Did you know that we have the same content on Page X and Page Y? If we can consolidate this to just one of the two, we will get an SEO boost."

**Comment by jenniferlee-dsva** [comment]
Also - I do notice that when the CMS generates URLs, it does so without the trailing / . And I wonder if that is one of the sources of this issue -- the discrepancy between sitemap using URLs with the  / but the CMS publishing pages without the /. 

So possibly 2 issues? 
- 1/ missing rel="canonical" tags  -- ?
- 2/ the CMS publishing URLs without the trailing /  --?

Example - CMS URL: 
![image](https://user-images.githubusercontent.com/43381063/113014221-6b601b00-914a-11eb-923f-5b34458a6a44.png)

**Comment by johnhashva** [comment]
Update w/next steps:

- John will set a meeting with CMS team to dig deeper (with @denisecoveyduc and @srsuddath participating)
- @srsuddath and @denisecoveyduc will set-aside time in upcoming sprint to understand this topic better via SEMRush and Google and other resources.  One more for read-in:
Canonical URLs: A Beginner's Guide to Canonical Tags in 2021 -  https://www.semrush.com/blog/canonical-url-guide/

**Comment by johnhashva** [comment]
@johnhashva to follow up with CMS to ask these two questions (per @ncksllvn)

- Ask CMS If I wanted to add the canonical URL into the metadata of a page, could I specify that from the CMS?
- If yes, then Is there anything a front-end engineer needs to do to ensure that the "canonical" field from the CMS is supported/honored by front-end templates?

**Comment by ncksllvn** [comment]
Just looked into this further...

I looked at the VA.gov sitemap and it includes the trailing slashes like it should. This doesn't match what Drupal says is the `VA.gov URL` but once on the webste the trailing slash is still correct as the URL. 

So I think @jenniferlee-dsva's [first comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22242#issuecomment-810347255) gets at the root of the issue here (great insight @jenniferlee-dsva thank you.) 

I looked into the canonical tag this by going to `view-source:https://www.va.gov/health-care/`. I see this in the page source -

![image](https://user-images.githubusercontent.com/1915775/113235300-c7bd5a80-9270-11eb-8aff-2d9c4cfe8950.png)

Two issues there -

1. "canonical" is present but it needs the trailing slash
2. I don't think it is part of this issue but the `og:url` has two slashes after `va.gov` so we should get that while we are at it. 

Both of these fixes can be made at https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/includes/metatags.drupal.liquid.

**Comment by ncksllvn** [comment]
I can do this change if you want @johnhashva, the hard part was this investigation.

**Comment by ncksllvn** [comment]
Scratch that, I went ahead and grabbed it, https://github.com/department-of-veterans-affairs/vets-website/pull/16614.

**Comment by johnhashva** [comment]
@ncksllvn thanks for the deeper probe -- and fix.    We (@srsuddath) will take a closer look at:

1/ missing rel="canonical" tags

**Comment by ncksllvn** [comment]
The canonical tags are there actually. They were just incorrect - they were missing a trailing slash, which is important when you write the canonical URL. I think my PR above will close this issue.

**Comment by johnhashva** [comment]
Got it @ncksllvn.  We will keep this ticket open so we can validate that the fix is not only live in production -- but also, via SEMRush audit the errors magically go away.

**Comment by ncksllvn** [comment]
This is in Prod now @johnhashva if you want to rerun the report in SEMRush

![image](https://user-images.githubusercontent.com/1915775/113773674-4fcdb500-96f4-11eb-9083-115eb6f75150.png)

**Comment by johnhashva** [comment]
Thanks @ncksllvn.  Going to keep this ticket open until we see evidence/data that the fix solved the problem.  That will come via an SEMRush audit report that will presumably show a complete elimination or significant reduction in number of non-canonical URL issues in the site map.   I'm thinking that should surface relatively quickly -- in the next week or so.  Do you agree?

**Comment by ncksllvn** [comment]
Sounds good to me. I didn't know how the SEMRush report was generated (I thought we clicked a button or something.)

**Comment by johnhashva** [comment]
Team -@ncksllvn + @jenniferlee-dsva + @brianalloyd + @denisecoveyduc + @srsuddath -- Per a fresh crawl by SEMRush, looks like this one is fixed.  Thanks @jenniferlee-dsva and @ncksllvn for getting this bugger diagnosed and  solved.

<img width="1045" alt="Screen Shot 2021-04-07 at 9 41 00 AM" src="https://user-images.githubusercontent.com/63107147/113876425-bcdd5b00-9785-11eb-85aa-982df5ffea98.png">

Any reason not to close?

**Comment by ncksllvn** [comment]
Just saw this - yay! No reason not to close this - this issue is all done ✅

**Comment by johnhashva** [comment]
@brianalloyd closing this one with updated proof -- via SEMRush -- that the issue of incorrect pages found in sitemap.xml has been resolved.

<img width="1041" alt="Screen Shot 2021-05-04 at 10 13 55 AM" src="https://user-images.githubusercontent.com/63107147/117017550-ac0b0100-acc1-11eb-9cbe-a3d53b462142.png">
