### ISSUE TITLE
Need 508 review for NewKMI tool asap

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#22249]
## Issue Description

President Biden signed the SAVE LIVES Act last week. We're trying to ship this today to allow the VA to vaccinate ~20 million more people.

---
## Tasks

Need an a11y review from @joshkimux to discover any launch blockers. @stephenBarrs , @cohnjesse , and @bkjohnson  are the FE engineers. @batemapf  is the product owner.

Staging: https://staging.va.gov/health-care/covid-19-vaccine/stay-informed

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joshkimux** [comment]
<img width="720" alt="Screen Shot 2021-03-29 at 4 20 00 PM" src="https://user-images.githubusercontent.com/14154792/112895121-b6c2ec80-90aa-11eb-9ffb-93aff6fff4a9.png">
Not accessibility related, but question for @artsymartha68

**Comment by artsymartha68** [comment]
Hoping this is fixed now that #16574 has been fixed?

**Comment by batemapf** [comment]
The preferredFacility issue has been fixed!

**Comment by joshkimux** [comment]
@artsymartha68 instead of tagging ticket by ticket, tagging you to the epic. It looks like 4 major issues have not been resolved in over 2 years 😢

**Comment by artsymartha68** [comment]
Closing this, we don't have a KMI tool anymore.
