### ISSUE TITLE
Create confirmation pages

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2224]
As a developer, I want to know what to show veterans on the confirmation page for each type of appointment so that I can show them the right thing.

## Variants
- Direct Scheduled appointments
- VA appointment requests
- Community Care appointment requests

## AC
- [ ] Mocks for each of these variants are attached to this ticket.

**Comment by markgreenburg** [comment]
Posted in another ticket:

Requests variants:
![request-confirmation-variants](https://user-images.githubusercontent.com/24251447/67506339-7c9e2180-f652-11e9-9797-f90a80e0a351.png)

Direct schedule confirmation:
![direct-confirmation](https://user-images.githubusercontent.com/24251447/67506353-858ef300-f652-11e9-85b3-72b9ea40fede.png)

**Comment by markgreenburg** [comment]
Think this is ready for front end, though content may need updating once Peggy takes a look.

**Comment by peggygannon** [comment]
@markgreenburg @rtwell @goldenmeanie 
Please see below my content updates for the 3 types of confirmation pages. Let me know if you have any questions or want to review this together at our next sync. 


cc @jbalboni 

VA appointment request confirmation page
{alert}
**Your appointment request has been submitted**
We’re reviewing your request. You don’t have to do anything right now. A scheduler will contact you to schedule the first available appointment. 

{new text box}
**Pending appointment**
We’ll contact you to schedule this appointment. 

**Type of appointment:** {Primary care or specialist type}

**{name of medical center}**

**{address}**

**Your preferred date and time**

**Routine/follow-up visit**

**Your contact email**

**Your contact phone number**

**Best time for us to call you**

-------

Community care request confirmation page

{alert}
**Your appointment request has been submitted**
We’re reviewing your request. You don’t have to do anything right now. A scheduler will contact you to schedule the first available appointment. 

{new text box}
**Pending appointment**
We’ll contact you to schedule this appointment. 

**Type of appointment:** Community Care

**Preferred providers** 

**Your preferred date and time**

**Routine/follow-up visit**

**Your contact email**

**Your contact phone number**

**Best time for us to call you**

-------

Direct schedule confirmation page

{alert}
**Your appointment has been scheduled**
Your appointment is confirmed. Please see appointment details below. 

{new text box}
**Your appointment details**

**Type of appointment:** Primary care
**Date** {date} November 26, 2019
**Time** {time} 10:00 a.m. ET
**{medical center name}**
**Routine/follow-up visit**
**Your contact email**
**Your contact phone number**

**Comment by rtwell** [comment]
Hi @peggygannon 

Thanks for this! I think we should discuss at our sync — we've had a few more thoughts on how we might organize the info on these screens

**Comment by markgreenburg** [comment]
Tagging Ryan and myself for visibility before the content sync.

**Comment by rtwell** [comment]
## Direct schedule

### Review page
![Direct schedule - Review@2x](https://user-images.githubusercontent.com/12564977/68324783-1a9fdc00-0096-11ea-8b93-b854d41cd525.png)

### Confirm page
![Direct schedule - Confirm@2x](https://user-images.githubusercontent.com/12564977/68324796-212e5380-0096-11ea-822a-9c7cd37ecc89.png)

### List view
![Direct schedule - List view@2x](https://user-images.githubusercontent.com/12564977/68324816-27bccb00-0096-11ea-92fa-899115f77fa4.png)

## VA appt request

### Review page
![Request -VA appt - Review appt@2x](https://user-images.githubusercontent.com/12564977/68324908-59ce2d00-0096-11ea-8b51-ad55367f1d85.png)

### Confirm page
![Request -VA appt - Confirm@2x](https://user-images.githubusercontent.com/12564977/68324988-8da95280-0096-11ea-9de3-a645199ce749.png)

### List view
![Request -VA appt - List view@2x](https://user-images.githubusercontent.com/12564977/68325003-9732ba80-0096-11ea-9e5e-7fb6bdd8f675.png)

## CC appt request

### Review page
![Request - CC appt - Review appt@2x](https://user-images.githubusercontent.com/12564977/68325020-a154b900-0096-11ea-8ab3-306846b44ed1.png)

### Confirm page
![Request - CC appt - Confirm@2x](https://user-images.githubusercontent.com/12564977/68325036-aade2100-0096-11ea-8ae6-89e737940c54.png)

### List view
![Request - CC appt - List view@2x](https://user-images.githubusercontent.com/12564977/68325090-c6e1c280-0096-11ea-818d-0b84cf717919.png)

## Video appt request

### Review page
![Request - Video appt - Review appt@2x](https://user-images.githubusercontent.com/12564977/68325196-ef69bc80-0096-11ea-9e81-0c29d666bd8b.png)

### Confirm page
![Request - Video appt - Confirm@2x](https://user-images.githubusercontent.com/12564977/68325209-f42e7080-0096-11ea-9bb7-35974a242e8e.png)

### List view
![Request - Video appt - List view@2x](https://user-images.githubusercontent.com/12564977/68325223-f98bbb00-0096-11ea-895c-202817ccb824.png)

**Comment by jbalboni** [comment]
@peggygannon One thing I noticed looking at the confirmation page mocks, they don’t have top level page header text. I think we need one on all pages for accessibility reasons. Is that text something you could write for us? I could use the bold text in the green boxes if I have to.

**Comment by peggygannon** [comment]
@jbalboni Yes, I'll write a top level head for the confirmation pages. I'm going to work on making these confirm, review and list/card pages consistent across the tool

**Comment by rtwell** [comment]
one more thing—these will also been seen next to each other in the appointment list view:

![image](https://user-images.githubusercontent.com/12564977/68411858-45069d80-0159-11ea-85ae-aa4061b18a1e.png)

**Comment by rtwell** [comment]
my sense is we'll need 2 groups of header info (all of this is for placement only):
1. **Statuses**
a. Confirmed
b. Canceled
c. Pending
2. **Headers**
a. Date, Time, and Time zone (for example: Wednesday, December 11, 2019 at 11:00 a.m. ET)
b. Appointment request - VA
c. Appointment request - Community Care
d. Appointment request - VA Video Connect

**Comment by jbalboni** [comment]
@rtwell Do we need to include the join button on the confirmation page for video appointments? It's never going to be active and I don't think it's guaranteed that you end up with a video appointment if you make a request for one, if a scheduler works with you and decides otherwise (though I could be wrong on the last part).

**Comment by rtwell** [comment]
great question—my thinking was to include it to clue the user in right away that they'll be able to join the call directly from vaos, rather then having to figure that out later, but maybe that should be better handled with emails, etc

**Comment by peggygannon** [comment]
@rtwell @jbalboni Please see below my content recommendations for the 
Review and confirmation pages. Please let me know if you have any questions or want to discuss over the phone. 

cc @markgreenburg 

I'll upload my recommendations to the list/card screens shortly. 

------

VAOS Review page variants: 

1. Direct schedule

{page title} **Review your appointment**

**You’re scheduling a primary care appointment**
Please review the information below before confirming your appointment. If you need to update any details, click Edit to go back to the screen where you entered the information. After you update your information, you’ll need to go through the tool again to schedule your appointment. 

Type of appointment: {Primary care or specialist type}
{date and time}
{medical center name/address}
{type of visit}Routine/follow-up visit
{your contact info}

{button} Confirm appointment 

-----

2. VA appointment request

{Page title} **Review your appointment**
 
**You’re requesting a VA primary care appointment**
Please review the information below before submitting your request. If you need to update any details, click Edit to go back to the screen where you entered the information. After you update your information, you’ll need go through the tool again to request your appointment. 

Type of appointment: {Primary care or specialist type}
{Preferred date and time}
{medical center name/location}
{type of visit}Routine/follow-up visit
{ Your contact information}

{button} Request appointment

------

3. Community care request

{page title} **Review your appointment** 

**You’re requesting a Community Care appointment**
Please review the information below before submitting your request. If you need to update any details, click Edit to go back to the screen where you entered the information. After you update your information, you’ll need to go through the tool again to request your appointment. 

Type of appointment: {Community Care }
{Preferred date and time}
{medical center/provider name/location}
{type of visit}Routine/follow-up visit
{ Your contact information}

{button} Request appointment

--------

Confirmation page variants
1. Direct schedule

{page title} **Your appointment has been scheduled**
Your appointment is confirmed. Please see your appointment details below.

{new text box}
Type of appointment: Primary care
Date {date} and Time {time} November 26, 2019 at 10:00 a.m. ET
{medical center name}
{type of visit-Routine/follow-up}
Your contact information}

2. VA appointment request

{page title} **Your appointment request has been submitted**

We’re reviewing your request. You don’t have to do anything right now. A scheduler will contact you to schedule the first available appointment.

{new text box}
**Pending appointment**
We’ll contact you to schedule this appointment.
Type of appointment: {Primary care or specialist type}
{medical center name/address}
{Preferred date and time}
{type of visit}Routine/follow-up visit
{Your contact information}
{Best time for us to call you}

3. Community Care request

{page title} **Your appointment request has been submitted**

We’re reviewing your request. You don’t have to do anything right now. A scheduler will contact you to schedule the first available appointment.

{new text box}
**Pending appointment**
We’ll contact you to schedule this appointment.
Type of appointment: {Community Care}
{medical center/provider name/address}
{Preferred date and time}
{type of visit}Routine/follow-up visit
{Your contact information}
{Best time for us to call you}

**Comment by peggygannon** [comment]
@rtwell @jbalboni Content recommendation for Card/List screens. I'm recommending that we group the cards under subheads: Upcoming appointments, Canceled appointment, and Pending appointments.  Can you let me know if that's possible? 

-----

{page title} **VA appointments**

**Create a new appointment**
Schedule a new appointment at a VA medical center or Community Care facility. 

{button} Schedule an appointment

Cards
**Upcoming appointments**
{new card}
{icon} Confirmed
{Date and time} November 26, 2019 at 10:00 a.m. ET
{location}
{type of visit}

**Canceled appointments**
{new card}
{icon} Canceled – This appointment has been canceled.
{Date and time} November 26, 2019 at 10:00 a.m. ET
{location}
{type of visit}

{new card}
{icon} Canceled – This appointment has been canceled.
{Date and time} November 26, 2019 at 10:00 a.m. ET
**Community Care appointment**
{location}
{type of visit}

**Pending appointments**
{new card}
{icon} Pending – The time and date of this appointment are still to be determined.
Appointment request for {type of appointment}
{location}
{type of visit}

**Comment by jbalboni** [comment]
@peggygannon That's up to @rtwell, but we had them more divided up before (albeit on different pages) and I believe we switched to the single list design based on user research.

**Comment by rtwell** [comment]
yes, we're sticking with the single list view for now
