### ISSUE TITLE
Draft proposed Levels of Service doc

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2225]
## Problem Statement
How might we define tiers of VSP Content & IA support for VFS teams, so that they know what we are able to do with and for them, and what they are expected to do themselves? 

## Goals
Create a proposed "Levels of Service" document that can be shown to VSP leadership for feedback. (This will then be iterated on and distributed to VFS teams as needed). 

## Definition of Done
- [x] Brainstorm examples of requests that fall on the spectrum of support for VFS teams
- [x] Meet to discuss and align on what we are able to offer, make adjustments to proposal as needed
- [x] Distribute doc to VSP leadership for feedback

Working document: https://docs.google.com/document/d/1SL6vN2nFIBJKiaG5SvyWHsofbQJQmE06PT1mrG7b0EM/edit#

**Comment by peggygannon** [comment]
@meganhkelley Can this move into Validate or Closed?

**Comment by meganhkelley** [comment]
Oh yes of course! Closing. 

Documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/content-ia-support-levels.md
