### ISSUE TITLE
google-api-client production gem minor version update

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#22258]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the google-api-client gem (production group) to it's latest minor version 

---
## Tasks
- [ ] CI make target passing locally 
- [ ] Reviewed gem change log updates

**Comment by LindseySaari** [comment]
The latest version (0.53.0) is dependent upon [two other gems ](https://github.com/googleapis/google-api-ruby-client/blob/master/google-api-client/google-api-client.gemspec#L36-L37). Those are dependent upon"googleauth", "~> 0.14". Google auth is being updated in a separate PR and will need to be merged in first before this one

**Comment by jeff2d2** [comment]
@jeff2d2 to create ticket for ^
