### ISSUE TITLE
faraday production gem minor version update

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#22252]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the faraday gem (production group) to it's latest minor version 

---
## Tasks
- [ ] CI make target passing locally 
- [ ] Reviewed gem change log updates

**Comment by annaswims** [comment]
Looks like we're a few years and a major version behind. I ran into this today when the online docs didn't with the old version of the gem we're using. 

1.4.1 - April 18, 2021 (77.5 KB)
1.4.0 - April 16, 2021 (77.5 KB)
1.3.1 - April 16, 2021 (79 KB)
1.3.0 - December 31, 2020 (78.5 KB)
1.2.0 - December 23, 2020 (78.5 KB)
1.1.0 - October 17, 2020 (78 KB)
1.0.1 - March 29, 2020 (75.5 KB)
1.0.0 - January 01, 2020 (76 KB)
1.0.0.pre.rc1 - July 08, 2019 (42.5 KB)
0.17.4 - February 06, 2021 (71 KB)
0.17.3 - December 31, 2019 (70.5 KB)
0.17.2 - December 31, 2019 (70.5 KB) yanked
0.17.1 - November 27, 2019 (69.5 KB)
0.17.0 - October 06, 2019 (39.5 KB)
