### ISSUE TITLE
rails production gem minor version update

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#22271]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the rails gem (production group) to it's latest minor version 

---
## Tasks
- [x] CI make target passing locally 
- [x] Reviewed gem change log updates

**Comment by LindseySaari** [comment]
This is a bit of a rabbit hole. I ran into many depreciation issues and failing specs when trying to upgrade

Here's what I tried:
1. Upgraded rails version constraints in main app and engines
2. Had to update rgeo-activerecord because of broken support https://github.com/rgeo/rgeo-activerecord/issues/54
3. Breaking change in activerecord-postgis-adapter — ran bundle update activerecord-postgis-adapter

Issues: 
PaperTrail 10.3.1 is not compatible with ActiveRecord 6.1.3. — updated paper trail????
Tons of failing specs related to rails 6.1 upgrade
DEPRECATION WARNING: Enumerating ActiveModel::Errors as a hash has been deprecated
Changing errors[:user] << to errors[:user].add

**Comment by ericboehs** [comment]
Let's merge this into #18862.

**Comment by jeff2d2** [comment]
@jeff2d2 to merge

**Comment by LindseySaari** [comment]
Had to revert [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/6979) due to an issue with bootsnap being in the incorrect gem group. [New PR](https://github.com/department-of-veterans-affairs/vets-api/pull/7260) ready to go for Monday after the holiday

**Comment by jeff2d2** [comment]
:shipit: The PR for Rails 6.1 has been merged, migrations ran, and is now live in prod. @LindseySaari good to close?
