### ISSUE TITLE
Common component: Unread message count tag

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22295]
## Acceptance Criteria
1. Create common component for the unread message count tag
     - This is used in the Messages button on the Health screen to show the unread message count
2. This component will ultimately be inserted into card button
3. Specs:
     - Background-color: gray-dark #323a45
     - Color: #fff
     - Text: Mobile Body Bold
     - Padding: 
          - top/bottom: 5px;
          - left/right: 10px;
4. The width will increase dynamically for longer numbers (e.g. 333 unread messages)
5. Hook this up to the Messages card button on the Health page
6. Add specs to ReadMe

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364857
![Screen Shot 2021-04-01 at 9.43.33 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9d10f072-1c42-487c-97ab-14009f7a3be6)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/23/2021 - Looks good on Android and iOS.  Closing.
