### ISSUE TITLE
Text in to create vaccine appointment - Veteran Initiated Messages

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#22291]
### Notes
Similar to Vax / pass 

Different approaches:

request type with parameters for message
whatever cohorts are active
automated approach where VEText looks for availability for any clinics associated with that site, hard coded end date?

default to last center where the vet had an appt?
return a message with facilities they've been to in the past

different request type - cohort section is not active. 
need to define a fixed date range (ie 2 weeks out)

phone number has to be registered with VA or they get an autoresponse. 

Send "Vaccine" to get a message. 

This is actually a pretty cool idea.

The facilities setup general vaccine clinics in the portal.  Advertise on social media, "text vaccine to schedule an appt".

Then we can schedule the appt in any slot in the clinic.  (look up their # number in the sta3n_icn table,  give them a choice if there is more than one record found?)

The vets would drive it, so in theory the opt-out rates wouldn't be impacted, for spamming.

I guess the biggest issue would be the 2nd dose dilemma.

Maybe I am oversimplifying it.

Good Afternoon,

Is there a way to have VEText allow Veterans to text “Vaccine” or something like that to the VEText number and then be prompted to self-schedule?  We are now open to all patients for scheduling and this would be helpful in filling our clinics.

----

From: Travis, Lauren M
Sent: Friday, March 26, 2021 2:52 PM

Good Afternoon,

Is there a way to have VEText allow Veterans to text “Vaccine” or something like that to the VEText number and then be prompted to self-schedule?  We are now open to all patients for scheduling and this would be helpful in filling our clinics.

**Comment by snyderje** [comment]
Sketch of possible implementation in portal

![VeteranInitiated.jpg](https://images.zenhubusercontent.com/602c49961617aa4bd4216173/384b03b8-1395-48d2-a42c-03f321b9491d)

**Comment by Kennon-git** [comment]
released in to prod. functionality is out. waiting on communication to sites and config for their VEText setup.
