### ISSUE TITLE
Conduct content audit of downtime banners

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2230]
As a content expert, I want all of the downtime banners to have clear messaging consistent with our style guide so that VA.gov users have a good experience.

AC:

- [x] Use list generated in #2208 to audit content of downtime banners
- [ ] Create tickets for follow up work needed based on state of the banners
- [x] Discuss with dev if any of the downtime/maintenance messages can be more actionable/specific

**Comment by meganhkelley** [comment]
@peggygannon screenshots of the downtime banners have been gathered in #2208! Take a look and let me know if you think you'll have time to get to this in Sprint 10, or if it will need to continue into Sprint 11

**Comment by peggygannon** [comment]
@meganhkelley The downtime banner messages currently listed in ticket #2208 are consistent with our content styleguide (tone and voice). However, I would like to explore further if we can give users a more actionable step for some of them. 

Some of the notifications ask users to "check back soon," but they don't provide a timeline to do so (should they check back within a day? 24-48 hours?). 

Also I want to explore if we can give users another way to resolve if they experience the issues for more than a day?  (call the help desk? troubleshoot another way?). 

I will need to work with a dev to find out if we can *be* this specific in these notifications. I will document my findings here in this ticket. 

cc @emilywaggoner @CrystabelReiter

**Comment by peggygannon** [comment]
Per conversations with dev, at this time we can't put a more specific timeframe for these maintenance downtime banners. Rarely would they go longer than 24 hours.

**Comment by meganhkelley** [comment]
Iterations on downtime banners tracked in #3915
