### ISSUE TITLE
508-defect-4, health services, list under "mental health care" not complete.

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#22304]
Label: 18928

    - [508-defect-4]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4

Issue Title: Defect level 4, health services, list under "mental health care" not complete.
Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

User Story or Problem Statement:

<h2>Details</h2>
Under "Mental health care behavioral health," there is a list element containing a list of issues for which a vet can seek health. Aggressive or self-harming behavior is listed, but not contained within the list element. This could cause confusion for some users.

<h2>Acceptance Criteria</h2>

- [ ] The item ""Aggressive or self-harming behavior" is contained within the list element.
 
Environment

Steps to Recreate

Proposed Solution (if known)

WCAG or Vendor Guidance (optional)

Screenshots or Trace Logs

**Comment by laflannery** [comment]
This is resolved and the list is complete.  Will close in 1 week unless told otherwise
