### ISSUE TITLE
508-defect-4: health services, duplicate links for Erie VA Medical Center

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#22306]
Label: 18928

    - [508-defect-4]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4

Issue Title: Defect level 4, health services, duplicate links for Erie Health care
Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

User Story or Problem Statement:

<h2>Details</h2>
Under Health Services, extended care and rehabilitation, there are duplicate links for "Erie VA Medical Center."

<h2>Acceptance Criteria</h2>

- [ ] One of the links to Erie VA Medical Center has been removed. 

<h2>Environment</h2>
Tested with JAWS and NVDA and got visual confirmation to ensure the issue wasn't unique to screen readers.

Steps to Recreate

Proposed Solution (if known)

WCAG or Vendor Guidance (optional)

Screenshots or Trace Logs

**Comment by laflannery** [comment]
This is no longer relevant.  Will close in 1 week unless told otherwise
