### ISSUE TITLE
Community Care USe Case #1

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#22300]
Add URL to message (shortened)
https://www.va.gov/communitycare/#:~:text=The%20VHA%20Office%20of%20Community%20Care%20administers%20health,family%20member%E2%80%94like%20health%20care%2C%20disability%2C%20education%2C%20and%20more.

- [x] need to create shortened url. 
- [ ] julia to determine how to include url in content - text change.

**Comment by Kennon-git** [comment]
shane to provide a shortened url

**Comment by shanemelliott** [comment]
Shortened URL:  https://go.usa.gov/x64hN

Rob, please add to the messages.

**Comment by Kennon-git** [comment]
"nobody knows what community care is, can you add this URL to messages?"

**Comment by snyderje** [comment]
We are following up on the COMMUNITY CARE DENTAL appointment you elected to schedule outside of VA. We sent you a letter with contact info for the provider. 

If you have scheduled the appointment, reply with the date and time of the appointment.
If care was provided by VA, reply V2
If care was provided by other health insurance, reply H3
If care is no longer required, reply X1

More info about Community Care: https://go.usa.gov/x64hN
For assistance, call 727-398-3252.
Reply STOP to end messages.
