### ISSUE TITLE
DebtRes FSR Moderated UAT

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#22317]
In order to QA the online FSR in production we need to have Veterans who can log into VA.GOV log in, fill out and submit FSR form. 

Number of Veterans - 

Veteran Criteria -

**Comment by leahkeeler** [comment]
This is live production testing which has uncovered 4 back-end issues that are addressed under different PR's 
1-API parameter mismatch
2-pre-fill not populating
3-fe- schema not populating address

**Comment by rileyorr** [comment]
I'm assuming this is completed because we've launched the tool!
