### ISSUE TITLE
VRRAP: Create form

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22315]
As a veteran, I need a way to apply for the Veteran Rapid Retraining Assistance Program so that I can receive benefits for additional training to increase my ability to try and find new employment opportunities.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The form page is located at the URL: https://[environment].va.gov/vrrap/form
2. The breadcrumb of the page is: Home > Education and training > Other VA education benefits > Veteran Rapid Retraining Assistance Program
    a. Home - URL when active: https://[environment].va.gov/
    b. Education and training - URL when active: https://[environment].va.gov/education/
    c. Other VA education benefits - URL when active: https://[environment].va.gov/education/other-va-education-benefits/
    d. Veteran Rapid Retraining Assistance Program - URL when active: https://[environment].va.gov/vrrap/introduction
3. The title of the page is: Veteran Rapid Retraining Assistance Program (VRRAP)
4. The application supports capturing the following data with the corresponding attributes in a single section:
    a. First Name (required)
    b. Middle Name
    c. Last Name (required)
    d. Suffix
    e. Social Security Number (required)
    f. Date of Birth (required)
    g. Mobile Phone number (required)
    h. Alternate Phone number
    i. Email address (required)
    j. Country
    k. Street Address (Line 1) (required)
    l. Street Address (Line 2)
    m. City (required)
    n. State (required)
    o. Postal Code (required)
    p. Account Type (required, if the applicant opts to provide)
    q. Routing Number (required, if the applicant opts to provide)
    r. Account Number (required, if the applicant opts to provide)
    w. If they have selected a program (required)
    t. Provider name
    u. Program name
    v. Program location (city, state)
    w. Program type (in person, online, both)
    x. VRRAP confirmation
5. The user has the ability to opt out of providing direct deposit information.
6. The user has the ability to review their entered data prior to submission.
7. The user must acknowledge the privacy policy prior to submission.
8. The user has the ability to submit the application:
    a. While authenticated
    b. While unauthenticated.
9. The content of the page matches that as specified in SA1.
10. The layout of the page matches that as specified in SA2.

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/77027d16d9810b0e3134551dd796dcbdaf2179ac/products/education-careers/application/VRRAP/design/content-doc.md#intro-page)
2. [Prototype](https://bahdigital.invisionapp.com/share/CUIAGI923MB#/screens/296058330)

**Comment by zurbergram** [comment]
Refactor PR (unrelated to actual changes just cleanup and tweaks related to overall form)
https://github.com/department-of-veterans-affairs/vets-website/pull/16559

This will resolve AC2 and AC3.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6379

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16622

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/1618&group_by=cases:section_id&group_order=asc)

**Comment by delli-gatti-michael** [comment]
Testing complete
