### ISSUE TITLE
VRRAP: Wire up complete form submission experience

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22328]
As a veteran, I need to receive a confirmation that my application has successfully been submitted so that I have an artifact to reference if I need to contact the VA.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The submission confirmation page is located at the URL: https://[environment].va.gov/vrrap/confirmation
2. The user is provided a confirmation number.
3. The breadcrumb of the page is: Home > Education and training > Other VA education benefits > Veteran Rapid Retraining Assistance Program
    a. Home - URL when active: https://[environment].va.gov/
    b. Education and training - URL when active: https://[environment].va.gov/education/
    c. Other VA education benefits - URL when active: https://[environment].va.gov/education/other-va-education-benefits/
4. The content of the submission confirmation page matches that as specified in SA1.
5. The layout of the submission confirmation page matches that as specified in SA2.
6. The user is able to navigate:
    a. From the form introduction page (https://[environment].va.gov/vrrap/introduction) to the form page (https://[environment].va.gov/vrrap/form).
    b. From the form page (https://[environment].va.gov/vrrap/form) to the form review page (https://[environment].va.gov/vrrap/review-and-submit)
    c. From the form review page (https://[environment].va.gov/vrrap/review-and-submit) to the submission confirmation page (https://[environment].va.gov/vrrap/confirmation) on submission.
7. The applicant has the ability to print the submission confirmation page.

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/files/6250778/vrrap_content_final.txt)
2. [Prototype](https://bahdigital.invisionapp.com/share/CUIAGI923MB#/screens/296058389)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16632

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/1622&group_by=cases:section_id&group_order=asc)

**Comment by delli-gatti-michael** [comment]
Closing out
