### ISSUE TITLE
VRRAP: Add two new fields to schema

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22338]
As a developer, I need to update the schema for the VRRAP application so that UI and spool file development can begin in parallel.

## Assumptions:
1. This work does not need to be completed behind a prod or feature flag.
2. All data collected will need to be available for inclusion in the spool file.

## Acceptance Criteria:
The schema supports capturing the following data elements with the corresponding attributes:
1. Street Address (Line 3)
    - Note: This is related to the address information
2. Bank Name
    - Note: This is related to the direct deposit information
 3. The Street Address (Line 3) is included in the spool file document for the submission.
 4. The Bank Name is included in the spool file document for the submission.

## Supporting Artifacts:
1. [vrrap_mock_spool_formatv4.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6224292/vrrap_mock_spool_formatv4.docx)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/575

**Comment by ksantiagoBAH** [comment]
vets-api pr: https://github.com/department-of-veterans-affairs/vets-api/pull/6362

vets-website pr: https://github.com/department-of-veterans-affairs/vets-website/pull/16594

**Comment by zurbergram** [comment]
22338 is OBE due to reconsideration of technical ramifications for other forms.
