### ISSUE TITLE
Second Dose: COVID-19 Vaccine Scheduling 

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#22341]
[PDF of Two Possible Workflows](https://app.zenhub.com/files/133843125/1926ac19-1111-4eee-816c-ac8264489f59/download)
This pdf includes two possible workflows for scheduling the second dose at the same time as the 1st dose is scheduled.
* The workflow in the purple box allows Vets to schedule any available time on the day +28 days after their first dose
* The workflow in the orange box offers Vets to only schedule in the exact same time as their 1st dose time, on a day 28 days later, or to call.

 - [x] Draft of possible workflows

**Comment by Kennon-git** [comment]
tabled for now
