### ISSUE TITLE
[Bug] Financial Status Report - Content/Styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#22349]
## What happened?
On Staging, **[Request help with VA debt (VA Form 5655)](https://staging.va.gov/manage-va-debt/request-debt-help-5655/)** (FSR) form, the following content/styling anomalies were found:

### Device-/browser-agnostic:
- **Step 2 of 7: Household Income > Your spouse information**: Form-page subtitle content didn't match prototype.

### Mobile:
- **Step 4 of 7: Household expenses > Installments**: After adding an installment debt, form-page subtitle and body-text was missing vertical spacing.

## Specs:
- Devices: [so far, Win10 PC desktop, iPad, but I'm surmising it's device-agnostic]
- Browsers: [so far, Win IE11, Safari, but I'm surmising it's browser-agnostic]
- Test User _(if applicable)_:
  - `vets.gov.user+228@gmail.com` (Colder)
  - `vets.gov.user+14@gmail.com` (Jerry)
  - `vets.gov.user+1@gmail.com` (Greg)

## Steps to Reproduce
- URL: https://staging.va.gov/manage-va-debt/request-debt-help-5655/
- Test User _(if applicable)_: [see **Specs** above]
- Sign-in as needed, advance as needed to each form-page listed, and observe each anomaly listed.  [See **What happened** above.]

#### Step 2 of 7: Household Income > Your spouse information:
![bug-spouse-other-income-subtitle](https://user-images.githubusercontent.com/587583/112912807-49fd2180-90ad-11eb-960b-fc4b1bf43860.png)

#### Step 4 of 7: Household expenses > Installments:
![bug-mbl-installment-subhead-body-text-no-spacing](https://user-images.githubusercontent.com/587583/113493856-23b5f800-9498-11eb-9625-0bf7735154a9.png)

## Desired content/styling
[See pages list in **What happened** above]

### Device-/browser-agnostic:

- [x] **Step 2 of 7: Household Income > Your spouse information** form-page subtitle should be **Your spouse information**: 
    ![spec-spouse-other-income-subtitle](https://user-images.githubusercontent.com/587583/112912814-508b9900-90ad-11eb-8abf-9baf76e8436c.png)

### Mobile

- [x] **Step 4 of 7: Household expenses > Installments** form-page subtitle and body-text should have vertical-spacing.

## Acceptance Criteria
[See **Desired content/styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by rebeccawalsh** [comment]
@craigwheeler I'm pretty sure you took care of the "Your questions information" part, but have you addressed the second problem / spacing on mobile?

**Comment by craigwheeler** [comment]
sorry @rebeccawalsh been caught up with FSR bugfixes and just recently pushed updates to fix the mobile styling issue so we should be good close this now

**Comment by LinnJS** [comment]
@tlei123 ready for validation when you get a moment

**Comment by tlei123** [comment]
Sorry, @LindaLi123 !  The following anomalies still exist:

- [ ] **Step 2 of 7 Household income** > **Spouse** > **other sources**

![fsr-spouse-income-other-sources](https://user-images.githubusercontent.com/587583/121971368-6d8b4c00-cd2d-11eb-9c7a-a47aa591ef18.png)

**Comment by LinnJS** [comment]
Will take a look at this one today.

**Comment by LinnJS** [comment]
Got the [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17601) open for the final fix on this ticket will have it merged ASAP.

**Comment by craigwheeler** [comment]
Hi @tlei123 ... I believe all changes have been merged at this time so please let us know if theres anything else we should update otherwise we should be good to close this ticket once fixes have been verified on your end ... thanks!

**Comment by tlei123** [comment]
@craigwheeler , final fix validated on Staging.

![image](https://user-images.githubusercontent.com/587583/123680725-e4304b00-d7fd-11eb-8814-8bb43df77a27.png)
