### ISSUE TITLE
[Bug] Financial Status Report - Review page - Spouse subsection updates auto-scroll up to Vet's subsections

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#22355]
## What happened?
On Staging, **[Request help with VA debt (VA Form 5655)](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction)** (FSR) form, **Review application** page, editing some Spouse employment/income subsections auto-scrolled away from edited subsections, back up to Veteran's corresponding subsections upon clicking **Update**:
- Spouse employment [current] > Payroll deductions
- Spouse employment [previous]
- Spouse additional income

The pattern seems to be IF a Spouse subsection has a corresponding Veteran equivalent, then updating that subsection auto-scrolled back up.

## Specs:
- Device: [so far, Windows 10 PC, iPad but I'm surmising this is device-agnostic]
- Browser: [so far, Windows IE11, Safari but I'm surmising this is browser-agnostic]
- Test User _(if applicable)_: 

## Steps to Reproduce
- URL:  https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction
- Test User _(if applicable)_:
  - `vets.gov.user+228@gmail.com` (Colder)
- Advance through form-pages, completing required-fields at least for **Veteran & Spouse current-jobs (incl. Deductions), previous-jobs, and additional incomes**.
- On **Review** page, edit Spouse current-job deductions, previous job, and additional income subsections.
- Observe that after clicking **Update** for each edit, browser auto-scrolls away from Spouse subsection, back up to Veteran's corresponding subsection.

**Video capture** [Spouse employment [current] > Payroll deduction example]

https://user-images.githubusercontent.com/587583/112919250-951e3100-90bb-11eb-87b0-7977ae6a4290.mp4

## Desired behavior
Editing a Spouse employment/income subsection, browser should NOT auto-scroll up to Veteran's corresponding subsection after clicking **Update**.

## Acceptance Criteria
- [ ] [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by leahkeeler** [comment]
Can this please be validated and closed?

**Comment by tlei123** [comment]
@LinnJS , I just did a quick check in Mac Chrome...

While I validated fix for Spouse previous-employment and additional-income subsection-edits, her **payroll-deductions subsection** was not editable.  When you click a deduction-row's **Edit** link, this is what you get instead of an edit-form:
![image](https://user-images.githubusercontent.com/587583/117052509-a830ac00-accc-11eb-8dce-25f3f837693e.png)

Let me know if this should be a separate ticket.

**Comment by LinnJS** [comment]
This needs to be re-check by a FE dev to see if its ready for validation or to fix it. If its fixed we can kick back to Tze to re-check and if its not fixed we can open a new ticket.

**Comment by LinnJS** [comment]
This one is kinda confusing because it works one way but no the other... So if the review panel is not in edit mode it will not let you edit the fields even though the UI says you can edit it. So its a bit of a UX conflict. Perhaps we can just made it edit mode on default so we do not have this conflict anymore... See video below. Took me a good 15mins to understand as I felt like I could and then could not reproduce.  

https://images.zenhubusercontent.com/133843125/e98b4aae-f4d1-441a-9c0
4-58857c112557/review_page_payroll_bug.mp4

**Comment by LinnJS** [comment]
Opened up this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17452) but need to get design feedback to see if the trade off in UI is worth the benefit of the UX.

**Comment by tlei123** [comment]
Fix validated on Staging.
