### ISSUE TITLE
Create Top 5 list of content validation warnings

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2235]
## Goal(s)
Create a list of "top 5" content validations that can be used in the MVP of automated content checker.  

## Definition of Done
- [x] Based on VA.gov content style guide and @peggygannon's experience as a content expert, select top 5 top content validations to be used in MVP of plain language linter for VA.gov tools and applications

**Comment by peggygannon** [comment]
Hi, @kfrz Please see below my recommendation of the top 5 content errors/validations to use in the plain language linting MVP. Let me know if you have any questions and/or it you want to sync about this on call. thx!

**1. Contractions**
We should use contractions on VA.gov. (for example, don't, can't, we're, what's) 
Some exceptions below: 
--Be careful not to mix up “its” and “it’s.”
--Use “it’s” for a contraction of “it is,” never “it has.”
--Don’t use non-standard contractions like “would’ve,” “could’ve,” or “should’ve.”

**2. Conversational tone**
 When referring to VA, use the first-person pronoun (we, us, our). 
When referring to Veterans, service members, family member, use the second person pronoun (you, your) 

**3. Sentence-case capitalization**
We use sentence-case capitalization for most content, including page titles, headings, subheadings, buttons, and text links unless a word is a proper noun. 
(Examples of proper nouns: “VA.gov,” the word “Veteran" or "Veterans," official VA program names, state names, names of federal agencies, days of the week, months, book titles, )

**4. Time**
--Write out times, using a.m. and p.m. with periods: for example, 9:00 a.m. NOT: 9 am or 9 a.m.
--Spell out noon and midnight. Don’t use 12:00 p.m. or 12:00 a.m.

**5. Specific style and formatting of commonly used words on VA.gov **
--service member: this should be lowercase and two words. Don't write as Servicemember
--active duty: Hyphenate when it modifies a noun and don’t capitalize. (for example, active-duty service member
--federal: don't capitalize for generic usage (for example, federal agency)
--GI: this shouldn't have any periods. Don't write as G.I.
--PO Box: this shouldn't have any periods. Don't write as P.O. Box
--service connected: Don't hyphenate unless it appears before a noun (for example, service-connected disability)
--sign in, sign out: We use sign in/sign out on VA.gov. Don’t use log in, log out, login ID, or sign on.

cc @meganhkelley

**Comment by peggygannon** [comment]
Closing this issue, As the content recommendations are done. Next step is to begin non-technical discovery work.
