### ISSUE TITLE
0994: Update spool file to include form field updates

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22359]
As a RPO processor, I need the new information gathered during the application process included in the spool file so that I can effectively process the application.

## Assumptions:
1. This is behind the 0994 spool file feature flag (edu_form_omb_and_expiration #18293).

## Acceptance Criteria:
1. The question "Enter the date you expect to be released from active duty:" is included in the spool file document.
    a. The user provided answer is included in the format [YYYY-MM-DD]
2. The question "Do you expect to be called to active duty while enrolled in a VET TEC program?" is included in the spool file document.
    a. The user provided answer (Yes or No) is included.
    b. If no user provided answer than "N/A" is included.
3. The question "Are you in the Selected Reserve or National Guard and do
you expect to be called to duty for 30 days or more?: " is not included in the spool file document.

## Supporting Artifacts:
1. [0994_spool_updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6228810/0994_spool_updates.docx)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6353

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2021-03-30 at 1.26.46 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2654ef80-6417-487a-a8d2-c84675d007cf)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1584&group_by=cases:section_id&group_order=asc)

**Comment by dneel-bah** [comment]
EDU confirmed production spool file as of 03/31 has the correct fields.
