### ISSUE TITLE
Folders list page displays empty content 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22357]
## What happened?
On the **Folders** tab of the Messages page, the page content doesn't always load/appear as expected. It loads when navigating to the **Inbox** tab, then back to **Folders**. However - when I go back to **Inbox** and back to **Folders**, the content disappears again.

See attached video.

## Specs:
- Device: iPhone 11
- Test user: vets.gov.user+261@gmail.com

## Steps to Reproduce
1. Log in with a new session.
2. Navigate to the Messages page, where **Inbox** is the defaulted segment.
3. Select the **Folders** segment. Notice how all page content below Header 2 does not appear. 
4. Go back to the **Inbox** segment.
5. Select the **Folders** segment again. Notice how the page displays a loading spinner, and the page content loads. 
6. Repeat steps 4-5. This time, notice how the **Folders** page content disappears again like it did in step 3. 

## Desired behavior
App should not display blank screen on the Folders page. 

## Acceptance Criteria
1. As the app works to load in the page content for the first time, display a loading spinner
2. Once the page content loads, it should still display if the user navigates away and returns to that page
     - The app should never display a partially-empty (or fully empty) screen. If the app needs to reload page content, it should display a loading spinner in the interim. 

## Bug Severity 
- 3- Medium

## Linked to Story
n/a

## Video
https://images.zenhubusercontent.com/133843125/f3b0fbc3-b9ca-4cca-897e-5dd9c6b0241c/image_from_ios__1_.mp4

**Comment by digitalken** [comment]
PASS 4/9/2021 - This looks good now on iPhone XR.  Closing.
