### ISSUE TITLE
[BE Tools] Next gen BE http request handling (Discovery)

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#22350]
## Problem Statement 
HTTP requests handling, both form submissions and data fetching requests, on VA.gov is leading to lackluster stability, security, scalability and consistency on VA.gov. The following doc shows the suggested new architecture change to the [VA.gov request handling](https://vfs.atlassian.net/wiki/spaces/VI/pages/1100021768/Next+generation+form+handling). There are many moving pieces to this suggested architecture so we need to complete a discovery effort on feasibility of this work, how we can break it up, the priority in each of these pieces of work, and a timeline for completion.

Secondly, in #26743, we'll focus on building a prototype of a queue for additional stability, security and scalability.

## Hypothesis or Bet
If we take the time to complete a discovery effort, we can quickly identify feasibility and come up with a game plan to complete this whole large project. 

## We will know we're done when... ("Definition of Done")

- [x] #28291
- [x] #28293
- [x] #28294

## Known Blockers/Dependencies 
None at this time

## Projected finish for discovery
End of Q3 2021

**Comment by drorva** [comment]
These should really be two separate epics.
* Discovery on next generation backend form handling
* Prototype separate backend into two: queue and processor
