### ISSUE TITLE
Samsung phone not respecting right margin on certain pages

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22358]
## What happened?
1. On the Direct Deposit form, the checkbox field error touches the right edge of the screen. Should be seeing a line-wrap on "correct". 
2. On the Claims Decision form, the checkbox field error touches the right edge of the screen. Should be seeing a line-wrap on "is correct".

## Specs:
- Device: Samsung Galaxy S9
- Claims Decision issues: vets.gov.user+366@gmail.com

## Steps to Reproduce
- On a Samsung Galaxy S9, observe the following pages:
     -  Direct Deposit form page
     - Claims Decision form

## Desired behavior
Right margin is maintained.

The design library indicates a 20px gutter: https://adhoc.invisionapp.com/d/main#/console/21114574/445194518/preview

## Acceptance Criteria
Right margin is maintained.

## Bug Severity 
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information
![Screenshot_20210329-214000_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/09082b8c-4a3b-41ea-bd2b-5777d0c32a4d)
![Screenshot_20210329-221001_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/56d6516a-9c83-4978-9de9-ca8a32477b85)

**Comment by kxiao133** [comment]
^Only fixing the checkbox error right margins
The other right margin error has to do with samsung and involves a different process

**Comment by digitalken** [comment]
PASS 4/7/2021 - Get the line wrap to keep error text away from edge of page.  Closing.
