### ISSUE TITLE
Access for Calvin Gonzalez

### ISSUE THREAD

**Issue by Cgfor3** [department-of-veterans-affairs/va.gov-team#22369]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Calvin Gonzalez
- Please Provide your email.
   > calvin.gonzalez@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > FE Tools, Software Engineer, Oddball

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEr2YW+8gsI5vOAvld30QWFtPprIv7rVGPqRoyW898HB calvin.gonzalez@oddball.io
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why?
  > Review instances for front-end tools and debugging purposes

**Comment by jsev-io** [comment]
cc: @Jeff-Hayter 
Requesting AWS Approval

**Comment by mleclerc00** [comment]
@Jeff-Hayter 

Looking for approval so we can move forward with AWS access

**Comment by Cgfor3** [comment]
PRs granting SOCKS access
- https://github.com/department-of-veterans-affairs/devops/pull/8896
- https://github.com/department-of-veterans-affairs/devops/pull/8914

Still awaiting confirmation of AWS access being granted

**Comment by mleclerc00** [comment]
@drorva 

Given Jeff is no longer approving AWS access requests, is this something you can sign off on?

Thanks!

**Comment by drorva** [comment]
I can.
Do we grant AWS access to all FE tools folks?
If yes, this request is approved.
