### ISSUE TITLE
Display "Letters - Empty" UI when it's an unauthorized service

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22368]
## User story
As a user, if I don't have permission to access Letters & Documents, I want to see a screen informing me that  I'm unable to access this feature, along with guidance on what to do next.

_Note for dev: currently, it looks like the app displays a Generic Error State w/ Refresh on the Letters List page if the letters service is 'false'. This ticket will replace that._

## Acceptance Criteria
1. When the letters service is 'false' in the authorized service list, the following should occur:
     - On what would be the letters list page, display the "Letters (Empty)" UI (#16035)
2. Update the UI for this screen to also display a TTY / 711 component (#21363). The TTY component should appear below the 800- number.

## For testing:
- User: +2

## Designs
https://adhoc.invisionapp.com/d/main#/console/20546460/434420520/preview

**Comment by bessgreen** [comment]
Hi @bridgethapner, wanted to review this with you: if a user doesn't have permission to access Letters, how do we want the app to handle this? Here are a few options:

1. Hide the Letters feature completely from the app (including the button on the Home page). We're doing something similar for Direct Deposit & Contact Information.
2. Keep the Home page button & the ListItem button on the Profile page. When they get to what _would_ be the Letters List page, display the null state UI (or something similar): https://adhoc.invisionapp.com/share/YUYRT9BAPSB#/screens/434420520

Open to any / all ideas!

**Comment by bridgethapner** [comment]
Hi there @bessgreen - Looking at staging for user +2 I see the same null state (screenshot below), so let's use the same null state for 'false' in the app.

![Screen Shot 2021-04-08 at 4.55.12 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/479fcbce-38e9-4279-b5d3-7b897539db33)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
@keli13 - I'm getting some funny stuff going on with this using user +2.  Would you take another look at this guy?  Putting it back in "In progress" for you.

**Comment by digitalken** [comment]
PASS 5/10/2021 - Looks good on Android and iOS. Closing.
