### ISSUE TITLE
Determine technical approach for MVP of vale 

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2236]
## Goal(s) 
- Collaborate with other teams and engineers, and conduct research as needed, to determine the most feasible technical approach for MVP of plain language linter
- Propose answer to high level question: Where will users (VFS teams) encounter this in their process? 

## Definition of Done
- [x] Technical approach for MVP of vale plain language linter has been determined
- [x] Next steps have been captured as issues within epic #2233

**Comment by kfrz** [comment]
@cvalarida and I did some brainstorming and discussion on this and we think there's a viable path forward that looks something like this:

**Proposed Issues & AC AC (subject to revision)**:

- Add the `vale` dependency to `vets-website`
  - `Dockerfile` is updated to contain the `vale` plugin
  - Documentation is updated with instructions on how to install dependency locally
- Create a metalsmith plugin `plainLanguageLinter`
  - Locally, `yarn preview` ignores the `plainLanguageLinter` plugin if dependency is not in `PATH` 
  - Plugin is applied at a point in metalsmith build where data is in `HTML` or other lintable format
  - Plugin is called in a child process
  - Plugin child process is properly handled
- Inject output warnings and errors into page
  -   Plugin output is modified into a proper `.js` object
  -   Warnings and errors from are added to the HTML content

##### Some notes: 

- [`vale`](https://github.com/errata-ai/vale) is a `go` binary, which can run on the preview server
- We will want to execute the `vale` linting command on a [child process](https://stackoverflow.com/questions/20643470/execute-a-command-line-binary-with-node-js)
? What does the shape of the `.js` object in metalsmith look like?
? At which point in the metalsmith build can we get to the HTML object in out plugin?
- We can save error output tmp `.json` format, & output to a file
- Error output will be interleaved into the HTML
----

**Comment by cvalarida** [comment]
Probably worth noting: I don't know how well the `PATH` check is going to work in Windows. We may need to have some other way to determine if the command is available. Not sure yet.

**Comment by kfrz** [comment]
Updated the epic #2233 with the above issues. Closing this as DOD is fulfilled.
