### ISSUE TITLE
Co-Branding Screen Design and Research

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#22370]
Create card sort. 
Two separate card sorts to be sent to two different groups. 
Design screens in support of the co-branding research effort. 

Screen 1 = co-branding w/ MHV small logo
Screen 2= only VA Branding (no new design needed)
Screen 3= co-branding w/ MHV large logo
Screen 4= dummy screen 

Survey Questions: 
https://docs.google.com/document/d/1OrFHv8UqHYlDGFBmGqh2LoJl2ZZD8iW3o2KIkMtt5PU/edit?ts=60623278

**Comment by ashley-matthews** [comment]
Design screens in support of the co-branding research effort. 

Screen 1 = co-branding w/ MHV small logo
Screen 2= only VA Branding (no new design needed)
Screen 3= co-branding w/ MHV large logo
Screen 4= dummy screen 

Survey Questions: 
https://docs.google.com/document/d/1OrFHv8UqHYlDGFBmGqh2LoJl2ZZD8iW3o2KIkMtt5PU/edit?ts=60623278

**Comment by melissa-lefevre** [comment]
https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1616159194734?sender=uff1791dd79ec763420518644&key=9522341a-c040-4be0-b718-c7475343cb23

**Comment by melissa-lefevre** [comment]
I made two card sorts "VA Mobile App - Available Features 1" is with MHV branding and the "2" is without.
Preview: https://adhoc.optimalworkshop.com/optimalsort/ocf75vdy

**Comment by melissa-lefevre** [comment]
Research plan github file: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/ux-research/Co-branding%20research
