### ISSUE TITLE
Analytics KPI dashboard request for Debt Resolution - FSR Form 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#22375]
# Request a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [ ] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [ ] Your KPIs are clearly linked back to Veteran outcomes
- [ ] Link your KPIs below (KPIs should be in your Product Outline)
- [ ] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.
- [ ] New dashboard
- [X ] Iteration of current dashboard

I would like the Dashboards for Debt Portal and FSR Combined into a single view 

### KPIs
I would like the data laid out in the following format in DOMO broken out by devices

of Veterans landing page | Logged in page 
of Veterans completing | abandoning FSR online form - where the Veteran abandoned 
Time to complete FSR Form }| Time Veterans spend on each page 
How many Veterans land on Debt portal that click through to FSR 
Referring page (ie Google etc ) 
A separate card if referral is email (as part of VANofity email send, they can append url) 

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by denisecoveyduc** [comment]
@jennaouellet @chloedotbrown This is the request for FSR Domo Dashboard. hoping we can move this forward? What info do you need?

**Comment by chloedotbrown** [comment]
Hey @denisecoveyduc - I believe this product is already covered on the [Forms dashboard](https://va-gov.domo.com/page/447193050) on Domo. Want to proof this and make sure the flow hasn't changed since this was submitted?
