### ISSUE TITLE
VEText system status indication for portal users

### ISSUE THREAD

**Issue by snyderje** [department-of-veterans-affairs/va.gov-team#22380]
### Issue:
As a staff member, I can't easily tell if the VEText systems are up and running and messages are being sent as expected, or if there is a system error. Unknown system status leads to support questions about message sending timing, volume, errors, etc.

### Next steps:
- [ ] Schedule brainstorming meeting to discuss possible ways to show system health (Julia to lead)

**Comment by ambikaroos** [comment]
@snyderje  to hold a Crazy 8s ideation exercise with team on 4/2

**Comment by Kennon-git** [comment]
duplicate - been turned into other tickets
