### ISSUE TITLE
Design for Video Visit Link

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#2238]
## User Story or Problem Statement
As a veteran, if I am on iOS, I need to be prompted to download the iOS app in order to launch a video appointment.

Could use some design/content guidance for this. 

Extension of this ticket: #1772.

**Current functionality:** If you're on iOS, there's a message that you must download an app (https://itunes.apple.com/us/app/va-video-connect/id1224250949?mt=8)
   - Not sure if this is required for Android, it's not mentioned

Assuming we will display some sort of modal popup if we detect they are on iOS, maybe with options such as "Download app", "I already have the app".

## Goal
User understands that they must download an app to view video appointments on iOS

## Screenshots
![image](https://user-images.githubusercontent.com/12564977/65277208-694de280-daf7-11e9-9fd3-c3beb8160570.png)
![image](https://user-images.githubusercontent.com/12564977/65277232-74087780-daf7-11e9-9252-5cc8ba980460.png)

## Acceptance Criteria
- [ ] Design has been created
- [ ] Message is displayed to user

**Comment by narin** [comment]
CC: @markgreenburg @goldenmeanie

**Comment by jbalboni** [comment]
This is covered in recent mocks, closing.
