### ISSUE TITLE
Support for VAOS direct scheduling link in vaccine outreach messages

### ISSUE THREAD

**Issue by snyderje** [department-of-veterans-affairs/va.gov-team#22396]
Add a new template for scheduling via VAOS, will follow one-way logic.

Message Template Draft:

> %FACILITY_NAME% is offering COVID-19 vaccines.  
> 
> To schedule an appointment, go to https://go.usa.gov/xstkr or call %FACILITY_PHONE%
> 
> If you have already received, or are scheduled to receive, the vaccine: Reply VAX 
> If you do not plan to receive the vaccine: Reply PASS
> 

Removed STOP to reduce opt-out for first time VEText recipients, and removed 'More info' link to not draw attention from scheduling link, or add confusion that the links look similar but go different places. If the links are quite distinct, we could consider including both.
Just received some feedback about the PASS language, considering some changes to that phrasing and will keep you posted.

**Comment by ambikaroos** [comment]
FYI @laurenernest
