### ISSUE TITLE
Best Practice Guides - VFS Application for testing and demo of best practices

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#2239]
# Description
Transform an existing platform application by testing out and implementing VSP best practices for use as an example for other VSA teams during onboarding.

# Problems
As a platform we need a way to demonstrate best practices, optimizations and tool usage in a real world production environment so VFS teams can better understand how they could utilize them in their own applications.

# Overview:
There are many VSP best-practice initiatives (code quality, testing methodologies and tools, accessibility, front-end and back-end architecture, security, privacy, etc...) that we would like a way to test and then demonstrate to new VSA teams onboarding on the VSP platform so it is easier and more clear for them observe. We will be selecting some different platform applications that we will then use for this effort going forward.

Teams
1. HCA
2. TBD

## VSP Q1 + Q2 2020 OKRs
O5: All customers comply with the Platform's standards.
KR: % customers meeting coding standards

**Comment by rroueche** [comment]
@brandonrapp could you add KPIs to the description? what data will you be looking at to understand if these guides are improving the problem they're meant to improve?

**Comment by brandonrapp** [comment]
I moved this from the NOW epics to NEXT as we are still driving at establishing our baselines and platform standards. Once the standards are set we can look again at documenting best practices for optimization.

**Comment by f1337** [comment]
I would love to see us pick this up as one of our Q4 KRs for VSP. I have ideas™ about code isolation, testing patterns, code generators, app generators, wrapping it all in a friendly command-line UI that we someday turn into a web app…

I also see a parallel opportunity with BE Tools, to create a best practice Rails engine with similar goals.
