### ISSUE TITLE
Update toolbar button CC w/ design specs

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22400]
## Acceptance Criteria
1. Update the specs for the toolbar button (né: footer button) common component:
     - Text: Mobile Body Bold
     - Background color: #F9F9F9
     - Text color: #0071BC
     - SVG fill: #0071BC
     - Height: 44px;
     - Width: 100%;
     - Border-top: 1px solid gray-light #aeb0b5
     - Active state:
          - Color: primary-darkest #112e51
          - SVG fill: #FFFFFF
2. Update ReadMe w/ new specs

## Related ticket
#21083: Footer button (preliminary implementation)

**Comment by drjecker** [comment]
@bessgreen Spec are in the [UI style guide](https://docs.google.com/document/d/1VC-CLWnhevB8HLBBHPwkSJvECn8EBie8HOkJylKE1lo/edit#bookmark=id.30t2ug2lzf8f), but let me know if you have questions.

**Comment by digitalken** [comment]
PASS 4/7/2021 - Looks good on iOS and Android.  Closing.
