### ISSUE TITLE
Prepare Review Instance Script for Content Separation

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#22408]
Ops has requested that we update the review entrypoint script at `script/review-entrypoint.sh` to be prepared for the content separation. This script can be updated right now to check for the content-build sibling directory, if the directory exists, use it, otherwise, do what we're doing right now.

This way, the script can be merged and should just work when Ops updated the review instance docker config.

This can be updated in place or migrated into a node script, left up to the discretion of the implementing engineer.

Working PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16593
Working Branch: feature/prep-RI-script-for-content-separation

Tasks:
[ ] Update Review instance Entrypoint script
[ ] Current process is not disrupted

cc @dginther

**Comment by theodur** [comment]
The review instance script `review-entrypoint.sh` is executed in the Docker container when it's being created. Because we can't see the output of `docker-compose up` in Jenkins, we can't see exactly what's being outputted. I had to test the updates to the script differently.

I'm testing the changes by running `build` in `review-entrypoint.sh` if the `content-build` directory exists, and doing the same if the `vets-api` directory exists. Because we know the `content-build` directory shouldn't exist, and the `vets-api` directory does, we should see drastic time differences, since `build` should be executed in the latter situation and not the former.

**Comment by theodur** [comment]
I tested the updates to the review instances further by SSHing into the review instance, and manually adding the `content-build` directory there to see if the script would work as expected when `content-build` is present. After cloning the repo on the review instance and adding `content-build` to the [volumes list](https://github.com/department-of-veterans-affairs/vets-website/blob/master/docker-compose.review.yml#L19), the docker container isn't recognizing the `content-build` directory.

**Comment by theodur** [comment]
All that can updated at this time for content build in review instances has been added and merged from this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16593).

We will still need to update the following once the `content-build` directory is added to review instances:
- [ ] Add `../content-build` volume in [docker-compose.review.yml](https://github.com/department-of-veterans-affairs/vets-website/blob/master/docker-compose.review.yml#L19)
- [ ] Update ports in [docker-compose.review.yml](https://github.com/department-of-veterans-affairs/vets-website/blob/master/docker-compose.review.yml#L16)
- [ ] Remove `npm run fetch-drupal-cache` call in `script/review-entrypoint.sh`

**Comment by theodur** [comment]
The work for getting review instances ready for content-build is complete. Review instances are using the `content-build` in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16757). 

Link to review instance: http://cd633a40f80dbd05fde0102ee6e817c2.review.vetsgov-internal/

Relevant PRs to get review instances working with `content-build`:
- https://github.com/department-of-veterans-affairs/devops/pull/8940 (**Merged**)
- https://github.com/department-of-veterans-affairs/content-build/pull/80 (**Merged**)
- https://github.com/department-of-veterans-affairs/vets-website/pull/16757 (**Can be merged when launching content-build**)

I added merging the last PR to the [launch checklist](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/22451). That is all that's needed to make review instances use content build :rocket:.
