### ISSUE TITLE
Form 526 update - Program Selection

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#22402]
## Issue Description
Program selection has been changed and now contains radio buttons and allows for only 1 selection.
---
## Tasks
- [ ] Modify form - checkboxes change to radio buttons

## Acceptance Criteria
- [ ] Updated form
---

**Comment by Mottie** [comment]
No work needs to be done on the FE for this ticket

**Comment by vhenry07** [comment]
Closing complete. No FE or BE work needed.
