### ISSUE TITLE
Accordion CC accessibility issues

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#22401]
## What happened?
1.  Samsung phones pronounce VA as "vah" on file upload page (accordion page) "You have 2 file requests from VA"

2. Keyboard is unable to tab through accordion page on iOS.  (up/down arrows work, though.)

3. Keyboard can tab through, but it seems like it must be tabbing through the previous page(s) first before it tabs through the current page. It must tab through 40+ times before it starts to tab on the current page.  The keyboard is basically unusable to tab through the current page.

## Specs:
- Devices: 
1. Samsung phones with TalkBack enabled

2. iPhone XR

3. Samsung Galaxy Note 9

## Steps to Reproduce
- Visit page with talkback enabled (for "vah") and bluetooth keyboard to tab through page.

## Desired behavior
1. VA is pronounced "Vee A".

2. iOS is able to tab through the page.

3. Android is able to tab through the page without tabbing through previous page(s). 

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## Bug Severity
- 4 - Low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21984
(But the accessibility listed for the story seems to be fulfilled.)

## Screen shot(s) and additional information
For number 1.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/3fb36ac2-abdc-4236-9a76-11081362a098)

**Comment by jperk51** [comment]
Fix for Vah mobile issue is in PR: https://github.com/department-of-veterans-affairs/va-mobile-app/pull/932

Note: Keyboard issues not resolved

**Comment by digitalken** [comment]
PASS 7/15/2021 - Sounds OK on Samsung phones (VA).  Keyboard portion has been added to existing bug #17008 for the Claims accordion.  Closing.
