### ISSUE TITLE
Diagram the content build separation for Ops

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#22409]
Ops has request a diagram of the content build separation work in order to help facilitate a production release.

**Tasks**:
[ ] System diagram for the Ops team
[ ] Should include the repository processes (vets-website to apps, content-build to content)
[ ] Should include deployment information
[ ] Should include proxy information
[ ] Should be reviewed by @dginther

**Comment by timwright12** [comment]
Slide deck that contains a very high level system diagram: https://docs.google.com/presentation/d/1bGcQ1baPFrins5cxxjgtVr4XHSdsBL_5pIeQxTdKVIM/edit?usp=sharing

**Comment by theodur** [comment]
Diagram of content build separation is on LucidChart. [Chat with invitation link](https://dsva.slack.com/archives/C01S39QMSSV/p1617982994011300).

Waiting on my LucidChart license to be updated to finish the last few edits.

**Comment by meganhkelley** [comment]
@theodur could you please drop the link to the diagram in GitHub here and go ahead and close this? Thanks!

**Comment by theodur** [comment]
The Content Build Separation diagram is competed and live in the `va.gov-team` repo: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/content-build-separation-ci-cd.pdf
