### ISSUE TITLE
Data Layer Variable Clearing 

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#22412]
## Description 
Today, with www.va.gov being a single page app, there are cases where a data layer variable may persist to a subsequent event where its context/meaning/definition is not necessarily needed. 

With our design system standardization, it would be great time  to do some discovery around the best method to clear data layer variables immediately following their usage within an event. 

## Acceptance Criteria 
- [x] Research + Document a few options for clearing data layer variables following their usage
- [ ] _Stretch_: Begin mocking up that method programmatically and/or within GTM

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
Ready for your QA @jonwehausen.  You should be able to use the test build.

https://github.com/department-of-veterans-affairs/vets-website/pull/16738

**Comment by jonwehausen** [comment]
@bsmartin-ep The changes look good, however not having luck with using the review instance.

**Comment by jonwehausen** [comment]
## QA Testing

| Description of Interaction | Data Layer Screenshot | GTM Tag | Test Status | Test Notes
| -- | -- | -- | -- | -- |
Click on the promo banner (_example of a component library generated event_) | ![image](https://user-images.githubusercontent.com/48527022/115426044-2752ba00-a1ce-11eb-9a09-ac9ff42f07c4.png) <br><br><br> ![image](https://user-images.githubusercontent.com/48527022/115426188-4bae9680-a1ce-11eb-8e42-0b2f1e399e0b.png) | ![image](https://user-images.githubusercontent.com/48527022/115426127-3afe2080-a1ce-11eb-90a4-ef590e8fdde5.png) | ✔️ **PASS** | Effectively pushed `undefined` for all data layer variables immediately after firing proper tag
