### ISSUE TITLE
General Analytics Request for VANotify

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/va.gov-team#22411]
# Google Account setup help request

## Description
Who is this request for?
- VANotify team (@ffafara-tw)

We want to use gmail postmaster tool (https://gmail.com/postmaster/) to manage reputation of the domains VANotify uses to send email notifications to veterans.
The 2 domains that are currently being used are:
- notifications.va.gov (via AWS Simple Email Service)
- messages.va.gov (via Granicus)

To use the postmaster tool we need a google account under which we will verify and manage these domains.
We would prefer that this google account is somehow owned by VA.

Knowing that Analytics team has experience in setting up google account for Google Analytics tool and has established patterns for access and permissions we were hoping you could offer some guidance how to best set it up.

Perhaps using the same underlying google account for GA and Postmaster would be an option?

**Comment by joanneesteban** [comment]
@ffafara-tw 👋🏻

On Analytics, we need people to have Google Accounts to give them Google Analytics access. We have folks create a Google Account/Gmail and have them [associate those emails](https://support.google.com/accounts/answer/176347?co=GENIE.Platform%3DDesktop&hl=en) to their VA.gov emails. These emails are generally owned by the individual VA person, but you can probably use a Google Group to provision ownership to multiple VA people.

**Comment by jonwehausen** [comment]
Hi @ffafara-tw , 

If you want to associate a .gov email with a google account, you'll want to [use this sign up form. ](https://accounts.google.com/signup/v2/webcreateaccount?flowName=GlifWebSignIn&flowEntry=SignUp). From there, you should be able to utilize that email in registration for postmaster. 

With this information, we will close this issue but please feel free to reopen should you have any further questions.

**Comment by ffafara-tw** [comment]
One last question: 
As far as I understand, in Google Analytics all the data lives in 'admin' google account and access is granted to users' own personal accounts (that can be created with @va.gov emails).

Would this 'admin' google account be suitable to use as owner of the postmaster data?
Or should I create a separate account for Postmaster that is in no way connected to Analytics?

**Comment by joanneesteban** [comment]
Hi @ffafara-tw - thanks for the reminder! Our team discussed, and we wanted to know if you can you clarify what you're looking for with the admin accounts? 

We don't have a single "admin" google account as the Analytics owner, unless we talk about who owns the Google Marketing Platform, in which case that's connected to an organization instead of someone on the team. Everyone who's an admin on our Google suite co-owns the data, but those are tied to our company email accounts.

**Comment by ffafara-tw** [comment]
I was looking at https://support.google.com/analytics/answer/1009618 and https://support.google.com/analytics/answer/1102152
So I guess my question is if there is a VA organization or VA analytics account (separate from google account users) that would also be appropriate for Postmaster tool (if that would at all be possible).

I can always create a new account using our team's VA email (vanotify@va.gov) that will have nothing to do with Google Analytics. Just looking for some guidelines or preferred approaches regarding governance of google accounts / resources used at VA.

**Comment by joanneesteban** [comment]
Hi @ffafara-tw 

> I can always create a new account using our team's VA email (vanotify@va.gov) that will have nothing to do with Google Analytics. 

That's probably most appropriate. We have a shared email/group for Google Analytics ownership so that ownership isn't tied to a single user on our side. But it seems like y'all can create a new account with your team's email so that Postmaster is owned by your team.

**Comment by ffafara-tw** [comment]
Ok. Will do that.
Thank you!
