### ISSUE TITLE
Large button CC: display icon

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22425]
## Acceptance Criteria
1. Update the Large Button common component to take in an optional icon
     - This will be applied to the **Add files** button on the Compose a Message form
2. Update ReadMe 

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364867
.svg: 
![paperclip--$color-link-default.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c2c4185f-a739-4208-bafa-98b48a349dcb)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
4/12/2021 - Not ready to be tested yet, needs the compose message form.  Setting to QA Blocked.

**Comment by digitalken** [comment]
PASS 4/20/2021 - Looks good on Android and iOS.  Closing.
