### ISSUE TITLE
Form wrapper to take in radio buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22424]
## Acceptance Criteria
1. Update the form wrapper component to take in radio buttons
     - This change is required for the **Compose a Message** form
2. Add specs to ReadMe

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364867

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
4/12/2021 - QA blocked at this time until I get a compose message form.

**Comment by digitalken** [comment]
Closing 4/20/2021 - No longer taking radio buttons.
