### ISSUE TITLE
[BE] HCA/ICN issues

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2242]
@Samara-Strauss commented on [Thu Aug 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19496)

Re-creating this ticket with ICNs redacted:

------

Hi team,
Seeing couple of these per day, not sure how it could be happening.
 
Incoming enrollment application, authenticated path, and sent with [ICN redacted]
Traits:
Submitted: [redacted]
 
ICN for this person is [redacted] and has existed for a year already.
 
It fails because incoming FQID not exist in MVI; it does not fall back to a trait search in the LOA3 flow.
 
Question is where could this invalid ICN value be coming from?
 
Thinking possibly it’s a temp if the dslogin or id.me account was just newly created right before she applied, but I’m not familiar with how all that works.

---

@lihanli commented on [Thu Aug 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19496#issuecomment-521850772)

> Looks like it started around October 2018, it was extremely infrequent up until about the last 8 weeks or so.

> I have not seen any case yet where it was an ICN that belonged to another person; just not found.

---

@lihanli commented on [Mon Aug 19 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19496#issuecomment-522804630)

> We are looking into the issue and have found the messaging around the ICN provided and MVI did return a newly created ICN for some reason for an Identity that already existed since 2018 under ICN xxxx.

**Comment by Justin-Pickett** [comment]
Looks like this is possibly a bug on the MVI side. @lihanli advised that we may not need to do anything else on our end if this is fixed by MVI team. 

Closing this ticket out.
