### ISSUE TITLE
Common component: Text entry box

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22426]
## Acceptance Criteria
1. Create common component for the text entry box
2. This component will ultimately be inserted into a form wrapper
3. UI details:
     - Border: 1px solid gray #5B616B
     - Background: white
     - Text: Mobile Body
     - Helper text (optional): Source Sans Pro, 16/22px #323A45
4. When there is a required label:
     - Red secondary dark, #CD2026
     - UI when field is in focus:
     - Border: 2px solid, #003E73
5. UI when there is an error:
     - Border: 2px solid red secondary dark, #CD2026
     - Background: white
     - Label text: Mobile Body Bold
     - Error text: Mobile Body Bold, #CD2026
6. Dimensions of the text box are fixed
6. Add specs to ReadMe

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364867
![Screen Shot 2021-03-30 at 4.49.42 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/273fa928-26f8-4251-b634-e1e3e41c844d)

**Comment by bessgreen** [comment]
@drjecker i took a first pass at the specs and leveraged what we did for the input field CC #19584. the main open question is about the dimensions of the box and whether or not it needs to scale, or if it is a fixed height/width.

**Comment by drjecker** [comment]
Per our convo @bessgreen this can be fixed size.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/14/2021 - Looks good on iOS and Android.  Closing.
