### ISSUE TITLE
Migrate linting from CircleCI/Jenkins to Github Actions

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#22436]
As a VFS team, I want a more stable and fast release process so that I can rely on builds and get my code out quickly. 

As part of the effort to stabilize and speed up the deployment process, we want to move all the parts of the BRD process to github actions. To kick off this effort, we want to start with migrating linting to using Github Actions. 

AC: 
- [x] Get Rubocop to work in Github Actions
- [x] There is a check on each pull request to show this has run successfully
- [x] Rubocop is using the parallel flag
- [ ] Remove Rubocop from Jenkins

**Comment by ericboehs** [comment]
Moving last step to https://github.com/department-of-veterans-affairs/va.gov-team/issues/22870
