### ISSUE TITLE
Implement Github Auth for Sidekiq

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#22437]
As a security engineer on VSP, I want Sidekiq to be behind an authentication so that not just everyone can access it. 

AC: 
- [x] Create oauth application in GH at organization level
- [x] Make sure it works for sidekiq
- [x] Socialize this change to anyone using Sidekiq
- [x] Figure out who we want to have access to Sidekiq
- [ ] Implement audit logging if that's built in (if not we can figure out another solution later)

Transferred from #23196:
- [x] Transfer oauth app to va bot GitHub account
- [x] Define access criteria for Sidekiq (teams' access)
- [x] Add specs for oauth flow (via VCR)
- [ ] Document how to add teams to various tools (e.g. Sidekiq, PgHero)
- [x] Meet with Joe and Fleet for a security review

**Comment by mchelen-gov** [comment]
i think this is supposed to be part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/22354 ?

**Comment by andreahewitt-odd** [comment]
@mchelen-gov Yup! Thanks for catching that!

**Comment by rileyanderson** [comment]
related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/23196.

Need to get with @f1337 who has access to bot users to transfer ownership of the OAUTH applications.

We need to determine which groups/teams we want to have access to Sidekiq and how we want to manage this. Do we create a new team in the organization or do we just go off existing teams? @jeff2d2 is this something you could ask around about and try to track down?

**Comment by jeff2d2** [comment]
[Decision thread for access group set up](https://dsva.slack.com/archives/CQHBJ5U06/p1624638662147400)
