### ISSUE TITLE
Parallelize Nightwatch A11y Sitemap Tests to Speed Up Execution

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#22445]
>Does breaking up the sitemap a11y test in consideration of future or current parallelization make sense? - https://github.com/department-of-veterans-affairs/va.gov-team/issues/22163#issuecomment-807314901

Explore the idea of reconfiguring Nightwatch to leverage parallelization when executing the already 'chunked' sitemap.

**Comment by pjhill** [comment]
PR merged -- it's fast!
