### ISSUE TITLE
Create static tool landing page in unauth benefit hub for Rated Disabilities dashboard view

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va.gov-team#2244]
## Considerations
- Who is responsible for creating pages like this?  Should we do it or Global UX?
- IA feedback has been provided in #2584 that concerns this ticket.
 
## Story   
As a user, I want a clear indication that I need to log in to VA.gov to view rated disabilities if I am not already logged in. 

## Goal
If the eBenefits Team needs to build this, create a logged out view, notifying the user they need to log in to see their rated disabilities. 

## Acceptance Criteria
- [ ] A logged out view is created in adherence to the corresponding mockup slide found [here](https://xd.adobe.com/view/ebfa6df6-c0aa-4ea9-413e-98793ba7a5a3-9dcb/)
- [ ] If a user signs in this way at /disability/my-rated-disability, then they should not be redirected away from that URL, they should see their information load on the same page. 
- [ ] URL for this page should be Static page URL: www.va.gov/disability/check-disability-rating/
- [ ] Disability hub page has been updated with a link to this page.
- [ ] The 'manage' spoke in the left nav menu has been updated with a link to this page.

## Research
- Something like this can already be viewed at va.gov/claims-or-appeal-status/
- Globally available widget is available to use here: https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/platform/site-wide/cta-widget
- The above widget automatically toggles the sign in modal we've been using already, found here: https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/platform/user/authentication/components

![Screen Shot 2019-10-03 at 1.15.10 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/edf15b5b-fa39-4d71-844e-91f44f93dfda)

<img width="159" alt="Screen Shot 2019-10-03 at 1 35 24 PM" src="https://user-images.githubusercontent.com/15097156/66162180-b4c9bb80-e5e2-11e9-85c6-e74ba3733dcd.png">

**Comment by micahchiang** [comment]
This issue is tabled pending further discussion with global-ux and authenticated-experience.

**Comment by Karak888** [comment]
need access for feature landing page or area where people can click into this feature.  @mnorthuis @jenniferlee-dsva  meet to assess where and how this feature can be accessed from unauthenticated site.

**Comment by mnorthuis** [comment]
Provide feedback on this in the overall IA review here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/2584

**Comment by Karak888** [comment]
@mnorthuis is it ok to close this ticket since seems mostly everything is included under #2584 and I will be creating a ticket to link to disability calculator page once page is live?  Thanks!

**Comment by mnorthuis** [comment]
@Karak888 who is creating the static page?  Is that work documented in a ticket somewhere?

**Comment by Karak888** [comment]
@Karak888 to sync with @mnorthuis @peggygannon and will need FE engineering and create status page in Drupal.  Is there a file or word doc where we can grab content?  what is the timeframe for this?

**Comment by Karak888** [comment]
@micahchiang is there a word doc where we can grab the images from?  Thanks

**Comment by micahchiang** [comment]
@Karak888 - Here's a link to the mockups: https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/

As far as images go, I'm looping @sporeboy in. He's our designer so he may know better than I where to get those types of resources.

**Comment by Karak888** [comment]
once @jenniferlee-dsva will talk to Steve Kovacs and likely create a ticket for work specific to public websites team.  Needs a lot of content and some FE engineering.

**Comment by Karak888** [comment]
actionable ticket to be written from call on 11/13/19.  @Karak888

**Comment by jenniferlee-dsva** [comment]
@Karak888 I've created a clean epic here for the public website team: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3451

We can close this ticket and use the ^ going forward for our team.

**Comment by Karak888** [comment]
Moving to close this ticket as @jenniferlee-dsva has created a new epic for tracking here:  https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3451
