### ISSUE TITLE
Use a JS Set instead of an array in the replacePathInData() function

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#22448]
## Details 

Recommended in #20764 

"Use a JS Set instead of an array in the replacePathInData() function. This will already save about 40 seconds with the current build. As the node count increases, this change will become more important, and eventually critical. It makes sense to tackle this first due to the immediate benefit to build time."

Make the change and test for regressions and issues.

## Acceptance Criteria 
- [x] JS Set is used instead of an array in the replacePathInData() function
- [x] Testing has been completed to ensure this has not introduced any issues 
   - [x] Compare new build output to old (consider using content build comparison script)

**Comment by alexandec** [comment]
Did final testing, then merged [the PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16628). Will monitor for any issues (this will be deployed Monday).

**Comment by alexandec** [comment]
Looks good in prod, closing this.
