### ISSUE TITLE
Parallelize Cypress tests (without using Cypress Dashboard)

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#22446]
# Description
Timebox the effort to parallelize tests without using Cypress Dashboard to 2 sprints. We should be wrapping up this effort by the end of sprint 50 (4/27/2021).

>Is there some simple way of parallelizing the Cypress E2E test execution that doesn't rely on an additional tool such as Cypress Dashboard? - https://github.com/department-of-veterans-affairs/va.gov-team/issues/22163#issuecomment-807314901

**Comment by billfienberg** [comment]
Here's how Nightwatch's `test_workers` parallelization seems to work:
1. [`getTestWorkersCount`](https://github.com/nightwatchjs/nightwatch/blob/f0388b336145b598c4931f67573de2dbac1ffdd4/lib/runner/concurrency/concurrency.js#L180-L189)
1. [`runMultipleTestWorkers`](https://github.com/nightwatchjs/nightwatch/blob/f0388b336145b598c4931f67573de2dbac1ffdd4/lib/runner/concurrency/concurrency.js#L86-L109)

See also:
- [`currency.js`](https://github.com/nightwatchjs/nightwatch/blob/main/lib/runner/concurrency/concurrency.js)
- [child-process.js](https://github.com/nightwatchjs/nightwatch/blob/main/lib/runner/concurrency/child-process.js)

**Comment by billfienberg** [comment]
https://github.com/sorry-cypress/sorry-cypress

**Comment by billfienberg** [comment]
https://github.com/Shelex/cypress-parallel-specs-locally

**Comment by billfienberg** [comment]
https://github.com/tnicola/cypress-parallel

**Comment by ddzz** [comment]
Cypress tests have been parallelized by distributing tests among six Docker containers on Jenkins. This approach does not use the Cypress Dashboard or any new dependencies. Test execution time has been reduced to an average of 9-10 minutes total.

Two PRs were merged:
- https://github.com/department-of-veterans-affairs/vets-website/pull/16916
- https://github.com/department-of-veterans-affairs/vets-website/pull/17108

**Comment by pjhill** [comment]
This has been completed and functioning well for several weeks now. Hooray!
