### ISSUE TITLE
Create an Experimental Design section on design.va.gov 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#22456]
## Issue Description
Create an Experimental Design section on design.va.gov 
Include the usual subsections on the page. 

---
## Tasks
- [ ]Create an Experimental Design section on design.va.gov 

## Acceptance Criteria
- [ ] Experimental section is on design.va.gov

**Comment by k80bowman** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/427
