### ISSUE TITLE
Move debug stringification to template

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#22450]
## Details 

Recommended in #20764 

Currently before piping data into metalsmith we take each page object, stringify it, and add the string to the corresponding file object. Then later in the Apply Layouts step we include the string in a liquid template to help with debugging. However, all those strings use a large amount of extra memory and slow down the build process. To save memory and time we can instead perform the stringification in the liquid template itself. This improvement will be noticeable even in our current build (roughly half the peak memory use and 40 seconds of build time saved). These benefits will become much greater as we scale.

## Acceptance Criteria 
- [x] Stringification of debugging data is moved from page object to template 
- [x] Testing has been completed to ensure this has not introduced any issues 
   - [x] Compare new build output to old (consider using content build comparison script) - may not work for debug info, may need to do manual comparison

**Comment by alexandec** [comment]
Currently testing, PR is here: https://github.com/department-of-veterans-affairs/vets-website/pull/16668. Looks good so far.

**Comment by alexandec** [comment]
Merged to master, everything still looks good. I'm seeing the reduced memory use and build time I expected. Closing this ticket.
