### ISSUE TITLE
Hide Drafts & Deleted folders

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22463]
## Acceptance Criteria
1. On the Folders list page, hide the following ListItems from the UI, as they are out-of-scope for app store launch:
     - Drafts
     - Deleted

Note: we will add these back in at a later date. For app store launch, we’re not offering the ability to edit drafts or delete messages, which is why we are hiding these folders in the interim.

## Reference
![IMG_0140.jpeg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/02df0630-f313-4304-80a4-d2f1f756d3d7)

**Comment by bessgreen** [comment]
Blocked: awaiting content from VA

**Comment by bessgreen** [comment]
Per feedback from Jen: prioritizing this ticket ahead of AH's SM demo on 4/15.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/14/2021 - Looks good on iOS and Android. Closing.
