### ISSUE TITLE
Use semver in vets-website to reference vets-json-schema

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#22462]
**Description**
vets-website currently references [vets-json-schema](https://github.com/department-of-veterans-affairs/vets-json-schema) versions with a [commit hash](https://github.com/department-of-veterans-affairs/vets-website/blob/master/package.json#L366). This may cause confusion when multiple teams are updating the reference. If multiple developers have `vets-website` PRs open with different references to `vets-json-schema`, there is a chance that someone can merge code that brings `vets-json-schema` to an older version than the `vets-website` `master` branch is referencing.

Using version number as a reference will lessen the chance of front-end developers reverting back to an older `vets-json-schema`. We should use semver in package.json so a simple `npm update vets-json-schema` will always increment the version and developers can see if it's being incremented vs decremented, right there in package.json.

Example of such situation: https://dsva.slack.com/archives/CBU0KDSB1/p1617214467071800?thread_ts=1617206272.037100&cid=CBU0KDSB1

**Comment by mchelen-gov** [comment]
Note: package.json is referencing the `vets-json-schema` Git repo directly, rather than as an NPM package. Recent version of NPM/Yarn look like the still support semvar references for this case: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#git-urls-as-dependencies

**Comment by mchelen-gov** [comment]
based on slack convo with @bkjohnson any versioning format would be fine as long as vets-website and vets-api both point to the __same version__

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new bug.
