### ISSUE TITLE
[SPIKE] Profile preferred facility BE changes

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22473]
## Summary
In #16107, a facility preference could be stored for a Veteran so VAOS can use that information in the app.

## Tasks

- [ ] Review API changes

- [ ] Document if changes are needed and create VAOS BE tickets if necessary (for FE use of Veteran preferences)

**Comment by ajmagdub** [comment]
Reviewed the work done on #16107 and it looks ready for use by the FE to pull preferred facilities without any further modifications.

The work done provides the ability to retrieve a list of preferred facilities for the current user, GET; create a single facility for the current user, POST; and delete a single facility for the current user, DELETE. Following are the associated endpoints from Vets API Rails routes:
<pre>
v0_preferred_facilities GET     /v0/preferred_facilities(.:format)       v0/preferred_facilities#index {:format=>"json"}
                        POST    /v0/preferred_facilities(.:format)       v0/preferred_facilities#create {:format=>"json"} 
  v0_preferred_facility DELETE  /v0/preferred_facilities/:id(.:format)   v0/preferred_facilities#destroy {:format=>"json"}
</pre>

Below are the relevant sections of the Vets API swagger docs:
<pre>
paths:
  /v0/preferred_facilities:
    get:
      responses:
        '200':
          description: user's preferred facilities
          schema:
            properties:
              data:
                type: array
                items:
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    attributes:
                      type: object
                      properties:
                        facility_code:
                          type: string
        '401':
          description: Not authorized
          schema:
            $ref: '#/definitions/Errors'
      description: Get list of user's preferred facilities
      operationId: getPreferredFacilities
    post:
      responses:
        '200':
          description: the created preferred facility
          schema:
            properties:
              data:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  attributes:
                    type: object
                    properties:
                      facility_code:
                        type: string
        '401':
          description: Not authorized
          schema:
            $ref: '#/definitions/Errors'
      description: Create a preferred facility for a user
      operationId: createPreferredFacility
      parameters:
        - name: preferred_facility
          in: body
          description: Preferred Facility data
          required: true
          schema:
            type: object
            required:
              - preferred_facility
            properties:
              preferred_facility:
                type: object
                required:
                  - facility_code
                properties:
                  facility_code:
                    type: string
  '/v0/preferred_facilities/{id}':
    delete:
      parameters:
        - name: id
          in: path
          description: Id of Preferred Facility to delete
          required: true
          type: string
      responses:
        '200':
          description: the destroyed preferred facility
          schema:
            properties:
              data:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  attributes:
                    type: object
                    properties:
                      facility_code:
                        type: string
        '401':
          description: Not authorized
          schema:
            $ref: '#/definitions/Errors'
      description: Destroy a user's preferred facility
      operationId: deletePreferredFacility
definitions:
    Errors:
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/definitions/Error'
    Error:
      required:
        - title
        - detail
        - code
        - status
      properties:
        title:
          type: string
          example: Bad Request
          description: error class name
        detail:
          type: string
          example: Received a bad request response from the upstream server
          description: 'possibly some additional info, or just the class name again'
        code:
          type: string
          example: EVSS400
          description: |-
            Sometimes just the http code again, sometimes something like "EVSS400", where" \
                                    " the code can be found in config/locales/exceptions.en.yml
        source:
          type:
            string
          example: 'EVSS::DisabilityCompensationForm::Service'
          description: error source class
        status:
          type: string
          example: '400'
          description: http status code
        meta:
          type: object
          description: 'additional info, like a backtrace'           
</pre>

**Comment by laurenernest** [comment]
Great! Thank you for validating!
