### ISSUE TITLE
Design base architecture for Forms KPIs

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#22479]
## Issue Description
How might we design the base architecture for Forms KPIs so that we (and in the future, others) can automate those KPIs into a BI Tool?

This is the first iteration, and we anticipate creating additional data objects to support the standardization efforts for Content and Search data.

---
## Tasks
- [ ] Design base architecture for forms data in BigQuery

## Acceptance Criteria
- [ ] Platform Analytics has centralized Forms KPI datasets so that we can more quickly create charts and calculations for those KPIs

**Comment by JasonTheBearded** [comment]
Base architecture design complete and implemented
