### ISSUE TITLE
Access for Jacqueline Gu

### ISSUE THREAD

**Issue by gujacq** [department-of-veterans-affairs/va.gov-team#22477]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Jacqueline Gu
- Please Provide your email.
   > jacqueline.gu@civicactions.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS-CMS team, UX designer, CivicActions.

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyY99mKeOEJlsa8LVt2aVRt/Di3gqs5nmqEk9OZink9d8ndA/kBMsGtKV3T2DxcTwiic0aT0GNVFUyOXC95OtoC5HyZdkn3yxpIRJX8LD6thSusmOozVbI1Ig4m78gQN+lY+g3TAAsmjQvoNiQ2Fgn3aMNz3bADvb8EjM528CJSwSwisBSL8cHZGD4kCcaDY+dASTghXFdYRgxQGB3/Fg0AHCQa/PieVJV/Im0X7XQgvwDrcM3Lphd7crtbE4ovFBgg6TGcLeffay7JH6BnXluYtSoiupXSz8Chenp2y1ZRiyjVDHlsilTjpdE3h8RVw628+5xxejZmp/tOFjkBaDyj2Pd+zGP/hKzmAP7dV7vkRItHKCYSnH3ezoTUmcy/QUkaIu9DXdu+nh8gnRebkWsCJSwd+T8Bmcf2BVZqV82swdx/OjAz+PLkE4IvrEEYgYnXZdGVcXLjMPCR8PamJebxZgfDYQG8uNMJqRVQX+CLFR7SaIaaiwEif9j78XDU7U= gujacq@Jacquelines-MBP.local

```

- Grant AWS Console access?
  > NO

**Comment by gujacq** [comment]
@jbritt1 Could I get my public key added for Socks access? Thank you!

**Comment by jbritt1** [comment]
> @jbritt1 Could I get my public key added for Socks access? Thank you!

On PTO until Tuesday. You can drop a note in the vfs-platform-support channel for a more expedited turnaround.

**Comment by mleclerc00** [comment]
SOCKS access granted. Please continue with the guide to establish a connection to SOCKS proxy.

**Comment by mleclerc00** [comment]
@gujacq 

Just looking to confirm that this is all set so I can close this ticket.

**Comment by cmaeng** [comment]
thanks @mleclerc00 . @gujacq is OOO through the end of this week but I believe she's good to go. we can always open a new ticket if there's anything lingering when she gets back.
