### ISSUE TITLE
Create mocks for appointment details page variants

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2247]
## Context
Many of these mocks probably already exist somewhere, but we need to confirm that they're up to date and we need to put them in one place so that developers can ensure they've accounted for all the variants.

## Story
As a developer, I want to understand what each appointment or request should show to veterans after it's been clicked on from within the list of appointment / requests, so that I can build the right thing to show to veterans.

## Variants
- Direct Scheduled appointments & confirmed VA appointment requests
    - Video
    - Office
- Confirmed Community Care appointment requests
- VA appointment requests
- Community Care appointment requests

## Available confirmed appointment data:
Facility appointment data:
- Facility id (just id, no name or anything)
- Clinic name
- Appointment time/length
- Booking note

Video appointment data:
- Facility name, id
- Video link
- Appointment time
- Provider name/contact info
- Various codes and statuses

CC appointment data:
- Provider name, phone, and address
- Veteran instructions
- Appointment time

Notably, we don't appear to have type of care for any of these cases.

## Available VA request data
- Care type
- Preferred appointment date(s) & am / pm
- Preferred facility
- Purpose of visit (e.g., new issue, routine follow-up)
- Visit type (e.g., office visit)
- Contact number & time of day preferences

## Available CC request data
- Not sure, presumably everything is the same across the two + this would perhaps return CC preferences, but we need to check with a dev first.

## AC
- [ ] Mocks for each variant are attached to this ticket

**Comment by markgreenburg** [comment]
@jbalboni curious if phone appointments need to be specifically differentiated just like office & video?

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/67396455-a03f6a00-f575-11e9-88a3-e7c028741e6d.png)

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/67397646-8010aa80-f577-11e9-8c01-846cb4e476f2.png)

**Comment by rtwell** [comment]
I left out the most important comment: **there are no more detail views of appointments.**

1) Confirmed appointments surface all details and actions on their respective cards.

2) Pending appointments have a show more / show less interaction to reveal details

**Comment by markgreenburg** [comment]
Dupe of #2306 and also no longer needed because we don't have 'appointment detail' views anymore.
