### ISSUE TITLE
Access for Oseas Moran

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#22487]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Oseas Moran
- Please Provide your email.
   > oseas.moran@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Front End Tools, Software Engineer, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/pJ9b5nLI9RcAoYujOEPft7AcK4V6rbjd90ACmYNX03wdupcSn273sqyXEcPkJd1STuFWrwaCtPoRbcqLHqgvaINJdm94m45zPSrJ525knwyXZQAEWjsdljv+ZEEkJcLmbQymTJC63lIxRqAioopjYmWNpBQAxWzQ8Mdr/Wc1oNOm+TcvVDYS6UAYVp1dzERh+9J/rCfb+yIqcXrSDkY8uF57J5JG3tDFje7EQ1xr83ddhJwZ/8lZ6xsKCKcUDWi1aR7gx0/lCCuuIjQcbyuQHujBUVt5y4cDDq0z4aGv11WWmEC8kvCxHDyu3sZxldcPzBT7kH23dJuUd/dziUYsQE2aenOEayDZmH0SfLwoz1mf//UAIe9RIELKgRYV1AlFgRIFlFLAZ/x8Xz2NQjS6+6U4/OQJpoO2DoX8KgCFXKDkdeKsUUDNwSAzHAhXyTAIoERvJfZmBK/LzUjXmJ03tuLQw0EJ9h6aI+GmDVE+QdVoJWjrF63rM0KwL3DSqvE= oseasmoran@Oseas-Moran-MacBook.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by mleclerc00** [comment]
@oseasmoran73 

Can you confirm that socks access is working for you so I can close this ticket.

**Comment by oseasmoran73** [comment]
Hi @mleclerc00 ,

Hope all is well. Yes, I have socks access and working as intended. You may close this ticket. Thank you!
