### ISSUE TITLE
[Discovery] Identify opportunities for unit testing

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#225]
## Description
We want to identify opportunities for improvement to increase our *detection* / *prevention* with unit tests.

## AC
- [ ] Research has been conducted to identify opportunities for automated testing improvements
- [ ] A research readout has been written and shared with the tools and improvement teams
- [ ] New tickets have been written to break out the work to be done

## Notes
- Sister ticket to #178

**Comment by jholton** [comment]
Questions for discussion:
Is this a problem for `vets-api`?
By `unit tests` do we mean `model` tests?  What about classes in `lib`?
How do we measure acceptable unit test coverage? Simplecov? Do we require 100% coverage of classes? Do we require coverage of private methods or just public methods?

**Comment by rianfowler** [comment]
This is what we did for vets-website:  [improve unit test coverage of vets-website](https://github.com/department-of-veterans-affairs/va.gov-team/issues/183)

**Comment by rtluu** [comment]
Let's start by documenting our current BE automated tests and the current expectations we have around test coverage around their apps.

**Comment by rtluu** [comment]
@hpjaj is there any overlap with the #128 here? Do you have any written guidelines around ☝️

**Comment by annaswims** [comment]
@jholton I think we mean all code in app and lib should have a minimum of 90% test coverage. 

Ideas I have so far: 
* Review https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/PULL_REQUEST_TEMPLATE.md to add testing specifics
* verify that `SimpleCov.refuse_coverage_drop` works on Jenkins (kinda doubt it)
* running `rsepc` runs fewer tests than `rake spec` see if we can make them run the same tests
* There are a significant number of filters/exclusions to test coverage. Verify that they are all still necessary
* Consider Codeclimate as a way to increase visibility to code coverage.
