### ISSUE TITLE
Meet with CARMA team to develop path forward on timeout issues

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#22504]
Given that timeout errors cause user ambiguity, and resubmission leads to burdensome duplicates,
We want to work with the CARMA team to prevent timeout errors from occurring at all.

**Comment by ala-yna** [comment]
Scheduled for Weds, April 7

**Comment by kevinmirc** [comment]
Met with Paul and Ramesh today.

**Summary**
- Data contract changes for `lastTreatmentFacility.name` `lastTreatmentFacility.type`
  - Paul will create and size a ticket to handle a flat structure for these attributes as `lastTreatmentFacilityName` and `lastTreatmentFacilitytype`.
  - Level of effort is low
  - This will not be queued for implementation until the next cycle.

- Sending additional data for veteran representation
  - Va.gov team provided context on what changes are happening on the form, and what new data will be capture:
    - A POA attachment will be sent to CARMA when it's provided by the user
    - We only ask the user if they want to upload representation documentation, we don't ask if they are a POA
      - See upload mockups here: [final poa copy.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6273585/final.poa.copy.pdf)
      - This may not be enough information to create a flag in CARMA that the veteran has representation
    - We will capture the signature typed on the final page of the form
      - These will not be sent to CARMA unless requested
      - These may be used to help create a flag, depending on requirements by the Business.
    - Signature on PDF will match what the user provided online
      - When the user uploads representative documentation, the "veteran's signature" is an open text where the representative can sign their name. This signature will be populated on the PDF.
  - CARMA team will discuss the requirement around a "may have representative" flag, with the Business, and let us know what information we could send to help set that flag.
    - There may be no additional info needed from VA.gov to create the flag, but that depends on the requirements.

**Comment by kevinmirc** [comment]
Paul: "the business decided to push the two development stories for consideration in the next PI (post-July)."
