### ISSUE TITLE
Landscape mode - iPhone ear speaker cutout interferes with content on screen

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#22517]
## What happened?
Using an iPhone in landscape mode, I found that some screens had data that went way to the end of the screen and the ear speaker cutout tended to cover up content on the screen that made it difficult to read or understand.  I was able to rotate the screen 180 degrees to reveal what was covered by the cutout, but the experience was kind of a pain.

## Specs:
- Device: iPhone XR

## Steps to Reproduce
- View the app in landscape mode.

## Desired behavior
User is able to view all content on the screen, whether in portrait or landscape mode.

## Acceptance Criteria
- User is able to view all content on the screen, whether in portrait or landscape mode.

## Bug Severity
- 4 - Low

## Linked story
n/a

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/86b81362-5cdc-4d8e-9006-eb3f08ac5cc5)

**Comment by lexicalninja** [comment]
More than likely can be fixed by update the `VAScrollView` with the following:

```tsx
const VAScrollView: FC<ScrollViewProps> = (props) => {
  const insets = useSafeAreaInsets()
  const style = {
    paddingRight: insets.right,
    paddingLeft: insets.left,
  }
  return (
    /**
     * force scroll position by default to avoid visual bug where scrollbar appears in the center of a screen
     * scrollIndicatorInsets is an iOS only prop, this bug only appears on iOS
     */
    <ScrollView scrollIndicatorInsets={{ right: 1 }} {...props} style={style} />
  )
}
```

**Comment by digitalken** [comment]
PASS 4/22/2021 - Looks good on iPhone!  Closing.
