### ISSUE TITLE
Create mocks for appointment / appointment request submission failure

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2251]
## Story
As a veteran, I want to see a helpful error message when my appointment or appointment request doesn't go through so that I'm not confused and know what to do next.

## Context
Discuss possible error types with devs to understand if more than one UI variant needs to be created

## AC
- [ ] Mock for direct scheduling and / or request error exists in this ticket
- [ ] Documented, in ticket, whether one UI is sufficient or if multiple are needed

**Comment by markgreenburg** [comment]
@rtwell do you remember if we already have mocks for when a submission fails? Might already be implemented but I'd like to check.

**Comment by rtwell** [comment]
i thought we did, lemme check…

**Comment by rtwell** [comment]
yeah i can't find anything

quesitons i have about this:

1) would/should this error appear on the same page as the submission? or would a new page appear with only an error/next steps?

2) speaking of next steps, what are our options? i'm assuming 
a) start over — although where in the flow?
b) call
c) try again
d) ??

**Comment by lenaecb** [comment]
Closing this ticket as it's getting addressed in #6288
