### ISSUE TITLE
Establish Location and Style of Doc Type Selection

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22510]
## Background
Now that we know what doc types are applicable, we need to establish what the component will look like and where it should go, presumably above or below the file upload tool.

## Tasks
- [x] Create a description in either the mock up or in plain text what this  implementation should consist of

## Acceptance Criteria
- [x] Share with PM and FE

**Comment by sporeboy** [comment]
Style, position and content created for doc selection dropdown. Mockup available here: 

https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/f3a518de-ab91-4103-bddb-e7004a7425c3/
