### ISSUE TITLE
Update DIC Page URLs and Redirect to new Locations in Disability Hub 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2252]
### **User Story**
As a surviving spouse, dependent or parent, I need to easily find DIC benefit info, so I can apply and access the benefit I'm eligible for.

### **Goal**
Move DIC into Disability where users expect to find it and ensure there is crosslinking in Survivors Pension, Burials and Family hubs.

### **Acceptance Criteria**
- [ ] DIC page and all DIC rates pages are moved to Disability hub with new URLs
- [ ]  All existing links to DIC and DIC rates pages are updated to reflect new URLs
- [ ]  DIC rates pages are removed from Burials hub page and Burials left nav
- [ ]  Old DIC page URLs are redirected to their new locations
- [ ]  Links to the DIC rates pages are added to the Disability hub page
- [ ]  Links to DIC and DIC rates pages are added to Disability left nav
- [ ]  Content and link to DIC is added to Survivors Pension page
- [ ]  Content and link to Survivors Pension is added to DIC page
- [X]  All master IA documentation is updated

**Comment by ncksllvn** [comment]
Hey @Karak888, I don't think this is actionable yet as a dev task for @kelsonic to grab. A couple things -

1. We don't know anything about these DIC pages, but even if we knew where they lived today(like  `somewhere.va.gov/dic`) we still need to know where their new locations should be on www.va.gov. This is an IA task.
1. Even after determining their new location, shouldn't this be done in Drupal?

**Comment by kelsonic** [comment]
@Karak888 Going to unassign myself from this for now until we have groomed out dev tasks as @ncksllvn mentioned above :)

**Comment by ncksllvn** [comment]
Yeah, @Karak888 I think @kelsonic and I need a lot more insight into this - maybe a kickoff meeting where we can map this into more-actionable tickets?

**Comment by Karak888** [comment]
@RLHecht / @AnneHurley  can one of you please find out where the above referenced DIC pages are supposed to live (i.e., do you know where they live today, and where they will eventually reside in Drupal)? Thanks!

**Comment by Karak888** [comment]
closing this out and will create a new ticket when we are ready to do redirect work.
