### ISSUE TITLE
IA feedback - Design intent - Preferred facilities

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#22520]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- ~Do all users see this option, or just users enrolled in health care?  If all users, is the "no facilities" message clear enough for users who don't have VA health care?~
- ~How do user's add facilities to the list?~
- ~If they remove a facility as a "preferred" option, does it still appear in this list as a previously visited facility but not a favorite, or is it removed for good?~
- Where does the "Your local VA health care facility" link go to in the error message?  Link label gives impression that it would take them to their specific facility. 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- User flow/entry points:  Determine what will prompt/guide users to this feature? Will they primarily come here from a prompt within VAOS? Or, should this be a more global feature (like direct deposit), where there may find links/info other places within the site? Is an SEO rich static landing page needed?
- Navigation components: Recent IA and accessibility discussions recommended changes to the breadcrumb, which should be accurately reflected within this prototype.  Here is the issue for background info: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19552
- Nomenclature/labeling:  Recommend labeling this "group" of facilities to be more specific in its purpose or use.  "Your facilities" may be too non-descript - is it facilities I previously received care at, facilities I can receive care at (registered), or facilities that I prefer to receive care at?  Since this data set will be used within VAOS and potentially elsewhere, they should be referenced consistently and descriptively.  

**Should:**
- Navigation components: What is the order of nav options within the left nav based on? Recommend reviewing analytics to determine priority/high traffic items, review for potential groupings, and gather user input.
- Nomenclature/labeling:  Labeling is also important for the profile left nav - all options in the left nav could be proceeded with "Your", but that would become very repetitive.

**Consider:**
- Consider what potential future uses these "preferred" facilities could have - i.e. could they link to the facility/location detail page, or could they be displayed within the facility locator as a default, etc

## VSP directions
- [x] Update "Issue Title"
- [x] Link to collab cycle touchpoint meeting epic
- [x] Add to the Feedback pipeline on the VSP Product Support board
- [x] Add your feedback
- [x] Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by mnorthuis** [comment]
Answers to questions from design intent meeting. Please let me know if any of this is incorrect. 

- Do all users see this option, or just users enrolled in health care?  If all users, is the "no facilities" message clear enough for users who don't have VA health care?
  - Answer: non-health care veterans do not see
- How do user's add facilities to the list?
  - Answer: can't do it online at this time
- If they remove a facility as a "preferred" option, does it still appear in this list as a previously visited facility but not a favorite, or is it removed for good?
  - Answer: Facilities are still in that list and available to re-check when they edit.  
- Where does the "Your local VA health care facility" link go to in the error message?  Link label gives impression that it would take them to their specific facility. 
- Should these "preferred" or "registered" facilities eventually link to the facility/location detail page? Should they be displayed within the facility locator as a default?

**Comment by andaleliz** [comment]
Thanks @mnorthuis! Here are my comments:

>User flow/entry points: Determine what will prompt/guide users to this feature? Will they primarily come here from a prompt within VAOS?  Or, should this be a more global feature (like direct deposit), where there may find links/info other places within the site? Is an SEO rich static landing page needed?

For our MVP, the primary entry point will be VAOS.  People with healthcare will see this nav point in their profile, but we expect interactions based on "I came to my profile to update something else and noticed this facilities section" to be secondary.  There's potential for this to be used more globally, but at this point our roadmap and business goals are focused on VAOS.

>Nomenclature/labeling: Recommend labeling this "group" of facilities to be more specific in its purpose or use. "Your facilities" may be too non-descript - is it facilities I previously received care at, facilities I can receive care at (registered), or facilities that I prefer to receive care at? Since this data set will be used within VAOS and potentially elsewhere, they should be referenced consistently and descriptively.

After meeting w/ Danielle, I updated the label to `Your VA health facilities` - want to confirm you saw this most current version and still feel that's too non-descript? We landed on "your VA health facilities" based on what we currently know about how Veterans think about these places.  I'm very interested to see how Veterans talk about this in our research study and was hoping to get some data there that can help with better labeling.  If it is a must to resolve that in this design intent phase, I can work on that.

>Navigation components: Recent IA and accessibility discussions recommended changes to the breadcrumb, which should be accurately reflected within this prototype. Here is the issue for background info: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19552

Updated in the mock-ups, thanks for catching this!

>Nomenclature/labeling: Labeling is also important for the profile left nav - all options in the left nav could be proceeded with "Your", but that would become very repetitive.

Yes, I agree, that would be repetitive. We'll make sure the nav labeling is consistent with the h1 for this section

>Navigation components: What is the order of nav options within the left nav based on? Recommend reviewing analytics to determine priority/high traffic items, review for potential groupings, and gather user input.

This was based on my best guess - Samara requested an update to move it above account security so profile moves from things we know about you to general account information. This is now reflected in the mock-ups.

> Consider what potential future uses these "preferred" facilities could have - i.e. could they link to the facility/location detail page, or could they be displayed within the facility locator as a default, etc

We have thought about the facility locator tie-in, and asked about scheduling things beyond health appointments w/ VAOS (e.g. career counseling.  this is not on their roadmap yet). I'm hoping we can learn more about other opportunities in research when we talk to Veterans.

**Comment by andaleliz** [comment]
>Where does the "Your local VA health care facility" link go to in the error message? Link label gives impression that it would take them to their specific facility.

I've updated this in the mockups so it's more clear that it goes to the facility locator; still out for review w/ content.

**Comment by andaleliz** [comment]
@ajakabcin Just FYI I'm waiting for a response on this question before closing this out. Hopeful we can still close it in this sprint.

**MUST feedback:**
> Nomenclature/labeling: Recommend labeling this "group" of facilities to be more specific in its purpose or use. "Your facilities" may be too non-descript - is it facilities I previously received care at, facilities I can receive care at (registered), or facilities that I prefer to receive care at? Since this data set will be used within VAOS and potentially elsewhere, they should be referenced consistently and descriptively.

**My question:**
After meeting w/ Danielle, I updated the label to Your VA health facilities - want to confirm you saw this most current version and still feel that's too non-descript? We landed on "your VA health facilities" based on what we currently know about how Veterans think about these places. I'm very interested to see how Veterans talk about this in our research study and was hoping to get some data there that can help with better labeling. If it is a must to resolve that in this design intent phase, I can work on that.

**Comment by mnorthuis** [comment]
@andaleliz thank you for all your responses!  I'm going to try and connect with Danielle on this last one today if possible. I can see this labeling as it pertains to VAOS, but am just concerned about how its understood outside of the VAOS context.

**Comment by andaleliz** [comment]
Hi @mnorthuis That sounds good! One more question I want to get your input on since it relates to a users flow: I'm considering linking the `schedule an appointment online` copy to the appointment scheduling page to make it easy for folks to go back to where they most likely came from, or complete that task if they need to do that from their profile.  Thoughts?

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/6f09bfbd-3eaa-4dac-8f4a-5764203fe687)

I also pinged Danielle and Peggy on this in the relevant content tickets since they previously reviewed this copy and it's a new change.

**Comment by mnorthuis** [comment]
Yes, totally agree with providing a link to scheduling from this page - otherwise the flow from VAOS to here ends in a dead end.  Good catch!

**Comment by andaleliz** [comment]
@mnorthuis following up to see if you had a chance to connect with Danielle on the outstanding question:

**MUST feedback:**

> Nomenclature/labeling: Recommend labeling this "group" of facilities to be more specific in its purpose or use. "Your facilities" may be too non-descript - is it facilities I previously received care at, facilities I can receive care at (registered), or facilities that I prefer to receive care at? Since this data set will be used within VAOS and potentially elsewhere, they should be referenced consistently and descriptively.

**My question:**
After meeting w/ Danielle, I updated the label to Your VA health facilities - want to confirm you saw this most current version and still feel that's too non-descript? We landed on "your VA health facilities" based on what we currently know about how Veterans think about these places. I'm very interested to see how Veterans talk about this in our research study and was hoping to get some data there that can help with better labeling. If it is a must to resolve that in this design intent phase, I can work on that.

**Comment by mnorthuis** [comment]
Yes, Danielle and I did talk and I am aware of this approach.  Thank you for following up!

**Comment by andaleliz** [comment]
Thanks @mnorthuis ! I should've been more clear in my question. Glad to know you are aware! Do you still want to see a change to this as an AC of closing this issue? Or can we move forward with "your VA health facilities" and learn more in testing?

**Comment by mnorthuis** [comment]
lol, I should've been more clear in my response!   Yes I am aware, and yes I am good with "your VA health facilities".   Thank you!

**Comment by andaleliz** [comment]
Woot woot! Closing this out :)
