### ISSUE TITLE
Unauth Landing page from Healthcare Questionnaire team

### ISSUE THREAD

**Issue by abuckley3385** [department-of-veterans-affairs/va.gov-team#22530]
### Content support for:
- Unauthenticated (static) VA.gov pages

## How to submit your request

- [X] Determine if this request is for:  
     - [X] Both (Content + PW Eng Spt)   
- [X] Post a link to this issue in the appropriate channel: For Engineering only requests: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @ncksllvn and @kelsonic.  In situations where both are needed post to Public Websites and in Slack tag @brianalloyd, @ncksllvn, @kelsonic and @RLHecht for awareness.  

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   *Our goal is to improve the in-person and online pre- and post-appointment experiences for Veterans, contribute to physical distancing efforts in VA facilities, and better integrate Veteran-provided data in VA workflows by providing Veterans with a digital option to complete pre- or post-appointment questionnaires and screeners.
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
   * [wireframes](https://sketch.cloud/s/fd688be2-76eb-484b-a306-9c1b522f4f09)
  * [IA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-questionaires.md)

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [X] **New unauthenticated VA.gov page** 
   * We are still having content and privacy make a few minor edits waiting to hear back.
   * < https://staging.va.gov/health-care/health-questionnaires/questionnaires >
   * **Schedule a meeting.** Please schedule a meeting with @RLHecht and @brianalloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page.  

   * **Scope: How many screens or messages?** 
     - < 1 screen ?>            

### Frontend engineering support 

- [X] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     -  Yes
   * **Link to VSP IA redirect request ticket:** 
     - < not created yet >
      

### Desired/target implementation date

* End of April

---

### About your team

- Team name: *Amanda Buckley*
- DEPO product owner: *Ming Ligh
- Product manager: *Amanda Buckley*
- Designer: *Kristen McConnell*
- FE engineer: *Mark Dewey*
- Product/team Slack channel: *vsa-clipboard*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Not sure if you had this on your radar yet so tagging you here. We can discuss in this week's sitewide content meeting.

**Comment by brianalloyd** [comment]
@RLHecht @DanielleThierryUSDSVA let me know how PW team and engage on this ticket, post internal review.  TIA.

**Comment by brianalloyd** [comment]
@RLHecht @DanielleThierryUSDSVA checking on ticket as this was mentioned in ToT's today.  Any idea on timing for this or when you might need PW FE support?  Thank you all for your support.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @brianalloyd. I think we can handle this in Drupal, but will double check with Randi. Thanks!

**Comment by RLHecht** [comment]
Opened ticket #23589 to implement the actual work in Drupal.

**Comment by RLHecht** [comment]
@abuckley3385 Do you have the text for this landing page in a word doc by any chance so it's easier for @lunascoop to add it into Drupal?

**Comment by kristenmcconnell** [comment]
You should be able to Inspect and copy the text within the Sketch for Teams wireframe link above. Let me know if you can't access Inspect for some reason.

![Screen Shot 2021-04-21 at 4.03.00 PM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/7c6e4c31-0ca3-4fc9-9ffd-15d41b02cf6c)

**Comment by lunascoop** [comment]
@kristenmcconnell can you provide the link urls for the page content below?

- A verified ID.me account that you can **create here on VA.gov**
- Get tips for protecting your personal health information

**Comment by kristenmcconnell** [comment]
- The ID.me link is https://api.id.me/en/registration/new. It is the same one that exists on a few of the other health care pages, such as https://www.va.gov/health-care/view-test-and-lab-results/.
- The "Get tips..." link is https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/protecting-your-personal-health-information. It is also found on a few of the other health care pages, such as https://www.va.gov/health-care/refill-track-prescriptions/

**Comment by mnorthuis** [comment]
@RLHecht @brianalloyd @lunascoop This ticket doesn't specifically mention adding this new static page into the left nav of the health care hub.  Is that work covered here or in another ticket?

**Comment by RLHecht** [comment]
@mnorthuis Not that I'm aware of. Do you have a doc with your IA guidance? If so I can add it to a ticket for when we publish the page (I'm not sure when that is— @DanielleThierryUSDSVA do you know when this is launching?)

**Comment by kristenmcconnell** [comment]
@RLHecht Here is the IA guidance: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-questionaires.md

Our staging review is tomorrow. We have a final stakeholder meeting on the calendar for May 21.

**Comment by jilladams** [comment]
Closed under https://github.com/department-of-veterans-affairs/va.gov-team/issues/23589
