### ISSUE TITLE
General Analytics Request for VAOS for Distribution Data Flow Check

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#22538]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- @laurenernest 
    
- What team/project is this work for?
    - VAOS for Distribution (vaccine scheduling initiative) pilot
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

Rollout pilot starting March 31 to current day

## Analytics to Track Down
> Examples
> 
> - [ ] Metric 1
> - [ ] Metric 2
> - [ ] Metric 3

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
https://analytics.google.com/analytics/web/#/dashboard/oGLWNZNTThqBAPP0VLQykA/a50123418w177519031p176188361/

[(Template link if above doesn't work)](https://analytics.google.com/analytics/web/template?uid=r4yGqUOPTUmyRN9dasB2zg)

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._
Now that there's real production data, I expected to see data in 2 widgets of the dashboard that I'm not currently seeing:
- Traffic from VEText
- Submissions by Facility

Related tickets and conversation: #20035, #21931

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by laurensimpson14** [comment]
**Traffic from VEText**: Set the filter to "Page" "Containing" "https://www.va.gov/health-care/schedule-view-va-appointments/appointments" and delete the ?utm_source=vetext at the end. 

Then, add a second filter and set the filter to "Source" "Containing" "vetext". 

Note: ^ this will show you pageviews from many pages. For example: 
	- https://www.va.gov/health-care/schedule-view-va-appointments/appointments (_the one you initially wanted_)
	- www.va.gov/health-care/schedule-view-va-appointments/appointments?postlogin=true
	- www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/
	- www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/received-dose/
	- www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/facility/

If you are looking for pageviews from all /appointments pages and are OK with the above links then those two filters will work. 

However, if you would like the pageviews to ONLY include the first bullet point above, then set the first filter to "Page" "_Exactly matching_" "https://www.va.gov/health-care/schedule-view-va-appointments/appointments".

Submissions by Facility: It looks like the issue here is that we may not be collecting the facility ID. I see that you mentioned this to @jonwehausen yesterday in ticket #20035. @jonwehausen, can you weigh in here? Would she need to request another GTM setup to track the facility ID with the submission data? (**note**: Jon is out today, so we likely won't hear back on this piece until Monday.)

**Comment by jonwehausen** [comment]
@laurensimpson14 @laurenernest Weighed in here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/20035#issuecomment-813571727

**Comment by jonwehausen** [comment]
@laurensimpson14 @laurenernest Updated [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20035#issuecomment-825137680).

**Comment by laurenernest** [comment]
Thank you both for double checking the facility data! Good to close this ticket.

**Comment by laurensimpson14** [comment]
@laurenernest It looks like the facility ID is not being passed. Is this something that you'd like to be able to filter by? If so, we would need to include this on submission.

**Comment by laurenernest** [comment]
Yep, I'll have my team do some work on the submission data then submit a new GTM request.

**Comment by laurensimpson14** [comment]
Sounds good 👍
