### ISSUE TITLE
Design Feedback - Design intent [VSA Authenticated Experience, Preferred Medical Facilities in the VA.gov profile]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#22531]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Nice work!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Add a [success alert ](https://design.va.gov/components/alertboxes#background-color-only)after they have updated their list
- Per [VA guidelines](https://design.va.gov/components/alertboxes#background-color-only), background only alerts are for immediate feedback, not static messages. If you add an H3 (or H2 depending on the other H tags) then it will be considered a ‘callout box’ and will be within the VA guidelines.

**Should:**
- None

**Consider:**

- Using a borderless table to display the locations
- Having a label to show which facilities are ‘preferred’ for scheduling (if available). I think this would help clear up an uncertainty about registered facilities
- Add an H2 tag above the list of facilities

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by andaleliz** [comment]
Thanks @allison0034! I thought about a success alert, but that doesn't follow the pattern we have in the rest of profile.  There's no success message when any section is updated and saved.  I have this on my list of overall profile improvements to consider in the future. With that context, is adding a success alert still a must?

**Comment by allison0034** [comment]
@andaleliz good question. My assumption is we would want to do things the right way going forward but I want to confirm with Ryan. @rtwell should Liz add the success alert message here even if the rest of the profile tools don't have it?

**Comment by andaleliz** [comment]
Responding to the other areas of feedback:

> Per VA guidelines, background only alerts are for immediate feedback, not static messages. If you add an H3 (or H2 depending on the other H tags) then it will be considered a ‘callout box’ and will be within the VA guidelines.

We're not going to move forward with the background only alert below the list, since we feel the context could get lost. I glazed over that guideline about background only alerts though, so thank you for pointing that out!

>Using a borderless table to display the locations

I explored this in earlier iterations but the team decided to include the border to be consistent with the other areas of profile

> Having a label to show which facilities are ‘preferred’ for scheduling (if available). I think this would help clear up an uncertainty about registered facilities

I agree, and did explore this in earlier versions as well (great minds!). Since we're talking about the idea of "current" or places where you still receive care, rather than preferred, we opted against this label.

> Add an H2 tag above the list of facilities

I had an H2 in earlier versions, but Danielle recommended removing it since it is fairly redundant with the H1. This could change depending on what we call it once we know more about the VAOS flow. I'll keep this in mind.

**Comment by andaleliz** [comment]
@allison0034 Actually, it looks like we _do_ have a success message in some but not all parts of the profile! I definitely wanted to add one here so will update the designs to reflect what we do in direct deposit.

**Comment by rtwell** [comment]
apologies for being late to the game @andaleliz  

I would still recommend a simplified approach to displaying the list in one view, and validate it's working (or not)

1. it's simpler and keeps users focused on the task at hand which [aligns with our design principles](https://design.va.gov/design/principles)
2. while VAOS does leverage the `+ more` interaction, however we are meeting known user needs by doing so. We do not know this is an issue for this page. happy to elaborate on this if you'd like.
3. less engineering lift to implement 
4. better aria / focus management for accessibility
5. considering design system guidance on [links and buttons](https://design.va.gov/components/buttons), I would think `+ more` interaction should be a button, not a link. Josh also noted this in his [accessibility ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22466). if this were a secondary button, I think we would need a primary button and a secondary button, which also breaks the pattern of Profile. either way, this change gets tricky b/c it probably would trigger revisiting Profile as a whole (regarding buttons and links)
6. it's also somewhat unexpected to see a short list of locations, skipping + more, clicking edit to see a longer list than what a user was initially viewing.

**Comment by andaleliz** [comment]
@allison0034 I've added a success alert following how this is handled in other areas of profile. There's opportunity to improve the UX on mobile, so our team is going to iterate on that improvement w/ the direct deposit section. That's already live, and it'll be a while before facilities sees production.  We'll translate the improved UX from DD to the rest of profile once we have it dialed in (including facilities, when it launches).

I need to get content feedback on the success message, but it's on the [desktop version](https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006545/comment/sitemap,comments?mode=i) now.  Will add to mobile once we have the language right.

@rtwell totally agree w/ you about displaying the list in one view; the mockups now reflect this too.

**Comment by rtwell** [comment]
I know this issue is closed, but I wanted to give @andaleliz a big THANK YOU for your willingness to feedback and quickly turning around the feedback!
