### ISSUE TITLE
[Design] My VA - Coordinate assistive tech mobile testing on Android and iOS

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22543]
## Background
Following up from our conversation with Trevor about assistive tech in testing, we'll need to with Josh or Trevor to figure out how to do this on Android devices as it's currently only set up for iOS. We'll then need to conduct a dry run to make sure everything is working smoothly.

## Tasks
- [ ] Work with Josh and/or Trevor to get assistive tech working on Android
- [ ] Conduct dry run to ensure all tech is working properly

**Comment by tressaellen** [comment]
Update here - I don't think there is a need for a dry run for this. Trevor mentioned that things are 1:1 for IOS and Android, and we can double check that with the study that Leyda is running (it will be before ours). 

I do recommend that we still run a practice run when it's time for our study though.

If there isn't anything else for this ticket, then I think we're good to close.

**Comment by ajakabcin** [comment]
Awesome thanks for closing the loop on this. Please let us know how the other study goes in case there's anything we need to adjust for.
