### ISSUE TITLE
CLP Yellow Line under banner when 'Back to Top" button is engaged [Chrome/MAC OS]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22546]
## Issue Description
_CLP Yellow Line under banner when 'Back to Top" button is engaged [Chrome/MAC OS]_

![Screen Shot 2021-04-01 at 12 47 19 PM](https://user-images.githubusercontent.com/70410912/113357776-c425e400-9301-11eb-906a-abb35ff6b1f8.png)

## Steps to Recreate:
1. Visit https://staging.va.gov/campaign-mission-act/
2. Enter passcode
3. Scroll to bottom of page 
4. Engage the 'back to top' button 
5. Yellow line appears under 'Hero' banner 

## Front end tasks
- diagnose the reason for the yellow line 
- Take steps to remove from the UX

## Acceptance Criteria
- [ ] behavior of 'back to top' element is working with out producing 'yellow line' 
- [ ] Tier 3 component - doesn't require PO/PM review for release
- [ ] Since this is a protected CLP, needs to remain behind firewall on "staging" and be released to prod env.

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
2 solutions:

1) Add `el.blur()` after this line: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c47b89b63ee13348f167310c28949db54f8256fa/packages/formation/js/back-to-top.js#L11
2) Add `outline: none;` on the body tag.

CC @1Copenut @joshkimux do either of you have a preference? 🙂 

Related slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1622130966269100?thread_ts=1622128639.266400&cid=C52CL1PKQ

**Comment by kelsonic** [comment]
After discussing with @joshkimux it sounds like all we will need to do is switch this line here to `const el = document.querySelector('h1');`: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/c47b89b63ee13348f167310c28949db54f8256fa/packages/formation/js/back-to-top.js#L7

**Comment by mmiddaugh** [comment]
Hi - our "Back to top" implementation on Vet Centers was flagged during a recent staging review for 508 defects - 

- ARIA-hidden 
- a missing focus halo in Safari 
- failure to display in IE-11 

Let us know if your update touches any of these items!

**Comment by brianalloyd** [comment]
@mmiddaugh we're addressing the IE-11 issue in a separate ticket during Sprint 49.

**Comment by joshkimux** [comment]
> Hi - our "Back to top" implementation on Vet Centers was flagged during a recent staging review for 508 defects -
> 
> * ARIA-hidden
> * a missing focus halo in Safari
> * failure to display in IE-11
> 
> Let us know if your update touches any of these items!

These are separate defects that we'll need to work on 🙇

**Comment by brianalloyd** [comment]
Validated, closing ticket in support.
