### ISSUE TITLE
[FE] My VA: Implement handling of long load times for claims & appeals

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22565]
## Background
Currently when the claims and appeals section takes a long time to load it isn't very clear to the user what's happening. We need to improve this experience.

## Spinner Content

We're loading your information

<img width="568" alt="Screen Shot 2021-04-05 at 12 14 54 PM" src="https://user-images.githubusercontent.com/58752772/113596654-18bdad80-95e7-11eb-9787-591f4624ddd6.png">

## Spinner failure guidelines

If a spinner doesn't resolve in 45 seconds we will show the following error. (The same errror as if an API is down)

**We can't access any claims or appeals information right now**

We’re sorry. Something went wrong on our end. If you have any claims or appeals, you won't be able to access your claims or appeals information right now. Please refresh or try again later.

<img width="691" alt="Screen Shot 2021-04-05 at 12 17 57 PM" src="https://user-images.githubusercontent.com/58752772/113596949-75b96380-95e7-11eb-889f-8577139d9792.png">

## Tasks

- [ ] Implement spinner functionality
- [ ] Implement error message when it takes too long to pull up data

**Comment by erikphansen** [comment]
This will be on staging soon.

Validating the loading spinner's text will be easy.

Validating that we stop checking for claims and "error out" about 45sec or so will be a little more tedious

**Comment by ajakabcin** [comment]
Confirmed with user 15
