### ISSUE TITLE
set up initial analytics funnel

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#22561]
- [x] integrate firebase into app

- [x] create helper functions

- [x] determine what user properties to set and what the data for them is and when to change them

- [x] determine when to log non-fatal errors and what "errors" we want to track

- [x] create first events for log in (login start, login success, login fail/cancel)

**Comment by lexicalninja** [comment]
Need to start anlaytics meetings with Ayush and get first events done

**Comment by ayushchak** [comment]
Some sub-components are more important than others - this can be kept to Tier 1 as priority.

**Comment by lexicalninja** [comment]
initial funnel complete. All out of the box functionality works, so sessions, screen timers, etc work

@ayushchak do we want to keep this ticket open or make new tickets to add the Metrics Fun work we do?
