### ISSUE TITLE
Attachment access denied

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#22562]
### User Story
As a user I want to know if I cannot access an attachment

### Dev notes
API Error
```
SM112: # 'User is not owner of entity requested' (usually attachments)
detail: 'You do not have access to the requested resource'
```
### TBD:
- [ ] Copy/Content
- [ ] Happy Path
- [ ] Design

**Comment by narin** [comment]
@drjecker I don't think we'll need to account for this error.  If we ever do, it is a bug to be fixed in the mobile code.
