### ISSUE TITLE
Access for Dene Gabaldon

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#22566]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   >  Mary O'Toole
- Please provide your name.
   > Dene Gabaldon
- Please Provide your email.
   > dene.gabaldon@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I am a Senior UX Designer on VSA Caregivers and I need SOCKS to review instance. 

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key?
 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzi8NL3p8wq2PtdiZ7Z+r7aXSy3//+FF3XzR2HO5HZIcvEFfURbd/sBWNnHAA83y/hOOnptxa91e01mXcUCABbdF6lPpcsvfQbZM3NnY6f9s1DrMcg5L4l1USYlVIqrJWDSs/7EOXRyyWSjjFIfYF4VwRwZMLDg/zp4MudUcqt5TXvytXZXiDHcCum4S9SRPEI0UNAGcOLjpSB1ntH5dmW/3kVhL/A2ovSFB/k+1m3UVVShdm1Bhm1gkhRiu9Jqzbs6S6NeciCgLt/JIvAGe8LgCcSa9O3ae5L4HLxf4VI54y9AosOEB54B75aN/q3raTjkmp2nn7jqruVQxJoBFqNuhHXoX9aH7CKShB17oZQNlhrG1TTF3lgeect3tCkzUa5tN+FF45JzDB/443FH/OaVGwj/7kKt+NBJ+fYTkkvdhMUQRtMp7sEMsOmFjvFvrT6YqqqLAcCCy+B7foT54QQAxpqQyG79SgJ5QZCOJjOEE6A21z5AuDwPh2pWxKqd/U= denegabaldon@Dene-Gabaldon-Macbook.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why? 

/cc @department-of-veterans-affairs/vsp-operations

**Comment by jsev-io** [comment]
SOCK Access Approved - @Dene-human please confirm

**Comment by Dene-human** [comment]
I confirm that it is working. @jsev-io
