### ISSUE TITLE
[FE] My VA: Implement error states for claims & appeals

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22564]
## Background
Following up from #21373 and #21838, we need to implement the errors states on the frontend.

## Content/Design for when an API is down

**We can't access any claims or appeals information right now**

We’re sorry. Something went wrong on our end. If you have any claims or appeals, you won't be able to access your claims or appeals information right now. Please refresh or try again later.

<img width="902" alt="Screen Shot 2021-04-02 at 2 19 00 PM" src="https://user-images.githubusercontent.com/58752772/113442700-03554300-939d-11eb-98b0-ae6988f0c017.png">

## Content/Design for when there's downtime

**We can't access any claims or appeals information right now**

We’re sorry. We’re working to fix some problems with the claims or appeals tool right now and cannot display your information on this page. Please check back after [Month, Date] at [00:00 a.m./p.m. ET].

<img width="874" alt="Screen Shot 2021-04-02 at 2 19 04 PM" src="https://user-images.githubusercontent.com/58752772/113442806-31d31e00-939d-11eb-852e-127c137edfb2.png">

## Tasks

- [ ] Build error for when the API is down
- [ ] Build error state for indicating downtime

See designs linked above

**Comment by erikphansen** [comment]
Merged and closing since this is hard to properly validate on staging.
