### ISSUE TITLE
Add Dené to SOCKS

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#22560]
SOCKS is a web proxy tool used to look at code before it's deployed to Staging or Prod.

Follow the steps [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md#additional-access-for-developers), including creating an Environment Access Request.

Here's an example ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16354

**Comment by Dene-human** [comment]
I have submitted ticket here #[ 22566](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22566)

**Comment by Dene-human** [comment]
I know have access to SOCKS
