### ISSUE TITLE
[FE] My VA: Implement "Go to your profile" link

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22570]
## Background
Users needs to be able to navigate to their profile from the redesign My VA dashboard. This has already been designed, it just needs to be implemented on the fronted.

## Tasks

- [x] Implement link to profile with link text that reads "Go to your profile" in the top right corner of the screen, as shown in attached screenshot below.

## Screenshot
![My VA LOA1](https://user-images.githubusercontent.com/45603961/113439530-c26b2780-93b8-11eb-98a0-8053ecea7c41.jpeg)

**Comment by erikphansen** [comment]
This can be validated on staging.

**Comment by ajakabcin** [comment]
Confirmed on staging
