### ISSUE TITLE
526 fix separation location and RAD date for active duty guard and reserve

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#22582]
If someone is currently in the guard or reserves and is activated on federal orders, they must provide their separation location.

Service members who are currently activated on federal orders are bdd-qualified and will have a RAD date of the 
end date of their schedule 10 orders.

# Acceptance criteria
## FE
 - [x] separation location must appear after federal orders question
 - [x] if the service member is activated on federal orders they must provide a separation location (even if they are not bdd-qualified, we need separation location for all future discharge dates)
## BE
- [x] the RAD date should be the last of: the last non-guard/reserve service period & the end date for federal orders 
- [x] a SM is BDD-qualified if their rad date is 90 days in the future

As these are merged: 
BE: update the return url so any SM that should have separation location but doesn't is returned to the separation location page.

http://sentry.vfs.va.gov/organizations/vsp/issues/32329/?project=3&referrer=AssignedActivityEmail

Still unknown:
How do we know if someone in the national guard is active duty?

**Comment by Mottie** [comment]
FE work has been completed - https://github.com/department-of-veterans-affairs/vets-website/pull/17558

**Comment by annaswims** [comment]
code run to send people back to an earlier page

`urls =["/claim-type", "/review-veteran-details/separation-location",  "/separation-pay", "/retirement-pay", "/training-pay"]

urls.each do |url|
  forms = InProgressForm.where( form_id: '21-526EZ').return_url(url)
  forms.each do |f| 
    md = f.read_attribute('metadata')
    md['returnUrl'] = '/review-veteran-details/military-service-history'
    f.write_attribute('metadata', md)
    f.skip_exipry_update = true
    f.save!
  end
end


`

**Comment by annaswims** [comment]
````ruby
forms = InProgressForm.where(form_id: '21-526EZ')
forms.each do |f|
  fd = JSON.parse(f.form_data)
  if fd.dig("serviceInformation","separationLocation", "separationLocationCode").blank?
    sps = fd.dig("serviceInformation","servicePeriods")&.map {|sp| sp["dateRange"]["to"]} 
    if sps 
      last_date = (sps << fd.dig("title10Activation","anticipatedSeparationDate")).compact.sort.last
      if last_date && Date.parse(last_date) > Date.today
        md = f.read_attribute('metadata')
        puts "updating #{f.id} - previously #{md}"
        md['returnUrl'] = '/review-veteran-details/military-service-history'
        f.write_attribute('metadata', md)
        f.skip_exipry_update = true
        f.save!
      end
    end
  end
end

````

**Comment by annaswims** [comment]
I think we're all set on this one, but I'd like to keep an eye on stats for a bit.

**Comment by annaswims** [comment]
This has been blocked by EVSS for some time, but I expet to be able to verify in staging tomorrow and prod July 7

**Comment by annaswims** [comment]
Fixed on August 18
