### ISSUE TITLE
Add custom picker to dropdowns throughout app

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22584]
## Acceptance Criteria
1. Replace current implementation of the picker
2. Apply the custom picker CC to the following parts of the mobile app:
     - Past Appointments > date range 
     - Edit Direct Deposit > Account type
     - Edit Address form:
          - Country
          - State (U.S.)
          - APO/FPO/DPO
          - State (Military)
     - Compose a Message form (TBD - depending on when this ticket is worked on)
          -  Recipient
3. Check that the form wrapper component still works as expected (including field errors) once the custom picker has been applied

## Accessibility Implementation Guidelines

**Mark [picker header] as Header 1**

**Cancel button**
accessibilityLabel= "cancel”
accessibilityHint= "Cancels selection and closes the menu"
accessibilityRole= “button”

**Done button**
accessibilityLabel= "done"
accessibilityHint= "Confirms selection and closes the menu"
accessibilityRole= “button”

**Items in the dropdown list**
accessibilityState= denote when "selected" or "unselected"

**Comment by digitalken** [comment]
Added to TestRail

**Comment by digitalken** [comment]
Linked bug - https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23539

**Comment by digitalken** [comment]
4/23/2021 - Test this when bug #23265 has been addressed for accessibility.
Visually and functionally, this one looks good.  Accessibility needs some work.

**Comment by digitalken** [comment]
PASS 4/30/2021 - Looks good in iOS and Android.  Closing.
