### ISSUE TITLE
Design Feedback - Staging Review - vsa- education STEM Scholarship Automated Decision

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#22580]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Use a text link for ‘View details’ button. If you feel it needs to be more prominent, use an [action link](https://design.va.gov/components/action-links)

**Should:**
- None

**Consider:**
- None

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by amyknox** [comment]
@allison0034 - Sorry should've asked if this was must or should when we were on the call. 

The "View details" button is the existing style throughout the claims tool. Is your feedback intending that we change it for all claims cards in the Claims status tool? 

![image](https://user-images.githubusercontent.com/41081945/113445420-da947400-93c3-11eb-845b-794118a272bf.png)

**Comment by allison0034** [comment]
@amyknox good question. I have asked Ryan in the Design Slack channel and tagged you.

**Comment by rtwell** [comment]
ideally yes, all of those buttons should become action links as they do nothing on this page, but navigate users to other pages.

**Comment by amyknox** [comment]
Thanks. We'll incorporate this update.

**Comment by amyknox** [comment]
@allison0034 @rtwell 
Our team was working on this launch-blocking update but hit a snag.  The Secondary action link styling isn't available to our devs yet.  Do you have an ETA for this design component?  Can we scale it back to a "should" and proceed with secondary, blue buttons? 

![image](https://user-images.githubusercontent.com/41081945/114444452-edb1fb80-9b9c-11eb-804d-ec9190bf0ff3.png)

**Comment by allison0034** [comment]
@CrystabelReiter @bkjohnson per @amyknox 's comment above, do either of you know when the secondary action link styling will be available for devs?

**Comment by bkjohnson** [comment]
@amyknox, the secondary action link styling should already be available under the name `va-action-link--white`.

It can be seen as the [third action link here](https://design.va.gov/storybook/?path=/docs/components-action-link--page).

**Comment by amyknox** [comment]
Thanks @bkjohnson - we'll take a look and get back to you if we have any questions.
