### ISSUE TITLE
Replying to a message a users is not part of

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#22598]
### User Story
As a user, if I try to reply to a message I am not part of, I want to know so that I can contact my MHV Coordinator or the HRC Helpdesk for support.

### Reasons why this might happen (from OCC)
- Provider initiating a message to a patient who is not part of their HCT by mistake. Many of the providers are associated with multiple teams so this can happen.
- Clinician composed a new message to the patient. They selected a Triage group that the patient is not part of. This happens them clinician has more than 2 triage groups that they manage.
- Patient was manually added to TG – user communicated with the TG but was later removed from the manual association
- Associations updated based on clinic appointments ( dropped off the list of TGs)
- Blocked from the specific Triage group (See [#22600](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22600))
- Blocked from the facility (See [#22602](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22602))

### Dev Notes
API Error
```
SM129:
detail: 'Unable to reply because you are no longer associated with this Triage Team'
```

**Comment by drjecker** [comment]
@narin Looking to see how this is currently handled and what the user is given for suggested follow-up. Screenshots would be welcome.

**Comment by narin** [comment]
@drjecker I think this was mentioned in a Slack convo, but what we can do here is check the user's recipients before displaying the reply form to prevent this error from occurring, displaying some sort of messaging like "You are no longer allowed to send messages to `x`.  Please contact..."

**Comment by drjecker** [comment]
Closing this ticket as it's already covered by [#22600](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22600)
