### ISSUE TITLE
[COGNITION]: STEM Automated Decision - Consider moving the TTY phone number above the location link in right rail

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#22595]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a screen reader user, I would like to have the three telephone numbers gathered together in the right rail, instead of hearing the first two, then a location link, then the TTY phone number. This will benefit users who might also have a cognitive issue or be looking for the TTY number with other telephone numbers visually.

## Screenshots or Trace Logs

![telephone-number-rearranged](https://user-images.githubusercontent.com/934879/113450895-70c99980-93c6-11eb-853a-68127700f96d.jpg)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18358

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
@noahgelman @1Copenut This fix is on staging and ready for review

To check on staging
1. Log in as user 220
2. Click the My VA link in the header
3. Click "Check your claim or appeal status"
4. Click "View details" for any of the STEM scholarship claims


![Screen Shot 2021-08-30 at 3.24.28 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/9cded842-0a8a-4e91-8277-d05613713567)

**Comment by 1Copenut** [comment]
@delli-gatti-michael 👍 LGTM. Moving to close.
