### ISSUE TITLE
DebtRes FSR - Remove 45 days from confirmation page 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#22590]
After much discussion with DMC we need to remove 45 days from confirm page - they have no visibility into timelines and this would be misleading. In the future when they implement SF we can look into integrating the systems to expose this information on va.gov 

cc: @DanielleThierryUSDSVA  for visibility

---
**Example of where this exists in the form**

![image.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/0d3130f1-5a68-4b16-b4df-0e5225fe80f4)

---

**Locations that need to be updated**

- [introduction page mock step 3](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701378/simulate/sitemap?mode=i) -> `Within 45 days of when you submit your request, we’ll send you this information by mail:`

- [confirmation page mock](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134209101/simulate/sitemap?mode=i) -> `We’ll send you a letter with our decision and any next steps within 45 days.`

- [confirmation page mock](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134209101/simulate/sitemap?mode=i) -> `You can expect our decision within 45 days`

---

- [ ] Provide language modification to FE

- [ ] @Craig - change the content to reflect new language

**Comment by rileyorr** [comment]
I've updated the ticket to include the three sections of the form that need to be updated - thanks for bringing those areas up @craigwheeler! 

Adding my thoughts here:

- **Introduction page mock step 3** 
    - Current: Within 45 days of when you submit your request, we’ll send you this information by mail:
    - Proposed: After we’ve processed your request, we’ll send you this information by mail:
- **Confirmation page** 
    - Current: We’ll send you a letter with our decision and any next steps within 45 days 
    - Proposed: We’ll send you a letter with our decision and any next steps. 
- **Confirmation page**
    - Current: When will VA make a decision on my request? You can expect our decision within 45 days. We’ll send you a letter by mail with our decision and any next steps to resolve your debt
    - Proposed: If we remove ‘You can expect our decision within 45 days’ then the section no longer makes sense since the header is implying we’ll provide a timeframe. ‘We’ll send you a letter by mail with our decision and any next steps to resolve your debt’ is redundant of the content above the blue card. How do other forms approach this section when they’re unable to provide a decision timeframe? If there’s no standard way we handle this on confirmation pages, then we should remove this section until we can provide a timeframe.

I'm going to attend this afternoon's content office hours to discuss what content we should move forward with

**Comment by rileyorr** [comment]
Followup after meeting with Beth + Danielle:
We want to propose massaging the language with something like, "If you haven't received your letter within [30, 60, 90, whatever] days, please contact us at xxx-xxx-xxxx.". If our stakeholders are uncomfortable with providing any timeframe, we've received backup content recommendations.  

Will have finalized direction tomorrow after the DMC weekly 👍

**Comment by rileyorr** [comment]
The DMC weekly meeting was canceled this week, and I don't want the new proposed content to be a blocker so we can move forward with what our backup plan was going to be and work towards adding the massaged timeline in the near future. 

**Introduction**
[UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701378/comment/sitemap?mode=i)
- Remove "Within... request,"

**Confirmation**
[UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138138134/comment/sitemap?mode=i)
- Remove the first sentence “We’ll send you a letter… 45 days.”
- Remove the section "When will VA make a decision on my request?"
- Add "If you have a question about the status of your request call us at 800-827-0648 (or 1-612-713-6415 from overseas). We’re here Monday through Friday, 7:30 a.m. to 7:00 p.m. ET." under step 3 of the "How can I check the status of my request?" section

@craigwheeler let me know if you have any questions!

**Comment by craigwheeler** [comment]
Everything looks good to me thanks for clarifying this @rileyorr i'll go ahead and make the changes and reach out if there are any issues.
