### ISSUE TITLE
[COGNITION]: STEM Automated Decision - Consider shortening the accessible labels for downloadable PDFs

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#22593]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## User Story or Problem Statement

As a screen reader user, I would like to hear the entire downloadable PDF label read without having to press `DOWN_ARROW`. NVDA doesn't store quite enough characters in the buffer, so it's a little confusing and I might miss the announcement that the PDF will open in a new tab.

## Details

I like that the team has added the type of download to the accessible labels. That said, I think we can shorten them a bit because the contextual paragraph describes the PDF's purpose clearly.

## Acceptance Criteria
- [ ] Accessible labels are shortened and spot-checked in NVDA for proper read back without a pause

## Proposed Solution (if known)

```diff
<a 
  href="https://www.vba.va.gov/pubs/forms/VBA-20-0995-ARE.pdf"
- aria-label="Download Decision Review Request for Supplemental Claims VA Form 20 - 0 9 9 5. Opens in new browser tab"
+ aria-label="Download VA Form 20 - 0 9 9 5. Opens in new browser tab." 
  target="_blank"
  rel="noopener noreferrer"
>Download VA Form 20-0995</a>
```

```diff
<a
  href="https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf"
- aria-label="Download Decision Review Request: Higher-Level Review VA Form 20 - 0 9 9 6. Opens in new browser tab" 
+ aria-label="Download VA Form 20 - 0 9 9 6. Opens in new browser tab." 
  target="_blank"
  rel="noopener noreferrer"
>Download VA Form 20-0996</a>
```

```diff
<a
  href="https://www.va.gov/vaforms/va/pdf/VA10182.pdf"
- aria-label="Download Decision Review Request: Board Appeal for Notice of Disagreement VA Form 1 0 1 8 2. Opens in new browser tab"
+ aria-label="Download VA Form 1 0 1 8 2. Opens in new browser tab."
  target="_blank"
  rel="noopener noreferrer"
>Download VA Form 10182</a>
```

## WCAG or Vendor Guidance (optional)

* [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18282

**Comment by delli-gatti-michael** [comment]
@1Copenut This is on staging and ready for review

It's been a while so here's a refresher in case you need it:
To check on staging
1. Log in as user 220
2. Click the My VA link in the header
3. Click "Check your claim or appeal status"
4. Click "View details" for any of the STEM scholarship claims
5. The links are located in the "What should I do if I disagree with your decision?" section

**Comment by 1Copenut** [comment]
@delli-gatti-michael 3 of 4 aria-labels were shorter and looked great. The label for Download VA Form 20-0998 was a bit longer "Download Your Right to Seek Review of Our Decision VA Form 20 - 0 9 9 8. Opens in new browser tab". That one might still get cut off by screen readers.

If that's outside the scope of changes, please disregard this comment and feel free to close the ticket when you're ready.

Thank you for the recap comment and heads up!
