### ISSUE TITLE
Fix linting / installation issues in VFS tools repo 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2259]
Linting is currently disabled in the [VFS Tools Repo](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools)

Tasks:

- document the way linting is currently done in VFS tools repo 
- re-enable linting as part of the VFS tools CI

**Comment by oseasmoran73** [comment]
> Determine why the accessibility package cannot be installed on linux

Don't have sufficient information regarding this snippet. Will be creating a ticket for.

**Comment by oseasmoran73** [comment]
Closing as PR has been merged
