### ISSUE TITLE
Replying to a message from the triage group a user is blocked from

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#22600]
### User Story
As a user, if I try to reply to a message from a triage group I am blocked from, I want to know so that I can contact my MHV Coordinator or the HRC Helpdesk for support. Related to issue [#22598](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22598)

**Comment by drjecker** [comment]
@narin Looking to see how this is currently handled and what the user is given for suggested follow-up. Screenshots would be welcome.

**Comment by narin** [comment]
The message the user is given in the MHV app is:

> You can no longer send messages to this Secure Messaging Triage Group.  Please contact the My HealtheVet Coordinator at your local VA Medical Center to see if this Triage Group is currently participating in Secure Messaging, and if you are enrolled in the Triage Group.

**Comment by drjecker** [comment]
### Design
UI is here in InVision: https://adhoc.invisionapp.com/console/share/YM10HVPXJE7V/601892053

### Notes for dev

- Alert should display underneath message thread when a user opens a message from a triage group they blocked from. Should be able to check message sender against users recipient/contact.
- Reply button should not be displayed.
- Headline is Mobile Body Bold
- Text is Mobile Body

### Copy
Headline: Access to this triage group has been restricted
Paragraph: You can’t reply to messages to this triage group. If you think your access was restricted by mistake, contact your My HealtheVet Coordinator at this VA Medical Center.

**Comment by drjecker** [comment]
@bessgreen this has a UI/design for it in InVision as notes above, but doesn't have a click through for it.
