### ISSUE TITLE
Research improvements to Pact logging in vets-website

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#22601]
Scripts for running Pact tests in `vets-website` do not provide logs of failures locally or on CI. A separate file needs to be opened in order to view failure details:
- `/logs/pact.log` for local test runs
- `/test-results/test-results.xml` on CircleCI

This task is to research how Pact test logging can be improved locally and on CI so that a separate file does not have to be opened to view the details of a failure.

**Comment by ddzz** [comment]
Logging has been improved by printing out raw XML output when Pact tests fail on GitHub Actions. This was added in the PR to migrate Pact from CircleCI to GitHub Actions: https://github.com/department-of-veterans-affairs/vets-website/pull/16809

A separate PR will be opened to improve the failure output so that raw XML is not shown.

**Comment by CBonade** [comment]
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/22601

I've started here by implementing the JUnit reporter we were using both on our Unit Tests and our Cypress Tests.  I'm not sure if we want more than that (Mochawesome-level?) or if this is readable enough compared to the raw xml dump prior.  Open to feedback!

**Comment by pjhill** [comment]
Nice -- failures are displayed with some detail:
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/93c4b3e0-7386-42eb-983c-c81a7a035ccd)

If we decide we want to expand reporting beyond this then we can work that under a new ticket.
