### ISSUE TITLE
Common component: Attachment link

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22616]
## Acceptance Criteria
1. Create common component for the attachment link
     - This CC appears on the message detail pages
2. UX/UI details
     - Icon color: #004795
     - Link: 
          - Format: **File name + (file size)**
          - Font-size: 20px
          - Line-height: 30px
          - Color: #004795
          - Style: underline

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/448493167
![Screen Shot 2021-04-02 at 5.43.04 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/f8c2f2df-a9b5-4d95-b769-93ef3907c79f)
.svg: ![paperclip--$color-link-default.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/6a88aaa8-9057-4f8e-ae22-71f756126386)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/23/2021 - Looks good on iOS and Android.  Closing.
