### ISSUE TITLE
Common component: Form attachments

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22610]
## Acceptance Criteria
1. Create common component for form attachments
2. This component will ultimately be inserted into a form wrapper
3. UX/UI consists of:
     - Header: "Attachments"
     - Help hyperlink
     - File name w/ Remove icon
     - Large button
4. Help hyperlink
     - Icon: 16px/16px
     - Hyperlink copy: 16px
5. File name w/ Remove icon*
     - Attachment icon
     - File name + (file size)
     - Remove icon:
          - Icon: 16px/16px
          - Hyperlink copy: 16px
6. Large button*
     - Insert existing large button CC
7. *The File Name & Large Button are conditional and will not always appear in the UI

## Designs
Variation 1 (no attachments in UI): https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364867
Variation 2 (w/ attachments): https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364859
![Screen Shot 2021-04-06 at 8.45.03 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/66d73fe3-9f4d-483b-8115-ad06a0651692)

.svg for help hyperlink: ![question-circle.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/dff0c1c5-196e-4c72-8ef0-1f35e747dbd5)
.svg for Remove button: 
![times-circle.svg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e5ef40e1-12f7-4030-9a6d-f456a133f000)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
Fail - 4/21/2021 - Two medium bugs - one for formatting on Android, one for missing file size when displaying attachment.


https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23570


https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23574

**Comment by digitalken** [comment]
PASS 6/18/2021 - Since #23570 is closed and #23574 requires UX/UI input that wasn't part of the original requirements, I'm closing this one.
