### ISSUE TITLE
Alert: reply expired

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22617]
## Acceptance Criteria
1. On the message detail page, display a mobile alert at the bottom of the page for when the reply window has expired
     - For threaded messages, this alert will appear when the **most recent** message is >45 days
      - **Error should display when the Message detail page loads**
2. This error is handled on both the backend and the frontend:
3. BE handling: the alert displays when the API returns the following error:
     - SM130: detail: 'Unable to reply because the source message is expired'
     - Provide the most recent message ID when making the API call for the reply. The error message will appear if the sentDate of the message being replied to is >45 days.
4. FE handling: compare against the date of the last message in the thread to determine whether to hide the Reply button
     - Hide the **Reply** toolbar button when this mobile alert displays
5. UX/UI for mobile alert:
     - Pull in mobile alert CC
     - All copy is hard-coded
     - Display large button: "Compose a message" 
6. Selecting the "Compose a message" button routes to the **Compose message** form page

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/448878465

## Discovery / UX ticket
#22134

## Accessibility Implementation Guidelines

- Mark "You can no longer reply to this message" as Header 3

**Compose a message button**
- accessibilityLabel= "compose a message"
- accessibilityRole= "button"
- accessibilityHint= "go to the compose a message page"

**Comment by bessgreen** [comment]
Will this be handled on the FE, BE, or both?

**Comment by bessgreen** [comment]
Hi @narin, do you know if this error will be handled on the FE, BE, or both?

**Comment by narin** [comment]
@bessgreen Both if possible. The API should already be responding with the above SM130 error upon submission, but I was thinking that it might be nice for the FE to preemptively alert them when they hit the "Reply" button so that they don't waste time writing up a reply.  We should be able to compare the current date with the `sentDate` of the message on the front end pretty easily.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by ayushchak** [comment]
@ashley-matthews to investigate alternative error message and set launch criticality based on findings.

**Comment by digitalken** [comment]
PASS 6/10/2021 - Looks good on iOS and Android except for accessibiltyHint not being read.  Logged and tracked, so closing.

Bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/25915
