### ISSUE TITLE
[Bug] Financial Status Report - Submission allowed without checking required self-certify checkbox

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#22618]
## What happened?
On Staging, **[Request help with VA debt (VA Form 5655)](https://staging.va.gov/manage-va-debt/request-debt-help-5655/)** (FSR) form, **Review** page, submission was allowed even though **By checking this checkbox, I certify...** checkbox was not checked.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_:
  - `vets.gov.user+228@gmail.com` (Colder)
  - `vets.gov.user+14@gmail.com` (Jerry)
  - `vets.gov.user+1@gmail.com` (Greg)

### Video capture

https://user-images.githubusercontent.com/587583/113464044-babe7980-93de-11eb-82b6-6c1bd6649232.mp4

## Steps to Reproduce
- URL: (https://staging.va.gov/manage-va-debt/request-debt-help-5655/
- Test User _(if applicable)_: [see **Specs** above]
- Advance to **Review** page, completing req'd fields and clicking **Continue** button on the way there.
- Without checking **By checking this checkbox, I certify...** checkbox, click **Submit...** button.
- Observe that browser advances to **We've received your request** (confirmation) page.

## Desired behavior
Form submission should not be allowed without checking self-certification checkbox -- should not advance to confirmation page.

## Acceptance Criteria
- [ ] [see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by LinnJS** [comment]
Accidentally closed this ticket in confusion with another ticket

**Comment by LinnJS** [comment]
@tlei123 this is ready to be validated whenever you get a spare moment

**Comment by tlei123** [comment]
Fix validated on Staging.
