### ISSUE TITLE
[Bug] Financial Status Report - Review page - Repayment/relief options section edit causes page to disappear

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#22615]
## What happened?
On Staging, **[Request help with VA debt (VA Form 5655)](https://staging.va.gov/manage-va-debt/request-debt-help-5655/)** (FSR) form, **Review** page, editing **Repayment or relief options** section caused entire page to disappear.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_:
  - `vets.gov.user+228@gmail.com` (Colder)
  - `vets.gov.user+14@gmail.com` (Jerry)
  - `vets.gov.user+1@gmail.com` (Greg)

## Steps to Reproduce
- URL: https://staging.va.gov/manage-va-debt/request-debt-help-5655/
- Test User _(if applicable)_: [see **Specs** above]
- Advance to Review  page, completing **req'd fields** and clicking **Continue** on the way there.
- On Review page, expand **Repayment or relief options** section, then click 1st **Edit** button [for **Resolution options**].
- Observe that the entire page disappears.

### Video capture
https://user-images.githubusercontent.com/587583/113463047-a9726e80-93d8-11eb-8a93-d5ab5c072191.mp4

## Desired behavior
**Repayment or relief options** section should be editable, without causing the page to disappear.

## Acceptance Criteria
- [ ] [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by leahkeeler** [comment]
@tlei123 - Can this be closed?

**Comment by tlei123** [comment]
@leahkeeler , closing now.  Just did a quick check and the bug's gone.
