### ISSUE TITLE
Update MISSION Act phone number on R&S helpful numbers page

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#22621]
### Content support for:
- Unauthenticated (static) VA.gov pages - resources and support article (https://www.va.gov/resources/helpful-va-phone-numbers/)

**Note: These requests are handled by the Sitewide Content Team.** 

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content

- [x] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * < https://www.va.gov/resources/helpful-va-phone-numbers/ >
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * < There is an incorrect number for the mission act entry. It should be listed as 800-698-2411, option 1 >
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* ASAP as this is incorrect information but no particular date it is needed by. 

---

### About your team

- Team name: *Contact Center Support*
- DEPO product owner: *Chante Lantos-Swett*
- Product manager: *Jason Woodman*
- Product/team Slack channel: *vsp-contact-center-support*

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by RLHecht** [comment]
@clantosswett Thanks for letting us know about this. I'll make the change this morning so it should go live by the next deploy. I'll let you know when it's up there.

**Comment by RLHecht** [comment]
This page is published. Moving to validate and will close after live on site.

**Comment by clantosswett** [comment]
Awesome. Thank you!
