### ISSUE TITLE
Investigate PR Review Times Task

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#22639]
Determine why https://github.com/department-of-veterans-affairs/vets-api/blob/master/rakelib/github_stats.rake is reporting such low times for PR review rate (~19 seconds).

## AC

- [ ] GitHub PR stats are understood

**Comment by LindseySaari** [comment]
Running the query in prometheus give me ~1949 secs (33 min) http://prometheus-dev.vetsgov-internal:9090/prometheus/graph?g0.range_input=1d&g0.expr=avg(tasks_github_stats_scraper_duration%7Brepo%3D%22vets-api%22%7D)&g0.tab=1

**Comment by LindseySaari** [comment]
Defined [here](https://github.com/department-of-veterans-affairs/devops/pull/6389/files)
