### ISSUE TITLE
[FE] My VA: Implement functionality/prompt for LOA1 users

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22644]
## Background
We need to implement the experience for an LOA1 user so that when a veteran signs in they are prompted to set up 2 factor authentication so that we can verify their identity before they can begin personalizing their account. They should also be able to see the "Apply for Benefits" section. However, note that we do not need to attempt logic to tell whether they have any benefits or not, since we won't have access to that info for LOA1 users.

## Tasks

- [ ] Implement designs/copy per documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/loa1_design.md) 
- [ ] Validate functionality 

## Screenshots, Invision & Copy
For reference, please note that the alert is the same as in Profile.
- [Invision](https://vsateams.invisionapp.com/share/SH10HT8JCKYM#/448032788_My_VA_LOA1) 
- [Copy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/my-va-copy.md)

**Comment by erikphansen** [comment]
This was already done:

![Screen Shot 2021-04-07 at 11.36.33 AM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/7ab46d18-c903-4da7-a1fc-584fe133e589)

And [this PR will fix the issue with the ID.me logo being way too large on the button](https://github.com/department-of-veterans-affairs/vets-website/pull/16703)

**Comment by erikphansen** [comment]
This can be validated in staging. Although I'm not sure if we have an LOA1 staging user?

**Comment by ajakabcin** [comment]
Confirmed on staging (I created a new LOA1 user)
