### ISSUE TITLE
[Design] R&S article ‘recommend/share’ feature

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22642]
## Problem Statement(s)
As a Veterans (or someone that supports Veterans) I want to be able to ‘recommend/share’ an article from R&S via email.   
This could help increase content confidence through helping more Veterans better understand the benefits they have earned.  

Explore both a mobile and desktop version.  We know that mobile is the primary method in which Veterans and those that support Veterans are using to review content and interact with content tags.  Having an optimized mobile version and share component would be ideal in improving the user experience.  

Discovery Ticket for Reference [#21180](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21180)

## Outcomes 
Veteran confidence increased through self discovery and source of truth content via VA.gov/resources library. 

Veterans are more informed and are able to share and receive shared content from the Resources and Support library.

## Design 
[Share Article Mock Ups](https://vsateams.invisionapp.com/share/B610RHOJVCHG)

**Comment by callen2563** [comment]
@brianalloyd Hey Brian, Shawna and I were chatting about this copy link component that Laurel had added: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19867
We were wondering if this was ever built out and if so, should we make sure this and the share article link are consistent? I can bring both of these to the design council meeting next week to get thoughts as well. Let me know your thoughts. Thanks!

**Comment by callen2563** [comment]
I have updated the button copy based on the content that was provided. I will be bringing this and the #19867 ticket to the design council meeting on Friday for feedback and direction.

![Share Article - option 3](https://user-images.githubusercontent.com/68560244/115313325-0c863400-a141-11eb-8f70-6586e0f2823c.jpg)
![Share Article - option 3 clicked](https://user-images.githubusercontent.com/68560244/115313336-114ae800-a141-11eb-9628-3fa690f87300.jpg)

**Comment by callen2563** [comment]
@brianalloyd when you get a chance can you add any analytics or research background to this ticket? I'm just hoping to bring that to the design council meeting tomorrow. thanks :)

**Comment by brianalloyd** [comment]
@callen2563 following up on this ticket as discussed.  Refreshing the goal here:

## Problem Statement(s)
As a Veterans (or someone that supports Veterans) I want to be able to ‘recommend/share’ an article from R&S.
This could help increase content confidence through helping more Veterans better understand the benefits they have earned. 

## Research Findings 
In recent research studies it was revealed that Veterans finding content on VA.gov/resources were unaware on how to share helpful content via share methods (what every vehicle Veterans share with connections).  Veterans we're largely confused on how they would share helpful content and being able to "bookmark" links to helpful content that would allow them the ability to quickly revisit to consume the content and/or consume the data via mobile device which is the primary method of reviewing content on VA.gov/resources currently.

## Analytics
Please note: We currently don't have analytics that directly prove this hypothesis, however we do have related analytics that can help support this user story as we drive toward an iterative improvement to the UX for Veterans.  
The initial study would be increased scroll depth, which shows more users are scrolling deeper into resource and content pages and likely consuming content.  Shown Below:
![Screen Shot 2021-04-23 at 10 24 03 AM](https://user-images.githubusercontent.com/70410912/115901512-86a70900-a41e-11eb-804c-3f50da1d55a9.png)

Additionally, user search terms are largely those of "content types" on the R&S library, meaning Veterans are visiting R&S but not finding the previous articles they have consumed.  A copy link, article share copy would help save Veterans a search on R&S and give them a quick link for content consumption ultimately leading them to completing a Tier 1 task on Va.gov.  Metrics shown below:
![Screen Shot 2021-04-23 at 10 29 40 AM](https://user-images.githubusercontent.com/70410912/115901967-1b116b80-a41f-11eb-939f-ffdefeb3a4a3.png)

**Comment by brianalloyd** [comment]
Holding on this until we've gained some perspective concerning the copy link that Sharon's team is working.  The desired intent is to use that approved approach going forward.

**Comment by brianalloyd** [comment]
Closing this ticket based on the decision to go with anchor link solution.
