### ISSUE TITLE
Replace "Apply online" CTA on VAMC Register for care page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#22647]
## Issue Description
The Facilities team recently became aware of the button/link design shift which will impact various CTAs throughout the VAMC product. 

## Current behavior: 
![image](https://user-images.githubusercontent.com/55411834/113612197-bb3c5780-960c-11eb-91a1-5978c2381d87.png)

## Expected behavior
This issue will address the "Apply online" CTA on the VAMC [Register for care page] (https://www.va.gov/pittsburgh-health-care/register-for-care/) which behaves as a link and should be styled accordingly: 
![image](https://user-images.githubusercontent.com/55411834/113602191-8d044b00-95ff-11eb-8eb7-8517d3191157.png)

## Tasks

- [ ] Replace the "Apply online" CTA with a secondary (blue) action link styled according to the [Design system](https://design.va.gov/components/action-links) and [Storybook](https://design.va.gov/storybook/?path=/docs/components-action-link--page)
`<a className="va-action-link--blue" href="#">Call to action</a>` 

## Acceptance Criteria
- [ ] The the "Apply online" CTA as seen on the VAMC [Register for care page](https://www.va.gov/pittsburgh-health-care/register-for-care/) is styled as a secondary (blue) action link, according to the [Design system](https://design.va.gov/components/action-links#how-to-use-other-links) and use Source Sans Pro (Bold), underlined, 16px, #004795

**Comment by kevwalsh** [comment]
This will be addressed via the newly hardened Register for care pages #37631
