### ISSUE TITLE
VRRAP: Update Introduction Page content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22652]
As a developer, I need to update the VRRAP introduction page content so that it is inline with DEPO plain language patterns and practices.

## Assumptions:
1. The signed in note at the bottom of the introduction page is out of scope of this story because it is dependent upon the pre-fill data functionality.
2. If the content in the prototype does not match the content doc, the content doc is to be followed.
3. The page matches the layout and styling of the prototype as closely as possible.

## Acceptance Criteria:
1. The button text "Sign in or create an account" above the subway map is replaced with: "Sign in to start your application"
2. The user has a way to start the application without signing in at the top of the page.
3. The header of the subway map is: "Follow these steps to apply"
4. The content of step 1 of the subway map displays the corresponding content in SA1.
5. The content of step 4 of the subway map displays the corresponding content in SA1.
6. The content of step 5 of the subway map displays the corresponding content in SA1.
7. The privacy act statement is included on the introduction page.

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/86caa72edfb4923a9f3be4a8dba2505532d4d8f3/products/education-careers/application/VRRAP/design/content-doc.md)
2. Prototype: 
   a. Unauthenticated user: https://bahdigital.invisionapp.com/share/9UIAGJUQNXC
   b. Authenticated user: https://bahdigital.invisionapp.com/share/RMIAGJTSDEA

**Comment by ksantiagoBAH** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/16664

**Comment by delli-gatti-michael** [comment]
Local testing complete

[Testrail test case](https://dsvavsp.testrail.io/index.php?/tests/view/105920&group_by=cases:section_id&group_order=asc&group_id=51)

**Comment by delli-gatti-michael** [comment]
Changes are in Staging. Closing this issue
