### ISSUE TITLE
[Bug] Ch31 - Content anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#22668]
## What happened?
On Staging **[Apply for Veteran Readiness and Employment with VA Form 28-1900](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction)** form, the following content anomalies were found:

### Device-/browser-agnostic:

- **Intro** page:
  - **VR&E Orientation**:
    - **Slide 5** (Reemployment Track): 2nd bullet-point "**succed**" was misspelled. ✅ 
    - **Slide 7** (Self-Employment Track): 1st bullet-point "**developm**" was misspelled. ✅ 
    - **Slide 8** (Employment Through Long-Term Services Track): 7th bullet-point "**house**" was inappropriate word-choice [unless money's really provided ONLY for use of house and NOT any other form of shelter].  It should read "housing and food" ✅ 
  - **Sign-in** (Apply):
    - **Form-page subtitle** didn't match prototype. ✅ 
    - **Subway-map**: Step 1 **Get help...** link (href https://staging.va.gov/disability-benefits/apply/help/index.html) threw **500 error**. ✅ 
    - **Bottom form-info** didn't match prototype. ✅ 
- ~**Step 1b** (Vet contact-info) page: **Learn more about military base addresses** collapsible-section was missing.~
- **Review** page: **Submission error-alert phone number** didn't match supplied screenshot.
**Additional feedback from Peggy**
1.	Please update content under **Need help?** to align with our standard content for this component: ✅ 

If you have trouble using this online form, call our MyVA411 main information line at 800-698-2411[hyperlink]. If you have hearing loss, call TTY: 711[hyperlink] ✅ 

2.	Remove errant comma in this sentence: 
Learn more about VR&E from our orientation, and decide if it’s right for you., ✅

3.	~~Orientation Slide 5: Fix misspelling of succeed in this sentence: Recommend changes to your physical workplace that can help you **succed**~~ ✅

4.	Orientation Slide 6:  Please fix error. (See content in bold): 
This track is right for you if you already have most of the skills you’ll need to be competitive in the labor market in a suitable occupation **and suggest removing** for the type of job you want. ✅

5.	~~Orientation Slide 7: Fix misspelling of develop in this sentence: 
Referrals to resources and guidance to help you **developm** a business plan~~ ✅

6.	~~Orientation Slide 8: Fix typo in this sentence: Money to use toward house and food. 
It should read "housing and food"~~ ✅

7.   After a user goes through the orientation, this alert appears: 
Thank you for viewing the VR&E orientation. To apply for Veteran Readiness & Employment benefits now, click the button below.
{link} Apply for Veteran Readiness and Employment
There is a  link not a button below this content, please remove button reference from this alert. ✅
Also this link language differs from other link language that’s also on the wizard, which says "Apply online now with VA Form 28-1900"
 
Please make these links consistent. Our pattern across wizards has been to use the form name. ✅

8. Please add “the” to this sentence for sense/readability: Are you in the Integrated Disability Evaluation System (IDES) or going through “the” Physical Evaluation Board process? ✅

**Subway map page**

9. Please fix error in the paper form name underneath H1 on subway map. It currently says:  Equal to VA Form 21-1900 (28-1900 Veteran Readiness and Employment). ✅
Form number and name  is VA Form 28-1900 (Vocational Rehabilitation for Claimants With Service-Connected Disabilities)

10. Please update this validation error to make it more plain-language friendly and accessible. (occurs in VA file number field): 
does not match pattern "^[cC]{0,1}\\d{7,9}$" ✅

10. https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/communication-preferences
Please fix typo in this sentence: Please let us know which options work best for you and we'll call your email you with more details.

It should be… and we’ll call **or**  email you with more details. ✅

###### Slide 5 (Reemployment Track): mispelled word
![bug-orientation-5-spelling](https://user-images.githubusercontent.com/587583/113628728-2c363c00-961a-11eb-83c6-e4eb56a3c54e.png)
###### Slide 7 (Self-Employment Track): mispelled word
![bug-orientation-7-spelling](https://user-images.githubusercontent.com/587583/113632045-46264d80-961f-11eb-86df-8b75e772daee.png)
###### Slide 8 (Employment Through Long-Term Services Track): inappropriate word-choice
![bug-orientation-8-word](https://user-images.githubusercontent.com/587583/113632941-e466e300-9620-11eb-85e4-c14075d821ef.png)
###### Page-subtitle
![bug-intro-post-orientation-page-subtitle](https://user-images.githubusercontent.com/587583/113635793-1fb7e080-9626-11eb-8e2e-8572d867b246.png)
###### Subway map Step 1 Get help link 500-error
![bug-intro-post-orientation-help-link](https://user-images.githubusercontent.com/587583/113635256-2a25aa80-9625-11eb-937a-da0e0de2f9fa.png)
![bug-intro-post-orientation-help-link-500](https://user-images.githubusercontent.com/587583/113635265-2d209b00-9625-11eb-94de-5e4cb19d7285.png)
###### Bottom form-info
![bug-intro-post-orientation-bottom-info](https://user-images.githubusercontent.com/587583/113636577-a7eab580-9627-11eb-838a-6b1a22b107c7.png)
#### Step 1b (Vet contact-info) page missing Learn more about military base addresses section
![bug-step-1b-missing-mil-addr-help](https://user-images.githubusercontent.com/587583/113638487-d2d70880-962b-11eb-8393-d53b74bc2fdf.png)
#### Review page submission-error-alert phone-number
![bug-review-submission-error-phone-nbr](https://user-images.githubusercontent.com/587583/113641520-9f4bac80-9632-11eb-9f89-646e57886f4b.png)

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: VR&E Orientation, Slide 5 (Reemployment Track):
- Test User _(if applicable)_: [TBD]
- [No specific interactive steps needed.  Just access form, advancing as needed through wizard/orientation and pages to observe anomalies listed above in **What happened**.]

### Device-/browser-agnostic

- **Intro** page:
  - **VR&E Orientation**
    - [x] **Slide 5** (Reemployment Track): 2nd bullet-point "succed" should be spelled "**succeed**".
    - [x] **Slide 7** (Self-Employment Track): 1st bullet-point "developm" should be spelled "**develop**".
    - [x] **Slilde 8** (Employment Through Long-Term Services Track): 7th bullet-point "house" should be "**housing**" [unless money's really provided ONLY for use of house and NOT any other form of shelter].
  - **Sign-in**:
    - [x] **Form-page subtitle** should match one of the prototypes - [[not signed-in](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526674/)] [[signed-in](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526686/)]:
      ![spec-intro-post-orientation-page-subtitle](https://user-images.githubusercontent.com/587583/113645666-205b7180-963c-11eb-8be5-4ae735169112.png)

      ![spec-intro-post-orientation-page-subtitle-signed-in](https://user-images.githubusercontent.com/587583/113645477-cce92380-963b-11eb-8b10-9a08445135b6.png)

    - [x] **Subway map**: Step 1 **Get help...** link should successfully navigate to correct destination page.
    - [x] **Bottom form-info** should match [prototype](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526674/):
      ![spec-intro-post-orientation-bottom-info](https://user-images.githubusercontent.com/587583/113636668-d10b4600-9627-11eb-86da-a22a06926f38.png)
- [x] **Step 1b** (Vet contact-info) page: [**Learn more about military base addresses** collapsible-section](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526676/) should be included:
  ![specs-step-1b-missing-mil-addr-help](https://user-images.githubusercontent.com/587583/113638640-29444700-962c-11eb-920c-aa3496e03453.png)
- [x] **Review** page: **Submission-error-alert phone-number** should match [supplied reference-screenshot in TestRail](https://dsvavsp.testrail.io/index.php?/attachments/get/810):
  ![specs-review-submission-error-phone-nbr](https://user-images.githubusercontent.com/587583/113641624-df129400-9632-11eb-95a5-504a180dc26d.png)

## Acceptance Criteria
- [x] Address spelling
- [x] Check platform error messaging
- [x] Longer sub-title is used
- [ ] A PR has been requested for merging

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by micahchiang** [comment]
Leaving some comments here for our planning session today:
- the additional information component for military bases is no longer necessary, as that information appears below the country dropdown. That is the most up to date design to my knowledge, so the mocks might be a little dated.
- The phone number discrepancy might be a platform level change

**Comment by jason-gcio** [comment]
Go with longer sub-title
