### ISSUE TITLE
[Design] Direct deposit for edu: Add pngs or jpegs of design files to Github

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#22664]
## Background

So we can easily link to/share the information, especially in a case where we lose access to old prototypes, we need the PNGs or JPEGs of the direct deposit for edu screens uploaded to GitHub.

## Tasks

- [ ] Upload direct deposit for edu screens [to this folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/images).

## Accepted Criteria
- [ ] Images uploaded to folder mentioned above

**Comment by jason-gcio** [comment]
Dupe of #22665
