### ISSUE TITLE
Error | No Contacts Assigned

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22669]
## User story
As a user, if I have no contacts in secure messaging, I want to know how to get them so that I can send a message.

## Acceptance Criteria
1. Create an error state that displays when a user has no contacts assigned
2. This error appears on the **Compose a Message** page when the API returns the following error:
      -  SM119:  'Triage team does not exist' when trying to create new message
3. UX/UI for mobile alert:
     - Pull in mobile alert CC
     - All copy is hard-coded
     - Display large button: "Go to Inbox"
4. Selecting the "Go to Inbox" Large Button routes to the Inbox list page

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/448880937_No_Contacts_Error

## Discovery ticket
#21090

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

- Mark "We can't match you with a provider" as Header 2

**Return to Inbox button**
- Title= "Go to Inbox"
- accessibilityHint= “Go to the Inbox page” 
- accessibilityRole= “button”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Add to TestRail.

**Comment by komaly15** [comment]
Note: there is no api error associated with this, so this is displayed when the api call returns a 200 status code (success), and an empty list for the recipients

**Comment by digitalken** [comment]
PASS 4/26/2021 - Looks good on iOS and Android.  Closing.

**Comment by bessgreen** [comment]
account for testing: judy
