### ISSUE TITLE
Explore converting a page component to React-Redux's useSelector and useDispatch hooks

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#22662]
We're now on the latest version of react-redux, so we can use their `useSelector` and `useDispatch` hooks instead of using `connect()`.

Docs are here: https://react-redux.js.org/api/hooks (they're very good docs, highly recommend reading them).

Generally, `useSelector` replaces what we use `mapStateToProps` for. And `useDispatch` replaces what we use `mapDispatchToProps`, except that it doesn't automatically wrap the actions with `dispatch`, it just returns `dispatch` for you to use. We can then do `dispatch(someAction())`, where `someAction` was something we had in `mapDispatchToProps` before.

I think any component with both `mapStateToProps` and `mapDispatchToProps` could be used to try this out.

**Comment by jenniemc** [comment]
Converted "TypeOfVisitPage" component to use react-redux recommended `useSelector` and `useDispatch` hooks on #23404
