### ISSUE TITLE
[Design] Direct deposit for edu: Add pngs or jpegs of design files to Github

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#22665]
## Background
We need the PNGs or JPEGs of the direct deposit for edu screens uploaded to GitHub in case we lose access to old prototypes. 

## Tasks
- [x] Upload direct deposit for edu screens [to this folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/images).

## Acceptance Criteria
- [x] Files are uploaded to the proper folder

**Comment by sporeboy** [comment]
PNGs uploaded: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/images

**Comment by Samara-Strauss** [comment]
Thank you!
