### ISSUE TITLE
Field errors for Compose Message form (UI)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22667]
## User story
As a user, I want to understand why my message cannot be sent so I can fix the fields that were flagged as invalid. 

## Acceptance Criteria
1. On the Compose a Message form, the Send button should always be enabled
2. When at least 1 field level error appears on the form, the corresponding mobile alert error should also appear at the top of the page
     - Copy is hard coded: "Check your message"
     - The mobile alert should disappear when all field level errors are resolved/have disappeared
3. Any fields that have an associated error will update to display the error UI (as detailed in the input field #19585 & dropdown #19584 CC tickets): 
     - Label text: Mobile Body Bold
     - Border: 2px solid red secondary dark, #CD2026
     - Error text: Mobile Body Bold, #CD2026
4. Create UI for the following field-level errors below the specified field: _(Note: these field-level errors will only appear next to fields that are already marked as *Required)_
     - To: "To is required"
     - Subject: "Subject is required"
     - Subject line: "Subject line is required". **This error only applies when 'General' is the Subject**
     - Message: "The message cannot be blank"
5. The field-level errors should appear when any of the following occur:
     - A user taps into a required input field and leaves the field without completing it
     - A user tries to send the form without interacting with a required field. In this case, the error message displays when "Send" is selected
6. A field-level error should disappear when any of the following occur:
     - For dropdown fields: user makes a selection from the dropdown
     - For input fields: user begins typing into the field
     - A user hits "Cancel" to exit the form
7. Clear all field errors if the user changes the Subject from "General" to another option 

## Designs
No designs for the field error UI. Refer to Edit Address form for a similar UX/UI. 
Compose message screen w/o errors: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364867

## Discovery ticket / documentation
https://docs.google.com/document/d/1LUBg1a0dEjQb4aKXimWYEq9DXNQOe35Etq8MzroAuJ4/edit?ts=6065f684#
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17044

## Accessibility Implementation Guidelines

**Error state:**
Formfield: “{label}. error - {Validation text}.”
Formfield/Message: “{label, hint message}. error - {Validation text}.”
Dropdown:“{label}. error - {Validation text}.”
Dropdown/Message“{label, hint message}. error - {Validation text}.”

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Context for AC #7:

If we change subject to "General", subject line becomes a required field. Then, if we make Subject Line trigger the field error, and we change Subject to something other than "General", then Subject Line's field error still persists even though it isn't required anymore. 

Implementing AC #7 as a workaround.

![Screen Shot 2021-04-13 at 1.43.20 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ceb34dec-835c-42d7-b2ed-6ddebffb7a9c)

**Comment by digitalken** [comment]
PASS 4/14/2021 - Looks good on iOS and Android, but small bug logged on Android when leaving To: and Subject: fields unfilled unchosen when leaving the field.  Tracked the bug, so closing.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23273
