### ISSUE TITLE
[Bug] Ch31 - Authenticated - Veteran Information prefill anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#22675]
## What happened?
On Staging **[Apply for Veteran Readiness and Employment with VA Form 28-1900](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction)** form [authenticated flow]:
- **Veteran Information** [personal-info] page: Information was not prefilled
- **Review** page: Veteran Information sub-section was repeated, with 2nd one editable.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vets.gov.user+4@gmail.com` (Alfredo)

## Steps to Reproduce
- URL: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction
- Test User _(if applicable)_:  `vets.gov.user+1@gmail.com` (Alfredo)
- Advance to **Veteran Information** [personal-info] form-page after signing-in.
- Observe that input-form is displayed, instead of prefilled info.
- Advance to **Review** page, completing **required fields** w/ dummy-values and clicking **Continue** on the way.
- Click to expand **Veteran Information** section.
- Observe that **Veteran Information** sub-section is repeated.  1st section [apparently prefilled] is not editable, while 2nd [showing inputted values] is.

#### Veteran Information [personal-info] page input-form
![bug-step-1a-info-not-prefilled-signed-in](https://user-images.githubusercontent.com/587583/113646965-be503b80-963e-11eb-84cf-44fbf90a386c.png)
#### Review page
![bug-authd-review-vet-info-section](https://user-images.githubusercontent.com/587583/113792757-86f39480-96fb-11eb-949f-17bbbdbc525d.png)

#### Staging /v0/user API-response [see prefill available & all Veteran-info data present]
![xhr-step-1a-info-prefilled-signed-in](https://user-images.githubusercontent.com/587583/113647712-30755000-9640-11eb-9df6-acff02e7f16b.png)

## Desired behavior
- [ ] Veteran-info should be prefilled, instead of displaying input-form:
![specs-step-1a-info-prefilled-signed-in](https://user-images.githubusercontent.com/587583/113646984-cad49400-963e-11eb-967f-45d04ab350b2.png)
- [ ] Review page Veteran Info section should not be repeated.

## Acceptance Criteria
[see **Desired behavior** above]
- [ ] PR: Review page with accordions, there is duplicate content
- [ ] PR: update yml profile mapping

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by micahchiang** [comment]
Some thoughts for planning today:
- Removing [this line](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vre/28-1900/config/form.js#L52) from our form config should get rid of the extra section on review
- I'm not sure the above will address the second part of the issue, which is that our form isn't getting properly prefilled with veteran data. I think name and dob need to be added to [this file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/form_profile_mappings/28-1900.yml)? Not sure though

**Comment by micahchiang** [comment]
Looking into this now. Just noticed the last screenshot with the static veteran information page. That mockup is slightly out of date, as we've temporarily moved away from that pattern due to some inherent issues it has with save-in-progress. Authenticated users will instead have their information prefilled into standard form fields.
