### ISSUE TITLE
Attach file to form (4 of 6)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22676]
## User Story
As a user, I want to add a file to my message and view it as part of the form. 

## Acceptance Criteria
1. Selecting "Attach" from the Attachments page routes to the **Compose a Message** form page
2. When the **Compose a Message** form loads, display a "preview" of that file in the Attachments section of the form
     - Leverage the form attachments CC #226103
     - The "preview" should include the file name + size, and a "Remove" button (routing not needed for this story)
3. When 4 attachments have been added to the form, hide the "Add files" button from the form page UI

## Designs
Example w/ 2 files added: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449234242
Example w/ 4 files added and no large button: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449234239

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/21/2021 - Looks good on iOS and Android.  Two bugs were logged against the common component for file size missing and Android formatting.  Closing this story.
