### ISSUE TITLE
Schedule VistA batch load jobs hourly

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#22673]
Per discussion with Josh F. and team, they will be able to run VistA bulk registrations every hour between 6a - 7p ET on weekdays. When we are comfortable with data quality and job stability on our end, we should schedule serialization and SFTP uploads on an hourly basis and notify Josh F. and team.

**Comment by patrickvinograd** [comment]
We want to be careful to avoid race conditions with batching records and submitting them to ES - not that duplicate submissions are the end of the world but they introduce noise and confusion. 

The current logic for batching and submitting via rake task is:
* Do a mass update_all on records with state=received and batch_id= nil, assigning them a batch_id. Now that they have a batch_id, they won't get caught up in a subsequent batch.
* Iterate through all records in batch_id, write CSV, submit to ES.
* If successful, do mass update_all to update state to enrollment_pending.
* If failed, then there is a second rake task to write the CSV and submit out of band, and a third rake task to update the state to enrollment_pending once confirmed received by ES team.

The way I think this should be structured as scheduled workers is:

* `ScheduledBatchWorker` - does mass update_all of records with state = received and batch_id = nil, assigning them a batch_id. Then kicks off a second Worker EnrollmentUploadWorker, passing it the batch_id as a parameter.
* `EnrollmentUploadWorker` performs the CSV generation and upload, and if successful, updates the state of the batch to enrollment_pending.

ScheduledBatchWorker is *not* retryable - if it fails, then it leaves the batch_id as nil and those records get caught in the next attempt a little while later.

EnrollmentUploadWorker is retryable, in case the connection to ES SFTP is temporarily down. 

The logic currently in EnrollmentProcessor can either be copy/pasted or refactored to be usable from these workers.

Also we will probably want a rake task that summarizes states by batch_id, so we can see any outliers like a batch from a week ago that is still in `received` state. Maybe that's a separate ticket, and it might prompt the need for an additional DB index on `state+batch_id` columns.

**Comment by batemapf** [comment]
Safe to assume that failures of the proposed ScheduledBatchWorker and EnrollmentUploadWorker workers would be surfaced via Sentry? Just thinking about how to (passively) keep an eye on this thing a week or two from now.

**Comment by patrickvinograd** [comment]
Yes, absolutely.

**Comment by patrickvinograd** [comment]
I have a PR in flight for this but might need to hand it off

**Comment by batemapf** [comment]
@kreek If this needs to be handed off, can you pick up?
