### ISSUE TITLE
Error | Duplicate file

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22679]
## User story
As a user, I want to know when I cannot upload an attachment to my message because its a duplicate, and I've already uploaded it to the form.
 
## Acceptance Criteria
1. Create UI for an error state when a file cannot be added to the form page because it is a duplicate file that has already been uploaded to the form
     - No API error - this will be flagged on the front-end
     - Use the URI to flag this error
2. This error state displays on the Attachments page (#20139). It appears after a user has selected a file from their device's camera, photo gallery, or camera roll
3. Pull in mobile alert CC 
     - Left border: #CD2026
     - This alert appears at the top of the page, below the top nav bar
4. Copy: "File already uploaded. Please select a different file."
     - Copy is unbolded
5. This error state persists until the user navigates away from the page

## Designs
Similar error state:
![Screen Shot 2021-04-05 at 10.07.12 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/cf19686d-96a2-460b-8116-39527d004af1)

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/22/2021 - Works good on iOS and Android.  Closing.
