### ISSUE TITLE
Remove attachment from the form (6 of 6)

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22671]
## User story
As a user, I want the ability to remove attachments from my message before I send it.

## Acceptance Criteria
1. From the Remove Attachment confirmation screen (#20815), selecting the "Yes, remove attachment" large button will delete the attachment from the user's message
2. Return the user to the message form page
     - The deleted attachment should no longer be visible in the Attachments section of the form

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/21/2021 - Looks good on iOS and Android.  Closing.
