### ISSUE TITLE
Submit data to VEText

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#22674]
As discussed in #22672, the last stop for SLA submissions is a table in CDW maintained by VEText. This should only occur when we are certain that the SLA submission has successfully been processed by the VistA bulk registration process or by HEC staff. Certainty will be based on the existence of an ICN and an MPI lookup that shows that ICN is associated with the facility that was indicated on the SLA submission. 

Note: this does not necessarily mean that the VistA bulk registration job did anything to create/alter a VistA record. It is possible, even probable, that an ICN already existed and record already existed in the VistA instance of the facility selected on the SLA submission. This would occur when a person applied for VHA care in the past but never enrolled; or enrolled but never sought care; or enrolled and received care, but mistakenly submitted an SLA form.

In addition to the existing Keep Me Informed attributes already being sent to VEText from vets-api, the SLA data that should be sent to VEText must include:

streetAddress
city
state
applicantType
privacyAgreementAccepted
smsAcknowledgement
birthSex
lastBranchOfService
serviceDateRange
characterOfService
enhancedEligibility

For testing, the VEText staging server is configured in the vets-api staging environment.

**Comment by stephenBarrs** [comment]
Submissions to VeText will occur periodically by kicking off the `expandedSubmissionJob` job, probably through a schedule configured in `sidekiq_scheduler.yml.   `expandedSubmissionJob` will query the database for records with state=`enrollment_pending` (indicative that data has been sent to enrollment) and process x number of records found.  

There will also need to be a temporary run of `expandedSubmissionJob` in batches and possibly at low peak traffic times to process the existing records.  

The following events may occur for each record when this job runs:

### Happy Path
* user is found in MVI and MVI locations match preferred_facility entered in form (happy path): DB state updated to `enrollment_complete`, Data will be sent to VeText and DB state updated to `registered`

### Delayed Submissions (occur when enrollment has not been completed) 
(these records will be picked up and retried on the next job run.  We will probably need a way to find any records that are not found in MVI for an extended period of time)
* user is found in MVI and MVI locations do not match preferred_facility entered in form: Data will not be sent to VeText and exception will be raised
* user is not found in MVI : Data will not be sent to VeText and exception will be raised
* user and facility are found in MVI but send to VeText fails: This will result in DB state=`enrollment_complete` **ToDo:** The existing VetextService class is used to send expanded data - what does this Class do when error occurs?

### Error state
(records with state=`enrollment_out_of_band` require manual intervention) 
* no `preferred_facility` is present in form data: Data will not be sent to VeText, an exception will be raised and DB state will be updated to `enrollment_out_of_band` which is indicative that manual intervention will be required for this record.

**Comment by stephenBarrs** [comment]
Questions for @batemapf :  

how often do you suggest the send to VeText job run?  the enrollment job is executing every 15 minutes.  I am not sure we need to send to VeText that often, but not sure what the appropriate timeframe would be. 

Confirming that we do NOT want to send an email to the user when they are registered in VistA?  They do get an email when they submit the form.

**Comment by batemapf** [comment]
> how often do you suggest the send to VeText job run? the enrollment job is executing every 15 minutes. I am not sure we need to send to VeText that often, but not sure what the appropriate timeframe would be.

I'd like to keep the send to VEText job in sync with the enrollment service upload job (every 15 min as you noted). To give the enrollment job a fighting chance at finishing, I'd set the cron on the VEText job to 30 min past every hour (i.e. `30 * * * *`)

>Confirming that we do NOT want to send an email to the user when they are registered in VistA? They do get an email when they submit the form.

Confirmed. A happy path user will receive: (1) a confirmation email upon submission; and (2) any future KMI newsletters. A less happy path user will receive: (1) a confirmation email upon submission; (2) any future KMI newsletters; and (3) possibly some kind of follow up email asking them to reach out to their selected facility after a certain number of times failing to find them in MPI (this is a future feature, not looking to include it in this change set).
