### ISSUE TITLE
Error | Sum of files exceeds limit

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22678]
## User story
As a user, I want to know when I cannot upload an attachment to my message because when combined with the other file(s) I've uploaded, the sum of all files exceeds the limit. 
 
## Acceptance Criteria
1. Create UI for an error state when a file cannot be added to the form page because the total of that file **and** the files that have already been attached to the message >6 MB
     - doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx
2. This error state displays on the Attachments page (#20139). It appears after a user has selected a file from their device's camera, photo gallery, or camera roll
     - This error state should only appear if at least 1 other file has successfully been added to the form page. There is a separate error state that handles when a single file exceeds the individual limit of 3MB
3. Pull in mobile alert CC 
     - Left border: #CD2026
     - This alert appears at the top of the page, below the top nav bar
4. Copy: "The sum of the file(s) you are trying to upload exceeds the 6 MB limit. Please reduce the file(s) size and try again.."
     - Copy is unbolded
5. This error state persists until the user navigates away from the page

## Designs
Similar error state: 
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449230096

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/22/2021 - Good on iOS and Android.  Closing.
