### ISSUE TITLE
Discover ICN for SAVE LIVES Act records post-VistA load before sending to VEText

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#22672]
The final destination for a submission for VA vaccination under SAVE LIVES Act (SLA) authority is a VEText maintained table in CDW. Pushing SLA data into CDW via VEText will enable other teams, including VEText, to access submission attributes that are not included in the patient record when it is created (e.g. they "type" of SLA eligibility, like spouse or caregiver). For example, facilities can use this data via the VSSC's COVID-19 Vaccine Outreach Tool to target communications for different eligibility groups.

One key piece of information that we would like to include when sending the SLA submission data over to VEText is the ICN associated with the submission. This unique value enables data to be joined with lots of other data sources in CDW. We expect that almost every (>= 99%) of records received via VA.gov and sent for VistA bulk registration [1]. This would happen in one of two ways:

(1) the person submitting a SLA form on VA.gov already has an ICN due to a prior interaction with VHA/VA; or
(2) the person submitting a SLA form on VA.gov has a new ICN created on their behalf during the VistA bulk registration job.

We are not doing ICN look ups prior to sending records for VistA bulk registration (which would identify SLA submissions with an existing ICN). Nor are we getting reliable feedback from the VistA bulk registration process that would indicate an ICN associated with a particular SLA submission.

Thus, the problem to be solved is **how might we discover ICNs for a SLA submission for purposes of appending it to the submission before/during sending the submission to VEText?**

--- 

[1] Any SLA submission that cannot be tied to an ICN would almost certainly be due to a data validation issue during the VistA bulk registration process.

**Comment by patrickvinograd** [comment]
Do we also want to do a match of their preferred facility with the list of facility correlations in MPI? Use case:
* Veteran was registered at VA in San Diego x years ago.
* Veteran used SLA/KMI tool and now resides in Vermont.
* We scan for presence in MPI, but do so before enrollment has processed them to add this facility.
* We ignore facility, look them up and see they have an ICN, and pass them on to VEText for outreach but they are still only affiliated with San Diego.

Does this cause any problems for vetext? For the facility doing follow-up outreach? I don't know.
