### ISSUE TITLE
[bug] - Facility selection is not happening for all submissions

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#22683]
Our 4/5 VistA bulk registration load included about 200 records with no facility included in the submission. A facility should always be included in the submission so long as a valid US zip code is entered [1]. The expected behavior is either:

(1) User enters zip code on /contact-information
(2) User sees list of five proximate facilities on /vaccine-location
(3) User selects a facility from list
(4) User submits form
(5) Selected facility is included in submission and sent to the VistA bulk registration process

**OR**

(1) User enters zip code on /contact-information
(2) User sees list of five proximate facilities on /vaccine-location
(3) User does not select a facility from list
(4) User submits form
(5) Nearest facility is selected for the user and appended to the submission prior to VistA bulk registration process [2]

We heard the following feedback from the VistA bulk registration team regarding this issue:

>It’s over 200, some are null and some are literal empty string “”, not sure why the diff.
>I don’t think this part is working, it does allow you to skip thru without selecting one but I think defaulting to the first one doesn’t make its way to the file.

---
[1] According to vets-api data, there have only been 110 instances where facilities where not recommend to the user. In this case, it is _not_ expected that the submission would include a facility preference.
[2] This step may/could take place before #4 in the front end.

**Comment by stephenBarrs** [comment]
[This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16623) updated the facility data sent to the backend in the Payload to ensure that either the facilityID or a blank string '' is sent.  If the user selects a facility, the facilityID is sent.  If there are no facilities found or the user does not select a facility, a blank string is sent.  Prior to #16623 I cannot recall what data was sent if no facility was selected, but suspect that the `preferredFacility` field would just not be included in the payload.  

I suspect that some of the data anomalies are a result of `preferredFacility` not being included in the payload when a facility was not selected.  

[This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16617) will ensure that if a list of facilities is presented to the user, one must be selected.  It makes sense to merge this PR and not spend time ensuring that the first Facility in the list is sent if none are selected.  

We need to confirm what action should occur on the BE when `preferredFacility` is a blank string.

**Comment by patrickvinograd** [comment]
There is a backend process that remediated the issue with users not picking a facility even when some where suggested. But it needs to be run as a rake task before generating the CSV. 

I thought the second of the PRs that Stephen mentioned had been merged, and so didn't run the facility fix-up task before our second upload, and so those entries were not resolved correctly.

I can run the fix-up task before our next upload (number 3); it will not retroactively fix the entries from upload number 2, but I could probably re-generate a CSV for the affected entries from upload 2 and manually upload it.

**Comment by patrickvinograd** [comment]
We can and should run the facility resolver lookup as part of the bulk upload process. 
Note there will still be some entries with zips that don't resolve to a facility because of things like PO Box only zip codes.
