### ISSUE TITLE
Updates to COVID-19 vaccine sign-up boxes

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#22689]
# Update sign-up component on vaccine mini-hub

[header] **Sign up to get a COVID-19 vaccine at VA**

[subhead 1] **Enrolled in VA health care or currently receiving care through VA?**
Sign up to tell us if you plan to get a COVID-19 vaccine. Your local VA health facility may use this information to determine when to contact you once your risk group becomes eligible.

[subhead 2] **Not enrolled, but need a COVID-19 vaccine?**
Sign up to tell us if you want to get a vaccine at VA. If you’re a Veteran, spouse, caregiver, or CHAMPVA recipient, we'll contact you when we have a vaccine for you. At this time, we don't know when that will be.

[button] **Sign up to get a COVID-19 vaccine**

# Update sign-up component on KMI landing page

[header] **What you should know about signing up**

By sharing your plans for getting a vaccine, you help us better plan our efforts. This helps us do the most good with our limited vaccine supply.

[subhead 1] **If you're enrolled in VA health care or currently receiving care through VA**

Sign up to tell us if you plan to get a COVID-19 vaccine. We continue to contact Veterans as they become eligible to get a COVID-19 vaccine. We base eligibility on VA and [CDC COVID-19 risk criteria.](https://www.cdc.gov/vaccines/covid-19/phased-implementation.html) Within each risk group, we may first contact Veterans who sign up here and tell us that they plan to get a vaccine. But we’ll still contact every eligible Veteran in each risk group to ask if they want to get a vaccine.

[subhead 2] **If you're not enrolled, but need a COVID-19 vaccine**

Sign up to tell us if you want to get a vaccine at VA. If you’re a Veteran, spouse, caregiver, or CHAMPVA recipient, we'll contact you when we have a vaccine for you. At this time, we don't know when that will be.

**Note:** Your employer, pharmacy, health care provider’s office, or local public health officials may offer you a COVID-19 vaccine. We encourage you to take the first opportunity you have to get a vaccine at the most convenient location for you. The Centers for Disease Control and Prevention’s (CDC) online vaccine finder tool can help you find COVID-19 vaccines near you.

[Find COVID-19 vaccines near you with the CDC’s vaccine finder](https://www.cdc.gov/vaccines/covid-19/reporting/vaccinefinder/about.html)

**Comment by DanielleThierryUSDSVA** [comment]
@lalexanderson-dsva @batemapf @artsymartha68 Here's a ticket for updating sign-up components for KMI. Lauren and I were talking about the KMI landing page and want to make sure that's updated too to align. I've reworked that one a bit, so let me know what you think!

**Comment by RLHecht** [comment]
Old ticket. Closing.
