### ISSUE TITLE
STEM AD: Update 'View Details' styling to use an action link 

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22680]
As a developer, I need to update the view details styling on the claim status cards so that it is consistent with DEPO patterns and practices.

## Assumptions:
1. This work does not require a feature or prod flag.
2. This is for all card types, not just 10203 denials.

## Acceptance Criteria
1. The ‘View details’ button is styled as a **_Secondary Action Link_**. (See SA2)

## Supporting Artifacts:
1. Originating issue: #22580
2. [Design System Reference](https://design.va.gov/components/action-links)
3. Login to claims page here: https://staging.va.gov/claim-or-appeal-status/
4. Cards are found here: https://staging.va.gov/track-claims/your-claims

**Comment by dmccurdybah** [comment]
![image.png](https://images.zenhubusercontent.com/5bb388cc38a73929698456e2/e498f8f2-f0fe-4595-99b7-369bf30cabe9)

Secondary Action Link class doesn't seem to be in available in build yet.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16762

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-04-13 at 1.18.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/08f0af4f-1938-40d2-b25d-b0b6bca636bd)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah this is in staging. User 220 will be the one needed to check.

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me

**Comment by watersemma** [comment]
UX Review 2/2: This looks good to me!

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16762

**Comment by sonntag-adam** [comment]
Closing story.

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1790)
