### ISSUE TITLE
VRRAP Introduction page URL not found

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#22692]
When attempting to access the VRRAP introduction page on staging, the user is met with a "Sorry — we can’t find that page" message as shown in the Actual behavior below.

## Expected behavior
User is able to access the login page at https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction

![Screen Shot 2021-04-06 at 10.45.03 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/1b8eccc8-1a2a-4635-8c67-60d9f13a06d3)

## Actual behavior
User receives the following error:
![Screen Shot 2021-04-06 at 10.41.11 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/9f39532e-0056-4d34-a70d-3220187be118)

**Comment by dmccurdybah** [comment]
I checked all config and couldn't find any issues.  Locally everything worked fine but staging wasn't working correctly.

Now staging is working, so the issue must have been an environmental issue outside of our code and resolved itself.

**Comment by sonntag-adam** [comment]
This is confirmed working in staging now.
