### ISSUE TITLE
Internal Search QA | Make sure the best page is recommended for valuable keywords on internal search.

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2269]
@steve-gov commented on [Wed Nov 07 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14923)

Make sure that the most frequently performed internal searches are directing to the most valuable content.

Here are the top 100 internal searches on va.gov in the last fiscal quarter of 2018: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Search/va-gov-internal-searches-q4-2018.xlsx

Perform an internal search against each one of those keywords, and make sure the best page is coming up as a "Best Bet" or otherwise as a top result. 

~~If not, edit the appropriate file in https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Search/best-bets, and upload to search.gov.~~

Just add the Best Bet directly to the interface at https://search.usa.gov/sites/7378/best_bets_texts. That data is newer than anything in this repo.

---

@steve-gov commented on [Thu Nov 15 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14923#issuecomment-439192165)

First week of va.gov internal searches here (top 1000): https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Search/va_2018-11-11_2018-11-17.csv

---

@WinishaSmith commented on [Tue Dec 11 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14923#issuecomment-446361803)

@steve-gov Where are you receiving the list of top internal searches from? I'll be maintaining the best bets and I'm wondering how I'll be able to get these going forward.

---

@steve-gov commented on [Tue Dec 11 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14923#issuecomment-446371057)

The historical files I got from the Site Search section of the va.gov property in Google Analytics.

But ignore any of the files in the /product/search/best-bets repo, they were good for seeding but are now out of date.

Couple ways to get the current top searches:
- Run a query at https://search.usa.gov/sites/7378/queries/new and just copy/ paste the table as you need to
- Download one of the reports at the bottom of this page: https://search.usa.gov/sites/7378/monthly_reports

That last one is what I'd been adding to the vetsgov-analytics slack channel.

Let me know if you need anything else!

---

@batemapf commented on [Mon Sep 23 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14923#issuecomment-534148252)

Doing some repo cleanup. @chrisj-usds @Karak888 I believe this is one for Global UX. If so, would you please assign yourselves and, if you are migrating issues to `va.gov-team`, please take care of this one?

**Comment by Karak888** [comment]
@chrisj-usds @batemapf I will include this in our discovery ticket we have on our board.  thanks

**Comment by tlei123** [comment]
@Justin-Pickett @Karak888 , if this does require manual UI testing on Staging, please add the **vsa-qa** label and assign this to me at least 1 sprint before testing-day.

Thanks much!  :)

**Comment by Karak888** [comment]
I think we are good to close this one for now as we are already working on that. @tlei123
