### ISSUE TITLE
Clean up "dashboard" references in code throughout repo

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2270]
@BBarone1 commented on [Fri Sep 28 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13798)

## Background
The dashboard product on Vets.gov is becoming "My VA" on va.gov. As a result, we'll want to change references to this product as "dashboard"  to My VA in our code and in our analytics.

## Definition of done
- [ ] Collect all references to dashboard throughout the code and analytics
- [ ] Ensure no unwanted side-effects of making the changes
- [ ] Update "dashboard" references to "my va"

---

@ricetj commented on [Fri May 17 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13798#issuecomment-493538712)

When we talk about dashboard 2.0. We can talk about this again.

---

@batemapf commented on [Mon Sep 23 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13798#issuecomment-534147313)

I think this one is yours, @lkoenigsberg?

**Comment by Justin-Pickett** [comment]
We'll revisit later. We'll keep it in the "icebox" for now.

**Comment by bradl3yC** [comment]
@nedierecel @jonwehausen is this still needed for analytics? Is analytics aware of this change request?
