### ISSUE TITLE
Update icons on navigation bar

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22708]
## Acceptance Criteria
1. Update the buttons on the bottom navigation bar with the new .svgs
     - Include selected/unselected states for Home/Claims/Health/Profile

Note: this is a known change to the recent nav bar update the FE team did as part of #21038.

## Assets
Nav bar .svgs: https://drive.google.com/drive/folders/1MQJxqFhiW8Bcj_-5g_ZCyx75oCQUjgrf?usp=sharing

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS - 4/15/2021 - Icons have been added and appear correct.  Logged bug on icon / text alignment / spacing but closing this story.

Bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/23291
