### ISSUE TITLE
Weekend Appts Do Not Display for Primary Care or Specialty Care clinics

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#22711]
Weekends (Sat/Sunday) appointments do not display in VAOS for clinics that are configured in Staging for direct scheduling.  

For example CHY Pharmacy has appointments on the weekends but those are not seen in VAOS front end (they are returned by back end).  

VAOS only shows Monday through Friday.  

## Expected Results

- [ ] Given `va_online_scheduling_cheetah` flag in ON, When primary or specialty care direct scheduling flow, Then show all days of the week (Sun-Sat) on calendar by default for all months

**Comment by laurenernest** [comment]
Is this happening when the cheetah toggle is turned on?

**Comment by marcynadeau** [comment]
@laurenernest Yes this is happening in Staging right now.  I asked Lance "For weekend direct scheduling is that for all care types or just COVID?  Just need to know what to test".  
Lance replied COVID only
