### ISSUE TITLE
Move bulk of VHIE Q&As over to Resources and Support article

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#22716]
## User story

As a Veteran, I want quick access to my health tools. I also need to understand how VA is sharing my health information with providers.

## Issue description

As part of our refresh of VA health tool landing pages, we'd like to focus the ["Get your VA medical records online"](https://www.va.gov/health-care/get-medical-records/) tool landing page more on VA Blue Button, and move the VHIE informational content over into Resources and Support.

**Notes:**
 - We'll be doing other work on this health tool landing page, but moving VHIE can be its own lift.
- Content for this page is currently housed in react widgets due to the 2 different states for Cerner. We'll be working to change that, but for now, that's the current state. So when we're ready to remove the existing content from this page and link over to R&S, we'll need to request PW help.
- As part of this, I'd like to check on the italicized part of this paragraph: <br> "VHIE helps improve continuity of your care, reduce test duplication, and avoid clinical error. That's because _you can see all your health care providers from different practices or networks in one place_. Our secure system also eliminates the need to send paper medical records by mail, and to carry your records to appointments with community providers." <br> I know Anne worked with the SMEs to get this reviewed, but this seems slightly off to me in that VHIE is about *all of your providers* having your info, not about *you* seeing all your providers in one place.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jenniferlee-dsva - thanks for volunteering to take this one! Let me know if you have any questions about the ticket. I'm also working with content team on updating intros and other content on this and other health tool landing pages to match sitewide content standards that we're setting (shorter intro paragraphs, accordions for many of the Qs, etc.), so let's just keep each other looped into changes on this page.

Tagging @mpeterz for awareness as well. Thanks!

**Comment by RLHecht** [comment]
Closing this ticket as a newer one was created to do this work in conjunction with other edits to the medical records page. The new ticket is #41792.
