### ISSUE TITLE
Coordinate with BDD SMEs  on RAD Date

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#22710]
## Issue Description
Get clarification on Release from Active Duty flow and decisions

---
## Tasks
- [x] Update flow diagram, send to SMEs, get confirmation that flow is correct.

## Acceptance Criteria
- [x] Written confirmation of flow logic.
---

**Comment by kevinstachura** [comment]
I emailed our BDD SMEs and we had a follow up meeting with them about this issue. The written confirmation was from Barry Cooper:

>I wanted to clarify one point from the below e-mail.  Otherwise, looks good to me. 

>If it's 180 days out, we show a validation error that says "Your separation date must be before 180 days from today"

 >For example, let’s say a SM puts in a BDD claim today and enters a discharge date that is exactly 180 days from today, then, they meet the BDD requirements.  If it is 181 or more, then they cannot submit a VA claim until they hit day 180.

This has been noted and otherwise, our understanding of the process was indeed correct.
