### ISSUE TITLE
[Bug] Ch31 - Review page - Add'l Info section - Update anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#22724]
## What happened?
On Staging **[Apply for Veteran Readiness and Employment with VA Form 28-1900](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction)** form, Review page, editing **Additional Information** section's **Are you moving...** from Yes to **No** rendered **Update...** button non-responsive.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: n/a

## Steps to Reproduce
- URL: https://staging.va.gov/careers-employment/vocational-rehabilitation/apply/introduction
- Advance to **Veteran Information > Additional Information** form-page, completing **required fields** as needed and clicking **Continue** button on the way there. 
- For **Are you moving...**, choose **Yes** and complete **required address-fields**.
- Advance to **Review** page, completing **required fields** as needed and clicking **Continue** button on the way there. 
- Change **Additional Information > Are you moving...** to **No**.
- Observe that **Update...** button is not responding.

### Video capture [Win Chrome example]
https://user-images.githubusercontent.com/587583/113753637-2d6f7380-96c3-11eb-8113-1d2a7bc90cd5.mp4

## Desired behavior
After changing **Review** page **Add'l Info** section **Are you moving...** from **Yes** to **No**, the **Update...** button should work, with updated selection saved & displayed afterward.

## Acceptance Criteria
- [ ] Address `ui:required` as needed
- [ ] A PR has been requested for merging

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by micahchiang** [comment]
Leaving some thoughts here for planning today:
- I took a quick look at this, and I think the `ui:required` callback needs to be fiddled with in order to fix this issue.
