### ISSUE TITLE
Content Request from Find a Form Team

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#22726]
## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [x] Determine if this request is for:
     - [x] Content Only      
     - [ ] Public Website Engineering Support      
     - [ ] Both (Content + PW Eng Spt)   
- [x] Post a link to this issue in the appropriate channel: For Engineering only requests: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @ncksllvn and @kelsonic. Content only support: [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) in Slack, tag @RLHecht.  In situations where both are needed post to Public Websites and in Slack tag @brianalloyd, @ncksllvn, @kelsonic and @RLHecht for awareness.  
- [ ] If noted in the guidance below, please schedule any relevant meetings.

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * Yes, this is for content creation and editing for the [Find a Form](https://www.va.gov/find-forms/) detail pages (an example [detail page here](https://www.va.gov/find-forms/about-form-10-10ez/)
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/State-of-the-Product.md)
   * [Publishing and Editing a Forms Detail page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/form-detail-landing-pages/publish-edit-delete-details-page.md)
  
---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content

- [X] **Updates to **the content** in an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      *  [Find a Form](https://www.va.gov/find-forms/) detail pages (an example [detail page here](https://www.va.gov/find-forms/about-form-10-10ez/))
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * Yes, writing and/or copyediting of "when to use this form" description text and when feasible addition of Related Forms and/or Helpful Links (which will need to be approved by VA Form SMEs)

### Recommended Approach
 - We have determined that the Top 100 most searched forms are the ideal scope for Details Pages.  Approximately 40 details pages are already created/published.   For this effort, we will focus on the next 60. (NOTE: Going forward, only new Veteran-facing forms – and select non-Veteran facing forms -- averaging more than 200 Find a Form searches a month will receive Details page treatment)
 - There are three content batches in the attached Word docs, organized by VBA and VHA (and their program offices).   These can be tackled by priority in sequence -- e.g. Batch 1, then 2, then 3.
- For each, we need:
   - At a minimum, the descriptive text for "When to Use"
   - If obvious, please also provide "Related Forms" and/or "Helpful Links"
   - More details about [what to publish in a Form Details page is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/form-detail-landing-pages/Publishing%20a%20new%20form%20detail%20landing%20page.pdf)

### Desired/target implementation date

- Batch 1 - by May 24  (for SME Review

[VA.gov_Find_a_Form_Content_Batch-1_VBA.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6400288/VA.gov_Find_a_Form_Content_Batch-1_VBA.docx)

- Batch 2 - by June 24 (for SME review)

[VA.gov_Find_a_Form_Content_Batch 2_VHA.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6400291/VA.gov_Find_a_Form_Content_Batch.2_VHA.docx)

- Batch 3 - by July 26 (for SME review)

[VA.gov_FaF_Content_Update_Batch-3_VBA.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6400294/VA.gov_FaF_Content_Update_Batch-3_VBA.docx)

When each batch is delivered by Content, the Product team will work to get SME feedback/approvals and will be responsible for entering/publishing the final approved content into the CMS.

###To Be Determined
- TBD
- TBD
-
---

### About your team

- Team name: Decision Tools
- DEPO product owner: John Hashimoto
- Product manager: Marci McGuire
- Designer: Cassandra Allen
- FE engineer: Zach Morel
- Product/team Slack channel: #vsa-decision-tools

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by johnhashva** [comment]
Recapping our plans, based on 4/16 convo:

- Product team will re-organize the content deck "batches" to include Admin program info (e.g., VBA-Loans, Education, etc.) and suggestions for Helpful links (based on what Jen previously created).   
- We will then re-organize each copy deck/batch based on Admin/Program so that we get "all at once" SME review

**Comment by lunascoop** [comment]
[VA.gov_Find_a_Form_Content_Batch-1_VBA.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6511283/VA.gov_Find_a_Form_Content_Batch-1_VBA.docx)
@RLHecht this is ready for review

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's Selina's first batch with my edits as well. Can you take a look and if they're good we can get them into Drupal?
[VA.gov_Find_a_Form_Content_Batch-1_VBA.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6594285/VA.gov_Find_a_Form_Content_Batch-1_VBA.docx)

**Comment by johnhashva** [comment]
@RLHecht great to see this progress.   Next step is actually: I need to get your final approved copy reviewed by the VA forms stakeholders (wish we could bypass that process, but Jen is of the opinion it is necessary).   @bethpotts you agree?

**Comment by RLHecht** [comment]
@johnhashva Forgot about that part! Yep, makes sense to send to the stakeholders once Beth signs off on it.

**Comment by bethpottsVADEPO** [comment]
@johnhashva @RLHecht @lunascoop I'm looking at this today so I'll be able to get it back to you either eod or first thing Monday!

**Comment by bethpottsVADEPO** [comment]
[VA.gov_Find_a_Form_Content_Batch-1_VBA.bp.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6605089/VA.gov_Find_a_Form_Content_Batch-1_VBA.bp.docx)
@RLHecht @lunascoop Take a look at my edits to inform how you approach the next batch. Also, per my convo with Randi last week, I reviewed only the descriptions. I'm leaving the assessment of helpful links on that page to you two. Would you touch base with each other to double check those? Then hand off to @johnhashva and @MarciMcGuireGCIO.

For batch 2 descriptions, focus on:
- accuracy
- shorter descriptions that don't include eligibility or bullets with examples
- wording at the start of the description that sets expectations: "if you want to apply for X benefit" (not "if you want to receive X benefit"--which could imply that everyone gets it, all you have to do is apply)

**Comment by RLHecht** [comment]
@johnhashva @MarciMcGuireGCIO Here is the first batch finished with all our changes and edits. Selina and I went through the related links but also wanted to confirm that you were going to have the stakeholders review as well since they are more familiar with their forms and pages. 
[VA.gov_Find_a_Form_Content_Batch-1_VBA.6.7.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6610741/VA.gov_Find_a_Form_Content_Batch-1_VBA.6.7.21.docx)

**Comment by johnhashva** [comment]
Yes @RLHecht -- plan to have stakeholders to vet the description text and the related links too.

**Comment by MarciMcGuireGCIO** [comment]
Great; thank you @RLHecht !

**Comment by RLHecht** [comment]
Noting here that after discussing on the weekly Content and IA sync we will not do detail pages for non-VA forms (that begin with OF and SF). @lunascoop for the new batches you work on, you don't need to add descriptions for these. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Thank you for that update, @RLHecht

**Comment by lunascoop** [comment]
@RLHecht Batch #2 is ready for review.

[VA.gov_Find_a_Form_Content_Batch.2_VHA-SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6639036/VA.gov_Find_a_Form_Content_Batch.2_VHA-SC.docx)

**Comment by johnhashva** [comment]
@RLHecht + @lunascoop thank you both for Batch 1.   Noticed that there is no "Use Form < > if ..." description for 28-1900 (highlighted in Yellow in the doc) -- is there a reason for that one being the outlier?

**Comment by lunascoop** [comment]
@johnhashva form 28-1900 is listed twice in the doc. The first one is on the second row of the table. The one highlighted is a duplicate.

**Comment by johnhashva** [comment]
A-ha!  Thanks @lunascoop

**Comment by RLHecht** [comment]
@bethpottsVADEPO Batch 2 of the forms is ready for you. [https://app.zenhub.com/files/133843125/a143ebe3-8899-4801-b142-8fb50fbedfef/download](https://app.zenhub.com/files/133843125/a143ebe3-8899-4801-b142-8fb50fbedfef/download)

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO cc @johnhashva  - John has consolidated feedback & updates from the VA stakeholders in this Word doc for your final review. 
[VA.gov_Find_a_Form_Content_Batch-1_VBA._Consolidated_Changes.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6756085/VA.gov_Find_a_Form_Content_Batch-1_VBA._Consolidated_Changes.docx)

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO I'll be reviewing batch 1 stakeholder feedback by Wednesday. Will let you know if there's anything to push back on.

@lunascoop @RLHecht Can you take another pass at batch 2 for
- plain language (for example, "make changes to" rather than "modify")
- ensuring the right verb is used in all the first sentences: apply vs request
- VA.gov voice (and try to borrow language from our existing static content when possible--see below)

An example of where I drew from our existing content in this intro where we say, "installing ramps and widening doorways":
(from https://www.va.gov/housing-assistance/disability-housing-grants/)

Our voice:
These changes may include installing ramps and widening doorways so you can live more independently.

Rather than:
This may include adding ramping to your entrance paths and driveways, and other structural changes to improve accessibility throughout your home.

I slacked you the Word doc with my edits since zenhub isn't letting me upload it here to the ticket for some reason. I've edited the first 4 descriptions, but none of the others. Those are the ones you should revisit. 

Also, since I'm not reviewing the related links, please work together to make sure those are ready/questions resolved. If we need to get on a call to go over any of them, let me know, otherwise, I'm leaving them to you to resolve questions and decide what to feature there!

**Comment by lunascoop** [comment]
@RLHecht here's batch #2 ready for you review.
[Batch 2 Find a form.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6784309/Batch.2.Find.a.form.docx)

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO @johnhashva 
1/ **For Form 21-0538:** It looks like the stakeholder removed the description but I don't see a replacement. Would you run the one I just wrote past them and see if they approve (see attached Word doc)?

I also updated the name of the form in the appropriate column per the stakeholder feedback: Mandatory Verification of Dependents

2/ I see new content inserted for Form 26-4555. I edited that text. You'll see my tracked changes.

3/ I see new content inserted for Form 26-1880. I edited that text. Changes are tracked.

[https://app.zenhub.com/files/133843125/f9679f04-76f5-40b8-a1ab-6f2e227333ee/download](https://app.zenhub.com/files/133843125/f9679f04-76f5-40b8-a1ab-6f2e227333ee/download)

4/ Where did the teasers come from for the other information links? We should really shorten those. @lunascoop and @RLHecht can you work on that?

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO @johnhashva @lunascoop @RLHecht Wait! I see a typo I'm correcting and will re-upload the Word doc.

**Comment by bethpottsVADEPO** [comment]
OK, updated Word doc, both here and in my comment above. Apologies!:
[https://app.zenhub.com/files/133843125/91577e04-bd43-4426-a69b-6d6ed68f7888/download](https://app.zenhub.com/files/133843125/91577e04-bd43-4426-a69b-6d6ed68f7888/download)

**Comment by johnhashva** [comment]
@bethpotts sounds like I should wait for @lunascoop and @RLHecht to work in the edits to the other information links -- then I can then resend to the stakeholders to see/sign off on our final set of updates before I paste/publish all these in the CMS -- right?

**Comment by lunascoop** [comment]
@RLHecht I've reviewed the other information links for the doc @bethpottsVADEPO attached and they're ready for your review. 

[91577e04-bd43-4426-a69b-6d6ed68f7888.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6793014/91577e04-bd43-4426-a69b-6d6ed68f7888.docx)


@johnhashva @bethpottsVADEPO @MarciMcGuireGCIO I want to confirm that we aren't including information links to legacy pages. There's one listed for VA forms 26-4555 and 26-1880: **[About VA Home Loans](https://www.benefits.va.gov/homeloans/)**. I added a comment in the doc that recommends replacing it with our **[VA-backed Veterans home loans](https://www.va.gov/housing-assistance/home-loans/)** page instead. I updated the description for that as well.

**Comment by johnhashva** [comment]
good call, @lunascoop -- we should only link to modern pages as the source of truth.  TY.

**Comment by RLHecht** [comment]
@lunascoop I shortened up some of the related links and took out the legacy one you mentioned. I think that was everything I needed to address. Can you take another look and then accept the changes so John can send it to stakeholders? Thanks!
[91577e04-bd43-4426-a69b-6d6ed68f7888.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6802529/91577e04-bd43-4426-a69b-6d6ed68f7888.docx)

**Comment by lunascoop** [comment]
@johnhashva I have reviewed and accepted the changes. The doc is ready to send to stakeholders. 
[91577e04-bd43-4426-a69b-6d6ed68f7888 (1).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6809105/91577e04-bd43-4426-a69b-6d6ed68f7888.1.docx)

**Comment by johnhashva** [comment]
Thanks @lunascoop + @RLHecht + @bethpotts (with @MarciMcGuireGCIO FYSA).   Will send this back over to the VBA stakeholders for (hopefully) final review.   Then, I will add to the details pages via CMS.

**Comment by RLHecht** [comment]
@lunascoop Here's the second batch back to you. I updated a few of the related links and did some other tweaks. If you don't have any questions I think you can accept the changes and pass it back to John and Marci. [https://app.zenhub.com/files/133843125/84910afd-39f3-4fe5-8d8f-5088414e1c9c/download](https://app.zenhub.com/files/133843125/84910afd-39f3-4fe5-8d8f-5088414e1c9c/download)

**Comment by lunascoop** [comment]
@johnhashva @MarciMcGuireGCIO Here's a revised copy of batch #2. 
[84910afd-39f3-4fe5-8d8f-5088414e1c9c.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6840664/84910afd-39f3-4fe5-8d8f-5088414e1c9c.docx)

@RLHecht Here's batch #3 for review. 
[VA.gov_FaF_Content_Update_Batch-3_VBA_SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6840690/VA.gov_FaF_Content_Update_Batch-3_VBA_SC.docx)

**Comment by johnhashva** [comment]
Thanks @lunascoop -- I will send Batch #2 to the appropriate VA stakeholders for review/feedback.

**Comment by johnhashva** [comment]
@lunascoop (with @MarciMcGuireGCIO FYSA) -- just received one more (and I hope, final) round of tweaky feedback from the VBA stakeholders.  Hard to aggregate into one doc -- so here are both, with notes:

- Please see additional feedback for the 26 series form(s).

[VA.gov_Find_a_Form_Content_Batch-1_VBA_07132021- LGY.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6848553/VA.gov_Find_a_Form_Content_Batch-1_VBA_07132021-.LGY.docx)

- Please see additional feedback for the 28 series form(s).

[VA.gov_Find_a_Form_Content_Batch-1_VBA_07132021(AB edits 7.16.21).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6848560/VA.gov_Find_a_Form_Content_Batch-1_VBA_07132021.AB.edits.7.16.21.docx)

**Comment by RLHecht** [comment]
@bethpottsVADEPO Here's the third batch of forms ready for you.[https://app.zenhub.com/files/133843125/fff5c216-7c92-452d-b052-46ea9285105b/download](https://app.zenhub.com/files/133843125/fff5c216-7c92-452d-b052-46ea9285105b/download)

**Comment by johnhashva** [comment]
@lunascoop and @RLHecht -- just checking back to see if you've had a chance to review the hopefully last bit of feedback from the VA stakeholders for Batch 1 -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/22726#issuecomment-883389672.  Let us know once that's ready and I will paste these into the CMS for the relevant Details pages. (@MarciMcGuireGCIO FYSA)

**Comment by lunascoop** [comment]
@RLHecht can you review the changes made per the stakeholder feedback? I only attached my edits to the second doc in [#22726 (comment)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22726#issuecomment-883389672). The only change I saw in the "LGY" doc was that they added a link to the form in the first column. cc: @johnhashva 

[VA.gov_Find_a_Form_Content_Batch-1_reviewstakeholderedits.7.23.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6887911/VA.gov_Find_a_Form_Content_Batch-1_reviewstakeholderedits.7.23.21.docx)

**Comment by RLHecht** [comment]
These changes look OK to me @lunascoop @johnhashva

**Comment by johnhashva** [comment]
OK -- I'll cut/paste Batch 1 content into the CMS this week.  TY @lunascoop and @RLHecht and @bethpottsVADEPO

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva sent Batch 2 to Janel Keyes at VA on ~July 19.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO (with @bethpottsVADEPO + @RLHecht + @lunascoop FYSA) -- I've copy/pasted the Batch 1 content -- attached here -- for VBA forms into the CMS and the updated detail pages should go live with the next DB migration/push (Saturday or Monday?).   If you have time, please take a look in Preview mode via CMS.

[VA.gov_Find_a_Form_Content_Batch-1_reviewstakeholderedits.7.23.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6909082/VA.gov_Find_a_Form_Content_Batch-1_reviewstakeholderedits.7.23.21.docx)

**Comment by johnhashva** [comment]
@RLHecht for the Batch 1 content update for VBA forms -- one of the forms admins, Kayce White, said this about the description for For 26-1880: _"When to this this form" also doesn't match up with a comment Kayce White made in the document. She says the correct use of the form is "Use this form to determine continued eligibility to the additional allowance for dependents. "._. Do you agree with her recommended change?  It was unclear to me in looking at the redlined doc.

**Comment by RLHecht** [comment]
@johnhashva @lunascoop reworked the sentence in 21-0538 to reflect Kayce White's change (not 26-1880). It now reads: We use this information to determine if you’re eligible to continue receiving additional compensation based on how many dependents you have. I think that addresses what Kayce was saying.

**Comment by johnhashva** [comment]
Thanks @RLHecht -- to confirm: the What's this for description/text is good to go on this page: https://www.va.gov/find-forms/about-form-21-0538/? (Note: I've changed and published the title of the form to Mandatory Verification of Dependents)

**Comment by RLHecht** [comment]
@johnhashva Yep, that looks good to us.

**Comment by RLHecht** [comment]
@MarciMcGuireGCIO The third batch of these got lost in the shuffle but here it is: 
[fff5c216-7c92-452d-b052-46ea9285105b.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/7382283/fff5c216-7c92-452d-b052-46ea9285105b.docx)

**Comment by MarciMcGuireGCIO** [comment]
Thank you @RLHecht !  @LindaLi123 & @davidconlon - This is related to content updates that John Hashimoto initiated with the goal of boosting organic traffic to forms.   The content in the Word doc Randi provided above will need to be reviewed by the VA stakeholders for accuracy.  If they make any adjustments, those adjustments will need to be re-reviewed by Content, and then can be entered into the CMS for the appropriate form.

**Comment by jilladams** [comment]
Contract changed hands, this initiative was not continued, and we are closing old / aging tickets. CLosing. Can reopen as needed in the future.
