### ISSUE TITLE
Medallia Survey | Spanish Language Pages (1 Request of 3) | C&L

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#22721]
# Request the Feedback Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Request is to add the Survey to the Spanish language pages listed below:

1. https://www.va.gov/health-care/covid-19-vaccine-esp/ 
2. https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/
3. http://www.va.gov/asistencia-y-recursos-en-espanol 

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md)

## Description
*Please provide the name(s) of your product and a high level description of your product.*

- Part of Public Websites, the Covid-19 Vaccine, Coronavirus FAQ and Language Assistance page (this one launching ~June 7) have been translated to Spanish . We would like to implement the survey on each page, in-language.

### Launch Date
*Please provide the launch or rollout date.*

- Covid-19 and Corona FAQ pages are live. The Language Assistance page is targeted for release June 7th.

### Staging URLs
*Please provide staging URLs*

1. https://staging.va.gov/health-care/covid-19-vaccine-esp/
2. https://staging.va.gov/coronavirus-veteran-frequently-asked-questions-esp/
3. https://staging.va.gov/asistencia-y-recursos-en-espanol

### Production URLs
*Please provide Production URLs*

- See URLs above

### Additional Information

This is to request translated text for the" Always on (Feedback) survey" via Medallia. It is a Floating feedback button and will be used for COVID-19 and future translated pages.

- Text to be translated to Spanish and Tagalog:

1. Were you able to do your task today?
Yes
No

2. What task were you trying to do today?
[Free text]
 
3. What is your overall satisfaction with this site?
1 = Very dissatisfied
5 = Very satisfied

# Spanish version:

**UPDATES FROM JULY 12**

**Please revise the text for the following 2 survey questions:**

Question 1: 
**FROM** ¿Pudo realizar su tarea hoy?
**TO** ¿Pudo Ud. cumplir su cometido hoy?

Question 2:
**FROM** ¿Qué tarea estaba tratando de hacer hoy?
**TO** ¿Qué Ud. estaba tratando de hacer hoy?

~**UPDATED**~

~¿Pudo realizar su tarea hoy?~

Sí
No

~¿Qué tarea estaba tratando de hacer hoy?**~

¿Cuál es su satisfacción general con este sitio?
1, 2, 3, 4, 5

Muy insatisfecho

Muy satisfecho

[button 1] Cancelar [button 2] Enviar

~[encuesta]~
~¿Pudo completar su tarea hoy?~
~Sí~
~ No~
~¿Cuál tarea estaba tratando de hacer hoy?~
~¿Qué tan satisfecho está usted con este sitio?~
~[escala: 1, 2, 3, 4, 5] [comienzo de la escala] Muy insatisfecho [fin de la escala] Muy satisfecho~
~[botón 1] Cerrar [botón 2] Envío~

# Survey screenshot: ![Screen Shot 2021-04-09 at 1.31.11 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/81fe5529-9bd3-44f7-bfbd-6cb099df58bd)
---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by SKasimow** [comment]
# Request the Feedback Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/medallia-request-survey.md)

## Description
*Please provide the name(s) of your product and a high level description of your product.*

### Launch Date
*Please provide the launch or rollout date.*

### Staging URLs
*Please provide staging URLs*

### Production URLs
*Please provide Production URLs*

---

*Please leave the following blank*

---


## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by SKasimow** [comment]
How to request a survey link takes you to a 404.

**Comment by jwoodman5** [comment]
> How to request a survey link takes you to a 404.

@SKasimow The link is updated now. Thanks.

**Comment by SKasimow** [comment]
@jwoodman5 Hi - tried link ^ again and still getting a 404. Is there something else I need to submit outlined via the link or does this ticket cover what's needed?

Also, do I need to provide you with translated verbiage or does my engineer take care of that? Thanks. Sharon

**Comment by jwoodman5** [comment]
@SKasimow Sorry, I only updated the template you used to create this ticket. But, I just updated the ticket links here as well. You landed in the right spot, but there is some helpful information in those docs as well. Specifically, the fact that we are only doing standard, approved Medallia implementations right now - only the already approved (english) feedback survey.

A translated survey is effectively a different survey and is considered custom, which we are _not_ implementing right now. I know that is not happy information, but I hope it helps regardless.

**Comment by SKasimow** [comment]
@jwoodman5 Thank you - I can access the page now :)

Assuming things continue to go smoothly with the Medallia roll-out, any idea of what timing might be for a custom implementation?

Thanks,

Sharon

**Comment by jwoodman5** [comment]
@SKasimow I think we'll be able to start looking at custom Feedback surveys in a month or two. Also, I don't recall where we landed but we will need you to provide the translation and we will need to make sure it aligns with the PRA approval we got for the initial Feedback survey. Hope that helps. Happy to stay in touch on this. 

Jason

**Comment by SKasimow** [comment]
@jwoodman5 Thanks...I will put in a request for the translations (we may have had the spanish one translated but def. didn't have tagalog) and have those ready to go.

**Comment by jwoodman5** [comment]
@SKasimow Right on. When you get them, can you please add them to this ticket? Thanks!

**Comment by jwoodman5** [comment]
Hi @SKasimow Looks like we have 3 tickets open for translated surveys and I want to make sure I have them straight. Can you please advise? We have this one plus https://github.com/department-of-veterans-affairs/va.gov-team/issues/22997 and https://github.com/department-of-veterans-affairs/va.gov-team/issues/24877#event-4762265503. Please correct me if I'm reading them wrong too. 

The way it works on our side is each translated version is a new request. Ex. We just need one ticket for the Spanish version with all URLs that survey will go on. And we'll need separate ticket for the Tagalog version with those URLs. Happy to have a quick chat to clear it all up. That being said, I did put in the request for the Spanish version, but logged that in a different ticket. Thanks!

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason - I was opening tickets on a per project basis rather than a language basis. I'll update so that we have a ticket for Spanish, a ticket for Tagalog and a ticket for a new English page. Thanks for clarification. Sharon

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason - this is now the request for Spanish survey :)

**Comment by jwoodman5** [comment]
@SKasimow Awesome, thanks again for consolidating by language!

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason - we just received a revised translation for the Spanish survey - I added to this ticket and crossed out old language. Hope it's not a problem to use new text...lmk if it is. Thanks,

Sharon

**Comment by jwoodman5** [comment]
Hi @SKasimow This should not be a problem because I don't think they started it yet. I got the new version submitted and will provide an ETA when I get one. Thanks.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Here's the ticket for the Spanish Medallia survey.

**Comment by RLHecht** [comment]
@SKasimow Here is the translated copy for the Spanish survey.
[13063_Survey_Spanish.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6735376/13063_Survey_Spanish.docx)

**Comment by SKasimow** [comment]
@RLHecht Awesome - thank you Randi!

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason -- I'll put any changes to the staging version of the Spanish survey here:

1. Remove the 2 asterisks at the end of this sentence: ¿Qué tarea estaba tratando de hacer hoy?**
2. Can we change the blue "Feedback" button to "Comentarios"






cc @DanielleThierryUSDSVA

**Comment by RLHecht** [comment]
@SKasimow Here are Mateo's comments from the survey review:

Change the Word Feedback to Comentarios –if we are able to change this radio button.

For the questions, change them to read:

Q1 Pudo encontrar lo que buscaba hoy?

Q2 Que información estaba buscando?

**Comment by SKasimow** [comment]
Hi - I already have a q into Medallia re: changing the "feedback"radio button :)

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi there - let me know if we should move forward with Mateo's feedback. thx!

**Comment by SKasimow** [comment]
@RLHecht Hi Randi - spoke with @DanielleThierryUSDSVA and wanted to understand Mateo's reasoning for changing the wording/meaning from "task" to "information"? 

Was he using the English version of the survey to translate from?


Q1
- English: Were you able to do your **task** today?
- Mateo: Pudo encontrar lo que buscaba hoy?  
     - Google translates this to: **Could you find** what you were looking for today?


Q2
- English: What **task** were you trying to do today?
- Mateo: Que información estaba buscando?
     - Google translates this to: What **information** were you looking for?

**Comment by RLHecht** [comment]
Hi @SKasimow @DanielleThierryUSDSVA I went back to Mateo with the English content so that he could see what our intended questions were. Here is his last email about using the language that's there:

Ok, the words of Q1 and Q2 are not written incorrectly from a literal translation perspective.  

However, culturally, the word “tarea” is not used to say task…in a cultural sense this is to mean “homework” and realizar is to realize something so the wording is a bit off. Task doesn’t translate well so…

Might I suggest to use:

Q1- Pudo UD cumplir su cometido (could also use asunto which is “issue”) hoy? –which better translates to could you complete your misión (Task) today. Cumplir is better aligned to say complete or accomplish which is what I think the question is getting at.

Q2- Qué Ud estaba tratando de hacer hoy? –which better translates to what were you trying to do today and better relates to what the person was able to do or wasn’t able to do if Q1 answer was no.

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA @RLHecht Hola! The update from Jason re: changing the word "Feedback" on the survey button to "Comentarios" was the feedback button uses an image and there isn't an easy way to change these dynamically. There is a larger discussion around changes to the button in general that may solve for this.

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA @RLHecht We're going with Mateo's last recommendation for the 2 questions:

>Might I suggest to use:

Q1- Pudo UD cumplir su cometido (could also use asunto which is “issue”) hoy? –which better translates to could you complete your misión (Task) today. Cumplir is better aligned to say complete or accomplish which is what I think the question is getting at.

Q2- Qué Ud estaba tratando de hacer hoy? –which better translates to what were you trying to do today and better relates to what the person was able to do or wasn’t able to do if Q1 answer was no.

**Comment by SKasimow** [comment]
Completed and released 7/19/21
