### ISSUE TITLE
monitoring of unhealthy ELB nodes

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2273]
During an incident review with the fwdproxy, we realized that there were alarms about the number of nodes that prometheus was finding through autodiscovery in a deployment that was meant as a way of capturing the number of nodes in use for a particular service, but there were no alarms explicitly for when nodes were failing health checks and being cycled out by the ASG.

Some investigation is needed here on the exact threshold, but we should know when a situation like this comes up and there's unhealthy nodes in a load balancer being cycled out regularly. A few is fine and should be expected, but not a constant stream.

**Comment by ricetj** [comment]
No longer relevant.

**Comment by wyattwalter** [comment]
We took a slightly different approach, but it looks like there wasn't actually another ticket for that.

I wrote a Prom rule to attempt to detect when instances seem to be cycling in and out of the ASG which covers more of the scenarios that this was attempting to cover.
