### ISSUE TITLE
audit and fix infrastructure deployments that do all envs at the same time

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2274]
During incident review for fwdproxy failures on 9/19, we noticed that a kernel update (which caused a panic of nodes randomly in a cluster and eventually knocked the service offline) was taken in automatically by the build process that deployed to all 3 environments immediately.

While doing a sequential deploy likely wouldn't have avoided this particular incident alone, we should be rolling out patches to lower environments first to give us a better chance of catching that before an incident.

**Comment by benniemosher** [comment]
we’re working on splitting out these application deploys from the infrastructure so this shouldn’t be a problem as we go forward
