### ISSUE TITLE
File Attachment Issue #2

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22758]
## Background
Attaching evidence in a 686, they are not uploading to VBMS.

## Consideration
- Error: "No such file or directory exists"
- Check in with Ed (before Friday (!))

## Tasks
- [x] Troubleshoot and determine cause of failure

## Acceptance Criteria
- [x] A path forward has been determined

**Comment by kathleencrawford** [comment]
This issue is currently blocked until we can upload documents to VBMS in staging.  Currently our SAML tokens have expired and we are waiting on devops to update with the latest.

**Comment by jason-gcio** [comment]
need staging to be up
