### ISSUE TITLE
Contact Center Review for eBenefits - VRE CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22767]
# Request the Contact Center Review 

<!Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)-->
 

## Description
•	The Veteran Readiness and Employment tool is a short form (VA Form 28-1900) that allows a Veteran to sign up to be contacted for vocational rehabilitation counseling.  Also included is an eligibility wizard that helps Veterans understand if they are using the right form or service and some orientation content to assist in qualifying applicants.  

### Launch Date
Target launch date for VRE is April 19, 2021.

### Version Number
Guide: v1
Video: v1

### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/VRE-CH31-Product-Guide.pdf
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/VRE-CH31-Product-Guide.docx

### Product Video
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/VRE-Ch31-Product-Guide-Video_1.mp4

### Product Video Transcript
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/contact-center-video-transcript.md

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
@jason-gcio , can you please share the original Word file of the guide and transcript?

**Comment by jason-gcio** [comment]
Sure thing!  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/VRE-CH31-Product-Guide.docx (added above as well)

**Comment by starlow00** [comment]
Hi @jason-gcio  Here are my reviewed drafts of the product guide and the transcript. Please let me know if the changes work for you by early next week, if possible. Thanks!

[VRE-Ch31-video-transcript-st-040921.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6288088/VRE-Ch31-video-transcript-st-040921.docx)
[VRE-CH31-Product-Guide-st-040921.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6288089/VRE-CH31-Product-Guide-st-040921.docx)

**Comment by jason-gcio** [comment]
Thanks @starlow00 - I accepted those changes and can reshare them if you like...
[VRE-CH31-Product-Guide_v2.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6288211/VRE-CH31-Product-Guide_v2.pdf) and
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-vre-ch31/contact-center-video-transcript.md

**Comment by starlow00** [comment]
Thanks, @jason-gcio . This looks great. I'll make sure VEO gets copies.

**Comment by starlow00** [comment]
Sent to VEO for review. If no changes by 4/15, will close.

**Comment by starlow00** [comment]
Materials in hand and approved by VEO, ready to go. Closing.
