### ISSUE TITLE
Decompose Subdomains: secondary header / footer

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2280]
This ticket is a placeholder Epic- will populate with info post discovery. 

[Edit - Jen: Referencing original issue here https://github.com/department-of-veterans-affairs/va.gov-team/issues/1877 ]

**Comment by jenniferlee-dsva** [comment]
@Karak888 - added a reference to Andy's original issue.

**Comment by jenniferlee-dsva** [comment]
@Karak888 I think the first decomposed ticket could be to have Liz work with Andy on a research plan to… 

1/ Identify a list of subdomains

2/ Identify subdomain teams/stakeholders

3/ Put together a research plan - interview questions, UI problems, what not - for stakeholders; 

4/ From ^, identify common subdomain header/footer issues  (UI, but maybe possibly there are also CSS and other techie issues?) that we would need to be addressed in a header/footer injection.

I’m not sure what else off the top of my head. These are not necessarily prescriptive, but items that should help her get started. I also recommend that she reach out to Nick, Andy, and Jeff Barnes for history; they were part of header/footer injection last fall and know a lot about the difficulties we encountered.

**Comment by jenniferlee-dsva** [comment]
@Karak888 - We can close this epic now. The nature of this work changed (simpler) and Liz's audit for [2394](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2394) completes this for our team. Sending over to Platform team and Jeff Barnes now for the FE engineering injection work. If any part of this comes back to us, we can reopen.

**Comment by Karak888** [comment]
closing this Epic per note above.
