### ISSUE TITLE
Tier 2:  Content IA / content design

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2281]
## Create experience for tier 2 content. See product outline here: ##
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design

**Goal:** Ensure that helpful, relevant tier 2 information is accessible in the new VA.gov site experience, AND does not dilute, distract, and clutter Veterans' benefit product UX.

**Beneficiaries: As a user,** I want to easily find and get to relevant, related information that helps me better understand how my benefit works; or better use my benefit; or take advantage of non-benefit program resources or services.

**Non-beneficiaries (like VSOs, school counselors, etc.):** As a (VSO, school administrator, fill-in-the-blank user type),** I want to easily find and get to relevant, related information that helps me better do my job to support/help VA beneficiaries, be they Veteran students in college or caregivers of older Veterans, etc.

**Update:** Learnings from design workshop: Tier 2 benefit-adjacent content is vast and there are actually many kinds of tier 2 benefit-adjacent content. There will likely be multiple content and design work streams coming out of this epic. (Ex: campaign landing page template; SLP; learning center; non-Veteran-but-Veteran-supporting audience content...)

[x] Discovery competitive analysis and 'lite' audit
[ ] Select MVP pilot tier 2 content topic/business
[x] Design workshop kickoff 
[ ] Create MVP IA for tier 2 content
[ ] Create MVP content designs for tier 2 content types
[ ] Conduct user research and testing
[ ] Iterate IA and design based on research and testing
[ ] Build Drupal templates
[ ] Launch pilot tier 2 content product
[ ] Create Drupal migration and content workflow plans
[ ] Create training and support schedules
[ ] Socialize templates, onboard teams according to training and support schedules

**Comment by jenniferlee-dsva** [comment]
@Karak888 - I updated the epic story above and linked to the repo folder.

**Comment by Karak888** [comment]
@jenniferlee-dsva has already included the acceptance Criteria up at the top, just not sure where you are with those.  Thanks!

**Comment by jenniferlee-dsva** [comment]
@Karak888 - the criteria above is for the Epic so probably the tickets will need their own smaller criteria/checklists. I'm going to edit the Epic description above to reflect the new reality post-design studio -- that there will actually be multiple types of tier 2 content types and content design work streams.

**Comment by jenniferlee-dsva** [comment]
Referencing related epic for campaign landing page template: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4621

**Comment by jenniferlee-dsva** [comment]
closing as this was completed via learning center product work.
