### ISSUE TITLE
STEM AD: Add google analytics tracking to new functionality.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22812]
As a developer, I need to add google analytics tracking to the new stem automated denial functionality so that we can monitor usage and make adjustments as necessary.

## Assumption:
1. This work does not require a production or feature flag.

## Acceptance Criteria:
1. The links in the more resources section are tracked using:

    > 'event': nav-linkslist'
    > 'links-list-section-header': 'More resources about VA benefits' //dynamically populate with value of links list section
    > 'links-list-header': //dynamically populate with text of header clicked, i.e 'Edith Nurse Rogers STEM Scholarship', 'Find a VA Form', 'GI Bill Comparison Tool'

2. The links in the "Need Help?" right side bar section are tracked using:

    > 'event': 'nav-ask-va-questions-link-click',
    > 'ask-va-questions-header': 'Need help'

3. The link in the email that directs the user to check their claim status (`To check your application's status, go to URL and sign into our claim status tool.`) is tracked using:

    > &utm_medium=email&utm_campaign=stem_scholarship_decision

    example full URL: https://www.va.gov/track-claims/your-stem-claims/8468/status?utm_source=govdelivery&utm_medium=email&utm_campaign=stem_scholarship_decision

## Supporting artifacts:
1. Originating issue: #21747
2. AC 1 Reference
![more-resources](https://user-images.githubusercontent.com/48260534/113865092-b34df600-9779-11eb-9c4f-210b1b6c1428.png)
3. AC 3 Reference
![image](https://user-images.githubusercontent.com/48260534/115294057-18b0c800-a126-11eb-8687-49ab7ef63156.png)
4. [Email Content for AC4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-email-content.md)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/16895
- https://github.com/department-of-veterans-affairs/vets-api/pull/6636

**Comment by sonntag-adam** [comment]
Notified story #21747 is completed. Closing current story.
