### ISSUE TITLE
VRRAP: Remove ability for unauthenticated users to complete the application

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22815]
As a developer, I need to remove the ability for unauthenticated users to complete the VRRAP application so that the processing RPO has all of the necessary information to process the applications.

## Assumptions:
1. N/A

## Acceptance Criteria
1. Unauthenticated users are not able to start and complete the application.
    a. Links to start the application unauthenticated are removed.
    b. The user is not able to directly access the form unauthenticated.
2. The sign in widget at the top of the page uses the pattern as seen in SA3.

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/design/content-doc.md)
2. [Prototype](https://bahdigital.invisionapp.com/d/main#/projects/prototypes/14222564?scrollOffset=310)
 [Another prototype link](https://bahdigital.invisionapp.com/share/CUIAGI923MB)
3. AC2 Reference
    <img width="647" alt="Screen Shot 2021-04-07 at 10 00 46 AM" src="https://user-images.githubusercontent.com/48260534/113879473-8b19c380-9788-11eb-8fc6-736ae48a577e.png">

4. 0994 has the same authentication requirements.

**Comment by JenLJ** [comment]
[Uploading... Screen Shot 2021-04-07 at 10.21.26 AM.png][Uploading... Screen Shot 2021-04-07 at 10.21.47 AM.png]

**Comment by ksantiagoBAH** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/16695

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-04-07 at 1.07.39 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/270b661f-bd8d-499a-af7f-408b89e211bd)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1665&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.
