### ISSUE TITLE
Find a VA Form: Archive Spanish detail pages via CMS and redirect to English to form landing page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#22817]
## User Story

As a Spanish speaker, I would like to have access to the Spanish-language versions of forms so that I can fill them out in my native language, but I do not want to be confused by form detail pages that alternate between Spanish and English

## Expected Behavior

Forms that have a published Spanish language detail page will be changed to "draft" or "archived" status in the CMS so that they can be revived in the future, once we have a more robust translation solution.

## Acceptance Criteria

- [x] Ask Mikki to redirect the Spanish URLs listed below to the main Find a VA Form page (https://www.va.gov/find-forms/)  so that users who may have bookmarked don't get an error.
- [x] Change the publish status of the below forms to "Archive"
- [x] Confirm that the English version of the below forms reference their Spanish counterpart as a "related form"

## Affected Forms & current detail page URLs

| Column1.attributes.form_details_url                          |
|--------------------------------------------------------------|
| https://www.va.gov/find-forms/about-form-10-0137-espanol     |
| https://www.va.gov/find-forms/about-form-10-10ez-espanol     |
| https://www.va.gov/find-forms/about-form-21p-0510-espanol    |
| https://www.va.gov/find-forms/about-form-21p-0512s-1-espanol |
| https://www.va.gov/find-forms/about-form-21p-0513-1-espanol  |
| https://www.va.gov/find-forms/about-form-21p-0514-1-espanol  |
| https://www.va.gov/find-forms/about-form-21p-0516-1-espanol  |
| https://www.va.gov/find-forms/about-form-21p-0517-1-espanol  |
| https://www.va.gov/find-forms/about-form-21p-0518-1-espanol  |
| https://www.va.gov/find-forms/about-form-21p-0519c-1-espanol |
| https://www.va.gov/find-forms/about-form-21p-0519s-1-espanol |

##  Additional context from Jen Lee via [Slack thread](https://dsva.slack.com/archives/C01GCADCMQT/p1617641977086900?thread_ts=1617638328.085000&cid=C01GCADCMQT);

I have a workaround proposal for these handful of Spanish language PDF forms that VA has:

Jennifer Lee  1 day ago
We can continue to make them available via form search, and cross-link to them as the "Related form" on the EN source form detail page. But archive/unpublish the standalone faux Spanish/English hybrid language form detail landing pages.

Jennifer Lee  1 day ago
Example:

Jennifer Lee  1 day ago
Keep this EN page of the 10-10EZ: https://www.va.gov/find-forms/about-form-10-10ez/

Jennifer Lee  1 day ago
^ note how that page does cross-link users to the Spanish version of the PDF.

Jennifer Lee  1 day ago
Archive/unpublish this standalong page: https://www.va.gov/find-forms/about-form-10-10ez-espanol/

Jennifer Lee  1 day ago
Because we don't have a true sitewide localization program, we can't translate the user interface texts of these landing pages -- field labels like "About VA Form ----" / "Related to:" / "Form last updated:" / and so on. We are very far away from being able to do that right now @Josh.

Jennifer Lee  1 day ago
(Remember - the coronavirus related localization is super manual and not scalable sitewide; and we're doing super manual way for COVID 19 only because of pandemic/public health emergency support.)

Jennifer Lee  1 day ago
@Marci McGuire ^

This is a good mini-use case of what happens when we proactively archive a page. It looks like in the past 5 months (since Dec 6, 2020) this form page has only received 29 sessions/unique page views and only 13 clicks from organic search.
But Mikki might want us to implement a redirect, so I would send her a redirect ticket for this page www.va.gov/find-forms/about-form-10-10ez-espanol/  to be pointed to the main Find a VA form search page https://www.va.gov/find-forms/. (in case someone has bookmarked or linked to it directly, they'll still be able to find the Spanish form via search.) And she can decide if it's worth it. (edited) 

Jennifer Lee  1 day ago
^ We never 1:1 redirected the legacy Spanish form landing page, so we don't have to worry there. (Here is the original forms redirect ticket that Mikki might ask for: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5549 ) (edited) 

Jennifer Lee  1 day ago
You and @Marci McGuire will probably want to use this same approach for the all other Spanish PDF form detail landing pages - archive & redirect to forms search. Ex:
https://www.va.gov/find-forms/about-form-21p-0514-1-espanol/
You can find the rest on the CMS: https://www.va.gov/find-forms/about-form-21p-0514-1-espanol/  and https://prod.cms.va.gov/admin/content/va-forms?combine=%28esp&moderation_state=All&field_va_form_administration_target_id=All

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva yes, I'll submit the redirect ticket.  And you're correct.  We'd want the redirects in place before you modify the records in the CMS.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO after you do,  reach out to Mikki via #vsp-content-ia to make her aware and -- if she can provide -- get a sense of her timing.   We don't want this one to sit for too long.   Thank you!

**Comment by MarciMcGuireGCIO** [comment]
I've just reached out an referenced this ticket to ask if it's sufficient or if she needs a separate one.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva I have entered the redirect request for Mikki.  It will be our responsibility to notify our stakeholders of this change.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO  -- All of the following have been archived.
https://www.va.gov/find-forms/about-form-10-0137-espanol
https://www.va.gov/find-forms/about-form-10-10ez-espanol
https://www.va.gov/find-forms/about-form-21p-0510-espanol
https://www.va.gov/find-forms/about-form-21p-0512s-1-espanol
https://www.va.gov/find-forms/about-form-21p-0513-1-espanol
https://www.va.gov/find-forms/about-form-21p-0514-1-espanol
https://www.va.gov/find-forms/about-form-21p-0516-1-espanol
https://www.va.gov/find-forms/about-form-21p-0517-1-espanol
https://www.va.gov/find-forms/about-form-21p-0518-1-espanol
https://www.va.gov/find-forms/about-form-21p-0519c-1-espanol
https://www.va.gov/find-forms/about-form-21p-0519s-1-espanol

Please --

- Confirm that the English version of the forms reference their Spanish counterpart as a "related form"
- Confirm on Friday 2/23 that these Spanish form detail pages are no longer published via Find a Form

**Comment by MarciMcGuireGCIO** [comment]
Great!  Thanks, @johnhashva!  I'll confirm and comment here.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva detail pages for the following forms currently do NOT list their Spanish counterparts as related forms: 

21P-0510 
21P-0512s-1
21P-0513-1
21P-0514-1
21P-0515-1
21P-0518-1
21P-0519c-1
21P-0519s-1

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO got it -- will add these tomorrow.

**Comment by MarciMcGuireGCIO** [comment]
Great; thank you @johnhashva!

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva - just checked and detail page links for the Spanish forms still appear in the search results.  It may be that the detail page URL needs to be manually removed from the form record in the CMS.

**Comment by johnhashva** [comment]
1. These are now updated and will be published in the next overnight DB pull/push.

21P-0510
21P-0512s-1
21P-0513-1
21P-0514-1
21P-0516-1
21P-0519c-1
21P-0519s-1

Note: There is no 21P-0515-1 -- guessing you meant 21P-0516-1

2.  Re: detail page links for the Spanish forms still appear in the search results. If I manually delete  the form record in the CMS -- meaning the Spanish-language detail page -- then the Related Forms links I just created for the English forms won't work, right?  In order to make those Forms disappear from the search results, I believe we need that to happen in ... Lighthouse?  Or maybe I'm missing something.

**Comment by MarciMcGuireGCIO** [comment]
Thank you! Yes, I must have fat-fingered while typing. Thank you for catching that.

I will do a little digging to figure out how to get the links to go away. You're right; you can't delete the actual form record. I thought there was a CMS field for the detail page URL, but I will find out and update you.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO (re-surfacing this) -- looks to me like there is an error in the logic for the Spanish language forms I have set the Detail page to Archived in the CMS.  What we were expecting: When set to archive, the detail page is no longer available, and the Search listing for the PDF should change back to a non-linking headline, allowing the user only to download the PDF.

<img width="774" alt="Screen Shot 2021-04-26 at 8 40 24 AM" src="https://user-images.githubusercontent.com/63107147/116084365-b9920c80-a66b-11eb-8dee-1b5398480f31.png">

I'm going to set the 10-0137 to DRAFT status and see if that works.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @johnhashva.  As I understand it, a non-published page should result in the Forms API returning a null value in the detail URL field.  That, in turn, should result in the title having no link in the search results.  I'll check at it again tomorrow to see if your latest change had an impact (and also check the archived ones to see if the recent change Steve Wirt made possibly made a difference).

**Comment by MarciMcGuireGCIO** [comment]
As of this morning, the Forms API continues to return a value in the `form_detail_url` field on the Spanish form results, which is not what we'd expect after setting their publish states to "Archive".  I have pinged @swirtSJW in Slack to find out if there is a different way this needs to be done.

https://dsva.slack.com/archives/CUB5X5MGF/p1619530881081000

![image](https://user-images.githubusercontent.com/73354907/116252006-2d501a00-a73d-11eb-966c-aec71ccd74cb.png)
