### ISSUE TITLE
STEM AD: POA value is not returned from EVSS

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#22822]
Part of the STEM automated denial process is to look into an applicant's EVSS data to see if they have a Power of Attorney (POA). That value is then added to the spool file entry for that 10203 application. Currently, the value is not returned as expected and is always showing as `N/A` on the spool file.

### Steps to reproduce:
1. Submit a form with a user that has POA
2. Review the spool file which contains the submission

### Expected behavior
1. Spool file contains `Applicant has POA: YES`

### Actual Behavior
1. Spool file contains `Applicant has POA: N/A`

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6480

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
V-EBC-8526 submitted 4/8/21 using user 228 should have POA and can be confirmed the morning of 4/9/21

**Comment by delli-gatti-michael** [comment]
Latest PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6582#pullrequestreview-636820845

**Comment by desireeturner** [comment]
Need to check logging to see if we're getting the EDIPI.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6726

When this is deployed we should see a `Submit10203EVSSError` error in Sentry if there are any issues with the `User.power_of_attorney`

**Comment by shawkey-daniel** [comment]
A review of the Sentry logs indicates the latest PR did not rectify the issue. As far as we can tell, the EVSS VSOSearch request does not work as indicated in production. We have been unsuccessful in finding anyone with domain knowledge to help troubleshoot the issue. I recommend closing this issue.
