### ISSUE TITLE
Explore the Idea of Caching Content / Node Modules Between Jenkins Runs

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22835]
# To-do
* Create GHA focused tickets for these ideas
* Make sure to add details about working with Ops on the GHA tickets
* Close out this ticket -- research into this solution for Jenkins has hit a natural dead-end

## User Story

As a platform team member who relies on the **Jenkins** pipeline to understand the success of my changes, I need the most responsive build pipeline that I can get.

## Expected Behavior

Elements of the build that are unchanged between pipeline runs are cached and reused in subsequent runs.

## Acceptance Criteria

- [ ] _Add bulleted list of all the task that bust be finished for the feature to be consider finished & ready to merge_

**Comment by billfienberg** [comment]
This might be useful for caching stuff to a volume that can be used between different runs. 

https://www.jenkins.io/doc/book/pipeline/docker/#caching-data-for-containers

**Comment by pjhill** [comment]
This will be timeboxed to the current sprint. If no progress is made then future efforts will be made to create these changes in the GHA hosted CI pipeline for `vets-website`.

**Comment by pjhill** [comment]
This effort will be pursued in the GHA pipeline.
