### ISSUE TITLE
Message displayed to Veteran in VAOS regarding reason why they can not direct schedule needs clear message

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#22859]
Current behavior:

When a user tries to schedule at a facility that is enabled for direct scheduling, not enabled for requests, and fails one of the direct scheduling checks (past visits or has matching clinics), we show a message saying that the facility does not support online scheduling for this type of care.

New behavior:

When a user tries to schedule at a facility that is enabled for direct scheduling, not enabled for requests, and fails one of the direct scheduling checks (past visits or has matching clinics), we should show a message about the reason they failed the direct scheduling check.

This results in two new messages:
- The veteran hasn’t visited the facility yet for that TOC - show the no past visit found error (text in issue below)
- The veteran hasn’t used any clinics at the facility for that TOC - show the no clinics error (text in issue below)

AC
- [ ] Past visits message is displayed when a user fails the direct schedule past visits check and requests aren't enabled
- [ ] No clinics message is displayed when a user fails the direct schedule no matching clinics check and requests aren't enabled
- [ ] No changes to the messages shown to the user if requests are enabled

Original bug:

Veteran does not have a past appointment at the particular site within the last 24 mos.  

If DS = 12/24 mos and request = yes --> request flow
If DS  12/24 mos and request = 12 or 24 -->  the vets sees message:  We can’t find a recent appointment for you.

This one is the one I have an issue with:  
If DS=12/24 mos and request = no --> VAOS displays message:  This facility doesn’t accept online scheduling for this care. 

So here is my minor issue. It is not that the site does not support direct scheduling. It is that the veteran hasn't had an appointment.  This message make it appear that VATS is set to NO when that is not the case.

**Comment by jbalboni** [comment]
The way we handle choosing an error message is to fall back to from the DS flow to the request flow checks. We assume that requests are generally less restrictive than DS, so we show those messages before we show DS ones. This isn't really correct when DS is turned on and requests are not.

I think the logic should be:

- if DS and requests are both turned on and you can't do either: show the request check errors
- if DS is off and requests are turned on and you can't make a request: show the request check errors
- if DS is on and requests are turned off and you can't self schedule: show the direct schedule check errors

**Comment by laurenernest** [comment]
@jbalboni which of the alerts documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md) is the direct schedule check error you think the last scenario should show?

**Comment by jbalboni** [comment]
@laurenernest One of them is the [past visit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts/eligibility-modal-request-past-visit.png) one, the other would be not finding any clinics they've used before, which we don't have an alert for.

**Comment by laurenernest** [comment]
Let's make your recommended change for the alert we do have. I've created a placeholder follow-up ticket for the clinic scenario. #25756

If you still see the copy "within the past months", can you create a bug ticket to fill in the x number of months where it's missing?

**Comment by jbalboni** [comment]
@laurenernest It's kind of awkward to do those two alerts separately. It'd be better to make the change in one ticket. The main thing that changes is to not fall back to the request check failures if requests are turned off, so it's tricky to not do that for one direct scheduling check, but not the other.

**Comment by laurenernest** [comment]
Sounds good. Will do a design and content review.

@marcynadeau what are steps to repro so we can run through the flow as a user who will hit that config?

cc @outerpress

**Comment by marcynadeau** [comment]
@laurenernest Veteran does not have a past appointment at the particular site within the last 24 mos.  DS= Yes 12/24 mos and request = No. Type of care = Ophthalmology. Site = Sidney.  Patient = kidys.b.quankep@id.me

**Comment by outerpress** [comment]
@jbalboni I’m not 100% clear on how these eligibility checks work, so I’ll restate what I _think_ you’re proposing - please let me know where I’m off:

For a given type of care, when a Veteran selects a facility, we check if they’re eligible to receive that TOC there.

If that facility has both DS and requests turned on, show request check errors when:
* The facility doesn’t support requests for that TOC - show the [requests not supported](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md#requests-not-supported) error
* The request limit has been reached for that TOC - show the [request limit reached](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md#request-limit) error
* The veteran hasn’t visited the facility yet  for that TOC - show the [no past visit found](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md#past-visit) error

If that facility has DS turned off and requests turned on, show request check errors when:
* Same as above

If that facility has DS turned on and requests turned off, show the direct schedule check errors when:
* The veteran hasn’t visited the facility yet for that TOC - show the [no past visit found](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md#past-visit) error
* The veteran hasn’t used any clinics at the facility for that TOC - **this doesn’t exist, we need designs/language for this case**

**Comment by jbalboni** [comment]
@outerpress That all looks correct to me. There are two variations for the "The veteran hasn’t used any clinics at the facility for that TOC." use case. One is what you state, that you haven't used any of the clinics available. The other is that there are not any clinics available at all. The latter is a facility configuration issue, but it could happen.

**Comment by outerpress** [comment]
Thanks @jbalboni - I think we can use the same popup interaction for those states with different language. Here's my first pass at the new alerts we need for direct schedule issues. @peggygannon could you take a look at these and provide recommendations? 

I'll restate the context here:

For a given type of care, when a Veteran selects a facility, we check if they’re eligible to receive that TOC there.

If that facility has DS turned on and requests turned off, we show direct schedule check errors when:

---

**The veteran hasn’t used any clinics at the facility for that TOC**
(Note - this is based on the [no past visit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md#past-visit) alert for requests)

_Alert header_ 
We couldn't find a recent appointment at this location

_Alert body text_ 
You need to have visited this facility within the past [number] months to schedule an online appointment for the type of care you selected.

If you haven't visited this location within the past [number] months, please call this facility to schedule your appointment or search for another facility.

----

**There are no clinics available for that TOC at the facility**
Note - this is a configuration issue

_Alert header_
We're sorry, we couldn't find any available clinics for this type of care

_Alert body text_
This facility doesn't have any clinics that support online scheduling for this type of care. Please call this facility to schedule your appointment or search for another facility.

**Comment by peggygannon** [comment]
Hi, @outerpress Please see below for my recommendations to these messages. Please let me know if you have any questions. Thx! 


**We couldn't find a recent appointment at this location**

You need to have visited this facility within the past [number] months to schedule an online appointment for the type of care you selected. Please call this facility to schedule your appointment or search for another facility.

------

**We couldn't find a clinic for this type of care**

We're sorry. This facility doesn't have any available clinics that support online scheduling for the type of care you selected. Please call this facility to schedule your appointment or search for another facility.

**Comment by outerpress** [comment]
Looks great to me @peggygannon! cc @laurenernest

**Comment by jbalboni** [comment]
@laurenernest @outerpress @peggygannon Reading back through this ticket again, this language isn't accurate: "You need to have visited this facility within the past [number] months to schedule an online appointment for the type of care you selected." 

It's not just that you visited the facility, it's that you had an appointment for that type of care within the type period. The current message for requests says: "To request an appointment online at this location, you need to have had a primary care appointment at this facility within the last 12 months."

**Comment by aarathi-poldass** [comment]
@laurenernest @jbalboni - 

1) Validated scenario where the user didn't have any optometry appointments for the past 12 months. Attached is the screenshot.

![image.png](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/179a8133-e71a-4ac2-aa8d-c196d7baee29)

2) Validated scenario where the Type of care - Sleep Medicine, CPAP, Fort Collins VA Clinic (Facility) --> No clinics found for the type of care

![image.png](https://images.zenhubusercontent.com/5f2d821a116669dd6f883796/979cc309-46e0-42f7-aa11-9b6289511b50)

**Comment by laurenernest** [comment]
Thanks! Closing ticket.
