### ISSUE TITLE
Find a VA Form: Create Word copydecks for SME review/input

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#22857]
## User Story

As a Veteran, I would like some information about forms so that I can distinguish similarly-named ones from one another based on their "When to Use" descriptions.

## Expected Behavior

A document will be created for each VA forms SME so that they can review our proposed descriptions and provide feedback and add additional information about related forms or helpful links

## Acceptance Criteria

- [x] Decide how many forms need "When to Use" text
- [x] Identify the SME for each of those forms
- [x] Create a Word document template that includes form name, draft "When to Use" copy, and fields for SMEs to add related links and information about other links that  might be helpful in relation to that form.
- [x] Review document structure with Content team

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva is there anything I can do to help keep this one rolling? Thx!

**Comment by johnhashva** [comment]
Nope, finishing this up today and scheduling a re-meet with Site Content team for Friday.
