### ISSUE TITLE
IA Feedback - Staging review - FSR

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#22869]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- 5655 PDF links - I noticed links to the PDF version of the 5655 actually link to the legacy content page that then has a link to the PDF.  Should these links go to a legacy page (that page will eventually be redirected), or should they link directly to the pdf?
 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- **User flow:**  I was not signed in on staging and started the form, it was all pre-populated with test user data, so I wasn't able to go through the form in an unauthenticated state.  Either test data needs to be removed from unauthenticated state, or the link to be able to complete the form in an unauthenticated state needs to be removed.  Not fixing this will result in users being unable to submit the form correctly. 
- **User flow:** Once I signed in, then the 5655 indicated that I had a form in progress, when I selected to start over, it should have taken me all the way back through the wizard, but it immediately started the form.  If a user is indicating they want to start over, they should go back to the wizard so that the type of request they need can be confirmed to ensure they should be doing the form.  Not fixing this will result in users being led down the wrong path.  
- ~**Entry points:** No primary entry points to the form are provided for users.  The recommended primary entry point was on the [Manage debt static page.](Use our online tool to check the status of your VA debt and find out what options you have to resolve it.)  No content is currently displayed on that static page to reference the ability request help for debt. Not fixing this will result in users not being able to access the form unless by directly linking to it.~

**Should:**
- **Entry points:**  Using test user 1, going through viewing their debt, once on an education debt, there is content and a link to request financial assistance, that link takes the user to the legacy content page that is planned to eventually be redirected.  I believe these links should now take the user to the wizard on the FSR so it can direct them appropriately.  Not fixing this will result in sending users down a path that requires extra clicks to get to their ultimate destination (the online FSR).
- **Linking/information scent:** In wizard alerts after selecting either STEM or VET TEC, the email addresses provided are displayed in all caps - email addresses are not case sensitive, and these should be in all lower case for ease of reading and consistency to how the "mailto:" is coded. Not fixing this may cause confusion if users don't see a matching email address when they click the link. 
- **Linking/information scent:** *In the wizard alerts after selecting "Make a payment",  the link to " Find out how to manage your debt" is a more broad task than what they have indicated they want to do - make a payment. Recommend providing more specific info/link directly to pay.va.gov, or and/or providing a more specific link to deep link them to the corresponding content on the static page for all the ways to make a payment. Not fixing may result in increase in time to complete task and user frustration.*
- **Linking/information scent:** In the wizard alerts after selecting "I disagree with the VA decision" , the link label to "Learn more about the VA appeals process" should reference the new label for appeals "Decision reviews".  Not fixing this will lead to user confusion due to a disconnect between the link label and the page they land on. 

**Consider:**
- **Navigation components:** My recommendations were not clear, and this is not a blocker by any means - the last component of the breadcrumb should generally match the H1.  If time allows, consider mapping/changing the breadcrumb to match the H1 of the introduction page of the online form.  This ensures consistency between the content page and the sitewide navigation components. 
- **User flow:**  The wizard design pattern does have an optional "start over" function, that allows a user, once they go past the wizard and get to the beginning of the form, to choose to start over if they feel they need to answer something different, or are exploring options.  That may be a helpful option for this form.

**Comment by mnorthuis** [comment]
Danielle provided a link to the static landing page.  After reviewing I have removed an item from the feedback above (crossed out) and updated another issue (in italics).   Please let me know if you have any questions!

**Comment by rebeccawalsh** [comment]
Thanks, @mnorthuis! I've gone ahead and made design and FE tickets for these, only one piece I had a question about:

**Must:**
- Done - unauthenticated is not a feature, we just used it to test in staging with! This is removed now.
- [Ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23061)

**Should:**
- [Ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23198)
- [Ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23199)
- [Ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23204)
- [Ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23205)

**Consider:** 
- Having a hard time interpreting -- are you saying that the breadcrumb on the introduction page and subsequent pages of the form should include parentheses like the h1? 
![image](https://user-images.githubusercontent.com/6361930/114739577-02b29a00-9d17-11eb-8a47-4ea5dbae59e5.png)
- [Ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23061)

**Comment by mnorthuis** [comment]
Hi @rebeccawalsh, I'm going to have a quick convo with the sitewide content team on the H1/breadcrumb - they haven't used parenthesis in the H1 like that before, so I want to confirm that they are moving in that direction and make sure everyone is clear on how that will change the breadcrumb as well.  Ideally the H1 and breadcrumb are tied together/the same. 

I also noticed- and I am SO VERY SORRY FOR MY MISS ON THIS ONE - that I had the URL for the form incorrect.  It is missing the word "form" in final slug.  So it should be:

www.va.gov/manage-va-debt/request-debt-help-form-5655/

Let me know if this is something that can be corrected before you go to production.

**Comment by mnorthuis** [comment]
Ok, I spoke with Beth and Danielle to confirm their approach on the H1s for this.   The breadcrumb will no longer have the form number on it, due to how we need to approach the H1s when there is a wizard included on the /introduction page.   
So the breadcrumb for all the pages within the form flow will be:

Home > Manage VA debt > Request help with VA debt

I will update this in the IA recommendation.

**Comment by rebeccawalsh** [comment]
@mnorthuis Cool - those changes are reflected in [this ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23341)! (Feel free to add anything if I missed it.)
