### ISSUE TITLE
Mobile Inconsistency: Resources & Support Search 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22868]
## User Story

As a user I would like to see consistent design across all VA.gov search tools, including Resources & Support, so that I don't have to re-learn a new pattern for each tool.  During the consistency work it was identified that R&S Mobile UX was inconsistent from that of Desktop and likely creating confusion to mobile users.

## Expected Behavior

R&S had the correct search bar UI on desktop but the mobile UI needed an update. Mainly the grey box / filter menu that was hiding the search bar and radio buttons was removed and adjusted to the grid width to create consistency with other mobile tool UI.

[R&S mobile update](https://vsateams.invisionapp.com/share/8Y10IE2JN2J4#/448630358_Resources_-_Support_-_Mobile) 

## Acceptance Criteria

- [ ] Mockups for Resources & Support search completed
- [ ] Accessibility has reviewed and provided feedback
- [ ] Design has reviewed and provided feedback
- [ ] PO/PM has reviewed design elements and approved next steps
- [ ] Design has been validated by Ryan T. as part of the design system process

**Comment by brianalloyd** [comment]
Plan is to wait and add this to a research component for Cindy before revisiting with Ryan and Design team.

**Comment by FranECross** [comment]
This is the only ticket still open on an old epic. Closing, and can resurrect in the future if needed.
