### ISSUE TITLE
Access for [Brian A. Lloyd, PM Public Websites Team VFS]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#22877]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Brian A. Lloyd
- Please Provide your email.
   > blloyd@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VFS Public Websites, Senior Product Manager, GovernmentCIO.

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key? ssh/id_rsa_vagov.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmcn8f06pb5GMu5r5KIAmE3RUJHBdReDvoft7ReIKMQKrcQ/1WMLeIe31fWyLbvEPy7On2RAc93vVX0VTiT37wfO6dkW0clkej1cLf/zvR1cfc6zKpXOlL/flXwQr7t3PALzV0spDYUAP0hPQvA5xS3jX/sSGTLMXHkzNc9hv739UGbQbubm4dVjNWag0R/vmObXYZnCEfA692bsDjiDCWHfmxa873maI0X+7efbaMnxhfkKJtRLpGnEVkEft8O1in2Hy/Poe7wjg0euc6+qp31KJVlgQpVOy/nQn72wBwBN2dst6DE4rbVihIb1VS0Y0cyj7odi30sz1CWKo3tG49HGtxk6MJYROLnTliM+DDUAU7R7L+tWlMYsExC4bO3PvZjNHRJG4LWrN4d55eUfuBEIpCN/Mr19mJ6/i4cRQHrXTr7wwY3x4q/AIRVMvMh/t4UcpWUppuahY72dpjC/Rn5AjhEGj8i1iDRvgIxsqbYAf16etLFFkbQ+KyULS9fgs= brianlloyd@BrianLloydsMBP

If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+ username@mail.com
```

- Grant AWS Console access?
  >  NO
  - What AWS services do you need access to and why?

**Comment by brianalloyd** [comment]
@department-of-veterans-affairs/vsp-operations could you please review this request.

**Comment by mydesignrocks** [comment]
getting to it @brianalloyd

**Comment by mydesignrocks** [comment]
SOCKS access granted. Please continue with the guide to establish a connection to SOCKS proxy.

**Comment by brianalloyd** [comment]
@mydesignrocks I had to change my SSH Key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCv9NAhFZFoTMDjPF4W84jXvlO/OXd9aSUQJD+j4zpz/Fi3aNehCVUEXorLgpk8Q5jjKrbE1OYdQFryBIo5Ytnr1AdL7phaxMuzCwMTX9KVL6Q2VL39VudAocYVXasRTNq21jfHdja3rV17h+HBaz9lU284rHrN6WATHoauvVuGEiaO7IaeNsciRCuAN9hP570U6xuialEP2PtrbCaz4MTfO/KssTGNtkDIcKrbPIk715/j27LVdy+RmPCo4lkuJUUcUP934OuQpqyajqV+p8Xi7pcEYsG0dd94OM6iEdPS337BsPkWT82313FjzYQ72gtwztU+yUxpPbS4qy/fQ6hNG8y5w4sru/nqVJJ26XNOcvZHhfsnjWi638F/kCCyy1IH9wmlwL0SRckGxlkdiqJC/Y8pIZmulLDv8Y8khCk/JhuK5E4xSDYVproTLlts6GMBTFr/uewu5hjj92MVjiebsbpOFby5k+JcsutC2E1sY5/cuMzsl/kR/hDIsqAfm/8= brianlloyd@BrianLloydsMBP

Do you need to reestablish access in support.  Sorry for the issues, had issues connecting and was direct to respin steps.

**Comment by mleclerc00** [comment]
ssh key updated

**Comment by brianalloyd** [comment]
@mleclerc00 still suck on this, would it possible to get a consult, screen walkthrough?
