### ISSUE TITLE
508-defect-4 [COGNITION]: Reword or design the education math problem on step 2 of 4

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#22874]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a user with cognitive considerations, I don't want to have to count or do math on how many years of education I have.

## Details

Is there a reason we ask for Veterans to provide a specific number on how many years of education they have? This may prove to be a blocker for Veterans with learning/cognitive disabilities. Folks could overthink this too- does this mean counting half years as well? What if my schooling lasted only half a year?

The original mockups indicate that these are optional, but that is not present in staging. [If it really is optional, why are we asking for it?](https://preview.uxpin.com/e291c4ac8956d804d774160cdb82ecb724044689#/pages/129526678/simulate/no-panels)

## Acceptance Criteria

- [x] Education question does not require significant cognitive load

## Steps to Recreate

Step 2 of 4 Additional Information

## Proposed Solution (if known)

Remove the question if it is optional or rephrase it in a more human-centered way. E.g. 

**What was your highest level of education?**
( ) Middle school
( ) High school
( ) Undergraduate College or University
( ) Higher education, for example, a masters or doctorate

## Screenshots or Trace Logs

<img width="818" alt="Screen Shot 2021-04-07 at 3 10 45 PM" src="https://user-images.githubusercontent.com/14154792/113920976-7868b400-97b3-11eb-9a7b-c9580b387559.png">

**Comment by ohgreatkate** [comment]
replaced with drop-down and the question adjusted to 'what's your level of education?' ideally would like it to say highest level of education.
