### ISSUE TITLE
508-defect-1 ❗ Launchblocker [SCREENREADER, COGNITION]: Step 2 of 4, legend must be the first child of the fieldset so it can be announced

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#22876]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

<hr/>

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader user, I need to know that a range of form inputs are grouped together, so that I may understand the scope of the use case.

## Details

Groups of form elements **MUST** have group labels (e.g. `<fieldset>` and `<legend>`, to meet Section 508 requirements. Although "your new address" is written as a `legend` within a `fieldset`, it _will not_ be announced unless it is the first child of the `fieldset`.

That being said, we strongly recommend splitting this page apart into two pages to reduce complexity and meet platform's guidance of boring before magic.

For example:

Page 1
> "How many years of education?"
> "Are you moving in the next 30 days?"
> Continue >

Page 2
> "Where are you moving to?"
> Continue >

## Acceptance Criteria

- [x] The legend is the first child of the fieldset
OR
- [ ] The page is split apart into two pages 

## Environment

* Operating System: all
* Browser: all
* Screenreading device: all
* Server destination: staging

## Steps to Recreate

Step 2 of 4, Additional Information

## WCAG or Vendor Guidance (optional)

* [WCAG 2.0 Level A - 1.3.1 - Info and Relationships: Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

* [Wuhcag 1.3.1 – Info and Relationships (Level A)](https://www.wuhcag.com/info-and-relationships/)

* [WCAG 2.0 Level A - 4.1.1 - Parsing](http://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html)

## Screenshots or Trace Logs
<img width="1278" alt="Screen Shot 2021-04-07 at 3 26 00 PM" src="https://user-images.githubusercontent.com/14154792/113922936-ec0bc080-97b5-11eb-9f60-74c173659f10.png">

**Comment by ohgreatkate** [comment]
page was updated with the proper fieldset labeling
