### ISSUE TITLE
Conduct UAT for CH31

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#22871]
## Background
We need to conduct a final UAT for CH31

## Tasks
- [x] Using the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/uat/ch36-uat-research-plan.md) and [convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/uat/ch36-uat-convo-guide.md), conduct UAT from April 13 through the 16

## Acceptance Criteria
- [x] ~~UAT has been conducted~~ UAT concluded until reschedule

**Comment by sporeboy** [comment]
Rescheduled Monday sessions... Created email roster if we need to "whitelist" participants.

**Comment by sporeboy** [comment]
UAT will be postponed until 4/26 at the earliest. Per Perigean, session will need to be recruited for and scheduled, though some participants may return.
