### ISSUE TITLE
Redirect Request: COVID content support - urgent

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#22889]
### Instructions
We want to capture the following URL variations to permanently 301 point to the
 https://www.va.gov/health-care/covid-19-vaccine/ page

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

### Requesting team info
*Lauren Alexander, Jen Lee, Danielle Thierry*

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live* 

Destination page is already live: 
https://www.va.gov/health-care/covid-19-vaccine/

Please indicate when the change/redirect(s) needs to be implemented"
- [x] Other - Please indicate timing :  **as soon as April 8 - no later than Friday April 10.** 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Redirect Destination:  https://www.va.gov/health-care/covid-19-vaccine/

- va.gov/covidvaccine
- va.gov/covidvaccines
- ~va.gov/covid-vaccine~
- va.gov/covid-vaccines
- va.gov/covid19vaccine
- va.gov/covid19vaccines 
- va.gov/covid-19-vaccines  {plural variation of existing redirect}
- va.gov/covid19-vaccines {plural variation of existing redirect}

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by jenniferlee-dsva** [comment]
Just a note - maybe already obvious - the URL variations above should not be in the sitemap. they are not meant to be indexed.

**Comment by mnorthuis** [comment]
@jenniferlee-dsva we already have a redirect in place for `/covid-vaccine`, so I crossed that one off above. 

One other redirect we already have in place is `/covid19-vaccine`, so do you want to add the plural version of that one as well?

**Comment by jenniferlee-dsva** [comment]
Per Lauren's thumbs up above - yes, we're adding the plural version in case ppl accidentally type it that way. Thank you!

>One other redirect we already have in place is /covid19-vaccine, so do you want to add the plural version of that one as well?

**Comment by ncksllvn** [comment]
Gotcha, so add `/covid19-vaccines` onto the list of redirects?

**Comment by jenniferlee-dsva** [comment]
Lauren had mentioned that `covid-19-vaccine` was the existing redirect. That's why we wanted the plural version of this: `covid-19-vaccines`.  

Is `covid-19-vaccine` singular not already a redirect? if not, we need that too.

**Comment by ncksllvn** [comment]
> Is covid-19-vaccine singular not already a redirect? if not, we need that too.


We do already have that one

**Comment by jenniferlee-dsva** [comment]
cool. then please add the pluralized version of that: 
`va.gov/covid-19-vaccines`

**Comment by ncksllvn** [comment]
> cool. then please add the pluralized version of that:
va.gov/covid-19-vaccines

Got it!

**Comment by jenniferlee-dsva** [comment]
i think it was already up there on the og list.  so with all the odd ones from comments, the complete list:

    va.gov/covidvaccine
    va.gov/covidvaccines
    va.gov/covid-vaccines
    va.gov/covid19vaccine
    va.gov/covid19vaccines
    va.gov/covid-19-vaccines {plural variation of existing redirect}
va.gov/covid19-vaccines {plural variation of existing one}
