### ISSUE TITLE
Phase 1: Migrate Cypress E2E Tests from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#22884]
# Description
Per coordination with FE Tools, the pipeline is shifting in two phases. Phase 1 involves moving all services out of the CircleCI hosted pipeline into GitHub Actions.
Cypress E2E test artifacts are currently only available in CircleCI. CircleCI Cypress E2E test execution is non-blocking. VSP needs to migrate the Cypress E2E test execution and artifact collection from CircleCI to GitHub Actions.

Merge this change into Eugene's branch as part of the effort to deprecate the use of CircleCI.

Per Eugene, the default behavior for GitHub Actions will require an interested user to download an archive of all test execution playbacks. This is not ideal and could be worked around by altering the storage location for the playback files to an S3 bucket.

# Acceptance Criteria
- [x] Cypress E2E tests are executed in GHA
- [x] Cypress E2E test artifacts are collected and available in GHA
- [x] Cypress E2E tests are no longer executed in CircleCI
- [ ] Test playback artifacts are uploaded to an S3 bucket upon execution for individual download

**Comment by ddzz** [comment]
PR opened: https://github.com/department-of-veterans-affairs/vets-website/pull/17246

**Comment by pjhill** [comment]
Artifact collection is a continuing effort under this ticket -- https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/25312. Other than that, this ticket is resolved by the merging of this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17246).
