### ISSUE TITLE
Find a VA Form: Writing up design intent outline for search UI consistency

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#22882]
## Acceptance Criteria

- [ ] Design intent outline is created for reference when requesting a design intent review.

**Comment by callen2563** [comment]
Link to [product outline template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md) 
I'm just wondering where I should save the outline in GH

**Comment by MarciMcGuireGCIO** [comment]
Let me make a spot and I'll put the link here.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 I can also fill in most of this.  If there are design-specific bits, then I'll ping you for that info.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 here is the link to the file: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/search-ui-consistency/product-outline.md
