### ISSUE TITLE
508-defect-3 [COGNITION]: Review page, it's not clear if a user has not selected a time

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#22881]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a user with cognitive considerations, I want to know for certain if I have not selected a time.

## Details

It's unclear if a user has explicitly not selected a time on the results page.

## Acceptance Criteria

- [ ] Either the unselected times are not shown OR
- [ ] The unselected times are explicitly labelled as "unselected"

## Steps to Recreate

Review page, select only one time of three

## Proposed Solution 

Explicitly write out "unselected"

## Screenshots or Trace Logs

<img width="989" alt="Screen Shot 2021-04-07 at 4 13 40 PM" src="https://user-images.githubusercontent.com/14154792/113928568-fed5c380-97bc-11eb-89ea-fb89f1d522b0.png">

**Comment by ohgreatkate** [comment]
all options have been converted to a check box, the issue is resolved.
