### ISSUE TITLE
[FE] My VA - (Pre QA) My VA content lacks proper x-margin/padding at 1008px breakpoint

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#22896]
The page contents gets too close to the edge of the browser at the 1008px breakpoint. We should add the proper x-padding.

https://user-images.githubusercontent.com/20728956/113944009-ac92a380-97b8-11eb-93bd-237852e761e0.mp4

**Comment by erikphansen** [comment]
PR merged. This can be validated on staging later today.

**Comment by ajakabcin** [comment]
Confirmed on staging
