### ISSUE TITLE
[FE] My VA - (Pre QA) Refine My VA name tag line leading?

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#22895]
The line spacing in the name tag doesn't look quite right to me, especially when the disability rating is shown.

![Screen Shot 2021-04-07 at 3.40.30 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/9d44489d-bb34-49c0-b62e-ec7e4698eff6)

![Screen Shot 2021-04-07 at 3.40.04 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/47d891f0-f00a-42cb-bfcf-1f81250ace9a)

What do you think, @tressaellen?

**Comment by erikphansen** [comment]
PR merged. This can be validated on staging later today.

**Comment by ajakabcin** [comment]
Confirmed fixed on staging
