### ISSUE TITLE
Rules when an attachment upload fails due to multiple errors

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22891]
## Acceptance Criteria
1. When an attachment upload fails due to _multiple_ errors with the file, the UI should display only 1 of the individual errors
2. Hierarchy that determines the order for which error to display:
     - 1) Error - duplicate file
     - 2) Error w/ file type
     - 3) Error w/ individual file size (>3 MB)
     - 4) Error w/ total file size (> 6MB)

For example: 
- if a user uploads an attachment that fails due to all 4 of the errors listed above, the "Error - duplicate file" UI should display. 
- if a user uploads an attachment that fails due to errors 3 & 4 listed above, the "Error w/ individual file size" UI should display.

## Designs
N/A

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
4/23/2021 - Looking good with everything but file type.  Unable to test file type until bug #23585 is in actual build.  Holding...

**Comment by digitalken** [comment]
PASS 4/26/2021 - Looks good on iOS and Android.  Closing.
