### ISSUE TITLE
[FE] My VA - (Pre QA) My VA name tag needs x-padding

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#22898]
Name tag contents can run right into the browser's edge at small screen sizes.

![Screen Shot 2021-04-07 at 3.53.29 PM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/c2edb385-9272-41ff-8c75-250f13006bc2)

**Comment by erikphansen** [comment]
PR merged. This can be validated on staging later today.

**Comment by ajakabcin** [comment]
Confirmed on staging
