### ISSUE TITLE
Apply Message ListItem throughout the app

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22900]
## Dev task
1. Sweep the following pages of the app and apply the Messages ListItem (#22239):
     - Inbox list page
     - Sent folders list page
     - Custom folders list page

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/22/2021 - Looks OK in Android and iOS.  Closing.
