### ISSUE TITLE
Reply to Message | page layout

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22901]
## User story
As a Veteran, I want to reply to a message so that I can communicate a new question or need to my healthcare team.

## Acceptance Criteria
1. Selecting the **Reply** toolbar button routes to a new page, called "Reply"
     - "Cancel" button in header
2. Display the Veteran Crisis Line banner
3. Page layout is split into 2 sections:
     - Section 1: form
     - Section 2: message thread
4. Create placeholder for Section 1 (Form UI is covered in #20486)
5. Create UX/UI for Section 2: 
     - "Message thread" section header
     - Display the message thread that appeared on the preceding message detail page
6. Default behavior for accordions:
     - The accordion of the **most recent** message (i.e. the message closest to the bottom) should be open
     - All other accordions should be closed

## Designs
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447461529

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines

- Mark "Reply" as Header 1
- Mark "Message thread" as Header 2
- Mark "[Subject: Subject line]" as Header 3

## Dev checklist
- [x] UX/UI
- [x] Accessibility
- [x] Add tests

**Comment by digitalken** [comment]
Added to TestRun.

**Comment by digitalken** [comment]
PASS 5/3/2021 - Good on iOS and Android.  Closing.
