### ISSUE TITLE
Field errors for Reply form

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22903]
## User story
As a user, I want to understand why my message cannot be sent so I can fix the fields that were flagged as invalid. 

## Acceptance Criteria
1. On the Reply form, the Send button should always be enabled
2. When at least 1 field level error appears on the form, the corresponding mobile alert error should also appear at the top of the page
     - Copy is hard coded: "Check your message"
     - The mobile alert should disappear when all field level errors are resolved/have disappeared
3. Any fields that have an associated error will update to display the error UI (as detailed in the input field #19585 & dropdown #19584 CC tickets): 
     - Label text: Mobile Body Bold
     - Border: 2px solid red secondary dark, #CD2026
     - Error text: Mobile Body Bold, #CD2026
4. Create UI for the following field-level errors below the specified field:
     - Message: "The message cannot be blank"
5. The field-level error should appear when any of the following occur:
     - A user taps into a required input field and leaves the field without completing it
     - A user tries to send the form without interacting with a required field. In this case, the error message displays when "Send" is selected
7. The field-level error should disappear when any of the following occur:
     - User begins typing into the field
     - User exits the form

## Designs
No designs for the field error UI. Refer to Edit Address form for a similar UX/UI. 
Reply to Message screen w/o errors: https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447461529

## Discovery ticket / documentation
https://docs.google.com/document/d/1LUBg1a0dEjQb4aKXimWYEq9DXNQOe35Etq8MzroAuJ4/edit?ts=6065f684#
https://github.com/department-of-veterans-affairs/va.gov-team/issues/17044

## Accessibility Implementation Guidelines

**Error state:**
Formfield: “{label}. error - {Validation text}.”
Formfield/Message: “{label, hint message}. error - {Validation text}.”
Dropdown:“{label}. error - {Validation text}.”
Dropdown/Message“{label, hint message}. error - {Validation text}.”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/4/2021 - Looks good on Android and iOS.  Closing.
