### ISSUE TITLE
Hook up attachments flow to Reply form

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#22904]
## Acceptance Criteria
1. In the **Reply to Message** form, hook up the attachments upload flow that's been implemented for the **Compose a Message** form
     - Starting point: add routing for the "Add files" button on the Reply form
2. Include the following pages/functionality:
     - Attachment page | no file added (#20139)
     - Attach file from action sheet (#20813)
     - View attachment page with file added (#20814)
     - Attach file to form (#22676)
     - Confirmation screen to remove attachment (#20815)
     - Remove attachment from the form (#22671)
3. Include any upload error states that have already been implemented

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/4/2021 - Looks good on iOS and Android.  Closing.
