### ISSUE TITLE
VRRAP: Add "Need Help" content to introduction page.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22924]
As an EDU developer, I need to add the need help footer content to the vrrap introduction page so that the form is consistent with other EDU forms on VA.gov.

## Assumptions:
1. VRRAP introduction page on staging: https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction

## Acceptance Criteria:
1. The content in SA1 is displayed on the VRRAP introduction page below the OMB details.

## Supporting Artifacts:
1. AC1 Screenshot
<img width="665" alt="Screen Shot 2021-04-08 at 9 58 48 AM" src="https://user-images.githubusercontent.com/48260534/114039814-0fd01480-9851-11eb-93bb-187b3652b63a.png">

**Comment by dmccurdybah** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16708

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/1673)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now on Staging. Closing this issue
