### ISSUE TITLE
VRRAP: "Start the education application" button scrolling to top of page

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#22925]
## Steps to reproduce:

1. Navigate to https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction
2. Select "Sign in or create an account"
3. Use user from https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv to sign in
4. Select "Start the education application"
5. Observe it scroll to the top of the page

https://user-images.githubusercontent.com/48804582/114042347-5757a000-9853-11eb-90cc-848f4e9b6d95.mov

## Expected results:
Starts application

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16724

**Comment by delli-gatti-michael** [comment]
The fix for this is now live on Staging. Closing this issue

**Comment by delli-gatti-michael** [comment]
Reopening as some users are still unable to access the form

**Comment by delli-gatti-michael** [comment]
The form can now be accessed by any user. Closing this issue
