### ISSUE TITLE
CT: CENTRAL TEXAS COLLEGE MAIN CAMPUS profile page doesn't load

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#22920]
## Steps to reproduce:

1. Navigate to https://www.va.gov/gi-bill-comparison-tool/profile/14806143
2. Profile page doesn't load

Error in console

![Screen Shot 2021-04-08 at 7.36.43 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6c815c35-bfef-4175-9979-d9fa4575cdb0)

## Expected results:

1. Page loads

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
This fix is live. Closing this issue
