### ISSUE TITLE
sitewide 508-defect-2 [SCREENREADER, FOCUS]: NVDA bug causes search results to not be announced on focus

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#22927]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh and Trevor

## Details

@zacharymorel and I spent time investigating [ticket 18398](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18398) and determined that the issue surrounding search results _not_ being announced was specific to a [NVDA bug as documented on their github here](https://github.com/nvaccess/nvda/issues/5825).

NVDA won't announce contents of a newly focused element if:
- it's originally hidden and made visible
- replaces an item within the same position
- and receives focus

That being said, this is still an accessibility barrier to Veterans who may use NVDA (which is the second most used screen reader and arguably the most accessible given that its free). 

We plan to convene with @1Copenut and @noahgelman to find a way around this bug in the meantime.

## Acceptance Criteria

- [ ] NVDA announces the `h2` search results

## Environment

Firefox and NVDA
Find a form search results

**Comment by zacharymorel** [comment]
Whoo. Alright, I am ready for a work around to be found.

**Comment by laflannery** [comment]
@joshkimux The search results on Find a Form are being announced for me correctly, but the NVDA upstream issue is still open.  I can't figure out if we had done a work around (that would need to perhaps be undone later) or if this just works now?  Are you able to let me know if this can be closed?

**Comment by laflannery** [comment]
Thanks, I'll close.

For possible future reference/documentation, I _think_ looking at the NVDA issue, it might be a case of they fixed some of the bug but maybe not all super specific cases? There was some reopening of multiple tickets.  

I confirmed on Global, Resources, and Find a Form search that with NVDA 2022.2 and Chrome Version 105.0.5195.127 The updated search results (i.e. Showing 21-30) were announced correctly when the user clicked to the next page in the pagination.
