### ISSUE TITLE
VRRAP: Make address details not required.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22939]
As an EDU developer, I need to make the address fields not required so that the form is compliant with federal law.

## Assumptions:
1. The form is found on staging here: https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction
2. This update is **_ONLY_** for the VRRAP form and is not intended to be used on other forms.

## Acceptance Criteria:
1. None of the mailing address fields are required:
    a. Country
    b. Street address
    c. Street address line 2
    d. City
    e. State/Province/Region
    f. Postal code

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
vets-json-schema PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/585

**Comment by dmccurdybah** [comment]
vets-api PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6524

vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16717

**Comment by zurbergram** [comment]
When clicking submit without entering any information 
![Screen Shot 2021-04-09 at 11.40.07 AM.png](https://images.zenhubusercontent.com/5bfd74885cb43a45a18acb1b/ff574306-fa52-4861-ab61-9965fa3f85cd)

**Comment by delli-gatti-michael** [comment]
Changes are on staging. Closing this issue

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1789)
