### ISSUE TITLE
Add Research insights sections to the component documentation

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#22938]
- [x] Create product outline
- [ ] Get outline approved
- [ ] Create tickets on each component, properly label
- [ ] Create a link to ticket on each component page

**Comment by GnatalieH** [comment]
I have included a Resources section in the [new component template](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/559). This section would include links to research that is relevant to the component. I am open to renaming this section to "Research", but thought Resources might be a more generic bucket to organize additional items. This may be a good question for the DSC.

**Comment by caw310** [comment]
Closing since link to research has been added to DS components.
