### ISSUE TITLE
General Analytics Request for Authenticated Exp - Errors not coming through on GA dashboard for Direct Deposit for Edu

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22941]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- @erikphansen , @ajakabcin @Samara-Strauss 

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?  

    _this adds context for the data_
    - Authenticated Experience, Direct Deposit for Edu
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
after 03/31/21

## Link to Metrics
https://analytics.google.com/analytics/web/?authuser=0#/dashboard/qEpkRFroTOSTpgaBDHXK4A/a50123418w177519031p176188361/

## Additional Comments
More details about the issue we're seeing documented in #22629 , specifically Erik's comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22629#issuecomment-815953260)

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by laurensimpson14** [comment]
@erikphansen I don't see any `Profile Save Failure - EDU Direct Deposit Information` events being collected in GA, and I think your hypothesis about it being due to the lack of an `error-key` is likely correct. From your comment on ticket #22629 it looks like that change is in progress.

**Comment by erikphansen** [comment]
@laurensimpson14 🤞 hopefully it'll work. But also hopefully there are very few errors!

**Comment by erikphansen** [comment]
Closing this as errors are now showing up in GA.

This ticket was created as a follow-up: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23312
