### ISSUE TITLE
Specs are performed by GitHub Actions

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#22944]
We are currently running specs in Jenkins. We are moving to GitHub Actions for our CI pipeline.

## AC
- [x] All tests (rspec) are ran via GitHub Actions
- [x] Coverage reports are generated and fail the build via GitHub Actions
- [x] [Stretch] Parallelize specs 

Moved to separate cards:
- [x] [Move tests to self-hosted runner](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/23197)
- [x] [Implement Bridged solution for failing deploy if CI red + Remove testing from Jenkins](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/23096)

**Comment by jeff2d2** [comment]
Waiting on ops for this before merging and closing
