### ISSUE TITLE
Accordion Web Component migration 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#22945]
## Product Outline
 https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/design-system/web-component-pilot.md

## High Level User Story/ies
As a VFS team, I want to be using the accordion web component so that I am using the most recent version

## Hypothesis or Bet
If we update accordions in use with the accordion web component, then we can monitor usage. 

## OKR
Updates to DS

## Definition of done
Update current instances of accordion with the accordion web component.

**Comment by bkjohnson** [comment]
Closing in favor of #22946
