### ISSUE TITLE
Add Click Tracking to Best Bets - Front End

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#22949]
## Description

Currently click tracking is not implemented on best bets. This issue is to accomplish the required FE and BE lift to connect Best Bets to our existing click tracking endpoint. Our hypothesis is that best bets are incredibly impactful and valuable to the overall user experience and we expect to see high engagement.

## Tasks

- [x] Update the Front End to pass in a module code that is 'BOOS' when the user clicks on a best bet, and 'I14Y' when the user clicks on a standard search result

    // const moduleCode = bestBet ? 'BOOS' : 'I14Y';

## Definition of Done

- [x] Best Bets are tracking clicks appropriately.

**Comment by srsuddath** [comment]
PR has been merged!
