### ISSUE TITLE
Access for John Hashimoto - DSVA Product Owner for Public Website

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#22948]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Chris Johnston
- Please provide your name.
   > John Hashimoto
- Please Provide your email.
   > john.hashimoto@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I'm DSVA/OCTO-DE Product Owner for three unauth teams -- Public Website, Decision Tools and Search.

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGomrAn1T6vjskXiCudxEzXJ9hVafukBH5sU/e0iIuZp/J3lizcLnFkKFO2CXgpQe7S6vzIqbLB4kUq9xT8LH+Lmg4A0jcjBVROjZuI/uhHB7OmH0vOPXaPccn3NLH88JFy4LnTPgt6C3Okz6ajRuwbDLMEOR6ov1NtXnty9/zI1CltLj7p/ZjvH0MhX1ygx4DIjb6CS3IiBoDSkEFCu/QmVHEz7Ne+wshI7tk68HwYIKQg2XYsDQqJs6H/QvC5OP/y9fiGV1y+HYLY15Tsln/0YsQXD0r/kwWHntXDJbSiRVWYPAYBr6055BZVVxeXw/yxzKqsRQ+SKRtk2QjS/dcKn5SnJfRRxH1sW7nHSKZRpRUJ48XqwV6WdttFZMN5vTseRr3iTPkBD225ak= VACOHashiJ@VAC

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by johnhashva** [comment]
Hi -- looking for an update for this request as we want to use Socks for product reviews prior to staging (FYSA: @drorva and @brianalloyd )

**Comment by johnhashva** [comment]
Hi @mydesignrocks -- can you provide an update on the status of this request?

**Comment by mleclerc00** [comment]
Hi @johnhashva 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

Let me know if you are able to set everything up so I can close out this ticket and if you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by johnhashva** [comment]
@brianalloyd and @kelsonic Threading you in here to let you know I'm set up -- so I'll be ready to give this a whirl after Brian is settled in with his Socks connect.

**Comment by johnhashva** [comment]
@jbritt ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCk9o53ri0U5R6ImI7dkob8+8gLpIDzhxOwl5gPq70ZBp9iSs2n3WDJ3e4p/dBD9Xv5lDRl6j4EAsyrMQ6rm+V3OHfmdstBICNLAxGPTNktvFmvFWCAmwNRP0UCCatF8WovRn/b0Y3yLSjvpjS8j0GJy6Fna5u1WZdrNCWd6rCmLMsEuzqpK3RrCBdYhRluFu5VK2h99H3y/Wt3gVNdFOhguVGk/vWAuXcrpnrxa7oPVEU6RdpCNTh3vnmPugfHSnv/xEZFwgtGlxexhnCKrNLpmvrh1O6bYolNHT6tubwcsufrrjFmF9KNcKKIAK2GYGAQGE8mokcj0idTFT0VL4W6t+pc05CjIfsWi6OLlC4+h44rsK10jXc5AnWswn6MnR9G8ocP3EpvWHAxjNEmVvTS6KAKZlYWmTHN8LI1pv9a5FhQolwD/tT70ME9gdXlBhBNTzeQgvmRX0lGA6qRaStds2PLQ0cNxnvON/sqqCJQ6MElIfFMW6p04sKISj/hoS8= johnhashimoto@Johns-MBP.attlocal.net

**Comment by jbritt1** [comment]
> @jbritt Howdy, I had to program a new key -- can you set this up for me?
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCk9o53ri0U5R6ImI7dkob8+8gLpIDzhxOwl5gPq70ZBp9iSs2n3WDJ3e4p/dBD9Xv5lDRl6j4EAsyrMQ6rm+V3OHfmdstBICNLAxGPTNktvFmvFWCAmwNRP0UCCatF8WovRn/b0Y3yLSjvpjS8j0GJy6Fna5u1WZdrNCWd6rCmLMsEuzqpK3RrCBdYhRluFu5VK2h99H3y/Wt3gVNdFOhguVGk/vWAuXcrpnrxa7oPVEU6RdpCNTh3vnmPugfHSnv/xEZFwgtGlxexhnCKrNLpmvrh1O6bYolNHT6tubwcsufrrjFmF9KNcKKIAK2GYGAQGE8mokcj0idTFT0VL4W6t+pc05CjIfsWi6OLlC4+h44rsK10jXc5AnWswn6MnR9G8ocP3EpvWHAxjNEmVvTS6KAKZlYWmTHN8LI1pv9a5FhQolwD/tT70ME9gdXlBhBNTzeQgvmRX0lGA6qRaStds2PLQ0cNxnvON/sqqCJQ6MElIfFMW6p04sKISj/hoS8= [johnhashimoto@Johns-MBP.attlocal.net](mailto:johnhashimoto@Johns-MBP.attlocal.net)

To be clear, you want to replace the old one we have on file for you with this new value... correct?

**Comment by jbritt1** [comment]
Pull request to update key merged, new key should be deployed in 5-10 minutes. Pre-emptively closing, but feel free to reopen if any issues arise.
