### ISSUE TITLE
[FE] My VA bug: "View disability rating" link showing to user who doesn't have a disability rating

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#22957]
## Background

In the [nametag documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md#states), the "View disability rating" link should not show if we detect someone doesn't have a rating. The link should only show if (1) someone has a rating or (2) if we can't connect to the endpoint and therefore can't determine either way whether someone has a rating or not.

For user 377, I am seeing the "View disability rating" link, yet this user does not have a rating on file. We should not see this link for this user.

<img width="1280" alt="Screen Shot 2021-04-08 at 2 58 39 PM" src="https://user-images.githubusercontent.com/34068740/114090139-08c2f980-9885-11eb-82d7-e79a612782b7.png">

<img width="915" alt="Screen Shot 2021-04-08 at 3 22 55 PM" src="https://user-images.githubusercontent.com/34068740/114090146-0bbdea00-9885-11eb-9fc5-5c6af0283caa.png">

## Tasks

- [ ] Do not show the disability rating if the call to `GET disability_compensation_form/rating_info` results in a 403 like:

```json
{
  "errors": [
    {
      "title": "Forbidden",
      "detail": "User does not have access to the requested resource",
      "code": "403",
      "status": "403"
    }
  ]
}
```

**Comment by Samara-Strauss** [comment]
cc/ @tressaellen @ajakabcin for awareness

**Comment by erikphansen** [comment]
This could be a legit bug. But you could be seeing the error state when there is an error fetching the disability rating. We'll check it out

**Comment by Samara-Strauss** [comment]
@erikphansen I guess I'm not sure what the error state in the actual disability rating tool looks like. Given that the messaging says "we don't have a disability rating for you," I assumed that there wasn't a rating on file and not that the site was unable to connect to the endpoint. But yeah, I don't know for sure. Let me know what you find!

**Comment by erikphansen** [comment]
The user data for 377 seems weird. They are flagged as a VA patient, but also do not exist in EMI so they have no veteran records.

<details>
  <summary>**User 377's full `GET user` response:**</summary>

```
{
  "data": {
    "id": "",
    "type": "users_scaffolds",
    "attributes": {
      "services": [
        "facilities",
        "hca",
        "edu-benefits",
        "form-save-in-progress",
        "form-prefill",
        "rx",
        "messaging",
        "health-records",
        "add-person",
        "user-profile",
        "appeals-status",
        "identity-proofed",
        "vet360"
      ],
      "account": { "accountUuid": "ba0cda35-41d8-4431-8129-559cd9debba1" },
      "profile": {
        "email": "vets.gov.user+377@gmail.com",
        "firstName": "KRISTIE",
        "middleName": null,
        "lastName": "GPSYSRXTESTONE",
        "birthDate": "1971-10-27",
        "gender": "F",
        "zip": "94103",
        "lastSignedIn": "2021-04-08T21:43:16.347Z",
        "loa": { "current": 3, "highest": 3 },
        "multifactor": true,
        "verified": true,
        "signIn": { "serviceName": "idme", "accountType": "N/A" },
        "authnContext": "http://idmanagement.gov/ns/assurance/loa/3"
      },
      "vaProfile": {
        "status": "OK",
        "birthDate": "19711027",
        "familyName": "Gpsysrxtestone",
        "gender": "F",
        "givenNames": ["Kristie"],
        "isCernerPatient": false,
        "facilities": [{ "facilityId": "989", "isCerner": false }],
        "vaPatient": true,
        "mhvAccountState": "OK"
      },
      "veteranStatus": null,
      "inProgressForms": [],
      "prefillsAvailable": [
        "21-686C",
        "40-10007",
        "0873",
        "22-1990",
        "22-1990N",
        "22-1990E",
        "22-1995",
        "22-5490",
        "22-5495",
        "22-0993",
        "22-0994",
        "FEEDBACK-TOOL",
        "22-10203",
        "21-526EZ",
        "1010ez",
        "21P-530",
        "21P-527EZ",
        "686C-674",
        "20-0996",
        "10182",
        "MDOT",
        "5655",
        "28-8832",
        "28-1900"
      ],
      "vet360ContactInformation": {
        "email": null,
        "residentialAddress": null,
        "mailingAddress": null,
        "mobilePhone": null,
        "homePhone": null,
        "workPhone": null,
        "temporaryPhone": null,
        "faxNumber": null,
        "textPermission": null
      },
      "session": {
        "ssoe": true,
        "transactionid": "H/yqD4tWaviY4RrP9/15GgEKpsfsXOAQuxjp0lWN0C8="
      }
    }
  },
  "meta": {
    "errors": [
      {
        "externalService": "EMIS",
        "startTime": "2021-04-08T21:49:55Z",
        "endTime": null,
        "description": "EMISRedis::VeteranStatus::RecordNotFound, NOT_FOUND",
        "status": 404
      }
    ]
  }
}
```

</details>

But that might be besides the point.

The real work here is: Do not show the disability rating if the call to `GET disability_compensation_form/rating_info` results in a 403 like:

```
{
  "errors": [
    {
      "title": "Forbidden",
      "detail": "User does not have access to the requested resource",
      "code": "403",
      "status": "403"
    }
  ]
}
```

I will update the original message in this ticket to reflect that.

**Comment by Samara-Strauss** [comment]
Sounds good, and sorry that this is partially weirdness with how a staging user is set up :-/ There's nothing I can do about the "not in EMI" part of things given that this is a health care user and we don't have a way for a user in one backend system to get into another (because of VA silos 😭 ).

**Comment by erikphansen** [comment]
This is ready to validate.

**Comment by ajakabcin** [comment]
Confirmed on staging
