### ISSUE TITLE
Offboarding of Jasmin Smith

### ISSUE THREAD

**Issue by tradle51** [department-of-veterans-affairs/va.gov-team#22965]
# Instructions
Fill out name of individual and *Description* section below.

# Description
- Please provide the name of the individual needing offboarded.
   > Jasmin Smith

- Please provide the name of their team, their role on that team, expected last day, and the name of the company they work for.
   > Team: VA Notify; Role: Quality Analyst; Last Day: 3/12; Company: ThoughtWorks, Inc.

- Please provide any type of access they may have and their GitHub username. 
  > jsmithVA; access types unknown.
  
 
## AC
 - [X] Remove global/config.yml / SOCKS Access removed (if applicable) 
  > That file (global/config.yml) has a list of email addresses in groups. The email address in those groups is used to lookup their key. Keys are stored in files named with the user’s email address. So, you need to remove the file and their entry in that list to be finished.
 - [x] AWS Access removed  (if applicable) 
  > Since there are multible accounts please ensure all are check ie test access.
 - [x] DSVA Slack (if applicable) 
  > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] User removed from the VA GitHub Org
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D). 
 - [x] Pagerduty access removed (if applicable) 
 - [x] Sentry access removed (if applicable)
 - [x] Google analytics, and Domo access removed (if applicable) 
 
 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support , @department-of-veterans-affairs/vsp-analytics-insights, @KevinMHoffmanUSDS, @drorva

**Comment by bsmartin-ep** [comment]
No GA, GTM, or DOMO access for Jasmin Smith to remove.

**Comment by mydesignrocks** [comment]
No AWS access for Jasmin Smith

**Comment by tradle51** [comment]
@bsmartin-ep, @joanneesteban, @mydesignrocks  -  quick question.  When the tasks on this issue are done, will Jasmine be removed from the VA, or will a subsequent issue (like [this](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D) be needed for that purpose?

**Comment by tradle51** [comment]
> @bsmartin-ep, @joanneesteban, @mydesignrocks - quick question. When the tasks on this issue are done, will Jasmine be removed from the VA, or will a subsequent issue (like [this](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19%2C+michelecmiller&labels=remove-user&template=remove-users-from-va-organization.md&title=REMOVE+USER+FROM+ORG+-+%5BUSERNAME%5D)) be needed for that purpose?

I should have read my own issue.  Apologies, all.  https://github.com/department-of-veterans-affairs/github-user-requests/issues/6680 created for the 4th bullet in the AC list.

**Comment by mleclerc00** [comment]
no pagerduty/sentry and not part of the VA GitHub Org

closing this ticket
