### ISSUE TITLE
IA Feedback - Staging Review - CH 31 VR&E

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#22961]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- **URL:**  URL is not accurate.  Must be updated to approved URL to meet standards: `www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/`
- **Entry points:**  There were 5 primary entry points recommended for this form, plus additional options for consideration.  Only one of the primary entry points is implemented in staging ([on the VRE page](https://staging.va.gov/careers-employment/vocational-rehabilitation/)).  The additional entry points will need to be implemented preferably before launch, if not immediately after.  Please be sure you are coordinating with the Sitewide content team to ensure all entry points are implemented as recommended in [the IA request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-chapt31.md).
- 

**Should:**
- **User flow:** When you select "neither of these" in the first wizard question, the orientation slideshow appears, even though the user is not eligible for VRE.  The orientation slideshow should not be displayed if the user is not eligible, or users may feel they are receiving conflicting/confusing information. 
-  **User flow:** Once the orientation slideshow is displayed, it does not go away if you change any answers in the wizard.  This can result in seeing the slideshow when you are not eligible
-  **User flow:** Similar to above, once the "Thank you for viewing" message and action link to apply are displayed, they do not go away if you change any answers in the wizard.  This risks providing users conflicting messaging and access to the application when they may not be eligible for it.  
- 

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by jason-gcio** [comment]
Hi @mnorthuis - thanks again for you help this afternoon.

We are amending the url shortly per [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23014), and wanted to come back to the other piece of **must* feedback; the entry pages.  

We have them feature toggled here and wanted to share some notes...
- There are a few entrances to the CH31 application that we already have feature toggles in place for in collaboration with Public websites:
  - [VR&E Reemployment track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/reemployment/)
  - [VR&E Rapid Access to Employment track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/rapid-access-to-employment/)
  - [VR&E Self-Employment track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment/)
  - [VR&E Employment Through Long-Term Services track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/long-term-services/)
  - [VR&E Independent Living track](https://www.va.gov/careers-employment/vocational-rehabilitation/programs/independent-living/)
  - [How to apply for Veteran Readiness and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/) 
  - [Eligibility for Veteran Readiness and Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/) 

Does that align with what you were thinking for this?

**Comment by mnorthuis** [comment]
Hi, those content pages align with my recommendations.  In addition, there is also a recommendation to add an option to the top nav, left nav and Careers hub page.    Can you attach the issue for the Public Websites/Sitewide Content team or tag me in that issue?

**Comment by jason-gcio** [comment]
Here is that PubWeb intake ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23016
