### ISSUE TITLE
Design Feedback - Staging Review eBenefits - VRE CH31

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#22969]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Change green apply button to green action link

**Should:**
- Add a title to the card![Screen Shot 2021-04-09 at 2.03.11 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/ebaedeb4-3f2d-4428-a68b-8512ce35a4fd)

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by jason-gcio** [comment]
@vhenry07 - can we chat about the **Should** feedback in this ticket?  I want to make sure we are addressing titles in wizards correctly and figured I would start with you.  Prolly need to ask a content person as well but starting here.

You know of other wizards that have titles in their cards for wizard dead-end points?

**Comment by vhenry07** [comment]
@jason-gcio Here are a couple examples, though not certain they fit your use case exactly: 
https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction

**Comment by jason-gcio** [comment]
Hmm, yours don't have titles on the cards either...ok, thanks!

@allison0034 - I need some help seeing what an example of titles on these cards might look like (feedback from **Should**👆).  If there aren't any out there "in-the-wild" I can certainly make an example...just want to make sure we are making them correctly.

**Comment by allison0034** [comment]
@jason-gcio @vhenry07 you are correct, currently some wizards in production do not have card titles. If you look at [the wizard](https://design.va.gov/patterns/wizards), this card should not only have a card title but it should in an alert style. Sorry, I missed the alert styles. I put it as should because I know in production we have examples without the alert styles/titles and we are retiring the wizard.

**Comment by jason-gcio** [comment]
I remember those alert styles - I think we were putting this together when those conversations were being had.  We'll move them towards alerts but may take a little longer as we get Content to approve language.

**Comment by jason-gcio** [comment]
And, thank you @allison0034!

**Comment by jason-gcio** [comment]
Future @jason-gcio: **Must* is in progress, **Should** needs a separate ticket to move the dead-end cards to alerts + language.

**Comment by allison0034** [comment]
Thank you @jason-gcio !
