### ISSUE TITLE
[FE] My VA - (Pre QA) My VA shows "undefined" message count when loading secure messages

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#22964]
We should be showing a loading spinner while we are still waiting for the secure messages API calls to resolve.

https://user-images.githubusercontent.com/20728956/114100556-4faaf200-9879-11eb-8e24-910e2f3a7010.mp4

**Comment by ajakabcin** [comment]
confirmed fixed on staging
