### ISSUE TITLE
VRRAP: Update application with OMB details

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#22970]
As a developer, I need to update the VRRAP OMB content that so that it is compliant with the registration of the form with OMB.

## Assumptions:
1. The form is found on staging here: https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction
2. This privacy act statement update is **_ONLY_** for the VRRAP form and is not intended to be used on other forms.

## Acceptance Criteria
1. The respondent burden on the introduction page is: 10 minutes
2. The OMB Control # on the introduction page is:  2900-0885
3. The Expiration Date on the introduction page is:  October 31, 2021
4. The content in the privacy act statement modal is:

> Privacy Act Statement {h3}

> **Privacy Act Notice:** This form under §8006 of Public Law 117-2 (H.R. 1319) authorizes VA to implement the Veteran Rapid Retraining Assistance Program (VRRAP) which provides eligible Veterans impacted by the COVID-19 pandemic with the opportunity to pursue a covered program of education in a high technology - high demand occupation. The responses you submit are considered confidential (38 U.S.C. 5701). VA may disclose the information that you provide, including Social Security numbers (SSN), outside VA if the disclosure is authorized under the Privacy Act, including the routine uses identified in the VA system of records, 58VA21/22/28, Compensation, Pension, Education, and Vocational Rehabilitation and Employment Records - VA, published in the Federal Register. The requested information is considered relevant and necessary to determine maximum benefits under the law. Your obligation to respond is required in order to obtain or retain education benefits. Giving us your SSN account information is voluntary. Refusal to provide your SSN by itself will not result in the denial of benefits. The VA will not deny an individual benefits for refusing to provide his or her SSN unless the disclosure of the SSN is required by Federal Statute of law enacted before January 1, 1975 and still in effect. Any information provided by applicants may be subject to verification through computer matching programs with other agencies.
> 
> **Respondent Burden:** We need this information to determine your ability to participate in the Veteran Rapid Retraining Assistance Program, 38 U.S.C. 3702 (d) and 38 CFR 36.4344. Title 38, United States Code, allows us to ask for this information. We estimate that you will need an average of 10 minutes to review the instructions, find the information, and complete this form. VA cannot conduct or sponsor a collection of information unless a valid OMB control number is displayed. You are not required to respond to a collection of information if this number is not displayed. Valid OMB control numbers can be located on the OMB Internet Page at [www.reginfo.gov/public/do/PRAMain](url). If desired, you can call [800-827-1000](url) to get information on where to send comments or suggestions about this form.

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/e7065074df8121adbb1b8bb64dd8af85e74e3dd8/products/education-careers/application/VRRAP/design/content-doc.md)

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1672)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are staging. closing this issues
