### ISSUE TITLE
[PM] Combined Profile and Account: Determine analytics approach

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2298]
Epic #2086

- [x] Work with analytics team to figure out what analytics we can use to measure success for combining profile and account

**Comment by Samara-Strauss** [comment]
Hi Joanne, Jon, and Nedie — 

Thanks for meeting with us yesterday to talk about our potential analytics approach for measuring success with the combine profile and account project. I'm creating this to-do so we can keep track of this conversation and regroup as needed.

These are my big takeaways from yesterdays call:

- We can potentially measure increased visits to the new profile/account as a metric for success, though our goal is to get the *right* people to this section more so than seeing an increase in the amount of unique visits. However, I think we can pretty safely say we don't want to see a reduced number of people to this new combined profile/account section from the amount of traffic we currently see to the separate profile and account pages.
- We would love to be able to measure reduced time to task completion for things like changing your address or updating your direct deposit information, but we don't have a way to measure time to task completion right now.
- We could potentially use an increase in people verifying their identity or adding 2FA as a metric for success since these things should be easier to find in this new section. However, it's worth noting we do prompt people to take these actions elsewhere, so we would have to measure this through increased link clicks from this section.
- We may be able to use exit rate to measure success, but it was not clear to me how we would do this.
- Reduction in profile-related calls to the call center could be a metric for success.

**To-dos**

- I think the only to-do from this meeting was that Nedie and Jon were going to take some time to think through this problem, and we'll regroup when there's more to discuss.

**Comment by lkoenigsberg** [comment]
This is great stuff!  Please also consider 

- Tracking both success and failures at a feature level (address, dd, etc.), getting as granular as possible.  Failures are super helpful in knowing if we have problems and also can be used as a KPI measure...reduce failure rates, or keep failure rates to x%
- Reporting dashboard for all things profile.  Easy and fast way to view what's happening for profile as a whole.
- Flow reports for key interactions.  Ties to the first bullet a bit.

**Comment by Samara-Strauss** [comment]
Following up — @nedierecel @joanneesteban @jonwehausen, now that you've had a week to noodle on things, any additional thoughts on how we can approach success metrics for this project?

**Comment by nedierecel** [comment]
@Samara-Strauss @jonwehausen and I met this AM, but we're going to set up some additional internal time to brainstorm the KPIs against the user intent.

**Comment by Samara-Strauss** [comment]
Thanks for the update, @nedierecel!

**Comment by Samara-Strauss** [comment]
Closing. Finall metrics were figured out in #2329
