### ISSUE TITLE
[FE] My VA - (Pre QA) Incorrect section header for "Apply for VA benefits"

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22998]
The last section header on the page should read "Apply for VA benefits" (according to mockups), however on staging the section header reads "Apply for benefits"

**Current State**
![22998 Apply for benefits incorrect section header](https://user-images.githubusercontent.com/45603961/114220713-53eb1400-993a-11eb-96d9-0cb1eb8bcd14.png)

**Desired State**
As seen in mockups in [Invision](https://vsateams.invisionapp.com/share/SH10HT8JCKYM#/screens/448032781_My_VA_Desktop_Everything_Copy) Note that the header should include the word "VA"
![22998 Invision screenshot correct section header](https://user-images.githubusercontent.com/45603961/114220983-ab897f80-993a-11eb-81e7-10de22ef827c.png)

**Comment by tressaellen** [comment]
Just double checked - Apply for VA benefits is the correct heading. :)

**Comment by erikphansen** [comment]
[PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/16789) so this can be validated on staging soon.

**Comment by ajakabcin** [comment]
Confirmed on staging thanks!
