### ISSUE TITLE
User Feedback Survey  | Language Assistance English Page | Request 3 out of 3 | C+L

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#22997]
### What this form is for

Use this template to request adding the Medallia Survey to your product.

Read more about Medallia link & how to request a survey link

### Description

Please provide the name(s) of your product and a high level description of your product.

The new Language Assistance page (English) is live. We would like to add the survey to this page in English.

### Launch Date

Already in production

### Production URLs

Please provide Production URLs

https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/

### Please leave the following blank

Acceptance Criteria

 URLs added & QA'd with the Medallia survey

**Comment by SKasimow** [comment]
Hi @DanielleThierryUSDSVA -  it may be another month or so before "custom" surveys can be supported, but wanted to get the text translations on the docket and have ready to go.

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason - while we're waiting for the translations, I noticed that the survey order I show above (from production)has the first and second q's vs doc in Github:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md

Out of an abundance of caution (since it takes us some time to get translations), I wanted to confirm which is the correct order - the below listing from Github? Or the above text in the ticket which is from production?
(I just don't want us trying to figure out last minute how to move Tagalog q's around!)

Github doc:

1. What task were you trying to do today?
[Free text]
2. Were you able to do your task today?
Yes
No
3. What is your overall satisfaction with this site?
1 = Very dissatisfied
5 = Very satisfied

**Comment by SKasimow** [comment]
Spanish:

[encuesta]
¿Pudo completar su tarea hoy?
Sí
 No
¿Cuál tarea estaba tratando de hacer hoy?
¿Qué tan satisfecho está usted con este sitio?
[escala: 1, 2, 3, 4, 5] [comienzo de la escala] Muy insatisfecho [fin de la escala] Muy satisfecho
[botón 1] Cerrar [botón 2] Envío

**Comment by jwoodman5** [comment]
Hey @SKasimow Nice catch. The screenshot is correct and looks like your most recent comment aligns with that. Thanks for double-checking! We will get this one started.

**Comment by jwoodman5** [comment]
@SKasimow The request has been officially submitted to Medallia. We are working through an update to the standard Feedback survey, which will need to be applied here as well. It will be a notice for respondents to _not_ enter any PII/PHI in the free-form text field. Once we are settled on the wording (with Medallia), we will work with you for translation.

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason - sounds good; thanks for the update!


cc: @DanielleThierryUSDSVA

**Comment by jwoodman5** [comment]
Hi @SKasimow - The Spanish Feedback survey is on staging and ready for your review here:

https://staging.va.gov/coronavirus-veteran-frequently-asked-questions-esp/

https://staging.va.gov/health-care/covid-19-vaccine-esp/

Please check them out and if you approve, we will push to production. Thanks!

**Comment by jwoodman5** [comment]
@SKasimow We made the translation updates and the survey is ready for staging review again. Thanks!
https://staging.va.gov/coronavirus-veteran-frequently-asked-questions-esp/

**Comment by SKasimow** [comment]
@jwoodman5 Hi Jason - looks good to me! Can we push to prod today?

**Comment by jwoodman5** [comment]
Request to add the VFS Feedback button survey here has been submitted.  https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/?

**Comment by jwoodman5** [comment]
@SKasimow Your brand new survey is live! Please have a look and let me know if you have any questions or concerns. Thanks!

**Comment by SKasimow** [comment]
Thank you @jwoodman5! Appreciate the quick turn-around on this.
