### ISSUE TITLE
[FE] My VA - (Pre QA) "What benefits does VA offer?" menu in wrong location

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22996]
Currently on staging the the link and corresponding expanding menu appear below the Disability compensation and Education and training modules. The link and menu should appear directly below the section header "Apply for benefits"

**Current State**
![22996 Incorrect placement of What benes does VA offer](https://user-images.githubusercontent.com/45603961/114219954-5e58de00-9939-11eb-98bb-e18f101291bb.png)

**Desired State**
As seen in mockups in [Invision](https://vsateams.invisionapp.com/share/SH10HT8JCKYM#/screens/448032781_My_VA_Desktop_Everything_Copy) - Note the desired location for this text and menu is immediately below the section header:
![22996 Invision referece for correct placement of What benes does the VA offer link](https://user-images.githubusercontent.com/45603961/114219760-146ff800-9939-11eb-87fb-a9dfe45e7664.png)

**Comment by erikphansen** [comment]
[PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/16789) so this can be validated on staging soon.

**Comment by ajakabcin** [comment]
Confirmed on staging
