### ISSUE TITLE
Discuss flaky test patterns with codeowners

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#23006]
## Details 

Based on patterns identified in #23004, reach out to individuals/teams that show up more frequently in the flaky test spreadsheet. 

Discuss via Slack or meeting: 

* What patterns have we identified with these tests? What does the codeowner think might be contributing to the issues? 
* Has the codeowner tried rewriting their tests due to flakiness or not yet? 
* Additional questions to come 

Goal of ticket is information gathering, not necessarily requesting that teams address their tests — as we do request that teams address their tests, we may need to loop in PMs in terms of writing tickets and prioritizing work. 

## Acceptance Criteria 

- [x] We've talked to codeowners with recurring flaky test issues 
- [x] Findings are documented 
- [x] Path identified to resolve these flaky (note whether teams have committed to address tests as part of our convos or not so that we can follow up later)

**Comment by k80bowman** [comment]
I have spoken to Robin Garrison and Erik Hansen about test quick fixes. Robin was able to get a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17153) merged very quickly to fix the test I had highlighted for him. Erik wasn't satisfied with the quick fix I recommended and [wanted to dig in more](https://dsva.slack.com/archives/C5HP4GN3F/p1620840168267600?thread_ts=1620757260.254500&cid=C5HP4GN3F). He was not only able to come up with a fix for the test I had highlighted, but for a couple of other tests that had been failing intermittently as well. He also found that tests that are mocking fetch but not resetting it could be causing significant problems. I'm creating a card to look into fixing that at the platform level (it's not going to be a quick fix). Over the course of our discussion we talked about a couple of the patterns we both had seen in flaky tests. Based on that discussion and the discussions I had with Eugene, Jeff Balboni, and Chris V. I think we are good to close this card.

In the process of these discussions I learned several important things that changed how I think we should proceed:
1. We have a mix of unit and integration tests in our spec files. This isn't necessarily a problem, but it's definitely something to be aware of.
2. Some teams have developed their own guidelines for unit/integration testing.
3. While some teams are paying attention to their flaky unit tests and are getting them fixed, other teams are not.

Given these insights, I think updating our documentation is a good idea and some of the things outlined above should be highlighted there. I think we should proceed with looking at the unit tests from a platform perspective—doing things like calling resetFetch in the mocha-setup and finding better/easier ways to surface flaky unit tests to the teams responsible for them. We should also keep in mind that, depending on the direction we go with app isolation, some of these issues may resolve themselves.
