### ISSUE TITLE
Design Feedback - Midpoint Review Booz Allen Education Applications - VRRAP

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#23005]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**
- Break up the form into smaller chapters. See our [Design principles/](https://design.va.gov/design/principles)Simple

**Consider:**
- Put this in a blue info box ![Screen Shot 2021-04-09 at 2.31.35 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/81eafd0b-aa56-40c6-b393-0814d066ead1)

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by amyknox** [comment]
Thanks, @allison0034 - we're tracking the Should & Consider input for post-MVP.
