### ISSUE TITLE
Redirect Request for Find a VA Form 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23000]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
There are currently eleven form detail pages containing a mix of Spanish and English.   These pseudo-Spanish pages can create confusion for non-English-speaking users when they encounter passages of text interspersed with Spanish, and also present a cognitive accessibility issue.   

Until we have a robust solution for generating form detail pages wholly in Spanish, we are going to archive the pseudo-Spanish detail pages and redirect their URLs to the main Find A VA Form search page to prevent anyone who may have bookmarked a page, or who happens upon a cached link from encountering an error.  

All eleven pages reference  Spanish-language PDF forms which will still be available for download via search results following this redirect change. 

### Requesting team info
Decision Tools Team
- John Hashimoto, PO
- Marci McGuire - PM

### Implementation date
Date new URL(s) will be live: **New URL already exists**

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing :  Can happen any time the Content and IA team has bandwidth to make this change.

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

| Column1.attributes.form_details_url                          | New URL
|--------------------------------------------------------------|--------------------------------|
| https://www.va.gov/find-forms/about-form-10-0137-espanol     | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-10-10ez-espanol     | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0510-espanol    | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0512s-1-espanol | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0513-1-espanol  | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0514-1-espanol  | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0516-1-espanol  | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0517-1-espanol  | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0518-1-espanol  | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0519c-1-espanol | https://www.va.gov/find-forms/ |
| https://www.va.gov/find-forms/about-form-21p-0519s-1-espanol | https://www.va.gov/find-forms/ |

### Definition of done
- [X] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [ ] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: **Please ensure that these redirects are implemented as temporary redirects.**
- [ ] Implementation team: Implementation team completes work 
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
@MarciMcGuireGCIO Could we link to the spanish pdf forms on the english form detail page and redirect to that instead?

Also, do we want this set up as a temporary redirect so we can bring these back at some point?

**Comment by MarciMcGuireGCIO** [comment]
@mnorthuis the English form detail pages already have links to the Spanish PDF forms under "Related Forms, about midway down the page.  I suspect that @jenniferlee-dsva may have been thinking that since the search also provides the link to the PDF, they can get to it without being presented with a page that is all in English.

**Comment by johnhashva** [comment]
@mnorthuis and good idea about temporary redirects.  Our plan is to bring back the Spanish-language detail pages when we have a more scaled, robust solution for translation.

**Comment by mnorthuis** [comment]
Thank you for that information, I assumed you had discussed that option, but wanted to make sure. 

Assigning this ticket over to @brianalloyd for his team to implement.   @MarciMcGuireGCIO and Brian can coordinate on timing. 

Brian - Please ensure that these redirects **are implemented as temporary redirects.**

**Comment by brianalloyd** [comment]
@mnorthuis thanks for the clarification, I'm going to update the AC criteria on this ticket to include the:

> Brian - Please ensure that these redirects are implemented as temporary redirects.

I'm also going to loop in `Sitewide Content team` in support of the temporary redirect implementation work and our team will scrub in to support as needed.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @mnorthuis and @brianalloyd !

**Comment by brianalloyd** [comment]
@mnorthuis @MarciMcGuireGCIO a PR is submitted for the redirects and should go out with today's daily deployment.  I'll follow back up once these changes are in the wild.  Note: We did ensure these were implemented as `Temporary` according to the ticket AC.  CC @johnhashva

**Comment by kelsonic** [comment]
Temporary redirects merged + being deployed to prod after we validated them on staging http://jenkins.vfs.va.gov/job/deploys/view/Prod/job/revproxy-vagov-prod/310 🙂

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @brianalloyd & @kelsonic! 🥳 

@johnhashva - Once the VA stakeholders are notified of this upcoming change, we are in a position for you to archive the Spanish-language pages at your convenience.  See this #22817 for details.

**Comment by mnorthuis** [comment]
Redirects working in production and documented.  Closing issue.  Thanks all!

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @mnorthuis !
