### ISSUE TITLE
Update unit test best practices

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#23007]
## Details 

Based on our knowledge and findings from #23004, draft updated documentation of unit test best practices. 

[Unit test docs](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test/)

## Acceptance Criteria 
- [x] Update unit testing documentation and add best practices and examples
- - [x] Replace documentation about Enzyme with documentation about React Testing Library
- - ~[ ] Add section on testing with Redux (will be dependent upon discussion that happen as part of #23006~
- - [x] Add more examples
- [x] Demo updates to VSP

**Comment by k80bowman** [comment]
As a result of the [findings](https://docs.google.com/document/d/1bAnymtfwfp00OvcZlIcVAdSBzfkgYwXTL5NKXWoy4zM/edit#) from #23004, we would like to accomplish the following as part of this ticket:
1. Update unit testing documentation and add best practices and examples
    1. Replace documentation about Enzyme with documentation about React Testing Library
    1. Add section on testing with Redux (will be dependent upon discussion that happen as part of #23006
    1. Add more examples
1. Demo updates to VSP

**Comment by Cgfor3** [comment]
This work is now in a PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/619
