### ISSUE TITLE
Clean up unit test console output

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#23008]
## Details 

Currently, our `test:unit` output is littered with errors. It's mostly 404 errors, but there are also some TypeErrors, React errors, and Geolocation errors, among others. It makes the test output logs difficult to decipher and, at least on Jenkins, difficult to figure out which tests are failing. We need to see if there is a platform-level solution to some of these, especially the 404 errors. For other errors we should identify which tests are producing them and alert the appropriate teams that they need to be fixed.

## Acceptance Criteria 
- [ ] Find a solution for the 404 errors and implement it
- [ ] Identify tests that are producing other errors.
- [ ] If there are platform-level solutions for other errors, enact them. If not, alert the teams responsible for these tests that these errors need to be cleaned up. If needed, provide guidance on how to do this.

**Comment by Cgfor3** [comment]
Yesterday @k80bowman and I were able to determine that the unit tests throwing 404s during execution were being caused by missing custom mockFetch calls. I will be putting together a spreadsheet outlining which tests need to be addressed.
