### ISSUE TITLE
Analytics Implementation [Facilities - VAMC]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23009]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA? -> consult, primarily
- Who is this request for?  Michelle Middaugh, Facilities team
- Provide the Domain where Google Analytics needs to be implemented
    Example domain: https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
    (applies to all VAMC pages)
- Typical Website Interactions to Track  
   - Breadcrumbs across the VMAC product need to be addressed for consistency and usability. We want any big changes to the IA or iterate navigation iterations to be informed by analytics (and user research). 
   - This request is to determine what data collection methods are already available and/or need to be implemented to gather useful data. Primarily, we want to know the most important navigational paths for Veterans visiting the VAMC pages, how Veterans are using breadcrumbs for navigation and whether the breadcrumbs are supporting them:  
> - What are the prominent user paths for facility page(s)? 
> - How often do users move between system and facility pages? (either direction)
> - What are the main points of entry (Google? Facility Locator? Straight into the facility? Heath care system -> facility? Bookmarks?)
> - Do Veterans rely on the breadcrumbs or use the back button? 
>    - Do they go back more than one level or just to the previous page?

Importantly, we need this in an aggregated form (rather than just for Pittsburgh or Erie, for example). I haven't been able to figure out how to identify them as a group in GA using URL filters. 

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by bsmartin-ep** [comment]
@mmiddaugh -

Some initial answers, but let me know if you want to meet for a minute to discuss any of this.


-----------------------
> What are the prominent user paths for facility page(s)?

We have a couple of options for paths.  A good start is the navigation summary for your page:

[Link to GA report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fpittsburgh-health-care~2Flocations~2Fpittsburgh-va-medical-center-university-drive~2F&_r.tabId=navigationsummary)

Users Flow is good too, but a bit chaotic unless you add a segment....

[Link to GA report](https://analytics.google.com/analytics/web/#/report/visitors-flow/a50123418w177519031p176188361/_r.threshold=50&_.useg=userAExvfGfhSVehevziwRo45g)

I created this _Sessions with VAMC Pittsburgh_ segment you can use to narrow it to sessions with a VAMC Pittsburgh visit.  Feel free to add this to any other GA reports as well.

![image](https://user-images.githubusercontent.com/62304138/118196649-5cdc7300-b41b-11eb-8087-f1bfadc038fc.png)

----------------------------

> How often do users move between system and facility pages? (either direction)

So basically how often are they navigating to a page (or from a page) outside the `pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/` directory?

------------------------------

> What are the main points of entry (Google? Facility Locator? Straight into the facility? Heath care system -> facility? Bookmarks?)

Adding "Full Referrer" as a secondary dimension will give you the external ones....

[Link to GA report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210302&_u.date01=20210512&_.useg=&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.fullReferrer&_r.drilldown=analytics.pagePath:www.va.gov~2Fpittsburgh-health-care~2Flocations~2Fpittsburgh-va-medical-center-university-drive~2F)

Here are the Google queries that led to this page as a Landing Page...

[Link to GA report](https://analytics.google.com/analytics/web/#/report/acquisition-sc-landingpages/a50123418w177519031p176188361/_u.date00=20210302&_u.date01=20210512&_.useg=&search_console-table.plotKeys=%5B%5D&_r.drilldown=analytics.landingPagePath:www.va.gov~2Fpittsburgh-health-care~2Flocations~2Fpittsburgh-va-medical-center-university-drive~2F)

Everything internal should be under "Previous Page Path"....

[Link to GA report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210302&_u.date01=20210512&_.useg=&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.previousPagePath&_r.drilldown=analytics.pagePath:www.va.gov~2Fpittsburgh-health-care~2Flocations~2Fpittsburgh-va-medical-center-university-drive~2F)

_(entrance)_ is when it's the first hit in a session.  _www.va.gov/facilities/index.html?XXX_ is a masked URL (for PII reasons) for facility locator searches.

--------------------------


 > Do Veterans rely on the breadcrumbs or use the back button?
>     Do they go back more than one level or just to the previous page?

Here are the breadcrumb events I see on this page.

[Link to GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210302&_u.date01=20210512&_.useg=&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22breadcrumb%22,0%5D,%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2Fpittsburgh-health-care~2Flocations~2Fpittsburgh-va-medical-center-university-drive~2F%22,0%5D%5D)

Looking into the mysterious blank one on top.

Back button tracking is an interesting request.  I don't think we are tracking this directly (via unbeforeunload or whatever), but maybe this is the data elsewhere?  We could look at bounces - visits where people visits the page and don't interact.  Or maybe  when the path is _Page 1 > VAMC > Page 1_?
