### ISSUE TITLE
[Content review] VAOS home refresh (post-feedback updates)

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#23018]
Content review for some proposed changes to the VAOS home page that came from user and collab cycle feedback.

**Proposed changes**

Clarify requests - some participants weren't clear on what "requests were

* Use more specific language for "Requested" select option. [TBD]
* Add a note above the list: "Appointments you requested that are waiting for a scheduler to review. Oldest requests are at the top."

In context:
![image.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/0a3c4efe-a054-46cd-a0e9-69d6a3b0d5f4)

----

From the collab cycle feedback: 

> https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/441371953 Instead of using "Special instructions" on this screen, could we use the same header that is used on the EC card?  "You shared these details about your concern"

Can we use this language everywhere we display the booking note? 

The current pattern is:
{Booking reason} - i.e., "Follow-up/Routine"
{Booking note} - i.e, "I need my yearly physical"

Some examples with the proposed new pattern, where the reason for visit precedes the booking note
VA appointment
![image.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/9330c0aa-b0c5-4785-b239-6af91a201cdd)

CC appointment
![image.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/5921247c-f89a-4630-ba5a-689938ad438d)

-----

If we follow the above we'll have a pattern that separates Veteran-provided information from facility-provided information:
* "You shared these details about your concern"
* "Your contact details"
Can/should we use this pattern by changing "Preferred date and time" -> "Your preferred date and time"?

----

Feedback from earlier collab cycle content review:

> Please use sentence case for headers  VA Appointment > VA appointment

----

Feedback from earlier collab cycle design review: 

> Label email and phone number under contact details.

-----

Need clearer for the empty state for each of the homepage sections. 

For example, the generic message (currently shows under canceled appointments) should rea
 ![Screen Shot 2021-04-09 at 4.03.06 PM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/bab17967-0e45-4610-8fad-d733360c2fc8)

TBD: It might be better to not display some/all sections if they don't apply to the Veteran - like canceled and requests. We should always show upcoming and past. 

---- 

Simplify home page header

The current home page header pattern is:

{h1} VA appointments
{h2} Schedule a new appointment
{h2} Your appointments

I'd like to remove the first h2 as shown in the example in the screenshot below to help focus attention on the main CTA.

Also to consider: rename the second h2 to avoid repeating "appointments." 

*NOTE: if we change the name of the h1, the breadcrumb needs to be updated as well*

Screenshot

![image.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/2761a7fc-b240-4c8d-bbe4-14cced1185cd)

**Comment by outerpress** [comment]
@peggygannon adding you for visibility, we'll run through these at our next sync before you start reviewing.

**Comment by peggygannon** [comment]
@outerpress.. Here are some recommendations for the above. Please let me know if you want to discuss any of them in person! 


1. Use more specific language for "Requested" select option. [TBD]

**Content recommendation** Has the team discussed using "Open requests" rather than "Requested"?

2. Add a note above the list: "Appointments you requested that are waiting for a scheduler to review. Oldest requests are at the top."

**Content recommendation:**  Your oldest appointment requests are at the top. We haven’t scheduled these appointments yet.  


--------

Recommending replacing this line of content: "You shared these details about your concern" with the below to make this more mobile friendly and plain-language.

**Content recommendation:** Your reason for your visit: 


------

with the above^^  content recommendation, this pattern would look like this below. Does that work? 

"You shared these details about your concern"> Your reason for your visit
"Your contact details"
"Preferred date and time" -> Your preferred date and time

-----


I'm unable to access Sketch to see the example to see your proposed design for the below.
 Is there another place I can view your proposed update?  

**I'd like to remove the first h2 as shown in this example to help focus attention on the main CTA.**

**Comment by outerpress** [comment]
Thanks Peggy! 

I'm still working through these, but in the meantime here's a fixed link to the home screen with the new header suggestion: https://www.sketch.com/s/304fd996-c00f-4b5a-b0a7-a252c2c23cce/a/52oVQ2w (updated in the ticket description as well.

**Comment by peggygannon** [comment]
@laurenernest @outerpress Hello! I see you have a CC staging review scheduled for the VAOS homepage refresh on the 22nd. Since you have a meeting scheduled for this, I think we can close this ticket and I'll provide feedback through the Collab Cycle.

**Comment by outerpress** [comment]
@peggygannon thanks! Your recommendations look good to me. Just a question about this one:

> Your oldest appointment requests are at the top.

Are we supposed to avoid language that indicates spacial position, or is that only for things like "please see x below." I thought there were some accessibility considerations there but I'm not sure.

**Comment by peggygannon** [comment]
Hi, @outerpress I'm unable to access Sketch to see the examples and updates. 

regarding your question immediately above, it would be helpful for me to see this page. 
Here's another recommendation to make it more accessible: 

Below is a list of your appointment requests. Older requests are at the top of the list. We haven’t scheduled these appointments yet.

**Comment by outerpress** [comment]
> I'm unable to access Sketch to see the examples and updates.

Sorry about that, I replaced all of the examples in the main content with screenshots. I'll update the earlier comments after this

> regarding your question immediately above, it would be helpful for me to see this page.

Here's the latest with your recommendation:

![VAOS-appt-list-requested.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/8912045e-0c4e-4d63-a5d4-5b9ed65f165d)

**Comment by peggygannon** [comment]
@outerpress thank you. Here's another content tweak that tightens up the language even further:  

Your open appointment requests are listed below. Older requests are at the top of the list. These appointments haven't been scheduled.

**Comment by outerpress** [comment]
Thanks @peggygannon that looks good to me! cc: @laurenernest

**Comment by laurenernest** [comment]
Dev ticket created #26657

**Comment by laurenernest** [comment]
@peggygannon We realized that adding "open" to the requests language in the list won't be accurate because we're also (intentionally) showing requests that were canceled.

If we update the dropdown from "Show by type" to "Show by status", it might be better to keep the option as "Requested" and just add the extra intro text. Thoughts?

**Comment by peggygannon** [comment]
Hi, @laurenernest Yes, that sounds good. I feel like we discussed this earlier and agreed on Show by status. If not, then yes, Show by status works for that label. 

Can you clarify what is the "extra intro text" that you mention in your comment above?

**Comment by laurenernest** [comment]
Yep, we're going to update to "Show by status". Given that change, and the fact that not all the requests in the list will be "open", would you want to make any other changes to the intro text?

Here's a screenshot for context.
![Screen_Shot_2021-07-20_at_10_23_56_AM](https://user-images.githubusercontent.com/72046525/126375023-2e017349-0e61-45f8-8475-eea351198b41.png)

**Comment by peggygannon** [comment]
Hi, @laurenernest 

Agree on having Requested for the dropdown. 

Will the intro text only show for "Requested" appointments? or will this intro show all the time?

**Comment by laurenernest** [comment]
@peggygannon the intro would show only for the Requested list. No intro when the other 3 are selected, unless you recommend adding.

**Comment by peggygannon** [comment]
HI, @laurenernest just a small tweak to tighten up the Requested intro text. I'm not sure the value of calling out "older" requests. I think the important message is that the requests at the top haven't yet been scheduled. Please let me know if you agree? 

{intro content for Requested list}
Below is your list of appointment requests. The requests at the top haven't been scheduled yet.

**Comment by laurenernest** [comment]
Agree with the "older" part for now. We can watch for feedback if that kind of info would be helpful. 

All of the appointments in that list view won't have been scheduled yet so we can leave out the "top" part too.

**Comment by outerpress** [comment]
Hi folks! How about:

> Below is your list of appointment requests that haven’t been scheduled yet.

?

The [research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/jan-2021-appts-list-test/report-out.md#appointment-requests-continue-to-create-confusion) showed that it wasn't clear how the requests were organized in this section, but I'm fine leaving that part out until it's clear it's an actual problem.

Here's a mock:

![VAOS-appt-list-requested](https://user-images.githubusercontent.com/2536801/129596387-70af0d07-5322-4e78-a277-b8294ebc62e7.png)

**Comment by peggygannon** [comment]
Hi, @outerpress the updated mock looks good.

**Comment by laurenernest** [comment]
i'll update our copy doc and dev ticket #26657
