### ISSUE TITLE
[FE] My VA - (Pre QA) Clicking "Manage all claims and appeals" link re-routes back to My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23015]
Clicking the "Manage all your claims and appeals" link from the Claims and appeals section should route the user to the main claims and appeals tool page. Currently, clicking "Manage all your claims and appeals" link re-routes the user back to My VA.

Note the url changes from **/my-va/**  
![23015 manage all your claims and appeals pt1](https://user-images.githubusercontent.com/45603961/114242425-daaee980-9958-11eb-85f7-57ca8551db1d.png)

to  **my-va/claim-or-appeal-status/** 
![23015 manage all your claims and appeals pt2](https://user-images.githubusercontent.com/45603961/114242432-de427080-9958-11eb-8bd4-123c32c60c6b.png)

**Comment by erikphansen** [comment]
This can be validated on staging.

**Comment by ajakabcin** [comment]
Confirmed on staging thanks!
