### ISSUE TITLE
IA Request | C+L Team | Anchor Tag Links for Corona FAQ (English) Page

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#23023]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kick-off ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/anchor-tags.md
- Link to or attach prototype or mockup: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20125
- Link to or attach user/page flows
- Link to or attach your content source of truth, including H1s (if separate from prototype/mockup)

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?

**URL(s)** - What are your suggested URLs and why?

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
Hi @SKasimow, its my understanding that the solution for this has already been determined per this issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/22385.

**Comment by SKasimow** [comment]
Hi @mnorthuis - https://github.com/department-of-veterans-affairs/va.gov-team/issues/22385 was a Discovery ticket so thought we should have an I/A specific ticket opened.  I can close at the end of this sprint.

Also, fyi -- I don't this changes anything from your perspective but please note we did also update the UI (link above).

Thanks, Sharon

cc: @jenniferlee-dsva
