### ISSUE TITLE
Messages - User sometimes gets the "You don't have any messages" message and sometimes gets an error going to Messages

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#23021]
## What happened?
When I'm logged in as a user who apparently doesn't have access to the Messages section, I get multiple responses from the app.  It flicks between "You don't have any messages in your Inbox" and a generic error, sometimes landing ultimately on the message, sometimes ultimately on the error.  See the clip attached.

## Specs:
- Device: iPhone XR and Samsung Galaxy Note 9 (most noticeable with the Samsung).
- Browser: (e.g. Firefox, IE 11)
- Test User: I used 366

## Steps to Reproduce
- Log in as user 366.
- Navigate to Health > Messages (multiple times)

## Desired behavior
I get the "You don't have any messages" message (as long as user has accessess.

## Acceptance Criteria
Responses don't flip between a message and an error.

## Bug Severity
- 3 - Medium

## Linked to Story
n/a

## Screen shot(s) and additional information

https://images.zenhubusercontent.com/133843125/fe4deff7-d761-4949-9bad-b42618e38e0c/img_8977.mp4

**Comment by bessgreen** [comment]
@digitalken please retest now that #23732 has been merged

**Comment by digitalken** [comment]
PASS 5/20/2021 - Looks good now that #23732 has been merged.  Closing.
