### ISSUE TITLE
Update UX & content of Confirmation Page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2303]
Veteran feedback suggests the visual ordering / grouping of information, and content, on the confirmation page may be confusing.

Recommendations:
- [ ] 'Location' field is of primary importance to veterans and should be co-located on the left with the clinic info, not off to the right by itself
- [ ] 'Additional details' header should align with the question asked; should probably be 'why do you want to make an appointment'
- [ ] Veterans should be able to navigate back to the VAOS dashboard from the confirmation page
- [ ] Veterans should be able to add the confirmed appointment to their calendar (tbd if this should be its own ticket)

**Comment by markgreenburg** [comment]
@rtwell these are consolidated findings from usability - assigned this to you since you just pushed up the confirmation page mocks. Not sure if these items are already covered by your new mocks - if so, then feel free to close this ticket out.

**Comment by rtwell** [comment]
yeah we captured this on the other tickets
