### ISSUE TITLE
Identifying Account Owner

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23038]
##Description
There are a few actions in the app store consoles that only the designated Account Owner can do. We need to identify who this person is and how to contact them

**Approx date needed by**
- 4/1

**Acceptance Criteria**
- [ ] We know who the account owner is for App Store and Google Play, and how to contact them

**Comment by leanna-usds** [comment]
Tony Williams (tony.williams@va.gov) is the account owner. We'll need to get him our code so he can push it. I've emailed him and I think we're good here. Closing.
