### ISSUE TITLE
Load Testing 

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23032]
## Description
Do we need to conduct load testing to make sure that APIs can handle traffic added by mobile app?

## Reference documentation
- Load Testing added as a significant decision to this doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/product/significant%20decisions.md#decision-13-load-testing
- Device Matrix: ![image.png](https://images.zenhubusercontent.com/5d7fb658ed817a000174e5fd/bb74b591-f5e5-46b3-86ef-8509b839a1ab)

## Status & Tasks
**4/26** 
- No new tasks, want to make sure Leanna sees the device matrix

**4/20** 
- We have a device matrix which was signed off on at the start of the project

**4/12** 
- USDS mobile app dev & Dror are resources here, @leanna-usds to reach out 
- can probably lean on VSP here - existing processes / scripts / documents 
- @lexicalninja will bring up load testing for MHV with Barry week of 4/19

**Comment by leanna-usds** [comment]
I spoke to Dror with Alastair and Ayush on 4/13. He had no concerns about load testing the back end. Next step is to find out from DF QA what devices/conditions they're using and make sure it's sufficient.

**Comment by leanna-usds** [comment]
We do want to load test IAM, @kreek can provide more details.

**Comment by lexicalninja** [comment]
Can we smoke test IAM or do we need them to smoke test for us? We aren't using our own API for this, so I don't think we can just drill their end points without them. We don't want to degrade service for the other applications with our testing.

**Comment by ayushchak** [comment]
| OS      | DEVICE                     | SCREEN SIZE |
|---------|----------------------------|-------------|
| iOS     | iPhone SE                  | 320x568     |
| iOS     | iPhone XR                  | 375x812     |
| iOS     | iPhone 11                  | 414x896     |
| Android | Samsung Galaxy S7          | 360x640     |
| Android | Samsung Galaxy S9          | 360x740     |
| Android | Samsung Galaxy Note9       | 412x846     |
| Android | Motorola Moto G7 Power     | 360x760     |
| Android | Google Pixel 3XL           | 412x846     |
| Android | LG LM-Q720 Stylo 5         | 412x823     |

**Comment by patrickvinograd** [comment]
We  can run some tests  against IAM in staging, but it might not be super informative on a  couple fronts:

1) We have limited test users - testing the token/ introspection endpoints for the same users over  and over  might not be reflective of testing  many different  users,  because of caching.

2) IAM will admit that their SQA env is underpowed relative to their prod env, so even if it falls over it doesn't help us understand what the  real capacity of prod is. They _might_ have a pre-prod env we can test against that's more reflective of prod?

**Comment by leanna-usds** [comment]
Documented as a known risk but there's not much we can do while we are reliant on this service. Closing.
