### ISSUE TITLE
Launch Dry Run & Go/No Go Docs

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23042]
## Description
What is the checklist of items we will want to run through before making the apps public (go/no-go doc)? Who needs to be in the room?

**Acceptance Criteria**
- [x] Go/No-Go doc is on Github
- [x] Appropriate team members are identified

## Documents
- Mobile App Go/No Go draft: https://docs.google.com/document/d/1z7VCUocleZPHxDhz-LLEBCtbNq2ors31_i2IKcJt5Hc/edit?ts=60998d21
- VSP Go/No Go reference: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/go-no-go-meeting-template.md

## Notes
- 5/27: Leanna to own this and finish in the next week or so

**Comment by ayushchak** [comment]
An additional question here is specific to login: what % of logins in our testing or early days of app store release have to be successful in order for us to consider the current auth solution appropriate for the mobile app? 
Three inflection points, but we need to know what our thresholds are for each:
- Login is working well, not an immediate priority to find a new auth solution
- Login is working medium-well, but we will need to find an auth solution in the near-term
- Login is working so poorly that we will have to pull the app until a new auth solution can be put in place.

**Comment by leanna-usds** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/releases/MVP-launch/soft-launch-go-no-go.md
