### ISSUE TITLE
Add messaging for 'only VAOS-supported facilities listed' on system / facility selection page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2304]
As a veteran, I want to understand why some of the facilities in my registered systems are not showing when I'm on the 'select a system / facility' page so that I don't think there's something wrong with my registration.

Context: only certain facilities 1. support VAOS and 2. support the type of care the veteran selected. Facilities that don't meet these checks will be hidden from veterans, which could in theory be confusing if not explained correctly.

@peggygannon would appreciate your thoughts on content here.

AC:
- [ ] Content exists in FE explaining that the facilities shown are only ones that support online scheduling for the type of care selected earlier.

<img width="760" alt="Screen Shot 2019-10-09 at 3 30 10 PM" src="https://user-images.githubusercontent.com/24251447/66522443-0ecef300-eab3-11e9-834b-a04e4e6f98d9.png">

**Comment by jbalboni** [comment]
@markgreenburg I think we've covered this in the question text now?

**Comment by markgreenburg** [comment]
I don't think we're covering the 'only some sites support VAOS' in the current question text (Screengrab below). @peggygannon – not all healthcare systems support VA Online Scheduling, and we should probably call that out in the 'select a system' question so that veterans aren't confused if they don't see their preferred healthcare system in the list.

<img width="858" alt="Screen Shot 2020-01-13 at 10 03 01 AM" src="https://user-images.githubusercontent.com/24251447/72271591-c6146200-35ec-11ea-8759-48a957541f86.png">

**Comment by jbalboni** [comment]
@markgreenburg The first question always shows the VAMCs you're registered at, there won't be anything excluded from that list. Unlike the second question, where we might not show some facilities.

**Comment by lenaecb** [comment]
@jbalboni - does this still need to be addressed?

**Comment by jbalboni** [comment]
@lenaecb I don't think so, but I think it would be up to @rtwell and @peggygannon if they feel like there's any text we should clarify or change on this page.

**Comment by peggygannon** [comment]
A few followup questions: 

@jbalboni for #2, will users only see the clinics that support the type of care the veteran selected? If so, then I don't think we need any additional content. 

If all clinics are shown and a user selects one that doesn't support the type of care, do we show an error alert?

**Comment by jbalboni** [comment]
@peggygannon Correct, we're only showing facilities in that second question that support the type of care you chose. If that list is empty, we show a warning and they can't go any further.

**Comment by peggygannon** [comment]
ok, thanks. I don't think we need any additional content for this screen.

**Comment by lenaecb** [comment]
Based on that, I am going to close this ticket.
