### ISSUE TITLE
Tabletop exercise

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23041]
## Description
Conducting an activity for key team members to discuss how to respond to any post-launch incidents

**Acceptance Criteria**
- [x] Activity is planned
- [x] Activity is conducted
- [x] Incident response plan documentaion is on Github

## Reference Documentation
- https://docs.google.com/document/d/1TnF3fi9lWE90RY49pgZI6abHqAtPB3f5L6IdZq6sUDU/edit#heading=h.660a5vio9zyo
- https://docs.google.com/document/d/1TnF3fi9lWE90RY49pgZI6abHqAtPB3f5L6IdZq6sUDU/edit#heading=h.660a5vio9zyo

**Comment by ashley-matthews** [comment]
Scheduled for 5/12

**Comment by patrickvinograd** [comment]
Tabletop exercise conducted today. I'm going to copy the notes into GitHub and link here, then close this issue. The post-exercise action items will be noted in #23053, and that item can be closed after those are resolved or spun off into separate tickets.

**Comment by patrickvinograd** [comment]
Exercise Notes:

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/mobile-app/Mobile%20Launch%20Tabletop%20Exercise%205_12_2021.pdf

**Comment by patrickvinograd** [comment]
Incident response plan is here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/operations
