### ISSUE TITLE
On-call support?

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23052]
## Description
Do we need on-call for a mobile app?

## Reference Documentation
On call for VSP: 
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/README.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/a5bf9c37d2e38480507490f59bf69feef2ab8f90/teams/vsp/teams/tools/backend/triage/on-call-process.md
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/OnCall

## Notes, Tasks, Next Steps
**6/24**
- Will be adjusted once we know our launch date

**6/14**
- We reviewed on-call expectations with the engineering team and shared a draft on-call schedule the week of 6/7. Will need to update the schedule once we launch. 

**6/7**
- We intended to start this week, but we can wait til we're in the store. Ashley working on documentation with Jonathan

**6/3**
- Will start this rotation on Tuesday

**5/10**
- We don't need a formal PagerDuty on call rotation, but we will set up business-hours on call to hold people accountable for keeping an eye on observability tools

**5/5**
- Patrick V will have input into this
- We should have a incident response protocol (see ticket #23054)
- The only additional info we'd have beyond what VSP has is Crashlytics reports
- There is a chance that there is an issue in the mobile API (and not a downstream service)

**Comment by patrickvinograd** [comment]
As described in #23051, we won't have a formal PagerDuty-style on call rotation as doing so would be largely redundant with what VSP already does - instead we will make sure that team knows to escalate the mobile-specific issues to us.

I would recommend that after launch we set up a business-hours on call rotation to hold specific people accountable for keeping an eye on our observability tools and raising any urgent issues for triage. We will have to see how long this is warranted based on the observed level of events - and if we need to tune down noisy alerts. But in the short term I think it will be a good practice for stakeholder confidence.

**Comment by patrickvinograd** [comment]
Reassigning to @ashley-matthews to coordinate this. Just a lightweight schedule and some way for engineers to know when they are on call. A google spreadsheet is probably sufficient.
