### ISSUE TITLE
App Store Review monitoring & reporting

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23056]
## Description
Who is responsible on our team for monitoring app store reviews? How frequently will they check? How will they flag or respond to inappropriate comments? How will they pass along reports to us?

**Acceptance Criteria**
- [x] We know who is flagging and handling inappropriate app store reviews [our team is]
- [x] Our team know what criteria defines an inappropriate review
- [x] Our team has access and knows how to flag or respond to a review
- [ ] Our team knows how frequently to report to us about App store reviews [N/A because our team is handling]
- [x] This protocol is documented in Github

## Documentation
- https://docs.google.com/document/d/1Qi3H-edMEZ_mLFSPiJvqf2DGZ3mqtuHRCm0VLU8mCw4/edit

## Status, Tasks, Next Steps
- 5/20: Leanna to add this documentation to GH
- 5/14: Leanna to work with team on templatizing and documenting
- 5/10: Our team will be responsible for this at the start, and then will hand off to Chante's team

- 4/26: will be part of conversation with Chante, Leanna wants to loop Tracey in on

- We need to give the right person access to the console, with the right permissions

**Comment by leanna-usds** [comment]
@ambikaroos where in Github do you want me to document this process?

**Comment by ambikaroos** [comment]
@leanna-usds add a markdown file in this [MVP launch folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/product/MVP-launch) and then link to it from the App Store Monitoring & Flagging Protocol checkbox in this [readme](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/product/MVP-launch)

**Comment by ayushchak** [comment]
https://docs.google.com/document/d/1Qi3H-edMEZ_mLFSPiJvqf2DGZ3mqtuHRCm0VLU8mCw4/edit

**Comment by ambikaroos** [comment]
@leanna-usds @ayushchak I can add this doc to GH, but there are a few outstanding comments/questions. Can you take a look? https://docs.google.com/document/d/1Qi3H-edMEZ_mLFSPiJvqf2DGZ3mqtuHRCm0VLU8mCw4/edit#heading=h.1clymxg6j6o2

**Comment by ambikaroos** [comment]
On GH: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/releases/MVP-launch/app-store-review-monitoring.md
