### ISSUE TITLE
Post-launch reporting analytics outwards

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23055]
## Description
After launch, how will we monitor and report on the app, and to whom?

**Acceptance Criteria**
We know the cadence of who (product team? eng team?) checks the following, and reports it to whom (which stakeholders at VA):
- [ ] Events in Firebase
- [ ] App store reviews (see #23056 for Chante's team's process)
- [ ] App console KPIs (downloads, impressions, etc)

## Notes & Next Steps
- 5/20: Subset of team met and are aligned on high level metrics. Ayush putting together an excel, Leanna pulling this into a slide
- 5/14: Ayush to send some high level metrics to Leanna, which she'll share with stakeholders and set expectation that this will be the metrics and will be sent on a weekly basis

**Comment by ayushchak** [comment]
Any thoughts on our earlier discussions re: Slack integration? Would like to have a way to set up a line of communication between us and the call center staff so that they know when there is an app issue or outage.

**Comment by ambikaroos** [comment]
Folding this into #20993
