### ISSUE TITLE
Content Feedback - Midpoint review - VRRAP

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#23069]
## User story
VSP content review of VRRAP. 
Link to prototype: https://bahdigital.invisionapp.com/share/RMIAGJTSDEA#/screens
Link to content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/design/content-doc.md

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

**Comment by peggygannon** [comment]
@amyknox VSP content review for VRRAP form. Please let me know if you have any questions. 

**Questions/thoughts**

1.	Form screen 1 has a lot of different components and content.
Per design and content principles listed below, content/components should be broken down into smaller steps and or content chunks.
- Focus users on the primary task, free of distractions. Break complex tasks into small logically ordered steps.
- Break down complex information into simple, snackable chunks, and provide it progressively, when and where they need it, so it’s easy to find, easy to understand, and not overwhelming.

Also an accessibility issue, as having this much information on one screen creates cognitive burden on users. 

2. Should this content be below be styled as alert? This doesn’t follow pattern of other forms where this is styled as intro text. 
This is the personal information we have on file for you. 


3.	Are there any validation error or error states that should be included as part of this review? 

-------


**Must**

1. Intro page: 
Several edits from content outline aren’t implemented in this mockup. Please update the content to match the recommendations from OCTO:
- Per OCTO content recommendations, H2 should read: Follow these steps to apply
- Under: "Make sure you’re eligible" header: 
--First bullet point should read: Between 22 and 66 years old
--Remove commas at the end of each bullet point
--Remove period at the end of last bullet

2. Direct deposit information: 
Please make this edit, per OCTO recommendations: 
This is the bank account information we have on file for you. We’ll send your housing payment to this account.

3.  Program selection information screen
Add comma after “online”
Is the program in-person, online, or both? 

4. Review application screen
Under Program information accordion, please update the questions to match the edits that were made on that screen. For example: 
•	Do you know which program you'd like to enroll in? ( * Required) { Radio: yes or no }
•	What's the name of the school or training provider? { free text }
•	What's the name of the program? { free text }
•	Which city is the program in? { free text }
•	Which state is the program in? { free text }
•	Is the program in-person, online, or both? 


---------

**Should**

1. Review application screen

This content below is in the content outline, but not in mockup. Was it decided to not include this? 

Please review the information below to make sure it’s correct before you submit your application. This is especially important if you worked on your application over several days.

2. Confirmation page: 
I recommend updating this line to match the edit that was made on the intro page: 

We usually process claims within 30 days. TO:  We usually make a decision within **30 days.**

3. This link language should be updated to make it a complete sentence: 
[More about what happens after you apply] TO:  [Learn more about what happens after you apply]

**Comment by amyknox** [comment]
@peggygannon - I'm so sorry! We've been moving quickly on this and in the process, a [new prototype was spawned](https://bahdigital.invisionapp.com/share/CUIAGI923MB). As you'll see, this one DOES match the content doc.  

I think we can incorporate all the musts except this one, which for some reason, the Education Service team has pushed back on strongly:

--First bullet point should read: Between 22 and 66 years old

They want to use the language "At least 22 years of age but not more than 66 years of age" and we've gone back and forth a couple times with them on it already. 


Shoulds - I'll see if we can get these incorporated before it goes out: 
1. Should be in the final version of the prototype but doesn't look like it is, I'll see if we can update that
2. I'll see if we can update that language
3. Should be in the final version of the prototype but doesn't look like it is

**Comment by amyknox** [comment]
@peggygannon 
We're addressing Musts 3 & 4 via a defect on our end and review Musts 1 & 2 for timing / critical path.

**Comment by peggygannon** [comment]
Hi, @amyknox OK, thank you for the update.

**Comment by amyknox** [comment]
Thanks for the input @peggygannon 
Musts have been addressed. Shoulds that weren't already addressed are in our backlog. 

**Questions/thoughts**

> Form screen 1 has a lot of different components and content.
> Per design and content principles listed below, content/components should be broken down into smaller steps and or content chunks
> Focus users on the primary task, free of distractions. Break complex tasks into small logically ordered steps.
> Break down complex information into simple, snackable chunks, and provide it progressively, when and where they need it, so it’s easy to find, easy to understand, and not overwhelming.
> Also an accessibility issue, as having this much information on one screen creates cognitive burden on users.
> 

I agree! If we can break this into a form with typical chapters post-MVP, we will!  

> Should this content be below be styled as alert? This doesn’t follow pattern of other forms where this is styled as intro text.
> 
> This is the personal information we have on file for you.

Yes, it should.  It wasn't addressed in the prototype but is in the content doc. 

> Are there any validation error or error states that should be included as part of this review?
Not at this time.  They're all standard error messages.
