### ISSUE TITLE
Access for Josh Kim

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#23066]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Ariel Nerbovig
- Please provide your name.
   > Josh Kim
- Please Provide your email.
   > josh.kim@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Accessibility Specialist, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtKtPlRk/XH/zPgGj8zYMt3dEklPDSp9IZ/nLmVaGzMK6XsMHDwPWX6EEKVRWPPMck2FqyHqv7lrnXUDH3OjACqzdHubPvNupckM3aoxUHKFOKqRNO/v0cDz21Z8o7x02Qbhae5s1pa+Atr9C/URNzwUqpJRwj92dIEksRVUm/QimPWGBEvhL34HRhHK64+G8GG7Yrc7RHse0zR4JpBgxO74TwpUaswLErf+JswkrhFDkTexuvDcpYOTtGqrCg3PKEhA4ipYk2NwVduCTkW2DatnYLfYeW5AGqWjqaoj1f6XBn/p2CR4cmvypY6E0uVFSy9aRmGHFzzgtu3awhPHVmu/02OWYYGArDkqWxQBYx2JWBLzkeiK3Kb6bKo6E4u9G69WXLBL9IOqtPBUm3DBUOKppJfb91nUK9JopNaObvOa/dlUw1zA17JKMig3tXJXW6i4r/d3Sk4tdwH2dUMkwKPsGI/4WtczGVXVO8B/t6nZ53qhkXaCesPPIu2I9YjNE= joshuamichaelkim@JoshuaKim-Macbook.fios-router.home
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why? 
  - Just need access to SOCKS

**Comment by joshkimux** [comment]
@department-of-veterans-affairs/vsp-operations please review 🙇

**Comment by mydesignrocks** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/8948 was completed.
