### ISSUE TITLE
Accessibility Feedback - Midpoint Review - Booz Allen Education Applications - VRRAP

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#23067]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Does the "Print this page" open a print dialog? Does it use a print stylesheet?

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Should:**
- Start the education application should be a [primary action link](https://design.va.gov/components/action-links).
- SSN should use the `***-**-9191` pattern to match our production component.
- Break the form into smaller chapters. There's a lot of information here on one page that could be a high cognitive load.
- The Direct Deposit Information should be its own section like "Banking" or something similar.
- "Go back to VA.gov" on the confirmation page should be a link. The [action link style](https://design.va.gov/components/action-links#how-to-use-other-links) might be a good one here.

**Consider:**
- Tracking users who prefer to click the first "Start the education application" vs. the second one. There's a lot of information in the subway map that could be useful, but may be ignored if users can shortcut skimming/reading it before starting their application.
- Additional research sessions with assistive tech users when code is stable in staging or production.

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by amyknox** [comment]
Thanks @1Copenut - appreciate your input! We're tracking Should & Consider items for post-MVP.

**Comment by amyknox** [comment]
@1Copenut The "Print this page" opens the print dialogue. This is what the confirmation page looks like. 
[PrintThisPage-confirmation.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6313197/PrintThisPage-confirmation.pdf)

**Comment by 1Copenut** [comment]
Thank you @amyknox that printout looks really nice! Is it generated as a PDF, or is it CSS print styles?
