### ISSUE TITLE
Consolidate 'pending' and 'confirmed' appointment lists / sections

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2306]
As a veteran, it's confusing to see 'pending' and 'confirmed' appointments in separate lists, especially since some appointment requests will move between the two and I'm not sure where my canceled appointments will show up. I want to see both in one place so that I'm not jumping between the two.

- Pending and confirmed appointments should be in the same list
- Ordering should be chronological
- AM / PM should be used in the sort order for requests
- Requests should come after any overlapping confirmed appointments
- Past appointments & cancelled appointments / requests: @goldenmeanie not to sure where to put these, need some guidance in the mocks.

Ex: Confirmed PC appointment on 10/10 at 10am, confirmed Audiology appt on 10/10 at 11am, confirmed sleep medicine appt on 10/10 at 3pm, optometry request on 10/10 AM. Cards in the list should show in this order:

[ PC 10am ]
[ audiology 11am ]
[ Optometry (time pending) ]
[ sleep medicine 3pm ]

-----

AC
- [x] Updated design exists for a combined 'pending' / 'confirmed' appointments page / appointments lists.
- [ ] Updated list is in front end
- [ ] Preceding page with confirmed / pending appointments is removed

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/67396576-d846ad00-f575-11e9-9b1f-d419ce888efb.png)
![image](https://user-images.githubusercontent.com/12564977/67396603-e0065180-f575-11e9-876e-d073a33146ab.png)

**Comment by markgreenburg** [comment]
@peggygannon not sure that there's much content to review here but would be great to get your take on Ryan's mocks.

**Comment by markgreenburg** [comment]
@rtwell I'm assuming the one confirmed appointment in the right-hand pane on the first screenshot is unintentional, unless you say otherwise :)

**Comment by rtwell** [comment]
oh on the other ticket i mentioned that was there to show what it looks like on mobile—sorry for the confusion!

**Comment by peggygannon** [comment]
@markgreenburg @rtwell Hi, I just have a few style recommendations for this page mockup: 

1. Please change EST to ET (per out styleguide time zones should be CT, ET, MT, or PT (no parentheses, periods, or daylight/standard)

2. For Pending appointments, I recommend tweaking the header at the top for clarity TO: 
**Pending** The date and time of this appointment are still to be determined.

**Comment by 1Copenut** [comment]
@rtwell I'm attaching a JPG of your card comp with some 508-specific notes and questions. LMK if anything doesn't make sense or you want to discuss further.

![508-vaos-card-review](https://user-images.githubusercontent.com/934879/67888289-d8691e80-fb1a-11e9-9d57-39d0aff7677d.jpg)

**Comment by narin** [comment]
I have the majority of this work done and will review the accessibility comments @1Copenut made.

@markgreenburg @rtwell After working on this a bit, there is some data in the mockups that is either not available or would require additional API calls:

![Screen Shot 2019-10-30 at 2 47 16 PM](https://user-images.githubusercontent.com/786704/67901759-d1470e00-fb24-11e9-9800-fa05962ed0e8.png)
1. Only community care appointments have address info without making an additional API call
     - One possible workaround for this is to provide a link to the facility details page instead
1. "Purpose of appointment" (e.g. Follow up/Routine visit) which appears on the right is only available for requests
3. "Add to calendar" is doable but should probably be its own ticket
