### ISSUE TITLE
[Design] Veterans can reschedule appointment in VAOS-R

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2307]
As a veteran, I want to be able to reschedule my appointment - not just cancel it - so that I can book the same appointment at a different time that is more convenient for me.

AC
- [ ] Flowchart created for rescheduling an appointment
- [ ] Flowchart includes technical details, e.g. steps where service calls are made

**Comment by outerpress** [comment]
In January we ran a usability test on a concept for rescheduling confirmed, direct-scheduled appointments. Most participants easily completed the rescheduling task as presented ([results here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/jan-2021-appts-list-test/report-out.md#the-ability-to-reschedule-and-cancel-appointments-online-empowers-veterans)) so I feel comfortable moving in this direction.

[Prototype of the concept we tested.](https://www.sketch.com/s/b512e2c6-1987-4ea4-92bc-97586b720aee/a/Vrk1gyo/play)

Below is a rough user flow showing how rescheduling might work for:
* Direct scheduled, confirmed appointments
* Canceled appointments
* Appointment requests

Some assumptions/questions:
* Assuming Veterans will not need to change facilities to reschedule - though do we need to consider this if no other dates are available?
* Assuming Veterans will want to reschedule all three types of appts.

User flow:
![Reschedule flow.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/7fa6e0a6-7d18-454d-9ac6-4532c8f0b607)

Next steps, we get engineer feedback as to feasibility of the path(s) we want to move forward with.

**Comment by outerpress** [comment]
I dove a bit deeper on the different possible rescheduling flows here: https://www.sketch.com/s/b512e2c6-1987-4ea4-92bc-97586b720aee/a/dljERKl/play

Just noting for when we loop back to this

**Comment by outerpress** [comment]
This one got a little messy because I dropped in comments instead of creating/linking tickets.  I'll create new tickets for future work needed for this Epic. But since the initial workflows are done, assigning back to product/ @ldelacosta
