### ISSUE TITLE
[FE] My VA - (Pre QA) "Learn how to apply for education benefits" links to wrong page

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23073]
The "Learn how to apply for education benefits" should link to the "[How to file apply for the GI Bill and related benefits](https://www.va.gov/education/how-to-apply/)" page. On staging, it's incorrectly directing the user to the [main VA education and training benefits page](https://www.va.gov/education/?_ga=2.222141016.1190016477.1618237465-1696807371.1617981758). 

**Current State**
![23073 incorrect apply for edu benefits link](https://user-images.githubusercontent.com/45603961/114425528-27780780-9b87-11eb-9f93-637786d802fd.png)

**Desired State**
User should be sent to [this page](https://www.va.gov/education/how-to-apply/) when clicking that link

**Comment by Samara-Strauss** [comment]
Also, please maintain the original domain for this link. Right now, our staging page is linking to prod. My VA staging links should link to staging pages; My VA prod (once it launches) should link to pro pages.

**Comment by ajakabcin** [comment]
See also #23134 and #23072

**Comment by erikphansen** [comment]
[PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/16789) so this can be validated on staging soon.

**Comment by Samara-Strauss** [comment]
Validated!
