### ISSUE TITLE
Questionnaires MVP - This Visit - VSA-QA Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#23077]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

## Product/Feature summary

- Product/Feature Outlines:
  - [Product Outline (Questionnaires)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/product-outline.md)
  - [Feature Initiative (This Visit)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)
  - [Feature Outline (This Visit)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/features/this-visit.md)
- Feature Epics: #12102
- [Feature Flows](https://app.mural.co/t/vsa8243/m/vsa8243/1596561661701/0afd94dfc8598b105524e87c8828b10dba98bbf2)
- [Feature Design prototypes](https://app.zeplin.io/project/5f3d86a458ea2231e60a4780)
- Staging URL: https://staging.va.gov/health-care/health-questionnaires/questionnaires

## Product-team SMEs

[see [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002) > Healthcare Experience team]

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated use-cases (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data mocked to support these scenarios.]

Link to **Use Cases doc**: \[TBD] Currently awaiting Lighthouse Team

## How to configure this issue

- [ ] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided/developed.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [x] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
Feature to be released (date TBD) is This Visit (Visit Intro).  [Slacked](https://dsva.slack.com/archives/C0136TS768M/p1618248946158000) w/ Team and got reference-links [now updated above in main description] from B/E Engineer Dillo Raju & Designer Kristen McConnell.

**Comment by tlei123** [comment]
@kristenmcconnell , would you mind starting a Use Cases doc please and add a link in the main description above?  [I'm assuming there'd be different specific use-needs to be met, but I could be wrong.]

- Use Cases [doc-template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)
- Relevant [QA documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/vsa-qa-use-cases.md) [Template instructions are at the bottom]

This doc should outline in general the different "user-journeys" to their "user-need being met", so as to enable QA to develop corresponding, detailed QA test-cases.  You can chat w/ @mdewey & @dillo to decide how to delineate different use-cases.

Feel free to ping me on Slack if you have any questions/issues.  You can also send me a Zoom meeting invitation for more detailed discussion if you prefer.

Thanks much in advance!

**Comment by tlei123** [comment]
@mdewey @dillo , re. our [Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/testing/test-cases.md#test-case--upcoming-appointment-questionnaire-is-still-in-progress):
- Future-Appt-[Not-Started-](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/testing/test-cases.md#test-case--upcoming-appointment-questionnaire-needs-to-be-filled-out) & [In-Progress-](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/testing/test-cases.md#test-case--upcoming-appointment-questionnaire-is-still-in-progress)Qstnrs: On Staging, the questionnaire-cards are not moving from To do and Completed tab after successful submission [i.e., Confirmation page displayed].  Will this be fixed once app's code-complete on Staging?
- Canceled-Appt-[No-Qstnr](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/testing/test-cases.md#test-case--cancelled-appointment-no-questionnaire-response)/[-Incomplete-Qstnr](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/testing/test-cases.md#test-case--not-completed-questionnaire-for-a-past-appointment), [Past-Appt-Incomplete-Qstnr](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/testing/test-cases.md#test-case--not-completed-questionnaire-for-a-past-appointment), & [Future-Appt-No-Qstnr](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/testing/test-cases.md#test-case--use-has-an-appointment-in-the-future-with-no-questionnaire): The Expected Outcome ("q-card NOT visible) can't be properly validated via normal UI-testing. Might they be testable via Safari [local-override](https://webkit.org/web-inspector/local-overrides/) of incoming API-data [i.e., changing some prop in the JSON]?
- PDF downloadability & printability: Are both download and print functionalities browser-native?  I.e., is either controlled by the app's functional code?  I'm figuring PDFs are simply implemented as links, but I want to make sure.

cc @kristenmcconnell

**Comment by mdewey** [comment]
@tlei123  I think I can shed some light on your questions

1. That is expected for right now we are still dealing with mocked data on that screen. This will be fixed this upcoming sprint
2. Can you expanding on using Safari for overriding API requests? That sounds like a good workaround, but is that a long-term solution? 
3. The PDF works by opening the PDF in a new tab and the user can do with what they will. This feature will need browser/device testing.

**Comment by tlei123** [comment]
@mdewey , re. Safari local-overrides...

We can actually skip using local-overrides, if you can tell me which API response and which props therein you're checking, for each of those "q-card-should-not-be-visible" cases, to determine if a questionnaire should be hidden by f/e.

**Comment by mdewey** [comment]
@tlei123  I have added some docs here https://github.com/department-of-veterans-affairs/va.gov-team/issues/23977#issuecomment-830207991

**Comment by tlei123** [comment]
@leahkeeler , all test-runs now completed.  QA-artifact links are here, and will also be updated into Staging Review ticket #24145.

Only one content/styling defect logged: #24417 

- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1215)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/35&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=896)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/221)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/222)

**Comment by tlei123** [comment]
Closing this now.  QA-feedback will be addressed & tracked via #24674.
