### ISSUE TITLE
Discharge Upgrade Wizard - Change PDF link for Air Force respondents to a link to AFRBA portal

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23071]
## User Story
As a member of the US Air Force who uses the Discharge Upgrade Wizard (the Wizard literally branches users by service), The Air Force would now like us to direct users to their Air Force Review Boards Agency portal (AFRBA) https://afrba-portal.cce.af.mil/#portal -- and we've been asked to route users of the wizard to that portal vs. providing a link to the PDF form as a download. 

<img width="330" alt="US AF Discharge Upgrade Page" src="https://user-images.githubusercontent.com/63107147/114218970-15ecf080-9938-11eb-86e0-799588d2368a.png"> 

 Link to page: https://www.va.gov/discharge-upgrade-instructions/guidance - then answer the questions to match this 
[PDF](https://github.com/department-of-veterans-affairs/va.gov-team/files/6401425/DUW.pdf) to see the page in question, which is also contained in this PDF: 
[DoD Form 149 Page.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6401590/DoD.Form.149.Page.pdf)

- We need content and possibly SME support to rework the Air Force specific results page for the Wizard
- We need to change the **Download Form 149 CTA** link to a link to the AFRBA portal.

## Expected Results
If a service member chooses Air Force while filling out the Discharge Upgrade Wizard questions, AND if their answers currently direct them to download DD Form 149, they will now be directed to visit the AFRBA portal located at https://afrba-portal.cce.af.mil/#portal  

## Acceptance Criteria
- [x] AFRBA portal certificate issue is resolved by Alex Reber before this change is started
- [x] Air Force-specific content is identified and isolated so that these changes are not visible to Veterans from other branches of the military
- [x] Text that explains how to fill out the PDF form is removed and replaced with new content supplied by Content team - [see content in mockup](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23591#issuecomment-874870018)
- [x] Link to download DD Form 149 is removed
- [x] Link to AFRBA portal is added according to design [see mockup](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23591#issuecomment-874870018) 
- [x] Internal QA/unit/a11y testing
- [x] Peer review
- [ ] Internal staging review
- [ ] Staging review
- [ ] Deployed to Production

**Comment by MarciMcGuireGCIO** [comment]
Contacting Alexander Reger to let him know we are encountering a cert-related privacy error when accessing https://afrba-portal.cce.af.mil/#portal from outside the VA network.  
[Privacy error.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6299523/Privacy.error.pdf)

**Comment by zacharymorel** [comment]
> Contacting Alexander Reger to let him know we are encountering a cert-related privacy error when accessing https://afrba-portal.cce.af.mil/#portal from outside the VA network.
> [Privacy error.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6299523/Privacy.error.pdf)

I'm not  100% certain this is it, but I am pretty sure there's an issue with the certificate of the website or a privacy related issue.

**Comment by MarciMcGuireGCIO** [comment]
Attaching a screen shot of privacy error that occurs outside the VA.gov network.  I have emailed Alexandar Reber to let him know about the issue and to hopefully get the name of a contact who can help resolve it.
[Privacy error.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6304813/Privacy.error.pdf)

**Comment by MarciMcGuireGCIO** [comment]
Adding blocked label until the URL privacy issue is resolved.

**Comment by MarciMcGuireGCIO** [comment]
As of yesterday, Alexander did not have a timeline for when they will have the certificate issue resolved, but in the meantime we can work on the UI & content changes.

**Comment by MarciMcGuireGCIO** [comment]
https://afrba-portal.cce.af.mil/#portal is the correct link

**Comment by MarciMcGuireGCIO** [comment]
Blocked until we see the other content changes that are coming for Discharge Upgrade Wizard.  John Santos at OPIA and Margarete Ashmore at DoD are collaborating.

**Comment by MarciMcGuireGCIO** [comment]
@zkoppert I added links to the mockup and content in the acceptance criteria above so you can better estimate your effort.

**Comment by zacharymorel** [comment]
> @zacharymorel I added links to the mockup and content in the acceptance criteria above so you can better estimate your effort.

The Content, _text that explains how to fill out the PDF form is removed and replaced with new content_,  is the same as the link for _Link to AFRBA portal is added according to design_.

**Comment by zacharymorel** [comment]
I'm still not 100% clear on this. Let's groom it in sprint planning.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I'm
sorry -- I should have been more clear. They are the same link.  The recommended text has already been incorporated into the mockup.  @callen2563 can probably provide a Sketch link as well.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel sure thing! I know it's been a little while.

**Comment by zacharymorel** [comment]
So the steps that come with the form on the guidance page are not going to show?

**Comment by MarciMcGuireGCIO** [comment]
That's correct.  In this particular case (Air Force previously directed to fill out DD0149), the information in the latest mockup is all that will be displayed.

**Comment by zacharymorel** [comment]
Okay, thanks, I can give it an estimate then.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel -- Perfect; thanks!

**Comment by zacharymorel** [comment]
Link to mock up https://github.com/department-of-veterans-affairs/va.gov-team/issues/23591#issuecomment-874870018

**Comment by MarciMcGuireGCIO** [comment]
Mockup for this change can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23591#issuecomment-874870018

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO  Question regarding the link here that is purple under **Additional Resources**. 
This link leads us to => https://www.afpc.af.mil/Career-Management/Military-Personnel-Records/
Should that be exchanged as well? 

![Screen Shot 2021-07-20 at 2 10 16 PM](https://user-images.githubusercontent.com/26075258/126374107-026a38be-8808-475b-b383-4397bfde3441.png)

**Comment by MarciMcGuireGCIO** [comment]
That link looks like it is meant to be an additional resource, so I don’t know that I would change it.  If they had something unrelated to a discharge that needed to be changed, this is still a legit resource.  Agree, @***@***.******@***.***>?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarciMcGuireGCIO** [comment]
That link looks like it is meant to be an additional resource, so I don’t know that I would change it. If they had something unrelated to a discharge that needed to be changed, this is still a legit resource. Agree, @johnhashva ?

**Comment by johnhashva** [comment]
Yes, agree with you @MarciMcGuireGCIO (FYSA @zacharymorel )

**Comment by zacharymorel** [comment]
Thank you, I'll be leaving it then.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva - This is ready for internal staging review.   To see the change, respond to the questions in the wizard with the following answers: 

![image](https://user-images.githubusercontent.com/73354907/126823130-c2920024-fe19-4caf-a1b2-03a8b8443701.png)

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO It'll be ready soon. It's not quite on staging yet.

**Comment by zacharymorel** [comment]
There is a build issue right now with GitHub for both the website and api repositories. It appears to be backed up till 3pm EDT today.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel Everything looks good other than a couple small tweaks.  When I compare Staging to the mockup, it looks like the text wrapping lines up with the accordions instead of flowing out the full width of the div.   I also think that the action link icon is supposed green based on the feedback from the design intent.  Thanks! 

![image](https://user-images.githubusercontent.com/73354907/126824601-b7f604fe-2e50-4f89-89ea-f773a71c883e.png)

**Comment by zacharymorel** [comment]
Oh it's a green arrow. Whoops.  How'd I miss that.

**Comment by MarciMcGuireGCIO** [comment]
Well the initial design was blue.

**Comment by zacharymorel** [comment]
Well alrighty then. I shall be changing it.
