### ISSUE TITLE
[FE] My VA - (Pre QA) "Learn how to file a claim for disability" links to wrong page

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23072]
The "Learn how to file a claim for disability" should link to the "[How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/)" page. On staging, it's incorrectly directing the user to main [VA disability compensation](https://www.va.gov/disability/?_ga=2.202684881.1190016477.1618237465-1696807371.1617981758) page.

**Current State**
![23072 Incorrect link for how to file a claim for disability](https://user-images.githubusercontent.com/45603961/114424673-5a6dcb80-9b86-11eb-9b2e-ac2a7ca929d3.png)

**Desired State**
User should be sent to [this page](https://www.va.gov/disability/how-to-file-claim/) when clicking that link. Note that on staging this should link to the staging equivalent, and once launched on prod link to the prod page.

**Comment by Samara-Strauss** [comment]
Also, please maintain the original domain for this link. Right now, our staging page is linking to prod. My VA staging links should link to staging pages; My VA prod (once it launches) should link to pro pages.

**Comment by ajakabcin** [comment]
See also #23134 and #23073

**Comment by erikphansen** [comment]
This should be available on staging to validate.

**Comment by Samara-Strauss** [comment]
Validated! Looks great!
