### ISSUE TITLE
Can we auto-populate the cancellation reason?

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2308]
As a veteran, I don't want to click options that are not necessary so that I can cancel my appointment as quickly as possible.

We need to verify with business owners that our current plan of auto-filling the cancel reason is acceptable.

AC
- [ ] Documentation exists explaining whether or not cancellation options feed into any analysis VA-side. (If not, we could probably just auto-fill an answer instead of making the veteran choose.)

**Comment by jbalboni** [comment]
Based on discussions, it sounds like we don't want to auto-fill the answer and can close this?

**Comment by markgreenburg** [comment]
We are already auto-populating the cancellation reason, using:
1. The 'unable to keep appointment' reason
2. If not available, the next available reason
