### ISSUE TITLE
Notice of Disagreement VSA-QA Test Plan

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#23083]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

## Product/Feature summary

Allow veterans to file decision reviews using VA.gov

- [Product/Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/readme.md)
- Product/Feature Epics:
  - #2140
  - #4341 
- Product/Feature Copy deck(s): \[provide link, or type "In Design prototypes"]
- [Product/Feature Design prototypes](https://vsateams.invisionapp.com/share/8Y10I6K7DU9R#/screens/447558866_NOD_-_Info_Page)

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Kevin Stachura, Christian Valla
Content/IA: Beth Potts
Front-end: Robin Garrison
Back-end: Anna Carey
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/nod-use-cases.md

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [x] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by vhenry07** [comment]
Use cases added.

**Comment by tlei123** [comment]
@vhenry07 , thanks for starting the [Use Cases doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/nod-use-cases.md)!  I have a couple of **follow-up requests** for completion:
1.  **Design-links**: Please add **specific design-prototype link(s)** for each specific Case [cc @chrvalla @kevinstachura ].  IF there're absolutely no design-screens that are unique to a Case, then please indicate so explicitly.
The purpose of requesting design-links for each Case separately is to let me know what visually distinguishes one Case from another.
2.  **Access instructions**:  Please add a **specific Staging test-account** for each Case unless its flow's unauthenticated.  IF all Cases will be support with a single, common test-account, please indicate so at the top. [cc @annaswims @Mottie]
The assumption here is that there would be different user-specific API-data that support each of the Cases, and thus a different test-account to sign-in with.

Please tag me here if you have further questions, or once the doc's been updated for the above items.  Thanks much!

P.S.  No need to include common flow-steps in the Descriptions; each Case should have a brief flow description outlining what makes that Case unique.

**Comment by Mottie** [comment]
2. Access NOD:
  - Go to https://staging.va.gov/decision-reviews/board-appeal/request-board-review-form-10182
  - Log into any of the HLR test users (https://dsva.slack.com/archives/C5AGLBNRK/p1601069669025200?thread_ts=1601069567.024300&cid=C5AGLBNRK)
  - Design: https://vsateams.invisionapp.com/share/8Y10I6K7DU9R#/screens/447558866 
  - Note: It's still a WIP and we're missing a page - if the Veteran chooses "Hearing with a Veterans Law Judge" the next page will ask the type of hearing: virtual, video conference or central office.

**Comment by tlei123** [comment]
Thanks @Mottie for the answers above!

I have a few further follow-up questions [cc @vhenry07 @kevinstachura @chrvalla, in case you have any helpful input]:
[No big rush; I'll be busy standing-up my TestRail test-cases over the next couple of days]

- (3)  **[Info page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538562/play)**: Might the content under **Option 2**'s PDF-download link be replaced with a button/link that goes to the [form-intro page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538592), once the online-form's code-complete?
- (4)  **[Vet details [homeless y/n] page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538593)**: If I choose **Yes** (I'm homeless), would there be any addition page introduced to the flow [maybe for alternate contact-info] before [Vet details [rep y/n] page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538564)?
- (5) **[Vet details [rep y/n] page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538564)**:  If I choose **No** (no rep), I'm assuming [rep name page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538566) gets skipped.  Would you mind confirming this please?
- (6) **[Confirmation page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538545)**: Where does **Track the status of your claim or appeal** button (near bottom of page) go?

Please let me know when you have a chance.  Thanks much, and have a great weekend!  :)

P.S.  @vhenry07 , I have 1 [WIP TestRail test-case](https://dsvavsp.testrail.io/index.php?/cases/view/4741)* in-place (for [Use Case A](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/nod-use-cases.md#use-case-a)).  Feel free to check it -- you should have TestRail access to check the TR test-case -- and share your TR creds w/ anyone else who'd like to give it a look.

**Comment by Mottie** [comment]
Others might have further insights to my answers:

- (3) We don't have a method in place to allow uploading further evidence _after_ the NOD has been submitted. We'll need to confirm if the claim status tool has this capability already in place. If it does, we'll need to figure out how to link the NOD to this further evidence. If not, then it'll need to be built.
- (4) The homeless question does not have any additional pages
- (5) Rep page, choosing no will skip the rep info page; choosing yes will display it
- (6) The confirmation status button (which should be a link), goes to `https://staging.va.gov/claim-or-appeal-status/`, but as mentioned before, we'll need to check on the CST to confirm it supports NOD.

Additionally, there are other forks in the flow... on the board review option page (`/board-review-option`), choosing:
- "Direct review" does not add any additional pages
- "Submit addition" adds 2 additional pages, one asking if uploading will occur now and the second to upload documents
- "Hearing with a Veterans Law Judge" add one additional page asking about the hearing type.

**Comment by kevinstachura** [comment]
Hey @tlei123 - just wanted to add a bit more clarification to this question:

>(3) Info page: Under What are my... options? > Option 2, might the PDF-download link be replaced with a button/link that goes to the form-intro page, once the online-form's code-complete?

I think changing the copy on this section a bit might make sense! It was carry-over from when there was no digital NOD form in the works, so another look is warranted. 

In regards to the other questions, all of Robin's answers are spot-on 💯 let us know if you have any other questions! Thanks.

**Comment by tlei123** [comment]
@vhenry07 @kevinstachura @Mottie , I have a few remaining questions before starting test-runs:
* (7) All the **[Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/nod-use-cases.md)** mention "**check the opt-in button**", but I didn't see any on Staging.  Can you clarify please?
* (8) Have the **areas-of-disagreement** pages been dropped?  Here's [one of the designs](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292864).  I didn't see any of these pages on Staging.
* (9) Have the **issues-review** pages also been dropped?  Here's [one of the designs](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292872) [which shows an opt-in _checkbox_ (related to q7?)]  I didn't see any of these on Staging either.

Please let me know.  Thanks much!

**Comment by kevinstachura** [comment]
Hey, @tlei123! Glad to answer these and I apologize in advance for the confusion. Here's what I got:

To answer all of these questions generally, we split the 'Issues for review' flow into multiple pages (to satisfy the 'one task per page' principle) per the midpoint review. This meant that I had to change the design of that part rather substantially, and Robin had to then follow suit in doing so on staging - which isn't fully complete as of yet (a decent chunk of work).

> (7) All the Use Cases mention "check the opt-in button", but I didn't see any on Staging. Can you clarify please?

They'll get to this page towards the end of the 'issues for review' flow, but it may not yet be in staging as Robin works to split one page out into several.

> (8) Have the areas-of-disagreement pages been dropped? Here's one of the designs. I didn't see any of these pages on Staging.

Nope! More like these have been _added_ and it's a matter of coding them out at this point. Design is ahead of staging at the moment, in this regard.

> (9) Have the issues-review pages also been dropped? Here's one of the designs [which shows an opt-in checkbox (related to q7?)] I didn't see any of these on Staging either.

We actually have a page that [tells you which of these potentially needed to be opted in to the new system](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292872), as well as a summary page that[ lists **all** issues you'd like reviewed](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292874) - both of which will be added to staging.

@Mottie please feel free to fill in the gaps I may have missed here! And let me know if you have any follow-up questions, Tze. Thanks again!

- Kevin

**Comment by Mottie** [comment]
Kevin is correct... we may not have all the updated pages in place until near or maybe just past the end of this sprint (May 18). The midpoint review suggested some significant changes, so we won't need a QA review until the changes are all in place. I'll let you know when everything is available on staging. Thanks Tze!

**Comment by tlei123** [comment]
@vhenry07 , all QA test-runs now completed.

4 defects logged: #24984, #24990, #24993, #25601

QA-artifact links:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1870)
- [Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/6&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1070)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/234)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/235)
