### ISSUE TITLE
Remove placeholder text in form dropdowns/input fields

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23088]
## Acceptance Criteria
1. For input fields, remove the placeholder text that appears _(currently, it only displays on Required fields)_
2. For dropdown fields, remove the placeholder text that appears as the first option in the picker menu
2. The placeholder **option** should still exist, so that a user can select an empty row. However, the app should not display any text in the placeholder row. This change applies to the following dropdowns in the app:
     - Edit Address forms
          - Country
          - State (U.S. or military-driven)
          - APO/FPO/DPO
     - Direct Deposit form
          - Account type
4. Update the accessibilityLabel for the placeholder: "No selection made"

## Mockups for reference
![IMG_0170.jpeg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ad52c451-7b25-4c57-9235-3a280602ebf7)
### **Similar UX on va.gov:** 
![Screen Shot 2021-04-12 at 9.34.57 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/edf7cae6-54e1-4778-82be-4154aa8648c1)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
Note for QA: retest #23088 once this ticket is merged

**Comment by digitalken** [comment]
PASS 5/4/2021 - Looks good on iOS and Android.  Closing.
