### ISSUE TITLE
Add 'new appointment' button to appointments list(s)

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2309]
As a veteran, I want a 'new appointment' button in my appointments / pending appointments list so that I don't have to navigate around the tool to figure out how to create a new appointment if I'm already looking at my appointments list.

AC
- [ ] New button exists for 'add appointment' on the 'appointments list' page
- [ ] Page / button matches any mocks.

Page to update (note - the 'start over' button is just an invision artifact and doesn't represent where the new appt button should go):
<img width="1172" alt="Screen Shot 2019-10-09 at 5 02 17 PM" src="https://user-images.githubusercontent.com/24251447/66524010-d6c9af00-eab6-11e9-9c75-0c41e127376c.png">

**Comment by markgreenburg** [comment]
@goldenmeanie curious where you think this button should go. Could you please throw it into a mock?

**Comment by jenniemc** [comment]
@markgreenburg  here is the screenshot with schedule button located on the left
![image](https://user-images.githubusercontent.com/54327023/67307448-8e52be00-f4c6-11e9-9aef-0ff8e9671eb4.png)

**Comment by jenniemc** [comment]
@markgreenburg, just wondering if you got a chance to speak to Ryan about the layout of  schedule button on Confirmed Appt page. I included a screenshot of what i have so far on the the ticket 2309

**Comment by jenniemc** [comment]
added button to top right per @markgreenburg
