### ISSUE TITLE
QA Feedback - Midpoint Review - Booz Allen Education Applications - VRRAP

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#23098]
## Thoughts/questions
Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/22836.

Great work on testing the feature and logging everything in TestRail!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- TestRail test cases should be tested on multiple platforms in order to ensure feature functionality works as expected with different browsers and different OSes.

**Consider:**
-  Consider writing automated end-to-end tests for test cases defined in TestRail. TestRail cases should have their `Automation Type` changed to `Cypress` once this is implemented.

**Comment by amyknox** [comment]
@delli-gatti-michael & @sonntag-adam 
Wanted to be sure you saw this input.  Please close the issue after reviewing.

**Comment by delli-gatti-michael** [comment]
Thanks for the feedback!

For the "should" we are actually using multiple browsers, but could document that better in TestRail. We'll look into doing multiple test runs with a comment indicating the browser used. We'll also definitely take a look at our scripts and see what makes sense as an automated test.
