### ISSUE TITLE
Investigate Cypress tests hanging on Jenkins

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#23091]
Multiple teams have reported that Cypress tests hang indefinitely while running on Jenkins. Individual tests fail and then hang on the first retry. Cypress does not give any failure output after it hangs. This task is to determine the cause of these failures and to find a fix.

**Comment by pjhill** [comment]
@ddzz -- Now that we are in a post-parallelization world -- is this still an issue? Are teams still reporting this issue?

**Comment by pjhill** [comment]
Overcome by events
