### ISSUE TITLE
[Design] Home page detail navigation dive

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#23104]
The home page refresh includes "thumbnail" summaries on the home page and "detail" views of appointments for each thumbnail. These should be easy to navigate between.

Currently we have two ways to navigate from detail to the list of thumbnails on the home page:
* Standard breadcrumbs at top of page
* "Go back to appointments" link at bottom of page

The pain points this sets out to address:
* Both links return the user to the top of the home page, so they end up losing the context of their appointment in the broader calendar.
* Ideally, only one link is needed - two links add cognitive load to processing the page (unnecessarily, since they both do the same thing)

This looks at whether we can replace the breadcrumbs at the top of the page with a "back" link that returns the user to the home page, scrolled to the appointment they were just viewing.

![Appt detail nav rework.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/b9ddacdd-0c56-46c1-8ca3-0daf83e0b3be)

**Comment by outerpress** [comment]
Checked with VSP IA on this one and we'll need to plan user testing before moving forward since this change would affect the global navigation component. We'll consider testing along with the "back" form control, since they're similar concepts.

Here's a slightly more fleshed out version of the concept:

![VAOS home page navigation concept.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/2424bd57-3943-43b2-af59-7fd91a7501b3)

Iceboxing until we get more user testing bandwidth

CC: @laurenernest

**Comment by ldelacosta** [comment]
No longer need this ticket. Closing it out. cc: @JRRoof @outerpress
