### ISSUE TITLE
Smoke Testing

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23100]
## Description
Do we want to do any smoke testing pre-launch? With production data?

## Tasks & Status
**4/20**
- Jonathan to talk to Alastair

**Comment by ayushchak** [comment]
Analysis, per discussion with @jjulian:

Smoke testing is a process whereby we test various components of the app through the production environment. 

For the app: Smoke testing of the app has been completed and additionally planned through QA and UAT processes, including the API. Additional smoke testing is not required.
