### ISSUE TITLE
EDU Forms / 1990e:  Certification Content Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23118]
Content has been updated per EDU input	

* Content is reworked, as necessary 
* GH Doc is shared internally (UXBA team).   
* Respond to any questions

**Comment by JenLJ** [comment]
Updated existing document: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/1990e/1990e-outline-draft.md
