### ISSUE TITLE
EDU Form / VRRAP:  DEPO Midpoint Review	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23114]
VRRAP Review with DEPO 	

* DEPO Asynch Review of VRRAP Form  
* Review tickets and respond to input 
* Write new stories as needed

**Comment by amyknox** [comment]
Update content doc & prototype with all **"MUST"** input from DEPO Content review https://github.com/department-of-veterans-affairs/va.gov-team/issues/23069

* Per OCTO content recommendations, H2 should read: Follow these steps to apply

* Under: "Make sure you’re eligible" header:
--First bullet point should read: Between 22 and 66 years old
--Remove commas at the end of each bullet point
--Remove period at the end of last bullet

* Direct deposit information:
_(For user with pre-fill bank info - this is in our prototype and needs to be updated)_ This is the bank account information we have on file for you. We’ll send your housing payment to this account.
_(For user with no-bank info - we don't have this in the prototype but should add into content doc for posterity)_ We make payments only through direct deposit, also called electronic funds transfer (EFT). Please provide your direct deposit information below. We’ll send your housing payment to this account. 

* Program selection information screen
Add comma after “online”
Is the program in-person, online, or both?

* Review application screen
Under Program information accordion, please update the questions to match the edits that were made on that screen. For example:
• Do you know which program you'd like to enroll in? ( * Required) { Radio: yes or no }
• What's the name of the school or training provider? { free text }
• What's the name of the program? { free text }
• Which city is the program in? { free text }
• Which state is the program in? { free text }
• Is the program in-person, online, or both?

**Comment by amyknox** [comment]
Content doc is updated with OCTO-DE musts.
