### ISSUE TITLE
EDU Forms / VET TEC:  Certification Prototype - UXBA Review	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23117]
VET TEC prototype is reviewed w UXBA	
* Prototype is reviewed w B.A./TL 
* Updates are incorporated, if needed

**Comment by JenLJ** [comment]
Reviewed at PI Mini Sync on April 19th.  Updates were incorporated.  Prototype can be found at  https://bahdigital.invisionapp.com/share/EKIAGNW2V86
