### ISSUE TITLE
Removal of Team member from DSVA Slack

### ISSUE THREAD

**Issue by JQuaggles** [department-of-veterans-affairs/va.gov-team#2311]
Please remove the following person from the DSVA Slack. Offboarding request has been made in the #vfs-platform-support channel as well. 

James Hupp 
jameshupp@navapbc.com

Thanks!
-Josh

**Comment by LEHigley** [comment]
it looks like this was done?

**Comment by JQuaggles** [comment]
:thinking_face: 
Is the removal from DSVA slack part of the offboarding request now too? I thought they were separate which is why I usually make the request here as well. 
@batemapf ?

**Comment by batemapf** [comment]
yeah i've been handling slack removals as part of the [contractor offboarding process](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/4c04bcfab1ac4d8f551df4fd47a5e363db715ccc/Administrative/Onboarding%20and%20Offboarding/ContractorOffboarding.md). @JQuaggles what doc were you following that resulted in this request? i'll take a look at it and try to rectify the two.

**Comment by JQuaggles** [comment]
@batemapf Probably been updated and was following an older process. Also probably assumed that since slack items were all going through github that removal did as well.
