### ISSUE TITLE
CT Redesign: Comparison Tray Controls - Solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23111]
Document approaches to improve controls (button, labels, links) within the Comparison Tray	

* Explore possible ways to address the challenge on mobile devices and on desktop  
* Document approaches with greatest potential 
* Discuss pros/cons with UX team

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1619006037743/75a424fd8fb7f5662fb4038c7b5e762da651cdf8
