### ISSUE TITLE
VRRAP: Analytics Request

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23115]
Analytics story is prepped and ready to submit to VSP when development is complete	

* UX has reviewed analytics request collab cycle input in GH 
* UX has reviewed analytics request issue / template 
* UX has reconciled analytics with EDU-approved KPIs 
* UX submits request if functionality is in place & ready for analytics tags

**Comment by amyknox** [comment]
Analytics request collab cycle: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-analytics-request.md

Analytics request template https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D

VRRAP Product Outline (KPIs specifically) https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/product-outline.md#key-performance-indicators-kpis
