### ISSUE TITLE
1990s: Auto-Fill not working for all users on Staging

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#23124]
When a user starts the 1990s form, some of their data is automatically filled in. For some of the users on staging, the data does not populate.

### Steps to reproduce:
1. Access the 1990s form on Staging at https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s
2. Log in using the test account `vets.gov.user+8@gmail.com`
3. Begin the application
4. notice none of the fields are pre-filled

### Expected behavior
Fields such as first and last name, SSN, etc are pre-filled such as the below screenshot of the 0994 form
![Screen Shot 2021-04-13 at 9.16.40 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c1be7491-3fe0-4337-b4a1-c20e453da6cc)

### Actual behavior
No fields are pre-filled
![Screen Shot 2021-04-13 at 9.18.09 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/7a1fdc5d-f552-4bf8-af4c-08f24fae262d)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16767

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
This fix is now live on Staging. Closing this issue
