### ISSUE TITLE
[FE] My VA bug: For LOA1 user, "Benefits you might be interested in" won't load

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#23125]
## Background

Steps to reproduce:

1. Sign into staging with LOA1 user.
2. Go to My VA.
3. "Benefits you might be interested in" keeps showing the loading spinner but never loads.

Expected functionality: According to [the documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/loa1_design.md), we expect this section to load all three benefits (health care, disability, education) for all LOA1 users given that we can't detect what benefits they may or may not have. **If this is problematic given some of the logic we've applied to the LOA3 use case, let us know.**

<img width="1010" alt="Screen Shot 2021-04-12 at 3 40 48 PM" src="https://user-images.githubusercontent.com/34068740/114563771-b6475b80-9c3d-11eb-8d95-7c7a0973acf1.png">

## Tasks

- [ ] Confirm this bug
- [ ] Make it so "Benefits you might be interested in" automatically loads for all LOA1 users

**Comment by erikphansen** [comment]
This can be validated.

**Comment by Samara-Strauss** [comment]
Validated! Looks great.
