### ISSUE TITLE
[FE] My VA bug: "Health care" block is showing in "Benefits you might be interested in" section after an application has been started

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#23128]
## Background

Steps to reproduce:

1. Sign in to staging with user 272.
2. Go to My VA. You should **not** see a health care app in progress, and you should see the "Health care" block showing under "Benefits you might be interested in."
3. Go to the health care app and start an app. Save it in progress.
4. Go back to My VA.
5. You will still see the "Health care" block showing under "Benefits you might be interested in."

Expected functionality: According to [the documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/apply-for-benefits.md#states) this block should disappear once you have started an application (look under **State 1B: A user who has an in-progress health care, disability, OR education application**). 

**If we no longer thinks this makes sense, or if there are issues with this, let us know.**

<img width="1280" alt="Screen Shot 2021-04-13 at 10 02 12 AM" src="https://user-images.githubusercontent.com/34068740/114565657-7a14fa80-9c3f-11eb-967d-ee5eaf30a7ed.png">

## Tasks

- [x] Confirm bug
- [x] Make it so that the "Health care" block is goes away in "Benefits you might be interested in" section after an application has been started.
- [ ] **After you've made this fix, please delete the in-progress app for user 272 so we can use this user for QA. You can do this by going to https://staging.va.gov/health-care/apply/application/introduction, starting a new app, and then clicking the "Back" button without saving in progress. This should delete the current app so that user no longer has one.**

**Comment by erikphansen** [comment]
This can be validated

**Comment by Samara-Strauss** [comment]
Validated! Working as expected.
