### ISSUE TITLE
[FE] My VA bug: Cerner alert should be 2/3 width on desktop

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#23133]
## Background

Steps to reproduce:

1. Log in to staging with user [ssoissoetesting+mhvcss4@gmail.com](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-cerner.md) on desktop.
2. Go to My VA.
3. You'll see the Cerner alert (good!), but it's full width when it should be 2/3 width.

Expected functionality: The Cerner alert should be 2/3 width on desktop.

<img width="989" alt="Screen Shot 2021-04-12 at 3 20 19 PM" src="https://user-images.githubusercontent.com/34068740/114576805-77b79e00-9c49-11eb-949c-f203f55c78ca.png">

## Tasks

- [x] Give the Cerner alert a max width of 2/3 width on desktop

**Comment by ajakabcin** [comment]
Confirmed on staging
