### ISSUE TITLE
[FE] My VA bug: "What benefits does the VA offer?" links all have weird numerical slug

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#23132]
## Background

Steps to reproduce:

1. Log in with any staging user.
2. Go to My VA, and scroll down to the "Apply for benefits" section.
3. Open the "What benefits does the VA offer?" section.
4. Click into those links. They all go to the right place, but they all have a weird numerical slug. This is an example of the one for the health care link: https://www.va.gov/health-care/?_ga=2.19349816.1402723902.1618233318-334419980.1612381530

Expected functionality: We do not include a numerical slug at the end of the links to the benefit hub landing pages. **Additionally, all of these links should stay in the same domain. So, since we are in staging right now, they should link to staging. Once we launch to prod, those links should go to those pages in prod.**

## Tasks

- [ ] Fix domain issue — all of these links should stay in the same domain. So, since we are in staging right now, they should link to staging. Once we launch to prod, those links should go to those pages in prod.

**Comment by Samara-Strauss** [comment]
Also: All these links go to prod, when they should stay in staging if the click is initiated from staging. I'll add this to the first comment in the ticket.

**Comment by erikphansen** [comment]
[PR merged](https://github.com/department-of-veterans-affairs/vets-website/pull/16789) so this can be validated on staging soon.

**Comment by Samara-Strauss** [comment]
Validated!
