### ISSUE TITLE
VRRAP: Update content based on DEPO midpoint review

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23138]
As a developer, I need to update the content of the VRRAP application form so that it is consistent with DEPO content best patterns and practices.

## Assumptions:
1. VRRAP introduction page on staging: https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction
2. The "Bank Name" field does not need to be included / re-added to the widget.
3. Any updates to the direct deposit content or widget are specific to the 1990s (VRRAP form) only.

## Acceptance Criteria
1. On the introduction page in the "Make sure you're eligible" section:
    a. The bullet `At least 22 years of age but not more than 66 years of age,` is replaced with: `At least 22 years old, but not older than 66`
    b. Each bullet point statement does not have ending punctuation (comma or period).

2. In the direct deposit section, when no pre-fill data is available:
    a. The following content is displayed below the "Direct deposit information" header:

    > We make payments only through direct deposit, also called electronic funds transfer (EFT). Please provide your direct deposit information below. We’ll send your housing payment to this account.

    b. The default form state can be seen in SA5
    c. When the user clicks "save:, the form state converts to the form state seen in SA4.

3. In the direct deposit section, when pre-fill data is available:
    a. The following content is displayed below the "Direct deposit information" header when the pre-fill data has not been changed by the applicant:

    > This is the bank account information we have on file for you. We’ll send your housing payment to this account.

    b. The default form state can be seen in SA4.
    c. When the user clicks "Update Account Information", the form state converts to the form state seen in SA5.
4. The "What if I don't have a bank account ~or don't want to use direct deposit~?" help link and drop down content is replaced with the content below:

> { help-link } What if I don’t have a bank account? { end help-link }
> 
> { help-text}
> 
> The Veterans Benefits Banking Program (VBBP) provides a list of Veteran-friendly banks and credit unions. They’ll work with you to set up an account, or help you qualify for an account, so you can use direct deposit.
> 
> To get started, call one of the participating banks or credit unions listed on the VBBP website. Be sure to mention the Veterans Benefits Banking Program. After you have direct deposit set up, call the GI Bill Hotline at 888-442-4551. We're here Monday through Friday, 8:00 a.m. to 7:00 p.m. ET.
> 
> Note: The Department of the Treasury requires us to make electronic payments. If you don’t want to use direct deposit, you’ll need to call the Department of the Treasury at 888-224-2950. Ask to talk with a representative about waiver requests. They can answer any questions or concerns you may have.
> 
> { collapse help content link }

5. On the Review application (Chapter 1, Page 2)
    a. The Bank account number is masked.
    b. The Bank routing number is masked.

## Supporting Artifacts:
1. Originating Issue: #23069 
2. AC1 Update Location:
<img width="522" alt="Screen Shot 2021-04-13 at 1 03 38 PM" src="https://user-images.githubusercontent.com/48260534/114593334-fcaab380-9c59-11eb-96e4-7ca8a7838aa2.png">
3. AC2 & AC3 Update Location:
<img width="405" alt="Screen Shot 2021-04-13 at 1 12 45 PM" src="https://user-images.githubusercontent.com/48260534/114593358-046a5800-9c5a-11eb-9db2-2d67bd51341d.png">

4. [Direct Deposit Input State](https://design.va.gov/patterns/form-templates#input-state)

5. [Direct Deposit Review State](https://design.va.gov/patterns/form-templates#review-state)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16786/

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-04-15 at 11.29.07 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/93f90363-cef7-4fcc-a569-b204e3b7e460)
##
![Screen Shot 2021-04-15 at 11.32.29 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/93062ad8-b43f-4e41-afbe-3edbd627d599)
##
![Screen Shot 2021-04-15 at 11.33.09 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/da8e0d1b-cf6f-4b69-aba8-c9b999a97901)
##
![Screen Shot 2021-04-15 at 11.35.30 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ca5a90f2-1b3d-4709-9e37-d57fa006bb60)
##
![Screen Shot 2021-04-15 at 11.33.19 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f7d0dfd5-beb4-4dd3-ab53-0293d042a52c)
##
![Screen Shot 2021-04-15 at 11.36.05 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/123abb97-bf4b-4a20-bfe9-0f617ab44c61)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1703&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah ready for review

**Comment by amyknox** [comment]
UX 1/2: This checks out for me

There's  a discrepancy between the content doc and AC and the prototype for { help-link } What if I don’t have a bank account?.  The "Note:" isn't bold in the content doc and AC but is in the prototype and in the implementation. The bold "Note:" looks & feels right to me.

**Comment by JenLJ** [comment]
UX 2/2:  When bank account information is pre-filled, the label needs to be "Bank account number" instead of "Account number"

**Comment by ksantiagoBAH** [comment]
Additional PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16830 
![image](https://user-images.githubusercontent.com/50601724/115071812-b4db9480-9ec4-11eb-91b1-22d7fb0ae9c5.png)

**Comment by sonntag-adam** [comment]
Fixed in staging. Closing story.

![Screen Shot 2021-04-19 at 11.15.27 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/597259e7-906e-47b3-aa3d-2543156c0be6)
