### ISSUE TITLE
[FE] My VA bug: "View your VA medical records" should go straight to MHV

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#23134]
## Background

Steps to reproduce:

1. Log in to staging with user 226 or any user that has health care.
2. Scroll to the Health care section and click "View your VA medical records". You'll notice this goes to https://staging.va.gov/health-care/get-medical-records/ when it should link directly into MHV staging.

Expected functionality: This link should go directly to MHV staging: https://sqa.eauth.va.gov/mhv-portal-web/eauth?deeplinking=download_my_data

## Tasks

- [x] Update "View your VA medical records" link to https://sqa.eauth.va.gov/mhv-portal-web/eauth?deeplinking=download_my_data

**Comment by ajakabcin** [comment]
Confirmed on staging
