### ISSUE TITLE
Requesting access to Google Analytics for the VSA Debt Team

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#23131]
# Requesting access to Google Analytics for the VSA Debt Team

https://github.com/department-of-veterans-affairs/va.gov-team/issues/22714 - Requesting Google Analytics access for the the following users on the VSA Debt Team

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

Would like to request access for the following VSA Debt Team members:

- cwheeler@governmentcio.com
- jlinn@governmentcio.com
- lkeeler@governmentcio.com
- rebecca.walsh@adhocteam.us
- riley@amida.com
- triser@governmentcio.com
- kmircovich@governmentcio.com

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [ ] Domo

## Date Required
_Please share the date you require access._
By the end of Sprint 45 which is due by Apr 19, 2021

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

- VSA Debt Resolution Team

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @craigwheeler , 

The folks you listed should now all have Google Analytics access. Some folks such as Leah and Rebecca had existing access that was just increased to Collaborator (so they may not have received an email). 

Please let me know if any folks have any access related issues -- I'll close this ticket but please feel free to reopen should you have any questions/concerns.
