### ISSUE TITLE
VRRAP: Program Selection update content

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#23130]
## Steps to reproduce:
1. Navigate to https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s
2. Log in with a user https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv
3. Select "Start the education application"
4. Following section needs the correct text
![Screen Shot 2021-04-13 at 10.26.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/eca1e132-48d7-4239-979b-379f4f8fac86)

## Expected results:

Program information
• Do you know which program you'd like to enroll in? ( * Required) { Radio: yes or no }
• What's the name of the school or training provider? { free text }
• What's the name of the program? { free text }
• Which city is the program in? { free text }
• Which state is the program in? { free text }
• Is the program in-person, online, or both? {radio: In-person, Online, Both in-person and online}

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16769

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on Staging and ready for review

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me

**Comment by amyknox** [comment]
UX Review 2/2: This checks out for me, too
