### ISSUE TITLE
[FE] My VA fix: Update copy for Health care link under "Benefits you might be interested in"

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#23135]
## Background

Steps to reproduce:

1. Log in with user 272.
2. Go to My VA, and scroll down to the "Apply for benefits" section.
3. Under the "Benefits you might be interested in", the "Health care" link is labeled "Apply for VA health care". It should be labeled "Learn how to apply for VA health care". **Additionally, this link is going to prod when it should go to staging.**

Expected functionality: Change the "Health care" link label from "Apply for VA health care" to "Learn how to apply for VA health care". Also, change the link so it links to staging from staging, not to prod from staging.

<img width="934" alt="Screen Shot 2021-04-13 at 10 16 03 AM" src="https://user-images.githubusercontent.com/34068740/114580599-fd891880-9c4c-11eb-8fc4-779cbf1dad49.png">

## Tasks

- [ ] Change the "Health care" link label from "Apply for VA health care" to "Learn how to apply for VA health care"
- [ ] Change the link so it maintains the right domain — My VA staging links should go to staging pages; My VA prod links should go to prod pages.

**Comment by erikphansen** [comment]
This is ready to be validated

**Comment by Samara-Strauss** [comment]
Looks good to me!
