### ISSUE TITLE
Content Feedback - Midpoint review - VSA Caregivers, Sign as representative

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#23141]
## User story
VSP content review of sign as representative screens in this [prototype](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666490/simulate/sitemap?mode=i)
- The new Representative documentation question page 
- The new document upload page
- And the signature/review page - this page is being edited and the veteran signature box changes to a representative signature box if they choose one of the yes options

## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

**Comment by peggygannon** [comment]
@ala-yna @sshein 
VSP content feedback for sign as representative screens is below. Please let me know if you have questions. 

**Questions**
- There seems to be 2 upload documentation screens in the prototype with slightly different content. Which screen has the up to date content? 

- On signature review screen:  It looks like the checkbox before the privacy line is missing. Is this intentional? 


**Should** 
Our style is to use contractions. Please ensure consistence use throughout the new screens. you are should be: you're

**Comment by sshein** [comment]
This is the current upload page https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666491/simulate/sitemap?mode=i

on the signature page, we put the privacy line in the signature boxes themselves so users weren't having to fill out the signature boxes as well as check another box before the submit button. 

Noted regarding contractions, thanks!

**Comment by peggygannon** [comment]
thanks, @sshein I've updated my feedback above ^^ to include content recommendations to the Upload screen.

**Comment by sshein** [comment]
thank you! incorporated all your suggestions for the upload page
