### ISSUE TITLE
Discharge Upgrade Wizard - [Discovery] - Get familiar with the product, tech, & strategic analysis

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23142]
## User Story

_As a member of the Decision Tools team, I want to understand the Discharge Upgrade Wizard product so that I can make recommendations on how to improve it according to our value categories - Findability, Ease of Use, Service Completion, Trust, and Health

## Expected Behavior

Review the existing product, any metrics available, and note areas of concern, areas for improvement

## Acceptance Criteria

- [ ] Evaluation notes are stored in GH product folder
- [ ] New issues related to areas for improvement are added to GH icebox for grooming

**Comment by zacharymorel** [comment]
Notes from discovery found: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/discharge-upgrade-wizard/post-mvp/technical/tech-evaluation-04-2021.md
