### ISSUE TITLE
Discharge Wizard - Possible rewrite any code that is needed

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#23157]
## Issue Description
We recently took on Discharge Wizard, here we are:

   1. Rewrite any code as I found during the process of evaluating, adding testing, moving files.

Previous discovery => https://github.com/department-of-veterans-affairs/va.gov-team/issues/23142

## Acceptance Criteria
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] All axe checks pass
- [ ] Peer reviews code
- [ ] Code works as it did before changes

**Comment by MarciMcGuireGCIO** [comment]
This is not urgent; more "nice to have".

**Comment by MarciMcGuireGCIO** [comment]
Potential this could become an epic if numerous issues are uncovered as Zach implements unit testing

**Comment by zacharymorel** [comment]
Running list of things discovered as during implementing new tests and rewriting new tests:

1.  Rewrite Redux state management system.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel should I leave this issue open, or is it good to go? Thx!

**Comment by zacharymorel** [comment]
We can leave it open until the PR is merged!

**Comment by zacharymorel** [comment]
PR merged and life is peachy!

**Comment by MarciMcGuireGCIO** [comment]
🥳 Woooo!
