### ISSUE TITLE
Discharge Upgrade Wizard - Organization of Application

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#23156]
## Issue Description
We recently took on Discharge Wizard, here we are:
   1. Update and reorganize the folder structure to current standards

Previous discovery => https://github.com/department-of-veterans-affairs/va.gov-team/issues/23142

## Front end tasks
- Reorganize the current application code folder structure to current standards

## Acceptance Criteria
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] All axe checks pass
- [ ] Folder structure makes sense

**Comment by MarciMcGuireGCIO** [comment]
Could be a high risk, so should be done after unit tests are incorporated into the product.

**Comment by MarciMcGuireGCIO** [comment]
🥳
