### ISSUE TITLE
508-defect-2: Add information buttons must not rely on color

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#23159]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Josh_

## Details

Buttons must not rely on color. Affordances are provided only on hover, which is not available to mobile users.

## Acceptance Criteria

- [ ] Buttons do not rely on color to convey that they can be interacted with 

## Proposed Solution

Use a secondary button style. Consider shortening the text so it fits on mobile.

## WCAG or Vendor Guidance (optional)

* [WCAG 1.4.1: Use of Color](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html)

## Screenshots or Trace Logs

<img width="702" alt="Screen Shot 2021-04-13 at 3 15 31 PM" src="https://user-images.githubusercontent.com/14154792/114608464-b65e5000-9c6b-11eb-832c-61ec21351a15.png">
<img width="608" alt="Screen Shot 2021-04-13 at 3 18 42 PM" src="https://user-images.githubusercontent.com/14154792/114608465-b6f6e680-9c6b-11eb-981c-5a898f955ab5.png">

<img width="539" alt="Screen Shot 2021-04-13 at 3 22 50 PM" src="https://user-images.githubusercontent.com/14154792/114608968-40a6b400-9c6c-11eb-8004-90b33bb98207.png">

**Comment by ajakabcin** [comment]
We'll resolve this issue with #22742. Closing this as work will be addressed in 22742.
