### ISSUE TITLE
Discharge Upgrade Wizard - Testing Upgrades

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#23155]
## Issue Description
We recently took on Discharge Wizard, here we are:
1. Updating end to end test
2. Adding unit tests
3. Adding integration tests

Here's the recent discovery for the product:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/23142

## Acceptance Criteria
- [ ] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [ ] All axe checks pass

**Comment by MarciMcGuireGCIO** [comment]
There is currently no test coverage for this product because NightWatch has been deprecated.

**Comment by MarciMcGuireGCIO** [comment]
Nice job, @zacharymorel !
