### ISSUE TITLE
"Subject:" does not display the form field value

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23166]
## What happened?
On the message list views _and_ the message detail pages, the "Subject: Subject line" should be dynamic. "Subject:" and "subject line" are 2 distinct fields that come from the API. 

Currently, the "Subject:" appears to always be hard-coded. It is not displaying service-driven data as expected. 

## Specs:
- Devices: all
- Test user: vets.gov.user+261@gmail.com

## Steps to Reproduce
- Log in with user that has Secure Messages
- Notice that in all list pages (Inbox, Sent, Custom folder list), "Subject:" displays across all messages
- Navigate to the message detail page(s). Notice how the page header always displays "Subject:" before the dynamic subject line. 

## Desired behavior
1. "Subject:" is not hard-coded on both the message list pages and the message detail pages
2. "Subject:" is a mandatory field and will only ever display as 1 of the following options:
     - General
     - COVID
     - Appointment
     - Medication
     - Test
     - Education
3. If the message does not contain "Subject line" (which is an optional field), do not display a colon <:> after the "Subject"

Example of how this should display if "Appointment" is the subject and "Appt on Mar 2" is the subject line:
- **Appointment: Appt on Mar 2**

Example of how this should display when "Appointment" is the subject and there is not a subject line:
 - **Appointment**

## Acceptance Criteria
See desired behavior.

## Bug Severity
- 3 - Medium

## Linked to Story
#21195, #21081, #21197

## Screen shot(s) and additional information

(L) = designs
(R) = build
![Screen Shot 2021-04-13 at 12.51.41 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/6aa68f49-c55d-4ba4-af34-e525729bb402)

**Comment by digitalken** [comment]
PASS 4/22/2021 - Looks good, closing.
