### ISSUE TITLE
Design | Language Assistance and Resource Page Links | Footer Placement

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#23160]
Request for mock to use for usability testing that shows placement of spanish, tagalog and other link in VA.gov footer.

Text is as follows:

~Support | Espanol | Tagalog | Other~

**Language support**
Español | Tagalog | Other languages

**Comment by DanielleThierryUSDSVA** [comment]
Hi, just updating this with the full text. Also chatted with Ryan via slack and we agreed we should add "Language" so that people scanning headers will better understand the context.

Language support in:
Español | Tagalog | Other languages

**Comment by rtwell** [comment]
Ok gang i have some comps for your review. I have included 2 versions depending on the bandwidth of this work:
1. [comp 1](https://www.sketch.com/s/d4137b22-6930-46e1-8158-37718cc36265/a/Vrojxjl)—leaving the footer as-is _except_ for adding the Language support section
2. [comp 2](https://www.sketch.com/s/d4137b22-6930-46e1-8158-37718cc36265/a/KvRVgVV)—updating the rest of the footer while we're in there:
    a. Change the headers to sentence case
    b. Adjust the spacing between the headers and the first line of type that follows (snugging them up a bit)
    c. Remove the last `|` from "Veterans Portrait Project" so inline lists do not end in a `|`
3. Language support collapses into its own accordion on mobile ([seen here](https://www.sketch.com/s/d4137b22-6930-46e1-8158-37718cc36265/a/YG54x4E))

Let me know if anyone has questions are has trouble accessing the comps

**Comment by SKasimow** [comment]
Thanks @rtwell   I can't access the comps. Can you add me to Sketch or send a guest link?

**Comment by SKasimow** [comment]
@rtwell Thanks Ryan - these look great! I like the improvements you made in 2nd option as it shows more clearly what belongs under each heading.

Adding in @DanielleThierryUSDSVA , @mpeterz and @mnorthuis for feedback.

**Comment by DanielleThierryUSDSVA** [comment]
Agree, option 2 is perfect! Thank you so much for helping us with this, @rtwell. I really appreciate it. 

Also wanted to note that we're just today adding a "LGBT Veterans" link in the first programs and services list of links. Should be live in today's deploy.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/54a4bad9-77c2-4ee9-8fb2-53f5ff0300ec)

**Comment by DanielleThierryUSDSVA** [comment]
@johnhashva @brianalloyd Tagging you both here for awareness as the translation effort evolves. Feel free to reach out with any questions. Thanks!
