### ISSUE TITLE
[Discovery] Facility Locator Design

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2316]
**User Story**
As the new Facility Locator team, we need to be familiar with the current product so we have the best information possible to plan the next version of the product. 

**Goal(s)**
Conduct a round of evaluative usability testing of the current Facility Locator tool to:
1. understand bright spots and pain points
2. gain insights into how users expect the tool to work (e.g., search by facility name, search by services, search by task, etc.)

**Outcome**
Research readout summary which includes findings, recommendations, additional questions

**Comment by arickalewis1** [comment]
Submitting the research plan for review @lalexanderson-dsva 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/discovery-sprints/user-research/research-plan.md

**Comment by mmiddaugh** [comment]
This work is complete except for final synthesis and readout which are captured in [3164](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3164)
