### ISSUE TITLE
Publish Newsletter style guide V2 (Publish Monthly Newsletter)

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#23165]
# User story
To come.

# Tasks
- Add April examples
- Add content about voice, tone, casing, word choice, etc.
- Add Hemingway link and blurb
- Move from Amy's personal space to a more public space

# Acceptance criteria
To come.

# Reference info
To come.

**Comment by andreahewitt-odd** [comment]
Newletter no longer exists -- closing
