### ISSUE TITLE
Analytics Implementation or QA Support for Claims & Appeals - Notice of Disagreement

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#23163]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

Google Analytics

- Who is this request for?

    - [Ronnie Henry @Ronnie]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _Claims & Appeals
    
    - [[Notice of Disagreement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/readme.md)]
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. https://www.va.gov/decision-reviews/board-appeal/request-board-review-form-10182/_
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Anticipated launch - mid-late May]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [Board Appeals Page](https://www.va.gov/decision-reviews/board-appeal/)
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - 
![image](https://user-images.githubusercontent.com/77287545/114611724-57023f00-9c6f-11eb-9a1c-c1336fe587a3.png)

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Test users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md)
- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by laurensimpson14** [comment]
@jonwehausen I've completed this ticket's request to "Identify if PII is passed in URL or title tag." Below are my notes for the form flow for: https://www.va.gov/decision-reviews/board-appeal/request-board-review-form-10182/

##Form Flow
1. https://staging.va.gov/decision-reviews/board-appeal/request-board-review-form-10182/veteran-information
     *Veteran Information
          *Name (JUDY SNOW MORRISON)
          *Social (●●●–●●–1976)
          *VA file number (●●●–●●–1976)
          *Date of birth (March 31, 1953)
          *Gender (Female)
     *GA event: Vetsgov 10182-board-appeal-sip-form-loaded 
2. https://staging.va.gov/decision-reviews/board-appeal/request-board-review-form-10182/contact-information
     *Veteran Information
          *Home phone (313-622-0000)
          *Email address (judymo@gmail.com)
          *Mailing address: (521 W Cedar St Rawlins, WY 82301)
     *GA event: None
3. https://staging.va.gov/decision-reviews/board-appeal/request-board-review-form-10182/homeless
     *Veteran Information
          *Homeless? y/n
     *GA event: None
     *\*After selecting "no" a notification came up that said "Your application has been saved. It was last saved on April 22, 2021 at 9:40 am
          *GA event: Vetsgov 10182-board-appeal-sip-form-saved
          *It resaved & triggered the event each time I changed my answer from yes to no or no to yes
4. https://staging.va.gov/decision-reviews/board-appeal/request-board-review-form-10182/representative
     *Representation
          *Do you have a representative, like a Veteran Service Organization (VSO) or a VA-accredited attorney or agent helping you file this appeal? (y/n)
     *GA event: None
     *\*after selecting an answer, the ga event for saving the form fired again
5. https://staging.va.gov/decision-reviews/board-appeal/request-board-review-form-10182/eligible-issues
     *Issues eligible for review (step 3 of 5)
          *Check box that you understand 
     *Ga event: None
     *Application saved event firing
     *Saw an alert that said "(*Required) and **would not let me continue** even though the box was checked

##PII Search in Google Analytics in `VA.gov - Non-Production Environments` property and `All Web Site Data - VA.gov Testing Environments` view
*No **email addresses** found when searching for the test user's email (judymo@gmail.com) or when filtering with "@" on the All Pages report
*No **social security #'s** found when searching for the test user's number (●●●–●●–1976) or when using this regex: (\d{3}-?\d{2}-?\d{4})
*No **home address** found when searching the test user's (521 W Cedar St Rawlins, WY 82301) or when using this regex: (drive|street|road|dr.|po box|rd.)
*No **phone numbers** found when searching the test user's (313-622-0000) or when using this regex: (\d{3}-?\d{3}-?\d{4}) or (\d{3}\d{3}\d{4})
*No **first or last names** found when searching the test user's name (judy|snow|morrison) or when using this regex: (fn|ln|lastname|firstname|name|fullname) or this regex for common names: (j(im(my)?|ohn|ames)|robert|bob(by)?|michael|dav(id|e)|(d|r)ic(k|hard)|ch(arl(es|ie)|uck)|pat(ty|ricia)|linda|barb(ara)?|e?liz(zy|abeth)|jenn?(ifer)?|mari(e|a)|su(e|san)|sarah?)

**Comment by jonwehausen** [comment]
Hi @laurensimpson14 , 

Thank you for walking through the flow and identifying there is no PII. With this being a new implementation request, see guidance on next steps below: 

- [ ] Read and review and [product documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/readme.md) on KPIs (or request from Veronica if can't find) 
   - [ ] If needing to, schedule a meeting to review those KPIs and other product analytics tracking needs
- [ ] Ensure [forms library events ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/tracking-form-events.md) are tracking appropriately. 
- [ ] Ensure the proper product prefix is used and any GTM updates to our form events have been made 
- [ ] Determine if there are any further additional data layer variables necessary to fulfil KPIs
- [ ] Setup a Goal within Google Analytics with the form similar to other forms with the funnel steps above included

**Comment by joanneesteban** [comment]
@vhenry07 @Mottie Hello! When are you anticipating needing these analytics? We have some team changes and out of offices, and are looking to see if we need to readjust on our assignments for the next couple of weeks. Thanks!

**Comment by Mottie** [comment]
I believe the board is expecting our form to be done, or nearly ready for production, by the end of this month. @vhenry07 knows the exact date.

**Comment by vhenry07** [comment]
Robin's correct. By end of the month most likely.

Veronica Henry | PMP
Sr. Product Manager
| *mobile* 702-509-6192
| *e.* ***@***.***

**Comment by joanneesteban** [comment]
Thank you both for the quick response!

**Comment by laurensimpson14** [comment]
Hi @vhenry07 How can I access the form? When I go to https://www.va.gov/decision-reviews/board-appeal/request-board-review-form-10182/ I get a "sorry, we can't find that page" notice. 

I tried logging into staging with the test users you provided, but even for those I'm only seeing the option to download the board review form on the https://www.staging.va.gov/decision-reviews/board-appeal page. Thank you!

**Comment by Mottie** [comment]
Hi @laurensimpson14 the URL has changed to https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182 - `board-review` has changed to `board-appeal`

**Comment by laurensimpson14** [comment]
@Mottie and @vhenry07 Thank you for your patience on this ticket. I've QA'd the form's library events below to ensure they are tracking properly. I've also added your product prefix (`10182-board-appeal`) to out GTM lookup tables. @bsmartin-ep the GTM changes are in the ["23163 - Claims & Appeals" workspace](https://tagmanager.google.com/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Ftag-manager%2F#/container/accounts/144676348/containers/2214120/workspaces/1000530). I don't believe there are any additional data layer variables necessary. 

This form has also now been configured as a Goal within Google Analytics in slot 8 in the VA.gov Production property in the Disability and Claims Modernized view [here](https://analytics.google.com/analytics/web/#/a50123418w177519031p184341898/admin/goals/table). Please take a look at this screenshot of the URLs that I used for the Goal's funnel and let me know if there are any steps in the form that are missing: 
![image](https://user-images.githubusercontent.com/80417436/119866243-9cf72780-beea-11eb-98c8-a37f8247433e.png)


### QA
| Step in Form Process       | Interaction                                                                                 | dataLayer Event                     | Screenshot | QA Status |
|----------------------------|---------------------------------------------------------------------------------------------|-------------------------------------| -- | -- |
| Form Starts                | Form Start - Starting application without logging in                                        | `no-login-start-form`                 |
| Form Starts                | Form Start - Call-to-action to **Sign In** to start form                                    | `login-link-clicked-cta-form`         | ![image](https://user-images.githubusercontent.com/80417436/119860656-8e0d7680-bee4-11eb-9f7e-bd9caf7a68f0.png) | ✔️ Tracking Correctly |
| Form Starts                | Form Start - Begin form button after successful sign in                                     | `login-successful-start-form`        | ![image](https://user-images.githubusercontent.com/80417436/119860692-96fe4800-bee4-11eb-8cb5-093b3f66f470.png) | ✔️ Tracking Correctly |
| Form Loaded               | Form Loaded - Clicking the "Continue your request" button                                     | `<product>-sip-form-loaded`        | ![image](https://user-images.githubusercontent.com/80417436/119860724-a1b8dd00-bee4-11eb-8f81-28679aa0f38c.png) | ✔️ Tracking Correctly |
| Form Saves and Submissions | Form Saves - Event is triggered for auto form saves                                         | `<product>-sip-form-saved`          | ![image](https://user-images.githubusercontent.com/80417436/119851347-539fdb80-bedc-11eb-99f5-7e429d103012.png) | ✔️ Tracking Correctly |
| Form Saves and Submissions | Form Submission - Measure the form submission; Success and failures are measured distinctly | `<product>--submission`             | ![image](https://user-images.githubusercontent.com/80417436/119851434-64505180-bedc-11eb-97e0-89304a47d037.png) | ✔️ Tracking Correctly |
| Form Saves and Submissions | Form Submission Successful - Triggered when the form has been successfully submitted        | `<product>--submission-successful`  | ![image](https://user-images.githubusercontent.com/80417436/119851507-7205d700-bedc-11eb-9e49-6ee1c8693595.png) | ✔️ Tracking Correctly |
| Form Saves and Submissions | Form Failures - Triggered when the form has failed server-side                    | `<product>--submission-failed`      |
| Form Saves and Submissions | Form Failures - Triggered when the form has failed in the client                            | `<product>--submission-failed-client`|

There are three events that I wasn't able to QA: 
1. `no-login-start-form`: Is there a way to begin this form without logging in? If not, then this event isn't applicable. 
3. `<product>--submission-failed`: About an hour ago I was having no problems submitting the form, which is how I was able to QA the `<product>--submission-successful` and `<product>--submission` events. However, I'm now getting the same error on every test user that I try. It's an error that says, "We’re sorry. Some information in your request is missing or not valid". ![image](https://user-images.githubusercontent.com/80417436/119865500-b9469480-bee9-11eb-8790-9b56e4109e56.png). However, when I go into the section that it says is not filled out entirely, I see no questions that are incomplete. ![image](https://user-images.githubusercontent.com/80417436/119865604-d8452680-bee9-11eb-9a91-8c5989c3ec23.png). 
Do you know what may be causing this? 
4. `<product>--submission-failed-client`: Unable to test for the same reason as the `<product>--submission-failed` event above.

**Comment by Mottie** [comment]
> Do you know what may be causing this?

There was a bug in validation that I fixed about an hour ago... please let me know if you're still seeing this issue.

**Comment by laurensimpson14** [comment]
@Mottie It is working now! I was able to QA the two `--submission-failed` events and updated the table in my last comment.

**Comment by Mottie** [comment]
> 1. Is there a way to begin this form without logging in? If not, then this event isn't applicable.

No, only logged in users can start this form

Just to be clear... all the analytics events are working as expected? So nothing needs to be change?

**Comment by laurensimpson14** [comment]
@Mottie Yes, we are good to close.
