### ISSUE TITLE
Analytics Implementation or QA Support for COVID 19 Vaccine Stay Informed

### ISSUE THREAD

**Issue by SethNiman** [department-of-veterans-affairs/va.gov-team#23177]
# Google Analytics Implementation or QA Request

## What this form is for
We currently have a campaign driving traffic here:

https://www.va.gov/health-care/covid-19-vaccine/stay-informed

we are using SEM, Paid Social and Display (through our DSP) to target several audiences to that page. We want to track if they click on the button that says "Sign up now". We are using utm codes already to differentiate by audience. 
Can we also apply tags to this button so we can optimize traffic to that conversion? 

That button then leads to several steps in a form. I'd love to somehow also track the progress through to the last page of the form to see if we can ultimately attribute the number of signups we get back to our advertising. 

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

- Who is this request for?

    - [Insert Name(s)]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
    - [Insert team and project]
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - [Provide relevant dates here]

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by jonwehausen** [comment]
Hi @SethNiman , 

Thank you for opening this implementation request. 

Per your analysis requirements of wanting the capability to be able to see the full veteran journey of where & how they got to the `/stay-informed` >> to their form completion, the tracking we have in place today will give us visibility into this without any additional data layer + tag manager work. 

You can find the existing volume of events who started the form either logged in or not [here](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22%5Ewww.va.gov~2Fhealth-care~2Fcovid-19-vaccine~2Fstay-informed.*%22,0%5D,%5B0,%22analytics.eventLabel%22,%22RE%22,%22(covid-vaccination-login-successful-start-form%7Cno-login-start-form)%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.eventLabel). From here, we can set up a segment based on these events of folks who started & completed and pair that with their `source/medium/campaign` to determine their session origin. 

In terms of supplying additional GA reports for this information -- Please be aware our team has paused reporting requests for the time being in place of our DOMO KPI dashboarding initiative. We plan on reinstating reporting requests in the near future but we are confident our KPI dashboard initiative will account for your needs here. 

For your awareness, the events that you'll want to filter on to determine starts & completions are: 
- `no-login-start-form` _with a page path of starting `^www.va.gov/health-care/covid-19-vaccine/stay-informed.*`_
- `covid-vaccination-login-successful-start-form`
- `covid-vaccination--submission-successful`

Given this information, we're going to close this ticket as their isn't any further GTM tracking necessary here -- we will do our best to assist with reporting needs given our pausing of reporting requests in the meantime. 

Thanks so much.
