### ISSUE TITLE
Unexpected errors when saving & deleting phone numbers

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23176]
## What happened?
1. The app intermittently displays the "Generic Error w/ Refresh" on the Edit Phone pages (Home/Work/Mobile/Fax). The error is usually triggered when any of the following actions are taken on these forms:
     - Deleting a phone number
     - Editing & saving a new phone number

This appears to be an issue specific to the Edit Phone forms. I haven't observed the same issues with Edit Address or Edit Email. 

2. There are also times when a new entry on the Edit Phone form "saves" and displays the loading screen, but when rerouted to the Personal Info page, the field still displays the null state. _(see attached video)_

## Specs:
- Device: iPhone 11
- Test users: I've reproduced this on a number of accounts: +228, +261, judy.morrison

## Steps to Reproduce
For Issue #1:
1. Log in w/ a user that is authorized to edit their contact information
2. If the account doesn't have saved fields for all 4 phone number types, add these in
3. Try deleting each of the phone numbers
4. Repeat these steps a number of times and see if it triggers the Generic Error w/ Refresh
5. Notice how the Generic Error persists on all of the Edit Phone forms

For Issue #2:
1. Log in w/ judy.morrison
2. Ensure that the "Home Phone" field is null
3. Go to the Edit Home Phone, and enter the following number: 212-568-8889
 _(Note: I've reproduced this with other random phone numbers)_
4. Save the form. The app should display the loading screen to save the new number.
5. Once you're rerouted to the Personal Information page, notice that the Home Phone summary still displays the null state

See attached video below.

## Desired behavior
For #1: Deleting a phone number, or saving a new phone number, should not trigger a Generic Error State, seemingly randomly. If one of the forms _does_ trigger the error, the error should not display on the other 3 phone forms.

For #2: If a phone number cannot be saved, the user should see an error message on the Edit form. If a phone number successfully saves, it should always be displayed back on the Personal Information page. 

## Acceptance Criteria
See desired behavior.

## Bug Severity
- 2 - High

## Linked story
n/a

## Screen shot(s) and additional information
Video for Issue #2 (phone number not saving):
https://images.zenhubusercontent.com/133843125/517ea961-f4c5-490e-8851-9bad24f09502/image_from_ios__1_.mp4

**Comment by bessgreen** [comment]
Update: Issue #2 may be resolved, but Issue #1 still persists.

**Comment by digitalken** [comment]
PASS 6/1/2021 - Looks to be working correctly.  Closing.
