### ISSUE TITLE
508-defect-2 [AXE-CORE]: Autocomplete attribute must be used correctly for home address/mailing address checkbox

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#23173]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Steps to Recreate

User 2 Andrea, profile information page, run axe-coconut, confirm error is thrown

## Proposed Solution (if known)

Use the correct autocomplete attribute

## WCAG or Vendor Guidance (optional)

https://dequeuniversity.com/rules/axe/4.1/autocomplete-valid?application=coconut

## Screenshots or Trace Logs

<img width="1541" alt="Screen Shot 2021-04-13 at 4 58 59 PM" src="https://user-images.githubusercontent.com/14154792/114620806-f2001680-9c79-11eb-87a4-5eeaa9209ce5.png">

**Comment by ajakabcin** [comment]
Rolling to sprint 51
