### ISSUE TITLE
[Design] - Profile: clean up design specs for profile

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#23186]
There are discrepancies between what is on staging + profile 2.0 mocks, particular wrt to padding and margins.  Audit + create new mock-ups/spec sheets to provide to FE so they can clean it up and align staging w/ mocks.

- table padding on desktop and mobile
- h1 bottom margin
- section bottom margin, especially on mobile
etc - will continue to add more

AC
- [ ] design specs delivered to FE

**Comment by andaleliz** [comment]
@MarciMcGuireGCIO this is something that's been in our backlog for a long time, and as I work on #32074, I feel like it makes sense to clean things up as I split them into new files.  It'll be much easier on Christina and anyone else moving forward if we start from a place where everything is shored up.

I'm thinking we can close this out and update the description of the other ticket to include that part of this work is to update the mock-ups to match the latest versions on staging.  

I'd also like to increase the estimate of the other ticket to 8 - this is more work than I thought, since it includes making these updates too.

**Comment by MarciMcGuireGCIO** [comment]
@andaleliz that sounds great! I'll combine them and close this one and update the estimate. Thank you!

**Comment by MarciMcGuireGCIO** [comment]
Added issue, tasks and AC to #32074; closing this one out.
