### ISSUE TITLE
[Discovery] Facility Locator Engineering

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#2318]
**User Story**
As the new Facility Locator team, we need to be familiar with the current product so we have the best information possible to plan the next version of the product. 

**Goal(s)**
Investigate and document the current Facility Locator tool's:
1. front-end architecture 
2. back-end architecture, including data sources and any transformations or mappings of those data.

**Outcome**
Research readout summary which includes findings, recommendations, additional questions

**Comment by dhall** [comment]
The engineers on the lighthouse API team have been maintaining the back end code for the facilities data in the vets-api code repository. Please reach out if we can answer any questions about how things currently work. I'd also like for us to keep in communication about any architecture changes regarding the data or the back end. Just let us know how we can help!

**Comment by jellis-gcio** [comment]
uploaded to drive and GitHub (commit: 682ee24cd751282e8f563c312052e693316bf7bf)
