### ISSUE TITLE
Design Feedback - Midpoint Review [VSA Caregivers, Sign as a Representative)

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#23193]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Change ‘Delete file’ text link to a [secondary button](https://design.va.gov/patterns/form-templates#file-upload)
![Screen Shot 2021-04-14 at 10.53.46 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/c237c263-015b-45ac-9f71-0467d2b0d953)
- Add a checkbox next to ‘I have read and accept the privacy policy. ‘ on review page
- Center button text![Screen Shot 2021-04-14 at 10.56.08 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/f2cc37a1-8c53-4377-8691-c607bf34fb4d)

**Should:**

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by sshein** [comment]
hi there - will make the changed regarding changing "Delete file" to a button. Regarding the privacy policy checkbox, we removed it because we integrated it into the larger signature boxes so the user had single place to agree to things.
