### ISSUE TITLE
[FSR] Update emails in wizard to be lower case

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#23199]
## Issue Description
Emails in the wizard terminus for VET TEC and Rogers STEM are currently all caps -- change these to lowercase.

![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/2744f2c9-2841-44cf-8ef2-db18b312ca92)
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/9775a10c-c40b-4ca9-a20c-2bca1f462a49)

---
## Tasks
- [x] Change emails in wizard to be lower case

## Acceptance Criteria
- [x] Emails lower case

**Comment by LinnJS** [comment]
Update grey boxes on error content

wizard option 1 -> 2 -> 2 & 3 ...Which of these issues do you want to report?

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17448) where this work is being done.
