### ISSUE TITLE
Analytics KPI dashboard iteration request for [Caregivers - Health care application)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23194]
# Request an \*iteration of\* a KPI Dashboard

## What this form is for
Use this template to request a KPI dashboard on Domo for your product.

## Instructions for the VFS team
- [x] Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) to guide your KPI setting. You use the Mural workshop to support linking your KPIs back to Veteran outcomes.
- [x] For additional info, read through the [How to Request a KPI Dashboard Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-dashboard-request.md)
- [x] Link your KPIs below (KPIs should be in your Product Outline)
- [x] Add your team label to follow progress

Is this a new KPI dashboard request? Or is this an iteration? Please check the corrrect response.
- [ ] New dashboard
- [x] Iteration of current dashboard

### KPIs
- *\*New*\* - How many Veterans return to the health care application to complete it after saving it in progress? Specifically, we'd like to be able to see data from 2020, and YTD 2021

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Groom Analytics
- [ ] Groom analytics for technical feasibility
    - [ ] Document data sources for each metric
    - [ ] Document unavailable vs. available metrics
- [ ] If any, add implementation issue for additional necessary implementation

2. Draft PST Dashboard
- [ ] Draft dashboard on Domo
- [ ] Structure data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Add appropriate team members to dashboard

Please see [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

## Definition of Done
- [ ] KPIs have been groomed and connected to Domo
- [ ] Dashboard has been shared back with the VFS team
- [ ] KPI Dashboard full QA checklist completed

**Comment by joanneesteban** [comment]
Hi Alayna! We'll see you in the Feedback Session tomorrow, but just want to share that we're pausing on any new dashboards or iterations to dashboards until the end of June.

**Comment by ala-yna** [comment]
Thanks @joanneesteban! I understand you're pausing on dashboard changes, but is there any way for us to at least get some answers to our questions, especially re: saved-in-progress completion rates? This would be very useful for our stakeholders and the work we're about to embark on.

**Comment by joanneesteban** [comment]
Hi @ala-yna , we're unfortunately pausing on any additional reporting _discovery_ work, which includes this question. It's a bit more complicated, and our team will have to do some digging on this and potentially create another report to surface that data. You can find more info on our pause [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md). 

However, if you attend the Collaboration Cycle office hours, Wednesdays 11:30-12pm EST, we'd be happy to work with you on this discovery there!

**Comment by mlighdc** [comment]
@ala-yna can you please stop in the Collaboration Cycle office hours on Wednesday, tomorrow, and talk to Joanne about this. This information would be really helpful in determining our approach for increasing online submissions.

**Comment by ala-yna** [comment]
Hi @mlighdc! Unfortunately, dashboard and iteration requests are paused until June. However, @bsmartin-ep was able to pull together a [quick funnel ](https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p176188361/edit/0ajGVIZpSrSz6nqVUCvR4Q)to help us see what percentage of people who resume a saved-in-progress application then go on to submit an application.

**Comment by mlighdc** [comment]
@ala-yna can you tell me what I should be looking at for the quick funnel and what are the key takeaways? Can you give me a summary?

@bsmartin-ep what does the prioritization process look like when the analytics team picks up the requests in June? I am curious where we will fall in your backlog. @ala-yna you may have already asked Brian. If so, let me know how it will be working.

**Comment by mlighdc** [comment]
@joanneesteban June is around the corner... can you please provide an update on the process for iteration? :-)

**Comment by joanneesteban** [comment]
@mlighdc Thanks for the ping! Our tentative plan is to release the standardized KPI dashboards that you gave feedback for towards the end of June. We're including the 1010EZ form in that dashboard.

**Comment by joanneesteban** [comment]
@mlighdc we're planning on adjusting our SLAs and the request templates, and will update you as soon as we have the new guidelines. Our aim is to have final guidelines by or before June 30.  

If you have any analytics questions about how to interpret your data, we'll be at the Collaboration Cycle office hours on Wednesdays 11:30-12pm EST. And if you need any [new or updated Google Tag Manager tags](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D), those services are still a go!

**Comment by SKasimow** [comment]
@chloedotbrown Hi - here's the ticket that was a request for a dashboard iteration but don't think it was ever submitted/done.

However, this seems like a good metric for us to track: 

- How many Veterans return to the health care application to complete it after saving it in progress? Specifically, we'd like to be able to see data from 2020, and YTD 2021

Can I submit this as a request or piggy-back to the funnel update ticket I just sent it?

**Comment by chloedotbrown** [comment]
Hey @SKasimow! What event would be associated with this action for your team? Brian pulled a [quick report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20211101&_u.date01=20220213&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:caregivers-10-10cg-sip-form-loaded/) on `caregivers-10-10cg-sip-form-loaded`, but it's only showing 1 occurrence. Want to make sure we're looking at the right thing and that's it's functioning properly!

Once we've got the event confirmed, please submit this as a separate [Feature Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+enhancement&template=analytics-feature-request-bug-report.md&title=Analytics+Feature+Request%2FBug+Report). This will be a different process/timeline than the funnel change, so it will be easiest for us to track them in their own tickets. Thanks!

**Comment by SKasimow** [comment]
Hi @chloedotbrown although this says "caregiver" in the title it is actually referring to the HCA form not the Caregiver form.
I looked and see a lot of traffic hca-sip-form-saved so think we're actually all set. Sorry I didn't catch the mix-up sooner.
