### ISSUE TITLE
Design Feedback - Midpoint Review for BAH/Sitewide Content VRRAP static page

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#23201]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Change green apply button to [green action link](https://design.va.gov/components/action-links)

**Should:**

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Is there any update on the drupal side of things about when we'll be able to start using the new action link?

**Comment by bethpottsVADEPO** [comment]
@allison0034 Green action links are yet supported in drupal, so we'll need to launch with the existing green button.  Can't fulfill that "must" feedback at this time.
