### ISSUE TITLE
User Survey Request for Find a VA Form

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23207]
# Request the Feedback Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md)

## Description
Find a VA Form - tool for Veterans to search for forms needed to apply or qualify for benefits.

### Launch Date
Search page launched in July 2020; detail pages launched in September/October 2020

### Staging URLs
Landing page - https://staging.va.gov/find-forms/
Sample detail page - https://staging.va.gov/find-forms/about-form-10-10ez/

### Production URLs
*Please provide Production URLs*
Landing page - https://www.va.gov/find-forms/
Sample detail page - https://www.va.gov/find-forms/about-form-10-10ez/
---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by jwoodman5** [comment]
Hi @MarciMcGuireGCIO Great to see this come through. Can you please confirm you are wanting the _standard_ Medallia _feedback_ survey on https://staging.va.gov/find-forms/ and all (detail) pages in that directory? Double checking because there has been some confusion with other folks. Thank you!

**Comment by johnhashva** [comment]
@jwoodman5 we are okay with the standard feedback implementation as we know customization will be hard (based on what I heard in the discussion about Resources & Support).   That said, will the standard implementation allow us to control how many pages it appears on?  In other words, we'd like to test it on a few pages at first -- Landing Page and then 5 of our most popular Forms -- to ensure its not disruptive to the user experience.  If we can "throttle" at the product team level, that will be great.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva we are 💯 on the same wavelength. I was going to suggest a similar approach.

**Comment by MarciMcGuireGCIO** [comment]
I also don't know if it will ever be necessary to survey every detail page. We should be able to leave enough about the overall performance of a few representative pages to apply to the others.

**Comment by jwoodman5** [comment]
Hi @johnhashva (cc: @MarciMcGuireGCIO) Absolutely, we can control which pages the feedback survey appears on. We will just need to know specific URLs with that approach versus just a directory (unless all pages in the directory will get the survey). Hope that helps. As soon as we are clear on which pages you want the survey on, I will get the ball rolling with Medallia. Thanks for the quick replies!

**Comment by jwoodman5** [comment]
@MarciMcGuireGCIO We can get this one going as soon as we know which pages you want it on. We can either put it on this page and everything in the directory (all detail pages) https://www.va.gov/find-forms/ or you can specify URLs. Just let me know when you can. Thanks.

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO let's discuss next steps before we finalize this initial implementation for FaF and Yellow Ribbon.   This is exciting!

**Comment by MarciMcGuireGCIO** [comment]
Sounds good. Yellow Ribbon is in place as of yesterday. What are you thinking for FaF detail pages? Top 5? Top 10?

**Comment by MarciMcGuireGCIO** [comment]
Hi @jwoodman5!  Sorry for the delay on this.  Here are the five detail pages we would like the Medallia survey to appear on, in addition to the Find a VA Form landing page (https://www.va.gov/find-forms/).

www.va.gov/find-forms/about-form-21-4138
www.va.gov/find-forms/about-form-10-5345
www.va.gov/find-forms/about-form-20-0995
www.va.gov/find-forms/about-form-21-526ez
www.va.gov/find-forms/about-form-10-7959c

Thank you again, and let me know if you have questions or need anything else!

**Comment by jwoodman5** [comment]
Hi @MarciMcGuireGCIO  - I learned something after asking you for URL clarification. If we add the feedback survey to https://www.va.gov/find-forms/, all detail pages will get it as well _unless_ we specifically exclude them. I was (mistakenly) under the impression we could add singular URLs even if they had child/detail pages. 

So, I see a couple of options but am open to suggestions:

1. We can add the feedback survey to _just_ the detail pages you specified and _not_ https://www.va.gov/find-forms/.
2. We can add the feedback survey to https://www.va.gov/find-forms/ and exclude all detail pages except the ones you listed above. For this, I would need a list of all excluded URLs.
3. We can addd the feedback survey to https://www.va.gov/find-forms/ with no exclusions and all detail pages will show the survey as well. 

Please let me know how you would like to proceed and/or if you have any questions. I am happy to hop on a call if that helps too. Thanks for working with us on this!

**Comment by MarciMcGuireGCIO** [comment]
Hi Jason,

Well that is an interesting development!

Let's go with including the landing page and all the detail pages.

Thank you so much!

**Comment by jwoodman5** [comment]
Thanks, @MarciMcGuireGCIO Sounds good. And sorry for the mixup. Thanks for you thumbs up too, @johnhashva! I will confirm when we're live!

**Comment by MarciMcGuireGCIO** [comment]
No worries at all, @jwoodman5.  I know you all are still getting your arms around this product.  Appreciate you helping us out with this!

**Comment by jwoodman5** [comment]
Hi @MarciMcGuireGCIO and @johnhashva We are live with the Medallia feedback survey on https://www.va.gov/find-forms/ and all detail pages! Thanks again for working with us through this process.

**Comment by MarciMcGuireGCIO** [comment]
Great! Thank you very much, @jwoodman5 !

Just to confirm, once we are ready to see some data, we can reach out to your team for that until it's available in Domo?

**Comment by jwoodman5** [comment]
Yes, please!

**Comment by MarciMcGuireGCIO** [comment]
Thank you! :pray:
