### ISSUE TITLE
JSDOM cleanup 

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#23217]
## Details 

Some tests require setup before the test runs, test runs, and then when test ends it is normal procedure to clear out the setup before the next test runs. Not all unit tests are clearing out their setup. 

This is an issue that can BOTH be addressed at a platform level, AND should be added to best practices for VFS teams writing unit tests. 

## Acceptance Criteria
- [ ] Added mechanisms to clean these instances up at the platform level 
   - [ ] Example test runs that were failing before are now passing 
- [ ] Add to best practices documentation (or note in the list to be added to best practices docs)

**Comment by k80bowman** [comment]
Upon further examination of our code, I determined that the platform changes are already implemented in the `src/platform/testing/unit/mocha-setup.js` file. As far as unit tests not clearing out their setup, this may still be an issue, but not as relates to JSDOM. Any other residual tests effects will be discussed with teams as part of #23006.
