### ISSUE TITLE
Update covid clinic report

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23232]
## Description
Some of the sites made changes to their clinics following the latest guidance about J&J.

---
## Tasks
- [ ] Clinic report is updated in GitHub https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/clinics.csv

**Comment by laurenernest** [comment]
@jbalboni to confirm, all these sites that are display to patient and direct scheduling `true` could display in VAOS if they have slots, correct?

**Comment by jbalboni** [comment]
@laurenernest Correct. The clinic list report works by pulling down any active clinics that have the CDQC CHAR4 code. So anything on that list that has the display to patient and direct scheduling flags on will then meet all the covid clinic criteria.
