### ISSUE TITLE
[My VA Dashboard 2.0 Redesign] VSA-QA Test Plan

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23242]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

## Product/Feature summary

- Product/Feature Outline: [My VA Dashboard 2.0 Redesign](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/README.md)
- Product/Feature Epic: [My VA Dashboard 2.0](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6326)
- Product/Feature Design prototypes: My VA InVision documentation [Desktop](https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/screens/443777220) and [Mobile](https://vsateams.invisionapp.com/share/XNZWCYAYD45#/screens/443913926_My_VA_Mobile_Icons)

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: 
Content/IA: 
Front-end: 
Back-end: 
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

Link to **Use Cases doc**: [My VA Test Cases and Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [x] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by tlei123** [comment]
@ajakabcin  @erikphansen @sanlouise @lihanli @tressaellen @andaleliz , I've got some follow-up questions re. the Use Cases for **Apply for VA benefits** section:

- (1)  [for **Erik/Sandra**] **[What benefits does VA offer?](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md#apply-for-va-benefits-links)** (Benefits dropdown): Is the links-list dynamic [i.e., are certain links here shown/hidden depending on user-scenario]?
- (2)  **[Benefits you may be interested in](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md#benefits-you-may-be-interested-in)**:
  - (2.a)  **Not enrolled in & never applied for healthcare**:
    - (2.a.i)  [**Erik/Sandra**] How do I "recreate using existing user" [what are the local-override details]?
    - (2.a.ii)  [for **Tressa/Liz**] [Design-prototype](https://vsateams.invisionapp.com/console/share/SH10HT8JCKYM/600538560) doesn't appear to fit this scenario.  Can you update the link for the Use-case or provide it here please?
  - (2.b)  **Started healthcare-app**:
    - (2.b.i)  [**Erik/Sandra**] How do I "recreate using existing user" [what are the local-override details]?
    - (2.b.ii)  [**Tressa/Liz**] [Design prototype](https://vsateams.invisionapp.com/console/share/SH10HT8JCKYM/600538559) doesn't appear to this scenario.  Can you update the link for the Use-case or provide it here please?
  - (2.c)  [**Tressa/Liz**] **Has / has not filed claim**: Intended outcomes are the same for both.  For User who's already filed a claim [see [design prototype](https://vsateams.invisionapp.com/console/share/SH10HT8JCKYM/600538535)], shouldn't **Disability compensation** card be hidden?
  - (2.d)  **Has started edu-benefits app**:
    - (2.d.i)  [**Erik/Sandra**] How do I "add application to existing user" [what are the local-override details]?
    - (2.d.ii)  [**Tressa/Liz**] Just to confirm, there should be an app-card displayed in Applications-in-progress subsection above, right?
  - (2.e)  [for **Anastasia**] **Doesn't receive direct-deposit for edu-benefits**: Where's the password documented for test-user 378?

Please add Comment(s) below with your responses and tag me (@tlei123).  Thanks much!

**Comment by erikphansen** [comment]
@tlei123:

1) the bulleted list of benefits never changes
2a) for this case it's best to find a staging user who is not a VA patient and not in ESR
2b) for this case it's best to find a staging user who is not a VA patient or in ESR and start a health care application
2d) we actually do not change the My VA Dashboard if a user has started or submitted an application for edu benefits

For 2d we do hide info about education benefits if we detect that a user is getting direct deposit for education benefits. I believe you did QA for DD4EDU a couple of months ago so should already have a user who is getting DD4EDU.

**Comment by Samara-Strauss** [comment]
> (1) [for Erik/Sandra/Lihan] What benefits does VA offer? (Benefits dropdown): Is the links-list dynamic [i.e., are certain links here shown/hidden depending on user-scenario]?

No, these links are not dynamic.

> (2.a.i) [Erik/Sandra/Lihan] How do I "recreate using existing user" [what are the local-override details]?
> (2.b.i) [Erik/Sandra/Lihan] How do I "recreate using existing user" [what are the local-override details]?

Sorry I didn't catch this before — as per @erikphansen's comment above, yes, we should use an existing staging user to test these. You can use user 272 to test this use case, but please note that if you need to test this multiple times (like on different devices or in different browsers), you'll need to delete the health care app each time. The only way to delete an app is to start a new one and *not* save it in progress. I've updated the documentation to note all of this.

> (2.c) [Tressa/Liz] Has / has not filed claim: Intended outcomes are the same for both. For User who's already filed a claim [see design prototype], shouldn't Disability compensation card be hidden?

No, the card shouldn't be hidden. We opted to do things this way because people can (and do) fill out multiple claims.

> (2.d.i) [Erik/Sandra/Lihan] How do I "add application to existing user" [what are the local-override details]?

You don't need to do local override. Just pick a staging user and start an edu application for them. User 226 does not have an edu application currently, so you can use them. I've updated the documentation accordingly.

> (2.e) [for Anastasia] Doesn't receive direct-deposit for edu-benefits: Where's the password documented for test-user 378?

I have linked this from the test user doc. Sorry for the original oversight.

Beyond this, I'll let @tressaellen handle the design documentation specific questions, as she's the right person to handle that. And FYI — Liz hasn't worked on this project, so Tressa is your main point person for all design questions.

**Comment by tlei123** [comment]
> 1. the bulleted list of benefits never changes
>    2a) for this case it's best to find a staging user who is not a VA patient and not in ESR
>    2b) for this case it's best to find a staging user who is not a VA patient or in ESR and start a health care application
>    2d) we actually do not change the My VA Dashboard if a user has started or submitted an application for edu benefits

@erikphansen , please do provide the API-details for the above -- what the f/e checks to support those cases.

I will indeed keep local-overrides as last resort, BUT considering I have 3 other teams' products/features concurrent with this one to prep for QA-testing, the probability of not finding test-users is far from negligable.  Hope you understand.

Thanks much!  :)

**Comment by erikphansen** [comment]
User 272 can be used to test 2a and 2b

I believe 378 is signed up for DD4EDU benefits so they can be used to test the scenario where we hide the Education Benefits info down in the Apply For Benefits section

If you need to you can make a user a VA Patient (or not a patient) by setting `vaProfile.vaPatient` to `true` or `false` in the `GET user/` response.

You can override the `GET enrollment_status` response to be the following to make it seem like they are not in ESR:
```
{
  "applicationDate": null,
  "enrollmentDate": null,
  "preferredFacility": null,
  "effectiveDate": null,
  "parsedStatus": "none_of_the_above"
}
```

And you can make someone appear to get DD4EDU benefits by mocking the response from `GET ch33_bank_accounts` to be:

```
{
  "data": {
    "id": "",
    "type": "hashes",
    "attributes": {
      "accountType": "Savings",
      "accountNumber": "*****0543",
      "financialInstitutionRoutingNumber": "*****0017",
      "financialInstitutionName": "BANK OF AMERICA, N.A."
    }
  }
}
```

**Comment by tlei123** [comment]
@erikphansen , thx much!  Sorry, in my haste I didn't read @Samara-Strauss 's answers before bugging you again -- she's provided test-user 272 for those cases.  It's still good to know the details you've just provide above.  Thanks much!  :)

**Comment by tressaellen** [comment]
Hi @tlei123 , I've updated the prototype screens that were wrong. 

> (2.a.ii) [for Tressa/Liz] Design-prototype doesn't appear to fit this scenario. Can you update the link for the Use-case or provide it here please?

Updated

>(2.b.ii) [Tressa/Liz] Design prototype doesn't appear to fit this scenario. Can you update the link for the Use-case or provide it here please?

Updated

> (2.d.ii) [Tressa/Liz] Just to confirm, there should be an app-card displayed in Applications-in-progress subsection above, right?

Yep - there should be an app-card displayed in the applications in progress subsection.

It looks like Samara answered the rest of the questions, but let me know if you need anything else or have any other questions! Thank you!

**Comment by ajakabcin** [comment]
@tlei123 Tressa filed a new claim for test user 15 for you so you'll be ready to go next week for claims and appeals test cases

**Comment by tlei123** [comment]
@ajakabcin , all test-runs now completed, and reports generated.

3 defects logged: #24645, #24646, #24647

Once you have a Staging Review ticket opened, please use these QA-artifact links to update that tic's main description:
- [Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/1799)
- [Test cases](https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1069)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/224)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/225)

Feel free to ping me on Slack if you have any questions/issues.

cc @Samara-Strauss
