### ISSUE TITLE
Adding Teesh Shahi to DSVA Slack

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#23241]
The following individual Teesh.Shahi@adhocteam.us needs to be added as a full member.    He is part of the VA Startup team.  Thank you!

CC: @cgreim

**Comment by LEHigley** [comment]
hi @narin i just went to add them and got a notification they're already in Slack. can this be closed?

**Comment by narin** [comment]
Yes we can close it out. Thank you @LEHigley!
