### ISSUE TITLE
[SPIKE] Direct schedule appointment ID for confirmation

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23253]
## Summary
To help inform the new appointment confirmation design, we need to research how to get the appointment ID from MAS.

Problem: we would like to send users to the appointment detail page after direct scheduling an appointment. To do this, we need to know the MAS appointment id for the appointment we just created. However, MAS appointment ids are synthetic, and we're not going through MAS to create appointments (that's not supported in the current version). It's not clear where the synthetic id comes from.

So, we need to answer the following questions:

1. What data is sent back when creating an appointment? Currently the front end receives an empty response. If there is data sent back that isn't forwarded on to the FE, does it have the synthetic id?
- The upstream service VAR/Resources that vets-api calls to create an appointment does not return the synthetic id.
2. What's the MAS or VIA logic for creating the synthetic id for an appointment? Could we mimic this based on the appointment information we have?
- During the last SOS call 4/20 it was determined that the algorithm for creating the synthetic id was fairly complicated and the thought was that it wouldn't make sense to mimic it but instead to wait until the new VAOS service is live.  The new VAOS service will rely on MAS 2.0 logic that will return a new id that we can use going forward.
3. Is there a delay between appointments being created and MAS being able to return them? If we can't generate the MAS id, then we might want to fall back to querying MAS for the specific appointment time to find the one we just created, before sending the user over to the details page.
- See the answer to number 2.0.

Frontend implementation will be covered in #23246

## Tasks

- [x] Document answers to above questions
- [x] Create VAOS BE tickets and note dependencies, if necessary

**Comment by laurenernest** [comment]
@jbalboni Can you help fill in any technical instructions or tasks for this ticket?

**Comment by grossb1** [comment]
During today's SOS call it was mentioned that it may be best to wait until the release of MAS 2.0 due to the way id's will be created in that release.
