### ISSUE TITLE
[Consider] Health service modalities

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23250]
## Issue Description
The existence of virtual/remote services is a reality in remote areas, COVID times and mobile facilities. 
How should modality/delivery method information be represented in health service details on VAMC and Vet Center pages?

Hypotheses
- It's important for Veterans to understand the options for how services can be delivered
- It's important for Veterans to expect the delivery modality for a given service when visiting a facility (ie: visiting a mobile unit and connecting with a provider via virtual meeting)

Idea: 
Is telehealth offered?
- yes
- no
- unknown
- only by telehealth

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
Service Modalities are being explored as part of VBA MVP https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13128
