### ISSUE TITLE
VAMC phone tree options as extensions in Drupal 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23260]
## Issue Description
Editors are adding phone tree information ("option 8") into the extension field in Drupal. 

## Considerations
- Depending on FE handling, accessibility defects may be created.
- We can't be assured that the phone tree will remain the same - the information may become misleading/confusing for Veterans. 

This epic will house the various CMS and Facilities team tasks to deliver the best experience for Veterans and editors. 

## Example: 
VAMC Facility Health Service COVID-19 vaccines - Sacramento VA Medical Center
https://prod.cms.va.gov/node/15415/edit

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@kevwalsh for visibility

**Comment by laflannery** [comment]
@mmiddaugh You originally opened this epic but I would like to close it in favor of [the more recent phone epic here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17854). Any objections?

CC: @Agile6MSkinner

**Comment by Agile6MSkinner** [comment]
It's three years old and there are no issues assigned to it. I think that's a safe bet. I'll go ahead and do it. I've added the epic that you linked to the roadmap in Zenhub.

cc: @mmiddaugh
