### ISSUE TITLE
Update formatting of file list content

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23268]
## Acceptance Criteria
1. On the **Attachments** page, update the formatting of the file list (doc, docx, gif, etc.) so that it does not display as a bulleted list. Rather, it will display in the first paragraph at the end of the sentence (see image below)

**Note for QA**: This will undo , AC #2B of #20139

## Designs
![Screen Shot 2021-04-14 at 3.51.01 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/39100bff-9888-4584-9f4a-c4aeeb8de1f0)
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/449230092/comments

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/21/2021 - Looks good on iOS and Android.  Closing.
