### ISSUE TITLE
Design expandable alert for Vet Center operating status

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23261]
## Issue Description
The VAMC product has an [Operating Status page](https://www.va.gov/pittsburgh-health-care/operating-status/) which provides details on facility access. The Facility Locator provides the details on the [Facility Detail page](https://www.va.gov/find-locations/facility/vc_0434V). 

The Vet Center product does not have an equivalent experience to connect to the operating status displayed on the Locations page. We identified a component that is being used on [Suicide Prevention pages](https://www.va.gov/health-care/health-needs-conditions/mental-health/suicide-prevention/)

![image](https://user-images.githubusercontent.com/55411834/114786347-30113f00-9d3b-11eb-8593-238897e60e73.png)

---
## Tasks
- [x] Design an expandable alert that can be used to display the operating status details for a Vet Center location. 

## Acceptance Criteria
- [ ] Design spec ready for FE engineers to implement

**Comment by lildziner** [comment]
## [Design problem description](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138515145?mode=cvhid)

#### Design option A
[(see prototype)](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138511926?mode=cvhid)

![op-status-expandable-A.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/231bae74-34d1-4e7e-9c1a-0a2ad6cd6e03)

#### Design option B
[(see prototype)](https://preview.uxpin.com/0a5eaacdf411fde0cb3abf4932010c29fbccb7de#/pages/138520599?mode=cvhid)

![op-status-expandable-B.png](https://images.zenhubusercontent.com/5c4895778d88074ab2c6ad18/9a3f2dbe-ec6c-4966-8062-18d16473aaef)
