### ISSUE TITLE
Compose message form - Android, unable to trigger error by leaving To: and Subject: field pickers 

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#23273]
## What happened?
I can trigger all of the field errors by trying to send the message but I'm supposed to be able to trigger the error by leaving a field picker empty and going elsewhere in the form.  That isn't happening with To: and Subject: on the Android.

## Specs:
- Device: Android

## Steps to Reproduce
- Cause the To: field picker to come up.  Leave it without choosing or by choosing the blank choice.  Should pop up error.
- Cause the Subject: field picker to come up.  Leave it without choosing or by choosing the blank choice.  Should pop up error.

## Desired behavior
Pops up error when leaving the field without making a valid choice.

## Acceptance Criteria
Pops up error when leaving the field without making a valid choice.

"The field-level errors should appear when any of the following occur:
- A user taps into a required input field and leaves the field without completing it"

## Bug Severity
- 3 - Medium

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22667

**Comment by komaly15** [comment]
Note: this should be resolved once the custom picker usages is merged in ([22584](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22584))

**Comment by digitalken** [comment]
PASS 4/20/21 - Looks good now.  Closing.
