### ISSUE TITLE
Collaboration Cycle Kickoff - Discharge Upgrade Wizard - PDF download to AFRBA portal

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23279]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [x] VFS: Attach any available artifacts.
- [x] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-update/readme.md)
- Link to wireframes, mockups, or prototypes
- Any other artifacts you have so far
     - The current page can be viewed on this PDF:
[DoD Form 149 Page.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6401590/DoD.Form.149.Page.pdf)

    - To see it in Production, go to [this page](https://www.va.gov/discharge-upgrade-instructions/guidance)  then answer the questions according to this [PDF](https://github.com/department-of-veterans-affairs/va.gov-team/files/6401425/DUW.pdf).

   - We need content that provides context for the portal link rather than the PDF-centric copy that is currently there.
   - We also need to change the **Download Form 149 CTA** link to an Action Link that tells the user that s/he can apply online for a Discharge Upgrade

    

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

**Will your work result in visible changes to the user experience?**
- [x] Yes
- [ ] No

**Is your work a new product/feature or an iteration to an existing product/feature?**
- [ ] New
- [x] Iteration

**Will your work impact only static content pages?**
- [X] Yes
- [ ] No

**Are you making changes to the visual design?**
- [X] Yes
- [ ] No

**Are you making changes to content?**
- [X] Yes
- [ ] No

**Are you making a change to the user flow?**
- [ ] Yes
- [X] No

**Are you making a change to urls, navigation, or entry points?**
- [ ] Yes
- [X] No, but we are changing a PDF download link to portal hosted on a .mil site.

**Are you doing research with VA.gov users?**
- [ ] Yes
- [X] No

**Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?**
- [ ] Yes - GA, but no KPI dashboard
- [ ] No

**If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?**
- [ ] Yes
- [ ] No
- [x] Not sure.  The event tracking probably needs to be standardized since this tool is 3 years old.

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @MarciMcGuireGCIO.  Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, we are recommending  the following Collaboration Cycle touchpoints:

- Design Intent
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch:

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

When you find out if your product has existing analytics artifacts, please follow up with the Analytics team. At this time, I'm not recommending an Analytics Request.

For IA, I will be following up with Mikki to see if an IA Request is recommended.

The following practice areas will be included throughout the Collaboration Cycle process:

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

Your project has been added to the Platform Collaboration Point Tracker (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @shiragoodman!

**Comment by MarciMcGuireGCIO** [comment]
Hi @shiragoodman - have you had an opportunity to talk with Mikki about whether an IA review will be needed?  Thanks!

**Comment by shiragoodman** [comment]
@MarciMcGuireGCIO I'll get back to you by EOD!

**Comment by mnorthuis** [comment]
@MarciMcGuireGCIO Can you clarify the work for this project?  Are you building a new online form?

**Comment by MarciMcGuireGCIO** [comment]
Hi @mnorthuis we are iterating on an existing product.  We are changing a link to a PDF to a link to an online tool, along with modifying the accompanying instruction.I hope that helps!

**Comment by mnorthuis** [comment]
Where does the online tool live?

**Comment by mnorthuis** [comment]
@shiragoodman,   Marci and I briefly talked, the online tool is on another site - I wanted to make sure we weren't building that tool.  No IA work is needed for this project.  Thank you!!

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @mnorthuis and @shiragoodman !

**Comment by MarciMcGuireGCIO** [comment]
Updated title to reflect the fact that the link is to a portal and not to an e-application.
