### ISSUE TITLE
Slack Workflow Usability Testing

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#23270]
Before launching the customer support Slack workflow, we wanted to test 2 sample Slack forms to see which aligns better with the type of help VFS team members might need and makes Platform support more efficient. 

We are conducting directed interviews and usability testing with high-fidelity prototypes of each form option with Platform team members who provide support and VFS team members who request support. 

Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/research/customer-support/research-plan.md

**Comment by Khyatinp18** [comment]
2/21/2022:
This issue is no longer needed since SRE team took over this process.
