### ISSUE TITLE
Collaboration Cycle Kickoff - Find a VA Form, Add Relevance, Popularity, Related Forms

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23277]
## Steps to complete Collaboration Cycle Kickoff
- [X] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [X] VFS: Answer the questions below.
- [X] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [x] VFS: Attach any available artifacts.
- [x] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/README.md)

- Link to wireframes, mockups, or prototypes
    - "[Best Match" option added to sort is on Staging](https://staging.va.gov/find-forms/?q=) ~~("Most Popular" will follow the same pattern - this scope was just added so we don't have a mockup for that yet.)~~ Popularity will not be a sort option; it is used behind the scenes to weight search results.
    - Mockups for new search UI pattern: 
        - Desktop: https://vsateams.invisionapp.com/share/SD10IE31CENR 
        - Mobile: https://vsateams.invisionapp.com/share/8Y10IE2JN2J4
   ~~ - [Mockups for PDF download instructions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24981)~~ DESCOPED 6/14/2021

- Any other artifacts you have so far  **Below is an outline of the changes**

     - We are working with the Lighthouse team to add logic to the Forms API that will score search results based on the field in which a match is found, and the quality of the match (full match, partial match), and then order the results based on the score.    [Draft of search scoring methodology](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19170#issuecomment-818237470).   We will add "Best Match" as an option in the sorting select.
     - The Lighthouse team is also adding logic to use "Most Popular" data to weight the order of the search results.
     - We are also adding links for "related to" forms on form detail pages so that users can click directly do them without having to do another search.   [Example of where the link will be added](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24889).
     - We are applying the new pattern for search tools that was designed recently
   ~~  - We are adding some sort of callout next to PDF links that advise the user to download the form to fill it out. That callout may link to a page that has more detailed PDF help content.~~ DESCOPED 6/14/2021

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

**Will your work result in visible changes to the user experience?**
- [x] Yes
- [ ] No

**Is your work a new product/feature or an iteration to an existing product/feature?**
- [ ] New
- [x] Iteration

**Will your work impact only static content pages?**
- [ ] Yes
- [x] No

**Are you making changes to the visual design?**
- [X] Yes
- [ ] No

**Are you making changes to content?**
- [x] Yes
      1. Add two new options (Best Match, Most Popular) to the existing sort tool (see below)
     ~~ 2. Add a link/and or verbiage for PDF help~~
- [ ] No

**Are you making a change to the user flow?**
- [ ] Yes
- [x] No

**Are you making a change to urls, navigation, or entry points?**
- [ ] Yes
- [x] No

**Are you doing research with VA.gov users?**
- [ ] Yes
- [x] No

**Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?**
- [x] Yes
- [ ] No

**If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?**
- [ ] Yes
- [x] No

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hey @MarciMcGuireGCIO. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, we are recommending the following Collaboration Cycle touchpoints:

- Privacy and Security Review

Your project has been added to the Platform Collaboration Point Tracker (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman - we recently realized that this change will require that we add an additional sorting option (Closest Match or Relevance) to the existing drop-down.  Are there additional touchpoints we will need given that change?  Thanks! 

![image](https://user-images.githubusercontent.com/73354907/116408637-0bb86680-a801-11eb-8bde-74acb39cef14.png)

**Comment by shiragoodman** [comment]
thanks for following up @MarciMcGuireGCIO! Yes, we will most likely be recommending additional touchpoints because your work will now result in visible changes to the user experience. Would you please do me a favor and re-do the questions above? I have already cleared the checks. Please tag me here when complete and I will follow up!

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @shiragoodman.  Yep; will update them now.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman I've updated everything.  Thanks!

**Comment by shiragoodman** [comment]
Hi @MarciMcGuireGCIO. Thanks for redoing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- Midpoint Review (asynch would be fine since it isn't a big change)
- Contact Center Review (most likely will require minor modifications to your Product Guide)
- Staging Review
- Privacy and Security Review

Post Launch: 

- Full Accessibility and 508 Office Audit

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. (thank you for already doing this!)
 
Your project has been updated in the Platform Collaboration Point Tracker. Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman, our PO wanted to add some additional scope to this, so we would like to combine this with three other collab cycles have in the works if at all possible. 

#23279
#24535
#24878 

Please let me know if we can combine, and what info you need from me.  Thanks!

**Comment by shiragoodman** [comment]
thanks @MarciMcGuireGCIO ! This is awesome. We would definitely prefer to review 1 large set of changes thru Collab Cycle, than 4 smaller changes. Let me review these 4 tickets, see what was recommended for all, and I'll reply back soon. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @shiragoodman!  Actually, that first collab cycle ID shouldn't be on there.  I copied the wrong number.  I'll fix that now.

**Comment by shiragoodman** [comment]
For tracking purposes, this effort is now a combination of the following:
1. Search Matching Improvements, Iteration 2
2. Related To Link on Detail Pages
3. Apply new search UI pattern to existing tool
4. PDF Download Info

Recommended Collaboration Cycle touchpoints include:

- Design Intent
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy & Security Review
- Full Accessibility & 508 Office Audit
- Post-Launch Check-In

The Platform Collaboration Point Tracker will be updated. @MarciMcGuireGCIO feel free to close the ticket you have open for the other initiatives, if any.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @shiragoodman !  I've updated this to included the full scope of what it now includes.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman since there are still some unanswered questions related to the PDF download link, John and I agreed to de-scope this morning so we don't delay getting the other features into Production on July 6.

**Comment by shiragoodman** [comment]
hey @MarciMcGuireGCIO thanks for the info!
