### ISSUE TITLE
CT: Add README to vets-website/src/applications/gi/

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23284]
As a developer, I need to add a README for the comparison tool repo so that when new developers join the project they have the information that they need to begin development.

## Assumptions:
1. The documentation listed is the minimum, any additional documentation that would be beneficial to be added can and should be added.

## Acceptance Criteria:
1. A README.md exists in vets-website/src/applications/gi/
2. Documentation includes
    a. Data sources in the repository
    b. CSV data sources in the repository

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17853

**Comment by zurbergram** [comment]
Closing as https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi/README.md now exists
