### ISSUE TITLE
IA Request [Authenticated Experience, Notification Preferences (Communication Permissions)]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23286]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kick-off ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- [Communication Permissions (Notification Preferences) product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
- Link to [mockups](https://preview.uxpin.com/bb87d0fa61a32938a47e7bcdc836db235ab77576#/pages/137640964/simulate/sitemap?mode=i)
- Link to [content documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/design-specs.md)

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?
- On Profile within the authenticated experience. Unauthenticated users won't be able to access this.

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?
- We expect to validate further in research but our initial assumptions are the following: notifications, alerts, settings

**URL(s)** - What are your suggested URLs and why?
- Follow standard/existing convention: profile/notification-settings

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool? 
-  We expect to validate this in research but our initial thinking is that users will be driven here from a notification they receive either by email or text message.  E.g. at the end of whatever the notification is "You can always manage your notification settings in your VA.gov profile"

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
- TBD, we'll need to validated this further in research but an initial thought we had was locations where a user submits a form or application that would trigger a notification so the user knows they have the ability to manage them. 

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?
- no

## Definition of Done
- [x] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by ajakabcin** [comment]
@mnorthuis  and @shiragoodman we need to hold on this for a bit while we get a few other details ironed out. I'll ping again when we're in a better position to resume. Sorry for any confusion - thanks

**Comment by ajakabcin** [comment]
Hi @mnorthuis and @shiragoodman we're good to go on this request now. Thanks for your patience!
cc @andaleliz and @Samara-Strauss

**Comment by mnorthuis** [comment]
@ajakabcin @andaleliz Are you working with sitewide content on the content and labeling within profile?  If so, is what I see in the prototype and the linked content document final content (i.e. H1s, link labels, etc)?

**Comment by mnorthuis** [comment]
IA recommendations are documented here:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/auth-profile-notifications.md

Please let me know if you have any questions.  You are welcome to close this ticket at your discretion.  

FYSA  @DanielleThierryUSDSVA

**Comment by andaleliz** [comment]
Thanks @mnorthuis! I've reviewed and it makes sense to me. Will let @ajakabcin close once she's had a chance to review too.

**Comment by Samara-Strauss** [comment]
This looks good to me.

@mnorthuis are you also reviewing the IA of the notification groupings? I know @DanielleThierryUSDSVA is working with @andaleliz on the copy, but not sure if you also wanted input into that IA. Liz, have you talked about this with Mikki?

**Comment by mnorthuis** [comment]
@Samara-Strauss Yes, I just joined that convo this morning, and will drop in any feedback I have on the ticket that is covering that.  Thank you!

**Comment by Samara-Strauss** [comment]
Awesome! Thank you for letting me know.

**Comment by ajakabcin** [comment]
documentation updates can be tracked in #24696 , closing this
