### ISSUE TITLE
CT: Add documentation for the gibct-data-service repo

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23283]
As a developer, I need to update the documentation for the gibct-data-service repo so that when new developers join the project they have the information that they need to begin development.

## Assumptions:
1. The documentation is located in README.md
2. The documentation listed is the minimum, any additional documentation that would be beneficial to be added can and should be added.

## Acceptance Criteria:
1. Scorecard API fetches are documented.
2. Version generation (app/models/institution_builder.rb) is documented.
3. Can go through repo setup steps and have GIDs deployed locally

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/804
