### ISSUE TITLE
[FSR] Privacy policy content

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#23298]
We need to customize the Privacy Act statement modal for our product, to be included on the review page of the FSR:
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/4af91840-07f2-4fed-82f1-0c7a3738d36a)

Per staging feedback:
The link should go to the Privacy Act statement modal, which should have content customized for each form.
I believe the sitewide content team is making updates to the content for the Privacy Act statement modal, so they should be able to provide you with an update on where the latest content can be found.

--
- [x] Get in touch with sitewide content to customize content
- [x] Finalize and post results in the [FE ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23297)

**Comment by rileyorr** [comment]
Met with Beth yesterday, subsequent discussions have been happening in [this thread](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22475).

**Comment by rileyorr** [comment]
Updated the frontend ticket with both parts of the form that need the varying privacy act content.
