### ISSUE TITLE
Access for Jesse House

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23295]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter (@Jeff-Hayter)
- Please provide your name.
   > Jesse House
- Please Provide your email.
   > jesse.house@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Operations

- Requesting SSH key authorization?
   > YES

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDA5/D9qJGK6gNRxTU7zndNkqmpz2110gVKtHnvQbDfiaS8qRJDsJrzkmu9+cIpDPOis+PPUxfg7x3SYSkF0pmNoOWwP/i6yBPWxiCpFct0fWnVH13mddxtPGd6hh6zIIWMbfKYPjzEp+w4CdS8R27imEqO1j717xp7gp+Zvx8ou2AGPcnKNa6jo7B0ezeZjT5u7xqWu3ag6SMWg9Bi5nZy60G/SBPSUdjSf7seT0qBJCo8GGBfIzwAPjkrIx4Z0qTxARR2+/RPIU4x2iOpziZCqDhpugPAXXNZlSdsiimxzr9O/P2yLRziBCdLXfAMiKkeVD41AM+Pzv+5J47/kGCZ14Ao6EQM48mlpGZ5BcB0Dvr6K2htL/JKYVA1b5szVJsH1dPoKzY1Cl1TIwMiNWV6RO7zABYmcyq1Q8OEOAUo/KrsiViSJJ6JMuDGRKl8gU+1j1SdunJol+6RIa6hYGhl4dxo+N6pWP+3OZnigQT+lQrDvveAnWV+t2Z5unsiwJM= jesse.house@adhocteam.us
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  - CloudWatch/EKS for product support purposes if possible (but the most important and immediate need is SOCKS)

**Comment by mleclerc00** [comment]
### AWS Access

User: Jesse House
COR: Jeffrey Hayter 
Approval required: @Jeff-Hayter

**Comment by mleclerc00** [comment]
@mchelen-gov 

Circling back on this aws request for approval

Thanks!

**Comment by drorva** [comment]
Approved
