### ISSUE TITLE
Analytics Implementation for design.va.gov

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#23296]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
  - **Implementation**
- Who is this request for?
    - **Chris Valarida, Carol Wong**
- What team/project is this work for?
    - **VSP Design System Team**
- Provide the Domain where Google Analytics needs to be implemented
    - **design.va.gov**
- Please provide any upcoming deadlines or important milestones
    - **None:** There's no deadline or anything, but the sooner we get analytics, the sooner we can see whether the documentation efforts we've been focusing on are proving fruitful
- Typical Website Interactions to Track
    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
      - **Everything?** :man_shrugging:
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
      - **For now, none**

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A

- Certain conditions/responses that need to be reviewed

    - N/A

- Additional Comments

    - Nope, I ain't got nothin' here. :smile: Thanks for helping us out!

> Please leave the following blank

## Acceptance Criteria
- [ ]  Setup a Google Analytics view on property `UA-50123418-19` specifically for design.va.gov
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by jonwehausen** [comment]
Hi @cvalarida , 

@laurensimpson14 is going to handle this request from this point forward but with her being out I at least wanted to provide you next steps here. 

First step is going to be embedding our GTM snippet to begin capturing design.va.gov standard/vanilla metrics (pageviews, sessions, etc).

### GTM Snippet

1. **Paste this code as high in the `<head>` of the page as possible:**
```javascript
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T2ZTDXZ');</script>
<!-- End Google Tag Manager -->
```

2. **Additionally, paste this code immediately after the opening `<body>` tag:**

```javascript
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T2ZTDXZ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by jonwehausen** [comment]
From here work with @laurensimpson14 on additional event tracking you all may need.

**Comment by cvalarida** [comment]
This is just for design.va.gov, right? I'd need a separate `gtm_auth` value for staging and dev? (For clarity, I don't think we'll need analytics in those environments right now. I just want to make sure I'm understanding correctly.)

**Comment by laurensimpson14** [comment]
@cvalarida You won't need to implement a different snippet for each environment. It'll just be the production one and then we can filter our dev/staging traffic on the GA side.

**Comment by laurensimpson14** [comment]
Here is a link to the new Google Analytics view on property `UA-50123418-19` specifically for design.va.gov: https://analytics.google.com/analytics/web/#/report-home/a50123418w224573768p241857190

**Comment by laurensimpson14** [comment]
@jonwehausen Could you please QA the changes I made to the `VSP - GitHub TOC and Platform Docs` GTM account inside of the `Analytics Implementation for design.va.gov #23296` workspace? You should now be seeing the GA global pageview tag firing in GTM preview.

**Comment by bsmartin-ep** [comment]
## QA

The pageviews and scroll depth tagging LGTM @laurensimpson14.  

I wonder though if we need to make these changes to the `CL - Relevant Click Classes` variable:

![image](https://user-images.githubusercontent.com/62304138/116335871-8eabd380-a7a5-11eb-8890-742c4f9ce88c.png)

The `EV - Global Link Tag` tag seems to [only apply to the old TOC page](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w224573768p212889364/_u.date00=20210201&_u.date01=20210426&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.hostname&explorer-table.rowCount=1000&explorer-table.filter=Practice%20Area&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Practice%20Area%22,0%5D%5D/).

https://department-of-veterans-affairs.github.io/va.gov-team/

If not - maybe  back this out and rename it as deprecated?

**Comment by laurensimpson14** [comment]
Brian, I've abandoned the changes to the `CL - Relevant Click Classes` variable and published out the others. 

@cvalarida The design.va.gov property is now collecting data: https://analytics.google.com/analytics/web/#/realtime/rt-overview/a50123418w224573768p241857190/

I'm going to close this ticket, but please feel free to re-open if there is anything further that I can assist with!
