### ISSUE TITLE
Nav bar icons / text misaligned - not spaced evenly

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#23291]
## What happened?
Nav bar icons and text need alignment.

## Specs:
- Device: Android and iOS

## Steps to Reproduce
View nav bar.

## Desired behavior
Icons and text are aligned.
Icons and text are evenly spaced.

## Acceptance Criteria
See above.

## Bug Severity
4 - Low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/22708

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/097e3694-000e-4d03-81c3-467049b3d812)

**Comment by bessgreen** [comment]
Note for QA: please retest once #23440 is merged

**Comment by digitalken** [comment]
PASS 5/10/2021 - Looks good on both iOS and Android.  Closing.
