### ISSUE TITLE
[FSR] Move Financial Overview header into detail box

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#23294]
Move the financial overview header into the blue detail box on the resolution selection pages as seen here:
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/96b327fb-962a-486f-9136-459bcbedd128)
[UXPin link](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136429387/specification/sitemap)

**Comment by LinnJS** [comment]
I did this one a while back... I think its a duplicate.
