### ISSUE TITLE
Use self-hosted runner in vets-website and content-build GitHub Actions workflows

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#23300]
## Description
In the course of creating a GitHub Actions workflow for `vets-website`, we observed some variations in runtimes where our other CI tools typically took less time. For example, a build step that would usually take 9 minutes in CircleCI sometimes exceeded our maximum timeout of 15 minutes in GHA.

We may be able to improve runtimes for our GHA workflows by allocating more CPU cores to the runner. There isn't a way to configure that for the default GitHub Actions runner, but it's possible with a self-hosted runner.

Furthermore, by hosting our runner internally, the CI pipeline would have access to internal systems like the Drupal CMS. We'd be able to run a content build independently of a content caching solution.

## Definition of done
- [ ] Use a runner hosted within our internal infrastructure instead of the GitHub runner in workflows for both `vets-website` and `content-build`.
- [ ] Achieve runtimes in longer GHA jobs (such as build or unit tests) that are comparable to their counterparts in Jenkins or CircleCI.

**Comment by U-DON** [comment]
- Initially needed to explicitly install Yarn; the self-hosted runner didn't have the same dependencies as the `ubuntu-latest` environment for the default GitHub runner.
- Ops has since configured the image to match the GitHub environment, and we no longer have to explicitly install Yarn.
- Managed to get a full build working within the self-hosted runner using both the prod CMS URL and the new Tugboat URL.

**Comment by jhouse-solvd** [comment]
@U-DON - no rush, but if you can add any notes as to the current status, that would be helpful. Thank you!

**Comment by U-DON** [comment]
The use of self-hosted runners seem stable so far from testing. The parallelized Cypress tests are currently running across all branches.

We would like to roll out a bit more of the pipeline (still non-blocking) so that VFS teams will have the GHA pipeline with builds for all environments (vagovdev, vagovstaging, vagovprod).
- These builds would account for the remaining jobs that would require self-hosted runners.
- This would enable us to validate the stability and performance of the runners in a way that would more closely resemble the full launch of a merge-blocking GHA pipeline.

When we've merged those jobs into `master`, I think we can close this ticket and open new ones if necessary for any issues that arise.

**Comment by meganhkelley** [comment]
Closing ticket in favor of more specific troubleshooting tickets: 

Troubleshoot artifact uploads in GitHub Actions content-build #27680
Builds and tests are timing out in GHA implementation #27683
