### ISSUE TITLE
Update Footer Links | Spanish, Tag, Other | Language Assistance and Resource Pages | C&L Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#23305]
## USER STORY ##

As an LEP (Limited English Proficiency) Veteran, family beneficiary or caregiver, I would like to access all translated content from the VA.gov homepage using a single, easily identifiable link. 

## Expected Behavior

As a Veteran seeking spanish or tagalog content on VA.gov
WHEN
I am viewing the  footer near the bottom of the page 
THEN
I should see text~"Language support"~ "Language assistance" followed by a second line with hyperlinks directing me to either spanish, tagalog or other languages
AND
Upon clicking this link I am taken to a resource page in spanish or tagalog (or other)  per my selection (URL: TBD)

## Comp ##

Desktop:  https://www.sketch.com/s/d4137b22-6930-46e1-8158-37718cc36265/a/KvRVgVV 

![Screen Shot 2021-04-15 at 1.55.04 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/f455010d-f411-4e5b-a1f2-8c5f2d7289ff)

Note: Please use production footer as it is being updated. I am only including the mock here to show placement for spanish/tagalog links AND some re-design for the right-hand column of the footer to make the section more readable.

Mobile:  https://www.sketch.com/s/d4137b22-6930-46e1-8158-37718cc36265/a/YG54x4E 

![image.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/4a6c3a3d-6de5-43fe-b6c8-aad1e7ff6f8d)

Note:  Language support collapses into its own accordion on mobile 

## Tasks ##

[ ] URLs for Spanish, Tagalog and Other Language pages

## Acceptance Criteria ## 

[ ]  Clicking spanish or tagalog resource link in footer area takes you to appropriate resource page (URL: is TBD)
[ ]  Accessibility checks complete

**Comment by SKasimow** [comment]
@youngfreezyVA hi - can you point this?

**Comment by youngfreezyVA** [comment]
i am going to try to re use the previous [`i18Select](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/i18Select/I18Select.js)` component, so we'll need to regression test that feature as well.

**Comment by SKasimow** [comment]
@youngfreezyVA are you able to get this started without URLs finalized? We should have next week.

cc @DanielleThierryUSDSVA

**Comment by youngfreezyVA** [comment]
yup, I can put in placeholder URLS for now

**Comment by SKasimow** [comment]
@youngfreezyVA awesome - lmk if you need anything else to start working on that ticket!

**Comment by youngfreezyVA** [comment]
nope, it looks like this ticket captures an update to the entire layout of the footer, not just adding in the lang resources

**Comment by SKasimow** [comment]
@youngfreezyVA Also, I broke up the requirements for the new Language Assistance links (described in this ticket) and then created a new ticket for some updates to the existing footer here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23541

**Comment by youngfreezyVA** [comment]
ah, perfect @SKasimow thanks so much!

**Comment by SKasimow** [comment]
@youngfreezyVA I will be opening up some additional tickets for testing, analytics etc but think the bulk of the FE work will be in the 3 tickets that are now in the Ready column. Can you give me a eta on when you can complete? I'm trying to get staging reviews, QA etc lined up so we can hit a June 1 launch date.

Thanks,

Sharon

**Comment by youngfreezyVA** [comment]
i'd say 1.5 - 2 sprints since i'll need to thoroughly regression test and write unit tests, as it impacts the entire website, since the footer is used everywhere.

**Comment by SKasimow** [comment]
@youngfreezyVA Hmmm..we are in sprint 47 and sprint 48 closes June 1st. Think we'd be cutting it too close (plus I still have to create an analytics ticket, just sent you a feature toggle ticket and would like to have some breathing room if we have fixes or small changes).

For the general footer update which is 5 pts (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23541 ) thinking if we were to get agreement to make it a nice-to-have or post-launch item,  that would help right? Just want to make sure it's not as easy to do the general footer changes when hood is up and regression testing is planned for footer.

**Comment by youngfreezyVA** [comment]
yes i think having the footer changes in a later sprint would be best.

**Comment by SKasimow** [comment]
@youngfreezyVA I spoke to Danielle and she's in agreement with deferring the General Footer update ticket post-launch (if necessary) https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23541

Can you have the rest of the work completed within this sprint (Sprint 47 ends May 18th)?

@DanielleThierryUSDSVA

**Comment by youngfreezyVA** [comment]
Yes, that sounds reasonable. I'm about 50% done as is.

**Comment by SKasimow** [comment]
@youngfreezyVA Wow - that's awesome!!!! Yay Fareez!!

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA @youngfreezyVA Made the update to replace text for "Language support" with "Language assistance"

**Comment by youngfreezyVA** [comment]
hey @rtwell can you confirm the colors used for the links, section sub titles (ie Get answers)
and the borders at the top / bottom for language support?

**Comment by rtwell** [comment]
they should be white—you can inspect the colors in the sketch doc here:

https://www.sketch.com/s/d4137b22-6930-46e1-8158-37718cc36265/a/Vrojxjl#Inspector

please make sure you reference the web design system colors (not random hex codes)

**Comment by youngfreezyVA** [comment]
awesome, looks like that color is already being used, no changes required on my end:
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/sass/modules/_m-footer.scss
