### ISSUE TITLE
Clipboard Collab Cycle 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#23302]
Track all VSP Collaboration cycle touch-points to release product

**Comment by julieadair1** [comment]
@leahkeeler does this epic need to remain open?  
cc: @jparker0425

**Comment by jparker0425** [comment]
@julie closing this out. Questionnaire was released earlier 2021 and has been hold since the Check-in product was picked up. We may end up incorporating some of the Questionnaire work in Pre-check-in, but that work can be added to a new epic specific to that work.
