### ISSUE TITLE
[Campaign Landing Page Production MVP] - VA Trust

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#23304]
## Description 

As part of VA.gov's Campaign Landing Page MVP Production phase, the Veterans Experience Office (VEO) wants to launch a CLP in support of a communications initiative to create more Veteran, public and Congressional awareness about VA's  improved services and value delivery as represented by Trust Scores.

## Key Info

**Who is Requesting**

- Requestor name: Tim Hudak
- VA organization: VEO
- Email address: timothy.hudak@va.gov

**About the Campaign**

- Name or focus of Campaign: Trust
- Target audience(s) [up to 3]:
   - Veterans
   - VSOs
   - Congress
- Goals of the Campaign:  
   - Increase transparency, accountability. Demonstrate VA’s commitment to listening to the voice of the Veteran by displaying VA trust scores publicly.
- Campaign start and end dates: 
   - April 29th, 2021
- Campaign page target launch date: 
  - April 28th, 2021
- Preferred URL: 
   - www.va.gov/trust
- What will you to drive awareness of this Campaign and this page? 
   - Social media, #VetResources, VSO and Congressional engagements
- What metrics will you want to know to measure success of the Campaign landing page? 
   - visitors / new visitors

**About Your Campaign Page Build**

- How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system enough to use the campaign page?
  - Very (Tim)
- Who will build the campaign landing page in the VA.gov CMS?
  - Tim
- Who will review and give approval to publish the page? 
  - Tim
- Who will update/maintain the landing page during the campaign?
  - Tim
- At the end or your campaign, do you want to page to be retired/removed from VA.gov or preserved?  If preserved, why?
  - It may be “retired” as it is replaced with a larger effort or a larger dashboard page.

## What Needs to Be Done

- [x] CMS: Set up the CLP page in CMS for Tim to use as his build template
- [x] Product: Get the Analytics dashboard set-up and UTM campaign code for Tim and his team
- [x] Product & IA: Validate that the requested URL -- va.gov/trust -- is optimal (e.g. should it be va.gov/campaign-trust and instead set va.gov/trust as a redirect.
- [x] Product: Determine if Tim's build needs to go through light Collab Cycle prior to launch (Analytics, Accessibility, Content)

**Comment by brianalloyd** [comment]
@johnhashva we'll need to define URL before I can submit a UTM request.  @mnorthuis could you review the ticket and requested URL and advise on recommended URL approach forward.  Once defined I'll begin working UTM and Analytic tag management components.  Thanks.

**Comment by johnhashva** [comment]
Adding here the staging/pre-launch Collab feedback (mostly accessibility and content) provided to VEO-Tim Hudak on 4/27.   He agreed to make most of these changes prior to launch.

[CLP-Trust-Feedback.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6392678/CLP-Trust-Feedback.docx)

**Comment by jenniferlee-dsva** [comment]
@johnhashva - Regarding feedback doc: We don't want to suggest adding links to campaign pages from global elements such as the top nav and footer. Those things are evergreen and should not be linking ever to temporary, time-based content. 

Also - OCTO does not entirely own what things we link to under the About VA flyout menu. Some of those things there are legally required and OPIA has a lot of final say there.

**Comment by brianalloyd** [comment]
Campaign is now live, closing ticket in support.
