### ISSUE TITLE
VRRAP: Email validation allows differing email addresses

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#23314]
## Steps to reproduce:

1.  Log in with any user
2. Navigate to https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply
3. Proceed to Contact information Phone & email on the form
4. Try entering in two differing email addresses like below
![Screen Shot 2021-04-15 at 2.20.06 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4fb28df9-4d72-4198-9838-8c1619b16d69)

## Expected results:

1. Should be similar to how 10203 form works with email validation observe below, should only be allowed to continue with the same email
![Screen Shot 2021-04-15 at 2.28.33 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/70e0fe53-3599-4beb-bd44-3af49122cbcc)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16810

**Comment by delli-gatti-michael** [comment]
Local testing complete
![Screen Shot 2021-04-15 at 3.16.29 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/b070a3ed-2524-4d53-bcc8-275cbc0dac2a)

**Comment by delli-gatti-michael** [comment]
Fix is now on staging
