### ISSUE TITLE
VRRAP: Staging error on submission

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#23325]
## Steps to reproduce:

1. Fill out https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s 
2. Continue to Step 2 of 2: Review Application
3. Leave "I have read and accept the privacy policy(*Required)" unchecked and try to submit
4. Error displays
![Screen Shot 2021-04-15 at 2.57.12 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/238d27f9-88d3-40e2-9aa5-eb567dbf7935)
5. Unable to proceed after error

## Expected results:

1.  Error doesn't occur with validation of "You must accept the privacy policy before continuing." only and allows submission.

## Additional Info
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/components/review/PreSubmitSection.jsx is what calls/uses/sets up https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/1990s/containers/PreSubmitInfo.jsx#L110

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16819

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Fix is now on staging
