### ISSUE TITLE
Review request for Content/IA for Epic #756 Texting for Medical Appointments

### ISSUE THREAD

**Issue by lichellebain** [department-of-veterans-affairs/va.gov-team#2332]
Functionality adds a new text box field under Mobile Phone Number on profiles page, This field will allow users to receive text notifications for their medical appointments.
URL: https://staging.va.gov/  User 220 and 226 were used in testing.
Mock up: https://vsateams.invisionapp.com/share/FSTDOO0WUHC#/screens/378179664

Note: The green box containing the save message that appears after the user edits the check box on the profile page does not have a check box as the mock up shows. This is due to the fact that the check mark is not in the style guide for alert messages.

There is one existing defect: The cancel button does not appear to clear the unsaved checked box in the pop-up.

Steps:
1- On the profile screen, start with an existing mobile number, but the text box unchecked.
2- Click on Edit to open pop-up.
3- Click on the text box
4- Click on Cancel—which takes you back to the profile page.
5- Click on Edit to open pop-up.
6- The text box is still checked.

I would expect that the check box would not be checked since the user pressed cancel and it was never saved.

**Comment by peggygannon** [comment]
@lichellebain Please see my content review edits below. 

1. No changes to the checkbox copy ("Send me text message reminders....," as I had reviewed this content earlier). 

2. Please update in-line mobile phone message to the below:
We’re saving your new mobile phone number. We’ll show it here once it’s been updated.

**Comment by peggygannon** [comment]
@lichellebain please see additional update to this message, per request in https://github.com/department-of-veterans-affairs/va.gov-team/issues/2442

We’re saving your mobile phone number and text alert preference. We’ll show them here once they've been updated.

**Comment by mnorthuis** [comment]
@lichellebain FYI, No IA review is required for this work since it is just content being added to an existing page.

**Comment by lkoenigsberg** [comment]
@elwoodva , please see Peggy's suggestions and coordinate with her on any questions.
