### ISSUE TITLE
On-site Search: Legacy sites search switch-over

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#23322]
### Description

The legacy VA sites search team -- led by Kevin Reid -- has decided not to renew its license for its Search software/engine (IDOL) and redirect any request -- except for [BVA Decision queries](https://www.index.va.gov/search/va/bva.jsp0 -- to https://www.va.gov or https://www.va.gov/search/?query= if there is a searched term.

### Use Cases

Basic use cases:

Submit a search form
- Currently resulting search - https://www.index.va.gov/search/va/va_search.jsp?NQ=URL%3Ahttps%3A%2F%2Fwww.salem.va.gov%2F&QT=hours
  -NQ is a parameter passed via VA search forms (the value above is just an example) to determine the source of the query and bias search results to favor that site in search results

- New action if a term is searched
   - Redirect with the queried term to https://www.va.gov/search/?query=hours
    - OR, I can send the NQ parameter or other parameters that might be useful for you to know the request was a redirect

- New action if no term is searched (which happens more often than it should)
   -  Redirect to https://www.va.gov
   - Not a great option because currently some top level results are returned. A redirect to www.va.gov will drop them on https://www.va.gov without any context
     - Existing results for a blank query from the Salem site: https://www.index.va.gov/search/va/va_search.jsp?NQ=URL%3Ahttps%3A%2F%2Fwww.salem.va.gov%2F&QT= 
      - Existing results for a blank query: https://www.index.va.gov/search/va/va_search.jsp?QT=

- Directly visit https://www.index.va.gov or any page that isn’t https://www.index.va.gov/search/va/bva.jsp 
  - Redirect to https://www.va.gov/

##Worth Noting

- BVA Decisions currently holds about 1.3M documents and is not indexed by other Internet search engines. It used to be indexed by Google and Bing after I created sitemap.xml files to link all of the content but the sitemaps were removed from www.va.gov a few years ago when the new search engine was implemented.
.

**Comment by denisecoveyduc** [comment]
@johnhashva will discuss further with Kevin Reid.  Specifically: 
- Collect a list of terms that refine the results that are presented to users(hours, directions, etc.) There may be ways we can improve the experience and transition for veterans
- Determine the plans to remove or keep the legacy search header vs replace it with the modern search header.

**Comment by denisecoveyduc** [comment]
May 4 - @johnhashva reached out to Kevin so ask if there were any updates or any further support needed. Rolling over to S47 to ensure all needs have been met.

**Comment by denisecoveyduc** [comment]
We have made a few attempts via email to reach out to Kevin to confirm no further support is required. Anticipate he will reach out  should he need anything from the team.
