### ISSUE TITLE
Access for Ryan Johnson

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#23323]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter (@Jeff-Hayter)
- Please provide your name.
   > Ryan Johnson
- Please Provide your email.
   > Ryan.Johnson@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP/Testing Team

- Requesting SSH key authorization?
   > No (already have it)

```
N/A
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  - CloudWatch/Synethetics (Canary) for working with synthetics monitoring of va.gov

**Comment by omgitsbillryan** [comment]
cc @rjohnson2011

**Comment by mleclerc00** [comment]
### AWS Access

User: Ryan Johnson
COR: Jeffrey Hayter
Approval required: @Jeff-Hayter

**Comment by mchelen-gov** [comment]
Approved, eQIP application date confirmed by Amber Malcolm.

**Comment by omgitsbillryan** [comment]
Account created and access granted.
