### ISSUE TITLE
Use Redis for triage teams, folders, and folder messages

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#23333]
We want to be able to cache the triage teams, folders, and folder messages in Redis so we can improve performance when re-loading entities that we've already fetched.

**Comment by narin** [comment]
@ashley-matthews Pagination is actually working already on the `vets-api` layer so we are not blocking the mobile team at all.  Updated this ticket to be related to Redis caching so we can improve performance.
