### ISSUE TITLE
Request Security Review for Epic #756 Texting for Medical Appointments

### ISSUE THREAD

**Issue by lichellebain** [department-of-veterans-affairs/va.gov-team#2333]
Functionality adds a new text box field under Mobile Phone Number on profiles page, This field will allow users to receive text notifications for their medical appointments.
URL: https://staging.va.gov/  User 220 and 226 were used in testing.
Mock up: https://vsateams.invisionapp.com/share/FSTDOO0WUHC#/screens/378179664

Note: The green box containing the save message that a appears after the user edits the check box on the profile page does not have a check box as the mock up shows. This is due to the fact that the check mark is not in the style guide for alert messages.

There is one existing defect: The cancel button does not appear to clear the unsaved checked box in the pop-up.
Steps:
1- On the profile screen, start with an existing mobile number, but the text box unchecked.
2- Click on Edit to open pop-up.
3- Click on the text box
4- Click on Cancel—which takes you back to the profile page.
5- Click on Edit to open pop-up.
6- The text box is still checked.
I would expect that the check box would not be checked since the user pressed cancel and it was never saved.

Ahead of the review, Andrew needs:
• an architecture diagram, showing involved systems + data flows
• description of any new publicly-exposed endpoints (vets-api or otherwise)
• description of any new interactions with dependent services (i.e. vets-api --> ???)
• description of any other security hotspots you're concerned about / want extra attention on

**Comment by elwoodva** [comment]
There should already be some documentation with these data flows.  This did not change for this text permission flag.

There are no new endpoints exposed in vets-api.  The interaction with VET360 did not change.  VET360 was always returning this flag.  It was already part of their interface with vets-api.

We don't believe this would have introduced any new security risk that the existing functionality didn't already address.  We are just adding the checkbox to set a flag on the Mobile Phone number transaction that was not already being set in the existing Profile transaction.

**Comment by lkoenigsberg** [comment]
@elwoodva and @gunsch , what is the status of this review please?

**Comment by gunsch** [comment]
Status at https://dsva.slack.com/archives/CBU0KDSB1/p1571179979092400?thread_ts=1570564090.361700&cid=CBU0KDSB1 --- I'm still looking for Elwood or Lichelle to schedule a security review and provide architectural details that we can speak to/review.

**Comment by elwoodva** [comment]
Yes, @lichellebain has been out this week but she will schedule that review when she gets back next week.  Since I'm not sure exactly what architectural details you still need since we're using the existing transactions and endpoints we can discuss it during the review I think.

**Comment by lkoenigsberg** [comment]
@elwoodva , I think we can solve this using copy instead of making both a copy and design change.

My proposed solution is to use new copy (from https://github.com/department-of-veterans-affairs/va.gov-team/issues/2581) but keep the check boxes on both the profile and within the modal.

cc/ @Samara-Strauss and @claricechan

**Comment by lichellebain** [comment]
@gunsch  Do you have a list of what architectural details you will need?  Hopefully we can meet this afternoon or tomorrow.  What is your availability? @elwoodva @talbotmj

**Comment by elwoodva** [comment]
I cannot provide an architectural diagram before the meeting (hopefully tomorrow) but I can answer questions at the meeting.

**Comment by gunsch** [comment]
Easy enough review, thanks for the demo! No concerns from my end. 

LGTM
