### ISSUE TITLE
VRRAP: Update breadcrumb and direct deposit

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23332]
As a developer, I need to update the bank account label and form breadcrumbs so they are in line with DEPO recommendations.

## Assumptions:
1. The form is found on staging here: https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction
2. The only changes to the breadcrumb is 2d; including the entire breadcrumb for clarity.

## Acceptance Criteria:
1. The "Bank account number (No more than 17 digits)" label is replaced with "Bank account number"
    a. The only validation on the field is that it is required.
2. The breadcrumb for the form is: Home > Education and training > Other VA education benefits > Veteran Rapid Retraining Assistance Program (VRRAP) > Apply for the Veteran Rapid Retraining Assistance Program (VRRAP)
    a. Home - URL when active: [https://[environment].va.gov/]()
    b. Education and training - URL when active: [https://[environment].va.gov/education/]()
    c. Other VA education benefits - URL when active: [https://[environment].va.gov/education/other-va-education-benefits/]()
    d. Veteran Rapid Retraining Assistance Program (VRRAP) - URL when active: [https://[environment].va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance]()
    e. Apply for VRRAP VA Form 22 1990s - URL when active: [https://[environment].va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s]()

## Supporting Artifacts:
N/A

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16824

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1712)
