### ISSUE TITLE
AWS access for Kenneth Santiago

### ISSUE THREAD

**Issue by ksantiagoBAH** [department-of-veterans-affairs/va.gov-team#23350]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Doris Lin
- Please provide your name.
   > Kenneth Santiago
- Please Provide your email.
   > santiago_kenneth@bah.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA .gov team, Junior Developer, BAH

- Requesting SSH key authorization?
   > NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+AAAByyyz/1234+ username@mail.com
```

- Grant AWS Console access?
  > YES 
  - What AWS services do you need access to and why? 
 I would need the same access as the bah-vfs-developers group

**Comment by ksantiagoBAH** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by mleclerc00** [comment]
### AWS Access

User: Kenneth Santiago
COR: Doris Lin
Approval required: @Jeff-Hayter

**Comment by mleclerc00** [comment]
Jeff let me know that we need approval from Doris Lin to move forward with AWS access but I can't seem to fin their user to ping in this thread

**Comment by mleclerc00** [comment]
I have reached out to Doris Lin via email and will proceed once access is approved.

**Comment by mleclerc00** [comment]
Received approval from Doris Lin.  Will provide AWS console access via Slack.
