### ISSUE TITLE
Regularly Scheduled Deployments of Jenkins

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#23357]
### The Problem
Jenkins is currently not on any kind of regular deployment schedule. As a result, we go long stretches between deployments. This poses a number of problems:

1. Deployments become scary
2. No reliable schedule to get Jenkins code changes deployed (up to the developer to make a judgment call as to whether or not to deploy)

### Extra Context
- [The current Jenkins deployment process](https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Jenkins%20deployment%20workflow.md) incurs ~2 minutes of downtime
- 9pm EST is the earliest time we're allowed to incur any downtime per SLA
- The problem is that updating Jenkins comes with updated plugins, causing conflicts

### Definition of Done: 
- [ ] Create a schedule/process for deploying Jenkins on a regular cadence
- [ ] (Optional) Investigate ways to make the deployment process less manual

**Comment by jhouse-solvd** [comment]
This isn't a super high priority at the moment. Requests that require a deployment of Jenkins do not occur very frequently, and it seems most teams are getting on with GitHub Actions at this point. Additionally, the Ops team will be looking to potentially sunset Jenkins (or reduce usage significantly) at some point in the not-too-distant future.

**Comment by jhouse-solvd** [comment]
Based on the level of effort, and the move to deprecate Jenkins in the near future, we are going to close this issue. We can revisit if it continues to be a pain point worth addressing. 

Closing.
