### ISSUE TITLE
Replace connect() with hooks on ClinicChoicePage in vaccine flow

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#23351]
We want to update the way we use react-redux to the current recommended approach, which is to use the useSelector and useDispatch hooks.

Docs: https://react-redux.js.org/api/hooks

Note: it's worth paying attention to the [equality comparison](https://react-redux.js.org/api/hooks#equality-comparisons-and-updates) section. If a selector is returning an object, that object is changing each time the selector is run, and we're just using individual properties within that object, consider using shallowEqual.

AC
- [x] connect() is no longer used on page
- [x] All actions that were in mapDispatchToProps are now wrapped in dispatch() when called
- [x] All data in mapStateToProps is pulled in through useSelector hooks

**Comment by grossb1** [comment]
I submitted a PR with a couple of questions as commented out code.
