### ISSUE TITLE
Request accessibility/508 review for Epic #756 Texting for Medical Appointments

### ISSUE THREAD

**Issue by lichellebain** [department-of-veterans-affairs/va.gov-team#2336]
## Instructions

1. Click or press the gear icon next to the "Labels" heading on the right. Search for your team in the labels list. If your team is not listed in the Labels menu, please leave a comment after you have created this issue. The Product Support team will create a new label for your team.
2. Text inside `<-- comment -->` blocks will not appear in your issue ticket. These comments offer guidance on what information you should provide for each section.

## Team Name

Bylight
## Product Description
Epic #756 Texting for Medical Appointments

Functionality adds a new text box field under Mobile Phone Number on profiles page, This field will allow users to receive text notifications for their medical appointments.
## Staging URL and Credentials

URL: https://staging.va.gov/ 
User accounts 220, and 226.
## Known Issues
There is one existing defect: The cancel button does not appear to clear the unsaved checked box in the pop-up.  This is not 508 related.
Steps:
1- On the profile screen, start with an existing mobile number, but the text box unchecked.
2- Click on Edit to open pop-up.
3- Click on the text box
4- Click on Cancel—which takes you back to the profile page.
5- Click on Edit to open pop-up.
6- The text box is still checked.
I would expect that the check box would not be checked since the user pressed cancel and it was never saved.
[https://app.zenhub.com/files/133843125/cba9408e-4eb9-4d89-b5a6-75bd99f7b5fd/download](https://app.zenhub.com/files/133843125/cba9408e-4eb9-4d89-b5a6-75bd99f7b5fd/download)
[https://app.zenhub.com/files/133843125/920e3658-51b9-4381-86ce-1dcb39cfbedf/download](https://app.zenhub.com/files/133843125/920e3658-51b9-4381-86ce-1dcb39cfbedf/download)

[508 Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=508%2FAccessibility&template=508-issue.md&title=)

- **Related Issue URL:** _Delete if no known issues._

**Comment by 1Copenut** [comment]
@lichellebain I've logged all issues in epic https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2443 and am moving this pre-launch 508 audit to close.
