### ISSUE TITLE
Common component: Notification banner

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23373]
## User Story
As a user, I want to see an in-app reminder when I have an upcoming appointment. 

## Acceptance Criteria
1. Create common component for the notification banner, with the specs indicated below:
2. Specs:
     - Border: none
     - Text style: Hint Text
     - Text color: variable
     - white #ffffff
     - Background color: primary #0071bb
     - Internal padding: 10px
     - Margin left-right: standard gutter
     - Margin top-bottom: marginBetween
     - Border radius: 5px
     - Height 60px
3. Placement for the banner:
    - When a banner displays on a page that includes the VCL, the notification banner should display below the VCL
    - When a banner displays on a page that excludes the VCL, the notification banner should display below the page header
4. The banner is dismissed when either of the following occur: 
     - User selects the the link in the banner, OR
     - The banner displays for 8 seconds. After 8 seconds, it should disappear

## Designs
![Screen Shot 2021-04-16 at 2.02.22 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e56a041f-790b-4eae-8453-65ffcacf44bd)https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447951000

**Comment by bessgreen** [comment]
Open Qs:
1. UI specs
2. Should rules about dismissing the banner be handled by the component?

**Comment by msmanak** [comment]
WIP

1. UI specs

2. Should rules about dismissing the banner be handled by the component?

3. Time duration for how long the banner should display?

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by ashley-matthews** [comment]
No longer the path we are taking with push notifications
