### ISSUE TITLE
Notification banner: Appointments

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23375]
## User story
As a user, I want to see an in-app reminder when I have an upcoming appointment.

## Acceptance Criteria
1. When the app is open and an appointments push notification comes through, display the notification banner in the app
2. Pull in Notification banner CC (#23373)
3.  Copy in the banner is variable depending on the # of appointment reminders that are pushed:
     - When 1 appointment is pushed: "You have an upcoming VA appointment, review your appointment"
     - When >1 appts are pushed: "You have <#> upcoming VA appointments, review your appointments"
4. The hyperlink in the notification banner routes to the Upcoming Appointments page _(note for dev: there is not a way to link to the appointment detail page)_

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/447951000

## Accessibility Acceptance Criteria
1. Everything on the page should be read by the screen reader.
     - If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the component type needs to be announced by the screenreader. (Include name (title), role, value)
2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap, or horizontal scroll.
3. Each touch target must be at minimum 44px by 44px
4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.  
5. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
6. When a page opens, the first section or element should automatically be placed in focus
7. When a page opens, the title page should be announced

## Accessibility Implementation Guidelines 

**Appointment banner: link button**
- accessibilityTitle= "review your appointment" or "review your appointments"
- accessibilityRole= "link”
- accessibilityHint= "go to the appointments page"

## Dev Checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by ashley-matthews** [comment]
Not launch critical

**Comment by ashley-matthews** [comment]
No longer the the path we are using, we are sticking with system notification bubbles in the app
