### ISSUE TITLE
10-10CG Improve Veteran Medical Care Page

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/va.gov-team#23383]
As a veteran, I want to be able to fill out questions about medical care without being confused.

The program team said we need to keep the "Most recent medical care" question for now. We need to make it more obvious that it's optional, and add. some language about why we need it.

Suggestion to make it its own page, articulating that it is optional.

**Comment by sshein** [comment]
we also need to figure out what to tell the user if the VA medical center they go to isn't in the dropdown list

**Comment by SKasimow** [comment]
This will be addressed in facility design so closing. Facility ticket # 30650
