### ISSUE TITLE
[FE] My VA - Treat 404 from appeals API as no data state

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#23417]
It's possible to get the following response from the `GET appeals/` API:

```json
{
  "errors": [
    {
      "title": "Not found",
      "detail": "Appeals data for a veteran with that SSN was not found",
      "code": "CASEFLOWSTATUS404",
      "source": "Appeals Caseflow",
      "status": "404"
    }
  ]
}
```

**We are currently treating that as an error, but we need to treat it as though the user has an empty array of appeals.** Because we treat it as an error, we show an alert in place of the Claims and Appeals section, which we do not want to do.

Staging users 2 and 36 both get this response from the API. And I've discovered this likely happens to A LOT of users because it's possible for people who have never filed an appeal to have the `"appeals-status"` listed in their available services. My own account on prod has the `"appeals-status"` service.

FWIW, the current My VA Dashboard does not show an error when it gets a 404 from the `GET appeals` API.

**Comment by erikphansen** [comment]
This should be available on staging to validate. Users 2 and 36 should no longer see an error in the Claims and Appeals section.

**Comment by ajakabcin** [comment]
Confirmed on staging - closing
