### ISSUE TITLE
508-defect-3 [COGNITION]: Link text should make sense when taken out of context in the disconnect alert on connected apps

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#23436]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader user, I want to be able to understand the purpose and target of a link by listening to the link text alone.

## Details

Screen reader users may navigate by links alone using AT. When links are presented as one long list, it helps to have both the purpose and context included within the link text. 

Instead of just "privacy policy", the link should include the full context "review the ThoughtWorksGacek-2021-04-06T20:15:44.531Z privacy policy."

## Acceptance Criteria

- [ ] Link text includes "review the --- privacy policy."

## Steps to Recreate

User 36, connected apps page, disconnect a service

## Proposed Solution

Include "review the ThoughtWorksGacek-2021-04-06T20:15:44.531Z privacy policy." in the "privacy policy" link

## Screenshots or Trace Logs

<img width="1081" alt="Screen Shot 2021-04-19 at 12 35 57 PM" src="https://user-images.githubusercontent.com/14154792/115271925-d9757d80-a10b-11eb-899b-7567dde209e6.png">

**Comment by ajakabcin** [comment]
hey @joshkimux or @AngelaFowler82 could one you take a look at this for us? Thanks again in advance!

**Comment by joshkimux** [comment]
@ajakabcin I'm trying to verify now but profile is not loading for some reason
<img width="1156" alt="Screen Shot 2021-07-14 at 10 45 05 AM" src="https://user-images.githubusercontent.com/14154792/125642169-36652073-47de-4077-94e3-41a60fb2e174.png">

**Comment by joshkimux** [comment]
<img width="760" alt="Screen Shot 2021-07-14 at 10 59 31 AM" src="https://user-images.githubusercontent.com/14154792/125644695-0e28ca7f-9e8c-407e-9124-b67a8f4a1148.png">
Confirming this has been fixed 🥳
