### ISSUE TITLE
PagerDuty - Add account for Cameron Testerman 

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#23438]
Cameron needs to be added to be-tools [support rotation](https://dsva.pagerduty.com/schedules#PPGUD8L). I can't add him there as he's not in Pager Duty.

He'll also need to be added to the on call rotation.

**Comment by jhouse-solvd** [comment]
@ericboehs - When is @camerontesterman's upcoming support rotation? Just to make sure we are timely with the request.

**Comment by ericboehs** [comment]
@jhouse-solvd in two sprints (4 weeks).

**Comment by jhouse-solvd** [comment]
@ericboehs - I believe Cameron got added to PagerDuty, but it looks like we didn't follow up properly on this ticket. Can you please validate and close with a comment if this is good to go?

**Comment by cbtkc** [comment]
I am in pager duty now.

**Comment by dginther** [comment]
Verified that Cameron has a user in PD
