### ISSUE TITLE
0994: Add "I certify" statement to Review Application chapter

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23442]
As an EDU application processor, I need VET TEC applicants to certify that the information that I have provided as part of the application is true to the best of my knowledge and that I have contacted my ESO if currently on active duty, so that the application is consistent with the paper form and compliant with legislation.

## Assumptions:
1. This work is completed behind a prod flag.
2. This content is to be included on all EDU forms; consider the reusability when implementing.

## Acceptance Criteria:
1. If the answer to the question "Are you on full-time duty in the Armed Forces? (This doesn't include active-duty training for Reserve and National Guard members.)" is "Yes", the following content is displayed in the Review Application Chapter:

    > 	**By submitting this form** you certify that:
    > 		• All statements in this application are true and correct to the best of your knowledge and belief
    > 		• As an active-duty service member, you have consulted with an Education Service Officer (ESO) regarding your education program

2. If the answer to the question "Are you on full-time duty in the Armed Forces? (This doesn't include active-duty training for Reserve and National Guard members.)" is "No", the following content is displayed in the Review Application Chapter:

    > 	**By submitting this form** you certify that all statements in this application are true and correct to the best of your knowledge and belief.

## Supporting Artifacts:
1. Prototype
    a. [AC 1](https://bahdigital.invisionapp.com/d/main#/console/14222606/296058971/preview)
    b. [AC 2](https://bahdigital.invisionapp.com/d/main#/console/14222606/296058983/preview)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/51ad2a8b77f0fa90db9b7e7aafdf5f8e1152bd02/products/education-careers/application/vettec-0994/design/0994-content.md#chapter-title-step-7-of-7-review-application)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16937

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-04-27 at 1.41.01 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5fe91b67-fdff-4784-9f58-6390bc5e283c)
##
![Screen Shot 2021-04-27 at 1.23.00 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a85065b2-ce17-4b4d-b164-7a3523e34cef)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1773&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah this is ready

**Comment by JenLJ** [comment]
UX Review 1/2: This checks out for me

**Comment by amyknox** [comment]
UX Review 2/2: Good news & bad news.

**Good news:** it works as expected & meets AC. Nice!
**Bad news:** there's a typo in AC.  Correct phrasing for confirmation is "active-duty service member"  We need to update this before pushing this to production.

**Comment by dneel-bah** [comment]
The AC matched the requested content at the time of story creation.  @elder-joseph @sonntag-adam @delli-gatti-michael I can create a new story or include the updates in this one.  Which would you prefer?

**Comment by dneel-bah** [comment]
The content has changed since the acceptance of this story.  After discussion with the team, the changes have been agreed to be made as part of this story.  Here is the [content doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d3439bca3dcd14cf829c36c913ed4b973bdec138/products/education-careers/application/vettec-0994/design/0994-content.md) with the requested change.

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-04-30 at 8.03.37 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1029f2c4-8cf9-455b-a46d-a83fc035469c)

Fixed. Closing story.
