### ISSUE TITLE
Update navigation bar icons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23440]
## Acceptance Criteria
1. Update the buttons on the bottom navigation bar with the latest .svgs
     - Include selected/unselected states for Home/Claims/Health/Profile

Note: this is a known change to the recent nav bar update the FE team did as part of #21038 and #22708

Related bug for alignment issues: #23291

## Assets
Nav bar .svgs: https://drive.google.com/drive/folders/1ivveptpfPJ6dI0XzItcpub3f-RZsd0kK

**Comment by digitalken** [comment]
Added to TestRail.   When testing, retest bug #23291.
