### ISSUE TITLE
0994: Remove "I certify" prod flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23443]
As a developer, I need to remove the prod flag created for #23442 so that the new functionality is available in production.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of 2021-04-30.

## Acceptance Criteria
1. The functionality created in #23442 is available in production.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17064

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are live on prod. Closing this issue
