### ISSUE TITLE
User Survey Request for [VA.gov Virtual Agent team]

### ISSUE THREAD

**Issue by LucianaAlexanderMorais** [department-of-veterans-affairs/va.gov-team#23457]
# Request the Feedback Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product. 

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md)

## Description
Requesting Medallia for the virtual agent/chatbot project. We are rolling a Proof of Value concept that will reside on staging.va.gov/virtual-agent/ and will be accessible via feature-flag invitation either on a banner at Va.gov landing and/or as a feature-flag on the Contact Us page. 

Veterans will be able to ask questions directly to the bot. Those questions will then be analyzed by the virtual-agent team to understand topic areas, usage times, etc. We will place disclaimer text to the right of the virtual agent that addresses prototype questions etc, as well as an invitation to the Medallia survey. We would like to place the Medallia floating feedback button there as well. 

The goal is to use Medallia as is to collect feedback on the chatbot. 

### Launch Date
June 1st, 2021. Page will close EOD June 30th, 2021

### Staging URLs
staging.va.gov/virtual-agent

### Production URLs
No production links at this time. We will use staging.va.gov/virtual-agent. 
![page](https://user-images.githubusercontent.com/72036779/115296738-5400c600-a129-11eb-9c55-a20ab77d65ce.png)

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by jwoodman5** [comment]
Hi @LucianaAlexanderMorais. Thanks for submitting this request. Can you please confirm if you want the survey _only_ on staging.va.gov/virtual-agent or if there are other pages in that directory that need it as well? Thanks.

**Comment by shefalinayak** [comment]
We only have one page for our app, so staging.va.gov/virtual-agent is it.

Our app is in development and not yet in the production build of the website. Will we have to repeat these steps for www.va.gov/virtual-agent once we're in prod?

**Comment by jwoodman5** [comment]
@shefalinayak Hi there - Thank you for that confirmation. We will get this up on staging for you. I will note that here in the ticket once it is up and we will leave this ticket in our backlog so once you're in prod, you can comment here and we can add the survey based on that info from this ticket. That way you won't need to create a separate ticket. Sound good?

**Comment by shefalinayak** [comment]
@jwoodman5 That works. Thanks!

**Comment by katieho-va** [comment]
@jwoodman5 We see it in staging now, thank you! How do we get access to the data?

**Comment by jwoodman5** [comment]
Hi @katieho-va - The analytics team is working on ingesting the data into BigQuery-DOMO, which will be the only way for users to view survey data. This path was a decision made by USDS when they adopted Medallia. So, in the meantime before DOMO is ready, please let me know what you need and I'll work on getting it straight from Medallia. I know this may not be ideal, but hope it will help.

**Comment by jwoodman5** [comment]
As confirmed, we are now live in staging. This ticket will remain in the backlog until ready for production rollout.

**Comment by jwoodman5** [comment]
We received a request to remove this Feedback button/survey from the staging URL listed and it was completed on 5/25.

**Comment by ianpsant** [comment]
@jwoodman5 Per our discussion, we'll be launching the chatbot into production in February and in preparation we wanted to re-add Medallia to our staging environment (https://staging.va.gov/virtual-agent-study/). Once we know the production URL we'll update this ticket with that info as well.

**Comment by jwoodman5** [comment]
@ianpsant I put the request in to the Medallia technical team and will let you know what it is live.

**Comment by jwoodman5** [comment]
Hi @ianpsant. The Medallia Feedback Survey is now live on your staging page linked above. Please have a look and let me know if you have any questions. If you don't see it at first, you may need to hard refresh/cache clear. Have a good weekend.
