### ISSUE TITLE
Prep Tasks for Research: Baseline Wayfinding Research on VA.gov

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23453]
## Issue Description
_Tasks needed in support of upcoming research project_

## Preparatory tasks
- [x] Share research plan and conversation guide with Lauren Alexanderson for approval and recruiting
- [x] Make note-taking spreadsheet
- [x] Schedule pilots
- [x] Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [x] Run pilots
- [x] Debrief pilots 
- [x] Revise conversation guide
- [x] Send instructions to observers
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [x] Schedule team debrief sessions once a day
- [x] Followup with Perigean re participant list
- [x] Other tasks as needed 

## Acceptance Criteria (AC)
- [ ] All set to start research sessions

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cindymerrill** [comment]
Scheduled first pilot for Wed 4/21 with someone at Ad Hoc who uses a screen reader

**Comment by cindymerrill** [comment]
Scheduled second pilot for Thu 4/22 with a Veteran. Created notetaking spreadsheet. Updated conversation guide per navigation of VA.gov by phone.

**Comment by cindymerrill** [comment]
Run pilot #1, revised conversation guide and notetaking spreadsheet. Ready for pilot #2 tomorrow.

**Comment by cindymerrill** [comment]
Ran pilot #2, revised conversation guide (removed last 2 tasks) and note-taking spreadsheet. Research sessions getting scheduled for next week.

**Comment by cindymerrill** [comment]
All ready and excited for research sessions to begin on Monday April 26!
