### ISSUE TITLE
VRRAP: Set configuration prod status to true

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23451]
As a developer, I need to set the prod status of the VRRAP application to true so that the application is available in the production environment.

## Assumptions:
1. This functionality has been signed off on EDU as of 2020-04-20.

## Acceptance Criteria
1. The 22-1990S (VRRAP) application is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16861

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16882

**Comment by sonntag-adam** [comment]
Closing story.
