### ISSUE TITLE
[DISCOVERY] PPMS API token change

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23456]
## Issue Description
Discovery effort for recently announced API change

![image](https://user-images.githubusercontent.com/55411834/115295224-be5c3b00-a116-11eb-8114-55066bb084c4.png)

---
## Tasks
- [ ] Document questions 

## Acceptance Criteria
- [ ] Issue with tasks and dependencies is ready for grooming

**Comment by darkbushido** [comment]
The PR is up, I still need to work with OPS to update the secrets we use in staging
We still haven't received the production keys.
