### ISSUE TITLE
[SPIKE] Facility vaccine phone number & URL

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23469]
## Description
Lighthouse is adding fields for a vaccine scheduling-specific phone number for a facility and a local URL for COVID-19 vaccines. Facility Locator will return this phone number for vaccine facility searches (#23095).

Lighthouse updates - see facilities ticket for details.

### Questions
- Is the facility vaccine scheduling phone number available for VAOS to use?
  - What is the field name?
- Is the facility local vaccine page URL available for VAOS to use?
  - What is the field name?
- Is VAOS BE work required to make fields available to FE or are they passing through?

## Tasks
- [ ] Document answers to above questions
- [ ] Create VAOS BE tickets and note dependencies, if necessary

**Comment by ajmagdub** [comment]
Currently when VAOS pulls facility information it does not retrieve that info from Lighthouse but from VAMF. The Facility vaccine phone number and URL is not available. 

There is a Vets API module, facilities_api, that does pull the Facilities information from Lighthouse and the CovidVaccine::V0::FacilitiesController does call that endpoint but does not pass through those new fields. 

New Vets API work would need to be done to pass through those new fields.  

The fields are found in the detailed_services attribute. The phone number is found in the detailed_services->appointment_phones -> number attribute; and the URL is found in the detailed_services->path attribute.

Work would need to be done on the facilities_api module to expose the new fields and then the VAOS front end can call the new endpoint. A Vets API ticket is needed, but I'm not sure if it should be a VAOS ticket or some other groups ticket.

**Comment by ajmagdub** [comment]
Another approach is create another VAOS route to return facilities using the Lighthouse::Facilities::Client to access the new fields
