### ISSUE TITLE
[FE] My VA: Implement an error when we cannot connect to MPI 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23464]
## Background
As noted in #22656 there may be instances when we cannot connect to MPI and we need to have a way to indicate this error to the user

## Tasks
- [ ] Implement error handling when we cannot connect to MPI using the copy and screenshots indicated below

**We can't access any health care, claims, or appeals information right now**

We’re sorry. Something went wrong when we tried to connect to your records. Please refresh or try again later.

## Screenshot
<img width="667" alt="23464 cannot connect to MPI error message" src="https://user-images.githubusercontent.com/45603961/115428522-7863ad80-a1d0-11eb-9796-e45b112e1f2b.png">

**Comment by ajakabcin** [comment]
Updated screenshot TK

**Comment by erikphansen** [comment]
I just merged a PR for this one. Again, I don't think it's easy to validate in staging, so feel free to close it, @ajakabcin
