### ISSUE TITLE
[FE] Profile: Remove the word "veteran" from copy in existing Profile error

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23468]
## Background
As noted in #22656 we need to remove the word "veteran" from the alerts that appear when 

1. We can't connect to MPI/MVI
2. We can connect to MPI/MVI but the user does not exist in MPI/MVI

## Task

- [ ] Remove the word "veteran" in the headline and body of the alert for when we can't connect to MPI
- [ ] Remove the word "veteran" in the headline of the alert for when we can connect to MPI but the user does not exist in MPI

## Screenshots
Remove the word Veteran in headline and body of the alert:
![image](https://user-images.githubusercontent.com/45603961/115886383-dc7bb100-a41e-11eb-84ce-9bace16c5780.png)

Remove the word Veteran in the headline of the alert:
![image](https://user-images.githubusercontent.com/45603961/115886443-ee5d5400-a41e-11eb-8f08-c0206d8a7672.png)

**Comment by erikphansen** [comment]
@ajakabcin Just to make sure I've got this right.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/22656 outlines the error alerts for My VA. One error for when we cannot connect to MPI. A different error for when we cannot find the user in MPI.

This ticket, 23468, is to remove "veteran" from the existing errors we are currently using on the Profile. Is that right?

**Comment by tressaellen** [comment]
@erikphansen @ajakabcin I verified with VSP - the alert should be yellow, so we'll go with that. 

I also reached out to copy to make sure that we're good to go there - but in the mean time I've also updated what's outlined in the ticket to reflect what's shown in profile (with a few changes). I'll update here when I hear back. Thank you!

**Comment by erikphansen** [comment]
@ajakabcin gah! You totally changed the scope of this ticket which I had already linked this merged PR to https://github.com/department-of-veterans-affairs/vets-website/issues/16902

**Comment by erikphansen** [comment]
The original scope of this ticket, to update the two different MPI errors that appear on the Profile, is on staging. But I don't think there is an easy way to validate it without faking MPI errors from the API.

**Comment by bethpottsVADEPO** [comment]
@tressaellen Do you have all the feedback you need from me? I do notice in the above yellow alert that we use both "match your information **to** our records" in the header and then "match your information **with** our records" in the body copy. Can you change the header to "with"--which will match the other alert we were working on as well?

**Comment by ajakabcin** [comment]
Apologies for the confusion, I've reverted this issue back to what it was originally to correct the copy in the existing MPI/MVI alert in Profile.

**Comment by erikphansen** [comment]
@ajakabcin feel free to close this. I don't think there is an easy way for you to validate it in staging since it's an error message.
