### ISSUE TITLE
Adjust spacing between text and logo on loading screens

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#23463]
## Acceptance Criteria
1. Add 50px of spacing between logo and text on all app loading/sync screens 

### Screenshot
![Group 3.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/68e55ef2-4d8d-462c-a2c1-4896b1bc03e4)

### Background
To meet VA brand guidelines, we want to add some spacing between the VA logo used on the loading screens and the text that appears underneath. Space should be, according to guidelines, at least half the height of the logo mark. To stay away from any dynamic spacing which we think will be time-intensive for MVP, we want to have 50px of space, knowing that should meet this requirement across mobile devices.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/10/2021 - Looks good, extra space on Android and iOS.  Closing.

**Comment by digitalken** [comment]
PASS 5/10/2021 - Looks good, extra space on Android and iOS.  Closing.
