### ISSUE TITLE
Analytics Implementation or QA Support for [Public Website - CLP/Trust]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23471]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
_This Request is for Google Analytics implementation and acquisition of UTM for URL: www.va.gov/trust.  Please reference ticket [#23304](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23304) for complete details.  

- Who is this request for?

    - [Public Websites - Campaign Landing Page]
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
Public Websites team is requesting on behalf of:

Requestor name: Tim Hudak
VA organization: VEO
Email address: timothy.hudak@va.gov
About the Campaign

Name or focus of Campaign: Trust
Target audience(s) [up to 3]:
Veterans
VSOs
Congress
Goals of the Campaign:
Increase transparency, accountability. Demonstrate VA’s commitment to listening to the voice of the Veteran by displaying VA trust scores publicly.
Campaign start and end dates:
April 29th, 2021
Campaign page target launch date:
April 28th, 2021
Preferred URL:
www.va.gov/trust
What will you to drive awareness of this Campaign and this page?
Social media, #VetResources, VSO and Congressional engagements
What metrics will you want to know to measure success of the Campaign landing page?
visitors / new visitors
    
- Provide the Domain where Google Analytics needs to be implemented
     - www.va.gov/trust
    
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
Campaign start and end dates:
April 29th, 2021
Campaign page target launch date:
April 28th, 2021

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - www.va.gov/trust
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - Page Visits
    - CTA Interactions 
    - PDF Downloads 
    - Link clicks in "Events", "Stories"
    - "VA Benefits" section links
    - Scroll Depth 
    - Bounce Rate 

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - None

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - None

- Certain conditions/responses that need to be reviewed

    - None

- Additional Comments

    - This is a new CLP, please reference [#16749](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16749) for CLP data layer connections that have already been implemented / supported.  Please reach out to our team with any questions as this is our first CLP stakeholder kickoff and want to learn and improve on this experience in an effort to streamline efforts going forward.  

> Please leave the following blank

## Acceptance Criteria
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups
- [x] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [x] All appropriate issue tagging is completed
- [x] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by jonwehausen** [comment]
Hi @brianalloyd , 

Thank you for your request here. 

Please check out our documentation [here ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b01cd996bf4b907c9ba2f494e6e20ca14bfb3e57/teams/vsp/teams/insights-analytics/va.gov-utm-campaign-tracker.xlsx) that contains an excel workbook for creating your own UTM campaign URLs for VA.gov. You should be able to download a copy for yourself in creating your own links. For further documentation, you can check out Google's docs [here](https://support.google.com/analytics/answer/1033863).

A couple further things to note here: 

- Please be sure to review the conventions on the "Lookup UTM_Medium" and "Lookup UTM_Source" worksheets to determine what conventions to best use here. 
- The URL that is created in column P are is the URL that you will inherently want to use at your different touchpoints/user entry ways. If you wish, you can take that URL and put it into a URL shortener, and use that URL are your different touchpoints. 

If you would like us to review your final URLs following creation we can certainly do that. 

Thanks and let us know any further questions you may have here.

**Comment by jonwehausen** [comment]
In terms of the other site interactions you included -- if www.va.gov/trust is going to be a CLP, we can continue to QA those with @bsmartin-ep's work on #16749

**Comment by johnhashva** [comment]
@jonwehausen + @brianalloyd re: UTM ... seems to me the right/appropriate process for specifying these Link URLs is to:

**Comment by jonwehausen** [comment]
### Next Steps
- @bsmartin-ep I'm handing off to you to to execute QA when staging.va.gov/veterans-trust-va becomes available
- No GTM changes and/or data layer changes should be necessary

**Comment by jonwehausen** [comment]
@brianalloyd and/or @johnhashva Would you all be able to provide a ballpark estimate of when `/veterans-trust-va` will be live in staging? Thanks so much

**Comment by brianalloyd** [comment]
@jonwehausen due to some delays CLP/Trust will likely not be on staging environment until Monday or Tuesday of next week. CC @johnhashva who will be the publishing authority for this campaign who might have more up to date details.

**Comment by brianalloyd** [comment]
@jonwehausen @bsmartin-ep CLP is now live https://www.va.gov/initiatives/veteran-trust-in-va/ and looking to finalize QA process along with a small impact dashboard as mentioned above in order to share with the stakeholder in terms of progress of CLP.  Please reach out if you have any questions and thanks again for the support.

**Comment by joanneesteban** [comment]
Thanks, @brianalloyd ! Jon is no longer on the VA, so @bsmartin-ep will be helping QA.

**Comment by bsmartin-ep** [comment]
@brianalloyd - As discussed on Slack, here's a basic Dashboard showing how to filter widgets by Page URL...

https://analytics.google.com/analytics/web/template?uid=7upyOw24TmibU2eGiVk87A

Let me know what URLs to enable Scroll Depth Tracking.

Thanks!

**Comment by brianalloyd** [comment]
Thanks for the support @bsmartin-ep see below for URL to enable scroll depth tracking:
Current URL  |  Redirect URLs 
---  |  ---
https://www.va.gov/initiatives/veteran-trust-in-va | https://www.va.gov/trust 
https://www.va.gov/initiatives/veteran-Trust-in-va | https://www.va.gov/Trust

**Comment by bsmartin-ep** [comment]
Apologies @brianalloyd - we neglected to tell you this was deployed:

[Link to GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.rowCount=100&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22PT%22,%22trust%22,0%5D%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Scroll%20Depth&explorer-table-dataTable.sortColumnName=analytics.totalEvents&explorer-table-dataTable.sortDescending=false)

**Comment by joanneesteban** [comment]
@brianalloyd Hi! Do you need any other support? Can we close out this ticket?

**Comment by brianalloyd** [comment]
Hi @joanneesteban sorry for the delay, we can close this ticket out.  Thanks for the support and assistance.
