### ISSUE TITLE
Integration | Compose Message fields + loading screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23474]
## User story
As a user, I want to see a loading screen that the Compose Message form is loading with the predetermined Recipient list. 

**Note:** If we decide to display the user's signature (part of the SM Preferences work) on this form page, we'll also need to make the relevant call so that this info displays on the form.
 
## Acceptance Criteria
1. Selecting the "Compose a Message" toolbar button will make a call to the recipient (?) endpoint
     - When the form loads, the user's list of recipients should be pre-filled in the "To" dropdown
2. While the Compose Message form page loads, display a loading screen in the interim
     - Pull in loading spinner CC

## Designs
Similar design:
![Image from iOS (35).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/390b7b19-ff95-44dd-be5b-f008567a816c)

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
PASS 4/26/2021 - Looks good on Android and iOS.  Get the list and spinner.  Closing.
