### ISSUE TITLE
Add total # of records to pagination CC

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23472]
Blocked: not yet supported in the backend

## Acceptance Criteria
1. Update the pagination CC to display the total number of records for each list
2. Copy between the buttons: "[Variable label] #A to #B of #C"
     - #C = total number of records _(#A & #B are already built out)_
3. Implement this across all pages that display the pagination CC (revisit this list depending on when this ticket gets implemented):
     - Appts
     - Claims/Appeals
     - Secure Messaging lists
4. Update ReadMe w/ latest specs for the CC
5. Update it so use pagination metaData instead of the links data to track first and last page

## Designs 
https://adhoc.invisionapp.com/share/YM10HVPXJE7V#/screens/447364845_Inbox

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 4/30/2021 - Looks good on Appts.  Will verify on Claims/appeals and secures message when available.  Closing.
