### ISSUE TITLE
Create unit test for card component

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2347]
## Story
As an engineer I want to create unit test to ensure that components do not introduce bugs.

## Tasks
- Create unit test for card components

## Definition of Done
- [x] Unit tests cover all new functionality in the new component
- [x] New functionality has been submitted for code review and merged into master.

**Comment by micahchiang** [comment]
Since this work is closely related to the work in #2346, it will be completed on the same branch to avoid future build failures.

**Comment by micahchiang** [comment]
Completed and merged via https://github.com/department-of-veterans-affairs/vets-website/pull/10908
