### ISSUE TITLE
[Design] Home page thumbnail card A11Y and layout improvements

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#23473]
This addresses changes to the home page refresh thumbnail card:
* Collab cycle feedback that the carat is not enough of a clickability indicator on mobile (See [A11Y review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18583#issuecomment-764018272) and [design review](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/18587) ) - this displays the "details" text on mobile to address that.
* Rounded borders not using standard border-radius
* Updates the "canceled" status label style to use the tag component
* Styles for active, hover, and focus states

**Design specs**
https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/JnPpm4M#Inspector

**Comment by laurenernest** [comment]
Dev ticket created for these changes #23478
