### ISSUE TITLE
0994: Remove prod flag for direct deposit update

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23486]
As a developer, I need to remove the prod flag created for #23485 so that the new functionality is available in production.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of [TBD].

## Acceptance Criteria
1. The functionality created in #23485  is available in production.

## Supporting Artifacts:
1. N/A

**Comment by daltonatkins** [comment]
Not applicable
