### ISSUE TITLE
Access for Jeremy Britt

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#2348]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Jeremy Britt
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Oddball - VSP Operations - DevOps Engineer
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYwydwEUHgGO2nXwtwA+uO0gv9OtmdBqErHGU5lQg8EBSgZCFF+GvsgOJYqzVHzRTnGG/LchtfzshEA1xUgfurexFpFoPLOaiNTojmqI32SJUEenbAHk1bgWhPLkWd5ATgfvV0Tr7KOlU9Z99QjxUX/uHPsy1dEfYECL/PIY44lu92bC5IJkP57FHRHt1L33DOEiataECEQuoD9DceI2vn3dg9oBYxLTQXISyKe6dNocXnPgAvRBwFVV3A7O36X8uWSLP3ls3MEJxBGIEqMqe5UgRrL4bxZ118GHS6h05gWXz1UC8gR3sSzHMJWAy59SmrTNy0Bso7zUJB2ydrxwuV Jeremy@BattleStation1

- [Grant AWS Console access?]
  > YES

# Label
 > Operations

# Mentions
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter
COR: Yourself
User: Jeremy Britt

**Comment by Jeff-Hayter** [comment]
@ricetj SAC confirmed, please grant SOCKS access.

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for AWS.

**Comment by andreahewitt-odd** [comment]
Eqip confirmed 11/15/23
