### ISSUE TITLE
Update offboarding to include flipper access removal

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#23483]
## Issue Description
It was recently discovered that the flipper admin list was outdated and included personnel who have left the platform. The offboarding docs should be updated to include removal of flipper admin access once folks leave the platform. 

We may also want to ask folks to use their company email credentials when possible vs their personal email. It makes it difficult to know who the person is and which company they work for.

[vets-api Flipper Settings](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml#L664)

We may also want to break apart this list into Ops, VFS teams, FE, BE, VA, etc
---

**Comment by jeff2d2** [comment]
May not be needed if #23571 is successful and flipper access is managed as a sub-group of `vets.gov-write`
