### ISSUE TITLE
IA Request: Find & View Representative (eBenefits)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23490]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kick-off ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

Link to or attach user flows: https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/dlG4Y22
Link to prototype or mockups: https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/PGJ3ZlP
Link to any epics/issues that may be helpful: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3672

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?
- Feels like working with representatives have so much applicability this might be a root feature _OR_
- It could be found somewhere on the benefits page (https://www.va.gov/service-member-benefits/) 
- Legacy pages seem to use a lot of benefits.va.gov and eBenefits

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?
rep  
representative  
attorney  
power of attorney  
legal  

**URL(s)** - What are your suggested URLs and why?
- https://www.va.gov/ -- seems like a candidate
- https://www.va.gov/service-member-benefits/ -- previously found at benefits.va.gov and eBenefits

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  
- https://www.va.gov/ -- seems like a candidate
- https://www.va.gov/service-member-benefits/ -- previously found at benefits.va.gov and eBenefits

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
- Claim Status Tool

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?  
- EBN features

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by candy-gcio** [comment]
Hi, @mnorthuis, I haven't updated the breadcrumbs yet (or looked at your open questions much yet), but I have updated the workflow and updated the tool pages. 
- [workflow](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/L0d9ndD)
- [v2 wireframes](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/p/47673127-1304-4E6D-8CBE-C8A160E00A55)

**Comment by mnorthuis** [comment]
@candy-gcio wanted to check in on this work to see if you have answers to my questions above and make sure we are in sync on the page structure and flow.  Is this work still tabled, or is it progressing?

**Comment by candy-gcio** [comment]
We just brought a task into the sprint to sync up with you on this and talk with the owners of the pages you called out.

1. The H1s are updated in the [wireframes](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/p/47673127-1304-4E6D-8CBE-C8A160E00A55) and have been reviewed by Beth. 
2. I think Education is the only other benefit we need to connect to.
3. I'm not sure... @jason-gcio, does this (`What approval do we need to retire the "Get help" page in decision reviews?`) sound like something that would go to Melissa Rebstock or Nathan Kroes?

**Comment by sporeboy** [comment]
The prototype is available with click-through functionality only. The are two flows:
- [Authenticated (UXPin link)](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145482056)
- [Unauthenticated (UXPin link)](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145370991)

View representative has two iterations:
- [Points to EBN to change (UXPin link)](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145530300)
- [Points to VA.gov to change (UXPin link)](https://preview.uxpin.com/ff9dda3348ca1caa09500613a08dbe3fa512da5a#/pages/145522615)

**Comment by mnorthuis** [comment]
@jason-gcio @candy-gcio @sporeboy IA design is complete for this work and documented here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-representative.md

Please let me know if you have any questions.  You can close this issue when you have the information you need.  

cc @bethpottsVADEPO @RLHecht
