### ISSUE TITLE
Collaboration Cycle Kickoff [Public Website, Campaign Landing Page / Truth (VEO)]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23495]
## Steps to complete Collaboration Cycle Kickoff
- [X] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [X] VFS: Answer the questions below.
- [X] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [X] VFS: Attach any available artifacts.
- [x] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
Description
As part of VA.gov's Campaign Landing Page MVP Production phase, the Veterans Experience Office (VEO) wants to launch a CLP in support of a communications initiative to create more Veteran, public and Congressional awareness about VA's improved services and value delivery as represented by Trust Scores.

Key Info
Who is Requesting

Requestor name: Tim Hudak
VA organization: VEO
Email address: timothy.hudak@va.gov
About the Campaign

Name or focus of Campaign: Trust
Target audience(s) [up to 3]:
Veterans
VSOs
Congress
Goals of the Campaign:
Increase transparency, accountability. Demonstrate VA’s commitment to listening to the voice of the Veteran by displaying VA trust scores publicly.
Campaign start and end dates:
April 29th, 2021
Campaign page target launch date:
April 28th, 2021
Preferred URL:
www.va.gov/trust
What will you to drive awareness of this Campaign and this page?
Social media, #VetResources, VSO and Congressional engagements
What metrics will you want to know to measure success of the Campaign landing page?
visitors / new visitors
About Your Campaign Page Build

How familiar are you -- or the person who will build the campaign page -- with the VA.gov Drupal content management system enough to use the campaign page?
Very (Tim)
Who will build the campaign landing page in the VA.gov CMS?
Tim
Who will review and give approval to publish the page?
Tim
Who will update/maintain the landing page during the campaign?
Tim
At the end or your campaign, do you want to page to be retired/removed from VA.gov or preserved? If preserved, why?
It may be “retired” as it is replaced with a larger effort or a larger dashboard page.

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [  ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [X] New (CLP for VA Stakeholder)
- [ ] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [ ] Yes
- [X] No (CMS automated design elements)

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [ ] Yes
- [X] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work include content changes for: (Select all that apply)
- [ ] Tools and applications*
- [ ] Static pages
- [X] This work doesn’t involve content changes.

*For tools and applications, take into account if any content on static page entry points will need updates.

Content changes could include: updates to buttons, links, labels, headings, reordering content, or adding error messages.

### 6. Are you making a change to the user flow?
- [ ] Yes
- [X] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 7. Are you making a change to urls, navigation, or entry points?
- [X] Yes (Adding a new URL as requested for a CLP)
- [ ] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 8. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [X] Yes (Ticket already submitted)
- [ ] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 9. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X] Yes
- [ ] No

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @brianalloyd  Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is a new static content page so we are recommending the following Collaboration Cycle touchpoints: 

- Information Architecture (IA) Request
- Analytics Request (in progress [#23304](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23304))
- Staging Review (submitted [#23509](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23509)) 
- Privacy and Security Review
 
Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by brianalloyd** [comment]
Thanks you @shiragoodman for the quick response.  I'll spin up an IA request in support.

**Comment by brianalloyd** [comment]
Closing this ticket based on completion of defined tasks. Thanks all for the assistance.
