### ISSUE TITLE
Confirmation alert for Sign Out

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23498]
## User story
As a user, I want to see a confirmation alert that asks me to make sure that I want to log out of the mobile app. 

_Note for dev:_ refer to the Delete Contact Information flow for similar UX. 

## Acceptance Criteria
1. Selecting the "Sign Out" button on the Profile & Settings page does the following:
     - Large button disappears
     - Display mobile alert in place of the button
2. Mobile alert UI: 
     - Header 2: "Are you sure you want to sign out?"
     - Large Button (primary): Confirm
     - Large button (secondary): Cancel
3. "Confirm" button signs the user out of the mobile app
4. "Cancel" button removes the mobile alert and reinstates the "Sign Out" button on the screen

## Designs
https://adhoc.invisionapp.com/share/K910GW90XFQM#/screens/450038488

## Accessibility Implementation Guidelines

- Mark "Are you sure you want to sign out?" as Header 2

**Confirm button:**
accessibilityLabel= "Confirm"
accessibilityRole= "button"
accessibilityHint= "Sign out of the VA mobile app"

**Cancel button:**
accessibilityLabel= "Cancel"
accessibilityRole= "button"
accessibilityHint= "Cancel and remain signed into the VA mobile app"

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/6/2021 - Looks good on iOS and Android. Minor bug for lack of header being marked in accessibility and Samsun pronunciation of Vee A. (vah). Closing.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/24367
