### ISSUE TITLE
Search Reorganization Discussion 

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#23503]
After reviewing the search app, here are some potential improvements. I have broken them up into 2 categories based on their impact

### Low Impact (easy wins)
- [x] Reach out to search.gov about a health endpoint for search
- [x] (if a health endpoint exists) disable sitewide search / show a search is down message when a user attempts to search
- [x] (if a health endpoint exists) redirect to home page when a search is initiated / show a popup
- [x] Remove unnecessary abstraction for rendering results page
- [x] Add improved error tracking
- [x] Remove redirect to home page when an empty query is provided - instead redirect to resources and support >#23648

### Higher Impact (larger efforts)
- [x] Remove current downtime notification app, replace with a functioning one (current implementation just checks against scheduled downtime calendars, which we do not have for search)
- [x] Use improved error logging for more detailed messages when search has failed - can provide user with more accurate "what went wrong"
- [x] Consolidate all search event logging into a single function with an options parameter

**Comment by denisecoveyduc** [comment]
April 22nd the team discussed this breakdown and agreed that all improvements identified should be explored further. @srsuddath will categorize improvements into 3 buckets (Tech Debt, Monitoring/Analytics and User Flow) and outline which (if any) need to happen before any results page redesign work. Then we will establish issues and add estimates for future prioritization.

**Comment by srsuddath** [comment]
This discussion has been broken out into the following tickets:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/24116
https://github.com/department-of-veterans-affairs/va.gov-team/issues/24117
https://github.com/department-of-veterans-affairs/va.gov-team/issues/24118

**Comment by denisecoveyduc** [comment]
The above issues will be integrated into the roadmap along with work for the results page redesign/surfacing VA Search Tools
