### ISSUE TITLE
Implement on 4/22: Redirect Request needed for 2 R&S articles about direct deposit

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#23507]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
Now that changing direct deposit info for education will be handled the same as disability and pension, our step-by-step article [How to change direct deposit information for education benefits](https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-education-benefits/) will no longer be relevant. We will delete this from R&S but want to redirect it to the step-by-step article that is remaining [How to change direct deposit information for disability or pension](https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-disability-or-pension/). 

Also the H1 of the remaining step-by-step article is changing so we want to redirect the old URL to what the new one will be.

### Requesting team info
Sitewide content
@RLHecht 

### Implementation date
Date new URL(s) will be live: 4/21

Please indicate when the change/redirect(s) needs to be implemented" **April 22nd**
- [x] On the same date the new URLs launch
- [x] Can happen within 1-5 business days after new URLs launch
- [X] Other - Please indicate timing: April 22nd

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
/resources/how-to-change-direct-deposit-information-for-va-education-benefits/ | /resources/how-to-change-direct-deposit-information-for-va-benefits
/resources/how-to-change-direct-deposit-information-for-va-disability-or-pension/ | /resources/how-to-change-direct-deposit-information-for-va-benefits

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [ ] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [ ] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [ ] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by lunascoop** [comment]
@mnorthuis can you assign this directly to @brianalloyd or @kelsonic after you’ve vetted the URLs? Thanks!

**Comment by mnorthuis** [comment]
@bethpottsVADEPO Reviewed analytics and SEO data on these pages - they have significant traffic and SEO value, and have backlinks from external sites (woo hoo!) - this validates that a redirect is needed for a URL change to ensure these pages are properly served. 

This request is vetted and documented and ready to be implemented when you are ready.   Assigning to @brianalloyd for next steps.

**Comment by kelsonic** [comment]
@mnorthuis do you want these to be permanent or temporary redirects?

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/9024/

**Comment by mnorthuis** [comment]
> @mnorthuis do you want these to be permanent or temporary redirects?

Permanent please.  Always permanent, unless otherwise noted.  Thank you for checking!

**Comment by bethpottsVADEPO** [comment]
@RLHecht Want you to be the final "go" word on this--do we want this to happen today?

**Comment by RLHecht** [comment]
The URL has been changed and the education article is now archived so if we can do it today, all for it! @kelsonic

**Comment by kelsonic** [comment]
https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-education-benefits/
https://www.va.gov/resources/how-to-change-direct-deposit-information-for-va-disability-or-pension/

Give those a try! 😃 PR merged + deployed, ready for validation

**Comment by RLHecht** [comment]
Beautiful! Thanks, @kelsonic !
