### ISSUE TITLE
CT Redesign: Update Search Page in sandbox

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23514]
As a developer, I need to update the search page of the CT sandbox so that it matches the latest designs and can be used to build out the rest of the application.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The search functionality is out of scope of this story; this is strictly a UI update.

## Acceptance Criteria
1. The user has the ability to toggle between a name search and location search.
2. The "Search by name" is a free text search.
3. The "Search by location":
    a. Is a free text search
    b. Can be customized by the following distances: 10, 25, 50

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222610/296059003/preview)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16950

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
On staging. Closing this issue

**Comment by delli-gatti-michael** [comment]
[testrail test run](https://dsvavsp.testrail.io/index.php?/tests/view/137503&group_by=cases:section_id&group_order=asc&group_id=46)
