### ISSUE TITLE
CT Redesign: Create/Update sandbox free text search service

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23515]
As a developer, I need to update the free text search of the CT sandbox so that it searches all institution types and returns a comprehensive list of results.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The "Search by location" search functionality is out of scope of this story.
3. This search leverages the same weighting and fuzzy search capabilities as currently in production.  This should result in a search in the sandbox returning the same results as the vettec search + non vettec search in the current comparison tool.
4. The data points collected in AC2 are for use in future stories for display and/or filtering. Some of the listed data points are calculated values and may not be explicit columns on institution table.

## Acceptance Criteria
1. The “Search by name” free text searches all institution types (ex. schools, employers, training providers) by name.
    a. That match the production comparison tool free text search
    b. Are displayed using the production comparison tool non-vettec card pattern
    c. The "Search by name" criteria is an OR.  (Example: Galvanize has "school" locations and "training provider" locations.  All locations are included in a single set of search results).
2. The following data points are included:
    a. Institution Name
    b. Institution City
    c. Institution State
    d. Accreditation Type
    e. # GI Bill Students
    f. Institution Rating Score
    g. Number of Institution Ratings
    h. Institution Type
    i. Institution Country
    j. Institution Caution Flags
    k. Institution Has Student Veteran Group
    l. Institution Offers Yellow Ribbon Program
    m. School Type
    n. Degree Type Offered
    o. Is HBCU
    p. Is gender specific
    q. Is religion affiliated
    r. Preferred provider (VETTEC indicator)

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222610/296059003/preview)

**Comment by dneel-bah** [comment]
Removed AC3 and created a separate story: #24141

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/vets-website/pull/17074
- https://github.com/department-of-veterans-affairs/vets-api/pull/6763
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/815
