### ISSUE TITLE
Content Review for DD beta launch messaging for 10/15

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2351]
## Background 
Authenticated Experience team is looking to roll this out to the live content page before 10/16 when the eBenefits team has their release on 10/16. Ultimately our goal is to ramp up the % of users to 50% and between 10/16- 10/30 be fully ramped up to 100% of users. 

## User Story
If a user is unable to use the DD feature on the profile section of VA.gov, we want the user to be prompted with these message:

 "Currently, this feature is still in beta mode and not yet available to all users. If you do not see it in your profile,  please continue to use eBenefits for this service " or something of this sort. 

## Goal
We need a content/copy review for the content above to live on the content page at: https://.va.gov/change-direct-deposit/

## Definition of Done
- [x] Content team has reviewed and approved/provided suggested changes to the content. 
- [x] If changes are needed, content changes have been made

**Comment by peggygannon** [comment]
@Justin-Pickett @lkoenigsberg 
Please see below for suggested messaging for direct deposit beta. Let me know if you have any questions or want to discuss in person. I also have two questions: 

--I dropped in a URL for the eBenefits page, so please check if the one I added is correct?
--Does this message appear only on the profile page? or does it also need to appear on /change-direct-deposit/ ?

The direct deposit feature is in beta testing and isn’t available to everyone right now. If you don’t see this feature in your profile, please go to eBenefits to change your direct deposit information. 
[Go to eBenefits]( https://www.ebenefits.va.gov/ebenefits/about/feature?feature=direct-deposit-and-contact-information)

**Comment by lkoenigsberg** [comment]
This seems good but wondering why we wouldn't just make "go to eBenefits" in the copy a link rather then another text link?

**Comment by Justin-Pickett** [comment]
@peggygannon also, I was told to have the messaging convey that "if users have to go back to eBenefits, they will need to log back on."

And this is the link where users would need to go on to eBenefits to complete there direct deposit change  - https://www.ebenefits.va.gov/ebenefits/PCIU

**Comment by peggygannon** [comment]
@Justin-Pickett @lkoenigsberg Thank you for your feedback. What do you think of the below? URL has also been updated to the one Justin provided above. 

The direct deposit feature is in beta testing and isn’t available to everyone right now. If you don’t see this feature in your profile, please [sign in to eBenefits](https://www.ebenefits.va.gov/ebenefits/PCIU) to change your direct deposit information.

**Comment by Justin-Pickett** [comment]
@peggygannon I have no issues with the message above. Thank you.

**Comment by peggygannon** [comment]
@Justin-Pickett ok, great. How will this message appear on /profile/? will it be in an alert or some other component? I'm happy to look at this again once it's placed on the page.

**Comment by Justin-Pickett** [comment]
@peggygannon I am not sure how it will appear on the page. My understanding would be due to it being temporary, i think it should be placed on the page the easiest way it can be put on and removed. @erikphansen can you offer some input on how this messaging will be placed on the content page?

**Comment by erikphansen** [comment]
Are we talking about changing content on `/profile/` or on a static page that directs people to the Profile to update their direct deposit info?

**Comment by Justin-Pickett** [comment]
@erikphansen this will be for the static page that directs people to the profile to update their direct deposit info.  here - https://.va.gov/change-direct-deposit/

**Comment by Justin-Pickett** [comment]
@erikphansen and @peggygannon  I'm okay with either. My main goal is we do whatever is easiest for us to implement in the shortest amount of time to have it on the page. 

@lkoenigsberg or @Samara-Strauss  do you two have a specific preference if we use an alert box vs just static content for users to be informed about the direct deposit feature being in beta still?

**Comment by peggygannon** [comment]
@Justin-Pickett OK, thanks. I want to clarify that this should go on /change-direct-deposit/ and not /profile/? (above it says /profile/, so I want to double-check. 

If it's the /change-direct-deposit page, I can make the update on that page in drupal once it's decided *how* the message would appear.

**Comment by Justin-Pickett** [comment]
@peggygannon yes it should be on the /change-direct-deposit/ content page.

**Comment by Samara-Strauss** [comment]
@Justin-Pickett @lkoenigsberg @erikphansen @peggygannon This is something design should have been involved with from the beginning. In the future, please make sure @artistgreen or I am involved to approve the overall user experience of any page updates. Copy updates go beyond "just" the words on the page (though the words are critically important) — we need to make sure users see messaging at a point that makes sense in the flow, regardless of whether it is this flow or something else. The copy can not be separated from the design, and we should not be asking our copywriters to write copy agnostic of design.

That being said, I *think* I understand this flow as follows:

- User is on eBenefits. They are told to check out DD on VA.gov.
- Users are sent from eBenefits --> the direct deposit content page. It is here that we need to communicate the direct deposit feature is in beta.

So I'd like this to work something like this:

- Add copy within the "Disability compensation and pension benefit payments"
- Use h4 to announce the feature is in beta (though my guess is we won't use the word "beta" since that probably doesn't mean anything to users).
- Add some copy below the h4 to clarify. This should mention this feature is not available to anyone and that people can go to eBenefits if they don't see it in their profile.
- **Don't** change the dynamic prompt below that since that has four different scenarios we're prompting people with (sign in, verify your identity, set up 2FA, go to profile).

The copy that needs love from @peggygannon is outlined in red. Once the beta is over and we are rolled out 100%, we can just delete this copy.

![Direct deposit content page: Sign in prompt](https://user-images.githubusercontent.com/34068740/66666987-f29c9480-ec1f-11e9-880f-6e022a7be9f3.png)

**Comment by Justin-Pickett** [comment]
@Samara-Strauss thanks for the help!

**Comment by peggygannon** [comment]
@Justin-Pickett @lkoenigsberg @Samara-Strauss 

Hello, please see updated content message below. Let me know your thoughts. I provided 2 options for a header. We've used the term "beta testing" before on other VA.gov tools, so I feel comfortable using it here. But I provided another option if you want to avoid using that term. 

**The direct deposit feature is in beta testing on VA.gov**
OR 
**We're testing out the direct deposit feature on VA.gov**

We're in the process of bringing direct deposit to VA.gov. This feature isn't available to everyone right now. If you see the direct deposit feature in your profile, you can update your information from there. If you don’t see this feature in your profile, please [go to eBenefits and sign in to change your direct deposit information](https://www.ebenefits.va.gov/ebenefits/PCIU).

If we use "beta testing" in the header, we *could* provide some helper text explaining what that means. 

optional, helper link: 
What does beta testing mean? 
[drop down]
Beta testing means we're testing a new tool to make sure it’s working the way it should before we give all VA.gov users access to it.

**Comment by Justin-Pickett** [comment]
@peggygannon both work great for sure.  I think the best line to use is "We're testing out the direct deposit feature on VA.gov" , as I feel its pretty straight forward to the user to understand. It also keeps the user from needing to make an additional step in understanding what is going on with the feature during this beta phase. 

 @Samara-Strauss any objections to that?

**Comment by peggygannon** [comment]
@Justin-Pickett @Samara-Strauss OK, so it sounds like we'll go with this. 

**We're testing out the direct deposit feature on VA.gov**
We're in the process of bringing direct deposit to VA.gov. This feature isn't available to everyone right now. If you see the direct deposit feature in your profile, you can update your information from there. If you don’t see this feature in your profile, please [go to eBenefits and sign in to change your direct deposit information](https://www.ebenefits.va.gov/ebenefits/PCIU).

I can add this alert to the drupal page.

**Comment by Justin-Pickett** [comment]
This beta messaging is scheduled to  go live on 10/15 during 2pm EST daily deploy.

**Comment by Samara-Strauss** [comment]
@Justin-Pickett @peggygannon — sorry I missed this! With the day off yesterday, I'm just getting back to emails now.

I agree with Justin 100% and think we should go with the "We're testing out the direct deposit feature on VA.gov" heading. The rest of the copy looks great as well. Thank for adding it to the drupal page, @peggygannon!

**Comment by Justin-Pickett** [comment]
Content page has been updated and live with correct information. Closing this ticket.
