### ISSUE TITLE
Remove date-fns from MaintenanceBanner

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#23523]
## Background
A few things lead to this:
1. We use `date-fns` in the `MaintenanceBanner` component
2. This leads to using vanilla `Date` objects and `date-fns` in [maintenanceBanner.js](https://github.com/department-of-veterans-affairs/vets-website/blob/direct-deposit-review-fix-cv/src/platform/site-wide/banners/config/maintenanceBanner.js#L2)
3. That :point_up: module is included for the bundle on every page
    - I'm pretty sure this is true, but haven't traced it back yet
4. Whenever we use `date-fns`, we can't get Webpack to tree-shake the library properly, so the entire library is included rather than just the desired functions

The end result is that we're including the entire `date-fns` library on every page.

---
## Tasks
- [ ] Remove `date-fns` from the `MaintenanceBanner`

## Acceptance Criteria
- [ ] The `component-library` repo does not have `date-fns` or `date-fns-tz` ad dependencies

## Followup
- Update `maintenanceBanner.js` to not use `date-fns`

**Comment by k80bowman** [comment]
I'd like to see if we can remove date-fns entirely and rely only on native date functions.
