### ISSUE TITLE
NOD: Add unit tests & cleanup

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#23526]
@Mottie commented on [Tue Apr 20 2021](https://github.com/department-of-veterans-affairs/vets-website/issues/16869)

## Description

Finish up work on the Notice of Disagreement form.

## Tasks
- [ ] Code cleanup
- [ ] Add better code coverage (unit tests)
- [ ] Check accessibility
- [ ] Ensure form with mock data submits to endpoint after updates (see #16868)

## Acceptance criteria
- Tasks completed

**Comment by Mottie** [comment]
One PR left open - it's a form system change so will take longer to review.
