### ISSUE TITLE
[Carryover] Frontend: Update 10-10CG content for new form

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23527]
Open a PR to update the content in the 10-10CG based on any changes being made in April 2021

**Comment by Dene-human** [comment]
[Identified content changes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23613)

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17035) for this ticket

**Comment by ala-yna** [comment]
Hey Justin! I took a look through the PR and identified a couple of changes to make. You can see them here: https://docs.google.com/document/d/1MJaemi4cSI8AvNtzBwX4SlXT4ouUOGo4-KGE5YYcssA/edit#bookmark=id.3p7d1vfegxvz

There are 5. Please let me know if you have any questions!

cc @Dene-human
