### ISSUE TITLE
CT Redesign: Update styling of the institution search results card in sandbox

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23531]
As a developer, I need to update the CT sandbox search results card to match the redesign so that the changes are available for usability testing.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. Caution Flag indicator is out of scope for this story.
3. VETTEC Preferred Provider indicator is out of scope for this story.
4. The compare checkbox is out of scope of this story.

## Acceptance Criteria:
1. A card is displayed for each institution that is returned by the search results.
2. The following data is displayed in each card:
    a. Institution Name
    b. Institution City
    c. Institution State
    d. Accreditation Type
    e. # GI Bill Students
    f. Institution Rating Score
    g. Number of Institution Ratings
    h. Tuition Benefit
    i. Housing Benefit
3. The user has the ability to navigate from the card to the institution profile page.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/37IAGO4DHZG)
2. 
<img width="318" alt="Screen Shot 2021-04-20 at 3 34 46 PM" src="https://user-images.githubusercontent.com/48260534/115453987-47927100-a1ee-11eb-967b-dcb0c222c562.png">

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1818&group_by=cases:section_id&group_order=asc

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17118/
