### ISSUE TITLE
[Best Bet] Veteran Rapid Retraining Assistance Program

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#23533]
**Description**

The American Rescue Plan created a new education benefit for Veterans who've become unemployed due to COVID-19, Veteran Rapid Retraining Assistance Program (VRRAP).  

The VRRAP program runs for 21 months total - starting the date the American Rescue Plan was signed by Pres. Biden, March 11, 2021.

The application will launch 4/21-4/22.

Given the tight timeline and high level of interest in this application from the Sec. of VA, making the form easily accessible to Veterans is a high priority.  

We want to create a Best Bet to ensure Veterans seeking this new benefit have the easiest possible experience finding the application.

**To Be Done**
 Specify the headline and text for the Best Bet (@DanielleThierryUSDSVA or @bethpotts)

Headline:
Example: Learn if you're eligible for Veteran Rapid Retraining Assistance Program (VRRAP) and apply for the program.  

Text:
Example: VRRAP is a new education benefit for Veterans who are unemployed due to COVID-19.  VRRAP provides funding for eligible Veterans to get train in high-demand careers.

Specify the keywords that would generate the Best Bet
Examples: VRRAP, VRAP, retraining assistance, retraining program, 1990s, etc.(@DanielleThierryUSDSVA or @bethpotts)

Specify the URL for the Best Bet: (Static content page)
www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance

(Application intro page)
www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s

 Setup, test and validate the Best Bet in Production via the Search.gov dashboard (@johnhashva)

**Comment by johnhashva** [comment]
Thanks @amyknox .   Adding 

- @bethpotts (@bethpottsVADEPO ) for content team creation of the headline and description text for this Top Recommendation/Best Bet. 
- @denisecoveyduc since this ticket will also sit in the Search & Discovery team backlog for implementation after product is deployed in production.
-

**Comment by amyknox** [comment]
Thanks @johnhashva ! I was planning on fine-tuning this ticket but if the team is ready to work it - full speed ahead!

**Comment by johnhashva** [comment]
@amyknox strongly recommend you Slack @bethpotts and @RLHecht about this one in the #sitewide-content channel today to make them aware this one is easy/quick copy write/edit and you'd ideally like the Best Bet to go live in the next few days post-launch.

**Comment by amyknox** [comment]
@johnhashva I don't have access to #sitewide-content but can ping them in our education channel for awareness.  It's looking like the form will go live next week.

**Comment by denisecoveyduc** [comment]
@johnhashva I added this to our sprint 46 plan so we don't lose sight of it but sounds like things are moving along quickly. (Congrats @amyknox - great stuff!!) Once we get the copy from the content John will add it as a best bet. Keep me posted if you need anything else from our team :)

**Comment by bethpottsVADEPO** [comment]
@RLHecht Would you create a ticket for this and we'll take care of it this week?

**Comment by bethpottsVADEPO** [comment]
@johnhashva Where do you have documentation about standards for best bet blurbs--like character count, etc.? Or if there isn't documentation, want to just let me know right here any requirements/guidance I should be aware of?

**Comment by johnhashva** [comment]
No documentation re: standards and something from a content perspective that is sorely needed.   Indeed, there is a long standing ticket re: Best Bet strategy here https://github.com/department-of-veterans-affairs/va.gov-team/issues/9538).   For now, you can use the Disability Compensation Best Bet as a guide re: format, ideal length, etc.  https://www.va.gov/search/?query=disability

**Comment by bethpottsVADEPO** [comment]
@amyknox Here you go!

**Headline:**
Veteran Rapid Retraining Assistance Program (VRRAP)

**Text:**
If you're unemployed because of the COVID-19 pandemic, you may be able to get education or training for high-demand jobs. Find out if you're eligible for the Veteran Rapid Retraining Assistance Program (VRRAP).

**Comment by johnhashva** [comment]
Thanks @bethpotts -- @amyknox let me know when the new form is live.  I checked the URL -- and looks like not yet.

**Comment by bethpottsVADEPO** [comment]
The static page and the form are targeted for Friday deployment. @johnhashva FYI that there won't be a pdf version of this form, only online application.

**Comment by johnhashva** [comment]
Got it -- thanks @bethpotts.    (For record: looks like there is a related form for Educational entities that participate -- https://www.vba.va.gov/pubs/forms/VBA-22-10271-ARE.pdf)

**Comment by RLHecht** [comment]
@johnhashva Letting you know that the form is now live so the Best Bet is ready to go. Thanks!

**Comment by johnhashva** [comment]
<img width="713" alt="Screen Shot 2021-04-30 at 3 46 52 PM" src="https://user-images.githubusercontent.com/63107147/116747012-4ff76280-a9cb-11eb-8630-957bb1bed4db.png">
@bethpotts + @RLHecht + @amyknox this Best Bet is now live on VA.gov.

**Comment by denisecoveyduc** [comment]
Appears that this is live and working as expected. Closing this request out.
