### ISSUE TITLE
Add analytics events to va-accordion

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#23530]
## Issue Description
Add analytics events to the accordion web component.

---
## Acceptance Criteria
A `component-library-analytics` event is emitted when...
- [x] the accordion is opened
- [x] the accordion is closed

**Comment by bsmartin-ep** [comment]
This was deployed May 17....

https://github.com/department-of-veterans-affairs/vets-website/pull/17157

Closing.
