### ISSUE TITLE
Custom picker - UX/UI issues

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23539]
## What happened?
1. The custom picker menu is missing the placeholder, which should appear first in the list. The placeholder is missing on the following dropdowns (it _does_ appear as expected in the SM form dropdowns):
     - Edit Address > Country
     - Edit Address > State (U.S.-driven)
     - Edit Address > APO/DPO/FPO
     - Edit Address > State (Military address-driven)
     - Edit Direct Deposit > Account type
2. On the Country and State pickers, when an option is confirmed, the input field on the form displays an abbreviation of the selection ("AFG"), rather than the entire word or phrase ("Afghanistan")
3. Some options in the Country/State menu appear to be missing from the UI:
     - Country: Zambia/Zimbabwe??
     - State: Wisconsin, Wyoming

## Specs:
- Devices: iPhone 11

## Steps to Reproduce
1. On the Edit Address page, select the Country picker (see list above for all dropdowns where this is applicable). Notice how there is not a placeholder option above "United States"
2. Select a country from the picker (e.g. Afghanistan) and hit "Done". Notice how the input field displays this selection as "AFG", not "Afghanistan"

## Desired behavior
1. The first menu option in the picker should be a placeholder (there is a separate ticket to remove placeholder text from all dropdown/input fields: #23088)
2. When a selection is confirmed from the picker, it should appear in the same format on the form page. The form page should not display an abbreviated version of what was selected in the picker.
3. The picker menu should display all options for Countries, States, etc. 

## Acceptance Criteria
See desired behavior

## Bug Severity
- 2 - High

## Screen shot(s) and additional information
For #2:
![Image from iOS.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/3ca25453-4449-4bac-8e87-e896587a10e2)

**Comment by digitalken** [comment]
PASS 4/26/2021 - Looks good on iOS and Android.  Closing.
