### ISSUE TITLE
Redirect Request: VRRAP legacy page

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#23536]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
In ticket #22727, we created an informational/static page to communicate this new program to Veterans. Veterans who are unemployed because of COVID-19 and meet the other eligibility criteria can get education or training in a high-demand job. This program will last for 21 months.

### Requesting team info
*Indicate what team and who the primary contact on that team is*

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live* TBD

Please indicate when the change/redirect(s) needs to be implemented"
- [x] On the same date the new URLs launch
- [X] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing:

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
https://benefits.va.gov/gibill/vrrap.asp | /education/other-va-education-benefits/veteran-rapid-retraining-assistance

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [x] Implementation team: Implementation team completes work 
- [x] Implementation team: Implementation pushed live and redirect is validated in production
- [x] Requesting team: Ticket is closed

**Comment by lunascoop** [comment]
@mnorthuis can you assign this directly to brianalloyd or kelsonic after you’ve vetted the URLs? Thanks!

cc: @bethpottsVADEPO

**Comment by bethpottsVADEPO** [comment]
@RLHecht @brianalloyd @kelsonic Please hold on the redirect until I post here. The page isn't live yet and I also want to make sure stakeholders are aware before we put the redirect in place.

**Comment by kelsonic** [comment]
Sounds good! We will wait to work on this until you directly tell us it's good to go 🙂

**Comment by mnorthuis** [comment]
Request is vetted and documented, and ready to go per @bethpottsVADEPO .  Assigned to @brianalloyd for next steps.

**Comment by brianalloyd** [comment]
Thanks @mnorthuis, @RLHecht @lunascoop moving this into sprint for action @kelsonic.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/16885 CC @ncksllvn

**Comment by bethpottsVADEPO** [comment]
@kelsonic @brianalloyd I just saw in the edu channel that launch of the new page will not be this week, so maybe you can have this work on your radar for next week, and I'll follow up here when we need you to implement the redirect. Thanks!

**Comment by kelsonic** [comment]
I will keep the PR open as a `DON'T MERGE UNTIL */*/2021`, thanks for the heads up! 🙂

**Comment by kelsonic** [comment]
Hey @bethpotts any update on when we should merge the [redirects PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16885)? 🙂

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you coordinate this with @kelsonic once VRRAP launches?

**Comment by RLHecht** [comment]
@kelsonic as of now, VRRAP is launching 4/30. I'll let you know when the redirects are good to go.

**Comment by kelsonic** [comment]
Sounds good! Thank you for the update! 🙂

**Comment by RLHecht** [comment]
@kelsonic VRRAP is launching today with this afternoon's deploy. Does that mean we wait until Monday for the redirects? I don't think they can go at the same time, right?

**Comment by kelsonic** [comment]
PR merged, will go out with the daily deploy today
