### ISSUE TITLE
CT Redesign: Create "Update tuition and housing estimates" component

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23567]
As a developer, I need to create a component that allows users to answer questions regarding their tuition and housing questions so that their estimated benefits can be updated accordingly and the component can be tested during usability testing.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The behavior of this component will match the existing TBD component, except that the "Select an institution" question has been removed.
    a. The current business logic to update the search results cards financial information is maintained.
3. Adding the component to the profile page is out of scope of this story.

## Acceptance Criteria:
1. The search results display a "Update tuition and housing estimates" component that allows the user to answer questions in order to receive a more accurate update to their estimated benefits.

2. The following questions are always displayed
    a. What's your military status?
    b. Which GI Bill benefit do you want to use?
    c. Will you be taking any classes in person?

#### What's your military status?

3. The available answers to the "What's your military status?" question are:
    a. Veteran (default)
    b. Active Duty
    c. National Guard / Reserves
    d. Spouse
    e. Child

4. The "Is your spouse on active duty?" question is conditionally displayed when the answer to the "What's your military status?" is "Spouse".

5. The available answers to the "Is your spouse on active duty?" question are:
    a. Yes
    b. No

#### "Which GI Bill benefit do you want to use?"

6. The available answers to the "Which GI Bill benefit do you want to use?" are:
    a. Post-9/11 GI Bill (Ch 33) (default)
    b. Montgomery GI Bill (Ch 30)
    c. Select Reserve GI Bill (Ch 1606)
    d. Veteran Readiness and Employment
    e. Dependents Educational Assistance (DEA)

7. The "Which GI Bill benefit do you want to use?" has a "Learn more" link that displays the following helper content:

    > **Which GI Bill benefit do you want to use?**
    > You may be eligible for multiple types of education and training programs. Different programs offer different benefits, so it’s important to choose the program that will best meet your needs. Use this tool to compare programs and schools.
    > 
    > Learn more about [GI Bill program benefits and eligibility requirements](https://staging.va.gov/education/eligibility/).

#### "Cumulative Post-9/11 active-duty service"

8. The "Cumulative Post-9/11 active-duty service" is conditionally displayed when the answer to "Which GI Bill benefit do you want to use?" is "Post-9/11 GI Bill (Ch 33)".

9. When the answer to "Which GI Bill benefit do you want to use?" is "Post-9/11 GI Bill (Ch 33)" AND the answer to "What's your military status?" is "Active duty" the following content is displayed:

    > [Post 9/11 GI Bill](http://www.benefits.va.gov/gibill/post911_gibill.asp) recipients serving on Active Duty (or transferee spouses of a service member on active duty) are not eligible to receive a monthly housing allowance.

10. The available answers to the "Cumulative Post-9/11 active-duty service" question are:
    a. 36+ months: 100% (default)
    b. 30 months: 90%
    c. 24 months: 80%
    d. 18 months: 70%
    e. 6 months: 60%
    f. 90 days: 50%
    g. GYSGT Fry Scholarship: 100%
    h. Service-Connected Discharge: 100%
    i. Purple Heart Service: 100%

11. The "Cumulative Post-9/11 active-duty service" question has a "Learn more" link that displays the following helper content:

    > **Cumulative Post-9/11 service**
    > The Post-9/11 GI Bill provides financial support for education and a housing allowance. To qualify for this program, you must have served after September 10, 2001 for at least 90 days or, if you were discharged with a service-connected disability, for at least 30 days. The service period for these benefits doesn't include your entry and initial skill training. You also need to have received an honorable discharge.

#### "Montgomery GI Bill (Ch 30)"

12. The "Completed an enlistment of:" question is conditionally displayed when the answer to "Which GI Bill benefit do you want to use?" is "Montgomery GI Bill (Ch 30)".

13. The "Completed an enlistment of:" question has a "Learn more" link that displays the following helper content:

    > **Completed an enlistment of (MGIB):**
    > The Montgomery GI Bill – Active Duty provides education benefits to Veterans and service members who have served at least two years of active duty. When using this tool, you will need to select the length of your original active duty enlistment obligation in order to get an estimate of your monthly benefit. The amount of time you served (2 year enlistment vs. 3+ year enlistment) will impact your monthly payment amount when using the Montgomery GI Bill. To learn more about MGIB please visit  http://www.benefits.va.gov/gibill/mgib_ad.asp.

14. The "Completed an enlistment of:" question has the following available answers:
    a. 3 or more years (default)
    b. 2 or more years

#### "Veteran Readiness and Employment"

15. The following is conditionally displayed when the answer to the "Which GI Bill benefit do you want to use?" is "Veteran Readiness and Employment":
    a. The note: `To apply for VR&E benefits, please [visit this site](https://www.ebenefits.va.gov/ebenefits/about/feature?feature=vocational-rehabilitation-and-employment).`
    b. The question: "Are you eligible for the Post-9/11 GI Bill?"

16. The available answers to the question "Are you eligible for the Post-9/11 GI Bill? are:
    a. Yes
    b. No (default)

17. The "How many dependents do you have?" question is conditionally displayed when the answer to "Are you eligible for the Post-9/11 GI Bill?" is "No".

18. The available answers to the "How many dependents do you have?" question are:
    a. 0 dependents (default)
    b. 1 dependents
    c. 2 dependents
    d. 3 dependents
    e. 4 dependents
    f. 5 dependents

#### "Will you be taking any classes in person"

19. The available answers to the "Will you be taking any classes in person?" question are:
    a. Yes (default)
    b. No

20. The "Will you be taking any classes in person?" question has a "Learn more" link that displays the following helper content:

    > **Your housing allowance is determined by where you take classes**
    > Under the GI Bill you’re eligible to receive a monthly housing allowance. We calculate this monthly housing allowance based on where you take classes.
    > 
    > If you use Post-9/11 GI Bill benefits to take at least 1 in-person class, your housing allowance is based on where you do most of your coursework. If you take online courses only, your housing allowance is based on 50% of the national average.
    > 
    > Through Dec. 21, 2020, current and new students can receive in-person allowance rates if their school’s approved program changed from in-person to online learning due to COVID-19.
    > 
    > [View the current housing allowance payment rates](https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp?_ga=2.144591223.39405460.1542131207-1582256389.1508352376)

21. The user has the ability to initiate an update of the cards after changing the answers to the questions.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/37IAGO4DHZG)
2. <img width="317" alt="Screen Shot 2021-04-20 at 4 07 29 PM" src="https://user-images.githubusercontent.com/48260534/115457420-862a2a80-a1f2-11eb-89dc-7805598407cf.png">

**Comment by sonntag-adam** [comment]
Text shouldn't be italicized 
![Screen Shot 2021-05-12 at 1.48.15 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/048d325e-0c32-4f66-9b7d-d94bc1461970)
##
Housing Benefit:
$1,650 / Month
When it should flip between $825 and $1860 for Charleston Southern University for example.
![Screen Shot 2021-05-12 at 1.49.34 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f4baf608-bdce-4830-b58d-95985dd157b7)
##
Radio button does update housing per selection
![Screen Shot 2021-05-12 at 1.42.43 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/98de0733-c90b-453c-b7db-1d79059c6628)

**Comment by sonntag-adam** [comment]
Moving back to in progress

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1869&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.
