### ISSUE TITLE
Archiving of Slack Channels

### ISSUE THREAD

**Issue by JQuaggles** [department-of-veterans-affairs/va.gov-team#2357]
Good afternoon,
  I'd like to have the following slack channels archived:
Okay'd by DSVA folks - any questions please ask @andrewlewandowski 

Channels to be archived:
#cms-administration 
#cms-changemgmt
#cms-ci 
#cms-demos 
#cms-design 
#cms-engineering-frontend
#cms-migrations 
#cms-outreach 
#cms-product 
#cms-unity

**Comment by lisac-usds** [comment]
coordinating with @JQuaggles , we've decided to make this change at the end of the day on Friday. I'll follow up after I've applied the change.

**Comment by lisac-usds** [comment]
Hi @JQuaggles , with the exception of `#cms-ci`, I've archived the channels in your list. 

Why did I not archive `#cms-ci`? I saw recent activity in it. I'm asking the CMS team for feedback, via a post in the [#cms-general]( https://dsva.slack.com/archives/CDHBKAL9W/p1570828052009000) channel. Planning to follow up on Tuesday (Oct 15) afternoon.

**Comment by lisac-usds** [comment]
from the team's comments in the slack thread, I've decided not to archive `#cms-ci`.
