### ISSUE TITLE
10-10CG signature page (followup from call)

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#23572]
## Acceptance Criteria
- Finalize content and design for signature boxes for POA
- Update prototype to reflect new designs

This is a followup to a meeting Danielle and Dené had on 4/20/2021. 

The option to upload a document for legal representative worked well in usability testing. The part that did not preform well is when the representative reached the signature page. 
1.  None of our participants immediately understood that they need to sign their own name (not Veteran’s name)
2. Some participants were confused that they would need to sign own name twice (as representative and caregiver)
3. Program team would still like to provide representative opportunity to sign own name not Veteran’s

Attached:

1. **PDF of [staging](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg) signature page**
[https://app.zenhub.com/files/133843125/b36587d4-c278-4c8d-a7e7-349e00a30280/download](https://app.zenhub.com/files/133843125/b36587d4-c278-4c8d-a7e7-349e00a30280/download)

2. **Screenshot of design ideation after usability test**
![CG_Updated signature_04.20.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/ef96907e-9528-472b-84be-20034c6597e2)

3. **Marked up design with Danielle's initial thoughts from meeting**
![Signature-Danielle initial thoughts.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/dd687d24-0646-413e-a46d-8b28b3a6e53f)

**Comment by sshein** [comment]
thanks Dené! can you add it to this sprint and link it to this ticket? https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/22702 - or ask Alayna to help?

**Comment by sshein** [comment]
@DanielleThierryUSDSVA curious what suggestions you'd give to resolve the issue of "I" and "you" both appearing - since the "I statements" are the things the user is agreeing to and the "you" statement is not what they are agreeing to, just a note about how they filled out the form. Also FYI the "I" Statements are legalese statements that we can't really change :)

**Comment by ala-yna** [comment]
@sshein / @DanielleThierryUSDSVA  - The paper form does say, 

> `I certify that I give consent to the individual(s) named in this application to perform personal care services for me **(or if the Veteran's Representative, the Veteran)** upon being approved as a Primary and/or Secondary Family Caregiver(s) in the Program of Comprehensive Assistance for Family Caregivers. I certify that the information provided in this form is correct and true to the best of my knowledge and belief.`

Perhaps we could conditionally show the "if the Veteran's Representative" bit if the person is signing as a representative?

**Comment by sshein** [comment]
right Dené and I talked a little bit about this. I think that makes sense... we also talked about if we even need "for me" if we know it's the veteran signing, e.g. we could just say "for the Veteran" but then we decided representatives really aren't used to things changing conditionally for them, and they were more comfortable seeing language that referred to the veteran - which is why we think we're recommending *not* changing the header to "representative's statement of truth" but keeping it as "veteran's statement of truth"

**Comment by DanielleThierryUSDSVA** [comment]
Hi! What do you think about trying something like this?

### Veterans statement of truth
**Signed by the Veteran’s legal representative on behalf of the Veteran**

I certify…

I have read…

Enter representative’s full name (*Required)

[signature box] On behalf of **Rodrigo S. Fleet**

**Comment by DanielleThierryUSDSVA** [comment]
Or maybe with an added note:

### Veterans statement of truth
**Signed by the Veteran’s legal representative on behalf of the Veteran**

I certify…

I have read…

Enter representative’s full name (*Required)

**Note:** Enter your own name here to sign as the Veteran's representative.

[signature box] On behalf of **Rodrigo S. Fleet**

**Comment by sshein** [comment]
I like it - screenshot for folks to look at. One thing is I don't think the hint text color against the gray box is accessible so we'll have to figure it out. Also slightly edited the "note/hint text" - what do y'all think?
![Uploading Screen Shot 2021-04-22 at 9.50.23 AM.png…]()

**Comment by sshein** [comment]
@joshkimux do you have thoughts on the hint text on the gray box?

**Comment by DanielleThierryUSDSVA** [comment]
Love your edit to the hint text, @sshein - thanks!

**Comment by joshkimux** [comment]
@sshein yes! Would be great if we could make the hint text darker here. It's currently coming in at 3.96:1, when it should be 4.5:1

<img width="779" alt="Screen Shot 2021-04-22 at 2 38 50 PM" src="https://user-images.githubusercontent.com/14154792/115768551-776d8000-a378-11eb-900b-14a5a7289bd0.png">
