### ISSUE TITLE
CT Redesign: Create copy of profile pages for use in sandbox

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23581]
As a developer, I need to copy the institution profile pages to the sandbox so that they can be used during usability testing.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. The current profile page for non VET TEC institutions is accessible in the sandbox.
2. The current profile page for VET TEC institutions is accessible in the sandbox.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16946

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1738&group_by=cases:section_id&group_order=asc)

**Comment by delli-gatti-michael** [comment]
Changes are on Staging. Closing this issue
