### ISSUE TITLE
CT Redesign: Comparison Tray Controls - Team Sync

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#23590]
Comparison Tray prototypes with improved controls are reviewed with UXBA

* Prototype is shared with relevant team members 
* Feedback is collected
* Prototype is tweaked, per input OR additional stories are written, as necessary

**Comment by JenLJ** [comment]
Shared with team on April 22nd.

Feedback:
- Like the mobile view better
- Need to be consistent with order of buttons
- Consider using checkboxes instead of Xs to remove schools
