### ISSUE TITLE
CT Redesign: Create "Refine your search" component

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23597]
As a developer, I need to create a component that allows users to filter their search results so that the institutions they are looking for can be displayed in the search results and the component can be tested during usability testing.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This component is similar to the current "Refine search" functionality on the search results.

## Acceptance Criteria
1. The user has the ability to filter down the search results by the following criteria:
    a. Type of Institution
    b. Location
    c. School Attributes
    d. Type of School
    e. School Mission

#### Type of Institution

2. Filters available for "Type of Institution" are:
    a. Schools (default)
    b. Employers (On the job training and Apprenticeships) (default)
    c. VET TEC (default)

3. The VET TEC filter has a sub-filter of "Preferred Provider"
    a. If the user selects the "Preferred Provider" filter, the "VET TEC" filter is automatically selected.
    b. If the user de-selects the "VET TEC" filter, the "Preferred Provider" filter is automatically de-selected.

#### Location

4. The user can filter results by country.
    a. The country list is populated with the country of institutions in the current set of search results.
    b. All is an available filter option (default)

5. The user can filter results by state.
    a. The state list is populated with the state of institutions in the current set of search results.
    b. All is an available filter option (default)

### School Attributes
6. The following are filter groupings under "School Attributes":
    a. Type of School
    b. School Mission

7. The following general filters are available:
    a. Has no cautionary warnings
    b. Is accredited
    c. Has student veteran group
    d. Offers Yellow Ribbon Program

8. The "Has no cautionary warnings" has a "Learn more" link that displays the following content:

    > **Cautionary warnings and school closings**
    > VA applies caution flags when we, or another federal agency, have increased regulatory or legal scrutiny of an educational program. We recommend students consider these warnings before enrolling in flagged programs.
    > 
    > When VA receives notice that a school or campus location will be closing, we add a school closing flag to that profile. Once the closing date passes, we remove the institution from the Comparison Tool during the next system update.
    > 
    > To learn more about caution flags, [visit the About this Tool page](https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#CF).

9. The "Is accredited" has a "Learn more" link that displays the following content:

    > **Accreditation and why it matters**
    > The goal of accreditation is to ensure that the education provided by institutions of higher education meets acceptable levels of quality. Schools can be accredited by private educational associations of regional or national scope.
    > 
    > Accreditation matters if you plan to start school at one institution and transfer to another to complete your degree.  Be sure to ask any potential school about their credit transfer policy.

9. The available answers to the "Type of School" question are:
    a. All (default)
    b. Flight
    c. Foreign
    d. For Profit
    e. Private
    f. Public

10. The available answers to the "School Mission" question are:
    a. Historically Black Colleges and Universities
    b. Single gender school
    c. Religious Affiliation

11. The search results are updated to include results that contain the selected values of AC2-9.

12. The user has the ability to initiate an update of the cards using a button after changing the answers to the questions.

## Supporting Artifacts:
1. [Prototype - Search by name](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296060315_Searchbyname_Desktop_4_refineopen)

2. [Prototype - Search by location](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296060646_Searchbylocation_Desktop_results_openrefine)

**Comment by elder-joseph** [comment]
Associated PRs:
Website: https://github.com/department-of-veterans-affairs/vets-website/pull/17295
GIDS: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/822

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1901)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17455

**Comment by zurbergram** [comment]
need both to test filters
https://github.com/department-of-veterans-affairs/vets-website/pull/17455
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/828/

**Comment by delli-gatti-michael** [comment]
After adding lat/long data to a VET TEC and OJT school locally I found the following:
1. Having both "Employers" and "VET TEC" checked omits VET TEC results which should show.
2. Having "Employers", "VET TEC", and "Preferred Providers" all checked omits all results

I am currently unable to test the "country" filter for Location search as foreign institutions are currently not shown in the results.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/829

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
These changes are now on staging. Closing this issue
