### ISSUE TITLE
Find a VA Form: Feature Flag to allow testing ranking/scoring changes in Forms API

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23599]
## User Story

As a member of the Find a VA Form Product Team, I want the ability to test the Forms API ranking/scoring changes on Staging so that I can help determine if it is producing the desired results.

## Expected Behavior

Changes to the Forms API that score and rank search results are testable on the Staging environment

## Acceptance Criteria

- [ ] Feature flag to hide new scoring/ranking Forms API change is created
- [ ] Code changes required to test changes in Staging are added
- [ ] Code with feature flag is promoted to Staging

**Comment by zacharymorel** [comment]
Adding blocked until lighthouse gives it the go.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel do you want a separate ticket for the FE change to add a new sorting option to the select, or would you prefer I add that to this one?  Thx!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Let's open another. I'm not sure about timing, VSP's involvement and such

**Comment by MarciMcGuireGCIO** [comment]
Done! Thanks!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO This as well could be closed now that the bug is fixed and the feature flag is on?

**Comment by MarciMcGuireGCIO** [comment]
Aye, @zacharymorel.  That is correct.  🦜 🏴‍☠️
