### ISSUE TITLE
Discharge Upgrade Wizard: Design Intent to change PDF link to Portal Link

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23591]
## User Story

Please refer to the details of the link change requested in #23071

## Expected Behavior

Please mock up design changes for changing PDF link to AFRBA portal link.

## Acceptance Criteria

- [x] Mockups created
- [x] Draft verbiage created
- [ ] Design intent review and content review completed.

**Comment by MarciMcGuireGCIO** [comment]
Blocking this until we have content for the new page.

**Comment by callen2563** [comment]
I will bring this to Content office hours on Monday to see if I can get some movement on content.

**Comment by MarciMcGuireGCIO** [comment]
Thank you! I do have a content request out there, but the conversation will probably help too!

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO & @callen2563 can we meet up briefly this week to talk about his request and how it relates to the [content request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25578) for the same product?  I can't see your calendar, @bethpottsVADEPO , but if you can send me a few time slot options, I'll schedule!  Thank you!

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO I'm free today 3:30-4:00 ET and tomorrow 11:00 - 1:00 ET. Thanks for setting up some time for us!

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @bethpottsVADEPO !  Cassanda had some conflicts, so I scheduled for tomorrow at 11:30 ET.  Thanks for making time for us!

**Comment by MarciMcGuireGCIO** [comment]
Meeting notes from 2021-06-17 https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-update/post-mvp/air-force-portal-link/meetings.md#2021-05-19-meeting-to-discuss-content-for-link-change-for-air-force-veterans

**Comment by bethpottsVADEPO** [comment]
@callen2563 Let's try this for your mockup:
- Remove the whole subway map 
- Replace the existing intro paragraph with this:

Based on your answers, you need to complete an Application for Correction of Military Record (DD Form 149). You can download this form from the Air Force Review Board Agency portal.
Button: Find the form on the Air Force portal

**Notes:** I may futz with the button label a bit more, but let's see how this overall approach works. I tried creating a subway map with the instructions once you get to the portal, but in the end I thought it was easy enough to find the form to download on that site. So I opted for this shorter version.

**Comment by callen2563** [comment]
@bethpotts Hi Beth, Let me know if this is what you were thinking or if you want to change the CTA copy at all. Thanks! :)


![Introduction - Discharge Wizard - Desktop](https://user-images.githubusercontent.com/68560244/123482047-9daad880-d5d2-11eb-98fe-f7ef5cd3adbb.png)

**Comment by bethpottsVADEPO** [comment]
@callen2563 I feel like the CTA should change to "Get the form on the Air Force portal" so it doesn't sound like "good luck to you, go find it!" Would you make that change?

**Comment by callen2563** [comment]
haha sure! Here you go: 
![Introduction - Discharge Wizard - Desktop](https://user-images.githubusercontent.com/68560244/123692710-2325c700-d825-11eb-9309-5f6772322729.png)

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 can you please share the Sketch link for the latest design so that I can include in the design intent request ticket?  Thank you!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO my memory and notes doesn't serve me well, I cannot remember the under what condition of which the page would show above. I gather _Air Force_ is the branch that is selected.

**Comment by MarciMcGuireGCIO** [comment]
I'll find the full request and post here.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/23071 is the ticket for the coding work.  I believe it has all the details, but if you still have questions, LMK.

**Comment by zacharymorel** [comment]
So, quick q, is the button only replacing where the link is to `download form 149` ? 
![Screen Shot 2021-06-29 at 3 01 16 PM](https://user-images.githubusercontent.com/26075258/123852932-ddcbcd00-d8ea-11eb-98b7-5474bbe2e34c.png)

Or are we removing the steps and other text presented at the Air Force form for 149.

**Comment by MarciMcGuireGCIO** [comment]
Closing this since the design is ready for design intent review.

**Comment by callen2563** [comment]
updated the CTA with the new action link

![Introduction - Discharge Wizard - Desktop](https://user-images.githubusercontent.com/68560244/124628997-fe49d900-de4e-11eb-8967-5120ce14b9a9.png)

**Comment by MarciMcGuireGCIO** [comment]
Thank you @callen2563! Looks great!!

**Comment by zacharymorel** [comment]
Thank you @callen2563 !
