### ISSUE TITLE
Document rollback process 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#236]
The rollback process is not well documented. it should include 
- more specific criteria for a rollback
- types of rollbacks and how to do them 

manual deploys are covered in /getting-started/workflow/deploy

**Comment by timwright12** [comment]
Closing out as complete: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/deploy#rollbacks
