### ISSUE TITLE
Content Feedback - Midpoint review - Virtual Agent 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#23611]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

**Comment by peggygannon** [comment]
@katieho-va 

I am not providing detailed content feedback at this time, as I know your team is still working with the sitewide content team on the content. Here are just a few thoughts regarding what's in the mockup. 


**Thoughts**

1. Screens 5 and 6: Use plain language in message(For example, require should be> need)

2. Screen 6, consider making the first line of the message the header to make this message more specific  for users and to condense the message down. . 
“We’re working on the site” > **We’re making some updates to the Virtual Agent**

3. Please hyperlink all phone numbers and TTY number

4. For screen 8 in prototype, consider making this your header: 
**Thank you for using our Virtual Agent**
I also recommend condensing this alert down, following plain language and styleguide principles (For example, use contractions.  you are should be> you’re)

**Comment by murrayra** [comment]
Noted in [this ticket](https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/159) what we incorporated and what we likely would do post POV.
