### ISSUE TITLE
 Review new content, update prototype, and highlight changes for the new 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23613]
## Acceptance Criteria

- Review the new form
- Highlight any changes that we'll need to make on the online form
- Update the prototype
- Pass them to a front-end dev by updating this ticket: https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/23527

**Comment by Dene-human** [comment]
[Living Doc](https://docs.google.com/document/d/1MJaemi4cSI8AvNtzBwX4SlXT4ouUOGo4-KGE5YYcssA/edit#) for comments and questions


### Signature page
**Primary Family Caregiver applicant’s statement of truth**
<img width="694" alt="primary statement update" src="https://user-images.githubusercontent.com/80857940/116468259-a1261b80-a83e-11eb-8b71-46c00b0d9fcd.png">

1. Update text with below:

I certify that I am at least 18 years of age.	
				
I certify that either: (1) I am a member of the Veteran's family (including a parent, spouse, a son or daughter, a step-family member, or an extended family member) OR (2) I am not a member of the Veteran's family, and I reside with the Veteran full-time or will do so upon designation as the Veteran's Primary Family Caregiver.

I agree to perform personal care services as the Primary Family Caregiver for the Veteran named on this application.	

I understand that the Veteran or the Veteran's surrogate may request my discharge from the Program of Comprehensive Assistance for Family Caregivers (PCAFC) at any time and that my designation as a Primary Family Caregiver may be revoked or I may be discharged from PCAFC by the Secretary of Veterans Affairs (or designee) as set forth in 38 CFR 71.45.	
				
I understand that participation in the PCAFC does not create an employment relationship between me and the Department of Veterans Affairs.

2. Remove word: “Enter”		
		



		
**Secondary Family Caregiver applicant's statement of truth	
And
Secondary Family Caregiver (2) applicant’s statement of truth**
<img width="706" alt="secondary statement update" src="https://user-images.githubusercontent.com/80857940/116468278-a84d2980-a83e-11eb-86b0-c31b9cbe988e.png">

1. Update text with below:

I certify that I am at least 18 years of age.	
				
I certify that either: (1) I am a member of the Veteran's family (including a parent, spouse, a son or daughter, a step-family member, or an extended family member) OR (2) I am not a member of the Veteran's family, and I reside with the Veteran full-time or will do so upon designation as the Veteran's Secondary Family Caregiver.	
	
I agree to perform personal care services as the Secondary Family Caregiver for the Veteran named on this application.
					
I understand that the Veteran or the Veteran's surrogate may request my discharge from the Program of Comprehensive Assistance for Family Caregivers (PCAFC) at any time and that my designation as a Secondary Family Caregiver may be revoked or I may be discharged from PCAFC by the Secretary of Veterans Affairs (or designee) as set forth in 38 CFR 71.45.

I understand that participation in the PCAFC does not create an employment relationship between me and the Department of Veterans Affairs.
						
2. Remove word: “Enter”	
									
NOTE: 
Please make sure changes are reflected for ALL Secondary Family Caregivers (if there are more than one)- Secondary Family Caregiver and Secondary Family Caregiver (2)
