### ISSUE TITLE
Update 10-10EZ content with new form (April 2021)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23610]
## User Story

As a Veteran 
I want to fill out the latest version of the online form
So that I can apply for the program with the most useful information.

## Acceptance Criteria
- [Product] Receive & distribute new paper form
- [Design] Prototypes are updated
- [Design] New language is approved by VSP
- [Design/Product] New changes are approved by Health care program
- [Frontend] Front end is updated
- [Backend] Any backend changes are made
- [Product] Front end is QAed
- [Product] Pushed to production
- [Product] Confirmed there are no errors

**Comment by ala-yna** [comment]
Draft of the new form: [https://app.zenhub.com/files/133843125/9b991ddb-aac6-433e-8796-a5c775d5b71f/download](https://app.zenhub.com/files/133843125/9b991ddb-aac6-433e-8796-a5c775d5b71f/download)

**Comment by mlighdc** [comment]
@ala-yna I sent up the latest agreed upon changes to the 10-10EZ via email.

In summary:

- Online form for enrollment

- Add 3B. SELF-IDENTIFIED GENDER IDENTITY. 

![image.png](https://images.zenhubusercontent.com/5eaf8fc6e9ce8c652d0f1cb4/985cf6d1-9ed0-4248-b77e-e6956cda6dac)

![image.png](https://images.zenhubusercontent.com/5eaf8fc6e9ce8c652d0f1cb4/270e3738-94fd-4289-a87b-de653fec90ec)

I think that is it for this round. It would be great if you can summarize the other discussion we had with the Healthcare Enrollment team on Friday, April 30th. Thanks.

**Comment by tchrisdyer** [comment]
The gender identity question was separated into it's own project. All other items have been completed and promoted to production.
