### ISSUE TITLE
[Carryover] [Frontend] Update POA implementation to account for A11y findings

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23616]
See: https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/23222

Additional notes from @sshein:
- [x] [Dev intent] Ensure `legend`s are properly used with `fieldset`s
- [x] Style the `legend` to be more recognizable from standard `p` text [Step 4 of 5: Legal Representative](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666495/simulate/sitemap?mode=i) (might just be a prototype issue)
- [x] Add labels to signature boxes to satisfy accessibility requirements
- [ ] Make document upload edit by default on review page 
- [x] If we keep "on behalf of" - Either rewrite content so that "on behalf of" is not an isolated `p` tag between two fields (preferred) OR use `aria-describedby` so that it is programatically linked to the first field [Step 5 of 5: Review Application](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666520/simulate/sitemap?mode=i)

**Comment by LinnJS** [comment]
One last thing that is not fully implemented is the `aria-desribeby` looks like the DSVA component does not accept that prop or have one I can pass to it. Will need to add an `ariaDescribeby` prop to the DSVA [TextInput](https://design.va.gov/storybook/?path=/docs/components-textinput--default) kind of like what is implemented for the [Checkbox](https://design.va.gov/storybook/?path=/docs/components-checkbox--default) on the `ariaLabelledBy` prop. Added the code but will not take effect till this component is updated.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17168) With all fixed besides the two listed above will be merging today.

**Comment by dat-gcio** [comment]
Opened PR on the DSVA component to add area-describedby. [PR](https://github.com/department-of-veterans-affairs/component-library/pull/96)

**Comment by dat-gcio** [comment]
[Merged the component library change for the aria-describedby attribute today](https://github.com/department-of-veterans-affairs/component-library/pull/96). Will need to update the component library version number in vets-website repo and change the spelling of the implimentation to `ariaDescribedBy`

**Comment by dat-gcio** [comment]
Tested the `ariaDescribedBy` change in staging and it looks good. The `Make document upload edit by default on review page` task was made into a ticket and passed off to Platform. I think we can close out this ticket.

**Comment by tchrisdyer** [comment]
Added to Sprint 48 Epic for tracking purposes. Remove Sprint 47 Epic

**Comment by dat-gcio** [comment]
@tchrisdyer Going to close this out, the last bullet point for updating the review page platform code is in this [TICKET](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24583)
