### ISSUE TITLE
SM ListItem not respecting right margin

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23614]
## What happened?
1. On the Secure Message list pages, the ListItem content touches the right edge of the screen and hides the right chevron ">". Should be seeing a line-wrap when applicable. 

## Specs:
- Device: iPhone 11, Samsung Galaxy S9
- Test user: 261, 41

## Steps to Reproduce
1. Log in with user 261 and navigate to the Inbox page.
2. View the list of messages. Notice that messages with a longer subject line touch the edge of the screen.

## Desired behavior
Right margin for SM ListItem is maintained like other ListItems

## Acceptance Criteria
Right margin is maintained.

## Bug Severity 
- 3 - Medium

## Linked to Story
n/a

## Screen shot(s) and additional information
![IMG_0186.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b123bc1f-9391-495e-8e44-73e5a5ed9521)
![IMG_0187.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/026048f4-2bfc-4a8b-aa1c-23be1f5df348)

**Comment by digitalken** [comment]
PASS 4/26/2021 - Looks good on iOS and Android.  Closing.
