### ISSUE TITLE
Create Conversation Guide for HCA Study

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23621]
## Acceptance Criteria

- Write conversation guide
- Pass to VSP for approval

**Comment by Dene-human** [comment]
Conversation guides for discovery with SMEs and end user 1:1s linked below:

- [Conversation Guide: VSA Caregiver, Discovery Research for the 10-10EZ form-SME interviews, May 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Research%20April-May%202021/SME%20Discovery%20Research/1:1conversation-guide.md)

- [Conversation Guide: VSA Caregiver, Discovery Research for the 10-10EZ form, May 2021](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Research%20April-May%202021/End%20user%20discovery%20research/conversation-guide.md)
