### ISSUE TITLE
CT: Use institution physical address for free text search

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23637]
As a developer, I need the free text search to reference the physical address for the institution, so that the institution is returned when a user searches for institutions where they would be attending classes.

## Assumptions:
1. This work is completed behind a prod flag.
2. The VETTEC free text search currently uses physical address.
3. This work is completed in the current comparison tool NOT the sandbox.

## Acceptance Criteria
1. When searching for any of the following, the institution physical address fields (street 1, street 2, street 3, city, state, zip, country) are used:
    a. city
    b. state
    c. city, state (abbreviation)
    d. zip code
    e. country

## Supporting Artifacts:
1. N/A

**Comment by ksantiagoBAH** [comment]
Pull request: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/807

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-04-28 at 9.56.42 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/df590a24-a7f1-42b9-85a9-c31c520d4a3a)
##
![Screen Shot 2021-04-28 at 9.56.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/abf9b659-0e38-4e6b-973b-3fcf4744aa13)
##
![Screen Shot 2021-04-28 at 9.57.15 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/70a674f5-f1d4-4d11-8b14-1ef7a307c25c)

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
