### ISSUE TITLE
Accessibility Feedback - Midpoint review - Virtual Agent

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#23632]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- ~~Is this going to use the same Microsoft bot framework as the COVID-19 chatbot?~~
- Does the chatbot have a list of shortcuts or a bailout option to speak to a human? There's a non-zero cognitive load associated with bots. Sometimes we want to just press "0" and talk to someone.
- Does the chatbot have text appear that says "The bot is typing..." or something like that?
  - If it does not, no further action is needed on this question.
  - If it does, please monitor this closely in research sessions. It could be too much overhead for screen readers or users with cognitive issues like PTSD, ADD, or anxiety.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

### Must:
- Test the chatbot with mobile device users
- Test the chatbot with screen reader users
- Consider the source order and target area for the chat icon:
  - Is it at the end of the HTML on the page?
  - Do keyboard users have to tab through all of the page to open a chat?
  - Is there clear space around the chat icon on mobile?
- Consider how new messages are announced and how focus is handled:
  - Users type in their message, and it appears immediately. Does it receive focus and get read back to screen readers?
  - What happens when the bot or a human responds? Does that message receive focus when it's added to the screen? Is it read back to screen readers?
  - This is different from the COVID-19 chatbot because responses are slower.
  - Does focus remove the need for an ARIA live region?
- User text and chatbot text should have contrasting background colors (like in the Microsoft example to help users easily differentiate the two

### Should:
- Test the chatbot with voice navigation users:
  - Thinking users of Dragon Speaking Naturally and/or Zoom Text
  - The paper airplane icon could be problematic for this user group. I don't know enough about how voice navigation would interact with the input to say for sure, so I'm raising it now.

### Consider:
- Testing with IE11 + JAWS if possible. The button > SVG pattern has some particular quirks with this combination that can be coded for defensively, but require real box testing to confirm.
- Moving the `placeholder` text out of the input and making it a label that is visible all the time. This does reduce the compactness of the input, but the tradeoff is improved cognition. Placeholders disappear when the input receives focus, which introduces a small level of uncertainty.
- Is there a way to communicate the chatbot is unavailable without having to click to open the chat window?

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by murrayra** [comment]
We are tracking all the outstanding accessibility issues in this [ticket](https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/169), some of which will be discussed in the Staging Review and may be post proof of value
