### ISSUE TITLE
GIDS: Profile page mailing zip incorrect

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#23638]
Note: This issue may have caused this https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19652

## Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/25115205
2. Observe the mailing address below and see what is in the weams file
![Screen Shot 2021-04-22 at 1.46.17 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/95746d2d-3d98-42d3-9f61-170367e414f4)
![Screen Shot 2021-04-22 at 1.46.33 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/82332206-f7eb-45a6-8d9a-f945a449384d)
3. The profile page doesn't show the correct zip code and appears to be pulling the physical institution zip code when it should be pulling the institution zip code

## Expected results:
1.  Pulling the institution zip code from the weams file.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/16912

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-04-23 at 12.02.45 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e5eb0245-dc3b-4869-bb5e-72f8d4bc413f)

**Comment by sonntag-adam** [comment]
in staging.
