### ISSUE TITLE
Design Review with Shawna

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2363]
## Goal
Meet with Shawna and seek feedback on the current design state for the Rated Disabilities feature.

## Considerations
There are some alternate design options that need to be decided upon.

## Acceptance Criteria
- [x] Schedule a time with Shawna
- [x] Address her feedback

**Comment by sporeboy** [comment]
Meeting and review conducted 10/16. Feedback received and addressed in layouts presented during design review:

https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/
