### ISSUE TITLE
[TASK] User Interview Analysis

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2364]
## Task
Review and analyze results of user interviews regarding current eBenefits awareness and usage.

### Goal
Produce a foundational discovery document that will provide insight and a baseline understanding for the importance of eBenefits features as Veterans and their families manage VA benefits. 

- Aggregate Participant views into relevant personas
- Identify common patterns, preferences and pain points
- Matrix participants experiences with various eBenefits features
- Identify opportunities to improve eBenefits features and performance

### Considerations
[Nice example](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Disability/Declare%20Dependent%20686/Design/Usability%20Research%20June%202018/20180719.686.research.readout.pdf)

### Acceptance Criteria
- [x] Develop a presentation of significant findings

**Comment by sporeboy** [comment]
Aricka has a starting point for review/analysis of user interviews here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/research-findings.md

I will pick up where she started.

**Comment by sporeboy** [comment]
Aricka's initial synthesis/analysis MURAL is here: https://app.mural.co/t/vsa8243/m/vsa8243/1570714734227/135cc9229f15be89de914d583c8f5d51fa38552d

**Comment by sporeboy** [comment]
Final MD write-up is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/research-findings.md
