### ISSUE TITLE
Request access to Domo

### ISSUE THREAD

**Issue by rebekahickey** [department-of-veterans-affairs/va.gov-team#23643]
## User Email Address
rebekah.hickey@adhocteam.us

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [X] Domo
_Please list any additional requirements, if any._

## Date Required
By the middle of next week.

## Product Team / External Team / VA Office
VSP Service Design

CC: @jchasia-adhoc 

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
@rebekahickey You should now have Domo access.
