### ISSUE TITLE
CT Redesign: Populate missing latitude and longitude values

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23651]
As a developer, I need to populate the missing latitude and longitude values on version generation so that all institutions are considered when a user uses searches by location.

## Assumptions:
1. Previously completed research [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/schools-near-me/research.md)
2. Census Tool Data was imported as part of #24332

## Acceptance Criteria
1. If an institution does not have a latitude or longitude value both looked up and replaced with the values from the sources below in the following priority order:
    a. IPEDS_HD
    b. Scorecard
    c. Census Tool Data
    d. The most recent version is checked and the latitude/longitude are used if the physical address is same

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/810

**Comment by desireeturner** [comment]
Removing this from the sprint.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/838

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by sonntag-adam** [comment]
In staging, testing passes QA.
