### ISSUE TITLE
CT Redesign: Create/Update sandbox location search service

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23654]
As a developer, I need to update the location search of the CT sandbox so that it searches all institution types and returns a comprehensive list of results.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The data points collected in AC2 are for use in future stories for display and/or filtering.
3. The results are returned using the current sandbox cards.
4. The search results are limited to single locations, ambiguous locations (ex. washington) are handled in a separate story #23959.
5. The following is out of scope for this story:
    a. The "Search by name" search functionality
    b. Autocomplete functionality
    c. Mapping functionality
    d. Institutions that are missing latitude or longitude values.

## Acceptance Criteria
1. The “Search by location” accepts a user entered location and searches all institution types (ex. schools, employers, training providers) by the following location details within the specified radius:
    a. City
    b. State
    c. City, State
    d. ZIP Code
    e. Country
2. The following data points are included:
    a. Institution Name
    b. Institution City
    c. Institution State
    d. Accreditation Type
    e. # GI Bill Students
    f. Institution Rating Score
    g. Number of Institution Ratings
    h. Tuition Benefit
    i. Housing Benefit
    j. Institution Type
    k. Institution Country
    l. Institution Caution Flags
    m. Institution Has Student Veteran Group
    n. Institution Offers Yellow Ribbon Program
    o. School Type
    p. Degree Type Offered
    q. Is HBCU
    r. Is gender specific
    s. Is religion affiliated
    t. Preferred provider (VETTEC indicator)
3. The distance menu:
    a. "within 10 miles" is replaced with "within 5 miles"
    b. has a "within 75 miles" option
    c. "within 50 miles" is the default selection.

## Technical Notes:
1. The search API takes the input, converts the results into lat/long, then hits GIDS and returns search results within radius.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/37IAGO4DHZG)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/817
https://github.com/department-of-veterans-affairs/vets-website/pull/17196

**Comment by sonntag-adam** [comment]
In staging, closing story.
