### ISSUE TITLE
CT Redesign: Add postgresql plugin to use lat and long for geographical searches

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23655]
As a developer, I need to add the postgresql plugin for latitude and longitude so that geographical searches can be done in the comparison tool.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. Previously completed research [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/schools-near-me/research.md)

## Acceptance Criteria:
1. The `earthdistance` plugin is installed in all environments.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222610/296059003/preview)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/809

**Comment by delli-gatti-michael** [comment]
local testing complete
