### ISSUE TITLE
Request for access to Google Analytics 

### ISSUE THREAD

**Issue by pamlo412** [department-of-veterans-affairs/va.gov-team#23663]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.

To access Google Analytics: if the user has a VA.gov email address or does not yet have a google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). VA.gov users and external users with email accounts that are not google based should select the option "Use my current email address instead".

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [ ] Domo
_Please list any additional requirements, if any._

## Date Required
_Please share the date you require access._

## Product Team / External Team / VA Office
_Please share the team you are on. This is helpful for auditing purposes._

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
Hello @pamlo412 I want to confirm that you need GA access only (not Domo) and, if so, what email address you'd like the Google Account access to be linked to.

**Comment by pamlo412** [comment]
Hi Lauren,
It looks like I already have access to GA and it's linked to my
***@***.*** email, which is a Google account. I don't know if
I need DOMO. Does it cover developer.va.gov (the Lighthouse program)?
That's the only site I'm interested in. If you don't know, I'll check with
a colleague this aft and get back to you.
Thanks,
Pam
-- 
*Pamela Lougheed, Ph.D., PSPO*
*Sr. Product Manager, Ad Hoc LLC*
*Lighthouse | VA API Program*
*(412) 638-5277*
*Visit *developer.va.gov* to learn more about the VA API Program.*

**Comment by laurensimpson14** [comment]
@pamlo412 I don't think there are any DOMO dashboards currently built for developer.va.gov, so you'll likely not need access. I'll go ahead and close this ticket, but feel free to open it back up if you do end up needing DOMO access.
