### ISSUE TITLE
[TTY]: Develop a consistent language and visual presentation for help text and icon

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#23664]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _See list of assignees_

## User Story or Problem Statement

We want to have a standard call to action with help text and an approved icon for TTY 711 links on VA.gov. This includes placements for:

- VAOS appointment cards
- Facility Locator
- VAMCs
- Content landing page right rail
- Other implementations we haven't accounted for yet

## Details

This ticket is a content + design item to gather the right call to action, help text, and Font Awesome icon for TTY. It's a small, self-contained snippet that should work for the multiple scenarios outlined above.

## Acceptance Criteria

- [ ] Call to action text is defined
- [ ] Help text is defined
- [x] Font Awesome icon is identified and approved through VA license ( https://fontawesome.com/v4.7.0/icon/tty )
- [ ] Visual design is created and approved
- [ ] Visual design is added to Sketch file and/or design system guidance

**Comment by humancompanion-usds** [comment]
This strikes me as a Design System issue given that we control the design of va-telephone and we now have va-icon. We've already identified an icon we can bring in for TTY. [We don't use an icon currently](https://design.va.gov/storybook/?path=/docs/components-va-telephone--tty#tty) but, we could!

**Comment by humancompanion-usds** [comment]
The TTY icon has been added: https://design.va.gov/foundation/icons#appointments

**Comment by caw310** [comment]
Closing as we have a TTY icon that is equivalent to the FA one. If this is still an issue, open a new bug.
