### ISSUE TITLE
CT Redesign: Add Map control and update search results view for Location search

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23686]
As a developer, I need to the location search results view to display a map and corresponding cards so that the user has a visual understanding of the institution location and the functionality can be usability tested.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. This story assumes a specific location is found; ambiguous locations (ex. washington, springfield, etc) are out of scope of this story and covered by #23959.
3. Manipulating the map and using it to search is out of scope of this story and is covered by #24261.

## Acceptance Criteria
1. The search results are displayed:
    a. In a list
    b. On a map
2. For the search results displayed in a list:
    a. the card displays a letter corresponding to the map pin.
    b. the card displays the distance (in miles) from the entered location.
    c. The order the cards are returned is from closest to the user entered search location to the furthest away within user the specified distance.
3. For the search results displayed on the map:
    a. the map displays a pin for each institution that meets the search criteria.
    b. When a pin is clicked on the map, the corresponding card is brought into view in the search results list.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/37IAGO4DHZG)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/821
https://github.com/department-of-veterans-affairs/vets-website/pull/17247

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/1921)

**Comment by delli-gatti-michael** [comment]
Closing this out
