### ISSUE TITLE
Analytics Implementation or QA Support for [Virtual Agent]

### ISSUE THREAD

**Issue by katieho-va** [department-of-veterans-affairs/va.gov-team#23693]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

```
Google Analytics implementation. Our suite of analytics for the Virtual Agent will be:
- Google Analytics
- Medallia (for feedback)
- Power Virtual Agent (Microsoft tool) will track most of our product metrics 
```

- Who is this request for?

    - Joanne Esteban
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._

```
- Luciana Morais Luciana.Morais@va.gov (Virtual Agent Product Owner)
- Katie Ho Kathryn.Ho@va.gov (Project Manager)
```
    
- What team/project is this work for?
    _this adds context for the data_
    
    - Virtual Agent - as part of VEO Omnichannel Modernization project. 
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    
    _Identify if PII is passed in URL or title tag_ No PII 
    
    -  https://staging.va.gov/virtual-agent/ 
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - June 1st launch for our proof of value (POV)

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - https://staging.va.gov/virtual-agent/ 
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - All actions will be on https://staging.va.gov/virtual-agent/   

The analytics we’re looking to track will be a mixture of the analytics from the va.gov site and from the chatbot specific analytics listed below.

```
- Engagement rates (PVA Stats)
     - Number of users who interact with the new virtual agent that get the link
     - Number of users left without interaction
     - Number of users who ask multiple questions in one session
     - Number of users who ask the same question (in variations) during one session
- Satisfaction rates
     - Number of times the virtual agent able to answer a question
     - Number of times the virtual agent was not able to answer a question?
     - Feedback on users how how they veterans feel about the interaction (captured by Medallia)
     - Feedback on users on what could be improved (captured by Medallia)
     - Feedback on users on if they are likely to use this again
- Perceived human requirements
     - Number of users who directly ask to speak with a human (e.g., phone number)
     - Number of of users who still want to speak with a human after an interaction
     - Number of crisis-related statement/question
- Content requests
     - Most asked about topics by users
     - Types of tasks did users ask the bot to do 
- Debugging (dev use)
     - Number of times there is a webchat connection success
     - Number of times there is a webchat connection failure
```

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - We are not using sample users to test in the bot. Please reach out to the team to meet with team’s QA.

- Certain conditions/responses that need to be reviewed

    - N/A

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by katieho-va** [comment]
Hi @laurensimpson14 @joanneesteban! Just wanted to check in on our ticket– let me know if you need any other information from the team.

**Comment by joanneesteban** [comment]
Closing this ticket, as Virtual Agent will no longer be launching on production, per [this comment](https://dsva.slack.com/archives/CBU0KDSB1/p1621890618370400). @katieho-va please feel free to reopen if you end up launching to production!
