### ISSUE TITLE
Content Build Separation - Investigate soft-launch capability

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#23717]
## Description
In order to support the content build separation work currently underway by FE Tools team, and to limit the potential of breaking changes and the need for after-hours work, Ops will investigate the ability to soft-launch the deployment of this feature with special configuration of reverse proxy, et al infrastructure components. 

## Background/context/resources
[Launch checklist for content build separation 
](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/22451)

## Technical notes
Maybe IP detection possible in revproxy? 

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [X] Please attach your team label and any other appropriate label(s) 
- [X] Please attach the needs grooming tag if needed
- [X] Please connect to an epic

**Comment by timwright12** [comment]
Relevant slack thread https://dsva.slack.com/archives/C01S39QMSSV/p1619569195069800
