### ISSUE TITLE
Lighthouse Request - 526 Claims Id's

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#23724]
Request to provide Premal a list of claim Id's for the 526 claims that we've processed via va.gov. (Low priority)

**Comment by annaswims** [comment]
all form526_submission_id's submitted from VA.gov for all time, no PII necessary.

**Comment by annaswims** [comment]
Emailed to Premal. 

552,358 submissions!

`ruby
fs = Form526Submission.where("submitted_claim_id is not null").order(:id).pluck(:submitted_claim_id, :created_at)
IO.write("form526_submissions.csv", fs.map(&:to_csv).join)`

**Comment by vhenry07** [comment]
Closing complete.
