### ISSUE TITLE
VRRAP: Remove prod flag for UI content tweaks in 23496

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23720]
As a developer, I need to remove the prod flag created for #23496 so that the new functionality is available in production.

## Assumptions:
1. EDU signed off on updates as of 5/10/21.

## Acceptance Criteria
1. The functionality created in #23496 is available in production.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17261
