### ISSUE TITLE
General Analytics Request for VA.gov home page scrolling data

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-team#23733]
# Metrics Reporting Request
@cindymerrill posted this request on #vfs-analytics on 4/23/2021 and was asked by @bsmartin-ep to submit it in an issue.

## Description
@cindymerrill would like to know about users' scrolling behavior on the VA.gov home page. Cindy is conducting baseline user research (April 26 - May 4) on the current VA.gov home page and how people find what they're looking for, and in tandem, exploring analytics data to compare with research findings.

This research is planned within the context of the Public Websites team and the larger Unauthenticated crew, but it may also provide insights for the Authenticated teams and overall website information architecture and layout. 
    
This ticket is requesting analytics data on **how far down users scroll on the VA.gov home page** 
in the form of a one-time metrics report.

## Timeframe for Analytics Requested
Not sure. Perhaps data after 01/01/2021 would be appropriate.

## Analytics to Track Down
I would like to know what percent of users…
- don't scroll at all
-  scroll only as far as the top 4 quadrants and the row of photos
-  scroll down below the row of photos
-  scroll all the way down to the footer

## Which Product Questions are you trying to answer?
- How far do users scroll on the VA.gov home page? 
- What percent of users don't see anything below the photos? 

## Additional Comments
I would like to have this data by Friday April 30, if possible. 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@cindymerrill -

To examine things at the hit scope, I would compare [the total scroll events on the homepage](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2F%22,0%5D%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Scroll%20Depth) with the [total pageviews in the same timeframe](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2F/).

|     |     |
|-------------|-------------|
![image](https://user-images.githubusercontent.com/62304138/116486365-739b9b00-a85b-11eb-9b12-ef982fd412b0.png)|![image](https://user-images.githubusercontent.com/62304138/116486380-7bf3d600-a85b-11eb-9d67-365cf5344adb.png)

Reminder a "unique" metric in GA (like a pageview or event) just means it is counted once per session.

--------------------
Next - I would build a quick custom report to see User data for this event.

You can [use this import link](https://analytics.google.com/analytics/web/template?uid=H-qEHBTFSoqH0Mz8IR2uyw) to add the custom report your GA account.  Make sure you import into the "All VA.gov Website Data [Production]" view (see note at bottom).

![image](https://user-images.githubusercontent.com/62304138/116486791-6a5efe00-a85c-11eb-905e-2a780094a188.png)

This will take the (hit scope) events and give you user metrics.  So essentially what percent of users - **at any point in our history for them** - manage to scroll this % on the homepage.  That's your numerator.  To get the total users who visit the homepage in the same time, you can use this custom segment:

https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_.useg=builtin1,userDnQcFkSST4iXl__TLG-4EA/

![image](https://user-images.githubusercontent.com/62304138/116486911-b611a780-a85c-11eb-9b6d-d0698d8fce8f.png)

----------------------

*One last thing - you _probably_ want to do this on "All VA.gov Website Data [Production]".  But in case you just want to examine data for the "modernized" va.gov - so not MHV etc - you would want to switch to the "WBC - VA.gov Modernized Content" view.

----------------------

This covers the metrics we have.  To correlate this with certain breakpoints ("What percent of users don't see anything below the photos?", you would need to watch the console on different screen and viewport sizes.  Let me know if you want me to show you how to do that.

**Comment by cindymerrill** [comment]
Thank you for all of this info, @bsmartin-ep! I have a few questions about it:

1.  On the total scroll events on the homepage, that tells me that only about 10% of users scroll all the way to the bottom of the page, 31% scroll 3/4 of the way down, and 58% scroll halfway. Is this a correct interpretation?
2. Why would you need to compare the total pageviews in the same timeframe? Doesn't seem like I need that.
3. For the custom view you created, how is this different from the "total scroll events on the homepage" link above? The numbers are slightly different but in the same ballpark (i.e., about 11% for scrolling all the way to the bottom of the page).
4. I'm looking for scrolling data for only the VA.gov home page, without including data for all the other content pages and MHV. Looks like "All VA.gov Website Data [Production]" includes all pages, not only the home page; is this correct?
5. To answer the question "What percent of users don't see anything below the photos?", what do you mean by "you would need to watch the console on different screen and viewport sizes"? I would like to know how to do that please.

**Comment by cindymerrill** [comment]
Hi @bsmartin-ep ! Just checking in that you saw my reply (see above) about the VA.gov home page scrolling data that you provided. I got a strange error from github, so it's possible that my comment wasn't posted correctly and tagged to you.

When you have a chance, I'd like to hear your replies to my questions. Thanks!

**Comment by joanneesteban** [comment]
Hi @cindymerrill Thank you the notice, and for your patience. 

For context, our Google Analytics experts have limited part time hours, and we have been down on available hours for the last few weeks due to personnel changes.  

This has been announced in Team of Teams, but would you be able to attend the Collaboration Cycle office hours (Wednesdays, 11:30am-12pm EST), and we can help in real time? 

CC: @bsmartin-ep @chloedotbrown

**Comment by cindymerrill** [comment]
I have another meeting during that time, but I can try to be there tomorrow
anyway.

--Cindy

**Comment by cindymerrill** [comment]
What is the videoconferencing link for the Collaboration Cycle office hours?

**Comment by joanneesteban** [comment]
Thanks, @cindymerrill . The link & password can be found [here](https://dsva.slack.com/archives/CBU0KDSB1/p1622042232033100).

**Comment by bsmartin-ep** [comment]
@cindymerrill -

> 1. On the total scroll events on the homepage, that tells me that only about 10% of users scroll all the way to the bottom of the page, 31% scroll 3/4 of the way down, and 58% scroll halfway. Is this a correct interpretation?

If we're looking at hit / event scope...

For 2021-01-01 to 2021-05-31...

Event Label | Page | Total Events | Total Homepage Pageviews | Percentage
-- | -- | -- | -- | --
50% Viewed | ww<span></span>w.va.gov/ | [1,963,106](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2F%22,0%5D%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Scroll%20Depth&explorer-table-tableMode.selected=data/) | [22,350,956](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2F/) | 8.78%
75% Viewed | ww<span></span>w.va.gov/ | [1,044,481](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2F%22,0%5D%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Scroll%20Depth&explorer-table-tableMode.selected=data/) | [22,350,956](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2F/) | 4.67%
100% Viewed | ww<span></span>w.va.gov/ | [320,914](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22EQ%22,%22www.va.gov~2F%22,0%5D%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Scroll%20Depth&explorer-table-tableMode.selected=data/) | [22,350,956](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2F/) | 1.44%

I linked the metrics to their GA equivalents if that helps.

> 2. Why would you need to compare the total pageviews in the same timeframe? Doesn't seem like I need that.

I'm not sure I understand.  I'm comparing the total number of scroll events (numerator) to the total number of homepage pageviews (denominator) to get a hit / event scoped % of `scroll events per homepage pageview`.  Or am I misinterpreting your question?

> 3. For the custom view you created, how is this different from the "total scroll events on the homepage" link above? The numbers are slightly different but in the same ballpark (i.e., about 11% for scrolling all the way to the bottom of the page).

The custom report I created is user scoped vs hit / event scope.  Which means it gives a count of users who - at any point in the history of the user - scroll to that % of the homepage.  We have to use a custom segment to get the denominator in this case.

The scope really boils down to the question you are asking - "How many users ever scroll to x% on the homepage?" vs "How many views of the homepage have a scroll of x%?"

A similar table as above in user scope...

Event Label | Users | Total Homepage Users | Percentage
-- | -- | -- | --
50% Viewed | 1,444,547 | [4,980,720](https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&_.useg=builtin1,userDnQcFkSST4iXl__TLG-4EA/) | 29.00%
75% Viewed | 849,260 | [4,980,720](https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&_.useg=builtin1,userDnQcFkSST4iXl__TLG-4EA/) | 17.05%
100% Viewed | 276,137 | [4,980,720](https://analytics.google.com/analytics/web/#/report/visitors-overview/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&_.useg=builtin1,userDnQcFkSST4iXl__TLG-4EA/) | 5.54%

...which - as you would expect - is a bit higher than hit scope.  If a user _ever_ scrolls to a certain point, it counts.

> 4. I'm looking for scrolling data for only the VA.gov home page, without including data for all the other content pages and MHV. Looks like "All VA.gov Website Data [Production]" includes all pages, not only the home page; is this correct?

Correct.  All VA.gov is _everything_ - MHV, www, etc.  WBC Modernized is the just the "modernized" www.va.gov.

> 5. To answer the question "What percent of users don't see anything below the photos?", what do you mean by "you would need to watch the console on different screen and viewport sizes"? I would like to know how to do that please.

Does [this GTM preview link](https://tagassistant.google.com/#/?id=GTM-WFJWBD&url=https%3A%2F%2Fwww.va.gov%2F&source=TAG_MANAGER&gtm_auth=U8PS5TuF5Gb4-4lUH65y9Q&gtm_preview=env-8) work for you?  If so, scroll to down and you'll see scroll events in the preview window...

![image](https://user-images.githubusercontent.com/62304138/120405653-0f1aa280-c317-11eb-925c-5f9e5058f282.png)

You'll have to click the `dataLayer.push` code chunk at the top to see the %.

![image](https://user-images.githubusercontent.com/62304138/120405746-4be69980-c317-11eb-8df2-dd435b628463.png)

Let me know if the GTM preview doesn't work, and I can walk you through examining the dataLayer in the console.

**Comment by bsmartin-ep** [comment]
Links from today...

- [Homepage pageviews by screen resolution](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.screenResolution&_r.drilldown=analytics.pagePath:www.va.gov~2F/)
- [Homepage pageviews by device category](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20210101&_u.date01=20210531&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.deviceCategory&_r.drilldown=analytics.pagePath:www.va.gov~2F/)
- [Custom report template](https://analytics.google.com/analytics/web/template?uid=vDafMjetThOkWY6zykscqg) - 2 tabs comparing homepage scroll events by device category and screen resolution

**Comment by joanneesteban** [comment]
@cindymerrill Hi! Are you all set/can we close out this ticket?

**Comment by cindymerrill** [comment]
Yes, I am. Thanks for checking, @joanneesteban !

**Comment by joanneesteban** [comment]
Thanks, @cindymerrill & @bsmartin-ep ! Closing this ticket.
