### ISSUE TITLE
Plan second dose-add back J&J

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23737]
## Description
Due to latest CDC & FDA guidance, add back references to J&J vaccine on the "Plan second dose" page in the vaccine flow.

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/second-dose.md) 
![second_dose_page__2_.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/4698f909-d127-4922-a0af-88d20fc6f0df)

## Definition of Done
- [ ] All acceptance criteria are met

- [ ] [Documentation/screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md) are updated

**Comment by laurenernest** [comment]
@LanceGundersen Can you update the flow documentation screenshot please?

**Comment by LanceGundersen** [comment]
@laurenernest completed
