### ISSUE TITLE
Error | No premium MHV account

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23732]
## User story
As a user, if I cannot see secure messaging within the mobile app, I want to know what I need to do in order to upgrade my account.

## Acceptance Criteria
1. Display a generic error for Secure Messaging pages when an MHV identifier is not found within MPI during login. This is triggered by the following scenario:
     - If secure messages=false in the authorized_services list, AND
     - If appointments=true in the authorized_services list
2. Create UX/UI based on the linked designs
     - Header 2: "You're not currently enrolled to use Secure Messaging"
     - Content is hard-coded
3. Hyperlink: "Learn how to upgrade to a My HealtheVet Premium account"
     - Selecting this button opens the following link, out-of-app, in the device's browser: https://www.myhealth.va.gov/web/myhealthevet/upgrading-your-my-healthevet-account-through-in-person-or-online-authentication

## Designs
https://adhoc.invisionapp.com/console/share/YM10HVPXJE7V/600511919

## Discovery ticket
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21088

## Accessibility Implementation Guidelines 

- Mark "You're not currently enrolled to use Secure Messaging" as Header 2

**"Learn how to upgrade" link**
- Title= learn how to upgrade to a My HealtheVet Premium account
- accessibilityRole= “link”

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by narin** [comment]
Note for mobile devs:

I've added secure messaging to the list of `authorized_services` that come back in the `/user` profile API call. If it is missing from this list, the user doesn't have access to SM, we can display the relevant copy, and prevent any SM api calls.

**Comment by drjecker** [comment]
Here is the link for the: [Learn how to upgrade to a My HealtheVet Premium account](https://www.myhealth.va.gov/web/myhealthevet/upgrading-your-my-healthevet-account-through-in-person-or-online-authentication)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by bessgreen** [comment]
QA: test with 1401, 1402, 1413, or 1414

**Comment by digitalken** [comment]
PASS 5/25/2021 - Looks good on Android and iOS.  Samsung "vah" bug got added to...  Closing.
