### ISSUE TITLE
migrate EC2 instances to latest families

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2373]
We've made a pass to get a good number of the more resource-intensive services on latest class, but we're coming up on a time where DSVA is wanting to renew some EC2 reserves so we should get everything to the latest instance families (m5/t3/r5/etc).

This shouldn't be done with a single PR for all as things like mount locations can change from m4 -> m5, for example. Let's make a list and iterate through them, redeploying through environments as we go.

**Comment by tskinn** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/5774 updates lots of lower environments.

Verified with working deployment:
- [ ] content-preview-dev
- [ ] content-preview-staging
- [ ] gi-bill-data-service-vagov-dev
- [ ] gi-bill-data-service-vagov-staging
- [ ] jumpbox-vetsgov-staging
- [ ] revproxy-vagov-dev
- [ ] revproxy-vagov-sandbox
- [ ] revproxy-vagov-staging
- [ ] scratch-dev
- [ ] vets-api-server-vagov-dev
- [ ] vets-api-server-vagov-staging
- [ ] vets-api-worker-vagov-dev
- [ ] vets-api-worker-vagov-sandbox
- [ ] vets-api-worker-vagov-staging

**Comment by tskinn** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/5780 updates rest of t2 types

Verified working deployment:

- [ ] content-preview-prod
- [ ] grafana-vagov-utility
- [ ] jumpbox-vetsgov-prod
- [ ] sentry-cron-vetsgov-utility
- [ ] va-socks-utility
- [ ] vets-api-server-vagov-prod
- [ ] vets-api-server-vagov-sandbox

**Comment by tskinn** [comment]
prometheus:
- [x] dev
- [x] staging
- [x] sandbox
- [x] prod
- [x] utility

**Comment by wyattwalter** [comment]
Looks like these are all done 👍
