### ISSUE TITLE
tune ASG rules for revproxy for cost optimization

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2374]
The current ASG rules for the revproxy were kind of tuned for the re-launch of va.gov, but appear to be scaling up a bit more aggressively than we really would need to be. I'd like to have someone take the time to make a pass at checking if we can lower the thresholds there and possibly lower the minimum number.. Just need to make sure we get at least one instance in each AZ.

**Comment by tskinn** [comment]
I've been lowing the minimum instance count to 3 and monitoring asg metrics and elb metrics. Here is what that looks like now

![screenshot_2019-10-24-093841.png](https://images.zenhubusercontent.com/56d7378f6caf56c9d38d2503/fe1ae6a3-fe6e-41fd-9a8d-4ecb06ef6b50)

![screenshot_2019-10-24-093851.png](https://images.zenhubusercontent.com/56d7378f6caf56c9d38d2503/bee8838d-fc3f-4851-a170-2b334f4b24bd)

**Comment by tskinn** [comment]
and after almost a week:
![screenshot_2019-10-28-155542.png](https://images.zenhubusercontent.com/56d7378f6caf56c9d38d2503/13b5364c-a225-4ffb-b633-1874a3450d49)![screenshot_2019-10-28-155552.png](https://images.zenhubusercontent.com/56d7378f6caf56c9d38d2503/51e5f2fb-dcb1-4508-80f1-2b6a233321ee)

**Comment by wyattwalter** [comment]
I think we've done what we can do on this for the moment and are in a better state.
