### ISSUE TITLE
CT Redesign: Research Workshop - Search / Sandbox

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23748]
Identify target participants
Establish goals for testing effort
Identify themes for conversations (discussion guide building blocks)

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1620211255425/9bd661947a68987047d6231c5ba58441d89a2dd0
