### ISSUE TITLE
CT Redesign: Profile Page IA	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23746]
Mural is created / updated with proposed profile page structure 

* Review existing profile page IA (all types of institutions) 
* Identify areas of concern 
* Discuss solutions for revisions / updates w UX team 
* Pull in additional stories for Sp73 as needed (labels, interactions)

**Comment by JenLJ** [comment]
Card sort link: https://BAHdXL.optimalworkshop.com/optimalsort/78831tq0
