### ISSUE TITLE
CT Redesign: Search Cards Solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23747]
Mural is created with working version of search results card structure 	

* Review existing search results cards (all types of institutions) 
* Identify areas of concern 
* Discuss solutions for revisions / updates w UX team 
* Pull in additional stories, as necessary

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1620131600634/4057ee167fef2eef666968fd9ab35a6f7a2a446a
