### ISSUE TITLE
CT Redesign: Comparison Tray  Layout and behavior - Team Sync	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23745]
Comparison Tray prototypes with improved layout & behavior are reviewed with UXBA	

* Prototype is shared with relevant team members  
* Feedback is collected 
* Prototype is tweaked, per input OR additional stories are written, as necessary

**Comment by amyknox** [comment]
@watersemma - nice job on this work y'day!
