### ISSUE TITLE
CT Redesign: Comparison Tray - Layout and behavior - Solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23741]
Document approaches to improve layout & behavior of Comparison Tray on landing page

* Explore possible ways to address the challenge on mobile devices and on desktop  
* Document approaches with greatest potential 
* Discuss pros/cons with UX team

**Comment by JenLJ** [comment]
Mural: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1617710116724/06fd7c751f02d73b05dc3065221dca2cfa5a47e7
