### ISSUE TITLE
EDU Forms / STEM 10203: Eligibility Update -  Prototype

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23751]
STEM Prototype showing expanded eligibility is updated	

* Prototype is updated to incorporate EDU updates on confirmation page 
* Prototype is reviewed w UX team 
* Updates from UX are incorporated

**Comment by JenLJ** [comment]
Prototype: https://bahdigital.invisionapp.com/share/8RIAGQUSXU3
