### ISSUE TITLE
EDU Forms / STEM 10203: Eligibility Update - Content

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#23750]
Content for expanded eligibility has been drafted 	

* Content is drafted 
* GH Doc is shared internally 
* Respond to any questions

**Comment by JenLJ** [comment]
Content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md
