### ISSUE TITLE
Access for Cameron Testerman

### ISSUE THREAD

**Issue by cbtkc** [department-of-veterans-affairs/va.gov-team#23754]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Cameron Testerman
- Please Provide your email.
   > cameron@oddball.io
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP/BE Tools, Software Engineer, Oddball.io

- Requesting SSH key authorization?
   > YES / NO 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDphcbhOLkI+9ChyWyyWyKk+lH9X1EAmdJvFm5RuGJouZcTrSsvws0dG/W+MoBO1pNioyvKo77JOQQcfShGSn2RZ6bsf03BL1lINmLX1/7+fgZXCEYJVUxB+15rJCDk6+kfdfU4LLTl4D8JbXWs8UP3cfnhE3Mo43x9VMf1584omHxuGlwI+/3nAZM6PWNAeXMrCSBKUJwGToBOafD941FaI42BrVUWGSv0yqxuVKQCFbKTwgNGmNAdP2fG2f9oUmF/Dm8snie0SXJlojHQy4o4GgA3g1DeM1FlFkGnQXicrJZmI9cji+ApqKbbXKuM5F1yyRy9Yb4uYTDI8uKrdvqD cameronbtesterman@gmail.com
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > Need access to standard set of permissions for VSP BE Tools team software engineers, for accessing logs, troubleshooting issues, etc.

**Comment by mleclerc00** [comment]
### AWS Access

User: Cameron Testerman
COR: Jeffrey Hayter
Approval required: @Jeff-Hayter

**Comment by mleclerc00** [comment]
Hi @camerontesterman 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

Let me know if you are able to set everything up so I can close out this ticket and if you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by jbritt1** [comment]
@Jeff-Hayter, @cbtkc has been around the platform for a long while now, any way we can expedite this one? Thanks in advance for any info.

**Comment by nsmith1982** [comment]
@drorva could you approve this?

**Comment by drorva** [comment]
Approved

**Comment by jbritt1** [comment]
Temporary credentials passed to user.
