### ISSUE TITLE
Add Asha Gross and Steve Batson to DSVA Slack as Full Member

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#23758]
Please add the following new people supporting VSA as full members to the DSVA Slack:

sbatson@governmentcio.com
asha.gross@adhocteam.us

Thank you!

**Comment by LEHigley** [comment]
@YanaRoy they're both showing as active members

**Comment by YanaRoy** [comment]
@LEHigley that's odd! but i'll take it :) thank you
