### ISSUE TITLE
Update the Liquid Template Testing Framework documentation with information about how to use the DOM Testing Library

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#23762]
## Issue Description
Update the Liquid Template Testing Framework with information about how to use the [DOM Testing Library](https://testing-library.com/). 

This ticket is derived from [ticket #21651](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/21651)

---
## Tasks
- [x] Update the Liquid Template Testing Framework documentation 

## Acceptance Criteria
- [x] The Liquid Template Testing Framework documentation is updated

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/va.gov-team/pull/23764

This ticket is complete.

**Comment by pjhill** [comment]
Nicely done -- thanks for the quick review, @billfienberg !

@holdenhinkle, Have we notified the platform personnel / teams that were interested in this capability?

**Comment by holdenhinkle** [comment]
Yes, I notified Michael Pelz-Sherman and he's spreading the word.

**Comment by pjhill** [comment]
Merged and requesting team members notified
