### ISSUE TITLE
Assess the implications of polyfills

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#23768]
## Issue Description

Our Web Components need a Promise polyfill in order to work properly in IE11. The polyfill was added to the `web-components` loader in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16925

This was modeled after the `core-js` polyfill that is added at the platform level, because `polyfills.js` wasn't sufficient enough.

---
## Tasks
- [ ]  Investigate why there are two polyfill bundles outside of the web component loader
- [ ] Assess the performance impact of having a duplicate polyfill in with the web component loader

**Comment by bkjohnson** [comment]
We no longer support IE11, so these polyfills should not be needed anymore.

**Comment by caw310** [comment]
Closing as this is an old ticket and it seems not needed.
