### ISSUE TITLE
Access for Teesh Shahi

### ISSUE THREAD

**Issue by Teesh** [department-of-veterans-affairs/va.gov-team#23766]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Teesh Shahi
- Please Provide your email.
   > teesh.shahi@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA Startups, Ad Hoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0TpmBKFcchGvfcRSZIm56NDpj10yYFV/dqip2iCzOVs9vax6d5JG89BdrPJBA4n8GDG0qv86D8pRT+adUlm7uP676ACcqxRcegz2LLE2kDCQjHKrKrHMaUHVKOyZ1vvVekz3jmbwQWJpAsE+8vcrKDu/UAOayoBQ1FwmE5c3B+zNoxL+A7f9WWE3g/5e7TpW6eYSN4ajpRaSVRPZWTU7gVramEWLLMFa4Xqb4VQTqumRYZDb2KuEPS2Fe/GMdCqB50eT0HgkhqbqlLT33mtrlxciNU8qYx7kiNjDBiYwb+FVKwYTfKT886DCZyTWbXYyDTChbUplHN1ZVA9FGNqdPdc0RtoMJXpFaGOJtwejvwJlFzQnlBSmRMUVnziBsGtKWFLtXIwXDfmB8NvqZ8M1/FJ88EaMREY/q427K0yzw71sAqOe32s+LlK2nMX2qlYONH7XaUmEC0SzD1Vk/Bl2ibBdlx8JGnPGbZeoCukRjj/JjPzopDmFT/QaT83rO7ns= priteeshshahi@Priteesh-Shahi-Macbook.local
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  > CloudWatch (logs), SSM (rails console), any other common services for vets-api backend dev

**Comment by mleclerc00** [comment]
### AWS Access

User: Teesh Shahi
COR: Crystal Moultrie
Approval required: @Jeff-Hayter

**Comment by mleclerc00** [comment]
Hi @Teesh 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

Let me know if you are able to set everything up so I can close out this ticket and if you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by Teesh** [comment]
I was able to access the test curl endpoint in the SOCKS tutorial. Thank you

**Comment by mleclerc00** [comment]
Jeff let me know that we need approval from Crystal Moultrie to move forward with AWS access but I can't seem to fin their user to ping in this thread

**Comment by mleclerc00** [comment]
I have reached out to Crystal Moultrie via email and will proceed once access is approved.

**Comment by cgreim** [comment]
@mleclerc00 Hi! Have you been able to get approval from Crystal? This is a blocker for our team.

**Comment by mleclerc00** [comment]
Unfortunately I have not heard back, but I will follow up again.

**Comment by mleclerc00** [comment]
@mchelen-gov 

Circling back on this aws request for approval

Thanks!

**Comment by mchelen-gov** [comment]
Hi @Teesh, who is your vendor onboarding representative? This is the person from your company or the primary contractor who helped you onboard at VA.

**Comment by mchelen-gov** [comment]
Closed for inactivity, please reopen if still needed.

**Comment by lexicalninja** [comment]
@Teesh Do you still need this or can they leave it closed?
