### ISSUE TITLE
Create PII guidelines

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2377]
As a VFS team, I want to know more about PII so that I can code to the privacy expectations of the platform

AC:
- [ ] Publish the guidelines in GH
- [ ] Distribute the guidelines
- [ ] present at engineering leads meeting
- [ ] add to engineering onboarding meeting slide deck

**Comment by johnpaulashenfelter** [comment]
From @wyattwalter https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md

**Comment by johnpaulashenfelter** [comment]
Updated presentation to link to it

https://docs.google.com/presentation/d/1qewAANeGvQSTfXK4m40lO2N0-S9IaCfl7JlZY_0EI6A/edit#slide=id.p7
