### ISSUE TITLE
[FE] My VA: "Learn how to apply for education benefits" link text is incorrect on staging

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23779]
## Background
On My VA dashboard on staging, in the Apply for VA benefits section, under the Education and training subsection, there is a link that reads "Learn how to apply for education benefits." This copy is incorrect. It should read "Learn how to apply for VA education benefits."

## Steps to reproduce
1. Log in to staging with user 10
2. Scroll to Apply for VA benefits section
3. Locate the Education and training subsection
4. See that the link at the bottom of the small paragraph reads "Learn how to apply for education benefits" when it should say "Learn how to apply for VA education benefits."
5. Compare to text as indicated in [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/my-va-copy.md) and [invision](https://vsateams.invisionapp.com/console/share/SH10HT8JCKYM/600538559)

## Screenshot
Staging:
![image](https://user-images.githubusercontent.com/45603961/116135505-38546d00-a69f-11eb-980e-63a218466ad6.png)

## Tasks
- [x] Correct link text to read "Learn how to apply for VA education benefits" instead of "Learn how to apply for education benefits"

**Comment by erikphansen** [comment]
Can be validated once commit `0e9d6ebc7cbfbd01608443ee31cc550d85528388` is on staging. You can check to see if it's on staging at https://frontend-support-dashboard.vercel.app

**Comment by ajakabcin** [comment]
Confirmed on staging
