### ISSUE TITLE
Content Feedback - Staging review - CLP Trust VA

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#23778]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

**Comment by peggygannon** [comment]
Content feedback for Trust CLP staging review. Please let me know if you have any questions. 


QUESTIONS
1.	Should the "Get updates from Veteran Affairs section" be reformatted as a right rail to align with how we present this type of information on VA.gov? 
2.	Will there be number percentages populated in the  VA-wide trust section? 


-----

Must feedback
1.	In first content block, Veteran should be> Veterans
2.	Please add “that” to this sentence: 79% of Veterans responded “that” they trust VA
3.	March 30th should be> March 30, we don't use ordinal numbers, per style guide 
4.	Spell out millions:  6M should be>  6 million, to follow plain language guidelines and readability 
5.	Near-future should be> near future
6.	Under this accordion: What is being done with Veteran feedback? 
-	Fix typo: your should be>  “you”         if you tell VA
-	In-order-to should not have hyphens. It should be in order to
7.	“This page is for” component, please update “their families” to Family members to align with treatment throughout VA.gov


------

Should feedback

1.	I don’t think you need the FAQ above the Frequently asked questions H2. Seem duplicative

2.	Accordion:  "Who measures customer experience at VA"
I recommend we don’t use "/ " special characters in content to readability and accessibility. I recommend rewriting to:   
Ease and simplicity, efficiency and speed, employee helpfulness, equity and transparency, satisfaction, and confidence and trust. 

3.	Accordion: "Why does ease, effectiveness, and emotion matter?" 
This accordion doesn’t address the question until the last sentence. It mostly focuses on Integrity.

 Should Integrity be included in question? I recommend either tweaking the answer to include more about ease, effectiveness, and emotion,  or tweaking the question to add  Integrity. 

---------

Consider feedback

Below is a suggested rewrite to the content under "Why this matters to you" to make this plain language and to align with VA.gov voice and tone. 

The Veteran feedback we received in more than 6 million surveys enables VA to make enhancements to the way we provide care, benefits, and services. Improving customer access to our resources with equity starts with listening to the Veteran community and then designing tailored experiences and responses to meet their individual needs.

**Comment by johnhashva** [comment]
@peggygannon the VEO CLP lead -- Tim Hudak -- plans to make most if not all of these suggested changes and really appreciates the feedback.   Thank you.

**Comment by peggygannon** [comment]
Thanks, @johnhashva for the followup!

**Comment by brianalloyd** [comment]
Great feedback and thanks for the support, close ticket based on launch readiness status.  Thanks.
