### ISSUE TITLE
CLP Redirect Request: VA.gov/trust

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#23783]
### Instructions
We want to capture the following URL variations to permanently 301 point to the new, to be published Campaign Landing Page for VA Trust initiative at:
www.va.gov/veteran-trust-in-va/

Additional guidance about this request is seen here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/clp-truth.md

### Requesting team info
*John Hashimoto for VEO (the business user/stakeholder for the CLP)*

### Implementation date
Date new URL(s) will be live: April 28, 2021

Destination page will be live on April 28: 
www.va.gov/veteran-trust-in-va/

Please indicate when the change/redirect(s) needs to be implemented"
- [x] Other - Please indicate timing :  As soon as April 28, no later than April 29

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect URLs to be created
---  |  ---
https://www.va.gov/initiatives/veteran-trust-in-va | https://www.va.gov/trust 
https://www.va.gov/initiatives/veteran-trust-in-va | https://www.va.gov/Trust

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [ ] Implementation team: Implementation team completes work 
- [ ] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
@brianalloyd this is good to go from my standpoint.

**Comment by brianalloyd** [comment]
Thanks @mnorthuis I'm pulling this in for action now.  Thanks.  CC @johnhashva

**Comment by kelsonic** [comment]
PR is open: https://github.com/department-of-veterans-affairs/devops/pull/9065 won't merge until we get the green light from either of you @brianalloyd @johnhashva

**Comment by johnhashva** [comment]
@brianalloyd and @kelsonic just formalizing here; our IA team would prefer the va.gov/trust URL NOT be used as the vanity URL/redirect -- and is recommending va.gov/trustva or va.gov/trust-va.  Will post here and in the CLP/PW channels when we get the final word on this one.

**Comment by brianalloyd** [comment]
Thanks @johnhashva we'll standby for confirmation, thanks for working the details.

**Comment by johnhashva** [comment]
5/5 UPDATE: @brianalloyd and @kelsonic just formalizing here that we -- via Site IA-Content team guidance --  are now recommending that Tim/VEO go with one of the following vanity URLs as opposed to va.gov/trust (va.gov/Trust) because it is too broad.

- va.gov/veteran-trust-in-va
- va.gov/trust-va
- va.gov/trustva

I'm still awaiting word back from Tim on this and will update the ticket when we get final word,

**Comment by johnhashva** [comment]
5/12 Update:   Final word on redirect is:   we need to set up are va.gov/Trust and va.gov/trust which should point to the destination  URL https://va.gov/initiatives/veteran-trust-in-va

**Comment by kelsonic** [comment]
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/trust | https://www.va.gov/initiatives/veteran-trust-in-va
https://www.va.gov/Trust | https://www.va.gov/initiatives/veteran-trust-in-va

**Comment by johnhashva** [comment]
Current URL  |  Redirect URLs to be created
---  |  ---
https://www.va.gov/initiatives/veteran-trust-in-va | https://www.va.gov/trust 
https://www.va.gov/initiatives/veteran-trust-in-va | https://www.va.gov/Trust

**Comment by kelsonic** [comment]
@johnhashva just to confirm, the end destination is https://www.va.gov/trust or https://www.va.gov/Trust?

**Comment by brianalloyd** [comment]
CLP is now live, closing ticket in support.
