### ISSUE TITLE
BUILD API Infrastructure for VETLink Replacement.

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#23794]
Create API infrastructure for VETlink Replacement[https://app.zenhub.com/files/133843125/1b7a4025-6133-4c5b-a4a0-ec84741e3721/download](https://app.zenhub.com/files/133843125/1b7a4025-6133-4c5b-a4a0-ec84741e3721/download). (see attachment)

**Comment by pcshah1026** [comment]
[https://app.zenhub.com/files/133843125/29a240c8-a144-459f-b139-b97511a6483d/download](https://app.zenhub.com/files/133843125/29a240c8-a144-459f-b139-b97511a6483d/download)



@shanemelliott @robertdurkin attached, you will find the RPCs (and other data elements) that Vetlink is currently using.
