### ISSUE TITLE
[Web Component]: Alert Box - Consider adding a prop to change the SR-only text currently hard-coded as "Alert"

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#23795]
## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Details

The alert box has some `sr-only` text that's hard coded as "Alert". It might be nice to have a way to change this text by passing in a prop like `label="Success` or something of that type. Not every use of the alert box in the Storybook examples feels like an alert or negative event.

## Acceptance Criteria

- [ ] Prop is added and documented that allows users to override the default SR-only "Alert" text

**Comment by 1Copenut** [comment]
@caw310 the accessibility staging review tickets are all entered. I had one question that didn't feel like it needed a ticket. Will the Storybook docs be updated to include all of the props? Some of them like `visible` were not included in the feature branch I was testing.

**Comment by caw310** [comment]
@bkjohnson , can you answer Trevor's question about props in SB?

**Comment by bkjohnson** [comment]
We may be able to close this - the hardcoded `<span class="sr-only">Alert: </span>` was removed in https://github.com/department-of-veterans-affairs/component-library/pull/137

**Comment by k80bowman** [comment]
Closing, as Brooks noted above, the hardcoded span no longer exists.
