### ISSUE TITLE
Example QA project on VA.gov

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#2379]
As a QA on product support, I want to create an example test plan so that other teams have examples to look at when doing their own QA effort. 

AC: 
- [ ] Create a test plan
- [ ] Create a test suite
- [ ] Create test cases
- [ ] Test execution logs
- [ ] Test report
- [ ] Publish in GH in QA practice area

**Comment by peterhill-oddball** [comment]
Working with Tze on a set of artifacts for his testing efforts related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/2540.

**Comment by peterhill-oddball** [comment]
I am also in search of a good candidate from one of the teams without any testers.  I think By Light is a good candidate.

**Comment by peterhill-oddball** [comment]
I have created an example test plan and test cases in markdown and pushed them to the va.gov-team repository here -- https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance/examples/about-disability-ratings
