### ISSUE TITLE
Document how to deploy a branch to dev 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#238]
Summary here: https://github.com/department-of-veterans-affairs/vets-website/pull/10097#discussion_r286155809

Suggest adding it to this page: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/site-structure/environments/

**Comment by timwright12** [comment]
PR for this: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/626
