### ISSUE TITLE
Message form: Double arrow on "To" picker displays outside the field 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23805]
## What happened?
When a message recipient is selected from the picker, the double arrow that denotes the picker gets pushed outside the field. 

This appears to only be an issue with the "To" picker in Secure Messaging. Not able to reproduce on other dropdowns in the app.

## Specs:
- Device: iPhone 11, Samsung Galaxy S9

## Steps to Reproduce

1. Log in with user +41 on Samsung Galaxy S9 (default text size settings enabled:
2. On the Compose Message form, select either recipient from the "To" dropdown
3. When the selection is confirmed, notice how the double arrow on the "To" dropdown field now displays to the right of the field

Alternative way to reproduce:

1. Log in with user +261 on iPhone 11
2. In the device's settings, max out the font size
3. On the Compose Message form, select any recipient from the "To" dropdown
4. When the selection is confirmed, notice how the double arrow on the "To" dropdown field now displays to the right of the field

## Desired behavior
Dropdown arrows stay within the boundaries of the dropdown field.

## Acceptance Criteria
See desired behavior.

## Bug Severity
- 4 - Low

## Linked to Story
N/A

## Screen shot(s) and additional information
![Screenshot_20210426-172659_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/5fe1a6a1-5874-444e-942f-a6bcf37eb441)
![Image from iOS (38).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/41b3bc6e-5e8e-47c5-9fce-607ba3e410d4)

**Comment by digitalken** [comment]
PASS 5/3/2021 - Looks good on Samsung and iOS.  Closing.
