### ISSUE TITLE
Picker: issues w/ resizing & resetting

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23806]
## What happened?
1. When larger font sizes are enabled on a device, the picker modal also increases in size. This results in the following: 
- Picker headings (i.e. "Country") are difficult to read
- Picker nav bar occupies most of the screen
- Options in the picker occupy minimal real estate, which makes it difficult to navigate through the options

2. When an item in the picker is selected but not confirmed, that option is still selected when re-opening the picker. The placeholder should be the selected option if the field does not contain a valid entry. 

## Specs:
- Device: iPhone 11

## Steps to Reproduce
**For resizing issue:** 
1. On an iPhone 11, max out the device's font size in the accessibility settings
2. Navigate to any picker in the app, e.g. Edit Address > Country
3. Observe how the scale of the picker has increased with the rest of the text: the header assumes almost the entire screen, and the "Country" label is not legible.

**For resetting issue:** 
1. Open Country picker
2. Tap a valid option (e.g. "Algeria") so that it is highlighted. Select the "Cancel" button to close the picker. 
3. The picker should display a field error. 
4. Re-open the picker. Notice how "Algeria" is still highlighted, instead of the placeholder. 

## Desired behavior
1. Picker nav bar should remain a fixed size regardless of the device's text size
2. If a dropdown field does not contain a valid entry, the picker should open with the placeholder selected as the default.

## Acceptance Criteria
1. Lock the size of the picker nav bar so that it remains the same height/width when a user increases the text size on their device
     - The options in the picker menu can scale
2. If a dropdown field does not contain a valid entry, the picker should open with the placeholder selected as the default.

## Bug Severity
- 3 - Medium

## Linked to Story
For resizing issue: #21131, AC 10

#### **Resizing issue:** 
![Image from iOS (39).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/0e202aba-9274-40fa-be90-13ff381fd4b6)
#### **Resetting issue:** 
https://images.zenhubusercontent.com/133843125/e42e6ff2-8df6-44e7-b80a-6e26379f1ed2/rpreplay_final1619494820.mp4

**Comment by digitalken** [comment]
PASS 5/4/2021 - Looks good on iOS with font maxed out.  Closing.
