### ISSUE TITLE
Find a Form - Form Last Updated Issue (20-0996)

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#23818]
## What happened?

VA Form managers in April 2021 updated the 20-0996 (Request for Higher Level Review) but the Forms detail page shows Form Last Updated as June 25, 2019 and that is also what is shown in the Forms DB Data in the CMS.

<img width="438" alt="Screen Shot 2021-04-27 at 8 53 53 AM" src="https://user-images.githubusercontent.com/63107147/116244661-21148e80-a736-11eb-871e-14d8538426fd.png">

<img width="642" alt="VA Form 20-0996 - Main DB" src="https://user-images.githubusercontent.com/63107147/116245070-8ec0ba80-a736-11eb-8d01-91febc627a9e.png">

![20-0996 Forms Detail Page](https://user-images.githubusercontent.com/63107147/116244519-00e4cf80-a736-11eb-8772-610de8e5ca1c.jpg)

Forms DB Data
<img width="341" alt="Form 20-0996 DB Dataset" src="https://user-images.githubusercontent.com/63107147/116244091-9764c100-a735-11eb-9c56-e9122564f2fd.png">

## Specs:
- Device: Desktop and Mobile
- Browser: All
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/find-forms/about-form-20-0996/
- Test User _(if applicable)_:

## Desired behavior
- The _Form Last Updated_ should be 04-26-2021 as shown on the Search Result page, as seen here:

<img width="883" alt="Screen Shot 2021-04-27 at 8 43 34 AM" src="https://user-images.githubusercontent.com/63107147/116245384-ea8b4380-a736-11eb-8b58-cece7117fd36.png">

## Acceptance Criteria
- [ ] The _Form Last Updated_ should be 04-26-2021 on the 20-0996 Detail Page

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by johnhashva** [comment]
Per @swirtSJW on Friday 4/23: Issue found.  Our file mover was still moving the file each night, but it was putting it in the wrong place.   The last time the file was copied to the right spot, was the morning of 4/15/21.   All files moves after that were put in the wrong spot.  The migration was still running every night, it just was using the same data from 4/15 every night.  So when the mover is fixed, all of the out of date data should be fixed on the next nightly migration.  Our fix was just merged in.  It will go out monday afternoon and forms data should be up-to-date by Tuesday morning.

**Comment by johnhashva** [comment]
4/27 Update:  @MarciMcGuireGCIO and @swirtSJW Looks like the Forms Search page now has the new date

<img width="883" alt="Screen Shot 2021-04-27 at 8 43 34 AM" src="https://user-images.githubusercontent.com/63107147/116246074-a2205580-a737-11eb-8ad5-ee62b6c7fd31.png">

But the 20-0996 Detail Page does not:

<img width="642" alt="Screen Shot 2021-04-27 at 9 05 20 AM" src="https://user-images.githubusercontent.com/63107147/116246240-cbd97c80-a737-11eb-9a53-88fb329ad895.png">

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @johnhashva!  @swirtSJW - thank you for getting that resolved!

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva I'll check with @zacharymorel to see if this is possibly a programmatic issue.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel - can you take a look at this issue and see if there is something in the code that would cause the detail page for VA Form 20-0996 to show a different date from what is shown on the search results for the same form? Thanks!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Awesome!
