### ISSUE TITLE
508-defect-2 [SCREENREADER, COGNITION]: Rewrite VA-wide trust percentages so they are pronounced understandably by screen readers 

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#23829]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Details

Currently, the text string `VA-wide trust: 00% Male: 00% Female: 00%` is read out as "VA-wide trust [pause] zero zero percent Male [pause] zero zero percent Female [pause] zero zero percent. In other words, to a screen reader user, they would interpret the information as follows:

VA-wide trust:
- zero zero percent male
- zero zero percent female
- zero zero percent

This will lead to screen reader users interpreting the VA-wide trust percentage as the male trust percentage, the male trust percentage as the female trust percentage, etc.

## Acceptance Criteria

- [ ] 0% is used instead of 00%
- [ ] There are pauses between the percentage and the following category e.g. VA-wide trust, 0 percent [pause] Male, 0% [pause], etc

## Steps to Recreate

http://preview-prod.vfs.va.gov/preview?nodeId=18299
Run any screen reader

### Recommended - Semantic Lists
Using a semantic list such as `dl` or `ul` will make it very clear to screen reader users that this is three separate groupings. 

For example, the following may be read by a screen reader as:
"Definition list, 6 items. VA-wide trust, 1 of 6. 0%, 2 of 6. Male, 3 of 6. 0% 4 of 6. etc"

```html
<dl>

  <dt>VA-wide trust</dt>
  <dd>
    0%
  </dd>

  <dt>Male</dt>
  <dd>
    0%
  </dd>

  <dt>Female</dt>
  <dd>
    0%
  </dd>

</dl>
```

OR, more simply, use an unordered list which would be read as:
"List, 3 items. VA-wide trust: 0%, 1 of 3. Male: 0%, 2 of 3..." etc

```html
<ul> <!-- Add role="list" if you remove the bullet styling -->
  <li>VA-wide trust: 0%</li>
  <li>Male: 0%</li>
  <li>Female: 0%</li>
</ul>
```

### Band aid solution - Paragraphs or punctuation
Simply adding in line breaks or punctuation can split this string apart to make sense. 

For example, line breaks will cause this to be read out as three separate lines:
```html
<p>
  VA-wide trust: 0% <br aria-hidden="true">
  Male: 0% <br aria-hidden="true">
  Female: 0%
</p>
```

Or adding a period between each will add a needed pause to make this easier to understand:
```html
<p>
  VA-wide trust: 0%. Male: 0%. Female: 0%
</p>
```

## Screenshots or Trace Logs

<img width="1113" alt="Screen Shot 2021-04-27 at 10 12 23 AM" src="https://user-images.githubusercontent.com/14154792/116256413-2a572880-a741-11eb-9f16-4b1b8e00fc77.png">
<img width="688" alt="Screen Shot 2021-04-27 at 10 10 51 AM" src="https://user-images.githubusercontent.com/14154792/116256416-2a572880-a741-11eb-9125-5d6c7999ab74.png">

**Comment by laflannery** [comment]
I don't believe this is relevant anymore, the screenshot is not on the page.  Will close unless I hear otherwise
