### ISSUE TITLE
[Frontend] Send the "will upload documentation" property with the rest of the form data on 10-10CG submission

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#23822]
Schema Ticket: https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/23820

**Description**
Update the front-end to pass the value of the user's selection for POA documentation upload, to the backend.

**Comment by SKasimow** [comment]
@lzapson @jchilders found this ticket in the backlog and looks like it is related to the ticket we made for sprint 65 assigned to James: https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/35009 

I'll leave it open for now but sounds like once James confirms what he sees in the payload, there may be FE work if we need to pass more along to the BE.
