### ISSUE TITLE
billing tags on CloudWatch Logs

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2382]

**Comment by wyattwalter** [comment]
@jbritt1 can you research how we can get billing tags on CloudWatch Logs? I'm not sure exactly what gets tagged.. Streams, Groups, etc. We typically create them on-the-fly via the deployment config. The result is an awslogs.conf file with individual files like:

```
[/var/log/prometheus/statsd_exporter.log]
datetime_format = %Y-%m-%d %H:%M:%S %z
file = /var/log/prometheus/statsd_exporter.log
log_stream_name = deployment-vagov-dev-vets-api-server-20191010-183602-{ip_address}
log_group_name = dsva-vagov-dev/var/log/prometheus/statsd_exporter.log
```

**Comment by jbritt1** [comment]
At first glance of the TF docs, it appears log groups can be tagged. Log streams receive log_group_name as a parameter leading me to believe the tags are then transitory. That and the fact that tags do not seem to be an option for `aws_cloudwatch_log_stream`. Will continue the deep dive on it, but wanted to drop some notes as I go.
