### ISSUE TITLE
TUD: Implement design audit fixes

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#23838]
## Issue Description
Amanda has completed a full design audit of the Test User Dashboard web application and will provide feedback of things to be fixed.  This will outline all tasks to be performed on the TUD application.

---
### **Find a user account**
- [x] Switch casing of 'staging'
- [x] Fix spacing of between Services rows (switch to grid); Move Services over to the left
- [x] Update date of birth to use MM-DD-YYYY
- [x] Update services consistency
  - [x] Messaging = Secure Messaging
  - [x] Form 526 = Form 526 Disability Compensation
  - [x] Form prefill = Form prefilled enabled
  - [x] Save in process = Form saved in process
- [x] Facilities does not show up in the "Services table"
- [x] Sign in = "Go to staging"
- [x] Profile should align to left dropdown arrow
- [x] Getting started appears as a separate link & "Learn more"

### Getting started
- [x] Lowercase all capitalized "Staging"
- [ ] Documentation calls out Test User Dashboard instead of TUD acronyms
- [x] Consistent terms of "Test account", "Test user account", or "User account"

### Documentation
- [x] Change 'Available' => "Availability"
- [x] "Search" should be lowercase
- [ ] Call out Services are attributes on an account (add to definitions table)
- [x] Status section the word "can" should not be capitalized
- [x] Add a definition for "Test Account/whichever term we decide on"

### Issues
- [x] Services & attributes are being used, switch to one
- [x] Remove period before "to"
- [x] Update language from 'VA.gov' to 'VA.gov staging'
- [x] Break up text under number 3
- [x] Missing word in unable to login with ID.me, DS Logon, etc.

## Acceptance Criteria
- [ ] Amanda approves of the design changes implemented
- [ ] Functionality of the TUD application does not change
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by APorter-Clarity** [comment]
[https://app.zenhub.com/files/133843125/9c1dd94b-bc13-403e-8b30-cc16b7979215/download]
