### ISSUE TITLE
Add billing tags on EBS volumes

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2385]
## Problem
Ensure EBS Vols have proper billing tags. 

## Goal
_Ensure these tags are correct and get updated when Vols are made_

## Acceptance Criteria
- [x] _Ensure EBS Vols have proper billing tags_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
@jhouse-solvd any way to check if this is still a priority? If it is not, can we close?

**Comment by jbritt1** [comment]
Forgot volumes attached to EKS cluster nodes. Should have a pull request up for this aspect soon.
