### ISSUE TITLE
Ensure reverse proxy metrics labels are granular enough for mobile observability

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#23865]
We measure API request rates and latency at the nginx reverse proxy, using Prometheus metrics. 

Prometheus requires us to be thoughtful about the cardinality of metric tags/labels - having a metric label with thousands of unique values causes performance problems.

The nginx requests were tagged with a two-level scheme "app" and "component", where app="api" and "component" = the individual feature. As things got split into modules, it's not clear that there was enough granularity for things within the modules with this two level scheme.

Task: Verify how mobile API requests are getting labeled, and make sure they are not e.g. all getting collapsed under a single "mobile" metric as this will not be helpful in isolating specific API requests to different upstreams. 

If the metrics are not granular enough, work with the VSP operations team to refine them in a way that is consistent with other modules.

**Comment by patrickvinograd** [comment]
I confirmed that all API requests under the mobile module are getting collapsed under `app=api, component=mobile`. Since the mobile module encompasses a wide range of features that's not very helpful.

One mitigating factor is that we do have per-controller metrics from the `api_rack_requests` instrumentation in rails. But I would like to capture this in nginx as well.

## Options
1. Change `app` to `mobile` for this module. This would be more accurate in terms of mobile being a wide-ranging app. But it is still logically part of vets-api and so you'd lose the roll-up of those API requests still hitting rails in any metrics that are using `app=api`. 

2. Add an intermediary `module` label, so `app=api, module=mobile, component=claims|sm|appointments|etc`. This again would be accurate for mobile. It is adding an entire label dimension to all these nginx_http metrics which carries some prometheus overhead with it. And most modules probably don't have exactly this issue.

3. Break out a location block in the nginx config for mobile, and prefix the `component` with `mobile_` so `app=api, component=mobile_appointments|mobile_claims|mobile_profile` etc. This way we get some granularity, we don't add an entire dimension to the metrics, and we can still roll up everything with a `component=~mobile_*` regex query in prometheus.

**Comment by ayushchak** [comment]
Hey @patrickvinograd - would you consider this launch-critical?

**Comment by patrickvinograd** [comment]
Connects to #23051.

Yes, I'd consider this launch critical because this is the best way to enable the mobile-specific alerting that we want to do.

**Comment by ashley-matthews** [comment]
@ayushchak @patrickvinograd - initial thought is this is critical for launch, but Patrick is working on another ticket that may influence whether we will move forward with this work or not.

**Comment by patrickvinograd** [comment]
Merged to all environments; there are some follow-on monitoring and alerting changes that rely on this, tracked in other tickets. Closing.
