### ISSUE TITLE
Access for Angela Fowler

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#23864]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Ariel Nerbovig
- Please provide your name.
   > Angela Fowler @AngelaFowler82 
- Please Provide your email.
   > angela.fowler@adhocteam.us
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Accessibility Specialist, Work for Ad Hoc LLC

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDv8nRdrIaCPpiD0pApUeMKMuaZptSkhYCO++hGZQswhD86XM1xQphjNKCtB+UZTa0cggCF8Zd38thkAW12o4ySIdSncetIHeFUjZQdBbooly8nMtg34946NakRz4eLIYMoThLMJaPWq0N5LyqGXWCDgJfZ+ZyZ5a8oVUQcsF7jC+N2lvsi1z989oYRupBYhUZUndgGkoa19TNxDOCBOZSknOz5nnVq0PbL4In16E/CoqmKGFxazzLEIXjwQnzrv/C//ae4hKlzmQPr9/OiNmEFW4NPrAbXiGfztLj8X/HmCuD3Bz64M2uJAYosM8eyrb7687V8EbJ8cXgUvQ4HvoEBl2+j7uOWzxq55+ItovQY6yMNRJPPHXDdfbepk2OB05J0MzuLJOLiDxtpOky/nOwv06ed2utjxF0OOQUB5hoP2CjJdaTFXxaEFe2kYvZjGy0afWuLhaSb3ufdZvRFUT+JqUD7npvEO++r0Vq504S7nXgSidmhpRcFzQcKK3WIJP0= Angela Fowler@Angela-Laptop
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? Just need access to SOCKS for accessibility reviews.

@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Ariel Nerbovig
Name: Angela Fowler

**Comment by mleclerc00** [comment]
Hi @AngelaFowler82 

You should be able to access socks now with the following [socks tutorial](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy)

Let me know if you are able to set everything up so I can close out this ticket and if you have any issues feel free to drop a message in [#vsp-platform-support](https://dsva.slack.com/archives/CBU0KDSB1)

**Comment by mleclerc00** [comment]
Jeff let me know that we need approval from Ariel Nerbovig to move forward with AWS access but I can't seem to fin their user to ping in this thread

**Comment by joshkimux** [comment]
@mleclerc00 Angela was able to access her socks! Closing this ticket out.
