### ISSUE TITLE
Access for Marci McGuire

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23869]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Marci McGuire
- Please Provide your email.
   > mmcguire@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Decision Tools team, Project Manager, GovernmentCIO

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnKgheiwDTddAneIhxU96pHvG044wJ1dy82nB9CMYlN4RshFhlnXX/BNisNeKVwcsIjaSogZZva6q7tqC1mD2xUHCcRsYfquv58AEqgXVmJlw48qggfBHn44pffeDn5qOwaxeu2wJ+MoQppMTGTvOF5VzguarEDGVyaPOGlr6M1NRVLNLVcG+G9Ho+9l7k2sCGsR9zAxaCLAFgTZwmVEydelWpIvSpmV8H0PL1mI8Ix9wd1kXR9hE6x5VOXsMlQPPXubGbaaGzuS9WD+TQ8dyr6behqLlX6ms6BeIKKqmvkhEIoYy2B6RM7fx9S8K3mJfnIkk8Q2E204DmX3x7Qty879zeftEUR0bLbcB/Yo3qi9Zox0RyC7118xGSA83y0Dd0N0xMYRpwOInCJSz123Vs5J83pds4J6xiXJ4X5IdbYqqzB81eRZsar4mW0sHx+3xEphHnGqMOTXSUyMiUpYnuPE/3rGPNoYV2S+bx8Yx9hx/8bvhyP9Da0adTyZC/f9s= Marci McGuire@DESKTOP-86C7897

- Grant AWS Console access?
  >  NO
  - What AWS services do you need access to and why? N/A

**Comment by tskinn** [comment]
@MarciMcGuireGCIO your ssh key has been added to the socks proxy and you should be able to connect. Reach out in slack if you have any issues.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @tskinn !

**Comment by MarciMcGuireGCIO** [comment]
Hi @tskinn I tried following the instructions for configuring and testing the SOCKS proxy, but when I run the command `$ curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.gov' I get a response of "connection refused".

**Comment by jbritt1** [comment]
Verified user has working SOCKS access at this time, closing. 

Ref: https://dsva.slack.com/archives/CBU0KDSB1/p1619619960043200

We can definitely reopen / help out if any issues arise.
