### ISSUE TITLE
[IE11 + JAWS] Colmery 107 - Too much information is being read on SELECT menu changes

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2386]
# Description

The 508 office noticed an issue where IE11 + JAWS will read out a lot of extra information on the program detail views when users change a `<select>` menu in forms mode. I was able to recreate the issue, and it only occurred with IE11, not Chrome, using JAWS.

I think it's related to some extra `aria-live="polite"` regions that are defined on parent or sibling elements, but can't test easily until code is in Staging. See screenshots attached for possible points to start reviewing.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a JAWS user, I don't want to hear extra information read aloud when I make a choice in FORMS mode from a `<select>` menu

## Environment

* Windows 10
* IE11
* JAWS
* https://staging.va.gov/gi-bill-comparison-tool/profile/11806124

## Steps to Recreate

1. Enter `https://staging.va.gov/gi-bill-comparison-tool/profile/11806124` in browser
2. Start screenreading device listed in Environment
3. Navigate to one of the `<select>` menus and press `ENTER` to jump into forms mode.
4. Verify you hear an audible "click". This is JAWS entering forms mode.
5. Press the `DOWN_ARROW` to change the `<option>`.
6. Press `ENTER` to exit forms mode.
7. Verify you hear extra information from further up the page being read aloud, and see the green virtual cursor square in the top-left of your screen.

## Possible Fixes (optional)

I have a hunch the extra `aria-live` regions are to blame. Engineers and QA will need to be diligent and ensure these are not being used to inject warning flags or other content after the page load.

## PR
https://github.com/department-of-veterans-affairs/vets-website/pull/10933

## Screenshots or Trace Logs

![Screen Shot 2019-10-10 at 4 57 27 PM](https://user-images.githubusercontent.com/934879/66610532-65a2fe00-eb81-11e9-92ce-9e81c7640f4e.png)

---
![Screen Shot 2019-10-10 at 4 57 41 PM](https://user-images.githubusercontent.com/934879/66610536-6cca0c00-eb81-11e9-8ad2-35804869c3f4.png)

---
![Screen Shot 2019-10-10 at 4 58 10 PM](https://user-images.githubusercontent.com/934879/66610544-73588380-eb81-11e9-8cc0-dd4e0893bdf9.png)

**Comment by sonntag-adam** [comment]
Testing passes

**Comment by 1Copenut** [comment]
@sonntag-adam Let me know when this one is merged into Staging. I'll review it with JAWS and IE11 then. Thank you.

**Comment by delli-gatti-michael** [comment]
@1Copenut This is in staging and ready for re-testing.

**Comment by 1Copenut** [comment]
@desireeturner Following up on this item quickly. The pull request associated with this issue ticket caused a screen reader regression on GIBCT in staging and production. Let me know if you'd like to discuss updates and/or retesting.

**Comment by desireeturner** [comment]
@1Copenut: @ksantiagomorgan6 reverted his changes and we have this issue in the backlog to be worked as soon as possible but have two high priority efforts that the team is focused on right now in order to be ready to launch in November. We will reach out when we're ready to test a new solution.

**Comment by 1Copenut** [comment]
@desireeturner Thank you for the update. I confirmed in JAWS the regression has been removed. I'll keep this issue open and available to re-test after your November launch item.

**Comment by desireeturner** [comment]
@1Copenut this is ready to be reviewed again

**Comment by 1Copenut** [comment]
This appears to be working as expected, not reading out additional information beyond the `<select>` and it's related `<label>`. Moving to close.
