### ISSUE TITLE
Add facility info to vaccine submission

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23860]
## Description
As Product, I would like to see vaccine submissions by facility in Google Analytics so that I can report on progress for the initiative.

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag
- [ ] ANALYTICS - facility number is sent with submission event

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by jenniemc** [comment]
@laurenernest, which submission event would you like the facility info sent to GA? At "vaos-covid19-submission" or "vaos-covid19-submission-successful"? 

cc @jbalboni

**Comment by laurenernest** [comment]
Successful please :)
