### ISSUE TITLE
Misc Secure Messaging Errors

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#23872]
### Description

Looking to confirm from the list of API errors I've collected that these ones seem like we don't need to specifically handle in the mobile app with custom error messages. The only exception might be `SM135`?

```
SM105: # What causes this? Perhaps then we can come up with more customized detail below
detail: 'User was not found'
```
```
SM117:
detail: 'A data integrity issue was encountered'
```
```
SM135: # 'User is not eligible because they have not accepted terms and conditions or opted-in'
detail: 'You have not accepted the MHV Terms and Conditions to use secure messaging'
```            
```
SM152:
detail: 'Email address is invalid’
```
```
SM904: # 'Message Service Error' - treating as 404, see gets_a_message_thread_id_error
detail: 'Message requested could not be found'
status: 404
```

**Comment by narin** [comment]
@drjecker I think you're right.  `SM135` is probably the only one we'd need a custom error for. This is most likely occur when the user first attempts to access the SM page in the mobile app, and we should probably  redirect them to MHV and ask them to accept the terms and conditions there.

**Comment by drjecker** [comment]
Sounds good. Closing out this ticket and will make a new one for that specific error.
