### ISSUE TITLE
[COGNITION]: Colmery 107 - Heading H2s should wrap expand/collapse buttons

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2387]
## Description

The VA 508 office noted this as an improvement item. The large gray expand/collapse sections do not identify as headings level two in JAWS. A quick investigation showed the `<button>` elements wrapping the `<h2>` and is the likely cause of these headings being ignored. Screenshot attached.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* As a screenreader user, I want the H2 headings to appear in the Headings menu and be available as virtual cursor stops when I'm navigating by heading
* As a visual user, I do not want to see any style or functionality changes in the expand/collapse sections

## Environment

* Windows 10
* IE11
* JAWS
* https://staging.va.gov/gi-bill-comparison-tool/profile/11806124

## Possible Fixes (optional)

Let's try refactoring these to wrap the buttons in the H2:

```html
<h2>
  <button
    aria-controls="accordion-item-8"
    aria-expanded="true"
    class="usa-accordion-button"
  >
    Veteran programs
  </button>
</h2>
```
-->

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2019-10-10 at 5 15 43 PM](https://user-images.githubusercontent.com/934879/66611029-eadae280-eb82-11e9-886e-b8f4d2f722c1.png)

**Comment by sonntag-adam** [comment]
![Screen Shot 2019-10-22 at 10.44.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/323ef7d7-b4d7-4ddd-a21b-ab76e522fe29)

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by 1Copenut** [comment]
@sonntag-adam When you've got a few minutes, would you mind sending me the PR link?

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/10901

**Comment by 1Copenut** [comment]
@sonntag-adam This tested well in VoiceOver on MacOS. I'm not able to test on Windows (JAWS) on localhost, will retest when it's in Staging.

**Comment by sonntag-adam** [comment]
@1Copenut this is in staging now

**Comment by 1Copenut** [comment]
@sonntag-adam Confirmed in JAWS and NVDA on Staging. Moving to close.
