### ISSUE TITLE
VRRAP: Incomplete link text

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#23875]
While filling out the VRRAP (1990s) form, the user is asked for bank account information. Under these fields is a helper text section that can be expanded by clicking "What if I don’t have a bank account?". Contained within that helper text is a link to `https://veteransbenefitsbanking.org/`. The link functions correctly, however, not all of the words that should be part of the link currently are. 

### Steps to reproduce
1. Log in to staging.va.gov
2. Begin the VRRAP (1990s) form at the following link:
https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply
3. Scroll down to the bank account information section and expand the helper text by clicking "What if I don’t have a bank account?"

### Expected behavior
`Veterans Benefits Banking Program (VBBP)` is a link that leads to `https://veteransbenefitsbanking.org/` as shown in the screenshot below:
![Screen Shot 2021-04-27 at 2.40.59 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/539e84d5-30a1-41b1-bef9-d08badc3b766)

### Actual behavior
The word `Veterans` is present but not part of the link as shown in the screenshot below:
![Screen Shot 2021-04-27 at 2.41.21 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c6f37ebb-6fa0-4b9e-9552-b4484c7ff1f7)

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/16966

**Comment by delli-gatti-michael** [comment]
Local testing complete
![Screen Shot 2021-04-27 at 3.26.04 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/302f9bdb-126c-4fee-be26-9878c1e540e4)

**Comment by delli-gatti-michael** [comment]
Fix is on Staging. Closing this issue
