### ISSUE TITLE
Contact Center Review for VSA-Education 22-1990S (VRRAP)

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23874]
# Request the Contact Center Review  

## Description
22-1990S - Veteran Rapid Retraining Assistance Program (VRRAP)
The 22-1990S is an application form for the VRRAP education benefit that was passed into law early 2021.  It is a short term benefit program aimed to reduce unemployment due to COVID.

### Launch Date
2020-04-30

### Version Number
1.0

### Product Guide
Being revised, will update with final document when ready.

Note - This application will be linked to and included on VA.gov, but that is not currently available on staging.  You must directly access the form at this time.

### Product Video
https://user-images.githubusercontent.com/48260534/116262067-3beeff00-a746-11eb-86e4-0eb10623eb57.mp4

### Product Video Transcript
[VRRAP_Transcript_20210427.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6385432/VRRAP_Transcript_20210427.docx)

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Hi @dneel-bah. Just wanted to let you know (in case you weren't already aware) that there is a best practice that requires at least a 1-week turnaround (ideally 2) with product guide and video edits. Not only does it need to meet your approval, but that of the VEO team before distribution. I will have something for you as soon as I'm able, working with the 4/30 launch date as much as possible. Thanks!

**Comment by starlow00** [comment]
Hello @dneel-bah . Attached is a draft of the product guide with my edits. Please look it over and let me know if you're good with changes, then I can have VEO review. Since this is set to launch 4-30, the sooner you can reply, the better.

Note: I will have video/transcript notes (if any) for your review by Thurs. 4-29.

[Education.22-1990S.Product.guide_ST_042721.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6394728/Education.22-1990S.Product.guide_ST_042721.docx)

**Comment by dneel-bah** [comment]
@starlow00 Thank you for the quick turnaround.  All of the changes looked good.  I did get the information about how VA.gov will link to the application, so I have included that.  I also modified one of the screenshots.

I don't know how to do the linking that you did with the figures so I wasn't able to add it in.  Here is the updated document.
[Education.22-1990S.Product.guide_BAH_042921.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6399263/Education.22-1990S.Product.guide_BAH_042921.docx)

**Comment by starlow00** [comment]
@dneel-bah , this looks good, thank you. I updated the TOC and TOF for the additional images, and included the necessary links. The video transcript and video work well. I will forward to VEO for their review and get in touch with you afterward.

**Comment by starlow00** [comment]
No edits from VEO. Closing.
[VRRAP-22-1990S-Product-guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6454913/VRRAP-22-1990S-Product-guide.docx)
[VRRAP-video-transcript.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6454914/VRRAP-video-transcript.docx)

https://user-images.githubusercontent.com/73244652/117723397-30b0c000-b197-11eb-8d90-cb571be71cfa.mp4
