### ISSUE TITLE
Research Comparison of Visual Testing Tools and Create Summary Document

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#23888]
## User Story

As a platform stakeholder, I need a tool that evaluates products hosted on the platform for regressions upon integration of changes.

## Expected Behavior

N/A

## Acceptance Criteria

- [x] Prominent industry products and services for visual testing have been listed and evaluated
- [x] Document pros and cons for each tool, pricing, and how it fits into our tooling ecosystem on the platform

**Comment by holdenhinkle** [comment]
Google spreadsheet - https://docs.google.com/spreadsheets/d/1QKC0d31lARWY83vztyQXTY0pA1mZkjSqVkILQfraHl4/edit?usp=sharing

**Comment by pjhill** [comment]
Research is complete.
