### ISSUE TITLE
Create Report for Community Care

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#23896]
Justin, there is a new table we need a report for: [OVAC_VEText].[App].[MON_CommCareAppts]

If we could start simple.  # messages sent by site, # responses, etc.

**Comment by shanemelliott** [comment]
sompling as simple as this:

SELECT count(*),stationNo
--,date
,status
  FROM [OVAC_VEText].[App].[MON_CommCareAppts]
  group by stationNo,
 -- date,
  status
  order by stationNo

**Comment by jwowk** [comment]
Report published to VEText Power BI App:
https://app.powerbigov.us/groups/me/apps/edb20dd9-adff-4cdb-9e08-35ecc7e2ea94/reports/918e5fbe-5011-46df-8494-036f23d01500/ReportSection99642ad0ac7c70206011?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf
