### ISSUE TITLE
[Campaign Landing Page MVP Release] VA Trust CLP - Site Navigation Links

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#23913]
## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * This is a site navigation links (IA) request for the first CLP to be released in production (target date: by May 3, 2021) -- [Trust VA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23304)

* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [CLP Trust VA product Epic.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23304)

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

- [X] **Updates to an existing unauthenticated VA.gov page**
With the site URL (www.va.gov/veteran-trust-in-va/) and redirect URL established (VA.gov/trust + VA.gov/Trust) via consultation with Platform-IA (@mnorthuis), we now need to determine the site links-paths to the page.   Here is the recommendation:

*The primary entry points and changes to global navigation, as well as any potential crosslinking opportunities*

Priority | Placement | Destination | Description  
--- | --- | --- | ---
Consider | Top Nav - About VA menu | www.va.gov/veteran-trust-in-va/ | A link could be considered for the "Learn about VA" column.  Recommended placement there would be as the 4th option, just after "VA plans, budget, and performance".  <br>Links added to the top nav must be approved by appropriate OCTO-DE stakeholders.
Consider | Top Nav - About VA menu promo spot | www.va.gov/veteran-trust-in-va/ | The promo spot could be utilized to highlight the campaign and provide quick access to the CLP.  <br>Promo spot changes must be approved by appropriate OCTO-DE stakeholders.
Consider | Footer |  www.va.gov/veteran-trust-in-va/  | The very bottom 2 lines of the footer include a number required gov links as well as broad VA links.  They are listed in alpha order.  This option could be labeled something like "Veteran Trust" and listed in proximity to the dashboard and portrait project links. <br>Links added to the footer must be approved by appropriate OCTO-DE stakeholders.  
       

### Frontend engineering support 

- [X] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - No, not yet. Need to finalize the site links with approval from @mpeterz 
     - Once the site links are finalized, a PW front-end engineer will need to implement (e.g., add links to specified navigation)
 

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* By mid-May 2021

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Public Website (aka Sitewide)
- DEPO product owner: John Hashimoto
- Product manager: Brian Lloyd
- Designer: Ryan Thurwell
- FE engineer: Kelson Adams
- Product/team Slack channel: #vsa-public-websites

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by johnhashva** [comment]
@brianalloyd 5/3 update: I need to confirm with Meg Peters what the site links strategy for CLP/Trust VA will be.   There are some differing opinions about this that need require consensus.

**Comment by johnhashva** [comment]
Update 5/3 from @mpeterz:  Re: linking to the Trust VA CLP, two acceptable options:VEO could talk to the VA.gov Performance Dashboard folks about having them include a link to Trust VA since they also measure VA performance (perception by Veterans). I am not sure who manages the dashboard. Maybe Chante? VEO could also talk to OPIA about using the promo spot on the right in the top nav flyout/megamenu.

**Comment by brianalloyd** [comment]
Work has been completed, CLP is now live.  Closing in support.

**Comment by johnhashva** [comment]
@brianalloyd

**Comment by brianalloyd** [comment]
Awesome, thanks @johnhashva for the update.

**Comment by johnhashva** [comment]
Confirmed: No site links will be made for this CLP.   So closing.
