### ISSUE TITLE
Health Care Rewriting: Active duty service members

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2391]
@DanielleSoCompany commented on [Mon Apr 22 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156)

## User story

As an active-duty service member, I need to know how and when I can transition to VA health care or other health benefits available to me after separation. As a service member returning from OEF/OIF/OND combat, it's also important that I know about my enhanced eligibility period for VA health care.

## What's needed

Rewrite legacy pages ahttps://www.va.gov/HEALTHBENEFITS/apply/active_duty.asp and https://www.va.gov/HEALTHBENEFITS/apply/returning_servicemembers.asp into one, consolidated page.

Page preview: https://vagov-content-pr-344.herokuapp.com/health-care/eligibility/active-duty/

---

@DanielleSoCompany commented on [Wed Jun 26 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-505838155)

PDF with link to preview page sent to SMEs for review. To note: We sent this content for review previously, as part of the first batch of health care content, but didn't receive feedback/approval. Sending again to ensure we have approval prior to pushing to production.

**SMEs:** Jeff Grandon and Robin Brown 

@Karak888 for awareness - adding stakeholder review labels and moving to backlog until we receive feedback/approval.

**Note:** This page will need to be built in the CMS, as the health care hub content has been migrated from Github to Drupal in parallel with SME review.

---

@DanielleSoCompany commented on [Tue Jul 09 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-509824690)

@Karak888 We've been told by SME we'll have feedback by 7/12. Moving to Ready so we can either implement or add latest status before moving to Icebox.

---

@DanielleSoCompany commented on [Thu Oct 10 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-511535634)

**7/15 transition update:** 

Hi @Karak888 @jenniferlee-dsva. We just today  received approval, with no changes, on this page: https://vagov-content-pr-344.herokuapp.com/health-care/eligibility/active-duty/

It can be published at any time. Here's what's needed:

- [x] Rebuild page in Drupal
- [x] Edit navigation and crosslinks

**For updating navigation and crosslinks:**

- In left nav

Combine these 2 left nav items into this 1 new page.

![image.png](https://images.zenhubusercontent.com/59ca9629b0222d5de479369c/f8fd9029-3f3a-4012-95c0-9cd9bca9bea6)

- On /service-member-benefits/:
Update this link to point to the new page.

![image.png](https://images.zenhubusercontent.com/59ca9629b0222d5de479369c/61bbecab-3182-44d0-9590-e257074cb18e)

- On /health-care/eligibility/:

Update this link to point to the new page.

![image.png](https://images.zenhubusercontent.com/59ca9629b0222d5de479369c/287d845d-5024-427d-9572-0daf47f247ce)

And update this link to point to the new page.

![image.png](https://images.zenhubusercontent.com/59ca9629b0222d5de479369c/5361be5a-2b62-47ea-bbaf-2890aa931272)

And, combine these 2 related links into 1, linking to the new page:

![image.png](https://images.zenhubusercontent.com/59ca9629b0222d5de479369c/3fa3731c-bae7-4e2a-ba81-120e77292724)

- Look for other potential places to crosslink

---

@DanielleSoCompany commented on [Mon Jul 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-511536356)

@Karak888 Putting this in the Ready colum for next steps.

---

@Karak888 commented on [Thu Jul 18 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-512946823)

@peggygannon  Not sure Randi got to this one or not, but _looks_  like it has been approved, just needs to be published in Drupal? Please check when you get a moment?  Thanks!

---

@jenniferlee-dsva commented on [Wed Oct 09 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-540187316)

Omg. This ticket is so old. 

Here's what needs to happen, based on reading through the ^ historical thread. 

1/ @RLHecht - please use this approved heroku content as your source; please build this page in Drupal. 
https://vagov-content-pr-344.herokuapp.com/health-care/eligibility/active-duty/ 

2/ Please update the links in the left nav - per above Danielle's screenshots. 

3/ When ^ is ready, please have @peggygannon or @AnneHurley do a proofread check and publish. 

4/ Please email Jeff Grandon and Robin Brown that this page is live, and cc me. Please also let @mnorthuis    know, so she can check this off as a blocker from her "Redirect health hub" ticket.

5/ @Karak888 - Once all of the ^ are done, please close this ticket! 

---

@RLHecht commented on [Thu Oct 10 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-540679015)

@peggygannon I have created this page in Drupal and updated the left nav and the other pages that needed new links (thank you, @jenniferlee-dsva for the help!). Could you please review the following before today's deployment:
- the new Drupal page: **node ID 1005**: Active Duty service members and VA health care
- **node ID 809**: VA benefits for service members (I updated the link for "Active-duty service members and VA health care")
- **node ID 31**: Eligibility for VA health care: I updated links in 3 areas and combined two related links into one. See Danielle's old comment above for the ones that needed updating. 

All three of these pages are now in Draft and need to be published. If you can't get to them before today's deployment let me know so that I can uncheck the Menu links since they can only be checked in Drupal when publishing.

Thank you!

---

@jenniferlee-dsva commented on [Thu Oct 10 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-540703782)

@RLHecht  - sorry just noticed one thing. Our section headers should target a max of 70 characters with spaces or fewer. Can we shorten the second H2, myabe to just "Eligibility after separation" (and incorporate the parenthetical information in the body copy of the text)... 

Style guide on section headers: https://design.va.gov/content-style-guide/page-titles-and-section-titles#section-titles

![image](https://user-images.githubusercontent.com/43381063/66594337-f15b6100-eb66-11e9-8207-834f022e1b88.png)

---

@RLHecht commented on [Thu Oct 10 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-540764603)

@jenniferlee-dsva I changed that second bullet and updated the text to put in the info from the parentheses with Anne's help. @peggygannon these are now all ready for you to review so they can go live in tomorrow's deployment. Let me know if you have questions. Thanks!

---

@peggygannon commented on [Thu Oct 10 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18156#issuecomment-540791802)

Hi, all. i review and published this page in Drupal. Should go live with tomorrow's deploy.

**Comment by Karak888** [comment]
Closing this one out (moved from vets.gov)

**Comment by RLHecht** [comment]
@peggygannon the other pages that I updated the links to this new page (nodes are in a comment above) were also saved as drafts and need to be reviewed and published.

**Comment by peggygannon** [comment]
thanks, @RLHecht. I just checked the other 2 pages. they should go live  with today's deploy.
