### ISSUE TITLE
Sort by searchableContent AND introText instances found

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#23911]
# Description

**Related slack thread:** https://dsva.slack.com/archives/C52CL1PKQ/p1619557476325100?thread_ts=1619536672.303000&cid=C52CL1PKQ

**Dependency:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/22196 this ticket must be completed **FIRST**.

Change the non-prod staging logic for R&S search to be:

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/8362a871-3514-454e-9803-c3c9c6befc17)

## Acceptance Criteria

- [ ] Replace `// Sort ties then by query word instances found in searchableContent descending` with `// Sort ties then by query word instances found in introText and searchableContent descending` [here](https://github.com/department-of-veterans-affairs/vets-website/blob/e5328976f93cd323a73a19af390e1847e4cd67a2/src/applications/resources-and-support/hooks/useGetSearchResults.js).

**Comment by kelsonic** [comment]
@brianalloyd left sprint + milestone blank for you to modify at your leisure! 🙂 

fysa @jenniferlee-dsva

**Comment by brianalloyd** [comment]
Thanks @kelsonic for spinning the ticket, I've updated sprint + milestone in support.  Thanks for taking point on this initiative.

**Comment by brianalloyd** [comment]
@jenniferlee-dsva  do you have time to validate if you still want the change above to the sorting behavior for R&S? I know your busy and likely miss these in GH so I'll keep calling you out if it helps.

**Comment by jenniferlee-dsva** [comment]
Yes - let's go to production with this logic. Per convo, the changes will be really subtle, because it's changing the sorting logic rather than the filter. When I compare the staging vs prod - they appear identical, so I actually thought this was already live.

**Comment by kelsonic** [comment]
PR merged, should go to prod with the daily deploy today 🙂

**Comment by brianalloyd** [comment]
Closing out, validated.
