### ISSUE TITLE
[FE] My VA: Remove V1 benefits modal from My VA

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#23924]
## Background

The "find VA benefits" FTUX modal still appears on My VA 2.0. We need to remove this.

You can easily make this modal appear by deleting `"find-benefits-intro"` from teh `DISMISSED_ANNOUNCEMENTS` local storage array.

## Screenshot and video

![Screen Shot 2021-04-28 at 12.03.12 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/66e7ab5f-fdd3-43a1-8380-5133cf9176e2)

https://user-images.githubusercontent.com/20728956/116442829-d06d6600-a807-11eb-85e6-69e94a494279.mp4

**Comment by erikphansen** [comment]
Can be validated by staging by signing in private/incognito mode to confirming that the modal does not appear when visiting My VA

commit hash `43871dd96966ddd7b708a49c7756c7f1ab13419b`: https://frontend-support-dashboard.vercel.app

**Comment by ajakabcin** [comment]
confirmed
