### ISSUE TITLE
Questionnaire Manager feature should be accessible to users in participating locations only

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#23929]
## User Story
**In order** to interact with the Questionnaire Manager and fill out pre-visit Questionnaires
**As a** Veteran
**I want** the pre-visit questionnaire feature to be available only at participating locations

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- The Questionnaire Manager feature must be available to all veterans in participating locations only. If a user happens to visit the feature page and they are not part of a facility that's in the pilot, then do not let them proceed with the feature.

**Comment by dillo** [comment]
@mlighdc could I get the ID of the pilot location?

**Comment by dillo** [comment]
per @stephenBarrs the Facility ID for the participating facility is: 605

**Comment by mlighdc** [comment]
@dillo just for additional context and more for terminology 605 is the station number for the Jerry L. Pettis Memorial Veterans' Hospital. We been calling it Loma Linda but Jerry L Pettis is the official name :-) in the VA systems.
