### ISSUE TITLE
Show the time-zone for the appointment on the PDF

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#23925]
## User Story
**In order** to know the accurate appointment time for the facility and location where I'm scheduled
**As a** Veteran
**I want** the Questionnaire Response PDF to display the time-zone of the facility next to the appointment time

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
- When a veteran generates a Questionnaire Response PDF for a questionnaire that they've submitted, they should be shown the time in the time-zone of the facility next to their appointment time so that it will always remain the same no matter from which geographic location they view the PDF from.

**Comment by kristenmcconnell** [comment]
@joshkimux Here is the ticket that the rest of the PDF work for completed health questionnaires will be completed. As stated, we are interested in feedback on PDF accessibility. @dillo (engineering) and I are the people that you can coordinate feedback with.

**Comment by joshkimux** [comment]
@kristenmcconnell @dillo Awesome! Is there a sample PDF I could start testing with?
Otherwise, [y'all can also run the tests by following this tutorial](https://www.adobe.com/accessibility/products/acrobat/using-acrobat-pro-accessibility-checker.html) as a starting point.

**Comment by joshkimux** [comment]
Raising awareness to @1Copenut who has been working on 508 PDF accessibility errors in ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/11446

**Comment by dillo** [comment]
@joshkimux here's an example PDF file: [https://app.zenhub.com/files/133843125/3dd6289a-2348-40f9-b108-364856cd701d/download](https://app.zenhub.com/files/133843125/3dd6289a-2348-40f9-b108-364856cd701d/download)

**Comment by joshkimux** [comment]
<h1 id="reportTop" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Accessibility Report</h1><dl style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><dt style="float: left; clear: left; margin-right: 5px; font-weight: bold;">Filename:<span class="Apple-converted-space"> </span></dt><dd style="margin: 0px;">test.pdf</dd></dl><dl style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><dt style="float: left; clear: left; margin-right: 5px; font-weight: bold;">Report created by:<span class="Apple-converted-space"> </span></dt><dd style="margin: 0px;">Joshua Michael Kim</dd><dt style="float: left; clear: left; margin-right: 5px; font-weight: bold;">Organization:<span class="Apple-converted-space"> </span></dt><dd style="margin: 0px;"></dd></dl><p style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">VA</p><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Summary</h2><p style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">The checker found problems which may prevent the document from being fully accessible.</p><ul style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-size: 11.199999809265137px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><li style="list-style: square;">Needs manual check: 2</li><li style="list-style: square;">Passed manually: 0</li><li style="list-style: square;">Failed manually: 0</li><li style="list-style: square;">Skipped: 1</li><li style="list-style: square;">Passed: 12</li><li style="list-style: square;">Failed: 17</li></ul><h2 style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Verdana, Geneva, sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Detailed Report</h2>

Document
--

Accessibility permission flag | Passed | Accessibility permission flag must be set
Image-only PDF | Passed | Document is not image-only PDF
Tagged PDF | Failed | Document is tagged PDF
Logical Reading Order | Needs manual check | Document structure provides a logical reading order
Primary language | Failed | Text language is specified
Title | Failed | Document title is showing in title bar
Bookmarks | Passed | Bookmarks are present in large documents
Color contrast | Needs manual check | Document has appropriate color contrast
Page Content

Tagged content | Failed | All page content is tagged
Tagged annotations | Passed | All annotations are tagged
Tab order | Failed | Tab order is consistent with structure order
Character encoding | Passed | Reliable character encoding is provided
Tagged multimedia | Passed | All multimedia objects are tagged
Screen flicker | Passed | Page will not cause screen flicker
Scripts | Passed | No inaccessible scripts
Timed responses | Passed | Page does not require timed responses
Navigation links | Passed | Navigation links are not repetitive
Forms

Tagged form fields | Passed | All form fields are tagged
Field descriptions | Passed | All form fields have description
Alternate Text

Figures alternate text | Failed | Figures require alternate text
Nested alternate text | Failed | Alternate text that will never be read
Associated with content | Failed | Alternate text must be associated with some content
Hides annotation | Failed | Alternate text should not hide annotation
Other elements alternate text | Failed | Other elements that require alternate text
Tables

Rows | Failed | TR must be a child of Table, THead, TBody, or TFoot
TH and TD | Failed | TH and TD must be children of TR
Headers | Failed | Tables should have headers
Regularity | Failed | Tables must contain the same number of columns in each row and rows in each column
Summary | Skipped | Tables must have a summary
Lists

List items | Failed | LI must be a child of L
Lbl and LBody | Failed | Lbl and LBody must be children of LI
Headings

Appropriate nesting | Failed | Appropriate nesting
