### ISSUE TITLE
Make type of care selection ux more obvious

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2393]
As a veteran, I'm confused about how many things I'm supposed to pick from the type of care list because I see several categories - do I need to pick something from each?

AC
- [ ] UX & content makes it more clear / obvious to veterans that only one selection should be made.
- [ ] Grouping is the same
- [ ] Types of care use patient-friendly names from Andy's list

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/67861891-7ea32d00-faf7-11e9-836a-c38f000dbc19.png)

**Comment by markgreenburg** [comment]
Dupe of #3380
