### ISSUE TITLE
[UI] Post appointment Wireframes

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#23939]
## Description
Create an initial draft wireframes for post appointment experience that is part of the check-in project. The intent would be for these to be presented to stakeholders, product teams, and internal team members for discussion.

## Tasks
- [ ] Create draft wireframes in Sketch

## Acceptance Criteria
- [ ] Initial wireframe draft is complete and reviewed by product/Ming

**Comment by loripusey** [comment]
@kristenmcconnell this ticket was created almost a year ago, do we still need it?

**Comment by kristenmcconnell** [comment]
No. It can be closed.
