### ISSUE TITLE
Investigate full claims history not displaying

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#23930]
During a UAT session a user said their full claims history was not displaying

### Notes
User mentioned that the older version of the app displayed a fuller history than the most recent build; some claim types that are on va.gov are not on the app.

### Reference
[UAT Issues Sheet](https://docs.google.com/spreadsheets/d/1swOSRwSo2ULYFuzghiDYlX3qXm8_bD5dorAmxfAiMlI/edit#gid=0)

**Comment by jperk51** [comment]
Issue was related to date filtering that was added the day before this participant reported the issue. The date filtering has since been changed so the default will return all claims and appeals, not just the ones updated within the past year.
