### ISSUE TITLE
Audit of Subdomain Sites that currently do not have VA official header and footer

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2394]
Liz will make a list of subdomains that currently don't have our official header and footer.
- Will be note TeamSite template sites vs. weird custom file sites or sites that Platform team needs to take a closer look at.
- Will start with VHA area.
- Then other areas that appear in our About VA mega menu.

**Comment by andaleliz** [comment]
@jenniferlee-dsva Can you please take a look at the attached spreadsheet and let me know how this lines up with what you were expecting?  

I've gone through all the links in the VA Mega Menu, and all the left sidebar links under VHA and Benefits pages.  As I started to go through the sidebar links on other sections of va.gov, I kept hitting the same sites over and over, so it feels like I exhausted those. Happy to do another pass if you have a sense things might be missing.

Thanks, looking forward to your feedback!
 
[subdomain_header_footer_audit.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3726906/subdomain_header_footer_audit.xlsx)

**Comment by Karak888** [comment]
@jenniferlee-dsva will review.

**Comment by jenniferlee-dsva** [comment]
Looking now @andaleliz

**Comment by andaleliz** [comment]
[subdomain_header_footer_audit.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3744412/subdomain_header_footer_audit.xlsx)

@jenniferlee-dsva Here's the updated file you requested - new column indicating if it is a subdomain, and another column to indicate if it's linked to from the About Us megamenu.  Only urls with direct links from that menu are indicated with an X.

**Comment by jenniferlee-dsva** [comment]
Thank you Liz!

**Comment by Karak888** [comment]
@jenniferlee-dsva per our check-in yesterday with the thumbs up, I am going to close out this ticket, thanks!
