### ISSUE TITLE
General Analytics Request for Search & Discovery

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#23948]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description

- Search & Discovery would like some help to interpret and validate the data we are seeing as as result of POC2 for typeahead. We established a list of hardcoded suggestions which appear with terms from search.gov algorithm to improve the user experience by offering a set of suggestions that a user may click on to improve their search experience. For each of the terms we hardcoded we validated that a relevant match would appear in the top 4 results appearing on the results page. We expected as a result that the Typeahead conversion rate would be comparable but ideally higher than the conversion with typeahead. The data is telling the opposite story showing an overall typeahead conversion rate (row 7 on attached spreadsheet) of 8.86%

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

Search & Discovery / Typeahead 

    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

As soon as possible because we would like to be able to report on the outcomes of our POC2.

## Analytics to Track Down
> Examples
> 
> - [ ] Conversion Rates
> - [ ] Metric 2
> - [ ] Metric 3

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
[Typeahead DOMO Dashboard ](https://va-gov.domo.com/page/439942537?userId=1724393873)

Search & Discovery Data Summary Spreadsheet: 
[https://app.zenhub.com/files/133843125/c6149edc-bca5-4a8f-8288-b9009a806bd8/download](https://app.zenhub.com/files/133843125/c6149edc-bca5-4a8f-8288-b9009a806bd8/download)

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by srsuddath** [comment]
As per our discussion, I will add new google analytics tagging to allow the tracking of whether or not typeahead was used in our onsite-search-results-click event.

**Comment by srsuddath** [comment]
All, the new analytics tagging added to the onsite-search-results click will be the following variable:
search-typeahead-used
which will be true when a suggestion was clicked to get to the search results page, or false any other time
this tagging will be added as part of the following PR
https://github.com/department-of-veterans-affairs/vets-website/pull/16960

**Comment by srsuddath** [comment]
This PR has been merged and should be available on staging shortly

**Comment by denisecoveyduc** [comment]
Hi @laurensimpson14 following up on this review request. As a result of the meeting you had with @srsuddath last week I understand you were reviewing the data we are seeing on the Typeahead Domo Dashboard to ensure that it is indeed telling us the story that we are interpreting. Could you provide us with a timeframe of when you think you will be able to share your findings? 

cc: @johnhashva  @joanneesteban

**Comment by srsuddath** [comment]
Also just to tack onto this comment, the analytics tagging has been updated. on all onsite-search-results-click events a search-typeahead-used flag is set to true when typeahead is used

**Comment by denisecoveyduc** [comment]
Created an analytics request to establish a GA custom dimension for search-typeahead-used #24482
