### ISSUE TITLE
Determine if other warnings are hidden with lambdas

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#23955]
Created out of https://github.com/department-of-veterans-affairs/va.gov-team/issues/23853
- This can be done concurrently with #23953

### AC
- [ ] X

**Comment by ericboehs** [comment]
Something to note, lambdas can also be called like so:

```ruby
my_lambda = lambda { puts "hello" }

my_lambda.call
my_lambda.()
my_lambda.[]
my_lambda.===
```

**Comment by ericboehs** [comment]
Related: #23953.
