### ISSUE TITLE
Content Feedback - Midpoint review - Notice of Disagreement

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#23951]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
@vhenry07 @kevinstachura 

Platform NOD midpoint content review. Please let me know if you have any questions. 

**Questions**
1. Some of the content on the static page in the mockup doesn’t match content on live static page Some examples: 
-	Judge is capped in the intro
-	Coronavirus is capped in the alert
-	Go to Frequently Asked Questions (FAQs) link language is different than link on live site (Go to FAQs)


2. What is the correct language for the “Track status of claim” Blue CTA button? 
On Prototype static page this button says:  Track the status of your claim 
Live page says Check your VA claim status
On Prototype Confirmation page says: Track the status of your claim or appeal

3. Language for the Request Board Appeal action links is different. Recommend that this language be aligned
On static page it’s>  Request a Board Appeal
On subway map page it’s> Start the Board Appeal request

4. Should phone number in Need help? footer list the general help number, 800-698-2411?  


**Should feedback** 
1. Please hyperlink all phone numbers (for example,  (711)
2. On Additional evidence screen: Change “at” to “to” in this sentence: You can also send it by fax to: 
3. On Review your request screen: 
Representative name label should align with how it appears on earlier screen:   Representative or VSO name 

4. On Confirmation page: 
Please rewrite the content under “What should I do while I wait?” header to refer to VA in first-person (per VA.gov style guide)
VA > we
You don’t need to do anything unless we send you a letter asking for more information. If we schedule any exams for you, be sure not to miss them. 
If you requested a decision review, and haven’t heard back from us yet, please don’t request another review. Call us at [800-827-1000](hyperlink).


**Consider feedback**

1. On Issues eligible for review screen
Consider positioning Add issue button closer to the reference to this button that is in the intro. 

2. On Add issue content
Consider tweaking first sentence in this intro TO: Add issue and the issue’s decision date. 

3. On Board review option screen
Consider removing VLJ acronym from this content, as acronym isn’t used on subsequent screens. 

4. Under virtual tele-hearing content: 
Should Veterans representatives be written as “your representative”
As currently written, it sounds like Veterans representatives isn’t “their” representative. 

5. Under in-person hearing content
Is Central Office hearing another term for this type of hearing? Recommend we use consistent language for how we refer to the hearing, or rewrite to “These hearings….”

6. On Upload additional evidence screen, consider tweaking content to avoid repeating document types in intro and in bullets. 
Can users also scan to a tablet?  Also, consider adding “tablet”

possible tweak to:  You can scan a copy of your document onto your computer, tablet, or mobile phone. You can upload your document from there. 
Guidelines for uploading a file: 
-	You can upload a .pdf, .jpeg, or .png file
-	Your file should be no larger than 100MB

**Comment by kevinstachura** [comment]
Hi @peggygannon!

Sorry for the late response on this! I worked through a lot of this content with Beth, and have added all of the 'should' feedback you have suggested here. Let me know if you have any questions. The prototype can be accessed here:

https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538562

Thanks!
