### ISSUE TITLE
CT Redesign: Add autocomplete menu to search by location

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23959]
As a developer, I need to add an autocomplete menu to the search by location field so that it can be usability tested.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. "Use my current location" is out of scope for this story.

## Acceptance Criteria
1. The autocomplete menu displays up to a maximum of 6 results in addition to the user entered term
2. If the user selects a value from the list the search field is populated with the value.

### Technical considerations:
1. There should be a delay on the search, so a search is not performed on every keystroke.  Similar to the current comparison tool autocomplete behavior.
2. Example cities to search for: springfield, washington, london

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/37IAGO4DHZG)
2. [Public Prototype Link](https://bahdigital.invisionapp.com/share/37IAGO4DHZG#/296059390_State_Search)

**Comment by dmccurdybah** [comment]
PRs:

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/823
- https://github.com/department-of-veterans-affairs/vets-website/pull/17286

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1920)

**Comment by delli-gatti-michael** [comment]
Closing this out
