### ISSUE TITLE
CT Redesign:  Add content for when no search results are displayed

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23952]
As a developer, I need to add content for when no results are found using the redesign search by location functionality so that users know during usability testing that the search was unsuccessful.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

#### For name search
1. If filters have been applied and no search results are found, the following content is displayed:

    > We didn't find any institutions based on the filters you've applied. Please update the filters and search again. 

#### For location search
2. When no locations are returned due to searching:
    a. The "Update tuition and housing estimates" control is not displayed.
    b. The "Filter your results" control is not displayed.
    c. If the text search was used the map view shows the entire continental United States 
    d. If the map search was used the map view shows the current zoom level
    e. The following content is displayed:

    > We didn't find any institutions based on your search. 
    > 
    > **For better results:**
    > - **Zoom in or out** to view a different area of the map, or
    > - **Move the map** to a different area
    > 
    > Then click the **“Search this area of map”** button.
    > 
    > If we still haven't found any facilities near you, **please enter a different search term** (street, city, state, or postal code).

3. If filters have been applied and no locations are found, the following content is displayed:

    > We didn't find any institutions near this location based on the filters you've applied. Please update the filters and search again. 

## Supporting Artifacts:
1. [Prototype - Location Search with no results](https://bahdigital.invisionapp.com/d/main#/console/14222691/296060311/preview)
2. AC1 Mockup
<img width="1029" alt="Screen Shot 2021-07-07 at 11 32 48 AM" src="https://user-images.githubusercontent.com/48260534/124788195-243ab080-df17-11eb-9a79-59ec0c6ce0d6.png">
3. AC 3 Mockup
<img width="1029" alt="Screen Shot 2021-07-07 at 11 29 21 AM" src="https://user-images.githubusercontent.com/48260534/124788230-2a309180-df17-11eb-87b4-3c08e0a54abd.png">

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17877

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2010&group_by=cases:section_id&group_order=asc
