### ISSUE TITLE
CT Redesign: Add Use my current location functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23967]
As a developer, I need to add use my current location functionality to the redesign search by location so that it can be tested during usability testing.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. Outlined behavior is similar to [facility locator](https://www.va.gov/find-locations/)

## Acceptance Criteria:
1. The user can elect to search using their current location (determined using browser location data)

2. After electing to use their current location:
    a. while retrieving the current location the link is updated to indicate that the request is processing.
    b. the search field is populated with the users street name (with number), city, state if in the US
    c. the search field is populated with the current street name (with number), city, country if outside the US

3. After executing the search the users current location is marked with a red pin.

4. If the use of the users current location is blocked by the browser, the user is notified that the functionality has to be enabled.

5. If there is an error while the using the browser location data the user is notified of the error.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296060306_Searchbylocation_Desktop)
2. [Get Browser Location Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition)
3. AC1 - Note, the screenshot is from the facility locator for reference.  The prototype shows the search field / link accurately.

    > <img width="474" alt="AC1" src="https://user-images.githubusercontent.com/48260534/119135499-8180ae00-ba0c-11eb-976a-82785af435a3.png">

4. AC2 - Note, the screenshot is from the facility locator for reference.  The prototype does not show this functionality.
    
    > <img width="474" alt="AC2a" src="https://user-images.githubusercontent.com/48260534/119135542-8fceca00-ba0c-11eb-94da-b34bf7853d55.png">

5. AC4

    > <img width="611" alt="AC3" src="https://user-images.githubusercontent.com/48260534/119135582-9e1ce600-ba0c-11eb-83b7-2bbb27b071d1.png">

6. AC5

    > <img width="611" alt="AC4" src="https://user-images.githubusercontent.com/48260534/119135670-b7be2d80-ba0c-11eb-896c-3c440f3d595e.png">

**Comment by ksantiagoBAH** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17557

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1956&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA.
