### ISSUE TITLE
508-defect-2 [FOCUS]: Focus must remain on the copy link button after use

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#23968]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Details

After the button is activated, focus is lost. When the button is made to be accessible, it's important that focus remains on the copy link button so Veterans don't need to tab all the way through the page to return to where they left off.

## Acceptance Criteria

- [ ] Focus remains on the button after use

## Steps to Recreate

Click on the copy link button and then press `tab`, confirm that focus is lost and thrown to the very top of the page.

## Screenshots or Trace Logs

https://user-images.githubusercontent.com/14154792/116464731-530f1900-a83a-11eb-8f38-aeeeda804606.mov

**Comment by SKasimow** [comment]
@youngfreezyVA another lower-level bug for anchor tags...

**Comment by youngfreezyVA** [comment]
yup, this is a quick one & was working before

i accidentally introduced this bug when i swapped out the onClick handlers for another accessibility bug 🙃

**Comment by joshkimux** [comment]
Great work! 🔥 

https://user-images.githubusercontent.com/14154792/118318886-fe210300-b4c7-11eb-817d-e06b87d9d1c0.mov
