### ISSUE TITLE
Sleep medicine content

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2396]
As a veteran, I want more information about the difference between home sleep testing and CPAP so that I can make an informed choice about the type of care I want to schedule.

Page to update:
<img width="817" alt="Screen Shot 2019-10-11 at 1 20 38 PM" src="https://user-images.githubusercontent.com/24251447/66674968-f2a19200-ec29-11e9-9ef1-8e7765c33eab.png">

New Content:

Choose the type of sleep medicine appointment that you need

[Continuous Positive Airway Pressure (CPAP)]
This includes an office visit to set up or fix your CPAP machine. You shouldn’t book a CPAP appointment if you want to schedule a sleep study or if you have an undiagnosed sleep issue.

[Sleep medicine and home sleep testing]
This includes an office visit for the diagnosis and treatment of sleep problems, such as difficulty sleeping or breathing, snoring, teeth grinding, and jaw clenching. You can also choose this type of appointment if you want to schedule a home or lab sleep study.

AC
- [ ] Content updated for sleep medicine follow up page
- [ ] Updated content is implemented in the front end.

**Comment by peggygannon** [comment]
@lalexanderson-dsva Please see my content suggestions below.  I still need to review all the VAOS headers to see if they are best as statements or questions. I'll be making that recommendation when I do a content review of the full flow in prototype. 

Choose the type of sleep medicine appointment that you need
•	**Continuous Positive Airway Pressure (CPAP)**
This includes an office visit to set up or fix your CPAP machine. You shouldn’t book a CPAP appointment if you want to schedule a sleep study or if you have an undiagnosed sleep issue. 

•	**Sleep medicine and home sleep testing**
This includes an office visit for the diagnosis and treatment of sleep problems, such as difficulty sleeping or breathing, snoring, teeth grinding, and jaw clenching. You can also choose this type of appointment if you want to schedule a home or lab sleep study.

**Comment by lalexanderson-dsva** [comment]
@peggygannon these edits look great.
