### ISSUE TITLE
Fetch 12 months of upcoming appointments

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23973]
## User story
As a user, if I have confirmed/upcoming appointments over the next year, I want to see these in the VA mobile app. 

## Acceptance Criteria
1. When making the call to load upcoming appointments, request 12 months of appointments

Note for dev: currently, the frontend is fetching 6 months

**Comment by ashley-matthews** [comment]
@bessgreen  just adding some labels on here so that we can keep track of a UAT board.

**Comment by digitalken** [comment]
PASS 5/25/2021 - Have about 12 months upcoming appointments.  Closing.
