### ISSUE TITLE
Clarify emergency content on 'reason for appointment' page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2397]
We have received feedback that some veterans are booking 'emergency'-type appointments (e.g., chest pain) through vaos instead of going to a hospital / emergency room. To help push them in the right direction, we want to add content to the 'reason for appointment' page that clarifies VAOS is for non-emergency appointments.

Page to update:
![Reason For Appointment Page](https://user-images.githubusercontent.com/24251447/66426488-8e878f80-e9d7-11e9-8ebf-4430c31ecf18.png)

AC
- [ ] Content updated to dissuade from booking emergency care via VAOS
- [ ] Updated content added to the front end

**Comment by markgreenburg** [comment]
@rtwell is this page still where you'd like to introduce some text about emergency care, or would you prefer to do that on a different page in the flow?

**Comment by rtwell** [comment]
i think this is def one of the place we'll need to drop in that messaging, yes—we could probably component-ize it so we can use it throughout the flow(s) cc @peggygannon

**Comment by peggygannon** [comment]
@rtwell @markgreenburg Please see below for my content recommendation for content about emergency care. Can you let me know if I've captured all the pertinent info that we need to convey with this message? 


With the VA appointment tool, you can schedule, view, and organize some of your VA health care appointments online. The VA appointment tool is for non-emergency appointments only, like routine check-ups or doctor visits. 
Don’t use the VA appointment tool if you have a medical emergency and need to see a doctor right away. If you have an urgent medical need, please:
- Call [911], **or** 
- Go to your nearest emergency room or VA medical center. [Find your nearest VA medical center](va.gov/find-locations/)

**Comment by narin** [comment]
Should be a quick fix. @rtwell What are we thinking for the design for this.  Yellow or light blue Alert box?  Should it appear below or after the existing form elements?

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/70531747-91ac1280-1b23-11ea-9611-9c383ea72406.png)

**Comment by rtwell** [comment]
i think for MVP, we should pare this down to the second half of what Peggy wrote:

**If you have an urgent medical need, please:**

- Call [911], or
- Call the Veterans Crisis hotline at [800-273-8255] and press 1, or
- Go to your nearest emergency room or VA medical center. Find your nearest VA medical center

thank you!
