### ISSUE TITLE
VANotify 2 way integration

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#23972]
https://dsva.slack.com/archives/C01D2T36XLL/p1617300986022000?thread_ts=1617300863.021900&cid=C01D2T36XLL

**Comment by Kennon-git** [comment]
Rob talked to philipe about supporting a fail over endpoint for the VEText api. a secondary api for vanotify. 

sqs service in aws - a message bus. several advantages, even if VEText was completely down there wouldn't be need for vanotify to retry, once VEText is back online it would check bus and grab messages that need to be processed. 

would require some development work, but would take care of auth and fail over mechanism. 

s- we don't have an aws account, can ask philipe if he can host it in his account. 
do we need that before we start two way messaging? we have an extra short code for prescriptions

**Comment by Kennon-git** [comment]
Rob testing end to end this week with filip. 

once we are using va notify for messaging, this is also a possible solution for prescription tracking.

**Comment by kjduensing** [comment]
SQS is working fine.

Currently Poll SQS for this use case. Currently writing code for long polling

Next up: E2E testing w/ VANotify (they have some work to do before this - Phil working on this now).

**Comment by kjduensing** [comment]
waiting on VANotify work to be complete. Our work is largely done. Need to test directly with VANotify.
