### ISSUE TITLE
Update Next / Previous month calendar UX

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2398]
As a veteran, I am confused about what the next / previous buttons do on the datepicker, because I don't know if those are meant to advance the form or advance the date on the current page.

AC
- [ ] Mocks for next / previous calendar interaction are updated and attached to this ticket.
- [ ] Veterans clearly understand the difference between the calendar controls and the form controls.

**Comment by markgreenburg** [comment]
@rtwell these are consolidated findings from usability re. the calendar widget - I think you and @narin have already been talking about proposed changes via other tickets. Please feel free to close this if no longer applicable.

**Comment by jbalboni** [comment]
@markgreenburg @rtwell Is this still a relevant ticket?

**Comment by markgreenburg** [comment]
Seeing some behavior in UAT that might warrant some tweaking with regard to what hitting 'next' does and how many months show. But not quite sure yet and quite frankly we've only had 4 sessions. Let's keep this open for now, but moving to backlog.

**Comment by lenaecb** [comment]
@jbalboni - is this still an issue?

**Comment by jbalboni** [comment]
@lenaecb I think that's up to @rtwell. If he wants us to make changes, we can, but we don't have any outstanding design changes to implement that I'm aware of.

**Comment by rtwell** [comment]
it doesn't sound like an issue has come out of UAT. Let's close and address if it comes out in the next round?
