### ISSUE TITLE
Business intake form for Debt Resolution | FSR 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#23983]
## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)
Already in place

**Comment by miabecker** [comment]
https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138138134/simulate/sitemap?mode=i

**Comment by miabecker** [comment]
@leahkeeler Just want to confirm that this is a form that the Veteran will be filling out online on VA.gov? Also are you working with a developer / technical resource in terms of developing the form on VA.gov. When do you think you'll have a content draft? 

In terms of road to production, once you have content, we could create templates IDs and hand them to your development resource to plug in and test in staging. cc: @bevnobev @ffafara-tw

**Comment by bevnobev** [comment]
Adding @LindaLi123 as she is taking over from @leahkeeler

**Comment by miabecker** [comment]
Hi @LindaLi123 and @leahkeeler per your request sending through some examples of email confirmation for form submissions in vets-api codebase. Waiting to hear from you on content, and the timeline for us to begin building your notifications template!

app/workers/form526_confirmation_email_job.rb
which is triggered from app/models/form526_submission.rb 
 modules/covid_vaccine/app/jobs/covid_vaccine/registration_email_job.rb 
which is triggered from below

modules/covid_vaccine/app/services/covid_vaccine/v0/registration_service.rb 
modules/covid_vaccine/app/jobs/covid_vaccine/expanded_registration_email_job.rb triggered from modules/covid_vaccine/app/controllers/covid_vaccine/v0/expanded_registration_controller.rb

There is another email on application connection/disconnection that lighthouse team is sending here 

modules/apps_api/lib/apps_api/notification_service.rb

Direct deposit changes trigger this email job app/workers/va_notify_dd_email_job.rb

and it’s triggered here 

app/controllers/v0/profile/ch33_bank_accounts_controller.rb and here app/controllers/v0/ppiu_controller.rb
