### ISSUE TITLE
Discharge Upgrade Wizard: Update DD149 PDF link on DD214 Request Page

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23988]
### What's the Problem
1. The DD 149 PDF download link contained on the [upgrade discharge status wizard DD214 request page](https://www.va.gov/discharge-upgrade-instructions/request-dd214) does not open properly in some browsers. The PDF form is located at this URL https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf.   Instead of seeing the PDF form, the user gets this confusing message:

![Broken PDF Form Link](https://user-images.githubusercontent.com/63107147/112183219-6c39ff80-8bd4-11eb-977f-211604bfdfb7.jpg)

(Tried VA PC on VPN, personal Mac laptop, personal and VA iPhones). 

### What's the Cause

This is a well-known issue. It has to do with the fact that some VA businesses and non-VA businesses are creating PDFs in a dynamic XFA format of Adobe PDF.  (The form you reference is in fact a DOD form, so not created by VA in this instance.) The dynamic XFA Adobe format happens to be the very latest version of PDF formats, and many in VA – and looks like at the DOD as well -- mistakenly believe that the 21st Century Idea Act requires VA to use the very latest Adobe PDF format without regard to whether it is supported by browsers. Unfortunately, this newer dynamic XFA format is not supported by the International Organization for Standardization - ISO. And because it isn’t supported by the ISO, modern browsers like Chrome, Safari, Firefox don’t support it either. 

### What's the Solution

- Change the URL link in the Download CTA to this MilConnect FAQ https://www.dfas.mil/correctmilitaryrecords/ which links to an older version of the DD 149 form. This older version opens okay in the browser: https://www.dfas.mil/Portals/98/Documents/CorrectMilitaryRecords/dd0149.pdf?ver=2020-01-08-143351-750

**Comment by zacharymorel** [comment]
Closing this due to the Form now working! 
Going to revert the existing changes. 

See - > https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf

**Comment by MarciMcGuireGCIO** [comment]
Tested on Windows, iPhone. I still get the Please Wait image on iPhone. @zacharymorel I suspect you may have changed your default PDF opener on iOS to Adobe Acrobat Reader. Since this PDF still produces an issue, we need to proceed with changing the PDF link to https://www.dfas.mil/Portals/98/Documents/CorrectMilitaryRecords/dd0149.pdf?ver=2020-01-08-143351-750

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO did you test this page => https://www.va.gov/discharge-upgrade-instructions/guidance

**Comment by zacharymorel** [comment]
Oh wait, nvm, I see this user story is referring to https://www.va.gov/discharge-upgrade-instructions/request-dd214

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel I commented on both issues because the first one had been re-opened in anticipation of changing the link back, and this one had been closed because we thought the PDF was working.

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel did you get any feedback on this one yet?  Thx!

**Comment by zacharymorel** [comment]
Not yet, I ping again.

**Comment by zacharymorel** [comment]
This should be on Staging within 30mins

**Comment by MarciMcGuireGCIO** [comment]
Thanks @zacharymorel !  I saw it, and it looks great!

**Comment by MarciMcGuireGCIO** [comment]
Update - based on an email we received this morning, the original URL https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd0149.pdf is, in fact, the correct one that the DoD wants on this page.  The original issue is related to the XFA format, which prevents the PDF from opening in the browser.  It must be downloaded.

**Comment by zacharymorel** [comment]
So, due to CORS and the PDF link domains not being the same as va.gov, we will need an "alert" or notification teach the vets to right click on select _"save link as"_ to download the PDF.

**Comment by MarciMcGuireGCIO** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25065 now nullifies this request since the DoD has clarified that the PDF link that originally was on this page was in fact the most current.  The issue with the error message is related to XFA and requires the user to download.
