### ISSUE TITLE
Message data isn't clearing between sessions

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#23984]
## What happened?
When logging out of User A and logging into User B, some of the message data from User A is still visible, including their Custom Folder list.

## Specs:
- Device: iPhone 11
- Test users: 41, 261

## Steps to Reproduce
1. Log in with +41. Go to the Folders page of SM. Observe the list of custom folders.
2. Log out
3. Log in with +261. Go to the Folders page. Observe that the list of custom folders is the same as user 41.

## Desired behavior
When a user logs out, their data isn't cached. 

## Acceptance Criteria
1. Clear cache message data between users. This includes:
      - Inbox messages
      - Sent messages
      - Custom folders list

## Bug Severity
- 2 - High

## Linked story
n/a

## Screen shot(s) and additional information
n/a

**Comment by digitalken** [comment]
PASS 5/3/2021 - Looks good, no old data.  Closing.
