### ISSUE TITLE
Access for Denise Coveyduc

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#23994]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Denise Coveyduc
- Please Provide your email.
   >dcoveyduc@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Name: Search & Discovery
   > My Role: Product Manager
   > Company: Government CIO

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd0ssl0Dq6pFVXkSf8vhhhOxkQVdZ2TvorVJv9c3Nhe6PCINUOUV5BQjY0RKw2MQ6hwhhiLgMYXLYIf3lOapeOr6WfCxhctLBHrTn9k3IcIyDwuJUcVZQ6B+8FMtgygMR7MUzEqmDW6WHlE6MWdg9GWVhwt7/iE2VU2bTTrqLIWtPdDRrdnxVqWHxOCkHwgEFpeTjKCtCVTotysIvledZqLecHO7g9IFdtd0sUVvSwUBcgImd8cPgUATwNOS0d2RhYmsQJeMwYIeuY6HvcbCRaPGHhrrlh9pBj4C98acGsGlSh3lmU0qbPFMrMZES8nsF524qJBBsWoa1ot0RO8h3kL9oddPZynrpnSvKU5T/PpTaEyRWXUm/zivYPNXClPx8KIYydjknKQ+qzILYiVutFPgWp0DMsXn+YSAF/saisX25uIBPQa4AiGbl6GKZV/Yyb74QEakMBK61LTFocSQL7ZvR0jbDoem9SjsvL/ZjkVryNDZEM29OkLFIb/nbnNUc= denisecoveyduc@denises-mbp-2.lan
```

- Grant AWS Console access?
  >  NO
  - What AWS services do you need access to and why?

**Comment by mleclerc00** [comment]
Whoops, you can ignore my last message given you don't require AWS access

**Comment by denisecoveyduc** [comment]
@mleclerc00  I just tested it out and was able to connect to our review instances!Thank you for all your help.
