### ISSUE TITLE
Up To Top Button does not render on IE

### ISSUE THREAD

**Issue by brangi** [department-of-veterans-affairs/va.gov-team#23999]
## What happened?

Up To Top Button does not render on IE 11

## Steps to Reproduce
visit  https://www.va.gov/resources/can-i-get-a-replacement-gi-bill-benefit-certificate-of-eligibility/
scroll to bottom

 ## Screenshot
Works on edge but not on IE
<img width="1112" alt="Screen Shot 2021-04-29 at 10 52 12 AM" src="https://user-images.githubusercontent.com/100468/116580560-19d9b600-a8d9-11eb-8b66-b95e5fc322bd.png">

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
@MarciMcGuireGCIO @zacharymorel would you have some bandwidth to work this ticket into your sprint cycle?  I believe @zacharymorel created the B2T component and might be best suited to work this fix.  No issue if not, we can work in when we have bandwidth.  Thanks.

**Comment by MarciMcGuireGCIO** [comment]
@brianalloyd ,I believe @zacharymorel does have some bandwidth this sprint. We'll talk about it in our sprint planning this afternoon. Thank you!

**Comment by brianalloyd** [comment]
Thanks @MarciMcGuireGCIO appreciate it.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Looking towards the end of this thread about the issue. 
Appears VSP will tackle the IE11 mystery!

https://dsva.slack.com/archives/C52CL1PKQ/p1619709144385600

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @zacharymorel . I will take this off our list.

**Comment by brianalloyd** [comment]
@zacharymorel could you link me in with the VSP engineer that is working this issue?  Just wanted to close the loop with them in support.  TIA

**Comment by zacharymorel** [comment]
Hello Brian! 

Here's the support ticket for VSP => https://github.com/department-of-veterans-affairs/va.gov-team/issues/24309
I believe @cvalarida might be our best bet.

**Comment by brianalloyd** [comment]
Closing this ticket as issue is being handled by VSP.
