### ISSUE TITLE
[Reported Bug] Outreach and Events Add to Calendar

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#23991]
## What happened?
A VA.gov user reports that Outreach & Events "Add to Calendar" don't work as expected and the files appear to be corrupted.   A VA stakeholder tested  this and when it opens directly in Outlook it is fine, but when you save it to the desktop and try to open it (MacOS+Safari+Calendar) it is corrupted.

I tried recreating on my Mac OS/Desktop and was unable to import the file as seen here:

<img width="1358" alt="Screen Shot 2021-04-29 at 9 37 18 AM" src="https://user-images.githubusercontent.com/63107147/116563884-77b6cf80-a8d2-11eb-81e4-5f25f5b9a197.png">

Per the user who reported the issue:

- Go to: https://www.va.gov/outreach-and-events/events/sexual-harassment-violence-prevention/
(That is just one example. All pages have a file with errors.)
- IF you click on the link "Add to Calendar" it downloads the .ics file that should put the information into the calendar app.
- The files are all corrupted. Do not take my word for it. ANY .ics file is pre text. You can read it with
notepad or any text editor.
- The Problems:
  - EVERY .ics file on the VA.gov web site has this:
    - DTSTAMP:NaNNaNNaNTNaNNaNNaN
    - DTSTART:NaNNaNNaNTNaNNaNNaN
    -  DTEND:NaNNaNNaNTNaNNaNNaN
- Each field needs a 8 digit DATE, a "T" and a six digit TIME, followed by a Time ZONE letter.
  - The DATE needs to be YYYYMMDD
  - The TIME needs to be HHMMSS
  - The Time Zone follows UTC and military standard:
     - P=Pacific Time, Q=Mountain Time,R=Central Time S=Eastern Time.
    - W=Hawaii (K is Guam but there are no event there.)

By example an evert for 2:30pm to 4:15pm on May 3, 2021 in TEXAS would read:
DTSTAMP:20210503T143000Q
DTSTART:20210503T143000Q
DTEND:20210503T161500Q

## Specs:
- Device: Mac OS Desktop
- Browser: Unknown
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/outreach-and-events/events/sexual-harassment-violence-prevention/
- Test User _(if applicable)_:

## Desired behavior
- The multiple behaviors for this one are hard to capture in a few short sentences -- so I'll link here as a guide to the various "expected behavior" scenarios -- https://support.higherlogic.com/hc/en-us/articles/360032695012-How-To-Download-Events-to-Your-Calendar

## Acceptance Criteria
- [ ]  The files should not be corrupted
- [ ]  The Add to Calendar feature should work as expected for Mac users.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by kelsonic** [comment]
I'm not sure what I can do here to fix this... is this something that can be fixed in Drupal @kevwalsh?

**Comment by brianalloyd** [comment]
@kevwalsh and @swirtSJW could you both take a look at this one in Drupal.

**Comment by swirtSJW** [comment]
My hunch is that judging by the NaN  the query is no longer correct to get the date and it is just passing it on to the template in that way.  The data is on the node and making it to the html, but not making it to the data in the link that I am assuming generates the file. 
![image](https://user-images.githubusercontent.com/5752113/117069470-7fbfa680-acfa-11eb-893e-3c202d14ed2b.png)

**Comment by swirtSJW** [comment]
My guess is on this logic is not getting what it is supposed to 
https://github.com/department-of-veterans-affairs/vets-website/blob/21260300681f449c564f53596d0a8302dd684e7b/src/applications/static-pages/ics-generator.js#L6-L9

**Comment by swirtSJW** [comment]
As far as the time zone goes, I think you'd need a lookup function or array map to convert the drupal data that looks like 
![image](https://user-images.githubusercontent.com/5752113/117071163-b39bcb80-acfc-11eb-985b-b42b09de96d2.png)

into P,Q,R,S,W,K ...

**Comment by kelsonic** [comment]
PR merged, will go out with daily deploy

**Comment by brianalloyd** [comment]
@johnhashva can you validate the fix, should have went out with daily deploy yesterday.  TIA

**Comment by johnhashva** [comment]
@brianalloyd just did and looks good (my Slack DM minutes ago).  Did you validate in production as well?  I always like a second pair of eyes.

**Comment by brianalloyd** [comment]
@johnhashva I did, looks good on my end. I'll close this ticket in support, thanks again @johnhashva

**Comment by johnhashva** [comment]
@kelsonic and @brianalloyd wanted to share this from the Veteran who reported the issue.  Before we close this one, @kelsonic can you confirm his "you may want to check" note in bold:

Mr. Hashimoto,
Sir,
 
Thank you for attending to the matter promptly. I have indeed noticed the correction.
(I tested all the links.)
 
Your effort is appreciated. You did a good job in fixing the errors.  While some of
the messages are of a social nature, many are important to the lives of veterans.
Some actually depend on the messages as one of the few means we have of learning
what resources are available.
 
Your attention to fixing the error, will be helping many.
 
J**ust a reminded, you might want to add a check, to be sure that no
event is scheduled for 59 minutes past the hour. IF any do, then those
usiing the Microsoft Calendar feature will have the wrong hours due to
a bug in the calendar program. (Easy fix, just reset the minutes to 58
instead of 59).
 
The only time someone might have 59 minutes past an hour is for a teleconfrence
where they need to be sure people have the correct midnight.  There are two
midnights for any date. So, it is common to schedule meetings at 23:59 to be
sure they are at the correct DAY.**
 
It is possible you have already set a routine to prevent this from happening.
 
Again, thank you for your support.

**Comment by johnhashva** [comment]
Re-opening because of one more possible calendar logic thing to check.

**Comment by brianalloyd** [comment]
Interesting, thanks @johnhashva for the additional context. We'll scrub into the issue and validate the above. Thanks.

**Comment by kelsonic** [comment]
The datetime timestamp numbers we get are from the CMS, so I'm not sure

**Comment by johnhashva** [comment]
Got it @kelsonic .   @brianalloyd let's pitch this over to CMS team and close this ticket -- agree?

**Comment by kelsonic** [comment]
There may need to be some follow-up FE work here dealing with timezones depending on what the cms team tells us fysa 🙂

**Comment by brianalloyd** [comment]
Thanks @johnhashva going to close out this ticket and post CMS review on new issue for action.
