### ISSUE TITLE
[Analytics] Prepare Analytics Prototype with current data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#240]
## User Story
As a product owner, I need to easily access and understand data about my product to leverage data for product decisions and understand if there are problem areas I may need to dig more deeply into.

## Description
Prepare the Analytics MVP prototype to align with available current usable data so we are able to see which data is currently available.

## AC
- [x] Prepare Weekly data
- [x] Prepare Monthly data

**Comment by joanneesteban** [comment]
GA Analytics and links have been added to Analytics Prototype for usability testing.

Weekly latency has been added:
Latency in Grafana is only collected and stored for the last 15 days, so in order to collect monthly latency, data would need to be collected bimonthly. 

Average weekly latency can be collected with timestamps.

Grafana also stores _average_ latency every minute, and the average of that average needs to be calculated.

CC: @rtluu @nedierecel for visibility

**Comment by nedierecel** [comment]
@joanneesteban Other goals to include:

- Form 22-0994 (VET TEC)
- Form 5495
- Form 0993

Non-funnel goals:
- Retrieved GI Bill Status
- Viewed GI Bill Facility Profile

https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goals-overview/a50123418w177519031p184334251/_u.dateOption=last30days&_.goalOption=ALL

**Comment by joanneesteban** [comment]
@amycesal @smoonpeyes FYI, the columns for Latency & Funnel Conversion have BE blockers for automation into the dashboard. These data points may not make it into the first working draft.

**Comment by joanneesteban** [comment]
@nedierecel Would you mind reviewing the added goals on the prototype?
I'm missing events for 0993 & Viewed GI Bill Facility Profile
and
Funnels for 22-0994 and 0993

**Comment by nedierecel** [comment]
0993
- [Event Labels for 0993](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20181106&_u.date01=20190613&_.useg=builtin1&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.filter=0993) 
- [Funnel for 0993](https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goal-funnel/a50123418w177519031p184334251/_u.date00=20181106&_u.date01=20190613&_.useg=builtin1&_.goalOption=9)

VET TEC
- [Event labels for 22-0994](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20181106&_u.date01=20190613&_.useg=builtin1&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22PT%22,%220994--submission%22,0%5D%5D)
- [Funnel for 22-0994](https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goal-funnel/a50123418w177519031p184334251/_u.date00=20181121&_u.date01=20190613&_.useg=builtin1&_.goalOption=11)

Viewing GI Bill Facility Profile: This goal acts differently in that it doesn't track events but instead looks at the number of sessions where a GI Bill Facility Profile was viewed at least once:
- [Goal](https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goals-overview/a50123418w177519031p184334251/_u.date00=20181106&_u.date01=20190613&_.useg=builtin1&_.goalOption=7)

**Comment by joanneesteban** [comment]
Thank you for those tracking links, @nedierecel 
Current Education MVP has updated links to available data on Google Analytics. Latency will need more discovery and Back End help, so that will be opened as a new issue. Closing this issue.
