### ISSUE TITLE
Do not render main facility phone number links if no phone number is present

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24009]
## Issue Description
Two pages on the Salt Lake City VAMC have no visual text and will cause CI/CD breaks when the Nightwatch tests are fixed. These need to be remediated. 

Issue was confirmed on 4/8 at 12:15pm ET using axe-CLI for the following pages: 
- https://www.va.gov/salt-lake-city-health-care/locations/
- https://www.va.gov/salt-lake-city-health-care/locations/cache-valley-va-clinic/

This was originally mentioned in #21404. Moving it into this issue for traceability on fixes. 

Relevant details from [comment on #21404](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21404#issuecomment-828475245): 
> I know we have work going on for general archived page output, but I opened a PR to deal with the two templates @1Copenut listed department-of-veterans-affairs/vets-website#16976
> I also found 16 instances in 12 files of tel:{{ - someone them already had conditionals wrapping them, so if we want to tackle that it doesn't seem like a very big lift

PR for fix: Added conditionals around tel links that were throwing a11y errors department-of-veterans-affairs/vets-website [#16976](https://github.com/department-of-veterans-affairs/vets-website/pull/16976)

---

**Comment by 1Copenut** [comment]
@mmiddaugh Both of these are passing validation now. Moving this one to closed.
