### ISSUE TITLE
Create and implement policy for when slow queries are detected

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#24005]
**Why**: Currently, there isn’t an easy way for us to see database query times and therefore it is difficult for us to know what queries are the slowest and need to be optimized.

**What**: After creating a visual for reporting the database query times and showing which are the slowest in [Create visual for DB queries](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/24001), a policy needs to be written and implemented for what to do when slow database queries are detected. This work does not necessarily need to be blocked until the reporting tool is built out; progress could be made towards the creation of a policy while that is happening although won't be able to be finished.

### AC
- [ ] Policy has been created on what the responsible team needs to do when slow database queries are detected
  - @drorva will help with this
- [ ] As a final step the new policy needs to be rolled out and put into action

**Comment by LindseySaari** [comment]
Notes:

- Whos responsible and how often (code that has no team)
  - Automate running [these methods](https://github.com/ankane/pghero/blob/master/guides/Rails.md#methods)
- How quickly should do we investigate and fix?
- How long do they have to fix it?
- How often do we check this dashboard? - Support dev checks once per rotation

**Comment by jeff2d2** [comment]
Final docs including policy: https://vfs.atlassian.net/wiki/spaces/BTT/pages/1511325900/PgHero#Policy
