### ISSUE TITLE
[FE] Profile: "we can't load all data" error sometimes shown when it shouldn't be on Profile

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#24003]
I noticed that we are showing the generic "we can't load all the info..." error at the top of the Profile when we cannot load military info even when the user's Veteran status is 'NOT_AUTHORIZED'. While we normally _do_ want to show that error if we cannot load military info, we do not want to show that error if the user's veteran status is `null` or 'NOT_AUTHORIZED'. There is an error in the logic causing the error to show for 'NOT_AUTHORIZED' users.

**Comment by ajakabcin** [comment]
confirmed
