### ISSUE TITLE
Find a VA Form: Add new sort by relevance option to existing sort

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24012]
## User Story

As a Veteran, I want the ability to re-sort my search results by relevance if I sort them alphabetically or by date.

## Expected Behavior

- Existing sort drop-down contains a new option (use Closest match per Content team - see content request #23912)
- Capitalization on remaining sort options is modified so that only the first word is capitalized - also mentioned in content request #23912.

## Acceptance Criteria

- [x] New option (**Closest match**) is added to existing sort on Find a VA Form search results behind feature flag
- [x] Capitalization on remaining sort options is modified so that only the first word is capitalized
- [ ] Change is reviewed on Staging with PO and PM
- [ ] Midpoint review is held with VSP
- [ ] Staging review is performed by VSP
- [ ] Feature flag is removed
- [ ] FE change is deployed to Prod in coordination with Lighthouse team's change to add ranking/scoring logic to Forms API

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel - I updated to specify that the new option will be labeled "Closest match", and added another AC item to also change the capitalization on the other sort options per Content's recommendation.  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel just pinging to make sure you saw this update from yesterday.  Can you also update the sort option and capitalization while updating for the refresh bug? Thank you! 🙏😊

**Comment by zacharymorel** [comment]
Sure thing

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO Can we move this to close then?
