### ISSUE TITLE
Configure the GitHub Actions workflow for the separated content build

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#24015]
## Description

Some of the steps from the `vets-website` GitHub Actions workflow will need to get split out into a new workflow to support the new separated content build in the `content-build` repo.

The most obvious change would be to move the content build and content-related tests (including sitemap accessibility tests) from `vets-website` to `content-build`. The deploy steps should also reference the appropriate buckets for each repo.

## Acceptance criteria
- [ ] The GHA workflow for `vets-website` should match its Jenkins pipeline.
- [ ] The GHA workflow for `content-build` should match its Jenkins pipeline.

**Comment by meganhkelley** [comment]
vets-website and content-build each have their own workflow now
