### ISSUE TITLE
Anchor Tags | VSA-QA Test Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#24011]
## Product/Feature summary

When a vet, caregiver or customer service representative wants to direct someone to a specific question/answer on the Coronavirus FAQ page, they can only share a link at the page level leaving it up to the recipient to navigate through the long list of information to find the specific content they seek. This can be frustrating and time-consuming.

The goal of this experiment is to make it quick and painless to share specific content contained within a page. By adding shareable anchor links / deeplinks to a heavily trafficked page we can launch quickly and determine whether we meet user’s needs and should deploy more widely across warrants VA.gov. 

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature Outline: \[provide link]  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/anchor-tags.md (WIP)
- Product/Feature Epic: \[provide link] https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19337 
- Product/Feature Copy deck(s): \[provide link, or type "In Design prototypes"] Design captured here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20125
- Product/Feature Design prototypes: \[provide links, or type "In Design prototypes"] https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/#como-puedo-seguir-informado-e-27876
- Design mocks for reference here: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19867#issuecomment-786718474

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Product manager: @SKasimow 
Product owner: @jenniferlee-dsva 
Design/Research: @rtwell 
Content/IA: @mnorthuis 
Front-end: @youngfreezyVA 
Back-end: n/a
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: \[provide link] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/Anchor-Tags-Use-Cases.md
## How to configure this issue

- [x] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [x] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by jenniferlee-dsva** [comment]
@SKasimow - the above looks good to me. I made a few minor edits. Did you want me to look at anything else? (I fleshed out use case B. I think other use cases can include all the things we're internally testing for per those bugs we identified earlier.)

**Comment by SKasimow** [comment]
@jenniferlee-dsva Hey Jen - oh sorry, I didn't mean to have you review them yet as it is still a WIP :).  But thanks for feedback!! I'll pick it up again a little later today

**Comment by tlei123** [comment]
@SKasimow , all test-runs now completed.

Only 1 defect logged: #24372 [IE11-specific]

QA-artifact links are below, and will also be updated into Staging Review ticket #23367:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1805)
- [Test Case](https://dsvavsp.testrail.io/index.php?/cases/view/4795&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=827)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/220)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/219)

**Comment by tlei123** [comment]
Closing this now.  QA-feedback will be addressed & tracked via #24727.
