### ISSUE TITLE
Support review instances in GitHub Actions workflow

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#24014]
## Description

The Jenkins pipeline deploys review instances for feature branches. The GHA workflow should continue to support review instances.

Since the review instance workflow and experience may change in the future, it might be best in the short term to just invoke the Jenkins API endpoint for the review instance deploy job (`deploys/vets-review-instance-deploy`). This work should not involve re-implementing the entire review instance deploy process in GHA.

## Acceptance criteria
- [x] Review instances are deployed in feature branches through the GitHub Actions workflow.

**Comment by oseasmoran73** [comment]
Review instance is now supported in `vets-website` and `content-build` repo. See ticket #21750 for more detail.
