### ISSUE TITLE
Copy build step from Jenkins pipeline to GitHub Actions workflow

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#24013]
## Description

With the self-hosted runner (#23300), we have access to the internal network of systems, including the Drupal CMS, so we're able to run a full build.

To match the build step in Jenkins, we'll need to generate a build for each environment (`vagovdev`, `vagovstaging`, `vagovprod`). Additionally, the prod build should fail on broken links according to the same criteria and threshold as in Jenkins.

## Acceptance criteria
- [ ] Generate a build for each environment (`vagovdev`, `vagovstaging`, `vagovprod`.
- [ ] Process the output of the broken link check and fail the build with the same criteria as Jenkins.

**Comment by oseasmoran73** [comment]
Closing ticket as PR recently merged
