### ISSUE TITLE
[FE] Create Feature toggle playbook

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#24017]
[From feedback from the security review](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/252): 

## Tasks

MUSTS:
- [ ] Playbook w/ information for the feature flag name & how to disable the feature in case of emergency.

## Acceptance
- [ ] Disable feature guide has been seen and approved by appropriate persons.

**Comment by mdewey** [comment]
Playbook created : 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/playbook/toggle-app.md

**Comment by leahkeeler** [comment]
@mdewey - if you can attach this ticket to security ticket that will do it !
