### ISSUE TITLE
[Bug] 10-10CG - Representative documentation - upload errors

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#24029]
## What happened?
On Staging **[Apply for the Program of Comprehensive Assistance for Family Caregivers](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)** (10-10CG) form, **Representative documentation > Upload** page, file-upload threw an error, and clicking **Continue** didn't advance.  Same behavior occurs with upload on Review page.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]

## Steps to Reproduce
- URL: https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction
- Advance to **Representative documentation** page, completing required fields and clicking **Continue** button on the way there.
- Choose **Yes... upload... now.**, then **Continue**.
- On **Representation documentation > Upload...** page, click **Upload**, select & upload a dummy-file [pdf/jpg/png].
- Observe that the file-card displayed includes an error-message "There are no routes matching your request: v0/caregiver_attachments"
- Click **Continue**.
- Observe that the button doesn't respond -- the form doesn't advance.
- **Delete** file, then **Continue** to **Review Application** page.
- Expand **Representative documentation**, then **Upload** a dummy-file.
- Observe that the file-card displayed includes the same error-message.
- Click **Update page**.
- Observe that the button doesn't respond -- the section doesn't update.

### Video capture (Win Chrome, Rep-doc page example)

https://user-images.githubusercontent.com/587583/116630966-283fc600-a909-11eb-961a-0e5d499a65ed.mp4

## Desired behavior
On both **Representative documentation > Upload...** & **Review Application** pages:
- [ ] File-upload should work -- not throw an error.
- [ ] Clicking **Continue**/**Update** should advance/update the form.

## Acceptance Criteria
- [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ala-yna** [comment]
@tlei123  - Now that the frontend and backend have been connected, this issue should be resolved. Can you please retest? Thank you!

**Comment by tlei123** [comment]
@ala-yna , closing now -- checked this on Staging and upload's working.
