### ISSUE TITLE
IA Feedback - Midpoint Review [Claims & Appeals Team, Notice of Disagreement]

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#24024]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
-  Breadcrumb:  Breadcrumb on form is inaccurate.  Each segment should match the corresponding page H1 and should not change from page to page.   Correct breadcrumb for the form:  
Home > Decision reviews and appeals > Board Appeals > [Form introduction page H1] 
- Left nav: Represent an accurate left nav on the static page that will include an additional entry point to the NOD form.  Add "Request a Board Appeal" as the first option nested under "Board Appeals"

**Should:**

**Consider:**
- User feedback: Gather user feedback on findability/wayfinding starting at the [decision reviews hub page](https://www.va.gov/decision-reviews/) to gauge their understanding of their options, and allow them to flow through the [Board appeal static page](https://www.va.gov/decision-reviews/board-appeal/) to get to the NOD form.  For this area of the site (decision reviews), we use a lot of new and complex labeling and structure that we do not have a lot of user feedback on.  It would be helpful to gather feedback on whether users understand what the decision review options are, and when they might choose one over the other.   

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by kevinstachura** [comment]
Hey @mnorthuis - IA changes have been completed on the design and can be found here:

https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538562

Changes implemented include:

- Corrected breadcrumbs
- Left nav now shows 'Request a Board Appeal'

Please let me know if I missed anything or if any of the changes are incorrect. Thank you!

I absolutely agree that this is something to pursue as part of a future research study:

>User feedback: Gather user feedback on findability/wayfinding starting at the decision reviews hub page to gauge their understanding of their options, and allow them to flow through the Board appeal static page to get to the NOD form. For this area of the site (decision reviews), we use a lot of new and complex labeling and structure that we do not have a lot of user feedback on. It would be helpful to gather feedback on whether users understand what the decision review options are, and when they might choose one over the other.

@vhenry07 it may be valuable to create a prelim list of priorities for future enhancements and testing to the NOD experience and to include this in said list. 👍

Thanks!

**Comment by mnorthuis** [comment]
@kevinstachura I know we are all a bit hungry for some bigger user feedback in this area!

There's just an underline missing in the breadcrumb for the form intro page under "Board appeals".  Thank you for following up, looks great!

**Comment by kevinstachura** [comment]
I'll make that fix - thank you @mnorthuis !!
