### ISSUE TITLE
Request access to Google Analytics and/or Domo - Testing Tools Team

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#24023]
# Request GoogleAnalytics, Domo and BigQuery access

## User Email Address
Please link this issue to the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), add VSP Analytics & Insights to your message, and provide the email address(es) for user(s) requesting access.
* peter.hill@oddball.io
* ryan.johnson@oddball.io
* holden.hinkle@oddball.io

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [ ] Domo
- [ ] BigQuery

## Date Required
_ASAP_

## Product Team / External Team / VA Office
_VSP Testing Tools Team_

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by joanneesteban** [comment]
@laurensimpson14 When you get a chance today, can you please check if they have access to Domo already (so they're not double added), add them to the Testing Tools group in Domo (please create the group if it's not there), and give them editing permissions?

**Comment by laurensimpson14** [comment]
@JoeTice I've granted Peter, Ryan, and Holden editor access in Domo and added them to the VSP Testing Tools group. 

Do they also need Google Analytics and BigQuery access? It looks like all three have GA access already.

**Comment by laurensimpson14** [comment]
@JoeTice I see that there's a separate ticket for Holden to get BQ access, so I'm going to close this ticket.

**Comment by JoeTice** [comment]
@laurensimpson14 - Sorry for the slow reply on this...  Yes, Peter and Ryan also need BQ access...

**Comment by joanneesteban** [comment]
Thanks, Joe! @laurensimpson14 @JasonTheBearded This is for the Testing Tools team's BigQuery access, so reassigning this one.

**Comment by JoeTice** [comment]
@joanneesteban - adding some more detail to ensure everyone is on the same page, and all the specifics are in one place...

* Domo Access - Peter and Ryan will need write access to Domo (Holden has been given this already)
* BQ Access - Peter, Ryan and Holden will need BQ service credentials as well (Based on our conversation via slack, we understand this to be the same thing as getting BQ Access)

CC: @laurensimpson14 @JasonTheBearded (in case this info is helpful)

**Comment by joanneesteban** [comment]
Thanks for those details, @JoeTice !

We're figuring out how to provide BQ credentials (this is our team's first time provisioning access for folks to add datasets outside of Analytics-owned datasets), so we're determining how to best do that on our end. Appreciate your patience as we go through this!

**Comment by bsmartin-ep** [comment]
@JoeTice -

I'll need to keybase someone the JSON key.  Got a username I should send it to?

**Comment by JasonTheBearded** [comment]
@JoeTice I created a dataset in our vsp-analytics-and-insights project called vsp_testing_tools and granted Peter, Ryan, and Holden access to it. Can you have them double check that they can access it?

**Comment by pjhill** [comment]
> @JoeTice -
> 
> I'll need to keybase someone the JSON key. Got a username I should send it to?

@bsmartin-ep You can keybase me the JSON key. My username is `pjhill`.

**Comment by JasonTheBearded** [comment]
@pjhill It is in BigQuery, [here's the link](console.cloud.google.com/bigquery?project=vsp-analytics-and-insights) to get to our project and when you expand the project name you should see the dataset underneath. Let me know if you don't.

**Comment by pjhill** [comment]
> @pjhill It is in BigQuery, [here's the link](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights) to get to our project and when you expand the project name you should see the dataset underneath. Let me know if you don't.

@JasonTheBearded OK, I have access -- thanks! I'll get the other guys to check as well.

**Comment by pjhill** [comment]
@JasonTheBearded -- Holden and Ryan have verified that they have access to that dataset. I'm not sure if it's included in this request, but we are also looking for a set of BigQuery service account credentials.

**Comment by JasonTheBearded** [comment]
> @JasonTheBearded -- Holden and Ryan have verified that they have access to that dataset. I'm not sure if it's included in this request, but we are also looking for a set of BigQuery service account credentials.

@pjhill Great to hear they can access the dataset. The SA creds are what @bsmartin-ep will be supplying through keybase

**Comment by pjhill** [comment]
> > @JasonTheBearded -- Holden and Ryan have verified that they have access to that dataset. I'm not sure if it's included in this request, but we are also looking for a set of BigQuery service account credentials.
> 
> @pjhill Great to hear they can access the dataset. The SA creds are what @bsmartin-ep will be supplying through keybase

Ah whoops, I forgot about that -- thanks!

**Comment by bsmartin-ep** [comment]
JSON key has been keybased to @pjhill.

**Comment by pjhill** [comment]
@bsmartin-ep and @JasonTheBearded 

Thanks for getting us setup! We're starting to work on creating the table structure today, but it looks like we don't have the right permissions to be able to create tables within our dataset. Would you have a look please?
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/d432ce1d-7b2d-4c96-889f-7931504f27a8)

**Comment by JasonTheBearded** [comment]
@pjhill I expanded the permissions for you, Ryan, and Holden. Can you give it another try?

**Comment by pjhill** [comment]
> @pjhill I expanded the permissions for you, Ryan, and Holden. Can you give it another try?

@JasonTheBearded , we were able to create a table, but now I can't query it, which seems... odd.

`Access Denied: Project vsp-analytics-and-insights: User does not have bigquery.jobs.create permission in project vsp-analytics-and-insights.`

I guess querying the table is generating a job somehow?

**Comment by pjhill** [comment]
@JasonTheBearded and @bsmartin-ep 

Per [this conversation](https://dsva.slack.com/archives/CJYRZK2HH/p1620929833142200), please rotate the credentials that you generated for us this week. 

In summary, the credentials were logged out in a GitHub Actions step. While this repository is private, members of the **Department of Veterans Affairs** GitHub organization are able to view them, and we would prefer to restrict access to our dataset to only our team.

Also, we are unable to run queries against our data, please have a look at permissions and let us know how to proceed.

**Comment by JasonTheBearded** [comment]
@pjhill Can you try running your queries again? I'll also be keybasing you the new credentials shortly.

**Comment by pjhill** [comment]
> @pjhill Can you try running your queries again? I'll also be keybasing you the new credentials shortly.

Queries are working as expected now -- thanks! Sorry about the creds, we appreciate it!

**Comment by JasonTheBearded** [comment]
@pjhill Let me know if there's anything else. Otherwise I think we're good to close this ticket.

**Comment by pjhill** [comment]
> @pjhill Let me know if there's anything else. Otherwise I think we're good to close this ticket.

Agreed -- close away
