### ISSUE TITLE
Military address: update field error copy

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24028]
## Acceptance Criteria
1. On the Edit Mailing/Home address forms, make the following change to the field error copy when the "military base" box is checked:
     - Field error for APO/FPO/DPO: "Please select a valid option"
     - Field error for State: "Please select a valid option"
          - Note: this change should _only_ be applied to "State" when the field is driven by the Military base checkbox. If Military Base is unchecked and U.S. is the selected country, then the field error for "State" should remain as "State is required" 

## Screenshot for reference
![Image from iOS (41).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/91ef9207-b16d-4ef1-bc60-c9bd339e0661)

**Comment by digitalken** [comment]
PASS 5/24/2021 - Looks good on iOS and Android.  Closing.
