### ISSUE TITLE
[Jenkins] Maintain API keys across deployments

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#24039]
### The Problem
Currently, when re-deploying Jenkins, user API gets get deleted. This is a problem specifically for the `va-cms-bot` user since a number of teams depend on its API key in order to remotely trigger Jenkins jobs.

### Extra Context
New API key(s) have been manually generated by ops team members after re-deploys of Jenkins, but this creates the need for a manual step in the deployment that we'd prefer to have automated.

There have been a number of attempts to fix this:

- https://github.com/department-of-veterans-affairs/devops/pull/7862
- https://github.com/department-of-veterans-affairs/devops/pull/9077

...but those ☝️ fail since the "user" in Jenkins is loaded from Github and doesn't actually exist at the time the [bootstrap groovy script](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/bootstrap.groovy) is executed.

### Work to be Done
- [x] Investigate how Jenkins API key persistence might work
  - [x] Generate a new key and use the aws CLI to store that new key in SSM? (preferred)
 - [x] Implement said ☝️ solution

**Comment by tskinn** [comment]
For some reason this command is not running successfully https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/bootstrap.groovy#L189

Once that is working I think this ticket can be closed.

**Comment by oseasmoran73** [comment]
@jhouse-solvd Following the PR that Taylor provided and direction moving forward, looks like we can close this ticket

[Comment](https://github.com/department-of-veterans-affairs/devops/pull/9196#issuecomment-914495712) from @jbritt1
