### ISSUE TITLE
Accessibility Feedback - Midpoint Review [Claims & Appeals Team, Notice of Disagreement]

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#24031]
# Midpoint Review - Claims & Appeals - Notice of Disagreement

* https://github.com/department-of-veterans-affairs/va.gov-team/issues/23841
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/24031

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

## Questions

* https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538580 consult with Josh about the Gestalt that lines up with his feedback from today's design intent review.
* How will the final print this page for your records be output? As print CSS, or as a PDF? If it's a PDF, it will have accessibility requirements.
* Do we need the signed out view after users click the action link on the intro page? https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538562 It seems better to automatically trigger the login prompt and land on the logged in start screen. This feels like an extra step. https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538592
* Did we remove the Add Issue button when we're in list loop edit mode? https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538584
* Is the "Track the status of your claim or appeal" button a button or a link styled as a button? If it's the latter, consider using a link. If it is starting a new flow or journey, consider using an action link.
* Does the "print your records" blue box have a smaller font size than the rest of the page? Was this an intentional design decision? 

## Must

* https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538583 list loop must have unique accessible names for each list item

## Should

* Some of the linked views for step 2 Issues eligible for review could be cross-linked. Not all users may want to click on the existing issue after entering a new one, or click on the "Why aren't all my issues listed here" before continuing.
* The longer paragraph under the checkbox label should be associated with the label using `aria-describedby`. This is more of a dev item, but worth mentioning here. Users will want to know this information but may miss it if they're tabbing through or using the `f` shortcut key in JAWS or NVDA.
* Same advice for the radio buttons on https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538585
* Same advice for the checkbox on the review page: https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538572
* "You can still file..." and "Can I request a Board Appeal?" should both be `h2`s. They're currently styled as `h3`s and may be written as `h3`s unless clearly annotated for developers.

## Consider

*  Consider making Guidelines for uploading a file a heading level 2: https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538577

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by vhenry07** [comment]
No changes to incorporate. Closing ticket.

**Comment by joshkimux** [comment]
@vhenry07 , We will be opening this ticket as it has been updated with Trevor's feedback and some additions from my end 🙇
