### ISSUE TITLE
Content Request from Decision Tools Team for Discharge Upgrade Wizard

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24034]
### Content support for:
- Unauthenticated (static) VA.gov pages
- Apps or tools
- Other writing or editing requests

**Note: These requests are handled by the Sitewide Content Team.** 

### Engineering support for:
- Redirects that have **first been vetted by the VSP IA team**
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support

**Note: These requests are handled by the Public Website Team.** 

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [ ] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [x] Determine if this request is for:
     - [X] Content Only      
     - [ ] Public Website Engineering Support      
     - [ ] Both (Content + PW Eng Spt)   
- [x] Post a link to this issue in the appropriate channel: For Engineering only requests: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @ncksllvn and @kelsonic. Content only support: [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) in Slack, tag @RLHecht.  In situations where both are needed post to Public Websites and in Slack tag @brianalloyd, @ncksllvn, @kelsonic and @RLHecht for awareness.  
- [ ] If noted in the guidance below, please schedule any relevant meetings.

#### Content requests

|Type of need | When to submit your request |
| :-- | :-- |
| **New unauthenticated VA.gov page (such as a static landing page to support a new app/tool)** | At project kickoff |
| **Updates to an existing unauthenticated VA.gov page** | For significant updates (like consolidating pages or reworking page content): At project kickoff <br> For smaller updates (like adding a section of new info): At least 1 full sprint in advance (so we can work it into our next sprint). |
| **Writing support for app/tool** | At project kickoff | 
| **Editing support for app/tool or other writing/editing support** | For multiple screens: At least 1 full sprint in advance (so we can work it into our next sprint). <br> For very small needs (like an error message): At least 2 days in advance | 

### Engineering requests

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * Yes, it's for the existing Discharge Upgrade Instructions page  https://www.va.gov/discharge-upgrade-instructions/
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

### Background
~~If a service member chooses Air Force while filling out the Discharge Upgrade Wizard questions, and their answers currently direct them to download DD Form 149, they will now be directed to a link to the Air Force Review Boards Agency portal located at https://afrba-portal.cce.af.mil/#portal   🔴 **Note** We're aware this URL currently throws a privacy error outside the VA network due to a security certificate issue.  We are working with Alexander Reber with USAF on getting that resolved**~~

**5/26/2021 Update due to change in approach and scope** Currently the Discharge Upgrade asks a series of questions, and depending upon the user's responses, gives the user instructions, links to PDF form(s) and the mailing address for the appropriate military review board.   

The DoD recently notified us that each branch now has created its own portal that provides detailed instructions and PDF links.  They would like for Discharge Upgrade page to simply provide links to each of these portals, eliminating the need for the user to traverse the wizard.

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [ ] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @RLHecht and @brianalloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page.  

- [X] **Updates to an existing unauthenticated VA.gov page**
 To see it in Production, go to [this page](https://www.va.gov/discharge-upgrade-instructions/guidance).   

   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.

- We need content that provides links to the portals for each of the military review boards:

**Department of Army:**

- Army BCMR:  https://arba.army.pentagon.mil/abcmr-overview.html  

- Army Discharge Review Board:  https://arba.army.pentagon.mil/adrb-overview.html r

 **Department of Navy (Navy/Marine Corps)**

- Board for Correction of Naval Records: https://www.secnav.navy.mil/mra/bcnr/Pages/default.aspx  

 - Naval Discharge Review Board:  https://www.secnav.navy.mil/mra/CORB/Pages/NDRB/default.aspx  

 **Department of Air Force**

- Air Force Review Boards Agency:  https://afrba-portal.cce.af.mil 

**U.S. Coast Guard**

- U. S. Coast Guard BCMR:  https://www.uscg.mil/Resources/Legal/BCMR/  

- U.S. Coast Guard Discharge Review Board:  https://www.uscg.mil/Resources/legal/DRB/

 <hr>

* **Are updates related to usability testing or analytics?** If yes, please provide details.**
       * No

- [ ] **Writing support for new app/tool** 
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 
      * < URL list >
   * **Schedule a meeting.** Please schedule a meeting with @RLHecht and @brianalloyd to kick off this work. We'll work with your team and the VSP content resource to determine how best to support your needs.   

- [ ] **Editing support for app/tool** <br> <br> **Note:** We'll work with your team and the VSP content resource to determine how best to support your needs.
   * URL where draft content appears (if available) <br>    
     - < link > 
   * **Word document with draft content** (if needed) <br> **Note:** If you have more than 2 paragraphs of text to edit, please provide text in a Word doc.     
     - < link >      
   * **Design context** <br> **Example:** Is this content in a user flow, an in-line error message, tool tip, field label?
     - < design context >
   * **Scope: How many screens or messages?** 
     - One screen       

### Frontend engineering support 

- [ ] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.)
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

*We are waiting for Air Force to resolve a certificate issue with their link, but a new **campaign landing page will launch June 1, 2021 to drive users to this page**, so we would like to get these changes in soon after that so that users have the most current info as quickly as we can reasonably provide it.*

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Decision Tools
- DEPO product owner: John Hashimoto
- Product manager: Marci McGuire
- Designer: Cassandra Allen
- FE engineer: Zach Morel
- Product/team Slack channel: #vsa-decision-tools

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by RLHecht** [comment]
@MarciMcGuireGCIO The action link component is not available in Drupal yet, so we wouldn't be able to switch the CTA link to one.

**Comment by MarciMcGuireGCIO** [comment]
Thank you. Does that mean we just need to change the CTA to a PDF download link?

We are looking for guidance on how to word the updated page and the CTA.

Thank you,

Marci

**Comment by MarciMcGuireGCIO** [comment]
@RLHecht Can we get together to discuss this request?  We are currently blocked from moving forward on this change until we have content recommendations.  Thank you!

**Comment by RLHecht** [comment]
@MarciMcGuireGCIO I want to make sure I understand the new instructions for this form. Will users still be able to download the form and mail it in as well even with the new online form? Trying to determine if the setup is similar to our form landing pages where we have the different ways to apply: online, by mail, and in person.

**Comment by MarciMcGuireGCIO** [comment]
@RLHecht it's my understanding that for Veterans who were in the Airforce and currently being instructed to download this form, the desire from the requestor is to have them now fill it out completely online.  We will clarify with the requestor and advise that this could present issues for some users who may have a specific reason for needing the PDF. cc @johnhashva

**Comment by MarciMcGuireGCIO** [comment]
@RLHecht we met with the Stakeholder this morning and got some further clarification.  The link they've asked us to add was mistaken as an online application.  It is actually a link to the **AFRBA (Air Force Review Boards Agency) portal** which provides a link to the DD 149 PDF form and detailed instructions so they can download, fill it in, then upload it there to expedited their request. 

That being said, we would remove the instructions from our page and replace the PDF link with a link to this AFRBA portal.  

I believe the only ask now is for Content recommendations for introductory text explaining that the Discharge Upgrade request can be made via the AFRBA portal, and what that actual link itself should say.  

Happy to schedule something you'd like to discuss in more detail.  Thanks! 

cc @johnhashva

**Comment by RLHecht** [comment]
Thanks @MarciMcGuireGCIO that all makes sense. I'll work with Beth and/or Danielle to figure out the language for the intro and the link and get back to you.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @RLHecht !  Let me know if any new questions come up when you talk to them.

**Comment by MarciMcGuireGCIO** [comment]
@bethpotts - this ticket has been updated to include the other military review board info as we discussed yesterday.  Thank you!

**Comment by bethpottsVADEPO** [comment]
@bethpottsVADEPO @MarciMcGuireGCIO Tagging myself with my current account so I can follow along. The one you used to tag me above was my old github account and I don't get those notifications.

Am I understanding correctly that we'll need to replace the content in subway step No. 1? That wall of text--with something that introduces the links to the review boards? But the wizard is staying in place on the static page and no content needs to change there?

**Comment by MarciMcGuireGCIO** [comment]
Note from Collab Cycle office hours - Trevor mentioned that it is important that there are headers and that each link is distinct so that screen readers have enough context.  I have updated the link text to reflect Trevor's recommendation.

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO - thank you for catching the account.   

I think it would be best if we have a quick call with @johnhashva and Margarete Ashmore at DoD to get some clarification and make sure we are all on the same page.   

My understanding is that the "Get Started" button on the [first page](https://www.va.gov/discharge-upgrade-instructions/) would be replaced with the portal links.  Users would no longer go through the wizard and would never see the subway map. 

In our brief meeting with Margarete we didn't discuss the questions/accordions shown below the "Get Started" button.  Those have some wizard-specific copy, so they would either need to be updated or removed.  If you're good with a meeting, I'll find a time.  Thanks!

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO before we meet with Margarete -- let's meet as a threesome.  I may be able to clarify on some of these points -- or maybe not.

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva sounds good.  I'll post a meeting time request on Slack and tag Beth.

**Comment by MarciMcGuireGCIO** [comment]
This request has changed and is expected to change again, so I am closing this ticket and will open new ones when we know the full scope.
