### ISSUE TITLE
[FE] Update Legal Text

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#24041]
Waiting for updates to legal text

**Comment by mdewey** [comment]
Still waiting on Text

**Comment by mlighdc** [comment]
@mdewey we have received feedback regarding the language for Privacy. Danielle is working to make it more plain language. It may be a few more days. If you have any questions, let me or @kristenmcconnell know.

**Comment by kristenmcconnell** [comment]
The "Will VA protect my personal health information?" wording updates are finalized. You can review the wording here: https://www.sketch.com/s/fd688be2-76eb-484b-a306-9c1b522f4f09/a/OmOnpym

**Will VA protect my personal health information?**

We make every effort to keep your personal information private and secure.

[Read more about privacy and security on VA.gov
](https://www.va.gov/privacy-policy/)

You're also responsible for protecting your personal health information. If you print or download your information—or share it electronically with others—you’ll need to take steps to protect it.

[Get tips for protecting your personal health information
](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/protecting-your-personal-health-information)

cc @DanielleThierryUSDSVA

**Comment by kristenmcconnell** [comment]
Also, we will need the privacy act statement modal. Danielle worked on the wording (making it more plain language) and it is out for review.

**Comment by mdewey** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17351). Waiting for the privacy act to merge.

**Comment by batemapf** [comment]
final text, approved by VHA privacy:

**Privacy act statement:** We ask you to provide the information in this questionnaire to help with your medical care (under law 38 U.S.C. Chapter 17). It’s your choice if you want to provide this information. If you choose not to provide this information, it may make it harder for us to prepare for your visit. But it won’t have any effect on your eligibility for any VA benefits or services. We may use and share the information you provide in this questionnaire in the ways we’re allowed to by law. We may make a “routine use” disclosure of the information as outlined in the Privacy Act system of records notice, s (“24VA10A7 “Patient Medical Record – VA” and following the Veterans Health Administration (VHA) Notice of Privacy Practices.

**Comment by mdewey** [comment]
This is staging, who needs to review this? @kristenmcconnell? @batemapf?

**Comment by kristenmcconnell** [comment]
The text looks good. The "Read more.." and "Get tips..." links open in the same tab, which kicks the user out of the questionnaire workflow. Since the "Get tips..." link opens MyHealtheVet, I'm wondering if it should open in a different tab. 

@DanielleThierryUSDSVA How did the Public Websites team implement the links for the Drupal page, since this content appears there as well?

**Comment by batemapf** [comment]
@mdewey if you can get to it easily, mind just dropping a screen shot in here? i'd do it myself, but no idea which test user to use...

**Comment by mdewey** [comment]
@batemapf Here you go :-) 

![Screen Shot 2021-05-27 at 12 53 29 PM](https://user-images.githubusercontent.com/1793923/119866196-8bae1b00-beea-11eb-9c9a-3e0699fa58e8.png)
 and 
![Screen Shot 2021-05-27 at 12 53 46 PM](https://user-images.githubusercontent.com/1793923/119866226-9668b000-beea-11eb-9372-7d395b8844f7.png)

**Comment by batemapf** [comment]
LGTM :shipit:
