### ISSUE TITLE
Determine how to address facilities with null hours

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#2405]
### **Description**
The facility locator displays hours for some locations as `N/A - N/A`; the api data for these locations comes in as `null` for the hours each day.   Here are some examples:

- [Ralph H. Johnson Department of Veterans Affairs Medical Center](va.gov/find-locations/facility/vha_534)
- [Wm. Jennings Bryan Dorn Department of Veterans Affairs Medical Center](https://www.va.gov/find-locations/facility/vha_544)
- [Jesse Brown Department of Veterans Affairs Medical Center](https://www.va.gov/find-locations/facility/vha_537)

So far I'm only seeing this on Medical Centers, which are hospitals that have 24/7 emergency rooms, but the centers also have speciality clinics with different hours, and they have special visiting hours which vary by department (according to the operator I spoke with at the first center).  

### **User Impact**
**Who is the user impacted by this problem?**
Anybody looking at a location whose facility hours are missing

**How does this problem affect the user?**
They have no information about the facilities actual hours

### **Steps to Reproduce**
Go to [this medical center](va.gov/find-locations/facility/vha_534) (for example; there are many)
Look at the Hours of Operation
#### Expected Results
The hours of operation for every day of the week are there.  Better yet, the hours for various parts of the center

#### Actual Results
Each day of the week says N/A
![image](https://user-images.githubusercontent.com/55992116/66680977-bf69fd80-ec3f-11e9-8527-e148c4b70adf.png)

### Proposed solution
- At a minimum, determine the best way to communicate to users that the facility is open 24/7.  Possibly replace list of days with a simple statement, "This facility is open 24 hours a day, 7 days a week"? Or put 24/7 as the value for each day?
- Break out the hours of operation by core services: Emergency, Pharmacy, + Speciality Clinics

**Comment by andaleliz** [comment]
@arickalewis1 just an FYI for you so you have visibility to this issue. My understanding is the Global UX team will tackle for now but would love to hear any thoughts you want to share

**Comment by Karak888** [comment]
I was just going to send this your way @mmiddaugh !

**Comment by jellis-gcio** [comment]
@mmiddaugh this is probably better to be handled on the frontend since we still want the rest of the facility data

**Comment by Karak888** [comment]
@mmiddaugh do you want this to go into your backlog or icebox or hold?  Please let me know- I will add this to our backlog until you are ready or we get direction to handle. 

FYI:  @andaleliz

**Comment by jellis-gcio** [comment]
removed assignment since it seems to be frontend focused

**Comment by mmiddaugh** [comment]
Front end expects times representing open and closed
24 hours expressed as N/A
Aricka will get an example of a facility with "occasional Saturday hours" so we can look at the back end data for that location...need to make sure this is the only scenario/edge cases...look beyond VA Health (other facility types: Benefit locations, Vet Centers, Cemeteries)
MVP: clean up 24/7

**Comment by mmiddaugh** [comment]
@davidconlon @brangi @arickalewis1 
I just discovered [10838](https://github.com/department-of-veterans-affairs/vets-website/pull/10838) which looks like changing the hours to N/A was a conscious decision that this current ticket proposes to undo. 
Thoughts?

**Comment by arickalewis1** [comment]
@mmiddaugh There's a better design decision to be made. For example, if we cannot pull the hours I say that we remove the section. Showing the user something that isn't there isn't helpful to them.

**Comment by davidconlon** [comment]
@mmiddaugh @arickalewis1 Changing the hours to N/A seems like it was done when the hours are missing, but I believe @jellis-gcio was stating that the back-end provides a few different options that the front end doesn't know how to handle so it reverts to an inappropriate N/A. 

Let's check the data to see what's available because there could be data/format expectations on the front end and, as a result, we're "running to our safe space" with N/A.  

Examples may include Cemeteries being open from Sunrise to Sunset, or VAMC being 24/7.  I know the VAMC data is being served up as 24/7 because Pittsburg is getting that correctly.

**Comment by davidconlon** [comment]
It looks like they purposefully changed stuff like "Sunrise" to "Sunset".  This is actually a fairly typical hours description for an open outdoor space like a cemetery or a park. "Don't come here when it's dark".   I'm more concerned about the 24/7 VAMC stuff.  The new Pittsburgh is displaying 24/7 (https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/)

**Comment by kelsonic** [comment]
Looks like this ticket is still solving the following question:
`When the api returns null values for weekdays, what does that mean?`

I believe that could mean 3 things:
```
1. No hours were provided for that day by the location.
2. The intent is to make it 24/7 for that day.
3. The intent is to make it Sunrise - Sunset for that day.
```
Once we decide that it means one of those 3 things then this should be relatively straight-forward to implement! :)

**Comment by Karak888** [comment]
@kelsonic thanks for being proactive, but just want to let you know that the Facility Locator team will be handling all of this work moving forward.  Thanks!

**Comment by mmiddaugh** [comment]
@brangi 
Facility Locator should display the hours of operation information sent through the API, rather than interpreting the data. 

**Acceptance Criteria**
If the Facility reports hours as "24/7", the Facility Detail page should display 24/7 in a meaningful, understandable way. 
If the Facility reports "Sunrise-Sunset", the Facility Detail page should display "Sunrise-Sunset" in a meaningful, understandable way. 
If the API does not contain information for the hours of operation, the Facility Detail page should not display that area of content.

I will open a separate issue to query the data and identify Facilities with missing information so that we can contact the data sources to address the data quality directly.

**Comment by davidconlon** [comment]
Small item, but we want to be sure that the content complies with https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones

Looks like we need a space between the time and "a.m." and "p.m."

**Comment by davidconlon** [comment]
Following on this, we should also be including time zones per the spec, but this gets a bit complicated for an automated system so opening another issue.

**Comment by mmiddaugh** [comment]
Moved the small change into [#3541] as this issue has been resolved and merged.
