### ISSUE TITLE
[FE] Direct Deposit: post launch code cleanup

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24056]
## Background
Following the successful launch of Direct Deposit for Education to all users we need to do a bit of code cleanup around the feature flag and v1 code.

## Tasks
- [x] Remove the front end feature flag and all code the uses that feature flag
- [x] Remove all code related to direct deposit v1 (code without direct deposit for education)

**Comment by erikphansen** [comment]
I removed all FE code with https://github.com/department-of-veterans-affairs/vets-website/pull/17147.

And this PR will totally delete the feature flag from Flipper https://github.com/department-of-veterans-affairs/vets-api/pull/6907

**Comment by erikphansen** [comment]
Still waiting to be able to merge this PR https://github.com/department-of-veterans-affairs/vets-api/pull/6907 :(

**Comment by erikphansen** [comment]
Merged!
