### ISSUE TITLE
[App Hosting and Deployment] Migrate GIDS to EKS and bring up in Dev

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#24057]
## Description
As GIDS (GI Bill Data Service) is one of the services that ops owns and maintains. We need to begin looking into how to migrate it into EKS. 

## Background/context/resources
The current deployment schedule for GIDS (from Jenkins BRD) is weekly on Wednesdays @ 1150 ET

## Technical notes
Need to set up CI/CD workflow for getting this service into EKS 
Need to discuss the deployment plan

---
## Setup Tasks
- [X] CI using GitHub Actions
- [x] CD w/ ArgoCD
  - [x] Create a new namespace w/in EKS
  - [ ] Tie back to ArgoCD
  - [x] Docker image -> ECR
- [ ] Monitoring? (probably separate ticket) 
- [x] move deployment_files to SSM PS, use external secrets to mount them
- [x] build ca cert into docker image?
- [x] setup k8s resources (namespace,deployment,service,ingress)
- [ ] update all references to gids load balancer to new ingress
- [ ] create GHA for running migrations? or figure out how that is supposed to happen

## Testing tasks 
- [ ] Get GIDS team to test 
 
## Definition of Done
- [x] GIDS will be running in the EKS
  - [x] in DEV
  - [x] in STAGING
  - [x] in PROD
- [ ] GIDS team will be using the EKS-based service (change setting in fwdproxy and revproxy)
  - [x] in DEV
  - [ ] in STAGING
  - [ ] in PROD 

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@tskinn is going to pick up where Sri left off. please see tasks above

**Comment by jhouse-solvd** [comment]
@tskinn - when you get a chance (no rush) if you can check off any additional tasks and notes as to the status, that would be helpful. I also noticed that this definition of done was that we want this running in Dev. So, not sure if we should modify that to include production, or if you'd prefer a separate ticket? Let me know and we'll make it happen.

**Comment by tskinn** [comment]
Update: gids running in k8s is live in dev

**Comment by jhouse-solvd** [comment]
This is fully up and running in Dev. Once we are ready, we can bring it live in staging, prod environments. We will want to set up monitoring and alerting for this service when we do...  

Closing.
