### ISSUE TITLE
[DESIGN] My VA: Kick off recruiting for UAT

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#24062]
## Background

We need to ensure that My VA is working properly for users.

## Tasks

- [x] Submit the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-conversation-guide.md) to Perigean
- [x] Prep all note taking/synthesis materials

**Comment by Samara-Strauss** [comment]
Moving this out of sprint 47. We are not ready to actually recruit for UAT yet — UAT can only happen after QA, the staging review, and the privacy review. Think of UAT basically as a soft launch. We're just not ready yet.
