### ISSUE TITLE
[Design, FE] My VA: Begin compiling/executing accessibility tests for staging review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24067]
## Background
As part of our preparation for the staging review we need to perform accessibility tests for My VA. This will be a joint effort from Design and FE to perform these tests and Product to ensure everything is documented to submit the request. The plan is for @ajakabcin to be able to submit this request in sprint 48.

[Staging review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/touchpoint-staging-review.md) documentation for reference. 

## Tasks
Design and FE to perform the accessibility tests as documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/staging-review/accessibility-test-prep.md)

**Comment by tressaellen** [comment]
@erikphansen (cc/ @ajakabcin) I've done the color tests, content zoom and keyboard navigation check. Let me know if you need help with any of the other ones.

**Comment by erikphansen** [comment]
@tressaellen do you want to take a stab at screenreader tests? I'll do it as well. Then we can compare notes and things that seem to work well or poorly.

**Comment by erikphansen** [comment]
@ajakabcin I believe this can be closed now that Tressa and I have checked off the required items from the list and made tickets for some issues we uncovered.

**Comment by ajakabcin** [comment]
Closing - the noted issues have been added to sprint 48
