### ISSUE TITLE
Unable to load messages in some custom folders

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#24076]
## Description

We're running into an error while trying to load some of a test user's custom folder messages:

MHV Endpoint: `/patient/v1/folder/660837/message/page/1/pageSize/10`

Error response:
```
{
  "errorCode": 99,
  "developerMessage": "",
  "message": "Unknown application error occurred"
}
```

Affected folder IDs:
- 660837
- 660437
- 660693

MHV Correlation ID: 13492196
id.me email: vets.gov.user+261@gmail.com

Loading system folders and some custom folders seem to be fine.

Trello ticket: https://trello.com/c/cYgWh4t5/18-issues-loading-custom-folder-messages
MHV Jira Ticket: TBD

**Comment by narin** [comment]
Barry has asked his team to create a defect JIRA ticket.

**Comment by narin** [comment]
Example Sentry event from UAT 5/17 12:30pm EST: http://sentry.vfs.va.gov/organizations/vsp/issues/37377/?environment=production&project=3&query=is%3Aunresolved

**Comment by ashley-matthews** [comment]
MHV implemented fix
