### ISSUE TITLE
Set up Platform "workspaces" in Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#24075]
## Issue Description
More Platform teams will be setting up dashboards in Domo. In order to unblock them, but also track activity so that we can troubleshoot if needed, Analytics will set up a dashboard space for teams to create charts and dashboards.

---
## Tasks
Set up dashboard spaces for the following teams, and share the dashboard with the Analytics group in Domo:
- [x] Service Design
- [x] Product Support
- [x] Contact Center

## Acceptance Criteria
- [ ] VSP teams have a workspace to make dashboards in Domo & Analytics has views of these workspaces for troubleshooting.

**Comment by JasonTheBearded** [comment]
Dashboard spaces set up and shared with Analytics group.
