### ISSUE TITLE
Common Component: pagination - buttons don't seem to have enough top padding

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#24072]
## What happened?
Top padding on the right/left arrow buttons looks the same as left/right, which is 20px.  Top/bottom padding should be 40px.

EDIT:  Applies to messages, too.

## Specs:
Using judy.morrison@id.me.

From the story:

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/e5ac9d38-5cba-4556-b878-7e9b7b7a33d2)

## Steps to Reproduce
Observe pagination in appointments.

## Desired behavior
Top and bottom padding should be 40px.
Right and left padding should be 20px.

## Acceptance Criteria
Top and bottom padding is 40px.

## Bug Severity
- 4 - Low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21331

And messages:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21330

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/706a9f47-c7e4-42ad-a543-d2ecab09c76b)

**Comment by bessgreen** [comment]
@digitalken I've consolidated this ticket with a related issue (#24747).

Closing this ticket.
