### ISSUE TITLE
SM Camera/Photo Gallery Attachment File Size Issues

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#24087]
### Issues
1. Attaching a file by taking a photo is resulting in a file over 3mb which is over the max for a single file
2. Attachments from the photo gallery or camera are doubling in size after being sent

### Expected Behavior
1. Images taken with camera should be sized down and not run into any max file size errors
2. If a list of attachments is < 6mb combined, and each file is < 3mb, there should be no issues sending the message
3. Once message is sent, file sizes should remain the same (can be checked by viewing message in Sent folder)

### Notes
We will revisit this error once SM is operating as expecting // we ask for the full file size. JP, AD, JM to chat about max file sizes and quality/size constraints. This will have to apply to both taking a picture and selecting one.

**Comment by ashley-matthews** [comment]
MHV is planning to make updates to the API that would:

1) increase the attachment file sizes to match the clinician portal (10MB max and 6 MB for single attachment)
2) Increase the number of attachments Veterans can upload to also match the clinicians (tbd on #)

Unsure of the timing, but just wanted to share it here for awareness.

**Comment by narin** [comment]
@kxiao133 Reported some issues with incorrect file sizes in [her PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/755):

> Note: image file size display on compose form does not match image file size read by backend. (e.g., sending 2 MB attachment receives an API error saying it's greater than 3 MB. Also, on the compose form the file attachment size display is about 1 MB less than the display once it's sent: 1.15 MB --> 2.19 MB)

Will try to determine whether this is an issue in the `vets-api` layer or if it needs to be escalated to MHV and track in this ticket.

**Comment by narin** [comment]
@kxiao133 I did some debugging and compared the file sizes using the app vs Postman using the same 475kb file.  When uploading through Postman, the file size returned from MHV matches the file size I see in my Finder.  However, when I upload through the app, there size becomes 1.1mb.  

So it appears to be an issue somewhere within the mobile app that is increasing the file size by over double.  The attachments list that is shown to the user in the app is showing the correct size, so maybe somewhere in the appending of the file or further along the file size is being inflated.  Not sure if this is helpful but here is the sample `fetch()` that Postman gives me:

```javascript
var myHeaders = new Headers();
myHeaders.append("Authorization", "Bearer t1Mq2kRFXsSD15m6ZP3W");

var formdata = new FormData();
formdata.append("uploads[]", fileInput.files[0], "ezgif-5-f9e2d5921bcf.jpg");
formdata.append("message", "{\"body\":\"test tiger with attachment through postman\"}");

var requestOptions = {
  method: 'POST',
  headers: myHeaders,
  body: formdata,
  redirect: 'follow'
};

fetch("localhost:3000/mobile/v0/messaging/health/messages/1942553/reply", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
```

**Comment by narin** [comment]
I also tried transferring the image to the Files app, and choosing it as an attachment from there.  It does not increase the file size in this case. So this issue occurs when the user is choosing from the Photo Gallery or if they are taking a picture with the camera.

**Comment by digitalken** [comment]
PASS 5/27/2021 - Not getting any errors about any single photos taken with camera being too large.  Closing.
