### ISSUE TITLE
Update content for system & facility selection

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2408]
There are several possible UI / data states on the facility selection page for which we don't have updated content, which may be confusing to veterans who are trying to decide what step to take next.

AC
- [ ] Each of the three scenarios have updated content attached to this ticket.

**Failed recency check:** Only one facility supports the selected type of care, however, the veteran hasn't been seen recently enough at that facility to schedule online (they must call into the facility instead):
![Screen Shot 2019-10-09 at 6.08.35 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/55a4791f-d03f-4c4d-b7e7-564dc91894aa)

**Failed recency check, veteran has multiple registered systems or facilities:** This is a slight permutation of the above scenario. The main difference is that in the first scenario, the veteran has no other options because he / she only has one facility in their one registered system that supports the selected type of care, but here the veteran can choose a different system or facility instead.
![Screen Shot 2019-10-09 at 6.03.54 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/e690e7bf-ea05-4004-905d-7d77c86aa221)

**Failed request limit check:** The veteran already has x outstanding request(s) for the selected type of care at the selected facility and can't make any more requests until the existing request(s) are converted to appointments or cancelled. The specific number for the cap is configured by each facility (though usually the request cap is set to 1 request), and caps are not mandatory.
![Screen Shot 2019-10-09 at 6.04.00 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/409bd3f9-204c-4230-9e09-b509f714165b)

**Comment by peggygannon** [comment]
@markgreenburg @rtwell Please see my content recommendations for the VA location scenarios. We might want to go over this one together at our next content sync to be sure I've captured all the messaging correctly. 



1. Please fix misspelling of appointment in header and add some intro text to give some baseline guidance to the user about scheduling appts.

**Choose a VA location for your appointment**

To schedule an online appointment, some locations require that you have visited the facility within the past 12 months for the type of care you select. And some types of care are available at only certain locations. 

2. *Failed recency check scenario*

{alert message}
**You’re registered at the following VA medical center**

{location name/info}

To request an appointment online for the type of care you selected, you need to have visited this facility within the past 12 months.
If you haven’t visited this location within the past 12 months, please call this facility to schedule your appointment or [search for another facility](va.gov/find-locations/). 



3. *Failed recency check, veteran has multiple registered systems or facilities scenario*

You’re registered at the following VA medical centers. Please choose where you’d like to schedule your appointment. (*Required)

{list of facilities}
{user makes choice}
Appointments are available at the following locations. Please choose your preferred location.

{user makes choice}

{alert message}
**We couldn’t find a recent appointment at this location**
You need to have visited this facility within the past 12 months to request an appointment online for the type of care you selected. 
If you haven’t visited this location within the past 12 months,  please call this facility to schedule your appointment or [search for another facility](va.gov/find-locations/). 

4. *Failed request limit check scenario*
{alert message}

**We’re sorry. We couldn’t schedule an appointment at this location**

Our records show that you have an open appointment request at this location. We can’t schedule any more appointments at this facility until the open appointment requests are scheduled or canceled.

**Comment by rtwell** [comment]
i think these are all screens from staging, so imma ping @narin + cc @markgreenburg

**Comment by jbalboni** [comment]
@markgreenburg I'm not sure this is relevant anymore.

**Comment by markgreenburg** [comment]
Per conversation with Jeff, seems like these are already implemented so closing this ticket.
