### ISSUE TITLE
OS Check - Ignore GHA Self-Hosted Runner Machines

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#24091]
## Issue Description
GHA self-hosted runner (GHSHR) machines currently cause the OS Check job to fail due to unreachability. We will likely need to ignore them for these automated jobs. These instances are much shorter lived, so the OS check is irrelevant from the perspective that it's goal is to keep instances up to date as the OS remains online. 

Additional Slack thread: https://dsva.slack.com/archives/C37M86Y8G/p1620039785367500

---
## Tasks
- [ ] Ignore GHA self-hosted runner machines within the OS Check job automation

## Acceptance Criteria
- [ ] OS Check jobs no longer failing due to GHA self-hosted runners
---

**Comment by jhouse-solvd** [comment]
The reason that it fails is that the runner machines don't have SSH connectivity. So, technically, it's possible to:

- allow SSH to go in, or 
- modify the check job to use SSM instead
- rewrite the job so SSH isn't required

This may be a short-lived issue as we may use GHSHR into k8s.

**Comment by mleclerc00** [comment]
GHA runners are no longer being included in the ansible os check.  All the nodes captured by the filter have sshd installed and can be reached.

![image](https://user-images.githubusercontent.com/76792875/130510213-06e93af3-5dfb-4c80-ac98-65386d8cb1d9.png)
