### ISSUE TITLE
[Placeholder] Financial Status Report's 'Find a form' content 

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#24098]
## Background
With the FSR's release coming up, we need to ensure it's findable in multiple places on VA.gov. I've drafted content based on the 526-EZ's 'Find a form' page to ensure consistency; let me know what thoughts you have about any of the proposed content!

**FSR's URL:** va.gov/manage-va-debt/request-debt-help-5655/  

**When to put in place:** TBD; estimating 1-2 sprints. I'll remove 'Placeholder' from the title and add a comment to this ticket when I have a solidified date. 

---
## Content

**Title change:** About VA Form 5655

**Related to:** I'm unsure what guidelines determine what we put here. I looked at multiple results and some listed 1-2 categories while other listed many. Let me know how I can help determine what would be best to list here.
My thoughts on what we might want to include: Debt Management, Veteran’s Benefits Administration, Veteran’s Health Administration, Disability, Pension, Health Care

**When to use this form**
Use VA Form 5655 if you’re a Veteran or service member who needs help with debt related to VA disability compensation, education, or pension benefits. You can use this form to request a payment plan, compromise offer, or waiver. 

**Helpful links**
We'd like to add the following links:

**Manage your VA debt**
Check the status of your VA debt and find out what options you have to resolve it.
URL: https://va.gov/manage-va-debt/

**Request financial assistance for VA copays**
If you’re struggling to pay your copays, learn how to request a repayment plan, debt relief, or copay exemption.
URL: https://va.gov/health-care/pay-copay-bill/financial-hardship/

These two links directly relate to VA debt, so it's important that we provide that information to our users. We likely don't want a long list in the 'Helpful links' section, so we can replace the 'Request your military records, including DD214' and 'Get your VA records and documents online' because documents related to VA debt live in the 'Manage your VA debt' tool. 

Thank you!

**Comment by MarciMcGuireGCIO** [comment]
Hi Riley, It may make sense for us to have a quick chat on this.  LMK when you have a few minutes free.  Thanks!

**Comment by rileyorr** [comment]
Update to make sure all pieces of this work are looped together: [I opened a content review ticket with the public websites team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24443).

**Comment by MarciMcGuireGCIO** [comment]
@rileyorr Hi!  I ran across this issue in our backlog and just checking if there are any updates. Thanks!

**Comment by rileyorr** [comment]
Hi @MarciMcGuireGCIO! Thanks for following up - the FSR was rolled back while we iron out some endpoint issues. Shen the FSR is up and running again I can either update you on this ticket or open a new ticket! Let me know what works best for your team 😄

**Comment by MarciMcGuireGCIO** [comment]
Thanks! You can just update this ticket.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @rileyorr @MarciMcGuireGCIO! Just checking in to let you know that we'll finalize the content for this now that we're close to putting the FSR back online. Thanks!

cc @davidconlon

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @DanielleThierryUSDSVA !

**Comment by denisecoveyduc** [comment]
@DanielleThierryUSDSVA  @MarciMcGuire Doing some backlog clean up and I am pretty sure this one can be closed out? The FSR is up and functioning for both VBA and VHA at this point and I haven't heard of anyone having difficulty finding it online. Any reason we need to keep this open at this point?
