### ISSUE TITLE
Content Feedback - Staging review - VAOS for distribution

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#24101]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
@laurenernest @outerpress Hello! Platform content review for VAOS for distribution. Please let me know if you have any questions. Thx! 



**Questions**
1.	This alert below was in the copy docs, but I didn’t see it in the staging flow/link. Want to check, where in the flow will this appear? 
Sign up to stay informed
We’re working to provide COVID-19 vaccines to Veterans as quickly and safely as we can, based on CDC guidelines and available supply.
Learn how to stay informed about COVID-19 vaccines at VA.

------

**Must feedback**
n/a

-----

**Should feedback**

1.	Recommend tweaking this line, adding “you should” for sense and readability: 
Here’s what to know: TO> Here’s what you should know:

2.	Recommend updating this error alert to avoid repetitive content and to avoid use of “booking.” That term isn't used anywhere else in the VAOS flow. 

**Sorry, we could not find any available slots for your booking**
We could not find any available slots for your booking. Please call your medical facility:

TO: 
**We’re sorry. We couldn’t find any available slots for your appointment**
Please call your medical facility: 
{facility name and address}
{facility number} 

3. Please make validation errors descriptive, so users with accessibility devices will understand what is the missing input. 
For example: Please provide a response> TO Please select a location for your appointment

**Comment by outerpress** [comment]
@peggygannon feedback looks good on my end. 

@laurenernest  I'm guessing that booking language (feedback item #2)  shows up in a similar alert for the direct schedule and/or request flows so we should update it in those spots too if so.

**Comment by laurenernest** [comment]
**Question 1** - That alert only appears on the version of the Contact a facility page when a user can't schedule online after we check their facility registration against slots and online scheduling being turned on.

---

**Should 1** - Updated [Plan Ahead copy doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/plan-ahead.md) with recommendation and included in #24219

**Should 2** - Updated [Facility Selection copy doc ](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs/facility-selection.md#alerts)with recommendation and included in #24219
- @peggygannon Should there be a period at the end of "We couldn’t find any available slots for your appointment"?

**Should 3** - I created a separate ticket to update the error validation messages #24221 and will go through the whole flow to check

**Comment by peggygannon** [comment]
@laurenernest Yes, there should be a period there. thanks.

**Comment by laurenernest** [comment]
@peggygannon What are your thoughts on this error validation message on the screener page?
![cheetah screener error validation copy](https://user-images.githubusercontent.com/72046525/117723909-debc6a00-b197-11eb-8df0-649e9f852d48.png)

**Comment by peggygannon** [comment]
Hi, @laurenernest Here's a recommendation to make it more clear that the users need to provide an answer. Let me know your thoughts.  

Please select an answer

**Comment by laurenernest** [comment]
All recommendations have been captured in dev tickets. Closing this ticket.
