### ISSUE TITLE
Design Feedback - Staging Review VAOS - VAOS for Distribution

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#24102]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Nice job! I know you have worked really hard on this.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Move H1 outside of alerts and gray cards![Screen Shot 2021-05-03 at 5.36.47 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/21e594cf-c897-4498-90de-e3524a7fc14a)
- Use the [utilities](https://design.va.gov/utilities/font-size) to style H1’s to look like H2. Right now the H1’s are all different sizes throughout the screens. See the primary scheduling screens for example.
- Add the left blue bar and gray background to the info alert. Change the icon color to the ‘base’ color. See [information alert](https://design.va.gov/components/alertboxes#informational-alert) for example![Screen Shot 2021-05-03 at 11.42.34 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/e927463b-1956-4df7-819b-2503c74f79b2)

**Should:**
- Make the name of the locations an H3 but styled like an H5 to match the Find a VA pattern![Screen Shot 2021-05-03 at 11.53.12 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/ef9bbbf4-826d-4c7f-9072-afd4b45e8839)

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by outerpress** [comment]
Thanks Allison! Just a couple of questions and clarifications:

> Move H1 outside of alerts and gray cards
Is this feedback just for the "we can't schedule your second dose online" page, or are there other alerts?

> Use the utilities to style H1’s to look like H2. Right now the H1’s are all different sizes throughout the screens. See the primary scheduling screens for example.
Is it standard to style the H1's as H2's in forms? These could all be styled as H1's from my perspective.

> Add the left blue bar and gray background to the info alert. Change the icon color to the ‘base’ color. See information alert for example
This is specifically meant to be the main content of the page, not an alert. We styled it this way after usability testing showed users weren't reading all the information we needed to get across - the big bold bullets help focus the eye on the separate important points.  

Separately, are we moving away from the information alerts style? In a different [review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19757) I thought you said that this style isn't mobile-friendly, but maybe there was something context-specific I missed.

**Comment by allison0034** [comment]
@outerpress I believe I only saw it in the one screen but it should be applicable everywhere there are alerts/cards that have the H1

Is it standard to style the H1's as H2's in forms? Good question. Let me do a little digging. I know our forms H1's are not the normal H1 size. The schedule an appt has them styled as H2's that is why I suggested that.

The alerts with the left bar and icon are not mobile friendly, we would love for them to be redesigned and tested. Until that happens we need to use them. You are using the info icon and this really seems to reflect an info alert or possibly a callout box. That being said, I dont want to undo what your usability testing showed. Did you have it styled in the info alert box style when you did testing?

**Comment by allison0034** [comment]
@outerpress Is it standard to style the H1's as H2's in forms? No, I have found both H1's styled as H1 and H1's styled as H2

**Comment by outerpress** [comment]
@allison0034 made some progress:

> Add the left blue bar and gray background to the info alert. Change the icon color to the ‘base’ color. See information alert for example

After our chat about alerts on Tuesday (cc: @rtwell ) I went with switching this to regular bullets to align with the design system:
![HP-preflow-info.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/332635ad-ced8-4d6b-b31b-29fbd18c836c)

I also ran the suggested changes to the header (Make "Here's what you should know:" the h1) by @peggygannon and @1Copenut.  Peggy's going to review this some more to see if we can find something that's more accessible but still action-based to align with the current headers, though we may end up leaving it as is and watching analytics to see if the current header is causing trouble.

Oh, and this screen includes a content change recommended in [the content review ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/24101)

----

> Move H1 outside of alerts

Done, though I'm wondering if the card makes sense now. @peggygannon  would you recommend new card language here, or does this work?

![DENODO2-received-CVAX-call.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/cbc786df-f5d0-4c34-aa0c-69c98d4953e5)

--------

>  Is it standard to style the H1's as H2's in forms? No, I have found both H1's styled as H1 and H1's styled as H2

Thank you! @laurenernest just a note, something we can look at aligning across VAOS flows ^

**Comment by allison0034** [comment]
@outerpress nice work!

**Comment by outerpress** [comment]
Thanks @allison0034! 

@laurenernest these are GTG on my end, outside of any content changes that might come from @peggygannon

**Comment by outerpress** [comment]
@peggygannon yep yep, here's the updated Sketch file: https://www.sketch.com/s/fd383f03-0827-49a7-865c-e0b44f70b183/p/mvp-staging-review-updates

Caveats and notes:

- I updated the pages that had changes from the staging review, but not the others. So if some are out of sync or confusing, just let me know
- There are three different flows represented by the prefixes in the screen names:
* DENOAPPT - Dead end - no appointments available
* DENODO2 - Dead end - no second dose
* HP - Happy path

So if it looks like some screens are repeated, that's why. Sorry about that, sorting and organizing options are limited with Sketch Cloud.

**Comment by outerpress** [comment]
@peggygannon just a follow up from our sync yesterday:

[First page in the flow](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/332635ad-ced8-4d6b-b31b-29fbd18c836c)
We're going to leave the h1 as "COVID-19 vaccine appointment" for this and revisit if we see a problems with this page in the GA funnel, so this change is good to go.

[Dead end if they've already had a vaccine dose](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/cbc786df-f5d0-4c34-aa0c-69c98d4953e5)
I'd like you to look at the info box and see if the content still makes sense now that it's a little separated from the header (in the version we're updating, the header was in the yellow info box)

**Comment by laurenernest** [comment]
Confirming we have almost 100% step completion on the first/"COVID-19 vaccine appointment" page 👍🏼

**Comment by peggygannon** [comment]
Hi, @outerpress Thanks... Yes, I think the content in the yellow box still makes sense,  even thought the header moved out of the yellow box.

**Comment by outerpress** [comment]
Thanks @peggygannon and @laurenernest ! 

@laurenernest given Peggy's comment, this should be GTG design-wise. I'm pretty sure these are the outstanding changes haven't been captured in another ticket:

**First page in the flow**
- The text highlighted with info icons changes to a bulleted list
- [Mobile spec](https://www.sketch.com/s/fd383f03-0827-49a7-865c-e0b44f70b183/a/3OPEQLD#Inspector)

**Dead end if they've already had a vaccine dose**
- Yellow alert box doesn't encompass h1
- [Mobile spec](https://www.sketch.com/s/fd383f03-0827-49a7-865c-e0b44f70b183/a/52PWQyP#Inspector)

I'll drop D/T specs in the dev ticket separately

**Comment by laurenernest** [comment]
Dev ticket created #25478

**Comment by laurenernest** [comment]
Feedback updates complete
