### ISSUE TITLE
Accessibility Feedback for Staging Review [Caregivers - Sign as a Representative]

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#24103]
# Accessibility Feedback for Staging Review [Caregivers - Sign as a Representative]

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh and Angela

**Comment by joshkimux** [comment]
@ala-yna some bugs I caught that may not be relevant completely to the accessibility ticket:

<img width="379" alt="Screen Shot 2021-05-10 at 10 32 08 PM" src="https://user-images.githubusercontent.com/14154792/117755969-47810200-b1eb-11eb-8af9-29f07340c1a7.png">
<img width="413" alt="Screen Shot 2021-05-10 at 10 34 40 PM" src="https://user-images.githubusercontent.com/14154792/117755983-4e0f7980-b1eb-11eb-8530-29cec1ee1d4e.png">

**Comment by 1Copenut** [comment]
I agree with Josh's feedback on all items. After a quick consult I escalated https://github.com/department-of-veterans-affairs/va.gov-team/issues/24501 to a `508-defect-1` because of the need for letter-perfect accuracy in the caregiver's signature field.

**Comment by AngelaFowler82** [comment]
Can someone please reset this test account or provide me with another one? Huge thanks.

**Comment by mlighdc** [comment]
@AngelaFowler82 did you get what you need? @ala-yna what is the status of this ticket?

**Comment by ala-yna** [comment]
@Dene-human @dat-gcio and Chris - we should go through these and prioritize them for the next sprint.
