### ISSUE TITLE
[FE] Profile: Update "Not In MPI" alert on Profile and My VA 2.0

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#24105]
## Background

In an effort to streamline My VA and profile alerts we need to update the alert for the scenario when we can connect to MPI but a user does not exist. The correct copy is as follows.

**We're having trouble verifying your identity**

We're sorry. We're having trouble matching your information to our records. So we can’t give you access to VA.gov tools right now. Please contact the VA help desk at 800-698-2411 (TTY: 771) to verify and update your records.

![Screen Shot 2021-05-07 at 1.07.05 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/700f90f6-43ec-4410-989f-f1c6b611ae24)

## Tasks

- [ ] Update copy in alert

**Comment by tressaellen** [comment]
@bethpottsVADEPO no, not too late! Feel free to make updates, you can just drop them in this ticket.

**Comment by erikphansen** [comment]
I'll use this ticket to update this alert on both the Profile and My VA

**Comment by erikphansen** [comment]
@tressaellen @ajakabcin this can be validated on staging but I'm not sure of "not in MPI" staging user off the top of my head.

**Comment by tressaellen** [comment]
Hi @erikphansen - I've been working with @ajakabcin and we can't figure out a user to use that's "not in MPI". Is there another way to validate this?

**Comment by erikphansen** [comment]
@tressaellen not really. I thought there would be some user who'd match this. you could always get a friend to sign up through ID.me, verify their identity, and they should see these errors, assuming they've never registered at a VA facility for any reason :-D

**Comment by ajakabcin** [comment]
closing this as we haven't been able to find a way to test
