### ISSUE TITLE
VRRAP: Update spool file attestation section

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24119]
As a RPO processor, I need the spool file to accurately reflect the questions being asked of the applicant so that I can process the application efficiently and correctly.

## Assumptions:
1. This work does not require a prod / feature flag.

## Acceptance Criteria
1. The `As of the date of this application, are you currently unemployed by reason of the COVID-19 pandemic?` question is replaced with: `As of the date of this application, you're currently unemployed due to the COVID-19 pandemic:`.
2. The `Are you currently enrolled in a Federal or State jobs program, or do you expect to be enrolled in such a program while training under VRRAP?` question is replaced with: `You're not currently enrolled in a federal or state jobs program, and you don't expect to be enrolled in one while using VRRAP:`.
3. The following content

    > Are you currently receiving unemployment compensation, including any cash benefit received pursuant to the CARES Act, or do you expect to begin receiving unemployment benefits prior to training under VRRAP?
    > Or 
    > Are you currently receiving unemployment compensation benefits, including any cash benefit received pursuant to the CARES Act, but your benefits will end before you will begin training under VRRAP?

    is replaced with

    > You won't receive unemployment compensation, including any cash benefit received under the CARES Act, while training using VRRAP: 

5. The answers to the questions updated in AC 1, 2, and 3:
    a. If the applicant answers `Yes` to the question `The statements above are true and accurate to the best of my knowledge and belief` and the corresponding the [self attestation content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/design/content-doc.md#confirm-youre-eligible-for-vrrap), all questions in the "VRRAP ATTESTATION QUESTIONS" section have an answer of "Yes".
    b. If the applicant answers `No` to the question `The statements above are true and accurate to the best of my knowledge and belief` and the corresponding the [self attestation content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/design/content-doc.md#confirm-youre-eligible-for-vrrap), all questions in the "VRRAP ATTESTATION QUESTIONS" section have an answer of "No".
    a. If the applicant does not answer the question `The statements above are true and accurate to the best of my knowledge and belief` , all questions in the "VRRAP ATTESTATION QUESTIONS" section have an answer of "N/A".

## Supporting Artifact:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222564/296058457/preview)
2. [Mock Spool File](https://github.com/department-of-veterans-affairs/va.gov-team/files/6416432/vrrap_mock_spool_formatv4.docx)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6751

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1792)

**Comment by delli-gatti-michael** [comment]
The following submissions made 5/4/21 should be in the staging spool file generated the morning of 5/5/21:
* V-EBC-8820 (N/A for all attestation questions)
* V-EBC-8821 (Yes for all attestation questions)
* V-EBC-8822 (No for all attestation questions)

**Comment by delli-gatti-michael** [comment]
Changes have been confirmed in prod. Closing this issue
