### ISSUE TITLE
[Design] Facility v2 specs for Cerner

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24127]
## Summary
When the v2 iterations to the Facility Selection page were made, the experience for Cerner site users remained on v1. To avoid maintaining 2 versions of the page (`/va-facility` and `/va-facility-2`), we would like to move all the Cerner handling to the updated facility page.

Facility v2 aka flat facility page

### Business Requirements
- Veterans who are only registered to Cerner site cannot schedule or manage VA appointments
- Veterans who are registered at both a Cerner site and a non-Cerner site can schedule or manage VA appointments for their non-Cerner registered locations, but not for the Cerner registered site
- Veterans who are registered at a Cerner site and are eligible for Community Care can request a Community Care appointment
- If Veteran is registered at a Cerner site, then direct user to My VA Health portal for appointment

### Current Designs
**Cerner only**
![localhost_3001_health-care_schedule-view-va-appointments_appointments_new-appointment_va-facility(iPad) - cerner site only.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/e4a7a507-da18-4c64-ab31-49bea29ee528)

**Cerner and non-Cerner**
![localhost_3001_health-care_schedule-view-va-appointments_appointments_new-appointment_va-facility(iPad) - cerner and noncerner default.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/08f8ec6b-6b86-49dc-a0db-ec4702e395dc)     ![localhost_3001_health-care_schedule-view-va-appointments_appointments_new-appointment_va-facility(iPad) - cerner and noncerner-noncerner selected.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/9d2aa1a8-7e6e-4919-b43f-3040b7efb16a)

---
## Request
- [ ] Desktop, Tablet, and Mobile specs for Cerner site only experience

- [ ] Desktop, Tablet, and Mobile specs for Cerner and non-Cerner combo experience

- [ ] Use "Mann-Grandstaff Department of Veterans Affairs Medical Center" as the Cerner site name

---
## Design assets

-- [New workflow overview](https://www.sketch.com/s/b61269d5-4ea9-439f-b86a-5bf9562d84ba/a/rblP2LG)
-- Mobile spec (TBD)
-- Tablet spec (TBD)
-- Desktop spec (TBD)

**Comment by outerpress** [comment]
@jbalboni  A couple of questions about how this works since I haven't designed for the v1 facilities page before:
* Does the My VA Health link open in the same window or a new tab?
* Does that link carry any info about the user, or the facility it's linking from? (i.e. do we send Cerner info about which facility the user wanted, or anything to make logging in to My VA Health easier?)
* The [last screen](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/9d2aa1a8-7e6e-4919-b43f-3040b7efb16a) looks like it loads the second list based on the selection made in the first - is that right? (Just want to make sure I'm reading the interaction correctly)

**Comment by jbalboni** [comment]
@outerpress 

1. New tab
2. We carry over session information, so you should be automatically logged into the Cerner portal. But there's no appointment or facility specific information.
3. That's correct

**Comment by outerpress** [comment]
First pass at this workflow below, with some notes:
- This mostly follows the current v1 language, while trying to provide a clearer path forward to My VA Health by making all options selectable and making the CTA stronger (will need to talk to accessibility folks about this too).
- Still looking at whether we have a convention or best practices around disabling vs. removing continue buttons on DE's
- All language is FPO, need to review current states and with @peggygannon 

![Overview - Cerner sites on V2 facilities page.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/fb64e504-cdeb-4250-97d5-8c27205c54bf)

**Comment by jbalboni** [comment]
@outerpress It might be better to talk about this on video, but a couple questions/comments based on those screenshots:

1. In "Cerner facility on V2 with other options", are you expecting that clicking on each of those radio buttons will reveal the blue box that's below the Mann-Grandstaff one? All those facilities, based on their names, are part of the Mann-Grandstaff system and none of them would be schedulable.
2. On the last screen, it's pretty unlikely that the VATS settings we use to determine if someone can schedule online will be accurate for Cerner sites. So it might be misleading to say that we found a Cerner location that supports online scheduling for a particular type of care.

**Comment by outerpress** [comment]
Some updates below based on feedback/chats last week:
* Removed the state where we'd show a single Cerner facility, as this isn't a current scenario 
* Added unselected/selected state 
* Updated example facilities to show multiple Cerner mixed with non-cerner ( @jbalboni to your comment \#1 the links would always be showing, not just on the selected option)
* Adjusted language/added address and phone call info to VAOS dead end "How to schedule"

Still to do:
* Get feedback/input from content
    * My VA health link language
    * How to schedule page language
    * Facilities page instructions (esp. to @jbalboni 's point \#2 in the above comment)
  
![Overview - Cerner sites on V2 facilities page.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/6a887604-ca3b-44a6-80e6-b2075fb0c413)

**Comment by outerpress** [comment]
@peggygannon just to confirm we do use the title "Choose a location" for the H1 in the Covid vaccine flow.

Here's my first pass suggestion for the instructions, would love your recommendation:

h1: Choose a location
Below is a list of VA locations where you're registered. Locations closest to you are at the top of the list.

We could show the same instructions for both states of this page (when users have Cerner facilities or not) and watch for any potential issue/confusion that comes up if Veterans don't see TOC listed on this page. But I'm open showing separate instructions as well.

**Comment by outerpress** [comment]
Dev ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25482

Closing this one out.
