### ISSUE TITLE
Contact Center Request - Save in Progress ID

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#24122]
## Issue Description
Contact Center needs instructions on how to collect the save in progress ID. This will aid in our troubleshooting efforts. 

---
## Tasks
- [x] Prepare 1-pager documenting procedure.

## Acceptance Criteria
- [x] Uploaded to GitHub and shared with Contact Center
---

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/support/README.md
