### ISSUE TITLE
Update load-test sessions documentation

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#2414]
## Problem
The [load-test sessions documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/auth-session-loadtest.md) is outdated, after Ansible code was recently updated by @wyattwalter to improve load-test setup-experience.

## Goal
Documentation should reflect the updated setup-experience.

## Objective this is meant to further
General CI/CD/QA process-improvement.

## Acceptance Criteria
- [x] Update sessions-code extract procedure to reflect the new Jenkins-job console-output -- this should now be a straight copy-n-paste from console-output to new JSON file with no code-cleanup needed.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tlei123** [comment]
@peterhill-oddball, [PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/2426) now Open for your review & approval.  :)

**Comment by wyattwalter** [comment]
Sorry, I missed the ping here. Looks good. Thanks!
