### ISSUE TITLE
Request For BigQuery Service Credentials

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#24142]
# Request Google Analytics and/or Domo access

## What this form is for
I'm writing to request [service credentials for BigQuery](https://cloud.google.com/bigquery/docs/authentication#service_accounts). The Testing Tools Team needs these credentials to build out our Testing Dashboard.

## User Email Address
My email address is holden.hinkle@oddball.io

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [ ] Domo

_Please list any additional requirements, if any._
- [x] Google BigQuery Service Credentials

## Date Required
ASAP

## Product Team / External Team / VA Office
Testing Tools Team

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by joanneesteban** [comment]
@holdenhinkle double checking - you already have edit permissions in Domo too, right?

**Comment by holdenhinkle** [comment]
> @holdenhinkle double checking - you already have edit permissions in Domo too, right?

Yes, I believe I do.

**Comment by holdenhinkle** [comment]
Hi Joanne, I just tried to create a card in DOMO and it appears I don't have permissions for that. I don't think I have edit permissions. Thanks :-)

**Comment by JasonTheBearded** [comment]
@holdenhinkle Are you looking for a service account to hook an API up to BigQuery or something different?

**Comment by holdenhinkle** [comment]
Hi Jason, Yeah, we're going to send test results data to BQ.

**Comment by joanneesteban** [comment]
Hi @holdenhinkle ! Checking in to see if we can close this ticket - do you need any additional Domo or BigQuery access support?

**Comment by holdenhinkle** [comment]
Hi @joanneesteban ! I think we're all set. Thanks for everything!

**Comment by joanneesteban** [comment]
Thanks @holdenhinkle & @JasonTheBearded !
