### ISSUE TITLE
CT Redesign: Copy CT name auto complete to sandbox name search

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24141]
As a developer, I need to copy the current comparison tool autocomplete functionality to the sandbox name search so that it can be usability tested as part of the overall redesign.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The current comparison tool auto complete can be copied over with no additional changes necessary.

## Acceptance Criteria
1. The autocomplete menu:
    a. displays results where the institution name starts with the users search term
    b. displays up to a maximum of 6 results in addition to the user entered term
2. If the user selects a value from the list: 
    a. the search field is populated with the value
    b. the search is executed
3. If the user does not select a value and executes the search:
    a. the search field remains populated with the user entered value
    b. the search is executed

## Supporting Artifacts:
1. [Redesign Prototype](https://bahdigital.invisionapp.com/share/37IAGO4DHZG)
2. Current autocomplete functionality
<img width="494" alt="Screen Shot 2021-05-07 at 8 40 15 AM" src="https://user-images.githubusercontent.com/48260534/117450981-ebc72800-af0f-11eb-8944-377d340f8762.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17197

**Comment by delli-gatti-michael** [comment]
Local testing complete
![Screen Shot 2021-05-19 at 3.12.35 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4df5646f-122d-4009-afcd-fa63c5d14959)

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/runs/view/1886)

**Comment by delli-gatti-michael** [comment]
Testing complete. Closing this issue
