### ISSUE TITLE
[Research] Review analytics data on home page clicks & scrolling to compare with user research findings

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#24150]
## Issue Description
_This work started this last week and will continue after research sessions end for inclusion in research findings_

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cindymerrill** [comment]
Done reviewing analytics data on home page clicks. Results are in slides #2-6 of this visualization presentation: https://docs.google.com/presentation/d/1ZF15IHMHlQ-az5ttbdS8DuDoh5if-82Z4SMcubG097c/edit?usp=sharing
Haven't started looking at scrolling analytics data.

**Comment by cindymerrill** [comment]
Reviewed Brian Martin's analytics information and links on scrolling, and replied with some questions.

**Comment by cindymerrill** [comment]
Still haven't heard back from @bsmartin-ep so left a followup comment on the ticket.

**Comment by bsmartin-ep** [comment]
Apologies @cindymerrill - I missed this message:

>  And these unique searches are only ones that have been typed into the site search box in the header on VA.gov , not from searches on the Find a Form or Resources and Support pages?

Yes - if you're [filtering to the homepage](https://analytics.google.com/analytics/web/#/report/content-site-search-pages/a50123418w177519031p176188361/_u.date00=20210401&_u.date01=20210430&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.searchStartPage:www.va.gov~2F/) as the search "start page", this would only be header searches. 

However, if you **do** ever want to pull search metrics for a page that has multiple search types, we can filter the Event Action to just the one (or ones) we need.

**Comment by cindymerrill** [comment]
@bsmartin-ep didn't answer the 5 questions I had in analytics ticket #23733, so I pinged him in that ticket.

**Comment by cindymerrill** [comment]
I got my analytics questions answered today in Collaboration Cycle Office Hours, and they're documented in analytics ticket #23733. New finding, which I'll update in my research report:

_Only about 9% of home page views scroll down 50% of the home page, 5% down 75%, and 1% all the way to the bottom (including seeing the footer)._
