### ISSUE TITLE
Contact Center Review for [Authenticated Experience - My VA]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24153]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
We are launching a new version of the **My VA** dashboard which allows veterans easier access to critical information in one centralized place. My VA (www.va.gov/my-va) allows veterans to view a summary of important information about themselves from a central location 

[Staging](https://www.staging.va.gov/my-va)

### Launch Date
Phased launch late Q2 2021 (late June/early July)

### Version Number
version 1.0

### Product Guide
[My VA 2.0 Product Guide.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6418565/My.VA.2.0.Product.Guide.pdf)
[My VA 2.0 Product Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6454222/My.VA.2.0.Product.Guide.docx)

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Hi @ajakabcin, can you please share the .doc version of this product guide? Thank you!

**Comment by ajakabcin** [comment]
Attached to the original issue - thanks!

**Comment by starlow00** [comment]
Hi @ajakabcin. Attached is my draft with edits for your review. Once we agree on a clean copy, I can forward to VEO for their review. Please note that I've saved the page numbers in the Table of Contents for after your review. At that point, contents won't be shifting any more and you can be certain that things are where the TOC says they are :)

 
[My.VA.2.0.Product.Guide_ST_051021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6475101/My.VA.2.0.Product.Guide_ST_051021.docx)

**Comment by ajakabcin** [comment]
Thank you @starlow00!

**Comment by ajakabcin** [comment]
Woops sorry didn't mean to close!

**Comment by starlow00** [comment]
No problem, @ajakabcin . Just let me know if the changes work for you and then I can forward to VEO. Thanks!

**Comment by ajakabcin** [comment]
@starlow00 apologies for the delay here - all good from our side. Thanks!

**Comment by starlow00** [comment]
Sent to VEO for review

**Comment by starlow00** [comment]
No updates from VEO. Closing.
