### ISSUE TITLE
[Bug] 10-10CG - Submission error

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#24155]
## What happened?
On Staging **[Apply for the Program of Comprehensive Assistance for Family Caregivers](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)** form, submission threw an error.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]

## Steps to Reproduce
- URL: https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction
- Complete the form through to **Review** page, adding any combination of caregivers (PFC only, PFC+SFC1, or PFC+SFC1+SFC2), uploading or not uploading rep doc.  [Submission error occurs regardless of form-data.]
- On **Review** page, complete **statement of truth** required fields, then click **Submit**.
- Observe that an error message is displayed.

### Screenshot
![sar-bug-submission-error](https://user-images.githubusercontent.com/587583/116953861-2e081500-ac43-11eb-8074-1c01613fcd0b.png)

## Desired behavior
- [ ] Form submission should succeed -- no error message should be displayed.

## Acceptance Criteria
- [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ala-yna** [comment]
@tlei123  - please use Veteran data from [this list](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) when fill out the Veteran section of the form. That should resolve this issue.

**Comment by tlei123** [comment]
Thx, @ala-yna !  Closing now -- submission successful after signing-in to Staging and filling form  using a test-user's data from your list above.
