### ISSUE TITLE
Determine best place and content for VA Mobile page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#24159]
## Issue Description
The team building the VA Mobile app is looking for the best place to put a page to promote and explain the team/product/development process. 

Their suggestion was an R&S page, which doesn't work with this info, but there might be an opportunity for a different type of R&S Q&A once launched.

Danielle and the rest of the sitewide team will discuss how best to proceed with this.

Ticket with more info on the ask: #23522

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by mnorthuis** [comment]
Totally stumbled across this...would a stripped down campaign landing page work here? Or is it more about how to use it and where to get it?

**Comment by jenniferlee-dsva** [comment]
Hi @mnorthuis - please see comment in original ticket here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23522#issuecomment-827035845

Also - they are not looking for proactive engagement or want the general public to know, so I don't think a campaign page is appropriate - there being no campaign. 

I think the team's goals are internally not aligned, so it is difficult to know what would really fit their contradictory goals: a) they don't want proactive marketing and public engagement, but b) they want to link somewhere from the app store page. (If the app is on app stores, that's about as public and customer facing as you can get, so ???) 

> [Background & goals of this page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23522#issuecomment-831355567)
> We don't want proactive press, but we do want a place for people to learn more about the app so folks can learn more about the app. This is not really marketing and PR, but more like "here's why we built the app" and a contact point for more information. The app store pages are user-facing, the goal of this page is to be for PR folks OR users who want to learn more, and offer them a transparent look into our process.

**Comment by jenniferlee-dsva** [comment]
Totally agree - it sounds like a press release. Or even product details content that just goes on the app store page itself - like this?

![image](https://user-images.githubusercontent.com/43381063/117468960-39995b80-af23-11eb-9b19-83c5c766580c.png)

**Comment by jenniferlee-dsva** [comment]
if you want ppl to download your app, why would you link them off of the app store page to another page that's static. you could just say everything on the app store page, keep them there, so they can still easily download the app. it is a confusing comms strategy.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Is this still something that is being considered or worked on? If so, I'll leave it in the backlog. If not, is this good to close?

**Comment by DanielleThierryUSDSVA** [comment]
We can close this, @RLHecht. Thanks!
