### ISSUE TITLE
Start Forwarding logs to VA's Splunk

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2416]
Boris would like us to start forwarding logs to VA's Splunk.
From Boris: Yep, for now. I would like us to save the VPC flow logs -> Cloudwatch.
- Create a LogGroup for VPC flow logs
- Create a subscription filter for Kinesis to forward to Splunk (ECSO COMS can walk you through that)

Came from this conversation: https://github.com/department-of-veterans-affairs/devops/pull/5686#discussion_r333717470

**Comment by ricetj** [comment]
@wyattwalter Craig, brought this one up and asked if we can take it on.

**Comment by ricetj** [comment]
@jbritt1 This is the ticket I spoke about and Nathan gave the overview for. @wyattwalter gave this to Jeremy to take on as a learning task.

**Comment by jbritt1** [comment]
I think I have done all that I can currently with this one after merging these. Taylor has agreed to help me with the applies, but for the Kinesis info I have from Boris it seems to require VA network access to accomplish the second half of this issue.

**Comment by jbritt1** [comment]
Tested with Craig yesterday morning on one of the envs. Flow logs were indeed being created and pushed to a log group in CloudWatch. This will still need assistance from someone with VA network access for the second half though.

**Comment by ricetj** [comment]
@nathanhruby to help bring this to complete.

**Comment by jbritt1** [comment]
All subscription filters with VAEC desired destination have been Terraform'd and applied to our infrastructure. I commented on the ticket this morning to ask for confirmation that the VPC flowlogs are being received as requested. Upon confirmation, we can close this ticket.

**Comment by jbritt1** [comment]
I attempted to bump the VAEC ticket yesterday asking to please confirm that the desired vpc flow logs were being received. Still awaiting response.

**Comment by ricetj** [comment]
Hey @boris-ning-usds, we aren't getting any responses from VAEC, so we are going to close this ticket, but let us know if you hear anything that would be useful. 

Here is the SNOW ticket: https://vaec-servicedesk.ec.va.gov/servicedesk/customer/portal/2/VAEC-3126
