### ISSUE TITLE
Build process shouldn't fail when a name contains double quotes

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#24177]
## Details
When a name in the GraphQL query data contains a double quote, the build process can fail in the "Apply layouts" step. For example:

```
{"depth": 5, "link": {"label":"Gerald "Jeremy" Mayo","url": {"path": "/"}, "links": []}, "parent": {"label": "Leadership", "links": [], "url": {"path": "/sioux-falls-health-care/leadership"}}}
                                       ^
SyntaxError: Unexpected token J in JSON at position 39
    at JSON.parse (<anonymous>)
    at liquid.filters.jsonToObj (/Users/chris/Documents/code/vets-website/src/site/filters/liquid.js:164:49)
    at exports.Context.callFilter (/Users/chris/Documents/code/vets-website/node_modules/tinyliquid/lib/context.js:387:28)
    at /Users/chris/Documents/code/vets-website/node_modules/tinyliquid/lib/vm.js:312:15
```

We need to ensure double quotes are handled properly so they don't fail the build.

## Acceptance Criteria
- [ ] Build process succeeds with names containing double quotes

**Comment by alexandec** [comment]
@meganhkelley @timwright12 looking into this a bit more, it appears to be an issue with how the liquid templates/filters stringify the JSON data from the GraphQL query. The quotes are correctly escaped in the original GraphQL data:

```
"title": "Gerald \"Jeremy\" Mayo",
```

But somewhere in the liquid template process this gets stringified and the escaping is removed:

```
{"label":"Gerald "Jeremy" Mayo"}
```

This is no longer valid JSON. When the jsonToObj liquid filter runs JSON.parse() on the invalid JSON, the build fails. So based on what I'm seeing, the fix would need to occur in the realm of liquid filters and templates.

**Comment by meganhkelley** [comment]
Hey @alexandec ! Are we able to see specifically which templates would be affected? Trying to determine whether we should hand this off to Facilities team or Public Websites team.

**Comment by alexandec** [comment]
@meganhkelley I narrowed down the issue to the following code in `src/site/layouts/person_profile.drupal.liquid`:

```
{% assign sidebarData = '{"depth": 5, "link": {"label":"' | append: title | append: '","url": {"path": "/"}, "links": []}, "parent": {"label": "Leadership", "links": [], "url": {"path": "' | append: fieldOffice.entity.entityUrl.path | append: '/leadership"}}}' %}

```

When this outputs the value for `title`, it doesn't escape double quotes, creating invalid JSON if double quotes are present.

**Comment by kelsonic** [comment]
Hey folks, this isn't our area of the code but I'm wondering if this would fix it. If we modify the following lines of code [here](https://github.com/department-of-veterans-affairs/vets-website/blob/fd09b2673b78103fc1ce5df910ced9a678650de1/src/site/layouts/person_profile.drupal.liquid):
```liquid
{% assign formattedTitle = title | replace: '"', '' %}
{% assign sidebarData = '{"depth": 5, "link": {"label":"' | append: formattedTitle | append: '","url": {"path": "/"}, "links": []}, "parent": {"label": "Leadership", "links": [], "url": {"path": "' | append: fieldOffice.entity.entityUrl.path | append: '/leadership"}}}' %}
```

**Comment by mpelzsherman** [comment]
I think Facilities should probably own this. We should probably convert the quotes into HTML entities (`&quot;`) rather than just stripping them out or escaping them wth `\`.

**Comment by mpelzsherman** [comment]
I managed to reproduce this error by editing the following node in tugboat:

https://master-7gb5iotuvt47rpo6jcdienuwvjyblpan.demo.cms.va.gov/pittsburgh-health-care/staff-profiles/donald-koenig

![Donald__The_Don__Koenig___VA_Pittsburgh_health_care___Veterans_Affairs](https://user-images.githubusercontent.com/80267/117515664-e647fd00-af64-11eb-9a0f-ff7f985bb554.png)

The fix suggested by @kelsonic does not resolve the issue, because the error occurs in a different template (src/site/navigation/sidebar_nav.drupal.liquid).

```
{"depth": 5, "link": {"label":"Donald "The Don" Koenig","url": {"path": "/"}, "links": []}, "parent": {"label": "Leadership", "links": [], "url": {"path": "/pittsburgh-health-care/leadership"}}}
                                       ^
SyntaxError: Unexpected token T in JSON at position 39
    at JSON.parse (<anonymous>)
    at liquid.filters.jsonToObj (/Users/michaelpelz-sherman/source/vets-website/src/site/filters/liquid.js:164:49)
```

I've confirmed that the data is properly escaped in pages.json (as @alexandec said). So we need to figure out where the data is being stringified and re-escape the quotes.
