### ISSUE TITLE
Quality Assurance Feedback - Staging Review - VAOS for Distribution

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#24176]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
Please consider using TestRail. TestRail is a test management tool that is configured to link to our GitHub repository (va.gov-team) for issue creation and reference. This allows a level of traceability from user story -> test case -> defect that is not available in a spreadsheet or external tool. If you need an account in TestRail please contact @pjhill via Slack, email, or GitHub comment for help.

It looks like you've added a distinct Cypress test spec for the COVID-19 user flows -- great work!

The spreadsheet with your test cases looks good. I'm curious about how many test runs were performed and at what point in the SDLC tests were executed. Does this spreadsheet represent the final run before staging review?

Since you're using JIRA for test management, would it be possible to generate a report demonstrating a link between test cases and user stories / other reference material?

Is a collection of defects generated by QA test activities available for review?

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

**Comment by laurenernest** [comment]
I don't know for sure how many runs were performed, but at least when the VAMF dependencies were released back at the end of March/early April.
> The spreadsheet with your test cases looks good. I'm curious about how many test runs were performed and at what point in the SDLC tests were executed. Does this spreadsheet represent the final run before staging review?

---

We (the VFS side) don't use JIRA, but our VAMF partners use JIRA and Confluence for some test tracking. They don't write up test case tickets that align with our user stories.
> Since you're using JIRA for test management, would it be possible to generate a report demonstrating a link between test cases and user stories / other reference material?

---

This is the record of findings specifically for this work https://github.com/department-of-veterans-affairs/va.gov-team/issues/21487#issuecomment-800232409
> Is a collection of defects generated by QA test activities available for review?
