### ISSUE TITLE
NOD - Phase 3 Design Enhancement

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#24173]
## Issue Description
As we go through final tech considerations and edits to content, design changes for the NOD form will be necessary. This ticket captures those design changes.

---
## Tasks
Complete final design updates.

## Acceptance Criteria
- [x] design updates are complete per changes from content and development needs
---

**Comment by kevinstachura** [comment]
Changes from this sprint for design --> dev and content have been made and can be viewed here:

https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538562
