### ISSUE TITLE
[Platform] Review Service Description Document and Interface Control Document (ICD) for VA Profile and send feedback

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#24182]
## Background

On 5.3.21, Terry Bazemore from the VA Profile team sent over the Service Description Document and Interface Control Document (ICD) for the notifications preferences and contact information work that we integrate through the VA Profile backend. We need to review these and get him feedback as soon as we can. 

## Tasks

- [ ] Review Service Description Document and Interface Control Document (ICD) that are attached
- [ ] Let Terry know via email thread if you have any feedback or if you have no feedback and everything looks good

[VA.gov-VAProfile-ICD-CommunicationPermissions_v0.9.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6422849/VA.gov-VAProfile-ICD-CommunicationPermissions_v0.9.pdf)
[VAProfile_Communication Permissions_ServiceDescription_v1.1a.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6422850/VAProfile_Communication.Permissions_ServiceDescription_v1.1a.pdf)

**Comment by Samara-Strauss** [comment]
Hi all — we have promised VA Profile that we'd get them our final feedback no later than **Next Friday, May 14th**. Please review these documents and send over your feedback in the email thread I CC'd you on by then. If we don't hear from you by then, we'll assume you have no feedback and the documents are good to go.

Let me know if you have any questions!

**Comment by joeniquette** [comment]
@Samara-Strauss Can you please let that team know we would like to meet with them to review this. The documents have a ton of information that isn't clicking with me.

**Comment by Samara-Strauss** [comment]
Email sent with you and @f1337 included. Please feel free to set up the conversation as your schedule allows. I don't need to be the in-between person to get this set up.
