### ISSUE TITLE
Copy archive step to GitHub Actions workflow

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#24188]
## Description
The archive step in Jenkins does a few things:
1. Generates the `BUILD.txt` file containing information about the build.
2. Archives the build output into a tar file.
3. Copies the build output to the S3 bucket `vetsgov-website-builds-s3-upload` at the path corresponding to the commit ref and build type.

This step should be included in the GitHub Actions workflow after prearchive and before deploy.

Note that although the step generates a `tar.bz2` file, it doesn't actually seem to be getting compressed. Evidence that suggests that might be the case:
- The [archive step](https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/common.groovy#L305-L321) only seems to `tar` the build without passing any compression flags.
- In the console logs for [deploy jobs](http://jenkins.vfs.va.gov/job/deploys/job/vets-website-vagovprod/1401/console), the expected [log for detecting the compression type](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-speedy-s3-assets/files/speedy-s3-deploy.sh#L86-L101) doesn't appear. It should be between `Fetching source` and `Expanding source into /build`.

Consider making the correction to compress the archive when adapting this to GHA.

## Acceptance criteria
- [x] The archive step is in the GitHub Actions workflow after prearchive and before deploy.
- [x] Archives for each build type are uploaded to S3 at the paths corresponding to the ref and build type.
- [x] Each archive has a `BUILD.txt` with the correct information.

**Comment by oseasmoran73** [comment]
Closing ticket as archive and deploy are now complete for `vets-website` and `content-build`.

Included compressed build in `tar.bz2`

**Comment by oseasmoran73** [comment]
Closing ticket as archive and deploy are now complete for `vets-website` and `content-build`. Will create a new ticket specifically for release portion.
