### ISSUE TITLE
Request access to Domo for Chris Valarida

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#24184]
# Request Domo access

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [x] Domo
_Please list any additional requirements, if any._

## Date Required
As soon as is convenient. :man_shrugging: 

## Product Team / External Team / VA Office
VSP design system team.

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by joanneesteban** [comment]
@laurensimpson14 same with this one: Chris will need edit rights.

**Comment by laurensimpson14** [comment]
@cvalarida You now have Domo access. I added you to both the Default group and the VSP Service Design group. Please let me know if you have any access issues!
