### ISSUE TITLE
Phase 2: Move vets-website Nightwatch E2E Tests to GHA

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#24185]
## Disclaimer

⚠️ We're currently using Nightwatch 0.9. Make sure you're reading the Nightwatch 0.9 docs. ⚠️ 

http://v09.nightwatchjs.org/

## Description

The nightwatch tests currently live in the [`Integration` stage of the `Jenkinsfile`](https://github.com/department-of-veterans-affairs/vets-website/blob/d2299dead1445ea6bad3c3bc3341098d83827ae5/Jenkinsfile#L148-L228). 

The `Integration` stage is actually split up into two separate workflows; [one that runs after a PR is merged to the `master` branch](https://github.com/department-of-veterans-affairs/vets-website/blob/d2299dead1445ea6bad3c3bc3341098d83827ae5/Jenkinsfile#L155-L182) and [one that runs whenever a commit is pushed to a non-`master` branch](https://github.com/department-of-veterans-affairs/vets-website/blob/d2299dead1445ea6bad3c3bc3341098d83827ae5/Jenkinsfile#L184-L209). 

In the `master` branch workflow, there are two steps related to Nightwatch:

- [`nightwatch-e2e`](https://github.com/department-of-veterans-affairs/vets-website/blob/d2299dead1445ea6bad3c3bc3341098d83827ae5/Jenkinsfile#L158-L160): runs the [`nightwatch:docker` npm script](https://github.com/department-of-veterans-affairs/vets-website/blob/d2299dead1445ea6bad3c3bc3341098d83827ae5/package.json#L48)
- [`nightwatch-accessibility`](https://github.com/department-of-veterans-affairs/vets-website/blob/d2299dead1445ea6bad3c3bc3341098d83827ae5/Jenkinsfile#L161-L163): runs the [`nightwatch:docker` npm script](https://github.com/department-of-veterans-affairs/vets-website/blob/d2299dead1445ea6bad3c3bc3341098d83827ae5/package.json#L48) with the `--env=accessibility` flag
   - This step is currently commented out because of test instability. 
   - Testing Tools has an [open ticket to fix the root cause of that instability](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23331). 
   
The non-`master` branch workflow only contains the `nightwatch-e2e` step. 

The `nightwatch:docker` npm script runs the following command, and uses the [`config/nightwatch.docker-compose.js` config file](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/nightwatch.docker-compose.js):

 ```
 nightwatch -c config/nightwatch.docker-compose.js --suiteRetries 3
 ```
 
## Acceptance Criteria
- [ ] Nightwatch E2E tests are executed in GHA
- [ ] Nightwatch E2E test parallelization continues to work in GHA
- [ ] Nightwatch test artifacts are collected and available in GHA

**Comment by billfienberg** [comment]
Other GHA branches:

- https://github.com/department-of-veterans-affairs/vets-website/compare/gha-full-build
- https://github.com/department-of-veterans-affairs/vets-website/compare/circleci-to-gha
- https://github.com/department-of-veterans-affairs/vets-website/compare/jenkins-gha
- https://github.com/department-of-veterans-affairs/vets-website/compare/gha-broken-links-check

**Comment by billfienberg** [comment]
WIP `add-nightwatch-gha-jobs` branch: https://github.com/department-of-veterans-affairs/vets-website/compare/add-nightwatch-gha-jobs

**Comment by billfienberg** [comment]
## How to run `yarn test:e2e` locally

### Pre-requisites for Mac

- A terminal to run `yarn watch` in `vets-website`
- A terminal to run `yarn watch` in `content-build`
- A terminal to run `yarn test:e2e` in `vets-website`
- [Oracle JDK](https://www.oracle.com/java/technologies/javase-downloads.html) installed 

### Links

- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started

### Steps

1. In one of the `vets-website` terminals, [start the `vets-website` app](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started#start-up-the-front-end)
2. In the `content-build` terminal, [start the `content-build` app](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started#content-build)
3. In the idle `vets-website` terminal, run `yarn test:e2e` to start the nightwatch tests

**Comment by billfienberg** [comment]
New branch with a cleaner commit history: https://github.com/department-of-veterans-affairs/vets-website/compare/24185-migrate-nightwatch-to-gha-take-2

**Comment by billfienberg** [comment]
## Take 3.0 

Branch: https://github.com/department-of-veterans-affairs/vets-website/compare/upgrade-major-version-of-nightwatch

### Experiment

Upgrade major version of nightwatch from 0.9 to 1.* (https://github.com/department-of-veterans-affairs/vets-website/commit/5af086bed6d25d736f9e2002889edeaf6380fcfb)

### Run: https://github.com/department-of-veterans-affairs/vets-website/runs/2577639024

### Result

COMING SOON

**Comment by ddzz** [comment]
PR opened: https://github.com/department-of-veterans-affairs/vets-website/pull/17284

**Comment by pjhill** [comment]
Nightwatch E2E test execution[ has been merged](https://github.com/department-of-veterans-affairs/vets-website/pull/17585) into [jenkins-gha-migration](https://github.com/department-of-veterans-affairs/vets-website/tree/jenkins-gha-migration) branch.

**Comment by pjhill** [comment]
The integration of Nightwatch E2E test execution into CI will be worked under this [ticket](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/25311).  That said, we are hoping to be able to deprecate Nightwatch in vets-website. We refactored the remaining Nightwatch tests into Cypress  under this [epic](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/25660).
