### ISSUE TITLE
Copy prearchive step to GitHub Actions workflow

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#24183]
## Description
The prearchive step is responsible for prefixing asset links with the S3 bucket URLs before archiving the build output. It occurs after the integration tests in Jenkins and should be included in the GitHub Actions workflow. Like in Jenkins, this involves calling the [prearchive script](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/prearchive/index.js) on each environment build.

## Acceptance criteria
- [ ] Prearchive script is called after integration tests in GitHub Actions workflow.
- [ ] Asset links match the S3 bucket corresponding to the build environment.

**Comment by U-DON** [comment]
No longer applicable to `vets-website`, but should be done for `content-build`.

**Comment by oseasmoran73** [comment]
Closing as PR was recently merged for `content-build`
