### ISSUE TITLE
Copy dev and staging deploys to GitHub Actions workflow

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#24190]
## Description
The final step of the Jenkins pipeline triggered by commits is to deploy to dev and staging.

This involves expanding the archived build from the archive bucket into the live bucket.

We may be able to reuse the [script that's currently being used for the Jenkins deploys](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-speedy-s3-assets/files/speedy-s3-deploy.sh).

## Acceptance criteria
- [x] The contents of the dev and staging S3 buckets represent the builds deployed from the corresponding archives.
- [x] There are no outstanding issues caused by moving the dev and staging deploys into the GitHub Actions workflow.

**Comment by oseasmoran73** [comment]
The work involved is completed in `vets-website` and content-build`. The acceptance criteria can't be completed as it would require Github Actions to be fully integrated

**Comment by oseasmoran73** [comment]
The work has been completed and integrated in `content-build` and `vets-website`. Closing ticket as #29254 addresses enabling to deprecate Jenkins.
