### ISSUE TITLE
VRRAP: Add 22-1990S to YTD report

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24192]
As an education team member, I need the YTD report to include submissions of the 22-1990S so that I can report back on the number of applications that have been received.

## Assumptions:
1. This work does not require a prod or feature flag.

## Acceptance Criteria
1. The YTD report includes the following 3 columns for 22-1990S details:
    a. The total number of application submissions for the current fiscal year to date (ex. 20YY-10-01..20YY-MM-DD 23:59:59 UTC)
    b. The total number of application submissions on the previous day (ex. 2021-05-04 00:00:00 UTC..2021-05-04 23:59:59 UTC)
    c. The total number of application submissions that were included in the spool file for the previous day (ex. 2021-05-04 00:00:00 UTC..2021-05-04)
2. The counts are displayed for each RPO in a vrrap benefit row
3. The counts are included in the:
    a. Total Row for the RPO
    b. All RPOS Total Row
4. The following email addresses are included in the Production “Year to date report” email distribution:
    a. Lee Munson (lee.munson@va.gov )
    b. Preston Sanders (preston.sanders@va.gov)
    c. Patrick Burk (patrick.burk@va.gov)
    d. Robyn Noles (robyn.noles@va.gov)
    e. Muskogee Corporate Mailbox (EDU.VBAMUS@va.gov)

## Supporting Artifacts:
1. [Sample_YTD_Report_w1990S_v2.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6423579/Sample_YTD_Report_w1990S_v2.xlsx)

**Comment by zurbergram** [comment]
Database - https://github.com/department-of-veterans-affairs/vets-api/pull/6792
Report update - https://github.com/department-of-veterans-affairs/vets-api/pull/6784

**Comment by delli-gatti-michael** [comment]
Submissions made on Staging 5/7/21 should show up on the YTD report sent out the morning of 5/8

**Comment by delli-gatti-michael** [comment]
[Testrail test case](https://dsvavsp.testrail.io/index.php?/cases/view/4825)
