### ISSUE TITLE
Secure Messaging Grafana Dashboard

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#24194]
## Description
It might be useful to have some Secure Messaging specific monitoring in Grafana.  This ticket covers the discovery and implementation of an SM dashboard.

## Acceptance Criteria
- [x] Look into what's currently available on Grafana for the mobile API and/or SM
- [x] Determine what type of info might be useful to monitor
- [x] Implement dashboards if we think it'd be helpful

**Comment by Teesh** [comment]
Merged in
