### ISSUE TITLE
Access for Benjamin Allen Mosher, Jr.

### ISSUE THREAD

**Issue by benniemosher** [department-of-veterans-affairs/va.gov-team#2419]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Benjamin Allen Mosher, Jr.
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Senior DevOps Engineer, Oddball
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

  > ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBbBBsRw2WpscYxEqsHQjL0+B+4//xBmZNsTeZySDbt3G+ixT3OCweKh5eOQ/92hyxs/AvGL4LLMB0h239M+6gfkZUkypCji/hmzcXjNG5ZBl29qs4tIqCyhlExAgsWbOteFFl7Qy+JzPaEUxLXV+D+VcyOqskiKtDDLwass6DnvdSaUml/1w4wrPUOXNEd/YwbxmONx6WqpXYrHgp8ARqTdwuWJ4bkuwFYAb41vPePPa4u2mkSkz7sLCR1GJvDHiaMz/cAG/ZpP8b+xreazXK7psPqeBvSXAZxTvPbkkrJlfprOsYNsT5WXbw3kBUBhhUeHReQeNLZ/2xV4waHMYeeLBfV8WWIc8r3WEIH3HMdvyy0LlOyG9gYzlS2Qh8rKfrev07y08d+xpxhuH0GQroxBGQStJ2eHILvzcoT8tMZMFPmnhcu1J9UwR/NFM8/IcYrSA3kVn9GsMAmbYWe6LIbbUKQese6unuuV3LzpErGDSPJGVQVIYn4KfMyG1YC/sVDrobbwvcKFQITNfiotHYst4opjlVrc1kRilF16nvZCZ69My4XhOZ9JWyNXqq11xfFRzX8iP6IGNJNxpguQ3E4jPxiB6xFRi8L0udOl6gTweAwVhbQFzttPF1N1u8kpbrlQpi2lzjOTPqpF9dIoWmKx7DSavTKUKQS4XqUrlIZQ== benniemosher@gmail.com

- [Grant AWS Console access?]
  > **YES** / NO
  >  Please give a brief description for why you are requesting AWS access.

Yes, will be in charge of maintaining infrastructure for VA applications.

**Comment by benniemosher** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Yourself
User: Benjamin Allen Mosher, Jr.

**Comment by ricetj** [comment]
Bennie still needs AWS access and approval, so we will keep this open till then.
