### ISSUE TITLE
Reconsider timeout for GI::Client

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#242]
As a follow up to https://github.com/department-of-veterans-affairs/vets.gov-team/pull/18917

At peak load, we've seen 230 requests/min to `v0/gi/institutions/autocomplete` if each of those requests takes 15s (our current read timeout) we will likely experience degradation of all vets-api. Typical response time is well below 1s for GIDS, so we should consider lowering the timeout.

**Comment by alexpappasoddball** [comment]
Duplicate and closing in favor of #241

**Comment by annaswims** [comment]
This ticket is not a duplicate and should be completed.  This work was not completed and we had an additional inciden https://dsva.slack.com/archives/C30LCU8S3/p1574355738471100

**Comment by annaswims** [comment]
#241 is an additional ticket to mitigate

**Comment by annaswims** [comment]
on a call with @mattpointzxer0 and @wyattwalter we settled on a 1s timeout.  it's 10x the slowest typical response.  Currently timeout is 15s

**Comment by omgitsbillryan** [comment]
IIRC we changed the FE bounce interval from 2 to 5s. If we set the BE timeout from 15 down to 1s, I think we should change that FE interval back down to 2s.

It will feel snappier for end users, and if one of their autocomplete requests happens to drop out, then so what, another request will be sent 2s later.

Also probably need to update alerting. Given the 1s timeout, we'd probably want to allow for a reasonably high % of timed out requests - more so than other external calls.

**Comment by annaswims** [comment]
I think we need to dig a bit deeper before we would increase the number of requests to GIDS.  The root cause of this all was database response time.  I think we increased the instance size, but I'd like to make sure we have proper indexing first.

**Comment by wyattwalter** [comment]
The bounce went from 150ms to 333ms. https://github.com/department-of-veterans-affairs/vets-website/pull/10320/files

That's a good point about alerting. We may see more 5xx responses which would indicate that the system is kicking in to protect itself. Probably still worth investigation if that happens, but worth updating wording on any text that comes out at a minimum.
