### ISSUE TITLE
Update vaccine flow breadcrumb

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24206]
## Description
Per VSP IA recommendations, update the breadcrumb in the vaccine flow.

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_cheetah` feature flag
- [ ] Breadcrumb for the vaccine flow is "New COVID-19 vaccine appointment"

### Out of scope
All other non-vaccine flows should remain the same

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/cheetah_flow.md) are updated

**Comment by laurenernest** [comment]
@LeKeve can you please update the flow screenshots? The link to the docs is in the DoD section. It'll end up being most of them.

**Comment by LeKeve** [comment]
@laurenernest Screenshots updated.
