### ISSUE TITLE
IA Feedback - Staging Review VAOS - VAOS for Distribution

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#24203]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

Per recommendations from IA request https://github.com/department-of-veterans-affairs/va.gov-team/issues/19821
While these recommendations are not launch blockers, they do ensure consistent language and experience for our users - it utilizes common terminology and structure in the breadcrumb and URLs to ensure context is clear.  Changing URLs post-launch creates a risk that users will receive a 404 if redirects are not properly implemented. 

- For the breadcrumb, consider adding the word "appointment" to the last segment of the breadcrumb **and** the small caps above the H1  (i.e. Home > Health care > Schedule and view appointments > VA online scheduling > New COVID-19 vaccine appointment).  This is consistent with with other appointment types in the tool. 

- I walked through the URLs proposed and reviewed the H1s as well as the URLs used elsewhere on the site and within VAOS.  My goal was to make them concise and consistent.  Here are my recommendations: 

Page | URL | Notes
-- | -- | --
New   covid appt | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment | Content uses the word "appointment", not "booking". 
New   covid appt - contact facility | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/contact-facility | More accurate description of step - user will contact a single facility, not multiple
New   covid appt - dose history | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/confirm-doses-received | current URL (/received-dose) is a statement rather than a request for action or input
New   covid appt - Choose facility | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/choose-facility | clear description of step in process
New   covid appt - Choose clinic | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/choose-clinic | clear description of step in process
New   covid appt - Select date | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/select-date | 
New   covid appt - Second dose  info | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/second-dose-info | More accurate description of step - step is providing info, not planning the next dose
New   covid appt - Contact info | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/contact-info
New   covid appt - Review | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/review
New   covid appt - Confirmation | /health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/confirmation

**Consider:**

**Comment by laurenernest** [comment]
Updates made in #25380 and #24206. Closing ticket.
