### ISSUE TITLE
[Research] Variant test - improve completion rate of facility selection page

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#24213]
### Problem
Currently 75% of users who land on the facilities page move to the next step. We want to raise this completion rate this page. 
We also want to increase the speed at which those who complete the page, move on to the next step (Need analytics to measure baseline against)

### Hypothesis
We believe that if we provide simpler interactions and clearer language on the facility selection page, veterans will be able to more easily understand their options. This will help them complete the facility selection step more quickly, whether they move on to the next step, or drop-off. This will also help them complete the step successfully slightly more often.

### Test
We'll build a variant of the VA facility selection page that modifies:
- Header language  
- Facility sorting interaction

We'll release this variant to 50% of users for a limited time. We'll then turn the variant off and compare it to a cohort of users who saw the current page in the same time frame.

### Design assets
[Sketch file](https://www.sketch.com/s/439713c6-cb08-4b65-94ab-d97dcac0beba)
 - [New workflow overview (IP) ](https://www.sketch.com/s/439713c6-cb08-4b65-94ab-d97dcac0beba/a/3Obqv7j)
 - [Selector states (IP)](https://www.sketch.com/s/439713c6-cb08-4b65-94ab-d97dcac0beba/a/rbl4jRd)

### Analytics:

We'll compare 
* Percent of users in each cohort who completed the step successfully
* Percent of users in each cohort who did not complete/dropped off
* For each cohort, time on page for those who completed the step
* For each cohort, time on page for those who did not complete/dropped off

### Gravity problem
VA facilities don’t offer online scheduling for every type of care. It’s a challenge to communicate this to a veteran.  And this creates a ceiling for the total number of users who can actually complete this page that we can’t design around.

### Product Checklist
- [x] Summary and analytics links [documentation in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/variant-tests/2021-sorting-facilities.md)

- [x] Dev ticket(s)
- #24280 (dev)
- #26106 (events for analytics)

- [x] [Results readout slides](https://docs.google.com/presentation/d/1SvwwoiDa6OrzAuTWwetqAz2WUH3j4z0Q73muJXfwipk/edit?usp=sharing)
  - [x] Benchmark
  - [x] Outcomes

**Comment by laurenernest** [comment]
Dev ticket for this variant #24280

**Comment by outerpress** [comment]
Current state/progress on these captured below (see "Design Assets" for newer changes)

Still to do:
* Add "loading" state (when "location" selected)
* Validate select list functionality with eng
* Get copy and a11y feedback

![Current facilities page.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/ca6dbc48-7a48-41ac-b49b-9b7a3f6f620d)!

[Sorting selector states.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/04e6974c-4ebd-4c8f-b794-e577aaa97731)
