### ISSUE TITLE
COVID-19 vaccine mini-hub eligibility updates 5.5.21

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#24246]
Recommendations to update content based on current eligibility.

[Who can now get a COVID-19 vaccine_updates_05.05.21](https://app.zenhub.com/files/133843125/fd6d0302-63c6-4740-86ae-a18bf9f1fd2d/download)

**Comment by DanielleThierryUSDSVA** [comment]
Morning, @lalexanderson-dsva! When you have a moment, let me know what you think of the attached. Thanks!

**Comment by RLHecht** [comment]
This work has been completed. Closing ticket.
