### ISSUE TITLE
Expand/collapse icon separates from text in accessibility "display size" mode

### ISSUE THREAD

**Issue by msmanak** [department-of-veterans-affairs/va.gov-team#24254]
## What happened?
Depending on the device's text size, there are cases where the 'V' caret on the expand/collapse component separates from the text that precedes it, causing the caret to appear on its own line.

This expand/collapse component appears on the following pages:
- LOA 1 gate
- Edit Direct Deposit 
- Compose/Send message forms

## Specs:
- user +41

## Devices:
- iPhone 11, when adjusting text size
- Google Pixel 4, in dynamic text mode. 

## Steps to Reproduce

1. Google Pixel display size mode on
2. Click on sign-in button
3. informational "before we give you access..." page displays the accordion disconnect.

Alternative steps on iPhone 11:
1. In the device's settings, update the Text Size to notch 7 out of 12
2. Log in with +41
3. Navigate to the Edit DD page
4. Observe the "Where can I find these numbers?" accordion. 

## Acceptance Criteria
1. The caret icon should not separate from the text that precedes it and get pushed to its own line
2. If the caret icon cannot fit on the same line as the label, it should display on the right side of the component so it is middle-aligned with the text _(note for dev: this is how it works on iPhone 11, when the text size is on notch 8 of 12)_:
![Image from iOS.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c009ef14-64d5-4897-ab08-1c032f840aba)

## Screen shot(s) and additional information
![Screenshot_20210503-205134.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/269a8599-5d4c-4dbc-8a9d-dc128b819931)

![Image from iOS (20).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/8bd3dae9-b1a5-4397-bc64-5b532dee1d35)

**Comment by bessgreen** [comment]
Note: Pixel 4 is not in the device matrix for app launch. Dev team will need to rely on simulators, rather than physical devices, to resolve & test this issue.

**Comment by digitalken** [comment]
PASS 7/7/2021 - Looks good on iOS and Android.  Closing.
