### ISSUE TITLE
[Discovery] Determine Impact of Sampling on GA Product Health v2

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#2425]
## User Story or Problem Statement
As an analytics-insights team member, I want to see the impact of sampling on trendline reports within the Product Health tool. 

## Goal
- Compare data pulled via API against Unsampled reports

## Objectives or Key Results this is meant to further
- Communicate if data has been sampled using 12+ month timeframe
- Summarize results and how this impacts our roadmap with or without a data warehouse

## Acceptance Criteria
- [ ] Review @deweydell's prototype
- [ ] Run unsampled reports within Google Analytics
- [ ] Compare delta

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@deweydell When you're back, can you walk me through the local version, and we can compare the data?

**Comment by nedierecel** [comment]
@joanneesteban @jonwehausen Please see the spreadsheet where I am pulling unsampled reports directly from Google Analytics to the Core Reporting API: https://docs.google.com/spreadsheets/d/150sv50j-feov62FQMKoLa1rOAuFzwKlYuFcpvy_igLI/edit#gid=903064363

I will pull a few more comparisons at the goal level. From my events and pageviews so far, I am not seeing sampling, but we may as we pull longer date ranges beyond 12 months.

**Comment by nedierecel** [comment]
@joanneesteban @deweydell @jonwehausen I completed a comparison of 4 key items for the Product Health tool. The only item remaining is for me to insert links to the unsampled report or Core Reporting API logic I used. 

- Pageviews to the Education Hub
- Success events
- Failed events
- Goal completions 

In its current state, data does not appear to be sampled using the core reporting API since it's pulling from a standard set of reports. If we reach a point where the timeframe we are pulling exceeds 100M sessions, we will expect to see sampling.

**Comment by nedierecel** [comment]
@joanneesteban One other comment that may impact sampling - if we filter or add segments to the reports, there is a chance with the Core Reporting API that this data might be sampled. For the existing set of data points, this is not happening but may occur if we allow MVP users to filter (e.g. "As a Product Health MVP user, I want to filter out VA.gov network domain traffic")

**Comment by joanneesteban** [comment]
Sampling impacts have been determined.
