### ISSUE TITLE
Investigate & fix how app is displaying/clearing errors

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24266]
## Context
There are inconsistencies in how the app is handling errors. For example:

1. When navigating to certain pages, the app will display a Generic Error. When leaving the page, and returning back to it, it will display a null state UI instead of the Generic Error. 
     - Test with: +49, Claims & Appeals
2. On certain pages, the app will flicker between a Generic Error and a null state, w/o leaving the page. 
      - Test with: +366, Messages
3. Using user +41, iOS displays either an error or "you don't have any submitted claims or appeals" for claims, but Android shows an active claim.
     - Test with: +41, Claims

## Dev task

- [ ] Investigate how the mobile app is displaying and clearing errors
- [ ] General rules _(add to this list as needed)_:
     - Errors should not display in lieu of a null state
     - If a user refreshes an error, it shouldn't clear if the error is still happening

## Related issues
#23021
#23176
#22347

**Comment by keli13** [comment]
Investigation: 
Generic errors need to be updated to be tracked per page rather than all in one. Otherwise it will clear the generic errors when navigating to a different page and going back to the old one.

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/27/2021 - Looks good with no flashing/changing screens.  Closing.
