### ISSUE TITLE
IA Request Claims & Appeals - Disability Wizard

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#24263]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kick-off ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/README.md)
- [Mural board](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1599137761089/b5b2662802d862b436660938241e79d1ef4ecf31)
- Link to or attach [user/page flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md)
- Link to or attach your content source of truth, including H1s (if separate from prototype/mockup) N/A

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

[IA documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-apply-wizard.md) for implementation teams; also includes some UX documenation
Additional UX guidance captured in [UXPin documentation](https://preview.uxpin.com/ca08f3dbf63475b2b62f3e8c00050ad1b19c4cb5#/pages/132986657/documentation/no-panels?mode=i) (using Edu flow as an example)
Content outlines of [wizard user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/how-to-apply-wizards/content-outlines/education-forms-wizard.md)
[Site Links changes content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14982) for Public Websites

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?

**URL(s)** - What are your suggested URLs and why?

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
Hi @vhenry07, could you please open a separate issue for the HLR wizard to split these two and let me know what the priority is between them?  Thank you!

**Comment by mnorthuis** [comment]
Actually, the HLR wizard is already live, so not sure what the work is for that one...

**Comment by vhenry07** [comment]
@mnorthuis We're only moving the wizard from the info page to the intro page. [This thread](https://dsva.slack.com/archives/C0113MPTGH5/p1617112949005200) outlines direction that this go through the collab cycle.

**Comment by mnorthuis** [comment]
@vhenry07 Yes, but this ticket references 2 different wizards - 526/Disability and HLR.  The slack thread only references the 526, so can we remove HLR from this issue?

**Comment by shiragoodman** [comment]
@vhenry07  - did you see @mnorthuis's comment above? Please reply ASAP so we can move forward with this work. Thanks.

**Comment by vhenry07** [comment]
Yes, we can remove.

**Comment by mnorthuis** [comment]
> Yes, @mnorthuis, we can remove.

This was the info that I needed to confirm scope.

**Comment by mnorthuis** [comment]
@vhenry07 a draft of the IA information is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/wizard-disability.md

I'm still reviewing this and working through some entry points.   

A couple of things for next steps...

1) Please review the user flows and URL for the actual wizard move - these are different than what is implemented currently in staging.  These flows are based off the work that was done last fall, and a recent accessibility change to move the wizard onto its own page (/start) rather than as a display state on the /introduction page.   Please post any questions to this ticket so we can finalize that aspect of the work. 

2) You will need to coordinate content updates on the static pages and changes to entry points, which will be done by the sitewide content team.  Please open an intake ticket with them for this work.  You can reference this IA issue, please indicate that it is still in progress for now.  Once they have a chance to review the work, then I will connect with them to finalize.  

Let me know if there are any questions, and I will let you know once this is final.  Thanks!

**Comment by vhenry07** [comment]
> @vhenry07 a draft of the IA information is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/wizard-disability.md
> 
> I'm still reviewing this and working through some entry points.
> 
> A couple of things for next steps...
> 
> 1. Please review the user flows and URL for the actual wizard move - these are different than what is implemented currently in staging.  These flows are based off the work that was done last fall, and a recent accessibility change to move the wizard onto its own page (/start) rather than as a display state on the /introduction page.   Please post any questions to this ticket so we can finalize that aspect of the work.
> 2. You will need to coordinate content updates on the static pages and changes to entry points, which will be done by the sitewide content team.  Please open an intake ticket with them for this work.  You can reference this IA issue, please indicate that it is still in progress for now.  Once they have a chance to review the work, then I will connect with them to finalize.
> 
> Let me know if there are any questions, and I will let you know once this is final. Thanks!

Adding @Mottie and @ashagross

**Comment by mnorthuis** [comment]
IA is complete.  You can close this issue at your discretion.
