### ISSUE TITLE
526 Usability Testing

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#24264]
## Issue Description
526/BDD Usability Testing

---
## Tasks
- [ ] Complete usability testing. 

## Acceptance Criteria
- [ ] Finish remaining end user testing
---

**Comment by chrvalla** [comment]
Complete

Results can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd/BDD%20Research/BDD-Usability-test-April2021

Closed
