### ISSUE TITLE
Create GA Report to validate typeahead data

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24267]
## Description

Reviewing the Typeahead POC2 data we as a product team, have highlighted the need to validate the DOMO dashboard data by adding a new tag and confirming the data in Google Analytics. This issue is to establish the report in GA 

## Background/Context

General Analytics Request for Search & Discovery [#23948](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23948)

## Tasks

- [x] Establish GA Custom Report for variable: `search-typeahead-used`

## Definition of Done

- [x] Custom Report has been created.

**Comment by srsuddath** [comment]
As part of this report I think we should look at the following event "funnel"

Report 1 - Searches completed overall:
event: view-search-results

Report 2 - searches where typeahead was enabled (should be approx 35%, will eventually be 100%)
event: view-search-results
search-typeahead-enabled: true

Report 3 - searches with typeahead enabled and used
event: view-search-results
search-typeahead-enabled: true
type-ahead-option-keyword-selected: != undefined (aka if this is set to anything)

Report 4 - number of search clicks where typeahead was used
event: onsite-search-results-click
search-typeahead-used: true

Using these numbers we should be able to determine our search typeahead click-through rate by calculating report 4 / report 3

**Comment by denisecoveyduc** [comment]
@srsuddath has established a GA report that allows us to monitor to total number of searches, the total number of searches that have suggestions, the total number of searches that selected one of the suggestions that was presented and finally how many selected a result after selecting a suggestion. 
This funnel enables us to calculate overall conversion rates at each stage and provide us with the data needed to make strategic decisions as we move forward and iterate on the feature. 

**GA Report  Link** - https://analytics.google.com/analytics/web/#/dashboard/Iv7tzMW8QEeoyu_P6PXzXQ/a50123418w177519031p176188361/_u.date00=20210501&_u.date01=20210525/
