### ISSUE TITLE
CT Redesign: Allow location search via Map control

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24261]
As a developer, I need to update the map control in the CT Redesign sandbox to allow for the user to change the viewport and conduct a new search from the tool so that the functionality can be usability tested.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria:
1. The map has a button that:
    a. Is not displayed on page load
    b. Is displayed when the viewport of the map changes
    c. Allows for the user to execute a new search via the map
    d. Is removed after the execution of any search (map, search control,
2. Changing and searching via the map have no impact on:
    a. the search text box
    b. the distance drop down

## Supporting Artifacts:
1. [Prototype - Map after search conducted](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296060309_Searchbylocation_Desktop_results)

2. [Prototype - After user interacts with map viewport](https://bahdigital.invisionapp.com/share/QCIAGXOTD3P#/296060649_Searchbylocation_Desktop_results_zoomin)

3. [VA.gov Location Finder](https://www.va.gov/find-locations)

**Comment by zurbergram** [comment]
Exclude invalid lat/long values from going into institutions table - **requires generate and publish**
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/831

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17583

**Comment by sonntag-adam** [comment]
Testing passes QA. Closing story



https://dsvavsp.testrail.io/index.php?/runs/view/1940&group_by=cases:section_id&group_order=asc
