### ISSUE TITLE
[FE] Profile, My VA: Profile and My VA have inconsistent x-padding

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#24279]
The Profile tends to have less x-padding compared to the My VA Dashboard. The breadcrumbs in particular are not consistent.

![profile - small screen.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/2641c4c3-ef80-43eb-bb15-fbdaaf07a240)
![profile - normal screen.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/b93fff70-cb12-4ab3-84d6-e844fd23476b)
![profile - wide screen.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/34bcde0d-16d1-468a-87ec-09e7c35f3c9e)

The padding on the Profile seems to be correct on _small_ screen sizes.
The padding on My VA seems to be correct for screen sizes larger than mobile.

To do:
- [ ] When the screen size is larger than mobile, make the x-padding of the breadcrumbs on the Profile match the My VA Dashboard
- [ ] When the screen size is mobile, make the x-padding of the My VA Dashboard match the Profile

**Comment by erikphansen** [comment]
@tressaellen can you review this when you have a chance and let me know if my plan for making the Profile and My VA have consistent x-padding sounds correct to you?

**Comment by tressaellen** [comment]
@erikphansen this looks correct to me!
