### ISSUE TITLE
Remove page label from pagination component

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24281]
## Acceptance Criteria
1. Update the pagination component (#21331) so that it no longer displays the page label. Remove "Messages", Claims and appeals", and "Appointments" from the pagination copy.
     - Across all pages, the pagination component should now display as: **# to # of #**

## Screenshot for reference
![Screen Shot 2021-05-05 at 10.52.30 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/04e88e13-5996-48b4-873a-4e7adac378f7)

**Comment by digitalken** [comment]
PASS 5/10/2021 - Looks good on Android and iOS.  Closing.
