### ISSUE TITLE
[BE] Notification Preferences: Change update communication preferences API

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#24284]
https://dsva.slack.com/archives/C909ZG2BB/p1620225484347900
Frontend has requested that the communication preferences API be changed from accepting an array of communication channels to accepting a single communication channel

**Comment by erikphansen** [comment]
One other request that I mention on a recent VA Profile call:

Could you adjust the `GET` response to include the `id` with each member of the `communication_groups` array?
