### ISSUE TITLE
Find a VA Form - link related form titles to appropriate detail pages.

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24282]
## User Story

As a user I would like to be able to access the detail pages of related forms directly from form detail pages so that I don't have to do a separate search to learn more about them. 

On Find a VA Form, detail pages listed in search results link to the form's detail page, but are not linked when a form is listed under "Related Forms" on other forms' detail pages.  Example below. 
### Search Results
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/344bbdb2-4e69-49b3-87c6-fbb6cdc547bd)

<hr>

### Detail Page
![image.png](https://images.zenhubusercontent.com/5f92fce34aee8412716359a7/e86276a4-37d5-42ce-a828-c124738d01e5)

## Expected Behavior

Any form listed under "Related Forms" should provide a link to its detail page (if one exists).

## Acceptance Criteria

- [x] Titles for forms with detail pages are linked appropriately to when they appear under "Related Forms"
- [x] Change is reviewed for usability and accessibility
- [x] Change is peer reviewed
- [x] Internal review is done with PO and PM
- [x] If team agrees it behaves as expected, change is promoted to Production.

**Comment by zacharymorel** [comment]
Reference => https://dsva.slack.com/archives/CUB5X5MGF/p1619530881081000

Need to add the following to the build graphql query: 
entityUrl.path
entityPublished

Need to also wrap logic around it in template.

**Comment by zacharymorel** [comment]
@joshkimux @rtwell Can you give this snap shot of the new links a thumbs up or thumbs down? Thank you.
CC: @MarciMcGuireGCIO @callen2563 

![Screen Shot 2021-05-07 at 1 42 26 PM](https://user-images.githubusercontent.com/26075258/117488277-378ec700-af3a-11eb-89a7-0d11c242c5c5.png)

**Comment by MarciMcGuireGCIO** [comment]
Just to add a little context - prior to now, the names of forms under "Related forms and instructions" did not contain links to their respective detail pages, even though they were linked form the form search results page.  This is what it looks like in Production currently:

![image](https://user-images.githubusercontent.com/73354907/117490424-bf75d080-af3c-11eb-8dac-ee9e707db461.png)

**Comment by callen2563** [comment]
From a Visual Design perspective I'm seeing some styling that is showing some inconsistencies from what we just determined in UI Consistency. For example the download links should have the download icon in front. "VA Form 21-674" should be a header link style.

**Comment by MarciMcGuireGCIO** [comment]
Per Shira, this will require design and most other steps in the Collab Cycle.  Converting to Epic.

**Comment by MarciMcGuireGCIO** [comment]
This is being handled  in Epic #21639

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @callen2563 

Details pages on staging has new look. FYI, make sure the details pages point to staging.  
https://staging.va.gov/find-forms/about-form-10-10ez/

**Comment by johnhashva** [comment]
Based on quick glance, looks good to me, @zacharymorel

**Comment by MarciMcGuireGCIO** [comment]
This looks great, @zacharymorel!  @callen2563 can you please take a look when you have a chance?  Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 have you had a chance to review this on Staging and provide feedback?

**Comment by MarciMcGuireGCIO** [comment]
Comments were being added on a different ticket.
