### ISSUE TITLE
Icon Expander - Media-list-images Page R&S

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#24293]
## Issue Description
_Iterative work on #21847 for each image show the expand icon that is actually just a link to the raw image._

Example: 
![116948657-3bba9c00-ac3d-11eb-98d8-cc8ad0c0c9c6](https://user-images.githubusercontent.com/70410912/117192814-63c21080-ad9f-11eb-955d-ac61c5d12e7d.png)

## Acceptance Criteria
- [x] Implement according to description with images expand as intended 
- [x] Fixed according to design specs
- [ ] Validated on preview
- [ ] close out ticket once validated

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
I found out that the expand button on the facility map pages is rendered conditionally depending on if the media type has a property called fieldAllowClicksOnThisImage: https://github.com/department-of-veterans-affairs/content-build/blob/dc59dd6401e5f[…]7c59f10188ace515b0d43a0/src/site/paragraphs/media.drupal.liquid

For the media list images page, we don't have that property on the images. Perhaps that's something CMS could add though? If we want to show the expand button by default on every image, however, then I can just render it always for media list images pages, not based off a fieldAllowClicksOnThisImage field.

This is what we will do here as per @rtwell's comment [here](https://dsva.slack.com/archives/C52CL1PKQ/p1621948261196400?thread_ts=1621947972.194000&cid=C52CL1PKQ) 👍

**Comment by kelsonic** [comment]
PR merged, will go out with the daily deploy today

**Comment by brianalloyd** [comment]
@rtwell this should be ready for validation, could you review and let me know if we need to tweak anything in support.  Thanks.

**Comment by rtwell** [comment]
Hellos! How might I see these changes—is there a page I can visit?

**Comment by kelsonic** [comment]
@rtwell you should be able to see it here with socks on: http://preview-prod.vfs.va.gov/preview?nodeId=6954 🙂

**Comment by kelsonic** [comment]
I just saw that when you expand `Show more`, the extra images don't have it yet, so will get a follow-up PR for that now 👍

**Comment by rtwell** [comment]
lookin' good @kelsonic tyvm!

**Comment by brianalloyd** [comment]
Validated and closing ticket. Thanks @rtwell and @kelsonic
