### ISSUE TITLE
Establish inventory of all search tagging events

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24292]
## Description

As a product team we want to maintain an inventory of all analytics tagging events we track in order to establish custom reports in Google Analytics and monitor what data is available. 

## Tasks

- [x] Create an inventory of search tagging events

## Definition of Done

- [x] inventory has been added to github (Denise will add the folder link of where it should live?)

**Comment by srsuddath** [comment]
Doc has been updated with {GA} for all fields that are tagged in google analytics
