### ISSUE TITLE
Test User Dashboard Kubernetes Onboarding

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#24307]
## Description of your application
_Name_: Test User Dashboard
_Functionality_: staging.va.gov test user management tool
_Language/Stack_: JavaScript/Gatsby
_Ports/Networking needed_: Unsure
_Other infrastructure needed e.g. Database, redis, etc_: No
_Anything else we need to know?_: The TUD frontend is currently [configured to ping `https://staging-api.va.gov`](src/utils/api.js) in non-development environments, should this configuration change for deployment? That environmental check is done through the use of the `NODE_ENV` env variable. 

## Background/Context/Resources
_Any addition information that can be provided, Slack conversations, tickets, design documents, epics, etc._
* TUD Readme: https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/blob/main/README.md

## Technical Notes
_Any addition technical notes that can be provided_

## Checklist of Items needed for onboarding (Responsible parties in parentheses)
- [x] Your application! (Your team)
    Your application should conform to the 12 factor app methodology (https://12factor.net/)
- [x] A Github Repository for your application (Operations or your team)
- [x] A Dockerfile for your application (Your team, Operations can assist if needed)
- [x] Elastic Container Registry Repository for your application (Operations, PRs are welcome: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/ecr.tf)
  - (https://github.com/department-of-veterans-affairs/va.gov-team/issues/24265)
- [x] Automation to "Release" and "Tag" the application Github Repository with a semantic version number. (Your team, Operations can assist if needed)
  - (https://github.com/department-of-veterans-affairs/va.gov-team/issues/23839)
- [x] Automation to push the built Docker container to the ECR Repository and tag it with the semantic version number. (Your team, Operations can assist if needed). Please do not use 'latest' tags
  - (https://github.com/department-of-veterans-affairs/va.gov-team/issues/23840)
- [x] Kubernetes Application Manifest in YAML, jsonnet, or Helm Chart (Operations and your team)
    YAML and jsonnet are highly preferred, Helm charts are discouraged
  - (https://github.com/department-of-veterans-affairs/va.gov-team/issues/23844)
- [x] Automation to update the Kubernetes Application Manifest when a new version of your application container is pushed to ECR (Operations and your team)
  - (https://github.com/department-of-veterans-affairs/va.gov-team/issues/23846)
- [x] AWS Service account for your team or application (Operations)
- [x] Path/s in AWS SSM Parameter Store created for your team or application (Operations)
- [x] AWS IAM Permissions applied to your team members to allow read/write access to AWS SSM Parameter Store path/s for your application/team (Operations)
- [x] AWS IAM Permissions applied to the service account to allow read access to AWS SSM Parameter Store path/s for your application/team (Operations)
- [x] Secrets and Parameters needed for your application stored in AWS Systems Manager Parameter Store (Your team)

**Comment by AGarcia-Clarity** [comment]
@department-of-veterans-affairs/vsp-operations Any updates on which sprint this will be pulled into?  Thank you.

**Comment by jhouse-solvd** [comment]
@AGarcia-Clarity - Just wanted to make sure I dropped a note here. This is ongoing, and I believe the next step is to get the application manifest set up for Kubernetes, which will help control the deployment aspect (cd) for the app. hope this add'l information helps, and please let me know if you need any more.

**Comment by AGarcia-Clarity** [comment]
@jhouse-solvd That is correct.  Demian shared this with us https://github.com/department-of-veterans-affairs/devops/projects/13  I've been using it to track the awesome work your team has been completing :sunglasses: . Thank you.

Not a priority at this moment but we can discuss what the subdomain will be I remember discussing it being something like vfs.tud.va.gov instead of tud.staging.va.gov.

**Comment by jhouse-solvd** [comment]
@AGarcia-Clarity - oh, cool. that's perfect. you're in good hands. just ping me if there's anything that you need.
