### ISSUE TITLE
Back-to-Top broken in IE

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#24309]
## Issue Description
The back-to-top component doesn't show up in IE.

## Steps to reproduce
1. In IE, go to https://design.va.gov/components/back-to-top
2. Scroll down in the component iframe

**Comment by mmiddaugh** [comment]
Related issue: #25103

**Comment by k80bowman** [comment]
We need to check and see if this is still an issue in the design system component. If it is, we need to fix it. If not, we can close this.

**Comment by k80bowman** [comment]
Closing as this is fixed with the back-to-top web component.
