### ISSUE TITLE
Explore Structured Markup Entity Field 

### ISSUE THREAD

**Issue by srsuddath** [department-of-veterans-affairs/va.gov-team#24304]
## Background
As part of this previous ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22442, it was determined that the following sites can't be updated to have a Main Entity Field due to them being static content pages, and any metadata changes will require buy in from the content team, as well as changes to the page templates in order to support it. The pages impacted by this are as follows:

https://www.va.gov/welcome-kit/
https://www.va.gov/privacy-policy/
https://www.va.gov/veterans-portrait-project/
https://www.va.gov/pension/pension-management-centers/
https://www.va.gov/housing-assistance/home-loans/
https://www.va.gov/health-care/get-reimbursed-for-travel-pay/
https://www.va.gov/health-care/family-caregiver-benefits/
https://www.va.gov/disability/how-to-file-claim/when-to-file/
https://www.va.gov/disability/eligibility/special-claims/
https://www.va.gov/coronavirus-research
https://www.va.gov/careers-employment/vocational-rehabilitation/

## Tasks
- [ ] Discuss overall changes needed across departments in order to allow the Main Entity field to be used on these pages.

**Comment by denisecoveyduc** [comment]
There is currently no plan to tackle this since it will require a lot of coordination across multiple teams with little benefit to users. Will leave it in the icebox to assess if things change after time has passed but for now this is not actionable.
