### ISSUE TITLE
Design Exploration - Search Landing Page

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24300]
## Description

As a product team we would to explore the creation of a search landing page

- [Initiative Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/search-landing/initiative-brief.md)

## Background/Context
- Establish Search Landing Page [#23648](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23648)

## Tasks
- [x] design exploration 

## Definition of Done
- [x] Link or screenshots of search landing page have been included on ticket and are ready for team review.

**Comment by mgleo** [comment]
![design-exp-landing.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/0d4a7e99-7d31-4056-ac94-20a1ef2bd464)
