### ISSUE TITLE
VAOS Sustainment | Variant Testing

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24319]
## Summary
This epic houses all tickets related to timed variant tests in VAOS.

Additional documentation on the tests can be found on [GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/initiatives/variant-tests)

**Comment by ldelacosta** [comment]
No further action is needed at this time. Closing out the epic @JRRoof
