### ISSUE TITLE
CT Redesign: Export addresses with missing latitude or longitude for batch processing

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24324]
As a developer, I need a process to identify and export institution addresses that are missing latitude or longitude data and export from GIDS as CSV in Census Tool Format, so that the missing data can be populated by future functionality.

## Assumptions:
1. The export file does not require a header row.
2. Each institution has a physical and mailing address, we only want to use the physical address as specified in AC1.

## Acceptance Criteria:
1. The user can export a CSV of institutions missing latitude and/or longitude data containing the following physical address data:
    a. Unique ID (Facility Code)
    b. House Number and Street Name
    c. City
    d. State
    e. ZIP Code

2. The institution data is identified for inclusion in the data file when:
    a. The most recent version of approved institution data for a facility code does not have a latitude or longitude 
 _**OR**_
    b. Approved WEAMS rows that have one of the following conditions
      - that have a facility code without "cross" data in Ipeds_hd or scorecard 
      - In either Ipeds_hd or scorecard  for "cross" value: have invalid or null latitude or longitude values, -90 <= latitude <= 90, -180 <= longitude <= 180
      - In Ipeds_hd for "cross" value: The Weam's physical city, physical state, or institution name does not match Ipeds_hd values
      - In Scorecard for "cross" value: The Weam's physical city or physical state does not match Ipeds_hd values

    c. If a facility code meets both 2A and 2B, only the 2B physical address data is used.
    d. If an approved Weams row's physical address data is not available the mailing address is used if these check pass:
      - In Ipeds_hd for "cross" value: The Weam's physical city, or physical state does not match Ipeds_hd values
      - In Scorecard for "cross" value: The Weam's physical city or physical state does not match Ipeds_hd values

3. If there are 10,000 rows or less, the file is exported as a single CSV.
4. If there are more than 10,000 rows, a file is generated for each 10,000 rows (ex. 15,000 rows generates 2 files)
5. The user has the ability to navigate directly to the census tool (https://geocoding.geo.census.gov/geocoder/locations/addressbatch?form) from GIDS

## Supporting Artifacts:
1. Census tool file format guidelines: [link](https://www.census.gov/programs-surveys/geography/technical-documentation/complete-technical-documentation/census-geocoder.html)
2. Sample UI

    > <img width="638" alt="Screen Shot 2021-05-21 at 1 54 42 PM" src="https://user-images.githubusercontent.com/48260534/119178749-223a9200-ba3c-11eb-84ce-d5d23ee9b112.png">

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/837

**Comment by sonntag-adam** [comment]
In staging. Closing story.
