### ISSUE TITLE
Access for [individual]

### ISSUE THREAD

**Issue by ashagross** [department-of-veterans-affairs/va.gov-team#24329]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Asha Gross
- Please Provide your email.
   > asha.gross@adhocteam.us or hello@ashagross.com (used for github)
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Claims & Appeals Frontend Engineer Adhoc

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtfAZuuFImS/UJmwBWJO+YLDhpSm3mr/tVdbtjlsVUUWYoZCWFDU/Pj/Lv8gMDGhmQr8DkYEZBrCTthMttNsjNRw7NegEKTDl2owvn6Am/QhX34bWqD0TdbrriIK6GzwErbSSUkdXzDJw0MbFEJdAgjNzWM7gU4jEQ6mgxQ3MG2C+NdO7h5DKqCJuLRgczlDs2X03K1I/FtAyIUDc64rUmcGwMXuWA2OoYDZLPVH52EMkDwuqQxhkmCbPP3LkbMmQOO8bdbqPcc6RPYZapayEVOr58Cov6sfq+1Q++LleZJKPqFXqRW3oQaveNuYTKdOWDOxDTNfjVpZ0ln1SLBUumFOvIRSXOQnOFoxwAVFf2OTPDZMCjHeOZHC5GEKpEqexYSVeTk9KYOxGZiQzYkVurPPii2R2b2vvIYyreczRxmd25TPsT/B5Knt1zDQuLn7g3DF2+LfXahR0EpkzBlvp2LZlU3DvliIlcc2jGGYHrkyDHpqeFpXJL+jDzbyRdLws= elif-asha-gross@elif-asha-gross-macbook.lan
```

- Grant AWS Console access?
  >  NO

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
