### ISSUE TITLE
Design Feedback - Design intent [Healthcare Experience - Check-in]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#24326]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Great jobs on these flows!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Focus the user on the [primary task.](https://design.va.gov/design/principles) Priority 1 is that the are checked in, priorty 2 is view appointments. Priority 3 is Questions (see consider feedback for an option)
![Screen Shot 2021-05-06 at 1.49.10 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/42133297-6208-4af8-a13e-e6216d86b323)

**Should:**
- When a user clicks on check in and goes into app, put them on the specific appointment screen if possible

**Consider:**

- (Primary focus option) Move the ‘You are now checked in…’ to H1 and put the action link in the alert box, and last have 'Questions' content. The verbiage may have to change to support the new hierarchy
- Not using a progress bar for only 2 steps
- Formatting Questions similar to Need Help (add blue line)

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by kristenmcconnell** [comment]
It looks like the mobile app team will be picking up this check-in work and further refining the check-in Veteran experience there sometime this summer. I added the mobile specific comment above into the Sketch for Teams file that is becoming a living document for multiple teams, so the comment doesn't get lost. 

The va.gov website experience wireframes have been updated to reflect the above comments. You can review the updates within the "text to va.gov" workflow wireframes: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/kaVYLYP/play

**Comment by allison0034** [comment]
@kristenmcconnell thank you!
