### ISSUE TITLE
CT Redesign: Import census tool latitude or longitude data

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24332]
As a developer, I need to be able to import a census tool data file so that missing latitude and longitude data can be populated and used in future comparison tool functionality.

## Assumptions:
1. SA2 outlines the format of the file that is returned by the census tool.  Not all data needs to be persisted.
2. Uploading the census tool data behaves as all other GIDS files uploads and previously uploaded data is purged with each new upload.

## Acceptance Criteria:
1. The user can upload one or more CSV file(s) at a time containing the following data into GIDS:
    a. Record ID Number (ID from original address list - Facility Code)
    b. Input Address (Address from original address list)
    c. TIGER Address Range Match Indicator (Results indicating whether or not there was a match for the address (Match, tie, no match))
    d. TIGER Match Type (Results indicating if the match is exact or not (Exact, non-exact))
    e. TIGER Output Address (Address the original address matches to)
    f. Interpolated Longitude, Latitude (Interpolated longitude and latitude for the address)
    g. TIGER Line ID (Unique ID for the edge the address falls on in the MAF/TIGER database)
    h. TIGER Line ID Side (Side of the street address in on (L for left and R for right))

## Supporting Artifacts:
1. Census tool file format guidelines: [link](https://www.census.gov/programs-surveys/geography/technical-documentation/complete-technical-documentation/census-geocoder.html)
2. Sample Import File: [GeocodeResults.csv](https://github.com/department-of-veterans-affairs/va.gov-team/files/6434946/GeocodeResults.csv)
3. Sample UI:

    > <img width="638" alt="Screen Shot 2021-05-21 at 1 54 42 PM" src="https://user-images.githubusercontent.com/48260534/119179043-76de0d00-ba3c-11eb-9ce9-7d52542ce9d9.png">

**Comment by elder-joseph** [comment]
DB Specific PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/839

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA
