### ISSUE TITLE
CT Redesign:  Research plan - Search / Sandbox	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24330]
- [x] Draft initial research plan
- [ ] Review w UX Team 
- [ ] Update based on feedback

**Comment by JenLJ** [comment]
Research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/usability-testing-may2021/research-plan.md
