### ISSUE TITLE
Caregiver Form URL is broken

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#24339]
## Description

When the new 10-10CG PDF was uploaded, the URL changed from: https://www.va.gov/vaforms/medical/pdf/10-10CG.pdf to https://www.va.gov/vaforms/medical/pdf/VA%20Form%2010-10CG.pdf.

This is causing the intro page of the online 10-10CG to break, as well as other places that were linking to the old pdf. 

## Acceptance Criteria

Change the form URL back to the old, or redirect back to the old one.

**Comment by johnhashva** [comment]
@ala-yna  + @mlighdc my teams don't have access to this page https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction to fix the link -- but we were able to update the link on this page (it's in the CMS) https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/ to fix the link.   Can you take that one on?

**Comment by mlighdc** [comment]
Thanks @johnhashva , I think @LinnJS has a PR in place to take care of it. 

Sorry to bother your team.

**Comment by ala-yna** [comment]
I was wondering if it was possible to rename the file upload? I'm sure there are other places on the internet that might still be using the old link. Not sure how that process works, or if we have access to it. But we can also change the url on the form intro page as a short-term fix.
