### ISSUE TITLE
Access for Dat Tran

### ISSUE THREAD

**Issue by dat-gcio** [department-of-veterans-affairs/va.gov-team#24334]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Dat Tran
- Please Provide your email.
   > dtran@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSA; Role: Front-End Engineer; Employer: GovernmentCIO
- SSH key (public)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvcGvdk5mrqv64/MJXTSRNHJGHzynx8kOFx081aDJCHayPUrJLYTO7Vya2hj+JjBoif4Pjrph6sXngcuTRCp8in5RzBhnQQ0YwQuhe+FXw4f+9z9bR97kXgUveZ4sbwruPyxrErWc1Kmvl0rUdQgppwe0d5EX1ulhIqA8BbEvPUXgGGCrOXRUuL93Ash0MNEYMG/oWLBAhFGgrJUiICihDrRCHX2j3zKzgqK0xaHyi9SSYSHetgm3zKLDC/zuezPTI93os22L22sl1E5Yi7/tyHT7y8O7HkRPuMKwh2CCVSwim0/G7g6ZAzVPBiLMvpnsG7YcdFhro++hMPTu0OSIsYO+0XFVATYemKTIsBYGtC95OZ8TR3r8KcrwfsJwpg4u4mr10jy8kvzHvlnXImTLMsGfUnoHZouOwyQtDcAOff+sVcNVOPwDcvLKCtj4hES5+qpHdJ8dD2C1Y838xx9sh4HvCK2PPP6zTQYpUw9ZR6J7fxeH/7pT9JF4kox0esIk= dtran-c02zjahdlvdl@Dats-MacBook-Pro.local
```

- [Grant AWS Console access?]
NO
>General: software development, troubleshooting, and understanding of systems, potential pipeline and delivery improvement. Specific: shell access to development and staging systems for troubleshooting, log analysis, testing, and walk-through with developers.

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
