### ISSUE TITLE
Check In Integration Point (CHIP) vt

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#24344]
Create API infrastructure for VETlink Replacement[https://app.zenhub.com/files/133843125/1b7a4025-6133-4c5b-a4a0-ec84741e3721/download](https://app.zenhub.com/files/133843125/1b7a4025-6133-4c5b-a4a0-ec84741e3721/download). (see attachment)

**Comment by aschulhof** [comment]
Completed
