### ISSUE TITLE
Add `agreed` to VEText API model for KMI and surface in LSV view

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#24347]
### Background
Users of the SLA version of KMI are now required to check a box that states they have access to VHA's Notice of Privacy Practices. This removes the need for a facility to collect this acknowledgement at point of care via paper. We'd like to get evidence of this acknowledgement pushed over to VEText and made available via the `OVAC_VEText.LSV.COVID_Vaccine_Data_CDW` view so if a privacy audit needs to done on any KMI SLA patients, we will have evidence of acknowledgement documented.

## Request
Add the attribute `agreed` to KMI endpoint in the VEText API so VA.gov can start sending over this data. We'll be sending over a boolean value, but feel free to process and store it in whatever type makes sense for you. There will likely be a follow up ticket submitted to update existing records for which we have an `agreed` value but it has not been submitted to VEText.

**Comment by Kennon-git** [comment]
- [ ] Create fields on clinical and cdw sides
- [ ] modify the api

**Comment by shanemelliott** [comment]
added the field @wamccarty you will have to edit the sync job.

**Comment by Kennon-git** [comment]
done, not in production yet

**Comment by Kennon-git** [comment]
rob to push to prod today
