### ISSUE TITLE
Move Delete button to the top of form pages

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24340]
## Acceptance Criteria
1. On the Contact Information forms, move the Delete button (e.g. "Remove mailing address") from the bottom of the form so that it now displays at the top of the form
     - Ensure that when the Delete button does _not_ display (because there is not a saved entry), there is not a gap between the page header and the form
2. This change applies to 6 form pages (all but Mailing address):
     - Home address
     - Phone > Home
     - Phone > Work
     - Phone > Mobile
     - Phone > Fax
     - Email address

## Designs
https://adhoc.invisionapp.com/console/Mobile-App-screens-cknr12ik52y3t01yqc9678i1z/ckobq9sc000at015bgqegfkyd/play

**Comment by digitalken** [comment]
PASS 5/24/2021 - Looks good on iOS and Android.  Closing.
