### ISSUE TITLE
Update KMI SLA records with corrected `dateCreated`

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#24342]
### Background
The `dateCreated` field for KMI records available via the `OVAC_VEText.LSV.COVID_Vaccine_Data_CDW` view appears to be populated with the date in which the record was created in the VEText database. This is completely fine for almost all records. However, there are a set of records that sat in the VA.gov database before being sent to VEText for a considerable amount of time, so the `dateCreated` value in the LSV view above is significantly different than the actual time the record was submitted to VA.gov. While the `dateCreated` value and the time in which a form was submitted on VA.gov do **not** need to be exact, it is helpful for operational and analytical purposes if they are someone similar.

### Request
Use the attached `sid` --> `created_at` mapping below to update the `dateCreated` field for KMI records in VEText. The timestamps are in UTC; if TZ needs to be changed to align with other dates in the `dateCreated` column, no problem.

[`sid` --> `created_at` mapping file] (https://app.zenhub.com/files/133843125/a052b16b-0bd2-4351-85c2-77d12313baaf/download)

**Comment by shanemelliott** [comment]
Imported Data into clinical and Cdw
Updated records based on SID.
