### ISSUE TITLE
[ZOOM]: Text Appointments - Need a space between input and label in modal window

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2435]
## Description

The modal dialog window needs a space between the top input field and the second label element. Screenshot attached.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

1. The inputs have proper spacing
2. No other items are changed visually

## Screenshots or Trace Logs

![Screen Shot 2019-10-14 at 3 44 48 PM](https://user-images.githubusercontent.com/934879/66781809-e28fe980-ee99-11e9-86d7-aeeb1942ad28.png)

**Comment by lkoenigsberg** [comment]
This will move to the Authenticated Experience board for consideration as we merge account and profile to a single page and redesign. (cc/ @Justin-Pickett )

**Comment by 1Copenut** [comment]
Verified in staging
