### ISSUE TITLE
GIDS: Add ability to upload VRRAP providers file

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24358]
As an Education team member, I need the ability to upload a file containing providers that offer programs eligible for VRRAP to GIDS so that information can be displayed on the provider profile page within the comparison tool.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The file type is "VRRAP Providers".
2. The user has the ability to:
    a. Import a data file
    b. Export a data file
3. Accepted file formats for the data file are:
    a. .txt
    b. .csv
    c. .xls
    d. .xlsx
4. Valid column delimiters are:
    a. ,
    b. |
5. The accepted imported file has the columns in the following order:
    a. SchoolName
    b. FacilityCode
    c. Programs
    d. VACO Approved/Disapproved
    e. Address
6. The following columns are required for data to be imported:
    a. FacilityCode
    b. VACO Approved/Disapproved
7. The VACO Approved/Disapproved data is included in the institution version generation.
8. The column is named `vrrap_provider` on version export

## Supporting Artifacts:
1. [Draft Only_Approved VRRAP Schools List_23Apr2021.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6436614/Draft.Only_Approved.VRRAP.Schools.List_23Apr2021.xlsx)

**Comment by zurbergram** [comment]
DB - https://github.com/department-of-veterans-affairs/gibct-data-service/pull/835
Main - https://github.com/department-of-veterans-affairs/gibct-data-service/pull/833

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Testing complete
