### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by CoryTrimmUSDS** [department-of-veterans-affairs/va.gov-team#24356]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo

## User Email Address
cory.trimm@va.gov (Google account created)

## Access Requirements
Please check the analytics tools you need access to:
- [x] Google Analytics
- [x] Domo

## Date Required
Ongoing.

## Product Team / External Team / VA Office
OCTO, Identity Team

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Hi @CoryTrimmUSDS ,

Thank you for your request. 

You should have received an email invitation with your access to Google Analytics and DOMO. 

We will close this request but please do feel free to reopen should you have any access related questions and/or concerns.
