### ISSUE TITLE
Content Feedback - Staging review - Caregivers Sign as Representative 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#24359]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
@ala-yna Hello, please see below for content feedback on Caregivers sign as representative work. Please let me know if you have any questions. 


**Question**
The content shown in the content source of truth doesn't match the content that appears on staging. Specifically, the edits listed below in the should feedback. 

Does staging need to be updated with the language that appears in the content source of truth?  content? 

**Should feedback**
 
On the Upload screen: 
1. I recommend changing “documentation” to document in the header to be more plain language and to be in alignment with how we talk about this in the intro paragraph. We use “documents” not “documentation”
**H: Upload your legal representative document**

2. Suggested edits to the bullets below, for plain language: 

Guidelines for uploading a file:
•	You can upload a .pdf, .jpeg, or .png file
•	Your file should be no larger than 25MB

**Comment by Dene-human** [comment]
The [prototype](https://preview.uxpin.com/e3a1c4cfb7408175af0bc54173e311d14a406ae2#/pages/138525977/simulate/sitemap?mode=i) has not been updated to be the content source of truth.

Update to plain language on upload documentation page will be addressed in #24588

**Comment by Dene-human** [comment]
Hi @peggygannon 
All "should feedback" has been updated and is reflected [on staging](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)

**Comment by ala-yna** [comment]
@peggygannon - Please take a look at staging and let us know if you have any other feedback. Thank you!

**Comment by peggygannon** [comment]
Hi, @ala-yna @Dene-human Thank you for the follow up. The updates look good on staging.

**Comment by Dene-human** [comment]
@peggygannon Apologies for reopening the ticket- and not sure this is the correct place for this question, but my FE dev says that since we accept .jpg should we also include this on the list of "You can upload" files?

Regarding:
Guidelines for uploading a file:
• You can upload a .pdf, .jpeg, or .png file



cc: @dat-gcio

**Comment by hdjustice** [comment]
Closing this ticket - feature launched to 100% in July 2022
