### ISSUE TITLE
Access for Andrew Ramos

### ISSUE THREAD

**Issue by ramosan-lit** [department-of-veterans-affairs/va.gov-team#24362]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Cecilia Lee Cecilia.Lee@va.gov
- Please provide your name.
   > Andrew Ramos
- Please Provide your email.
   > andrew.ramos@libertyits.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Name: Shanktopus
       Company   : Liberty ITS
       Role            : Product Manager 

- Requesting SSH key authorization?
   > YES 
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+yDXQI9JX3CTaYrfpwEFf6jbccs4y2eBqdFVVnB8y67RwDq0avnOf4/1VN6pH+Hw9ZYD5ACvx8PE0+0f3nw5sTyXMl6d90dIzVDeRsT3lbC6E85D5TVUjNCsTl//aznSLYV4oj31zrbFKnPfvgmENldCltOzW6LHsY4N0A6J2HSRcNE4KL52qJul8din34wBvhkzvTXu/l/5GvCIS5bE9O564dnackDN+f3jwK6uagAVJWI/NTZkF8k90iqOCI31iUdAvQ7qp5lNp4eh+DXx4BuYVNTZav32Q84XC3LcBiVpp8JP5qZITnFABE+8C1vItB649LvuTFYtUgo1Zm27oj/XE/GPKg3XojRUjkwwLRXRgcD2JCeExL7byTyBZ23jn4JGpQYuNGO5j0Y1sx5u9AYhVss24KSBrIBD5FoehiPXHJjqTeD5ea2Vp+DvTUdnQLHQripj1Vlf8pL7DWuHz4z4gfYYwlE5LCltGJsZOR86VNKfdJ+W09BwEaWHgMFk= AzureAD+AndrewRamos@WIN-FTOH8HM5OIQ
```

- Grant AWS Console access?
  > YES
  - What AWS services do you need access to and why? 
  S3, EC2, RDS - everything that's used in vets-api on the VSP side of the house including things like CloudWatch

**Comment by jbritt1** [comment]
### AWS Access:

User: Andrew Ramos
COR: Cecilia Lee
Approval Needed: @Jeff-Hayter

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by ramosan-lit** [comment]
I apologize but I have forgotten my password on my key. Can I generate a new one and provide it here?

**Comment by jbritt1** [comment]
> I apologize but I have forgotten my password on my key. Can I generate a new one and provide it here?

Yep, just drop it here and we can get it updated for you.

**Comment by ramosan-lit** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKzoOTYqia0lLfKmypbmnOQ3bukNeYFnvfk3gi2dCTFzZ05bHPdP+q5IazoPMJbrXnVm2/jmrcz5EbPcLg5SI59Hj0BB95XxhPYe9b1fRhdQYnn5W5cnbmP0JXrlZHoH85pTxnyeO5Xo9IWKRhl9mrYlFDswfCrNKl7c/qp0QyQMfohIr7fLidv9y7rSiEIUI4ghg/DMn89+MtA5T7Mpq2+V3JgY/K6TMOGEkUMWI6SoGbSdS7nWJEdOlYi+YpFSm3h8mycmI5En2DSi9Qu07F3LqTcWohUByBjZ9pH1YxUmN2h1kzbVRJhutbsJ92UBHKmFC/65fmF+bJQFaYAi63/9xQP6FiTdVz3J918GtOhlWG4pN8ohOQTXhGa4/1YTP6Sr0e6b3VDrRZZq8iR9MkAtotODdxm8XK5ubgab5KUD4xF+HQ1blugGQf9MImr6llIMvNKfcjq6Msnu9SNQYItHLx8KIEi/kpWJ1jIIathug6Exf0W0PPk5uuHk80T2c= AzureAD+AndrewRamos@WIN-FTOH8HM5OIQ

**Comment by ramosan-lit** [comment]
When I try and connect I get the following error:

`socks@172.31.2.171: Permission denied (publickey)`

**Comment by ramosan-lit** [comment]
All good now.

**Comment by drorva** [comment]
@jbritt1 looks like this can be closed

**Comment by jbritt1** [comment]
> @jbritt1 looks like this can be closed

I believe this user is still awaiting approval for AWS access.

**Comment by jbritt1** [comment]
Since this is an older ticket that had originally tagged Jeff H., I might should have re-tagged anyway...

AWS Access
User: Andrew Ramos
COR: Cecilia Lee
Approval Needed: @drorva, @mchelen, @thepipster

**Comment by drorva** [comment]
Request sent to CORS

**Comment by drorva** [comment]
Approved

**Comment by jbritt1** [comment]
Temporary credentials passed to user at this time.
