### ISSUE TITLE
Sign Out button - Active state should have darker text to match border

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#24364]
## What happened?
Sign out button should have darker text to match the border color in active state.

## Specs:
Default state:
Border color: #CD2026
Background color: #ffffff
Copy: Mobile Body Bold, #CD2026

Active state (when pressed):
Border color: #981B1E
Background color: #ffffff
-> Copy: Mobile Body Bold, **#981B1E**

## Steps to Reproduce
View Sign Out button.
Hold finger down on sign out button.

## Desired behavior
Text color on active state should match specs.

## Acceptance Criteria
see above

## Bug Severity
- 4 - Low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21986

## Screen shot(s)

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/0a0ca39e-7782-443d-8aec-0c8a0233dbcc)

**Comment by bessgreen** [comment]
Upon further discussion with @msmanak, we are going to keep the font color the same across both the active/default states. This pattern is consistent with the other large buttons in the app. 

Current implementation passes. Closing this ticket, as it is no longer an issue.
