### ISSUE TITLE
[Bug] COVID FAQs - IE11 - Anchor Tags not working

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#24372]
## What happened?
With Internet Explorer 11, on Staging **[Coronavirus FAQs](https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/)** page, after clicking an **anchor tag** in any expanded accordion-section, the **Link saved** flag was not displayed.

## Specs:
- Device: Windows 10 PC/laptop
- Browser: IE11

### Video capture

https://user-images.githubusercontent.com/587583/117396633-33699780-aeaf-11eb-8d6d-b8a665ba35d9.mp4

## Steps to Reproduce
- URL: https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/
- Expand any accordion section, then click the **anchor tag** at the bottom of the expanded section.
- Observe that **Link saved** flag is not displayed.
- Open a new **browser tab** and in the **address box** attempt to **Paste** you clipboard contents [whatever they might  be].
- Observe that either nothing's pasted [you haven't copied anything prior to clicking the anchor-tag], or what's pasted was from a previous Copy [of something prior to clicking anchor-tag].

## Desired behavior
- [ ] **Link saved** flag should be displayed next to any clicked **anchor tag**.  [See #20125]
- [ ] Deeplink actually copied on-click, able to be Pasted into address-box of new browser-tab.

## Acceptance Criteria
- [See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by SKasimow** [comment]
@youngfreezyVA Hi Fareez - can you take a look at this issue and add points for fixing. Thanks
