### ISSUE TITLE
CT: Remove Rogers STEM Scholarship Indicator from profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24375]
As an EDU team member, I need the Rogers STEM Scholarship indicator that is displayed on the institution profile page to be removed because the data source is not being set correctly and will not be corrected in the near future.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The "Rogers STEM Scholarship" and data is not displayed in the "Institution summary" area of the "Additional information" section of the profile page.
2. The "Rogers STEM Scholarship" search results is not displayed under the "Programs" search results filters.

## Supporting Artifacts:
1. Location of Indicator:
<img width="441" alt="Screen Shot 2021-05-07 at 8 12 42 AM" src="https://user-images.githubusercontent.com/48260534/117447862-07303400-af0c-11eb-95d0-bcc6cb1264db.png">

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17885

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/2014&group_by=cases:section_id&group_order=asc
