### ISSUE TITLE
CT: Add VRRAP Participant indicator to institution profile page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24373]
As an education benefits recipient, I need a way to see if an institution is participating in the VRRAP program when browsing the comparison tool so that I can determine which benefit I am able to use at that institution.

## Assumptions:
1. This work is completed behind a prod flag.
2. Data referenced in AC was made available in #24358.

## Acceptance Criteria
1. In the "Institution summary" area of the "Additional information" section:
    a. "**Veteran Rapid Retraining Assistance Program (VRRAP):**" is displayed with a "Yes" if the institution facility code is included in the VRRAP provider data with a status of "Approved".
    b. "**Veteran Rapid Retraining Assistance Program (VRRAP):**" is displayed with a "No" if the institution facility code is included in the VRRAP provider data with a status of "Disapproved".
    c. "**Veteran Rapid Retraining Assistance Program (VRRAP):**" is not displayed if the institution facility code is not included in the VRRAP provider data.

## Technical Note ##
1. AC1c will be NULL from the backend data source.

## Supporting artifacts:
1. AC1
![image](https://user-images.githubusercontent.com/48260534/117446752-87ee3080-af0a-11eb-843f-88b5fb772d20.png)

**Comment by ksantiagoBAH** [comment]
Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/17644

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1959)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Testing Complete
