### ISSUE TITLE
Front-end Accessibility Testing Checklist | Before Staging | Lang Assist. & Resource Pages (with footer update)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#24370]
Process doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md

## Front end tasks

[ x]Ensure the page is styled according to design spec.
[ x]Ensure the back end data from API is displayed in local and review instance
[ x] Ensure unit tests are available.
[x ]Ensure your code changes are covered by E2E tests
[ x]Run axe checks using the Chrome or Firefox browser plugin
[ x]Test for color contrast and color blindness issues
[ x]Zoom layouts to 400% at 1280px width
[ x]Test with 1 or 2 screen readers
[x ]Navigate using the keyboard only

Acceptance Criteria

 Designer comments on this issue to approve page styling
 Unit tests pass
 E2E tests cover current code and regression
 End-to-end tests show 0 violations.
 The data returned matches API response (for given user or scenario)
 All axe checks pass
 All color contrast checks pass
 All zoom testing passes
 All keyboard checks pass
 All screenreader checks pass
Appendix

Ensure your code changes are covered by E2E tests (expand)
 Run axe checks using the Chrome or Firefox browser plugin (expand)
 Test for color contrast and color blindness issues (expand)
 Zoom layouts to 400% at 1280px width (expand)
 Test with 1 or 2 screen readers (expand)
Navigate using the keyboard only (expand)
How to configure this issue

 Attached to a Milestone (when will this be completed?)
 Attached to an Epic (what body of work is this a part of?)
 Labeled with Team (product support, analytics-insights, operations, service-design, tools-be, tools-fe)
 Labeled with Practice Area (backend, frontend, devops, design, research, product, ia, qa, analytics, contact center, research, accessibility, content)
 Labeled with Type (bug, request, discovery, documentation, etc.)

**Comment by SKasimow** [comment]
@youngfreezyVA - hi...should I open up multiple tickets for the FE accessibility testing (ie one for each page plus footer)?

Also, can you point this when you have a chance? I'm putting it in next sprint vs current.

**Comment by youngfreezyVA** [comment]
i think just one is fine, since the only change re: accessibility will be the language section

**Comment by SKasimow** [comment]
cool - how many points should I put on it?

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - when you've completed, can you please update this checklist in Github (needed for Staging Review):  https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/content-localization/accessibility-checklist-language-assistance.md
