### ISSUE TITLE
Copy check content style guide update

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#24386]
On these 3 branch PRs: 

Character count exceptions for RS, news releases, event titles:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/455

Clarified meta title tag character count info, per new RS etc. exception: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/456

VAMC meta title tag formatting update: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/457

FYSA ^ @bethpottsVADEPO @DanielleThierryUSDSVA

**Comment by jenniferlee-dsva** [comment]
No rush, but I would love to merge this sometime next week. And then Randi, you and I can work on the update email with Michelle's web governance featured content.

**Comment by RLHecht** [comment]
Work completed on this and newsletter is going out 5.13 at 7 a.m. closing ticket.
