### ISSUE TITLE
[Site Services Maintenance Notification] DSLogon June 5-June 6

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#24388]
### Frontend engineering support 

- [ X ] **Other- Site Services Maintenance Notification**
   - DSLogn Extended Outage is Scheduled Saturday, 5 June and continue until the evening of Sunday, 6 June
      - Due to the database migration, DSL is anticipating an extended outage potentially starting Saturday, 5 June at 8 am PST/11 am EST and lasting until Sunday, 6 June 8 pm PST/11 pm EST. 
      - As a reminder, technical partners that are making back-channel API calls will need to have their IPs whitelisted. For technical partners connecting through the F5 network, URLs will remain unchanged. Please plan accordingly.
 
Contact: Agloro, Amanda K CTR (USA) <amanda.k.agloro.ctr@mail.mil>

   
### What Needs to Be Done

- Make sure we have a plan for utilizing the [Sitewide Maintenance Banner ](Sitewide system maintenance downtime banner) to alert VA.gov users to this long-duration service outage.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Public Website
- DEPO product owner: John Hashimoto
- Product manager: Brian Lloyd
- Designer: Cassandra Allen
- FE engineer: Kelson Adams
- Product/team Slack channel: #vsa-public-websites

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by brianalloyd** [comment]
@johnhashva could we determine time scope for the outage?  Also, need to determine which banner we would like for this "Promo" Vs. "Maintenance Banner" is what was discussed during grooming session.

**Comment by kelsonic** [comment]
This is where we would set up the config for this maintenance banner: https://github.com/department-of-veterans-affairs/vets-website/blob/96da57c412d3bd0f0dd7feac96d32fe1376cbf49/src/platform/site-wide/banners/config/maintenanceBanner.js

Specifically, we need:

1. What is the exact time we should show it?
2. What is the exact time we should stop showing it?
3. What is the title? Default = `'Site maintenance'`
4. What is the content? Default = `"We’re working on VA.gov right now. If you have trouble signing in or using tools, check back after we're finished. Thank you for your patience."`
5. Do you want to show a warning before the downtime happens? If so, how much time before we show the maintenance banner should we show the warning?
6. What should the warning title be? Default = `'Upcoming site maintenance'`
7. What should the warning content be? Default = `'We’ll be doing some work on VA.gov. The maintenance will last x hours. During that time, you won’t be able to sign in or use tools.'`

CC @brianalloyd @johnhashva

**Comment by johnhashva** [comment]
5/12 Update from DS Logon below -- TL/DR: event delayed.   Hours are still not known.  I will follow up week prior

When we were planning our extended outage, we did not take into consideration that it was Memorial Day weekend.  We have updated our extended outage date.

DSL Extended Outage Tentatively Scheduled 6/5 - 6/6:

DSL will be migrating to high availability site tentatively scheduled for Saturday, 5 June. Due to the database migration, DSL is anticipating a 24-hour extended outage potentially starting Saturday, 5 June and lasting until Sunday, 6 June**. Exact days and times will be communicated out as the schedule is finalized.**  As a reminder, technical partners that are making back-channel API calls will need to have their IPs whitelisted. For technical partners connecting through the F5 network, URLs will remain unchanged. Please plan accordingly.

**Comment by kelsonic** [comment]
@brianalloyd @johnhashva can we close this one? 🙂

**Comment by johnhashva** [comment]
Yep.  Closing now.
