### ISSUE TITLE
Contact Center Review | Anchor Tags | C&L Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#24399]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high level description of your product.*

The goal of this pilot is to test making it possible to share deep content contained within a very long page and easier to access deep content through a shared link. 
A new clickable icon will be introduced on one page for the pilot. The new clickable icon will enable users to copy a deep link to their clipboard. They can then paste that link and share it in an email or their choice of application.  

The coronavirus FAQ page will be used to pilot this new feature.

### Launch Date
*Please provide the launch or rollout date and details.*

Target mid-May (exact date will be determined post staging review)

### Version Number
*Please provide the version number of the guide and/or video.*

Version 1

### Product Guide
*Please provide product guide link*

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/Anchor_Tags_Product_Guide_5-7.docx  

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by SKasimow** [comment]
Also, can you send me the final copy? @starlow00

**Comment by starlow00** [comment]
Sharing with VEO for review.

**Comment by SKasimow** [comment]
Thanks @starlow00  Lmk if anyone has any questions on this feature!

**Comment by starlow00** [comment]
No changes from VEO. Closing.
[Anchor-Tags-Product-Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6496259/Anchor-Tags-Product-Guide.docx)
