### ISSUE TITLE
Messages not displaying in custom folders 

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#24400]
### Issue
Messages are not displaying in customer folders within secure messaging

### Expected behavior
These messages should display when a user clicks into a custom folder

MHV needs to make the fix (MHV Jira ID of MHV-15742) has been prioritized as our #1 ask during MHV's increment planning.

**Comment by digitalken** [comment]
PASS 7/8/2021 - Seeing messages in custom folders with user +41.  Closing.

![2021-07-08_15-55-26.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/80c24eaa-5373-4780-966a-97b2541cb808)
