### ISSUE TITLE
From cannot be restarted after submit. in prod 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#24404]
Observed behavior: Once a form is submitted and a Veteran choses to restart the form it cannot be submitted. This has been observed in production only - in lower environments the form can be restarted. 

Desired Behavior: A Veteran should be able to submit a new FSR if they chose restart per requirements - DMC has a method to sort based on submit date to work with the latest submitted form.

**Comment by craigwheeler** [comment]
unable to reproduce

**Comment by LinnJS** [comment]
This is still in limbo due to not being able to reproduce...

**Comment by LinnJS** [comment]
Can re-open if this issue comes back up should be handled on the FE with a recent update just cannot reproduce with mock data on a localhost/dev environment.
