### ISSUE TITLE
Message from a different sender

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va.gov-team#24406]
### User Story
As a user I want to know if a message is coming from a different sender then I initially sent to.

### Current Experience
<img src="https://images.zenhubusercontent.com/602e6bbb345265c801d416d8/026026c1-d7c9-44de-b62d-26480681953c" width="250" alt="Screenshot of reply alert">

### Copy
**This message may not be from the person you initially contacted**
It may have been reassigned in order to efficiently address your question.

**Comment by drjecker** [comment]
@narin Just found this alert in some screenshots I have of the MHV web experience. Can you help me figure out what the API error is?

**Comment by narin** [comment]
@drjecker I logged into MHV staging using our +41 and +261 users and am pretty sure that this message is always displayed, and not due to any sort of API error.
