### ISSUE TITLE
faraday_middleware prod gem major upgrade

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#24418]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the faraday_middlware gem (production group) to it's latest major version 

---
## Tasks
- [ ] CI make target passing locally 
- [ ] Reviewed gem change log updates

**Comment by ericboehs** [comment]
The great @rileyanderson says we'll need to update faraday and faraday_middleware at the same time. I trust him to the fullest with this evaluation.
