### ISSUE TITLE
[Bug] Questionnaire - Visit Intro - Content/styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#24417]
## What happened?
On Staging **[Your health questionnaires](https://staging.va.gov/health-care/health-questionnaires/questionnaires/)** page, the following content/styling anomalies were observed:
- **Questionnaire-list** page:
  - [**IE11 only**] **Questionnaire cards**: **CTA-links** icon was underlined and label-text wrapped to 2nd line.
  - **Need help?** section: **Contact your VA provider** link is broken (navigated to empty page).
- [**IE11 only**] **Intro** page: **CTA** icon was underlined

## Specs:
- Device: [device-agnostic unless otherwise noted above]
- Browser: [browser-agnostic unless otherwise noted above]
- Test User _(if applicable)_: `va.api.user+idme.101@gmail.com` (Sheba)

## Steps to Reproduce
- URL: https://staging.va.gov/health-care/health-questionnaires/questionnaires/
- Test User _(if applicable)_: `va.api.user+idme.101@gmail.com` (Sheba)
- Observe each anomaly listed above in **What happened?**.

### Screenshots
**[IE11] Questionnaire-list page questionnaire-card CTAs**:
![q-vi-bug-ie11-answer-qstns-button](https://user-images.githubusercontent.com/587583/117717264-72d60380-b18f-11eb-843c-d9771fb9bab0.png)

**[IE11] Intro page CTA**:
![q-vi-bug-ie11-answer-qstns-button2](https://user-images.githubusercontent.com/587583/117720850-04e00b00-b194-11eb-9e99-17a31808ac0a.png)

### Video capture
**Contact your VA provider broken-link**:
https://user-images.githubusercontent.com/587583/117718248-b4b37980-b190-11eb-94a9-5645e487b115.mp4

## Desired content/styling
 - **Questionnaire-list** page:
    - [x] [**IE 11**] **Questionnaire cards**: **CTA-link** icon should not be underlined and label-text should remain on same line as icon.
    - [x] **Need help?** section: **Contact your VA provider** link should navigate successfully to destination page.
- [x] [**IE11**] **Intro** page: **CTA** icon should not be underlined

## Acceptance Criteria
- [See **Desired content/styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

**Comment by mdewey** [comment]
<img width="982" alt="Screen Shot 2021-05-21 at 4 16 42 PM" src="https://user-images.githubusercontent.com/1793923/119193670-f1fcee80-ba4f-11eb-9477-1614c0a365aa.png">


@tlei123  This has been fixed and is in staging.

**Comment by tlei123** [comment]
@mdewey , yep, fix validated on Staging.  Thanks much!

![image](https://user-images.githubusercontent.com/587583/119584766-26d5b200-bd7e-11eb-980f-7d9956e4e330.png)

![image](https://user-images.githubusercontent.com/587583/119584879-6b614d80-bd7e-11eb-9515-0d529b3ba1fe.png)

cc @leahkeeler [couldn't find Corey Parker]
