### ISSUE TITLE
[COGNITION]: Text Appointments - Can we review the update message for language and intent?

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#2442]
## Description

The update message has me a bit confused. As I understand it, we want to convey to the user we are updating their preference for text messages about upcoming appointments. I'd like to take a look at this for visual design and content accuracy. Adding Peggy and Emily for visibility.

Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor, Peggy, Emily_

## Acceptance Criteria

* As a user, I want to read a clear message and understand that my text message preferences are being updated.

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2019-10-14 at 3 54 33 PM](https://user-images.githubusercontent.com/934879/66782504-70b89f80-ee9b-11e9-909c-95d9a4b79aad.png)

**Comment by lkoenigsberg** [comment]
@peggygannon , how would you feel about updating this text so that it just adds text preferences?  So something like "...your new mobile phone number and text preference..."

**Comment by peggygannon** [comment]
Hi, @lkoenigsberg thank you. I had provide an edit to this text in this issue, per (https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2332)

And yes, we can add "text alert preference" to the message. So the update would now read: 

We’re saving your mobile phone number and text alert preference. We’ll show them here once they've been updated.

**Comment by lkoenigsberg** [comment]
@elwoodva , please go ahead and make the text change as we've agreed above.

**Comment by elwoodva** [comment]
I have made the change and I have started a draft pull request started for this issue.

**Comment by 1Copenut** [comment]
@elwoodva Would you mind linking the PR and this issue when you've got a few minutes?

**Comment by elwoodva** [comment]
@1Copenut I think I already did.  Didn't I?

**Comment by 1Copenut** [comment]
@elwoodva Ah, yes I see it now. I had to log into Zenhub, but it's linked now. Much appreciated.
