### ISSUE TITLE
faraday prod gem major upgrade

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#24420]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the faraday gem (production group) to it's latest major version 

---
## Tasks
- [ ] CI make target passing locally 
- [ ] Reviewed gem change log updates

**Comment by ericboehs** [comment]
This is blocking our upgrade to sentry-raven as sentry-raven needs > 1.0 and we're on 0.17.4. faraday can't be updated though, until breakers and betamocks are updated.

**Comment by rileyanderson** [comment]
Going through and fixing the ~200 spec failures due to the upgrade
