### ISSUE TITLE
puma prod gem major upgrade

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#24426]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the puma gem (production group) to it's latest major version 

---
## Tasks
- [ ] CI make target passing locally 
- [x] Reviewed gem change log updates

**Comment by cbtkc** [comment]
`WEB_CONCURRENCY` environment variable has been added to the configuration vets-api server in the DevOps repo. [See here](https://github.com/department-of-veterans-affairs/devops/commit/2da74ea0bedc94912436e34376d3f4e78a5da7df)

**Comment by cbtkc** [comment]
PR should be ready to merge. Put a message in BE channel to see if anyone else wants to take a look prior to merge.
