### ISSUE TITLE
sentry-raven prod gem major upgrade

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#24430]
## Issue Description
As a more cautious approach to update our production gems, the upgrade path was split into three sub-steps. It was discussed to break out each gem into a ticket individually, as the risk level increases. This ticket details the upgrade of the sentry-raven gem (production group) to it's latest major version 

---
## Tasks
- [ ] CI make target passing locally 
- [ ] Reviewed gem change log updates

**Comment by ericboehs** [comment]
@LindseySaari I've extracted the migration to sentry-ruby to https://github.com/department-of-veterans-affairs/va.gov-team/issues/22273.

For the scope of this ticket, let's just get on the latest sentry-raven (3.1.2 as of now).
