### ISSUE TITLE
[IN PROGESS] Staging Review Decision Tools - Find a VA Form Search Term Transformation Iteration 2

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24436]
## Steps to complete Staging Review: 

- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [ ] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @vsp-product-support-members. 
- [ ] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [ ] VFS: At least 4 days before scheduled meeting, you must complete list of artifacts below
- [x] VFS: Verify that access information has been provided for the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.
- [ ] VSP: Create feedback tickets and link to the Staging Review ticket (if no feedback, please comment stating that). 
- [ ] VFS: Respond to VSP feedback tickets.
- [ ] VFS: Update this ticket with the product’s launch date after it has gone live.
- [ ] VSP: Update [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when the review is complete.

## Artifacts
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/README.md)
- Link to the tool or feature in staging. Do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository.   **https://staging.va.gov/find-forms/**
-  Staging test-user information (if applicable)  N/A
-  Link to content brief (if applicable) N/A
-  Link to or specify the artifact that represents this initiative's content source of truth (for example, mockup, prototype, Github, Word outline, or staging or preview link)    **https://staging.va.gov/find-forms/**
- Link to [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md) with the "Planning" sections completed (in each section: Phase I, Phase II, Go Live)
- Link to your product test cases/test plan in TestRail with test execution logs ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) _for QA practice area review_  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/mvp/design/find-va-form-use-cases.md
- Link to your [Coverage for References](https://dsvavsp.testrail.io/index.php?/reports/view/12) and [Summary(Defects)](https://dsvavsp.testrail.io/index.php?/reports/view/14) reports in TestRail _for QA practice area review_
- Link to verification that accessibility checks are complete:
  - (preferred) Link to your [TestRail VSP accessibility test plan template](https://dsvavsp.testrail.io/index.php?/suites/view/14&group_by=cases:section_id&group_order=asc).
OR
  - Link to a doc in your product folder that indicates all required checks from the accessibility [staging review prep](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/staging-review-processes.md) doc are complete.
- List of known issues (with links to tickets when applicable)

## Meeting attendees from requesting team
- Product Manager (required): Marci McGuire
- DEPO Product lead (recommended): John Hashimoto
- DEPO Design lead (required): Ryan Thurlwell
- Anyone else from your team who significantly contributed to the artifacts provided (required): Zach Morel
- Content, IA, accessibility, and QA specialists (if applicable): name(s): Angela Fowler, Josh Kim

## Scheduling
What is your preferred time slot per the [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York)? **TBD**

Please note:
- All times are shown in ET. 
- Available time slots are indicated with [CALENDAR BLOCK]. 
- When you reserve a time slot, the reserved meeting will show up alongside the [CALENDAR BLOCK]. 
- Please select a time slot at least 4 business days from request date. 

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/README.md) on Github for more information about the Collaboration Cycle.

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman we hit some unexpected proxy issues that delayed us by several days, so I will have to reschedule once we have everything in order.  I will update the ticket and Slack you once we have a new date. Thank you!

**Comment by shiragoodman** [comment]
Thanks @MarciMcGuireGCIO . I'll keep the appointment but update it to state cancelled. We can move it to the new date/time when I hear back from you. cc: @mnorthuis (please follow this and move appointment to new date/time when Marci responds. thanks!)

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @shiragoodman !

**Comment by shiragoodman** [comment]
hey @MarciMcGuireGCIO - following up on this. Do you have a new date/time in mind for staging review?

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman, thank you for following up. Not yet; the engineer working on the Forms API was asked to rewrite some regex, and we hope that will be on Staging today so I can reschedule.

**Comment by shiragoodman** [comment]
Meeting has been moved to Tuesday June 1 at 11:00am ET

**Comment by MarciMcGuireGCIO** [comment]
@shiragoodman I'm really sorry, but we need to reschedule.  We've got time-sensitive work that needs to go live by this Thu, and the scope on this one changed significantly late yesterday.  I will update our Collab Cycle ticket tomorrow and will request a Staging review when we are prepared.  Thank you!

**Comment by shiragoodman** [comment]
no problem @MarciMcGuireGCIO . I'll update the appointment to "Cancelled" and we can just move it when you have a new date.

Thanks for the heads up!

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @shiragoodman !

**Comment by MarciMcGuireGCIO** [comment]
Closing this; will open a new one when we are ready.
