### ISSUE TITLE
[FE] My VA: Investigate why we are showing prescription and messages link to people who shouldn't be seeing them

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#24447]
## Background

On 5.6.21, we did a usability session for our preferred facilities work with a team member who happens to also be a veteran. This session revealed that the following can be true:

- A veteran is not formally part of the VA health care system and is not currently a patient.
- BUT, that veteran has received some sort of care in the past, and is therefore registered at a VA facility.
- Because this person is registered at at least one VA facility, their `GET user` object comes back that they are a VA patient.
- And because of that, we show them the Health care section of the My VA dashboard even though they aren't actually receiving care at the VA. **This includes the prescriptions and messages links, which they should not be seeing if they do not manage either of these things through the VA and neither `rx` or `messaging` shows up in their list of available services.**

## Tasks

- [ ] Investigate why this person was seeing prescriptions and messages links even though he doesn't manage them through the VA.
- [ ] Fix this issue, if possible.

**Comment by erikphansen** [comment]
@ajakabcin I'm going to work on this ASAP since it should be resolved before we test with anyone.

**Comment by erikphansen** [comment]
I can already see that we just never gate showing the Rx or Messaging CTAs at all. Adding the gating logic should be easy. Most of the work will be making sure there is proper test coverage for the fix.

**Comment by erikphansen** [comment]
merged a fix. closing this.
