### ISSUE TITLE
ATO Documentation (if needed)

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#2444]
Determine if ATO changes are required as part of the VAMF integration. Either on the VA.gov or VAMF side.

**Comment by markgreenburg** [comment]
@saneshark regardless, I think we'll want to schedule & complete a formal pre-launch ATO review on the va.gov side via this process: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ato-reviews.md

That might be good acceptance criteria for this ticket?
