### ISSUE TITLE
Access for Dat Tran (AWS)

### ISSUE THREAD

**Issue by dat-gcio** [department-of-veterans-affairs/va.gov-team#24462]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Dat Tran
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Name of Team: Caregivers
   > Role: Front End Engineer
   > Company: GovernmentCIO

- [Grant AWS Console access?] Yes
I need AWS access to see production error logs on cloudwatch. Our team only has two developers so I need AWS access for when my Backend developer (@kevinmirc) is out of office.

**Comment by omgitsbillryan** [comment]
AWS Access
User: Dat Tran
COR: Mary O'Toole
Approval Needed: @Jeff-Hayter

**Comment by omgitsbillryan** [comment]
Email sent, still waiting on approval.

![image](https://user-images.githubusercontent.com/3077884/119195781-2b832900-ba53-11eb-8206-b3727c23469c.png)

**Comment by mlighdc** [comment]
Hi @Jeff-Hayter, would you be able to approve? Dat Tran just joined the 10-10 (Caregiver / HCA) team as a front end engineer. If you need anything let me know. Thank you!

**Comment by Jeff-Hayter** [comment]
@omgitsbillryan Approved for AWS, cc @jhouse-solvd

**Comment by mlighdc** [comment]
Thanks @Jeff-Hayter!

**Comment by omgitsbillryan** [comment]
Access given.
