### ISSUE TITLE
Language Assistance and Resource Pages w/ Footer Link | VSA-QA Test Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#24463]
\[**Product Managers**: Open this ticket **at least 2 Sprints** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Add yourself to Assignees
- Fill-out sections below.]

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- Product/Feature: 
Addition of a highly visible navigational element to the VA homepage footer which links to newly created translated resource pages (Spanish, Tagalog and Other languages). The new resource pages will provide quick access to existing translated content and information for in-language support assistance and resources.

- Product/Feature Epic:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21079

- Product/Feature Copy deck(s): 

- Product/Feature Design prototypes: \[provide links, or type "In Design prototypes"]
Design prototypes:
Footer:  https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23305

## Product-team SMEs

**\[if different from (or more specific than) [VSA Master Org Chart](https://docs.google.com/drawings/d/1_OmxooPQXRwUjb08DoaMoEvw1-2Gq9e_wYLunMzEsxE/edit?ts=5daa1002 )]**

(Leave blank to implicitly refer to VSA Master Org Chart (linked above)
Design/Research: Ryan Thurwell
Content/IA: Mikki N.
Front-end: Fareez Ahmed
Back-end: N/A
QA: Tze-chiu Lei

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

IMPORTANT for authenticated products (requiring sign-in): Staging test-accounts must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

Link to **Use Cases doc**: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/use-cases-language-assistance-pages.md

## How to configure this issue

- [ ] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Product references provided by Product Team.
- [ ] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod enviornment].
- [ ] Test Reports generated.  These should be provided to VSP at least 4 workdays before [Staging Review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review).

**Comment by SKasimow** [comment]
Hi @DanielleThierryUSDSVA - can you take a look at my Use Cases before I assign to QA? I can only think of 4 but want to see if there are any I overlooked:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/use-cases-language-assistance-pages.md

Thanks!

Sharon

**Comment by tlei123** [comment]
> @tlei123 Hi Tze! I am assigning this to you although I don't have the translated URLs yet.
> I thought you could at least put in in your queue and check my use cases :)

@skasimow Yes, I'll be looking at your [Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/use-cases-language-assistance-pages.md) & starting my QA Test Cases this afternoon.  Your Test Plan tic happens to be the only one open right now, so once your URLs are in-place, please tag me here [or ping me on Slack] -- I should then be able to turn-around my test-runs in 2 days max.

**Comment by SKasimow** [comment]
@tlei123 awesome - thanks!

@DanielleThierryUSDSVA

**Comment by SKasimow** [comment]
@tlei123 Hi - here are new URLs; hoping to have them in staging by tomorrow (Thursday):
va.gov/asistencia-y-recursos-en-espanol
va.gov/tagalog-wika-mapagkukunan-at-tulong


This one is already in prod: https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/

**Comment by tlei123** [comment]
@pjhill @ddzz , where would you like last-minute notice of URL changes?  Test Plan ticket here, or Staging Review ticket, or somewhere else? The URLs in my test-cases might go out-of-date before your reviews...

Right now, the content pages are currently only on Prod and the footer Language-support section only on Staging.  I'm sure they'll all be on both eventually; I just not sure when that'll be.

**Comment by tlei123** [comment]
> Right now, the content pages are only on Prod and the footer Language-support section only on Staging. I'm sure they'll all be on both environments eventually; I just not sure when that'll be.

NVM, @pjhill @ddzz .  the content-pages are all on Staging now.  They temporarily "sneaked out" on Prod, and the Team just fixed them via feature-flag.

**Comment by tlei123** [comment]
@SKasimow , all QA test-runs now completed.

1 defect logged: #25395 

QA-artifacts for Staging Review:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/1868)
- [Test Case](https://dsvavsp.testrail.io/index.php?/suites/view/183&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1101)
- [Coverage for References (Cases) report](https://dsvavsp.testrail.io/index.php?/reports/view/239)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/240)
