### ISSUE TITLE
General Analytics Request for Search & Discovery - Custom Dimension for search-typeahead-used

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24482]
## Description
Who is this request for?

As a result of the exploration in #23948 Search & Discovery would like a custom dimension added to Google Analytics for search-typeahead-used

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

Search & Discovery - Typeahead
    
- What type of analytics support are you looking for?
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
n/a

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
_Please link your report if you are seeking verification of metrics._

## Additional Comments
@srsuddath does not have the ability to add custom dimensions in GA and we wanted to ask that one be created for search-typeahead-used 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@denisecoveyduc -

Unless @JasonTheBearded has any objections, I think I'm going to append this to the end of the Event Action vs custom dimension.

![image](https://user-images.githubusercontent.com/62304138/118204605-99fd3100-b42c-11eb-8051-012dbd164513.png)

**Comment by JasonTheBearded** [comment]
@bsmartin-ep no objections, we'll definitely need to update the query powering the type ahead dashboard after this change though.

**Comment by denisecoveyduc** [comment]
Thanks! @bsmartin-ep  & @JasonTheBearded  Let us know once the dashboard has been updated.. can't wait ;)

**Comment by srsuddath** [comment]
my only request would be to maybe extend it just a big for easy Querying - like TA-Used: true
that way if there is another true somewhere in the string we don't get a false hit

**Comment by denisecoveyduc** [comment]
@bsmartin-ep Thanks for the touchpoint today. Ass discussed please go ahead and add this custom dimension. cc: @srsuddath

**Comment by bsmartin-ep** [comment]
## QA

Description|dataLayer|tag|pass
----|----|-----|----
Search results click without type-ahead|![image](https://user-images.githubusercontent.com/62304138/119514411-ff152880-bd42-11eb-9024-e49170e5a3aa.png)|**![image](https://user-images.githubusercontent.com/62304138/119514449-0805fa00-bd43-11eb-8fcf-0fb90b3817cc.png)|**PASS**
Search results click WITH type-ahead|![image](https://user-images.githubusercontent.com/62304138/119514556-1eac5100-bd43-11eb-92c4-1535c589def0.png)|**![image](https://user-images.githubusercontent.com/62304138/119514602-2966e600-bd43-11eb-9b73-3391d12d88a9.png)|**PASS**

GTM changes has been published @denisecoveyduc.  We should start seeing values in custom dimension "Search Type Ahead Used" today.

**Comment by joanneesteban** [comment]
@denisecoveyduc is it okay to close this ticket out?

**Comment by denisecoveyduc** [comment]
Hey @joanneesteban Yes, meant to do that earlier.. thanks for catching it!
