### ISSUE TITLE
Pagination: canceling an appointment loads in all of the previous records

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24497]
## What happened?
After canceling an appointment that is listed on Page 2 or higher, the Upcoming Apointments page loads in all of the appointments that preceded it. 

For example, if Appointment #30 in the list is successfully canceled, returning to the Upcoming Appointments page will display appointments 1-30, rather than 21-30. 

## Specs:
- Device: iPhone 11
- Test user: judy.m

## Steps to Reproduce

1. Navigate to the Upcoming Appointments page
2. From the pagination CC, navigate to page 3 (or any page beyond the first page)
3. Take note of the 10 appointments that display on that page, including the dates for the 1st and 10th appointment on the page. _The attached video includes appointments between July 8th - August 13th_
4. Select a VA Appointment and go to the details page
5. Cancel that appointment
6. When the "Your appointment has been canceled" success message appears, hit the Back button
7. Notice how the Upcoming Appointments page has loaded in all of the appointments from Page 1, 2, and 3

## Desired behavior
Pagination is maintained so that only 10 records display on each page. 

In Step 7 of the above example, only the 10 records from Page 3 should have displayed after hitting Back. 

## Acceptance Criteria
See desired behavior above.

## Bug Severity
- 4 - Low

## Linked to Story
#21331, AC 6

## Screen shot(s) and additional information
[Screen recording of described behavior](https://drive.google.com/file/d/1hzmwUheLcail0WHySbACC3hua28UyZGW/view?usp=sharing)

**Comment by digitalken** [comment]
PASS 6/17/2021 - Looks good and goes back to max of 10 listings.  Closing.
