### ISSUE TITLE
Establish Sentry tagging standards

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#245]
## Background
Sentry allows for `tagging` events (e.g. exceptions, messages).
These tags are useful to 'generate breakdowns charts and search filters'  ([Sentry docs](https://docs.sentry.io/enriching-error-data/context/)).

## Problem
We do not have any established, documented standards for tagging.
If engineers are not following a standard it could result in increased difficulty in efficiently and accurately triaging issues.

Hypothetical example: 
Two developers working on PreNeed Burial features.
One developer tags a bit of code like so:
`Raven.tags_context(feature: 'preneed')`

The second developer tags his bit of code like so:
`Raven.tags_context(product: 'preneed_burial')`

You can see in this example we have incongruous keys and values in our tags.

## Current state of tags in `vets-api`
Every controller request (i.e. every endpoint request) gets tagged with
```
{
    controller_name: controller_name,
    sign_in_method: sign_in_method_for_tag
}
```
That is great.  Every endpoint request is tagged in a consistent manner. 
What other calls should be reliably tagged?  Perhaps every call to an external service?  

I also see:
- `validation: "#{feature_name}"` when validation fails in some controllers and a Faraday middleware
- Sidekiq initializer is configured to autotag `job: job['class']`.  However, I also see `job: "FacilityLocationDownloadJob:#{type}"` and `job: 'hca_submission'` in their respective Sidekiq jobs. Are those redundant?   
- `EVSS::Service` adds `external_service: self.class.to_s.underscore`
- Service specific tags: 
  - `ihub: 'appointments'` and `ihub: 'appointments_error_occurred'` in `IHub::Appointments::Service`
  - `vet360: conditional ? 'failed_vet360_id_initializations' : 'general_client_error'` in `Vet360::Service`
  - `search: 'general_search_query_error'` in `Search::Service` upon an error
- Some helper classes (search repo for `TagSentry`) that tag with the appropriate feature (e.g. `feature: 'pension_burial'` 
- A helper clsss to tag Rainbows team (i.e. `team: 'rainbows'`).  This is the only team specific tag in the codebase.  With team re-organization possible and transient contractors hopping on and off the project, perhaps tagging by team is not a good long term approach. Rainbows team itself doesn't exist any more.
- login info (e.g. sign in service and account type, etc) in `lib/saml/user`
- `profile: 'pciu_profile'` in `personal_informations_controller`
- `session_token: self.class.obscure_token(@token)` in `models/session`
- `sign_in_method` in `app/services/mhv_account_type_service`
- `account: 'cannot_create_unique_account_record'` in `concerns/accountable`
- `backend_service: :emis` in `models/form_profile`.  Should this be `external_service` for consistency (or vice versa)?

## What to do from here
We need to establish standards for Sentry tags and their values as they pertain to va.gov products, features and services.

### tags (keys):
What are our standard keys and what do they represent?
From examples above I see these as being used across features/services:
- `feature` 
- `external_service` (and `backend_service`)
- `job`
- `validation`
- `controller_name`

What other candidates would give us the most benefit?

### values
We need to standardize on values.
When supplying the name of a feature or service, how is it formatted? 
How do we enforce consistency?

## Then
Make sure these standards are documented in in our onboarding and/or best practices documentation.

## Acceptance Criteria
- [ ] Sentry tagging standards and best practices to facilitate efficient filtering, triaging and reporting are established and documented.
- [ ] Engineering documentation is updated

**Comment by jholton** [comment]
Documentation aspect could pertain to #191 and #192

**Comment by jholton** [comment]
Related to #219

**Comment by jholton** [comment]
cc @annaswims

**Comment by annaswims** [comment]
we can get a complete list of tags for each project from http://sentry.vetsgov-internal/settings/vets-gov/projects/platform-api-production/tags/ and can get a relatively good idea of values from the search autocomplete.  

I also really like the issue ownership rules  http://sentry.vetsgov-internal/settings/vets-gov/projects/platform-api-production/ownership/ as a potential strategy for triage.  It's nice that it won't involve code changes.

**Comment by cvalarida** [comment]
I can give this a little front end flavor: We've got [this bit o' code](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/startup/index.js#L40) which automagically gives the events we log to Sentry a `source` tag corresponding to the React app the user is in when the event triggered. Sounds similar to that...middleware(?) that tags requests in the API.

I think ownership rules are the way to go for triaging Sentry issues. The Triage team is currently trying to get a service -> team map to make this dream a reality.

Personally, I'm not a fan of magic strings, so having enums for features, external services, jobs, etc. would be ideal to me.

**Comment by kfrz** [comment]
PR to add documentation of current standards is [here](https://github.com/department-of-veterans-affairs/va.gov-team/pull/837).

After exploring our current state, assessing notes from this thread, and attempting some refactorization I've managed to come up with the following list of todo's:

 ## Action Items:
- [x] Remove tag_rainbows as it is deprecated
- [ ] Extract `external_service` tag to base class
- [ ] Change `backend_service: :emis` to external service in `models/form_profile`
- [ ] Remove redundant job tags in `hca_submission` and `FacilityLocationDownloadJob`
- [ ] Investigate duplicate login tags:  
    - `sign_in_service_method`: captures which sign in method is used if user is signed in, i.e. `idme`, `dslogon` etc
        - can be seen [here](http://sentry.vfs.va.gov/vets-gov/platform-api-production/?query=is%3Aunresolved+sign_in_service_name%3A) in sentry found in lib/saml/user
    - `sign_in_method`: found in SentryTaggable and ApplicationController
- [ ] Remove service specific tags and use `external_service: service.class_name` as a standard, allows for filtering by service.
    - [ ] these can probably be moved to a transaction or feature tag
        - [ ] ihub: 'appointments' and ihub: 'appointments_error_occurred' in IHub::Appointments::Service
        - [ ] vet360: conditional ? 'failed_vet360_id_initializations' : 'general_client_error' in Vet360::Service
        - [ ] search: 'general_search_query_error' in Search::Service upon an error
        - [ ] account: 'cannot_create_unique_account_record'
- [ ] Set assignment rules in Sentry via the codepaths or URLs based on VSA teams
