### ISSUE TITLE
CT Redesign: Comparison View - Improve ability to distinguish differences - Accessible solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24507]
Solution for distinguishing differences addresses 508 accessibility 	

* Identify mechanisms to incorporate accessible solutions into "Highlight differences solution" 
* Share with accessibility SME to validat

**Comment by amyknox** [comment]
DEPO Office Hours- 
Is color change significant enough? Maybe also bold table row info. 
Or row-level icon. *= difference.  

Conditional screenreader-only text applied to row that toggles when highlight differences is checked. 

Consider "Hide / show similarities"  - that would work well for assistive tech. But maybe not, 
Mikki says "Hide similarities" was jarring to users. 

No concerns about sticky header with highlight differences & Remove links.  But may want a shortcut / skiplinks. Revisit in code - focus-only sticky header. 

Still promote a "Back to search results" action link...maybe test without this.  Consider Search results breadcrumb. (not sure how this'd be technically feasible). 

Mobile Sticky Header... Button to jump to next column would be part of sticky header.

**Comment by amyknox** [comment]
@watersemma - I believe this is complete.  Could you confirm?
