### ISSUE TITLE
508-defect-1 ❗ Launchblocker [COGNITION]: Prevent memory challenges when signing by reminding users of their original inputs

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#24501]
# [508-defect-1](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As someone with a cognitive or reading disability, I want to be reminded of who I wrote down as the primary caretaker and first and second secondary caretakers and how I spelled their names.

## Details

The current method of requiring a signature may present a memory challenge to folks with cognitive or reading disabilities. Two scenarios may occur:

1. If one of the names were misspelled originally, and the individual spells the name correctly when signing, they will receive an error but no explanation as to why the name is incorrect
2. Someone may forget who they wrote down for each caretaker and may become frustrated that they must return backwards to dig it up or find it within the review page.

## Acceptance Criteria

- [ ] Provide the names that must be reentered to sign for each caretaker/representative signature
- [ ] If possible, provide more specific error messaging OR allow for mistakes

## Steps to Recreate

Misspell any of the signature fields

## Proposed Solution

The solution will depend on the constraints of the feature. Ideally it would be best to provide the individual the names of all the caretakers written down earlier.

## Screenshots or Trace Logs

<img width="1290" alt="Screen Shot 2021-05-10 at 10 51 32 PM" src="https://user-images.githubusercontent.com/14154792/117755760-d3def500-b1ea-11eb-9108-a3e54c0202c2.png">

**Comment by hdjustice** [comment]
@joshkimux - This is a super old ticket for the 10-10CG form.  We want to be sure any accessibility tickets are addressed in a timely manner, and want to clear out the backlog of items as well.  I think this one may be addressed.

In staging environment, I ran a test and misspelled a primary caregiver name.  An error message appears identifying the name that is expected to be 'signed'.  Is this what you mean?

**Before entering name**
![image](https://user-images.githubusercontent.com/92328831/173423453-a5b81007-f759-49b2-b9cb-9f6c127779d0.png)

**After entering mis-spelled name**
![image](https://user-images.githubusercontent.com/92328831/173423498-d18c76de-1d9f-4474-8346-9d7916819a04.png)
