### ISSUE TITLE
CT Redesign: Comparison View - Prototype with all comparison points

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24508]
Prototype is updated with all data points identified to be compared	

* Identify all data points to be compared 
* Update prototype to include all data points 
* Review with UX team & refine

**Comment by amyknox** [comment]
Need to reconcile data points with Compare mural and make sure we have what's anticipated in the "final" compare prototype.

**Comment by amyknox** [comment]
@watersemma - a couple notes from the 5/13 Education Service review

- [ ] Deactivate Compare button in compare tray when there's only 1 school in the tray
- [ ] Deactivate Compare checkbox when 3 schools are in the compare tray
- [ ] Drop in a different symbol for "highlight differences" that doesn't look like a control, maybe just an asterisk*

**Comment by amyknox** [comment]
Comparison points in the works: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1617710116724/06fd7c751f02d73b05dc3065221dca2cfa5a47e7?wid=12-1620988627060

**Comment by amyknox** [comment]
Updated Comparison / Profile page IA https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1617710116724/06fd7c751f02d73b05dc3065221dca2cfa5a47e7?wid=0-1621458299563
