### ISSUE TITLE
508-defect-2 [SEMANTIC MARKUP]: <Article> should not be used to contain signatures as it is not independent, self-contained content

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#24503]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader user, I expect `articles` I find in my elements list or rotor to be content that is independent and self-contained like a blog post.

## Details

> The HTML `article` element represents a self-contained composition in a document, page, application, or site, which is intended to be independently distributable or reusable (e.g., in syndication). Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.
[From MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article)

Using the `article` element to contain the signatures will suggest to screen reader users scanning through their elements list or rotor that there are independent, self-contained sections on the page. This isn't the case as the signatures are directly related to the other elements on the review page.

Furthermore, since none of the `articles` are uniquely labelled, they will simply appear as a list of generic articles in a rotor or elements list.

## Acceptance Criteria

- [ ] The `article` element is not used for the signature componenet

## Steps to Recreate

On a Mac in Safari with VoiceOver, open up the rotor `ctrl` + `opt` + `u`. Use the right/left arrow keys to navigate to the `article` list. Confirm there are 4 generic articles.

https://user-images.githubusercontent.com/14154792/117758072-4ce04b80-b1ef-11eb-8726-d7b4e0e29242.mov

## Proposed Solution 

It may be more semantically appropriate to use `role="group"` along with `aria-labelledby` pointing to its unique heading. I recommend for the developer to reach out to the accessibility specialists to solve this together.

## WCAG or Vendor Guidance (optional)
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_group_role
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

**Comment by longmd** [comment]
@joshkimux , this has been updated. Can you validate that we are good to go with this?

**Comment by joshkimux** [comment]
Hi @longmd ! Once again-- I'm a little overwhelmed at the moment bandwidth wise, but this is a great fix, and we'll find someone to validate soon. Tagging in @RLHecht for awareness ❤️

**Comment by SarahKay8** [comment]
@longmd validated!

**Comment by longmd** [comment]
Thanks @SarahKay8 !!
