### ISSUE TITLE
[Phase 2] Use Service Connected Disability Rating to Fast Track Completion of 10-10EZ

### ISSUE THREAD

**Issue by mlighdc** [department-of-veterans-affairs/va.gov-team#24506]
## Story

As a veteran if my service connected disability rating is equal or greater then 50% I should be able to skip sections of the 10-10EZ.

The disability rating is available through the GET /v0/disability_compensation_form/rating_info API

## Acceptance Criteria
- [x] Unauthenticated-self-report design
- [x] Authenticated-self-report design
- [x] Reviewed by designer in RI

## Flow
- [Authenticated clickable prototype](https://preview.uxpin.com/acda277e33e9629a7ab817f6c93c251b4a60ac56#/pages/141488399/simulate/no-panels?mode=i)
- [Unauthenticated clickable prototype](https://preview.uxpin.com/2a1ce93f62d447e101cfce3c803d20941fba7203#/pages/141808810/simulate/no-panels?mode=i)

**Flow charts**
- Authenticated-immediate alert ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/EL9RYvq)) 
- Authenticated-self-report ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/jgDjqJb))
- Unauthenticated-self-report ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dlvDq7j))
- Full application flow/ less than 50% disability rating ([chart](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/zxZzO2l))

## Design
- [Authenticated first alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/px07lr/a/1Kz2Pak/r/2kvkn5)
- Auth & Unauth [accordion alert ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/PGeGRKd)on every page at top
- Unauth [confirmation page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/YGLwZQO)
- Unauth [Alert of reselection](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/QbGpljm) (upon back) + Experimental design [link](https://design.va.gov/experimental-design/input-message)
- Unauth [Short form alert](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/bgWPqbz)
- Auth & Unauth [short form review page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/rbdvz8d)

**Comment by SKasimow** [comment]
Here is some info re: getting disability rating:https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-rated-disabilities/evss-tcdr/README.md

**Comment by SKasimow** [comment]
will separate into 2 tickets - one for disability rating and one for combat theater.
