### ISSUE TITLE
Remove the "Records" side nav from the "Discharge upgrade" page

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2451]
## What happened?

The "Records" side nav shows on the "Discharge upgrade" page even though it shouldn't. "Discharge upgrade" does not live under the "Records" root — it lives outside of the "Records" hub — so we should not be showing the "Records" side nav.

<img width="1026" alt="Discharge upgrade_remove side nav" src="https://user-images.githubusercontent.com/34068740/66844546-75816000-ef3c-11e9-8bb4-c1f90650cb18.png">

## Specs:
- Device: Macbook
- Browser: (e.g. Firefox, IE 11) Most recent version of Chrome
- Test User _(if applicable)_: Logged out/no test user

## Steps to Reproduce

URL: https://www.va.gov/discharge-upgrade-instructions

1. Go to this URL.
2. You'll see the side nav even though it's not supposed to be there.

## Desired behavior

Please remove the "Records" side nav on this page. This has been reviewed with @mnorthuis and confirmed as the desired behavior.

## Acceptance Criteria

"Records" side nav no longer shows on this page.

**Comment by Karak888** [comment]
Thanks @Samara-Strauss will have someone look into this today, and will follow-up with you.  

:cc @jenniferlee-dsva

**Comment by Karak888** [comment]
@Samara-Strauss I spoke to @RLHecht and she said she will take a look this afternoon.  thanks both!

**Comment by RLHecht** [comment]
I am having trouble finding where this page lies to update it. It's not in Drupal yet (no date at the bottom of the page) and I can't locate it in the root pages or in Records in Github.  @ncksllvn or @kelsonic would you guys know where I could find this? cc @jenniferlee-dsva

**Comment by ncksllvn** [comment]
Hm, I thought that the Discharge Upgrade application was a root-level page but still considered part of the Records hub. That's how the MegaMenu represents it -

![image](https://user-images.githubusercontent.com/1915775/66863328-c30fc400-ef60-11e9-89c3-e7a8d942d88b.png)

That said, I'd have to figure out whether this sidebar is from Drupal or vagov-content to remove it. Should I do that?

**Comment by Samara-Strauss** [comment]
> That said, I'd have to figure out whether this sidebar is from Drupal or vagov-content to remove it. Should I do that?

Yes please!

> Hm, I thought that the Discharge Upgrade application was a root-level page but still considered part of the Records hub. That's how the MegaMenu represents it -

@ncksllvn yes, you are correct that the Discharge Upgrade application IS a root-level page, and while we do link to it from the Records hub, @mnorthuis said this page shouldn't have the side nav because it's not a *child* of the Records hub. 

Let me know if you have any other questions!

**Comment by Karak888** [comment]
@RLHecht is this something you can do or is left nav in Drupal that needs to be done?  Thanks!

**Comment by RLHecht** [comment]
@Karak888 I think I need help with this. I don't see the info in the menu that's in Drupal.

**Comment by jenniferlee-dsva** [comment]
This is another of those funny Drupal business with menu structure - per this Slack explanation from Kevin Walsh: https://dsva.slack.com/archives/CDHBKAL9W/p1570728600006000?thread_ts=1570719676.005300&cid=CDHBKAL9W 

Basically, when we cross-link to a page (whether in another hub or in this case, at the root level), we have to make sure that the link is not showing up under that parent hub menu. Otherwise, the breadcrumb and nav for that parent hub will show up on that page. 

@RLHecht @mnorthuis - do you want to jump on a call/screenshare together and we can walk through this tgogether? I feel like the more of us have this knowledge, the better. Menus and nav links in Drupal are really confusing!

**Comment by jenniferlee-dsva** [comment]
p.s. @RLHecht - this page isn't in Drupal. There were a few root pages that we deliberately did not migrate into Drupal. This appears to be one of them, but I'd have to check.

**Comment by Karak888** [comment]
hi @RLHecht were we still not able to find this in GH?  Just trying to circle back on a few things, thanks!!

**Comment by RLHecht** [comment]
@Karak888 Still need help with this one. If there's time on the other call I have with Jen and Mikki tomorrow maybe Jen can walk us through it. If not, I'll touch base with her again on it.

**Comment by Karak888** [comment]
thanks @RLHecht !

**Comment by Karak888** [comment]
@ndsprinkle can you please let us know if this has been fixed, or if we need to size this.

**Comment by ndsprinkle** [comment]
@Karak888 Hey, I should've commented sooner, but this has not been fixed. Kelson and I worked through this quite a bit together, but there is something strange going on with my setup locally and I will have to wait until Nick Sullivan returns to see what is wrong. However, we were able to figure out basically how to solve this. 

If you are going to size this, I would recommend a 2 as the estimate. It is straightforward to remove the side nav and the remaining estimated time will be used to adjust some styling that gets messed up by removing it.

**Comment by ncksllvn** [comment]
Opened a PR for this, https://github.com/department-of-veterans-affairs/vets-website/pull/10979.

**Comment by ncksllvn** [comment]
Thanks for the quick reviews @kelsonic and @ndsprinkle! The work is merged and should go live tomorrow.

**Comment by mnorthuis** [comment]
This is now live and validated in prod.  Thank you!
