### ISSUE TITLE
CT Redesign: Search Cards  - Desktop  Prototype

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24518]
Low-fidelity profile page desktop prototype is drafted based on updated designs	

* Update mobile & desktop prototypes with optimal approach 
* UX team review for usability concerns, adherence VA.gov styles

**Comment by amyknox** [comment]
Noting that the title of this ticket is "Desktop" prototypes but the tasks include "mobile" prototypes.  Let's discuss.
