### ISSUE TITLE
CT Redesign: Search Cards -  Prototype, Team Sync

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24519]
Low-fidelity profile page prototypes Xfunc review is complete

* Prototype is shared with relevant team members  
* Feedback is collected 
* Prototype is tweaked, per input OR additional stories are written, as necessary

**Comment by JenLJ** [comment]
Mural with team feedback: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1620131600634/4057ee167fef2eef666968fd9ab35a6f7a2a446a
