### ISSUE TITLE
CT Redesign: Comparison Tray -- Remove Institution Solution; Desktop	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24510]
Desktop prototypes are updated with Comparison Tray removal alert	

* Update prototypes with alert to notify users the school will be removed from compare 
* Solution is consistent across CT screens (search page tray, compare page, profile page tray) 
* Review for adherence VA.gov styles

**Comment by amyknox** [comment]
Modal component in design.va.gov (storybook) https://design.va.gov/storybook/?path=/docs/components-modal--default

Starter text:

Remove {name of school} from your comparison? 

Yes / No

**Comment by amyknox** [comment]
@watersemma - I believe this is complete.  Could you confirm?

**Comment by watersemma** [comment]
@amyknox Copy has been updated. Should be good to go!

**Comment by watersemma** [comment]
https://bahdigital.invisionapp.com/share/VPIAGUNAY3S
