### ISSUE TITLE
EDU Forms / STEM 10203: Eligibility Update / Wizard  Content Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24526]
Content for expanded eligibility / SCO email has been drafted 	
* Content is drafted
* GH Doc is shared internally w/ UX; Xfunc Team
* Respond to any questions

**Comment by JenLJ** [comment]
Content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/apply-for-benefits-wizard-content-update.md
