### ISSUE TITLE
EDU Forms /1990e Update: Dependent & School Selection Discovery

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24529]
Requirements for form updates are understaood and documented	

* Form update is discussed internally 
* Questions are captured 
* Questions for EDU are shared, answered 
* Any outstanding questions are resolved

**Comment by amyknox** [comment]
https://dsva.slack.com/archives/C01K37HRUAH/p1620741728286000

**Comment by amyknox** [comment]
Final answer:  "Child"
No definition or supporting content.
