### ISSUE TITLE
EDU Forms / STEM 10203: Eligibility Update / SCO Email Content Update	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24523]
Content for expanded eligibility / SCO email has been drafted 	

* Content is drafted 
* GH Doc is shared internally w/ UX; Xfunc Team 
* Respond to any questions

**Comment by JenLJ** [comment]
Removed 6 digit CIP code criteria for clinical training programs in accordance with EDU direction.  Awaiting final edits from EDU


Content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-SCO-email.md

**Comment by JenLJ** [comment]
Updated with latest language on clinical training programs
