### ISSUE TITLE
EDU Forms / STEM 10203: Eligibility Update / Wizard  Prototype Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24527]
STEM Prototype showing expanded eligibility / SCO email is updated	

* Prototype is updated to incorporate EDU updates on confirmation page 
* Prototype is reviewed w UX team 
* Updates from UX are incorporated

**Comment by JenLJ** [comment]
Prototype: https://bahdigital.invisionapp.com/share/Q8IAGVLMYPS

**Comment by JenLJ** [comment]
Updated with latest language for clinical training programs
