### ISSUE TITLE
EDU Forms / STEM 10203: Eligibility Update / SCO Email Prototype Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#24524]
STEM Prototype showing expanded eligibility / SCO email is updated	

* Prototype is updated to incorporate EDU updates on confirmation page
* Prototype is reviewed w UX team 
* Updates from UX are incorporated

**Comment by JenLJ** [comment]
Prototype: https://bahdigital.invisionapp.com/share/RFIAGVBZYHJ

**Comment by JenLJ** [comment]
Updated with the latest language for clinical training programs
