### ISSUE TITLE
All CI actions are removed from Jenkins & Circle CI (lint/security/specs/reporting)

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#24536]
## AC
- [x] Ensure all CI actions from Circle CI (Testing Tools team is doing the work here)
- [x] CI tests are removed from Jenkins (build and deploy will still occur in Jenkins)

**Comment by ericboehs** [comment]
We've moved away as much as makes sense for now as we're moving to K8s/argo in ~6 months. Everything is being ran in GHA except when we deploy (Jenkins runs our rspec suite on deploy, for now).

**Comment by jeff2d2** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/7839
