### ISSUE TITLE
[Design] Combine Profile & Account: Create mockups of the new profile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2453]
Epic #2086 

[Sketch file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/personalization%202.0/Combine%20Profile%20and%20Account/Design/Profile%202.0.sketch)

- [x] Create mockups including:
  - [x] Personal information
  - [x] Contact information
  - [x] Military information
  - [x] Direct deposit
  - [x] Connected accounts
  - [x] Edit modals for all pages
  - [x] How saving and errors work
    - Make sure that modals close only after something has saved, and figure out when to show error message if save fails.
  - [x] How FAQ's work on each page
  - [ ] Mobile mockup
- [x] Share with the team
- [x] Make edits as needed

**Comment by Samara-Strauss** [comment]
First pass at design. Up next: modals, saving, errors.

[Profile 2.0.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3745520/Profile.2.0.pdf)

**Comment by lkoenigsberg** [comment]
@Samara-Strauss , this is great stuff and I only have a few comments/questions/suggestions.

1. Consider making the breadcrumb Home: Profile: Page, where Page is the section you are in now.  I’m sure you talked to the IA folks and maybe what you have is better, just wondering if there’s a real use case where a user might want to go back tot he start of profile and w/out a breadcrumb is not sure how.
2. For pages that don’t have an edit link (account security), consider spreading the text to use the whole area instead of leaving extra white space.
3. I’m pretty sure we can remove the terms & conditions element within account security.  Previous conversations with David B. gave me the impression that this is automatic upon creating an account and we don’t need to show it again.
4. Since we don’t actually have any connected accounts available right now, should we remove this section?

Looking forward to next level of detail!

Thanks,
Lisa

**Comment by Samara-Strauss** [comment]
Thanks for this, @lkoenigsberg! 

> Consider making the breadcrumb Home: Profile: Page, where Page is the section you are in now. I’m sure you talked to the IA folks and maybe what you have is better, just wondering if there’s a real use case where a user might want to go back tot he start of profile and w/out a breadcrumb is not sure how.

OK, so this is a little complicated because of how the side navigation is currently built. Right now, the side nav is built so the top heading (outlined in red) only serves to expand/close the navigation. It is *not* its own page and *does not* have its own URL.

<img width="222" alt="Screen Shot 2019-10-22 at 10 47 48 AM" src="https://user-images.githubusercontent.com/34068740/67298662-92c4aa00-f4b9-11e9-9140-2ad5298bf3a5.png">

So, given this, there will not be a way for people to go back to the beginning of the profile without a breadcrumb. We can default to the Personal Information section when people select "Profile" from the main navigation, and we can also make sure /profile routes to /profile-personal-information for people who may enter that URL manually.

> For pages that don’t have an edit link (account security), consider spreading the text to use the whole area instead of leaving extra white space.

Noted. I'm game for this from a design perspective, but I want to check in with one of our devs during technical discovery re: how the table is going to be built and whether it can be two or three columns depending on content needs, or whether we should consider it to always be three columns regardless or whether the third column is blank.

> I’m pretty sure we can remove the terms & conditions element within account security. Previous conversations with David B. gave me the impression that this is automatic upon creating an account and we don’t need to show it again.

I would imagine we would still need to show a link to the T&C, right? I understand that people may automatically have accepted it at sign up, but then there isn't anywhere else on the site I could easily find where we link to the T&C. If the account/profile is the only place to access it, my guess is we'd have to keep it accessible from there, or we'd have to surface that link elsewhere.

> Since we don’t actually have any connected accounts available right now, should we remove this section?

The Apple Health app uses this feature and is currently in Beta, so I've created these mockups to account for that. That being said, this section will not show for users unless they have connected an account to VA.gov, at least in the short term. In the long term, I think we could leave the section in the profile if there are more sites people could connect to VA.gov.

**Comment by Samara-Strauss** [comment]
Closing this ticket. Will create separate tickets for Tressa as necessary, as she is now taking over the project.
