### ISSUE TITLE
Design Feedback - Staging Review Healthcare Experience - Questionnaires (AKA: Clipboard)

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#24538]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Make sure you are using the proper heading/ styles. ‘Answer psychiatry…’ should be an H1, ‘Please try to fill out…’ should be a lead paragraph and ‘What happens after..’ should be an H2. Looking at the code it seems there is custom code applied.
- ![Screen Shot 2021-05-11 at 10.54.44 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/60f1992e-a61f-4a35-a67a-648a0f742ad4)
- Move the action link closer to the top of the page to keep the focus users on the [primary task](https://design.va.gov/design/principles), free of distractions. Right now the user will have to scroll and read to find the action link.
- ![Screen Shot 2021-05-13 at 1.31.24 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/d73c86d3-979d-4be0-b6f8-b580fd91f38e)
- Make sure the content on the review page matches the content in the form
- Unbold the data (Saturday…, 1:00a.m…. TEM…)
- ![Screen Shot 2021-05-13 at 1.55.13 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/51a25b09-f5fc-49ab-82e9-882843ec4a79)
- ‘Add another Question’ should be sentence case
- ![Screen Shot 2021-05-13 at 1.58.18 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/34873a90-4620-41a3-9f84-47015b182e62)

**Should:**
- Change the action link to be something more descriptive. Work with content to confirm but something like ‘Fill out the questionnaire’.

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by kristenmcconnell** [comment]
@allison0034 @rtwell In regards to the action link placement on the introduction page, I recently spoke with Danielle about this, since they are taking a holistic look at the intro pages. 

During the initial user test of this feature ([Research Findings](https://dsva.slack.com/archives/C0136TS768M/p1620933149370700)), we had the action at the top and bottom of the page (the traditional layout). Veterans immediately clicked the action at the top of the page and didn't review the rest of the page at all. After we had users slow down and review the content, they did find it valuable information. Therefore, we purposely removed the top call to action and we were able to run another user test. The revised intro page as you see it with the action link at the bottom tested very well. I didn't really include this in the second [research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/research/all-mvp-workflows/AllMVPWorkflows-Research%20Findings.pdf), because it tested so well.

I know that Riley Orr just ran a test on debts and had a similar finding. She discussed her findings with Danielle and Beth as well. 

@DanielleThierryUSDSVA Would you have anything to add about action links and intro pages?

So, my question is...Since the current placement of the action is backed by user research, is this still a must item?

**Comment by allison0034** [comment]
@kristenmcconnell if your primary goal is to get users to review that information first because that is the priority and then answer, then leave it as is. User research always wins : )

**Comment by kristenmcconnell** [comment]
@allison0034 To clarify this feedback:
Make sure the content on the review page matches the content in the form

Ignoring the list loop, the only difference I see is that the form says "What's the reason for your visit?" and the review page says "Main reason for visit."

I just want to double check that I'm not missing any other differences that you saw.

**Comment by allison0034** [comment]
@kristenmcconnell that should be fine. As long as it is coded correctly. We have documentation for the [review section](https://design.va.gov/patterns/form-templates#review-section) and [accordions](https://design.va.gov/components/accordions#multi-selectable) if you need a reference. It may have been an issue with the H2 tags. I tried to get back in to look but now the link isnt working.

**Comment by mdewey** [comment]
Dev tasks: 

- [ ] update header to be p tag
- [ ] Update `"What's the reason for your visit?"` on review page
- [ ] Bold labels, unbold data for appointment details

**Comment by kristenmcconnell** [comment]
@mdewey 
Update the H1, lead paragraph, and H2 styling.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell.

Re: question about thoughts on placement: I agree with Allison that if this tested well and meets the goal, we should go with it for this case. For awareness on the broader look at intro page patterns, Beth and I brought some initial ideas  to the design council last Friday, and we're continuing to work with Ryan more on this in this ticket: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/24391. Thanks!

**Comment by kristenmcconnell** [comment]
@allison0034 
Above (in the last two comments) are the items that Mark will be changing/updating. 

I wanted to address the last two items that I have commented on yet.

1. Add another Question’ should be sentence case
  - We are going to remove the list loop completely and replace it with a text area. Therefore, this button will go away.
2. Change the action link to be something more descriptive. Work with content to confirm but something like ‘Fill out the questionnaire’.
  - We worked with Peggy on the description of the buttons. We originally had something like "Complete your questionnaire," so I completely understand your feedback. We definitely had questions about what the action should be. We also discussed questionnaire statuses and if that impacted the action. On the other hand, was our status indicator (the thing styled like a label) enough/how did their addition impact the action links? Peggy proposed "Answer questions" and "Continue questions" actions. With all these questions, we made it a part of our last user test. In the end, what you see today tested well.

**Comment by allison0034** [comment]
@kristenmcconnell thanks for the update! If it tested well then leave it : )

**Comment by mdewey** [comment]
All the items that are from this ticket are in staging.

**Comment by mdewey** [comment]
Good Morning @allison0034! It looks like all the _musts_ have been addressed. What are the next steps?

**Comment by allison0034** [comment]
@mdewey thank you for all your hard work! You can close this ticket.
