### ISSUE TITLE
Platform Support Request Form User Guide

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#24534]
Updated version: https://vfs.atlassian.net/l/c/q7LBpzk7

Requesting review of the draft user guide for the new platform support request form. The draft is in my personal Confluence workspace: [https://vfs.atlassian.net/l/c/V1PPoE7x](https://vfs.atlassian.net/l/c/V1PPoE7x)

The images have not been finalized yet but want to make sure the written instructions make sense.

Thank you!

**Comment by lianilychee** [comment]
5/13 Thurs SU update:
- Gretchen (with Amy) will work with James on this after the SD sync today

**Comment by lianilychee** [comment]
5/17 Mon:
- The info is already IN the Platform website space
- Rebekah will update and image then let Gretchen know when `publish` button should be pressed (tho any of us can press `publish` if G is unavailable)
  - Just make sure there is only 1 change in the Support content source, no other changes

**Comment by lianilychee** [comment]
Live in Platform Website https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html
