### ISSUE TITLE
Add hint text to DSVA text input component

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#24548]
## Technical Task

As the design system adds more patterns to its library sometimes we see implementation gaps between what is a pattern and what is possible with the DSVA components.  When trying to implement this [hint text pattern](https://design.va.gov/experimental-design/hint-text#as-subtext-beneath-the-label) I noticed that the markup when input was required looked really bad when passing a custom label component into the input. This is possible inside the form builder due to additional configuration added by the forms library. When trying to implement with just DSVA component it tuns out wonky. Conversation talking about this [in slack thread](https://dsva.slack.com/archives/CMJ2V70UV/p1619625541416300)

Add a feature to the DSVA design component system so hint text can be passed as a prop. This way the markup when having a label, hint text, and a required field look good as intended in the DSVA Design Pattern documentation.

This way we can implement the design below outside of the forms library:

![image.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/cbb611fd-825d-4bb9-b561-ac472cbe2b1f)

## Expected Behavior

DSVA Text Input component can accept `hint text` as a prop and styling looks good when there is a label, hint text, and is a required field.

## Acceptance Criteria

- [ ] Expected Behavior is met on design system component
- [ ] Prop is added to story book documentation
- [ ] Design council is notified of this enhancement and has approved

## Resources & links
- [Component library repo](https://github.com/department-of-veterans-affairs/component-library)
- [TextInput Story Book](https://design.va.gov/storybook/?path=/docs/components-textinput--default)

**Comment by ala-yna** [comment]
Hi @caw310 - please take a look at this Design System ticket and let us know if you have any questions. Thanks!

**Comment by sshein** [comment]
Yes please!

**Comment by caw310** [comment]
@LinnJS , this issue was discussed in the DSC meeting. We're good with this change. If you could make it, that would be great as DST is booked up.

**Comment by dat-gcio** [comment]
@sshein @cvalarida I may be able to start work on this ticket this sprint. I wanted to ask how this works in regards to experimental design. From the engineering side, I am just adding additional features to an existing component. Each area that uses this existing component would have to opt into this feature.

**Comment by sshein** [comment]
yay! great question. since "hint text" is already in experimental design, I don't think you'd need to do anything besides adding the additional features and getting the normal PR approval. I'll add @rtwell in case he has anything to add though.

**Comment by SKasimow** [comment]
Note: overall design system issue not specific to 10-10 team. 

@sshein Hi - has there been progress on this issue? Wondering if we should close this ticket since it's not specific to 10-10 team. Thanks, Sharon

**Comment by sshein** [comment]
Justin was going to do it but then I guess it didn't get prioritized. Your team can still do it if there is time. If not, maybe tag the design system team to get in their backlog? cc @k80bowman for awareness

**Comment by humancompanion-usds** [comment]
Hint text is in the DS: https://design.va.gov/components/form/#hint-text Closing.
