### ISSUE TITLE
Design Feedback - Staging Review [Caregivers - Sign as a Representative]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#24544]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Good work!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Change ‘Cancel’ text link to secondary button on file upload
- ![Screen Shot 2021-05-11 at 8.36.32 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/ab41115a-4fe8-4ceb-b483-f1457bd8abe1)
- Fix text alignment issue
- ![Screen Shot 2021-05-11 at 8.44.50 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/b4ae5c0d-56e9-4a9f-9b93-e02c77c853e7)
- In the [review section](https://design.va.gov/patterns/form-templates#review-section), add a secondary ‘Delete file’ button. This is what most have currently in production. You may be able to remove the ‘Edit’ button. Ignore the primary button, it should be secondary and I have a ticket submitted to fix it.
- ![Screen Shot 2021-05-11 at 8.41.39 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/4ba605ed-1949-4fae-9ae6-43a98dfa95cd)

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by dat-gcio** [comment]
I have this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17190) open to make the change to the cancel button. The rest has been merged.

**Comment by Dene-human** [comment]
@allison0034 All feedback has been incorporated on [staging](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction).

**Comment by allison0034** [comment]
@Dene-human thank you!
