### ISSUE TITLE
Add cypress test for POA work on 10-10CG

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#24552]
## Technical task

We need to test the sign as representative work with cypress test so we can move quickly in the future without the worry of breaking the user experience. We need to add the stub for the POA feature flip to the cypress test. And then make a test case that includes the feature flip with mock data for the corresponding pages. 

## Expected Behavior

The cypress test suite for the 10-10CG includes the sign as representative (POA) workflow as well as the sign as representative signature box on the review page.

There is a pre-existing `data-testid` on the signature box that you can use to select the inputs. Linked below.

## Acceptance Criteria

- [x] We are testing the yes/no/no POA page
- [x] We are testing the document upload page
- [x] We are testing the sign as representative signature box on review page

## Helpful links & resources
- [Cypress forms library docs](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-end-to-end-test/)

-  [Feature flip mocks for cypress](https://github.com/department-of-veterans-affairs/vets-website/blob/LinnJS-poa-508-fixes/src/applications/caregivers/tests/e2e/fixtures/mocks/feature-toggles.json#L0-L1)

- [Cypress test where flip data is added](https://github.com/department-of-veterans-affairs/vets-website/blob/LinnJS-poa-508-fixes/src/applications/caregivers/tests/e2e/1010cg.cypress.spec.js#L73)

- [data-tesid selector used for Cypress testing](https://github.com/department-of-veterans-affairs/vets-website/blob/LinnJS-poa-508-fixes/src/applications/caregivers/components/PreSubmitInfo/SignatureCheckbox.jsx#L34)

**Comment by dat-gcio** [comment]
There is a weird issue with the file upload accessibility test failing in Jenkins but works fine locally. Merged two of the test cases in and troubleshooting the one with the issue.
