### ISSUE TITLE
Select & copy text

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24558]
## User story
As a user, I want the ability to select blocks of text from the app so that I can paste it in an email, text message, or note. 

## Acceptance Criteria
1. Enable the ability to select and copy text by long-pressing on the text
2. On iOS:
    - Long pressing the text will trigger a "Copy" button. Selecting this will copy the paragraph to the device's clipboard
3. On Android:
     - Long pressing the text will highlight certain text
     - Options to Copy, Share, Select All
     - Highlight color: #9bdaf1

- [ ] Note for dev: retest #17734

## Screenshot for reference
![Screen Shot 2021-05-11 at 10.03.31 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/47591110-ee9a-4e16-a000-691a3bd5828a)

## Accessibility Implementation Guidelines
- When the device's screen reader is enabled (Voice Control, Voice Assistant, etc.), this should disable the select-to-copy UX

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/2/2021 - Looks good on iOS and Android.  Closing.
