### ISSUE TITLE
[FE] Combine Profile & Account: Technical Discovery

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2455]
Epic #2086

Tracking questions for technical discovery. This list will continue to grow:

1. What are our current profile save messages, warnings, and errors?
2. Do we show military awards under the "Military information" section? I have that in an old mockup but I'm not sure if we actually pull in that information. Can you check the code?
3. What are all the military branches we detect in the Military Information section? Do we detect if someone was in the Guards/Reserves? Can we pull an exact list of the terms we use?

**Comment by Samara-Strauss** [comment]
@Justin-Pickett can we get this prioritized for next sprint?

**Comment by Justin-Pickett** [comment]
@Samara-Strauss yes we can look at getting this slated to go into Sprint 7 coming up.

**Comment by Samara-Strauss** [comment]
@bradl3yC I greatly pruned the list of questions above, as @tressaellen is working on some new design proposals and a lot of my original questions were based on specific design mockups. Over time, we'll have more questions as we land on a final direct for the profile. In the meantime, the above questions are still applicable regardless of visual approach.

@tressaellen I'd recommend starting to compile technical questions as you're doing your explorations. We can post them here as we're more sure of what direction we want to take.

**Comment by bradl3yC** [comment]
1. It looks as if we are passing on the error message provided by the API - Checking with Lihan if we have a list.
2.  I cannot find any reference to awards that we're currently displaying on profile
3.  Here is the list of options we provide when selecting your service via profile (as best I can find in the code):
```
{ value: 'air force', label: 'Air Force' },
  { value: 'army', label: 'Army' },
  { value: 'coast guard', label: 'Coast Guard' },
  { value: 'marine corps', label: 'Marine Corps' },
  { value: 'merchant seaman', label: 'Merchant Seaman' },
  { value: 'navy', label: 'Navy' },
  { value: 'noaa', label: 'Noaa' },
  { value: 'usphs', label: 'USPHS' },
  { value: 'f.commonwealth', label: 'Filipino Commonwealth Army' },
  { value: 'f.guerilla', label: 'Filipino Guerilla Forces' },
  { value: 'f.scouts new', label: 'Filipino New Scout' },
  { value: 'f.scouts old', label: 'Filipino Old Scout' },
  { value: 'other', label: 'Other' }
```

**Comment by Samara-Strauss** [comment]
Thank you, @bradl3yC!

**Comment by Justin-Pickett** [comment]
We need to find a list of errors that are being presented from the VA profile database. Tressa will do a bit of research in the testing environment. Also, Justin will reach out to VA Profile team to see if there is a list of errors that returned .

**Comment by tressaellen** [comment]
Here's what I could find for errors/messaging.

- [Errors list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/error-messaging/error-code-matrix.md) 

- [Address Validation Errors](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/error-code-matrix.md)

- Screenshots of messages: [https://app.zenhub.com/files/133843125/9faec29d-0e08-469e-8afd-ba202cc327b2/download](https://app.zenhub.com/files/133843125/9faec29d-0e08-469e-8afd-ba202cc327b2/download)

- [Full errors list](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/locales/exceptions.en.yml) (look for anything with prefixed Vet360)
