### ISSUE TITLE
Expose Sign Out button below errors on Profile

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24555]
## Acceptance Criteria
1. If the Profile page displays a generic app error, display the Sign Out button below the error alert
     - Users should have the ability to log out of the app even if they encounter an error on the Profile page

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/27/2021 - Looks good.  Closing.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/5448784d-4d77-4e49-b4cf-ac48dd252957)
