### ISSUE TITLE
[DESIGN] My VA: Write conversation guide for My VA mini usability sessions

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#24564]
## Background

Before we launch, we need to make sure there are no major usability problems with My VA. We're going to run an internal mini usability test to make sure nothing is too confusing before we launch to all users.

## Tasks

- [ ] Write conversation guide
- [ ] Review with Samara

**Comment by tressaellen** [comment]
Good morning @Samara-Strauss ! Here is the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/discovery-and-research/MyVA-mini-usability/MyVA%20mini-conversation-guide.md) if you'd like to review it.

**Comment by Samara-Strauss** [comment]
Going to hold off on reviewing this per my comment in #24563. We can not run usability research with My VA launched behind a feature flag until we are effectively ready to launch the work, which won't be until we are ready for UAT.

Let's talk about whether we want to run research at all. If so, we can update the plan and convo guide as necessary, and then I'll review.

**Comment by Samara-Strauss** [comment]
Just reviewed and have a thought. If we're really just looking for any glaring usability issues, I don't think we need to ask questions like the following:

- What would you use this page for?
- What would make this page more useful to you?
- What is confusing about this page?
- What is missing on this page?
- What's the most important thing we could tell you about your claims and appeals?

It's not that there's anything inherently wrong with these questions — I do think we should continue exploring these things with real veterans and real veteran data as the page evolves — but they don't necessarily answer whether the design is usable or not. I would imagine that if we want to assess usability, we'd be asking more task-based questions and then following up as necessary if someone seems lost, mentions confusion (in that case, we definitely want to understand why they were confused and how we could make it better), or makes other negative comments (eg. "I would never use this page").

Does that make sense? I just want to make sure you're able to get what you need to out of this study.

**Comment by tressaellen** [comment]
@Samara-Strauss - yes that does make sense... I'll revise.

**Comment by tressaellen** [comment]
Okay, I've made updates to the conversation guide and restructured it so it's more task based, let me know what you think!

**Comment by tressaellen** [comment]
I just realized you're on PTO - so no need to respond! I'll follow up with some Ad Hoc folks to make sure I'm going the right direction. Enjoy your time off!

**Comment by Samara-Strauss** [comment]
Looks better! Good luck with your sessions on Friday. I'll catch the ones on Monday. Have a great weekend!
