### ISSUE TITLE
[DESIGN] My VA: Synthesize findings from My VA mini usability sessions

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#24566]
## Background

Before we launch, we need to make sure there are no major usability problems with My VA. We're going to run an internal mini usability test to make sure nothing is too confusing before we launch to all users.

## Tasks

- [ ] Write research synthesis 
- [ ] Review with Samara and team

**Comment by tressaellen** [comment]
Hello @Samara-Strauss - the [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/discovery-and-research/MyVA-mini-usability/My%20VA-mini-usability-findings.md) are ready for your review. :)

**Comment by Samara-Strauss** [comment]
This is great! Thank you so much for doing the research and putting this together. I think the insights are really helpful.

One question — what did people say they wanted when they wanted a customizable dashboard? Could you add some details on that in the findings section? I am curious as to what that means and what your recommendations are. My gut is that we could solve this problem with better personalization — I have yet to meet a product problem that really, truly needed customizability — but I'd love to know more about what people said.

**Comment by tressaellen** [comment]
Thank you for looking over it! 

Re: customization - I added some details around this (granted I don't have much since we couldn't dive into things super deep), but I also agree with your hypothesis that once we can provide a more personalized experience the need for customization won't be there. I added a question around that in the 'Things to think about' section.

**Comment by Samara-Strauss** [comment]
Awesome, thank you!
