### ISSUE TITLE
Fix app bucket deploy scripts

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#24567]
## Description
The [new deploy script for deploying to the app bucket](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-application-build/files/application-build.sh) was copied over from a [previous "speedy S3 deploy" script](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-speedy-s3-assets/files/speedy-s3-deploy.sh).

It currently copies everything from the archived app build to the live bucket. The bucket contents should be narrowed down to the set of assets that actually get referenced by the content build pages.

In copying the script, we've also dropped the compression on the assets and need to add it back. The lack of compression has caused total downloaded size of pages to almost double, so pages are taking longer to load. Currently only affects dev and staging; prod does not use its app bucket yet, but this needs to be fixed before that happens.

One approach discussed was (1) identifying what assets need to go into the bucket from the file manifest and (2) compressing and uploading everything from that list.

### Slack threads
- [In which SpeedCurve reported a lot of metrics crossing their budgeted thresholds, including total downloaded size.](https://dsva.slack.com/archives/CQH357ZTP/p1620423178272100) We also made the initial discovery that assets were not getting compressed.
- [In which it was confirmed that the new deploy script for the app bucket did not compress the assets.](https://dsva.slack.com/archives/C01S39QMSSV/p1620678288223000)

## Acceptance criteria
- [ ] Assets served from the app buckets are compressed.
- [ ] App buckets contents include only the assets that they need to serve.

**Comment by jhouse-solvd** [comment]
@U-DON - is there something specific that you need the operations team's help on?

**Comment by U-DON** [comment]
@jhouse-solvd: Not at the moment, but when we're ready to test the changes, we may ask for assistance with doing a deploy to dev from a branch.

**Comment by jhouse-solvd** [comment]
@U-DON - is it cool if we remove the "operations" label for now? That's the team label that we use to determine our number of open issues/tickets...

**Comment by U-DON** [comment]
@jhouse-solvd: Sure thing. We'll bring it back if we specifically need more involvement from y'all. 😉

**Comment by theodur** [comment]
Updates to the [app](https://github.com/department-of-veterans-affairs/devops/pull/9217) and [content](https://github.com/department-of-veterans-affairs/devops/pull/9224) deploy scripts are merged. The s3 buckets should now only contain the files needed ✅ Big thanks to @mleclerc00 for helping with testing changes on dev.
