### ISSUE TITLE
VRRAP: Update introduction content and YTD prod report distribution

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24562]
As a developer, I need to update the introduction page content so that it is consistent with other informational content on VA.gov and add an additional user to the YTD report distribution so that they have access to the VRRAP submission statistics.

## Assumptions:
1. N/A

## Acceptance Criteria:
1. The content in section 1 of the VRRAP introduction subway map is:

> #### 1. Make sure you're eligible  
> 
> To be eligible for Veteran Rapid Retraining Assistance Program (VRRAP), you must meet all the requirements listed here. 
> 
> **All of these must be true.  You're:**
> 
> * At least 22 years old, but not older than 66, **and**
> * Unemployed because of the COVID-19 pandemic, **and**
> * Not rated as totally disabled because you can't work, **and**
> * Not enrolled in a federal or state jobs program
> 
> **Note:** You can't receive VRRAP benefits at the same time you're receiving unemployment benefits (including CARES Act benefits).
> 
> Also, at the time you apply for VRRAP you can't be eligible for any of these other benefits: 
> * [Post-9/11 GI Bill](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/)
> * [Montgomery GI Bill](https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/)
> * [Veteran Readiness and Employment (VR&E)](https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/)
> * [Survivors’ and Dependents’ Educational Assistance (DEA)](https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/)
> * [Veterans’ Educational Assistance Program (VEAP)](https://www.va.gov/education/other-va-education-benefits/veap/)
> 
> **Note:** You can get VRRAP benefits if you were eligible for the Post-9/11 GI Bill at one time but have transferred all of those benefits to family members

2. The following email addresses are included in the Production “Year to date report” email distribution:
    a. Darla van Nieukerk <Darla.vanNieukerk@va.gov>

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/3f71d966a6e0ad4934096028a59715cc86fc8d7b/products/education-careers/application/VRRAP/design/content-doc.md)
2. [Introduction Page](https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/7154

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17492

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA


https://dsvavsp.testrail.io/index.php?/runs/view/1927&group_by=cases:section_id&group_order=asc&group_id=51
