### ISSUE TITLE
[DESIGN] My VA: Create My VA mini usability research plan

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#24563]
## Background

Before we launch, we need to make sure there are no major usability problems with My VA. We're going to run an internal mini usability test to make sure nothing is too confusing before we launch to all users.

## Tasks

- [x] Write research plan
- [ ] Review with Samara

**Comment by tressaellen** [comment]
Good morning @Samara-Strauss ! Here is the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/discovery-and-research/MyVA-mini-usability/MyVA%20mini-research-plan.md) if you'd like to review it.

**Comment by Samara-Strauss** [comment]
Cross-posting from Slack.

We can't do this test as outlined. We are not going to be ready to launch this work behind a feature flag until QA is complete, fixes have been implemented, and it goes through the final platform reviews. Launching behind a feature flag basically is launch, and that really should only happen when we are 100% ready for UAT. If we want to test with users' real data, we are going to have to wait.

Let me know if you'd like to talk about this and whether any testing now is useful or not.
