### ISSUE TITLE
[Design] Notification Preferences: Update documentation and mockups to show removal of mobile alert checkbox in profile

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24575]
## Background
As a result of Liz's research and design work around the Notification Preferences feature we've determined that we should ultimately remove the mobile alert checkbox that currently appears on Profile. This checkbox has also caused a11y issues in the past. (See #23168 and #23532 for reference).

## Tasks
- [ ] Update frontend documentation to indicate the removal of this checkbox in Profile
- [ ] Update/create mockup to indicate remove of this checkbox in Profile
- [ ] Review w/ team

**Comment by andaleliz** [comment]
Updated #24696 to capture this change; closing since its duplicative.
