### ISSUE TITLE
1990S: Axe error  "Heading levels should only increase by one" on intro and confirmation pages

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#24576]
The introduction and confirmation pages of the VRRAP form both fail axe checks with a `Heading levels should only increase by one` error. The heading levels need to be adjusted so that the form meets accessibility standards.

*Notes:* 
- The **styling** of the heading is correct and should not change
- Fixing only the header highlighted by the original axe check will only move the error. All subsequent heading levels will also have to be adjusted

# Expected behavior
- Heading levels are not skipped and axe checks pass

# Actual behavior
- Heading levels are skipped

## Intro page
- [ ] `Follow these steps to apply` to H2
- [ ] `Make sure you're eligible` to H3
- [ ] `Prepare` to H3
- [ ] `Apply` to H3
- [ ] `VA review` to H3
- [ ] `Decision` to H3
- [ ] `All of these must be true. You're:` to H4
- [ ] `To fill out this application, you’ll need your:` to H4

## Confirmation page
- [ ] `We've received your application.` to H2
- [ ] `Veteran Rapid Retraining Assistance Program (VRRAP)` to H3
- [ ] `What happens after I apply?` to H3
- [ ] `Need help?` to H3

# Screenshots
![Screen Shot 2021-05-11 at 4 36 27 PM](https://user-images.githubusercontent.com/45575003/117990034-c6b92780-b30a-11eb-86c9-59e823d1aa4f.png)

---

![Screen Shot 2021-05-11 at 4 46 57 PM](https://user-images.githubusercontent.com/45575003/117990059-cc167200-b30a-11eb-9194-4b9581fef254.png)

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18658
