### ISSUE TITLE
[Design] Profile: Create design to replace mobile alert checkbox in read mode

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24572]
## Background
As reported in #23168 and #23532 the current design of the mobile alert checkbox on Profile is not compatible with screen readers. In read mode, we need to let people know if they are opted into or out of notifications in a way that is compatible with screen readers

**Current state**
<img src="https://user-images.githubusercontent.com/55992116/118108825-74c9dd80-b3ae-11eb-9b8b-c4ae173e18a6.png" width="75%"/>

## Tasks

- [ ] Create design to let people know if they are opted into or out of notifications in a way that is compatible with screen readers

**Comment by andaleliz** [comment]
Put together a couple of options to review in content office hours today.  I'm glad we're adding notification settings - this is kind of an odd pattern to have people opt in to this one notification in this way.

**Proposed for opted-in users**
<img src="https://user-images.githubusercontent.com/55992116/118111985-67165700-b3b2-11eb-9ccc-464cd0abd9cf.png" width="75%" />

**Proposed for opted-out users**
<img src="https://user-images.githubusercontent.com/55992116/118112039-78f7fa00-b3b2-11eb-8ed8-b50d50edb23f.png" width="75%" />

**Comment by andaleliz** [comment]
Reviewed with Danielle this morning.  

Final copy for users opted out:
If you’d like to get text reminders for your VA health appointments, edit your mobile number settings.
<img src="https://user-images.githubusercontent.com/55992116/118148931-0a7d6100-b3df-11eb-89a4-5ccd9a5a4570.png" width="75%" />

Final copy for users opted in:
We text VA health appointments reminders to this number. To stop getting these reminders, edit your mobile number settings.
<img src="https://user-images.githubusercontent.com/55992116/118148821-efaaec80-b3de-11eb-8d56-02a6a3fd2838.png" width="75%" />

Closing as I think this is ready for FE, but please re-open if more work is needed on my part.

**Comment by ajakabcin** [comment]
awesome work on this @andaleliz and the quick turnaround - thank you!

**Comment by erikphansen** [comment]
@DanielleSoCompany It might just be me, but `health appointments reminders` reads a bit odd. Should it be `health appointment reminders`?

**Comment by andaleliz** [comment]
@erikphansen yes it should! That's my bad.
