### ISSUE TITLE
[new] Frontend updates based on Staging Review 

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#24588]
This is feedback is based on the staging review (May 11, 2021). Design and content related updates.

**Design-related**
- [x] Change ‘Cancel’ text link to secondary button on file upload. Please use [prototype](https://preview.uxpin.com/e3a1c4cfb7408175af0bc54173e311d14a406ae2#/pages/138525979/simulate/sitemap?mode=i) as reference. ![Screen Shot 2021-05-11 at 8.36.32 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/ab41115a-4fe8-4ceb-b483-f1457bd8abe1) 

- [x] Check text alignment issue. This is issue is occurring only for some testers. ![Screen Shot 2021-05-11 at 8.44.50 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/b4ae5c0d-56e9-4a9f-9b93-e02c77c853e7)

- [x] Check that on the review page the supporting document section has ‘Delete file’ button. This is issue is occurring only for some testers.
![Screen Shot 2021-05-11 at 8.41.39 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/4ba605ed-1949-4fae-9ae6-43a98dfa95cd)
![correct upload file](https://user-images.githubusercontent.com/80857940/117992330-d8033380-b30c-11eb-8b8d-d7a99d46996e.png)

**Content-related**
- [x] [Representative documentation](https://preview.uxpin.com/e3a1c4cfb7408175af0bc54173e311d14a406ae2#/pages/138525977/simulate/sitemap?mode=i) question page, please add period after "No. I don't have this document." (third radio)
![add period](https://user-images.githubusercontent.com/80857940/117990787-7c847600-b30b-11eb-9f7a-e049d938e935.png)

- [x] [Upload document](https://preview.uxpin.com/e3a1c4cfb7408175af0bc54173e311d14a406ae2#/pages/138525978/simulate/sitemap?mode=i) page text update to:

Guidelines for uploading a file:
You can upload a .pdf, .jpeg, or .png file
Your file should be no larger than 25MB
![upload file guidelines](https://user-images.githubusercontent.com/80857940/117988384-5b228a80-b309-11eb-94c0-35a815dad500.png)

Representative document question and upload page
- [x] 1.  (both pages) Header change from Representative documentation to **Representative document** 
- [x] 2. (upload page) Upload your legal representative documentation change to **Upload your legal representative document**
![document content](https://user-images.githubusercontent.com/80857940/118045672-38fb2d80-b346-11eb-93c1-5d0e07b06b7c.png)

**Update 5/14/2021**
Intro page
- [x] 1. Change "Start your application" action link to green styling ([see here](https://design.va.gov/storybook/iframe.html?id=components-action-link--primary&viewMode=story))
- [x] 2. text change: Follow the steps below to apply for the Program of Comprehensive Assistance for Family Caregivers to **Follow these steps to get started:**
<img width="1031" alt="intro page" src="https://user-images.githubusercontent.com/80857940/118303011-eee38a80-b4b2-11eb-9385-9e56ea3ee7ff.png">

**Comment by dat-gcio** [comment]
Re `Change ‘Cancel’ text link to secondary button on file upload. Please use prototype as reference.`
- I will need to do this in a separate PR since it's a change on the platform side.

Re `Check text alignment issue. This is issue is occurring only for some testers.` After discussion with Dené and Shawna, it  was decided that we should go ahead and move the `On behalf of` label to under the signature input.

Re `Check that on the review page the supporting document section has ‘Delete file’ button. This is issue is occurring only for some testers.`
- I was also not able to repro this issue.

**Comment by Dene-human** [comment]
@dat-gcio Please note that I have add one more item on the content changes list

**Comment by dat-gcio** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17186) has been updated.

**Comment by Dene-human** [comment]
@dat-gcio I have added the feedback from platform accessibility and content to the bottom of the list.

**Comment by dat-gcio** [comment]
@Dene-human Here is the review instance for your review for the changes to `Start your application` http://9ce008779b86a37b88c5e8b7d91475f5.review.vetsgov-internal/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction

**Comment by dat-gcio** [comment]
@Dene-human The file upload cancel button and intro page changes were merged this morning.
