### ISSUE TITLE
Use editOnReviewPage in FileField

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#24583]
## Issue Description
The `FileField` doesn't use the `editOnReviewPage` uiSchema option. This leads to issues like what @LinnJS ran into [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23616). The fix is to put the field in edit mode if `!formContext.reviewMode || editOnReviewPage`.

---
## Acceptance Criteria
- [ ] The field starts in review mode if `editOnReviewPage` is false
- [ ] The field starts in edit mode if `editOnReviewPage` is true when `formContext.reviewMode` is also true

**Comment by cvalarida** [comment]
Looks like this should be a pretty light lift. I think we'll just need to update [this line](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms-system/src/js/fields/FileField.jsx#L227) and write a test for it.

**Comment by caw310** [comment]
Closing as this is old and the VADS has been updated. If there is still an issue file a new bug.
