### ISSUE TITLE
Langauge Assistance Pages | Click-to-Dial |

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#24580]
Embedding the "Click-to-Dial" feature on our pages, eliminates the need to remember, copy and paste, or write down a phone number.

Click-to-Dial should support both mobile and desktop users provided Mac users have FaceTime or Windows users have installed the Your Phone app.

## User Story

As a user I would like to be able to use the "click-to-dial" functionality to make it easier for me to connect with an interpreter when I am on a mobile device, have FaceTime on my Mac or have installed the Your Phone app on Windows.

## Expected Behavior

**Scenario 1:**
Given I am on a mobile device 
OR
have FaceTime on my Mac
OR
have Your Phone app installed on my Windows device
THEN
The phone number shown on the Spanish, Tagalog and Other Language pages be underlined indicating it is a clickable element 
AND
upon clicking should invoke the dialer with appropriate treatment based on device/OS

(Note: <a href="tel:+18008271000" aria-label="8 0 0. 8 2 7. 1 0 0 0.">800-827-1000</a> )

## Acceptance Criteria

- [ ] 800# for language assistance invokes dialer

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - can you provide the 800# to use?

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow It's not that number, no - I was just sharing that example from our style guide to show the coding. 

This is the language that we're currently working with around the 800 # and interpreters:
If you need more help, call our MyVA411 main information line at 800-698-2411 (TTY: 711). We're here 24 hours a day, 7 days a week. Select 0 to connect with a call center agent. Tell the agent you'd like an interpreter who speaks [language] to join the call.

But I want to make sure I'm understanding - we would typically just add this in as part of flowing the content in. Are you thinking that there will be a separate element on the page highlighting the #?

**Comment by SKasimow** [comment]
Hmmmm....I'll defer to @youngfreezyVA to respond to what exactly is needed here. I thought there might be a different/additional requirement since the page will be built in Github. Maybe it's simpler than I thought it would be :)

**Comment by youngfreezyVA** [comment]
it sounds like you can add a links href directly in the CMS, but formatting/building the href on the front end is pretty simple if we needed to do that, but if its possible to do it in the CMS we can just do it there.

this matches up w/ the example @DanielleThierryUSDSVA provided earlier:
https://css-tricks.com/the-current-state-of-telephone-links/

**Comment by SKasimow** [comment]
@youngfreezyVA these are pages you'll build in Github so I assume it will need to be done on the front end, no?

**Comment by SKasimow** [comment]
@youngfreezyVA @DanielleThierryUSDSVA closing this. As discussed pages will be created in Drupal :)
