### ISSUE TITLE
Search UI Consistency: Document Search Design Pattern for Design System

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24597]
This is just a placeholder issue to link to the Experimental Request ticket in the design system backlog: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=&labels=&template=experimental_design_request.md

**Comment by MarciMcGuireGCIO** [comment]
New pattern template is now available.  https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=&labels=&template=documentation_template.md

The Design System request that needs to be completed is https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/459

**Comment by MarciMcGuireGCIO** [comment]
@denisecoveyduc @mgleo I am tagging you both into this issue because your team was also involved in this, and will need be involved in documenting and defining the pattern.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 and @mgleo -- I know you both have other priorities, but would you mind estimating this work when you have a chance?  Thank you!

**Comment by MarciMcGuireGCIO** [comment]
Updating description to link to Experimental Request template.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 I just reviewed the new template for experimental design and it looks pretty straightforward.  I think it's something you could easily complete, and then the only other step is to present to the Design Council.

**Comment by MarciMcGuireGCIO** [comment]
Experimental Design Request: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/503

**Comment by MarciMcGuireGCIO** [comment]
Posted request in #vsp-design-system requesting to attend an upcoming Design Council Meeting.
https://dsva.slack.com/archives/C01DBGX4P45/p1627562144122900

**Comment by MarciMcGuireGCIO** [comment]
This pattern was approved to be added to the Experimental design system.  Zach, Cassandra & Marci will document in Sprint 55 after everyone is back from PTO.

**Comment by mgleo** [comment]
@MarciMcGuireGCIO I can help during Sprint 55 as well.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @mgleo !

**Comment by MarciMcGuireGCIO** [comment]
@mgleo were you able to get any additional clarification on adding this to the experimental design system?

**Comment by MarciMcGuireGCIO** [comment]
Moving this to blocked; reading through threads on Slack it seems that the process for adding a pattern to the experimental design system needs to be defined.

**Comment by MarciMcGuireGCIO** [comment]
See work now being tracked in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/30400

**Comment by FranECross** [comment]
Closing ancient ticket.
