### ISSUE TITLE
Access for Jhonny Gonzalez

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#2459]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Jhonny Gonzalez
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP-Tools and Improvements team, Senior Frontend Engineer, and Oddball
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

  >  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQrpyvrQ2F9xPYaeLolAzbvQghDrCAEQHD3DemlH0wfM/TlJhV9q1Voao55aVLAsJpNug8zVH0GG6roHrCjq+DzFOubJk7Wi/P408M7bUY5PySX/HPIeMqiyywaHtT2KTVP/sYFeOlBaGWBk6T70pHtxnCyk7naKqxDeoswgvWN8xmOSpWTgDZVCTJgtTRZFdYHQZIGbqW7mAqoO4T1HOpL1tljaDpZsLQ3ZVnXKtKgNYgRyndWlNAOa9WrvodeKPfYEDORRus9iaPH3TIBfoQKT0cjBrRr5GIyXcq0oh22kiNbyK+NUE1FWVA6ohotx+7+vX3vyb/a0n2AZYzoe+f mauro@Mauros-MacBook-Pro.local

- [Grant AWS Console access?]
  > NO

**Comment by jhonnyoddball** [comment]
@department-of-veterans-affairs/vsp-operations Please proceed

**Comment by ricetj** [comment]
@Jeff-Hayter
COR: Yourself
User: Jhonny Gonzalez

**Comment by Jeff-Hayter** [comment]
@ricetj Confirmed, please grant access.
