### ISSUE TITLE
Add Issue Templates to `va.gov-vfs-team` repo

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#246]
## User Story
As a VFS team member, I need issue templates so I can write tickets with all of the correct information expected of me for building on Va.gov.

## Goal
We want writing tickets to be extremely easy and consistent across all VFS teams

## Acceptance Criteria
- [ ] Issue Templates need to be created for different scenarios including
   - Standard Issues
   - Bugs
   - Epics
   - Review Requests

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by gunsch** [comment]
cc @hpjaj, the content in https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/13 should inform the issue template content

**Comment by rtluu** [comment]
Per our decisions from the Content/IA team (@mnorthius), we've decided to have VFS teams operate their workflow out of `va.gov-team` repo and therefore do not need separate issue templates in `va.gov-vfs-teams` repo

[Link to decision](https://dsva.slack.com/archives/CJRQ85PQB/p1563287518010300)
