### ISSUE TITLE
Fix Find Forms Sorting unexpected bug after Lighthouse Feature Flag is enabled

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#24616]
## Issue Description
Undesired side effect found during testing. The relevance sort is not default correctly now.
Need to test to make sure the FF is working correctly.

## Acceptance Criteria
- [x] Sort default correctly
- [ ] Add back FE "spellchecker" back in.
- [ ] Feature Flag works as intended.
- [x] Unit tests pass
- [x] End-to-end tests show 0 violations.
- [x] All axe checks pass

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO We good to close this now that there's no need to refresh?

**Comment by MarciMcGuireGCIO** [comment]
Yep!  🎉

**Comment by MarciMcGuireGCIO** [comment]
Reopening; looks like it has reared its ugly head.

**Comment by zacharymorel** [comment]
Morning @MarciMcGuireGCIO , from the conversation about the race condition, we should be able to close this.

**Comment by MarciMcGuireGCIO** [comment]
Oh, yep! Thank you!
