### ISSUE TITLE
10203: Add question and content for covered clinical training program update

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24612]
As an EDU team member, I need form 22-10203 updated to account for legislative changes that allows for applicants to be eligible for the STEM scholarship if they are pursuing a covered clinical training program so that they can apply and be processed efficiently.

## Assumptions:
1. This work is completed behind feature flag `10203_isakson_and_roe` #24615 
2. The form can be found here: [Staging Form](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction)

## Acceptance Criteria:
1. On the Form Introduction page, the `STEM degree:` bullet has the following sub-bullets in subway stop 1:

    > - You're enrolled in a bachelor’s degree program for science, technology, engineering, or math (STEM), **or** 
    > - You've already earned a STEM bachelor’s degree and are working toward a teaching certification, **or**    
    > - You've already earned a STEM bachelor's or graduate degree and are pursuing a covered clinical training program for health care professionals.
    >    [See eligible degree and clinical training programs](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf)

2. In Form Chapter 3, Page 1:
    a. The question 

    > "Do you have a STEM undergraduate degree and are now pursuing a teaching certification?" 

    is replaced with: 

    > "Do you have a STEM undergraduate degree and are now working toward a teaching certification?"

    b. The following question is conditionally displayed when the applicant answers `No` to the question `Do you have a STEM undergraduate degree and are now working toward a teaching certification?`:

    > Do you have a STEM bachelor's or graduate degree and are now pursuing a covered clinical training program for health care professionals?

3. The question in AC2b has the following characteristics:
    a. Available answers of "Yes" and "No"
    b. Is required
    c. Includes the following link to eligible programs: [See eligible programs](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf)
    d. Is grouped with the conditional question by the blue bar pattern
    e. Is included in the spool file with the user selected answer (Ex: Do you have a STEM bachelor's or graduate degree and are now pursuing a covered clinical training program for health care professionals? Yes)

4. In Form Chapter 3 STEM Summary Widget:
    a. "Are enrolled in a bachelor’s degree program for science, technology, engineering, or math (STEM), or have already earned a STEM bachelor’s degree and are pursuing a teaching certification" is removed from the widget.
    b. The following content is included in the widget:
     > ✖️ Are:
     > 
     > - Enrolled in a bachelor’s degree program for science, technology, engineering, or math (STEM), **or**
     > 
     > - Have already earned a STEM bachelor’s degree and are working toward a teaching certification, **or**
     > 
     > - Have already earned a STEM bachelor's or graduate degree and are pursuing a covered clinical training program for health care professionals

    c. "Are:" is marked with an ✖️ if the answer to all corresponding questions is "No".
    d. "Are:" is marked with an ✔️ if the answer to any corresponding questions is "Yes".
    e. The EVSS entitlement warning content is:

    > Your remaining education benefits
    > 
    > You must have less than 6 months left of Post-9/11 GI Bill benefits when you submit your application. Our system shows you have XX months, XX days remaining of GI Bill benefits.
    > 
    > If you apply now, your application will be denied.

5. In Form Chapter 3, Page 2:
    a. The content "STEM degree and school details" is replaced with "STEM degree and institution details"
    b. The content "What’s the name of the school where you plan on using the Rogers STEM Scholarship?" is replaced with "What’s the name of the school or training institution where you plan on using the Rogers STEM Scholarship?"
    c. The content "Your school ID and contact details" is replaced with "Your student ID and contact details"
    d. The content "Your school student ID number" is replaced with "Your student ID number"
    e. The content "Your school email address" is replaced with "Your student email address"

6. In the SCO email, the content

    > A student enrolled at your school has applied for the Edith Nourse Rogers STEM Scholarship.

    is replaced with

    > A student enrolled at your school or training facility has applied for the Edith Nourse Rogers STEM Scholarship.

7. If the applicant answers "yes" to the "Are you enrolled in a science, technology, engineering, or math (STEM) degree program?" question, the following content is included in the email that is sent to the SCO:

    > If the student is currently enrolled in an undergraduate program, please provide the following:
    > 
    > - Is the student pursuing a bachelor’s degree in an approved STEM program? ([Programs approved for the Rogers STEM Scholarship](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf))
    > - Name of STEM program student is enrolled in:
    > - 6-digit CIP Code for the program:
    > - Credit hours completed toward STEM program (specify semester or quarter):
    > - Required credit hours for STEM program (specify semester or quarter):
    >  
    > Note: If the student is enrolled in a dual degree program, at least one of the degrees must include an undergraduate degree in an approved STEM field. For dual degree programs, please provide the total credit hours required for the dual degree program as well as the credits completed toward the dual degree program when responding above.

8. If the applicant answers "yes" to the "Do you have a STEM bachelor’s or graduate degree and are now pursuing a covered clinical training program for healthcare professionals?" question, the following content is added to the email that is sent to the SCO:

    > If the student already has a bachelor's or graduate degree and is pursuing a clinical training program, please provide the following:
    > 
    > - Has the student earned a bachelor’s or graduate degree in an approved STEM program? 
    >    ([Programs approved for the Rogers STEM Scholarship](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf))
    > - Name of STEM program of degree conferred:
    > - Is the student currently enrolled in a covered clinical training program for health care professionals? 
    >    ([Programs approved for the Rogers STEM Scholarship](https://benefits.va.gov/gibill/docs/fgib/STEM_Program_List.pdf))
    > - Total length of clinical training program (in months or years):
    > - Amount of clinical training program completed to date (in months or years):

9. The ":" is not displayed with the following questions in the SCO email content:
    a. "Has the student earned a bachelor’s degree in an approved STEM program?:"
    b. "Is the student currently enrolled in a program leading to a teaching certification?:"

## Supporting Artifacts:
1. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/0c219b735879c20ffb26cd963dee11c70e132418/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content-v0.6.md)
2. [Email Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f225eff42c572b9786a8fd9300cdfa4457b13cee/products/education-careers/stem/stem-standalone-10203/content/stem-SCO-email.md)
3. [Prototype](https://bahdigital.invisionapp.com/share/8RIAGQUSXU3#/screens)

**Comment by ksantiagoBAH** [comment]
Vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17461
Vets-api PR: https://github.com/department-of-veterans-affairs/vets-api/pull/7121

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA. https://dsvavsp.testrail.io/index.php?/runs/view/1929&group_by=cases:section_id&group_order=asc
