### ISSUE TITLE
Education Applications - Definition of Child for Education Benefits for Booz Allen team

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#24614]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

**Johnny Isakson and David P. Roe, M.D. Veterans Health Care and Benefits Improvement Act of 2020 (P.L.116-315)**  is expanding the definition of who can be considered a dependent child for Chapter 33 Post-9/11 GI Bill education benefits.  

On the [1990e application](https://www.va.gov/education/apply-for-education-benefits/application/1990E/applicant/information), we are simplifying the dependent response to the question "What’s your relationship to the service member whose benefit is being transferred to you?" to "Child" but want to provide additional information to clarify who is considered a child for the purposes of this benefit. 

We are working with Education Service to track down specifics on this update.  In the interim we've been [using this document on benefits.va.gov ](https://benefits.va.gov/GIBILL/docs/IsaksonRoe/IsaksonRoeFactSheet.pdf) as a touchstone. See Sec. 1011
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

Understand the scope of eligible dependents for Chapter 33 benefits per Isakson-Roe Sec. 1011 
 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

Create the definition of "child" that encompasses all eligible non-spouse dependents.
The definition will be added to the 1990e benefit transfer application as an additional information component 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amyknox** [comment]
@bethpotts -  Could you hold on this effort until I have more info for you?    

When I reached out to our Education Service stakeholders to get more information on the updated definition for us to work from, they said it's still in the works.  They're also not sure yet that they want to include the definition in the 1990e.

**Comment by bethpottsVADEPO** [comment]
@amyknox Any update on this?

**Comment by amyknox** [comment]
@bethpotts I was expecting to hear today but we didn't get a response.  I'll ping you as soon as I know.

**Comment by amyknox** [comment]
@bethpotts - this work is OBE.  Per Education Service team: 

> We prefer to not provide further information for qualifying dependents.  The bottom line is that TOE is a DoD program, administered by VA.  DoD is the sole determiner of whether or not a dependent is eligible to receive transferred entitlement from a participating Service member.

Thanks for being ready to act on this!
