### ISSUE TITLE
Install monitoring on servers

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#24629]
- [ ] Install Agent

**Comment by shanemelliott** [comment]
Cannot find Arnaud Tako to assign to him

**Comment by Kennon-git** [comment]
waiting on token for Arnaud

**Comment by kjduensing** [comment]
Team dedicated to do monitoring systems. AVS/VEText on their list. Installed agent on staging server. Plan is to go with Dynatrace.
