### ISSUE TITLE
Add accessibility hint to out-of-app web links

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24623]
## User story
As a user who relies on screen reader tools, I want to know if a button or link is going to open in my device's browser, rather than open a page in the VA mobile app. 

## Acceptance Criteria
1. Tack on the following accessibilityHint to all buttons + links in the app which will open out-of-app in the device's browser:
     - accessibilityHint: "This page will open in your device's browser"
     - Note: this should **not** replace the existing a11yHints - it should be included after the existing a11yHint. 
2.  Sweep the app and apply AC 1 to all buttons + links where this will occur. This includes (but may not be limited to): 
    - Home > COVID-19 vaccines button
    - Home > COVID-19 screening tool
     - VCL > Start a confidential chat
     - VCL > VeteransCrisisLine.net
     - Letters > Benefit Summary & Service Verification > Send us a message
     - Settings > Privacy policy
     - Active Claim detail > Review locations button
     - Active Claim detail > What should I do if I disagree... > Learn about your decision review options
     - Active Appeal detail > Visit VA.gov
     - Null Appointments > Visit VA.gov
     - VA appointment cancelation > Unsuccessful cancel alert (if API does not return a phone number) > Find your VA location
     - Community Care & VAVC appointment cancelation card (if API does not return a phone number) Find your VA location
     - SM Unauthorized screen > Learn how to upgrade to a My HealtheVet Premium account

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
6/2/2021 @ 3:30 PM - Need to test the following yet:

- Active Claim detail > Review locations button
- Active Claim detail > What should I do if I disagree... > Learn about your decision review options
- Active Appeal detail > Visit VA.gov
- Null Appointments > Visit VA.gov
- VA appointment cancelation > Unsuccessful cancel alert (if API does not return a phone number) > Find your VA location
- Community Care & VAVC appointment cancelation card (if API does not return a phone number) Find your VA location
- SM Unauthorized screen > Learn how to upgrade to a My HealtheVet Premium account

**Comment by digitalken** [comment]
6/28/2021 - Not working:
- Active Claim detail > What should I do if I disagree... > Learn about your decision review options
- Null Appointments > Visit VA.gov

Bug is here:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26767

Not finding Active Appeal detail, Appointment Cancelations to test.

**Comment by digitalken** [comment]
PASS 7/22/2021 - Looks good for Appointment Cancelations, too.  Closing.
