### ISSUE TITLE
Update Call Center Number on "Check Post 9/11 GI Bill Benefits" Page

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#2463]
## What happened?
At the bottom of the statement of benefits page (https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit) we list a phone number where users can call to receive assistance. This phone number needs to be updated from an incorrect number to the education call center number. 

## Specs:
- Device: NA
- Browser: NA

## Steps to Reproduce
- URL: https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit
- At the bottom of the page, the current language reads 

"If none of the above situations applies to you, and you think your Statement of Benefits should be here, please call us at 855-574-7286.
If you have hearing loss, call TTY: 711."

## Desired behavior
The above paragraph should be replaced with the following text:

"If none of the above situations applies to you, and you think your Statement of Benefits should be here, please call us the GI Bill Hotline at 888-GIBILL-1 (888-442-4551).

## Acceptance Criteria
- [ ] Text has been updated based on what is outlined in the "desired behavior"
- [ ] Chante has reviewed the change

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by Karak888** [comment]
thanks @clantosswett will have it done as soon as possible!  @RLHecht can you please take a look at this one as well?  This was something that @lunascoop worked on, but assume fix needs to be made in Drupal?

**Comment by lunascoop** [comment]
@Karak888 I don't recall working on this. I worked on #2163 and #2243 .

**Comment by RLHecht** [comment]
@ncksllvn Here's another one where I can't find where this page lies. I don't see it in Education on Github and it's not in Drupal. If you steer me in the right direction I can make these changes. There are some style guide fixes that need to be done too (no vanity numbers and no periods after links).

**Comment by Karak888** [comment]
@RLHecht were you able to find any more information on this issue or no? Not sure if Nick was able to help you.  

@clantosswett I assume this is still occurring pretty regularly?  

Thanks!

**Comment by RLHecht** [comment]
@Karak888 I still need Nick or maybe @kelsonic to help me with this one. Not sure where the page lies for me to make the changes.

**Comment by clantosswett** [comment]
@Karak888 when you say occurring regularly, what do you mean? Basically this is a content update we need to make so that users are no longer calling the wrong number to get help when they are stuck or have questions. Hope this helps and let me know if you need additional information.

**Comment by kelsonic** [comment]
@RLHecht @Karak888 You can assign this to me 👍

**Comment by RLHecht** [comment]
@kelsonic When you make the change, please take out the vanity number and fix the text so it reads: If none of the above situations applies to you, and you think your Statement of Benefits should be here, please call the GI Bill Hotline at 888-442-4551. @clantosswett Should the TTY number still be included?

**Comment by Karak888** [comment]
Thanks @kelsonic @RLHecht! Please just let me know when you get to that so I can update on my end! thanks

**Comment by clantosswett** [comment]
@RLHecht the TTY number wasn't provided to us and as far as I can tell, there doesn't seem to be one, which isn't great. Also, could someone provide an estimated date for when this change will go live? I would like to update our stakeholders so they know when to expect the change. Thank you!

**Comment by RLHecht** [comment]
Thanks, @clantosswett. @kelsonic Please let me know once that text is updated. I can review it if you need to before merging PR.

**Comment by Karak888** [comment]
@clantosswett would you like to validate that everything looks good before closing out?  Thanks! 

thanks @kelsonic

**Comment by clantosswett** [comment]
@Karak888 I just noticed that the last part of the copy had an error in it (my fault, sorry!). It reads "...please call **us the** GI Bill Hotline at 888-GIBILL-1 (888-442-4551)." The "us" should be removed and it should read "...please call the GI Bill Hotline at 888-GIBILL-1 (888-442-4551)." Sorry about that and thanks for asking for a final review.

**Comment by RLHecht** [comment]
So sorry @clantosswett I thought we fixed that. @kelsonic Can you please go in to make these new changes. We need to take out the vanity number as well. The text should read: "<b>If none of the above situations applies to you, and you think your Statement of Benefits should be here, please call the GI Bill Hotline at 888-442-4551.</b>" Thank you! FYI @Karak888

**Comment by kelsonic** [comment]
Merged [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10968)! Should be on production tomorrow afternoon :)

**Comment by clantosswett** [comment]
Everything looks good to me. Thank you!

**Comment by Karak888** [comment]
closing out as completed and verified.
