### ISSUE TITLE
508-defect-2 [HEADINGS]: Introductory paragraph should not be a heading

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#24639]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## Details

Screen reader users use headings to quickly skim a page and understand its hierarchy. Headings can be thought of as a table of contents of a page. In this case, the introductory paragraph is not a semantic heading as it would create an unorganized and verbose table of contents for a screen reader user:

1. Answer psychiatry clinic questionnaire
  2. Please try to fill out this questionnaire before your appointment. When you tell us about your symptoms and concerns, we can better prepare to meet your needs.
    3. What happens after I answer the questions?
    3. How will VA protect my personal and health information if I answer these questions?

A more understandable table of contents for this page would aim to be more easy to skim and look something like:

1. Answer psychiatry clinic questionnaire
   2. What happens after I answer the questions?
   2. How will VA protect my personal and health information? 

<img width="1720" alt="Screen Shot 2021-05-12 at 5 35 57 PM" src="https://user-images.githubusercontent.com/14154792/118049821-4f0bec80-b34c-11eb-8954-03c89e12cb7e.png">

## Acceptance Criteria

- [x] Introductory paragraph is a `p`, not a `h2`
- [x] All headings below the introductory paragraph are bumped up by one level

## WCAG or Vendor Guidance
I recommend reading the following to understand heading semantics and usage.

* [WAI headings tutorial](https://www.w3.org/WAI/tutorials/page-structure/headings/)
* [G130: Providing descriptive headings](https://www.w3.org/WAI/WCAG21/Techniques/general/G130.html)

**Comment by mdewey** [comment]
Hey @joshkimux! This is staging and has been addressed.

**Comment by joshkimux** [comment]
Confirmed this has been fixed 🥳 
<img width="1605" alt="Screen Shot 2021-05-24 at 8 35 08 AM" src="https://user-images.githubusercontent.com/14154792/119348532-fea95e80-bc6a-11eb-8a7b-e7a0d9f64541.png">
