### ISSUE TITLE
[Bug] My VA - Health care appointments mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#24646]
## What happened?
On Staging **[My VA](https://staging.va.gov/my-va/)** (Dashboard) page, signed-in as **judy.morrison@id.me**, in **Health care** section, **Next appointment** card showed **7:20 a.m. MT** appt-time, but after clicking **Schedule and view...** link, on destination **VA appointments** page, under **Upcoming appointments** the 1st appointment showed **8:20 a.m. MT** appt-time.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: judy.morrison@id.me

## Steps to Reproduce
- URL: https://staging.va.gov/my-va/
- Test User _(if applicable)_: judy.morrison@id.me
- In **Health care** section, **Next appointment** card, note the **appt-time** (**7:20 a.m. MT**), then click **Schedule and view your appointments** link.
- On **VA appointments** page, under **Upcoming appointments** tab, observe that the 1st upcoming appointment's **appt-time** is mismatched (**8:20 a.m. MT**).

#### My-VA Next-appointment card
![my-va-bug-appt-times-a](https://user-images.githubusercontent.com/587583/118060574-e6227580-b347-11eb-9a24-19e85d2035aa.png)

#### VA-appointments upcoming-appointment card
![my-va-bug-appt-times-b](https://user-images.githubusercontent.com/587583/118060586-ec185680-b347-11eb-9338-8d9cb19fa1c6.png)

## Desired behavior
- [ ] My-VA's and VA-appointments' next/upcoming appointments should match (show the same appt-times).

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by erikphansen** [comment]
Good catch. And also 😱 time zones!! (╯°□°）╯︵ ┻━┻

**Comment by erikphansen** [comment]
This was _way_ more complex than I imagined it would be so I bumped the estimate.

**Comment by erikphansen** [comment]
@tlei123 this issue seems resolved on staging. But I did uncover a new bug that I am working on next https://github.com/department-of-veterans-affairs/va.gov-team/issues/25279

**Comment by tlei123** [comment]
@erikphansen, fix validated on Staging.  Thanks much!

**My VA**:
![image](https://user-images.githubusercontent.com/587583/119746811-286aad00-be46-11eb-9f3c-f9db7d91d18f.png)
**VA appointments**:
![image](https://user-images.githubusercontent.com/587583/119747021-a929a900-be46-11eb-8668-d40991c40bff.png)

cc @ajakabcin
