### ISSUE TITLE
[Bug] My VA - IE11 styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#24647]
## What happened?
In Internet Explorer 11, on Staging **[My VA](https://staging.va.gov/my-va/)** (Dashboard) page, in **Apply for VA benefits** section, appointment-/benefit-card's texts didn't wrap within the cards.

## Specs:
- Device: Windows 10 pc/laptop
- Browser: IE11
- Test User _(if applicable)_: `vets.gov.user+100@gmail.com`

## Steps to Reproduce
- URL:https://staging.va.gov/my-va/
- Test User _(if applicable)_: `vets.gov.user+100@gmail.com` (Norman)
- In **Apply for VA Benefits** section, observe the following styling anomalies:
  - In **Applications in progress** subsection, appointment-card titles spill-out beyond right-border of cards
  - In **VA Benefits you might be interested in** subsection, benefit-card body-texts spill-out beyond right-border of cards.

### Screenshot
![my-va-bug-ie11-styling](https://user-images.githubusercontent.com/587583/118063800-a317d080-b34e-11eb-85e1-0b27ab6fcf3d.png)

## Desired styling
- [ ] Appointment-card titles should wrap within cards.
- [ ] Benefit-card body-texts should wrap within cards.

## Acceptance Criteria
[see **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

**Comment by erikphansen** [comment]
@tlei123 Thanks for finding this. Can you recommend a good way for me to test vets-website running locally in IE11 on my Mac?

**Comment by tlei123** [comment]
> @tlei123 Thanks for finding this. Can you recommend a good way for me to test vets-website running locally in IE11 on my Mac?

@erikphansen , sorry, we may ultimately need to push to Staging before the fix can be validated.  In the meantime, I'm asking around for info/help, and I'll keep you posted.

**Comment by erikphansen** [comment]
This looks promising https://www.degdigital.com/insights/virtualbox-test-ie11-mac/ Not sure if the VirtualBox VM will allow me to connect to localhost running on the host Mac, though.

**Comment by tlei123** [comment]
> This looks promising https://www.degdigital.com/insights/virtualbox-test-ie11-mac/ Not sure if the VirtualBox VM will allow me to connect to localhost running on the host Mac, though.

@erikphansen , I recall trying this a couple years ago, and gave up exactly 'cuz of your concern -- it couldn't hit my vets-website from inside the VM.

@mpelzsherman , did you successfully log into local vets-website via BrowserStack?  [I lost Internet and couldn't follow-up w/ ya earlier.]  Erik needs to check authenticated My VA Dashboard on his local for this IE11 styling bug.

**Comment by mpelzsherman** [comment]
Yes, I have been able to use https://www.browserstack.com/open-source for local IE11 testing.

**Comment by erikphansen** [comment]
lol we are not alone.
<img width="616" alt="google autosuggest ie11 text not wrapping" src="https://user-images.githubusercontent.com/20728956/119246737-d883a180-bb38-11eb-87d2-3fb84187b225.png">

This is an IE11 flexbox issue. The fix seems simple. Make sure the parent of the non-wrapping block has its width set to 100%.

**Comment by erikphansen** [comment]
@mpelzsherman thanks for the BrowserStack lead! While I was waiting to get approved for the free open source account I tried working with Virtual Box and it was an absolute nightmare. Then I tried BrowserStack and it was like magic. Slow, yeah, but basically just worked. 🎉

**Comment by erikphansen** [comment]
@tlei123 a fix should be on staging in an hour or so.

**Comment by tlei123** [comment]
Validate fixed on Staging.

![image](https://user-images.githubusercontent.com/587583/119575793-6abfbb80-bd6c-11eb-9c4d-68659f48dfba.png)
