### ISSUE TITLE
Business intake form for VBA Education Service

### ISSUE THREAD

**Issue by bevnobev** [department-of-veterans-affairs/va.gov-team#24648]
## Requestor Name
Schnell Carraway

## Business Line
VBA Education Service                                   

## What is the business outcome you are trying to achieve? (required 1-2 sentences) 
We would like to send electronic benefit notification letters to our VET TEC graduates. The letter would include: a notification of receipt of application, certificate of eligibility or denial, award letter (at 3 intervals, enrollment, completion, and upon employment). Also attendees are required to verify attendance monthly, we would like to achieve this via monthly text alerts. 

## What is an overview of the notification use case? (required 3-5 sentences) 

Confirmation of receipt
Certificate of eligibility
Enrollment initial 25% payment sent
Completion next 25% payment sent
Employment final 50% payment sent

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 
The user will be notified at each interaction point, user will also be notified to certify monthly for the duration of their program . Programs range from 6 to 26 weeks in length. User will be notified of second and final payments along with next steps.

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 
Yes, these notifications are already being sent we would just like an electronic option.

## What kind of notification would this be? (required Email, Text, Not sure)
Email and/or text. Text could inform to check account (if applicable) to receive letters.

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure) 
Yes

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 
Vets.gov and LTS(Long Term Solution)

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 
Yes

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)
Yes

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)
Not sure – depends on cost

## What is your estimated volume of notifications per day, week, month? (optional - open space)
We typically have a budget that pays 2100 veterans per year. Which if averaged will be 175 vets per month for award letters. 1750 denial or coes per month. With 2100 monthly verifications.

## When does this notification need to be in production? (optional - open space)
We would like for this notification to be in place by the new fiscal year which begins on Oct 1st.

**Comment by miabecker** [comment]
@bevnobev Need to better understand their triggers from Vets.gov and if they are needing attachments in order to deliver letters.

**Comment by bevnobev** [comment]
Schnell is interested in sending a notifications for  VA Form 22-0994 completions.

**Comment by mjones-oddball** [comment]
Closing as they are inactive
