### ISSUE TITLE
[Bug] My VA - Health Care messages mismatch

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#24645]
## What happened?
On Staging **[My VA](https://staging.va.gov/my-va/)** (Dashboard) page, signed-in as **`vets.gov.user+377@gmail.com` (Kristie)**, in **Health care** section, **You have 3 unread messages** link opened a Secure Messaging page saying "**Welcome, Gehna**" and "**No Messages Found**."

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: `vets.gov.user+377@gmail.com` (Kristie)

## Steps to Reproduce
- URL: https://staging.va.gov/my-va/
- Test User _(if applicable)_: `vets.gov.user+377@gmail.com` (Kristie)
- In **Health care** section, click **You have 3 unread messages** link.
- On My HealtheVet **Secure Messaging** page, observe that:
  - page header shows **Welcome, Gehna**
  - messages table shows **No Messages Found**.

### Video capture

https://user-images.githubusercontent.com/587583/118058991-4e6f5800-b344-11eb-9f45-c993930d8021.mp4

## Desired behavior
- [ ] My-VA messages link should open Kristie's Secure Messaging page.
- [ ] My-VA messages link-text should accurately reflect Secure Messaging page's new-messages count.

## Acceptance Criteria
- [see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

**Comment by erikphansen** [comment]
@tlei123 I cannot replicate this anymore. User 377 does not have the `"messaging"` service so we no longer even try to fetch messages for that user. Do you know who we could ask to update User 377 so they _do_ have the `"messaging"` service as part of their `GET user/` response?

But I am also 99% sure this is simply a difference in the mock user data that's used on VA.gov vs. what's used by MHV.

**Comment by erikphansen** [comment]
I actually gave user 377 the `"messaging"` service using a Safari local override but then they get a 403 from the secure messages folder API. We've got an email thread trying to get to the bottom of this.

I _still_ think the data mismatch between VA.gov and MHV in staging does not point to a real problem.

**Comment by erikphansen** [comment]
A little birdie told me that user 41 might also have unread messages, but ID.me is preventing everyone from signing into staging right now.

**Comment by erikphansen** [comment]
This worked great for user 41 ¯\_(ツ)_/¯

https://user-images.githubusercontent.com/20728956/119399711-134b1e00-bc8e-11eb-83e9-4380ded23d73.mp4

I tried again with user 377, which is once again working correctly on My VA v2. But clicking on the 3 unread messages CTA link leads me to this error.

<img width="1220" alt="Screen Shot 2021-05-24 at 12 44 49 PM" src="https://user-images.githubusercontent.com/20728956/119399702-0f1f0080-bc8e-11eb-8a3e-e65cfb59032a.png">

**Comment by tlei123** [comment]
Just checked from my end, and now both 377 & 41 are blocked by that same My-HealtheVet error message shown above.  #HardNutToCrack

**Comment by erikphansen** [comment]
And now I'm getting this for user 41.

<img width="1301" alt="Screen Shot 2021-05-25 at 7 17 23 PM" src="https://user-images.githubusercontent.com/20728956/119592867-2218fa00-bd8e-11eb-95fb-19e523ffecc4.png">

**Comment by erikphansen** [comment]
@tlei123 can we call this one closed? I'm 99% sure this is an issue with the mocked data in our staging env not matching what is in MHV's staging.
