### ISSUE TITLE
Redirect Request: /initiatives/ empty directory

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#24655]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
All CLPs will live under a sub-directory of va.gov - www.va.gov/initiatives/.  That sub-directory will not have a landing page, so we need to redirect any visitors that land directly at that sub-directory back to the va.gov home page.   **This redirect cannot impact any child pages of the /initiatives/ sub-directory.**

### Requesting team info
VSP-IA

### Implementation date
Date new URL(s) will be live: Currently live

Please indicate when the change/redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing :  Can be implemented at anytime

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination 
---  |  ---
www.va.gov/initiatives/ | www.va.gov

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [x] Implementation team: Implementation team completes work 
- [x] Implementation team: Implementation pushed live and redirect is validated in production
- [ ] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
@brianalloyd This can be implemented at any time.  This will ensure no users that land directly at the /inititiatives/ sub-directory either by error or through URL hacking, will receive a 404 error. 

cc @johnhashva FYSA

**Comment by brianalloyd** [comment]
Thanks @mnorthuis we'll get this programmed into next sprint for action.

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/9208

**Comment by brianalloyd** [comment]
@mnorthuis I believe this is ready for validation if you would like to review.  Thanks.

**Comment by mnorthuis** [comment]
So sorry I didn't review this in a timely manner!  It looks good, but you already knew that! :-)

**Comment by kelsonic** [comment]
Oops I was cleaning up my board and must have moved it without thinking, sorry! 😂  Awesome, happy to hear that!

**Comment by brianalloyd** [comment]
Thanks @mnorthuis appreciate it. Good work @kelsonic
