### ISSUE TITLE
Design workshop for tier 2 content design & IA

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#2466]
## The goal/outcome of this 2-day design workshop is to come out with concepts for a first draft wireframe of IA, content design, and page template(s) for tier 2 content on VA.gov. 

@rtwell @JeffBarnesUSDS  @lalexanderson-dsva @mnorthuis @kevwalsh @andrewlewandowski  Early scattered thoughts to get us brainstorming... Not in any order of importance:

1. Rethink/modify the "More resources" spoke to accommodate possibly:
- a) Deep linking to tier 2 content detail page?
- b) Top level linking to tier 2 content landing page? (Could we use our 'hub/spoke' model here?)

2. Tier 2 content landing page or 'hub' - i.e., the default landing page for a tier 2 content 'Resources/Learning' center
- How/where would be the access path to this new tier 2 hub/landing page - from mega menu? on page hub nav only? from benefit hub page? 

3. Tier 2 content detail page(s) - maybe 1-3 types of page templates based on main type of content (e.g., wikipedia type of 'about' page vs. FAQs page vs. step-by-step tutorial vs. checklists)?
- Each type of detail page template should have certain elements that are rigid and common to all tier 2 detail pages, such as:
- CTA to a benefit page
- CTA to a tool sign in
- Was this page helpful? feature
- Summary or 'What is this page about?' element (or we could just re-use the TOC jump links to provide this value?)
- More to come via whiteboard upload...

This is part of [Epic 2281 Create tier 2 content experience](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2281)

Product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design

@Karak888 - FYSA

**Comment by jenniferlee-dsva** [comment]
@Karak888 - this is happening next week, so I think it along with the epic can come out of ice box and into backlog. Thank you!

**Comment by Karak888** [comment]
work on this will not begin until 10/21

**Comment by Karak888** [comment]
closing this and will follow up with next  tasks
