### ISSUE TITLE
QA Feedback - Staging Review - Healthcare Experience - Questionnaires

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#24674]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
QA feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/24145.

- Great work on the comprehensive QA for this feature!
- TestRail test cases include links to zeplin.io, which require a login. Are these credentials shared anywhere?

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Questionnaires that have not been started but have an expiration date in the past still appear in the `To do` tab. The user can click on `Answer questions` for this questionnaire, but the questionnaire can't be completed because it is expired. Determine if expired questionnaires should still appear in the `To do` tab.
- Address content/styling issues mentioned in https://github.com/department-of-veterans-affairs/va.gov-team/issues/24417.

**Should:**
- When the user clicks `Add another Question` without inputting anything for the first question, an empty box with an `Edit` button appears for the first question. This box should include a message to enter a question. 

<img width="540" alt="Screen Shot 2021-05-13 at 9 26 08 AM" src="https://user-images.githubusercontent.com/3535749/118140025-96868d00-b3cd-11eb-8803-6bb081dc450c.png">
- When adding a second question, there is no button to save the question. Pressing the Enter key continues to the next step in the questionnaire. The user should have a way to save the question that they enter. 
<img width="528" alt="Screen Shot 2021-05-13 at 9 29 18 AM" src="https://user-images.githubusercontent.com/3535749/118140334-e5342700-b3cd-11eb-89c4-90983957d312.png">
- When more than two questions are added to the questionnaire, the UI is inconsistent for the first and following questions. The UI should appear more consistent for these questions. 
<img width="539" alt="Screen Shot 2021-05-13 at 9 31 13 AM" src="https://user-images.githubusercontent.com/3535749/118140593-1dd40080-b3ce-11eb-9a78-83102f3f9fe8.png">
- If the user clicks `Add another Question` without entering anything for the new question, this new question appears with an empty field on the review page. Determine if empty questions should be removed from the review page. 
<img width="573" alt="Screen Shot 2021-05-13 at 9 34 19 AM" src="https://user-images.githubusercontent.com/3535749/118141049-95a22b00-b3ce-11eb-941c-8fcd63e907de.png">

**Consider:**
None

**Comment by tlei123** [comment]
@mdewey , as you work with Platform Forms and/or Design Systems teams to address the List-loop gap(s), please keep me in the loop.  I very curious how this process goes.  Thx much!

**Comment by mdewey** [comment]
Just to keep track: 

Task:
- [x] The list loop is going away and being replaced with a text area
- [x] IE fixes are staging. 
- [ ] hide appointments in the past that are expired.

**Comment by mdewey** [comment]
@ddzz  Good Morning :-) All the addressed feedback is in staging.

**Comment by tlei123** [comment]
@pjhill @ddzz , both **MUST** items have been addressed, thx to @mdewey .
- #24417 now fixed, validated & Closed
- Expired questionnaires now hidden on list-page -- only ones w/ future Complete-by dates are displayed.  [See screenshot below].

![image](https://user-images.githubusercontent.com/587583/119585440-8ed8c800-bd7f-11eb-9fed-817376551594.png)

cc @leahkeeler [couldn't find Corey Parker]

**Comment by tlei123** [comment]
@leahkeeler [& Corey Parker] @mdewey , I'll leave it to your Team to address the **Should** item(s), but pls. keep me in the loop in case you make changes, so that I can update my test-cases and do quick re-tests.  Thx much!  :)

**Comment by mdewey** [comment]
@tlei123  We have addressed **shoulds** by removing the list loop and using a text area instead. Not sure how that will affect your tests. Let me know if you have any questions

Are we good to close this ticket @ddzz?

**Comment by tlei123** [comment]
> @tlei123 We have addressed **shoulds** by removing the list loop and using a text area instead. Not sure how that will affect your tests. Let me know if you have any questions

Thx, @mdewey !  yeah, i'll update my test-cases & re-test the Add'l qstns feature.  Stay tuned!

cc @ddzz

**Comment by tlei123** [comment]
@pjhill @ddzz , new follow-up test-run added to [test plan](https://dsvavsp.testrail.io/index.php?/plans/view/1215) -- no defects logged.  [Follow-up Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/238) generated.

@leahkeeler [couldn't find Corey Parker], this QA-Feedback ticket can be Closed.  cc @mdewey

**Comment by pjhill** [comment]
> @pjhill @ddzz , new follow-up test-run added to [test plan](https://dsvavsp.testrail.io/index.php?/plans/view/1215) -- no defects logged. [Follow-up Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/238) generated.
> 
> @leahkeeler [couldn't find Corey Parker], this QA-Feedback ticket can be Closed. cc @mdewey

Thanks for working as a team to close out these issues — great work!
