### ISSUE TITLE
Contact Center Review for [Caregivers - Sign as a Representative]

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#24680]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
- The Sign as a Representative feature is being added to the [Family Caregiver Application](https://www.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/). This feature will allow caregivers who have Power of Attorney (or similar) status for their Veteran to upload documentation relating to their legal status and sign the form as the Veteran's representative.  

### Launch Date
- We are targeting a 50% rollout on Monday, May 17th (we don't expect many users of this functionality) and a 100% release the week after that (Monday, May 24th)

### Version Number
*I believe this will be the third version of the Product Guide that we've submitted.*

### Product Guide

- [Online-10-10CG-Product-Guide-Updated-05.12.2021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6473296/Online-10-10CG-Product-Guide-Updated-05.12.2021.docx)

- Note: this is still a draft; we are awaiting final feedback from the Caregiver program team.

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Hi @ala-yna. Thank you for sending this over. I will review and provide comment as soon as I can. For the future, please keep in mind that we typically need a 1-2 week turnaround time. That includes VEO review. I notice you're planning to begin launch on 5/17...

**Comment by ala-yna** [comment]
Thank you so much! Unfortunately we were unable to turn this in earlier, since the changes to the guide were dependent on the functionality being built out. I got the go ahead from @Kimberley2019 this morning to release on Monday, but to expect to make any feedback to the Product Guide next week. We did receive some feedback on the Product Guide from the Caregiver program, so I'm attaching the most recent version here. Thank you!
[Online-10-10CG-Product-Guide-Updated-05.14.2021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6480511/Online-10-10CG-Product-Guide-Updated-05.14.2021.docx)

**Comment by starlow00** [comment]
Hello @ala-yna. I've attached a draft with my edits. Please let me know if you have comments/questions, and confirm if all is good. There is one comment that will require your input, and I can update that in the draft sent to VEO. 

[Online-10-10CG-Product-Guide-Updated-05.12.2021_ST_051421.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6481286/Online-10-10CG-Product-Guide-Updated-05.12.2021_ST_051421.docx)

**Comment by starlow00** [comment]
Hi @ala-yna . Just checking in to see if you've had a chance to review the draft I sent.

**Comment by ala-yna** [comment]
Hi @starlow00 - yes! Your changes look great. I'm just working on combining the edits you made with the ones we made based on the Caregiver program team's feedback - the merge is proving a bit tricky. I'll get it back to you ASAP!

**Comment by ala-yna** [comment]
Hi @starlow00 please take a look at the revised product guide and let me know if you have any questions/edits. This incorporates the feedback from the Caregiver Program folks as well.

[Online-10-10CG-Product-Guide-Updated-05.20.2021.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6517355/Online-10-10CG-Product-Guide-Updated-05.20.2021.docx)

**Comment by starlow00** [comment]
Thanks, @ala-yna . This looks good! I'll share with VEO for their approval.

**Comment by starlow00** [comment]
Sent to VEO for review.

**Comment by ala-yna** [comment]
FYI - re-attached the file to the comment above - there were some comments that were still included in the document, which I marked as resolved.

**Comment by tchrisdyer** [comment]
Hi all, my name is Chris Dyer and I'm taking over as Product Manager from Alayna Abel. I'm just following up with this to see if there are next steps or whether we can close this ticket. Let me know.

**Comment by starlow00** [comment]
Hi @tchrisdyer  VEO had no changes to the guide, so it is posted and ready at https://dvagov.sharepoint.com/:w:/r/sites/VACOveohotline/Training%20Files/KM%20Docs/VA.GOV/Product%20Guides/Caregiver%20Benefits%20Application%2010-10CG/Caregiver-Benefits-Application-10-10CG-Product-Guide.docx?d=w4ae743a04cf14fe7a4aebd202113dfa7&csf=1&web=1&e=ikMybZ.

I've closed the ticket, but feel free to re-open if you see the need. Just let me know if so.
[Caregiver-Benefits-Application-10-10CG-Product-Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6594274/Caregiver-Benefits-Application-10-10CG-Product-Guide.docx)
