### ISSUE TITLE
Homepage Refresh-E2E Staging testing request

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24686]
## Summary
Request for end to end testing for the homepage refresh work in Staging to identify any bugs prior to launch.

The following pages are included the scope of this initiative:
- VAOS homepage (appointment list)
- Appointment detail pages (new functionality)
- Appointment confirmation pages

Related issues are listed in this epic #19237

### VA.gov Feature Toggle
`va_online_scheduling_homepage_refresh`

Toggle is currently ON in [Staging](https://staging.va.gov/)

### Designs & Copy
- All specs for dev: https://www.sketch.com/s/4198dca5-69c7-4769-9686-d213c900876d

## Tasks
- Run Mobile and Desktop E2E tests
- Attach spreadsheet(s) of test cases
- Document bugs in GitHub using the [VAOS Bug Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=laurenernest&labels=bug%2C+vaos&template=vaos-bug.md&title=) and assign to @laurenernest for review and prioritization
- Document questions that arise (in this ticket or attach a separate doc)

## Recommended Scenarios

- [ ] Homepage
- Upcoming
- Requested/pending
- Past
- Canceled

- [ ] Appointment cards and details in different statuses
- VA in person
- VA phone
- Community Care
- VVC ATLAS
- VVC home
- VVC VA device
- VVC VA location
- COVID-19 vaccine

- [ ] Confirmation pages
- VA in person request
- VA in person self schedule
- VA phone request
- Community Care request
- VVC request
- COVID-19 vaccine self schedule

## Known Issues
None

## Additional Notes
- Here's a [Cypress best practices document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-best-practices-on-vsp.md#viewport-presets-cyviewportpresetpreset-orientation-options) that includes notes on how to test multiple views.

**Comment by laurenernest** [comment]
@marcynadeau can you please upload and/or link the test cases/test plan with test execution logs that you used for this?

**Comment by marcynadeau** [comment]
@laurenernest This page has a link to the test scripts. https://wiki.mobilehealth.va.gov/display/VAOSR/Regression+Test+Scripts

Will this work?  Or do you want me to upload each of the scripts this ticket?

**Comment by laurenernest** [comment]
@marcynadeau can you upload the scripts you used related to this initiative? our platform folks don't have access to the wiki.

**Comment by marcynadeau** [comment]
Sorry this took so long. I was on vacation and thought I had this covered while I was out.  Here are the scripts.  [https://app.zenhub.com/files/133843125/e9c27ee2-8d00-442f-9fcb-52844e20affc/download](https://app.zenhub.com/files/133843125/e9c27ee2-8d00-442f-9fcb-52844e20affc/download)[https://app.zenhub.com/files/133843125/744388fc-1ed3-4965-a304-5eb6d6f19396/download](https://app.zenhub.com/files/133843125/744388fc-1ed3-4965-a304-5eb6d6f19396/download)[https://app.zenhub.com/files/133843125/be69381d-0928-4fe8-bf53-f202c7605795/download](https://app.zenhub.com/files/133843125/be69381d-0928-4fe8-bf53-f202c7605795/download)

**Comment by laurenernest** [comment]
Defects found:
#25609
#25598
#25601
#25613
#25579
#25087
#24964
#25084
#25078
#24971
#24965
#24966

**Comment by pjhill** [comment]
> Defects found:
> #25609
> #25598
> #25601
> #25613
> #25579
> #25087
> #24964
> #25084
> #25078
> #24971
> #24965
> #24966

Thanks for the summary!
