### ISSUE TITLE
Programmatically Create Endpoint to Product mapping (Distributed Tracing)

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#2469]
## User Story or Problem Statement
As a developer, I need to understand the what products are hitting an endpoint so I can better troubleshoot issues

As a member of the analytics and insights team, I need to link products to their relevant endpoints so I can show application teams that data on the Grey Sky tool.

## Goal
Have a always up to date list, that is programmatically generated that shows which products are utilizing which endpoints.  There is currently no known list that is maintained with this information that is easily accessible by all users.

## Objectives or Key Results this is meant to further
- Programmatically create a list of all endpoints
- Programmatically capture which products utilize each endpoint
- Allow this mapping to be easily accessible for Grey Sky and other tools

## Acceptance Criteria
- [ ] Mapping of Endpoints and Products is accessible 

## Two Possible Approaches
**Using Headers**
Each front end application has its own dedicated javascript bundle. In the "bootloader" we could have a global variable that is defined for the application which is then read by the api request helper to inject whatever we need it to (probaby in the headers). This would require
- Modifications to the common API request handler
- Looking for any application that doesn't use that common helper (need to verify all of them)
- Modifying each application to bootstrap that variable so we can send the product information.

This should take maybe 3 days at most for the changes on the front end.

We'd still need a way to consume the data. (The rev proxy might be the place to do this.)

**Using the Rev Proxy**
Needs further details

## Questions
How does Grey Sky (or other tools) intend to use/ingest that information.

## Other possible opportunities

Products to vets-api endpoint - Routing to the correct product owners, allow for more sophisticated code ownership processes.

Improve our risk assessment based on endpoint usage and usage pattern.

Automatic routing (phase 2)

scythe, staccato-rails

Visualization map of products.

**Comment by omgitsbillryan** [comment]
In the revproxy, we already keep track of the "component" being called. [Here is the list of components](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_components.yml#L7-L37).

I like the idea of `vets-website` setting a header on each request made to `vets-api` that says which product this request came from. e.g.

`'vets-website-tool': 'post911_gi_bill_status'`

If this header existed, we could then start to formulate promQL queries that cross reference which FE products are hitting which BE endpoints.
