### ISSUE TITLE
Unit test for liquid.filters.toTitleCase

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#24694]
Add unit tests for [liquid.filters.toTitleCase](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/filters/liquid.js#L91) covering the following cases

- null => null
- "" => ""
- [] => ""
- "tEST" => "Test"
- "t3sT String" => "T3st String"

- Modify the function as needed so the tests pass
- Consider using lodash [upperFirst](https://docs-lodash.com/v4/upper-first/)

## Acceptance Criteria

- All tests pass

**Comment by gescobardev** [comment]
PR ready for review
https://github.com/department-of-veterans-affairs/content-build/pull/157
