### ISSUE TITLE
[Design] Preferred Facility: Update FE documentation post-content & IA review

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24697]
## Background
Following completion of content and IA review of preferred facilities/your health facilities (#23288), there are some updates needed to the FE documentation.

## Tasks
- [x] Update [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/frontend/design-specs.md) per final [IA recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/auth-profile-your-facilities.md)
- [x] Update content documentation per content feedback

**Comment by andaleliz** [comment]
Updated #24696 to capture this change; closing since its duplicative.

**Comment by andaleliz** [comment]
Arg! Too many tabs. Closed this by mistake.

**Comment by andaleliz** [comment]
Completed.  May need to do another round of updates based on the outcome of our usability study w/ VAOS
