### ISSUE TITLE
Review VA Profile changes impacts to Identity

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#24692]
Need a review of the docs in https://github.com/department-of-veterans-affairs/va.gov-team/issues/24182

Essentially they impact how va.gov applications (through vets-api) make calls to VA Profile (the backend not va.gov profile). We are also going to have a rate limit per application to VA Profile which we need to be aware of. This should not directly impact anything within Identity right now, but likely will during future iterations with VA Profile.

**Comment by nsoutouras** [comment]
12/13/21 Planning: We are confident the changes have already gone through and the ticket was not updated.  Closing.
