### ISSUE TITLE
Combine Incident Response Playbooks

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#247]
We have two copies of the Incident Response Playbook with slightly different information.  They should be combined. 

https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Incident%20Response%20Playbook.md

https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/OnCall/Incident%20Response%20Playbook.md

**Comment by alexpappasoddball** [comment]
7/1/19 - Triage team needs to make sure this is still timely.

**Comment by mnorthuis** [comment]
Removing this into the new repo org epic and keeping in the backlog.  Content should be reviewed by the appropriate team, and determine where this content should live and what is the single source of truth.

**Comment by LindseySaari** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/1318/commits/219117648e3c1ac4f74ce28f9de10be7240b8adc

**Comment by LindseySaari** [comment]
We had two copies of the triage incident response playbooks. This change consolidates the playbooks into one location in the va.gov-team repo. 

These response playbooks are depreciated https://github.com/department-of-veterans-affairs/devops/blob/master/docs/Incident%20Response%20Playbook.md
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/OnCall/Incident%20Response%20Playbook.md


New location will be in the va.gov-team repo /platform/teams/triage/incident_response_playbook.md  https://github.com/department-of-veterans-affairs/va.gov-team/pull/1318/commits/219117648e3c1ac4f74ce28f9de10be7240b8adc
