### ISSUE TITLE
Staff list showing unpublished content.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#24708]
## What happened?
Pages listing staff profiles (content type: leadership_listing) are not filtering the list based on the published status of the data in the CMS.  As a result we end up with staff being listed whose profiles have been archived and creating broken links to profile pages that do not exist.
![image](https://user-images.githubusercontent.com/5752113/118198423-d4f86800-b41e-11eb-8131-75ba8270972a.png)

The root cause is the query for the list of staff profiles is not filtering by published.

Workflow notes:

- Draft content which has never been published should not be displayed. 
- Published content which is being edited will be in draft (temporarily). The previously published version of that content should still be displayed during the editing process. 
- Preview server disables "isPublished" filter (therefore draft/archived content can still be viewed)

**Recommendation:** 

1. Check each item in `fieldLeadership` and only render if it is not NULL and `status` = true.
2. When rendering the anchor, do not build the anchor if the is no url for the href.

## Steps to Reproduce
- Archive a staff profile in the CMS
- Trigger a content release
- see broken links reported.

## Desired behavior
Only published staff profile pages are listed on the listing pages.

## Acceptance Criteria
- [x] Only published staff profile pages in fieldLeadership are listed on the listing pages.
- [x] Null entries for fieldLeadership produce no html.
- [x] anchors are not built if no href is present.
- [x] Add/update [documentation, for example](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/README.md) as needed

**Comment by acrollet** [comment]
Update: the staff profiles in question have been deleted. However, links with no `href` are still generated on https://www.va.gov/palo-alto-health-care/leadership/, generating broken link errors and odd spacing:

<img width="1246" alt="Screen Shot 2021-05-14 at 7 24 49 AM" src="https://user-images.githubusercontent.com/101649/118278205-fbea8480-b486-11eb-8839-f721d32209ef.png">

**Comment by swirtSJW** [comment]
A different view of what @acrollet  is showing 
![image](https://user-images.githubusercontent.com/5752113/118281803-9f459480-b49b-11eb-9129-e6a1cb96223d.png)

**Comment by swirtSJW** [comment]
After some great sleuthing by @acrollet we determined there are three issues that need resolving.

**Front End**
1. When looping through the results of `field_leadership` (fieldLeadership) Only items  that have isPublished = 1/true should be rendered.   NULL or false should not be rendered.  
2. If there is no url for the href, do not attempt to build the anchor tag.


**CMS**
1 Upon delete of a staff profile node, the listing entity is not saving to remove the empty entry from field_leadership, which results in a NULL entry being present in the graphQL query for fieldLeadership.

**Comment by mpelzsherman** [comment]
Unless I am mistaken, the issue with empty anchors should be addressed by the filtering of the unpublished bios in the fieldLeadership array. We could “go the extra mile” here and do a null check in our bioParagraph.drupal.liquidtemplate. However, my feeling is that again, doing so would mask a problem with the data. We should not have bios with null entityUrls, and if we do, that should be flagged by the broken link checker. So I’m recommending we remove that AC item.

See tugboat instance: https://web-7gb5iotuvt47rpo6jcdienuwvjyblpan.demo.cms.va.gov/palo-alto-health-care/leadership/

**Comment by mmiddaugh** [comment]
Looks good! 
Daniel Kulenich and Kandace Woodruff are both archived in CMS. Neither appear on Palo Alto leadership page: 
![image](https://user-images.githubusercontent.com/55411834/119897550-d08f7d00-befd-11eb-9963-9a4231ba534f.png)
