### ISSUE TITLE
[FE] My VA: Change keyboard focus to start in the banner/disability rating

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#24714]
## Background

While running accessibility tests, I noticed the keyboard focus starts on 'Go to your profile'. After a [conversation with Trevor/Josh](https://adhoc.slack.com/archives/C6NT0TTU3/p1620938507183500), we need to change the focus to start on the banner/disability rating.

We decided to go with the following direction from Trevor.

What do you think about a `<section aria-label="My status and disability rating">...</section>` instead of an article? My understanding of the section/article difference is not nuanced, but this feels like a logical landmark, but not quite one that stands on its own. More of a relationship to the main content.

## Tasks

- [ ] Update keyboard focus
- [ ] Validate with Tressa or AJ

**Comment by tressaellen** [comment]
@erikphansen - I added some details about what direction trevor/josh landed on. Let me know if you need anything else here. Thanks!

**Comment by erikphansen** [comment]
@joshkimux this should be ready to validate on staging. When the My VA Dashboard loads focus is on the "name tag" component (specifically on the Veteran's name) and the markup has been changed.

**Comment by erikphansen** [comment]
Hi @joshkimux 👋 I just realized you were on PTO when I pinged you about validating this earlier this week, so this is me asking you to take a look when you can. Thanks!

**Comment by joshkimux** [comment]
@erikphansen great work! It's working wonderfully.

https://user-images.githubusercontent.com/14154792/121042976-3394d580-c782-11eb-92ff-133a8e0f2e87.mov

A weird bug did pop up though when I was testing with user 226 where content was set to Spanish. 
<img width="1462" alt="Screen Shot 2021-06-07 at 11 18 47 AM" src="https://user-images.githubusercontent.com/14154792/121043020-414a5b00-c782-11eb-9c9b-2e96e3b8a5c7.png">

**Comment by erikphansen** [comment]
What is the implication of this? I'm guessing that when `lang="es"` gets added to that wrapper div screenreaders will pronounce all the English text incorrectly?

**Comment by joshkimux** [comment]
@erikphansen Correct, it will pronounce at in a Spanish accent making the English incomprehensible. Not sure how it ended up here though in this instance.

**Comment by erikphansen** [comment]
@youngfreezyVA Sorry to bring you into this mid-stream, but it looks like the translation work you've been doing is maybe affecting pages that it shouldn't?

1. Sign into staging with any user
2. Go to /my-va
3. Switch the language to Spanish
4. Return to /my-va and notice that `lang="es"` is set on the `div#content`

This also affects the /profile, so this is probably pretty widespread.

I know virtually nothing about the work you are doing other than you've been involved with this translation stuff. Let me know what you think.

**Comment by erikphansen** [comment]
@joshkimux Thanks for catching this, but this likely has nothing to do with my work. We might need to make a new bug ticket for @youngfreezyVA . So lets leave this open until we figure out how to track this issue you found.

**Comment by youngfreezyVA** [comment]
> @youngfreezyVA Sorry to bring you into this mid-stream, but it looks like the translation work you've been doing is maybe affecting pages that it shouldn't?
> 
> 1. Sign into staging with any user
> 2. Go to /my-va
> 3. Switch the language to Spanish
> 4. Return to /my-va and notice that `lang="es"` is set on the `div#content`
> 
> This also affects the /profile, so this is probably pretty widespread.
> 
> I know virtually nothing about the work you are doing other than you've been involved with this translation stuff. Let me know what you think.

hi @erikphansen thanks for pointing this out, and yes this appears to be a [bug from the stuff that I was working on](https://dsva.slack.com/archives/C01GCADCMQT/p1622731916139800?thread_ts=1622673853.134600&cid=C01GCADCMQT).

some questions for debugging:

Just to clarify, this is when clicking spanish in the footer right?

how is the user returning to my-va in number 4 above? back button, or directly pasting in the url (or both)?

**Comment by erikphansen** [comment]
@youngfreezyVA

1. Yes, I'm clicking `Español` in the footer
2. Yes, clicking the "back" button, or clicking My VA in the main nav, when on https://staging.va.gov/asistencia-y-recursos-en-espanol/

Interesting that if you click on My VA again, while on the My VA page, the language gets reset back to `en`

**Comment by youngfreezyVA** [comment]
awesome, thanks! I believe [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17524/files) should address it. pls lmk if you continue to see it after the daily deploy tomorrow.

**Comment by erikphansen** [comment]
I'm not seeing the problem anymore, @youngfreezyVA. @joshkimux I'm going to close this because you validated the fix and the new issue you found didn't have anything to do with this ticket and appears to be fixed :)

@youngfreezyVA : I did notice that it looks like the breadcrumbs on https://staging.va.gov/asistencia-y-recursos-en-espanol/ do not have a `lang="es"` attribute applied to them. I have no idea if that's a new thing.
