### ISSUE TITLE
Intake Request: Add VA IPv6 Policy Page to VA.gov 

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#24711]
## Why you're here 

**Note: These requests are handled by the Public Website Team.** 

## How to submit your request
- Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.
- [ ] Determine if this request is for:
     - [ ] Content Only      
     - [ ] Public Website Engineering Support      
     - [X] Both (Content + PW Eng Spt)   
- [ ] Post a link to this issue in the appropriate channel: For Engineering only requests: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @ncksllvn and @kelsonic. Content only support: [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) in Slack, tag @RLHecht.  In situations where both are needed post to Public Websites and in Slack tag @brianalloyd, @ncksllvn, @kelsonic and @RLHecht for awareness.  

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * No
* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * N/A

---

## About your support needs
*Please select all that apply, and follow related guidance.* 

### Content
     
- [X] **New unauthenticated VA.gov page**
   * **Additional info.** Please provide any details not covered above about what app/tool/other need this new page will support. 

The Office of Management and Budget’s IT policy shop is requiring VA and other agencies to publish on their Websites information about the transition to IPv6, the current standard for identifying systems and devices communicating with and over the internet. 

More background here: https://www.nextgov.com/it-modernization/2020/03/omb-ipv6-transition/163459/

There is no explicit requirement or guidance about where this information page should go.
      
   * **Schedule a meeting.** Please schedule a meeting with @RLHecht and @brianalloyd to kick off this work. We'll work with your team and the VSP IA resource to determine how best to accommodate this new page.  

- [ ] **Updates to an existing unauthenticated VA.gov page**
   * **What URL(s) do we need to review or update?** 
      * While a decision needs to be made, one possible placement for this page could be a link from https://www.va.gov/privacy-policy/#other-va-policies in the "Other VA policies" section.  Copy to be provided by OIT/CIO.
      * 
   * **Are updates for a small section of copy?** If yes, please tell us what new info we need to consider and what (if anything) it's replacing.
      * This will be one page of copy from VA OIT/CIO office.
 

### Frontend engineering support 

- [X] **New URL or redirect requests**
   * **Have you vetted this request by the VSP IA team?:** 
     - No, needs to be reviewed/vetted by Sitewide IA.
   * **Link to VSP IA redirect request ticket:** 
     - < Github issue link >
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* <Desired/target implementation date>

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: Public Website
- DEPO product owner: John Hashimoto
- Product manager: Brian Lloyd
- Designer: Cassandra Allen
- FE engineer: Kelson Adams
- Product/team Slack channel: #vsa-public-websites

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by RLHecht** [comment]
Thanks @johnhashva ! Is this a page that OIT/CIO is writing and we need to put it into Drupal and rework into plain language and VA voice and style, or is it us just finding where we should be linking to their page?

**Comment by johnhashva** [comment]
@RLHecht (with @brianalloyd) -- I believe the policy can not be changed language wise -- we just need to find a place where we can link from VA.gov (and create a simple page with the text).  Should we get the IA team involved (MegMikki)?

**Comment by johnhashva** [comment]
@brianalloyd and @RLHecht here is the FINAL VA MEMO that should be used as the text for the new page.  (I've asked for Word version and will post here when received).  @brianalloyd we will need IA guidance as to where to put this page.

[Memo for IPv6 Policy - 05122021 - v6.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6510990/Memo.for.IPv6.Policy.-.05122021.-.v6.pdf)

**Comment by johnhashva** [comment]
And here is the Word doc version @RLHecht and @brianalloyd 
[V05135661_For CIO Signature (Word)_VA Internet Protocol Version 6 (IPv6) Transition Procedures Memorandum.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6511231/V05135661_For.CIO.Signature.Word._VA.Internet.Protocol.Version.6.IPv6.Transition.Procedures.Memorandum.docx)

**Comment by johnhashva** [comment]
Update: I'm negotiating to see if we can have this memo (now that I've reviewed more closely) posted at oit.va.gov (natural fit) -- and if we absolutely must, simply link to it from here https://www.va.gov/privacy-policy/#other-va-policies.   Stay tuned.

**Comment by johnhashva** [comment]
5/21 Update @RLHecht and @brianalloyd -- This memorandum will now be posted on the oit.va.gov Website by Stephen Walker's team.   Once that is live, I need to get IA approval to add a link to the memo/page from here https://www.va.gov/privacy-policy/#other-va-policies

**Comment by johnhashva** [comment]
Update: @brianalloyd and @RLHecht Page is up at the [OIT website here ](https://www.oit.va.gov/omb/ipv6/).  I will follow up with Meg/Mikki to get their take on the VA.gov link and post that update here.

**Comment by jenniferlee-dsva** [comment]
FYSA - we usually link to policies from the existing privacy and policies page. There is a section there called "Other VA policies": https://www.va.gov/privacy-policy/#other-va-policies

I don't know if this situation fits, but worth considering.

**Comment by johnhashva** [comment]
Final update and closing: Confirmed with VA OIT lead there is no need for a VA.gov link now that the page is posted on the OIT site.

**Comment by brianalloyd** [comment]
Thanks for confirming @johnhashva
