### ISSUE TITLE
Misc. copy changes

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24716]
## Acceptance Criteria
1. On Onboarding Screen #2 ("Easily manage your health appointments"), remove the first bullet point from the list:
     - Delete: "• Schedule some appointments"
2. On the SM Inbox null page, implement the following change:
     - Old copy: "and medication renewals"
     - Replace with new copy: "and medication refills" 

**Notes for testing:**
Use the following test user for AC #2: +264

## Designs
AC #2: https://adhoc.invisionapp.com/console/MVP-Secure-Messaging-Mobile-App---Design-Handoff-cknr12ik62y3u01yqt8gsv31c/cknr138cc34a201yiyory7mie/play

**Comment by digitalken** [comment]
PASS 5/24/2021 - changes look good.  Closing.
