### ISSUE TITLE
1990E: Remove prod flag for question content update 24718

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24719]
As a developer, I need to remove the prod flag created for #24718 so that the new functionality is available in production.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of 2021-06-10.

## Acceptance Criteria
1. The functionality created in #24718  is available in production.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
Associated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17568

**Comment by sonntag-adam** [comment]
In production. Closing story.
