### ISSUE TITLE
1990E: Update 2 questions due to legislative changes.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24718]
As an EDU team member, I need the 1990E form updated so that it is compliant with recent legislative changes and the applicants are able to complete the form as accurately as possible.

## Assumptions:
1. This work is completed behind a prod flag.
2. The staging form is found [here](https://staging.va.gov/education/apply-for-education-benefits/application/1990E/introduction).
3. Initial research has been conducted to indicate that "Spouse" & "Child" are the values sent on the spool file.

## Acceptance Criteria
1. In Chapter 1, Page 1 the answers to the question `What’s your relationship to the service member whose benefit is being transferred to you?` are:
    a. Spouse
    b. Child
2. In Chapter 6, Page 1 the question `Type of education or training` is not required.

## Supporting Artifacts:
1. For AC1:
<img width="468" alt="AC1" src="https://user-images.githubusercontent.com/48260534/118294683-f9992200-b4a8-11eb-9668-a46de5287a9a.png">

2. For AC2:
<img width="653" alt="AC2" src="https://user-images.githubusercontent.com/48260534/118294686-fb62e580-b4a8-11eb-8a32-1364a4b23c00.png">

**Comment by sonntag-adam** [comment]
![Screen Shot 2021-06-04 at 7.30.57 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c83bc2f9-4442-4a1d-b1c1-b73a6e9097f8)
##
![Screen Shot 2021-06-04 at 7.31.11 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/879c0022-7ae4-47b0-9e9a-ec075e774b8e)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/1925&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.
