### ISSUE TITLE
Letter case for the recipient/sender name should mirror the backend

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24729]
## Context for this task
On the SM ListItems, the recipient/sender name is displaying in all-caps. The frontend should not be enforcing any formatting rules for letter case. Rather, the frontend should mirror how the name is displayed in the backend. 

For example:
     - If the backend displays the sender name as "john smith", the frontend should follow the same letter case.
     - If the backend displays the sender name as "JoHn sMith", the frontend should follow the same letter case.

## Acceptance Criteria
1. On the SM ListItems, check to see that the frontend is not enforcing special formatting for letter case on the  recipient/sender name
     - Display the recipient-sender name in the same letter case as it displays in the backend

**Comment by keli13** [comment]
It seems as though the backend data is returning recipient/sender name's as all uppercase. Closing this as its behaving as intended. 

Raw data(left) App(right)

Screenshot:
![Screen Shot 2021-05-26 at 4.43.14 PM.png](https://images.zenhubusercontent.com/5f6a835240937331cdb5cee5/b39921d0-5d63-4afb-b1f1-c65068ce1067)

**Comment by digitalken** [comment]
Test case/run deleted.
