### ISSUE TITLE
Quality Assurance Feedback - Staging Review - Anchor Tag Pilot on CoronaFAQ Page

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#24727]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
Great job with the cross-platform testing!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
Determine why anchor links are not showing up on staging. The links were appearing earlier today (5/14), but they do not show up on any platform currently.
Please verify and work to resolve the IE11 specific issue described in defect [24372](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24372).
I was unable to reproduce the issue in IE11 on my personal machine.
![image](https://user-images.githubusercontent.com/52456633/118299085-4f23fd80-b4ae-11eb-9d70-75636c1778de.png)

**Should:**
None

**Consider:**
None

**Comment by SKasimow** [comment]
Thanks @pjhill - we will double-check this reported issue next week

cc @youngfreezyVA

**Comment by youngfreezyVA** [comment]
I just tried to reproduce, wasn't able to:
https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fstaging.va.gov%2Fcoronavirus-veteran-frequently-asked-questions%2F&speed=1
windows asks you to allow access to the clipboard, my guess is that the windows pop up didn't appear correctly when the reporter was originally testing
