### ISSUE TITLE
Message form field is optional when it should be required

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24737]
## What happened?
On the Compose Message form, the Subject line field is not assuming the required state when 'General' is the Subject.

## Specs:
- Device: all
- User: 41

## Steps to Reproduce
- Log in as user 41
- Navigate to the Compose Message form
- From the Subject picker, select 'General'
- Notice how the Subject line field does not update to "Required"

## Desired behavior
Subject line is required if 'General' is the Subject.

## Acceptance Criteria
1. When 'General' is the Subject, the Subject line is marked as a required field
     - Associated field error for Subject line: "Subject line is required"

## Bug Severity
- 3 - Medium

## Linked to Story
#22667 - AC #4c

## Screen shot(s) and additional information
![Image from iOS (51).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/23a3a9e8-3913-4454-9db8-9f8508cefafa)

**Comment by digitalken** [comment]
PASS 5/21/2021 - Looks good on iOS and Android.  Closing.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/cb070b93-b67f-4074-b4c4-5c08ee7de9ff)
