### ISSUE TITLE
SM forms: "Cancel" nav button should route to confirmation screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24734]
## Acceptance Criteria
1. On the Compose & Reply message forms, route the **Cancel** button in the top nav bar to the cancel confirmation page (i.e. the Cancel this message? and Cancel this Reply? pages) 
     - This is the same routing that's used on the large Cancel button below the form
2. On the confirmation pages (for both the Compose & Reply forms) replace the **Cancel** button with a **Back** button

#### AC #1
![Screen Shot 2021-05-14 at 10.57.34 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/c9134e87-afb4-4aa2-825f-22071c6ef896)

#### AC #2
![Screen Shot 2021-05-14 at 10.57.55 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e2a8c7f8-5bac-49ce-9f0b-9640778cfa6c)

**Comment by digitalken** [comment]
PASS 6/10/2021 - Looks good on Android and iOS.  Closing.
