### ISSUE TITLE
1990E: Remove prod flag for 24730

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24731]
As a developer, I need to remove the prod flag created for #24730 so that the new functionality is available in production.

## Assumptions:
1. UAT has been completed for this effort and EDU signed off as of [TBD].

## Acceptance Criteria
1. The functionality created in #24730  is available in production.

## Supporting Artifacts:
1. N/A

**Comment by mrblanco1** [comment]
Please wait to approve this PR until UAT is approved.

**Comment by SebVortex** [comment]
After removing env flags, automation failures have been plaguing the unit tests involving 1990E. Given that staging code was test compliant. Test flakiness was assumed and a new branch was made to combat flakiness with test proven code that is already in the staging environment.

**Comment by SebVortex** [comment]
Warning: getCacheEntry failed: self signed certificate in certificate chain

**Comment by SebVortex** [comment]
On PR https://github.com/department-of-veterans-affairs/vets-website/pull/20783, unit tests are failing with functionally identical code that passed tests in the staging environment. The errors and warnings produced were:
> Warning: getCacheEntry failed: self signed certificate in certificate chain
> Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
> Warning: Attempt 2 failed. Reason: Child_process exited with error code 1
> Error: invalid format for 'output: SyntaxError: Unexpected token } in JSON at position 11
> Error: Unable to find an artifact with the name: unit-test-coverage-report

All cypress tests are passing (which is important to note as the aforementioned flaky tests were cypress tests).

Already tried a rebase, and will see if rerunning all jobs fixes the matter post-rebase.

**Comment by SebVortex** [comment]
Opened support request to deal with testing mishaps:
https://dsva.slack.com/archives/CBU0KDSB1/p1649864619047649

**Comment by SebVortex** [comment]
Unit tests are now passing, however, cypress tests are now failing to run in the automation with error output:
> SyntaxError: Unexpected end of JSON input
>    at JSON.parse (<anonymous>)
>    at Object.<anonymous> (/__w/vets-website/vets-website/script/github-actions/run-cypress-tests.js:3:20)
>    at Module._compile (internal/modules/cjs/loader.js:1063:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>    at Module.load (internal/modules/cjs/loader.js:928:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>    at internal/main/run_main_module.js:17:47

Seeing if another rebase will fix this.

Note: It might have occured to someone reading this that the instability of the automation can be waited out and the code can be verified locally. However, it has been found that for some tests, local failures or successes don't correlate directly to failures and successes in the automation. As is the case with 'edu-1990e.cypress.spec.js'. Volatility in the automation means more time is added in verifying even code that, aside from being environment flagged, have already passed and been approved by other developers, UAT, and the automation itself.

**Comment by SebVortex** [comment]
After impacted unit tests were addressed, cypress tests were impacted but quickly fixed yesterday afternoon.
After all tests were functional again, a single cypress test was failing that pointed to a recognizable fix. The minimal.json (default test data) for 1990e didn't have any information supplied for the bankAccount and it just needed to be updated for tests to run smoothly.

Unfortunately, even knowing this, it couldn't be tested locally, as even with the change, the affected test did not pass on its own even though it passes in the automation.

It has been noted before but a big enemy to productivity in development is test flakiness. Especially when the first resonable assumption for failing tests in some cases is not developer work but a failure of the automation.
