### ISSUE TITLE
1990E: Update direct deposit content and add I certify content

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24730]
As an Education team member, I need the 1990E form updated to include the latest direct deposit pattern and certification content language so that it is consistent with other available digital forms.

## Assumptions:
1. This work is completed behind a prod flag.
2. The form can be found here: [Staging Form](https://staging.va.gov/education/apply-for-education-benefits/application/1990E/introduction)

## Acceptance Criteria:
1. In Form Chapter 7:
    a. The direct deposit pattern matches that outlined in SA2.
    b. The `What if I don’t have a bank account?` content is replaced with:

    > The [Veterans Benefits Banking Program (VBBP)](https://veteransbenefitsbanking.org/) provides a list of Veteran-friendly banks and credit unions. They’ll work with you to set up an account, or help you qualify for an account, so you can use direct deposit. To get started, call one of the participating banks or credit unions listed on the VBBP website. Be sure to mention the Veterans Benefits Banking Program.
    > 
    > Note: The Department of the Treasury requires us to make electronic payments. If you don’t want to use direct deposit, you’ll need to call the Department of the Treasury at [888-224-2950](url). Ask to talk with a representative who handles waiver requests. They can answer any questions or concerns you may have.

2. In Form Chapter 8 the following content is displayed in the Review Application Chapter:

    > 	**By submitting this form** you certify that all statements in this application are true and correct to the best of your knowledge and belief.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/projects/prototypes/14222615)
2. [VA.gov Direct Deposit Pattern](https://design.va.gov/patterns/form-templates#direct-deposit)

**Comment by mrblanco1** [comment]
Need more info to find out about this change. Gina to follow up with OCTO's design.

**Comment by AdamFreemer** [comment]
This is for Chapter 7 content part (1). https://github.com/department-of-veterans-affairs/vets-website/pull/20587

**Comment by SebVortex** [comment]
A functionally unrelated test seems to be failing consistently. Not only on the branch associated with requirement 2 but on master (locally) as well.
https://dsva.slack.com/archives/CBU0KDSB1/p1648221426081569

**Comment by SebVortex** [comment]
Design support request: https://dsva.slack.com/archives/CBU0KDSB1/p1649350961605569

**Comment by hallihocine** [comment]
Ticket has been validated in staging: all changes have been implemented to 1990E form.
1. Direct deposit pattern updated and matches the OCTO/Design recommendations: 
<img width="469" alt="Screen Shot 2022-04-08 at 6 31 23 PM" src="https://user-images.githubusercontent.com/86266024/162542971-31b8c4d8-e4c6-4f75-b723-48329468be53.png">
2. The What if I don’t have a bank account? content is added:
<img width="530" alt="Screen Shot 2022-04-08 at 5 25 06 PM" src="https://user-images.githubusercontent.com/86266024/162543053-4e210853-94a0-4cf0-85f8-5eeaad90a653.png">
3. A certification content is added and displayed in the Review Application Chapter:
<img width="594" alt="Screen Shot 2022-04-08 at 5 54 42 PM" src="https://user-images.githubusercontent.com/86266024/162543238-a1973f74-b850-4b1c-af9a-b3abf8571162.png">

**Comment by hallihocine** [comment]
- Test run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/3134&group_by=cases:section_id&group_order=asc&group_id=4169
- Test Steps:
[1990E-Update direct deposit content and add I certify content.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8455684/1990E-Update.direct.deposit.content.and.add.I.certify.content.xlsx)

**Comment by mrblanco1** [comment]
QA and UAt passed on 4/11/2022.
