### ISSUE TITLE
Investigate VAOS app toggle history (Production)

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24735]
## Description 
Following the incident reported 5/14 where users couldn't access the VAOS homepage in Production, it was discovered that this was due to the feature toggle configurations.

### Incident details
- User can't load https://www.va.gov/health-care/schedule-view-va-appointments/appointments/

![VA_Online_Scheduling___Veterans_Affairs.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/ea64fc9c-da39-4dd1-af88-11d27a80863e)

- Toggle admin console https://api.va.gov/flipper/features
- Toggle changes likely included:
  - From `ON` to conditional
  - "Percentage of Logged in Users" = 100
  - Addition of emails in "Logged in Users" section
- Sentry log: http://sentry.vfs.va.gov/organizations/vsp/issues/677/?project=4&query=is%3Aunresolved&statsPeriod=24h
- Changes likely occurred 5/13 afternoon/night

## Task
- [ ] Research toggle history for changes that caused the issue
Per convo in platform support

> there’s not a console that shows it, but every transition is recorded in the database so an engineer can go and look at the feature toggle events table and see the history...in the rails console

**Comment by LeKeve** [comment]
@laurenernest 

After some digging around and speaking with platform support, it looks like I need production AWS access to further investigate. A backend dev that has access to the rails console in production may need to take this on.

They will need to view the `feature_toggle_event` table in the rails console for changes to the `va_online_scheduling` feature flag.

**Comment by grossb1** [comment]
![image.png](https://images.zenhubusercontent.com/5f31c8a58b5893ec1bdbac09/7392f91d-b5a2-45d3-bc69-80d22cda157f)

**Comment by grossb1** [comment]
Here is the additional data containing all records sans May

[https://app.zenhub.com/files/133843125/eb6b1509-70c9-425c-9aac-e2a5f03fb68f/download](https://app.zenhub.com/files/133843125/eb6b1509-70c9-425c-9aac-e2a5f03fb68f/download)

**Comment by laurenernest** [comment]
That record stops in April 2020. Can we get 2021?

**Comment by grossb1** [comment]
That's all of them, although it is a bit curious that it should jump from 4/2020 to 5/2021.

**Comment by laurenernest** [comment]
Since this toggle is for our whole app on VA.gov, it makes sense that there isn't much activity after the last record, but it is concerning that the actions that caused the issue are the only ones not don't show up in the record.

@grossb1 Can you run the same check on the `va_online_scheduling_provider_selection` toggle? There should be activity in 2021. If there isn't anything then we know there was a time where toggle activity wasn't logged.

**Comment by grossb1** [comment]
Here is the latest va_online_scheduling_provider_selection
![image.png](https://images.zenhubusercontent.com/5f31c8a58b5893ec1bdbac09/6ec4ab0b-5beb-4064-8468-33317aab65f0)

**Comment by laurenernest** [comment]
Thanks! I'll have to consult VA and VSP for further triage. closing ticket.
