### ISSUE TITLE
Message detail: attachment icon not displaying

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24736]
## What happened?
For messages w/ attachments, the detail accordion is not displaying the attachment icon in line with the date/time. Instead, the message displays "(has attachment)" below the date/time.

## Specs:
- Device: all
- User: 41

## Steps to Reproduce
- Log in as user 41
- From the Inbox page, select a message w/ attachments
- View the detail of that message
- Notice how the copy "has attachment" displays underneath the date/time

## Desired behavior
1. When a message has an attachment, the detail accordion should display the attachment icon to the left of the date/time. 
2. The message detail should not display "has attachment" copy underneath the date/time.

## Acceptance Criteria
See desired behavior

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information
![Screen Shot 2021-05-14 at 11.31.21 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/b7536246-dc8c-4f16-8778-2acd0e750208)

**Comment by digitalken** [comment]
(Not in build yet as of 5/21/2021 @ 11:30 AM)

**Comment by digitalken** [comment]
PASS 5/27/2021 - Looks good, has icon.  Closing.
