### ISSUE TITLE
Create Research Plan (Rated Disabilities & View Dependents)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2473]
## Story
As a design researcher, I want to create a consistent plan that encompasses the guidance of approved methods and all the components for the item I am researching.

## Goal
To validate my hypothesis and ensure that I am applying user centered designs before engineers start to build.

## Considerations
- Baseline functionality
- Incorporate info from users already obtained
- Walkthrough of functionality
- Use mockups/prototypes as needed
- Make refinements
- Usability testing
- [Previous Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery-research-plan.md)

## Task
Document a research plan to include:
Research method (moderated user interviews)
Participants & Recruitment
Timeframe
Team Availability
Roles (include emails)
Seek review before implementation

## Acceptance Criteria
- [x] Create a research plan detailing hypothesis and anatomy of the page
- [x] Research Plan has been sent for review by [Lauren Alexanderson](https://dsva.slack.com/team/U772MC9BQ) and/or Shawna(?)
- [x] Notify Andre

**Comment by sporeboy** [comment]
Research plan initial draft is available here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md
