### ISSUE TITLE
Access for [Gaida Escobar]

### ISSUE THREAD

**Issue by gescobardev** [department-of-veterans-affairs/va.gov-team#24732]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Do not remove `operations` label; this will notify the VSP Operations team of your request
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O’Toole
- Please provide your name.
   > Gaida Escobar
- Please Provide your email.
   > gescobar@governmentcio.com
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team Name: Facilities, Role: Front-End Engineer, Company: GovernmentCIO

- Requesting SSH key authorization?
   > YES
   - What is your **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnO9LXEs9uULxV2CjKYUQlDdkbQvIKBsXOu1BsSoUvm6bo9DjZG8cdUfVqdW34YnDqsBe30qWTaKmhhj7gkhAJJQz4ShbK9W7XGEATRZNInivFlCYOoZKJhkoJVU1oryWp9a5UIv00/24oRTGxb8rxB4b6DWQhjL5VoVWxrFc+H6uyEOlcjYPDwXZxaksMX8XRSoA4k83JvNTjf1gkPk0AdHC1R+mYxbWzlpm5YTWb9Uus2FtXFs0yf24KO9SzeTMtiRVBxn/51EwchXInvCIatp9HVSy/PT6rFmL9l/HgprIt+uqxkZDJtI+TJpOEyarUrcHVvGjDWhze5EfZppvSmNeQlBVYkvCrV+A+n6zOHdj7Fl4CW3vBtkk4B0lhwd5mOmqCssT7HP+s46cxIvzRY+//TW2/KmuACWR3P/ACZMDnGxl5htAU8HSzfxWFWyrJ5ZvUaMxHsvBcIx3dkwqFRj4YeRRwXG7xD7xcDzZQVFBMzPm/VEsJ+BwIi4zIkHM= gaidaescobar@gescobar-C02Z18JJLVCG.local
```

- Grant AWS Console access?
  > NO
  - What AWS services do you need access to and why?

**Comment by jbritt1** [comment]
SOCKS access granted. Please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
