### ISSUE TITLE
General Analytics Request for Monthly Reports

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#24741]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation. If you have your KPIs set, please [request a KPI dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

Chris Johnston (VEO, OMB, & DMC reports)
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
The past 24 months. For the datasets, try to go as far back as possible

## Analytics to Track Down

Can we get these metrics? Document the availability & how we would be able to track & connect these metrics:

- [ ] Facility Detail Views (add after “Page Views”) – Maps to the DE goal: “Veterans and their families can find a single, authoritative source of information”
- [ ] Letters Downloaded (add after “Claim Status”) – Maps to the DE goal: “Logged-in users have a personalized experience, with relevant and time-saving features”
- [ ] Profile Updates (combined all updates, add after “Unique Logins”) – Maps to goal: “Logged-in users can update their personal information easily and instantly”
- [ ] On-site Searches (add after “Facility Views”) – Maps to goal: “Veterans and their families can find a single, authoritative source of information”
    This one isn’t in GA, rather it would likely be a new integration with Search.gov. Not even sure this is possible so certainly a lower priority

## Which Product Questions are you trying to answer?

1. Is there a difference between those that say “Total” and those that don’t? If not, we can exclude the word “total”

2. In the last two, does “total users” mean unique visitors to the site?  

3. Similarly, I’m equating “unique logins” to “monthly active users” – is that correct?

4. Why are some of the data different? E.g., HCA submissions in the VEO report show 19,484 for March, but the OMB version shows 15,495

## Other Helpful Questions to think through
- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Link to Metrics
Current monthly reports
- [Digital Modernization Council](https://va-gov.domo.com/page/42290444)
- [Veterans Experience Office](https://va-gov.domo.com/page/730309340)
- [Office of Management and Budget](https://va-gov.domo.com/page/1587068891)

## Additional Comments
These are discovery questions for the larger rehaul of our current recurring monthly reports. That work is described in more detail in #24740 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
> 1. Is there a difference between those that say “Total” and those that don’t? If not, we can exclude the word “total”

No - all the GA metrics are summations or "totals".  "Total" has been removed from card names. 

> 2. In the last two, does “total users” mean unique visitors to the site?

Yes - it's a count of distinct user IDs over the entire month...

```sql
COUNT(DISTINCT fullVisitorId) AS users,`
```
> 3. Similarly, I’m equating “unique logins” to “monthly active users” – is that correct?

That is correct.  Standard disclaimer that we don't do any user ID or cross-browser tracking in our GA, so users on multiple browsers or devices will inflate this number.

> 4. Why are some of the data different? E.g., HCA submissions in the VEO report show 19,484 for March, but the OMB version shows 15,495

A card filter in Domo that was filtering out days with < 200 events.  This is fixed.

**Comment by bsmartin-ep** [comment]
> Facility Detail Views (add after “Page Views”) – Maps to the DE goal: “Veterans and their families can find a single, authoritative source of information”


This would just be pageviews to pages like https://www.va.gov/find-locations/facility/vha_595GA ?

I don't see an existing dataset with these pageviews, but they're in BigQuery.

>  Letters Downloaded (add after “Claim Status”) – Maps to the DE goal: “Logged-in users have a personalized experience, with relevant and time-saving features”

Are these the same as Debt Letter downloads?

https://va-gov.domo.com/kpis/details/1559138384

> Profile Updates (combined all updates, add after “Unique Logins”) – Maps to goal: “Logged-in users can update their personal information easily and instantly”

Total Profile Submissions?

https://va-gov.domo.com/kpis/details/1952454837

> On-site Searches (add after “Facility Views”) – Maps to goal: “Veterans and their families can find a single, authoritative source of information”

We have the data, but not an exact generic total searches card...

https://va-gov.domo.com/datasources/e94aa216-38f5-483e-9eef-01421bc2ee37/details/cards

**Comment by joanneesteban** [comment]
Thanks, @bsmartin-ep !

> > On-site Searches (add after “Facility Views”) – Maps to goal: “Veterans and their families can find a single, authoritative source of information”
>
> We have the data, but not an exact generic total searches card...
> 
> https://va-gov.domo.com/datasources/e94aa216-38f5-483e-9eef-01421bc2ee37/details/cards

Brian, are these totals from the top search bar? If so, maybe this formula? `All Site Searches total + All Facility Searches total`?

@chrisj-usds would you be able to clarify the data points for `Letters Downloaded` and `Profile Updates` from Brian's previous comment?

**Comment by bsmartin-ep** [comment]
@joanneesteban -

> Brian, are these totals from the top search bar? If so, maybe this formula? All Site Searches total + All Facility Searches total?

The one I linked is an older dataset looking at every `searchKeyword` dimension.  So anything in the URL with one of these query params...

`_3_keywords, q, query`

..which I do not believe includes the facility locator.

I made a quick card with Jason's new search dataset and that also excludes Facility Locator...

![image](https://user-images.githubusercontent.com/62304138/121761416-9a591c80-cafd-11eb-97b0-a74da62ee0ef.png)

I'm guessing due to it being a separate event from `view_search_results`.  

Maybe we can ETL those Facility Locator event counts into dataset #1?

**Comment by chrisj-usds** [comment]
Thought I had answered all your questions a while back @bsmartin-ep. Apologies for that. Here goes:

**Comment by chrisj-usds** [comment]
Thought I had answered all your questions a while back @bsmartin-ep. Apologies for that. Here goes: 

>> Facility Detail Views (add after “Page Views”) – Maps to the DE goal: “Veterans and their families can find a single, authoritative source of information”

> This would just be pageviews to pages like https://www.va.gov/find-locations/facility/vha_595GA ?

Correct. If they're in BQ, does that mean we can pull them in? 

>> Letters Downloaded (add after “Claim Status”) – Maps to the DE goal: “Logged-in users have a personalized experience, with relevant and time-saving features” 

> Are these the same as Debt Letter downloads? 

Yes. 

>> Profile Updates (combined all updates, add after “Unique Logins”) – Maps to goal: “Logged-in users can update their personal information easily and instantly”

> Total Profile Submissions?

Yes. 

>> On-site Searches (add after “Facility Views”) – Maps to goal: “Veterans and their families can find a single, authoritative source of information”

> We have the data, but not an exact generic total searches card...
https://va-gov.domo.com/datasources/e94aa216-38f5-483e-9eef-01421bc2ee37/details/cards

I'm unable to see that link. I am thinking of header utility searches here, not Facility searches.

**Comment by bsmartin-ep** [comment]
@chrisj-usds -

> Correct. If they're in BQ, does that mean we can pull them in?

Sure thing - [they are recorded in GA](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.filter=www.va.gov~2Ffind-locations~2Ffacility~2F&explorer-table.plotKeys=%5B%5D) so they are available in BQ.

> I'm unable to see that link. I am thinking of header utility searches here, not Facility searches.

As in this search?  

![image](https://user-images.githubusercontent.com/62304138/128757811-0c5e0fb0-4d86-4225-9f65-833a57920b30.png)

If so, our Domo datasets [for that are a lot better than before](https://va-gov.domo.com/page/1964748112?pfilters=%5B%7B%22column%22:%22search_scope%22,%22operand%22:%22IN%22,%22values%22:%5B%22VA.gov%20Onsite%20Search%22%5D%7D%5D).

**Comment by chrisj-usds** [comment]
@bsmartin-ep  That search indeed!

**Comment by joanneesteban** [comment]
Thanks, @chrisj-usds !! 

@bsmartin-ep will get started on pulling this data into Domo.

CC: @chloedotbrown for https://github.com/department-of-veterans-affairs/va.gov-team/issues/24740

**Comment by chloedotbrown** [comment]
Thanks, Brian! Since all metrics are defined and now in Domo, I'm going to close this ticket. I'll add updates or any questions that come up during build on the report iteration ticket (#24740).
