### ISSUE TITLE
UI updates to bottom nav & SM footer buttons

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24745]
## Acceptance Criteria
1. On the bottom navigation bar, update the top & bottom margin/padding to 10px
     - _Currently, the top margin is 8px and the bottom margin is 12px. These should both be 10px._ 
2. Increase the height of the Compose Message & Reply toolbar buttons so they are the same height as the bottom nav bar
     - _Currently, the height of the nav bar is > than the height of the toolbar buttons_
3. Update background color for the nav bar **and** both SM footer buttons to #F9F9F9
     - Add this hex code to the app's color palette, as it is a new addition to the Design Library

#### AC 1:
![Screen Shot 2021-05-14 at 1.43.45 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/8ca43bb8-789b-4002-869d-415f3f810782)
#### AC 2:
![Screen Shot 2021-05-14 at 1.43.56 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/07922daf-2691-46ca-9e1d-48542a86c04e)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/10/2021 - Looks good on iOS and Android.  Closing.

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/a415c3fd-1a7b-4d78-9c87-86b633d6cdfc)
