### ISSUE TITLE
Pagination: inconsistent padding

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24747]
## What happened?
1. The top/bottom padding on the pagination component is inconsistent across pages. 
2. Top padding on the right/left arrow buttons looks the same as left/right, which is 20px. Top/bottom padding should be 40px.

## Specs:
User +41
![e5ac9d38-5cba-4556-b878-7e9b7b7a33d2.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/d5765e16-7130-4502-913b-114ec82a2c7a)

## Steps to Reproduce
**Inconsistencies w/ bottom padding**
- Log in with user +41
- Navigate to the Inbox page. Scroll to the bottom. Observe the amount of padding below the pagination CC and above the toolbar button
- Navigate to the Sent page. Scroll to the bottom. Observe the amount of padding below the pagination CC and above the toolbar button
- Notice how there is less padding on the Sent page than there is on the Inbox page

**Inconsistencies w/ top padding**
- On user +41 > Secure messages, observe the top padding 
- Switch to +judy > Appointments, observe the top padding
- Notice how there is less padding on Judy's appointments pagination, than on +41's SM pagination

## Desired behavior
1. Padding below the pagination component is consistent across all screens. 
2. Top and bottom padding should be 40px.
3. Right and left padding should be 20px.

## Acceptance Criteria
1. Padding below the pagination component is consistent across all screens. 
2. Top and bottom padding should be 40px.
3. Right and left padding should be 20px.

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information
![Screen Shot 2021-05-14 at 2.18.20 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/e98f3222-bda6-404a-b629-c167026a6a15)
![706a9f47-c7e4-42ad-a543-d2ecab09c76b.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/3c7da286-4f6c-4a67-835d-39b35f265c3e)

**Comment by digitalken** [comment]
6/17/2021 - @kxiao133 It seems to be OK on Android but iOS is still giving bottom margin/padding inconsistencies.  After getting a large bottom margin, I can slide the screen image a little bit and it jumps down to where it should be.  See the two screens showing the same page.  I can slide the page down slightly and it will jump to where it should be.  Check the video.  Sending back to in-progress.

![2021-06-17_12-42-21.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/b2e282df-ac29-44fe-b980-74d092fe5fec)

https://images.zenhubusercontent.com/133843125/97dcd3a1-b994-4b29-8e30-1e1f851e0556/rpreplay_final1623958259.mov

**Comment by digitalken** [comment]
PASS 7/7//2021 - Looks good on iOS now, too.  Closing.
