### ISSUE TITLE
Iterate on Feedback Received from Shawna (View Dependents)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2474]
## Tasks
- Based on user feedback, adjust mockups

## Acceptance Criteria
- [x] Incorporate feedback from Shawna on "View Dependents"

### Next Steps
- Design Review

**Comment by sporeboy** [comment]
Met with Shawna 11/1. View dependents screen will proceed to usability testing alongside Rated disabilities. Usability testing will determine suitability of tools page layout, cards and the right hand sidebars for migrated eBenefits screens.

Will work with Authenticated Experience team to determine way forward with AE-specific styling, and application-appropriate UX/UI/components.

Iteration of View Dependents screens can proceed as prototypes for testing. Content review is required for all user-facing mockups and prototypes.
