### ISSUE TITLE
Update borders/padding for SM lists

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24746]
## Acceptance Criteria
1. On the Message Detail and Reply to Message forms, reduce the size of the accordion borders to 1px
2. On the SM ListItem, increase the size of the bottom margin so it matches the top margin

#### AC #1
![Screen Shot 2021-05-14 at 1.51.36 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/8aca21bc-dfc0-407e-a3ce-74ae39f23bf3)
#### AC #2
![Screen Shot 2021-05-14 at 2.09.40 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/ec817dfa-9e9f-419c-8d83-90aaadd7c34c)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/25/2021 - Borders look like 1px, margins look to be matching top and bottom.  Closing.
