### ISSUE TITLE
Display file size on Attachments screen 

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24744]
## Acceptance Criteria
1. In the SM flow, when a file has been added to the Attachments page (i.e. user has selected 'File folder' option), display the file size after the file name
     - Format: (#.## MB)
2. Bold the file name + file size

Note for dev: this formatting is nearly identical to what is displayed on the form after the file is attached to a message.

## Mockup
![Screen Shot 2021-05-14 at 1.18.59 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/05555d98-7bb5-49a4-8ef2-0a67941c7c13)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/10/2021 - Looks good on Android and iOS.  Closing.
