### ISSUE TITLE
Back button is missing "<" on File FAQ page

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24743]
## What happened?
On the Attach a File FAQ pages, the Back button in the top nav bar is missing the "<" icon 

## Specs:
- Device: all
- User: 41

## Steps to Reproduce
- Log in as user 41
- Navigate to the Compose Message form
- Select "How to attach a file" 
- Notice that the Back button does not display the "<" character as it does on the other pages in the app

## Desired behavior
Universally throughout the app, Back buttons in the header should display as: **< Back**

## Acceptance Criteria
See desired behavior.

## Bug Severity
- 4 - Low

## Linked to Story
n/a

## Screen shot(s) and additional information
![Image from iOS (52).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/6b3fb60b-f18e-4a0e-830d-f5f56f8fa5b5)

**Comment by digitalken** [comment]
PASS 6/3/2021 - Arrow is present.  Closing.
