### ISSUE TITLE
Claims Integration | Multi-photo upload

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24755]
## User Story / Task 
This is a backend task to integrate with the file upload endpoint 

## Acceptance Criteria

1. Service integration with the claims API to call the relevant endpoint when a user uploads photo(s) to their claim
2. Call this endpoint after a user confirms the upload for 1 or more photos

## Note for QA
Once this story is complete, retest the following file upload tickets:

- #19098
- #18735

**Comment by digitalken** [comment]
PASS 5/21/2021 - Looks good on Android and iOS.  Closing.
