### ISSUE TITLE
Create a system for cataloging and recording staging test user information

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#2475]
VFS teams looking to utilize test users in staging to test their products need to understand what kind of services the user is authorized for and what kind of data is mapped to the user.  A piece of documentation in the form of a table or perhaps a custom tool describing the characteristics of the test accounts in great detail would be very useful.  VFS teams would find the following information useful --

1. User credentials (user credentials will need to be stored in a secure way)
1. VA.gov services available to user
1. Data mapped to user
   - Addresses
   - Phone numbers
   - Medical records
   - Claims
   - Military records
   - GI Bill benefits
   - Lab / test results
   - Appointment history
   - Messages
   - Prescriptions
   - ID cards

**Comment by peterhill-oddball** [comment]
@tlei123 , Per our discussion on the other ticket, I've created this ticket for creating/enhancing the staging test user documentation.  If you have any input about what this should look like, or if you have any ideas about how to accomplish this then let's discuss that here!

**Comment by tlei123** [comment]
@peterhill-oddball , thanks much for creating this & including me!  I should have some time later this week or early next to provide input here, but feel free to ping me on Slack if you want to chat more before then.
