### ISSUE TITLE
Refresh-CC past detail updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24754]
## Description
Clean up designs and copy on the past community care appointment detail page.

![scope 24754.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/39e130c2-3d97-4301-8241-b5e6055b66d6)

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#confirmed-past) 
- [ ] DESIGN - Designs match the specs (copy is FPO) 
- [Desktop](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/DPdlVyn#Inspector)
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/ZOK57P7#Inspector)
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/GmJpeZ7#Inspector)
- Heading layout reference [overview](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/rblrZzD) and [content detail](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/nRgDbr0)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Screenshot of updated detail page is posted in this ticket

**Comment by outerpress** [comment]
@laurenernest just want to confirm for this ticket, are these changes in scope?:
* Remove the "Need to make changes" alert
* Remove the "Add to calendar" link
* If there's a booking note, show it (following the language in the copy doc)

**Comment by laurenernest** [comment]
Yes, and add yellow past alert
