### ISSUE TITLE
Draft guidance for VSP and VFS teams on Git LFS usage

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#2476]

**Comment by thatmattjohnson** [comment]
kickoff conversation with content/IA and product support team members scheduled for Thu 10/17

**Comment by thatmattjohnson** [comment]
draft document incorporating team feedback here: https://docs.google.com/document/d/1ZyjbSJm8ZOqpeK1n7wdsU4fiyfUl9Np_M0sh_1Z7o6g/edit
