### ISSUE TITLE
Contact Center Review for Find a VA Form - Search Improvements Iteration 2

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24777]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Find a VA Form - used to locate forms Veterans need to apply for benefits.  We've made changes to how the search matching works behind the scenes, and the UI has changed slightly due to the addition of a new option to sort by relevance.

### Launch Date
MVP launched in July 2020.  This feature will launch May 2021.

### Version Number
v05-17-2021

### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form/contact-center

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] VSP Contact Center QA has been completed 
- [ ] VSP Contact Center sends artifacts to appropriate contact centers
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by starlow00** [comment]
Hi @MarciMcGuireGCIO . This looks great! I made a couple of bulleted lists into numbered lists and number labeled the corresponding red highlight brackets. I also made the "TOC" page clickable to section. If it looks good to you, I'll make sure VEO gets a copy.
[FindVAFormsSearch-ProductGuide_v05-17-2021_ST-051921.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6511533/FindVAFormsSearch-ProductGuide_v05-17-2021_ST-051921.pptx)

**Comment by MarciMcGuireGCIO** [comment]
@starlow00 looks good to me!  Thank you!

**Comment by starlow00** [comment]
Sent to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. 

https://gcc02.safelinks.protection.outlook.com/ap/b-59584e83/?url=https%3A%2F%2Fdvagov.sharepoint.com%2F%3Ab%3A%2Fr%2Fsites%2FVACOveohotline%2FTraining%2520Files%2FKM%2520Docs%2FVA.GOV%2FProduct%2520Guides%2FFind-VA-Forms-Search-Product-Guide-v051721.pdf%3Fcsf%3D1%26web%3D1%26e%3DVHLfHp&data=04%7C01%7C%7C31789284add3434e120808d926c38ec1%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637583443610428650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TYZ35180NF0CEQNg3rh05hqIScgL5I%2F1umA9wX5k0wk%3D&reserved=0

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @starlow00 !
