### ISSUE TITLE
Design Feedback - Staging Review [Search & Discovery - Typeahead 1.0]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#24789]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- I am sure users will love this!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- make sure the font color is .vads-u-color--gray-dark $color-gray-dark #323a45, currently it is #212121 color-base

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by denisecoveyduc** [comment]
@allison0034 Can you confirm what exactly needs to change colors? the input field text? the suggestion text color? both?

**Comment by allison0034** [comment]
@denisecoveyduc it needs to be changed in both. The color should be .vads-u-color--gray-dark $color-gray-dark #323a45
<img width="1277" alt="Screen Shot 2021-05-17 at 1 06 04 PM" src="https://user-images.githubusercontent.com/72398073/118528948-f3a57a00-b710-11eb-8e27-ef5f7f434654.png">
<img width="1222" alt="Screen Shot 2021-05-17 at 1 06 29 PM" src="https://user-images.githubusercontent.com/72398073/118528956-f56f3d80-b710-11eb-9f6c-c7b300be6c07.png">

**Comment by denisecoveyduc** [comment]
PR went live on May 17th with this change. 
cc: @srsuddath will comment with any additional details required.
