### ISSUE TITLE
Get translated urls

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#24783]
## Issue description

We need to get translations for the URLs for these pages as soon as possible:

- VA Spanish-language assistance and resources
- VA Tagalog-language assistance and resources

**Comment by DanielleThierryUSDSVA** [comment]
@SKasimow FYSA Randi sent this out and asked for a quick turnaround. You can track in this ticket. Thanks!

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA thx!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA @SKasimow We just got the URLs back from the translation team. 

[https://app.zenhub.com/files/133843125/e4366623-2404-478e-837d-889faa68dd04/download](https://app.zenhub.com/files/133843125/e4366623-2404-478e-837d-889faa68dd04/download)

[https://app.zenhub.com/files/133843125/9c5da59a-053c-42d3-8392-16a6e9c3ca1d/download](https://app.zenhub.com/files/133843125/9c5da59a-053c-42d3-8392-16a6e9c3ca1d/download)
