### ISSUE TITLE
[Discovery] Loki staging test-logging past appointments

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24785]
## Description
Time box: 8 hours

We would like to test how we might be able to use Loki data for visualizations and insights we may not be able to see in Google Analytics.

Scenario: For VAOS users only, which facilities have the most appointments?
- Data logged should not include canceled appointments
- Data logged should not include upcoming pending or processed appointments

---

## Questions
- How might we reduce chances of counting users more than once and inflating totals?
- How might we understand if a facility has been visited by the same user more than once?

## Definition of Done
- [ ] Tasks are complete
- [ ] Answers to questions are documented

**Comment by cferris32** [comment]
Discovery findings:

Loki offers some degree of granularity with identifying single user interactions, with tags such as request_id to track individual requests, or account_id for a particular user account. However, at this time it does not seem to provide the necessary metrics to isolate a single user and potential duplicate interactions (whether it be requests or facility visits) with complete confidence. For a more wholistic look at past appointments metrics, we may need to turn to where source data is stored, but that is beyond the scope of this discovery.

Closing the ticket with this note as we have roughly reached the timebox on it. As we learn more about the service, we may find new ways to answer these questions.
