### ISSUE TITLE
BUG | Launch-Blocker | Anchor Tags Not Appearing on Page Load

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#24782]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

When using a variety of browsers, the copy link icon  does not appear on the Coronavirus FAQ Page until I refresh my browser from 1 -3x's:
- https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/

## Specs:
- Device: (e.g. iPhone 8, Macbook) Macbook
- Browser: (e.g. Firefox, IE 11) Safari v14.1

## Steps to Reproduce
- URL: https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

Copy link icon should appear upon page load for q's both inside and outside accordions 

## Acceptance Criteria
- [ ] Copy link icon should appear upon page load for q's both inside and outside accordions 

I've included screenshots showing the copy link icon missing from q's within and outside accordions.

![Screen Shot 2021-05-17 at 11.14.19 AM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/5748088b-13cf-4121-8feb-9ac91124ac4a)![Screen Shot 2021-05-17 at 11.14.30 AM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/8254de33-d9d4-47cc-9250-9acc760d4e4b)

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - here's ticket I created to track work on this bug. On the Staging Review call there were other instances where people reported same behavior on different browsers so it is not limited to just Safari.

@jenniferlee-dsva - think you saw this too; what were you using?

**Comment by SKasimow** [comment]
Interesting, just tried using Chrome browser (Google Chrome Version 90.0.4430.212 (Official Build) (x86_64)
and upon page load, the copy link icon appeared for the non-accordion q but did NOT appear within any of the accordion q's. Whereas in Safari the copy link icon did not appear anywhere.

**Comment by youngfreezyVA** [comment]
Hi @SKasimow yes the above was a separate issue and should be resolved (not appearing within accordions) by PRS merged in

I tried to reproduce anchor tags not showing up on page load in all these devices, and I couldn't see it happening:

Device: (e.g. iPhone 8, Macbook) Macbook
Browser: (e.g. Firefox, IE 11) Safari v14.1

I will keep trying. My guess is its a staging environment specific issue with feature toggles
