### ISSUE TITLE
CT Redesign: Housing benefit incorrect amount

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#24780]
AC 2 i https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/23531

Housing benefit is incorrect in staging sandbox

Sandbox:
![Screen Shot 2021-05-17 at 10.39.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6ab7283e-989f-4c10-be19-c51992851e68)
##
Comparison tool:
![Screen Shot 2021-05-17 at 10.40.06 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d5de4e4f-8992-4d21-b90c-0eddb827364d)

**Comment by ksantiagoBAH** [comment]
FE PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17237

BE PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/818

**Comment by sonntag-adam** [comment]
In staging. Closing bug
