### ISSUE TITLE
Load Testing Rated Disabilities

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2479]
## Story
As a frontend engineer, I want to be able to test this page to ensure it will not go down under heavy traffic.

## Considerations
- Docs for load testing [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/auth-session-loadtest.md)
- VSP QA: Peter Hill (peter.hill@oddball.io)
- VSA QA (for manual, front-end UI testing on Staging): Tze-chiu Lei (tze@adhocteam.us)
- Rated Disabilities needs to have all its endpoint components in place to fully load test given the network requirements
- Access to internals tools is required to perform load testing.

## Tasks
- Communicate with someone in QA and establish the procedures (and timing) for load testing

## Acceptance Criteria
After staging:
- [x] Schedule a meeting with QA (Tze) to understand how load testing works

**Next steps:**
- Does Tze suggest any other tickets after meeting?

**Comment by micahchiang** [comment]
Spoke with Tze and he confirmed there isn't a way to load test applications without access to internal tooling. He also mentioned he _might_ have bandwidth to help when our application is on staging, but he'd have to confirm with his team. I'll create a new ticket that deals with performing actual load tests, but it will be blocked until internal tool access has been granted.
