### ISSUE TITLE
Refresh-CC upcoming confirmed detail page updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24803]
## Description
Clean up designs and copy on the upcoming confirmed community care appointment detail page.

![scope 24803.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/8cacc346-b83a-431a-95e7-a09b7cfba546)

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#confirmed-future-1) 
- [ ] DESIGN - Designs match the specs (copy is FPO) 
- [Desktop](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/m18JMm8#Inspector)
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/zxlO2LW#Inspector)
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/eKgqW2j#Inspector)
- Heading layout reference [overview](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/rblrZzD) and [content detail](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/nRgDbr0)
- Note: 
    - icon colors are changed in new design
    - check spacing between header and text in alert

### Out of Scope
- Detail page navigation: breadcrumbs, back to appointments button

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Screenshot of updated detail page is posted in this ticket

**Comment by LeKeve** [comment]
Hey @outerpress. For the alert box, we use a component that is shared across va.gov and that component defines the spacing between the header and text. Would it make sense to leave the spacing as is?

**Comment by outerpress** [comment]
Oh gotcha - yep leave it as is in that case. Thanks @LeKeve !

**Comment by LeKeve** [comment]
Closing ticket. Work validated and merged in #24754
