### ISSUE TITLE
Update metrics around 10-10CG applications without a Primary Family Caregiver

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#24808]
- [x] Have they been occurring more frequently?
  - No.
- [x] Are there any commonalities among these cases?
  - See comment

**Comment by kevinmirc** [comment]
Other than these days below, the amount of secondary-only applications have been about the same (no more than 4 per day).

```
2021-05-06: 7
2021-05-07: 7
2021-05-11: 8
```
