### ISSUE TITLE
Login broken in local environment

### ISSUE THREAD

**Issue by thilton-oddball** [department-of-veterans-affairs/va.gov-team#24809]
[Anna reported](https://dsva.slack.com/archives/CBU0KDSB1/p1621263372475300) devs are unable to login to va.gov locally.

There are two types of login issues. With and without SSOe.

## Without SSOe (/sessions/idme/new)
  The SAML response comes back invalid (code 007)
  We’ve confirmed that content separation did not break the non-SSOe login, since the error page was still observed in the commit preceding the content separation release.

## With SSOe  (/v1/sessions/idme/new):
There’s something happening in the` int.eauth.va.gov` page during redirect that’s bringing the flow back to the ID.me login page (could be invalid SAML too, but haven’t seen an explicit error)
With the latest master. logging in redirects back to the login page, and at other times (maybe only last week) didn’t proceed further than “Authenticating…” But the commit before the content separation release was observed to have worked at least once. Yet to be determined whether this is flakiness on the part of SSOe or some change made between that commit and now.

### Repro Steps

1. Check out the latest master commit on vets-api and vets-website ([5a695ca](https://github.com/department-of-veterans-affairs/vets-api/commit/5a695cae626634b0f5b7f0969eeacc91b112cf5b) and [5902ff4](https://github.com/department-of-veterans-affairs/vets-website/commit/5902ff44d86166f7ad39575ba132b52de64d8526)).
2. Start vets-api and vets-website (via `rails s` and `yarn watch`).
3. Navigate to [the SSOe feature](http://localhost:3000/flipper/features/ssoe) and ensure it's enabled.
4. While using Safari 14.1 on macOS 11.3.1, navigate to [http://localhost:3001](http://localhost:3001) and click "Sign in”.
5. Select ID.me under “Sign in with an existing account”.
6. Sign in with Gmail account.

**Expected:** Returned to vets-website with an authenticated session.  
**Actual:** Returned to [idmelabs.com login page](https://api.idmelabs.com/en/session/new).

**Comment by ericboehs** [comment]
This has been fixed. It was a configuration issue on id.me's side.

While it wasn't working, this was provided as a work around:
- Click “Disable for everyone" on [ssoe feature page](http://localhost:3000/flipper/features/ssoe).
- Replace the existing files in config/certs with [the two here](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/62551d696e24658b2ff0e611757ed03bb93deeea/Products/Identity/Files_From_IDme/development-certificates).
- Set `authn_requests_signed: true` (under `saml`) in vets-api/config/settings.yml.
