### ISSUE TITLE
SM ListItem: line wrapping is not respected when switching from portrait > landscape > portrait

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24815]
## What happened?
Switching from portrait > landscape > portrait results in line wrapping issues for SM ListItems with multi-line subjects:
- on iOS: the longer line disappears behind the ListItem chevron ">" 
- on Android: the longer line overlaps with the date/time

## Specs:
- Device: iPhone 11, Samsung Galaxy S9
- Test user: +41

## Steps to Reproduce
1. Log in w/ a user that has access to SM (i.e. +41)
2. View the app in portrait mode
3. On the Inbox page, identify a message that has a longer **Subject line** that wraps to >1 line
4. Rotate the device to landscape
5. Rotate the device back to portrait
6. Notice how the LIstItem in Step 3 no longer wraps appropriately _(see 'What happened?' above for behavior across iOS vs Android)_

The following "fixes" the issue:
7. Tap into the message detail for that ListItem
8. Hit "Back" to return to the Inbox page
9. Notice that the line wrapping issue is resolved, and it now wraps appropriately as it did in Step 3

## Desired behavior
When rotating back to portrait, the ListItem content wraps to multiple lines

## Acceptance Criteria
See above.

## Bug Severity
- 4- Low

## Linked to Story
n/a

#### iOS:
![Image from iOS.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/60c50b18-890a-43d4-be1b-07284672ce68)

#### Android:

![Screenshot_20210517-132118_VAMobile.jpg](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/0b7b5c07-b56e-4069-8a0c-e0411faadc73)

**Comment by kxiao133** [comment]
![Screen Shot 2021-06-23 at 10.22.24 AM.png](https://images.zenhubusercontent.com/60649478943a271dbcdc43ea/fe3e29e1-e337-4080-a7cb-caac08abd792)
![Screen Shot 2021-06-23 at 10.24.38 AM.png](https://images.zenhubusercontent.com/60649478943a271dbcdc43ea/dbd3848b-e4e9-4d15-bad2-5181201be4cd)
Android update seems to have fixed the issue on my simulator - sending to QA to double check

**Comment by digitalken** [comment]
FAIL 6/25/2021 - @kxiao133 , still having the problem on Android.  iOS seems to be OK, but the same list with Android is still showing the problem.  Attaching a screen shot and sending back to in-progress.

![2021-06-25_11-16-21.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/12ce8216-cb4b-455d-a7b1-095bdee73b7f)

**Comment by digitalken** [comment]
PASS 7/7/2021 - This is now looking good on both Android and iOS.  Closing.
