### ISSUE TITLE
Refresh-VA canceled detail page updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24816]
## Description
Clean up designs and copy on the canceled VA appointment detail page.

![scope 24816.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/366ecee1-fe03-4e10-a2e9-cf8b25e18fd5)

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#canceled-future) 
- [ ] DESIGN - Designs match the specs (copy is FPO) 
- [Desktop](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/4amqEko#Inspector)
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/xrVeRwA#Inspector)
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/ZOK57Y7#Inspector)
- Heading layout reference [overview](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/rblrZzD) and [content detail](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/nRgDbr0)
- Note the casing of VA Appointment should be sentence case; VA appointment.

### Out of Scope
- Detail page navigation: breadcrumbs, back to appointments button

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Screenshot of updated detail page is posted in this ticket

**Comment by LeKeve** [comment]
It looks like the work for this ticket has been completed in #24817. 
- `VA Appointment` casing updated to sentence case, `VA appointment`
- appointment reason/details heading

We don't have the canceled time data so the canceled alert still reads `[Canceler] canceled this appointment.` without the date/time.

Here is a screenshot of our current canceled appointment details page:

![Screen Shot 2021-05-25 at 9.55.53 AM.png](https://images.zenhubusercontent.com/5fb2c17a7bedf7598b0e96f2/37e9845c-8c2f-4123-a3e3-4dc223efee5f)

**Comment by LeKeve** [comment]
@outerpress Want to check with you and make sure I'm not missing anything before closing this ticket. Does the current screenshot cover all the design specs?

**Comment by outerpress** [comment]
@LeKeve looks good to me, thanks!
