### ISSUE TITLE
Synthesize health care application research (first round)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#24812]
- High level report + detailed findings

**Comment by Dene-human** [comment]
Topline summary for team review: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Research%20April-May%202021/End%20user%20discovery%20research/topline%20summary_research%20findings.md

**Comment by Dene-human** [comment]
DRAFT [Research findings ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Research%20April-May%202021/End%20user%20discovery%20research/research%20findings.md)

**Comment by Dene-human** [comment]
[Session Notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/caregivers/10-10EZ/Research%20April-May%202021/End%20user%20discovery%20research/session%20notes)
[Topline Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Research%20April-May%202021/End%20user%20discovery%20research/topline%20summary_research%20findings.md)
[Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Research%20April-May%202021/End%20user%20discovery%20research/research%20findings.md)
[Research Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10EZ/Research%20April-May%202021/End%20user%20discovery%20research/10-10EZ%20Discovery%20Research%20readout.pdf)
