### ISSUE TITLE
SPIKE: Investigate page timeout for unauthenticated forms

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#24814]
A stakeholder discovered that the page, when left open, would just stay open for hours at a time. What is the the timeout on unauthenticated, in-progress forms, and what should it be?

**Comment by dat-gcio** [comment]
There is no timeout when the user is not logged in. [Slack convo](https://dsva.slack.com/archives/CBU0KDSB1/p1622564520340600?thread_ts=1622225437.293800&cid=CBU0KDSB1). The question of if there should be was deemed not important at this time.
