### ISSUE TITLE
Refresh-VA upcoming confirmed detail page updates

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24817]
## Description
Clean up designs and copy on the upcoming confirmed VA appointment detail page.

![scope 24817.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/55ebac66-2b7e-444a-a8ef-51974ade8cef)

---

## Acceptance Criteria
- [ ] Changes are behind the `va_online_scheduling_homepage_refresh` feature flag
- [ ] CONTENT - Content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#confirmed-future) 
- [ ] DESIGN - Designs match the specs (copy is FPO)
- [Desktop](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/JnPVvye#Inspector) 
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/nR8qG0W#Inspector)
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/dlkq78Z#Inspector)
- Heading layout reference [overview](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/rblrZzD) and [content detail](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/nRgDbr0)
- Note: "VA Appointment" should be sentence case: "VA appointment"

### Out of Scope
- Detail page navigation: breadcrumbs, back to appointments button

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Screenshot of updated detail page is posted in this ticket

**Comment by jbalboni** [comment]
![localhost_3001_health-care_schedule-view-va-appointments_appointments_va_22cdc6741c00ac67b6cbf6b972d084c0(iPad).png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/75a12242-c54e-4492-96c8-b5bba50b756a)
![localhost_3001_health-care_schedule-view-va-appointments_appointments_va_21cdc6741c00ac67b6cbf6b972d084c1(iPad).png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/ef2e58fc-e94b-47b5-8c5d-60e9626e2743)
