### ISSUE TITLE
Add cypress test to online scheduling feature

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24828]
## Issue Description
In #22760, we implemented the front end to include the availability of online scheduling for COVID-19 vaccine services. This code was placed behind a feature flag, pending VAOS rollout and a possible pivot to display walk-in availability. 

We did not include Cypress tests for this code as it has been placed on hold. 

---
## Tasks
- [ ] Add appropriate testing to online scheduling feature.

**Comment by jilladams** [comment]
Code for this still exists: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/facility-locator/components/ResultsList.jsx#L29

We should make a call re: whether the underlying functionality will be removed as part of unrolling COVID (that was introduced under [this PR 17207](https://github.com/department-of-veterans-affairs/vets-website/pull/17207), and this ticket closed. Or, if the functionality is staying as part of ongoing support for COVID vaccines, and this test should be added.

Screenshot from original implementation ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22760#issuecomment-838934876

**Comment by jilladams** [comment]
No op.
