### ISSUE TITLE
Implement Women's Health Text Reminders. 

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#24820]
From: Ashe, Steven B <Steven.Ashe2@va.gov> 
Sent: Friday, May 14, 2021 12:52 PM
To: Williams, Erica <Erica.Williams@va.gov>
Cc: VEText <VEText@va.gov>
Subject: RE: Women's Vet Outreach via Vet-text
Importance: High

Good Friday Erica,

Attached is the list of female veterans who will qualify for the Women’s Screening Text Message Reminder, which will include the following message:

“According to our records, you are due for your cervical cancer screening (or mammogram if that is the case).  Please contact your primary care team through the call center at 562-826-5151.  If you have already completed your screening please notify your primary care team who can document the screening in your medical record."

Please send a screenshot of what this text message will look like so I can share it with the Clinicians.  Let me know if you have any questions.
[https://app.zenhub.com/files/133843125/8b431718-049d-4a11-a6c2-ebdd9e56daa3/download](https://app.zenhub.com/files/133843125/8b431718-049d-4a11-a6c2-ebdd9e56daa3/download)

**Comment by Kennon-git** [comment]
duplicate
