### ISSUE TITLE
Add a URL for Rx Tracking in the Tools MEnu. 

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#24822]
From: Major, Ronald A. ASHVAMC <Ronald.Major@va.gov> 
Sent: Friday, May 14, 2021 8:49 AM
To: VEText <VEText@va.gov>
Subject: Patient Rx Tracking Report

Would it be possible to convert the tracking number on the patient messages report to a link for tracking?

URLs for direct tracking below
UPS: https://wwwapps.ups.com/WebTracking/processInputRequest?TypeOfInquiryNumber=T&InquiryNumber1=TRACKINGNUMBER
USPS: https://tools.usps.com/go/TrackConfirmAction.action?tLabels=TRACKINGNUMBER
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/f4c1f2d9-349a-4f28-b0de-39e3fe010e34)

**Comment by Kennon-git** [comment]
rob to do today
