### ISSUE TITLE
[ Discovery] Vet360 - Person and Contact Information Split - Update Request

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2483]
## Background
Back in August, we split our person and contact information endpoints apart to set the stage for our expansion into additional data domains in the future. Vets360 team are requesting that we start planning an update to use the new endpoint/points before June 2020.  We will work with you to submit any necessary change requests to accomplish this transition in the near future. 

* Contact Information has moved from person-mdm-cuf-person-hub has  to contact-information-hub removed "/person" from URL around contact-information. 

 
## Goal
Update to use the new endpoint/points before June 2020.

## Attachments

[https://app.zenhub.com/files/133843125/cbeb29ae-e0fd-4223-8cba-838c3c3dc2c7/download](https://app.zenhub.com/files/133843125/cbeb29ae-e0fd-4223-8cba-838c3c3dc2c7/download)

**Comment by Justin-Pickett** [comment]
@lihanli you can grab this ticket and began the technical discovery on this endpoint work.

**Comment by Samara-Strauss** [comment]
Lihan still needs to ask devops about access to deploy this for testing.
