### ISSUE TITLE
Refresh-vaccine appointment details

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24832]
## Issue Description
Currently, vaccine appointments display on the appointment details as a standard VA appointment. Update appointment details to reflect vaccine-specific information and functionality.

![-TICKET 24832.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/f8d2680c-cab2-4ea3-b452-4a51770721ca)

![-TICKET 24832 - Canceled](https://user-images.githubusercontent.com/2536801/119208071-700fc400-ba55-11eb-8273-7fcc97463d7d.png)

---

## Acceptance Criteria
- [ ] Given COVID-19 vaccine appointment, When appointment is confirmed and active, and homepage refresh flag is on, Then show vaccine details page
- [ ] CONTENT - Confirmed-active appointment copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#confirmed-future-vaccine)
- [ ] DESIGN - Confirmed-active designs match the specs (copy is FPO) 
- [Desktop](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/zxloQkb#Inspector)
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/4amb8yZ#Inspector)
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/DPdqJjW#Inspector)
- Headings: visual styling and semantic coding:
    - [overview](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/rblrZzD) 
    - [details](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/nRgDbr0)
- [ ] Given COVID-19 vaccine appointment, When appointment is confirmed and canceled, Then show vaccine details page
- [ ] CONTENT - Confirmed-canceled appointment copy matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#canceled-future-vaccine)
- [ ] DESIGN - Confirmed-canceled designs match the specs (copy is FPO) 
- [Desktop](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/JnPVvyr#Inspector)
- [Tablet](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/GmJpeD7#Inspector)
- [Mobile](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/AxJLE84#Inspector)
- Headings: visual styling and semantic coding:
    - [overview](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/rblrZzD) 
    - [details](https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/a/nRgDbr0)

### Out of Scope

- Detail page navigation: breadcrumbs, back to appointments button

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Screenshot of updated detail page is posted in this ticket

**Comment by outerpress** [comment]
@laurenernest I added screenshots and updated links. Questions from grooming:
* Confirmed - is replacing "cancel" button with alert in scope for this ticket?
* Confirmed - is updating the button icon color (black on staging, blue in design) in scope for this ticket? I am looking at replacing these with secondary buttons based on a11y feedback so might be worth skipping.

@jbalboni I couldn't find a canceled covid-19 vaccine appt on staging - could you drop a screenshot of that state here (@320px if possible)? I'll update the "?" screen above with that.

**Comment by jbalboni** [comment]
@outerpress 
![Screen Shot 2021-05-20 at 3 29 47 PM](https://user-images.githubusercontent.com/634932/119037647-3e78f900-b980-11eb-9675-060d0ae0c05b.png)

**Comment by LeKeve** [comment]
Updated vaccine appointment details page:

![Screen Shot 2021-05-24 at 1.28.39 PM.png](https://images.zenhubusercontent.com/5fb2c17a7bedf7598b0e96f2/d681b5f7-ec24-43c7-8783-b98dcb342837)

Icon buttons left unchanged per ticket comments.

**Comment by jbalboni** [comment]
@outerpress This seems to make the UI for canceling vaccine appointments different from all the other types, even though we have other types that don't allow cancellation. Are we going to make this change for all appointment types where you can't cancel them?

**Comment by outerpress** [comment]
@jbalboni yep this should eventually be the same for all non-cancellable appointments. Here are the states I have for upcoming appts in the in the design spec for reference (not official until they get into a dev ticket of course): https://www.sketch.com/s/d4b8e6aa-2e36-47fd-aa04-52f4d3f839c3/p/e83c0f64-10a3-4d33-811c-1cd4d83e4419?search=upcoming
