### ISSUE TITLE
Content Feedback - Staging review - My VA Dashboard

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#24858]
Feature in staging: staging/va.gov/my-va

## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
Hello, @tressaellen @ajakabcin Please see below feedback for Platform content review. 


**Questions**

When I click on the following links for user 226, it takes me to MHV page. Is this the intended behavior?
You have 0 messages
Refill and track your prescriptions
Get your lab and test results
Get your VA medical records 

-----

**Must feedback**

1. Please lowercase S in service connected at the top banner. It should be:
80% service connected

(the prototype shows it lowercase) 

-----

**Should feedback**

1. Link language doesn’t align and are inconsistent with the page's H1 they link to: 

For example: 
- "Manage all your claims and appeals" 
The H1 for this page/tool is “Check your claim or appeal status”  Users can’t manage their claims in this tool.

  - "Schedule and view your appointments"
The H1 for this page is  “Schedule and manage health appointments” to reflect that users can do more than schedule and view. 

2. For user 15, please replace the colon at the end of this message with a period

We can’t access your appointment information
We’re sorry. Something went wrong on our end, and we can’t access your appointment information. Please try again later or go to the appointments tool:

**Comment by ajakabcin** [comment]
Summarizing our tasks here:

- [ ] *Must Content feedback:* Lowercase the S in service connected in top banner
- [ ] *Should Content feedback:* Link language doesn’t align and are inconsistent with the page's H1 they link to 

@tressaellen and @erikphansen we need to resolve these for our UAT go/no-go.

**Comment by erikphansen** [comment]
@peggygannon:

> When I click on the following links for user 226, it takes me to MHV page. Is this the intended behavior?
> You have 0 messages
> Refill and track your prescriptions
> Get your lab and test results
> Get your VA medical records

Yes that's the correct behavior.

**Comment by erikphansen** [comment]
This is ready to validate on staging

**Comment by ajakabcin** [comment]
@peggygannon are you able to validate/confirm we're good to close this issue? Thanks!

**Comment by peggygannon** [comment]
hello @ajakabcin Yes, sorry I missed the earlier comment. The updates look good on staging.
