### ISSUE TITLE
[Alerting] Add Alarms to VSP Canary Terraform Module

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#24866]
## The Problem
The VSP terraform module for creating AWS canaries does not include the creation of any AWS Alarms. When a canary is created using the module and it begins to fail, it will do so silently unless the author also manually creates an alarm in the AWS console.

## Extra Context
Current canary state as of writing this ticket:
- 2 canaries (`build-error-check` & `vagov-search`) have alarms that were created manually in the AWS console
- 1 canary (`vagov-heartbeat`) does not have an alarm at all
- Both alarms use the `DevOps_Critical_by_Alarm_Description` SNS topic which is already configured in PagerDuty

## Work to be Done
- [ ] Update terraform canary module to create & manage AWS alarms

**Comment by jbritt1** [comment]
Awaiting team feedback: https://dsva.slack.com/archives/CTYQL39FE/p1655826375146319
