### ISSUE TITLE
Enable feature flags in dev per the enable_in_development setting

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#24868]
## User Story

**As a VFS developer**, I would like for the feature_toggles API on dev-api.va.gov to respect the `enable_in_development` settings in [config/features.yml](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/features.yml), **because then** we could point vets-website to the dev server (using the `--env.api` flag when starting the app) and those feature flags would be enabled for us.

## Expected Behavior

The dev environment does not currently respect the `enable_in_development` feature config. Since dev is indeed supposed to be “used by developers”, it would be 👍 if the feature flags were enabled per the `enable_in_development` settings.

## Acceptance Criteria

- [ ] Any features with `enable_in_development` set to `true` are enabled in dev-api.va.gov
- [ ] Any features with `enable_in_development` set to `false` OR not defined at all are disabled in dev-api.va.gov
- [ ] Supporting documentation has been updated

**Comment by thilton-oddball** [comment]
Based on info from [this discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24881), adding in a conditional to flipper that checks vsp_environment in settings.yml should (:crossed_fingers:) do the trick.

**Comment by thilton-oddball** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/7426
