### ISSUE TITLE
CT Redesign: Add compare drawer to search results

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24869]
As a Comparison Tool user, I need to be able to temporarily save an institution that I would like to compare against others so that I can browse multiple pages of institutions and then be able to compare them.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. Wiring up of the compare button is handled in story #24874.

## Acceptance Criteria:
1. On the search results page a compare drawer:
    a. Has a title of "Compare Institutions (X of 3)".  (Where X is the number of institutions currently selected for comparison)
    b. Displays collapsed by default

2. When the compare drawer is expanded there are 3 slots for display of institutions to compare.
    a. When there are no institutions selected, a placeholder indicator is displayed.
    b. The following content is displayed: "You can compare 2 to 3 institutions"
    c. A "Compare" button is available to initiate the comparison

3. The "Compare" button is disabled until there are at least 2 institutions available for comparison.

4. When an institution is added for comparison via the "Compare" checkbox on the institution card:
    a. The drawer is filled from left to right.
    b. The institution name is displayed
    c. The user has the ability to remove the institution for comparison from the drawer.
    d. The drawer header count is increased to match the total number of institutions in the drawer for comparison.

5. The user can remove an institution from the comparison drawer:
    a. by unchecking the "Compare" checkbox on the card.
    b. by clicking the remove link for the institution in the compare drawer.

6. When the user attempts to remove an institution using the drawer removal mechanism, they are prompted to confirm the removal.
    a. If they choose to remove, the institution is removed from the drawer and the selections slide to the left so that all blank compare slots are to the right.
    b. If they choose to not remove, no action is taken.

7. When an institution is removed from the compare drawer, the drawer header count is decreased to match the total number of institutions in the drawer.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/296060318_Searchbyname_Desktop_unselected)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17470

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1928)
