### ISSUE TITLE
[FE] Notification Preferences: Redux actions and reducers

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24863]
## Background
We need to ensure proper loading and saving of data 

## Tasks
- [ ] ..

**Comment by erikphansen** [comment]
This was far more complex than I expected so I bumped it to a 5. It required doing a lot of the big-picture thinking for how this feature is going to be built.

**Comment by erikphansen** [comment]
Merged and closing.
