### ISSUE TITLE
Receive Data from `FindRatingInfoService`

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2487]
## Story
As a Veteran using Rated Disabilities, I need to see the real data coming from within the VA to inform me of my status.

## Notes
- This will replace the dummy data with real data 

## Tasks
- Change the redux code so it uses the number from `FindRatingInfo`
- Update the endpoint the redux action is using and potentially update how errors are handled
- Check unit test still passes

## Acceptance Criteria
- [x] Data is being successfully received from `vets-api`
- [x] Frontend will confirm that the data received is coming from `vets-api`

**Comment by kathleencrawford** [comment]
Reopening this issue - there was some confusion between this issue and #2488 

2488 is for the dummy data and that is the one that should be closed, while this one is for the "real" api from evss, which is still blocked

**Comment by kathleencrawford** [comment]
the new endpoint within vets-api is:

.../v0/disability_compensation_form/find_rating_info_pid

**Comment by jason-gcio** [comment]
This still says it’s blocked, but I think it isn't anymore, correct?  We can take the dependency piece off if so.

**Comment by micahchiang** [comment]
@kathleencrawford - I noticed some discussion on your PR about potentially changing the name of the new endpoint to be a little more RESTy. If that happens, can you leave the new endpoint name here? Thx.

**Comment by kathleencrawford** [comment]
@micahchiang - here is the new name of the endpoint: /v0/disability_compensation_form/rating_info
