### ISSUE TITLE
Find a VA Form:  Add Online Tool URL to 28-1900 in CMS

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24870]
## User Story

As as user, I would like to have access to the new online tool landing page equivalent to form 28-1900 (URL https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/) from Find a VA Form so I have the option of using it rather than filling out a PDF. 

## Expected Behavior
The Find a VA Form landing page and the form detail page for form 28-1900 have links to the online tool URL 
https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/ 

## Acceptance Criteria

- [ ] Online Tool URL is added to the CMS
- [ ] CMS content is merged 
- [ ] Online tool button linked to https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/ appears on va.gov/find-forms when form 28-1900 is searched
- [ ] Online tool button linked to https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/ appears on https://www.va.gov/find-forms/about-form-28-1900/

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva - @jason-gcio said this is at 100% and they are ready to add the link as soon as we are able.  Thanks!

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO This has been updated and set to Publish for tomorrow.  Let's close after we validate this is live.

<img width="436" alt="28-1900 Online Tool Link" src="https://user-images.githubusercontent.com/63107147/118695100-cb824d80-b7da-11eb-9965-f858a1606877.png">

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @johnhashva !  I'll take a look in the morning and validate.

**Comment by MarciMcGuireGCIO** [comment]
Just confirmed the button is there and links to the correct page. Thank you, @johnhashva ! Cc @jason-gcio
