### ISSUE TITLE
CT Redesign: Create comparison view page

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#24874]
As a Comparison Tool user, I need to be able to compare institution details for institutions that I am interested in using my benefits at so I can make an informed decision about which institution to attend.

## Assumptions:
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/
2. The implementation of the remove / highlight UI interactions is out of scope, this story will simply add the UI elements on the page.
3. This will leverage the service #25219 
4. AC6 will use placeholder values and the real amounts will be added in a follow-on story.

## Acceptance Criteria:
1. When the user clicks the "Compare" button in the compare drawer on the search results page they are taken to the compare page.

2. The Compare page has a header:
    a. Displays informational content:

     > **School comparison:**
     > View school information side by side to compare schools

    b. Displays the name and city, state / city, country location of each institution selected for comparison.
    c. That is "sticky" so as the user scrolls down the page, the names of each institution remain within view.
    d. While the header is at the top of the page, the location information is displayed as a part of each school card.
    e. While the header is "sticky" and below the top of the page the location information is not displayed as a part of each school card.

3. There are six sections to the page:
    a. Summary    
    b. Your estimated benefits
    c. School ratings
    d. Cautionary information
    e. Academics
    f. Veteran programs

4. The "Summary" section displays the following information for each institution:
    a. Accreditation
    b. GI Bill students
    c. Length of program
    d. Type of school
    e. Institution locale
    f. Size of school
    g. Specialized mission (Men-only, Women-only, Religious, HBCU)

5. The "Your estimated benefits" section has the following subsections:
    a. Payments made to school
    b. Payments made to you

6. The "Payments made to school" section displays the following information for each institution:
    a. Tuition and fees
    b. GI Bill pays to school
    c. Out of pocket tuition

7. The "Payments made to you" section displays the following information for each institution:
    a. Housing allowance
    b. Book stipend

8. The "School ratings" section has the following subsections:
    a. Education ratings
    b. Veteran friendliness

9. The "School ratings" section displays the following information for each institution:
    a. Overall rating
    b. # of veteran ratings

10. The "Education ratings" section displays the following information for each institution:
    c. Overall experience Rating
    d. Quality of classes Rating
    e. Online instruction Rating
    f. Job preparation Rating

11. The "Veteran friendliness" section displays the following information for each institution:
    g. GI Bill support Rating
    h. Veteran community Rating
    i. True to expectations Rating

12.  The "Cautionary information" section displays the following information for each institution:
    a. Caution flags
    b. Student complaints

13.  The "Academics" section displays the following information for each institution:
    a. Credit for military training

14. The "Veteran programs" section displays the following information for each institution:
    a. Yellow Ribbon
    b. Student Veteran Group
    c. Principles of Excellence
    d. 8 Keys to Veteran Success
    e. Military Tuition Assistance (TA)
    f. Priority Enrollment

16. If there are less than 3 institutions being compared:
    a. There is a placeholder for an institution to be added.
    b. The user has the ability to return to the search page.

## Supporting Artifacts:
1. [Prototype - Compare two schools](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/296060323_CT_Redesign_PI10_Desktop_ComparePg_only2)

2. [Prototype - Compare three schools](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/296060322_CT_Redesign_PI10_Desktop_ComparePg)

3. [Prototype - Sticky header](https://bahdigital.invisionapp.com/share/ACIAGXRSM9P#/296060325_CT_Redesign_PI10_Desktop_ComparePg_OnScroll)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17554

**Comment by delli-gatti-michael** [comment]
Local teting complete

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1935)

**Comment by delli-gatti-michael** [comment]
Changes are on Staging. Closing this issue
