### ISSUE TITLE
General Analytics Request for Auth experience: Add tag to track "Delete" action for contact information in user profile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#24876]
# Metrics Reporting Request

## Description

**Who is this request for?**

Authenticated experience
    
**What project is this work for?**

We are looking to better understand whether people are actually deleting their contact information from the user profile (https://www.va.gov/profile/personal-information) or whether this particular action isn't used. We are considering removing the delete functionality and are looking for analytics that will help either support this decision or show evidence to the contrary.

**What type of analytics support are you looking for?**
  - [x] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [ ] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [ ] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    
## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._

**What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?**

This is not bound to a deadline, but hopefully we'd get some insights within the next month or so if that is possible given the analytics team current backlog. If it will take a few weeks to get to this request, that's fine. Please just let us know.

## Analytics to Track Down

We need tracking on how many people deleting contact information from their user profile.

This is the URL: https://www.va.gov/profile/personal-information

Delete functionality needs to be tracked for:

- Home address
- Home phone 
- Mobile phone
- Work phone
- Fax number
- Email address

Please note that Mailing address currently *does not* have a delete option, so that's why it is not included in the list above.

Here is a screenshot of the link we're talking about:

<img width="595" alt="Screen Shot 2021-05-18 at 1 29 41 PM" src="https://user-images.githubusercontent.com/34068740/118697326-2d43b700-b7dd-11eb-8e05-988c3866b52d.png">

## Which Product Questions are you trying to answer?

As stated above, we are looking to better understand whether people are actually deleting their contact information from the user profile (https://www.va.gov/profile/personal-information) or whether this particular action isn't used. We are considering removing the delete functionality and are looking for analytics that will help either support this decision or show evidence to the contrary.

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

If you'd like to view the contact information section of the profile on staging, you can do that via **any staging user** at https://staging.va.gov/profile/personal-information.

We would also love to see this information within the context of our [existing contact information dashboard](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/3Z1vT6SlQqevdav1s72QwA/a50123418w177519031p176188361/). However, we understand right now that dashboards aren't getting updated, so if we can only getting tagging now and not a dashboard update, that is completely fine. Just let us know.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by Samara-Strauss** [comment]
@ajakabcin @andaleliz tagging you all for awareness that this request has been submitted.

**Comment by andaleliz** [comment]
@erikphansen and I were discussing this, and he mentioned that he can send events to Google Analytics.  I know how to find events in Google Anayltics via the Behaviors section; if the GA team has a large back log, is implementing an event tag ourselves something we can explore? We could follow the same pattern on for the save event.

**Comment by Samara-Strauss** [comment]
> is implementing an event tag ourselves something we can explore? We could follow the same pattern on for the save event.

Is this a question for me or for the analytics team? I think if we have folks who are able to correctly do this themselves, then all help is welcome. But, I would confirm that with the analytics team first. I am all for taking work off their plate if people on our team have the capability to do that!

**Comment by andaleliz** [comment]
>Is this a question for me or for the analytics team?

I meant more for the analytics team, as I'm not sure how they feel about people sending events that they didn't set up themselves. Things could get really messy if every team did this anytime they wanted.  @joanneesteban let me know how your team feels about this, because we would be happy to take this off your plate if that's easier and acceptable to you.

**Comment by erikphansen** [comment]
+1 to Samara. I'm also looking forward to Liz showing me how to make sense of GA! 😆

**Comment by Samara-Strauss** [comment]
Closing! @bsmartin-ep is a genius and realized [we are already tracking delete events](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=Profile%20-%20Delete/) Thank you, Brian!
