### ISSUE TITLE
Find a VA Form: Mock up adding links to Related Forms on Detail Pages

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24889]
## User Story

As a User, I want to be able to access details about a related form directly from a form detail page so that I don't have to conduct another search for that information.

## Expected Behavior

If a form is listed under Related forms and instructions on _another_ form's detail page, its title should link to its own detail page.  Example screen shot below.  Actual page can be viewed at https://www.va.gov/find-forms/about-form-21-686c/.  Links would be added for two forms listed under "Related forms and instructions"

![image](https://user-images.githubusercontent.com/73354907/118712488-d8a93780-b7ee-11eb-95a9-7f26055ef64d.png)

## Acceptance Criteria

- [ ] Create mockup of detail page with hyperlinked form title according to the Design System - question possibly for Ryan - should this also be consistent with the [Search Consistency UI work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23458)?
- [ ] Collaborate with Design and Accessibility to confirm the design approach does not present any design or accessibility issues
- [ ] Let PM know when a design intent review can be scheduled
- [ ] Present at design intent review 
- [ ] Incorporate feedback from Design
- [ ] Add Sketch links to this ticket for future reference

**Comment by MarciMcGuireGCIO** [comment]
@cassandra - if you can take a look and estimate this one, that would be great.  Thank you!

**Comment by callen2563** [comment]
@MarciMcGuireGCIO I have a question on this one do you have a few minutes to day to chat?

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 we are going to roll this work in with the PDF link work you've already mocked up.  Do you want to have two separate design intent reviews or just one?  Thanks!!

**Comment by callen2563** [comment]
@MarciMcGuireGCIO I think we can have one design intent for both

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 Ok!  They have a block this Friday at 2:00 PM ET, next Tue at 11:00 and 11:30 AM ET.   Let me know which one you want and I'll request it.

**Comment by MarciMcGuireGCIO** [comment]
Hey! I couldn't find a mock-up for the "related to" to add to the design intent review, so once you get a chance to mock that up I'll schedule another one to go over that one.

**Comment by callen2563** [comment]
@Marci I mocked the page mentioned above up and added some UI design consistency tweaks such as the online tool active link and the download pdf icon as well as the under lined related links.

[FAF - Detail Page .pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6618128/FAF.-.Detail.Page.pdf)

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @callen2563 !  That looks really good!  😄 cc @zacharymorel @johnhashva

**Comment by zacharymorel** [comment]
Thank you @callen2563 !
