### ISSUE TITLE
Discovery: Why is RAILS_ENV=production across all environments

### ISSUE THREAD

**Issue by jeff2d2** [department-of-veterans-affairs/va.gov-team#24881]
## Goal

- Discover why all environments have `RAILS_ENV=production`.
- [Originating Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1620995547388300) for background.
- We're conducting this discovery to determine if #24868 is even necessary.

## Acceptance Criteria

- [x] Reasoning for why `RAILS_ENV=production` across all envs has been determined and documented

**Comment by LindseySaari** [comment]
There's also some useful information near the bottom of [this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1618947662225900)

**Comment by thilton-oddball** [comment]
Responses from Ops:

- dev ,staging, & prod should all mirror one another as closely as possible
- RAILS_ENV=development is only used for local development. Any deployed environment should have RAILS_ENV=production
- configuration differences are handled by settings.yml which is different for each environment
