### ISSUE TITLE
[new] Content updates to Secondary Family Caregiver (2) applicant information

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#24890]
In order to keep Secondary Family Caregiver (2) consistent with Secondary Family Caregiver, the following content changes should be made:

[ ] 1. Secondary Family Caregiver’s (2) applicant information change to: **Secondary Family Caregiver (2) applicant information**

[ ] 2.  **Please complete the following information about the Secondary Family Caregiver (2).** Should be added before Secondary Family Caregiver’s (2) first name

![Screen Shot 2021-05-18 at 3.56.50 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/d5a19ee6-6aa2-492c-b020-c2c8ac1c2adc)

## Secondary Family Caregiver EXAMPLE
![Screen Shot 2021-05-18 at 4.01.37 PM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/030a1d7c-0032-48f7-b5e2-4b171193106c)

**Comment by dat-gcio** [comment]
@Dene-human Review instance [link](http://bbd0875a31872246944870ca6e55d2ab.review.vetsgov-internal/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)

**Comment by Dene-human** [comment]
Looks good! Thank you!
