### ISSUE TITLE
Populate questions for ORDMI/Harassment initiative questionnaire 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#24896]
## Issue Description
_In response to the ORDMI/Harassment initiative, we've started a questionnaire that we would like to populate with items we need to know or would like to know as we posture to support this coming initiative._

The questionnaire can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/questionnaire.md)

## Front end tasks
- [ ] Please populate related questions for your specific functional area on the questionnaire document  
- [ ] PM/PO will validate all comments have been provided and formulated in support of push back to ORDMI stakeholder feedback
- [ ] PO will disseminate to ORDMI office in support of fact finding/discovery prior to our next session 
- [ ] PM will explore weekly touch point with ORDMI project coordinators as a touch point to review items of interest and ensure implementation is tracked and synced accordingly

**Comment by cindymerrill** [comment]
I've added some Research questions to the questionnaire document. See what you think, @brianalloyd @johnhashva

**Comment by johnhashva** [comment]
@cindymerrill you can find lots of documentation -- including service design -- in the ORDMI/PIF links on this page -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/read-me.md

**Comment by cindymerrill** [comment]
@johnhashva I looked at that page again, and I don't think that it answers any of the research questions I added, except maybe the service blueprint one (I added a link into the questions document to reflect that). And I don't really understand the service blueprint, so I think it would be helpful to meet with them (Soni?) for more information. I can't plan user research when I don't understand what's been done and what needs doing.

**Comment by johnhashva** [comment]
@cindymerrill let's discuss at today's PW planning session.

**Comment by cindymerrill** [comment]
I revised my Research questions after reading John's email from Soni.

**Comment by brianalloyd** [comment]
Responses received, reviewed and pass along for ORDMI review.
