### ISSUE TITLE
Remove cancel appointment link for past appointments

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#24903]
## What happened?
Past appointments should not have the cancel appointment link

## Specs:
- Device: MAC
- Browser: Chrome
- Finding from: #24020

## Steps to Reproduce
1. Go to URL: health-care/schedule-view-va-appointments/appointments/past
2. from the past appointment list page, click on any appointment to a VA facility to display its detailed page

![image.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/9e55539e-bc29-4709-9aa0-7e79f3950817)

## Desired behavior
Remove the Cancel appointment link from past appointments

## Acceptance Criteria
- [ ] Cancel appointment link no longer displays in past appointments

**Comment by laurenernest** [comment]
Good catch! I created another ticket based on this one for the add to calendar link. #24913

cc @outerpress
