### ISSUE TITLE
GitHub milestones (sprint) report

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24904]
## Description
Repeatable way to pull a list of tickets associated to a GitHub milestone for use in determining demo agendas.

Milestone list example: https://github.com/department-of-veterans-affairs/va.gov-team/milestone/629

Milestone data in issue
![Screen Shot 2021-05-18 at 3.12.24 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/741416a8-f70a-48ce-9ec3-65e97fc3ece5)

---
## Tasks
- [ ] Milestone spreadsheet with the following data:
- Issue title
- Assignee
- Issue link (either GH or ZH)

**Comment by jbalboni** [comment]
I have a page that takes a milestone id and outputs the list of issues in markdown grouped by author:

![Screen Shot 2021-05-20 at 11.44.28 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/a524c44f-03f7-4c80-8901-38974ab16f9a)

I've uploaded it [here](https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/products/health-care/appointments/va-online-scheduling/product/milestonereport.html). You can save that file locally and then open it in Chrome and you should be able to generate the list.

Let me know if that works or if there are better formats.

**Comment by laurenernest** [comment]
COOL! This works. Closing ticket
