### ISSUE TITLE
Call Center Escalation Path

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#24900]
How will the contact center teams (VA.gov and HRC) let us know whether they are hearing a substantial number of issues with the app from folks calling in?

- 5/25: Meeting tomorrow with call center team

Notes:
- 6/7: Brenda would prefer email, they'll add us to their list.
- 6/3: Confirming with Brenda that she is comfortable using slack, she's been added to #va-mobile-app-alerts. Let's be clear with them about what "urgent" means = security breach, and complete outage. Note that if we take the app down, we're not removing it from people's phones, but we could turn off the APIs so that people who still have the app won't be able to do things with it.

- 5/27: If it's very urgent, call center team will Slack us, if it is a more minor but recurring issue, they will create a Github issue and tag us (on a separate board)

**Comment by ayushchak** [comment]
Flagging - this will be discussed at our 5/24 meeting with Chante

**Comment by ambikaroos** [comment]
If it's very urgent, call center team will Slack us, if it is a more minor but recurring issue, they will create a Github issue and tag us (on a separate board)
