### ISSUE TITLE
[VAMC]  Validate that react widgets are enabled in top task pages [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#24917]
## STORY
As a Veteran I need to know the reaction alerts work, so I can get the resources and information in each section.

## GOAL
Enable react widgets to work properly.

## TASK
_Validate that all Enable React widgets for Pharmacy, medical records, and Suicide prevention are enabled.
1) Open Reach Widget on page, confirm that "Call to Action Widget" is enabled.
2) "OPTION"  You can also test all published pages and widgets by going to System URL and page and test widget

**Complete for the following VISNs and Systems:
_
- [x] VISN-2
- [x] VISN-4
- [x] VISN-6
- [x] VISN-7
- [x] VISN-8
- [x] VISN-16
- [x] VISN-17
- [x] VISN-19
- [x] VISN-21
- [x] VISN-23

## ACCEPTANCE CRITERIA
* All listed systems have been validated that react widgets are enabled.

**Comment by kevwalsh** [comment]
Hey @SgardnerPMP i did an [audit](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2920) a couple days ago that shows all the places where this checkbox is not checked, but should be. 

![Screenshot_2021-05-19__10_33_AM](https://user-images.githubusercontent.com/643678/118831332-b0bce100-b88d-11eb-89d5-6f577ccdb1d3.png)
