### ISSUE TITLE
[Design] Vaccine walk-in messaging specs

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#24912]
## Description
All VAMCs now allow walk-ins for the COVID-19 vaccine. We should add related messaging to appropriate areas in VAOS.

Pages/states to consider:
- Dead ends: Contact a Facility

### Content
- Related content already exists on the VA's COVID-19 page https://www.va.gov/health-care/covid-19-vaccine/#how-to-get-a-covid-19-vaccine-
- Facility Locator may also do work with walk-in messaging

### Design assets
- [Sketch file](https://www.sketch.com/s/2d26a3f6-095d-4c26-869f-a41b6caca1f5)
- [Overview](https://www.sketch.com/s/2d26a3f6-095d-4c26-869f-a41b6caca1f5/a/bgoyr04)
- [Mobile template](https://www.sketch.com/s/2d26a3f6-095d-4c26-869f-a41b6caca1f5/a/52YrxmL#Inspector)

**Comment by outerpress** [comment]
First pass designs below.

A couple assumptions I'm working with ( @lalexanderson-dsva fyi if there are other/different considerations for this):
- Even with walk-in clinics broadly available, it's more convenient for some Veterans to have a scheduled appointment than to visit a walk-in clinic. 
- Knowledge of walk-in clinics will be widely spread among Veterans who are likely to schedule online via VAOS
- So, helping Veterans find walk-in clinics should be a fallback for when no facilities offer online scheduling
- We shouldn't be directing Veterans to find walk in clinics if they already received their first dose

@peggygannon I drafted some rough language, could you review/recommend refinements?

![24912-walk-in scheduling.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/fe47cf55-23da-4b23-91a0-17d6695f70cb)

**Comment by peggygannon** [comment]
Hi, @outerpress Here's a recommendation on the VAOS walk in clinic alert.  

And no, I'm not currently working with the preferred facilities team on a similar alert (I believe they are working with the sitewide content team). I recommend you check  the preferred facilities team to see if they have an alert for this already.  We should make sure these alerts are consistent across the different tools. 



**Find a vaccine walk-in clinic near you**
You can go to a VA facility's vaccine clinic during walk-in hours to get the COVID-19 vaccine. You don't need an appointment, but be sure to check the facility's walk-in hours before you go.

**Comment by outerpress** [comment]
@peggygannon sounds good to me. I updated the overview with the new language [here]( https://www.sketch.com/s/2d26a3f6-095d-4c26-869f-a41b6caca1f5/a/bgoyr04)

@laurenernest I think this is GTG.  I added design assets to the description - let me know if D/T templates would be helpful for this change and I'll whip them up.

@mmiddaugh FYI this is the language VAOS is looking at using for walk-in clinics, in case it's useful when the FL team starts similar work

**Comment by laurenernest** [comment]
@outerpress that message is in a design system component, right?

**Comment by outerpress** [comment]
@laurenernest So...yes. But. I just checked and it looks like some of the guidance around the component we're using has changed.

I believe those are using the [background-only alert](https://design.va.gov/components/alertboxes#background-color-only). Looking at the design system there's only the info option now, and guidance to use those "only for immediate feedback...not for static messaging"

This usage is closer to "messaging" (without quibbling with the word static) so we should change those to use the [featured content component](https://design.va.gov/components/featured-content)

**Comment by laurenernest** [comment]
Added the component info to the dev ticket. Closing this request.
