### ISSUE TITLE
Request edit access to Domo

### ISSUE THREAD

**Issue by rebekahickey** [department-of-veterans-affairs/va.gov-team#24929]
## User Email Address
rebekah.hickey@adhocteam.us

## Access Requirements
Please check the analytics tools you need access to:
- [ ] Google Analytics
- [X] Domo
- [ ] (Platform Teams only) BigQuery

_Please list any additional requirements, if any._
I already have a Domo account; I'm requesting elevated permissions in Domo so that I can connect to a data source (a Google sheet) and create/edit a dashboard.

## Date Required
By end of week would be great.

## Product Team / External Team / VA Office
Platform Service Design team.

*Please leave the following blank*

---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by laurensimpson14** [comment]
@rebekahickey I've given you edit access in Domo & you should be all set! Feel free to re-open this ticket if there is anything else I can help you with.
