### ISSUE TITLE
[Discovery] Discharge Upgrade Wizard - Link change ONLY for Air Force Veterans directed to DD149

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24928]
Determine level of effort to implement a change that will only be seen by Air Force Veterans who are currently directed to DD149

Page https://www.va.gov/discharge-upgrade-instructions/guidance appears to be shared by multiple branches, and this requested change will only apply to Air Force.

**Comment by zacharymorel** [comment]
SEE => https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-update/dw-content.md

**Comment by zacharymorel** [comment]
Another doc worth of note => https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-update/dischargemaintenancedoc.md
