### ISSUE TITLE
White flash during app launch

### ISSUE THREAD

**Issue by travis-newby** [department-of-veterans-affairs/va.gov-team#24927]
## What happened?
iOS: When launching the app, the launch screen is white and contains the text 'VAMobile'. This is the default launch screen for a React Native app.

Android: When launching the app, the launch screen is white / does not contain any text.

## Specs:
iOS:
- Device: iPhone XS
- OS: iOS 14.5.1

Android:
- Device: Samsung Galaxy S9

## Steps to Reproduce
- Force close app
- Launch app

## Desired behavior
When launching the app, the launch screen should be the same color as the background of the app, and should not contain any text. Ideally if the app has a blue background, the launch screen will be a matching blue.

## Acceptance Criteria
1. Launch screen is the same color as the background of the app: #003E73
2. Launch screen does not contain any text

## Bug Severity
- 4- low

## Linked to story
N/A

## Screenshot
![Image from iOS (3).png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/6e2928fa-2bc6-4d99-83ef-cfe23ebd5f13)

## Video
https://images.zenhubusercontent.com/133843125/87e2eab3-f7cb-4586-946e-81e69b8751ce/image_from_ios__1_.mov

**Comment by lexicalninja** [comment]
will need to update the launch screen file in xcode to just be a blue background.
Will need to check android builds for the same issue

**Comment by digitalken** [comment]
PASS 6/18/2021 - Launches with blue background, looks good on iOS.  Closing.
