### ISSUE TITLE
[vaos service requests] Convert Community Care supported sites check

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#24935]
Instead of calling the supported sites endpoint, we want to call the scheduling/configurations VAOS service endpoint and check the communityCare flag.

Tasks
- [ ] Update getLocationSettings service function to switch between current endpoints and /vaos/v2/scheduling/configurations endpoint based on a feature flag parameter
- [ ] Create transform for scheduling configurations data, if necessary (the data format we currently use should be pretty close to what comes back from the VAOS service)
- [ ] Update CC eligibility check to call getLocationSettings with vaos service requests flag instead of supported sites fetch

AC
- [ ] Community care supported sites are checked through the scheduling configurations endpoint when the vaos service requests flag is on

**Comment by laurenernest** [comment]
no additional validation needed at this stage. closing ticket.
