### ISSUE TITLE
COVID-19 vaccine confidence campaign landing page_

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#24940]
## User story

As a Veteran who has questions before deciding whether to get a COVID-19 vaccine, I need accurate and clear answers.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here you go. Just a few minor copy tweaks and I had one question that I put in the comments.
[Vaccine confidence campaign landing page_FAQs content_05.18.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6510448/Vaccine.confidence.campaign.landing.page_FAQs.content_05.18.21.docx)

**Comment by DanielleThierryUSDSVA** [comment]
page is live - closing!
