### ISSUE TITLE
Change Sorting of Daily Summary Report Email

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#24945]
## Background
The stakeholder has asked if the RO list can be organized and grouped via RO instead of by date arrived.

## Tasks
- [x] Sort the summary results so that they are grouped by Regional office and not by arrival time, all on one contiguous list

## Acceptance Criteria
- [x] The summary email is sorted by RO

**Comment by RudyOnRails** [comment]
Merged https://github.com/department-of-veterans-affairs/vets-api/pull/7320
