### ISSUE TITLE
(HOLD) [vaos service requests] Convert request list and details page tests to VAOS service

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#24946]
Update our request list and details page tests to have the vaos service requests flag on.

This work should be done post prod release or very near to it.

Tasks
- Update mocked data in each test to use mock data and helpers for the VAOS service
- Create any new mock helpers needed

AC
- [ ] Tests use vaos service requests flag and associated vaos service endpoints
- [ ] New mock data matches the scenarios created by the old mock data.

**Comment by JRRoof** [comment]
Old ticket.   No longer relevant.
