### ISSUE TITLE
[FE] Profile, DD: Update focus upon "edit" so first field is announced immediately

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#24952]
## Background
Following work on #23168 a minor issue was noted regarding how the focus is managed upon the user activating the "edit" button:

_- Focus should be managed when the user activates "edit", focus should be sent to the first field so it is announced immediately and is visible to keyboard users with the yellow halo_

 [See Josh's comments and supporting video for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23168#issuecomment-844233581)

## Tasks
- [x] Update focus upon "edit" so that the first field is announced immediately and is visible to keyboard users with yellow halo
- [x] This update should apply to all contact info fields in profile as well as edit fields on Direct Deposit

**Comment by erikphansen** [comment]
This can be validated on staging once https://frontend-support-dashboard.vercel.app shows hash 68995de7ddad8ea1d42911296e014315f007ae07 as being on staging

**Comment by ajakabcin** [comment]
Hey @joshkimux or @AngelaFowler82 would you be able to give this a look? Thanks in advance!

**Comment by joshkimux** [comment]
Great work @erikphansen as always! 🥳 

https://user-images.githubusercontent.com/14154792/125506420-77ea6d3c-c172-40d4-bd0b-4b99dbcc712e.mov

**Comment by AngelaFowler82** [comment]
I chose “Edit direct deposit information,” and it dropped me right into the “routing number” field and read all pertinent information. Bravo!
