### ISSUE TITLE
Content recommendation for Vet Center service descriptions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#24959]
### What is your documentation request, question, comment, or issue?
Give us whatever details you have, but vague requests are welcome. We'll follow up with you within 3 business days and let you know if we have questions or need more information. 

## Background
Although Vet Centers generally offer the same services nationwide, the ways in which those services are offered are very dependent on the clinicians and staff at a given location - and the Veterans they serve. Opportunities to convey local "flavor" is an important piece of our new Vet Center pages. 

Within the Vet Center service accordions, there is an opportunity for the local staff to describe the ways a particular service is offered at the location. For some of these accordions, the list could be extensive if every counseling group, whole health offering, or treatment modality is listed. In particular, we're running into issues with evidence-based treatments. 

The type(s) of evidence-based treatments available depends on the clinicians on staff. Some of our pilot Vet Centers rollout have up to 6 different types of evidence-based treatments listed - in addition to the counseling groups and other service offerings which might be listed within the Mental health or PTSD service. 

## Example

![image](https://user-images.githubusercontent.com/55411834/118859996-1a41ed00-b898-11eb-8b41-4661693d607d.png)

## Problem to solve 
Balance the need for Veterans to see that these particular types of treatments are available (and which modalities) while communicating that the description isn't all-inclusive/comprehensive.  

## Questions
Looking for recommendations on 

- the ideal number of bullets within a section
- appropriate intro text to give context to the list as examples of the types of services Veterans can expect
- best way to say "and more" (or something similar)

**Comment by peggygannon** [comment]
thanks, @gmaciolek.  

@mmiddaugh this content support request should be routed to the sitewide content team. 
The Vet Centers staging review is scheduled for tomorrow. But it sounds like the content is still being worked out. Can you confirm if the Vet Center content posted in the staging ticket is ready for review ?  

cc @shiragoodman

**Comment by mmiddaugh** [comment]
There's no specific content review needed for the staging review.

**Comment by shiragoodman** [comment]
@mmiddaugh I'm aware that much of the Vet Center content will be provided by the centers content editors, but isn't there a template that is in use that would have pre-determined content?

**Comment by gmaciolek** [comment]
Following up on this: @mmiddaugh is this ticket still needed? If so, @shiragoodman and @peggygannon is there someone else it should be assigned to?

**Comment by mmiddaugh** [comment]
This can be closed
