### ISSUE TITLE
CANCELED status on 'Requested' page only displays after page is reloaded.  

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#24964]
1. Enter VA request in VAOS. 

- Cancel in VAOS.  Return back to request page.  

- There is no status of cancel (cancel in dark grey status outline).  

- If you look at the details it shows cancelled but the status of cancel in dark grey outline is missing on the summary list.  Because of this I wondered did I really cancel it.  ![CancelStatusNotDisplayed.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/48fdc3a8-22de-4154-8ded-59aa039f4217)

- Once you refresh or reload the page then the cancel in dark grey status outline displays.

**Comment by jbalboni** [comment]
@marcynadeau Lance and I can't reproduce this in staging, is it still happening for you?

**Comment by marcynadeau** [comment]
@jbalboni No. It is no longer happening.
