### ISSUE TITLE
Resolved and Booked Requests Display as Pending in VAOS

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#24965]
Enter VA request in VAOS.  Sign out of VAOS.  Resolve in Scheduling Manager.  Log back into VAOS.  Request still shows as Pending on VAOS request page. 

Enter VA request in VAOS.  Sign out of VAOS.  Book in Scheduling Manager.  Log back into VAOS.  Request still shows as Pending on VAOS request page. 

Enter CC request in VAOS.  Sign out of VAOS.  Resolve in Scheduling Manager.  Log back into VAOS.  Request still shows as Pending on VAOS request page. 

 Enter CC request in VAOS.  Sign out of VAOS.  Book CC  appt in Scheduling Manager.  Log back into VAOS.  Request still shows as Pending on VAOS request page.  Note the appt does display in upcoming appointments.

![BookedVAApptDisplaysPending.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/6e07d885-9bec-4cd5-9212-4d4e14694fde)![ResolvedCCDisplaysAsPending.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/c726e899-8306-4ec6-b8ff-1f8725db9e4f)

**Comment by jbalboni** [comment]
Note: we're not doing the status filtering that we're doing on the current upcoming appointments tab for requests. We need to carry that over and display just proposed and cancelled requests.
