### ISSUE TITLE
Language assistance and resources: Patient advocacy and main page content (issue 2 of 3 for this work)

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#24963]
## User story

As a Veteran, caregiver, or family member, I need to know how to connect with a patient advocate to get language assistance and help to resolve problems at a VA health facility.

As someone with limited English proficiency, I need this information in my first language.

## Issue description

- [x] Finalize content (Danielle)
- [x] Copy edit (Randi)
- [x] Share with translators (Randi)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht! Here's the page for copy editing. And then as soon as we're finished with that, let's get this off to the translation team. Thank you!

[VA.gov_language assistance and resources content for translation_05.18.21](https://app.zenhub.com/files/133843125/69abcb8c-5412-4735-a113-8572e96033f8/download)

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Quick note that I just updated the doc and reposted above. Just in case you downloaded already!

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here you go. Just a few copy tweaks. I'll send it to the translation team now.
[VA.gov_language assistance and resources content for translation_05.19.21.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6510957/VA.gov_language.assistance.and.resources.content.for.translation_05.19.21.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @RLHecht!! 

FYSA @SKasimow
