### ISSUE TITLE
Use TestRail API to store all relevant data in BigQuery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#24979]
# Description
* Use the TestRail API to retrieve all relevant data and store it in BigQuery. We want to store as much data as possible from TestRail in order to enable us to create new metrics or combine data in novel ways in order to create new metrics in the future.
* Recreate similar data structures in BigQuery as the data is extracted from TestRail. Include at a minimum the below set of TestRail objects:
  * Cases
  * Configurations
  * Milestones
  * Plans
  * Projects
  * Results
  * Runs
  * Sections
  * Shared Steps
  * Suites
  * Tests
  * Users
* Create views of raw data in BigQuery to feed cards in Domo

## BigQuery Features to Keep in Mind
* Queries cost money based on how much data is retrieved for the query (1GB = $.01 or so)
* BigQuery is designed for de-normalized data structures. We should prefer this where possible. But, don't be afraid to use lookup tables to convert code / other signifiers to a more human readable format.

**Comment by holdenhinkle** [comment]
Here's the link to the new Testing Tools Team Dashboard Data repo - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data

This repo consists of a Node app with a GitHub workflow file that fires a scheduled event every day at 12am. The workflow file calls a GitHub action that:
- Deletes a number of TestRail tables (see below), creates the tables again, then does a bulk insert into each table. (This process ensures that the tables are up to date daily with TestTail.)
- Inserts a row of computed TestRail metics (see below) into the `testrail_metrics` table

All of the data from the following TestRail tables are stored in BigQuery and updated daily via GitHub scheduled event:
- users
- projects
- runs
- tests
- cases
- configs
- milestones
- plans
- priorities
- results
- sections
- suites
- statuses

The app uses the [testrail-api package](https://www.npmjs.com/package/testrail-api). Unfortunately, the package is not up to date and does not include functions to hit the new [Shared Steps endpoints](https://www.gurock.com/testrail/docs/api/reference/api-shared-steps#getsharedsteps).

The following is an example of the computed metrics that are inserted into the `testrail_metics` table once a day:
```
[
  {
    total_vfs_teams: 22,
    total_users: 23,
    total_active_vfs_teams: 10,
    percent_active_vfs_teams: 45.45454545454545,
    total_active_vfs_users: 6,
    percent_active_vfs_users: 26.08695652173913,
    created_at: BigQueryDatetime { value: '2021-05-24 18:10:27.775' }
  }
]
```

The following is logged to the terminal after the action is complete:
```
Table testrail_users deleted.
Table testrail_users created.
Inserted 38 rows
Table testrail_projects deleted.
Table testrail_projects created.
Inserted 33 rows
Table testrail_runs deleted.
Table testrail_runs created.
Inserted 731 rows
Table testrail_tests deleted.
Table testrail_tests created.
Inserted 2385 rows
Table testrail_cases deleted.
Table testrail_cases created.
Inserted 1439 rows
Table testrail_configs deleted.
Table testrail_configs created.
Inserted 31 rows
Table testrail_milestones deleted.
Table testrail_milestones created.
Inserted 432 rows
Table testrail_plans deleted.
Table testrail_plans created.
Inserted 83 rows
Table testrail_priorities deleted.
Table testrail_priorities created.
Inserted 4 rows
Table testrail_results deleted.
Table testrail_results created.
Inserted 1187 rows
Table testrail_sections deleted.
Table testrail_sections created.
Inserted 181 rows
Table testrail_suites deleted.
Table testrail_suites created.
Inserted 33 rows
Table testrail_statuses deleted.
Table testrail_statuses created.
Inserted 5 rows
Inserted 1 rows
```

**Comment by holdenhinkle** [comment]
To do:
- Convert the following `json` files into BigQuery tables:
  - [Project to ignore](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/blob/master/src/testrail/dataToIgnore/projects.js)
  - [Users to ignore](https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/blob/master/src/testrail/dataToIgnore/users.js)
- Create a table that maps TestTrail Project names to VFS Team names
- Finish writing unit tests

**Comment by holdenhinkle** [comment]
testrail_projects_to_ignore - https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3stestrail_projects_to_ignore&page=table&d=vsp_testing_tools&p=vsp-analytics-and-insights&t=testrail_projects_to_ignore

testrail_users_to_ignore - https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3stestrail_users_to_ignore&page=table&d=vsp_testing_tools&p=vsp-analytics-and-insights&t=testrail_users_to_ignore

**Comment by holdenhinkle** [comment]
CI steps for creating a Cypress Mochawesome Report and posting the Cypress test results to BigQuery:

### Step 1
Cypress tests are divided into n steps, each step running an arbitrary set of Cypress tests in a Docker container, each container running in parallel. While Cypress tests are being executed in each container, Mochawesome will generate a `json` results file for each spec. After the Cypress tests have completed, the `json` files will be copied to the host into a the `cypress/report/mochawesome-report` directory. 

### Step 2
This CI step is dependent on Step 1.

This step will merge the `json` files (creating a `mochawesome.json` file), generate the Mochawesome report, rename the report from `mochawesome.html` to something like `2021-05-26T12:29:50.898Z.html` (a date-time string) and post the report to a GitHub repo for serving the static Mochawesome reports. The directory structure will look like this:

```
mochawesome-reports
  assets
  2021-05-26T12:29:50.898Z.html
  2021-05-26T12:11:50.898Z.html
  2021-04-26T11:15:50.898Z.html
```

### Step 3
This CI step is dependent on Step 2  because we need the name of the Mochawesome report that was generated. This step will parse the `mochawesome.json` file into row objects that will be inserted in two BigQuery tables. While parsing the `json` file, a field called `mochawesome_report_link` will be created that will be set to the url of the new report in the GitHub static site.

**Comment by holdenhinkle** [comment]
This is complete.

**Comment by pjhill** [comment]
MVP of TestRail data ingest is complete -- nice work!
