### ISSUE TITLE
Implement UI Consistency Elements on Global Search - Part 1

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24972]
## Description

Search UI Consistency elements have been defined as part of this joint effort - Detail in Epic #21055. These UI elements need to be updated on all global search pages to align with the design system addition. 

## Background/Context

[Desktop](https://vsateams.invisionapp.com/console/share/SD10IE31CENR)
[Mobile](https://vsateams.invisionapp.com/console/share/8Y10IE2JN2J4)
[Spreadsheet](https://docs.google.com/spreadsheets/d/1KnkaMDBeOZUR9n1sG_w3JB1cpAWvg-rWOLuJPjbUwsI/edit?usp=sharing)

[Epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21055)

## Tasks

- [ ] initiate changes to address the following global design needs:

1. Link Header
2. Header Link a:visited
3. Header Link a:hover
4. Header Link a:focus & a:active
5. Search input, search button
6. Search input, search button a:hover
7. Search input, search button a:focus & a:active
8. Pagination
9. Page Header
10. Results Description – Style & truncation of the descriptions
11. URL
12. "Showing 1-10 results..."
13. Our top recommendations for you

 

## Definition of Done

- [x] This is a two part initiative, part 1 is complete when foundational work has been established and is ready for completion in part two.

**Comment by srsuddath** [comment]
Work has begun on this effort and will be completed in part 2
