### ISSUE TITLE
Find a VA Form: Design for adding download instructions for PDF links

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#24981]
## User Story

As a user, I need to be aware that I must download PDFs provided on Find a VA Form and fill them out using Adobe Acrobat or Adobe Acrobat Reader in order to fully complete and/or save them. 

## Expected Behavior

Search results and form detail pages for Find a VA form will provide user-friendly, visible information on downloading and opening PDFs documents.   

Context: There has been a known issue where some PDF forms will not open in web browsers.  After meeting with VBA stakeholders and their Adobe representative on 5/19/2021, we learned that the VA has invested in Adobe technology and plans to continue using digital signature fields in their PDFs.  VBA currently creates documents with Adobe Experience Manager's Forms Designer use XFA technology, which is not widely supported inside modern web browsers.  There is no plan to move away from XFA, so users will need to be instructed to download the PDF and open it with Adobe Reader (which is free) in order to fill it out.

It should be noted that search results can contain links to multiple PDF documents.  See example links below.

Search results: https://www.va.gov/find-forms/?q=10-10
Find a VA Form detail page example: https://www.va.gov/find-forms/about-form-10-10ez/

A couple of examples of how similar content is being provided:

- IRS: https://www.irs.gov/forms-pubs/trouble-downloading-pdf-files 
- VA.gov IRIS - https://iris.custhelp.va.gov/app/answers/detail/a_id/3047/~/problems-with-.pdf-forms-on-va-website - **note this was last updated in 2014 and no longer valid info**

## Acceptance Criteria

- [ ] Create design for PDF information in Find a VA Form search results   - example: https://www.va.gov/find-forms/?q=10-10
- [ ] Create design for PDF information on Find a VA Form detail pages - example:  https://www.va.gov/find-forms/about-form-10-10ez/
- [ ] Let PM know when you're ready to schedule a Design Intent Review
- [ ] Present designs at Design Intent Review
- [ ] Incorporate feedback 
- [ ] Provide link to Sketch files in this ticket for future reference.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 please take a look at this issue, let me know if you have questions, and assign an estimate when you have a minute.  Thanks!

**Comment by callen2563** [comment]
@MarciMcGuireGCIO I estimated this one at a 4 to be on the safe side because I have a feeling there might be some back and forth with the design system team.

**Comment by MarciMcGuireGCIO** [comment]
You are the design expert!  I defer to your judgment!

**Comment by callen2563** [comment]
@joshkimux Hey Josh, I wanted to get this ticket on your radar. I'm wondering if you have any thoughts on the XFA browser issues and is there any thing I need to consider from an accessibly perspective before I dig into UX solutions for PDF download instructions.

**Comment by joshkimux** [comment]
@callen2563 [this thread may be of interest to you in slack!](https://dsva.slack.com/archives/C52CL1PKQ/p1621606334136000)

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 as info -- this might end up being a good candidate for a new pattern since we're learning that this issue is persuasive across VA.gov.  

Anywhere that links to a VA form could have the same issue as digital signature in PDF forms becomes more common.  We have the same exact issue on Discharge Upgrade Wizard where a link to DD 149 PDF won't open and the user needs to download.

**Comment by callen2563** [comment]
This is one I idea I had on how to handle the PDF download link instructions:

![Dowload PDF_Modal_desktop2x](https://user-images.githubusercontent.com/68560244/119185034-31bdd900-ba44-11eb-82b3-73e74bc78377.png)

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 Looks good!  What does the link on the page look like (before the modal is displayed)?   Also, we need to instruct users to right click + download since PDFs hosted outside VA.gov can't be downloaded with a left-click in some browsers as a security measure.

**Comment by callen2563** [comment]
So for this version the the user would click the "download PDF" link on the FAF page. This modal with pop up with what ever instructions or details they need. In the case of the right click.. I would like to know from @joshkimux if there are any accessibility issues I should consider there. But for those types of outside hosted links I would think an info alert or help text would have to sit above those links.

**Comment by callen2563** [comment]
@MarciMcGuireGCIO I just added another design option above..

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @callen2563 ! Also looping in @johnhashva and @zacharymorel.  I suppose we'll have to see what they say at the design intent review.

**Comment by joshkimux** [comment]
> @MarciMcGuireGCIO So for this version the the user would click the "download PDF" link on the FAF page. This modal with pop up with what ever instructions or details they need. In the case of the right click.. I would like to know from @joshkimux if there are any accessibility issues I should consider there. But for those types of outside hosted links I would think an info alert or help text would have to sit above those links.

For modals, we'll need to use a `button`. The main concern here is that folks won't be expecting a modal to pop up upon activating a link. I'd suggest we explore alternative methods of letting folks know that Adobe Reader is required. 

For example:

`Download VA form XYZ, Adobe Reader Only` (downloads pdf)
`Request a different or accessible format v` (help accordion)

**Comment by jenniferlee-dsva** [comment]
@MarciMcGuireGCIO @johnhashva - just providing some additional information about this situation. It is not only non-VA forms on other domains. Most of the VBA forms are hosted on benefits.va.gov. That also reads as a different domain. This is a browser behavior, so we have no control over this outside of moving those forms to be hosted on a va.gov domain. (Like VHA forms for instance.) 

History around this: 
Many many years ago, VBA did try to move their forms to a new domain. But when they did that, thousands of links to forms went to 404s. (I think they did not plan ahead or realize that redirects should have been put into place along with the domain URL change.) 

Also - wrt @callen2563 's FPO - it is not the form fill that is not supported by browsers. It is the type of Adobe Acrobat format. I wouldn't even mention something like that, as it is incredibly complicated to explain. It's not even accurate to say that the format is invalid or outdated, because technically the dynamic XFA format is a MORE RECENT Adobe format. 

(The issue is that this more recent Adobe format isn't supported by the Int'l Standards Org - ISO - and thus browsers haven't adopted supporting it. It is basically a conflict between Adobe and the ISO, with consumers sort of caught in the middle. Thus, not only VA is affected.) 

The ultimate solution of course is to migrate VA forms into Drupal, so that PDF url's, domain, file names, etc. are managed by form managers from Drupal, which would allow your team to standardize some of these things with built-in technical governance. 

We can communicate to VA form creators that they should use the older Adobe format that is supported by the ISO (that older format is also fillable in the browser).  But the likelihood of all of these forms being recreated in a supported format is very low unless OIT issues a policy memo of some kind. @boris-ning-usds and I tried to determine a solution/proposal for VA, but we hit a wall and didn't get to that last hurdle.

**Comment by jenniferlee-dsva** [comment]
One more thing: 

So Nick Sullivan was able to create FE logic to have the PDF form links initiate a download (instead of letting the browser try to open it in a browser window and thus error on some PDFs).  

This does work -- but only on forms that are on the va.gov domain. I.e., per above comment, this FE logic doesn't work on forms that are 1/ in that XFA dynamic format and 2/ are also hosted on another domain. That 2nd part is a browser security thing, not a VA thing. 

Have you considered simply providing a link to the help page about this issue? https://www.va.gov/resources/what-if-im-having-trouble-opening-a-pdf/

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @jenniferlee-dsva.  We met with the VA forms stakeholders and their Adobe reps last week, and it seems there is currently no plan to depart from the XFA format.  They invested in Adobe Experience Manager/Forms Designer after Adobe LiveCycle was sunset and have a desire to use digital signature more widely. 

A simple download is to address the XFA issue on VA.gov-hosted PDFs.  The additional context of **right click  + download** was added for the issue where the form is hosted outside VA.gov and some browsers won't download without that additional "consensual" action.  There is code that can force download, but all browsers don't support it. `<a href="myfile.pdf" download="myfile.pdf">My PDF Link To Download</a>. `

We have considered a link to a centralized page; I proposed that as a pattern initially to avoid having multiple versions of PDF information floating around (like the one you linked, and this guy --> https://iris.custhelp.va.gov/app/answers/detail/a_id/3047/~/problems-with-.pdf-forms-on-va-website 😱 .)  

We don't know if the page approach is accessible, but  I'm attending VSP office hours this week for input on the same issue on another product.

Thanks again!

**Comment by MarciMcGuireGCIO** [comment]
Adding this suggested text provided by one of the VA's Adobe reps.  

"...In the meantime, I wanted to share some sample language and an example image for your consideration to instruct users to download the PDF form vs. opening it in the browser. 

 

Icon PDF - PDF downloadable form only  Adobe PDF forms are available for download only.  To view or save these PDF forms, please use Adobe Acrobat or Reader.

When saving a file, be sure to use the Save function of Adobe Reader rather than the web browser's save.

 

In addition to the language above, the web page could force the download of the PDF when there is a requirement to fill, save and sign.  The following is a technical example of how to do this <a href="myfile.pdf" download="myfile.pdf">My PDF Link To Download</a>. "

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 @bethpotts @DanielleThierryUSDSVA cc @johnhashva  There has been a lot of churn on this ticket, so I'll summarize:
- Instructions to right click + download should cover all scenarios regardless of where the PDF is hosted.   We don't have to provide technical reasons; it's just going to work in Acrobat Reader
- There can be NUMEROUS PDF links on the same page - ex: https://www.va.gov/find-forms/?q=10, so we need to be mindful of how this is going to look in those cases.  
- We'd like to repurpose this same language on Discharge Upgrade wizard on pages where they've instructed Veterans to download a PDF form.
- (blue sky) It would be nice to have a centralized PDF help page so that anyone who is provided PDF forms can point to it and it can be maintained in one place.
- Adobe provided some language in my comment immediately above.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 here is some verbiage for mock-ups. TOTALLY forgot that mobile has not right click!!


[PDF icon] Download and complete VA form XYZ by right clicking (long press on mobile), saving and opening in Adobe Acrobat Reader.

**Comment by joshkimux** [comment]
@MarciMcGuireGCIO Heads up to make it a tad more complicated, we'll also need to account for keyboard only users who don't have access to a right click or long press.

**Comment by MarciMcGuireGCIO** [comment]
Ahh @joshkimux the plot thickens. It may make sense to just say "download
and save..." and have a separate "PDF help" link to a page with detailed PDF information. IDK if that approach is accessible though.

**Comment by callen2563** [comment]
@MarciMcGuireGCIO I'm uploading the latest mock up here although I know the wording for right click or ctl click will need to change..

![Dowload PDF_Modal_desktop_on page Copy](https://user-images.githubusercontent.com/68560244/119404787-47ced200-bcae-11eb-9f56-90f5b47bddc9.png)

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @callen2563 I'm not sure either.  So, turns out there is a PDF help page already in R&S that we could point to, maybe sort of like this (forgive the awful mockup; I don't have nice tools anymore).  

![image](https://user-images.githubusercontent.com/73354907/119408338-8adf7400-bcb3-11eb-8bf4-1fb0f728ab80.png)

**Comment by callen2563** [comment]
Updated mock up.. 
Help text could either have a link included that goes to this page or it includes the information that is on this page..
https://www.va.gov/resources/what-if-im-having-trouble-opening-a-pdf/

![Dowload PDF_Modal_desktop_on page Copy 2](https://user-images.githubusercontent.com/68560244/119412357-bebd9800-bcb9-11eb-8a79-ca6661c09e8f.png)

**Comment by jenniferlee-dsva** [comment]
> We have considered a link to a centralized page; I proposed that as a pattern initially to avoid having multiple versions of PDF information floating around (like the one you linked, and this guy --> https://iris.custhelp.va.gov/app/answers/detail/a_id/3047/~/problems-with-.pdf-forms-on-va-website 

fysa @MarciMcGuireGCIO - All IRIS content is slated to retire in 2021. So the RS article is the source of truth for this pdf troubleshooting sitch.

**Comment by MarciMcGuireGCIO** [comment]
@jenniferlee-dsva do you happen to know who maintains the content for that page?

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 this looks like a solid start.  @johnhashva - there are a lot of questions swirling around this due to the different browser scenarios that have to be considered (right-click/ctrl-click/long press), which are not currently included in the [RS article about PDFs](https://iris.custhelp.va.gov/app/answers/detail/a_id/3047/~/problems-with-.pdf-forms-on-va-website).

We want to show this at a Design Intent review and get some feedback/direction on how to proceed, but what are your initial thoughts?

**Comment by johnhashva** [comment]
I agree -- what seems so simple is actually quite complex, especially when you add our requirements for accessibility -- so design intent is warranted.

Just one more thought for that design intent/consideration: @callen2563 -- can you look at how other Gov sites are handling this use case for comparison (and possible rationale)?  Example: [ IRS.gov](https://apps.irs.gov/app/picklist/list/formsPublications.html) has instructions at the top which link to this help page/article: https://www.irs.gov/help/downloading-and-printing.

Here's how State of NY provides guidance -- https://tax.custhelp.com/app/answers/detail/a_id/224/~/how-do-i-download-pdf-documents-to-my-computer%3F
