### ISSUE TITLE
Add tests to 4 more liquid.filter functions

### ISSUE THREAD

**Issue by gescobardev** [department-of-veterans-affairs/va.gov-team#24986]
Identify 3 funcitions within `liquid.js` that need tests written for them. 
Tests can be found in `liquid.unit.spec.js`

Functions to test: 

1. `benefitTerms()`
2. `findCurrentPathDepth()`
3. `hashReference()`
4. `fileExt()`

**Acceptance Criteria**
All tests must pass

**Comment by gescobardev** [comment]
PR ready for review
https://github.com/department-of-veterans-affairs/content-build/pull/168

**Comment by mpelzsherman** [comment]
Let's go ahead and delete the unused functions. Thanks!
