### ISSUE TITLE
Use Github API to retrieve and store Accessibility Testing activity data in BigQuery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#24982]
# Description
* Use the Github API to retrieve all data related to Accessibility testing and store it in BigQuery. We want to store as much data as possible from Github accessibility testing activities to enable us to create new metrics or combine data in novel ways in order to create new metrics in the future.
* Recreate similar data structures in BigQuery as the data is extracted from Github
* Create views of raw data in BigQuery to feed cards in Domo
* Use GitHub API to retrieve issues related to Accessibility by filtering on the label `508/Accessibility`
  * Use the `508-defect-0` through `508-defect-4` labels for analysis
  * Use other 508 labels that classify the a11y category for analysis as well -- ex. `508-issue-cognition`
  * Example tickets:
    * https://github.com/department-of-veterans-affairs/va.gov-team/issues/25019
    * https://github.com/department-of-veterans-affairs/va.gov-team/issues/25015

## BigQuery Features to Keep in Mind
* Queries cost money based on how much data is retrieved for the query (1GB = $.01 or so)
* BigQuery is designed for de-normalized data structures. We should prefer this where possible. But, don't be afraid to use lookup tables to convert code / other signifiers to a more human readable format.

**Comment by rjohnson2011** [comment]
6/11 Update: Synced with Holden regarding passing data to BigQuery and modifying the Github Accessibility Metrics to be compatible with what the BigQuery service is expecting.

**Comment by rjohnson2011** [comment]
6/14 Update: Refactored Github Accessibility Metrics into 2 services, one as an array returning all accessibility related issues with key info, and the other with an object of overall metric tallies. I am creating a PR today and will work with Holden to migrate the data into BigQuery.
Service one sample response:
```
{
    title: '508-defect-1 ❗ Launchblocker [SCREENREADER]: In footer, Tagalog and Espanol are pronounced in an english accent ',
    body: '# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)\r\n' +
      '\r\n' +
      "<!-- It's okay to delete the instructions above, but leave the link to the 508 defect severity level for your issue. -->\r\n" +
      '\r\n' +
      '## Feedback framework\r\n' +
      '\r\n' +
      '- **❗️ Must** for if the feedback must be applied \r\n' +
      '- **⚠️ Should** if the feedback is best practice \r\n' +
      '- **✔️ Consider** for suggestions/enhancements \r\n' +
      '\r\n' +
      '## Definition of done\r\n' +
      '\r\n' +
      '1. Review and acknowledge feedback.\r\n' +
      '1. Fix and/or document decisions made.\r\n' +
      '1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.\r\n' +
      '\r\n' +
      '## Point of Contact\r\n' +
      '\r\n' +
      '<!-- If this issue is being opened by a VFS team member, please add a point of contact. Usually this is the same person who enters the issue ticket. -->\r\n' +
      '\r\n' +
      '**VFS Point of Contact:** Josh\r\n' +
      '\r\n' +
      '## Details\r\n' +
      '\r\n' +
      '<del>There appears to be a bug where the string "href" is appended to the `lang` attribute. This causes the screen reader to announce "Espanol" and "Tagalog" in English. Removing the "href" ahead of "lang" will fix the issue. </del>\r\n' +
      '\r\n' +
      'Edit: not a bug, just missing the `lang` attribute which is separate to the `hreflang`\r\n' +
      '\r\n' +
      '> Hints at the human language of the linked URL. No built-in functionality. Allowed values are the same as the global lang attribute.\r\n' +
      '\r\n' +
      '## Acceptance Criteria\r\n' +
      '\r\n' +
      '- [ ] `lang` attribute is added on top of the `hreflang`\r\n' +
      '\r\n' +
      '## Screenshots or Trace Logs\r\n' +
      '\r\n' +
      '<img width="1516" alt="Screen Shot 2021-06-03 at 9 22 49 AM" src="https://user-images.githubusercontent.com/14154792/120652298-a5e97b00-c44d-11eb-838a-4936c4d527fa.png">\r\n' +
      '\r\n',
    url: 'https://api.github.com/repos/department-of-veterans-affairs/va.gov-team/issues/25593',
    created_at: '2021-06-03T13:26:01Z',
    closed_at: '2021-06-10T01:13:03Z',
    state: 'closed',
    defect_num: '1',
    labels: [
      '508-defect-1',
      '508/Accessibility',
      'Sprint 48',
      'frontend',
      'vsa-content-localization',
      'vsa-language assistance & resources'
    ],
    creator: 'joshkimux',
    assignee: 'youngfreezyVA'
  }
```
Second service with key overall metric data:
```
{
  totalIssuesAndPRs: 500,
  totalAccessibilityIssues: 20,
  totalAccIssuesOpen: 17,
  totalAccIssuesClosed: 3,
  totalIssue1Defect: 3,
  totalIssue2Defects: 7,
  totalIssue3Defects: 0,
  totalIssue4Defects: 1
}
```

**Comment by holdenhinkle** [comment]
Code has been integrated into the application.

Data is being grabbed from GitHub via a GitHub Actions scheduled event that runs at midnight every day. It is then parsed and pushed to BigQuery.

**Comment by rjohnson2011** [comment]
Working on adding charts to Domo (https://va-gov.domo.com/page/486021553) in regards to desired graphs mentioned in chat with Peter/Joe:
```
Graph displaying all issues tagged a11y (horizontal axis is defect0-4 and vertical axis is # defects)
Graph displaying all issues tagged a11y (horizontal axis is team and vertical axis is # defects). There's a lookup table with team names, testrail project IDs, and I think GH labels in the schema already.
Open vs. Closed a11y issues by team
Oldest open a11y issue by team
```
Worked on adding additional team metrics related to open/closed issues into BQ.

**Comment by rjohnson2011** [comment]
Made improvements to the appearance of Domo dashboard, added references, and created an additional chart that compares Total va-gov issues and pull requests with those labeled '508/Accessibility'. 

Completed demo presentation yesterday and today had conversation amongst team to refactor Accessibility page computational metrics from JavaScript to SQL.

**Comment by pjhill** [comment]
@rjohnson2011 -- per the feedback from analytics, they are looking to leverage our GH issues import mechanism for their own purposes. They have the following list of attributes that they're interested in --

1. issue.number,
2. issue.state,
3. labels.name,
4. issue.created_at,
5. issue.updated_at,
6. issue.closed_at

I imagine that we are already interested in all of those attribute, and wouldn't be inclined to throw them out anyway. But, there they are at any rate.

**Comment by rjohnson2011** [comment]
Thanks @pjhill . We're already pulling in all these attributes except issue number and updated_at. I'll pull in these additional params.

**Comment by rjohnson2011** [comment]
This is completed.
