### ISSUE TITLE
[Bug] Notice of Disagreement - Issues add y/n page pre-selects Yes option

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#24990]
## What happened?
On Staging **[Request a Board Appeal form](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction)**, **Issues for review** [add y/n] page pre-selected **Yes**, despite having an issue already selected on the previous [select] page.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [use any of the following]
  - `vetsgov+test239@id.me` (Medge)
  - `vetsgov+test233@id.me` (Cara)
  - `vetsgov+test238@id.me` (Nerea)

## Steps to Reproduce
- URL: https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction
- Test User _(if applicable)_: [see **Specs** above]
- Ensure no automatic form-prefills occur:
  - Disable browser auto-fill feature.
  - Start a new request if in-progress alert is displayed.
- Advance to **Issues for review** [select] page, completing any required fields and clicking **Continue** on the way.
- On **Issues for review** [select] page, select an **issue-card**, then **Continue**.
- On **Issues for review** [add y/n] page, observe that **Yes** option is preselected, even though an issue has been selected on previous page.
- **Continue** to **Issues for review** [add] page, and observe that you can't **Continue** further without manually adding an issue.

**Video capture**:

https://user-images.githubusercontent.com/587583/118907570-9b1eda00-b8d4-11eb-98f4-8435293164c8.mp4

## Desired behavior
- [ ] With an issue already selected on previous page, **Issues for review** [add y/n] page should not pre-select **Yes** option.  [Once an issue's been selected, manual-add should be optional.]

**Screenshot** [design-prorotype](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/615292857):
![nod-spec-issue-add-not-preselected](https://user-images.githubusercontent.com/587583/118908088-91e23d00-b8d5-11eb-8aba-0d17bfc11f9a.png)

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Mottie** [comment]
Fixed in https://github.com/department-of-veterans-affairs/vets-website/pull/17323

**Comment by tlei123** [comment]
Validated fixed on Staging.

![image](https://user-images.githubusercontent.com/587583/119582087-cdb74f80-bd78-11eb-8002-45800a6285fe.png)

cc @Mottie @vhenry07
