### ISSUE TITLE
Establish list of Stop Words

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24994]
## Description

In preparation to remove stop words we need to establish a list of common words that search engines filter out after processing.

The default English Stopwords used in Elasticsearch are:
> a, an, and, are, as, at, be, but, by, for, if, in, into, is, it, no, not, of, on, or, such, that, the, their, then, there, these, they, this, to, was, will, with 

[Source: [Use Elastic Search + Stop Words](https://qbox.io/blog/how-to-use-elasticsearch-remove-stopwords-from-query/)]

## Tasks

- [ ] Define list of stop words 

## Definition of Done

- [ ] List is ready to share with search.gov to be removed as part of (#24892)

**Comment by mgleo** [comment]
In addition to the Elasticsearch's default stop words, I'm proposing that the following stop words are also added: 
**about, am, any, become, became, can, could, did, do, does, doing, get, getting, had, has, have, how, how's, I, I'm, it's, its, just, my, myself, so, than, that's, them, too, we, who, what, what's, when, where, which, who, who's, whose, why, would, yet, you**

This will help when general questions/phrases such as "how to get prescriptions" are entered in search.

@denisecoveyduc @johnhashva
