### ISSUE TITLE
Remove Redirect

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#24992]
## Description

Remove redirect to home page when an empty query is provided

## Background/Context

- Search UI Consistency has removed the gray button and therefore it will remove the redirect. 

## Definition of Done

- [x] Remove redirect 
- [x] Land users on search results page with no results showing
- [x] Tier 3 (No Socks validation necessary)

**Comment by srsuddath** [comment]
The re-direct has been removed!
