### ISSUE TITLE
CT Sandbox: Loading indicator icon overlaps loading indicator text

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#25007]
## What happened?
The loading indicator for the redesigned comparison tool is not rendering correctly and does not match va.gov standards
See image
![image](https://user-images.githubusercontent.com/1094999/118999092-f80fa400-b957-11eb-9084-ccbbb0d287c4.png)

## Steps to Reproduce
1. Access the [staging CT redesign sandbox](https://staging.va.gov/gi-bill-comparison-tool-sandbox/)
2. Type any search term into the search bar
3. Click "search"
4. Observe the loading indicator

## Desired behavior
Tthe loading indicator matches the below example:
![Screen Shot 2021-05-20 at 10 42 31 AM](https://user-images.githubusercontent.com/1094999/118999263-1d9cad80-b958-11eb-9837-8f5ee5a2d9f4.png)

**Comment by zurbergram** [comment]
Name search loading on staging
![Screen Shot 2021-06-07 at 11 26 34 AM](https://user-images.githubusercontent.com/1094999/121044108-4065f900-c783-11eb-88d9-3c66cb4fb75c.png)

Location search is also fixed

**Comment by sonntag-adam** [comment]
Testing passes QA. No longer occurring in staging.
