### ISSUE TITLE
[FE] Onboarding: Taylor Mitchell

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#25000]
## Background

Welcome, Taylor! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to team members

Please schedule a short chat with each of these folks (internal mtgs can come from Ad Hoc or GCIO account):

- [x] AJ Jakabcin
- [x] Erik Hansen
- [x] Lihan Li
- [x] Tressa Furner
- [x] Liz Lantz
- [x] Samara Strauss

### Docs to review

**Authenticated experience docs**

- [x] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/charter.md)
- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/product-outline.md#north-star-objectives)
- [x] [Roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/authenticated-experience/roadmap)

### Products/Projects

Here are some helpful resources on what we're currently working on:

**My VA 2.0 redesign**

- [x] [My VA 2.0 product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va#readme)
- [x] [My VA staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)

**Communications preferences** (aka Notification preferences)

- [x] [Communications preferences project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/README.md)
- [x] [MVP documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/product/communications-permissions-mvp-definition.md)

**Preferred medical facility**

- [x] [Preferred medical facility project outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/preferred-facility/README.md)

**Profile**

- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [Profile folder and list of products](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile)
- [x] [Profile staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile.md)

**Comment by Samara-Strauss** [comment]
@tmitchellgcio — feel free to reach out to team members to schedule individual chats. We haven't pre-scheduled anything for you, so you can do this as time allows. Let me know if you have questions!

**Comment by tmitchellgcio** [comment]
Absolutely. Will try to set those up soon
