### ISSUE TITLE
New VAOS - Record VCR Cassettes for     get '/locations/:location_id/clinics'

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#25017]
As a continuation of the work done in #23885, VCR cassettes need updating to reflect data retrieved from the hosted new VAOS service.

- VCR cassette data reflects actual data hosted by the new VAOS service
- Adjustments are made to the code-base such that vets-api exposes accurate data value/schema to vets-website
- Documentation is updated to reflect any code changes

**Comment by ajmagdub** [comment]
This was already worked and merged into master in [PR-6851](https://github.com/department-of-veterans-affairs/vets-api/pull/6851)
