### ISSUE TITLE
Discovery around tightening Jenkins access for new users.

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2501]
right now, if we give users access to Jenkins they have full access. Is there a way we can tighten our access, so that when people do have access they don't have the keys to the kingdom right out the gate?

**Comment by jbritt1** [comment]
@benniemosher I haven't done a deep dive into this yet, but a quick google search found something called "role-based authorization strategy plugin". I am unsure what it is, how it works, etc. at this time, but wanted to drop a note here.

**Comment by jbritt1** [comment]
Further example of the above note: https://github.com/jrichardsz/jenkins-tips-snippets-templates/blob/master/kblearningacademy_com_jenkins_Role%2BStrategy%2BPlugin.pdf.

**Comment by jbritt1** [comment]
More reading material on this: https://jenkins.io/doc/book/system-administration/security/.

**Comment by jbritt1** [comment]
Step 1: Install GitHub Authentication Plugin in Jenkins

**Comment by jbritt1** [comment]
Step 1: Install GitHub Authentication Plugin
![image](https://user-images.githubusercontent.com/56260532/67513985-f261b780-f669-11e9-9f1b-a01da78fdd7a.png)

Step 2: Create a GitHub OAuth Application
https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/

Step 3: Manage Jenkins' global security settings and select GitHub Authentication Plugin for "Security Realm". Insert client ID and client secret from the new OAuth app in GitHub
![image](https://user-images.githubusercontent.com/56260532/67514280-75830d80-f66a-11e9-99ef-a4d0b05831d9.png)

Step 4: Still working out a piece that seems to require admin user(s) to be explicitly defined. 

##Posting this for now as notes, still a WIP##

**Comment by jbritt1** [comment]
After some testing and digging around on the real Jenkins node, I found we are already manually maintaining a group of admin users. What I believe at this time will give us the ability to still allow everyone to read, but only admins to create, configure, build, cancel, etc. is the use of matrix-based security for authorization. This can still leverage the GitHub authentication integration, but will block users from being able to do many of the functions in the console unless explicitly allowed.
