### ISSUE TITLE
Remove more copy from Appts Onboarding screen

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25029]
## Acceptance Criteria
1. On Onboarding Screen #2 ("Easily manage your health appointments"), remove the following bullet point:
     - Delete: "• Get reminders"

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 5/27/2021 - Looks good.  Closing.
