### ISSUE TITLE
New VAOS - Record VCR Cassettes for put '/appointments/:id'

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#25020]
As a continuation of the work done in #23883, VCR cassettes need updating to reflect data retrieved from the hosted new VAOS service.

- VCR cassette data reflects actual data hosted by the new VAOS service
- Adjustments are made to the code-base such that vets-api exposes accurate data value/schema to vets-website
- Documentation is updated to reflect any code changes

**Comment by ajmagdub** [comment]
waiting for [VAOSR-1978](https://issues.mobilehealth.va.gov/browse/VAOSR-1978) to be implemented

**Comment by laurenernest** [comment]
@grossb1 @ajmagdub it looks like [VAOSR-1978](https://issues.mobilehealth.va.gov/browse/VAOSR-1978) is done. is this work unblocked or is it also now blocked by [VAOSR-2119](https://issues.mobilehealth.va.gov/browse/VAOSR-2119)?

**Comment by ajmagdub** [comment]
With VAOSR-1978 done this task should be able to update the appointment's status field. 

It's interesting though VAOSR-2119 is about not having data in the cancellation reason field, but the current VAOS Service swagger doc does not specify how to submit a cancel reason when updating the appointment.

**Comment by ajmagdub** [comment]
Per conversation with Brad Crosby. CKM blocks requests from untrusted domains for PUT requests are block which prevents us from recording interactions with the VAOS Service. Looks like we may have to mock our Put/Cancel request on this ticket and test out the Cancel appointment function during full end to end testing with the Vets Website

**Comment by ajmagdub** [comment]
Changed from writing a generic update endpoint to a cancel appointment endpoint since the VAOS Service will only accept cancel status update. This also follows the way it was done in the vets-api VAOS V0 appointment cancel endpoint.
