### ISSUE TITLE
Error | Accept new Terms & Conditions

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25035]
## User story
As a user I need to have accepted terms and conditions to user secure messaging, and if not be directed on how to do that.

This most likely occurs when the user first attempts to access the SM page in the mobile app.

## Acceptance Criteria
1. Display an error for Secure Messaging pages when a user has not yet accepted the terms & conditions to use SM. This is triggered by the following API error: 
     - SM135: # 'User is not eligible because they have not accepted terms and conditions or opted-in' detail: 'You have not accepted the MHV Terms and Conditions to use secure messaging'
2. Create UX/UI based on the linked designs
     - Header 2: "You're required to accept the current terms and conditions"
     - Content is hard-coded
3. Hyperlink: "Go to My HealtheVet"
     - Selecting this button opens the following link, out-of-app, in the device's browser: https://www.myhealth.va.gov/mhv-portal-web/user-login?redirect=/mhv-portal-web/web/myhealthevet/secure-messaging
4. Mock this out with user +1414

## Designs
https://adhoc.invisionapp.com/console/share/YM10HVPXJE7V/631950368

## Discovery ticket
#24125

## Accessibility Implementation Guidelines 

- Mark "You're required to accept the current terms and conditions" as Header 2

**"Go to My HealtheVet" link**
- Title= go to myhealthevet (_note for dev: please adjust as needed so that it is pronounced like "my healthy vet"_)
- accessibilityRole= “link”
- acessibilityHint= "accept the current terms and conditions. this page will open in your device's browser"

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by bessgreen** [comment]
Note for QA: test on user +1414 (mock data)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/3/2021 - Looks good on iOS and Android except for a minor error logged.  Closing.

Error: https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/25628
