### ISSUE TITLE
Accessibility Feedback for Staging Review [Authenticated Experience - My VA Dashboard 2.0]

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#25033]
# Accessibility Feedback for Staging Review [Authenticated Experience - My VA Dashboard 2.0] 

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh and Angela

**Comment by joshkimux** [comment]
<img width="869" alt="Screen Shot 2021-05-21 at 12 10 24 PM" src="https://user-images.githubusercontent.com/14154792/119167228-9cafe580-ba2d-11eb-89cd-34f410c80492.png">

👏

**Comment by joshkimux** [comment]
Structure is very sound. Links list is easy to navigate. 👏 

https://user-images.githubusercontent.com/14154792/119171926-3d54d400-ba33-11eb-8104-5fdc94ea45a1.mov

**Comment by joshkimux** [comment]
<img width="902" alt="Screen Shot 2021-05-21 at 12 52 04 PM" src="https://user-images.githubusercontent.com/14154792/119172011-5fe6ed00-ba33-11eb-8412-b60d6bc07b98.png">

**Comment by Samara-Strauss** [comment]
It looks like all tickets related to this epic have been addressed, so I am going to close this.
