### ISSUE TITLE
CLP Redirect Request: VA.gov/covid-vaccine-questions

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25048]
### Instructions
We want to capture the following URL variations to permanently 301 point to the new, to be published Campaign Landing Page for VA COVID Vaccine Confidence initiative to be published at: https://www.va.gov/initiatives/have-questions-before-you-get-your-COVID-19-vaccine

Additional guidance about this request is seen here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24799

### Requesting team info
*Danielle Thierry (the business user/stakeholder for the CLP)*

### Implementation date
Date new URL(s) will be live: May 24, 2021
Would like both Vanity URL and Redirects live on 5/24. 

Destination page will be live on May 24: 
VHA will be promoting the redirect http://va.gov/covid-vaccine-questions — so when a user clicks/types that URL they should go to https://www.va.gov/initiatives/have-questions-before-you-get-your-COVID-19-vaccine 

Please indicate when the change/redirect(s) needs to be implemented"
- [x] Other - Please indicate timing :  NLT May 24

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Redirect URL  |  Vanity URLs to be created
---  |  ---
Redirect URL will be: https://va.gov/initiatives/have-questions-before-you-get-your-COVID-19-vaccine
Vanity URL will be: https://va.gov/covid-vaccine-questions

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [x] Implementation team: Implementation team completes work 
- [x] Implementation team: Implementation pushed live and redirect is validated in production
- [x] Requesting team: Ticket is closed

**Comment by johnhashva** [comment]
@brianalloyd Just changed some references to Trust CLP.

**Comment by DanielleThierryUSDSVA** [comment]
This looks great to me, @brianalloyd! Only thing I noticed was I think the "s" is missing in the "https://" for this link:

 http://va.gov/covid-vaccine-questions

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/devops/pull/9202

**Comment by brianalloyd** [comment]
Campaign is now live, closing ticket in support. Redirects have been verified.
