### ISSUE TITLE
RFC for call center issue reporting automation

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#2504]
## User Story or Problem Statement
As a vets-api engineer, I need to further investigate and discover automation solutions for reporting call center issues from IRIS and Salesforce

## Goal
When reported issues from Salesforce, IRIS, etc are in need of further triaging, additional steps are required to report the data. The goal is to further automate the reporting process to avoid tedious and lengthy processes.

## Acceptance Criteria
- [ ] Investigate CSV export solutions
- [ ] Investigate issue grouping solutions 
- [ ] Investigate Salesforce & IRIS processes

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
Closing as this is no longer a priority based on discussion we had long ago on triage team when it existed.
