### ISSUE TITLE
Redirect Request - VAMC Pittsburgh

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#25044]
### Instructions
- Requests for URL changes/redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some changes/redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
These redirects are related to the CMS work to lock down the IA within the VAMC sites.  As part of that work, there are a number of URLs that need to be updated as a result of correcting their placement within the IA.  

### Requesting team info
CMS / Facilities

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the change/redirect(s) needs to be implemented"
- [x] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination or New URL
---  |  ---
/pittsburgh-health-care/about   |	/pittsburgh-health-care/about-us
/pittsburgh-health-care/ambulatory-care-center-floor-plans   |	/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/ambulatory-care-center-floor-plans
/pittsburgh-health-care/billing-insurance   |	/pittsburgh-health-care/billing-and-insurance
/pittsburgh-health-care/caregiver-support   |	/pittsburgh-health-care/health-services/caregiver-support
/pittsburgh-health-care/committee-member-information   |	/pittsburgh-health-care/research/committee-member-information
/pittsburgh-health-care/consolidation-building-floor-plans	   |	/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/consolidation-building-floor-plans
/pittsburgh-health-care/covid-19-vaccines   |	/pittsburgh-health-care/programs/covid-19-vaccines
/pittsburgh-health-care/daisy-award   |		/pittsburgh-health-care/programs/daisy-award
/pittsburgh-health-care/history   |		/pittsburgh-health-care/about-us/history
/pittsburgh-health-care/hj-heinz-iii-campus-map   |		/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/hj-heinz-iii-campus-map
/pittsburgh-health-care/homeless-veteran-care   |		/pittsburgh-health-care/health-services/homeless-veteran-care
/pittsburgh-health-care/intensive-rehab-program   |		/pittsburgh-health-care/programs/intensive-rehab-program
/pittsburgh-health-care/interdisciplinary-pain-rehabilitation-program   |		/pittsburgh-health-care/programs/interdisciplinary-pain-rehabilitation-program
/pittsburgh-health-care/intermediate-low-vision-clinic   |		/pittsburgh-health-care/programs/intermediate-low-vision-clinic
/pittsburgh-health-care/internships-fellowships/forms   |	/pittsburgh-health-care/work-with-us/internships-and-fellowships/required-paperwork-for-your-training
/pittsburgh-health-care/jobs-careers/internships-fellowships/forms   |  /pittsburgh-health-care/research/forms-and-general-information
/pittsburgh-health-care/jobs-careers/internships-fellowships/trainee-coordinators   |	  /pittsburgh-health-care/work-with-us/internships-and-fellowships/trainee-coordinators
/pittsburgh-health-care/leadership/	   |	/pittsburgh-health-care/about-us/leadership
/pittsburgh-health-care/lgbt-veteran-care	   |	/pittsburgh-health-care/health-services/lgbt-veteran-care
/pittsburgh-health-care/mental-health-care   |	/pittsburgh-health-care/health-services/mental-health-care
/pittsburgh-health-care/minority-veteran-care   |		/pittsburgh-health-care/health-services/minority-veteran-care
/pittsburgh-health-care/mission-vision	   |	/pittsburgh-health-care/about-us/mission-vision
/pittsburgh-health-care/new-employee-information	   |	/pittsburgh-health-care/work-with-us/jobs-careers/new-employee-information
/pittsburgh-health-care/new-researchers   |		/pittsburgh-health-care/research/new-researchers
/pittsburgh-health-care/nurse-residency-programs	   |	/pittsburgh-health-care/work-with-us/internships-and-fellowships/nurse-residency-programs
/pittsburgh-health-care/patient-advocates   |		/pittsburgh-health-care/health-services/patient-advocates
/pittsburgh-health-care/performance   |		/pittsburgh-health-care/about-us/performance
/pittsburgh-health-care/research-and-development-contacts   |		/pittsburgh-health-care/research/research-and-development-contacts
/pittsburgh-health-care/returning-service-member-care   |		/pittsburgh-health-care/health-services/returning-service-member-care
/pittsburgh-health-care/suicide-prevention   |	/pittsburgh-health-care/health-services/suicide-prevention
/pittsburgh-health-care/surgery-service   |		/pittsburgh-health-care/health-services/surgery-service
/pittsburgh-health-care/university-drive-campus-map   |		/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/university-drive-campus-map
/pittsburgh-health-care/women-veteran-care	   |	/pittsburgh-health-care/health-services/women-veteran-care
/pittsburgh-health-care/work-with-us/internships-fellowships	   |	/pittsburgh-health-care/work-with-us/internships-and-fellowships
/pittsburgh-health-care/work-with-us/internships-fellowships/psychology-internships-and-fellowships	   |	/pittsburgh-health-care/work-with-us/internships-and-fellowships/psychology-internships-and-fellowships
/pittsburgh-health-care/work-with-us/jobs-careers	   |	/pittsburgh-health-care/work-with-us/jobs-and-careers

### Definition of done
- [x] Requesting team: Above information is provided and issue is tagged and assigned appropriately 
- [x] Requesting team: All appropriate VA stakeholders are notified of pending redirect 
- [x] VSP IA: Request is vetted and documented and implementation plan is clear - *@ VSP IA*
- [x] VSP IA: Request is assigned to appropriate team for implementation - *@ VSP IA team*
- [x] Implementation team: Implementation team completes work 
- [x] Implementation team: Implementation pushed live and redirect is validated in production
- [x] Requesting team: Ticket is closed

**Comment by mnorthuis** [comment]
@brianalloyd @kelsonic These have been reviewed and are ready to go!  Please hold once the PR is done for coordination with @kevwalsh on timing.

**Comment by brianalloyd** [comment]
Completed, closing ticket in support.
