### ISSUE TITLE
Sitewide content feedback in prep for usability testing

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#25055]
Here's some basic feedback as you get ready for usability testing. Would like to get your opinion if you think this approach will work:

**Intro page**
1/ Please add (COE) to the end of the H1 and rearrange the subhead as shown here.
H1: Apply for a VA home loan Certificate of Eligibility (COE)
Subhead: Request for a Certificate of Eligibility (VA Form 26-1880)

2/ Subway map
1. **Check your eligibility**

Make sure you meet our VA home loan eligibility requirements before you apply for a COE.

You may be able to get a COE if you meet these requirements. You:
- Didn’t receive a dishonorable discharge, **and** 
- Meet the minimum active-duty service requirement based on when you served
[Check your service requirements](https://www.va.gov/housing-assistance/home-loans/eligibility/)
_Note to Jim: I'd love to put in an anchor link to take users right to the accordions for the service requirements, but I'll need to add an H2 to the static eligibility page for that to work. Just mentioning here for a future iteration._

2. **Gather your information**

Here's what you'll need to apply:

**If you’re a Veteran**, you’ll need a copy of your discharge or separation papers (DD214).

**If you’re an active-duty service member**, you’ll need a statement of service—signed by your commander, adjutant, or personnel officer—showing this information:

- Your full name
- Your Social Security number
- Your date of birth
- The date you entered duty
- The duration of any lost time
- The name of the command providing the information

**If you're a current, former, or discharged member of the National Guard or Reserves, or the surviving spouse** of a Veteran who died on active duty or who had a service-connected disability, find out what information you'll need to apply.
[You'll need to gather this information] _Additional information element_ 

INFO TO GO IN ADDITIONAL INFORMATION:
**If you’re a current or former activated National Guard or Reserve member,** you’ll need a copy of your discharge or separation papers (DD214).

**If you’re a current member of the National Guard or Reserves, and have never been activated,** you’ll need a statement of service—signed by your commander, adjutant, or personnel officer—showing this information:

- Your full name
- Your Social Security number
- Your date of birth
- The date you entered duty
- Your total number of creditable years of service
- The duration of any lost time
- The name of the command providing the information

**If you’re a discharged member of the National Guard and were never activated,** you’ll need:

- Your Report of Separation and Record of Service (NGB Form 22) for each period of National Guard service, **and**
- Your Retirement Points Statement (NGB Form 23) and proof of the character of service

**If you’re a discharged member of the Reserves and were never activated,** you’ll need:

- A copy of your latest annual retirement points, **and**
- Proof of your honorable service

**If you’re a surviving spouse who qualifies for home loan benefits,** you’ll need the Veteran’s discharge documents (DD214)—if available—and:

If you’re receiving Dependency & Indemnity Compensation (DIC), you’ll need to fill out and send us a Request for Determination of Loan Guaranty Eligibility—Unmarried Surviving Spouses (VA Form 26-1817).
Download VA Form 26-1817 (PDF)
**Or**
If you’re not receiving DIC benefits, you’ll need to send us all of these:

- A completed Application for DIC, Death Pension and/or Accrued Benefits (VA Form 21P-534EZ), **and**
- A copy of your marriage license, **and**
- The Veteran’s death certificate

Download VA Form 21P-534EZ (PDF)
Find out if you qualify for home loan benefits
Get military service records online

**Comment by bethpottsVADEPO** [comment]
@sporeboy Thanks for reworking the intro page. It works great! Here are a couple edits:

Capturing what I slacked you:

Here's what you'll need to apply:

**As a Veteran,** you'll need...
**As an active duty service member,** you'll need...
etc.

1/ The third bullet is missing "you'll need."
2/ Remove bolding from "and" in the last two bullets.
3/ Add periods at the end of each bullet since they're now complete sentences. 
4/ Change "What is" to "What's" in the additional info question: What's a statement of service?"
5/ For No. 1 in the subway map, let's start with a verb: Check your service requirements

For other screens:
6/ Introduction Signed-in: Can you make the same updates you made to the previous 2 screens in the H1, subhead, H2 (Follow these steps to apply for a VA home loan Certificate of Eligibility), and subway map?
7/ Automatic COE, for the alert about needing more info: I like the header, but since (COE) will be in the H1, we can use COE in the header here instead of spelling it out (We have all the information we need for your COE). I'd suggest this for the paragraph of text: 
You don't need to apply for a COE because we already have all the information we need. You can download your COE now. 
[Download your COE (PDF) 0.20 MB]
8/ I think I heard that we are starting to add the size of the file as I see you did with 0.20 MB. We'll need to figure out how to show/format that since we also already have in place a content pattern of indicating in parentheses that the doc is a PDF. What do you think about the way I've done it above--does that work?
9/ For testing, will you delete "This document will also be available on..."?
10/ **What if I need to make changes to my COE?** If you need to make changes or corrections to your COE--or are applying for a restoration of entitlement--you'll need to complete and submit Form 26-1880.
[Make changes to your COE with Form 26-1880]

**Note to Jim:** I'm not sure you need to include the second sentence under "What if I need to make changes"--"We'll process your application and notify you...."

**Comment by sporeboy** [comment]
Edits called-out in this issue were implemented, then were superseded by further revisions.
