### ISSUE TITLE
[Bug] 10-10CG - Representative Document file-upload error

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#25058]
## What happened?
On Staging **[Apply for the Program of Comprehensive Assistance for Family Caregivers](https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction)** form, **Representative document** [upload] page, file-upload _intermittently_ triggered errors.  For me, the errors occurred twice out of 8 uploads.

This was **different** behavior from already-Closed #24029

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Large (>10 Mb) sample files* for testing:
  - PDF: https://www.learningcontainer.com/sample-pdf-files-for-testing/#Sample_pdf_download_10_MB
  - JPG: https://www.learningcontainer.com/sample-jpeg-file-download-for-testing/#Extra_Large_Sample_JPEG_File
  - PNG: https://www.learningcontainer.com/sample-png-image-for-testing/#Large_Sample_PNG_File

## Steps to Reproduce
- URL: https://staging.va.gov/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/introduction
- Advance to **Representative document** [upload] page, completing required fields and clicking **Continue** on the way.:
  - Add at least a Primary Family Caregiver
  - On **Representative document** [options] page [just before upload page], choose **Yes... upload... now**.
- On **Representative document** [upload] page, click **Upload**, select & upload a large file [>10 Mb].  [You may need a few tries to trigger the error.]
- Observe that _sometimes_ the error below is displayed.

**Screenshot**
![sar-bug-pdf-error](https://user-images.githubusercontent.com/587583/119060905-05448700-b988-11eb-8d66-f45931adcdea.png)

## Desired behavior
Large-file-uploads should not error-out.

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

\*I've downloaded and scanned these sample files w/ my anti-virus software and they're clean, but you're encouraged to scan your own downloads just to be safe.

**Comment by ala-yna** [comment]
@tlei123 do you have more documentation on when errors occurred vs. not?

**Comment by tlei123** [comment]
@ala-yna ,  sorry, no.  There doesn't seem to be any pattern to how/when the uploads errored-out.  Both small (<10Mb) & large (>10Mb) files intermittently threw this **Network request failed** error.

**Comment by Mottie** [comment]
@tlei123, I thought that NoD submission-error was resolved? I doubt this upload error is related to NoD uploads since we have a exclusive upload endpoint for our form.

**Comment by tlei123** [comment]
> @tlei123, I thought that NoD submission-error was resolved?  I doubt this upload error is related to NoD uploads since we have a exclusive upload endpoint for our form.

@Mottie , thx & never mind about this one then.  Re. NoD submission error, that was Darius' **Should** item #2 in the [QA-Feedback ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25212) -- "...determine of it's a bug" -- not a launch-blocker.  We can discuss that further as needed on Slack.

**Comment by tlei123** [comment]
Closing this now.  Not a bug in our app, but rather intermittent issues with the Staging API attachments service.
