### ISSUE TITLE
[FE] My VA: 508-defect-2 [MAGNIFICATION]: "Go to your profile" may be missed by magnification tool users

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#25052]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a low vision, magnification tool user, I expect there to be no major gaps between important content on the page so I don't accidentally miss it while scanning a page.

## Details

For Veterans who use [magnification tools like zoomtext](https://www.youtube.com/watch?v=ojtiVj78QPw) that enlarge only a portion of the screen at a time (unlike using a browser's built in zoom in feature), content that exists across large gaps may be missed.

The "go to your profile" link is particularly far off to the right across a gap of white space which may cause these users to miss it completely.

<img width="1792" alt="Screen Shot 2021-05-20 at 5 11 22 PM" src="https://user-images.githubusercontent.com/14154792/119050361-be5a8f80-b98f-11eb-9a15-838e18477c85.png">

## Acceptance Criteria

- [ ] ~"go to your profile" is not separated from the rest of the content significantly~
- [ ] "got to your profile" is immediately below the "My VA" header on the left side of the screen

## Proposed Solution
Updating this per Josh's comment on 8/5: solution is to move the "go to your profile" link to be immediately below the "My VA" header on the left side of the screen

~Consider setting a maximum width to the container that holds go to your profile or look into other design solutions.~

<img width="1348" alt="Screen Shot 2021-05-20 at 5 13 23 PM" src="https://user-images.githubusercontent.com/14154792/119050341-b864ae80-b98f-11eb-9a2c-21a5a9da06f6.png">

**Comment by tressaellen** [comment]
@erikphansen @ajakabcin - I propose we move the 'Go to your profile' link to be under the My VA header. 

<img width="639" alt="Screen Shot 2021-08-04 at 3 12 46 PM" src="https://user-images.githubusercontent.com/58752772/128255581-f3ee94c4-50ab-4921-861a-69d54a71b817.png">

**Comment by joshkimux** [comment]
@tressaellen this would fix the issue!

**Comment by erikphansen** [comment]
@joshkimux this can be validated on staging

**Comment by joshkimux** [comment]
<img width="954" alt="Screen Shot 2021-08-13 at 10 43 55 AM" src="https://user-images.githubusercontent.com/14154792/129374624-ddf8b930-cc8f-41dd-b097-25578fc653c8.png">
Validated. Y'all rock! 👏
