### ISSUE TITLE
Screen reader not announcing "24/7" correctly

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25053]
## What happened?
On the Veteran Crisis Line page, the screen reader is not announcing "24/7" correctly. Instead of "twenty four seven", its announced as:
- iOS (VoiceOver): "twenty four slash seven"
- Android (Voice Assistant): "twenty four sevenths"

## Specs:
- Device: iPhone 11, Samsung Galaxy S9

## Steps to Reproduce
1. Turn on the device's screen reader tool
2. Navigate to the VCL page
3. Tap on Header 2: "We're here anytime, day or night - 24/7"

## Desired behavior
Screen reader announces "24/7" as "twenty four seven"

## Acceptance Criteria
See desired behavior. 

## Bug Severity
- 4 - Low

## Linked to story
n/a

## Screen shot(s) and additional information
n/a

**Comment by digitalken** [comment]
PASS 6/25/2021 - Sounds good on both iOS and Android.  Closing.
