### ISSUE TITLE
Re-add duplicate file error

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25054]
## Acceptance Criteria
1. Re-add the "Duplicate file" error (#22679) to the SM attachments flow
2. Ensure that this error state displays if there are multiple errors with the file (#22891)

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/3/2021 - Looks good on iOS and Android.  Closing.
