### ISSUE TITLE
Update expiration - HLR

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#25051]
## Description
**Slack thread:** https://dsva.slack.com/archives/C52CL1PKQ/p1621543104105000

This PR updates an expiration date.

## Testing done
N/A

## Screenshots
N/A

## Acceptance criteria
- [x] Update expiration date.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

**Comment by kelsonic** [comment]
PR merged, will go out with daily deploy tomorrow

**Comment by brianalloyd** [comment]
Validated and closing.
