### ISSUE TITLE
[FE] My VA: 508-defect-3 [COGNITION]: Applications in progress card's form number should describe the heading and be simplified to be less redundant

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#25069]
# [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a sighted user with a cognitive disability, I want to see less clutter and redundancies so I can better parse information.
As a screen reader user, I want to know that the number is indeed a form number without having to go backwards from the heading itself.

## Details

Because the application title within the card is a heading, screen reader users who navigate by heading will not know the number is indeed the _form_ number unless it is tied to the heading using `aria-describedby`. 

For example, they'll hear "Application for VET TEC (22-0994)", but they won't know 22-0994 is the explicit _form number_ because _form_ is placed _above_ the heading itself.

For sighted users with cognitive disabilities, seeing the form number "22-0994" repeated twice could potentially be confusing.

## Acceptance Criteria

- [ ] The form number is removed from the application name
- [ ] "Form #" above the application name is tied to the application name using `aria-describedby`

## Steps to Recreate

Log in to staging test user 10 and turn on a screen reader. Navigate by headings to the application name. Confirm "form" is not present in the announced string.

## Proposed Solution (if known)

As suggested in the acceptance criteria, remove the form number from the application name and tie the form number above the application name to the application name using `aria-describedby`

For example:

`<p id="unique-id">FORM 22-0994</p>`
`<h4 aria-describedby="unique-id">Application for VET TEC</h4>`

Demo:

https://user-images.githubusercontent.com/14154792/119160077-e399dd00-ba25-11eb-9b9a-3e7b10f52bf4.mov

**Comment by erikphansen** [comment]
@joshkimux this is ready to be validated on staging

**Comment by joshkimux** [comment]
<img width="1275" alt="Screen Shot 2021-08-17 at 1 36 27 PM" src="https://user-images.githubusercontent.com/14154792/129774187-87793a44-3f21-460f-b913-8160025079e7.png">

Wonderful! Thank you @erikphansen !! 🥳
