### ISSUE TITLE
Backend Analytics Requests

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2506]
## User Story or Problem Statement
How might we _____________ ?

## Goal
_What outcome(s) do we want to see?_

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] Define the metrics that we are requested that are exist in the backend and not in GA

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andreahewitt-odd** [comment]
@joanneesteban Can this ticket be closed? Per grooming on 12/18.

**Comment by joanneesteban** [comment]
High priority Backend data request already sent to the Backend Tools team. Will be in discussion with BE on future data points. Closing this ticket.
