### ISSUE TITLE
[NEW] Add note on 10-10CG intro page

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#25073]
**Is it possible to link this to the toggle so that only the 50% of users who see the POA workflow will see this note?**

Please add the following text on the[ intro page](https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666459/simulate/sitemap?mode=i).

**Note:** A legal representative, or someone with power of attorney, can fill out this application on behalf of the Veteran. They’ll need to sign the application. They'll also have a chance to submit documentation to show their status as a legal representative.

![Screen Shot 2021-05-21 at 10.27.17 AM.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/4a1b3472-8a82-476b-a2a5-2f3c212018c0)

**Comment by Dene-human** [comment]
@dat-gcio Before you implement this- can you please make sure that this note can be tied to the toggle so that only users that receive the POA workflow will see this note.

**Comment by dat-gcio** [comment]
@Dene-human I haven't started this, but this work can be tied behind the canUpload1010cgPOA toggle.

**Comment by dat-gcio** [comment]
@Dene-human Here is the [review instance](http://6937f57f871edc07be95217be481907f.review.vetsgov-internal/family-member-benefits/apply-for-caregiver-assistance-form-10-10cg/vet-3). You can toggle the canUpload1010cgPOA flag [here](http://6937f57f871edc07be95217be481907f-api.review.vetsgov-internal/flipper/features/can_upload_10_10cg_poa). This is just for this specific review instance, so flipping it doesn't affect dev/qa/prod or anything like that.

**Comment by Dene-human** [comment]
Pretty nifty! Looks good.

**Comment by dat-gcio** [comment]
Validated in prod.
