### ISSUE TITLE
Loading screen for Claims File Upload submission

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25077]
## User Story
As a user, I want see a loading screen that tells me that the app is submitting the evidence to support my claim. 

## Acceptance Criteria
1. Selecting the "Confirm upload" button (from both the File & Photo upload paths) will trigger a loading screen while the app works to submit the request
     - Pull in loading screen CC
     - Copy: "We're submitting your request"

## Designs
Similar design: https://adhoc.invisionapp.com/d/main/#/console/21165105/446525918/inspect

## Dev checklist
- [ ] UX/UI
- [ ] Accessibility
- [ ] Add tests

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/3/2021 - Looks good, closing.
