### ISSUE TITLE
Build messaging into request flow

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2508]
As a veteran, I want to be able to message my scheduler when I request an appointment so that I can tell them more context about my situation, which will get me connected to the right care that I need as fast as possible.

**Comment by rtwell** [comment]
I believe this page is now common to both the Direct Schedule _and_ Request flows:

![image](https://user-images.githubusercontent.com/12564977/67719910-23632480-f9a9-11e9-8e2e-3259edf9d458.png)

![image](https://user-images.githubusercontent.com/12564977/67719981-442b7a00-f9a9-11e9-8adb-7654bf90cee3.png)

![image](https://user-images.githubusercontent.com/12564977/67719991-48f02e00-f9a9-11e9-8f8e-cbf2546b97bc.png)

**Comment by markgreenburg** [comment]
@peggygannon also need to think about policy language around the fact that VAOS is *not* intended for emergency / urgent care, and schedulers may not even see your request for 48 business hours.

Intent of the field is to account for issues in scheduling (can't do Wednesdays), why you want the appointment more specifically, if you're not sure you picked the right clinic, etc.

**Comment by peggygannon** [comment]
@markgreenburg, @rtwell , @goldenmeanie  
Please see content recommendation below. I'm not sure if I got the text box messaging 100% accurate, so please let me know. 

New appointment *(sentence case (no caps)*

Why are you making this appointment? 
{radio buttons}

Routine or follow-up visit
a new medical issue
or a concern or question about my medication
My reason isn’t listed 

{text box if 
Routine or follow-up visit
I have a new medical issue
I have a concern or question about my medication selected} 

Please give us additional details about your appointment. This will help us schedule your appointment with the right provider or facility. Please also let us know if you have any scheduling issues, like you can't have an appointment on a certain day. 

{text box if 
reason not listed selected} 

Please give us additional details about what type of appointment you’re looking for. This will help us find you the right provider or facility for your appointment. Please also let us know if you have any scheduling issues, like you can't have an appointment on a certain day. 



{Emergency content}
**The VA appointment tool is for non-emergency appointments**
The VA appointment tool lets you schedule, request, and view some of your VA health care appointments online, like routine check-ups or doctor visits.
Don’t use the VA appointment tool if you have a medical emergency and need to see a doctor right away. 

**If you have an urgent medical need, please:**

Call [911], **or**
Call the Veterans Crisis hotline at [800-273-8255] and press 1, **or**
Go to your nearest emergency room or VA medical center. [Find your nearest VA medical center](va.gov/find-locations/)

**Comment by rtwell** [comment]
thank you for this @peggygannon ! I will update the comps and drop them here. 

One concern I have about the radio button language—these buttons also serve as labels later on in the flow, seen here:

![image](https://user-images.githubusercontent.com/12564977/67864095-74832d80-fafb-11e9-8fd9-34dcd6bff487.png)

I'm wondering if the words on the radio buttons should mirror the labels verbatim or if listing them one way on this page vs a different way on the review / success / list views would be confusing? cc @lalexanderson-dsva

**Comment by peggygannon** [comment]
@rtwell ah, thank you for letting me know that the  radio buttons are labels later in the flow.  

To reduce confusion we could do below, if it's possible from a dev point of view to have the labels be different. I had tweaked the radio button language to be more conversational and clear. 

But would like @lalexanderson-dsva thoughts if this would work? 

{button} Routine or follow-up visit
{label later in flow} Routine/follow-up visit

{button} I have a new medical issue
{label later in flow} New medical issue

{button}I have a concern or question about my medication
{label later in the flow} Medication concern

**Comment by narin** [comment]
@rtwell @peggygannon I plan to work on this tomorrow (Friday). Are there updated comps? I think I can get by with the copy changes for the existing fields, but not sure about the emergency content.

**Comment by rtwell** [comment]
i would connect with @jbalboni

**Comment by jbalboni** [comment]
@rtwell @narin I don't really understand when and where emergency contact info should appear on this page. Like the Narin said, the copy updates for the field names seem ok, but I haven't seen anything about emergency content on this page.

**Comment by rtwell** [comment]
i'm thinking something like this:

![image](https://user-images.githubusercontent.com/12564977/68968709-436c5380-07b1-11ea-94e2-7e78c03ca403.png)
