### ISSUE TITLE
VVC VA Facility Details Displays Facility Address & Phone which implies the appt is at that facility

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25084]
1.  Log into VAOS.  Upcoming Appts display.
2.  Select VA Video Connect at a VA location. View details.  
3.  Actual Response  details shows the facility and directions link.  Expected response; detail should not show the facility name and directions link.  

--Video appointments at a VA location should use the same logic as VA appointments (using 'sta6aid' is used to display the facility address & phone number).  
--The bug right now is that they do not use that logic.  
--Video appointments at VA location is using the logic used for as VA Video Connect at home which uses the facilityId to display the VAMC name and phone number.  
--  Using the facilityId means it will always list the parent site and the appointment may not be at that site

facilityId is the parent site #
sta6aid is will show the 2-3 digit code at the end to indicate child/CBOC.  

Here is an example:
"facilityId": "984",
        "sta6aid": "984GD",

**Comment by jbalboni** [comment]
The bug is that the facility we choose for CLINIC_BASED appointments is based on `appointment.videoData.facilityId`, which is not always the `sta6aid` (it falls back to the vista site id). We should instead use `appointment.location.stationId`
