### ISSUE TITLE
Move downloaded file contents out of file object

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va.gov-team#25088]
Discussed in [#24022](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/24022).

### Details

The content build downloads all the images and other files associated with site content and places them in Metalsmith's `files` object. The file contents are stored as binary data in buffers referenced by the object. As the site grows, this represents a large amount of data which increases the memory footprint of the build process substantially.

We can free up all this RAM by storing downloaded file contents on disk instead. File metadata such as the path will still be stored in the `files` array so the build process can reference this as needed, such as when checking for broken links.

### Acceptance Criteria

- [x] Downloaded file metadata is still stored in the `files` array, but file contents are stored on disk
- [x] Build completes with no errors
- [x] All images and other files are present in the build directory, in the proper location, after the build completes

**Comment by theodur** [comment]
After testing removing downloaded file contents from the file object, total memory usage decreased by around 1 GB for both local builds and on 48k nodes in CI. The [PR](https://github.com/department-of-veterans-affairs/content-build/pull/216) with these changes has been merged.
