### ISSUE TITLE
Atlas Appointments Missing Facility - No Way for Vet to Know Facility to Contact to Cancel

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#25087]
Log into VCM create Atlas appt
View in VAOS.  View details.

Need to make changes instructs the veteran to contact facility to reschedule or cancel.

There is no facility listed.  Just an Atlass street address and phone number.  How do you contact an address to cancel an appointment?![AtlasNoSiteContactToCancel.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/4a9fc80c-7773-4fb8-b8f8-781d81535176)

**Comment by jbalboni** [comment]
@outerpress Do we want to change the language in the blue box to make this clearer? "This facility" I think is supposed to refer to the ATLAS facility.

**Comment by outerpress** [comment]
Ideally we could provide the contact info for canceling/managing their ATLAS appts here.

Looking through some of the ATLAS guidance it seems like they're asking Veterans to call their "ATLAS scheduling team" to manage appointments. It also seems like there are only about 11 ATLAS facilities, [each with different contacts listed](https://connectedcare.va.gov/partners/atlas).

I'll ask around, but if there's already established reasons why we can't do this or get this data, lemme know :)

**Comment by jbalboni** [comment]
@outerpress We do get a list of ATLAS facility contacts for each appointment, so we could use that, if those are the appropriate people for canceling the appointment.

**Comment by outerpress** [comment]
Thanks @jbalboni - and just to confirm, we're not displaying those ATLAS contacts anywhere right? (I looked around, but couldn't find an ATLAS appt to check the cancelation message.)

**Comment by jbalboni** [comment]
@outerpress Correct, we weren't sure when you would need to use those contacts as a patient, so we never show them.

**Comment by outerpress** [comment]
@jbalboni got some clarification on this, the guidance is for Veterans to call the VAMC where they scheduled the appointment if they want to make changes.

So if we could do something like the below, where [Facility name] and number are the info from the VA facility (not the ATLAS site) associated with the appt, that should work. I think we can probably use this pattern for all our VAVC appt types as well.

![va-appt-vavc-atlas_UPCOMING](https://user-images.githubusercontent.com/2536801/119548609-3ee00e00-bd4b-11eb-8740-7ad5c9e7d3b5.png)

cc @laurenernest
