### ISSUE TITLE
Uplaods get sent to CARMA even when user says they will upload later

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#25083]
**Reproduction steps**
- Add the veteran's information
- Add a caregiver's information
- When prompted to upload a file:
  - Select "Yes, upload now"
  - Upload a file successfully
  - Go back
- Select "Yes, upload later"
- Complete the form

On submit, you'll see the POA Attachment ID is incorrectly sent in the submission payload.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17300) to make sure to remove document ID on form submit. Added edge case to unit test.

**Comment by dat-gcio** [comment]
@LinnJS I retested in Staging and it looks good. Gonna close this out.
