### ISSUE TITLE
UX/UI issues for SM accordions w/ attachments

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25097]
## What happened?
There are multiple UI issues w/ SM accordions that have attachments. Some icons overlap w/ text, some data is not displaying (date/time), and attachment links overlap and don't fully display. See screenshot below.

This issue also appears to be specific to longer message threads (the example below is a thread with 15 messages). Shorter threads that contain 1-2 messages don't seem to be affected.

## Steps to Reproduce
1. Log in with +41
2. On the Sent page, select the following message:
     - Test: Your lab results
     - 21 May 2021 @ 1012 PDT
3. View the content in the accordions - namely, the newer messages at the bottom of the screen
4. Notice the following:
     - Attachment icons overlap with message body
     - Message date/time is not visible next to the attachment icon
     - Attachment links are not fully visible 

## Desired behavior
1. SM accordions with attachments should mirror* the format of this design: https://adhoc.invisionapp.com/console/share/YM10HVPXJE7V/600511912
2. The following should be visible in an SM accordion w/ attachments:
     - Attachment icon + date/time
     - Message body
     - Attachment link(s) w/ file name + size

*exception: the linked design does not display an accordion arrow in the top right corner, but this arrow _should_ display in the build.

## Acceptance Criteria
See desired behavior.

## Bug Severity
- 3 - Medium

## Linked to story
#24736

## Screen shot(s) and additional information
![Screen Shot 2021-05-21 at 10.14.41 AM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/2b68b1a4-1b4a-4104-a127-197ad857861e)

**Comment by digitalken** [comment]
PASS 5/27/2021 - No longer seeing any issues with icons overlapping, etc.  Closing.
