### ISSUE TITLE
VAMC System pages not filtering featured events correctly

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#25091]
## What happened?
In some cases, VAMC system pages show events that should not be shown.
https://www.va.gov/pittsburgh-health-care/
![image](https://user-images.githubusercontent.com/5752113/119183735-7e081980-ba42-11eb-9ed9-23f62b4d233e.png)

![image](https://user-images.githubusercontent.com/5752113/119184338-3fbf2a00-ba43-11eb-8487-3fec5fd44b21.png)
The page should show:
-  A published event flagged as featured (fieldFeaturedValue = 1)
- The next upcoming published event if there are none flagged as featured 

The page NOT should show:

- archived events
- draft events
- past events

## Steps to Reproduce
- URL:https://www.va.gov/pittsburgh-health-care/
- Have no featured upcoming event set
- Have no upcoming event
- Have only past events.

## Desired behavior
Veterans should only see events that they have the option to attend.

## Acceptance Criteria
For featured events on both main system page and events list page:
- [ ] Never show unpublished events
- [ ] Never show past events
- [ ] Only show upcoming events
- [ ] Featured events are prioritized over unfeatured
- [ ] Next upcoming event if nothing is featured
- [ ] PM/PO will validate

**Comment by mpelzsherman** [comment]
The current https://www.va.gov/pittsburgh-health-care/ page looks fine to me.

It would be helpful to have a series of steps to reproduce with a tugboat instance.

**Comment by mpelzsherman** [comment]
Steps to reproduce:

1. In Tugboat, find a past event for Pittsburgh Health Care
2. Check the "Featured" checkbox in the "Feature This Content" section on a past event
3. View the Pittsburgh Health Care page while pointing to tugboat and note that the featured/past event now shows up.

**Comment by mmiddaugh** [comment]
I validated this in Tugboat using an event in Wilkes-Barre with "Featured" checked in the "Feature This Content" section. . It displays when the date is in the future and does not when in the past.
