### ISSUE TITLE
Design Feedback - Staging Review [Authenticated Experience - My VA Dashboard 2.0]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#25096]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Thanks for all your hard work!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Most of the text links are a hybrid of the Design Systems approved styles (eg. not bold but have chevron). Use [active link styles](https://design.va.gov/experimental-design/action_links#active-links) (chevron and bold) or default (not bold and no chevron) link styles. I added some screen shots below but this would apply to all text links.
- ![Screen Shot 2021-05-21 at 1.58.45 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/ec340a02-5e52-4ace-b345-b3d260d65712)
- ![Screen Shot 2021-05-21 at 11.59.10 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/130c303f-bedb-4199-ae2f-9cf10d893ecf)
- ![Screen Shot 2021-05-21 at 12.29.55 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/e0c212a6-6ec0-4702-a91b-c8abda7d72bc)

**Should:**
- 'Applications in progress' and 'VA benefits you might be interested in' are coded as an H3 but overwritten to look like H4. 'Disability compensation' is coded as an H4 but overwritten to look like an H3. Content should be placed in the order of importance and the hierarchy of H tags used to communicate that. 
- ![Screen Shot 2021-05-21 at 12.36.15 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/563fe966-baf3-416b-a134-3b6a2ca60090)

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by ajakabcin** [comment]
this was resolved via #28302
