### ISSUE TITLE
CT Redesign: Update name/location search functionality

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#25098]
As a developer, I need to update the search functionality in the CT sandbox with current CT functionality so that existing functionality is not lost.

## Assumptions: 
1. This work is completed in the CT sandbox found here: https://staging.va.gov/gi-bill-comparison-tool-sandbox/

## Acceptance Criteria
1. On the name search:
    a. The "Update tuition and housing estimates" widget keeps it's expanded/collapsed state on search.
    b. The "Refine your search" widget keeps it's expanded/collapsed state on search.
    c. The enter key executes a search
    d. Filters are applied to the search when pressing Enter Key, clicking Search, or clicking “Update Results” in “Refine your search”
    e. When executing a search, the page scrolls to the top of the search form.

2. On the location search:
    a. The "Update tuition and housing estimates" widget is collapsed on search.
    b. The "Refine your search" widget is collapsed on search.
    c. The enter key executes a search
    d. Filters are applied to the search when pressing Enter Key, clicking Search, or clicking “Update Results” in “Refine your search”
    e. When executing a search, the page scrolls to the top of the search form.
    f. If a map marker is clicked, the accordions are collapsed so the corresponding card is visible next to the map.

3. Selecting a value from the autocomplete menu (name or location) does not execute the search, it just populates the search field.

4. The following data is persisted so that if the URL is shared the same search is executed:
    a. The search tab name
    b. The free text name search value
    c. The free text location search value
    d. Refine your search values
    e. Search Radius (if on location search)

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
Already merged PRs that cover scrolling behavior, AC1, and accordion behavior
https://github.com/department-of-veterans-affairs/vets-website/pull/17543
https://github.com/department-of-veterans-affairs/vets-website/pull/17489

**Comment by delli-gatti-michael** [comment]
[Testrail test run](https://dsvavsp.testrail.io/index.php?/runs/view/1938)

**Comment by delli-gatti-michael** [comment]
Testing complete
