### ISSUE TITLE
In-app webview for COVID-19 button

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#25095]
## Acceptance Criteria
1. At the top of the Home page, update the copy for the **COVID-19 vaccines** card button:
     - Old copy: "Stay informed and help us prepare"
     - Update to: "Get your COVID-19 vaccine"
2. Update the routing so that the button points to: https://www.va.gov/health-care/covid-19-vaccine/
3. Update the UX so that selecting the button opens the link in an in-app web view
     - Hide the header/footer when the page displays in-app

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
PASS 6/3/2021 - Looks good on iOS and Android.  Closing.
