### ISSUE TITLE
[Bug] Notice of Disagreement - IE11 - Styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#25108]
## What happened?
In IE11, on Staging **[Request a Board Appeal form](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction)**, the following styling anomalies were found:
- (1) **Issues for review** [add] page: Added **issue-card** **Edit** button was mis-aligned.

## Specs:
- Device: Win10 pc
- Browser: IE11
- Test User _(if applicable)_: [use any of the following]
  - `vetsgov+test239@id.me` (Medge)
  - `vetsgov+test233@id.me` (Cara)
  - `vetsgov+test238@id.me` (Nerea)

## Steps to Reproduce
- URL: https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction
- Test User _(if applicable)_: [see **Specs** above]
- Advance to **Issues for review** [add y/n] page, completing required fields and clicking **Continue** on the way.
- On  **Issues for review** [add y/n] page, choose **Yes**, then **Continue**.
- On **Issues for review** [add] page, complete **required fields**, the **Save**.
- Observe that **issue-card**'s **Edit**button juts out of right card-border.

### Screenshots

(1) **Issues for review** [add] page:
![nod-bug-ie11-issues-for-review-add-issue-card](https://user-images.githubusercontent.com/587583/119243031-24721e80-bb18-11eb-902b-2ac9ea9be756.png)

## Desired styling
- [ ] (1) **Issues for review** [add] page: Added **issue-card** **Edit** button should display within issue-card border.

## Acceptance Criteria
[see **Desired styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [X] **Labeled with `Bug`**

**Comment by Mottie** [comment]
A partial fix has been merged into master. It'll be available on staging soon.

By partial fix, I mean, it works for screen sizes > 600 px.

**Comment by tlei123** [comment]
@Mottie , thanks much!  Fix validated on Staging.  I'm _thinking_ this can be Closed...

@pjhill @ddzz , what do you think about IE11 at <600px screen-width?  Sounds like an edge-case to me, since we're talking about desktop.  Pls. let us know your thoughts.

![image](https://user-images.githubusercontent.com/587583/119748718-62d64900-be4a-11eb-8e71-8dc1be28d5a0.png)

**Comment by tlei123** [comment]
> I just merged in a fix for the "Add an issue..." text that isn't wrapping on smaller screens.

@Mottie , was it this PR? #17370

Sorry, I just checked Staging w/ IE11 now, and this is what I'm seeing:

https://user-images.githubusercontent.com/587583/119880042-b2675400-bee0-11eb-9367-38834f098fff.mp4

**Comment by tlei123** [comment]
^ hi, @pjhill @ddzz , just wanna say this is NOT a functional bug.  The **Edit** button still works fine despite the visual mis-alignment.

Plus, this did NOT happen on the Android/iOS phones that I tested.

cc @Mottie @SKasimow

**Comment by Mottie** [comment]
I tried to fix it properly, but the `<dl>` wrapper doesn't match the width of the wrapper. I think it might be due to me using flexbox to make the `label` the same size as the entire element to make the blue outline clickable. It's not pretty, but it works.

I vote that we leave it like this since IE11 end-of-life will be next year anyway.

**Comment by pjhill** [comment]
> ^ hi, @pjhill @ddzz , just wanna say this is NOT a functional bug. The **Edit** button still works fine despite the visual mis-alignment.
> 
> Plus, this did NOT happen on the Android/iOS phones that I tested. I doubt if any current smartphones have IE11 either.
> 
> cc @Mottie @SKasimow

I'm not especially concerned about a horizontally constrained viewport for IE11. I'd hazard an educated guess that is a very slim slice of our userbase. I'm glad that you discovered the issue and that it is documented thoroughly for potential future resolution, but I agree that it is not a high priority issue at this time.

**Comment by tlei123** [comment]
Closing as out-of-date.
