### ISSUE TITLE
Provide global access to feature flags on app start up

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#25105]
## Issue Description
Currently, our feature flags are only available in redux state after a query returns. It would be better if the query happened on the server side first, as the app was starting up, and the features were published to the front end via a global variable. This would make feature flipping much easier, and more stable, because it avoids race conditions.

## Acceptance Criteria
- [ ] feature flag values are available as a global JavaScript variable when the app is started and any page is first rendered

**Comment by mpelzsherman** [comment]
See https://github.com/department-of-veterans-affairs/vets-website/pull/17308

**Comment by mpelzsherman** [comment]
I've found a solution for my ticket that seems to work, but I still think putting the feature flags in a global is a good idea. It's a lot less overhead and it eliminates potential race conditions.

**Comment by mpelzsherman** [comment]
Hi @meganhkelley . This is one of our top priorities for VSA. Looks like it's been added to your current sprint, but hasn't been assigned yet. Can we get a priority bump on this?

**Comment by meganhkelley** [comment]
Following up here! Platform FE Tools evaluated this and our recommendation is to not change this behavior at this time — please let us know your comments and/or questions! #27352

> After reviewing the request and gathering information about other difficulties with our current feature toggle system, I am recommending that we not do anything with this right now, but that we leave this open for reconsideration later.

> The main concern with our system right now is that there is a chance that a feature will load before the feature flag API request is returned. If the feature is inside of the React/Redux ecosystem, this should not be a concern, as the feature flags are stored in Redux. If the feature is outside of the React/Redux ecosystem, this is more of a concern, but still not something that is happening enough to cause large problems.

> Performing this call during our current build process (in order to have the feature flags loaded and ready when the applications load on the client) is not an option at this point. This would mean we wouldn't be able to turn feature flags on and off without a re-deploy of the applications and we wouldn't be able to use features like turning a feature flag on for only a percentage of users. These are essential features that we are not going to disable.

> A real resolution to this would probably require server-rendering this call, which is a big shift and would require a lot of work to re-think how our applications work (and how we want them to work). This may be something we want to revisit later.

**Comment by mpelzsherman** [comment]
> If the feature is inside of the React/Redux ecosystem, this should not be a concern, as the feature flags are stored in Redux.

There is still a chance that things can happen on the front end while waiting for the feature toggle query to return. Here's a screen shot from the VA.gov home page that demonstrates this:

![VA_gov_Home___Veterans_Affairs](https://user-images.githubusercontent.com/80267/130263501-f9a033e5-7e83-4f43-97ed-7d76b541ace7.png)

But I understand that our pages are not currently rendered server-side, and this would be a major architecture change. I'm fine putting this on ice for now, but it's something to keep in mind. There are other big [advantages to server-side rendering](https://medium.com/walmartglobaltech/the-benefits-of-server-side-rendering-over-client-side-rendering-5d07ff2cefe8), and if we ever decide to move in that direction, "thread safe" feature flipping would be another great benefit.

**Comment by timwright12** [comment]
Closing as there is another initiative for server side rendering
