### ISSUE TITLE
redis_caching concern set/get of nil object raises NoMethodError

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#25101]
We're seeing semi-frequent NoMethodErrors from the claims_and_appeals controller, and possibly other controllers that use the redis_caching concern:

http://sentry.vfs.va.gov/organizations/vsp/issues/6142/?query=is%3Aunresolved+assigned%3A%23mobile-api-team&statsPeriod=14d

The get_cached is trying to call `map` on `nil`. This despite the nil check on the data retrieved from the cache. My best guess:

1. Things are calling set_cached with data=nil
2. nil.to_json = "null" (i.e. the string "null")
3. That string is non-empty so result in get_cached is truthy
4. JSON.parse("null") = nil
5. nil.map -> NoMethodError

I can't quite see why claims and appeals would be setting a nil object into redis since it instantiates an empty array, but here we are.

I think to fix this:
- [ ] Add safe navigation operator to get_cached (e.g. `data&.map`) so it will return nil.
- [x] It probably doesn't make sense to stash a bunch of nulls in redis so set_cached should probably bail if data is nil.
- [x] Make sure this same bug doesn't exist in the messaging redis_caching mixin that was added for secure messaging.

**Comment by jperk51** [comment]
Didn't add the safe operator because the `unless data` check catches that since nils/nulls aren't being added to the cache anymore.
