### ISSUE TITLE
VRRAP: "This is the personal information we have on file for you." notification should be conditional

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#25116]
After starting the VRRAP form, the user is given a "This is the personal information we have on file for you." message to indicate that some fields have been automatically completed. This message should only display if the user does, in fact, have data that is used to pre-fill some of the fields on the form. Currently, the message is displayed to all users even when they do not have prefilled data.

### Steps to reproduce
1. Navigate to https://staging.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction
2. Sign in as a user with no prefill data (you may need to create an account)

### Expected results
1. "This is the personal information we have on file for you." is not present when there is no prefilled data

### Actual results
1. "This is the personal information we have on file for you." is present when there is no prefilled data

![Screen Shot 2021-05-24 at 9.17.34 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c51c1ec6-1579-4e0a-9b0e-824e554c28bb)

**Comment by ksantiagoBAH** [comment]
Currently waiting on a test user with no EVSS data.

**Comment by ksantiagoBAH** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/18171

**Comment by delli-gatti-michael** [comment]
testing complete
