### ISSUE TITLE
[Copy] Direct deposit: Remove beta copy from content page when we go 100% live

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#2511]
**Blocked until direct deposit goes live to 100% of VA.gov users**

### Definition of done

- [ ] Remove beta copy on the direct deposit content page (https://www.va.gov/change-direct-deposit/) when the direct deposit feature goes live to 100% of customers.

<img width="674" alt="Direct deposit remove beta copy" src="https://user-images.githubusercontent.com/34068740/66942390-fdd43380-f016-11e9-88a3-860598ae21b6.png">

**Comment by Samara-Strauss** [comment]
Cc/ @Justin-Pickett @lkoenigsberg @erikphansen for awareness

**Comment by Justin-Pickett** [comment]
@peggygannon our team received word recently that for the moment there will be a delay in the full launch of DD originally scheduled for 10/30. It is currently being postponed tentatively until 12/3/19 as we dive deeper into some more of error issues we've been tackling in recent weeks. We will keep you updated on when we need to remove the content. 

Adding @Samara-Strauss  and @lkoenigsberg for awareness to this comment for their awareness and any feedback they'd like to offer up as well.

**Comment by peggygannon** [comment]
@Justin-Pickett OK, thank you for the update. I appreciate it.

**Comment by Samara-Strauss** [comment]
@peggygannon we've gone to 100%! This beta copy can be removed whenever you have a moment.

**Comment by peggygannon** [comment]
@Samara-Strauss Awesome, yes, I saw that this morning!! I can remove that copy from the drupal file today. 

Just to confirm, this is the block of text that I'll be removing from /change-direct-deposit/ 

**We're testing out the direct deposit feature on VA.gov**
We're in the process of bringing direct deposit to VA.gov. This feature isn't available to everyone right now. If you see the direct deposit feature in your profile, you can update your direct deposit information from there. If you don’t see this feature in your profile, please go to eBenefits and sign in to change your direct deposit information.

**Comment by Justin-Pickett** [comment]
Just waiting for @Samara-Strauss to confirm the above copy is what is to be remove per @peggygannon's response, once a confirmation is received this ticket can be closed out.

**Comment by peggygannon** [comment]
thanks, @Justin-Pickett I realize after my note that Samara had already boxed in red (above) the copy to be removed above. Here's a screenshot of the update. Once this goes live tomorrow, then this ticket can be closed. 

![2019-12-17](https://user-images.githubusercontent.com/17554224/71041941-41165580-20df-11ea-903e-f74e73da5cee.png)

**Comment by Samara-Strauss** [comment]
This is perfect! We'll close after the 3:00 deploy/confirmation the copy is gone.

**Comment by Samara-Strauss** [comment]
Hey @peggygannon — the copy has been removed from production. YAY! However, I am still seeing it on staging. Do we need to do something else to remove it there?

**Comment by peggygannon** [comment]
@Samara-Strauss I'm not sure why it's still on staging..  I will check in about that with the devs and make sure it's also removed from staging.  Thanks for noticing this!

**Comment by Samara-Strauss** [comment]
Great, thanks! Keep me posted on what you find out.

**Comment by Samara-Strauss** [comment]
Copy has been removed from staging and production. Closing!
