### ISSUE TITLE
 Discharge Upgrade Wizard - Upgrade Military Branch Addresses

### ISSUE THREAD

**Issue by zacharymorel** [department-of-veterans-affairs/va.gov-team#25119]
## Issue Description
As the title says, two addresses need to be updated on the Steps of the Guidance page.
This covers # 3, 4 and 6) in the EPIC.

**EDIT:** https://dsva.slack.com/archives/C01DWJFD45D/p1621955228091100
No longer adding Army portal link.

## Front end tasks
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin

## Acceptance Criteria
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] Addresses are updated as spec'd [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25065#issuecomment-847050115) 
- [ ] Add Army Portal link.

**Comment by zacharymorel** [comment]
Blocked until content team gives input on the Link Verbage.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO @johnhashva This is on staging.

**Comment by MarciMcGuireGCIO** [comment]
These look good, @zacharymorel.  I'm good with this.  Thanks! 

Screen shots for reference:  Coast Guard 

![image](https://user-images.githubusercontent.com/73354907/119709363-1fb8ad80-be2b-11eb-85cf-5feb5402c082.png)![image](https://user-images.githubusercontent.com/73354907/119709374-221b0780-be2b-11eb-8313-1d1528e0e9fa.png)


Army

![image](https://user-images.githubusercontent.com/73354907/119709577-5db5d180-be2b-11eb-884b-d2ae40da1960.png)
![image](https://user-images.githubusercontent.com/73354907/119709853-ad949880-be2b-11eb-8b0c-61620236d8aa.png)

Navy/Marines

![image](https://user-images.githubusercontent.com/73354907/119710014-e03e9100-be2b-11eb-9738-614b7d9a2562.png)

![image](https://user-images.githubusercontent.com/73354907/119710337-3a3f5680-be2c-11eb-92f0-32c05d4ddd3c.png)


Air Force 

![image](https://user-images.githubusercontent.com/73354907/119710473-68bd3180-be2c-11eb-9d73-7ad9c164812f.png)

![image](https://user-images.githubusercontent.com/73354907/119710600-85f20000-be2c-11eb-9058-3bc3b86622ac.png)

**Comment by MarciMcGuireGCIO** [comment]
Sure can!
