### ISSUE TITLE
Content Feedback - Staging review - Virtual chatbot agent

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#25125]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
My feedback for the chatbot responses is captured in this spreadsheet: 

https://docs.google.com/spreadsheets/d/1J6hsR4m4XS6R-yxp1pmXUoVSv9F8qKX9vZn3xLda508/edit#gid=664478734

**Comment by peggygannon** [comment]
@murrayra Additional feedback for the new General response content is below. 

**Content recommendations**

1. Voice is inconsistent across the bot responses. 
Is it going to be in first-person voice or a third-person?
We refer to the chatbot as "it", but then some chatbot responses are in first person. See examples in bold.  


-  Ask **it** a question to get started. Recommend updating TO>  Ask the chatbot a question to get started. 

-  Thanks for chatting with **me**. Bye! Recommend updating TO>  Thanks for chatting with me. Goodbye. 

-  Ok, **I'll** start over. Recommend updating TO> OK, I'll start over.  <br>
------

2. What does "soon" mean  in this response below? Can we just direct users to call right away, based on their request to speak to someone? 

Soon you will be able to connect directly to a person who can help. In the meantime, to connect with someone right away, please call MyVA411 (VA’s main information line) 800-698-2411 Telecommunications Relay Services (using TTY) 711

See recommendation: 

~Soon you will be able to connect directly to a person who can help.~ To speak with someone right away, please call VA's main information line at 800-698-2411 (MyVA411). TTY (711).

-------

3. Please see recommended edits to this response:  

Thank you for participating in this study.  We're exploring how a virtual agent (or chatbot) can help you find answers on VA.gov.  This virtual agent is still in development. During this learning phase, you can help us protect your privacy and security by not typing any personal information into the virtual agent. This includes your name, address, Social Security number, or anything else that someone could use to identify you. 

For more information on this study, please review “What information are we collecting” on this page. For other privacy & security questions, go to our [Privacy, Policies, and legal information page](https://www.va.gov/privacy-policy/).
<br>
--------

4.  For the homeless response, I recommend you use content from the homeless alert on VA.gov  (see screenshot)

![homeless alert.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/e1d7954c-b8eb-4209-94fc-6c280cea5977)


------

5. inconsistent user of voice in this response. What voice will this chatbot be in? 
I've also edited the response to align with our styleguide

Thank you for asking this question. Unfortunately, **this virtual agent** doesn't have an answer right now.

Try asking your question in a different way, or you can ask questions like:
• Are x-rays covered?
• What’s my priority number?
• How do I file an appeal?

You can tell us what you think about the virtual agent at any time by clicking on the “Feedback” button located to the right of this page. Thank you.

**Comment by sstrassberg** [comment]
@peggygannon Thank you for providing great feedback. I've incorporated it into our spreadsheet and will update the content in PVA as well.
